Add translation of Compression Streams API
mdn/translated-content pull request #10009
Opened 2022-11-19 17:13 UTC by mikecat

### Description

Compression Streams API およびそこで使用される型を新規翻訳。

### Motivation

### Additional details

### Related issues and pull requests

2022-11-25 14:53 UTC, mfuji09 requested changes
1件の修正をお願いします。

2022-11-25 14:53 UTC, mfuji09 commented on files/ja/web/api/compression_streams_api/index.md
> +ビルトインの圧縮機能を使うことで、JavaScript のアプリケーションに圧縮ライブラリを含める必要がなくなり、アプリケーションのダウンロードサイズをより小さくできます。
「ライブラリ」→「ライブラリー」に修正をお願いします。

2022-11-25 17:17 UTC, mikecat commented on files/ja/web/api/compression_streams_api/index.md
> +ビルトインの圧縮機能を使うことで、JavaScript のアプリケーションに圧縮ライブラリを含める必要がなくなり、アプリケーションのダウンロードサイズをより小さくできます。
修正しました。

2022-11-26 01:09 UTC, mfuji09 commented
修正ありがとうございました。
修正が終わった時、ページ右上の Reviewers のところにある回転する矢印のボタン (Re-request review) ボタンを押しておいていただけると、早く確認ができますので、よろしくお願いします。

2022-11-26 01:09 UTC, mfuji09 approved these changes
OKです。

2022-11-26 01:09 UTC, merged