Add translation of WebHID API
mdn/translated-content pull request #10026
Opened 2022-11-20 11:20 UTC by mikecat

### Description

WebHID API `/docs/Web/API/WebHID_API` および関連ページを新規翻訳。

### Motivation

### Additional details

* 以下のページにおいて「Input レポートを受信」というのは疑問がありますが、一旦英語版に沿って訳しています。
  * `/docs/Web/API/HIDConnectionEvent`
  * `/docs/Web/API/HIDConnectionEvent/HIDConnectionEvent`
* 以下のページにおいて、下にサンプルが無いのに「以下のサンプル」というのは疑問がありますが、一旦英語版に沿って訳しています。
  * `/docs/Web/API/HIDDevice/sendReport`

### Related issues and pull requests

Relates to mdn/content#22419 (「Input レポートを受信」の件)
Relates to mdn/content#22426 (「以下のサンプル」の件)

2022-11-21 15:42 UTC, mfuji09 requested changes
新規翻訳や記事全体の更新などで、元の英語版記事が特定できる場合は、ヘッダ部（`title:` や `slug:` と同じ並び）に、以下のようにして元となった英語版記事のコミット ID を入れてください。
l10n:
  sourceCommit: XXXXXXXXXXXXXXXX

2022-11-21 15:42 UTC, mfuji09 commented on files/ja/web/api/hid/connect_event/index.md
> +イベント名を {{domxref("EventTarget.addEventListener", "addEventListener()")}} のようなメソッドで使うか、イベントハンドラプロパティを設定します。
「イベントハンドラ」→「イベントハンドラー」と記述してください。
同じ指摘は繰り返しませんので、他の記事も同様に修正をお願いします。

2022-11-21 15:42 UTC, mfuji09 commented on files/ja/web/api/hid/disconnect_event/index.md
> +{{domxref("HID")}}  インターフェイスの **`disconnect`** イベントは、ユーザーエージェントが HID デバイスを切断した時発火します。
「インターフェイス」の前に2文字の空白が入力されているようなので、1文字にしてください。

2022-11-21 15:42 UTC, mfuji09 commented on files/ja/web/api/hid/requestdevice/index.md
> +## 文法
他の記事と合わせて「構文」としてください。

2022-11-21 15:42 UTC, mfuji09 commented on files/ja/web/api/hiddevice/forget/index.md
> +### 戻り値
「返り値」「戻り値」など訳語が揺れているので、他の記事と合わせて「返値」とするようお勧めします。

2022-11-21 15:42 UTC, mfuji09 commented on files/ja/web/api/hid/index.md
> +## プロパティ
英語版では Instance property となっていますので、「インスタンスプロパティ」と記述するようお願いします。

2022-11-21 15:42 UTC, mfuji09 commented on files/ja/web/api/hid/index.md
> +## メソッド
同じく、英語版では Instance method となっているので、「インスタンスメソッド」と表記してください。他のインターフェイスも同様にお願いします。

2022-11-21 23:16 UTC, mikecat commented
@mfuji09 修正しました。

2022-11-23 03:27 UTC, mfuji09 approved these changes
OKです。

2022-11-23 03:28 UTC, merged