zh-cn(update): sync ReadableStreamDefaultReader
mdn/translated-content pull request #10030
Opened 2022-11-20 14:43 UTC by Jack-Zhang-1314

### Description

### Motivation

### Additional details

### Related issues and pull requests

2022-11-21 00:33 UTC, yin1999 requested changes

2022-11-21 00:33 UTC, yin1999 commented on files/zh-cn/web/api/readablestreamdefaultreader/index.md
> +然而，请注意，只有自动分配缓冲区的基础字节源支持从底层源进行零副本传输。换句话说，流必须同时指定[构造函数](/zh-CN/docs/Web/API/ReadableStream/ReadableStream)中的 [`type="bytes"`](/zh-CN/docs/Web/API/ReadableStream/ReadableStream#type) 和 [`autoAllocateCh
请改进这两段话的翻译

2022-11-21 05:28 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/readablestreamdefaultreader/index.md
> +然而，请注意，只有自动分配缓冲区的基础字节源支持从底层源进行零副本传输。换句话说，流必须同时指定[构造函数](/zh-CN/docs/Web/API/ReadableStream/ReadableStream)中的 [`type="bytes"`](/zh-CN/docs/Web/API/ReadableStream/ReadableStream#type) 和 [`autoAllocateCh
```suggestion
`ReadableStreamDefaultReader` 可以用于读取有任何类型的底层源 {{domxref("ReadableStream")}}（和 {{domxref("ReadableStreamBYOBReader")}} 不同的是，ReadableStreamBYOBReader 仅可以和拥有*底层字节源*的可读流一起使用）。

然而，请注意，对于自动分配缓冲区的底层字节源，仅支持从底层源进行零拷贝转移。换句话说，流必须同时指定[构造函数](/zh-CN/docs/Web/API/ReadableStream/ReadableStream)中的 [`type="bytes"`](/zh-CN/docs/Web/API/ReadableStream/ReadableStream#type) 和 [`autoAllocateChunkSize`](/zh-CN/docs/Web/API/ReadableStream/ReadableStream#autoallocatechunksize)。对于任何其它底层源，流将始终使用来自内置队列的数据满足读取请求。
```

我不确定这里的 any type 是**任何类型**还是**任意输入**

2022-11-22 01:29 UTC, yin1999 commented on files/zh-cn/web/api/readablestreamdefaultreader/index.md
> +然而，请注意，只有自动分配缓冲区的基础字节源支持从底层源进行零副本传输。换句话说，流必须同时指定[构造函数](/zh-CN/docs/Web/API/ReadableStream/ReadableStream)中的 [`type="bytes"`](/zh-CN/docs/Web/API/ReadableStream/ReadableStream#type) 和 [`autoAllocateCh
两段话的翻译还需修改，上面的修改还是有问题的

2022-11-22 04:19 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/readablestreamdefaultreader/index.md
> +然而，请注意，只有自动分配缓冲区的基础字节源支持从底层源进行零副本传输。换句话说，流必须同时指定[构造函数](/zh-CN/docs/Web/API/ReadableStream/ReadableStream)中的 [`type="bytes"`](/zh-CN/docs/Web/API/ReadableStream/ReadableStream#type) 和 [`autoAllocateCh
需要帮助 @yin1999

2022-11-22 14:45 UTC, yin1999 approved these changes

2022-11-22 14:49 UTC, merged