zh-cn(update): sync response.body
mdn/translated-content pull request #10031
Opened 2022-11-20 15:11 UTC by Jack-Zhang-1314

### Description

### Motivation

### Additional details

### Related issues and pull requests

2022-11-21 00:36 UTC, yin1999 requested changes

2022-11-21 00:36 UTC, yin1999 commented on files/zh-cn/web/api/response/body/index.md
> +一个 {{domxref("ReadableStream")}}，或者对于使用空的 [`body`](/zh-CN/docs/Web/API/Response/Response#body) 属性构建的任意的 `Response` 对象，或者没有任何[主体](/zh-CN/docs/Web/HTTP/Messages#body_2)的实际 [HTTP 响应](/zh-CN/docs/Web/HTT
请修改，翻译得不对

2022-11-21 00:36 UTC, yin1999 commented on files/zh-cn/web/api/response/body/index.md
> +> **备注：** 当前的浏览器实际上不会将没有正文的响应（例如，对 [`HEAD`](/zh-CN/docs/Web/HTTP/Methods/HEAD) 请求的响应或 [`204 No Content`](/zh-CN/docs/Web/HTTP/Status/204)）将 `body` 属性设置为空的规范要求。
请修改

2022-11-21 04:48 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/response/body/index.md
> +一个 {{domxref("ReadableStream")}}，或者对于使用空的 [`body`](/zh-CN/docs/Web/API/Response/Response#body) 属性构建的任意的 `Response` 对象，或者没有任何[主体](/zh-CN/docs/Web/HTTP/Messages#body_2)的实际 [HTTP 响应](/zh-CN/docs/Web/HTT
```suggestion
一个 {{domxref("ReadableStream")}}，或者使用空的 [`body`](/zh-CN/docs/Web/API/Response/Response#body) 属性构建的任意的 `Response` 对象，或者没有任何[主体](/zh-CN/docs/Web/HTTP/Messages#body_2)的实际 [HTTP 响应](/zh-CN/docs/Web/HTTP/Messages#http_响应)，则为 [`null`](/zh-CN/docs/Web/JavaScript/Reference/Operators/null)。
```

2022-11-21 04:52 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/response/body/index.md
> +> **备注：** 当前的浏览器实际上不会将没有正文的响应（例如，对 [`HEAD`](/zh-CN/docs/Web/HTTP/Methods/HEAD) 请求的响应或 [`204 No Content`](/zh-CN/docs/Web/HTTP/Status/204)）将 `body` 属性设置为空的规范要求。
```suggestion
> **备注：** 对于没有 body 的响应，当前的浏览器实际上不符合将 `body` 属性设置为 `null` 的规范要求（例如，对 [`HEAD`](/zh-CN/docs/Web/HTTP/Methods/HEAD) 请求的响应或 [`204 No Content`](/zh-CN/docs/Web/HTTP/Status/204)）。
```

2022-11-21 04:55 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/response/body/index.md
> +> **备注：** 当前的浏览器实际上不会将没有正文的响应（例如，对 [`HEAD`](/zh-CN/docs/Web/HTTP/Methods/HEAD) 请求的响应或 [`204 No Content`](/zh-CN/docs/Web/HTTP/Status/204)）将 `body` 属性设置为空的规范要求。
@yin1999 已修改

2022-11-21 05:16 UTC, yin1999 commented on files/zh-cn/web/api/response/body/index.md
> +一个 {{domxref("ReadableStream")}}，或者对于使用空的 [`body`](/zh-CN/docs/Web/API/Response/Response#body) 属性构建的任意的 `Response` 对象，或者没有任何[主体](/zh-CN/docs/Web/HTTP/Messages#body_2)的实际 [HTTP 响应](/zh-CN/docs/Web/HTT
![image](https://user-images.githubusercontent.com/15844309/202971083-9c8d7c0b-d5f1-4f7f-9324-4098cdd3b849.png)

2022-11-21 05:33 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/response/body/index.md
> +一个 {{domxref("ReadableStream")}}，或者对于使用空的 [`body`](/zh-CN/docs/Web/API/Response/Response#body) 属性构建的任意的 `Response` 对象，或者没有任何[主体](/zh-CN/docs/Web/HTTP/Messages#body_2)的实际 [HTTP 响应](/zh-CN/docs/Web/HTT
已改

2022-11-22 01:24 UTC, yin1999 commented on files/zh-cn/web/api/response/body/index.md
> +一个 {{domxref("ReadableStream")}}，或者对于使用空的 [`body`](/zh-CN/docs/Web/API/Response/Response#body) 属性构建的任意的 `Response` 对象，或者没有任何[主体](/zh-CN/docs/Web/HTTP/Messages#body_2)的实际 [HTTP 响应](/zh-CN/docs/Web/HTT
```suggestion
一个 {{domxref("ReadableStream")}}，或者对于使用空的 [`body`](/zh-CN/docs/Web/API/Response/Response#body) 属性构建的任意的 `Response` 对象，或没有任何[主体](/zh-CN/docs/Web/HTTP/Messages#body_2)的实际 [HTTP 响应](/zh-CN/docs/Web/HTTP/Messages#http_响应)，则为 [`null`](/zh-CN/docs/Web/JavaScript/Reference/Operators/null)。
```

2022-11-22 01:26 UTC, yin1999 approved these changes

2022-11-22 01:30 UTC, merged