Javascript Date 객체의 setUTCxxx 추가 수정 - 2
mdn/translated-content pull request #10048
Opened 2022-11-21 14:24 UTC by wisedog

### Description

아래 번역을 수정하였습니다.
setUTCDate()
setUTCFullYear()
setUTCHours()
setUTCMilliseconds()

2022-11-26 14:45 UTC, hochan222 approved these changes
@wisedog 님 안녕하세요.

하기 몇가지 사항에 대해서 리뷰 드렸습니다.

고생 많으셨습니다 :)

2022-11-26 14:45 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/date/setutcdate/index.md
> +**`setUTCDate()`** 메서드는 표준시에 따라 지정된 날짜의 날짜를 설정합니다.
원문 형식과 가깝게 번역 수정했습니다.

> The **`setUTCDate()`** method changes the day of the month of a given {{jsxref("Date")}} instance, based on UTC time.

```suggestion
**`setUTCDate()`** 메서드는 UTC 시간을 기준으로 지정된 {{jsxref("Date")}} 인스턴스의 날짜를 변경합니다.
```

2022-11-26 14:45 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/date/setutcfullyear/index.md
> +`monthValue` 및 `dayValue` 매개 변수를 지정하지 않으면 {{jsxref("Date.prototype.getUTCMonth", "getUTCMonth()")}} 및 {{jsxref("Date.prototype.getUTCDate","getUTCDate()")}} 메소드가 사용됩니다.
원문에 맞게 수정했습니다.

> If you do not specify the `monthValue` and
`dayValue` parameters, the values returned from the
{{jsxref("Date.prototype.getUTCMonth()", "getUTCMonth()")}} and
{{jsxref("Date.prototype.getUTCDate()", "getUTCDate()")}} methods are used.

```suggestion
`monthValue` 및 `dayValue` 매개 변수를 지정하지 않으면 {{jsxref("Date.prototype.getUTCMonth()", "getUTCMonth()")}} 및 {{jsxref("Date.prototype.getUTCDate()", "getUTCDate()")}} 메소드가 사용됩니다.
```

2022-11-26 14:45 UTC, hochan222 requested changes
.

2022-11-26 23:22 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/date/setutcfullyear/index.md
> +`monthValue` 및 `dayValue` 매개 변수를 지정하지 않으면 {{jsxref("Date.prototype.getUTCMonth", "getUTCMonth()")}} 및 {{jsxref("Date.prototype.getUTCDate","getUTCDate()")}} 메소드가 사용됩니다.
감사합니다! 수정하였습니다.

2022-11-26 23:22 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/date/setutcdate/index.md
> +**`setUTCDate()`** 메서드는 표준시에 따라 지정된 날짜의 날짜를 설정합니다.
수정완료!

2022-11-26 23:32 UTC, wisedog commented
언제부터 이렇게 린트가 빡빡하게 돌았는지 모르겠네요;;  혹시 로컬에서 린트 돌릴 수 있는 방법이 있을까요?

2022-11-27 04:04 UTC, hochan222 approved these changes
비교적 최근에 린트가 생겨서 음.. 조금 오류가 있나보네요. translated-content repo에서 `yarn markdownlint-cli2 files/ko/**/*.md` 로 찾아내고, `yarn markdownlint-cli2-fix files/ko/**/*.md`로 수정할 수 있습니다!

2022-11-27 04:04 UTC, merged