Add missing docs for console methods
mdn/translated-content pull request #10044
Opened 2022-11-21 12:14 UTC by taggon

### Description

Translates a few console methods docs in Korean.
한국어 번역이 없는 Console 메서드 문서를 추가했습니다.

### Motivation

Because there are no Korean docs for those APIs.
해당 API에 관한 한국어 문서가 없었으므로.

### Additional details

### Related issues and pull requests

2022-11-21 14:19 UTC, wisedog reviewed
와우 첫 PR 환영합니다. 트위터에서 글 쓴 보람이 있네요! 앞으로도 많은 PR 부탁드립니다! 

저는 리뷰 및 코멘트만 해드리고 나머지는 여기 계신 리뷰어분들이 해드릴겁니다.

2022-11-21 14:19 UTC, wisedog commented on files/ko/web/api/console/timelog/index.md
> +상세한 내용과 예제는 [타이머](/en-US/docs/Web/API/console#timers) 문서를 참고하세요.
요건 일단 `/ko/docs/Web/API/console#timers` 로 하심이 좋겠습니다.

2022-11-21 14:19 UTC, wisedog commented on files/ko/web/api/console/timelog/index.md
> +### 예상 결과
원문이 `Expectation`이 아니라 `Exceptions`이 아닐런지요?

2022-11-21 14:19 UTC, wisedog commented on files/ko/web/api/console/table/index.md
> +두 번째 인수인 `columns`는 선택적으로 전달할 수 있습니다.
en-US가 2줄이라고 2줄로 하실 필요는 없습니다  :)

2022-11-21 14:19 UTC, wisedog commented on files/ko/web/api/console/dirxml/index.md
> +**`console.dirxml()`** 메서드는 주어진 XML/HTML 엘리먼트의 자손 엘리먼트를 인터랙티브한 트리로 표시합니다.
용어집에는 `Element`를 요소로 번역하고 있습니다. 

참고: https://github.com/mdn/translated-content/blob/main/docs/ko/translation-guide.md#%EC%9A%A9%EC%96%B4-%EC%A7%80%EC%B9%A8

2022-11-21 14:19 UTC, wisedog commented on files/ko/web/api/console/dir/index.md
> +**`console.dir()`** 메서드는 주어진 자바스크립트 객체 속성을 인터랙티브한 목록으로 표시합니다.
자바스크립트는 고유명사로 `Javascript`라고 표기합니다.

2022-11-21 14:32 UTC, taggon commented on files/ko/web/api/console/timelog/index.md
> +### 예상 결과
허... 눈이 잘못됐나 봅니다. 바로 수정해두겠습니다.

2022-11-21 14:32 UTC, taggon commented on files/ko/web/api/console/table/index.md
> +두 번째 인수인 `columns`는 선택적으로 전달할 수 있습니다.
아, 예전에 Node쪽 번역해보니까 이렇게 문장 단위로 끊어두면 읽기도 좋고 피드백 받기가 더 좋더라고요.

2022-11-21 14:32 UTC, taggon commented on files/ko/web/api/console/dir/index.md
> +**`console.dir()`** 메서드는 주어진 자바스크립트 객체 속성을 인터랙티브한 목록으로 표시합니다.
`JavaScript`란 뜻이죠?

2022-11-21 14:40 UTC, taggon commented
@wisedog 말씀하신 내용 중 수정이 필요한 부분은 전부 반영했습니다. 리뷰 감사합니다 :)

2022-12-03 02:15 UTC, pje1740 requested changes
마크다운의 메타데이터 확인 부탁드립니다.
그리고 이미지의 경우 [yari](https://github.com/mdn/yari)를 통해서 MDN에서 en-US의 이미지를 참조할 수 있도록 변경되기 때문에 별도로 파일을 추가하지 않으셔도 괜찮습니다. 
이미지 경로 관련해서는 아직 가이드에 명시되지 않아 혼선을 드린 점 양해 부탁 드리며, 로컬에서 확인해보고 싶으시다면 [yari](https://github.com/mdn/yari)의 quickstart 참고하시어 실행해보실 수 있습니다.
질문이 있다면 언제든 말씀 주세요! 고생하셨습니다!

2023-01-07 04:02 UTC, hochan222 approved these changes
@taggon 님, @pje1740 님 안녕하세요.

PR 병합이 지연되고 있어서, 리뷰 내용 제가 반영 후 병합하겠습니다.

고생 많으셨습니다! 모두 새해복 많이 받으세요 :)

2023-01-07 04:02 UTC, hochan222 commented on files/ko/web/api/console/dir/index.md
> +browser-compat: api.console.dir
```suggestion
```

2023-01-07 04:02 UTC, hochan222 commented on files/ko/web/api/console/dirxml/index.md
> +browser-compat: api.console.dirxml
```suggestion
```

2023-01-07 04:02 UTC, hochan222 commented on files/ko/web/api/console/table/index.md
> +browser-compat: api.console.table
```suggestion
```

2023-01-07 04:02 UTC, hochan222 commented on files/ko/web/api/console/timelog/index.md
> +browser-compat: api.console.timeLog
```suggestion
```

2023-01-07 04:05 UTC, merged