Add translation: Web Serial API
mdn/translated-content pull request #10054
Opened 2022-11-21 16:01 UTC by mikecat

### Description

Web Serial API および関連するページを新規翻訳。

### Motivation

### Additional details

シリアル通信の制御信号について、以下のページを参考にしました。

* [RS232C信号線の意味｜DTR・RTS・CTS・DSR・DCDの意味を解説](http://www.sacom.co.jp/lecture/rs232c.html)
* [玄箱PROと電子工作で遊ぼう - 46071_p113-116.pdf](https://www.cqpub.co.jp/hanbai/books/46/46071/46071_p113-116.pdf)

以下のプルリクエストで提案中の変更を反映済みです。

### Related issues and pull requests

Relates to mdn/content#22449
Relates to mdn/content#22450
Relates to mdn/content#22454
Relates to mdn/content#22455

2022-11-23 16:15 UTC, mfuji09 requested changes
1件だけ確認してください。

2022-11-23 16:15 UTC, mfuji09 commented on files/ja/web/api/serial/index.md
> +{{domxref("SerialPort.connect_event", "connect")}} および {{domxref("SerialPort.disconnect_event", "disconnect")}} イベントにロードイベントリスナーを追加することで、デバイスが接続された時や切断された時にサイトが反応できるようにします。{{domxref("Serial.getPorts(
先頭の On load event でいったん文が切れると解釈したほうが正しいと思います。
下の例で load イベントが登場しないのが難しいところですが、イベントリスナーの追加は主に load イベントで行うと思いますので。
```suggestion
`load` イベントにおいて {{domxref("SerialPort.connect_event", "connect")}} および {{domxref("SerialPort.disconnect_event", "disconnect")}} イベントのリスナーを追加することで、デバイスが接続された時や切断された時にサイトが反応できるようにします。{{domxref("Serial.getPorts()","getPorts()")}} メソッドを呼ぶことで、接続されたポートが既にサイトからのアクセスが許可されたものかどうかを調べることができます。
```

2022-11-24 10:08 UTC, mikecat commented on files/ja/web/api/serial/index.md
> +{{domxref("SerialPort.connect_event", "connect")}} および {{domxref("SerialPort.disconnect_event", "disconnect")}} イベントにロードイベントリスナーを追加することで、デバイスが接続された時や切断された時にサイトが反応できるようにします。{{domxref("Serial.getPorts(
修正しました。

2022-11-24 13:49 UTC, mfuji09 approved these changes
OKです。

2022-11-24 13:50 UTC, merged