docs: translate content for unary_plus and unary_negation
mdn/translated-content pull request #10065
Opened 2022-11-22 07:33 UTC by YangFong

### Description

Translate content.

2022-11-22 14:47 UTC, yin1999 requested changes

2022-11-22 14:47 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/unary_negation/index.md
> +title: 一元否（-）
这个翻译是不是感觉很容易让人误解为“否定” `!`

2022-11-23 02:08 UTC, YangFong commented on files/zh-cn/web/javascript/reference/operators/unary_negation/index.md
> +title: 一元否（-）
这一点确实是，还有另一个方案：「一元减」。

我也考虑过其他的，其作用是获取数值的相反数。「一元反」也算贴合。

2022-11-26 06:34 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/unary_negation/index.md
> +title: 一元否（-）
Sorry for the late, let's use "一元减" for there is more usages through Google

```suggestion
title: 一元减（-）
```

2022-11-26 06:41 UTC, yin1999 approved these changes

2022-11-26 06:45 UTC, merged