translate DOM example document
mdn/translated-content pull request #10063
Opened 2022-11-22 04:25 UTC by notJoon

### Description
* Web API/DOM/Examples 문서에서 누락된 부분들의 한국어 번역을 끝냈습니다. 

### Additional details
- example 1 설명 부분에 `:`이 들어가 있던 것은 한국어 가이드라인에 맞게 수정했습니다.
- example 7 코드에 `lableList`가 `labelList`의 오타인거 같아 수정했습니다.
- 코드 부분의 타이틀이나 주석도 번역하긴 했는데(e.g., `<title>너비/높이 예시</title>`) 이게 번역 지침에 맞는지는 모르겠습니다. 만약 아니라면 이 부분은 되돌려놓겠습니다.  
- 또한 코드 블럭에 몇몊 설명들이 들어가 있던데, 영어 문서를 참고하여 따로 뺐습니다.

2022-11-26 16:21 UTC, hochan222 requested changes
@notJoon 님 안녕하세요.

몇 가지 리뷰사항 아래 드렸습니다. 고생 많으셨습니다!

기여해주셔서 감사합니다. 좋은 하루 보내세요 :)

2022-11-26 16:21 UTC, hochan222 commented on files/ko/web/api/document_object_model/examples/index.md
>  ---
누락된 sidebar 원문과 동일하게 추가했습니다.

```
---
title: Examples of web and XML development using the DOM
slug: Web/API/Document_Object_Model/Examples
page-type: guide
tags:
  - DOM
  - DOM Reference
---

{{DefaultAPISidebar("DOM")}}

This chapter provides some longer examples of web and XML development using the DOM. Wherever possible, the examples use common APIs, tricks, and patterns in JavaScript for manipulating the document object.
```

```suggestion
---

{{DefaultAPISidebar("DOM")}}

```

2022-11-26 16:21 UTC, hochan222 commented on files/ko/web/api/document_object_model/examples/index.md
> +이 장에서는 DOM을 사용한 웹, XML 개발의 자세한 예제를 제공합니다. 예제는 문서의 객체를 조작하기 위해 가능한 JavaScript의 일반적인 API, 트릭, 패턴을 사용합니다.
```suggestion
이 장에서는 DOM을 사용한 웹, XML 개발의 자세한 예제를 제공합니다. 예제는 문서의 객체를 조작하기 위해 가능한 JavaScript의 공통 API, 트릭, 패턴을 사용합니다.
```

2022-11-26 16:21 UTC, hochan222 commented on files/ko/web/api/document_object_model/examples/index.md
> +## 참고 문서
`## Subnav` 부분이 사라져서, 해당 section 제거 부탁드립니다 🙇🙇

2022-11-27 12:53 UTC, notJoon commented
@hochan222 리뷰된 내용에 맞춰 수정했습니다. 감사합니다 👍👍

2022-11-27 23:42 UTC, hochan222 approved these changes

2022-11-29 00:46 UTC, hochan222 commented
기여해주셔서 감사합니다. 좋은 하루 보내세요 :)

---

For the record, this PR failed the markdown lint workflow, but just squash merged it.

![image](https://user-images.githubusercontent.com/22424891/204410733-e3823fca-1303-4603-9150-377fee076d20.png)

2022-11-29 00:46 UTC, merged