Add chinese translate
mdn/translated-content pull request #1007
Opened 2021-05-28 09:15 UTC by stigersmile

2021-05-28 12:07 UTC, t7yang requested changes
你的進度已經落後目前的版本，請重新 pull 確保完成你本機的進度再開始翻譯。

除了提及的問題外，也請參考新上線的[正體中文翻譯指南](https://github.com/mdn/translated-content/blob/main/docs/zh-tw/translation-guide.md)並重新檢視你的翻譯內容確保符合中文翻譯的指導原則，感謝。

審核小組在經過討論後做了一個重大的決定——取消中英文之間的空格修飾，原因跟細節可以參考[這裡](https://github.com/mdn/translated-content/blob/main/docs/zh-tw/translation-guide.md#%E4%B8%AD%E6%96%87%E5%8F%8A%E6%8B%89%E4%B8%81%E8%AA%9E%E7%B3%BB%E6%96%87%E5%AD%97%E9%96%93%E4%B8%8D%E5%8A%A0%E4%BF%AE%E9%A3%BE%E7%A9%BA%E7%99%BD)，再麻煩根據指導原則進行修改，造成困擾的部分請包涵。

2021-06-02 03:09 UTC, stigersmile commented
fixed the conflict

2021-06-05 03:17 UTC, tso1158687 commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_item_component/index.html
> +<p>雙括號 <code>{{}}</code>，在 <code>&lt;h2&gt;</code> 內顯示 <code>items</code> 的長度與數目。</p>
這一行修正試試看

2021-06-05 06:51 UTC, irvin commented
現在與 main 分支還是有 conflict 喔

2021-06-05 08:23 UTC, stigersmile commented
> 現在與 main 分支還是有 conflict 喔

請問在哪裡呢? 從我這邊看不出來

2021-06-05 09:50 UTC, irvin commented
> > 現在與 main 分支還是有 conflict 喔
> 
> 請問在哪裡呢? 從我這邊看不出來

請在你的 repo 下按 fetch upstream 試試

<img width="1317" alt="截圖 2021-06-05 下午5 49 53" src="https://user-images.githubusercontent.com/165936/120887622-8e191f00-c626-11eb-8169-c89e6f8fc90a.png">

2021-06-06 06:53 UTC, SphinxKnight commented
This pull request contains files unrelated to the PR itself. Including files for various locales (including frozen ones where contribution is not accepted). It should not be merged as is.

Let us know if you need help with Git to get this one on track :)

2021-06-06 06:53 UTC, SphinxKnight requested changes
Review comment: unrelated files should not be touched by this PR.

2021-06-06 13:46 UTC, stigersmile commented
> 
> 
> This pull request contains files unrelated to the PR itself. Including files for various locales (including frozen ones where contribution is not accepted). It should not be merged as is.
> 
> Let us know if you need help with Git to get this one on track :)

Than you for your feedback, I just push "Fetch upstream" Fetch and merge on my github. What should I do to fixed this problem?

2021-06-07 01:45 UTC, t7yang commented
I think we should stop here.

@stigersmile could you please submit a new PR and make sure your work is based on the latest main branch. This is easier than fixing the issue here if you unfamiliar with git.

Thx

2021-06-07 01:45 UTC, closed without merging