feat: translate-ko /accessibility/aria/attributes/aria-label
mdn/translated-content pull request #10119
Opened 2022-11-23 17:02 UTC by July249

### Description

The "aria-label" part of the "aria attributes" keyword of the Accessibility has been translated into Korean. 
(https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label)

Created new folder "attributes/aria-label" and new file "index.md".

### Motivation

This translation was made to ensure that native Korean developers (or learners) who have difficulty reading English will not have linguistic difficulties in using and understanding Web accessibility.

### Additional details

### Related issues and pull requests

2022-12-12 17:11 UTC, hochan222 commented
@July249 님 안녕하세요.

리뷰가 늦어지게 되어서 죄송합니다. 월요일에 리뷰어님과 연락 진행했으며, 리뷰 주신다는 답변을 받았습니다.

다시 한번 리뷰가 지연되게 되어 정말 죄송합니다.

좋은 하루 보내세요 :)

2022-12-12 17:54 UTC, July249 commented
감사합니다!👍

2022-12-13 08:37 UTC, cos18 commented on files/ko/web/accessibility/aria/attributes/aria-label/index.md
> +> **참조:** `aria-label`은 레이블로 참조되어질 수 있는 DOM 안에 표시가능한 적당한 텍스트가 없을 때, 상호작용을 하는 요소들 또는 다른 ARIA 선언들을 통해 상호작용하도록 만들어진 요소에 사용하기 위한 것입니다.
```suggestion
> **참고:** `aria-label`은 레이블로 참조되어질 수 있는 DOM 안에 표시가능한 적당한 텍스트가 없을 때, 상호작용을 하는 요소들 또는 다른 ARIA 선언들을 통해 상호작용하도록 만들어진 요소에 사용하기 위한 것입니다.
```

2022-12-13 08:42 UTC, cos18 requested changes
늦은 리뷰 죄송합니다 ㅠㅠ 리뷰드린 내용 수정 부탁드립니다!

2022-12-13 08:42 UTC, cos18 commented on files/ko/web/accessibility/aria/attributes/aria-label/index.md
> +---
```suggestion
---
title: "aria-label"
slug: Web/Accessibility/ARIA/Attributes/aria-label
---
```

[이 글](https://github.com/mdn/translated-content/blob/main/docs/ko/translation-guide.md#메타데이터) 참고 부탁드립니다!

2022-12-13 08:42 UTC, cos18 commented on files/ko/web/accessibility/aria/attributes/aria-label/index.md
> +> **참조:** `aria-label`은 레이블로 참조되어질 수 있는 DOM 안에 표시가능한 적당한 텍스트가 없을 때, 상호작용을 하는 요소들 또는 다른 ARIA 선언들을 통해 상호작용하도록 만들어진 요소에 사용하기 위한 것입니다.
```suggestion
> **참고:** `aria-label`은 레이블로 참조되어질 수 있는 DOM 안에 표시가능한 적당한 텍스트가 없을 때, 상호작용을 하는 요소들 또는 다른 ARIA 선언들을 통해 상호작용하도록 만들어진 요소에 사용하기 위한 것입니다.
```

2022-12-15 09:00 UTC, July249 commented on files/ko/web/accessibility/aria/attributes/aria-label/index.md
> +---
@cos18  리뷰 주신 내용을 참고하여 수정하였습니다.

2022-12-15 09:00 UTC, July249 commented on files/ko/web/accessibility/aria/attributes/aria-label/index.md
> +> **참조:** `aria-label`은 레이블로 참조되어질 수 있는 DOM 안에 표시가능한 적당한 텍스트가 없을 때, 상호작용을 하는 요소들 또는 다른 ARIA 선언들을 통해 상호작용하도록 만들어진 요소에 사용하기 위한 것입니다.
@cos18 리뷰 주신 내용을 참고하여 수정하였습니다.

2022-12-17 08:04 UTC, cos18 approved these changes
LGTM! 감사합니다 :)

2022-12-17 08:04 UTC, merged