Update index.md
mdn/translated-content pull request #10120
Opened 2022-11-23 17:11 UTC by AdaJass

小小的改动

### Description
It is a little change to the Chinese version. Just make the sentence more comprehensible without the term `私网设备`, and the English version is no the term which mean Private Network Devices. Chinese version makes me a little confuse.

### Motivation

may help others? 

### Additional details
The Chinese sentence is:
`一些路由器严格地限定了部分私网设备的对外连接。`
and the English version is:
`Some routers will have restrictions on who can connect to devices on the network. `

Let me translate the Chinese version to English would be:
`Some routers had hardly restricted parts of private network devices to connect outside. `    WTF! 

### Related issues and pull requests

2022-11-24 02:13 UTC, yin1999 requested changes

2022-11-24 02:13 UTC, yin1999 commented on files/zh-cn/web/api/webrtc_api/protocols/index.md
> +一些路由器严格地限定了谁能连接进入内网。这种情况下，即使 STUN 服务器识别了该私网设备的公网 IP 和端口的映射，依然无法和这个私网设备建立连接。这种情况下就需要转向 TURN 协议。
```suggestion
一些路由器严格地限定了谁能连接内网的设备。这种情况下，即使 STUN 服务器识别了该内网设备的公网 IP 和端口的映射，依然无法和这个内网设备建立连接。这种情况下就需要转向 TURN 协议。
```

2022-11-24 07:53 UTC, yin1999 approved these changes
Thank you @AdaJass :) Welcome aboard 🎉

2022-11-24 07:55 UTC, merged

2022-11-25 00:01 UTC, schalkneethling commented
Welcome to the community, @AdaJass 🎉 Thank you for your contribution. If you are interested in more ways to contribute to MDN Web Docs, please have a look at our [contributor task board](https://github.com/orgs/mdn/projects/25). If you have any questions or need help finding something to work on, feel free to ask for help in our [community discussions](https://github.com/orgs/mdn/discussions). We look forward to more of your contributions. 🙌