[ko] fix and update translations in webextensions
mdn/translated-content pull request #10155
Opened 2022-11-24 14:21 UTC by sieazz

/ko/mozilla/add-ons/webextensions/what_are_webextensions
/ko/mozilla/add-ons/webextensions/your_second_webextension
다음 두 문서의 기존 번역 내용을 수정하였습니다.

1. 원문 영어 문서에서 누락된 부분이나 새롭게 수정된 부분들에 대해서도 번역을 진행하였습니다.
2. 단어 extension을 '확장 기능'으로 통일하였습니다.
3. 경어체와 평어체가 혼동된 경우 경어체로 수정하였습니다.
4. 누락된 이미지를 추가하였습니다.
5. 그외 자잘한 오타를 수정하였습니다.

2022-11-26 15:50 UTC, hochan222 requested changes
@sieazz 님 안녕하세요.

몇 가지 사항에 대해서 리뷰 드렸습니다. 고생 많으셨습니다!

기여해주셔서 감사합니다. 좋은 하루 보내세요 :)

2022-11-26 15:50 UTC, hochan222 commented on files/ko/mozilla/add-ons/webextensions/what_are_webextensions/index.md
> +> **참고:** 만약 브라우저 확장 기능의 기본적인 개념은 이미 익숙하다면, 이 섹션을 스킵하고 [확장 기능 파일이 어떻게 구성되는지 읽어보세요](/en-US/docs/Mozilla/Add-ons/WebExtensions/Anatomy_of_a_WebExtension). 그 다음, [참고 문서](/en-US/docs/Mozilla/Add-ons/WebE
아래 번역이 가독성이 조금 더 좋아 보여서 리뷰 드렸습니다. 아래 번역은 어떠하신가요?

```suggestion
> **참고:** 만약 브라우저 확장 기능의 기본적인 개념은 이미 익숙하다면, 이 섹션을 스킵하고 [확장 기능 파일이 어떻게 구성되는지 읽어보세요](/en-US/docs/Mozilla/Add-ons/WebExtensions/Anatomy_of_a_WebExtension). 그 다음, [참고 문서](/en-US/docs/Mozilla/Add-ons/WebExtensions#reference)와 함께 확장 기능을 개발해 보세요. [Firefox Extension Workshop](https://extensionworkshop.com/?utm_source=developer.mozilla.org&utm_medium=documentation&utm_campaign=your-first-extension)을 방문하여 Firefox용 테스트, 게시 및 확장 기능에 대한 작업 흐름에 대해 자세히 알아보세요.
```

2022-11-26 15:50 UTC, hochan222 commented on files/ko/mozilla/add-ons/webextensions/what_are_webextensions/index.md
> +확장 기능은 브라우저에 기능을 추가합니다. 확장 기능은 표준 웹 기술(HTML, CSS, JavaScript)을 이용해 만들어집니다. 확장 기능은 JavaScript에서 사용되는 웹 API 뿐만이 아니라 전용 JavaScript API에도 접근할 수 있어 웹페이지의 코드가 할 수 있는 것보다 더 많은 일을 할 수 있습니다. 아래는 몇 가지 예시입니다.
>  It's created using familiar web-based technologies — HTML, CSS, and JavaScript.

> 확장 기능은 표준 웹 기술(HTML, CSS, JavaScript)을 이용해 만들어집니다.

👍👍 

```suggestion
확장 기능은 브라우저에 기능을 추가합니다. 확장 기능은 표준 웹 기술(HTML, CSS, JavaScript)을 이용해 만들어집니다. 확장 기능은 JavaScript에서 사용되는 웹 API 뿐만이 아니라 전용 JavaScript API에도 접근할 수 있어 웹페이지의 코드가 할 수 있는 것보다 더 많은 일을 할 수 있습니다. 다음은 수행할 수 있는 작업의 몇 가지 예시입니다.
```

> Here are just a few examples of the things you can do:

원문과 최대한 동일하게 번역하는 것을 지침으로 삼고 있습니다. 문장 개수도 이에 해당합니다.

2022-11-26 15:50 UTC, hochan222 commented on files/ko/mozilla/add-ons/webextensions/what_are_webextensions/index.md
> +![](amazon_add_on.png)
> ![Amazon add-on example providing price comparison features](amazon_add_on.png)

```suggestion
![가격 비교 기능을 제공하는 Amazon 애드온 예제](amazon_add_on.png)
```

2022-11-26 15:50 UTC, hochan222 commented on files/ko/mozilla/add-ons/webextensions/what_are_webextensions/index.md
> +![](myweb_new_tab_add_on.png)
```suggestion
![배트맨 테마를 보여주는 나의 웹 새 탭 애드온](myweb_new_tab_add_on.png)
```

2022-11-26 15:50 UTC, hochan222 commented on files/ko/mozilla/add-ons/webextensions/what_are_webextensions/index.md
> +Examples: [Amazon Assistant for Firefox](https://addons.mozilla.org/en-US/firefox/addon/amazon-browser-bar/), [OneNote Web Clipper](https://addons.mozilla.org/en-US/firefox/addon/onenote-clipper/), a
```suggestion
예제: [Amazon Assistant for Firefox](https://addons.mozilla.org/en-US/firefox/addon/amazon-browser-bar/), [OneNote Web Clipper](https://addons.mozilla.org/en-US/firefox/addon/onenote-clipper/), and [Grammarly for Firefox](https://addons.mozilla.org/en-US/firefox/addon/grammarly-1/).
```

2022-11-26 15:50 UTC, hochan222 commented on files/ko/mozilla/add-ons/webextensions/what_are_webextensions/index.md
> +**웹페이지에 컨텐츠를 추가 또는 제거**: 사용자를 위해 웹페이지에서 거슬리는 광고를 제거한다던가, 웹페이지에 국가나 도시명이 띄워질 때 마다 여행 가이드를 제공한다던가, 일관된 읽기 경험을 제공하기 위해 페이지 컨텐츠를 재구성하는 작업을 하고 싶을 수 있습니다. 웹페이지의 HTML과 CSS에 접근하고 업데이트함으로써 확장 기능은 사용자가 원하는 방식으
```suggestion
**웹페이지에 컨텐츠를 추가 또는 제거**: 사용자를 위해 웹페이지에서 방해가 되는 광고를 차단하도록 돕거나, 웹 페이지에서 국가 또는 도시가 언급될 때마다 여행 가이드에 대한 접근을 제공하거나, 일관된 읽기 경험을 제공하기 위해 페이지 컨텐츠를 재구성하는 작업을 하고 싶을 수 있습니다. 웹페이지의 HTML과 CSS에 접근하고 업데이트함으로써 확장 기능은 사용자가 원하는 방식으로 웹을 볼 수 있도록 돕습니다.
```
부드럽게 번역을 수정했습니다.

2022-11-26 15:50 UTC, hochan222 commented on files/ko/mozilla/add-ons/webextensions/what_are_webextensions/index.md
> +**도구와 브라우징 기능 제공**: 태스크보드에 새로운 기능을 추가하고, URL, 하이퍼링크, 페이지 텍스트로부터 QR코드 이미지를 생성합니다. [WebExtensions APIs](/en-US/docs/Mozilla/Add-ons/WebExtensions)가 제공하는 유연한 UI옵션과 강력한 기능을 통해 브라우저에 새로운 기능을 쉽게 추가할 수 있습니다
```suggestion
**도구 및 새로운 브라우징 기능 추가**: 작업 보드에 새로운 기능을 추가하거나, URL, 하이퍼링크, 화면의 글자로부터 QR코드 이미지를 생성합니다. [WebExtensions APIs](/en-US/docs/Mozilla/Add-ons/WebExtensions)가 제공하는 유연한 UI 옵션들과 강력한 기능을 통해 브라우저에 새로운 기능을 쉽게 추가할 수 있습니다. 그리고 당신의 웹사이트가 아니더라도, 거의 모든 웹사이트의 기능을 향상시킬 수 있습니다.
```

> **Add tools and new browsing features**

new 가 누락되었습니다.

2022-11-26 15:50 UTC, hochan222 commented on files/ko/mozilla/add-ons/webextensions/what_are_webextensions/index.md
> +**개발 도구 추가**: 웹 개발 도구를 비즈니스로써 제공한다던가 공유하고자 하는 유용한 기술이나 웹 개발 접근법을 만들었을 수 있습니다. 어느 쪽이든 간에, 개발자 툴바에 새 탭을 추가하여 내장 Firefox 개발자 도구를 개선할 수 있습니다.
```suggestion
**개발 도구 추가**: 웹 개발 도구를 비즈니스로 제공하거나 공유하고 싶은 웹 개발에 대한 유용한 기술 또는 접근 방식을 개발했을 수 있습니다. 어느 쪽이든 간에, 개발자 도구 모음에 새 탭을 추가하여 내장 Firefox 개발자 도구를 향상시킬 수 있습니다.
```

2022-11-26 15:50 UTC, hochan222 commented on files/ko/mozilla/add-ons/webextensions/what_are_webextensions/index.md
> +Firefox 용 확장 프로그램은 확장 기능 개발을 위한 크로스 브라우저 시스템인 [WebExtensions APIs](/en-US/docs/Mozilla/Add-ons/WebExtensions)를 사용하여 만들어집니다. 대부분의 경우 API는 Google 크롬 및 Opera에서 지원하는 [extension API](https://developer.chr
```suggestion
Firefox 용 확장 프로그램은 확장 기능 개발을 위한 크로스 브라우저 시스템인 [WebExtensions APIs](/en-US/docs/Mozilla/Add-ons/WebExtensions)를 사용하여 만들어집니다. 대부분의 경우 API는 Google 크롬 및 Opera에서 지원하는 [extension API](https://developer.chrome.com/extensions)와 호환됩니다. 대부분의 경우 이러한 브라우저 용으로 작성된 확장 프로그램은 Firefox 또는 Microsoft Edge에서 몇 가지 [변경 사항](/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension)만으로 실행됩니다. API는 [멀티프로세스 Firefox](/en-US/Firefox/Multiprocess_Firefox)와도 완벽하게 호환됩니다.
```

2022-11-27 03:13 UTC, sieazz commented on files/ko/mozilla/add-ons/webextensions/what_are_webextensions/index.md
> +**개발 도구 추가**: 웹 개발 도구를 비즈니스로써 제공한다던가 공유하고자 하는 유용한 기술이나 웹 개발 접근법을 만들었을 수 있습니다. 어느 쪽이든 간에, 개발자 툴바에 새 탭을 추가하여 내장 Firefox 개발자 도구를 개선할 수 있습니다.
툴바가 도구 모음으로 번역이 되는군요!

2022-11-27 03:21 UTC, sieazz commented
@hochan222 세세한 리뷰 감사드립니다 :)

2022-11-27 04:11 UTC, hochan222 requested changes
@sieazz 님 안녕하세요!

현재 마크다운 린트 에러가 발생하고 있습니다. `yarn`을 실행해서 최신 dependencies 를 설치 후 commit 시도해서 해결 부탁드립니다.

위 방법으로도 미해결 시 translated-content repo에서 `yarn markdownlint-cli2 files/ko/~~.md` 로 
 마크다운 에러를 찾아내고, `yarn markdownlint-cli2-fix files/ko/~~.md`로 수정 부탁드립니다..! 

더불어 미번역된 Examples나 이미지 alt도 번역하면 좋을것 같습니다.

2022-11-29 00:35 UTC, hochan222 approved these changes

2022-11-29 00:40 UTC, merged

2022-11-29 00:43 UTC, hochan222 commented
기여해주셔서 감사합니다. 좋은 하루 보내세요 :)