Sync Web/API/Window/confirm in ja with c575deb
mdn/translated-content pull request #10167
Opened 2022-11-25 09:50 UTC by MikuroXina

### Description

Synchronize `Web/API/Window/confirm` in Japanese with c575deb.

### Motivation

It had some weird sentences as Japanese, and was too old as compared to the latest English version.

### Additional details

Retranslated the article completely.

2022-11-29 01:24 UTC, mfuji09 requested changes
2件について修正をお願いします。
なお、日本語翻訳記事へのプルリクエストは日本人しか見ませんので、日本語でどうぞ。

2022-11-29 01:24 UTC, mfuji09 commented on files/ja/web/api/window/confirm/index.md
> +page-type: web-api-instance-method
翻訳記事では、ヘッダ部分の page-type: tags: browser-compat: は削除してください。

2022-11-29 01:24 UTC, mfuji09 commented on files/ja/web/api/window/confirm/index.md
> +ダイアログボックスはモーダルウィンドウです。つまり閲覧者は、これを閉じないと他のプログラムのインタフェースにアクセスできません。したがって、ダイアログボックス（もしくは、モーダルウィンドウ）を生成する関数を乱用するべきではありません。何にせよ、それ相応の [確認を目的としたダイアログボックスの使用を避けるべき](https://alistapart.com/article/neveruseawa
interface は「インターフェイス」と表記してください。以前の記事では統一されていませんでしたが、記事全体を更新する際には統一するようお願いします。

2022-11-29 01:45 UTC, MikuroXina commented on files/ja/web/api/window/confirm/index.md
> +page-type: web-api-instance-method
627a3b6 にて対応しました.

2022-11-29 01:46 UTC, MikuroXina commented on files/ja/web/api/window/confirm/index.md
> +ダイアログボックスはモーダルウィンドウです。つまり閲覧者は、これを閉じないと他のプログラムのインタフェースにアクセスできません。したがって、ダイアログボックス（もしくは、モーダルウィンドウ）を生成する関数を乱用するべきではありません。何にせよ、それ相応の [確認を目的としたダイアログボックスの使用を避けるべき](https://alistapart.com/article/neveruseawa
分かりました. 98d9075 で対応しました.

2022-11-30 13:10 UTC, mfuji09 approved these changes
OKです。

2022-11-30 13:16 UTC, merged