Add a few terms to the glossary
mdn/translated-content pull request #10172
Opened 2022-11-25 13:29 UTC by taggon

### Description

Operand, Web Standards, WebGL, WebM, WebP를 용어 사전에 추가했습니다.

### Motivation

### Additional details

### Related issues and pull requests

2022-12-03 02:38 UTC, pje1740 requested changes
메타데이터 부분만 확인 부탁드리겠습니다! 고생하셨습니다 😊

2022-12-03 02:38 UTC, pje1740 commented on files/ko/glossary/operand/index.md
> +  - CodingScripting
https://github.com/mdn/translated-content/blob/main/docs/ko/translation-guide.md#%EB%A9%94%ED%83%80%EB%8D%B0%EC%9D%B4%ED%84%B0
모든 번역 파일 tags 제거 부탁 드리겠습니다!

2023-01-07 03:59 UTC, hochan222 approved these changes
@taggon 님, @pje1740 님 안녕하세요.

PR 병합이 지연되고 있어서, 리뷰 내용 제가 반영 후 병합하겠습니다.

고생 많으셨습니다! 모두 새해복 많이 받으세요 :)

2023-01-07 03:59 UTC, hochan222 commented on files/ko/glossary/operand/index.md
> +  - CodingScripting
```suggestion
tags:
  - CodingScripting
```

2023-01-07 04:03 UTC, merged