JavaScript: Int16Array 추가
mdn/translated-content pull request #10187
Opened 2022-11-26 01:23 UTC by wisedog

int16Array와 생성자 int16Array() 를 추가하였습니다.

2022-11-26 08:09 UTC, yujo11 requested changes
안녕하세요 wisedog님!

전체적인 번역 내용에는 코멘트 드릴 내용이 없었는데요!

formating관련하여 몇가지 코멘트 남긴 내용만 확인해주심 좋을거 같습니다! 

번역 진행하느라 고생 하셨습니다! 👍 👍 👍

2022-11-26 08:09 UTC, yujo11 commented on files/ko/web/javascript/reference/global_objects/int16array/index.md
> +
여기 개행이 2개 들어가서 lint에서 걸리는데 개행 하나 제거 부탁 드리겠습니다!

2022-11-26 08:09 UTC, yujo11 commented on files/ko/web/javascript/reference/global_objects/int16array/index.md
> +- {{jsxref("DataView")}}
여기는 개행이 안 들어가서 lint에서 걸리네용

2022-11-26 08:09 UTC, yujo11 commented on files/ko/web/javascript/reference/global_objects/int16array/int16array/index.md
> +- {{jsxref("DataView")}}
여기도 개행이 없다고 걸리는군요!

2022-11-26 08:09 UTC, yujo11 commented on files/ko/web/javascript/reference/global_objects/int16array/index.md
> +```
여긴 lint에 잡히는 부분은 아니지만 개행이 들어가면 가독성이 더 좋아질거 같습니다!

```suggestion
```js
// From a length
const int16 = new Int16Array(2);
int16[0] = 42;
console.log(int16[0]); // 42
console.log(int16.length); // 2
console.log(int16.BYTES_PER_ELEMENT); // 2

// From an array
const x = new Int16Array([21, 31]);
console.log(x[1]); // 31

// From another TypedArray
const y = new Int16Array(x);
console.log(y[0]); // 21

// From an ArrayBuffer
const buffer = new ArrayBuffer(16);
const z = new Int16Array(buffer, 2, 4);
console.log(z.byteOffset); // 2

// From an iterable
const iterable = (function* () {
  yield* [1, 2, 3];
})();
const int16FromIterable = new Int16Array(iterable);
console.log(int16FromIterable);
// Int16Array [1, 2, 3]
```
```

2022-11-26 08:09 UTC, yujo11 commented on files/ko/web/javascript/reference/global_objects/int16array/int16array/index.md
> +// Int16Array [1, 2, 3]
여기두요!

```suggestion
// From a length
const int16 = new Int16Array(2);
int16[0] = 42;
console.log(int16[0]); // 42
console.log(int16.length); // 2
console.log(int16.BYTES_PER_ELEMENT); // 2

// From an array
const x = new Int16Array([21, 31]);
console.log(x[1]); // 31

// From another TypedArray
const y = new Int16Array(x);
console.log(y[0]); // 21

// From an ArrayBuffer
const buffer = new ArrayBuffer(16);
const z = new Int16Array(buffer, 2, 4);
console.log(z.byteOffset); // 2

// From an iterable
const iterable = (function* () {
  yield* [1, 2, 3];
})();
const int16FromIterable = new Int16Array(iterable);
console.log(int16FromIterable);
// Int16Array [1, 2, 3]
```

2022-11-26 08:18 UTC, wisedog commented
> 안녕하세요 wisedog님!
> 
> 전체적인 번역 내용에는 코멘트 드릴 내용이 없었는데요!
> 
> formating관련하여 몇가지 코멘트 남긴 내용만 확인해주심 좋을거 같습니다!
> 
> 번역 진행하느라 고생 하셨습니다! 👍 👍 👍

제가 이걸 못보고 수정을 했네요. 다시 올리도록 하겠습니다!

2022-11-27 08:29 UTC, yujo11 approved these changes
고생하셨습니다! 👍 👍 👍

2022-11-27 08:29 UTC, merged