zh-cn(update): sync iteration
mdn/translated-content pull request #10257
Opened 2022-11-27 16:24 UTC by Jack-Zhang-1314

### Description

### Motivation

### Additional details

### Related issues and pull requests

2022-11-27 16:27 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +当内置语法迭代迭代器，并且最后的结果 `done` 为 `false`（即迭代器能够生成更多值）但不需要更多值时，如果存在，将调用 `return` 方法。例如，如果在 `for...of` 循环中遇到 `break` 或 `return`，或者所有标记都已绑定在数组解构中，则可能会发生这种情况。
将标记绑定到数组结构中，感觉翻译的不太好

2022-11-28 04:56 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
>  **可迭代协议**允许 JavaScript 对象定义或定制它们的迭代行为，例如，在一个 {{jsxref("Statements/for...of", "for..of")}} 结构中，哪些值可以被遍历到。一些内置类型同时是[内置可迭代对象](#内置可迭代对象)，并且有默认的迭代行为，比如 {{jsxref("Array")}} 或者 {{jsxref("Map")}}，而其他内置类型则不是（
```suggestion
**可迭代协议**允许 JavaScript 对象定义或定制它们的迭代行为，例如，在一个 {{jsxref("Statements/for...of", "for..of")}} 结构中，哪些值可以被遍历到。一些内置类型同时是[内置可迭代对象](#内置可迭代对象)，并且有默认的迭代行为，比如 {{jsxref("Array")}} 或者 {{jsxref("Map")}}，而其他内置类型则不是（比如 {{jsxref("Object")}}）。
```

2022-11-28 05:04 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +> **备注：** 不可能判断（例如，没有实际调用 `next()` 并验证返回的结果）一个特定的对象是否实现了迭代器协议。
```suggestion
> **备注：** 不可能条件反射地判断（例如，没有实际调用 `next()` 并验证返回的结果）一个特定的对象是否实现了迭代器协议。
```

`reflectively` 这样翻译好一点？

2022-11-28 05:04 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +很容易使一个迭代器也可迭代：只需实现 `[@@iterator]()` 方法，返回它的 `this`。
```suggestion
很容易使一个迭代器也可迭代：只需实现 `[@@iterator]()` 方法，并返回它的 `this`。
```

2022-11-28 05:05 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +{{jsxref("String")}}、{{jsxref("Array")}}、{{jsxref("TypedArray")}}、{{jsxref("Map")}}、{{jsxref("Set")}} 以及 {{jsxref("Intl.Segments")}} 都是内置的可迭代对象，因为它们的每个 `prototype` 对象都实现了 `@@iterator` 方法。此外，[`argumen
```suggestion
{{jsxref("String")}}、{{jsxref("Array")}}、{{jsxref("TypedArray")}}、{{jsxref("Map")}}、{{jsxref("Set")}} 以及 {{jsxref("Intl.Segments")}} 都是内置的可迭代对象，因为它们的每个 `prototype` 对象都实现了 `@@iterator` 方法。此外，[`arguments`](/zh-CN/docs/Web/JavaScript/Reference/Functions/arguments) 对象和一些 DOM 集合类型，如 {{domxref("NodeList")}} 也是可迭代的。目前，没有内置异步可迭代对象.
```

2022-11-29 04:50 UTC, yin1999 requested changes

2022-11-29 04:50 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +要成为**可迭代**对象，该对象必须实现 **`@@iterator`** 方法，这意味着对象（或者它[原型链](/zh-CN/docs/Web/JavaScript/Guide/Inheritance_and_the_prototype_chain)上的某个对象）必须有一个键为 `@@iterator` 的属性，可通过常量 {{jsxref("Symbol.iterator")}} 访问该属性
```suggestion
要成为**可迭代**对象，该对象必须实现 **`@@iterator`** 方法，这意味着对象（或者它[原型链](/zh-CN/docs/Web/JavaScript/Inheritance_and_the_prototype_chain)上的某个对象）必须有一个键为 `@@iterator` 的属性，可通过常量 {{jsxref("Symbol.iterator")}} 访问该属性：
```

2022-11-29 04:50 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +  - : 无参数或者接受一个参数，并返回符合 `IteratorResult` 接口的对象的函数（见下文）。如果在使用迭代器内置的语言特征（例如 `for...of`）时，得到一个非对象返回值（例如 `false` 或 `undefined`），将会抛出 {{jsxref("TypeError")}}（`"iterator.next() returned a non-object value"
请修改，有翻译错误

2022-11-29 04:50 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +> **备注：** 不可能判断（例如，没有实际调用 `next()` 并验证返回的结果）一个特定的对象是否实现了迭代器协议。
reflect 是[反射](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Reflect)，指一种语言的特性，并不是“条件反射地判断”的意思。

2022-11-29 05:12 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +  - : 无参数或者接受一个参数，并返回符合 `IteratorResult` 接口的对象的函数（见下文）。如果在使用迭代器内置的语言特征（例如 `for...of`）时，得到一个非对象返回值（例如 `false` 或 `undefined`），将会抛出 {{jsxref("TypeError")}}（`"iterator.next() returned a non-object value"
```suggestion
  - : 无参数或者接受一个参数，并返回符合 `IteratorResult` 接口的对象的函数（见下文）。如果在使用迭代器内置的语言特征（例如 `for...of`）时，得到一个非对象返回值（例如 `false` 或 `undefined`），将会抛出 {{jsxref("TypeError")}}（`"iterator.next() returned a non-object value"`）。
```

2022-11-29 05:15 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +> **备注：** 不可能判断（例如，没有实际调用 `next()` 并验证返回的结果）一个特定的对象是否实现了迭代器协议。
>Note: It is not possible to know reflectively (i.e. without actually calling next() and validating the returned result) whether a particular object implements the iterator protocol.

原文是这样，我觉得并不指 reflect

2022-11-29 05:19 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +> **备注：** 不可能判断（例如，没有实际调用 `next()` 并验证返回的结果）一个特定的对象是否实现了迭代器协议。
不可能条件反射地知道xxxx，语义上就说不过去

2022-11-29 05:24 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +> **备注：** 不可能判断（例如，没有实际调用 `next()` 并验证返回的结果）一个特定的对象是否实现了迭代器协议。
```plain
在计算机学中，反射式编程（英语：reflective programming）或反射（英语：reflection），
是指计算机程序在运行时（runtime）可以访问、检测和修改它本身状态或行为的一种能力。
用比喻来说，反射就是程序在运行的时候能够“观察”并且修改自己的行为。

 ——https://zh.wikipedia.org/zh-cn/%E5%8F%8D%E5%B0%84%E5%BC%8F%E7%BC%96%E7%A8%8B
```

2022-11-29 05:25 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +> **备注：** 不可能判断（例如，没有实际调用 `next()` 并验证返回的结果）一个特定的对象是否实现了迭代器协议。
在不调用方法的情况下，需要推断类型、方法等，就是“反射编程”

2022-11-29 05:27 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +> **备注：** 不可能判断（例如，没有实际调用 `next()` 并验证返回的结果）一个特定的对象是否实现了迭代器协议。
这个很清晰

2022-11-29 05:29 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +  - : 无参数或者接受一个参数，并返回符合 `IteratorResult` 接口的对象的函数（见下文）。如果在使用迭代器内置的语言特征（例如 `for...of`）时，得到一个非对象返回值（例如 `false` 或 `undefined`），将会抛出 {{jsxref("TypeError")}}（`"iterator.next() returned a non-object value"
这里的翻译还需修改，第二句话的翻译是错误的，后文也请仔细检查一下

2022-11-29 05:45 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +> **备注：** 不可能判断（例如，没有实际调用 `next()` 并验证返回的结果）一个特定的对象是否实现了迭代器协议。
包括其它的也已修改

2022-11-29 05:50 UTC, yin1999 reviewed
其余的内容，等我有时间再 review

2022-11-29 05:50 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +> **备注：** 不可能反射地知道（例如，没有实际调用 `next()` 并验证返回的结果）一个特定的对象是否实现了迭代器协议。
```suggestion
> **备注：** 无法通过反射的方法确定（例如，没有实际调用 `next()` 并验证返回的结果）一个特定的对象是否实现了迭代器协议。
```

2022-11-29 05:56 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +> **备注：** 不可能反射地知道（例如，没有实际调用 `next()` 并验证返回的结果）一个特定的对象是否实现了迭代器协议。
```js
const aGeneratorObject = (function* () {
   yield 1;
   yield 2;
   yield 3;
 })();

Reflect.has(aGeneratorObject, Symbol.iterator) // true
```

我试了一下，是可以的，我不太明白你说的是怎么样的

2022-11-29 06:24 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +> **备注：** 不可能反射地知道（例如，没有实际调用 `next()` 并验证返回的结果）一个特定的对象是否实现了迭代器协议。
这一块内容是“实现迭代器协议”，而非直接使用生成器创建迭代对象：

```js
function makeIterator(array) {
  let nextIndex = 0;
  return {
	next: function() { // impl next method
	  return nextIndex < array.length ?
		{value: array[nextIndex++], done: false} :
		{value: undefined, done: true};
	}
  };
}

const it = makeIterator(['a', 'b']);
console.log(Reflect.has(it, Symbol.iterator)); // false
```

2022-11-29 11:25 UTC, yin1999 requested changes

2022-11-29 11:25 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +这种对象被称为*可迭代迭代器*。这样做可以让迭代器被被期望可迭代的各种语法使用——因此，在不实现迭代的情况下，实现迭代器协议很少有用。（事实上，几乎所有的语法和 API 都期待*可迭代，而不是迭代器*。）[生成器对象](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Generator)是一个例子：
iterables 翻译为“可迭代对象”是不是更好些。

2022-11-29 11:25 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
>  ### 格式不佳的可迭代对象
[当内置语法迭代迭代器，并且最后的结果](https://github.com/mdn/translated-content/pull/10254/files#diff-8ea15c0d6bb570481618e67a31f90d10eb2c39a1876191f1b8047c9ce0a10f9fL42)

2022-11-29 11:25 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +当内置语法迭代迭代器，并且最后的结果 `done` 为 `false`（即迭代器能够生成更多值）但不需要更多值时，如果存在，将调用 `return` 方法。例如，如果在 `for...of` 循环中遇到 `break` 或 `return`，或者所有标记都已绑定在数组解构中，则可能会发生这种情况。
```suggestion
当内置语法迭代迭代器，并且最后的结果中 `done` 为 `false`（即迭代器能够生成更多值）但不需要更多值时，如果存在，将调用 `return` 方法。例如，如果在 `for...of` 循环中遇到 `break` 或 `return`，或者数组解构中的标识符只是有限个的，则可能会发生这种情况。
```

2022-11-29 11:25 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +[异步生成器函数](/zh-CN/docs/Web/JavaScript/Reference/Statements/async_function*)（但不是[同步生成器函数](/zh-CN/docs/Web/JavaScript/Reference/Statements/function*)）中的 [`for await...of`](/zh-CN/docs/Web/JavaScript/Ref
```suggestion
[异步生成器函数](/zh-CN/docs/Web/JavaScript/Reference/Statements/async_function*)（但不是[同步生成器函数](/zh-CN/docs/Web/JavaScript/Reference/Statements/function*)）中的 [`for await...of`](/zh-CN/docs/Web/JavaScript/Reference/Statements/for-await...of) 循环和 [`yield*`](/zh-CN/docs/Web/JavaScript/Reference/Operators/yield*) 是与异步迭代交互的唯一方式。在不是同步迭代的异步迭代对象（即它有 `[@@asyncIterator]()` 但没有 `[@@iterator]()`）上使用 `for...of`、数组展开等将抛出 `TypeError：x is not iterable`。
```

2022-11-29 11:25 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +迭代器本质上是有状态的。如果您不将其定义为[生成器函数](/zh-CN/docs/Web/JavaScript/Reference/Statements/function*) （如上例所示），你可能需要将状态封装在闭包中。
```suggestion
迭代器本质上是有状态的。如果你不将其定义为[生成器函数](/zh-CN/docs/Web/JavaScript/Reference/Statements/function*)（如上例所示），你可能需要将状态封装在闭包中。
```

2022-11-29 11:25 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +注意重新定义 `@@iterator` 如何影响使用迭代协议的内置结构的行为：
请修改

2022-11-29 12:23 UTC, Jack-Zhang-1314 commented
✅

2022-11-30 05:41 UTC, Jack-Zhang-1314 commented
@yin1999 虽然这个地方不太合适，但是我还是想问你一下之前翻译的一些问题

```js
const obj2 = {
  [Symbol.toPrimitive](hint) {
    if (hint === "number") {
      return 10;
    }
    if (hint === "string") {
      return "hello";
    }
    return true;
  },
};
console.log(+obj2); // 10  — hint 参数值是 "number"
console.log(`${obj2}`); // "hello"   — hint 参数值是 "string"
console.log(obj2 + ""); // "true"    — hint 参数值是 "default"
```

* [在这里](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Data_structures#强制其它类型转换)它告知我们强制原始值的转换过程，会首先触发 default，但是我看了一下 [`+` 运算符](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Addition#描述),如果有字符串它会强制准换为字符串的过程吗？为什么它的 hint 是 default

2022-11-30 08:49 UTC, yin1999 commented
> [在这里](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Data_structures#%E5%BC%BA%E5%88%B6%E5%85%B6%E5%AE%83%E7%B1%BB%E5%9E%8B%E8%BD%AC%E6%8D%A2)它告知我们强制原始值的转换过程，会首先触发 default，但是我看了一下 [+ 运算符](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Addition#%E6%8F%8F%E8%BF%B0),如果有字符串它会强制准换为字符串的过程吗？为什么它的 hint 是 default

对象需要强制转换为基本类型，但因为加号在后面，所以对象只能强制转换为默认的原始类型（由 hint 传入）。

第二，我指出的问题还未完全修改，请继续修改。修改完成后，我有时间会review的。请认真修改。

2022-11-30 11:21 UTC, yin1999 requested changes

2022-11-30 11:21 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +可选地，迭代器也实现了 **`return(value)`** 和 **`throw(exception)`** 方法，这些方法在调用时告诉迭代器，调用者已经完成迭代，并且可以执行任何必要的清理（例如关闭数据库）。
```suggestion
可选地，迭代器也实现了 **`return(value)`** 和 **`throw(exception)`** 方法，这些方法在调用时告诉迭代器，调用者已经完成迭代，并且可以执行任何必要的清理（例如关闭数据库连接）。
```

2022-11-30 11:21 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +这种对象被称为*可迭代迭代器*。这样做可以让迭代器被被期望可迭代的各种语法使用——因此，在不实现迭代的情况下，实现迭代器协议很少有用。（事实上，几乎所有的语法和 API 都期待*可迭代的对象，而不是迭代器*。）[生成器对象](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Generator)是一个例子：
```suggestion
这种对象被称为*可迭代迭代器*。这样做可以让期望可迭代对象的各类语法使用此类迭代器——因此，在不实现可迭代协议的情况下，仅实现迭代器协议的作用很小。（事实上，几乎所有的语法和 API 都期待*可迭代对象，而不是迭代器*。）[生成器对象](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Generator)是一个例子：
```

2022-11-30 11:21 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +console.log(typeof aGeneratorObject.next);
```suggestion
})();

console.log(typeof aGeneratorObject.next);
```

2022-11-30 11:21 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +// "function"——它有 next 方法（返回正确的值），所以它是迭代器
```suggestion
// "function"——它有 next 方法（返回正确的值），所以它是迭代器 

```

2022-11-30 11:21 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +// "function"——它有 @@iterator 方法（返回正确的迭代器），所以它是可迭代的
```suggestion
// "function"——它有 @@iterator 方法（返回正确的迭代器），所以它是可迭代的

```

2022-11-30 11:21 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +该语言指定了产生或使用可迭代和迭代器的 API。
```suggestion
JavaScript 语言指定了产生或使用可迭代对象和迭代器的 API。
```

2022-11-30 11:21 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +{{jsxref("String")}}、{{jsxref("Array")}}、{{jsxref("TypedArray")}}、{{jsxref("Map")}}、{{jsxref("Set")}} 以及 {{jsxref("Intl.Segments")}} 都是内置的可迭代对象，因为它们的每个 `prototype` 对象都实现了 `@@iterator` 方法。此外，[`argumen
```suggestion
{{jsxref("String")}}、{{jsxref("Array")}}、{{jsxref("TypedArray")}}、{{jsxref("Map")}}、{{jsxref("Set")}} 以及 {{jsxref("Intl.Segments")}} 都是内置的可迭代对象，因为它们的每个 `prototype` 对象都实现了 `@@iterator` 方法。此外，[`arguments`](/zh-CN/docs/Web/JavaScript/Reference/Functions/arguments) 对象和一些 DOM 集合类型，如 {{domxref("NodeList")}} 也是可迭代的。目前，没有内置的异步可迭代对象.
```

2022-11-30 11:21 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +Array Iterator {}
```suggestion
console.log([][Symbol.iterator]());

Array Iterator {}
```

2022-11-30 11:21 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +new WeakSet(
```suggestion
const myObj = {};

new WeakSet(
```

2022-11-30 11:21 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
>  // "c"
```suggestion
// "c"

```

2022-11-30 11:21 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +console.log([..."abc"]); // ["a", "b", "c"]
```suggestion
console.log([..."abc"]); // ["a", "b", "c"]

```

2022-11-30 11:21 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +console.log(gen().next()); // { value: "a", done: false }
```suggestion

console.log(gen().next()); // { value: "a", done: false }
```

2022-11-30 11:21 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/iteration_protocols/index.md
> +[a, b, c] = new Set(["a", "b", "c"]);
```suggestion
[a, b, c] = new Set(["a", "b", "c"]);

```

2022-11-30 11:34 UTC, yin1999 approved these changes
请注意我修改的这些问题，请尽量去与英文原文作一次比对，这些问题还是比较好找出来的。#10338 这个PR中还有一些比较明显的问题，请先自行修改

2022-11-30 11:37 UTC, merged