corregido el error #9805 [es]
mdn/translated-content pull request #10255
Opened 2022-11-27 15:27 UTC by EnriqueSource

### Description

### Motivation

### Additional details

### Related issues and pull requests

2022-11-28 22:15 UTC, Graywolf9 commented on files/es/learn/javascript/asynchronous/introducing/index.md
> +// "Hello, my name is Miriam!"
Las cadenas y ejemplos se pueden cambiar y hacer más amigable el ejemplo

```suggestion
const name = 'Miriam';
const greeting = `¡Hola, mi nombre es ${name}!`;
console.log(greeting);
// "¡Hola, mi nombre es Miriam!"
```

2022-11-28 23:16 UTC, Graywolf9 requested changes
Excelente traducción y actualización, muchas gracias!

Te he dejado algunos comentarios

2022-11-29 06:50 UTC, EnriqueSource commented on files/es/learn/javascript/asynchronous/introducing/index.md
> +La descripción que acabamos de ver de las funciones asíncronas podría recordarte a los manejadores de eventos, y si es así, tendrías razón. Los manejadores de eventos son, en realidad, una forma de p
Si que existe en español, aunque si crees que así queda mejor se cambia. La verdad es que aunque sea válida suena algo extraña.

2022-11-29 06:54 UTC, EnriqueSource commented
Gracias @Graywolf9. Sólo he dejado un comentario, aunque como digo, es español válido pero sueno un tanto extraño. Por eso creo que en efecto suena mejor con el cambio.

2022-11-29 16:30 UTC, Graywolf9 commented on files/es/learn/javascript/asynchronous/introducing/index.md
> +La descripción que acabamos de ver de las funciones asíncronas podría recordarte a los manejadores de eventos, y si es así, tendrías razón. Los manejadores de eventos son, en realidad, una forma de p
Sí en internet, no en la RAE, y como mencionas suena algo extraña 😅, entonces mejor una redacción más concreta

Muchas gracias 😁

2022-11-29 16:31 UTC, Graywolf9 approved these changes
Muchas gracias por tu tiempo y atenciones!

2022-11-29 16:40 UTC, Graywolf9 commented on files/es/learn/javascript/asynchronous/introducing/index.md
> +</table>
```suggestion
<table>
  <tbody>
    <tr>
      <th scope="row">Requisitos previos</th>
      <td>
        Conocimientos básicos de informática así como una comprensión razonable de los fundamentos de JavaScript, incluyendo funciones y manejadores de eventos.
      </td>
    </tr>
    <tr>
      <th scope="row">Objetivo:</th>
      <td>
        Familiarizarse con lo que es JavaScript asíncrono, en qué se diferencia de JavaScript síncrono y por qué lo necesitamos.
      </td>
    </tr>
  </tbody>
</table>
```

2022-11-29 16:48 UTC, merged