chore: replace `WebRTCSidebar` in ko
mdn/translated-content pull request #10291
Opened 2022-11-28 13:02 UTC by notJoon

### Description
Removed `{{WebRTCSidebar}}` macros and changed to `{{DefaultAPISidebar('WebRTC')}}`

### Additional details
  * add header `page-type`, `tags` which are missing in ko header
  * fixable link flaws and typos are fixed 

### Related issues and pull requests
* issue: #10177

2022-11-28 18:56 UTC, wbamberg reviewed
Thank you @notJoon !

Just a couple of comments: we should use `APIRef`, not `DefaultAPISidebar` for pages that are not under /api/webrtc_api.

Apart from that, the sidebar changes look good. The page type changes and code updates look good to me too. I didn't review anything else :).

2022-11-28 18:56 UTC, wbamberg commented on files/ko/web/api/rtcpeerconnection/currentlocaldescription/index.md
> +{{DefaultAPISidebar("WebRTC")}}
```suggestion
{{APIRef("WebRTC")}}
```

2022-11-28 18:56 UTC, wbamberg commented on files/ko/web/api/rtcpeerconnection/localdescription/index.md
> +{{DefaultAPISidebar("WebRTC")}}
```suggestion
{{APIRef("WebRTC")}}
```

2022-11-28 20:14 UTC, nschonni commented on files/ko/web/api/rtcpeerconnection/currentlocaldescription/index.md
> -읽기 속성인 **`RTCPeerConnection.currentLocalDescription`**은 가장 최근에 {{domxref("RTCPeerConnection")}}가 성공적으로 네고시에이션을 마치고 원격 피어와 연결된, 연결인터페이스의 로컬 엔드를 설명하는 {{domxref("RTCSessionDescription")}} 객체를 반환합니다. 이외에
These are usually bolded. There is a general cleanup for all the stuck bolding in the KO docs in https://github.com/mdn/translated-content/pull/10273

2022-11-29 01:31 UTC, notJoon commented
@wbamberg @nschonni 
thanks for your reviewing! all changes are updated

2022-11-29 01:38 UTC, wbamberg approved these changes
Thank you @notJoon , the sidebar changes look good to me!

2022-12-10 09:15 UTC, yin1999 commented on files/ko/web/api/rtcpeerconnection/currentlocaldescription/index.md
> +browser-compat: api.RTCPeerConnection.currentLocalDescription
we can remove this part, see: #7412

```suggestion
```

2022-12-10 09:15 UTC, yin1999 commented on files/ko/web/api/rtcpeerconnection/currentlocaldescription/index.md
> +- [WebRTC](/en-US/docs/Web/API/WebRTC_API)
```suggestion
- [WebRTC](/ko/docs/Web/API/WebRTC_API)
```

2022-12-10 09:15 UTC, yin1999 commented on files/ko/web/api/rtcpeerconnection/currentremotedescription/index.md
> +browser-compat: api.RTCPeerConnection.currentRemoteDescription
```suggestion
```

2022-12-10 09:15 UTC, yin1999 commented on files/ko/web/api/webrtc_api/adapter.js/index.md
> +  - WebRTC
```suggestion
```

2022-12-10 09:15 UTC, yin1999 commented on files/ko/web/api/webrtc_api/protocols/index.md
> +  - WebRTC API
```suggestion
```

2022-12-10 09:15 UTC, yin1999 commented on files/ko/web/api/webrtc_api/using_data_channels/index.md
> +  - buffering
```suggestion
```

2022-12-10 09:15 UTC, yin1999 commented on files/ko/web/api/webrtc_api/signaling_and_video_calling/index.md
> +`setLocalDescription()`의 fulfillment 핸들러가 실행되면, ICE agent는 [`icecandidate`](/en-US/docs/Web/API/RTCPeerConnection/icecandidate_event)event들을 처리하기 시작한다.
just link to localized documents (even if that not exists), yari would resolve this, see: #7413

```suggestion
`setLocalDescription()`의 fulfillment 핸들러가 실행되면, ICE agent는 [`icecandidate`](/ko/docs/Web/API/RTCPeerConnection/icecandidate_event)event들을 처리하기 시작한다.
```

2022-12-10 13:10 UTC, hochan222 commented
LGTM for me too. have a nice day everyone.

---

@notJoon 님 안녕하세요. [yin1999](https://github.com/yin1999)님께서 리뷰주셨듯이 [메타데이터 지침](https://github.com/mdn/translated-content/blob/main/docs/ko/translation-guide.md#%EB%A9%94%ED%83%80%EB%8D%B0%EC%9D%B4%ED%84%B0) 에서 해당 내용 확인 가능합니다.

시간 여유 괜찮으시다면 추후 다른 기여자 분들을 위해 [한국 번역 가이드 지침](https://github.com/mdn/translated-content/blob/main/docs/ko/translation-guide.md)에 기여주신 내용들 추가 부탁드려도 괜찮을까요?

그외 다른 사항들은 문제 없어보입니다. 기여해주셔서 감사합니다. 좋은 하루 보내세요 :)

2022-12-10 13:12 UTC, hochan222 requested changes
LGTM for me too. Have a nice day everyone.

---

@notJoon 님 안녕하세요. [yin1999](https://github.com/yin1999)님께서 리뷰주셨듯이 [메타데이터 지침](https://github.com/mdn/translated-content/blob/main/docs/ko/translation-guide.md#%EB%A9%94%ED%83%80%EB%8D%B0%EC%9D%B4%ED%84%B0) 에서 해당 내용 확인 가능합니다.

https://github.com/mdn/translated-content/pull/10291#discussion_r1045032240 는 반영 하지 않은 이유가 있으신지 궁금합니다.

시간 여유 괜찮으시다면 추후 다른 기여자 분들을 위해 [한국 번역 가이드 지침](https://github.com/mdn/translated-content/blob/main/docs/ko/translation-guide.md)에 기여주신 내용들 추가 부탁드립니다.

그외 다른 사항들은 문제 없어보입니다. 고생 많으셨습니다. 기여해주셔서 감사합니다. 좋은 하루 보내세요 :)

2022-12-10 14:29 UTC, notJoon commented
@hochan222 빠진 코멘트는 의도한건 아니고 못 보고 지나친거 같습니다. 꼼꼼히 안봤더니 이런 일이 다 일어나네요. 확인해주셔서 감사드리며, 좋은 하루 보내시길 바랍니다 👍

2022-12-10 14:32 UTC, hochan222 approved these changes

2022-12-10 14:32 UTC, merged