chore: adds translation for files/pt-br/web/api/htmlinputelement
mdn/translated-content pull request #10298
Opened 2022-11-28 23:14 UTC by josielrocha

### Description

Page content is outdated

- [en-US](https://developer.mozilla.org/en-US/docs/web/api/htmlinputelement)
- [pt-BR](https://developer.mozilla.org/pt-BR/docs/web/api/htmlinputelement)

### Motivation

### Additional details

### Related issues and pull requests

2022-11-30 00:06 UTC, nathipg commented on files/pt-br/web/api/htmlinputelement/index.md
> +- {{domxref("HTMLInputElement.list", "lista")}} {{ReadOnlyInline}}
```suggestion
- {{domxref("HTMLInputElement.list", "list")}} {{ReadOnlyInline}}
```

2022-11-30 00:08 UTC, nathipg commented on files/pt-br/web/api/htmlinputelement/index.md
> +  - : `string`: **Retorna / Define** o atributo [`name`](/pt-BR/docs/Web/HTML/Element/Input#name) do elemento, contendo um nome que identifica o elemento ao enviar o Formato.
```suggestion
  - : `string`: **Retorna / Define** o atributo [`name`](/pt-BR/docs/Web/HTML/Element/Input#name) do elemento, contendo um nome que identifica o elemento ao enviar o formulário.
```

2022-11-30 00:17 UTC, nathipg commented on files/pt-br/web/api/htmlinputelement/index.md
> +### Propriedades de instância que se aplicam a qualquer tipo de elemento de entrada que não esteja oculto
=== Pausei a revisão aqui ===

2022-12-13 01:01 UTC, nathipg commented on files/pt-br/web/api/htmlinputelement/index.md
> +  - : `boolean`: **Retorna / Define** o atributo [`required`](/pt-BR/docs/Web/HTML/Element/Input#required) do elemento, indicando que o usuário deve preencher um valor antes enviando um formulário.
```suggestion
  - : `boolean`: **Retorna / Define** o atributo [`required`](/pt-BR/docs/Web/HTML/Element/Input#required) do elemento, indicando que o usuário deve preencher um valor antes de enviar um formulário.
```

2022-12-13 01:11 UTC, nathipg commented on files/pt-br/web/api/htmlinputelement/index.md
> +  - : `string`: **Retorna / Define** o atributo [`max`](/pt-BR/docs/Web/HTML/Element/Input#max) do elemento, contendo o máximo (numérico ou data-hora) valor para este item, que não deve ser menor que
```suggestion
  - : `string`: **Retorna / Define** o atributo [`max`](/pt-BR/docs/Web/HTML/Element/Input#max) do elemento, contendo o valor (numérico ou data-hora) máximo para este item, que não deve ser menor que seu valor mínimo (atributo [`min`](/pt-BR/docs/Web/HTML/Element/Input#min)).
```

2022-12-13 01:12 UTC, nathipg commented on files/pt-br/web/api/htmlinputelement/index.md
> +  - : `unsigned long`: **Retorna / Define** o atributo [`maxlength`](/pt-BR/docs/Web/HTML/Element/Input#maxlength) do elemento, contendo o número máximo de caracteres (em Unicode pontos de código) qu
```suggestion
  - : `unsigned long`: **Retorna / Define** o atributo [`maxlength`](/pt-BR/docs/Web/HTML/Element/Input#maxlength) do elemento, contendo o número máximo de caracteres (em pontos de código Unicode) que o valor pode ter.
```

2022-12-13 01:13 UTC, nathipg commented on files/pt-br/web/api/htmlinputelement/index.md
> +  - : `string`: **Retorna / Define** o atributo [`min`](/pt-BR/docs/Web/HTML/Element/Input#min) do elemento, contendo o mínimo (numérico ou data-hora) valor para este item, que não deve ser maior que
```suggestion
  - : `string`: **Retorna / Define** o atributo [`min`](/pt-BR/docs/Web/HTML/Element/Input#min) do elemento, contendo o valor (numérico ou data-hora) mínimo para este item, que não deve ser maior que seu valor máximo (atributo [`max`](/pt-BR/docs/Web/HTML/Element/Input#max)).
```

2022-12-13 01:14 UTC, nathipg commented on files/pt-br/web/api/htmlinputelement/index.md
> +- {{domxref("HTMLInputElement.pattern", "padrão")}}
```suggestion
- {{domxref("HTMLInputElement.pattern", "pattern")}}
```

2022-12-13 01:17 UTC, nathipg commented on files/pt-br/web/api/htmlinputelement/index.md
> +  - : `boolean`: **Retorna / Define** o atributo [`readonly`](/pt-BR/docs/Web/HTML/Element/Input#readonly) do elemento, indicando que o usuário não pode modificar o valor do ao controle. Isso é ignor
```suggestion
  - : `boolean`: **Retorna / Define** o atributo [`readonly`](/pt-BR/docs/Web/HTML/Element/Input#readonly) do elemento, indicando que o usuário não pode modificar o valor do controle. Isso é ignorado se o [`type`](/pt-BR/docs/Web/HTML/Element/Input#type) for `hidden`, `range`, `color`, `checkbox`, `radio`, `file`, ou um tipo de botão.
```

2022-12-13 01:23 UTC, nathipg commented on files/pt-br/web/api/htmlinputelement/index.md
> +  - : Seleciona todo o texto no elemento de entrada e o concentra para que o usuário possa substituir posteriormente todo o seu conteúdo.
```suggestion
  - : Seleciona todo o texto no elemento de entrada e o foca para que o usuário possa substituir posteriormente todo o seu conteúdo.
```

2022-12-13 01:25 UTC, nathipg commented on files/pt-br/web/api/htmlinputelement/index.md
> +  - : define uma mensagem de validade personalizada para o elemento. Se esta mensagem não for a string vazia, o elemento está sofrendo de um erro de validade personalizado e não é validado.
```suggestion
  - : Define uma mensagem de validação personalizada para o elemento. Se esta mensagem não for a string vazia, o elemento está sofrendo de um erro de validade personalizado e não é validado.
```

2022-12-13 01:29 UTC, nathipg commented on files/pt-br/web/api/htmlinputelement/index.md
> +  - : Decrementa o [`value`](/pt-BR/docs/Web/HTML/Element/Input#value) em ([`step`](/pt-BR/docs/Web/HTML/Element/Input# step) \* n), em que n é padronizado como 1 se não for especificado. Lança uma e
```suggestion
  - : Decrementa o [`value`](/pt-BR/docs/Web/HTML/Element/Input#value) em ([`step`](/pt-BR/docs/Web/HTML/Element/input#step) \* n), em que n é padronizado como 1 se não for especificado. Lança uma exceção `InvalidStateError`:
```

2022-12-13 01:30 UTC, nathipg commented on files/pt-br/web/api/htmlinputelement/index.md
> +    - se o valor resultante estiver acima de [`max`](/pt-BR/docs/Web/HTML/Element/Input#max) ou abaixo de [`min`](/pt-BR/docs/Web/HTML /Elemento/entrada#min).
```suggestion
    - se o valor resultante estiver acima de [`max`](/pt-BR/docs/Web/HTML/Element/Input#max) ou abaixo de [`min`](/pt-BR/docs/Web/HTML/Element/input#min)..
```

2022-12-13 01:31 UTC, nathipg commented on files/pt-br/web/api/htmlinputelement/index.md
> +  - : Incrementa o [`value`](/pt-BR/docs/Web/HTML/Element/Input#value) em ([`step`](/pt-BR/docs/Web/HTML/Element/Input# step) \* n), em que n é padronizado como 1 se não for especificado. Lança uma e
```suggestion
  - : Incrementa o [`value`](/pt-BR/docs/Web/HTML/Element/Input#value) em ([`step`](/pt-BR/docs/Web/HTML/Element/input#step) \* n), em que n é padronizado como 1 se não for especificado. Lança uma exceção `InvalidStateError`:
```

2022-12-13 01:32 UTC, nathipg commented on files/pt-br/web/api/htmlinputelement/index.md
> +    - se o método não for aplicável para o valor atual de [`type`](/pt-BR/docs/Web/HTML/Element/Input#type).,
```suggestion
    - se o método não for aplicável para o valor atual de [`type`](/pt-BR/docs/Web/HTML/Element/Input#type),
```

2022-12-13 01:33 UTC, nathipg commented on files/pt-br/web/api/htmlinputelement/index.md
> +    - se o valor resultante estiver acima de [`max`](/pt-BR/docs/Web/HTML/Element/Input#max) ou abaixo de [`min`](/pt-BR/docs/Web/HTML /Elemento/entrada#min).
```suggestion
    - se o valor resultante estiver acima de [`max`](/pt-BR/docs/Web/HTML/Element/Input#max) ou abaixo de [`min`](/pt-BR/docs/Web/HTML/Element/input#min)..
```

2022-12-13 01:34 UTC, nathipg commented on files/pt-br/web/api/htmlinputelement/index.md
> +  - : Dispara quando o `value` de um elemento {{HTMLElement("input")}}, {{HTMLElement("select")}} ou {{HTMLElement("textarea")}} foi alterado. Observe que isso é realmente acionado na interface {{dom
```suggestion
  - : Dispara quando o `value` de um elemento {{HTMLElement("input")}}, {{HTMLElement("select")}} ou {{HTMLElement("textarea")}} foi alterado. Observe que na verdade isso é acionado na interface {{domxref("HTMLElement")}} e também se aplica a elementos [`contenteditable`](/pt-BR/docs/Web/HTML/Global_attributes/contenteditable), mas também listamos aqui porque é mais comumente usado com elementos de entrada de formulário.
```

2022-12-13 01:37 UTC, nathipg requested changes
Obrigada pela contribuição! Essa página é bem longa xD
Poderia dar uma olhada em algumas questões que apontei, por favor?

2022-12-13 02:09 UTC, josielrocha commented on files/pt-br/web/api/htmlinputelement/index.md
> +    - se o valor resultante estiver acima de [`max`](/pt-BR/docs/Web/HTML/Element/Input#max) ou abaixo de [`min`](/pt-BR/docs/Web/HTML /Elemento/entrada#min).
Aqui, parece que o `.` da sugestão ficou duplicado.

2022-12-13 02:10 UTC, josielrocha commented on files/pt-br/web/api/htmlinputelement/index.md
> +    - se o valor resultante estiver acima de [`max`](/pt-BR/docs/Web/HTML/Element/Input#max) ou abaixo de [`min`](/pt-BR/docs/Web/HTML /Elemento/entrada#min).
Mesmo caso aqui da sugestão com o `.` duplicado.

2022-12-13 02:16 UTC, josielrocha commented
> Obrigada pela contribuição! Essa página é bem longa xD Poderia dar uma olhada em algumas questões que apontei, por favor?

Olá @nathipg!

Realmente é uma página bem extensa.
Apliquei quase todas as suas sugestões.. Apenas duas delas tinham um `.` duplicado, então fiz a alteração manualmente em um commit separado.

Obrigado, mais uma vez, pelo seu apoio!

2023-01-08 20:09 UTC, merged