improved css/learn documents in KO
mdn/translated-content pull request #10293
Opened 2022-11-28 14:23 UTC by notJoon

### Description
* [이미지, 미디어 및 양식 요소](https://developer.mozilla.org/ko/docs/Learn/CSS/Building_blocks/Images_media_form_elements) 문서 중 일부 미번역 된 문장을 번역했습니다.
* 이미지 경로들을 수정했습니다.
* 문서 헤더에 `tags`를 영문판과 동일하게 추가했습니다.
* 오타 수정

2022-11-29 04:36 UTC, yujo11 requested changes
안녕하세요 notJoon님 기여 감사합니다!

내용 상에 코멘트 드릴내용은 없었는데요.

이제 `tags`의 경우 더 이상 사용하지 않고 있어서 제거 해주시면 감사하겠습니다! 🙇‍♂️🙇‍♂️

2022-11-29 04:36 UTC, yujo11 commented on files/ko/learn/css/building_blocks/cascade_and_inheritance/index.md
> +  - specificity
`tags`는 이제 사용하지 않아서 추가해주실 필요 없습니다!

참고: [번역가이드- 메타데이터](https://github.com/mdn/translated-content/blob/main/docs/ko/translation-guide.md#%EB%A9%94%ED%83%80%EB%8D%B0%EC%9D%B4%ED%84%B0)

2022-11-29 04:36 UTC, yujo11 commented on files/ko/learn/css/building_blocks/images_media_form_elements/index.md
> +title: 이미지, 미디어 및 양식 요소
👍👍👍

2022-11-29 05:42 UTC, notJoon commented on files/ko/learn/css/building_blocks/cascade_and_inheritance/index.md
> +  - specificity
확인해주서서 감사합니다. 리뷰 내용 반영해서 수정했습니다 👍👍

2022-12-13 03:12 UTC, notJoon commented
@yujo11 이걸 지금 확인했네요 불필요한 tag하고 충돌난 부분들은 전부 해결했습니다.

2023-01-01 07:48 UTC, hochan222 approved these changes
@notJoon 님, @notJoon 님 고생 많으셨습니다. 리뷰 사항 이상 없고, PR 지연이 되어서 제가 병합하겠습니다!

모두 새해 복 많이 받으세요 :)

2023-01-01 07:48 UTC, merged