JavaScript: Add Int32Array, Uint32Array
mdn/translated-content pull request #10300
Opened 2022-11-29 00:25 UTC by wisedog

Int32Array, Uint32Array 추가

2022-12-03 16:08 UTC, hochan222 reviewed
휴가로 12월 9일 이후에 리뷰 드릴 수 있을 것 같습니다. 양해 부탁 드립니다.

좋은 하루 보내세요 :)

2022-12-10 14:28 UTC, hochan222 requested changes
@wisedog 님 안녕하세요.

리뷰사항은 아래에 남겨두었습니다.

고생하셨습니다! 좋은 하루 보내세요 :)

2022-12-10 14:28 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/int32array/int32array/index.md
> +new Int32Array(object)
```suggestion
new Int32Array(object)

```

원문과 같이 위와 아래 코드는 buffer와 그외의 것들로 구분가능하므로 가독성을 위해 개행을 추가해주는것이 좋아 보여서 리뷰 드렸습니다.

2022-12-10 14:28 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/uint32array/uint32array/index.md
> +new Uint32Array(object)
```suggestion
new Uint32Array(object)

```

2022-12-11 00:51 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/int32array/int32array/index.md
> +new Int32Array(object)
음 - 이런 문제가.... 사실 전 contents 에서 안가져오고 없는 문서 있으면 github 에서 바로소스보기로 가져오거든요. 근데 긁어올때 코드 내의 엔터는 제대로 못긁어오더라구요. ㅠㅠ

다음부터 주의하겠습니다.

2022-12-11 09:32 UTC, hochan222 approved these changes
LGTM :)

2022-12-11 09:34 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/int32array/int32array/index.md
> +new Int32Array(object)
처음에는 저도 동일하게 가져왔는데 이미지도 로컬 서버에서만 확인할 수 있고 해서, 어느 순간부터는 contents에서 가져오고 있습니다. 고생 많으셨습니다!

2022-12-11 09:34 UTC, merged