zh-cn(update): sync promsie.allsettled
mdn/translated-content pull request #10310
Opened 2022-11-29 07:21 UTC by Jack-Zhang-1314

### Description

### Motivation

### Additional details

### Related issues and pull requests

2022-11-29 07:22 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/global_objects/promise/allsettled/index.md
> +`Promise.allSettled()` 方法是 [promise 并发性](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise#promise_concurrency)方法的其中之一。`Promise.allSettled()` 通常用于你有多个不依赖于彼此成功完成的异步任务时，或者你总是想知道每个 promise 的结果
由于 promise 文档过旧，hash 还是指向英文版

2022-11-29 11:31 UTC, yin1999 requested changes

2022-11-29 11:31 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/promise/allsettled/index.md
> +**`Promise.allSettled()`** 方法接受一个 promise 的可迭代类型作为输入，并且返回一个 {{jsxref("Promise")}} 实例。当输入的所有 promise 都已敲定时（包括传递空的可迭代类型），返回的 promise 使用一个带有描述每个 promsie 结果的对象数组兑现。
请修改

2022-11-29 11:44 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/global_objects/promise/allsettled/index.md
> +**`Promise.allSettled()`** 方法接受一个 promise 的可迭代类型作为输入，并且返回一个 {{jsxref("Promise")}} 实例。当输入的所有 promise 都已敲定时（包括传递空的可迭代类型），返回的 promise 使用一个带有描述每个 promsie 结果的对象数组兑现。
```suggestion
**`Promise.allSettled()`** 方法接受一个 promise 的可迭代类型作为输入，并且返回一个 {{jsxref("Promise")}} 实例。当输入的所有 promise 都已敲定时（包括传递空的可迭代类型），返回的 promise 将兑现，并带有描述每个 promsie 结果的对象数组。
```

2022-11-29 11:45 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/global_objects/promise/allsettled/index.md
> +**`Promise.allSettled()`** 方法接受一个 promise 的可迭代类型作为输入，并且返回一个 {{jsxref("Promise")}} 实例。当输入的所有 promise 都已敲定时（包括传递空的可迭代类型），返回的 promise 使用一个带有描述每个 promsie 结果的对象数组兑现。
已修改

2022-11-29 11:58 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/promise/allsettled/index.md
> +**`Promise.allSettled()`** 方法接受一个 promise 的可迭代类型作为输入，并且返回一个 {{jsxref("Promise")}} 实例。当输入的所有 promise 都已敲定时（包括传递空的可迭代类型），返回的 promise 使用一个带有描述每个 promsie 结果的对象数组兑现。
第一句话翻译是由问题的，再好好考虑一下

2022-11-29 12:00 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/global_objects/promise/allsettled/index.md
> +**`Promise.allSettled()`** 方法接受一个 promise 的可迭代类型作为输入，并且返回一个 {{jsxref("Promise")}} 实例。当输入的所有 promise 都已敲定时（包括传递空的可迭代类型），返回的 promise 使用一个带有描述每个 promsie 结果的对象数组兑现。
好的，我当时直接抄的 promise.all

2022-11-29 12:03 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/promise/allsettled/index.md
> +**`Promise.allSettled()`** 方法接受一个 promise 的可迭代类型作为输入，并且返回一个 {{jsxref("Promise")}} 实例。当输入的所有 promise 都已敲定时（包括传递空的可迭代类型），返回的 promise 使用一个带有描述每个 promsie 结果的对象数组兑现。
翻译请与英文原文对应，以前的翻译并不一定正确，只能作参考

2022-11-29 12:24 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/global_objects/promise/allsettled/index.md
> +**`Promise.allSettled()`** 方法接受一个 promise 的可迭代类型作为输入，并且返回一个 {{jsxref("Promise")}} 实例。当输入的所有 promise 都已敲定时（包括传递空的可迭代类型），返回的 promise 使用一个带有描述每个 promsie 结果的对象数组兑现。
修改好了

2022-11-29 14:20 UTC, Jack-Zhang-1314 commented
```js
const promise1 = Promise.resolve(3);
const promise2 = new Promise((resolve, reject) => setTimeout(reject, 100, 'foo'));
const promises = [promise1, promise2];

const obj = {
  [Symbol.iterator]() {
    let i = 0;
     return {
       next() {
         i++;
         if (i === 3) return { done: true, value: promise1 };
         return { done: false, value: i };
       }
     };
  },
};


Promise.allSettled(obj).
  then((results) => results.forEach((result) => console.log(result.status)));
```

@yin1999 像传入一个可迭代的 promise 参数，必须使用 可迭代的迭代器，但是如果我像下面这样, 这个 this 指向的是 obj 对象，但是不能进行迭代，而上面的是可以的，但是上面的 return 也是返回的一个有 next 的对象

```js
const promise1 = Promise.resolve(3);
const promise2 = new Promise((resolve, reject) => setTimeout(reject, 100, 'foo'));
const promises = [promise1, promise2];

const obj = {
  next(){
  // ...
  },
  [Symbol.iterator]() {
    let i = 0;
     return  this
  },
};
```

2022-11-29 14:26 UTC, yin1999 commented
> an iterable of promises

由 promise 组成的可迭代对象，并不是可迭代的 promise

```js
const promise1 = Promise.resolve(3);
const promise2 = new Promise((resolve, reject) => setTimeout(reject, 100, 'foo'));
const promises = [promise1, promise2];
```

这里的 promises 就是 promise 组成的可迭代对象，因为它是数组。修改的翻译还是有问题的，不要和前面翻译的可迭代对象弄混了。这个看例子应该很好理解。

2022-11-29 14:31 UTC, yin1999 commented
```js
const promise1 = Promise.resolve(3);
const promise2 = new Promise((resolve, reject) => setTimeout(reject, 100, 'foo'));
const promises = [promise1, promise2];

const obj = {
  next(){
  // ...
  },
  [Symbol.iterator]() {
     return  this
  },
};
```

next 方法**必须**实现迭代器协议，即必须返回一个对象:

```js
{value: any, done: boolean }
```

2022-11-29 14:33 UTC, Jack-Zhang-1314 commented
嗯，是要停止迭代必须要实现，大意了

2022-11-30 11:37 UTC, yin1999 requested changes

2022-11-30 11:37 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/promise/allsettled/index.md
> +  - : 一个[可迭代的](/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterable_protocol)（例如{{jsxref("Array")}}）promise。
下面也需修改，请更正并检查全文

2022-11-30 11:41 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/global_objects/promise/allsettled/index.md
> +  - : 一个[可迭代的](/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterable_protocol)（例如{{jsxref("Array")}}）promise。
```suggestion
  - : 一个[可迭代的](/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#可迭代的协议)（例如{{jsxref("Array")}}）promise。
```

2022-11-30 11:44 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/global_objects/promise/allsettled/index.md
> +  - : 一个[可迭代的](/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterable_protocol)（例如{{jsxref("Array")}}）promise。
下面的 hash？

2022-11-30 11:45 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/promise/allsettled/index.md
> +  - : 一个[可迭代的](/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterable_protocol)（例如{{jsxref("Array")}}）promise。
https://github.com/mdn/translated-content/pull/10310#issuecomment-1330729945

2022-11-30 11:49 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/global_objects/promise/allsettled/index.md
> +  - : 一个[可迭代的](/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#可迭代的协议)（例如{{jsxref("Array")}}）promise。
```suggestion
  - : 一个以 promise 组成的[可迭代](/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#可迭代的协议)（例如{{jsxref("Array")}}）对象。
```

2022-12-01 01:07 UTC, yin1999 requested changes

2022-12-01 01:07 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/promise/allsettled/index.md
> +  - : 一个以 promise 组成的[可迭代](/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#可迭代的协议)（例如{{jsxref("Array")}}）对象。
```suggestion
  - : 一个以 promise 组成的[可迭代](/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#可迭代的协议)（例如 {{jsxref("Array")}}）对象。
```

2022-12-01 01:07 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/promise/allsettled/index.md
> +- **异步兑现**，当给定的 `iterable` 中所有 promise 已经敲定时（要么已兑现，要么已拒绝）。兑现的值是一个对象数组，每个对象都以 `iterable` 的顺序描述一个 promise 的结果，无论完成顺序如何。每个结果对象都有以下的属性：
> 每个对象都以 `iterable` 的顺序描述一个 promise 的结果

不对

2022-12-01 01:07 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/promise/allsettled/index.md
> +`Promise.allSettled()` 方法是 [promise 并发性](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise#promise_concurrency)方法的其中之一。`Promise.allSettled()` 通常用于你有多个不依赖于彼此成功完成的异步任务时，或者你总是想知道每个 promise 的结果
用于xxxxx时，不符合中文语法

2022-12-01 04:59 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/global_objects/promise/allsettled/index.md
> +- **异步兑现**，当给定的 `iterable` 中所有 promise 已经敲定时（要么已兑现，要么已拒绝）。兑现的值是一个对象数组，每个对象都以 `iterable` 的顺序描述一个 promise 的结果，无论完成顺序如何。每个结果对象都有以下的属性：
```suggestion
- **异步兑现**，当给定的 `iterable` 中所有 promise 已经敲定时（要么已兑现，要么已拒绝）。兑现的值是一个对象数组，每个对象都按照 promise 传递的顺序，描述在 `iterable` 中每一个 promise 的结果，无论完成顺序如何。每个结果对象都有以下的属性：
```

2022-12-01 05:01 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/global_objects/promise/allsettled/index.md
> +`Promise.allSettled()` 方法是 [promise 并发性](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise#promise_concurrency)方法的其中之一。`Promise.allSettled()` 通常用于你有多个不依赖于彼此成功完成的异步任务时，或者你总是想知道每个 promise 的结果
```suggestion
`Promise.allSettled()` 方法是 [promise 并发性](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise#promise_concurrency)方法的其中之一。在你有多个不依赖于彼此成功完成的异步任务时，或者你总是想知道每个 promise 的结果时，使用 `Promise.allSettled()` 。
```

2022-12-01 05:30 UTC, yin1999 approved these changes

2022-12-01 05:30 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/promise/allsettled/index.md
> +- **异步兑现**，当给定的 `iterable` 中所有 promise 已经敲定时（要么已兑现，要么已拒绝）。兑现的值是一个对象数组，每个对象都按照 promise 传递的顺序，描述在 `iterable` 中每一个 promise 的结果，无论完成顺序如何。每个结果对象都有以下的属性：
```suggestion
- **异步兑现**，当给定的 `iterable` 中所有 promise 已经敲定时（要么已兑现，要么已拒绝）。兑现的值是一个对象数组，其中的对象按照 `iterable` 中 promise 传递的顺序，描述每一个 promise 的结果，无论完成顺序如何。每个结果对象都有以下的属性：
```

2022-12-01 10:50 UTC, merged