zh-cn(update): sync toStringTag
mdn/translated-content pull request #10338
Opened 2022-11-30 05:59 UTC by Jack-Zhang-1314

### Description

### Motivation

### Additional details

### Related issues and pull requests

2022-11-30 11:53 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/global_objects/symbol/tostringtag/index.md
> +### 有着 toStringTag 的自定义标签
```suggestion
### 使用 toStringTag 自定义标签
```

2022-11-30 11:54 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/global_objects/symbol/tostringtag/index.md
> +更多内置的对象提供了它们自己的 `@@toStringTag` 属性。所有内置对象的 `@@toStringTag` 属性都是不可写的（writable）、不可枚举的（enumerable）以及不可配置的（configurable）。
```suggestion
大多数内置的对象提供了它们自己的 `@@toStringTag` 属性。所有内置对象的 `@@toStringTag` 属性都是不可写的（writable）、不可枚举的（enumerable）但是可配置的（configurable）。
```

2022-11-30 11:55 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/global_objects/symbol/tostringtag/index.md
> +现在，在 `toStringTag` 的帮助下，您可以设置自己的自定义标签：
```suggestion
现在，在 `toStringTag` 的帮助下，你可以设置自己的自定义标签：
```

2022-11-30 12:08 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/global_objects/symbol/tostringtag/index.md
> +大多数内置的对象提供了它们自己的 `@@toStringTag` 属性。所有内置对象的 `@@toStringTag` 属性都是不可写的（writable）、不可枚举的（enumerable）但是可配置的（configurable）。
```suggestion
大多数内置的对象提供了它们自己的 `@@toStringTag` 属性。所有内置对象的 `@@toStringTag` 属性都是不可写的（writable）、不可枚举的（enumerable）并且不可配置的（configurable）。
```

https://github.com/mdn/content/pull/22633

2022-11-30 12:14 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/global_objects/symbol/tostringtag/index.md
> +**`Symbol.toStringTag`**，众所周知的 symbol，其是一个字符串值属性，用于创建对象的默认字符串描述。它由 {{jsxref("Object.prototype.toString()")}} 方法内部访问。
```suggestion
已知的 **`Symbol.toStringTag`**  symbol 是一个字符串值属性，用于创建对象的默认字符串描述。它由 {{jsxref("Object.prototype.toString()")}} 方法内部访问。
```

2022-12-01 11:28 UTC, yin1999 requested changes

2022-12-01 11:28 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/symbol/tostringtag/index.md
> +由于 2020 年年中 [WebIDL规范的变化](https://github.com/whatwg/webidl/pull/357)，浏览器正在向所有 DOM 原型对象添加 `Symbol.toStringTag` 属性。例如，要访问 {{domxref("HTMLButtonElement")}} 上的 `Symbol.toStringTag` 属性：
```suggestion
由于 2020 年年中 [WebIDL 规范的变化](https://github.com/whatwg/webidl/pull/357)，浏览器正在向所有 DOM 原型对象添加 `Symbol.toStringTag` 属性。例如，要访问 {{domxref("HTMLButtonElement")}} 上的 `Symbol.toStringTag` 属性：
```

2022-12-01 11:56 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/global_objects/symbol/tostringtag/index.md
> +已知的 **`Symbol.toStringTag`** symbol 是一个字符串值属性，用于创建对象的默认字符串描述。它由 {{jsxref("Object.prototype.toString()")}} 方法内部访问。
@yin1999 https://262.ecma-international.org/6.0/#sec-well-known-symbols, 我觉得不翻译，它是 javascript 内部实现的一些特殊 symbol

2022-12-01 11:57 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/global_objects/symbol/tostringtag/index.md
> +已知的 **`Symbol.toStringTag`** symbol 是一个字符串值属性，用于创建对象的默认字符串描述。它由 {{jsxref("Object.prototype.toString()")}} 方法内部访问。
看了一下日本的翻译，也是没有翻译 https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Symbol#well-known_symbol

2022-12-03 16:27 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/global_objects/symbol/tostringtag/index.md
> +已知的 **`Symbol.toStringTag`** symbol 是一个字符串值属性，用于创建对象的默认字符串描述。它由 {{jsxref("Object.prototype.toString()")}} 方法内部访问。
我问了一下，well-known 有通用的意思，然后这些 symbol 都是内置的，建议翻译 **内置通用**

2022-12-04 01:28 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/symbol/tostringtag/index.md
> +已知的 **`Symbol.toStringTag`** symbol 是一个字符串值属性，用于创建对象的默认字符串描述。它由 {{jsxref("Object.prototype.toString()")}} 方法内部访问。
> 我问了一下，well-known 有通用的意思，然后这些 symbol 都是内置的，建议翻译 **内置通用**

`well-known` 的确是众所周知的意思，但在中文语境下，这么翻译并不合适。我赞同使用“内置通用”这一翻译，若有时间，请另开PR更新其它的页面中对该词的翻译（附加英文 `well-known`）。感谢

2022-12-04 05:21 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/global_objects/symbol/tostringtag/index.md
> +已知的 **`Symbol.toStringTag`** symbol 是一个字符串值属性，用于创建对象的默认字符串描述。它由 {{jsxref("Object.prototype.toString()")}} 方法内部访问。
```suggestion
**`Symbol.toStringTag`**（内置通用的 symbol）是一个字符串值属性，用于创建对象的默认字符串描述。它由 {{jsxref("Object.prototype.toString()")}} 方法内部访问。
```

2022-12-04 05:22 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/global_objects/symbol/tostringtag/index.md
> +已知的 **`Symbol.toStringTag`** symbol 是一个字符串值属性，用于创建对象的默认字符串描述。它由 {{jsxref("Object.prototype.toString()")}} 方法内部访问。
改成这样，你看合不合适

2022-12-04 07:25 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/symbol/tostringtag/index.md
> +已知的 **`Symbol.toStringTag`** symbol 是一个字符串值属性，用于创建对象的默认字符串描述。它由 {{jsxref("Object.prototype.toString()")}} 方法内部访问。
`内置通用 symbol` 即可

2022-12-04 07:39 UTC, yin1999 approved these changes
Thanks

2022-12-04 07:39 UTC, merged