:speech_balloon: [ko] translate CORS preflight error to korean.
mdn/translated-content pull request #10362
Opened 2022-12-01 09:23 UTC by rjsdn0124

### Description
번역되어 있지 않던 페이지를 번역했습니다!

### Motivation

### Additional details
#10361

### Related issues and pull requests

2022-12-08 17:57 UTC, yujo11 requested changes

2022-12-08 17:57 UTC, yujo11 commented on files/ko/web/http/cors/errors/corspreflightdidnotsucceed/index.md
> +  - troubleshooting
`tags`의 경우 현재 쓰이지 않아서 제거를 부탁 드리겠습니다.

참고문서 : https://github.com/mdn/translated-content/blob/main/docs/ko/translation-guide.md#%EB%A9%94%ED%83%80%EB%8D%B0%EC%9D%B4%ED%84%B0

2022-12-09 03:03 UTC, rjsdn0124 commented on files/ko/web/http/cors/errors/corspreflightdidnotsucceed/index.md
> +  - troubleshooting
수정했습니다!

2022-12-11 05:38 UTC, yujo11 approved these changes

2022-12-11 05:38 UTC, merged