Translate Web/Performance/Understanding_latency
mdn/translated-content pull request #10427
Opened 2022-12-03 16:24 UTC by jaeyeong951

### Description
`Web/Performance/Understanding_latency` 문서 전체를 한국어로 번역했습니다. 
처음 기여하는거라 부족한 점이 많습니다. 번역 가이드와 기여 지침을 꼼꼼히 읽고 따랐지만 혹시 잘못된 부분이 있을 수 있습니다.
피드백 부탁드립니다!

2022-12-05 14:00 UTC, hochan222 commented
@jaeyeong951 님 안녕하세요.

휴가로 12월 9일 이후에 리뷰 드릴 수 있을 것 같습니다. 양해 부탁 드립니다.

좋은 하루 보내세요 :)

2022-12-12 13:50 UTC, hochan222 requested changes
@jaeyeong951 님 안녕하세요.

리뷰가 늦어져서 죄송합니다.

세부 리뷰사항은 아래에 남겨놓았습니다. 몇몇 리뷰 사항은 강제가 아니기에 좋은 이유가 있으실 경우 말씀해주신 후  유지하셔도 무방합니다.

기여해주셔서 감사합니다 좋은 하루 보내세요 :)

---

png 파일의 경우는 폴더안에 넣지 않아도 자동으로 yari (mdn 서버)에서 경로를 맞게 넣어주고 있습니다. __따라서 png 파일들은 모두 제거 부탁드립니다.__

이미지가 잘 나오는지는 yari 를 local에서 아래 경로로 확인하실 수 있습니다.

```
http://localhost:3000/ko/docs/web/performance/understanding_latency
```

yari 실행 방법은 [yari](https://github.com/mdn/yari) 나 [[MDN] Markdown 변환 완료 및 앞으로의 방향성](https://egas.tistory.com/168) 참고 부탁드립니다.

2022-12-12 13:50 UTC, hochan222 commented on files/ko/web/performance/understanding_latency/index.md
> +레이턴시란 일반적으로 사용자가 요청을 하고 해당 요청에 대한 응답을 받기까지 걸리는 시간을 말합니다. 14KB 만큼의 첫 요청에서는 {{glossary('DNS')}} 조회, {{glossary('TCP handshake')}}, 보안 {{glossary('TLS')}} 협상 등의 과정을 거치기 때문에 레이턴시가 큽니다. 이후의 연속된 요청은 서버와의 연
```suggestion
레이턴시란 일반적으로 사용자가 요청을 한 시점부터 해당 사용자에게 요청에 대한 응답을 받기까지 걸리는 시간을 말합니다. 첫 번째 요청에서 14KB 만큼의 {{glossary('DNS')}} 조회, {{glossary('TCP handshake')}}, 보안 {{glossary('TLS')}} 협상 등의 과정을 거치기 때문에 레이턴시가 큽니다. 이후의 후속 요청은 서버에 대한 연결이 이미 설정되어 있으므로 레이턴시이 줄어듭니다.
```

원문은 최대한 그대로 번역하는것을 지침으로 하고 있어서 해당 사항 반영했습니다.

2022-12-12 13:50 UTC, hochan222 commented on files/ko/web/performance/understanding_latency/index.md
> +레이턴시는 네트워크나 인터넷 연결의 지연 시간을 나타냅니다. 낮은 레이턴시는 지연이 없거나 아주 적다는 것을 의미하고 높은 레이턴시는 지연이 많다는 걸 의미합니다. 성능 향상의 주요 목표 중 하나가 레이턴시를 줄이는 것입니다.
```suggestion
대기 시간은 네트워크나 인터넷 연결의 지연 시간을 나타냅니다. 대기 시간이 짧다는 것은 지연이 없거나 거의 없음을 의미합니다. 대기 시간이 길다는 것은 지연이 많다는 것을 의미합니다. 성능 향상의 주요 목표 중 하나는 대기 시간을 줄이는 것입니다.
```

문장의 개수도 `content repo`와 동일하게  유지하는것이 좋습니다.

2022-12-12 13:50 UTC, hochan222 commented on files/ko/web/performance/understanding_latency/index.md
> +기본적인 HTML 페이지와 같이 한 개의 자원 대한 레이턴시는 사소해 보일 수 있습니다. 하지만 웹사이트는 일반적으로 여러 개의 요청을 포함합니다. HTML은 여러 개의 CSS, 스크립트, 미디어 파일에 대한 요청으로 이루어져 있기 때문입니다. 이런 요청의 크기와 개수가 커질수록 높은 레이턴시가 사용자 경험에 미치는 영향 또한 커집니다.
```suggestion
기본적인 HTML 페이지와 같이 한 개의 자원에 대한 레이턴시는 사소해 보일 수 있습니다. 하지만 웹사이트는 일반적으로 여러 개의 요청을 포함합니다. HTML은 여러 개의 CSS, 스크립트, 미디어 파일에 대한 요청으로 이루어져 있기 때문입니다. 이런 요청의 개수와 크기가 커질수록 높은 레이턴시가 사용자 경험에 미치는 영향 또한 커집니다.
```

2022-12-12 13:50 UTC, hochan222 commented on files/ko/web/performance/understanding_latency/index.md
> +연결의 레이턴시가 낮은 경우 요청한 자원은 거의 즉시 보입니다. 레이턴시가 높은 연결의 경우 요청을 보낸 시점과 자원을 받은 시점 사이에 눈에 띄는 지연이 있습니다. 레이턴시는 데이터가 네트워크의 한 지점에서 다른 지점으로 이동하는 속도를 측정하여 얻을 수 있습니다.
```suggestion
대기 시간이 짧은 연결에서는 요청된 자원이 거의 즉시 보입니다. 대기 시간이 긴 연결에서는 요청을 보낸 시점과 자원을 받은 시점 사이에 눈에 띄는 지연이 있습니다. 대기 시간은 데이터가 네트워크의 한 지점에서 다른 지점으로 이동하는 속도를 측정하여 얻을 수 있습니다.
```

2022-12-12 13:50 UTC, hochan222 commented on files/ko/web/performance/understanding_latency/index.md
> +개발자 도구를 사용하여 저대역폭 네트워크 연결로 전환하면 저대역폭 네트워크의 레이턴시를 에뮬레이트할 수 있습니다.
```suggestion
개발자 도구를 사용하여 저대역폭 네트워크 연결로 전환하면 저대역폭 네트워크의 레이턴시를 모방할 수 있습니다.
```

해당 문장뿐만 아니라 본문 전체에서 에뮬레이트 정도면 한글로 변역해도 문제 없다고 생각합니다.

2022-12-12 13:50 UTC, hochan222 commented on files/ko/web/performance/understanding_latency/index.md
> +개발자 도구에서 network 테이블의 스로틀링 옵션을 통해 2G, 3G 혹은 다른 대역폭으로 전환할 수 있습니다. 각 브라우저의 개발자 도구에는 서로 다른 사전 설정 옵션이 있으며, 에뮬레이트되는 특성에는 다운로드 속도, 업로드 속도, 최소 레이턴시 또는 데이터 패킷을 보내는 데 필요한 최소 타입이 포함됩니다. 일부 사전 설정의 대략적인 값은 다음과 같
```suggestion
개발자 도구에서 network 테이블의 스로틀링 옵션을 통해 2G, 3G 혹은 다른 대역폭으로 전환할 수 있습니다. 다양한 브라우저의 개발자 도구에는 서로 다른 사전 설정 옵션이 있으며, 에뮬레이트되는 특성에는 다운로드 속도, 업로드 속도, 최소 레이턴시 또는 데이터 패킷을 보내는 데 필요한 최소 타입이 포함됩니다. 일부 사전 설정의 대략적인 값은 다음과 같습니다.
```

2022-12-16 14:43 UTC, jaeyeong951 commented on files/ko/web/performance/understanding_latency/index.md
> +**레이턴시(Latency)** 란 하나의 데이터 패킷이 출발지에서 도착지까지 가는 데 걸리는 시간을 뜻합니다. 성능 최적화에 있어서 레이턴시의 원인을 없애는 것과 연결이 좋지 않은 사용자를 고려하여 레이턴시가 높은 환경에서 사이트 성능을 테스트하는 것은 중요합니다. 이 글에서 레이턴시가 무엇인지, 레이턴시가 성능에 어떤 영향을 주는지, 이를 어떻게 측정
이 문서를 번역하면서 고민을 제일 많이 했던 부분이 latency라는 단어의 번역유무였는데요, 말씀해주신 것 처럼 영문을 괄호로 따로 표현했으니 '대기 시간'처럼 번역하는게 좋아보입니다. 본문의 단어들도 모두 수정하겠습니다.

2022-12-16 15:04 UTC, jaeyeong951 commented
> [<img alt="@hochan222" width="20" height="20" src="https://avatars.githubusercontent.com/u/22424891?s=40&amp;v=4">](/hochan222)
> ** hochan222 ** requested changes
> ### The mdn:main branch requires linear history
> The base branch does not accept merge commits. Alternate merge methods are preferred. [Learn more about required linear history.](https://docs.github.com/github/administering-a-repository/requiring-a-linear-commit-history)

리뷰 반영해서 브랜치 업데이트했습니다. 세심한 리뷰 감사합니다!

2022-12-17 00:15 UTC, hochan222 approved these changes
고생 많으셨습니다! 좋은 주말 보내세요 :)

2022-12-17 00:16 UTC, merged