replace `@api/deki` reference ko
mdn/translated-content pull request #10507
Opened 2022-12-06 08:07 UTC by notJoon

### Description

replace `@api/deki` in ko documents

### Additional details

Some of the documents are completely different from other languages, so I changed `@api/deki`  for now. I'll make this as an issue later.

For your information, I'll leave a document that is problematic:
1. Does not match documents in other languages
- https://developer.mozilla.org/ko/docs/Web/CSS/float
- https://developer.mozilla.org/ko/docs/Web/CSS/image-rendering
- https://developer.mozilla.org/ko/docs/Web/CSS/Visual_formatting_model
- https://developer.mozilla.org/Learn/CSS/Howto/Generated_content
- https://developer.mozilla.org/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

2. Missing some paragraph
- https://developer.mozilla.org/ko/docs/Web/SVG/Tutorial/Paths

3. Untranslated
- https://developer.mozilla.org/ko/docs/Learn/CSS/Howto/Generated_content
- https://developer.mozilla.org/ko/docs/Web/CSS/CSS_Positioning/Understanding_z_index/Stacking_context_example_1
- https://developer.mozilla.org/ko/docs/Web/CSS/CSS_Positioning/Understanding_z_index/Stacking_context_example_3
- https://developer.mozilla.org/ko/docs/Web/SVG/Tutorial/Basic_Shapes

### Related issues and pull requests
 Issue #10487

2022-12-12 14:06 UTC, hochan222 requested changes
@notJoon 님 안녕하세요

넘넘 고생 많으셨습니다. 하기 사항 반영해주시면 바로 머지 드리겠습니다.

좋은 하루 보내세요 :)

---

+ 충돌 처리도 부탁드립니다!

2022-12-12 14:06 UTC, hochan222 commented on files/ko/web/api/css_object_model/determining_the_dimensions_of_elements/index.md
> +표시된 컨텐트의 너비, 스크롤바, 패딩까지 포함해서 엘리먼트가 차지하는 전체 공간을 알고 싶다면, [`offsetWidth`](/en-US/docs/Web/API/HTMLElement/offsetWidth)와 `offsetHeight 속성을 사용하세요:`
```suggestion
표시된 컨텐트의 너비, 스크롤바, 패딩까지 포함해서 엘리먼트가 차지하는 전체 공간을 알고 싶다면, [`offsetWidth`](/ko/docs/Web/API/HTMLElement/offsetWidth)와 `offsetHeight 속성을 사용하세요:`
```

2022-12-12 14:06 UTC, hochan222 commented on files/ko/web/api/css_object_model/determining_the_dimensions_of_elements/index.md
> +패딩은 포함하되 경계선, 여백, 스크롤바는 포함시키지 않고 보이는 컨텐트가 실제로 차지하는 공간이 알고 싶다면, [`clientWidth`](/en-US/docs/Web/API/Element/clientWidth)와 [`clientHeight`](/en-US/docs/Web/API/Element/clientHeight) 속성을 사용하세요:
```suggestion
패딩은 포함하되 경계선, 여백, 스크롤바는 포함시키지 않고 보이는 컨텐트가 실제로 차지하는 공간이 알고 싶다면, [`clientWidth`](/ko/docs/Web/API/Element/clientWidth)와 [`clientHeight`](/ko/docs/Web/API/Element/clientHeight) 속성을 사용하세요:
```

2022-12-12 14:06 UTC, hochan222 commented on files/ko/web/api/css_object_model/determining_the_dimensions_of_elements/index.md
> +컨텐트의 실제 크기를 알고 싶다면(보여지는 부분만이 아닌 전체 컨텐트 크기), [`scrollWidth`](/en-US/docs/Web/API/Element/scrollWidth)와 [`scrollHeight`](/en-US/docs/Web/API/Element/scrollHeight) 속성을 사용하세요. 이 속성들은 엘리먼트 컨텐트의 전체 크기에 해당하
```suggestion
컨텐트의 실제 크기를 알고 싶다면(보여지는 부분만이 아닌 전체 컨텐트 크기), [`scrollWidth`](/ko/docs/Web/API/Element/scrollWidth)와 [`scrollHeight`](/ko/docs/Web/API/Element/scrollHeight) 속성을 사용하세요. 이 속성들은 엘리먼트 컨텐트의 전체 크기에 해당하는 너비와 높이를 반환합니다. 보여지는 영역이 작아서 스크롤바를 사용하고 있다해도 관계없습니다.
```

2022-12-12 14:06 UTC, hochan222 commented on files/ko/web/css/css_positioning/understanding_z_index/stacking_and_float/index.md
> +- [Adding z-index](/en-US/CSS/Understanding_z-index/Adding_z-index) : Using z-index to change default stacking
```suggestion
- [Adding z-index](/ko/CSS/Understanding_z-index/Adding_z-index) : Using z-index to change default stacking
```

2022-12-12 14:06 UTC, hochan222 commented on files/ko/web/css/css_positioning/understanding_z_index/stacking_and_float/index.md
> +- [Stacking context example 1](/en-US/CSS/Understanding_z-index/Stacking_context_example_1) : 2-level HTML hierarchy, z-index on the last level
```suggestion
- [Stacking context example 1](/ko/CSS/Understanding_z-index/Stacking_context_example_1) : 2-level HTML hierarchy, z-index on the last level
```

2022-12-12 14:06 UTC, hochan222 commented on files/ko/web/css/css_positioning/understanding_z_index/stacking_and_float/index.md
> +- [Stacking context example 2](/en-US/CSS/Understanding_z-index/Stacking_context_example_2) : 2-level HTML hierarchy, z-index on all levels
```suggestion
- [Stacking context example 2](/ko/CSS/Understanding_z-index/Stacking_context_example_2) : 2-level HTML hierarchy, z-index on all levels
```

2022-12-12 14:06 UTC, hochan222 commented on files/ko/web/css/css_positioning/understanding_z_index/stacking_and_float/index.md
> +- [Stacking context example 3](/en-US/CSS/Understanding_z-index/Stacking_context_example_3) : 3-level HTML hierarchy, z-index on the second level
```suggestion
- [Stacking context example 3](/ko/CSS/Understanding_z-index/Stacking_context_example_3) : 3-level HTML hierarchy, z-index on the second level
```

2022-12-12 14:06 UTC, hochan222 commented on files/ko/web/guide/html/content_categories/index.md
> +[![다양한 내용 범주가 상호 작용하는 방식을 보여주는 벤다이어그램입니다. 다음 절에서는 이러한 관계를 텍스트로 설명합니다.](content_categories_venn.png)](/en-US/docs/Web/Guide/HTML/Content_categories/content_categories_venn.png)
```suggestion
[![다양한 내용 범주가 상호 작용하는 방식을 보여주는 벤다이어그램입니다. 다음 절에서는 이러한 관계를 텍스트로 설명합니다.](content_categories_venn.png)](/ko/docs/Web/Guide/HTML/Content_categories/content_categories_venn.png)
```

2022-12-12 14:06 UTC, hochan222 commented on files/ko/web/svg/tutorial/basic_shapes/index.md
> +[패스](/en-US/Web/SVG/Element/path)는 아마 SVG에서 사용할 수 있는 가장 일반적인 형태일 것이다. path 요소를 사용해서 당신은 사각형(둥근 모서리가 있거나 없는), 원, 타원, 폴리라인 및 다각형을 그릴 수 있다. 기본적으로 다른 모든 종류의 모양, 베지에 곡선, 2차원 곡선 등이 가능하다. 그러한 이유로, paths 는 튜
```suggestion
[패스](/ko/Web/SVG/Element/path)는 아마 SVG에서 사용할 수 있는 가장 일반적인 형태일 것이다. path 요소를 사용해서 당신은 사각형(둥근 모서리가 있거나 없는), 원, 타원, 폴리라인 및 다각형을 그릴 수 있다. 기본적으로 다른 모든 종류의 모양, 베지에 곡선, 2차원 곡선 등이 가능하다. 그러한 이유로, paths 는 튜토리얼의 [the next section](/en-US/Web/SVG/Tutorial/Paths) 에 들어가지만, 지금은 모양을 제어하는 데 사용되는 단일 속성이 있음을 알려주겠다.
```

2022-12-12 14:06 UTC, hochan222 commented on files/ko/web/svg/tutorial/getting_started/index.md
> +- SVG에서 크기와 단위를 처리하는 방법에 대해서는 [다음 페이지](/en-US/docs/Web/SVG/Tutorial/Positions)에서 설명 할 것입니다.
```suggestion
- SVG에서 크기와 단위를 처리하는 방법에 대해서는 [다음 페이지](/ko/docs/Web/SVG/Tutorial/Positions)에서 설명 할 것입니다.
```

2022-12-16 05:47 UTC, notJoon commented
> @notJoon 님 충돌해결도 같이 부탁드립니다~!
> 
>     * [replace `@api/deki` reference ko #10507 (comment)](https://github.com/mdn/translated-content/pull/10507#issuecomment-1343087664)
얼마전부터 충돌 해결하려고 시도는 했는데 브랜치가 맛이 가서 꽤 꼬였습니다. 최대한 빨리 처리해볼께요

2022-12-16 06:12 UTC, notJoon commented
@hochan222 
번거롭게 해드려 죄송합니다. 브랜치가 상당히 꼬여있어서 쳐내느라 꽤 오래걸렸습니다. 충돌난 부분은 전부 처리했지만, `content_categories`는 빈 파일이라고 린트 에러가 떠서 다시 작성해서 넣어놨습니다. 감사합니다.

2022-12-17 00:17 UTC, hochan222 approved these changes
넘넘 고생 많으셨습니다. 좋은 주말 보내세요 :)

2022-12-17 00:17 UTC, merged