add missing links and update image refs KO
mdn/translated-content pull request #10607
Opened 2022-12-11 13:55 UTC by notJoon

### Description
 
CSS building blocks의 문서에서 누락된 링크를 추가했고 이미지 경로들을 수정했습니다.

2022-12-12 17:26 UTC, hochan222 approved these changes
@notJoon 님 안녕하세요.

en-us 경로는 yari (mdn 서버)에서 자동으로 경로가 수정되어서 ko로 변경 부탁드립니다.

고생 많으셨습니다. 좋은 하루 보내세요 :)

2022-12-12 17:26 UTC, hochan222 commented on files/ko/learn/css/building_blocks/values_and_units/index.md
> +| [`<dimension>`](/en-US/docs/Web/CSS/dimension) | `<dimension>` 은 예를 들어 `45deg`, `5s` 또는 `10px`. 과 같은 단위가 붙어있는 `<number>` 입니다. `<dimension>` 은 [`<length>`](/en-US/docs/Web/CSS/length), [`<angle>`](/
```suggestion
| [`<dimension>`](/ko/docs/Web/CSS/dimension) | `<dimension>` 은 예를 들어 `45deg`, `5s` 또는 `10px`. 과 같은 단위가 붙어있는 `<number>` 입니다. `<dimension>` 은 [`<length>`](/ko/docs/Web/CSS/length), [`<angle>`](/ko/docs/Web/CSS/angle), [`<time>`](/ko/docs/Web/CSS/time) 및 [`<resolution>`](/ko/docs/Web/CSS/resolution) 의 종류를 포함하는 카테고리입니다[.](/ko/docs/Web/CSS/resolution) |
```

2022-12-12 17:26 UTC, hochan222 requested changes
.

2022-12-12 19:11 UTC, notJoon commented
@hochan222 수정 완료했습니다! yari에서 변환되는줄 모르고 괜히 번거롭게 한거 같네요. 꼼꼼한 리뷰 항상 감사드리고 좋은 하루 되세요!

2022-12-13 02:12 UTC, hochan222 approved these changes

2022-12-13 02:13 UTC, hochan222 commented
번거로우실 수 있는데 빠른 수정 감사합니다. 좋은 하루 보내세요 :)

2022-12-13 02:13 UTC, merged