JavaScript: Logical AND(&&) 연산자 신규 작성
mdn/translated-content pull request #10655
Opened 2022-12-14 23:40 UTC by wisedog

JavaScript Reference Logical AND(&&) 연산자 신규 작성

2023-01-07 03:31 UTC, hochan222 requested changes
@wisedog 님 안녕하세요.

몇가지 리뷰 사항 하기에 남겨두었습니다.

기여해주셔서 감사합니다. 좋은 하루 보내세요 :)

2023-01-07 03:31 UTC, hochan222 commented on files/ko/web/javascript/reference/operators/logical_and/index.md
> +
```suggestion
```

원본은 개행이 존재하지 않습니다!

<img width="350" alt="image" src="https://user-images.githubusercontent.com/22424891/211128845-b6354153-7e03-4ce6-9fcd-100d3c4b504e.png">

2023-01-07 03:31 UTC, hochan222 commented on files/ko/web/javascript/reference/operators/logical_and/index.md
> +보다 일반적으로 왼쪽에서 오른쪽으로 평가할 때 연산자는 처음으로 만나는 {{Glossary("falsy", "거짓 같은 값")}} 피연산자의
```suggestion
보다 일반적으로 왼쪽에서 오른쪽으로 평가할 때 연산자는 처음으로 만나는 {{Glossary("falsy", "거짓 같은")}} 피연산자의 값을 반환합니다. 혹은 모두 {{Glossary("truthy", "참 같은 값")}}이라면 마지막 피연산자의 값을 반환합니다.
```

1. 23 Line과 동일하게 '거짓 같은 피연산자의 값'으로 통일 시켜주는 것이 좋아 보입니다.
2. '보다' 부터 개행이 되었는데 개행을 하신 이유가 있으신가요?

2023-01-07 03:31 UTC, hochan222 commented on files/ko/web/javascript/reference/operators/logical_and/index.md
> +값을 반환합니다. 혹은 모두 {{Glossary("truthy", "참 같은 값")}}이라면 마지막 피연산자의 값을 반환합니다.
```suggestion
```

2023-01-07 03:31 UTC, hochan222 commented on files/ko/web/javascript/reference/operators/logical_and/index.md
> +보다 일반적으로 왼쪽에서 오른쪽으로 평가할 때 연산자는 처음으로 만나는 {{Glossary("falsy", "거짓 같은 값")}} 피연산자의
오랜 기간을 두고 '거짓 같은', '거짓 같은 값' 외에 어떻게 표현하면 좋을까 고민해보았는데, 지금이 가장 좋은 표현인것같습니다. Glossary로 감싸져있으니 괜찮아 보이네요!

2023-01-07 03:31 UTC, hochan222 commented on files/ko/web/javascript/reference/operators/logical_and/index.md
> +{{Glossary("falsy", "거짓같은 값")}}으로 평가되기 때문에 **절대 평가되지 않습니다**.
```suggestion
첫 번째 피연산자 `(some falsy expression)`은 {{Glossary("falsy", "거짓 같은 값")}}으로 평가되기 때문에, `expr` 부분은 **절대 평가되지 않습니다**.
```

'평가되기 때문에'와 '절대 평가되지 않습니다' 가 연속적으로 번역되어서 가독성이 떨어져서, "`expr` 부분은"을 사이에 넣어주었습니다.

2023-01-07 13:58 UTC, wisedog commented on files/ko/web/javascript/reference/operators/logical_and/index.md
> +보다 일반적으로 왼쪽에서 오른쪽으로 평가할 때 연산자는 처음으로 만나는 {{Glossary("falsy", "거짓 같은 값")}} 피연산자의
거짓/참은 호찬님 말씀이 좋아보입니다. 
md 파일 작성에는 가능하면 80자 기준으로 개행하라고 해서요 : >

2023-01-08 02:39 UTC, hochan222 approved these changes
LGTM 좋은 하루 보내세요 :)

2023-01-08 02:40 UTC, merged