JavaScript: Map 신규 작성
mdn/translated-content pull request #10672
Opened 2022-12-16 23:21 UTC by wisedog

### Description

`Map` 신규 작성

### Motivation

`Map`은 Global Object 중에서 꽤 비중있는 친구인데, 아직까지 번역이 안되서 꽤 오랜 시간동안 번역했습니다. 
(하다말다하다말다해서...)
`Map`의 메서드인 `set`, `clear` 등은 이 PR 이 머지된 후 작업할 예정입니다.

2022-12-16 23:27 UTC, wisedog commented
하위 메서드 번역이 안되서 Flaw 가 좀 많습니다. 참고하시기 바랍니다.

2023-01-07 06:54 UTC, yechoi42 requested changes
안녕하세요 @wisedog 님! 리뷰가 늦어져서 죄송하며 긴 글 번역해주셔서 감사합니다. 몇가지 코멘트를 남겨두었습니다. 확인 부탁드립니다!

2023-01-07 06:54 UTC, yechoi42 commented on files/ko/web/javascript/reference/global_objects/map/index.md
> +`map()`의 명세는 "평균적으로 집합 내 요소의 수에 따라 하위 선형인 접근 시간을 제공하는" 맵을 구현해야 한다고 기술되어 있습니다.
```suggestion
`Map`의 명세는 "평균적으로 집합 내 요소의 수에 따라 하위 선형인 접근 시간을 제공하는" 맵을 구현해야 한다고 기술되어 있습니다.
```
단순 maps 라고 되어있어서 생성자가 아닌 Map으로 표현하는 것이 어떨지 제안드려봅니다.

2023-01-07 06:54 UTC, yechoi42 commented on files/ko/web/javascript/reference/global_objects/map/index.md
> +값 동일성은 [`sameValueZero`](/ko/docs/Web/JavaScript/Equality_comparisons_and_sameness#same-value-zero_equality)을
```suggestion
값 동일성은 [`SameValueZero`](/ko/docs/Web/JavaScript/Equality_comparisons_and_sameness#same-value-zero_equality)을
```

2023-01-07 06:54 UTC, yechoi42 commented on files/ko/web/javascript/reference/global_objects/map/index.md
> +    </tr>
Security 칼럼도 추가해주세요~!

2023-01-07 06:54 UTC, yechoi42 commented on files/ko/web/javascript/reference/global_objects/map/index.md
> +          {{jsxref("Object.getOwnPropertySymbols")}}은 <code>Symbol</code>-키 속성에 대해 동일합니다.
```suggestion
          {{jsxref("Object.getOwnPropertySymbols")}}은 <code>Symbol</code>-키 속성에 대해 동일합니다.)
```

2023-01-07 07:40 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/map/index.md
> +`map()`의 명세는 "평균적으로 집합 내 요소의 수에 따라 하위 선형인 접근 시간을 제공하는" 맵을 구현해야 한다고 기술되어 있습니다.
오.. 왜 이렇게 했는지 모르겠군요. 말씀하신게 타당합니다.

2023-01-07 07:41 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/map/index.md
> +    </tr>
흑흑 그 새 추가되었군요...

2023-01-07 11:10 UTC, yechoi42 approved these changes
감사합니다~~!

2023-01-07 11:10 UTC, merged