fix: correct description of `[attr~=value]`
mdn/translated-content pull request #10726
Opened 2022-12-20 10:25 UTC by higamaya

### Description

Corrected description of `[attr~=value]`.

### Motivation

The original description misleadingly stated that the `value` in the selector could be a whitespace-separated list of words.

Actually, I understood it like that and implemented CSS, but it didn't work as expected and I was troubled for a while.
After that, I read the description written in English and realized that I had misunderstood.

### Additional details

### Related issues and pull requests

2022-12-20 14:30 UTC, mfuji09 requested changes
1件の修正をお願いします。
なお、日本語版記事に対するプルリクエストは日本人しか見ませんので、日本語でどうぞ。

2022-12-20 14:30 UTC, mfuji09 commented on files/ja/web/css/attribute_selectors/index.md
> +  - : _attr_ という名前の属性の値が空白区切りの語のリストであり、その内の1つが正確に _value_ と一致する要素を表します。
英数字と日本語の間には、1文字の半角空白を置くようにしてください。

```suggestion
  - : _attr_ という名前の属性の値が空白区切りの語のリストであり、その内の 1 つが正確に _value_ と一致する要素を表します。
```

2022-12-21 00:35 UTC, higamaya commented on files/ja/web/css/attribute_selectors/index.md
> +  - : _attr_ という名前の属性の値が空白区切りの語のリストであり、その内の1つが正確に _value_ と一致する要素を表します。
レビュー有難うございます。
修正しました。

2022-12-22 03:48 UTC, mfuji09 approved these changes
OKです。

2022-12-22 14:22 UTC, merged