zh-cn(update): sync numberformat for the English
mdn/translated-content pull request #10728
Opened 2022-12-20 13:58 UTC by fwqaaq

* part of  #3893

2022-12-20 13:59 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +**`Intl.NumberFormat`** 对象使语言敏感的数字格式化。
```suggestion
**`Intl.NumberFormat`** 对象使语言敏感的数字能够格式化。
```

2022-12-21 01:51 UTC, yin1999 requested changes

2022-12-21 01:51 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +**`Intl.NumberFormat`** 对象使语言敏感的数字能够格式化。
not right

2022-12-21 01:51 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +<!-- 此交互式示例的源代码存储在 GitHub 存储库中。如果你想为交互式示例项目做出贡献，请克隆 https://github.com/mdn/interactive-examples 并向我们发送拉取请求。 -->
please remove the hidden notes. We are not adding this anymore. If you like, please also remove this from mdn/content.

2022-12-21 01:51 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +  - : 返回一个数组，其包含着那些被提供的受支持的地区（local），而运行时的默认的地区不会回落到该数组。
locale, and the translation is not right, this means `区域`

2022-12-21 01:51 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +  - : 返回一个对象{{jsxref("Array","数组")}}，表示可以用于自定义区域设置感知格式的部分数字字符串。
removing code wrapping

```suggestion
  - : 返回一个对象{{jsxref("Array","数组", "", 1)}}，表示可以用于自定义区域设置感知格式的部分数字字符串。
```

2022-12-21 01:51 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +### 使用地区（locale）
see above, just `### 使用 locales`, this is a param's name.

2022-12-21 01:51 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +### 使用可选的对象
see above

2022-12-21 02:09 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +**`Intl.NumberFormat`** 对象使语言敏感的数字能够格式化。
🤔

2022-12-24 02:13 UTC, yin1999 requested changes

2022-12-24 02:13 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +**`Intl.NumberFormat`** 对象能使语言敏感的数字格式化。
“语言敏感的数字”是不正确的，1 2 3 4 5...何来语言敏感一说。可以参考其它的翻译：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

2022-12-24 02:13 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +// '3,500' if in US English locale
原有的示例是有翻译的

2022-12-24 02:13 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +// 123.456,789
同上一处

2022-12-24 02:13 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +// 16 litres
同上一处

2022-12-24 02:36 UTC, fwqaaq commented
最近好像得新冠，等我好了再修

2022-12-24 02:37 UTC, yin1999 commented
> 最近好像得新冠，等我好了再修

注意身体，好好休息 🙏

2022-12-25 08:47 UTC, yin1999 requested changes

2022-12-25 08:47 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +  - : 返回一个数组，其包含着那些被提供的受支持的区域（local），而运行时的默认的区域不会回落到该数组。
最后的短句可以考虑一下有没有更好的翻译，当然现在已经是正确的了

2022-12-25 08:47 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +  - : 返回一个对象{{jsxref("Array", "数组", "", 1)}}，表示可以用于自定义区域设置感知格式的部分数字字符串。
翻译得不太对，可以参考这里的示例 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatToParts

2022-12-25 08:47 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +  - : getter 函数，根据调用该方法的 {{jsxref("Intl.NumberFormat")}} 对象的区域设置和格式化选项格式化一系列数字。
不对，range在这里指范围（`1~2` `一到二` `10至11` 这叫范围），对于不确定的可以区看一下方法的文档。

2022-12-25 08:47 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +  - : 返回一个对象{{jsxref("Array", "数组", "", 1)}}，表示可以用于自定义区域设置感知格式的部分数字字符串范围。
同

2022-12-25 08:47 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +### 基本使用
```suggestion
### 基础用例
```

2022-12-25 08:47 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +在不指定区域设置的基本使用中，返回默认区域设置中的格式化字符串和默认选项。
基础用例，且后半句话翻译得怪怪的，好好修改一下

2022-12-25 08:47 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +此示例展示了本地数字格式化的一些变化。未来得到用户应用接口使用的语言格式，请确保使用 `locales` 参数指定该语言（可能还有一些备选语言）：
“未来”——in order to

2022-12-25 08:47 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
>  ### 可用的选项
与上一处小标题保持一致

2022-12-26 04:17 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
>  ### 可用的选项
```suggestion
### 使用 options
```

2022-12-26 04:17 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +此示例展示了本地数字格式化的一些变化。未来得到用户应用接口使用的语言格式，请确保使用 `locales` 参数指定该语言（可能还有一些备选语言）：
```suggestion
此示例展示了本地数字格式化的一些变化。为了得到用户应用接口使用的语言格式，请确保使用 `locales` 参数指定该语言（可能还有一些备选语言）：
```

2022-12-26 04:17 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +// '3,500' if in US English locale
```suggestion
// 如果在美国英语地区 → '3,500'
```

2022-12-26 04:17 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +在不指定区域设置的基本使用中，返回默认区域设置中的格式化字符串和默认选项。
```suggestion
在不指定区域设置的基本用例中，返回默认区域和默认选项中的格式化字符串。
```

2022-12-26 04:18 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +  - : getter 函数，根据调用该方法的 {{jsxref("Intl.NumberFormat")}} 对象的区域设置和格式化选项格式化一系列数字。
```suggestion
  - : getter 函数，根据调用该方法的 {{jsxref("Intl.NumberFormat")}} 对象的区域设置和格式化选项格式化一个范围数字。
```

2022-12-26 04:19 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +  - : 返回一个对象{{jsxref("Array", "数组", "", 1)}}，表示可以用于自定义区域设置感知格式的部分数字字符串。
```suggestion
  - : 返回一个对象{{jsxref("Array", "数组", "", 1)}}，表示可以用于自定义区域感知格式化部分的数字字符串。
```

2022-12-26 04:23 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +  - : 返回一个对象{{jsxref("Array", "数组", "", 1)}}，表示可以用于自定义区域设置感知格式的部分数字字符串范围。
```suggestion
  - : 返回一个对象{{jsxref("Array", "数组", "", 1)}}，表示可以用自定义区域设置感知格式化部分的数字字符串范围。
```

2022-12-26 04:35 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +  - : 返回一个数组，其包含着那些被提供的受支持的区域（local），而运行时的默认的区域不会回落到该数组。
```suggestion
  - : 返回一个数组，其包含着那些被提供的受支持的区域（local），而运行时的默认的区域不会出现在该数组。
```

2022-12-26 07:03 UTC, yin1999 commented
还是不太对，等病好了再好好修改

2022-12-26 11:21 UTC, fwqaaq commented
> 还是不太对，等病好了再好好修改

差不多了，我再改一改😭

2022-12-29 13:27 UTC, jasonren0403 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +  - : 返回一个数组，其包含着那些被提供的受支持的区域（local），而运行时的默认的区域不会回落到该数组。
> 

区域应该是locale

2022-12-30 11:05 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +  - : 返回一个对象{{jsxref("Array", "数组", "", 1)}}，表示可以用于自定义区域设置感知格式的部分数字字符串。
现在应该差不多，看了一下 formattoparts 差不多这个意思😭

2022-12-30 12:15 UTC, yin1999 requested changes

2022-12-30 12:15 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +- {{jsxref("Intl/NumberFormat/formatRangeToParts", "Intl.NumberFormat.prototype.formatRangeToParts()")}} {{experimental_inline}}
```suggestion
- {{jsxref("Intl/NumberFormat/formatRangeToParts", "Intl.NumberFormat.prototype.formatRangeToParts()")}}
```

2022-12-30 12:15 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +- {{jsxref("Intl/NumberFormat/formatRange", "Intl.NumberFormat.prototype.formatRange()")}} {{experimental_inline}}
```suggestion
- {{jsxref("Intl/NumberFormat/formatRange", "Intl.NumberFormat.prototype.formatRange()")}}
```

2022-12-30 12:15 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +  - : 返回一个对象{{jsxref("Array", "数组", "", 1)}}，表示可以用于自定义区域设置感知格式的部分数字字符串范围。
"数字字符串的范围" -> "数字范围的字符串"，后半句也再修改一下，可参考 #10819

2022-12-30 12:15 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +  - : 返回一个新对象，其属性反映了对象对象初始化期间计算的区域设置和排序选项。
参考：#10819

2022-12-30 12:15 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +const number = 123456.789;
下面的示例代码部分与英文的保持一致，把箭头去掉

2022-12-30 12:15 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
>  // → 1,23,000
```suggestion
// 1,23,000
```

2022-12-30 12:28 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +  - : 返回一个新对象，其属性反映了对象对象初始化期间计算的区域设置和排序选项。
```suggestion
  - : 返回一个新对象，其属性能够反映相应对象在初始化时计算所得的区域和格式化选项。
```

2022-12-30 12:46 UTC, yin1999 approved these changes
Thanks

2022-12-30 12:46 UTC, merged