Create index.md & translate async scripts page from EN to FR
mdn/translated-content pull request #10738
Opened 2022-12-20 16:54 UTC by gregWDumont

### Description

I created the French translation of the async scripts page which was only available in [English](https://developer.mozilla.org/en-US/docs/Games/Techniques/Async_scripts). 

### Motivation

Helping the community while learning. 

### Additional details

### Related issues and pull requests

2022-12-20 19:43 UTC, tristantheb commented
@gregWDumont Les erreurs pour les espaces sont corrigés, cependant, le cheminement vers cette page ne correspond pas en terme de dossier.

Il faut que le index.md suive le chemin suivant : `/files/fr/games/techniques/async_scripts/index.md`, actuellement il n'y a pas de dossier "techniques" dans le commit présenté, ça ne passera pas lors des vérifications ;)

2022-12-20 19:49 UTC, tristantheb commented
Et du coup pour l'explication de l'erreur : 

En Anglais, il n'y a pas d'espace après un mot quand on écrit un « : » ou un « ? », mais un Français, nous avons un espace insécable. Et la sécurité des requête veut qu'on écrive la valeur HTML de l'espace insécable et non un espace sécable donc le fameux `&nbsp;` « Non Breackable Space »

Voilà voilà :D En espérant que ça t'aide pour tes prochaines requêtes ;)

2022-12-20 20:08 UTC, gregWDumont commented
Salut. Merci beaucoup pour la réponse détaillée. J'apprends beaucoup en faisant ces traductions et pas forcément sur le sujet en question. Je rectifie cela fissa et j'envoie le PR.

2023-01-03 12:19 UTC, SphinxKnight requested changes
Merci @gregWDumont pour cette traduction et mes excuses pour la revue tardive. J'ai apporté quelques commentaires. N'hésitez pas s'il y a des questions ou besoin d'en discuter :)

2023-01-03 12:19 UTC, SphinxKnight commented on files/fr/games/techniques/async_scripts/index.md
> +  - async
```suggestion
slug: Games/Techniques/Async_scripts
l10n:
  sourceCommit: f3ef176745e4875e42584df143fba15a63c7ad32
```
Les tags sont inutiles en français :) 
Pour le suivi des traductions entre l'anglais et le français, nous ajoutons une métadonnée qui correspond au commit du dépôt anglophone qui décrit l'état/le timestamp git auquel correspond la traduction (ici je suis parti du principe que c'était la dernière version anglaise qui était traduite :))

2023-01-03 12:19 UTC, SphinxKnight commented on files/fr/games/techniques/async_scripts/index.md
> +Chaque jeu moyen ou volumineux doit compiler le code [asm.js](/en-US/docs/Games/Tools/asm.js) dans le cadre d'un script asynchrone afin de donner au navigateur le maximum de flexibilité pour optimise
```suggestion
Chaque jeu moyen ou volumineux doit compiler le code [asm.js](/fr/docs/Games/Tools/asm.js) dans le cadre d'un script asynchrone afin de donner au navigateur le maximum de flexibilité pour optimiser le processus de compilation.
```

2023-01-03 12:19 UTC, SphinxKnight commented on files/fr/games/techniques/async_scripts/index.md
> +Dans Gecko, la compilation asynchrone permet au moteur JavaScript de compiler l'asm.js du fil d'exécution principal lors du chargement du jeu et de mettre en cache le code machine généré afin que le
```suggestion
Dans Gecko, la compilation asynchrone permet au moteur JavaScript de compiler l'asm.js en dehors du fil d'exécution principal lors du chargement du jeu et de mettre en cache le code machine généré afin que le jeu n'ait pas besoin d'être compilé lors des chargements suivants (à partir de Firefox 28) . Pour voir la différence, basculez `javascript.options.parallel_parsing` dans `about:config`.
```

2023-01-03 12:19 UTC, SphinxKnight commented on files/fr/games/techniques/async_scripts/index.md
> +Obtenir une compilation asynchrone est facile&nbsp;: lors de l'écriture de votre JavaScript, utilisez simplement l'attribut "async" comme suit&nbsp;:
```suggestion
Obtenir une compilation asynchrone est facile&nbsp;: lors de l'écriture de votre JavaScript, utilisez simplement l'attribut `async` comme suit&nbsp;:
```

2023-01-03 12:19 UTC, SphinxKnight commented on files/fr/games/techniques/async_scripts/index.md
> +## Mettre l'asynchrone en action
```suggestion
## Passer à la compilation asynchrone
```

Peut être plus "fluide" que la formule tirée de l'anglais.

2023-01-03 12:19 UTC, SphinxKnight commented on files/fr/games/techniques/async_scripts/index.md
> +(Les scripts créés à partir du script par défaut sont `async`.) Le shell HTML par défaut généré par Emscripten produit ce dernier.
Je ne suis pas sûr de comprendre, mais je ne suis pas sûr de comprendre la version anglaise non plus :x

2023-01-03 12:19 UTC, SphinxKnight commented on files/fr/games/techniques/async_scripts/index.md
> +## Quand l'async n'est-il pas asynchrone&nbsp;?
```suggestion
## Attention aux `async` en réalité synchrones
```
Une tentative de reformulation pour éviter l'utilisation de "async" sans indication de code (backticks)

2023-01-03 12:19 UTC, SphinxKnight commented on files/fr/games/techniques/async_scripts/index.md
> +Deux situations courantes dans lesquelles un script n'est \*pas\* asynchrone (comme [défini par la spécification HTML](https://html.spec.whatwg.org/multipage/scripting.html)) sont&nbsp;:
```suggestion
Il existe deux situations courantes où un script n'est \*pas\* asynchrone malgré l'utilisation d'`async` ou du chargement d'un script (voir [la spécification HTML à ce sujet](https://html.spec.whatwg.org/multipage/scripting.html))&nbsp;:
```

2023-01-03 12:19 UTC, SphinxKnight commented on files/fr/games/techniques/async_scripts/index.md
> +Les deux sont comptés comme des scripts "en ligne" et sont compilés puis exécutés immédiatement.
```suggestion
Les deux sont comptés comme des scripts «&nbsp;en ligne&nbsp;»  (<i lang="en">inline</i>) et sont compilés puis exécutés immédiatement.
```

2023-01-03 12:19 UTC, SphinxKnight commented on files/fr/games/techniques/async_scripts/index.md
> +Que faire si votre code est dans une chaîne JS&nbsp;? Au lieu d'utiliser `eval` ou `innerHTML`, qui déclenchent tous deux une compilation synchrone, vous devez utiliser un Blob avec une URL d'objet&n
```suggestion
Que faire si votre code est dans une chaîne de caractères JavaScript&nbsp;? Au lieu d'utiliser `eval()` ou `textContent`, qui déclenchent tous deux une compilation synchrone, privilégiez un blob avec une URL d'objet&nbsp;:
```

2023-01-03 12:19 UTC, SphinxKnight commented on files/fr/games/techniques/async_scripts/index.md
> +Le réglage de `src` plutôt que `innerHTML` est ce qui rend ce script asynchrone.
```suggestion
Dans ce dernier exemple, c'est l'utilisation de `src` plutôt que de `innerHTML` qui rend le chargement du script asynchrone.
```

2023-01-03 12:23 UTC, SphinxKnight requested changes
J'avais oublié le titre :)

2023-01-03 12:23 UTC, SphinxKnight commented on files/fr/games/techniques/async_scripts/index.md
> +title: Async scripts for asm.js
```suggestion
title: Script asynchrones pour asm.js
```

2023-01-03 13:16 UTC, gregWDumont commented on files/fr/games/techniques/async_scripts/index.md
> +## Quand l'async n'est-il pas asynchrone&nbsp;?
Je n'étais pas le plus à l'aise avec certaines formulations. Tes modifications me semblent plus lisibles en effet.

2023-01-03 13:18 UTC, gregWDumont commented on files/fr/games/techniques/async_scripts/index.md
> +(Les scripts créés à partir du script par défaut sont `async`.) Le shell HTML par défaut généré par Emscripten produit ce dernier.
Je t'avoue ne pas avoir été le plus à l'aise avec cette traduction non plus.

2023-01-03 13:21 UTC, gregWDumont reviewed
Je crois avoir inclus toutes les demandes de modifications sauf erreur de ma part !?

2023-01-03 13:47 UTC, SphinxKnight commented
désolé j'avais ajouté un espace en trop là aussi :( (d'où l'échec de markdownlint)

2023-01-04 07:01 UTC, SphinxKnight approved these changes

2023-01-04 07:01 UTC, merged

2023-01-04 07:01 UTC, SphinxKnight commented
Merci @gregWDumont : )