Fix typo, try to make it more readable, add &nbsp;
mdn/translated-content pull request #10740
Opened 2022-12-21 10:51 UTC by gregWDumont

### Description

Fix typo, try to make it more readable, add &nbsp;

### Motivation

Learning by helping.

### Additional details

### Related issues and pull requests

2022-12-21 12:34 UTC, gregWDumont commented
Hello,
Should I change the location of the file within the repo? I have only made minor modifications so far.

2022-12-22 19:04 UTC, cw118 requested changes
Merci pour cette PR @gregWDumont ! Quelques légers ajustements, le reste est bon pour moi :)

2022-12-22 19:04 UTC, cw118 commented on files/fr/web/api/fetch_api/using_fetch/index.md
> +Les Requêtes et Réponses (et par extension la fonction `fetch()`), vont tenter de déterminer le type de contenu. Une requête va automatiquement définir un en-tête `Content-Type`  si rien n'est défini
```suggestion
Les requêtes et réponses (et par extension la fonction `fetch()`), vont tenter de déterminer le type de contenu. Une requête va automatiquement définir un en-tête `Content-Type` si rien n'est défini dans le dictionnaire \[NDLT&nbsp;: configuration d'initialisation].
```

2022-12-23 10:17 UTC, gregWDumont commented on files/fr/web/api/fetch_api/using_fetch/index.md
> +Toutes les méthodes d'en-tête provoquent une erreur TypeError si un nom d’en-tête utilisé n'est pas un nom d’en-tête HTTP valide. Les opérations de mutation vont provoquer une erreur TypeError si il
Je me demandais également si je devais utiliser des paranthèses ici, merci pour la modif. J'utiliserai ce format à l'avenir.

2022-12-23 10:20 UTC, gregWDumont commented
On doit être tout bon, merci pour la relecture !

2022-12-23 17:33 UTC, cw118 approved these changes
Merci beaucoup @gregWDumont, fusionnons tout ça :)

2022-12-23 17:33 UTC, merged