update async translate，更新更容易理解的中文
mdn/translated-content pull request #10898
Opened 2023-01-04 08:32 UTC by wanqingying

update translate

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-01-04 08:57 UTC, fwqaaq commented on files/zh-cn/games/techniques/async_scripts/index.md
> +如果你的代码是一个 JS 字符串呢？您应该使用 URL.createObjectURL 包装的 Blob 对象，而不是使用 eval 或 innerHTML，这两者都会触发同步编译：
```suggestion
如果你的代码是一个 JS 字符串呢？你应该使用 URL.createObjectURL 包装的 Blob 对象，而不是使用 eval 或 innerHTML，这两者都会触发同步编译：
```
https://github.com/mdn/translated-content/blob/e8b614665d4cb3be1b3cb571694eaef7f2817615/docs/zh-cn/translation-guide.md?plain=1#L188

2023-01-04 09:50 UTC, yin1999 requested changes

2023-01-05 06:47 UTC, yin1999 commented on files/zh-cn/games/techniques/async_scripts/index.md
> +如果你的代码是一个 JS 字符串呢？你应该使用 URL.createObjectURL 包装的 Blob 对象，而不是使用 eval 或 innerHTML，这两者都会触发同步编译：
```suggestion
如果你的代码是一个 JS 字符串呢？你应该使用带有对象 URL（object URL）的 Blob 对象，而不是使用 `eval` 或 `innerHTML`，这两者都会触发同步编译：
```

2023-01-05 06:49 UTC, yin1999 approved these changes

2023-01-05 06:51 UTC, merged