zh-cn(update): sync CORS for the English
mdn/translated-content pull request #10931
Opened 2023-01-05 08:40 UTC by fwqaaq

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-01-05 10:12 UTC, yin1999 requested changes

2023-01-05 10:12 UTC, yin1999 commented on files/zh-cn/glossary/cors/index.md
> +### CORS 标头
请同时修改 en-US 文档的标题级别：

```suggestion
## CORS 标头
```

2023-01-05 10:12 UTC, yin1999 commented on files/zh-cn/glossary/cors/index.md
> +- 在维基百科的[跨源资源共享](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing)
```suggestion
- 维基百科上的[跨源资源共享](https://zh.wikipedia.org/wiki/跨來源資源共享)
```

2023-01-06 00:13 UTC, yin1999 commented
请同步修改英文文档：https://github.com/mdn/content/blob/ffb20c5e9a940d083c97758cf73217e638feee1e/files/en-us/glossary/cors/index.md?plain=1#L13

2023-01-06 04:49 UTC, fwqaaq commented
update: https://github.com/mdn/content/pull/23427/files

2023-01-06 05:02 UTC, yin1999 approved these changes

2023-01-06 05:02 UTC, merged