zh-cn(update): sync http1.1 for english version
mdn/translated-content pull request #10982
Opened 2023-01-07 11:28 UTC by fwqaaq

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-01-07 11:29 UTC, fwqaaq commented on files/zh-cn/web/http/connection_management_in_http_1.x/index.md
> +要注意的一个重点是 HTTP 的连接管理适用于两个连续节点之间的连接，它是[逐跳（Hop-by-hop）标头](/zh-CN/docs/Web/HTTP/Headers#逐跳Hop-by-hop标头)，而不是[端到端（End-to-end）标头](/zh-CN/docs/Web/HTTP/Headers#端到端End-to-end标头)。当模型用于从客户端到第一个代理服务器的连接和从代理服务器到
这个 hash 后缀我试了一下，要去掉  `（）` 但是我不确定 mdn 是否是这样
```suggestion
要注意的一个重点是 HTTP 的连接管理适用于两个连续节点之间的连接，它是[逐跳（Hop-by-hop）标头](/zh-CN/docs/Web/HTTP/Headers#逐跳Hop-by-hop标头)，而不是[端到端（End-to-end）标头](/zh-CN/docs/Web/HTTP/Headers#端到端End-to-end标头)。当模型用于从客户端到第一个代理服务器的连接和从代理服务器到目标服务器之间的连接时（或者任意中间代理）效果可能是不一样的。HTTP 协议头受不同连接模型的影响，比如 {{HTTPHeader("Connection")}} 和 {{HTTPHeader("Keep-Alive")}}，就是[逐跳（Hop-by-hop）标头](/zh-CN/docs/Web/HTTP/Headers#逐跳Hop-by-hop标头)标头，它们的值是可以被中间节点修改的。
```

2023-01-07 11:34 UTC, yin1999 commented on files/zh-cn/web/http/connection_management_in_http_1.x/index.md
> +要注意的一个重点是 HTTP 的连接管理适用于两个连续节点之间的连接，它是[逐跳（Hop-by-hop）标头](/zh-CN/docs/Web/HTTP/Headers#逐跳Hop-by-hop标头)，而不是[端到端（End-to-end）标头](/zh-CN/docs/Web/HTTP/Headers#端到端End-to-end标头)。当模型用于从客户端到第一个代理服务器的连接和从代理服务器到
![image](https://user-images.githubusercontent.com/15844309/211148542-1829f0a0-bf5e-4423-b8a7-475dd9bf566a.png)

2023-01-07 11:36 UTC, yin1999 requested changes

2023-01-07 11:36 UTC, yin1999 commented on files/zh-cn/web/http/connection_management_in_http_1.x/index.md
> +作为 HTTP/1.x 的连接，请求是序列化的，哪怕本来是无序的，在没有足够庞大可用的带宽时，也无从优化。一个解决方案是，浏览器为每个域名建立多个连接，以实现并发请求。曾经默认的连接数量为 2 到 3 个，现在比较常用的并发连接数已经增加到 6 条。如果尝试大于这个数字，就有触发服务器 [DoS](https://developer.mozilla.org/zh-CN/docs/Glossary
去掉链接的 host

2023-01-07 11:36 UTC, yin1999 commented on files/zh-cn/web/http/connection_management_in_http_1.x/index.md
> +连接管理是一个 HTTP 的关键话题：打开和保持连接在很大程度上影响着网站和 Web 应用程序的性能。在 HTTP/1.x 里有多种模型：*短连接*，*长连接*，和 *HTTP 流水线*。
顿号，这里也可以使用下划线

2023-01-07 13:34 UTC, fwqaaq commented on files/zh-cn/web/http/connection_management_in_http_1.x/index.md
> +连接管理是一个 HTTP 的关键话题：打开和保持连接在很大程度上影响着网站和 Web 应用程序的性能。在 HTTP/1.x 里有多种模型：*短连接*，*长连接*，和 *HTTP 流水线*。
嗯，喜欢 * 号

2023-01-07 13:35 UTC, fwqaaq commented on files/zh-cn/web/http/connection_management_in_http_1.x/index.md
> +要注意的一个重点是 HTTP 的连接管理适用于两个连续节点之间的连接，它是[逐跳（Hop-by-hop）标头](/zh-CN/docs/Web/HTTP/Headers#逐跳Hop-by-hop标头)，而不是[端到端（End-to-end）标头](/zh-CN/docs/Web/HTTP/Headers#端到端End-to-end标头)。当模型用于从客户端到第一个代理服务器的连接和从代理服务器到
🆗

2023-01-07 13:36 UTC, fwqaaq commented on files/zh-cn/web/http/connection_management_in_http_1.x/index.md
> +连接管理是一个 HTTP 的关键话题：打开和保持连接在很大程度上影响着网站和 Web 应用程序的性能。在 HTTP/1.x 里有多种模型：*短连接*，*长连接*，和 *HTTP 流水线*。
```suggestion
连接管理是一个 HTTP 的关键话题：打开和保持连接在很大程度上影响着网站和 Web 应用程序的性能。在 HTTP/1.x 里有多种模型：*短连接*、*长连接*和 *HTTP 流水线*。
```

2023-01-07 13:36 UTC, fwqaaq commented on files/zh-cn/web/http/connection_management_in_http_1.x/index.md
> +作为 HTTP/1.x 的连接，请求是序列化的，哪怕本来是无序的，在没有足够庞大可用的带宽时，也无从优化。一个解决方案是，浏览器为每个域名建立多个连接，以实现并发请求。曾经默认的连接数量为 2 到 3 个，现在比较常用的并发连接数已经增加到 6 条。如果尝试大于这个数字，就有触发服务器 [DoS](https://developer.mozilla.org/zh-CN/docs/Glossary
```suggestion
作为 HTTP/1.x 的连接，请求是序列化的，哪怕本来是无序的，在没有足够庞大可用的带宽时，也无从优化。一个解决方案是，浏览器为每个域名建立多个连接，以实现并发请求。曾经默认的连接数量为 2 到 3 个，现在比较常用的并发连接数已经增加到 6 条。如果尝试大于这个数字，就有触发服务器 DoS 保护的风险。
```

2023-01-08 00:38 UTC, yin1999 commented on files/zh-cn/web/http/connection_management_in_http_1.x/index.md
> +要注意的一个重点是 HTTP 的连接管理适用于两个连续节点之间的连接，它是[逐跳（Hop-by-hop）标头](/zh-CN/docs/Web/HTTP/Headers#逐跳（Hop-by-hop）标头)，而不是[端到端（End-to-end）标头](/zh-CN/docs/Web/HTTP/Headers#端到端（End-to-end）标头)。当模型用于从客户端到第一个代理服务器的连接和从代理
```suggestion
要注意的一个重点是 HTTP 的连接管理适用于两个连续节点之间的连接，它是[逐跳（Hop-by-hop）标头](/zh-CN/docs/Web/HTTP/Headers#逐跳（hop-by-hop）标头)，而不是[端到端（End-to-end）标头](/zh-CN/docs/Web/HTTP/Headers#端到端（end-to-end）标头)。当模型用于从客户端到第一个代理服务器的连接和从代理服务器到目标服务器之间的连接时（或者任意中间代理）效果可能是不一样的。HTTP 协议头受不同连接模型的影响，比如 {{HTTPHeader("Connection")}} 和 {{HTTPHeader("Keep-Alive")}}，就是[逐跳标头](/zh-CN/docs/Web/HTTP/Headers#逐跳（hop-by-hop）标头)标头，它们的值是可以被中间节点修改的。
```

2023-01-08 00:38 UTC, yin1999 commented on files/zh-cn/web/http/connection_management_in_http_1.x/index.md
> +> 由于这些原因，流水线已被 HTTP/2 中更好的算法*多路复用*所取代。
```suggestion
> - 流水线受制于[队头阻塞（HOL）](https://zh.wikipedia.org/wiki/队头阻塞)问题。
>
> 由于这些原因，流水线已被 HTTP/2 中更好的算法——*多路复用*（multiplexing）所取代。
```

2023-01-08 00:38 UTC, yin1999 commented on files/zh-cn/web/http/connection_management_in_http_1.x/index.md
> +并不是所有类型的 HTTP 请求都能用到流水线：只有{{glossary("idempotent", "幂等")}}方式，比如 {{HTTPMethod("GET")}}、{{HTTPMethod("HEAD")}}、{{HTTPMethod("PUT")}} 和 {{HTTPMethod("DELETE")}} 能够被安全的重试。如果有故障发生时，流水线的内容要能被轻易的重试。
```suggestion
并不是所有类型的 HTTP 请求都能用到流水线：只有{{glossary("idempotent", "幂等")}}方式，比如 {{HTTPMethod("GET")}}、{{HTTPMethod("HEAD")}}、{{HTTPMethod("PUT")}} 和 {{HTTPMethod("DELETE")}} 能够被安全地重试。如果有故障发生时，流水线的内容要能被轻易的重试。
```

2023-01-08 00:39 UTC, yin1999 approved these changes

2023-01-08 00:41 UTC, yin1999 commented on files/zh-cn/web/http/connection_management_in_http_1.x/index.md
> +> **备注：** 除非你有紧急而迫切的需求，不要使用这一过时的技术；而是升级到 HTTP/2。在 HTTP/2 里，做域名分片就没必要了：HTTP/2 的连接可以很好的处理并发的无优先级的请求。域名分片甚至会影响性能。大多数 HTTP/2 的实现还会使用一种称作[连接凝聚](https://daniel.haxx.se/blog/2016/08/18/http2-connection-coal
```suggestion
> **备注：** 除非你有紧急而迫切的需求，不要使用这一过时的技术；而是升级到 HTTP/2。在 HTTP/2 里，做域名分片就没必要了：HTTP/2 的连接可以很好的处理并发的无优先级的请求。域名分片甚至会影响性能。大多数 HTTP/2 的实现还会使用一种称作[连接聚合](https://daniel.haxx.se/blog/2016/08/18/http2-connection-coalescing/)的技术去尝试合并被分片的域名。
```

2023-01-08 00:44 UTC, merged