zh-cn(update): sync protocol upgrade mechanism
mdn/translated-content pull request #10991
Opened 2023-01-08 02:24 UTC by fwqaaq

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-01-08 02:24 UTC, fwqaaq commented on files/zh-cn/web/http/protocol_upgrade_mechanism/index.md
> +这个机制是可选的；它并不能执意协议的更改（通常来说这一机制总是由客户端发起的）。如果它们支持新协议，实现甚至可以不利用 upgrade，在实践中，这种机制主要用于引导 WebSocket 连接。
```suggestion
这个机制是可选的；它并不能强制协议的更改（通常来说这一机制总是由客户端发起的）。如果它们支持新协议，实现甚至可以不利用 upgrade，在实践中，这种机制主要用于引导 WebSocket 连接。
```

2023-01-08 07:27 UTC, fwqaaq commented on files/zh-cn/web/http/protocol_upgrade_mechanism/index.md
> +`Sec-WebSocket-Protocol` 标头按优先顺序指定你希望用的一个或者多个 WebSocket 协议。由服务器支持的第一个 WebSocket 协议，将由服务器在响应中包含的 `Sec-WebSocket-Protocol` 标头中选择并返回它。你可以在标头中多次使用它；结果与在单个标头中使用逗号分隔的子协议标识符列表相同。
```suggestion
`Sec-WebSocket-Protocol` 标头按优先顺序指定你希望用的一个或者多个 WebSocket 协议。将服务器支持的第一个 WebSocket 协议，由服务器在响应中包含的 `Sec-WebSocket-Protocol` 标头中选择并返回它。你可以在标头中多次使用它；结果与在单个标头中使用逗号分隔的子协议标识符列表相同。
```

2023-01-08 13:29 UTC, yin1999 requested changes

2023-01-08 13:29 UTC, yin1999 commented on files/zh-cn/web/http/protocol_upgrade_mechanism/index.md
> +注意：HTTP/2 明确禁止使用此机制；这个机制只属于 HTTP/1.1
```suggestion
注意：HTTP/2 明确禁止使用此机制；这个机制只属于 HTTP/1.1。
```

2023-01-08 13:29 UTC, yin1999 commented on files/zh-cn/web/http/protocol_upgrade_mechanism/index.md
>  - [`Connection: Upgrade`](/zh-CN/docs/Web/HTTP/Headers/Connection)
下面的这部分没有删去

2023-01-08 13:29 UTC, yin1999 commented on files/zh-cn/web/http/protocol_upgrade_mechanism/index.md
> +根据之前的请求的协议，可能需要其他头部信息，例如：从 HTTP/1.1 升级到 [WebSocket](/zh-CN/docs/Web/API/WebSocket) 允许配置有关 WebSocket 连接的头部详细信息，以及在连接时提供一定程度的安全性。查看[升级到 WebSocket 协议的连接](#升级到_websocket_协议的连接) 获取更多信息。
标头

2023-01-08 13:29 UTC, yin1999 commented on files/zh-cn/web/http/protocol_upgrade_mechanism/index.md
> +  - : 如果 {{HTTPHeader("Sec-WebSocket-Key")}} 标头被提供，则该标头的值是通过获取密钥的值、将字符串“258EAFA5-E914-47DA-95CA-C5AB0DC85B11”连接到它、采用 [SHA-1](https://zh.wikipedia.org/wiki/SHA-1) 哈希来计算的连接字符串，产生一个 20 字节的值。然后对该值进行 [bas
如果提供了xxx标头

2023-01-08 13:57 UTC, fwqaaq commented on files/zh-cn/web/http/protocol_upgrade_mechanism/index.md
>  ## 升级 HTTP/1.1 的链接
```suggestion
## 升级 HTTP/1.1 连接
```

2023-01-09 00:32 UTC, yin1999 commented on files/zh-cn/web/http/protocol_upgrade_mechanism/index.md
> +  - : 如果提供了 {{HTTPHeader("Sec-WebSocket-Key")}} 标头，则该标头的值是通过获取密钥的值、将字符串“258EAFA5-E914-47DA-95CA-C5AB0DC85B11”连接到它、采用 [SHA-1](https://zh.wikipedia.org/wiki/SHA-1) 哈希来计算的连接字符串，产生一个 20 字节的值。然后对该值进行 [bas
这段话的翻译还得再改改

2023-01-09 00:43 UTC, fwqaaq commented on files/zh-cn/web/http/protocol_upgrade_mechanism/index.md
> +  - : 如果提供了 {{HTTPHeader("Sec-WebSocket-Key")}} 标头，则该标头的值是通过获取密钥的值、将字符串“258EAFA5-E914-47DA-95CA-C5AB0DC85B11”连接到它、采用 [SHA-1](https://zh.wikipedia.org/wiki/SHA-1) 哈希来计算的连接字符串，产生一个 20 字节的值。然后对该值进行 [bas
```suggestion
  - : 如果提供了 {{HTTPHeader("Sec-WebSocket-Key")}} 标头，则通过取密钥的值，将字符串“258EAFA5-E914-47DA-95CA-C5AB0DC85B11”连接到它，取该连接字符串的 SHA-1 哈希，从而得出 20 字节值来计算此标头的值。然后对该值进行 [base64](/zh-CN/docs/Glossary/Base64) 编码以获得该属性的值。
```

2023-01-09 01:01 UTC, fwqaaq commented on files/zh-cn/web/http/protocol_upgrade_mechanism/index.md
> +  - : 如果提供了 {{HTTPHeader("Sec-WebSocket-Key")}} 标头，则该标头的值是通过获取密钥的值、将字符串“258EAFA5-E914-47DA-95CA-C5AB0DC85B11”连接到它、采用 [SHA-1](https://zh.wikipedia.org/wiki/SHA-1) 哈希来计算的连接字符串，产生一个 20 字节的值。然后对该值进行 [bas
意思应该更清晰一点了

2023-01-09 03:56 UTC, yin1999 commented on files/zh-cn/web/http/protocol_upgrade_mechanism/index.md
> +  - : 如果提供了 {{HTTPHeader("Sec-WebSocket-Key")}} 标头，则该标头的值是通过获取密钥的值、将字符串“258EAFA5-E914-47DA-95CA-C5AB0DC85B11”连接到它、采用 [SHA-1](https://zh.wikipedia.org/wiki/SHA-1) 哈希来计算的连接字符串，产生一个 20 字节的值。然后对该值进行 [bas
还是不够好，“则通过”后面应该是一个用定语修饰的名词。最后两句话再好好考虑一下如何更好地描述

2023-01-09 14:31 UTC, fwqaaq commented on files/zh-cn/web/http/protocol_upgrade_mechanism/index.md
> +  - : 如果提供了 {{HTTPHeader("Sec-WebSocket-Key")}} 标头，则该标头的值是通过获取密钥的值、将字符串“258EAFA5-E914-47DA-95CA-C5AB0DC85B11”连接到它、采用 [SHA-1](https://zh.wikipedia.org/wiki/SHA-1) 哈希来计算的连接字符串，产生一个 20 字节的值。然后对该值进行 [bas
👌

2023-01-11 04:24 UTC, fwqaaq commented on files/zh-cn/web/http/protocol_upgrade_mechanism/index.md
> +  - : 如果提供了 {{HTTPHeader("Sec-WebSocket-Key")}} 标头，则该标头的值是通过获取密钥的值、将字符串“258EAFA5-E914-47DA-95CA-C5AB0DC85B11”连接到它、采用 [SHA-1](https://zh.wikipedia.org/wiki/SHA-1) 哈希来计算的连接字符串，产生一个 20 字节的值。然后对该值进行 [bas
@yin1999 改好了，请 review

2023-01-11 05:07 UTC, yin1999 commented
I've modified the suggestion. It's better for now.

2023-01-11 05:07 UTC, yin1999 approved these changes
Thanks

2023-01-11 05:09 UTC, merged