translation_CSS_Syntax
mdn/translated-content pull request #11008
Opened 2023-01-08 15:12 UTC by gregWDumont

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-01-08 15:13 UTC, gregWDumont commented
Salut,
J'ai un doute sur un paragraphe que j'ai mentionné en commentaires directement dans le texte.

2023-01-09 12:32 UTC, SphinxKnight requested changes
Merci @gregWDumont :)
Les images n'ont pas à être dupliquées du contenu anglais (elles seront reprise automatiquement). A minima, il faut donc supprimer les fichiers PNG de la PR.

Par ailleurs, vu les images en question, il pourrait valoir le coup d'avoir des versions localisées (bon ça demande plus de temps/de travail) (j'utilise https://app.diagrams.net/ de temps à autre) et une version SVG serait plus maintenable :x 

Je passe sur l'article même plus tard :)

2023-01-11 12:27 UTC, SphinxKnight requested changes
pour `css_syntax_-_block.png` : "la fin du bloc" plutôt que "la fin du block"

2023-01-11 12:57 UTC, SphinxKnight requested changes
Quelques suggestions :) 

Merci beaucoup déjà @gregWDumont pour le travail accompli

2023-01-11 12:57 UTC, SphinxKnight commented on files/fr/web/css/syntax/index.md
> +slug: Web/CSS/Syntax
```suggestion
title: Syntaxe
slug: Web/CSS/Syntax
l10n:
  sourceCommit: 71c4bc0b6329ec40ddbefd8d3124547e91cfa612
```

2023-01-11 12:57 UTC, SphinxKnight commented on files/fr/web/css/syntax/index.md
> +L'objectif fondamental du langage <i lang="en">Cascading Stylesheet</i> ([CSS](/fr/docs/Web/CSS)) est de permettre à un moteur de navigation d'associer des fonctionnalités spécifiques, comme les coul
```suggestion
L'objectif fondamental du langage <i lang="en">Cascading Style Sheets</i> ([CSS](/fr/docs/Web/CSS)) est de permettre à un moteur de navigation d'associer des fonctionnalités spécifiques, comme les couleurs, le positionnement ou les décorations à des éléments de la page. La _syntaxe CSS_ reflète cet objectif et ses éléments de base sont&nbsp;:
```

2023-01-11 12:57 UTC, SphinxKnight commented on files/fr/web/css/syntax/index.md
> +- La **propriété** est un identifiant, c'est-à-dire un _nom_ lisible par l'homme, qui définit quelle fonctionnalité est ciblée.
```suggestion
- La **propriété** est un identifiant, c'est-à-dire un _nom_ compréhensible par un être humain, qui définit quelle fonctionnalité est ciblée.
```

2023-01-11 12:57 UTC, SphinxKnight commented on files/fr/web/css/syntax/index.md
> +## déclarations CSS
```suggestion
## Déclarations CSS
```

2023-01-11 12:57 UTC, SphinxKnight commented on files/fr/web/css/syntax/index.md
> +Ces blocs sont naturellement appelés **blocs de déclaration** et les déclarations à l'intérieur sont séparées par un point-virgule, '`;`' (`U+003B SEMICOLON`). Un bloc de déclaration peut être vide,
```suggestion
Ces blocs sont naturellement appelés **blocs de déclaration** et les déclarations à l'intérieur sont séparées par un point-virgule, '`;`' (`U+003B SEMICOLON`). Un bloc de déclaration peut être vide, c'est-à-dire contenir une déclaration nulle. Les espaces blancs autour des déclarations sont ignorés. La dernière déclaration d'un bloc n'a pas besoin d'être terminée par un point-virgule, bien que faire ainsi soit considéré comme une bonne pratique (cela évite d'oublier de l'ajouter lors de l'extension du bloc avec une autre déclaration).
```

2023-01-11 12:57 UTC, SphinxKnight commented on files/fr/web/css/syntax/index.md
> +> **Remarque&nbsp;:** Le contenu d'un bloc de déclaration CSS, c'est-à-dire une liste de déclarations séparées par des points-virgules, sans les accolades d'ouverture et de fermeture, peut être placé
```suggestion
> **Note :** Le contenu d'un bloc de déclaration CSS, c'est-à-dire une liste de déclarations séparées par des points-virgules, sans les accolades d'ouverture et de fermeture, peut être placé dans un attribut HTML [`style`](/fr/docs/Web/HTML/Global_attributes#attr-style).
```

2023-01-11 12:57 UTC, SphinxKnight commented on files/fr/web/css/syntax/index.md
> +Comme un élément de la page peut être mis en correspondance par plusieurs sélecteurs, et donc par plusieurs règles contenant potentiellement plusieurs fois une même propriété, avec des valeurs différ
```suggestion
Comme un élément de la page peut correspondre à plusieurs sélecteurs, et donc par plusieurs règles contenant potentiellement plusieurs fois une même propriété, avec des valeurs différentes, la norme CSS définit laquelle a priorité sur l'autre et doit être appliquée&nbsp;: c'est ce qu'on appelle la [cascade](/fr/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance).
```

2023-01-11 12:57 UTC, SphinxKnight commented on files/fr/web/css/syntax/index.md
> +Un ensemble de règles CSS (ou règle) est visualisé dans le diagramme ci-dessous.
```suggestion
Une règle CSS est visualisé dans le diagramme ci-dessous.
```

2023-01-11 12:57 UTC, SphinxKnight commented on files/fr/web/css/syntax/index.md
> +> Cela conduit à une conséquence importante&nbsp;: si un seul sélecteur de base est invalide, comme lors de l'utilisation d'un pseudo-élément ou d'une pseudo-classe inconnus, l'ensemble du _sélecteur
```suggestion
> **Note :** Même si on peut utiliser une règle utilisant un groupe de sélecteurs afin d'éviter de dupliquer une même règle pour chaque sélecteur distinct de ce groupe, cela n'a pas exactement le même effet. En effet, si on utilise un groupe de sélecteurs contenant un sélecteur invalide, c'est tout le groupe qui sera invalide et la règle sera ignoré. Si on utilise plusieurs règles pour chacun des sélecteurs individuels, seule celle du sélecteur invalide ne sera pas appliquée.
```

2023-01-11 12:57 UTC, SphinxKnight commented on files/fr/web/css/syntax/index.md
> +Les ensembles de règles sont les principaux éléments constitutifs d'une feuille de style, qui se compose souvent d'une longue liste de ceux-ci. Mais il y a d'autres informations qu'un auteur Web veut
```suggestion
Les ensembles de règles sont les principaux éléments constitutifs d'une feuille de style, qui se compose souvent d'une longue liste de ceux-ci. Mais il y a d'autres informations qu'on peut transmettre dans la feuille de style, comme le jeu de caractères, d'autres feuilles de style externes à importer, les descriptions des polices de caractères ou des compteurs de liste et bien d'autres. On utilisera alors d'autres types d'instructions spécifiques.
```

2023-01-11 12:57 UTC, SphinxKnight commented on files/fr/web/css/syntax/index.md
> +Une **instruction** est un bloc de construction qui commence par n'importe quel caractère autre qu'un espace et se termine à la première accolade ou point-virgule fermant (en dehors d'une chaîne, san
```suggestion
Une **instruction** est un bloc de construction qui commence par n'importe quel caractère autre qu'un espace et se termine à la première accolade ou point-virgule fermant (en dehors d'une chaîne, sans échappement et qui ne soit pas inclus dans une autre paire d'accolades (`{}`), de parenthèses (`()`), ou de crochets (`[]`)).
```

2023-01-11 12:57 UTC, SphinxKnight commented on files/fr/web/css/syntax/index.md
> +Il existe deux types de déclarations :
```suggestion
Il existe deux types de déclarations&nbsp;:
```

2023-01-11 12:57 UTC, SphinxKnight commented on files/fr/web/css/syntax/index.md
> +- Les **ensembles de règles** (ou _règles_) qui, comme on le voit, associent une collection de déclarations CSS à une condition décrite par un [sélecteur](/fr/docs/Web/CSS/CSS_Selectors).
```suggestion
- Les **règles** qui associent une collection de déclarations CSS à une condition décrite par un [sélecteur](/fr/docs/Web/CSS/CSS_Selectors).
```

2023-01-11 12:57 UTC, SphinxKnight commented on files/fr/web/css/syntax/index.md
> +- Les **règles @** qui commencent par un arobase, '`@`' (`U+0040 COMMERCIAL AT`), suivi d'un identifiant et se poursuivant jusqu'à la fin de l'instruction, c'est-à-dire jusqu'à au prochain point-virg
```suggestion
- Les **règles @** qui commencent par une arobase, '`@`' (`U+0040 COMMERCIAL AT`), suivie d'un identifiant et se poursuivant jusqu'à la fin de l'instruction, c'est-à-dire jusqu'à au prochain point-virgule (;) en dehors d'un bloc, ou à la fin du bloc suivant. Chaque type de [règles @](/fr/docs/Web/CSS/At-rule), défini par l'identifiant, peut avoir sa propre syntaxe interne, et bien sûr sa sémantique. Ils sont utilisés pour transmettre des informations de métadonnées (comme [`@charset`](/fr/docs/Web/CSS/@charset) ou [`@import`](/fr/docs/Web/CSS/@import)), des informations conditionnelles (comme [`@media`](/fr/docs/Web/CSS/@media) ou [`@document`](/fr/docs/Web/CSS/@document)), ou des informations descriptives (comme [`@font-face`](/fr/docs/Web/CSS/@font-face)).
```

2023-01-11 12:57 UTC, SphinxKnight commented on files/fr/web/css/syntax/index.md
> +Toute instruction qui n'est pas un ensemble de règles ou une règle-at est invalide et ignorée.
```suggestion
Toute instruction qui n'est pas une règle ou une règle @ est invalide et ignorée.
```

2023-01-11 12:57 UTC, SphinxKnight commented on files/fr/web/css/syntax/index.md
> +Il existe un autre groupe d'instructions&nbsp;: les **instructions imbriquées**. Ce sont des instructions qui peuvent être utilisées dans un sous-ensemble spécifique de règles @ - les _règles de grou
```suggestion
Il existe un autre groupe d'instructions&nbsp;: les **instructions imbriquées**. Ce sont des instructions qui peuvent être utilisées dans un sous-ensemble spécifique de règles @&nbsp;: les _[règles de groupe conditionnelles](/fr/docs/Web/CSS/At-rule#les_règles_de_groupe_conditionnelles)_. Ces déclarations ne s'appliquent que si une condition spécifique est satisfaite. Par exemple, le contenu d'une règle @ `@media` est appliqué uniquement si l'appareil sur lequel le navigateur s'exécute correspond à la condition exprimée.
```

2023-01-11 12:57 UTC, SphinxKnight commented on files/fr/web/css/syntax/index.md
> +  - [Élément remplacé](/fr/docs/Web/CSS/Replaced_element)
```suggestion
- Concepts clés CSS&nbsp;:
  - **Syntaxe CSS**
  - [Commentaires](/fr/docs/Web/CSS/Comments)
  - [Spécificité](/fr/docs/Web/CSS/Specificity)
  - [Héritage](/fr/docs/Web/CSS/inheritance)
  - [Modèle de boîte](/fr/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model)
  - [Mode de mise en page](/fr/docs/Web/CSS/Layout_mode)
  - [Modèle de mise en forme visuelles](/fr/docs/Web/CSS/Visual_formatting_model)
  - [Fusion des marges](/fr/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing)
  - Valeurs
    - [Valeur initiale](/fr/docs/Web/CSS/initial_value)
    - [Valeur calculée](/fr/docs/Web/CSS/computed_value)
    - [Valeur utilisée](/fr/docs/Web/CSS/used_value)
    - [Valeur réelle](/fr/docs/Web/CSS/actual_value)
  - [Syntaxe de définition des valeurs](/fr/docs/Web/CSS/Value_definition_syntax)
  - [Propriétés raccourcies](/fr/docs/Web/CSS/Shorthand_properties)
  - [Élément remplacé](/fr/docs/Web/CSS/Replaced_element)
```

2023-01-11 12:57 UTC, SphinxKnight commented on files/fr/web/css/syntax/index.md
> +Le CSS permet cela en associant des conditions à des blocs de déclarations. Chaque bloc de déclaration (valide) est précédé d'un ou plusieurs [**sélecteurs**](/fr/docs/Web/CSS/CSS_Selectors) séparés
```suggestion
Le CSS permet cela en associant des conditions à des blocs de déclarations. Chaque bloc de déclaration (valide) est précédé d'un ou plusieurs [**sélecteurs**](/fr/docs/Web/CSS/CSS_Selectors) séparés par des virgules, qui sont des conditions sélectionnant certains éléments de la page. Un [<i lang="en">groupe de sélecteurs</i>](/fr/docs/Web/CSS/Selector_list) et un bloc de déclarations associé, ensemble, forment ce qu'on appelle une **règle** (en anglais, le terme formel est <i lang="en">ruleset</i>, mais <i lang="en">rule</i> est également usité).
```

2023-01-11 12:59 UTC, SphinxKnight commented
> Salut, J'ai un doute sur un paragraphe que j'ai mentionné en commentaires directement dans le texte.

N'hésite pas à utiliser les commentaires de revue GitHub dans ce cas ^^ (on peut soi-même commenter sur sa propre PR, ça permet d'ouvrir des discussions)

2023-01-11 15:59 UTC, gregWDumont commented
I copy/pasted the command `filecheck` from the mdn/content package.json list of scripts to the mdn/translated-content as it was missing which resulted in giving the following outcome when I used the compressing command:
```
$ env-cmd --silent cross-env CONTENT_ROOT=files yari-filecheck --cwd=. css_syntax_-_declaration.png --save-compression
/bin/sh: env-cmd: command not found
error Command failed with exit code 127.
```
 The same command was working for the same image that I committed on the [mdn/content version](https://github.com/mdn/content/pull/23543).

2023-01-12 07:49 UTC, SphinxKnight commented
@gregWDumont Il faut lancer la commande `yarn filecheck` depuis le dépôt local de mdn/content en lui indiquant le chemin des fichiers présents dans l'arborescence du dépôt local mdn/translated-content. Par exemple, j'ai lancé ce qui suit et ça fonctionne : 
`yarn filecheck '../translated-content/files/fr/web/css/syntax/css_syntax_-_block.png' --save-compression`

2023-01-12 08:24 UTC, SphinxKnight commented
lessgo :)

2023-01-12 08:24 UTC, merged