Replace outdated references to createObjectURL()
mdn/translated-content pull request #11003
Opened 2023-01-08 12:32 UTC by BaguetteSeeker

- Removed the former maintainer' advanced demo version' references, which seem to no longer be maintained and returns a 404 error (repo still accessible but it just seem confusing to leave its link having no workable demo available)

-  Replaced code sections using outdated [createObjectURL()](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL#using_object_urls_for_media_streams) calls. Did so with proper assignement of the raw `stream` to the srcObject of our `video` element, and using `Promise` based response handling

- Changed demo links to an updated functioning [JSFiddle ](https://jsfiddle.net/BaguetteSeeker/jchezp01/) (same code replacements as above)

-  Removed vendor specific comments / code sections referring to Firefox Nightly (given it isn't referred to on the English doc, i assume Nightly now has native support for the MediaDevices API)

-  Extended the step by step description of section **Obtenir la vidéo** according to the English version

2023-01-11 11:48 UTC, BaguetteSeeker commented
Voilà pour la maj fonctionnelle / ergonomique @SphinxKnight .

J'ai ajouté des tags, et j'ai repris la `macro` de la doc anglaise pour avoir la barre de navigation concernant le reste de la doc relative à l'API. Si j'ai bien compris le fonctionnement de la chose, la langue de la nav bar devrait être la même que celle de l'article par-dessus lequel elle est affichée

2023-01-12 08:23 UTC, SphinxKnight requested changes
J'ai commencé la revue mais j'ai l'impression qu'il y a pas mal de différences par rapport à la version anglaise.
Comme GitHub ne me permet pas d'ajouter des suggestions pour certaines lignes, je vais proposer une PR sur votre fork, j'espère que ça sera plus pratique ainsi.

2023-01-12 08:23 UTC, SphinxKnight commented on files/fr/web/api/media_capture_and_streams_api/taking_still_photos/index.md
>  original_slug: Web/API/Media_Streams_API/Taking_still_photos
```suggestion
l10n:
  sourceCommit: 161d14143bce668a6d33415d58f349423b3d3758
```

2023-01-12 08:23 UTC, SphinxKnight commented on files/fr/web/api/media_capture_and_streams_api/taking_still_photos/index.md
>  original_slug: Web/API/Media_Streams_API/Taking_still_photos
Il faudrait également aligner le titre sur la version anglophone : "Prendre des photos avec getUserMedia()" (je ne peux pas fournir de suggestion Git à cet endroit :( )

2023-01-12 08:23 UTC, SphinxKnight commented on files/fr/web/api/media_capture_and_streams_api/taking_still_photos/index.md
>  ## Introduction et demo
```suggestion
```
Ce titre n'est pas présent en anglais, autant le retirer également ici.

2023-01-12 09:45 UTC, BaguetteSeeker commented
> J'ai commencé la revue mais j'ai l'impression qu'il y a pas mal de différences par rapport à la version anglaise. Comme GitHub ne me permet pas d'ajouter des suggestions pour certaines lignes, je vais proposer une PR sur votre fork, j'espère que ça sera plus pratique ainsi.

Effectivement, l'article conserve d'assez nettes différences, même après mes changements. Le but de cette PR étant d'abord de proposer un code / article fonctionnel pour les visiteurs, le temps de retravailler l'arrangement et la traduction de l'article plus en profondeur. Cependant si c'est mieux de publier tout les changements en une seule PR, on peut tout à fait faire comme ça

2023-01-12 12:52 UTC, SphinxKnight commented
> > J'ai commencé la revue mais j'ai l'impression qu'il y a pas mal de différences par rapport à la version anglaise. Comme GitHub ne me permet pas d'ajouter des suggestions pour certaines lignes, je vais proposer une PR sur votre fork, j'espère que ça sera plus pratique ainsi.
> 
> Effectivement, l'article conserve d'assez nettes différences, même après mes changements. Le but de cette PR étant d'abord de proposer un code / article fonctionnel pour les visiteurs, le temps de retravailler l'arrangement et la traduction de l'article plus en profondeur. Cependant si c'est mieux de publier tout les changements en une seule PR, on peut tout à fait faire comme ça

j'ai poussé ça sur https://github.com/BaguetteSeeker/translated-content/pull/1/, désolé du coup pour le temps passé en double

2023-01-18 11:44 UTC, SphinxKnight requested changes
Pour les documents en français, on utilise le mode "Auto" des exemples embarqués, cela facilite la maintenance en cas de changement des titres.
Il s'agit donc bien d'une différence avec la version anglophone mais l'exemple fonctionne sans, autant le retirer.

2023-01-18 11:46 UTC, SphinxKnight requested changes
Sur le processus, les changements de db0d29b677cd9271aafed3c4b8b2929e314b5727 apportent du contenu supplémentaire par rapport à la version anglaise. Il faudrait que ceux-ci soient déjà présents sur la version anglaise de mdn/content.

Sur le fond, je ne suis pas certain que ça serve au propos d'illustration de `getUserMedia()` qui est le sujet de l'article.

2023-01-18 11:51 UTC, SphinxKnight requested changes
En l'état, je préfère garder la photo d'origine du contenu de mdn/content :
- Voir la remarque précédente sur l'ajout du téléchargement (et du libellé associé)
- Le poster en fond représente un risque non négligeable de débat non pertinent sur MDN : je ne dis pas qu'aucun sujet n'est politique mais plutôt qu'on peut facilement avoir une image qui soit moins source de flamewar qui ne concerne pas la documentation du Web.

2023-01-18 18:01 UTC, BaguetteSeeker commented
- J'avais initialement eu l'idée de la fonctionnalité de téléchargement car il ne me paraissait pas du tout évident que l'URL d'objet puisse être utilisée dans un href pour servir à télécharger la donnée en question. J'ai pensé que ce cas d'utilisation serait susceptible d'inspirer les visiteur·ices. Mais du coup effectivement, une telle démonstration serait plus pertinente sur la page concernant directement [les URLs de données](https://developer.mozilla.org/fr/docs/Web/HTTP/Basics_of_HTTP/Data_URLs)

- J'entends l'argument sur la nécessité de la prévalence de la documentation anglaise par souci de conformité et cohérence inter-langues. Si des ajouts me semblent pertinents à l'avenir, je prendrais soin de les proposer sur la doc anglaise en amont.

- Merci pour l'explication concernant le mode auto. Je trouvais justement curieux que tu aies laissé le 1er paramètre de la macro vide, ainsi que l'emplacement indiqué par l'adresse du fichier sans photo associée. Je comprends mieux maintenant! J'ai cru qu'il fallait reprendre une photo et j'étais d'humeur espiègle, d'où le poster de fond; mais je comprends totalement qu'il n'ait pas sa place sur MDN ;)

J'effectue le roll-back vers ta version, avec la petite correction orthographique en plus → https://github.com/mdn/translated-content/pull/11003/commits/9129f15c53c14923bfc9d2628a95f74afd653111 et je re-demande une review. Désolé du caractère décousu de cette PR. Je découvre certaines intrications de la contribution sur MDN. Les prochaines contributions de ma part seront plus synthétiques pour sûr. @SphinxKnight

2023-01-19 05:12 UTC, SphinxKnight approved these changes
Merci beaucoup @BaguetteSeeker, entre autres d'avoir tenu bon :) Il y avait en effet quelques arcanes de MDN ici :x Fusionnons ça :)

2023-01-19 05:12 UTC, merged