feat: translate glossary/property in ko
mdn/translated-content pull request #11035
Opened 2023-01-10 11:21 UTC by sukvvon

### Description

translate glossary/property in ko

### Motivation

[Property](https://developer.mozilla.org/en-US/docs/Glossary/property) page is not translated in ko so i translated

### Additional details

### Related issues and pull requests

2023-01-15 10:59 UTC, pje1740 commented on files/ko/glossary/property/index.md
> +
원본은 이 뒤에 CSS, JavaScript property 관련하여 더 설명이 있는데 혹시 누락된 걸까요? 확인 부탁드립니다!

2023-01-30 15:46 UTC, hochan222 requested changes
file request changes

2023-01-31 06:41 UTC, sukvvon commented on files/ko/glossary/property/index.md
> +
`{{GlossaryDisambiguation}}`에 필요한 [Property (JavaScript)](https://developer.mozilla.org/en-US/docs/Glossary/Property/JavaScript), [Property (CSS)](https://developer.mozilla.org/en-US/docs/Glossary/Property/CSS) 한글 번역 완료하여 누락된 부분 해결하였습니다! :)

2023-02-12 14:12 UTC, hochan222 approved these changes
@pje1740 님, 피드백주신 사항이 `{{GlossaryDisambiguation}}` 매크로 부분인듯합니다. 문제 없어보여서 머지하겠습니다!

@sukvvon 님, 기여해주셔서 감사합니다. 고생 많으셨습니다. 좋은 하루 보내세요 :)

2023-02-12 14:12 UTC, merged