Sync Access-Control-Expose-Headers Doc
mdn/translated-content pull request #11055
Opened 2023-01-11 10:55 UTC by maoxiaoke

sync with english version for  [Access-Control-Expose-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers) into Chinese

2023-01-11 12:48 UTC, awxiaoxian2020 requested changes

2023-01-11 13:01 UTC, maoxiaoke commented on files/zh-cn/web/http/headers/access-control-expose-headers/index.md
>  ## 相关内容
已处理

2023-01-11 13:12 UTC, yin1999 requested changes

2023-01-11 13:12 UTC, yin1999 commented on files/zh-cn/web/http/headers/access-control-expose-headers/index.md
> +  - : 若请求没有 [HTTP Cookie](/zh-CN/docs/Web/HTTP/Cookies)或认证信息，通配符 ”*“ 会暴露所有响应头部。对于有凭证信息的请求，会被简单地识别为头部名 ”*“，没有通配的语义。
```suggestion
  - : 若请求没有携带凭据（请求没有 [HTTP Cookie](/zh-CN/docs/Web/HTTP/Cookies)或认证信息），“`*`”才会被当作一个特殊的通配符。对于带有凭据的请求，会被简单地当作标头名称“`*`”，没有特殊的语义。
```

2023-01-11 13:12 UTC, yin1999 commented on files/zh-cn/web/http/headers/access-control-expose-headers/index.md
> +```plain
````suggestion
```http
````

2023-01-11 13:12 UTC, yin1999 commented on files/zh-cn/web/http/headers/access-control-expose-headers/index.md
>  ```plain
```suggestion
```http
```

2023-01-11 13:12 UTC, yin1999 commented on files/zh-cn/web/http/headers/access-control-expose-headers/index.md
> +有凭证信息的请求，可以指定一个通配符：
```suggestion
服务器可以为不带凭据的请求响应通配符：
```

2023-01-11 13:12 UTC, yin1999 commented on files/zh-cn/web/http/headers/access-control-expose-headers/index.md
> +但是，“*” 对 [Authorization 头](/zh-CN/docs/Web/HTTP/Headers/Authorization) 不生效，需要显式指定：
See line: https://github.com/mdn/content/blob/2344afbffd22b7932b755d6c74b8242ededdfbd2/files/en-us/web/http/headers/access-control-expose-headers/index.md?plain=1#L65

Please reflect the translation as the english content

2023-01-11 13:12 UTC, yin1999 commented on files/zh-cn/web/http/headers/access-control-expose-headers/index.md
> +```plain
also: http

2023-01-12 01:16 UTC, yin1999 commented on files/zh-cn/web/http/headers/access-control-expose-headers/index.md
> +但是，“*” 对 [Authorization 头](/zh-CN/docs/Web/HTTP/Headers/Authorization) 不生效，需要显式指定：
```suggestion
但是，这并不会匹配 {{HTTPHeader("Authorization")}} 标头，所以如果你要暴露它，需要显式指定：
```

2023-01-12 01:16 UTC, yin1999 commented on files/zh-cn/web/http/headers/access-control-expose-headers/index.md
>    - : 包含 0 个或多个除 {{Glossary("Simple response header", "simple response headers")}}（简单响应首部）之外的[首部名称](/zh-CN/docs/Web/HTTP/Headers)列表，可以暴露给外部，供页面资源使用。
```suggestion
  - : 包含 0 个或多个除{{Glossary("Simple response header", "简单响应标头")}}之外的[标头名称](/zh-CN/docs/Web/HTTP/Headers)列表，可以暴露给外部，供页面资源使用。
```

2023-01-12 01:16 UTC, yin1999 commented on files/zh-cn/web/http/headers/access-control-expose-headers/index.md
> +```plain
````suggestion
```http
````

2023-01-12 01:17 UTC, yin1999 commented on files/zh-cn/web/http/headers/access-control-expose-headers/index.md
>  ```plain
````suggestion
```http
````

2023-01-12 01:18 UTC, yin1999 commented on files/zh-cn/web/http/headers/access-control-expose-headers/index.md
```suggestion
```

2023-01-12 01:18 UTC, yin1999 commented on files/zh-cn/web/http/headers/access-control-expose-headers/index.md
>  想要暴露一个非简单响应首部，可以这样指定：
```suggestion
想要暴露一个非简单响应标头，可以这样指定：
```

2023-01-12 01:37 UTC, yin1999 approved these changes
Thanks a lot. I've applied some changes to made a full async.

Welcome to the community :tada: 

We've listed some suggestions [here](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md). Looking forward to your future contribution :)

2023-01-12 01:38 UTC, merged