Web/HTML/Link_types/preconnect, prerender を新規翻訳
mdn/translated-content pull request #1106
Opened 2021-06-05 15:02 UTC by mfuji09

- 2021/05/21 時点の英語版に基づき新規翻訳

2021-06-15 14:23 UTC, potappo requested changes
長音が足りなかったところを追加しました。確認をお願いします。

2021-06-15 14:23 UTC, potappo commented on files/ja/web/html/link_types/prerender/index.html
> +<p><span class="seoSummary"><strong><code>prerender</code></strong> キーワードを {{HTMLElement("link")}} 要素の {{HTMLAttrxRef("rel", "link")}} 属性に設定すると、ユーザーが次の操作でターゲットとなるリソースを必要とする可能性があることをブラウザーに示唆します。したがって、
```suggestion
<p><span class="seoSummary"><strong><code>prerender</code></strong> キーワードを {{HTMLElement("link")}} 要素の {{HTMLAttrxRef("rel", "link")}} 属性に設定すると、ユーザーが次の操作でターゲットとなるリソースを必要とする可能性があることをブラウザーに示唆します。したがって、ブラウザーはリソースの取得や処理を先取りすることで、ユーザーの操作性を向上させることができる可能性があります。</span></p>
```

2021-06-15 15:22 UTC, mfuji09 commented on files/ja/web/html/link_types/prerender/index.html
> +<p><span class="seoSummary"><strong><code>prerender</code></strong> キーワードを {{HTMLElement("link")}} 要素の {{HTMLAttrxRef("rel", "link")}} 属性に設定すると、ユーザーが次の操作でターゲットとなるリソースを必要とする可能性があることをブラウザーに示唆します。したがって、
うっかりしていました。ありがとうございます！

2021-06-16 12:00 UTC, potappo approved these changes
OK です。

2021-06-16 12:01 UTC, merged