[ja] hgroup の説明の更新
mdn/translated-content pull request #11122
Opened 2023-01-17 14:40 UTC by kagankan

### Description

hgroup要素の説明を英語版の内容に合わせる形で修正しました。

### Motivation

説明が、hgroupの現在の仕様と合っていないため。
（hgroupの仕様は昨年大きく変更されました。）

### Additional details

英語版の変更時の差分：
https://github.com/mdn/content/commit/59abae8b181d413e89e882c97e58c68c7c2c929f

HTML仕様：
https://html.spec.whatwg.org/multipage/sections.html#the-hgroup-element

### Related issues and pull requests

2023-01-24 14:08 UTC, mfuji09 requested changes
スタイル上の修正をお願いしいます。

2023-01-24 14:08 UTC, mfuji09 commented on files/ja/web/html/element/hgroup/index.md
> +**HTML の `<hgroup>` 要素**は、見出しとそれに関連する内容を表します。これは1つの [`<h1>–<h6>`](/ja/docs/Web/HTML/Element/Heading_Elements) 要素と、1つ以上の [`<p>`](/ja/docs/Web/HTML/Element/p) 要素をグループ化します。
半角数字と日本語の間には、空白を入れてください。

2023-01-24 14:08 UTC, mfuji09 commented on files/ja/web/html/element/hgroup/index.md
> +現在のところ、 `<hgroup>` 要素に強いアクセシビリティセマンティクスはありません。要素内のコンテンツ (見出しと、任意の段落) は、ブラウザーのアクセシビリティAPIによって公開されます。
日本語と英字の間にも、半角スペースを入れてください。

2023-01-26 16:28 UTC, kagankan commented
@mfuji09 

ご確認ありがとうございました！
半角スペースの修正を行いましたのでご確認ください。

2023-01-27 14:03 UTC, mfuji09 approved these changes
OKです。

2023-01-27 14:04 UTC, merged