Promise オブジェクト以下の記事を更新
mdn/translated-content pull request #11145
Opened 2023-01-18 16:14 UTC by mfuji09

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-01-21 08:16 UTC, potappo requested changes
文章的におかしいところを直しましたので、確認をお願いします。

2023-01-21 08:16 UTC, potappo commented on files/ja/web/javascript/reference/global_objects/promise/resolve/index.md
> +**`Promise.resolve()`** は静的メソッドで、 {{jsxref("Promise")}} を与えられた値で「解決」させます。値がプロミスの場合は、そのプロミスをそのプロミスが返されます。その値が [Thenable](/ja/docs/Web/JavaScript/Reference/Global_Objects/Promise#thenables) であれば、`Promi
```suggestion
**`Promise.resolve()`** は静的メソッドで、 {{jsxref("Promise")}} を与えられた値で「解決」させます。値がプロミスの場合は、そのプロミスが返されます。その値が [Thenable](/ja/docs/Web/JavaScript/Reference/Global_Objects/Promise#thenables) であれば、`Promise.resolve()` は `then()` メソッドを、準備した 2 つのコールバックと共に呼び出します。それ以外の場合は、その値で履行するプロミスが返されます。
```

2023-01-21 08:16 UTC, potappo commented on files/ja/web/javascript/reference/global_objects/promise/resolve/index.md
> +`Promise.resolve()` は、既存の `Promise` インスタンスを再利用します。ネイティブのプロミスを解決する場合は、ラッパーを作成せずに同じプロミスインスタンスを返す。
```suggestion
`Promise.resolve()` は、既存の `Promise` インスタンスを再利用します。ネイティブのプロミスを解決する場合は、ラッパーを作成せずに同じプロミスインスタンスを返します。
```

2023-01-24 14:09 UTC, mfuji09 commented on files/ja/web/javascript/reference/global_objects/promise/resolve/index.md
> +**`Promise.resolve()`** は静的メソッドで、 {{jsxref("Promise")}} を与えられた値で「解決」させます。値がプロミスの場合は、そのプロミスをそのプロミスが返されます。その値が [Thenable](/ja/docs/Web/JavaScript/Reference/Global_Objects/Promise#thenables) であれば、`Promi
ありがとうございます。編集ミスでした。

2023-01-24 14:14 UTC, merged