zh-cn: update not translated content
mdn/translated-content pull request #11188
Opened 2023-01-21 06:46 UTC by daiwanxing

### Description

promise.prototype.catch这一章节有部分未翻译或者漏翻译的内容，现将剩下的翻译完。

### Motivation

### Additional details

### Related issues and pull requests

2023-01-21 10:27 UTC, yin1999 requested changes
同时请注意中英文间的空格，而在中文与中文之间一般不加空格，请修正排版，具体说明请参考：<https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md#%E4%B8%AD%E6%96%87%E5%92%8C%E6%8B%89%E4%B8%81%E8%AF%AD%E7%B3%BB%E6%96%87%E5%AD%97%E9%97%B4%E5%8A%A0%E7%A9%BA%E6%A0%BC>

2023-01-21 10:27 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/promise/catch/index.md
> +当 promise 被 rejected 时，[Promise](/zh-CN/docs/Web/API/Promise)对象上的 `catch()` 方法会被调用。它会立即返回一个新的 Promise 对象，这可以允许你链式调用 promise 其他的方法。`catch()` 方法是{{jsxref("Promise.then", "Promise.prototype.then(undefin
还需修改，中文翻译应该尽可能贴近英文原文，最后一句话“的一种简写形式”，打错字了

2023-01-21 10:27 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/promise/catch/index.md
> +因为 `catch()` 只是单纯的调用了 `then()`，它支持 [子类化](https://en.wikipedia.org/wiki/Inheritance_(object-oriented_programming)#Subclasses_and_superclasses)。
外链引用应和英文文档保持一致。

2023-01-22 02:37 UTC, daiwanxing commented on files/zh-cn/web/javascript/reference/global_objects/promise/catch/index.md
> +当 promise 被 rejected 时，[Promise](/zh-CN/docs/Web/API/Promise)对象上的 `catch()` 方法会被调用。它会立即返回一个新的 Promise 对象，这可以允许你链式调用 promise 其他的方法。`catch()` 方法是{{jsxref("Promise.then", "Promise.prototype.then(undefin
好的

2023-01-22 04:23 UTC, yin1999 requested changes

2023-01-22 04:23 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/promise/catch/index.md
> +当 promise 被 rejected 时，[Promise](/zh-CN/docs/Web/API/Promise)对象上的 `catch()` 方法会被调用。它会立即返回一个新的 Promise 对象，这可以允许你链式调用 promise 其他的方法。`catch()` 方法是 {{jsxref("Promise.then", "Promise.prototype.then(undefi
```suggestion
{{jsxref("Promise")}} 对象的 **`catch()`** 方法用于注册一个在 promise 被拒绝时调用的函数。它会立即返回一个等价的 {{jsxref("Promise")}} 对象，这可以允许你[链式](/zh-CN/docs/Web/JavaScript/Guide/Using_promises#链式调用)调用其它 promise 的方法。此方法是 {{jsxref("Promise/then", "Promise.prototype.then(undefined, onRejected)")}} 的一种简写形式。

{{EmbedInteractiveExample("pages/js/promise-catch.html")}}
```

2023-01-22 04:23 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/promise/catch/index.md
> +返回一个新的{{jsxref("Promise")}}，无论当前的 promise 状态如何，这个新的 promise 在返回时总是处于挂起（pending）状态。 如果 `onRejected` 方法抛出了一个错误或者返回了一个被拒绝（rejected）的 promise， 那么这个新的 promise 也会被置为拒绝（rejected）；否则会被置为实现（fulfilled）。
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise#%E6%8F%8F%E8%BF%B0

```suggestion
返回一个新的 {{jsxref("Promise")}}，无论当前的 promise 状态如何，这个新的 promise 在返回时总是处于待定（pending）状态。 如果 `onRejected` 方法抛出了一个错误或者返回了一个被拒绝（rejected）的 promise， 那么这个新的 promise 也会被拒绝；否则它最终会被兑现（fulfilled）。
```

2023-01-22 04:23 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/promise/catch/index.md
> +`catch` 方法用于在 Promise 链进行错误处理，因为它总是会返回一个 Promise，所以它可以和 {{jsxref("Promise.prototype.then()")}} 方法一样被[链式调用](/zh-CN/docs/Web/JavaScript/Guide/Using_promises#chaining_after_a_catch)。
```suggestion
`catch` 方法用于在 Promise 链进行错误处理，因为它总是会返回一个 {{jsxref("Promise")}}，所以它可以和 {{jsxref("Promise/then", "then()")}} 方法一样被[链式调用](/zh-CN/docs/Web/JavaScript/Guide/Using_promises#链式调用)。
```

2023-01-22 04:23 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/promise/catch/index.md
> +如果一个 promise 置为被拒绝（rejected）并且没有可调用的拒绝处理函数（处理函数可以是 {{jsxref("Promise.prototype.then()")}}、{{jsxref("Promise.prototype.catch()")}}、{{jsxref("Promise.prototype.finally()")}} 中的其中一个），那么将会触发一个拒绝事件。拒绝事件由宿
这一段再修改一下，请对照原文：https://github.com/mdn/content/blob/a7bfa276a8f3f6afea79272f1967b5c80ececb0e/files/en-us/web/javascript/reference/global_objects/promise/catch/index.md?plain=1#L43

2023-01-23 06:29 UTC, daiwanxing commented on files/zh-cn/web/javascript/reference/global_objects/promise/catch/index.md
> +如果一个 promise 置为被拒绝（rejected）并且没有可调用的拒绝处理函数（处理函数可以是 {{jsxref("Promise.prototype.then()")}}、{{jsxref("Promise.prototype.catch()")}}、{{jsxref("Promise.prototype.finally()")}} 中的其中一个），那么将会触发一个拒绝事件。拒绝事件由宿
已修改了

2023-01-23 11:47 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/promise/catch/index.md
> +{{jsxref("Promise")}} 对象的 **`catch()`** 方法用于注册一个在 promise 被拒绝时调用的函数。它会立即返回一个等价的 {{jsxref("Promise")}} 对象，这可以允许你[链式调用](/zh-CN/docs/Web/JavaScript/Guide/Using_promises#链式调用)其他 promise 的方法。此方法是 {{jsxref
```suggestion
{{jsxref("Promise")}} 对象的 **`catch()`** 方法用于注册一个在 promise 被拒绝时调用的函数。它会立即返回一个等价的 {{jsxref("Promise")}} 对象，这可以允许你[链式](/zh-CN/docs/Web/JavaScript/Guide/Using_promises#链式调用)调用其它 promise 的方法。此方法是 {{jsxref("Promise/then", "Promise.prototype.then(undefined, onRejected)")}} 的一种简写形式。

{{EmbedInteractiveExample("pages/js/promise-catch.html")}}
```

2023-01-23 11:47 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/promise/catch/index.md
> +返回一个新的 {{jsxref("Promise")}}，无论当前的 promise 状态如何，这个新的 promise 在返回时总是处于待定（pending）状态。 如果 `onRejected` 方法抛出了一个错误或者返回了一个被拒绝（rejected）的 promise， 那么这个新的 promise 也会被拒绝（rejected）；否则它最终会被兑现（fulfilled）。
```suggestion
返回一个新的 {{jsxref("Promise")}}，无论当前的 promise 状态如何，这个新的 promise 在返回时总是处于待定（pending）状态。如果 `onRejected` 方法抛出了一个错误或者返回了一个被拒绝（rejected）的 promise， 那么这个新的 promise 也会被拒绝（rejected）；否则它最终会被兑现（fulfilled）。
```

2023-01-23 11:47 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/promise/catch/index.md
> +如果一个 promise 被拒绝（rejected）并且没有可调用的拒绝处理函数（处理函数可以是 {{jsxref("Promise.prototype.then()")}}、{{jsxref("Promise.prototype.catch()")}}、{{jsxref("Promise.prototype.finally()")}} 中的其中一个），则拒绝事件由宿主环境来提供。在浏览器中，这
```suggestion
如果一个 promise 被拒绝（rejected）并且没有可调用的拒绝处理器（处理器可以是 {{jsxref("Promise.prototype.then()")}}、{{jsxref("Promise.prototype.catch()")}} 或 {{jsxref("Promise.prototype.finally()")}}），则拒绝事件由宿主环境来提供。在浏览器中，这将导致未处理的拒绝（[`unhandledrejection`](/zh-CN/docs/Web/API/Window/unhandledrejection_event)）事件。如果将一个处理器附加到一个已被拒绝，且已导致未处理的拒绝事件的 promise，将会触发 [`rejectionhandled`](/zh-CN/docs/Web/API/Window/rejectionhandled_event) 事件。
```

2023-01-23 11:47 UTC, yin1999 approved these changes

2023-01-23 11:49 UTC, merged