mozilla-japan/translation#676
mdn/translated-content pull request #11193
Opened 2023-01-21 07:45 UTC by hitoshi44

mozilla-japan/translation#676

### Description

確認のためにPR出させていただきました。以下が変更点です。

- ディレクトリ, ファイルの作成(md, svg)
- タイトルの変更
- tags を `l10n: hash` に変更
- 冒頭の翻訳

2023-01-21 08:00 UTC, potappo requested changes
13 行目がスペースだけの行になっているかと思うので、削除してください。

日本語と英数字の間には半角スペースを入れてください。
https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline

2023-02-09 15:37 UTC, mfuji09 commented
@hitoshi44 さん
potappo さんからのコメントが来てから3週間がたちました。
本件を続いて対処されますか？

2023-02-10 13:15 UTC, hitoshi44 commented
@mfuji09 
ありがとうございます。potappoさんからの指摘は修正済みなのですが、まとまったコミットができたら再度リクエストをだすつもりでした。
自分としては引き続き翻訳を続けるつもりです。

翻訳はまだまだ終わっておらず、空き時間に少しずつ翻訳していく予定なのですが、ちょっと時間をかけすぎでしょうか。

2023-02-10 15:09 UTC, mfuji09 commented
@hitoshi44 さん
あまり長く時間をかけると、元の英語版が変更されたり、日本語版の他の記事との整合が問題になる可能性があります。切りの良いところでいったんコミットし、残りの翻訳は別なプルリクエストで投稿するという方法もあります。

2023-02-11 04:31 UTC, hitoshi44 commented
@mfuji09 さん
ありがとうございます。仰っていいただいた方法でコミットしていこうと思います。

@potappo さん
指摘箇所の修正と、（短いですが）次のセクションの翻訳を行いました。
時間が空いてしまい恐縮ですが、レビューお願いいたします。

2023-02-11 04:51 UTC, potappo commented
@hitoshi44 了解です！今外出中なので、夜以降、明日中にはチェックします。

2023-02-12 08:14 UTC, potappo approved these changes
脱字を1箇所修正しましたが、他は問題ありませんでしたので、これでいったんマージします。

2023-02-12 08:15 UTC, merged