fix markup syntax and translate content
mdn/translated-content pull request #11237
Opened 2023-01-24 15:50 UTC by weixiang0815

修復 markup 語法錯誤，並翻譯部分英文內容

2023-01-25 10:21 UTC, yin1999 requested changes

2023-01-25 10:21 UTC, yin1999 commented on files/zh-tw/learn/html/introduction_to_html/getting_started/index.md
> +> **備註：** HTML 中的元素是不區分大小寫的。例如：一個 {{htmlelement("title")}} 標籤可以寫成`<title>`、`<TITLE>`、`<Title>`、`<TiTlE>`之類的形式，都沒有問題。通常來說，為了保持一致性(consistency)、可讀性(readability)，以及其他可能的原因，最好還是以小寫來撰寫標籤。
请详细阅读<https://github.com/mdn/translated-content/blob/main/docs/zh-tw/translation-guide.md#%E4%B8%AD%E6%96%87%E7%BF%BB%E8%AD%AF%E7%9A%84%E5%B8%B8%E8%A6%8B%E5%95%8F%E9%A1%8C>完成标点等的修改

2023-01-25 10:21 UTC, yin1999 commented on files/zh-tw/learn/html/introduction_to_html/getting_started/index.md
> +1. **起始標籤(opening tag):** 它包含了元素的名字(在這裡是 p)，夾在一對 **<、> (angle brackets)** 之間。它指明元素從何開始生效 — 在上例中則代表段落的開始。
更改为中文标点可能有渲染的问题，可以采用以下格式：

https://github.com/mdn/content/blob/8183cfa3a25c440ca4ff0f39fe941871ed495a7b/files/en-us/learn/html/introduction_to_html/getting_started/index.md?plain=1#L70-L72

```suggestion
1. **起始標籤**（opening tag）：它包含了元素的名字(在這裡是 p)，夾在一對打開和關閉尖括號之間。它指明元素從何開始生效——在上例中則代表段落的開始。
```

2023-01-25 10:21 UTC, yin1999 commented on files/zh-tw/learn/html/introduction_to_html/getting_started/index.md
>  ## 另見
```suggestion
## 參見
```

2023-01-26 01:10 UTC, weixiang0815 commented on files/zh-tw/learn/html/introduction_to_html/getting_started/index.md
>  ## 另見
已修改。

2023-01-26 01:11 UTC, weixiang0815 commented on files/zh-tw/learn/html/introduction_to_html/getting_started/index.md
> +1. **起始標籤(opening tag):** 它包含了元素的名字(在這裡是 p)，夾在一對 **<、> (angle brackets)** 之間。它指明元素從何開始生效 — 在上例中則代表段落的開始。
了解，已將有出現此問題的每一行修正，感謝指教

2023-01-26 01:15 UTC, weixiang0815 commented on files/zh-tw/learn/html/introduction_to_html/getting_started/index.md
> +> **備註：** HTML 中的元素是不區分大小寫的。例如：一個 {{htmlelement("title")}} 標籤可以寫成`<title>`、`<TITLE>`、`<Title>`、`<TiTlE>`之類的形式，都沒有問題。通常來說，為了保持一致性(consistency)、可讀性(readability)，以及其他可能的原因，最好還是以小寫來撰寫標籤。
已在新 commit 裡修正，請問那樣修改對嗎？

2023-01-26 01:21 UTC, yin1999 commented on files/zh-tw/learn/html/introduction_to_html/getting_started/index.md
> +> **備註**：空元素有時也被稱作 _void elements。_
```suggestion
> **備註：**空元素有時也被稱作 _void element_。
```

2023-01-26 01:21 UTC, yin1999 commented on files/zh-tw/learn/html/introduction_to_html/getting_started/index.md
> +本文將探討 HTML 最基本的部分。首先，我們將會定義元素（elements）、屬性（attributes）以及其它你可能聽過的重要名詞，然後講解該如何使用它們。我們也會告訴你典型的 HTML 頁面以及其中的元素是如何構成的，以及解釋其他重要的基礎語言特性。在此過程中，我們會撰寫一些 HTML 來引發你的興趣！
```suggestion
本文將探討 HTML 最基本的部分。首先，我們將會定義元素（element）、屬性（attribute）以及其它你可能聽過的重要名詞，然後講解該如何使用它們。我們也會告訴你典型的 HTML 頁面以及其中的元素是如何構成的，以及解釋其他重要的基礎語言特性。在此過程中，我們會撰寫一些 HTML 來引發你的興趣！
```

2023-01-26 01:21 UTC, yin1999 commented on files/zh-tw/learn/html/introduction_to_html/getting_started/index.md
> +> **備註**：HTML 中的元素是不區分大小寫的。例如：一個 {{htmlelement("title")}} 標籤可以寫成 `<title>`、`<TITLE>`、`<Title>`、`<TiTlE>` 之類的形式，都沒有問題。通常來說，為了保持一致性（consistency）、可讀性（readability），以及其他可能的原因，最好還是以小寫來撰寫標籤。
这是特殊的结构，用于文档高亮，https://developer.mozilla.org/zh-CN/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN#%E5%A4%87%E6%B3%A8%E3%80%81%E8%AD%A6%E5%91%8A%E5%92%8C%E6%A0%87%E6%B3%A8

```suggestion
> **備註：** HTML 中的元素是不區分大小寫的。例如：一個 {{htmlelement("title")}} 標籤可以寫成 `<title>`、`<TITLE>`、`<Title>`、`<TiTlE>` 之類的形式，都沒有問題。通常來說，為了保持一致性（consistency）、可讀性（readability），以及其他可能的原因，最好還是以小寫來撰寫標籤。
```

2023-01-26 01:21 UTC, yin1999 commented on files/zh-tw/learn/html/introduction_to_html/getting_started/index.md
> +### 巢狀元素（Nesting elements）
这里与下文中的翻译不一致，请统一。同时，请移除单词的复数形式

```suggestion
### 巢狀元素（Nesting element）
```

2023-01-26 01:21 UTC, yin1999 commented on files/zh-tw/learn/html/introduction_to_html/getting_started/index.md
> +> **備註**：目前，在你要開始學更多有關 HTML 的知識時，你可能也想要探索基礎的 [CSS](/zh-TW/docs/Learn/CSS)(Cascading Style Sheets)。CSS 是一種用來為你的網頁增添花樣的語言，例如改變字型、顏色，或改變頁面的布局。你很快就會發現，同時使用 HTML 和 CSS 會帶來很棒的效果。
同

2023-01-26 02:46 UTC, weixiang0815 commented on files/zh-tw/learn/html/introduction_to_html/getting_started/index.md
> +> **備註**：目前，在你要開始學更多有關 HTML 的知識時，你可能也想要探索基礎的 [CSS](/zh-TW/docs/Learn/CSS)(Cascading Style Sheets)。CSS 是一種用來為你的網頁增添花樣的語言，例如改變字型、顏色，或改變頁面的布局。你很快就會發現，同時使用 HTML 和 CSS 會帶來很棒的效果。
已修正

2023-01-26 02:47 UTC, weixiang0815 commented on files/zh-tw/learn/html/introduction_to_html/getting_started/index.md
> +### 巢狀元素（Nesting elements）
已修正

2023-01-26 02:47 UTC, weixiang0815 commented on files/zh-tw/learn/html/introduction_to_html/getting_started/index.md
> +> **備註**：HTML 中的元素是不區分大小寫的。例如：一個 {{htmlelement("title")}} 標籤可以寫成 `<title>`、`<TITLE>`、`<Title>`、`<TiTlE>` 之類的形式，都沒有問題。通常來說，為了保持一致性（consistency）、可讀性（readability），以及其他可能的原因，最好還是以小寫來撰寫標籤。
了解，已修正

2023-01-26 02:47 UTC, weixiang0815 commented on files/zh-tw/learn/html/introduction_to_html/getting_started/index.md
> +本文將探討 HTML 最基本的部分。首先，我們將會定義元素（elements）、屬性（attributes）以及其它你可能聽過的重要名詞，然後講解該如何使用它們。我們也會告訴你典型的 HTML 頁面以及其中的元素是如何構成的，以及解釋其他重要的基礎語言特性。在此過程中，我們會撰寫一些 HTML 來引發你的興趣！
已修正

2023-01-26 02:47 UTC, weixiang0815 commented on files/zh-tw/learn/html/introduction_to_html/getting_started/index.md
> +> **備註**：空元素有時也被稱作 _void elements。_
已修正

2023-01-26 10:41 UTC, yin1999 approved these changes

2023-01-26 10:41 UTC, merged