feat: translate array/findlast in ko
mdn/translated-content pull request #11274
Opened 2023-01-27 12:38 UTC by sukvvon

### Description

translate web/javascript/reference/global_objects/array/findlast in ko

### Motivation

[Array.prototype.findLast()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findLast) is not translated in ko so i translated

### Additional details

### Related issues and pull requests

2023-01-30 09:12 UTC, wisedog reviewed
담당자는 아니나 리뷰를 진행했습니다. 나머지는 리뷰어분들께서 해주실 예정입니다! 

긴 글 번역하느라 고생 많으셨습니다. 감사합니다. 🙏

2023-01-30 09:12 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/array/findlast/index.md
> +배열 내에서 제공된 테스트 함수를 만족하는 제일 높은 색인 값을 가진 요소의 값입니다. 일치하는 요소가 찾아지지 않을 때 {{jsxref("undefined")}}.
`일치하는 요소를 찾을 수 없을때는 {{jsxref("undefined")}}를 반환합니다. `

정도로 좀 더 의역을 하시면 어떨까요?

2023-01-30 09:12 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/array/findlast/index.md
> +`findLast()` 메서드는 [일반적](/ko/docs/Web/JavaScript/Reference/Global_Objects/Array#generic_array_methods)입니다. 이것은 오직 `length` 특성과 정수 키 특성을 가질 것으로 예상합니다.
`일반적`보다는 MDN 한글 문서에는 `제네릭`이라는 용어를 주로 사용합니다. 

또한 `findLast()`가 제네릭 배열 함수이며 duck typing 을 하는 특성상 이 함수의 동작에는 `length` 속성과 정수 키 속성을 가지는 `this`가 필요하다는 의미로 파악하시면 좀 더 매끄러운 번역이 되지 않을까 합니다. 😁

2023-01-30 09:12 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/array/findlast/index.md
> +#### 화살표 함수와 구조 분해 할당 사용
구조분해는 맞으나 할당은 아니지 않을까요?
구조분해 할당은 명확하게 Destructuring Assignment 라는 용어가 있습니다.

2023-01-30 09:12 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/array/findlast/index.md
> +`findLast()` 메서드는 [반복 메서드](/ko/docs/Web/JavaScript/Reference/Global_Objects/Array#iterative_methods)입니다. 이것은 [참 같은 값](/ko/docs/Glossary/Truthy)이 반환될 때까지 제공된 `callbackFn`을 배열 내에서 각 요소에 내림차순으로 한 번 호출합니
진실된 값 보다는 참 값? 참 같은 값? 이 좋겠습니다.

2023-02-14 02:16 UTC, yujo11 requested changes
안녕하세요 sukvvon님

리뷰가 많이 늦어져서 죄송합니다 🙇‍♂️

몇 가지 코멘트 남겼는데요.

제가 남긴 코멘트와 wisedog님이 남겨주신 코멘트 같이 확인해주시면 감사하겠습니다

2023-02-14 02:16 UTC, yujo11 commented on files/ko/web/javascript/reference/global_objects/array/findlast/index.md
> +배열 내에서 제공된 테스트 함수를 만족하는 제일 높은 색인 값을 가진 요소의 값입니다. 일치하는 요소가 찾아지지 않을 때 {{jsxref("undefined")}}.
wisedog님이 남겨주신 의견에 동의합니다

수정해주시면 좋을거 같아요

2023-02-14 02:16 UTC, yujo11 commented on files/ko/web/javascript/reference/global_objects/array/findlast/index.md
> +#### 화살표 함수와 구조 분해 할당 사용
원문에서도 destructuring으로 사용되니 위에 wsiedog님이 얘기해주신 것처럼 "구조 분해"로 변경해주시면 좋을거 같아요

2023-02-14 02:16 UTC, yujo11 commented on files/ko/web/javascript/reference/global_objects/array/findlast/index.md
> +`callbackFn`은 할당된 값만이 아닌 _모든_ 배열의 색인에 호출됩니다. [성긴 배열](/ko/docs/Web/JavaScript/Guide/Indexed_collections#sparse_arrays) 내의 빈 슬롯은 `undefined`와 동일하게 동작합니다.
이 부분은 논의를 진행하고 있는데요. `희소 배열`이 이라는 용어를 일반적으로 더 많이 사용하는만큼 `희소 배열`로 변경해주시면 좋을거 같습니다.

2023-02-23 15:14 UTC, sukvvon commented
@wisedog @yujo11 모두 반영하여 수정 완료하였습니다! :)

2023-02-25 15:50 UTC, yujo11 approved these changes
고생 많으셨습니다! 👍 👍 👍

2023-02-25 15:50 UTC, merged