Update index.md
mdn/translated-content pull request #11297
Opened 2023-01-29 15:38 UTC by ericfourmaux

Mise à jour et finalisation de la traduction française

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-01-30 09:30 UTC, SphinxKnight commented
Merci @ericfourmaux pour cette PR et félicitations pour cette première.
Je vais relire aujourd'hui ou dans les prochains jours !

2023-01-30 12:37 UTC, SphinxKnight commented
@ericfourmaux je vois que certains éléments sont également à mettre à jour par rapport à la version anglaise courante (qui agit comme référence). Comme cela s'étale sur l'ensemble de la page, plutôt que de passer par des suggestions, puis-je faire une _pull request_ sur votre branche afin de la compléter ? N'hésitez pas à me dire si vous voulez procéder autrement.

2023-02-01 09:46 UTC, SphinxKnight requested changes
cf. https://github.com/ericfourmaux/translated-content/pull/1

2023-02-01 10:48 UTC, ericfourmaux reviewed
Updated links to French version

2023-02-01 11:26 UTC, ericfourmaux reviewed
Removed double spaces

2023-02-15 08:51 UTC, SphinxKnight approved these changes
Merci @ericfourmaux, j'avais oublié de repasser :)

2023-02-15 11:18 UTC, merged