[ja] fix image source
mdn/translated-content pull request #11318
Opened 2023-01-31 00:17 UTC by Nao000

https://developer.mozilla.org/ja/docs/Learn/Server-side/First_steps/Introduction

### Description

画像が読み込めていなかったので、英語版の画像ファイルを読み込むように修正しました。

### Motivation
### Additional details
### Related issues and pull requests

2023-01-31 11:43 UTC, mfuji09 requested changes
英語版の画像を読み込む場合は、パスを記述しないでください。
ファイル名のみを指定すれば、日本語版の画像ファイルがない場合、自動的に英語版の画像ファイルが表示されます。

2023-01-31 13:16 UTC, Nao000 commented
ご確認ありがとうございます。
ファイル名のみを指定するように修正しましたのでお手すきの際にご確認いただければと思います。
193d86a5560ee04396024982709c2dc39766a255

2023-02-05 15:01 UTC, mfuji09 approved these changes
OKです。

2023-02-05 15:01 UTC, merged

2023-02-10 13:23 UTC, Nao000 commented
今見ました。
ご対応ありがとうございました！