Update translation
mdn/translated-content pull request #11310
Opened 2023-01-30 14:36 UTC by YQisme

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-01-30 17:22 UTC, fwqaaq commented on files/zh-cn/glossary/semantics/index.md
> +HTML 应该编写为表示将要填充的数据，而不是基于其默认的演示样式。演示（应该是什么样子），是[CSS](/zh-CN/docs/Web/CSS)的唯一责任。
```suggestion
HTML 应该编写为表示将要填充的数据，而不是基于其默认的演示样式。演示（应该是什么样子），是 [CSS](/zh-CN/docs/Web/CSS) 的唯一责任。
```

2023-01-30 17:22 UTC, fwqaaq commented on files/zh-cn/glossary/semantics/index.md
> +- 搜索引擎将其内容视为影响页面搜索排名的重要关键字 （参见{{ glossary ("SEO")}}）。
```suggestion
- 搜索引擎将其内容视为影响页面搜索排名的重要关键字（参见 {{ glossary ("SEO")}}）。
```

2023-01-30 17:23 UTC, fwqaaq commented on files/zh-cn/glossary/semantics/index.md
> +- 语义命名反映了正确的自定义元素/组件命名
```suggestion
- 语义命名反映了正确的自定义元素/组件命名。
```

2023-01-31 01:25 UTC, yin1999 requested changes
请作出修改

2023-01-31 01:25 UTC, yin1999 commented on files/zh-cn/glossary/semantics/index.md
> +- 比起搜索无休止的带有或不带有语义或命名空间类的 `div`，找到有意义的代码块显然容易得多。
两个或连用存在一定的争议，改成符号表示更好：

```suggestion
- 比起搜索无休止的带有或不带有语义/命名空间类的 `div`，找到有意义的代码块显然容易得多。
```

2023-01-31 01:25 UTC, yin1999 commented on files/zh-cn/glossary/semantics/index.md
> +当接近要使用的标记时，问问自己，“什么元素最能描述/表示我要填充的数据？”例如，它是数据列表吗？；有序，无序？；是否是一篇具有章节和相关信息旁注的文章？；它是否列出了定义？；它是需要标题的图形还是图像？；除了全局网站范围的页眉和页脚之外，它还应该有页眉和页脚吗？；等。
中文标点用法是不会将问号和分号连用的，问号已经表达了一句话的结束，参见 <http://www.moe.gov.cn/ewebeditor/uploadfile/2015/01/13/20150113091548267.pdf>：

```suggestion
当接近要使用的标记时，问问自己，“什么元素最能描述/表示我要填充的数据？”例如，它是数据列表吗？有序或无序？是否是一篇具有章节和相关信息旁注的文章？它是否列出了定义？它是需要标题的图形还是图像？除了全局网站范围的页眉和页脚之外，它还应该有页眉和页脚吗？等等。
```

2023-01-31 01:41 UTC, yin1999 approved these changes

2023-01-31 01:43 UTC, merged

2023-01-31 01:43 UTC, yin1999 commented
Thanks