zh-cn(update): update serviceworkercontainer
mdn/translated-content pull request #11364
Opened 2023-02-02 07:56 UTC by fwqaaq

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-02-02 07:59 UTC, fwqaaq commented on files/zh-cn/web/api/serviceworkercontainer/index.md
> +  - : 提供了一种延迟代码执行直到 service worker 被激活的方法。它返回一个从不会拒绝的 {{jsxref("Promise")}}，并且一直等到与当前页面相关联的 {{domxref("ServiceWorkerRegistration")}} 有一个 {{domxref("ServiceWorkerRegistration.active")}} worker。一旦满足该条件
```suggestion
  - : 提供了一种延迟代码执行直到 service worker 被激活的方法。它返回一个从不会拒绝的 {{jsxref("Promise")}}，并且一直等到与当前页面相关联的 {{domxref("ServiceWorkerRegistration")}} 有一个 {{domxref("ServiceWorkerRegistration.active")}} worker。一旦满足该条件，它将用 {{domxref("ServiceWorkerRegistration")}} 兑现。
```

2023-02-02 08:33 UTC, yin1999 requested changes

2023-02-02 08:33 UTC, yin1999 commented on files/zh-cn/web/api/serviceworkercontainer/index.md
> +更重要的是，它暴露了用于注册 service worker 的 {{domxref("ServiceWorkerContainer.register", "ServiceWorkerContainer.register()")}} 方法，并且用于确定当前页面是否受到主动控制的 {{domxref("ServiceWorkerContainer.controller")}} 属性。
名词间用并且不太合适吧，不通顺：

```suggestion
更重要的是，它暴露了用于注册 service worker 的 {{domxref("ServiceWorkerContainer.register", "ServiceWorkerContainer.register()")}} 方法，和用于确定当前页面是否受到主动控制的 {{domxref("ServiceWorkerContainer.controller")}} 属性。
```

2023-02-02 08:37 UTC, fwqaaq commented on files/zh-cn/web/api/serviceworkercontainer/index.md
> +  - : 如果 ServiceWorker 对象的状态是 `activating` 或 `activated` 的时候（与 {{domxref("ServiceWorkerRegistration.active")}} 返回相同的对象），则返回 {{domxref("ServiceWorker")}} 对象。在强制刷新请求（_Shift_ + refresh）或者没有激活的 worker 的时
```suggestion
  - : 如果 ServiceWorker 对象的状态是 `activating` 或 `activated`（与 {{domxref("ServiceWorkerRegistration.active")}} 返回相同的对象），则返回 {{domxref("ServiceWorker")}} 对象。在强制刷新请求（_Shift_ + refresh）或者没有激活的 worker 的时候，该属性返回 `null`。
```

2023-02-02 08:40 UTC, fwqaaq commented on files/zh-cn/web/api/serviceworkercontainer/index.md
> +  - : 显示地启动，从 service worker 分发到其控制页面下的消息流（例如，通过 {{domxref("Client.postMessage()")}} 发送）。这可用于更早地对发送的消息做出反应，甚至在该页面的内容内容加载完成之前。
```suggestion
  - : 显示地启动，从 service worker 分发到其控制页面下的消息流（例如，通过 {{domxref("Client.postMessage()")}} 发送）。这可用于更早地对发送的消息做出反应，甚至在该页面的内容加载完成之前。
```

2023-02-03 00:32 UTC, yin1999 requested changes

2023-02-03 00:32 UTC, yin1999 commented on files/zh-cn/web/api/serviceworkercontainer/index.md
> +  - : 当文档关联的 {{domxref("ServiceWorkerRegistration")}} 获得新的 {{domxref("ServiceWorkerRegistration.active","active")}} worker 时触发。
```suggestion
  - : 当文档关联的 {{domxref("ServiceWorkerRegistration")}} 获得新{{domxref("ServiceWorkerRegistration.active","激活", "", 1)}}的 worker 时触发。
```

2023-02-03 00:32 UTC, yin1999 commented on files/zh-cn/web/api/serviceworkercontainer/index.md
> +  - : 每当关联的 service worker 出现错误时都会触发。
```suggestion
  - : 每当关联的 service worker 出现错误时触发。
```

2023-02-03 00:32 UTC, yin1999 commented on files/zh-cn/web/api/serviceworkercontainer/index.md
> +  - : 当 {{domxref("ServiceWorkerContainer")}} 对象收到传入的消息时，触发（例如，通过 {{domxref("MessagePort.postMessage()")}} 调用）。
```suggestion
  - : 当 {{domxref("ServiceWorkerContainer")}} 对象收到传入的消息时触发（例如，通过 {{domxref("MessagePort.postMessage()")}} 调用）。
```

2023-02-03 00:32 UTC, yin1999 commented on files/zh-cn/web/api/serviceworkercontainer/index.md
> +以下示例首先检查浏览器是否支持 service worker。如果支持，代码将注册 service worker，并确定页面是否由 service worker 主动控制。如果不是，它会提示用户重新加载页面，以便 service worker 可以控制。该代码还报告任何失败的注册。
```suggestion
以下示例首先检查浏览器是否支持 service worker。如果支持，代码将注册 service worker，并确定页面是否由 service worker 控制。如果不是，它会提示用户重新加载页面，以便 service worker 可以控制。该代码还将报告任何注册的错误。
```

2023-02-03 00:35 UTC, yin1999 commented on files/zh-cn/web/api/serviceworkercontainer/index.md
> +  - : 显示地启动，从 service worker 分发到其控制页面下的消息流（例如，通过 {{domxref("Client.postMessage()")}} 发送）。这可用于更早地对发送的消息做出反应，甚至在该页面的内容加载完成之前。
```suggestion
  - : 显式启动从 service worker 分发到其控制页面下的消息流（例如，通过 {{domxref("Client.postMessage()")}} 发送）。这可用于更早地对发送的消息做出反应，甚至在该页面的内容加载完成之前。
```

2023-02-03 00:36 UTC, yin1999 approved these changes

2023-02-03 06:16 UTC, merged