[ko] JavaScript: RegExp.protytype.flags 추가 외
mdn/translated-content pull request #11428
Opened 2023-02-05 23:00 UTC by wisedog

- RegExp.prototype.flags 추가
- RegExp.prototype.ignorecase 추가

2023-02-14 02:25 UTC, yujo11 requested changes
안녕하세요 wisedog님 간단한 코멘트 하나 남겼는데 확인 부탁드리겠습니다!

2023-02-14 02:25 UTC, yujo11 commented on files/ko/web/javascript/reference/global_objects/regexp/flags/index.md
> +`flags`의 설정 접근자가 `undefined`라면 이 속성을 직접 변경할 수 없습니다.
영어 원문에는 "The set accessor of flags is undefined. You cannot change this property directly."라고 되어 있는데요.

"`undefiend`라면 "보다는 "`flags`의 set 접근자는 정의되지 않았습니다. 이 속성을 직접 변경할 수 없습니다." 라고 번역 되는게 문맥상 맞는거 같은데 이 부분 의견 주시면 감사하겠습니다

2023-02-14 23:12 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/regexp/flags/index.md
> +`flags`의 설정 접근자가 `undefined`라면 이 속성을 직접 변경할 수 없습니다.
말씀 감사합니다. 제안해주신 번역이 문맥상 맞습니다. 수정하겠습니다.

2023-02-16 14:24 UTC, yujo11 approved these changes

2023-02-16 14:24 UTC, merged