[ko] JavaScript: BigUint64Array,BigUInt64Array()추가
mdn/translated-content pull request #11519
Opened 2023-02-08 23:49 UTC by wisedog

- BigUint64Array 설명 추가
- BigUint64Array() 추가

2023-02-18 14:42 UTC, hochan222 requested changes
@wisedog 님 안녕하세요.

고생 많으셨습니다! 리뷰 사항 확인 한번 부탁드립니다 :)

2023-02-18 14:42 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/biguint64array/biguint64array/index.md
> +slug: Web/JavaScript/Reference/Global_Objects/BigUint64Array/BigUint64Array
```suggestion
slug: Web/JavaScript/Reference/Global_Objects/BigUint64Array/BigUint64Array
l10n:
	  sourceCommit: effd5de5e42bfe045c3bf44b2d7b14f4d6146785
```

2023-02-18 14:42 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/biguint64array/index.md
> +slug: Web/JavaScript/Reference/Global_Objects/BigUint64Array
```suggestion
slug: Web/JavaScript/Reference/Global_Objects/BigUint64Array
l10n:
	  sourceCommit: effd5de5e42bfe045c3bf44b2d7b14f4d6146785
```

2023-02-18 14:42 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/biguint64array/biguint64array/index.md
> +**`BigUint64Array()`** 생성자는 플랫폼의 바이트 순서를 따르는 64비트 부호없는 정수의 형식화 배열(TypedArray)
```suggestion
**`BigUint64Array()`** 생성자는 플랫폼의 바이트 순서를 따르는 64비트 부호 없는 정수의 형식화 배열(TypedArray)
```

2023-02-19 07:23 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/biguint64array/biguint64array/index.md
> +[`TypedArray`](/en/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#parameters)를 참조하세요.
아앗...

2023-02-19 07:23 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/biguint64array/biguint64array/index.md
> +slug: Web/JavaScript/Reference/Global_Objects/BigUint64Array/BigUint64Array
감사합니다. 기존 소스커밋을 다 찾아넣으려니 오픈된게 많아서 -ㅁ-

2023-02-19 10:47 UTC, hochan222 approved these changes
빠른 반영 감사합니다! 좋은 하루 보내세요 :)

2023-02-19 10:47 UTC, merged