feat: translate contentvisibilityautostatechange in zh-cn
mdn/translated-content pull request #11535
Opened 2023-02-09 07:28 UTC by LockingReal

Provide Chinese translation for content visibility autostatechange,this api has updated

### Related issues and pull requests

https://github.com/mdn/content/pull/24263

2023-02-09 07:30 UTC, LockingReal commented
I also want to take this opportunity to better understand the process and details of mdn contribution translation so as to make more contributions in the future ~~😝🦾

2023-02-09 07:35 UTC, yin1999 commented
> Provide Chinese translation for 【contentvisibilityautostatechange】this api has updated

Please pin me after the en-US updates are applied :) thanks for your contribution

2023-02-09 07:43 UTC, LockingReal commented
> > Provide Chinese translation for 【contentvisibilityautostatechange】this api has updated
> 
> Please pin me after the en-US updates are applied :) thanks for your contribution

ok~~🍻

2023-02-10 23:59 UTC, yin1999 requested changes
请对照英文文档更新内容，https://github.com/mdn/content/blob/main/files/en-us/web/api/contentvisibilityautostatechangeevent/index.md

同时，请阅读[简体中文翻译指南](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md)更正常见的问题

2023-02-10 23:59 UTC, yin1999 commented on files/zh-cn/web/api/contentvisibilityautostatechangeevent/index.md
> +browser-compat: api.ContentVisibilityAutoStateChangeEvent
请移除：

```suggestion
```

2023-02-10 23:59 UTC, yin1999 commented on files/zh-cn/web/api/contentvisibilityautostatechangeevent/index.md
> +user](https://www.w3.org/TR/css-contain-2/#relevant-to-the-user)，当元素的呈现状态由于任何使元素与用户相关的属性而发生变化时，该事件将在元素上触发。
这里的翻译还需修改

2023-02-10 23:59 UTC, yin1999 commented on files/zh-cn/web/api/contentvisibilityautostatechangeevent/index.md
> +- The {{cssxref("contain")}} property
请翻译

2023-02-10 23:59 UTC, yin1999 commented on files/zh-cn/web/api/contentvisibilityautostatechangeevent/index.md
> +  - : 构造一个 `ContentVisibilityAutoStateChangeEvent` 实例e.
注意标点

2023-02-10 23:59 UTC, yin1999 commented on files/zh-cn/web/api/contentvisibilityautostatechangeevent/index.md
> +// Call this when the canvas updates need to stop.
可以的话，请翻译注释

2023-02-11 03:45 UTC, LockingReal commented on files/zh-cn/web/api/contentvisibilityautostatechangeevent/index.md
> +// Call this when the canvas updates need to stop.
ok，感谢老哥的review，我这将逐一进行更改😁

2023-02-11 06:00 UTC, LockingReal commented
@yin1999 老哥很奇怪，我好像rebase了一下main，提交就成这样了，你再看看嘞，又在web/api/element下补充了一个

2023-02-11 06:04 UTC, closed without merging

2023-02-11 06:24 UTC, yin1999 commented
> @yin1999 老哥很奇怪，我好像rebase了一下main，提交就成这样了，你再看看嘞，又在web/api/element下补充了一个

若没有冲突，请不要使用 rebase。有冲突需要解决的话，用 merge 命令就行