fix:  translation error
mdn/translated-content pull request #11558
Opened 2023-02-10 08:45 UTC by zybieku

en:
The actual space taken up by the box
zhch:
标准模型的实际占用宽度
reason:
'The actual space taken up by the box' should be translated into '标准模型实际占用宽度' The 宽度 in Chinese generally refers to the width attribute of css

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-02-10 09:04 UTC, yin1999 requested changes

2023-02-10 09:04 UTC, yin1999 commented on files/zh-cn/learn/css/building_blocks/the_box_model/index.md
> +如果使用标准模型,实际占用宽度 = 410px (350 + 25 + 25 + 5 + 5)，高度 = 210px (150 + 25 + 25 + 5 + 5)，padding 加 border 再加 content box。
Actual space是实际占用空间，而不是宽度，空间包含宽度和高度两个属性，请修改翻译。同时，请使用全角的逗号

2023-02-11 02:46 UTC, zybieku commented on files/zh-cn/learn/css/building_blocks/the_box_model/index.md
> +如果使用标准模型,实际占用宽度 = 410px (350 + 25 + 25 + 5 + 5)，高度 = 210px (150 + 25 + 25 + 5 + 5)，padding 加 border 再加 content box。
已经修改

2023-02-11 02:49 UTC, yin1999 commented on files/zh-cn/learn/css/building_blocks/the_box_model/index.md
> +如果使用标准模型，实际占用空间的宽高分别为：宽度 = 410px (350 + 25 + 25 + 5 + 5)，高度 = 210px (150 + 25 + 25 + 5 + 5)，即 padding 加 border 再加 content box。
英文文档已移除后半句内容

```suggestion
如果使用标准模型，实际占用空间的宽高分别为：宽度 = 410px (350 + 25 + 25 + 5 + 5)，高度 = 210px (150 + 25 + 25 + 5 + 5)。
```

2023-02-11 02:49 UTC, yin1999 commented on files/zh-cn/learn/css/building_blocks/the_box_model/index.md
>  ![Showing the size of the box when the standard box model is being used.](standard-box-model.png)
```suggestion

![Showing the size of the box when the standard box model is being used.](standard-box-model.png)
```

2023-02-11 02:50 UTC, yin1999 approved these changes

2023-02-11 02:52 UTC, merged