[ko] CSP: worker-src
mdn/translated-content pull request #11560
Opened 2023-02-10 10:23 UTC by SnowMarble

2023-02-13 14:16 UTC, cos18 requested changes
기여 감사드립니다! 리뷰 내용 확인해주시고 수정 부탁드립니다 :)

2023-02-14 08:24 UTC, SnowMarble commented on files/ko/web/http/headers/content-security-policy/worker-src/index.md
> +  soruceCommit: 45c7ae13178203b4ee58842efbe2a27deab274a6
[메인 브렌치](https://github.com/mdn/content/commits/main/files/en-us/web/http/headers/content-security-policy/worker-src/index.md)에서 봤을 때 최상단에 있는 [커밋](https://github.com/mdn/content/commit/45c7ae13178203b4ee58842efbe2a27deab274a6)인데, 저도 sourceCommit을 넣어보는게 아직 익숙하지 않아서 조금 헷갈리네요😓. 한번만 더 확인해주실 수 있을까요?
![image](https://user-images.githubusercontent.com/69508345/218678904-fa655810-0382-4a21-87ca-4ed050f1512a.png)

2023-02-17 07:51 UTC, SnowMarble commented on files/ko/web/http/headers/content-security-policy/worker-src/index.md
> +  soruceCommit: 45c7ae13178203b4ee58842efbe2a27deab274a6
@cos18

2023-02-21 16:16 UTC, cos18 commented on files/ko/web/http/headers/content-security-policy/worker-src/index.md
> +  soruceCommit: 45c7ae13178203b4ee58842efbe2a27deab274a6
늦은 확인 죄송합니다 ㅠㅠ 제가 잘못된 경로로 접근했는지 커밋 기준 최상단 커밋 해쉬값임을 확인했습니다. 번거롭게 다시 확인하게 요청드려서 죄송합니다 ㅠㅠ

2023-02-21 16:31 UTC, cos18 approved these changes
LGTM! 기여 감사합니다 :)

2023-02-21 16:55 UTC, merged