[ko] JavaScript: TypedArray.prototype.every(), forEach()
mdn/translated-content pull request #11572
Opened 2023-02-11 08:44 UTC by wisedog

- TypedArray.prototype.every() 추가
- TypedArray.prototype.forEach() 추가

2023-02-18 15:05 UTC, hochan222 requested changes
@wisedog 님 안녕하세요.

고생 많으셨습니다! 리뷰 사항 확인 한번 부탁드립니다 :)

2023-02-18 15:05 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/typedarray/every/index.md
> +`every`는 `callbackFn`이 {{Glossary("falsy")}}을 반환하는 요소를 찾을때까지 형식화 배열에 있는
```suggestion
`every`는 `callbackFn`이 {{Glossary("falsy")}}을 반환하는 요소를 찾을 때까지 형식화 배열에 있는
```

2023-02-18 15:05 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/typedarray/foreach/index.md
> +  - : 각 요소에 대해 실행할 함수. 다음 세 가지 매개변수를 받습니다.
```suggestion
  - : 각 요소에 대해 실행할 함수.
  
    다음 세 가지 매개변수를 받습니다.
```

2023-02-19 23:41 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/typedarray/every/index.md
> +  - : 각 요소를 시험할 함수. 다음 세 가지 인수를 받습니다.
좋은 의견 감사합니다.

2023-02-19 23:42 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/typedarray/every/index.md
> +      - : `every`를 호출한 형식화 배열
원문에 따라 붙이도록 하겠습니다. bullet list 의 경우 제가 붙일때도 있고 안 붙일때도 있는데 이 부분을 신경써야겠군요!

2023-03-04 09:28 UTC, hochan222 approved these changes
알림에서 지워져서 늦게 확인하게 되었네요 ㅜㅜ 

고생 많으셨습니다. 좋은 주말 보내세요 :)

2023-03-04 09:28 UTC, merged