[zh-cn] Update glossary/domain
mdn/translated-content pull request #11570
Opened 2023-02-11 03:44 UTC by jasonren0403

### Description

Update untranslated content.

### Motivation

### Additional details

### Related issues and pull requests

2023-02-11 03:45 UTC, jasonren0403 commented on files/zh-cn/glossary/domain/index.md
> +域是互联网中控制其自身资源的机构。它的“域名”是在 {{Glossary("URL")}} 中作为层次结构的一部分来称呼这个机构的一种方式，通常是其中最令人难忘的部分，例如品牌名称。
```suggestion
域是互联网中控制其自身资源的机构。它的“域名”部分是在 {{Glossary("URL")}} 中作为层次结构的一部分来称呼这个机构的一种方式，通常是其中最令人难忘的部分，例如品牌名称。
```

2023-02-11 03:45 UTC, jasonren0403 commented on files/zh-cn/glossary/domain/index.md
> +2. “mozilla”是域名。如果你需要拥有一个域名，你必须在[注册商](https://zh.wikipedia.org/wiki/域名注册商)中注册。在顶级域域名注册商委派下，注册商可以为你注册域名。
```suggestion
2. “mozilla”是域名。如果你需要拥有一个域名，必须在[注册商](https://zh.wikipedia.org/wiki/域名注册商)中注册。在顶级域域名注册商委派下，注册商可以为你注册域名。
```

2023-02-11 04:01 UTC, yin1999 commented on files/zh-cn/glossary/domain/index.md
> +- 维基百科词条[域](https://zh.wikipedia.org/wiki/域)
```suggestion
- 维基百科词条[域名](https://zh.wikipedia.org/wiki/域名)
```

2023-02-11 04:33 UTC, jasonren0403 commented on files/zh-cn/glossary/domain/index.md
> +一个全限定域名（FQDN）包含可以使用互联网的{{Glossary("DNS","域名系统")}}毫不含糊地按名称查询该机构的所有必要部分。
```suggestion
一个全限定域名（FQDN）包含可以使用互联网的{{Glossary("DNS","域名系统")}}明确地按名称查询该机构的所有必要部分。
```

2023-02-11 04:42 UTC, jasonren0403 commented on files/zh-cn/glossary/domain/index.md
> +域是互联网中控制其自身资源的机构。它的“域名”部分是在 {{Glossary("URL")}} 中作为层次结构的一部分来称呼这个机构的一种方式，通常是其中最令人难忘的部分，例如品牌名称。
```suggestion
域是互联网中控制其自身资源的机构。它的“域名”部分是通过 {{Glossary("URL")}} 层次结构的一部分称呼这个机构的方式。域名通常是 URL 中最令人难忘的地方，例如品牌名称。
```

2023-02-11 05:14 UTC, yin1999 commented on files/zh-cn/glossary/domain/index.md
> +域是互联网中控制其自身资源的机构。它的“域名”部分是在 {{Glossary("URL")}} 中作为层次结构的一部分来称呼这个机构的一种方式，通常是其中最令人难忘的部分，例如品牌名称。
关于 "authority" 一词的翻译还需考虑，我没有找到特别合适的，有将其翻译为“权威”的。但平时没怎么遇到过。

https://ahrefs.com/zh/website-authority-checker

2023-02-11 10:10 UTC, jasonren0403 commented on files/zh-cn/glossary/domain/index.md
> +域是互联网中控制其自身资源的机构。它的“域名”部分是在 {{Glossary("URL")}} 中作为层次结构的一部分来称呼这个机构的一种方式，通常是其中最令人难忘的部分，例如品牌名称。
我想不出更好的建议了，但第一句话“域是...机构”感觉是得稍微改改

2023-02-12 22:51 UTC, awxiaoxian2020 requested changes

2023-02-12 22:51 UTC, awxiaoxian2020 commented on files/zh-cn/glossary/domain/index.md
> +域是互联网中控制其自身资源的机构。它的“域名”部分是在 {{Glossary("URL")}} 中作为层次结构的一部分来称呼这个机构的一种方式，通常是其中最令人难忘的部分，例如品牌名称。
```suggestion
域是互联网中控制其自身资源的“代表”（authority，有时被直译为“权威” ）。它的“域名”部分是 {{Glossary("URL")}} 层次结构的一部分，是对“代表”的称呼。域名通常是 URL 中最令人难忘的地方，例如品牌名称。
```

2023-02-13 15:12 UTC, yin1999 approved these changes

2023-02-13 15:12 UTC, merged