[zh-cn] Update attribute/rel
mdn/translated-content pull request #11574
Opened 2023-02-11 15:36 UTC by jasonren0403

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-02-11 15:36 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +`rel' 属性与 {{htmlelement('link')}}、{{htmlelement('a')}}、{{htmlelement('area')}} 和 {{htmlelement('form')}} 元素有关，但有些值只与这些元素的子集有关。像所有的 HTML 关键字属性值一样，这些值是不区分大小写的。
```suggestion
`rel` 属性与 {{htmlelement('link')}}、{{htmlelement('a')}}、{{htmlelement('area')}} 和 {{htmlelement('form')}} 元素有关，但有些值只与这些元素的子集有关。像所有的 HTML 关键字属性值一样，这些值是不区分大小写的。
```

2023-02-11 15:37 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +  - : 与 {{htmlelement('form')}}、{{htmlelement('a')}} 和 {{htmlelement('area')}} 元素相关，包括这个值使得 referrer 未知（不会包含 `Referer` 标头），并创建一个顶级的浏览上下文，就像 `noopener' 也被设置一样。
```suggestion
  - : 与 {{htmlelement('form')}}、{{htmlelement('a')}} 和 {{htmlelement('area')}} 元素相关，包括这个值使得 referrer 未知（不会包含 `Referer` 标头），并创建一个顶级的浏览上下文，就像 `noopener` 也被设置一样。
```

2023-02-11 15:43 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    > **备注：** 在 Firefox 83 之前，[crossorigin](/zh-CN/docs/Web/HTML/Attributes/crossorigin)属性不支 持`rel="icon"`，也有 [Chrome 的一个开放问题](https://bugs.chromium.org/p/chromium/issues/detail?id=1121645)。
```suggestion
    > **备注：** 在 Firefox 83 之前，[crossorigin](/zh-CN/docs/Web/HTML/Attributes/crossorigin)属性不支持 `rel="icon"`，也有 [Chrome 的一个开放问题](https://bugs.chromium.org/p/chromium/issues/detail?id=1121645)。
```

2023-02-11 15:44 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    如果有多个 `<link rel="icon">`，浏览器会使用它们的 [`media`]（媒体）[`type`](/zh-CN/docs/Web/HTML/Element/link#attr-type) 和 [`size`]（尺寸）属性来选择最合适的图标。如果几个图标同样合适，则使用最后一个。如果后来发现最合适的图标不合适，例如使用了不支持的格式，浏览器就会继续选择下一个最合适的，以此
原文 media(media)和 sizes(sizes) 属性链接不存在

2023-02-11 15:44 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    > **备注：** 苹果的 iOS 系统不使用这种链接类型，也不像其他移动浏览器那样使用 [`size`](size)属性，来选择网页夹或启动占位符的网页图标。
原文sizes属性链接不存在

2023-02-11 15:45 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +  - : 在 {{HTMLElement("a")}}、{{HTMLElement("area")}}、{{HTMLElement("form")}}、 {{HTMLElement("link")}} 元素上有效，`license` 值表示该超链接指向描述许可信息的文件；当前文件的主要内容被引用文件描述的版权许可所覆盖。如果不在{ {HTMLElement("head")}} 元素内，标准并不
```suggestion
  - : 在 {{HTMLElement("a")}}、{{HTMLElement("area")}}、{{HTMLElement("form")}}、 {{HTMLElement("link")}} 元素上有效，`license` 值表示该超链接指向描述许可信息的文件；当前文件的主要内容被引用文件描述的版权许可所覆盖。如果不在 {{HTMLElement("head")}} 元素内，标准并不区分适用于文档特定部分的超链接还是适用于整个文档的超链接。只有页面上的数据可以表明这一点。
```

2023-02-11 15:46 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    当与 [alternate](#alternate) 关键字一起使用时，它定义了一个替代的样式表。在这种情况下，包括一个非空的 [`title`]（类型）。
原文 `[title](type)` 链接不存在

2023-02-11 15:47 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +  - : 指定用户代理必须根据 [`as`]（as）属性给出的潜在目的地（以及与相应目的地相关的优先级），为当前导航预先获取和缓存目标资源。参见 [`preload`](/zh-CN/docs/Web/HTML/Attributes/rel/preload) 值的页面。
原文 `[as](as)` 链接不存在

2023-02-11 15:48 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    如果媒体与 [`media`](media) 属性的值不匹配，外部样式表将不会被使用，甚至不会下载。
原文media链接不存在

2023-02-12 04:40 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    如果有多个 `<link rel="icon">`，浏览器会使用它们的 [`media`]（媒体）[`type`](/zh-CN/docs/Web/HTML/Element/link#attr-type) 和 [`size`]（尺寸）属性来选择最合适的图标。如果几个图标同样合适，则使用最后一个。如果后来发现最合适的图标不合适，例如使用了不支持的格式，浏览器就会继续选择下一个最合适的，以此
```suggestion
    如果有多个 `<link rel="icon">`，浏览器会使用它们的 [`media`](media) [`type`](/zh-CN/docs/Web/HTML/Element/link#attr-type) 和 [`sizes`](sizes) 属性来选择最合适的图标。如果几个图标同样合适，则使用最后一个。如果后来发现最合适的图标不合适，例如使用了不支持的格式，浏览器就会继续选择下一个最合适的，以此类推。
```

2023-02-12 04:40 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    > **备注：** 苹果的 iOS 系统不使用这种链接类型，也不像其他移动浏览器那样使用 [`size`](size)属性，来选择网页夹或启动占位符的网页图标。
```suggestion
    > **备注：** 苹果的 iOS 系统不使用这种链接类型，也不像其他移动浏览器那样使用 [`sizes`](sizes) 属性，来选择网页夹或启动占位符的网页图标。
```

2023-02-12 04:40 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    当与 [alternate](#alternate) 关键字一起使用时，它定义了一个替代的样式表。在这种情况下，包括一个非空的 [`title`]（类型）。
```suggestion
    当与 [alternate](#alternate) 关键字一起使用时，它定义了一个替代的样式表。在这种情况下，包括一个非空的 [`title`](type)。
```

2023-02-12 04:40 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +  - : 指定用户代理必须根据 [`as`]（as）属性给出的潜在目的地（以及与相应目的地相关的优先级），为当前导航预先获取和缓存目标资源。参见 [`preload`](/zh-CN/docs/Web/HTML/Attributes/rel/preload) 值的页面。
```suggestion
  - : 指定用户代理必须根据 [`as`](as) 属性给出的潜在目的地（以及与相应目的地相关的优先级），为当前导航预先获取和缓存目标资源。参见 [`preload`](/zh-CN/docs/Web/HTML/Attributes/rel/preload) 值的页面。
```

2023-02-12 04:42 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +| [`alternate`](#attr-alternate)                                       | 当前文件的替代描述。
```suggestion
| [`alternate`](#attr-alternate)                                       | 当前文档的替代描述。                                                                                                                                                                                                                                           | 链接                      | 链接                                                 | 不允许               |
```

2023-02-12 04:43 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +| [`external`](#attr-external)                                         | 引用的文件与当前的文件不属于同一个站点。
```suggestion
| [`external`](#attr-external)                                         | 引用的文档与当前的文档不属于同一个站点。                                                                                                                                                                                                                | 不允许               | 注解                                           | 注解                |
```

2023-02-12 04:44 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +| [`prev`](#attr-prev)                                                 | 表示当前文档是一个系列的一部分，该系列中的上一个文件是被引用的文件。
```suggestion
| [`prev`](#attr-prev)                                                 | 表示当前文档是系列的一部分，被引用的文档是该系列中的上一个文档。                                                                                                                                                           | 链接                      | 链接                                                 | 链接                      |
```

2023-02-12 04:45 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +| [`next`](#attr-next)                                                 | 表示当前文档是一个系列的一部分，该系列中的下一个文件是被引用的文件。
```suggestion
| [`next`](#attr-next)                                                 | 表示当前文档是一个系列的一部分，被引用的文档是该系列中的下一个文档。                                                                                                                                                               | 链接                      | 链接                                                 | 链接                      |
```

2023-02-12 13:48 UTC, yin1999 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    如果有多个 `<link rel="icon">`，浏览器会使用它们的 [`media`]（媒体）[`type`](/zh-CN/docs/Web/HTML/Element/link#attr-type) 和 [`size`]（尺寸）属性来选择最合适的图标。如果几个图标同样合适，则使用最后一个。如果后来发现最合适的图标不合适，例如使用了不支持的格式，浏览器就会继续选择下一个最合适的，以此
html 元素属性的链接为也没怎么处理过，如果不清楚咋去解决的话，麻烦在 mdn/content 中开一个issue,报告这些错误链接，我们再同步修改

2023-02-12 14:53 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    如果有多个 `<link rel="icon">`，浏览器会使用它们的 [`media`]（媒体）[`type`](/zh-CN/docs/Web/HTML/Element/link#attr-type) 和 [`size`]（尺寸）属性来选择最合适的图标。如果几个图标同样合适，则使用最后一个。如果后来发现最合适的图标不合适，例如使用了不支持的格式，浏览器就会继续选择下一个最合适的，以此
issue 已开（https://github.com/mdn/content/issues/24366）
这边自己先转draft了

2023-02-15 06:52 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +| `rel` 值                                                          | 描述
```suggestion
| `rel` 值                                                          | 描述                                                                                                                                                                                                                                                                                  | {{htmlelement('link')}} | {{htmlelement('a')}} 和 {{htmlelement('area')}} | {{htmlelement('form')}} |
```

2023-02-15 06:54 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    如果有多个 `<link rel="icon">`，浏览器会使用它们的 [`media`]（媒体）[`type`](/zh-CN/docs/Web/HTML/Element/link#attr-type) 和 [`size`]（尺寸）属性来选择最合适的图标。如果几个图标同样合适，则使用最后一个。如果后来发现最合适的图标不合适，例如使用了不支持的格式，浏览器就会继续选择下一个最合适的，以此
```suggestion
    如果有多个 `<link rel="icon">`，浏览器会使用它们的 [`media`](/zh-CN/docs/Web/HTML/Element/link#attr-media) [`type`](/zh-CN/docs/Web/HTML/Element/link#attr-type) 和 [`sizes`](/zh-CN/docs/Web/HTML/Element/link#attr-sizes) 属性来选择最合适的图标。如果几个图标同样合适，则使用最后一个。如果后来发现最合适的图标不合适，例如使用了不支持的格式，浏览器就会继续选择下一个最合适的，以此类推。
```

2023-02-15 06:55 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    > **备注：** 苹果的 iOS 系统不使用这种链接类型，也不像其他移动浏览器那样使用 [`size`](size)属性，来选择网页夹或启动占位符的网页图标。
```suggestion
    > **备注：** 苹果的 iOS 系统不使用这种链接类型，也不像其他移动浏览器那样使用 [`sizes`](/zh-CN/docs/Web/HTML/Element/link#attr-sizes) 属性，来选择网页夹或启动占位符的网页图标。
```

2023-02-15 06:56 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    这与 [opener](#opener) 具有的含义相反。
```suggestion
    这与 [`opener`](#attr-opener) 具有的含义相反。
```

2023-02-15 06:56 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +  - : 指定用户代理必须根据 [`as`]（as）属性给出的潜在目的地（以及与相应目的地相关的优先级），为当前导航预先获取和缓存目标资源。参见 [`preload`](/zh-CN/docs/Web/HTML/Attributes/rel/preload) 值的页面。
```suggestion
  - : 指定用户代理必须根据 [`as`](/zh-CN/docs/Web/HTML/Element/link#attr-as) 属性给出的潜在目的地（以及与相应目的地相关的优先级），为当前导航预先获取和缓存目标资源。参见 [`preload`](/zh-CN/docs/Web/HTML/Attributes/rel/preload) 值的页面。
```

2023-02-15 06:57 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +  - : 与 [next](#next) 关键字类似，与 {{htmlelement('form')}}、{{htmlelement('link')}}、{{htmlelement('a')}} 和 {{htmlelement('area')}} 元素相关，`prev` 值表示当前文档是一个系列的一部分，而链接引用该系列中的一个先前文档就是被引用的文档。
```suggestion
  - : 与 [`next`](#attr-next) 关键字类似，与 {{htmlelement('form')}}、{{htmlelement('link')}}、{{htmlelement('a')}} 和 {{htmlelement('area')}} 元素相关，`prev` 值表示当前文档是一个系列的一部分，而链接引用该系列中的一个先前文档就是被引用的文档。
```

2023-02-15 06:58 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    当与 [alternate](#alternate) 关键字一起使用时，它定义了一个替代的样式表。在这种情况下，包括一个非空的 [`title`]（类型）。
```suggestion
    当与 [`alternate`](#attr-alternate) 关键字一起使用时，它定义了一个替代的样式表。在这种情况下，包括一个非空的 [`title`](/zh-CN/docs/Web/HTML/Element/link#attr-title)。
```

2023-02-15 06:58 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    如果媒体与 [`media`](media) 属性的值不匹配，外部样式表将不会被使用，甚至不会下载。
```suggestion
    如果媒体与 [`media`](/zh-CN/docs/Web/HTML/Element/link#attr-media) 属性的值不匹配，外部样式表将不会被使用，甚至不会下载。
```

2023-02-15 07:05 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +| [`dns-prefetch`](/zh-CN/docs/Web/HTML/Attributes/rel/dns-prefetch)   | 告知浏览器为目标资源的来源预先执行DNS解析。
```suggestion
| [`dns-prefetch`](/zh-CN/docs/Web/HTML/Attributes/rel/dns-prefetch)   | 告知浏览器为目标资源的来源预先执行 DNS 解析。                                                                                                                                                                                                    | 外部资源         | 不允许                                          | 不允许               |
```

2023-02-15 07:07 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +      - 如果一起给出 `type` 和 `alternate` 一起给出，它表示被引用的文件是一种替代格式（如 PDF）。
```suggestion
      - 如果一起给出 `type` 和 `alternate`，它表示被引用的文件是一种替代格式（如 PDF）。
```

2023-02-15 07:08 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +  - : 在 {{htmlelement('body')}} 和 {{htmlelement('head')}} 元素内与 {{htmlelement('link')}} 元素相关。它告诉浏览器为目标资源的来源预先执行 DNS 解析。对于用户可能需要的资源来说，它有助于减少延迟，从而提高用户访问资源时的性能，因为浏览器会预先对指定资源的来源进行 DNS 解析。参见[资源提示](https://
```suggestion
  - : 在 {{htmlelement('body')}} 和 {{htmlelement('head')}} 元素内与 {{htmlelement('link')}} 元素相关。它告诉浏览器为目标资源的来源预先执行 DNS 解析。对于用户可能需要的资源来说，它有助于减少延迟，从而提高用户访问资源时的性能，因为浏览器会预先对指定资源的来源进行 DNS 解析。参见[资源提示](https://w3c.github.io/resource-hints/)中描述的 [dns-prefetch](/zh-CN/docs/Web/Performance/dns-prefetch)。
```

2023-02-15 07:09 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    如果 [`type`](/zh-CN/docs/Web/HTML/Element/link#attr-type) 属性被设置为`application/opensearchdescription+xml`，则该资源是一个 [OpenSearch](/zh-CN/docs/Web/OpenSearch) 插件，可以很容易地添加到一些浏览器（如 Firefox 或 Internet Expl
```suggestion
    如果 [`type`](/zh-CN/docs/Web/HTML/Element/link#attr-type) 属性被设置为 `application/opensearchdescription+xml`，则该资源是一个 [OpenSearch](/zh-CN/docs/Web/OpenSearch) 插件，可以很容易地添加到一些浏览器（如 Firefox 或 Internet Explorer）的界面中。
```

2023-02-15 09:26 UTC, yin1999 requested changes

2023-02-15 09:26 UTC, yin1999 commented on files/zh-cn/web/html/attributes/rel/index.md
> +关系的类型是由 `rel` 属性的值给出的，如果存在的话，它的值必须是一组无序的、唯一的、用空格隔开的关键字。与不表达语义的 `class` 名称不同，`rel` 属性必须使用对机器和人类都有语义的标记。目前关于 `rel` 属性的可能值的注册表是 [IANA 链接关系注册表](https://www.iana.org/assignments/link-relations/link-relati
```suggestion
关系的类型是由 `rel` 属性的值给出的，如果存在的话，它的值必须是一组无序的、唯一的、用空格隔开的关键字。与不表达语义的 `class` 名称不同，`rel` 属性必须使用对机器和人类都有语义的标记。目前关于 `rel` 属性的可能值的注册表是 [IANA 链接关系注册表](https://www.iana.org/assignments/link-relations/link-relations.xhtml)、[HTML 现行标准](https://html.spec.whatwg.org/multipage/links.html#linkTypes)和 microformats wiki 中可自由编辑的 [existing-rel-values 页面](https://microformats.org/wiki/existing-rel-values)（根据现行标准的[建议](https://html.spec.whatwg.org/multipage/links.html#other-link-types)）。如果使用一个不存在于上述三个来源之一的 `rel` 属性，一些 HTML 验证器（如 [W3C Markup Validation Service](https://validator.w3.org/)）会产生一个警告。
```

2023-02-15 09:26 UTC, yin1999 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    - 与文档语言不同的 [`hreflang`](/zh-CN/docs/Web/HTML/Element/link#attr-hreflang) 属性表示一个翻译。
翻译的不太对

2023-02-15 09:26 UTC, yin1999 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    > **备注：** 由于历史原因，废弃的属性值 `rev="made"` 视为 `rel="author"`。
```suggestion
    > **备注：** 由于历史原因，废弃的属性值 `rev="made"` 被视为 `rel="author"`。
```

2023-02-15 09:26 UTC, yin1999 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    `icon` 值最常见的用途是 favicon：
可以翻译一下：网站图标

https://zh.wikipedia.org/wiki/Favicon

2023-02-15 09:26 UTC, yin1999 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    如果有多个 `<link rel="icon">`，浏览器会使用它们的 [`media`](/zh-CN/docs/Web/HTML/Element/link#attr-media) [`type`](/zh-CN/docs/Web/HTML/Element/link#attr-type) 和 [`sizes`](/zh-CN/docs/Web/HTML/Element/link#att
```suggestion
    如果有多个 `<link rel="icon">`，浏览器会使用它们的 [`media`](/zh-CN/docs/Web/HTML/Element/link#attr-media)、[`type`](/zh-CN/docs/Web/HTML/Element/link#attr-type) 和 [`sizes`](/zh-CN/docs/Web/HTML/Element/link#attr-sizes) 属性来选择最合适的图标。如果几个图标同样合适，则使用最后一个。如果后来发现最合适的图标不合适，例如使用了不支持的格式，浏览器就会继续选择下一个最合适的，以此类推。
```

2023-02-15 09:26 UTC, yin1999 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    > **备注：** 在 Firefox 83 之前，[crossorigin](/zh-CN/docs/Web/HTML/Attributes/crossorigin)属性不支持 `rel="icon"`，也有 [Chrome 的一个开放问题](https://bugs.chromium.org/p/chromium/issues/detail?id=1121645)。
翻译成议题或问题都可，自行选择：

```suggestion
    > **备注：** 在 Firefox 83 之前，[crossorigin](/zh-CN/docs/Web/HTML/Attributes/crossorigin)属性不支持 `rel="icon"`，而 [Chrome 也仍有一个未解决的问题](https://bugs.chromium.org/p/chromium/issues/detail?id=1121645)。
```

2023-02-15 09:26 UTC, yin1999 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    > 相反，它分别使用非标准的 [`apple-touch-icon`](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.ht
合并成一段

2023-02-15 09:26 UTC, yin1999 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    > **备注：** 虽然同义词 `copyright` 也是认可的，但它是不正确的，必须避免使用。
感觉写“认可”不太好，再想想

2023-02-15 09:26 UTC, yin1999 commented on files/zh-cn/web/html/attributes/rel/index.md
> +  - : 与 {{htmlelement('form')}}、{{htmlelement('a')}} 和 {{htmlelement('area')}} 元素相关， `nofollow` 关键字告诉搜索引擎蜘蛛忽略链接关系。nofollow 关系可能表明当前文档的所有者并不认可被引用的文档。它经常被搜索引擎优化者包括在内，假装他们的链接养殖场不是垃圾页面。
```suggestion
  - : 与 {{htmlelement('form')}}、{{htmlelement('a')}} 和 {{htmlelement('area')}} 元素相关， `nofollow` 关键字告诉搜索引擎蜘蛛忽略链接关系。nofollow 关系可能表明当前文档的所有者并不认可被引用的文档。它经常被搜索引擎优化者包括在内，假装他们的链接农场不是垃圾页面。
```

2023-02-15 09:26 UTC, yin1999 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    备注：同义词 `previous` 不正确的，必须避免使用。
```suggestion
    备注：同义词 `previous` 并不正确，不应被使用。
```

2023-02-15 09:26 UTC, yin1999 commented on files/zh-cn/web/html/attributes/rel/index.md
> +  - : 与{{htmlelement('form')}}、{{htmlelement('link')}}、{{htmlelement('a')}} 和 {{htmlelement('area')}} 元素相关，`search` 关键字表示该超链接引用一个文档，其界面是专门为在当前文档、站点和相关资源中搜索而设计的，提供一个可以用来搜索的资源链接。
```suggestion
  - : 与 {{htmlelement('form')}}、{{htmlelement('link')}}、{{htmlelement('a')}} 和 {{htmlelement('area')}} 元素相关，`search` 关键字表示该超链接引用一个文档，其界面是专门为在当前文档、站点和相关资源中搜索而设计的，提供一个可以用来搜索的资源链接。
```

2023-02-15 10:53 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    `icon` 值最常见的用途是 favicon：
```suggestion
    `icon` 值最常见的用途是网站图标：
```

2023-02-15 10:54 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    > 相反，它分别使用非标准的 [`apple-touch-icon`](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.ht
```suggestion
    > **备注：** 苹果的 iOS 系统不使用这种链接类型，也不像其他移动浏览器那样使用 [`sizes`](/zh-CN/docs/Web/HTML/Element/link#attr-sizes) 属性，来选择网页夹或启动占位符的网页图标。相反，它分别使用非标准的 [`apple-touch-icon`](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html#//apple_ref/doc/uid/TP40002051-CH3-SW4) 和 [`apple-touch-starttup-image`](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html#//apple_ref/doc/uid/TP40002051-CH3-SW6)。
```

2023-02-16 02:35 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    > **备注：** 虽然同义词 `copyright` 也是认可的，但它是不正确的，必须避免使用。
```suggestion
    > **备注：** 虽然同义词 `copyright` 也是可以识别的，但它是不正确的，必须避免使用。
```

2023-02-16 02:45 UTC, jasonren0403 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    - 与文档语言不同的 [`hreflang`](/zh-CN/docs/Web/HTML/Element/link#attr-hreflang) 属性表示一个翻译。
不太确定这样是否可以：

```suggestion
    - [`hreflang`](/zh-CN/docs/Web/HTML/Element/link#attr-hreflang) 属性与文档所使用语言不同时，表示该页面的一个翻译。
```

2023-02-16 02:48 UTC, yin1999 commented on files/zh-cn/web/html/attributes/rel/index.md
> +    - 与文档语言不同的 [`hreflang`](/zh-CN/docs/Web/HTML/Element/link#attr-hreflang) 属性表示一个翻译。
可以

2023-02-16 03:02 UTC, merged