Firefox 89 for developers を翻訳
mdn/translated-content pull request #1161
Opened 2021-06-09 14:02 UTC by yyss

Jun 3, 2021 の英語版に対応 (不要な変更を含まないPull Requestを再作成)

2021-06-09 15:04 UTC, mfuji09 requested changes
2点の修正をお願いします。

2021-06-09 15:04 UTC, mfuji09 commented on files/ja/mozilla/firefox/releases/89/index.html
> +  <li>{{htmlelement("input")}} および {{htmlelement("textarea")}} 要素の内容物を、デフォルトで {{domxref("Document.execCommand()")}} コマンドを使用して操作できるようになりました。<a href="/ja/docs/Web/HTML/Global_attributes/contenteditable
ブラウザ→ブラウザーへの修正をお願いします。

2021-07-03 13:34 UTC, yyss commented on files/ja/mozilla/firefox/releases/89/index.html
> +<h2 id="Changes_for_web_developers" name="Changes_for_web_developers">ウェブ開発者向けの変更点一覧</h2>
name属性を削除しました。

2021-07-03 13:34 UTC, yyss commented on files/ja/mozilla/firefox/releases/89/index.html
> +  <li>{{htmlelement("input")}} および {{htmlelement("textarea")}} 要素の内容物を、デフォルトで {{domxref("Document.execCommand()")}} コマンドを使用して操作できるようになりました。<a href="/ja/docs/Web/HTML/Global_attributes/contenteditable
修正しました。

2021-07-03 14:51 UTC, mfuji09 approved these changes
OKです。

2021-07-03 14:51 UTC, merged