Web/JavaScript/Reference/Errors/I-J* を更新
mdn/translated-content pull request #1164
Opened 2021-06-11 18:14 UTC by mfuji09

2021/06/11 時点の英語版に同期

2021-06-19 08:21 UTC, potappo requested changes
未訳の部分があったのと、typo を修正しています。確認をお願いします。

2021-06-19 08:21 UTC, potappo commented on files/ja/web/javascript/reference/errors/invalid_const_assignment/index.html
> +<p>JavaScript の例外 "invalid assignment to const" は、定数を変更しようとしたときに発生します。 JavaScript の <code><a href="/ja/docs/Web/JavaScript/Reference/Statements/const">const</a></code> で宣言すると、再代入野菜宣言を行うことができません。</p>
```suggestion
<p>JavaScript の例外 "invalid assignment to const" は、定数を変更しようとしたときに発生します。 JavaScript の <code><a href="/ja/docs/Web/JavaScript/Reference/Statements/const">const</a></code> で宣言すると、再代入や再宣言を行うことができません。</p>
```

2021-06-19 15:29 UTC, mfuji09 commented on files/ja/web/javascript/reference/errors/in_operator_no_object/index.html
>  <p>Instead you will need to use {{jsxref("String.prototype.indexOf()")}}, for example.</p>
ありがとうございます。

2021-06-19 15:30 UTC, mfuji09 commented
@potappo さん、ありがとうございます！

2021-06-21 14:08 UTC, potappo approved these changes
OK です。

2021-06-21 14:09 UTC, merged