zh-cn(update): update HSTS about http
mdn/translated-content pull request #11641
Opened 2023-02-15 04:30 UTC by fwqaaq

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-02-15 04:34 UTC, fwqaaq commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +  - : 查看 [预加载 HSTS](#预加载_hsts) 获得详情。当使用 `preload`，`max-age` 指令必须至少是 `31536000`（一年），并且必须存在 `includeSubDomains` 指令。不是标准的一部分。
```suggestion
  - : 查看 [预加载 HSTS](#预加载_hsts) 获得详情。当使用 `preload`，`max-age` 指令必须至少是 `31536000`（一年），并且必须存在 `includeSubDomains` 指令。这不是标准的一部分。
```

2023-02-15 05:14 UTC, yin1999 requested changes
后面的再好好检查一下吧，英文文档的内容一直在变、以前的翻译也不一定足够好，好好对照检查一下。也注意一下错别字

2023-02-15 05:14 UTC, yin1999 commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +**`HTTP-Strict-Transport-Security`**（通常简称为 {{Glossary("HSTS")}}）响应标头用来通知浏览器应该只通过 HTTPS 访问该站点，并且以后使用 HTTP 访问该站点的所有尝试都应自动重定向到 HTTPS。
```suggestion
HTTP **`Strict-Transport-Security`**（通常简称为 {{Glossary("HSTS")}}）响应标头用来通知浏览器应该只通过 HTTPS 访问该站点，并且以后使用 HTTP 访问该站点的所有尝试都应自动重定向到 HTTPS。
```

2023-02-15 05:14 UTC, yin1999 commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
>  title: HTTP Strict Transport Security
```suggestion
title: Strict-Transport-Security
```

2023-02-15 05:14 UTC, yin1999 commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +> **备注：** 这比在你的服务器上简单地配置 HTTP 到 HTTPS（301）重定向要安全，因为初始的 HTTP 连接仍然易受到中间人的攻击。
```suggestion
> **备注：** 这比在你的服务器上简单地配置 HTTP 到 HTTPS（301）重定向要安全，因为初始的 HTTP 连接仍然易受到中间人攻击。
```

2023-02-15 05:14 UTC, yin1999 commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +| {{Glossary("Forbidden header name","禁止修改的标头")}} | 无                                         |
请对应英文修改：

```html
<table class="properties">
  <tbody>
    <tr>
      <th scope="row">Header type</th>
      <td>{{Glossary("Response header")}}</td>
    </tr>
    <tr>
      <th scope="row">{{Glossary("Forbidden header name")}}</th>
      <td>no</td>
    </tr>
  </tbody>
</table>
```

2023-02-15 05:14 UTC, yin1999 commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +如果一个网站接受一个 HTTP 的请求，然后重定向到 HTTPS，用户可能在开始重定向前，通过没有加密的方式和服务器对话，比如，用户输入 `http://foo.com` 或者直接是 foo.com。这样存在中间人攻击潜在威胁，重定向过程可能被恶意网站利用来直接接触用户信息，而不是原来的加密信息。可以利用重定向直接将访问者引导至一个恶意网站，而不是原始站到安全版本。
```suggestion
如果一个网站接受一个 HTTP 的请求，然后重定向到 HTTPS，用户可能在开始重定向前，通过没有加密的方式与服务器通信，比如，用户输入 `http://foo.com` 或者只是 foo.com。这样为中间人攻击创造了机会。可以利用重定向将用户引导至恶意站点，而不是原始站的安全版本。
```

2023-02-15 05:19 UTC, fwqaaq commented
HTTP 之前的翻译，虽然有的过时，但是翻译的确实好，我只修改一些过时的，便于学习。

2023-02-15 05:42 UTC, yin1999 commented
> HTTP 之前的翻译，虽然有的过时，但是翻译的确实好，我只修改一些过时的，便于学习。

文档翻译不是另起炉灶。请尽量与英文文档保持一致。若有觉得英文文档写的不好的地方，也应该是先修改英文文档，再将相应的内容同步到中文文档。

2023-02-15 05:45 UTC, fwqaaq commented
🤔，如果它的大概意思没问题，而且更接近读者的理解呢

2023-02-15 05:58 UTC, yin1999 commented
若没有时间，可以选择只修改一部分，但如果修改了一个段落，可以的话，我们是需要尽量与当前版本的英文文档同步的。多次提交PR修改同一个段落的内容会浪费太多的时间。我需要花时间检查，你也需要花时间做修改。

> 如果它的大概意思没问题，而且更接近读者的理解呢

同样的，就像我上面提的几处内容，英文原文中没这句话了，你可以选择在英文文档中加上去，也可以选择在中文文档中删去。当时有这个内容，可能是翻译的时候有人加上的（但在我们转换到 markdown 格式后，修改历史有时并不好追溯到那个时间点）；也有可能是后续从英文文档中删去的，那就有可能是有读者觉得这句话加上显得很多余。而修改的生效本身也需要由对应的[团队](https://developer.mozilla.org/zh-CN/docs/MDN/Community/Roles_teams#%E5%9B%A2%E9%98%9F)批准，一般相关的团队都是这方面的专家。

所以如果我们尽量会保证翻译内容的一致性，那读者有疑问的时候，我们也可以很好地将修改反馈到英文文档。

2023-02-15 08:56 UTC, yin1999 requested changes

2023-02-15 08:56 UTC, yin1999 commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +      <td>无</td>
```suggestion
      <td>否</td>
```

2023-02-15 08:56 UTC, yin1999 commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +> **备注：** `Strict-Transport-Security` 在通过 HTTP 访问时会被浏览器**忽略**。只有在你的网站通过 HTTPS 访问并且没有证书错误时，浏览器才认为你的网站支持 HTTPS，然后遵守 `Strict-Transport-Security` 标头。浏览器这样做是因为攻击者可以拦截到站点的 HTTP 连接，然后注入或者删除标头。
```suggestion
> **备注：** `Strict-Transport-Security` 标头在通过 HTTP 访问时会被浏览器**忽略**。只有在你的网站通过 HTTPS 访问并且没有证书错误时，浏览器才认为你的网站支持 HTTPS，然后遵守 `Strict-Transport-Security` 标头。浏览器这样做是因为攻击者可以拦截到站点的 HTTP 连接，然后注入或者删除标头。
```

2023-02-15 08:56 UTC, yin1999 commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +网站通过 HTTP Strict Transport Security 通知浏览器，这个网站禁止使用 HTTP 方式加载，并且浏览器应该自动把所有尝试使用 HTTP 的请求自动替换为 HTTPS 请求。
```suggestion
网站通过 HTTP Strict Transport Security 标头通知浏览器，这个网站禁止使用 HTTP 方式加载，并且浏览器应该自动把所有尝试使用 HTTP 的请求自动替换为 HTTPS 请求。
```

2023-02-15 08:56 UTC, yin1999 commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +现在和未来的所有子域名会自动使用 HTTPS，连接长达一年（`max-age` 值为 1）。同时阻止了只能通过 HTTP 访问页面或者子域的内容。
```suggestion
现在和未来的所有子域名会自动使用 HTTPS，有效期（`max-age`）为一年。同时阻止了只能通过 HTTP 访问页面或者子域的内容。
```

2023-02-15 08:56 UTC, yin1999 commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +在以下示例中，`max-age` 被设置为 2 年，并且后缀是 `preload`，这是必要的，它表示该网站包含在所有主流的 web 浏览器（如 Chromium、Edge 以及 Firefox）的 HSTS 预加载列表。
好好考虑一下，这两段翻译都需要修改

2023-02-15 08:56 UTC, yin1999 commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +- 维基百科：[HTTP Strict Transport Security](https://zh.wikipedia.org/wiki/HTTP_Strict_Transport_Security)
维基百科的链接就需要特别注意，它不会像 MDN 一样统一 path

```suggestion
- 维基百科：[HTTP Strict Transport Security](https://zh.wikipedia.org/wiki/HTTP严格传输安全)
```

2023-02-15 09:10 UTC, fwqaaq commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +- 维基百科：[HTTP Strict Transport Security](https://zh.wikipedia.org/wiki/HTTP_Strict_Transport_Security)
不过维基百科只要改 `en` -> `zh` 就可以了，它应该是自动重定向的

2023-02-15 09:14 UTC, fwqaaq commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +在以下示例中，`max-age` 被设置为 2 年，并且后缀是 `preload`，这是必要的，它表示该网站包含在所有主流的 web 浏览器（如 Chromium、Edge 以及 Firefox）的 HSTS 预加载列表。
```suggestion
然而，如果域可以接受 `max-age` 的值为 1 年，则推荐使用的值最好是 2 年，正如 <https://hstspreload.org> 中描述的那样。

在以下示例中，`max-age` 被设置为 2 年，并且后缀是 `preload`，这是网站被包含在所有主流的 web 浏览器（如 Chromium、Edge 以及 Firefox）的 HSTS 预加载列表所必要的。
```

2023-02-15 09:25 UTC, fwqaaq commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +在以下示例中，`max-age` 被设置为 2 年，并且后缀是 `preload`，这是必要的，它表示该网站包含在所有主流的 web 浏览器（如 Chromium、Edge 以及 Firefox）的 HSTS 预加载列表。
感觉**的**有点拗口🤔

2023-02-15 09:28 UTC, yin1999 commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +- 维基百科：[HTTP Strict Transport Security](https://zh.wikipedia.org/wiki/HTTP_Strict_Transport_Security)
并不是：

- https://en.wikipedia.org/wiki/Link_farm
- https://zh.wikipedia.org/wiki/Link_farm

2023-02-15 09:34 UTC, fwqaaq commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +- 维基百科：[HTTP Strict Transport Security](https://zh.wikipedia.org/wiki/HTTP_Strict_Transport_Security)
😯，<https://zh.wikipedia.org/wiki/HTTP_Strict_Transport_Security> 这个链接可以，我误认为是可以的

2023-02-15 09:38 UTC, yin1999 commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +在以下示例中，`max-age` 被设置为 2 年，并且后缀是 `preload`，这是必要的，它表示该网站包含在所有主流的 web 浏览器（如 Chromium、Edge 以及 Firefox）的 HSTS 预加载列表。
在以下示例中，有效期（`max-age`）被设置为 2 年，并带有 `preload` 后缀，这个后缀是网站被收录到所有主流的 web 浏览器（如 Chromium、Edge 以及 Firefox）的 HSTS 预加载列表所必须的。

2023-02-15 09:43 UTC, fwqaaq commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +在以下示例中，`max-age` 被设置为 2 年，并且后缀是 `preload`，这是必要的，它表示该网站包含在所有主流的 web 浏览器（如 Chromium、Edge 以及 Firefox）的 HSTS 预加载列表。
👌

2023-02-15 10:42 UTC, yin1999 commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +在以下示例中，`max-age` 被设置为 2 年，并且后缀是 `preload`，这是必要的，它表示该网站包含在所有主流的 web 浏览器（如 Chromium、Edge 以及 Firefox）的 HSTS 预加载列表。
第一段还是怪怪的，再考虑一下

2023-02-15 16:03 UTC, fwqaaq commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +在以下示例中，`max-age` 被设置为 2 年，并且后缀是 `preload`，这是必要的，它表示该网站包含在所有主流的 web 浏览器（如 Chromium、Edge 以及 Firefox）的 HSTS 预加载列表。
还是加上主语，再加一下补充，这样好很多

2023-02-16 00:56 UTC, yin1999 commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +在以下示例中，`max-age` 被设置为 2 年，并且后缀是 `preload`，这是必要的，它表示该网站包含在所有主流的 web 浏览器（如 Chromium、Edge 以及 Firefox）的 HSTS 预加载列表。
感觉英文就不对，我开了个 PR：mdn/content#24476

2023-02-16 03:29 UTC, fwqaaq commented
> 感觉英文就不对，我开了个 PR：mdn/content#24476 <https://github.com/mdn/content/pull/24476>

那先等它合并吧

2023-02-16 04:49 UTC, yin1999 commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +在以下示例中，`max-age` 被设置为 2 年，并且后缀是 `preload`，这是必要的，它表示该网站包含在所有主流的 web 浏览器（如 Chromium、Edge 以及 Firefox）的 HSTS 预加载列表。
```suggestion
虽然将域的有效期（`max-age`）设置为 1 年是可以的，但 <https://hstspreload.org> 推荐将其设置为 2 年。

在以下示例中，有效期（`max-age`）被设置为 2 年，并带有 `preload` 后缀，该后缀是网站被收录到所有主流的 web 浏览器（如 Chromium、Edge 以及 Firefox）的 HSTS 预加载列表所必须的。
```

2023-02-16 04:56 UTC, fwqaaq commented on files/zh-cn/web/http/headers/strict-transport-security/index.md
> +在以下示例中，`max-age` 被设置为 2 年，并且后缀是 `preload`，这是必要的，它表示该网站包含在所有主流的 web 浏览器（如 Chromium、Edge 以及 Firefox）的 HSTS 预加载列表。
🐮

2023-02-16 05:02 UTC, yin1999 approved these changes

2023-02-16 05:02 UTC, merged