[ko] Translation for checkbox input type
mdn/translated-content pull request #11695
Opened 2023-02-17 15:42 UTC by dwywdo

### Description

HTML Input 요소 중 체크박스 타입에 대한 한국어 번역 문서 추가

### Motivation

한국어 번역 문서가 존재하지 않았음

### Additional details

None

### Related issues and pull requests

Fixes #11464

2023-02-17 15:42 UTC, dwywdo commented
@yechoi42 시간 되실 때 확인 부탁드립니다 🙇

2023-02-18 02:13 UTC, SnowMarble commented
안녕하세요, 새롭게 추가된 메타데이터 작업이 있는데, [여기](https://github.com/hochan222/translated-content/blob/ko-guide-translate/docs/ko/guides/meta-data-guide.md#%ED%8E%98%EC%9D%B4%EC%A7%80-%EA%B0%B1%EC%8B%A0-%ED%91%9C%EC%8B%9C) 한 번 참고해주세요:)

2023-02-18 06:23 UTC, dwywdo commented
@SnowMarble 감사합니다 🙇  sourceCommit 부분 반영 완료하였습니다.

2023-02-18 06:33 UTC, dwywdo commented on files/ko/web/html/element/input/checkbox/index.md
> +**`checkbox`** 유형의 {{htmlelement("input")}} 요소는 기본적으로 공문서에서 볼 법한, 활성화될 시에 체크되는 박스로 렌더링 됩니다. 박스의 정확한 외형은 브라우저가 실행 중인 운영체제의 시스템 구성에 따라 달라질 수 있습니다. 일반적으로는 사각형의 모습이지만, 둥근 모서리를 가질 수도 있습니다. **`checkbox`**
- 체크박스가 체크된 상태를 "체크되었다/체크되지 않았다"가 아닌 "활성화" 혹은 "비활성화"라는 표현을 사용하였습니다. 혹시 문맥에 어긋나거나 더 적절한 표현이 있다면 의견을 구하고 싶습니다.
  - "선택하다 / 선택하지 않다"라는 표현은 사용자의 브라우저 상에서의 행위를 나타내는 데에만 사용하였고, 그 행위의 결과롤 나타난 체크박스의 상태를 표현하는 단어와는 구분하고자 하였습니다.

2023-02-18 06:36 UTC, dwywdo commented on files/ko/web/html/element/input/checkbox/index.md
> +## 값
여기에서의 `값` 이라는 단어의 표현을 정확히 기술하자면 checkbox type의 input 요소에 부여되는 value 속성(특성)의 값이라고 이해하였습니다만, 그대로 번역을 하다보니 `값`이라는 너무 범위가 넓은 단어가 번역에 사용되어 자칫 위 기술적 의미를 명확히 전달하지는 못할 수 있겠다는 생각이 들었습니다. (코드에서는 `<input 값="newsletter" />`와 같이 사용할 수는 없으니까요.. 그래서 이 문서를 번역하는 과정에서, HTML 요소의 특성(속성, Property)의 하나의 의미를 갖는 것들은 `값` 혹은 `이름`과 같이 번역하기보다는 `value` / `name`을 그대로 사용하는 것이 낫지 않은가 하였습니다. 앞으로 번역할 때 이 부분에 대해서 스스로 계속 부딪힐 것 같아서, KO 리뷰어분들께 이 부분에서는 어떤 관점을 갖고 계신지 여쭈어보고 싶습니다.

2023-02-18 06:38 UTC, dwywdo commented on files/ko/web/html/element/input/checkbox/index.md
> +{{EmbedGHLiveSample("learning-area/html/forms/indeterminate-example/index.html", '100%', 200)}}
직접적으로 접근 가능한 다른 예제에서는 영어로 표현된 텍스트를 한글로 바꾸었는데, 이 예제 파일 내에 존재하는 영어 텍스트도 한글로 바꾸어야 할 필요가 있을까요? 만약 그렇다고 한다면, 어느 부분을 수정해야 하는지 알려주시면 좋겠습니다 (일단 해당 파일, `indeterminate-example/index.html` 파일을 찾지도 못했고 🤔  LiveSample 등이 어떤 구조로 소스가 관리되고 렌더링되는지 깊게 보지는 않아서 잘 이해하지 못하겠네요)

2023-02-18 06:39 UTC, dwywdo commented on files/ko/web/html/element/input/checkbox/index.md
> +## 기술 명세
기술 명세의 텍스트도 가능하면 한글로 번역하는 것이 권장되는지 가이드에는 기술되어 있지 않아 문의드리고 싶습니다 🙇

2023-02-18 06:40 UTC, dwywdo reviewed
첫 PR인지라, 번역하는 과정에서 권장되는 방식과 애매모호하게 느꼈던 부분에 대해서 Self 코멘트를 일부 남겨보았습니다. 의견 주시면 감사하게 생각하고 이 후 다른 PR에서 반영해 작업해보겠습니다.

2023-02-18 07:09 UTC, SnowMarble commented on files/ko/web/html/element/input/checkbox/index.md
> +## 값
이게 가이드에 있었는지 정확히 생각나진 않지만, 인라인 코드(\`\`안)는 실제 속성 이름 등을 쓸 때 사용되기때문에 번역하지 않는것을 권장한다고 알고있습니다. `name`과 `value` 도 용어집에서 [Attribute](https://developer.mozilla.org/en-US/docs/Glossary/Attribute)를 `name="value"`로 설명하고 있어서 인라인 코드로 썼다고 추측해보지만,  물론 번역하는 것이 바람직하다면 하는것이 맞습니다. 이 부분은 유연하게 작업해주시면 될 것 같아요🙂

2023-02-18 07:25 UTC, SnowMarble commented on files/ko/web/html/element/input/checkbox/index.md
> +{{EmbedGHLiveSample("learning-area/html/forms/indeterminate-example/index.html", '100%', 200)}}
라이브 샘플은 번역하지 않아도 괜찮습니다. 

라이브 샘플 소스는 다른 리포지토리에서 관리되고있고, [mdn/interactive-examples](https://github.com/mdn/interactive-examples) 해당 매크로 소스는 [여기](https://github.com/mdn/yari/blob/main/kumascript/macros/EmbedGHLiveSample.ejs)에서 확인하실 수 있어요

2023-02-18 07:30 UTC, dwywdo commented on files/ko/web/html/element/input/checkbox/index.md
> +## 값
의견 감사합니다.
>  인라인 코드(``안)는 실제 속성 이름 등을 쓸 때 사용되기때문에 번역하지 않는것을 권장한다고 알고있습니다.
요 부분이 공감되기도 하고..! 참고하여 수정하는 커밋을 얹어보겠습니다.

2023-02-19 06:24 UTC, SnowMarble commented on files/ko/web/html/element/input/checkbox/index.md
> +## 기술 명세
기본적으로 모든 영어를 번역한다는 점에서 저는 "Technical summary" 부분도 모두 번역하는 것이 맞다고 생각합니다.
한번 살펴보니 아직 전부 번역하시진 않은것 같은데, 첫 번째 Value를 제외한 모든 것을 번역하면 좋을 것 같습니다. 그리고 제목에 사용하신 "명세"보단 "요약"으로 쓰는것도 제안드려보는데, 바로 아래 실제 명세서가 있고, 문서 내용을 요약하는 표이기 때문입니다.😄

2023-02-19 11:10 UTC, dwywdo commented on files/ko/web/html/element/input/checkbox/index.md
> +## 기술 명세
말씀해주신 것처럼 기술 명세 (Specification) 보다는 Summary에 해당하는 요약이 적절한 번역인 것 같아서 수정했습니다 🙇  
추가적으로, 기술 요약 섹션 아래에 외에 한글 표현으로 바뀌지 않은 부분도 번역 완료하였습니다.

2023-02-20 13:30 UTC, yechoi42 requested changes
@dwywdo 님 기여 감사합니다. (@SnowMarble 님 같이 리뷰해주셔서 감사합니다.)
문장을 자연스럽게 하였고, 예제 매크로 한 가지를 작동하도록 수정하였습니다.
확인하신 뒤 저를 다시 멘션해주시면 머지하도록 하겠습니다.

2023-02-20 13:30 UTC, yechoi42 commented on files/ko/web/html/element/input/checkbox/index.md
> +**`checkbox`** 유형의 {{htmlelement("input")}} 요소는 기본적으로 공문서에서 볼 법한, 활성화될 시에 체크되는 박스로 렌더링 됩니다. 박스의 정확한 외형은 브라우저가 실행 중인 운영체제의 시스템 구성에 따라 달라질 수 있습니다. 일반적으로는 사각형의 모습이지만, 둥근 모서리를 가질 수도 있습니다. **`checkbox`**
```suggestion
공문서에서 볼 법한 **`checkbox`** 유형의 {{htmlelement("input")}} 요소는 기본적으로 활성화될 시에 체크되는 박스로 렌더링 됩니다. 박스의 정확한 외형은 브라우저가 실행 중인 운영체제의 시스템 구성에 따라 달라질 수 있습니다. 일반적으로는 사각형의 모습이지만, 둥근 모서리를 가질 수도 있습니다. **`checkbox`** 는 폼 안에서 선택된 단일 값들을 제출할 수 있는 기능을 제공합니다.
```
우리말로 하였을 때 더 자연스럽도록 어순을 바꿔 제안드립니다.

2023-02-20 13:30 UTC, yechoi42 commented on files/ko/web/html/element/input/checkbox/index.md
> +{{EmbedLiveSample('Examples', '100%', 300)}}
```suggestion
{{EmbedLiveSample('예제', '100%', 300)}}
```
라고 해주셔야 예시를 올바르게 불러올 수 있습니다 !

2023-02-20 14:17 UTC, dwywdo commented
@yechoi42 확인 감사합니다..! 제안해주신 내용 & Live Example Fix 반영하였습니다 🙇

2023-02-22 01:00 UTC, yechoi42 approved these changes

2023-02-22 01:00 UTC, merged