Issue/679/commnd line crash course
mdn/translated-content pull request #11745
Opened 2023-02-18 15:09 UTC by gurezo

@hmatrjp @potappo 

### issue
- [ Command line crash course の翻訳 #679 ](https://github.com/mozilla-japan/translation/issues/679)  のPRです。

### yari

2023-02-19 02:34 UTC, mfuji09 requested changes
自動チェックの指摘箇所とレビュー指摘箇所の修正をお願いします。
また、画像については、英語版と同じ画像は削除してください。画像をPRに含めて良いのは、画像内を翻訳した場合のみです。

2023-02-19 02:34 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +        ターミナル／コマンドラインとは何か、学ぶべき基本的なコマンドは何か、新しいコマンドラインツールをインストールする方法を理解します。。
末尾の「。」が2つになっているので、1つにしてください。

2023-02-19 02:34 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +端末は、テキストベースのプログラムを実行するためのテキストインターフェイスです。 Web 開発用のツールを実行している場合、選択したツールを使用するために、コマンドラインを開いていくつかのコマンドを実行する必要がある可能性がほぼ保証されています (**CLI ツール**と呼ばれるツールをよく見かけます — コマンドラインインターフェイスツール）。
Web→ウェブと表記してください。（以下も同様）
また、「ーコマンドラインインターフェイスツール」は「CLI ツール」の直後に付けた方が良いと思います。

2023-02-19 02:34 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +コマンドラインにコマンドを入力すると、多数のツールを使用できます。 多くはシステムにプリインストールされており、その他の膨大な数はパッケージレジストリからインストールできます。
レジストリ→レジストリー
でお願いします。（以下も同様）

2023-02-19 02:34 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +コマンドラインを初めて表示するときは、気が遠くなるような体験になる可能性があります。空白の画面と点滅するカーソルが表示され、何をすべきかについての明確なヘルプはほとんどありません。
「初めて表示する」だと主語が曖昧になるので、「初めて見る」のほうが良いと思います。
また、「空白の画面」よりも「空っぽの画面」くらいに表現したほうが良いと思います。

2023-02-19 02:34 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +これが私たちがこの章を提供している理由です — この一見不親切な環境であなたが始めるのを助けるために.
句点が「．」になっているので、「。」で統一してください。

2023-02-19 02:34 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +端末は 1950 年代から 60 年代頃に誕生し、その元の形は現在私たちが使用しているものとはまったく似ていません (感謝すべきことです)。 ウィキペディアの[コンピューターターミナル](https://en.wikipedia.org/wiki/Computer_terminal) のエントリで歴史の一部を読むことができます。
「端末」は前後で「ターミナル」と呼んでいるので、ここでも「ターミナル」と呼んだ方が良いと思います。

2023-02-19 02:34 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +自動化にも役立ちます。たとえば、「ch01-xxxx.png」から「ch02-xxxx.png」など、数百のファイルのタイトルを即座に更新するコマンドを作成します。 ファインダーまたはエクスプローラー GUI アプリを使用してファイル名を更新すると、長い時間がかかります。
「コマンドを作成します」よりも「コマンドを書くことができます」の方が、自然でより原文に近いと思います。

2023-02-19 02:34 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +そして、その下にmacOS ターミナルアプリケーションが表示されます。
ここも半角スペースを入れてください。
```suggestion
そして、その下に macOS ターミナルアプリケーションが表示されます。
```

2023-02-19 02:34 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +今日、多くの開発者は Unix ベースのツールを使用しています (例: ターミナルと、そこからアクセスできるツール)。 今日 Web 上に存在する多くのチュートリアルやツールは、Unix ベースのシステムをサポートしています (残念ながらそれを想定しています) が、心配する必要はありません。ほとんどのシステムで利用できます。 このセクションでは、選択したシステムの端末にアクセスする方法を見ていき
ここも「Web」→「ウェブ」で統一してください。

2023-02-19 02:34 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +他のプログラミングツールと同様に、Windows でターミナル (またはコマンド ライン) を使用することは、従来、他のオペレーティングシステムほど単純でも簡単でもありませんでした。 しかし、状況は良くなっています。
単語間の空白は外してください。（以下も同様）
```suggestion
他のプログラミングツールと同様に、Windows でターミナル (またはコマンドライン) を使用することは、従来、他のオペレーティングシステムほど単純でも簡単でもありませんでした。 しかし、状況は良くなっています。
```

2023-02-19 02:34 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +  - ディレクトリを移動: `cd`
ディレクトリ→ディレクトリー

2023-02-19 02:34 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +> **注:**Windows では、スラッシュの代わりにバックスラッシュを使用します。 `cd Desktop\project\src` — これは非常に奇妙に思えるかもしれませんが、その理由に興味がある場合は、マイクロソフトのプリンシパル エンジニアの 1 人の[この YouTube クリップをご覧ください](https://www.youtube.com/watch?v=5T3IJfBfB
`**注:**` ではなく `**メモ:**` と翻訳してください。（この表記がマジックワードとして意味を持っているため）

2023-02-19 02:34 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +前のディレクトリに戻りたい場合は、2 つのドットを使用します。:
`。` と `:` は共に文末を示す記号なので、両方を付けることは不要です。
`。` のみのほうが自然な日本語らしくて良いと思います。

2023-02-19 02:34 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +You'll get an output like this
翻訳し忘れと思われます。

2023-02-19 02:34 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +- git リポジトリにコミットする前に[Husky](https://github.com/typicode/husky) を使用します。
リポジトリ→リポジトリー
また、Huskyの前に半角スペースを入れてください。

2023-02-19 05:39 UTC, gurezo commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +        ターミナル／コマンドラインとは何か、学ぶべき基本的なコマンドは何か、新しいコマンドラインツールをインストールする方法を理解します。。
[c6d6356](https://github.com/mdn/translated-content/pull/11745/commits/c6d6356f0e922541f7d68c9663094888f051b5bd)

2023-02-19 05:42 UTC, gurezo commented
@mfuji09 

修正しました。
- Remove images 0f6e4f6
- Remove 。。 c6d6356
- CLI ツール — コマンドラインインターフェイスツール 437c506
- Web→ウェブ 048ab77
- レジストリ→レジストリー 7e7a441
- .→。 6ab4964
- 端末→ターミナル 11d4af9
- コマンドを作成します→コマンドを書くことができます 1eec4ec
- 。:→。 a2376e4
- translate You'll get an output like this 168403a
- リポジトリ→リポジトリー 71024ea
- **注:**=> **メモ:** 298a8de
- ディレクトリ→ディレクトリー 1d12c66
- コマンド ライン=>コマンドラ ン

2023-02-20 13:16 UTC, mfuji09 requested changes
追加事項と、まだ修正されていない点がありましたので、再度ご確認ください。

2023-02-20 13:16 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +- 特定の URL にあるファイルのダウンロードs: `curl`
s は不要と思われます。
```suggestion
- 特定の URL にあるファイルのダウンロード: `curl`
```

2023-02-20 13:16 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +> **メモ:** 非常に便利なターミナルショートカットは、 <kbd>tab</kbd> キーを使用して、すべてを入力するのではなく、存在することがわかっている名前をオートコンプリートすることです。 たとえば、上記の 2 つのコマンドを入力した後、 `cd D` と入力して <kbd>tab</kbd> を押してみてください。現在のディレクトリーに存在する場合、ディレクトリー名 `Deskto
後から気が付きましたが、この文の翻訳が不自然に感じました。
```suggestion
> **メモ:** 存在することがわかっている名前をすべて入力するのではなく、<kbd>tab</kbd> キーを使用して自動補完することは、非常に便利なターミナルのショートカットです。 たとえば、上記の 2 つのコマンドを入力した後、 `cd D` と入力して <kbd>tab</kbd> を押してみてください。現在のディレクトリーに存在する場合、ディレクトリー名 `Desktop` が自動補完されます。 前進するときは、このことを念頭に置いてください。
```

2023-02-20 13:16 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +パスの先頭にスラッシュを含めると、パスが絶対パスになることに注意してください (例: `/Users/your-user-name/Desktop`)。 上記のように先頭のスラッシュを省略すると、パスは現在の作業ディレクトリーからの相対パスになります。 これは、ウェブブラウザの URL で表示されるものとまったく同じです。 先頭のスラッシュは「ウェブサイトのルート」を意味し、スラッシュを省略する
「ブラウザ」の表記をすべて「ブラウザー」に修正するようお願いします。
```suggestion
パスの先頭にスラッシュを含めると、パスが絶対パスになることに注意してください (例: `/Users/your-user-name/Desktop`)。 上記のように先頭のスラッシュを省略すると、パスは現在の作業ディレクトリーからの相対パスになります。 これは、ウェブブラウザーの URL で表示されるものとまったく同じです。 先頭のスラッシュは「ウェブサイトのルート」を意味し、スラッシュを省略すると「現在のページに関連する URL」を意味します。
```

2023-02-20 13:16 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +> **メモ:** 各コマンドで使用できるオプションを正確に確認するには、[man ページ](https://en.wikipedia.org/wiki/Man_page) を参照してください。 これを行うには、 `man` コマンドの後に、検索するコマンドの名前を入力します ( `man ls` など)。 これにより、端末のデフォルトのテキスト ファイル ビューアー (たとえば、私の端末では
こちらも、カタカナ語内の半角スペースを挿入しないでください。
以降の記事についても、確認の上修正をお願いします。

2023-02-20 14:32 UTC, gurezo commented
@mfuji09 

修正しました。
- 。 => 。 57009c48c4deda148b494b61961f34d9bac8d94e
- Remove unnecessary space 52374ec54b7795b1292287063439d911b1137efc

2023-02-22 13:48 UTC, mfuji09 approved these changes
OKです。

2023-02-22 13:49 UTC, merged