[ko] Translation for linear-gradient()
mdn/translated-content pull request #11748
Opened 2023-02-18 19:56 UTC by dwywdo

### Description

CSS의 `linear-gradient()` 함수에 대한 한국어 번역 문서 추가

### Motivation

한국어 번역 문서가 존재하지 않음

### Additional details

### Related issues and pull requests

Fixes #11462

2023-02-19 11:45 UTC, hochan222 requested changes
@dwywdo 님 안녕하세요.

기여해주셔서 감사합니다. 고생 많으셨습니다.

몇가지 리뷰사항 남겨두었습니다. 좋은 하루 보내세요 :)

2023-02-19 11:45 UTC, hochan222 commented on files/ko/web/css/gradient/linear-gradient/index.md
> +**`linear-gradient()`** [CSS](/ko/docs/Web/CSS) [함수](/en-US/docs/Web/CSS/CSS_Functions)는 두 개 이상의 색상이 직선을 따라 점진적으로 변화되는 선형 그라데이션 그림을 생성합니다. 그 결과는 {{CSSxRef("&lt;gradient&gt;")}} 데이터 유형의 객체이며, 이는 {{CSS
```suggestion
**`linear-gradient()`** [CSS](/ko/docs/Web/CSS) [함수](/ko/docs/Web/CSS/CSS_Functions)는 두 개 이상의 색상이 직선을 따라 점진적으로 변화되는 선형 그라데이션 그림을 생성합니다. 그 결과는 {{CSSxRef("&lt;gradient&gt;")}} 데이터 유형의 객체이며, 이는 {{CSSxRef("&lt;image&gt;")}}의 특별한 종류 중 하나입니다.
```

[문서 연결 경로](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md#%EB%AC%B8%EC%84%9C-%EC%97%B0%EA%B2%B0-%EA%B2%BD%EB%A1%9C)에 따라 한글 문서가 존재하지 않더라도 /en-US 문서로 넘겨주기 때문에 한국 문서의 모든 경로는 /ko로 표기 부탁드립니다!

2023-02-19 11:45 UTC, hochan222 commented on files/ko/web/css/gradient/linear-gradient/index.md
> +/* 45도 경사를 기준으로
👍👍

2023-02-19 11:45 UTC, hochan222 commented on files/ko/web/css/gradient/linear-gradient/index.md
> +/* 오른쪽 아래에서 왼쪽 위으로,
```suggestion
/* 오른쪽 아래에서 왼쪽 위로,
```

2023-02-19 11:45 UTC, hochan222 commented on files/ko/web/css/gradient/linear-gradient/index.md
> +  - : 그라데이션의 시작 지점의 위치. 이 값이 지정될 때에는 `to`라는 값과 함께 최대 2개의 키워드를 가질 수 있습니다. 한 경우는 `left`와 `right` 값을 통해 수평선을 의미하는 방식이고, 다른 경우는 `top`과 `bottom`을 이용해 수직선을 의미하는 방식입니다. 각 키워드의 순서는 중요하지 않습니다. 만약 이 값이 명시되지 않으
> 한 경우는 `left`와 `right` 값을 통해 수평선을 의미하는 방식이고, 다른 경우는 `top`과 `bottom`을 이용해 수직선을 의미하는 방식입니다.

> If specified, it consists of the word `to` and up to two keywords: one indicates the horizontal side (`left` or `right`), and the other the vertical side (`top` or `bottom`).

괄호도 최대한 원문과 동일하게 번역을 권장드리지만, 번역해주신 부분도 괜찮아보입니다.

2023-02-19 11:45 UTC, hochan222 commented on files/ko/web/css/gradient/linear-gradient/index.md
> +> **참고:** [CSS 그라데이션의 색 중지점](#선형_그라데이션의_구성)의 렌더링 방식은 [SVG 그라데이션](/en-US/docs/Web/SVG/Tutorial/Gradients)과 동일한 규칙을 따릅니다.
```suggestion
> **참고:** [CSS 그라데이션의 색 중지점](#선형_그라데이션의_구성)의 렌더링 방식은 [SVG 그라데이션](/ko/docs/Web/SVG/Tutorial/Gradients)과 동일한 규칙을 따릅니다.
```

2023-02-19 11:45 UTC, hochan222 commented on files/ko/web/css/gradient/linear-gradient/index.md
> +_시작점_ 은 그라데이션 선에서 첫 색상이 시작되는 위치입니다. _끝점_ 은 마지막 색상이 끝나는 위치입니다. 이 각각의 두 지점들은 같은 사분면에 존재하는 박스 모서리로부터 시작되는 수직선과 그라데이션 선의 교차점으로 정의됩니다. 끝점은 시작점과 대칭 관계라고 이해할 수 있습니다. 조금은 복잡해보이는 이 정의는 _magic corners_ 라는 흥미로운
```suggestion
시작점 은 그라데이션 선에서 첫 색상이 시작되는 위치입니다. 끝점은 마지막 색상이 끝나는 위치입니다. 이 각각의 두 지점들은 같은 사분면에 존재하는 박스 모서리로부터 시작되는 수직선과 그라데이션 선의 교차점으로 정의됩니다. 끝점은 시작점과 대칭 관계라고 이해할 수 있습니다. 조금은 복잡해보이는 이 정의는 magic corners 라는 흥미로운 효과를 만들게 됩니다. 즉, 시작점과 끝점에 가장 가까운 모서리는 대응되는 점과 동일한 색상을 갖게 됩니다.
```
[기울임꼴](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md#%EA%B8%B0%EC%9A%B8%EC%9E%84%EA%BC%B4)에 따라 한국 문서에서는 기울임꼴을 사용하지 않습니다.

2023-02-19 11:45 UTC, hochan222 commented on files/ko/web/css/gradient/linear-gradient/index.md
> +_시작점_ 은 그라데이션 선에서 첫 색상이 시작되는 위치입니다. _끝점_ 은 마지막 색상이 끝나는 위치입니다. 이 각각의 두 지점들은 같은 사분면에 존재하는 박스 모서리로부터 시작되는 수직선과 그라데이션 선의 교차점으로 정의됩니다. 끝점은 시작점과 대칭 관계라고 이해할 수 있습니다. 조금은 복잡해보이는 이 정의는 _magic corners_ 라는 흥미로운
magic corners가 [Inline code](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md#inline-code)가 아님으로 번역해도 무방합니다.

현재 문서에서는 번역하는것이 좋아보입니다. 기여자님 의견은 어떠하신가요?

2023-02-20 04:39 UTC, dwywdo commented on files/ko/web/css/gradient/linear-gradient/index.md
> +_시작점_ 은 그라데이션 선에서 첫 색상이 시작되는 위치입니다. _끝점_ 은 마지막 색상이 끝나는 위치입니다. 이 각각의 두 지점들은 같은 사분면에 존재하는 박스 모서리로부터 시작되는 수직선과 그라데이션 선의 교차점으로 정의됩니다. 끝점은 시작점과 대칭 관계라고 이해할 수 있습니다. 조금은 복잡해보이는 이 정의는 _magic corners_ 라는 흥미로운
magic corners에 대해서 적절한 한국어 표현을 찾지 못해서 일단 번역하지 못했습니다.. 😭 
적절한 표현을 찾아 수정해보겠습니다.

2023-02-20 04:40 UTC, dwywdo commented on files/ko/web/css/gradient/linear-gradient/index.md
> +**`linear-gradient()`** [CSS](/ko/docs/Web/CSS) [함수](/en-US/docs/Web/CSS/CSS_Functions)는 두 개 이상의 색상이 직선을 따라 점진적으로 변화되는 선형 그라데이션 그림을 생성합니다. 그 결과는 {{CSSxRef("&lt;gradient&gt;")}} 데이터 유형의 객체이며, 이는 {{CSS
그렇군요...매번 들어가서 번역된 문서가 있는지 확인했었는데 그럴 필요가 없었군요 😓 감사합니다 반영해보겠습니다.

2023-02-20 08:24 UTC, hochan222 commented on files/ko/web/css/gradient/linear-gradient/index.md
> +_시작점_ 은 그라데이션 선에서 첫 색상이 시작되는 위치입니다. _끝점_ 은 마지막 색상이 끝나는 위치입니다. 이 각각의 두 지점들은 같은 사분면에 존재하는 박스 모서리로부터 시작되는 수직선과 그라데이션 선의 교차점으로 정의됩니다. 끝점은 시작점과 대칭 관계라고 이해할 수 있습니다. 조금은 복잡해보이는 이 정의는 _magic corners_ 라는 흥미로운
제가 번역이라고 표현해서 조금 오해의 소지가 있었네요. `매직 코너`를 의미한것이었습니다. 보통의 경우 한글 음차를 사용하는 편인것같습니다.

문맥과 의도된 의미에 따라 여러 가지 번역이 되는 경우나 원문의 의도된 의미와 어조가 번역으로 잘 표현되지 못하는 경우는 아니지만, 마법 모서리보다는 매직 코너를 더 많이 사용하기에 `매직 코너`가 좋아보입니다!

2023-02-20 08:26 UTC, hochan222 approved these changes
@dwywdo 님 안녕하세요.

고생 많으셨습니다! 병합해도 괜찮을 것같은데 혹시 더 수정하실 사항이 있으실까요?

2023-02-20 12:33 UTC, dwywdo commented
@hochan222 
https://github.com/mdn/translated-content/pull/11748#discussion_r1111219445 + magic corner 건까지 수정 완료하였습니다. 병합은 Reviewer 분들께서 해주시나요? 😄 더 수정할 사항은 없어 보입니다 🙇

2023-02-20 12:53 UTC, hochan222 commented
@dwywdo 님, 빠른 반영 감사드립니다 :) 

네네 병합은 리뷰어의 책임입니다. 고생 많으셨습니다. 좋은 하루 보내세요!

2023-02-20 12:53 UTC, merged