[ko] What is Accessibility? translation
mdn/translated-content pull request #11825
Opened 2023-02-22 05:54 UTC by se030

### Description

[What is Accessibility?](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/What_is_accessibility) 문서를 한국어로 번역합니다.

### Motivation

기존 한국어 번역이 투박하거나 없습니다.

### Additional details

- 번역 기여가 처음이라서 제대로 진행했는지 모르겠습니다. 개선이 필요한 부분은 편하게 말씀해주세요!

- 가이드를 읽지 않고 진행했던 번역을 추후에 수정해서 미흡한 부분이 있을 수 있습니다. 검토는 했지만 리뷰 시에 한번 더 확인 부탁드립니다.

- 기존 한국어 버전 문서의 영문 컨텐츠가 [현재 content 레포](https://github.com/mdn/content/blob/main/files/en-us/learn/accessibility/what_is_accessibility/index.md)와 싱크가 맞지 않습니다. 저는 원본 레포 기준으로 작업했습니다.

### Related issues and pull requests

2023-02-24 06:35 UTC, cos18 requested changes
첫 기여 감사드립니다! 리뷰 내용 확인해주시고 리뷰 re-request 부탁드립니다!

2023-02-24 06:35 UTC, cos18 commented on files/ko/learn/accessibility/what_is_accessibility/index.md
> +[Deaf and hard-of-hearing(DHH)](https://www.nad.org/resources/american-sign-language/community-and-culture-frequently-asked-questions/) 사람들은 경도에서 심도까지 다양한 수준의 난청을 가지고 있습니다. 이들 중 일부는 보조 기술(AT, [Assist
```suggestion
[청각 장애 및 난청 (Deaf and hard-of-hearing, DHH)](https://www.nad.org/resources/american-sign-language/community-and-culture-frequently-asked-questions/) 사람들은 경도에서 심도까지 다양한 수준의 난청을 가지고 있습니다. 이들 중 일부는 보조 기술(AT, [청각, 음성, 언어 장애가 있는 사람들을 위한 보조 장치](https://www.nidcd.nih.gov/health/assistive-devices-people-hearing-voice-speech-or-language-disorders) 참고)을 사용하지만 보편적이지는 않습니다.
```

70 줄에서 같은 단어는 번역을 하셨는데 여기에는 번역을 안하셔서 같은 내용을 넣어놨습니다.

2023-02-24 06:35 UTC, cos18 commented on files/ko/learn/accessibility/what_is_accessibility/index.md
> +따라서 접근성을 위해서는 대체 텍스트가 제공되어야 합니다. 영상에는 수동으로 자막을 달고 오디오 컨텐츠에 대해서도 대본을 제공해야 합니다. 또, DHH 인구의 높은 언어 박탈([language deprivation](https://www.notion.so/6673cd1146724a14aa4f009c6b05af9c))을 고려해 [텍스트 단순화](https:
```suggestion
따라서 접근성을 위해서는 대체 텍스트가 제공되어야 합니다. 영상에는 수동으로 자막을 달고 오디오 컨텐츠에 대해서도 대본을 제공해야 합니다. 또, DHH 인구의 높은 [언어 박탈 (language deprivation)](https://www.notion.so/6673cd1146724a14aa4f009c6b05af9c))을 고려해 [텍스트 단순화](https://circlcenter.org/collaborative-research-automatic-text-simplification-and-reading-assistance-to-support-self-directed-learning-by-deaf-and-hard-of-hearing-computing-workers/)가 필요할 수 있습니다.
```

2023-02-24 06:35 UTC, cos18 commented on files/ko/learn/accessibility/what_is_accessibility/index.md
> +운동 장애를 고려한 웹 개발의 보편적인 요구 사항은 키보드를 통해 컨트롤(이 가능한 요소들)에 접근할 수 있도록 해야 한다**는 것입니다. 이 모듈의 다른 아티클에서 키보드 접근성에 대해 이야기하겠지만, 웹 사이트를 키보드만으로 사용하는 일을 한번 해보세요. 어떻게 될까요? Tab 키를 사용해 웹 form의 컨트롤 요소들을 왔다갔다 할 수 있나요? 키보드
```suggestion
운동 장애를 고려한 웹 개발의 보편적인 요구 사항은 키보드를 통해 컨트롤(이 가능한 요소들)에 접근할 수 있도록 해야 한다는 것입니다. 이 모듈의 다른 아티클에서 키보드 접근성에 대해 이야기하겠지만, 웹 사이트를 키보드만으로 사용하는 일을 한번 해보세요. 어떻게 될까요? Tab 키를 사용해 웹 form의 컨트롤 요소들을 왔다갔다 할 수 있나요? 키보드 컨트롤에 관련된 더 많은 이야기는 [Cross browser testing Using native keyboard accessibility](/ko/docs/Learn/Tools_and_testing/Cross_browser_testing/Accessibility#Using_native_keyboard_accessibility) 섹션에서 다루어집니다.
```

2023-02-24 06:35 UTC, cos18 commented on files/ko/learn/accessibility/what_is_accessibility/index.md
> +프로젝트 계획을 세울 때, 대상 데스크탑이나 모바일 브라우저와 같은 중요한 타겟 오디언스 세그먼트를 위한 테스팅과 함께 접근성 테스팅을 고려하세요. 빠르게, 자주 테스트하세요. 이상적인 방식은 자동화된 테스트를 통해 누락되어 있는 접근성 관련 피쳐들(예를 들어 이미지의 [대체 텍스트](/ko/docs/Learn/Tools_and_testing/Cross_
```suggestion
프로젝트 계획을 세울 때, 대상 데스크탑이나 모바일 브라우저와 같은 중요한 타겟 오디언스 세그먼트를 위한 테스팅과 함께 접근성 테스팅을 고려하세요. 빠르게, 자주 테스트하세요. 이상적인 방식은 자동화된 테스트를 통해 누락되어 있는 접근성 관련 기능들(예를 들어 이미지의 [대체 텍스트](/ko/docs/Learn/Tools_and_testing/Cross_browser_testing/Accessibility#Text_alternatives)나 잘못된 링크 텍스트. [Element relationships and context](/ko/docs/Learn/Tools_and_testing/Cross_browser_testing/Accessibility#Element_relationships_and_context)를 참고하세요)을 잡아내는 것입니다. 또, 장애가 있는 유저 그룹을 대상으로 일부 테스팅을 진행하며 그들이 복잡한 사이트 기능을 얼마나 잘 활용할 수 있는지 확인할 수 있습니다. 다음과 같은 기준을 사용할 수 있습니다.
```
번역이 누락된 내용과 번역투를 자연스럽게 수정했습니다.
`-` 대시에 대한 번역 가이드는 [이 내용](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md#-대시)을 참고 부탁드립니다!

2023-02-24 06:35 UTC, cos18 commented on files/ko/learn/accessibility/what_is_accessibility/index.md
>  ## Accessibility guidelines and the law
```suggestion
## 접근성 지침 및 법률
```
번역이 누락되어 있습니다.

2023-02-24 06:35 UTC, cos18 commented on files/ko/learn/accessibility/what_is_accessibility/index.md
> +- WC3에서 나라 별로 [Web Accessibility Laws & Policies](https://www.w3.org/WAI/policies/) 목록을 관리하고 있습니다.
```suggestion
- 당신의 국가에 웹 사이트의 접근성 제공 필요성에 대한 법률이 있을 수도 있습니다. 예를 들어 EU의 [EN 301 549](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/02.01.02_60/en_301549v020102p.pdf), 미국의 [Section 508 of the Rehabilitation Act](https://www.section508.gov/training/), 독일의 [Federal Ordinance on Barrier-Free Information Technology](https://www.einfach-fuer-alle.de/artikel/bitv_english/), 영국의 [Accessibility Regulations 2018](https://www.legislation.gov.uk/uksi/2018/952/introduction/made), 이탈리아의 [Accessibilità](https://www.agid.gov.it/it/design-servizi/accessibilita), 호주의 [Disability Discrimination Act](https://humanrights.gov.au/our-work/disability-rights/world-wide-web-access-disability-discrimination-act-advisory-notes-ver) 등이 있습니다. WC3에서 나라 별로 [웹 접근성 법률 및 정책](https://www.w3.org/WAI/policies/) 목록을 관리하고 있습니다.
```
위 대쉬 번역 가이드를 적용하였습니다.
추가로 번역은 최대한 원문 형식에 따라서 작성해야합니다. 원문에서는 하나의 항목으로 이루어진 내용을 세 개의 항목으로 분리하셔서 이를 합쳤습니다.

2023-02-24 06:35 UTC, cos18 commented on files/ko/learn/accessibility/what_is_accessibility/index.md
> +웹 앱의 HTML 요소들이 제공하는 네이티브 시맨틱 정보가 부족한 경우는 접근성 트리에 시맨틱 정보를 추가해 접근성을 개선하는 [WAI-ARIA specification](https://www.w3.org/TR/wai-aria/)의 기능들로 보완이 가능합니다. 이 모듈의 [WAI-ARIA basics](/ko/docs/Learn/Accessibility/
```suggestion
웹 앱의 HTML 요소들이 제공하는 네이티브 시맨틱 정보가 부족한 경우는 접근성 트리에 시맨틱 정보를 추가해 접근성을 개선하는 [WAI-ARIA 명세서](https://www.w3.org/TR/wai-aria/)의 기능들로 보완이 가능합니다. 이 모듈의 [WAI-ARIA basics](/ko/docs/Learn/Accessibility/WAI-ARIA_basics)에서 더 많은 내용을 설명합니다.
```

[ko glossary-guide](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md)에 등록된 단어로 번역했습니다.

2023-02-24 06:35 UTC, cos18 commented on files/ko/learn/accessibility/what_is_accessibility/index.md
> +  sourceCommit: 3f24b87ec5ef32a046aa9cabd19a4ced0041385c
앞으로 기여를 하실 때 페이지 갱신 상태를 확인할 수 있는 'sourceCommit' 메타데이터 값을 추가하셔야 합니다. [이 글](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md#페이지-갱신-표시) 참고 부탁드립니다!

2023-03-01 15:01 UTC, se030 commented on files/ko/learn/accessibility/what_is_accessibility/index.md
> +아래에는 생각해보아야 하는 장애의 주요 유형들이 설명되어 있습니다. 웹 컨텐츠에 접근하기 위해 사용하는 특별한 도구가 있다면 함께 살펴보겠습니다. 이런 도구들은 보조 기술(**assistive technology**, 또는 **AT**)이라고 불립니다.
한국어에서 기술을 복수형으로 잘 사용하지 않아서 그렇게 했던 것 같습니다. 원문대로 작성해도 좋습니다 :)

2023-03-01 15:06 UTC, se030 commented on files/ko/learn/accessibility/what_is_accessibility/index.md
> +  sourceCommit: 3f24b87ec5ef32a046aa9cabd19a4ced0041385c
리뷰 주신 부분들 반영했습니다. 가이드 링크들 감사드려요.
가이드 참고했다고 생각했는데 익숙하지 않아서 빠뜨린 부분이 많았네요. ㅠㅠ
분량이 많았는데 꼼꼼하게 봐주시느라 고생하셨습니다! 👍🏻

2023-03-02 06:10 UTC, cos18 approved these changes
LGTM! 수고하셨습니다 :)

2023-03-02 07:13 UTC, cos18 commented
@se030 Lint 문제가 있는거같은데 제가 확인 & 수정 후 머지해드리겠습니다!

2023-03-08 10:02 UTC, se030 commented
@cos18

안녕하세요 리뷰어님! 린팅 확인해서 커밋했습니다. 편하실 때 확인해주세요!
제 로컬에서는 아래 룰에서 에러가 뜨는데 리모트에서는 지금 괜찮아 보이네요.

```jsonc
// .markdownlint-cli2.jsonc ln131

    "search-replace": {
      "rules": [
        {
          "name": "nbsp",
          "message": "Don't use no-break spaces",
          "searchPattern": "/ /g",
          "replace": " ",
          "skipCode": false
        },
```

그리고 하나 궁금한게 있는데 아티클 길이가 길 때 PR을 여러개로 나누는게 더 좋은가요?
리뷰 해주시는 분들 편의나 문서 로그 관리 면에서 나누는게 좋은지 하나의 문서라면 PR 하나 단위로 하는게 좋을지 궁금해서 질문 드려요.

2023-03-09 01:58 UTC, merged

2023-03-09 02:04 UTC, cos18 commented
@se030 앗 제가 이 피알 확인한다고 놔두다가 까먹어버렸네요 ㅠㅠ 멘션 감사합니다!
앞으로도 저나 다른 리뷰어가 처리가 늦다면 직접 멘션하시거나 공식 디스코드, 오픈카톡방을 통해 알려주시면 빠르게 조치하도록 하겠습니다.

일단 저희 공식 규정은 "번역을 할 땐 모든 문서에 대해 번역해 PR을올려야 한다“ 여서 여러 문서를 동시에 번역해도 건드린 문서들은 모두 번역하는게 원칙적으론 맞습니다.
다만 길이가 너무 길어 기여하시기 어려운 경우에는 일부 파트만 번역하셔서 PR을 올리셔도 되요. 그래도 문서 전체를 번역하신다면 무조건 한 PR로 올리시는게 conflict 가 안나는 방법이라 그렇게 권장드립니다.

늦었지만 기여 감사드립니다! 오늘도 좋은 하루 보내세요 :)