ko: JavaScript/Guide/Introduction
mdn/translated-content pull request #11845
Opened 2023-02-22 15:03 UTC by SnowMarble

2023-03-09 16:19 UTC, hochan222 requested changes
리뷰가 늦어져서 죄송합니다.

고생 많으셨습니다. 몇 가지 리뷰 사항 남겨두었습니다! 참고 부탁드려용!

2023-03-09 16:19 UTC, hochan222 commented on files/ko/web/javascript/guide/introduction/index.md
> +이 챕터에선 JavaScript를 소개하고 몇 가지 기본 개념을 다룹니다.
```suggestion
이 장에서는 JavaScript를 소개하고 몇 가지 기본 개념에 대해 설명합니다.
```

는 어떤가요? chapter를 장이아닌 챕터로 번역하신 이유가 궁금합니다!

2023-03-09 16:19 UTC, hochan222 commented on files/ko/web/javascript/guide/introduction/index.md
> +- 인터넷과 월드 와이드 웹 ([WWW](/en-US/docs/Glossary/World_Wide_Web))에 대한 일반적인 이해.
```suggestion
- 인터넷과 월드 와이드 웹 ([WWW](/ko/docs/Glossary/World_Wide_Web))에 대한 일반적인 이해.
```

2023-03-09 16:19 UTC, hochan222 commented on files/ko/web/javascript/guide/introduction/index.md
> +- HyperText Markup Language ([HTML](/en-US/docs/Glossary/HTML))에 대한 적절한 실무 지식.
```suggestion
- HyperText Markup Language ([HTML](/ko/docs/Glossary/HTML))에 대한 적절한 실무 지식.
```

2023-03-09 16:19 UTC, hochan222 commented on files/ko/web/javascript/guide/introduction/index.md
> +JavaScript가 처음이라면, [학습터](/ko/docs/Learn)와 [JavaScript 안내서](/ko/docs/Web/JavaScript/Guide)부터 시작해 보세요. 기본 사항을 확실히 이해했다면 [JavaScript 참고서](/ko/docs/Web/JavaScript/Reference)에서 개별 개체 및 명령문에 대한 자세한 내용을 확인할
```suggestion
JavaScript가 처음이라면, [학습터](/ko/docs/Learn)와 [JavaScript 안내서](/ko/docs/Web/JavaScript/Guide)부터 시작해 보세요. 기본 사항을 확실히 이해했다면 [JavaScript 참고서](/ko/docs/Web/JavaScript/Reference)에서 개별 객체 및 명령문에 대한 자세한 내용을 확인할 수 있습니다.
```

2023-03-09 16:19 UTC, hochan222 commented on files/ko/web/javascript/guide/introduction/index.md
> +ECMA-262 표준은 또한 IOS-16262로서 [ISO](http://www.iso.ch/) (국제 표준화 기구) 에 의해 승인되었습니다. [Ecma International website](http://www.ecma-international.org/publications/standards/Ecma-262.htm) 에서 그 명세를 찾을 수 있습니다.
```suggestion
ECMA-262 표준은 또한 IOS-16262로서 [ISO](http://www.iso.ch/) (국제 표준화 기구)에 의해 승인되었습니다. [Ecma International website](http://www.ecma-international.org/publications/standards/Ecma-262.htm) 에서 그 명세를 찾을 수 있습니다. ECMAScript 명세는 [World Wide Web Consortium (W3C)](http://www.w3.org/) 나 [WHATWG (Web Hypertext Application Technology Working Group)](https://whatwg.org/)에 의해 표준화된 Document Object Model (DOM)을 설명하지 않습니다. DOM은 HTML 문서 객체가 스크립트에 노출되는 방식을 정의합니다. JavaScript로 프로그래밍할 때 사용되는 다양한 기술에 대한 더 나은 아이디어를 얻으려면, [JavaScript 기술 개요](/ko/docs/Web/JavaScript/JavaScript_technologies_overview) 기사를 참고하세요.
```

2023-03-09 16:19 UTC, hochan222 commented on files/ko/web/javascript/guide/introduction/index.md
> +웹 콘솔의 한 줄 입력 모드는 JavaScript 표현식을 빠르게 테스트하는 데 적합합니다. 그리고 여러 줄을 실행할 수도 있지만 그리 편리하지 않습니다. 보다 복잡한 JavaScript의 경우 [여러 줄 입력 모드](https://firefox-source-docs.mozilla.org/devtools-user/web_console/the_command
```suggestion
웹 콘솔의 한 줄 입력 모드는 JavaScript 표현식을 빠르게 테스트하는 데 적합합니다. 그리고 여러 줄을 실행할 수도 있지만 그리 편리하지 않습니다. 더 복잡한 JavaScript의 경우 [여러 줄 입력 모드](https://firefox-source-docs.mozilla.org/devtools-user/web_console/the_command_line_interpreter/index.html#multi-line-mode)를 사용할 수 있습니다.
```

2023-03-09 22:05 UTC, SnowMarble commented on files/ko/web/javascript/guide/introduction/index.md
> +이 챕터에선 JavaScript를 소개하고 몇 가지 기본 개념을 다룹니다.
챕터가 더 문장을 빠르게 이해할 수 있지 않을까라고 생각했습니다. 그리고 큰 고민없이 썼는데, 챕터가 외래어가 아닌걸 미처 찾아보진 못했네요. 👍

2023-03-09 22:09 UTC, SnowMarble commented on files/ko/web/javascript/guide/introduction/index.md
> +JavaScript는 웹 페이지를 대화식(예: 복잡한 애니메이션, 클릭 가능한 버튼, 팝업 메뉴 등)으로 만드는 데 사용되는 크로스 플랫폼, 객체 지향 스크립팅언어입니다. 또한 Node.js와 같이 파일을 다운로드하는 것보다 더 많은 기능(예: 여러 컴퓨터 간의 실시간 공동 작업)을 웹 사이트에 추가할 수 있는 JavaScript의 고급 서버 측 버전도
[사전](https://opendict.korean.go.kr/dictionary/view?sense_no=731902&viewType=confirm)엔 "스크립팅^언어"로 표기되어 있는는데, 앞으로도 "^"이 포함된 단어는 붙여쓰는걸 선호하도록 할까요?

2023-03-09 22:11 UTC, SnowMarble commented on files/ko/web/javascript/guide/introduction/index.md
> +반면에, JavaScript는 HyperTalk 과 dBASE 같은 더 작고 동적인 형지정이 가능한 언어들의 정신을 계승했습니다. 이러한 스크립팅언어는 더 쉬운 구문과 특별한 내장 기능, 그리고 객체 생성을 위한 최소 요구사항으로 인해 훨씬 더 많은 사람들에게 프로그래밍 도구를 제공합니다.
typed array를 형식화 배열이라고 하고 있는것 처럼, 모두 형 지정으로 바꾸는건 어떨까요?

2023-03-09 23:25 UTC, hochan222 commented on files/ko/web/javascript/guide/introduction/index.md
> +반면에, JavaScript는 HyperTalk 과 dBASE 같은 더 작고 동적인 형지정이 가능한 언어들의 정신을 계승했습니다. 이러한 스크립팅언어는 더 쉬운 구문과 특별한 내장 기능, 그리고 객체 생성을 위한 최소 요구사항으로 인해 훨씬 더 많은 사람들에게 프로그래밍 도구를 제공합니다.
네! 사실 이 부분 리뷰를 드릴까 고민하다가 드리지 않았는데 저도 형 지정이 더 좋아보입니다.

2023-03-10 00:59 UTC, SnowMarble commented
@hochan222 수고하셨습니다!😉

2023-03-10 01:47 UTC, hochan222 approved these changes
LGTM :)

좋은 하루 보내세용!

2023-03-10 01:47 UTC, hochan222 commented on files/ko/web/javascript/guide/introduction/index.md
> +Java는 빠른 실행과 타입 안전성을 위해 설계된 클래스 기반 프로그래밍 언어입니다. 형 안전성은, 예를 들어, 여러분이 Java 정수를 객체의 레퍼런스로 형변환 하거나 Java 바이트코드를 변경하여 private 메모리에 접근할 수 없음을 의미합니다. Java의 클래스 기반 모델은 프로그램이 오로지 클래스와 그 메서드로만 구성된다는 것을 뜻합니다. Ja
```suggestion
Java는 빠른 실행과 형 안전성을 위해 설계된 클래스 기반 프로그래밍 언어입니다. 형 안전성은, 예를 들어, 여러분이 Java 정수를 객체의 레퍼런스로 형변환 하거나 Java 바이트코드를 변경하여 private 메모리에 접근할 수 없음을 의미합니다. Java의 클래스 기반 모델은 프로그램이 오로지 클래스와 그 메서드로만 구성된다는 것을 뜻합니다. Java의 클래스 상속과 강한 형 지정은 보통 단단하게 결합된 객체 계층구조를 요구합니다. 이러한 요구는 Java 프로그래밍을 JavaScript 프로그래밍보다 더 복잡하게 만듭니다.
```

2023-03-10 02:10 UTC, merged