[ko] Translate: Grid template columns
mdn/translated-content pull request #11932
Opened 2023-02-28 08:25 UTC by sunhpark42

### Description

Grid template columns  번역입니다.

### Related issues and pull requests

fixes #11466

2023-03-07 13:54 UTC, yujo11 requested changes
안녕하세요 선희님~

전체적으로 깔끔하게 잘 번역해주신거 같아요!

간단한 코멘트 남긴 것만 확인하고 반영 부탁드리겠습니다!

2023-03-07 13:54 UTC, yujo11 commented on files/ko/web/css/grid-template-columns/index.md
> +### Specifying grid column sizes
이 부분도 같이 번역해주시면 좋겠네요!

2023-03-09 18:19 UTC, hochan222 requested changes
@sunhpark42 님 안녕하세요.

고생 많으셨습니다. 몇 가지 리뷰 남겨두었습니다. 참고 부탁드려요 :)

2023-03-09 18:19 UTC, hochan222 commented on files/ko/web/css/grid-template-columns/index.md
> +  - 해당 위치의 각 열에 대한 이름을 명시하는 [`<custom-ident>`](/en-US/docs/Web/CSS/custom-ident) 입니다. ident는 예약어인 `span` 이나 `auto`를 제외한 어떤 문자열이든 올 수 있습니다. 라인들은 대괄호 안에 공백으로 구분된 여러개의 이름을 가질 수 있습니다. 예시) `[line-name-a l
```suggestion
  - 해당 위치의 각 열에 대한 이름을 명시하는 [`<custom-ident>`](/ko/docs/Web/CSS/custom-ident) 입니다. ident는 예약어인 `span` 이나 `auto`를 제외한 어떤 문자열이든 올 수 있습니다. 행에는 `[line-name-a line-name-b]`와 같이 대괄호 안에 공백으로 구분된 여러 이름을 가질 수 있습니다.
```

최대한 원문 그대로 번역하는것을 권장합니다.

2023-03-09 18:19 UTC, hochan222 commented on files/ko/web/css/grid-template-columns/index.md
> +  - 음수가 아닌 그리드 컨테이너의 내부 크기에 상대적인 {{cssxref("percentage", "&lt;percentage&gt;")}} 값입니다. 막약 그리드 컨테이너의 크기가 트랙의 크기에 따라 달라지는 경우, `percentage`값은 `auto`. 로 취급됩니다.
```suggestion
  - 음수가 아닌 그리드 컨테이너의 내부 크기에 상대적인 {{cssxref("percentage", "&lt;percentage&gt;")}} 값입니다. 만약 그리드 컨테이너의 크기가 트랙의 크기에 따라 달라지는 경우, 백분율을 `auto`로 처리해야 합니다.
```

[inline-code 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md#inline-code)에 따라 inline block은 번역하지 않으며, inline block이 원문에서 아닌것을 inline으로 표기할 수 없습니다.

2023-03-09 18:19 UTC, hochan222 commented on files/ko/web/css/grid-template-columns/index.md
> +    트랙의 본질적인 크기 기여는 그리드 컨테이너의 크기에 맞게 조젇될 수 있고, 백분율에 맞는 최소 크기 만큼 트랙의 최종크기를 증가시킬 수 있습니다.
```suggestion
    트랙의 본질적인 크기 기여는 그리드 컨테이너의 크기로 조정될 수 있으며, 트랙의 최종 크기를 백분율에 맞는 최소 크기 만큼 증가시킬 수 있습니다.
```

2023-03-09 18:19 UTC, hochan222 commented on files/ko/web/css/grid-template-columns/index.md
> +  - 트랙의 Flex 요소를 지정하는 `fr`단위를 가지는 음이 아닌 차원입니다. 각각의 `<flex>`에 크기가 정해진 트랙은 flex 요소에 비례하여 남은 공간을 차지합니다.
```suggestion
  - 트랙의 Flex 요소를 지정하는 `fr` 단위를 가지는 음이 아닌 치수입니다. 각각의 `<flex>`에 크기가 정해진 트랙은 flex 요소에 비례하여 나머지 공간을 공유합니다.
```

dimension을 길이로 번역하는것이 좋아보입니다.

> a share of the remaining space

누락된 부분을 추가했습니다.

2023-03-09 18:19 UTC, hochan222 commented on files/ko/web/css/grid-template-columns/index.md
> +  - 그리드 트랙을 차지하는 그리드 아이템의 가장 큰 [maximal content contribution](https://www.w3.org/TR/css-sizing-3/#max-content)를 의미합니다. 예를들어, 만약 그리드 트랙의 첫번째 엘리먼트가 _"Repetitio est mater studiorum"_ 라는 문장을 포함하고, 두번째 엘리
```suggestion
  - 그리드 트랙을 차지하는 그리드 항목의 가장 큰 [최대 콘텐츠 기여도](https://www.w3.org/TR/css-sizing-3/#max-content)를 의미합니다. 예를 들어, 만약 그리드 트랙의 첫번째 요소가 "Repetitio est mater studiorum" 라는 문장을 포함하고, 두번째 요소가 "Dum spiro, spero"을 포함한다면, 최대 콘텐츠 기여(maximal content contribution)는 모든 그리드 요소들에서 가장 긴 "Repetitio est mater studiorum" 문장의 크기가 됩니다.
```

[단어 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md#%EA%B3%B5%ED%86%B5-%EC%9A%A9%EC%96%B4)에 따라 content는 "콘텐츠"로 번역부탁드립니다.

2023-03-12 03:36 UTC, sunhpark42 commented on files/ko/web/css/grid-template-columns/index.md
> +- [`masonry`](/en-US/docs/Web/CSS/CSS_Grid_Layout/Masonry_Layout) {{Experimental_Inline}}
오 존재하지 않아도 알아서 리다이렉트 되는군요? 새로운 사실 하나 알고갑니다 👍👍 (ko 페이지 존재하는지 하나하나 확인하고 있었던건 안비밀..)

2023-03-12 03:50 UTC, sunhpark42 commented on files/ko/web/css/grid-template-columns/index.md
> +  - 트랙의 Flex 요소를 지정하는 `fr`단위를 가지는 음이 아닌 차원입니다. 각각의 `<flex>`에 크기가 정해진 트랙은 flex 요소에 비례하여 남은 공간을 차지합니다.
a share of the remaining space 는 공유 하다라는 의미보다는 flex 요소 내의 여러 share중, 남은 영역의 share, 즉 남은 부분을 차지한다는 의미가 적합하다고 생각합니다. 어떻게 생각하시나요?

2023-03-12 08:01 UTC, hochan222 commented on files/ko/web/css/grid-template-columns/index.md
> +  - 트랙의 Flex 요소를 지정하는 `fr`단위를 가지는 음이 아닌 차원입니다. 각각의 `<flex>`에 크기가 정해진 트랙은 flex 요소에 비례하여 남은 공간을 차지합니다.
차지한다가 더 적합해보입니다. 감사합니다 :)

2023-03-12 08:02 UTC, hochan222 approved these changes

2023-03-12 08:02 UTC, hochan222 commented
고생 넘넘 많으셨습니다! 좋은 주말 보내세요 :)

2023-03-12 08:02 UTC, merged

2023-03-12 09:36 UTC, sunhpark42 commented
아이고 잠깐 추가로 볼 거 있나 했는데, 확인하셨군용. 리뷰 감사합니다~ 좋은 주말 보내세용!