[zh-tw] translate some articles in WebAssembly/Reference/Control_flow
mdn/translated-content pull request #11967
Opened 2023-03-02 03:34 UTC by shiyou0130011

### Description

翻譯以下兩個條目

1. WebAssembly/Reference/Control_flow/unreachable
2. WebAssembly/Reference/Control_flow/br

2023-03-03 02:43 UTC, yin1999 commented on files/zh-tw/webassembly/reference/control_flow/br/index.md
> +**`br`** 是讓程式跳躍至指定區塊（可能是loop 、 block 或是 if）。
下文也请修改一下，具体规则在[这里](https://github.com/mdn/translated-content/blob/main/docs/zh-tw/translation-guide.md#%E4%B8%AD%E6%96%87%E5%8F%8A%E6%8B%89%E4%B8%81%E8%AA%9E%E7%B3%BB%E6%96%87%E5%AD%97%E9%96%93%E4%B8%8D%E5%8A%A0%E4%BF%AE%E9%A3%BE%E7%A9%BA%E7%99%BD)：

```suggestion
**`br`** 是讓程式跳躍至指定區塊（可能是 loop、block 或是 if）。
```

2023-03-03 14:09 UTC, SiongSng commented on files/zh-tw/webassembly/reference/control_flow/unreachable/index.md
> +| 指令          | 二進制操作碼 |
```suggestion
| 指令          | 二進制運算碼 |
```

2023-03-03 14:09 UTC, SiongSng commented on files/zh-tw/webassembly/reference/control_flow/br/index.md
> +| 指令          | 二進制操作碼 |
```suggestion
| 指令          | 二進制運算碼 |
```

2023-03-03 14:14 UTC, SiongSng requested changes
運算碼（OP Code）為繁體中文（台灣）的常見譯法

2023-03-03 14:14 UTC, SiongSng commented on files/zh-tw/webassembly/reference/control_flow/br/index.md
> +| 指令          | 二進制操作碼 |
```suggestion
| 指令          | 二進制 opcode |
```
建議保留原文或者譯為 `運算碼` 之類的

2023-03-03 14:14 UTC, SiongSng commented on files/zh-tw/webassembly/reference/control_flow/unreachable/index.md
> +| 指令          | 二進制操作碼 |
```suggestion
| 指令          | 二進制 opcode |
```
建議保留原文或者譯為 `運算碼` 之類的

2023-03-07 00:32 UTC, shiyou0130011 commented on files/zh-tw/webassembly/reference/control_flow/br/index.md
> +**`br`** 是讓程式跳躍至指定區塊（可能是loop 、 block 或是 if）。
已修改了

2023-03-07 00:35 UTC, shiyou0130011 commented on files/zh-tw/webassembly/reference/control_flow/br/index.md
> +| 指令          | 二進制操作碼 |
我剛特地去查了「國家教育研究院 雙語詞彙、學術名詞暨辭書資訊網」，絕大多數學術領域都使用「運算碼」，所以照你意見改成「運算碼」

2023-03-07 05:35 UTC, merged

2023-03-07 05:35 UTC, irvin commented
thanks