Translate test html images to es
mdn/translated-content pull request #11994
Opened 2023-03-03 21:50 UTC by adairo

### Description

Hola! Esta vez es la traducción del ejercicio de evaluación sobre imágenes en HTML 

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML/Test_your_skills:_HTML_images

### Motivation
### Additional details
### Related issues and pull requests

2023-03-03 22:02 UTC, adairo commented
Hola @Graywolf9 justo me estaba dando cuenta de que se coló el archivo del anterior PR. Para resolverlo actualicé mi repositorio local, lo mezclé con el nuevo trabajo y resolví el conflicto entre las dos versiones distintas del archivo del anterior PR. El problema es que no me deja hacer push porque en mi repositorio remoto ya hay una versión más reciente y me aparece que primero debo hacer un pull.

 ¿Cómo le hiciste para simplemente borrar ese archivo? 😵

2023-03-03 22:09 UTC, Graywolf9 commented
Lo borré directamente desde aquí, con la interfaz de GitHub, perdón por alterar el flujo de tu rama, creo que si quieres hacer más cambios desde local, lo más fácil sería borrar la rama local y volver a hacer fetch para traer la de GitHub. También para evitar que se agreguen archivos yo siempre regreso a `main` hago `git pull` y a partir de ahí creo la nueva rama

2023-03-03 23:15 UTC, Graywolf9 reviewed
Sugerencias menores

2023-03-03 23:15 UTC, Graywolf9 commented on files/es/learn/html/multimedia_and_embedding/images_in_html/test_your_skills_colon__html_images/index.md
> +> **Importante:**
Error nuestro, falta agregarlo a la lista de traducción de palabras

```suggestion
> **Observación:**
```

2023-03-03 23:15 UTC, Graywolf9 commented on files/es/learn/html/multimedia_and_embedding/images_in_html/test_your_skills_colon__html_images/index.md
> +intenta actualizar el siguiente código vivo para recrear el ejemplo finalizado:
```suggestion
Intenta actualizar el siguiente código vivo para recrear el ejemplo finalizado:
```

2023-03-03 23:15 UTC, Graywolf9 commented on files/es/learn/html/multimedia_and_embedding/images_in_html/test_your_skills_colon__html_images/index.md
> +> **Importante:**
```suggestion
> **Observación:**
```

2023-03-03 23:15 UTC, Graywolf9 commented on files/es/learn/html/multimedia_and_embedding/images_in_html/test_your_skills_colon__html_images/index.md
> +> **Importante:**
```suggestion
> **Observación:**
```

2023-03-03 23:15 UTC, Graywolf9 commented on files/es/learn/html/multimedia_and_embedding/images_in_html/test_your_skills_colon__html_images/index.md
> +intenta actualizar el siguiente código vivo para recrear el ejemplo finalizado:
```suggestion
Intenta actualizar el siguiente código vivo para recrear el ejemplo finalizado:
```

2023-03-03 23:15 UTC, Graywolf9 commented on files/es/learn/html/multimedia_and_embedding/images_in_html/test_your_skills_colon__html_images/index.md
> +2. Escribe una publicación en la que pides asesoría y/o ayuda en el [foro de MDN Discourse en la categoría de aprendizaje](https://discourse.mozilla.org/c/mdn/learn/250). Tu publicación debe incluir:
```suggestion
2. Escribe una publicación en la que pides asesoría y/o ayuda en el [foro de Discourse de MDN  en la categoría de aprendizaje](https://discourse.mozilla.org/c/mdn/learn/250). Tu publicación debe incluir:
```

2023-03-03 23:16 UTC, Graywolf9 commented on files/es/learn/html/multimedia_and_embedding/images_in_html/test_your_skills_colon__html_images/index.md
> +2. Escribe una publicación en la que pides asesoría y/o ayuda en el [foro de Discourse de MDN  en la categoría de aprendizaje](https://discourse.mozilla.org/c/mdn/learn/250). Tu publicación debe incl
```suggestion
2. Escribe una publicación en la que pides asesoría y/o ayuda en el [foro de Discourse de MDN en la categoría de aprendizaje](https://discourse.mozilla.org/c/mdn/learn/250). Tu publicación debe incluir:
```

2023-03-03 23:18 UTC, Graywolf9 requested changes
Detalle

2023-03-03 23:18 UTC, Graywolf9 commented on files/es/learn/html/multimedia_and_embedding/images_in_html/test_your_skills_colon__html_images/index.md
> +  sourceCommit: ad20678be564e8df6495c2f352dc0daaa88371b7
A mi me aparece este commit como el último de ese archivo, ¿cómo obtuviste el tuyo?

```suggestion
  sourceCommit: 8e2641ebe076ab89299c77a51ece882de4ba5efb
```

2023-03-04 02:03 UTC, adairo commented
> Lo borré directamente desde aquí, con la interfaz de GitHub, perdón por alterar el flujo de tu rama, creo que si quieres hacer más cambios desde local, lo más fácil sería borrar la rama local y volver a hacer fetch para traer la de GitHub. También para evitar que se agreguen archivos yo siempre regreso a `main` hago `git pull` y a partir de ahí creo la nueva rama

No se me ocurrió hacer eso que mencionas. No te preocupes en lo absoluto estuvo mucho mejor así jeje 
Precisamente el error vino por empezar a trabajar en la rama local pre-merged del anterior PR. Seguiré ese consejo muchas gracias 👌

2023-03-04 02:06 UTC, adairo commented on files/es/learn/html/multimedia_and_embedding/images_in_html/test_your_skills_colon__html_images/index.md
> +  sourceCommit: ad20678be564e8df6495c2f352dc0daaa88371b7
Ahora que lo mencionas me surge una gran duda. 

Ese commit era el último del repositorio `content` pero ahora que lo mencionas creo que en realidad debo poner el último commit en el que se modificó dicho archivo. ¿Es esto correcto?

2023-03-04 18:00 UTC, JuanVqz commented on files/es/learn/html/multimedia_and_embedding/images_in_html/test_your_skills_colon__html_images/index.md
> +  sourceCommit: ad20678be564e8df6495c2f352dc0daaa88371b7
@adairo es correcto!

2023-03-05 17:51 UTC, adairo commented on files/es/learn/html/multimedia_and_embedding/images_in_html/test_your_skills_colon__html_images/index.md
> +  sourceCommit: ad20678be564e8df6495c2f352dc0daaa88371b7
@JuanVqz Todo este tiempo lo había entendido mal, disculpen. Muchas gracias por aclararlo :)

2023-03-05 19:28 UTC, JuanVqz commented on files/es/learn/html/multimedia_and_embedding/images_in_html/test_your_skills_colon__html_images/index.md
> +  sourceCommit: ad20678be564e8df6495c2f352dc0daaa88371b7
Ntp, crees que se debe mejorar el documento al respecto? Donde lo leíste?

si recuerdas haber agregado el sha "equivocado" en otros documentos podrías por favor actualizarlos? 

Muchas gracias por contribuir y disculpa la condición, también gracias por preguntar y confirmar lo que se espera 👍

2023-03-05 22:06 UTC, adairo commented on files/es/learn/html/multimedia_and_embedding/images_in_html/test_your_skills_colon__html_images/index.md
> +  sourceCommit: ad20678be564e8df6495c2f352dc0daaa88371b7
Me parece que eso no se menciona en la [guía para traducir (es)](https://github.com/mdn/translated-content/tree/main/docs/es).

En las anteriores ocasiones Alex me ayudó a corregir ese aspecto, el error fue más que nada que yo asumí que tenía que poner el último commit del repo. 

No te preocupes, al contrario te agradezco por responder mi duda, la siguiente vez ya estará el sha de forma correcta :)  

Saludos

2023-03-06 16:00 UTC, Graywolf9 approved these changes
Nuevamente, muchas gracias por la excelente traducción, una vez aclarado lo del hash, hacemos el merge

Gracias!

2023-03-06 16:01 UTC, merged

2023-03-06 16:15 UTC, adairo commented
Muchas gracias a ti @Graywolf9 para mi es un gusto :)