ko: URL이란?
mdn/translated-content pull request #12008
Opened 2023-03-04 11:49 UTC by SnowMarble

#11911

* ko/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL
* ko/docs/Glossary/Hypertext

2023-03-28 17:51 UTC, cos18 requested changes
안녕하세요! 늦은 리뷰 죄송합니다 ㅠㅠ
남겨놓은 커멘트 확인 부탁드립니다!
추가로 이미지를 추가하셨는데 제가 yari를 통해 돌려본 결과 translate-content에 이미지 파일을 올리지 않아도 알아서 content 레포의 이미지로 폴백하는거 같은데, 파일이 꼭 translate-content 레포에 필요한가요? 제가 보기엔 필요없는거같은데 PR에서 지우는게 좋은 것 같아요!

2023-03-28 17:51 UTC, cos18 commented on files/ko/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +**URL**은 *Uniform Resource Locator*의 약자입니다. URL은 웹에서 주어진 고유 리소스 주소에 지나지 않습니다. 이론적으로 각각의 유효한 URL은 고유한 리소스를 가리킵니다. 이러한 리소스는 HTML 페이지, CSS 문서, 이미지 등이 될 수 있습니다. 실제로는 몇 가지 예외가 있으며 가장 일반적인 예외는 더 이상 존재하지 않거
```suggestion
**URL**은 _Uniform Resource Locator_ 의 약자입니다. URL은 웹에서 주어진 고유 리소스 주소에 지나지 않습니다. 이론적으로 각각의 유효한 URL은 고유한 리소스를 가리킵니다. 이러한 리소스는 HTML 페이지, CSS 문서, 이미지 등이 될 수 있습니다. 실제로는 몇 가지 예외가 있으며 가장 일반적인 예외는 더 이상 존재하지 않거나 이동된 리소스를 가리키는 URL입니다. URL로 표시되는 리소스와 URL 자체는 웹 서버에서 처리되므로 해당 리소스와 관련 URL을 신중하게 관리하는 것은 웹 서버 소유자에게 달려 있습니다.
```

원문에 최대한 유지해 `_` 를 넣어봤습니다.

2023-03-28 17:51 UTC, cos18 commented on files/ko/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +- 도메인은 요청하는 웹 서버를 나타냅니다. 도메인은 일반적으로 [도메인 이름](/ko/docs/Learn/Common_questions/Web_mechanics/What_is_a_domain_name)이지만 IP 주소도 사용될 수 있습니다. (그러나 이것은 훨씬 불편하기 때문에 자주 사용하지 않습니다.)
```suggestion
- 도메인은 요청하는 웹 서버를 나타냅니다. 도메인은 일반적으로 [도메인 이름](/ko/docs/Learn/Common_questions/Web_mechanics/What_is_a_domain_name)이지만 [IP 주소](/ko/docs/Glossary/IP_Address)도 사용될 수 있습니다. (그러나 이것은 훨씬 불편하기 때문에 자주 사용하지 않습니다.)
```
원문에 있는 링크가 누락돼 추가했습니다.

2023-03-28 17:51 UTC, cos18 commented on files/ko/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +[다음에 설명할](/ko/docs/Learn/HTML/Introduction_to_HTML) HTML 언어는 URL을 광범위하게 사용합니다.
```suggestion
[다음](/ko/docs/Learn/HTML/Introduction_to_HTML)에 설명할 [HTML](/ko/docs/Glossary/HTML) 언어는 URL을 광범위하게 사용합니다.
```
HTML 링크를 추가하고, `다음에 설명할` 과 `HTML`을 구분하기 위해 링크 범위를 수정했습니다.

2023-03-28 17:51 UTC, cos18 commented on files/ko/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +URL이 HTML 페이지와 같은 문서 내에서 사용되는 경우, 상황이 약간 다릅니다. 브라우저에는 이미 문서 고유의 URL이 있기 때문에 이 정보를 사용하여 해당 문서 내에서 사용할 수 있는 URL의 누락된 부분을 채울 수 있습니다. URL의 경로 부분만 보면 **절대 URL**과 **상대 URL**을 구별할 수 있습니다. URL의 **경로** 부분이 "`
`*` 로 넣으신 절대, 상대 URL을 `_`로 수정 부탁드립니다! `_` 넣으실 때 단어를 붙어놓으면 적용되지 않으니 위 피드백 참고 부탁드려요!

2023-03-28 22:06 UTC, SnowMarble commented
> 안녕하세요! 늦은 리뷰 죄송합니다 ㅠㅠ 남겨놓은 커멘트 확인 부탁드립니다! 추가로 이미지를 추가하셨는데 제가 yari를 통해 돌려본 결과 translate-content에 이미지 파일을 올리지 않아도 알아서 content 레포의 이미지로 폴백하는거 같은데, 파일이 꼭 translate-content 레포에 필요한가요? 제가 보기엔 필요없는거같은데 PR에서 지우는게 좋은 것 같아요!

영어 문서 변경으로 이미지가 삭제되거나 이름이 변경되는 경우가 우려되어 추가했습니다. yari가 어떻게 사진을 찾는지 찾아보진 않았지만, 이런 경우엔 어떻게 되나요? 최신화가된 다른 지역은 사진 파일을 추가하진 않았던데, 사진에 대한 가이드가 있었으면 좋겠습니다.

2023-03-28 22:10 UTC, SnowMarble commented on files/ko/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +URL이 HTML 페이지와 같은 문서 내에서 사용되는 경우, 상황이 약간 다릅니다. 브라우저에는 이미 문서 고유의 URL이 있기 때문에 이 정보를 사용하여 해당 문서 내에서 사용할 수 있는 URL의 누락된 부분을 채울 수 있습니다. URL의 경로 부분만 보면 **절대 URL**과 **상대 URL**을 구별할 수 있습니다. URL의 **경로** 부분이 "`
이 부분을 잘 이해하지 못했는데, "*로 넣은 절대, 상대 URL"이 `**절대 URL**`, `**상대 URL**` 말씀하시는 건가요?

2023-03-29 05:02 UTC, cos18 commented
> 영어 문서 변경으로 이미지가 삭제되거나 이름이 변경되는 경우가 우려되어 추가했습니다. yari가 어떻게 사진을 찾는지 찾아보진 않았지만, 이런 경우엔 어떻게 되나요? 최신화가된 다른 지역은 사진 파일을 추가하진 않았던데, 사진에 대한 가이드가 있었으면 좋겠습니다.

@SnowMarble  yari에서는 translate 레포에 없는 문서에 경우에는 항상 content 쪽의 resource쪽으로 fallback합니다. 번역본이 없는 문서의 링크가 자동으로 en문서로 redirect 되는거와 같은 원리라고 생각하시면 됩니다.
일단 translate-content 레포의 1차적인 목표는 "content 레포의 최신버젼을 변역" 하는 것이기 때문에, content 레포에서 삭제된 내용이라면 이 레포에서는 구버젼을 유지하는 방향이 아니라 content 와의 동기화가 우선됩니다. 이에 대한 가이드에 대해 팀에 건의후 기여하겠습니다!

2023-03-29 05:04 UTC, cos18 commented on files/ko/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +URL이 HTML 페이지와 같은 문서 내에서 사용되는 경우, 상황이 약간 다릅니다. 브라우저에는 이미 문서 고유의 URL이 있기 때문에 이 정보를 사용하여 해당 문서 내에서 사용할 수 있는 URL의 누락된 부분을 채울 수 있습니다. URL의 경로 부분만 보면 **절대 URL**과 **상대 URL**을 구별할 수 있습니다. URL의 **경로** 부분이 "`
@SnowMarble 넵 제가 범위로 지정된 모든 `**볼드체**` 를 `_기울임체_` 로 바꿔주시면 될 것 같습니다.
깃헙 시스템이 deleted lines 를 포함한 범위에 대해 Suggestion을 넣지 못하도록 되어있어 간단하게 전달드렸는데 다음부터는 더욱 자세히 전달드리겠습니다!

2023-03-29 05:09 UTC, SnowMarble commented
그럼 사진은 일단 지워두겠습니다:)

2023-03-29 05:18 UTC, SnowMarble commented on files/ko/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +URL이 HTML 페이지와 같은 문서 내에서 사용되는 경우, 상황이 약간 다릅니다. 브라우저에는 이미 문서 고유의 URL이 있기 때문에 이 정보를 사용하여 해당 문서 내에서 사용할 수 있는 URL의 누락된 부분을 채울 수 있습니다. URL의 경로 부분만 보면 **절대 URL**과 **상대 URL**을 구별할 수 있습니다. URL의 **경로** 부분이 "`
엄.. 기울임꼴은 한글에서 적용하지 않는걸로 알고 있는데, 정말 바꾸나요? https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md#%EA%B8%B0%EC%9A%B8%EC%9E%84%EA%BC%B4

2023-03-29 05:28 UTC, cos18 commented on files/ko/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +URL이 HTML 페이지와 같은 문서 내에서 사용되는 경우, 상황이 약간 다릅니다. 브라우저에는 이미 문서 고유의 URL이 있기 때문에 이 정보를 사용하여 해당 문서 내에서 사용할 수 있는 URL의 누락된 부분을 채울 수 있습니다. URL의 경로 부분만 보면 **절대 URL**과 **상대 URL**을 구별할 수 있습니다. URL의 **경로** 부분이 "`
@SnowMarble 앗 제가 착각했군요 강조할 의도가 아니시라면 최대한 강조표시를 빼고 `'...'`로 묶어주시면 감사하겠습니다!

2023-03-29 05:49 UTC, cos18 approved these changes
LGTM! 수고하셨습니다 :)

2023-03-29 05:49 UTC, merged