zh-cn(update): encode.encodeInto()
mdn/translated-content pull request #12037
Opened 2023-03-06 10:03 UTC by fwqaaq

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-03-06 10:42 UTC, yin1999 requested changes

2023-03-06 10:42 UTC, yin1999 commented on files/zh-cn/web/api/textencoder/encodeinto/index.md
> +上述 `roundUpToBucketSize()` 函数，用于将空间向上舍入到分配器的桶大小。例如，如果你的 Wasm 分配器使用 2 的幂次方桶，则 `roundUpToBucketSize()` 应该返回该参数（如果它是 2 次幂的话，否则返回下一个 2 次幂）。如果 Wasm 分配器的行为未知，则 `roundUpToBucketSize()` 应为恒等函数。
2 次幂？

2023-03-06 10:42 UTC, yin1999 commented on files/zh-cn/web/api/textencoder/encodeinto/index.md
> +如果你的行为未知，你可能想要进行多达两次重新分配，并使得第一次重新分配的步骤将*剩余为转换*的长度乘以 2 而不是 3。然而，在这种情况下，未实现*已经写入*缓冲区的长度通常乘 2，因为在这种情况下，如果发生第二次重新分配，他将总是与原始长度乘 3 相比是过度分配的。上述建议假设你不需要为 0 终止符分配空间。也就是说，在 WASM 方面，你正在使用 Rust 字符串或者一个不以 0 终止的 C
你的行为未知？

2023-03-06 10:42 UTC, yin1999 commented on files/zh-cn/web/api/textencoder/encodeinto/index.md
> +{{EmbedLiveSample('Examples')}}
```suggestion
{{EmbedLiveSample('示例')}}
```

2023-03-06 11:33 UTC, fwqaaq commented on files/zh-cn/web/api/textencoder/encodeinto/index.md
> +上述 `roundUpToBucketSize()` 函数，用于将空间向上舍入到分配器的桶大小。例如，如果你的 Wasm 分配器使用 2 的幂次方桶，则 `roundUpToBucketSize()` 应该返回该参数（如果它是 2 次幂的话，否则返回下一个 2 次幂）。如果 Wasm 分配器的行为未知，则 `roundUpToBucketSize()` 应为恒等函数。
2 的幂，但是好像还是写全了好一点

2023-03-06 11:34 UTC, fwqaaq commented on files/zh-cn/web/api/textencoder/encodeinto/index.md
> +如果你的行为未知，你可能想要进行多达两次重新分配，并使得第一次重新分配的步骤将*剩余为转换*的长度乘以 2 而不是 3。然而，在这种情况下，未实现*已经写入*缓冲区的长度通常乘 2，因为在这种情况下，如果发生第二次重新分配，他将总是与原始长度乘 3 相比是过度分配的。上述建议假设你不需要为 0 终止符分配空间。也就是说，在 WASM 方面，你正在使用 Rust 字符串或者一个不以 0 终止的 C
分配器忘记了

2023-03-06 11:37 UTC, fwqaaq commented on files/zh-cn/web/api/textencoder/encodeinto/index.md
> +如果你的行为未知，你可能想要进行多达两次重新分配，并使得第一次重新分配的步骤将*剩余为转换*的长度乘以 2 而不是 3。然而，在这种情况下，未实现*已经写入*缓冲区的长度通常乘 2，因为在这种情况下，如果发生第二次重新分配，他将总是与原始长度乘 3 相比是过度分配的。上述建议假设你不需要为 0 终止符分配空间。也就是说，在 WASM 方面，你正在使用 Rust 字符串或者一个不以 0 终止的 C
```suggestion
如果你分配起的行为未知，但是你可能想要进行多达两次重新分配，并使得第一次重新分配的步骤将*剩余为转换*的长度乘以 2 而不是 3。然而，在这种情况下，未实现*已经写入*缓冲区的长度通常乘 2，因为在这种情况下，如果发生第二次重新分配，他将总是与原始长度乘 3 相比是过度分配的。上述建议假设你不需要为 0 终止符分配空间。也就是说，在 WASM 方面，你正在使用 Rust 字符串或者一个不以 0 终止的 C++ 类。如果你正在使用 C++ `std::string` 标准库，即使逻辑长度已经向你展示，当计算向上舍入到分配器的桶大小的时候，你还是需要去考虑额外的终止符字节。请参阅下一节有关 C 字符串的内容。
```

2023-03-06 11:37 UTC, fwqaaq commented on files/zh-cn/web/api/textencoder/encodeinto/index.md
> +上述 `roundUpToBucketSize()` 函数，用于将空间向上舍入到分配器的桶大小。例如，如果你的 Wasm 分配器使用 2 的幂次方桶，则 `roundUpToBucketSize()` 应该返回该参数（如果它是 2 次幂的话，否则返回下一个 2 次幂）。如果 Wasm 分配器的行为未知，则 `roundUpToBucketSize()` 应为恒等函数。
```suggestion
上述 `roundUpToBucketSize()` 函数，用于将空间向上舍入到分配器的桶大小。例如，如果你的 Wasm 分配器使用 2 的幂次方桶，则 `roundUpToBucketSize()` 应该返回该参数（如果它是 2 次幂的话，否则返回下一个 2 次幂）。如果 Wasm 分配器的行为未知，则 `roundUpToBucketSize()` 应为恒等函数。
```
```suggestion
上述 `roundUpToBucketSize()` 函数，用于将空间向上舍入到分配器的桶大小。例如，如果你的 Wasm 分配器使用 2 的幂次方桶，则 `roundUpToBucketSize()` 应该返回该参数（如果它是 2 的幂次方的话，否则返回下一个 2 的幂次方）。如果 Wasm 分配器的行为未知，则 `roundUpToBucketSize()` 应为恒等函数。
```

2023-03-06 14:36 UTC, yin1999 commented on files/zh-cn/web/api/textencoder/encodeinto/index.md
> +如果你的行为未知，你可能想要进行多达两次重新分配，并使得第一次重新分配的步骤将*剩余为转换*的长度乘以 2 而不是 3。然而，在这种情况下，未实现*已经写入*缓冲区的长度通常乘 2，因为在这种情况下，如果发生第二次重新分配，他将总是与原始长度乘 3 相比是过度分配的。上述建议假设你不需要为 0 终止符分配空间。也就是说，在 WASM 方面，你正在使用 Rust 字符串或者一个不以 0 终止的 C
第二句话再修改一下，我把错别字啥的给你改了，但还是不够好

2023-03-07 09:26 UTC, yin1999 approved these changes

2023-03-07 09:27 UTC, merged