sync with English version for `What we write` for zh-CN
mdn/translated-content pull request #12043
Opened 2023-03-07 00:42 UTC by awxiaoxian2020

2023-03-07 09:28 UTC, yin1999 commented on files/zh-cn/mdn/writing_guidelines/what_we_write/index.md
> +MDN Web Docs 的文档内容是通用的，并不偏向某一个浏览器。这使得 Web 开发人员可以编写与任何浏览器都兼容的代码。本文介绍了在 MDN Web Docs 上应该包含哪些主题或类型的内容的有关信息。
统一翻译为“MDN Web 文档”吧

2023-03-07 12:20 UTC, yin1999 requested changes

2023-03-07 12:20 UTC, yin1999 commented on files/zh-cn/mdn/writing_guidelines/what_we_write/index.md
> +- 在稳定的浏览器版本里发布。
```suggestion
- 至少有一个渲染引擎实现。
- 在稳定的浏览器版本里发布。
```

2023-03-07 12:20 UTC, yin1999 commented on files/zh-cn/mdn/writing_guidelines/what_we_write/index.md
> +MDN Web 文档上的所有内容都必须与其出现的技术部分相关。贡献者应遵循这些 MDN 的编写风格、代码示例以及一些其他主题的[撰写指南](/zh-CN/docs/MDN/Writing_guidelines)。
```suggestion
MDN Web 文档上的所有内容都必须与其出现的技术部分相关。贡献者应遵循这些 MDN 的编写风格、代码示例以及一些其它主题的[撰写指南](/zh-CN/docs/MDN/Writing_guidelines)。
```

2023-03-07 12:20 UTC, yin1999 commented on files/zh-cn/mdn/writing_guidelines/what_we_write/index.md
> +- 至少一个浏览器中已经始终如一地实现了该规范，并且其他浏览器开发者也表现出了兴趣（例如，已经存在一个有效的 ticket 或“意图实现”流程正在进行中）。
一般，我们翻译为“工单”：

```suggestion
- 至少一个浏览器中已经始终如一地实现了该规范，并且其他浏览器开发者也表现出了兴趣（例如，已经存在一个有效的工单或“意图实现”流程正在进行中）。
```

2023-03-07 12:20 UTC, yin1999 commented on files/zh-cn/mdn/writing_guidelines/what_we_write/index.md
> +- 目前仅有一个甚至没有浏览器已经实现该规范，且其他未支持该规范的浏览器没有表现出有意实现的迹象。你可以通过询问那些负责开发浏览器的工程师，并查看浏览器的错误跟踪器和邮件列表等方式来评估这一情况。
```suggestion
- 目前仅有一个甚至没有浏览器已经实现该规范，且其它未支持该规范的浏览器没有表现出有意实现的迹象。你可以通过询问那些负责开发浏览器的工程师，并查看浏览器的错误跟踪器和邮件列表等方式来评估这一情况。
```

2023-03-07 12:20 UTC, yin1999 commented on files/zh-cn/mdn/writing_guidelines/what_we_write/index.md
> +- 这项技术在 Web 上不是完全公开的
```suggestion
- 这项技术在 Web 上不是公开的，或是完全专有的。
- 已经显示出被弃用或被类似特性替代的迹象。
```

2023-03-07 12:20 UTC, yin1999 commented on files/zh-cn/mdn/writing_guidelines/what_we_write/index.md
> +## 哪些主题不属于 MDN Web Docs？
```suggestion
## 哪些主题不属于 MDN Web 文档
```

2023-03-07 12:20 UTC, yin1999 commented on files/zh-cn/mdn/writing_guidelines/what_we_write/index.md
> +### 当我们删除文档时
```suggestion
### 我们何时删除文档
```

2023-03-07 12:20 UTC, yin1999 commented on files/zh-cn/mdn/writing_guidelines/what_we_write/index.md
> +- 文章包含有关未在所有浏览器中实现且后来被撤回的功能的信息（通常是实验性功能，例如前置功能）。
这里好像还缺少两个段落

2023-03-07 12:20 UTC, yin1999 commented on files/zh-cn/mdn/writing_guidelines/what_we_write/index.md
>  ## 哪些类型在 MDN 的范畴内？
```suggestion
## 哪些类型在 MDN Web 文档的范畴内
```

2023-03-07 12:20 UTC, yin1999 commented on files/zh-cn/mdn/writing_guidelines/what_we_write/index.md
> +一般情况下，MDN 是*产品*文档，而不是*项目*或记录过程的文档。因此，如果文档是关于“如何使用一项技术”或“一项技术是如何工作的”（这项技术在上面提到的一个主题类别中）那么它可以被放在 MDN 上。
```suggestion
一般情况下，MDN Web 文档是*产品*文档，而不是*项目*或记录过程的文档。因此，如果文档是关于“如何使用一项技术”或“一项技术是如何工作的”（这项技术在上面提到的一个主题类别中）那么它可以被放在 MDN 上。
```

2023-03-07 12:20 UTC, yin1999 commented on files/zh-cn/mdn/writing_guidelines/what_we_write/index.md
>  ## 哪些话题在 MDN 的范畴内？
```suggestion
## 哪些话题在 MDN 的范畴内
```

2023-03-07 12:20 UTC, yin1999 commented on files/zh-cn/mdn/writing_guidelines/what_we_write/index.md
> +### 当我们记录一项新技术时
```suggestion
### 我们何时记录一项新技术
```

2023-03-07 12:23 UTC, awxiaoxian2020 commented on files/zh-cn/mdn/writing_guidelines/what_we_write/index.md
> +MDN Web 文档上的所有内容都必须与其出现的技术相关。网站绝不会接受垃圾信息（商业广告）和其他不相关的内容。继续尝试提交垃圾信息的贡献者可能会被 Mozilla MDN 工作人员酌情禁止访问 MDN。
“他们”为常见用法。

2023-03-07 12:25 UTC, awxiaoxian2020 commented on files/zh-cn/mdn/writing_guidelines/what_we_write/index.md
> +- 至少一个浏览器中已经始终如一地实现了该规范，并且其他浏览器开发者也表现出了兴趣（例如，已经存在一个有效的 ticket 或“意图实现”流程正在进行中）。
其实我不太明白这里的 ticket 会在什么情况下使用。

2023-03-07 12:32 UTC, yin1999 commented on files/zh-cn/mdn/writing_guidelines/what_we_write/index.md
> +MDN Web 文档上的所有内容都必须与其出现的技术相关。网站绝不会接受垃圾信息（商业广告）和其他不相关的内容。继续尝试提交垃圾信息的贡献者可能会被 Mozilla MDN 工作人员酌情禁止访问 MDN。
的确，这个没有统一的定论，其实两者均可。但我更希望，所有文档能够保持统一，目前而言，使用“它”来特指“物”是没有问题的。

2023-03-07 12:43 UTC, awxiaoxian2020 commented on files/zh-cn/mdn/writing_guidelines/what_we_write/index.md
> +MDN Web 文档上的所有内容都必须与其出现的技术相关。网站绝不会接受垃圾信息（商业广告）和其他不相关的内容。继续尝试提交垃圾信息的贡献者可能会被 Mozilla MDN 工作人员酌情禁止访问 MDN。
>《现代汉语异形词规范词典》明确指出，“其他”与“其它”是一组异形词，但“其他”能够包孕“其它”。至此，“其他”和“其它”的使用方式已经非常明显，“其他”可以代替“其它”行使语言表达作用，表达指代事物过程中仍然可以使用“其它”，表达指代人时必须使 用“其他”，由于“其他”能够包孕“其它”，为了语言规范，避免出现差错，在科技期刊编辑审校过程中使用“其他”为宜。
> 
> [1]王海波.科技期刊审校过程中异形词的使用辨析[J].通化师范学院学报,2021,42(12):124-128.DOI:10.13877/j.cnki.cn22-1284.2021.12.021.

![others](https://user-images.githubusercontent.com/69554233/219677644-abc37e29-d9da-4ecb-9f22-9e81e95548d2.png)

我似乎没有找到支持"它们"的说法。Vue 官方文档亦统一到“其他”。要不我们也统一到“其他”吧。

2023-03-08 05:55 UTC, yin1999 commented on files/zh-cn/mdn/writing_guidelines/what_we_write/index.md
> +- 至少一个浏览器中已经始终如一地实现了该规范，并且其他浏览器开发者也表现出了兴趣（例如，已经存在一个有效的 ticket 或“意图实现”流程正在进行中）。
https://wiki.mbalib.com/wiki/%E5%B7%A5%E5%8D%95

2023-03-08 06:48 UTC, yin1999 approved these changes

2023-03-08 06:51 UTC, merged