Explicitation de la valeur de retour de .then()
mdn/translated-content pull request #12072
Opened 2023-03-08 21:33 UTC by peacefulNPC

Je propose d'expliciter le fait que .then() retourne une nouvelle promesse immédiatement, qu'importe l'état de la promesse sur laquelle then() a été appelée (c'est d'ailleurs ce qu'indique clairement la version US de la page : "Returns a new Promise immediately. This new promise is always pending when returned, regardless of the current promise's status." -- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then

Cela peut aider à comprendre pourquoi dans le cas exemple que j'ai ajouté, on a bien 42 qui s'affiche, mais myThenPromise est indiquée en attente : c'est parce que then() renvoie immédiatement la nouvelle promesse sans se soucier de l'état de la promesse d'origine.

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-04-05 22:05 UTC, cw118 requested changes
Bonjour, désolé pour le délai ici et merci déjà pour cette *pull request* !

Les pages françaises font référence à leurs homologues anglaises, alors il faudra d'abord ajouter le premier exemple (Valeur de retour de la méthode `then()`) à [la page anglaise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then#examples). Vous pouvez proposer cette modification sur le contenu anglais en ouvrant une PR sur [le dépôt mdn/content](https://github.com/mdn/content).

N'hésitez pas si besoin d'aide.

2023-04-17 21:00 UTC, cw118 commented
@peacefulNPC Avez-vous besoin d'un coup de main sur cette PR ?

2023-05-06 15:41 UTC, SphinxKnight commented
Je vais fusionner en l'état vu la date d'ouverture de la PR. J'ai retiré l'exemple suite au commentaire de @cw118 mais le remet ici (avec des espaces plutôt que des tabulations) au cas où il puisse resservir sur une autre PR : 

````
### Valeur de retour de la méthode `then()`

L'appel à `then()` sur une promesse retourne toujours une nouvelle promesse en attente de résolution.

```js
const myOriginalPromise = new Promise(function(resolve, reject){
	resolve(42); // la promesse est résolue avec la valeur 42 dès sa création
});
console.log(myOriginalPromise); // Promise { <state>: "fulfilled", <value>: 42 }

const myThenPromise = myOriginalPromise.then(
	function(result){ // fonction anonyme qui est toujours appelée car myOriginalPromise est toujours résolue
		console.log(result); // affiche 42 immédiatement (dès l'appel à then())
	}
);
console.log(myThenPromise); // Promise { <state>: "pending" }
// Elle est en réalité déjà résolue : on peut voir son état actuel en déroulant les détails avec la petite flèche dans la console
```
````

2023-05-06 15:41 UTC, SphinxKnight approved these changes

2023-05-06 15:44 UTC, SphinxKnight commented
arf @cw118 je suis bloqué pour la fusion :) preneur d'une revue ou d'un déblocage de ton côté :) désolé :x

2023-05-08 18:17 UTC, cw118 approved these changes
Merci beaucoup pour tout ce travail 🚀

2023-05-08 18:18 UTC, merged