[ko] Update javascript/internalerror
mdn/translated-content pull request #1210
Opened 2021-06-16 09:49 UTC by wisedog

/web/javascript/reference/global_objects/internalerror 문서를 en-US와 동기화

2021-06-22 16:27 UTC, hochan222 requested changes
안녕하세요 @wisedog 님 리뷰드립니다.

문서에 대해 몇가지 suggestion을 남겼습니다. 확인해주시고 반영해주세요.

기여해주셔서 감사합니다. 좋은 하루 보내세요 :)

2021-06-22 16:27 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/internalerror/index.html
> + <dd>새로운 <code>InternalError</code> 객체를 만듭니다.</dd>
<img src="https://user-images.githubusercontent.com/22424891/122961416-58fb2380-d3bf-11eb-9408-19969a900274.png" height="100px" />

이 부분은 https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/internalerror/index.html#L26 와 코드가 같은데도 링크가 깨지네요.. 아직은 원인을 못찾았지만 나중에 찾아보겠습니다..!

2021-06-22 16:27 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/internalerror/index.html
> +  <dd>오류 메시지.{{jsxref("Error")}}로부터 상속되었습니다.</dd>
```suggestion
  <dd>오류 메시지. {{jsxref("Error")}}로부터 상속되었습니다.</dd>
```
공백이 생략돼서 추가했습니다 :)

2021-06-22 16:27 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/internalerror/index.html
> +  <dd>오류가 발생한 곳의 줄 위치. {{jsxref("Error")}}로부터 상속되었습니다.</dd>
```suggestion
  <dd>오류가 발생한 곳의 줄 번호. {{jsxref("Error")}}로부터 상속되었습니다.</dd>
```
> Line number in file that raised this error. Inherited from Error.

`InternalError.prototype.lineNumber`, lineNumber인 만큼 줄 위치보다는 줄 번호가 더 자연스러운 번역으로 느껴져서 리뷰했습니다.

2021-06-22 16:27 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/internalerror/index.html
> +  <dd>오류가 발생한 곳의 열 위치. {{jsxref("Error")}}로부터 상속되었습니다.</dd>
```suggestion
  <dd>오류가 발생한 행의 열 번호. {{jsxref("Error")}}로부터 상속되었습니다.</dd>
```
> Column number in line that raised this error. Inherited from Error.

`in line`의 의미가 누락돼서 리뷰했습니다.

2021-06-22 16:27 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/internalerror/index.html
> +<p>어떤 표준에도 속하지 않았습니다.</p>
```suggestion
<p>어떤 표준에도 속하지 않습니다.</p>
```

과거형 표현은 현재 상태의 불확실성을 줄 수 있으므로 없애고 추후에 표준에 등록되면 그 때 반영하는게 좋다고 생각합니다.

아래 표현도 좋은 것 같아요 :)

> 표준의 일부가 아닙니다.

2021-06-22 16:27 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/internalerror/index.html
> + </ul>
```suggestion
 </ul>
 
```

EOL

2021-06-22 23:21 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/internalerror/index.html
> +<p>어떤 표준에도 속하지 않았습니다.</p>
저도 직역하면 표준의 일부가 아니라는 말이 되는데 저는 그게 더 이상하더라구요. 말씀하신대로 과거형보다는 현재형이 좋겠습니다.

2021-06-22 23:24 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/internalerror/index.html
> + <dd>새로운 <code>InternalError</code> 객체를 만듭니다.</dd>
`InternalError()`외의 모든 Error 객체 페이지(`RangeError` 등)에서 동일하게 발생하는 문제입니다. `Error`는 별도의 생성자 페이지가 따로 있더라구요. 번역을 추가하면 해결될 문제로 보입니다.

2021-06-23 01:12 UTC, hochan222 approved these changes
LGTM, 좋은 하루 보내세요 :)

2021-06-23 01:12 UTC, merged