Translated the 'Package management' section of 'Understanding client-side tools'.
mdn/translated-content pull request #12196
Opened 2023-03-14 17:40 UTC by JasonLamv-t

### Description

- 修补之前的翻译缺陷——没有翻译元数据中的标题，位于`/zh-cn/learn/tools_and_testing/understanding_client-side_tools/overview/index.md`；
- 并添加了全新的翻译内容，位于`/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md`

- Fixed the translation issue that the title in the metadata was not translated, located at `/zh-cn/learn/tools_and_testing/understanding_client-side_tools/overview/index.md`;
- Added new translation content, located at `/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md`.

2023-03-15 00:48 UTC, yin1999 requested changes

2023-03-15 00:48 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +> **备注：**：npm 不是唯一可用的软件包管理器。有一种成功和流行的替代软件包管理器是 [Yarn](https://yarnpkg.com/) Yarn 使用不同的算法解决依赖项，这可能意味着更快的用户体验。还有一些其他新兴的客户端，例如 [pnpm](https://pnpm.js.org/)。
```suggestion
> **备注：** npm 不是唯一可用的软件包管理器。有一种成功和流行的替代软件包管理器是 [Yarn](https://yarnpkg.com/) Yarn 使用不同的算法解决依赖项，这可能意味着更快的用户体验。还有一些其他新兴的客户端，例如 [pnpm](https://pnpm.js.org/)。
```

2023-03-15 00:48 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +      <th scope="row">先决条件：</th>
统一翻译：

```suggestion
      <th scope="row">预备条件：</th>
```

2023-03-15 00:48 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +## 什么是软件包管理器？
重了，麻烦删除英文，下文中也有出现的，请教对一下

```suggestion
## 什么是软件包管理器？
```

2023-03-15 00:48 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +这是定义你的软件包的配置文件。目前为止都很好，所以我们继续。
idto

2023-03-15 00:48 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +现在使用 <kbd>Ctrl</kbd> + <kbd>C</kbd> 停止之前的Parcel命令。
中英文间的空格，全文检查一下

```suggestion
现在使用 <kbd>Ctrl</kbd> + <kbd>C</kbd> 停止之前的 Parcel 命令。
```

2023-03-15 00:48 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +- 在 Parcel（Parcel 2之前）的情况下，需要一个特殊的标志——`--experimental-scope-hoisting`——来进行 Tree Shaking 构建。
```suggestion
- 在 Parcel（Parcel 2 之前）的情况下，需要一个特殊的标志——`--experimental-scope-hoisting`——来进行 Tree Shaking 构建。
```

2023-03-15 00:48 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +
idto

2023-03-15 00:48 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +
idto

2023-03-15 00:48 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +这个命令将检查您项目的所有依赖树，并使用漏洞数据库检查您正在使用的特定版本，如果您的项目中存在潜在的漏洞包，则会通知您。
请使用“你”

```suggestion
这个命令将检查你项目的所有依赖树，并使用漏洞数据库检查你正在使用的特定版本，如果你的项目中存在潜在的漏洞包，则会通知你。
```

2023-03-15 11:22 UTC, JasonLamv-t commented
@yin1999 ，已经进行了修改和检查，麻烦请重新 review

2023-03-15 12:55 UTC, fwqaaq requested changes

2023-03-15 12:55 UTC, fwqaaq commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +想要了解有关漏洞的更多信息，可以参考 [Snyk项目](https://snyk.io/)，该项目涵盖了 JavaScript 软件包和其他编程语言。
```suggestion
想要了解有关漏洞的更多信息，可以参考 [Snyk 项目](https://snyk.io/)，该项目涵盖了 JavaScript 软件包和其他编程语言。
```

2023-03-15 12:55 UTC, fwqaaq commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +此外，npm（和 yarn）命令非常智能，它们会在尝试通过传统方法查找命令行工具之前，先搜索项目中本地安装的工具（计算机通常会存储和允许查找软件）。你可以 [了解有关 `run` 命令的技术细节](https://docs.npmjs.com/cli/run-script/)，尽管在大多数情况下，你自己的脚本都可以正常运行。
```suggestion
此外，npm（和 yarn）命令非常智能，它们会在尝试通过传统方法查找命令行工具之前，先搜索项目中本地安装的工具（计算机通常会存储和允许查找软件）。你可以[了解有关 `run` 命令的技术细节](https://docs.npmjs.com/cli/run-script/)，尽管在大多数情况下，你自己的脚本都可以正常运行。
```

2023-03-15 12:55 UTC, fwqaaq commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +版本号的确定是通过名为 [semver](https://semver.org/) 的系统实现的。从文档中看起来可能有些复杂，但是只考虑摘要信息并将版本表示为 `MAJOR.MINOR.PATCH`，例如 2.0.1 表示主版本 2 和补丁版本 1，可以简化这个系统。一个测试 semver 值的绝佳方法是使用 [semver计算器](https://semver.npmjs.com/)。
```suggestion
版本号的确定是通过名为 [semver](https://semver.org/) 的系统实现的。从文档中看起来可能有些复杂，但是只考虑摘要信息并将版本表示为 `MAJOR.MINOR.PATCH`，例如 2.0.1 表示主版本 2 和补丁版本 1，可以简化这个系统。一个测试 semver 值的绝佳方法是使用 [semver 计算器](https://semver.npmjs.com/)。
```

2023-03-16 03:01 UTC, fwqaaq requested changes

2023-03-16 03:01 UTC, fwqaaq commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +- `license`：要发布软件包的许可证。按下<kbd>Return</kbd>来接受默认值。
```suggestion
- `license`：要发布软件包的许可证。按下 <kbd>Return</kbd> 来接受默认值。
```

2023-03-16 03:01 UTC, fwqaaq commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +现在，我们将运行我们新安装的Parcel工具。在终端中运行以下命令：
```suggestion
现在，我们将运行我们新安装的 Parcel 工具。在终端中运行以下命令：
```

2023-03-16 03:04 UTC, JasonLamv-t commented
感谢的你 review ，我会尽快检查并更正

2023-03-17 02:09 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +然而，这就是开发工具大放异彩的地方。当它在我们的计算机上运行时，我们可以要求软件检查我们对代码的使用，并在构建中仅包含我们实际使用的函数——这个过程称为“Tree Shaking”。
```suggestion
然而，这就是开发工具大放异彩的地方。当它在我们的计算机上运行时，我们可以要求软件检查我们对代码的使用，并在构建中仅包含我们实际使用的函数——这个过程称为“摇树优化（Tree Shaking）”。
```

2023-03-17 02:09 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +这非常有意义，因为我们希望减小文件大小，从而使我们的应用程序尽可能快地加载。不同的工具将以不同的方式让你进行 Tree Shaking。
```suggestion
这非常有意义，因为我们希望减小文件大小，从而使我们的应用程序尽可能快地加载。不同的工具将以不同的方式让你进行摇树优化。
```

2023-03-17 02:09 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +- RollUp 工具提供 Tree Shaking 和代码拆分作为其核心特性。
```suggestion
- RollUp 工具提供摇树优化和代码拆分作为其核心特性。
```

2023-03-17 02:09 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +- 在 Parcel（Parcel 2 之前）的情况下，需要一个特殊的标志——`--experimental-scope-hoisting`——来进行 Tree Shaking 构建。
idto

2023-03-17 02:09 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +让我们暂时继续使用Parcel，因为我们已经安装了它。尝试运行以下命令：
```suggestion
让我们暂时继续使用 Parcel，因为我们已经安装了它。尝试运行以下命令：
```

2023-03-17 05:44 UTC, JasonLamv-t commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +一旦完成了 _所有准备工作_，我们现在准备进行一些“现代客户端开发”（这实际上意味着使用构建工具使开发人员的体验更加轻松）。但是首先，请再次查看你的 package.json 文件。你将看到 npm 添加了一个新字段——dependencies：
原文使用的是斜体而非加粗，是否需要对原文也提PR进行修改呢？

2023-03-17 05:55 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +一旦完成了 _所有准备工作_，我们现在准备进行一些“现代客户端开发”（这实际上意味着使用构建工具使开发人员的体验更加轻松）。但是首先，请再次查看你的 package.json 文件。你将看到 npm 添加了一个新字段——dependencies：
一个星号是不间断的斜体（下划线则必须使用空格或其他的标点隔开，星号不用）

2023-03-17 05:59 UTC, JasonLamv-t commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +一旦完成了 _所有准备工作_，我们现在准备进行一些“现代客户端开发”（这实际上意味着使用构建工具使开发人员的体验更加轻松）。但是首先，请再次查看你的 package.json 文件。你将看到 npm 添加了一个新字段——dependencies：
👌

2023-03-17 07:46 UTC, yin1999 approved these changes
Thanks. Welcome aboard :tada:

2023-03-17 07:46 UTC, merged