Update the documentation of message and name of DOMException
mdn/translated-content pull request #12210
Opened 2023-03-15 12:15 UTC by senmu-a

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-03-15 12:47 UTC, fwqaaq commented on files/zh-cn/web/api/domexception/name/index.md
> +
```suggestion
```

2023-03-15 13:38 UTC, senmu-a commented on files/zh-cn/web/api/domexception/name/index.md
> +
感谢🥰

2023-03-15 14:41 UTC, yin1999 requested changes

2023-03-15 14:41 UTC, yin1999 commented on files/zh-cn/web/api/domexception/message/index.md
> +{{domxref("DOMException")}} 接口中的 **`message`** 是一个只读属性，它返回一个字符串来表示与给定[错误名称](/zh-CN/docs/Web/API/DOMException#%E9%94%99%E8%AF%AF%E5%90%8D%E7%A7%B0)关联的消息或描述。
```suggestion
{{domxref("DOMException")}} 接口的 **`message`** 只读属性返回一个字符串来表示与给定[错误名称](/zh-CN/docs/Web/API/DOMException#错误名称)关联的消息或描述。
```

2023-03-15 14:41 UTC, yin1999 commented on files/zh-cn/web/api/domexception/name/index.md
> +{{domxref("DOMException")}} 接口中的 **`name`** 是一个只读属性，它返回了与[错误名称](/zh-CN/docs/Web/API/DOMException#%E9%94%99%E8%AF%AF%E5%90%8D%E7%A7%B0)关联的字符串。
这句话请再修改一下，与英文的有出入

2023-03-16 08:51 UTC, yin1999 approved these changes
Thanks

2023-03-16 08:51 UTC, merged