feat(translate): Package management basicsの翻訳
mdn/translated-content pull request #12248
Opened 2023-03-18 09:15 UTC by gurezo

@hmatrjp @potappo 

### issue
- [  Package management basics の翻訳 #689  ](https://github.com/mozilla-japan/translation/issues/689)  のPRです。

### translated-content
#### 以下のセクション毎にコミットしてあります。

2023-03-22 15:42 UTC, mfuji09 requested changes
以下の2つのスタイルガイドに合う表記に修正をお願いします。
https://mozilla-l10n.github.io/styleguides/ja/l10nguideline.html
https://mozilla-l10n.github.io/styleguides/ja/editorialguideline.html

同じ指摘事項は繰り返していませんので、指摘箇所だけでなく、同様の他の箇所も修正してください。

2023-03-22 15:42 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +        パッケージマネージャーとパッケージリポジトリとは何か、必要な理由や使用方法の基本を理解する。
「リポジトリ」→「リポジトリー」と表記してください。

2023-03-22 15:42 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +**依存関係**とは、サードパーティ製のソフトウェアであり、おそらく他の誰かによって作成されたものであり、理想的には 1 つの問題を解決してくれます。 Web プロジェクトには、0 から多数の範囲で任意の数の依存関係を含めることができます。また依存関係には、明示的にインストールしていないサブ依存関係が含まれる場合があります。依存関係には、独自の依存関係がある場合があります。
「Web」→「ウェブ」と表記してください。

2023-03-22 15:42 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +プロジェクトの依存関係は、React や Vue などの JavaScript ライブラリまたはフレームワーク全体、または人間が読める日付ライブラリのような非常に小さなユーティリティ、または以前の記事で説明した Prettier や ESLint などのコマンドラインツールである可能性があります。
「ライブラリ」→「ライブラリー」と表記してください。

2023-03-22 15:42 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +最新のビルド ツールがなければ、単純な [`<script>`](/en-US/docs/Web/HTML/Element/script) 要素を使用して、このような依存関係をプロジェクトに含めることができますが、これはすぐには機能しない可能性があります。 また、コードと依存関係が Web 上にリリースされるときに、コードと依存関係を一緒にバンドルするための最新のツールが必要になる可能性がありま
「ビルド ツール」の間のように、カタカナ語の間の半角空白は削除してください。

2023-03-22 15:42 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +## パッケージレジストリ
「レジストリ」→「レジストリー」と表記してください。

2023-03-22 15:42 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +まず、実験的なアプリを保存するための新しいディレクトリを作成します。 これを parcel-experiment と呼びますが、好きなように呼ぶことができます。
「ディレクトリ」→「ディレクトリー」と表記してください。

2023-03-22 15:42 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +  <kbd>Return</kbd> を入力します。
原文を見ると、この文と次の文が一続きの文になっていますので、ここでは「Return を押すと、デフォルトの `parcel-experiment` が使用されます」などのように、一続きの文として翻訳したほうが良いと思います。次の文以降も同様です。

2023-03-22 15:42 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +> **メモ:** 「command not found」エラーをターミナルに返す場合は、上記のコマンドを `npx` ユーティリティ、つまり `npx parcel index.html`で実行してみてください。
「command not found」エラーをターミナルに返す、のではなく、
「command not found」エラーをターミナルが返す、だと思います。

2023-03-22 15:42 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +ただし、このコードは本番用の準備ができていません。 ほとんどのビルド ツール システムには、「開発モード」と「プロダクションモード」があります。 重要な違いは、開発で使用する便利な機能の多くが最終サイトでは必要ないため、本番環境では取り除かれることです。 「hot module replacement」、「live reloading」、および「uncompressed and commente
この部分が日本語として自然ではないので、例えば以下のような形で日本語として自然な表現を使用してください。

重要な違いは、開発で使用する便利な機能の多く、たとえば「hot module replacement」、「live reloading」、「uncompressed and commented source code」が最終サイトでは必要ないため、本番環境では取り除かれることです。

2023-03-22 15:42 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +ただし、開発者を「助ける」すべてのツールと同様に多くの場合、トレードオフがあります。 この特定のケースでは、それはファイルサイズです。 JavaScript バンドル my-project.fb76efcf.js はなんと 195K にもなり、1 行のテキストを出力するだけなので非常に大きいです。 確かに計算はありますが、これを行うために 195K 相当の JavaScript は絶対に必要あり
「確かに計算はありますが、」の部分の意味が分かりにくいと思います。
「確かに多少の計算は行いますが、」のように、少し言葉を補って分かりやすくしてください。

2023-03-22 15:42 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
> +開発ツールを一切使用せず、 `<script src="">` 要素を `date-fns` のホストされたバージョンに向けていた場合、ほぼ同じことが起こっていたでしょう — サンプルページのときにすべてのライブラリがダウンロードされます。ブラウザに読み込まれます。
「ブラウザ」→「ブラウザー」と表記してください。

2023-04-02 07:46 UTC, gurezo commented
@mfuji09 
以下修正しました。

- リポジトリ => リポジトリー 1809acf
- Web => ウェブ b4d361b
- ライブラリ => ライブラリー 17b12e7
- ビルド ツール => ビルドツール 2b9569d
- translate remove space 50d3ecc
- レジストリ => レジストリー 480d2f5
- 「command not found」エラーをターミナルが返す 47ddeff
- ブラウザ => ブラウザー a453fd7
- 確かに多少の計算は行いますが、 fb073b8
- 重要な違いは〜 bb10992
- ディレクトリ => ディレクトリー a5c775f
- <kbd>Return</kbd> d289512

2023-04-03 13:59 UTC, mfuji09 approved these changes
OKです。

2023-04-03 14:00 UTC, merged