[zh-cn]: Update every methods of the Array.
mdn/translated-content pull request #12243
Opened 2023-03-17 16:59 UTC by JasonLamv-t

### Description

更新 Array.every() 方法文档，当前版本与英文不一致

### Motivation

同上

### Additional details

页面中引用的 [稀疏数组](/en-US/docs/Web/JavaScript/Guide/Indexed_collections#sparse_arrays) 中文与英文不一致，需要进行更新

2023-03-17 17:33 UTC, fwqaaq requested changes
Some suggestions

2023-03-17 17:33 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/array/every/index.md
>  ---
```suggestion
---
title: Array.prototype.every()
slug: Web/JavaScript/Reference/Global_Objects/Array/every
---
```

2023-03-17 17:33 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/array/every/index.md
> +`every` 和数学中的"所有"量词类似。特别的，对于空数组，它只返回 `true`。（这种情况属于[无条件正确](http://en.wikipedia.org/wiki/Vacuous_truth)因为[空集](https://zh.wikipedia.org/wiki/%E7%A9%BA%E9%9B%86)的所有元素都符合给定的条件。）
```suggestion
`every` 和数学中的“所有”量词类似。特别的，对于空数组，它只返回 `true`。（这种情况属于[无条件正确](http://en.wikipedia.org/wiki/Vacuous_truth)因为[空集](https://zh.wikipedia.org/wiki/空集)的所有元素都符合给定的条件。）
```

这里的 for all 应该是全称量词，**对于所有**或者**任意**的意思

2023-03-17 17:33 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/array/every/index.md
> +`callbackFn` 仅针对已分配值的数组索引调用。它不会为[稀疏数组](/en-US/docs/Web/JavaScript/Guide/Indexed_collections#sparse_arrays)中的空槽调用。
这里改成 zh-CN，yari 会自动替换

2023-03-17 17:33 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/array/every/index.md
> +- 如果数组中一个现有的、尚未访问的元素被 `callbackFn` 更改，则它传递给 `callbackFn` 的值将是该元素被访问时的值。 [删除的](/zh-CN/docs/Web/JavaScript/Reference/Operators/delete)元素不会被访问。
```suggestion
- 如果数组中一个现有的、尚未访问的元素被 `callbackFn` 更改，则它传递给 `callbackFn` 的值将是该元素被访问时的值。[删除的](/zh-CN/docs/Web/JavaScript/Reference/Operators/delete)元素不会被访问。
```

2023-03-17 17:35 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/every/index.md
>  ---
这里我是看原文添加的，原来是不需要的吗？

2023-03-17 17:35 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/every/index.md
> +`every` 和数学中的"所有"量词类似。特别的，对于空数组，它只返回 `true`。（这种情况属于[无条件正确](http://en.wikipedia.org/wiki/Vacuous_truth)因为[空集](https://zh.wikipedia.org/wiki/%E7%A9%BA%E9%9B%86)的所有元素都符合给定的条件。）
xs，想不起来叫全称量词了，之后改一下

2023-03-18 10:37 UTC, fwqaaq requested changes

2023-03-18 10:37 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/array/every/index.md
> +`every` 和数学中的"全称量词（∀）"类似。特别的，对于空数组，它只返回 `true`。（这种情况属于[无条件正确](http://en.wikipedia.org/wiki/Vacuous_truth)因为[空集](https://zh.wikipedia.org/wiki/空集)的所有元素都符合给定的条件。）
```suggestion
`every` 和数学中的全称量词“任意”（∀）类似。特别的，对于空数组，它只返回 `true`。（这种情况属于[无条件正确](http://en.wikipedia.org/wiki/Vacuous_truth)因为[空集](https://zh.wikipedia.org/wiki/空集)的所有元素都符合给定的条件。）
```

2023-03-18 10:37 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/array/every/index.md
> +- 当开始调用 `every()` 时，`callbackFn` 将不会访问超出数组初始长度的任何元素。
```suggestion
- 当开始调用 `every()` 时，`callbackFn` 将不会访问超出数组初始长度之外的任何新增元素。
```

2023-03-18 10:37 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/array/every/index.md
> +- 如果数组中一个现有的、尚未访问的元素被 `callbackFn` 更改，则它传递给 `callbackFn` 的值将是该元素被访问时的值。[删除的](/zh-CN/docs/Web/JavaScript/Reference/Operators/delete)元素不会被访问。
```suggestion
- 如果 callbackFn 更改了数组中一个现有的、尚未访问的元素，则它传递给 `callbackFn` 的值将是该元素被访问后的值。[删除的](/zh-CN/docs/Web/JavaScript/Reference/Operators/delete)元素不会被访问。
```

**访问后**应该更符合上下文（建议）

2023-03-19 02:54 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/every/index.md
> +- 当开始调用 `every()` 时，`callbackFn` 将不会访问超出数组初始长度的任何元素。
这里，超出数组长度外的元素不一定是新增的，callbackFn 对于数组的操作可以是在数组的头部进行的，考虑以下代码：
```js
let a = [0, 1, 2, 3, 4]
a.every((cur, index, array) => {
  if (cur === 0) {
    array.unshift(-3, -2, -1);
  }
  console.log(cur);  // [0, -2, -1, 0, -2]
  return true;
});
```

2023-03-19 03:02 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/every/index.md
> +- 如果数组中一个现有的、尚未访问的元素被 `callbackFn` 更改，则它传递给 `callbackFn` 的值将是该元素被访问时的值。[删除的](/zh-CN/docs/Web/JavaScript/Reference/Operators/delete)元素不会被访问。
这里如果要修改被动语态的话，后半句的 它 可能也需要进行修改以使含义显然。访问时 -> 访问后 -> 修改后 会不会更好一点？这个感觉应该是强调被修改后的值

2023-03-19 04:21 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/array/every/index.md
> +- 当开始调用 `every()` 时，`callbackFn` 将不会访问超出数组初始长度的任何元素。
对，应该是添加之后

2023-03-19 04:24 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/array/every/index.md
> +- 如果数组中一个现有的、尚未访问的元素被 `callbackFn` 更改，则它传递给 `callbackFn` 的值将是该元素被访问时的值。[删除的](/zh-CN/docs/Web/JavaScript/Reference/Operators/delete)元素不会被访问。
可以

2023-03-19 11:30 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/every/index.md
> +`every` 和数学中的全称量词"任意（∀）"类似。特别的，对于空数组，它只返回 `true`。（这种情况属于[无条件正确](http://en.wikipedia.org/wiki/Vacuous_truth)，因为[空集](https://zh.wikipedia.org/wiki/空集)的所有元素都符合给定的条件。）
```suggestion
`every` 和数学中的全称量词"任意（∀）"类似。特别的，对于空数组，它只返回 `true`。（这种情况属于[无条件正确](https://en.wikipedia.org/wiki/Vacuous_truth)，因为[空集](https://zh.wikipedia.org/wiki/空集)的所有元素都符合给定的条件。）
```

2023-03-19 11:30 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/every/index.md
> +- 对已访问索引的更改不会导致再次调用它们的 `callbackFn`。
```suggestion
- 对已访问索引的更改不会导致再次在这些元素上调用 `callbackFn`。
```

2023-03-19 11:30 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/every/index.md
> +`every()` 不会在空槽上运行它的谓词函数（译注：即 `callbackFn`）。
翻译为“断言”应该更合适一些（true or false）

```suggestion
`every()` 不会在空槽上运行它的断言函数。
```

2023-03-19 11:33 UTC, yin1999 approved these changes
Thanks

2023-03-19 11:35 UTC, merged