zh-CN: Translate `inset-block-*`
mdn/translated-content pull request #12245
Opened 2023-03-18 03:32 UTC by yarusome

### Description

### Motivation

### Additional details

### Related issues and pull requests

Depends on #12237 and https://github.com/mdn/content/pull/25437.

2023-03-18 03:36 UTC, yarusome commented on files/zh-cn/web/css/inset-block-end/index.md
> +- 定义其他偏移的属性：{{CSSXref("inset-block-start")}}、{{CSSXref("inset-inline-start")}} 和 {{CSSXref("inset-inline-end")}}
此处将 inset 按实际含义译为了“偏移”（offset）。

2023-03-18 03:36 UTC, yarusome commented on files/zh-cn/web/css/inset-block-start/index.md
> +- 定义其他偏移的属性：{{CSSXref("inset-block-end")}}、{{CSSXref("inset-inline-start")}} 和 {{CSSXref("inset-inline-end")}}
同上。

2023-03-18 10:54 UTC, fwqaaq requested changes

2023-03-18 10:54 UTC, fwqaaq commented on files/zh-cn/web/css/inset-block-start/index.md
> +- {{CSSXref("writing-mode")}}, {{CSSXref("direction")}}, {{CSSXref("text-orientation")}}
```suggestion
- {{CSSXref("writing-mode")}}、{{CSSXref("direction")}}、{{CSSXref("text-orientation")}}
```

2023-03-19 05:11 UTC, yin1999 approved these changes

2023-03-19 05:17 UTC, merged