zh-cn: update translation content for element.scrollTo
mdn/translated-content pull request #12250
Opened 2023-03-18 10:37 UTC by daiwanxing

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-03-18 10:51 UTC, fwqaaq requested changes
Some suggestions

2023-03-18 10:51 UTC, fwqaaq commented on files/zh-cn/web/api/element/scrollto/index.md
> +  - : 包含以下参数的字典：
```suggestion
  - : 包含以下参数的对象：
```

这个意译吧。

2023-03-18 10:51 UTC, fwqaaq commented on files/zh-cn/web/api/element/scrollto/index.md
> +      - : 指定沿X轴滚动窗口或元素的像素数。
```suggestion
      - : 指定沿 Y 轴滚动窗口或元素的像素数。
    - `left`
      - : 指定沿 X 轴滚动窗口或元素的像素数。
```

2023-03-18 14:45 UTC, yin1999 commented on files/zh-cn/web/api/element/scrollto/index.md
> +      - : 指定滚动是否应平稳地动画显示（`smooth`）、在单个跳跃中瞬间完成（`instant`），或由浏览器自行决定（`auto`，默认）。
平稳地动画显示 这个词总觉得怪怪的，可否改进一下翻译

2023-03-18 14:45 UTC, yin1999 commented on files/zh-cn/web/api/element/scrollto/index.md
>  ## 例子
```suggestion
## 示例
```

2023-03-18 15:15 UTC, daiwanxing commented on files/zh-cn/web/api/element/scrollto/index.md
> +      - : 指定滚动是否应平稳地动画显示（`smooth`）、在单个跳跃中瞬间完成（`instant`），或由浏览器自行决定（`auto`，默认）。
改成 “指定滚动是否应平滑地进行动画显示” 如何

2023-03-19 23:52 UTC, yin1999 approved these changes

2023-03-19 23:52 UTC, merged