Update CN docs to sync with the latest docs
mdn/translated-content pull request #12260
Opened 2023-03-19 10:35 UTC by Hacker-C

### Description

更新 URLSearchParams API 的中文文档，和英文文档一致。

### Motivation

原中文文档的 [URLSearchParams](https://developer.mozilla.org/zh-CN/docs/Web/API/URLSearchParams/URLSearchParams) 里的已经和英文文档有较大差异，现在 URLSearchParams 已经没用被标记为一个实验性的 API，而且也能接收更多类型的参数类型（比如字符串键值对对象），但这些在中文文档中都没有说明。

### Additional details

### Related issues and pull requests

2023-03-19 11:36 UTC, jasonren0403 requested changes
请根据最新的英文文档补上相应的侧边栏和webworker宏

https://github.com/mdn/content/blob/main/files/en-us/web/api/urlsearchparams/urlsearchparams/index.md?plain=1

2023-03-20 12:41 UTC, fwqaaq commented on files/zh-cn/web/api/urlsearchparams/urlsearchparams/index.md
> +    - 一系列基于字面量的字符串键值对，或者任何对象，比如一个 {{domxref("FormData")}} 对象，能提供一系列字符串对的 [iterator](/zh-CN/docs/Web/JavaScript/Guide/Iterators_and_Generators#iterator) 对象。需要注意，文件将被序列化为 `[object File]`，而不是它们的文件名（就像在
```suggestion
    - 一系列基于字面量的字符串键值对，或者任何对象（例如 {{domxref("FormData")}} 对象），能提供一系列字符串对的[迭代器](/zh-CN/docs/Web/JavaScript/Guide/Iterators_and_Generators#迭代器)对象。需要注意，{{domxref("File")}} 将被序列化为 `[object File]`，而不是它们的文件名（就像 `application/x-www-form-urlencoded` 格式中的那样）。
```

2023-03-20 12:41 UTC, fwqaaq commented on files/zh-cn/web/api/urlsearchparams/urlsearchparams/index.md
> +**`URLSearchParams()`** 构造器创建并返回一个新的 {{domxref("URLSearchParams")}} 对象。开头的 `'?'` 字符会被忽略。
构造函数？构造函数的翻译用的可能更多一点。

2023-03-21 06:02 UTC, yin1999 commented on files/zh-cn/web/api/urlsearchparams/urlsearchparams/index.md
> +这个例子展示了如何从一个已有的带有 URLSearchParams 对象的 URL，用另一个 URLSearchParams 对象创建一个新的 URL。
```suggestion
这个示例展示了如何使用来自一个带有查询参数（search parameter）的 URL 构建的查询参数对象创建一个新的 URL。
```

2023-03-21 06:42 UTC, yin1999 approved these changes
Thanks

2023-03-21 06:48 UTC, merged