Add MutationObserver/MutationRecord
mdn/translated-content pull request #12312
Opened 2023-03-21 15:03 UTC by alattalatta

### Description

`MutationObserver`에서 `takeRecords()` 제외한 나머지를 추가합니다. `MutationRecord`의 인덱스만 추가합니다.

### Motivation

자료 누락

### Additional details

`observe()`의 "트리 분리 후에도 주시는 지속됨" 아래 내용의 경우 원문 이해가 안돼서 직접 해보고 동작 맞춰 적느라 차이가 좀 있어요.

### Related issues and pull requests

2023-03-21 23:47 UTC, wisedog requested changes
너무 훌륭한 PR 감사합니다. 덕분에 많이 배우고 갑니다. 

`alattalatta` 님께 논의드릴게 있는데요. 

- 본문에서 `subtree` 를 `서브트리`로 쓰셨는데 `하위 트리`는 어떨까요? 정해진 규칙은 없고 다른데서도 이 두 단어를 혼용해서 사용하긴 합니다. 
- 굉장히 사소한거지만... `명세`가 아니라 `명세서` 라고 합니다. (저도 자주 틀림)

2023-03-21 23:47 UTC, wisedog commented on files/ko/web/api/mutationobserver/mutationobserver/index.md
> +일어난 변경의 종류(자식의 변경, 특성의 변경)는 {{domxref("MutationRecord.type", "mutation.type")}} 속성을 통해 알 수 있습니다.
`자식의 변경` 보다는 원문 `a change to the list of children` 처럼 `자식의 목록 변경` 이 어떨까요?

2023-03-21 23:47 UTC, wisedog commented on files/ko/web/api/mutationobserver/index.md
요 쯤에 원문 하나가 빠져있습니다. 
```md
[Mutation Observer & customize resize event listener & demo](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver#mutation_observer_customize_resize_event_listener_demo)
https://codepen.io/milofultz/pen/LYjPXPw
```

2023-03-21 23:47 UTC, wisedog commented on files/ko/web/api/mutationobserver/index.md
> +  - : `MutationObserver`의 알림 큐를 비우고, 큐에서 대기 중이던 알림들은 {{domxref("MutationRecord")}}의 {{jsxref("Array")}}로 반환합니다.
```suggestion
  - : `MutationObserver`의 알림 큐를 비우고, 큐에서 대기 중이던 알림들은 새로운 {{domxref("MutationRecord")}}의 {{jsxref("Array")}}로 반환합니다.
```
원문의 `new`가 빠졌습니다. 새로 생성된다는 건.... 프로그래머에게 매우 중요한 문제겠죠? 😉

2023-03-21 23:47 UTC, wisedog commented on files/ko/web/api/mutationobserver/observe/index.md
> +`MutationObserver`는 노드들의 연결이 끊어져도 주시가 끊기지 않도록 설계됐습니다. 그래서 주시 중인 서브트리의 일부를 분리해 DOM의 다른 곳으로 옮기는 동시에 그 노드들의 특성을 변경하는 경우에도 특성 변경 알림까지 수신할 수 있슶니다.
`있습니다` 오타가... : )

2023-03-21 23:47 UTC, wisedog commented on files/ko/web/api/mutationobserver/observe/index.md
> +달리 말하자면 주시 중인 서브트리에서 노드들이 분리될 때, 분리로 인한 노드 제거 알림을 콜백으로 수신하기 전까지는 그 노드들의 주시가 해제되지 않으므로, DOM 트리의 변경과 노드 제거 알림 수신 사이에 발생하는 변경을 감지합니다. 이 동작 덕분에 분리된 노드들에 대한 주시를 새로 시작하기 전에 발생한 변경들을 놓치지 않을 수 있습니다.
이 부분 원문이 
`In other words, until you've been notified that nodes are being split off from your monitored subtree, you'll get notifications of changes to that split-off subtree and its nodes. ` 

라서 저라면 아마도 
`다시 말해, 주시 중인 하위 트리에서 노드가 분리된다는 알림을 받기 전까지는 분리된 하위 트리와 해당 노드의 변경 사항에 대한 알림을 받습니다.`

이렇게 해석할것 같습니다. 어떠실까요?

2023-03-25 15:52 UTC, alattalatta commented on files/ko/web/api/mutationobserver/index.md
예제 자체에 대한 설명이 전무하고, 바로 아래 라이브 예제도 "customize resize event listener"라는 헤딩에 충분히 맞는 설명이며 코드도 [좀 더 깊게 알아보기](https://hacks.mozilla.org/2012/05/dom-mutationobserver-reacting-to-dom-changes-without-killing-browser-performance/)에서 그대로 가져온 거라 제외했어요. 원본에 먼저 반영하는 게 순서긴 한데 content 저장소 클론할 때 얕게 해서 unshallow 하기가 좀 귀찮네요... 
그래도 넣는 게 좋겠다 하시면 다시 답변해 주세요.

2023-03-25 16:02 UTC, wisedog commented on files/ko/web/api/mutationobserver/index.md
그렇게 생각하신다면 굳이 하실필요는 없다고 생각합니다. 수정하실게 있다면 수정 후 다시 리뷰 요청 부탁드리겠습니다.

2023-03-25 16:04 UTC, alattalatta commented on files/ko/web/api/mutationobserver/observe/index.md
> +달리 말하자면 주시 중인 서브트리에서 노드들이 분리될 때, 분리로 인한 노드 제거 알림을 콜백으로 수신하기 전까지는 그 노드들의 주시가 해제되지 않으므로, DOM 트리의 변경과 노드 제거 알림 수신 사이에 발생하는 변경을 감지합니다. 이 동작 덕분에 분리된 노드들에 대한 주시를 새로 시작하기 전에 발생한 변경들을 놓치지 않을 수 있습니다.
<pre>
다시 말해, 주시 중인 하위 트리에서 노드가 분리된다는 <del>알림을 받기</del><ins>알림이 콜백까지 전달되기</ins>
전까지는 분리된 하위 트리와 해당 노드의 변경 사항에 대한 알림을 <ins>계속</ins> 받습니다.
</pre>

원문(`disconnect()`)에서 (일관적이진 않지만) _notification_ 의 _detection_ 과 _report_ 를 구분하고 있고, '알림'의 '감지'와 '보고'라는 용어가 `observe()`에는 없으므로 동작의 명확함을 위해 '콜백까지 전달되기 전' + '계속'을 추가해봤는데 리뷰해 주세요~

2023-03-25 16:07 UTC, alattalatta commented
정말 명세*서*네요, 오래 안했더니 놓쳤는데 감사합니다~

서브트리 하위 트리 둘 다 용례가 거의 없네요. 그나마 하위 트리가 많은 편이니까 말씀하신대로 하위 트리로 바꿨습니다.

2023-03-26 06:43 UTC, wisedog commented on files/ko/web/api/mutationobserver/observe/index.md
> +달리 말하자면 주시 중인 서브트리에서 노드들이 분리될 때, 분리로 인한 노드 제거 알림을 콜백으로 수신하기 전까지는 그 노드들의 주시가 해제되지 않으므로, DOM 트리의 변경과 노드 제거 알림 수신 사이에 발생하는 변경을 감지합니다. 이 동작 덕분에 분리된 노드들에 대한 주시를 새로 시작하기 전에 발생한 변경들을 놓치지 않을 수 있습니다.
네네 이거 좋습니다!

2023-03-26 06:50 UTC, wisedog requested changes
흑흑 제가 놓친게 있어서 번거롭게 해드려 정말 죄송합니다.

2023-03-26 06:50 UTC, wisedog commented on files/ko/web/api/mutationobserver/disconnect/index.md
> +### Return value
죄송합니다. 제가 이걸 놓친것 같군요! 

```suggestion
### 반환 값
```

이것만 수정해주시면 바로 머지하도록 하겠습니다. 고생많으셨습니다. 😊

2023-03-26 07:06 UTC, alattalatta commented on files/ko/web/api/mutationobserver/disconnect/index.md
> +### Return value
헉

2023-03-26 08:46 UTC, merged