[zh-cn]: Newly translation - introducing complete toolchain.
mdn/translated-content pull request #12332
Opened 2023-03-22 10:14 UTC by JasonLamv-t

### Description

新的翻译内容，关于 web 开发中工具链的构建部份

### Motivation

同上

### Additional details

🈚️

2023-03-22 13:43 UTC, fwqaaq requested changes
Some suggestions

2023-03-22 13:43 UTC, fwqaaq commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain/index.md
> +![示例网站 “will it miss” 的屏幕截图](will-it-miss-screenshot.png)
```suggestion
![示例网站 “will it miss” 的屏幕截图](will-it-miss-screenshot.png)
```
```suggestion
![示例网站“will it miss”的屏幕截图](will-it-miss-screenshot.png)
```

2023-03-22 13:43 UTC, fwqaaq commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain/index.md
> +正如我们在 [第一章](/zh-CN/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Overview) 中所讨论的那样，工具链将分为以下阶段：
```suggestion
正如我们在[第一章](/zh-CN/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Overview)中所讨论的那样，工具链将分为以下阶段：
```

2023-03-22 13:43 UTC, fwqaaq commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain/index.md
> +> **备注：**虽然不清楚具体的安装过程，但安装 npm 时还会安装一个名为 npx 的补充工具。我们稍后将使用 npx 来帮助运行作为项目本地依赖项安装的工具。
```suggestion
> **备注：** 虽然不清楚具体的安装过程，但安装 npm 时还会安装一个名为 npx 的补充工具。我们稍后将使用 npx 来帮助运行作为项目本地依赖项安装的工具。
```

2023-03-22 13:43 UTC, fwqaaq commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain/index.md
> +你可以以多种不同的方式与 git 进行交互，从使用命令行发出命令，到使用 [git GUI 应用程序](https://git-scm.com/downloads/guis) 通过按按钮发出相同的命令，甚至从直接在代码编辑器内部使用，如下面的 Visual Studio Code 示例所示：
```suggestion
你可以以多种不同的方式与 git 进行交互，从使用命令行发出命令，到使用 [git GUI 应用程序](https://git-scm.com/downloads/guis)通过按按钮发出相同的命令，甚至从直接在代码编辑器内部使用，如下面的 Visual Studio Code 示例所示：
```

2023-03-22 13:43 UTC, fwqaaq commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain/index.md
> +![ESLint error integration shown in VS Code](eslint-error.png)
漏了

2023-03-22 13:43 UTC, fwqaaq commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain/index.md
> +   使用这些设置，当 Prettier 为你格式化 JavaScript 代码时，它将对所有带引号的值使用单引号，并且不使用尾随逗号（这是 ECMAScript 的新特性，在旧版浏览器中这会导致错误）。你可以在 [Prettier 文档](https://prettier.io/docs/en/configuration.html) 中找到更多关于配置 Prettier 的信息。
```suggestion
   使用这些设置，当 Prettier 为你格式化 JavaScript 代码时，它将对所有带引号的值使用单引号，并且不使用尾随逗号（这是 ECMAScript 的新特性，在旧版浏览器中这会导致错误）。你可以在 [Prettier 文档](https://prettier.io/docs/en/configuration.html)中找到更多关于配置 Prettier 的信息。
```

2023-03-23 01:02 UTC, yin1999 approved these changes
Thanks!

2023-03-23 01:02 UTC, merged