zh-CN: Add space between the ** add text content
mdn/translated-content pull request #12342
Opened 2023-03-22 14:36 UTC by Yukiniro

### Description

### Motivation

### Additional details

### Related issues and pull requests

Fixes #12341

2023-03-22 14:42 UTC, fwqaaq requested changes
中文之间不需要空格

2023-03-22 14:42 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/array/findindex/index.md
> +**`findIndex()`** 方法返回数组中满足提供的测试函数的第一个元素的 **索引**。若没有找到对应元素则返回 -1。
```suggestion
**`findIndex()`** 方法返回数组中满足提供的测试函数的第一个元素的**索引**。若没有找到对应元素则返回 -1。
```

https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md

2023-03-22 14:42 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/array/findindex/index.md
> +另请参见 {{jsxref("Array.find", "find()")}} 方法，它返回数组中找到的元素的 **值**，而不是其索引。
```suggestion
另请参见 {{jsxref("Array.find", "find()")}} 方法，它返回数组中找到的元素的**值**，而不是其索引。
```

2023-03-22 14:42 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/array/findindex/index.md
> +数组中通过提供测试函数的第一个元素的 **索引**。否则，返回 -1
```suggestion
数组中通过提供测试函数的第一个元素的**索引**。否则，返回 -1
```

2023-03-22 14:51 UTC, Yukiniro commented on files/zh-cn/web/javascript/reference/global_objects/array/findindex/index.md
> +**`findIndex()`** 方法返回数组中满足提供的测试函数的第一个元素的 **索引**。若没有找到对应元素则返回 -1。
好的 多谢

2023-03-22 22:08 UTC, yin1999 approved these changes
对于简单的错误修改，不用特地开issue，再在pr中引用这个issue。直接在pr中把错误和修改的内容描述清楚即可。

2023-03-22 22:09 UTC, merged

2023-03-23 00:03 UTC, Yukiniro commented
> 对于简单的错误修改，不用特地开issue，再在pr中引用这个issue。直接在pr中把错误和修改的内容描述清楚即可。

好的