[zh] Add "CSS Properties and Values API" translation
mdn/translated-content pull request #12346
Opened 2023-03-22 16:35 UTC by gxy5202

### Description

Add "CSS Properties and Values API" simplified Chinese translation.

### Motivation

There is no zh-CN version for "CSS Properties and Values API".

### Additional details

原文 https://developer.mozilla.org/en-US/docs/Web/API/CSS_Properties_and_Values_API

### Related issues and pull requests

2023-03-22 18:28 UTC, JasonLamv-t requested changes
Check https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md

2023-03-22 18:28 UTC, JasonLamv-t commented on files/zh-cn/web/api/css_properties_and_values_api/index.md
> +**CSS Properties and Values API** — [CSS Houdini](/en-US/docs/Web/Guide/Houdini) API 的一部分 — 允许开发者显式地定义他们的 {{cssxref('--*', 'CSS custom properties')}}，允许设置属性类型检查、默认值以及是否可继承其值。
```suggestion
**CSS Properties and Values API** — [CSS Houdini](/zh-CN/docs/Web/Guide/Houdini) API 的一部分——允许开发者显式地定义他们的 {{cssxref('--*', 'CSS custom properties')}}，允许设置属性类型检查、默认值以及是否可继承其值。
```

2023-03-22 18:28 UTC, JasonLamv-t commented on files/zh-cn/web/api/css_properties_and_values_api/index.md
> +## 参考
```suggestion
## 参见
```

2023-03-22 18:28 UTC, JasonLamv-t commented on files/zh-cn/web/api/css_properties_and_values_api/index.md
> +- [CSS Houdini](/en-US/docs/Web/Guide/Houdini)
```suggestion
- [Using the CSS properties and values API](/zh-CN/docs/Web/API/CSS_Properties_and_Values_API/guide)
- [CSS Painting API](/zh-CN/docs/Web/API/CSS_Painting_API)
- [CSS Typed Object Model](/zh-CN/docs/Web/API/CSS_Typed_OM_API)
- [CSS Houdini](/zh-CN/docs/Web/Guide/Houdini)
```

2023-03-23 01:41 UTC, yin1999 commented on files/zh-cn/web/api/css_properties_and_values_api/index.md
> +**CSS Properties and Values API** — [CSS Houdini](/zh-CN/docs/Web/Guide/Houdini) API 的一部分——允许开发者显式地定义他们的 {{cssxref('--*', 'CSS custom properties')}}，允许设置属性类型检查、默认值以及是否可继承其值。
```suggestion
**CSS 属性和值 API**（CSS Properties and Values API）——[CSS Houdini](/zh-CN/docs/Web/Guide/Houdini) API 的一部分——允许开发者显式地定义它们的 {{cssxref('--*', 'CSS custom properties')}}，允许设置属性类型检查、默认值以及是否可继承其值。
```

2023-03-23 01:41 UTC, yin1999 commented on files/zh-cn/web/api/css_properties_and_values_api/index.md
> +  - : 定义了浏览器应该如何解析 {{cssxref('--*', 'CSS custom properties')}}。通过 [CSS](/zh-CN/docs/Web/CSS) 中的 {{cssxref('@property')}} [at-rule](/zh-CN/docs/Web/CSS/At-rule) 访问该接口。
```suggestion
  - : 定义了浏览器应该如何解析 {{cssxref('--*', 'CSS custom properties')}}。通过 [CSS](/zh-CN/docs/Web/CSS) 中的 {{cssxref('@property')}} [at 规则](/zh-CN/docs/Web/CSS/At-rule)访问该接口。
```

2023-03-23 01:41 UTC, yin1999 commented on files/zh-cn/web/api/css_properties_and_values_api/index.md
> +title: CSS Properties and Values API
```suggestion
title: CSS 属性和值 API
```

2023-03-23 01:41 UTC, yin1999 commented on files/zh-cn/web/api/css_properties_and_values_api/index.md
> +- [CSS Typed Object Model](/zh-CN/docs/Web/API/CSS_Typed_OM_API)
```suggestion
- [CSS 类型对象模型](/zh-CN/docs/Web/API/CSS_Typed_OM_API)
```

2023-03-23 01:50 UTC, gxy5202 commented
> Check https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md

Thanks

2023-03-23 01:50 UTC, yin1999 approved these changes
Thanks

2023-03-23 01:51 UTC, yin1999 commented on files/zh-cn/web/api/css_properties_and_values_api/index.md
> +以下代码在 [JavaScript](/zh-CN/docs/Web/JavaScript) 中使用 {{domxref('CSS.registerProperty')}} 输入一个 {{cssxref('--*', 'CSS custom properties')}}，`--my-color`，将其作为一个颜色，然后为其设置一个默认值，并且不允许继承它的值。
```suggestion
以下代码在 [JavaScript](/zh-CN/docs/Web/JavaScript) 中使用 {{domxref('CSS.registerProperty')}} 输入一个 {{cssxref('--*', 'CSS 自定义属性')}}，`--my-color`，将其作为一个颜色，然后为其设置一个默认值，并且不允许继承它的值。
```

2023-03-23 01:58 UTC, merged