[zh-cn] complete translation of web performance landing page
mdn/translated-content pull request #12345
Opened 2023-03-22 16:19 UTC by jasonren0403

### Description

### Motivation

don't remain redundant outdated English content

### Additional details

### Related issues and pull requests

2023-03-22 18:48 UTC, JasonLamv-t requested changes
一些建议

2023-03-22 18:48 UTC, JasonLamv-t commented on files/zh-cn/learn/performance/index.md
> +- [CSS 性能特性](/en-US/docs/Learn/Performance/CSS)
```suggestion
- [CSS 性能特性](/zh-CN/docs/Learn/Performance/CSS)
```

2023-03-22 18:48 UTC, JasonLamv-t commented on files/zh-cn/learn/performance/index.md
> +  - : 开发人员可以做很多事情来提高性能，但多快才算够快？你怎样才能说服当权者相信这些努力的重要性？一旦优化了，你如何确保臃肿不会再出现？在这篇文章中，我们将探讨如何说服管理层，发展一种性能文化和性能预算，并介绍如何确保回归不会潜入你的代码库。
```suggestion
  - : 开发人员可以采取许多措施来提高系统的性能，但是什么样的速度才算快？如何说服管理层重视这些努力？一旦优化完成，如何确保系统不会再次出现性能问题？本文将探讨如何说服管理层、如何培养性能文化和制定性能预算，并介绍确保系统不会出现性能回退的方法。
```

2023-03-22 18:48 UTC, JasonLamv-t commented on files/zh-cn/learn/performance/index.md
> +  - : 看看你是否需要包括外部字体，如果需要，如何包括你的设计所需的字体，对你的网站性能影响最小。
```suggestion
  - : 看看你是否需要引入外部字体，如果需要，如何以对网站性能影响最小的方式引入你的设计所需的字体。
```

2023-03-22 18:48 UTC, JasonLamv-t commented on files/zh-cn/learn/performance/index.md
> +  - : 随着移动设备上的网络访问如此流行，所有的移动平台都有成熟的网络浏览器，但带宽、CPU 和电池寿命可能有限，考虑你的网络内容在这些平台上的性能是很重要的。本文探讨了针对移动设备的性能考虑。
```suggestion
  - : 随着移动设备上的网络访问普及，所有的移动平台都有成熟的网络浏览器，但可能存在带宽、CPU和电池寿命受限等问题，因此必须考虑在这些平台上提供的Web内容的性能。本文探讨了针对移动设备的性能考虑。
```

2023-03-22 18:48 UTC, JasonLamv-t commented on files/zh-cn/learn/performance/index.md
> +  - : 如果使用得当，JavaScript 可以实现交互式和沉浸式的网络体验——或者它可以显著损害下载时间、渲染时间、应用内性能、电池寿命和用户体验。本文概述了一些应该考虑的 JavaScript 最佳实践，以确保即使是复杂的内容也能尽可能地执行。
```suggestion
  - : 如果使用得当，JavaScript 可以实现交互式和沉浸式的网络体验——或者它可以显著增加下载时间、渲染时间并损害应用性能、电池寿命和用户体验。本文概述了一些应该考虑的 JavaScript 最佳实践，以确保即使是复杂的内容也能尽可能地执行。
```

2023-03-23 00:53 UTC, jasonren0403 commented on files/zh-cn/learn/performance/index.md
> +  - : 随着移动设备上的网络访问如此流行，所有的移动平台都有成熟的网络浏览器，但带宽、CPU 和电池寿命可能有限，考虑你的网络内容在这些平台上的性能是很重要的。本文探讨了针对移动设备的性能考虑。
```suggestion
  - : 随着移动设备上的网络访问普及，所有的移动平台都有成熟的网络浏览器，但可能存在带宽、CPU 和电池寿命受限等问题，因此必须考虑在这些平台上提供的 Web 内容的性能。本文探讨了针对移动设备的性能考虑。
```

2023-03-23 01:36 UTC, yin1999 approved these changes

2023-03-23 01:36 UTC, merged