[ko] Bitwise NOT(~) traslation
mdn/translated-content pull request #12357
Opened 2023-03-23 10:32 UTC by onehunnitconst

### Description
 
[JavaScript 레퍼런스의 Bitwise NOT(~) 문서](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_NOT)를 한국어로 번역하였습니다.

### Motivation

해당 문서의 한국어 번역이 없어 추가하였습니다.

### Additional details

번역에 처음 기여하게 되었습니다!

### Related issues and pull requests

2023-04-11 06:28 UTC, yujo11 approved these changes

2023-04-11 06:30 UTC, yujo11 requested changes
안녕하세요 @onehunnitconst 님 먼저 리뷰가 늦어져서 죄송합니다 🙇‍♂️🙇‍♂️🙇‍♂️

[file changed](https://github.com/mdn/translated-content/pull/12357/files) 확인해보시고 markdown lint에 걸리는 내용들만 수정해주시면 감사하겠습니다

2023-05-15 15:32 UTC, hochan222 commented
@yujo11 님 안녕하세요~!

PR이 많이 지연되어서 하기 3가지 중 하나 선택해서 진행 부탁드립니다 :)

(1) 현재 PR에 markdown lint 반영
(2) co-author로 새로운 PR 생성 후 반영
(3) 현재 PR close

2023-05-15 15:56 UTC, onehunnitconst commented
안녕하세요! 방금 이메일을 보고 PR을 올렸었다는 것을 깨달았습니다.. 죄송합니다!
일단 markdown lint에 걸리는 내용들을 수정하였는데, 이렇게 하는 것이 맞는 지 모르겠습니다!

2023-05-15 16:00 UTC, hochan222 approved these changes

2023-05-15 16:02 UTC, hochan222 commented
@onehunnitconst 바로 반영해주셔서 감사합니다!! 모두 잘 수정되었습니다.

PR 리뷰가 늦어진점 죄송합니다. 좋은 하루 보내세요 :)

2023-05-15 16:04 UTC, hochan222 commented
@yujo11 님께서 request change 요청을 주셔서, 직접 approve전에는 병합이 되지 않나봅니다! 확인 후 병합해주세요~!

@onehunnitconst 님, 아마 다른 사항은 문제없어서 yujo님 확인 후 병합하면 될듯합니다. 감사합니다!

2023-05-16 03:49 UTC, yujo11 approved these changes
안녕하세요 @onehunnitconst 님 리뷰가 늦어져서 죄송합니다 🙇‍♂️

도와주신 @hochan222 님 감사드립니다

이 PR은 Merge 하도록 하겠습니다

2023-05-16 03:49 UTC, merged