feat: 'Svelte variables props' 한글 번역본 추가
mdn/translated-content pull request #12363
Opened 2023-03-23 23:01 UTC by thewoowon

'Svelte variables props' 한글 번역본을 추가했습니다.

### Description

- svelte_variables_props 폴더 생성 및 'svelte_variables_props' 마크다운 추가

### Motivation

Interested in contributing to open source

### Additional details

구체적인 릴리즈 정보를 추적하려면 아래의 소스커밋 코드를 확인하세요.
- 4def230f85756724b59660e3cd9de363db724ef8

### Related issues and pull requests

2023-04-02 03:53 UTC, thewoowon commented
다음 문서도 준비되어 있습니다.
확인 부탁드립니다.

2023-04-20 08:49 UTC, yechoi42 commented
@thewoowon 님 리뷰가 늦어져 죄송합니다. 오늘 중으로 리뷰 완료하도록 하겠습니다.

2023-04-20 13:11 UTC, yechoi42 requested changes
안녕하세요! @thewoowon 님. 수정 요청 드린 부분이 있으니, 확인후 저를 다시 멘션해주시거나 제게 다시 리뷰 요청 부탁드리겠습니다.

2023-04-20 13:11 UTC, yechoi42 commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/svelte_variables_props/index.md
> +   이것은 입력에 대한 양방향 데이터 바인딩의 정형화된 구현입니다. 하지만 이렇게 할 필요는 없습니다 왜냐하면 Svelte는 [`bind:property`](https://svelte.dev/docs#bind_element_property) 지시문을 사용하여 모든 속성을 변수에 바인딩하는 더 쉬운 방법을 제공합니다.
```suggestion
   이는 입력에 대한 양방향 데이터 바인딩을 수동으로 구현한 것입니다. 하지만 이렇게 할 필요는 없습니다 왜냐하면 Svelte는 [`bind:property`](https://svelte.dev/docs#bind_element_property) 지시문을 사용하여 모든 속성을 변수에 바인딩하는 더 쉬운 방법을 제공합니다.
```
뒷 문장을 미루어보았을 때, manual은 수동으로 해석하는 것이 더 자연스러울 듯해 제안드립니다.

2023-04-20 13:11 UTC, yechoi42 commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/svelte_variables_props/index.md
> +6. 이제 폼이 Submit 될 때마다 `addTodo()`를 호출하도록 HTML을 업데이트하려고 합니다. NewTodo 폼의 여는 태그를 다음과 같이 업데이트하세요.
```suggestion
6. 이제 폼이 제출(submit)될 때마다 `addTodo()`를 호출하도록 HTML을 업데이트하려고 합니다. NewTodo 폼의 여는 태그를 다음과 같이 업데이트하세요.
```

2023-04-20 13:11 UTC, yechoi42 commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/svelte_variables_props/index.md
> +지금은 충분합니다! 이 문서에서 우리는 이미 우리가 원하는 대부분의 기능을 구현했습니다. 우리의 앱은 할 일을 표시, 추가 및 삭제하고, 완료된 상태를 전환하고, 완료한 작업 수를 표시하고, 필터를 적용할 수 있습니다.
```suggestion
이 정도면 충분합니다! 이 문서에서 우리는 이미 우리가 원하는 대부분의 기능을 구현했습니다. 우리의 앱은 할 일을 표시, 추가 및 삭제하고, 완료된 상태를 전환하고, 완료한 작업 수를 표시하고, 필터를 적용할 수 있습니다.
```
번역투로 느껴져 자연스럽게 느껴지도록 수정하였습니다.

2023-04-20 13:11 UTC, yechoi42 commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/svelte_variables_props/index.md
> +다시 말하지만 이것은 좋은 진전입니다. 이 시점에서 이제 작업을 삭제할 수 있습니다. 할일 항목의 _Delete_ 버튼을 누르면 관련 할일이 `todos` 배열에서 제거되고 더 이상 표시되지 않도록 UI가 업데이트됩니다. 또한 이제 확인란을 선택할 수 있으며 관련 할 일의 완료된 상태가 이제 `todos` 배열에서 업데이트됩니다.
```suggestion
다시 말하지만 이것은 좋은 진전입니다. 이 시점에서 이제 작업을 삭제할 수 있습니다. 할 일 항목의 _Delete_ 버튼을 누르면 관련 할 일이 `todos` 배열에서 제거되고 더 이상 표시되지 않도록 UI가 업데이트됩니다. 또한 이제 확인란을 선택할 수 있으며 관련 할 일의 완료된 상태가 이제 `todos` 배열에서 업데이트됩니다.
```

2023-04-20 13:11 UTC, yechoi42 commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/svelte_variables_props/index.md
> +7. 이 시점에서 새 할일을 추가하려고 하면 새 할 일은 할 일 배열에 추가되지만 UI는 업데이트되지 않습니다. Svelte에서는 [반응성은 할당으로 트리거됨](https://svelte.dev/docs#2_Assignments_are_reactive)을 기억하세요. 즉, `addTodo()` 함수가 실행되고 요소가 `todos` 배열에 추가되지만 Sve
```suggestion
7. 이 시점에서 새 할 일을 추가하려고 하면 새 할 일은 할 일 배열에 추가되지만 UI는 업데이트되지 않습니다. Svelte에서는 [반응성은 할당으로 트리거됨](https://svelte.dev/docs#2_Assignments_are_reactive)을 기억하세요. 즉, `addTodo()` 함수가 실행되고 요소가 `todos` 배열에 추가되지만 Svelte는 push 메서드가 배열을 수정했음을 감지하지 못하므로 작업 `<ul>`을 새로 고치지 않습니다.
```

2023-04-21 11:25 UTC, thewoowon commented
@yechoi42 요청하신 부분 모두 확인했습니다.
리뷰에 정말 감사드립니다.

2023-04-21 13:56 UTC, yechoi42 approved these changes
기다려주셔서 감사합니다! 머지하겠습니다 :)

2023-04-21 13:57 UTC, merged