[zh-cn]: Update translation of Array.findIndex.
mdn/translated-content pull request #12388
Opened 2023-03-25 11:40 UTC by JasonLamv-t

### Description

更新 `Array.findIndex()` 方法

### Motivation

同上

### Additional details

🈚️

2023-03-25 12:00 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/array/findindex/index.md
> +  应该为数组中的每个元素执行的函数。它应该返回一个[真值](/zh-CN/docs/Glossary/Truthy)来指示已找到匹配的元素。
```suggestion
  - : 应该为数组中的每个元素执行的函数。它应该返回一个[真值](/zh-CN/docs/Glossary/Truthy)来指示已找到匹配的元素。
```

2023-03-26 00:22 UTC, yin1999 requested changes

2023-03-26 00:22 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/findindex/index.md
> +console.log([4, 6, 8, 9, 12].findIndex(isPrime)); // -1, 没有找到
```suggestion
console.log([4, 6, 8, 9, 12].findIndex(isPrime)); // -1，没有找到
```

2023-03-26 00:22 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/findindex/index.md
> +console.log([4, 6, 7, 9, 12].findIndex(isPrime)); // 2 (array[2] is 7)
```suggestion
console.log([4, 6, 7, 9, 12].findIndex(isPrime)); // 2（array[2] 是 7）
```

2023-03-26 00:22 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/findindex/index.md
> +您可以搜索稀疏数组中的 `undefined` 并来获取空槽的索引。
请使用你

```suggestion
你可以搜索稀疏数组中的 `undefined` 并来获取空槽的索引。
```

2023-03-26 00:23 UTC, yin1999 approved these changes

2023-03-26 00:25 UTC, merged