zh-cn: sync content for css direction
mdn/translated-content pull request #12380
Opened 2023-03-25 01:17 UTC by daiwanxing

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-03-25 03:18 UTC, fwqaaq requested changes
还有其他未修改的地方也要一并修改

2023-03-25 03:18 UTC, fwqaaq commented on files/zh-cn/web/css/direction/index.md
>  值得注意的是文本方向通常由文档定义 (e.g., with [HTML's `dir` attribute](/zh-CN/docs/Web/HTML/Global_attributes/dir)) 而不是通过直接使用 `direction` 属性定义。
```suggestion
值得注意的是文本方向通常由文档定义（例如，使用 [HTML 的 `dir` 属性](/zh-CN/docs/Web/HTML/Global_attributes/dir)）而不是通过直接使用 `direction` 属性定义。
```

2023-03-25 03:18 UTC, fwqaaq commented on files/zh-cn/web/css/direction/index.md
>  CSS 属性 **`direction`** 用来设置文本、表列水平溢出的方向。 `rtl` 表示从右到左 (类似希伯来语或阿拉伯语)， `ltr` 表示从左到右 (类似英语等大部分语言).{{EmbedInteractiveExample("pages/css/direction.html")}}
应修改为中文的标点

2023-03-26 00:16 UTC, yin1999 commented on files/zh-cn/web/css/direction/index.md
> +**`direction`** CSS 属性用于设置文本流的方向，即文本、表格列和水平溢出的方向。对于从右到左书写的语言（如希伯来语或阿拉伯语），应将该属性设置为 `rtl`；对于从左到右书写的语言（如英语和大多数其他语言），则应将该属性设置为 `ltr`。
```suggestion
**`direction`** CSS 属性用于设置文本、表格列和水平溢出的方向。对于从右到左书写的语言（如希伯来语或阿拉伯语），应将该属性设置为 `rtl`；对于从左到右书写的语言（如英语和大多数其他语言），则应将该属性设置为 `ltr`。
```

![image](https://user-images.githubusercontent.com/15844309/227748277-fa059ec8-857e-4ae0-a5f3-60cc2a6bd4f1.png)

2023-03-26 00:16 UTC, yin1999 commented on files/zh-cn/web/css/direction/index.md
```suggestion

要使 `direction` 属性在行级元素上生效，{{Cssxref("unicode-bidi")}} 属性的值必须是 `embed` 或 `override`。

```

2023-03-26 00:17 UTC, yin1999 approved these changes

2023-03-26 00:22 UTC, merged