display プロパティの解説文をCSS仕様書にならって修正する
mdn/translated-content pull request #12389
Opened 2023-03-25 15:26 UTC by oti

### Description

https://developer.mozilla.org/ja/docs/Web/CSS/display#%E5%A4%96%E5%81%B4

「ブロック要素」は「ブロックレベル要素」を想起させますが、「インライン要素」も含めHTML4.01時代の語彙で、仕様は既に廃止され、HTML Standardにはないキーワードです。そもそも display の仕様には "block element" や "inline element" といったセンテンスで解説されていません。

https://www.w3.org/TR/css-display-3/#outer-role

### Motivation

HTMLとCSSの仕様が背マンティクスとスタイルに分離されて久しく、今日びHTML4.01時代の語彙が出現すると混乱を招きます。

### Additional details

### Related issues and pull requests

2023-03-29 14:41 UTC, mfuji09 requested changes
「ブロック要素」「インライン要素」という用語は英語版で使われているものです。この文書は英語版の翻訳記事であるため、表現を変更するのであれば、先に英語版を変更する必要があります。
日本語版に対して、英語版とは異なる記述へ変更をしたいのであれば、その前に content リポジトリーの英語版に対して変更を提案してみてください。

2023-05-06 04:43 UTC, oti commented
ping: https://github.com/mdn/content/pull/26612

2023-05-12 01:50 UTC, oti commented
@mfuji09 

`/ja/docs/web/css/display/index.html` の英語版の修正はマージされたようです。
https://github.com/mdn/content/pull/26612

CSS displayのページだけでなく、他ページの記述も修正するPRが英語版でマージされていますが、
https://github.com/mdn/content/pull/25891
こちらへの追従は別PRで行うべきしょうか？　それともこのPRに混ぜるべきでしょうか？

2023-05-28 02:55 UTC, mfuji09 commented
@oti さん
すみません、コメントを見落としていました。
一貫性を保つため、他のページの修正もこのPRにて行っていただけると幸いです。

2024-04-22 06:14 UTC, oti commented
@mfuji09 こちら長らく放置してしまってすみませんでした。随時されている英語版への追従で、わたしがやりたかった翻訳の変更は対応済みになっていました。なのでこのPRはcloseしたいと思います。ありがとうござました！

2024-04-22 06:14 UTC, closed without merging