Update Window
mdn/translated-content pull request #12407
Opened 2023-03-26 12:31 UTC by alattalatta

### Description

번역 안된 '이벤트' 구획을 영어 최신본으로 덮습니다. '인스턴스 속성'까지 번역을 추가합니다.

### Motivation

### Additional details

### Related issues and pull requests

2023-03-26 23:38 UTC, wisedog requested changes
너무 커서 엄두도 못내는 작업 도전(?)해주셔서 정말 감사합니다. 

빠진 부분 몇 군데만 채워넣어주시구요,  `Deprecated properties` 항목은 지우지 마시고 원문과 동일하게 복붙만 해주시면 (해석x) 될 것 같습니다.

2023-03-26 23:38 UTC, wisedog commented on files/ko/web/api/window/index.md
> +현재 스크립트가 작동 중인 창을 나타내는 전역 변수 `window`를 JavaScript 코드에서 접근할 수 있습니다.
직역은 노출이지만 노출되었으니 접근할 수 있다로 해석하셨군요! 👍

2023-03-26 23:38 UTC, wisedog commented on files/ko/web/api/window/index.md
> +  - : 현재 컨텍스트에서 보안 컨텍스트를 요구하는 기능을 사용할 수 있는지 나타냅니다.
원문은 
`Returns a boolean indicating whether the current context is secure (true) or not (false).`

이긴 합니다. 원문은 다른데 크게 보면 같은 말이라... 혹시 이대로 가는게 좋을까요? 아니면 수정하시는게 좋을까요?

2023-03-26 23:38 UTC, wisedog commented on files/ko/web/api/window/index.md
> -- {{domxref("Window.messageManager")}}
원문에는 있긴한데... 원문도 Broken Link 네요

2023-03-26 23:38 UTC, wisedog commented on files/ko/web/api/window/index.md
> -- {{domxref("Window.sidebar")}} {{non-standard_inline}} {{ReadOnlyInline}}
원문에는 아직 존재합니다.

2023-03-26 23:38 UTC, wisedog commented on files/ko/web/api/window/index.md
> -- {{domxref("Window.status")}}
이것도 아직 원문에 존재합니다.

2023-03-26 23:38 UTC, wisedog commented on files/ko/web/api/window/index.md
> -<div class="hidden"><h3 id="Deprecated_properties">Deprecated properties</h3><dl><dt>{{domxref("Window.content")}} and <code>Window._content</code> {{Non-standard_inline}} {{deprecated_inline}} {{Rea
원문에 `Deprecated properties` 항목이 있는데, 그게 여기 있는 항목입니다.

2023-03-27 04:45 UTC, alattalatta commented on files/ko/web/api/window/index.md
> +  - : 현재 컨텍스트에서 보안 컨텍스트를 요구하는 기능을 사용할 수 있는지 나타냅니다.
앗 원문 업데이트됐었나보네요. 이건 수정해야 할듯...

2023-03-27 04:55 UTC, alattalatta commented on files/ko/web/api/window/index.md
> -- {{domxref("Window.messageManager")}}
mdn/content#25654 에서 날라갔습니다.

2023-03-27 04:55 UTC, alattalatta commented on files/ko/web/api/window/index.md
> -- {{domxref("Window.sidebar")}} {{non-standard_inline}} {{ReadOnlyInline}}
https://github.com/mdn/content/pull/25651 에서 Deprecated properties로 이동했습니다.

2023-03-27 04:55 UTC, alattalatta commented on files/ko/web/api/window/index.md
> -- {{domxref("Window.status")}}
https://github.com/mdn/content/pull/25651 에서 Deprecated properties로 이동했습니다.

2023-03-27 04:55 UTC, alattalatta commented on files/ko/web/api/window/index.md
> -<div class="hidden"><h3 id="Deprecated_properties">Deprecated properties</h3><dl><dt>{{domxref("Window.content")}} and <code>Window._content</code> {{Non-standard_inline}} {{deprecated_inline}} {{Rea
이건 MDN 위키일 때... `Window`를 아무도 만지질 않는 와중에 저도 건드릴 엄두가 안나서 그냥 숨겨버렸던 (`<div class="hidden">`) 거였어요. 안그래도 번역 안된 거 투성인데 불필요한 분량만 많아보일까봐...

이벤트까지 끝내고 다시 가져와도 될까요?

2023-03-27 04:57 UTC, wisedog commented on files/ko/web/api/window/index.md
> -<div class="hidden"><h3 id="Deprecated_properties">Deprecated properties</h3><dl><dt>{{domxref("Window.content")}} and <code>Window._content</code> {{Non-standard_inline}} {{deprecated_inline}} {{Rea
그러셔도 되긴하는데... 지우는 것보다는 차라리 원문을 그냥 복붙으로 대체하시는건 어떨까요? 미래의 누군가(?)가 하도록 말이죠.. ㅎㅎ

2023-03-27 04:58 UTC, wisedog commented on files/ko/web/api/window/index.md
> -- {{domxref("Window.sidebar")}} {{non-standard_inline}} {{ReadOnlyInline}}
아... 이거 소스를 제가 확인안하고 MDN으로만 확인을 했군요. alattalatta 님 말씀이 맞습니다!

2023-03-27 04:59 UTC, wisedog commented on files/ko/web/api/window/index.md
> -- {{domxref("Window.messageManager")}}
확인했습니다. MDN 영문 페이지에는 남아있어서요. 앞으로는 저도 github 원문을 확인하도록 하겠습니다.

2023-03-28 00:02 UTC, wisedog commented
고생 많으셨습니다. 언제나 감사합니다.

2023-03-28 00:03 UTC, merged