zh-cn: sync content for animation-direction
mdn/translated-content pull request #12403
Opened 2023-03-26 08:26 UTC by daiwanxing

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-03-26 11:04 UTC, yin1999 requested changes

2023-03-26 11:04 UTC, yin1999 commented on files/zh-cn/web/css/animation-direction/index.md
> +  - : 动画在每个循环中正向播放。换句话说，每次动画循环时，动画将重置为起始状态并重新开始。这是默认值。
```suggestion
  - : 动画在每个循环中*正向*播放。换句话说，每次动画循环时，动画将重置为起始状态并重新开始。这是默认值。
```

2023-03-26 11:04 UTC, yin1999 commented on files/zh-cn/web/css/animation-direction/index.md
> +  - : 动画在每个循环中反向播放，第一次迭代是*正向*播放。确定循环是奇数还是偶数的计数从 1 开始。
两个都叫“反向”播放并不合适

2023-03-30 12:01 UTC, jasonren0403 commented on files/zh-cn/web/css/animation-direction/index.md
> +  - : 动画在每个循环中反向播放，第一次迭代是*正向*播放。确定循环是奇数还是偶数的计数从 1 开始。
alternate 应该是（正反）交替的意思，看开头那个运行实例就明白了

2023-03-31 11:45 UTC, yin1999 approved these changes

2023-03-31 11:45 UTC, merged