add message event translation
mdn/translated-content pull request #12425
Opened 2023-03-27 05:09 UTC by imbant

### Description

增加《EventSource：message 事件》

### Motivation

中文版缺失

2023-03-27 05:37 UTC, imbant commented
顺便请教下各位大佬，都是本地跑 yari 去看编辑后的效果吗？怎么解决本地 fork mdn 的仓库，同步源仓库更新的问题的？感觉是文件太多，每次本地 fetch+rebase 源仓库的改动，要等很久，有冲突的话更慢。这次提交试着用前边 bot 的 `Preview URLs` 做预览，没有本地跑 yari（而且目前 Windows 下启动 yari 会[失败](https://github.com/mdn/yari/issues/8391)） ，看上去也很方便

2023-03-27 07:21 UTC, yin1999 commented
> 都是本地跑 yari 去看编辑后的效果吗？怎么解决本地 fork mdn 的仓库，同步源仓库更新的问题的？

请参考 https://github.com/mdn/translated-content#setting-up-to-edit

2023-03-27 11:37 UTC, JasonLamv-t requested changes
Some suggestions

2023-03-27 11:37 UTC, JasonLamv-t commented on files/zh-cn/web/api/eventsource/message_event/index.md
> +browser-compat: api.EventSource.message_event
```suggestion
```
check：https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md

2023-03-27 11:37 UTC, JasonLamv-t commented on files/zh-cn/web/api/eventsource/message_event/index.md
> +此事件不能取消，也不会冒泡。
```suggestion
{{domxref("EventSource")}} API 的 `message` 事件，会在 EventSource 实例收到数据时触发。此事件不能取消，也不会冒泡。
```

2023-03-27 11:37 UTC, JasonLamv-t commented on files/zh-cn/web/api/eventsource/message_event/index.md
> +_本接口也继承了父接口 {{domxref("Event")}} 的属性_
```suggestion
*本接口也继承了父接口 {{domxref("Event")}} 的属性*
```

2023-03-27 11:42 UTC, JasonLamv-t commented
> 顺便请教下各位大佬，都是本地跑 yari 去看编辑后的效果吗？怎么解决本地 fork mdn 的仓库，同步源仓库更新的问题的？感觉是文件太多，每次本地 fetch+rebase 源仓库的改动，要等很久，有冲突的话更慢。这次提交试着用前边 bot 的 `Preview URLs` 做预览，没有本地跑 yari（而且目前 Windows 下启动 yari 会[失败](https://github.com/mdn/yari/issues/8391)） ，看上去也很方便

每次我开始新的翻译前，我都会确保我 fork 的 translated-content 跟源是同步的，然后再从我的 fork 里 checkout 新的分支，这样 merge 前一般没什么冲突；yari 的话，我直接 clone 了 mdn/content 到本地，直接设置好环境变量，这样就可以直接预览了，至于 content 的更新不影响预览自己的内容，强迫症的话每次预览前 pull 一下就好了

2023-03-28 02:56 UTC, imbant commented on files/zh-cn/web/api/eventsource/message_event/index.md
> +browser-compat: api.EventSource.message_event
收到，文档我再仔细看下，非常感谢

2023-03-28 03:00 UTC, imbant commented on files/zh-cn/web/api/eventsource/message_event/index.md
> +_本接口也继承了父接口 {{domxref("Event")}} 的属性_
收到，不过从 markdown 语法上两者都是斜体吧？我看[原文](https://github.com/mdn/content/blob/main/files/en-us/web/api/eventsource/message_event/index.md?plain=1#L32)是用下划线的，请问是有其他要求吗

2023-03-28 03:02 UTC, yin1999 commented on files/zh-cn/web/api/eventsource/message_event/index.md
> +_本接口也继承了父接口 {{domxref("Event")}} 的属性_
这里不需要修改，只有在[这个讨论](https://github.com/mdn/translated-content/discussions/12352#discussioncomment-5401774)中提到的特殊情况，才需要使用星号

2023-03-28 03:08 UTC, JasonLamv-t commented on files/zh-cn/web/api/eventsource/message_event/index.md
> +_本接口也继承了父接口 {{domxref("Event")}} 的属性_
原来如此

2023-03-28 03:09 UTC, imbant commented on files/zh-cn/web/api/eventsource/message_event/index.md
> +_本接口也继承了父接口 {{domxref("Event")}} 的属性_
学到了

2023-03-28 03:13 UTC, imbant commented
弄明白了，之前我是根据 [yari](https://github.com/mdn/yari) 的指南去预览的，现在看来直接在 content 里运行就好。更新太慢，应该是我本地仓库太久没有 pull 远程仓库导致的

2023-03-28 03:43 UTC, yin1999 commented on files/zh-cn/web/api/eventsource/message_event/index.md
> +title: "EventSource.onmessage"
```suggestion
title: EventSource：message 事件
```

2023-03-28 03:43 UTC, yin1999 commented on files/zh-cn/web/api/eventsource/message_event/index.md
> +{{domxref("EventSource")}} API 的 `message` 事件，会在 EventSource 实例收到数据时触发。此事件不能取消，也不会冒泡。
```suggestion
{{domxref("EventSource")}} API 的 `message` 事件，会在通过事件源收到数据时触发。

此事件不能取消，也不会冒泡。
```

2023-03-28 03:43 UTC, yin1999 commented on files/zh-cn/web/api/eventsource/message_event/index.md
> +一个 {{domxref("MessageEvent")}}。继承自 {{domxref("Event")}}。
```suggestion
_一个 {{domxref("MessageEvent")}}。继承自 {{domxref("Event")}}。_
```

2023-03-28 03:43 UTC, yin1999 commented on files/zh-cn/web/api/eventsource/message_event/index.md
> +_本接口也继承了父接口 {{domxref("Event")}} 的属性_
```suggestion
_本接口也继承了父接口 {{domxref("Event")}} 的属性。_
```

2023-03-28 03:43 UTC, yin1999 commented on files/zh-cn/web/api/eventsource/message_event/index.md
> +  - : 一个 `MessageEventSource`（可以是一个 {{glossary("WindowProxy")}}，{{domxref("MessagePort")}}，或者 {{domxref("ServiceWorker")}} 对象），表示事件发射器。
英文中表并联使用的是逗号，但在中文中请使用顿号（除非是一些特殊情况）

```suggestion
  - : 一个 `MessageEventSource`（可以是一个 {{glossary("WindowProxy")}}、{{domxref("MessagePort")}} 或 {{domxref("ServiceWorker")}} 对象），表示事件发射器。
```

2023-03-28 03:43 UTC, yin1999 commented on files/zh-cn/web/api/eventsource/message_event/index.md
> +- [使用 Server-sent events](/zh-CN/docs/Web/API/Server-sent_events/Using_server-sent_events)
```suggestion
- [使用 Server-sent 事件](/zh-CN/docs/Web/API/Server-sent_events/Using_server-sent_events)
```

2023-03-28 03:50 UTC, imbant commented on files/zh-cn/web/api/eventsource/message_event/index.md
> +title: "EventSource.onmessage"
我看中文的 [`error`](https://developer.mozilla.org/zh-CN/docs/Web/API/EventSource/error_event) 和 [`open`](https://developer.mozilla.org/zh-CN/docs/Web/API/EventSource/open_event) 事件，是用 `onevent` 的 handle 写法，请问这种情况应该和原文格式一致，还是应该和同目录下的其他篇目一致？

2023-03-28 03:51 UTC, imbant commented on files/zh-cn/web/api/eventsource/message_event/index.md
> +  - : 一个 `MessageEventSource`（可以是一个 {{glossary("WindowProxy")}}，{{domxref("MessagePort")}}，或者 {{domxref("ServiceWorker")}} 对象），表示事件发射器。
好的，收到

2023-03-28 05:13 UTC, yin1999 commented on files/zh-cn/web/api/eventsource/message_event/index.md
> +title: "EventSource.onmessage"
和原文一致，原来的 on_event_name 的写法已被废弃

2023-03-28 05:14 UTC, yin1999 approved these changes

2023-03-28 05:19 UTC, merged

2023-03-28 05:21 UTC, imbant commented on files/zh-cn/web/api/eventsource/message_event/index.md
> +title: "EventSource.onmessage"
好的