zh-cn(translate): compression and decompression
mdn/translated-content pull request #12428
Opened 2023-03-27 10:53 UTC by fwqaaq

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-03-27 11:07 UTC, JasonLamv-t approved these changes
LGTM.

2023-03-28 05:23 UTC, yin1999 requested changes

2023-03-28 05:23 UTC, yin1999 commented on files/zh-cn/web/api/compressionstream/index.md
> +{{domxref('Compression Stream API','','',' ')}} 的 **`CompressionStream`** 接口是一个用于压缩数据流的 API。
```suggestion
{{domxref('Compression Streams API', '', '', 1)}} 的 **`CompressionStream`** 接口是一个用于压缩数据流的 API。
```

2023-03-28 05:23 UTC, yin1999 commented on files/zh-cn/web/api/decompressionstream/index.md
> +{{domxref('Compression Stream API','','',' ')}} 接口的 **`DecompressionStream`** 是一个用与解压缩数据流的 API。
```suggestion
{{domxref('Compression Streams API','','',1)}} 的 **`DecompressionStream`** 接口是一个用与解压缩数据流的 API。
```

2023-03-28 05:24 UTC, yin1999 commented on files/zh-cn/web/api/compressionstream/index.md
> +{{domxref('Compression Stream API','','',' ')}} 的 **`CompressionStream`** 接口是一个用于压缩数据流的 API。
![image](https://user-images.githubusercontent.com/15844309/228136393-2b9a4d22-5241-4a59-860a-161b365a93ee.png)

2023-03-28 05:27 UTC, merged

2023-03-28 07:33 UTC, fwqaaq commented on files/zh-cn/web/api/decompressionstream/index.md
> +{{domxref('Compression Stream API','','',' ')}} 接口的 **`DecompressionStream`** 是一个用与解压缩数据流的 API。
oh, 搞错了，第二个参数才是描述