update: Web API の紹介 の未訳箇所
mdn/translated-content pull request #1245
Opened 2021-06-19 08:55 UTC by ShirasuGyoza

ページ：Web API の紹介
https://developer.mozilla.org/ja/docs/Learn/JavaScript/Client-side_web_APIs/Introduction

未訳箇所（オブジェクトに基づいています〜）があったため翻訳しました。

fix mozilla-japan/translation/issues/557
close fix mozilla-japan/translation/issues/557

2021-06-27 16:09 UTC, mfuji09 requested changes
指摘点の修正をお願いいたします。

2021-06-27 16:09 UTC, mfuji09 commented on files/ja/learn/javascript/client-side_web_apis/introduction/index.html
> +  <li>{{domxref("AudioContext")}} は、ブラウザ内で再生する音声を操作するのに使われる<a href="/ja/docs/Web/API/Web_Audio_API/Basic_concepts_behind_Web_Audio_API#Audio_graphs">オーディオグラフ</a>を表し、その音声を操作するためのたくさんのメソッドとプロパティを持ちます。<
「ブラウザ」ではなく「ブラウザー」と長音を使用してください。
（https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline を参照）
以下も同様にお願いします。

2021-06-27 16:09 UTC, mfuji09 commented on files/ja/learn/javascript/client-side_web_apis/introduction/index.html
> + <li>{{domxref("AudioDestinationNode")}} は、音声の最終目的地、つまりはコンピュータで実際に出力するデバイス（通常スピーカーやヘッドホン）を表します。</li>
「コンピュータ」→「コンピューター」

2021-06-27 16:09 UTC, mfuji09 commented on files/ja/learn/javascript/client-side_web_apis/introduction/index.html
> +<p>では、どのようにこれらのオブジェクトは互いに作用するのでしょうか？ こちらの<a href="https://github.com/mdn/learning-area/blob/master/javascript/apis/introduction/web-audio/index.html">シンプルな web audio の例</a> (<a href="https://mdn.gith
HTML の前後に半角空白をあけてください。

2021-06-27 16:09 UTC, mfuji09 commented on files/ja/learn/javascript/client-side_web_apis/introduction/index.html
> +<p>音声はソースから始まり、ソースはゲインノードに接続されるため、音声の音量を調整できます。次に、ゲインノードが宛先ノードに接続され、コンピューターでサウンドを再生できるようになります。（{{domxref("AudioContext.destination")}} は、スピーカなど、コンピュータのハードウエアで使用可能なデフォルトの {{domxref("AudioDestinationNo
「スピーカ」→「スピーカー」

2021-07-17 04:21 UTC, ShirasuGyoza commented on files/ja/learn/javascript/client-side_web_apis/introduction/index.html
> +  <li>{{domxref("AudioContext")}} は、ブラウザ内で再生する音声を操作するのに使われる<a href="/ja/docs/Web/API/Web_Audio_API/Basic_concepts_behind_Web_Audio_API#Audio_graphs">オーディオグラフ</a>を表し、その音声を操作するためのたくさんのメソッドとプロパティを持ちます。<
「ブラウザー」に統一しました。※既に翻訳されている同ページ内の箇所にも適用しています

2021-07-17 04:21 UTC, ShirasuGyoza commented on files/ja/learn/javascript/client-side_web_apis/introduction/index.html
> + <li>{{domxref("AudioDestinationNode")}} は、音声の最終目的地、つまりはコンピュータで実際に出力するデバイス（通常スピーカーやヘッドホン）を表します。</li>
「コンピューター」に統一しました。※既に翻訳されている同ページ内の箇所にも適用しています

2021-07-17 04:22 UTC, ShirasuGyoza commented on files/ja/learn/javascript/client-side_web_apis/introduction/index.html
> +<p>では、どのようにこれらのオブジェクトは互いに作用するのでしょうか？ こちらの<a href="https://github.com/mdn/learning-area/blob/master/javascript/apis/introduction/web-audio/index.html">シンプルな web audio の例</a> (<a href="https://mdn.gith
半角空白を追加しました。

2021-07-17 04:22 UTC, ShirasuGyoza commented on files/ja/learn/javascript/client-side_web_apis/introduction/index.html
> +<p>音声はソースから始まり、ソースはゲインノードに接続されるため、音声の音量を調整できます。次に、ゲインノードが宛先ノードに接続され、コンピューターでサウンドを再生できるようになります。（{{domxref("AudioContext.destination")}} は、スピーカなど、コンピュータのハードウエアで使用可能なデフォルトの {{domxref("AudioDestinationNo
「スピーカー」に統一しました。

2021-07-17 04:29 UTC, ShirasuGyoza commented
@mfuji09 レビューいただきありがとうございます。修正致しました。

2021-07-17 16:14 UTC, mfuji09 approved these changes
OKです。

2021-07-17 16:15 UTC, merged