Update Window
mdn/translated-content pull request #12451
Opened 2023-03-29 14:43 UTC by alattalatta

### Description

"... implemented from elsewhere" 섹션 제거를 반영합니다. 메서드들을 번역합니다.

### Motivation

번역 X

### Additional details

인코딩/디코딩 vs. 부호화/복호화

저장소 내 전체 검색 결과, 전자가 압도적이라 이 MR에서도 인코딩/디코딩으로 진행했습니다. (@hochan222)
굳이 여쭤보는 이유는 명확하게 대응되는 단어가 있어서 💭

```
- {{domxref("atob", "Window.atob()")}}
  - : Base64로 인코딩된 문자열 데이터를 디코딩합니다.
- {{domxref("btoa", "Window.btoa()")}}
  - : 이진 데이터 문자열을 Base64로 인코딩해 ASCII 문자열을 생성합니다.

- {{domxref("atob", "Window.atob()")}}
  - : Base64로 부호화된 문자열 데이터를 복호화합니다.
- {{domxref("btoa", "Window.btoa()")}}
  - : 이진 데이터 문자열을 Base64로 부호화해 ASCII 문자열을 생성합니다.
```

### Related issues and pull requests

#12407 에서 이어짐

2023-04-08 02:49 UTC, cos18 requested changes
기여 감사합니다! 리뷰드린 내용 확인 부탁드립니다.

2023-04-08 02:49 UTC, cos18 commented on files/ko/web/api/window/index.md
> +  - : 새로운 [사용자 정의 요소](/ko/docs/Web/Web_Components/Using_custom_elements)를 등록하거나, 이전에 등록한 요소에 대한 정보를 얻을 수 있는 {{domxref("CustomElementRegistry")}} 객체를 반환합니다.
```suggestion
  - : 새로운 [사용자 정의 요소](/ko/docs/Web/Web_Components/Using_custom_elements)를 등록하거나 이전에 등록한 요소에 대한 정보를 얻을 수 있는, {{domxref("CustomElementRegistry")}} 객체의 참조를 반환합니다.
```
`,`의 위치에 따라 해석의 여지가 달라질 수 있을 것 같아 이를 수정했습니다.
또한, `reference`의 의미가 누락된 것 같아 추가했습니다.

2023-04-09 13:55 UTC, hochan222 commented
> 저장소 내 전체 검색 결과, 전자가 압도적이라 이 MR에서도 인코딩/디코딩으로 진행했습니다.

@alattalatta 님 안녕하세요. 멘션주셔서 감사합니다.

- https://github.com/mdn/translated-content/issues/12452 

관련하여 이슈 생성했으며, **인코딩/디코딩**으로 우선 결정했습니다. 추가적인 의견 있으시면 커멘트 부탁드립니다.

좋은 하루 보내세요 :)

2023-04-09 13:56 UTC, hochan222 approved these changes
@cos18 님, 수정 사항 확인하여 병합하겠습니다!

2023-04-09 13:57 UTC, merged