zh-cn: sync content for animation-timing-function
mdn/translated-content pull request #12469
Opened 2023-03-31 07:53 UTC by daiwanxing

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-03-31 11:48 UTC, yin1999 requested changes

2023-04-01 13:40 UTC, yin1999 commented on files/zh-cn/web/css/animation-timing-function/index.md
> +  - : 按照 n 个停止点在转换中显示动画迭代，每个停止点等长时间显示。例如，如果 n 为 5，则有 5 个步骤。动画是否暂时停留在 0%、20%、40%、60% 和 80% 处，在 20%、40%、60%、80% 和 100% 处之间作出 5 个停止点，或者在动画沿着 0% 和 100% 之间做出 5 个停止点（在 0%、25%、50%、75% 和 100% 处）取决于使用以下跳跃项之一：
感觉翻译为阶跃并不合适，上下文阶跃和跳跃也有点杂糅在一起

@yarusome 你有什么想法

2023-04-01 13:56 UTC, daiwanxing commented on files/zh-cn/web/css/animation-timing-function/index.md
> +  - : 按照 n 个停止点在转换中显示动画迭代，每个停止点等长时间显示。例如，如果 n 为 5，则有 5 个步骤。动画是否暂时停留在 0%、20%、40%、60% 和 80% 处，在 20%、40%、60%、80% 和 100% 处之间作出 5 个停止点，或者在动画沿着 0% 和 100% 之间做出 5 个停止点（在 0%、25%、50%、75% 和 100% 处）取决于使用以下跳跃项之一：
关于这个，我是直接参考的中文维基百科的翻译，[阶跃函数](https://zh.wikipedia.org/wiki/%E9%98%B6%E8%B7%83%E5%87%BD%E6%95%B0)

2023-04-01 14:38 UTC, yarusome commented on files/zh-cn/web/css/animation-timing-function/index.md
> +  - : 按照 n 个停止点在转换中显示动画迭代，每个停止点等长时间显示。例如，如果 n 为 5，则有 5 个步骤。动画是否暂时停留在 0%、20%、40%、60% 和 80% 处，在 20%、40%、60%、80% 和 100% 处之间作出 5 个停止点，或者在动画沿着 0% 和 100% 之间做出 5 个停止点（在 0%、25%、50%、75% 和 100% 处）取决于使用以下跳跃项之一：
我其实觉得 stop 这个词的译法需要斟酌。这个词的意思类比公交停靠的站点，所以译为“停**止**点”不太达意。而且这个词还出现在颜色属性的文档中，需要协调一起调整。我目前只有一些感觉差强人意的译法：卡（qia）口、停靠点、经停点。

2023-05-31 03:52 UTC, yin1999 commented on files/zh-cn/web/css/animation-timing-function/index.md
> +  - : 按照 n 个途径点在转换中显示动画迭代，每个停止点等长时间显示。例如，如果 n 为 5，则有 5 个步骤。动画是否暂时停留在 0%、20%、40%、60% 和 80% 处，在 20%、40%、60%、80% 和 100% 处之间作出 5 个停止点，或者在动画沿着 0% 和 100% 之间做出 5 个停止点（在 0%、25%、50%、75% 和 100% 处）取决于使用以下跳跃项之一：
/cc @jasonren0403, @yarusome

2023-05-31 12:42 UTC, yarusome commented on files/zh-cn/web/css/animation-timing-function/index.md
> +  - : 按照 n 个途径点在转换中显示动画迭代，每个停止点等长时间显示。例如，如果 n 为 5，则有 5 个步骤。动画是否暂时停留在 0%、20%、40%、60% 和 80% 处，在 20%、40%、60%、80% 和 100% 处之间作出 5 个停止点，或者在动画沿着 0% 和 100% 之间做出 5 个停止点（在 0%、25%、50%、75% 和 100% 处）取决于使用以下跳跃项之一：
我正在翻译 [`<easing-funtion>`](https://developer.mozilla.org/en-US/docs/Web/CSS/easing-function)，或许可以等我今天修补英文版内容后在中文版的合并请求中敲定这个译法。

我觉得还是需要注意与 [<color-stop-list>](https://drafts.csswg.org/css-images-4/#gradient-colors) 的译法保持协调，所以这两个与动画高度关联的译法可能无法迁移。

2023-06-13 01:58 UTC, yin1999 approved these changes
Thanks @daiwanxing, @yarusome

2023-06-13 01:58 UTC, merged

2023-06-21 06:20 UTC, daiwanxing commented
终于被 merged 了🤣