zh-tw: sync with english version for Array.of()
mdn/translated-content pull request #12471
Opened 2023-03-31 10:00 UTC by jessiehu907

Sync with english version.

2023-03-31 11:12 UTC, yin1999 requested changes

2023-03-31 11:12 UTC, yin1999 commented on files/zh-tw/web/javascript/reference/global_objects/array/of/index.md
> +- [`Array.of()` polyfill](https://gist.github.com/rwaldron/3186576)
Removed in mdn/content#25802

```suggestion
```

2023-03-31 11:12 UTC, yin1999 commented on files/zh-tw/web/javascript/reference/global_objects/array/of/index.md
> +The `of()` method can be called on any constructor function that accepts a single argument representing the length of the new array.
请翻译一下这句话

2023-04-02 00:53 UTC, yin1999 commented on files/zh-tw/web/javascript/reference/global_objects/array/of/index.md
> +The `of()` method can be called on any constructor function that accepts a single argument representing the length of the new array.
```suggestion
可以在接受表示新陣列長度的單個參數的任何建構式上調用 `of()` 方法。
```

2023-04-02 10:36 UTC, jessiehu907 commented on files/zh-tw/web/javascript/reference/global_objects/array/of/index.md
> +The `of()` method can be called on any constructor function that accepts a single argument representing the length of the new array.
抱歉, 沒有即時看到, tks!

2023-04-02 11:11 UTC, yin1999 commented on files/zh-tw/web/javascript/reference/global_objects/array/of/index.md
>  - {{jsxref("Array")}}
```suggestion
- [`Array()`](/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/Array)
```

2023-04-02 11:12 UTC, yin1999 approved these changes
Thanks

2023-04-02 11:14 UTC, merged

2023-04-03 08:18 UTC, schalkneethling commented
Welcome to the community, @jessiehu907  🎉 Thank you for your contribution. If you are interested in more ways to contribute to MDN Web Docs, please have a look at our [contributor task board](https://github.com/orgs/mdn/projects/25). If you have any questions or need help finding something to work on, please ask for help in our [community discussions](https://github.com/orgs/mdn/discussions). We look forward to more of your contributions. 🙌