[zh-cn]: New translation of Array.groupToMap()
mdn/translated-content pull request #12503
Opened 2023-04-02 12:38 UTC by JasonLamv-t

### Description

添加 Array.groupToMap() 方法的翻译

### Motivation

同上

### Additional details

🈚️

2023-04-03 02:43 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/grouptomap/index.md
> +  - : A function to execute for each element in the array. It should return a value ({{Glossary("object")}} or {{Glossary("primitive")}}) indicating the group of the current element. The function is
```suggestion
```

2023-04-03 02:48 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/grouptomap/index.md
> +`callbackFn` 函数会被数组中的*每个*索引调用，而不仅仅是那些具有赋值的索引。在[稀疏数组](/zh-CN/docs/Web/JavaScript/Guide/Indexed_collections#稀疏)中，空槽的行为表现与 `undefined` 相同。
```suggestion
`callbackFn` 函数会被数组中的*每个*索引调用，而不仅仅是那些具有赋值的索引。在[稀疏数组](/zh-CN/docs/Web/JavaScript/Guide/Indexed_collections#稀疏数组)中，空槽的行为表现与 `undefined` 相同。
```

2023-04-03 04:19 UTC, yin1999 requested changes

2023-04-03 04:19 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/grouptomap/index.md
> +**`groupToMap()`** 方法根据提供的测试函数返回的值对调用数组的元素进行分组。最终返回的 {{jsxref("Map")}} 使用测试函数的唯一值作为键，可以用于获取每个组中的元素数组。
https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md#%E4%BB%A3%E5%90%8D%E8%AF%8D

2023-04-03 12:42 UTC, yin1999 requested changes

2023-04-03 12:42 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/grouptomap/index.md
> +该方法主要用于分组与对象相关的元素，特别是当该对象可能随时间而变化时。如果对象不变，你可以使用字符串表示它，并使用{{jsxref("Array.prototype.group()")}}分组元素。
```suggestion
该方法主要用于分组与对象相关的元素，特别是当该对象可能随时间而变化时。如果对象不变，你可以使用字符串表示它，并使用 {{jsxref("Array.prototype.group()")}} 分组元素。
```

2023-04-03 12:42 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/grouptomap/index.md
> +  - : 为数组中的每个元素执行的函数。它应该返回一个（{{Glossary("object")}} 或 {{Glossary("primitive")}}）来指示当前元素的组。该函数被调用时将传入以下参数：
```suggestion
  - : 为数组中的每个元素执行的函数。它应该返回一个值（{{Glossary("object")}} 或 {{Glossary("primitive")}}）来指示当前元素的组。该函数被调用时将传入以下参数：
```

2023-04-03 12:42 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/grouptomap/index.md
> +一个 {{jsxref("Map")}} 对象，其中每个组都有一个键，每个键都分配给一个包含组对应元素的数组。
Google 给出的翻译是不对的，不要太过于依赖机翻

2023-04-03 12:42 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/grouptomap/index.md
> +`Map` 的键可以被修改并仍然使用。但是，你不能重新创建键并仍然使用它。因此，任何需要使用映射的内容都保留对其键的引用是非常重要的。
被修改、被使用

```suggestion
`Map` 的键可以被修改和使用。但是，你不能重新创建键并仍然使用它。因此，任何需要使用映射的内容都保留对其键的引用是非常重要的。
```

2023-04-03 12:42 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/grouptomap/index.md
> +// 键可以修改并仍然使用
idto

2023-04-04 10:30 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/grouptomap/index.md
> +一个 {{jsxref("Map")}} 对象，其中每个组都有一个键，每个键都分配给一个包含组对应元素的数组。
```suggestion
一个为每个组分配了键的 {{jsxref("Map")}} 对象，每个键都分配了一个包含相关组元素的数组。
```

2023-04-04 10:32 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/grouptomap/index.md
> +// 键可以修改并仍然使用
```suggestion
// 键可以被修改和使用
```

2023-04-04 10:36 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/grouptomap/index.md
> +`Map` 的键可以被修改并仍然使用。但是，你不能重新创建键并仍然使用它。因此，任何需要使用映射的内容都保留对其键的引用是非常重要的。
```suggestion
`Map` 的键在修改后仍可以使用。但是，你不能重新创建键并仍然使用它。因此，任何需要使用映射的内容都保留对其键的引用是非常重要的。
```

2023-04-04 12:00 UTC, yin1999 approved these changes

2023-04-04 12:01 UTC, merged