translate `>>>=` operator doc in ko
mdn/translated-content pull request #12535
Opened 2023-04-03 14:50 UTC by notJoon

### Description

Unsigned right shift assignment 문서를 번역 후 추가했습니다.

2023-04-20 13:15 UTC, cos18 requested changes
늦은 리뷰 죄송합니다 ㅠㅠ
리뷰드린 내용 확인 부탁드립니다!

2023-04-20 13:15 UTC, cos18 commented on files/ko/web/javascript/reference/operators/unsigned_right_shift_assignment/index.md
> +**unsigned 오른쪽 시프트 할당(`>>>=`)** 연산자는 지정된 수 만큼의 비트를 오른쪽으로 이동시키고 그 결과를 변수에 할당합니다.
```suggestion
**unsigned 오른쪽 시프트 할당(`>>>=`)** 연산자는 지정된 수 만큼 [unsigned 오른쪽 시프트 연산](/ko/docs/Web/JavaScript/Reference/Operators/Unsigned_right_shift)을 수행하고 그 결과를 왼쪽 피연산자에 할당합니다.
```
문서는 최대한 원본을 유지하면서 번역해야 합니다. 링크의 경우에도 문서가 없어도 알아서 fallback되기 때문에 이후 문서가 추가되는 것을 대비해 넣어놓고, 의미가 누락된 내용을 추가했습니다.

2023-04-20 14:01 UTC, notJoon commented on files/ko/web/javascript/reference/operators/unsigned_right_shift_assignment/index.md
> +  sourceCommit: d85a7ba8cca98c2f6cf67a0c44f0ffd467532f20
오.. 저걸 빼먹었네요. 감사합니다

2023-04-20 14:06 UTC, notJoon commented
> 늦은 리뷰 죄송합니다 ㅠㅠ 리뷰드린 내용 확인 부탁드립니다!

나름 확인했다 했는데 깜박하고 빼먹은 부분이 많았네요.. 꼼꼼한 리뷰 감사합니다!

2023-04-20 15:13 UTC, cos18 commented
@notJoon 혹시 resolve와 add suggestion을 햇갈리셨나요? resolve만 누르면 브랜치에 반영이 되지 않습니다!

2023-04-28 12:39 UTC, notJoon commented
@cos18 ??? 제가 눈에 뭔가 씌였던거 같네요 다시 수정했습니다. 감사합니다

2023-04-29 04:48 UTC, cos18 approved these changes
LGTM! 수고하셨습니다 :)

2023-04-29 04:48 UTC, merged