Update index.md
mdn/translated-content pull request #12549
Opened 2023-04-04 07:04 UTC by abitwhy

2023-04-04 11:00 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/template_literals/index.md
> +不过，非法转义序列在"熟的"当中仍然会体现出来。它们将以 {{jsxref("undefined")}} 元素的形式存在于"熟的"数组之中：
这里的 cooked 指下面的代码块中的 cookied，上面也是

2023-04-04 15:08 UTC, abitwhy commented on files/zh-cn/web/javascript/reference/template_literals/index.md
请问哪些链接要改成中文？（我并不清楚哪些有对应的中文链接。）

2023-04-04 15:31 UTC, abitwhy commented on files/zh-cn/web/javascript/reference/template_literals/index.md
>  ```js
见 https://github.com/abitwhy/translated-content/commit/4d807ebe6492d37b28a5a5fe8b75c233435125f1

2023-04-04 15:31 UTC, abitwhy commented on files/zh-cn/web/javascript/reference/template_literals/index.md
>  ```js
见 https://github.com/abitwhy/translated-content/commit/4d807ebe6492d37b28a5a5fe8b75c233435125f1

2023-04-04 15:31 UTC, abitwhy commented on files/zh-cn/web/javascript/reference/template_literals/index.md
> +不过，非法转义序列在"熟的"当中仍然会体现出来。它们将以 {{jsxref("undefined")}} 元素的形式存在于"熟的"数组之中：
见 https://github.com/abitwhy/translated-content/commit/4d807ebe6492d37b28a5a5fe8b75c233435125f1

2023-04-04 15:37 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/template_literals/index.md
> +## 参见
[Lexical grammar](/zh-CN/docs/Web/JavaScript/Reference/Lexical_grammar) 这些引文中的阐述，可以修改，如果有中文的，可以参考。例如 <https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Lexical_grammar> 中的标题，其它的尽量也可以翻译

2023-04-04 17:54 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/template_literals/index.md
> +模板字面量用反引号 `` ` `` 括起来，而不是双引号 `"` 或单引号 `'`。
```suggestion
模板字面量用反引号（`` ` ``）括起来，而不是双引号（`"`）或单引号（`'`）。
```
这里考虑跟原文一样用括号括起来？

2023-04-05 06:43 UTC, abitwhy commented on files/zh-cn/web/javascript/reference/template_literals/index.md
> +模板字面量用反引号 `` ` `` 括起来，而不是双引号 `"` 或单引号 `'`。
https://github.com/abitwhy/translated-content/commit/dc7b67df755c4cb20f284a6353447f97da70cb6e
还修改了其他地方，以保持一致的风格。

2023-04-05 06:47 UTC, abitwhy commented on files/zh-cn/web/javascript/reference/template_literals/index.md
> +模板字面量用反引号 `` ` `` 括起来，而不是双引号 `"` 或单引号 `'`。
然而令人困惑的是，原文还有其他地方有不一致的风格：
![image](https://user-images.githubusercontent.com/68452982/230002094-d1fca189-029f-4c80-9ff5-8b3564d534fb.png)
所以有关于这个风格的明确规则吗？

2023-04-05 07:05 UTC, abitwhy commented on files/zh-cn/web/javascript/reference/template_literals/index.md
> +## 参见
见 https://github.com/abitwhy/translated-content/commit/fa5b701667097df58d941fcc85d0d3193a0cb2ce

2023-04-05 08:51 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/template_literals/index.md
> +模板字面量用反引号 `` ` `` 括起来，而不是双引号 `"` 或单引号 `'`。
目前还没有相关的约束

2023-04-05 14:03 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/template_literals/index.md
> +这允许标签函数以其第一个参数作为标识来缓存结果。为了进一步确保数组值不变，第一个参数及其[原始属性](#原始字符串)都会被[冻结](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/isFrozen)，因此你将无法改变它们。
```suggestion
这允许标签函数以其第一个参数作为标识来缓存结果。为了进一步确保数组值不变，第一个参数及其 [`raw` 属性](#原始字符串)都会被[冻结](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/isFrozen)，因此你将无法改变它们。
```

代码块里指的就是指的 `raw` 属性

2023-04-05 14:06 UTC, yin1999 requested changes

2023-04-05 14:06 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/template_literals/index.md
> +  - : 将成为模板字面量的一部分的字符串文本。几乎允许所有字符，包括[换行符](/zh-CN/docs/Web/JavaScript/Reference/Lexical_grammar#行终止符)和其他[空白字符](/zh-CN/docs/Web/JavaScript/Reference/Lexical_grammar#空白符)。但是，除非使用了标记函数，否则无效的转义序列将导致语法错误。
关于 `tag` 一词的上下文翻译不一致，其他几处也修改一下。

![image](https://user-images.githubusercontent.com/15844309/230105826-4d2684b5-39ce-48d9-850d-78a55b729258.png)

```suggestion
  - : 将成为模板字面量的一部分的字符串文本。几乎允许所有字符，包括[换行符](/zh-CN/docs/Web/JavaScript/Reference/Lexical_grammar#行终止符)和其他[空白字符](/zh-CN/docs/Web/JavaScript/Reference/Lexical_grammar#空白符)。但是，除非使用了[标签函数](#带标签的模版字面量及转义序列)，否则无效的转义序列将导致语法错误。
```

2023-04-05 15:25 UTC, abitwhy commented on files/zh-cn/web/javascript/reference/template_literals/index.md
> +**模板字面量**是用反引号（`` ` ``）分隔的字面量，允许[多行字符串](#多行字符串)、带嵌入表达式的[字符串插值](#字符串插值)和一种叫[带标签的模板](#带标签的模板)的特殊结构。（译注：几种语法。）
这应当只是我个人的困惑。

2023-04-05 16:04 UTC, abitwhy commented on files/zh-cn/web/javascript/reference/template_literals/index.md
> +  - : 将成为模板字面量的一部分的字符串文本。几乎允许所有字符，包括[换行符](/zh-CN/docs/Web/JavaScript/Reference/Lexical_grammar#行终止符)和其他[空白字符](/zh-CN/docs/Web/JavaScript/Reference/Lexical_grammar#空白符)。但是，除非使用了标记函数，否则无效的转义序列将导致语法错误。
见 https://github.com/abitwhy/translated-content/commit/5a10d104f0470d180711ec398b19d29ba1f78c20

2023-04-05 16:59 UTC, fwqaaq approved these changes

2023-04-07 00:58 UTC, JasonLamv-t approved these changes
NFQ.

2023-04-07 00:58 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/template_literals/index.md
> +// Some formatters will format this literal's content as HTML
翻译一下这部份？

2023-04-07 07:27 UTC, yin1999 approved these changes
感谢，整体翻译得挺好的，我修改了一些细微的错误

2023-04-07 07:27 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/template_literals/index.md
> +在源码中（译注：指在 ` `` ` 所包裹的范围内）插入的任何换行符都是模板字面量的一部分。
没有特殊的需要请不要加“译注”，我们正在从中文文档中移除相关的内容。

2023-04-07 07:28 UTC, merged

2023-04-07 07:55 UTC, abitwhy commented on files/zh-cn/web/javascript/reference/template_literals/index.md
> +在源码中（译注：指在 ` `` ` 所包裹的范围内）插入的任何换行符都是模板字面量的一部分。
明白，之前看到过这种用法，所以在自己对译文有疑惑时才考虑添加这样的解释。

2023-04-07 08:04 UTC, abitwhy commented
> 感谢，整体翻译得挺好的，我修改了一些细微的错误

也谢谢你们的所有指正~总算完成了这次翻译，里面确实存在太多错误了😅

2023-04-07 09:55 UTC, abitwhy commented on files/zh-cn/web/javascript/reference/template_literals/index.md
> +// Some formatters will format this literal's content as HTML
见 https://github.com/mdn/translated-content/pull/12549/commits/d64ea2617a9d3f516f9cb3bafab360058083002c