add a link to examples
mdn/translated-content pull request #12554
Opened 2023-04-04 14:31 UTC by imba-tjd

2023-04-04 17:41 UTC, JasonLamv-t requested changes

2023-04-04 17:41 UTC, JasonLamv-t commented on files/zh-cn/web/http/proxy_servers_and_tunneling/index.md
> +See [Proxy Auto-Configuration (PAC)](/zh-CN/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file) for more examples.
本行包括本文其他内容还未翻译为中文

2023-04-05 01:56 UTC, yin1999 commented on files/zh-cn/web/http/proxy_servers_and_tunneling/index.md
> +See [Proxy Auto-Configuration (PAC)](/zh-CN/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file) for more examples.
```suggestion
参见[代理自动配置（PAC）](/zh-CN/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file)以获取更多示例。
```

2023-04-05 04:39 UTC, yin1999 approved these changes

2023-04-05 04:39 UTC, merged