[zh-cn]: New translation of Array.fromAsync()
mdn/translated-content pull request #12558
Opened 2023-04-04 18:13 UTC by JasonLamv-t

### Description

添加 `Array.fromAsync()` 方法的翻译

### Motivation

同上

### Additional details

🈚️

2023-04-05 14:15 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +**`Array.fromAsync()`** 静态方法可以从一个[异步可迭代对象](/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#异步迭代器和异步可迭代协议)、[可迭代对象](/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#可迭代协议)或[类数组对象](/zh-
```suggestion
**`Array.fromAsync()`** 静态方法可以由一个[异步可迭代对象](/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#异步迭代器和异步可迭代协议)、[可迭代对象](/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#可迭代协议)或[类数组对象](/zh-CN/docs/Web/JavaScript/Guide/Indexed_collections#使用类数组对象)创建一个新的、浅拷贝的 `Array` 实例。
```

2023-04-05 14:15 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +一个新的 {{jsxref("Promise")}}，其完成值是一个新的 {{jsxref("Array")}} 实例。
**承诺**被**兑现**

```suggestion
一个新的 {{jsxref("Promise")}}，其兑现值是一个新的 {{jsxref("Array")}} 实例。
```

2023-04-05 14:15 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +- [异步可迭代对象](/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#异步迭代器和异步可迭代协议) (如 {{domxref("ReadableStream")}} 和 {{jsxref("AsyncGenerator")}})；
少了半句

2023-04-05 14:15 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +- 如果使用非异步可迭代对象调用 `Array.fromAsync()`，则要添加到数组中的每个元素都会先进行 [await](/zh-CN/docs/Web/JavaScript/Reference/Operators/await) 处理。
感觉翻译成“await 处理”并不好，再考虑一下，看看有什么想法

2023-04-05 17:06 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +- 如果使用非异步可迭代对象调用 `Array.fromAsync()`，则要添加到数组中的每个元素都会先进行 [await](/zh-CN/docs/Web/JavaScript/Reference/Operators/await) 处理。
await 用于等待 promise 处理完成，原文档有大量的使用反引号的 code，可以直接翻译为中文，不保留 code 比较好（对于阅读以及有较好的术语的情况下），这个考虑一下？
@yin1999

2023-04-06 00:29 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +- 类数组的对象 (带有 `length` 属性和索引元素的对象)。
```suggestion
- [异步可迭代对象](/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#异步迭代器和异步可迭代协议) (如 {{domxref("ReadableStream")}} 和 {{jsxref("AsyncGenerator")}})；或者，如果对象不是异步可迭代的，
- [可迭代对象](/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#可迭代协议) (如 {{jsxref("Map")}} 和 {{jsxref("Set")}})；或者，如果对象不可迭代的，
- 类数组的对象 (带有 `length` 属性和索引元素的对象)。
```

2023-04-06 14:55 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +- 如果使用非异步可迭代对象调用 `Array.fromAsync()`，则要添加到数组中的每个元素都会先进行 [await](/zh-CN/docs/Web/JavaScript/Reference/Operators/await) 处理。
@yin1999 @yin1999 这里的 await 我希望保留，但是可能直接翻译为等待在中文阅读上更通顺一些，不过 await 直接翻译成等待感觉并不合适。暂时我先这么改

2023-04-08 13:50 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +- 如果使用非异步可迭代对象调用 `Array.fromAsync()`，则要添加到数组中的每个元素都会先进行 [await](/zh-CN/docs/Web/JavaScript/Reference/Operators/await) 处理。
文章很多地方都未使用 code 包裹 await，我建议是将其翻译成 -> 等待

2023-04-09 01:56 UTC, yin1999 requested changes

2023-04-09 01:56 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +- [异步可迭代对象](/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#异步迭代器和异步可迭代协议) (如 {{domxref("ReadableStream")}} 和 {{jsxref("AsyncGenerator")}})；或者，如果对象不是异步可迭代的，
```suggestion
- [异步可迭代对象](/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#异步迭代器和异步可迭代协议)（如 {{domxref("ReadableStream")}} 和 {{jsxref("AsyncGenerator")}}）；或者，如果对象不是异步可迭代的，
```

2023-04-09 01:56 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +- [可迭代对象](/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#可迭代协议) (如 {{jsxref("Map")}} 和 {{jsxref("Set")}})；或者，如果对象不可迭代的，
```suggestion
- [可迭代对象](/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#可迭代协议)（如 {{jsxref("Map")}} 和 {{jsxref("Set")}}）；或者，如果对象是不可迭代的，
```

2023-04-09 01:56 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +- 类数组的对象 (带有 `length` 属性和索引元素的对象)。
```suggestion
- 类数组的对象（带有 `length` 属性和索引元素的对象）。
```

2023-04-09 01:56 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +- `Array.fromAsync()` 返回一个 {{jsxref("Promise")}}，该 Promise 在解析为数组实例之前进行了处理。
```suggestion
- `Array.fromAsync()` 返回一个 {{jsxref("Promise")}}，会兑现数组实例。
```

2023-04-09 01:56 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +- 如果使用非异步可迭代对象调用 `Array.fromAsync()`，则要添加到数组中的每个元素（无论是否为 Promise）都会先 [await](/zh-CN/docs/Web/JavaScript/Reference/Operators/await) 其兑现。
我的想法与 @fwqaaq 的类似，翻译为等待更好点，请修改一下

2023-04-09 05:21 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +- 如果使用非异步可迭代对象调用 `Array.fromAsync()`，则要添加到数组中的每个元素（无论是否为 Promise）都会先 [await](/zh-CN/docs/Web/JavaScript/Reference/Operators/await) 其兑现。
```suggestion
- 如果使用非异步可迭代对象调用 `Array.fromAsync()`，则要添加到数组中的每个元素（无论是否为 Promise）都会先等待其兑现。
```

2023-04-09 05:28 UTC, Aexmuxomor approved these changes

2023-04-09 05:48 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +  - : 为数组中的每个元素执行的函数。如果提供了该函数，则每个要添加到数组中的值都会先通过该函数处理，`mapFn` 的返回值将代替该值被添加到数组中（在经过 [await](/zh-CN/docs/Web/JavaScript/Reference/Operators/await) 处理后）。该函数被调用时将传入以下参数：
这里，下面也还有好几处没有修改的，全文检查一下

2023-04-09 05:49 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +  - : 为数组中的每个元素执行的函数。如果提供了该函数，则每个要添加到数组中的值都会先通过该函数处理，`mapFn` 的返回值将代替该值被添加到数组中（在经过 [await](/zh-CN/docs/Web/JavaScript/Reference/Operators/await) 处理后）。该函数被调用时将传入以下参数：
稍后。

2023-04-09 05:52 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +  - : 为数组中的每个元素执行的函数。如果提供了该函数，则每个要添加到数组中的值都会先通过该函数处理，`mapFn` 的返回值将代替该值被添加到数组中（在经过 [await](/zh-CN/docs/Web/JavaScript/Reference/Operators/await) 处理后）。该函数被调用时将传入以下参数：
```suggestion
  - : 为数组中的每个元素执行的函数。如果提供了该函数，则每个要添加到数组中的值都会先通过该函数处理，`mapFn` 的返回值将代替该值被添加到数组中（在等待兑现后）。该函数被调用时将传入以下参数：
```

2023-04-09 05:54 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +      - : 数组中当前正在处理的元素。由于所有元素都会先被 [await](/zh-CN/docs/Web/JavaScript/Reference/Operators/await) 处理，因此该值永远不会是 [thenable](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise#thenables)。
```suggestion
      - : 数组中当前正在处理的元素。由于所有元素都会先等待其兑现，因此该值永远不会是 [thenable](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise#thenables)。
```

2023-04-09 05:55 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +- `Array.fromAsync()` 会依次 `await` 对象中产生的每个值。`Promise.all()` 会并行 `await` 所有值。
```suggestion
- `Array.fromAsync()` 会依次等待对象中产生的每个值兑现。`Promise.all()` 会并行等待所有值兑现。
```

2023-04-09 05:55 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +- 如果提供了 `mapFn`，则其输入和输出会在内部进行 `await` 处理。
```suggestion
- 如果提供了 `mapFn`，则其输入和输出会在内部等待兑现。
```

2023-04-09 05:58 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +- `Array.fromAsync()` 惰性迭代可迭代对象，并且不会获取下一个值，直到当前值被处理完成。`Promise.all()` 预先获取所有值并等待它们全部处理完成。
```suggestion
- `Array.fromAsync()` 惰性迭代可迭代对象，并且不会获取下一个值，直到当前值被兑现。`Promise.all()` 预先获取所有值并等待它们全部兑现。
```

2023-04-09 05:58 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +`Array.fromAsync()` 会依次 `await` 对象中产生的每个值。`Promise.all()` 会并行 `await` 所有值。
```suggestion
`Array.fromAsync()` 会依次等待对象中产生的每个值兑现。`Promise.all()` 会并行等待所有值兑现。
```

2023-04-09 06:00 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +如果需要关闭迭代器，则需要使用 {{jsxref("Statements/for...of", "for...of")}} 循环，并手动 `await` 每个值。
```suggestion
如果需要关闭迭代器，则需要使用 {{jsxref("Statements/for...of", "for...of")}} 循环，并手动等待每个值兑现。
```

2023-04-09 06:08 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/fromasync/index.md
> +  - : 为数组中的每个元素执行的函数。如果提供了该函数，则每个要添加到数组中的值都会先通过该函数处理，`mapFn` 的返回值将代替该值被添加到数组中（在等待兑现后）。该函数被调用时将传入以下参数：
原文是有链接的，别去了啊，下文有几处也是，检查一下（翻译成“等待”读者在遇到这个词的时候没有参考或不熟悉是很难猜对它具体指什么）

```suggestion
  - : 为数组中的每个元素执行的函数。如果提供了该函数，则每个要添加到数组中的值都会先通过该函数处理，`mapFn` 的返回值将代替该值被添加到数组中（在[等待](/zh-CN/docs/Web/JavaScript/Reference/Operators/await)兑现后）。该函数被调用时将传入以下参数：
```

https://github.com/mdn/content/blob/ee09695c6bb4339bf97f2f643dfde6dc54c50b1d/files/en-us/web/javascript/reference/global_objects/array/fromasync/index.md?plain=1#L27

2023-04-09 06:19 UTC, yin1999 commented
Why closing this :confused:

2023-04-09 09:33 UTC, yin1999 commented
I'm going to reopen this

2023-04-09 11:28 UTC, JasonLamv-t commented
Will re-translate next week after digging into promises

2023-04-09 11:30 UTC, JasonLamv-t commented
> Why closing this 😕

Temporarily closed due to personal and family matters.

2023-04-09 11:44 UTC, yin1999 commented
> > Why closing this confused
> 
> Temporarily closed due to personal and family matters.

Please convert to draft instead of closing, after the PR is ready to review, just click the `Ready for review` button

2023-04-13 03:11 UTC, yin1999 approved these changes

2023-04-13 03:13 UTC, merged

2023-04-13 07:28 UTC, JasonLamv-t commented
@yin1999 Thanks!