add missing link to planets-data.txt file
mdn/translated-content pull request #12564
Opened 2023-04-05 08:30 UTC by flora-le

Link was missing, add a link to download the file planets-data.txt

### Description

Link was missing for downloading the file planets-data.txt, add a link to download the file.

### Motivation

To access the link to download the file when clicking on the name

### Additional details

### Related issues and pull requests

2023-04-05 21:49 UTC, cw118 requested changes
Thank you again for this PR, I added one small suggestion :)

2023-04-05 21:49 UTC, cw118 commented on files/fr/learn/html/tables/structuring_planet_data/index.md
> +Les étapes suivantes décrivent ce que vous devez faire pour compléter l'exemple de tableau. Toutes les données dont vous avez besoin sont contenues dans le fichier [planets-data.txt](https://github.c
```suggestion
Les étapes suivantes décrivent ce que vous devez faire pour compléter l'exemple de tableau. Toutes les données dont vous avez besoin sont contenues dans le fichier [`planets-data.txt`](https://github.com/mdn/learning-area/blob/main/html/tables/assessment-start/planets-data.txt). Si vous avez du mal à visualiser les données, regardez l'exemple donné dans le lien ci-dessus, ou essayez de dessiner un diagramme.
```

(keep the `code` formatting)

2023-04-17 21:01 UTC, cw118 commented
@flora-le Please don't hesitate if help is needed on this PR :)

2023-04-18 12:52 UTC, flora-le commented
Hello,
thanks! it's my first time doign this kind of thing. Does clicking on the button "update branch" is enough ? Thanks :)

2023-04-18 13:54 UTC, SphinxKnight approved these changes
Merci @flora-le :)

2023-04-18 13:54 UTC, merged