zh-cn(fix-partof): svg-marker
mdn/translated-content pull request #12600
Opened 2023-04-07 03:25 UTC by fwqaaq

### Description

### Motivation

Part of #12578

### Additional details

### Related issues and pull requests

2023-04-07 05:43 UTC, JasonLamv-t requested changes
主要是链接和格式问题

2023-04-07 05:43 UTC, JasonLamv-t commented on files/zh-cn/web/svg/element/marker/index.md
> +  - : 该属性定义了 marker 视口的高度。*值的类型*：**[\<length>](/en-US/docs/Web/SVG/Content_type#length)**；*默认值*：`3`；*动画*：**有**
```suggestion
  - : 该属性定义了 marker 视口的高度。*值的类型*：**[\<length>](/zh-CN/docs/Web/SVG/Content_type#长度)**；*默认值*：`3`；*动画*：**有**
```

2023-04-07 05:43 UTC, JasonLamv-t commented on files/zh-cn/web/svg/element/marker/index.md
> +  - :该属性定义了 marker 视图的宽度。*值的类型*：**[\<length>](/en-US/docs/Web/SVG/Content_type#length)** ；*默认值*：`3`；*动画*：**有**
```suggestion
  - : 该属性定义了 marker 视图的宽度。*值的类型*：**[\<length>](/zh-CN/docs/Web/SVG/Content_type#长度)** ；*默认值*：`3`；*动画*：**有**
```

2023-04-07 05:43 UTC, JasonLamv-t commented on files/zh-cn/web/svg/element/marker/index.md
> +  - :该属性定义了 marker 相对于它所附着到形状的方向。*值的类型*：`auto`|`auto-start-reverse`|**[\<angle>](/en-US/docs/Web/SVG/Content_type#angle)** ；*默认值*：`0`；*动画*：**有**
```suggestion
  - : 该属性定义了 marker 相对于它所附着到形状的方向。*值的类型*：`auto`|`auto-start-reverse`|**[\<angle>](/zh-CN/docs/Web/SVG/Content_type#角度)** ；*默认值*：`0`；*动画*：**有**
```

2023-04-07 05:43 UTC, JasonLamv-t commented on files/zh-cn/web/svg/element/marker/index.md
> +  - :该属性为 `markerWidth`、`markerHeight` 和 `<marker>` 的内容定义了坐标系。*值的类型*：`userSpaceOnUse`|`strokeWidth` ；*默认值*：`strokeWidth`；*动画*：**有**
```suggestion
  - : 该属性为 `markerWidth`、`markerHeight` 和 `<marker>` 的内容定义了坐标系。*值的类型*：`userSpaceOnUse`|`strokeWidth` ；*默认值*：`strokeWidth`；*动画*：**有**
```

2023-04-07 05:43 UTC, JasonLamv-t commented on files/zh-cn/web/svg/element/marker/index.md
> +  - :该属性定义了 marker 视图的宽度。*值的类型*：**[\<length>](/en-US/docs/Web/SVG/Content_type#length)** ；*默认值*：`3`；*动画*：**有**
```suggestion
  - : 该属性定义了 marker 视图的宽度。*值的类型*：**[\<length>](/en-US/docs/Web/SVG/Content_type#length)** ；*默认值*：`3`；*动画*：**有**
```

2023-04-07 05:43 UTC, JasonLamv-t commented on files/zh-cn/web/svg/element/marker/index.md
> +    *值的类型*：**[\<list-of-numbers>](/en-US/docs/Web/SVG/Content_type#list-of-ts)** ；*默认值*：none；*动画*：**有**
ditto，另外
```markdown
`none`| `xMinYMin`
```
中的 `|` 是否需要考虑换成 `｜` 呢？

2023-04-07 05:43 UTC, JasonLamv-t commented on files/zh-cn/web/svg/element/marker/index.md
> +- [核心属性](/en-US/docs/Web/SVG/Attribute/Core)
ditto

2023-04-07 05:43 UTC, JasonLamv-t commented on files/zh-cn/web/svg/element/marker/index.md
> +- [样式属性](/en-US/docs/Web/SVG/Attribute/Styling)
ditto

2023-04-07 05:43 UTC, JasonLamv-t commented on files/zh-cn/web/svg/element/marker/index.md
> +- [条件处理属性](/en-US/docs/Web/SVG/Attribute/Conditional_Processing)
ditto

2023-04-07 05:43 UTC, JasonLamv-t commented on files/zh-cn/web/svg/element/marker/index.md
> +- [Presentation Attributes](/en-US/docs/Web/SVG/Attribute/Presentation)
ditto

2023-04-07 05:55 UTC, fwqaaq commented on files/zh-cn/web/svg/element/marker/index.md
> +    *值的类型*：**[\<list-of-numbers>](/en-US/docs/Web/SVG/Content_type#list-of-ts)** ；*默认值*：none；*动画*：**有**
类似于 [CSS 形式语法](https://developer.mozilla.org/zh-CN/docs/Web/CSS/Value_definition_syntax#%E2%80%9C%E4%BA%92%E6%96%A5%E2%80%9D%E7%BB%84%E5%90%88%E7%AC%A6%EF%BC%9A)，我就保留了

2023-04-07 06:00 UTC, JasonLamv-t commented on files/zh-cn/web/svg/element/marker/index.md
> +    *值的类型*：**[\<list-of-numbers>](/en-US/docs/Web/SVG/Content_type#list-of-ts)** ；*默认值*：none；*动画*：**有**
那[这一行](https://github.com/mdn/translated-content/pull/12600/files#diff-fa577a0f91fb03e1ac4203d4163477ddb8bfcd6c4e80e66d0e0982c0ee82777cR175)中，两个括号内 `|` 左右的空格表现不一致，不过现在跟原文是一致的，也许，给原文提个 PR？

2023-04-07 06:02 UTC, fwqaaq commented on files/zh-cn/web/svg/element/marker/index.md
> +    *值的类型*：**[\<list-of-numbers>](/en-US/docs/Web/SVG/Content_type#list-of-ts)** ；*默认值*：none；*动画*：**有**
好，你可以提一下，🤔

2023-04-07 07:35 UTC, yin1999 requested changes

2023-04-07 07:35 UTC, yin1999 commented on files/zh-cn/web/svg/element/marker/index.md
> +  - : 该属性定义了 marker 视口的高度。*值的类型*：**[\<length>](/zh-CN/docs/Web/SVG/Content_type#长度)**；*默认值*：`3`；*动画*：**有**
这里翻译为“动画：有”总觉得怪怪的

2023-04-07 07:35 UTC, yin1999 commented on files/zh-cn/web/svg/element/marker/index.md
> +  - : 该属性定义了 svg 片段在嵌入具有不同宽高比例的容器中应该如何变形。*值的类型*：(`none`| `xMinYMin`| `xMidYMin`| `xMaxYMin`| `xMinYMid`| `xMidYMid`| `xMaxYMid`| `xMinYMax`| `xMidYMax`| `xMaxYMax`) (`meet`|`slice`)? ；*默认值*：`xMidYMid
括号

2023-04-07 07:35 UTC, yin1999 commented on files/zh-cn/web/svg/element/marker/index.md
> +  - : 最重要地：{{SVGAttr('id')}}、{{SVGAttr('tabindex')}}
中文好像没有类似于英文文档中的那种使用习惯，改成形容词吧（表名词）

```suggestion
  - : 最重要的：{{SVGAttr('id')}}、{{SVGAttr('tabindex')}}
```

2023-04-07 10:47 UTC, fwqaaq commented on files/zh-cn/web/svg/element/marker/index.md
> +  - : 该属性定义了 marker 视口的高度。*值的类型*：**[\<length>](/zh-CN/docs/Web/SVG/Content_type#长度)**；*默认值*：`3`；*动画*：**有**
可以通过SVG动画系统进行动画处理，那翻译成可以？

2023-04-07 10:49 UTC, fwqaaq commented on files/zh-cn/web/svg/element/marker/index.md
> +  - : 该属性定义了 svg 片段在嵌入具有不同宽高比例的容器中应该如何变形。*值的类型*：(`none`| `xMinYMin`| `xMidYMin`| `xMaxYMin`| `xMinYMid`| `xMidYMid`| `xMaxYMid`| `xMinYMax`| `xMidYMax`| `xMaxYMax`) (`meet`|`slice`)? ；*默认值*：`xMidYMid
类似 CSS 形式语法，特意保留，而且还有问号，要一起改？

2023-04-08 01:54 UTC, yin1999 commented on files/zh-cn/web/svg/element/marker/index.md
> +  - : 该属性定义了 svg 片段在嵌入具有不同宽高比例的容器中应该如何变形。*值的类型*：(`none`| `xMinYMin`| `xMidYMin`| `xMaxYMin`| `xMinYMid`| `xMidYMid`| `xMaxYMid`| `xMinYMax`| `xMidYMax`| `xMaxYMax`) (`meet`|`slice`)? ；*默认值*：`xMidYMid
看了一下，这个暂时不修改了吧

2023-04-08 01:56 UTC, yin1999 commented on files/zh-cn/web/svg/element/marker/index.md
> +## 使用注意
关于这个词，我也想统一一下翻译，我见过的、常用的有：使用备注、使用说明、使用注意 这三种

2023-04-08 01:56 UTC, yin1999 commented on files/zh-cn/web/svg/element/marker/index.md
> +## 使用注意
关于这个词，我也想统一一下翻译，我见过的、常用的有：使用备注、使用说明、使用注意 这三种

2023-04-08 03:26 UTC, fwqaaq commented on files/zh-cn/web/svg/element/marker/index.md
> +  - : 最重要地：{{SVGAttr('clip-path')}}、{{SVGAttr('clip-rule')}}、{{SVGAttr('color')}}、{{SVGAttr('color-interpolation')}}、{{SVGAttr('color-rendering')}}、{{SVGAttr('cursor')}}、{{SVGAttr('display')}}、{{SVGA
```suggestion
- [条件处理属性](/zh-CN/docs/Web/SVG/Attribute/Conditional_Processing)
  - : 最重要的：{{SVGAttr('requiredExtensions')}}、{{SVGAttr('systemLanguage')}}
- [表现属性](/zh-CN/docs/Web/SVG/Attribute/Presentation)
  - : 最重要的：{{SVGAttr('clip-path')}}、{{SVGAttr('clip-rule')}}、{{SVGAttr('color')}}、{{SVGAttr('color-interpolation')}}、{{SVGAttr('color-rendering')}}、{{SVGAttr('cursor')}}、{{SVGAttr('display')}}、{{SVGAttr('fill')}}、{{SVGAttr('fill-opacity')}}、{{SVGAttr('fill-rule')}}、{{SVGAttr('filter')}}、{{SVGAttr('mask')}}、{{SVGAttr('opacity')}}、{{SVGAttr('pointer-events')}}、{{SVGAttr('shape-rendering')}}、{{SVGAttr('stroke')}}、{{SVGAttr('stroke-dasharray')}}、{{SVGAttr('stroke-dashoffset')}}、{{SVGAttr('stroke-linecap')}}、{{SVGAttr('stroke-linejoin')}}、{{SVGAttr('stroke-miterlimit')}}、{{SVGAttr('stroke-opacity')}}、{{SVGAttr('stroke-width')}}、{{SVGAttr("transform")}}、{{SVGAttr('vector-effect')}}、{{SVGAttr('visibility')}}
```

2023-04-08 03:27 UTC, fwqaaq commented on files/zh-cn/web/svg/element/marker/index.md
> +## 使用注意
备注和注意，都 OK，如果想和之前 code 中的统一，选备注

2023-04-10 12:39 UTC, yarusome commented on files/zh-cn/web/svg/element/marker/index.md
> +  - : 该属性定义了 marker 视口的高度。*值的类型*：**[\<length>](/zh-CN/docs/Web/SVG/Content_type#长度)**；*默认值*：`3`；*动画*：**有**
animatable 这个词确实是（曾经的）CSS 和（现在的）SVG 共有的坑。也许可以译为“动画性：有/无”，即把 animatable 名词化。

2023-04-10 13:48 UTC, yin1999 commented on files/zh-cn/web/svg/element/marker/index.md
> +## 使用注意
`使用说明` 用得更多，也相对符合语义，就用使用说明吧

2023-04-10 14:08 UTC, fwqaaq commented on files/zh-cn/web/svg/element/marker/index.md
> +## 使用注意
```suggestion
## 使用说明
```

2023-04-10 23:16 UTC, yin1999 approved these changes

2023-04-10 23:20 UTC, merged

2023-04-10 23:25 UTC, yin1999 commented
要以标准的格式写 pr 标题的话，可以参考 https://github.com/angular/angular/blob/main/CONTRIBUTING.md 中的 message of commit。这个是使用较为广泛的，我们很少会使用类似于 zh-cn(fix-partof)这样的格式，如果是错误修正，一般会写 fix(zh-cn): 后接一段修复错误的具体说明