fix(ko): error on EmbedLiveSample of adding z-index
mdn/translated-content pull request #12631
Opened 2023-04-08 13:42 UTC by nnnnoel

### Description

### Motivation

### Additional details

### Related issues and pull requests
Relates to #2848

2023-04-09 14:51 UTC, hochan222 requested changes
@nnnnoel 님 안녕하세요.

리뷰 사항 아래에 남겨두었습니다.

기여해주셔서 감사합니다. 좋은 하루 보내세요 :)

2023-04-09 14:51 UTC, hochan222 commented on files/ko/web/css/css_positioning/understanding_z_index/adding_z-index/index.md
> +### 예시 코드
```suggestion
### 예제
```

(1) [glossary guide](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md)에 따라 example 은 "예제"로 번역 부탁드립니다.
(2) [content repo](https://github.com/mdn/content/blob/e8383b94615de06243607843361202ddba8451bf/files/en-us/web/css/css_positioning/understanding_z_index/adding_z-index/index.md?plain=1#L4)에 제목이 Example 이여서, Example로 수정 부탁드립니다. :)

2023-04-09 14:51 UTC, hochan222 commented on files/ko/web/css/css_positioning/understanding_z_index/adding_z-index/index.md
> +{{EmbedLiveSample("예시_코드", 600, 400)}}
```suggestion
{{EmbedLiveSample("예제", 600, 400)}}
```

2023-04-10 13:29 UTC, nnnnoel commented
@hochan222 [fix: title](https://github.com/mdn/translated-content/pull/12631/commits/98c027e424b3cbef209c1bbcbbc372b6d0c60dce) 리뷰해주신 내용 수정되었습니다~

2023-04-10 13:31 UTC, hochan222 approved these changes
빠른 반영 감사합니다! 좋은 하루 보내세요 :)

2023-04-10 13:31 UTC, merged