[삼항 연산자] 업데이트된 내용 반영 및 번역 수정
mdn/translated-content pull request #1263
Opened 2021-06-21 05:54 UTC by sunup1992

EN/US 내용과 동기화하였습니다.

2021-07-04 10:08 UTC, pje1740 requested changes
작업 진행해주셔서 감사합니다! 몇가지 코멘트 남겼는데 확인 부탁드리겠습니다.
혹시나 코멘트 관련하여 이견이 있거나 의문이 있으시면 언제든 편하게 남겨주세요 :)
리뷰가 많이 늦어진 점, 양해 부탁 드립니다! (_ _)

2021-07-04 10:08 UTC, pje1740 commented on files/ko/web/javascript/reference/operators/conditional_operator/index.html
> +// Equivalent to:
이 주석은 한글로 변경해도 무방할 것 같아 제안 드립니다!
```suggestion
// 위의 코드는 아래의 코드와 동일합니다.
```

2021-07-04 10:08 UTC, pje1740 commented on files/ko/web/javascript/reference/operators/conditional_operator/index.html
>  <h2 id="명세">명세</h2>
아이디는 영어로 표기 부탁드리겠습니다.
```suggestion
<h2 id="Specifications">명세</h2>
```

2021-07-04 10:08 UTC, pje1740 commented on files/ko/web/javascript/reference/operators/conditional_operator/index.html
>  <h2 id="브라우저_호환성">브라우저 호환성</h2>
```suggestion
<h2 id="Browser_compatibility">브라우저 호환성</h2>
```

2021-07-04 10:08 UTC, pje1740 commented on files/ko/web/javascript/reference/operators/conditional_operator/index.html
>  <h2 id="같이_보기">같이 보기</h2>
```suggestion
<h2 id="See_also">같이 보기</h2>
```

2021-07-31 13:53 UTC, hochan222 approved these changes

2021-07-31 13:53 UTC, hochan222 commented on files/ko/web/javascript/reference/operators/conditional_operator/index.html
> +<p><strong>조건부 삼항 연산자</strong>는 JavaScript에서 세 개의 피연산자를 취할 수 있는 유일한 연산자입니다. 맨 앞에 조건문 들어가고. 그 뒤로 물음표(<code>?</code>)와 조건이 참이라면 실행할 식이 물음표 뒤로 들어갑니다. 바로 뒤로 콜론(<code>:</code>)이 들어가며 조건이 거짓이라면 실행할 식이 마지막에
```suggestion
<p><strong>조건부 삼항 연산자</strong>는 JavaScript에서 세 개의 피연산자를 취할 수 있는 유일한 연산자입니다. 맨 앞에 조건문 들어가고. 그 뒤로 물음표(<code>?</code>)와 조건이 {{Glossary("truthy")}}이라면 실행할 식이 물음표 뒤로 들어갑니다. 바로 뒤로 콜론(<code>:</code>)이 들어가며 조건이 {{Glossary("falsy")}}이라면 실행할 식이 마지막에 들어갑니다. 보통 <a href="/ko/docs/Web/JavaScript/Reference/Statements/if...else"><code>if</code></a> 명령문의 단축 형태로 쓰입니다.</p>
```

2021-08-03 06:09 UTC, merged