Quelques macros manquantes sont ajoutées
mdn/translated-content pull request #12643
Opened 2023-04-09 13:25 UTC by Mehrm0

### Description
J'ai ajouté quelques titres et macros aux éléments de HTML.

### Motivation
[Ici](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/HTML_element_page_template) est mentionné que le titre des exemples doit être au pluriel, même s'il y a seulement un exemple:
 
> Note that we use the plural "Examples" even if the page only contains one example.

De plus j'ai ajouté les macros *live sample* aux éléments qui ne l'avaient pas.  

### Additional details

Les exemples d l'élément \<audio\> ne contiennent pas de fichiers sonores et rien ne se produit quand on appuie sur les buttons. Peut-être que l'ajout des fichiers peut améliorer la page.

### Related issues and pull requests

2023-04-09 14:47 UTC, cw118 requested changes
J'ai laissé quelques remarques, merci déjà @Mehrm0 !

2023-04-09 14:47 UTC, cw118 commented on files/fr/web/html/element/abbr/index.md
> +{{EmbedliveSample('')}}
```suggestion
##### Résultat

{{EmbedLiveSample('')}}
```

Je vois qu'il n'y a pas d'exemple live ici sur [l'homologue anglaise](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr#accessibility_concerns), aimeriez-vous peut-être créer une PR sur mdn/content pour l'ajouter ? Sinon je pourrais m'en occuper :)

2023-04-09 14:47 UTC, cw118 commented on files/fr/web/html/element/acronym/index.md
> +{{EmbedLiveSample('')}}
(À noter que la page anglaise n'a pas cet exemple non plus)

2023-04-09 14:47 UTC, cw118 commented on files/fr/web/html/element/audio/index.md
> +{{EmbedLiveSample('')}}
Même commentaire pour tous les exemples ici que sur la page `<abbr>` (càd la page anglaise `<audio>` n'a aucune des macros EmbedLiveSample insérées dans cette PR)

2023-04-09 18:11 UTC, Mehrm0 commented
> J'ai laissé quelques remarques, merci déjà @Mehrm0 !

J'ai proposé les changements(sur mdn-content), mais malheureusement  d'habitude ils répondent assez tard. De plus J'ai décidé d'annuler les changements de l'élément \<audio\>. Je m'en occupe plus tard.

2023-04-10 18:29 UTC, cw118 approved these changes
Merci encore pour cette contribution @Mehrm0 ! Fusionnons tout ça :)

2023-04-10 18:29 UTC, merged