zh-cn: sync translation content
mdn/translated-content pull request #12649
Opened 2023-04-09 14:40 UTC by daiwanxing

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-04-09 14:46 UTC, yin1999 commented
`zh-cn: sync translation content` 这个是 MDN 机器人从 mdn/content 仓库同步文档移动使用的标题，请注意合理填写 PR 的标题

2023-04-09 14:55 UTC, fwqaaq commented on files/zh-cn/web/css/scrollbar-width/index.md
> +scrollbar-width: revert-layer;
注意段落的标题

2023-04-10 01:11 UTC, yin1999 commented on files/zh-cn/web/css/scrollbar-width/index.md
>  {{EmbedInteractiveExample("pages/css/scrollbar-width.html")}}
```suggestion
```

2023-04-10 01:11 UTC, yin1999 commented on files/zh-cn/web/css/scrollbar-width/index.md
>  ## Syntax
```suggestion
## 语法
```

2023-04-10 14:22 UTC, yin1999 requested changes

2023-04-10 14:22 UTC, yin1999 commented on files/zh-cn/web/css/scrollbar-width/index.md
> +- [MDN 理解 WCAG，指南 2.1 解释](/en-US/docs/Web/Accessibility/Understanding_WCAG/Operable#guideline_2.1_—_keyboard_accessible_make_all_functionality_available_from_a_keyboard)
链接要本地化 https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md#%E7%AB%99%E5%86%85%E9%93%BE%E6%8E%A5%E7%BF%BB%E8%AF%91

2023-04-10 14:22 UTC, yin1999 commented on files/zh-cn/web/css/scrollbar-width/index.md
注意一下下面的表格，请改成 HTML table，markdown 表格无法表示没有表头的表格

2023-04-11 01:57 UTC, daiwanxing commented on files/zh-cn/web/css/scrollbar-width/index.md
> +- [MDN 理解 WCAG，指南 2.1 解释](/en-US/docs/Web/Accessibility/Understanding_WCAG/Operable#guideline_2.1_—_keyboard_accessible_make_all_functionality_available_from_a_keyboard)
原文链接没有本地化内容

2023-04-11 01:58 UTC, yin1999 commented on files/zh-cn/web/css/scrollbar-width/index.md
> +- [MDN 理解 WCAG，指南 2.1 解释](/en-US/docs/Web/Accessibility/Understanding_WCAG/Operable#guideline_2.1_—_keyboard_accessible_make_all_functionality_available_from_a_keyboard)
请仔细阅读翻译指南，关于这些内容我们已经有明确的说明。

![image](https://user-images.githubusercontent.com/15844309/231035878-1e05b8ea-1afe-499b-a0a2-d84784cc5533.png)

2023-04-11 02:03 UTC, yin1999 commented on files/zh-cn/web/css/scrollbar-width/index.md
> +- [MDN 理解 WCAG，指南 2.1 解释](/en-US/docs/Web/Accessibility/Understanding_WCAG/Operable#guideline_2.1_—_keyboard_accessible_make_all_functionality_available_from_a_keyboard)
如果是指向特定的章节的，可以选择保留原来的hash，或者对hash部分进行翻译

2023-04-11 02:29 UTC, daiwanxing commented on files/zh-cn/web/css/scrollbar-width/index.md
> +- [MDN 理解 WCAG，指南 2.1 解释](/en-US/docs/Web/Accessibility/Understanding_WCAG/Operable#guideline_2.1_—_keyboard_accessible_make_all_functionality_available_from_a_keyboard)
got

2023-04-11 05:27 UTC, yin1999 requested changes

2023-04-11 05:28 UTC, yin1999 approved these changes

2023-04-11 05:32 UTC, merged