[ko] JavaScript: Map 일부 메서드 최신 동기화
mdn/translated-content pull request #12670
Opened 2023-04-10 13:10 UTC by wisedog

JavaScript Map의 일부 메서드 최신 동기화

- Map.prototype.clear()
- Map.prototype.delete()
- Map.prototype.entries()
- Map.prototype.keys()
- Map.prototype.values()
- Map.prototype.size

2023-05-06 01:03 UTC, yechoi42 requested changes
안녕하세요 기여자님! 리뷰가 늦어져서 죄송합니다. 소스커밋으로 올려주셨던 ab97df6이 더이상 문서에서 찾아볼 수 없어 수정이 필요한 부분이 있습니다. 확인 부탁드리겠습니다. 저를 다시 멘션해주세요.

2023-05-06 01:03 UTC, yechoi42 commented on files/ko/web/javascript/reference/global_objects/map/keys/index.md
> +**`keys()`** 메서드는 배열에서 각 인덱스의 키를 포함하는 새로운 _[배열 반복자](/ko/docs/Web/JavaScript/Reference/Global_Objects/Iterator)_ 객체를 반환합니다.
```suggestion
**`keys()`** 메서드는 배열에서 각 인덱스의 키를 포함하는 새로운 [반복자](/ko/docs/Web/JavaScript/Reference/Global_Objects/Iterator) 객체를 반환합니다.
```
번역 가이드에 따라 기울임 꼴은 사용하지 않기로 하였고, 원문을 보면 'iterator'라고만 칭하고 있으므로 반복자라고만 하는 것이 좋을 것 같습니다.

2023-05-06 01:03 UTC, yechoi42 commented on files/ko/web/javascript/reference/global_objects/map/keys/index.md
> +  sourceCommit: ab97df6ce8865569507bcfc884206a1ed297a690
여기도 해당 소스 커밋이 없는데 확인 부탁드립니다.

2023-05-06 01:03 UTC, yechoi42 commented on files/ko/web/javascript/reference/global_objects/map/values/index.md
> +  sourceCommit: ab97df6ce8865569507bcfc884206a1ed297a690
해당 소스 커밋이 없습니다!

2023-05-06 01:03 UTC, yechoi42 commented on files/ko/web/javascript/reference/global_objects/map/values/index.md
> +**`values()`** 메서드는 배열의 각 아이템의 값을 순회하는 새로운 [배열 반복자](/ko/docs/Web/JavaScript/Reference/Global_Objects/Iterator) 객체를 반환합니다.
```suggestion
**`values()`** 메서드는 배열의 각 아이템의 값을 순회하는 새로운 [반복자](/ko/docs/Web/JavaScript/Reference/Global_Objects/Iterator) 객체를 반환합니다.
```

2023-05-06 01:03 UTC, yechoi42 commented on files/ko/web/javascript/reference/global_objects/map/values/index.md
> +새로운 [순회 가능한 반복자 객체](/ko/docs/Web/JavaScript/Reference/Global_Objects/Iterator).
이것도 기존 번역이 더 정확합니다.

2023-05-06 07:22 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/map/entries/index.md
> +  sourceCommit: ab97df6ce8865569507bcfc884206a1ed297a690
https://github.com/mdn/content/commit/2eb202adbe3d83292500ed46344d63fbbae410b5

이겁니다. 

그 사이에 커밋이 2개 들어와서 최신것이 안보인것 같아요.

2023-05-06 07:23 UTC, wisedog commented
@yechoi42 혹시 contents pull 을 해보신 후 다시 리뷰 주실 수 있으실까요?

2023-05-06 07:35 UTC, yechoi42 reviewed
@wisedog 님 제가 잘못된 저장소를 확인했나봅니다 :( 잘못된 conversation은 닫아두고, map iterator 해석에 대해서만 코멘트 남겨두었으니, 확인 부탁드립니다!

2023-05-14 04:48 UTC, yechoi42 approved these changes

2023-05-14 04:48 UTC, yechoi42 approved these changes

2023-05-14 04:48 UTC, merged