Math.max en-us 동기화
mdn/translated-content pull request #1268
Opened 2021-06-21 06:08 UTC by Dilrong

Math.max en-us 동기화 작업을 진행하였습니다.

2021-06-21 16:09 UTC, yujo11 requested changes
안녕하세요 Dilrong님! 

몇몇 부분 수정이 필요해보여 변경 요청 드립니다!

기여해주셔서 감사합니다!

2021-06-21 16:09 UTC, yujo11 commented on files/ko/web/javascript/reference/global_objects/math/max/index.html
> +  - Largest Value
중복되는 태그들은 지워주시면 좋을거 같습니다!

2021-06-21 22:02 UTC, Dilrong commented on files/ko/web/javascript/reference/global_objects/math/max/index.html
> +<p>그러나, 두 스프레드 (<code>...</code>)와 <code>적용</code> 모두 실패하거나 배열에 요소가 너무 많은 경우 잘못된 결과를 반환합니다.
apply를 명령어 코드로 표현되는군요!

2021-06-21 22:05 UTC, Dilrong commented on files/ko/web/javascript/reference/global_objects/math/max/index.html
> +<p>새로운<a href="/ko/docs/Web/JavaScript/Reference/Operators/Spread_syntax">확산
확산을 스프레드 라는 고유명사 느낌이 더 이해하기 좋겠네요.

2021-06-21 22:05 UTC, Dilrong commented on files/ko/web/javascript/reference/global_objects/math/max/index.html
> +    href="/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply#using_apply_and_built-in_functions">사용 참조보다 자세한 내용을 보려면 기능 적용</a> 및 기본 제공 감소 솔루션에는 문제가 없습니다.
감사합니다! 더 자연스럽고 좋네요!

2021-06-21 22:06 UTC, Dilrong commented on files/ko/web/javascript/reference/global_objects/math/max/index.html
> +  - Largest Value
앗...미처 인지하지 못했습니다.
알려주셔서 감사합니다!

2021-06-21 22:10 UTC, Dilrong commented
수정사항 반영했습니다.
피드백 주셔서 감사합니다!

2021-06-22 00:42 UTC, yujo11 approved these changes
고생하셨습니다!! 👍👍👍

2021-06-22 01:15 UTC, merged

2021-06-22 03:26 UTC, Dilrong commented
리뷰 감사드리며 수고하셨습니다!