zh-cn: sync with en-US ver for css property `text-decoration`
mdn/translated-content pull request #12728
Opened 2023-04-13 15:22 UTC by daiwanxing

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-04-14 01:28 UTC, jasonren0403 commented on files/zh-cn/web/css/text-decoration/index.md
> +**`text-decoration`** [缩写](/zh-CN/docs/Web/CSS/Shorthand_properties) [CSS](/zh-CN/docs/Web/CSS) 属性设置文本上的装饰性线条的外观。它是 {{cssxref("text-decoration-line")}}、{{cssxref("text-decoration-line")}}、{{cssxref("
参考[这页](https://developer.mozilla.org/zh-CN/docs/Web/CSS/Shorthand_properties)，还是把 `shorthand` 译为“简写属性”？
```suggestion
**`text-decoration`** [简写](/zh-CN/docs/Web/CSS/Shorthand_properties) [CSS](/zh-CN/docs/Web/CSS) 属性设置文本上的装饰性线条的外观。它是 {{cssxref("text-decoration-line")}}、{{cssxref("text-decoration-line")}}、{{cssxref("text-decoration-style")}} 和较新的 {{cssxref("text-decoration-thickness")}} 属性的缩写。
```

2023-04-14 05:50 UTC, daiwanxing commented on files/zh-cn/web/css/text-decoration/index.md
> +**`text-decoration`** [缩写](/zh-CN/docs/Web/CSS/Shorthand_properties) [CSS](/zh-CN/docs/Web/CSS) 属性设置文本上的装饰性线条的外观。它是 {{cssxref("text-decoration-line")}}、{{cssxref("text-decoration-line")}}、{{cssxref("
nice

2023-04-15 23:47 UTC, yin1999 requested changes

2023-04-15 23:47 UTC, yin1999 commented on files/zh-cn/web/css/text-decoration/index.md
> +文本装饰会覆盖子孙文本元素。这意味着如果一个元素指定了文本装饰，那么子元素无法去除这个装饰。例如，在标记 `<p>This text has <em>some emphasized words</em> in it.</p>` 中，样式规则 `p { text-decoration: underline; }` 会导致整个段落被下划线划掉。样式规则 `em { text-decoration:
```suggestion
文本装饰会覆盖子孙文本元素。这意味着如果一个元素指定了文本装饰，那么子元素无法去除这个装饰。例如，在标记 `<p>This text has <em>some emphasized words</em> in it.</p>` 中，样式规则 `p { text-decoration: underline; }` 会导致整个段落被下划线划掉。样式规则 `em { text-decoration: none; }` 不会有任何变化；整个段落仍然会被下划线划掉。但是，规则 `em { text-decoration: overline; }` 会导致“some emphasized words”上出现第二个装饰。
```

2023-04-15 23:47 UTC, yin1999 commented on files/zh-cn/web/css/text-decoration/index.md
> +<p class="blink">此文本可能会为你闪烁，具体取决于您使用的浏览器。</p>
使用“你”

```suggestion
<p class="blink">此文本可能会为你闪烁，具体取决于你使用的浏览器。</p>
```

2023-04-15 23:47 UTC, yin1999 commented on files/zh-cn/web/css/text-decoration/index.md
> +- 各个文本装饰属性分别是 {{cssxref("text-decoration-line")}}、{{cssxref("text-decoration-color")}}、{{cssxref("text-decoration-style")}} 和 {{cssxref("text-decoration-thickness")}}。
这里就意译吧，意指这个简写属性所囊括的单独的文本装饰属性

```suggestion
- 包括文本装饰属性分别是 {{cssxref("text-decoration-line")}}、{{cssxref("text-decoration-color")}}、{{cssxref("text-decoration-style")}} 和 {{cssxref("text-decoration-thickness")}}。
```

2023-04-15 23:47 UTC, yin1999 commented on files/zh-cn/web/css/text-decoration/index.md
> +- {{cssxref("text-decoration-skip-ink")}}、{{cssxref("text-underline-offset")}} 和 {{cssxref("text-underline-position")}} 属性也会影响文本装饰，但不包括在缩写中。
```suggestion
- {{cssxref("text-decoration-skip-ink")}}、{{cssxref("text-underline-offset")}} 和 {{cssxref("text-underline-position")}} 属性也会影响文本装饰，但不包括在该简写属性中。
```

2023-04-16 03:32 UTC, yin1999 approved these changes

2023-04-16 04:24 UTC, merged