zh-cn: sync with en-US version for `:empty` pseudo class
mdn/translated-content pull request #12775
Opened 2023-04-16 08:44 UTC by daiwanxing

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-04-17 08:08 UTC, yin1999 requested changes

2023-04-17 08:08 UTC, yin1999 commented on files/zh-cn/web/css/_colon_empty/index.md
> +提供交互控件的可访问名称的文本可以使用[一些属性的组合](https://gomakethings.com/hidden-content-for-better-a11y/#hiding-the-link)进行隐藏，这些属性可以将其在视觉上从屏幕上移除，但可以被辅助技术解析。这通常用于仅依靠图标来传达目的的按钮。
idto

2023-04-17 08:08 UTC, yin1999 commented on files/zh-cn/web/css/_colon_empty/index.md
> +- [什么是可访问的名称？ | The Paciello Group](https://www.tpgi.com/what-is-an-accessible-name/)
idto

2023-04-17 08:08 UTC, yin1999 commented on files/zh-cn/web/css/_colon_empty/index.md
> +- [MDN 理解 WCAG，指南 2.4 解释](/en-US/docs/Web/Accessibility/Understanding_WCAG/Operable#guideline_2.4_%e2%80%94_navigable_provide_ways_to_help_users_navigate_find_content_and_determine_where_they_are)
zh-CN

2023-04-17 08:08 UTC, yin1999 commented on files/zh-cn/web/css/_colon_empty/index.md
> +- {{CSSxRef(":-moz-only-whitespace")}} {{Non-standard_Inline}} – The {{glossary("Vendor_Prefix", "prefixed")}} 在[选择器 Level 4](https://drafts.csswg.org/selectors-4/#the-empty-pseudo) 中更改的前缀实现。
中英文混在一起 `The {{glossary("Vendor_Prefix", "prefixed")}}`

2023-04-18 01:20 UTC, daiwanxing commented on files/zh-cn/web/css/_colon_empty/index.md
> +**`:empty`** [CSS](/zh-CN/docs/Web/CSS) [伪类](/zh-CN/CSS/Pseudo-classes)用于选择不包含任何子元素的元素。子元素可以是元素节点或文本，包括空格。但是注释、处理指令和 CSS {{cssxref("content", "内容")}}不会影响元素是否被认定为空。
好的，感谢建议

2023-04-18 01:27 UTC, daiwanxing commented on files/zh-cn/web/css/_colon_empty/index.md
> +> **备注：** 在[选择器 Level 4](https://drafts.csswg.org/selectors-4/#the-empty-pseudo) 中，`:empty` 伪类被更改为类似于 {{CSSxRef(":-moz-only-whitespace")}}，但目前还没有浏览器支持它。
这段翻译读起来并未通顺，重新调整后："`:empty` 伪类被更改为与 `:-moz-only-whitespace` 类似一样的行为"

2023-04-18 04:18 UTC, yin1999 approved these changes

2023-04-18 07:26 UTC, merged