zh-cn: sync with en-US version for css `:hover`
mdn/translated-content pull request #12773
Opened 2023-04-16 08:24 UTC by daiwanxing

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-04-17 08:12 UTC, yin1999 requested changes

2023-04-17 08:12 UTC, yin1999 commented on files/zh-cn/web/css/_colon_hover/index.md
> + **`:hover`** 是 [CSS](/zh-CN/docs/Web/CSS) 中的一个[伪类](/zh-CN/docs/Web/CSS/Pseudo-classes)，它匹配用户使用指针设备与元素进行交互但不一定激活元素的情况。通常情况下，用户将光标（鼠标指针）悬停在元素上时触发。
怎么这个文档的书写风格又和 #12775 不一样了

2023-04-18 02:09 UTC, daiwanxing commented on files/zh-cn/web/css/_colon_hover/index.md
> + **`:hover`** 是 [CSS](/zh-CN/docs/Web/CSS) 中的一个[伪类](/zh-CN/docs/Web/CSS/Pseudo-classes)，它匹配用户使用指针设备与元素进行交互但不一定激活元素的情况。通常情况下，用户将光标（鼠标指针）悬停在元素上时触发。
欠缺考虑到风格的一致性了，我想，我计划接下来的伪类一章节的书写风保持一致

2023-04-18 07:25 UTC, yin1999 commented on files/zh-cn/web/css/_colon_hover/index.md
> +`:hover` 伪类定义的样式将被任何后续的链接相关伪类（{{ cssxref(":link") }}、{{ cssxref(":visited") }}、或 {{ cssxref(":active") }}）覆盖，这些伪类的特殊性至少相等。为了适当地为链接设置样式，应该在 `:link`和 `:visited` 规则之后但在 `:active` 规则之前放置 `:hover` 规则，即按照
```suggestion
`:hover` 伪类定义的样式将被任何后续的链接相关伪类（{{ cssxref(":link") }}、{{ cssxref(":visited") }} 或 {{ cssxref(":active") }}）覆盖，这些伪类的特殊性至少相等。为了适当地为链接设置样式，应该在 `:link`和 `:visited` 规则之后，`:active` 规则之前放置 `:hover` 规则，即按照 _LVHA 定义的顺序_：`link` — `:visited` — `:hover` — `:active`。
```

2023-04-18 07:33 UTC, yin1999 approved these changes

2023-04-18 07:34 UTC, merged