Corrects 404 links in the FR translation
mdn/translated-content pull request #12779
Opened 2023-04-16 13:43 UTC by Lou8is

### Description

Corrects three 404 links, two to the popup page (page exists, link is incorrect) and one to the browserAction.onClicked

### Motivation

Readers will be able to navigate the documentation more easily with corrected links.

### Additional details

None

### Related issues and pull requests

None that I know of.

2023-04-16 19:18 UTC, SphinxKnight requested changes
Merci @Lou8is pour ces corrections bienvenues :) Peut-on en profiter pour mettre les liens "effectifs" actuellement afin d'éviter les redirections ?

2023-04-16 19:18 UTC, SphinxKnight commented on files/fr/mozilla/add-ons/webextensions/user_interface/browser_action/index.md
> +Il existe deux façons de spécifier une action du navigateur: avec ou sans [popup](/fr/Add-ons/WebExtensions/user_interface/Popups). Si vous ne spécifiez pas de popup, lorsque l'utilisateur clique sur
```suggestion
Il existe deux façons de spécifier une action du navigateur: avec ou sans [popup](/fr/docs/Mozilla/Add-ons/WebExtensions/user_interface/Popups). Si vous ne spécifiez pas de popup, lorsque l'utilisateur clique sur le bouton, un événement est envoyé à l'extension, que celle-ci attend pour utiliser [`browserAction.onClicked`](/fr/docs/Mozilla/Add-ons/WebExtensions/API/BrowserAction/onClicked) :
```

2023-04-16 19:18 UTC, SphinxKnight commented on files/fr/mozilla/add-ons/webextensions/user_interface/browser_action/index.md
> +Si vous spécifiez une fenêtre contextuelle, l'événement de clic n'est pas envoyé : A la place, le popup s'affiche lorsque l'utilisateur clique sur le bouton. L'utilisateur peut interagir avec le popu
```suggestion
Si vous spécifiez une fenêtre contextuelle, l'événement de clic n'est pas envoyé : A la place, le popup s'affiche lorsque l'utilisateur clique sur le bouton. L'utilisateur peut interagir avec le popup et il se ferme automatiquement lorsque l'utilisateur clique à l'extérieur. Consulter l'article [Popup](/fr/docs/Mozilla/Add-ons/WebExtensions/user_interface/Popups) pour plus de détails sur la création et la gestion des fenêtres pop-up.
```

2023-04-16 20:37 UTC, Lou8is commented
@SphinxKnight Sans problème, j'avais pris pour exemple les autres liens de la page qui eux fonctionnait.

2023-04-17 06:19 UTC, SphinxKnight approved these changes
Merci :)

2023-04-17 06:19 UTC, merged