[zh-cn]: Update the translation of Array.@@unscopables
mdn/translated-content pull request #12793
Opened 2023-04-17 06:05 UTC by JasonLamv-t

### Description

更新 `Array.@@unscopables` 的翻译

### Motivation

同上

### Additional details

原文中：## Value 似乎应为 ## Return value，将在原文 repo 中提出 Issue，并等待 close/fix 后再行合并

2023-04-17 06:37 UTC, jasonren0403 commented on files/zh-cn/web/javascript/reference/global_objects/array/@@unscopables/index.md
>  }
代码格式

2023-04-18 07:46 UTC, yin1999 requested changes

2023-04-18 07:46 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/@@unscopables/index.md
> +`Array.prototype` 的 **`@@unscopables`** 数据属性被所有 {{jsxref("Array")}} 实例共享。它包含在 ES2015(ES6) 版本之前 ECMAScript 标准中未收纳的属性名，并且这些属性被排除在由 [`with`](/zh-CN/docs/Web/JavaScript/Reference/Statements/with) 语句绑定的环境
怎么重复写了一段，这一段其实应该是根据原来中文文档的第一段改的吧

![image](https://user-images.githubusercontent.com/15844309/232707624-f454606d-c615-4255-9342-ab47faecbc39.png)

2023-04-18 07:51 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/@@unscopables/index.md
>  Symbol 属性 **`@@unscopable`** 包含了所有 ES2015 (ES6) 中新定义的、且并未被更早的 ECMAScript 标准收纳的属性名。这些属性被排除在由 [`with`](/zh-CN/docs/Web/JavaScript/Reference/Statements/with) 语句绑定的环境中。
```suggestion
```

2023-04-19 00:44 UTC, yin1999 requested changes

2023-04-19 00:44 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/@@unscopables/index.md
> +请参阅 {{jsxref("Symbol.unscopables")}} 了解如何为自定义对象设置不可作用域属性。
我并不认同“不可作用域”这一翻译，这个翻译有什么依据吗

2023-04-19 02:35 UTC, Josh-Cena commented on files/zh-cn/web/javascript/reference/global_objects/array/@@unscopables/index.md
> +请参阅 {{jsxref("Symbol.unscopables")}} 了解如何为自定义对象设置不可作用域属性。
「不可作用域」确实不通顺，我建议「不可被绑定」，但 https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Symbol/unscopables 里没有翻译这个关键词，所以这里也不一定要翻译

2023-04-19 04:40 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/@@unscopables/index.md
> +请参阅 {{jsxref("Symbol.unscopables")}} 了解如何为自定义对象设置不可作用域属性。
> 我并不认同“不可作用域”这一翻译，这个翻译有什么依据吗

我倾向于保留或者翻译成 `不可访问/调用的`, 这么翻译只是之前过于注重 ‘made’ 这个词。

```suggestion
`Array.prototype[@@unscopables]` 是一个空对象，仅包含所有上述属性，且对应值为 `true`。它的[原型是 `null`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object#null_原型对象)，因此不会意外地将 `Object.prototype` 属性（比如 [`toString`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/toString)）设置为 unscopable ，而令在 `with` 语句中调用数组的 `toString()` 方法仍然有效。

请参阅 {{jsxref("Symbol.unscopables")}} 了解如何为自定义对象设置不可作用域属性。
```

2023-04-19 04:51 UTC, Josh-Cena commented on files/zh-cn/web/javascript/reference/global_objects/array/@@unscopables/index.md
> +请参阅 {{jsxref("Symbol.unscopables")}} 了解如何为自定义对象设置不可作用域属性。
「不可访问/调用」对应的是 "Inaccessible/Uncallable", 指的是属性自己设置的性质，而不是 `with` 语句的行为。后者完成的是把属性绑定到作用域上的工作 "attach to scope"，至于之后究竟能不能真的通过变量名访问到属性还不一定，所以「不可绑定」是我能想到的最好的翻译

2023-04-19 05:38 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/@@unscopables/index.md
> +请参阅 {{jsxref("Symbol.unscopables")}} 了解如何为自定义对象设置不可作用域属性。
所以我评论的代码更改是保留 `unscopable`

2023-04-19 07:03 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/@@unscopables/index.md
> +请参阅 {{jsxref("Symbol.unscopables")}} 了解如何为自定义对象设置不可作用域属性。
考虑翻译为“非作用域”，但在使用时可能需要加上“属性”二字。

```suggestion
`Array.prototype[@@unscopables]` 是一个只包含所有上述属性且对应值为 `true` 的空对象。它的[原型是 `null`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object#null_原型对象)，因此不会意外地使 `Object.prototype` 属性（比如 [`toString`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/toString)）变为非作用域属性，而令在 `with` 语句中调用数组的 `toString()` 方法仍然有效。

请参阅 {{jsxref("Symbol.unscopables")}} 了解如何为自定义对象设置非作用域属性。
```

@Josh-Cena 你有什么想法

2023-04-19 07:57 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/@@unscopables/index.md
> +请参阅 {{jsxref("Symbol.unscopables")}} 了解如何为自定义对象设置不可作用域属性。
如果是 `非作用域` 和 `不可绑定` 二选一的话，我觉得 非作用域 更准确一些，不可绑定可能会有一些歧义

2023-04-26 00:59 UTC, yin1999 approved these changes

2023-04-26 01:00 UTC, merged