Les macros/titres des éléments <em>,<embed> et <figure> sont modifiés
mdn/translated-content pull request #12800
Opened 2023-04-17 11:43 UTC by Mehrm0

### Description
Quelques macros sont insérées/ modifiées et les blocs *Résultat* sont ajoutés. 

### Motivation

### Additional details

### Related issues and pull requests

2023-04-17 20:58 UTC, cw118 requested changes
Un seul commentaire, merci déjà @Mehrm0 !

2023-04-17 20:58 UTC, cw118 commented on files/fr/web/html/element/figure/index.md
> +#### Résultat
```suggestion
#### Résultat

{{EmbedLiveSample("", "100%", 480)}}
```

2023-04-18 02:08 UTC, Mehrm0 commented on files/fr/web/html/element/figure/index.md
> +#### Résultat
> ```suggestion
> #### Résultat
> 
> {{EmbedLiveSample("", "100%", 480)}}
> ```

Je m'excuse, c'est une drôle de faute.

2023-04-18 23:22 UTC, cw118 approved these changes
Pas de souci, merci pour cette contribution :)

2023-04-18 23:22 UTC, merged