Ready for review
mdn/translated-content pull request #12804
Opened 2023-04-17 13:41 UTC by robert-jx

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-04-17 15:59 UTC, JasonLamv-t requested changes
Some suggestions

2023-04-17 15:59 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/findlast/index.md
> +- 该数组中是否*存在* 一个值，使用 {{jsxref("Array.prototype.includes()")}}。同样地，它检查每个元素是否和值相等，而不是使用一个测试函数。
```suggestion
- 该数组中是否*存在*一个值，使用 {{jsxref("Array.prototype.includes()")}}。同样地，它检查每个元素是否和值相等，而不是使用一个测试函数。
```

2023-04-17 15:59 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/findlast/index.md
> +  - : 执行 `callbackFn` 时，用作 {{jsxref("Operators/this", "this")}} 的值。详见[迭代方法](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#iterative_methods)
```suggestion
  - : 执行 `callbackFn` 时，用作 {{jsxref("Operators/this", "this")}} 的值。详见[迭代方法](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array#iterative_methods)
```

2023-04-17 15:59 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/findlast/index.md
> +`findLast()` 是一个[迭代方法](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#iterative_methods)。该方法对数组每一个元素按降序（索引从大到小）执行 `callbackFn` 函数，直到 `callbackFn` 返回一个[真值](/zh-CN/docs/Glossary/Truthy)。然后 `
```suggestion
`findLast()` 是一个[迭代方法](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array#迭代方法)。该方法对数组每一个元素按降序（索引从大到小）执行 `callbackFn` 函数，直到 `callbackFn` 返回一个[真值](/zh-CN/docs/Glossary/Truthy)。然后 `findLast()` 返回该元素的值并停止遍历数组。如果 `callbackFn` 没有返回一个真值，则 `findLast()` 返回 {{jsxref("undefined")}}。
```

2023-04-17 15:59 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/findlast/index.md
> +`callbackFn` 会被数组中的*每个*元素调用，而不仅仅是那些被赋值的元素。对于[稀疏数组]()来说，空槽行为和`undefined`相同。
```suggestion
`callbackFn` 会被数组中的*每个*元素调用，而不仅仅是那些被赋值的元素。对于[稀疏数组](/zh-CN/docs/Web/JavaScript/Guide/Indexed_collections#稀疏数组)来说，空槽行为和`undefined`相同。
```

2023-04-17 15:59 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/findlast/index.md
> +`findLast()` 方法不会改变调用它的数组，但是提供的 `callbackFn` 可以。但是请注意，数组的长度是在第一次调用`callbackFn`*之前*保存的。因此：
```suggestion
`findLast()` 方法不会改变调用它的数组，但是提供的 `callbackFn` 可以。但是请注意，数组的长度是在第一次调用 `callbackFn` *之前*保存的。因此：
```

2023-04-17 15:59 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/findlast/index.md
>  - 给初始的范围外的索引赋值，其将不会被 `callbackFn` 访问。
```suggestion
```

2023-04-17 15:59 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/findlast/index.md
> +- 如果 `callbackFn` 更改了数组中现有的、尚未访问的元素，则其传递给 `callbackFn` 的值将是 `findLast()` 访问该元素索引时的值。[已删除](/en-US/docs/Web/JavaScript/Reference/Operators/delete)元素会被当做`undefined`来访问。
```suggestion
- 如果 `callbackFn` 更改了数组中现有的、尚未访问的元素，则其传递给 `callbackFn` 的值将是 `findLast()` 访问该元素索引时的值。[已删除](/zh-CN/docs/Web/JavaScript/Reference/Operators/delete)的元素会被当做 `undefined` 来访问。
```

2023-04-17 15:59 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/findlast/index.md
> +`findLast()`方法是[通用的](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#generic_array_methods)。它只期望`this`值具有`length`属性和整数键的属性
```suggestion
`findLast()` 方法是[通用的](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array#通用数组方法)。它只期望 `this` 值具有 `length` 属性和整数键的属性
```

2023-04-17 15:59 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/findlast/index.md
> +稀疏数组中的空槽*被*访问，并被视为`undefined`
```suggestion
稀疏数组中的空槽*被*访问，并被视为 `undefined`
```

2023-04-17 15:59 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/findlast/index.md
> +### 在非数组对象上调用findLast()
```suggestion
### 在非数组对象上调用 findLast()
```

2023-04-17 15:59 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/findlast/index.md
> +`findLast()`方法读取`this`的`length`属性，然后访问每个整数索引
```suggestion
`findLast()` 方法读取 `this` 的 `length` 属性，然后访问每个整数索引
```

2023-04-17 15:59 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/findlast/index.md
> +- [Indexed collections](/en-US/docs/Web/JavaScript/Guide/Indexed_collections)
```suggestion
- [索引集合类](/zh-CN/docs/Web/JavaScript/Guide/Indexed_collections)
```

2023-04-18 01:58 UTC, jasonren0403 commented on files/zh-cn/web/javascript/reference/global_objects/array/findlast/index.md
> +  - : 执行 `callbackFn` 时，用作 {{jsxref("Operators/this", "this")}} 的值。详见[迭代方法](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array#iterative_methods)
下面更新了，这行忘了
```suggestion
  - : 执行 `callbackFn` 时，用作 {{jsxref("Operators/this", "this")}} 的值。详见[迭代方法](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array#迭代方法)
```

2023-04-18 01:59 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/array/findlast/index.md
> +  - : 执行 `callbackFn` 时，用作 {{jsxref("Operators/this", "this")}} 的值。详见[迭代方法](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array#iterative_methods)
```suggestion
  - : 执行 `callbackFn` 时，用作 {{jsxref("Operators/this", "this")}} 的值。详见[迭代方法](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array#iterative_methods)。
```

2023-04-18 01:59 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/array/findlast/index.md
> +`callbackFn` 会被数组中的*每个*元素调用，而不仅仅是那些被赋值的元素。对于[稀疏数组](/zh-CN/docs/Web/JavaScript/Guide/Indexed_collections#稀疏数组)来说，空槽行为和`undefined`相同。
```suggestion
`callbackFn` 会被数组中的*每个*元素调用，而不仅仅是那些被赋值的元素。对于[稀疏数组](/zh-CN/docs/Web/JavaScript/Guide/Indexed_collections#稀疏数组)来说，空槽行为和 `undefined` 相同。
```

2023-04-18 01:59 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/array/findlast/index.md
> +`findLast()` 方法是[通用的](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array#通用数组方法)。它只期望 `this` 值具有 `length` 属性和整数键的属性
```suggestion
`findLast()` 方法是[通用的](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array#通用数组方法)。它只期望 `this` 值具有 `length` 属性和整数键的属性。
```

2023-04-18 01:59 UTC, fwqaaq commented on files/zh-cn/web/javascript/reference/global_objects/array/findlast/index.md
> +`findLast()` 方法读取 `this` 的 `length` 属性，然后访问每个整数索引
```suggestion
`findLast()` 方法读取 `this` 的 `length` 属性，然后访问每个整数索引。
```

2023-04-18 02:41 UTC, robert-jx commented on files/zh-cn/web/javascript/reference/global_objects/array/findlast/index.md
> +  - : 执行 `callbackFn` 时，用作 {{jsxref("Operators/this", "this")}} 的值。详见[迭代方法](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array#iterative_methods)
```suggestion
  - : 执行 `callbackFn` 时，用作 {{jsxref("Operators/this", "this")}} 的值。详见[迭代方法](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array#迭代方法)。
```

2023-04-19 07:22 UTC, yin1999 approved these changes
Thanks. Welcome aboard :tada:

2023-04-19 07:24 UTC, merged