translate(zh-cn): config methods of GPUCanvasContext
mdn/translated-content pull request #12816
Opened 2023-04-18 09:15 UTC by fwqaaq

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-04-18 09:15 UTC, fwqaaq commented on files/zh-cn/web/api/gpucanvascontext/config/index.md
> +        - `GPUTextureUsage.STORAGE_BINDING`: 纹理可绑定以在着色器中用作存储纹理，例如，调用 {{domxref("GPUDevice.createBindGroup()")}} 的要使用的绑定组条目。
```suggestion
        - `GPUTextureUsage.STORAGE_BINDING`：纹理可绑定以在着色器中用作存储纹理，例如，调用 {{domxref("GPUDevice.createBindGroup()")}} 的要使用的绑定组条目。
```

2023-04-18 09:22 UTC, fwqaaq commented on files/zh-cn/web/api/gpucanvascontext/config/index.md
> +      - : 视图从 `getCurrentTexture()` 返回的纹理创建的可能使用的格式数组。有关所有可能的值，请参阅[纹理格式](https://gpuweb.github.io/gpuweb/#texture-formats)
```suggestion
      - : 视图从 `getCurrentTexture()` 返回的纹理创建时可能使用的格式数组。有关所有可能的值，请参阅[纹理格式](https://gpuweb.github.io/gpuweb/#texture-formats)。
```

2023-04-18 09:36 UTC, fwqaaq commented on files/zh-cn/web/api/gpucanvascontext/configure/index.md
> +        - `GPUTextureUsage.RENDER_ATTACHMENT`：纹理可用于渲染通道中的颜色附件，例如，调用 {{domxref("GPUCommandEncoder.beginRenderPass()")}} 中要使用的颜色附件视图。`usage` 的默认值是 `GPUTextureUsage.RENDER_ATTACHMENT`，但请注意，如果明确设置了不同的值，则
```suggestion
        - `GPUTextureUsage.RENDER_ATTACHMENT`：纹理可用于渲染通道中的颜色附件，例如，调用 {{domxref("GPUCommandEncoder.beginRenderPass()")}} 中要使用的颜色附件视图。`usage` 的默认值是 `GPUTextureUsage.RENDER_ATTACHMENT`，但请注意，如果明确设置了不同的值，则不会自动地包含它；在这种情况下，你需要去主动的添加。
```

2023-04-19 11:19 UTC, yin1999 requested changes

2023-04-19 11:19 UTC, yin1999 commented on files/zh-cn/web/api/gpucanvascontext/configure/index.md
> +      - : 枚举值，用于指定 alpha 值，当在读取、显示或者使用作为图像时，该值可以通过 {{domxref("GPUCanvasContext.getCurrentTexture()", "getCurrentTexture()")}} 返回的纹理内容产生效果。
这段话我没读懂到底是啥意思

2023-04-19 11:19 UTC, yin1999 commented on files/zh-cn/web/api/gpucanvascontext/configure/index.md
> +      - : `getCurrentTexture()` 返回的纹理中写入的值应该使用哪种颜色空间来显示。可能的值时 `srgb`（默认值）和 `display-p3`。
```suggestion
      - : `getCurrentTexture()` 返回的纹理中写入的值应该使用哪种颜色空间来显示。可能的值是 `srgb`（默认值）和 `display-p3`。
```

2023-04-19 11:19 UTC, yin1999 commented on files/zh-cn/web/api/gpucanvascontext/configure/index.md
> +      - : 上下文渲染信息将来自的 {{domxref("GPUDevice")}}。
```suggestion
      - : 包含上下文渲染信息的 {{domxref("GPUDevice")}}。
```

2023-04-19 11:36 UTC, fwqaaq commented on files/zh-cn/web/api/gpucanvascontext/configure/index.md
> +      - : 枚举值，用于指定 alpha 值，当在读取、显示或者使用作为图像时，该值可以通过 {{domxref("GPUCanvasContext.getCurrentTexture()", "getCurrentTexture()")}} 返回的纹理内容产生效果。
用于控制纹理的透明度

2023-04-19 11:44 UTC, fwqaaq commented on files/zh-cn/web/api/gpucanvascontext/configure/index.md
> +      - : 枚举值，用于指定 alpha 值，当在读取、显示或者使用作为图像时，该值可以通过 {{domxref("GPUCanvasContext.getCurrentTexture()", "getCurrentTexture()")}} 返回的纹理内容产生效果。
```suggestion
      - : 枚举值，用于指定 alpha 值，用于指定在读取、显示或使用作为图像源的纹理时，该值会对通过 {{domxref("GPUCanvasContext.getCurrentTexture()", "getCurrentTexture()")}} 返回的纹理产生影响。
```

2023-04-19 11:48 UTC, fwqaaq commented on files/zh-cn/web/api/gpucanvascontext/configure/index.md
> +      - : 枚举值，用于指定 alpha 值，当在读取、显示或者使用作为图像时，该值可以通过 {{domxref("GPUCanvasContext.getCurrentTexture()", "getCurrentTexture()")}} 返回的纹理内容产生效果。
现在应该好一点？

2023-04-19 12:07 UTC, yin1999 commented on files/zh-cn/web/api/gpucanvascontext/configure/index.md
> +      - : 枚举值，用于指定 alpha 值，当在读取、显示或者使用作为图像时，该值可以通过 {{domxref("GPUCanvasContext.getCurrentTexture()", "getCurrentTexture()")}} 返回的纹理内容产生效果。
或“用作”（使用作为 太长了）

2023-04-20 01:38 UTC, merged