[zh-cn]: add translation for Web/CSS/CSS_Container_Queries
mdn/translated-content pull request #12821
Opened 2023-04-18 13:02 UTC by immccn123

### Description

Add translation for Web/CSS/CSS_Container_Queries.

本人能力有限，若翻译有疏漏或不妥当，恳请指正。  
If there are any omissions or inappropriate translations, please correct me.

### Motivation

just saw that it has no zh-CN translation

### Additional details

### Related issues and pull requests

2023-04-19 00:10 UTC, immccn123 commented on files/zh-cn/web/css/css_container_queries/index.md
> +要使用容器查询，你需要在元素上声明一个**容器上下文（Containment context）**，以便浏览器知道你可能希望稍后查询此容器的尺寸。为此，请使用 {{Cssxref("container-type")}} 属性，值为 `size`、`inline-size` 或 `normal`。
感谢指正🙏

2023-04-19 11:21 UTC, yin1999 requested changes

2023-04-19 11:21 UTC, yin1999 commented on files/zh-cn/web/css/css_container_queries/index.md
> +  - ：该元素不是任何容器大小查询的查询容器，但仍然是容器样式查询的查询容器。
见 https://developer.mozilla.org/zh-CN/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN#%E5%AE%9A%E4%B9%89%E5%88%97%E8%A1%A8

```suggestion
  - : 查询将基于容器的[行向和块向](/zh-CN/docs/Web/CSS/CSS_Logical_Properties/Basic_concepts#块向与行向尺度)尺度，将布局、样式和大小的限制应用于容器。
- `inline-size`
  - : 查询将基于容器的[行向](/zh-CN/docs/Web/CSS/CSS_Logical_Properties/Basic_concepts#块向与行向尺度)尺度，将布局、样式和行向大小的限制应用于元素。
- `normal`
  - : 该元素不是任何容器大小查询的查询容器，但仍然是容器样式查询的查询容器。
```

2023-04-19 11:21 UTC, yin1999 commented on files/zh-cn/web/css/css_container_queries/index.md
> +有关这些单位的更多信息，请参阅[容器查询长度单位](/zh-CN/docs/Web/CSS/length#容器查询长度单位) 参考。
```suggestion
有关这些单位的更多信息，请参阅[容器查询长度单位](/zh-CN/docs/Web/CSS/length#容器查询长度单位)参考。
```

2023-04-19 11:21 UTC, yin1999 commented on files/zh-cn/web/css/css_container_queries/index.md
> +page-type: guide
https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md#%E5%85%83%E6%95%B0%E6%8D%AE

```suggestion
```

2023-04-19 13:25 UTC, immccn123 commented on files/zh-cn/web/css/css_container_queries/index.md
> +page-type: guide
已修正 感谢您的耐心指正

2023-04-20 01:45 UTC, yin1999 commented on files/zh-cn/web/css/css_container_queries/index.md
> +使用容器查询时，卡片可以在页面的多个区域中重复使用，无需每次都知道它放置在的具体位置。如果包含卡片的容器宽度小于 `700px`，卡片标题的字体将变小，如果卡片在宽度大于 `700px` 的容器中，则卡片标题的字体将变大。有关容器查询语法的更多信息，请参阅 {{cssxref("@container")}} 页面。
```suggestion
使用容器查询时，卡片可以在页面的多个区域中重复使用，无需每次都知道它放置在的具体位置。如果包含卡片的容器宽度小于 `700px`，卡片标题的字体将变小，如果卡片在宽度大于 `700px` 的容器中，则卡片标题的字体将变大。

有关容器查询语法的更多信息，请参阅 {{cssxref("@container")}} 页面。
```

2023-04-20 01:45 UTC, yin1999 commented on files/zh-cn/web/css/css_container_queries/index.md
> +在上一节中，容器查询基于有局限上下文的最近祖先元素应用样式。可以使用 {{Cssxref("container-name")}} 属性为局限上下文命名。命名后，可以在 `@container` 查询中使用该名称针对特定容器。以下示例创建了一个名为 `sidebar` 的局限上下文：
“针对”这个翻译感觉不太好

2023-04-20 01:45 UTC, yin1999 commented on files/zh-cn/web/css/css_container_queries/index.md
> +然后，你可以使用 at 规则 `@container` 针对此局限上下文：
同

2023-04-20 13:03 UTC, immccn123 commented on files/zh-cn/web/css/css_container_queries/index.md
> +在上一节中，容器查询基于有局限上下文的最近祖先元素应用样式。可以使用 {{Cssxref("container-name")}} 属性为局限上下文命名。命名后，可以在 `@container` 查询中使用该名称针对特定容器。以下示例创建了一个名为 `sidebar` 的局限上下文：
改成（上面被否决的）“定位”？

> 在这里，“定位”意味着通过名称来选择或识别容器，而不是指“位置”。

2023-04-20 13:08 UTC, immccn123 commented on files/zh-cn/web/css/css_container_queries/index.md
> +然后，你可以使用 at 规则 `@container` 针对此局限上下文：
然后这里翻成“选择”

后面加上 “从而可以对其中的元素进行样式操作：” 可能会更清晰一点

2023-04-20 13:14 UTC, immccn123 commented on files/zh-cn/web/css/css_container_queries/index.md
> +在上一节中，容器查询基于有局限上下文的最近祖先元素应用样式。可以使用 {{Cssxref("container-name")}} 属性为局限上下文命名。命名后，可以在 `@container` 查询中使用该名称针对特定容器。以下示例创建了一个名为 `sidebar` 的局限上下文：
> “针对”这个翻译感觉不太好

改成“标识”可以吗

2023-04-20 14:22 UTC, immccn123 commented on files/zh-cn/web/css/css_container_queries/index.md
> +在上一节中，容器查询基于有局限上下文的最近祖先元素应用样式。可以使用 {{Cssxref("container-name")}} 属性为局限上下文命名。命名后，可以在 `@container` 查询中使用该名称针对特定容器。以下示例创建了一个名为 `sidebar` 的局限上下文：
```suggestion
在上一节中，容器查询基于有局限上下文的最近祖先元素应用样式。可以使用 {{Cssxref("container-name")}} 属性为局限上下文命名。命名后，可以在 `@container` 查询中使用该名称以选择特定容器。以下示例创建了一个名为 `sidebar` 的局限上下文：
```

2023-04-20 14:24 UTC, immccn123 commented on files/zh-cn/web/css/css_container_queries/index.md
> +然后，你可以使用 at 规则 `@container` 针对此局限上下文：
```suggestion
然后，你可以使用 at 规则 `@container` 选择此局限上下文，从而对其中的元素进行样式操作：
```

2023-04-21 01:48 UTC, yin1999 commented on files/zh-cn/web/css/css_container_queries/index.md
> +然后，你可以使用 at 规则 `@container` 针对此局限上下文：
> 后面加上 “从而可以对其中的元素进行样式操作：” 可能会更清晰一点

还是不加这句了，和英文文档保持一致就好，看到下方的示例代码读者能明白意思

2023-04-21 01:52 UTC, yin1999 approved these changes
:+1:

2023-04-21 01:52 UTC, merged