zh-CN: translate worker/error_evnet
mdn/translated-content pull request #12824
Opened 2023-04-18 15:58 UTC by Yukiniro

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-04-18 20:47 UTC, BSPR0002 requested changes

2023-04-18 20:47 UTC, BSPR0002 commented on files/zh-cn/web/api/worker/error_event/index.md
> +title: Worker: error 事件
规避 YAML 解释器错误：
```suggestion
title: "Worker: error 事件"
```
或使用中文冒号：
```suggestion
title: Worker：error 事件
```

2023-04-19 01:18 UTC, jasonren0403 commented on files/zh-cn/web/api/worker/error_event/index.md
> +title: Worker: error 事件
用中文冒号就行

2023-04-19 01:20 UTC, Yukiniro commented on files/zh-cn/web/api/worker/error_event/index.md
> +title: Worker: error 事件
ok

2023-04-20 02:09 UTC, yin1999 commented on files/zh-cn/web/api/worker/error_event/index.md
> +当 worker 发生错误时，就会触发 {{domxref("Worker")}} 接口的 **`error`** 事件。
可以改成“某某接口的某某事件会在 xxx 时触发吗”。把关键字提前

2023-04-20 13:55 UTC, Yukiniro commented on files/zh-cn/web/api/worker/error_event/index.md
> +当 worker 发生错误时，就会触发 {{domxref("Worker")}} 接口的 **`error`** 事件。
好的，我更新下 PR

2023-04-21 00:50 UTC, yin1999 approved these changes

2023-04-21 00:50 UTC, merged