[ko] fix: learn/javascript/objects en-us와 동기화
mdn/translated-content pull request #1283
Opened 2021-06-22 17:31 UTC by hochan222

#1042

[ko] fix: learn/javascript/objects en-us와 동기화

2021-06-22 17:32 UTC, hochan222 commented on files/ko/learn/javascript/objects/index.html
> +</dl>
```suggestion
</dl>

```

2021-06-22 17:32 UTC, hochan222 commented on files/ko/learn/javascript/objects/index.html
> +</dl>
eol

2021-07-04 10:13 UTC, pje1740 commented on files/ko/learn/javascript/objects/index.html
> +<p class="summary"> 자바스크립트에서는 배열과같은 기능부터 JavaScript 위에 구축된 브라우저 API에 이르기까지 대부분의 것들이 객체입니다. 사용자는 관련된 함수들과 변수들을 효율적인 패키지로 추상화하거나 편리한 데이터 컨테이너로 작동하는 객체를 만들 수 있습니다. 언어에 대한 지식을 가지고 더 멀리 나아고자 한다면 자바스크립트의 객
API 부분 원문과 동일하게 Glossary 연결이 필요한 거 같습니다 :)

2021-07-04 10:41 UTC, pje1740 requested changes
Glossary 빠진 부분만 확인해주시면 될 거 같아요! 고생하셨습니다! (_ _)

2021-07-07 01:08 UTC, hochan222 commented on files/ko/learn/javascript/objects/index.html
> +<p class="summary"> 자바스크립트에서는 배열과같은 기능부터 JavaScript 위에 구축된 브라우저 API에 이르기까지 대부분의 것들이 객체입니다. 사용자는 관련된 함수들과 변수들을 효율적인 패키지로 추상화하거나 편리한 데이터 컨테이너로 작동하는 객체를 만들 수 있습니다. 언어에 대한 지식을 가지고 더 멀리 나아고자 한다면 자바스크립트의 객
```suggestion
<p class="summary"> 자바스크립트에서는 배열과같은 기능부터 JavaScript 위에 구축된 브라우저 {{Glossary("API", "APIs")}}에 이르기까지 대부분의 것들이 객체입니다. 사용자는 관련된 함수들과 변수들을 효율적인 패키지로 추상화하거나 편리한 데이터 컨테이너로 작동하는 객체를 만들 수 있습니다. 언어에 대한 지식을 가지고 더 멀리 나아고자 한다면 자바스크립트의 객체 기반의 본질을 이해하는 것이 중요하므로, 여러분을 돕기위해 이 모듈을 제공하였습니다. 여기에서는 객체 이론과 구문을 자세히 가르쳐드리며, 사용자 정의 객체를 만드는 방법도 알아볼 것입니다.</p>
```

2021-07-07 01:09 UTC, hochan222 commented
앗앗 원문 문장이 이상해서 해석만 바꿨는데 Glossary부분을 빼먹었네요! 감사합니다. 좋은 하루 보내세요 :)

2021-07-09 05:25 UTC, pje1740 approved these changes
고생하셨습니다!

2021-07-09 05:25 UTC, merged