translate(zh-cn): The importmap value of the type attribute of the sc…
mdn/translated-content pull request #12852
Opened 2023-04-20 02:08 UTC by fwqaaq

…ript

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-04-20 04:31 UTC, fwqaaq commented on files/zh-cn/web/html/element/script/type/importmap/index.md
> +不得 `src`、`async`、`nomodule`、`defer`、`crossorigin`、`integrity` 和 `referrerpolicy` 属性。
```suggestion
不得指定 `src`、`async`、`nomodule`、`defer`、`crossorigin`、`integrity` 和 `referrerpolicy` 属性。
```

2023-04-20 12:20 UTC, yin1999 requested changes

2023-04-20 12:20 UTC, yin1999 commented on files/zh-cn/web/html/element/script/type/importmap/index.md
> +有关更多信息，请参见 JavaScript 模块指导的[使用导入映射导入模块](/zh-CN/docs/Web/JavaScript/Guide/Modules#使用导入映射导入模块)。
```suggestion
有关更多信息，请参见 JavaScript 模块指南的[使用导入映射导入模块](/zh-CN/docs/Web/JavaScript/Guide/Modules#使用导入映射导入模块)部分。
```

2023-04-20 12:20 UTC, yin1999 commented on files/zh-cn/web/html/element/script/type/importmap/index.md
> +  // JSON object defining import
```suggestion
  // 定义导入的 JSON 对象
```

2023-04-20 12:20 UTC, yin1999 commented on files/zh-cn/web/html/element/script/type/importmap/index.md
> +script 元素中的 `type="importmap"` 并未处理，则会触发 [`error` 事件](/zh-CN/docs/Web/API/Element/error_event)。这是可能发生的，例如，在处理导入模块时模块加载已经开始，或页面中定义了多个导入映射。
```suggestion
如果 script 元素中的 `type="importmap"` 没有被处理，则会触发 [`error` 事件](/zh-CN/docs/Web/API/Element/error_event)。这是可能发生的，例如，在处理导入模块时模块已经开始加载，或页面中定义了多个导入映射。
```

2023-04-20 12:20 UTC, yin1999 commented on files/zh-cn/web/html/element/script/type/importmap/index.md
> +导入映射允许开发着在模块标识中指定（几乎）他们想要的任意文本；映射提供了一个相应的值，该值在解析模块标识符时替换文本。
```suggestion
导入映射允许开发者在模块标识中指定（几乎）他们想要的任意文本；映射提供了一个相应的值，该值在解析模块标识符时替换文本。
```

2023-04-20 12:20 UTC, yin1999 commented on files/zh-cn/web/html/element/script/type/importmap/index.md
> +下面的导入映射定义了一个 `imports` 键，该键具有属性为 `square` 和 `circle` 的“模块说明符映射”。
为什么这里变成了“模块说明符”

2023-04-20 12:20 UTC, yin1999 commented on files/zh-cn/web/html/element/script/type/importmap/index.md
> +使用导入映射，我们可以导入以上相同的模块，但在我们的模块标识符中要使用“暴露模块”。
“暴露模块”有具体的引用来源吗

2023-04-20 12:20 UTC, yin1999 commented on files/zh-cn/web/html/element/script/type/importmap/index.md
> +模块标识符符映射键也可用于重新映射模块标识符中的路径前缀。请注意，在这种情况下，属性和映射路径都必须有一个尾随的正斜杠（`/`）。
```suggestion
模块标识符映射键也可用于重新映射模块标识符中的路径前缀。请注意，在这种情况下，属性和映射路径都必须有一个尾随的正斜杠（`/`）。
```

2023-04-20 12:20 UTC, yin1999 commented on files/zh-cn/web/html/element/script/type/importmap/index.md
> +如下，然后我们可以导入 circle 模块。
```suggestion
然后我们可以这样导入 circle 模块。
```

2023-04-20 12:20 UTC, yin1999 commented on files/zh-cn/web/html/element/script/type/importmap/index.md
> +模块标识符键不必是单个单词名称（“暴露名称”）。它们也可以包含或者路径分隔符结尾，或者是绝对 URL，或者以 `/`、`./` 或 `../` 开始的相对 URL。
语病“包含或者路径分隔符结尾”，后面的也好好检查一下，问题有点多，我暂时不检查下去了

2023-04-20 14:57 UTC, fwqaaq commented on files/zh-cn/web/html/element/script/type/importmap/index.md
> +下面的导入映射定义了一个 `imports` 键，该键具有属性为 `square` 和 `circle` 的“模块说明符映射”。
```suggestion
下面的导入映射定义了一个 `imports` 键，该键具有属性为 `square` 和 `circle` 的“模块标识符映射”。
```

2023-04-20 15:05 UTC, fwqaaq commented on files/zh-cn/web/html/element/script/type/importmap/index.md
> +模块标识符键不必是单个单词名称（“暴露名称”）。它们也可以包含或者路径分隔符结尾，或者是绝对 URL，或者以 `/`、`./` 或 `../` 开始的相对 URL。
```suggestion
模块标识符键不必是单个单词名称（“暴露名称”）。它们也可以包含路径分隔符或者以路径分隔符结尾，或者是绝对 URL，或者以 `/`、`./` 或 `../` 开始的相对 URL。
```

2023-04-20 15:09 UTC, fwqaaq commented on files/zh-cn/web/html/element/script/type/importmap/index.md
> +如果模块标识符映射中有几个可能匹配的模块标识符键，则将选择最具体的键（即具有较长路径/值的键）。
```suggestion
如果模块标识符映射中对应几个可能匹配的模块标识符键，则将选择最具体的键（即具有较长路径/值的键）。
```

2023-04-20 15:20 UTC, fwqaaq commented on files/zh-cn/web/html/element/script/type/importmap/index.md
> +例如，仅有加载模块有包含以下路径的 URL：“/modules/customshapes/”，映射才会使用作用域模块。
```suggestion
例如，仅有加载的模块包含以下路径的 URL：“/modules/customshapes/”，映射才会使用作用域映射。
```

2023-04-20 15:25 UTC, fwqaaq commented on files/zh-cn/web/html/element/script/type/importmap/index.md
> +        - 所有的值必须是字符串。定义有效的绝对 URL或者以 `/`、`./` 或 `../` 开始的相对 URL。
```suggestion
        - 所有的值必须是字符串。定义有效的绝对 URL 或者以 `/`、`./` 或 `../` 开始的相对 URL。
```

2023-04-20 15:28 UTC, fwqaaq commented on files/zh-cn/web/html/element/script/type/importmap/index.md
> +    作用域对象是一个有效的 JSON 对象，其每个属性都是一个 `<scope key>`，都是一个 URL 路径，并且相应的值是一个 `<module specifier map>`。
```suggestion
    作用域对象是一个有效的 JSON 对象，其每个属性都是一个 `<scope key>`（URL 路径），并且相应的值是一个 `<module specifier map>`。
```

2023-04-20 15:35 UTC, fwqaaq commented on files/zh-cn/web/html/element/script/type/importmap/index.md
> +`./Foo/../js/app.js` 的模块说明符将在匹配之前解析为 `./js/app.js`。这意味着 `./js/app.js` 的模块标识符键将与模块标识符匹配，即使它们不完全相同。
```suggestion
在匹配之前，`./Foo/../js/app.js` 的模块说明符将解析为 `./js/app.js`。这意味着，即使 `./js/app.js` 的模块标识符键与模块标识符不完全相同，它们也是匹配的。
```

2023-04-20 15:37 UTC, fwqaaq commented on files/zh-cn/web/html/element/script/type/importmap/index.md
> +  - : 该值是[模块标识符映射](#module_specifier_map)，它提供可能在 `import` 语句或 `import()` 运算符中出现的模块标识符文本在解析时将替换它的文本之间的映射。
```suggestion
  - : 该值是[模块标识符映射](#module_specifier_map)，它提供可能在 `import` 语句或 `import()` 运算符中出现的模块标识符文本，其会在解析时与替换它的文本建立映射。
```

2023-04-20 15:39 UTC, fwqaaq commented on files/zh-cn/web/html/element/script/type/importmap/index.md
> +导入映射（import map）是一个 JSON 对象，其允许开发者导入 [JavaScript 模块](/zh-CN/docs/Web/JavaScript/Guide/Modules)时，控制浏览器如何解析模块标识符。它提供了在 [`import` 语句](/zh-CN/docs/Web/JavaScript/Reference/Statements/import)或 [`import()`
```suggestion
导入映射（import map）是一个 JSON 对象，其允许开发者在导入 [JavaScript 模块](/zh-CN/docs/Web/JavaScript/Guide/Modules)时，控制浏览器如何解析模块标识符。它提供了在 [`import` 语句](/zh-CN/docs/Web/JavaScript/Reference/Statements/import)或 [`import()` 运算符](/zh-CN/docs/Web/JavaScript/Reference/Operators/import)中用作模块标识符的文本，其会在解析标识符时与要替换的文本之间建立映射。JSON 对象必须符合[导入映射 JSON 表示格式](#导入映射_json_表示)。
```

2023-04-22 08:43 UTC, yin1999 commented on files/zh-cn/web/html/element/script/type/importmap/index.md
> +使用导入映射，我们可以导入以上相同的模块，但在我们的模块标识符中要使用“暴露模块”。
vite 将其翻译为“裸模块”

https://cn.vitejs.dev/guide/features.html

```suggestion
使用导入映射，我们可以导入以上相同的模块，但在我们的模块标识符要使用“裸模块（bare module）”。
```

2023-04-22 08:47 UTC, fwqaaq commented on files/zh-cn/web/html/element/script/type/importmap/index.md
> +### 暴露模块
```suggestion
### 裸模块
```

2023-04-22 08:48 UTC, fwqaaq commented on files/zh-cn/web/html/element/script/type/importmap/index.md
> +模块标识符键不必是单个单词名称（“暴露名称”）。它们也可以包含路径分隔符或者以路径分隔符结尾，或者是绝对 URL，或者以 `/`、`./` 或 `../` 开始的相对 URL。
```suggestion
模块标识符键不必是单个单词名称（“裸模块的名称”）。它们也可以包含路径分隔符或者以路径分隔符结尾，或者是绝对 URL，或者以 `/`、`./` 或 `../` 开始的相对 URL。
```

2023-04-22 08:59 UTC, yin1999 approved these changes

2023-04-22 08:59 UTC, merged