Update WeakMap, add Symbol
mdn/translated-content pull request #12874
Opened 2023-04-20 16:01 UTC by alattalatta

### Description

`WeakMap`을 업데이트하고, 관련 링크가 많은 `Symbol` 문서를 새로 번역합니다.

### Motivation

- `WeakMap`: 자료 누락 등.
- `Symbol`: 단어집 문서가 옮겨진 후 새로 번역된 적 없음.

### Additional details

심볼일까요, 심벌일까요?

외래어 표기법에 따르면 simb**ə**l이라서 심**벌**이 맞습니다. 의외로 프**런**트엔드 개발자가 맞는 것과 마찬가지인데요, 🤔 예컨대 [NHN Forward](https://forward.nhn.com/2022)에서는 프런트엔드를 사용합니다.

하지만 정작 NHN 채용 사이트에서는 프**론**트엔드를 사용하기도 하고...ㅎ..ㅎㅎ 이미 [관련 논의..?](https://github.com/mdn/translated-content/issues/1042#issuecomment-851807273)가 있었던 거 같으니 심**볼**이 맞겠죠..? (@hochan222)

(추가: 프라미스가 아니라 프로미스로 가는 게 낫겠다고 했던 게 저니까 심볼도 심볼이 맞겠네요)

### Related issues and pull requests

Fixes #12776.

2023-04-20 22:12 UTC, wisedog commented
메가톤급 PR에 맞으니 정신이 혼미합니다.. 왜 저에게 이런 시련이... 🥲

일단 Symbol 문서 여러 개를 번역했던 입장에서, `심벌` 보다는 `심볼` 로 번역하긴 했습니다. 말씀하신대로 논의가 필요한 부분입니다.

2023-04-20 22:13 UTC, wisedog commented
양이 많아서 리뷰는 2차에 거쳐서 하겠습니다. 양해 부탁드릴께요!

2023-04-20 23:33 UTC, wisedog requested changes
다행히 제가 PR 올리신 Symbol 한 달째 작업 중이어서 그나마 쉽게 PR이 가능했습니다.

너무 매끄러운 번역 감사합니다.

2023-04-20 23:33 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/symbol/index.md
> +따라서 개발자가 새로운 심볼 값을 만드는 대신 명시적으로 `Symbol` 래퍼 객체를 생성하는 걸 방지하는데, 일반적으로 다른 원시 데이터 타입들의 래퍼 객체(`new Boolean`, `new String`, `new Number`)는 생성할 수 있다는 점을 생각하면 예상하지 못한 동작일 수도 있습니다.
제가 이 부분 읽을때 조금 어려웠는데 멋진 번역 감사합니다!

2023-04-20 23:33 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/weakmap/index.md
> +`WeakMap`의 키는 반드시 가비지 컬렉션 가능해야 합니다. 대부분의 {{Glossary("Primitive", "원시 값")}}은 임의로 생성될 수 있고 생명 주기가 따로 없으므로 키로 사용할 수 없습니다. 객체와 [등록되지 않은 심볼][]은 가비지 컬렉션 대상이므로 키로 사용할 수 있습니다.
`[등록되지 않은 심볼][]` 도 수정이 필요합니다.

2023-04-21 01:47 UTC, alattalatta commented on files/ko/web/javascript/reference/global_objects/weakmap/index.md
> +**`WeakMap`** 은 키/값 쌍의 모음으로, 키는 반드시 객체 또는 [등록되지 않은 심볼][]이며 값은 임의의 [JavaScript 타입](/ko/docs/Web/JavaScript/Data_structures#javascript의_타입)입니다. `WeakMap`은 키에 대한 강력한 참조를 생성하지 않으므로, 객체가 `WeakMap`의 키에 포함되
레퍼런스 링크 구문입니다! https://github.com/mdn/translated-content/pull/12874/files/54edfe2834ede047477df8e054778c631092c82c#diff-17478d64bbc2bea7c78254fa676659e8859236df7f7d4f322539409e7539f43bR278

ID 프래그먼트 너무 긴데, 또 너무 많이 나와서... [이런 거](https://github.com/mdn/translated-content/pull/12874/commits/d248a5313a607604fe9c6a452429cb5e254a7137) 할 때 유용해요.

2023-04-21 01:56 UTC, alattalatta commented on files/ko/web/javascript/reference/global_objects/symbol/index.md
> +위에서 살펴봤던 `Symbol()` 함수 구문은 프로그램이 종료될 때까지 고유한 채 남는 심볼을 생성합니다. 파일, 그리고 (각각 자신만의 전역 스코프를 갖는) 렐름까지도 걸쳐서 사용 가능한 심볼을 생성하려면 {{jsxref("Symbol.for()")}} 메서드와 {{jsxref("Symbol.keyFor()")}} 메서드를 사용하여 전역 심볼 레지스트
Realm 한국어 문서가 거의 없으니 정하는 대로 가면 될텐데, _영역_은 너무 범용적인 단어라 자신이 없어요. Scope를 예전에는 범위라고 했었는데 요즘은 스코프라고 하는 거랑 비슷한 느낌으로요.

2023-04-21 01:56 UTC, alattalatta commented on files/ko/web/javascript/reference/global_objects/weakmap/index.md
> +`WeakMap`의 키는 반드시 가비지 컬렉션 가능해야 합니다. 대부분의 {{Glossary("Primitive", "원시 값")}}은 임의로 생성될 수 있고 생명 주기가 따로 없으므로 키로 사용할 수 없습니다. 객체와 [등록되지 않은 심볼][]은 가비지 컬렉션 대상이므로 키로 사용할 수 있습니다.
(상동: https://github.com/mdn/translated-content/pull/12874#discussion_r1173227892)

2023-04-21 06:06 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/symbol/index.md
> +위에서 살펴봤던 `Symbol()` 함수 구문은 프로그램이 종료될 때까지 고유한 채 남는 심볼을 생성합니다. 파일, 그리고 (각각 자신만의 전역 스코프를 갖는) 렐름까지도 걸쳐서 사용 가능한 심볼을 생성하려면 {{jsxref("Symbol.for()")}} 메서드와 {{jsxref("Symbol.keyFor()")}} 메서드를 사용하여 전역 심볼 레지스트
하긴.. 저도 어떻게 해야할까 모르겠네요. 사실 문서 이것저것 살펴봤을때도 렐름이라는 단어는 사실 거의 안나와서 .. 이번 건은 일단 렐름 그대도 가도록 할까요?

2023-04-21 06:40 UTC, alattalatta commented on files/ko/web/javascript/reference/global_objects/symbol/index.md
> +위에서 살펴봤던 `Symbol()` 함수 구문은 프로그램이 종료될 때까지 고유한 채 남는 심볼을 생성합니다. 파일, 그리고 (각각 자신만의 전역 스코프를 갖는) 렐름까지도 걸쳐서 사용 가능한 심볼을 생성하려면 {{jsxref("Symbol.for()")}} 메서드와 {{jsxref("Symbol.keyFor()")}} 메서드를 사용하여 전역 심볼 레지스트
https://www.microsoft.com/ko-kr/language/Search?&searchTerm=realm&langID=457&Source=true&productid=0

요즘 MS는 너무 기계번역을 남발해서 좀 그렇지만..? 그래도 사전에 영역이라고 되어있긴 하니까 저는 어느 쪽이건 상관 없을 거 같아요

2023-04-21 07:49 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/symbol/index.md
> +위에서 살펴봤던 `Symbol()` 함수 구문은 프로그램이 종료될 때까지 고유한 채 남는 심볼을 생성합니다. 파일, 그리고 (각각 자신만의 전역 스코프를 갖는) 렐름까지도 걸쳐서 사용 가능한 심볼을 생성하려면 {{jsxref("Symbol.for()")}} 메서드와 {{jsxref("Symbol.keyFor()")}} 메서드를 사용하여 전역 심볼 레지스트
일단 그대로 가겠습니다.

2023-04-21 07:49 UTC, wisedog approved these changes

2023-04-21 07:49 UTC, merged

2023-05-01 14:11 UTC, hochan222 commented
> 하지만 정작 NHN 채용 사이트에서는 프론트엔드를 사용하기도 하고...ㅎ..ㅎㅎ 이미 관련 논의가 있었던 거 같으니 심볼이 맞겠죠..?

그당시 사용 빈도수만 비교해서 정했습니다. MDN 문서가 대부분의 경우 표준으로 인식되고 있고, 현재 시점에서 다시 논의를 한다면 **국립국어원을 기준** 삼아 프런트엔드가 좋다는 의견을 드릴것 같아요. ([국립국어원 프론트엔드 vs 프런트엔드](https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=257365&pageIndex=9))

말씀해주신 사례들로인해 우선은 [용어 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md#%EC%9A%A9%EC%96%B4-%EC%95%88%EB%82%B4%EC%84%9C)에서 아래와 같이 **"권장합니다"로** 첫 문장을 작성했습니다.

> 새로운 용어를 추가할 때, 기존 문서의 레거시와 [국립 국어원 한국어 어문 규범](https://kornorms.korean.go.kr/main/main.do)을 고려해 추가할 것을 권장합니다. [국립 국어원 온라인가나다](https://www.korean.go.kr/front/onlineQna/onlineQnaList.do?mn_id=216)에서 어문 규범, 어법, 표준국어대사전 내용 등에 대하여 문의할 수 있습니다.

표준으로 인식되고 있는 문서인 만큼 국립 국어원을 따를지, 더 널리 알려진 표현으로 사용할지 고민이 항상 됩니다. (우선은 그대로 두고 추후 누군가 의견을 주실때, 양측 의견이 비등비등하다면 국립 국어원 손을 들어줄 예정입니다.)

모두 좋은 하루 보내세요 :)

(cc @alattalatta 님, @wisedog 님, @mdn/yari-content-ko)