[zh-cn]: Update the translation of Array.join and Array.lastIndexOf
mdn/translated-content pull request #12873
Opened 2023-04-20 14:54 UTC by JasonLamv-t

### Description

Update the translations of `Array.join()` and `Array.lastIndexOf()`.

### Motivation

Ditto.

### Additional details

🈚️

2023-04-21 05:38 UTC, yin1999 requested changes

2023-04-21 05:38 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/lastindexof/index.md
> +  - 以 0 起始的索引，表明反向搜索的起始位置，[会被转换为整数](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Number#整数转换)。
这两段是一起的

![image](https://user-images.githubusercontent.com/15844309/233549244-17e2cd00-5855-42f9-93fa-ddfe62ce63da.png)

2023-04-21 05:38 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/lastindexof/index.md
> +The `lastIndexOf()` method is [generic](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#generic_array_methods). It only expects the `this` value to have a `length` property and integer-keye
英文

2023-04-21 06:03 UTC, coolzjy commented on files/zh-cn/web/javascript/reference/global_objects/array/lastindexof/index.md
> +### 使用 lastIndexOf
```suggestion
### 使用 lastIndexOf()
```

2023-04-21 06:06 UTC, coolzjy commented on files/zh-cn/web/javascript/reference/global_objects/array/lastindexof/index.md
> +### 查找所有元素
```suggestion
### 查找元素出现的所有位置
```

2023-04-22 14:55 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/lastindexof/index.md
> +  - 以 0 起始的索引，表明反向搜索的起始位置，[会被转换为整数](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Number#整数转换)。
最好在本地预览一下 markdown 文件，https://github.com/mdn/translated-content#content-repo-setup

```suggestion
  - : 以 0 起始的索引，表明反向搜索的起始位置，[会被转换为整数](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Number#整数转换)。
```

2023-04-22 15:00 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/lastindexof/index.md
请不要再保留“译者注”这一部分内容了。如果英文原文不够好，我们应该修改英文文档的说明，而不是在中文文档中添加“译者注”这一个补丁。这会让文档变得难以维护，且难以将一些好的 建议反馈到英文文档中，从而间接改善其他本地化文档的内容。

2023-04-23 00:29 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/lastindexof/index.md
>  `idx > 0`时，才进入 lastIndexOf 由后往前移一位进行倒查找；如果`idx == 0`则直接设置`idx = -1`，循环`while (idx != -1)`就结束了。
```suggestion
```

2023-04-23 00:32 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/array/lastindexof/index.md
> +`lastIndexOf` 使用[严格相等](zh-CN/docs/Web/JavaScript/Reference/Operators/Strict_equality)（与 `===` 运算符使用的算法相同）比较 `searchElement` 和数组中的元素。[`NaN`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/NaN) 值不
```suggestion
`lastIndexOf` 使用[严格相等](zh-CN/docs/Web/JavaScript/Reference/Operators/Strict_equality)（与 `===` 运算符使用的算法相同）比较 `searchElement` 和数组中的元素。[`NaN`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/NaN) 值永远不会被认为是相等的，因此当 `searchElement` 为 `NaN` 时 `lastIndexOf()` 总是返回 `-1`。
```

2023-04-23 01:16 UTC, yin1999 approved these changes

2023-04-23 01:16 UTC, merged