[ja] (WIP) JavaScript/Reference/Statements/import の更新
mdn/translated-content pull request #12899
Opened 2023-04-22 08:35 UTC by igrep

### Description

https://github.com/mozilla-japan/translation/issues/685 の指摘をきっかけに、 https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/import のページが最新の原文に追いついていないことが分かったので更新しています。

### Additional details

最新の原文: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
参照時点におけるソースコード: https://github.com/mdn/content/blob/ab19b16083a8cafc5b060ac3de05a426b226e245/files/en-us/web/javascript/reference/statements/import/index.md

### Related issues and pull requests

Fix https://github.com/mozilla-japan/translation/issues/685

2023-05-06 05:44 UTC, mfuji09 commented
@igrep さん
前回のコミットから時間が経っていますが、このまま続けますか？

2023-05-06 08:09 UTC, igrep commented
> @igrep さん
> 前回のコミットから時間が経っていますが、このまま続けますか？

次回の翻訳ミートアップの時に続きを書く予定ですので、続けさせていただきたいです。🙇

2023-05-20 15:03 UTC, mfuji09 requested changes
指摘事項を確認のうえ、対応をお願いします。

2023-05-20 15:03 UTC, mfuji09 commented on files/ja/web/javascript/reference/statements/import/index.md
> +ソースファイルの中で`import`宣言を使用するためには、ランタイムがそのファイルを[モジュール](/ja/docs/Web/JavaScript/Guide/Modules)と見なす必要があります。HTMLでは、{{HTMLElement("script")}}タグに `type="module"` を加えることがこれに相当します。モジュールは、宣言するかどうかにかかわらず、{{JSxRef
日本語と英数字の間には、半角空白を空けてください。この記事内の他の部分も同様です。

2023-05-20 15:03 UTC, mfuji09 commented on files/ja/web/javascript/reference/statements/import/index.md
> +> **注意:** `import { x, y } from "mod"` は、 `import defaultExport from "mod"` して `defaultExport` から `x` と `y` を分割代入することと等価ではありません。名前付きのインポートとデフォルトのインポートは JavaScript のモジュールにおける別種の構文です。
`**注意:**` ではなく `**メモ:**` と訳してください。この文字列自体に意味があるため、他の文字列にすると正しく整形されません。

2023-05-21 00:44 UTC, igrep commented on files/ja/web/javascript/reference/statements/import/index.md
> +ソースファイルの中で`import`宣言を使用するためには、ランタイムがそのファイルを[モジュール](/ja/docs/Web/JavaScript/Guide/Modules)と見なす必要があります。HTMLでは、{{HTMLElement("script")}}タグに `type="module"` を加えることがこれに相当します。モジュールは、宣言するかどうかにかかわらず、{{JSxRef
すみません、読点の直後は空けないものと勝手に思い込んでました。直します。

2023-05-28 06:13 UTC, debiru commented on files/ja/web/javascript/reference/statements/import/index.md
> +ソースファイルの中で`import`宣言を使用するためには、ランタイムがそのファイルを[モジュール](/ja/docs/Web/JavaScript/Guide/Modules)と見なす必要があります。HTMLでは、{{HTMLElement("script")}}タグに `type="module"` を加えることがこれに相当します。モジュールは、宣言するかどうかにかかわらず、{{JSxRef
https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline#%E7%B4%84%E7%89%A9%E3%81%AE%E8%A1%A8%E8%A8%98

> 句読点、カギ括弧などの日本語 [約物](http://ja.wikipedia.org/wiki/%E7%B4%84%E7%89%A9) と英数字が隣接する場合は半角スペースを挿入しない。

句読点の直後の半角スペースは付けないことになっていると認識しています。しかし @mfuji09 さんの作業履歴を拝見するとしばしば付けられているようですね。付けてもよいポリシーなのかどうかは気になっていたところです。

> 中で`import`宣言を

> あります。HTMLでは、

`import`, `HTML` の部分にスペースがないことを指摘しているのかと思いました。

2023-06-24 04:37 UTC, igrep commented on files/ja/web/javascript/reference/statements/import/index.md
> +ソースファイルの中で`import`宣言を使用するためには、ランタイムがそのファイルを[モジュール](/ja/docs/Web/JavaScript/Guide/Modules)と見なす必要があります。HTMLでは、{{HTMLElement("script")}}タグに `type="module"` を加えることがこれに相当します。モジュールは、宣言するかどうかにかかわらず、{{JSxRef
ありがとうございます。改めて見たら他にもスペースを入れ損ねている箇所がありましたね...
https://github.com/mdn/translated-content/pull/12899/commits/bc1c2dcbd0081a45ea557c30d85ad4b80d78c585 ですべて修正できたはずです。

2023-07-16 01:51 UTC, igrep commented
@mfuji09 ping

2023-07-16 04:27 UTC, mfuji09 commented
@igrep さん
ping の意味を測りかねますが、もし修正が終わったのであれば、右上の Reviewers のところで Re-request review ボタンを押していただければと思います。

2023-07-16 05:02 UTC, igrep commented
すみません。了解です

2023-07-16 07:17 UTC, mfuji09 requested changes
原文が更新されているので、それに合わせた修正をお願いします。

指摘点以外に、`## 関連情報` の節も原文が更新されていますので、反映をお願いします。

また、末尾にある `## ブラウザー実装状況` の見出しは、マクロから `## ブラウザーの互換性` という名前で参照されているので、他の記事に合わせてください。

以上、よろしくお願いいたします。

2023-07-16 07:17 UTC, mfuji09 commented on files/ja/web/javascript/reference/statements/import/index.md
> +`import` 宣言には4つの形式があります:
英数字の前後には半角スペースを入れてください。
```suggestion
`import` 宣言には 4 つの形式があります:
```

2023-07-16 07:17 UTC, mfuji09 commented on files/ja/web/javascript/reference/statements/import/index.md
> +静的な **`import`** 宣言は、他のモジュールによって[エクスポート](/ja/docs/Web/JavaScript/Reference/Statements/export)された読み込み専用のライブバインディングをインポートするために使用します。インポートしたバインディングは、バインディングをエクスポートしたモジュールによって更新される一方、インポートしているモジュールによって再代
原文では「バインディング」が用語集へのリンクになっていますので、合わせてください。

2023-07-16 07:17 UTC, mfuji09 commented on files/ja/web/javascript/reference/statements/import/index.md
> +`import` 宣言は構文的に硬直したものとなっています。例えば、文字列リテラルしか指定子に使えなかったり、トップレベルでしか使用できなかったり、すべてのバインディングが識別子でなければならない、といった制限があります。この制限により、モジュールは評価する前に静的に解析してリンクさせることができます。これはモジュールを非同期にロードする上で鍵となる性質で、[トップレベル await](/ja/
原文では、この段落の前に段落が追加されていますので、合わせてください。

2023-07-16 08:55 UTC, igrep commented
@mfuji09 
> 原文が更新されているので、それに合わせた修正をお願いします。

了解です。その場合、`sourceCommit`も更新した方がよいでしょうか？

2023-07-16 15:02 UTC, mfuji09 commented
@igrep さん

> 了解です。その場合、`sourceCommit`も更新した方がよいでしょうか？

はい、更新してください。

2023-07-18 14:50 UTC, mfuji09 approved these changes
OKです。

2023-07-18 14:50 UTC, merged