Update /Web/API/WebGLRenderingContext/enableVertexAttribArray
mdn/translated-content pull request #12969
Opened 2023-04-25 02:02 UTC by Gerocer

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-04-25 06:58 UTC, yin1999 requested changes

2023-04-25 06:58 UTC, yin1999 commented on files/zh-cn/web/api/webglrenderingcontext/enablevertexattribarray/index.md
> +在[WebGL API](/zh-CN/docs/Web/API/WebGL_API)中，使用 {{domxref("WebGLRenderingContext")}} 中的 **`enableVertexAttribArray()`** 方法，会启用指定索引位置的通用顶点属性数组，让其在渲染时生效。
目前的翻译与英文文档并不一致

![image](https://user-images.githubusercontent.com/15844309/234198150-00f8338b-1631-4d40-b90a-b78e9d5e1703.png)

2023-04-25 06:58 UTC, yin1999 commented on files/zh-cn/web/api/webglrenderingcontext/enablevertexattribarray/index.md
> +无论怎样，都需要你使用`enableVertexAttribArray()`方法，来激活每一个属性以便使用，不被激活的属性是不会被使用的。一旦激活，以下其他方法就可以获取到属性的值了，包括{{domxref("WebGLRenderingContext.vertexAttribPointer", "vertexAttribPointer()")}}，{{domxref("WebGLRenderi
注意一下，这里有星号是没问题的，这是四种方法的通配符

```js
vertexAttrib1f(index, v0)
vertexAttrib2f(index, v0, v1)
vertexAttrib3f(index, v0, v1, v2)
vertexAttrib4f(index, v0, v1, v2, v3)
```

2023-04-25 06:58 UTC, yin1999 commented on files/zh-cn/web/api/webglrenderingcontext/enablevertexattribarray/index.md
> +None ({{jsxref("undefined")}}).
```suggestion
无（{{jsxref("undefined")}}）。
```

2023-04-25 07:04 UTC, Gerocer commented on files/zh-cn/web/api/webglrenderingcontext/enablevertexattribarray/index.md
> +在[WebGL API](/zh-CN/docs/Web/API/WebGL_API)中，使用 {{domxref("WebGLRenderingContext")}} 中的 **`enableVertexAttribArray()`** 方法，会启用指定索引位置的通用顶点属性数组，让其在渲染时生效。
我认为是符合实际意义的

2023-04-25 07:05 UTC, Gerocer commented on files/zh-cn/web/api/webglrenderingcontext/enablevertexattribarray/index.md
> +无论怎样，都需要你使用`enableVertexAttribArray()`方法，来激活每一个属性以便使用，不被激活的属性是不会被使用的。一旦激活，以下其他方法就可以获取到属性的值了，包括{{domxref("WebGLRenderingContext.vertexAttribPointer", "vertexAttribPointer()")}}，{{domxref("WebGLRenderi
好的

2023-04-25 07:16 UTC, yin1999 commented on files/zh-cn/web/api/webglrenderingcontext/enablevertexattribarray/index.md
> +在[WebGL API](/zh-CN/docs/Web/API/WebGL_API)中，使用 {{domxref("WebGLRenderingContext")}} 中的 **`enableVertexAttribArray()`** 方法，会启用指定索引位置的通用顶点属性数组，让其在渲染时生效。
英文文档中并没有“让其在渲染时生效”这句话，如果你觉得英文文档的内容是不完整的，也请先给英文文档提交 PR。中文文档只是对英文文档的翻译。我们也希望在维护中文文档的同时，可以有相应的给英文文档的反馈。

2023-04-25 07:24 UTC, Gerocer commented on files/zh-cn/web/api/webglrenderingcontext/enablevertexattribarray/index.md
> +在[WebGL API](/zh-CN/docs/Web/API/WebGL_API)中，使用 {{domxref("WebGLRenderingContext")}} 中的 **`enableVertexAttribArray()`** 方法，会启用指定索引位置的通用顶点属性数组，让其在渲染时生效。
好的，已修改。

2023-04-26 00:56 UTC, yin1999 commented on files/zh-cn/web/api/webglrenderingcontext/enablevertexattribarray/index.md
> +无论怎样，都需要你使用`enableVertexAttribArray()`方法，来激活每一个属性以便使用，不被激活的属性是不会被使用的。一旦激活，以下其他方法就可以获取到属性的值了，包括{{domxref("WebGLRenderingContext.vertexAttribPointer", "vertexAttribPointer()")}}，{{domxref("WebGLRenderi
```suggestion
无论怎样，都需要你使用 `enableVertexAttribArray()` 方法，来激活每一个属性以便使用，不被激活的属性是不会被使用的。一旦激活，以下其他方法就可以获取到属性的值了，包括{{domxref("WebGLRenderingContext.vertexAttribPointer", "vertexAttribPointer()")}}、{{domxref("WebGLRenderingContext.vertexAttrib", "vertexAttrib*()")}} 和 {{domxref("WebGLRenderingContext.getVertexAttrib", "getVertexAttrib()")}}。
```

2023-04-26 00:57 UTC, yin1999 commented on files/zh-cn/web/api/webglrenderingcontext/enablevertexattribarray/index.md
> +在[WebGL API](/zh-CN/docs/Web/API/WebGL_API)中，使用 {{domxref("WebGLRenderingContext")}} 中的 **`enableVertexAttribArray()`** 方法，可以打开属性数组列表中指定索引处的通用顶点属性数组。
```suggestion
在 [WebGL API](/zh-CN/docs/Web/API/WebGL_API) 中，使用 {{domxref("WebGLRenderingContext")}} 中的 **`enableVertexAttribArray()`** 方法，可以打开属性数组列表中指定索引处的通用顶点属性数组。
```

2023-04-26 00:58 UTC, yin1999 approved these changes

2023-04-26 01:00 UTC, merged

2023-04-26 01:01 UTC, yin1999 commented
如果没有冲突，不需要经常合并主分支到 PR 所属分支

2023-04-26 01:02 UTC, Gerocer commented
感谢指正。