/docs/Web/JavaScript/Reference/Global_Objects/Object/keys 문서 추가
mdn/translated-content pull request #1297
Opened 2021-06-24 07:07 UTC by EchoHertz

[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys](url)
문서를 번역하여 추가 PR 드립니다.

검토, 승인 부탁드리겠습니다.

2021-06-24 16:15 UTC, cos18 requested changes
번역 감사드립니다. [가이드 문서](https://github.com/mdn/translated-content/blob/main/docs/ko/translation-guide.md)에 이번 리뷰 리퀘스트에 요청드린 사항들이 적혀있으니 시간나실때 읽어보시길 바라곘습니다.

또한, PR을 올리시기 전에 yari를 실행하셔서 작성하신 문서를 확인해보시고 flaw등을 확인해주시면 감사드리겠습니다. yari에 대한 사용법도 가이드라인에 간단히 작성되어 있습니다.

2021-06-27 07:22 UTC, EchoHertz commented on files/ko/web/javascript/reference/global_objects/object/keys/index.html
> +     동일한 순서로 반복되는 열거 가능한 배열로 반환합니다.
@cos18 
용어 지침에 보면 **Enumerated**는 열거형 이라 지침되어있습니다.
고로 **enumerable property names** 해당 내용을 열거 가능한이라고 번역했는데 혹시 이에 대해 이슈가 있나요??

그리고 제 타 문서들을 읽어본 경험을 바탕으로 Enumerable은 "열거 가능한"으로 번역 하는게 맞지 않을까 싶어 답변 드립니다.

아래에 비슷인이슈로 열거 -> 순회로 suggestion 들어온 이슈에 대해도 한번 더 재고 부탁드리겠습니다.

2021-06-27 08:34 UTC, EchoHertz commented on files/ko/web/javascript/reference/global_objects/object/keys/index.html
> +    {{jsxref("Object.getOwnPropertyNames()")}}.</p>
괄호 오타인지 한번 더 확인 부탁드려도 될까요? 중괄호 기준으로 {{}} 로 되어 있습니다.

추가로, 제가 en-us 기준으로 번역을 진행중인데, 해당 문서에는 
`{{jsxref("Object.getOwnPropertyNames()")}}.`
로 사용중입니다. 원문이 오타인지 확인 부탁드리겠습니다.

2021-06-27 08:45 UTC, EchoHertz commented
Flaw 확인하여 수정 완료했습니다.
참조하고 있는 레퍼런스 파일들, 기존에는 ko 로 번역된 파일이 없어 us-en으로 리디렉트 되고 있었습니다.

해당 이슈 우선 번역되지 않은 파일 업로드 해놓음으로서 flaw 제거 했습니다. 만약 이번 PR에 해당 문서까지 번역 필요하면, 추가로 번역 진행할 예정입니다.

2021-06-28 07:39 UTC, cos18 commented on files/ko/web/javascript/reference/global_objects/object/keys/index.html
> +     동일한 순서로 반복되는 열거 가능한 배열로 반환합니다.
@EchoHertz 리뷰 당시 제가 실수로 enumerate와 iterate를 햇갈렸나 보네요. 이에 대해 잘못 리뷰드려 죄송합니다. 열거에 대한 번역은 그대로 두셔도 괜찮을 것 같습니다.

추가로 iterate에 대해서는 "순회"로 수정해주시면 감사드리겠습니다.

2021-06-28 07:42 UTC, cos18 commented on files/ko/web/javascript/reference/global_objects/object/keys/index.html
> +    {{jsxref("Object.getOwnPropertyNames()")}}.</p>
@EchoHerz 해당 내용 역시 리뷰 당시 잘못 보게된 내용인 것 같습니다. 오타가 아님을 확인했습니다.

2021-06-28 07:52 UTC, cos18 requested changes
다시한번 이전 리뷰에서 용어 실수가 있어 죄송합니다. 리뷰 항목 참고하셔서 수정 부탁드립니다.

추가로, 수정을 요청한 내용을 모두 완료하셨다면 리뷰를 rerequest 해주시면 감사드리겠습니다. rerequest를 하셔야 리뷰어에게 알림도 오고 기여자분께서 PR 수정을 완료했다는 걸 알 수 있습니다.

2021-06-28 07:52 UTC, cos18 commented on files/ko/web/javascript/reference/global_objects/object/getownpropertynames/index.html
> +---
해당 문서가 없어서 생긴 flaw는 수정하지 않으셔도 됩니다. 해당 flaw가 있어도 yari에서 한국 문서가 없는 경우 영어 문서로 연결해줍니다.

현재 이 문서를 추가한다고 하면 해당 문서는 한국어 문서로 간주되기 때문에 문제가 될 수 있습니다. 해당 파일 지워주시면 감사드리겠습니다.

2021-06-28 07:52 UTC, cos18 commented on files/ko/web/javascript/reference/global_objects/object/keys/index.html
> +     동일한 순서로 반복되는 열거 가능한 배열로 반환합니다.
```suggestion
     동일한 순서로 순회되는 열거할 수 있는 배열로 반환합니다.
```
"열거 가능한" 이라는 말이 번역체스러운 것 같습니다.

2021-06-28 07:52 UTC, cos18 commented on files/ko/web/javascript/reference/global_objects/object/keys/index.html
> +  <dd>열거 가능한 속성 이름들을 반환 받을 객체</dd>
```suggestion
  <dd>열거할 수 있는 속성 이름들을 반환 받을 객체</dd>
```

2021-06-28 07:52 UTC, cos18 commented on files/ko/web/javascript/reference/global_objects/object/keys/index.html
> +<p>전달된 객체의 열거 가능한 모든 속성 이름들을 나타내는 문자열 배열
```suggestion
<p>전달된 객체의 열거할 수 있는 모든 속성 이름들을 나타내는 문자열 배열
```

2021-06-28 07:52 UTC, cos18 commented on files/ko/web/javascript/reference/global_objects/object/keys/index.html
> +<p><code>Object.keys()</code> 는 전달된 객체에서 직접 찾은 열거 가능한 속성 이름에 해당하는 문자열 배열을 반환합니다.
```suggestion
<p><code>Object.keys()</code> 는 전달된 객체에서 직접 찾은 열거할 수 있는 속성 이름에 해당하는 문자열 배열을 반환합니다.
```

2021-06-28 07:52 UTC, cos18 commented on files/ko/web/javascript/reference/global_objects/object/keys/index.html
> +// getFoo 는 열거 가능하지 않은 속성입니다.
```suggestion
// getFoo 는 열거할 수 없는 속성입니다.
```

2021-06-28 07:52 UTC, cos18 commented on files/ko/web/javascript/reference/global_objects/object/keys/index.html
> +<p>만약 열거 가능하지 않은 속성도 포함한 속성 이름들을 원한다면, 다음을 참고할 수 있습니다.
```suggestion
<p>만약 열거할 수 없는 속성도 포함한 속성 이름들을 원한다면, 다음을 참고할 수 있습니다.
```

2021-06-29 00:35 UTC, EchoHertz commented
수정해서 다시 request 요청 드렸습니다. 확인 부탁드립니다 ^^

2021-06-29 03:44 UTC, EchoHertz commented
@cos18 
제 실수로 getOwnPropertyNames 까지 해당 PR에 포함되 버렸습니다.

해당 내용까지 확인 부탁드리겠습니다..!!

2021-06-30 16:24 UTC, cos18 requested changes
어쩌다 보니 getOwnPropertyNames 문서까지 번역해주셔서 감사합니다! 이전에 리뷰드린 keys 문서는 더이상 문제가 없는 것 같고, 새로 번역한 문서에서 몇가지 수정 / 조언드린 점이 있어 리뷰드립니다.

2021-06-30 16:24 UTC, cos18 commented on files/ko/web/javascript/reference/global_objects/object/getownpropertynames/index.html
> +    배열의 열거할 수 있는 속성들의 순서는 {{jsxref("Statements/for...in", "for...in")}} 반복문 (또는 {{jsxref("Object.keys()")}})의 결과 값과 일치합니다.
```suggestion
    배열의 열거할 수 있는 속성들의 순서는 {{jsxref("Statements/for...in", "for...in")}} 반복문 (또는 {{jsxref("Object.keys()")}})이 처리되는 순서와 일치합니다.
```
"결과" 보단 "순서"가 더 원문 의미와 맞는 것 같습니다.

2021-06-30 16:24 UTC, cos18 commented on files/ko/web/javascript/reference/global_objects/object/getownpropertynames/index.html
> +<p>만약 열거 가능 한 속성만 사용한다면, {{jsxref("Object.keys()")}} 또는 {{jsxref("Statements/for...in", "for...in")}} 반복문을 사용하는걸 권장합니다.
```suggestion
<p>만약 열거 가능한 속성만 사용한다면, {{jsxref("Object.keys()")}} 또는 {{jsxref("Statements/for...in", "for...in")}} 반복문을 사용하는걸 권장합니다.
```

2021-06-30 16:24 UTC, cos18 commented on files/ko/web/javascript/reference/global_objects/object/getownpropertynames/index.html
> +    (이는 객체의 프로토타입 체인을 먼저 사용하여 열거 가능 한 속성을 반환합니다. 단, {{jsxref("Object.prototype.hasOwnProperty()", "hasOwnProperty()")}}에 필터 됩니다.)
```suggestion
    (이는 객체의 프로토타입 체인을 먼저 사용하여 열거 가능한 속성을 반환합니다. 단, 후자는{{jsxref("Object.prototype.hasOwnProperty()", "hasOwnProperty()")}}에 필터 됩니다.)
```
원문의 `latter` 의미가 빠져있습니다.

2021-06-30 16:24 UTC, cos18 commented on files/ko/web/javascript/reference/global_objects/object/getownpropertynames/index.html
> +<p>이 방법은 열거 가능한 키를 없애기 위해서 {{jsxref("Array.prototype.filter()")}} 함수를 사용합니다. {{jsxref("Object.keys()")}} 을 통해 얻은 키 배열을 <code>Object.getOwnPropertyNames()</code> 을 통해 얻은 키 배열에 필터링하여 열거할 수 없는 키 배열들만 출력
```suggestion
<p>이 방법은 {{jsxref("Array.prototype.filter()")}} 함수를 사용해 (<code>Object.getOwnPropertyNames()</code> 을 통해 얻은) 모든 키 중 ({{jsxref("Object.keys()")}} 을 통해 얻은) 열거 가능한 키들을 제거하여 열거할 수 없는 키들만 출력합니다.</p>
```
원문에서 한 문장인 문장이 두 문장으로 나누어져있습니다. 원문에 맞게 재해석했습니다.

2021-07-01 00:34 UTC, EchoHertz commented on files/ko/web/javascript/reference/global_objects/object/getownpropertynames/index.html
> +<p>이 방법은 열거 가능한 키를 없애기 위해서 {{jsxref("Array.prototype.filter()")}} 함수를 사용합니다. {{jsxref("Object.keys()")}} 을 통해 얻은 키 배열을 <code>Object.getOwnPropertyNames()</code> 을 통해 얻은 키 배열에 필터링하여 열거할 수 없는 키 배열들만 출력
오 깔끔하네요 ^^

2021-07-01 00:38 UTC, EchoHertz reviewed
리뷰 감사합니다.

해당 리뷰와 남겨주신대로 변경사항 반영됐습니다.

추가 리뷰 부탁드리겠습니다.

2021-07-01 07:00 UTC, cos18 approved these changes
LGTM 😄

2021-07-01 07:03 UTC, merged