fix(zh-cn): Correct the wrong link address in `webgl_api/tutorial`
mdn/translated-content pull request #13019
Opened 2023-04-28 06:44 UTC by lastnigtic

…hting_in_webgl`

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-04-28 15:11 UTC, jasonren0403 requested changes

2023-04-28 15:11 UTC, jasonren0403 commented on files/zh-cn/web/api/webgl_api/tutorial/lighting_in_webgl/index.md
> +[View the complete code](https://github.com/mdn/dom-examples/tree/main/webgl-examples/tutorial/sample7) | [Open this demo on a new page](https://mdn.github.io/webgl-examples/webgl-examples/tutorial/s
可以顺便翻译一下
```suggestion
[查看完整代码](https://github.com/mdn/dom-examples/tree/main/webgl-examples/tutorial/sample7) | [在新页面中打开示例](https://mdn.github.io/dom-examples/webgl-examples/tutorial/sample7/)
```

2023-04-29 01:33 UTC, lastnigtic commented on files/zh-cn/web/api/webgl_api/tutorial/lighting_in_webgl/index.md
> +[View the complete code](https://github.com/mdn/dom-examples/tree/main/webgl-examples/tutorial/sample7) | [Open this demo on a new page](https://mdn.github.io/webgl-examples/webgl-examples/tutorial/s
好的，也翻译了，liveSample的地址也改了

2023-04-29 06:26 UTC, yin1999 approved these changes
Thanks. Welcome aboard 🎉

2023-04-29 06:30 UTC, merged