sync latest document of English
mdn/translated-content pull request #13414
Opened 2023-05-26 09:56 UTC by imaxue

### update Server-sent_events

### Motivation

### Additional details

### Related issues and pull requests

2023-05-26 10:47 UTC, skyclouds2001 commented on files/zh-cn/web/api/server-sent_events/index.md
> +> **注意：** Firefox 不能在 service workers 正常支持服务端事件（但支持在 Dedicated Worker 和 Shared Worker 中使用）。参见 [Firefox bug 1681218](https://bugzil.la/1681218).
```suggestion
> **注意：** Firefox 不能在 service workers 正常支持服务端事件（但支持在 Dedicated Worker 和 Shared Worker 中使用）。参见 [Firefox bug 1681218](https://bugzil.la/1681218)。
```

2023-05-26 10:47 UTC, skyclouds2001 commented on files/zh-cn/web/api/server-sent_events/using_server-sent_events/index.md
> +title: 使用服务器事件
server-sent 直接翻译为 服务器 感觉不太合适

2023-05-26 10:47 UTC, skyclouds2001 commented on files/zh-cn/web/api/server-sent_events/using_server-sent_events/index.md
>  你也可以使用`addEventListener()`方法来监听其他类型的事件：
```suggestion
你也可以使用 `addEventListener()` 方法来监听其他类型的事件：
```

2023-05-26 10:47 UTC, skyclouds2001 commented on files/zh-cn/web/api/server-sent_events/index.md
> +> **注意：** Firefox 不能在 service workers 正常支持服务端事件（但支持在 Dedicated Worker 和 Shared Worker 中使用）。参见 [Firefox bug 1681218](https://bugzil.la/1681218).
```suggestion
> **备注：** Firefox 不能在 service workers 正常支持服务端事件（但支持在 Dedicated Worker 和 Shared Worker 中使用）。参见 [Firefox bug 1681218](https://bugzil.la/1681218).
```

2023-05-26 10:47 UTC, skyclouds2001 commented on files/zh-cn/web/api/server-sent_events/index.md
> +> **注意：** Firefox 不能在 service workers 正常支持服务端事件（但支持在 Dedicated Worker 和 Shared Worker 中使用）。参见 [Firefox bug 1681218](https://bugzil.la/1681218).
note 应该译为 备注 才可以正常地显示

2023-05-26 10:47 UTC, skyclouds2001 commented on files/zh-cn/web/api/server-sent_events/index.md
>  - 一个使用 server-sent events 的、类似 [Twitter](http://hacks.mozilla.org/2011/06/a-wall-powered-by-eventsource-and-server-sent-events/) 的应用程序，代码存放在这里：[Github](https://github.com/mozilla/webowonder-demos/tre
```suggestion
- 一个使用 server-sent events 的、类似 [Twitter](http://hacks.mozilla.org/2011/06/a-wall-powered-by-eventsource-and-server-sent-events/) 的应用程序，代码存放在这里：[Github](https://github.com/mozilla/webowonder-demos/tree/master/demos/friends%20timeline)
```

2023-05-26 12:25 UTC, jasonren0403 commented
参考<https://dorado.w3.org/archives/786/>，Server-sent events大可译为“服务器发送事件”or“服务器推送事件”

![image](https://github.com/mdn/translated-content/assets/40999116/4590e3a5-5ae5-44d6-be95-63ea4e417d16)

2023-05-26 14:47 UTC, skyclouds2001 commented on files/zh-cn/web/api/server-sent_events/using_server-sent_events/index.md
> +title: 使用服务器事件
参见 https://github.com/mdn/translated-content/pull/13414#issuecomment-1564315535

2023-05-28 07:38 UTC, jasonren0403 requested changes
some suggestions

2023-05-28 07:38 UTC, jasonren0403 commented on files/zh-cn/web/api/server-sent_events/using_server-sent_events/index.md
> +#### 纯数据 messages
有很多地方需要注意复数形式转换，参见 https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md#复数形式

```suggestion
#### 纯数据 message
```

2023-05-28 07:38 UTC, jasonren0403 commented on files/zh-cn/web/api/server-sent_events/using_server-sent_events/index.md
> +> **备注：** 您可以在 github 上找到以上代码的完整示例 —— 参见 [Simple SSE demo using PHP](https://github.com/mdn/dom-examples/tree/main/server-sent-events)。
```suggestion
> **备注：** 你可以在 GitHub 上找到以上代码的完整示例——参见[使用 PHP 语言的简单 SSE 示例](https://github.com/mdn/dom-examples/tree/main/server-sent-events)。
```

2023-05-28 07:38 UTC, jasonren0403 commented on files/zh-cn/web/api/server-sent_events/using_server-sent_events/index.md
> +当发生错误（例如请求超时或与[访问控制](/zh-CN/docs/Web/HTTP/CORS)有关的问题），会生成一个错误事件。您可以通过在 `EventSource` 对象上使用 `onerror` 回调来对此采取措施：
```suggestion
当发生错误时（例如网络超时或与[访问控制](/zh-CN/docs/Web/HTTP/CORS)有关的问题），会生成一个错误事件。可以通过在 `EventSource` 对象上实现 `onerror` 回调来编程地处理它：
```

2023-05-28 07:38 UTC, jasonren0403 commented on files/zh-cn/web/api/server-sent_events/using_server-sent_events/index.md
> +服务器端发送事件的脚本需要响应的内容应该使用值为 `text/event-stream` 的 MIME 类型。每个通知以文本块形式发送，并以一对换行符结尾。有关事件流的格式的详细信息，请参见[事件流格式](#事件流格式)。
```suggestion
发送事件的服务器端脚本需要使用 `text/event-stream` MIME 类型响应内容。每个通知以文本块形式发送，并以一对换行符结尾。有关事件流的格式的详细信息，请参见[事件流格式](#事件流格式)。
```

2023-05-28 07:38 UTC, jasonren0403 commented on files/zh-cn/web/api/server-sent_events/using_server-sent_events/index.md
> +服务器事件 API 包含在 {{domxref("EventSource")}} 接口中
```suggestion
服务端推送事件 API 包含在 {{domxref("EventSource")}} 接口中。
```

2023-05-28 07:38 UTC, jasonren0403 commented on files/zh-cn/web/api/server-sent_events/using_server-sent_events/index.md
> +开发一个使用[服务器事件](/zh-CN/docs/Web/API/Server-sent_events)的 Web 应用程序是很容易的。你只需要在服务器上编写一些代码将事件流传输到前端，而客户端的代码在处理传入事件部分几乎与 [websockets](/zh-CN/docs/Web/API/WebSockets_API) 相同。需要注意这是一个单向的连接，所以你不能从客户端发送事件到服务器。
```suggestion
开发一个使用[服务端推送事件](/zh-CN/docs/Web/API/Server-sent_events)的 Web 应用程序是很容易的。你只需要在服务器上编写一些代码将事件流传输到前端，而客户端的代码在处理传入事件部分几乎与 [websocket](/zh-CN/docs/Web/API/WebSockets_API) 相同。这是一个单向的连接，所以你不能从客户端向服务器发送事件。
```

2023-05-28 07:38 UTC, jasonren0403 commented on files/zh-cn/web/api/server-sent_events/index.md
> +- [WebSockets](/zh-CN/docs/Web/API/WebSockets_API)
```suggestion
- [WebSocket](/zh-CN/docs/Web/API/WebSockets_API)
```

2023-05-28 07:38 UTC, jasonren0403 commented on files/zh-cn/web/api/server-sent_events/index.md
>  一个网页获取新的数据通常需要发送一个请求到服务器，也就是向服务器请求的页面。使用 server-sent 事件，服务器可以在任何时刻向我们的 Web 页面推送数据和信息。这些被推送进来的信息可以在这个页面上作为 _[Events](/zh-CN/docs/DOM/event) + data_ 的形式来处理。
请根据[原文](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events)更新其中的内容及表述

2023-05-28 14:16 UTC, jasonren0403 commented on files/zh-cn/web/api/server-sent_events/using_server-sent_events/index.md
> +
```suggestion

```

2023-05-28 14:16 UTC, jasonren0403 commented on files/zh-cn/web/api/server-sent_events/using_server-sent_events/index.md
> +
```suggestion

```

2023-05-28 14:16 UTC, jasonren0403 commented on files/zh-cn/web/api/server-sent_events/using_server-sent_events/index.md
> +
```suggestion

```

2023-05-28 14:16 UTC, jasonren0403 commented on files/zh-cn/web/api/server-sent_events/using_server-sent_events/index.md
> +
```suggestion

```

2023-05-28 14:16 UTC, jasonren0403 commented on files/zh-cn/web/api/server-sent_events/using_server-sent_events/index.md
> +
```suggestion

```

2023-05-28 14:16 UTC, jasonren0403 commented on files/zh-cn/web/api/server-sent_events/using_server-sent_events/index.md
> +
```suggestion

```

2023-05-28 14:16 UTC, jasonren0403 commented on files/zh-cn/web/api/server-sent_events/using_server-sent_events/index.md
> +
```suggestion

```

2023-05-28 14:21 UTC, jasonren0403 approved these changes
👍 Thanks!

2023-05-28 14:24 UTC, merged