Update setTimeout
mdn/translated-content pull request #13421
Opened 2023-05-26 15:20 UTC by alattalatta

### Description

새로 생긴 부분을 번역하고 용어를 통일합니다.

- 타이머/타임아웃 -> 타임아웃
- 딜레이 -> 지연 시간

### Motivation

내용 추가됨

### Additional details

### Related issues and pull requests

2023-05-29 17:49 UTC, hochan222 requested changes

2023-05-29 17:49 UTC, hochan222 commented on files/ko/web/api/settimeout/index.md
> +전역 **`setTimeout()`** 메서드는 만료된 후 함수나 지정한 코드 조각을 실행하는 타임아웃을 설정합니다.
```suggestion
전역 **`setTimeout()`** 메서드는 만료된 후 함수나 지정한 코드 조각을 실행하는 타이머을 설정합니다.
```

@alattalatta 님 안녕하세요!

원문은 아래와 같은데요!

> The global **`setTimeout()`** method sets a timer which executes a function or specified
piece of code once the timer expires.

문장에서 "timer"는 "타이머"로 번역하는 것이 더 좋지 않을까 의견드립니다.

"타임아웃"은 "지정된 시간이 만료됨"의 의미를 가지고 있고, "타이머"는 "특정 시간에 특정 작업을 수행하도록 설정된 장치"의 의미를 가지고 있다고 생각합니다.

[html.spec.whatwg timers](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#timers)를 참고해보아도 

> Objects that implement the [WindowOrWorkerGlobalScope](https://html.spec.whatwg.org/multipage/webappapis.html#windoworworkerglobalscope) mixin have a map of active timers,

위 문장의 'a map of active timers'나

<img width="1261" alt="image" src="https://github.com/mdn/translated-content/assets/22424891/4f09dd54-7936-4dbb-a894-4842c3f9b92b">

위 문단에서 timer와 timeout이 동시에 사용된 것을 볼 때, 제가 이해한 바로는 두 단어의 의미는 구분되어 사용되고 있어서 검토 부탁드립니다!

2023-08-04 05:49 UTC, queengooborg commented
안녕하세요!  Since this PR has been sitting around for a while, I decided to apply the requested changes and fix merge conflicts -- this should be ready for re-review!

2023-08-12 06:11 UTC, hochan222 commented
As this review is one example, it needs to be edited throughout the document, so I will resolve it first and merge with other priorities (guides on merging after correcting conflicts directly by reviewers). But it won't be long. I will merge them soon.

Until then.. I will wait for contributors (cc. @alattalatta ). Thanks for resolving the crash..!

2024-03-24 09:33 UTC, hochan222 approved these changes

2024-03-24 09:36 UTC, merged