web Referer 문서를 en-us 문서와 동기화
mdn/translated-content pull request #1354
Opened 2021-07-02 05:00 UTC by whddn5464

web Referer 문서를 en-us 문서와 동기화

2021-07-04 13:22 UTC, pje1740 requested changes
원문과 비교하여 생략된 부분과 기타 수정사항 등에 대해 코멘트 남겼습니다. 확인 부탁드리며 제가 제안해둔 번역 외에 다르게 작성해주셔도 무방합니다! 질문이 있으시면 편하게 남겨주세요. 고생하셨습니다! :)

2021-07-04 13:22 UTC, pje1740 commented on files/ko/web/http/headers/referer/index.html
> +<p><code>Referer</code> 헤더는 URL 프래그먼트 (예 : "#section") 또는 "username : password" 정보를 포함 할 수 없습니다. 잠재적으로 <em>원본</em>, <em>경로</em>, 및 <em>쿼리 문자열</em>을 포함 할 수 있습니다. 전송되는 내용은 요청에 대한 referer 정책에 따라 다릅니다. 정
origin의 경우 헤더의 종류 중 하나인 점과, mdn origin 페이지에서 '원본'으로 표기하지 않는 것으로 파악되어 원본 대신 origin이라고 그대로 표기하면 어떨지 제안 드려봅니다 :)
그 외 referrer policy 오타 수정하였고, potentially 라는 단어가 잠재적이라는 뜻보단 possibly에 가깝게 느껴져 어감을 수정하면 어떨까 싶어 이 또한 제안 드립니다 :)

```suggestion
<p><code>Referer</code> 헤더는 URL 프래그먼트 (예 : "#section") 또는 "username : password" 정보를 포함 할 수 없습니다. <em>origin</em>, <em>경로</em>, 및 <em>쿼리 문자열</em>을 포함 할 수는 있습니다. 전송되는 내용은 요청에 대한 referrer 정책에 따라 다릅니다. 정보 및 예제는 Referrer-Policy를 참조하십시오. <a href="/en-US/docs/Web/HTTP/Headers/Referrer-Policy#directives">정보</a> 와 <a href="/en-US/docs/Web/HTTP/Headers/Referrer-Policy#examples">예시</a>는 이곳 {{HTTPHeader("Referrer-Policy")}}을 참고하세요.
```

2021-07-04 13:22 UTC, pje1740 commented on files/ko/web/http/headers/referer/index.html
> +    <p><p>referer는 실제로 단어 "referrer"에서 철자를 뺀 것입니다. 자세한 내용은 {{interwiki("wikipedia", "HTTP_referer", "HTTP referer on Wikipedia")}}을 참고하세요.</p>
misspelling은 잘못된 철자, 표기법을 의미하는 단어이기에 철자를 뺐다고 하면 뉘앙스가 다를 수 있을 거 같아 제안 드려봅니다 :)

```suggestion
    <p><p>referer는 단어 "referrer"의 잘못된 철자입니다. 자세한 내용은 {{interwiki("wikipedia", "HTTP_referer", "HTTP referer on Wikipedia")}}을 참고하세요.</p>
```

2021-07-04 13:22 UTC, pje1740 commented on files/ko/web/http/headers/referer/index.html
> + <dd>현재 요청된 페이지의 링크 이전의 웹 페이지의 절대 혹은 부분 주소. URL 프래그먼트(예를 들어, "#section")는 포함되지 않습니다.</dd>
원문과 비교하여 뒷부분이 생략된 것 같아 추가 부탁드립니다!

2021-07-04 13:22 UTC, pje1740 commented on files/ko/web/http/headers/referer/index.html
> +
Fetch 관련 링크가 빠져있는 것 같아 추가하고 번역되지 않은 The obsolete directive 부분 추가하였습니다. obsolete라는 표현의 번역은 다양할 수 있겠으나 사전 정의인 '구식'은 조금 어감이 이상하여 outdated된으로 표기해두었습니다. 다른 적절한 번역이 있다면 자유롭게 제안 주세요! 
그 외, 링크 패스를 ko로 수정하였습니다.

```suggestion
  <li>{{interwiki("wikipedia", "HTTP_referer", "HTTP referer on Wikipedia")}}</li>
  <li><a href="/ko/docs/Web/API/Fetch_API">Fetch</a>: {{domxref("Request.referrerPolicy")}}</li>
  <li>outdated 된 {{HTTPHeader("Content-Security-Policy")}} {{HTTPHeader("Content-Security-Policy/referrer", "referrer")}} {{deprecated_inline}} 디렉티브</li>
  <li><a href="/ko/docs/Web/Security/Same-origin_policy">Same-origin policy</a></li>
  <li><a href="https://blog.mozilla.org/security/2015/01/21/meta-referrer/">Tighter Control Over Your Referrers – Mozilla Security Blog</a></li>
```

2021-07-05 03:32 UTC, whddn5464 commented on files/ko/web/http/headers/referer/index.html
> + <dd>현재 요청된 페이지의 링크 이전의 웹 페이지의 절대 혹은 부분 주소. URL 프래그먼트(예를 들어, "#section")는 포함되지 않습니다.</dd>
수정부분 모두 적용시켰습니다. 피드백감사합니다!

2021-07-05 03:33 UTC, whddn5464 commented
피드백주신 comment들 확인했습니다. 감사합니다!

2021-07-07 09:37 UTC, whddn5464 reviewed
반영하도록하겠습니다!

2021-07-07 09:39 UTC, whddn5464 reviewed
!

2021-08-03 06:16 UTC, hochan222 approved these changes
LGTM :)

2021-08-14 10:54 UTC, pje1740 commented
확인이 늦었습니다...! 체크 오류가 있는 듯하여 PR 닫았다가 다시 열겠습니다!

2021-08-14 12:02 UTC, pje1740 requested changes
우선 확인이 너무 늦어져 번거롭게 해드린 점 양해 부탁드립니다! 🙇‍♀️
수정 주신 부분 모두 확인하였습니다! 추가적으로 원문에는 있는데 번역 때 누락된 부분이 보여서 괜찮으시다면 이 부분만 추가해주시면 어떨까 싶습니다! 기다려주셔서 감사합니다!

2021-08-14 12:02 UTC, pje1740 commented on files/ko/web/http/headers/referer/index.html
> + <dd>현재 요청된 페이지의 링크 이전의 웹 페이지의 절대 혹은 부분 주소. URL 프래그먼트(예를 들어, "#section")는 포함되지 않습니다.</dd>
영어 원문에서 뒤에 좀 더 추가적으로 설명하는 부분이 있어 이것도 포함하면 좋을 거 같아 제안 드립니다 :)

```suggestion
 <dd>현재 요청된 페이지의 링크 이전의 웹 페이지의 절대 혹은 부분 주소. URL 프래그먼트(예를 들어, "#section")나 사용자 정보(예를 들어 "https://username:password@example.com/foo/bar/" 에서 "username:password")는 포함되지 않습니다. 오리진, 패쓰, 쿼리스트링은 <a href="/ko/docs/Web/HTTP/Headers/Referrer-Policy#directives">referrer 정책</a>에 따라 포함될 수 있습니다.</dd>
```

2021-08-14 12:04 UTC, hochan222 commented
@pje1740 시간이 너무 오래되었고 PR 작성자분 commit 상태를 보니 해당 작업을 진행하려면 우선 머지하고 추가적으로 진행하는게 좋아보입니다. 머지하면 제가 나중에 작업하겠습니다.

2021-08-14 12:10 UTC, merged