add(structured_clone): 문서 추가
mdn/translated-content pull request #13592
Opened 2023-06-05 14:16 UTC by jgjgill

### Description
`structuredClone` 문서를 추가했습니다.🙇‍♂️

### Motivation

- `transfer`를 '전송 가능한'으로 번역했습니다.
- 'en-US' 문서들을 'ko' 문서들로 변경했습니다.

### Additional details

### Related issues and pull requests

2023-06-12 00:45 UTC, pje1740 requested changes
오타만 확인 부탁드립니다! 고생하셨습니다!

2023-06-12 00:45 UTC, pje1740 commented on files/ko/web/api/structuredclone/index.md
> +    - `transter`
```suggestion
    - `transfer`
```
오타가 있네요!

2023-06-12 01:51 UTC, jgjgill commented on files/ko/web/api/structuredclone/index.md
> +    - `transter`
아이고 오타가 있었네요..😂 감사합니다!

2023-06-13 14:31 UTC, pje1740 approved these changes
오타 수정 확인했습니다! 고생하셨습니다 😄

2023-06-13 14:31 UTC, merged