[ko] translate scrollIntoView
mdn/translated-content pull request #13636
Opened 2023-06-08 15:44 UTC by kwangminini

### Description
- 한국어 문서에 ```behavior``` 옵션에 ```instant```가 빠져있고 설명이 영어 문서와 달라서 ```instant```추가 하였고 옵션의 설명을 영어 문서와 일치시키며 번역하였습니다.
- 매개변수가 번역이 안되어 있어 매개변수 번역하였습니다.
- Notes 번역 안되어 있어 번역하였습니다.
- 반환 값 부분이 없어서 추가하였습니다.

### Motivation
[scrollIntoView en-us](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView)와[scrollIntoView ko](https://developer.mozilla.org/ko/docs/Web/API/Element/scrollIntoView)의 매개변수 ```behavior```의 옵션이 달랐으며 설명 또한 달랐습니다.

이번 번역을 통해 영어 문서와 한국어 문서의 매개변수를 일치시켜 독자에게 혼동을 줄일 수 있습니다.

### Additional details

### Related issues and pull requests

2023-06-09 05:25 UTC, wisedog requested changes
첫 기여 감사합니다. 전반적으로 훌륭합니다. GitHub Action 에서 자동으로 검사했을때 나온 부분 (24번째 줄 맨 마지막 빈 공백)  고쳐서 다시 PR 주시면 감사하겠습니다.

2023-06-09 05:25 UTC, wisedog commented on files/ko/web/api/element/scrollintoview/index.md
> +      `scrollIntoViewOptions: {block: "start", inline: "nearest"}`와 유사합니다.
원문인 `Corresponds to`는 일치, 혹은 상응한다는 뜻을 가지고 있습니다. `유사`랑은 좀 다른 의미로 보입니다.

2023-06-09 05:25 UTC, wisedog commented on files/ko/web/api/element/scrollintoview/index.md
> +      `scrollIntoViewOptions: {block: "end", inline: "nearest"}`와 유사합니다.
이 부분도 같습니다. 어떻게 생각하시는지 의견이 궁금합니다!

2023-06-09 05:25 UTC, wisedog commented on files/ko/web/api/element/scrollintoview/index.md
> +  - : 다음 속성을 포함하는 객체입니다.
맨 끝의 `:` 을 제외하신 점 잘 하셨습니다. 👏

2023-06-09 05:25 UTC, wisedog commented on files/ko/web/api/element/scrollintoview/index.md
> +없음 ({{jsxref("undefined")}}).
기왕 해주실거 아래 `예제`도 최신 영문 버전으로 업데이트 해주심 완벽한 번역 문서가 될 것 같습니다. 🙏

2023-06-09 05:40 UTC, kwangminini commented on files/ko/web/api/element/scrollintoview/index.md
> +      `scrollIntoViewOptions: {block: "end", inline: "nearest"}`와 유사합니다.
@wisedog 상응하다라는 단어가 일상에서 자주 사용하는 단어가 아니기 때문에 쉬운 단어로 바꾸려고 하다가 '유사' 라는 단어를 사용하였습니다.

말씀주신대로 '일치'와 '유사'는 다르기 때문에 수정하도록 하겠습니다!

2023-06-09 05:42 UTC, kwangminini commented on files/ko/web/api/element/scrollintoview/index.md
> +없음 ({{jsxref("undefined")}}).
예제의 경우 영문원서와 내용은 일치한 것 같은데 띄어쓰기를 말씀하시는 걸까요?

2023-06-09 07:02 UTC, wisedog commented on files/ko/web/api/element/scrollintoview/index.md
> +없음 ({{jsxref("undefined")}}).
아 아닙니다. 예제의 내용이 두 문서간 약간 달라서(var vs const, 띄어쓰기) 그냥 원본을 덮어쓰기만 해주시면 좋을 것 같아요.

2023-06-10 03:40 UTC, kwangminini commented on files/ko/web/api/element/scrollintoview/index.md
> +없음 ({{jsxref("undefined")}}).
앗 ㅋㅋ var를 못봤었네요..

2023-06-10 03:40 UTC, kwangminini commented
@wisedog 수정 완료했습니다. 리뷰 감사드립니다.

2023-06-10 07:40 UTC, wisedog approved these changes

2023-06-10 07:41 UTC, merged