fr: Removes duplicated frontmatter keys (learn folder)
mdn/translated-content pull request #13663
Opened 2023-06-10 13:15 UTC by Lou8is

### Description

Removes duplicated frontmatter keys (see #7412) from the **files/fr/learn** sub-folder.

Only `title`, `short_title`, `slug` and` l10n.*` are left, essentially removed `tags`, `original_slug`, `browser-compat`, `file-type`.

### Motivation

Help keeping the FR translation nice and up-to-date :)

### Additional details

### Related issues and pull requests

Relates to #7412 
Relates to 6 other PR for the other subfolders (will edit with #)

2023-07-03 10:50 UTC, SphinxKnight requested changes
multi-line metadata should be properly removed

2023-07-03 10:50 UTC, SphinxKnight commented on files/fr/learn/forms/how_to_build_custom_form_controls/index.md
>    Web/Guide/HTML/Formulaires/Comment_construire_des_widgets_de_formulaires_personnalisés
```suggestion
```

2023-07-03 11:22 UTC, SphinxKnight commented
@Lou8is thanks that was fast :) (I was working on it locally as well)

2023-07-03 11:28 UTC, Lou8is commented
I had time and saw the notification so... 😄 
However I am not sure how to handle the PR Test fail? I do not understand whats wrong (I'd guess the {{LearnSidebar}} macro).

2023-07-03 11:39 UTC, SphinxKnight commented
> I had time and saw the notification so... 😄 However I am not sure how to handle the PR Test fail? I do not understand whats wrong (I'd guess the {{LearnSidebar}} macro).

thanks for this (and for all the work on this PR and the others)

I think it has to do with the content used from the subpages in the `EmbedLiveSample` calls. I'm investigating and comparing with en-US to be sure.

2023-07-03 12:02 UTC, SphinxKnight commented
I'll be back at it later tonight or tomorrow :)

2023-07-06 10:31 UTC, Lou8is commented
Well removing EmbedLiveSample macros from /fr/docs/Learn/Forms/How_to_build_custom_form_controls also removes the errors so you were right. However, i compared that with the EN content, and it does not seems to be any difference regarding that.

I suspect the error comes from arguments being deprecated in the EmbedLiveSample macro (see line 17 of https://github.com/mdn/yari/blob/main/kumascript/macros/EmbedLiveSample.ejs).

That might be a whole other issue to rewrite pages so they don't call out-of-page code samples.

2023-07-06 21:57 UTC, cw118 commented
It seems that the EmbedLiveSample macros on the en-US page need to be updated as well. I opened [an issue on mdn/content](https://github.com/mdn/content/issues/27801) to confirm and I am preparing a pull request (for en-US).

2023-07-07 15:52 UTC, cw118 commented
The accepted solution on en-US (cf. mdn/content#27813) was to copy the code of each EmbedLiveSample from the `Learn/Forms/How_to_build_custom_form_controls/Example_1`, `Learn/Forms/How_to_build_custom_form_controls/Example_2` etc. pages and add it to the `Learn/Forms/How_to_build_custom_form_controls` file above each corresponding EmbedLiveSample using hidden codeblocks (html hidden, css hidden. js hidden).

Some comments (Styles requis, etc.) were removed from the hidden codeblocks (not from the `Learn/Forms/How_to_build_custom_form_controls/Example` pages!), and links pointing to the source code need to be moved as well.

See the [pull request diff on mdn/content](https://github.com/mdn/content/pull/27813/files) for more details, and let us know if help is needed for fixing the live samples :)

2023-07-08 15:58 UTC, Lou8is commented
I've fixed that page as you demonstrated and did not thought about looking into the other pages.

Seems like these files are also impacted, at list in the FR translation. I'm working on them but listing them if you'd like to check the EN content.

(Impacted macros per page)

- [ ] (1) /fr/learn/forms/how_to_structure_a_web_form/index.md
- [ ] (1) /fr/learn/forms/your_first_form/index.md
- [ ] (3) /fr/learn/html/introduction_to_html/advanced_text_formatting/index.md
- [ ] (2) /fr/learn/html/multimedia_and_embedding/images_in_html/index.md
- [ ] (1) /fr/learn/html/multimedia_and_embedding/other_embedding_technologies/index.md
- [ ] (1) /fr/learn/html/tables/advanced/index.md
- [ ] (2) /fr/learn/javascript/building_blocks/conditionals/index.md
- [ ] (2) /fr/learn/javascript/building_blocks/events/index.md
- [ ] (2) /fr/learn/javascript/first_steps/a_first_splash/index.md

2023-07-08 16:11 UTC, Lou8is commented
Some macros use "hide-codepen-jsfiddle" as parameter $6. Removing it does not seem to have functional impact, however it changes the page display (more margins or something). Any advice on that?

2023-07-16 20:28 UTC, cw118 commented
> Some macros use "hide-codepen-jsfiddle" as parameter $6. Removing it does not seem to have functional impact, however it changes the page display (more margins or something). Any advice on that?

Parameter $6 is also deprecated. However, some say that it was [incorrectly/prematurely deprecated](https://github.com/mdn/content/issues/25005#issuecomment-1460687579), so MDN might keep this parameter. 

In case MDN does keep parameter $6 (perhaps also [parameter $5](https://github.com/mdn/content/issues/25005#issuecomment-1460859179)) in the future, I would say if the `en-US` page uses it and all checks pass then we can keep the parameter. Not 100% sure though. 

@SphinxKnight any thoughts regarding parameters $5 and $6 of EmbedLiveSample?

2023-07-16 20:30 UTC, cw118 commented
> Edit: checks passed, maybe I did not modified those files. I could modified them in this PR or in a separate one.

Since this PR already modifies a lot of files/lines and the scope is not to fix EmbedLiveSample macros (and clarification is needed regarding parameters $5 and $6), let's remove deprecated EmbedLiveSample parameters in a separate one.

2023-07-17 18:53 UTC, SphinxKnight commented
> > Edit: checks passed, maybe I did not modified those files. I could modified them in this PR or in a separate one.
> 
> Since this PR already modifies a lot of files/lines and the scope is not to fix EmbedLiveSample macros (and clarification is needed regarding parameters $5 and $6), let's remove the remaining deprecated EmbedLiveSample parameters in a separate one.

Agreed :) 
Sorry for the late reaction here, @Lou8is please let us know if you need help spltting the EmbedLiveSample work on another PR.

2023-07-17 19:06 UTC, SphinxKnight commented
For args $5 and $6 of `EmbedLiveSample`, I never used them (or cannot remember) and since https://github.com/mdn/content/issues/25005 is kind of a deep dive into KumaScript arcanas and apparently some stuff is private :( 

In other words: looks over-complicated and sticking with what en-US does is probably the best solution for now.

2023-07-17 19:48 UTC, Lou8is commented
I'll try to do that other PR. For what I've seen, I might first raise an issue to discuss it before doing an actual PR, because from what I already saw, the remaining macros with a $6 arg are not in the EN version + modify how the code is rendered.

2023-07-19 11:22 UTC, SphinxKnight commented
I've thought a bit more about this one, esp. now that #14380 suffers from the same issue.
Instead of extanding the scope of this one, I'd suggest the following course of action: 

1. For this PR: reset to https://github.com/mdn/translated-content/pull/13663/commits/a2623857c6e1226f9af56387b76bc9bca1046675
2. Merge this one :) (after a review) 
3. Fix what need to be fixed under /learn regarding EmbedLiveSample calls in #14401

Sorry for this @Lou8is and thanks once more for the help.

2023-07-19 13:13 UTC, Lou8is commented
@SphinxKnight hmm not convinced I've managed this one correctly, I might need some help on reverting (or I could just re-do the edits on a clean branch).
+ I've reverted only up to a8514164d3f252eaf83eb9b74436ba8c3c80ca43 as it was corrections to the original modifications.

2023-07-19 14:48 UTC, SphinxKnight commented
@Lou8is if you made sure the "newer commits" were on another branch for https://github.com/mdn/translated-content/pull/14401 , locally (assuming you have `#7412-cleans-metadata-learn` as a branch and `origin` as a remote to your GH fork), you can:

```
git checkout #7412-cleans-metadata-learn 
git reset --hard a8514164d3f252eaf83eb9b74436ba8c3c80ca43
git push -f origin #7412-cleans-metadata-learn 
```
Since you have `[fix-embedlivesample-macros-learn](https://github.com/Lou8is/translated-content/tree/fix-embedlivesample-macros-learn)`, the commits for the EmbedLiveSample situation should be kept.
This way we have a "proper" history to review on this PR.

Please let me know if you need help in a "synchronous" way and I'll gladly help :)

2023-07-19 14:55 UTC, SphinxKnight commented
since the changes now touch a lot of files (incl. other locales and some engine/core stuff), I'll go ahead for the push

2023-07-19 15:39 UTC, Lou8is commented
Yeah thanks for handling that. I obviously messed up with git.
I'll handle the EmbedSampleLive in the ongoing PR :)

2023-07-20 06:03 UTC, SphinxKnight requested changes

2023-07-20 06:03 UTC, SphinxKnight commented on files/fr/learn/css/building_blocks/box_model_tasks/index.md
> +translation_of: Learn/CSS/Building_blocks/Box_Model_Tasks
```suggestion
translation_of: Learn/CSS/Building_blocks/Box_Model_Tasks
l10n:
  sourceCommit: 40cfeaf2623824ff3acf9d95af67a0498e23e3e8
```

2023-07-20 06:05 UTC, SphinxKnight approved these changes

2023-07-20 06:06 UTC, merged