[ko] Translate: `Array.prototype.toSorted()`
mdn/translated-content pull request #13683
Opened 2023-06-11 12:14 UTC by parkjbdev

### Description

ES2023에 추가된 Array.prototype.toSorted() 문서를 번역하였습니다.

### Motivation

### Additional details

### Related issues and pull requests

2023-06-12 01:01 UTC, pje1740 requested changes
메타데이터 부분만 확인 부탁드리겠습니다. 고생하셨습니다!

2023-06-12 01:01 UTC, pje1740 commented on files/ko/web/javascript/reference/global_objects/array/tosorted/index.md
> +---
https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md

여기 가이드 참고하셔서 메타데이터 업데이트 부탁드리겠습니다!

2023-06-12 02:18 UTC, parkjbdev commented on files/ko/web/javascript/reference/global_objects/array/tosorted/index.md
> +---
변경완료하였습니다. 확인부탁드립니다!

2023-06-13 14:36 UTC, pje1740 approved these changes
수정 반영 확인했습니다! 고생하셨습니다 👍

2023-06-13 15:07 UTC, merged