[ko] JavaScript: indexed collections 최신 동기화
mdn/translated-content pull request #13721
Opened 2023-06-13 09:33 UTC by wisedog

- JavaScript Guide 의 Indexed Collections 최신 동기화

2023-06-24 06:49 UTC, hochan222 requested changes
고생 많으셨습니다! 몇가지 리뷰 사항 아래에 남겨두었습니다.

좋은 주말 보내세요 :)

2023-06-24 06:49 UTC, hochan222 commented on files/ko/web/javascript/guide/indexed_collections/index.md
> +이번 장에서는 인덱스 값에 의해 정렬이 되는 데이터 자료구조에 대해 소개합니다. 배열과 유사 배열 생성자인
```suggestion
이번 장에서는 인덱스 값에 의해 정렬이 되는 데이터 컬렉션에 대해 소개합니다. 배열과 유사 배열 생성자인
```

(1)  Data Collection과 Data Structure는 Javascript에서 거의 동일하지만 미묘한 차이가 있다고 생각합니다.

우선, Javascript에서 존재하는 Collection의 종류는 아래와 같습니다.

> Indexed Collection - Arrays, Typed Array
> Keyed Collection - Objects, Map, Set, Weak Map, Weak Set

데이터 구조는 주로 데이터를 구성하고 저장하는 방법을 정의하는 방식이라면(예: 스택, 큐, 트리), 데이터 컬렉션은 정보에 **접근할 수** 있는 방법을 정의하는 방식의 차이가 있다고 생각합니다.

원문에서 `collections of data`로 작성되어 있는 만큼, **데이터 컬렉션**으로 번역하는 것이 좋아 보여 리뷰드렸습니다!

2023-06-24 06:49 UTC, hochan222 commented on files/ko/web/javascript/guide/indexed_collections/index.md
> +이번 장에서는 인덱스 값에 의해 정렬이 되는 데이터 자료구조에 대해 소개합니다. 배열과 유사 배열 생성자인
[고민]

```suggestion
이번 장에서는 색인 값에 의해 정렬이 되는 데이터 자료구조에 대해 소개합니다. 배열과 유사 배열 생성자인
```

인덱스를 색인으로 번역하는 것에 대해 어떻게 생각하시나요..? 고민입니다..!

2023-06-24 06:49 UTC, hochan222 commented on files/ko/web/javascript/guide/indexed_collections/index.md
> +이번 장에서는 인덱스 값에 의해 정렬이 되는 데이터 자료구조에 대해 소개합니다. 배열과 유사 배열 생성자인
[제안]
```suggestion
이번 장에서는 인덱스 값에 의해 정렬이 되는 데이터 자료구조에 대해 소개합니다. 배열과 유사 배열 구조인
```

`constructs`를 구조로 번역해도 좋을듯하여 리뷰드렸습니다.

2023-06-24 06:49 UTC, hochan222 commented on files/ko/web/javascript/guide/indexed_collections/index.md
> +배열은 이름과 인덱스로 참조되는 정렬된 값들의 집합입니다.
```suggestion
배열은 이름과 인덱스를 사용하여 참조하는 값들의 순서가 있는 목록입니다.
```

> An _array_ is an ordered list of values that you refer to with a name and an index.

실제 배열은 정렬된 상태는 아니기 때문에, 순서로 번역하는것이 좋아보입니다..!

2023-06-24 06:49 UTC, hochan222 commented on files/ko/web/javascript/guide/indexed_collections/index.md
> +타입 배열에도 동일한 개념이 많이 적용됩니다. 타입 배열에 대한 자세한 내용은
```suggestion
형식화 배열에도 동일한 개념이 많이 적용됩니다. 형식화 배열에 대한 자세한 내용은
```

현재 문서에서는 형식화 배열과 타입 배열 두 가지 표현이 사용되고 있습니다. 일관성 있는 번역을 위해 **형식화 배열**로 통일하는 것이 좋아보입니다!

2023-06-24 06:49 UTC, hochan222 commented on files/ko/web/javascript/guide/indexed_collections/index.md
> +[형식화 배열 가이드](/ko/docs/Web/JavaScript/Guide/Typed_arrays)를 참조하세요.
[제안]
```suggestion
[형식화 배열 안내서](/ko/docs/Web/JavaScript/Guide/Typed_arrays)를 참조하세요.
```
안내서 혹은 지침 번역 제안 드립니다 :)

2023-06-24 06:49 UTC, hochan222 commented on files/ko/web/javascript/guide/indexed_collections/index.md
> +배열 성성을 위한 다른 형태보다 짧아서 일반적으로 선호하는 방법입니다. 자세한 내용은 [배열 리터럴](/ko/docs/Web/JavaScript/Guide/Grammar_and_types#array_literals)을 참조하세요.
```suggestion
배열 생성을 위한 다른 형태보다 짧아서 일반적으로 선호하는 방법입니다. 자세한 내용은 [배열 리터럴](/ko/docs/Web/JavaScript/Guide/Grammar_and_types#array_literals)을 참조하세요.
```

2023-06-24 06:49 UTC, hochan222 commented on files/ko/web/javascript/guide/indexed_collections/index.md
> +다음 예제에서 `'Dusty'`는 인덱스 `30`번 째에 위치하기 때문에 `cats.length`는 `30 + 1`을 반환합니다.
```suggestion
다음 예제에서 `'Dusty'`는 인덱스 `30`번째에 위치하기 때문에 `cats.length`는 `30 + 1`을 반환합니다.
```

2023-06-24 06:49 UTC, hochan222 commented on files/ko/web/javascript/guide/indexed_collections/index.md
> +이는 아래 예제처럼 배열의 `length` 속성은 배열에 저장되어 있는 가장 큰 인덱스보다 1만큼 큰 값이 된다는 뜻입니다.
```suggestion
이는 아래 예제처럼 배열의 `length` 속성은 배열에 저장된 가장 큰 인덱스보다 1만큼 큰 값이 된다는 뜻입니다.
```

2023-06-24 06:49 UTC, hochan222 commented on files/ko/web/javascript/guide/indexed_collections/index.md
>  ### 배열 객체의 메서드
```suggestion
### 배열의 메서드
```

> ### Array methods

2023-06-24 06:49 UTC, hochan222 commented on files/ko/web/javascript/guide/indexed_collections/index.md
> +두개의 배열을 합쳐 새로운 배열을 반환합니다.
```suggestion
두 개의 배열을 합쳐 새로운 배열을 반환합니다.
```

2023-06-24 06:49 UTC, hochan222 commented on files/ko/web/javascript/guide/indexed_collections/index.md
> +콜백을 받는 `forEach` 메서드 (그리고 아래의 다른 메서드)는 어떤 방식으로든 전체 배열을 반복하기 때문에
```suggestion
콜백을 받는 `forEach` 메서드(그리고 아래의 다른 메서드)는 어떤 방식으로든 전체 배열을 반복하기 때문에
```

2023-06-24 06:49 UTC, hochan222 commented on files/ko/web/javascript/guide/indexed_collections/index.md
> +배열 메서드가 희소 배열에서 작동하는 방식에 대한 전체 목록은 [`Array` 레퍼런스 페이지](/ko/docs/Web/JavaScript/Reference/Global_Objects/Array#array_methods_and_empty_slots)를 참조하세요.
```suggestion
배열 메서드가 희소 배열에서 작동하는 방식에 대한 전체 목록은 [`Array` 참조 페이지](/ko/docs/Web/JavaScript/Reference/Global_Objects/Array#array_methods_and_empty_slots)를 참조하세요.
```

2023-06-25 06:00 UTC, wisedog commented on files/ko/web/javascript/guide/indexed_collections/index.md
> +이번 장에서는 인덱스 값에 의해 정렬이 되는 데이터 자료구조에 대해 소개합니다. 배열과 유사 배열 생성자인
네 컬렉션이 맞습니다. 기존 번역을 최대한 활용하다보니 이런걸 못걸렀군요 ㅎㅎ

2023-06-25 06:01 UTC, wisedog commented on files/ko/web/javascript/guide/indexed_collections/index.md
> +이번 장에서는 인덱스 값에 의해 정렬이 되는 데이터 자료구조에 대해 소개합니다. 배열과 유사 배열 생성자인
저도 좀 고민이긴 한데요. 인덱스라는 단어가 너무 광범위하게 사용되고 있어서요.

2023-06-25 23:24 UTC, wisedog commented
수정 완료했습니다. 제안 감사합니다. 😊

2023-06-26 10:28 UTC, hochan222 approved these changes
LGTM :)

2023-06-26 10:28 UTC, merged