[ko] CSS: CSS 기본 박스모델 입문 최신화
mdn/translated-content pull request #13875
Opened 2023-06-21 03:44 UTC by soorokim

### Description

* 박스모델 이미지 오류 수정
* 각 요소별 제목 추가
* 명세서 항목 삭제
* 같이보기 최신화

### Motivation

* 박스모델 이미지가 정상적으로 보이게 하고싶었습니다.
* 이미지를 수정하고 나니 최신 문서와 다른부분이 보여 최신화 했습니다.
(번역을 한게 아니라 민망하네요! ㅎㅎ)

### Additional details

- [en docs](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_box_model/Introduction_to_the_CSS_box_model)
- [ko docs](https://developer.mozilla.org/ko/docs/Web/CSS/CSS_box_model/Introduction_to_the_CSS_box_model)
### Related issues and pull requests

2023-06-21 04:01 UTC, wisedog requested changes
첫 기여 감사합니다. 

그림 파일 추가 외 큰 문제는 없었지만 힘들게 기울임꼴을 적용해주셨는데 한글 문서에는 기울임꼴이 들어가면 안되서 이 부분이 제일 안타깝습니다..... 😭

이 부분만 수정되면 바로 머지하도록 하겠습니다. 다시 한 번 감사합니다!

2023-06-21 04:31 UTC, soorokim commented on files/ko/web/css/css_box_model/introduction_to_the_css_box_model/index.md
> +테두리의 두께는 {{cssxref("border-width")}}와 단축 속성인 {{cssxref("border")}}가 결정합니다. {{cssxref("box-sizing")}} 속성의 값이 `border-box`라면 테두리 영역의 크기를 {{cssxref("width")}}, {{cssxref("min-width")}}, {{cssxref("max-w
`이 동작 방식은` -> `이 기본동작 방식은` 으로 수정했습니다.!

2023-06-21 04:31 UTC, soorokim commented on files/ko/web/css/css_box_model/introduction_to_the_css_box_model/index.md
> +끝으로, 비대체 인라인 요소가 차지하는 공간의 크기(줄 높이에 기여하는 양)는, 요소 주위에 테두리와 안쪽 여백이 표시되더라도 {{cssxref('line-height')}} 속성으로 결정한다는 점을 주의하세요.
삭제 완료했습니다!

2023-06-21 04:35 UTC, soorokim commented on files/ko/web/css/css_box_model/introduction_to_the_css_box_model/index.md
> +하나의 박스는 네 부분(_영역_)으로 이루어집니다. 각 영역을 _콘텐츠 영역_, _안쪽 여백(패딩) 영역_, _테두리 영역_, 그리고 _바깥 여백(마진) 영역_ 이라고 부릅니다.
* 기울임 글꼴을 해제했습니다.
(다만, 기울임 글꼴 적용하지 않는다는 내용을 제가 가이드에서 찾지 못했습니다. 따지려는것이 아니라 누락일까 싶어 여쭤보는거라 기분상하지 않으셨으면 합니다! 텍스트로 소통하다보니 오해가 생길수있을것 같아 사족을 길게 답니다ㅎㅎㅎㅎ)
* 가이드를 읽다보니 '무슨무슨 값'에 대한 가이드가 보여 추가적으로 수정했습니다.

2023-06-21 04:36 UTC, soorokim commented on files/ko/web/css/css_box_model/introduction_to_the_css_box_model/index.md
> +![CSS Box model](boxmodel.png)
제가 그 부분을 몰랐네요 알려주셔서 감사합니다. 파일 추가 했습니다!

2023-06-21 04:59 UTC, wisedog commented on files/ko/web/css/css_box_model/introduction_to_the_css_box_model/index.md
> +하나의 박스는 네 부분(_영역_)으로 이루어집니다. 각 영역을 _콘텐츠 영역_, _안쪽 여백(패딩) 영역_, _테두리 영역_, 그리고 _바깥 여백(마진) 영역_ 이라고 부릅니다.
아이고... 죄송합니다. 제가 링크를 잘못드렸습니다.
https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md

해당 문서에는 기울임꼴에 대한 내용이 있습니다. 텍스트로 소통하는데에 대한 문제는 저도 굉장히 잘 알고 있습니다. 배려 정말 감사드립니다.

2023-06-21 05:04 UTC, soorokim commented on files/ko/web/css/css_box_model/introduction_to_the_css_box_model/index.md
> +하나의 박스는 네 부분(_영역_)으로 이루어집니다. 각 영역을 _콘텐츠 영역_, _안쪽 여백(패딩) 영역_, _테두리 영역_, 그리고 _바깥 여백(마진) 영역_ 이라고 부릅니다.
리뷰를 꼼꼼히 해주셔서 PR이 훨씬 좋아졌네요 진심으로 감사드립니다.

2023-06-21 13:12 UTC, wisedog approved these changes

2023-06-21 13:14 UTC, merged

2023-08-08 18:36 UTC, hochan222 commented
@soorokim 님 안녕하세요. 

현재 한국 문서들은 최신화 되어있지 않은 레거시 문서들이 많이 존재합니다. [[ko] 한국 MDN 문서에 존재하는 레거시 문서 최신화](https://github.com/mdn/translated-content/issues/14965)에서 한국 MDN 문서에 존재하는 레거시 문서 최신화를 위한 작업을 진행하고 있습니다. 

참고 부탁드립니다. 좋은 하루 보내세요 :)

2023-08-08 22:42 UTC, soorokim commented
감사합니다! 잘 읽어보고 오늘부터 작업 시작 해보겠습니다!