zh-CN: updated the translation of `tab-size`
mdn/translated-content pull request #13877
Opened 2023-06-21 09:23 UTC by daiwanxing

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-06-21 12:57 UTC, yin1999 requested changes

2023-06-21 12:57 UTC, yin1999 commented on files/zh-cn/web/css/tab-size/index.md
> +**`tab-size`** CSS 属性用于自定义制表符字符的宽度 (U+0009)。
```suggestion
**`tab-size`** CSS 属性用于自定义制表符（U+0009）的宽度。
```

2023-06-21 12:57 UTC, yin1999 commented on files/zh-cn/web/css/tab-size/index.md
> +  - : 使用空格字符（U+0020）的进阶宽度的倍数作为制表符的宽度。必须是非负数。
I'm not sure 'advance width' could be translated to "进阶宽度"

2023-06-21 12:57 UTC, yin1999 commented on files/zh-cn/web/css/tab-size/index.md
> +  - : 制表符的宽度必须是非负数。
why removing the period

```suggestion
  - : 制表符的宽度。必须是非负数。
```

2023-06-22 11:02 UTC, daiwanxing commented on files/zh-cn/web/css/tab-size/index.md
> +  - : 使用空格字符（U+0020）的进阶宽度的倍数作为制表符的宽度。必须是非负数。
嗯，应该是指的是字符的宽度，疏漏了。https://learn.microsoft.com/en-us/windows/win32/gdi/character-widths

2023-06-22 13:07 UTC, yin1999 approved these changes
Thanks 👍

2023-06-22 13:09 UTC, merged