/ja/docs/Web/Accessibility/ARIA/Roles/Rowgroup_Role の更新
mdn/translated-content pull request #1387
Opened 2021-07-04 13:56 UTC by Wind1808

Mar 23, 2021 時点の英語版に同期

2021-07-06 14:51 UTC, mfuji09 requested changes
指摘箇所の修正をお願いします。

2021-07-06 14:51 UTC, mfuji09 commented on files/ja/web/accessibility/aria/roles/rowgroup_role/index.html
>  <h2 id="Description" name="Description">説明</h2>
翻訳を全面改訂するのであれば、 name="..." は不要になっているので削除してください。

2021-07-07 23:30 UTC, Wind1808 commented
見出しの name 属性を削除しました

2021-07-07 23:33 UTC, Wind1808 commented on files/ja/web/accessibility/aria/roles/rowgroup_role/index.html
>  <h2 id="Description" name="Description">説明</h2>
ソースが見やすくなりますね
他のページも更新時に反映させたいと思います

2021-07-12 17:51 UTC, mfuji09 approved these changes
OKです。

2021-07-12 17:51 UTC, merged