[ko] Translate: react_components
mdn/translated-content pull request #13913
Opened 2023-06-23 14:51 UTC by parkjbdev

### Description
react_components 문서를 번역하였습니다.

### Motivation

### Additional details

### Related issues and pull requests

2023-07-16 00:50 UTC, pje1740 submitted a review, later dismissed
리뷰가 늦어졌습니다! 양해 부탁드립니다 🙇‍♀️

번역 부분에선 제가 코멘트한 부분만 참고 부탁 드리겠습니다.
이미지의 경우, [yari](https://github.com/mdn/yari) 를 통해서 자동으로 문서에 삽입이 되기 때문에 별도로 폴더에 올려주실 필요는 없습니다. 제거 부탁 드립니다! (코드 자체에서는 수정하실 부분은 없습니다) 로컬에서 yari를 통해 실행하시려면 해당 레포의 가이드 참고 부탁드립니다.

2023-07-16 00:50 UTC, pje1740 commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.md
> +특히 두번째 항목은 유용합니다: 자주 재사용되는 UI 요소를 컴포넌트로 만들면, 코드를 한 곳에서 변경하고 그 컴포넌트가 사용되는 모든 곳에서 변경 사항을 볼 수 있습니다. 모든 것을 컴포넌트로 분리할 필요는 없습니다. 두번째 항목을 영감으로 삼아, 가장 재사용되고 중요한 UI 조각인 todo list의 항목을 컴포넌트로 만들어 보겠습니다.
```suggestion
특히 두번째 항목은 중요합니다.
```
colon(쌍점)은 가급적 [온점으로 치환](http://localhost:5042/ko/docs/Learn/tools_and_testing/client-side_javascript_frameworks/react_components)하면 좋을 거 같습니다! 그리고 valuable 이라고 원문이 적혀있는데, 유용함 보다는 중요함을 표현하는 것으로 보여 이렇게 제안 드려 봅니다!

2023-07-30 17:00 UTC, hochan222 requested changes
.

2023-08-10 11:41 UTC, pje1740 commented
확인이 늦은 사이에 컨플릭이 나고 있었네요 ㅠㅠㅠ 컨플릭 한번만 다시 해결해서 푸시 주시면 빠르게 확인하겠습니다! 번거롭게 해드린 점 양해 부탁드립니다 🥲

2023-08-15 04:50 UTC, parkjbdev commented
컨플릭트 해결했습니다! 검토 후 빠른머지 부탁드립니다!

2023-08-15 21:12 UTC, hochan222 approved these changes
고생 정말 많으셨습니다.

다시한번 리뷰가 늦어져서 죄송하고, 기여해주셔서 정말 감사합니다.

좋은 하루 보내세요 :)

2023-08-15 21:13 UTC, merged