update: Request interface of Fetch API
mdn/translated-content pull request #13997
Opened 2023-07-01 08:57 UTC by fwqaaq

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-07-01 09:01 UTC, fwqaaq commented on files/zh-cn/web/api/request/index.md
> +你可以使用 {{domxref("Request.Request","Request()")}} 构造函数创建一个新的 `Request` 对象，但是你可能会遇到作为其他 API 操作结果返回的 Request 对象，比如一个 `service worker` 的 {{domxref("FetchEvent.request")}}。
```suggestion
你可以使用 {{domxref("Request.Request","Request()")}} 构造函数创建一个新的 `Request` 对象，但是你可能会遇到作为其他 API 操作结果返回的 Request 对象，比如 `service worker` 的 {{domxref("FetchEvent.request")}}。
```

2023-07-01 15:02 UTC, jasonren0403 requested changes
some suggestions

2023-07-01 15:02 UTC, jasonren0403 commented on files/zh-cn/web/api/request/index.md
> +- [跨源资源共享（CORS）](/zh-CN/docs/Web/HTTP/Access_control_CORS)
```suggestion
- [跨源资源共享（CORS）](/zh-CN/docs/Web/HTTP/CORS)
```

2023-07-01 15:26 UTC, fwqaaq commented on files/zh-cn/web/api/request/index.md
> +## 实例方法
??

2023-07-01 15:27 UTC, fwqaaq commented on files/zh-cn/web/api/request/index.md
> +>**备注：** 这些 Body 上的函数只能运行一次; 随后的调用将通过空 strings/ArrayBuffers 解析。
```suggestion
>**备注：** 这些请求主体上的函数只能运行一次，随后的调用将兑现为空字符串或空的 ArrayBuffer。
```

2023-07-01 15:30 UTC, jasonren0403 commented on files/zh-cn/web/api/request/index.md
> +## 实例方法
![image](https://github.com/mdn/translated-content/assets/40999116/0e560930-2c0d-4201-b8f0-c063b3b99608)

2023-07-01 15:35 UTC, jasonren0403 commented on files/zh-cn/web/api/request/index.md
> +>**备注：** 这些 Body 上的函数只能运行一次; 随后的调用将通过空 strings/ArrayBuffers 解析。
哦对，这里有点问题 🤔 我有时间去提个 PR

![image](https://github.com/mdn/translated-content/assets/40999116/608b722a-025c-4d51-80cc-0288874e8e7b)

2023-07-01 15:39 UTC, fwqaaq commented on files/zh-cn/web/api/request/index.md
> +## 实例方法
👌

2023-07-01 15:59 UTC, jasonren0403 commented
temporaily hold until https://github.com/mdn/content/pull/27697 resolves

2023-07-10 10:33 UTC, jasonren0403 commented on files/zh-cn/web/api/request/index.md
> +>**备注：** 这些请求主体上的函数只能运行一次，随后的调用将兑现为空字符串或空的 ArrayBuffer。
```suggestion
> **备注：** 这些请求主体上的函数只能运行一次，随后的调用将出现 TypeError 错误，表明请求主体流已被使用。
```

2023-07-10 10:37 UTC, jasonren0403 approved these changes
👍

2023-07-10 10:39 UTC, merged