[ko] Update: How to structure a web form
mdn/translated-content pull request #14002
Opened 2023-07-02 03:25 UTC by soorokim

### Description

how to structure a web from 부분의 최신화를 진행했습니다.

### Motivation

[한글문서가 표시되지 않던 이슈](https://github.com/mdn/yari/issues/9154)를 확인 하다
해당 문서에서 오류가 나는것을 발견하고 최신화를 하기 시작했습니다.

### Additional details

> The paragraph at the top states a rule for required elements. The rule must be included _before_ it is used so that sighted users and users of assistive technologies such as screen readers can learn what it means before they encounter a required element. While this helps inform users what an asterisk means, it can not be relied upon. A screen reader will speak an asterisk as "_star_" when encountered. When hovered by a sighted mouse user, "_required_" should appear, which is achieved by use of the `title` attribute. Titles being read aloud depends on the screen reader's settings, so it is more reliable to also include the [`aria-label`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) attribute, which is always read by screen readers.

문장을 해석하면서 _before_ 와 _star_, _required_ 에 강조표시를 위해 따옴표를 사용했습니다.

2023-07-25 08:17 UTC, sunhpark42 requested changes, later dismissed
안녕하세요 @soorokim 님, 리뷰가 늦어 정말로 죄송합니다.  🙇‍♀️
수정이 필요한 부분에 대해 코멘트 남겨두었습니다. 확인 부탁드립니다.
기여 감사합니다.🙏

2023-07-25 08:17 UTC, sunhpark42 commented on files/ko/learn/forms/how_to_structure_a_web_form/example/index.md
> +## A payment form
제목도 번역 부탁드립니다.

2023-07-25 08:17 UTC, sunhpark42 commented on files/ko/learn/forms/how_to_structure_a_web_form/example/index.md
> +### Result
제목 번역 부탁드립니다. 참고 링크 첨부합니다.
https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md

2023-07-25 08:17 UTC, sunhpark42 commented on files/ko/learn/forms/how_to_structure_a_web_form/index.md
> +- [Property compatibility table for form widgets](/en-US/docs/Learn/Forms/Property_compatibility_table_for_form_controls)
경로 표기 ko/~ 로 부탁드립니다. 🙇‍♀️
https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md

2023-07-30 14:37 UTC, hochan222 requested changes

2023-07-30 14:37 UTC, hochan222 commented on files/ko/learn/forms/how_to_structure_a_web_form/example/index.md
> +---
```suggestion
l10n:
  sourceCommit: ~
---
```

최신 문서를 번역하셨다면, [문서 갱신 표시 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md)에 따라 `l10n.sourceCommit`을 추가해주시면 좋을듯합니다. cc. @sunhpark42 님

2023-07-30 23:00 UTC, soorokim commented
@sunhpark42 @hochan222 수정 완료했습니다!

2023-07-30 23:30 UTC, soorokim commented on files/ko/learn/forms/how_to_structure_a_web_form/example/index.md
> +---
혹시 제가 추가한것이 맞을까요? 번역한 파일에 가장 최신커밋이 
https://github.com/mdn/content/pull/27672/commits/8130108afffac43fb24f9db8c43d3d36043c17f8
라고 판단했습니다.

2023-07-31 12:45 UTC, hochan222 requested changes

2023-08-02 15:50 UTC, hochan222 approved these changes
고생 많으셨습니다! 좋은 하루 보내세요 :)

2023-08-02 15:57 UTC, merged