[zh-CN] sync  `Getting started` part of  `web-ext`
mdn/translated-content pull request #14030
Opened 2023-07-04 05:47 UTC by uiolee

### Description

- Synchronize with content
    - Mainly to add missing text.
    - keep their structure the same.
    - correct outdated links.

### Motivation

Some articles are missing something compared to CONTENT. I don't think readers want to view both versions of the article and compare them carefully. I think an incomplete document is incompetent. So I added these contents from CONTENT to our Chinese documentation, although they have not been translated yet.

2023-07-04 06:03 UTC, yin1999 reviewed
Hi @uiolee, please translate those English sentences. **Do not** add more English words in zh-CN translation. Thanks

2023-07-04 06:03 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/anatomy_of_a_webextension/index.md
> +![The components of a web extension. The manifest.JSON must be present in all extensions. It provides pointers to background pages, content scripts, browser actions, page actions, options pages, and
please translate the sentences

2023-07-04 06:03 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/examples/index.md
> +> **Warning:** Some examples work only on specific domains or pages. Details of any restrictions are provided in each example's readme file. None of the examples work in private browsing windows by d
same

2023-07-04 06:03 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/what_are_webextensions/index.md
> +![Amazon add-on example providing price comparison features](amazon_add_on.png)
same

2023-07-04 07:14 UTC, BSPR0002 commented on files/zh-cn/mozilla/add-ons/webextensions/anatomy_of_a_webextension/index.md
> +![The components of a web extension. The manifest.JSON must be present in all extensions. It provides pointers to background pages, content scripts, browser actions, page actions, options pages, and
```suggestion
![Web 扩展的组件。manifest.JSON 是所有扩展里都必须存在的。它提供指向后台页面、内容脚本、浏览器操作、页面操作、选项页和网络可访问资源的指针。后台页面由 HTML 和 JS 组成。内容脚本由 JS 和 CSS 组成。用户单击扩展图标能够触发浏览器操作和页面操作，由此产生的弹出窗口由 HTML、CSS 和 JS 组成。选项页由 HTML、CSS 和 JS 组成。](webextension-anatomy.png)
```
比起这个，不更应该把这张图片给改改么

2023-07-04 08:46 UTC, BSPR0002 requested changes

2023-07-04 08:46 UTC, BSPR0002 commented on files/zh-cn/mozilla/add-ons/webextensions/what_next_/index.md
> +- A collection of how-to guides on achieving key tasks in your extensions or making use of the JavaScript APIs.
```suggestion
- 一系列关于如何在扩展中实现关键任务与运用 JavaScript API 的指南。
```

2023-07-04 08:46 UTC, BSPR0002 commented on files/zh-cn/mozilla/add-ons/webextensions/what_next_/index.md
> +- [details about the Firefox developer communities](https://extensionworkshop.com/community/)
```suggestion
你还能在扩展工坊找到创建 Firefox 扩展所需要了解的所有东西，包括：

- [Firefox 扩展特性一览](https://extensionworkshop.com/#about)
- [用于开发及测试的工具和工序的详细介绍](https://extensionworkshop.com/documentation/develop/)
- [如何在 addons.mozilla.org 上发布你的扩展以及如何自行分发扩展](https://extensionworkshop.com/documentation/publish/)
- [如何管理你发布的扩展](https://extensionworkshop.com/documentation/manage/)
- [面向企业的开发与使用扩展的指南](https://extensionworkshop.com/documentation/enterprise/)
- [如何为 Firefox 开发主题](https://extensionworkshop.com/documentation/themes/)
- [Firefox 开发者社区的详细介绍](https://extensionworkshop.com/community/)
```

2023-07-04 08:46 UTC, BSPR0002 commented on files/zh-cn/mozilla/add-ons/webextensions/your_second_webextension/index.md
> +![A red-eared slider turtle.](turtle.jpg)
```suggestion
![一只棕色青蛙。](frog.jpg)

![一条有白色条纹的翡翠树蚺。](snake.jpg)

![一只巴西龟。](turtle.jpg)
```

2023-07-04 08:46 UTC, BSPR0002 commented on files/zh-cn/mozilla/add-ons/webextensions/your_second_webextension/index.md
> +![The beastify icon in the Firefox toolbar](beastify_icon.png)
```suggestion
![Firefox 工具栏上的 beastify 扩展图标](beastify_icon.png)
```

2023-07-04 08:46 UTC, BSPR0002 commented on files/zh-cn/mozilla/add-ons/webextensions/your_second_webextension/index.md
> +![A page replaced with the image of a turtle](beastify_page.png)
```suggestion
![被替换成乌龟图像的页面。](beastify_page.png)
```

2023-07-04 08:46 UTC, BSPR0002 commented on files/zh-cn/mozilla/add-ons/webextensions/your_second_webextension/index.md
> +- [take your learning further](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/What_next_#continue_your_learning_experience).
```suggestion
## 接下来做什么？

你已经创建了一个更加高级的 Firefox Web 扩展，接下来可以：

- [阅读扩展剖析](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Anatomy_of_a_WebExtension)
- [浏览扩展示例](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Examples)
- [学习如何开发、测试、发布你的扩展](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/What_next_)
- [进一步学习](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/What_next_#continue_your_learning_experience).
```

2023-07-04 09:01 UTC, uiolee commented
Hi @yin1999 . My thought is to pull content first, and then our readers and volunteers will see it. Then that content will be translated. Otherwise, we may ignore these content. I don't know if it fits the workflow.

2023-07-04 10:03 UTC, BSPR0002 commented
> Hi @yin1999 . My thought is to pull content first, and then our readers and volunteers will see it. Then that content will be translated. Otherwise, we may ignore these content. I don't know if it fits the workflow.

IMO, this is most about the accessibility of the images, the absence of these contents in the original version may have been because they are not typically visible, leading to a lack of effort in translation. However, this is not considered good practice. Though you may not a chinese speaker, I think your approach is more like passing trouble to others.

2023-07-04 10:32 UTC, yin1999 commented
> Hi @yin1999 . My thought is to pull content first, and then our readers and volunteers will see it. Then that content will be translated. Otherwise, we may ignore these content. I don't know if it fits the workflow.

The problem is, we have too many document that are not fully translated, and many documents are even fully in English. So I don't like the idea of directly adding English content to l10n. If a document is out-of-date (see the "last modified" at the bottom of page), it's better to report an issue rather than mixin English content, as Chrome could not perform the translation well with mixin content (The Chinese words in document may be "mis-translated", we just receive an [issue about this](https://github.com/mdn/translated-content/issues/14020)).

2023-07-04 11:24 UTC, uiolee commented
> 
Thank you for your answer. I think I understand now.

2023-07-04 15:21 UTC, uiolee commented on files/zh-cn/mozilla/add-ons/webextensions/examples/index.md
> +3. 克隆代码库，进入 [`build`](https://github.com/mdn/webextensions-examples/tree/main/build) 文件夹。该文件夹包含所有示例的已构建、带签名版本。你可以在 Firefox 中打开（菜单栏->文件->打开文件）并且永久安装这些扩展。这些扩展和直接从 [addons.mozilla.org](https://addons.mo
yep

2023-07-05 05:26 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/examples/index.md
>  为帮助了解如何开发扩展，我们维护了一个包含简单扩展示例的代码仓库在<https://github.com/mdn/webextensions-examples>. 本文描述了仓库代码中所使用的 WebExtension APIs。
```suggestion
为帮助了解如何开发扩展，我们维护了一个包含简单扩展示例的代码仓库在<https://github.com/mdn/webextensions-examples>。本文描述了仓库代码中所使用的 WebExtension API。
```

2023-07-05 05:26 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/examples/index.md
>  > **警告：** 不要提交这些关于 WebExtension 例子的示例到 AMO (addons.mozilla.org) 上去，你无需为附加组件签名就能运行 WebExtension 的示例。只要按照上面的步骤来就可以了。
```suggestion
> **警告：** 不要提交这些关于 WebExtension 例子的示例到 AMO（addons.mozilla.org）上去，你无需为附加组件签名就能运行 WebExtension 的示例。只要按照上面的步骤来就可以了。
```

2023-07-05 05:26 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/what_are_webextensions/index.md
> +![图中的 Amazon 扩展提供比价功能](amazon_add_on.png)
screen reader would "tell" the disables that "this is an image", please provide the description only. And in Firefox, we translate "add-on" into "附加组件".

```suggestion
![Amazon 附加组件示例提供比价功能](amazon_add_on.png)
```

2023-07-05 05:26 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/what_are_webextensions/index.md
> +![图中的 My Web New Tab 扩展展现蝙蝠侠主题](myweb_new_tab_add_on.png)
```suggestion
![My Web New Tab 附加组件展现蝙蝠侠主题](myweb_new_tab_add_on.png)
```

2023-07-05 05:26 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/what_are_webextensions/index.md
> +![图中的 uBlock origin 扩展能够拦截跟踪器统计](ublock_origin_add_on.png)
```suggestion
![uBlock origin 附加组件示例和拦截跟踪器统计](ublock_origin_add_on.png)
```

2023-07-05 05:26 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/what_are_webextensions/index.md
> +![图中的扩展是一个二维码生成器](qr_code_image_generator_add_on.png)
```suggestion
![二维码生成器附加组件示例](qr_code_image_generator_add_on.png)
```

2023-07-05 05:26 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/what_are_webextensions/index.md
> +![图中是 axe 无障碍功能测试扩展](axe_developer_tools_add_on.png)
```suggestion
![axe 无障碍功能测试附加组件示例](axe_developer_tools_add_on.png)
```

2023-07-05 05:26 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/your_second_webextension/index.md
> +- [进一步学习](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/What_next_#continue_your_learning_experience).
```suggestion
- [进一步学习](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/What_next_#继续你的学习经历)。
```

2023-07-05 11:18 UTC, yin1999 approved these changes
Thanks

2023-07-05 11:18 UTC, merged