[ko] Intl.DisplayNames
mdn/translated-content pull request #14052
Opened 2023-07-06 01:50 UTC by SnowMarble

2023-07-06 02:05 UTC, wisedog requested changes
오랜만에 기여 감사합니다. 몇 가지 의견을 남겼으니 확인 부탁드릴께요.

2023-07-06 02:05 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/intl/displaynames/index.md
> +- {{jsxref("Intl/DisplayNames/of", "Intl.DisplayNames.prototype.of()")}}
인스턴스 메서드 부분 다시 한 번 확인 부탁드려도 될까요? en-US 최신본과 많이 다른데 착오가 있는듯 합니다.

2023-07-06 02:05 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/intl/displaynames/index.md
> +// 한국어로 언어 표시 이름을 가져옵니다.
@hochan222  `en-US` 원본은 중국번체이고, 예제코드이기 때문에 평소라면 즉각 수정 요청을 드리겠지만 이 문서는 다름이 아니라 Intl 이기 때문에 유지해도 나쁘지 않겠다 생각이 드는군요. 의견 부탁드려도 될까요?

2023-07-06 02:05 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/intl/displaynames/index.md
> +**`Intl.DisplayNames`** 객체를 사용하면 언어, 지역 그리고 문자 체계 표시 이름을 일관되게 번역할 수 있습니다.
`script display names.`을 `문자 체계 표시 이름` 이라 하셨는데 뭔가 딱 매칭되지가 않는데요. 부연설명 부탁드려도 될까요?

2023-07-06 02:05 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/intl/displaynames/index.md
> +<!-- 이 대화형 예제의 소스는 GitHub 리포지토리에 저장되어 있습니다. 대화형 예제 프로젝트에 기여하고 싶다면 https://github.com/mdn/interactive-examples를 클론하고 풀 리퀘스트를 보내주세요. -->
`en-US` 에는 해당 메시지가 없군요. 혹시 일부러 넣으신건지요?

2023-07-06 03:23 UTC, SnowMarble commented on files/ko/web/javascript/reference/global_objects/intl/displaynames/index.md
> +// 한국어로 언어 표시 이름을 가져옵니다.
저도 처음엔 다른 번역들과 마찬가지로 중국어 번체로 번역을 진행했지만, 저희가 하는 것이 단순한 번역이 아닌 "지역화"가 목적인 만큼, 원문 예제의 형식에서 벗어나지 않는 범위에서 예제 수정을 부분적으로 허용해도 괜찮지 않을까 생각해봤습니다. 의도적으로 기존 규칙에서 벗어나 작업을 진행한 점은 저의 잘못이 맞지만, 지역화의 관점에서 봤을때 @wisedog 님은 어떻게 생각하시나요?

2023-07-06 03:31 UTC, SnowMarble commented on files/ko/web/javascript/reference/global_objects/intl/displaynames/index.md
> +- {{jsxref("Intl/DisplayNames/of", "Intl.DisplayNames.prototype.of()")}}
이런 다시 확인해보니까 제 로컬 저장소 업데이트가 안되어있었네요. 다른 부분은 수정해서 다시 작업하겠습니다.

2023-07-06 03:35 UTC, SnowMarble commented on files/ko/web/javascript/reference/global_objects/intl/displaynames/index.md
> +**`Intl.DisplayNames`** 객체를 사용하면 언어, 지역 그리고 문자 체계 표시 이름을 일관되게 번역할 수 있습니다.
script를 문자로 해석하는 것보단 문자 체계로 번역하는 것이 더 의미상 적정하다고 판단했습니다. [일본어 번역](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames#%E6%96%87%E5%AD%97%E4%BD%93%E7%B3%BB%E3%82%B3%E3%83%BC%E3%83%89%E3%81%AE%E8%A1%A8%E7%A4%BA%E5%90%8D)의 文字体系를 참고했습니다.

2023-07-06 04:05 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/intl/displaynames/index.md
> +// 한국어로 언어 표시 이름을 가져옵니다.
잘못이라뇨 가당치 않습니다. 저도 원래같으면 예제의 코멘트 외에 코드 수정을 하셨다면 바로 수정요청드렸겠지만, 이번엔 Intl 부분이라서  @SnowMarble  님의 기여 방식이 꽤 괜찮다고 생각해서 호찬님 의견을 물어본거거든요 : > 저도 이 부분을 생각지도 못했는데 좋은 제안 정말 감사합니다.

2023-07-16 04:26 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/intl/displaynames/index.md
> +// 한국어로 언어 표시 이름을 가져옵니다.
@hochan222  님이 좀 바쁘신것 같습니다. 다른 부분은 다 오케이인데 이 부분만은 호찬님 의견이 중요할걸로 보여서 @SnowMarble  님 잠시만 더 기다려주시겠어요?

2023-07-16 04:44 UTC, SnowMarble commented on files/ko/web/javascript/reference/global_objects/intl/displaynames/index.md
> +// 한국어로 언어 표시 이름을 가져옵니다.
넵 전 괜찮습니다:)

2023-07-25 15:05 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/intl/displaynames/index.md
> +// 한국어로 언어 표시 이름을 가져옵니다.
@hochan222  의견을 구합니다!

2023-07-30 11:08 UTC, hochan222 approved these changes

2023-07-30 11:08 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/intl/displaynames/index.md
> +// 한국어로 언어 표시 이름을 가져옵니다.
@SnowMarble 님, @wisedog 님 안녕하세요. 답변이 늦어져서 정말 죄송합니다.

> 하는 것이 단순한 번역이 아닌 "지역화"가 목적인 만큼, 원문 예제의 형식에서 벗어나지 않는 범위에서 예제 수정을 부분적으로 허용해도 괜찮지 않을까 생각해봤습니다

좋은 방향이라고 생각합니다. 

예시가 중국어 기준으로 된 이유는 중국 페이지 트래픽이 그당시 2위여서 그런듯합니다. 아래는 2020년(커밋 당시) 트래픽은 아니지만 참고차 첨부드립니다. ([2021 web traffic compared to en-US](https://github.com/mdn/translated-content/discussions/1667))

```js
// 2021 web traffic compared to en-US
en-US      58.9% (English)
zh-CN      8.9% (Chinese (China))
ja         6.6% (Japanese)
ru         6.3% (Russian)
es         6.1% (Spanish)
fr         4.3% (French)
pt-BR      3.4% (Portuguese (Brazil))
ko         2.5% (Korean)
de         1.4% (German)
zh-TW      1.0% (Chinese (Taiwan, Province of China))
pl         0.5% (Polish)
```

따라서, en-us 페이지에 너무 얽메이지 않고 좋은 지역화 방안이 있다면 반영해도 좋아보입니다. 현재 경우는 문제 없어보이지만, 해당 내용 안내서에 추가해놓겠습니다. 

감사합니다. 모두 좋은 주말 보내세요 :)

2023-08-01 13:59 UTC, wisedog approved these changes

2023-08-01 14:00 UTC, wisedog commented
@SnowMarble  멋진 PR 이었습니다. 늘 감사드립니다. 👍

2023-08-01 14:00 UTC, merged

2023-08-12 12:46 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/intl/displaynames/index.md
> +// 한국어로 언어 표시 이름을 가져옵니다.
참고차, 최근 [Translation guidelines for MDN translated content](https://github.com/mdn/translated-content/tree/main/docs)이 갱신되었습니다.

Localizing code blocks의 "If a code block must be rewritten to meet a locale's requirements, add a comment explaining why" 내용 추가되어서 참고차 댓글 남깁니다 :)