[ko] add glossary `cdn` translation in ko
mdn/translated-content pull request #14126
Opened 2023-07-10 14:40 UTC by rbals0445

### Description

- 아래 용어집의 CDN을 번역했습니다.
- https://developer.mozilla.org/en-US/docs/Glossary/CDN 

### Motivation

### Additional details

- asset을 그대로 애셋으로 표현했는데 다른 표현이 있다면 알려주세요~ 정적 자산? 이란 말도 어색해서 그대로 표기하였습니다.

### Related issues and pull requests

혹시나 놓친 부분이나 컨벤션이 있다면 알려주시면 감사하겠습니다. 아래 링크 외에는 찾지 못했습니다.

https://github.com/cos18/translated-content/blob/4d3bbfc51d958ff71c6163b64b5394a515d62326/docs/ko/translation-guide.md

2023-07-16 12:18 UTC, pje1740 requested changes

2023-07-16 12:18 UTC, pje1740 commented on files/ko/glossary/cdn/index.md
> +slug: Glossary/CDN
번역본에는 어떤 버전의 문서를 기준으로 번역했는지에 대한 커밋 id 추가가 필요합니다. 관련 가이드는 [이 링크](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md) 참고하셔서 추가 부탁드리겠습니다!

2023-07-16 14:56 UTC, rbals0445 commented on files/ko/glossary/cdn/index.md
> +slug: Glossary/CDN
아하 ㅎㅎ glossary-guide는 봤는데, 여긴 확인하지 못했었네요. 알려주셔서 감사합니다~

수정해서 올리도록 하겠습니다!

2023-07-16 15:21 UTC, rbals0445 commented on files/ko/glossary/cdn/index.md
> +slug: Glossary/CDN
안녕하세요. 수정내용 반영했습니다. 아래 링크에서 해당 파일에 대한 최신 커밋 나오는것 확인했습니다.

https://github.com/mdn/content/commit/ada5fa5ef15eadd44b549ecf906423b4a2092f34

2023-07-16 23:37 UTC, pje1740 commented on files/ko/glossary/cdn/index.md
> +slug: Glossary/CDN
메타 데이터 관련해서 정리된 것이 비교적 최근이라 그렇습니다! 그래서 아마 관련 논의 이전에 번역이 되었던 문서들은 추가가 없을 수 있습니다. 논의 이후 작업되고 있는 파일들은 sourceCommit 을 추가가 필요해서 별도의 공지 추가가 없는 한 추후 작업에도 sourceCommit 추가 부탁 드리겠습니다! 🙇‍♀️

고생하셨습니다!! 👍

2023-07-16 23:39 UTC, pje1740 reviewed
메인 브랜치가 그 사이에 머지된 게 있어서 컨플릭만 수정해서 브랜치에 force push 부탁드리겠습니다! 감사합니다 🙂

2023-07-18 13:24 UTC, rbals0445 commented
@pje1740 님, main에 계속 커밋이 부어지는것 같은데, 혹시 메인테이너분은 리베이스나 머지할 수 있는 권한이 없는것일까요?

제가 일단 2번정도 계속 최신화를 진행했습니다~

2023-07-19 00:01 UTC, pje1740 commented
아이고 일괄적으로 지속적으로 적용되는 머지가 있나보네요! 그럼 제가 머지할 적용할 때 리베이스 해서 적용하도록 하겠습니다!

2023-07-19 00:03 UTC, pje1740 approved these changes

2023-07-19 06:06 UTC, merged