javascript/global_objects/null  en-us 문서와 동기화
mdn/translated-content pull request #1414
Opened 2021-07-06 13:33 UTC by wisedog

2021-07-09 02:31 UTC, alattalatta requested changes
이거 원본은 제가 했던거라 리뷰 남길게요 😅

2021-07-09 02:31 UTC, alattalatta commented on files/ko/web/javascript/reference/global_objects/null/index.html
> +
```suggestion
translation_of: Web/JavaScript/Reference/Global_Objects/null
```

2021-07-09 02:31 UTC, alattalatta commented on files/ko/web/javascript/reference/global_objects/null/index.html
> +<p><code>null</code>은 문자 그대로 <code>null</code>이라 씁니다. <code>null</code>은
여기서 "literal"은 "literally"의 literal이 아니고 "객체 리터럴"의 리터럴이므로 그대로 쓰는게 맞지 않을까요?

2021-07-09 02:31 UTC, alattalatta commented on files/ko/web/javascript/reference/global_objects/null/index.html
> +  {{jsxref("Global_Objects/undefined","undefined")}}과 같이 글로벌 객체의 속성에 대한 식별자가 아닙니다. 대신 <code>null</code>은 식별이 부족이나 변수가
"lack of identification"의 "lack of"는 "부족"이 아니고 "누락"입니다.

> `null` expresses a lack of identification, indicating that a variable points to no object.

이므로,

>  `null`은 식별되지 않은 것을 표현합니다. 즉, 변수가 아무런 객체도 가리키지 않음을 나타냅니다.

와 같은 뜻을 포함하는게 좋을 것 같아요.

2021-07-09 02:31 UTC, alattalatta commented on files/ko/web/javascript/reference/global_objects/null/index.html
> +    <p>{{jsxref("Operators/void", "void operator")}}</p>
"operator" 번역이 누락됐어요.

```suggestion
    {{jsxref("Operators/void", "void")}} 연산자
```

불필요한 `<p>`랑, "operator"까지 `<code>` 안에 들어가는건 영어 소스가 잘못됐네요.

2021-07-09 02:31 UTC, alattalatta commented on files/ko/web/javascript/reference/global_objects/null/index.html
> +  객체를 가리키지 않음을 표현합니다. API에서 <code>null</code>은 종종 객체가 있어야하지만 연관된 개체가 없는다는 항목을 받아올 때 사용합니다.
"있어야하지만" -> "있어야 하지만"
"개체" -> "객체"

> In APIs, null is often retrieved in a place where an object can be expected but no object is relevant. 

에서, "In APIs"가 주체라는 것이 아니고 API 응답을 말하는 것이므로 "is ... retrieved"는 "API에서 null은 ... 받아올 때 사용합니다"보단 "API에서는 null을 ... 사용합니다"가 더 자연스럽게 읽힙니다.

> API에서는 종종 `null`을 객체가 있어야 하는 항목에 연관된 객체가 없을 때 사용합니다.

그런데 원문이 "must exists"가 아니고 "can be expected"네요. 그러면 "있어야 하는" 이라는 말은 너무 강합니다.

```suggestion
  객체를 가리키지 않음을 표현합니다. API에서는 <code>null</code>을 종종 관련된 객체가 존재하지 않을 때 그 객체 대신 사용합니다.
```

2021-07-09 03:06 UTC, wisedog commented
> 이거 원본은 제가 했던거라 리뷰 남길게요 😅

아니 직접 리뷰를 달아주시다니 영광입니다!!

2021-07-21 13:18 UTC, wisedog commented
@alattalatta 제안주신 내용이 다 합당합니다. 그대로 반영하였습니다.

2021-07-28 23:52 UTC, pje1740 approved these changes
고생하셨습니다! 감사합니다 :)

2021-07-28 23:53 UTC, merged