[ko] add korean translation to what-is-css
mdn/translated-content pull request #14174
Opened 2023-07-13 13:06 UTC by rbals0445

### Description

- 반말이 섞여있는 부분들을 제거했습니다
- 누락된 번역들을 추가했습니다

### Motivation

### Additional details

### Related issues and pull requests

2023-07-16 04:41 UTC, wisedog requested changes
기여 감사합니다! 

원래는 메타 데이터에 l10n 이라 해서 원본 커밋을 넣는데, 기여하신 부분은 전체 문서를 변경한게 아니므로 그냥 넘어가도록 하겠습니다. 

리뷰한 부분 수정 부탁드리겠습니다. 감사합니다.

2023-07-16 04:41 UTC, wisedog commented on files/ko/learn/css/first_steps/what_is_css/index.md
> +모든 웹 표준 기술 (HTML, CSS, JavaScript 등.) 은 표준 조직 ({{glossary("W3C")}}, {{glossary("WHATWG")}}, {{glossary("ECMA")}} 또는 {{glossary("Khronos")}} 와 같은) 이 게시한 specifications (또는 단순히 "specs") 이라는 거대한 문서로 정의됩
[용어 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md)에 의거 specifications은 `명세서`라고 번역합니다.

2023-07-16 04:41 UTC, wisedog commented on files/ko/learn/css/first_steps/what_is_css/index.md
> +모든 웹 표준 기술 (HTML, CSS, JavaScript 등.) 은 표준 조직 ({{glossary("W3C")}}, {{glossary("WHATWG")}}, {{glossary("ECMA")}} 또는 {{glossary("Khronos")}} 와 같은) 이 게시한 specifications (또는 단순히 "specs") 이라는 거대한 문서로 정의됩
또한 `precisely`를 `자세하게`라고 번역하셨는데 `정확하게`가 아닐까 합니다. 즉 이를 조합해보자면 
`해당 기술들이 어떻게 작동(동작)하는지 정확하게 정의`일것 같습니다.

2023-07-16 04:41 UTC, wisedog commented on files/ko/learn/css/first_steps/what_is_css/index.md
> +CSS 를 처음 접하는 사람들은, CSS specs 이 압도적이라고 생각할 것입니다 — 웹 개발자가 CSS 를 이해하기 위해 읽는 것이 아니라 엔지니어가 user agents 의 기능에 대한 지원을 구현하는 데 사용하기 위한 것입니다. 많은 숙련된 개발자는 MDN 설명서나 기타 자습서를 참조하는 것이 좋습니다. 그러나 사용중인 CSS, 브라우저 지원 (아
`CSS specs`보다는 `CSS 명세`가 좋겠습니다.  또한 위에서 `HTML 이`를 `HTML이`로 붙이신것 처럼 `CSS 를` 을 `CSS를`로 붙여서 쓰시는게 어떨까요?

2023-07-16 04:41 UTC, wisedog commented on files/ko/learn/css/first_steps/what_is_css/index.md
> +CSS 를 처음 접하는 사람들은, CSS specs 이 압도적이라고 생각할 것입니다 — 웹 개발자가 CSS 를 이해하기 위해 읽는 것이 아니라 엔지니어가 user agents 의 기능에 대한 지원을 구현하는 데 사용하기 위한 것입니다. 많은 숙련된 개발자는 MDN 설명서나 기타 자습서를 참조하는 것이 좋습니다. 그러나 사용중인 CSS, 브라우저 지원 (아
user agents 는 용어 안내서에 의거, `사용자 에이전트`라고 번역합니다.

2023-07-16 15:53 UTC, rbals0445 commented on files/ko/learn/css/first_steps/what_is_css/index.md
> +CSS 를 처음 접하는 사람들은, CSS specs 이 압도적이라고 생각할 것입니다 — 웹 개발자가 CSS 를 이해하기 위해 읽는 것이 아니라 엔지니어가 user agents 의 기능에 대한 지원을 구현하는 데 사용하기 위한 것입니다. 많은 숙련된 개발자는 MDN 설명서나 기타 자습서를 참조하는 것이 좋습니다. 그러나 사용중인 CSS, 브라우저 지원 (아
@wisedog 님 안녕하세요. 리뷰 감사합니다!

아래 내용 수정하였습니다.

1. I10n 원본 커밋 추가 (아래 링크에서 확인하실 수 있습니다)
- https://github.com/mdn/content/commit/751d58669499de0c6ea0d5b356e0e1448418c5d3
2. spectifaction -> 명세서, spec -> 명세 로 수정
3. precisely -> 정확하게 로 수정
4. `CSS 를` -> `CSS를` 처럼 불필요하게 띄어쓰기가 들어간 내용 수정.

2023-07-17 02:46 UTC, wisedog commented on files/ko/learn/css/first_steps/what_is_css/index.md
> +CSS 를 처음 접하는 사람들은, CSS specs 이 압도적이라고 생각할 것입니다 — 웹 개발자가 CSS 를 이해하기 위해 읽는 것이 아니라 엔지니어가 user agents 의 기능에 대한 지원을 구현하는 데 사용하기 위한 것입니다. 많은 숙련된 개발자는 MDN 설명서나 기타 자습서를 참조하는 것이 좋습니다. 그러나 사용중인 CSS, 브라우저 지원 (아
좀 고민인데요. 원본 커밋을 명시한다는건 현재 페이지가 원본 커밋 당시의 내용과 "동일하다"는 전제로 넣는 내용이거든요. 적어도 전 그렇게 생각하고 있습니다. 다만 지금 보내주신 PR로 인해 변경되는 한국어 페이지와 해당 커밋 당시의 en-US 페이지랑은 많이 다릅니다. 그래서 그냥 넘어간다고 말씀드린 거였는데요. 방법은 2가지입니다. 

1. 현재 페이지를 해당 커밋 당시의 en-US 문서와 동일하게 맞춤
2. 원본 커밋(l10n) 부분을 삭제

@hochan222 님 의견 부탁드립니다.

2023-07-17 13:12 UTC, rbals0445 commented on files/ko/learn/css/first_steps/what_is_css/index.md
> +CSS 를 처음 접하는 사람들은, CSS specs 이 압도적이라고 생각할 것입니다 — 웹 개발자가 CSS 를 이해하기 위해 읽는 것이 아니라 엔지니어가 user agents 의 기능에 대한 지원을 구현하는 데 사용하기 위한 것입니다. 많은 숙련된 개발자는 MDN 설명서나 기타 자습서를 참조하는 것이 좋습니다. 그러나 사용중인 CSS, 브라우저 지원 (아
@wisedog 님, 저는 가장 최신 커밋만 붙이면 되는줄 알았습니다 ㅎㅎ;;

룰에 맞추기 위해 1번 방법을 택하도록 하겠습니다.

아래 사진처럼 누락된 유튜브 영상 부분과 CSS syntax 부분을 추가하도록 하겠습니다.

설명 감사합니다!

![image](https://github.com/mdn/translated-content/assets/60285506/2948c0f3-2189-465f-8539-17775a3a7d48)

2023-07-19 00:16 UTC, wisedog commented on files/ko/learn/css/first_steps/what_is_css/index.md
> +CSS 를 처음 접하는 사람들은, CSS specs 이 압도적이라고 생각할 것입니다 — 웹 개발자가 CSS 를 이해하기 위해 읽는 것이 아니라 엔지니어가 user agents 의 기능에 대한 지원을 구현하는 데 사용하기 위한 것입니다. 많은 숙련된 개발자는 MDN 설명서나 기타 자습서를 참조하는 것이 좋습니다. 그러나 사용중인 CSS, 브라우저 지원 (아
추가 수정 감사합니다.  근데 그 새 뭔가 변경된것 같아요. 리베이스가 필요하다고 나오네요.

2023-07-19 00:33 UTC, rbals0445 commented on files/ko/learn/css/first_steps/what_is_css/index.md
> +CSS 를 처음 접하는 사람들은, CSS specs 이 압도적이라고 생각할 것입니다 — 웹 개발자가 CSS 를 이해하기 위해 읽는 것이 아니라 엔지니어가 user agents 의 기능에 대한 지원을 구현하는 데 사용하기 위한 것입니다. 많은 숙련된 개발자는 MDN 설명서나 기타 자습서를 참조하는 것이 좋습니다. 그러나 사용중인 CSS, 브라우저 지원 (아
@wisedog 님, 제가 뭘 잘못 만든것인지, 원래 이렇게 되는것인지는 모르겠으나 계속 main 브랜치에 커밋이 주기적으로 쌓이는것 같습니다. (주기적으로 merge 하는데도 이렇게 되네요..)

아래처럼 wisedog 님께서 머지하실때 직접 리베이스나 머지 해주셔도 됩니다!

https://github.com/mdn/translated-content/pull/14126#issuecomment-1641143042

2023-07-21 07:20 UTC, wisedog commented on files/ko/learn/css/first_steps/what_is_css/index.md
> +CSS 를 처음 접하는 사람들은, CSS specs 이 압도적이라고 생각할 것입니다 — 웹 개발자가 CSS 를 이해하기 위해 읽는 것이 아니라 엔지니어가 user agents 의 기능에 대한 지원을 구현하는 데 사용하기 위한 것입니다. 많은 숙련된 개발자는 MDN 설명서나 기타 자습서를 참조하는 것이 좋습니다. 그러나 사용중인 CSS, 브라우저 지원 (아
넵 고생하셨습니다.

2023-07-21 07:21 UTC, wisedog approved these changes

2023-07-21 07:22 UTC, merged

2023-07-30 09:25 UTC, hochan222 commented on files/ko/learn/css/first_steps/what_is_css/index.md
> +CSS 를 처음 접하는 사람들은, CSS specs 이 압도적이라고 생각할 것입니다 — 웹 개발자가 CSS 를 이해하기 위해 읽는 것이 아니라 엔지니어가 user agents 의 기능에 대한 지원을 구현하는 데 사용하기 위한 것입니다. 많은 숙련된 개발자는 MDN 설명서나 기타 자습서를 참조하는 것이 좋습니다. 그러나 사용중인 CSS, 브라우저 지원 (아
@rbals0445 님, @wisedog 님 답변이 너무 늦어져서 정말 죄송합니다..

> 원본 커밋 당시의 내용과 "동일하다"는 전제로 넣는 내용이거든요.

추후 translated-content에서 문서의 `l10n.sourceCommit`와 content에서 해당 문서의 git hash와 비교해서 얼마나 뒤쳐졌는지 기준으로 삼을 예정입니다. 따라서, `l10n.sourceCommit`는 최소한 이 commit 까지의 변경은 보장한다의 의미로 이해하고 표기해주시면 좋을듯합니다. `l10n.sourceCommit` 시점보다 최신화 되어 있는건 이슈없을듯합니다.

참고차, [문서 갱신 표시 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md)에 따르면 `l10n.sourceCommit 메타데이터를 추가하여 현재 문서가 명시된 en-US의 hash 까지 최신 상태를 유지하고 있음을 나타낼 수 있습니다.`의 문장이 있습니다.

감사합니다. 좋은 하루 보내세요 :)