Improve IDBDatabase
mdn/translated-content pull request #14364
Opened 2023-07-18 13:02 UTC by mikecat

### Description

`IDBDatabase` の記述を改善。

* イベントの説明を英語版に基づいて書き直し
* ほか調整

### Motivation

### Additional details

### Related issues and pull requests

2023-07-18 14:55 UTC, mfuji09 requested changes
早めですが、1件の修正ををお願いします。

2023-07-18 14:55 UTC, mfuji09 commented on files/ja/web/api/idbdatabase/index.md
> +  - : 接続しているデータベース名を含む{{ domxref("DOMString") }}。
原文では DOMString が廃止されていますので、「文字列」などに書き換えてください。

2023-07-19 10:51 UTC, mikecat commented on files/ja/web/api/idbdatabase/index.md
> +  - : 接続しているデータベース名を含む{{ domxref("DOMString") }}。
修正しました。

2023-07-19 14:29 UTC, mfuji09 approved these changes
OKです。ありがとうございました。

2023-07-19 14:29 UTC, merged