[ko] modified: 'glossary/json' update and translate
mdn/translated-content pull request #14444
Opened 2023-07-20 08:23 UTC by etoile-j

### Description

`ko/docs/Glossary/JSON` 최신화와 함께 미번역 부분 번역하였습니다.

### Motivation

### Additional details

첫 문단의 web extension은
https://developer.mozilla.org/ko/docs/Mozilla/Add-ons/WebExtensions
를 참고해 ‘확장기능’으로 번역하였습니다.

### Related issues and pull requests

2023-07-30 16:38 UTC, hochan222 requested changes
@etoile-j 님 안녕하세요.

리뷰사항 하기에 남겨두었습니다.

기여해주셔서 감사합니다. 좋은 하루 보내세요 :)

2023-07-30 16:38 UTC, hochan222 commented on files/ko/glossary/json/index.md
> +  sourceCommit: ada5fa5ef15eadd44b549ecf906423b4a2092f34
👍👍

2023-07-30 16:38 UTC, hochan222 commented on files/ko/glossary/json/index.md
> +- [JSON](/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON) on MDN
```suggestion
- [JSON](/ko/docs/Web/JavaScript/Reference/Global_Objects/JSON) on MDN
```

[문서 연결 경로 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md)에 따라 ko로 변경 부탁드려요!

2023-07-31 04:52 UTC, etoile-j commented on files/ko/glossary/json/index.md
> +- [JSON](/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON) on MDN
리뷰 감사합니다!! 위키피디아 링크도 ko로 같이 수정하였습니다!

2023-07-31 12:53 UTC, hochan222 approved these changes
LGTM :)

2023-07-31 12:58 UTC, merged

2023-08-08 18:34 UTC, hochan222 commented
@etoile-j님 안녕하세요. 

현재 한국 문서들은 최신화 되어있지 않은 레거시 문서들이 많이 존재합니다. [[ko] 한국 MDN 문서에 존재하는 레거시 문서 최신화](https://github.com/mdn/translated-content/issues/14965)에서 한국 MDN 문서에 존재하는 레거시 문서 최신화를 위한 작업을 진행하고 있습니다. 

참고 부탁드립니다. 좋은 하루 보내세요 :)