페이지 번역
mdn/translated-content pull request #14454
Opened 2023-07-20 15:52 UTC by owjs3901

### Description
일정한 화법으로 변환

### Motivation

HTML 초보 분들을 위해

### Additional details

### Related issues and pull requests

2023-08-01 15:04 UTC, owjs3901 commented
@GwangYeol-Im 확인 부탁드립니다.

2023-08-06 07:55 UTC, GwangYeol-Im requested changes, later dismissed
@owjs3901 확인이 늦어 죄송합니다. 🥲 현재 ci 과정 살펴보았을 때 수정해주신 부분에서 prettier 충돌이 있는 것 같은데 이 부분 수정 뒤 멘션 부탁드립니다..!

2023-08-13 14:45 UTC, hochan222 approved these changes
@GwangYeol-Im 님 좋은 주말입니다~!  

prettier 오류 발생시 git action을 다시 돌려주면, 이제 위와같이 자동으로 suggestion이 생성됩니다! prettier 수정만 하면 되는 상태라면 git actions suggestion 적용 후 병합해도 좋을듯합니다.

@owjs3901 님, 고생 많으셨습니다. 

기여해주셔서 감사합니다. 모두 좋은 밤 보내세요 :)

2023-08-13 14:53 UTC, hochan222 commented
@owjs3901 님, @GwangYeol-Im 님, 쭉 보니 완벽하게 최신화는 되지 않은듯하여 머지하겠습니다~!

모두 고생 많으셨습니다. 좋은 주말 보내세요 :)

2023-08-13 14:54 UTC, merged