Update curl example in "Command line crash course"
mdn/translated-content pull request #14455
Opened 2023-07-20 16:22 UTC by queengooborg

This PR updates the examples for using `curl` across all locales, updating them to use localized links instead.

2023-07-20 16:27 UTC, cw118 approved these changes
LGTM for l10n-fr, thank you @queengooborg !

2023-07-20 16:29 UTC, yin1999 reviewed
Hi @queengooborg. This is a redirection example. So we may "need" to use `https://developer.mozilla.org/docs/Web/API/fetch`. As this would make the server to response a "location" header. The example in en-US seems also be wrong.

2023-07-20 16:29 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +因此，如果您使用 curl 请求 `https://developer.mozilla.org/zh-CN/docs/Web/API/fetch`，则不会得到输出。现在就试试：
```suggestion
因此，如果您使用 curl 请求 `https://developer.mozilla.org/docs/Web/API/fetch`，则不会得到输出。现在就试试：
```

2023-07-20 16:29 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
>  curl https://developer.mozilla.org/zh-CN/docs/Web/API/fetch
```suggestion
curl https://developer.mozilla.org/docs/Web/API/fetch
```

2023-07-20 16:29 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +curl https://developer.mozilla.org/zh-CN/docs/Web/API/fetch -L -I | grep location
```suggestion
curl https://developer.mozilla.org/docs/Web/API/fetch -L -I | grep location
```

2023-07-20 16:29 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +location: /zh-CN/docs/Web/API/fetch
```suggestion
location: /en-US/docs/Web/API/fetch
```

2023-07-20 16:29 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +curl https://developer.mozilla.org/zh-CN/docs/Web/API/fetch -L -I | grep location | awk '{ print "https://developer.mozilla.org" $2 }'
```suggestion
curl https://developer.mozilla.org/docs/Web/API/fetch -L -I | grep location | awk '{ print "https://developer.mozilla.org" $2 }'
```

2023-07-20 16:29 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +https://developer.mozilla.org/zh-CN/docs/Web/API/fetch
```suggestion
https://developer.mozilla.org/en-US/docs/Web/API/fetch
```

2023-07-20 16:43 UTC, cw118 requested changes
After taking a closer look at the contents/subject of the page, I agree with @yin1999, though it seems that the French version needs an update.

2023-07-20 18:03 UTC, cw118 reviewed
Just one small change, sorry for not being clear before 😖

The French content will need to be updated vs. en-US later, but I read the page more attentively and this example (for now) intentionally does not specify a locale.

2023-07-20 21:02 UTC, cw118 approved these changes
Thanks once again 🙏

2023-07-20 23:25 UTC, yin1999 approved these changes
LGTM for zh. Thanks 😊

2023-07-21 08:57 UTC, mfuji09 approved these changes
LGTM for `ja`. Thank you!

2023-07-21 09:08 UTC, merged