[zh-cn]: Update translation of String.matchAll()
mdn/translated-content pull request #14468
Opened 2023-07-21 01:17 UTC by JasonLamv-t

### Description

Same as the title.

### Motivation

Ditto.

### Additional details

None.

### Related issues and pull requests

#13975

2023-07-21 02:11 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/string/matchall/index.md
> +    如果 `regexp` 是一个[正则表达式对象](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp#正则表达式的特殊处理)，那么它必须设置了全局（`g`） 标志，否则会抛出一个 {{jsxref("TypeError")}} 异常。
extra space

2023-07-21 02:11 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/string/matchall/index.md
> +  - : 如果 `regexp` 是一个[正则表达式对象](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp#正则表达式的特殊处理)，且没有设置全局（`g`） 标志（其 [`flags`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp/flags) 属性不
same

2023-07-21 02:13 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/string/matchall/index.md
> +    如果 `regexp` 是一个[正则表达式对象](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp#正则表达式的特殊处理)，那么它必须设置了全局（`g`） 标志，否则会抛出一个 {{jsxref("TypeError")}} 异常。
```suggestion
    如果 `regexp` 是一个[正则表达式对象](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp#正则表达式的特殊处理)，那么它必须设置了全局（`g`）标志，否则会抛出一个 {{jsxref("TypeError")}} 异常。
```

2023-07-21 02:13 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/global_objects/string/matchall/index.md
> +  - : 如果 `regexp` 是一个[正则表达式对象](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp#正则表达式的特殊处理)，且没有设置全局（`g`） 标志（其 [`flags`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp/flags) 属性不
```suggestion
  - : 如果 `regexp` 是一个[正则表达式对象](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp#正则表达式的特殊处理)，且没有设置全局（`g`）标志（其 [`flags`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp/flags) 属性不包含 `"g"`），则会抛出该异常。
```

2023-07-21 05:47 UTC, yin1999 requested changes

2023-07-21 05:47 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/string/matchall/index.md
> +**`matchAll()`** 方法返回一个迭代器，用于匹配一个字符串和一个[正则表达式](/zh-CN/docs/Web/JavaScript/Guide/Regular_expressions)，包括[捕获组](/zh-CN/docs/Web/JavaScript/Guide/Regular_expressions/Groups_and_backreferences)在内的所有结果。
翻译再改改

2023-07-21 05:47 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/string/matchall/index.md
> +    如果 `regexp` 是一个[正则表达式对象](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp#正则表达式的特殊处理)，那么它必须设置了全局（`g`）标志，否则会抛出一个 {{jsxref("TypeError")}} 异常。
```suggestion
    如果 `regexp` 是一个[正则表达式](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp#正则表达式的特殊处理)，那么它必须设置了全局（`g`）标志，否则会抛出 {{jsxref("TypeError")}} 异常。
```

2023-07-21 05:47 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/string/matchall/index.md
> +一个匹配结果的[可迭代的迭代器对象](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Iterator)（它不可重新开始）。每个匹配结果都是一个数组，其形状与 {{jsxref("RegExp.prototype.exec()")}} 的返回值相同。
```suggestion
一个匹配结果的[可迭代迭代器对象](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Iterator)（它不可重新开始）。每个匹配结果都是一个数组，其形状与 {{jsxref("RegExp.prototype.exec()")}} 的返回值相同。
```

2023-07-21 05:47 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/string/matchall/index.md
> +  - : 如果 `regexp` 是一个[正则表达式对象](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp#正则表达式的特殊处理)，且没有设置全局（`g`）标志（其 [`flags`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp/flags) 属性不包
```suggestion
  - : 如果 `regexp` 是一个[正则表达式](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp#正则表达式的特殊处理)，且没有设置全局（`g`）标志（其 [`flags`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp/flags) 属性不包含 `"g"`），则会抛出该异常。
```

2023-07-21 05:47 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/string/matchall/index.md
> +有了可用的 `matchAll()` 方法，可以避免使用 `while` 循环和带有 `g` 标志的 `exec`。相反，你可以获得一个迭代器，以便使用更方便的 `for...of` 循环、[数组展开语法](/zh-CN/docs/Web/JavaScript/Reference/Operators/Spread_syntax)或者 `Array.from()` 构造函数：
```suggestion
如果有 `matchAll()` 方法，则可以避免使用 {{jsxref("Statements/while", "while")}} 循环和带有 `g` 标志的 `exec`。相反，你可以获得一个迭代器，以便使用更方便的 {{jsxref("Statements/for...of", "for...of")}} 循环、[数组展开语法](/zh-CN/docs/Web/JavaScript/Reference/Operators/Spread_syntax)或 `Array.from()` 构造函数：
```

2023-07-21 05:47 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/string/matchall/index.md
>  如果没有 `/g` 标志，`matchAll` 会抛出异常。
```suggestion
如果没有 `g` 标志，`matchAll` 会抛出异常。
```

2023-07-21 05:47 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/string/matchall/index.md
> +`matchAll` 内部做了一个 `regexp` 的复制，所以不像 {{jsxref("Global_Objects/RegExp/exec", "regexp.exec()")}}，`lastIndex` 在字符串扫描时不会改变。
```suggestion
`matchAll` 内部做了一个 `regexp` 的复制，所以不像 {{jsxref("Global_Objects/RegExp/exec", "regexp.exec()")}}，`lastIndex` 在扫描字符串后不会改变。
```

2023-07-21 05:47 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/string/matchall/index.md
> +`matchAll()` 方法的另一个重要优点是改进了对于捕获组的获取方式。
请将“方法名加括号”的修改同步至英文文档

2023-07-21 05:47 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/string/matchall/index.md
> +使用 `matchAll()` 方法，可以轻松获取捕获组：
包括下面的修改

2023-07-21 05:47 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/string/matchall/index.md
> +### 使用一个没有实现 @@matchAll 的非正则对象调用 matchAll()
```suggestion
### 使用实现了 @@matchAll 的非正则对象调用 matchAll()
```

2023-07-28 00:32 UTC, yin1999 approved these changes
Thanks. Looks better 😉

2023-07-28 00:33 UTC, merged