HTML 디버깅 페이지 일부 번역
mdn/translated-content pull request #14502
Opened 2023-07-22 07:36 UTC by owjs3901

### Description

영어 문장을 한글로 일부 번역했습니다.

`Next, open it in a browser. You will see something like this:`

위 문장을 아래와 같이 번역하였습니다.

`다음으로, 브라우저에서 다운로드 받은 파일을 여세요. 그렇다면 브라우저에서 아래와 같이 보일겁니다.`

### Motivation

아직 언어의 장벽을 넘지 못한 한국인들이 너무나 많습니다.

이런 현실에 조금이나마 개발자 교육에 기여하고 싶어서 기여를 하게 되었습니다.

2023-07-23 00:52 UTC, wisedog requested changes
PR은 기본적으로 한 문서의 전체 변경을 전제로 합니다. [가이드](https://github.com/mdn/translated-content/blob/main/docs/ko/README.md)를 참고하시기 바랍니다. 

따라서 `en-US`문서와 일치 부탁드리고 영어로 남은 부분까지 모두 한글로 변경 부탁드리겠습니다.

2023-07-23 00:52 UTC, wisedog commented on files/ko/learn/html/introduction_to_html/debugging_html/index.md
>  3. This immediately doesn't look great; let's look at the source code to see if we can work out why (only the body contents are shown):
영어가 남은 부분이 있습니다.

2023-07-23 14:48 UTC, owjs3901 commented on files/ko/learn/html/introduction_to_html/debugging_html/index.md
>  3. This immediately doesn't look great; let's look at the source code to see if we can work out why (only the body contents are shown):
감사합니다, draft로 변경하여 다른 부분까지 모두 번역 진행하겠습니다.

2023-07-30 06:31 UTC, owjs3901 commented
아직 작업 중 ㅇ비니다

2023-08-19 11:21 UTC, hochan222 commented
@owjs3901 님 안녕하세요. 

PR Pending이 3주가 지나 멘션드리게되었습니다. 1주 이내로 추가적인 변경사항이 없으면 다른 기여자분들을 위해 PR closed 진행하고자하여 알림 드립니다.

기여해주셔서 정말 감사합니다. 좋은 주말 보내세요 :)

2023-08-28 08:51 UTC, closed without merging