Introducing a complete toolchain の翻訳
mdn/translated-content pull request #14511
Opened 2023-07-22 10:06 UTC by gurezo

@hmatrjp @potappo @mfuji09 

### issue
- [   Introducing a complete toolchain の翻訳 #704  ](https://github.com/mozilla-japan/translation/issues/704)  のPRです。

### translated-content
#### 以下のセクション毎にコミットしてあります。

2023-07-22 17:42 UTC, mfuji09 requested changes
英語版記事に含まれる画像は、画像をローカライズした場合を除いて、コミットには含めないようお願いします。

2023-07-22 17:51 UTC, mfuji09 requested changes
表記上の問題をいくつか指摘しましたので、よろしくお願いします。

2023-07-22 17:51 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain/index.md
> +1. コード・ファイルを入手するには、<https://github.com/remy/mdn-will-it-miss> にアクセスし、このリポジトリーの内容をローカル ドライブのどこかにダウンロードして解凍します。 _Clone or download_ > _Download ZIP_ を選択すると、プロジェクト全体を zip ファイルとしてダウンロードできます。
特に必要でない限りは、カタカナ語の単語間に・や空白を置かないでください。
他の部分も同様にチェックをお願いします。

```suggestion
1. コードファイルを入手するには、<https://github.com/remy/mdn-will-it-miss> にアクセスし、このリポジトリーの内容をローカルドライブのどこかにダウンロードして解凍します。 _Clone or download_ > _Download ZIP_ を選択すると、プロジェクト全体を zip ファイルとしてダウンロードできます。
```

2023-07-22 17:51 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain/index.md
> +3. 次にウェブサイトのすべての開発コードが存在する新しいディレクトリを作成します。今すぐ次のコマンドを実行します。
ディレクトリ→ディレクトリーと表記してください。

2023-07-22 17:51 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain/index.md
> +4. ただし、このプロジェクトのソースファイルでは、React JSX構文を使用しています（実際のプロジェクトではReactやVueなどのフレームワーク、またはフレームワークを使用しない場合もあります！）。
この辺りで、英数字と日本語の間に空白がない箇所がありますので修正してください。

2023-07-22 17:51 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain/index.md
> +5. プロジェクトフォルダのルートで、以下のターミナルコマンドを実行してください。
フォルダ→フォルダーと表記してください。

2023-07-24 12:56 UTC, gurezo commented
> 英語版記事に含まれる画像は、画像をローカライズした場合を除いて、コミットには含めないようお願いします。

https://github.com/mdn/translated-content/pull/14511/commits/104b379e86de66c7aff35ab396485a1c51a75f29

2023-07-24 12:57 UTC, gurezo commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain/index.md
> +3. 次にウェブサイトのすべての開発コードが存在する新しいディレクトリを作成します。今すぐ次のコマンドを実行します。
https://github.com/mdn/translated-content/pull/14511/commits/232debb318c592fa2c404608f69cbbefa09fcd29

2023-07-24 12:57 UTC, gurezo commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain/index.md
> +5. プロジェクトフォルダのルートで、以下のターミナルコマンドを実行してください。
https://github.com/mdn/translated-content/pull/14511/commits/6c15705d83b63377361ab42ee13231b37412412e

2023-07-24 12:57 UTC, gurezo commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain/index.md
> +4. ただし、このプロジェクトのソースファイルでは、React JSX構文を使用しています（実際のプロジェクトではReactやVueなどのフレームワーク、またはフレームワークを使用しない場合もあります！）。
https://github.com/mdn/translated-content/pull/14511/commits/5a4be3ae8fc1047f18b3bfb508c9cf8c6b862cd2

2023-07-26 00:23 UTC, mfuji09 approved these changes
OKです。

2023-07-26 00:23 UTC, merged