Update and rename index.md to 오타수정&중복제거
mdn/translated-content pull request #14515
Opened 2023-07-22 14:45 UTC by BORA040126

존댓말 수정&중복제거

2023-07-23 00:46 UTC, wisedog requested changes
안녕하세요, 첫 기여 감사합니다. 

기여하실때 [지켜야 할 사항](https://github.com/mdn/translated-content/blob/main/docs/ko/README.md)을 확인해주시구요. 더불어 [번역안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md)와 [용어](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md)를 한 번 읽어주시면 좋겠습니다.

그리고 지금 이 PR 말고 @BORA040126 님이 올리신 다른 PR때문에 그런데요. PR은 기본적으로 한 페이지 전체의 변경을 담아야하고 `en-US` 원본과 동일해야 한다는 점 알아두셨으면 합니다.

2023-07-23 00:46 UTC, wisedog commented on files/ko/glossary/python/오타수정&중복제거
>  ---
`en-US` 문서의 {{GlossarySidebar}}가 빠졌습니다.

2023-07-23 00:46 UTC, wisedog commented on files/ko/glossary/python/오타수정&중복제거
> +**Python** 은 고도의 범용 프로그래밍 언어입니다. 그것은 절차적, 객체지향적, 그리고 일부 기능적 프로그래밍 구조를 지원하는 다변수적 접근방식을 사용합니다.
`en-US`의 `some functional programming` 부분이 `기능적`이 아니라 `함수형`으로 해석해야 옳지 않을까 합니다.

2023-07-23 00:46 UTC, wisedog commented on files/ko/glossary/python/오타수정&중복제거
> +1985년에서 1990년 사이에 다른 언어(ABC라고 불리는)의 계승자로 불리는 귀도 반 로섬에 의해 만들어졌으며, 현재는 웹 개발, 데스크톱 애플리케이션, 데이터 과학, DevOps, 자동화/생산성과 같은 다양한 영역에서 사용되고 있습니다.
원문 `It was created by Guido van Rossum as a successor to another language (called ABC) between 1985 and 1990`이 여기서는 `1985년에서 1990년 사이에 다른 언어(ABC라고 불리는)의 계승자로 불리는 귀도 반 로섬에 의해 만들어졌으며`라고 해석되어 있는데, 귀도 반 로섬이 계승자가 아니라.. 음... 

위 문장은 `1985년에서 1990년 사이에 귀도 반 로썸(Guido van Rossum)이 ABC라는 다른 언어의 후속으로 만들었으며`로 해석해야지 정확힌 문장이 아닐까 합니다.

2023-07-23 00:46 UTC, wisedog commented on files/ko/glossary/python/오타수정&중복제거
> +Python은 OSI가 승인한 오픈 소스 라이센스로 개발되어 상업적인 용도로도 자유롭게 사용할 수 있습니다. Python의 라이선스는 [Python Software Foundation](https://www.python.org/psf)에 의해 관리됩니다.
원문의 `배포` 내용이 빠져 있습니다. 

또한 `~에 의해 관리됩니다`라는 수동태보다는 `에서 관리합니다`라는 말이 맞겠습니다.

2023-07-23 00:46 UTC, wisedog commented on files/ko/glossary/python/오타수정&중복제거
>  slug: Glossary/Python
`sourceCommit` 메타데이터가 빠졌습니다. [메타데이터 가이드](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md)를 참고해주세요.

2023-07-23 01:25 UTC, wisedog commented
추가적으로 말씀을 드리자면 @BORA040126  님의 커밋이나 PR이 좀 더 이해 당사자에게 친절하게 적어주시면 좋겠습니다. 😁

프로그래밍은 무조건 협업이 바탕입니다. PR을 하는 사람은 하루에 많은 수의 PR을 볼텐데 `ko: 존댓말 수정&중복제거` 이 PR 제목이면 뭔가 싶기도 하고 나중에 검색할때도 좋지 않습니다. 

또한 커밋도 나중에 거대한 코드베이스에 들어갈텐데 `Update and rename index.md to 오타수정&중복제거` 라 되어 있으면 어느 파일의 오타와 중복을 제거했다는 건지도 알 수 없습니다. 게다가 지금 PR내용과 커밋 내용은 다릅니다.

일관되고 명확한 커밋 메시지는 다른 개발자가 @BORA040126 님의 작업을 더 쉽고 직관적으로 이해할 수 있는 단서가 됩니다. 
좋은 커밋 메시지 작성법은 웹상에 많이 나와있으니 찾아보시면 되고, 약간 잔소리 같긴 하지만 이제 막 프로그래밍에 입문하신 분 같아서 좀 더 이 말 저말 얹었습니다. (CAU라서 그런건 아닙니다 😉)

2023-07-23 10:40 UTC, BORA040126 commented
조언 감사드립니다. PR의 시스템을 몰라서 커밋 메시지에 수정한 것을 쓸 생각을 못 했네요. GLOSSARY SIDE BAR라는
시스템을 모르겠어서ㅠㅠ 수정은 못 할 듯 합니다. 아직 마크다운 언어를 몰라서
저는 이번에 오픈소스 컨트리뷰션 아카데미 MDN 한글화 번역 팀의 멘티고 어제 첫 모임이었어서 PR 처음으로 해봤는데(협업을 해본 적이
없습니다) 저 같은 초보에게 귀중한 조언 감사드립니다!

2023년 7월 23일 (일) 오전 10:25, Jongha Kim ***@***.***>님이 작성:

> 추가적으로 말씀을 드리자면 @BORA040126 <https://github.com/BORA040126> 님의 커밋이나 PR이 좀
> 더 이해 당사자에게 친절하게 적어주시면 좋겠습니다. 😁
>
> 프로그래밍은 무조건 협업이 바탕입니다. PR을 하는 사람은 하루에 많은 수의 PR을 볼텐데 ko: 존댓말 수정&중복제거 이 PR
> 제목이면 뭔가 싶기도 하고 나중에 검색할때도 좋지 않습니다.
>
> 또한 커밋도 나중에 거대한 코드베이스에 들어갈텐데 Update and rename index.md to 오타수정&중복제거 라 되어
> 있으면 어느 파일의 오타와 중복을 제거했다는 건지도 알 수 없습니다. 게다가 지금 PR내용과 커밋 내용은 다릅니다.
>
> 일관되고 명확한 커밋 메시지는 다른 개발자가 @BORA040126 <https://github.com/BORA040126> 님의
> 작업을 더 쉽고 직관적으로 이해할 수 있는 단서가 됩니다.
> 좋은 커밋 메시지 작성법은 웹상에 많이 나와있으니 찾아보시면 되고, 약간 잔소리 같긴 하지만 이제 막 프로그래밍에 입문하신 분 같아서
> 좀 더 이 말 저말 얹었습니다. (CAU라서 그런건 아닙니다 😉)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mdn/translated-content/pull/14515#issuecomment-1646717283>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVEOQBMPVVT22NN3C7O7GJTXRR4RFANCNFSM6AAAAAA2T4DLLQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-23 23:09 UTC, wisedog commented
@BORA040126 
안녕하세요. 수정을 해야지만 PR이 Merge됩니다. 좋은 git 사용법이나 PR 방법은 멘토분께 여쭤보시면 친절하게 답변주시리라 생각합니다. 이런 PR을 완료시키는것까지 멘토의 역할이니 적극적인 멘토 역할을 주문 바랍니다. 

감사합니다.

2023-07-30 04:54 UTC, BORA040126 commented
@wisedog 
- glossary side bar 추가
- source commit 메타데이터 추가
- 오번역 수정
- 수동태 수정
-  page type 추가

2023-07-30 05:46 UTC, wisedog commented
안녕하세요. @BORA040126  수정 감사합니다.

다만 기존 index.md 를 삭제하시고 별도의 파일을 만드셔서 에러가 난 것 같습니다. 확인 부탁드리겠습니다.

2023-07-30 05:53 UTC, wisedog commented on files/ko/glossary/python/오타수정&중복제거
> +page-type: glossary-definition
문서의 상단에 있는 메타데이터는 title, short-title, slug 그리고 l10n.*만 사용합니다. (참고: #7412)

2023-07-30 06:38 UTC, BORA040126 commented
@wisedog 
-index.md 복원했습니다. 
-수정 사항 다시 반영했습니다

2023-07-30 07:13 UTC, wisedog approved these changes

2023-07-30 07:13 UTC, merged

2023-07-30 07:13 UTC, wisedog commented
고생하셨습니다. 나머지 PR도 마찬가지로 처리 부탁드립니다.