ADD javascript get own property descriptors 번역
mdn/translated-content pull request #1453
Opened 2021-07-08 17:02 UTC by EchoHertz

_/ko/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptors_
Object.getOwnPropertyDescriptors()

번역하였습니다.

PR부탁드립니다.

2021-07-10 15:19 UTC, cos18 requested changes
기여 감사드립니다! 몇몇 확인하실 부분이 있어 리뷰드립니다.

2021-07-10 15:19 UTC, cos18 commented on files/ko/web/javascript/reference/global_objects/object/getownpropertydescriptors/index.html
> +<h3 id="Creating_a_subclass">하위 클래스 만들기</h3>
```suggestion
<h3 id="Creating_a_subclass">서브클래스 만들기</h3>
```

![Screen Shot 2021-07-11 at 12 13 49 AM](https://user-images.githubusercontent.com/33975709/125167744-f6868d80-e1dc-11eb-8b37-6961e3a10ff7.png)

`superclass` -> `슈퍼 클래스` / `subclass` -> `하위 클래스` 로 번역하셔서 이 둘 단어가 서로 어색해 [MS Terminology 사이트](https://www.microsoft.com/en-us/language)를 확인해본 결과 두 단어 모두 영어 발음대로 번역하는 것을 확인했습니다. 해당 내용에 맞게 수정하시길 추천드립니다.

2021-07-11 06:36 UTC, EchoHertz commented on files/ko/web/javascript/reference/global_objects/object/getownpropertydescriptors/index.html
> +<h3 id="Creating_a_subclass">하위 클래스 만들기</h3>
추천해 주신 바가 더 자연스러울것 같아 내용 반영했습니다.
:)

2021-07-11 07:50 UTC, cos18 approved these changes
LGTM 😄

2021-07-11 07:50 UTC, merged

2021-07-11 10:16 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/object/getownpropertydescriptors/index.html
> +<h3 id="Creating_a_subclass">하위 클래스 만들기</h3>
@cos18 혹시 해당 사항들에 대해서 이번 단어 안건에 올려주실 수 있으신가요?