feat: add instruction about image
mdn/translated-content pull request #14628
Opened 2023-07-27 04:21 UTC by striderkein

existing in the en but not in the ja

Instruction about image is existing in the English version but not in the Japanese version.
so I added it.

### Description

add instruction about image in Japanese

### Motivation

for the convenience of the developer"

### Additional details

### Related issues and pull requests

no related exists

2023-07-27 14:24 UTC, mfuji09 requested changes
警告の通り、 /en-us/ のリンク先は /ja/ のリンク先へ修正してください。
なお、日本語訳の記事におけるレビュアーは全員が日本人ですので、プルリクエストは日本語でどうぞ。

2023-07-28 04:41 UTC, striderkein commented
@mfuji09 コメントありがとうございます。ワーニングの 2 箇所を修正しましたのでご確認お願い致します

2023-07-30 17:42 UTC, mfuji09 requested changes
警告の指摘事項が修正されていないので、修正方法を書いておきました。
再修正をお願いします。

2023-07-30 17:42 UTC, mfuji09 commented on files/ja/glossary/intrinsic_size/index.md
> +画像の場合もテキストと同じ意味を持ちます。これは、CSS の適用によって描画が変更されなかった場合に表示される画像の大きさです。デフォルトでは、画像は「1x」のピクセル密度（1 デバイスピクセル = 1 CSS ピクセル）を持つものと見なされるため、固有サイズは単純にピクセルの高さと幅です。内在サイズと解像度は [EXIF]([https://developer.mozilla.org/en-U
警告の内容は、"developer.mozilla.org” サイト内のリンクにはドメイン名を入れないという意味です。

英語版で {{Glossary}} マクロを使用して作成したリンクは、日本語版でもマクロにしておいてください。
それ以外のリンクでは、MDN のサイト内へのリンクの場合は `/ja/` 以下のパスのみを記述してください。

以下、修正例ですので、参考にしてください。

```suggestion
画像の場合もテキストと同じ意味を持ちます。これは、CSS の適用によって描画が変更されなかった場合に表示される画像の大きさです。デフォルトでは、画像は「1x」のピクセル密度（1 デバイスピクセル = 1 CSS ピクセル）を持つものと見なされるため、固有サイズは単純にピクセルの高さと幅です。内在サイズと解像度は {{Glossary("EXIF")}} データで明示的に指定することもできます。また、 [`srcset`](/ja/docs/Web/HTML/Element/img#srcset) 属性を使用して画像の固有ピクセル密度も設定できます（ただし、両方のメカニズムを使用する場合は、 `srcset` の値が EXIF 値を「上書き」します）。
```

2023-08-04 07:53 UTC, mfuji09 approved these changes
修正ありがとうございます。OKです。

2023-08-04 07:55 UTC, merged