Перевод "Constraint validation API"
mdn/translated-content pull request #1466
Opened 2021-07-09 20:01 UTC by hisbvdis

Оригинальная статья: https://developer.mozilla.org/en-US/docs/Web/API/Constraint_validation

2021-07-23 08:21 UTC, hisbvdis commented
Прошло 2 недели..........

2021-07-29 13:47 UTC, sashasushko requested changes
@hisbvdis спасибо за перевод. Накидал своих саджестов. Где-то просто захотелось более доступно перефразировать, где-то опечатки или ошибки отловил.

Если с чем-то не согласен, откомменть саджест, пожалуйста.

2021-07-29 13:47 UTC, sashasushko commented on files/ru/web/api/constraint_validation/index.html
> +<p>Однако, вы можете задать более сложные ограничения или обеспечить более понятные сообщения об ошибках валидации, чем предусмотрены по умолчанию. Это можно сделать с помощью Constraint Validation A
```suggestion
<p>Для более сложных ограничений или для замены штатных сообщений об ошибках валидации на более понятные можно использовать Constraint Validation API.</p>
```

2021-07-29 13:47 UTC, sashasushko commented on files/ru/web/api/constraint_validation/index.html
> +<p><strong>Примечание:</strong> Валидация ограничений на стороне клиента не отменяет необходимости производить валидацию на стороне сервера. Даже при том, что валидация на стороне клиента может предо
```suggestion
<p><strong>Примечание:</strong> Валидация ограничений на стороне клиента не отменяет необходимости производить валидацию на стороне сервера. Даже при том, что валидация на стороне клиента может предотвратить многие распространённые типы не валидных значений, они всё ещё могут быть отправлены устаревшими браузерами или злоумышленниками, которые пытаются навредить вашему веб-приложению. Следовательно, вам по-прежнему нужно валидировать значения как на стороне клиента, так и на стороне сервера. Валидация на стороне клиента даёт пользователю быструю обратную связь, повышая удобство работы с интерфейсом. Но вы не должны полностью полагаться на неё в вопросе проверки данных, которые отправляются на сервер.</p>
```

2021-07-29 13:47 UTC, sashasushko commented on files/ru/web/api/constraint_validation/index.html
> + <dd>Интерфейс ValidityState представляет <em>состояния валидации</em>, которые может иметь элемент формы, с учётом определённых им ограничений. Вместе они помогают объяснить, была ли ошибка валидаци
```suggestion
 <dd>Интерфейс ValidityState содержит <em>состояния валидации</em>, которые применяются к элементу формы, с учётом указанных для элемента ограничений. По состоянию можно понять, была ли ошибка валидации и почему.</dd>
```

2021-07-29 13:47 UTC, sashasushko commented on files/ru/web/api/constraint_validation/index.html
> + <dd>Этот тип события запускается на элементе формы, если элемент не удовлетворяет ограничениям.</dd>
```suggestion
 <dd>Этот тип события запускается на элементе формы, если значение элемента не удовлетворяет ограничениям.</dd>
```

2021-07-29 13:47 UTC, sashasushko commented on files/ru/web/api/constraint_validation/index.html
> + <dd>Свойство, доступное только для чтения, которое возвращает объект <code><a href="/en-US/docs/Web/API/ValidityState">ValidityState</a></code>, свойства которого представляют ошибки валидации значе
```suggestion
 <dd>Свойство, доступное только для чтения, которое возвращает объект <code><a href="/en-US/docs/Web/API/ValidityState">ValidityState</a></code>, содержащий ошибки валидации значения данного элемента.</dd>
```

2021-07-29 13:47 UTC, sashasushko commented on files/ru/web/api/constraint_validation/index.html
> +<p>Если вы попытаетесь отправить форму с пустым полем, или полем, имеющим значение, не соответствующее шаблону в атрибуте <code><a href="/en-US/docs/Web/HTML/Attributes/pattern">pattern</a></code>, б
```suggestion
<p>Если вы попытаетесь отправить форму с пустым полем, или полем, значение которого не соответствует шаблону в атрибуте <code><a href="/en-US/docs/Web/HTML/Attributes/pattern">pattern</a></code> (только строчные и заглавные латинские буквы), базовый механизм валидации HTML-формы приведёт к появлению сообщения об ошибке, дизайн которого определяется браузером и операционной системой.</p>
```

2021-07-29 13:47 UTC, sashasushko commented on files/ru/web/api/constraint_validation/index.html
> +<p>Если вы хотели вместо этого отобразить кастомное сообщение об ошибке, следует использовать JavaScript, как показано ниже:</p>
```suggestion
<p>Если вы хотите вместо этого отобразить своё сообщение об ошибке, вам потребуется написать JavaScript-код вроде того, что показан ниже:</p>
```

2021-07-29 13:47 UTC, sashasushko commented on files/ru/web/api/constraint_validation/index.html
> +<p>Пример выглядит так:</p>
```suggestion
<p>Живой пример формы со своим сообщением об ошибке:</p>
```

2021-07-29 13:47 UTC, sashasushko commented on files/ru/web/api/constraint_validation/index.html
> +<p>Вкратце:</p>
```suggestion
<p>Как это работает:</p>
```

2021-07-29 13:47 UTC, sashasushko commented on files/ru/web/api/constraint_validation/index.html
> + <li>Если значение не валидно, происходит событие <code>invalid</code>, и запускается обработчик события <code>invalid</code>. Внутри этой функции с помощью блока <code>if()</code> мы выясняем, почем
```suggestion
 <li>Если значение не валидно, происходит событие <code>invalid</code> и срабатывает обработчик события <code>invalid</code>. Внутри обработчика с помощью условия <code>if...else</code> мы выясняем, почему значение является невалидным: из-за того, что строка пустая или потому что она не соответствует шаблону, и в зависимости от условия задаём своё сообщение об ошибке валидации.</li>
```

2021-07-29 13:47 UTC, sashasushko commented on files/ru/web/api/constraint_validation/index.html
> + <li>В результате, если при нажатии кнопки отправки формы значение input не валидно, отобразится одно из кастомных сообщений об ошибке.</li>
```suggestion
 <li>В результате при попытке отправить форму, если значение input не валидно, отобразится одно из наших сообщений об ошибке.</li>
```

2021-07-29 13:47 UTC, sashasushko commented on files/ru/web/api/constraint_validation/index.html
> + <li>Если поле валидно, как и ожидалось, форма будет отправлена. Чтобы это произошло, нужно отменить кастомную валидность, вызвав метод <code>setCustomValidity()</code> с пустой строкой. Поэтому мы д
```suggestion
 <li>Если поле валидно, как и ожидалось, форма будет отправлена. Но чтобы это произошло, нужно сбросить наше сообщение об ошибке, вызвав метод <code>setCustomValidity()</code> с пустой строкой в качестве аргумента. В примере это происходит каждый раз, когда случается событие <code>input</code>. Если этого не сделать, браузер будет показывать ошибку валидации, указанную ранее, даже если поле в данный момент содержит валидные данные.</li>
```

2021-07-29 13:47 UTC, sashasushko commented on files/ru/web/api/constraint_validation/index.html
> +<p><strong>Примечание</strong>: На протяжении многих версий браузер Firefox поддерживал собственный атрибут ошибки <code>x-moz-errormessage</code>, который позволял аналогичным образом устанавливать
```suggestion
<p><strong>Примечание</strong>: На протяжении многих версий браузер Firefox поддерживал собственный атрибут ошибки <code>x-moz-errormessage</code>, который позволял аналогичным образом устанавливать свои сообщения об ошибке. Данный атрибут был удалён в версии 66 (смотрите <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1513890">bug 1513890</a>).</p>
```

2021-07-29 13:47 UTC, sashasushko commented on files/ru/web/api/constraint_validation/index.html
> +<h2 id="See_also">Также смотрите</h2>
```suggestion
<h2 id="See_also">Смотрите также</h2>
```

2021-07-29 13:47 UTC, sashasushko commented on files/ru/web/api/constraint_validation/index.html
> + <li><code>Свойства {{domxref('ValidityState')}}</code>: {{domxref('validityState.badInput', 'badInput')}}, {{domxref('validityState.customError','customError')}}, {{domxref('validityState.patternMis
```suggestion
 <li><code>Свойства {{domxref('ValidityState')}}</code>: {{domxref('validityState.badInput', 'badInput')}}, {{domxref('validityState.customError','customError')}}, {{domxref('validityState.patternMismatch','patternMismatch')}}, {{domxref('validityState.rangeOverflow','rangeOverflow')}}, {{domxref('validityState.rangeUnderflow','rangeUnderflow')}}, {{domxref('validityState.stepMismatch','stepMismatch')}}, {{domxref('validityState.tooLong','tooLong')}}, {{domxref('validityState.tooShort','tooShort')}}, {{domxref('validityState.typeMismatch','typeMismatch')}}, {{domxref('validityState.valid','valid')}} и {{domxref('validityState.valueMissing','valueMissing')}}.</li>
```

2021-07-29 14:14 UTC, hisbvdis commented
@sashasushko , спасибо за корректировки

2021-07-30 09:29 UTC, sashasushko reviewed
Нашёл спеллером ещё одну ошибку.

2021-07-30 09:29 UTC, sashasushko commented on files/ru/web/api/constraint_validation/index.html
> +<p><strong>Примечание:</strong> Валидация ограничений на стороне клиента не отменяет необходимости производить валидацию на стороне сервера. Даже при том, что валидация на стороне клиента может предо
```suggestion
<p><strong>Примечание:</strong> Валидация ограничений на стороне клиента не отменяет необходимости производить валидацию на стороне сервера. Даже при том, что валидация на стороне клиента может предотвратить многие распространённые типы невалидных значений, они всё ещё могут быть отправлены устаревшими браузерами или злоумышленниками, которые пытаются навредить вашему веб-приложению. Следовательно, вам по-прежнему нужно валидировать значения как на стороне клиента, так и на стороне сервера. Валидация на стороне клиента даёт пользователю быструю обратную связь, повышая удобство работы с интерфейсом. Но вы не должны полностью полагаться на неё в вопросе проверки данных, которые отправляются на сервер.</p>
```

2021-07-30 10:37 UTC, sashasushko approved these changes

2021-07-30 10:39 UTC, merged

2021-07-30 10:39 UTC, sashasushko commented
@hisbvdis, вмёржил. Ещё раз спасибо.

2021-07-30 11:24 UTC, hisbvdis commented
@sashasushko, спасибо за помощь