작업 중(하이퍼링크 만들기)
mdn/translated-content pull request #14750
Opened 2023-07-30 07:44 UTC by 2kkeullim

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-08-10 12:32 UTC, pje1740 requested changes
긴 글인데 고생 많으셨습니다! 몇가지만 확인 부탁 드리겠습니다 😊

2023-08-10 12:32 UTC, pje1740 commented on files/ko/learn/html/introduction_to_html/creating_hyperlinks/index.md
>  ![frontpage of bbc.co.uk, showing many news items, and navigation menu functionality](bbc-homepage.png)
최신 기준으로는 이미지도 다음으로 변경된 거 같습니다.
```suggestion
![front page of bbc.co.uk, showing many news items, and navigation menu functionality](updated-bbc-website.png)
```

2023-08-12 08:31 UTC, 2kkeullim commented
@pje1740 수정했습니다!

2023-08-13 10:28 UTC, pje1740 commented
하루 사이에 다시 컨플릭이 발생하네요 😅 괜찮으시다면 제가 rebase 해도 되고, 혹시라도 제가 하면서 손실되는 부분이 걱정되신다면 직접 다시 rebase 부탁 드리겠습니다!

2023-08-14 00:52 UTC, 2kkeullim commented
@pje1740 merge conflict 해결했습니다!

2023-08-14 01:10 UTC, pje1740 approved these changes
컨플릭 해결까지 고생 많으셨습니다!

2023-08-14 01:10 UTC, merged