docs: update feature policy to permissions policy
mdn/translated-content pull request #14767
Opened 2023-07-30 19:01 UTC by konojunya

### Description

Since it was renamed

2023-07-31 08:31 UTC, konojunya commented
do not merge.

There are mistakes in Japanese content.
For example, value must be `camera=()` instead of `camera=none`, but the documentation has not been updated to do so.
If the URL is broken, please wait for a commit to add a link to the English version.
https://w3c.github.io/webappsec-permissions-policy/#example-cd5e6c93

2023-08-02 09:27 UTC, mfuji09 requested changes
いくつかコメントを入れましたので、参照してください。

2023-08-02 09:27 UTC, mfuji09 commented on files/ja/web/http/headers/permissions-policy/index.md
> +詳しくは、[機能ポリシー](/ja/docs/Web/HTTP/Permissions_Policy)の記事を参照してください。
リンク先の記事の名前はまだ変わっていませんが、Permission Policy にするのであれば、「機能ポリシー」ではなく「権限ポリシー」であるべきだと思います。

2023-08-02 09:42 UTC, konojunya commented on files/ja/web/http/headers/permissions-policy/index.md
> +詳しくは、[機能ポリシー](/ja/docs/Web/HTTP/Permissions_Policy)の記事を参照してください。
修正しました

https://github.com/mdn/translated-content/pull/14767/commits/ba8aa52bf77a7046ae3b77ec98451d652b0c41ca

2023-08-02 09:42 UTC, konojunya commented on files/ja/web/http/headers/permissions-policy/index.md
> +ブラウザがサポートしている場合、許可リストで複数の異なるサブドメインを明示的に指定する代わりに許可ポリシーのオリジンにワイルドカードを含めることができます。
修正しました
https://github.com/mdn/translated-content/pull/14767/commits/71910cf36e3fd01b4931f745ae538422ca8a9bba

2023-08-02 09:43 UTC, konojunya commented on files/ja/web/http/headers/permissions-policy/index.md
> +    > **Note:** ディレクティブにはデフォルトの allowlist があり、 `Permissions-Policy` HTTP ヘッダーでは常に `*`, `self` または `none` になります。これらは個々の[ディレクティブのリファレンスページ](#ディレクティブ)で指定されています。 `<iframe>` の `allow` 属性では、デフォルトの動作は常に `sr
修正しました
https://github.com/mdn/translated-content/pull/14767/commits/04225e0f9f52fc6d62de227f88ffd58f5ed0e3a1

2023-08-04 08:15 UTC, mfuji09 approved these changes
OKです。ありがとうございました。

2023-08-04 08:21 UTC, merged