[ko] add `why_web_performance` translation
mdn/translated-content pull request #14776
Opened 2023-07-31 16:27 UTC by rbals0445

### Description

`why_web_performance` 의 한국어 번역을 추가하였습니다.
sourceCommit도 추가하였습니다.

### Motivation

### Additional details

### Related issues and pull requests

2023-08-01 06:10 UTC, wisedog requested changes
기여 감사합니다. 의견을 남겼으니 수정 부탁드리겠습니다.

2023-08-01 13:02 UTC, rbals0445 commented on files/ko/learn/performance/why_web_performance/index.md
> +좋은 성능은 자산입니다. 나쁜 성능에는 책임이 따릅니다. 사이트 속도는 이탈률, 전환율, 수익, 사용자 만족 및 검색 엔진 순위에 직접적인 영향을 줍니다.성능이 우수한 사이트는 방문자 유지율과 사용자 만족도를 높이는것으로 나타났습니다. 느린 컨텐츠는 사이트 이탈로 이어지고 일부 사용자들은 다시는 돌아오지 않는것으로 나타났습니다. 클라이언트와 서버간의 전송
엇! 의도적으로 계속 신경쓰고 있었는데, 여기는 또 생각없이 복붙을 해버렸네요 ㅎㅎㅎ;;

감사합니다!

2023-08-01 13:03 UTC, rbals0445 commented on files/ko/learn/performance/why_web_performance/index.md
> +웹 성능은 웹 브라우저에서 얼마나 빠르게 사이트의 컨텐츠가 **불러와지고** **렌더되는지** 그리고 사용자 상호작용에 얼마나 잘 응답하는지를 나타냅니다. 나쁜 성능을 가진 사이트는 느리게 보여지고 입력에 느리게 응답합니다. 나쁜 성능의 사이트는 사이트 이탈을 증가시킵니다. 최악의 경우 나쁜 성능은 컨텐츠가 완전히 접근 불가능하게 될 수 있습니다. 웹 성
glossary guide에 따라 렌더링 되는지로 수정하겠습니다!

2023-08-01 13:22 UTC, rbals0445 commented
@wisedog 님, 리뷰 반영했습니다. https://github.com/mdn/translated-content/pull/14776/commits/b411e7d8308b82314d118a1b7dadfbf21325d01e

- 웹 성능이 중요한 '이유' 로 변경
- 렌더 -> 렌더링으로 수정
- en-US 문서 링크를 ko로 수정
- 띄어쓰기 수정 (이 부분은 맞춤법 검사기를 쭉 돌렸어야 했는데, 다음 PR 부터는 신경쓰도록 하겠습니다!)

2023-08-01 13:58 UTC, wisedog approved these changes

2023-08-01 13:58 UTC, wisedog commented
언제나 수준높은 PR 정말 감사합니다!

2023-08-01 13:59 UTC, merged

2023-08-08 18:32 UTC, hochan222 commented
@rbals0445 님 안녕하세요. 기여해주셔서 감사합니다.

현재 한국 문서들은 최신화 되어있지 않은 레거시 문서들이 많이 존재합니다. [[ko] 한국 MDN 문서에 존재하는 레거시 문서 최신화](https://github.com/mdn/translated-content/issues/14965)에서 한국 MDN 문서에 존재하는 레거시 문서 최신화를 위한 작업을 진행하고 있습니다. 

참고 부탁드립니다. 좋은 하루 보내세요 :)