translate cryptographic hash function for zh-CN
mdn/translated-content pull request #14777
Opened 2023-07-31 16:42 UTC by fwqaaq

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-07-31 16:44 UTC, fwqaaq commented on files/zh-cn/glossary/cryptographic_hash_function/index.md
> +加密散列函数有时也称为*摘要函数*，其是一种{{glossary("cryptography", "加密")}}原语，将任意大小的信息转位固定大小的消息，称为{{glossary("digest", "摘要")}}。加密散列函数通常用于授权、{{Glossary("digital signature", "数字签名")}}以及{{Glossary("HMAC", "密钥散列消息认证码")}}.
```suggestion
加密散列函数有时也称为*摘要函数*，其是一种{{glossary("cryptography", "加密")}}原语，将任意大小的信息转位固定大小的消息，称为{{glossary("digest", "摘要")}}。加密散列函数通常用于授权、{{Glossary("digital signature", "数字签名")}}以及{{Glossary("HMAC", "密钥散列消息认证码")}}。
```

2023-08-01 07:53 UTC, yin1999 requested changes

2023-08-01 07:53 UTC, yin1999 commented on files/zh-cn/glossary/cryptographic_hash_function/index.md
> +title: 加密散列函数
actually, I don't like the translation, as hash is not a method for encryption. I'd prefer "密码学" or "密码", just like the first translation given by wikipedia.

2023-08-01 08:43 UTC, fwqaaq commented on files/zh-cn/glossary/cryptographic_hash_function/index.md
> +title: 加密散列函数
Yeah, you're right, I'll modify not so good title.

```suggestion
title: 密码散列函数
```

2023-08-01 11:30 UTC, yin1999 commented on files/zh-cn/glossary/cryptographic_hash_function/index.md
> +散列函数必须有以下特征才能用于加密：
```suggestion
散列函数必须有以下特征才能用于密码学：
```

2023-08-01 11:30 UTC, yin1999 commented on files/zh-cn/glossary/cryptographic_hash_function/index.md
> +- 快速计算（因为它们需要频繁的生成）
```suggestion
- 快速计算（因为它们需要频繁地生成）
```

2023-08-01 11:30 UTC, yin1999 commented on files/zh-cn/glossary/cryptographic_hash_function/index.md
> +- 防篡改（对消息的任何改变都会导致不同的摘要）
```suggestion
- 不可逆（每个摘要可能来自拥有庞大数据的消息，并且仅有暴力破解才能生成产生给定摘要的消息）
- 防篡改（对消息的任何改变都会产生不同的摘要）
```

2023-08-01 11:30 UTC, yin1999 commented on files/zh-cn/glossary/cryptographic_hash_function/index.md
> +像 MD5 和 SHA-1 这样的加密散列函数被认为是不安全的，因为已经发现了一种可以显著降低它们抗碰撞性的一种方式。
```suggestion
像 MD5 和 SHA-1 这样的加密散列函数被认为是不安全的，因为已经发现了可以显著降低它们抗碰撞性的攻击。
```

2023-08-01 14:38 UTC, yin1999 approved these changes
Thx

2023-08-01 14:38 UTC, merged