[ko] add translation to measuring_performance
mdn/translated-content pull request #14871
Opened 2023-08-03 16:29 UTC by rbals0445

### Description

- '웹 성능 측정하기' 부분을 번역하였습니다.

### Motivation

### Additional details

- Performance API, Navigation Timing API 등은 따로 한글로 번역하지 않았습니다. 다른 언어를 보더라도 번역하지 않은 나라들도 있고, 그렇지 않은 나라들도 있더라구요.

제 생각은 exclusive lock을 '배타 잠금' 이런식으로 해석하지 않듯 굉장히 간단한 영어로 되어있고, 고유명사처럼 해당 api들의 집합을 표현하는 단어들은 영어 그대로 사용했습니다. 

다른 의견 있으시면 리뷰 부탁드리겠습니다~ 모든 문서를 확인해본것은 아니라 놓친 부분이 있을 수 있다고 생각합니다.

### Related issues and pull requests

2023-08-19 12:08 UTC, hochan222 requested changes
@rbals0445 님 안녕하세요.

리뷰사항 하기에 남겨두었습니다. 고생 많으셨습니다.

기여해주셔서 감사합니다. 좋은 하루 보내세요 :)

2023-08-19 12:08 UTC, hochan222 commented on files/ko/learn/performance/measuring_performance/index.md
> +      <th scope="row">사전 지식:</th>
```suggestion
      <th scope="row">필요한 사전 지식:</th>
```

[안내 문구 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md)에 따라 필요한 사전 지식으로 수정 부탁드립니다.

2023-08-19 12:08 UTC, hochan222 commented on files/ko/learn/performance/measuring_performance/index.md
> +  commitSource: 79b1494aa78ef35b13ee8c028f6d4838478a6420
```suggestion
l10n:
  commitSource: 7c483~
```

[문서 갱신 표시 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md)에 따라  content 저장소의 가장 최신 hash가 아닌, content 저장소에서 기여하는 문서와 동일한 위치의 파일에 대한 최신 hash로 변경 부탁드립니다.

2023-08-19 12:08 UTC, hochan222 commented on files/ko/learn/performance/measuring_performance/index.md
> +[Chrome's Network Monitor documentation](https://developer.chrome.com/docs/devtools/network/) 또한 확인할 수 있습니다.
링크도 번역하면 좋을듯합니다~!

2023-08-19 12:08 UTC, hochan222 commented on files/ko/learn/performance/measuring_performance/index.md
> +[PerformanceObserver API](/ko/docs/Web/API/PerformanceObserver) 는 성능 측정 이벤트들을 관찰하고 브라우저의 성능 타임라인에 기록되는 새로운 [PerformanceEntry](/ko/docs/Web/API/PerformanceEntry) 를 알려주는 데 사용할 수 있는 API입니다.
```suggestion
[PerformanceObserver API](/ko/docs/Web/API/PerformanceObserver)는 성능 측정 이벤트들을 관찰하고 브라우저의 성능 타임라인에 기록되는 새로운 [PerformanceEntry](/ko/docs/Web/API/PerformanceEntry)를 알려주는 데 사용할 수 있는 API입니다.
```

페이지 전체에 대해 공백 제거 부탁드립니다.

2023-08-19 15:09 UTC, rbals0445 commented on files/ko/learn/performance/measuring_performance/index.md
> +  commitSource: 79b1494aa78ef35b13ee8c028f6d4838478a6420
@hochan222 님, 가장 최근 커밋을 바라보고 번역을 진행해서 해당 커밋 번호로 달게 되었습니다.

실제로 79b~~ 의 [수정내역](https://github.com/mdn/content/commit/79b1494aa78ef35b13ee8c028f6d4838478a6420#diff-8c8e42863a68e97ad9dccb506029fd40d8fd103421dcc2c932a2f7f66f098fb9)을 보시면 링크의 이름이 변경된것을 확인하실 수 있습니다.

그리고 현재 문서의 링크 또한 변경된 최신 링크인것을 확인하실 수 있습니다.

어떤 부분에서 다른것을 느끼셨는지 알려주시면 확인 해보겠습니다! 

 ![image](https://github.com/mdn/translated-content/assets/60285506/f050f699-a11f-4937-bacb-d70a7f9d2e44)

2023-08-19 15:25 UTC, rbals0445 commented on files/ko/learn/performance/measuring_performance/index.md
> +[Chrome's Network Monitor documentation](https://developer.chrome.com/docs/devtools/network/) 또한 확인할 수 있습니다.
링크 번역 포함하였습니다! 

성능 모니터, 네트워크 모니터는 번역이 자연스러운데, PageSpeed Insight는 페이지 명칭인것 같아서 따로 번역하지 않았습니다.
어색하면 알려주세요!

2023-08-19 15:26 UTC, rbals0445 commented on files/ko/learn/performance/measuring_performance/index.md
> +      <th scope="row">사전 지식:</th>
추가했습니다! (https://github.com/mdn/translated-content/pull/14871/commits/80fee7f288a1ee5aeeeee8f2240ee6ef72ee182f)

2023-08-19 15:28 UTC, rbals0445 commented on files/ko/learn/performance/measuring_performance/index.md
> +[PerformanceObserver API](/ko/docs/Web/API/PerformanceObserver) 는 성능 측정 이벤트들을 관찰하고 브라우저의 성능 타임라인에 기록되는 새로운 [PerformanceEntry](/ko/docs/Web/API/PerformanceEntry) 를 알려주는 데 사용할 수 있는 API입니다.
공백 제거했습니다~ (https://github.com/mdn/translated-content/pull/14871/commits/80fee7f288a1ee5aeeeee8f2240ee6ef72ee182f)

2023-08-28 11:13 UTC, hochan222 commented on files/ko/learn/performance/measuring_performance/index.md
> +  commitSource: 79b1494aa78ef35b13ee8c028f6d4838478a6420
@rbals0445 님 죄송합니다! 다른 PR의 파일하고 혼동했습니다. ㅎㅎ

링크 감사해요~! :)

2023-08-28 11:13 UTC, hochan222 approved these changes
LGTM. 고생 많으셨습니다. 좋은 하루 보내세요 :)

2023-08-28 11:13 UTC, merged