ko: add translation for 'tools_and_testing/client-side_js_frameworks/react_interactivity_events_state`
mdn/translated-content pull request #14898
Opened 2023-08-04 02:46 UTC by IMHOJEONG

### Description

tools_and_testing/client-side_js_frameworks/react_interactivity_events_state를 번역하였습니다. 
영어 그대로 해석해서 쓰기에는, 읽는 사람들이 제대로 이해하지 못할 부분도 있어서, 개발에서 사용되는 단어, 문장을 최대한 반영해서 번역하였습니다.

### Motivation

React에 익숙하지 않을 때, 처음보면 좋을 가이드라인을 만들면 좋겠다 싶어 이 부분의 번역을 진행하고 있습니다.
좋은 가이드 문서가 있다면, 그만큼 더욱 기술에 친근하게 다가갈 수 있는 부분이라고 생각이 들었습니다.

### Additional details

정확하지 않은 부분도 있고, 번역하면서 약간 갸우뚱하던 부분들도 존재합니다. 
JavaScript나 React와 같이 언어 특성에 따른 단어(state,props)와 문장은 오히려 번역이 아니라, 원문 그대로 참조하여 쓰는 게 더 정확하다고 생각했습니다. (e.g. props를 속성들로 번역해서 사용하는 게 맞는건지에 대한 의문이 들었습니다.) 

- 원문 주소입니다

    - https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md

### Related issues and pull requests

2023-08-11 14:31 UTC, pje1740 requested changes
긴 글 작업하시느라 정말 고생 많으셨습니다! 제가 몇가지 코멘트 남겼는데, 꼭 정답은 아니기 때문에 궁금하신 점은 편하게 질문 남겨주시고, ko locale 차원에서의 논의가 필요하다고 생각되시면 그것도 코멘트 남겨주시면 감사하겠습니다.
제가 코멘트 드린 부분은 크게 이렇습니다. 
- 번역의 어감
- glossary 원칙에 따른 수정 (event listener 등)
- React의 고유한 개념의 원문 유지 여부

여러번 반복되는 것들은 하나하나 코멘트를 달지 않았지만 수정은 일괄적으로 부탁드리겠습니다!

2023-08-11 14:31 UTC, pje1740 commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +이제 `nanoid`를 `App.js` 상단으로 가져올 수 있으므로 이를 사용하여 새 작업에 대한 고유 ID를 만들 수 있습니다. 우선 `App.js` 상단에 다음 가져오기 줄을 포함합니다.
```suggestion
이제 `nanoid`를 `App.js` 상단으로 가져올 수 있으므로 이를 사용하여 새 작업에 대한 고유 ID를 만들 수 있습니다. 우선 `App.js` 상단에 다음 import문을 추가합니다.
```
```suggestion
이제 `nanoid`를 `App.js` 상단으로 가져올 수 있으므로 이를 사용하여 새 작업에 대한 고유 ID를 만들 수 있습니다. 우선 `App.js` 상단에 다음 구문을 추가합니다.
```

import문이라고도 많이들 표현은 하시는 거 같으나 콩글리시의 느낌이 있어서 '구문'으로 적은 것과 나란히 제안 드려봅니다!

2023-08-11 14:31 UTC, pje1740 commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +이제 새 작업을 추가할 수 있으므로, 문제가 있음을 알 수 있습니다. 작업 수에 관계없이, 머리글에 남은 작업이 3개로 표시됩니다! `taskList`의 길이를 세고 이에 따라 제목의 텍스트를 변경하여 이 문제를 해결할 수 있습니다.
```suggestion
새 작업을 추가해보면 문제가 있음을 알 수 있습니다. 실제 작업 수에 관계없이, 머리글에 남은 작업이 3개로 표시됩니다! `taskList`의 길이를 세고 이에 따라 제목의 텍스트를 변경하여 이 문제를 해결할 수 있습니다.
```
조금 더 자연스러운 표현으로 제안 남겨봅니다.

2023-08-11 14:31 UTC, pje1740 commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +브라우저에서 확인란의 선택이 취소되지만, 콘솔에서는 Eat가 아직 완료되었다고 알려줍니다. 다음에 수정하겠습니다!
```suggestion
브라우저에서 확인란의 선택이 취소되지만, 콘솔에서는 Eat가 아직 완료되었다고 알려줍니다. 이제 수정해보겠습니다!
```

다음에 수정한다고 하니 안 하고 넘어가는 건가?! 하는 느낌이 있어서 제안 드려봅니다 😂

2023-08-11 14:31 UTC, pje1740 commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +그런 다음 이 새 작업이 추가된 새 배열을 만든 다음 작업 데이터의 상태를 이 새 상태로 업데이트해야 합니다. 이를 위해, 확산 구문을 사용하여 [기존 배열을 복사](/ko/docs/Web/JavaScript/Reference/Operators/Spread_syntax#copy_an_array)하고 끝에 객체를 추가할 수 있습니다. 그런 다음 이 배열을
```suggestion
그런 다음 이 새 작업이 추가된 새 배열을 만든 다음 작업 데이터의 상태를 이 새 상태로 업데이트해야 합니다. 이를 위해, 전개 구문을 사용하여 [기존 배열을 복사](/ko/docs/Web/JavaScript/Reference/Operators/Spread_syntax#copy_an_array)하고 끝에 객체를 추가할 수 있습니다. 그런 다음 이 배열을 `setTasks()`에 전달하여 상태를 업데이트합니다.
```
현재 MDN 번역에서 spread를 '전개'로 번역하고 있어 동일하게 유지 부탁드립니다.

2023-08-11 14:31 UTC, pje1740 commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +기사 하나면 충분합니다. 여기에서는 React가 이벤트를 처리하고 상태를 처리하는 방법, 작업을 추가하고 삭제하고 완료된 작업을 토글하는 기능을 구현하는 방법에 대한 정보를 제공했습니다. 거의 다 왔습니다. 다음 문서에서는 기존 작업을 편집하고 모든 작업, 완료된 작업 및 완료되는 않은 작업 간에 작업 목록을 필터링하는 기능을 구현합니다. 그 과정에서 조
```suggestion
너무 길어질 수 있으니 이번 글은 여기서 마치겠습니다. 이 글을 통해 React가 이벤트를 처리하고 상태를 처리하는 방법, 작업을 추가하고 삭제하고 완료된 작업을 토글하는 기능을 구현하는 방법을 알려드렸습니다. 거의 다 왔습니다. 다음 문서에서는 기존 작업을 편집하고 모든 작업, 완료된 작업 및 완료되는 않은 작업 간에 작업 목록을 필터링하는 기능을 구현합니다. 그 과정에서 조건부 UI렌더링을 살펴보겠습니다.
```
첫 문장은 이 글로 충분하다는 의미보다는, 한 글이 너무 길어지니 이 쯤에서 끊고 간다는 어감으로 이해하면 더 자연스러울 거 같아 제안 드립니다.

2023-08-15 15:16 UTC, IMHOJEONG commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +컴포넌트 계획이 완료되었으므로, 이제 애플리케이션을 완전히 정적인 UI에서 실제로 상호 작용하고 변경할 수 있는 애플리케이션으로 업데이트할 때입니다. 이 기사에서는 이벤트와 상태를 파헤쳐 작업을 성공적으로 추가 및 삭제하고, 완료된 작업을 토글할 수 있는 애플리케이션으로 끝낼 것입니다.
저도 용어 안내서를 찾아봤는데, 어떤 거로 번역해야 할까 하다가 기사라는 뜻을 사용했는데, '글'이라는 표현이 더 어울려 보입니다. 
감사합니다.

2023-08-15 15:16 UTC, IMHOJEONG commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +지금까지 기본 JavaScript만 작성했다면, 일부 DOM 노드를 쿼리하고 여기에 리스너를 연결하는, 별도의 JavaScript 파일이 있는 부분이 익숙할 수 있습니다.
네, 리스너 대신 수신기로 번역하도록 하겠습니다. 감사합니다

2023-08-15 15:19 UTC, IMHOJEONG commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +React에서는, 다음과 같이 JSX의 요소에 직접 이벤트 핸들러를 작성합니다.
넵 전부 수정하겠습니다.

2023-08-15 15:20 UTC, IMHOJEONG commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +- `onClick`의 camel-cased 특성이 중요합니다. JSX는 `onclick`을 인식하지 않습니다(다시 말하지만 JavaScript에서 특정 목적을 위해 이미 사용되고 있습니다, 관련은 있지만 다릅니다 - 표준 [`onclick`](/ko/docs/Web/API/Element/click_event) 핸들러 prop).
혹시 이 부분에 대한 번역 가이드가 있나요? 저도 하이픈(-)으로 나오면, 어떻게 번역하는 게 더 자연스러운지 몰라서, 한국어로 했을 때 자연스러운 표현으로 하면 되는 건지 궁금합니다.

2023-08-15 15:21 UTC, IMHOJEONG commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +- `onClick`의 camel-cased 특성이 중요합니다. JSX는 `onclick`을 인식하지 않습니다(다시 말하지만 JavaScript에서 특정 목적을 위해 이미 사용되고 있습니다, 관련은 있지만 다릅니다 - 표준 [`onclick`](/ko/docs/Web/API/Element/click_event) 핸들러 prop).
그리고 수정된 표현이 더 자연스러워 보입니다.
감사합니다!

2023-08-15 15:29 UTC, IMHOJEONG commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +다음으로, `addTask()`를 `<Form />`에 prop으로 전달합니다. prop에는 원하는 이름을 지정할 수 있지만, 나중에 이해할 수 있는 이름을 선택해주세요. `addTask`와 같은 것이 작동합니다. 함수의 이름과 함수가 수행할 작업을 일치시키기 때문에 때문입니다. `<Form />` 컴포넌트 호출은 다음과 같이 업데이트되어야 합니다.
피드백 해주신 부분이 더 자연스럽습니다. 감사합니다

2023-08-15 15:31 UTC, IMHOJEONG commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +React는 상태처럼, 컴포넌트에 새로운 기능을 제공할 수 있는 다양한 특수 함수을 제공합니다. 이러한 함수를 **훅**이라고 하며, `useState` 훅은 이름에서 알 수 있듯이, 컴포넌트에 상태를 부여하기 위해 정확히 필요한 것입니다.
넵. 이 부분도 정말 고민 많이 했는데, React 원문 처럼 hook으로 그대로 두는 게 더 나아보여집니다.

2023-08-15 15:33 UTC, IMHOJEONG commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +지금까지, 컴포넌트를 통해 데이터를 전달하기 위해 props를 사용했고 이것이 우리에게 잘 맞았습니다. 그러나 이제 사용자 입력 및 데이터 업데이트를 처리하고 있으므로 더 많은 것이 필요합니다.
문법 그대로 해석하는 것보다, 앞뒤 글에 맞게 하는 게 더 자연스럽네요. 감사합니다.

2023-08-15 15:35 UTC, IMHOJEONG commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +"Use hooks!"를 빈 문자열로 변경해보세요. 이것이 우리가 초기 상태에 대해 원하는 부분입니다.
앗 네. 원문 그대로보다는, 더 자연스러운 표현이 있다면 편하게 적용해서 피드백 받도록 하겠습니다.

2023-08-15 15:36 UTC, IMHOJEONG commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +`name`의 값을 변경하기 전에, 입력하는 사용자의 입력을 캡처해야 합니다. 이를 위해, `onChange` 이벤트를 수신할 수 있습니다. `handleChange()` 함수를 작성하고 `<input />` 태그에서 입력을 기다려봅시다.
흠.. 고민이 많이 되는 부분입니다. 
영어 단어 그대로의 뜻을 따라가야 하는 건지, 아니면 문맥에 맞게 제가 커스텀하게 단어 뜻을 바꾸어도 되는 건지 어떻게 해야할지 모르겠네요 ㅠㅠ
바꾸어 주신 부분이 더 자연스럽기는 합니다. 감사드려요

2023-08-15 15:37 UTC, IMHOJEONG commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +변경된 입력 필드의 내용을 읽으려면 입력의 `value` 속성에 액세스 할 수 있습니다. `e.target.value`를 읽어 `handleChange()` 내부에서 이 작업을 수행할 수 있습니다. `e.target`은 `change` 이벤트를 발생시킨 요소를 나타냅니다. 이것이 우리의 입력입니다. 따라서 `value`는 그 안에 있는 텍스트입니다.
넵 수정하겠습니다.

2023-08-15 15:42 UTC, IMHOJEONG commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +브라우저에서 확인란의 선택이 취소되지만, 콘솔에서는 Eat가 아직 완료되었다고 알려줍니다. 다음에 수정하겠습니다!
아 그럴 수가 있겠네요.

2023-08-16 23:16 UTC, pje1740 commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +- `onClick`의 camel-cased 특성이 중요합니다. JSX는 `onclick`을 인식하지 않습니다(다시 말하지만 JavaScript에서 특정 목적을 위해 이미 사용되고 있습니다, 관련은 있지만 다릅니다 - 표준 [`onclick`](/ko/docs/Web/API/Element/click_event) 핸들러 prop).
제가 하이픈이라고 말했는데, 정확히는 대시네요! 😅
[번역 가이드](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md#-%EB%8C%80%EC%8B%9C)에 보면 대시 또한 온점으로 치환하는 것을 추천드리고 있습니다. 참고 부탁드려요!

2023-08-16 23:23 UTC, pje1740 commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +## 콜백 prop들
말씀 주셔서 감사합니다! React 공식 용어에 대한 번역은 논의가 필요해보이긴 합니다! 
@hochan222 호찬님, 혹시 이 부분 한번 같이 검토해볼 수 있을까요? React 공식 문서 기준으로는 props, hook 같은 용어는 그대로 사용하고 있는데, MDN도 해당 용어가 많이 등장하는 만큼 번역 가이드가 제공되면 좋을 거 같아요! (제가 혹시 가이드를 놓치고 있다면 알려주세요!)

2023-08-16 23:24 UTC, pje1740 commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +## 콜백 prop들
복수형의 경우, [국립국어원 상담](https://korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=276170)을 살펴보면 한국어의 경우 복수형을 위한 '들'을 붙이는 것이 선택적이라고 나와있습니다. 어떻게 보면 반복적인 표현이기 때문에 가급적 여러개라는 것이 추론되는 상황에서는 제거하라고 들어왔었는데, 이건 가이드에까지 올릴 건 아니고 자연스러운 선에서는 유지시켜도 될 거 같긴하네요! 

다만 여기선 props를 어떻게 번역할 것인가에 대한 논의여서 복수형과는 또 별개인 거 같아 코멘트 남겨봅니다 🤔

2023-08-16 23:29 UTC, pje1740 commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +`name`의 값을 변경하기 전에, 입력하는 사용자의 입력을 캡처해야 합니다. 이를 위해, `onChange` 이벤트를 수신할 수 있습니다. `handleChange()` 함수를 작성하고 `<input />` 태그에서 입력을 기다려봅시다.
제 경우 의역을 선호하는 편인데요, 받아본다와 'listen' / 'capture' 가 맥락이 많이 벗어나는 의역으로 판단되신다면 언제든 편하게 다른 제안 주셔도 됩니다! listener를 수신기로 번역하는 만큼, 여기서의 listen은 어떤 입력을 받아서 가져오는 행위라고 저는 판단해서 제안드렸습니다! 😊 한번 더 고민해보시고 언제든 논의가 필요하면 코멘트 남겨주세요!

2023-08-16 23:32 UTC, pje1740 commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +그런 다음 이 새 작업이 추가된 새 배열을 만든 다음 작업 데이터의 상태를 이 새 상태로 업데이트해야 합니다. 이를 위해, 확산 구문을 사용하여 [기존 배열을 복사](/ko/docs/Web/JavaScript/Reference/Operators/Spread_syntax#copy_an_array)하고 끝에 객체를 추가할 수 있습니다. 그런 다음 이 배열을
네넵, 이것도 용어 안내서에 추가하면 좋을 거 같네요!
@hochan222 spread 도 기존 번역이 현재는 '전개'인데, 다른 데서 혹시 논의되고 있을까요?? 없다면 정해서 용어 가이드에 추가해도 좋아보입니다!

2023-08-19 06:25 UTC, hochan222 commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +## 콜백 prop들
@pje1740 님, @IMHOJEONG 님 안녕하세요. 현재 React 관련 안내서는 존재하지 않습니다. React glossary 안내 영역 만들고 추가하겠습니다. 

props는 React에서 거의 관용어로 사용되고 있기에.. props 그대로 사용해도 좋을듯하빈다. hook은 `훅`으로도 사용하고 있어서 조금 고민이네요. (hooks 는 어떻게 하면 좋을지등..)

2023-08-19 06:26 UTC, hochan222 commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +그런 다음 이 새 작업이 추가된 새 배열을 만든 다음 작업 데이터의 상태를 이 새 상태로 업데이트해야 합니다. 이를 위해, 확산 구문을 사용하여 [기존 배열을 복사](/ko/docs/Web/JavaScript/Reference/Operators/Spread_syntax#copy_an_array)하고 끝에 객체를 추가할 수 있습니다. 그런 다음 이 배열을
@pje1740 님, 네 추가하도록 하겠습니다. (cc. @IMHOJEONG 님)

2023-08-23 12:24 UTC, pje1740 commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +## 콜백 prop들
@hochan222 확인 감사합니다!
@IMHOJEONG 제가 확인이 조금 늦었네요! hook은 일단 지금 수정 주신 것처럼 hook으로 유지하고 머지하겠습니다! 컨플릭만 한번 해결해서 올려주시면 머지 진행하겠습니다!

2023-08-23 13:45 UTC, IMHOJEONG commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
> +## 콜백 prop들
@pje1740 님 안녕하세요!
바쁘신데도 피드백 주셔서 감사합니다. 
conflict 해결하느라 좀 걸렸네요 ㅠㅠ

2023-08-24 01:07 UTC, pje1740 approved these changes
계속 변경이 발생해서 github에서 제공하는 rebase merge 로 우선 컨플릭 제가 해결했습니다! 너무 고생 많으셨습니다!!

2023-08-24 01:09 UTC, merged

2023-08-24 01:10 UTC, IMHOJEONG commented
@pje1740 님 안녕하세요.

ㅠㅠ 제가 해결을 못해서, 결국 해주셨군요.. 감사합니다!

하나 여쭈어 보고 싶은 부분이 있는데요.
이렇게 변경이 많이 발생하는 부분에 대해서 merge를 진행할 때, rebase 규칙은 어떻게 설정하시고, 
conflict을 해결하시는지 궁금합니다.

2023-08-24 01:18 UTC, pje1740 commented
기본적으로는 main 브랜치를 현재 작업 중인 브랜치에서 rebase 하고, 해당 변경 사항을 force-push 하여 해결하고 있습니다. 깃헙에서도 update branch 기능을 제공하고 있어서 제가 대단한 걸 한 건 아니고, 이 기능 활용했습니다! 😂
그래도 항상 기여자 분께 1차로 부탁을 드리는 건, 변경사항에 대해 더 잘 인지하고 계시고 누락되는 내용이 없게끔 하기 위함입니다. 다만 최근에는 변화가 잦은 상황이라 리뷰어들이 rebase 하는 경우도 많으니 참고 부탁드립니다!