[ko] add translation to css overflow-inline
mdn/translated-content pull request #14913
Opened 2023-08-05 06:06 UTC by xxslx

### Description

css/overflow-inline 파일을 번역하였습니다.

### Motivation

### Additional details

### Related issues and pull requests

2023-08-05 14:40 UTC, wisedog requested changes
안녕하세요, @xxslx  님.

첫 기여 감사합니다. 2가지 외에 딱히 번역에서는 수정할 점이 없구요. lint 에서 지적한 내용과 함께 고쳐주시면 좋겠습니다. 

감사합니다.

2023-08-05 14:40 UTC, wisedog commented on files/ko/web/css/overflow-inline/index.md
> +slug: Web/CSS/overflow-inline
[메타 데이터 가이드](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md) 참고해주시기 바랍니다.

l10n 을 추가해주시기 바랍니다.

2023-08-05 14:40 UTC, wisedog commented on files/ko/web/css/overflow-inline/index.md
> +**`overflow-inline`** [CSS](/en-US/docs/Web/CSS) 속성은 콘텐츠가 박스의 인라인 시작과 끝 가장자리를 넘어설 때 어떤 내용을 보여줄지를 설정합니다. 이는 아무 것도 표시하지 않을 수도 있고, 스크롤 바가 나타날 수도 있으며 넘친 콘텐츠가 보일 수도 있습니다.
[번역 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md) 참고해주시기 바랍니다. 

`/ko` 문서가 없더라도 `/ko` 로 넣어주시기 바랍니다.

2023-08-06 04:38 UTC, xxslx commented on files/ko/web/css/overflow-inline/index.md
> +**`overflow-inline`** [CSS](/en-US/docs/Web/CSS) 속성은 콘텐츠가 박스의 인라인 시작과 끝 가장자리를 넘어설 때 어떤 내용을 보여줄지를 설정합니다. 이는 아무 것도 표시하지 않을 수도 있고, 스크롤 바가 나타날 수도 있으며 넘친 콘텐츠가 보일 수도 있습니다.
안녕하세요,
수정 사항 반영완료 하였습니다 :)

2023-08-06 05:25 UTC, wisedog approved these changes

2023-08-06 05:25 UTC, merged

2023-08-06 05:26 UTC, wisedog commented
LGTM! 고생하셨습니다. 감사합니다. 🙏