[zh-cn]: Add translation of Numeric separators
mdn/translated-content pull request #14933
Opened 2023-08-06 14:59 UTC by DiamondMofeng

### Description

Add translation of `Numeric separators` in /web/javascript/reference/lexical_grammar#numeric_literals

### Motivation

This feature has been added for a long time, but it has never appeared in the Chinese documentation.

### Additional details

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Numeric_literals

2023-08-06 16:05 UTC, jasonren0403 requested changes
感谢翻译，这里有个建议

2023-08-06 16:05 UTC, jasonren0403 commented on files/zh-cn/web/javascript/reference/lexical_grammar/index.md
> +可以使用下划线（`_`, `U+005F`）作为分隔符以增强数值字面量的可读性，
注意标点符号使用

```suggestion
可以使用下划线（`_`，`U+005F`）作为分隔符以增强数值字面量的可读性：
```

2023-08-07 00:56 UTC, DiamondMofeng commented
@jasonren0403 感谢review，另外我发现指数、bigint字面量等也未翻译至中文文档，这个pr之后我可以也尝试翻译一下

2023-08-07 11:27 UTC, jasonren0403 approved these changes
👍 欢迎来到MDN！

2023-08-07 11:29 UTC, jasonren0403 commented
> @jasonren0403 感谢review，另外我发现指数、bigint字面量等也未翻译至中文文档，这个pr之后我可以也尝试翻译一下

没问题，如果有兴趣也可以把整篇文档都更新一下 👍

2023-08-07 11:29 UTC, merged