Fix Japanese text (React ToDoリストをはじめる)
mdn/translated-content pull request #1494
Opened 2021-07-12 01:08 UTC by shinshin86

I found a typo in Japanese on this page.
Some text has been corrected.

https://developer.mozilla.org/ja/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_todo_list_beginning

2021-07-12 17:05 UTC, mfuji09 requested changes
修正していただきましたが、まだ原文に対する日本語訳がおかしいと思います。以下は参考訳です。
- コンポーネントごとにスタイルシートを書く予定はないので、まず App.js の冒頭にある App.css のインポートを削除してください。
- logo.svg を使用する予定もないので、このインポートも削除してください。

また、不要な font 要素を削除してください（英語版に合わせてください）。

2021-07-13 01:06 UTC, shinshin86 commented
@mfuji09 ご確認ありがとうございます。

日本語の文章がおかしかったですね。すみません、確認が漏れていました。
参考訳として提示していただいた文章が最適であると思ったため、こちらをそのまま適用させていただきます。

また、font要素は特に必要なかったのですね。
下記の英語版に合わせてfont要素は削除しました。
https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.html

全体的に `<font>` を削除すると変更量が膨大になるため、一旦今回の修正箇所のみ削除していますが、このPR内でこのファイルの他の箇所についても併せて削除したほうが良いでしょうか？
(いずれにせよ、 このファイル内の `<font>` 削除のためのPRは作成しようと考えています)

2021-07-13 01:51 UTC, mfuji09 commented
@shinshin86 さん
ありがとうございました。
長引かせるのも良くないので、とりあえず今回のプルリクエストはここで閉じたいと思います。

この記事は、 '<font>' 要素が過剰に残っているだけでなく、文章もどこか機械翻訳のようですし、 https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline のガイドラインにも則していません。ですから、改めてそうした修正をしていただけると幸いです。

2021-07-13 01:52 UTC, merged

2021-07-13 02:26 UTC, shinshin86 commented
承知しました。
ご確認ありがとうございました。