ko: add translation for `tools_and_testing/client-side_js_frameworks/react_resources`
mdn/translated-content pull request #14943
Opened 2023-08-07 12:28 UTC by IMHOJEONG

### Description

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_resources 를 번역하였습니다.

### Motivation

리액트의 번역되지 않은 나머지 부분을 제대로 마무리하고 싶어서 번역하였습니다.

### Additional details

### Related issues and pull requests

2023-08-20 09:47 UTC, yechoi42 requested changes
안녕하세요. 기여 감사합니다. 몇가지 제안을 남겨두었으니, 확인 후 저를 다시 멘션하거나 제게 다시 리뷰 요청 주세요.

2023-08-27 15:11 UTC, IMHOJEONG commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_resources/index.md
> +이 접근 방식을 사용하면 특정 컴포넌트에 속하는 CSS를 쉽게 식별하고 관리할 수 있습니다. 그러나, 코드베이스 전체에서 스타일시트를 분할하기도 하며, 이러한 분할은 가치가 없을 수 있습니다. 수백 개의 고유한 view(보기)와 많은 이동 부분이 있는 대규모 애플리케이션의 경우, 사용자에게 전송되는 관련없는 코드의 양을 제한하는 것이 좋습니다. 애플리케이
@yechoi42 님 안녕하세요!
너무 늦게 확인해서 죄송합니다 ㅠㅠ 
혹시 view를 시각적인 요소로 해석하는 거는 어떻게 생각하시나요?

2023-08-27 15:13 UTC, IMHOJEONG commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_resources/index.md
> +왼쪽에는, 배열에서 렌더링되는 항목에 대한 일부 고유 키를 포함하여, 응용 프로그램을 구성하는 모든 컴포넌트가 표시됩니다. 오른쪽에는 애플리케이션 컴포넌트가 활용하는 props와 훅이 표시됩니다. 또한, `Form`, `FilterButton` 및 `Todo` 컴포넌트가 오른쪽으로 들여쓰기되어 있다는 점에 유의하세요. 이는 `App`이 해당 컴포넌트의 부
view가 시각적인 요소로 해석될 수 있는지에 따라 이 부분 정하겠습니다!

2023-09-16 14:59 UTC, yechoi42 commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_resources/index.md
> +이 접근 방식을 사용하면 특정 컴포넌트에 속하는 CSS를 쉽게 식별하고 관리할 수 있습니다. 그러나, 코드베이스 전체에서 스타일시트를 분할하기도 하며, 이러한 분할은 가치가 없을 수 있습니다. 수백 개의 고유한 view(보기)와 많은 이동 부분이 있는 대규모 애플리케이션의 경우, 사용자에게 전송되는 관련없는 코드의 양을 제한하는 것이 좋습니다. 애플리케이
@IMHOJEONG 님 안녕하세요! 저도 확인이 늦어져 죄송합니다 ㅠㅠ 네 좋습니다.

2023-09-16 14:59 UTC, yechoi42 commented
안녕하세요, 확인이 늦었습니다. ㅠㅠ 코멘트 남겨두었습니다!

2023-09-17 14:41 UTC, IMHOJEONG commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_resources/index.md
> +이 접근 방식을 사용하면 특정 컴포넌트에 속하는 CSS를 쉽게 식별하고 관리할 수 있습니다. 그러나, 코드베이스 전체에서 스타일시트를 분할하기도 하며, 이러한 분할은 가치가 없을 수 있습니다. 수백 개의 고유한 view(보기)와 많은 이동 부분이 있는 대규모 애플리케이션의 경우, 사용자에게 전송되는 관련없는 코드의 양을 제한하는 것이 좋습니다. 애플리케이
@yechoi42 님 안녕하세요.
넵 그러면 `view=> 시각적인 요소`로 반영해두겠습니다.

2023-09-17 14:43 UTC, IMHOJEONG commented on files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_resources/index.md
> +왼쪽에는, 배열에서 렌더링되는 항목에 대한 일부 고유 키를 포함하여, 응용 프로그램을 구성하는 모든 컴포넌트가 표시됩니다. 오른쪽에는 애플리케이션 컴포넌트가 활용하는 props와 훅이 표시됩니다. 또한, `Form`, `FilterButton` 및 `Todo` 컴포넌트가 오른쪽으로 들여쓰기되어 있다는 점에 유의하세요. 이는 `App`이 해당 컴포넌트의 부
추가적으로, 다시 읽어보니, 이 부분은 화면이 더 자연스러워서 
원래 주신 피드백 그대로 가겠습니다.

2023-09-17 14:47 UTC, IMHOJEONG commented
@yechoi42 님 안녕하세요.
앗 아닙니다. 코멘트에 

1) view => 시각적인 요소
2) 60번 째 라인 = `더 복잡한 어플리케이션에서, 이 화면은 부모/자식 관계를 한눈에 이해하는 데 유용합니다.` 
  => 이 부분은 시각적인 요소보다는 화면이 더 자연스러워 주신 피드백 그대로 적용하겠습니다.

위와 같이 추가의견 붙여서 푸시해두었습니다.

2023-09-17 14:50 UTC, yechoi42 approved these changes
기여 감사합니다!

2023-09-17 14:50 UTC, merged