ko: update & delete untranslated content in `mdn/html`
mdn/translated-content pull request #15008
Opened 2023-08-09 04:54 UTC by soorokim

### Description
@soorokim 의 작업 범위는 아래와 같습니다.

### 폴더 별 항목
- [ ] web/html/attributes ( 작업중 )
- [ ] web/html/content_categories
- [ ] web/html/cors_enabled_image
- [ ] web/html/quirks_mode_and_standards_mode
- [ ] web/html/reference
- [ ] web/html

### Related issues and pull requests
https://github.com/mdn/translated-content/issues/14965

2023-08-09 12:40 UTC, hochan222 requested changes
@soorokim 님 안녕하세요.

아직 draft지만 몇가지 리뷰사항 아래에 드립니다. 그외에는 문제없어 보입니다!

기여해주셔서 감사합니다. 좋은 하루 보내세요 :)

---

[PR 파일 개수 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/README.md)에 따라 한 리뷰어에게 너무 많은 리뷰가 몰리지 않도록 번역 PR의 경우 1개의 파일을 넘지 않는 것을 권장드리며, 사소한 변화 및 일괄적인 작업 PR에 대해서는 30개의 파일을 넘지 않는 것을 권장드립니다.

혹시 기여하시다가 페이지 번역길이가 길어지면 별도의 PR로 나누어서 기여주시면 더 좋을듯합니다. 충돌의 문제도 있고, 리뷰어의 부담이 낮아져서 보다 빠르게 반영될 수 있습니다.

2023-08-09 12:40 UTC, hochan222 commented on files/ko/web/html/attributes/autocomplete/index.md
> +  sourceCommit: f09f04f9658cce9c57e97270f59b24b263826fd0
👍👍

2023-08-09 12:40 UTC, hochan222 commented on files/ko/web/html/attributes/autocomplete/index.md
> +  - : 새로운 비밀번호. 계정을 생성할 때나 비밀번호를 변경할 때, new-password는 "새로운 비밀번호를 입력하세요" 또는 "비밀번호 확인"에 지정해야 합니다. 일반적인 비밀번호와 구분하는 이유는 브라우저가 기존 비밀번호를 자동완성으로 채우는 것을 피하기 위함이며, 안전한 무작위 비밀번호 생성을 제안할 곳을 결정할 때도 사용하기 때문입니다.([
```suggestion
  - : 새로운 비밀번호. 계정을 생성할 때나 비밀번호를 변경할 때, new-password는 "새로운 비밀번호를 입력하세요" 또는 "비밀번호 확인"에 지정해야 합니다. 일반적인 비밀번호와 구분하는 이유는 브라우저가 기존 비밀번호를 자동완성으로 채우는 것을 피하기 위함이며, 안전한 무작위 비밀번호 생성을 제안할 곳을 결정할 때도 사용하기 때문입니다.([autocomplete="new-password"를 사용한 자동 채우기 방지](/ko/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#preventing_autofilling_with_autocompletenew-password) 참조).
```

[문서 연결 경로 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md)에 따라 ko로 변경 부탁드립니다!

2023-08-28 15:15 UTC, hochan222 commented
@soorokim 님 안녕하세요. 

PR pending 상태가 오래 지속되고 있어서, 이번주내로 기여 예정이 없으실경우 현재 PR close로 상태 우선 변경하도록 하겠습니다.

기여해주셔서 감사합니다. 좋은 하루 보내세요 :)

2023-09-02 22:59 UTC, soorokim commented
@hochan222 작업에 신경을 못써 죄송합니다. 번역이 새로 필요한 페이지들은 적어두고 일단 삭제 후 추후 번역 진행하도록 하겠습니다. 오늘 작업 마무리 해놓겠습니다. 감사합니다.

2023-09-09 12:48 UTC, hochan222 commented
@soorokim 님 안녕하세요.

바쁘신 와중에 기여해주셔서 감사합니다. 위 5개 PR은 https://github.com/mdn/translated-content/issues/14965에 추가해두었습니다. 

기여해주심에 항상 감사드리고 있기 때문에 기여하시는 과정에서 부담을 느끼시지 않으시면 좋겠습니다.

해당 PR은 우선 닫겠습니다!

좋은 주말 보내세요 :)

2023-09-09 12:48 UTC, closed without merging