ko: update & delete untranslated content for `javascript` files
mdn/translated-content pull request #15001
Opened 2023-08-09 02:22 UTC by IMHOJEONG

### Description

@IMHOJEONG 의 작업 범위는 아래와 같습니다. 

아래에 체크박스로 현재 진행 중인 부분과 완료된 작업 현황 최신화하겠습니다.

- [ ] #14965 (진행중)

#### 폴더 별 항목

- [ ] web/javascript/language_overview (진행중)
- [ ] web/javascript/javascript_technologies_overview
- [ ] web/javascript/closures 
- [ ] web/javascript/data_structures
- [ ] web/javascript/memory_management
- [ ] web/javascript/inheritance_and_the_prototype_chain

### Motivation

번역을 하던 중에, 가이드라인을 받아서 맞추어서 진행하고자 시작하게 되었습니다.

### Additional details

참고한 안내서입니다.
https://github.com/mdn/translated-content/blob/main/docs/ko/README.md
번역하면서, 안내서 부분도 최신화시켜주면 좋을 듯 해보여서, 그 부분도 정리해서 기여해 볼 예정입니다.

### Related issues and pull requests

#14965

2023-08-09 02:31 UTC, hochan222 commented
> 번역하면서, 안내서 부분도 최신화시켜주면 좋을 듯 해보여서, 그 부분도 정리해서 기여해 볼 예정입니다.

안내서 최신화 작업 계획 세워주셔서 감사합니다. 기여주실 때, 안내서 문서는 현재 PR의 목적과 상이하여 다른 PR로 분리해서 기여주시면 조금 더 빠르게 기여 내용 반영될 수 있을듯합니다. 기여해주셔서 감사합니다. 🙇🙇

2023-08-09 12:06 UTC, IMHOJEONG commented
@hochan222 님 안녕하세요!
제가 커밋을 올려보았는데, 혹시 맞는지 피드백 부탁드려도 될까요?

수정하면서, 궁금한 점이 2가지 있습니다.

1. 이 PR에서는 번역을 하지 않고, 부분적으로 한국어 번역만 남겨두고 나머지는 최신화해도 되는건지 
2. 같은 폴더 위치에 한국어로 번역은 되어 있는데, 내용이 업데이트가 되어 최신화 이전이면 미번역으로 판단하고 그냥 두어야 하는 건지 

부족한 부분 있으면, 빠른 시간에 수정하겠습니다.

2023-08-09 12:26 UTC, hochan222 requested changes
@IMHOJEONG 님 안녕하세요.

기여해주셔서 감사합니다. 몇가지 리뷰사항 아래에 남겨두었습니다. 고생 많으셨습니다.

> 1. 이 PR에서는 번역을 하지 않고, 부분적으로 한국어 번역만 남겨두고 나머지는 최신화해도 되는건지

하나의 문서에 대해 전체 번역 및 최신화 부탁드립니다..!

> 2. 같은 폴더 위치에 한국어로 번역은 되어 있는데, 내용이 업데이트가 되어 최신화 이전이면 미번역으로 판단하고 그냥 두어야 하는 건지

현재 작업은 레거시를 제거하고 source commit으로 현재 동기화 기준이되는 en-us 버전 기록하여, 추후 source commit 차이가 발생했을 때 diff만 업데이트 할 수 있도록 하기 위한 작업입니다. 따라서, 모두 번역 부탁드립니다.

다만, 존재하는 문서중 en-us 문서와 겹치는 내용이 하나도 없을 정도로 번역함에 있어서 이전 문서를 참고할 수 없으면 제거하셔도 무방합니다. 

6개 문서 기여하시기 조금 부담이 되신다면, 부담 안되시는 선에서 기여주셔도 괜찮습니다 :)

---

[PR 파일 개수 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/README.md)에 따라 한 리뷰어에게 너무 많은 리뷰가 몰리지 않도록 번역 PR의 경우 1개의 파일을 넘지 않는 것을 권장드리며, 사소한 변화 및 일괄적인 작업 PR에 대해서는 30개의 파일을 넘지 않는 것을 권장드립니다.

현재 PR의 경우 번역에 해당하여, 6개의 PR로 나누어서 기여주시면 더 좋을듯합니다. 충돌의 문제도 있고, 리뷰어의 부담이 낮아져서 보다 빠르게 반영될 수 있습니다.

2023-08-09 12:26 UTC, hochan222 commented on files/ko/web/javascript/closures/index.md
> +l10n:
source commit은 전체 페이지가 완전히 번역되었을때만 추가합니다. (60d5d8f18ee6bc48949c228bf236529f89a8cca7 hash 시점까지 최신화가 되어있으며 모두 한국어 번역이 되어있어야합니다.)

2023-08-09 12:26 UTC, hochan222 commented on files/ko/web/javascript/closures/index.md
> +A **closure** is the combination of a function bundled together (enclosed) with references to its surrounding state (the **lexical environment**). In other words, a closure gives you access to an out
[PR 규칙 안내서](https://github.com/mdn/translated-content/tree/main/docs/ko)에 따라 "파일 전체 번역을 원칙"으로 합니다. 하나의 파일에 대해 기여 주실 때 전체 번역 부탁드립니다.

2023-08-09 12:26 UTC, hochan222 commented on files/ko/web/javascript/data_structures/index.md
> +### Null type
제목도 번역 부탁드립니다 :)

2023-08-09 12:26 UTC, hochan222 commented on files/ko/web/javascript/data_structures/index.md
> +- A [`return`](/en-US/docs/Web/JavaScript/Reference/Statements/return) statement with no value (`return;`) implicitly returns `undefined`.
```suggestion
- A [`return`](/ko/docs/Web/JavaScript/Reference/Statements/return) statement with no value (`return;`) implicitly returns `undefined`.
```

[문서 연결 경로 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md)에 따라 ko로 표기 부탁드립니다.

2023-08-09 12:26 UTC, hochan222 commented on files/ko/web/javascript/data_structures/index.md
> +## See also
```suggestion
## 같이 보기
```

용어의 번역이 궁금하실 때는 [용어 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md) 참고 부탁드립니다. 보통 제목은 용어 안내서에 거의 다 명시되어 있습니다.

2023-08-09 12:29 UTC, hochan222 commented on files/ko/web/javascript/memory_management/index.md
> +  sourceCommit: d85a7ba8cca98c2f6cf67a0c44f0ffd467532f20
sourceCommit은 모두 최신화 되었을 때, 올바른 hash값 들어가 있습니다. 👍👍

2023-08-09 13:17 UTC, IMHOJEONG commented
> 하나의 문서에 대해 전체 번역 및 최신화 부탁드립니다..!

> 현재 작업은 레거시를 제거하고 source commit으로 현재 동기화 기준이되는 en-us 버전 기록하여, 추후 source commit 차이가 발생했을 때 diff만 업데이트 할 수 있도록 하기 위한 작업입니다. 따라서, 모두 번역 부탁드립니다. 다만, 존재하는 문서중 en-us 문서와 겹치는 내용이 하나도 없을 정도로 번역함에 있어서 이전 문서를 참고할 수 없으면 제거하셔도 무방합니다.

> 현재 PR의 경우 번역에 해당하여, 6개의 PR로 나누어서 기여주시면 더 좋을듯합니다. 충돌의 문제도 있고, 리뷰어의 부담이 낮아져서 보다 빠르게 반영될 수 있습니다.

빠른 시간에 적절한 피드백 감사합니다! 

다시 번역 파일 꼼꼼히 보고 번역하여, 피드백 받도록 하겠습니다.

2023-09-09 16:28 UTC, hochan222 commented
@IMHOJEONG 님 안녕하세요.

현재 PR 내용 다른 PR에서 모두 처리된 듯 하여, closed 처리하겠습니다. 좋은 하루 보내세요 :)

2023-09-09 16:28 UTC, closed without merging

2023-09-10 02:52 UTC, IMHOJEONG commented
@hochan222 님 안녕하세요
넵. 이 pr은 종합적으로 다른 pr 관리하려고 만들었어서 
Closed 해도 될 거 같습니다.
감사합니다