Update index.md
mdn/translated-content pull request #15031
Opened 2023-08-10 04:36 UTC by KukHyunLim

css_lists 최신화

### Description

3. css_lists최신화 하였습니다. (구,CSS_Lists_and_Counters)

### Motivation

### Additional details

- title 변경
- page-type: css-module 추가
- spec-urls: https://drafts.csswg.org/css-lists/ 추가
- 번역 수정
- 안내서 링크 최신화
- 안내서 항목추가

### Related issues and pull requests
Relates to #3840

2023-08-10 05:13 UTC, KukHyunLim commented
Lint에 표시된 부분 수정해서 올렸는데 계속 fail이 뜨고 있습니다.
추가로 수정할 부분이 있을까요?

2023-08-10 07:53 UTC, IMHOJEONG reviewed
@KukHyunLim 님 안녕하세요. 
혹시 이 부분이 아닐까 싶어서 comment 남겨봅니다

2023-08-10 07:53 UTC, IMHOJEONG commented on files/ko/web/css/css_lists/index.md
@KukHyunLim 님 안녕하세요! 
```plain
index.md:12 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
```
위 에러에 따라, 혹시 이 부분에 있는 공백은 지워주실 수 있을까요?

2023-08-10 07:54 UTC, KukHyunLim commented on files/ko/web/css/css_lists/index.md
넵 삭제후 푸시하겠습니다.

2023-08-11 01:09 UTC, IMHOJEONG commented
@KukHyunLim 님 안녕하세요. 
제가 정식 reviewer가 아니기도 하고, PR 읽어보다가 이 부분에 오류난 거 같아서 comment 남긴 부분이라 
@wisedog 님께서 해주셔야 할 부분인 거 같습니다.

2023-08-11 01:14 UTC, KukHyunLim commented
@IMHOJEONG 아! 넵 알겠습니다 감사합니다~

2023-08-12 05:21 UTC, wisedog requested changes
첫 기여 감사합니다. 
몇 가지 수정 사항과 한 가지 질문을 남겼습니다. 확인 부탁드립니다.

2023-08-12 05:21 UTC, wisedog commented on files/ko/web/css/css_counter_styles/index.md
> +page-type: css-module
[MetaData 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md) 에 따라 `page-type`, `browser-compat` 을 삭제해주시고 `l10n`을 넣어주시기 바랍니다.

2023-08-12 05:21 UTC, wisedog commented on files/ko/web/css/css_lists/index.md
> +page-type: css-module
이 역시 메타데이터 안내서를 참고하시기 바랍니다.

2023-08-12 05:21 UTC, wisedog commented on files/ko/web/css/css_counter_styles/index.md
> +### 규칙 지시자
원문은 at-rules 네요. `규칙 지시자`로 번역하신 이유가 궁금합니다!

2023-08-14 02:03 UTC, KukHyunLim commented on files/ko/web/css/css_counter_styles/index.md
> +### 규칙 지시자
css에서 "@"를 at-규칙(at-rules)로 부르는데 "@"가 지시자의 역할을 한다고 생각해서 "@"로 쓸수 있는 단어 목록이라. 규칙 지시자로 번역하였습니다.

2023-08-14 02:04 UTC, KukHyunLim commented on files/ko/web/css/css_counter_styles/index.md
> +page-type: css-module
수정하였습니다.

2023-08-14 02:05 UTC, KukHyunLim commented on files/ko/web/css/css_lists/index.md
> +page-type: css-module
수정하였습니다.

2023-08-14 04:01 UTC, wisedog commented on files/ko/web/css/css_counter_styles/index.md
> +### 규칙 지시자
오호.. 네네 알겠습니다.

2023-08-14 05:24 UTC, wisedog approved these changes

2023-08-14 05:25 UTC, merged