[revise]: revise index.md for `web/javascript/language_overview`
mdn/translated-content pull request #15048
Opened 2023-08-11 01:52 UTC by IMHOJEONG

### Description

 - #15001 의 web/javascript/language_overview 입니다. 

### Motivation

#14965 중에 최신화 & sourceCommit 추가하는 작업 진행중입니다.

### Additional details

용어 안내집를 주로 참고해서 구성하였고, 없는 부분들은 읽어보았을 때 자연스러운 단어를 선택해서 번역하였습니다.

### Related issues and pull requests

#14965 
#15001

2023-08-18 07:26 UTC, cos18 commented
@IMHOJEONG
안녕하세요. 리뷰어로 지정된 @cos18 입니다. 양이 워낙 많은 문서다 보니 리뷰가 지연중인 점 알리고자 코멘트 작성드립니다. 현재 절반정도 리뷰 완료하였고, 이번 주말 전까지는 1차 리뷰를 남겨놓을 예정입니다. 기다려주시면 감사드리겠습니다 😢

2023-08-18 16:51 UTC, IMHOJEONG commented
@cos18 님 안녕하세요.

저는 괜찮습니다! 오히려 시간 내서 피드백 해주시는 게 감사합니다.

천천히 해주셔도 괜찮으니 기다리겠습니다.

2023-08-20 05:30 UTC, cos18 requested changes
기여 감사합니다!
다만 읽다보니 의문이 드는 점이, 후반부로 갈수록 특정 단어들을 원문과 함께 작성하시는 경우가 많고 (예를들어 `모듈(Modules)`), 실제 H2 제목들에 대해서도 대다수 이와 같은 형식으로 작성하셨더라고요. 제 의견은 번역하였지만 의미가 와닫지 않는 내용들에 대해선 위와 같이 원문과 같이 표기해주는게 좋다고 보지만 이외 내용들에 대해서는 너무 불필요한 원문 표시인거 같습니다. 한번 전체적으로 리뷰 읽어보시고 의견 남겨주세요!

2023-08-20 05:30 UTC, cos18 commented on files/ko/web/javascript/language_overview/index.md
>  ```
원문에서는 두 예시가 합쳐져 있습니다. 합치면 더 좋을 것 같네요.

2023-08-20 05:30 UTC, cos18 commented on files/ko/web/javascript/language_overview/index.md
>  이 예는 조금 어리석어 보이지만, 함수는 추가적로 전달한 매개변수를 함수 내부에서 접근할 수 있습니다. 이 [`arguments`](/ko/docs/Web/JavaScript/Reference/Functions/arguments)라는 객체는 매개변수로 전달한 모든 값을 가지고 있는 배열과 비슷한 객체입니다. 우리가 원하는만큼 값을 처리하는 add 함수로
```suggestion
```
원문에서 삭제된 문단입니다.

2023-08-20 05:30 UTC, cos18 commented on files/ko/web/javascript/language_overview/index.md
> +JavaScript에는 명명된 매개 변수가 없다고 언급했습니다. 하지만 객체를 편리하게 하나로 합치고, 분해할 수 있는 [(객체 분해)object destructuring](/ko/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)를 사용하여 구현할 수 있습니다.
```suggestion
JavaScript에는 명명된 매개 변수가 없다고 언급했습니다. 하지만 객체를 편리하게 하나로 합치고, 분해할 수 있는 [구조 분해 할당](/ko/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)을 사용하여 구현할 수 있습니다.
```
번역된 키워드를 사용하는 것이 좋아보입니다.

2023-08-20 05:30 UTC, cos18 commented on files/ko/web/javascript/language_overview/index.md
> +[기본 파라미터(_default parameter_)](/ko/docs/Web/JavaScript/Reference/Functions/Default_parameters) 구문도 있는데, 생략된 매개변수(또는 `undefined`로 전달된 매개변수)가 기본값을 갖도록 허용합니다.
```suggestion
[기본값 매개변수](/ko/docs/Web/JavaScript/Reference/Functions/Default_parameters) 구문도 있는데, 생략된 매개변수(또는 `undefined`로 전달된 매개변수)가 기본값을 갖도록 허용합니다.
```

2023-08-20 05:30 UTC, cos18 commented on files/ko/web/javascript/language_overview/index.md
> +위에 정의된 익명 함수는 인수와 함께 `avg()`와 같은 형태로 실행할 수 있습니다. 즉, `function avg()`와 같이 이름을 붙인 함수 선언과 의미적으로 같습니다.
```suggestion
위에 정의된 익명 함수는 인수와 함께 `avg()`와 같은 형태로 실행할 수 있습니다. 즉, `function avg() {}`와 같이 이름을 붙인 함수 선언과 의미적으로 같습니다.
```
중괄호가 빠져 있습니다.

2023-08-20 05:30 UTC, cos18 commented on files/ko/web/javascript/language_overview/index.md
> +[화살표 함수 표현식(arrow function expression)](/ko/docs/Web/JavaScript/Reference/Functions/Arrow_functions)을 사용하여 익명 함수를 정의하는 또 다른 방법이 있습니다.
```suggestion
[화살표 함수](/ko/docs/Web/JavaScript/Reference/Functions/Arrow_functions)를 사용하여 익명 함수를 정의하는 또 다른 방법이 있습니다.
```

2023-08-20 05:30 UTC, cos18 commented on files/ko/web/javascript/language_overview/index.md
> +익명 함수가 유용할 수 있는 또 다른 방법이 있습니다. [즉시 실행 함수 표현식(IIFE, Immediately Invoked Function Expressions)](/ko/docs/Glossary/IIFE)라는 단일 표현식에서 익명 함수를 동시에 선언하고 호출할 수 있습니다.
```suggestion
익명 함수가 유용할 수 있는 또 다른 방법이 있습니다. [즉시 실행 함수 표현(IIFE, Immediately Invoked Function Expressions)](/ko/docs/Glossary/IIFE)이라는 단일 표현식에서 익명 함수를 동시에 선언하고 호출할 수 있습니다.
```

2023-08-20 05:30 UTC, cos18 commented on files/ko/web/javascript/language_overview/index.md
> +JavaScript의 함수 선언은 다른 함수 내부에서도 가능합니다. JavaScript의 중첩 함수(nested functions)에서는 부모 함수 범위에 있는 변수에 접근이 가능하다는게 중요합니다.
```suggestion
JavaScript의 함수 선언은 다른 함수 내부에서도 가능합니다. JavaScript의 중첩 함수에서는 부모 함수 범위에 있는 변수에 접근이 가능하다는게 중요합니다.
```
굳이 괄호를 통해 원문 단어를 언급하지 않아도 충분히 이해할 수 있는 내용으로 보입니다.

2023-08-20 05:30 UTC, cos18 commented on files/ko/web/javascript/language_overview/index.md
> +정적 속성은 `정적`을 추가하여 생성됩니다. Private 속성은 hash(`#`) (`private` 키워드가 아닙니다)를 앞에 추가하여 생성됩니다. 이 해시는 속성 이름의 필수적인 부분입니다(Python에서 `#`을 `_`로 생각하세요). 대부분의 다른 언어와 달리, 클래스 본체 외부에서 Private 속성을 읽을 수 있는 방법이 전혀 없습니다. 파생
```suggestion
정적 속성은 `static`을 추가하여 생성됩니다. Private 속성은 hash(`#`) (`private` 키워드가 아닙니다)를 앞에 추가하여 생성됩니다. 이 해시는 속성 이름의 필수적인 부분입니다. (Python에서 `#`을 `_`로 생각하세요.) 대부분의 다른 언어와 달리, 클래스 본체 외부에서 Private 속성을 읽을 수 있는 방법이 전혀 없습니다. 파생 클래스(derived classes)에서도 마찬가지입니다.
```
보통 ` (백틱)을 통해 작성된 내용들은 문법에서의 키워드를 표현하는 경우가 많습니다. 이는 문법 키워드로 번역 없이 그대로 작성되어야 합니다.

2023-08-20 05:30 UTC, cos18 commented on files/ko/web/javascript/language_overview/index.md
> +### 비동기 프로그래밍(Asynchronous Programming)
```suggestion
## 비동기 프로그래밍
```
depth가 잘못되어 있습니다. 또한 굳이 원문을 같이 작성할 필요가 있을까 싶습니다.

2023-08-20 05:30 UTC, cos18 commented on files/ko/web/javascript/language_overview/index.md
> +JavaScript는 본질적으로 단일 스레드입니다. [병렬화(paralleling)](https://en.wikipedia.org/wiki/Parallel_computing)가 없고, [동시성(concurrency)](https://en.wikipedia.org/wiki/Concurrent_computing)만 가능합니다. 비동기 프로그래밍은 [이벤트 루
```suggestion
JavaScript는 본질적으로 단일 스레드입니다. [병렬화](https://en.wikipedia.org/wiki/Parallel_computing)가 없고, [동시성](https://en.wikipedia.org/wiki/Concurrent_computing)만 가능합니다. 비동기 프로그래밍은 [이벤트 루프](/ko/docs/Web/JavaScript/Event_loop)에 의해 구동되며, 이를 통해 일련의 작업을 대기하고 완료를 위해 폴링(polling)할 수 있습니다.
```

2023-08-20 05:30 UTC, cos18 commented on files/ko/web/javascript/language_overview/index.md
> +언어의 중요한 부분은 어떠한 비동기 프로그래밍 기능을 특정하지 않지만, [사용자 권한 요청](/ko/docs/Web/API/Permissions_API)부터, [데이터 가져오기(fetch)](/ko/docs/Web/API/Fetch_API/Using_Fetch) 및 [파일 읽기](https://nodejs.org/api/fs.html)까지 외부 환경과 상
```suggestion
언어의 중요한 부분은 어떠한 비동기 프로그래밍 기능을 특정하지 않지만, [사용자 권한 요청](/ko/docs/Web/API/Permissions_API)부터, [데이터 가져오기](/ko/docs/Web/API/Fetch_API/Using_Fetch) 및 [파일 읽기](https://nodejs.org/api/fs.html)까지 외부 환경과 상호작용을 할 때 중요합니다. 잠재적으로 오래 실행되는 작업을 비동기식으로 유지하면, 이 프로세스가 대기하는 동안 다른 프로세스가 계속 실행될 수 있습니다. 예를 들어, 사용자가 권한을 부여하기 위해 버튼을 클릭하기를 기다리는 동안, 브라우저가 정지되지 않습니다.
```

2023-08-20 05:30 UTC, cos18 commented on files/ko/web/javascript/language_overview/index.md
> +JavaScript는 또한 대부분의 런타임에서 지원하는 모듈 시스템을 사용합니다. 모듈은 일반적으로 파일 경로 또는 URL로 식별되는 파일입니다. [`import`](/ko/docs/Web/JavaScript/Reference/Statements/import) 및 [`export`](/ko/docs/Web/JavaScript/Reference/Statem
```suggestion
또한 JavaScript는 대부분의 런타임에서 지원하는 모듈 시스템을 사용합니다. 모듈은 일반적으로 파일 경로 또는 URL로 식별되는 파일입니다. [`import`](/ko/docs/Web/JavaScript/Reference/Statements/import) 및 [`export`](/ko/docs/Web/JavaScript/Reference/Statements/export)를 모듈 간에 데이터를 교환하는 명령문으로 사용할 수 있습니다.
```
제거되지 않은 원문이 있습니다.
추가로 번역투의 내용을 수정했습니다.

2023-08-20 05:30 UTC, cos18 commented on files/ko/web/javascript/language_overview/index.md
> +// 내보내기(export) 하지 않은 변수는 모듈 내에서 로컬 변수 범위를 가집니다.
```suggestion
// export 하지 않은 변수는 모듈 내에서 지역 변수 범위를 가집니다.
```
`export`는 키워드다 보니 번역을 하면 더욱 어색해 보입니다.

2023-08-20 05:30 UTC, cos18 commented on files/ko/web/javascript/language_overview/index.md
> +그러나, JavaScript 언어는 표준 라이브러리 모듈을 제공하지 않습니다. 대신 모든 핵심 기능은 [`Math`](/ko/docs/Web/JavaScript/Reference/Global_Objects/Math) 및 [`Intl`](/ko/docs/Web/JavaScript/Reference/Global_Objects/Intl)과 같은 전역 변수로 구
```suggestion
그러나, JavaScript 언어는 표준 라이브러리 모듈을 제공하지 않습니다. 대신 모든 핵심 기능은 [`Math`](/ko/docs/Web/JavaScript/Reference/Global_Objects/Math) 및 [`Intl`](/ko/docs/Web/JavaScript/Reference/Global_Objects/Intl)과 같은 전역 변수로 구동됩니다. 이것은 모듈 시스템이 없는 JavaScript의 오랜 역사와, 모듈 시스템을 선택한다면 런타임 설정에 대한 일부 변경이 포함된다는 사실 때문입니다.
```
어색한 부분을 최대한 이해되도록 수정했습니다.

2023-08-20 05:30 UTC, cos18 commented on files/ko/web/javascript/language_overview/index.md
> +### 언어 및 런타임
```suggestion
## 언어 및 런타임
```

2023-08-20 05:30 UTC, cos18 commented on files/ko/web/javascript/language_overview/index.md
> +런타임 또는 호스트는 JavaScript 엔진(인터프리터)에 데이터를 공급하고 추가 전역 속성을 제공하며, 엔진이 외부 세계와 상호 작용할 수 있도록 훅을 제공합니다. 모듈 확인, 데이터 읽기, 메시지 인쇄, 네트워크 요청 보내기 등은 모두 런타임 수준 작업입니다. JavaScript는 처음부터 브라우저([DOM](/ko/docs/Web/API/Docum
```suggestion
런타임 또는 호스트는 JavaScript 엔진(인터프리터)에 데이터를 공급하고 추가 전역 속성을 제공하며, 엔진이 외부 세계와 상호 작용할 수 있도록 훅을 제공합니다. 모듈 확인, 데이터 읽기, 메시지 인쇄, 네트워크 요청 보내기 등은 모두 런타임 수준 작업입니다. JavaScript는 처음부터 브라우저([DOM](/ko/docs/Web/API/Document_Object_Model)과 같은 API를 제공합니다), Node.js([파일 시스템 접근](https://nodejs.org/api/fs.html)과 같은 API를 제공합니다)와 같은 다양한 환경에서 채택되었습니다. JavaScript는 (가장 주요 목적인) 웹, 모바일 앱, 데스크탑 앱, 서버 측 앱, 서버리스, 임베디드 시스템 등에 성공적으로 통합되었습니다. JavaScript 핵심 기능에 대해 배우는 동안, 지식을 사용하기 위해 호스트에서 제공하는 기능을 이해하는 것도 중요합니다. 예를 들어, 브라우저 및 경우에 따라 비브라우저에 의해 구현되는 모든 [웹 플랫폼 API](/ko/docs/Web/API)에 대해 읽어볼 수 있습니다.
```

2023-08-20 05:30 UTC, cos18 commented on files/ko/web/javascript/language_overview/index.md
> +- [정규표현식(Regular expressions)](/ko/docs/Web/JavaScript/Guide/Regular_expressions)
```suggestion
- [상속과 프로토타입 체인](/ko/docs/Web/JavaScript/Inheritance_and_the_prototype_chain)
- [클로저(Closures)](/ko/docs/Web/JavaScript/Closures)
- [정규표현식](/ko/docs/Web/JavaScript/Guide/Regular_expressions)
```

2023-08-27 17:15 UTC, IMHOJEONG commented on files/ko/web/javascript/language_overview/index.md
> +불리언 연산자는 논리 연산자 `&&` (논리합), `||` (논리곱), 그리고 `!` (부정)이 지원됩니다. [연산자](#operators)를 참조하세요.
[연산자](#operators) => [연산자](#연산자)로 수정하였습니다.

2023-08-27 17:16 UTC, IMHOJEONG commented on files/ko/web/javascript/language_overview/index.md
> +하지만 이렇게 할 필요는 거의 없습니다. JavaScript는 이러한 변환 작업을 `if` 문([제어 구조](#control_structures) 참고)과 같이 불리언 값이 필요한 경우를 만나게 되면 자동으로 변환하기 때문입니다. 이러한 이유로 인해 우리는 때때로 "[참 같은 값(truthy)](/ko/docs/Glossary/Truthy)"와 "[거짓
[제어 구조](#control_structures) => [제어 구조](#제어_구조)로 수정하였습니다.

2023-08-27 17:19 UTC, IMHOJEONG commented
@cos18 님 안녕하세요.

어우... 피드백을 통해, 제가 얼마나 실수가 많았는지 알게 되서, 감사합니다!

그리고, 읽어보면서 

https://github.com/mdn/translated-content/pull/15048#discussion_r1306696459
https://github.com/mdn/translated-content/pull/15048#discussion_r1306696568

두 개의 링크가 작동 안 되는 수정 사항도 반영했습니다. 

다 읽어보시고 피드백까지 일일이 하시느라 너무 고생하셨습니다!

2023-08-29 07:18 UTC, cos18 approved these changes
LGTM! 큰 문서 기여해주셔서 감사합니다 :)

2023-08-29 07:55 UTC, merged