[ko] Translate Learn/Performance/Multimedia
mdn/translated-content pull request #15055
Opened 2023-08-11 06:43 UTC by dev-song

### Description

Translate [Multimedia: Images](https://developer.mozilla.org/en-US/docs/Learn/Performance/Multimedia) in MDN in Korean, following #13043

### Motivation

Interest in Web performance, deeper understanding by translating the subject

### Additional details

None

### Related issues and pull requests

#13043 Previous pull request, translating another web performance page on mdn

2023-08-13 17:59 UTC, hochan222 requested changes
@dev-song 님 안녕하세요.

고생 많으셨습니다. 리뷰사항 하기에 남겨두었습니다.

좋은 하루 보내세요.

---

+ 모든 이미지 파일들은 content repo에서 제공되는 파일들로 제공되기에 중복으로 포함하시지 않으셔도 됩니다. ar-guide.jpg 파일 제거 부탁드립니다 :)

2023-08-13 17:59 UTC, hochan222 commented on files/ko/learn/performance/multimedia/index.md
> +이미지 전송에 있어 "one size fits all" (역주: 사이즈와 무관하게 입을 수 있는 옷) 방식의 접근법은 최상의 결과를 내지 못합니다. 작은 화면에서는 이미지를 낮은 해상도로, 큰 화면에서는 반대로 높은 해상도로 제공하고 싶을 것이기 때문이죠. 그 외에 높은 DPI를 갖는 화면 (예: "레티나") 기기에도 높은 해상도로 제공하고 싶을 것입니다
```suggestion
이미지 전송에 있어 "모두에게 적합한" 방식의 접근법은 최상의 결과를 내지 못합니다. 작은 화면에서는 이미지를 낮은 해상도로, 큰 화면에서는 반대로 높은 해상도로 제공하고 싶을 것이기 때문이죠. 그 외에 높은 DPI를 갖는 화면 (예: "레티나") 기기에도 높은 해상도로 제공하고 싶을 것입니다.
```

(1) 역주는 최대한 사용을 하지 않는것을 원칙으로 합니다. 현재 문장에서는 제안과 같은 방향도 충분히 의미전달을 할 수 있다고 생각합니다.

(2)
> That's where you would need to upgrade your `<picture>` and `<source>` elements with [media](/en-US/docs/Web/HTML/Element/source#media) and/or [sizes](/en-US/docs/Web/HTML/Element/source#sizes) attributes. A detailed article on how to combine all of these attributes can be found [here](https://www.smashingmagazine.com/2014/05/responsive-images-done-right-guide-picture-srcset/).

누락된 문장이 있습니다.

2023-08-13 17:59 UTC, hochan222 commented on files/ko/learn/performance/multimedia/index.md
> +높은 DPI를 갖는 화면들을 다룰 땐 다음의 두 가지 흥미로운 효과들을 염두에 두세요.
```suggestion
높은 해상도의 화면들을 다룰 땐 다음의 두 가지 흥미로운 효과들을 염두에 두세요.
```

해상도도 좋을듯하여 리뷰드렸습니다.

2023-08-13 17:59 UTC, hochan222 commented on files/ko/learn/performance/multimedia/index.md
> +- [매우 적은 수의 사람들만이 2x DPI 이상의 해상도 상승을 알아차립니다.](https://observablehq.com/@eeeps/visual-acuity-and-device-pixel-ratio) 그러므로 해상도를 2x보다 더 높게 제공할 필요는 없습니다.
```suggestion
- [아주 소수의 사람들만 2배 이상의 DPI에서 해상도 증가를 알아차립니다.](https://observablehq.com/@eeeps/visual-acuity-and-device-pixel-ratio) 이는 2배 이상 해상도의 이미지를 제공할 필요가 없음을 의미합니다.
```

조금 더 자연스럽게 수정해보았습니다.

2023-08-13 17:59 UTC, hochan222 commented on files/ko/learn/performance/multimedia/index.md
> +둘째로, Priority Hints가 도입되면서, 이미지 태그에 `fetchPriority` 속성을 적용하여 우선순위를 추가로 조절할 수 있습니다. 적절한 사용 예시로 이미지 캐러셀의 첫 번째 이미지가 이어지는 이미지들보다 높은 우선순위를 갖도록 구현하는 것이 있습니다.
```suggestion
둘째로, 우선순위 힌트가 도입되면서, 이미지 태그에 `fetchPriority` 속성을 적용하여 우선순위를 추가로 조절할 수 있습니다. 적절한 사용 예시로 이미지 캐러셀의 첫 번째 이미지가 이어지는 이미지들보다 높은 우선순위를 갖도록 구현하는 것이 있습니다.
```

번역해도 무방할듯합니다. 마음이 쓰이신다면 `우선순위 힌트(Priority Hints)` 추천드립니다.

2023-08-13 17:59 UTC, hochan222 commented on files/ko/learn/performance/multimedia/index.md
> +### 렌더링 전략: 이미지 로딩 시 Jank 예방하기
```suggestion
### 렌더링 전략: 이미지 로딩 시 버벅거림 방지하기
```

2023-08-13 17:59 UTC, hochan222 commented on files/ko/learn/performance/multimedia/index.md
> +브라우저는 HTML이 파싱되면서 내용을 렌더링하기 시작합니다. 많은 경우 이는 이미지 같은 자원들이 모두 다운로드되는 시점 이전이죠. 이미지 크기를 포함시키면 브라우저가 최초의 페이지 렌더링 시 각 이미지가 표시될 정확한 크기의 플레이스홀더를 준비할 수 있습니다.
```suggestion
브라우저는 이미지를 포함한 모든 자산이 다운로드되기 전에 HTML이 구문 분석될 때 콘텐츠 렌더링을 시작합니다. 이미지 크기를 포함시키면 브라우저가 최초의 페이지 렌더링 시 각 이미지가 표시될 정확한 크기의 플레이스홀더를 준비할 수 있습니다.
```

상기 번역은 어떠한가요?

2023-08-13 17:59 UTC, hochan222 commented on files/ko/learn/performance/multimedia/index.md
> +`width`와 `height` 속성이 없다면 플레이스홀더 공간이 만들어지지 않기 때문에, 페이지 렌더링 후 이미지 로드 시점에 눈에 띄는 {{glossary('jank')}}나 Layout Shift가 생깁니다. 페이지 Reflow와 Repaint 모두 성능과 사용성 문제에 해당하죠.
```suggestion
`width`와 `height` 속성이 없다면 플레이스홀더 공간이 만들어지지 않기 때문에, 페이지 렌더링 후 이미지 로드 시점에 눈에 띄는 {{glossary('jank', '버벅거림(jank)')}}나 Layout Shift가 생깁니다. 페이지 Reflow와 Repaint 모두 성능과 사용성 문제에 해당하죠.
```

2023-08-13 17:59 UTC, hochan222 commented on files/ko/learn/performance/multimedia/index.md
> +이 방법은 반응형 레이아웃에는 유용하지만 width와 height 정보가 포함되어 있지 않을 경우 Jank를 유발합니다. `<img>` 요소가 파싱되었지만 이미지는 로드되기 전에 height 정보가 없을 경우엔 height를 0으로 설정한 것과 같은 효과를 주기 때문이죠. 페이지가 화면에 최초로 렌더링된 후 이미지 로드 시점에 페이지는 Reflow, Re
```suggestion
이 방법은 반응형 레이아웃에는 유용하지만 너비 및 높이 정보가 포함되어 있지 않을 경우 버벅거림을 유발합니다. `<img>` 요소가 파싱되었지만 이미지는 로드되기 전에 높이 정보가 없을 경우엔 높이를 0으로 설정한 것과 같은 효과를 주기 때문이죠. 페이지가 화면에 최초로 렌더링된 후 이미지 로드 시점에 페이지는 Reflow, Repaint되며 새로 설정된 높이를 위한 공간을 만들면서 Layout Shift가 생깁니다.
```

2023-08-13 17:59 UTC, hochan222 commented on files/ko/learn/performance/multimedia/index.md
> +가로 세로 비율은 그 다음으로 이미지의 높이를 계산하는 데 쓰이고, 그 결과 `<img>` 요소의 정확한 크기가 적용됩니다. 이렇게 되면 경우 이미지 로드 시 앞에서 얘기한 jank가 아예 일어나지 않거나 최소화됩니다. 목록으로 주어진 이미지 크기들이 정확하지 않더라도 말이죠.
```suggestion
가로 세로 비율은 그 다음으로 이미지의 높이를 계산하는 데 쓰이고, 그 결과 `<img>` 요소의 정확한 크기가 적용됩니다. 이렇게 되면 경우 이미지 로드 시 앞에서 얘기한 버벅거림이 아예 일어나지 않거나 최소화됩니다. 목록으로 주어진 이미지 크기들이 정확하지 않더라도 말이죠.
```

2023-08-13 17:59 UTC, hochan222 commented on files/ko/learn/performance/multimedia/index.md
> +지난 10년 동안 HTML에 {{htmlelement("img")}} 태그에 이미지를 쓸 때 `width`와 `height` 속성을 제외하는 것이 모범 사례로 추천되었었지만, 가로 세로 비율 매핑으로 인해 이제는 이 두 속성을 포함시키는 것이 모범 사례입니다.
```suggestion
지난 10년 동안 HTML에 {{htmlelement("img")}} 태그에 이미지를 쓸 때 `width`와 `height` 속성을 생략하는 것이 개발자 모범 사례로 추천되었었지만, 가로 세로 비율 매핑으로 인해 이제는 이 두 속성을 포함시키는 것이 모범 사례입니다.
```

생략의 수준은 어떠한가요!

2023-08-13 17:59 UTC, hochan222 commented on files/ko/learn/performance/multimedia/index.md
> +이 섹션에선 이미지 최적화에 대해 살펴보았습니다. 이제 평균적으로 웹사이트 데이터 중 절반에 달하는 부분을 최적화하는 방법에 대해 전체적으로 이해했을 것입니다. 이미지는 사용자들의 데이터를 소모하고 페이지 로딩을 느리게 하는 단 하나의 미디어 유형일 뿐입니다. 다음에는 데이터의 약 20%를 차지하는 비디오를 최적화하는 방법에 대해서 살펴봅니다.
```suggestion
이 섹션에선 이미지 최적화에 대해 살펴보았습니다. 이제 평균 웹사이트 대역폭 총계의 절반에 달하는 부분을 최적화하는 방법에 대해 전체적으로 이해했을 것입니다. 이미지는 사용자들의 대역폭을 소모하고 페이지 로딩을 느리게 하는 단 하나의 미디어 유형일 뿐입니다. 다음에는 대역폭 소모의 약 20%를 차지하는 비디오를 최적화하는 방법에 대해서 살펴보겠습니다.
```

2023-08-17 04:20 UTC, dev-song commented on files/ko/learn/performance/multimedia/index.md
> +평균적으로 웹사이트의 데이터 중 [51%를 이미지가, 25%는 비디오가 차지](https://discuss.httparchive.org/t/state-of-the-web-top-image-optimization-strategies/1367)하기 때문에, 멀티미디어를 능숙하게 다루고 최적화하는 것은 중요하다고 할 수 있습니다.
`일반적인`이 훨씬 나은 것 같습니다!
일반적인 웹사이트의 [데이터 전송량 중 51%는 ~~] 으로 고치도록 하겠습니다.

2023-08-17 04:26 UTC, dev-song commented on files/ko/learn/performance/multimedia/index.md
> +이미지는 데이터 전송량 중 가장 큰 부분을 차지하지만, 이미지 다운로드가 [사용자가 인지하는 성능](/ko/docs/Learn/Performance/Perceived_performance)에 영향을 끼치는 정도는 많은 사람들의 생각보다 훨씬 적습니다. 가장 큰 이유는 페이지 내 텍스트가 즉시 다운로드되어 표시되고 사용자들이 이미지가 도착하면서 렌더링되는
`여전히 중요하다`가 맥락상 다소 따로 노는 것 같아 생략했던 건데요,
음... 마지막 문장을 `하지만 그렇다 하더라도 방문자들이 이미지를 가능한 한 빨리 볼 수 있는 것은 좋은 사용자 경험을 위해 여전히 중요한 요소입니다`로 하면 어떨까요?

2023-08-17 04:32 UTC, dev-song commented on files/ko/learn/performance/multimedia/index.md
> +대부분의 웹사이트는 이미지에 [지연된 로딩(lazy loading)](/ko/docs/Web/Performance/Lazy_loading)을 적용해 크게 개선할 수 있습니다. 이 방법을 활용하면 최초에 페이지를 로딩할 때, 방문자의 스크롤 여부와 무관하게 모든 이미지를 한꺼번에 다운로드하는 것이 아니라 사용자에게 보이지 않는 곳에서 로드합니다. [lazy
beneath-the-fold를 찾아보니 `눈에 잘 띄지 않는`, `보이지 않는 곳에서`이다보니 이렇게 해석을 하게 되었는데요,
지금 보니 오역한 것 같네요.
`[lazy-loading](https://github.com/en-US/docs/Web/Performance/Lazy_loading) images beneath-the-fold`
부분에서 beneath-the-fold가 lazy-loading이 아닌 images를 수식하는 단어라면
`~~~ 다운로드하는 대신, 잘 보이지 않는 이미지를 [지연 로딩]~~~`으로 수정하면 어떨까 합니다!

2023-08-17 04:40 UTC, dev-song commented on files/ko/learn/performance/multimedia/index.md
> +'사진 같지 않은' 이미지, 즉 색상의 수가 적은 이미지에는 [SVG](/ko/docs/Web/Media/Formats/Image_types#svg_scalable_vector_graphics) 형식이 더 적합합니다. SVG 형식을 사용하려면 원본 이미지를 벡터 그래픽 형식으로 쓸 수 있어야 합니다. 만약 원본 이미지가 비트맵 형식으로만 존재한다면 [PN
motif가 다소 번역이 애매한 단어라 제외했었는데요,
`이런 주제의 유형으로는 로고, 일러스트, 차트, 아이콘 등이 있습니다.`로 수정하겠습니다~

2023-08-17 04:47 UTC, dev-song commented on files/ko/learn/performance/multimedia/index.md
> +지난 10년 동안 HTML에 {{htmlelement("img")}} 태그에 이미지를 쓸 때 `width`와 `height` 속성을 제외하는 것이 모범 사례로 추천되었었지만, 가로 세로 비율 매핑으로 인해 이제는 이 두 속성을 포함시키는 것이 모범 사례입니다.
훨씬 나은 것 같아요~ 감사합니다.

2023-08-17 04:49 UTC, dev-song commented on files/ko/learn/performance/multimedia/index.md
> +이 섹션에선 이미지 최적화에 대해 살펴보았습니다. 이제 평균적으로 웹사이트 데이터 중 절반에 달하는 부분을 최적화하는 방법에 대해 전체적으로 이해했을 것입니다. 이미지는 사용자들의 데이터를 소모하고 페이지 로딩을 느리게 하는 단 하나의 미디어 유형일 뿐입니다. 다음에는 데이터의 약 20%를 차지하는 비디오를 최적화하는 방법에 대해서 살펴봅니다.
데이터 전송량으로 수정하였습니다~

2023-08-17 04:55 UTC, dev-song commented on files/ko/learn/performance/multimedia/index.md
> +이미지 전송에 있어 "one size fits all" (역주: 사이즈와 무관하게 입을 수 있는 옷) 방식의 접근법은 최상의 결과를 내지 못합니다. 작은 화면에서는 이미지를 낮은 해상도로, 큰 화면에서는 반대로 높은 해상도로 제공하고 싶을 것이기 때문이죠. 그 외에 높은 DPI를 갖는 화면 (예: "레티나") 기기에도 높은 해상도로 제공하고 싶을 것입니다
누락된 부분 추가했습니다

2023-08-17 04:59 UTC, dev-song commented
매우매우 디테일한 리뷰 감사드립니다! 🙇 
대부분 리뷰 내용 그대로 반영하고 resolve 처리했고,
의견 요청하신 부분이나 다소 헷갈리는 부분들은 확인하실 수 있게 남겨놨습니다.
추가 의견 있으시면 맞춰서 더 수정할게요~

2023-08-19 06:29 UTC, hochan222 commented on files/ko/learn/performance/multimedia/index.md
> +이미지는 데이터 전송량 중 가장 큰 부분을 차지하지만, 이미지 다운로드가 [사용자가 인지하는 성능](/ko/docs/Learn/Performance/Perceived_performance)에 영향을 끼치는 정도는 많은 사람들의 생각보다 훨씬 적습니다. 가장 큰 이유는 페이지 내 텍스트가 즉시 다운로드되어 표시되고 사용자들이 이미지가 도착하면서 렌더링되는
좋아보입니다~!

2023-08-19 09:31 UTC, hochan222 commented on files/ko/learn/performance/multimedia/index.md
> +대부분의 웹사이트는 이미지에 [지연된 로딩(lazy loading)](/ko/docs/Web/Performance/Lazy_loading)을 적용해 크게 개선할 수 있습니다. 이 방법을 활용하면 최초에 페이지를 로딩할 때, 방문자의 스크롤 여부와 무관하게 모든 이미지를 한꺼번에 다운로드하는 것이 아니라 사용자에게 보이지 않는 곳에서 로드합니다. [lazy
@dev-song 님 좋은 주말입니다~!

Below The Fold라는 관용어로 사용되는 용어가 있으며, 아래 사진과같이 viewport 하단 영역을 나타냅니다. 의견주신 `잘 보이지 않는 이미지`는 해당 영역을 잘 나타내지 못하고 다르게 이해할 소지가 있어서, 개인적으로는 `스크롤 없이 볼 수 있는 이미지를`가 좋아보입니다. 다른 좋은 표현이 있다면 제안 부탁드립니다 :)

<img width="790" alt="image" src="https://github.com/mdn/translated-content/assets/22424891/f3ee3ece-202c-406f-aaa6-642d4f294576">


- [Below The Fold](https://vwo.com/glossary/below-the-fold/)

2023-08-19 09:38 UTC, hochan222 commented on files/ko/learn/performance/multimedia/index.md
> +'사진 같지 않은' 이미지, 즉 색상의 수가 적은 이미지에는 [SVG](/ko/docs/Web/Media/Formats/Image_types#svg_scalable_vector_graphics) 형식이 더 적합합니다. SVG 형식을 사용하려면 원본 이미지를 벡터 그래픽 형식으로 쓸 수 있어야 합니다. 만약 원본 이미지가 비트맵 형식으로만 존재한다면 [PN
좋습니다~!

2023-08-19 09:39 UTC, hochan222 requested changes
@dev-song 님 안녕하세요~!

https://github.com/mdn/translated-content/pull/15055#discussion_r1299162779 하나 확인해주시면 좋을듯합니다. 나머지는 모두 좋습니다~!

고생 많으셨습니다! 좋은 주말 보내세요 :)

2023-08-21 06:34 UTC, dev-song commented on files/ko/learn/performance/multimedia/index.md
> +대부분의 웹사이트는 이미지에 [지연된 로딩(lazy loading)](/ko/docs/Web/Performance/Lazy_loading)을 적용해 크게 개선할 수 있습니다. 이 방법을 활용하면 최초에 페이지를 로딩할 때, 방문자의 스크롤 여부와 무관하게 모든 이미지를 한꺼번에 다운로드하는 것이 아니라 사용자에게 보이지 않는 곳에서 로드합니다. [lazy
@hochan222 님 2차 리뷰 감사드립니다 :)

해당 용어가 존재하는지 몰랐었습니다. 정보 감사드려요!
그렇다면 말씀하신대로 `잘 보이지 않는 이미지`는 적절하지 않은 표현이라고 생각합니다.
다만 `viewport 하단 영역의 이미지 (beneath-the-fold)`를 `스크롤 없이 볼 수 있다`는 표현이 이해가 잘 안 되는 부분이 있습니다.
viewport 하단에 있다면 `스크롤을 해야 볼 수 있는` 이미지 아닌가 하는 생각이 들어서...
`스크롤 없이 볼 수 있는`의 의미를 조금 더 풀어서 설명해주실 수 있을까요?

2023-08-21 06:36 UTC, dev-song commented
@hochan222 님 안녕하세요!

2차 리뷰에서 코멘트 주셨던 부분 추가로 댓글 달아놨습니다.
https://github.com/mdn/translated-content/pull/15055#discussion_r1299666949
한 번 확인 부탁드려요~
항상 꼼꼼한 리뷰 감사합니다 :)

2023-08-28 12:18 UTC, hochan222 commented on files/ko/learn/performance/multimedia/index.md
> +대부분의 웹사이트는 이미지에 [지연된 로딩(lazy loading)](/ko/docs/Web/Performance/Lazy_loading)을 적용해 크게 개선할 수 있습니다. 이 방법을 활용하면 최초에 페이지를 로딩할 때, 방문자의 스크롤 여부와 무관하게 모든 이미지를 한꺼번에 다운로드하는 것이 아니라 사용자에게 보이지 않는 곳에서 로드합니다. [lazy
@dev-song 님 안녕하세요.

> viewport 하단에 있다면 스크롤을 해야 볼 수 있는 이미지 아닌가 하는 생각이 들어서...

제가 잘못 번역했네요..! `스크롤을 해야 볼 수 있는 이미지`이 올바른 번역입니다.

2023-08-29 09:03 UTC, dev-song commented
고생 많으셨습니다! 감사합니다~

2023-08-30 06:38 UTC, hochan222 approved these changes

2023-08-30 06:39 UTC, merged