ko: writing guidelines
mdn/translated-content pull request #15069
Opened 2023-08-12 09:58 UTC by SnowMarble

#15033

2023-09-07 02:47 UTC, SnowMarble commented
@hochan222 안녕하세요, PR이 방치되었는데 확인부탁드립니다.

2023-09-09 13:02 UTC, hochan222 requested changes
@SnowMarble 님, 안녕하세요.

리뷰사항 하기에 남겨두었습니다.

고생 많으셨습니다 :)

2023-09-09 13:03 UTC, SnowMarble commented on files/ko/mdn/writing_guidelines/index.md
> +title: 쓰기 지침
앗 찾아주셔서 고맙습니다!

2023-09-09 13:04 UTC, hochan222 approved these changes
LGTM :)

2023-09-09 13:06 UTC, merged