[ko] grid 원문에서 번역 안 된 부분 추가 및 오타 수정
mdn/translated-content pull request #15068
Opened 2023-08-12 08:25 UTC by 2kkeullim

### Description
`Grid` 파일의 전체적인 번역을 수정하였으며,
번역이 되어 있지 않은 영어 원문을 추가 번역하였습니다.

### Motivation

### Additional details

### Related issues and pull requests

2023-08-18 00:34 UTC, 2kkeullim commented
@yujo11 리뷰 부탁드립니다😊

2023-08-28 15:27 UTC, hochan222 requested changes
@2kkeullim 님 안녕하세요.

리뷰 사항 하기에 남겨두었습니다. 넘 잘 번역해주셔서 몇가지 문법 사항의 리뷰만 존재합니다. 고생 많으셨습니다.

기여해주셔서 감사합니다. 좋은 하루 보내세요 :)

2023-08-28 15:27 UTC, hochan222 commented on files/ko/learn/css/css_layout/grids/index.md
> +지금까지는 열 트랙만 지정했지만, 콘텐츠를 저장하기 위해 행도 만들어지고 있습니다. 이것은 _명시적_ 그리드와 _암시적_ 그리드의 예시입니다.
```suggestion
지금까지는 열 트랙만 지정했지만, 콘텐츠를 저장하기 위해 행도 만들어지고 있습니다. 이것은 명시적 그리드와 암시적 그리드의 예시입니다.
```

[기울임꼴 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md#%EA%B8%B0%EC%9A%B8%EC%9E%84%EA%BC%B4)에 따라 수정 부탁드립니다 :)

2023-08-28 15:27 UTC, hochan222 commented on files/ko/learn/css/css_layout/grids/index.md
> +이 글의 마지막까지 읽었지만 가장 중요한 정보를 기억할 수 있나요? 계속 진행하기 전에 이 정보를 기억하고 있는지 확인할 수 있는 몇 가지 추가 테스트가 있습니다. [Test your skills: Grid](/en-US/docs/Learn/CSS/CSS_layout/Grid_skills).
```suggestion
이 글의 마지막까지 읽었지만 가장 중요한 정보를 기억할 수 있나요? 계속 진행하기 전에 이 정보를 기억하고 있는지 확인할 수 있는 몇 가지 추가 테스트가 있습니다. [Test your skills: Grid](/ko/docs/Learn/CSS/CSS_layout/Grid_skills).
```

[문서 연결 경로 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md#%EB%AC%B8%EC%84%9C-%EC%97%B0%EA%B2%B0-%EA%B2%BD%EB%A1%9C)에 따라 위와 같이 수정 부탁드립니다 :)

2023-08-29 00:16 UTC, 2kkeullim commented
@hochan222 수정 완료하였습니다!! 리뷰해주셔서 감사합니다😊

2023-08-29 01:54 UTC, hochan222 approved these changes
고생 많으셨습니다! 좋은 하루 보내세요 :)

2023-08-29 03:01 UTC, merged