[revise]: revise index.md for `web/javascript/inheritance_and_the_prototype_chain`
mdn/translated-content pull request #15090
Opened 2023-08-13 16:42 UTC by IMHOJEONG

### Description

 - #15001 의 web/javascript/inheritance_and_the_prototype_chain입니다. 

### Motivation

#14965 중에 최신화 & sourceCommit 추가하는 작업 진행중입니다.

### Additional details

용어 안내집를 주로 참고해서 구성하였고, 없는 부분들은 읽어보았을 때 자연스러운 단어를 선택해서 번역하였습니다.

### Related issues and pull requests

#14965 
#15001

2023-09-17 11:17 UTC, hochan222 commented
@IMHOJEONG 님 안녕하세요.

리뷰어의 사정으로 변동되어서 리뷰가 지연될 수 있는점 양해 부탁드립니다. 

@pje1740 해당 리뷰 추가적으로 부탁드립니다..! 

감사합니다. 좋은 주말 보내세요 :)

2023-09-17 14:32 UTC, IMHOJEONG commented
@hochan222, @pje1740  님 안녕하세요.
앗 아닙니다~ 항상 꼼꼼한 피드백 주셔서 감사합니다!

2023-09-18 08:13 UTC, pje1740 requested changes
리뷰어 변경이 생겨서 문서 자체의 리뷰가 많이 늦어진 점 양해 부탁드립니다!
코멘트 확인 부탁 드립니다.

2023-09-18 08:13 UTC, pje1740 commented on files/ko/web/javascript/inheritance_and_the_prototype_chain/index.md
> +프로토타입 체인에서 상위에 있는 속성에 대한 조회 시간은 성능에 부정적인 영향을 미칠 수 있으며, 이는 성능이 중요한 코드에서 중요할 수 있습니다. 또한, 존재하지도 않는 속성에 접근하려는 시도는 항상 모든 프로토타입 체인인 전체를 탐색하게 됩니다.
```suggestion
프로토타입 체인에서 상위에 있는 속성에 대한 조회 시간은 성능에 부정적인 영향을 미칠 수 있으며, 이는 성능 중심의 코드에선 심각한 문제입니다. 또한, 존재하지도 않는 속성에 접근하려는 시도는 항상 모든 프로토타입 체인인 전체를 탐색하게 됩니다.
```

2023-09-18 08:13 UTC, pje1740 commented on files/ko/web/javascript/inheritance_and_the_prototype_chain/index.md
> +참고: 속성이 [`undefined`](/ko/docs/Web/JavaScript/Reference/Global_Objects/undefined)인지 확인하는 것만으로는 충분하지 않습니다. 속성이 존재할 수도 있지만, 해당 값은 `undefined`로 설정됩니다.
```suggestion
참고: 속성이 [`undefined`](/ko/docs/Web/JavaScript/Reference/Global_Objects/undefined)인지 확인하는 것만으로는 충분하지 않습니다. 속성이 존재하나 단순히 값이 `undefined`인 경우도 있습니다.
```

2023-09-18 08:13 UTC, pje1740 commented on files/ko/web/javascript/inheritance_and_the_prototype_chain/index.md
> +프로토타입 객체에 대한 참조는 새 인스턴스의 내부 `[[Prototype]]` 속성에 복사됩니다. 예를 들어, `const a1 = new A()`를 수행하면, JavaScript(메모리에 객체를 생성한 후 `this`가 정의된 함수 `A()`를 실행하기 전에)는 `a1.[[Prototype]] = A.prototype`을 설정합니다. 그런 다음 인스턴스
```suggestion
프로토타입 객체에 대한 참조는 새 인스턴스의 내부 `[[Prototype]]` 속성에 복사됩니다. 예를 들어, `const a1 = new A()`를 수행하면, JavaScript(메모리에 객체를 생성한 후 `this`를 정의한 `A()`를 실행하기 전에)는 `a1.[[Prototype]] = A.prototype`을 설정합니다. 그런 다음 인스턴스의 속성에 접근하면, JavaScript는 먼저 해당 객체에 직접 존재하는지 여부를 확인하고, 그렇지 않은 경우 `[[Prototype]]`에서 찾습니다. `[[Prototype]]`은 원하는 값을 찾을 때까지 재귀적으로 탐색합니다. 즉, `a1.doSomething`, `Object.getPrototypeOf(a1).doSomething`, `Object.getPrototypeOf(Object.getPrototypeOf(a1)).doSomething` 순서로 탐색하며, 값을 찾거나 `Object.getPrototypeOf`는 `null`일 때 탐색을 종료합니다. 이는 `prototype`에 정의된 모든 속성이 모든 인스턴스에서 효과적으로 공유되며, 나중에 `prototype`의 일부를 변경하고 변경 사항이 모든 기존 인스턴스에 나타나도록 할 수 있다는 것을 의미합니다.
```

2023-09-18 08:13 UTC, pje1740 commented on files/ko/web/javascript/inheritance_and_the_prototype_chain/index.md
> +If, in the example above, you do `const a1 = new A(); const a2 = new A();`, then `a1.doSomething` would actually refer to `Object.getPrototypeOf(a1).doSomething` — which is the same as the `A.prototy
원문 제거 부탁드립니다.

2023-09-18 08:13 UTC, pje1740 commented on files/ko/web/javascript/inheritance_and_the_prototype_chain/index.md
> +프로토타입 상속 모델을 사용하는 복잡한 코드를 작성하기 전에 프로토타입 상속 모델을 이해하는 것이 필수적입니다. 또한, 코드에서 프로토타입 체인의 길이를 알고 필요한 경우 가능한 성능 문제를 방지하기 위해 분할하세요. 또한, 네이티브 프로토타입은 최신 JavaScript 기능과의 호환성을 위한 경우가 아니면 **절대** 확장해서는 안 됩니다.
```suggestion
프로토타입 상속 모델을 사용하는 복잡한 코드를 작성하기 전에 프로토타입 상속 모델을 이해하는 것이 필수적입니다. 또한, 코드에서 프로토타입 체인의 길이를 파악하여 필요한 경우 성능 문제를 방지하기 위해 분할하세요. 또한, 내장 프로토타입은 최신 JavaScript 기능과의 호환성을 위한 경우가 아니면 **절대** 확장해서는 안 됩니다.
```

2023-09-18 16:02 UTC, IMHOJEONG commented on files/ko/web/javascript/inheritance_and_the_prototype_chain/index.md
> +`{ a: 1, b: 2, __proto__: c }`와 같은 객체 리터럴에서, 값 `c`(`null` 또는 다른 객체여야 합니다)는 다음의 `[[Prototype]]`이 됩니다. 리터럴로 표현되는 객체인 반면, `a` 및 `b`와 같은 다른 키는 객체의 *자체 속성*이 됩니다. `[[Prototype]]`은 객체의 "내부 속성"일 뿐이므로, 이 구문은
해당 객체로 변경하는 게 더 자연스러워 보여집니다.

2023-09-18 16:05 UTC, IMHOJEONG commented on files/ko/web/javascript/inheritance_and_the_prototype_chain/index.md
> +프로토타입의 힘은 속성들의 집합이 모든 인스턴스, 특히 메서드에 있어야 하는 경우, 속성들의 집합을 재사용할 할 수 있다는 점입니다. 각 상자는 `getValue` 함수를 통해 접근할 수 있는 값을 포함하는 객체인 많은 상자들을 만드는 것이라고 가정합니다. 네이티브한 구현은 다음과 같습니다.
넵 이 부분은 수정하겠습니다.

2023-09-18 16:07 UTC, IMHOJEONG commented on files/ko/web/javascript/inheritance_and_the_prototype_chain/index.md
> +> **참고:** 생성자 함수에서 기본이 아닌 값이 반환되면, 해당 값은 `new` 표현식의 결과가 됩니다. 이 경우, `[[Prototype]]`이 올바르게 바인딩되지 않을 수 있지만, 실제로는 많이 발생하지 않습니다.
넵 원시 값이 더 자연스럽습니다.

2023-09-18 16:08 UTC, IMHOJEONG commented on files/ko/web/javascript/inheritance_and_the_prototype_chain/index.md
> +- `constructor` 속성을 수동으로 재설정하지 않는 한, `instance.contructor`에서 더 이상 생성자 함수를 추적할 수 없으므로 사용자의 기대를 깨뜨릴 수 있습니다. 일부 기본 제공 연산은 `constructor` 속성도 읽으며 설정되지 않은 경우, 예상대로 작동하지 않을 수 있습니다.
넵, `동작 방식을 예상하기 어렵다`로 해석을 변경하겠습니다! 너무 직역의 느낌은 최대한 지우려고 해야겠네요

2023-09-18 16:12 UTC, IMHOJEONG commented on files/ko/web/javascript/inheritance_and_the_prototype_chain/index.md
> +생성자 형태를 통해, "설탕을 제거"할 수 있습니다.
넵 동의합니다. 
저도 디슈가링을 잘 몰라서 찾아봤는데, 문법적 설탕과 관련된 의미라서 앞에 작성해 주는 게 더 명확해 보입니다!

2023-09-18 16:14 UTC, IMHOJEONG commented on files/ko/web/javascript/inheritance_and_the_prototype_chain/index.md
> +> 이러한 잘못된 기능을 원숭이 패칭(monkey patching)이라고 합니다. 원숭이 패칭을 하게 되면, 향후 호환성에 문제가 발생합니다. 언어가 나중에 이 메서드를 추가하지만 다른 서명을 사용하면, 코드가 깨질 수 있기 대문입니다. 이로 인해, [SmooshGate](https://developer.chrome.com/blog/smooshgate/)
이 부분은 @pje1740 님의 의견이 맞습니다!
상위 호환이 적합한 말이라, 수정하겠습니다.

2023-09-18 16:17 UTC, IMHOJEONG commented on files/ko/web/javascript/inheritance_and_the_prototype_chain/index.md
> +Function.prototype(); // Function.prototype is a no-op function by itself // Function.prototype은 자체로 프로그램에 아무 작업도 수행하지 말라고 지시(no-op(no-operation)) 함수입니다.
@pje1740 님 안녕하세요.
`(no-op(no-operation)) => (no-operation, no-op)` 의 수정방향은 어떠신가요?
현재 glossary 번역하면서, (전체 단어, 약어)의 순으로 번역하고 있어서 제안드려봅니다.

2023-09-18 16:19 UTC, IMHOJEONG commented on files/ko/web/javascript/inheritance_and_the_prototype_chain/index.md
> +최적의 실습을 위해, 콘솔을 열고 "console" 탭으로 이동하여 아래의 JavaScript 코드를 복사하여 붙여넣고, 엔터/Return 키를 눌러서 실행하는 것이 좋습니다(콘솔은 대부분 웹 브라우저의 개발자 도구에 포함되어 있습니다). 자세한 내용은 [Firefox Developer Tools](https://firefox-source-docs.moz
앗 그러네요  `참고하세요).` 처럼 마침표를 문장 끝에 찍어주려고 합니다!

2023-09-18 16:23 UTC, IMHOJEONG commented on files/ko/web/javascript/inheritance_and_the_prototype_chain/index.md
> +        객체 리터럴 초기자의 <code>__proto__</code>가 표준화되고 최적화되었으며 {{jsxref("Object.create")}}보다 성능이 더 뛰어날 수 있습니다. 객체 생성 시 추가 자체 속성을 선언하는 것이 {{jsxref("Object.create")}}보다 인체공학적입니다.
넵. 다시 읽어보니까 어색하네요
수정하겠습니다.

2023-09-18 16:26 UTC, IMHOJEONG commented on files/ko/web/javascript/inheritance_and_the_prototype_chain/index.md
> +{{jsxref("Object.create()")}}을 호출하면 새로운 객체가 생성됩니다. 이 객체의 `[[Prototype]]`은 함수의 첫 번째 인수입니다.
맞습니다. 추가하겠습니다.

2023-09-18 16:29 UTC, IMHOJEONG commented on files/ko/web/javascript/inheritance_and_the_prototype_chain/index.md
> +프로토타입 객체에 대한 참조는 새 인스턴스의 내부 `[[Prototype]]` 속성에 복사됩니다. 예를 들어, `const a1 = new A()`를 수행하면, JavaScript(메모리에 객체를 생성한 후 `this`가 정의된 함수 `A()`를 실행하기 전에)는 `a1.[[Prototype]] = A.prototype`을 설정합니다. 그런 다음 인스턴스
훨씬 깔끔합니다. 긴 문단 수정감사합니다.

2023-09-18 16:32 UTC, IMHOJEONG commented
@pje1740 님 안녕하세요!
매우 긴 글 읽고, 피드백 하시느라 고생하셨습니다!
저도 하나 의견 드린 게 있는 데, 그거 결정되면 다시 수정해서 반영하겠습니다! (나머지는 다 반영하였습니다)
번역 안 된 부분, 어색한 부분, 좋은 의견 제안 항상 감사합니다!

2023-09-18 23:59 UTC, pje1740 commented on files/ko/web/javascript/inheritance_and_the_prototype_chain/index.md
> +Function.prototype(); // Function.prototype is a no-op function by itself // Function.prototype은 자체로 프로그램에 아무 작업도 수행하지 말라고 지시(no-op(no-operation)) 함수입니다.
후자가 눈에 더 잘 들어오기도 해서 전 좋은 거 같습니다! 👍

2023-09-19 01:31 UTC, IMHOJEONG commented on files/ko/web/javascript/inheritance_and_the_prototype_chain/index.md
> +Function.prototype(); // Function.prototype is a no-op function by itself // Function.prototype은 자체로 프로그램에 아무 작업도 수행하지 말라고 지시(no-op(no-operation)) 함수입니다.
넵 그러면 위처럼 수정하겠습니다.

2023-09-19 01:40 UTC, IMHOJEONG commented
@pje1740 님 안녕하세요!
제가 실수로 닫아버려서 죄송합니다.
확인부탁드립니다.

2023-09-19 01:41 UTC, IMHOJEONG commented
다시 열었습니다.

2023-09-19 04:03 UTC, pje1740 commented
@IMHOJEONG 새로운 커밋이 0로 집계되어 있어서 reopen 버튼이 비활성화 상태인데요, 번거로우시다면 PR 다시 열어서 리뷰어 저 지정해주셔도 될 거 같습니다!

2023-09-19 04:19 UTC, IMHOJEONG commented
@pje1740 님 안녕하세요!
실수로 closed 해서 다 날아가서 ㅠㅠ 다시 피드백 반영해서 push 해두었습니다!
번거롭게 해드려 죄송합니다.

2023-09-19 12:13 UTC, pje1740 requested changes

2023-09-19 12:13 UTC, pje1740 commented on files/ko/web/javascript/inheritance_and_the_prototype_chain/index.md
> +## Constructors
아래의 `##생성자`와 중복인 거 같은데 맞을까요?

2023-09-20 09:57 UTC, pje1740 approved these changes
너무나 긴 글인데, 리뷰도 또 늦어져서 번거롭게 해드렸습니다! 너무 고생하셨습니다 🔥

2023-09-20 10:03 UTC, merged