ko: webassembly
mdn/translated-content pull request #15098
Opened 2023-08-14 07:42 UTC by KukHyunLim

webassembly 최신화 및 번역

### Description
webassembly문서 최신화 및 번역

### Motivation

### Additional details
- l18n추가
- 가이드 번역
- API 참조 최신화 및 번역
- 바깥고리 최신화

### Related issues and pull requests

#14968, #14965

2023-08-14 15:45 UTC, hochan222 requested changes
@KukHyunLim 님 안녕하세요.

고생 많으셨습니다. 리뷰 내용 아래에 남겨두었습니다.

기여해주셔서 감사합니다. 좋은 하루 보내세요 :)

2023-08-14 15:45 UTC, hochan222 commented on files/ko/webassembly/index.md
> +  sourceCommit: 8bed414e44172a31b1793fe845abdf72f5087ffb
올바른 hash가 들어가있지 않은듯합니다. content repo에서 동일한 파일의 최신 commit hash를 기입해주셔야합니다. (<https://github.com/mdn/content/commits/3c7e928f332191b153c40a6ade88fb5815c92b99/files/en-us/webassembly/index.md>)

[문서 갱신 표시 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md) 참고 부탁드립니다 :)

2023-08-16 00:57 UTC, KukHyunLim commented on files/ko/webassembly/index.md
> +  sourceCommit: 8bed414e44172a31b1793fe845abdf72f5087ffb
수정완료하였습니다.
문서 갱신 표시 안내서 다시 확인했습니다.

감사합니다!

2023-08-16 09:52 UTC, KukHyunLim reviewed
리뷰 전부 수정했습니다.

2023-08-19 10:37 UTC, hochan222 approved these changes
@KukHyunLim 님, 고생 많으셨습니다. 좋은 하루 보내세요 :)

2023-08-19 10:37 UTC, hochan222 commented on files/ko/webassembly/index.md
> +  sourceCommit: 0cfdd279edb09f70fbeb52c67ecc2876da5ce32d
👍👍

2023-08-19 10:37 UTC, merged