add : translation of typesetting a homepage in CSS styling text
mdn/translated-content pull request #15130
Opened 2023-08-15 15:37 UTC by ykss

### Description

번역되지 않은 [Typesetting a community school homepage](https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Typesetting_a_homepage#starting_point)에 대한 전체 번역입니다.

### Motivation

번역되지 않은 페이지여서 번역하였습니다.

### Additional details

### Related issues and pull requests

2023-09-09 16:39 UTC, hochan222 commented
@sunhpark42 님, 안녕하세요. 일주일내로 해당 PR 리뷰 계획이 있으시면 리뷰 일정 커멘트로 말씀 부탁드립니다. 리뷰 드리기 어려울듯하면 말씀해주세요~!

모두 좋은 주말 보내세요 :)

2023-09-20 08:09 UTC, wisedog commented
@hochan222  이 PR은 담당자가 바쁘신 관계로 제가 리뷰하겠습니다.

2023-09-20 08:09 UTC, wisedog requested changes
기여 감사합니다. 전반적으로 흠잡을 곳은 없습니다. 사소한 문구만 몇 개 수정 부탁드릴께요 : >

2023-09-20 08:09 UTC, wisedog commented on files/ko/learn/css/styling_text/typesetting_a_homepage/index.md
> +      <th scope="row">전제 조건:</th>
`필요한 사전 지식`이 맞겠습니다. 
참고 링크: https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md

2023-09-20 08:09 UTC, wisedog commented on files/ko/learn/css/styling_text/typesetting_a_homepage/index.md
> +> **참고:** 만약 문제가 해결되지 않으면, 이 페이지 하단의 [평가 및 추가적인 도움말](#assessment_or_further_help) 섹션을 참조하여 도움을 요청하세요.
북마크 업데이트가 필요합니다.

2023-09-20 08:09 UTC, wisedog commented on files/ko/learn/css/styling_text/typesetting_a_homepage/index.md
> +- _외부_ 링크 옆에 외부 링크 아이콘이 삽입되도록 설정하세요.
한국어는 기울임꼴을 쓰지 않습니다 :  >
참고 링크: https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md

2023-09-20 15:07 UTC, ykss commented
@wisedog 코멘트 주신 부분들 모두 반영하였습니다! 리뷰 감사합니다 👍

2023-09-20 22:35 UTC, wisedog approved these changes

2023-09-20 22:35 UTC, wisedog commented
고생하셨습니다. 감사합니다.

2023-09-20 22:35 UTC, merged