[ko] responsive design 원문에서 번역 안 된 부분 추가 및 오타 수정
mdn/translated-content pull request #15140
Opened 2023-08-16 04:58 UTC by 2kkeullim

### Description
`Responsive design` 파일의 전체적인 번역을 수정하였으며,
번역이 되어 있지 않은 영어 원문을 추가로 번역하고, 소스 커밋을 추가하였습니다.

### Motivation

### Additional details

### Related issues and pull requests

2023-08-19 10:33 UTC, hochan222 requested changes
@2kkeullim 님 안녕하세요.

대부분 잘 번역해주셔서 리뷰사항이 몇가지 없지만, 리뷰 내용 하기에 남겨두었습니다. 고생 많으셨습니다.

기여해주셔서 감사합니다. 좋은 하루 보내세요 :)

2023-08-19 10:33 UTC, hochan222 commented on files/ko/learn/css/css_layout/responsive_design/index.md
> +page-type: learn-module-chapter
```suggestion
```

[메타 데이터 사용 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md)에 따라 제거 부탁드립니다.

2023-08-19 10:33 UTC, hochan222 commented on files/ko/learn/css/css_layout/responsive_design/index.md
> +  sourceCommit: c51e0599ea09c0e6d035c635db9f48ad1f241490
👍👍

2023-08-19 10:33 UTC, hochan222 commented on files/ko/learn/css/css_layout/responsive_design/index.md
> +_반응형 웹 설계_ 는 웹 페이지가 모든 화면 크기와 해상도에서 잘 렌더링되도록 하면서도 사용성을 보장하는 웹 디자인 접근 방식입니다. 멀티 디바이스 웹을 위한 디자인 방식입니다. 이 글에서는 이를 마스터하는 데 사용할 수 있는 몇 가지 기법에 대해 설명합니다.
```suggestion
반응형 웹 설계 는 웹 페이지가 모든 화면 크기와 해상도에서 잘 렌더링되도록 하면서도 사용성을 보장하는 웹 디자인 접근 방식입니다. 멀티 디바이스 웹을 위한 디자인 방식입니다. 이 글에서는 이를 숙달하기 위해 사용할 수 있는 몇 가지 기술을 이해하는 데 도움이 될 것입니다.
```

(1)
한글은 기울임꼴에 적합하지 않습니다. 전용 이탤릭체가 없다는 것이 첫 이유이고, 문자의 조형이 (정)사각형인 것이 두 번째 이유입니다. 따라서 제거했습니다.

- [기울임꼴 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md)

(2) 
자연스럽게 수정했습니다.

2023-08-19 10:33 UTC, hochan222 commented on files/ko/learn/css/css_layout/responsive_design/index.md
>        <th scope="row">선결 사항:</th>
```suggestion
      <th scope="row">필요한 사전 지식:</th>
```

[안내 문구 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md)에 따라 수정 부탁드립니다.

2023-08-19 10:33 UTC, hochan222 commented on files/ko/learn/css/css_layout/responsive_design/index.md
> +HTML은 기본적으로 반응형, 즉 _fluid_ 입니다. CSS 없이 HTML만 포함된 웹 페이지를 만들고 창 크기를 조정하면 브라우저는 뷰포트에 맞게 텍스트를 자동으로 리플로우합니다.
```suggestion
HTML은 기본적으로 반응형 또는 유동적 입니다. CSS 없이 HTML만 포함된 웹 페이지를 만들고 창 크기를 조정하면 브라우저는 뷰포트에 맞게 텍스트를 자동으로 리플로우합니다.
```

2023-08-19 10:33 UTC, hochan222 commented on files/ko/learn/css/css_layout/responsive_design/index.md
> +반응형 웹 디자인은 별도의 기술이 아니라 하나의 접근 방식입니다. 콘텐츠를 보는 데 사용되는 모든 기기에 _대응_ 할 수 있는 레이아웃을 만드는 데 사용되는 일련의 모범 사례를 설명하는 데 사용되는 용어입니다.
```suggestion
반응형 웹 디자인은 별도의 기술이 아니라 하나의 접근 방식입니다. 콘텐츠를 보는 데 사용되는 모든 기기에 대응할 수 있는 레이아웃을 만드는 데 사용되는 일련의 모범 사례를 설명하는 데 사용되는 용어입니다.
```

2023-08-19 10:33 UTC, hochan222 commented on files/ko/learn/css/css_layout/responsive_design/index.md
> +_반응형 디자인_ 이라는 용어는 [2010년 Ethan Marcotte가 만든 것](https://alistapart.com/article/responsive-web-design/)으로, Zoe Mickley Gillenwater의 저서 [Flexible Web Design](http://flexiblewebbook.com/)에서 설명한 대로 유동 그리드
```suggestion
반응형 디자인_이라는 용어는 [2010년 Ethan Marcotte가 만든 것](https://alistapart.com/article/responsive-web-design/)으로, Zoe Mickley Gillenwater의 저서 [Flexible Web Design](http://flexiblewebbook.com/)에서 설명한 대로 유동 그리드, 유동 이미지, 미디어 쿼리를 사용하여 반응형 콘텐츠를 만드는 것을 설명합니다.
```

2023-08-19 10:33 UTC, hochan222 commented on files/ko/learn/css/css_layout/responsive_design/index.md
> +`<picture>` 요소를 사용하면 "hints"(이미지가 가장 적합한 화면 크기 및 해상도를 설명하는 메타데이터)와 함께 여러 크기를 제공할 수 있으며, 브라우저는 각 디바이스에 가장 적합한 이미지를 선택하므로 사용자가 사용 중인 디바이스에 적합한 이미지 크기를 다운로드할 수 있습니다. `max-width`와 함께 `<picture>`을 사용하면 미디
```suggestion
`<picture>` 요소를 사용하면 "hints"(이미지가 가장 적합한 화면 크기 및 해상도를 설명하는 메타데이터)와 함께 여러 크기를 제공할 수 있으며, 브라우저는 각 디바이스에 가장 적합한 이미지를 선택하므로 사용자가 사용 중인 디바이스에 적합한 이미지 크기를 다운로드할 수 있습니다. `max-width`와 함께 `<picture>`을 사용하면 미디어 쿼리로 이미지 크기를 조정할 필요가 없습니다. 이는 다른 화면비의 이미지를 다른 뷰포트 크기에 맞추어 사용할 수 있도록 합니다.
```

> It enables targeting images with different aspect ratios to different viewport sizes.

조금 더 자연스럽게 수정했습니다.

2023-08-19 10:33 UTC, hochan222 commented on files/ko/learn/css/css_layout/responsive_design/index.md
> +**따라서 문서 헤드에 뷰포트 메타 태그를 _항상_ 포함해야 합니다.**
```suggestion
**따라서 문서 헤드에 뷰포트 메타 태그를 항상 포함해야 합니다.**
```

2023-08-19 10:33 UTC, hochan222 commented on files/ko/learn/css/css_layout/responsive_design/index.md
> +## 참고
```suggestion
## 같이 보기
```

[단어 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md)에 따라 같이 보기로 수정 부탁드립니다.

2023-08-20 12:34 UTC, 2kkeullim commented
@hochan222 꼼꼼한 리뷰 감사합니다! 수정 완료하였습니다~!!

2023-08-28 13:24 UTC, hochan222 approved these changes
@2kkeullim 님, 안녕하세요.

고생 많으셨습니다. 좋은 하루 보내세요 :)

2023-08-28 13:24 UTC, merged