[revise]: revise for `web/javascript/event_loop`
mdn/translated-content pull request #15142
Opened 2023-08-16 09:05 UTC by IMHOJEONG

### Description

 - #15001 의 web/javascript/event_loop입니다. 

### Motivation

#14965 중에 최신화 & sourceCommit 추가하는 작업 진행중입니다.

### Additional details

이미 읽어보았을 때, 잘 되어있는 번역은 최대한 남겨두었습니다.
용어 안내집를 주로 참고해서 구성하였고, 없는 부분들은 읽어보았을 때 자연스러운 단어를 선택해서 번역하였습니다.

### Related issues and pull requests

#14965 
#15001

2023-08-28 11:54 UTC, pje1740 requested changes
이미지를 불러오는 부분은 링크 자체는 원문 그대로 두시되, 추가해주신 파일만 삭제해주시면 됩니다!
고생하셨습니다!

2023-08-28 11:54 UTC, pje1740 commented on files/ko/web/javascript/event_loop/index.md
> +[`setTimeout`](/ko/docs/Web/API/setTimeout) 함수는 두 개의 매개변수를 가집니다. 첫 번째는 큐에 추가할 메시지, 두 번째는 시간 값(선택 사항, 기본 값 `0`)입니다. 시간 값은 메시지를 큐에 추가하기까지 기다릴 (최소) 지연 시간을 나타냅니다. 큐에 다른 메시지가 없고 스택이 비어있다면 `setTimeout`의 메시
```suggestion
{{domxref("setTimeout")}} 함수는 두 개의 매개변수를 가집니다. 첫 번째는 큐에 추가할 메시지, 두 번째는 시간 값(선택 사항, 기본 값 `0`)입니다. 시간 값은 메시지를 큐에 추가하기까지 기다릴 (최소) 지연 시간을 나타냅니다. 큐에 다른 메시지가 없고 스택이 비어있다면 `setTimeout`의 메시지는 딜레이 직후 즉시 처리됩니다. 그러나, 다른 메시지가 존재한다면 `setTimeout`은 앞선 메시지의 처리를 기다려야 합니다. 그래서 두 번째 값은 정확한 지연시간이 아닌, '최소' 지연 시간만 나타냅니다.
```
domxref 는 원본 그대로 유지시켜도 ko 문서로 잘 연결됩니다! 원본이 저 형태라면 굳이 링크 형태로 변경하지 않으셔도 괜찮습니다 🙂

2023-08-28 12:31 UTC, IMHOJEONG commented on files/ko/web/javascript/event_loop/the_javascript_runtime_environment_example.svg
넵. 삭제하겠습니다

2023-08-30 10:59 UTC, pje1740 approved these changes
고생하셨습니다!

2023-08-30 10:59 UTC, merged