Feat: Edit [ko] document.location page
mdn/translated-content pull request #15170
Opened 2023-08-17 06:23 UTC by GyoHeon

### Description

Web -> api -> Document -> location 페이지를 번역했습니다.

### Motivation

### Additional details

원문 : https://developer.mozilla.org/en-US/docs/Web/API/Document/location

### Related issues and pull requests

2023-09-09 16:38 UTC, hochan222 requested changes
@GyoHeon 님 안녕하세요.

리뷰사항 하기에 남겨두었습니다.

고생 정말 많으셨습니다. 좋은 주말 보내세요 :)

2023-09-09 16:38 UTC, hochan222 commented on files/ko/web/api/document/location/index.md
> +`Document.location`은 _읽기 전용_ `Location` 객체지만, 문자열을 할당할 수도 있습니다. 즉, 대부분의 경우에 `document.location`을 문자열처럼 사용할 수 있습니다. `document.location = 'http://www.example.com'`은 `document.location.href = 'http://ww
```suggestion
`Document.location`은 읽기 전용 `Location` 객체지만, 문자열을 할당할 수도 있습니다. 즉, 대부분의 경우에 `document.location`을 문자열처럼 사용할 수 있습니다. `document.location = 'http://www.example.com'`은 `document.location.href = 'http://www.example.com'`와 동의어입니다. 만약 다른 문자열을 할당한다면 브라우저가 할당된 웹사이트를 로드합니다.
```

[기울임꼴 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md#%EA%B8%B0%EC%9A%B8%EC%9E%84%EA%BC%B4)에 따라 제거 부탁드립니다.

2023-09-10 08:52 UTC, GyoHeon commented on files/ko/web/api/document/location/index.md
> +`Document.location`은 _읽기 전용_ `Location` 객체지만, 문자열을 할당할 수도 있습니다. 즉, 대부분의 경우에 `document.location`을 문자열처럼 사용할 수 있습니다. `document.location = 'http://www.example.com'`은 `document.location.href = 'http://ww
@hochan222 안녕하세요.

리뷰사항 반영하여 수정완료하였습니다.

감사합니다!

2023-09-17 08:35 UTC, hochan222 approved these changes
@GyoHeon 님 고생 많으셨습니다~!

좋은 주말 보내세요 :)

2023-09-17 08:40 UTC, hochan222 requested changes
@GyoHeon 님 충돌해결 한번만 부탁드립니다~!

2023-09-18 05:34 UTC, closed without merging