[ko] update translation to vibration api in Web API
mdn/translated-content pull request #15262
Opened 2023-08-19 10:04 UTC by ykss

### Description

바이브레이션 API를 최신 상태를 반영하여 업데이트 하고, 어투 등을 수정하였습니다.
특이사항 없습니다.

### Motivation

### Additional details

### Related issues and pull requests

2023-09-04 13:29 UTC, yechoi42 requested changes
안녕하세요! 기여 감사합니다. 원문과 비교했을 때 다른 부분이 있어 의견 남겨두었습니다. 수정 후 저를 다시 멘션하거나 제게 다시 리뷰 요청주세요.

2023-09-04 13:29 UTC, yechoi42 commented on files/ko/web/api/vibration_api/index.md
> +바이브레이션은 다양한 길이의 온·오프 펄스의 패턴이라고 할 수 있습니다. 패턴은 진동 시간(밀리초)을 나타내는 단일 정수로 구성되거나 진동 및 일시 정지 패턴을 나타내는 정수의 배열로 구성될 수 있습니다. 진동은 {{domxref("window.navigator.vibrate()")}} 라는 단일 메서드로 제어됩니다.
```suggestion
바이브레이션은 다양한 길이의 온·오프 펄스의 패턴이라고 할 수 있습니다. 패턴은 진동 시간(밀리초)을 나타내는 단일 정수로 구성되거나 진동 및 일시 정지 패턴을 나타내는 정수의 배열로 구성될 수 있습니다. 진동은 {{DOMxRef("Navigator.vibrate()")}} 라는 단일 메서드로 제어됩니다.
```

2023-09-04 13:29 UTC, yechoi42 commented on files/ko/web/api/vibration_api/index.md
> +진동/정지 쌍을 원하는 만큼 지정할 수 있습니다. 그리고 배열 내에 홀수 개 또는 짝수 개로 입력할 수 있습니다. 이렇게 하는 이유는 각각의 진동 시간이 끝나면 디바이스의 진동은 자동으로 멈추게 되므로 배열의 마지막 값이 정지에 해당하는 값이라면 그 값은 아무 의미가 없기 때문입니다.
```suggestion
진동/정지 쌍을 원하는 만큼 지정할 수 있습니다. 그리고 배열 내에 홀수 개 또는 짝수 개로 입력할 수 있습니다. 각 진동 주기가 끝날 때마다 진동이 자동으로 중지되므로 마지막 항목으로 일시 정지를 제공할 필요가 없습니다.
```
원문과 의미가 다릅니다.

2023-09-04 13:29 UTC, yechoi42 commented on files/ko/web/api/vibration_api/index.md
> +{{domxref("window.navigator.vibrate()")}} 메서드를 0 값을 호출하거나, 빈 배열, 0 값으로 구성된 배열로 호출하면 현재 진행 중인 진동 패턴은 모두 취소됩니다.
```suggestion
{{DOMxRef("Navigator.vibrate()")}} 메서드를 0 값을 호출하거나, 빈 배열, 0 값으로 구성된 배열로 호출하면 현재 진행 중인 진동 패턴은 모두 취소됩니다.
```

2023-09-04 13:29 UTC, yechoi42 commented on files/ko/web/api/vibration_api/index.md
>  }
```suggestion
function startPersistentVibrate(duration, interval) {
  vibrateInterval = setInterval(() => {
    startVibrate(duration);
  }, interval);
}
```

2023-09-04 14:41 UTC, ykss commented
@yechoi42 꼼꼼히 리뷰해주셔서 감사합니다! 아예 전체번역을 다시했어야 하는데, 기존 번역을 고치면서 영문 번역을 참조하다보니, 놓친 부분들이 있었던 것 같습니다!! 👍

2023-09-16 14:54 UTC, yechoi42 approved these changes
기여 감사합니다 :)

2023-09-16 14:54 UTC, merged