[ko] Mobile accessibility checklist를 번역했습니다.
mdn/translated-content pull request #15275
Opened 2023-08-19 15:56 UTC by msdio

### Description
mobile_accessibility_checklist 를 번역했습니다.

기존 파일에 비해서 몇 가지 변경사항이 있습니다.
- ARIA Role에 링크로 걸려있던 주소가 유효하지 않아, 원문에 있는 링크와 동일한 링크로 대체하였습니다.
- 기존 어투가 `~다` 로 작업되어 있어, `~니다` 체로 변경했습니다.
- 22 line의 `진짜로`와 `카드`는 [기울임꼴 번역 가이드](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md#%EA%B8%B0%EC%9A%B8%EC%9E%84%EA%BC%B4)에 따라 쌍따옴표로 작업했습니다.

### Questions
- Focus가 `초점`으로 번역되어 있었는데, 잘 와닿지 않는다고 판단해서 `포커스`로 작업해놓았습니다. `초점`이 더 적절할지 의견 부탁드립니다.
- 31번 라인의 control을 어떻게 번역하는것이 적절할지 몰라 우선 영어 그대로 놔두었습니다. 적절한 표현이 있다면 의견 부탁드립니다.

### Related issues and pull requests
- 레거시 파일 업데이트 (https://github.com/mdn/translated-content/issues/14968) 작업입니다.

2023-09-09 16:21 UTC, hochan222 requested changes
@msdio 님 안녕하세요.

리뷰사항 하기에 남겨두었습니다. 

고생 많으셨습니다. 좋은 주말 보내세요 :)

2023-09-09 16:21 UTC, hochan222 commented on files/ko/web/accessibility/mobile_accessibility_checklist/index.md
> +  - _alt_ 와 _title_ 속성은 적절하게 사용되어야 합니다 (스티브 폴크너의 [HTML의 제목 특성 사용하기](http://blog.paciellogroup.com/2013/01/using-the-html-title-attribute-updated/) 가 좋은 가이드가 될 것입니다).
```suggestion
  - _alt_ 와 _title_ 속성은 적절하게 사용되어야 합니다 (스티브 폴크너의 [HTML의 제목 특성 사용하기](http://blog.paciellogroup.com/2013/01/using-the-html-title-attribute-updated/) 가 좋은 안내서가 될 것입니다).
```
[단어 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md)에 따라 안내서로 변경 부탁드립니다 :)

2023-09-09 16:21 UTC, hochan222 commented on files/ko/web/accessibility/mobile_accessibility_checklist/index.md
> +  - 위 속성을 사용하기 어려운 경우 `aria-label`, `aria-labelledby`, or `aria-describedby` 등과 같은 적절한 [ARIA 속성들](http://www.w3.org/WAI/PF/aria/states_and_properties#global_states_header) 을 사용하세요.
```suggestion
  - 위 속성을 사용하기 어려운 경우 `aria-label`, `aria-labelledby`, or `aria-describedby` 등과 같은 적절한 [ARIA 속성들](http://www.w3.org/WAI/PF/aria/states_and_properties#global_states_header)을 사용하세요.
```

2023-09-09 16:21 UTC, hochan222 commented on files/ko/web/accessibility/mobile_accessibility_checklist/index.md
> +  - 비표준 control들은 반드시 `버튼`, `링크` 또는 `체크박스`와 같은 적절한 [ARIA Role](/ko/docs/Web/Accessibility/ARIA/Roles) 이 할당되어야 합니다.
```suggestion
  - 비표준 control들은 반드시 `button`, `link` 또는 `checkbox`와 같은 적절한 [ARIA Role](/ko/docs/Web/Accessibility/ARIA/Roles) 이 할당되어야 합니다.
```

원문의 인라인 코드는 번역하지 않습니다. 수정 부탁드립니다 :)

[inline code 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md#inline-code)

2023-09-09 16:21 UTC, hochan222 commented on files/ko/web/accessibility/mobile_accessibility_checklist/index.md
> +  - 링크, 버튼 및 form 필드와 같은 표준 control들은 기본적으로 포커스가 가능합니다.
> 31번 라인의 control을 어떻게 번역하는것이 적절할지 몰라 우선 영어 그대로 놔두었습니다. 적절한 표현이 있다면 의견 부탁드립니다.

개인적으로는 2번을 선택했을것같은데, 1번도 좋습니다.

(1) 
```suggestion
  - 링크, 버튼 및 form 필드와 같은 표준 컨트롤들은 기본적으로 포커스가 가능합니다.
```

(2)
```suggestion
  - 링크, 버튼 및 form 필드와 같은 표준 제어들은 기본적으로 포커스가 가능합니다.
```

2023-09-09 16:21 UTC, hochan222 commented on files/ko/web/accessibility/mobile_accessibility_checklist/index.md
> +## 포커스
> Focus가 초점으로 번역되어 있었는데, 잘 와닿지 않는다고 판단해서 포커스로 작업해놓았습니다. 초점이 더 적절할지 의견 부탁드립니다.

고유 단어로 사용되고 있기 때문에 포커스가 더 올바른 번역이라고 생각합니다.

2023-09-10 03:48 UTC, msdio commented on files/ko/web/accessibility/mobile_accessibility_checklist/index.md
> +  - 링크, 버튼 및 form 필드와 같은 표준 control들은 기본적으로 포커스가 가능합니다.
2번은 의미가 명확하게 전달되지 않는 것 같아서, 1번으로 작업하겠습니다. 추후에 용어에 대한 규칙이 정해진다면 수정하겠습니다!

2023-09-10 03:49 UTC, msdio commented on files/ko/web/accessibility/mobile_accessibility_checklist/index.md
> +  - 링크, 버튼 및 form 필드와 같은 표준 control들은 기본적으로 포커스가 가능합니다.
아래는 의미가 명확하지 않은 것 같아, 1번으로 작업하겠습니다. 추후에 용어에 대한 규칙이 생긴다면 변경하겠습니다!

2023-09-10 03:52 UTC, msdio commented
@hochan222 리뷰 감사합니다. 수정했으니 확인 부탁드립니다 :)

2023-09-17 07:05 UTC, hochan222 approved these changes
고생 많으셨습니다. 좋은 주말 보내세요 :)

2023-09-17 07:05 UTC, merged