[ko]: revise files for `web/glossary-c`
mdn/translated-content pull request #15293
Opened 2023-08-20 07:42 UTC by IMHOJEONG

### Description

#15221  의 진행상황 중, web/glossary/c 부분의 일부분 파일들입니다.

### Motivation

web/glossary 접근했는데, 한국어 파일은 없어서 시작하게 되었습니다.

### Additional details

여러 단어들이 추가된 경우도 많아서, 추가된 파일의 경우는 새로운 PR를 만들어서 번역 PR를 남기도록 하겠습니다.

attribute의 경우, "attribute reflection"이 추가되어 번역 부분을 추가했습니다.

### Related issues and pull requests

#14965 
#15221

2023-08-20 23:21 UTC, wisedog commented
오... 선생님 22개나..😭

2023-08-21 01:34 UTC, IMHOJEONG commented
@wisedog 님 안녕하세요.
 `web/glossary` 부분의 사소한(?) 변경이라서 30개 이하의 커밋을 한꺼번에 올리게 되었습니다. ㅠㅠ

2023-08-22 13:27 UTC, wisedog requested changes
많은 문서를 번역했는데, 의외로 문제된 부분이 별로 없었습니다! 

딱 2~3군데만 수정부탁드립니다.

2023-08-22 13:27 UTC, wisedog commented on files/ko/glossary/cors/index.md
> +- [교차 출처 리소스 공유 (CORS)](/en-US/docs/Web/HTTP/CORS) on MDN
요고 빠졌네요. `/ko`

2023-08-22 13:51 UTC, IMHOJEONG commented on files/ko/glossary/cors/index.md
> +- [교차 출처 리소스 공유 (CORS)](/en-US/docs/Web/HTTP/CORS) on MDN
감사합니다!

2023-08-22 13:52 UTC, IMHOJEONG commented on files/ko/glossary/css_preprocessor/index.md
> +선택할 수 있는 많은 CSS 전처기가 있지만, 대부분의 CSS 전처리기는 pure CSS에 존재하지 않는 특징(믹스인(mixin), 중첩 셀렉터(nesting selector), 상속 셀렉터(inheritance selector), 기타 등)을 추가할 것 입니다, 이러한 특징은 CSS 구조를 가독성있고 더 유지보수 하기 좋게 합니다.
기본 css로 번역하는 게 나아보입니다.

2023-08-22 13:55 UTC, IMHOJEONG commented on files/ko/glossary/css_preprocessor/index.md
> +CSS 전처리기를 사용하기 위해서는, 당신의 웹 {{Glossary("server")}}에 CSS compiler를 설치해야 한다. 또는 CSS 전처리기를 사용하여 개발환경에서 컴파일한 다음, 컴파일된 CSS 파일을 웹 서버에 업로드합니다.
앗 ㅠㅠ  CSS 전처리기 사용하기 위해서라는 말이 중복되네요 ㅠㅠ

`CSS 전처리기를 사용하기 위해서는, 당신의 웹 {{Glossary("server")}}에 CSS 컴파일러를 설치해야 하거나, 개발환경에서 컴파일한 후 컴파일된 CSS 파일을 웹 서버에 업로드합니다.`로 수정해서 번역하려 합니다.
이건 어떠실까요?

2023-08-22 13:57 UTC, wisedog commented on files/ko/glossary/css_preprocessor/index.md
> +선택할 수 있는 많은 CSS 전처기가 있지만, 대부분의 CSS 전처리기는 pure CSS에 존재하지 않는 특징(믹스인(mixin), 중첩 셀렉터(nesting selector), 상속 셀렉터(inheritance selector), 기타 등)을 추가할 것 입니다, 이러한 특징은 CSS 구조를 가독성있고 더 유지보수 하기 좋게 합니다.
넵 좋습니다.

2023-08-22 14:15 UTC, IMHOJEONG commented
@wisedog  님 안녕하세요.
위에서 주신 피드백 반영해서 다시 commit 올렸습니다.
늦은 시간에 피드백 감사합니다.

2023-08-22 14:29 UTC, wisedog approved these changes

2023-08-22 14:29 UTC, merged