[ko] translate Fundamental Layout Comprehension
mdn/translated-content pull request #15294
Opened 2023-08-20 07:43 UTC by C0012S

### Description
- `Fundamental Layout Comprehension` 한글 번역 페이지가 존재하지 않아 `fundamental_layout_comprehension/index.md`를 생성하고 번역했습니다.
  <img width="601" alt="image" src="https://github.com/mdn/translated-content/assets/66476874/e4de1520-6ba2-4db5-a89a-ae82e3e2a6c3">
  - [ko Fundamental Layout Comprehension MDN Link](https://developer.mozilla.org/ko/docs/Learn/CSS/CSS_layout/Fundamental_Layout_Comprehension)

<br/>

- 파일 전체 번역
  - 제목 번역
    - [CSS 레이아웃](https://developer.mozilla.org/ko/docs/Learn/CSS/CSS_layout)에 작성되어 있는 제목으로 번역했습니다.
  - 내용 번역
    - [용어 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md)를 참고하고 번역했으나 포함되어 있지 않은 용어는 번역하지 않고 그대로 뒀습니다.
      - 번역된 용어
        - Flexbox → 플렉스박스
        - Grid → 그리드
      - 번역되지 않은 용어
        - Floating
        - Positioning

<br/>
<br/>

### Motivation
`Fundamental Layout Comprehension` 페이지 번역에 기여하고 싶어서 작업했습니다.

### Additional details

### Related issues and pull requests

2023-09-09 16:57 UTC, hochan222 commented
@jho2301 님, 안녕하세요. 일주일내로 현재 PR 리뷰 계획이 있으시면 리뷰 일정 커멘트로 말씀 부탁드립니다. 리뷰 드리기 어려울듯하면 말씀해주세요~!

모두 좋은 주말 보내세요 :)

2023-09-18 16:29 UTC, jho2301 requested changes
안녕하세요 수정할 사항 코멘트로 남겼습니다 확인 한 번 부탁드려요

2023-09-18 16:29 UTC, jho2301 commented on files/ko/learn/css/css_layout/fundamental_layout_comprehension/index.md
> +이 과정을 학습했다면 현재 CSS 레이아웃을 만들고 이전 CSS로 작업하기 위해 알아야 할 기본 사항을 이미 다루었을 것입니다. 이 작업에서는 다양한 기법을 사용하여 간단한 웹 페이지 레이아웃을 개발하는 방식으로 지식을 테스트할 것입니다.
해당 문서에서 task는 과제로 해석되는것이 보다 자연스러워 보입니다

2023-09-18 16:29 UTC, jho2301 commented on files/ko/learn/css/css_layout/fundamental_layout_comprehension/index.md
> +원시 HTML, 기본 CSS 및 이미지가 제공되었으므로 이제 디자인을 위한 레이아웃을 만들어야 합니다.
```suggestion
가공되지 않은 HTML, 기본 CSS 및 이미지가 제공되었으므로 이제 디자인을 위한 레이아웃을 만들어야 합니다.
```

2023-09-18 16:29 UTC, jho2301 commented on files/ko/learn/css/css_layout/fundamental_layout_comprehension/index.md
> +        플렉스박스, 그리드, Floating, 그리고 Positioning을 사용하는 CSS 레이아웃 메서드에 대한 이해도를 테스트합니다.
```suggestion
        플렉스박스, 그리드, 플로팅, 그리고 포지셔닝을 사용하는 CSS 레이아웃 메서드에 대한 이해도를 테스트합니다.
```

2023-09-18 16:29 UTC, jho2301 commented on files/ko/learn/css/css_layout/fundamental_layout_comprehension/index.md
> +2. navigation bar가 콘텐츠와 함께 스크롤되다가 콘텐츠에 도달하면 뷰포트 상단에 고정되도록 합니다.
```suggestion
1. 내비게이션 항목을 항목 사이에 동일한 간격으로 일렬로 표시합니다.
2. 내비게이션 바가 콘텐츠와 함께 스크롤되다가 콘텐츠에 도달하면 뷰포트 상단에 고정되도록 합니다.
```

2024-07-29 16:56 UTC, merged

2024-07-29 16:56 UTC, hochan222 commented
@C0012S 님 안녕하세요.

PR기간이 많이 지나, 리뷰어께서 리뷰주신 사항 반영 후 병합하겠습니다.

기여해주셔서 정말 감사드립니다. 좋은 하루 보내세요 :)