[ko] translate `/learn/javascript/first_steps/variables/index.md`
mdn/translated-content pull request #15297
Opened 2023-08-20 08:41 UTC by Chaerim0626

### Description
🧩 `variables` 페이지가 한글로 존재하나, 3년 전 파일이라 전체적으로 새로 번역하였습니다. 원문과 다른 부분 전체 번역, 존대 통일, 기여 가이드라인을 통한 전체 번역 등을 진행하였습니다.
원문 MDN 링크: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Variables

### Motivation
💡 `variables` 페이지 번역에 기여하고 싶어서 작업하였습니다. JavaScript에서 변수는 매우 중요한 부분이라고 생각하여, 배우고자 하시는 분들이 좀 더 편리하고 쉽게 변수에 대해 학습하실 수 있기를 희망합니다.

### Additional details

### Related issues and pull requests

2023-09-09 17:07 UTC, hochan222 commented
@sunhpark42 님, 안녕하세요. 일주일내로 현재 PR 리뷰 계획이 있으시면 리뷰 일정 커멘트로 말씀 부탁드립니다. 리뷰 드리기 어려울듯하면 말씀해주세요~!

모두 좋은 주말 보내세요 :)

2023-09-24 04:45 UTC, wisedog commented
이것도 제가 하겠습니다. @hochan222

2023-09-24 05:02 UTC, wisedog requested changes
기여 감사합니다. 수정 요청한 내용도 있고, 같이 논의를 해볼만한 의견도 남겼으니 답변 부탁드립니다.

2023-09-24 05:02 UTC, wisedog commented on files/ko/learn/javascript/first_steps/variables/index.md
> +- 안전한 명명법은 소위 [소문자 camel case](https://en.wikipedia.org/wiki/CamelCase#Variations_and_synonyms)입니다. 여러 단어를 함께 붙일 때 첫 단어 전체에 소문자를 사용하고 그다음 단어는 대문자로 시작합니다. 지금까지 이 문서에서 변수 이름에 이 방식을 사용했습니다.
최신 커밋은 이 부분이 
`{{Glossary("camel_case", "lower camel case")}`
으로 변경되었습니다ㅏ.

2024-03-27 08:18 UTC, wisedog approved these changes

2024-03-27 08:19 UTC, merged