[ko] update translation to permission api in Web API
mdn/translated-content pull request #15312
Opened 2023-08-21 14:04 UTC by ykss

### Description

번역이 되어있지 않은 페이지를 전체 번역 진행했습니다.
특이 사항은 없습니다.

### Motivation

### Additional details

### Related issues and pull requests

2023-09-17 11:20 UTC, hochan222 commented
@ykss 님 안녕하세요. 

리뷰어 개인적인 사정으로 다른 리뷰어가 배정되어 리뷰가 지연되어도 양해 부탁드립니다.

@wisedog 님, 현재 PR 리뷰 부탁드립니다! 

모두 좋은 주말 보내세요 :)

2023-09-18 06:16 UTC, wisedog requested changes
3주 전에 한 번 업데이트가 되었습니다. 이 부분은 리뷰를 늦게 드려서 발생하게 된 점 굉장히 죄송스럽게 생각합니다. 

개선 요청 몇 개만 수정되면 바로 머지하도록 하겠습니다.

(참고: @hochan222 )

2023-09-18 06:16 UTC, wisedog commented on files/ko/web/api/permissions_api/index.md
> +- {{DOMxRef("Notification.permission")}}
`381c51574a3e6a07ee09c63493452440f046038d` 커밋에서 이 부분이 변경되었네요. 
`- {{DOMxref("Notification.permission_static", "Notification.permission")}}`

2023-09-18 06:16 UTC, wisedog commented on files/ko/web/api/permissions_api/index.md
> +`permissions` 속성은 표준 브라우징 맥락과 작업자 맥락(WorkerNavigator - 작업자 내부에서 권한 확인이 가능) 모두에서 {{domxref("Navigator")}} 객체에서 사용할 수 있게 되었으며, Permissions API 기능에 대한 접근을 제공하는 {{domxref("Permissions")}} 객체를 반환합니다.
`({{domxref("WorkerNavigator")}}` 부분이 빠져있습니다.

2023-09-18 06:16 UTC, wisedog commented on files/ko/web/api/permissions_api/index.md
> +이 객체가 있으면, {{domxref("Permissions.query()")}} 메서드를 사용하여 권한을 조회하여, 특정 API에 대한 {{domxref("PermissionStatus")}}로 확인되는 프로미스를 반환하는 등 권한 관련 작업을 수행할 수 있습니다. for a specific API.
`for a specific API.` 🥹

2023-09-18 07:18 UTC, ykss commented
@wisedog 꼼꼼히 리뷰해주셔서 너무 감사합니다! 피드백 주신 사항 모두 반영하였습니다 👍

2023-09-18 08:39 UTC, wisedog approved these changes
감사합니다!

2023-09-18 08:39 UTC, merged