존댓말 수정, : 수정, 오타 수정
mdn/translated-content pull request #15342
Opened 2023-08-23 06:18 UTC by BORA040126

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-08-23 08:57 UTC, wisedog commented
@BORA040126 안녕하세요. 기여 감사합니다. 다만 이 문서가 굉장히 옛날 문서라서 존댓말과 오타 수정 기여가 큰 의미가 없을 것 같습니다. 혹시 페이지 전체 번역을 해주실 수 있으실까요?

2023-08-23 08:59 UTC, BORA040126 commented
알겠습니다!

On Wed, Aug 23, 2023, 5:58 PM Jongha Kim ***@***.***> wrote:

> @BORA040126 <https://github.com/BORA040126> 안녕하세요. 기여 감사합니다. 다만 이 문서가 굉장히
> 옛날 문서라서 존댓말과 오타 수정 기여가 큰 의미가 없을 것 같습니다. 혹시 페이지 전체 번역을 해주실 수 있으실까요?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mdn/translated-content/pull/15342#issuecomment-1689561663>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVEOQBL7FSZPN7ASCAW4V6TXWXAZRANCNFSM6AAAAAA326DI4A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-28 15:30 UTC, hochan222 approved these changes
.

2023-08-29 00:45 UTC, hochan222 requested changes

2023-08-29 00:45 UTC, hochan222 commented on files/ko/learn/css/css_layout/responsive_design/index.md
> +**반응형 웹 디자인은 별도의 기술이 아니다**라는 것을 이해하는 것이 중요합니다. 즉, 웹 디자인에 대한 접근 방식이나 콘텐츠를 보는데 사용되는 장치에 *반응*할 수 있는 레이아웃 생성에 사용되는 모범 사례 집합을 기술하는 데 사용되는 용어입니다. 마르코트의 원래 연구에서 이것은 (부동체를 사용하는) 가변 격자와 미디어 쿼리를 의미했지만, 그의 문서가
```suggestion
**반응형 웹 디자인은 별도의 기술이 아니다**라는 것을 이해하는 것이 중요합니다. 즉, 웹 디자인에 대한 접근 방식이나 콘텐츠를 보는데 사용되는 장치에 *반응*할 수 있는 레이아웃 생성에 사용되는 모범 사례 집합을 기술하는 데 사용되는 용어입니다. 마르코트의 원래 연구에서 이것은 (부동체를 사용하는) 가변 격자와 미디어 쿼리를 의미했지만, 그의 문서가 쓰여진지 거의 10년 만에 반응형으로 동작하는 것이 기본값이 되었습니다. 현대의 CSS 레이아웃 메서드는 본질적으로 반응형이며 반응형 사이트 설계를 쉽게하기 위해 웹 플랫폼에 새로운 요소들이 내장되어 있습니다.
```

2023-08-29 00:45 UTC, hochan222 commented on files/ko/learn/css/css_layout/responsive_design/index.md
> +미디어 쿼리를 사용할 때 일반적인 접근법은 좁은 화면 장치(예: 휴대폰)에 대한 간단한 단일 열 레이아웃을 만든 다음, 큰 화면인지 점검하고, 화면 폭이 충분하다는 것을 알게 될 때 다단 레이아웃을 구현하는 것이다. 이를 **모바일 우선** 디자인이라고 표현하는 경우가 많습니니다.
```suggestion
미디어 쿼리를 사용할 때 일반적인 접근법은 좁은 화면 장치(예: 휴대폰)에 대한 간단한 단일 열 레이아웃을 만든 다음, 큰 화면인지 점검하고, 화면 폭이 충분하다는 것을 알게 될 때 다단 레이아웃을 구현하는 것이다. 이를 **모바일 우선** 디자인이라고 표현하는 경우가 많습니다.
```

2023-08-29 00:45 UTC, hochan222 commented on files/ko/learn/css/css_layout/responsive_design/index.md
> +해결책이 하나 있습니다. [`calc()`](/ko/docs/Web/CSS/calc)를 사용하는 것입니다. 즉, `em`와 같은 고정된 크기를 사용하여 속성값 집합에 `vw` 단위를 추가하면 텍스트는 여전히 확대/축소할 수 있습니다. 본질적으로 `vw` 단위는 확대/축소 값에 더해 추가됩니니다.
```suggestion
해결책이 하나 있습니다. [`calc()`](/ko/docs/Web/CSS/calc)를 사용하는 것입니다. 즉, `em`와 같은 고정된 크기를 사용하여 속성값 집합에 `vw` 단위를 추가하면 텍스트는 여전히 확대/축소할 수 있습니다. 본질적으로 `vw` 단위는 확대/축소 값에 더해 추가됩니다.
```

2023-08-29 00:52 UTC, wisedog commented
@hochan222 문서가 너무 달라져서 일부 존댓말 수정에 의미가 있는지 모르겠습니다. 🤔

2023-08-29 00:53 UTC, hochan222 commented
@BORA040126 님, 안녕하세요.

PR이 지연되고 있어서, 현재 PR 번역 금주내로 어려울듯하여 말씀부탁드립니다.

또한, @wisedog 님께서 말씀해주신것과 같이 현재 페이지는 원본 페이지와 비교하여 레거시로 남아있습니다.

현재 한국 문서는 [content 저장소](https://github.com/mdn/content)의 en-us 문서를 기반으로 번역이 되고 있습니다. 시간이 지남에 따라 문서가 최신 내용으로 갱신되지 못하고 영어 본문이 그대로 한국 문서에 남는 경우가 발생했습니다. 추후 번역 시에는 en-us 문서를 기반으로 기여주시면 최신 내용 반영이 될 수 있어서 조금 더 좋을듯합니다. 참고차, 관련하여 https://github.com/mdn/translated-content/issues/14965 이슈 진행하고 있습니다.

2023-08-29 01:25 UTC, hochan222 commented
> @hochan222 문서가 너무 달라져서 일부 존댓말 수정에 의미가 있는지 모르겠습니다. 🤔

@wisedog 님, 현재 문서 또한 mdn에 노출되고 있기에 최신화와 차이가 심해 추후 참고가 되지 못할정도라면 현재 페이지가 제거되는 것이 올바른 방향이라고 생각합니다..!

2023-08-29 01:34 UTC, wisedog commented
> > @hochan222 문서가 너무 달라져서 일부 존댓말 수정에 의미가 있는지 모르겠습니다. 🤔
> 
> @wisedog 님, 현재 문서 또한 mdn에 노출되고 있기에 최신화와 차이가 심해 추후 참고가 되지 못할정도라면 현재 페이지가 제거되는 것이 올바른 방향이라고 생각합니다..!

호찬님이 그렇게 생각하신다면 이 페이지는 제거하지 마시고 해당 PR은 유효한 PR로 간주하고 진행하면 되겠습니다 😄

2023-09-01 01:25 UTC, 2kkeullim commented
@BORA040126 님 안녕하세요.
해당 문서에 대한 최신화를 제가 맡아 진행하였으며,
4일 전에 pr이 merge 되었으니 참고 바랍니다.

#15140

2023-09-01 01:28 UTC, closed without merging