[ko] translate `strings`
mdn/translated-content pull request #15368
Opened 2023-08-24 14:00 UTC by wogha95

### Description

- 원문과 비교하여 누락된 부분 추가

### Motivation

- 오픈소스 컨트리뷰션 아카데미

### Additional details

### Related issues and pull requests

2023-09-16 00:00 UTC, wogha95 commented
@hochan222 
안녕하세요, hochan님.
현재 PR이 3주 이상 방치되고 있어서 멘션해드립니다.

2023-09-20 08:28 UTC, wisedog commented
> @hochan222 안녕하세요, hochan님. 현재 PR이 3주 이상 방치되고 있어서 멘션해드립니다.

@hochan222  이것도 제가...

2023-09-20 08:29 UTC, wisedog requested changes
기여 감사합니다! 리뷰어 개인 사정상 리뷰가 늦어진 점 정말 죄송합니다. 
몇 가지 수정 사항을 남겼으니 확인 부탁드립니다.

2023-09-20 08:29 UTC, wisedog commented on files/ko/learn/javascript/first_steps/strings/index.md
> +단어는 인간이 커뮤니케이션 함에 있어 커다란 하나의 부분이라고 할 수 있기에 매우 중요합니다. 웹은 사람들이 정보를 교환하고 공유할 수 있도록 설계된 텍스트 기반의 매체이므로, 웹에 표시되는 단어를 제어하는 것이 유용합니다. {{glossary ( "HTML")}}은 텍스트에 구조와 의미를 부여하고, {{glossary ( "CSS")}}는 텍스트의 스타
기왕 하신 김에
`{{glossary ( "HTML")}}` 를 `{{glossary("HTML")}}` 로 해주시면 좋구요.  
`{{glossary ( "CSS")}}`도 마찬가지..

2023-09-20 08:29 UTC, wisedog commented on files/ko/learn/javascript/first_steps/strings/index.md
>  ## 문자열 — 기초
`##Declaring strings` 이라서 `문자열 선언하기` 가 맞지 않을까 합니다.

2023-09-20 08:29 UTC, wisedog commented on files/ko/learn/javascript/first_steps/strings/index.md
> +JavaScript에서는 작은따옴표(`'`), 큰따옴표(`"`) 또는 백틱(`` ` ``)을 선택하여 문자열을 래핑할 수 있습니다. 다음 모두 사용할 수 있습니다.
제목의 `single quote`와 여기가 다르게 번역되어 있습니다. 확인 부탁드리겠습니다. 

또한 `래핑`이라는 말을 그대로 쓰는 것보다는 감싼다는 표현을 쓰시는게 어떨까요?

2023-09-20 08:29 UTC, wisedog commented on files/ko/learn/javascript/first_steps/strings/index.md
아래 번역 부분이 빠진듯 합니다. 
```
- you can [embed JavaScript](#embedding_javascript) in them
- you can declare template literals over [multiple lines](#multiline_strings)
```

2023-09-20 08:29 UTC, wisedog commented on files/ko/learn/javascript/first_steps/strings/index.md
> +지금까지 자바스크립트에서 다루는 문자열의 기본에 대해 알아봤습니다. 다음 글에서는 이를 바탕으로 자바스크립트에서 문자열에 사용할 수 있는 몇 가지 기본 제공 메서드와 이를 사용하여 문자열을 원하는 형태로 조작하는 방법을 살펴보겠습니다.
자바스크립트 -> JavaScript

참고 링크: https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md#%EA%B3%B5%ED%86%B5

2023-09-20 13:51 UTC, wogha95 commented on files/ko/learn/javascript/first_steps/strings/index.md
> +JavaScript에서는 작은따옴표(`'`), 큰따옴표(`"`) 또는 백틱(`` ` ``)을 선택하여 문자열을 래핑할 수 있습니다. 다음 모두 사용할 수 있습니다.
> In JavaScript, you can choose single quotes (`'`), double quotes (`"`), or backticks (`` ` ``) to wrap your strings in. All of the following will work:

원문은 이렇게 되어 있어서 위와 같이 번역을 하였는데 어떠한 부분이 다르다는 것인지 조금 더 자세하게 말씀해주실 수 있으실까요?
(감싼다라는 표현은 반영하였습니다!)

2023-09-20 14:04 UTC, wogha95 commented
@wisedog  님, 안녕하세요.
리뷰 모두 반영해두었습니다. 확인 부탁드리겠습니다.
([특정 부분 리뷰](https://github.com/mdn/translated-content/pull/15368#discussion_r1331670300)에 답변 달아두었습니다.

2023-09-20 22:32 UTC, wisedog commented on files/ko/learn/javascript/first_steps/strings/index.md
> +JavaScript에서는 작은따옴표(`'`), 큰따옴표(`"`) 또는 백틱(`` ` ``)을 선택하여 문자열을 래핑할 수 있습니다. 다음 모두 사용할 수 있습니다.
`### 따옴표, 쌍따옴표, 백틱` 라고 하셨는데, 원문에는 `Single quotes, double quotes, and backticks` 이더라구요. 그렇다면 아래 글에서는 `Single quotes`를 모두 `따옴표`라고 번역하던가, 제목을 수정하던가 해야하지 않을까 싶습니다.

2023-09-21 23:46 UTC, wisedog commented on files/ko/learn/javascript/first_steps/strings/index.md
> +JavaScript에서는 작은따옴표(`'`), 큰따옴표(`"`) 또는 백틱(`` ` ``)을 선택하여 문자열을 래핑할 수 있습니다. 다음 모두 사용할 수 있습니다.
@wogha95  확인 부탁드립니다.

2023-09-26 13:38 UTC, wisedog commented
> @wisedog 님, 안녕하세요. 리뷰 모두 반영해두었습니다. 확인 부탁드리겠습니다. ([특정 부분 리뷰](https://github.com/mdn/translated-content/pull/15368#discussion_r1331670300)에 답변 달아두었습니다.

안녕하세요. 위에 멘션을 달았는데 답변이 없으셔서 혹시나 해서 다시 알려드립니다.

2023-09-30 09:47 UTC, wogha95 commented on files/ko/learn/javascript/first_steps/strings/index.md
> +JavaScript에서는 작은따옴표(`'`), 큰따옴표(`"`) 또는 백틱(`` ` ``)을 선택하여 문자열을 래핑할 수 있습니다. 다음 모두 사용할 수 있습니다.
아하 확인했습니다. Single quotes 관련하여 전반적으로 검토하고 다시 멘션해두겠습니다!

2023-09-30 09:56 UTC, wogha95 commented
@wisedog 
리뷰해주신 내용 아래와 같이 모두 번역해두었습니다.
확인하시고 리뷰 부탁드립니다.
감사합니다!

```
quote -> 따옴표
single quote -> 따옴표
double quote -> 쌍따옴표
```

2023-09-30 12:00 UTC, wisedog approved these changes

2023-09-30 12:00 UTC, wisedog commented
LGTM

2023-09-30 12:00 UTC, merged