[revise]: revise index.md files for web/glossary/n
mdn/translated-content pull request #15360
Opened 2023-08-24 04:10 UTC by IMHOJEONG

### Description

#15241 의 진행상황 중, web/glossary/n 부분의 일부분 파일들입니다.

### Motivation

web/glossary 접근했는데, 한국어 파일은 없어서 시작하게 되었습니다.

### Additional details

### Related issues and pull requests

#14965 
#15241

2023-09-10 11:31 UTC, yechoi42 requested changes
안녕하세요! 몇가지 사소한 제안 코멘트를 남겨두었습니다. 확인 후 저를 다시 멘션해주세요.

2023-09-10 11:31 UTC, yechoi42 commented on files/ko/glossary/node.js/index.md
>  **Node.js**는 개발자가 서버 측과 네트워크 응용 프로그램을 만들 수 있도록 지원하는 크로스 플랫폼 {{Glossary("JavaScript")}} 런타임 환경입니다.
```suggestion
**Node.js**는 개발자가 서버 사이드 및 네트워크 응용 프로그램을 만들 수 있도록 지원하는 크로스 플랫폼 {{Glossary("JavaScript")}} 런타임 환경입니다.
```
기여해주신 부분은 아니지만 'server-side'를 보통 이야기할 때 '서버 사이드'로 많이 이야기해, 더 나은 이해를 위해 수정하였습니다.

2023-09-10 11:31 UTC, yechoi42 commented on files/ko/glossary/node.js/index.md
> +[npm](https://www.npmjs.com)은 Node.js와 함께 다운로드되어 번들로 제공되는 패키지 관리자입니다. 명령줄(CLI) 클라이언트 `npm`을 사용하여 Node.js 프로젝트에서 사용할 패키지를 다운로드, 구성 및 생성할 수 있습니다. 다운로드한 패키지는 종속성 디렉토리 `node_modules/`를 포함하지 않고 [ES import
```suggestion
[npm](https://www.npmjs.com)은 Node.js와 함께 다운로드되어 번들로 제공되는 패키지 관리자입니다. 명령줄(CLI) 클라이언트 `npm`을 사용하여 Node.js 프로젝트에서 사용할 패키지를 다운로드, 구성 및 생성할 수 있습니다. 다운로드한 패키지는 종속성 디렉토리 `node_modules/`를 포함하지 않고 [ES imports](/ko/docs/Web/JavaScript/Reference/Statements/import)문 및 [CommonJS `require()`](https://en.wikipedia.org/wiki/CommonJS)문을 통해서 가져올 수 있습니다. Node.js는 패키지를 가져올 때 지정된 상대 또는 절대 경로 없이 패키지를 [확인](https://nodejs.org/api/modules.html#loading-from-node_modules-folders)하기 때문입니다.
```

2023-09-10 11:31 UTC, yechoi42 commented on files/ko/glossary/nullish/index.md
>  title: Nullish value
```suggestion
title: Nullish 값
```

2023-09-10 11:31 UTC, yechoi42 commented on files/ko/glossary/nullish/index.md
>  [JavaScript](/ko/docs/Glossary/JavaScript) 에서 Nullish value는 [`null`](/ko/docs/Web/JavaScript/Reference/Operators/null)또는 {{JSxRef("undefined")}}값 중 하나입니다. Nullish values는 항상 [falsy](/ko/docs/Glossar
```suggestion
[JavaScript](/ko/docs/Glossary/JavaScript) 에서 Nullish 값은 [`null`](/ko/docs/Web/JavaScript/Reference/Operators/null)또는 {{JSxRef("undefined")}}값 중 하나입니다. Nullish 값은 항상 [falsy](/ko/docs/Glossary/Falsy) 입니다.
```
value 의미는 번역하는 것이 좋을 것 같습니다.

2023-09-10 11:31 UTC, yechoi42 commented on files/ko/glossary/number/index.md
> +{{Glossary("JavaScript")}}에서 **Number**는 [배정밀도 64비트 부동소수점 형식 (IEEE 754)](https://en.wikipedia.org/wiki/Double_precision_floating-point_format)의 숫자 데이터 타입입니다. 다른 프로그래밍 언어에서는 Intergers, Floats, Doubles
```suggestion
{{Glossary("JavaScript")}}에서 **Number**는 [배정밀도 64비트 부동소수점 형식 (IEEE 754)](https://en.wikipedia.org/wiki/Double_precision_floating-point_format)의 숫자 데이터 타입입니다. 다른 프로그래밍 언어에서는 Interger, Float, Double, Bignum와 같은 다양한 숫자 타입들이 존재할 수 있습니다.
```

2023-09-10 11:31 UTC, yechoi42 commented on files/ko/glossary/number/index.md
> +{{Glossary("JavaScript")}}에서 **Number**는 [배정밀도 64비트 부동소수점 형식 (IEEE 754)](https://en.wikipedia.org/wiki/Double_precision_floating-point_format)의 숫자 데이터 타입입니다. 다른 프로그래밍 언어에서는 Intergers, Floats, Doubles
원문 영어에서는 복수로 쓰였지만 우리말로 할 때에는 타입을 칭하는 것이므로 s는 빼는 것이 좋을 듯합니다.

2023-09-11 05:01 UTC, IMHOJEONG commented on files/ko/glossary/node.js/index.md
>  **Node.js**는 개발자가 서버 측과 네트워크 응용 프로그램을 만들 수 있도록 지원하는 크로스 플랫폼 {{Glossary("JavaScript")}} 런타임 환경입니다.
서버 측보다는 훨신 자연스러운 거 같습니다.

2023-09-11 05:01 UTC, IMHOJEONG commented on files/ko/glossary/node.js/index.md
> +[npm](https://www.npmjs.com)은 Node.js와 함께 다운로드되어 번들로 제공되는 패키지 관리자입니다. 명령줄(CLI) 클라이언트 `npm`을 사용하여 Node.js 프로젝트에서 사용할 패키지를 다운로드, 구성 및 생성할 수 있습니다. 다운로드한 패키지는 종속성 디렉토리 `node_modules/`를 포함하지 않고 [ES import
자연스러운 해석 감사합니다

2023-09-11 05:13 UTC, IMHOJEONG commented
@yechoi42 님 안녕하세요.
주신 피드백 반영하였습니다.

2023-09-16 14:33 UTC, yechoi42 approved these changes
기여 감사합니다!

2023-09-16 14:33 UTC, merged