ko: How to fix a website with blocked mixed content
mdn/translated-content pull request #15389
Opened 2023-08-26 05:39 UTC by SnowMarble

2023-09-18 17:00 UTC, jho2301 requested changes
안녕하세요 수정할 부분 코멘트 드려요

2023-09-18 17:00 UTC, jho2301 commented on files/ko/web/security/mixed_content/how_to_fix_website_with_mixed_content/index.md
> +title: 혼합 콘텐츠가 있는 웹사이트를 고치는 방법
title: How to fix a website with blocked mixed content

2023-09-18 22:41 UTC, SnowMarble commented on files/ko/web/security/mixed_content/how_to_fix_website_with_mixed_content/index.md
> +어떤 경우든 Firefox에 문제가 있는지 확인하는 가장 좋은 방법은 [최신 Firefox 에디션](https://www.mozilla.org/en-US/firefox/developer/)을 다운로드하고, 다른 페이지에서 [웹 콘솔](https://firefox-source-docs.mozilla.org/devtools-user/web_console/in
"여러 페이지"는 원래 말하려는 의도와 다르다고 느껴지는데, 어떤 맥락에서 "different"를 "여러"라고 번역하셨는지 여쭤봐도 괜찮을까요?

2023-09-19 00:15 UTC, jho2301 commented on files/ko/web/security/mixed_content/how_to_fix_website_with_mixed_content/index.md
> +어떤 경우든 Firefox에 문제가 있는지 확인하는 가장 좋은 방법은 [최신 Firefox 에디션](https://www.mozilla.org/en-US/firefox/developer/)을 다운로드하고, 다른 페이지에서 [웹 콘솔](https://firefox-source-docs.mozilla.org/devtools-user/web_console/in
in any case, the best way to know if something is broken in Firefox is to download the [latest Firefox Edition](https://www.mozilla.org/en-US/firefox/developer/), open different pages on your website with the [web console](https://firefox-source-docs.mozilla.org/devtools-user/web_console/index.html) open (enable the "Security" messages) and see if anything related to mixed content is reported.

여기서 다른이라고 해석한다면 어떤 페이지를 대상으로 구분되는 다른 페이지인지 알 수 없습니다.

<img width="686" alt="image" src="https://github.com/mdn/translated-content/assets/44419181/ea5dbc05-6668-4e88-93dd-474a6ade731f">

맥락적으로 distinct,  separate의 의미가 적합합하다고 생각하는데, 좀 더 매끄럽게 의미를 전달하기 위해 '여러' 로 해석하는 방식을 제안드렸어요

2023-09-19 01:13 UTC, SnowMarble commented on files/ko/web/security/mixed_content/how_to_fix_website_with_mixed_content/index.md
> +어떤 경우든 Firefox에 문제가 있는지 확인하는 가장 좋은 방법은 [최신 Firefox 에디션](https://www.mozilla.org/en-US/firefox/developer/)을 다운로드하고, 다른 페이지에서 [웹 콘솔](https://firefox-source-docs.mozilla.org/devtools-user/web_console/in
distinct가 적절하다는 것은 동의합니다. 하지만, '여러(many, several)'는 마치 많은 페이지를 열어라는 뜻이 되는것 같습니다.

> the best way to know if something is broken in Firefox is to download the latest Firefox Edition,

을 봤을 때, 최신 버전의 Firefox에서 웹 사이트에 접속하는 것을 다른 페이지를 연다(이전 브라우저가 최신 버전이 아니라는 가정으로 최신 버전의 Firefox를 다른(different) 페이지라고 칭함.)라고 표현한 것같은데, "여러"는 검사하려는 한 페이지를 많이 열어라는 의미가 될 수 있을것 같습니다.

혹시 @jho2301 님 설명에서 제가 놓친 부분이 있다면, 정말 죄송하지만, 한 번 더 설명을 부탁드리겠습니다.

2023-09-19 01:52 UTC, jho2301 commented on files/ko/web/security/mixed_content/how_to_fix_website_with_mixed_content/index.md
> +어떤 경우든 Firefox에 문제가 있는지 확인하는 가장 좋은 방법은 [최신 Firefox 에디션](https://www.mozilla.org/en-US/firefox/developer/)을 다운로드하고, 다른 페이지에서 [웹 콘솔](https://firefox-source-docs.mozilla.org/devtools-user/web_console/in
죄송합니다만.. 여기서  최신버전의 firefox를 page로 지칭하지는 않는것으로 보입니다.  different pages 동의해주신대로 separate/distinct pages로 대치한다면 직역했을때 구분되는 페이지들이라고 해석할 수 있습니다. 이를 좀 더 순화시켜 여러 페이지들이라고 제안드렸습니다.

2023-09-19 01:54 UTC, SnowMarble commented on files/ko/web/security/mixed_content/how_to_fix_website_with_mixed_content/index.md
> +어떤 경우든 Firefox에 문제가 있는지 확인하는 가장 좋은 방법은 [최신 Firefox 에디션](https://www.mozilla.org/en-US/firefox/developer/)을 다운로드하고, 다른 페이지에서 [웹 콘솔](https://firefox-source-docs.mozilla.org/devtools-user/web_console/in
@hochan222 안녕하세요, 이 부분에 대해 다른 리뷰어의 의견을 구해볼 수 있을까요?

2023-09-19 01:55 UTC, jho2301 commented on files/ko/web/security/mixed_content/how_to_fix_website_with_mixed_content/index.md
> +어떤 경우든 Firefox에 문제가 있는지 확인하는 가장 좋은 방법은 [최신 Firefox 에디션](https://www.mozilla.org/en-US/firefox/developer/)을 다운로드하고, 다른 페이지에서 [웹 콘솔](https://firefox-source-docs.mozilla.org/devtools-user/web_console/in
구버전과 신버전을 비교하지않는다는뜻입니다

2023-09-19 02:09 UTC, SnowMarble commented on files/ko/web/security/mixed_content/how_to_fix_website_with_mixed_content/index.md
> +어떤 경우든 Firefox에 문제가 있는지 확인하는 가장 좋은 방법은 [최신 Firefox 에디션](https://www.mozilla.org/en-US/firefox/developer/)을 다운로드하고, 다른 페이지에서 [웹 콘솔](https://firefox-source-docs.mozilla.org/devtools-user/web_console/in
jho2301님 의견은 이제 이해하고 있습니다. 말씀해주신 것은 브라우저 구분이 아니라 검사할 여러 페이지를 뜻하는것 같습니다.

2023-09-19 02:26 UTC, SnowMarble commented on files/ko/web/security/mixed_content/how_to_fix_website_with_mixed_content/index.md
> +어떤 경우든 Firefox에 문제가 있는지 확인하는 가장 좋은 방법은 [최신 Firefox 에디션](https://www.mozilla.org/en-US/firefox/developer/)을 다운로드하고, 다른 페이지에서 [웹 콘솔](https://firefox-source-docs.mozilla.org/devtools-user/web_console/in
생각해보니 제가 생각한 @jho2301 님 의견이 맞다면 jho2301 님 방향이 괜찮은것 같습니다. 그럼 "검사할 여러 페이지" 또는 "검사할 페이지들"이라고 명시적으로 적어주는건 어떻게 생각하시나요?

2023-09-19 04:46 UTC, jho2301 commented on files/ko/web/security/mixed_content/how_to_fix_website_with_mixed_content/index.md
> +어떤 경우든 Firefox에 문제가 있는지 확인하는 가장 좋은 방법은 [최신 Firefox 에디션](https://www.mozilla.org/en-US/firefox/developer/)을 다운로드하고, 다른 페이지에서 [웹 콘솔](https://firefox-source-docs.mozilla.org/devtools-user/web_console/in
넵넵 좋은것같아요 반영해주시면 어프루브 하도록하겠습니다!

2023-09-19 06:37 UTC, SnowMarble commented
"검사할 여러 페이지"로 최종 수정하였고, 나머지 리뷰 사항도 모두 반영했습니다. 친절히 알려주셔서 고맙습니다!🙇‍♂️

2023-09-19 14:18 UTC, jho2301 approved these changes
늦어져서 죄송하고 기여 감사드려요!

2023-09-19 14:19 UTC, merged