[ko] translate `/learn/javascript/first_steps/what_went_wrong/index.md`
mdn/translated-content pull request #15460
Opened 2023-08-28 15:27 UTC by Chaerim0626

### Description
🧩 ` What went wrong `페이지가 한글로 존재하나, 원문이 지난달에 수정되어 현재 한글 페이지와 원문 페이지의 다른 부분이 존재하여 번역하였습니다. 원문과 다른 부분 전체 번역, 어색한 표현 수정 등을 통한 전체적인 번역을 진행하였습니다.
원문 MDN 링크: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong

### Motivation
💡  `What went wrong` 페이지가 원문과 다른 부분이 존재하여, 이러한 불편을 해소하고 번역에 기여하고 싶어서 작업하였습니다. 많은 분께 도움이 되었으면 합니다.

### Additional details

### Related issues and pull requests

2023-08-28 23:04 UTC, wisedog requested changes
기여 감사합니다. 꽤 긴 글인데 정성스럽게 번역해주셨네요. 사소한 몇 부분만 수정하시면 바로 머지가 가능할 것 같습니다.

2023-08-28 23:04 UTC, wisedog commented on files/ko/learn/javascript/first_steps/what_went_wrong/index.md
> +지금까지 간단한 자바스크립트 프로그램에서 오류를 파악하는 기본 사항을 알아봤습니다. 코드에서 무엇이 잘못되었는지 알아내는 것이 항상 그렇게 간단하지는 않겠지만, 적어도 이렇게 하면 몇 시간의 잠을 절약할 수 있고 특히 학습 여정의 초기 단계에서 일이 제대로 풀리지 않을 때 조금 더 빠르게 진행할 수 있습니다.
`자바스크립트` -> `JavaScript` 입니다

2023-08-28 23:04 UTC, wisedog commented on files/ko/learn/javascript/first_steps/what_went_wrong/index.md
> +   ![](not-a-function.png)
대체 텍스트 번역이 빠졌습니다.

2023-08-28 23:04 UTC, wisedog commented on files/ko/learn/javascript/first_steps/what_went_wrong/index.md
> +   - 첫 번째 부분인 `Uncaught TypeError: guessSubmit.addeventListener`가 함수가 아님에서 무엇이 잘못되었는지를 알 수 있습니다.
`Uncaught TypeError: guessSubmit.addeventListener is not a function` 는 원문 그대로 써주시기 바랍니다.

2023-08-28 23:04 UTC, wisedog commented on files/ko/learn/javascript/first_steps/what_went_wrong/index.md
> +4. 오류 메시지 "guessSubmit.addeventListener is not a function"은 우리가 호출한 함수를 JavaScript 인터프리터가 인식하지 못했다는 뜻입니다. 보통 이 오류는 철자를 잘못 적은 경우 발생합니다. 구문의 올바른 철자가 확실하지 않을 땐 MDN에서 기능 참고서를 살펴보는 게 도움이 됩니다. 선호하는 검색 엔진에서
이 문장을 좀 더 살펴보면 어떨까 합니다. 
원문 "The best way to do this currently is to search for "mdn _name-of-feature_" with your favorite search engine" 이 좀 어색하구요. 

"in this instance" 에서 instance 가 이 경우로 해석되는게 맞을까 싶습니다. 좋은 문장이 없을까요?

2023-08-29 01:39 UTC, Chaerim0626 commented on files/ko/learn/javascript/first_steps/what_went_wrong/index.md
> +4. 오류 메시지 "guessSubmit.addeventListener is not a function"은 우리가 호출한 함수를 JavaScript 인터프리터가 인식하지 못했다는 뜻입니다. 보통 이 오류는 철자를 잘못 적은 경우 발생합니다. 구문의 올바른 철자가 확실하지 않을 땐 MDN에서 기능 참고서를 살펴보는 게 도움이 됩니다. 선호하는 검색 엔진에서
말씀해 주신 부분들 반영하여 수정하였습니다. 세심한 검토 정말 감사드립니다. 
![image](https://github.com/mdn/translated-content/assets/65753465/8b3bb51d-caeb-431a-9632-71f9c250f967)
이 부분을 고려하여서 마지막에 말씀하신 문장도 수정해 보았습니다!

2023-08-29 10:08 UTC, wisedog approved these changes

2023-08-29 10:08 UTC, wisedog commented
LGTM!

2023-08-29 10:08 UTC, merged