[ko]: revise index.md files for `web/glossary/s`
mdn/translated-content pull request #15495
Opened 2023-08-29 16:00 UTC by IMHOJEONG

### Description

#15264  의 진행상황 중, web/glossary/s 부분의 일부분 파일들입니다.

### Motivation

web/glossary 접근했는데, 한국어 파일은 없어서 시작하게 되었습니다.

### Additional details

### Related issues and pull requests

#14965 
#15264

2023-09-17 16:12 UTC, hochan222 requested changes
@IMHOJEONG 님 안녕하세요.

리뷰 사항 하기에 남겨두었습니다.

고생 많으셨습니다. 좋은 하루 보내세요 :)

2023-09-17 16:12 UTC, hochan222 commented on files/ko/glossary/stacking_context/index.md
>  title: 쌓임 맥락
```suggestion
title: 스태킹 컨텍스트 (Stacking context)
```

queue를 열이나 대기줄로 변역하지 않듯이... CSS의 고유 용어여서 음차로 작성하는것이 좋아 보여서 리뷰 드렸습니다.

2023-09-17 16:12 UTC, hochan222 commented on files/ko/glossary/string/index.md
>  title: String
```suggestion
title: 문자열 (String)
```

페이지에서 본문과 제목이 개연성이 있으면 더 내용을 전달하기에 좋다고 생각합니다. 제목에서 String이 나왔는데 본문에서 아무런 힌트없이 바로 문자열로 번역을하면 페이지를 이해하는데 어려움이 증가합니다.

따라서 페이지 본문 첫 예시에서 한글(영어)를 사용하거나 제목을 변경하는것을 제안드립니다.

2023-09-17 16:12 UTC, hochan222 commented on files/ko/glossary/style_origin/index.md
>  title: 스타일 출처
```suggestion
title: 스타일 출처 (Style origin)
```
원 단어를 적어두면 더 좋을듯합니다.

2023-09-17 16:12 UTC, hochan222 commented on files/ko/glossary/synchronous/index.md
> +title: 동기적(Synchronous)
```suggestion
title: 동기(Synchronous)
```
컴퓨터공학에서는 하나의 고유명사로 `동기`로 명사로 번역하는것이 더 좋아 보여서 리뷰 드렸습니다. 

밑에 같이보기에서도  동기와 비동기로 번역해주셨네요!

2023-09-18 06:31 UTC, IMHOJEONG commented on files/ko/glossary/signature/security/index.md
> +**서명** 또는 '디지털 서명'은 메시지가 진짜임을 보여주는 {{glossary("protocol", "프로토콜")}}입니다.
@hochan222 님 안녕하세요.

> 다른 페이지에서 음차를 사용하셨으니 음차로 작성하는 방향은 어떤가요? 혹은 보안쪽은 서명으로의 번역이 명확해서 위와같은 방향도 좋을듯합니다.

혹시 음차를 사용한다는 의미가 어떤 의미인지 궁금합니다. 그냥 소리내는 그대로 표시한다는 것을 의미하시는 걸까요?

2023-09-18 06:31 UTC, IMHOJEONG commented on files/ko/glossary/signature/security/index.md
> +title: 보안 시그니처
서명 (signature) (Security) 과 같은 방향은 어떠하신가요?

2023-09-18 06:33 UTC, IMHOJEONG commented on files/ko/glossary/string/index.md
>  title: String
넵 이부분은 `한글(영어)` 통일하도록 하겠습니다.

2023-09-18 06:34 UTC, IMHOJEONG commented on files/ko/glossary/synchronous/index.md
> +title: 동기적(Synchronous)
앗 그렇습니다. 명사가 더 어울리는 거 같습니다.

2023-09-18 06:45 UTC, IMHOJEONG commented on files/ko/glossary/stacking_context/index.md
>  title: 쌓임 맥락
@hochan222 님 안녕하세요.
Stacking Context가 CSS의 고유 용어 였나요? 찾아보니까, 검색을 통해 찾아보았을 때 쌓임 맥락으로 주로 사용하고 있어서 고유 용어인지 몰랐습니다.

2023-09-21 02:58 UTC, hochan222 commented on files/ko/glossary/signature/security/index.md
> +**서명** 또는 '디지털 서명'은 메시지가 진짜임을 보여주는 {{glossary("protocol", "프로토콜")}}입니다.
@IMHOJEONG 님 안녕하세요~!

네 맞습니다. `시그니처` 였습니다~!

2023-09-21 03:06 UTC, hochan222 commented on files/ko/glossary/signature/security/index.md
> +title: 보안 시그니처
원문은 하기와 같은데요..! `Security signature`처럼 하나의 고유 단어가 아니고 영역의 느낌으로 security를 사용해서 `Signature (security)`에 괄호로 추가해주었다고 생각합니다.

`title: Signature (security)`

>  서명 (signature) (Security) 과 같은 방향은 어떠하신가요?

괄호가 2개여서 조금 혼란이 있을 듯하여 조금 우려됩니다. 또한 Security를 번역하지 않은 이유가 있을지 궁금합니다.

`서명 (signature) (보안)`, `서명 (보안)`, `시그니처 (보안)` 조금 고민이 되네요.

단어 안내서에 추가하는것도 좋을듯하네요.

2023-09-22 00:01 UTC, IMHOJEONG commented on files/ko/glossary/signature/security/index.md
> +**서명** 또는 '디지털 서명'은 메시지가 진짜임을 보여주는 {{glossary("protocol", "프로토콜")}}입니다.
넵 확인했습니다. 페이지 제목과 통일해서 glossary에서는 `서명(signature)`로 가도록 하겠습니다.

2023-09-22 00:11 UTC, IMHOJEONG commented on files/ko/glossary/signature/security/index.md
> +title: 보안 시그니처
@hochan222 님 안녕하세요.

> 또한 Security를 번역하지 않은 이유가 있을지 궁금합니다. 

앗 코멘트 작성 시점에는 번역하지 않아도 되지 않을까라는 생각이 있었습니다. 

아마도, 하나의 단어가 여러 곳에서 동일한 발음을 가지지만, 다른 뜻을 가지고 있어서, 이렇게 폴더로 분리해서 하나의 단어 폴더내에서 여러 폴더로 관리하고 있었다고 생각했습니다(그래서 원문에서도 괄호를 가지고 있어서 제안드렸었습니다.

> 괄호가 2개여서 조금 혼란이 있을 듯하여 조금 우려됩니다

이 부분에 대해서는 이전까지는 `서명 (signature)` 로 번역을 했어서, 같은 괄호 안에 넣는 방향인 `서명 (signature, 보안)`은 같은 의미를 두지는 않는다고 생각했어서, 괄호 2개를 사용하는 방향으로 의견을 드렸습니다. @hochan222 님의 의견이 궁금합니다!

이렇게 다양한 분야에서 사용되는 하나의 단어를 title에서 번역할 때는, `서명 (signature) (보안)` 으로 번역하는 방향이 제 개인적으로는 이전 문서들과의 title을 어느 정도 비슷하게 가져간다고 생각했습니다.

2023-09-22 02:05 UTC, IMHOJEONG commented on files/ko/glossary/stacking_context/index.md
>  title: 쌓임 맥락
넵, 스태킹 컨텍스트 (Stacking context) 로 번역해서 반영해두겠습니다.

2023-10-08 03:58 UTC, IMHOJEONG commented
https://github.com/mdn/translated-content/pull/16340 
위 PR로 인해 Conflict이 발생하게 되어, 해당 stacking_context 파일 제거 후 다시 PR 올려두었습니다.

2023-10-08 04:08 UTC, hochan222 commented
@IMHOJEONG 님 안녕하세요. 충돌해결해주셔서 감사합니다. 

상기 리뷰 중 unresolved 처리된 2가지 리뷰는 빠른 시일내에 리뷰 다시 드리도록 하겠습니다. 감사합니다!

2023-10-08 06:21 UTC, IMHOJEONG commented
#15982가 merge 됨에 따라 
string/index.md도 제거하였습니다.

2024-03-24 11:10 UTC, hochan222 commented on files/ko/glossary/stacking_context/index.md
>  title: 쌓임 맥락
- https://www.w3.org/TR/CSS2/zindex.html

2024-03-24 11:13 UTC, hochan222 commented on files/ko/glossary/signature/security/index.md
> +title: 보안 시그니처
@IMHOJEONG 님 답변이 늦어져서 정말 죄송합니다.

> 서명 (signature) (보안) 으로 번역하는 방향이 제 개인적으로는 이전 문서들과의 title을 어느 정도 비슷하게 가져간다고 생각

충분히 긴 시간 고민했고 좋다고 생각합니다! 감사합니다!

2024-03-24 11:14 UTC, hochan222 approved these changes

2024-03-24 11:16 UTC, hochan222 commented
@IMHOJEONG 님 안녕하세요.

답변 지연되어서 정말 죄송합니다. 하기 2가지 사항 모두 좋습니다. 반영 후 머지하겠습니다.

1. title: 서명 (signature) (보안): https://github.com/mdn/translated-content/pull/15495#discussion_r1536791080
2. stacking_context : https://github.com/mdn/translated-content/pull/15495#discussion_r1333802499

기여해주셔서 정말 감사합니다. 좋은 하루 보내세요 :)

2024-03-24 11:16 UTC, hochan222 commented
고생 정말 많으셨습니다!

2024-03-24 11:16 UTC, merged