[ko] Add `table_advanced` translation
mdn/translated-content pull request #15499
Opened 2023-08-29 19:17 UTC by rbals0445

### Description

- `table_advanced` 번역을 추가하였습니다.

### Motivation

### Additional details

### Related issues and pull requests

2023-09-19 03:46 UTC, sunhpark42 commented
안녕하세요. @rbals0445  님 기여감사합니다!
개인 사정으로 리뷰가 늦어져서 죄송합니다. 해당 리뷰 9/22 6시 이전에 리뷰 드리겠습니다.
기다려주셔서 감사합니다. 🙇‍♀️

2023-09-20 13:02 UTC, rbals0445 commented
@sunhpark42 님 천천히 해주셔도 되어요~~

2023-10-07 03:49 UTC, rbals0445 commented
@sunhpark42 님, 혹시 리뷰 가능하실까요??? 
리뷰가 어려우시다면 다른 리뷰어분 지정해주시면 감사하겠습니다.

2023-10-10 07:41 UTC, hochan222 commented
@rbals0445 님 안녕하세요. 리뷰가 지연되어서 죄송합니다. 빠른 시간안에 리뷰드릴 수 있도록 하겠습니다.

좋은 하루 보내세요! (cc. @sunhpark42 님)

2023-10-10 14:14 UTC, sunhpark42 requested changes
안녕하세요. @rbals0445 님, 리뷰가 많이 늦어져서 죄송합니다.
덕분에 테이블 관련 접근성 내용을 읽을 수 있었네요!

리뷰 코멘트로 남겨두었으며, 번역해주신 내용중 article이 기사로 변역되어 있어, 문서로 변경하는것이 더 자연스럽지 않을까하여 의견드려봅니다.

기여 감사합니다! 🙇‍♀️

2023-10-10 14:14 UTC, sunhpark42 commented on files/ko/learn/html/tables/advanced/index.md
> +> **참고:** `<tbody>`는 항상 테이블에 포함되어 있습니다. 코드에서 명시적으로 지정하지 않으면 암시적으로 포함됩니다. 이를 확인하기 위해 `<tbody>`를 포함하지 않는 이전 예제를 열고 [브라우저 개발자 도구](/ko/docs/Learn/Common_questions/Tools_and_setup/What_are_browser_develop
```suggestion
> **참고:** `<tbody>`는 항상 테이블에 포함되어 있습니다. 코드에서 명시적으로 지정하지 않으면 암시적으로 포함됩니다. 이를 확인하기 위해 `<tbody>`를 포함하지 않는 이전 예제를 열고 [브라우저 개발자 도구](/ko/docs/Learn/Common_questions/Tools_and_setup/What_are_browser_developer_tools)에서 HTML 코드를 확인하세요. 브라우저가 이 요소를 자동으로 추가했을 것입니다. 이것을 왜 포함해야 하는지 궁금할 것입니다. 하지만 이 요소를 포함하는 것이 테이블 구조와 스타일링을 더 잘 제어할 수 있기 때문에 포함하는 것이 좋습니다.
```

영어 원문이 `You might wonder why you ought to bother including it at all` 으로 왜 굳이 이걸 추가해야 하는지 궁금해 할 수 도 있다. 라는 의미로, 변경 부탁드립니다. change 는 임의로 수정한 것으로, 보다 자연스러운 문장으로 변경해 주셔도 좋을 것 같습니다.🙇‍♀️

2023-10-10 14:14 UTC, sunhpark42 commented on files/ko/learn/html/tables/advanced/index.md
> +7. 저장하고 새로 고침하면 결과를 확인할 수 있습니다. `<tbody>`와 `<tfoot>` 요소가 없었다면, 동일한 스타일링을 적용하기 위해 훨씬 복잡한 선택자/규칙을 작성해야 했을 것입니다.
`선택자/규칙` -> `선택자와 규칙` 으로 작성하는 것이 더 자연스럽게 읽힐 것 같은데 어떻게 생각하시나요?

2023-10-10 14:14 UTC, sunhpark42 commented on files/ko/learn/html/tables/advanced/index.md
> +### Active learning: playing with scope and headers
제목 번역 부탁드립니다.

2023-10-12 16:50 UTC, rbals0445 commented
@sunhpark42 님, 안녕하세요~ 반영했습니다!  (https://github.com/mdn/translated-content/pull/15499/commits/75c9b6ff24face16b339ba2387d044a8f046cbeb)

2023-10-16 10:13 UTC, sunhpark42 approved these changes
안녕하세요 @rbals0445 님, 수정해주신 부분 확인하였습니다~! 
감사합니다 :) 👍👍

2023-10-16 10:13 UTC, merged