[ko] Add `debugging_css` translation
mdn/translated-content pull request #15497
Opened 2023-08-29 16:24 UTC by rbals0445

### Description

- `debugging_css`에 sourceCommit을 추가했습니다. 
- 원본 파일과 비교해 수정 및 누락된 부분을 추가하였습니다.

### Motivation

### Additional details

### Related issues and pull requests

2023-09-10 12:39 UTC, yechoi42 requested changes
안녕하세요. 기여 감사합니다! 개발자 도구도 널리 쓰이는 표현이기 때문에 번역하는 편이 더 좋겠습니다. 이 외에 포맷 등 사소한 수정 제안 남겨두었으니, 확인 후 저를 다시 멘션하거나 제게 다시 리뷰 요청 주세요!

2023-09-10 12:39 UTC, yechoi42 commented on files/ko/learn/css/building_blocks/debugging_css/index.md
> +때로는 CSS를 작성할 때 CSS가 예상한 대로 동작하지 않는 문제가 발생합니다. 아마도 특정 선택자가 요소와 일치해야 하지만, 아무 일도 일어나지 않거나 박스의 크기가 예상과 다릅니다. 이 기사에서는 CSS 문제를 디버깅하는 방법에 대한 지침을 제공하고 모든 최신 브라우저에 포함된 DevTools가 진행 상황을 찾는 데 어떻게 도움이 되는지 보여줍니다.
```suggestion
때로는 CSS를 작성할 때 CSS가 예상한 대로 동작하지 않는 문제가 발생합니다. 아마도 특정 선택자가 요소와 일치해야 하지만, 아무 일도 일어나지 않거나 박스의 크기가 예상과 다릅니다. 이 기사에서는 CSS 문제를 디버깅하는 방법에 대한 지침을 제공하고 모든 최신 브라우저에 포함된 개발자 도구가 진행 상황을 찾는 데 어떻게 도움이 되는지 보여줍니다.
```

2023-09-10 12:39 UTC, yechoi42 commented on files/ko/learn/css/building_blocks/debugging_css/index.md
> +        브라우저 DevTools의 기본 사항과 CSS의 간단한 검사 및 편집방법 배우기.
```suggestion
        브라우저 개발자 도구의 기본 사항과 CSS의 간단한 검사 및 편집방법 배우기.
```

2023-09-10 12:39 UTC, yechoi42 commented on files/ko/learn/css/building_blocks/debugging_css/index.md
>  ## 브라우저 개발자 도구 (DevTools) 사용 방법
```suggestion
## 브라우저 개발자 도구 사용 방법
```

2023-09-10 12:39 UTC, yechoi42 commented on files/ko/learn/css/building_blocks/debugging_css/index.md
> +또한 DevTools를 만들 때 브라우저가 다른 영역에 집중하도록 선택했음을 알 수 있습니다. 예를 들어, Firefox에는 CSS 레이아웃으로 시각적으로 작업하기 위한 훌륭한 도구가 있으며, [그리드 레이아웃](/ko/docs/Tools/Page_Inspector/How_to/Examine_grid_layouts), [Flexbox](/ko/docs/T
```suggestion
또한 브라우저마다 개발자 도구에서 집중하는 부분이 다르다는 것을 알 수 있습니다. 예를 들어, Firefox에는 CSS 레이아웃으로 시각적으로 작업하기 위한 훌륭한 도구가 있으며, [그리드 레이아웃](/ko/docs/Tools/Page_Inspector/How_to/Examine_grid_layouts), [Flexbox](/ko/docs/Tools/Page_Inspector/How_to/Examine_Flexbox_layouts) 및 [Shapes](/ko/docs/Tools/Page_Inspector/How_to/Edit_CSS_shapes)를 검사하고 편집할 수 있습니다. 그러나, 모든 브라우저마다 유사한 기본 도구가 있습니다. 이러한 기본 도구는 예를 들면 페이지의 요소에 적용된 속성 및 값을 검사하고 편집기에서 변경하는 데 사용됩니다.
```

'You will also find that browsers have chosen to focus on different areas when creating their DevTools. ' 원문을 이해하기 쉽게 제안드립니다.

2023-09-10 12:39 UTC, yechoi42 commented on files/ko/learn/css/building_blocks/debugging_css/index.md
> +이 수업에서는 CSS 작업을 위한 Firefox DevTools의 유용한 기능을 살펴봅니다. 이를 위해 [예제 파일](https://mdn.github.io/css-examples/learn/inspecting/inspecting.html)을 사용하겠습니다. 따라 하고 싶다면, 새 탭에 로드하고 위에 링크된 기사에 설명된 대로 DevTools를 여세요.
```suggestion
이 수업에서는 CSS 작업을 위한 Firefox 개발자 도구의 유용한 기능을 살펴봅니다. 이를 위해 [예제 파일](https://mdn.github.io/css-examples/learn/inspecting/inspecting.html)을 사용하겠습니다. 따라하고 싶다면, 새 탭에 로드하고 위에 링크된 기사에 설명된 대로 개발자 도구를 여세요.
```

2023-09-10 12:39 UTC, yechoi42 commented on files/ko/learn/css/building_blocks/debugging_css/index.md
> +새로운 사용자를 개발자 도구 (DevTools)로 체험할 수 있는 것은 웹 페이지의 [소스 보기](/ko/docs/Tools/View_source) 를 보거나 서버에 넣은 HTML 파일을 볼 때 표시되는 것과 개발자 도구의 [HTML 창](/ko/docs/Tools/Page_Inspector/UI_Tour#HTML_pane)에서 볼 수 있는 것의 차이입니
```suggestion
새로운 사용자가 개발자 도구에서 혼동할 수 있는 것은 웹 페이지의 [소스 보기](/ko/docs/Tools/View_source) 를 보거나 서버에 넣은 HTML 파일을 볼 때 표시되는 것과 개발자 도구의 [HTML 창](/ko/docs/Tools/Page_Inspector/UI_Tour#HTML_pane)에서 보이는 것의 차이입니다. 소스 보기를 통해 볼 수 있는 것과 거의 비슷해 보이지만 몇 가지 차이점이 있습니다.
```
기존 번역문에 오역이 있어 수정 제안 드립니다.

2023-09-10 12:39 UTC, yechoi42 commented on files/ko/learn/css/building_blocks/debugging_css/index.md
> +페이지에서 요소를 마우스 오른쪽/ctrl 키를 누른 채 클릭하고 **검사 (Inspect)** 를 선택하거나, 개발자 도구 디스플레이 왼쪽의 HTML tree에서 요소를 선택하세요. `box1` 클래스의 요소를 선택하세요. 이것은 테두리 박스가 그려진 페이지의 첫 번째 요소입니다.
```suggestion
페이지에서 요소를 마우스 오른쪽/ctrl 키를 누른 채 클릭하고 **검사(Inspect)** 를 선택하거나, 개발자 도구 디스플레이 왼쪽의 HTML tree에서 요소를 선택하세요. `box1` 클래스의 요소를 선택하세요. 이것은 테두리 박스가 그려진 페이지의 첫 번째 요소입니다.
```

2023-09-10 12:39 UTC, yechoi42 commented on files/ko/learn/css/building_blocks/debugging_css/index.md
> +속성을 켜고 끄는 것 외에도 해당 값을 편집할 수 있습니다. 다른 색상이 더 잘 보이는지 확인하고 싶거나 크기를 조정하고 싶으신가요? DevTools를 사용하면 스타일시트를 편집하고 페이지를 다시 로드하는 데 많은 시간을 절약할 수 있습니다.
```suggestion
속성을 켜고 끄는 것 외에도 해당 값을 편집할 수 있습니다. 다른 색상이 더 잘 보이는지 확인하고 싶거나 크기를 조정하고 싶으신가요? 개발자 도구를 사용하면 스타일시트를 편집하고 페이지를 다시 로드하는 데 많은 시간을 절약할 수 있습니다.
```

2023-09-10 12:39 UTC, yechoi42 commented on files/ko/learn/css/building_blocks/debugging_css/index.md
> +DevTools를 사용하여 속성을 추가할 수 있습니다. 상자가 `<body>` 요소의 글꼴 크기를 상속하는 것을 원하지 않고 고유한 특정 크기를 설정하기를 원하시나요? CSS 파일에 추가하기 전에 DevTools에서 시도할 수 있습니다.
```suggestion
개발자 도구를 사용하여 속성을 추가할 수 있습니다. 상자가 `<body>` 요소의 글꼴 크기를 상속하는 것을 원하지 않고 고유한 특정 크기를 설정하기를 원하시나요? CSS 파일에 추가하기 전에 DevTools에서 시도할 수 있습니다.
```

2023-09-10 12:39 UTC, yechoi42 commented on files/ko/learn/css/building_blocks/debugging_css/index.md
> +![색상 선택자가 열린 DevTools](inspecting2-color-picker.png)
```suggestion
![색상 선택자가 열린 개발자 도구](inspecting2-color-picker.png)
```

2023-09-10 12:39 UTC, yechoi42 commented on files/ko/learn/css/building_blocks/debugging_css/index.md
> +**규칙에서 닫는 중괄호를 클릭하여 새 선언 입력을 시작할 수 있습니다. 이 시점에서 새 속성 입력을 시작할 수 있으며 DevTools는 일치하는 속성의 자동 완성 목록을 표시합니다. `font-size`를 선택한 후 시도하려는 값을 입력합니다. + 버튼을 클릭하여 동일한 선택자로 규칙을 추가하고 거기에 새 규칙을 추가할 수도 있습니다.**
```suggestion
**규칙에서 닫는 중괄호를 클릭하여 새 선언 입력을 시작할 수 있습니다. 이 시점에서 새 속성 입력을 시작할 수 있으며 개발자 도구는 일치하는 속성의 자동 완성 목록을 표시합니다. `font-size`를 선택한 후 시도하려는 값을 입력합니다. + 버튼을 클릭하여 동일한 선택자로 규칙을 추가하고 거기에 새 규칙을 추가할 수도 있습니다.**
```

2023-09-10 12:39 UTC, yechoi42 commented on files/ko/learn/css/building_blocks/debugging_css/index.md
> +![DevTools 패널, 규칙에 새 속성을 추가하고, 폰트 자동 완성을 열고 있습니다.](inspecting3-font-size.png)
```suggestion
![개발자 도구 패널, 규칙에 새 속성을 추가하고, 폰트 자동 완성을 열고 있습니다.](inspecting3-font-size.png)
```

2023-09-10 12:39 UTC, yechoi42 commented on files/ko/learn/css/building_blocks/debugging_css/index.md
>  ## box model 이해
```suggestion
## 박스 모델 이해
```

2023-09-10 12:39 UTC, yechoi42 commented on files/ko/learn/css/building_blocks/debugging_css/index.md
> +![DevTools의 레이아웃 섹션](inspecting4-box-model.png)
```suggestion
![개발자 도구의 레이아웃 섹션](inspecting4-box-model.png)
```

2023-09-10 12:39 UTC, yechoi42 commented on files/ko/learn/css/building_blocks/debugging_css/index.md
> +**`.special` 클래스로 `<em>`을 검사하면 DevTools에서 주황색이 적용되는 색상임을 보여주고 또한 em에 적용된 `color` 속성은 그어진 선으로 표시됩니다. 이제 클래스가 요소 선택자를 재정의하는 것을 볼 수 있습니다.**
```suggestion
**`.special` 클래스로 `<em>`을 검사하면 개발자 도구에서 주황색이 적용되는 색상임을 보여주고 또한 em에 적용된 `color` 속성은 그어진 선으로 표시됩니다. 이제 클래스가 요소 선택자를 재정의하는 것을 볼 수 있습니다.**
```

2023-09-10 12:39 UTC, yechoi42 commented on files/ko/learn/css/building_blocks/debugging_css/index.md
>  ## Firefox DevTools에 대해 자세히 알아보기
```suggestion
## Firefox 개발자 도구에 대해 자세히 알아보기
```

2023-09-10 12:39 UTC, yechoi42 commented on files/ko/learn/css/building_blocks/debugging_css/index.md
> +여기 MDN에 Firefox DevTools에 대한 많은 정보가 있습니다. 주요 [DevTools 섹션](https://firefox-source-docs.mozilla.org/devtools-user/index.html)을 살펴보고 이 강의에서 간략하게 다룬 내용에 대한 자세한 내용은 [방법 안내](https://firefox-source-docs.mo
```suggestion
여기 MDN에 Firefox 개발자 도구 대한 많은 정보가 있습니다. 주요 [개발자 도구 섹션](https://firefox-source-docs.mozilla.org/devtools-user/index.html)을 살펴보고 이 강의에서 간략하게 다룬 내용에 대한 자세한 내용은 [방법 안내](https://firefox-source-docs.mozilla.org/devtools-user/page_inspector/index.html#how-to)를 참조하세요.
```

2023-09-10 12:39 UTC, yechoi42 commented on files/ko/learn/css/building_blocks/debugging_css/index.md
> +2. JavaScript를 제거해도 문제가 해결되지 않으면 JavaScript를 포함하지 마세요. JavaScript를 제거해도 문제가 _해결되지 않는_ 경우 가능한 한 많은 JavaScript를 제거하고 문제의 원인은 그대로 두세요.
```suggestion
2. JavaScript를 제거해도 문제가 해결되지 않으면 JavaScript를 포함하지 마세요. JavaScript를 제거해도 문제가 *해결되지 않는* 경우 가능한 한 많은 JavaScript를 제거하고 문제의 원인은 그대로 두세요.
```

2023-09-11 09:55 UTC, rbals0445 commented
@yechoi42 님, 리뷰 감사합니다~
- "DevTools" -> "개발자 도구" 수정
- box model -> 박스 모델 수정
- 그 외 제안주신 번역 으로 수정
  - https://github.com/mdn/translated-content/pull/15497#discussion_r1320761329

2023-09-11 14:03 UTC, rbals0445 commented on files/ko/learn/css/building_blocks/debugging_css/index.md
> +2. JavaScript를 제거해도 문제가 해결되지 않으면 JavaScript를 포함하지 마세요. JavaScript를 제거해도 문제가 _해결되지 않는_ 경우 가능한 한 많은 JavaScript를 제거하고 문제의 원인은 그대로 두세요.
여기는 로컬 환경에서 수정했을때 자동으로 * -> _ 로 바뀌었는데, 강제로 변경하니 린트 에러가 생겨서 변경하지 않았습니다!

https://github.com/mdn/translated-content/pull/15497#discussion_r1321299452

2023-09-16 14:31 UTC, yechoi42 approved these changes
기여 감사합니다!

2023-09-16 14:31 UTC, merged