[ko] translate css @keyframes
mdn/translated-content pull request #15519
Opened 2023-08-30 13:58 UTC by msdio

Web/CSS/@keyframes 를 번역했습니다.

기존에 존재하던 문서도 최신화 했는데, 과도하게 내용이 변경되었거나 필요한 내용이 누락된 경우는 코멘트 남겨주시면 감사하겠습니다 :)

2023-09-02 03:17 UTC, pje1740 requested changes
고생하셨습니다! 몇가지 수정사항 참고 부탁드립니다.
그리고 그 사이에 문서가 살짝 최신화되었는데요, 최신화된 부분까지도 업데이트 가능하시다면 추가해주시면 좋을 거 같습니다!

2023-09-09 10:48 UTC, msdio commented on files/ko/web/css/@keyframes/index.md
> +만약 한개의 이름에 대해서 여러개의 키프레임 셋이 존재하면, 파서가 마지막으로 마주치는 키프레임 셋만 유효합니다. `@keyframes` 룰은 연속되지 않기 때문에 한개의 룰 셋 이상을 적용하지 않습니다.
저도 기존에 부분 번역되어 있는 것이 일부는 `연속`, 일부는 `캐스케이드`라고 되어 있기도 하고, 정확하게 대응되는 한글이 애매한 것 같았습니다. 우선 제안해주신 대로 캐스케이드로 변경한 뒤 나중에 가이드가 생긴다면 업데이트 하겠습니다!

2023-09-09 10:50 UTC, msdio commented on files/ko/web/css/@keyframes/index.md
>  ### 중복 해상도
원문을 보며 직역하다 보니 맥락을 체크하지 못한 것 같습니다. 감사합니다 :)

2023-09-09 12:38 UTC, msdio commented
@pje1740 리뷰 감사합니다. 리뷰해주신 내용과 업데이트 된 컨텐츠들 반영해놓았는데 확인 부탁드립니다 🙂

2023-09-09 15:12 UTC, hochan222 commented on files/ko/web/css/@keyframes/index.md
> +만약 한개의 이름에 대해서 여러개의 키프레임 셋이 존재하면, 파서가 마지막으로 마주치는 키프레임 셋만 유효합니다. `@keyframes` 룰은 연속되지 않기 때문에 한개의 룰 셋 이상을 적용하지 않습니다.
> @hochan222 혹시 관련해서 논의가 있었을까요?

한번도 논의된적 없습니다!  CSS에서 사용하는 Cascade는 하나의 고유 단어로 Cascade 알고리즘의 의미도 내포되어 있어서 "연속"으로 번역하기보다는 음차로 번역하는 것이 좋아보이는데 어떻게 생각하시나요?

2023-09-12 09:46 UTC, pje1740 commented on files/ko/web/css/@keyframes/index.md
> +만약 한개의 이름에 대해서 여러개의 키프레임 셋이 존재하면, 파서가 마지막으로 마주치는 키프레임 셋만 유효합니다. `@keyframes` 룰은 연속되지 않기 때문에 한개의 룰 셋 이상을 적용하지 않습니다.
저도 캐스케이드 라고 그대로 번역하는 것 좋아보입니다! 이것도 가이드 추가가 필요하려나요?? 👀

2023-09-12 09:50 UTC, pje1740 approved these changes
수정 확인했습니다! 우선은 캐스케이드로 번역 반영된 것으로 머지하겠습니다.
고생하셨습니다!

2023-09-12 09:50 UTC, merged

2023-09-17 10:20 UTC, hochan222 commented on files/ko/web/css/@keyframes/index.md
> +만약 한개의 이름에 대해서 여러개의 키프레임 셋이 존재하면, 파서가 마지막으로 마주치는 키프레임 셋만 유효합니다. `@keyframes` 룰은 연속되지 않기 때문에 한개의 룰 셋 이상을 적용하지 않습니다.
네! 추가해 놓겠습니다 🙇🙇