[ko] JavaScript/Reference/Functions의 index.md 파일 소스 커밋 추가 및 번역 최신화
mdn/translated-content pull request #15533
Opened 2023-08-31 01:21 UTC by 2kkeullim

### Description
JavaScript/Reference/Functions의 index.md 파일의 전체적인 번역을 수정하였으며,
소스 커밋을 추가하고 원문과 비교하여 수정하였습니다.

### Motivation

### Additional details

### Related issues and pull requests
#15477

2023-09-12 01:30 UTC, 2kkeullim commented
@yujo11 리뷰 부탁드립니다😀

2023-09-17 12:00 UTC, hochan222 commented
@2kkeullim 님 안녕하세요.

리뷰어의 개인적인 사정으로 리뷰어가 변경되어, 제가 리뷰드릴 예정입니다. 리뷰가 조금 지연되어도 양해 부탁드립니다.

좋은 하루 보내세요 :)

2023-10-01 00:27 UTC, wisedog commented
@hochan222 이것도 제가 맡을까요?

2023-10-01 03:18 UTC, hochan222 commented
네 ㅜㅜ 감사합니다!

2023-10-02 09:40 UTC, wisedog requested changes
몇 가지 수정사항을 남겼습니다. 확인 부탁드리겠습니다!

2023-10-02 09:40 UTC, wisedog commented on files/ko/web/javascript/reference/functions/index.md
> +const car = {
ㅎㅎㅎㅎㅎㅎ. 원칙적으로 예제는 변경이 안되지만 말이죠.
로컬라이제이션 측면에서 필요하다면 가능합니다. 😉
즉, 그냥 두셔도 됩니다.

2023-10-02 09:40 UTC, wisedog commented on files/ko/web/javascript/reference/functions/index.md
> +크게 보면 자바스크립트에는 네 가지 종류의 함수가 있습니다.
자바스크립트 -> JavaScript 입니다. 
참고 가이드: https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md#%EA%B3%B5%ED%86%B5

2023-10-02 09:40 UTC, wisedog commented on files/ko/web/javascript/reference/functions/index.md
> +- 선언
본문과는 다른데 의미 전달을 잘 하시려고 노력하셨네요. 저도 동의합니다.

2023-10-02 09:40 UTC, wisedog commented on files/ko/web/javascript/reference/functions/index.md
> +- `함수` 생성자는 런타임 컴파일을 유발하며 다른 구문보다 속도가 느린 경우가 많습니다.
원래 백틱(``) 은 원문 그대로 쓰는게 원칙인데요. 설명 단락에서 `function` 도 문맥상 괜찮았는데 여기는 좀 아니지 않나 싶습니다. 의견이 어떠실까요?

2023-10-02 09:40 UTC, wisedog commented on files/ko/web/javascript/reference/functions/index.md
> +한 마디로, **안 됩니다**.
안된다기 보다는 "하지 마세요"가 의미상 맞을듯 하네요. 어떻게 생각하시나요

2023-10-10 05:35 UTC, 2kkeullim commented
@wisedog 피드백 주신 부분 반영하고 최신 소스커밋으로 수정하였습니다!

2023-10-10 08:34 UTC, wisedog approved these changes

2023-10-10 08:35 UTC, merged