[ko] Functions/get 소스 커밋 추가 및 번역 최신화
mdn/translated-content pull request #15547
Opened 2023-08-31 12:37 UTC by 2kkeullim

### Description
JavaScript/Reference/Functions/get의 index.md 파일의
전체적인 번역을 수정하였으며,
소스 커밋을 추가하고 원문과 비교하여 수정하였습니다.

### Motivation

### Additional details

### Related issues and pull requests
close #15481

2023-08-31 22:31 UTC, wisedog requested changes
안녕하세요! 기여 감사합니다. 

내용은 큰 문제는 없지만 몇 가지 사소한 문제만 수정 부탁드리겠습니다.

2023-08-31 22:31 UTC, wisedog commented on files/ko/web/javascript/reference/functions/get/index.md
> +**`get`** 구문은 객체의 속성 접근 시 호출할 함수를 바인딩합니다. 이 구문은 [classes](/en-US/docs/Web/JavaScript/Reference/Classes)에서도 사용할 수 있습니다.
한국어 문서가 없더라도 `/ko`로 해주셔야 합니다.

2023-08-31 22:31 UTC, wisedog commented on files/ko/web/javascript/reference/functions/get/index.md
> +  - : 지정된 함수에 바인딩할 속성의 이름입니다. [객체 초기자](/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer)의 다른 속성과 동일한 방식으로 문자열 리터럴, 숫자 리터럴 또는 식별자일 수 있습니다.
이 문서를 비롯해 다른 문서도 모두 `/ko` 로 변경 부탁드립니다.

2023-08-31 22:31 UTC, wisedog commented on files/ko/web/javascript/reference/functions/get/index.md
> +동적으로 계산된 값을 반환하는 속성에 대한 접근을 허용하는 것이 바람직한 경우도 있습니다.
영문에서 줄바꿈을 한건 120자 때문인데요. 한국어는 보통 그보다 짧기 때문에 적절한 줄바꿈을 하면 좀 더 읽기 편한 문서가 되지 않을까 합니다.

2023-08-31 22:31 UTC, wisedog commented on files/ko/web/javascript/reference/functions/get/index.md
> +다음 예제는 객체 `obj`에 유사 속성 `latest`를 생성합니다.
`pseudo`는 `유사`보다는 `의사`가 아닐까 합니다. 근데 의사 속성이라... 저도 공부를 좀 더 해야겠군요.🤔

2023-08-31 22:31 UTC, wisedog commented on files/ko/web/javascript/reference/functions/get/index.md
> +접근자 속성은 클래스의 `속성`으로 정의되므로 클래스의 모든 인스턴스에서 공유됩니다. 객체 리터럴의 접근자 속성과 달리 클래스의 접근자 속성은 열거할 수 없습니다.
인용구 \``속성`\` 대신 `prototype` 을 적어주시기 바랍니다.

2023-08-31 22:31 UTC, wisedog commented on files/ko/web/javascript/reference/functions/get/index.md
> +접근자를 삭제하려면 간단히 {{jsxref("Operators/delete", "delete")}} 연산자를
다시 말씀드리지만 줄바꿈을 꼭 영어와 동일하게 할 필요가 없습니다. : >

2023-08-31 22:31 UTC, wisedog commented on files/ko/web/javascript/reference/functions/get/index.md
> +접근자를 사용하면 객체에 속성을 **정의**하되,
이 곳 역시 줄바꿈때문에 도리어 가독성이 떨어지는 것 같습니다. 🥲

2023-09-01 01:13 UTC, 2kkeullim commented
@wisedog 빠른 리뷰 감사드립니다! 리뷰해주신 부분 수정해서 반영하였습니다!

2023-09-02 05:19 UTC, wisedog approved these changes

2023-09-02 05:20 UTC, merged