[revise]: revise index.md in web/glossary/advance_measure
mdn/translated-content pull request #15551
Opened 2023-08-31 15:27 UTC by IMHOJEONG

### Description

#15210  의 진행상황 중, `web/glossary/advance_measure` 부분의 일부분 파일들입니다.

### Motivation

web/glossary 접근했는데, 한국어 파일은 없어서 시작하게 되었습니다.

### Additional details

### Related issues and pull requests

#14965 
#15210

2023-09-16 14:45 UTC, yechoi42 requested changes
한가지 코멘트 남겨두었습니다! 확인부탁드립니다!

2023-09-16 14:45 UTC, yechoi42 commented on files/ko/glossary/advance_measure/index.md
> +title: Advance measure
```suggestion
title: 사전 측정
```
본문에서 번역했다면 제목도 번역하는 쪽이 좋을 것 같습니다!

2023-09-17 11:58 UTC, hochan222 requested changes

2023-09-17 11:58 UTC, hochan222 commented on files/ko/glossary/advance_measure/index.md
> +title: Advance measure (사전 측정)
```suggestion
title: 사전 측정 (Advance measure)
```

문서의 일관성을 위해 한글, 영어 둘다 사용 사례에서 `한글 (영어)` 로 변경 부탁드립니다. 해당 부분 현재 가이드에 존재하지 않아 추가하겠습니다.

2023-09-17 12:05 UTC, IMHOJEONG commented on files/ko/glossary/advance_measure/index.md
> +title: Advance measure (사전 측정)
앗 넵. 반대로 수정했네요.
피드백 감사합니다!

2023-09-17 12:09 UTC, hochan222 approved these changes

2023-09-17 15:11 UTC, yechoi42 approved these changes

2023-09-17 15:11 UTC, merged