[ko]: add index.md in `web/glossary/apple_safari`
mdn/translated-content pull request #15569
Opened 2023-09-01 16:37 UTC by IMHOJEONG

### Description

#15186  의 진행상황 중, `web/glossary/apple_safari` 부분입니다.

### Motivation

web/glossary 접근했는데, 한국어 파일은 없어서 시작하게 되었습니다.

### Additional details

### Related issues and pull requests

#14965 
fix #15186

2023-10-03 02:01 UTC, wisedog commented
@hochan222  이 PR도 제가

2023-10-03 02:02 UTC, wisedog requested changes
한 군데 수정 부탁드립니다.

2023-10-03 02:02 UTC, wisedog commented on files/ko/glossary/apple_safari/index.md
> +## See also
이 부분이 번역이 안되었네요!

2023-10-03 11:02 UTC, IMHOJEONG commented on files/ko/glossary/apple_safari/index.md
> +## See also
피드백 감사합니다!

2023-10-04 04:59 UTC, wisedog approved these changes

2023-10-04 04:59 UTC, merged