[ko]: add index.md in `web/glossary/base64`
mdn/translated-content pull request #15609
Opened 2023-09-03 11:16 UTC by IMHOJEONG

### Description

#15211  의 진행상황 중, `web/glossary/base64` 부분입니다.

### Motivation

web/glossary 접근했는데, 한국어 파일은 없어서 시작하게 되었습니다.

### Additional details

### Related issues and pull requests

#14965 
#15211

2023-09-07 13:34 UTC, pje1740 requested changes
고생하셨습니다! 코멘트 확인 부탁드릴게요!

2023-09-07 13:34 UTC, pje1740 commented on files/ko/glossary/base64/index.md
> +**Base64**는 이진 데이터를 기수-64 표현으로 변환하여 {{glossary("ASCII")}} 문자열 형식으로 나타내는 유사한 [이진 데이터를 텍스트로 인코딩](https://en.wikipedia.org/wiki/Binary-to-text_encoding)하는 구성표의 그룹입니다. 'Base64'라는 용어는 특정 [MIME 콘텐츠 전송 인코딩]
```suggestion
**Base64**는 이진 데이터를 기수-64 표현으로 변환하여 {{glossary("ASCII")}} 문자열 형식으로 나타내는 유사한 [이진 데이터를 텍스트로 인코딩](https://en.wikipedia.org/wiki/Binary-to-text_encoding)방식의 그룹입니다. 'Base64'라는 용어는 특정 [MIME 콘텐츠 전송 인코딩](https://en.wikipedia.org/wiki/MIME#Content-Transfer-Encoding)에서 생겼습니다.
```
저도 번역기를 조금 참고해보았는데요, '방식'이라고 번역되어도 자연스러울 거 같은데 의견 궁금합니다!

2023-09-07 13:34 UTC, pje1740 commented on files/ko/glossary/base64/index.md
> +특정 알고리즘을 표현하기 위해 "Base64"라는 용어가 단독으로 사용되는 경우, 일반적으로 [RFC 4648](https://datatracker.ietf.org/doc/html/rfc4648)에 설명된 Base64 버전을 나타냅니다. 섹션 4에서는 아래 알파벳을 사용하여 64진수를 표현하고 `=`를 패딩 문자로 사용합니다.
```suggestion
특정 알고리즘을 표현하기 위해 "Base64"라는 용어가 단독으로 사용되는 경우, 일반적으로 [RFC 4648](https://datatracker.ietf.org/doc/html/rfc4648) 섹션4에 설명된 Base64 버전을 나타냅니다. Base64는 아래 알파벳을 사용하여 64진수를 표현하고 `=`를 패딩 문자로 사용합니다.
```
section4 에서 문장이 끊어지면 어디의 섹션4인지 잘 모를 거 같아 앞 문장에 붙여주는 게 좋을 거 같습니다.

2023-09-07 13:34 UTC, pje1740 commented on files/ko/glossary/base64/index.md
> +Base64 인코딩 체계는 일반적으로 ASCII 텍스트만 처리할 수 있는 미디어(또는 여전히 임의의 이진 데이터를 허용하지 않는 일부 ASCII 상위 집합)를 통해 저장하거나 전송하기 위해 이진 데이터를 인코딩하는 데 사용됩니다. 이렇게 하면 전송 중에 데이터가 수정되지 않고 그대로 유지됩니다. Base64의 일반적인 애플리케이션은 다음과 같습니다.
```suggestion
Base64 인코딩 체계는 일반적으로 ASCII 텍스트만 처리할 수 있는 미디어(또는 여전히 임의의 이진 데이터를 수용하기에 부족한 일부 ASCII 상위 집합)를 통해 저장하거나 전송하기 위해 이진 데이터를 인코딩하는 데 사용됩니다. 이렇게 하면 전송 중에 데이터가 수정되지 않고 그대로 유지됩니다. Base64의 일반적인 애플리케이션은 다음과 같습니다.
```
falls short of 라고 하면 무언가 부족하다, 라는 의미로 보여 제안 드려봅니다! 편하게 의견 주세요!

2023-09-07 13:34 UTC, pje1740 commented on files/ko/glossary/base64/index.md
> +이는 문자열이나 파일의 Base64 버전이 일반적으로 소스보다 약 3배 더 크다는 것을 의미합니다(정확한 크기 증가는 문자열의 절대 길이, 길이를 3으로 나눈 나머지 값, 패딩 문자 사용 여부 등 다양한 요인에 따라 달라집니다).
```suggestion
이는 문자열이나 파일의 Base64 버전이 일반적으로 원본 대비 3분의1 만큼 더 크다는 것을 의미합니다(정확한 크기 증가는 문자열의 절대 길이, 길이를 3으로 나눈 나머지 값, 패딩 문자 사용 여부 등 다양한 요인에 따라 달라집니다).
```
위의 내용을 살펴보면 기존 3바이트가 base64에서 4바이트가 되고 있고, third라 하면 1/3 을 의미해서 수정이 필요할 거 같습니다!

2023-09-07 13:34 UTC, pje1740 commented on files/ko/glossary/base64/index.md
> +Alternatively, asynchronous conversion between base64 data URLs is possible natively within the web platform via the [`FileReader`](/en-US/docs/Web/API/FileReader) and [`fetch`](/en-US/docs/Web/API/F
```suggestion
Alternatively, asynchronous conversion between base64 data URLs is possible natively within the web platform via the [`FileReader`](/en-US/docs/Web/API/FileReader) and [`fetch`](/en-US/docs/Web/API/Fetch_API) APIs:
```
원문이 삭제되지 않았습니다!

2023-09-07 16:20 UTC, IMHOJEONG commented on files/ko/glossary/base64/index.md
> +**Base64**는 이진 데이터를 기수-64 표현으로 변환하여 {{glossary("ASCII")}} 문자열 형식으로 나타내는 유사한 [이진 데이터를 텍스트로 인코딩](https://en.wikipedia.org/wiki/Binary-to-text_encoding)하는 구성표의 그룹입니다. 'Base64'라는 용어는 특정 [MIME 콘텐츠 전송 인코딩]
위키백과의 문서에서 구성표 안에 하나를 가리키고 싶어서 사용했다고 이해했었는데,
'방식'으로 변경도 좋아보입니다.

2023-09-07 16:23 UTC, IMHOJEONG commented on files/ko/glossary/base64/index.md
> +Alternatively, asynchronous conversion between base64 data URLs is possible natively within the web platform via the [`FileReader`](/en-US/docs/Web/API/FileReader) and [`fetch`](/en-US/docs/Web/API/F
앗 죄송합니다.

2023-09-07 16:26 UTC, IMHOJEONG commented on files/ko/glossary/base64/index.md
> +Base64 인코딩 체계는 일반적으로 ASCII 텍스트만 처리할 수 있는 미디어(또는 여전히 임의의 이진 데이터를 허용하지 않는 일부 ASCII 상위 집합)를 통해 저장하거나 전송하기 위해 이진 데이터를 인코딩하는 데 사용됩니다. 이렇게 하면 전송 중에 데이터가 수정되지 않고 그대로 유지됩니다. Base64의 일반적인 애플리케이션은 다음과 같습니다.
이 부분 저는 허용하지 않는 약간 이진 데이터를 하나도 써서는 안 되는 느낌을 주고 싶어서 작성했었는데, 
혹시 수용하기에 부족한 문구도 좋지만, `이진 데이터를 사용할 수 없는` 이러한 느낌은 어떠실까요?
제가 잘못 생각하는 것일 수도 있어서, 의견 부탁드립니다~

2023-09-07 16:28 UTC, IMHOJEONG commented on files/ko/glossary/base64/index.md
> +이는 문자열이나 파일의 Base64 버전이 일반적으로 소스보다 약 3배 더 크다는 것을 의미합니다(정확한 크기 증가는 문자열의 절대 길이, 길이를 3으로 나눈 나머지 값, 패딩 문자 사용 여부 등 다양한 요인에 따라 달라집니다).
넵 맞습니다. 다시보니 3바이트에서 4바이트 => 4/3배가 되었다는 의미로 이해가 되었습니다.
피드백 감사합니다.

2023-09-07 22:38 UTC, pje1740 commented on files/ko/glossary/base64/index.md
> +Alternatively, asynchronous conversion between base64 data URLs is possible natively within the web platform via the [`FileReader`](/en-US/docs/Web/API/FileReader) and [`fetch`](/en-US/docs/Web/API/F
죄송해하시진 않으셔도 됩니다!! 😂 늘 빠른 반영 감사합니다!!

2023-09-07 22:47 UTC, pje1740 commented on files/ko/glossary/base64/index.md
> +Base64 인코딩 체계는 일반적으로 ASCII 텍스트만 처리할 수 있는 미디어(또는 여전히 임의의 이진 데이터를 허용하지 않는 일부 ASCII 상위 집합)를 통해 저장하거나 전송하기 위해 이진 데이터를 인코딩하는 데 사용됩니다. 이렇게 하면 전송 중에 데이터가 수정되지 않고 그대로 유지됩니다. Base64의 일반적인 애플리케이션은 다음과 같습니다.
falls short of 'accepting' 이라서 사용하지 못한다 보다는 원문의 느낌을 조금 더 살려보려고 했습니다.
지금 다시 찬찬히 보니 문맥상 엄밀하게 간다면 괄호 부분이 ASCII 텍스트 뒤에 붙어야 될 거 같은데 이것도 한번 다시 고민 부탁드리겠습니다!

제가 이해한 의미를 다르게 풀어보면, ASCII나 ASCII의 수퍼셋만을 처리할 수 있는 미디어에 이진 데이터를 전송하기 위해 base64가 사용되고 이런 ASCII & ASCII 의 수퍼셋은 이진 데이터를 온전히 해독하기엔 어려움이 있다, 정도인데요, 혹 다르게 이해가 되신다면 편하게 코멘트 남겨주세요!

@mdn/yari-content-ko ASCII의 수퍼셋을 사용하는 다른 예시가 생각이 잘 나지 않는데 여유 되시는 분들도 한번만 검토해주시면 감사하겠습니다!

2023-09-09 14:50 UTC, hochan222 commented on files/ko/glossary/base64/index.md
> +Base64 인코딩 체계는 일반적으로 ASCII 텍스트만 처리할 수 있는 미디어(또는 여전히 임의의 이진 데이터를 허용하지 않는 일부 ASCII 상위 집합)를 통해 저장하거나 전송하기 위해 이진 데이터를 인코딩하는 데 사용됩니다. 이렇게 하면 전송 중에 데이터가 수정되지 않고 그대로 유지됩니다. Base64의 일반적인 애플리케이션은 다음과 같습니다.
저도 동일하게 allow(허용)가 아닌 accept(수용)로 번역하는 것이 좋다고 생각합니다.

해당 문장은 `ASCII의 일부분을 포함하지만`의 의미가 포함되어 있지 않을까 생각합니다.

(or some superset of ASCII that still falls short of accepting arbitrary binary data). 
(또는 ASCII의 일부분을 포함하지만 임의의 이진 데이터를 수용하지는 못하는 몇몇 ASCII의 상위 집합). 

> ASCII의 수퍼셋을 사용하는 다른 예시

ISO-8859-1가 있습니다! ASCII는 7비트 인코딩이고 ISO-8859-1는 8비트 인코딩입니다. ISO-8859-1은 ASCII를 모두 포함하고(0x00~0x7F), 1비트만큼 더 확장(0x80~0xFF, '£'이런 문자들이 추가)되어 있는데요..! £도 ASCII 범위로 포함시켜서 나중에 디코딩 할 때, 원래 문자로 잘 디코딩 되도록 사용한다는 의미인듯합니다..!

2023-09-09 14:57 UTC, hochan222 requested changes
리뷰어님께서 리뷰주신 사항들 반영이 되지 않았는데, resolved 처리된 리뷰들이 있는듯하여 확인 한번 부탁드려요~!

2023-09-12 09:56 UTC, pje1740 approved these changes
고생하셨습니다!!
@hochan222 같이 고민해주셔서 감사합니다!

2023-09-17 10:38 UTC, hochan222 approved these changes
@pje1740 님 리뷰 머지하지 않으신 이유가 혹시 아래 사진의 이유라면 다음에는 `Dismiss review`로 제거 후 병합해주셔도 좋을듯합니다.

<img width="937" alt="image" src="https://github.com/mdn/translated-content/assets/22424891/3d7ba488-0cbc-449e-a8d5-9ad4b27d6dda">

모두 고생 많으셨습니다! 병합하겠습니다! 좋은 하루 보내세요 :)

2023-09-17 10:38 UTC, merged