[ko]: add index.md in web/glossary/bitwise_flags
mdn/translated-content pull request #15620
Opened 2023-09-04 11:37 UTC by IMHOJEONG

### Description

#15211  의 진행상황 중, `web/glossary/bitwise_flags` 부분입니다.

### Motivation

web/glossary 접근했는데, 한국어 파일은 없어서 시작하게 되었습니다.

### Additional details

### Related issues and pull requests

#14965 
#15211

2023-09-09 12:29 UTC, hochan222 requested changes
@IMHOJEONG 님 안녕하세요.

리뷰사항 하기에 남겨두었습니다.

고생 많으셨습니다. 좋은 주말 보내세요 :)

2023-09-09 12:29 UTC, hochan222 commented on files/ko/glossary/bitwise_flags/index.md
> +예를 들어, {{domxref("WebGPU API", "WebGPU API", "", "nocode")}}에서 {{domxref("GPUBuffer")}} 객체 인스턴스는 {{domxref("GPUDevice.createBuffer()")}} 메소드를 사용해 생성됩니다. 이 메서드를 호출할 때, 해당 버퍼에 다양한 허가된 사용을 활성화하는 하나 이상의
```suggestion
예를 들어, {{domxref("WebGPU API", "WebGPU API", "", "nocode")}}에서 {{domxref("GPUBuffer")}} 객체 인스턴스는 {{domxref("GPUDevice.createBuffer()")}} 메서드를 사용해 생성됩니다. 이 메서드를 호출할 때, 해당 버퍼에 다양한 허가된 사용을 활성화하는 하나 이상의 플래그가 포함된 설명자에 `usage` 속성을 정의합니다.
```

2023-09-09 12:29 UTC, hochan222 commented on files/ko/glossary/bitwise_flags/index.md
> +| 사용 플래그                    | 16진수 표현 | 십진수 해당 |
```suggestion
| 사용 플래그                    | 16진수 표현 | 10진수 변환값 |
```

2023-09-09 12:29 UTC, hochan222 commented on files/ko/glossary/bitwise_flags/index.md
> +{{domxref("GPUBuffer.usage")}} 속성을 쿼리하면, 단일 10진수가 반환됩니다. 이 단일 10진수는 다양한 사용 플래그에 대한 다양한 10진수 값의 합계입니다. 위의 예시로 돌아가서, 이전에 지정된 사용법으로 생성된 `GPUBuffer`에 대해 `GPUBuffer.usage`를 쿼리하면 다음이 반환됩니다.
```suggestion
{{domxref("GPUBuffer.usage")}} 속성을 쿼리하면, 단일 10진수가 반환됩니다. 이 단일 10진수는 다양한 사용 플래그에 대한 다양한 10진수 값의 합계입니다. 위의 예제로 돌아가서, 이전에 지정한 사용법으로 생성된 `GPUBuffer`에 대해 `GPUBuffer.usage`를 조회하면 다음과 같은 결과가 반환됩니다.
```

2023-09-11 01:46 UTC, IMHOJEONG commented on files/ko/glossary/bitwise_flags/index.md
> +**비트 플래그**는 메소드나 기타 코드 구조의 특정 사용이나 기능을 활성화하거나 비활성화하는 데 사용할 수 있는 변수 세트(일반적으로 간단한 숫자값)입니다. 비트 수준에서 작동하기 때문에 이 작업을 빠르고 효율적으로 수행할 수 있습니다. 동일한 그룹의 관련 플래그에는 일반적으로 단일 값(예. 16진수)에서 서로 다른 비트 위치를 나타내는 보색 값이 부여
괄호는 부가 설명으로 있다면 좋다고 생각했는데, 아니었군요
넵, 앞으로 괄호는 최대한 풀어서 해석하도록 하겠습니다.

2023-09-11 01:53 UTC, IMHOJEONG commented on files/ko/glossary/bitwise_flags/index.md
> +{{domxref("GPUBuffer.usage")}} 속성을 쿼리하면, 단일 10진수가 반환됩니다. 이 단일 10진수는 다양한 사용 플래그에 대한 다양한 10진수 값의 합계입니다. 위의 예시로 돌아가서, 이전에 지정된 사용법으로 생성된 `GPUBuffer`에 대해 `GPUBuffer.usage`를 쿼리하면 다음이 반환됩니다.
@hochan222 님 안녕하세요. 혹시 '쿼리'라는 단어도 '조회'라고 번역을 주로 하게 되는지 여쭈어보고 싶습니다.
다름이 아니라,  '쿼리'라는 단어도 db 쪽에서 많이 쓰는 부분으로 그대로 쿼리라고 해석을 했어서, 앞으로는 조회라고 번역하는 게 맞는 부분인지 의견이 궁금한 부분입니다.
(제 생각에는 쿼리가 조회, 삭제, 수정 등 다 포함하는 넓은 범위라고 생각이 들어서 그렇습니다) 
추가적으로, `속성을 쿼리하면` 부분도 `속성을 조회하면`으로 변경하겠습니다.

2023-09-11 03:03 UTC, hochan222 commented on files/ko/glossary/bitwise_flags/index.md
> +**비트 플래그**는 메소드나 기타 코드 구조의 특정 사용이나 기능을 활성화하거나 비활성화하는 데 사용할 수 있는 변수 세트(일반적으로 간단한 숫자값)입니다. 비트 수준에서 작동하기 때문에 이 작업을 빠르고 효율적으로 수행할 수 있습니다. 동일한 그룹의 관련 플래그에는 일반적으로 단일 값(예. 16진수)에서 서로 다른 비트 위치를 나타내는 보색 값이 부여
괄호가 남용되는 사례가 너무 많았고, 남용되지 않더라도 원문에 존재하지 않은 괄호는 가독성을 저하시키고 기여자의 의견을 작성하는 용도로 많이 사용되어서 지양하게되었습니다!

2023-09-11 03:36 UTC, IMHOJEONG commented on files/ko/glossary/bitwise_flags/index.md
> +**비트 플래그**는 메소드나 기타 코드 구조의 특정 사용이나 기능을 활성화하거나 비활성화하는 데 사용할 수 있는 변수 세트(일반적으로 간단한 숫자값)입니다. 비트 수준에서 작동하기 때문에 이 작업을 빠르고 효율적으로 수행할 수 있습니다. 동일한 그룹의 관련 플래그에는 일반적으로 단일 값(예. 16진수)에서 서로 다른 비트 위치를 나타내는 보색 값이 부여
앗 이해했습니다. 감사합니다

2023-09-17 10:04 UTC, hochan222 commented on files/ko/glossary/bitwise_flags/index.md
> +{{domxref("GPUBuffer.usage")}} 속성을 쿼리하면, 단일 10진수가 반환됩니다. 이 단일 10진수는 다양한 사용 플래그에 대한 다양한 10진수 값의 합계입니다. 위의 예시로 돌아가서, 이전에 지정된 사용법으로 생성된 `GPUBuffer`에 대해 `GPUBuffer.usage`를 쿼리하면 다음이 반환됩니다.
@IMHOJEONG 님 안녕하세요. 현재 문서에서는 말씀해주신 "원하는 조건의 데이터를 조작하는 언어의 집합"의 의미로 사용된것이 아닌 단순 조회의 의미로 사용되었습니다.

한가지를 정해두기보다는 상황에 맞게 번역하면 될듯합니다 :)

2023-09-17 10:05 UTC, hochan222 approved these changes
LGTM :)

@IMHOJEONG 님 안녕하세요. 현재 문서에서는 말씀해주신 "원하는 조건의 데이터를 조작하는 언어의 집합"의 의미로 사용된것이 아닌 단순 조회의 의미로 사용되었습니다.

한가지를 정해두기보다는 상황에 맞게 번역하면 될듯합니다 :)

2023-09-17 10:05 UTC, merged

2023-09-17 10:09 UTC, IMHOJEONG commented on files/ko/glossary/bitwise_flags/index.md
> +{{domxref("GPUBuffer.usage")}} 속성을 쿼리하면, 단일 10진수가 반환됩니다. 이 단일 10진수는 다양한 사용 플래그에 대한 다양한 10진수 값의 합계입니다. 위의 예시로 돌아가서, 이전에 지정된 사용법으로 생성된 `GPUBuffer`에 대해 `GPUBuffer.usage`를 쿼리하면 다음이 반환됩니다.
앗 넵, 이런 경우에는 굳이 정해두기보다는, 상황에 맞게 번역하면 되겠군요.
피드백 감사합니다.