[ko]: add index.md for `web/glossary/canonical_order`
mdn/translated-content pull request #15649
Opened 2023-09-05 15:38 UTC by IMHOJEONG

### Description

#15221  의 진행상황 중, `web/glossary/canonical_order` 부분입니다.

### Motivation

web/glossary 접근했는데, 한국어 파일은 없어서 시작하게 되었습니다.

### Additional details

### Related issues and pull requests

#14965 
#15221

2023-09-09 12:41 UTC, hochan222 requested changes
@IMHOJEONG 님, 안녕하세요.

리뷰내용 아래에 남겨두었습니다.

고생 많으셨습니다!

2023-09-09 12:41 UTC, hochan222 commented on files/ko/glossary/canonical_order/index.md
> +title: 표준 순서
```suggestion
title: 표준 순서 (Canonical order)
```

glossary의 경우 단어에 대한 지침이기 때문에, 단어의 번역을 원하신다면 원문 단어도 같이 작성해주는것이 좋아 보입니다.

2023-09-11 15:18 UTC, IMHOJEONG commented on files/ko/glossary/canonical_order/index.md
> +title: 표준 순서
넵 앞으로 한국어(영어)로 glossary는 통일하도록 하겠습니다.

2023-09-17 10:06 UTC, hochan222 approved these changes

2023-09-17 10:06 UTC, merged