Create index.md
mdn/translated-content pull request #15660
Opened 2023-09-06 00:32 UTC by owjs3901

### Description

document.timeline API 관련 번역을 진행하였습니다.

2023-09-06 08:57 UTC, yin1999 commented on files/ko/web/api/document/timeline/index.md
> +browser-compat: api.Document.timeline
Please remove those lines

```suggestion
```

2023-09-07 00:08 UTC, owjs3901 commented on files/ko/web/api/document/timeline/index.md
> +browser-compat: api.Document.timeline
@yin1999 Update completed!

2023-09-07 13:43 UTC, pje1740 requested changes
고생하셨습니다! 코멘트 확인만 부탁드릴게요!

2023-09-07 13:43 UTC, pje1740 commented on files/ko/web/api/document/timeline/index.md
> +이 타임라인은 각각의 `document` 마다 고유하며 {{domxref("Document.open()")}} 호출을 포함한 문서가 황성화 되어 있는 동안 유지됩니다.
```suggestion
이 타임라인은 각각의 `document` 마다 고유하며 {{domxref("Document.open()")}} 호출 또한 포함하는 문서의 생명주기 동안 유지됩니다.
```
오탈자 + call 함수가 생명주기 안에 포함된다는 맥락을 살려보고 싶어서 제안 드려봅니다! 언제든 편하게 다른 제안 주셔도 됩니다 :)

2023-09-07 13:43 UTC, pje1740 commented on files/ko/web/api/document/timeline/index.md
> +이 타임라인은 {{domxref("Performance.timeOrigin")}} 이후 시간을 밀리세컨드 단위로 연산합니다.
```suggestion
이 타임라인은 {{domxref("Performance.timeOrigin")}} 이후 시간을 밀리초 단위로 연산합니다.
```
milliseconds의 한글 표현이 있어서 제안 드립니다.

2023-09-07 23:58 UTC, owjs3901 commented on files/ko/web/api/document/timeline/index.md
> +이 타임라인은 각각의 `document` 마다 고유하며 {{domxref("Document.open()")}} 호출을 포함한 문서가 황성화 되어 있는 동안 유지됩니다.
감사합니다, 생명주기라는 표현을 어떻게 풀까 고민하다가 맞지 않는 활성화라는 표현을 써버린것 같습니다.
동의합니다.

2023-09-07 23:58 UTC, owjs3901 commented on files/ko/web/api/document/timeline/index.md
> +이 타임라인은 {{domxref("Performance.timeOrigin")}} 이후 시간을 밀리세컨드 단위로 연산합니다.
동의합니다.

2023-09-12 09:42 UTC, pje1740 approved these changes
고생하셨습니다!

2023-09-12 09:43 UTC, merged