Translate MIDIOutput
mdn/translated-content pull request #15671
Opened 2023-09-06 12:33 UTC by mikecat

### Description

MIDIOutput を新規翻訳。

### Motivation

### Additional details

### Related issues and pull requests

2023-09-10 07:28 UTC, mfuji09 requested changes
1点だけ、Middle Cの訳語について再検討いただけますか。

2023-09-10 07:28 UTC, mfuji09 commented on files/ja/web/api/midioutput/index.md
> +以下の例は、真ん中の C をすぐに MIDI チャンネル 1 に送信します。
"Middle C" は一般には「中央ハ」または「中央 C」と訳しますので、このどちらかの訳語を使用してください。
参考: https://ja.wikipedia.org/wiki/%E4%B8%AD%E5%A4%AE%E3%83%8F

2023-09-10 09:29 UTC, mikecat commented on files/ja/web/api/midioutput/index.md
> +以下の例は、真ん中の C をすぐに MIDI チャンネル 1 に送信します。
なじみのある「ド」を使った「真ん中のド」がわかりやすくといいと思います。
提示された「中央ハ」のページにも載っています。
ご検討よろしくお願いします。

2023-09-11 13:26 UTC, mfuji09 approved these changes
OKです。

2023-09-11 13:26 UTC, merged