[ko]: add index.md for `web/glossary/caret`
mdn/translated-content pull request #15693
Opened 2023-09-07 08:37 UTC by IMHOJEONG

### Description

#15221  의 진행상황 중, `web/glossary/caret` 부분입니다.

### Motivation

web/glossary 접근했는데, 한국어 파일은 없어서 시작하게 되었습니다.

### Additional details

### Related issues and pull requests

#14965 
#15221

2023-09-19 03:49 UTC, sunhpark42 commented
안녕하세요. @IMHOJEONG 님 기여감사합니다!
개인 사정으로 리뷰가 늦어져서 죄송합니다. 해당 리뷰 9/23 일 내로 리뷰 드리겠습니다!
기다려주셔서 감사합니다. 🙇‍♀️

2023-10-10 06:38 UTC, hochan222 requested changes
@IMHOJEONG 님 안녕하세요.

리뷰사항 하기에 남겨두었습니다. 고생 많으셨습니다!

2023-10-10 06:38 UTC, hochan222 commented on files/ko/glossary/caret/index.md
> +title: 캐럿
```suggestion
title: 캐럿 (Caret)
```

2023-10-10 06:38 UTC, hochan222 commented on files/ko/glossary/caret/index.md
> +**캐럿** (때때로 "텍스트 커서"라고도 함)은 텍스트 입력이 삽입될 위치를 나타내기 위해 화면에 표시되는 표시기입니다.
```suggestion
**캐럿(Caret)** (때때로 "텍스트 커서(text cursor)"라고도 함)은 텍스트 입력이 삽입될 위치를 나타내기 위해 화면에 표시되는 표시기입니다.
```

2023-10-11 09:00 UTC, hochan222 approved these changes
LGTM :)

2023-10-11 09:00 UTC, merged