[ko]: add index.md in `web/http/browser_detection_using_the_user_agent`
mdn/translated-content pull request #15733
Opened 2023-09-09 15:10 UTC by IMHOJEONG

### Description

#15393   의 진행상황 중, `web/http/browser_detection_using_the_user_agent` 부분입니다.

### Related issues and pull requests

#14965 
#15393

2023-10-10 06:31 UTC, hochan222 commented
@IMHOJEONG 님 안녕하세요. 리뷰가 지연되어서 죄송합니다. 빠른 시간안에 리뷰드릴 수 있도록 하겠습니다.

좋은 하루 보내세요! (cc. @sunhpark42 님)

2023-10-10 15:01 UTC, sunhpark42 requested changes
안녕하세요 @IMHOJEONG 님, 리뷰가 늦어져서 죄송합니다.
(다음엔 제때 리뷰 할 수 있도록 해보겠습니다..🥲)

리뷰 코멘트로 함께 남겨두었습니다. 확인 부탁드립니다.

기여 감사합니다.🙇‍♀️

2023-10-11 11:33 UTC, IMHOJEONG commented on files/ko/web/http/browser_detection_using_the_user_agent/index.md
> +다양한 웹 페이지나 서비스를 다양한 브라우저에 제공하는 것은 일반적으로 좋지 않은 생각입니다. 웹은 사용하는 브라우저나 장치에 관계없이 모든 사람이 접근할 수 있도록 만들어졌습니다. 특정 브라우저를 대상으로 하기보다는 기능의 가용성을 기반으로 웹사이트를 점진적으로 개선하도록 웹사이트를 개발하는 방법이 있습니다.
넵. 다양한 이라는 단어가 반복되었었는데, 이전보다 훨씬 자연스러운 번역인 부분이라고 생각이 듭니다.

2023-10-11 11:53 UTC, IMHOJEONG commented on files/ko/web/http/browser_detection_using_the_user_agent/index.md
> +할 수 있는 가장 간단한 방법은 화면 크기에 따라 콘텐츠를 이동하는 모든 코드를 페이지가 로드될 때와 그 후의 각 [크기 조정](/ko/docs/Web/API/Window/resize_event) 이벤트에서 호출되는 단일 함수로 분리하는 것입니다. 페이지의 새 레이아웃을 결정하기 전에 이 레이아웃 함수로 계산된 양이 많은 경우 이벤트 리스너가 자주 호출되
> resize 는 이벤트의 고유명이기 때문에 번역하지 않아도 될 것이라고 생각해서 

이 방향 좋은 거 같습니다. 지금 보니 크기 조정이라고 하면, 일반적으로 낯설다고 생각할 수 있겠네요

2023-10-11 12:01 UTC, IMHOJEONG commented on files/ko/web/http/browser_detection_using_the_user_agent/index.md
> +> **참고:** 다시 반복할 가치가 있습니다. 사용자 에이전트 스니핑을 사용하는 것은 거의 좋은 생각이 아닙니다. 문제를 해결하기 위해 거의 항상 더 좋고 더 광범위하게 호환되는 방법을 찾을 수 있습니다!
앗 저도 괜찮다고 생각합니다. 아래 링크를 찾아보니
http://hacks.mozilla.or.kr/2013/10/user-agent-detection-history-and-checklist/
혹시 `탐지`는 어떠실까요?

2023-10-16 10:19 UTC, sunhpark42 commented on files/ko/web/http/browser_detection_using_the_user_agent/index.md
> +> **참고:** 다시 반복할 가치가 있습니다. 사용자 에이전트 스니핑을 사용하는 것은 거의 좋은 생각이 아닙니다. 문제를 해결하기 위해 거의 항상 더 좋고 더 광범위하게 호환되는 방법을 찾을 수 있습니다!
탐지좋습니다! 수정해주시면 바로 확인하도록 하겠습니다.🙇‍♀️

2023-10-16 11:16 UTC, IMHOJEONG commented on files/ko/web/http/browser_detection_using_the_user_agent/index.md
> +> **참고:** 다시 반복할 가치가 있습니다. 사용자 에이전트 스니핑을 사용하는 것은 거의 좋은 생각이 아닙니다. 문제를 해결하기 위해 거의 항상 더 좋고 더 광범위하게 호환되는 방법을 찾을 수 있습니다!
@sunhpark42 님 안녕하세요 
탐지로 수정해서 반영하겠습니다.

2023-10-16 12:18 UTC, sunhpark42 approved these changes
안녕하세요 @IMHOJEONG 님, 수정사항 반영 확인했습니다!
빠른 반영 감사드립니다.
추가로 수정 할 부분은 없을 것 같아 머지하겠습니다.
감사합니다~! 👍👍

2023-10-25 01:41 UTC, wisedog commented
> 안녕하세요 @IMHOJEONG 님, 수정사항 반영 확인했습니다! 빠른 반영 감사드립니다. 추가로 수정 할 부분은 없을 것 같아 머지하겠습니다. 감사합니다~! 👍👍

머지를 안하신듯 하여 제가 머지하겠습니다.

2023-10-25 01:41 UTC, merged

2023-10-25 04:45 UTC, sunhpark42 commented
앗 머지가 안되어있었네요. @wisedog 님 확인 및 머지 감사합니다. 🙇‍♀️🙇‍♀️