[ko]: revise index.md in `web/glossary/character_set`
mdn/translated-content pull request #15751
Opened 2023-09-10 09:23 UTC by IMHOJEONG

### Description

#15221  의 진행상황 중, `web/glossary/character_set` 부분입니다.

### Related issues and pull requests

#14965 
#15221

2023-09-10 10:35 UTC, SnowMarble commented on files/ko/glossary/character_set/index.md
> +title: 문자 집합
```suggestion
title: 문자 집합 (Character set)
```
이전 번역도 모두 `한글 (영어)` 포멧으로 수정해야겠어요.

2023-09-10 13:02 UTC, IMHOJEONG commented on files/ko/glossary/character_set/index.md
> +title: 문자 집합
@SnowMarble 님 안녕하세요
넵 그래야 할 거 같아요
앞으로의 PR은 제목에 한글 (영어) 포맷으로 하고, 이전에 올렸던 PR들은 다른 PR에서 수정하는 것은 어떻게 생각하시나요?

2023-09-10 13:03 UTC, SnowMarble commented on files/ko/glossary/character_set/index.md
> +title: 문자 집합
네, 큰 문제는 아니니 나중에 일괄적으로 수정해도 괜찮을것 같습니다 :)

2023-09-17 15:09 UTC, yechoi42 requested changes
문서를 업데이트 해주실 때 전반적으로 확인해주시면 더 좋을 듯합니다 :) 기존 문서의 문제인데요, 14 라인의 문장만 어투가 다르니 확인 부탁드립니다.

2023-09-17 16:10 UTC, IMHOJEONG commented
@yechoi42 님 안녕하세요
앗 그러네요. 넵, 번역할 때, 기존 번역 글도 더 꼼꼼히 보겠습니다.

2023-09-25 10:32 UTC, yechoi42 approved these changes
기여 감사합니다!

2023-09-25 10:32 UTC, merged