[ko]: add index.md for `web/glossary/cipher`
mdn/translated-content pull request #15761
Opened 2023-09-10 15:10 UTC by IMHOJEONG

### Description

#15221  의 진행상황 중, `web/glossary/cipher` 부분입니다.

### Related issues and pull requests

#14965 
#15221

2023-09-20 10:07 UTC, pje1740 requested changes
소소한 수정사항 하나만 확인 부탁드려요! 고생하셨습니다! ㅎㅎ

2023-09-20 10:07 UTC, pje1740 commented on files/ko/glossary/cipher/index.md
> +{{glossary("cryptography", "암호학")}}에서, **암호**는{{glossary("Plaintext", "평문")}}을 읽을 수 없게 {{glossary("encryption", "암호화")}}하고, 다시 {{glossary("decryption", "복호화")}}할 수 있는 알고리즘입니다.
```suggestion
{{glossary("cryptography", "암호학")}}에서, **암호**는 {{glossary("Plaintext", "평문")}}을 읽을 수 없게 {{glossary("encryption", "암호화")}}하고, 다시 {{glossary("decryption", "복호화")}}할 수 있는 알고리즘입니다.
```
띄어쓰기 누락입니다!

2023-09-20 13:04 UTC, IMHOJEONG commented on files/ko/glossary/cipher/index.md
> +{{glossary("cryptography", "암호학")}}에서, **암호**는{{glossary("Plaintext", "평문")}}을 읽을 수 없게 {{glossary("encryption", "암호화")}}하고, 다시 {{glossary("decryption", "복호화")}}할 수 있는 알고리즘입니다.
넵 바로 수정하겠습니다.

2023-09-23 00:02 UTC, pje1740 approved these changes
고생하셨습니다!!

2023-09-23 00:02 UTC, merged