Translate BluetoothCharacteristicProperties
mdn/translated-content pull request #15798
Opened 2023-09-12 12:43 UTC by mikecat

### Description

`BluetoothCharacteristicProperties` を新規翻訳。

### Motivation

### Additional details

### Related issues and pull requests

2023-09-17 14:22 UTC, mfuji09 requested changes
1件だけ、用語を再検討願います。

2023-09-17 14:22 UTC, mfuji09 commented on files/ja/web/api/bluetoothcharacteristicproperties/index.md
> +  - : キャラクタリスティックの値のアクノーレッジメントありのインジケーションが許可されているならば `true` となる `boolean` 値を返します。
「アクノーレッジメント」よりも「アクノリッジメント」と表記する方が一般的なので、そう表記してください。

2023-09-18 04:22 UTC, mikecat commented on files/ja/web/api/bluetoothcharacteristicproperties/index.md
> +  - : キャラクタリスティックの値のアクノーレッジメントありのインジケーションが許可されているならば `true` となる `boolean` 値を返します。
修正しました。

2023-09-18 15:45 UTC, mfuji09 approved these changes
OKです。

2023-09-18 15:45 UTC, merged