[ko] ko_gram_err_fix
mdn/translated-content pull request #15827
Opened 2023-09-14 07:33 UTC by seok-pyo

javascript/first_steps/silly_story_generator

### Description

몇 개의 맞춤법 교정 입니다.
simple grammar correction.

2023-10-10 06:15 UTC, hochan222 commented
@seok-pyo 님 안녕하세요. 리뷰가 지연되어서 죄송합니다. 빠른 시간안에 리뷰드릴 수 있도록 하겠습니다.

좋은 하루 보내세요!

2023-10-10 07:48 UTC, seok-pyo commented
@hochan222 감사합니다! 😊

2023-10-10 13:50 UTC, sunhpark42 requested changes
안녕하세요. @seok-pyo 님, 리뷰가 늦어서 죄송합니다.
코멘트 남겨둔 내용 확인 부탁드립니다. 요약하면 아래와 같습니다.

1. 원문에 존재하지 않는 괄호 내용 삭제 부탁드립니다.
2. 번역한 단어 옆에 필요한 경우가 아니라면 괄호 및 영문 표기 병기된 부분 삭제 부탁드립니다.
3. 번역되지 않은 단어가 있습니다. 랜덤 -> 임의, 라인 -> 줄 로 변경 부탁드립니다. 

번역에 기여 감사합니다. 좋은하루 되세요🙇‍♀️

2023-10-10 13:50 UTC, sunhpark42 commented on files/ko/learn/javascript/first_steps/silly_story_generator/index.md
> +1. `newStory`라 불리는 새 변수를 만들고, 이것의 값(value)를 `storyText` 와 똑같이 설정하세요. 이것은 버튼을 누르고 함수가 수행(run)될 때 마다 새 이야기('story')가 랜덤하게 만들어 질 수 있게 합니다. `storyText`를 직접 변경했다면, 새로운 이야기('story')를 한번만 만들 수 있습니다(함수를 통해서
```suggestion
1. `newStory`라 불리는 새 변수를 만들고, 이것의 값을 `storyText` 와 똑같이 설정하세요. 이것은 버튼을 누르고 함수가 수행될 때 마다 새 이야기('story')가 임의로 만들어 질 수 있게 합니다. `storyText`를 직접 변경했다면, 새로운 이야기('story')를 한번만 만들 수 있습니다.
```
와 같이 변경 제안 드립니다.
번역시에는 MDN 원문 형태를 따르는 것을 지침으로 하고 있어 괄호 안 내용 삭제 부탁드립니다. 🙇‍♀️
추가로 `랜덤` 키워드 -> `임의` 로 변경 부탁드려요

2023-10-10 13:50 UTC, sunhpark42 commented on files/ko/learn/javascript/first_steps/silly_story_generator/index.md
> +2. 세 개의 새로운 변수 `xItem`, `yItem`, 와 `zItem` 를 만들고 이 세 개의 변수는 `randomValueFromArray()` 를 반환 결과인 세개의 배열과 같도록 만듭니다(각 경우의 호출 결과는 각 배열에 임의의 아이템). 예를 들어 `randomValueFromArray(insertX)`함수를 호출하면 `insertX` 에서
```suggestion
2. 세 개의 새로운 변수 `xItem`, `yItem`, 와 `zItem` 를 만들고 이 세 개의 변수를 `randomValueFromArray()` 의 반환 결과인 세개의 배열과 같도록 만듭니다(각 경우의 호출 결과는 각 배열에 임의의 아이템이 됩니다.). 예를 들어 `randomValueFromArray(insertX)`에 의해 작성된 `insertX` 에서 하나의 문자열을 임의로 반환하는 함수를 얻고, 호출할 수 있습니다.
```

2023-10-10 13:50 UTC, sunhpark42 commented on files/ko/learn/javascript/first_steps/silly_story_generator/index.md
> +3. 그 다음으로 `newStory` 문자열에 있는 세 개의 placeholders— `:insertx:`, `:inserty:`, `:insertz:` —저장된 `xItem`, `yItem`와 `zItem` 문자열을 이용하여 로 변환하세요. 여기서 특정 문자열 함수가 도움될 것입니다. 이 함수는 각 경우에 `newStory`와 같게되며(대입), 호출 시
`문자열을 이용하여 로 변환하세요` 부분 변환 중 잘못 된 것 같아 코멘트 남깁니다.

2023-10-10 13:50 UTC, sunhpark42 commented on files/ko/learn/javascript/first_steps/silly_story_generator/index.md
> +3. 그 다음으로 `newStory` 문자열에 있는 세 개의 placeholders— `:insertx:`, `:inserty:`, `:insertz:` —저장된 `xItem`, `yItem`와 `zItem` 문자열을 이용하여 로 변환하세요. 여기서 특정 문자열 함수가 도움될 것입니다. 이 함수는 각 경우에 `newStory`와 같게되며(대입), 호출 시
```suggestion
3. 그 다음으로 `newStory` 문자열에 있는 세 개의 placeholders— `:insertx:`, `:inserty:`, `:insertz:` —저장된 `xItem`, `yItem`와 `zItem` 문자열을 이용하여 로 변환하세요. 여기서 특정 문자열 함수가 도움될 것입니다. 이 함수는 각 경우에 `newStory`와 같게되며, 호출 시 마다 `newStory` 의 원래 값과 동일하지만 대체 될 수 있습니다. 그러므로 버튼이 눌러질때마다, 이 placeholder는 꾸며진 문자열로 랜덤하게 교체됩니다. 추가적인 힌트로, 이 문제의 함수는 하위 문자열에서 찾은 첫번째 인스턴스만 변경하므로, 두번 이상 이 함수를 호출해야 할 수도 있습니다.
```
위와 동일하게, 원문 기준으로 번역 부탁드립니다.

2023-10-10 13:50 UTC, sunhpark42 commented on files/ko/learn/javascript/first_steps/silly_story_generator/index.md
> +5. 두번째 `if` 블록에서는 `uk` 라디오 버튼이 선택되었는지 확인합시다. `uk` 라디오 버튼이 눌려졌다면, 이야기('story') 상의 무게('weight')와 온도('temperature') 값 들인 파운드('pounds')와 화씨온도(Fahrenheit) 를 'stones'와 섭씨온도('centigrade')를 바꾸어야 합니다. 필요한 것은
('story'), ('wieght') 와 같은 괄호 안 내용 삭제 부탁드립니다.

2023-10-10 13:50 UTC, sunhpark42 commented on files/ko/learn/javascript/first_steps/silly_story_generator/index.md
> +5. 두번째 `if` 블록에서는 `uk` 라디오 버튼이 선택되었는지 확인합시다. `uk` 라디오 버튼이 눌려졌다면, 이야기('story') 상의 무게('weight')와 온도('temperature') 값 들인 파운드('pounds')와 화씨온도(Fahrenheit) 를 'stones'와 섭씨온도('centigrade')를 바꾸어야 합니다. 필요한 것은
해당 가이드(https://github.com/mdn/translated-content/pull/2747#issuecomment-964241518)에 따라 쌍점(':') 제거 부탁드립니다. 
```suggestion
5. 두번째 `if` 블록에서는 `uk` 라디오 버튼이 선택되었는지 확인합시다. `uk` 라디오 버튼이 눌려졌다면, 이야기('story') 상의 무게('weight')와 온도('temperature') 값 들인 파운드('pounds')와 화씨온도(Fahrenheit) 를 'stones'와 섭씨온도('centigrade')를 바꾸어야 합니다. 필요한 것은 아래와 같습니다
```

2023-10-10 13:50 UTC, sunhpark42 commented on files/ko/learn/javascript/first_steps/silly_story_generator/index.md
> +   3. `temperature` 변수를 정의하는 라인에서는, 94를 화씨(Fahrenheit) 94도를 섭씨온도(centigrade)로 변환합니다. 변환 결과값을 `Math.round()` 를 실행한 결과값 끝에 `' centigrade'`을 결합합니다(문자열 더하기 연산 또는 concat())
```suggestion
   3. `temperature` 변수를 정의하는 줄에서는, 94를 화씨(Fahrenheit) 94도를 섭씨온도(centigrade)로 변환합니다. 변환 결과값을 `Math.round()` 를 실행한 결과값 끝에 `' centigrade'`을 결합합니다.
```
* 라인 -> 줄 로 변경 부탁드립니다.
* 원문에 없는 괄호 내용 삭제 부탁드립니다.

2023-10-11 04:04 UTC, seok-pyo commented
안녕하세요, @sunhpark42님. 코멘트 주신 부분 반영해서 커밋해 두었습니다! 제가 처음이어서 혹시 추가로 필요한 것 있다면 말씀해주세요..! 감사합니다 😊

2023-10-16 10:18 UTC, sunhpark42 requested changes
안녕하세요 @seok-pyo 님, 리뷰 반영감사합니다. 
단어 표기중 원문 표기를 하지 않아도 될 것 같은 부분들이 있어 코멘트 추가로 남겼습니다.
확인 부탁드립니다.

기여 감사합니다:) 🙇‍♀️

2023-10-16 10:18 UTC, sunhpark42 commented on files/ko/learn/javascript/first_steps/silly_story_generator/index.md
> +5. 두번째 `if` 블록에서는 `uk` 라디오 버튼이 선택되었는지 확인합시다. `uk` 라디오 버튼이 눌려졌다면, 이야기 상의 무게와 온도('temperature') 값 들인 파운드('pounds')와 화씨온도(Fahrenheit)를 스톤('stone')과 섭씨온도('centigrade')로 바꾸어야 합니다. 필요한 것은 아래와 같습니다.
이 부분 단어에서 괄호안의 값이 들어가지 않아도 될 것 같습니다~
(ex, 온도 값들인 파운드와 화씨온도를 스톤과 섯씨온도로 바꾸어야합니다.)

2023-10-16 10:18 UTC, sunhpark42 commented on files/ko/learn/javascript/first_steps/silly_story_generator/index.md
> +   3. `temperature` 변수를 정의하는 줄에서는, 94를 화씨(Fahrenheit) 94도를 섭씨온도(centigrade)로 변환합니다. 변환 결과값을 `Math.round()` 를 실행한 결과값 끝에 `' centigrade'`을 결합합니다.
위와 동일한 리뷰입니다. 괄호안의 원어 표기는 하지 않아도 될 것 같습니다~

2023-10-17 03:49 UTC, seok-pyo commented
@sunhpark42 님, 리뷰 반영해 두었습니다. 리뷰 감사드립니다! ☺️

2023-10-25 12:47 UTC, seok-pyo commented on files/ko/learn/javascript/first_steps/silly_story_generator/index.md
> +5. 두번째 `if` 블록에서는 `uk` 라디오 버튼이 선택되었는지 확인합시다. `uk` 라디오 버튼이 눌려졌다면, 이야기 상의 무게와 온도('temperature') 값 들인 파운드('pounds')와 화씨온도(Fahrenheit)를 스톤('stone')과 섭씨온도('centigrade')로 바꾸어야 합니다. 필요한 것은 아래와 같습니다.
@sunhpark42 님, 리뷰 반영해 두었습니다. 확인 부탁드립니다! :)

2023-10-25 12:48 UTC, seok-pyo commented on files/ko/learn/javascript/first_steps/silly_story_generator/index.md
> +   3. `temperature` 변수를 정의하는 줄에서는, 94를 화씨(Fahrenheit) 94도를 섭씨온도(centigrade)로 변환합니다. 변환 결과값을 `Math.round()` 를 실행한 결과값 끝에 `' centigrade'`을 결합합니다.
리뷰 반영해 두었습니다. 확인 부탁드립니다! :)

2023-10-27 06:00 UTC, sunhpark42 approved these changes
안녕하세요 @seok-pyo 님 확인이 늦었습니다.
수정사항 반영해주신 부분 확인했고, 추가 수정사항 없을 것 같아 머지하겠습니다.
기여 감사합니다:)

2023-10-27 06:00 UTC, merged