[ko]: add index.md for `web/glossary/code_point`
mdn/translated-content pull request #15829
Opened 2023-09-14 08:49 UTC by IMHOJEONG

### Description

#15221  의 진행상황 중, `web/glossary/code_point` 부분입니다.

### Related issues and pull requests

#14965 
#15221

2023-09-17 10:51 UTC, hochan222 requested changes
@IMHOJEONG 님 안녕하세요.

리뷰 사항 하기에 남겨두었습니다.

고생 많으셨습니다 :)

2023-09-17 10:51 UTC, hochan222 commented on files/ko/glossary/code_point/index.md
> +UTF-8 및 UTF-16과 같은 문자 인코딩 형식은 유니코드 코드 포인트를 바이트 시퀀스로 인코딩하는 방법을 결정합니다. 다른 인코딩 형식은 동일한 코드 포인트를 다른 바이트 시퀀스로 인코딩할 수 있습니다. 예를 들어, 코드 포인트가 U+0424인 키릴 문자 "Ф"는 UTF-8에서는 `0xd0a4`로, UTF-16에서는 `0x0424`로 인코딩됩니다.
```suggestion
UTF-8 및 UTF-16과 같은 문자 인코딩 형식은 유니코드 코드 포인트를 연속된 바이트로 인코딩하는 방법을 결정합니다. 다른 인코딩 형식은 동일한 코드 포인트를 다른 연속된 바이트로 인코딩할 수 있습니다. 예를 들어, 코드 포인트가 U+0424인 키릴 문자 "Ф"는 UTF-8에서는 `0xd0a4`로, UTF-16에서는 `0x0424`로 인코딩됩니다.
```

시퀀스를 번역해도 좋을듯합니다 :)

2023-09-17 14:52 UTC, IMHOJEONG commented on files/ko/glossary/code_point/index.md
> +UTF-8 및 UTF-16과 같은 문자 인코딩 형식은 유니코드 코드 포인트를 바이트 시퀀스로 인코딩하는 방법을 결정합니다. 다른 인코딩 형식은 동일한 코드 포인트를 다른 바이트 시퀀스로 인코딩할 수 있습니다. 예를 들어, 코드 포인트가 U+0424인 키릴 문자 "Ф"는 UTF-8에서는 `0xd0a4`로, UTF-16에서는 `0x0424`로 인코딩됩니다.
더 자연스럽습니다. 피드백 감사합니다.

2023-09-21 02:22 UTC, hochan222 approved these changes
LGTM :)

2023-09-21 02:22 UTC, merged