[ko]: add index.md for `web/glossary/continuous_media`
mdn/translated-content pull request #15852
Opened 2023-09-15 01:31 UTC by IMHOJEONG

### Description

#15221  의 진행상황 중, `web/glossary/continuous_media` 부분입니다.

### Related issues and pull requests

#14965 
#15221

2023-09-17 11:03 UTC, hochan222 requested changes
@IMHOJEONG 님 안녕하세요.

리뷰사항 하기에 남겨두었습니다!

고생 많으셨습니다 :)

2023-09-17 11:03 UTC, hochan222 commented on files/ko/glossary/continuous_media/index.md
> +연속적인 미디어는 소스와 대상 사이에 타이밍 관계가 있는 데이터입니다. 연속적인 미디어의 가장 일반적인 예로는 오디오와 모션 비디오가 있습니다. 연속적인 미디어는 소스와 싱크 사이에 "긴밀한" 타이밍 관계가 있는 실시간 (대화형) 이거나, 관계가 덜 엄격한 스트리밍(재생)일 수 있습니다.
```suggestion
연속 미디어(Continuous media)란 소스와 대상(destination) 사이에 시간적인 관계가 있는 데이터를 의미합니다. 연속적인 미디어의 가장 일반적인 예로는 오디오와 모션 비디오가 있습니다. 연속적인 미디어는 소스와 대상(sink) 사이에 "엄격한" 시간적인 관계가 있는 실시간(대화형)이거나, 관계가 덜 엄격한 스트리밍(재생)일 수 있습니다.
```

(1) 타이밍 번역하면 좋을듯합니다.
(2) tight는 뒷 문장을 보아 엄격한으로 번역하는 것이 좋아 보입니다.
(3) 싱크도 대상으로 번역할 수 있는데, 이전 문장의 대상과 구분하기 위해 `대상(destination)`, `대상(sink)`
로 번역하는 것은 어떤가요?

2023-09-17 15:07 UTC, IMHOJEONG commented on files/ko/glossary/continuous_media/index.md
> +연속적인 미디어는 소스와 대상 사이에 타이밍 관계가 있는 데이터입니다. 연속적인 미디어의 가장 일반적인 예로는 오디오와 모션 비디오가 있습니다. 연속적인 미디어는 소스와 싱크 사이에 "긴밀한" 타이밍 관계가 있는 실시간 (대화형) 이거나, 관계가 덜 엄격한 스트리밍(재생)일 수 있습니다.
@hochan222 님 안녕하세요.

(1) 타이밍 => 시간적인 번역은 저도 좋다고 생각합니다!
(2) tight + 시간 단어는 빡빡한 ~~ 로 대부분 해석이 되어서, 혹시 `빡빡한` 이라는 해석은 어떠실까요?
(3) 혹시 sink는 미디어에서는 [(1)](https://learn.microsoft.com/ko-kr/windows/win32/medfound/media-sinks) 처럼 수신 객체로 번역하는 방법에 대해서 어떻게 생각하실까요? 대상보다는 좀 더 명확한 거 같다고 생각되어 제안드려봅니다!

2023-09-21 02:45 UTC, hochan222 requested changes

2023-09-21 02:45 UTC, hochan222 commented on files/ko/glossary/continuous_media/index.md
> +연속적인 미디어는 소스와 대상 사이에 타이밍 관계가 있는 데이터입니다. 연속적인 미디어의 가장 일반적인 예로는 오디오와 모션 비디오가 있습니다. 연속적인 미디어는 소스와 싱크 사이에 "긴밀한" 타이밍 관계가 있는 실시간 (대화형) 이거나, 관계가 덜 엄격한 스트리밍(재생)일 수 있습니다.
@IMHOJEONG 님 안녕하세요.

(2) 해당 문장에서 tight는 뒤의 `the relationship is less strict`의 `less strict`와 짝을 이룬다고 생각합니다. 따라서 엄격한으로 번역했는데요. 빡빡한으로 번역하더라도 뒤에 `less strict`와 번역의 결을 같이하면 좋을듯 싶습니다.

> tight + 시간 단어는 빡빡한 ~~ 로 대부분 해석이 되어서

음.. 개인의 언어적 직관에 따라 다르게 판단될 가능성이 있어 쉽게 공식적인 의견을 내지는 못하겠지만, 다만 "엄격한 시간"으로 사용하는것은 문법에 큰 문제는 없습니다. 오히려 제 직관은.. 엄격한을 빡빡한보다 더 많이 사용하는듯합니다.

- 추가시간에 엄격하다 (엄격한 추가시간)
- 게임 시간을 엄격하게 제한하다 (엄격한 게임시간 제한)
- 입장시간이 엄격하다 (엄격한 입장시간)

(3) 이 부분 또한 앞의 `대상(destination)`와 짝을 이루도록 번역을 했던것인데, 음.. 싱크라는 단어를 원래 사용하고 있는 만큼 처음 번역하신 음차(싱크)로 번역해도 좋을듯합니다.

2023-09-21 23:50 UTC, IMHOJEONG commented on files/ko/glossary/continuous_media/index.md
> +연속적인 미디어는 소스와 대상 사이에 타이밍 관계가 있는 데이터입니다. 연속적인 미디어의 가장 일반적인 예로는 오디오와 모션 비디오가 있습니다. 연속적인 미디어는 소스와 싱크 사이에 "긴밀한" 타이밍 관계가 있는 실시간 (대화형) 이거나, 관계가 덜 엄격한 스트리밍(재생)일 수 있습니다.
@hochan222 님 안녕하세요.
(2) 흠... 예시를 들어주셔서 잘 이해가 되는 거 같습니다. => `엄격한`으로 번역하겠습니다.
(3) 넵 그러면 `대상(sink)` 로 번역하겠습니다.

2023-10-07 08:31 UTC, hochan222 approved these changes
@IMHOJEONG 님, 고생 많으셨습니다~!

좋은 주말 보내세요 :)

2023-10-07 08:31 UTC, merged