[ko]: add index.md for `web/glossary/entity`
mdn/translated-content pull request #15945
Opened 2023-09-19 03:56 UTC by IMHOJEONG

### Description

#15230  의 진행상황 중, `web/glossary/entity` 부분입니다.

### Related issues and pull requests

#14965 
#15230

2023-10-10 05:29 UTC, hochan222 requested changes
@IMHOJEONG 님, 안녕하세요.

리뷰 사항 하기에 남겨두었습니다. 좋은 하루 보내세요 :)

2023-10-10 05:29 UTC, hochan222 commented on files/ko/glossary/entity/index.md
> +| "    | `&quot;`  | {{Glossary('attribute', '속성')}} 값의 시작과 끝으로 해석됩니다. |
```suggestion
| "    | `&quot;`  | {{Glossary('attribute', '특성')}} 값의 시작과 끝으로 해석됩니다. |
```

2023-10-10 05:29 UTC, hochan222 commented on files/ko/glossary/entity/index.md
> +| °    | `&deg;`   | 학위 기호로 해석됩니다.                                          |
음.. 이걸 학위 기호로 사용하나요. 당장 조사했을 때는 잘 안나오는데, 조금 더 조사해보겠습니다.

2023-10-11 12:23 UTC, IMHOJEONG commented on files/ko/glossary/entity/index.md
> +| °    | `&deg;`   | 학위 기호로 해석됩니다.                                          |
@hochan222 님 안녕하세요.
음.. 학위 기호는 뭔가 이상한 해석이네요. 죄송합니다. 
혹시 도 기호라는 해석은 어떠실까요?
https://ko.wikipedia.org/wiki/%EB%8F%84_%EA%B8%B0%ED%98%B8

2023-10-25 09:20 UTC, hochan222 commented on files/ko/glossary/entity/index.md
> +| °    | `&deg;`   | 학위 기호로 해석됩니다.                                          |
@IMHOJEONG 님 안녕하세요.

> 음.. 학위 기호는 뭔가 이상한 해석이네요. 죄송합니다.
전혀 죄송하실필요 없습니다~! 오히려 생각할거리를 주셔서 감사합니다.

> 혹시 도 기호라는 해석은 어떠실까요?
좋습니다~!

2024-03-24 10:38 UTC, hochan222 approved these changes

2024-03-24 10:38 UTC, hochan222 commented on files/ko/glossary/entity/index.md
> +| °    | `&deg;`   | 학위 기호로 해석됩니다.                                          |
```suggestion
| °    | `&deg;`   | 도 기호로 해석됩니다.                                          |
```

2024-03-24 10:44 UTC, hochan222 commented
@IMHOJEONG 님 안녕하세요.

PR이 지연되는듯하여 제가 반영 후 병합했습니다.

기여해주셔서 감사합니다. 좋은 하루 보내세요 :)

2024-03-24 10:44 UTC, merged

2024-06-09 12:35 UTC, IMHOJEONG commented
@hochan222 님 안녕하세요!
제가 개인적인 사정으로 오랜만에 확인해보네요 ㅠㅠ 
수정 및 병합해주셔서 감사합니다!