[ko]:add index.md for `web/glossary/fetch_metadata_request_header`
mdn/translated-content pull request #15965
Opened 2023-09-20 04:00 UTC by IMHOJEONG

### Description

#15231  의 진행상황 중, `web/glossary/fetch_metadata_request_header` 부분의 일부분 파일들입니다.

### Related issues and pull requests

#14965 
#15231

2023-10-09 05:41 UTC, jho2301 requested changes
변경 요청드려요 감사합니다!

2023-10-09 05:41 UTC, jho2301 commented on files/ko/glossary/fetch_metadata_request_header/index.md
> +**메타데이터 가져오기 요청 헤더**는 요청이 시작된 컨텍스트에 대한 추가 정보를 제공하는 {{Glossary("Request header", "HTTP 요청 헤더")}}입니다. 이를 통해 서버는 요청이 어디서 왔는지와 리소스를 어떻게 사용하는지에 따라 요청을 허용할지 여부를 결정할 수 있습니다.
```suggestion
**메타데이터 가져오기 요청 헤더**는 요청이 시작된 맥락에 대한 추가 정보를 제공하는 {{Glossary("Request header", "HTTP 요청 헤더")}}입니다. 이를 통해 서버는 요청이 어디서 왔는지와 리소스를 어떻게 사용하는지에 따라 요청을 허용할지 여부를 결정할 수 있습니다.
```

2023-10-09 05:41 UTC, jho2301 commented on files/ko/glossary/fetch_metadata_request_header/index.md
> +이 정보를 사용하여 서버는 {{Glossary("resource isolation policy", "리소스 격리 정책")}}을 구현할 수 있고, 이를 통해 외부 사이트에서 공유할 예정이고 적절하게 사용되는 리소스만 요청할 수 있습니다. 이 접근 방식은 {{Glossary("CSRF")}}, 교차 사이트 스크립트 포함(Cross-site Script Inc
```suggestion
이 정보를 사용하여 서버는 {{Glossary("resource isolation policy", "리소스 격리 정책")}}을 구현할 수 있고, 이를 통해 외부 사이트에서는 공유하기로 의도된, 적절하게 사용되는 리소스만 요청할 수 있습니다. 이 접근 방식은 {{Glossary("CSRF")}}, 교차 사이트 스크립트 포함(Cross-site Script Inclusion, 'XSSI'), 타이밍 공격 및 교차 출처 정보 유출(cross-origin information leaks)과 같이, 일반적인 교차 사이트 웹 취약점을 완화하는 데 도움이 될 수 있습니다.
```

2023-10-09 05:41 UTC, jho2301 commented on files/ko/glossary/fetch_metadata_request_header/index.md
> +아래 요청 헤더는 동일한 명세서에 있지 않기 때문에, '엄격히' '메타데이터 가져오기 요청 헤더'는 아니지만, 비슷하게 리소스가 사용되는 방식에 대한 컨텍스트 정보를 제공합니다.
```suggestion
아래 요청 헤더는 동일한 명세서에 있지 않기 때문에, 엄격히 '메타데이터 가져오기 요청 헤더'는 아니지만, 비슷하게 리소스가 사용되는 방식에 대한 맥락 정보를 제공합니다.
```

2023-10-09 05:41 UTC, jho2301 commented on files/ko/glossary/fetch_metadata_request_header/index.md
> +- web.dev의[메타데이터 가져오기를 사용해 웹 공격으로부터 리소스를 보호하세뇨](https://web.dev/fetch-metadata/)
오타입니다!

2023-10-10 05:22 UTC, hochan222 approved these changes
LGTM :)

2023-10-15 01:52 UTC, jho2301 approved these changes

2023-10-15 01:52 UTC, merged