[ko]: add index.md for `web/glossary/first_contentful_paint`
mdn/translated-content pull request #15971
Opened 2023-09-20 12:32 UTC by IMHOJEONG

### Description

#15231  의 진행상황 중, `web/glossary/first_contentful_paint` 부분의 일부분 파일들입니다.

### Related issues and pull requests

#14965 
#15231

2023-10-10 05:19 UTC, hochan222 approved these changes
@IMHOJEONG 님 안녕하세요.

리뷰사항 하기에 남겨두었습니다. 좋은 하루 보내세요 :)

2023-10-10 05:19 UTC, hochan222 commented on files/ko/glossary/first_contentful_paint/index.md
> +**최초 콘텐츠풀 페인트(FCP)**는 브라우저가 DOM에서 첫 번째 콘텐츠 비트를 렌더링하여, 페이지가 실제로 로드되고 있다는 첫 번째 피드백을 사용자에게 제공하는 경우입니다. The question "이러한 일이 일어나고 있나요?"라는 질문 콘텐츠가 포함된 첫 번째 페인트가 완료되면 "예"입니다.
```suggestion
**최초 콘텐츠풀 페인트 (First contentful paint, FCP)**는 브라우저가 DOM에서 콘텐츠의 첫 번째 비트를 렌더링하여, 페이지가 실제로 로드되고 있다는 첫 번째 피드백을 사용자에게 제공하는 경우입니다. The question "이러한 일이 일어나고 있나요?"라는 질문 콘텐츠가 포함된 첫 번째 페인트가 완료되면 "예"입니다.
```

1. "the first bit of content"로 상기 변경 내용이 더 적합해보이고, 더 나아가서 "처음으로 콘텐츠의 일부가 렌더링하여~"로 번역하는건 어떨지 의견드립니다.
2. 번역이 완벽하게 되지 않았습니다. "The question"

2023-10-10 05:19 UTC, hochan222 commented on files/ko/glossary/first_contentful_paint/index.md
> +'최초 콘텐츠풀 페인트 (First contentful paint, FCP)' 타임스탬프는 브라우저가 텍스트, 이미지(배경 이미지 포함), 비디오, 그려진 캔버스 또는 비어있지 않은 SVG를 처음 렌더링한 시점입니다. 이것은 iframe의 모든 콘텐츠를 제외하지만 보류 중인 웹 글꼴이 있는 텍스트를 포함합니다. 사용자가 페이지 콘텐츠를 소비하기 시작한 것
```suggestion
최초 콘텐츠풀 페인트 타임스탬프는 브라우저가 텍스트, 이미지(배경 이미지 포함), 비디오, 그려진 캔버스 또는 비어있지 않은 SVG를 처음 렌더링한 시점입니다. 이것은 iframe의 모든 콘텐츠를 제외하지만 보류 중인 웹 글꼴이 있는 텍스트를 포함합니다. 사용자가 페이지 콘텐츠를 소비하기 시작한 것은 이 시점이 처음입니다.
```

두번째 부터는 괄호 작성하지 않아도 좋을듯합니다.

2023-10-10 08:23 UTC, hochan222 requested changes
.

2023-10-10 16:46 UTC, IMHOJEONG commented on files/ko/glossary/first_contentful_paint/index.md
> +**최초 콘텐츠풀 페인트(FCP)**는 브라우저가 DOM에서 첫 번째 콘텐츠 비트를 렌더링하여, 페이지가 실제로 로드되고 있다는 첫 번째 피드백을 사용자에게 제공하는 경우입니다. The question "이러한 일이 일어나고 있나요?"라는 질문 콘텐츠가 포함된 첫 번째 페인트가 완료되면 "예"입니다.
@hochan222 님 안녕하세요
1. 넵! 의역한 부분이 더 자연스러워보입니다.
2. 수정 감사합니다.
3. https://github.com/mdn/translated-content/pull/15984#discussion_r1341947405 에서 피드백 받은 부분입니다. 
  : "이러한 일이 일어나고 있나요?"라는 질문 콘텐츠가 포함된 첫 번째 페인트가 완료되면 "예"입니다. =>  FCP 이후에 사용자는 웹 페이지가 로드되가 있다는 것을 느낄 수 있습니다. 
   라고 바꿀 생각입니다. 의견 궁금해서 여쭈어봅니다.

2023-10-29 14:08 UTC, hochan222 commented on files/ko/glossary/first_contentful_paint/index.md
> +**최초 콘텐츠풀 페인트(FCP)**는 브라우저가 DOM에서 첫 번째 콘텐츠 비트를 렌더링하여, 페이지가 실제로 로드되고 있다는 첫 번째 피드백을 사용자에게 제공하는 경우입니다. The question "이러한 일이 일어나고 있나요?"라는 질문 콘텐츠가 포함된 첫 번째 페인트가 완료되면 "예"입니다.
@IMHOJEONG 님 안녕하세요.

> 라고 바꿀 생각입니다. 의견 궁금해서 여쭈어봅니다.

네 좋아 보입니다~!

2023-10-30 03:45 UTC, IMHOJEONG commented
@hochan222 님 안녕하세요.
요새 저도 바빠서 잘 못 챙기고 있어서... 알림 주셔서 감사합니다.
확인받은 피드백 수정해서 반영해두었습니다~

2023-10-30 13:16 UTC, hochan222 approved these changes
@IMHOJEONG 님, 바쁘신 와중에 바로 커멘트 남겨주셔서 감사합니다.

리뷰가 많이 늦어서 죄송해요. 좋은 하루 보내세요 :)

2023-10-30 13:17 UTC, merged