Updating CSS Background and border main page
mdn/translated-content pull request #15976
Opened 2023-09-20 13:34 UTC by tristantheb

### Description
Updating `css_backgrounds_and_borders` main page to latest version.

2023-09-20 15:43 UTC, thomasbnt requested changes

2023-09-20 15:43 UTC, thomasbnt commented on files/fr/web/css/css_backgrounds_and_borders/index.md
> +Les propriétés de ce module vous permettent également de définir si les cellules à l'intérieur d'un [`&lt;table&gt;`](/fr/docs/Web/HTML/Element/table) doivent avoir des bordures communes ou séparées.
Hello!
Error with ```[`&lt;table&gt;`]```

2023-09-20 15:49 UTC, SphinxKnight commented on files/fr/web/css/css_backgrounds_and_borders/index.md
> +Les propriétés de ce module vous permettent également de définir si les cellules à l'intérieur d'un [`&lt;table&gt;`](/fr/docs/Web/HTML/Element/table) doivent avoir des bordures communes ou séparées.
Oops, thanks :)

2023-09-20 19:57 UTC, tristantheb commented on files/fr/web/css/css_backgrounds_and_borders/index.md
> +Les propriétés de ce module vous permettent également de définir si les cellules à l'intérieur d'un [`&lt;table&gt;`](/fr/docs/Web/HTML/Element/table) doivent avoir des bordures communes ou séparées.
Ah yep, passed over my vision xD

2023-09-20 20:02 UTC, tristantheb commented on files/fr/web/css/css_backgrounds_and_borders/index.md
> +Les propriétés de ce module vous permettent également de définir si les cellules à l'intérieur d'un [`&lt;table&gt;`](/fr/docs/Web/HTML/Element/table) doivent avoir des bordures communes ou séparées.
Fixed on next commit, thanks @thomasbnt <3

2023-09-20 21:25 UTC, thomasbnt approved these changes
Good! 🎉

2023-09-25 11:22 UTC, SphinxKnight commented
@tristantheb je me suis permis un commit pour certaines reformulations / ajustements. Je te laisse la main pour le titre notamment où j'ai préféré inclure la version anglaise vu qu'on fait ici référence au texte normatif qu'est le module de specs CSS en question.

2023-09-25 11:22 UTC, SphinxKnight approved these changes

2023-09-25 11:29 UTC, thomasbnt approved these changes

2023-09-26 17:17 UTC, merged