[ko]: add index.md for `web/glossary/grid_cell`
mdn/translated-content pull request #16017
Opened 2023-09-22 03:49 UTC by IMHOJEONG

### Description

#15232  의 진행상황 중, `web/glossary/grid_cell` 부분의 일부분 파일들입니다.

### Related issues and pull requests

#14965 
#15232

2023-10-10 04:58 UTC, hochan222 requested changes
@IMHOJEONG 님 안녕하세요.

리뷰 사항 하기에 남겨두었습니다. 고생 많으셨습니다~!

2023-10-10 04:58 UTC, hochan222 commented on files/ko/glossary/grid_cell/index.md
> +그리드 배치 방법 중 하나를 사용해 항목을 배치하지 않으면, 그리드 컨테이너의 바로 밑 자식 요소는 자동 배치 알고리즘에 의해 각 개별 그리드 셀에 하나씩 배치됩니다. 모든 요소를 담을 수 있는 충분한 셀을 만들기 위해 추가 행 또는 열 {{glossary("grid tracks", "트랙")}}이 생성됩니다.
```suggestion
그리드 배치 방법 중 하나를 사용해 항목을 배치하지 않으면, 그리드 컨테이너의 바로 밑 자식 요소는 자동 배치 알고리즘에 의해 각 개별 그리드 셀에 하나씩 배치됩니다. 모든 요소를 담을 수 있는 충분한 셀을 만들기 위해 추가 행 또는 열 {{glossary("grid tracks", "그리드 트랙")}}이 생성됩니다.
```

그리드를 넣지 않은 이유가 있을지 궁금합니다..!

2023-10-10 13:08 UTC, IMHOJEONG commented on files/ko/glossary/grid_cell/index.md
> +그리드 배치 방법 중 하나를 사용해 항목을 배치하지 않으면, 그리드 컨테이너의 바로 밑 자식 요소는 자동 배치 알고리즘에 의해 각 개별 그리드 셀에 하나씩 배치됩니다. 모든 요소를 담을 수 있는 충분한 셀을 만들기 위해 추가 행 또는 열 {{glossary("grid tracks", "트랙")}}이 생성됩니다.
빼먹은 거 같습니다. 찾아주셔서 감사합니다.

2023-10-11 08:58 UTC, hochan222 approved these changes
LGTM :)

2023-10-11 08:58 UTC, merged