[ko]: add index.md for `web/glossary/loop`
mdn/translated-content pull request #16114
Opened 2023-09-25 14:43 UTC by IMHOJEONG

### Description

#15237  의 진행상황 중, `web/glossary/loop` 부분의 일부분 파일들입니다.

### Related issues and pull requests

#14965 
#15237

2023-10-09 06:07 UTC, jho2301 submitted a review, later dismissed

2023-10-09 06:07 UTC, jho2301 commented on files/ko/glossary/loop/index.md
> +루프는 다양한 횟수만큼 명령문을 실행하는 한 가지 방법입니다. {{glossary("Recursion", "반복")}}을 사용하여 동일한 효과를 얻을 수 있는데, 특히 모든 데이터가 {{glossary("Immutable", "불변")}}이어서 카운터 변수를 업데이트할 수 없는 언어에서 반복을 통해 같은 효과를 얻을 수 있습니다.
```suggestion
루프는 여러 번 명령문을 실행하는 방법 중 하나입니다. {{glossary("Recursion", "반복")}}을 사용하여 동일한 효과를 얻을 수 있는데, 특히 모든 데이터가 {{glossary("Immutable", "불변")}}이어서 카운터 변수를 업데이트할 수 없는 언어에서 반복을 통해 같은 효과를 얻을 수 있습니다.
```

2023-10-10 02:14 UTC, hochan222 requested changes
@IMHOJEONG 님 안녕하세요.

리뷰사항 하기에 남겨두었습니다. 좋은 하루 보내세요 :)

2023-10-10 02:14 UTC, hochan222 commented on files/ko/glossary/loop/index.md
> +루프는 여러 번 명령문을 실행하는 방법 중 하나입니다. {{glossary("Recursion", "반복")}}을 사용하여 동일한 효과를 얻을 수 있는데, 특히 모든 데이터가 {{glossary("Immutable", "불변")}}이어서 카운터 변수를 업데이트할 수 없는 언어에서 반복을 통해 같은 효과를 얻을 수 있습니다.
```suggestion
루프는 여러 번 명령문을 실행하는 방법 중 하나입니다. {{glossary("Recursion", "재귀")}}를 사용하여 동일한 효과를 얻을 수 있는데, 특히 모든 데이터가 {{glossary("Immutable", "불변")}}이어서 카운터 변수를 갱신할 수 없는 언어에서 반복을 통해 같은 효과를 얻을 수 있습니다.
```

https://github.com/mdn/translated-content/pull/16235/files 에서 Recursion을 재귀로 정의했으니 재귀로 번역하는것이 좋아보입니다.

2023-10-10 12:56 UTC, IMHOJEONG commented on files/ko/glossary/loop/index.md
> +루프는 여러 번 명령문을 실행하는 방법 중 하나입니다. {{glossary("Recursion", "반복")}}을 사용하여 동일한 효과를 얻을 수 있는데, 특히 모든 데이터가 {{glossary("Immutable", "불변")}}이어서 카운터 변수를 업데이트할 수 없는 언어에서 반복을 통해 같은 효과를 얻을 수 있습니다.
넵, 수정하겠습니다. 링크 감사합니다.

2023-10-11 08:54 UTC, hochan222 approved these changes
LGTM :)

2023-10-11 08:55 UTC, merged