[ko]: add index.md for `web/glossary/mobile_first`
mdn/translated-content pull request #16138
Opened 2023-09-26 12:33 UTC by IMHOJEONG

### Description

#15238  의 진행상황 중, `web/glossary/mobile_first` 부분의 일부분 파일들입니다.

### Related issues and pull requests

#14965 
#15238

2023-10-03 01:54 UTC, wisedog requested changes
한 군데 수정 부탁드립니다.

2023-10-03 01:54 UTC, wisedog commented on files/ko/glossary/mobile_first/index.md
> +{{Glossary("progressive enhancement", "점진적인 향상")}}의 한 형태인 **모바일 우선 (Mobile first)**은 데스크톱 화면 크기에 대한 디자인 및 개발보다, 모바일 화면 크기에 대한 디자인 및 개발에 우선순위를 두는 웹 개발 및 웹 디자인 접근 방식입니다. 모바일 우선 접근 방식을 사용하는 이유는 작은 화면에서
`**` 다음에 글자가 붙어서 제대로 강조 효과가 안네요. Preview 참고부탁드립니다.

2023-10-03 11:00 UTC, IMHOJEONG commented on files/ko/glossary/mobile_first/index.md
> +{{Glossary("progressive enhancement", "점진적인 향상")}}의 한 형태인 **모바일 우선 (Mobile first)**은 데스크톱 화면 크기에 대한 디자인 및 개발보다, 모바일 화면 크기에 대한 디자인 및 개발에 우선순위를 두는 웹 개발 및 웹 디자인 접근 방식입니다. 모바일 우선 접근 방식을 사용하는 이유는 작은 화면에서
넵! 피드백 감사합니다!

2023-10-04 04:58 UTC, wisedog approved these changes

2023-10-04 04:59 UTC, merged