[ko]: add index.md for `web/glossary/minification`
mdn/translated-content pull request #16134
Opened 2023-09-26 10:32 UTC by IMHOJEONG

### Description

#15238  의 진행상황 중, `web/glossary/minification` 부분의 일부분 파일들입니다.

### Related issues and pull requests

#14965 
#15238

2023-09-27 15:15 UTC, pje1740 requested changes

2023-09-27 15:15 UTC, pje1740 commented on files/ko/glossary/minification/index.md
> +**코드 경량화(Minification)**는 브라우저에서 리소스를 처리하는 방식에 영향을 주지 않고 불필요하거나 중복되는 데이터를 제거하는 프로세스입니다.
```suggestion
**코드 경량화(Minification)** 는 브라우저에서 리소스를 처리하는 방식에 영향을 주지 않고 불필요하거나 중복되는 데이터를 제거하는 프로세스입니다.
```
띄어쓰기 확인 부탁드립니다!

2023-09-27 15:56 UTC, IMHOJEONG commented on files/ko/glossary/minification/index.md
> +**코드 경량화(Minification)**는 브라우저에서 리소스를 처리하는 방식에 영향을 주지 않고 불필요하거나 중복되는 데이터를 제거하는 프로세스입니다.
넵 감사합니다!

2023-10-04 03:43 UTC, pje1740 approved these changes

2023-10-04 03:43 UTC, merged