[ko]: add index.md for `web/glossary/namespace`
mdn/translated-content pull request #16161
Opened 2023-09-27 13:08 UTC by IMHOJEONG

### Description

#15241  의 진행상황 중, `web/glossary/namespace` 부분의 일부분 파일입니다.

### Related issues and pull requests

#14965 
#15241

2023-09-27 15:28 UTC, pje1740 requested changes
고생하셨습니다! 코멘트 몇가지만 확인 부탁드립니다!

2023-09-27 15:28 UTC, pje1740 commented on files/ko/glossary/namespace/index.md
> +운영체제에서, 디렉터리는 네임스페이스입니다. 디렉토리 내 각 파일이나 하위 디렉토리에는 고유한 이름이 존재합니다. 동일한 이름을 하위 디렉터리 전체에 걸쳐서 여러 번 사용할 수 있습니다.
```suggestion
운영체제에서, 디렉터리는 네임스페이스입니다. 디렉토리 내 각 파일이나 하위 디렉토리는 고유한 이름입니다. 동일한 이름을 하위 디렉터리 전체에 걸쳐서 여러 번 사용할 수 있습니다.
```
디렉토리나 파일이 'has' a unique name 이어서 그 자체가 고유한 이름이라고 해석하는 게 좋아보이는데 어떠실까요?

2023-09-27 15:28 UTC, pje1740 commented on files/ko/glossary/namespace/index.md
> +HTML, CSS 와 XML 기반 언어에서, 네임스페이스는 요소(또는 속성)가 속하는 명시적으로 선언되거나 암시적인 방언입니다.
```suggestion
HTML, CSS 와 XML 기반 언어에서, 네임스페이스는 요소(또는 속성)가 명시적으로, 혹은 암시적으로 속한 언어입니다.
```
여기서 dialect는 XML 기반 언어들을 의미하는 거 같은데요, 찾아보면 [HTML, XML 같은 언어의 namespace](https://www.w3.org/TR/2011/WD-html5-20110525/namespaces.html)는 html 태그의 속성으로 넣어주게 됩니다. 이걸 통해 이 문서가 어떤 문법으로 작성된 건지 추론하는 것으로 알고 있는데요 (없는 경우 작성된 태그 등을 기반으로 알아서 추론하는 거 같구요), 이 관점에서 해석을 좀 더 명확하게 해봤는데 편하게 의견 남겨주세요!

2023-09-27 16:02 UTC, IMHOJEONG commented on files/ko/glossary/namespace/index.md
> +운영체제에서, 디렉터리는 네임스페이스입니다. 디렉토리 내 각 파일이나 하위 디렉토리에는 고유한 이름이 존재합니다. 동일한 이름을 하위 디렉터리 전체에 걸쳐서 여러 번 사용할 수 있습니다.
넵! 디렉토리와 파일 자체가 고유한 이름을 가질 수 있다는 느낌으로 좋은 거 같습니다!

2023-10-02 03:01 UTC, IMHOJEONG commented on files/ko/glossary/namespace/index.md
> +HTML, CSS 와 XML 기반 언어에서, 네임스페이스는 요소(또는 속성)가 속하는 명시적으로 선언되거나 암시적인 방언입니다.
@pje1740 님 안녕하세요.
답변이 늦어진 부분 죄송합니다. 
설명 덕분에 `<html xmlns="http://www.w3.org/1999/xhtml" lang="ko">` 로 사용하는 것으로 이해하였습니다. 
넵! 저도 위처럼 해석되는 부분이 이전보다는 더욱 명확히 이해된다고 생각합니다.
수정해서 반영하겠습니다!

2023-10-03 10:51 UTC, pje1740 approved these changes

2023-10-03 10:51 UTC, merged