[ko]: add index.md for `web/glossary/payload_body`
mdn/translated-content pull request #16195
Opened 2023-09-28 12:43 UTC by IMHOJEONG

### Description

#15243  의 진행상황 중, `web/glossary/payload_body` 부분의 일부분 파일들입니다.

### Related issues and pull requests

#14965 
#15243

2023-10-10 01:33 UTC, hochan222 requested changes
LGTM :)

2023-10-10 01:33 UTC, hochan222 commented on files/ko/glossary/payload_body/index.md
> +전송 인코딩을 사용하지 않으면, '페이로드 본문(payload body)'와 '메시지 본문(message body)'은 동일합니다!
```suggestion
HTTP 메시지 **페이로드 본문(payload body)** 은 {{HTTPHeader("Transfer-Encoding", "전송 인코딩")}}이 적용되기 이전에 HTTP 메시지 본문(있는 경우)으로 전송되는 데이터의 '정보'('페이로드') 부분입니다. 전송 인코딩을 사용하지 않으면, '페이로드 본문(payload body)'와 '메시지 본문(message body)'은 동일합니다!
```

@IMHOJEONG 님 안녕하세요. 원문과 개행을 맞춰주면 좋을듯합니다.

2023-10-10 12:47 UTC, IMHOJEONG commented on files/ko/glossary/payload_body/index.md
> +전송 인코딩을 사용하지 않으면, '페이로드 본문(payload body)'와 '메시지 본문(message body)'은 동일합니다!
앗 그렇군요. 알려주셔서 감사합니다!

2023-10-11 08:53 UTC, hochan222 approved these changes
LGTM :)

2023-10-11 08:53 UTC, merged