[ko]: add index.md for `web/glossary/prefetch`
mdn/translated-content pull request #16214
Opened 2023-09-29 00:26 UTC by IMHOJEONG

### Description

#15243  의 진행상황 중, `web/glossary/prefetch` 부분의 일부분 파일들입니다.

### Related issues and pull requests

#14965 
#15243

2023-10-10 01:18 UTC, hochan222 requested changes
@IMHOJEONG 님 안녕하세요.

리뷰사항 하기에 남겨두었습니다. 좋은 하루 보내세요 :)

2023-10-10 01:18 UTC, hochan222 commented on files/ko/glossary/prefetch/index.md
> +title: 프리페치 (Prefetch)
```suggestion
title: 프리패치 (Prefetch)
```

주관적인 의견이긴하지만 "프리패치" 표기가 더 일반적인듯하여 리뷰드렸습니다. 혹시 표기를 "ㅔ"로 선택하신 이유가 있을지 궁금합니다.

2023-10-10 12:05 UTC, IMHOJEONG commented on files/ko/glossary/prefetch/index.md
> +title: 프리페치 (Prefetch)
@hochan222 님 안녕하세요.
patch vs fetch 를 한국어 표기법에서 구별하고 싶었습니다.
전자는 패치라고 자연스럽지만, fetch는 
https://ko.dict.naver.com/#/search?query=fetch
과 같이 한국어로 사전에서는 `페치`로 나와있어서 사용하게 되었습니다!

2023-10-29 14:28 UTC, hochan222 commented on files/ko/glossary/prefetch/index.md
> +title: 프리페치 (Prefetch)
@IMHOJEONG 님 안녕하세요.

이해했습니다. 주신 의견 좋아 보입니다. 추후 가이드에도 추가하도록 하겠습니다.

감사합니다!

2023-10-29 14:28 UTC, hochan222 approved these changes

2023-10-29 14:28 UTC, merged