[ko]: add index.md for `web/glossary/pop`
mdn/translated-content pull request #16212
Opened 2023-09-28 23:57 UTC by IMHOJEONG

### Description

#15243  의 진행상황 중, `web/glossary/pop` 부분의 일부분 파일들입니다.

### Related issues and pull requests

#14965 
#15243

2023-10-10 01:21 UTC, hochan222 requested changes
@IMHOJEONG 님 안녕하세요.

리뷰사항 하기에 남겨두었습니다. 고생 많으셨습니다~!

2023-10-10 01:21 UTC, hochan222 commented on files/ko/glossary/pop/index.md
> +title: 우체국 프로토콜 (Post Office Protocol, POP3)
```suggestion
title: POP3
```

2023-10-10 01:21 UTC, hochan222 commented on files/ko/glossary/pop/index.md
> +**우체국 프로토콜 (Post Office Protocol, POP3)** 은 {{glossary("TCP")}} 연결을 통해 메일 서버에서 이메일을 받기 위한 매우 일반적인 {{glossary("protocol", "프로토콜")}}입니다. POP3는 더 복잡한 구조로 인해 구현하기가 더 어려운 최신 {{Glossary("IMAP")}}와 달리 폴더를 지
```suggestion
**우체국 프로토콜 (Post Office Protocol, POP3)** 은 {{glossary("TCP")}} 연결을 통해 메일 서버에서 이메일을 받기 위한 매우 일반적인 {{glossary("protocol", "프로토콜")}}입니다. POP3는 보다 더 복잡한 구조로 인해 구현하기가 더 어려운 최신 {{Glossary("IMAP")}}와 달리 폴더를 지원하지 않습니다.
```

보다를 추가하는건 어떤가요?

2023-10-10 12:36 UTC, IMHOJEONG commented on files/ko/glossary/pop/index.md
> +**우체국 프로토콜 (Post Office Protocol, POP3)** 은 {{glossary("TCP")}} 연결을 통해 메일 서버에서 이메일을 받기 위한 매우 일반적인 {{glossary("protocol", "프로토콜")}}입니다. POP3는 더 복잡한 구조로 인해 구현하기가 더 어려운 최신 {{Glossary("IMAP")}}와 달리 폴더를 지
IMAP가 더 어렵다는 것을 강조하기에 좋은 부분인 거 같습니다.

2023-10-11 08:50 UTC, hochan222 approved these changes
LGTM :)

2023-10-11 08:50 UTC, merged