[ko]: add index.md for `web/glossary/port`
mdn/translated-content pull request #16213
Opened 2023-09-29 00:04 UTC by IMHOJEONG

### Description

#15243  의 진행상황 중, `web/glossary/port` 부분의 일부분 파일들입니다.

### Related issues and pull requests

#14965 
#15243

2023-10-10 01:19 UTC, hochan222 requested changes

2023-10-10 01:19 UTC, hochan222 commented on files/ko/glossary/port/index.md
> +For a computer connected to a network with an {{Glossary("IP address", "IP 주소")}}를 사용하여 네트워크에 연결된 컴퓨터의 경우, **포트(port)** 는 통신의 종점입니다. 포트는 숫자로 지정되고, 1024 미만의 각 포트는 기본적으로 특정 {{Glossary("protocol", "프로토콜
번역이 완벽하지 않습니다.

2023-10-10 12:01 UTC, IMHOJEONG commented on files/ko/glossary/port/index.md
> +For a computer connected to a network with an {{Glossary("IP address", "IP 주소")}}를 사용하여 네트워크에 연결된 컴퓨터의 경우, **포트(port)** 는 통신의 종점입니다. 포트는 숫자로 지정되고, 1024 미만의 각 포트는 기본적으로 특정 {{Glossary("protocol", "프로토콜
넵 찾아주셔서 감사합니다.

2023-10-25 09:06 UTC, hochan222 approved these changes

2023-10-25 09:07 UTC, merged