[ko]: add index.md for `web/glossary/promise`
mdn/translated-content pull request #16223
Opened 2023-09-29 06:57 UTC by IMHOJEONG

### Description

#15243  의 진행상황 중, `web/glossary/promise` 부분의 일부분 파일들입니다.

### Related issues and pull requests

#14965 
#15243

2023-10-10 01:11 UTC, hochan222 requested changes
@IMHOJEONG 님 안녕하세요.

리뷰사항 하기에 남겨두었습니다. 

고생 많으셨습니다. 좋은 하루 보내세요 :)

2023-10-10 01:11 UTC, hochan222 commented on files/ko/glossary/promise/index.md
> +**{{jsxref("Promise", "프로미스")}}** 는 아직 작업이 완료되지 않은 {{Glossary("function")}}에 의해 반환된 {{Glossary("object", "객체")}}입니다. Promise는 문자 그대로 Promise 객체를 통해 결과를 반환할 함수에 의해 만들어진 프로미스를 나타냅니다.
```suggestion
**{{jsxref("Promise")}}** 는 아직 작업이 완료되지 않은 {{Glossary("function", "함수")}}에 의해 반환된 {{Glossary("object", "객체")}}입니다. 프로미스는 문자 그대로 프로미스 객체를 통해 결과를 반환할 함수에 의해 만들어진 프로미스를 나타냅니다.
```

0. {{jsxref("Promise")}}는 대문자 Promise여서 번역하지 않거나 Promise 표기를 같이 하는것이 좋아보입니다.

1. {{Glossary("function")}} 만 대치어를 작성하지 않은 이유가 있을지 궁금합니다.

<img width="751" alt="image" src="https://github.com/mdn/translated-content/assets/22424891/5f26b8e0-b583-4186-908a-ffa69535d618">

- https://pr16223.content.dev.mdn.mozit.cloud/ko/docs/Glossary/Promise

2. 원문에서 프로미스는 소문자로 작성되어있는데, 다음 두개의 promise만 대문자표기와 번역을하지 않는 이유가 있을지 궁금합니다.

2023-10-10 01:11 UTC, hochan222 commented on files/ko/glossary/promise/index.md
> +호출된 함수가 작업을 {{Glossary("asynchronous", "비동기적으로")}} 완료하면 원래 호출자에게 작업이 완료되었음을 알리기 위해 해결(또는 이행 또는 완료) 핸들러라고 불리는 Promise 객체의 함수가 호출됩니다.
```suggestion
호출된 함수가 작업을 {{Glossary("asynchronous", "비동기적으로")}} 완료하면 원래 호출자에게 작업이 완료되었음을 알리기 위해 해결(또는 이행 또는 완료) 핸들러라고 불리는 프로미스 객체의 함수가 호출됩니다.
```

2023-10-10 12:10 UTC, IMHOJEONG commented on files/ko/glossary/promise/index.md
> +**{{jsxref("Promise", "프로미스")}}** 는 아직 작업이 완료되지 않은 {{Glossary("function")}}에 의해 반환된 {{Glossary("object", "객체")}}입니다. Promise는 문자 그대로 Promise 객체를 통해 결과를 반환할 함수에 의해 만들어진 프로미스를 나타냅니다.
앗 이 부분은 제가 실수하였습니다.

0. 저도 이 부분은 번역하지 않고 가는 게 맞다고 보여집니다.
1과 2는 함수 및 번역하는 방향으로 가는 게 맞습니다.

2023-10-25 09:09 UTC, hochan222 approved these changes

2023-10-25 09:09 UTC, merged