[ko]: add index.md for `web/glossary/rail`
mdn/translated-content pull request #16225
Opened 2023-09-29 07:27 UTC by IMHOJEONG

### Description

#15263  의 진행상황 중, `web/glossary/rail` 부분의 일부분 파일들입니다.

### Related issues and pull requests

#14965 
#15263

2023-10-04 03:56 UTC, pje1740 requested changes

2023-10-04 03:56 UTC, pje1740 commented on files/ko/glossary/rail/index.md
> +**RAIL**, **Response, Animation, Idle, and Load** 의 축약어, 2015년 Google Chrome 팀이 창안한 성능 모델로, 브라우저 내 사용자 경험과 성능에 중점을 두고 있습니다. RAIL의 성능 만트라()는 '사용자에게 초점을 맞추세요. 최종 목표는 사이트가 특정 장치에서 빠르게 작동하도록 만드는 것이 아니라 사
```suggestion
**RAIL** 은 **Response, Animation, Idle, and Load** 의 축약어로,  2015년 Google Chrome 팀이 창안한 브라우저 내 사용자 경험과 성능에 중점을 둔 성능 모델입니다. RAIL의 성능의 골자는 '사용자에게 초점을 맞추세요. 최종 목표는 사이트가 특정 장치에서 빠르게 작동하도록 만드는 것이 아니라 사용자를 행복하게 만드는 것'입니다. 상호 작용에는 페이지 로드, 유휴, 입력에 대한 응답, 스크롤 및 애니메이션의 4단계가 있습니다. 약어순으로 주요 원칙은 아래와 같습니다.
```

문장 순서, mantra = 골자로 번역 제안, 오탈자 수정입니다.

2023-10-04 03:56 UTC, pje1740 commented on files/ko/glossary/rail/index.md
> +  - : **1초** 이내에 대화형 콘텐츠를 제공합니다.
```suggestion
  - : **1초** 이내에 상호작용 가능한 콘텐츠를 제공합니다.
```
대화형이라는 표현이 조금 제한적인 거 같아 상호작용이라는 단어로 제안 드려봅니다!

2023-10-05 13:39 UTC, IMHOJEONG commented on files/ko/glossary/rail/index.md
> +**RAIL**, **Response, Animation, Idle, and Load** 의 축약어, 2015년 Google Chrome 팀이 창안한 성능 모델로, 브라우저 내 사용자 경험과 성능에 중점을 두고 있습니다. RAIL의 성능 만트라()는 '사용자에게 초점을 맞추세요. 최종 목표는 사이트가 특정 장치에서 빠르게 작동하도록 만드는 것이 아니라 사
@pje1740 님 안녕하세요.
혹시 골자 대신 다른 단어는 어떠실까요? 골자라는 단어가 어렵다고(?) 생각이 들어서 의견드려봅니다!
목적이나 의도와 같은 단어를 사용해도 되는지 궁금합니다.

2023-10-05 13:40 UTC, IMHOJEONG commented on files/ko/glossary/rail/index.md
> +  - : **1초** 이내에 대화형 콘텐츠를 제공합니다.
넵! 수정 사항 피드백 감사합니다.

2023-10-06 01:19 UTC, pje1740 commented on files/ko/glossary/rail/index.md
> +**RAIL**, **Response, Animation, Idle, and Load** 의 축약어, 2015년 Google Chrome 팀이 창안한 성능 모델로, 브라우저 내 사용자 경험과 성능에 중점을 두고 있습니다. RAIL의 성능 만트라()는 '사용자에게 초점을 맞추세요. 최종 목표는 사이트가 특정 장치에서 빠르게 작동하도록 만드는 것이 아니라 사
그렇다면 `핵심`은 어떨까요? 목적이나 의도도 제가 처음에 생각은 했던 단어인데요, 여기서는 어떤 행위에 대한 purpose라기 보다는, 어떠한 개념의 '중심이 되는 아이디어' 라는 뜻으로 느껴져서 (mantra가 그런 어감이기도 하구요) 제안 드려봅니다~

2023-10-07 04:43 UTC, IMHOJEONG commented on files/ko/glossary/rail/index.md
> +**RAIL**, **Response, Animation, Idle, and Load** 의 축약어, 2015년 Google Chrome 팀이 창안한 성능 모델로, 브라우저 내 사용자 경험과 성능에 중점을 두고 있습니다. RAIL의 성능 만트라()는 '사용자에게 초점을 맞추세요. 최종 목표는 사이트가 특정 장치에서 빠르게 작동하도록 만드는 것이 아니라 사
> 어떠한 개념의 '중심이 되는 아이디어' 라는 뜻으로

엇 저도 이 부분에 공감합니다. 저는 `핵심`이라는 단어 좋다고 생각이 들었습니다.
그러면 수정해서 반영하도록 하겠습니다!

2023-10-07 11:49 UTC, hochan222 approved these changes
LGTM :)

2023-10-07 13:17 UTC, pje1740 approved these changes

2023-10-07 13:17 UTC, merged