[ko]: add index.md for `web/glossary/same-origin_policy`
mdn/translated-content pull request #16268
Opened 2023-09-30 14:55 UTC by IMHOJEONG

### Description

#15264  의 진행상황 중, `web/glossary/same-origin_policy` 부분의 일부분 파일들입니다.

### Related issues and pull requests

#14965 
#15264

2023-10-04 04:08 UTC, pje1740 requested changes

2023-10-04 04:08 UTC, pje1740 commented on files/ko/glossary/same-origin_policy/index.md
> +잠재적으로 악의적인 문서를 격리하여, 가능한 공격 벡터를 줄이는 데 도움이 됩니다.
```suggestion
잠재적으로 악의적인 문서를 격리하여, 가능한 공격 경로를 줄이는 데 도움이 됩니다.
```
여기서 벡터는 공격 경로를 의미하는 거 같아 한글로 수정 제안 드립니다.

2023-10-05 13:43 UTC, IMHOJEONG commented on files/ko/glossary/same-origin_policy/index.md
> +잠재적으로 악의적인 문서를 격리하여, 가능한 공격 벡터를 줄이는 데 도움이 됩니다.
더 잘 어울리는 거 같습니다. 
피드백 감사합니다.

2023-10-06 01:20 UTC, pje1740 approved these changes

2023-10-06 01:20 UTC, merged