[ko]: add index.md for `web/glossary/type_coercion`
mdn/translated-content pull request #16405
Opened 2023-10-05 16:50 UTC by IMHOJEONG

### Description

#15265  의 진행상황 중, `web/glossary/type_coercion` 부분의 일부분 파일들입니다.

### Related issues and pull requests

#14965 
#15265

2023-10-10 00:42 UTC, hochan222 requested changes

2023-10-10 00:42 UTC, hochan222 commented on files/ko/glossary/type_coercion/index.md
> +title: 타입 강제 변환 (Type coercion)
@mdn/yari-content-ko 안녕하세요. (cc. @IMHOJEONG 님)

Type coercion이 형변환, 타입변환, 타입강제변환, 강제형변환 4가지로 번역되고 있습니다. 어떻게 번역하면 좋을지 고민이 되어 멘션드렸습니다. 

한 가지로 통일하면 좋을듯합니다. 의견 부탁드립니다. (개인적으로는 1번 좋아보입니다.)

참고차, 현재 한국 문서에는 1번과 2번이 각각 1회씩 사용되었습니다. (그외 "타입변환" 3회(파일 1곳에서 사용), "형변환" 4회(파일 4곳에서 사용))

1. 타입 강제 변환
2. 강제 형 변환
3. 강제 타입 변환

cc. https://github.com/mdn/translated-content/pull/15071

2023-10-11 23:51 UTC, pje1740 commented on files/ko/glossary/type_coercion/index.md
> +title: 타입 강제 변환 (Type coercion)
본문을 보니 type coercion의 경우 implicit 한 느낌을 살리면 좋을 거 같아 '자동 형변환'도 괜찮은 거 같네요! type casting이 조금 더 강제하는 느낌이라 type coercion에는 '강제'라는 용어가 빠져도 괜찮아 보이네요!

흥미로운(?) 논의로 보여 지나가다가 댓글 남겨봅니다.....! 🥹

2023-10-29 14:37 UTC, hochan222 commented on files/ko/glossary/type_coercion/index.md
> +title: 타입 강제 변환 (Type coercion)
@IMHOJEONG 님, @pje1740 님 답변이 늦어서 정말 죄송합니다. 의견 주셔서 감사합니다.

저도 좋아보입니다. 하기 두 가지 단어 안내서에 추가하도록 하겠습니다.

- type coercion: 자동 형변환
- type casting: 강제 형변환

좋은 하루보내세요 :)

2023-10-29 14:42 UTC, hochan222 approved these changes
@IMHOJEONG 님, 리뷰사항 반영하여 병합하겠습니다.

고생 정말 많으셨습니다. 좋은 하루 보내세요 :)

2023-10-29 14:42 UTC, hochan222 commented on files/ko/glossary/type_coercion/index.md
> +title: 타입 강제 변환 (Type coercion)
```suggestion
title: 자동 형변환 (Type coercion)
```

2023-10-29 14:42 UTC, hochan222 commented on files/ko/glossary/type_coercion/index.md
> +타입 강제 변환(Type coercion)은 한 데이터 타입에서 다른 데이터 타입(예, 문자열을 숫자로)으로 값을 자동 또는 암시적으로 변환하는 것을 의미합니다. {{Glossary("Type conversion", "형 변환")}}은 '타입 강제 변환(Type coercion)'과 유사합니다. 두 경우 모두 하나의 중요한 차이점을 제외하고, 한 데이터
```suggestion
자동 형변환(Type coercion)은 한 데이터 타입에서 다른 데이터 타입(예, 문자열을 숫자로)으로 값을 자동 또는 암시적으로 변환하는 것을 의미합니다. {{Glossary("Type conversion", "형 변환")}}은 '자동 형변환(Type coercion)'과 유사합니다. 두 경우 모두 하나의 중요한 차이점을 제외하고, 한 데이터 형식에서 다른 데이터 형식으로 값을 변환하기 때문입니다. 하나의 중요한 차이점은 '자동 형변환'은 암시적이지만, '형 변환'은 암시적이거나 명시적일 수 있습니다.
```

2023-10-29 14:42 UTC, hochan222 commented on files/ko/glossary/type_coercion/index.md
> +위의 예제에서, JavaScript는 숫자의 `9`를 문자열로 강제 변환 후, 두 값을 함께 연결하여 `59`라는 문자열을 생성합니다. JavaScript는 문자열이나 숫자 중에서 선택할 수 있었고 문자열을 사용하기로 결정했습니다.
```suggestion
위의 예제에서, JavaScript는 숫자의 `9`를 문자열로 자동 형변환 후, 두 값을 함께 연결하여 `59`라는 문자열을 생성합니다. JavaScript는 문자열이나 숫자 중에서 선택할 수 있었고 문자열을 사용하기로 결정했습니다.
```

2023-10-29 14:42 UTC, hochan222 commented on files/ko/glossary/type_coercion/index.md
> +컴파일러는 `5`를 숫자로 강제 변환하고 합의 결과를 `14`로 반환할 수 있었지만 그렇지 않았습니다. 이 결과를 반환하려면, {{jsxref("Global_Objects/Number", "Number()")}} 메서드를 사용하여 `5`를 숫자로 명시적으로 변환해야 합니다.
```suggestion
컴파일러는 `5`를 숫자로 자동 형변환하고 합의 결과를 `14`로 반환할 수 있었지만 그렇지 않았습니다. 이 결과를 반환하려면, {{jsxref("Global_Objects/Number", "Number()")}} 메서드를 사용하여 `5`를 숫자로 명시적으로 변환해야 합니다.
```

2023-10-29 14:45 UTC, merged