[ko] Work done for 'BaseAudioContext' article.
mdn/translated-content pull request #1642
Opened 2021-07-21 16:15 UTC by logic-finder

https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext

en-US 문서를 content폴더에서 가져와 전문 번역하였습니다.

※ 본 문서의 일부 내용이 한국어로 번역된 이전 버전의 AudioContext 문서에 포함되어 있었고 이에 따라 기 번역된 내용이 다소 있는 것으로 보여, 작업 중에 기존 번역을 조금 참고하였습니다. (#1627 참조)

2021-07-31 12:49 UTC, cos18 requested changes
기어 감사드립니다. 리뷰드린 내용 확인해주시고 혹시 이상한 점이 있으면 커멘트 남겨주세요!

2021-07-31 12:49 UTC, cos18 commented on files/ko/web/api/baseaudiocontext/index.html
> +<p class="summary"><span class="seoSummary"><a href="/ko/docs/Web/API/Web_Audio_API">Web Audio API</a>의 <code>BaseAudioContext</code> 인터페이스는, 각각 {{domxref("AudioContext")}} 와 {{domxref("OfflineAudioC
```suggestion
<p class="summary"><span class="seoSummary"><a href="/ko/docs/Web/API/Web_Audio_API">Web Audio API</a>의 <code>BaseAudioContext</code> 인터페이스는 {{domxref("AudioContext")}} 와 {{domxref("OfflineAudioContext")}}에 의해 표현되는 온라인과 오프라인 오디오 프로세싱 그래프에 대한 기본 정의로 작동합니다.  <code>BaseAudioContext</code>는 직접적으로 사용될 수 없습니다. 대신 위에서 언급한 두 상속 인터페이스를 통해  <code>BaseAudioContext</code>의 기능을 사용할 수 있습니다.</p>
```
쉼표 (`,`)가 문장을 읽을때 더욱 이해하기 어렵게 만들고 있습니다. 해당 내용을 제거해도 충분히 원문의 의미를 남길 수 있을 것 같습니다.
두번째 문장에서는 번역체 느낌이 나 이를 자연스럽게 수정했습니다.

2021-07-31 12:49 UTC, cos18 commented on files/ko/web/api/baseaudiocontext/index.html
> +<p><em>또한 </em>{{domxref("EventTarget")}} 인터페이스로부터의 메서드를 구현합니다.</p>
```suggestion
<p><em>또한 {{domxref("EventTarget")}} 인터페이스로부터의 메서드를 구현합니다.</em></p>
```
원문에는 해당 문장 전체에 기울림체가 적용되어있습니다

2021-07-31 12:49 UTC, cos18 commented on files/ko/web/api/baseaudiocontext/index.html
> + <dd>오디오 시간과 주파수 데이터를 드러내고 예를 들자면 데이터 시각화를 생성하는 데 사용될 수 있는 {{domxref("AnalyserNode")}}를 생성합니다.</dd>
```suggestion
 <dd>오디오 시간과 주파수 데이터를 드러내고 데이터 시각화를 생성하는 데 사용될 수 있는 {{domxref("AnalyserNode")}}를 생성합니다.</dd>
```
문장이 어색해 보여 이를 수정해보았습니다.

2021-07-31 12:49 UTC, cos18 commented on files/ko/web/api/baseaudiocontext/index.html
> + <dd>샘플이 모두 같은 값을 가지고 있는 모노럴의(한 채널의) 사운드 시그널을 계속적으로 출력하는 오디오 소스인 {{domxref("ConstantSourceNode")}} 객체를 생성합니다.</dd>
```suggestion
 <dd>샘플이 모두 같은 값을 가지고 있는 모노럴의(한 채널의) 사운드 신호를 계속적으로 출력하는 오디오 소스인 {{domxref("ConstantSourceNode")}} 객체를 생성합니다.</dd>
```

2021-07-31 12:49 UTC, cos18 commented on files/ko/web/api/baseaudiocontext/index.html
> + <dd>오디오 그래프에 예를 들자면 잔향(reverberation) 효과와 같은 콘볼루션 이펙트를 적용하기 위해 사용될 수 있는 {{domxref("ConvolverNode")}}를 생성합니다.</dd>
```suggestion
 <dd>오디오 그래프에 잔향(reverberation) 효과와 같은 콘볼루션 이펙트를 적용하기 위해 사용될 수 있는 {{domxref("ConvolverNode")}}를 생성합니다.</dd>
```

2021-07-31 12:49 UTC, cos18 commented on files/ko/web/api/baseaudiocontext/index.html
> + <dd>들어오는 오디오 시그널을 특정한 양으로 연기하기 위해 사용되는 {{domxref("DelayNode")}}를 생성합니다. 이 노드는 또한 Web Audio API 그래프에서 피드백 루프를 생성하는 데 유용합니다.</dd>
```suggestion
 <dd>들어오는 오디오 신호를 지연시키기 위해 사용되는 {{domxref("DelayNode")}}를 생성합니다. 이 노드는 Web Audio API 그래프에서 피드백 루프를 생성하는 데 유용합니다.</dd>
```
delay는 연기보단 지연이 더욱 좋은 번역인 것 같습니다.

2021-07-31 12:49 UTC, cos18 commented on files/ko/web/api/baseaudiocontext/index.html
> + <dd>음향 압축(acoustic compression)을 오디오 시그널에 적용하기 위해 사용될 수 있는 {{domxref("DynamicsCompressorNode")}}를 생성합니다.</dd>
```suggestion
 <dd>음향 압축(acoustic compression)을 오디오 신호에 적용하기 위해 사용될 수 있는 {{domxref("DynamicsCompressorNode")}}를 생성합니다.</dd>
```

2021-07-31 12:49 UTC, cos18 commented on files/ko/web/api/baseaudiocontext/index.html
> +<p>기본적인 오디오 컨텍스트 선언:</p>
```suggestion
<p>기본적인 오디오 컨텍스트 선언</p>
```
한국어로 번역하는 경우에는 `:`를 포함하는 것이 어색해 보여 이를 제거하는 것이 좋아보입니다.

2021-07-31 12:49 UTC, cos18 commented on files/ko/web/api/baseaudiocontext/index.html
> +<p>크로스 브라우저를 위한 다른 형태:</p>
```suggestion
<p>크로스 브라우저를 위한 다른 형태</p>
```

2021-08-15 14:46 UTC, hochan222 commented
15일이 경과하여, 빠른 진행을 위해 제가 merge 하겠습니다. 

기여해주셔서 감사합니다. 좋은 하루 보내세요 :)

2021-08-15 14:46 UTC, hochan222 approved these changes

2021-08-15 14:46 UTC, merged