[ko]: revise index.md `webassembly/c_to_wasm`
mdn/translated-content pull request #16462
Opened 2023-10-08 15:40 UTC by IMHOJEONG

### Description

#15856  의 진행상황 중, `webassembly/c_to_wasm` 부분의 일부분 파일들입니다.

### Related issues and pull requests

#14965 
#15856

2023-10-10 00:28 UTC, hochan222 requested changes
안녕하세요! sourceCommit만 리뷰 드립니다 🙇🙇

2023-10-10 00:28 UTC, hochan222 commented on files/ko/webassembly/c_to_wasm/index.md
> +  sourceCommit: 13080fe407c8bbba19b5d6876b4706ca59c136b4
sourceCommit이 잘못 기입된듯합니다.

<img width="1326" alt="image" src="https://github.com/mdn/translated-content/assets/22424891/229f68c0-44ff-4c09-923a-d60c340e21fa">

2023-10-10 12:32 UTC, IMHOJEONG commented on files/ko/webassembly/c_to_wasm/index.md
> +  sourceCommit: 13080fe407c8bbba19b5d6876b4706ca59c136b4
피드백 감사합니다! 수정하겠습니다.

2023-10-11 08:49 UTC, hochan222 approved these changes
LGTM :)

2023-10-11 08:49 UTC, merged