Issues/issue719/client side java script frameworks/introduction
mdn/translated-content pull request #16543
Opened 2023-10-14 08:42 UTC by gurezo

@hmatrjp @potappo @mfuji09 

### issue
- [ Introduction to client-side frameworks の翻訳 #719 ](https://github.com/mozilla-japan/translation/issues/719)  のPRです。

### translated-content
#### 以下のセクション毎にコミットしてあります。
- file add . 65794f6a20
- title, header translate 9bfeba1aa1
- A brief history translate 98f4a4912b
- What frameworks are out there? translate c39ee48ac9
- Ember translate 33fa7c1734
- Angular translate 2126d3ec6c
- Vue translate f5d1e67940
- React translate 9cf764f2a8
- Why do frameworks exist? translate 4389d38420
- The verbosity of DOM changes translate aaa03c42fa
- Another way to build UIs translate ba9cf9110e
- Other things frameworks give us translate f97940f183
- Tooling translate 17c2b2bb9f
- Compartmentalization translate d60d17723a
- Routing translate 0df13a29b9
- Things to consider when using frameworks translate eb858c3662
- Familiarity with the tool translate 9e3df9eaff
- Overengineering translate d5d55a41e3
- Larger code base and abstraction translate 7ef634fc33
- Accessibility on a framework-driven web translate ee84423be5
- How to choose a framework translate 593636af0e
- Does the framework have a strong community? translate 6122d4ec48
- Opinions on the web translate ddc5905c54
- Alternatives to client-side frameworks translate 75cb9e6602
- Content-management systems translate fbadc90ef3
- Server-side rendering translate ecf2511743
- Static site generators translate 6a8b1bc4ab
- Summary translate 2dc7699157
- 半角スペース除去、付与、typo 修正 5806dd738a
- url en-US => ja b1ccd22803
- ー 追加 2074a0d80f

2023-10-14 08:48 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.md
> +title: クライアント側フレームワークの概要
半角スペース除去 04318a9f41

2023-10-16 08:49 UTC, mfuji09 requested changes
6点について確認してください。

2023-10-16 08:49 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.md
> +これで、フレームワークの紹介は終わりになります。まだコードを教えていませんが、そもそもフレームワークを使用する理由と、フレームワークの選択方法について有益な背景を提供できたことを願っています。 1 つ目は、もっと学びたい、夢中になってみたいという気持ちが高まりました。
hopefully は最後の文まで掛かっており、「もっと学びたい、夢中になってみたいという気持ちになっていただければ幸いです」というような意味だと思います。

2023-10-16 08:49 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.md
> +        クライアントサイド JavaScript フレームワークがどのようにして存在するようになったのかを理解するには、 それによって解決される問題、どのような代替案があるのか​​、どのように対処すべきか 一つを選ぶこと。
このObjectiveは、4つの項目をそれぞれ理解するという目的だと思います。従って、「理解する」は最後に来たほうが良いと思います。
```suggestion
        クライアントサイド JavaScript フレームワークがどのようにして登場したのか、それによって何が解決されるのか、どのような代替案があるのか​​、どのように一つを選べばよいかを理解すること。
```

2023-10-16 13:19 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.md
> +これで、フレームワークの紹介は終わりになります。まだコードを教えていませんが、そもそもフレームワークを使用する理由と、フレームワークの選択方法について有益な背景を提供できたことを願っています。 1 つ目は、もっと学びたい、夢中になってみたいという気持ちが高まりました。
- まとめ修正 20aba50485

2023-10-16 13:19 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.md
> +オリジナルの [AngularJS](https://angularjs.org/)プロジェクトに取り組み、そこから学んだエヴァン・ユーは、2014年に [Vue](https://vuejs.org/) をリリースしました。Vueはビッグ4の中では最も歴史が浅いが、最近人気が急上昇しています。
- 半角スペース追加 4fdef6fe28

2023-10-16 13:19 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.md
> +現在、 JavaScript はウェブに不可欠な部分であり、[すべてのウェブサイトの 98% で使用されており](https://w3techs.com/technologies/details/cp-javascript)、ウェブは現代生活に不可欠な部分です。ユーザーは論文を書いたり、予算を管理したり、音楽をストリーミングしたり、映画を鑑賞したり、テキスト、音声、またはビデオチャットを使って遠
- であり => となり 41ffaf11b9

2023-10-16 13:19 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.md
> +1996 年に JavaScript が登場すると、それまで静的なドキュメントで構成されていたウェブに、偶発的な話題と興奮が加わりました。 ウェブは単に _ものを読む_ だけではなく、 _何かをする_ ための場所になりました。 JavaScript の人気は着実に高まりました。 JavaScript を扱う開発者は、直面した問題を解決するためのツールを作成し、**ライブラリー**と呼ばれる再利用
- ところどころの操作可能性 => ところどころの操作の可能性 bee05426bc

2023-10-16 14:20 UTC, mfuji09 approved these changes
OKです。

2023-10-16 14:20 UTC, merged