zh-ch: learn: performance: html: init translation
mdn/translated-content pull request #16548
Opened 2023-10-14 13:39 UTC by hanyujie2002

### Description

Same as title
### Motivation

Ditto
### Additional details

I don't know why but there is pre commit hook which I can't pass

```
$ git commit -m "zh-ch: learn: performance: html: init translation"
[STARTED] Preparing lint-staged...
[COMPLETED] Preparing lint-staged...
[STARTED] Running tasks for staged files...
[STARTED] .lintstagedrc.json — 1 file
[STARTED] !*.md — 0 files
[STARTED] *.md — 1 file
[SKIPPED] !*.md — no files
[STARTED] markdownlint-cli2 --fix
[COMPLETED] markdownlint-cli2 --fix
[STARTED] node ./scripts/check-url-locale.js --fix
[FAILED] node ./scripts/check-url-locale.js --fix [FAILED]
[FAILED] node ./scripts/check-url-locale.js --fix [FAILED]
[COMPLETED] Running tasks for staged files...
[STARTED] Applying modifications from tasks...
[SKIPPED] Skipped because of errors from tasks.
[STARTED] Reverting to original state because of errors...
[COMPLETED] Reverting to original state because of errors...
[STARTED] Cleaning up temporary files...
[COMPLETED] Cleaning up temporary files...

✖ node ./scripts/check-url-locale.js --fix:
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'mdast-util-from-markdown' imported from C:\Users\hanyujie2002\Documents\translated-content\scripts\check-url-locale.js
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:887:9)
    at moduleResolve (node:internal/modules/esm/resolve:936:20)
    at defaultResolve (node:internal/modules/esm/resolve:1129:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.17.1
husky - pre-commit hook exited with code 1 (error)
```

Then I bypass it by using `git commit --no-verify`

### Related issues and pull requests

Relates to #16025

2023-10-14 14:03 UTC, yin1999 commented
> I don't know why but there is pre commit hook which I can't pass

Have you ran `yarn install` to update the toolchain?

2023-10-16 05:59 UTC, hanyujie2002 commented
Sorry, 

> > I don't know why but there is pre commit hook which I can't pass
> 
> Have you ran `yarn install` to update the toolchain?

Sorry I can't configure this at the moment, maybe bypass the check directly is also ok ;)

2023-10-17 05:37 UTC, yin1999 requested changes

2023-10-17 05:37 UTC, yin1999 commented on files/zh-cn/learn/performance/html/index.md
> +详细信息请参见 web.dev 上的[浏览器级 web 图像懒加载](https://web.dev/browser-level-image-lazy-loading/)。
Could you update the url in en-US document (the previous one has been redirected)

```suggestion
详细信息请参见 web.dev 上的[浏览器级 web 图像懒加载](https://web.dev/articles/browser-level-image-lazy-loading)。
```

2023-10-17 05:37 UTC, yin1999 commented on files/zh-cn/learn/performance/html/index.md
> +详细信息请参见 web.dev 上的[视频懒加载](https://web.dev/lazy-loading-video/)。
+1

```suggestion
详细信息请参见 web.dev 上的[视频懒加载](https://web.dev/articles/lazy-loading-video)。
```

2023-10-17 05:37 UTC, yin1999 commented on files/zh-cn/learn/performance/html/index.md
> +使用 `<iframe>` 方面的最重要也是最关键的建议是：“除非你非常必要，否则不要使用嵌入式 `<iframe>`”。如果你要创建一个包含多个不同信息窗格的页面，你可能会觉得把它们分成单独的页面并加载到不同的 `<iframe>` 中是有组织性的。但是，这样做会带来一些性能和其他方面的问题：
```suggestion
使用 `<iframe>` 方面的最重要也是最关键的建议是：“除非非常必要，否则不要使用嵌入式 `<iframe>`”。如果你要创建一个包含多个不同信息窗格的页面，你可能会觉得把它们分成单独的页面并加载到不同的 `<iframe>` 中是有组织性的。但是，这样做会带来一些性能和其他方面的问题：
```

2023-10-17 05:37 UTC, yin1999 commented on files/zh-cn/learn/performance/html/index.md
> +如果必须使用 `<iframe>`，请谨慎使用。
```suggestion
如果必须使用 `<iframe>`，请保持谨慎。
```

2023-10-17 05:37 UTC, yin1999 commented on files/zh-cn/learn/performance/html/index.md
> +详情请参阅[是时候懒加载屏外 iframe 了！](https://web.dev/iframe-lazy-loading/)。
+1

```suggestion
详情请参阅[是时候延迟加载屏外 iframe 了！](https://web.dev/articles/iframe-lazy-loading)。
```

2023-10-17 05:37 UTC, yin1999 commented on files/zh-cn/learn/performance/html/index.md
> +> **注意：** 这只是一个非常简单的叙述，但可以让你了解发生的事情。
```suggestion
> **备注：** 这只是一个非常简单的叙述，但可以让你了解发生的事情。
```

2023-10-17 05:37 UTC, yin1999 commented on files/zh-cn/learn/performance/html/index.md
> +如果我们将这个 `<script>` 元素放在 `<p>` 元素之前（例如，在 {{htmlelement("head")}} 元素中），页面会抛出错误（例如，Chrome 报告到控制台上的错误为 "Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')"）。这是因为脚本依赖于 `<p>` 元
```suggestion
如果我们将这个 `<script>` 元素放在 `<p>` 元素之前（例如，在 {{htmlelement("head")}} 元素中），页面会抛出错误（例如，Chrome 报告到控制台上的错误为“Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')”）。这是因为脚本依赖于 `<p>` 元素才能正常工作，但在解析脚本时，`<p>` 元素在页面上并不存在。它尚未被渲染。
```

2023-10-17 05:37 UTC, yin1999 commented on files/zh-cn/learn/performance/html/index.md
> +这会使脚本获取与 DOM 解析并行进行，因此它会在相同的时间准备好，不会阻塞呈现，从而提高性能。
```suggestion
这会使脚本获取与 DOM 解析并行进行，因此它会在相同的时间准备好，不会阻塞渲染，从而提高性能。
```

2023-10-17 05:37 UTC, yin1999 commented on files/zh-cn/learn/performance/html/index.md
> +> **注意：** 还有另一个属性 `defer`，它会使脚本在文档解析完成之后、`DOMContentLoaded` 事件触发之前执行。这与 `async` 有类似的效果。
```suggestion
> **备注：** 还有另一个属性 `defer`，它会使脚本在文档解析完成之后、`DOMContentLoaded` 事件触发之前执行。这与 `async` 有类似的效果。
```

2023-10-17 05:37 UTC, yin1999 commented on files/zh-cn/learn/performance/html/index.md
> +处理 JavaScript 加载的另一个技巧是将脚本拆分为代码模块，并在需要时加载每个部分，而不是将所有代码放入一个巨大的脚本并在开头加载。这可以通过使用 [JavaScript 模块](/zh-CN/docs/Web/JavaScript/Guide/Modules) 来实现。阅读链接的文章以获取详细指南。
```suggestion
处理 JavaScript 加载的另一个技巧是将脚本拆分为代码模块，并在需要时加载每个部分，而不是将所有代码放入一个巨大的脚本并在开头加载。这可以通过使用 [JavaScript 模块](/zh-CN/docs/Web/JavaScript/Guide/Modules)来实现。阅读链接的文章以获取详细指南。
```

2023-10-17 05:37 UTC, yin1999 commented on files/zh-cn/learn/performance/html/index.md
> +- [预加载关键资源以提高加载速度](https://web.dev/preload-critical-assets/) web.dev（2020）
```suggestion
- [预加载关键资源以提高加载速度](https://web.dev/articles/preload-critical-assets) web.dev（2020）
```

2023-10-18 10:05 UTC, yin1999 approved these changes
Thanks

2023-10-18 10:05 UTC, merged