[JA] Translate `WebGLRenderingContext: createRenderbuffer()` and `WebGLRenderingContext: createFramebuffer()` Page
mdn/translated-content pull request #16607
Opened 2023-10-17 07:49 UTC by frodo821

I translated `WebGLRenderingContext: createRenderbuffer()` and `WebGLRenderingContext: createFramebuffer()` page from en-US into Japanese.

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-10-21 15:23 UTC, mfuji09 requested changes
2点の修正をお願いします。
片方の記事にのみコメントを入れていますが、同様の修正をもう一方の記事にも行ってください。

2023-10-21 15:23 UTC, mfuji09 commented on files/ja/web/api/webglrenderingcontext/createframebuffer/index.md
> +## 仕様策定状況
見出しを外部リンクで使用することがあらうので、この見出しは「仕様書」に統一してください。
「ブラウザーの互換性」「関連情報」についても同じです。

2023-10-21 15:23 UTC, mfuji09 commented on files/ja/web/api/webglrenderingcontext/createframebuffer/index.md
> +### フレームバッファを作成する
buffer は er で終わるので、「バッファー」のように長音をつけてください。

2023-10-30 07:57 UTC, mfuji09 commented
@frodo821 さん
本件、このまま続けられますか？
このまま1週間以上レスポンスがない場合は、他の方に引き継いでいただく可能性があります。

2023-11-01 01:31 UTC, frodo821 commented
@mfuji09 
> @frodo821 さん 本件、このまま続けられますか？ このまま1週間以上レスポンスがない場合は、他の方に引き継いでいただく可能性があります。

対応しました

2023-11-01 01:33 UTC, frodo821 commented
@mfuji09 
> @frodo821 さん 本件、このまま続けられますか？ このまま1週間以上レスポンスがない場合は、他の方に引き継いでいただく可能性があります。

対応しました

2023-11-01 13:23 UTC, mfuji09 approved these changes
OKです。ありがとうございました。

2023-11-01 13:23 UTC, merged