chore(pt-br): replace old-style specification tables part 7
mdn/translated-content pull request #16610
Opened 2023-10-17 11:57 UTC by yin1999

### Description

- replace old-style specification tables
- replace `{{SpecName}}` macro calls

### Related issues and pull requests

continue: #16454

2023-10-20 13:22 UTC, yin1999 commented on files/pt-br/glossary/css_selector/index.md
> +[Selectors Level 3](https://drafts.csswg.org/selectors-3/)
If the macro call is not in a specification table, just replace it with the corresponding url. For the rest of content, follow the rule

2023-10-20 13:22 UTC, yin1999 commented on files/pt-br/web/javascript/reference/global_objects/function/arguments/index.md
> +Not part of any standard.
It's better to localize this, but I can't speak brazilian portuguese. Feel free to modify this.

2023-11-05 23:21 UTC, josielrocha commented on files/pt-br/web/javascript/reference/global_objects/function/arguments/index.md
> +Not part of any standard.
```suggestion
Não faz parte de nenhuma especificação.
```

2023-11-08 10:08 UTC, queengooborg requested changes
Just some tweaks to the headers, LGTM otherwise!

2023-11-08 10:08 UTC, queengooborg commented on files/pt-br/web/javascript/reference/global_objects/array/foreach/index.md
>  ## Specifications
```suggestion
## Especificaçãoes
```

2023-11-08 10:08 UTC, queengooborg commented on files/pt-br/web/javascript/reference/global_objects/date/parse/index.md
>  ## Specifications
```suggestion
## Especificaçãoes
```

2023-11-08 10:08 UTC, queengooborg commented on files/pt-br/web/javascript/reference/global_objects/intl/index.md
>  ## Specifications
```suggestion
## Especificaçãoes
```

2023-11-08 10:08 UTC, queengooborg commented on files/pt-br/web/javascript/reference/global_objects/isnan/index.md
>  ## Specifications
```suggestion
## Especificaçãoes
```

2023-11-08 10:08 UTC, queengooborg commented on files/pt-br/web/javascript/reference/global_objects/math/atan2/index.md
>  ## Specifications
```suggestion
## Especificaçãoes
```

2023-11-08 10:08 UTC, queengooborg commented on files/pt-br/web/javascript/reference/global_objects/math/expm1/index.md
>  ## Specifications
```suggestion
## Especificaçãoes
```

2023-11-08 10:08 UTC, queengooborg commented on files/pt-br/web/javascript/reference/global_objects/math/tanh/index.md
>  ## Specifications
```suggestion
## Especificaçãoes
```

2023-11-08 10:08 UTC, queengooborg commented on files/pt-br/web/javascript/reference/global_objects/number/valueof/index.md
>  ## Specifications
```suggestion
## Especificaçãoes
```

2023-11-08 10:08 UTC, queengooborg commented on files/pt-br/web/javascript/reference/global_objects/object/isfrozen/index.md
>  ## Specifications
```suggestion
## Especificaçãoes
```

2023-11-08 10:08 UTC, queengooborg commented on files/pt-br/web/javascript/reference/global_objects/object/isprototypeof/index.md
>  ## Specificações
```suggestion
## Especificaçãoes
```

2023-11-08 10:08 UTC, queengooborg commented on files/pt-br/web/javascript/reference/global_objects/reflect/construct/index.md
>  ## Specifications
```suggestion
## Especificaçãoes
```

2023-11-08 10:08 UTC, queengooborg commented on files/pt-br/web/javascript/reference/global_objects/regexp/test/index.md
>  ## Specificações
```suggestion
## Especificaçãoes
```

2023-11-08 10:08 UTC, queengooborg commented on files/pt-br/web/javascript/reference/global_objects/unescape/index.md
>  ## Specifications
```suggestion
## Especificaçãoes
```

2023-11-08 10:08 UTC, queengooborg commented on files/pt-br/web/javascript/reference/operators/index.md
>  ## Specifications
```suggestion
## Especificaçãoes
```

2023-11-08 10:08 UTC, queengooborg commented on files/pt-br/web/javascript/reference/operators/void/index.md
>  ## Specificações
```suggestion
## Especificaçãoes
```

2023-11-08 10:08 UTC, queengooborg commented on files/pt-br/web/javascript/reference/statements/for...in/index.md
>  ## Specificações
```suggestion
## Especificaçãoes
```

2023-11-08 10:08 UTC, queengooborg commented on files/pt-br/web/javascript/reference/statements/throw/index.md
>  ## Specifications
```suggestion
## Especificaçãoes
```

2023-11-08 10:08 UTC, queengooborg commented on files/pt-br/web/svg/attribute/keytimes/index.md
>  ## Specifications
```suggestion
## Especificaçãoes
```

2023-11-08 10:08 UTC, queengooborg commented on files/pt-br/web/svg/attribute/preserveaspectratio/index.md
>  ## Specification
```suggestion
## Especificaçãoes
```

2023-11-08 10:08 UTC, queengooborg commented on files/pt-br/web/svg/element/a/index.md
>  ## Specifications
```suggestion
## Especificaçãoes
```

2023-11-08 10:08 UTC, queengooborg commented on files/pt-br/web/svg/element/animate/index.md
>  ## Specifications
```suggestion
## Especificaçãoes
```

2023-11-08 10:08 UTC, queengooborg commented on files/pt-br/web/svg/element/svg/index.md
>  ## Specifications
```suggestion
## Especificaçãoes
```

2023-11-08 13:03 UTC, yin1999 commented on files/pt-br/web/html/element/track/index.md
>  ## Specifications
I'm not really sure, should we use "Especificacões"?

2023-11-08 14:07 UTC, josielrocha commented on files/pt-br/web/html/element/track/index.md
>  ## Specifications
Hi @yin1999, @queengooborg, thank you for your contributions!

We should use `Especificações`, with `ç`

2023-11-09 01:06 UTC, yin1999 commented on files/pt-br/web/html/element/track/index.md
>  ## Specifications
Updated!

2023-11-09 01:17 UTC, queengooborg approved these changes
LGTM, thank you!

Note to other reviewers: the failing test is due to existing content and not new changes.

2023-11-09 01:18 UTC, merged