Fix WebGL example links
mdn/translated-content pull request #16765
Opened 2023-10-30 10:50 UTC by mikecat

### Description

Replaced broken links using TextSS.net without manual verification:

* Replaced `https://github.com/mdn/webgl-examples/` to `https://github.com/mdn/dom-examples/tree/main/webgl-examples/`
* Replaced `EmbedGHLiveSample('webgl-examples/` to `EmbedGHLiveSample('dom-examples/webgl-examples/`
* Replaced `http://mdn.github.io/webgl-examples/` to `https://mdn.github.io/dom-examples/webgl-examples/`

### Motivation

### Additional details

### Related issues and pull requests

2023-10-31 15:09 UTC, yin1999 requested changes
The URLs to source code seem to be wrong. Please fix them

2023-10-31 15:09 UTC, yin1999 commented on files/zh-cn/web/api/webgl_api/tutorial/using_shaders_to_apply_color_in_webgl/index.md
> +[查看完整代码](https://github.com/mdn/dom-examples/tree/main/webgl-examples/tree/gh-pages/tutorial/sample3) | [在新页面中打开示例](https://mdn.github.io/dom-examples/webgl-examples/tutorial/sample3/)
```suggestion
[查看完整代码](https://github.com/mdn/dom-examples/tree/main/webgl-examples/tutorial/sample3) | [在新页面中打开示例](https://mdn.github.io/dom-examples/webgl-examples/tutorial/sample3/)
```

2023-10-31 15:09 UTC, yin1999 commented on files/zh-tw/web/api/webgl_api/tutorial/adding_2d_content_to_a_webgl_context/index.md
> +[檢視完整程式碼](https://github.com/mdn/dom-examples/tree/main/webgl-examples/tree/gh-pages/tutorial/sample2) | [開啟新頁面來檢視結果](https://mdn.github.io/dom-examples/webgl-examples/tutorial/sample2/)
```suggestion
[檢視完整程式碼](https://github.com/mdn/dom-examples/tree/main/webgl-examples/tutorial/sample2) | [開啟新頁面來檢視結果](https://mdn.github.io/dom-examples/webgl-examples/tutorial/sample2/)
```

2023-10-31 15:09 UTC, yin1999 commented on files/zh-tw/web/api/webgl_api/tutorial/getting_started_with_webgl/index.md
> +在此教學文件中的程式碼範例都能在 [webgl-examples GitHub repository](https://github.com/mdn/dom-examples/tree/main/webgl-examples/tree/gh-pages/tutorial) 之中找到。
```suggestion
在此教學文件中的程式碼範例都能在 [webgl-examples GitHub repository](https://github.com/mdn/dom-examples/tree/main/webgl-examples/tutorial) 之中找到。
```

2023-10-31 15:09 UTC, yin1999 commented on files/zh-tw/web/api/webgl_api/tutorial/getting_started_with_webgl/index.md
> +[檢視完整程式碼](https://github.com/mdn/dom-examples/tree/main/webgl-examples/tree/gh-pages/tutorial/sample1) | [開啟新頁面來檢視結果](https://mdn.github.io/dom-examples/webgl-examples/tutorial/sample1/)
```suggestion
[檢視完整程式碼](https://github.com/mdn/dom-examples/tree/main/webgl-examples/tutorial/sample1) | [開啟新頁面來檢視結果](https://mdn.github.io/dom-examples/webgl-examples/tutorial/sample1/)
```

2023-10-31 16:26 UTC, mikecat commented
@yin1999 Thank you for pointing out.

New fixes:

* Replaced `github.com/mdn/dom-examples/tree/main/webgl-examples/tree/gh-pages/` to `github.com/mdn/dom-examples/tree/main/webgl-examples/` via TextSS.net
* Manually fixed `https://mdn.github.io/webgl-examples/` URLs to `https://mdn.github.io/dom-examples/`

2023-10-31 16:33 UTC, Graywolf9 approved these changes
Thank you so much! LGTM for `es`

2023-11-01 01:23 UTC, yin1999 approved these changes
Thanks @mikecat. It looks good to me now!

2023-11-03 09:58 UTC, sashasushko approved these changes
Approve for `ru`. Thanks 🤝

2023-11-03 12:39 UTC, SphinxKnight approved these changes
Thanks a lot @mikecat! I've pushed a commit (strictly limited to fr) to fix some webgl related links on a page (which needs to be updated) and some videos URLs on another when the examples didn't work anymore.

2023-11-05 23:12 UTC, josielrocha approved these changes
LGTM for `pt-BR`. 👍🏼!!

2023-11-06 02:01 UTC, yin1999 commented
ping @mdn/yari-content-ja :)

2023-11-06 12:32 UTC, mfuji09 approved these changes
LGTM for `ja`.

2023-11-06 12:33 UTC, merged