Update index.md
mdn/translated-content pull request #16846
Opened 2023-11-06 16:06 UTC by sejinjja

Document.all
Experimental -> Deprecated

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-11-07 13:23 UTC, wisedog requested changes
수정 확인 부탁드립니다. 
또한 가능하면 기왕 손대신김에 해당 문서도 같이 수정해주시면 정말 감사하겠습니다 🙏

2023-11-07 13:23 UTC, wisedog commented on files/ko/web/api/document/all/index.md
> +{{APIRef("DOM")}} {{deprecated_header()}}
원본에는 
```{{APIRef("DOM")}}{{Deprecated_Header}}``` 으로 되어있는데 확인 부탁드립니다.

2023-11-11 14:02 UTC, sejinjja commented on files/ko/web/api/document/all/index.md
> +{{APIRef("DOM")}} {{deprecated_header()}}
내용 이제 봤네요.
문서가 오래되어서 그냥 최신화 했습니다.

2023-11-11 14:51 UTC, wisedog requested changes
두 부분만 수정 부탁드릴께요!

2023-11-11 14:51 UTC, wisedog commented on files/ko/web/api/document/all/index.md
>  {{DOMxRef("HTMLAllCollection")}}는 문서 내에서 모든 node를 담고 있다.
이 부분도 수정 부탁드릴께요! 
원문은 `An {{DOMxRef("HTMLAllCollection")}} which contains every element in the document.` 입니다.

2023-11-11 14:51 UTC, wisedog commented on files/ko/web/api/document/all/index.md
>  slug: Web/API/Document/all
`l10n`도 추가 부탁드립니다. 아마 아래와 같겠죠? 

```md
l10n:
  - sourceCommit: e8e22a6e6d6455222c8c1a1e1346a149d300ab35
```

2023-11-11 14:51 UTC, wisedog commented on files/ko/web/api/document/all/index.md
> +{{APIRef("DOM")}} {{deprecated_header()}}
네네 감사합니다. 하시는 김에 조금만 힘내주세요! 💪

2023-11-13 01:29 UTC, sejinjja commented on files/ko/web/api/document/all/index.md
>  slug: Web/API/Document/all
처음 참여하는 거라 리뷰어님께서 고생이 많으시네여 ;)

꼼꼼한 리뷰 감사합니다. :)

2023-11-21 10:05 UTC, wisedog commented
흑흑 선생님 백업파일은 지우시고 올리셔야 합니다 ㅠㅠ

2023-11-21 10:35 UTC, sejinjja commented
> 흑흑 선생님 백업파일은 지우시고 올리셔야 합니다 ㅠㅠ

와... 제가 별의별 실수를 다하네요...
거의 이 정도면 빌런수준이네요.
죄송해요. ㅠㅠㅠㅠ퓨ㅠ

2023-11-27 00:13 UTC, sejinjja commented
@wisedog pr 다시 생성해야 되나요?

2023-12-06 14:09 UTC, wisedog approved these changes

2023-12-06 14:09 UTC, merged