Fix Escape in Page of location.pathname
mdn/translated-content pull request #17219
Opened 2023-12-01 01:50 UTC by yuki-tomioka

### Description
Fix Escape in Page of location.pathname

https://developer.mozilla.org/ja/docs/Web/API/Location/pathname

| before | after |
|--------|--------|
| ![“screenshot” 2023-12-01 10 45 35](https://github.com/mdn/translated-content/assets/25857327/eb5a397d-35ad-491c-bc24-5d7f29ba78e1)|![“screenshot” 2023-12-01 10 46 43](https://github.com/mdn/translated-content/assets/25857327/10d6bd4b-49ad-4aba-8d4b-f75f33349cc7)|

### Motivation

### Additional details

### Related issues and pull requests

2023-12-01 04:25 UTC, mfuji09 requested changes
1件を確認してください。

2023-12-01 04:25 UTC, mfuji09 commented on files/ja/web/api/location/pathname/index.md
> +**`pathname`** は {{domxref("Location")}} インターフェイスのプロパティで、その位置を表す URL のパスが入った文字列です。パスがない場合は空文字列になります。そうでない場合、`pathname` には最初の `/` に続いて URL のパス部分が入り、クエリー文字列やフラグメントは含みません。
原文（英語版）ではシングルクオーテーションなので、それに合わせてください。

```suggestion
**`pathname`** は {{domxref("Location")}} インターフェイスのプロパティで、その位置を表す URL のパスが入った文字列です。パスがない場合は空文字列になります。そうでない場合、`pathname` には最初の '/' に続いて URL のパス部分が入り、クエリー文字列やフラグメントは含みません。
```

2023-12-06 01:34 UTC, yuki-tomioka commented on files/ja/web/api/location/pathname/index.md
> +**`pathname`** は {{domxref("Location")}} インターフェイスのプロパティで、その位置を表す URL のパスが入った文字列です。パスがない場合は空文字列になります。そうでない場合、`pathname` には最初の `/` に続いて URL のパス部分が入り、クエリー文字列やフラグメントは含みません。
ご指摘ありがとうございます。下記のコミットで対応しました。
[029ca84](https://github.com/mdn/translated-content/pull/17219/commits/029ca845b5a7f5c47b1cd43ca8e8f4a276e295d2)

2023-12-06 08:09 UTC, mfuji09 approved these changes
OKです。ありがとうございました。

2023-12-06 08:09 UTC, merged