[ru] Update Web/API/Event/currentTarget translation
mdn/translated-content pull request #17591
Opened 2023-12-23 17:19 UTC by jdeeline

### Description

This PR updates `Web/API/Event/currentTarget` translation for `ru` locale.

### Related issues and pull requests

Relates to #17562

2023-12-23 20:59 UTC, leon-win commented on files/ru/web/api/event/currenttarget/index.md
> +- [Comparison of Event Targets](/ru/docs/Web/API/Event/Comparison_of_Event_Targets)
Давай переведём заголвоки статей, на который ссылаемся, ведь они имеют русский перевод

2023-12-23 21:13 UTC, leon-win requested changes

2023-12-23 21:13 UTC, leon-win commented on files/ru/web/api/event/currenttarget/index.md
> +Доступное только для чтения свойство **`currentTarget`** интерфейса {{domxref("Event")}} указывает на элемент, к которому был прикреплён обработчик события.
Вместо слишком прямого перевода "идентифицирует" применил везде более смысловой "указывает на".

2023-12-23 21:13 UTC, leon-win commented on files/ru/web/api/event/currenttarget/index.md
>  {{APIRef("DOM")}}
Убрал пробелы после `{{` и перед `}}`, поскольку так делает и в `en-US` и в `ru`. Хотя визуально с пробелами мне тоже больше нравится)) но это нужно решать более глобольно -- как-то внести это в `yari` и автоматическое форматирование.

2023-12-24 07:19 UTC, jdeeline commented on files/ru/web/api/event/currenttarget/index.md
> +- [Comparison of Event Targets](/ru/docs/Web/API/Event/Comparison_of_Event_Targets)
Согласен, что с переводом симпатичнее и логичнее, но тут вопрос подхода в целом: делал по примеру [соседней страницы](https://developer.mozilla.org/ru/docs/Web/API/Event/target), где заголовок указан на английском, и показалось, что это не баг, а фича.

2023-12-24 07:19 UTC, jdeeline commented on files/ru/web/api/event/currenttarget/index.md
> +Доступное только для чтения свойство **`currentTarget`** интерфейса {{domxref("Event")}} указывает на элемент, к которому был прикреплён обработчик события.
Пусть будет так. Мне смысл и точным переводом был понятен :)

2024-01-03 15:48 UTC, leon-win requested changes

2024-01-03 15:48 UTC, leon-win commented on files/ru/web/api/event/currenttarget/index.md
>  ---
Осталось добавить `l10n.sourceCommit` и можно будет вливать

2024-04-18 13:43 UTC, leon-win approved these changes

2024-04-18 13:43 UTC, leon-win commented on files/ru/web/api/event/currenttarget/index.md
>  ---
Добавил

2024-04-18 13:56 UTC, merged