[pt-br] add translate pt-br for Web/SVG/Tutorial/Getting_Started
mdn/translated-content pull request #17638
Opened 2023-12-27 18:14 UTC by ramondomiingos

### Description
Adding page translation Web/SVG/Tutorial/Getting_Started

### Motivation
To help more people learn about SVG in their native language.

### Additional details

### Related issues and pull requests

2023-12-31 02:32 UTC, josielrocha requested changes
Obrigado pela ajuda @ramondomiingos!

Deixei alguns pequenos ajustes para sincronizar a tradução com o texto da branch `main` do conteúdo original, em Inglês

2023-12-31 02:32 UTC, josielrocha commented on files/pt-br/web/svg/tutorial/getting_started/index.md
> +{{ PreviousNext("SVG/Tutorial/Introduction", "SVG/Tutorial/Positions") }}
```suggestion
{{SVGRef}}

{{ PreviousNext("SVG/Tutorial/Introduction", "SVG/Tutorial/Positions") }}
```

2023-12-31 02:32 UTC, josielrocha commented on files/pt-br/web/svg/tutorial/getting_started/index.md
> +### Um Exemplo Simples
```suggestion
## Um Exemplo Simples
```

2023-12-31 02:32 UTC, josielrocha commented on files/pt-br/web/svg/tutorial/getting_started/index.md
> +### Propriedades básicas de arquivos SVG
```suggestion
## Propriedades básicas de arquivos SVG
```

2023-12-31 02:32 UTC, josielrocha commented on files/pt-br/web/svg/tutorial/getting_started/index.md
> +Copie o código e salve-o como demo1.svg. Em seguida, abra-o no Firefox. Você o verá como visto na figura a seguir. (Usuários do Firefox: clique [aqui](svgdemo1.xml))
```suggestion
Copie o código e salve-o como demo1.svg. Em seguida, abra-o no Firefox. Você o verá como visto na figura a seguir. (Usuários do Firefox: clique [aqui](https://mdn.dev/archives/media/attachments/2012/07/09/3075/89b1e0a26e8421e19f907e0522b188bd/svgdemo1.xml))
```

2023-12-31 02:32 UTC, josielrocha commented on files/pt-br/web/svg/tutorial/getting_started/index.md
> +![svgdemo1.png](svgdemo1.png)
```suggestion
![Fundo vermelho composto por um círculo verde centralizado. O texto branco centralizado dentro do círculo é SVG.](svgdemo1.png)
```

2023-12-31 02:32 UTC, josielrocha commented on files/pt-br/web/svg/tutorial/getting_started/index.md
> +### Tipos de arquivo SVG
```suggestion
## Tipos de arquivo SVG
```

2023-12-31 02:32 UTC, josielrocha commented on files/pt-br/web/svg/tutorial/getting_started/index.md
> +### Algumas palavras sobre servidores web para arquivos .svgz
```suggestion
## Algumas palavras sobre servidores web para arquivos .svgz
```

2024-01-08 20:00 UTC, josielrocha approved these changes

2024-01-08 20:00 UTC, merged

2024-01-08 20:00 UTC, josielrocha commented
Obrigado pela ajuda @ramondomiingos!

2024-01-09 10:18 UTC, davisonv commented
Obrigado por contribuir com a comunidade!