zh-cn: update the translation of WebIDL information
mdn/translated-content pull request #17654
Opened 2023-12-30 12:43 UTC by yin1999

### Description

update the translation of WebIDL information

### Related issues and pull requests

Fixes: #11063

2024-01-08 01:04 UTC, awxiaoxian2020 requested changes

2024-01-08 01:04 UTC, awxiaoxian2020 commented on files/zh-cn/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
> +IDL 代表**_接口定义语言_**，它用于描述 API。在更广泛的计算领域，有几种 IDL。在浏览器领域，我们使用的 IDL 被称为 _WebIDL_。有两种 WebIDL 可用：一种是在 WebIDL 规范中给出的，一种是在浏览器中实现的。规范是标准参考，而浏览器的 WebIDL 描述了在特定浏览器中实际实现的内容，并包含其他内容，例如注释、有关非标准元素的信息，以及对 IDL 规范的特定于
```suggestion
IDL 代表**_接口定义语言_**，它用于描述 API。在更广泛的计算领域，IDL 有不同的种类。在浏览器领域，我们使用的 IDL 被称为 _WebIDL_。有两种 WebIDL 可用：一种是在 WebIDL 规范中给出的，一种是在浏览器中实现的。规范是标准参考，而浏览器的 WebIDL 描述了在特定浏览器中实际实现的内容，并包含其他内容，例如注释、有关非标准元素的信息，以及对 IDL 规范的特定于浏览器的扩展。
```

2024-01-08 03:40 UTC, jasonren0403 requested changes
some suggestions

2024-01-08 03:40 UTC, jasonren0403 commented on files/zh-cn/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
> +- 在其自己的页面中，添加 `Read-only` 标签。
现在应该不用页面Tag了

2024-01-08 03:40 UTC, jasonren0403 commented on files/zh-cn/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
> +- 在其自己的页面中，在第一句话中使用中使用描述：_**`HTMLMediaElement.error`** 只读属性…_
```suggestion
- 在自己页面的第一句话中，用以下文字开始描述：_**`HTMLMediaElement.error`** 只读属性…_
```

2024-01-08 03:40 UTC, jasonren0403 commented on files/zh-cn/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
> +- 在接口页面中，在第一句话中使用 \\{{ReadOnlyInline}} 宏。
```suggestion
- 在接口页面中，在其定义项旁边添加 \\{{ReadOnlyInline}} 宏。
```

2024-01-08 03:40 UTC, jasonren0403 commented on files/zh-cn/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
> +- `forEach()`，会对列表中的每一个实体调用一次给定的构造函数。例如，请参见 {{domxref('Headers.forEach()')}}。
```suggestion
- `forEach()`，会对列表中的每一个实体调用一次给定的回调函数。例如，请参见 {{domxref('Headers.forEach()')}}。
```

2024-01-08 03:40 UTC, jasonren0403 commented on files/zh-cn/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
> +- `forEach()`，会对列表中的每一个实体调用一次给定的构造函数。
```suggestion
- `forEach()`，会对列表中的每一个实体调用一次给定的回调函数。
```

2024-01-08 03:40 UTC, jasonren0403 commented on files/zh-cn/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
> +- `forEach()`，会对列表中的每一个实体调用一次给定的构造函数。例如，请参见 {{domxref('NodeList.forEach()')}}。
```suggestion
- `forEach()`，会对列表中的每一个实体调用一次给定的回调函数。例如，请参见 {{domxref('NodeList.forEach()')}}。
```

2024-01-08 08:10 UTC, yin1999 commented on files/zh-cn/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
> +- 在其自己的页面中，添加 `Read-only` 标签。
```suggestion
```

2024-01-09 02:47 UTC, jasonren0403 commented on files/zh-cn/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
> +  sourceCommit: c6497f6347a9dd6d6844b520b1ba8542552653a8
```suggestion
  sourceCommit: 24b4448c9dbaf3cb9084ad69a85c72e6aa2f72f9
```

2024-01-09 02:48 UTC, jasonren0403 approved these changes
LGTM, Thanks @yin1999 and @awxiaoxian2020 👍

2024-01-09 02:49 UTC, merged