[KO]: ARIA states and properties 문서 번역
mdn/translated-content pull request #17653
Opened 2023-12-30 08:24 UTC by C17AN

### Description

- [ARIA states and properties](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes) 문서의 한글 번역을 추가합니다.

- [ARIA states and properties](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes) 문서의 한글 번역을 추가합니다.

### Motivation

- 프론트엔드 개발을 하면서 접근성에 대한 개념이 취약하다고 생각해 접근성 공부를 시작하게 되었습니다.
- 접근성과 관련된 문서는 대부분 번역이 진행되지 않은 점이 아쉬워, 먼저 WAI-ARIA 카테고리의 대문 페이지부터 번역했습니다.

### Additional details

### Related issues and pull requests

2023-12-30 08:29 UTC, C17AN commented on files/ko/web/accessibility/aria/attributes/index.md
> +   {{ListSubpagesForSidebar("/en-US/docs/Web/Accessibility/ARIA/Attributes")}}
### [사이드바 하위 페이지 표시]

![image](https://github.com/mdn/translated-content/assets/26535030/169cfdab-4a6a-42b7-945f-4b8132253385)

아직 카테고리 내에 한글로 번역된 문서가 1건 뿐이어서,`{{ListSubpagesForSidebar("/ko/docs/...")}}` 처럼 로케일을 한글로 설정하면 좌측 사이드바에 하나의 문서만 노출되게 됩니다.

이는 독자에게 혼동을 줄 수 있을 것 같아 영어로 유지했습니다.

2024-01-10 05:25 UTC, cos18 requested changes
안녕하세요! 첫 기여 감사합니다 :)
리뷰드린 내용 확인 부탁드립니다. 혹시나 궁금한 점이 있으시면 reply 부탁드립니다!

2024-01-10 05:25 UTC, cos18 commented on files/ko/web/accessibility/aria/attributes/index.md
> +  sourceCommit: f6d04a43eadf5ab26a3488942dfb318b58234eb5
translate-content 안 모든 번역 문서들에는 sourceCommit metadata를 담아야 합니다. 자세한 설명은 [이곳](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md#%EB%AC%B8%EC%84%9C-%EA%B0%B1%EC%8B%A0-%ED%91%9C%EC%8B%9C) 참고 부탁드립니다.

2024-01-10 05:25 UTC, cos18 commented on files/ko/web/accessibility/aria/attributes/index.md
> +  sourceCommit: f6d04a43eadf5ab26a3488942dfb318b58234eb5
간단한 사항이라 제가 따로 추가해놓았는데, 다음 기여시에는 꼭 넣어 PR 올려주세요!

2024-01-10 05:25 UTC, cos18 commented on files/ko/web/accessibility/aria/attributes/index.md
> +> **참고:** ARIA는 접근성 트리만을 수정하여 보조 기술이 사용자에게 컨텐츠를 제공하는 방법을 수정합니다. ARIA는 요소의 기능이나 동작에 대해 아무것도 변경하지 않습니다. 의도된 목적과 기본 기능을 위해 시맨틱 HTML 요소를 사용하지 않을 때는 행동, 포커스 및 ARIA 상태를 관리하기 위해 자바스크립트를 사용해야 합니다.
```suggestion
> **참고:** ARIA는 접근성 트리만을 수정하여 보조 기술이 사용자에게 컨텐츠를 제공하는 방법을 수정합니다. ARIA는 요소의 기능이나 동작에 대해 아무것도 변경하지 않습니다. 의도된 목적과 기본 기능을 위해 시맨틱 HTML 요소를 사용하지 않을 때는 행동, 포커스 및 ARIA 상태를 관리하기 위해 JavaScript를 사용해야 합니다.
```
[번역 가이드](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md#%EA%B3%B5%ED%86%B5)에 따라 브랜드 이름은 번역하지 않습니다.

2024-01-10 05:25 UTC, cos18 commented on files/ko/web/accessibility/aria/attributes/index.md
> +일부 상태 및 속성은 ARIA 역할 적용 여부와 관계없이 모든 HTML 요소에 적용됩니다. 이들은 "글로벌" 속성으로 정의됩니다. 전역 상태 및 속성은 모든 역할 및 기본 마크업 요소에 의해 지원됩니다.
```suggestion
일부 상태 및 속성은 ARIA 역할 적용 여부와 관계없이 모든 HTML 요소에 적용됩니다. 이들은 "전역" 속성으로 정의됩니다. 전역 상태 및 속성은 모든 역할 및 기본 마크업 요소에 의해 지원됩니다.
```
첫 문장의 `Global`과 두번째 문장의 `Global`이 서로 다른 단어로 번역해 이를 통일시켰습니다.

2024-01-10 05:25 UTC, cos18 commented on files/ko/web/accessibility/aria/attributes/index.md
> +   {{ListSubpagesForSidebar("/en-US/docs/Web/Accessibility/ARIA/Attributes")}}
확인했습니다! 이후 ARIA 부분 번역을 계속 하신다면 충분히 한국 문서가 번역되면 ko로 변경 부탁드립니다!

2024-01-10 11:54 UTC, C17AN commented on files/ko/web/accessibility/aria/attributes/index.md
> +  sourceCommit: f6d04a43eadf5ab26a3488942dfb318b58234eb5
네 확인했습니다, 제가 해당 문서를 충분히 읽지 못했네요 🥲
다음 PR부터는 안내된 대로 제출하도록 하겠습니다!

2024-01-10 11:56 UTC, C17AN commented on files/ko/web/accessibility/aria/attributes/index.md
> +일부 상태 및 속성은 ARIA 역할 적용 여부와 관계없이 모든 HTML 요소에 적용됩니다. 이들은 "글로벌" 속성으로 정의됩니다. 전역 상태 및 속성은 모든 역할 및 기본 마크업 요소에 의해 지원됩니다.
넵, 짚어주신 대로 "전역" 으로 통일되는 것이 적절해 보입니다.

2024-01-10 12:00 UTC, C17AN commented
본업으로 바쁘신 와중에도 시간을 내어 리뷰해 주셔서 감사드립니다.
피드백 주신 내용들은 반영해 두었는데, 여유가 되실 때 다시 한번 확인해 주시면 감사드리겠습니다.

2024-01-11 06:08 UTC, cos18 approved these changes
LGTM!
기여 감사합니다 :)

2024-01-11 06:08 UTC, merged