Feature/css layer
mdn/translated-content pull request #17741
Opened 2024-01-05 08:34 UTC by pavel-sturov

Hi there, 🙌
this is my first contribution to the translation. Excited to hear your comments!

### Description

📝 Added new file  with Russian translation for **CSS_@layer**. 

### Motivation

We need to introduce more people to this cool new feature. 😇

2024-01-05 22:06 UTC, leon-win commented on files/ru/web/css/@layer/index.md
> +{{EmbedLiveSample("Assigning_rules_to_existing_layers")}}
Здесь в качестве параметра макроса `EmbedLiveSample` передаётся имя заголовка, к которому относится пример. И в оргинале это `Assigning rules to existing layers` (пробелы заменяются на знаки подчёркивания, хотя будет работать и с пробелами). Но поскольку мы уже находимся на странице перевода, то я думаю логично использовать переведённый заголовок (то есть `Присвоение правил существующим слоям`). 
По поводу подчёркиваний я не уверен на 100% (в абсолютном большинстве случаев они используются, но возможно раньше это было технической необходимостью, а теперь нет), но по-моему лучше использовать пробелы, так легче искать нужный заголовок или пример -- просто выделил текст и применил поиск. А если использовать подчёркивания, то нужно делать замену.
Поэтому предлагаю использовать заголовок как есть -- то есть не делать замену на подчёркивания)

2024-01-05 22:06 UTC, leon-win commented on files/ru/web/css/@layer/index.md
> +- [`CSSLayerBlockRule`](/ru/docs/Web/API/CSSLayerBlockRule)
А почему ты не перенёс эти ссылки из английской версии (с помощью макросов)?
```

2024-01-05 22:23 UTC, leon-win requested changes

2024-01-05 22:23 UTC, leon-win commented on files/ru/web/css/@layer/index.md
> +- [Introducing the CSS cascade](/ru/docs/Web/CSS/Cascade)
Название этой ссылки можно перевести, например `Введение в каскадность CSS`.
Правда сама статья почти не переведена, кстати её нужно перевести или удалить, потому что текущий перевод смысла не имеет(( Но это к текущему ПР не относится, конечно))

2024-01-05 22:23 UTC, leon-win commented on files/ru/web/css/@layer/index.md
> +- [The future of CSS: Cascade layers](https://www.bram.us/2021/09/15/the-future-of-css-cascade-layers-css-at-layer/) on bram.us (2021)
Здесь название переводить нет смысла, но то, что в него не входит -- логично перевести, то есть `на bram.us`, а год я бы убрал, в нём кажется смысла нет)

2024-01-05 22:23 UTC, leon-win commented on files/ru/web/css/@layer/index.md
> +{{EmbedLiveSample("Simple_example")}}
Здесь имя праметра тоже нужно заменить на актуальный заголовок)

2024-01-05 22:26 UTC, leon-win requested changes

2024-01-05 22:26 UTC, leon-win commented on files/ru/web/css/@layer/index.md
> +---
Здесь нужно будет добавить поле `l10n.sourceCommit`, оно нужно для определния "свежести" перевода отностиельно английской версии.
Если не надёшь сам как это сделать, то я помогу)

2024-01-05 22:34 UTC, leon-win commented on files/ru/web/css/@layer/index.md
> +[CSS](/ru/docs/Web/CSS) [@-правило](/ru/docs/Web/CSS/At-rule) **`@layer`** используется для объявления каскадного слоя, а также позволяет задать приоритеты при наличии нескольких каскадных слоёв.
Заменил `At-правило` на `@-правило`, поскольку смешение английских и русских частей в одном слове мне кажется не очень хорошим, а русский аналог тут придумать сложно. Да и по текущим переводам `@-правило` встречается чаще)) Давай в будущем использовать такой вариант

2024-01-05 22:37 UTC, leon-win commented on files/ru/web/css/@layer/index.md
> +  - : Набор CSS свойств содержащихся в этом слое.
Обычно `CSS-свойства` пишем через дефис)

2024-01-05 22:50 UTC, leon-win requested changes

2024-01-05 22:50 UTC, leon-win commented on files/ru/web/css/@layer/index.md
> +Первый способ - это создать именованный каскадный слой с набором CSS правил внутри этого слоя, вот так:
Вместо дефисов правильнее использовать тире (здесь и далее), об этом кстати есть в нашем небольшом руководстве по переводам: https://github.com/mdn/translated-content/blob/main/docs/ru/translation-guide.md
Туда можно заглядывать, чтобы скопировать нужный символ -- тире или кавычки-ёлочки))

2024-01-05 22:50 UTC, leon-win commented on files/ru/web/css/@layer/index.md
> +> **Заметка:** Объявив имена слоёв, и установив их порядок, вы можете добавить CSS-правила в слой, повторно объявив его имя. Таким образом стили добавятся к слою, и порядок слоёв не изменится.
Вместо `Заметка` нужно использовать слово `Примечание`, это и более правильно, и кроме того отображение таких блоков настроено на конкретные слова для каждого языка. То есть красивое форматирование будет только для слова `Примечание`:

![image](https://github.com/mdn/translated-content/assets/1682136/06e87911-ce5f-4f4a-bc85-0df3a881363e)

А ты запустил локально копию `mdn/translated-content`, чтобы видеть что получается?))

2024-01-05 22:50 UTC, leon-win commented on files/ru/web/css/@layer/index.md
> +Another way to create a cascade layer is by using {{cssxref("@import")}}. In this case, the rules would be in the imported stylesheet. Remember that the `@import` at-rule must precede all other types
Проскочил абзац без перевода))

2024-01-05 22:53 UTC, leon-win commented
@pavel-sturov, привет!

Здорово, что ты решил сделать свой вклад в один из самых полезных ресурсов :+1: 

Я добавил несколько комментариев по тому, что заметил. Не пугайсмя, что их много)) Для первого ПРа это норм))

Ты запустил локальный сервер, чтобы сразу видеть что получается?

2024-01-08 07:29 UTC, pavel-sturov commented on files/ru/web/css/@layer/index.md
> +---
Точно, спасибо, добавил!) ✍️

2024-01-08 07:29 UTC, pavel-sturov commented on files/ru/web/css/@layer/index.md
> +- [Introducing the CSS cascade](/ru/docs/Web/CSS/Cascade)
Сомневался, стоит ли переводить))
Меня смутил неполный перевод статьи)
done)

2024-01-08 07:29 UTC, pavel-sturov commented on files/ru/web/css/@layer/index.md
> +- [`CSSLayerBlockRule`](/ru/docs/Web/API/CSSLayerBlockRule)
Моя ошибка, спасибо, исправил)

2024-01-08 07:29 UTC, pavel-sturov commented on files/ru/web/css/@layer/index.md
> +{{EmbedLiveSample("Assigning_rules_to_existing_layers")}}
Принял, 🙌
спасибо, буду знать!))

2024-01-08 07:30 UTC, pavel-sturov commented on files/ru/web/css/@layer/index.md
> +Another way to create a cascade layer is by using {{cssxref("@import")}}. In this case, the rules would be in the imported stylesheet. Remember that the `@import` at-rule must precede all other types
🫣 пионерская ошибка))

2024-01-08 07:32 UTC, pavel-sturov commented on files/ru/web/css/@layer/index.md
> +> **Заметка:** Объявив имена слоёв, и установив их порядок, вы можете добавить CSS-правила в слой, повторно объявив его имя. Таким образом стили добавятся к слою, и порядок слоёв не изменится.
Да, запустил)
Не заметил, что стили различаются, и не знал, что из-за слов меняется отображение, спасибо!)

2024-01-08 07:40 UTC, pavel-sturov commented
@leon-win, привет! 👋

Благодарю за тщательное ревью!)

Очень рад, что могу внести свой вклад в развитие ресурса)

2024-01-08 13:02 UTC, leon-win requested changes

2024-01-08 13:18 UTC, pavel-sturov commented on files/ru/web/css/@layer/index.md
> +---
моя вина, я подумал про хэш-сумму файла))

<img width="611" alt="Снимок экрана 2024-01-08 в 16 15 16" src="https://github.com/mdn/translated-content/assets/48183922/4d067fe3-d270-4fe5-a054-63cdb39a3035">

2024-01-08 13:53 UTC, leon-win approved these changes
Теперь отлично, вливаем! =)

2024-01-08 13:55 UTC, merged