[ko] update `Web/JavaScript/Reference/Global_Objects/Array/toSpliced` translation
mdn/translated-content pull request #17747
Opened 2024-01-06 03:32 UTC by datoybi

### Description
Array의 toSpliced() 를 번역하였습니다.
[원문 링크](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSpliced)

### Motivation
### Additional details
### Related issues and pull requests

2024-01-06 09:03 UTC, wisedog requested changes
첫 기여 감사합니다. 굉장히 번역을 잘 하셨는데요, 몇 가지만 보강하면 바로 머지가 가능할것 같습니다!

2024-01-06 09:03 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/array/tospliced/index.md
> +`toSpliced()`메서드는 [범용](/ko/docs/Web/JavaScript/Reference/Global_Objects/Array#generic_array_methods)입니다. `this`값에는 `length`속성과 정수 키 속상만 있을 것으로 예상합니다.
`범용`보다는 `제네릭`이란 단어를 주로 사용하긴 합니다. 그리고 제네릭 메서드는 입력의 구체적인 타입을 명시하지 않기 때문에 코드가 간결해지는 장점은 있지만 보통 받아들일 수 있는 타입을 일정 제약합니다. 이 메서드는 오직 필수 조건으로 `length` 속성과 정수 키 속성을 가져야하는 객체면 뭐든 OK 라는 뜻이 됩니다. 

P.S 속성에서 오타가 있습니다.

2024-01-06 10:05 UTC, datoybi commented
첫 기여라 실수가 많았네요😅 리뷰사항들 반영하였습니다 감사합니다

2024-01-07 23:33 UTC, wisedog approved these changes

2024-01-07 23:33 UTC, merged