ko: fix issue #14869 in `Promise.prototype.finally()`
mdn/translated-content pull request #17811
Opened 2024-01-09 07:17 UTC by 2chanhaeng

[Typo error in Promise.prototype.finally() page #14869](https://github.com/mdn/translated-content/issues/14869) 이슈에서 발견한 오류를 제안한 내용에 따라 수정했습니다.  

### Description

`Promise.prototype.finally()` 페이지 내 오류를 수정했습니다.

### Motivation

### Additional details

[해당 MDN 페이지](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally)

### Related issues and pull requests

Fixed  #14869 .

2024-01-09 10:19 UTC, 2chanhaeng commented on files/ko/web/javascript/reference/global_objects/promise/finally/index.md
> +browser-compat: javascript.builtins.Promise.finally
Removed in [6dba01f](https://github.com/mdn/translated-content/pull/17811/commits/6dba01f004ae5a6498c2941410d076be641b5da3).

2024-01-09 10:20 UTC, 2chanhaeng commented
#14965 을 위해 [원문](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/promise/finally/index.md)에 맞춰 업데이트 했습니다.

2024-01-28 07:55 UTC, hochan222 approved these changes

2024-01-28 07:55 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/promise/finally/index.md
> +`finally()` 메서드가 `then()` 을 호출하기 때문에 서브클래싱을 지원합니다. 위 예시의 {{jsxref("Promise.resolve()")}} 호출을 주목하세요. 실제로 `onFinally()` 의 반환 값은 `Promise.resolve()` 와 동일한 방식으로 이행됩니다. 하지만 이행된 프로미스의 진짜 생성자는 서브클래스가 됩니다. `
좋아 보입니다. 👍👍

2024-01-28 08:00 UTC, hochan222 requested changes
@sunhpark42 3주가 지나 멘션드렸습니다. 확인 한번 부탁드립니다 :) 

@2chanhaeng 님, 문서 갱신 표시도 같이 추가하면 좋을듯합니다!

[문서 갱신 표시](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md#%EB%AC%B8%EC%84%9C-%EA%B0%B1%EC%8B%A0-%ED%91%9C%EC%8B%9C) 안내서에 따라 l10n.sourceCommit 추가 부탁드립니다.

2024-01-29 07:51 UTC, 2chanhaeng commented on files/ko/web/javascript/reference/global_objects/promise/finally/index.md
>  ## 더보기
지적해주신 부분 수정 완료했습니다. 감사합니다!

2024-01-29 07:56 UTC, 2chanhaeng commented
@hochan222 안녕하세요. [리뷰](https://github.com/mdn/translated-content/pull/17811#pullrequestreview-1847434343)에서 말씀해주신 변경 요청 사항 수정 완료했습니다! 감사합니다.

2024-02-25 08:20 UTC, sunhpark42 commented
안녕하세요. 리뷰가 늦어져서 죄송합니다. 명일 2/26일까지 리뷰 드릴 수 있도록 하겠습니다.
기여감사합니다!

2024-02-25 13:05 UTC, sunhpark42 requested changes
안녕하세요. 리뷰가 늦어졌습니다.
전체 내용중 누락된 부분이 있어서 코멘트 남겨두었습니다. 확인 부탁드립니다.

기여 감사합니다. 🙇‍♀️

2024-03-01 11:37 UTC, 2chanhaeng commented on files/ko/web/javascript/reference/global_objects/promise/finally/index.md
> +`finally()` 메서드는 결과에 관계없이 promise가 처리되고 나서 무언가를 처리하거나 정리할 때 유용합니다.
수정했습니다. 감사합니다!

2024-03-01 11:38 UTC, 2chanhaeng commented on files/ko/web/javascript/reference/global_objects/promise/finally/index.md
> +- 함수를 인라인으로 만들 때, 두 번 선언하거나 변수에 할당할 필요 없이 한 번만 사용해서 전달할 수 있습니다.
추가했습니다. 감사합니다!

2024-03-01 11:38 UTC, 2chanhaeng commented on files/ko/web/javascript/reference/global_objects/promise/finally/index.md
> +
추가했습니다. 감사합니다!

2024-03-01 11:41 UTC, 2chanhaeng commented
@sunhpark42 안녕하세요. [리뷰](https://github.com/mdn/translated-content/pull/17811#pullrequestreview-1899672253)에서 말씀해주신 변경 요청 사항 수정 완료했습니다! 감사합니다.

2024-03-17 07:21 UTC, sunhpark42 approved these changes
안녕하세요 @2chanhaeng 님, 수정 해주신 부분 확인 했습니다. 감사합니다 :)
오늘도 좋은하루되세요!

2024-03-17 07:22 UTC, sunhpark42 commented
auto-merge 눌러놓겠습니다. 
@hochan222 님, Request Change 확인 부탁드립니다. :)

2024-03-18 14:44 UTC, hochan222 approved these changes
모두 고생 많으셨습니다. 좋은 하루 보내세요 :)

2024-03-18 14:44 UTC, merged