[ko] translate import.meta
mdn/translated-content pull request #17977
Opened 2024-01-20 12:30 UTC by pozafly

- `en-US/docs/Web/JavaScript/Reference/Operators/import.meta` 문서를 한국어로 번역했습니다.
-  MDN에 첫 번역 작업입니다. 리뷰가 필요합니다.

2024-01-20 12:33 UTC, pozafly commented on files/ko/web/javascript/reference/operators/import.meta/index.md
> +`import.meta` 객체는 호스트 환경(브라우저 또는 Node.js 등)에서 모든 속성을 쓰기 가능하고(writable), 구성할 수 있으며(configurable), 열거할 수 있는(enumerable) 확장 가능한(extensible) [`null`-prototype](/en-US/docs/Web/JavaScript/Reference/Global
null-prototype objects는 ko 버전이 없어, en 버전으로 할당해두었습니다.

2024-01-20 12:34 UTC, pozafly commented on files/ko/web/javascript/reference/operators/import.meta/index.md
> +- [`resolve`](/en-US/docs/Web/JavaScript/Reference/Operators/import.meta/resolve)
마찬가지로, import.meta.resolve도 ko 버전이 없어, en 버전으로 할당해두었습니다.

2024-01-20 12:34 UTC, pozafly commented on files/ko/web/javascript/reference/operators/import.meta/index.md
> +`import.meta` 구문은 키워드 `import`, 점(`.`), 식별자로 구성됩니다. `import`는 식별자가 아닌 [예약어](/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#reserved_words)이므로 [속성 접근자](/en-US/docs/Web/JavaScript/Reference/Opera
마찬가지 입니다.

2024-01-20 12:34 UTC, pozafly commented on files/ko/web/javascript/reference/operators/import.meta/index.md
> +`import` 지정자에 쿼리 매개변수를 사용하면 모듈에 특별한 정보를 전달할 수 있으며, 이는 애플리케이션 전체에서 매개변수를 읽을 수 있습니다(브라우저의 경우 [`window.location`](/en-US/docs/Web/API/Window/location), Node.js의 경우 `process.argv`). 예를 들면 다음 HTML이 있습니다:
마찬가지 입니다.

2024-01-25 13:16 UTC, pje1740 requested changes

2024-01-25 13:16 UTC, pje1740 commented on files/ko/web/javascript/reference/operators/import.meta/index.md
> +`import` 지정자에 쿼리 매개변수를 사용하면 모듈에 특별한 정보를 전달할 수 있으며, 이는 애플리케이션 전체에서 매개변수를 읽을 수 있습니다(브라우저의 경우 [`window.location`](/ko/docs/Web/API/Window/location), Node.js의 경우 `process.argv`). 예를 들면 다음 HTML이 있습니다:
```suggestion
`import` 지정자에 쿼리 매개변수를 사용하면 모듈별 인자를 전달할 수 있으며, 이는 애플리케이션 전체에서 매개변수를 읽는 것과 상호보완적일 수 있습니다.(브라우저의 경우 [`window.location`](/ko/docs/Web/API/Window/location), Node.js의 경우 `process.argv`). 예를 들면 다음 HTML이 있습니다:
```

이 부분은 말이 저도 조금 어렵다는 생각은 드는데요!
module-specific argument passing 은 현재 import 하는 특정 모듈에 argument를 넘긴다는 걸로 보여서 모듈별 인자를 넘긴다고 해석을 해주면 어떨까 하여 의견 드립니다.
뒤에는 complementary 하다는 맥락이 누락된 거 같아 추가 드렸습니다!

2024-01-25 13:16 UTC, pje1740 commented on files/ko/web/javascript/reference/operators/import.meta/index.md
> +그러나, Node.js의 CLI 명령(예: `node index.mjs?someURLInfo=5`)을 통해 쿼리 매개변수를 지정한 경우 쿼리(`?`) 또는 해시(`#`)를 사용할 수 없습니다. CLI 엔트리포인트는 CommonJS와 유사한 resolution mode를 사용하기 때문에 경로를 URL이 아닌 파일 경로로 취급하기 때문입니다. 엔트리포인트 모
```suggestion
그러나, Node.js의 CLI 명령(예: `node index.mjs?someURLInfo=5`)을 통해 모듈을 지정한 경우 쿼리(`?`) 또는 해시(`#`)를 사용할 수 없습니다. CLI 엔트리포인트는 CommonJS와 유사한 모듈 해석을 사용하기 때문에 경로를 URL이 아닌 파일 경로로 취급하기 때문입니다. 엔트리포인트 모듈에 매개변수를 전달하려면 CLI 인수를 사용하고 대신 `process.argv`를 통해 매개변수를 읽어야 합니다(예: `node index.mjs --someURLInfo=5`).
```
However, you cannot use queries or hashes when **the module** is specified through the CLI command
-> 원문을 보면 CLI 를 통해 지정된 것이 모듈이라서 수정이 필요해보입니다.

resolution mode는 모듈 해석에 대한 이야기 같아서 가급적 한글을 쓰는 게 어떨까 하여 제안 드립니다.

2024-01-25 13:16 UTC, pje1740 commented on files/ko/web/javascript/reference/operators/import.meta/index.md
> +Node.js CommonJS 모듈에는 현재 모듈이 포함된 폴더의 절대 경로를 포함하는 `__dirname` 변수가 있으며, 이는 상대 경로를 확인하는 데 유용합니다. 그러나 ES modules은 `import.meta`를 제외하고는 컨텍스트 변수를 가질 수 없습니다. 따라서 상대 파일을 확인하려면 `import.meta.url`을 사용할 수 있습니다.
```suggestion
Node.js CommonJS 모듈에는 현재 모듈이 포함된 폴더의 절대 경로를 포함하는 `__dirname` 변수가 있으며, 이는 상대 경로를 절대 경로로 치환하는 데 유용합니다. 그러나 ES modules은 `import.meta`를 제외하고는 컨텍스트 변수를 가질 수 없습니다. 따라서 파일의 위치를 절대 경로로 치환할 때 `import.meta.url`을 사용할 수 있습니다. 이 경우 파일 시스템 경로가 아닌 URL을 사용한다는 점에 유의하세요.
```

path 를 resolve 한다는 말이 정확한 path, 즉 상대 경로로 된 파일의 정확한 절대 경로로 치환하는 걸로 이해되는데요, resolve 자체를 깔끔하게 번역하긴 어려워서 이렇게나마 제안 드려봅니다.

2024-01-25 13:40 UTC, pozafly commented on files/ko/web/javascript/reference/operators/import.meta/index.md
> +`import` 지정자에 쿼리 매개변수를 사용하면 모듈에 특별한 정보를 전달할 수 있으며, 이는 애플리케이션 전체에서 매개변수를 읽을 수 있습니다(브라우저의 경우 [`window.location`](/ko/docs/Web/API/Window/location), Node.js의 경우 `process.argv`). 예를 들면 다음 HTML이 있습니다:
말씀 주신대로, 모듈별 인자를 넘긴다는 말이 좋은 것 같습니다 :)

2024-01-25 13:44 UTC, pozafly commented on files/ko/web/javascript/reference/operators/import.meta/index.md
> +그러나, Node.js의 CLI 명령(예: `node index.mjs?someURLInfo=5`)을 통해 쿼리 매개변수를 지정한 경우 쿼리(`?`) 또는 해시(`#`)를 사용할 수 없습니다. CLI 엔트리포인트는 CommonJS와 유사한 resolution mode를 사용하기 때문에 경로를 URL이 아닌 파일 경로로 취급하기 때문입니다. 엔트리포인트 모
앗 이 부분은 쿼리 매개변수가 아니라 모듈이 맞는 번역인 것 같아요! 제가 번역 실수 한 것 같습니다! 모듈 해석이 일반적으로 한국어로 통용되는 해석인지 애매해 영어로 두었는데 모듈 해석이라고 많이들 이야기하나보네요! 좋습니다.

2024-01-26 11:35 UTC, pje1740 approved these changes
수정사항 적용해주신 것 확인했습니다! 고생하셨습니다 😊

2024-01-26 12:08 UTC, merged

2024-01-26 12:10 UTC, pozafly commented
검토해주셔서 감사합니다!!