docs: Add location property of window object
mdn/translated-content pull request #18082
Opened 2024-01-29 06:55 UTC by ssk910

### Description

`window.location` 속성 번역.

### Motivation

기존 한글 문서가 없어서 추가하였음.

### Additional details

### Related issues and pull requests

2024-01-29 06:56 UTC, ssk910 commented
이 커뮤니티에서 사용되는 커밋 메세지 포맷이 따로 있는지 궁금합니다.
저는 주로 [Angular의 커밋 메세지 가이드라인](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit)을 사용하는데 이 커뮤니티만의 가이드라인이 있다면 따르고 싶습니다.

2024-01-31 08:16 UTC, wisedog requested changes
기여 감사합니다! l10n 외에는 없습니다!

2024-01-31 08:16 UTC, wisedog commented on files/ko/web/api/window/location/index.md
> +slug: Web/API/Window/location
[이 글](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md)을 참고하셔서 메타 데이터에 `l10n`을 넣어주세요.

2024-02-01 00:53 UTC, wisedog approved these changes

2024-02-01 00:53 UTC, merged