[zh-cn]: Add translation for Processing Instruction
mdn/translated-content pull request #18128
Opened 2024-02-02 03:57 UTC by Saraph1nes

Add translation for Processing Instruction

2024-02-02 05:53 UTC, skyclouds2001 commented on files/zh-cn/web/api/processinginstruction/index.md
> +**`ProcessingInstruction`** 接口表示一个[处理指令](https://www.w3.org/TR/xml/#sec-pi); 简单说就是一种包含特定应用指令的 {{domxref("Node")}} ，对于那些不识别该应用指令的程序，会忽略它。
```suggestion
**`ProcessingInstruction`** 接口表示一个[处理指令](https://www.w3.org/TR/xml/#sec-pi)；简单说就是一种包含特定应用指令的 {{domxref("Node")}}，对于那些不识别该应用指令的程序，会忽略它。
```

2024-02-02 05:53 UTC, skyclouds2001 commented on files/zh-cn/web/api/processinginstruction/index.md
> +处理指令可能与 [XML 声明](/zh-CN/docs/Web/XML/XML_introduction#xml_declaration) 不同。
```suggestion
处理指令可能与 [XML 声明](/zh-CN/docs/Web/XML/XML_introduction#xml_declaration)不同。
```

2024-02-02 05:53 UTC, skyclouds2001 commented on files/zh-cn/web/api/processinginstruction/index.md
> +> **备注：** 用户定义的处理指令不能以 `xml` 开头，因为以 `xml` 为前缀的处理指令目标名称是由 xml 规范为特定用途保留的（参见： `<?xml-stylesheet ?>` ）。
```suggestion
> **备注：** 用户定义的处理指令不能以 `xml` 开头，因为以 `xml` 为前缀的处理指令目标名称是由 xml 规范为特定用途保留的（参见：`<?xml-stylesheet ?>`）。
```

2024-02-02 05:53 UTC, skyclouds2001 commented on files/zh-cn/web/api/processinginstruction/index.md
> +_此接口从其父接口 {{domxref("CharacterData")}} 、 {{domxref("Node")}} 和 {{domxref("EventTarget")}} 继承属性。_
```suggestion
_此接口从其父接口 {{domxref("CharacterData")}}、{{domxref("Node")}} 和 {{domxref("EventTarget")}} 继承属性。_
```

2024-02-02 05:53 UTC, skyclouds2001 commented on files/zh-cn/web/api/processinginstruction/index.md
> +_此接口从其父接口 {{domxref("CharacterData")}}、 {{domxref("Node")}} 和 {{domxref("EventTarget")}}继承方法。_
```suggestion
_此接口从其父接口 {{domxref("CharacterData")}}、{{domxref("Node")}} 和 {{domxref("EventTarget")}}继承方法。_
```

2024-02-02 05:53 UTC, skyclouds2001 commented on files/zh-cn/web/api/processinginstruction/index.md
> +  - : 常用于获取包含在 XML 或 HTML 文档中的样式表，如果存在关联的 {{domxref("StyleSheet")}} 对象则返回该对象，如果没有则返回 `null` 。
```suggestion
  - : 常用于获取包含在 XML 或 HTML 文档中的样式表，如果存在关联的 {{domxref("StyleSheet")}} 对象则返回该对象，如果没有则返回 `null`。
```

2024-02-02 05:53 UTC, skyclouds2001 commented on files/zh-cn/web/api/processinginstruction/sheet/index.md
> +**`sheet`** 属性与 {{DOMxref("Stylesheet")}} 对象关联，如果 Stylesheet 不存在，那么值为 `null`
```suggestion
**`sheet`** 属性与 {{DOMxref("Stylesheet")}} 对象关联，如果 Stylesheet 不存在，那么值为 `null`。
```

2024-02-02 05:53 UTC, skyclouds2001 commented on files/zh-cn/web/api/processinginstruction/sheet/index.md
> +- The [DOM API](/zh-CN/docs/Web/API/Document_Object_Model)
```suggestion
- [DOM API](/zh-CN/docs/Web/API/Document_Object_Model)
```

2024-02-02 05:53 UTC, skyclouds2001 commented on files/zh-cn/web/api/processinginstruction/target/index.md
> +- The [DOM API](/zh-CN/docs/Web/API/Document_Object_Model)
```suggestion
- [DOM API](/zh-CN/docs/Web/API/Document_Object_Model)
```

2024-02-02 05:53 UTC, skyclouds2001 commented on files/zh-cn/web/api/processinginstruction/target/index.md
> +**`target`** 属性是 {{domxref("ProcessingInstruction")}} 接口的一个只读属性，它表示该 `处理指令` 的目标。
```suggestion
**`target`** 属性是 {{domxref("ProcessingInstruction")}} 接口的一个只读属性，它表示该处理指令的目标。
```

2024-02-02 05:53 UTC, skyclouds2001 commented on files/zh-cn/web/api/processinginstruction/sheet/index.md
> +**`sheet`** 属性是 {{domxref("ProcessingInstruction")}} 接口的一个只读属性，它包含了与该 `处理指令` 相关联的样式表信息。
```suggestion
**`sheet`** 属性是 {{domxref("ProcessingInstruction")}} 接口的一个只读属性，它包含了与该处理指令相关联的样式表信息。
```

2024-02-02 16:18 UTC, JasonLamv-t commented on files/zh-cn/web/api/processinginstruction/sheet/index.md
> +</root>
```suggestion
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="rule.css"?>
…
```

2024-02-02 16:18 UTC, JasonLamv-t commented on files/zh-cn/web/api/processinginstruction/target/index.md
> +**`target`** 属性是 {{domxref("ProcessingInstruction")}} 接口的一个只读属性，它表示该处理指令的目标。
```suggestion
**`target`** 属性是 {{domxref("ProcessingInstruction")}} 接口的一个只读属性，它表示该 `ProcessingInstruction` 的目标。
```

2024-02-02 16:18 UTC, JasonLamv-t commented on files/zh-cn/web/api/processinginstruction/target/index.md
> +例子：
```suggestion
例如：
```

2024-02-02 16:18 UTC, JasonLamv-t commented on files/zh-cn/web/api/processinginstruction/target/index.md
> +是一个包含应用程序名称的字符串。
```suggestion
一个包含应用程序名称的字符串。
```

2024-02-03 13:46 UTC, jasonren0403 requested changes
我这里还有一些建议

2024-02-03 13:46 UTC, jasonren0403 commented on files/zh-cn/web/api/processinginstruction/index.md
> +  - : 如果存在关联的 {{domxref("StyleSheet")}} 对象则返回，如果没有则为 `null` 。
```suggestion
  - : 如果存在关联的 {{domxref("StyleSheet")}} 对象，则返回该对象；否则为 `null` 。
```

2024-02-03 13:46 UTC, jasonren0403 commented on files/zh-cn/web/api/processinginstruction/sheet/index.md
> +title: "ProcessingInstruction: sheet property"
下方的 short-title 可移除

```suggestion
title: ProcessingInstruction：sheet 属性
```

2024-02-03 13:46 UTC, jasonren0403 commented on files/zh-cn/web/api/processinginstruction/sheet/index.md
> +**`sheet`** 属性是 {{domxref("ProcessingInstruction")}} 接口的一个只读属性，它包含了与该 `ProcessingInstruction ` 相关联的样式表信息。
```suggestion
**`sheet`** 属性是 {{domxref("ProcessingInstruction")}} 接口的一个只读属性，它包含了与该 `ProcessingInstruction` 相关联的样式表信息。
```

2024-02-03 13:46 UTC, jasonren0403 commented on files/zh-cn/web/api/processinginstruction/sheet/index.md
> +**`sheet`** 属性与 {{DOMxref("Stylesheet")}} 对象关联，如果 Stylesheet 不存在，那么值为 `null`。
https://github.com/mdn/content/blob/c0e47421330d58d462e8240405a5738332514d1c/files/en-us/web/api/processinginstruction/sheet/index.md?plain=1#L18

再看看原文

2024-02-03 13:46 UTC, jasonren0403 commented on files/zh-cn/web/api/processinginstruction/target/index.md
> +title: "ProcessingInstruction: target property"
下方 short-title 可移除

```suggestion
title: ProcessingInstruction：target 属性
```

2024-02-04 03:09 UTC, Saraph1nes commented on files/zh-cn/web/api/processinginstruction/sheet/index.md
> +**`sheet`** 属性与 {{DOMxref("Stylesheet")}} 对象关联，如果 Stylesheet 不存在，那么值为 `null`。
是的，直接翻译更好

2024-02-05 05:39 UTC, jasonren0403 approved these changes
LGTM, Thanks @Saraph1nes @JasonLamv-t @skyclouds2001 👍

2024-02-05 05:45 UTC, merged