[zh-tw]: translate 5 HTML element
mdn/translated-content pull request #18146
Opened 2024-02-03 12:22 UTC by Dr-XYZ

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-02-03 12:57 UTC, Dr-XYZ commented
Why need to edit the same? and where is wrong?

2024-02-03 14:21 UTC, yin1999 commented
> Why need to edit the same? and where is wrong?

Please preserve the EOF of each file, that means adding an empty line for each file.

2024-02-06 02:24 UTC, yin1999 requested changes
Hi @Dr-XYZ. I've listed some commom problem (for all those documents). Could you fix them before I have a deep check?

2024-02-06 02:24 UTC, yin1999 commented on files/zh-tw/web/html/element/article/index.md
> +title: "<article>: 文章內容元素"
Please use a full-width colon and remove the quotes

```suggestion
title: <article>：文章內容元素
```

2024-02-06 02:24 UTC, yin1999 commented on files/zh-tw/web/html/element/article/index.md
> +        <a
The line break will produce a "space" between the punctuation and Chinese words ([translation-guide](https://github.com/mdn/translated-content/blob/main/docs/zh-tw/translation-guide.md#%E4%B8%AD%E6%96%87%E5%8F%8A%E6%8B%89%E4%B8%81%E8%AA%9E%E7%B3%BB%E6%96%87%E5%AD%97%E9%96%93%E4%B8%8D%E5%8A%A0%E4%BF%AE%E9%A3%BE%E7%A9%BA%E7%99%BD)):

```suggestion
        >、<a
```

2024-02-06 02:24 UTC, yin1999 commented on files/zh-tw/web/html/element/article/index.md
> +        <a href="/zh-TW/docs/Web/HTML/Content_categories#flow_content"
Translate the hash, and do not add line break here (see the above)
```suggestion
        任何接受<a
          href="/zh-TW/docs/Web/HTML/Content_categories#流內容"
```

2024-02-06 02:24 UTC, yin1999 commented on files/zh-tw/web/html/element/article/index.md
> +        <a href="/zh-TW/docs/Web/Accessibility/ARIA/Roles/feed_role"><code>feed</code></a>、<a href="/zh-TW/docs/Web/Accessibility/ARIA/Roles/main_role"><code>main</code></a>、
do not add line break

2024-02-06 02:24 UTC, yin1999 commented on files/zh-tw/web/html/element/article/index.md
> +{{EmbedLiveSample('Examples','','570')}}
[translate the ID](https://github.com/mdn/translated-content/blob/main/docs/zh-tw/translation-guide.md#%E7%BF%BB%E8%AD%AF%E6%A8%99%E9%A1%8C-id)

```suggestion
{{EmbedLiveSample('範例','','570')}}
```

2024-02-06 02:24 UTC, yin1999 commented on files/zh-tw/web/html/element/article/index.md
> +## 規格
see [common translation](https://github.com/mdn/translated-content/blob/main/docs/zh-tw/translation-guide.md#%E5%B8%B8%E8%A6%8B%E6%A8%99%E9%A1%8C%E6%88%96%E8%A9%9E%E5%BD%99)

```suggestion
## 規範
```

2024-02-06 02:24 UTC, yin1999 commented on files/zh-tw/web/html/element/article/index.md
> +## 參閱
```suggestion
## 參見
```

2024-02-06 02:24 UTC, yin1999 commented on files/zh-tw/web/html/element/base/index.md
> +**`<base>`** [HTML](/zh-TW/docs/Web/HTML) 元素指定用於文件中所有 _相對_ URL 的基礎 URL。一個文件中只能有一個 `<base>` 元素。
Do not add spaces between Chinese words.

```suggestion
**`<base>`** [HTML](/zh-TW/docs/Web/HTML) 元素指定用於文件中所有*相對* URL 的基礎 URL。一個文件中只能有一個 `<base>` 元素。
```

2024-02-06 02:31 UTC, Dr-XYZ commented
Sure

2024-02-22 07:21 UTC, yin1999 approved these changes
Thank you @Dr-XYZ

2024-02-22 07:22 UTC, merged