docs(ko): Add glossary list
mdn/translated-content pull request #18224
Opened 2024-02-13 09:32 UTC by 1ilsang

### Description

- https://github.com/mdn/translated-content/pull/18220 번역 하면서 glossary에 추가되었으면 하는 단어들 추가했습니다.

추가된 gloassary 리스트
- workflow | 워크플로우
- tag | 태그
- mechanism | 메커니즘
- license | 라이선스
- protocol | 프로토콜
- on-demand(onDemand) | 온디맨드
- profile | 프로필
- custom | 커스텀
- trigger | 트리거
- event | 이벤트
- control | 컨트롤
- space bar | 스페이스바
- tip | 팁
- media | 미디어
- trick | 트릭
- hash | 해시
- error | 에러
- mime | MIME
- fallback | 폴백
- library | 라이브러리
- cross-browser | 크로스 브라우저
- tutorial | 튜토리얼
- capture | 캡처

### Related issues and pull requests

- https://github.com/mdn/translated-content/issues/18056

2024-02-17 07:23 UTC, yechoi42 commented on docs/ko/guides/glossary-guide.md
> +| Space bar           | 스페이스바      |                                                                                                        |
```suggestion
| Space bar           | 스페이스 바      |                                                                                                        |
```
(사전)[https://ko.dict.naver.com/#/entry/koko/6c25d09686a44656b12c12676c3e3f8b]에 등재된 것처럼 띄어쓰기 추가되면 좋겠습니다!

2024-02-21 11:42 UTC, pje1740 commented
저는 이견은 없습니다! 궁금한 것이 하나 있는데요,
trick이라는 단어가 사용되는 맥락을 예시로 볼 수 있을까요?? 개발에서 일반적으로 사용하는 특정 용어가 따로 있는 건지 궁금해서 여쭤봅니다! 😊

2024-02-21 13:54 UTC, 1ilsang commented
@pje1740 님

```md
- Here's a trick that stops the download at once:
+ 다음은 다운로드를 한 번에 중지하는 트릭입니다.
```

여기를 어떻게 해석할지 고민하다 트릭을 그대로 가져왔습니다.

- ref: https://github.com/mdn/translated-content/commit/63cd55735a1e07b0359bdc788a906eb87c315d21#diff-3472f625edaec88a2e81c2d75b96a231f65d086381dc3b9863ab37378129d90eL311

2024-02-23 07:38 UTC, pje1740 commented
아아 공유 감사합니다! 😆

개인적인 생각을 추가해보자면요,
- trick은 고유 명사는 아니고 한국어로 어감을 살려 다르게 번역이 가능 (요령, 방법, 노하우 등)
  - ~~물론... 노하우도 영어입니다만 😅~~

한국어로 트릭이라고 하면 뭔가 속임수의 어감이 강한데요, 영어에서의 트릭은 `간단하게 처리할 수 있는 요령` 정도의 어감을 가지고 있다고 생각합니다. 그래서 번역하시는 분들이 어감에 따라 다른 표현을 자유롭게 쓰시는 편이 좋을 거 같아서 glossary로 번역을 고정시키진 않아도 괜찮지 않을까 싶습니다! 

그래서 위에서 예시로 주신 문장은
```
다음은 다운로드를 한 번에 중지하는 요령/노하우/방법입니다.
```
로 번역해도 충분히 느낌을 살릴 수 있을 거 같습니다.

제 개인적인 생각이라 이견이 있으시면 편하게 남겨주세요!! 😊

2024-02-23 09:57 UTC, 1ilsang commented
@pje1740 님 

동의합니다. trick은 제외했습니다.

2024-02-23 12:26 UTC, pje1740 approved these changes
유연하게 의견 반영해주셔서 감사합니다!! 저는 이견 없어서 approve 눌러두겠습니다! ㅎㅎㅎ

2024-03-07 02:53 UTC, hochan222 requested changes
@1ilsang 님 안녕하세요~! 

몇 가지 리뷰사항 하기에 남겨두었습니다! 고생 정말 많으셨습니다~!

2024-03-07 02:53 UTC, hochan222 commented on docs/ko/guides/glossary-guide.md
> +| Error               | 에러            |                                                                                                        |
```suggestion
| Error               | 오류            |                                                                                                        |
```

@mdn/yari-content-ko 음차보다 "오류" 의견드립니다. 적절한 번역이 있음에도 변경하신 이유가 있을지 궁금합니다.

아래는 한국 문서 사용 현황입니다.

에러: 382 results in 181 files
오류: 756 results in 258 files

2024-03-07 02:53 UTC, hochan222 commented on docs/ko/guides/glossary-guide.md
> +| Custom              | 커스텀          |                                                                                                        |
```suggestion
| Custom              | 사용자 정의          |                                                                                                        |
```

번역 작업에 대한 절대적 기준을 설정하는 것도 어렵고, 올바른 언어 사용을 위한 절대적 기준을 마련하는 것도 어려운데요. 기본적인 방향성은 애매한 경우, 적절한 번역이 있으면 번역한다로 공유하고 있습니다.

Custom이 조금 애매한 경우라고 생각합니다. 이전에 논의 했을 때는 "사용자 정의"로 논의가 되었습니다. 혹시 "커스텀"으로 추가해주신 이유가 있을지 궁금합니다.  

+ 아래는 한국 문서 사용 현황입니다.

사용자 정의: 221 results in 96 files
커스텀: 97 results in 39 files

2024-03-07 02:53 UTC, hochan222 commented on docs/ko/guides/glossary-guide.md
> +| Method              | 메서드          | [국립국어원 Method](https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=11976) |
```suggestion
| Method              | 메서드          | method [meθəd] 메서드 |
```

국립 국어원 게시글은 시간이 지나면 삭제되어 때문에 제거했습니다.

2024-03-08 13:17 UTC, 1ilsang commented on docs/ko/guides/glossary-guide.md
> +| Error               | 에러            |                                                                                                        |
에러가 더 익숙해서 에러라고 하였는데요, 번역 입장에서 오류가 더 좋을것 같네요. 감사합니다

2024-03-08 13:34 UTC, 1ilsang commented on docs/ko/guides/glossary-guide.md
> +| Custom              | 커스텀          |                                                                                                        |
사용자 정의로 변경했습니다 [0cca942](https://github.com/mdn/translated-content/pull/18224/commits/0cca942090754c3b8574e001503830aa0226ff7f)

2024-03-09 22:31 UTC, hochan222 commented on docs/ko/guides/glossary-guide.md
> +| Custom              | 커스텀          |                                                                                                        |
아하 이해했습니다! 

이미 이전에 논의가 되어서 사용자 정의로 넣자는 의도보다는 안내서 넣기 전에 더 좋은 의견이 있을까해서 여쭤보았습니다.

@1ilsang 좋은 하루 보내세용!

2024-03-09 22:32 UTC, hochan222 approved these changes
빠르게 반영 및 답변해주셔서 감사합니다~! 어프로브 눌렀습니다! 

cc @yechoi42

2024-03-16 06:28 UTC, merged