[ko]: Translate :placeholder-shown pseudo-class docs
mdn/translated-content pull request #18239
Opened 2024-02-15 10:40 UTC by C17AN

### Description

- [:placeholder-shown](https://developer.mozilla.org/en-US/docs/Web/CSS/:placeholder-shown) 문서의 한글 번역을 추가합니다.

### Motivation

### Additional details

### Related issues and pull requests

2024-02-15 10:46 UTC, C17AN commented on files/ko/web/css/_colon_placeholder-shown/index.md
> +  sourceCommit: 5fea7c9593f5e4b4ef13ec65064acf1eabf01e4e
https://github.com/mdn/content/commit/5fea7c9593f5e4b4ef13ec65064acf1eabf01e4e

- `sourceCommit` 링크입니다.

2024-02-15 10:46 UTC, C17AN commented on files/ko/web/css/_colon_placeholder-shown/index.md
> +### 오버플로우되는 텍스트
원문은 "Overflowing text" 인데, "넘치는 텍스트" 라고 번역하면 '무엇이' 넘치는 텍스트 인지 모호하게 읽힐 수 있다고 생각해 원문을 음차해 사용했습니다.

2024-02-15 10:46 UTC, C17AN commented on files/ko/web/css/_colon_placeholder-shown/index.md
> +    <label for="branch">학생부를 입력하세요:</label>
`Student Branch` 를 찾아보니 `학생부` 라는 의미인데 우리 정서와 맞는지에 대한 의문이 있었습니다.
우선은 주어진 그대로 번역했으나, 더 나은 단어를 제안해주셔도 감사드리겠습니다 🙇

2024-02-15 10:47 UTC, C17AN commented
안녕하세요, CSS 의사 클래스중 하나인 `:placeholder-shown` 의 문서를 번역해 보았습니다.
아직 많이 부족해 어색한 부분들이 있을 수 있는데요, 피드백을 남겨주시면 최대한 빠르게 반영할 수 있도록 하겠습니다. 🙇

2024-03-02 16:13 UTC, C17AN reviewed
.

2024-03-17 06:57 UTC, sunhpark42 requested changes
안녕하세요 @C17AN 님, 리뷰가 늦어 죄송합니다.
코멘트 남겨두었습니다. 확인 부탁드립니다.
두 건은 제안 정도라서 확인 부탁드리며, 기울임꼴 관련해서 수정부탁드립니다.

기여 감사합니다:) 좋은하루되세요!

2024-03-17 06:57 UTC, sunhpark42 commented on files/ko/web/css/_colon_placeholder-shown/index.md
> +- {{CSSxRef("::placeholder")}} 의사 요소는 플레이스홀더 *자체*를 꾸밉니다.
가이드의 기울임꼴 안내에 따라 기울임꼴 스타일 삭제 부탁드립니다. =
https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md#%EA%B8%B0%EC%9A%B8%EC%9E%84%EA%BC%B4

2024-03-17 06:57 UTC, sunhpark42 commented on files/ko/web/css/_colon_placeholder-shown/index.md
> +    <label for="branch">학생부를 입력하세요:</label>
저도 찾아보니 student branch 는  학생 부서, 학생회 같은 느낌의 단어네요.🤔
지금 이대로 유지해도 괜찮지 않을까 싶어요.

2024-03-17 06:57 UTC, sunhpark42 commented on files/ko/web/css/_colon_placeholder-shown/index.md
> +### 오버플로우되는 텍스트
전 요부분은 문자열이 가로 크기를 넘겨서 잘리는 의미를 가지고 있기 때분에, 넘치는이라고 번역해도 괜찮다고 생각합니다. 추가로 텍스트도 문자로 번역 할 수 있을 것 같아요.
다른 번역으로는 문자열 넘침은 어떨까요?

2024-03-17 08:13 UTC, C17AN commented on files/ko/web/css/_colon_placeholder-shown/index.md
> +### 오버플로우되는 텍스트
'문자열 넘침' 깔끔한 것 같아요! 좋은 의견 주셔서 감사합니다! 🙂

2024-03-17 08:17 UTC, C17AN commented on files/ko/web/css/_colon_placeholder-shown/index.md
> +- {{CSSxRef("::placeholder")}} 의사 요소는 플레이스홀더 *자체*를 꾸밉니다.
네, 수정해서 다시 올려두었습니다! 🙇‍♂️

2024-03-17 08:21 UTC, C17AN commented
안녕하세요, @sunhpark42 님!
기울임꼴 수정 및 남겨주신 제안대로 수정해 두어, 다시 한번 확인해주시면 감사드리겠습니다.

바쁘신 와중에 시간을 내어 주셔서 감사드립니다!

2024-03-17 08:37 UTC, sunhpark42 approved these changes
안녕하세요 @C17AN 님, 수정해주신 부분 확인했습니다.
추가 수정사항은 없어 머지하도록 하겠습니다.
기여 감사합니다~!  👍👍 좋은 하루되세요 :)

2024-03-17 08:37 UTC, merged