Added translated content for regular expression glossary
mdn/translated-content pull request #18246
Opened 2024-02-16 13:33 UTC by nathipg

### Description

Added new page

### Motivation

Help to add pt-br pages to MDN

### Additional details

NA

### Related issues and pull requests

NA

2024-02-27 01:35 UTC, josielrocha requested changes
Obrigado pela ajuda @nathipg!
Deixei um pequeno apontamento, poderia verificar por favor?

2024-02-27 01:35 UTC, josielrocha commented on files/pt-br/glossary/regular_expression/index.md
> +Expressões regulares são implementadas em várias linguagens, mas a implementação mais conhecida é a do Pearl, a qual deu origem ao seu próprio ecossistema de implementações chamado de PCRE (_Perl Com
```suggestion
Expressões regulares são implementadas em várias linguagens, mas a implementação mais conhecida é a do Perl, a qual deu origem ao seu próprio ecossistema de implementações chamado de PCRE (_Perl Compatible Regular Expression_). Na Web, o {{glossary("JavaScript")}} provê outra implementação da regex por meio do objeto {{jsxref("RegExp")}}.
```

2024-02-29 14:29 UTC, nathipg commented on files/pt-br/glossary/regular_expression/index.md
> +Expressões regulares são implementadas em várias linguagens, mas a implementação mais conhecida é a do Pearl, a qual deu origem ao seu próprio ecossistema de implementações chamado de PCRE (_Perl Com
Boa!

2024-03-01 16:38 UTC, josielrocha approved these changes
LGTM ;)

2024-03-01 16:38 UTC, merged