[zh-cn] update 'The box model'
mdn/translated-content pull request #18264
Opened 2024-02-18 16:05 UTC by jasonren0403

### Description

Update 'The box model'

### Motivation

### Additional details

### Related issues and pull requests

fixes #17757 
part of #12632

2024-02-18 16:09 UTC, jasonren0403 commented on files/zh-cn/learn/css/building_blocks/the_box_model/index.md
> +本文已经结束，你还记得最重要的信息吗？在继续学习之前，可以找到一些进一步的测试来验证您是否保留了这些信息——请参阅[技能测试：盒模型](/zh-CN/docs/Learn/CSS/Building_blocks/Box_Model_Tasks)。
```suggestion
本文已经结束，你还记得最重要的信息吗？在继续学习之前，可以找到一些进一步的测试来验证你是否保留了这些信息——请参阅[技能测试：盒模型](/zh-CN/docs/Learn/CSS/Building_blocks/Box_Model_Tasks)。
```

2024-02-18 16:11 UTC, jasonren0403 commented on files/zh-cn/learn/css/building_blocks/the_box_model/index.md
> +[浏览器开发者工具](/zh-CN/docs/Learn/Common_questions/Tools_and_sestup/What_are_browser_developer_tools)可以使你更容易地理解盒模型。如果你在 Firefox 的 DevTools 中查看一个元素，你可以看到元素的大小以及它的外边距、内边距和边框。这是一个很好的检查元素大小的方式，可以便捷的判断你的盒子大小是否
```suggestion
[浏览器开发者工具](/zh-CN/docs/Learn/Common_questions/Tools_and_setup/What_are_browser_developer_tools)可以使你更容易地理解盒模型。如果你在 Firefox 的 DevTools 中查看一个元素，你可以看到元素的大小以及它的外边距、内边距和边框。这是一个很好的检查元素大小的方式，可以便捷的判断你的盒子大小是否符合预期！
```

2024-02-20 14:08 UTC, awxiaoxian2020 requested changes

2024-02-20 14:08 UTC, awxiaoxian2020 commented on files/zh-cn/learn/css/building_blocks/the_box_model/index.md
> +这就是你需要了解的关于盒子模型的大部分内容。今后，如果你对布局中盒子的大小感到困惑，不妨再来学习这一课。
```suggestion
这就是你需要了解的关于盒子模型的大部分内容。今后，如果你对布局中盒子的大小感到困惑，不妨再回来看看这些内容。
```

2024-02-21 01:32 UTC, yin1999 reviewed
Some suggestions:

2024-02-21 01:32 UTC, yin1999 commented on files/zh-cn/learn/css/building_blocks/the_box_model/index.md
> +**要在显示模式之间切换，可以将 `display: inline` 更改为 `display: block`，或将 `display: inline-flex` 更改为 `display: flex`** 。
```suggestion
**要在显示模式之间切换，可以将 `display: inline` 更改为 `display: block`，或将 `display: inline-flex` 更改为 `display: flex`。**
```

2024-02-21 01:32 UTC, yin1999 commented on files/zh-cn/learn/css/building_blocks/the_box_model/index.md
> +### 使用浏览器调试工具来查看盒模型
```suggestion
### 使用浏览器开发者工具来查看盒模型
```

2024-02-21 01:32 UTC, yin1999 commented on files/zh-cn/learn/css/building_blocks/the_box_model/index.md
> +![使用 Firefox DevTools 检查元素的盒模型](box-model-devtools.png)
```suggestion
![使用 Firefox 开发者工具检查元素的盒模型](box-model-devtools.png)
```

2024-02-21 01:32 UTC, yin1999 commented on files/zh-cn/learn/css/building_blocks/the_box_model/index.md
> +在上面的示例中，你已经看到了{{cssxref("margin")}}、{{cssxref("padding")}}和{{cssxref("border")}}属性的作用。该示例中使用了**简写属性**，允许我们一次性设置盒子的所有边。这些简写属性也有等效的普通属性，可以单独控制盒子的不同边。
```suggestion
在上面的示例中，你已经看到了 {{cssxref("margin")}}、{{cssxref("padding")}} 和 {{cssxref("border")}} 属性的作用。该示例中使用了**简写属性**，允许我们一次性设置盒子的所有边。这些简写属性也有等效的普通属性，可以单独控制盒子的不同边。
```

2024-02-21 01:32 UTC, yin1999 commented on files/zh-cn/learn/css/building_blocks/the_box_model/index.md
> +**你可以通过将第 2 段的 `margin-top` 设置为 0 来测试它。两个段落之间的可见边距不会改变——它保留了第一个段落 `margin-bottom` 设置的 50 像素。如果将其设置为 -10px，你会发现总边距变成了 40px（从 50px 中减去该负值）**
```suggestion
**你可以通过将第 2 段的 `margin-top` 设置为 0 来测试它。两个段落之间的可见边距不会改变——它保留了第一个段落 `margin-bottom` 设置的 50 像素。如果将其设置为 -10px，你会发现总边距变成了 40px（从 50px 中减去该负值）。**
```

2024-02-21 01:32 UTC, yin1999 commented on files/zh-cn/learn/css/building_blocks/the_box_model/index.md
> +- 如果其中一个外边距为负值，其值将从总值中*减*去。
```suggestion
- 如果其中一个外边距为负值，其值将从总值中*减去*。
```

2024-02-21 04:52 UTC, yin1999 approved these changes
Thank you @jasonren0403, @awxiaoxian2020

2024-02-21 04:53 UTC, merged