Firefox 122 for developersを更新
mdn/translated-content pull request #18304
Opened 2024-02-24 00:59 UTC by yyss

Feb 14, 2024の英語版に対応。

2024-02-29 07:40 UTC, mfuji09 requested changes
遅くなってすみません。
1件の修正をお願いします。

2024-02-29 07:40 UTC, mfuji09 commented on files/ja/mozilla/firefox/releases/122/index.md
> +- ほかのブラウザーに合わせるため [`Date.parse()`](/ja/docs/Web/JavaScript/Reference/Global_Objects/Date/parse) および [`Date()` コンストラクター](/ja/docs/Web/JavaScript/Reference/Global_Objects/Date/Date) は、[非標準の日付文字列](/ja/d
`#non-standard_date_strings` のフラグメントは翻訳されていますので、翻訳後のフラグメントに置き換えてください。

2024-03-02 12:41 UTC, yyss commented on files/ja/mozilla/firefox/releases/122/index.md
> +- ほかのブラウザーに合わせるため [`Date.parse()`](/ja/docs/Web/JavaScript/Reference/Global_Objects/Date/parse) および [`Date()` コンストラクター](/ja/docs/Web/JavaScript/Reference/Global_Objects/Date/Date) は、[非標準の日付文字列](/ja/d
修正しました。

2024-03-03 03:22 UTC, mfuji09 approved these changes
OKです。

2024-03-03 03:23 UTC, merged