Firefox 123 for developersを翻訳
mdn/translated-content pull request #18306
Opened 2024-02-24 02:52 UTC by yyss

Feb 20, 2024の英語版に対応。

2024-02-29 07:43 UTC, mfuji09 requested changes
1件の対応をお願いします。

2024-02-29 07:43 UTC, mfuji09 commented on files/ja/mozilla/firefox/releases/123/index.md
> +  - 不完全なタイムゾーン (たとえば "1/1/70 gm") や午前/午後 (たとえば "1/1/70 10:00 a") を受け入れないようになりました。・([Firefox bug 1870570](https://bugzil.la/1870570))
不自然な中点があるので、削除してください。
```suggestion
  - 不完全なタイムゾーン (たとえば "1/1/70 gm") や午前/午後 (たとえば "1/1/70 10:00 a") を受け入れないようになりました。([Firefox bug 1870570](https://bugzil.la/1870570))
```

2024-02-29 07:43 UTC, mfuji09 commented on files/ja/mozilla/firefox/releases/123/index.md
> +- ページが必要とする可能性があるリソースを、サーバーがまだ完全なレスポンスを準備している間に [先読み](/ja/docs/Web/HTML/Attributes/rel/preload) するための HTTP [`103 Early Hints`](/ja/docs/Web/HTTP/Status/103) [情報レスポンス](/ja/docs/Web/HTTP/Status#informa
フラグメントも翻訳するようお願いします。（以下同様）

2024-03-02 12:42 UTC, yyss commented on files/ja/mozilla/firefox/releases/123/index.md
> +- ページが必要とする可能性があるリソースを、サーバーがまだ完全なレスポンスを準備している間に [先読み](/ja/docs/Web/HTML/Attributes/rel/preload) するための HTTP [`103 Early Hints`](/ja/docs/Web/HTTP/Status/103) [情報レスポンス](/ja/docs/Web/HTTP/Status#informa
2か所修正しました。

2024-03-03 03:23 UTC, mfuji09 approved these changes
OKです。ありがとうございました。

2024-03-03 03:24 UTC, merged