[ko] DataView.getBigInt64()/getBigUint64() 추가
mdn/translated-content pull request #18355
Opened 2024-02-29 04:10 UTC by wisedog

- DataView.getBigInt64 추가
- DataView.getBigUint64 추가

2024-03-16 14:49 UTC, yechoi42 requested changes
안녕하세요! 원문과 다른 부분이 몇가지 있어 수정 코멘트 남겨두었습니다. 확인 부탁드립니다 :) 다시 제게 리뷰 요청하거나 저를 멘션해주시면, 다시 확인해보겠습니다.

2024-03-16 14:49 UTC, yechoi42 commented on files/ko/web/javascript/reference/global_objects/dataview/getbigint64/index.md
> +8바이트를 읽고 이를 부호있는 8비트 정수로 해석합니다. 정렬 제약 조건은 없으며, 범위 내의 모든 오프셋에서 멀티바이트 값을 가져올 수 있습니다.
```suggestion
8바이트를 읽고 이를 부호있는 64비트 정수로 해석합니다. 정렬 제약 조건은 없으며, 범위 내의 모든 오프셋에서 멀티바이트 값을 가져올 수 있습니다.
```
[원문](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/dataview/getbigint64/index.md)에 따르면 64비트로 해석합니다!

2024-03-16 14:49 UTC, yechoi42 commented on files/ko/web/javascript/reference/global_objects/dataview/getbiguint64/index.md
> +8바이트를 읽고 이를 부호없는 8비트 정수로 해석합니다. 정렬 제약 조건은 없으며, 범위 내의 모든 오프셋에서 멀티바이트 값을 가져올 수 있습니다.
```suggestion
8바이트를 읽고 이를 부호없는 64비트 정수로 해석합니다. 정렬 제약 조건은 없으며, 범위 내의 모든 오프셋에서 멀티바이트 값을 가져올 수 있습니다.
```
여기도 마찬가지로 [원문](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/dataview/getbiguint64/index.md?plain=1)은 64이네요

2024-03-16 14:49 UTC, yechoi42 commented on files/ko/web/javascript/reference/global_objects/dataview/getbiguint64/index.md
> +  - : [리틀 엔디언 혹은 빅 엔디언](/ko/docs/Glossary/Endianness) 형식으로 16비트 정수를 저장할지
```suggestion
  - : [리틀 엔디언 혹은 빅 엔디언](/ko/docs/Glossary/Endianness) 형식으로 저장할지
```
16비트 정수에 대한 언급은 없어 삭제했습니다

2024-03-16 14:49 UTC, yechoi42 commented on files/ko/web/javascript/reference/global_objects/dataview/getbigint64/index.md
> +  - : [리틀 엔디언 혹은 빅 엔디언](/ko/docs/Glossary/Endianness) 형식으로 16비트 정수를 저장할지
```suggestion
  - : [리틀 엔디언 혹은 빅 엔디언](/ko/docs/Glossary/Endianness) 형식으로  저장할지
```
원문과 동일하게 수정하였습니다

2024-03-17 04:50 UTC, wisedog commented
제가 비슷한것끼리 하다보니 복붙하는 과정에서 좀 실수가 있었네요! 리뷰 감사드립니다!

2024-03-24 13:11 UTC, yechoi42 approved these changes
반영 감사합니다! 머지하겠습니다.

2024-03-24 13:11 UTC, merged