Change incorrect translation of concurrency index.md
mdn/translated-content pull request #18396
Opened 2024-03-03 22:44 UTC by At-Sky

### Description

1) Event Loop has nothing to do with concurrency and multithreading. The event loop is responsible for asynchronous model in java script.

2) The term parallelism should be excluded from the article because the article mentions several ways of concurrency code execution in a java script (asynchronous model, multithreading with webworkers). And parallelism is not mentioned. 

3) You should also exclude any comparisons with other concurrency models of code execution (C and Java), since the article initially speaks about asynchronousness and not about parallelism or multithreading.

4) The term concurrency execution does not say how this concurrency will be obtained, for example, in our case we switch the execution thread using await. That is, we are not tied to any implementation, as it was in the article before.

5) The term parallelism in relation to asynchrony is misleading for beginners.

### Motivation

Help readers to properly understand what concurency and async is.

### Additional details

Rob Pike - Concurrency is not Parallelism - https://youtu.be/oV9rvDllKEg?si=DPYT0P5yeFnvgjyq
https://en.wikipedia.org/wiki/Concurrency_(computer_science)
https://www.baeldung.com/cs/concurrency-vs-parallelism

2024-03-03 22:46 UTC, Ansyr commented
I'm agree with this. This is a good statement

2024-03-04 07:41 UTC, 6616454 commented
good point. parallelism in relation to asynchrony constantly misleads newbies

2024-03-04 10:22 UTC, DmytroBaturin commented
Oh man. GOOD POINT!

2024-03-04 10:22 UTC, Solpio commented
LGTM

2024-03-04 11:06 UTC, melonges commented
as a native Russian speaker, I agree

2024-03-17 08:51 UTC, saionaro requested changes
@At-Sky hey! That's a great catch, thank you for pointing it out. However, we'd like to be more aligned with an original [EN version](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Event_loop).

What do you think about removing the parallelism term out the article title completely and rephrasing the first paragraph?

2024-03-19 06:10 UTC, saionaro approved these changes
@At-Sky thank you! LGTM

2024-03-19 06:17 UTC, merged

2024-03-19 09:39 UTC, Ansyr commented
@saionaro. @At-Sky forgot to change aside translation in this PR, approve this too please:
(https://github.com/mdn/yari/pull/10735)

2024-03-19 15:40 UTC, leon-win commented
Привет, @At-Sky, @saionaro!

А я думаю, что это неправильные изменения. На 8-ой строке в оригинале речь идёт о `runtime model`, то есть о модели выполнения кода, про асинхронность и не следовало добавлять.

И удаление сравнения с C тоже непонятно: во-первых, оно есть в оригинале, во-вторых, сравнение с другими языками программирования как раз помогает понять особенность Javascript.

2024-03-19 15:42 UTC, leon-win commented
А кстати почему такое внимание к этому ПРу большое?))
@At-Sky,  @Ansyr , @6616454 , @DmytroBaturin , @Solpio, вы все друзья/одноклассники?

2024-03-19 16:51 UTC, 6616454 commented
> Привет, @At-Sky, @saionaro!
> 
> А я думаю, что это неправильные изменения. На 8-ой строке в оригинале речь идёт о `runtime model`, то есть о модели выполнения кода, про асинхронность и не следовало добавлять.
> 
> И удаление сравнения с C тоже непонятно: во-первых, оно есть в оригинале, во-вторых, сравнение с другими языками программирования как раз помогает понять особенность Javascript.

ок, это валидно. главное убрать все, что связано с параллелизмом и многопоточностью в рассуждениях, где фигурирует ивент луп.

2024-03-19 17:06 UTC, At-Sky commented
> А кстати почему такое внимание к этому ПРу большое?)) @At-Sky, @Ansyr , @6616454 , @DmytroBaturin , @Solpio, вы все друзья/одноклассники?

борцы за правильный перевод

2024-03-19 17:10 UTC, 6616454 commented
> > Привет, @At-Sky, @saionaro!
> > А я думаю, что это неправильные изменения. На 8-ой строке в оригинале речь идёт о `runtime model`, то есть о модели выполнения кода, про асинхронность и не следовало добавлять.
> > И удаление сравнения с C тоже непонятно: во-первых, оно есть в оригинале, во-вторых, сравнение с другими языками программирования как раз помогает понять особенность Javascript.
> 
> ок, это валидно, можно явно написать асинк рантайм. главное убрать все, что связано с параллелизмом и многопоточностью в рассуждениях, где фигурирует ивент луп. а тейк про С валиден только при отсутствии многоядерной среды

но про С тут уже к ориг. источнику, думаю никто против не будет, чтобы это вернули.