[ko] Set.prototype.values()/ keys()/ size 최신화
mdn/translated-content pull request #18451
Opened 2024-03-07 04:17 UTC by wisedog

아래 항목 최신화
- Set.prototype.values()
- Set.prototype.keys()
- Set.prototype.size

2024-03-16 10:59 UTC, hochan222 requested changes
@wisedog 님 좋은 주말입니다~!

몇 가지 제안 남겨두었는데, 의견 주시면 바로 병합하겠습니다!

고생 많으셨습니다. 좋은 하루 보내세요 :)

2024-03-16 10:59 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/set/size/index.md
> +`size` 값의 설정자는 `undefined`입니다. 즉 값을 직접 바꿀 수는 없습니다.
```suggestion
`size`의 설정자는 `undefined`입니다. 즉, 이 속성을 변경할 수 없습니다.
```

> A set accessor function for `size` is `undefined`; you cannot change this property.

2024-03-16 10:59 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/set/values/index.md
> +없음
```suggestion
없음.
```

2024-03-17 04:50 UTC, wisedog commented
감사합니다. 제안주신대로 수정했습니다.

2024-03-18 08:43 UTC, hochan222 approved these changes

2024-03-18 08:43 UTC, merged