[ko] Retranslation of "Your first form" in Korean: fixed typos, unifi…
mdn/translated-content pull request #18452
Opened 2024-03-07 07:52 UTC by ono212

…ed tone, reflected latest English document

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-03-08 14:14 UTC, wisedog requested changes
기여 정말 감사합니다! 전반적으로 좋은 번역이었습니다. 다만 몇 군데만 수정 부탁드려도 될까요?

2024-03-08 14:14 UTC, wisedog commented on files/ko/learn/forms/your_first_form/index.md
> +- 두 번째 input에는 {{HTMLelement("input/email", "email")}} 값을 사용합니다. email 값은 올바른 형식의 이메일 주소만 허용하는 한 줄 텍스트 필드를 정의합니다. email 값으로 지정하면 기본 텍스트 필드에서 일종의 "지능형" 필드로 바뀌어 사용자가 입력한 데이터에 대해 몇 가지 유효성 검사를 수행합니다. 또한
`두 번째 input에는 올바른 형식의 이메일 주소만 허용하는 한 줄 텍스트 필드를 정의하는 [email] 값을 사용합니다.` 가 좀 더 자연스러워보입니다.

2024-03-08 14:14 UTC, wisedog commented on files/ko/learn/forms/your_first_form/index.md
> +  /* To make sure that all label have the same size and are properly align */
여력이 되신다면 주석까지 번역해주시면 완벽한 문서가 되지 싶습니다!

2024-03-08 14:14 UTC, wisedog commented on files/ko/learn/forms/your_first_form/index.md
> -하지만 이제 시작일 뿐이고, 더 깊게 파고들 시간이다. HTML폼은 이 문서에서 본 것 보다 더 강력한 도구이고, 이 가이드의 다른 문서가 나머지 내용을 배우는데 도움이 될 것이다.
이 부분이 빠진듯 합니다. 
```{{NextMenu("Learn/Forms/How_to_structure_a_web_form", "Learn/Forms")}}```

2024-03-09 19:06 UTC, ono212 commented on files/ko/learn/forms/your_first_form/index.md
> +- 두 번째 input에는 {{HTMLelement("input/email", "email")}} 값을 사용합니다. email 값은 올바른 형식의 이메일 주소만 허용하는 한 줄 텍스트 필드를 정의합니다. email 값으로 지정하면 기본 텍스트 필드에서 일종의 "지능형" 필드로 바뀌어 사용자가 입력한 데이터에 대해 몇 가지 유효성 검사를 수행합니다. 또한
아 그렇네요!! 그게 더 읽기에 자연스러운 것 같습니다👍🏻. 말씀해주신 부분 반영했습니다!!

2024-03-09 19:07 UTC, ono212 commented on files/ko/learn/forms/your_first_form/index.md
> +  /* To make sure that all label have the same size and are properly align */
주석 번역해서 반영해봤는데 괜찮은지 확인 부탁드립니다!

2024-03-09 19:08 UTC, ono212 commented on files/ko/learn/forms/your_first_form/index.md
> -하지만 이제 시작일 뿐이고, 더 깊게 파고들 시간이다. HTML폼은 이 문서에서 본 것 보다 더 강력한 도구이고, 이 가이드의 다른 문서가 나머지 내용을 배우는데 도움이 될 것이다.
앗 빠뜨렸네요! 알려주셔서 감사합니다! 반영했습니다!

2024-03-10 04:51 UTC, wisedog approved these changes
LGTM! 첫 기여인데도 상당히 좋은 PR 이었습니다. 감사합니다!

2024-03-10 04:51 UTC, merged