Web/HTTP/Headers/Authorization の翻訳を更新
mdn/translated-content pull request #185
Opened 2021-03-16 05:00 UTC by mfuji09

2021/02/20の英語版に基づき更新

2021-03-23 12:41 UTC, potappo requested changes
リンクの修正を指摘しましたので、修正お願いします。

2021-03-23 12:41 UTC, potappo commented on files/ja/web/http/headers/authorization/index.html
> - <dd><a href="/ja/docs/Web/HTTP/Authentication#Authentication_schemes">認証の種類</a>。一般的には <a href="/ja/docs/Web/HTTP/Authentication#Basic_authentication_scheme">"Basic"</a> です。それ以外の種類は以下に記述されています。
#authentication_schemes, #basic_authentication_scheme にしてください。MDN でのページ内 id 指定は小文字始まりでないと駄目なようです。
※http://localhost:5000/ で表示したときに、Broken Links で指摘してくれます。

2021-03-23 12:41 UTC, potappo commented on files/ja/web/http/headers/authorization/index.html
> -  <li>結果の文字列は <a href="/ja/docs/Web/API/WindowBase64/Base64_encoding_and_decoding">Base64</a> でエンコードされます (<code>YWxhZGRpbjpvcGVuc2VzYW1l</code>)。</li>
これもさきほどの Broken Links チェックから。リダイレクト先の /ja/docs/Glossary/Base64 に修正した方が良さそうです。

2021-03-23 16:03 UTC, mfuji09 commented on files/ja/web/http/headers/authorization/index.html
> - <dd><a href="/ja/docs/Web/HTTP/Authentication#Authentication_schemes">認証の種類</a>。一般的には <a href="/ja/docs/Web/HTTP/Authentication#Basic_authentication_scheme">"Basic"</a> です。それ以外の種類は以下に記述されています。
修正を見落としていました。ありがとうございます！

2021-03-23 16:03 UTC, mfuji09 commented on files/ja/web/http/headers/authorization/index.html
> -  <li>結果の文字列は <a href="/ja/docs/Web/API/WindowBase64/Base64_encoding_and_decoding">Base64</a> でエンコードされます (<code>YWxhZGRpbjpvcGVuc2VzYW1l</code>)。</li>
こちらも修正しました。ご指摘ありがとうございます。

2021-03-24 12:59 UTC, potappo approved these changes
OK です。

2021-03-24 12:59 UTC, merged