[ko] Math.max()/random() 최신 동기화
mdn/translated-content pull request #18529
Opened 2024-03-10 04:57 UTC by wisedog

MDN에서 조회 순서가 높지만 문서가 상당히 오래된 아래 문서를 최신화하였습니다.
- Math.max()
- Math.random()

2024-04-08 14:42 UTC, sunhpark42 requested changes
안녕하세요 @wisedog 님, 리뷰가 많이 늦어져서 죄송합니다.
수정사항 커멘트로 남겨두었으니 확인 부탁드립니다.
수정해주시면 바로 확인하도록 하겠습니다.
감사합니다 🙇‍♀️

2024-04-08 14:42 UTC, sunhpark42 commented on files/ko/web/javascript/reference/global_objects/math/max/index.md
> +`getMaxOfArray()`를 사용할 수 있습니다. 이 함수는 상대적으로 요소가 적은 배열에만 사용해야 합니다.
```suggestion
다음 함수는 {{jsxref("Function.prototype.apply()")}}를 사용하여 배열의 최대값을 가져옵니다.
`getMaxOfArray([1, 2, 3])`는 `Math.max(1, 2, 3)`와 동일하지만, 프로그래밍 방식으로 배열을 생성하기 위해
`getMaxOfArray()`를 사용할 수 있습니다. 이 함수는 상대적으로 요소가 적은 배열에만 사용해야 합니다.
```

source commit 내 원문이 아래와 같아서, 내용이 중복 된 것 같아 중복 내용 삭제 부탁드립니다.

```
The following function uses {{jsxref("Function.prototype.apply()")}} to get the maximum of an array. `getMaxOfArray([1, 2, 3])` is equivalent to `Math.max(1, 2, 3)`, but you can use `getMaxOfArray()` on programmatically constructed arrays. This should only be used for arrays with relatively few elements.
```

2024-04-08 14:42 UTC, sunhpark42 commented on files/ko/web/javascript/reference/global_objects/math/random/index.md
> +None.
없음.  으로 번역하는 것은 어떨까요?
```suggestion
없음
```

2024-04-08 14:42 UTC, sunhpark42 commented on files/ko/web/javascript/reference/global_objects/math/random/index.md
> +이 예제는 주어진 두 값 사이의 **정수인** 난수를 생성합니다.
_integer_ (정수) 를 강조할 필요가 없다고 생각하는데, @wisedog 님은 어떻게 생각하시나요? 정수임을 강조하는 것이 낫다면 유지하고, 강조하지 않아도 된다면 bold style 제거하는 것은 어떨지 제안드립니다.

2024-04-08 22:02 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/math/max/index.md
> +`getMaxOfArray()`를 사용할 수 있습니다. 이 함수는 상대적으로 요소가 적은 배열에만 사용해야 합니다.
제가 왜 그랬죠 ㅎㅎㅎ ㅇ.ㅇ? 감사합니다.

2024-04-08 22:04 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/math/random/index.md
> +이 예제는 주어진 두 값 사이의 **정수인** 난수를 생성합니다.
기존 한글 번역본에 bold가 적용되어 있었기에 큰 의미는 안두고 했습니다. 말씀하신대로 해도 무방할리라 생각합니다.

2024-04-11 08:19 UTC, sunhpark42 approved these changes
수정사항 확인했습니다. 감사합니다!

2024-04-11 08:20 UTC, merged