[ko] update translation of Object.prototype.toString
mdn/translated-content pull request #18543
Opened 2024-03-10 13:10 UTC by qja0707

### Description

Object.prototype.toString 의 요약 부분과 구문 부분을 최신화합니다.

### Motivation

### Additional details

### Related issues and pull requests

2024-03-10 15:29 UTC, hochan222 commented
@yechoi42 님 안녕하세요~! 

@1ilsang님 리뷰 후 같이 리뷰 부탁드립니다 🙇🏻‍♂️🙇🏻‍♂️

2024-03-11 12:44 UTC, 1ilsang requested changes
@qja0707 님

안녕하세요. 기여해주셔서 감사합니다!

최신화된 문서의 소스커밋 해시를 헤더에 추가해 주세요([예제 PR](https://github.com/mdn/translated-content/pull/18220/files#diff-3472f625edaec88a2e81c2d75b96a231f65d086381dc3b9863ab37378129d90eR5)).

[c9cb9a898105ed0fc5286cfdd552ad71ce345777](https://github.com/mdn/content/blob/c9cb9a898105ed0fc5286cfdd552ad71ce345777/files/en-us/web/javascript/reference/global_objects/object/tostring/index.md) 내용이 맞을까요?

```md
---
title: Object.prototype.toString()
slug: Web/JavaScript/Reference/Global_Objects/Object/toString
l10n:
  sourceCommit: c9cb9a898105ed0fc5286cfdd552ad71ce345777
---
```

관련 내용은 [CONTRIBUTING 문서](https://github.com/mdn/translated-content/blob/main/CONTRIBUTING.md#create-a-new-translation)에서 확인하실 수 있습니다.

2024-03-12 03:50 UTC, qja0707 commented
@1ilsang 님, 리뷰해주셔서 감사합니다. 

제가 이해하기로 해당 문서(files/en-us/web/javascript/reference/global_objects/object/tostring/index.md) 의 최신 커밋 해쉬값을 추가해달라는 말씀이신 것 같은데 맞나요? 

위 파일을 대상으로 git log 를 해보았을 때 최신 버전의 해쉬값인 6a3063ab22fdcaedc8d69b80261f09d870ea9709 으로 추가해두었습니다.

감사합니다.

2024-03-16 15:15 UTC, yechoi42 requested changes
안녕하세요 기여자님! 기여 감사합니다. 몇가지 코멘트를 남겨두었으니, 확인하시고 저를 다시 멘션하거나 제게 다시 리뷰 요청 부탁드립니다. 

만약 여유가 되신다면, url의 #뒤 부분을 한국어 문서에 존재하는 부분으로 대체해주셔도 좋을 것 같습니다. 
예) 
as-is: /ko/docs/Web/JavaScript/Data_structures#type_coercion
to-be: /ko/docs/Web/JavaScript/Data_structures#타입_강제_변환

2024-03-16 15:15 UTC, yechoi42 commented on files/ko/web/javascript/reference/global_objects/object/tostring/index.md
> +자바스크립트는 [객체를 원시 값으로 변환](/ko/docs/Web/JavaScript/Data_structures#type_coercion)하기 위해 `toString` 메서드를 호출합니다. 당신은 `toString` 메서드를 직접 부를 일이 거의 없습니다; 자바스크립트는 원시 값이 있어야 할 곳에 객체를 마주치면 자동으로 해당 메서드를 호출합니다.
```suggestion
자바스크립트는 [객체를 원시 값으로 변환](/ko/docs/Web/JavaScript/Data_structures#type_coercion)하기 위해 `toString` 메서드를 호출합니다. 당신은 `toString` 메서드를 직접 부를 일이 거의 없습니다. 자바스크립트는 원시 값이 있어야 할 곳에서 객체를 마주치면 자동으로 해당 메서드를 호출합니다.
```
안녕하세요 기여자님! [번역 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md#-%EC%8C%8D%EC%A0%90--%EC%8C%8D%EB%B0%98%EC%A0%90)에 따라 쌍반점은 온점으로 치환할 것을 안내드립니다.

2024-03-16 15:15 UTC, yechoi42 commented on files/ko/web/javascript/reference/global_objects/object/tostring/index.md
> +`Object.prototype.toString()`은 `"[object Type]"`을 반환하는데, 여기서 `Type`은 객체의 타입입니다. 만약 객체가 문자열 값인 [`Symbol.toStringTag`](/ko/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag) 특성을 가지고 있다면 그
```suggestion
`Object.prototype.toString()`은 `"[object Type]"`을 반환하는데, 여기서 `Type`은 객체의 타입입니다. 만약 객체가 문자열 값인 [`Symbol.toStringTag`](/ko/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag) 특성을 가지고 있다면 그 값이 `Type`이 됩니다. [`Map`](/ko/docs/Web/JavaScript/Reference/Global_Objects/Map) 과 [`Symbol`](/ko/docs/Web/JavaScript/Reference/Global_Objects/Symbol)을 포함한 많은 내장 객체들이 `Symbol.toStringTag`를 가지고 있습니다. ES6 이전에 생성된 몇몇 객체들은 `Symbol.toStringTag`가 없지만 특별한 태그를 가지고 있습니다. 이는 아래와 같습니다(아래에 제공된 타입 이름과 동일한 태그를 가지고 있습니다).
```
`that value will be used as the `Type`` 원문 표현에 따르면 '값'이 더 적합할 듯 합니다.
쌍점도 온점으로 치환해주시면 됩니다 :)

2024-03-16 15:15 UTC, yechoi42 commented on files/ko/web/javascript/reference/global_objects/object/tostring/index.md
> +[`arguments`](/ko/docs/Web/JavaScript/Reference/Functions/arguments) 객체는 `"[object Arguments]"`를 반환합니다. `Symbol.toStringTag`가 재정의 되지 않은 사용자-정의된 클래스들을 포함한 다른 객체들은 `"[object Object]"`를 반환할 것 입니다.
```suggestion
[`arguments`](/ko/docs/Web/JavaScript/Reference/Functions/arguments) 객체는 `"[object Arguments]"`를 반환합니다. `Symbol.toStringTag`가 재정의되지 않은 사용자 정의된 클래스들을 포함한 다른 객체들은 `"[object Object]"`를 반환할 것입니다.
```
한국어 표현에서는 -를 제외하는 것이 자연스러워 보여 제안드립니다.

2024-03-19 09:50 UTC, qja0707 commented
안녕하세요 @yechoi42 님, 리뷰 감사합니다.
`/ko/docs/Web/JavaScript/Reference/Global_Objects/Object#null-prototype_objects`의 경우 해당 문서가 업데이트되지 않아 null-prototype_objects 파트를 찾지 못해 수정하지 못하였습니다. 혹시 제가 놓친 부분을 알려주신다면 다시 반영하겠습니다.

감사합니다.

2024-03-24 13:54 UTC, yechoi42 approved these changes
확인해주셔서 감사합니다. (cc. @1ilsang 님도 한번 더 확인해주시면 감사하겠습니다!)

2024-03-24 15:40 UTC, 1ilsang approved these changes
LGTM 고생하셨습니다. 👍

2024-03-24 15:40 UTC, merged