[ko] modified filter-function invert markdown file
mdn/translated-content pull request #18555
Opened 2024-03-10 16:14 UTC by DrunkenNeoguri

### Description

ko/docs/Web/CSS/filter-function/invert/index.md 문서를 추가하여 한국어 번역을 진행했습니다.

### Motivation

개인 프로젝트를 진행하고 있는데, input의 type="date"일 때에 출력되는 calendar indicator의 색상을 변경할 필요가 있었습니다.  
stack overflow를 보던 중에 해당 css 함수를 통해 변경할 수 있다는 걸 알게 됐고, 마침 문서가 번역되어 있지 않아 이번에 참여를 시도하게 되었습니다.  

### Additional details

### Related issues and pull requests

2024-03-15 09:51 UTC, cos18 requested changes
안녕하세요, 첫 기여 감사합니다.
남겨 놓은 리뷰 읽어보시고 추가로 궁금하신 점 있으시면 언제든 멘션 후 알려주세요!

2024-03-15 09:51 UTC, cos18 commented on files/ko/web/css/filter-function/invert/index.md
> +---
```suggestion
slug: Web/CSS/filter-function/invert
l10n:
  sourceCommit: 66944f622b6b51bc9c24bebbbea242138d910600
---
```
[메타 데이타](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md#문서-갱신-표시) 태그가 없는 PR의 경우 이를 추가하도록 요청드리고 있습니다. 다음 기여시 참고 부탁드립니다 :)

2024-03-15 11:09 UTC, DrunkenNeoguri commented on files/ko/web/css/filter-function/invert/index.md
> +---
감사합니다, 향후 기여 시부터는 잊지 않고 추가하도록 하겠습니다! :D

2024-03-15 11:13 UTC, DrunkenNeoguri commented on files/ko/web/css/filter-function/invert/index.md
> +  - : {{cssxref("&lt;number&gt;")}} 또는 {{cssxref("&lt;percentage&gt;")}}를 지정한 변환할 양. `100%`는 완전하게 반전시켜주며, 값을 `0%`로 지정하면 입력값이 변경되지 않습니다. `0%` 과 `100%`의 사이의 값은 효과의 비율입니다. 보간({{Glossary("interpolation")
위처럼 추측 가능하고 번역도 완료된 문서가 있다면 링크로 추가하면 되는군요😮
감사합니다, 추후에도 MDN 쪽 문서 기여하게 된다면 참고해서 작성하겠습니다! 😄

2024-03-15 11:17 UTC, DrunkenNeoguri commented on files/ko/web/css/filter-function/invert/index.md
> +  - : {{cssxref("&lt;number&gt;")}} 또는 {{cssxref("&lt;percentage&gt;")}}를 지정한 변환할 양. `100%`는 완전하게 반전시켜주며, 값을 `0%`로 지정하면 입력값이 변경되지 않습니다. `0%` 과 `100%`의 사이의 값은 효과의 비율입니다. 보간({{Glossary("interpolation")
@cos18 바쁘신 중에도 친절하게 리뷰 남겨주셔서 감사합니다 🙇‍♂️
한 가지 궁금한 점이 있습니다, 위와 같이 국내 번역 문서가 존재할 경우 이처럼 Link를 통해서
국내 문서 쪽으로 연결하도록 하면 될까요? ㅁ?)

2024-03-16 08:01 UTC, cos18 commented on files/ko/web/css/filter-function/invert/index.md
> +  - : {{cssxref("&lt;number&gt;")}} 또는 {{cssxref("&lt;percentage&gt;")}}를 지정한 변환할 양. `100%`는 완전하게 반전시켜주며, 값을 `0%`로 지정하면 입력값이 변경되지 않습니다. `0%` 과 `100%`의 사이의 값은 효과의 비율입니다. 보간({{Glossary("interpolation")
@DrunkenNeoguri 네네 맞습니다 가능하면 최대한 원문대로 링크가 걸려있으면 걸어주시면 되고, 문서가 없어도 매크로를 그대로 놔두면 알아서 원문서로 리다이랙션 처리해줍니다.

2024-03-16 08:04 UTC, cos18 approved these changes
LGTM! 첫 기여 감사합니다 :)

2024-03-16 08:04 UTC, merged