Add Intl/PluralRules/resolvedOptions
mdn/translated-content pull request #186
Opened 2021-03-16 08:08 UTC by mfuji09

2021/02/20時点の英語版に基づき新規翻訳

2021-03-23 12:53 UTC, potappo requested changes

2021-03-23 12:53 UTC, potappo commented on files/ja/web/javascript/reference/global_objects/intl/pluralrules/resolvedoptions/index.html
> +	<dd>The type used (<code>cardinal</code> or <code>ordinal</code>).</dd>
翻訳漏れかと思います。

2021-03-23 16:09 UTC, mfuji09 commented on files/ja/web/javascript/reference/global_objects/intl/pluralrules/resolvedoptions/index.html
> +	<dd>The type used (<code>cardinal</code> or <code>ordinal</code>).</dd>
すっかり見落としていました。おっしゃる通りです。

2021-03-24 13:00 UTC, potappo approved these changes
OK です。

2021-03-24 13:01 UTC, merged