[zh-tw]: translate HTML element `map` `section` `small`
mdn/translated-content pull request #18658
Opened 2024-03-13 15:37 UTC by Dr-XYZ

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-03-17 02:03 UTC, yin1999 requested changes

2024-03-17 02:03 UTC, yin1999 commented on files/zh-tw/web/html/element/small/index.md
> +{{EmbedLiveSample("基本用法")}}
同样的问题，与标题不匹配，这里的字符串并不是你直接按英文翻译就可以，它是“你应该是覆盖了所有你需要引用的 HTML、CSS、JS 代码的标题”，在这里，它的内容就应该是第18行的标题——基本使用

2024-03-17 02:03 UTC, yin1999 commented on files/zh-tw/web/html/element/small/index.md
> +{{EmbedLiveSample("CSS 替代")}}
同

2024-03-17 02:03 UTC, yin1999 commented on files/zh-tw/web/html/element/small/index.md
> +          >段落型內容</a
这里的翻译不对

2024-03-17 02:03 UTC, yin1999 commented on files/zh-tw/web/html/element/small/index.md
> +          >段落型內容</a
同

2024-03-17 02:03 UTC, yin1999 commented on files/zh-tw/web/html/element/small/index.md
> +      <td>無；必須有開始標籤和結束標籤。</td>
见上文

2024-03-17 02:03 UTC, yin1999 commented on files/zh-tw/web/html/element/small/index.md
> +          >段落型內容</a
同

2024-03-18 14:26 UTC, yin1999 commented
还有问题没有解决，请继续修复

2024-03-19 08:45 UTC, Dr-XYZ commented on files/zh-tw/web/html/element/small/index.md
> +          >段落型內容</a
```md
      <th scope="row">Content categories</th>
      <td>
        <a href="/en-US/docs/Web/HTML/Content_categories#flow_content"
          >Flow content</a
        >,
        <a href="/en-US/docs/Web/HTML/Content_categories#phrasing_content"
          >phrasing content</a
        >
      </td>
```

翻譯成
```md
      <th scope="row">內容類別</th>
      <td>
        <a href="/zh-TW/docs/Web/HTML/Content_categories#流內容"
          >流內容</a
        >、<a href="/zh-TW/docs/Web/HTML/Content_categories#段落型內容"
          >段落型內容</a
        >
      </td>
```

沒有錯誤吧

2024-03-19 08:52 UTC, yin1999 commented on files/zh-tw/web/html/element/small/index.md
> +          >段落型內容</a
不好意思，我看错了。下次若我提供的反馈有错误，也请及时指出。这样我知道你已经看到了这条内容，然后可以根据回复来继续推进

2024-03-19 08:59 UTC, yin1999 approved these changes

2024-03-19 09:00 UTC, merged