[ko] outerHeight 번역추가
mdn/translated-content pull request #18671
Opened 2024-03-14 12:09 UTC by rosaceaee

outerHeight를 번역했습니다.
기여는 처음이라.. 어제 에러가 발생해서 다시 시도해봅니다만 어디부터 문제인지 모르겠습니다..

2024-03-14 22:47 UTC, wisedog commented on files/ko/web/api/window/outerHeight/index.md
> +
@rosaceaee  안녕하세요. 기여 감사합니다. 이 에러는 린트라고 하는 자동화된 프로그램에서 내는데요, 두 줄을 연속으로 줄바꿈하면 에러가 더 이상 발생하지 않을겁니다.

2024-03-14 22:47 UTC, wisedog commented on files/ko/web/api/window/outerHeight/index.md
> +
이 또한 마찬가지구요

2024-03-14 22:48 UTC, wisedog commented on files/ko/web/api/window/outerHeight/index.md
> +---
하시는 김에 [Meta Data 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md) 를 보고 `l10n` 항목 추가 부탁드립니다.

2024-03-16 07:46 UTC, rosaceaee commented on files/ko/web/api/window/outerHeight/index.md
> +---
안녕하세요! 확인해주셔서 감사합니다. 말씀해주신 부분 모두 수정하였습니다.
며칠째 번거롭게 해드려서 죄송해요. 
pr 후에 나온 에러 메세지를 확인해보니 error: The document's slug (Web/API/Window/outerHeight) doesn't match its disk folder name (ko/web/api/window/outerHeight) 라고 되어있어서요, 슬러그에서 문제가 발생하고 있습니다.

연관이 있을지 모르겠으나 content 폴더에서
1) .env 기입도 제대로 해두었고 
CONTENT_TRANSLATED_ROOT=../translated-content/files
EDITOR=code

2) 아래 이미지처럼 로컬에서 content와 translated-content 폴더 내 경로도 일치하는데 혹시 제가 잘못 짚고 있는 부분이 있는지 알 수 있을까요? 
<img width="100%" alt="path of both" src="https://github.com/mdn/translated-content/assets/115390541/1c1aa2dc-1717-44c5-a05a-55582688e3f1">

2024-03-16 08:21 UTC, cos18 commented on files/ko/web/api/window/outerHeight/index.md
> +---
@rosaceaee 확인 결과 경로 오타를 내신 것 같습니다. slug가 일치하는지 확인하는 것은 원본 repo (content repo)와 경로가 일치해야 하는데, 
원문 repo에서는 문서 제목과 slug와는 다르게 content repo의 파일 경로는 모두 소문자 혹은 underline (`_`)만 사용합니다. 경로 중 `outerHeight`에 대문자를 포함하셔서 생긴 오류인 것 같습니다.

2024-03-16 08:28 UTC, cos18 requested changes
첫 기여 감사드립니다 :)
놓칠수 있는 부분 추가 리뷰드리니 확인후 추가적으로 궁금하시면 태그후 코멘트 부탁드립니다.

2024-03-16 08:28 UTC, cos18 commented on files/ko/web/api/window/outerHeight/index.md
> +**`Window.outerHeight`** 는 읽기 전용 프로퍼티이며, 사이드 바와 브라우저 내의 요소 그리고 윈도우 창의 크기를 조절할 때 가장자리 경계선을 포함하여 전체 윈도우 브라우저의 높이값을 픽셀단위로 나타내는 프로퍼티입니다.
```suggestion
**`Window.outerHeight`** 는 읽기 전용 속성이며, 사이드 바와 브라우저 내의 요소 그리고 윈도우 창의 크기를 조절할 때 가장자리 경계선을 포함하여 전체 윈도우 브라우저의 높이값을 픽셀단위로 나타내는 속성입니다.
```
[ko glossary-guide](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md#공통-용어)에서 `property`를 `속성`으로 번역하길 권장드립니다.

2024-03-16 08:28 UTC, cos18 commented on files/ko/web/api/window/outerHeight/index.md
> +윈도우 브라우저의 내부 높이값, 즉 브라우저 안에서 보여지는 페이지의 높이값을 가져오려면 {{domxref("window.innerHeight")}}를 확인해주세요.
```suggestion
윈도우의 크기를 변경하려면 {{domxref("window.resizeBy()")}} 그리고 {{domxref("window.resizeTo()")}}를 확인하시오.

윈도우 브라우저의 내부 높이값, 즉 브라우저 안에서 보여지는 페이지의 높이값을 가져오려면 {{domxref("window.innerHeight")}}를 확인하시오.
```
[ko translation-guide](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md#표현)에서 격식체를 권장드리고 있습니다.

2024-03-19 08:48 UTC, rosaceaee commented on files/ko/web/api/window/outerHeight/index.md
> +---
안녕하세요! 답변 감사합니다. 말씀해주신대로 대소문자에서 문제가 발생한 것 같아요. 확인해주셔서 감사합니다!

2024-03-19 08:51 UTC, rosaceaee commented on files/ko/web/api/window/outerHeight/index.md
> +윈도우 브라우저의 내부 높이값, 즉 브라우저 안에서 보여지는 페이지의 높이값을 가져오려면 {{domxref("window.innerHeight")}}를 확인해주세요.
추가 리뷰 감사합니다! 확인 후 수정완료하였습니다.
다음 기여를 할 때 가이드에 맞게 작업하겠습니다 :)

2024-03-19 08:52 UTC, cos18 approved these changes
LGTM! 첫 기여 수고하셨습니다 :)

2024-03-19 08:53 UTC, merged