[zh-cn] add translation for highlights static property
mdn/translated-content pull request #18702
Opened 2024-03-15 07:08 UTC by ldt1997

### Description

As the title.

### Motivation

### Additional details

### Related issues and pull requests

2024-03-15 08:55 UTC, skyclouds2001 commented on files/zh-cn/web/api/css/highlights_static/index.md
> +- [CSS 自定义高亮 API：网页文本范围高亮的未来](https://css-tricks.com/css-custom-highlight-api-early-look/)
API 的名称不作翻译可能更好？

2024-03-15 08:57 UTC, skyclouds2001 commented on files/zh-cn/web/api/css/highlights_static/index.md
> +short-title: highlights
```suggestion
```

这里的 short-title 不是必须添加的，可以直接利用 en-US 的

2024-03-15 08:57 UTC, skyclouds2001 commented on files/zh-cn/web/api/css/highlights_static/index.md
> +- {{domxref("css_custom_highlight_api", "The CSS Custom Highlight API", "", "nocode")}}
```suggestion
- {{domxref("css_custom_highlight_api", "CSS Custom Highlight API", "", "nocode")}}
```

可以把链接的文本修改一下

2024-03-16 07:42 UTC, JasonLamv-t requested changes
Let's make some improvements.

2024-03-16 07:42 UTC, JasonLamv-t commented on files/zh-cn/web/api/css/highlights_static/index.md
> +{{domxref("CSS")}} 接口的静态、只读属性 **`highlights`** 提供对 `HighlightRegistry` 的访问，用于使用 {{domxref("css_custom_highlight_api", "CSS Custom Highlight API", "", "nocode")}} 为任意文本范围添加样式。
```suggestion
{{domxref("CSS")}} 接口的静态只读属性 **`highlights`** 提供访问 `HighlightRegistry` 的能力，通过使用 {{domxref("css_custom_highlight_api", "CSS 自定义高亮 API", "", "nocode")}} 为任意文本范围添加样式。
```

2024-03-16 07:42 UTC, JasonLamv-t commented on files/zh-cn/web/api/css/highlights_static/index.md
> +- [CSS Custom Highlight API：网页文本范围高亮的未来](https://css-tricks.com/css-custom-highlight-api-early-look/)
```suggestion
- {{domxref("css_custom_highlight_api", "CSS 自定义高亮 API", "", "nocode")}}
- [CSS 自定义高亮 API：网页文本范围高亮的未来](https://css-tricks.com/css-custom-highlight-api-early-look/)
```

2024-03-18 14:21 UTC, JasonLamv-t approved these changes
Thank you! @ldt1997

2024-03-18 14:22 UTC, merged