Re-translated from the English version to replace outdated content
mdn/translated-content pull request #1871
Opened 2021-08-03 13:59 UTC by YexuanXiao

2021-08-03 14:22 UTC, t7yang requested changes

2021-08-03 14:22 UTC, t7yang commented on files/zh-cn/web/api/htmlelement/click/index.html
> +<p>当在支持 <code>click()</code> 方法的元素上使用该方法 (such as an
The "such as an" is translatable.

2021-08-04 10:00 UTC, YexuanXiao reviewed
Fix an omission

2021-08-04 13:38 UTC, t7yang approved these changes

2021-08-04 13:44 UTC, merged