[ko] String.prototype.strike() 신규 추가
mdn/translated-content pull request #18749
Opened 2024-03-17 05:02 UTC by wisedog

- String.prototype.strike() 추가

2024-04-07 12:54 UTC, yechoi42 requested changes

2024-04-07 12:54 UTC, yechoi42 commented on files/ko/web/javascript/reference/global_objects/string/strike/index.md
> +> **참고:** 모든 [HTML 래퍼 메서드](/ko/docs/Web/JavaScript/Reference/Global_Objects/String#html_wrapper_methods)는 더 이상 사용되지 않으며 호환성 목적으로만 표준화되었습니다. 대신 [`document.createElement()`](/ko/docs/Web/API/Document_O
`대신 [`document.createElement()`](/ko/docs/Web/API/Document_Object_Model)와 같은 [DOM API](/ko/docs/Web/API/Document/createElement)를 사용하시기 바랍니다.`

이 부분에는 아래 문장 번역이 들어가야 하는 듯합니다.

`For the case of `strike()`, the `<strike>` element itself has been removed from the HTML specification and shouldn't be used anymore.`

한번 확인 부탁드립니다!

2024-04-07 14:24 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/string/strike/index.md
> +> **참고:** 모든 [HTML 래퍼 메서드](/ko/docs/Web/JavaScript/Reference/Global_Objects/String#html_wrapper_methods)는 더 이상 사용되지 않으며 호환성 목적으로만 표준화되었습니다. 대신 [`document.createElement()`](/ko/docs/Web/API/Document_O
어 맞군요. deprecated 된 여러 API를 동시에 다루다보니 좀 헷갈린 모양입니다. 감사합니다.

2024-04-08 12:55 UTC, yechoi42 approved these changes

2024-04-08 12:55 UTC, merged