[zh-cn] Sync with en-us 'column-count'
mdn/translated-content pull request #18775
Opened 2024-03-19 06:18 UTC by T34-active

### Description

[zh-CN column-count](https://developer.mozilla.org/zh-CN/docs/Web/CSS/column-count) Not sync with en-US markdown [en-US column-count](https://developer.mozilla.org/en-US/docs/Web/CSS/column-count)

### Motivation

Maintain consistency with the en-US document version

### Additional details

[zh-CN column-count](https://developer.mozilla.org/zh-CN/docs/Web/CSS/column-count)
[en-US column-count](https://developer.mozilla.org/en-US/docs/Web/CSS/column-count)

### Related issues and pull requests

2024-03-19 06:25 UTC, T34-active commented
英文文档的shorthand我在[术语翻译对照表](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/glossary.md)中没有找到

2024-03-19 13:03 UTC, jasonren0403 requested changes
一些修改建议

2024-03-19 13:03 UTC, jasonren0403 commented on files/zh-cn/web/css/column-count/index.md
> +
原文有个 fix：https://github.com/mdn/content/pull/32742

这里可以适当翻译并调整下排版

2024-03-19 13:03 UTC, jasonren0403 commented on files/zh-cn/web/css/column-count/index.md
> +  - : 是个严格的正整型 {{cssxref("&lt;integer&gt;")}} ，用来描述元素内容被划分的理想列数。假如 {{cssxref("column-width")}} 也被设置为非零值，此参数仅表示所允许的最大列数。
```suggestion
  - : 是个严格的正整型 {{cssxref("&lt;integer&gt;")}}，用来描述元素内容被划分的理想列数。假如 {{cssxref("column-width")}} 也被设置为非零值，此参数仅表示所允许的最大列数。
```

2024-03-19 13:03 UTC, jasonren0403 commented on files/zh-cn/web/css/column-count/index.md
> +/* Keyword value */
```suggestion
/* 关键字值 */
```

2024-03-19 13:03 UTC, jasonren0403 commented on files/zh-cn/web/css/column-count/index.md
> +/* <integer> value */
```suggestion
/* <integer> 值 */
```

2024-03-19 13:03 UTC, jasonren0403 commented on files/zh-cn/web/css/column-count/index.md
> +/* Global values */
```suggestion
/* 全局值 */
```

2024-03-20 01:47 UTC, T34-active commented on files/zh-cn/web/css/column-count/index.md
> +/* Global values */
好的 感谢你审核我的提交 我尽快处理

2024-03-20 03:06 UTC, yin1999 reviewed
关于 column 在 CSS 布局（除网格布局）中的翻译，我提议参照 [word 使用的“栏”](https://support.microsoft.com/zh-cn/office/%E6%8F%92%E5%85%A5%E5%88%86%E6%A0%8F%E7%AC%A6-fa34916a-d6ce-4c99-8646-0461a6030451)。还想征求一下大家的意见

2024-03-20 03:06 UTC, yin1999 commented on files/zh-cn/web/css/column-count/index.md
>  - [多列布局](/zh-CN/docs/Learn/CSS/CSS_layout/Multiple-column_Layout) （学习多列布局属性）
```suggestion
- [多列布局](/zh-CN/docs/Learn/CSS/CSS_layout/Multiple-column_Layout)（学习多列布局属性）
```

2024-03-20 03:06 UTC, yin1999 commented on files/zh-cn/web/css/column-count/index.md
>    - : 用来表示列的数量由其他 CSS 属性指定，例如 {{cssxref("column-width")}} 。
```suggestion
  - : 用来表示列的数量由其他 CSS 属性指定，例如 {{cssxref("column-width")}}。
```

2024-03-20 03:08 UTC, T34-active commented
这里有个问题 翻译了这一段文字没有达到满足三列的需求 我可以复制成三段显示吗
这里是复制前的效果
![image](https://github.com/mdn/translated-content/assets/71604450/44faba36-971a-4289-8042-5b6bfc5df487)
这里是复制后的效果
![image](https://github.com/mdn/translated-content/assets/71604450/109a7286-b3ef-4e3c-a785-5479cf9cf937)

2024-03-21 03:42 UTC, jasonren0403 commented on files/zh-cn/web/css/column-count/index.md
> +  这是一段使用了 CSS<code>column-count</code>
```suggestion
  这是一段使用了 CSS <code>column-count</code>
```

2024-03-24 15:25 UTC, jasonren0403 commented
> 关于 column 在 CSS 布局（除网格布局）中的翻译，我提议参照 [word 使用的“栏”](https://support.microsoft.com/zh-cn/office/%E6%8F%92%E5%85%A5%E5%88%86%E6%A0%8F%E7%AC%A6-fa34916a-d6ce-4c99-8646-0461a6030451)。还想征求一下大家的意见

简单在搜索引擎看了下，使用“多列布局”更多些，大概是习惯的问题。

但“[栏](https://zidian.gushici.net/9/680f.html)”有一个义项是“报刊或广播、电视按内容、性质划分的版面或专门的时间；亦指出版物版面的部位”，感觉“栏”更接近所讨论的排版布局方面的背景。

/cc @JasonLamv-t 可能需要下你的意见。

2024-03-25 09:26 UTC, JasonLamv-t commented
> > 关于 column 在 CSS 布局（除网格布局）中的翻译，我提议参照 [word 使用的“栏”](https://support.microsoft.com/zh-cn/office/%E6%8F%92%E5%85%A5%E5%88%86%E6%A0%8F%E7%AC%A6-fa34916a-d6ce-4c99-8646-0461a6030451)。还想征求一下大家的意见

征询了一些前端朋友的意见，他们更倾向于「列」，因为「列」这个概念相对于「行」更容易形成互补，且需要行列概念的布局上一般两者都是相对的，此外还有衍生的概念如“column spacing”等。

对于大多数场景，“column” 的直译都是“列”，因此“多列布局”可能更符合大部分人，尤其是初学者的第一直觉认知；在涉及类出版业的排版，“栏”是更专业确切的翻译，而且有现有概念如“栏目”易于推理和理解。对于“Multi-column layout”，我个人认为将“column”翻译为「栏」是可取的，其他地方应该以「列」为准，以降低初学者学习成本；

结合出于统一性的考量，和降低社区维护工作量，“column”统一翻译为「列」可能是更好的方案。

2024-03-27 06:06 UTC, yin1999 commented
可以，暂定统一翻译为“列”吧，我浏览了一部分文档，按“栏”去翻译可能有些拗口。

2024-03-28 14:24 UTC, jasonren0403 approved these changes
👍

2024-03-28 14:25 UTC, merged