[ko] Symbol.toStringTag 추가
mdn/translated-content pull request #18786
Opened 2024-03-19 23:00 UTC by wisedog

- Symbol.toStringTag 추가

2024-04-08 15:00 UTC, sunhpark42 requested changes
안녕하세요 @wisedog 님 리뷰가 늦었습니다.
default 단어 번역에 관해 comment 남겨두었습니다. 확인 부탁드립니다.
감사합니다.

2024-04-08 15:00 UTC, sunhpark42 commented on files/ko/web/javascript/reference/global_objects/symbol/tostringtag/index.md
> +### 디폴트 태그
디폴트는 기본으로 번역될 수 있는 값이라고 생각되어서, 기본 태그라고 작성하는 것은 어떨까요?

2024-04-08 22:09 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/symbol/tostringtag/index.md
> +### 디폴트 태그
좋은 의견입니다.

2024-04-11 08:18 UTC, sunhpark42 approved these changes
수정사항 확인했습니다. 감사합니다~!

2024-04-11 08:18 UTC, merged