[zh-cn] update 'column-rule-color'
mdn/translated-content pull request #18788
Opened 2024-03-20 07:49 UTC by T34-active

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-03-21 03:52 UTC, jasonren0403 requested changes
有关“column”的翻译暂时先等待确认，这里先提出其他意见

2024-03-21 03:52 UTC, jasonren0403 commented on files/zh-cn/web/css/column-rule-color/index.md
> +**`column-rule-color`** [CSS](/zh-CN/docs/Web/CSS) 属性中设置在多列布局中列与列之间绘制的线的颜色。
```suggestion
**`column-rule-color`** [CSS](/zh-CN/docs/Web/CSS) 属性设置在多列布局中列与列之间绘制的线的颜色。
```

2024-03-21 03:52 UTC, jasonren0403 commented on files/zh-cn/web/css/column-rule-color/index.md
> +  - : 用于单独设立列的规则的颜色。
```suggestion
  - : 用于单独设置列之间分割线的颜色。
```

2024-03-21 03:52 UTC, jasonren0403 commented on files/zh-cn/web/css/column-rule-color/index.md
> +### 设置列的颜色为蓝色
```suggestion
### 设置列分割线为蓝色
```

2024-03-21 03:52 UTC, jasonren0403 commented on files/zh-cn/web/css/column-rule-color/index.md
> +  这是分成三列的文本。在<code>column-rule-color</code>属性中用于更改列与列之间的线条颜色。修改列之间线条的颜色。你不觉得这很棒吗？
```suggestion
  这是分成三列的文本。用 <code>column-rule-color</code> 属性更改了列与列之间的线条颜色。你不觉得这很棒吗？
```

2024-03-21 03:52 UTC, jasonren0403 commented on files/zh-cn/web/css/column-rule-color/index.md
> +{{EmbedLiveSample("设置列的颜色为蓝色")}}
```suggestion
{{EmbedLiveSample("设置列分割线为蓝色")}}
```

2024-03-21 03:52 UTC, jasonren0403 commented on files/zh-cn/web/css/column-rule-color/index.md
> +- 其他颜色相关属性：{{cssxref("background-color")}}、{{cssxref("border-color")}}、{{cssxref("outline-color")}}、{{cssxref("text-decoration-color")}}、{{cssxref("text-emphasis-color")}}、{{cssxref("text-shadow")}}、
列表项不太对哦，再对着[原文](https://github.com/mdn/content/blob/58bd7a7f1a70dfe0c997f66912c69bdf76cc737a/files/en-us/web/css/column-rule-color/index.md?plain=1#L85)好好看看

2024-03-21 05:47 UTC, T34-active commented on files/zh-cn/web/css/column-rule-color/index.md
> +- 其他颜色相关属性：{{cssxref("background-color")}}、{{cssxref("border-color")}}、{{cssxref("outline-color")}}、{{cssxref("text-decoration-color")}}、{{cssxref("text-emphasis-color")}}、{{cssxref("text-shadow")}}、
> 列表项不太对哦，再对着[原文](https://github.com/mdn/content/blob/58bd7a7f1a70dfe0c997f66912c69bdf76cc737a/files/en-us/web/css/column-rule-color/index.md?plain=1#L85)好好看看

好的 我去修改

2024-03-28 14:35 UTC, jasonren0403 approved these changes

2024-03-28 14:36 UTC, merged