revise the translation of images in html
mdn/translated-content pull request #18812
Opened 2024-03-21 03:52 UTC by hanyujie2002

Relates to #18313

2024-03-21 03:57 UTC, hanyujie2002 commented on files/zh-cn/learn/html/multimedia_and_embedding/images_in_html/index.md
> +  按 ESC 退出编辑区域（按 Tab 可插入制表符）.
```suggestion
  按 ESC 退出编辑区域（按 Tab 可插入制表符）
```

2024-03-21 15:24 UTC, jasonren0403 commented on files/zh-cn/learn/html/multimedia_and_embedding/images_in_html/index.md
> +要想在网页上放置简单的图像，我们需要使用 {{htmlelement("img")}} 元素。这个元素是 {{Glossary("void element, 空元素")}}（即无法包含任何子内容和结束标签），它需要两个属性才能起作用：`src` 和 `alt`。`src` 属性包含一个 URL，该 URL 指向要嵌入页面的图像。`src` 属性可以是相对 URL 或绝对 URL，这与 {{htm
```suggestion
要想在网页上放置简单的图像，我们需要使用 {{htmlelement("img")}} 元素。这个元素是{{Glossary("void element", "空元素")}}（即无法包含任何子内容和结束标签），它需要两个属性才能起作用：`src` 和 `alt`。`src` 属性包含一个 URL，该 URL 指向要嵌入页面的图像。`src` 属性可以是相对 URL 或绝对 URL，这与 {{htmlelement("a")}} 元素的 `href` 属性类似。如果没有 `src` 属性，`img` 元素就没有图像可加载。
```

2024-03-26 03:17 UTC, jasonren0403 requested changes
一些修改建议

2024-03-26 03:17 UTC, jasonren0403 commented on files/zh-cn/learn/html/multimedia_and_embedding/images_in_html/index.md
> +如果你遇到了错误，可以按 _reset_ 按钮来重置。如果你遇到了困难无法完成，按下 _Show solution_ 按钮来看一下答案。
```suggestion
如果你遇到了错误，可以按*重置*按钮来重置。如果你遇到了困难无法完成，按下*显示答案*按钮来看一下答案。
```

2024-03-26 03:17 UTC, jasonren0403 commented on files/zh-cn/learn/html/multimedia_and_embedding/images_in_html/index.md
> +2. 将 `title` 属性的文本复制出来，移除 `title` 元素，然后把文字放入 {{htmlelement("figcaption")}} 元素中，这个元素在 {{htmlelement("img")}} 的下面。
```suggestion
2. 将 `title` 属性的文本复制出来，移除 `title` 属性，然后把文字放入 {{htmlelement("figcaption")}} 元素中，这个元素在 {{htmlelement("img")}} 的下面。
```

2024-03-26 03:17 UTC, jasonren0403 commented on files/zh-cn/learn/html/multimedia_and_embedding/images_in_html/index.md
> +  // 而不保存解决方案，以防止解决方案覆盖用户代码
```suggestion
  // 而不保存答案，以防止答案覆盖用户代码
```

2024-03-26 03:17 UTC, jasonren0403 commented on files/zh-cn/learn/html/multimedia_and_embedding/images_in_html/index.md
> +你也可以使用 CSS 把图片嵌入网站中（JavaScript 也行，不过那是另外一个故事了）。CSS 属性 {{cssxref("background-image")}} 和其他的 `background-*` 属性是用来控制背景图片的。比如，要想为页面中的每个段落设置一个背景图片，你可以这样做：
```suggestion
你也可以使用 CSS 把图片嵌入网站中（JavaScript 也行，不过那是另外一回事了）。CSS 属性 {{cssxref("background-image")}} 和其他的 `background-*` 属性是用来控制背景图片的。比如，要想为页面中的每个段落设置一个背景图片，你可以这样做：
```

2024-03-26 03:17 UTC, jasonren0403 commented on files/zh-cn/learn/html/multimedia_and_embedding/images_in_html/index.md
>  总而言之，如果图像对你的内容里有意义，则应使用 HTML 图像。如果图像纯粹是装饰，则应使用 CSS 背景图片。
```suggestion
总而言之，如果图像对你的内容有意义，则应使用 HTML 图像。如果图像纯粹是装饰，则应使用 CSS 背景图片。
```

2024-03-26 03:17 UTC, jasonren0403 commented on files/zh-cn/learn/html/multimedia_and_embedding/images_in_html/index.md
> +> **备注：** 你可以在 [CSS](/zh-CN/docs/Learn/CSS) 模块里学到更多关于 [CSS 背景图片](/zh-CN/docs/Learn/CSS/Styling_boxes/背景)的知识。
```suggestion
> **备注：** 你可以在 [CSS](/zh-CN/docs/Learn/CSS) 模块里学到更多关于 [CSS 背景图片](/zh-CN/docs/Learn/CSS/Building_blocks/Backgrounds_and_borders)的知识。
```

2024-03-26 03:17 UTC, jasonren0403 commented on files/zh-cn/learn/html/multimedia_and_embedding/images_in_html/index.md
> +## 网页上的其他图像
```suggestion
## 网页上的其他图形
```

2024-03-26 03:17 UTC, jasonren0403 commented on files/zh-cn/learn/html/multimedia_and_embedding/images_in_html/index.md
> +  - : 与 `<img>` 类似，你可以使用 HTML 将{{htmlelement("video")}} 和 {{htmlelement("audio")}} 嵌入到网页中，并控制其播放。
```suggestion
  - : 与 `<img>` 类似，你可以使用 HTML 将 {{htmlelement("video")}} 和 {{htmlelement("audio")}} 嵌入到网页中，并控制其播放。
```

2024-03-26 03:17 UTC, jasonren0403 commented on files/zh-cn/learn/html/multimedia_and_embedding/images_in_html/index.md
> +你已经阅读完本文，但你能记住重要的信息吗？在继续之前，你可以进行一些进一步的测试，以验证你是否掌握了这些信息。请参阅[测试你的技能：HTML 图像](/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML/Test_your_skills:_HTML_images)。
https://github.com/mdn/translated-content/blob/main/docs/zh-cn/glossary.md#标题表格

```suggestion
## 技能测试！

你已经阅读完本文，但你能记住重要的信息吗？在继续之前，你可以进行一些进一步的测试，以验证你是否掌握了这些信息。请参阅[技能测试：HTML 图像](/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML/Test_your_skills:_HTML_images)。
```

2024-03-28 14:21 UTC, jasonren0403 approved these changes
👍 Thank you

2024-03-28 14:21 UTC, merged