[zh-CN]: update the translation of wakeLock introduce
mdn/translated-content pull request #18833
Opened 2024-03-22 08:38 UTC by T34-active

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-03-22 11:14 UTC, jasonren0403 commented on files/zh-cn/web/api/wakelock/index.md
> +**`WakeLock`** [屏幕唤醒锁 API](/zh-CN/docs/Web/API/Screen_Wake_Lock_API) 接口可用于请求阻止设备屏幕在应用程序需要保持运行时变暗或锁定。
```suggestion
[屏幕唤醒锁 API](/zh-CN/docs/Web/API/Screen_Wake_Lock_API) 的 **`WakeLock`** 接口可用于请求锁，该锁阻止设备屏幕在应用程序需要保持运行时变暗或锁定。
```

2024-03-22 11:20 UTC, jasonren0403 requested changes
修改了一些语句通顺问题

2024-03-22 11:20 UTC, jasonren0403 commented on files/zh-cn/web/api/wakelock/index.md
> +此接口以及系统唤醒锁通过 {{domxref("Navigator.wakeLock")}} 属性。
```suggestion
此接口以及系统唤醒锁通过 {{domxref("Navigator.wakeLock")}} 属性暴露。
```

2024-03-22 11:20 UTC, jasonren0403 commented on files/zh-cn/web/api/wakelock/index.md
> +  - : 返回一个 {{jsxref("Promise")}} 对象，该对象在屏幕唤醒锁被授予时会实现一个 {{domxref("WakeLockSentinel")}} 对象。
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/Promise

```suggestion
  - : 返回一个 {{jsxref("Promise")}} 对象，该对象在屏幕唤醒锁被授予时会兑现为一个 {{domxref("WakeLockSentinel")}} 对象。
```

2024-03-22 11:20 UTC, jasonren0403 commented on files/zh-cn/web/api/wakelock/index.md
> +以下代码使用了 `awaits` 来请求 {{domxref("WakeLockSentinel")}} 对象，如果请求成功则继续执行。
```suggestion
以下代码使用了 `await` 来请求 {{domxref("WakeLockSentinel")}} 对象，如果请求成功则继续执行。
```

2024-03-22 11:20 UTC, jasonren0403 commented on files/zh-cn/web/api/wakelock/index.md
> +{{domxref("WakeLock.request", "WakeLock.request()")}} 方法被包裹在 `try...catch` 语句中，[导致 promise 被拒绝的情况](/zh-CN/docs/Web/API/WakeLock/request#exceptions) 例如由于设备电量低。
```suggestion
{{domxref("WakeLock.request", "WakeLock.request()")}} 方法被包裹在 `try...catch` 语句中，以捕捉[导致 promise 被拒绝的情况](/zh-CN/docs/Web/API/WakeLock/request#异常)，例如设备电量低。
```

2024-03-22 11:20 UTC, jasonren0403 commented on files/zh-cn/web/api/wakelock/index.md
> +  // 唤醒锁请求失败 - 通常是由于系统原因，例如设备电量不足
```suggestion
  // 唤醒锁请求失败——通常是系统原因，例如设备电量不足
```

2024-03-22 17:28 UTC, skyclouds2001 commented on files/zh-cn/web/api/wakelock/index.md
> +请注意，设备可能会在授予屏幕唤醒锁后撤销它。返回的 {{domxref("WakeLockSentinel")}} 可用于检查锁的状态，和/或手动取消持有的屏幕唤醒锁。
```suggestion
请注意，设备可能会在授予屏幕唤醒锁后撤销它。返回的 {{domxref("WakeLockSentinel")}} 可用于检查锁的状态，以及手动取消持有的屏幕唤醒锁。
```

这样可能更好？

2024-03-24 15:12 UTC, jasonren0403 commented on files/zh-cn/web/api/wakelock/index.md
> +请注意，设备可能会在授予屏幕唤醒锁后撤销它。返回的 {{domxref("WakeLockSentinel")}} 可用于检查锁的状态，和/或手动取消持有的屏幕唤醒锁。
没问题 👍

2024-03-24 15:13 UTC, jasonren0403 approved these changes
👍 感谢贡献，下次在修改完毕后可以点下这个按钮，这样团队能方便地收到通知，合并会更快些 🎉 
![image](https://github.com/mdn/translated-content/assets/40999116/f84e6773-b5b1-4b61-824d-3fee5c824e25)

2024-03-24 15:14 UTC, merged

2024-03-25 01:29 UTC, T34-active commented
> 👍 感谢贡献，下次在修改完毕后可以点下这个按钮，这样团队能方便地收到通知，合并会更快些 🎉 ![image](https://private-user-images.githubusercontent.com/40999116/316318809-f84e6773-b5b1-4b61-824d-3fee5c824e25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMzA0NTksIm5iZiI6MTcxMTMzMDE1OSwicGF0aCI6Ii80MDk5OTExNi8zMTYzMTg4MDktZjg0ZTY3NzMtYjViMS00YjYxLTgyNGQtM2ZlZTVjODI0ZTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDAxMjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4YjQ3YmYwOGMwNzRiZWNkOTc5MDQxOTRkMTA4NTBhMTEwYjE0NzEzNTY0ZTQ4NTllOTE2NTQ3MmZiMjMxNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R6wrJ5lRZV9YUzO8xseYT3L7-IMZPeMSaPHk5B9MIfQ)

好的