[ko] WeakSet.prototype.has() 신규 추가
mdn/translated-content pull request #18875
Opened 2024-03-23 00:49 UTC by wisedog

- WeakSet.prototype.has() 신규 추가

2024-03-24 15:51 UTC, 1ilsang requested changes
안녕하세요. 기여해주셔서 감사합니다.

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

2024-03-24 15:51 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/weakset/has/index.md
> +ws.has(window); // true 성공
```suggestion
ws.has(window); // true 반환
```

2024-03-24 23:22 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/weakset/has/index.md
> +ws.has(window); // true 성공
이런 실수가 ㅎㅎ 감사합니다.

2024-03-25 00:22 UTC, 1ilsang approved these changes
LGTM 고생하셨습니다!

2024-04-01 00:18 UTC, merged