feat(translate): Framework main features の翻訳
mdn/translated-content pull request #18886
Opened 2024-03-23 10:13 UTC by gurezo

@hmatrjp @potappo 

### issue
- [  Framework main features の翻訳 #724 ](https://github.com/mozilla-japan/translation/issues/724)  のPRです。

### translated-content
#### 以下のセクション毎にコミットしてあります。
- file add. 77fd59123b
- title, header translate Framework main features c7c5f498f1
- translate Domain-specific languages 02a0b5a1c0
- translate JSX d12bb3c062
- translate Handlebars 583dce3d09
- translate TypeScript 562aceea9b
- translate Writing components 52e5704daf
- translate Properties d33ceec52a
- translate State 954a55f23b
- translate Events ba18ccf067
- translate Styling components c9c5ed7c3d
- translate Handling dependencies 645085a098
- translate Components in components 6293ac81a7
- translate Dependency injection 536310b5b1
- translate Lifecycle 2828721d12
- translate Rendering elements 740fd93d42
- translate Routing 7b4e7a6eec
- translate Testing 13818c79b6
- translate Summary e82bcdfa4a
- translate link /en-US/ => /ja/ b1cd4c32b8
- title correction d1e6f4b82f

2024-03-23 10:28 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +page-type: learn-module-chapter
- remove page-type 4e261cea6c

2024-03-23 10:28 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +[Handlebars](https://handlebarsjs.com/)  テンプレート言語は Ember アプリケーションに固有のものではありませんが、 Ember アプリケーションで頻繁に利用されています。 Handlebars コードは HTML に似ていますが、他の場所からデータを取り込むオプションがあります。このデータは、アプリケーションが最終的に構築する HTML に影響を与え
- remove double space 5d457f650f

2024-03-23 10:28 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +
- remove empty row 877bb2469b

2024-03-23 10:28 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +Angular では、このプロセスを[依存関係の注入](https://angular.io/guide/dependency-injection)と呼びます。 Vue には [`provide()` および `inject()` コンポーネントメソッド](https://v2.vuejs.org/v2/api/#provide-inject)があります。 React には[ Context A
- remove space 7fa421125f

2024-03-23 10:29 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +
- remove empty row d587573ce7

2024-03-23 13:23 UTC, mfuji09 requested changes
指摘箇所の見直し・修正をお願いします。

2024-03-23 13:23 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +フレームワークのコンテキストでは、コンポーネントの **ライフサイクル** は、コンポーネントが DOM に追加されてブラウザーによってレンダリングされる時点 (_mounting_ と呼ばれることが多い)から削除される時点まで、コンポーネントが通過するフェーズの集合です。 DOM から (_unmounting_ と呼ばれることが多い)。各フレームワークはこれらのライフサイクルフェーズに異なる
以下の部分が意味がよく分からないので、原文を確認して翻訳の見直しをお願いします。
```
DOM から (_unmounting_ と呼ばれることが多い)。
```

2024-03-23 13:23 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +ライフサイクルと同様に、フレームワークはアプリケーションをレンダリングする方法に対して、異なるものの同様のアプローチを採用します。これらはすべて、ブラウザーの DOM の現在レンダリングされたバージョンを追跡し、アプリケーションのコンポーネントが再レンダリングされるときに DOM がどのように変更されるべきかについて、それぞれわずかに異なる決定を下します。これらの決定はフレームワークが行うため、
「メモリ」→「メモリー」に修正をお願いします。
（以下も同様）

2024-03-23 13:23 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +主要な JavaScript フレームワークごとに、 DOM の更新、ブラウザイベントの処理、楽しい開発者エクスペリエンスの提供に関して、異なるアプローチが採用されています。この記事では、「ビッグ 4」フレームワークの主な特徴を探り、フレームワークがどのように機能する傾向があるかを高いレベルから見ていき、それらの違いを見ていきます。
「主要な××ごとに」というのは不自然だと思います。以下のように訳したほうが良いように思います。
```
主要な JavaScript フレームワークはそれぞれ、（中略）について異なるアプローチを採用しています。
```

2024-03-23 13:23 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +DSL はブラウザで直接読み取ることはできません。最初に JavaScript または HTML に変換する必要があります。[変換は開発プロセスの追加のステップです](/ja/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Overview#transformation)しかし、フレームワークツールには通常、このステップを
「変換は開発プロセスの追加のステップです」の部分は、「開発プロセスにおいて、変換という追加のステップが必要になりますが」などと訳したほうが分かりやすいと思います。
また、「または次のように調整できます。このステップを含めてください。」は原文とは大きく意味が異なっています。「このステップを含めるように調整することができます」のように翻訳すべきだと思います。

2024-03-23 13:23 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +ここで各パラメータの後に書かれた `: number` は、TypeScript に `a` と `b` の両方が数字でなければならないことを伝えます。この関数を使用して引数として `'2'` を渡すと、 TypeScript はコンパイル中にエラーを発生させ、間違いを修正する必要があります。これらのエラーを発生させる独自の JavaScript を作成することもできますが、ソースコードが大幅に
「数字」ではなく「数値」ですね（変数が渡された場合は、数字以外になります）。

2024-03-23 13:23 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +## レンダリング要素
「要素のレンダリング」ではないでしょうか？

2024-03-23 13:23 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +**増分 DOM** は、何をレンダリングするかを決定するために DOM diff を構築するという点で仮想 DOM に似ていますが、 JavaScript メモリ内に DOM の完全なコピーを作成しないという点で異なります。変更する必要のない DOM の部分は無視されます。 Angular は、このモジュールでこれまで説明した、インクリメンタル DOM を使用する唯一のフレームワークです。
「インクリメンタル DOM」は直前で「増分 DOM」と訳していますので、統一してください。

2024-03-23 13:23 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +これは、 React テスト ライブラリの助けを借りて書かれた `CounterButton` の簡単なテストです。ボタンの存在や、ボタンが 0 、1 、 2 回クリックされた後に正しいテキストが表示されているかどうかなど、さまざまなことをテストします。
特に理由がなければ、「テスト ライブラリ」は「テストライブラリー」と空白なしで記述してください。

2024-03-23 14:05 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +主要な JavaScript フレームワークごとに、 DOM の更新、ブラウザイベントの処理、楽しい開発者エクスペリエンスの提供に関して、異なるアプローチが採用されています。この記事では、「ビッグ 4」フレームワークの主な特徴を探り、フレームワークがどのように機能する傾向があるかを高いレベルから見ていき、それらの違いを見ていきます。
- ブラウザ => ブラウザー b79093c137

2024-03-23 14:06 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +ここで各パラメータの後に書かれた `: number` は、TypeScript に `a` と `b` の両方が数字でなければならないことを伝えます。この関数を使用して引数として `'2'` を渡すと、 TypeScript はコンパイル中にエラーを発生させ、間違いを修正する必要があります。これらのエラーを発生させる独自の JavaScript を作成することもできますが、ソースコードが大幅に
- パラメータ => パラメーター 984d0e64e3

2024-03-23 14:06 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +ライフサイクルと同様に、フレームワークはアプリケーションをレンダリングする方法に対して、異なるものの同様のアプローチを採用します。これらはすべて、ブラウザーの DOM の現在レンダリングされたバージョンを追跡し、アプリケーションのコンポーネントが再レンダリングされるときに DOM がどのように変更されるべきかについて、それぞれわずかに異なる決定を下します。これらの決定はフレームワークが行うため、
- メモリ => メモリー b2728411b6

2024-03-23 14:06 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +主要な JavaScript フレームワークごとに、 DOM の更新、ブラウザイベントの処理、楽しい開発者エクスペリエンスの提供に関して、異なるアプローチが採用されています。この記事では、「ビッグ 4」フレームワークの主な特徴を探り、フレームワークがどのように機能する傾向があるかを高いレベルから見ていき、それらの違いを見ていきます。
- ごとに => それぞれ 90dc002c29

2024-03-23 14:06 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +ここで各パラメータの後に書かれた `: number` は、TypeScript に `a` と `b` の両方が数字でなければならないことを伝えます。この関数を使用して引数として `'2'` を渡すと、 TypeScript はコンパイル中にエラーを発生させ、間違いを修正する必要があります。これらのエラーを発生させる独自の JavaScript を作成することもできますが、ソースコードが大幅に
- 数字 => 数値 49ae39e7c1

2024-03-23 14:06 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +## レンダリング要素
- レンダリング要素 => 要素のレンダリング 7c2557a128

2024-03-23 14:06 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +**増分 DOM** は、何をレンダリングするかを決定するために DOM diff を構築するという点で仮想 DOM に似ていますが、 JavaScript メモリ内に DOM の完全なコピーを作成しないという点で異なります。変更する必要のない DOM の部分は無視されます。 Angular は、このモジュールでこれまで説明した、インクリメンタル DOM を使用する唯一のフレームワークです。
- インクリメンタル DOM => 増分 DOM 484bf350c1

2024-03-23 14:07 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +これは、 React テスト ライブラリの助けを借りて書かれた `CounterButton` の簡単なテストです。ボタンの存在や、ボタンが 0 、1 、 2 回クリックされた後に正しいテキストが表示されているかどうかなど、さまざまなことをテストします。
- テスト ライブラリ => テストライブラリー 0f34201fcf

2024-03-23 14:25 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +フレームワークのコンテキストでは、コンポーネントの **ライフサイクル** は、コンポーネントが DOM に追加されてブラウザーによってレンダリングされる時点 (_mounting_ と呼ばれることが多い)から削除される時点まで、コンポーネントが通過するフェーズの集合です。 DOM から (_unmounting_ と呼ばれることが多い)。各フレームワークはこれらのライフサイクルフェーズに異なる
- mouting, unmouting 翻訳修正 f1343f9c79

2024-03-23 14:25 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +DSL はブラウザで直接読み取ることはできません。最初に JavaScript または HTML に変換する必要があります。[変換は開発プロセスの追加のステップです](/ja/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Overview#transformation)しかし、フレームワークツールには通常、このステップを
- 翻訳修正 5e36cdd32a

2024-03-28 13:19 UTC, mfuji09 approved these changes
OKです。

2024-03-28 13:19 UTC, merged