[ko] Intl.RelativeTimeFormat() 생성자 신규 번역
mdn/translated-content pull request #18916
Opened 2024-03-24 04:45 UTC by wisedog

- Intl.RelativeTimeFormat() 생성자 신규 번역

2024-06-11 00:29 UTC, jho2301 requested changes

2024-06-11 00:29 UTC, jho2301 commented on files/ko/web/javascript/reference/global_objects/intl/relativetimeformat/relativetimeformat/index.md
> +      - : 숫자 형식화에 사용할 `"arab"`, `"hans"`, `"mathsans"` 등의 번호 체계입니다. 지원되는 번호 체계 유형 목록은 [`Intl.Locale.prototype.getNumberingSystems()`](/ko/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getN
번호는 ['차례를 나타내거나 식별하기 위해 붙이는 숫자.'](https://ko.dict.naver.com/#/entry/koko/06317db7338f4426a6332789bfe51087)  이기 때문에 숫자 체계가 더 자연스러워 보입니다

2024-06-11 03:36 UTC, wisedog commented
@jho2301 수정 완료했습니다. 리뷰 부탁드립니다.

2024-06-14 09:14 UTC, jho2301 approved these changes

2024-06-14 09:14 UTC, merged