[zh-CN]: update translation of debugger statement
mdn/translated-content pull request #18945
Opened 2024-03-25 07:38 UTC by T34-active

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-03-25 09:25 UTC, yin1999 requested changes

2024-03-25 09:25 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/debugger/index.md
> +**`debugger`** 语句会调用任何可用的调试功能，例如设置断点。如果没有任何调试功能可用，则此语句不会产生任何效果。
```suggestion
**`debugger`** 语句会调用任何可用的调试功能，例如设置断点。如果没有调试功能可用，则此语句不会产生任何效果。
```

2024-03-25 09:25 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/debugger/index.md
> +  // 做一些可能会出现错误的检查、步骤等。
“step through”指的是调试器的“按行/函数调用”来一步步执行代码的流程：

```suggestion
  // 做一些可能会出现错误的检查、单步调试等。
```

2024-03-25 09:25 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/debugger/index.md
> +当调试器被调用时，将在 `debugger` 执行语句处暂停，这类似于脚本元素中的断点。
原翻译并无错误：

- debugger：指 `debugger` 语句，不应翻译
- script source：脚本源代码，而非元素。

2024-03-25 09:25 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/debugger/index.md
> +!['浏览器打开了开发者工具，并显示了调试器面板。该面板展示了如何在调试器语句处暂停执行，以便仔细检查变量、范围、事件等。'](screen_shot_2014-02-07_at_9.14.35_am.png)
```suggestion
![打开浏览器及其开发者工具，并显示了调试器面板。该面板展示了如何在 debugger 语句处暂停执行，以便仔细检查变量、作用域、事件等。](screen_shot_2014-02-07_at_9.14.35_am.png)
```

2024-03-25 15:24 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/debugger/index.md
> +- [火狐浏览器 JavaScript 调试器¶](https://firefox-source-docs.mozilla.org/devtools-user/debugger/index.html) 在 Firefox 火狐浏览器源文档中
I believe the symbol `¶` is copied by mistake, could you remove it from the en-US doc?

Addition, the current translation does not comply with Chinese grammar/customs, please improve the translation.

2024-03-25 15:24 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/debugger/index.md
> +当调试器被调用时，将在 `debugger` 执行语句处暂停，这类似于脚本元素中的断点。
Please fix this

2024-03-26 02:14 UTC, JasonLamv-t reviewed
Some suggestions for your reference.

2024-03-26 02:14 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/statements/debugger/index.md
> +以下示例展示了在函数调用时插入 `debugger` 语句以调用调试器（如果存在）的代码。
```suggestion
以下示例显示了插入了 `debugger` 语句的代码，以便在调用函数时调用调试器（如果存在）。
```

2024-03-26 02:14 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/statements/debugger/index.md
> +- Firefox 源代码文档中的 [火狐开发者工具中调试](https://firefox-source-docs.mozilla.org/devtools-user/debugger/index.html)
```suggestion
- Firefox 源代码文档中的 [Firefox JavaScript 调试器¶](https://firefox-source-docs.mozilla.org/devtools-user/debugger/index.html)
```

2024-03-26 03:01 UTC, T34-active commented
> Some suggestions for your reference.

Thank you for the advice you've given me. You've been a great help.👍

2024-03-26 03:15 UTC, JasonLamv-t reviewed
Sorry for the wrong, I just noticed @yin1999 's comment and I think it was correct, or we should create a PR upstream for more accuracy.

2024-03-26 03:15 UTC, JasonLamv-t commented on files/zh-cn/web/javascript/reference/statements/debugger/index.md
> +- Firefox 源代码文档中的 [Firefox JavaScript 调试器¶](https://firefox-source-docs.mozilla.org/devtools-user/debugger/index.html)
```suggestion
- Firefox 源代码文档中的 [Firefox JavaScript 调试器](https://firefox-source-docs.mozilla.org/devtools-user/debugger/index.html)
```

2024-03-26 03:16 UTC, T34-active commented on files/zh-cn/web/javascript/reference/statements/debugger/index.md
> +- Firefox 源代码文档中的 [Firefox JavaScript 调试器¶](https://firefox-source-docs.mozilla.org/devtools-user/debugger/index.html)
...

2024-03-26 03:35 UTC, JasonLamv-t approved these changes
LGTM. Thank you! @T34-active  👍🏼

2024-03-26 05:45 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/debugger/index.md
> +- Firefox 源代码文档中的 [Firefox JavaScript 调试器](https://firefox-source-docs.mozilla.org/devtools-user/debugger/index.html)
Please fix the upstream content first: https://github.com/mdn/content/blob/f33c6e8a7204272b90d8f005f3d8c743333d7dbf/files/en-us/web/javascript/reference/statements/debugger/index.md?plain=1#L49

2024-03-26 06:26 UTC, T34-active commented on files/zh-cn/web/javascript/reference/statements/debugger/index.md
> +- Firefox 源代码文档中的 [Firefox JavaScript 调试器](https://firefox-source-docs.mozilla.org/devtools-user/debugger/index.html)
> Please fix the upstream content first: https://github.com/mdn/content/blob/f33c6e8a7204272b90d8f005f3d8c743333d7dbf/files/en-us/web/javascript/reference/statements/debugger/index.md?plain=1#L49

英文文档pull request：[#32839](https://github.com/mdn/content/pull/32839)

2024-03-26 08:34 UTC, T34-active commented on files/zh-cn/web/javascript/reference/statements/debugger/index.md
> +- Firefox 源代码文档中的 [Firefox JavaScript 调试器](https://firefox-source-docs.mozilla.org/devtools-user/debugger/index.html)
@yin1999 [#32839](https://github.com/mdn/content/pull/32839#issuecomment-2019805369)

2024-03-26 10:02 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/debugger/index.md
> +- Firefox 源代码文档中的 [Firefox JavaScript 调试器](https://firefox-source-docs.mozilla.org/devtools-user/debugger/index.html)
按我的理解，这个符号是在复制标题时复制到的，在其他引用 `firefox-source-docs.mozilla.org` 的文档中，并未出现该符号。（可参考 PR：mdn/content#28668）


https://github.com/mdn/translated-content/assets/15844309/c84b917f-9345-4438-9a30-14077e55dfa3

2024-03-26 10:21 UTC, T34-active commented on files/zh-cn/web/javascript/reference/statements/debugger/index.md
> +- Firefox 源代码文档中的 [Firefox JavaScript 调试器](https://firefox-source-docs.mozilla.org/devtools-user/debugger/index.html)
在[#32839](https://github.com/mdn/content/pull/32839#issuecomment-2019805369)评论中说，这里说是有意添加
地址：[#a71b892](https://github.com/mdn/content/commit/a71b8929628a2187794754c202ad399fe357141b#diff-0a56c572f70a745ddf0dfdbd73683a1c0da869f97bbebe3c62843b46e038a754R49)

2024-03-26 10:27 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/debugger/index.md
> +- Firefox 源代码文档中的 [Firefox JavaScript 调试器](https://firefox-source-docs.mozilla.org/devtools-user/debugger/index.html)
> 在[#32839](https://github.com/mdn/content/pull/32839#issuecomment-2019805369)评论中说，这里说是有意添加 commit：[#a71b892](https://github.com/mdn/content/commit/a71b8929628a2187794754c202ad399fe357141b#diff-0a56c572f70a745ddf0dfdbd73683a1c0da869f97bbebe3c62843b46e038a754R49)

我看到了，bsmth 并未反对你的修改，只是补充了一条说明，你可以在 content 仓库中搜索该符号，目前只有两处是有这个符号的。

2024-03-28 02:59 UTC, JasonLamv-t commented
Is there any new consensus? Should we reopen the PR upstream or merge this PR?

2024-04-01 03:17 UTC, yin1999 approved these changes
感谢，先不管上游吧

2024-04-01 03:17 UTC, merged