[ko] DataView.prototype.setInt16() 신규 번역
mdn/translated-content pull request #18971
Opened 2024-03-25 22:41 UTC by wisedog

- DataView.prototype.setInt16() 신규 번역

2024-03-31 15:48 UTC, 1ilsang requested changes
안녕하세요. 기여해주셔서 감사합니다.

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

2024-03-31 15:48 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/dataview/setint16/index.md
> +  - : {{Glossary("Endianness", "리틀 엔디언 혹은 빅 엔디언")}} 형식으로 데이터를 저장할지
원문에는 링크로 되어있는데 매크로로 바꾸어야 하는 건가요?

@hochan222 님 혹시 가이드 주실 수 있나요?

2024-03-31 22:21 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/dataview/setint16/index.md
> +  - : {{Glossary("Endianness", "리틀 엔디언 혹은 빅 엔디언")}} 형식으로 데이터를 저장할지
아닙니다. 원문대로 하는게 맞습니다.

2024-04-01 00:17 UTC, 1ilsang approved these changes
LGTM 고생하셨습니다!

2024-04-01 01:00 UTC, wisedog commented
머지를 안누르셔서 제가 대신 누릅니다 😊

2024-04-01 01:00 UTC, merged

2024-04-10 06:38 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/dataview/setint16/index.md
> +  - : {{Glossary("Endianness", "리틀 엔디언 혹은 빅 엔디언")}} 형식으로 데이터를 저장할지
@1ilsang 님, 모든 사항 원문과 동일하게 수정하면 됩니다.

참고차, 매크로 간소화 하는 추세이며, 주로 매크로 변경 및 제거하면서 링크로 대체되고 있습니다.