[ko] String.prototype.fixed() 신규 번역
mdn/translated-content pull request #19047
Opened 2024-03-28 22:26 UTC by wisedog

- String.prototype.fixed() 신규 번역

2024-04-08 15:10 UTC, sunhpark42 requested changes
안녕하세요 @wisedog 님, 
수정해주신 내용 확인 했습니다. String.prototype.big() 문서에서 수정할 부분은 없으나,
name 관련 해서 title 내용 확인 부탁드립니다.
감사합니다.

2024-04-08 15:10 UTC, sunhpark42 commented on files/ko/web/javascript/reference/global_objects/function/name/index.md
> +title: Function.prototype.name
최신 문서 기준으로
title: "Function: name"
로 확인되어 다시 확인 부탁드릴 수 있을까요?

source commit 추가해주시면 해당 문서 기준으로 확인해 보겠습니다.

2024-04-08 15:10 UTC, sunhpark42 commented on files/ko/web/javascript/reference/global_objects/function/name/index.md
> +title: Function.prototype.name
혹시 현재 수정에서 title, 서문, 값 만 우선 변경하는 것이 목적이라면 sourec commit 업데이트 없이 title 만 확인 부탁드리겠습니다.

2024-04-08 22:19 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/function/name/index.md
> +title: Function.prototype.name
그럼 괜히 바꾼것 같지만.... 일단 조금 바꾼것도 바꾼거니 일단 넣겠습니다.

2024-04-11 08:17 UTC, sunhpark42 approved these changes
수정사항 확인했습니다~! 감사합니다 :)

2024-04-11 08:17 UTC, merged