[zh-cn]: create the translation of Navigator: globalPrivacyControl property
mdn/translated-content pull request #19064
Opened 2024-03-29 08:10 UTC by T34-active

…operty

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-03-29 11:21 UTC, yin1999 requested changes

2024-03-29 11:21 UTC, yin1999 commented on files/zh-cn/web/api/navigator/globalprivacycontrol/index.md
> +**`Navigator.globalPrivacyControl`** 属性是一个只读属性，返回用户当前网站的[全球隐私控制](https://globalprivacycontrol.org/)设置。此设置指示用户是否同意网站或服务将其个人信息出售或共享给第三方。
请不要将其翻译为“xxx是一个只读属性，返回……”。语言应相对简洁，请使用统一的“xxx只读属性返回……”

2024-03-29 19:49 UTC, skyclouds2001 commented on files/zh-cn/web/api/navigator/globalprivacycontrol/index.md
> +- 维基百科上的 [请勿追踪](https://zh.wikipedia.org/wiki/请勿追踪)
```suggestion
- 维基百科上的[请勿追踪](https://zh.wikipedia.org/wiki/请勿追踪)
```

2024-03-30 02:37 UTC, yin1999 commented on files/zh-cn/web/api/navigator/globalprivacycontrol/index.md
> +**`Navigator.globalPrivacyControl`** 只读属性返回用户当前网站的[全球隐私控制](https://globalprivacycontrol.org/)设置。此设置指示用户是否同意网站或服务将其个人信息出售或共享给第三方。
```suggestion
**`Navigator.globalPrivacyControl`** 只读属性返回用户对当前网站的[全球隐私控制](https://globalprivacycontrol.org/)设置。此设置指示用户是否同意网站或服务将其个人信息出售或共享给第三方。
```

2024-03-30 02:37 UTC, yin1999 commented on files/zh-cn/web/api/navigator/globalprivacycontrol/index.md
> +如果用户明确表示*不同意*出售或共享其数据，则为 `true`，如果用户同意出售或共享数据，或者尚未表明偏好，则为 `false`。
```suggestion
如果用户明确表示*不同意*出售或共享其数据，则为 `true`；如果用户同意出售或共享数据，或者尚未表明偏好，则为 `false`。
```

2024-03-30 02:37 UTC, yin1999 commented on files/zh-cn/web/api/navigator/globalprivacycontrol/index.md
> +// 如果用户明确表示不同意共享或出售其数据，则为“true”，否则，为“false”。
```suggestion
// 如果用户明确表示不同意共享或出售其数据，则为“true”；否则为“false”。
```

2024-03-30 02:37 UTC, yin1999 commented on files/zh-cn/web/api/navigator/globalprivacycontrol/index.md
> +- [全球隐私控制技术规范](https://privacycg.github.io/gpc-spec/)
```suggestion
- [全球隐私控制规范](https://privacycg.github.io/gpc-spec/)
```

2024-03-30 02:44 UTC, yin1999 approved these changes
:+1:

2024-03-30 02:45 UTC, merged