[ko] scroll behavior 문서 번역
mdn/translated-content pull request #19073
Opened 2024-03-29 11:51 UTC by givvemee

### Description
[scroll-behavior 문서](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior)를 한국어로 번역합니다.

### Motivation

### Additional details
MDN 번역 기여는 처음입니다. 수정이 필요해 보이는 사항이나, 번역된 글에 더 좋은 표현이 있다면 코멘트 남겨 주세요. 감사합니다. 
<br />
**참고사항** `translated-content` 에는 해당 페이지가 존재하지 않았어서 `content` 페이지를 그대로 복사해 와서 한국어로 변경하였습니다. 그에 따라 기존 코드 블록이 원활하게 동작하는지도 같이 체크해 주시면 좋을 것 같습니다. 

### Related issues and pull requests

2024-03-29 11:54 UTC, givvemee commented on files/ko/web/css/scroll-behavior/index.md
> +browser-compat: css.properties.scroll-behavior
@리뷰어
이건 이렇게 빼는 것을 권하는 이유가 있나요?

2024-03-30 07:30 UTC, wisedog commented on files/ko/web/css/scroll-behavior/index.md
> +browser-compat: css.properties.scroll-behavior
@givvemee 
[메타데이터 가이드](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md)를 참고하시면 되겠습니다! 그 밖에 다른 문서도 읽어보시면 PR 시에 도움이 됩니다.

2024-03-30 10:19 UTC, givvemee commented on files/ko/web/css/scroll-behavior/index.md
> +browser-compat: css.properties.scroll-behavior
빌드 에러가 발생해서 제거는 하였습니다. 문서 공유 감사합니다.

2024-03-31 16:41 UTC, 1ilsang requested changes
@givvemee 님 안녕하세요. 기여해주셔서 감사합니다! 💯 

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

질문이나 도움이 필요하시다면 언제든 멘션 부탁드리겠습니다.

2024-03-31 16:41 UTC, 1ilsang commented on files/ko/web/css/scroll-behavior/index.md
> +## 명세
```suggestion
## 명세서
```

2024-03-31 16:41 UTC, 1ilsang commented on files/ko/web/css/scroll-behavior/index.md
> +## 형식 정의
이 내용은 [Glossary > CSS](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md#css)에 없어서요, 혹시 여유가 되신다면 Glossary에도 기여해 주시면 감사하겠습니다.

2024-03-31 16:41 UTC, 1ilsang commented on files/ko/web/css/scroll-behavior/index.md
> +/* Global values */
```suggestion
전역 값
```

코드 블록의 주석은 [번역하는 것을 가이드](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md#block-code)로 하고 있습니다.

2024-03-31 16:41 UTC, 1ilsang commented on files/ko/web/css/scroll-behavior/index.md
> +사용자에 의해 실행되는 스크롤 등 이 속성에 영향을 받지 않는 다른 스크롤의 종류가 있을 수 있습니다. 이 속성이 root 요소에 지정된다면, 이 속성은 뷰포트 전체에 적용됩니다. `body` 요소에 특정된 이 속성은 뷰포트로 전파되지 _않을_ 수 있습니다.
```suggestion
사용자에 의해 실행되는 스크롤 등 이 속성에 영향을 받지 않는 다른 스크롤의 종류가 있을 수 있습니다. 이 속성이 root 요소에 지정된다면, 이 속성은 뷰포트 전체에 적용됩니다. `body` 요소에 특정된 이 속성은 뷰포트로 전파되지 않을 수 있습니다.
```
기울임꼴을 그대로 사용하지 않습니다([관련 내용](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md#%EA%B8%B0%EC%9A%B8%EC%9E%84%EA%BC%B4)).

2024-03-31 16:41 UTC, 1ilsang commented on files/ko/web/css/scroll-behavior/index.md
> +**`스크롤 동작`** [CSS](/ko/docs/Web/CSS) 속성은 문서 탐색 또는 CSSOM 스크롤링 API에 의하여 스크롤 동작이 발생할 때 스크롤링을 포함하는 박스의 동작을 설정합니다.
```suggestion
**`scroll-behavior`** [CSS](/ko/docs/Web/CSS) 속성은 문서 탐색 또는 CSSOM 스크롤 API에 의하여 스크롤이 트리거될 때 스크롤을 포함하는 박스의 동작을 설정합니다.
```

1. scroll-behavior 속성에 대한 내용이므로 키워드 그대로 사용하는 것을 가이드 드립니다.
2. 스크롤링 -> 스크롤로 표현하는 것이 더 매끄럽게 느껴져 제안해 드립니다.
3. 트리거는 glossary에 등록되어 있습니다.

2024-03-31 16:41 UTC, 1ilsang commented on files/ko/web/css/scroll-behavior/index.md
> +  - : 스크롤링 박스 내에서 스크롤을 즉각적으로 실행합니다.
```suggestion
  - : 스크롤 박스가 즉시 스크롤 됩니다.
```

2024-04-01 14:03 UTC, givvemee commented on files/ko/web/css/scroll-behavior/index.md
> +## Syntax
영문에서 가져오면서 번역이 누락되었어요. 체크해 주셔서 감사합니다.

2024-04-01 14:04 UTC, givvemee commented on files/ko/web/css/scroll-behavior/index.md
> +## 형식 정의
조만간 올려보도록 할게요! 제안 감사합니다. Glossary 에도 관련 구문이 있군요.

2024-04-01 14:04 UTC, givvemee commented on files/ko/web/css/scroll-behavior/index.md
> +사용자에 의해 실행되는 스크롤 등 이 속성에 영향을 받지 않는 다른 스크롤의 종류가 있을 수 있습니다. 이 속성이 root 요소에 지정된다면, 이 속성은 뷰포트 전체에 적용됩니다. `body` 요소에 특정된 이 속성은 뷰포트로 전파되지 _않을_ 수 있습니다.
제거합니다.

2024-04-01 14:05 UTC, givvemee commented on files/ko/web/css/scroll-behavior/index.md
> +  - : 스크롤링 박스 내에서 스크롤을 즉각적으로 실행합니다.
@1ilsang 주신 코멘트는 모두 반영하였어요. 워딩도 스크롤링 보다는 스크롤로 단어 선택을 하는 게 낫다고 판단했습니다. 몇 개는 제가 resolve 를 해버렸는데요. 커밋 후 resolve 는 리뷰어 님이 해 주시는 건가요, 아니면 픽스 후 제가 해도 되나요?

2024-04-02 00:57 UTC, 1ilsang commented on files/ko/web/css/scroll-behavior/index.md
> +  - : 스크롤링 박스 내에서 스크롤을 즉각적으로 실행합니다.
@givvemee 님 편하신대로 하시면 됩니다.

2024-04-02 00:58 UTC, 1ilsang approved these changes
LGTM 고생하셨습니다. 👍

2024-04-02 01:00 UTC, merged