fr: remove the `{{DOMAttributeMethods}}` macros - Fixes #19044
mdn/translated-content pull request #19081
Opened 2024-03-29 21:55 UTC by quentin-rey

### Description

fix: remove `{{DOMAttributeMethods}}` macro
+ add/update _Specifications_ section
+ add/update _Compat_ section
+ add/update _See also_ section
    + listing complementary methods
+ Fixing broken links

### Motivation

Participates in resolving #19009 

### Additional details

Files updated:
- [x] files/fr/web/api/element/hasattribute/index.md
- [x] files/fr/web/api/element/setattributens/index.md
- [x] files/fr/web/api/element/setattributenode/index.md
- [x] files/fr/web/api/element/getattributenode/index.md
- [x] files/fr/web/api/element/hasattributens/index.md
- [x] files/fr/web/api/element/getattributens/index.md
- [x] files/fr/web/api/element/removeattributenode/index.md
- [x] files/fr/web/api/element/setattributenodens/index.md
- [x] files/fr/web/api/element/getattributenodens/index.md
- [x] files/fr/web/api/element/removeattributens/index.md
- [x] files/fr/web/api/element/removeattribute/index.md
- [x] files/fr/web/api/element/setattribute/index.md

### Related issues and pull requests

Fixes #19044

2024-04-11 14:56 UTC, SphinxKnight requested changes
Idéalement, il faudrait limiter la PR au retrait de la macro en question et garder les mises à jour et autres correction pour une/d'autres PR :)
On peut en dscuter :)

2024-04-12 07:49 UTC, SphinxKnight commented
Vu que adbebe0a5106e9a26300dde00776a6fc6300f2ad est le commit le plus "proche" de ça mais qu'il contient également d'autres modifications (que le retrait de la macro), je ne sais pas s'il existe une solution super-propre avec Git qui permettrait de tout avoir nickel sur deux branches.

À vue de nez, je dirai : 

1. Créer une nouvelle branche à partir de la branche courante afin de préparer la future PR (celle avec les màj complémentaires) (et la pousser sur le fork histoire d'éviter de perdre le boulot en cas de mauvaise manip en local)
2. Sur la branche courante (`remove_DOMAttributeMethods_macros`), revenir à l'état antérieur et faire "à la main" la modification pour retirer les macros. Force-pusher sur le fork remote afin que cette PR soit à jour
3. Attendre le merge (promis on va faire ça en moins de deux semaines ^ ^)
4. Rebase la branche créée en 1 sur l'état de la branche main (en étant sur la branche créée en 1, lancer un truc du style `git rebase main --strategy-option theirs` qui permet de garder la version courante du fichier (vu qu'il y aura déjà les macros de supprimées, ça devrait être bon)

2024-04-12 08:46 UTC, quentin-rey commented
J'ai du faire une mauvaise manip, j'ai fais un git push `--force-with-lease` après avoir remis à "0" la branche, avant de faire les suppressions de macros. Y a-t-il moyen de la rouvrir ?

2024-04-12 14:44 UTC, SphinxKnight commented
Si tu as toujours les commits en local dans les répertoires git oui, le mieux serait de connaître leur hash / ref pour recréer une branche dessus. En distant, je n'ai pas l'impression de voir grand chose : / 

Je n'ai jamais utilisé mais `git log --walk-reflogs` pourra peut-être te permettre de le retrouver.

2024-04-12 15:01 UTC, quentin-rey commented
Ce ne serait pas plus simple que je recrée un PR à partir de cette branche que j'ai retravaillé en local ? 🤔
J'ai l'impression que quoi qu'il en soit celui-ci est clos.

2024-04-12 15:03 UTC, SphinxKnight commented
il y a plusieurs choses : 
- les PR : je peux rouvrir celle-là ou on peut voir ça sur une autre, peu d'importance
- l'historique/les commits à retrouver si besoin pour faire ce que tu veux (auquel cas le hash te donne accès au fil de commits (permet de remonter les parents si besoin)

2024-04-14 08:10 UTC, SphinxKnight approved these changes
Merci @quentin-rey !

2024-04-14 08:10 UTC, merged