[Ko]: Fix incorrect translation in "Using_server-sent_events" doc.
mdn/translated-content pull request #19123
Opened 2024-03-31 11:15 UTC by C17AN

### Description

- 잘못 번역되어 있는 내용을 수정합니다.

### Motivation

- EventSource 문서를 기반으로 한 예제를 만드는 중, 잘못 번역된 내용이 있음을 인지했습니다.

### Additional details

### Related issues and pull requests

2024-03-31 11:27 UTC, C17AN commented
안녕하세요, @cos18 님!
바쁘신 와중에도 리뷰를 담당해주시게 되어 감사드립니다.

번역이 어색하거나 새로운 문장을 제안해주시면 빠르게 반영하도록 하겠습니다.

2024-04-18 03:46 UTC, wisedog commented
리뷰어 변경(@hochan222 )

2024-04-18 03:48 UTC, wisedog commented
@C17AN  안녕하세요. 예전부터 계속 기여를 해주셔서 감사합니다. 
그런데 딱 하나 걸리는게 있는데 커밋을 넣는다는건 적어도 해당 커밋에 맞게 한글 문서가 최신화되됨을 의미하는데, 지금 문서와 `en-US`문서가 많이 다릅니다. 방법은 2가지가 있는데요.

1. 한글 문서를 최신화한다.
2. l10n.sourceCommit 을 지운다.

답변 기다립니당. 늘 감사합니다. 🙏

2024-04-18 04:04 UTC, C17AN commented
> @C17AN 안녕하세요. 예전부터 계속 기여를 해주셔서 감사합니다. 그런데 딱 하나 걸리는게 있는데 커밋을 넣는다는건 적어도 해당 커밋에 맞게 한글 문서가 최신화되됨을 의미하는데, 지금 문서와 `en-US`문서가 많이 다릅니다. 방법은 2가지가 있는데요.
> 
> 1. 한글 문서를 최신화한다.
> 2. l10n.sourceCommit 을 지운다.
> 
> 답변 기다립니당. 늘 감사합니다. 🙏

---

안녕하세요, @wisedog 님!

제안해주신 내용 중, 1안대로 한글 문서를 최신화하는게 더 바람직한 방향인 것 같아, 전체 번역 후 다시 리뷰 요청드리도록 하겠습니다 🙂

오늘도 좋은 하루 보내세요!

2024-05-03 08:39 UTC, C17AN commented
개인 사정으로 본 이슈 F/U이 늦어지고 있어, 5월 19일까지는 완료 후 re-view 요청드리도록 하겠습니다. 🥲
빠르게 대응하지 못해 죄송하다는 말씀을 드리며, 해당 날짜까지는 업데이트할 수 있도록 하겠습니다 🙇‍♂️

2024-05-03 08:42 UTC, wisedog commented
> 개인 사정으로 본 이슈 F/U이 늦어지고 있어, 5월 19일까지는 완료 후 re-view 요청드리도록 하겠습니다. 🥲 빠르게 대응하지 못해 죄송하다는 말씀을 드리며, 해당 날짜까지는 업데이트할 수 있도록 하겠습니다 🙇‍♂️

천천히 하셔도 됩니다 : > 늘 감사합니다 👍

2024-05-19 14:22 UTC, C17AN commented
안녕하세요, @wisedog 님!
회사에서 작은 세미나를 담당하느라 번역 작업의 F/U이 늦어져 죄송합니다. 😅

다음 두 문서의 컨텐츠 최신화 및 번역을 추가해 두어, 여유가 되실 때 확인해주시면 감사드리겠습니다! 🙂

- [MDN / Server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events) / [SourceCommit](https://github.com/mdn/content/blob/e4c0939929e1b3e1fa3fd3da82b827fca3ed4c79/files/en-us/web/api/server-sent_events/index.md)
- [MDN / Using server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) / [SourceCommit](https://github.com/mdn/content/blob/c669fa7426d621482ca4c2d980c476cc5f8b62df/files/en-us/web/api/server-sent_events/using_server-sent_events/index.md)

이번 한 주도 행복한 일만 있으시길 바라겠습니다! 🙇‍♂️

2024-05-19 14:28 UTC, C17AN commented on files/ko/web/api/server-sent_events/using_server-sent_events/index.md
>  ---
[주요 수정사항]
- "-다" 로 끝나는 기존 번역체를 "-니다" 로 끝나는 경어체로 수정했습니다.
- 문서를 최신화하면서 기존에 없었던 문장들이 일부 추가되었습니다.

피드백 또는 제안해주실 내용이 있으시다면 편히 남겨주시면 감사드리겠습니다! 🙂

2024-05-20 22:55 UTC, wisedog requested changes
전반적으로 훌륭합니다. 딱 두 부분만 수정해주시면 되겠습니다. 감사합니다!

2024-05-20 22:55 UTC, wisedog commented on files/ko/web/api/server-sent_events/using_server-sent_events/index.md
> +## `EventSource` 객체 생성하기
```suggestion
## `EventSource` 인스턴스 생성하기
```
원문에는 `instance`라 되어 있어서 `객체`가 아니라  `인스턴스` 가 맞다고 생각합니다.

2024-05-20 22:55 UTC, wisedog commented on files/ko/web/api/server-sent_events/using_server-sent_events/index.md
> +이벤트를 생성하는 스크립트가 다른 오리진에 호스팅되어 있다면, URL과 옵션 딕셔너리를 모두 사용하여 새로운`EventSource` 객체를 만들어야 합니다. `example.com` 에 클라이언트 스크립트가 있는 경우를 예시로 들어 보겠습니다.
한 칸 띄기가 필요합니다. 
```suggestion
이벤트를 생성하는 스크립트가 다른 오리진에 호스팅되어 있다면, URL과 옵션 딕셔너리를 모두 사용하여 새로운 `EventSource` 객체를 만들어야 합니다. `example.com` 에 클라이언트 스크립트가 있는 경우를 예시로 들어 보겠습니다.
```

2024-05-21 12:33 UTC, C17AN commented on files/ko/web/api/server-sent_events/using_server-sent_events/index.md
> +이벤트를 생성하는 스크립트가 다른 오리진에 호스팅되어 있다면, URL과 옵션 딕셔너리를 모두 사용하여 새로운`EventSource` 객체를 만들어야 합니다. `example.com` 에 클라이언트 스크립트가 있는 경우를 예시로 들어 보겠습니다.
앗, 제가 잘 확인하지 못한 부분이 있었네요 😅
꼼꼼히 확인해주셔서 감사드립니다!

2024-05-21 12:40 UTC, C17AN commented on files/ko/web/api/server-sent_events/using_server-sent_events/index.md
> +## `EventSource` 객체 생성하기
앗 맞습니다, "인스턴스" 라는 단어 역시 한글로 번역해야 할지 고민했던 부분으로 기억하는데,
"객체" 와는 엄밀히 다른 개념이니 말씀해주신 내용이 맞는 것 같습니다 🙇‍♂️

무심코 넘어갈 수 있는 부분인데 꼼꼼히 짚어주셔서 감사합니다 👍

2024-05-21 22:28 UTC, wisedog approved these changes
LGTM!

2024-05-21 22:28 UTC, merged

2024-05-21 22:32 UTC, C17AN commented
고생 많으셨습니다!
오늘도 좋은 하루 보내세요~! 🙂