[zh-cn]: create the translation of `navigator.pdfViewerEnabled` property
mdn/translated-content pull request #19161
Opened 2024-04-02 08:29 UTC by T34-active

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-04-02 13:34 UTC, skyclouds2001 commented on files/zh-cn/web/api/navigator/pdfviewerenabled/index.md
> +> **注意：** 此方法取代了多种传统的判断浏览器是否支持内联显示 PDF 文件的方法。
```suggestion
> **备注：** 此方法取代了多种传统的判断浏览器是否支持内联显示 PDF 文件的方法。
```

`> **Note:**` 应翻译为 `> **备注：**`

2024-04-02 13:37 UTC, skyclouds2001 commented on files/zh-cn/web/api/navigator/pdfviewerenabled/index.md
> +{{domxref("Navigator")}} 接口的只读属性 **`pdfViewerEnabled`** 用于指示浏览器是否支持在导航到 PDF 文件时以内联方式显示它们。
```suggestion
{{domxref("Navigator")}} 接口的 **`pdfViewerEnabled`** 只读属性用于指示浏览器是否支持在导航到 PDF 文件时以内联方式显示它们。
```

2024-04-06 16:39 UTC, JasonLamv-t commented on files/zh-cn/web/api/navigator/pdfviewerenabled/index.md
> +如果浏览器在导航到 PDF 文件时可以使用内置查看器（或 PDF 查看器扩展程序）；则该属性值为 `true`，否则为 `false`。
```suggestion
如果浏览器在导航到 PDF 文件时可以使用内置查看器（或 PDF 查看器扩展程序），则该属性值为 `true`；否则为 `false`。
```

2024-04-06 16:40 UTC, JasonLamv-t requested changes
Some suggestions for your reference.

2024-04-06 16:40 UTC, JasonLamv-t commented on files/zh-cn/web/api/navigator/pdfviewerenabled/index.md
> +如果浏览器在导航到 PDF 文件时可以使用内置查看器（或 PDF 查看器扩展程序）；则该属性值为 `true`，否则为 `false`。
```suggestion
如果浏览器在导航到 PDF 文件时可以使用内置查看器（或 PDF 查看器扩展程序），则该属性值为 `true`；否则为 `false`。
```

2024-04-07 10:07 UTC, JasonLamv-t approved these changes
Thank you! @T34-active @skyclouds2001

2024-04-07 10:07 UTC, merged