[zh-cn]: update the translation of `navigator.oscpu` property
mdn/translated-content pull request #19160
Opened 2024-04-02 08:12 UTC by T34-active

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-04-02 14:28 UTC, jasonren0403 requested changes
一些需要修改的地方

2024-04-02 14:28 UTC, jasonren0403 commented on files/zh-cn/web/api/navigator/oscpu/index.md
> +| Linux                         | 输出结果是 `uname -sm`                        |
xx的输出结果

2024-04-02 14:28 UTC, jasonren0403 commented on files/zh-cn/web/api/navigator/oscpu/index.md
> +| OS/2                          | `OS/2 Warp x (either 3, 4 or 4.5)`            |
或许可调整为 `OS/2 Warp x`（x 为 3、4 或 4.5）

2024-04-02 14:28 UTC, jasonren0403 commented on files/zh-cn/web/api/navigator/oscpu/index.md
> +本表中，x.y 表示操作系统版本。
```suggestion
本表中，`x.y` 表示操作系统版本。
```

2024-04-02 14:28 UTC, jasonren0403 commented on files/zh-cn/web/api/navigator/oscpu/index.md
> +### 示例
```suggestion
## 示例
```

2024-04-02 14:28 UTC, jasonren0403 commented on files/zh-cn/web/api/navigator/oscpu/index.md
> +osInfo(); // 来自示例提示 "Windows NT 10.0; Win64; x64"
```suggestion
osInfo(); // 示例可能会输出“Windows NT 10.0; Win64; x64”
```

2024-04-02 14:28 UTC, jasonren0403 commented on files/zh-cn/web/api/navigator/oscpu/index.md
> +## 基础用法
与现有翻译对齐

```suggestion
## 使用说明
```

2024-04-07 06:37 UTC, jasonren0403 approved these changes
LGTM, Thank you @T34-active

2024-04-07 06:38 UTC, merged

2024-04-07 06:51 UTC, T34-active commented
Thank you @jasonren0403