[zh-cn]: create the translation of `navigator.windowControlsOverlay` property
mdn/translated-content pull request #19162
Opened 2024-04-02 09:04 UTC by T34-active

…property

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-04-02 13:24 UTC, yin1999 requested changes

2024-04-02 13:24 UTC, yin1999 commented on files/zh-cn/web/api/navigator/windowcontrolsoverlay/index.md
> +{{domxredowContrf("WinolsOverlay")}} 接口。
![image](https://github.com/mdn/translated-content/assets/15844309/c46e3303-d6f1-4f00-82b0-2ea7f7419003)

2024-04-02 13:32 UTC, skyclouds2001 commented on files/zh-cn/web/api/navigator/windowcontrolsoverlay/index.md
> +{{domxref("Navigator")}} 接口的只读属性 **`windowControlsOverlay`** 返回 {{domxref("WindowControlsOverlay")}} 接口，该接口提供有关桌面渐进式 Web 应用程序中使用[窗口控件叠加层 API](/zh-CN/docs/Web/API/Window_Controls_Overlay_API)的标题栏几何图形的
```suggestion
{{domxref("Navigator")}} 接口的只读属性 **`windowControlsOverlay`** 返回 {{domxref("WindowControlsOverlay")}} 接口，该接口提供有关桌面渐进式 Web 应用程序中使用[窗口控件叠加层 API](/zh-CN/docs/Web/API/Window_Controls_Overlay_API) 的标题栏几何图形的信息。
```

2024-04-02 13:32 UTC, skyclouds2001 commented on files/zh-cn/web/api/navigator/windowcontrolsoverlay/index.md
> +安装在桌面操作系统上的渐进式 Web 应用程序可以通过在 Web 应用程序清单成员 [`display_override`](/zh-CN/docs/Web/Manifest/display_override)中的 `window-controls-overlay` 值来选择加入窗口控件叠加层功能。
```suggestion
安装在桌面操作系统上的渐进式 Web 应用程序可以通过在 Web 应用程序清单成员 [`display_override`](/zh-CN/docs/Web/Manifest/display_override) 中的 `window-controls-overlay` 值来选择加入窗口控件叠加层功能。
```

2024-04-07 02:07 UTC, yin1999 commented on files/zh-cn/web/api/navigator/windowcontrolsoverlay/index.md
> +安装在桌面操作系统上的渐进式 Web 应用程序可以通过在 Web 应用程序清单成员 [`display_override`](/zh-CN/docs/Web/Manifest/display_override) 中的 `window-controls-overlay` 值来选择加入窗口控件叠加层功能。
```suggestion
安装在桌面操作系统上的渐进式 Web 应用程序可以通过在 Web 应用程序清单成员 [`display_override`](/zh-CN/docs/Web/Manifest/display_override) 中使用 `window-controls-overlay` 值来选择加入窗口控件叠加层特性。
```

2024-04-07 02:07 UTC, yin1999 commented on files/zh-cn/web/api/navigator/windowcontrolsoverlay/index.md
> +  // 窗口控制叠加功能不可用。
前后翻译不一致

```suggestion
  // 窗口控件叠加层特性不可用。
```

2024-04-07 02:27 UTC, yin1999 approved these changes

2024-04-07 02:27 UTC, merged

2024-04-07 02:30 UTC, T34-active commented
@yin1999 Thank you!