[ko] KeyboardEvent: KeyboardEvent() 문서 번역
mdn/translated-content pull request #19234
Opened 2024-04-05 13:18 UTC by givvemee

### Description

[https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/KeyboardEvent](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/KeyboardEvent) 문서를 한국어로 번역합니다. 

### Motivation

### Additional details

### Related issues and pull requests

2024-04-08 15:18 UTC, sunhpark42 requested changes
안녕하세요. @givvemee 님, 기여 감사합니다 :)
번역해주신 문서 확인했습니다. 수정 필요한 부분이 있어 리뷰 남겨두었습니다.
수정해주시면 빠르게 확인해보도록 하겠습니다.
감사합니다!

2024-04-08 15:18 UTC, sunhpark42 commented on files/ko/web/api/keyboardevent/keyboardevent/index.md
> +### 파라미터
가이드(https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md) 에 따라 매개 변수로 번역 부탁드립니다 
```suggestion
### 매개 변수
```

2024-04-08 15:18 UTC, sunhpark42 commented on files/ko/web/api/keyboardevent/keyboardevent/index.md
> +  - : {{domxref("UIEvent/UIEvent", "UIEvent()")}} 에 정의된 속성들과 더불어, 다음 속성들을 가질 수 있는 객체입니다:
```suggestion
  - : {{domxref("UIEvent/UIEvent", "UIEvent()")}} 에 정의된 속성들과 더불어, 다음 속성들을 가질 수 있는 객체입니다.
```
한국어 특성상 : => . 로 번역 되는 것이 자연스러울 것 같습니다. 가이드 함께 첨부드립니다~!(https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md#-%EC%8C%8D%EC%A0%90--%EC%8C%8D%EB%B0%98%EC%A0%90)

2024-04-09 02:57 UTC, givvemee commented on files/ko/web/api/keyboardevent/keyboardevent/index.md
> +  - : {{domxref("UIEvent/UIEvent", "UIEvent()")}} 에 정의된 속성들과 더불어, 다음 속성들을 가질 수 있는 객체입니다:
@sunhpark42 확인하였습니다. [0166855](https://github.com/mdn/translated-content/pull/19234/commits/016685526d634d7d0625aafa88e1119fa699f440) 에서 반영 후 재요청 드려요. 감사합니다.

2024-04-11 08:13 UTC, sunhpark42 commented
수정사항 모두 확인했습니다 감사합니다.

2024-04-11 08:13 UTC, sunhpark42 approved these changes

2024-04-11 08:13 UTC, merged