[ru] add response.ok translation
mdn/translated-content pull request #19248
Opened 2024-04-05 17:58 UTC by an4morph

### Description

Добавила перевод для страницы Response OK

2024-04-05 19:25 UTC, an4morph commented on files/ru/web/api/response/ok/index.md
> +- [HTTP](/ru/docs/Web/HTTP)
what I need to do there?

2024-04-05 21:59 UTC, leon-win requested changes

2024-04-05 21:59 UTC, leon-win commented on files/ru/web/api/response/ok/index.md
> +- [HTTP](/ru/docs/Web/HTTP)
> what I need to do there?

Я думаю, что здесь не хватает пустой строки в конце файла =)

А у тебя установлены плагины для автоматического форматирования? Для Visual Studio Code я использую:
https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint

2024-04-05 21:59 UTC, leon-win commented on files/ru/web/api/response/ok/index.md
> +- [HTTP](/ru/docs/Web/HTTP)
Ещё перед коммитом можно запускать команду `yarn fix:md`, это ещё надёжнее, фактически это та же самая проверка, которая отрабатывает и здесь.
Но она долго отрабатывает (потому что проверяет все md-файлы в репозитории), поэтому на мой взгляд удобнее пользоваться плагинами для IDE.

2024-04-05 21:59 UTC, leon-win commented on files/ru/web/api/response/ok/index.md
> +Свойство **`ok`** это доступное только для чтения свойство объекта {{domxref("Response")}}. Оно содержит в себе значение типа Boolean, указывающее был ли ответ от сервера успешным (статус в диапазоне
Предлагаю сформулирвоать более лаконично (и чуть ближе к оригиналу)):
```
Доступное только для чтения свойство **`ok`** объекта {{domxref("Response")}} содержит в себе значение логического типа, указывающее был ли ответ от сервера успешным (статус в диапазоне 200-299) или нет.
```

2024-04-05 21:59 UTC, leon-win commented on files/ru/web/api/response/ok/index.md
> +Значение типа Boolean.
В русском языке есть вполне устоявшиеся понятия `логический тип` и `логическое значение` (https://ru.wikipedia.org/wiki/%D0%9B%D0%BE%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D1%82%D0%B8%D0%BF). Я как раз недавно в своём PR тоже переводил Boolean)

Поэтому прдлагаю перевести так:
```
Логическое значение.
```

2024-04-05 21:59 UTC, leon-win commented on files/ru/web/api/response/ok/index.md
> +В нашем примере [Fetch Response example](https://github.com/mdn/dom-examples/tree/main/fetch/fetch-response) (см. [Fetch Response live](https://mdn.github.io/dom-examples/fetch/fetch-response/))
Этот блок предлагаю отредактировать таким образом:
```
В нашем примере [Fetch Response](https://github.com/mdn/dom-examples/tree/main/fetch/fetch-response) (см. [живой пример](https://mdn.github.io/dom-examples/fetch/fetch-response/)) мы создаëм новый экземпляр объекта {{domxref("Request")}} используя конструктор {{domxref("Request.Request","Request()")}}, передавая ему путь к изображению.
Затем мы отправляем запрос используя {{domxref("fetch()")}}, извлекаем из ответа объект Blob используя {{domxref("Response.blob")}}, создаëм объект URL с помощью {{domxref("URL.createObjectURL_static", "URL.createObjectURL()")}} и отображаем результат в теге {{htmlelement("img")}}.

> **Примечание:** в верхних строчках функции `fetch()` мы выводим в консоль ответ `ok`.
```

Какие тут изменения:
1) В оригинале периодически встречаются хаотичные переносы строк (то есть в середине предложения). Насколько я понимаю, это связано с историческими причинами и смысловой нагрузки не несёт, поэтому при переводе их можно убирать)
2) В английском языке запятые ставятся по другим правилам и в русском они не нужны)
3) Убрал повторение "используя"
4) Ещё пару мелочей)

2024-04-05 22:01 UTC, leon-win commented on files/ru/web/api/response/ok/index.md
> +В нашем примере [Fetch Response example](https://github.com/mdn/dom-examples/tree/main/fetch/fetch-response) (см. [Fetch Response live](https://mdn.github.io/dom-examples/fetch/fetch-response/))
Привет @an4morph!

Благодарю за желание улучшить проект MDN!

Я добавил несколько комментариев по улушению твоего PR'а :)

2024-04-06 02:58 UTC, yin1999 commented on files/ru/web/api/response/ok/index.md
> +- [HTTP](/ru/docs/Web/HTTP)
Please add the missing "EOF" line :)

```suggestion
- [HTTP](/ru/docs/Web/HTTP)

```

2024-04-06 11:07 UTC, an4morph commented on files/ru/web/api/response/ok/index.md
> +В нашем примере [Fetch Response example](https://github.com/mdn/dom-examples/tree/main/fetch/fetch-response) (см. [Fetch Response live](https://mdn.github.io/dom-examples/fetch/fetch-response/))
спасибо за комментарии, вроде все поправила)

2024-04-06 12:24 UTC, leon-win approved these changes

2024-04-06 12:25 UTC, leon-win commented on files/ru/web/api/response/ok/index.md
> +- [HTTP](/ru/docs/Web/HTTP)
> Please add the missing "EOF" line :)

Thank you, @yin1999 ! Done :ok_hand:

2024-04-06 12:34 UTC, leon-win commented
@an4morph, отлично, спасибо! :+1: 

Я добавил ещё `l10n.sourceCommit` ("front matter property") в блок мета-информации документа, это необходимо делать для того, чтобы можно было отслеживать "свежесть" перевода по отношению к оригиналу.

Информация об этом есть в https://github.com/mdn/translated-content/blob/main/CONTRIBUTING.md. По сути это хэш последнего коммита с изменениями файла, для которого делается перевод. Получить его можно, например, так: `git log <path/to/file/in/mdn-content>`

![image](https://github.com/mdn/translated-content/assets/1682136/e729b05d-39b9-43e9-b9fd-a227dad49cf6)

2024-04-06 12:37 UTC, merged