[zh-cn]: create the translation of `navigator.virtualKeyboard` property
mdn/translated-content pull request #19285
Opened 2024-04-07 07:50 UTC by T34-active

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-04-07 12:56 UTC, jasonren0403 requested changes
有些小问题

2024-04-07 12:56 UTC, jasonren0403 commented on files/zh-cn/web/api/navigator/virtualkeyboard/index.md
> +通过 {{domxref("VirtualKeyboard")}} 对象，你可以选择退出自动虚拟键盘行为、以编程方式显示或隐藏虚拟键盘，以及获取虚拟键盘的当前位置和大小。
```suggestion
一个 {{domxref("VirtualKeyboard")}} 对象。通过该对象，你可以选择退出自动虚拟键盘行为、以编程方式显示或隐藏虚拟键盘，以及获取虚拟键盘的当前位置和大小。
```

2024-04-08 08:00 UTC, jasonren0403 approved these changes
👍

2024-04-08 08:00 UTC, merged

2024-04-08 08:07 UTC, T34-active commented
@jasonren0403 Thank you!