[zh-cn]: update the translation of Undefined Glossary
mdn/translated-content pull request #19286
Opened 2024-04-07 08:04 UTC by T34-active

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-04-07 08:06 UTC, T34-active commented on files/zh-cn/glossary/undefined/index.md
> +## Example
```suggestion
## 示例
```

2024-04-07 08:18 UTC, yin1999 reviewed
请校对一遍

2024-04-07 08:43 UTC, T34-active commented on files/zh-cn/glossary/undefined/index.md
> +let x; //创建一个变量但是没有赋值
```suggestion
let x; //声明变量但不赋值
```

2024-04-07 08:43 UTC, T34-active commented on files/zh-cn/glossary/undefined/index.md
> +console.log(`x's value is ${x}`); //输出“x 的值是 undefined”
```suggestion
console.log(`x's 的值是 ${x}`); //输出“x 的值是 undefined“
```

2024-04-07 09:16 UTC, T34-active commented on files/zh-cn/glossary/undefined/index.md
> +**`undefined`** 是一个 {{Glossary("primitive", "原始值")}}，自动分配给刚刚声明的 {{glossary("variable", "变量")}}，或者没有实际 {{Glossary("Argument", "Arguments")}} 的形式参数。
```suggestion
**`undefined`** 是一个 {{Glossary("primitive", "原始值")}}，自动赋给刚刚声明的 {{glossary("variable", "变量")}}，或者给那些没有实际的 {{Glossary("Argument", "参数")}} 的形式参数。
```

2024-04-07 10:00 UTC, yin1999 reviewed
空格什么的，再看一下。对于这种短文，还是希望能够在不依靠我们纠正的情况下一遍过。不要太追求速度，欲速则不达。

2024-04-07 10:21 UTC, T34-active commented on files/zh-cn/glossary/undefined/index.md
> +- 维基百科上的[Undefined 值](https://zh.wikipedia.org/wiki/Undefined_value)
```suggestion
- 维基百科上的 [Undefined 值](https://zh.wikipedia.org/wiki/Undefined_value)
```

2024-04-07 11:11 UTC, skyclouds2001 requested changes

2024-04-07 11:11 UTC, skyclouds2001 commented on files/zh-cn/glossary/undefined/index.md
> +**`undefined`** 是一个 {{Glossary("primitive", "原始值")}}，自动赋给刚刚声明的 {{glossary("variable", "变量")}}，或者给那些没有实际的 {{Glossary("Argument", "参数")}} 的形式参数。
{{Glossary("primitive", "原始值")}}在渲染之后是中文，因此其两侧不需要保留空格；下同

![image](https://github.com/mdn/translated-content/assets/95597335/633dfba4-ad59-494a-b35e-39c118949700)

2024-04-08 02:19 UTC, T34-active commented on files/zh-cn/glossary/undefined/index.md
> +**`undefined`** 是一个 {{Glossary("primitive", "原始值")}}，自动赋给刚刚声明的 {{glossary("variable", "变量")}}，或者给那些没有实际的 {{Glossary("Argument", "参数")}} 的形式参数。
```suggestion
**`undefined`** 是一个{{Glossary("primitive", "原始值")}}，自动赋给刚刚声明的{{glossary("variable", "变量")}}，或者给那些没有实际的{{Glossary("Argument", "参数")}}的形式参数。
```

2024-04-08 05:19 UTC, yin1999 commented on files/zh-cn/glossary/undefined/index.md
> +console.log(`x's 的值是 ${x}`); //输出“x 的值是 undefined”
```suggestion
console.log(`x 的值是 ${x}`); //输出“x 的值是 undefined”
```

2024-04-08 05:19 UTC, yin1999 commented on files/zh-cn/glossary/undefined/index.md
> +- 维基百科上的 [Undefined 值](https://zh.wikipedia.org/wiki/Undefined_value)
```suggestion
- 维基百科上的 [Undefined 值](https://en.wikipedia.org/wiki/Undefined_value)
```

2024-04-08 05:20 UTC, yin1999 approved these changes
Thanks @T34-active, @skyclouds2001

2024-04-08 05:20 UTC, merged