[zh-tw]: translate HTTP Status `103`
mdn/translated-content pull request #19331
Opened 2024-04-08 15:13 UTC by an-777

2024-04-09 08:42 UTC, PassionPenguin reviewed
some minor suggestions，ptal ：）

2024-04-09 08:42 UTC, PassionPenguin commented on files/zh-tw/web/http/status/103/index.md
> +> **備註：**出於兼容性原因，[建議](https://www.rfc-editor.org/rfc/rfc8297#section-3)只在 HTTP/2 或更高版本上發送 HTTP `103 Early Hints` 回應，除非已知用戶端正確處理信息回應。
the styling may not applied correctly

```suggestion
> **備註：** 出於兼容性原因，[建議](https://www.rfc-editor.org/rfc/rfc8297#section-3)只在 HTTP/2 或更高版本上發送 HTTP `103 Early Hints` 回應，除非已知用戶端正確處理信息回應。
```

2024-04-09 08:42 UTC, PassionPenguin commented on files/zh-tw/web/http/status/103/index.md
> +早期提示回應主要用於 {{HTTPHeader("Link")}} 標頭，指示要加載的資源。它還可以包含一個 `Content-Security-Policy` 標頭，在處理早期提示時強制執行。
原文的 which 指代的是 Link header 的作用叭，译文变成了 early hints 可以指示…似乎范围变窄了

2024-04-09 08:42 UTC, PassionPenguin commented on files/zh-tw/web/http/status/103/index.md
> +- 第二次連接包括 [`crossorigin`](/zh-TW/docs/Web/HTML/Attributes/crossorigin) 屬性，將用於加載[CORS](/zh-TW/docs/Web/HTTP/CORS)保護的資源，例如字型。
shall CORS be space-around?

```suggestion
- 第二次連接包括 [`crossorigin`](/zh-TW/docs/Web/HTML/Attributes/crossorigin) 屬性，將用於加載[CORS](/zh-TW/docs/Web/HTTP/CORS) 保護的資源，例如字型。
```

2024-04-09 08:42 UTC, PassionPenguin commented on files/zh-tw/web/http/status/103/index.md
> +隨後伺服器發送最終回應。這包括指向樣式表的鏈接，該鏈接可能已經從早期提示中預加載。
不知道会不会更符合日常用语…?（代词代替）

```suggestion
隨後伺服器發送最終回應。這包括指向樣式表的鏈接，且其可能已經從早期提示中預加載。
```

2024-04-09 08:42 UTC, PassionPenguin commented on files/zh-tw/web/http/status/103/index.md
> +最終回應可能將 CSP 設置為 `none`，如下所示。樣式表已預加載，但在呈現頁面時將不會使用。
should be passive

```suggestion
最終回應可能將 CSP 設置為 `none`，如下所示。樣式表已預加載，但在呈現頁面時將不會被使用。
```

2024-04-09 09:05 UTC, PassionPenguin requested changes
plus，got a pr to the original content(see [mdn/content #33013](https://github.com/mdn/content/pull/33013)), fix some typos(inconsistent and incorrect tenses)

2024-04-09 09:05 UTC, PassionPenguin commented on files/zh-tw/web/http/status/103/index.md
> +最終回應可能將 CSP 設置為 `none`，如下所示。樣式表已預加載，但在呈現頁面時將不會使用。
Should be passive

```suggestion
最終回應可能將 CSP 設置為 `none`，如下所示。樣式表已被預加載，但在呈現頁面時將不會使用。
```

2024-04-09 09:05 UTC, PassionPenguin commented on files/zh-tw/web/http/status/103/index.md
> +早期回應將預加載限制在與請求相同的來源上。如果原始憑證匹配，則樣式表將預加載。
```suggestion
早期回應將預加載限制在與請求相同的來源上。如果原始憑證匹配，則樣式表將被預加載。
```

2024-04-09 09:05 UTC, PassionPenguin commented on files/zh-tw/web/http/status/103/index.md
> +隨後伺服器發送最終回應。這包括指向樣式表的鏈接，該鏈接可能已經從早期提示中預加載。
```suggestion
隨後伺服器發送最終回應。這包括指向樣式表的鏈接，該鏈接可能已經從早期提示中被預加載。
```

2024-04-10 13:12 UTC, yin1999 reviewed
nit:

2024-04-10 13:12 UTC, yin1999 commented on files/zh-tw/web/http/status/103/index.md
> +> 由於這個原因，大多數瀏覽器限制支持到 HTTP/2 或更高版本。請參見下面的[瀏覽器相容性](#瀏覽器相容性)。
考虑调整一下顺序，“限制在 HTTP/2 或更高版本中提供支持”

2024-04-10 13:27 UTC, yin1999 approved these changes
:+1:

2024-04-10 13:27 UTC, merged