[ko] ArrayBuffer.prototype.transferToFixedLength() 신규 번역
mdn/translated-content pull request #19338
Opened 2024-04-08 22:30 UTC by wisedog

- ArrayBuffer.prototype.transferToFixedLength() 신규 번역

ArrayBuffer 100% 입니다.

2024-04-28 07:25 UTC, sunhpark42 requested changes
안녕하세요.
리뷰가 늦어져서 죄송합니다.🙇‍♀️

제안사항 및 번역되지 않은 부분이 있어 수정요청드립니다.
수정 후 바로 확인해볼 수 있도록 하겠습니다.
감사합니다.

2024-04-28 07:25 UTC, sunhpark42 commented on files/ko/web/javascript/reference/global_objects/arraybuffer/transfertofixedlength/index.md
> +    - `newByteLength`가 이 `ArrayBuffer`의 `byteLength`보다 작으면 해당 버퍼에 담지못해 "넘치는" 바이트는 삭제됩니다.
한국어 특성상 "넘치는" 강조가 꼭 필요하지 않다면 큰 따옴표는 삭제되어도 될 것 같습니다.

2024-04-28 07:25 UTC, sunhpark42 commented on files/ko/web/javascript/reference/global_objects/arraybuffer/transfertofixedlength/index.md
> +Using `transferToFixedLength`, `newByteLength` can be larger than the `maxByteLength` of the original `ArrayBuffer`.
이 부분도 번역이 필요할 것 같습니다~

2024-05-02 23:00 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/arraybuffer/transfertofixedlength/index.md
> +Using `transferToFixedLength`, `newByteLength` can be larger than the `maxByteLength` of the original `ArrayBuffer`.
어이쿠...

2024-05-18 00:41 UTC, sunhpark42 approved these changes
안녕하세요 @wisedog 님, 수정사항 확인이 늦어져서 죄송합니다. 🥲
수정사항 확인했습니다. 머지하도록 하겠습니다. 감사합니다~!

2024-05-18 00:41 UTC, merged