[ko] String.prototype.replace() 신규 번역
mdn/translated-content pull request #19339
Opened 2024-04-08 22:32 UTC by wisedog

- String.prototype.replace() 신규 번역

아직 번역할 순번이 아니지만, replace 문서가 en-US 조회수는 높은데 한글 문서가 없어서 앞당겨 번역했습니다.
다만 RegEx 의 Disjunction 이걸 번역을 못했는데, 좋은 의견 있으면 부탁드리겠습니다.

2024-04-14 19:27 UTC, 1ilsang requested changes
@wisedog 님 안녕하세요. 기여해주셔서 감사합니다! 💯

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

질문이나 도움이 필요하시다면 언제든 멘션 부탁드리겠습니다.

2024-04-14 19:27 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/string/replace/index.md
> +전역 문자열 대체는 정규 표현식로만 가능합니다. 다음 예제는 정규식이 [전역 그리고 대소문자 무시 플래그](/ko/docs/Web/JavaScript/Guide/Regular_expressions#advanced_searching_with_flags)이 포함되어 있어서 `replace()`가 문자열에서 `'apple'`이 나타날 때마다 `'orange'`
```suggestion
전역 문자열 대체는 정규 표현식으로만 가능합니다. 다음 예제는 정규 표현식이 [전역 그리고 대소문자 무시 플래그](/ko/docs/Web/JavaScript/Guide/Regular_expressions#advanced_searching_with_flags)가 포함되어 있어서 `replace()`가 문자열에서 `'apple'`이 나타날 때마다 `'orange'`로 문자열을 바꾸도록 허용합니다.
```

2024-04-14 19:27 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/string/replace/index.md
> +다음 스크립트는 문자열의 단어의 순서를 바꿉니다. 대체 문자열의 경우, 스크립트는 [그룹 캡쳐](/ko/docs/Web/JavaScript/Guide/Regular_expressions/Groups_and_backreferences)과 `$1` 및 `$2` 대체 패턴을 사용합니다.
```suggestion
다음 스크립트는 문자열의 단어의 순서를 바꿉니다. 대체 문자열의 경우, 스크립트는 [그룹 캡처](/ko/docs/Web/JavaScript/Guide/Regular_expressions/Groups_and_backreferences)와 `$1` 및 `$2` 대체 패턴을 사용합니다.
```

2024-04-14 19:27 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/string/replace/index.md
> +정규식 `test`는 `F`로 끝나는 숫자가 있는지 확인합니다. 화씨 온도의 숫자는 두 번째 매개 변수인 `p1`을 통해 함수에 접근할 수 있습니다. 이 함수는 `f2c()` 함수에 문자열로 전달된 화씨 온도 숫자에 따라 섭씨 숫자를 설정합니다. 그런 다음 `f2c()`는 섭씨 숫자를 반환합니다. 이 함수는 Perl의 `s///e` 플래그를 근사화합니다.
```suggestion
정규 표현식 `test`는 `F`로 끝나는 숫자가 있는지 확인합니다. 화씨 온도의 숫자는 두 번째 매개 변수인 `p1`을 통해 함수에 접근할 수 있습니다. 이 함수는 `f2c()` 함수에 문자열로 전달된 화씨 온도 숫자에 따라 섭씨 숫자를 설정합니다. 그런 다음 `f2c()`는 섭씨 숫자를 반환합니다. 이 함수는 Perl의 `s///e` 플래그에 가깝습니다.
```

2024-04-14 19:27 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/string/replace/index.md
> +- [Polyfill of `String.prototype.replace` in `core-js` with fixes and implementation of modern behavior like `Symbol.replace` support](https://github.com/zloirock/core-js#ecmascript-string-and-regexp
```suggestion
- [`Symbol.replace` 지원과 같은 최신 동작의 수정 및 구현한 `core-js`의 `String.prototype.replace` 폴리필](https://github.com/zloirock/core-js#ecmascript-string-and-regexp)
```

2024-04-14 22:50 UTC, wisedog commented
매우 꼼꼼한 리뷰 다시 감사합니다. 내용을 수정해서 다시 올렸으니 리뷰 부탁드리겠습니다.

2024-04-15 04:20 UTC, 1ilsang commented
@wisedog 님 

resolved된 커멘트 외에도 12개의 커멘트가 남아있습니다. 혹시 확인해 주셨을까요?

2024-04-15 04:41 UTC, wisedog commented
> @wisedog 님
> 
> resolved된 커멘트 외에도 12개의 커멘트가 남아있습니다. 혹시 확인해 주셨을까요?

앗 Load More....

2024-04-15 04:45 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/string/replace/index.md
> +`$n` 및 `$<Name>`은 `pattern` 인수가 {{jsxref("RegExp")}} 객체인 경우에만 사용할 수 있습니다. `pattern`이 문자열이거나 해당 캡쳐 그룹이 정규식에 없는 경우 패턴은 리터럴로 대체됩니다. 그룹이 존재하지만 일치하지 않는 경우(Disjunction의 일부이기 때문에) 빈 문자열로 대체됩니다.
으흠!! 가장 의미가 와닿는 말 같습니다. 정말 감사합니다!

2024-04-15 04:47 UTC, wisedog commented
본문의 regex 는 정규식, regular expression 을 정규 표현식으로 하긴 했었는데 생각해보니 초심자에게는 혼동의 여지가 있을것 같군요 ㅎㅎ

2024-04-15 11:05 UTC, 1ilsang approved these changes
LGTM 고생하셨습니다

2024-04-15 11:05 UTC, merged