2024/04/11 時点の英語版に同期
mdn/translated-content pull request #19404
Opened 2024-04-11 06:22 UTC by hiroya-uga

### Description

### Motivation

### Additional details

### Related issues and pull requests

- Relates to https://github.com/mdn/content/pull/33032
- Fixes #19369

2024-04-15 14:42 UTC, mfuji09 requested changes
コメントをしましたので、対応をお願いします。

2024-04-15 14:42 UTC, mfuji09 commented on files/ja/web/javascript/reference/global_objects/string/length/index.md
> +書記素単位でカウントしたい場合は、[`Intl.Segmenter`](/ja/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter) を使用してください。まず、分割したい文字列を [`segment()`](/ja/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segment
日本語と英数字の間には空白を入れてください。
`Segments` の周囲などです。他の部分も同様にお願いします。

2024-04-15 14:42 UTC, mfuji09 commented on files/ja/web/javascript/reference/global_objects/string/length/index.md
> +  // ここで使用されているSegmentsオブジェクトのイテレータは、文字を書記素で反復処理します。
iterator は or で終わる単語なので、「イテレーター」と長音表記にしてください。

2024-04-16 15:50 UTC, hiroya-uga commented on files/ja/web/javascript/reference/global_objects/string/length/index.md
> +  // ここで使用されているSegmentsオブジェクトのイテレータは、文字を書記素で反復処理します。
@mfuji09 長音記号を追加しました！

2024-04-16 23:23 UTC, mfuji09 approved these changes
ありがとうございました。OKです。

2024-04-17 13:19 UTC, merged