[ko] input file property 신규 번역
mdn/translated-content pull request #19554
Opened 2024-04-16 18:13 UTC by hazzzi

### Description
[HTMLInputElement: files property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/files) 신규 번역입니다.

### Motivation

### Additional details

### Related issues and pull requests

2024-04-20 14:35 UTC, 1ilsang requested changes
@hazzzi 님 안녕하세요. 기여해주셔서 감사합니다! 💯

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

질문이나 도움이 필요하시다면 언제든 멘션 부탁드리겠습니다.

2024-04-20 14:35 UTC, 1ilsang commented on files/ko/web/api/htmlinputelement/files/index.md
> +slug: Web/API/HTMLInputElement/files
```suggestion
---
title: "HTMLInputElement: files property"
short-title: files
slug: Web/API/HTMLInputElement/files
l10n:
  sourceCommit: acfe8c9f1f4145f77653a2bc64a9744b001358dc
```

최신화된 문서의 소스커밋 해시를 헤더에 추가해 주세요([예제 PR](https://github.com/mdn/translated-content/pull/18220/files#diff-3472f625edaec88a2e81c2d75b96a231f65d086381dc3b9863ab37378129d90eR5)).

관련 내용은 [Meta Data 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md)에서 확인하실 수 있습니다.

2024-04-20 14:35 UTC, 1ilsang commented on files/ko/web/api/htmlinputelement/files/index.md
> +선택한 파일이 있는 경우 해당 파일을 나열하는 {{domxref("FileList")}} 객체입니다. **`HTMLInputElement`** 가 `type="file"`이 아닌 경우는 `null`입니다.
```suggestion
선택한 파일이 있는 경우 해당 파일을 나열하는 {{domxref("FileList")}} 객체입니다. **`HTMLInputElement`**가 `type="file"`이 아닌 경우는 `null`입니다.
```

2024-04-20 14:35 UTC, 1ilsang commented on files/ko/web/api/htmlinputelement/files/index.md
> +**`HTMLInputElement.files`** 는 파일이 선택되지 않은 경우에도 {{domxref("FileList")}}의 인스턴스를 반환합니다. 따라서 파일 선택 여부를 확인하지 않아도 {{JSxref("Statements/for...of", "for...of")}} 를 사용하여 이를 안전하게 반복할 수 있습니다.
```suggestion
**`HTMLInputElement.files`**는 파일이 선택되지 않은 경우에도 {{domxref("FileList")}}의 인스턴스를 반환합니다. 따라서 파일 선택 여부를 확인하지 않아도 {{JSxref("Statements/for...of", "for...of")}}를 사용하여 이를 안전하게 반복할 수 있습니다.
```

2024-04-21 00:50 UTC, hazzzi commented on files/ko/web/api/htmlinputelement/files/index.md
> +slug: Web/API/HTMLInputElement/files
오 알려주셔서 감사합니다!

2024-04-21 06:32 UTC, 1ilsang approved these changes
LGTM 👍 고생하셨습니다.

2024-04-21 06:34 UTC, merged