[ko] css align-items 번역
mdn/translated-content pull request #19596
Opened 2024-04-18 17:16 UTC by hazzzi

### Description
https://developer.mozilla.org/en-US/docs/Web/CSS/align-items 번역입니다.

### Related issues and pull requests
Relates to #11913

2024-04-21 23:46 UTC, wisedog requested changes
안녕하세요. 첫 기여 감사합니다! 제 기준에서 리뷰가 약간 늦었는데요. 리뷰 남긴 부분 다시 한 번 확인 부탁드리며, 특히 unordered list 부분이 preview를 봤을때 원문이랑 다릅니다.

2024-04-21 23:46 UTC, wisedog commented on files/ko/web/css/align-items/index.md
> +- CSS flexbox의 기본 개념: _[Basic Concepts of Flexbox](/ko/docs/Web/CSS/CSS_flexible_box_layout/Basic_concepts_of_flexbox)_
기울임꼴은 쓰지 않습니다~ [참고문서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md#%EA%B8%B0%EC%9A%B8%EC%9E%84%EA%BC%B4) 참고해주세요~

2024-04-21 23:46 UTC, wisedog commented on files/ko/web/css/align-items/index.md
> +- The {{cssxref("align-self")}} property
기왕이면 `{{cssxref("align-self")}} 속성` 이라 해주시면 좋겠습니다.

2024-04-21 23:46 UTC, wisedog commented on files/ko/web/css/align-items/index.md
> +  - 플렉스 레이아웃에서만 사용되며 플렉스 아이템을 플렉스 컨테이너의 주축 시작 또는 교차 축 시작에 맞춰 정렬합니다.
Preview를 보니 `en-US` 문서와 다르네요. 아무래도 `-:` 문제인것 같은데 한 번 확인 부탁드려도 될까요?

2024-04-25 11:24 UTC, hazzzi commented on files/ko/web/css/align-items/index.md
> +- CSS flexbox의 기본 개념: _[Basic Concepts of Flexbox](/ko/docs/Web/CSS/CSS_flexible_box_layout/Basic_concepts_of_flexbox)_
안녕하세요 피드백이 늦어서 죄송합니다! 말씀해주신 부분은 수정하였습니다.
다만 궁금한 점이 하나 있습니다. Basic Concepts of Flexbox 라는 문자가 영문이어서 기울림꼴을 그대로 두었는데 타이틀이 한글로 번역이된다면 링크도 함께 기울림꼴을 제거하면 되는걸까요?

2024-04-25 11:25 UTC, hazzzi commented on files/ko/web/css/align-items/index.md
> +- The {{cssxref("align-self")}} property
넵! 수정하겠습니다

2024-04-25 11:25 UTC, hazzzi commented on files/ko/web/css/align-items/index.md
> +  - 플렉스 레이아웃에서만 사용되며 플렉스 아이템을 플렉스 컨테이너의 주축 시작 또는 교차 축 시작에 맞춰 정렬합니다.
오 이 부분 수정하여 커밋하였습니다! 알려주셔서 감사합니다. [4503f42](https://github.com/mdn/translated-content/pull/19596/commits/4503f42d2c536a95873c864f595c6ca26d61fb70)

2024-04-25 14:30 UTC, wisedog commented on files/ko/web/css/align-items/index.md
> +- CSS flexbox의 기본 개념: _[Basic Concepts of Flexbox](/ko/docs/Web/CSS/CSS_flexible_box_layout/Basic_concepts_of_flexbox)_
좋은 질문입니다. 원래라면 해당 링크 문장도 번역해야 맞고 번역하면 기울임꼴도 없어지겠죠? ㅎㅎ 다만 한글 문서에서는 기울임꼴 자체가 별 의미가 없기에 없애는걸 추천드립니다.

2024-04-25 14:47 UTC, wisedog commented on files/ko/web/css/align-items/index.md
> +
@hazzzi  이것 때문에 린트 에러가 나는듯요

2024-04-25 23:57 UTC, hazzzi commented on files/ko/web/css/align-items/index.md
> +- CSS flexbox의 기본 개념: _[Basic Concepts of Flexbox](/ko/docs/Web/CSS/CSS_flexible_box_layout/Basic_concepts_of_flexbox)_
아 그렇군요! 답변감사합니다 링크에도 번역본이 존재하니 링크도 맞춰서 변경하도록 하겠습니다.

2024-04-26 00:11 UTC, hazzzi commented on files/ko/web/css/align-items/index.md
> +- CSS flexbox의 기본 개념: _[Basic Concepts of Flexbox](/ko/docs/Web/CSS/CSS_flexible_box_layout/Basic_concepts_of_flexbox)_
링크의 기울림꼴을 제거하고 문서의 한글 제목이 존재하는 경우 한글로 변경했습니다. [eec582f](https://github.com/mdn/translated-content/pull/19596/commits/eec582f9fdeeac90a9c859e7c2bb1153790899e7), [5a2947d](https://github.com/mdn/translated-content/pull/19596/commits/5a2947db2cbe94a4c1bc6c1c986e6a5d3de2b047)

2024-04-26 00:51 UTC, wisedog commented
마지막 한 줄만 넣으시면 린트 통과할것 같습니다. @hazzzi

2024-04-26 02:53 UTC, wisedog approved these changes
LGTM!

2024-04-26 02:53 UTC, merged

2024-04-26 02:55 UTC, hazzzi commented
@wisedog 리뷰 감사합니다!

2024-04-26 03:09 UTC, wisedog commented
@hazzzi  문서는 바로 MDN에 반영되지 않습니다. 정확하는 모르지만 1~2일뒤에 반영되니 그때 확인해보시면 되요. 고생 많이 하셨습니다.