add ru translation for  webglcontextlost event page
mdn/translated-content pull request #196
Opened 2021-03-17 07:23 UTC by mirexdoors

2021-03-17 11:34 UTC, lex111 commented on files/ru/web/api/htmlcanvaselement/webglcontextlost_event/index.html
> +<p>Событие <code><strong>webglcontextlost</strong></code> является частью <a href="/ru/docs/Web/API/WebGL_API">WebGL API</a>. Оно происходит когда {{Glossary("User agent")}} обнаруживает, что буфер,
Давайте упростим в одно предложение, как в оригинале? ("Событие ... вызывается когда ...")

2021-03-17 11:34 UTC, lex111 commented on files/ru/web/api/htmlcanvaselement/webglcontextlost_event/index.html
> +<p>Вы можете симулировать <code>webglcontextlost</code> событие с помощью расширения {{domxref("WEBGL_lose_context")}}:</p>
Обычно "имитировать" или "эмулировать" используется в таком контексте. Второй вариант немного чаще используется, поэтому можем остановимся на нем пока что.

2021-03-17 17:10 UTC, lex111 commented on files/ru/web/api/htmlcanvaselement/webglcontextlost_event/index.html
> +title: 'HTMLCanvasElement: webglcontextlost event'
"event" тоже можно перевести, кстати идентификаторы в якорных ссылках (`id="Example"`) вроде как тоже переводятся.  Но пока этого делать не нужно, я уточню этот момент. Просто в текущих переводах они переведены, но сомневаюсь, что это хорошее решение.

2021-03-17 17:22 UTC, lex111 commented on files/ru/web/api/htmlcanvaselement/webglcontextlost_event/index.html
> +title: 'HTMLCanvasElement: webglcontextlost event'
Давайте лучше по аналогии с оригиналом ('HTMLCanvasElement: событие webglcontextlost')

2021-03-22 18:40 UTC, myshov requested changes

2021-03-22 18:40 UTC, myshov commented on files/ru/web/api/htmlcanvaselement/webglcontextlost_event/index.html
> +        <th scope="row">Свойство обработчика событий</th>
Думаю, что так будет проще для понимания, так как речь идёт об `onchange`, `onclick` и т.п. Если в этом пункте установлен `none`, значит такое свойство не существует.
```suggestion
        <th scope="row">Свойство для обработки события</th>
```

2021-03-22 18:46 UTC, mirexdoors commented on files/ru/web/api/htmlcanvaselement/webglcontextlost_event/index.html
> +        <th scope="row">Свойство обработчика событий</th>
@myshov тогда возможно лучше "none" перевести как "отсутствует"?

2021-03-22 18:49 UTC, myshov commented on files/ru/web/api/htmlcanvaselement/webglcontextlost_event/index.html
> +        <th scope="row">Свойство обработчика событий</th>
можно, но и "нет" тоже вроде ок

2021-03-22 18:51 UTC, myshov approved these changes

2021-03-22 19:16 UTC, merged

2021-03-22 19:43 UTC, myshov commented on files/ru/web/api/htmlcanvaselement/webglcontextlost_event/index.html
> +        <td>Изначальное определение.</td>
@lex111 @mirexdoors как считаете может эту фразу лучше перевести как "первое определение" или "начальное определение"? Текущий перевод чересчур формальный имхо )

2021-03-22 20:02 UTC, lex111 commented on files/ru/web/api/htmlcanvaselement/webglcontextlost_event/index.html
> +        <td>Изначальное определение.</td>
Согласен, но для меня вообще слово "определение" формально звучит. Думаю в сторону "Первая/первоначальная редакция/версия/вариант", но не уверен, какое из их двух комбинаций слов лучше всего подходит (нравится "первоначальная версия").

2021-03-22 20:21 UTC, mirexdoors commented on files/ru/web/api/htmlcanvaselement/webglcontextlost_event/index.html
> +        <td>Изначальное определение.</td>
Согласен.  "Первоначальный(ая)"  лучше звучит.  Я бы выбрал "первоначальный вариант"

2021-03-22 21:52 UTC, myshov commented on files/ru/web/api/htmlcanvaselement/webglcontextlost_event/index.html
> +        <td>Изначальное определение.</td>
Тоже соглашусь. "Первоначальная версия" или "первая версия" звучит лучше. Слово "вариант" имхо не очень подходит в контексте эволюционного развития стандарта, слово "версия" для этого чаще используется. Слово "редакция" уже больше подходит, но я больше склоняюсь к переводу "версия".

2021-03-22 22:29 UTC, lex111 commented on files/ru/web/api/htmlcanvaselement/webglcontextlost_event/index.html
> +        <td>Изначальное определение.</td>
Хм, не совсем правильно понял в первый раз, тут имеется в виду первое появление? Например, https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object#specifications
Может тогда заменить на "Впервые появился/реализован" или "Первоначальная реализация ". Потому что как раз все остальные варианты вроде "первая версия" будут только сбивать с толку. Это как видно по ссылке выше, где указан "ECMAScript 1-е издание", т.е. там он впервые появился.