[zh-CN] sync translate RTCPeerConnection.addIceCandidate() method
mdn/translated-content pull request #19622
Opened 2024-04-20 14:18 UTC by ciyoe

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-04-20 19:56 UTC, skyclouds2001 commented on files/zh-cn/web/api/rtcpeerconnection/addicecandidate/index.md
> +在协商过程中，你的应用程序可能会收到许多候选者，你将以这种方式将其传递给 ICE 代理，从而使其建立潜在连接列表。这在文章 [WebRTC 连接性](/zh-CN/docs/Web/API/WebRTC_API/Connectivity) 和 [信令以及视频通话](/zh-CN/docs/Web/API/WebRTC_API/Signaling_and_video_calling) 中有更详细的
```suggestion
在协商过程中，你的应用程序可能会收到许多候选者，你将以这种方式将其传递给 ICE 代理，从而使其建立潜在连接列表。这在文章 [WebRTC 连接性](/zh-CN/docs/Web/API/WebRTC_API/Connectivity)和[信令以及视频通话](/zh-CN/docs/Web/API/WebRTC_API/Signaling_and_video_calling)中有更详细的介绍。
```

2024-04-22 09:07 UTC, jasonren0403 requested changes
一些修改建议

2024-04-22 09:07 UTC, jasonren0403 commented on files/zh-cn/web/api/rtcpeerconnection/addicecandidate/index.md
> +但在大多数情况下，你不需要显式设置这个，因为驱动 {{domxref("RTCPeerConnection")}} 的事件将为你处理（候选结束事件），发送适当的事件。
是否可以考虑在原文也加上（候选结束事件）这个注释

2024-04-22 11:38 UTC, yin1999 commented on files/zh-cn/web/api/rtcpeerconnection/addicecandidate/index.md
> +addIceCandidate(candidate, successCallback, failureCallback) // 已废弃
我们统一翻译成“已弃用”

```suggestion
addIceCandidate(candidate, successCallback) // 已弃用
addIceCandidate(candidate, successCallback, failureCallback) // 已弃用
```

2024-04-22 11:48 UTC, ciyoe commented on files/zh-cn/web/api/rtcpeerconnection/addicecandidate/index.md
> +但在大多数情况下，你不需要显式设置这个，因为驱动 {{domxref("RTCPeerConnection")}} 的事件将为你处理（候选结束事件），发送适当的事件。
原文是指 en-US 里面的？
原文英文语境的段落可能对native阅读者来说，不会产生阅读时理解的阻碍，但中文段落在中间有比较长的其他信息插入，所以主观的认为加词备注对阅读者比较友好。

2024-04-22 11:59 UTC, ciyoe commented on files/zh-cn/web/api/rtcpeerconnection/addicecandidate/index.md
> +```js
done

2024-04-22 12:01 UTC, ciyoe commented on files/zh-cn/web/api/rtcpeerconnection/addicecandidate/index.md
误删了，已经加回去。

2024-04-22 14:56 UTC, skyclouds2001 commented on files/zh-cn/web/api/rtcicecandidate/index.md
> +更多关于 `ICE` 的工作流程，可以参考[WebRTC 会话生命周期](/zh-CN/docs/Web/API/WebRTC_API/Session_lifetime)。[WebRTC 连接交互](/zh-CN/docs/Web/API/WebRTC_API/Connectivity)这篇文章则详细介绍了 `ICE` 的工作原理。
```suggestion
更多关于 `ICE` 的工作流程，可以参考 [WebRTC 会话生命周期](/zh-CN/docs/Web/API/WebRTC_API/Session_lifetime)。[WebRTC 连接交互](/zh-CN/docs/Web/API/WebRTC_API/Connectivity)这篇文章则详细介绍了 `ICE` 的工作原理。
```

2024-04-22 15:22 UTC, skyclouds2001 reviewed
参见 https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md#%E4%B8%AD%E6%96%87%E5%92%8C%E6%8B%89%E4%B8%81%E8%AF%AD%E7%B3%BB%E6%96%87%E5%AD%97%E9%97%B4%E5%8A%A0%E7%A9%BA%E6%A0%BC

中文+拉丁语系文字（英文单词、数字等）=保留空格
中文标点+拉丁语系文字=不保留空格

对mdn中的宏（macro），按*渲染后的文字*效果处理，如果不确定可以根据预览效果再做调整

2024-04-22 15:22 UTC, skyclouds2001 commented on files/zh-cn/web/api/rtcicecandidate/index.md
> +`ICE` 候选者描述了 `WebRTC` 能够与远程设备通讯的协议、路由等信息，在启动{{domxref("RTCPeerConnection")}}对等连接时，通常由每个连接方各自提出多个候选者，直到它们互相同意一个它们都认为是最佳的连接候选者描述。`WebRTC` 将使用该候选者描述建立连接。
```suggestion
`ICE` 候选者描述了 `WebRTC` 能够与远程设备通讯的协议、路由等信息，在启动 {{domxref("RTCPeerConnection")}} 对等连接时，通常由每个连接方各自提出多个候选者，直到它们互相同意一个它们都认为是最佳的连接候选者描述。`WebRTC` 将使用该候选者描述建立连接。
```

2024-04-22 15:22 UTC, skyclouds2001 commented on files/zh-cn/web/api/rtcicecandidate/index.md
> +更多关于 `ICE` 的工作流程，可以参考[WebRTC 会话生命周期](/zh-CN/docs/Web/API/WebRTC_API/Session_lifetime)。[WebRTC 连接交互](/zh-CN/docs/Web/API/WebRTC_API/Connectivity)这篇文章则详细介绍了 `ICE` 的工作原理。
```suggestion
更多关于 `ICE` 的工作流程，可以参考 [WebRTC 会话生命周期](/zh-CN/docs/Web/API/WebRTC_API/Session_lifetime)。[WebRTC 连接交互](/zh-CN/docs/Web/API/WebRTC_API/Connectivity)这篇文章则详细介绍了 `ICE` 的工作原理。
```

2024-04-22 15:22 UTC, skyclouds2001 commented on files/zh-cn/web/api/rtcicecandidate/index.md
> +    > **备注：** 为了向后兼容，构造函数也接受一个包含{{domxref("RTCIceCandidate.candidate", "candidate")}}属性值字符串参数，以此替代配置对象。
```suggestion
    > **备注：** 为了向后兼容，构造函数也接受一个包含 {{domxref("RTCIceCandidate.candidate", "candidate")}} 属性值字符串参数，以此替代配置对象。
```

2024-04-22 15:22 UTC, skyclouds2001 commented on files/zh-cn/web/api/rtcicecandidate/index.md
> +  - : 返回一个包含 `RTCIceCandidate` 当前配置的{{Glossary("JSON")}}对象。其格式与 `candidateInfo` 对象相同，可作为可选参数传入{{domxref("RTCIceCandidate.RTCIceCandidate()","RTCIceCandidate()")}} 构造一个新的 `RTCIceCandidate` 实例。
```suggestion
  - : 返回一个包含 `RTCIceCandidate` 当前配置的 {{Glossary("JSON")}} 对象。其格式与 `candidateInfo` 对象相同，可作为可选参数传入 {{domxref("RTCIceCandidate.RTCIceCandidate()","RTCIceCandidate()")}} 构造一个新的 `RTCIceCandidate` 实例。
```

2024-04-22 15:22 UTC, skyclouds2001 commented on files/zh-cn/web/api/rtcicecandidate/index.md
> +  - : 一个包含随机生成的用户名片段（`“ice-ufrag”`）的字符串，`ICE` 与随机生成的密码（`“ice-pwd”`）一起用于消息完整性。你可以使用此字符串来验证 `ICE` 生成的代数；同一 `ICE` 进程的每一代将使用相同的用户名片段 (`usernameFragment`)，即使 `ICE` 重新启动也是如此。
```suggestion
  - : 一个包含随机生成的用户名片段（`“ice-ufrag”`）的字符串，`ICE` 与随机生成的密码（`“ice-pwd”`）一起用于消息完整性。你可以使用此字符串来验证 `ICE` 生成的代数；同一 `ICE` 进程的每一代将使用相同的用户名片段（`usernameFragment`），即使 `ICE` 重新启动也是如此。
```

2024-04-22 15:22 UTC, skyclouds2001 commented on files/zh-cn/web/api/rtcicecandidate/index.md
> +  - : 表示候选者是用 `RTP` 或者 `RTCP`的字符串，返回值有 `rtp` 或 `rtcp`，该值是来自 `candidate` 属性行的 `"component-id"` 字段。
```suggestion
  - : 表示候选者是用 `RTP` 或者 `RTCP` 的字符串，返回值有 `rtp` 或 `rtcp`，该值是来自 `candidate` 属性行的 `"component-id"` 字段。
```

2024-04-22 15:22 UTC, skyclouds2001 commented on files/zh-cn/web/api/rtcicecandidate/index.md
> +  - : 表示用于连接检查的候选者的传输地址的字符串。此地址的格式是在{{RFC(5245)}}中定义的候选者属性（`candidate-attribute`）。如果 `RTCIceCandidate` 是候选者结束（"end of candidates"）指示器，则此字符串为空字符串（`""`）。
```suggestion
  - : 表示用于连接检查的候选者的传输地址的字符串。此地址的格式是在 {{RFC(5245)}}中定义的候选者属性（`candidate-attribute`）。如果 `RTCIceCandidate` 是候选者结束（"end of candidates"）指示器，则此字符串为空字符串（`""`）。
```

2024-04-22 15:22 UTC, skyclouds2001 commented on files/zh-cn/web/api/rtcicecandidate/index.md
> +  - : 如果值不为 `null`，`sdpMLineIndex` 表示 `SDP` 中候选者关联的从零开始的媒体描述索引编号（在[RFC 4566](https://datatracker.ietf.org/doc/html/rfc4566) 中定义）。
```suggestion
  - : 如果值不为 `null`，`sdpMLineIndex` 表示 `SDP` 中候选者关联的从零开始的媒体描述索引编号（在 [RFC 4566](https://datatracker.ietf.org/doc/html/rfc4566)中定义）。
```

2024-04-22 16:26 UTC, skyclouds2001 commented
关于处理大量评审意见时候有个建议，可以利用 batch suggestions 机制避免分别提交每条评审意见导致的大量 commit 影响观感的情况

![image](https://github.com/mdn/translated-content/assets/95597335/f34a5fb8-4bfc-4648-a98f-55bece36595c)

![image](https://github.com/mdn/translated-content/assets/95597335/832af09c-50bc-4f13-974e-682e0ec12720)

![image](https://github.com/mdn/translated-content/assets/95597335/8c64cb07-d5f5-4ecf-ae8f-900c0b2ce1b3)

2024-04-23 04:46 UTC, jasonren0403 reviewed
以下是rtcicecandidate主页的审阅

发现之前有的审阅没有反馈，建议检查files changed选项卡以避免遗漏

2024-04-23 04:46 UTC, jasonren0403 commented on files/zh-cn/web/api/rtcicecandidate/index.md
> +  - : 表示用于连接检查的候选者的传输地址的字符串。此地址的格式是在 {{RFC(5245)}}中定义的候选者属性（`candidate-attribute`）。如果 `RTCIceCandidate` 是候选者结束（"end of candidates"）指示器，则此字符串为空字符串（`""`）。
```suggestion
  - : 表示用于连接检查的候选者的传输地址的字符串。此地址的格式是在 {{RFC(5245)}} 中定义的候选者属性（`candidate-attribute`）。如果 `RTCIceCandidate` 是候选者结束（"end of candidates"）指示器，则此字符串为空字符串（`""`）。
```

2024-04-23 04:46 UTC, jasonren0403 commented on files/zh-cn/web/api/rtcicecandidate/index.md
> +  - : 返回一个包含唯一标识符的字符串，该标识符对于来自相同的 `STUN` 服务器的相同类型、共享相同的基础（`ICE` 代理发送候选者的地址）的候选者都是相同的。这有助于优化 `ICE` 的性能，因为当在两个 `RTCIceTransport` 对象上出现多个候选者时，可以利用这些标识符来进行优先级排序和关联性判断。
```suggestion
  - : 返回一个包含唯一标识符的字符串，该标识符对于来自相同的 {{Glossary("STUN")}} 服务器的相同类型、共享相同的基础（ICE 代理发送候选者的地址）的候选者都是相同的。这有助于优化 ICE 的性能，因为当在两个 {{domxref("RTCIceTransport")}} 对象上出现多个候选者时，可以利用这些标识符来进行优先级排序和关联性判断。
```

2024-04-23 04:46 UTC, jasonren0403 commented on files/zh-cn/web/api/rtcicecandidate/index.md
> +  - : 如果值不为 `null`，`sdpMLineIndex` 表示 `SDP` 中候选者关联的从零开始的媒体描述索引编号（在 [RFC 4566](https://datatracker.ietf.org/doc/html/rfc4566)中定义）。
```suggestion
  - : 如果值不为 `null`，`sdpMLineIndex` 表示 `SDP` 中候选者关联的从零开始的媒体描述索引编号（在 [RFC 4566](https://datatracker.ietf.org/doc/html/rfc4566) 中定义）。
```

2024-04-23 04:46 UTC, jasonren0403 commented on files/zh-cn/web/api/rtcicecandidate/index.md
> +  - : 如果协议 (`protocol`) 是 `"tcp"` ，`tcpType` 表示 `TCP` 类型的候选者。否则 `tcpType` 为 `null`。
```suggestion
  - : 如果 `protocol` 是 `"tcp"`，`tcpType` 表示 TCP 候选者的类型。否则 `tcpType` 为 `null`。
```

2024-04-23 04:46 UTC, jasonren0403 commented on files/zh-cn/web/api/rtcicecandidate/index.md
> +  - : 表示候选者类型的字符串，该值为 [`RTCIceCandidate.type`](/zh-CN/docs/Web/API/RTCIceCandidate/type#values) 中列出的字符串之一。
```suggestion
  - : 表示候选者类型的字符串，该值为 [`RTCIceCandidate.type`](/zh-CN/docs/Web/API/RTCIceCandidate/type#值) 中列出的字符串之一。
```

2024-04-23 04:46 UTC, jasonren0403 commented on files/zh-cn/web/api/rtcicecandidate/index.md
> +  - : 一个包含随机生成的用户名片段（`“ice-ufrag”`）的字符串，`ICE` 与随机生成的密码（`“ice-pwd”`）一起用于消息完整性。你可以使用此字符串来验证 `ICE` 生成的代数；同一 `ICE` 进程的每一代将使用相同的用户名片段（`usernameFragment`），即使 `ICE` 重新启动也是如此。
```suggestion
  - : 一个包含随机生成的用户名片段（“ice-ufrag”）的字符串，ICE 与随机生成的密码（“ice-pwd”）一起用于消息完整性。你可以使用此字符串来验证 ICE 生成的代数；同一 ICE 进程的每一代将使用相同的 `usernameFragment`，即使 ICE 重新启动也是如此。
```

2024-04-23 04:46 UTC, jasonren0403 commented on files/zh-cn/web/api/rtcicecandidate/index.md
> +  - : 返回一个包含 `RTCIceCandidate` 当前配置的 {{Glossary("JSON")}} 对象。其格式与 `candidateInfo` 对象相同，可作为可选参数传入 {{domxref("RTCIceCandidate.RTCIceCandidate()","RTCIceCandidate()")}} 构造一个新的 `RTCIceCandidate` 实例。
```suggestion
  - : 返回一个包含 `RTCIceCandidate` 当前配置的 {{Glossary("JSON")}} 对象。其格式与 `candidateInfo` 对象相同，可作为可选参数传入 {{domxref("RTCIceCandidate.RTCIceCandidate()","RTCIceCandidate()")}} 构造函数构造一个新的 `RTCIceCandidate` 实例。
```

2024-04-23 11:58 UTC, jasonren0403 approved these changes
👍 LGTM, Thanks @ciyoe , @skyclouds2001 and @yin1999

2024-04-23 12:02 UTC, merged