[ko] BigInt.prototype.toString() 신규 번역
mdn/translated-content pull request #19667
Opened 2024-04-22 14:35 UTC by wisedog

- BigInt.prototype.toString() 신규 번역

2024-04-28 14:48 UTC, 1ilsang requested changes
@wisedog 님 안녕하세요. 기여해주셔서 감사합니다! 💯

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

질문이나 도움이 필요하시다면 언제든 멘션 부탁드리겠습니다.

2024-04-28 14:48 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/bigint/tostring/index.md
> +  - : BigInt 값을 표현하기 위해 사용할 기저를 지정하기 위해 사용하는 2부터 36까지의 정수로 기저. 기본 값은 10.
```suggestion
  - : BigInt 값을 표현하기 위해 사용할 기저를 지정하기 위해 사용하는 2부터 36까지의 정수. 기본 값은 10.
```

2024-04-28 14:48 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/bigint/tostring/index.md
> +{{jsxref("BigInt")}} 객체는 {{jsxref("Object")}}의 `toString` 메서드를 재정의합니다. 즉 {{jsxref("Object.prototype.toString()")}}를 상속받지 않습니다. {{jsxref("BigInt")}} 값의 경우 `toString()` 메서드는 값을 명시된 기저에 따라 표현하는 문자열을 반환합
```suggestion
{{jsxref("BigInt")}} 객체는 {{jsxref("Object")}}의 `toString` 메서드를 재정의합니다. 즉 {{jsxref("Object.prototype.toString()")}}를 상속받지 않습니다.
{{jsxref("BigInt")}} 값의 경우 `toString()` 메서드는 값을 명시된 기저에 따라 표현하는 문자열을 반환합니다.
```

줄 수는 원본과 동일하게 해주세요.

관련 논의는 아래에서 확인 부탁 드립니다.

- https://github.com/orgs/mdn/discussions/655#discussioncomment-9251708

2024-04-28 14:48 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/bigint/tostring/index.md
> +명시된 BigInt 값이 음수일 경우 부호는 보존됩니다. 기저가 2일 경우에도 마찬가지 입니다. 반환되는 문자열은 앞에 `-`부호가 붙은 양의 2진 표현이며, BigInt값의 2의 보수가 아닙니다.
```suggestion
명시된 BigInt 값이 음수일 경우 부호는 보존됩니다. 기저가 2일 경우에도 마찬가지 입니다. 반환되는 문자열은 앞에 `-`부호가 붙은 양의 2진 표현이며, BigInt 값의 2의 보수가 **아닙니다**.
```

2024-05-02 22:59 UTC, wisedog commented
리뷰 감사합니다. 말씀하신 수정사항 모두 반영했습니다. 다시 리뷰 요청드릴께요

2024-05-03 03:26 UTC, 1ilsang approved these changes
LGTM 고생하셨습니다!

2024-05-03 03:26 UTC, merged