PT-BR translation of the async/await reference
mdn/translated-content pull request #1968
Opened 2021-08-07 15:30 UTC by izaccavalheiro

Create a PT-BR translated content for async/await reference

2021-08-12 11:51 UTC, josielrocha requested changes

2021-08-12 11:51 UTC, josielrocha commented on files/pt-br/learn/javascript/asynchronous/async_await/index.html
> +<p class="summary">Adições mais recentes à linguagem JavaScript são as funções assíncronas e a palavra-chave await, adicionadas no ECMAScript 2017. Esses recursos atuam basicamente como um syntactic
Poderia, por favor, incluir o link em "fuções assíncronas" e "await"?
![image](https://user-images.githubusercontent.com/1158643/129191170-56486bf4-9f9c-4cd8-a7be-36719a998beb.png)

2021-08-12 11:51 UTC, josielrocha commented on files/pt-br/learn/javascript/asynchronous/async_await/index.html
> +    <p>Ah. A invocação da função agora retorna uma promise. Isso é uma das características das funções assíncronas — seus valores de retorno são garantidos para serem convertidos em promessas.</p>
Em alguns parágrafos há a referência à Promises como `promises` e aqui como `promessas`. O que acha de normalizar esses termos e utilizar apenas `promises` ou apenas `promessas`?

2021-08-12 11:51 UTC, josielrocha commented on files/pt-br/learn/javascript/asynchronous/async_await/index.html
> +  <h2 id="Conclusao">Conclusão</h2>
O artigo original (https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await#the_await_keyword) possui diversas outras seções. Poderia, por favor, incluí-las na tradução?

2021-08-19 22:13 UTC, izaccavalheiro commented
I made the requested changes

2021-08-28 15:18 UTC, josielrocha approved these changes

2021-08-28 15:18 UTC, merged

2021-08-28 15:18 UTC, josielrocha commented
Obrigado pela contribuição @izaccavalheiro 
👍🏽