edit react_components
mdn/translated-content pull request #197
Opened 2021-03-17 08:46 UTC by rewrite0w0

I modified the mischaracter of react_components. 
also translated the non-translation part.

2021-03-17 16:43 UTC, mfuji09 requested changes
- 少し古いバージョンの英語版をもとに翻訳されているようです。文書の部分的な修正ではなく全面的な更新を行うのであれば、 mdn/content リポジトリにある最新版の英語版を確認し、差分の更新をお願いします。
- リンクのほとんどが英語ページへのリンクのままになっています。日本語記事へリンクを更新するようお願いします。

2021-03-18 12:57 UTC, mfuji09 commented
@rewrite0w0 さん
韓国語版のコンテンツを追加しても、私はレビューできません。このプルリクエストには日本語版のみを入れてください。
You added Korean versions of the content, so I cannot review them. Please include only the Japanese version in this pull request.

また、一度プルリクエストを行った後で、後から別なファイルを追加することは（必要のない限り）避けるようお願いします。
Also, once you have made a pull request, please avoid adding another file later (unless necessary).

2021-03-18 16:34 UTC, rewrite0w0 commented
Thank you for your advice!
It's my first time contributing, so I'm lacking a lot. 
I deleted the Korean document. :)

2021-03-19 14:48 UTC, mfuji09 commented
@rewrite0w0 さん
韓国語版の編集を削除した際に、最初のレビューの指摘事項が元に戻ってしまっているようなので、その指摘事項の修正のみを反映させていただけますか？
When you deleted the Korean translation of the edit, it seems that the points made in the first review have been also reverted. Could you please reflect only the correction of those points?

2021-03-20 04:29 UTC, rewrite0w0 commented
I modified the file [here](https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html) to base! check it one more time Please.

[ここ](https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html)のファイルをベースで修正させていただきました。
すみませんがもう一回、確認お願いします。

2021-03-21 16:13 UTC, mfuji09 commented
@rewrite0w0 さん
原文と比較して、不自然に改行が多く入っているのですが（例えば、1行の長さが長いわけでもないのにHTMLタグの中で改行しているなど）、この改変には何か意味があるのでしょうか。できれば、原文に合わせていただきたいと思います（原文との対応付けが困難になるので）。

また、表記については https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline に合わせてくださるようお願いします。
（ブラウザ→ブラウザー、英字と日本語の間を1文字空ける、など）

2021-03-22 12:36 UTC, rewrite0w0 commented
[ここ](https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline)を参考させて反映します。
あと改行は prettier 関連問題なので off に代わった状態で作業します。
ありがとうございます。
:)

2021-03-23 15:55 UTC, mfuji09 requested changes
もう一度よく読んでみました。以下の件が見つかりましたので、修正をお願いいたします。

2021-03-23 15:55 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
> +<p>私たちは食べたいだけではなく、他にもやるべきこと — そう、TODO があります。次に、異なるコンポーネント呼び出しで別々のコンテンツをレンダリングする方法を見てみましょう。</p>
この文は直前の図で、todoとしてeatが繰り返して表示されていることについて言っているものです。ですから、「食べたい」と TODO が同列ではなく、 TODO の中に eat があるというニュアンスで説明するべきだと思います。
「私たちがすべきことは、食べることだけではありません。そう、他にもすべきことがあります。」のように訳すべきだと思います。

2021-03-23 15:55 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
> +<p><em>これで、</em>ブラウザーには3つの一意のタスクが表示されるようになりました。しかし、もう一つの問題が残っています: これらはすべてデフォルトでチェックされています。</p>
日本語と数字の間は1文字空けるようお願いします。

2021-03-23 15:55 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
> +
alt 属性の中、「あるチェックボックスはチェックされ、他のチェックボックスはチェックされませんでした」という箇所は、原文では過去形ではありません。

2021-03-23 15:55 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
> +<p><code>App.js</code> では、それぞれの <code>&lt;Todo /&gt;</code> に名前の props を与えます。先ほどのタスクの名前を使ってみましょう。</p>
「名前の props を与えます」の部分ですが、原文を読むと name というのはプロパティ名のようですので、「name prop を与えます」の方が適切だと思います。

2021-03-23 15:55 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
> +<p>元の静的リストでは、<code>Eat</code> だけがチェックされていました。もう一度言いますが、<code>&lt;Todo /&gt;</code> コンポーネントを構成するUIのほとんどを再利用しつつ、一つだけ変更したいのです。これは別の props が良い仕事をしてくれます！ <code>App.js</code> での各 <code>&lt;Todo /&gt;</code
UI についても、日本語との間に半角スペースを空けてください。

2021-03-23 15:55 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
> +<p>import の後 <code>ReactDOM.render()</code> より前の行で以下の <code>const</code> を作成してください。</p>
原文の "In src/index.js," の部分の訳が抜けていますので、追加をお願いします。

2021-03-23 15:55 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
> +  <p><strong>注</strong>: <code>ALL_CAPS</code> 定数名は JavaScript では特別な意味はありません; 他の開発者に「このデータはここで定義された後は変更されません」と伝えるための慣習です。 </p>
\<code>ALL_CAPS\</code> の部分は「すべて大文字」であることを表していますので、それが分かるような表記にしてください。

2021-03-23 15:55 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
> +<p>これで、すべてのコンポーネントを再表示できるようになりましたが、まだやるべきことがあります。現在、ブラウザーは各タスクの名前を構造化されていないテキストとして表示しています。私たちが HTML の構造を失っているからです。— <code>&lt;li&gt;</code> と checkboxes、buttons! のことです。</p>
「私たちが HTML の構造を失っているからです」は不自然だと思います。「私たちが HTML の構造を見逃しているからです」などの訳のほうが適切だと思います。

2021-03-23 15:55 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
> +<h2 id="Componentizing_the_rest_of_the_app">アプリの残り部分をコンポネント化 </h2>
表記ゆれ。「コンポネント化」→「コンポーネント化」であるべきです。

2021-03-23 15:55 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
> +<p><code>components/Form.js</code> 開いて、以下のようにしてください。</p>
「\<code>components/Form.js\</code>」 と「開いて」の間に「を」が抜けています。

2021-03-23 15:55 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
> +  <li>Todo.js で行ったように、ファイルの先頭で React を Import します。</li>
Import は原文では文頭にあるため大文字で始まっていますが、日本語では文頭にならないうえ、プログラム中のキーワードなので小文字で表記すべきです。

2021-03-23 15:55 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
> +<p><code>FilterButton.js</code> を <code>Form.js</code> のようにします。でもコンポーネントの <code>FilterButton()</code> を呼び出し、<div>要素内の最初のボタンの HTML をコピーして <code>App.js</code> の <code>filters</code> のクラスを <code>return<
「クラス」は原文では \<code> 要素になっており、キーワードですので訳すべきではないと思います。

2021-03-23 15:55 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
>  <p>ファイルの内容は以下のようになります:</p>
文中で末尾のコロンを「:」のままにしたり、「。」に修正したりしているので、どちらかに統一をお願いします。（私は「。」に修正したほうが適切だと思います。）

2021-03-23 15:55 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
> +  <p><strong>注</strong>: ここでは、最初に <code>&lt;Todo /&gt;</code> コンポーネントで行ったのと同じ間違いをしていることに気づくかもしれません。つまり、それぞれのボタンは同じものになるということです。これでいいのです。このコンポーネントの修正は、後ほどで行います <a href="/ja/docs/Learn/Tools_and_testin
原文ではフラグメントの #back_to_the_filter_buttons が小文字になっていますので、合わせてください。

2021-03-26 04:55 UTC, rewrite0w0 commented
アドバイスの通り修正しました。
たくさん学ぶことができました、ありがとうございます。:D

2021-03-26 17:11 UTC, merged

2021-03-26 17:12 UTC, mfuji09 commented
いくつか修正するべき点が残っていたので、私の方で修正しました。

2021-03-27 03:54 UTC, rewrite0w0 commented
はい。