[ko] HTMLInputElement labels 속성 신규 번역
mdn/translated-content pull request #19818
Opened 2024-04-28 06:30 UTC by hazzzi

### Description
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/labels 신규 번역입니다.

### Motivation

### Additional details

### Related issues and pull requests

2024-04-28 14:52 UTC, 1ilsang requested changes
@hazzzi 님 안녕하세요. 기여해주셔서 감사합니다! 💯

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

질문이나 도움이 필요하시다면 언제든 멘션 부탁드리겠습니다.

2024-04-28 14:52 UTC, 1ilsang commented on files/ko/web/api/htmlinputelement/labels/index.md
> +`<input>` 요소와 연관된 `<label>` 요소를 포함하는 {{domxref("NodeList")}}입니다.
```suggestion
`<input>` 요소와 연관된 `<label>` 요소를 포함하는
{{domxref("NodeList")}}입니다.
```

위와 동일합니다. 줄 수는 원본과 동일하게 해주세요.

2024-04-28 14:52 UTC, 1ilsang commented on files/ko/web/api/htmlinputelement/labels/index.md
> +**`HTMLInputElement.labels`** 읽기 전용 속성은 요소가 숨겨져 있지 않은 경우 {{HTMLElement("input")}} 요소와 연관된 {{HTMLElement("label")}} 요소의 {{domxref("NodeList")}}를 반환합니다. 요소의 타입이 `hidden`인 경우, 속성은 `null`을 반환합니다.
```suggestion
**`HTMLInputElement.labels`** 읽기 전용 속성은 요소가 숨겨져 있지 않은 경우
{{HTMLElement("input")}} 요소와 연관된 {{HTMLElement("label")}} 요소의
{{domxref("NodeList")}}를 반환합니다.
요소의 타입이 `hidden`인 경우, 속성은 `null`을 반환합니다.
```

줄 수는 원본과 동일하게 해주세요.

관련 논의는 아래에서 확인 부탁 드립니다.

- https://github.com/orgs/mdn/discussions/655#discussioncomment-9251708

2024-04-28 16:00 UTC, hazzzi commented on files/ko/web/api/htmlinputelement/labels/index.md
> +**`HTMLInputElement.labels`** 읽기 전용 속성은 요소가 숨겨져 있지 않은 경우 {{HTMLElement("input")}} 요소와 연관된 {{HTMLElement("label")}} 요소의 {{domxref("NodeList")}}를 반환합니다. 요소의 타입이 `hidden`인 경우, 속성은 `null`을 반환합니다.
안녕하세요. 코멘트 남겨주셔서 감사합니다. 앞으로 번역 시 적절한 위치에서 개행하여 줄 수를 원본과 동일하게 맞추면 될까요?

2024-04-28 23:24 UTC, 1ilsang commented on files/ko/web/api/htmlinputelement/labels/index.md
> +**`HTMLInputElement.labels`** 읽기 전용 속성은 요소가 숨겨져 있지 않은 경우 {{HTMLElement("input")}} 요소와 연관된 {{HTMLElement("label")}} 요소의 {{domxref("NodeList")}}를 반환합니다. 요소의 타입이 `hidden`인 경우, 속성은 `null`을 반환합니다.
네 맞습니다. 개행 위치의 특정한 조건은 없습니다.

2024-04-29 00:14 UTC, hazzzi commented on files/ko/web/api/htmlinputelement/labels/index.md
> +**`HTMLInputElement.labels`** 읽기 전용 속성은 요소가 숨겨져 있지 않은 경우 {{HTMLElement("input")}} 요소와 연관된 {{HTMLElement("label")}} 요소의 {{domxref("NodeList")}}를 반환합니다. 요소의 타입이 `hidden`인 경우, 속성은 `null`을 반환합니다.
네 감사합니다!

2024-04-29 00:21 UTC, 1ilsang approved these changes
고생하셨습니다

2024-04-29 00:21 UTC, merged