[zh-cn]: sync translation for `using the permissions api`
mdn/translated-content pull request #19838
Opened 2024-04-29 05:33 UTC by tianyeeT

### Description

Update the translation of the file.

### Motivation

### Additional details

### Related issues and pull requests
Part of issue #19612

2024-04-29 06:28 UTC, skyclouds2001 requested changes
还有很多内容尚待同步，还请仔细比较原文与译文

2024-04-29 07:51 UTC, skyclouds2001 reviewed
另外原来的翻译存在大量的格式问题，可以的话也一并修正一下吧

2024-04-29 07:51 UTC, skyclouds2001 commented on files/zh-cn/web/api/permissions_api/using_the_permissions_api/index.md
>  {{DefaultAPISidebar("Permissions API")}}{{SeeCompatTable}}
```suggestion
{{DefaultAPISidebar("Permissions API")}}{
```

https://github.com/mdn/content/blob/main/files/en-us/web/api/permissions_api/using_the_permissions_api/index.md?plain=1#L9

2024-04-29 07:51 UTC, skyclouds2001 commented on files/zh-cn/web/api/permissions_api/using_the_permissions_api/index.md
>  title: Using the Permissions API
```suggestion
title: 使用 Permissions API
```

2024-04-29 07:51 UTC, skyclouds2001 commented on files/zh-cn/web/api/permissions_api/using_the_permissions_api/index.md
> +你可以 [在线运行](https://chrisdavidmills.github.io/location-finder-permissions-api/)，或 [在 Github 查看源码](https://github.com/chrisdavidmills/location-finder-permissions-api/tree/gh-pages)。大部分代码都很简单且常见 ── 所以接下
```suggestion
你可以[在线运行示例](https://chrisdavidmills.github.io/location-finder-permissions-api/)，或[在 Github 查看源代码](https://github.com/chrisdavidmills/location-finder-permissions-api/tree/gh-pages)。大部分代码都很简单且常见──所以接下来我们会重点关注和 Permissions API 有关的代码，如果你想学习其他部分，请自行阅读。
```

2024-04-29 07:51 UTC, skyclouds2001 commented on files/zh-cn/web/api/permissions_api/using_the_permissions_api/index.md
>  ![Screenshot showing a map of Greenfield, UK.](location-finder-with-permissions-api.png)
图片的标题也需要翻译一下

2024-04-29 07:51 UTC, skyclouds2001 commented on files/zh-cn/web/api/permissions_api/using_the_permissions_api/index.md
> +{{domxref("Permissions")}}还有其他方法可用于专门请求使用 API 的权限和撤销权限，但这些方法已被弃用（非标准和/或不被广泛支持）。
```suggestion
{{domxref("Permissions")}} 还有其他方法可用于专门请求使用 API 的权限和撤销权限，但这些方法已被弃用（非标准及不被广泛支持）。
```

2024-04-29 07:51 UTC, skyclouds2001 commented on files/zh-cn/web/api/permissions_api/using_the_permissions_api/index.md
> +本文提供了使用 W3C [Permission API](/zh-CN/docs/Web/API/Permissions_API)的基本说明，它提供了一种程序上的方式来查询当前上下文的 API 权限授权状态。
```suggestion
本文提供了使用 W3C [Permissions API](/zh-CN/docs/Web/API/Permissions_API) 的基本说明，它提供了一种编程方式来查询当前上下文的 API 权限授权状态。
```

2024-04-29 07:51 UTC, skyclouds2001 commented on files/zh-cn/web/api/permissions_api/using_the_permissions_api/index.md
> +由于历史原因，不同的 API 使用各自不同的方式来处理自己的权限 ── 例如，[Notification API](/zh-CN/docs/Web/API/Notifications_API)允许显式地检查权限状态和申请权限，然而，[Geolocation API](/zh-CN/docs/Web/API/Geolocation_API) 却不能（如果用户拒绝了首次权限请求，就会造成我们下面将要
```suggestion
由于历史原因，不同的 API 使用各自不同的方式来处理自己的权限──例如，[Notification API](/zh-CN/docs/Web/API/Notifications_API) 允许显式地检查权限状态和申请权限，然而，[Geolocation API](/zh-CN/docs/Web/API/Geolocation_API) 却不能。
```

https://github.com/mdn/content/blob/main/files/en-us/web/api/permissions_api/using_the_permissions_api/index.md?plain=1#L17

2024-04-29 07:51 UTC, skyclouds2001 commented on files/zh-cn/web/api/permissions_api/using_the_permissions_api/index.md
> +[Permissions API](/zh-CN/docs/Web/API/Permissions_API) 提供了一系列工具来让开发者在权限方面实现更好的用户体验。具体来说，开发人员可以使用 {{domxref("Permissions.query()")}} 来检查在当前上下文中使用特定 API 的权限是已授予、已拒绝还是需要通过提示获得特定用户权限。在主线程中查询权限是被[广泛支持](/z
```suggestion
[Permissions API](/zh-CN/docs/Web/API/Permissions_API) 提供了一系列工具来让开发者在权限方面实现更好的用户体验。具体来说，开发人员可以使用 {{domxref("Permissions.query()")}} 来检查在当前上下文中使用特定 API 的权限是已授予、已拒绝还是需要通过提示获得特定用户权限。在主线程中查询权限是被[广泛支持](/zh-CN/docs/Web/API/Permissions_API#api.navigator.permissions)的，在 [Worker](/zh-CN/docs/Web/API/Permissions_API#api.workernavigator.permissions) 中也是如此（但有一个明显的例外）。
```

2024-04-29 07:51 UTC, skyclouds2001 commented on files/zh-cn/web/api/permissions_api/using_the_permissions_api/index.md
另外请重点关注一下代码的部分的同步

2024-04-30 09:03 UTC, yin1999 approved these changes
感谢 @tianyeeT、@skyclouds2001

2024-04-30 09:05 UTC, merged