[zh-cn]: Update the translation of public class fields in class section
mdn/translated-content pull request #19871
Opened 2024-04-29 15:59 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests
Public class fields part of #18329

2024-04-30 11:35 UTC, yin1999 requested changes
链接文字未翻译、注释未翻译、中文之间多余的空格、中英文之间空格缺失等问题还请先解决一下。参考 #19857

2024-04-30 21:58 UTC, BSPR0002 requested changes

2024-04-30 21:58 UTC, BSPR0002 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
> +  static staticFieldWithInitializer = "static field";
```suggestion
  static staticFieldWithInitializer = "静态字段";
```

2024-04-30 21:58 UTC, BSPR0002 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
> +  [`${PREFIX}Field`] = "prefixed field";
```suggestion
  fieldWithInitializer = "实例字段";
  [`${PREFIX}Field`] = "带前缀字段";
```

2024-04-30 21:58 UTC, BSPR0002 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
> +// Both instances have the same field name
```suggestion
// 两个实例拥有相同的字段名称
```

2024-04-30 21:58 UTC, BSPR0002 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
> +  baseField = "base field";
```suggestion
  baseField = "基类字段";
```

2024-04-30 21:58 UTC, BSPR0002 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
>      return "base method output";
```suggestion
    return "基类方法输出";
```

2024-04-30 21:58 UTC, BSPR0002 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
> +console.log(sub.subField); // "base method output"
```suggestion
console.log(sub.subField); // "基类方法输出"
```

2024-04-30 21:58 UTC, BSPR0002 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
> +console.log(base.anotherBaseField); // "base field"
```suggestion
console.log(base.anotherBaseField); // "基类字段"
```

2024-04-30 21:58 UTC, BSPR0002 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
> +每次创建新实例时，都会对字段初始化表达式进行评估。(因为每个实例的 `this` 值都不同，所以初始化表达式可以访问特定于实例的属性）。
```suggestion
每次创建新实例时，都会对字段初始化表达式进行求值。（因为每个实例的 `this` 值都不同，所以初始化表达式可以访问特定于实例的属性）。
```

2024-04-30 21:58 UTC, BSPR0002 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
> +  name = nameArg; // nameArg is out of scope of the constructor
```suggestion
  name = nameArg; // nameArg 在构造函数的作用域外
```

2024-04-30 21:58 UTC, BSPR0002 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
> +  // All instances of Person will have the same name
```suggestion
  // Person 的所有实例会有相同的 name
```

2024-04-30 21:58 UTC, BSPR0002 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
> +  name = `Professor ${this.name}`;
```suggestion
  name = `${this.name} 教授`;
```

2024-04-30 21:58 UTC, BSPR0002 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
> +console.log(new Professor("Radev", 54).name); // "Professor Radev"
```suggestion
console.log(new Professor("Radev", 54).name); // "Radev 教授"
```

2024-04-30 21:58 UTC, BSPR0002 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
> +- 公共方法请参见 [method definitions](/zh-CN/docs/Web/JavaScript/Reference/Functions/Method_definitions)。
```suggestion
- 关于私有字段，请参阅[私有属性](/zh-CN/docs/Web/JavaScript/Reference/Classes/Private_properties)。
- 公共方法请参见[方法的定义](/zh-CN/docs/Web/JavaScript/Reference/Functions/Method_definitions)。
```

2024-04-30 21:58 UTC, BSPR0002 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
> +计算出的字段名只在[类定义时](/zh-CN/docs/Web/JavaScript/Reference/Classes#evaluation_order)评估一次。这意味着每个类总是有一组固定的字段名，两个实例不能通过计算的名称拥有不同的字段名。计算表达式中的 `this` 值是围绕类定义的 `this` ，而引用类名会导致{{jsxref("ReferenceError")}}，因为类尚未初
```suggestion
计算出的字段名只在[类定义时](/zh-CN/docs/Web/JavaScript/Reference/Classes#evaluation_order)评估一次。这意味着每个类总是有一组固定的字段名，两个实例不能通过计算的名称拥有不同的字段名。计算表达式中的 `this` 值是围绕类定义的 `this`，而引用类名会导致{{jsxref("ReferenceError")}}，因为类尚未初始化。在此表达式中，{{jsxref("Operators/await", "await")}} 和 {{jsxref("Operators/yield", "yield")}} 按预期工作。
```
多提一嘴，“计算表达式中的 `this` 值是围绕类定义的 `this`”这个表述有点奇怪，在 Class 的 Overview 也遇到过，但那里用了别的译法，是否应该校对一下或修改英语原文？

2024-04-30 21:58 UTC, BSPR0002 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
> +在字段初始化器中，[`this`](/zh-CN/docs/Web/JavaScript/Reference/Operators/this) 指的是正在构建的类实例，而 [`super`](/zh-CN/docs/Web/JavaScript/Reference/Operators/super)指的是基类的 `prototype` 属性，它包含基类的实例方法，但不包含其实例字段。
```suggestion
在字段初始化器中，[`this`](/zh-CN/docs/Web/JavaScript/Reference/Operators/this) 指向正在构建的类实例，而 [`super`](/zh-CN/docs/Web/JavaScript/Reference/Operators/super) 指向基类的 `prototype` 属性，它包含基类的实例方法，但不包含其实例字段。
```

2024-04-30 21:58 UTC, BSPR0002 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
> +由于类字段是使用 [`[[DefineOwnProperty]]`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/defineProperty)语义（本质上是 {{jsxref("Object.defineProperty()")}} ）添加的，因此派生类中的字段声明不会调用基类中的设置器。这种行为不同于在构造函
```suggestion
由于类字段是使用 [`[[DefineOwnProperty]]`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/defineProperty) 语义（本质上是 {{jsxref("Object.defineProperty()")}}）添加的，因此派生类中的字段声明不会调用基类中的设置器。这种行为不同于在构造函数中使用 `this.field = ...`。
```

2024-04-30 21:58 UTC, BSPR0002 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
> +> **备注：** 在类字段规范最终确定为`[[DefineOwnProperty]]`语义之前，包括 [Babel](https://babeljs.io/) 和 [tsc](https://www.typescriptlang.org/)在内的大多数转译器都将类字段转换为 `DerivedWithConstructor` 形式，这在类字段规范化之后造成了一些微妙的错误。
```suggestion
> **备注：**在类字段规范最终确定为 `[[DefineOwnProperty]]` 语义之前，包括 [Babel](https://babeljs.io/) 和 [tsc](https://www.typescriptlang.org/) 在内的大多数转译器都将类字段转换为 `DerivedWithConstructor` 形式，这在类字段规范化之后造成了一些微妙的错误。
```

2024-04-30 21:58 UTC, BSPR0002 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
> +console.log(instance.prefixField); // "prefixed field"
```suggestion
console.log(instance.fieldWithInitializer); // "实例字段"
console.log(instance.prefixField); // "带前缀字段"
```

2024-04-30 21:58 UTC, BSPR0002 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
>  const instance2 = new DerivedWithConstructor(); // Logs 1
```suggestion
const instance2 = new DerivedWithConstructor(); // 打印 1
```

2024-05-07 07:11 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
> +不过，即使声明一个空的类字段也是有好处的，因为这表明了字段的存在，从而允许类型检查程序和人类读者静态分析类的形状。
“形状”这一翻译有点抽象

```suggestion
不过，即使声明一个空的类字段也是有好处的，因为这表明了字段的存在，从而允许类型检查程序和人类读者静态分析类的结构。
```

2024-05-07 07:11 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
````suggestion

```js
class Person {
  name;
  age;
  constructor(properties) {
    Object.assign(this, properties);
  }
}
```

由于初始化器是在基类执行完成后求值的，因此你可以访问由基类构造函数创建的属性。

````

2024-05-07 07:11 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
> +- [使用类](/zh-CN/docs/Web/JavaScript/Guide/Using_classes) guide
```suggestion
- [使用类](/zh-CN/docs/Web/JavaScript/Guide/Using_classes)指南
```

2024-05-07 16:37 UTC, BSPR0002 commented
> 这里应该特指“此 `this` 并非实例中的 `this`”，其用于指代当前的类定义本身，而非实例。我觉得这与 https://github.com/mdn/translated-content/commit/02d6f5008ae6a906bc2275a2295323e22b1492ba 中的翻译其实类似

@yin1999 问题是，这个 `this` 实际上并不指向类本身，而是作用域的 this。相当于，类还不存在，正在借助外部的 this 创建类。
![image](https://github.com/mdn/translated-content/assets/42113148/c5ab67b4-3e0e-4369-a7f3-a60dfe1048ad)

2024-05-08 02:30 UTC, yin1999 commented
> > 这里应该特指“此 `this` 并非实例中的 `this`”，其用于指代当前的类定义本身，而非实例。我觉得这与 [02d6f50](https://github.com/mdn/translated-content/commit/02d6f5008ae6a906bc2275a2295323e22b1492ba) 中的翻译其实类似
> 
> @yin1999 问题是，这个 `this` 实际上并不指向类本身，而是作用域的 this。相当于，类还不存在，正在借助外部的 this 创建类。 ![image](https://private-user-images.githubusercontent.com/42113148/328604501-c5ab67b4-3e0e-4369-a7f3-a60dfe1048ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzUzNTgsIm5iZiI6MTcxNTEzNTA1OCwicGF0aCI6Ii80MjExMzE0OC8zMjg2MDQ1MDEtYzVhYjY3YjQtM2UwZS00MzY5LWE3ZjMtYTYwZGZlMTA0OGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAyMjQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmN2IxMzk5ZGQyZjlhMzUyZTdmMDk5YThlM2RmNGRiYzRhZTdkMDhjNzY1NjE5ZTgwOWM3MjU2NDQ4MWQyMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HwxMeM7Tvf427XVuXf4DCHPyEKGhEWWHU2MmkpYwBA8)

是的，我理解错了 :+1:

2024-05-08 02:32 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/public_class_fields/index.md
> +计算出的字段名只在[类定义时](/zh-CN/docs/Web/JavaScript/Reference/Classes#evaluation_order)评估一次。这意味着每个类总是有一组固定的字段名，两个实例不能通过计算的名称拥有不同的字段名。计算表达式中的 `this` 值是围绕类定义的 `this` ，而引用类名会导致{{jsxref("ReferenceError")}}，因为类尚未初
```suggestion
只在[类定义时](/zh-CN/docs/Web/JavaScript/Reference/Classes#求值顺序)对计算字段名进行一次求值。这意味着每个类总是有一组固定的字段名，两个实例不能通过计算的名称拥有不同的字段名。计算表达式中的 `this` 指向类声明所处上下文的 `this`，而引用类名会导致 {{jsxref("ReferenceError")}}，因为类尚未初始化。在此表达式中，{{jsxref("Operators/await", "await")}} 和 {{jsxref("Operators/yield", "yield")}} 按预期工作。
```

2024-05-08 02:32 UTC, yin1999 approved these changes
:+1:

2024-05-08 02:35 UTC, merged