[zh-cn]: Create the translation of static initialization block in cla…
mdn/translated-content pull request #19883
Opened 2024-04-30 01:57 UTC by tianyeeT

…ss section

### Description

### Motivation

### Additional details

### Related issues and pull requests
Static initialization block part of #18329

2024-04-30 17:57 UTC, skyclouds2001 requested changes
同 https://github.com/mdn/translated-content/pull/19871#pullrequestreview-2031032333

2024-05-08 00:18 UTC, yin1999 reviewed
一些建议

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +title: 静态初始块
```suggestion
title: 静态初始化块
```

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +{{jsxref("Statements/class", "class")}} 类主体中可以包含任意数量的 `static {}` 初始块。这些静态字段与任何交错的静态字段初始器一起，按照声明的顺序进行 [评估](/zh-CN/docs/Web/JavaScript/Reference/Classes#evaluation_order)。超类的任何静态初始化都是先进行的，然后才是子类的初始化。
```suggestion
{{jsxref("Statements/class", "类", "", "nocode")}}主体中可以包含任意数量的 `static {}` 初始化块。这些静态初始化块与任何交错的静态字段初始器一起，按照声明的顺序进行[求值](/zh-CN/docs/Web/JavaScript/Reference/Classes#求值顺序)。先进行父类的静态初始化，然后才是子类的静态初始化。
```

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +静态代码块内声明的变量的作用域是该代码块的本地变量。这包括 `var`、`function`、`const` 和 `let` 声明。代码块中的 `var` 声明不会被提升。
```suggestion
静态代码块内声明的变量的作用域是该代码块的本地。这包括 `var`、`function`、`const` 和 `let` 声明。代码块中的 `var` 声明不会被提升。
```

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +var y = "Outer y";
```suggestion
var y = "外部的 y";
```

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +  static field = "Inner y";
```suggestion
  static field = "内部的 y";
```

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +console.log(y); // 'Outer y'
```suggestion
console.log(y); // '外部的 y'
```

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +静态代码块中的 `this` 是指类的构造函数对象。`super.property` 可用于访问超类的静态属性。但请注意，在类的静态初始化代码块中调用 {{jsxref("Operators/super", "super()")}} 或使用 {{jsxref("Functions/arguments", "arguments")}} 对象都是语法错误。
```suggestion
静态代码块中的 `this` 是指类的构造函数对象。`super.property` 可用于访问父类的静态属性。但请注意，在类的静态初始化块中调用 {{jsxref("Operators/super", "super()")}} 或使用 {{jsxref("Functions/arguments", "arguments")}} 对象都会造成语法错误。
```

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +这些语句是同步执行的。在此代码块中不能使用 {{jsxref("Operators/await", "await")}} 或 {{jsxref("Operators/yield", "yield")}} 。(将初始化语句视为隐式封装在函数中）。
```suggestion
这些语句是同步执行的。在这些代码块中不能使用 {{jsxref("Operators/await", "await")}} 或 {{jsxref("Operators/yield", "yield")}}。（将初始化语句视为隐式封装在函数中。）
```

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +静态代码块的作用域嵌套在类主体的词法作用域内，可以访问类内声明的 [私有名称](/zh-CN/docs/Web/JavaScript/Reference/Classes/Private_properties)，而不会导致语法错误。
```suggestion
静态代码块的作用域嵌套在类主体的词法作用域*内*，并且可以访问类内声明的[私有名称](/zh-CN/docs/Web/JavaScript/Reference/Classes/Private_properties)，而不会导致语法错误。
```

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +[静态字段](/zh-CN/docs/Web/JavaScript/Reference/Classes/static) 初始化器和静态初始化块是逐个评估的。初始化块可以引用其上方的字段值，但不能引用其下方的字段值。所有静态方法都会事先添加并可以访问，但如果这些方法引用的字段位于当前块的下方，则调用这些方法时可能会出现与预期不符的情况。
```suggestion
[静态字段](/zh-CN/docs/Web/JavaScript/Reference/Classes/static)初始化器和静态初始化块是逐个求值的。初始化块可以引用其上方的字段值，但不能引用其下方的字段值。所有静态方法都会事先添加并可以访问，但如果这些方法引用的字段位于当前块的下方，则调用这些方法时可能会出现与预期不符的情况。
```

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +> **备忘：** 对于 [私有静态字段](/zh-CN/docs/Web/JavaScript/Reference/Classes/Private_properties) 而言，这一点更为重要，因为访问未初始化的私有字段会抛出 {{jsxref("TypeError")}}，即使该私有字段已在下面声明。(如果未声明私有字段，则会提前抛出{{jsxref("SyntaxError")}}）。
```suggestion
> **备忘：** 对于[私有静态字段](/zh-CN/docs/Web/JavaScript/Reference/Classes/Private_properties)而言，这一点更为重要，因为访问未初始化的私有字段会抛出 {{jsxref("TypeError")}}，即使该私有字段已在下面声明。（如果未声明私有字段，则会提前抛出{{jsxref("SyntaxError")}}。）
```

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +## 例子
https://github.com/mdn/translated-content/blob/main/docs/zh-cn/glossary.md#%E6%A0%87%E9%A2%98%E8%A1%A8%E6%A0%BC

```suggestion
## 示例
```

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +### 多区块
```suggestion
### 多个代码块
```

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +下面的代码演示了一个带有静态初始化块和交错静态字段初始化器的类。输出结果显示，块和字段是按执行顺序进行评估的。
```suggestion
下面的代码演示了一个带有静态初始化块和交错的静态字段初始化器的类。输出结果显示，块和字段是按执行顺序进行求值的。
```

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +请注意，超类的任何静态初始化都是先进行的，然后才是子类的初始化。
```suggestion
请注意，父类的任何静态初始化都是先进行的，然后才是子类的初始化。
```

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +  static field = "static field";
```suggestion
  static field = "静态字段";
```

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +// 'static field'
```suggestion
// '静态字段'
```

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +[`super.property`](/zh-CN/docs/Web/JavaScript/Reference/Operators/super) 语法可在 `static` 代码块中使用，以引用超类的静态属性。
```suggestion
[`super.property`](/zh-CN/docs/Web/JavaScript/Reference/Operators/super) 语法可在 `static` 代码块中使用，以引用父类的静态属性。
```

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +  static field = "static field";
```suggestion
  static field = "静态字段";
```

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +// 'static field'
```suggestion
// '静态字段'
```

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +console.log(getDPrivateField(new D("private"))); // 'private'
```suggestion
console.log(getDPrivateField(new D("私有"))); // '私有'
```

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +- [使用类](/zh-CN/docs/Web/JavaScript/Guide/Using_classes) guide
```suggestion
- [使用类](/zh-CN/docs/Web/JavaScript/Guide/Using_classes)指南
```

2024-05-08 00:18 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +- [ES2022 功能：类的静态初始块](https://2ality.com/2021/09/class-static-block.html) by Dr. Axel Rauschmayer (2021)
```suggestion
- v8.dev 上的[类的静态初始块](https://v8.dev/features/class-static-initializer-blocks)（2021）
- [ES2022 特性：类的静态初始块](https://2ality.com/2021/09/class-static-block.html) 来自 Axel Rauschmayer 博士（2021）
```

2024-05-08 01:15 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/classes/static_initialization_blocks/index.md
> +静态代码块中的 `this` 是指类的构造函数对象。这段代码展示了如何访问公共静态字段。
同 https://github.com/mdn/translated-content/pull/19872#discussion_r1593259852

```suggestion
静态代码块中的 `this` 是指类的构造函数对象。这段代码展示了如何访问公有静态字段。
```

2024-05-08 02:08 UTC, yin1999 approved these changes
感谢 @tianyeeT。一开始翻译的时候我们建议先挑简单的翻译，或者就选择一两个文档翻译。因为确实有些规则比较复杂，是一开始参与贡献的贡献者难以快速掌握的。这些内容需要慢慢熟悉。我建议是可以先看一下[我们的翻译指南](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md)和[如何使用 makdown 来撰写文档](https://developer.mozilla.org/zh-CN/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN)。当然 MDN 对刚接触本地化内容贡献的贡献者还是不够友好，这块我们也一直在进行相应的改进。如果有翻译上面的问题，欢迎通过社交软件[与我们取得联系](https://developer.mozilla.org/zh-CN/docs/MDN/Community/Contributing/Translated_content#%E6%B1%89%E8%AF%AD%EF%BC%88zh-cn%E3%80%81zh-tw%EF%BC%89)

2024-05-08 02:08 UTC, merged