[zh-cn]: Update the translation of export
mdn/translated-content pull request #19893
Opened 2024-04-30 05:48 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests
export part of issue #18266

2024-04-30 18:34 UTC, skyclouds2001 reviewed
参见 https://github.com/mdn/translated-content/pull/19871#pullrequestreview-2031032333

2024-04-30 18:34 UTC, skyclouds2001 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +要在源文件中使用 `export` 声明，运行时必须将该文件解释为 [模块](/zh-CN/docs/Web/JavaScript/Guide/Modules)。在 HTML 中，可通过在 {{HTMLElement("script")}} 标记中添加 `type="module"` 或由其他模块导入来实现。模块会自动以 [严格](/zh-CN/docs/Web/JavaScript/Refer
```suggestion
要在源文件中使用 `export` 声明，运行时必须将该文件解释为[模块](/zh-CN/docs/Web/JavaScript/Guide/Modules)。在 HTML 中，可通过在 {{HTMLElement("script")}} 标记中添加 `type="module"` 或由其他模块导入来实现。模块会自动以[严格模式](/zh-CN/docs/Web/JavaScript/Reference/Strict_mode)解释。
```

2024-04-30 18:34 UTC, skyclouds2001 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +// const、function、class）
```suggestion
// 导出单个特征（可导出 var、let、const、function、class）
```

2024-04-30 18:34 UTC, skyclouds2001 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +在 `export` 关键字之后，你可以使用 `let`、`const` 和 `var` 声明，以及函数或类声明。你还可以使用 `export { name1, name2 }` 语法导出在其他地方声明的名称列表。请注意，"export {}"不会导出一个空对象——它是一个不导出任何东西（一个空的名称列表）的无操作声明。
```suggestion
在 `export` 关键字之后，你可以使用 `let`、`const` 和 `var` 声明，以及函数或类声明。你还可以使用 `export { name1, name2 }` 语法导出在其他地方声明的名称列表。请注意，`export {}` 不会导出一个空对象——它是一个不导出任何东西（一个空的名称列表）的无操作声明。
```

2024-04-30 18:34 UTC, skyclouds2001 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +// 使用 `x` 的值。
```suggestion
// 这样做是可行的，因为 `export` 只是一个声明，并没有使用 `x` 的值。
```

2024-04-30 18:34 UTC, skyclouds2001 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +导出声明不受 [临时死区](/zh-CN/docs/Web/JavaScript/Reference/Statements/let#temporal_dead_zone_tdz) 规则的限制。你可以在声明名称 `X` 之前声明模块导出 `X`。
```suggestion
导出声明不受[临时死区](/zh-CN/docs/Web/JavaScript/Reference/Statements/let#暂时性死区)规则的限制。你可以在声明名称 `X` 之前声明模块导出 `X`。
```

2024-04-30 18:34 UTC, skyclouds2001 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +> **备忘：** 导出声明的名称必须相互独立。导出名称重复或使用多个 `default` 导出将导致{{jsxref("SyntaxError")}}并阻止模块被评估。
```suggestion
> **备注：** 导出声明的名称必须相互独立。导出名称重复或使用多个 `default` 导出将导致 {{jsxref("SyntaxError")}} 并阻止模块被执行。
```

2024-04-30 18:34 UTC, skyclouds2001 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +作为一种特殊情况，函数和类是作为 _声明_ 而不是表达式导出的，而且这些声明可以是匿名的。这意味着函数将被悬挂。
```suggestion
作为一种特殊情况，函数和类是作为*声明*而不是表达式导出的，而且这些声明可以是匿名的。这意味着函数将被悬挂。
```

考虑“hoisted”的翻译

2024-04-30 18:34 UTC, skyclouds2001 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +// 不是函数表达式
```suggestion
// 有效是因为 `foo` 是函数声明，而不是函数表达式
```

2024-04-30 18:34 UTC, skyclouds2001 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +// 但允许匿名
```suggestion
// 从技术上讲，它仍然是一个声明，但允许匿名
```

2024-04-30 18:34 UTC, skyclouds2001 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +// file test.js
```suggestion
// test.js 文件
```

2024-04-30 18:34 UTC, skyclouds2001 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +// some other file
```suggestion
// 其他一些文件
```

2024-04-30 18:34 UTC, skyclouds2001 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
>  ### 重导出 / 聚合
```suggestion
### 重导出/聚合
```

2024-04-30 18:34 UTC, skyclouds2001 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +模块还可以 "中继 "从其他模块导出的值，而无需编写两条单独的导入/导出语句。这在创建一个集中了来自不同模块的各种导出值的单一模块（通常称为 "桶模块"）时通常非常有用。
```suggestion
模块还可以“中继”从其他模块导出的值，而无需编写两条单独的导入及导出语句。这在创建一个集中了来自不同模块的各种导出值的单一模块（通常称为“桶模块”）时通常非常有用。
```

2024-04-30 18:34 UTC, skyclouds2001 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +大多数 "import from" 语法都有对应的 "export from" 语法。
```suggestion
大多数“import from”语法都有对应的“export from”语法。
```

2024-04-30 18:34 UTC, skyclouds2001 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +虽然没有 `import * from "mod"`，但也有 `export * from "mod"`。这会将 `mod` 中的所有**命名**导出语句重新导出为当前模块的命名导出语句，但 `mod` 的默认导出语句不会被重新导出。如果有两个通配符 exports 语句隐式地重新导出了相同的名称，则这两个语句都不会被重新导出。
```suggestion
虽然没有 `import * from "mod"`，但也有 `export * from "mod"`。这会将 `mod` 中的所有**命名**导出语句重新导出为当前模块的命名导出语句，但 `mod` 的默认导出语句不会被重新导出。如果有两个通配符导出语句隐式地重新导出了相同的名称，则这两个语句都不会被重新导出。
```

2024-04-30 18:34 UTC, skyclouds2001 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +”export from“语法允许省略 `as` 标记，这使得默认导出仍作为默认导出重新导出。
```suggestion
“export from”语法允许省略 `as` 标记，这使得默认导出仍作为默认导出重新导出。
```

2024-04-30 18:34 UTC, skyclouds2001 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +- [Exploring JS, Ch.16: Modules](https://exploringjs.com/es6/ch_modules.html) by Dr. Axel Rauschmayer
链接标题还请翻译一下

2024-05-08 01:33 UTC, yin1999 requested changes
我真的感觉你翻译内容太快了，有时真的不够仔细。还请认真翻译每一个文档，而不是快速提交这些 PR，由其他贡献者或者审查员来纠正大量的错误（说实话，这些工作为我们带来了大量的负担，望理解）。

2024-05-08 01:33 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
>  在创建 JavaScript 模块时，**`export`** 语句用于从模块中导出实时绑定的函数、对象或原始值，以便其他程序可以通过 {{jsxref("Statements/import", "import")}} 语句使用它们。被导出的绑定值依然可以在本地进行修改。在使用 import 进行导入时，这些绑定值只能被导入模块所读取，但在 export 导出模块中对这些绑定值进行修改，所修改的
这一段并未同步

2024-05-08 01:33 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +  - : 要导出的标识符（以便其他脚本通过 {{jsxref("Statements/import", "import")}} 语句进行导入）。如果使用带有 `as` 的别名，实际导出的名称可以指定为字符串字面形式，但它可能不是有效的标识符。
```suggestion
  - : 要导出的标识符（以便其他脚本通过 {{jsxref("Statements/import", "import")}} 语句进行导入）。如果使用带有 `as` 的别名，实际导出的名称可以指定为字符串字面量，但它可能不是有效的标识符。
```

2024-05-08 01:33 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
>  命名导出：
具名导出，前一段也请修改

2024-05-08 01:33 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +// 导出其它地方声明的特征
特征？

2024-05-08 01:33 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +// 导出单个特征（可导出 var、let、const、function、class）
+1

2024-05-08 01:33 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +导出声明不受[临时死区](/zh-CN/docs/Web/JavaScript/Reference/Statements/let#暂时性死区)规则的限制。你可以在声明名称 `X` 之前声明模块导出 `X`。
```suggestion
导出声明不受[暂时性死区](/zh-CN/docs/Web/JavaScript/Reference/Statements/let#暂时性死区)规则的限制。你可以在声明名称 `X` 之前声明当前模块导出 `X`。
```

2024-05-08 01:33 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +作为一种特殊情况，函数和类是作为*声明*而不是表达式导出的，而且这些声明可以是匿名的。这意味着函数将被悬挂。
```suggestion
作为一种特殊情况，函数和类是作为*声明*而不是表达式导出的，而且这些声明可以是匿名的。这意味着函数将被提升。
```

2024-05-08 01:33 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +命名导出在需要导出多个值时非常有用。导入此模块时，命名导出必须使用完全相同的名称（可选择用 `as` 重命名），但默认导出可以使用任何名称导入。例如：
```suggestion
具名导出在需要导出多个值时非常有用。导入此模块时，具名导出必须使用完全相同的名称（可选择用 `as` 重命名），但默认导出可以使用任何名称导入。例如：
```

2024-05-08 01:33 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +// 其他一些文件
```suggestion
// 其他文件
```

2024-05-08 01:33 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +import m from "./test"; // 请注意，我们可以自由地使用导入 m 而不是导入 k，因为 k 是默认导出值
```suggestion
import m from "./test"; // 请注意，我们可以自由地使用 import m 而不是 import k，因为 k 是默认导出
```

2024-05-08 01:33 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +你还可以重命名已命名的导出，以避免命名冲突：
```suggestion
你还可以对具名导出进行重命名，以避免命名冲突：
```

2024-05-08 01:33 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +你可以使用字符串文字将名称重命名为非有效标识符。例如：
```suggestion
你可以使用字符串字面量将名称重命名为非有效标识符。例如：
```

2024-05-08 01:33 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +虽然没有 `import * from "mod"`，但也有 `export * from "mod"`。这会将 `mod` 中的所有**命名**导出语句重新导出为当前模块的命名导出语句，但 `mod` 的默认导出语句不会被重新导出。如果有两个通配符导出语句隐式地重新导出了相同的名称，则这两个语句都不会被重新导出。
```suggestion
虽然没有 `import * from "mod"`，但也有 `export * from "mod"`。这会将 `mod` 中的所有**具名**导出重新导出为当前模块的具名导出，但 `mod` 的默认导出不会被重新导出。如果有两个通配符导出语句隐式地重新导出了相同的名称，则这两个语句都不会被重新导出。
```

2024-05-08 01:33 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +如果试图直接导入重复的名称，则会出错。
```suggestion
如果试图直接导入重复的名称，则会抛出错。
```

2024-05-08 01:33 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +正确的做法是重新命名导出：
原翻译更易理解，你可以再考虑一下（新的翻译是有歧义的）：

```suggestion
正确的做法是重新命名这个导出：
```

2024-05-08 01:33 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +- [探索 JS，第 16 章：模块](https://exploringjs.com/es6/ch_modules.html) 由 Dr. Axel Rauschmayer 所著
```suggestion
- [探索 JS，第 16 章：模块](https://exploringjs.com/es6/ch_modules.html) 由 Axel Rauschmayer 博士所著
```

2024-05-08 01:33 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
>  ### 使用命名导出
下面的代码块没更新

```suggestion
### 使用具名导出
```

2024-05-08 02:04 UTC, tianyeeT commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +// 导出其它地方声明的特征
https://github.com/mdn/content/blob/d7342e4c53efe1bd6d6d4ee66016b08c3d8e9b55/files/en-us/web/javascript/reference/statements/export/index.md?plain=1#L63-L64

var/let/const这类关键字算作是变量的「特征」吗，或者有没有更为合适的译法。

2024-05-08 02:10 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +// 导出其它地方声明的特征
用原来的翻译——特性——即可

2024-05-08 02:38 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/statements/export/index.md
> +**`export`** 声明用于从 JavaScript 模块中导出值。导出的值可通过 {{jsxref("Statements/import", "import")}} 声明或[dynamic import](/zh-CN/docs/Web/JavaScript/Reference/Operators/import)导入其他程序。导入绑定的值会在导出该绑定的模块中发生变化--当模块更新其导出
```suggestion
**`export`** 声明用于从 JavaScript 模块中导出值。导出的值可通过 {{jsxref("Statements/import", "import")}} 声明或[动态导入](/zh-CN/docs/Web/JavaScript/Reference/Operators/import)来将其导入其他程序。导入绑定的值会在导出该绑定的模块中发生变化——当模块更新其导出绑定的值时，更新将在其导入值中可见。
```

2024-05-08 02:43 UTC, yin1999 approved these changes
感谢 @tianyeeT

2024-05-08 02:44 UTC, merged