zh-tw: update translation of glossary - attribute
mdn/translated-content pull request #19936
Opened 2024-05-01 07:21 UTC by PassionPenguin

2024-05-02 12:18 UTC, yin1999 requested changes
内容并没有和[英文文档的](https://developer.mozilla.org/en-US/docs/Glossary/Attribute)同步

2024-05-02 12:27 UTC, PassionPenguin commented
> 内容并没有和[英文文档的](https://developer.mozilla.org/en-US/docs/Glossary/Attribute)同步

hah? what's diff?

2024-05-03 04:19 UTC, PassionPenguin reviewed
真没注意这一句，

2024-05-03 04:19 UTC, PassionPenguin commented on files/zh-tw/glossary/attribute/index.md
> +**標籤屬性** （Attribute）用於擴充 HTML {{Glossary("tag")}}，可改變標籤行為或提供額外資訊。
```suggestion
**標籤屬性** （Attribute）用於擴充 HTML、XML {{Glossary("tag")}}，可改變標籤行為或提供額外資訊。
```

2024-05-04 01:46 UTC, yin1999 commented on files/zh-tw/glossary/attribute/index.md
> +**標籤屬性** （Attribute）用於擴充 HTML、XML {{Glossary("tag")}}，可改變標籤行為或提供額外資訊。
```suggestion
**標籤屬性**（attribute）用於擴充 HTML 或 XML {{Glossary("element", "元素")}}，可改變其行為或提供後設資料。
```

2024-05-04 01:46 UTC, yin1999 commented on files/zh-tw/glossary/attribute/index.md
> +<!-- 或者 XML： -->
```suggestion
<!-- 等同於⋯⋯ -->
<input required="" />
<!-- 或者 -->
```

2024-05-04 01:46 UTC, yin1999 commented on files/zh-tw/glossary/attribute/index.md
>  ### 技術參考
```suggestion
## 參見
```

2024-05-04 01:46 UTC, yin1999 commented on files/zh-tw/glossary/attribute/index.md
> +一個標籤屬性通常的格式為 `name=value`（以屬性名稱對上屬性值）。
```suggestion
標籤屬性通常的格式為 `name=value`（屬性的標識符後面接其關聯值）。
```

2024-05-04 01:48 UTC, yin1999 approved these changes

2024-05-04 01:49 UTC, merged