zh-cn: update glossary/base64
mdn/translated-content pull request #19939
Opened 2024-05-01 07:58 UTC by PassionPenguin

2024-05-05 13:38 UTC, jasonren0403 commented on files/zh-cn/glossary/base64/index.md
> +一种常见的变体是 "URL 安全的 Base64"，它省略了填充并将 `+/` 替换为 `-_`，以避免在 URL 路径段或查询参数中可能引起问题的字符。
```suggestion
一种常见的变体是“URL 安全的 Base64”，它省略了填充，并将 `+/` 替换为 `-_`，以避免在 URL 路径段或查询参数中可能引起问题的字符。
```

2024-05-05 13:38 UTC, jasonren0403 commented on files/zh-cn/glossary/base64/index.md
> +- 通过[多用途互聯網郵件擴展](https://zh.wikipedia.org/wiki/多用途互聯網郵件擴展)进行电子邮件
```suggestion
- 通过[多用途互联网邮件扩展](https://zh.wikipedia.org/wiki/多用途互聯網郵件擴展)发送电子邮件
```

2024-05-05 13:38 UTC, jasonren0403 commented on files/zh-cn/glossary/base64/index.md
> +每个 Base64 数字代表 6 位数据。因此，输入字符串/二进制文件的三个 8 位字节（3×8 位 = 24 位）可以用四个 6 位 Base64 数字（4×6 = 24 位）表示。
```suggestion
每个 Base64 位代表 6 位数据。因此，输入字符串/二进制文件的三个 8 位字节（3×8 位 = 24 位）可以用四个 6 位 Base64 位（4×6 = 24 位）表示。
```

2024-05-05 13:38 UTC, jasonren0403 commented on files/zh-cn/glossary/base64/index.md
> +- [`btoa()`](/zh-CN/docs/Web/API/btoa)：从二进制数据“字符串”创建一个 Base64 编码的 ASCII 字符串（“btoa”意思是“二进制到 ASCII”）
原文无引号

```suggestion
- [`btoa()`](/zh-CN/docs/Web/API/btoa)：从二进制数据字符串创建一个 Base64 编码的 ASCII 字符串（“btoa”应看作“从二进制到 ASCII”）
```

2024-05-05 13:38 UTC, jasonren0403 commented on files/zh-cn/glossary/base64/index.md
> +- [`atob()`](/zh-CN/docs/Web/API/atob)：解码通过 Base64 编码的字符串数据（“atob”意思是“ASCII 到二进制”）
```suggestion
- [`atob()`](/zh-CN/docs/Web/API/atob)：解码通过 Base64 编码的字符串数据（“atob”应看作“从 ASCII 到二进制”）
```

2024-05-05 13:38 UTC, jasonren0403 commented on files/zh-cn/glossary/base64/index.md
> +> 然而，字节到代码点的对应关系只能可靠地适用于代码点到 `0x7f`。此外，超过 `0xff` 的代码点将导致 `btoa` 抛出错误，因为超过了 1 字节的最大值。下一节详细介绍了如何解决在编码任意 Unicode 文本时的这种限制。
```suggestion
> 然而，字节到代码点的对应关系只能可靠地适用于最高为 `0x7f` 的码位。此外，超过 `0xff` 的代码点将导致 `btoa` 抛出错误，因为超过了 1 字节的最大值。下一节详细介绍了如何解决在编码任意 Unicode 文本时的这种限制。
```

2024-05-05 13:38 UTC, jasonren0403 commented on files/zh-cn/glossary/base64/index.md
> +> **备注：** Base64 是一种二进制编码，而不是文本编码，但是在 Web 平台支持二进制数据类型之前，`btoa` 和 `atob` 被添加到了其中。因此，这两个函数使用字符串来表示二进制数据，其中每个字符的代码点表示每个字节的值。这导致了一个普遍的误解，即 `btoa` 可以用来编码任意文本数据，例如创建文本或 HTML 文档的 Base64 `data:` URL。
code point: https://zh.wikipedia.org/zh-cn/%E7%A0%81%E4%BD%8D （码位）

2024-05-05 13:38 UTC, jasonren0403 commented on files/zh-cn/glossary/base64/index.md
> +由于 `btoa` 将其输入字符串的代码点解释为字节值，因此如果字符的代码点超过 `0xff`，则调用 `btoa` 将导致"Character Out Of Range"异常。对于需要编码任意 Unicode 文本的时候，需要首先将字符串转换为其 UTF-8 中的字节，并然后对字节进行编码。
code point 问题同上
```suggestion
由于 `btoa` 将其输入字符串的代码点解释为字节值，因此如果字符的代码点超过 `0xff`，调用 `btoa` 将导致“Character Out Of Range”异常。对于需要编码任意 Unicode 文本的用例，需要首先将字符串转换为其 UTF-8 的组成字节，然后对这些字节进行编码。
```

2024-05-05 13:38 UTC, jasonren0403 commented on files/zh-cn/glossary/base64/index.md
> +最简单的解决方案是使用 TextEncoder 和 TextDecoder 在 UTF-8 和字符串的单字节表示之间进行转换：
注意格式同步

2024-05-05 13:38 UTC, jasonren0403 commented on files/zh-cn/glossary/base64/index.md
> +// 使用
```suggestion
// 用法
```

2024-05-05 13:38 UTC, jasonren0403 commented on files/zh-cn/glossary/base64/index.md
> +// 使用
```suggestion
// 用法
```

2024-05-05 14:03 UTC, PassionPenguin commented on files/zh-cn/glossary/base64/index.md
> +> **备注：** Base64 是一种二进制编码，而不是文本编码，但是在 Web 平台支持二进制数据类型之前，`btoa` 和 `atob` 被添加到了其中。因此，这两个函数使用字符串来表示二进制数据，其中每个字符的代码点表示每个字节的值。这导致了一个普遍的误解，即 `btoa` 可以用来编码任意文本数据，例如创建文本或 HTML 文档的 Base64 `data:` URL。
可以考虑提一个pr，给源文件加个macro（codepoint是个glossary）

2024-05-06 11:46 UTC, PassionPenguin commented on files/zh-cn/glossary/base64/index.md
> +> **备注：** Base64 是一种二进制编码，而不是文本编码，但是在 Web 平台支持二进制数据类型之前，`btoa` 和 `atob` 被添加到了其中。因此，这两个函数使用字符串来表示二进制数据，其中每个字符的代码点表示每个字节的值。这导致了一个普遍的误解，即 `btoa` 可以用来编码任意文本数据，例如创建文本或 HTML 文档的 Base64 `data:` URL。
这里忘记改了，可以先merge，我后续一起修之前在上游提的pr叭

2024-05-08 01:37 UTC, jasonren0403 requested changes
同步一下最新的改动

2024-05-08 01:37 UTC, jasonren0403 commented on files/zh-cn/glossary/base64/index.md
> +  sourceCommit: 45421b1345139445c3364f3adf0713be90381eff
```suggestion
  sourceCommit: 76d86face9211c33ba965763996ef09c7ee1fc68
```

2024-05-08 01:37 UTC, jasonren0403 commented on files/zh-cn/glossary/base64/index.md
> +> **备注：** Base64 是一种二进制编码，而不是文本编码，但是在 Web 平台支持二进制数据类型之前，`btoa` 和 `atob` 被添加到了其中。因此，这两个函数使用字符串来表示二进制数据，其中每个字符的码位表示每个字节的值。这导致了一个普遍的误解，即 `btoa` 可以用来编码任意文本数据，例如创建文本或 HTML 文档的 Base64 `data:` URL。
```suggestion
> **备注：** Base64 是一种二进制编码，而不是文本编码，但是在 Web 平台支持二进制数据类型之前，`btoa` 和 `atob` 被添加到了其中。因此，这两个函数使用字符串来表示二进制数据，其中每个字符的{{glossary("code point", "码位")}}表示每个字节的值。这导致了一个普遍的误解，即 `btoa` 可以用来编码任意文本数据，例如创建文本或 HTML 文档的 Base64 `data:` URL。
```

2024-05-08 01:37 UTC, jasonren0403 commented on files/zh-cn/glossary/base64/index.md
> +由于 `btoa` 将其输入字符串的码位解释为字节值，因此如果字符的码位超过 `0xff`，调用 `btoa` 将导致“Character Out Of Range”异常。对于需要编码任意 Unicode 文本的用例，需要首先将字符串转换为其 UTF-8 的组成字节，然后对这些字节进行编码。
```suggestion
由于 `btoa` 将其输入字符串的码位解释为字节值，因此如果字符的码位超过 `0xff`，调用 `btoa` 将导致“Character Out Of Range”异常。对于需要编码任意 Unicode 文本的用例，需要首先将字符串转换为其 {{glossary("UTF-8")}} 的组成字节，然后对这些字节进行编码。
```

2024-05-08 01:37 UTC, jasonren0403 commented on files/zh-cn/glossary/base64/index.md
>  ```
同步一下最新的 See Also 改动

2024-05-08 07:52 UTC, jasonren0403 approved these changes
感谢 @PassionPenguin 👍

2024-05-08 07:52 UTC, merged