Provide Simplified Chinese translation of Web/Security/Weak_Signature_Algorithm
mdn/translated-content pull request #1993
Opened 2021-08-09 10:39 UTC by Zjl37

2021-08-09 14:59 UTC, t7yang requested changes
The markdown format is still investigating, do not use markdown format now.

2021-08-10 23:46 UTC, Zjl37 commented
Okay, now it's in HTML.

2021-08-12 16:45 UTC, t7yang requested changes

2021-08-12 16:45 UTC, t7yang commented on files/zh-cn/web/security/weak_signature_algorithm/index.html
> +<h2 id="相关资料">相关资料</h2>
Should not translate `id`.

2021-08-13 02:36 UTC, Zjl37 commented on files/zh-cn/web/security/weak_signature_algorithm/index.html
> +<h2 id="相关资料">相关资料</h2>
有什么理由吗？我看其他文档都有中文的 id 的。

2021-08-13 03:24 UTC, irvin commented on files/zh-cn/web/security/weak_signature_algorithm/index.html
> +<h2 id="相关资料">相关资料</h2>
那些文章是過去 wiki 系統上遺留下來的部分，github-based 的新系統中統一不翻譯。
保留英文 ID，讓讀者容易切換不同語系的翻譯，變更語系時不會漏失錨點位置。

2021-08-13 09:37 UTC, Zjl37 commented on files/zh-cn/web/security/weak_signature_algorithm/index.html
> +<h2 id="相关资料">相关资料</h2>
好的。一会儿改。

2021-08-15 09:37 UTC, t7yang approved these changes

2021-08-15 09:40 UTC, merged