zh-cn: update link
mdn/translated-content pull request #19941
Opened 2024-05-01 11:10 UTC by PassionPenguin

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-05-01 11:12 UTC, yin1999 requested changes
请严格按照维基的链接来使用（避免重定向）

2024-05-01 11:12 UTC, yin1999 commented on files/zh-cn/glossary/baseline/index.md
> +- 维基百科上的 [基线](https://zh.wikipedia.org/wiki/基线)
```suggestion
- 维基百科上的[基线](https://zh.wikipedia.org/wiki/基線)
```

2024-05-01 11:13 UTC, yin1999 requested changes
不对，目标维基并没有被本地化，你替换的链接不是 <https://en.wikipedia.org/wiki/Baseline> 的

2024-05-02 05:30 UTC, PassionPenguin commented on files/zh-cn/glossary/baseline/index.md
> +- 维基百科上的 [基线](https://zh.wikipedia.org/wiki/基线)
mdn/content#33365

2024-05-02 05:50 UTC, PassionPenguin commented
sync with mdn/content#33365

2024-05-02 06:02 UTC, yin1999 commented
> sync with [mdn/content#33365](https://github.com/mdn/content/pull/33365)

请在上游 PR 合并后再将当前 PR 设置为准备合并状态。

2024-05-02 06:25 UTC, PassionPenguin commented
> > sync with [mdn/content#33365](https://github.com/mdn/content/pull/33365)
> 
> 请在上游 PR 合并后再将当前 PR 设置为准备合并状态。

蛤，已经merge了啊

2024-05-03 03:43 UTC, yin1999 reviewed
参考 [CY/T 154-2017](http://sxqx.alljournal.cn/uploadfile/sxqx/20190304/CY%20T154%E2%80%942017%20%E4%B8%AD%E6%96%87%E5%87%BA%E7%89%88%E7%89%A9%E5%A4%B9%E7%94%A8%E8%8B%B1%E6%96%87%E7%9A%84%E7%BC%96%E8%BE%91%E6%A0%87%E5%87%86.pdf)——《中文出版物夹用英文的编辑规范》。其中的英文标注并未使用大写。说实话，依我个人的感官，把所有的英文单词标注都改成首字母大写并不好看。

![image](https://github.com/mdn/translated-content/assets/15844309/a6f99ce7-804f-4b9a-a657-7a5c6b21c23a)

2024-05-03 03:43 UTC, yin1999 commented on files/zh-cn/glossary/baseline/typography/index.md
> +东亚文字没有基线，所有的文字坐落在一个方框中，既没有升部（Ascender）也没有降部（Descender）。当与有低基线的文字混排时，东亚文字应该坐落在有低基线的文字的基线与降部高度的中间。
```suggestion
东亚文字没有基线，所有字形（glyph）坐落在一个方框中，既没有升部（ascender）也没有降部（descender）。当与有低基线的文字混排时，东亚文字应该坐落在有低基线的文字的基线与降部高度的中间。
```

2024-05-03 04:38 UTC, PassionPenguin commented on files/zh-cn/glossary/baseline/typography/index.md
> +东亚文字没有基线，所有的文字坐落在一个方框中，既没有升部（Ascender）也没有降部（Descender）。当与有低基线的文字混排时，东亚文字应该坐落在有低基线的文字的基线与降部高度的中间。
这确实不是专有名词，嗯

2024-05-03 04:43 UTC, yin1999 approved these changes
Thx

2024-05-03 04:44 UTC, merged