[zh-cn]: update the translation of `**=` operator
mdn/translated-content pull request #19960
Opened 2024-05-02 06:16 UTC by T34-active

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-05-02 12:06 UTC, yin1999 requested changes

2024-05-02 12:06 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/exponentiation_assignment/index.md
> +**幂赋值 (`**=`)** 对两个操作数执行[幂运算](/zh-CN/docs/Web/JavaScript/Reference/Operators/Exponentiation)，并将结果赋给左操作数。
？为什么要修改它

2024-05-02 12:06 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/exponentiation_assignment/index.md
> +`x **= y` 和 `x = x ** y` 是等价的，不同之处在于表达式 `x` 只被计算一次。
```suggestion
`x **= y` 和 `x = x ** y` 是等价的，不同之处在于前者的 `x` 只被计算一次。
```

2024-05-02 14:13 UTC, T34-active commented on files/zh-cn/web/javascript/reference/operators/exponentiation_assignment/index.md
> +**幂赋值 (`**=`)** 对两个操作数执行[幂运算](/zh-CN/docs/Web/JavaScript/Reference/Operators/Exponentiation)，并将结果赋给左操作数。
![image](https://github.com/mdn/translated-content/assets/71604450/d13509b4-1a1f-4b05-898a-0daf41c28b3b)

2024-05-02 14:14 UTC, T34-active commented on files/zh-cn/web/javascript/reference/operators/exponentiation_assignment/index.md
> +**幂赋值 (`**=`)** 对两个操作数执行[幂运算](/zh-CN/docs/Web/JavaScript/Reference/Operators/Exponentiation)，并将结果赋给左操作数。
https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/exponentiation_assignment/index.md?plain=1
原文写的啊

2024-05-02 14:17 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/exponentiation_assignment/index.md
> +**幂赋值 (`**=`)** 对两个操作数执行[幂运算](/zh-CN/docs/Web/JavaScript/Reference/Operators/Exponentiation)，并将结果赋给左操作数。
首先，我们不应该在这里使用半角括号，这一点是我们必须遵从的。我们需要在这个基础上来让这一段话能够在尽可能贴近英文文档样式的情况下渲染。所以我们之前将其修改为了 ``**幂赋值**（**`**=`**）`` 这样的格式。

2024-05-02 14:21 UTC, T34-active commented on files/zh-cn/web/javascript/reference/operators/exponentiation_assignment/index.md
> +**幂赋值 (`**=`)** 对两个操作数执行[幂运算](/zh-CN/docs/Web/JavaScript/Reference/Operators/Exponentiation)，并将结果赋给左操作数。
好吧 是我的问题

2024-05-03 01:06 UTC, T34-active commented on files/zh-cn/web/javascript/reference/operators/exponentiation_assignment/index.md
> +**幂赋值 (`**=`)** 对两个操作数执行[幂运算](/zh-CN/docs/Web/JavaScript/Reference/Operators/Exponentiation)，并将结果赋给左操作数。
```suggestion
**幂赋值**（**`**=`**）对两个操作数执行[幂运算](/zh-CN/docs/Web/JavaScript/Reference/Operators/Exponentiation)，并将结果赋给左操作数。
```

2024-05-03 01:34 UTC, yin1999 approved these changes
感谢

2024-05-03 01:34 UTC, merged