HTTP Auth - Update - Fix typo and minor wording nitpicking
mdn/translated-content pull request #1998
Opened 2021-08-09 15:32 UTC by SphinxKnight

2021-08-13 22:51 UTC, audrasjb requested changes
Nitpicking the nitpicker 😝

2021-08-13 22:51 UTC, audrasjb commented on files/fr/web/http/authentication/index.html
> +<p>Une faille de sécurité potentielle qui a été récemment corrigée par les navigateurs est l'authentification des images multi-origines. À partir de <a href="/fr/docs/Mozilla/Firefox/Releases/59">Fir
"identifiants utilisateurs" > "identifiants", car le terme "utilisateurs" ne me semble pas apporter une quelconque plu-value :)

2021-08-13 22:51 UTC, audrasjb commented on files/fr/web/http/authentication/index.html
> +<p>Le fichier <code>.htaccess</code> fait référence à un fichier <code>.htpasswd</code> dans lequel chaque ligne contient un nom d'utilisateur et un mot de passe séparés par deux-points (« : »). Vous
Nitpicking level 2: il faudrait idéalement déplacer le point final du paragraphe à l'extérieur de la parenthèse (et donc supprimer le point final précédent 😄 )

2021-08-15 09:40 UTC, tristantheb commented on files/fr/web/http/authentication/index.html
> +<p>Une faille de sécurité potentielle qui a été récemment corrigée par les navigateurs est l'authentification des images multi-origines. À partir de <a href="/fr/docs/Mozilla/Firefox/Releases/59">Fir
C'est pourtant bien un terme valide, on parle d'ailleurs en Anglais de *User identifier* et pas uniquement d'*Identifier* ;)

2021-08-15 09:41 UTC, tristantheb approved these changes
Et une PR, une !

2021-08-15 09:41 UTC, merged