zh-CN: glossary - brotli
mdn/translated-content pull request #19981
Opened 2024-05-02 11:52 UTC by PassionPenguin

sync with upstream

2024-05-02 12:46 UTC, yin1999 commented on files/zh-cn/glossary/brotli_compression/index.md
> +- {{glossary("Lossy compression")}}
翻译？

2024-05-04 02:04 UTC, yin1999 commented on files/zh-cn/glossary/brotli_compression/index.md
> +- {{glossary("Lossy compression", "有损翻译")}}
```suggestion
- {{glossary("Lossless compression", "无损压缩")}}
- {{glossary("Lossy compression", "有损压缩")}}
```

2024-05-04 02:07 UTC, PassionPenguin commented on files/zh-cn/glossary/brotli_compression/index.md
> +- {{glossary("Lossy compression", "有损翻译")}}
对不起🧎

2024-05-04 02:08 UTC, yin1999 requested changes
翻译内容的时候也请考虑一下原来的翻译

2024-05-04 02:08 UTC, yin1999 commented on files/zh-cn/glossary/brotli_compression/index.md
> +**Brotli** 是一种通用的无损压缩算法。它结合使用一个现代变体的 [Lempel-Ziv 编码](https://zh.wikipedia.org/wiki/LZ77与LZ78#L277) LZ77 算法、[Huffman 编码](https://rosettacode.org/wiki/Huffman_coding)和二阶上下文建模来压缩数据，提供了与当前最佳通用压缩方法相媲美的压缩比
LZ77 是 Lempel-Ziv 编码的现代变体，你可以参考一下原来的翻译，现在的翻译读着真的怪怪的。Huffman 编码可以翻译为霍夫曼编码或者哈夫曼编码，这个是业界通行的翻译。

2024-05-04 02:08 UTC, yin1999 commented on files/zh-cn/glossary/brotli_compression/index.md
> +Brotli 提供比 {{glossary("GZip_compression", "gzip")}} 更好的压缩率，同时压缩速度相同。但 brotli 解压缩速度比 gzip 慢，因此 gzip 可能更适合于压缩不{{glossary("Cache", "可缓存")}}的内容。
相同这个说法有点太绝对了吧，是原来的翻译不好吗

2024-05-04 02:14 UTC, PassionPenguin commented on files/zh-cn/glossary/brotli_compression/index.md
> +**Brotli** 是一种通用的无损压缩算法。它结合使用一个现代变体的 [Lempel-Ziv 编码](https://zh.wikipedia.org/wiki/LZ77与LZ78#L277) LZ77 算法、[Huffman 编码](https://rosettacode.org/wiki/Huffman_coding)和二阶上下文建模来压缩数据，提供了与当前最佳通用压缩方法相媲美的压缩比
```suggestion
**Brotli** 是一种通用的无损压缩算法。它结合使用一个 LZ77 算法现代变体 [Lempel-Ziv 编码](https://zh.wikipedia.org/wiki/LZ77与LZ78#L277)、[霍夫曼编码](https://rosettacode.org/wiki/Huffman_coding)和二阶上下文建模来压缩数据，提供了与当前最佳通用压缩方法相媲美的压缩比。
```

2024-05-04 02:14 UTC, PassionPenguin commented on files/zh-cn/glossary/brotli_compression/index.md
> +Brotli 提供比 {{glossary("GZip_compression", "gzip")}} 更好的压缩率，同时压缩速度相同。但 brotli 解压缩速度比 gzip 慢，因此 gzip 可能更适合于压缩不{{glossary("Cache", "可缓存")}}的内容。
翻译过头了（

这里的修改，是压缩速率与gzip相比较，deflate是压缩吧

```
Brotli provides better compression ratios than gzip and deflate speeds are comparable.
```

```suggestion
Brotli 提供比 {{glossary("GZip_compression", "gzip")}} 更好的压缩率，也具有一个与 gzip 相当的压缩速率。但 brotli 解压缩速度比 gzip 慢，因此 gzip 可能更适合于压缩不{{glossary("Cache", "可缓存")}}的内容。
```

2024-05-06 06:08 UTC, yin1999 commented on files/zh-cn/glossary/brotli_compression/index.md
> +**Brotli** 是一种通用的无损压缩算法。它结合使用一个 LZ77 算法现代变体 [Lempel-Ziv 编码](https://zh.wikipedia.org/wiki/LZ77与LZ78#L277)、[霍夫曼编码](https://rosettacode.org/wiki/Huffman_coding)和二阶上下文建模来压缩数据，提供了与当前最佳通用压缩方法相媲美的压缩比。
```suggestion
**Brotli** 是一种通用的无损压缩算法。它结合使用 LZ77 算法的一个现代变体（[Lempel-Ziv 编码](https://zh.wikipedia.org/wiki/LZ77与LZ78#L277)）、[霍夫曼编码](https://rosettacode.org/wiki/Huffman_coding)和二阶上下文建模来压缩数据，提供了与当前最佳通用压缩方法相媲美的压缩比。
```

2024-05-06 06:08 UTC, yin1999 commented on files/zh-cn/glossary/brotli_compression/index.md
> +Brotli 提供比 {{glossary("GZip_compression", "gzip")}} 更好的压缩率，也具有一个与 gzip 相当的压缩速率。但 brotli 解压缩速度比 gzip 慢，因此 gzip 可能更适合于压缩不{{glossary("Cache", "可缓存")}}的内容。
这里 deflate 也应该指一种压缩算法，可以说，现代的 gzip 是 deflate 的改进。这里的意思应该是压缩率比 gzip 好，而其速度与 deflate 相当，后面一句是 brotli 压缩（不是解压）

2024-05-06 06:08 UTC, yin1999 commented on files/zh-cn/glossary/brotli_compression/index.md
> +- Caniuse 上的 [Brotli](https://caniuse.com/#feat=brotli)
没必要改

2024-05-06 06:08 UTC, yin1999 commented on files/zh-cn/glossary/brotli_compression/index.md
> +title: Brotli 压缩算法
同参见部分的“无损压缩”、“有损压缩”。

```suggestion
title: Brotli 压缩
```

2024-05-06 06:17 UTC, PassionPenguin commented on files/zh-cn/glossary/brotli_compression/index.md
> +Brotli 提供比 {{glossary("GZip_compression", "gzip")}} 更好的压缩率，也具有一个与 gzip 相当的压缩速率。但 brotli 解压缩速度比 gzip 慢，因此 gzip 可能更适合于压缩不{{glossary("Cache", "可缓存")}}的内容。
后一句确实是commpression压缩，抱歉：）

不过deflate is a compression algo, but…it’s weird

Brotli provides better compression ratios than gzip and deflate speeds are comparable, but brotli compression is a slower process than Gzip compression, so gzip may be a better option for the compression of non-cacheable content.

如果deflate指算法的话……

brotli 比 gzip 和 deflate 的压缩率更高**速度可比**（没有分隔符号的新的句子出现了）

2024-05-06 06:20 UTC, yin1999 commented on files/zh-cn/glossary/brotli_compression/index.md
> +Brotli 提供比 {{glossary("GZip_compression", "gzip")}} 更好的压缩率，也具有一个与 gzip 相当的压缩速率。但 brotli 解压缩速度比 gzip 慢，因此 gzip 可能更适合于压缩不{{glossary("Cache", "可缓存")}}的内容。
> brotli 比 gzip 和 deflate 的压缩率更高速度可比（没有分隔符号的新的句子出现了）

可以

2024-05-06 06:22 UTC, yin1999 commented on files/zh-cn/glossary/brotli_compression/index.md
> +Brotli 提供比 {{glossary("GZip_compression", "gzip")}} 更好的压缩率，也具有一个与 gzip 相当的压缩速率。但 brotli 解压缩速度比 gzip 慢，因此 gzip 可能更适合于压缩不{{glossary("Cache", "可缓存")}}的内容。
deflate 是算法：

![image](https://github.com/mdn/translated-content/assets/15844309/fe838201-7dbf-4e6d-b5ca-60456bcc462d)

2024-05-06 06:23 UTC, PassionPenguin commented on files/zh-cn/glossary/brotli_compression/index.md
> +Brotli 提供比 {{glossary("GZip_compression", "gzip")}} 更好的压缩率，也具有一个与 gzip 相当的压缩速率。但 brotli 解压缩速度比 gzip 慢，因此 gzip 可能更适合于压缩不{{glossary("Cache", "可缓存")}}的内容。
deflate是算法，但是如果这里的deflate是一种算法的话，这个句子就有问题了

2024-05-06 06:35 UTC, yin1999 commented on files/zh-cn/glossary/brotli_compression/index.md
> +Brotli 提供比 {{glossary("GZip_compression", "gzip")}} 更好的压缩率，也具有一个与 gzip 相当的压缩速率。但 brotli 解压缩速度比 gzip 慢，因此 gzip 可能更适合于压缩不{{glossary("Cache", "可缓存")}}的内容。
不，应该是英文语句的语法问题，我之前这么翻译是参考了 [brotli.org](https://www.brotli.org/) 的。里面就提到了这句话：

> It is similar in speed with deflate but offers more dense compression.

2024-05-06 06:38 UTC, yin1999 commented on files/zh-cn/glossary/brotli_compression/index.md
> +Brotli 与大多数现代浏览器兼容，但同时仍需考虑备用方案。
fallback 翻译为回落也没问题。这句可不修改。

![image](https://github.com/mdn/translated-content/assets/15844309/c9348437-1c5f-4e2e-ac88-ba70474b8eeb)

2024-05-06 08:13 UTC, PassionPenguin commented on files/zh-cn/glossary/brotli_compression/index.md
> +Brotli 提供比 {{glossary("GZip_compression", "gzip")}} 更好的压缩率，也具有一个与 gzip 相当的压缩速率。但 brotli 解压缩速度比 gzip 慢，因此 gzip 可能更适合于压缩不{{glossary("Cache", "可缓存")}}的内容。
uh…then should have some updates with the upstream

2024-05-06 08:14 UTC, PassionPenguin commented on files/zh-cn/glossary/brotli_compression/index.md
> +Brotli 提供比 {{glossary("GZip_compression", "gzip")}} 更好的压缩率，压缩速率也与之相当。但 brotli 压缩速度比 gzip 慢，因此 gzip 可能更适合于压缩不{{glossary("Cache", "可缓存")}}的内容。
```suggestion
Brotli 提供比 {{glossary("GZip_compression", "gzip")}} 更好的压缩率，压缩速率也与 deflate 相当。但 brotli 压缩速度比 gzip 慢，因此 gzip 可能更适合于压缩不{{glossary("Cache", "可缓存")}}的内容。
```

2024-05-06 14:29 UTC, yin1999 approved these changes

2024-05-06 14:31 UTC, merged