[zh-cn]: update the translation of JavaScript Expressions and operators
mdn/translated-content pull request #19993
Opened 2024-05-03 03:05 UTC by T34-active

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-05-03 19:02 UTC, skyclouds2001 commented on files/zh-cn/web/javascript/reference/operators/index.md
>    - : 成员运算符提供了对对象的属性或方法的访问（`object.property` 和 `object["property"]`）。
上下对同一个运算符的翻译不统一了

2024-05-06 01:09 UTC, T34-active commented on files/zh-cn/web/javascript/reference/operators/index.md
>    - : 成员运算符提供了对对象的属性或方法的访问（`object.property` 和 `object["property"]`）。
```suggestion
  - : 成员运算符用于访问对象的属性或方法（`object.property` 和 `object["property"]`）。
```

2024-05-08 00:49 UTC, yin1999 requested changes

2024-05-08 00:49 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/index.md
>  该章节说明了 JavaScript 语言所有的运算符，表达式和关键字。
```suggestion
该章节说明了 JavaScript 语言所有的运算符、表达式和关键字。
```

2024-05-08 00:49 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/index.md
>    - : `this` 关键字指向函数的执行上下文。
```suggestion
  - : `this` 关键字指向执行上下文的特殊属性。
```

2024-05-08 00:49 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/index.md
>    - : 分组操作符。
```suggestion
  - : 分组运算符。
```

2024-05-08 00:49 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/index.md
> +  - : 在构造器中，`new.target` 指向 {{jsxref("Operators/new", "new")}} 调用的构造器。
```suggestion
  - : 在构造函数中，`new.target` 指向 {{jsxref("Operators/new", "new")}} 调用的构造函数。
```

2024-05-08 00:49 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/index.md
>    - : `super` 关键字调用父类的构造器。
```suggestion
  - : `super` 关键字调用父类的构造函数或用于访问父类对象的属性。
```

2024-05-08 00:49 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/index.md
>    - : `void` 运算符表示表达式放弃返回值。
```suggestion
  - : `void` 运算符执行表达式并丢弃其返回值。
```

2024-05-08 00:49 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/index.md
>    - : 一元加运算符将操作转换为 Number 类型。
```suggestion
  - : 一元加运算符将操作数转换为 Number 类型。
```

2024-05-08 00:49 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/index.md
>    - : 一元减运算符将操作转换为 Number 类型并取反。
```suggestion
  - : 一元减运算符将操作数转换为 Number 类型并取反。
```

2024-05-08 00:49 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/index.md
> +  - : 暂停或恢复执行异步函数，并等待 promise 的已兑现或已拒绝的回调。
```suggestion
  - : 暂停或恢复执行异步函数，并等待 promise 的兑现或拒绝。
```

2024-05-08 00:49 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/index.md
> +评估相等运算符的结果始终是一个布尔类型，该类型基于比较是否为 true。
```suggestion
相等运算符的求值结果始终是布尔类型（基于比较是否为 true）。
```

2024-05-08 00:49 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/index.md
>    - : 全等运算符。
请考虑下一处的翻译存在的歧义：

```suggestion
  - : 严格相等运算符。
```

2024-05-08 00:49 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/index.md
>    - : 非全等运算符。
```suggestion
  - : 严格不相等运算符。
```

2024-05-08 00:49 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/index.md
>  在二进制的基础上对数字进行移动操作
```suggestion
对操作数的所有二进制位进行移动操作。
```

2024-05-08 00:49 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/index.md
>    - : 位异或（XOR）。
```suggestion
  - : 按位异或（XOR）。
```

2024-05-08 00:49 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/index.md
>    - : 条件元素运算符把两个结果中其中一个符合运算逻辑的值返回。
```suggestion
  - : 条件运算符返回两个值中符合条件逻辑值的那个值。
```

2024-05-08 00:49 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/index.md
>  赋值运算符将右边的操作数的值分配给左边的操作数。
```suggestion
赋值运算符将右边的操作数的值赋给左边的操作数。
```

2024-05-08 00:49 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/index.md
>  - [`[a, b] = arr`, `{ a, b } = obj`](/zh-CN/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)
```suggestion
- [`[a, b] = arr`、`{ a, b } = obj`](/zh-CN/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)
```

2024-05-08 00:49 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/index.md
> +  - : 委派给另外一个生成器函数或可迭代的对象。
```suggestion
  - : 委派给另外一个生成器函数或可迭代对象。
```

2024-05-08 00:49 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/index.md
> +  - : 展开运算符允许在需要多个参数（用于函数调用）或多个元素（用于数组字面量）的地方展开表达式。
```suggestion
  - : 展开语法允许在需要零个或多个参数（对于函数调用）或者元素（对于数组字面量）的地方展开可迭代对象（例如，数组或字符串）。而在对象字面量中，展开语法枚举对象的属性，并将其键值对添加到正在创建的对象中。
```

2024-05-08 00:49 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/index.md
>    - : 逗号操作符允许在一个判断状态中有多个表达式去进行运算并且最后返回最后一个表达式的值。
```suggestion
  - : 逗号操作符允许在单个语句中对多个表达式进行求值，并返回最后一个表达式的结果。
```

2024-05-08 03:00 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/index.md
> +  - : 逗号操作符允许在单个语句中对多个表达式进行求值，并返回最后一个表达式的结果。
```suggestion
  - : 逗号运算符允许在单个语句中对多个表达式进行求值，并返回最后一个表达式的结果。
```

2024-05-08 03:00 UTC, yin1999 approved these changes
:+1:

2024-05-08 03:02 UTC, T34-active commented
很抱歉让你审核了一些错误内容，因为我提交的这个只修复了文档格式，内容没有细看 @yin1999

2024-05-08 03:02 UTC, merged

2024-05-08 03:03 UTC, yin1999 commented
> 很抱歉让你审核了一些错误内容，因为我提交的这个只修复了文档格式，内容没有细看 @yin1999

如果仅仅是修复格式，那么请不要更新 `l10n.sourceCommit`，PR 的内容也应准确说明。