zh-CN: update glossary/crawler
mdn/translated-content pull request #20065
Opened 2024-05-05 12:44 UTC by PassionPenguin

# Description

## Modification

- link removal
- linted word `Web`

2024-05-10 07:43 UTC, JasonLamv-t requested changes

2024-05-10 07:43 UTC, JasonLamv-t commented on files/zh-cn/glossary/crawler/index.md
> +Web 爬虫是一种能有条理并且系统化地浏览 {{glossary("World Wide Web","Web")}} 以收集网页数据的程序（通常也被称作“机器人”）。Web 爬虫最典型的使用案例是搜索引擎（例如谷歌，必应）使用爬虫来创建索引。
```suggestion
**Web 爬虫**是一种能有条理并且系统化地浏览 {{glossary("World Wide Web","Web")}} 以收集网页数据的程序（通常也被称作“机器人”）。Web 爬虫最典型的使用案例是搜索引擎（例如谷歌，必应）使用爬虫来创建索引。
```

2024-05-10 07:43 UTC, JasonLamv-t commented on files/zh-cn/glossary/crawler/index.md
> +- {{Glossary("Search engine")}}
```suggestion
- {{Glossary("Search engine")}}
- 维基百科上的 [Web 爬虫](https://zh.wikipedia.org/wiki/網路爬蟲)
```

2024-05-13 14:02 UTC, yin1999 commented on files/zh-cn/glossary/crawler/index.md
> +  sourceCommit: oops, thx:)
What's this?

2024-05-14 09:44 UTC, JasonLamv-t approved these changes
LGTM. Thx! @PassionPenguin

2024-05-14 09:44 UTC, merged