[ko] translated keyboardEvent.isComposing
mdn/translated-content pull request #20183
Opened 2024-05-09 08:38 UTC by givvemee

### Description

이전에 한국어로 존재하지 않던 문서 [KeyboardEvent/isComposing](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/isComposing ) 를 번역합니다.

### Motivation

### Additional details

### Related issues and pull requests

2024-05-12 16:10 UTC, 1ilsang requested changes
@givvemee 님 안녕하세요. 기여해주셔서 감사합니다! 💯

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

질문이나 도움이 필요하시다면 언제든 멘션 부탁드리겠습니다.

2024-05-12 16:10 UTC, 1ilsang commented on files/ko/web/api/keyboardevent/iscomposing/index.md
> +- {{domxref("Element/compositionstart_event", "compositionstart")}} and {{domxref("Element/compositionend_event", "compositionend")}}
```suggestion
- {{domxref("Element/compositionstart_event", "compositionstart")}} 및 {{domxref("Element/compositionend_event", "compositionend")}}
```

2024-05-12 16:10 UTC, 1ilsang commented on files/ko/web/api/keyboardevent/iscomposing/index.md
> +**`KeyboardEvent.isComposing`** 는 읽기 전용 속성으로 {{domxref("Element/compositionstart_event", "compositionstart")}} 이후나 {{domxref("Element/compositionend_event", "compositionend")}} 이전과 같은 합성 세션 내에서 이벤트가
```suggestion
**`KeyboardEvent.isComposing`**는 읽기 전용 속성으로
{{domxref("Element/compositionstart_event", "compositionstart")}} 이후나 
{{domxref("Element/compositionend_event", "compositionend")}} 이전과 
같은 합성 세션 내에서 이벤트가 발생하는지를 불리언 값으로 나타냅니다.
```

줄 수는 [원본](https://github.com/mdn/content/blob/eab4066e72d5478de920e4020e5db71214dcffa6/files/en-us/web/api/keyboardevent/iscomposing/index.md?plain=1#L11-L14)과 동일하게 해주세요.

관련 논의는 아래에서 확인할 수 있습니다.

- https://github.com/orgs/mdn/discussions/655#discussioncomment-9251708

2024-05-13 01:27 UTC, givvemee commented on files/ko/web/api/keyboardevent/iscomposing/index.md
> +**`KeyboardEvent.isComposing`** 는 읽기 전용 속성으로 {{domxref("Element/compositionstart_event", "compositionstart")}} 이후나 {{domxref("Element/compositionend_event", "compositionend")}} 이전과 같은 합성 세션 내에서 이벤트가
@1ilsang 님 안녕하세요. 확인 후 업데이트 하였습니다. 감사합니다. (디스커션이 있는 줄은 몰랐네요. 😇 알려주셔서 감사합니다.

2024-05-13 01:35 UTC, 1ilsang commented on files/ko/web/api/keyboardevent/iscomposing/index.md
> +**`KeyboardEvent.isComposing`** 는 읽기 전용 속성으로 {{domxref("Element/compositionstart_event", "compositionstart")}} 이후나 {{domxref("Element/compositionend_event", "compositionend")}} 이전과 같은 합성 세션 내에서 이벤트가
@givvemee 님 한줄이 부족해 보이네요^^.. 4줄로 맞춰주실수 있으신가요?

2024-05-13 01:46 UTC, givvemee commented on files/ko/web/api/keyboardevent/iscomposing/index.md
> +**`KeyboardEvent.isComposing`** 는 읽기 전용 속성으로 {{domxref("Element/compositionstart_event", "compositionstart")}} 이후나 {{domxref("Element/compositionend_event", "compositionend")}} 이전과 같은 합성 세션 내에서 이벤트가
헉.

2024-05-13 01:47 UTC, givvemee commented on files/ko/web/api/keyboardevent/iscomposing/index.md
> +**`KeyboardEvent.isComposing`** 는 읽기 전용 속성으로 {{domxref("Element/compositionstart_event", "compositionstart")}} 이후나 {{domxref("Element/compositionend_event", "compositionend")}} 이전과 같은 합성 세션 내에서 이벤트가
@1ilsang 아이고 ... IDE 줄바꿈이 적용된지 모르고 번거롭게 해드렸네요. 수정 완료되었습니다.

2024-05-13 01:51 UTC, givvemee commented
<img width="280" alt="Screenshot 2024-05-13 at 10 50 51 AM" src="https://github.com/mdn/translated-content/assets/89691274/7e9e5ee3-274d-404b-ab8c-74ea67359acc">
@1ilsang 이거 방금 제가 올린 PR 이랑도 연관이 되어 있는데, 이렇게 마크다운 문법이 그대로 노출되는 경우가 있습니다. 이거 ... 어떻게 해결이 가능할까요?

2024-05-13 02:52 UTC, 1ilsang commented
@givvemee 님

```md
**`KeyboardEvent.isComposing`** 는
```

해당 경우는 어쩔 수 없이 띄어쓰기를 넣어주셔야 할 것 같네요.

이 부분은 파싱 과정의 문제이므로 현재 PR이 아닌 이후 따로 수정되어야 할 것 같습니다.

2024-05-13 02:56 UTC, givvemee commented
> @givvemee 님
> 
> ```
> **`KeyboardEvent.isComposing`** 는
> ```
> 
> 해당 경우는 어쩔 수 없이 띄어쓰기를 넣어주셔야 할 것 같네요.
> 
> 이 부분은 파싱 과정의 문제이므로 현재 PR이 아닌 이후 따로 수정되어야 할 것 같습니다.

현재 PR 에서 저 부분에 띄어쓰기를 삽입하면 Lint 에서 잡힐 것으로 예상하시기 때문일까요?

2024-05-13 04:38 UTC, 1ilsang commented
@givvemee 님

네 띄어쓰기 넣으면 볼드가 제대로 적용됩니다.

2024-05-13 05:11 UTC, givvemee commented
> @givvemee 님
> 
> 네 띄어쓰기 넣으면 볼드가 제대로 적용됩니다.

@1ilsang  네. 확인하였습니다. 이슈 사항 없는지 리뷰 승인해 주시면 추가 PR 올려두겠습니다.

2024-05-13 09:23 UTC, 1ilsang approved these changes
LGTM 고생하셨습니다

2024-05-13 09:23 UTC, merged