[zh-cn]: create the translation of Document `adoptedStyleSheets` property
mdn/translated-content pull request #20214
Opened 2024-05-10 07:14 UTC by T34-active

…erty

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-05-10 07:16 UTC, T34-active commented on files/zh-cn/web/api/document/adoptedstylesheets/index.md
> +如果需要修改数组，请使用 in place mutations，例如 `push()`。{{domxref("CSSStyleSheet")}} 实例本身也可以被修改，并且这些修改将应用在采用该样式表的任何地方。
```
如果需要修改数组，请使用 in place mutations，例如 `push()`。{{domxref("CSSStyleSheet")}} 实例本身也可以被修改，并且这些修改将应用在采用该样式表的任何地方。
```
in place mutations 这个我不知道怎么翻译 @JasonLamv-t

2024-05-10 07:21 UTC, T34-active commented on files/zh-cn/web/api/document/adoptedstylesheets/index.md
> +该属性中的样式表将与文档的其他样式表一起根据 [CSS 层叠](/zh-CN/docs/Web/CSS/Cascade) 进行求值。在规则解析顺序考虑样式表顺序的情况下，假设 `adoptedStyleSheets` 排列在 [`Document.styleSheets`](/zh-CN/docs/Web/API/Document/styleSheets) 中那些样式表之后。
```suggestion
该属性中的样式表将与文档的其他样式表一起根据 [CSS 层叠](/zh-CN/docs/Web/CSS/Cascade)进行求值。在规则解析顺序考虑样式表顺序的情况下，假设 `adoptedStyleSheets` 排列在 [`Document.styleSheets`](/zh-CN/docs/Web/API/Document/styleSheets) 中那些样式表之后。
```

2024-05-10 07:22 UTC, T34-active commented on files/zh-cn/web/api/document/adoptedstylesheets/index.md
> +> **备注：** 构建样式表是指使用 [`CSSStyleSheet()` 构造函数](/zh-CN/docs/Web/API/CSSStyleSheet/CSSStyleSheet)以编程方式创建的样式表（与用户代理在从脚本导入样式表时创建的相比，用户代理使用 {{HTMLElement('style')}} 和 {{CSSXref('@import')}} 进行导入，或通过 {{HTMLE
```suggestion
> **备注：** 构建样式表是指使用 [`CSSStyleSheet()` 构造函数](/zh-CN/docs/Web/API/CSSStyleSheet/CSSStyleSheet)以编程方式创建的样式表（与用户代理在从脚本导入样式表时创建的相比，用户代理使用 {{HTMLElement('style')}} 和 {{CSSXref('@import')}} 进行导入，或通过 {{HTMLElement('link')}}）进行链接。
```

2024-05-10 18:55 UTC, skyclouds2001 commented on files/zh-cn/web/api/document/adoptedstylesheets/index.md
> +只有在当前 {{domxref("Document")}} 上下文中使用 [`CSSStyleSheet()` 构造函数](/zh-CN/docs/Web/API/CSSStyleSheet/CSSStyleSheet) 创建的样式表才可以被采用。
```suggestion
只有在当前 {{domxref("Document")}} 上下文中使用 [`CSSStyleSheet()` 构造函数](/zh-CN/docs/Web/API/CSSStyleSheet/CSSStyleSheet)创建的样式表才可以被采用。
```

2024-05-10 18:55 UTC, skyclouds2001 commented on files/zh-cn/web/api/document/adoptedstylesheets/index.md
> +如果需要修改数组，请使用 in place mutations，例如 `push()`。{{domxref("CSSStyleSheet")}} 实例本身也可以被修改，并且这些修改将应用在采用该样式表的任何地方。
意思上来说应该是指直接修改数组本身而非通过创建应该新的数组返回的方法，比如说翻译为“原地修改（的方法）”

2024-05-12 17:46 UTC, JasonLamv-t requested changes
Is not any forbidden here of the using of AI/translate tools such as GPTs, but you need to keep in mind that you have to double check the results given by these tools. Here are some suggetions for you, thank you! :heart:

2024-05-12 17:46 UTC, JasonLamv-t commented on files/zh-cn/web/api/document/adoptedstylesheets/index.md
> +相同的构造样式表也可以通过使用 [`ShadowRoot.adoptedStyleSheets`](/zh-CN/docs/Web/API/ShadowRoot/adoptedStyleSheets) 属性与一个或多个 {{domxref("ShadowRoot")}} 实例共享。更改采用样式表会影响采用该样式表的所有对象。
```suggestion
相同的构造样式表也可以通过使用 [`ShadowRoot.adoptedStyleSheets`](/zh-CN/docs/Web/API/ShadowRoot/adoptedStyleSheets) 属性与一个或多个 {{domxref("ShadowRoot")}} 实例共享。更改已采用的样式表会影响采用该样式表的所有对象。
```

2024-05-12 17:46 UTC, JasonLamv-t commented on files/zh-cn/web/api/document/adoptedstylesheets/index.md
> +该属性中的样式表将与文档的其他样式表一起根据 [CSS 层叠](/zh-CN/docs/Web/CSS/Cascade)进行求值。在规则解析顺序考虑样式表顺序的情况下，假设 `adoptedStyleSheets` 排列在 [`Document.styleSheets`](/zh-CN/docs/Web/API/Document/styleSheets) 中那些样式表之后。
```suggestion
该属性中的样式表将与文档的其他样式表一起根据 [CSS 层叠算法](/zh-CN/docs/Web/CSS/Cascade)进行求值。在规则解析考虑样式表的顺序时，`adoptedStyleSheets` 被假定排列在 [`Document.styleSheets`](/zh-CN/docs/Web/API/Document/styleSheets) 中那些样式表之后。
```

2024-05-12 17:46 UTC, JasonLamv-t commented on files/zh-cn/web/api/document/adoptedstylesheets/index.md
> +如果需要修改数组，请使用 in place mutations，例如 `push()`。{{domxref("CSSStyleSheet")}} 实例本身也可以被修改，并且这些修改将应用在采用该样式表的任何地方。
@skyclouds2001 给出的解释是正确，`in-place` 在这里表示“原地”或者是“就地”的意思，常见的词有：[原地算法](https://en.wikipedia.org/wiki/In-place_algorithm)，Array 相关的文档中有这个概念。
```suggestion
如果需要修改数组，可以使用像 `push()` 这样的原地修改方法。{{domxref("CSSStyleSheet")}} 实例本身也可以被修改，且这些修改将应用在采用该样式表的任何地方。
```

2024-05-12 17:46 UTC, JasonLamv-t commented on files/zh-cn/web/api/document/adoptedstylesheets/index.md
> +```
```suggestion
```js
// 创建一个空的“构造的”样式表
const sheet = new CSSStyleSheet();
// 应用一条规则到样式表
sheet.replaceSync("a { color: red; }");

// 将样式表应用到文档中
document.adoptedStyleSheets = [sheet];
```

我们可以使用 {{domxref("CSSStyleSheet.insertRule()")}} 将新规则添加到样式表中。

```js
sheet.insertRule("* { background-color: blue; }");
// 现在文档将显示蓝色背景。
```
```

2024-05-12 17:46 UTC, JasonLamv-t commented on files/zh-cn/web/api/document/adoptedstylesheets/index.md
> +// 合并现有工作表和新的工作表
```suggestion
// 合并现有样式表和新的样式表
```

2024-05-12 17:46 UTC, JasonLamv-t commented on files/zh-cn/web/api/document/adoptedstylesheets/index.md
> +我们可以用类似的方法将样式表共享到影子根目录中。
```suggestion
我们可以用类似的方法将样式表共享到影子根中。
```

2024-05-12 17:46 UTC, JasonLamv-t commented on files/zh-cn/web/api/document/adoptedstylesheets/index.md
> +// 在文档中创建元素，然后创建影子根目录：
```suggestion
// 在文档中创建元素，然后创建影子根：
```

2024-05-12 17:46 UTC, JasonLamv-t commented on files/zh-cn/web/api/document/adoptedstylesheets/index.md
> +// 将同一工作表采用到影子 DOM 中
```suggestion
// 在影子 DOM 中采用同一个样式表
```

2024-05-13 02:12 UTC, JasonLamv-t approved these changes
LGTM. Thank you! @T34-active :+1:

2024-05-13 02:12 UTC, merged