zh-cn: sync html `<br>` element
mdn/translated-content pull request #20296
Opened 2024-05-12 10:43 UTC by xyy94813

### Description

Sync with newly orign docs

### Motivation

learning and translating

### Additional details

None.

### Related issues and pull requests

None.

2024-05-12 12:45 UTC, xyy94813 commented
HTML 标签的技术概要是否存在对应的宏？？

2024-05-12 16:30 UTC, skyclouds2001 commented on files/zh-cn/web/html/element/br/index.md
> +`<br>` 元素包含唯一且明确的语义 —— 在文本块中创建换行符。因此，它没有自己的尺寸或视觉输出，几乎无法设计它的样式。
```suggestion
`<br>` 元素包含唯一且明确的语义——在文本块中创建换行符。因此，它没有自己的尺寸或视觉输出，几乎无法设计它的样式。
```

2024-05-12 16:30 UTC, skyclouds2001 commented on files/zh-cn/web/html/element/br/index.md
> +- {{HTMLElement("wbr")}} element
```suggestion
- {{HTMLElement("wbr")}} 元素
```

上同

2024-05-12 16:30 UTC, skyclouds2001 commented on files/zh-cn/web/html/element/br/index.md
> +## 技术概要
表格也应该翻译一下

2024-05-13 03:03 UTC, xyy94813 reviewed
翻译技术概要表格和参见

2024-05-13 03:03 UTC, xyy94813 commented on files/zh-cn/web/html/element/br/index.md
> +    </tr>
```suggestion
  <tr>
      <th scope="row">隐含的 ARIA 角色</th>
      <td>
        <a href="https://www.w3.org/TR/html-aria/#dfn-no-corresponding-role"
          >没有对应的角色</a
        >
      </td>
    </tr>
```

2024-05-13 03:03 UTC, xyy94813 commented on files/zh-cn/web/html/element/br/index.md
>     <th scope="row">Permitted ARIA roles</th>
```suggestion
   <th scope="row">允许的 ARIA 角色</th>
```

2024-05-13 03:05 UTC, xyy94813 commented on files/zh-cn/web/html/element/br/index.md
> +## 技术概要
表格有没有最佳实践的示例？翻了 n 个文档书写方式千奇百怪的。

2024-05-13 04:05 UTC, yin1999 requested changes

2024-05-13 04:05 UTC, yin1999 commented on files/zh-cn/web/html/element/br/index.md
> +你可以给 `<br>` 元素设置 {{cssxref("margin")}} 从而增加文本行之间的间距，但这是一种糟糕的做法 —— 你应该使用为此目的而设计的 {{cssxref("line-height")}}。
```suggestion
你可以给 `<br>` 元素设置 {{cssxref("margin")}} 从而增加文本行之间的间距，但这是一种糟糕的做法——你应该使用为此目的而设计的 {{cssxref("line-height")}}。
```

2024-05-13 04:05 UTC, yin1999 commented on files/zh-cn/web/html/element/br/index.md
> +### 一般使用
```suggestion
### 简单的 br 示例
```

2024-05-13 04:05 UTC, yin1999 commented on files/zh-cn/web/html/element/br/index.md
> +{{ EmbedLiveSample('Simple_br', 640, 120) }}
```suggestion
{{ EmbedLiveSample('简单的 br 示例', 640, 120) }}
```

2024-05-13 04:05 UTC, yin1999 commented on files/zh-cn/web/html/element/br/index.md
> +
缺“无障碍考虑”

2024-05-13 04:05 UTC, yin1999 commented on files/zh-cn/web/html/element/br/index.md
> +   <td><a href="/zh-CN/docs/HTML/Content_categories#Flow_content">流式内容</a>，<a href="/zh-CN/docs/HTML/Content_categories#Phrasing_content">短语内容</a>。</td>
```suggestion
   <td><a href="/zh-CN/docs/Web/HTML/Content_categories#流式内容">流式内容</a>、<a href="/zh-CN/docs/Web/HTML/Content_categories#短语内容">短语内容</a>。</td>
```

2024-05-13 04:05 UTC, yin1999 commented on files/zh-cn/web/html/element/br/index.md
> +   <td>任意可容纳<a href="/zh-CN/docs/HTML/Content_categories#Phrasing_content">短语内容</a>的元素。</td>
```suggestion
   <td>任意可容纳<a href="/zh-CN/docs/Web/HTML/Content_categories#短语内容">短语内容</a>的元素。</td>
```

2024-05-13 04:05 UTC, yin1999 commented on files/zh-cn/web/html/element/br/index.md
>     <td>任意</td>
```suggestion
   <td>
     <a href="/zh-CN/docs/Web/Accessibility/ARIA/Roles/none_role"><code>none</code></a>、<a href="/zh-CN/docs/Web/Accessibility/ARIA/Roles/presentation_role"><code>presentation</code></a>
   </td>
```

2024-05-13 04:08 UTC, yin1999 commented on files/zh-cn/web/html/element/br/index.md
> +## 技术概要
HTML 表格的书写风格并不统一，这个和贡献者的习惯有关。关于何时使用 markdown 表格，请参阅[如何使用 Markdown 来撰写文档](https://developer.mozilla.org/zh-CN/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN#%E8%A1%A8%E6%A0%BC)。

2024-05-13 11:21 UTC, xyy94813 commented on files/zh-cn/web/html/element/br/index.md
> +
"无障碍" 相关内容原文只有 Table 中有提及

2024-05-13 11:24 UTC, yin1999 commented on files/zh-cn/web/html/element/br/index.md
> +
？这一段去哪里了，不是缺了一段吗：https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br#accessibility_concerns

2024-05-13 12:00 UTC, xyy94813 commented on files/zh-cn/web/html/element/br/index.md
> +
抱歉。已补充。

2024-05-13 12:15 UTC, yin1999 commented on files/zh-cn/web/html/element/br/index.md
> +请使用 `<p>` 元素，并使用 CSS 属性 {{cssxref("margin")}} 控制他们的间距。
```suggestion
请使用 `<p>` 元素，并使用 CSS 属性 {{cssxref("margin")}} 控制它们的间距。
```

2024-05-13 12:16 UTC, yin1999 approved these changes
Thanks

2024-05-13 12:18 UTC, merged