Corrections de coquilles
mdn/translated-content pull request #2034
Opened 2021-08-12 06:58 UTC by tetsuhaut

2021-08-13 22:42 UTC, audrasjb requested changes
Small change requested :)

Thanks for the PR BTW!

2021-08-13 22:42 UTC, audrasjb commented on files/fr/learn/css/building_blocks/the_box_model/index.html
> + <li><strong>La boîte de margin (marge extérieure)</strong> : Le margin est la couche la plus à l'extérieur, englobant le contenu, le padding et le border. Comme le padding, il s'agit d'une zone vier
Ce serait pas mal d'ajouter au passage des `&nbsp;` sur chacun des éléments de la liste, si possible :)

2021-08-14 16:24 UTC, tetsuhaut commented on files/fr/learn/css/building_blocks/the_box_model/index.html
> + <li><strong>La boîte de margin (marge extérieure)</strong> : Le margin est la couche la plus à l'extérieur, englobant le contenu, le padding et le border. Comme le padding, il s'agit d'une zone vier
ok mais où ? qqch comme ça ?
~~~
<li><strong>La boîte de padding</strong> <strong>(marge intérieure)&nbsp;</strong>:
~~~

2021-08-15 06:21 UTC, audrasjb commented on files/fr/learn/css/building_blocks/the_box_model/index.html
> + <li><strong>La boîte de margin (marge extérieure)</strong> : Le margin est la couche la plus à l'extérieur, englobant le contenu, le padding et le border. Comme le padding, il s'agit d'une zone vier
ouaip

2021-08-15 19:59 UTC, tetsuhaut commented on files/fr/learn/css/building_blocks/the_box_model/index.html
> + <li><strong>La boîte de margin (marge extérieure)</strong> : Le margin est la couche la plus à l'extérieur, englobant le contenu, le padding et le border. Comme le padding, il s'agit d'une zone vier
fait

2021-08-15 22:22 UTC, audrasjb commented on files/fr/learn/css/building_blocks/the_box_model/index.html
> + <li><strong>La boîte de margin (marge extérieure)</strong> : Le margin est la couche la plus à l'extérieur, englobant le contenu, le padding et le border. Comme le padding, il s'agit d'une zone vier
👍

2021-08-15 22:24 UTC, audrasjb approved these changes
Sounds good to me

2021-08-19 20:19 UTC, SphinxKnight commented
Il restait différentes coquilles, j'en ai profité pour "lifter" la page.

2021-08-19 20:20 UTC, merged