corrections coquilles
mdn/translated-content pull request #2037
Opened 2021-08-12 10:42 UTC by tetsuhaut

2021-08-13 22:39 UTC, audrasjb approved these changes
Sounds good to me 👍

2021-08-15 08:07 UTC, tristantheb requested changes
Translation added on my to-do, part of this page isn't l10n-fr

2021-09-02 06:11 UTC, SphinxKnight commented
@tristantheb, I've pushed a commit to finish the translation, I leave the review to you :)

2021-09-12 15:50 UTC, tristantheb approved these changes

2021-09-12 15:50 UTC, merged