correction coquille mineure
mdn/translated-content pull request #2039
Opened 2021-08-12 12:41 UTC by tetsuhaut

2021-08-13 22:38 UTC, audrasjb requested changes
Thanks for the PR. I requested a small change :)

2021-08-13 22:38 UTC, audrasjb commented on files/fr/learn/css/building_blocks/overflowing_content/index.html
> +<p>Dans les deux prochaines leçons, nous examinerons différentes façons de contrôler la taille des éléments afin de limiter l'overflow. Cependant, si vous avez besoin d'une taille fixe, vous pouvez é
il faudrait en outre utiliser une espace insécable (entité HTML `&nbsp;`) pour éviter que le caractère de ponctuation passe à la ligne sur les petits écrans.

2021-08-14 16:28 UTC, tetsuhaut commented on files/fr/learn/css/building_blocks/overflowing_content/index.html
> +<p>Dans les deux prochaines leçons, nous examinerons différentes façons de contrôler la taille des éléments afin de limiter l'overflow. Cependant, si vous avez besoin d'une taille fixe, vous pouvez é
fait

2021-08-15 09:32 UTC, tristantheb requested changes
[Bottom of page] En to Fr needed, see this change : https://github.com/mdn/translated-content/pull/2048/files#diff-7046299b122d35c664176e5dc4f07630058e9add37a9462353736e85188375bbR116-R136

2021-09-02 06:26 UTC, SphinxKnight commented
@tristantheb, this should be ok by now. Let me know.

2021-09-12 15:47 UTC, tristantheb approved these changes

2021-09-12 15:48 UTC, merged