[zh-cn]: update the translation of Document Object Model
mdn/translated-content pull request #20400
Opened 2024-05-15 03:53 UTC by T34-active

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-05-15 06:16 UTC, PassionPenguin commented on files/zh-cn/web/api/document_object_model/index.md
> +**文档对象模型（DOM）** 通过将文档的结构（例如表示网页的 HTML）以对象的形式存储在内存中，将网页与脚本或编程语言连接起来。尽管将 HTML、SVG 或 XML 文档建模为对象并不是 JavaScript 核心语言的一部分，但它通常是指 JavaScript。
/cc @yin1999 ptal:)

（这里两种释义似乎都说得过去：

1. 我们经常说的 DOM 都指的是 JavaScript 里面的那个（我会pick这一个）

```suggestion
**文档对象模型（DOM）** 通过将文档的结构（例如表示网页的 HTML）以对象的形式存储在内存中，将网页与脚本或编程语言连接起来。尽管将 HTML、SVG 或 XML 文档建模为对象并不是 JavaScript 核心语言的一部分，但它也通常指代 JavaScript 中的文档对象模型。
```

2. 我们经常说的 DOM 与 JavaScript 相关

```suggestion
**文档对象模型（DOM）** 通过将文档的结构（例如表示网页的 HTML）以对象的形式存储在内存中，将网页与脚本或编程语言连接起来。尽管将 HTML、SVG 或 XML 文档建模为对象并不是 JavaScript 核心语言的一部分，但它通常与 JavaScript 相关。
```

2024-05-15 06:25 UTC, PassionPenguin requested changes
improvements :)

2024-05-15 06:25 UTC, PassionPenguin commented on files/zh-cn/web/api/document_object_model/index.md
> +文档对象模型已被高度简化。为了实现这一目标，已在不同 DOM 第 3 级或更早规范中移除了以下接口。它们不再对 Web 开发者可用。
不同修饰的应该是spec叭，这样可能会更符合中文习惯

```suggestion
文档对象模型已被高度简化。为了实现这一目标，已在 DOM 3 级或更早的各种规范中移除了以下接口。它们不再对 Web 开发者可用。
```

2024-05-15 06:25 UTC, PassionPenguin commented on files/zh-cn/web/api/document_object_model/index.md
> +特别是 {{domxref("Element")}} 接口被增强为 {{domxref("SVGElement")}} 和各种子类，每个子类代表一个（或一系列密切相关的）元素。这些接口将在 [SVG API](/zh-CN/docs/Web/API/SVG_API) 文档中进一步讨论。
这个与上一个应该是一行的

```markdown
Similarly, a document containing SVG is also described using the {{DOMxRef("Document")}} interface, which is extended by the SVG specification to include various SVG-specific features. In particular, the {{domxref("Element")}} interface is enhanced to become {{domxref("SVGElement")}} and various subclasses, each representing an element or a family of closely related elements. These interfaces are discussed further in the [SVG API](https://github.com/mdn/content/blob/main/en-US/docs/Web/API/SVG_API) documentation.
```

特别地=>尤其是 Element 被拓展为 SVGElement 以及很多不同的子类……

2024-05-15 06:25 UTC, PassionPenguin commented on files/zh-cn/web/api/document_object_model/index.md
> +包含 HTML 的文档通过 {{DOMxRef("Document")}} 接口进行描述，接口由 HTML 规范扩展，包含了各种 HTML 特有的特性。特别是 {{domxref("Element")}} 接口被增强为 {{domxref("HTMLElement")}} 和各种子类，每个子类代表一个（或一系列密切相关的）元素。
```suggestion
包含 HTML 的文档通过由 HTML 规范扩展，包含了各种 HTML 特有的特性的 {{DOMxRef("Document")}} 接口进行描述。特别是 {{domxref("Element")}} 接口被增强为 {{domxref("HTMLElement")}} 和各种子类，每个子类代表一个（或一系列密切相关的）元素。
```

2024-05-15 06:31 UTC, PassionPenguin commented on files/zh-cn/web/api/document_object_model/index.md
> +包含 HTML 的文档通过 {{DOMxRef("Document")}} 接口进行描述，接口由 HTML 规范扩展，包含了各种 HTML 特有的特性。特别是 {{domxref("Element")}} 接口被增强为 {{domxref("HTMLElement")}} 和各种子类，每个子类代表一个（或一系列密切相关的）元素。
not a necessary one, but…中文很少会有英语从句这样的修饰，个人感觉最好加上一个关系（`我喜欢他，因为他很帅`、`文档通过接口进行描述，而接口又由规范拓展`、……）



```suggestion
包含 HTML 的文档通过 {{DOMxRef("Document")}} 接口进行描述，HTML 规范扩展了这个接口，包含了各种 HTML 特有的特性。特别是 {{domxref("Element")}} 接口被增强为 {{domxref("HTMLElement")}} 和各种子类，每个子类代表一个（或一系列密切相关的）元素。
```

2024-05-15 06:37 UTC, yin1999 commented on files/zh-cn/web/api/document_object_model/index.md
> +**文档对象模型（DOM）** 通过将文档的结构（例如表示网页的 HTML）以对象的形式存储在内存中，将网页与脚本或编程语言连接起来。尽管将 HTML、SVG 或 XML 文档建模为对象并不是 JavaScript 核心语言的一部分，但它通常是指 JavaScript。
我倾向于第二种。同时再强调一下，中文之间不要有空格（我修改了一下 @PassionPenguin 的建议）。

2024-05-15 06:49 UTC, PassionPenguin commented on files/zh-cn/web/api/document_object_model/index.md
> +**文档对象模型（DOM）** 通过将文档的结构（例如表示网页的 HTML）以对象的形式存储在内存中，将网页与脚本或编程语言连接起来。尽管将 HTML、SVG 或 XML 文档建模为对象并不是 JavaScript 核心语言的一部分，但它通常是指 JavaScript。
oops, thx:)

iOS 喜欢在复制黏贴前后加空格，喜欢在剪切后删空格）

2024-05-15 07:05 UTC, T34-active reviewed
fix content

2024-05-15 07:05 UTC, T34-active commented on files/zh-cn/web/api/document_object_model/index.md
> +包含 HTML 的文档通过 {{DOMxRef("Document")}} 接口进行描述，HTML 规范扩展了这个接口，包含了各种 HTML 特有的特性。特别是 {{domxref("Element")}} 接口被增强为 {{domxref("HTMLElement")}} 和各种子类，每个子类代表一个（或一系列密切相关的）元素。
```suggestion
包含 HTML 的文档通过 {{DOMxRef("Document")}} 接口进行描述，HTML 规范扩展了这个接口，包含了各种 HTML 特有的特性。尤其是 {{domxref("Element")}} 接口被拓展为 {{domxref("HTMLElement")}} 以及很多不同的子类，每个子类代表一个（或一系列密切相关的）元素。
```

2024-05-15 07:05 UTC, T34-active commented on files/zh-cn/web/api/document_object_model/index.md
> +同样，包含 SVG 的文档也通过 {{DOMxRef("Document")}} 接口来描述，接口由 SVG 规范扩展，包含了各种 SVG 特有的特性。特别是 {{domxref("Element")}} 接口被增强为 {{domxref("SVGElement")}} 和各种子类，每个子类代表一个（或一系列密切相关的）元素。这些接口将在 [SVG API](/zh-CN/docs/Web/AP
```suggestion
同样，包含 SVG 的文档也通过 {{DOMxRef("Document")}} 接口来描述，接口由 SVG 规范扩展，包含了各种 SVG 特有的特性。尤其是 {{domxref("Element")}} 接口被拓展为 {{domxref("SVGElement")}} 以及很多不同的子类，每个子类代表一个（或一系列密切相关的）元素。这些接口将在 [SVG API](/zh-CN/docs/Web/API/SVG_API) 文档中进一步讨论。
```

2024-05-15 07:07 UTC, PassionPenguin approved these changes
:)

2024-05-18 04:53 UTC, yin1999 commented on files/zh-cn/web/api/document_object_model/index.md
> +文档对象模型已被高度简化。为了实现这一目标，已在不同 DOM 第 3 级或更早规范中移除了以下接口。它们不再对 Web 开发者可用。
DOM 第三版

2024-05-18 05:20 UTC, PassionPenguin commented on files/zh-cn/web/api/document_object_model/index.md
> +文档对象模型已被高度简化。为了实现这一目标，已在不同 DOM 第 3 级或更早规范中移除了以下接口。它们不再对 Web 开发者可用。
@T34-active 你可能需要自己去patch这个outdated suggestion

2024-05-19 02:52 UTC, T34-active commented on files/zh-cn/web/api/document_object_model/index.md
> +文档对象模型已被高度简化。为了实现这一目标，已在 DOM 3 级或更早的各种规范中移除了以下接口。它们不再对 Web 开发者可用。
```suggestion
文档对象模型已被高度简化。为了实现这一目标，已在 DOM 第三版或更早的各种规范中移除了以下接口。它们不再对 Web 开发者可用。
```

2024-05-19 12:13 UTC, yin1999 approved these changes
:+1:

2024-05-19 12:13 UTC, merged