corrections de qques coquilles
mdn/translated-content pull request #2041
Opened 2021-08-12 14:08 UTC by tetsuhaut

certains caractères de ponctuation comme '!', '?' et ':' doivent toujours être précédés d'un espace en français, et jamais en anglais.

2021-08-13 22:37 UTC, audrasjb requested changes
Thanks for the pull request!
By the way, we should rather use the non-breaking space HTML entity.
Could you please edit the file accordingly?

Thanks!
Jb

2021-08-13 22:37 UTC, audrasjb commented on files/fr/learn/css/building_blocks/values_and_units/index.html
> +   <th scope="row">Prérequis :</th>
il faudrait en outre utiliser une espace insécable (entité HTML `&nbsp;`) pour éviter que le caractère de ponctuation passe à la ligne sur les petits écrans.

2021-08-13 22:37 UTC, audrasjb commented on files/fr/learn/css/building_blocks/values_and_units/index.html
> +   <th scope="row">Objectif :</th>
il faudrait en outre utiliser une espace insécable (entité HTML `&nbsp;`) pour éviter que le caractère de ponctuation passe à la ligne sur les petits écrans.

2021-08-13 22:37 UTC, audrasjb commented on files/fr/learn/css/building_blocks/values_and_units/index.html
> +<p><strong>Note</strong> : Vous verrez également des valeurs CSS appelées <em>types de données</em>. Les termes sont interchangeables — Quand vous voyez quelque chose en CSS identifié comme type de d
il faudrait en outre utiliser une espace insécable (entité HTML `&nbsp;`) pour éviter que le caractère de ponctuation passe à la ligne sur les petits écrans.

2021-08-13 22:37 UTC, audrasjb commented on files/fr/learn/css/building_blocks/values_and_units/index.html
> +<p>Dans l'exemple suivant, nous avons défini la couleur de notre titre en utilisant un mot-clé, et la couleur de fond en utilisant la fonction <code>rgb()</code> :</p>
il faudrait en outre utiliser une espace insécable (entité HTML `&nbsp;`) pour éviter que le caractère de ponctuation passe à la ligne sur les petits écrans.

2021-08-13 22:37 UTC, audrasjb commented on files/fr/learn/css/building_blocks/values_and_units/index.html
> +<p>Il existe de nombreux types de valeurs numériques que vous pourrez trouver vous-même en utilisant CSS. Les types de valeurs suivants sont tous classés comme numériques :</p>
il faudrait en outre utiliser une espace insécable (entité HTML `&nbsp;`) pour éviter que le caractère de ponctuation passe à la ligne sur les petits écrans.

2021-08-14 16:37 UTC, tetsuhaut commented on files/fr/learn/css/building_blocks/values_and_units/index.html
> +   <th scope="row">Prérequis :</th>
fait

2021-08-14 16:37 UTC, tetsuhaut commented on files/fr/learn/css/building_blocks/values_and_units/index.html
> +   <th scope="row">Objectif :</th>
fait

2021-08-14 16:37 UTC, tetsuhaut commented on files/fr/learn/css/building_blocks/values_and_units/index.html
> +<p><strong>Note</strong> : Vous verrez également des valeurs CSS appelées <em>types de données</em>. Les termes sont interchangeables — Quand vous voyez quelque chose en CSS identifié comme type de d
fait

2021-08-14 16:37 UTC, tetsuhaut commented on files/fr/learn/css/building_blocks/values_and_units/index.html
> +<p>Dans l'exemple suivant, nous avons défini la couleur de notre titre en utilisant un mot-clé, et la couleur de fond en utilisant la fonction <code>rgb()</code> :</p>
fait

2021-08-14 16:37 UTC, tetsuhaut commented on files/fr/learn/css/building_blocks/values_and_units/index.html
> +<p>Il existe de nombreux types de valeurs numériques que vous pourrez trouver vous-même en utilisant CSS. Les types de valeurs suivants sont tous classés comme numériques :</p>
fait

2021-08-15 06:29 UTC, audrasjb approved these changes
Looks good to me!

2021-08-15 09:28 UTC, tristantheb requested changes
Document in english, waiting for complete translation before sending to prod.

2021-09-12 15:43 UTC, tristantheb approved these changes

2021-09-12 15:44 UTC, merged