feat: fallback 번역
mdn/translated-content pull request #20447
Opened 2024-05-17 04:30 UTC by givvemee

### Description

기존에 한국어로 존재하지 않던 문서 [CSSCounterStyleRule: fallback property](https://developer.mozilla.org/en-US/docs/Web/API/CSSCounterStyleRule/fallback) 를 번역합니다. 

### Motivation

### Additional details

### Related issues and pull requests

2024-06-11 01:26 UTC, jho2301 requested changes

2024-06-11 01:26 UTC, jho2301 commented on files/ko/web/api/csscounterstylerule/fallback/index.md
> +{{domxref("CSSCounterStyleRule")}} 인터페이스의 **`fallback`** 속성은 {{cssxref("@counter-style/fallback","fallback")}} 설명자의 값을 호출하거나 지정합니다. 만일 설명자에 지정된 값이 없다면, 이 속성은 빈 문자열을 반환합니다.
"설명자의 값을 호출하거나 지정합니다"보다는 "설명자의 값을 가져오거나 설정합니다"가 더 자연스럽게 보입니다

2024-06-11 01:56 UTC, givvemee commented on files/ko/web/api/csscounterstylerule/fallback/index.md
> +{{domxref("CSSCounterStyleRule")}} 인터페이스의 **`fallback`** 속성은 {{cssxref("@counter-style/fallback","fallback")}} 설명자의 값을 호출하거나 지정합니다. 만일 설명자에 지정된 값이 없다면, 이 속성은 빈 문자열을 반환합니다.
@jho2301 리뷰 감사합니다. 수정 완료되었어요.

2024-06-14 09:15 UTC, jho2301 approved these changes
반영 감사합니다 고생하셨습니다

2024-06-14 09:15 UTC, merged