csscounterstyle-pad 번역
mdn/translated-content pull request #20454
Opened 2024-05-17 04:52 UTC by givvemee

### Description

기존에 한국어로 존재하지 않던 문서 [CSSCounterStyleRule: pad property](https://developer.mozilla.org/en-US/docs/Web/API/CSSCounterStyleRule/pad) 를 번역합니다. 

### Motivation

### Additional details

### Related issues and pull requests

2024-05-18 14:09 UTC, 1ilsang requested changes
@givvemee 님 안녕하세요. 기여해주셔서 감사합니다! 💯

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

질문이나 도움이 필요하시다면 언제든 멘션 부탁드리겠습니다.

2024-05-18 14:09 UTC, 1ilsang commented on files/ko/web/api/csscounterstylerule/pad/index.md
> +{{domxref("CSSCounterStyleRule")}} 인터페이스의 **`pad`** 속성은 {{cssxref("@counter-style/pad", "pad")}} 기술자의 값을 호출하거나 지정합니다. 만일 기술자에 지정된 값이 없다면, 이 속성은 빈 문자열을 반환합니다.
```suggestion
{{domxref("CSSCounterStyleRule")}} 인터페이스의 **`pad`** 속성은 {{cssxref("@counter-style/pad", "pad")}} 설명자의 값을 호출하거나 지정합니다. 만일 설명자에 지정된 값이 없다면, 이 속성은 빈 문자열을 반환합니다.
```

문서의 통일성을 위해 용어를 맞추고 있어요.

- 기술자 -> 설명자

[Glossary guide](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md#section-title)에서 확인할 수 있습니다.

2024-05-18 14:09 UTC, 1ilsang commented on files/ko/web/api/csscounterstylerule/pad/index.md
> +다음 예제는 {{cssxref("@counter-style")}} 의 규칙을 보여줍니다. JavaScript 에서, `myRules[0]` 은 이 `@counter-style` 규칙이며, `pad` 를 반환하면 "0" 값을 얻을 수 있습니다.
```suggestion
다음 예제는 {{cssxref("@counter-style")}} 의 규칙을 보여줍니다. JavaScript에서, `myRules[0]`은 이 `@counter-style` 규칙이며, `pad`를 반환하면 "0" 값을 얻을 수 있습니다.
```

불필요한 띄어쓰기를 제거해 주세요.

2024-05-18 14:11 UTC, givvemee commented on files/ko/web/api/csscounterstylerule/pad/index.md
> +{{domxref("CSSCounterStyleRule")}} 인터페이스의 **`pad`** 속성은 {{cssxref("@counter-style/pad", "pad")}} 기술자의 값을 호출하거나 지정합니다. 만일 기술자에 지정된 값이 없다면, 이 속성은 빈 문자열을 반환합니다.
@1ilsang 기존에 기술자로 번역된 문서가 있어서 참고했는데 설명자였군요 ... cssstylerule 문서 모두 번역에 기술자로 사용하였고, 이미 머지된 것도 있는데 머지된 건 다시 수정하여 올리면 될까요?

2024-05-18 14:25 UTC, 1ilsang commented on files/ko/web/api/csscounterstylerule/pad/index.md
> +{{domxref("CSSCounterStyleRule")}} 인터페이스의 **`pad`** 속성은 {{cssxref("@counter-style/pad", "pad")}} 기술자의 값을 호출하거나 지정합니다. 만일 기술자에 지정된 값이 없다면, 이 속성은 빈 문자열을 반환합니다.
@givvemee 님

네...😭 그렇게 해주시면 감사하겠습니다. 리뷰어로 저를 지정해 주시면 빠르게 도와드리겠습니다.

2024-05-18 14:47 UTC, givvemee commented on files/ko/web/api/csscounterstylerule/pad/index.md
> +{{domxref("CSSCounterStyleRule")}} 인터페이스의 **`pad`** 속성은 {{cssxref("@counter-style/pad", "pad")}} 기술자의 값을 호출하거나 지정합니다. 만일 기술자에 지정된 값이 없다면, 이 속성은 빈 문자열을 반환합니다.
@1ilsang 좋습니다. 명일 중으로 수정해서 리뷰 요청 드릴게요.

2024-05-20 00:26 UTC, givvemee commented
@1ilsang 수정 완료 및 확인 부탁드립니다.

2024-05-20 11:15 UTC, 1ilsang approved these changes

2024-05-20 11:15 UTC, 1ilsang commented
고생하셨습니다

2024-05-20 11:15 UTC, merged