[zh-cn]: update the translation of Text `wholeText` property
mdn/translated-content pull request #20474
Opened 2024-05-17 08:14 UTC by T34-active

### Description
https://developer.mozilla.org/en-US/docs/Web/API/Text/wholeText

### Motivation

### Additional details

### Related issues and pull requests

2024-05-17 08:17 UTC, T34-active commented on files/zh-cn/web/api/text/wholetext/index.md
> +现在你的结果是 _“徒步旅行很不错！然而，投票是一件棘手的事情。_，超链接前有两个节点：
```suggestion
现在你的结果是 _“徒步旅行很不错！然而，投票是一件棘手的事情。"_，超链接前有两个节点：
```

2024-05-20 01:59 UTC, JasonLamv-t requested changes
Some suggestions

2024-05-20 01:59 UTC, JasonLamv-t commented on files/zh-cn/web/api/text/wholetext/index.md
> +2. 第二个 `Text` 节点包含字符串 `"然而，"`
```suggestion
1. 包含字符串 `"徒步旅行很不错！"` 的 {{domxref("Text")}} 节点
2. 第二个 `Text` 节点，包含字符串 `"然而，"`
```

2024-05-20 01:59 UTC, JasonLamv-t commented on files/zh-cn/web/api/text/wholetext/index.md
> +要同时获取这两个节点，你需要调用 `paragraph.childNodes[0].wholeText`：
```suggestion
要同时获取这两个节点，你可以调用 `paragraph.childNodes[0].wholeText`：
```

2024-05-20 03:24 UTC, JasonLamv-t approved these changes
👍

2024-05-20 03:24 UTC, merged