zh-cn: update Glossary/Falsy
mdn/translated-content pull request #20515
Opened 2024-05-17 14:51 UTC by PassionPenguin

2024-05-19 15:33 UTC, jasonren0403 requested changes

2024-05-19 15:33 UTC, jasonren0403 commented on files/zh-cn/glossary/falsy/index.md
少一句话

https://github.com/mdn/content/blob/b9c5849612a5beed7f2b8ab5e3c0a336bd585674/files/en-us/glossary/falsy/index.md?plain=1#L27

2024-05-19 15:34 UTC, jasonren0403 commented on files/zh-cn/glossary/falsy/index.md
> +| `false`                     | Boolean   | 关键词 [`false`](/zh-CN/docs/Web/JavaScript/Reference/Lexical_grammar#reserved_words).                          |
```suggestion
| `false`                     | Boolean   | 关键词 [`false`](/zh-CN/docs/Web/JavaScript/Reference/Lexical_grammar#关键字)。                          |
```

2024-05-20 10:18 UTC, jasonren0403 commented on files/zh-cn/glossary/falsy/index.md
> +| `false`                     | Boolean   | 关键词 [`false`](/zh-CN/docs/Web/JavaScript/Reference/Lexical_grammar#reserved_words).                          |
@PassionPenguin 这里是否忘记修改了

2024-05-20 10:31 UTC, PassionPenguin commented on files/zh-cn/glossary/falsy/index.md
> +| `false`                     | Boolean   | 关键词 [`false`](/zh-CN/docs/Web/JavaScript/Reference/Lexical_grammar#reserved_words).                          |
诶，可能是，原文表格的diff有点多我没处理好

2024-05-21 02:12 UTC, jasonren0403 commented on files/zh-cn/glossary/falsy/index.md
> +| `false`                     | Boolean   | 关键词 [`false`](/zh-CN/docs/Web/JavaScript/Reference/Lexical_grammar#reserved_words).                          |
改完表格可以自己跑一下prettier以减少后续反复修改

2024-05-21 02:15 UTC, jasonren0403 approved these changes
👍

2024-05-21 02:16 UTC, merged