zh-CN: update translation Glossary/Flex_Item
mdn/translated-content pull request #20524
Opened 2024-05-18 02:25 UTC by PassionPenguin

2024-06-01 02:34 UTC, yin1999 requested changes

2024-06-01 02:34 UTC, yin1999 commented on files/zh-cn/glossary/flex_item/index.md
> +- CSS 弹性布局指南：_[排序弹性项目](/zh-CN/docs/Web/CSS/CSS_flexible_box_layout/Ordering_flex_items)_
请把“排序”放到最后，一般我们都会用“对 xxx 进行排序”这一类的用法吧，而不是“排序 xxx”

```suggestion
- CSS 弹性布局指南：_[弹性项目排序](/zh-CN/docs/Web/CSS/CSS_flexible_box_layout/Ordering_flex_items)_
```

2024-06-01 02:34 UTC, yin1999 commented on files/zh-cn/glossary/flex_item/index.md
> +{{glossary("Flex Container", "弹性容器")}}的一级子元素（设置 `display: flex` 或 `display: inline-flex` 的子元素）是**弹性项目**。
请保持上下文翻译的一致性（这一点我已在 discord 中提出过）：如果要使用“项目”这一翻译，那么上下文的其他翻译就不应继续使用“元素”；如果使用“元素”这一翻译，那么也同理

2024-06-01 02:40 UTC, PassionPenguin commented on files/zh-cn/glossary/flex_item/index.md
> +{{glossary("Flex Container", "弹性容器")}}的一级子元素（设置 `display: flex` 或 `display: inline-flex` 的子元素）是**弹性项目**。
:ok

2024-06-02 00:34 UTC, yin1999 approved these changes

2024-06-02 00:37 UTC, merged