zh-CN: update translation Glossary/Forbidden_response_header_name
mdn/translated-content pull request #20531
Opened 2024-05-18 03:00 UTC by PassionPenguin

2024-05-28 10:10 UTC, jasonren0403 requested changes
有两处问题需要确认下

2024-05-28 10:10 UTC, jasonren0403 commented on files/zh-cn/glossary/forbidden_response_header_name/index.md
> +- {{Glossary("Forbidden header name", "禁止修改的标头")}}
原文并未移除 (Glossary) 标志

2024-05-28 10:10 UTC, jasonren0403 commented on files/zh-cn/glossary/forbidden_response_header_name/index.md
第10行：如 `Set-Cookie`

2024-05-28 10:28 UTC, PassionPenguin commented
> 有两处问题需要确认下

PTAL again ：）

2024-05-29 00:20 UTC, jasonren0403 approved these changes
thx 👍

2024-05-29 00:20 UTC, merged