zh-CN: update translation Glossary/Fork
mdn/translated-content pull request #20537
Opened 2024-05-18 03:05 UTC by PassionPenguin

fork 在 git-scm 的文档译名为分支(https://git-scm.com/book/zh/v2)

<img width="209" alt="Screenshot 2024-05-18 at 11 05 46 AM" src="https://github.com/mdn/translated-content/assets/41184947/2c0d55b2-4b8d-4f99-a3cd-f4bfb3ca68d4">

2024-05-30 05:52 UTC, yin1999 commented
> fork 在 git-scm 的文档译名为分支(https://git-scm.com/book/zh/v2)
> 
> <img alt="Screenshot 2024-05-18 at 11 05 46 AM" width="209" src="https://private-user-images.githubusercontent.com/41184947/331761319-2c0d55b2-4b8d-4f99-a3cd-f4bfb3ca68d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNDg2MTEsIm5iZiI6MTcxNzA0ODMxMSwicGF0aCI6Ii80MTE4NDk0Ny8zMzE3NjEzMTktMmMwZDU1YjItNGI4ZC00Zjk5LWEzY2QtZjRiZmIzY2E2OGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA1NTE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmMzg1Yzc0MDEzY2EwOTY0MGNjOTUyZTcxNTA5MjM2YzFjNTE3ZTY4NGY3OWQ2Yzk4MWUxN2ViOWRhMzgzZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hZEm2JzOqDgzrcIm3bsNxSYI--C-X1JIHLXEKZrcs-8">

分支是“branch”，别搞错了

![image](https://github.com/mdn/translated-content/assets/15844309/22f7cfc8-a94f-4a02-86ca-1af8afc6f252)

2024-05-30 05:55 UTC, yin1999 requested changes
请修改翻译，fork 可以翻译为“分叉”、“派生”……

- https://docs.github.com/zh/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks
- https://git-scm.com/book/zh/v2/GitHub-%E5%AF%B9%E9%A1%B9%E7%9B%AE%E5%81%9A%E5%87%BA%E8%B4%A1%E7%8C%AE

2024-05-30 07:58 UTC, PassionPenguin commented
> 请修改翻译，fork 可以翻译为“分叉”、“派生”……
> 
> * https://docs.github.com/zh/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks
> * https://git-scm.com/book/zh/v2/GitHub-%E5%AF%B9%E9%A1%B9%E7%9B%AE%E5%81%9A%E5%87%BA%E8%B4%A1%E7%8C%AE

ええと！对不起！

分叉：）

2024-05-30 11:38 UTC, yin1999 reviewed
等待：mdn/content#33836

2024-05-30 11:38 UTC, yin1999 commented on files/zh-cn/glossary/fork/index.md
> +分叉（Fork）是在某一时刻对现有的软件项目进行复制，并在项目加上某人的修改。基本上，如果原软件的许可证允许，你就可以复制软件的代码，开发自己的版本，附加上自己的补充，这就是一个分叉。
```suggestion
分叉（Fork）是在某一时刻对现有的软件项目进行复制，并在项目加上某人的修改。

基本上，如果原软件的许可证允许，你就可以复制软件的代码，开发自己的版本，附加上自己的补充，这就是一个分叉。
```

2024-06-01 07:02 UTC, yin1999 commented on files/zh-cn/glossary/fork/index.md
> +  sourceCommit: ada5fa5ef15eadd44b549ecf906423b4a2092f34
```suggestion
  sourceCommit: 95d5dfa3fa7eac1bdb1a7bfbd67a84c470caa99e
```

2024-06-01 07:02 UTC, yin1999 approved these changes

2024-06-01 07:04 UTC, merged