zh-cn: update translation Glossary/Global_object
mdn/translated-content pull request #20558
Opened 2024-05-18 08:06 UTC by PassionPenguin

2024-05-28 15:14 UTC, yin1999 requested changes

2024-05-29 00:31 UTC, PassionPenguin commented on files/zh-cn/glossary/global_object/index.md
> +- [术语](/zh-CN/docs/Glossary)
啊，保留全名么（

👌

2024-05-29 00:40 UTC, yin1999 commented on files/zh-cn/glossary/global_object/index.md
> +- 在网页浏览器中，脚本未明确启动为后台任务的任何代码都将具有一个 {{domxref("Window")}} 作为其全局对象。这是网络上绝大多数 JavaScript 代码的情况。
Web 不翻译

```suggestion
- 在网页浏览器中，脚本未明确启动为后台任务的任何代码都将具有一个 {{domxref("Window")}} 作为其全局对象。这是 Web 上绝大多数 JavaScript 代码的情况。
```

2024-05-29 01:32 UTC, yin1999 commented on files/zh-cn/glossary/global_object/index.md
> +- 在浏览器中，脚本未明确启动为后台任务的任何代码都将具有一个 {{domxref("Window")}} 作为其全局对象。这是 Web 上绝大多数 JavaScript 代码的情况。
浏览器本身的指代其实是不明确的，我不太建议使用简称：

- Web 浏览器
- 文件浏览器

你将其翻译为“网页浏览器”也没有问题（因为这个已经是大家都认同且使用的翻译），或者就不翻译它（因为我们不翻译“Web”一词）。

2024-05-29 02:55 UTC, yin1999 approved these changes

2024-05-29 02:55 UTC, merged