zh-cn: update translation Glossary/Hoisting
mdn/translated-content pull request #20564
Opened 2024-05-18 08:07 UTC by PassionPenguin

2024-05-20 09:40 UTC, jasonren0403 requested changes
一些修改建议

2024-05-20 09:40 UTC, jasonren0403 commented on files/zh-cn/glossary/hoisting/index.md
> +有些人更倾向于将 `let`、`const` 和 `class` 视为不提升的，因为[暂时性死区](/zh-CN/docs/Web/JavaScript/Reference/Statements/let#temporal_dead_zone_tdz)严格禁止在声明之前使用变量。这种看法是可以接受的，因为提升并不是一个普遍认同的术语。然而，暂时性死区可以导致其作用域内的其他可观察变化，这表明存在某
链接锚点

2024-05-20 09:40 UTC, jasonren0403 commented on files/zh-cn/glossary/hoisting/index.md
> +*提升*不是 ECMAScript 规范中规范定义的术语。规范确实将一组声明定义为[可提升的声明](https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#prod-HoistableDeclaration)，但这只包括 [`function`](/zh-CN/docs/Web/
斜体格式

2024-05-20 09:40 UTC, jasonren0403 commented on files/zh-cn/glossary/hoisting/index.md
> +2. 能够在声明变量之前在其作用域中引用该变量而不抛出 {{jsxref("ReferenceError")}}，但值始终是 undefined。（“声明提升”）
链接

2024-05-20 09:40 UTC, jasonren0403 commented on files/zh-cn/glossary/hoisting/index.md
> +前面说到的四种函数声明的提升表现为第 1 种行为；`var` 声明的提升表现为第 2 种行为；[`let`](/zh-CN/docs/Web/JavaScript/Reference/Statements/let)、[`const`](/zh-CN/docs/Web/JavaScript/Reference/Statements/const) 和 [`class`](/zh-CN/docs/We
```suggestion
前面说到的四种函数声明的提升表现为第 1 种行为；`var` 声明的提升表现为第 2 种行为；[`let`](/zh-CN/docs/Web/JavaScript/Reference/Statements/let)、[`const`](/zh-CN/docs/Web/JavaScript/Reference/Statements/const) 和 [`class`](/zh-CN/docs/Web/JavaScript/Reference/Statements/class) 声明（也称为*词法声明*）的提升表现为第 3 种行为；[`import`](/zh-CN/docs/Web/JavaScript/Reference/Statements/import) 声明的提升表现为第 1 和第 4 种行为。
```

2024-05-20 09:40 UTC, jasonren0403 commented on files/zh-cn/glossary/hoisting/index.md
> +如果 `const x = 2` 声明完全没有提升（即仅在执行时生效），那么 `console.log(x)` 语句应该能够读取上层作用域的 `x` 值。然而，由于 `const` 声明仍然“污染”了其定义的整个作用域，`console.log(x)` 语句读取的是 `const x = 2` 声明的 `x`，但它尚未初始化，因此抛出 {{jsxref("ReferenceError")}}。不
```suggestion
如果 `const x = 2` 声明完全没有提升（即仅在执行时生效），那么 `console.log(x)` 语句应该能够读取上层作用域的 `x` 值。然而，由于 `const` 声明仍然“污染”了其定义的整个作用域，`console.log(x)` 语句读取的是 `const x = 2` 声明的 `x`，但它尚未初始化，因此抛出 {{jsxref("ReferenceError")}}。不过，从实用角度看，将词法声明视为不提升可能更有用，因为这些声明的提升并没有带来任何有意义的特性。
```

2024-05-20 09:40 UTC, jasonren0403 commented on files/zh-cn/glossary/hoisting/index.md
> +- `import` 提升 — [JavaScript 模块](/zh-CN/docs/Web/JavaScript/Guide/Modules#import_declarations_are_hoisted)
锚点

```suggestion
- `var`、`let`、`const` 提升——[语法类型教程](/zh-CN/docs/Web/JavaScript/Guide/Grammar_and_types#variable_hoisting)
- `function` 提升——[函数教程](/zh-CN/docs/Web/JavaScript/Guide/Functions#function_hoisting)
- `class` 提升——[类教程](/zh-CN/docs/Web/JavaScript/Guide/Using_classes#class_declaration_hoisting)
- `import` 提升——[JavaScript 模块](/zh-CN/docs/Web/JavaScript/Guide/Modules#import_declarations_are_hoisted)
```

2024-05-26 05:29 UTC, jasonren0403 reviewed
还是有些问题，请查看

2024-05-26 05:29 UTC, jasonren0403 commented on files/zh-cn/glossary/hoisting/index.md
> +- `import` 提升——[JavaScript 模块](/zh-CN/docs/Web/JavaScript/Guide/Modules#import_declarations_are_hoisted)
链接锚点也要作相应更新

2024-05-26 05:29 UTC, jasonren0403 commented on files/zh-cn/glossary/hoisting/index.md
> +- [`function` 语句](/zh-CN/docs/Web/JavaScript/Reference/Statements/function)
可考虑在原文中移除“- MDN”

2024-05-26 07:14 UTC, PassionPenguin commented on files/zh-cn/glossary/hoisting/index.md
> +- `import` 提升——[JavaScript 模块](/zh-CN/docs/Web/JavaScript/Guide/Modules#import_declarations_are_hoisted)
oops，过一阵子我一个个对照看（手机看不方便

2024-05-26 07:14 UTC, PassionPenguin commented on files/zh-cn/glossary/hoisting/index.md
> +- [`function` 语句](/zh-CN/docs/Web/JavaScript/Reference/Statements/function)
嗯，过一阵子提

2024-05-28 08:39 UTC, PassionPenguin commented on files/zh-cn/glossary/hoisting/index.md
> +- `import` 提升——[JavaScript 模块](/zh-CN/docs/Web/JavaScript/Guide/Modules#import_declarations_are_hoisted)
@jasonren0403 import的那个中文anchor缺失

2024-05-28 09:49 UTC, PassionPenguin commented on files/zh-cn/glossary/hoisting/index.md
> +- [`function` 语句](/zh-CN/docs/Web/JavaScript/Reference/Statements/function)
merged in mdn/content#33787

2024-05-28 10:05 UTC, jasonren0403 commented on files/zh-cn/glossary/hoisting/index.md
> +  sourceCommit: 8fb5853ceee5db8ac6e1c564c6dda4b3f5ec86c5
下次记得更新sourceCommit

```suggestion
  sourceCommit: 9fd171abed5944476123db22360b1e086f0900d5
```

2024-05-28 10:06 UTC, jasonren0403 approved these changes

2024-05-28 10:10 UTC, merged