zh-cn: update translation Glossary/GZip
mdn/translated-content pull request #20572
Opened 2024-05-18 08:08 UTC by PassionPenguin

2024-05-25 07:52 UTC, yin1999 requested changes

2024-05-25 07:52 UTC, yin1999 commented on files/zh-cn/glossary/gzip_compression/index.md
> +title: GZip 压缩
为何修改大小写，GNU 并未采用将“z”大写的形式：https://www.gnu.org/software/gzip/

2024-05-25 14:29 UTC, PassionPenguin commented on files/zh-cn/glossary/gzip_compression/index.md
> +title: GZip 压缩
因为原文是怪异的拼写……
<img width="643" alt="Screenshot 2024-05-25 at 10 28 59 PM" src="https://github.com/mdn/translated-content/assets/41184947/5a92ca80-a53d-4f30-8b2c-9a51e256a278">

2024-05-31 02:36 UTC, yin1999 commented
已在 #21045 中同步

2024-05-31 02:36 UTC, closed without merging