Firefox 91 for developers を翻訳
mdn/translated-content pull request #2059
Opened 2021-08-14 12:25 UTC by yyss

Aug 13, 2021 の英語版に対応。

2021-08-17 01:47 UTC, mfuji09 requested changes
1件だけ修正をお願いします。

2021-08-17 01:47 UTC, mfuji09 commented on files/ja/mozilla/firefox/releases/91/index.html
> +<h3 id="HTML" name="HTML">HTML</h3>
id属性とname属性を重ねる運用はもう行っていませんので、name属性は削除してください。以降も同じです。

2021-08-28 09:28 UTC, yyss commented
name属性を削除しました。

2021-08-28 11:31 UTC, mfuji09 approved these changes
OKです。

2021-08-28 11:57 UTC, merged