zh-CN: update translation Glossary/Idempotent
mdn/translated-content pull request #20610
Opened 2024-05-18 12:55 UTC by PassionPenguin

2024-05-20 10:10 UTC, jasonren0403 requested changes
同步过程中要注意原文的格式（段落、代码、链接、粗斜体等）

2024-05-20 10:10 UTC, jasonren0403 commented on files/zh-cn/glossary/idempotent/index.md
> +一个 HTTP 方法是**幂等**的，指的是同样的请求被执行一次与连续执行多次的效果是一样的，服务器的状态也是一样的。换句话说就是，
再检查下这段话

2024-05-20 10:10 UTC, jasonren0403 commented on files/zh-cn/glossary/idempotent/index.md
> +这不意味着请求不会有*任何*副作用，比如，服务器可能会对所有请求做记录。在正确实现的条件下， {{HTTPMethod("GET")}}、{{HTTPMethod("HEAD")}}、{{HTTPMethod("PUT")}} 和 {{HTTPMethod("DELETE")}} 等方法都是**幂等**的，而 {{HTTPMethod("POST")}} 方法不是。
[原文](https://github.com/mdn/content/blob/9a9dcd5848aaf1c4226f746539e6218c48647249/files/en-us/glossary/idempotent/index.md?plain=1#L11)并无“在正确实现的条件下……”的表达

2024-05-20 10:10 UTC, jasonren0403 commented on files/zh-cn/glossary/idempotent/index.md
> +幂等性只考虑服务器的状态。每次请求返回的响应可能不同：例如，第一次调用 {{HTTPMethod("DELETE")}} 可能会返回 {{HTTPStatus("200")}}，而后续的调用可能会返回 {{HTTPStatus("404")}}。另一个 {{HTTPMethod("DELETE")}} 是幂等的含义是，开发者不应该使用 `DELETE` 方法实现 RESTful API 的 _删
```suggestion
幂等性只考虑服务器的状态。每次请求返回的响应可能不同：例如，第一次调用 {{HTTPMethod("DELETE")}} 可能会返回 {{HTTPStatus("200")}}，而后续的调用可能会返回 {{HTTPStatus("404")}}。{{HTTPMethod("DELETE")}} 具有幂等性的另外一层含义是，开发者不应该使用 `DELETE` 方法实现 RESTful API 的*删除最后一个条目*功能。
```

2024-05-20 10:10 UTC, jasonren0403 commented on files/zh-cn/glossary/idempotent/index.md
>  ```
```suggestion
```http
```

2024-05-20 10:10 UTC, jasonren0403 commented on files/zh-cn/glossary/idempotent/index.md
>  ```
```suggestion
```http
```

2024-05-20 10:10 UTC, jasonren0403 commented on files/zh-cn/glossary/idempotent/index.md
>  `DELETE /idX/delete HTTP/1.1` 是幂等的，即便是不同请求之间接收到的状态码不一样：
```suggestion
`DELETE /idX/delete HTTP/1.1` 是幂等的，即使返回的状态代码在不同请求之间可能会发生变化：
```

2024-05-25 13:02 UTC, PassionPenguin commented on files/zh-cn/glossary/idempotent/index.md
> +这不意味着请求不会有*任何*副作用，比如，服务器可能会对所有请求做记录。在正确实现的条件下， {{HTTPMethod("GET")}}、{{HTTPMethod("HEAD")}}、{{HTTPMethod("PUT")}} 和 {{HTTPMethod("DELETE")}} 等方法都是**幂等**的，而 {{HTTPMethod("POST")}} 方法不是。
是上一个译者对之前版本的翻译，第一眼没看出来有diff，抱歉

2024-05-26 05:20 UTC, jasonren0403 commented on files/zh-cn/glossary/idempotent/index.md
> +一个 HTTP 方法是**幂等**的，如果同样的请求被执行一次与连续执行多次，在服务器上希望得到的效果是一样的。
```suggestion
如果同样的请求被执行一次与连续执行多次，对服务器的预期影响是相同的，那么称这个 HTTP 方法是**幂等的**。
```

2024-05-28 10:01 UTC, jasonren0403 approved these changes
👍

2024-05-28 10:01 UTC, merged