feat: cssrule index 번역
mdn/translated-content pull request #20668
Opened 2024-05-20 01:12 UTC by givvemee

### Description

기존에 한국어로 존재하지 않던 문서 [CSSRule](https://developer.mozilla.org/en-US/docs/Web/API/CSSRule) 을 번역합니다.

### Motivation

### Additional details

### Related issues and pull requests

2024-05-26 04:39 UTC, 1ilsang requested changes
@givvemee 님 안녕하세요. 기여해주셔서 감사합니다! 💯

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

질문이나 도움이 필요하시다면 언제든 멘션 부탁드리겠습니다.

2024-05-26 04:39 UTC, 1ilsang commented on files/ko/web/api/cssrule/index.md
> +The `CSSRule` interface specifies the properties common to all rules, while properties unique to specific rule types are specified in the more specialized interfaces for those rules' respective types
```suggestion

```

원문을 잘못 올리신 것 같네요

2024-05-26 04:39 UTC, 1ilsang commented on files/ko/web/api/cssrule/index.md
> +- [Using dynamic styling information](/ko/docs/Web/API/CSS_Object_Model/Using_dynamic_styling_information)
```suggestion
- [동적 스타일링 정보 사용하기](/ko/docs/Web/API/CSS_Object_Model/Using_dynamic_styling_information)
```

같이 번역 부탁드립니다.

2024-05-26 04:39 UTC, 1ilsang commented on files/ko/web/api/cssrule/index.md
> +  - : Returns the containing rule, otherwise `null`. E.g. if this rule is a style rule inside an {{cssxref("@media")}} block, the parent rule would be that {{domxref("CSSMediaRule")}}.
```suggestion

```

원문을 잘못 올리신 것 같아요.

2024-05-26 04:39 UTC, 1ilsang commented on files/ko/web/api/cssrule/index.md
> +  - : 이 규칙을 포함하는 상위 규칙을 반환하고, 상위 규칙이 없는 경우 null을 반환합니다. 예를 들어, 이 규칙이 {{cssxref("@media")}} 블록 내에 있는 스타일 규칙인 경우, 상위 규칙은 {{domxref("CSSMediaRule")}}입니다.
```suggestion
  - : 이 규칙을 포함하는 상위 규칙을 반환하고, 상위 규칙이 없는 경우 `null`을 반환합니다. 예를 들어, 이 규칙이 {{cssxref("@media")}} 블록 내에 있는 스타일 규칙인 경우, 상위 규칙은 {{domxref("CSSMediaRule")}}입니다.
```

원문의 표시와 같이 해주세요

2024-05-27 00:59 UTC, givvemee commented on files/ko/web/api/cssrule/index.md
> +  - : Returns the containing rule, otherwise `null`. E.g. if this rule is a style rule inside an {{cssxref("@media")}} block, the parent rule would be that {{domxref("CSSMediaRule")}}.
@1ilsang 아이고! 영문 보고 한글 번역 후 영문을 지우는데, 요거는 제가 지우지 못한 것들이 좀 남아 있었네요. 세심한 확인 감사합니다.

2024-05-30 15:10 UTC, 1ilsang approved these changes
LGTM 고생하셨습니다

2024-05-30 15:10 UTC, merged