[ko] String.prototype.anchor() 신규 번역
mdn/translated-content pull request #20716
Opened 2024-05-21 22:40 UTC by wisedog

String.prototype.anchor() 신규 번역

2024-06-18 23:02 UTC, wisedog commented
@1ilsang  ㅇ.ㅇ 이거 어떻게 된거죠?

2024-06-19 13:34 UTC, 1ilsang requested changes
@wisedog 님 안녕하세요. 늦어서 죄송합니다. 😅  

기여해주셔서 감사합니다! 💯

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

질문이나 도움이 필요하시다면 언제든 멘션 부탁드리겠습니다.

2024-06-19 22:35 UTC, wisedog commented
@1ilsang  리뷰 감사합니다. 반영했습니다.

2024-06-20 02:38 UTC, 1ilsang approved these changes
LGTM 고생하셨습니다

2024-06-20 02:38 UTC, merged