[zh-tw]: update HTTP CORS
mdn/translated-content pull request #20752
Opened 2024-05-24 08:45 UTC by an-777

2024-05-27 05:50 UTC, yin1999 requested changes

2024-05-27 05:50 UTC, yin1999 commented on files/zh-tw/web/http/cors/index.md
> +CORS 機制支持瀏覽器和伺服器之間的安全跨來源請求和數據傳輸。瀏覽器在 `fetch()` 或 `XMLHttpRequest` 等 API 中使用 CORS 來減少跨來源 HTTP 請求的風險。
降低风险（“减少”不太合适）

2024-05-27 05:50 UTC, yin1999 commented on files/zh-tw/web/http/cors/index.md
> +跨來源資源共享標準通過新增 [HTTP 標頭](/zh-TW/docs/Web/HTTP/Headers)來工作，這些標頭讓伺服器描述哪些來源被允許從 Web 瀏覽器讀取該訊息。此外，對於可能對伺服器數據產生副作用的 HTTP 請求方法（特別是 {{HTTPMethod("GET")}} 以外的 HTTP 方法，或具有特定 [MIME 類型](/zh-TW/docs/Web/HTTP/Basic
```suggestion
跨來源資源共享標準通過新增 [HTTP 標頭](/zh-TW/docs/Web/HTTP/Headers)來工作，這些標頭讓伺服器描述哪些來源被允許從 Web 瀏覽器讀取該訊息。此外，對於可能對伺服器數據產生副作用的 HTTP 請求方法（特別是 {{HTTPMethod("GET")}} 以外的 HTTP 方法，或具有特定 [MIME 類型](/zh-TW/docs/Web/HTTP/Basics_of_HTTP/MIME_types)的 {{HTTPMethod("POST")}} 方法），規範要求瀏覽器「預檢」該請求，通過 HTTP {{HTTPMethod("OPTIONS")}} 請求方法向伺服器詢問支持的方法，然後在獲得伺服器「批准」後發送實際請求。伺服器還可以通知用戶端是否應該與請求一起發送「憑證」（例如 [Cookie](/zh-TW/docs/Web/HTTP/Cookies) 和 [HTTP 身份驗證](/zh-TW/docs/Web/HTTP/Authentication)）。
```

2024-05-27 05:50 UTC, yin1999 commented on files/zh-tw/web/http/cors/index.md
> +某些請求不會觸發{{Glossary("Preflight_request","CORS 預檢請求")}}。這些請求被稱為*簡單請求*，這個術語來自過時的 [CORS 規範](https://www.w3.org/TR/2014/REC-cors-20140116/#terminology)，儘管現在定義 CORS 的 [Fetch 規範](https://fetch.spec.whatwg.o
```suggestion
某些請求不會觸發 {{Glossary("Preflight_request","CORS 預檢請求")}}。這些請求被稱為*簡單請求*，這個術語來自過時的 [CORS 規範](https://www.w3.org/TR/2014/REC-cors-20140116/#terminology)，儘管現在定義 CORS 的 [Fetch 規範](https://fetch.spec.whatwg.org/)並未使用該術語。
```

2024-05-27 05:50 UTC, yin1999 commented on files/zh-tw/web/http/cors/index.md
> +*簡單請求*是指 **符合以下所有條件的請求**：
```suggestion
*簡單請求*是指**符合以下所有條件的請求**：
```

2024-05-27 05:50 UTC, yin1999 commented on files/zh-tw/web/http/cors/index.md
> +- 除了由用戶代理自動設置的標頭（例如 {{HTTPHeader("Connection")}}、{{HTTPHeader("User-Agent")}} 或 [Fetch 規範中定義為*禁止標頭名稱*的其他標頭](https://fetch.spec.whatwg.org/#forbidden-header-name)）之外，唯一允許手動設置的標頭是 [Fetch 規範定義的 CORS 安全列
用“禁止的標頭名稱”是否更好些

2024-05-27 05:50 UTC, yin1999 commented on files/zh-tw/web/http/cors/index.md
> +  - {{HTTPHeader("Content-Type")}}（請注意以下附加要求）
“以下”一般需要内容紧跟，用“后面的”或者原先的翻译——下方，是否会更好些

2024-05-27 05:50 UTC, yin1999 commented on files/zh-tw/web/http/cors/index.md
> +- 如果請求是使用 {{domxref("XMLHttpRequest")}} 對象發出的，則在通過 {{domxref("XMLHttpRequest.upload")}} 屬性返回的對象上未註冊任何事件監聽器（即給定一個 {{domxref("XMLHttpRequest")}} 實例 `xhr`，沒有代碼調用 `xhr.upload.addEventListener()` 來添加事件監聽器
```suggestion
- 如果請求是使用 {{domxref("XMLHttpRequest")}} 對象發出的，則在通過 {{domxref("XMLHttpRequest.upload")}} 屬性返回的對象上未註冊任何事件監聽器（即給定一個 {{domxref("XMLHttpRequest")}} 實例 `xhr`，沒有代碼調用 `xhr.upload.addEventListener()` 來添加事件監聽器以監控上傳）。
```

2024-05-27 05:50 UTC, yin1999 commented on files/zh-tw/web/http/cors/index.md
> +> **備註：** WebKit Nightly 和 Safari Technology Preview 對 {{HTTPHeader("Accept")}}、{{HTTPHeader("Accept-Language")}} 和 {{HTTPHeader("Content-Language")}} 標頭中的值施加了額外的限制。如果這些標頭中的任何一個具有「非標準」值，WebKit/Safari
```suggestion
> **備註：** WebKit Nightly 和 Safari Technology Preview 對 {{HTTPHeader("Accept")}}、{{HTTPHeader("Accept-Language")}} 和 {{HTTPHeader("Content-Language")}} 標頭中的值施加了額外的限制。如果這些標頭中的任何一個具有「非標準」值，WebKit/Safari 不會認為該請求是「簡單請求」。WebKit/Safari 認為「非標準」的值未在文檔中說明，除了以下 WebKit bug：
```

2024-05-27 05:50 UTC, yin1999 commented on files/zh-tw/web/http/cors/index.md
> +> 沒有其他瀏覽器實施這些額外的限制，因為它們不是規範的一部分。
用“不属于该规范”？

2024-05-27 05:50 UTC, yin1999 commented on files/zh-tw/web/http/cors/index.md
> +[…XML Data…]
翻译一下

2024-05-27 05:50 UTC, yin1999 commented on files/zh-tw/web/http/cors/index.md
> +與[簡單請求](#簡單請求) 不同，對於「預檢」請求，瀏覽器首先使用 {{HTTPMethod("OPTIONS")}} 方法向另一個來源的資源發送 HTTP 請求，以確定實際請求是否安全可發送。這類跨來源請求會進行預檢，因為它們可能對用戶數據產生影響。
```suggestion
與[簡單請求](#簡單請求)不同，對於「預檢」請求，瀏覽器首先使用 {{HTTPMethod("OPTIONS")}} 方法向另一個來源的資源發送 HTTP 請求，以確定實際請求是否安全可發送。這類跨來源請求會進行預檢，因為它們可能對用戶數據產生影響。
```

2024-05-27 05:50 UTC, yin1999 commented on files/zh-tw/web/http/cors/index.md
> +上述的第 1 至 10 行代表了使用 {{HTTPMethod("OPTIONS")}} 方法的預檢查請求。瀏覽器根據上面 JavaScript 代碼片段使用的請求參數來確定需要發送這個請求，這樣伺服器就可以回應是否接受使用實際的請求參數發送請求。OPTIONS 是一個 HTTP/1.1 方法，用於從伺服器獲取更多訊息，是一個{{Glossary("Safe/HTTP", "安全")}}方法，意
預檢查 => 預檢，请保持统一，下文中还有好几处

2024-05-27 05:50 UTC, yin1999 commented on files/zh-tw/web/http/cors/index.md
> +#### 第三方Cookie
下文中也有这个问题，请修复

```suggestion
#### 第三方 Cookie
```

2024-05-27 05:50 UTC, yin1999 commented on files/zh-tw/web/http/cors/index.md
> +  - 如何修復<_「Access-Control-Allow-Origin頭不能是通配符」_>
为何要加尖括号

2024-05-29 08:53 UTC, an-777 commented on files/zh-tw/web/http/cors/index.md
> +- 除了由用戶代理自動設置的標頭（例如 {{HTTPHeader("Connection")}}、{{HTTPHeader("User-Agent")}} 或 [Fetch 規範中定義為*禁止標頭名稱*的其他標頭](https://fetch.spec.whatwg.org/#forbidden-header-name)）之外，唯一允許手動設置的標頭是 [Fetch 規範定義的 CORS 安全列
![螢幕擷取畫面 2024-05-29 165058](https://github.com/mdn/translated-content/assets/131597737/71f7f13a-a406-488e-acd7-2338dee9b706)
![螢幕擷取畫面 2024-05-29 165119](https://github.com/mdn/translated-content/assets/131597737/5793e694-dbb2-4ad6-be7d-29474baa56c2)


我是照之前 http header 翻的

2024-05-29 10:57 UTC, yin1999 commented on files/zh-tw/web/http/cors/index.md
> +[…XML Data…]
“Data”可翻译

2024-05-30 00:18 UTC, yin1999 approved these changes

2024-05-30 00:18 UTC, merged