[zh-cn]: update the translation of `webrtc/perfec negotiation`
mdn/translated-content pull request #20754
Opened 2024-05-24 09:17 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests
#16473

2024-05-25 18:34 UTC, skyclouds2001 commented on files/zh-cn/web/api/webrtc_api/perfect_negotiation/index.md
> +title: "Establishing a connection: The WebRTC perfect negotiation pattern"
```suggestion
title: "Establishing a connection: The WebRTC perfect negotiation pattern"
```

标题也应该翻译一下

2024-05-25 18:34 UTC, skyclouds2001 commented on files/zh-cn/web/api/webrtc_api/perfect_negotiation/index.md
> +由于 [WebRTC](/zh-CN/docs/Web/API/WebRTC_API)并没有强制要求在协商新对等连接期间使用特定的传输机制来发送信令，因此它具有很高的灵活性。不过，尽管信令消息的传输和通信具有这种灵活性，在可能的情况下，你应遵循一种推荐的设计模式，即完美协商。
```suggestion
由于 [WebRTC](/zh-CN/docs/Web/API/WebRTC_API) 并没有强制要求在协商新对等连接期间使用特定的传输机制来发送信令，因此它具有很高的灵活性。不过，尽管信令消息的传输和通信具有这种灵活性，在可能的情况下，你应遵循一种推荐的设计模式，即完美协商。
```

2024-05-25 18:34 UTC, skyclouds2001 commented on files/zh-cn/web/api/webrtc_api/perfect_negotiation/index.md
> +这与旧版 WebRTC 连接建立代码没有明显区别。用户的摄像头和麦克风可通过调用 {{domxref("MediaDevices.getUserMedia", "getUserMedia()")}} 获得。然后，通过向 {{domxref("RTCPeerConnection.addTrack", "addTrack()")}} 传入{{domxref("RTCPeerConnection")}
```suggestion
这与旧版 WebRTC 连接建立代码没有明显区别。用户的摄像头和麦克风可通过调用 {{domxref("MediaDevices.getUserMedia", "getUserMedia()")}} 获得。然后，通过向 {{domxref("RTCPeerConnection.addTrack", "addTrack()")}} 传入 {{domxref("RTCPeerConnection")}}，将得到的媒体轨道添加到 {{domxref("RTCPeerConnection")}} 中。最后，`selfVideo` 常量指示的自视图 {{HTMLElement("video")}} 元素的媒体源被设置为摄像头和麦克风流，这样本地用户就能看到对方看到的内容。
```

2024-05-25 18:34 UTC, skyclouds2001 commented on files/zh-cn/web/api/webrtc_api/perfect_negotiation/index.md
> +另一方面，如果报文有 `candidate`，则它是作为[trickle ICE]（/zh-CN/docs/Web/API/RTCPeerConnection/canTrickleIceCandidates）的一部分从远程对等设备接收的 ICE 候选。通过将候选对象传入 {{domxref("RTCPeerConnection.addIceCandidate", "addIceCandidate
```suggestion
另一方面，如果报文有 `candidate`，则它是作为 [trickle ICE](/zh-CN/docs/Web/API/RTCPeerConnection/canTrickleIceCandidates) 的一部分从远程对等设备接收的 ICE 候选。通过将候选对象传入 {{domxref("RTCPeerConnection.addIceCandidate", "addIceCandidate()")}}，候选对象将被发送到本地 ICE 层。
```

2024-05-25 18:34 UTC, skyclouds2001 commented on files/zh-cn/web/api/webrtc_api/perfect_negotiation/index.md
> +正如在 [实现完美协商](#实现完美协商) 部分所示，我们可以通过引入一个变量（这里称为 `makingOffer` ），用于指示我们正在发送一个邀约的过程，并利用更新后的 `setLocalDescription()` 方法来消除这个问题。
```suggestion
正如在[实现完美协商](#实现完美协商) 部分所示，我们可以通过引入一个变量（这里称为 `makingOffer` ），用于指示我们正在发送一个邀约的过程，并利用更新后的 `setLocalDescription()` 方法来消除这个问题。
```

2024-05-28 15:16 UTC, yin1999 commented on files/zh-cn/web/api/webrtc_api/perfect_negotiation/index.md
> +如果新设置的远程描述是一个邀约，我们就会要求 WebRTC 通过调用 {{domxref("RTCPeerConnection")}} 方法 {{domxref("RTCPeerConnection.setLocalDescription", "setLocalDescription()")}} 来选择合适的本地配置，而无需参数。这样， `setLocalDescription()` 就会自动生
```suggestion
如果新设置的远程描述是一个邀约，我们就会要求 WebRTC 通过调用 {{domxref("RTCPeerConnection")}} 方法 {{domxref("RTCPeerConnection.setLocalDescription", "setLocalDescription()")}} 来选择合适的本地配置，而无需参数。这样，`setLocalDescription()` 就会自动生成适当的应答，以回应收到的邀约。然后，我们通过信令信道将应答发送回第一个对等点。
```

2024-05-28 15:16 UTC, yin1999 commented on files/zh-cn/web/api/webrtc_api/perfect_negotiation/index.md
> +我们在调用 `setLocalDescription()` 之前立即设置 `makingOffer` ，以防止干扰发送此邀约，并且在将邀约发送到信令服务器后（或者发生错误，导致无法发出邀约）才将其清除为 `false` 。通过这种方式，我们避免了邀约发生冲突的风险。
空格

2024-05-28 15:16 UTC, yin1999 commented on files/zh-cn/web/api/webrtc_api/perfect_negotiation/index.md
> +由于没有一个单独的“回滚并使用此邀约”，在有礼貌的对等方上执行此更改需要两个步骤，在 [`Promise.all()`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) 的上下文中执行，该方法用于确保两个语句在继续处理接收到的邀约之前完全执行。第一个语句触发回滚，第二个语句将远程描述设置为接收到的描述，从而完成用新
也不应有空格

```suggestion
由于没有一个单独的“回滚并使用此邀约”，在有礼貌的对等方上执行此更改需要两个步骤，在 [`Promise.all()`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) 的上下文中执行，该方法用于确保两个语句在继续处理接收到的邀约之前完全执行。第一个语句触发回滚，第二个语句将远程描述设置为接收到的描述，从而完成用新收到的邀约替换先前*发送的*邀约的过程。有礼貌的对等方现在成为被叫方而不是主叫方。
```

2024-05-28 15:18 UTC, yin1999 commented on files/zh-cn/web/api/webrtc_api/perfect_negotiation/index.md
> +代码检查消息是否是一个邀约，并且如果是，则检查本地信令状态是否不是 `stable` 。如果不是稳定的，并且本地对等点是有礼貌的，那么我们需要触发回滚，以便我们可以用新收到的邀约替换正在传出的邀约。这两步都必须在我们继续处理收到的邀约之前完成。
```suggestion
代码检查消息是否是一个邀约，并且如果是，则检查本地信令状态是否不是 `stable`。如果不是稳定的，并且本地对等点是有礼貌的，那么我们需要触发回滚，以便我们可以用新收到的邀约替换正在传出的邀约。这两步都必须在我们继续处理收到的邀约之前完成。
```

2024-06-04 03:04 UTC, JasonLamv-t requested changes
请先检查一遍；
使用 GPT 之类的翻译工具作为辅助是允许的，但是请不要依赖并仔细检查和校对。

2024-06-04 03:04 UTC, JasonLamv-t commented on files/zh-cn/web/api/webrtc_api/perfect_negotiation/index.md
> +另一方面，如果报文有 `candidate`，则它是作为 [trickle ICE](/zh-CN/docs/Web/API/RTCPeerConnection/canTrickleIceCandidates) 的一部分从远程对等设备接收的 ICE 候选。通过将候选对象传入 {{domxref("RTCPeerConnection.addIceCandidate", "addIceCandida
```suggestion
另一方面，如果消息中包含一个 `candidate` 字段，那么它就是作为[渐进式 ICE](/zh-CN/docs/Web/API/RTCPeerConnection/canTrickleIceCandidates) 的一部分，从远程对等方接收到的 ICE 候选信息。这个候选项将通过调用 {{domxref("RTCPeerConnection.addIceCandidate", "addIceCandidate()")}} 方法传递给本地的 ICE 处理层。
```

2024-06-04 03:04 UTC, JasonLamv-t commented on files/zh-cn/web/api/webrtc_api/perfect_negotiation/index.md
> +##### 在收到说明时
```suggestion
##### 在收到描述时
```

2024-06-04 03:04 UTC, JasonLamv-t commented on files/zh-cn/web/api/webrtc_api/perfect_negotiation/index.md
> +如果我们收到了 `描述`，我们就会准备对收到的邀约或答复做出回应。首先，我们要检查是否处于可以接受邀约的状态。如果连接的信令状态不是“稳定”，或者连接的我们这一端已经开始发出自己的邀约，那么我们就需要注意邀约碰撞。
```suggestion
如果我们收到了 `description`，我们就会准备对收到的邀约或答复做出回应。首先，我们要检查是否处于可以接受邀约的状态。如果连接的信令状态不是 `stable`，或者连接的我们这一端已经开始发出自己的邀约，那么我们就需要注意邀约冲突。
```

2024-06-04 03:10 UTC, tianyeeT commented
感谢 @JasonLamv-t

2024-06-04 06:56 UTC, JasonLamv-t commented
@tianyeeT 我先将这个 PR 转为 draft，如果你完成了检查并准备好进行审查后，请转为 ready to review 并重新请求我的审查

2024-07-16 02:51 UTC, JasonLamv-t approved these changes
Sorry for the late, 🙏🏼 LGTM. Thank you! 👍🏼

2024-07-16 05:35 UTC, yin1999 approved these changes

2024-07-16 05:37 UTC, merged