add ru translate for transfercontroltooffscreen page
mdn/translated-content pull request #208
Opened 2021-03-18 04:23 UTC by mirexdoors

Тут есть вопрос по поводу "frame". Насколько корректно его переводить? Возможно, стоит добавить в глоссарий?

2021-03-18 16:53 UTC, Saionaro commented
@mirexdoors В целом у веб-стандартов вот есть закрепленный перевод для [keyframe - ключевой кадр](https://github.com/web-standards-ru/dictionary/blob/master/dictionary.md#keyframe). Есть ощущение, что правильнее переводить именно как "кадр".

2021-03-18 17:14 UTC, mirexdoors commented
> @mirexdoors В целом у веб-стандартов вот есть закрепленный перевод для [keyframe - ключевой кадр](https://github.com/web-standards-ru/dictionary/blob/master/dictionary.md#keyframe). Есть ощущение, что правильнее переводить именно как "кадр".

@Saionaro Да, я видел это. Но меня смутило, что там даётся именно перевод keyframe, то есть в контексте цсс-анимаций. Поэтому я и вынес этот вопрос :) Но вообще,  тоже не против "кадров"

2021-03-18 17:22 UTC, lex111 commented
Согласен, в контексте канваса "frame" лучше переводить как "кадр", а не "фрейм".

2021-03-18 17:29 UTC, mirexdoors commented
@Saionaro @lex111 ок, спасибо, исправил это.

2021-03-21 12:41 UTC, myshov requested changes
Прошу прощения за тормоза. Только сегодня получилось развернуть среду. Есть пара замечаний, но в целом всё ок

2021-03-21 12:41 UTC, myshov commented on files/ru/web/api/htmlcanvaselement/transfercontroltooffscreen/index.html
> +    передаёт управление объектом {{domxref("OffscreenCanvas")}} либо в основной поток, либо в {{domxref("Worker")}}.</p>
```suggestion
    передаёт управление объекту {{domxref("OffscreenCanvas")}}, который может использоваться либо в основном потоке, либо в {{domxref("Worker")}}.</p>
```

2021-03-21 12:41 UTC, myshov commented on files/ru/web/api/htmlcanvaselement/transfercontroltooffscreen/index.html
> +<p>{{domxref("OffscreenCanvas")}} объект.</p>
```suggestion
<p>Объект {{domxref("OffscreenCanvas")}}.</p>
```

2021-03-21 12:42 UTC, myshov commented on files/ru/web/api/htmlcanvaselement/transfercontroltooffscreen/index.html
> +<p>{{domxref("OffscreenCanvas")}} объект.</p>
Это некритично, но имхо так более по-русски звучит :)

2021-03-21 12:52 UTC, lex111 commented on files/ru/web/api/htmlcanvaselement/transfercontroltooffscreen/index.html
> +<p>{{domxref("OffscreenCanvas")}} объект.</p>
Кстати да, и это на самом деле критично, потому что в русском это не согласуется совсем, так что нужно менять порядок слов. Добавлю в существующее руководство несколько ресурсов по переводу, чтобы те, кому это интересно, могли лучше переводить.

2021-03-22 02:43 UTC, mirexdoors commented on files/ru/web/api/htmlcanvaselement/transfercontroltooffscreen/index.html
> +<p>{{domxref("OffscreenCanvas")}} объект.</p>
@lex111 спасибо, буду благодарен)

2021-03-22 04:43 UTC, merged

2021-03-22 04:43 UTC, myshov commented
🔥