docs(KO): Window.unload 이벤트의 문서를 최신화한다
mdn/translated-content pull request #20849
Opened 2024-05-26 06:27 UTC by C17AN

### Description

- [Window: unload](https://developer.mozilla.org/ko/docs/Web/API/Window/unload_event) 이벤트 문서의 한글 번역을 최신화합니다.

### Motivation

- ₩unload₩ 이벤트는 [deprecate가 예정되어 있는데요](https://ui.toast.com/posts/ko_chrome_report_202405#%EF%B8%8F-unload-%EC%9D%B4%EB%B2%A4%ED%8A%B8-%EC%A7%80%EC%9B%90-%EC%A4%91%EB%8B%A8-), 해당 내용이 한글 문서에는 반영되지 않은 것 같아 문서를 최신화합니다.

### Additional details

### Related issues and pull requests

- [SourceCommit 링크](https://github.com/mdn/content/blob/f2175c4c2cf9de232ec9b2e1c395903d53ea24a0/files/en-us/web/api/window/unload_event/index.md)

- [MDN 원문 링크](https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event)

2024-06-02 07:44 UTC, hochan222 requested changes
@C17AN 님 안녕하세요.

고생 정말 많으셨습니다! 

몇 가지 리뷰 남겨두었습니다. 확인 부탁드립니다!

2024-06-02 07:44 UTC, hochan222 commented on files/ko/web/api/window/unload_event/index.md
> +> **경고:** 개발자들은 이 이벤트의 사용을 피해야 합니다. 아래의 "사용 주의 사항"을 참고하세요.
```suggestion
> **경고:** 개발자들은 이 이벤트의 사용을 피해야 합니다. 아래의 "사용 일람"을 참고하세요.
```

[용어 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md#section-title)에 따라 사용 일람으로 변경 부탁드립니다~!

2024-06-02 07:44 UTC, hochan222 commented on files/ko/web/api/window/unload_event/index.md
> +## 용법
```suggestion
## 구문
```

2024-06-02 07:44 UTC, hochan222 commented on files/ko/web/api/window/unload_event/index.md
> +{{domxref("EventTarget.addEventListener", "addEventListener()")}}와 같은 메서드에서 이벤트 이름을 사용하거나, 이벤트 핸들러를 설정해 사용합니다.
```suggestion
{{domxref("EventTarget.addEventListener", "addEventListener()")}}와 같은 메서드에서 이벤트 이름을 사용하거나, 이벤트 처리기를 설정해 사용합니다.
```

- https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md#section-title

2024-06-02 07:44 UTC, hochan222 commented on files/ko/web/api/window/unload_event/index.md
> +`Window` 인터페이스 외에도, 이벤트 핸들러 속성 `onunload` 는 다음 대상에서도 사용할 수 있습니다.
```suggestion
## 이벤트 처리기 별칭

`Window` 인터페이스 외에도, 이벤트 처리기 속성 `onunload` 는 다음 대상에서도 사용할 수 있습니다.
```

2024-06-02 07:44 UTC, hochan222 commented on files/ko/web/api/window/unload_event/index.md
> +`unload` 이벤트와 관련된 문제에 대한 자세한 내용은 [페이지 수명 주기 API](https://developer.chrome.com/blog/page-lifecycle-api/#the-unload-event) 가이드를 참조하세요.
```suggestion
`unload` 이벤트와 관련된 문제에 대한 자세한 내용은 [페이지 수명 주기 API](https://developer.chrome.com/blog/page-lifecycle-api/#the-unload-event) 안내서를 참조하세요.
```

2024-06-02 12:12 UTC, C17AN commented on files/ko/web/api/window/unload_event/index.md
> +> **경고:** 개발자들은 이 이벤트의 사용을 피해야 합니다. 아래의 "사용 주의 사항"을 참고하세요.
아하! 용어 안내서가 있었군요!
어쩐지 [번역 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md)에 용어 가이드가 너무 적은게 이상했는데, 알려주셔서 감사합니다! 🙂

2024-06-02 12:14 UTC, C17AN commented on files/ko/web/api/window/unload_event/index.md
> +{{domxref("EventTarget.addEventListener", "addEventListener()")}}와 같은 메서드에서 이벤트 이름을 사용하거나, 이벤트 핸들러를 설정해 사용합니다.
"처리기" 로 번역한다는 용어 규정이 있었군요!
짚어주셔서 감사합니다! 🙂

2024-06-02 12:19 UTC, C17AN commented
안녕하세요, @hochan222 님!
본업으로 바쁘신 와중에도 피드백을 남겨주셔서 감사드립니다!

이전부터 [번역 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md#%EB%B2%88%EC%97%AD-%EC%95%88%EB%82%B4%EC%84%9C)에 용어집이 없는 것에 살짝 의아함을 느끼고 있었는데, 덕분에 용어집이 있다는 것을 알게 됐네요!

앞으로 기여할 때는 용어집의 안내를 따라 잘 번역하도록 하겠습니다 🙂
리뷰해 주시느라 고생 많으셨습니다!

2024-06-03 01:31 UTC, hochan222 approved these changes
@C17AN 님 안녕하세요.

빠르게 반영해 주셔서 감사합니다.

> 이전부터 [번역 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md#%EB%B2%88%EC%97%AD-%EC%95%88%EB%82%B4%EC%84%9C)에 용어집이 없는 것에 살짝 의아함을 느끼고 있었는데, 덕분에 용어집이 있다는 것을 알게 됐네요!

https://github.com/mdn/translated-content/tree/main/docs/ko 페이지를 먼저 접근하는것을 기대했는데, translation-guide.md를 먼저 접근하셨군요..! 혹시 접근 경로를 알 수 있을까요?

용어집은 일관성과 조금 더 나은 번역을 위한 안내로 언제든지 좋은 의견 있으면 이슈 및 PR 생성 후 제안 주셔도 좋습니다! 

고생 많으셨습니다. 좋은 하루 보내세요 :)

2024-06-03 01:32 UTC, merged

2024-06-03 02:07 UTC, C17AN commented
참고차 공유드리면 저는 제일 처음 [이 이슈](https://github.com/mdn/translated-content/issues/827)를 통해 [문서 번역 가이드](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md) 로 도달했던 것 같아요!

<img width="1903" alt="image" src="https://github.com/mdn/translated-content/assets/26535030/91532e60-371d-45a0-b9b2-04b255cd4160">

번역 가이드에 용어집 링크를 명시적으로 추가해도 좋을 것 같은데, 괜찮으시다면 이것도 PR로 올려 보도록 하겠습니다~!