[zh-cn]: create the translation of `element/menclose`
mdn/translated-content pull request #20842
Opened 2024-05-26 01:59 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests
#20746

2024-05-30 12:15 UTC, yin1999 reviewed
请把添加的所有图片都删掉

2024-06-03 07:01 UTC, JasonLamv-t requested changes
Need improvements.

2024-06-03 07:06 UTC, yin1999 reviewed
定义列表格式，包括表格内容的翻译都是仍需完善的，我先转草稿了，回头由 @JasonLamv-t  继续审查内容

2024-06-03 09:11 UTC, JasonLamv-t requested changes
Please translate the description column in the table.

2024-06-03 09:16 UTC, yin1999 commented on files/zh-cn/web/mathml/element/menclose/index.md
> +  - ：以空格分隔的符号列表，用于应用于子元素。这些符号将分别绘制，好像其他符号不存在一样，因此可能会重叠。可能的值有：
```suggestion
  - : 以空格分隔的符号列表，用于应用于子元素。这些符号将分别绘制，好像其他符号不存在一样，因此可能会重叠。可能的值有：
```

2024-06-03 10:29 UTC, yin1999 commented on files/zh-cn/web/mathml/element/menclose/index.md
> +  - ：以空格分隔的符号列表，用于应用于子元素。这些符号将分别绘制，好像其他符号不存在一样，因此可能会重叠。可能的值有：
怎么又把它改回去了，请注意[定义列表的格式](https://developer.mozilla.org/zh-CN/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN#%E5%AE%9A%E4%B9%89%E5%88%97%E8%A1%A8)

```suggestion
  - : 以空格分隔的符号列表，用于应用于子元素。这些符号将分别绘制，好像其他符号不存在一样，因此可能会重叠。可能的值有：
```

2024-06-03 10:37 UTC, tianyeeT commented on files/zh-cn/web/mathml/element/menclose/index.md
> +  - ：以空格分隔的符号列表，用于应用于子元素。这些符号将分别绘制，好像其他符号不存在一样，因此可能会重叠。可能的值有：
sorry，当时本地拉的不是最新的分支。我习惯在本地format一遍再直接复制到github上面。
是不是可以理解成中文的双引号时后面是跟着中文的冒号。

2024-06-03 14:25 UTC, yin1999 commented on files/zh-cn/web/mathml/element/menclose/index.md
> +  - ：以空格分隔的符号列表，用于应用于子元素。这些符号将分别绘制，好像其他符号不存在一样，因此可能会重叠。可能的值有：
定义列表的格式就是固定的，必须是以下格式（标点也必须是半角的）：

```md
- 术语名称
  - : 术语描述
```

这里的 `  - :` 是**固定前缀**（不能替换任意字符、不能改动空格数量）

2024-06-03 14:29 UTC, yin1999 commented
> 我习惯在本地format一遍再直接复制到github上面。

尝试一下直接在本地提交（先 pull 再修改，然后再提交），我们建议使用的编辑器是 VS Code，在本地配置好 git、Node.js 和 VS Code 以后。可以直接在 VS Code 里面创建新的分支和文件修改。

比如要对当前 PR 的文档内容做出更多修改，就只要在本地切换到与当前 PR 对应的分支，提交修改，然后推送到 GitHub，即可。

MDN 文档：https://developer.mozilla.org/zh-CN/docs/Learn/Tools_and_testing/GitHub

2024-06-03 15:07 UTC, tianyeeT commented
> > 我习惯在本地format一遍再直接复制到github上面。
> 
> 尝试一下直接在本地提交（先 pull 再修改，然后再提交），我们建议使用的编辑器是 VS Code，在本地配置好 git、Node.js 和 VS Code 以后。可以直接在 VS Code 里面创建新的分支和文件修改。
> 
> 比如要对当前 PR 的文档内容做出更多修改，就只要在本地切换到与当前 PR 对应的分支，提交修改，然后推送到 GitHub，即可。
> 
> MDN 文档：https://developer.mozilla.org/zh-CN/docs/Learn/Tools_and_testing/GitHub



> > 我习惯在本地format一遍再直接复制到github上面。
> 
> 尝试一下直接在本地提交（先 pull 再修改，然后再提交），我们建议使用的编辑器是 VS Code，在本地配置好 git、Node.js 和 VS Code 以后。可以直接在 VS Code 里面创建新的分支和文件修改。
> 
> 比如要对当前 PR 的文档内容做出更多修改，就只要在本地切换到与当前 PR 对应的分支，提交修改，然后推送到 GitHub，即可。
> 
> MDN 文档：https://developer.mozilla.org/zh-CN/docs/Learn/Tools_and_testing/GitHub

非常感谢！

2024-06-03 17:31 UTC, JasonLamv-t approved these changes
LGTM. Thank you! @tianyeeT @yin1999 ❤️

2024-06-03 17:32 UTC, merged