[zh-cn]: create the translation of `element/mpadded`
mdn/translated-content pull request #20852
Opened 2024-05-26 07:50 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests
#20746

2024-06-01 08:27 UTC, yin1999 requested changes
和 #20847 类似，这些问题请先自己处理一下。还有其他的几个 PR 也是，请先修正（我先标记为“草稿”了，修好后再转“可供审阅”）。

2024-06-01 12:23 UTC, yin1999 commented on files/zh-cn/web/mathml/element/mpadded/index.md
> +**`<mpadded>`** 这个 [MathML](/zh-CN/docs/Web/MathML) 元素用于添加额外的填充，并设置封闭内容的位置和大小的一般调整。
padding 与 [CSS padding 属性](https://developer.mozilla.org/zh-CN/docs/Web/CSS/padding)对应，翻译为“内边距”吧（然后把“这个”去掉）

```suggestion
**`<mpadded>`** [MathML](/zh-CN/docs/Web/MathML) 元素用于添加额外的内边距，并设置封闭内容的位置和大小的一般调整。
```

2024-06-01 12:23 UTC, yin1999 commented on files/zh-cn/web/mathml/element/mpadded/index.md
> +   - 一个[namedspace constant](/zh-CN/docs/Web/MathML/Values#常数)。指定值被解释为 α 乘以常量。
```suggestion
   - 一个[单位](/zh-CN/docs/Web/MathML/Values#单位)。指定值的解释方式与旧版 MathML 长度相同。
   - 一个[命名空间常量](/zh-CN/docs/Web/MathML/Values#常数)。指定值被解释为 α 乘以常量。
```

2024-06-01 12:23 UTC, yin1999 commented on files/zh-cn/web/mathml/element/mpadded/index.md
> +{{ EmbedLiveSample('示例', 700, 200) }}
有没有发现两个示例重叠在一起了：

![image](https://github.com/mdn/translated-content/assets/15844309/ed19c641-2e28-47db-8f87-fc4405d8b3d2)

这就是我们为什么要强调[“注意一并修改运行实例宏的第一个参数为相对应的中文标题”](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md#%E7%BF%BB%E8%AF%91%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81%E5%9D%97)的原因。

```suggestion
{{ EmbedLiveSample('尺寸和偏移', 700, 200) }}
```

2024-06-01 12:23 UTC, yin1999 commented on files/zh-cn/web/mathml/element/mpadded/index.md
> +{{ EmbedLiveSample('示例', 700, 200) }}
```suggestion
{{ EmbedLiveSample('旧版语法', 700, 200) }}
```

2024-06-01 12:23 UTC, yin1999 commented on files/zh-cn/web/mathml/element/mpadded/index.md
> +  <!-- 以一个长度增加 -->
```suggestion
  <!-- 增加一定的长度 -->
```

2024-06-01 12:30 UTC, tianyeeT commented on files/zh-cn/web/mathml/element/mpadded/index.md
> +{{ EmbedLiveSample('示例', 700, 200) }}
谢谢解答。明白了，以后在翻译的时候会注意。重叠的原因是因为我把两个名字都叫做”示例“导致的嘛。

2024-06-01 12:32 UTC, tianyeeT commented on files/zh-cn/web/mathml/element/mpadded/index.md
> +{{ EmbedLiveSample('示例', 700, 200) }}
我懂了，它渲染拿代码是根据那一章的标题拿的。

2024-06-01 12:39 UTC, yin1999 approved these changes

2024-06-01 12:40 UTC, yin1999 commented on files/zh-cn/web/mathml/element/mpadded/index.md
> +{{ EmbedLiveSample('旧版语法', 700, 200) }}
```suggestion
{{ EmbedLiveSample('旧版语法_2', 700, 200) }}
```

2024-06-01 12:43 UTC, merged

2024-06-02 14:29 UTC, mo7mda7 reviewed
<span style="caret-color: rgb(214, 114, 32); color: rgb(214, 114, 32); font-family: arial, helvetica, clean, sans-serif; font-size: 14px; font-style: normal; font-variant-caps: normal; font-weight: 700; letter-spacing: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: 100%; -webkit-text-stroke-width: 0px; background-color: rgb(255, 242, 231); text-decoration: none; display: inline !important; float: none;">Invalid Login Credentials</span>

The CSS code you provided seems to be a styling for displaying the text "Invalid Login Credentials" in a specific style. However, it is important to note that this code snippet alone does not handle the functionality of validating login credentials. 

To handle the validation of login credentials, you would typically use JavaScript along with CSS. JavaScript can be used to check the entered credentials against a database or perform other validation logic. CSS can then be used to style the form elements based on the validation results.

If you are looking for CSS pseudo-classes related to form validation, there are a few options available. One such pseudo-class is `:invalid`, which represents form elements or input fields that have failed validation [[1]](https://developer.mozilla.org/ja/docs/Web/CSS/:invalid). You can use this pseudo-class to apply specific styles to invalid input fields, such as changing the background color to pink.

Here's an example of how you can use the `:invalid` pseudo-class to style invalid input fields:

```css
input:invalid {
  background-color: pink;
}
```

This CSS rule will apply the specified background color to any invalid input field. You can customize the styles according to your needs.

It's worth mentioning that the `:invalid` pseudo-class is just one of the pseudo-classes related to form validation. There are other pseudo-classes like `:required`, `:optional`, and `:valid` that you can use to style form elements based on their validation status [[1]](https://developer.mozilla.org/ja/docs/Web/CSS/:invalid).

---
Learn more:
1. [:invalid - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/:invalid)
2. [:user-invalid (:-moz-ui-invalid) - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/:user-invalid)
3. [:user-invalidの魅力を伝えたい](https://zenn.dev/kyoheyee/articles/5867b2389ac635)