[ko] translate /ko/learn/html/howto/index.md
mdn/translated-content pull request #20869
Opened 2024-05-26 11:16 UTC by sqaurelu

### Description

/ko/learn/howto index.md 파일 번역했습니다.

### Related issues and pull requests

- [MDN 원문 링크](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto)

2024-05-26 22:48 UTC, wisedog requested changes

2024-05-26 22:48 UTC, wisedog commented on files/ko/learn/html/howto/index.md
> +---
내용은 이상이 없습니다. `l10n` 태그만 넣어주시면 머지 가능합니다. 
참고: https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md

2024-05-27 09:41 UTC, sqaurelu commented on files/ko/learn/html/howto/index.md
> +---
리뷰 반영했습니다!

2024-05-29 22:26 UTC, wisedog approved these changes
LGTM!

2024-05-29 22:26 UTC, merged