[zh-cn]: create the translation of `global_attributes/displaystyle`
mdn/translated-content pull request #20876
Opened 2024-05-26 13:39 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests
#20746

2024-05-28 03:36 UTC, JasonLamv-t requested changes
Some suggtions for your reference.

2024-05-28 03:36 UTC, JasonLamv-t commented on files/zh-cn/web/mathml/global_attributes/displaystyle/index.md
> +**`displaystyle`** [全局属性](/zh-CN/docs/Web/MathML/Global_attributes) 是一个布尔值，用于设置 MathML 元素的 [math-style](/zh-CN/docs/Web/CSS/math-style)。
```suggestion
**`displaystyle`** [全局属性](/zh-CN/docs/Web/MathML/Global_attributes)是一个布尔值，用于设置 MathML 元素的 [math-style](/zh-CN/docs/Web/CSS/math-style)。
```

2024-05-28 03:36 UTC, JasonLamv-t commented on files/zh-cn/web/mathml/global_attributes/displaystyle/index.md
> +在这个示例中，使用 [munder](/zh-CN/docs/Web/MathML/Element/munder) 元素将脚本 "A" 附加到基础的 "∑" 上。默认情况下，求和符号是以从其父元素继承的 [font-size](/zh-CN/docs/Web/CSS/font-size) 渲染的，并且 A 作为缩小的下标。通过显式设置 `displaystyle="true"` 属性，求和符号将
```suggestion
在这个示例中，使用 [munder](/zh-CN/docs/Web/MathML/Element/munder) 元素将脚本“A”附加到基础的“∑”上。默认情况下，求和符号是以从其父元素继承的[字体大小](/zh-CN/docs/Web/CSS/font-size)渲染的，并且 A 作为缩小的下标。通过显式设置 `displaystyle="true"` 属性，求和符号将会变大，并且“A”变成一个下标。
```

2024-05-28 03:36 UTC, JasonLamv-t commented on files/zh-cn/web/mathml/global_attributes/displaystyle/index.md
> +### 可选值
```suggestion
### 值
```

2024-05-28 03:36 UTC, JasonLamv-t commented on files/zh-cn/web/mathml/global_attributes/displaystyle/index.md
> +- 所有 [全局属性](/zh-CN/docs/Web/MathML/Global_attributes)
```suggestion
- 所有[全局属性](/zh-CN/docs/Web/MathML/Global_attributes)
```

2024-05-28 12:49 UTC, yin1999 commented on files/zh-cn/web/mathml/global_attributes/displaystyle/index.md
> +**`displaystyle`** [全局属性](/zh-CN/docs/Web/MathML/Global_attributes)是一个布尔值，用于设置 MathML 元素的 [math-style](/zh-CN/docs/Web/CSS/math-style)。
请等待 #20679 的确定

```suggestion
**`displaystyle`** [全局属性](/zh-CN/docs/Web/MathML/Global_attributes)是一个用于设置 MathML 元素的 [math-style](/zh-CN/docs/Web/CSS/math-style) 的布尔值。
```

2024-06-16 06:02 UTC, tianyeeT commented
@yin1999 @JasonLamv-t @jasonren0403 :
Hi, is there anyone available to review this PR, and then we close the issue #20746.

2024-06-16 06:12 UTC, JasonLamv-t commented
Sorry for the late. I will review this afternoon. Thxu so mcuh.

2024-06-16 08:06 UTC, JasonLamv-t approved these changes
LGTM. Thank you for you patience.

2024-06-16 08:06 UTC, merged