[zh-cn]: update the translation of `example/pythagorean_theorem`
mdn/translated-content pull request #20872
Opened 2024-05-26 11:57 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests
#20746

2024-05-28 03:47 UTC, JasonLamv-t requested changes
Needs some improments

2024-05-28 03:47 UTC, JasonLamv-t commented on files/zh-cn/web/mathml/examples/mathml_pythagorean_theorem/index.md
>  title: 证明毕达哥拉斯定理
```suggestion
title: 证明勾股定理
```

2024-05-28 03:47 UTC, JasonLamv-t commented on files/zh-cn/web/mathml/examples/mathml_pythagorean_theorem/index.md
> +现在我们将证明[毕达哥拉斯定理](https://zh.wikipedia.org/wiki/勾股定理)：
```suggestion
现在我们将证明[勾股定理](https://zh.wikipedia.org/wiki/勾股定理)：
```

2024-05-28 03:47 UTC, JasonLamv-t commented on files/zh-cn/web/mathml/examples/mathml_pythagorean_theorem/index.md
> +即，如果 a 和 b 是直角三角形的两条腿，c 是斜边，那么
```suggestion
即，如果 a 和 b 是直角三角形的两条直角边，c 是斜边，那么
```

2024-05-28 03:47 UTC, JasonLamv-t commented on files/zh-cn/web/mathml/examples/mathml_pythagorean_theorem/index.md
> +**证明：** 我们可以代数地证明这个定理，通过展示在[这个图形](http://www.cut-the-knot.org/pythagoras/proof31.gif)上，大正方形的面积等于内正方形（斜边的平方）的面积加上四个三角形的面积：
```suggestion
**证明：** 我们可以通过代数方式证明这个定理，即在[此图](http://www.cut-the-knot.org/pythagoras/proof31.gif)上，大正方形的面积等于内正方形（斜边的平方）的面积加上四个三角形的面积：
```

2024-05-29 03:07 UTC, yin1999 reviewed
1. 除了特殊情况，正常都不应在中文之间保留空格
2. statement 在数学中应被称为命题（命题才需要被证明）

2024-05-29 03:07 UTC, yin1999 commented on files/zh-cn/web/mathml/examples/mathml_pythagorean_theorem/index.md
> +**证明：** 我们可以通过代数方式证明这个定理，即在[此图](http://www.cut-the-knot.org/pythagoras/proof31.gif)上，大正方形的面积等于内正方形（斜边的平方）的面积加上四个三角形的面积：
```suggestion
**证明**：我们可以通过代数方式证明这个定理，即在[此图](http://www.cut-the-knot.org/pythagoras/proof31.gif)上，大正方形的面积等于内正方形（斜边的平方）的面积加上四个三角形的面积：
```

2024-05-29 03:07 UTC, yin1999 commented on files/zh-cn/web/mathml/examples/mathml_pythagorean_theorem/index.md
> +**陈述：** 在一个直角三角形中，斜边的平方等于另外两条边的平方和。
```suggestion
**命题**：在一个直角三角形中，斜边的平方等于另外两条边的平方和。
```

2024-05-29 16:30 UTC, JasonLamv-t approved these changes

2024-05-29 16:30 UTC, merged