[zh-cn]: create the translation of "Cognitive accessibility"
mdn/translated-content pull request #20896
Opened 2024-05-27 06:13 UTC by tianyeeT

…lty`

### Description

### Motivation

### Additional details

### Related issues and pull requests
#20821

2024-05-27 06:24 UTC, yin1999 requested changes

2024-05-27 06:24 UTC, yin1999 commented on files/zh-cn/web/accessibility/cognitive_accessibility/index.md
> +title: Cognitive accessibility
最近的几个PR都没翻译标题，请都更新一下（我不再一一提醒）

2024-05-27 06:35 UTC, tianyeeT commented on files/zh-cn/web/accessibility/cognitive_accessibility/index.md
> +title: Cognitive accessibility
这就去改，也该还挺多的（

2024-06-14 02:27 UTC, yin1999 approved these changes
我直接修改了一些术语的翻译，参考来源：

- https://www.w3.org/Translations/WCAG21-zh/#abstract
- https://www.chinaw3c.org/archives/2035/

2024-06-14 02:28 UTC, merged