[zh-cn]: update the translation of Document `write()` method
mdn/translated-content pull request #20901
Opened 2024-05-27 07:40 UTC by T34-active

### Description
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/write
### Related issues and pull requests
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/write/index.md
* Last commit: https://github.com/mdn/content/commit/1238ffad886924b20549d0cf3adca735cb0d074f

2024-05-27 07:41 UTC, T34-active commented on files/zh-cn/web/api/document/write/index.md
> +> **备注：** 因为 `document.write()`是写入文档**流**的，所以在已关闭（已加载）的文档上调用 `document.write()` 会自动调用 `document.open()`，[这将清空文档](/zh-CN/docs/Web/API/Document/open#备注)。
```suggestion
> **备注：** 因为 `document.write()`会向文档**流**中写入内容，所以在已关闭（已加载）的文档上调用 `document.write()` 会自动调用 `document.open()`，[这将清空文档](/zh-CN/docs/Web/API/Document/open#备注)。
```

2024-05-29 09:17 UTC, jasonren0403 requested changes
存在一些问题

2024-05-29 09:17 UTC, jasonren0403 commented on files/zh-cn/web/api/document/write/index.md
> +> **备注：** 因为 `document.write()`会向文档**流**中写入内容，所以在已关闭（已加载）的文档上调用 `document.write()` 会自动调用 `document.open()`，[这将清空文档](/zh-CN/docs/Web/API/Document/open#备注)。
[Document.open文档](https://developer.mozilla.org/zh-CN/docs/Web/API/Document/open)目前使用的锚点为“注意”，考虑下要不要一起更新那个文档

2024-05-29 09:17 UTC, jasonren0403 commented on files/zh-cn/web/api/document/write/index.md
> +> **备注：** 因为 `document.write()`会向文档**流**中写入内容，所以在已关闭（已加载）的文档上调用 `document.write()` 会自动调用 `document.open()`，[这将清空文档](/zh-CN/docs/Web/API/Document/open#备注)。
```suggestion
> **备注：** 因为 `document.write()` 会向文档**流**中写入内容，所以在已关闭（已加载）的文档上调用 `document.write()` 会自动调用 `document.open()`，[这将清空文档](/zh-CN/docs/Web/API/Document/open#备注)。
```

2024-05-29 09:17 UTC, jasonren0403 commented on files/zh-cn/web/api/document/write/index.md
> +Writing to a document that has already loaded without calling {{domxref("document.open()")}} will automatically call `document.open()`. After writing, call {{domxref("document.close()")}} to tell the
这句是不是忘记了

2024-05-29 09:17 UTC, jasonren0403 commented on files/zh-cn/web/api/document/write/index.md
> +> **备注：** **document.write()**（类似于 **document.writeIn**）在 XHTML 文档中无法正常工作（你会在控制台收到“Operation is not supported”（`NS_ERROR_DOM_NOT_SUPPORTED_ERR`）的错误）。当以 .xhtml 文件扩展名打开本地文件或任何使用 application/xhtml+xml {
```suggestion
> **备注：** **document.write()**（类似于 **document.writeln**）在 XHTML 文档中无法正常工作（你会在控制台收到“Operation is not supported”（`NS_ERROR_DOM_NOT_SUPPORTED_ERR`）的错误）。当以 .xhtml 文件扩展名打开本地文件或任何使用 application/xhtml+xml {{Glossary("MIME type", "MIME 类型")}}的文档时，就会出现这种情况。更多详细信息，请参阅 [W3C XHTML 常见问题解答](https://www.w3.org/MarkUp/2004/xhtml-faq#docwrite)。
```

2024-05-29 09:17 UTC, jasonren0403 commented on files/zh-cn/web/api/document/write/index.md
> +> **备注：** 在 [deferred](/zh-CN/docs/Web/HTML/Element/script#defer) 或 [asynchronous](/zh-CN/docs/Web/HTML/Element/script#async) 脚本中使用 `document.write()` 将被忽略，并且你会在错误控制台中收到类似于“A call to `document.write(
延迟或异步脚本

2024-05-29 09:17 UTC, jasonren0403 commented on files/zh-cn/web/api/document/write/index.md
> +> **备注：** 仅在 Edge 中，在 `document.write()` 中多次调用 {{HTMLElement("iframe")}} 会导致错误“SCRIPT70: Permission denied”。
在 iframe 中多次调用 `document.write()`

2024-05-29 09:17 UTC, jasonren0403 commented on files/zh-cn/web/api/document/write/index.md
> +> **备注：** 从版本 55 开始，当满足特定条件时，Chrome 将不会执行通过 `document.write()` 将不会执行通过 `<script>` 元素。有关详细信息，请参阅[干预 document.write()](https://developer.chrome.com/blog/removing-document-write/)。
怎么有两个“将不会执行通过”，再检查检查

2024-05-31 02:06 UTC, T34-active commented on files/zh-cn/web/api/document/write/index.md
> +> **备注：** 因为 `document.write()`会向文档**流**中写入内容，所以在已关闭（已加载）的文档上调用 `document.write()` 会自动调用 `document.open()`，[这将清空文档](/zh-CN/docs/Web/API/Document/open#备注)。
[#21046](https://github.com/mdn/translated-content/pull/21046)

2024-05-31 02:10 UTC, T34-active commented on files/zh-cn/web/api/document/write/index.md
> +> **备注：** 在 [deferred](/zh-CN/docs/Web/HTML/Element/script#defer) 或 [asynchronous](/zh-CN/docs/Web/HTML/Element/script#async) 脚本中使用 `document.write()` 将被忽略，并且你会在错误控制台中收到类似于“A call to `document.write(
```suggestion
> **备注：** 在[延迟](/zh-CN/docs/Web/HTML/Element/script#defer)或[异步](/zh-CN/docs/Web/HTML/Element/script#async)脚本中使用 `document.write()` 将被忽略，并且你会在错误控制台中收到类似于“A call to `document.write()` from an asynchronously-loaded external script was ignored”的消息。
```

2024-05-31 02:10 UTC, T34-active commented on files/zh-cn/web/api/document/write/index.md
> +> **备注：** 仅在 Edge 中，在 `document.write()` 中多次调用 {{HTMLElement("iframe")}} 会导致错误“SCRIPT70: Permission denied”。
```suggestion
> **备注：** 仅在 Edge 中，在 {{HTMLElement("iframe")}} 中多次调用  `document.write()` 会导致错误“SCRIPT70: Permission denied”。
```

2024-05-31 02:10 UTC, T34-active commented on files/zh-cn/web/api/document/write/index.md
> +> **备注：** 从版本 55 开始，当满足特定条件时，Chrome 将不会执行通过 `document.write()` 将不会执行通过 `<script>` 元素。有关详细信息，请参阅[干预 document.write()](https://developer.chrome.com/blog/removing-document-write/)。
```suggestion
> **备注：** 从 55 版本开始，当满足特定条件时，Chrome 将不会执行通过 `<script>` 元素中的 `document.write()` 。有关详细信息，请参阅[干预 document.write()](https://developer.chrome.com/blog/removing-document-write/)。
```

2024-05-31 02:10 UTC, T34-active commented on files/zh-cn/web/api/document/write/index.md
> +Writing to a document that has already loaded without calling {{domxref("document.open()")}} will automatically call `document.open()`. After writing, call {{domxref("document.close()")}} to tell the
```suggestion
在未调用 {{domxref("document.open()")}} 的情况下，向已加载的文档写入内容将自动调用 `document.open()`。写入后，调用 {{domxref("document.close()")}} 告诉浏览器完成页面加载。
```

2024-05-31 08:16 UTC, jasonren0403 approved these changes

2024-05-31 08:20 UTC, merged