[zh-cn]: create the translation of `colors_and_luminance`
mdn/translated-content pull request #20907
Opened 2024-05-27 12:40 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests
#20821

2024-05-29 02:20 UTC, jasonren0403 requested changes
“适应性”章节之前的 review

2024-05-29 02:20 UTC, jasonren0403 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +如前所述，[CSS 颜色模块](/zh-CN/docs/Web/CSS/CSS_colors)包括添加额外的颜色空间，包括[`lch()`](/zh-CN/docs/Web/CSS/color_value/lch) 和[`oklch()`](/zh-CN/docs/Web/CSS/color_value/oklch)函数颜色记法以及[`lab()`](/zh-CN/docs/Web/CSS/co
```suggestion
如前所述，[CSS 颜色模块](/zh-CN/docs/Web/CSS/CSS_colors)包括添加额外的颜色空间，包括 [`lch()`](/zh-CN/docs/Web/CSS/color_value/lch) 和 [`oklch()`](/zh-CN/docs/Web/CSS/color_value/oklch) 函数颜色记法以及 [`lab()`](/zh-CN/docs/Web/CSS/color_value/lab) 和 [`oklab()`](/zh-CN/docs/Web/CSS/color_value/oklab) 颜色坐标系统，可以指定任何可见颜色。尽管如此，由于其普及性，sRGB 仍然是默认和首选的可访问性颜色空间。
```

2024-05-29 02:20 UTC, jasonren0403 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +然而，在涉及到可访问性的地方，标准和指南目前主要是使用 sRGB 颜色空间，尤其是在涉及颜色对比度比率时。
```suggestion
然而，在涉及到无障碍的地方，标准和指南目前主要是使用 sRGB 颜色空间，尤其是在涉及颜色对比度比率时。
```

2024-05-29 02:20 UTC, jasonren0403 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +{{domxref('Window.getComputedStyle()')}} 方法使用 RGB 十进制参考刻度或通过`color(srgb...)`返回值。例如，对设置了`background-color: #ff0000`的`<div>`调用`Window.getComputedStyle()`会将计算后的背景颜色返回为`rgb(255 0 0)` —— RGB 十进制参考。但是，当[使用
```suggestion
{{domxref('Window.getComputedStyle()')}} 方法使用 RGB 十进制参考刻度或通过 `color(srgb...)` 返回值。例如，对设置了 `background-color: #ff0000` 的 `<div>` 调用 `Window.getComputedStyle()` 将会返回背景颜色的计算值 `rgb(255 0 0)` —— RGB 十进制参考。但是，当[使用相对颜色](/zh-CN/docs/Web/CSS/CSS_colors/Relative_colors)时（例如 `background-color: rgb(from blue 255 0 0)`）时，调用 `Window.getComputedStyle()` 将返回背景颜色的计算值 `color(srgb 1 0 0)`。由于与计算机硬件相关联，`Window.getComputedStyle()` 以 RGB 为单位测量颜色，而不是人眼对颜色的感知。
```

2024-05-29 02:20 UTC, jasonren0403 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +Protanopia 是一种色觉缺陷，眼睛中没有红色锥；sRGB 仍然可以通过绿色锥感知，尽管视觉较暗。Protan（红色缺失）和 Deutan（绿色缺失）缺陷都导致难以区分红色 _和_ 绿色。
```suggestion
红色盲是一种色觉缺陷，眼睛中没有红色锥；sRGB 仍然可以通过绿色锥感知，尽管视觉较暗。Protan（红色缺失）和 Deutan（绿色缺失）缺陷都导致难以区分红色*和*绿色。
```

2024-05-29 02:20 UTC, jasonren0403 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +开发者工具可以帮助在浏览器中模拟颜色视觉差异。例如，Firefox 的 Accessibility Inspector 可以在辅助功能面板中模拟 protanopia、deuteranopia、tritanopia、achromatopsia 和对比度丧失。
![image](https://github.com/mdn/translated-content/assets/40999116/a1fffeb4-edf8-4d88-9cee-21fc2f281669)

```suggestion
开发者工具可以帮助在浏览器中模拟颜色视觉差异。例如，Firefox 的“无障碍环境”可以在辅助功能面板中模拟红色盲、绿色盲、蓝色盲、全色盲和对比度丧失。
```

2024-05-29 02:20 UTC, jasonren0403 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +颜色之间的对比度（“色调”）是一个关键组成部分，但仅仅使用颜色（“色调”）是不足以创建可访问内容的。如前所述，对比度的任何计算都必须包括亮度。
```suggestion
颜色之间的对比度（“色调”）是一个关键组成部分，但仅仅使用颜色（“色调”）是不足以创建无障碍内容的。如前所述，对比度的任何计算都必须包括亮度。
```

2024-05-29 02:20 UTC, jasonren0403 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +[WCAG 对比度指南](/zh-CN/docs/Web/Accessibility/Understanding_WCAG/Perceivable#guideline_1.4_make_it_easier_for_users_to_see_and_hear_content_including_separating_foreground_from_background)将“大”文本定义为正常状态下
```suggestion
[WCAG 对比度指南](/zh-CN/docs/Web/Accessibility/Understanding_WCAG/Perceivable#guideline_1.4_make_it_easier_for_users_to_see_and_hear_content_including_separating_foreground_from_background)将“大”文本定义为正常状态下为 `18pt`（大约为 `24px`）或更大，`bold` 文本为 `14pt`（大约为 `18.7px`）的文本。指出：
```

2024-05-29 02:20 UTC, jasonren0403 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +总的来说，对于可访问性目的，对比度越大越好。这在动画中会有所改变。"更安全"的动画意味着图像的对比度较低，而不是更高。有关动画中颜色对比度的更多信息，请参见[三次闪烁或低于阈值的理解 SC 2.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html)。
```suggestion
总的来说，对于无障碍目的，对比度越大越好。这在动画中会有所改变。“更安全”的动画意味着图像的对比度较低，而不是更高。有关动画中颜色对比度的更多信息，请参见[三次闪烁或低于阈值的理解 SC 2.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html)。
```

2024-05-29 02:20 UTC, jasonren0403 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +此外，请注意图标需要足够的对比度以进行感知。请参阅[WCAG 2.1 技术 G207](https://www.w3.org/WAI/WCAG21/Techniques/general/G207)。
```suggestion
此外，请注意图标需要足够的对比度以进行感知。请参阅 [WCAG 2.1 技术 G207](https://www.w3.org/WAI/WCAG21/Techniques/general/G207)。
```

2024-05-29 02:20 UTC, jasonren0403 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +是颜色亮度的差异使我们能够看到对比度。在 WCAG 中，相对亮度被定义为“颜色空间中任何点的相对亮度，归一化为最黑的黑色为 0，最白的白色为 1”。
```suggestion
是颜色亮度的差异使我们能够看到对比度。在 WCAG 中，相对亮度被定义为“颜色空间中任何点的相对亮度，归一化为最深的黑色为 0，最浅的白色为 1”。
```

2024-05-29 02:20 UTC, jasonren0403 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +当然，这个声明是准确的，但在与 RGB 颜色空间相关的情况下使用时可能会令人困惑，因为 RGB 颜色空间是介于 0 和 255 之间的整数。白色的相对亮度为 100%，黑色的相对亮度为 0%（在大多数但不是所有文献中如此）。按照上述 W3C 标准的解释，这意味着白色，归一化为 1，将具有 RGB 值 rgb(255 255 255)，黑色，归一化为 0，则具有 RGB 值 rgb(0 0 0)。
```suggestion
当然，这个声明是准确的，但在与 RGB 颜色空间相关的情况下使用时可能会令人困惑，因为 RGB 颜色空间是介于 0 和 255 之间的整数。白色的相对亮度为 100%，黑色的相对亮度为 0%（在大多数但不是所有文献中如此）。按照上述 W3C 标准的解释，这意味着白色，归一化为 1，将具有 RGB 值 `rgb(255 255 255)`；黑色，归一化为 0，则具有 RGB 值 `rgb(0 0 0)`。请注意，黑色和白色也可以写作 `rgb(100% 100% 100%)` 和 `rgb(0% 0% 0%)`，这可能更直观。
```

2024-05-29 02:20 UTC, jasonren0403 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +在人类感知中，亮度差异比颜色差异更为重要。这一点很重要，因为亮度对比可以使即使是色盲者也能看到的内容得以开发。有了这样的理解，可以通过调整亮度来改善因亮度较低而难以看清的颜色，将这些颜色与具有对比亮度的另一种颜色放在一起。例如，NASA 对蓝色的一项有趣研究指出，这种低亮度的颜色可以通过 _注意确保足够的亮度对比_ 而变得清晰可见（来源：[与蓝色设计](https://colorusage.ar
```suggestion
在人类感知中，亮度差异比颜色差异更为重要。这一点很重要，因为亮度对比可以使即使是色盲者也能看到的内容得以开发。有了这样的理解，可以通过调整亮度来改善因亮度较低而难以看清的颜色，将这些颜色与具有对比亮度的另一种颜色放在一起。例如，NASA 对蓝色的一项有趣研究指出，这种低亮度的颜色可以通过*注意确保足够的亮度对比*而变得清晰可见（来源：[与蓝色设计](https://colorusage.arc.nasa.gov/blue_2.php)）。
```

2024-05-29 02:20 UTC, jasonren0403 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +颜色是我们对红色、黄色、绿色到蓝色的窄波段可见光的感知。然而，我们对这些不同色调的敏感程度并不相同。我们[眼睛](https://www.verywellhealth.com/eye-cones-5088699)中的光敏感细胞，称为锥体，被调整以感知某些颜色而不是其他颜色。大约 65% 的锥体对黄/绿色*最*为敏感，但也对红色有反应（我们称这些为“红色”锥体）。30% 对绿色敏感，而仅有[5%
```suggestion
颜色是我们对红色、黄色、绿色到蓝色的窄波段可见光的感知。然而，我们对这些不同色调的敏感程度并不相同。我们[眼睛](https://www.verywellhealth.com/eye-cones-5088699)中的光敏感细胞，称为锥体，被调整以感知某些颜色而不是其他颜色。大约 65% 的锥体对黄/绿色*最*为敏感，但也对红色有反应（我们称这些为“红色”锥体）。30% 对绿色敏感，而仅有 [5% 对蓝色敏感](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0144891#sec001)。虽然蓝色敏感的锥体数量远少于其他两种类型，但它们非常敏感，这在一定程度上弥补了它们数量较少的缺陷。
```

2024-05-29 02:20 UTC, jasonren0403 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +深纯蓝色与其他颜色的感知不同，因为蓝色锥体不参与亮度，并且我们拥有的蓝色锥体比红色或绿色锥体要少得多。
```suggestion
深纯蓝色与其他颜色的感知不同，因为蓝色锥体对亮度没有贡献，并且我们拥有的蓝色锥体比红色或绿色锥体要少得多。
```

2024-05-29 02:20 UTC, jasonren0403 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +对于无障碍性而言，这意味着亮度对比对文本非常重要。颜色，如色调和色彩饱和度，对于 _区分_ 项目（例如地图上的不同线条或图表中的条形）也很重要。
```suggestion
对于无障碍性而言，这意味着亮度对比对文本非常重要。颜色，如色调和色彩饱和度，对于*区分*项目（例如地图上的不同线条或图表中的条形）也很重要。
```

2024-05-29 03:28 UTC, yin1999 commented
请在 [Files changed](https://github.com/mdn/translated-content/pull/20907/files) 菜单中[一次性应用并提交建议的修改](https://docs.github.com/zh/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes)。因为你每提交一个 commit，所有的 l10n-zh 审查人员都会收到一条消息（一般为邮箱订阅）。以当前 PR 为例，我会收到几十封邮件。

2024-05-30 01:23 UTC, yin1999 reviewed
应用斜体样式或加粗样式时应始终注意一点：中文间请不要添加额外的空格。

对于斜体样式，若需要应用样式的中文内容两侧没有空白字符或者标点符号，请使用单个星号表加粗样式：

```md
应用*斜体*样式
```

如果要应用斜体样式或加粗样式的内容中有括号等标点，这些样式可能无法被正确解析，那么，请使用类似于下面的方式来避免渲染错误：

```md
**超文本标记语言**（HTML）是一种用于表示网页内容的编程语言。
```

而不是这样写：

```md
**超文本标记语言（HTML）**是一种用于表示网页内容的编程语言。
```

2024-05-30 01:23 UTC, yin1999 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +术语可能会令人困惑，因为不同的术语通常描述相同的事物。正确理解“亮度”和“饱和度”尤为重要。例如，在某些领域，“饱和度”被称为“色度”。在其他领域，“色度”和“饱和度”是两个不同的概念。HSL 颜色空间中的“L”有时被称为“亮度（Luminosity）”，而其他时候被称为“亮度（Lightness）”。即使是似乎简单的事物，如命名常见颜色，也可能存在争议。例如，“深红色”可能被一些人描述为 `#
```suggestion
术语可能会令人困惑，因为不同的术语通常描述相同的事物。正确理解“亮度”和“饱和度”尤为重要。例如，在某些领域，“饱和度”被称为“色度”。在其他领域，“色度”和“饱和度”是两个不同的概念。HSL 颜色空间中的“L”有时被称为“亮度（Luminosity）”，而其他时候被称为“亮度（Lightness）”。即使是似乎简单的事物，如命名常见颜色，也可能存在争议。例如，“深红色”可能被一些人描述为 `#990000`，而被其他人描述为 `#DC143C`。在本文中，我们将使用 W3C 在 [CSS 颜色模块第 4 版](https://www.w3.org/TR/css-color-4/)中定义的术语。
```

2024-05-30 01:23 UTC, yin1999 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +接下来的示例显示了"HSL"，代表 _色相（Hue）、饱和度（Saturation）和亮度（Lightness）_。对许多人来说，HSL 颜色值比 RGB 值更直观。由设置产生的颜色仍然处于 sRGB 颜色空间，但[`hsl()`](/zh-CN/docs/Web/CSS/color_value/hsl)是许多人的直观语法。色调调整为角度，可以使用旋钮或圆形控件轻松调整色调。请注意，HSL 颜色
考虑一下本文中的 lightness 和 luminance 是否有差别，有关斜体的标注请按我给出的方法进行修改（下一段同理）

```suggestion
接下来的示例显示了“HSL”，代表*色相*（Hue）、*饱和度*（Saturation）和*亮度*（Lightness）。对许多人来说，HSL 颜色值比 RGB 值更直观。由设置产生的颜色仍然处于 sRGB 颜色空间，但 [`hsl()`](/zh-CN/docs/Web/CSS/color_value/hsl)是许多人的直观语法。色调调整为角度，可以使用旋钮或圆形控件轻松调整色调。请注意，HSL 颜色包含*亮度*（lightness），而不是*亮度*（luminance），这是一个重要的考虑因素。
```

2024-05-30 01:23 UTC, yin1999 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +如前所述，[CSS 颜色模块](/zh-CN/docs/Web/CSS/CSS_colors)包括添加额外的颜色空间，包括 [`lch()`](/zh-CN/docs/Web/CSS/color_value/lch) 和 [`oklch()`](/zh-CN/docs/Web/CSS/color_value/oklch) 函数颜色记法以及 [`lab()`](/zh-CN/docs/Web/CS
有缺少空格的地方

2024-05-30 01:23 UTC, yin1999 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +[WCAG 对比度指南](/zh-CN/docs/Web/Accessibility/Understanding_WCAG/Perceivable#guideline_1.4_make_it_easier_for_users_to_see_and_hear_content_including_separating_foreground_from_background)将“大”文本定义为正常状态下
这段涉及的 `bold` 和 `normal` 等都是字体的关键字，建议这样翻译：

```md
加粗（`bold`）
```

2024-05-30 01:23 UTC, yin1999 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +- CSS [`color`](/zh-CN/docs/Web/CSS/color) property 属性
```suggestion
- CSS [`color`](/zh-CN/docs/Web/CSS/color) 属性
```

2024-05-30 01:23 UTC, yin1999 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +- **颜色可能是文化相关的：** [颜色情感含义的跨文化研究](https://journals.sagepub.com/doi/10.1177/002202217300400201)
这样应用加粗样式（避免额外的空格）

```suggestion
- **颜色可能是文化相关的**：[颜色情感含义的跨文化研究](https://journals.sagepub.com/doi/10.1177/002202217300400201)
```

2024-05-30 01:23 UTC, yin1999 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +颜色，如色调和饱和度，可以影响我们的情绪，并增强 — 或减弱 — 我们的互动体验。
```suggestion
颜色，如色调和饱和度，可以影响我们的情绪，并增强（或减弱）我们的互动体验。
```

2024-05-30 01:23 UTC, yin1999 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +_不止一个“红色”可以被认为是“饱和”的红色。_ 例如，颜色 `#990000` 的 `hsl(0 100% 30%)` 完全饱和，但亮度较低。类似地，颜色 `#8b0000` 也具有 100% 的饱和度。
```suggestion
_不止一个“红色”可以被认为是“饱和”的红色_。例如，颜色 `#990000` 的 `hsl(0 100% 30%)` 完全饱和，但亮度较低。类似地，颜色 `#8b0000` 也具有 100% 的饱和度。
```

2024-05-30 01:23 UTC, yin1999 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +![Red Saturation from Wikimedia Commons svg saved as png Attribution: Datumizer [CC0]](320px-red_saturations.svg.png)
翻译说明的文字

2024-05-30 01:23 UTC, yin1999 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +在讨论光敏性时最经常考虑的颜色空间是 RGB、HSL 和 HSV（也称为 HSB）颜色空间。HSV 颜色空间代表 _色调_、_饱和度_ 和 _亮度_，而 HSB 的同义词代表*色调*、*饱和度*和*亮度*，在 CSS 中表示为 [`hwb()`](/zh-CN/docs/Web/CSS/color_value/hwb)，表示*色调*、*白度*和*黑度*。
```suggestion
在讨论光敏性时最经常考虑的颜色空间是 RGB、HSL 和 HSV（也称为 HSB）颜色空间。HSV 颜色空间代表*色调*、*饱和度*和*亮度*，而 HSB 的同义词代表*色调*、*饱和度*和*亮度*，在 CSS 中表示为 [`hwb()`](/zh-CN/docs/Web/CSS/color_value/hwb)，表示*色调*、*白度*和*黑度*。
```

2024-05-30 01:23 UTC, yin1999 commented on files/zh-cn/web/accessibility/understanding_colors_and_luminance/index.md
> +局部适应发生在读者所看页面上。例如，如果你有蓝色文本位于灰色“高亮”区域内，那么如果该文本位于黑色的 {{HTMLElement("div")}} 或白色的 {{HTMLElement("div")}} 中，你的眼睛会以不同的方式感知那个确切的蓝色文本，这被称为 _局部_ 适应。尽管房间的环境光线没有改变，但这种差异影响了感知文本的能力。
```suggestion
局部适应发生在读者所看页面上。例如，如果你有蓝色文本位于灰色“高亮”区域内，那么如果该文本位于黑色的 {{HTMLElement("div")}} 或白色的 {{HTMLElement("div")}} 中，你的眼睛会以不同的方式感知那个确切的蓝色文本，这被称为*局部*适应。尽管房间的环境光线没有改变，但这种差异影响了感知文本的能力。
```

2024-06-07 03:20 UTC, jasonren0403 approved these changes
👍 感谢贡献

2024-06-07 03:20 UTC, merged