[ko] Web/JavaScript/Enumerability_and_ownership_of_properties 신규 번역
mdn/translated-content pull request #20929
Opened 2024-05-28 13:07 UTC by Dawon00

기존에 한국어로 존재하지 않던 문서 [Web/JavaScript/Enumerability_and_ownership_of_properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties) 를 번역합니다.

2024-06-09 10:17 UTC, yechoi42 requested changes
안녕하세요! 기여 감사합니다. 사소한 코멘트 하나 남겨두었으니 확인 후 저를 다시 멘션해주세요 :)

2024-06-09 10:17 UTC, yechoi42 commented on files/ko/web/javascript/enumerability_and_ownership_of_properties/index.md
> +slug: Web/JavaScript/Enumerability_and_ownership_of_properties
안녕하세요! 

[문서 갱신 표시](files/ko/web/javascript/enumerability_and_ownership_of_properties/index.md)를 위해 소스 커밋 표기를 부탁드립니다.

2024-06-10 13:07 UTC, Dawon00 commented on files/ko/web/javascript/enumerability_and_ownership_of_properties/index.md
> +slug: Web/JavaScript/Enumerability_and_ownership_of_properties
안녕하세요!

요청하신 대로 문서 갱신 상태를 표시하기 위해 `sourceCommit` 메타데이터를 추가했습니다. 변경 사항을 확인하시고 추가로 수정이 필요한 부분이 있으면 알려주세요.

감사합니다!

2024-06-18 14:40 UTC, yechoi42 approved these changes

2024-06-18 14:41 UTC, merged