[zh-cn]: update the translation and add sourceCommit hash
mdn/translated-content pull request #20946
Opened 2024-05-29 02:36 UTC by T34-active

### Description
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Stmt_after_return

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Already_has_pragma

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Malformed_URI

### Related issues and pull requests

#### Stmt_after_return

* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/errors/stmt_after_return/index.md
* Last commit: https://github.com/mdn/content/commit/a71b8929628a2187794754c202ad399fe357141b

#### already_has_pragma

* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/errors/already_has_pragma/index.md
* Last commit: https://github.com/mdn/content/commit/a71b8929628a2187794754c202ad399fe357141b

#### malformed_uri

* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/errors/malformed_uri/index.md
* Last commit: https://github.com/mdn/content/commit/6d606174faaedaa5dee7b7ebd87602cd51e5dd7e

2024-05-29 04:30 UTC, PassionPenguin requested changes

2024-05-29 04:30 UTC, PassionPenguin commented on files/zh-cn/web/javascript/reference/errors/already_has_pragma/index.md
>  JavaScript 源码通常被组合和压缩，使其从服务器传递更加高效。使用了[源码映射](http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/)，调试器能够将执行的源码映射到原始的源码。有两种指派源码映射的方式，通过注释，或者对 JavaScript 设置标题。
```suggestion
JavaScript 源码通常被组合和压缩，使其从服务器传递更加高效。使用[源码映射](http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/)，调试器能够将执行的源码映射到原始的源码。有两种指派源码映射的方式，通过注释，或者对 JavaScript 设置标题。
```

2024-05-29 04:30 UTC, PassionPenguin commented on files/zh-cn/web/javascript/reference/errors/already_has_pragma/index.md
> +- 在 developer.chrome.com（2012）上的 [JavaScript 源码映射简介](https://developer.chrome.com/blog/sourcemaps/)
emm，2012是文章的时间，放在网站域名后面，有点，，怪？

```suggestion
- 在 developer.chrome.com 上的 [JavaScript 源码映射简介](https://developer.chrome.google.cn/blog/sourcemaps/)（2012）
```

2024-05-29 08:44 UTC, jasonren0403 requested changes
一些问题

2024-05-29 08:44 UTC, jasonren0403 commented on files/zh-cn/web/javascript/reference/errors/already_has_pragma/index.md
> +JavaScript 源码通常被组合和压缩，使其从服务器传递更加高效。使用[源码映射](http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/)，调试器能够将执行的源码映射到原始的源码。有两种指派源码映射的方式，通过注释，或者对 JavaScript 设置标题。
这里的header指的是HTTP标头（下文举例的 X-SourceMap 很明显是个标头），第38行同样

```suggestion
JavaScript 源码通常被组合和压缩，使其从服务器传递更加高效。使用[源码映射](http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/)，调试器能够将执行的源码映射到原始的源码。有两种指派源码映射的方式，通过注释，或者对 JavaScript 设置标头。
```

2024-05-29 08:44 UTC, jasonren0403 commented on files/zh-cn/web/javascript/reference/errors/already_has_pragma/index.md
> +- 火狐源文档中的[使用源码映射](https://firefox-source-docs.mozilla.org/devtools-user/debugger/how_to/use_a_source_map/index.html)
```suggestion
- 火狐源代码文档中的[使用源码映射](https://firefox-source-docs.mozilla.org/devtools-user/debugger/how_to/use_a_source_map/index.html)
```

2024-05-29 08:44 UTC, jasonren0403 commented on files/zh-cn/web/javascript/reference/errors/malformed_uri/index.md
示例中“高—低”短横线标点周围不应该有空格

2024-05-29 08:44 UTC, jasonren0403 commented on files/zh-cn/web/javascript/reference/errors/stmt_after_return/index.md
>  ```
```suggestion
```plain
```

2024-05-29 08:44 UTC, jasonren0403 commented on files/zh-cn/web/javascript/reference/errors/stmt_after_return/index.md
两个代码块需要更新

2024-05-31 00:59 UTC, T34-active commented on files/zh-cn/web/javascript/reference/errors/malformed_uri/index.md
> +高-低位完整的代理字符是没问题的，例如：
```suggestion
高低位完整的代理字符是没问题的，例如：
```

2024-05-31 00:59 UTC, T34-active commented on files/zh-cn/web/javascript/reference/errors/malformed_uri/index.md
> +编码操作会将每一个字符实例替换为一到四个相对应的 UTF-8 编码形式的转义序列。如果试图编码一个非高-低位完整的代理字符，将会抛出 {{jsxref("URIError")}} 错误，例如：
```suggestion
编码操作会将每一个字符实例替换为一到四个相对应的 UTF-8 编码形式的转义序列。如果试图编码一个非高低位完整的代理字符，将会抛出 {{jsxref("URIError")}} 错误，例如：
```

2024-05-31 01:46 UTC, jasonren0403 approved these changes
👍

2024-05-31 01:46 UTC, merged