[zh-cn]: update the translation of SVG `<feflood>` and `<fefunc*>` element
mdn/translated-content pull request #20948
Opened 2024-05-29 03:23 UTC by T34-active

### Description

* https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFlood
* https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFuncA
* https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFuncB
* https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFuncG
* https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFuncR

### Related issues and pull requests

#### `<feflood>`

* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/feflood/index.md
* Last commit: https://github.com/mdn/content/commit/3a1ef2abc8233835f0b0cc73afaf36e44edaf4a1

#### `<feFuncA>`

* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/fefunca/index.md
* Last commit: https://github.com/mdn/content/commit/3a1ef2abc8233835f0b0cc73afaf36e44edaf4a1

#### `<feFuncB>`

* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/fefuncb/index.md
* Last commit: https://github.com/mdn/content/commit/3a1ef2abc8233835f0b0cc73afaf36e44edaf4a1

#### `<feFuncG>`

* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/fefuncg/index.md
* Last commit: https://github.com/mdn/content/commit/3a1ef2abc8233835f0b0cc73afaf36e44edaf4a1

#### `<feFuncR>`

* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/fefuncr/index.md
* Last commit: https://github.com/mdn/content/commit/3a1ef2abc8233835f0b0cc73afaf36e44edaf4a1

2024-05-29 03:24 UTC, yin1999 requested changes

2024-05-29 03:24 UTC, yin1999 commented on files/zh-cn/web/svg/element/feflood/index.md
> +**`<feFlood>`** SVG 滤镜基元使用由 {{SVGAttr("flood-color")}} 和 {{SVGAttr("flood-opacity")}} 定义的颜色和透明度填充滤镜子区域。
滤镜原语，我在以前的 PR 中提到过

2024-05-29 03:26 UTC, T34-active reviewed
"基元" replaces "原语"

2024-05-29 03:26 UTC, T34-active commented on files/zh-cn/web/svg/element/feflood/index.md
> +**`<feFlood>`** SVG 滤镜基元使用由 {{SVGAttr("flood-color")}} 和 {{SVGAttr("flood-opacity")}} 定义的颜色和透明度填充滤镜子区域。
```suggestion
**`<feFlood>`** SVG 滤镜原语使用由 {{SVGAttr("flood-color")}} 和 {{SVGAttr("flood-opacity")}} 定义的颜色和透明度填充滤镜子区域。
```

2024-05-29 03:26 UTC, T34-active commented on files/zh-cn/web/svg/element/fefunca/index.md
> +**`<feFuncA>`** [SVG](/zh-CN/docs/Web/SVG) 滤镜基元为其 {{SVGElement("feComponentTransfer")}} 父元素输入图形的 alpha 分量定义了传递函数。
```suggestion
**`<feFuncA>`** [SVG](/zh-CN/docs/Web/SVG) 滤镜原语为其 {{SVGElement("feComponentTransfer")}} 父元素输入图形的 alpha 分量定义了传递函数。
```

2024-05-29 03:26 UTC, T34-active commented on files/zh-cn/web/svg/element/fefuncb/index.md
> +**`<feFuncB>`** [SVG](/zh-CN/docs/Web/SVG) 滤镜基元为其 {{SVGElement("feComponentTransfer")}} 父元素输入图形的蓝色分量定义了传递函数。
```suggestion
**`<feFuncB>`** [SVG](/zh-CN/docs/Web/SVG) 滤镜原语为其 {{SVGElement("feComponentTransfer")}} 父元素输入图形的蓝色分量定义了传递函数。
```

2024-05-29 03:26 UTC, T34-active commented on files/zh-cn/web/svg/element/fefuncg/index.md
> +**`<feFuncG>`** [SVG](/zh-CN/docs/Web/SVG) 滤镜基元为其 {{SVGElement("feComponentTransfer")}} 父元素输入图形的绿色分量定义了传递函数。
```suggestion
**`<feFuncG>`** [SVG](/zh-CN/docs/Web/SVG) 滤镜原语为其 {{SVGElement("feComponentTransfer")}} 父元素输入图形的绿色分量定义了传递函数。
```

2024-05-29 03:26 UTC, T34-active commented on files/zh-cn/web/svg/element/fefuncr/index.md
> +**`<feFuncR>`** [SVG](/zh-CN/docs/Web/SVG) 滤镜基元为其 {{SVGElement("feComponentTransfer")}} 父元素输入图形的红色分量定义了传递函数。
```suggestion
**`<feFuncR>`** [SVG](/zh-CN/docs/Web/SVG) 滤镜原语为其 {{SVGElement("feComponentTransfer")}} 父元素输入图形的红色分量定义了传递函数。
```

2024-06-04 01:18 UTC, yin1999 reviewed
一些建议

2024-06-04 01:18 UTC, yin1999 commented on files/zh-cn/web/svg/element/feflood/index.md
> +- [SVG 滤镜属性](/zh-CN/docs/Web/SVG/Attribute#滤镜属性)
```suggestion
- [SVG 滤镜原语属性](/zh-CN/docs/Web/SVG/Attribute#滤镜属性)
```

2024-06-04 01:18 UTC, yin1999 commented on files/zh-cn/web/svg/element/fefunca/index.md
> +- [SVG 滤镜属性](/zh-CN/docs/Web/SVG/Attribute#滤镜属性)
```suggestion
- [SVG 滤镜原语属性](/zh-CN/docs/Web/SVG/Attribute#滤镜属性)
```

2024-06-04 01:18 UTC, yin1999 commented on files/zh-cn/web/svg/element/fefuncb/index.md
> +- [SVG 滤镜属性](/zh-CN/docs/Web/SVG/Attribute#滤镜属性)
```suggestion
- [SVG 滤镜原语属性](/zh-CN/docs/Web/SVG/Attribute#滤镜属性)
```

2024-06-04 01:18 UTC, yin1999 commented on files/zh-cn/web/svg/element/fefuncb/index.md
> +- {{SVGElement("feFuncB")}}
```suggestion
- {{SVGElement("feFuncA")}}
- {{SVGElement("feFuncR")}}
```

2024-06-04 01:18 UTC, yin1999 commented on files/zh-cn/web/svg/element/fefuncg/index.md
> +- [SVG 滤镜属性](/zh-CN/docs/Web/SVG/Attribute#滤镜属性)
```suggestion
- [SVG 滤镜原语属性](/zh-CN/docs/Web/SVG/Attribute#滤镜属性)
```

2024-06-04 01:18 UTC, yin1999 commented on files/zh-cn/web/svg/element/fefuncg/index.md
> +- {{SVGElement("feFuncG")}}
```suggestion
- {{SVGElement("feFuncA")}}
- {{SVGElement("feFuncR")}}
- {{SVGElement("feFuncB")}}
```

2024-06-04 14:13 UTC, yin1999 approved these changes

2024-06-04 14:13 UTC, merged