[zh-cn]: create the translation of `shape`
mdn/translated-content pull request #20962
Opened 2024-05-29 12:55 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests
#20951

2024-05-29 15:05 UTC, yin1999 commented
上面的问题都未解决，对于内容贡献比较多的，我们始终建议在本地处理文档翻译：https://github.com/mdn/translated-content/pull/20881#issuecomment-2134413248

2024-05-29 15:11 UTC, yin1999 requested changes
麻烦对照一下英文文档的缩进，当前文档的排版肯定是不对的。[预览页面](https://pr20962.content.dev.mdn.mozit.cloud/zh-CN/docs/Web/CSS/basic-shape/shape)的定义列表并未得到正确的渲染。

![image](https://github.com/mdn/translated-content/assets/15844309/03ea89b7-838d-4d17-9bf6-67a59f5c5430)

此外，当前文档中还是有一部分空格使用的问题（例如中文之间多了空格）

2024-05-29 15:11 UTC, yin1999 commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +## 正式语法
标题的翻译请参考：https://github.com/mdn/translated-content/blob/main/docs/zh-cn/glossary.md#%E6%A0%87%E9%A2%98%E8%A1%A8%E6%A0%BC

```suggestion
## 形式语法
```

2024-05-29 15:11 UTC, yin1999 commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +- [基本形状](/zh-CN/docs/Web/CSS/CSS_shapes/Basic_shapes) 指南
翻译、空格

2024-05-31 10:19 UTC, tianyeeT commented
https://github.com/mdn/content/pull/33804
need to follow up

2024-06-16 10:46 UTC, tianyeeT commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +    平滑曲线确保形状的连续过渡，而二次曲线则不然。平滑的二次曲线使用单个控制点来保持无缝过渡，而平滑的三次曲线使用两个控制点提供更精细的过渡。
<img width="623" alt="image" src="https://github.com/mdn/translated-content/assets/146603607/f57668f0-1d70-450f-90b8-4f0b8fb37390">

2024-06-16 13:47 UTC, yin1999 commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +    平滑曲线确保形状的连续过渡，而二次曲线则不然。平滑的二次曲线使用单个控制点来保持无缝过渡，而平滑的三次曲线使用两个控制点提供更精细的过渡。
与上一行之间应有一个空行。markdown 语法要求“块”与“块”之间应使用空行隔开

2024-06-16 14:01 UTC, yin1999 commented
多了一些额外的空格，我帮你去掉了。但目前这个 PR 还有很多内容需要更改，请再仔细检查一下，存在问题的点包括：

- 内容翻译（例如 https://github.com/mdn/translated-content/pull/20962#discussion_r1619065374 指出的第一个 `css shapes` 的 shapes 没有翻译，这个请使用搜索引擎去检索关键词“CSS shapes W3C”（仅搜索简体中文内容），我们使用 W3C 的官方译名即可；还有语法部分的注释）
- 好几个 URL 的片段（即 hash 部分）都没有本地化。
- 标点符号的使用（例如：正文部分很多地方错误地使用了半角括号）

2024-06-17 02:45 UTC, tianyeeT commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +- [CSS shapes](/zh-CN/docs/Web/CSS/CSS_shapes) 模块
```suggestion
- [CSS 形状](/zh-CN/docs/Web/CSS/CSS_shapes)模块
```

2024-06-17 02:45 UTC, tianyeeT commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +    `<hv-line-command>`：指定为 `[hline | vline] [by | to] <length-percentage>`。此命令将水平 (`hline`) 或垂直 (`vline`) [LineTo 命令](/zh-CN/docs/Web/SVG/Attribute/d#lineto_path_commands)添加到形状命令列表中。使用 `hline`，从命令的起
```suggestion
    `<hv-line-command>`：指定为 `[hline | vline] [by | to] <length-percentage>`。此命令将水平（`hline`）或垂直（`vline`）[LineTo 命令](/zh-CN/docs/Web/SVG/Attribute/d#lineto_path_commands)添加到形状命令列表中。使用 `hline`，从命令的起始点绘制水平线到由 `<length-percentage>` 定义的 `x` 位置的 `to` 或 `by`。使用 `vline`，从命令的起始点绘制垂直线到由 `<length-percentage>` 定义的 `y` 位置的 `to` 或 `by`。`by` 或 `to` 关键字分别确定了“相对”或“绝对”结束点。此命令相当于 `<line-command>`，其中一个坐标值由单个 `<length-percentage>` 设置，另一个坐标值保持从其起始命令开始的不变。
```

2024-06-17 02:45 UTC, tianyeeT commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +    - `<arc-sweep>`：指示所需的弧是否是顺时针 (`cw`) 或逆时针 (`ccw`) 围绕椭圆追踪的。如果省略，这默认为 `ccw`。
```suggestion
    - `<arc-sweep>`：指示所需的弧是否是顺时针（`cw`）或逆时针（`ccw`）围绕椭圆追踪的。如果省略，这默认为 `ccw`。
```

2024-06-17 02:45 UTC, tianyeeT commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +    - `<arc-size>`：指示所需的弧是否是两个弧中较大的一个 (`large`) 或较小的一个 (`small`)。如果省略，这默认为 `small`。
```suggestion
    - `<arc-size>`：指示所需的弧是否是两个弧中较大的一个（`large`）或较小的一个（`small`）。如果省略，这默认为 `small`。
```

2024-06-17 02:45 UTC, tianyeeT commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +该例子演示了如何在 {{cssxref("clip-path")}} 属性中使用 `shape()` 函数来为剪切区域创建不同的形状。第一个形状 (`shape1`) 使用由直线定义的三角形。第二个形状 (`shape2`) 包含曲线和平滑过渡；它还展示了在 `close` 命令之后使用 `<move-command>`，从而在剪切区域中添加矩形形状。
```suggestion
该例子演示了如何在 {{cssxref("clip-path")}} 属性中使用 `shape()` 函数来为剪切区域创建不同的形状。第一个形状（`shape1`）使用由直线定义的三角形。第二个形状（`shape2`）包含曲线和平滑过渡；它还展示了在 `close` 命令之后使用 `<move-command>`，从而在剪切区域中添加矩形形状。
```

2024-06-17 02:45 UTC, tianyeeT commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +  - : 将第一个 `<shape-command>` 的起始点定义为一对坐标，这些坐标是从[参考框](/zh-CN/docs/Web/CSS/CSS_shapes/Basic_shapes#the_reference_box)的左上角测量得到的。这些坐标被指定为用空格分隔的 `<x> <y>` {{cssxref("&lt;length-percentage&gt;")}} 值，分别表示左偏
```suggestion
  - : 将第一个 `<shape-command>` 的起始点定义为一对坐标，这些坐标是从[参考框](/zh-CN/docs/Web/CSS/CSS_shapes/Basic_shapes#参考框)的左上角测量得到的。这些坐标被指定为用空格分隔的 `<x> <y>` {{cssxref("&lt;length-percentage&gt;")}} 值，分别表示左偏移和上偏移。百分比值相对于元素的参考框的宽度和高度计算。在此参数后添加逗号。
```
对应的中文文档暂未翻译

2024-06-17 02:45 UTC, tianyeeT commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +  - : 指定一个或多个逗号分隔的命令列表，用于定义形状，其语法类似于 [SVG 路径命令](/zh-CN/docs/Web/SVG/Attribute/d#path_commands)。命令包括 `<move-command>`、`<line-command>`、`<hv-line-command>`、`<curve-command>`、`<smooth-command>`、`<arc-co
```suggestion
  - : 指定一个或多个逗号分隔的命令列表，用于定义形状，其语法类似于 [SVG 路径命令](/zh-CN/docs/Web/SVG/Attribute/d#路径命令)。命令包括 `<move-command>`、`<line-command>`、`<hv-line-command>`、`<curve-command>`、`<smooth-command>`、`<arc-command>` 和 `close`。每个命令的起始点是前一个命令的结束点，形状的第一个点由 [`from <coordinate-pair>`](#from_coordinate-pair) 参数定义。
```

2024-06-17 02:45 UTC, tianyeeT commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +    `<move-command>`：指定为 `move [by | to] <coordinate-pair>`。此命令将 [MoveTo 命令](/zh-CN/docs/Web/SVG/Attribute/d#moveto_path_commands)添加到形状命令列表中。它不绘制任何内容。相反，它指定了下一个命令的起始位置。`by` 或 `to` 关键字指定 `<coordinate-
```suggestion
    `<move-command>`：指定为 `move [by | to] <coordinate-pair>`。此命令将 [MoveTo 路径命令](/zh-CN/docs/Web/SVG/Attribute/d#MoveTo_路径命令)添加到形状命令列表中。它不绘制任何内容。相反，它指定了下一个命令的起始位置。`by` 或 `to` 关键字指定 `<coordinate-pair>` 点是“相对”还是“绝对“，分别。如果 `<move-command>` 跟随 `close` 命令，则它标识了下一个形状或子路径的起始点。
```

2024-06-17 02:45 UTC, tianyeeT commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +    `<line-command>`：指定为 `line [by | to] <coordinate-pair>`。此命令将 [LineTo 命令](/zh-CN/docs/Web/SVG/Attribute/d#lineto_path_commands)添加到形状命令列表中。它从命令的起始点直线绘制到其结束点。`by` 或 `to` 关键字指定由 `<coordinate-pair>` 分
```suggestion
    `<line-command>`：指定为 `line [by | to] <coordinate-pair>`。此命令将 [LineTo 路径命令](/zh-CN/docs/Web/SVG/Attribute/d#LineTo_路径命令)添加到形状命令列表中。它从命令的起始点直线绘制到其结束点。`by` 或 `to` 关键字指定由 `<coordinate-pair>` 分别指定的结束点是“相对”还是“绝对”。
```

2024-06-17 02:45 UTC, tianyeeT commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +    `<hv-line-command>`：指定为 `[hline | vline] [by | to] <length-percentage>`。此命令将水平 (`hline`) 或垂直 (`vline`) [LineTo 命令](/zh-CN/docs/Web/SVG/Attribute/d#lineto_path_commands)添加到形状命令列表中。使用 `hline`，从命令的起
```suggestion
    `<hv-line-command>`：指定为 `[hline | vline] [by | to] <length-percentage>`。此命令将水平 (`hline`) 或垂直 (`vline`) [LineTo 路径命令](/zh-CN/docs/Web/SVG/Attribute/d#LineTo_路径命令)添加到形状命令列表中。使用 `hline`，从命令的起始点绘制水平线到由 `<length-percentage>` 定义的 `x` 位置的 `to` 或 `by`。使用 `vline`，从命令的起始点绘制垂直线到由 `<length-percentage>` 定义的 `y` 位置的 `to` 或 `by`。`by` 或 `to` 关键字分别确定了“相对”或“绝对”结束点。此命令相当于 `<line-command>`，其中一个坐标值由单个 `<length-percentage>` 设置，另一个坐标值保持从其起始命令开始的不变。
```

2024-06-17 02:45 UTC, tianyeeT commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +    `<curve-command>`：指定为 `curve [by | to] <coordinate-pair> via <coordinate-pair> [<coordinate-pair>]`。此命令将一个[贝塞尔曲线命令](/zh-CN/docs/Web/SVG/Attribute/d#cubic_bézier_curve)添加到形状命令列表中。`by` 或 `to` 关键字确定
```suggestion
    `<curve-command>`：指定为 `curve [by | to] <coordinate-pair> via <coordinate-pair> [<coordinate-pair>]`。此命令将一个[贝塞尔曲线命令](/zh-CN/docs/Web/SVG/Attribute/d#三次贝塞尔曲线)添加到形状命令列表中。`by` 或 `to` 关键字确定由第一个 `<coordinate-pair>` 指定的曲线的结束点是“相对”还是“绝对”。
```

2024-06-17 02:45 UTC, tianyeeT commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +    - 如果只提供一个 `<coordinate-pair>`，该命令会绘制一个[二次贝塞尔曲线](/zh-CN/docs/Web/SVG/Attribute/d#quadratic_bézier_curve)，它由三个点（起点、控制点和终点）定义。
```suggestion
    - 如果只提供一个 `<coordinate-pair>`，该命令会绘制一个[二次贝塞尔曲线](/zh-CN/docs/Web/SVG/Attribute/d#二次贝塞尔曲线)，它由三个点（起点、控制点和终点）定义。
```

2024-06-17 02:45 UTC, tianyeeT commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +    `<smooth-command>`：指定为 `smooth [by | to] <coordinate-pair> [via <coordinate-pair>]`。此命令将一个平滑的[贝塞尔曲线命令](/zh-CN/docs/Web/SVG/Attribute/d#cubic_bézier_curve)添加到形状命令列表中。`by` 或 `to` 关键字确定由第一个 `<coordi
```suggestion
    `<smooth-command>`：指定为 `smooth [by | to] <coordinate-pair> [via <coordinate-pair>]`。此命令将一个平滑的[贝塞尔曲线命令](/zh-CN/docs/Web/SVG/Attribute/d#三次贝塞尔曲线)添加到形状命令列表中。`by` 或 `to` 关键字确定由第一个 `<coordinate-pair>` 指定的曲线的结束点是“相对“还是”绝对“。
```

2024-06-17 02:45 UTC, tianyeeT commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +    `<arc-command>`：指定为 `arc [by | to] <coordinate-pair> of <length-percentage> [<length-percentage>] [<arc-sweep> | <arc-size> | rotate <angle>]`。此命令将一个[椭圆弧曲线命令](/zh-CN/docs/Web/SVG/Attribute/d#elli
```suggestion
    `<arc-command>`：指定为 `arc [by | to] <coordinate-pair> of <length-percentage> [<length-percentage>] [<arc-sweep> | <arc-size> | rotate <angle>]`。此命令将一个[椭圆曲线命令](/zh-CN/docs/Web/SVG/Attribute/d#椭圆曲线)添加到形状命令列表中。它在起始点和结束点之间绘制椭圆弧。`by` 或 `to` 关键字确定由第一个 `<coordinate-pair>` 指定的曲线的结束点是“相对”还是“绝对”。
```

2024-06-17 02:45 UTC, tianyeeT commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +- `shape()` 函数要求指定一个或多个 `<shape-command>`，其中每个命令使用底层的[路径命令](/zh-CN/docs/Web/SVG/Attribute/d#path_commands)，例如 [MoveTo](/zh-CN/docs/Web/SVG/Attribute/d#moveto_path_commands)、[LineTo](/zh-CN/docs/Web/S
```suggestion
- `shape()` 函数要求指定一个或多个 `<shape-command>`，其中每个命令使用底层的[路径命令](/zh-CN/docs/Web/SVG/Attribute/d#路径命令)，例如 [MoveTo](/zh-CN/docs/Web/SVG/Attribute/d#MoveTo_路径命令)、[LineTo](/zh-CN/docs/Web/SVG/Attribute/d#LineTo_路径命令) 和 [ClosePath](/zh-CN/docs/Web/SVG/Attribute/d#closepath)。
```

2024-06-17 05:10 UTC, yin1999 commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +- `shape()` 函数要求指定一个或多个 `<shape-command>`，其中每个命令使用底层的[路径命令](/zh-CN/docs/Web/SVG/Attribute/d#路径命令)，例如 [MoveTo](/zh-CN/docs/Web/SVG/Attribute/d#MoveTo_路径命令)、[LineTo](/zh-CN/docs/Web/SVG/Attribute/d#Lin
这里的有几个片段值还不对，还记得前几天我讲过的如何查找片段值的方法吗

2024-06-17 11:37 UTC, tianyeeT commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +- `shape()` 函数要求指定一个或多个 `<shape-command>`，其中每个命令使用底层的[路径命令](/zh-CN/docs/Web/SVG/Attribute/d#路径命令)，例如 [MoveTo](/zh-CN/docs/Web/SVG/Attribute/d#MoveTo_路径命令)、[LineTo](/zh-CN/docs/Web/SVG/Attribute/d#Lin
忘记了，刚搜了没找到（

2024-06-17 11:46 UTC, yin1999 commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +- `shape()` 函数要求指定一个或多个 `<shape-command>`，其中每个命令使用底层的[路径命令](/zh-CN/docs/Web/SVG/Attribute/d#路径命令)，例如 [MoveTo](/zh-CN/docs/Web/SVG/Attribute/d#MoveTo_路径命令)、[LineTo](/zh-CN/docs/Web/SVG/Attribute/d#Lin
我们在翻译指南的[翻译示例代码块](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md#%E7%BF%BB%E8%AF%91%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81%E5%9D%97)小节中给出的链接有说明如何查找片段值。下次忘了请直接到这里去找。

2024-06-19 09:31 UTC, yin1999 commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +    `<move-command>`：指定为 `move [by | to] <coordinate-pair>`。此命令将 [MoveTo 路径命令](/zh-CN/docs/Web/SVG/Attribute/d#MoveTo_路径命令)添加到形状命令列表中。它不绘制任何内容。相反，它指定了下一个命令的起始位置。`by` 或 `to` 关键字指定 `<coordinate-pair>`
```suggestion
    `<move-command>`：指定为 `move [by | to] <coordinate-pair>`。此命令将 [MoveTo 路径命令](/zh-CN/docs/Web/SVG/Attribute/d#moveto_路径命令)添加到形状命令列表中。它不绘制任何内容。相反，它指定了下一个命令的起始位置。`by` 或 `to` 关键字指定 `<coordinate-pair>` 点是“相对”还是“绝对“，分别。如果 `<move-command>` 跟随 `close` 命令，则它标识了下一个形状或子路径的起始点。
```

2024-06-19 09:31 UTC, yin1999 commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +    `<line-command>`：指定为 `line [by | to] <coordinate-pair>`。此命令将 [LineTo 路径命令](/zh-CN/docs/Web/SVG/Attribute/d#LineTo_路径命令)添加到形状命令列表中。它从命令的起始点直线绘制到其结束点。`by` 或 `to` 关键字指定由 `<coordinate-pair>` 分别指定的结束点
```suggestion
    `<line-command>`：指定为 `line [by | to] <coordinate-pair>`。此命令将 [LineTo 路径命令](/zh-CN/docs/Web/SVG/Attribute/d#lineto_路径命令)添加到形状命令列表中。它从命令的起始点直线绘制到其结束点。`by` 或 `to` 关键字指定由 `<coordinate-pair>` 分别指定的结束点是“相对”还是“绝对”。
```

2024-06-19 09:31 UTC, yin1999 commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +    `<hv-line-command>`：指定为 `[hline | vline] [by | to] <length-percentage>`。此命令将水平（`hline`）或垂直（`vline`）[LineTo 命令](/zh-CN/docs/Web/SVG/Attribute/d#lineto_path_commands)添加到形状命令列表中。使用 `hline`，从命令的起始点绘制
```suggestion
    `<hv-line-command>`：指定为 `[hline | vline] [by | to] <length-percentage>`。此命令将水平（`hline`）或垂直（`vline`）[LineTo 命令](/zh-CN/docs/Web/SVG/Attribute/d#lineto_路径命令)添加到形状命令列表中。使用 `hline`，从命令的起始点绘制水平线到由 `<length-percentage>` 定义的 `x` 位置的 `to` 或 `by`。使用 `vline`，从命令的起始点绘制垂直线到由 `<length-percentage>` 定义的 `y` 位置的 `to` 或 `by`。`by` 或 `to` 关键字分别确定了“相对”或“绝对”结束点。此命令相当于 `<line-command>`，其中一个坐标值由单个 `<length-percentage>` 设置，另一个坐标值保持从其起始命令开始的不变。
```

2024-06-19 09:32 UTC, yin1999 commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +  - : 将第一个 `<shape-command>` 的起始点定义为一对坐标，这些坐标是从[参考框](/zh-CN/docs/Web/CSS/CSS_shapes/Basic_shapes#the_reference_box)的左上角测量得到的。这些坐标被指定为用空格分隔的 `<x> <y>` {{cssxref("&lt;length-percentage&gt;")}} 值，分别表示左偏
先翻译一下，后面翻译了对应的中文文档就不用再更新了

2024-06-20 01:54 UTC, yin1999 reviewed
一些建议

2024-06-20 01:54 UTC, yin1999 commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +    `<curve-command>`：指定为 `curve [by | to] <coordinate-pair> via <coordinate-pair> [<coordinate-pair>]`。此命令将一个[贝塞尔曲线命令](/zh-CN/docs/Web/SVG/Attribute/d#三次贝塞尔曲线)添加到形状命令列表中。`by` 或 `to` 关键字确定由第一个 `<coor
```suggestion
    `<curve-command>`：指定为 `curve [by | to] <coordinate-pair> via <coordinate-pair> [<coordinate-pair>]`。此命令将一个[贝塞尔曲线命令](/zh-CN/docs/Web/SVG/Attribute/d#三次贝塞尔曲线)添加到形状命令列表中。`by` 或 `to` 关键字确定由第一个 `<coordinate-pair>` 指定的曲线的结束点是“相对”还是“绝对”。`via` 关键字指定贝塞尔曲线的控制点。
```

2024-06-20 01:54 UTC, yin1999 commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +    - 如果提供两个 `<coordinate-pair>` 值，该命令会绘制一个三次贝塞尔曲线，它由四个点（起点、两个控制点和终点）定义。
```suggestion
    - 如果只提供一个 `<coordinate-pair>`，该命令会绘制一条[二次贝塞尔曲线](/zh-CN/docs/Web/SVG/Attribute/d#二次贝塞尔曲线)，它由三个点（起点、控制点和终点）定义。
    - 如果提供两个 `<coordinate-pair>` 值，该命令会绘制一条三次贝塞尔曲线，它由四个点（起点、两个控制点和终点）定义。
```

2024-06-20 01:54 UTC, yin1999 commented on files/zh-cn/web/css/basic-shape/shape/index.md
> +该示例演示了如何在 {{cssxref("offset-path")}} 属性中使用 `shape()` 函数来定义元素可以跟随的路径形状。在这个示例中，我们创建了一个曲线路径。
```suggestion
该示例演示了如何在 {{cssxref("offset-path")}} 属性中使用 `shape()` 函数来定义元素可以跟随的路径形状。
```

2024-06-20 02:26 UTC, yin1999 approved these changes
Thanks @tianyeeT

2024-06-20 02:26 UTC, merged