[zh-cn]: update the translation of `currentTarget`
mdn/translated-content pull request #20965
Opened 2024-05-29 13:43 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-05-29 15:01 UTC, yin1999 requested changes

2024-05-29 15:01 UTC, yin1999 commented on files/zh-cn/web/api/event/currenttarget/index.md
> +在这两种情况下，`currentTarget` 都标识父元素，因为那是处理程序附加到的元素。
```suggestion
在这两种情况下，`currentTarget` 都标识父元素，因为那是处理器附加到的元素。
```

2024-05-29 15:01 UTC, yin1999 commented on files/zh-cn/web/api/event/currenttarget/index.md
> +- [事件冒泡](/zh-CN/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling)
```suggestion
- [事件冒泡](/zh-CN/docs/Learn/JavaScript/Building_blocks/Events#事件冒泡)
```

2024-05-30 00:36 UTC, tianyeeT commented on files/zh-cn/web/api/event/currenttarget/index.md
> +请注意，`currentTarget` 的值仅在事件处理程序中可用。在事件处理程序外部，它将为 `null`。这意味着，例如，如果在事件处理程序内部引用 `Event` 对象然后在事件处理程序外部访问其 `currentTarget` 属性，则其值将为 `null`。
https://github.com/mdn/content/pull/33798

2024-05-31 10:15 UTC, tianyeeT commented
https://github.com/mdn/content/pull/33798
need to follow up

2024-06-16 08:51 UTC, yin1999 commented
@tianyeeT 麻烦更新一下文档

2024-06-16 10:39 UTC, tianyeeT commented on files/zh-cn/web/api/event/currenttarget/index.md
> +title: Event：currentTarget 属性
```suggestion
title: Event.currentTarget
```
@yin1999 要改回去吗

2024-06-16 10:44 UTC, yin1999 commented on files/zh-cn/web/api/event/currenttarget/index.md
> +title: Event：currentTarget 属性
与英文文档保持一致，不用改

2024-06-16 10:45 UTC, yin1999 approved these changes

2024-06-16 10:45 UTC, merged