[zh-cn]: create the translation of `cookies/cookiestore`
mdn/translated-content pull request #20989
Opened 2024-05-30 01:12 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests
#20967

2024-05-30 04:27 UTC, PassionPenguin requested changes
链接名需要翻译一下

2024-05-30 04:27 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/cookies/cookiestore/index.md
> +有关 cookie 存储的更多信息，请参见 [Work with the Cookies API](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Work_with_the_Cookies_API#cookie_stores)。
链接名字请作出翻译

2024-05-30 04:27 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/cookies/cookiestore/index.md
> +  - : 一个布尔值，指示这是一个无痕 cookie 存储。此属性在 Chrome 或 Safari 中不受支持。但是，你可以通过其 `id` 始终为“1”来识别 Chrome 中的无痕 cookie 存储。
```suggestion
  - : 一个布尔值，指示这是一个无痕 cookie 存储。此属性在 Chrome 或 Safari 中不受支持。不过，由于 Chrome 中无痕 cookie 存储的 `id` 值始终为“1”，你可以借此来识别这一存储。
```

2024-05-31 03:42 UTC, yin1999 requested changes

2024-05-31 03:42 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/cookies/cookiestore/index.md
> +`CookieStore` 类型的 {{WebExtAPIRef("cookies")}} API 表示浏览器中的一个 cookie 存储。
of 是一种倒装的修饰形式，这里的翻译未免太“直译”了吧

2024-05-31 03:42 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/cookies/cookiestore/index.md
> +不同浏览模式的窗口可能会使用不同的 cookie 存储。例如，隐私浏览/无痕模式窗口使用的 cookie 存储与非无痕/隐私窗口使用的 cookie 存储是分开的。此外，当使用[容器标签](https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers)功能时，一个窗口可能会有多个 cookie 存储。
https://support.mozilla.org/zh-CN/kb/how-use-firefox-containers

```suggestion
不同浏览模式的窗口可能会使用不同的 cookie 存储。例如，隐私浏览/无痕模式窗口使用的 cookie 存储与非无痕/隐私窗口使用的 cookie 存储是分开的。此外，在 Firefox 中使用[容器标签页](https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers)时，一个窗口可能会有多个 cookie 存储。
```

2024-05-31 03:42 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/cookies/cookiestore/index.md
> +有关 cookie 存储的更多信息，请参见[使用 Cookies API](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Work_with_the_Cookies_API#cookie_stores)。
```suggestion
有关 cookie 存储的更多信息，请参见[使用 Cookies API](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Work_with_the_Cookies_API#cookie_存储)。
```

2024-05-31 03:42 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/cookies/cookiestore/index.md
> +  - : 一个 `integers` 数组，标识共享此 cookie 存储的所有浏览器标签页。
```suggestion
  - : 一个整型数（`integer`）的数组，标识共享此 cookie 存储的所有浏览器标签页。
```

2024-05-31 03:42 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/cookies/cookiestore/index.md
> +在以下代码片段中，{{WebExtAPIRef("cookies.getAllCookieStores()")}} 方法用于检索浏览器中当前可用的所有 cookie 存储，并打印出每个 cookie 存储的 ID 以及当前共享每个 cookie 存储的标签页。
意译：

```suggestion
在以下代码片段中，{{WebExtAPIRef("cookies.getAllCookieStores()")}} 方法用于检索浏览器中当前可用的所有 cookie 存储，并打印出每个 cookie 存储的 ID 以及当前共享对应的 cookie 存储的标签页。
```

2024-05-31 03:42 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/cookies/cookiestore/index.md
> +    console.log(`Cookie store: ${store.id}\n Tab IDs: ${store.tabIds}`);
代码示例也应翻译

```suggestion
    console.log(`Cookie 存储：${store.id}\n标签页 ID：${store.tabIds}`);
```

2024-05-31 03:42 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/cookies/cookiestore/index.md
> +    `Of ${stores.length} cookie stores, ${incognitoStores.length} are incognito.`,
```suggestion
    `${stores.length} 个 cookie 存储中有 ${incognitoStores.length} 个是无痕模式的。`,
```

2024-06-04 01:25 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/cookies/cookiestore/index.md
> +`CookieStore` 是 {{WebExtAPIRef("cookies")}} API 中的一个类型，用于表示浏览器中的一个 cookie 存储区。
额，每个文档的开头的格式都很统一啊 ```**`A`** of B is/represents/...``` 就翻译成“B 的 A 是/表示/……”

```suggestion
{{WebExtAPIRef("cookies")}} API 的 `CookieStore` 类型用于表示浏览器中的一个 cookie 存储。
```

2024-06-04 01:41 UTC, yin1999 approved these changes

2024-06-04 01:41 UTC, merged