[zh-cn]: update the translation of `what_are_hyperlinks`
mdn/translated-content pull request #21019
Opened 2024-05-30 13:47 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-05-30 15:27 UTC, jasonren0403 requested changes
即使是看上去不必更新的内容，也需要注意标点符号及格式

2024-05-30 15:27 UTC, jasonren0403 commented on files/zh-cn/learn/common_questions/web_mechanics/what_are_hyperlinks/index.md
表格内容和标点符号需要更新

2024-05-30 15:27 UTC, jasonren0403 commented on files/zh-cn/learn/common_questions/web_mechanics/what_are_hyperlinks/index.md
>  ![Example of a basic display and effect of a link in a web page](link-1.png)
替代文本建议翻译下

2024-05-30 15:27 UTC, jasonren0403 commented on files/zh-cn/learn/common_questions/web_mechanics/what_are_hyperlinks/index.md
>  ![Example of a basic display and effect of an anchor in a web page](link-2.png)
替代文本

2024-05-30 15:27 UTC, jasonren0403 commented on files/zh-cn/learn/common_questions/web_mechanics/what_are_hyperlinks/index.md
95行，注意句号

2024-05-30 15:27 UTC, jasonren0403 commented on files/zh-cn/learn/common_questions/web_mechanics/what_are_hyperlinks/index.md
> +[SEO](https://zh.wikipedia.org/wiki/搜尋引擎最佳化) (search engine optimization) 是如何使网站在搜索结果中排名高的研究。改善网站的链接使用是一种有用的搜索引擎优化技术。
```suggestion
[SEO](https://zh.wikipedia.org/wiki/搜尋引擎最佳化)（search engine optimization）是如何使网站在搜索结果中排名高的研究。改善网站的链接使用是一种有用的搜索引擎优化技术。
```

2024-06-06 12:11 UTC, yin1999 commented on files/zh-cn/learn/common_questions/web_mechanics/what_are_hyperlinks/index.md
> +          网页，网站，网络服务器和搜索引擎间的区别</a
```suggestion
          网页、网站、网络服务器和搜索引擎间的区别</a
```

2024-06-06 14:09 UTC, yin1999 commented on files/zh-cn/learn/common_questions/web_mechanics/what_are_hyperlinks/index.md
> +早在 1989 年，网络发明人蒂姆·伯纳斯-李（Tim Berners-Lee）就提出了 Web 的三大支柱：
```suggestion
早在 1989 年，网络发明人蒂姆·伯纳斯·李（Tim Berners-Lee）就提出了 Web 的三大支柱：
```

2024-06-07 01:57 UTC, jasonren0403 commented on files/zh-cn/learn/common_questions/web_mechanics/what_are_hyperlinks/index.md
> +早在 1989 年，网络发明人蒂姆·伯纳斯·李（Tim Berners-Lee）就提出了 Web 的三大支柱：
```suggestion
早在 1989 年，网络发明人蒂姆·伯纳斯-李（Tim Berners-Lee）就提出了 Web 的三大支柱：
```

2024-06-07 01:57 UTC, jasonren0403 commented on files/zh-cn/learn/common_questions/web_mechanics/what_are_hyperlinks/index.md
> +- 想要一些更实际的东西？我们的 [HTML 介绍](/zh-CN/docs/Learn/HTML/Introduction_to_HTML) 模块中的[创建超链接](/zh-CN/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks) 解释了如何实现详细的超链接。
```suggestion
- 想要一些更实际的东西？我们的 [HTML 介绍](/zh-CN/docs/Learn/HTML/Introduction_to_HTML) 模块中的[创建超链接](/zh-CN/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks)详细解释了如何实现超链接。
```

2024-06-07 03:21 UTC, jasonren0403 approved these changes
👍

2024-06-07 03:25 UTC, merged