[zh-cn]: update the translation of `what_is_a_url`
mdn/translated-content pull request #21030
Opened 2024-05-30 14:32 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-05-30 14:49 UTC, yin1999 requested changes
我们希望贡献者能够认真对待翻译的内容，而不是大部分时候都需要由审查人员来提出并更正这些问题。为 MDN 做出贡献当然是好的，但我们希望每位贡献者都能够在保证质量的基础上再去追求数量。

提醒一下，我们建议在本地翻译，并使用工具链的[预览功能](https://github.com/mdn/content?tab=readme-ov-file#build-the-site)检查翻译内容。

我会将这个 PR 转为草稿，**请在认为当前 PR 可供审查员做进一步的审核的情况下再将其标记为可供审阅**。

2024-05-30 14:49 UTC, yin1999 commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +本文讨论了统一资源定位符 (URLs)，并解释了它们是什么，以及如何被构建的。
[复数形式的问题](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md#%E5%A4%8D%E6%95%B0%E5%BD%A2%E5%BC%8F)

2024-05-30 14:49 UTC, yin1999 commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +> **备注：** 你可以将 URL 视为普通的邮寄地址：_scheme_ 代表你想要使用的邮政服务，_domain name_ 就像是城市或城镇，_port_ 就像邮政编码；_path_ 表示你的邮件应该送到的建筑物；_parameters_ 表示额外的信息，例如建筑物中公寓的编号；最后，_anchor_ 表示你实际寄信给的人。
好好考虑一下应该如何翻译（还有复数形式）

2024-05-30 14:49 UTC, yin1999 commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +{{Glossary("HTML")}} 语言 — [后续会再来讨论](/zh-CN/docs/Learn/HTML/Introduction_to_HTML) — 对 URLs 有大量的使用：
标点、复数形式

2024-05-30 14:49 UTC, yin1999 commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +- 为显示多媒体如图片 (用 {{HTMLElement("img")}} )，视频 (用 {{HTMLElement("video")}} )，声音和音乐 (用 {{HTMLElement("audio")}} )，等等；
空格、标点的使用

2024-06-24 02:19 UTC, tianyeeT commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +本文讨论了统一资源定位符 (URLs)，并解释了它们是什么，以及如何被构建的。
```suggestion
本文讨论了统一资源定位符 (URL)，并解释了它们是什么，以及如何被构建的。
```

2024-06-24 02:19 UTC, tianyeeT commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
>  和 {{Glossary("Hypertext")}} 以及 {{Glossary("HTTP")}} 一样，**URL** 是 Web 中的一个核心概念。它是{{Glossary("Browser","浏览器")}}用来检索 web 上公布的任何资源的机制。
```suggestion
和 {{Glossary("Hypertext")}} 以及 {{Glossary("HTTP")}} 一样，**URL** 是 Web 中的一个核心概念。它是{{Glossary("Browser","浏览器")}}用来检索 Web 上公布的任何资源的机制。
```

2024-06-24 02:19 UTC, tianyeeT commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +理论上说，每个有效的 URL 都指向一个唯一的资源。这个资源可以是一个 HTML 页面，一个 CSS 文档，一幅图像，等等。而在实际中，也有一些例外，最常见的情况就是一个 URL 指向了不存在的或是被移动过的资源。由于通过 URL 呈现的资源和 URL 本身由 Web 服务器处理，因此 web 服务器的拥有者需要认真地维护资源以及与它关联的 URL。
```suggestion
理论上说，每个有效的 URL 都指向一个唯一的资源。这个资源可以是一个 HTML 页面，一个 CSS 文档，一幅图像，等等。而在实际中，也有一些例外，最常见的情况就是一个 URL 指向了不存在的或是被移动过的资源。由于通过 URL 呈现的资源和 URL 本身由 Web 服务器处理，因此 Web 服务器的拥有者需要认真地维护资源以及与它关联的 URL。
```

2024-06-24 02:19 UTC, tianyeeT commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +> **备注：** 你可以将 URL 视为普通的邮寄地址：_scheme_ 代表你想要使用的邮政服务，_domain name_ 就像是城市或城镇，_port_ 就像邮政编码；_path_ 表示你的邮件应该送到的建筑物；_parameters_ 表示额外的信息，例如建筑物中公寓的编号；最后，_anchor_ 表示你实际寄信给的人。
```suggestion
> **备注：** 你可以将 URL 视为普通的邮寄地址：_scheme_ 表示你想要使用的邮政服务，那么 _domain name_ 就像是城市或城镇，_port_ 就像邮政编码；_path_ 表示你的邮件应该送到的建筑物；_parameter_ 表示额外的信息，例如建筑物中公寓的编号；最后，_anchor_ 表示你实际寄信给的人。
```

2024-06-24 02:19 UTC, tianyeeT commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +{{Glossary("HTML")}} 语言 — [后续会再来讨论](/zh-CN/docs/Learn/HTML/Introduction_to_HTML) — 对 URLs 有大量的使用：
```suggestion
[后续会再来讨论](/zh-CN/docs/Learn/HTML/Introduction_to_HTML)在 URL 中有着大量的使用的 {{Glossary("HTML")}} 语言：
```

2024-06-24 02:19 UTC, tianyeeT commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +- 为显示多媒体如图片 (用 {{HTMLElement("img")}} )，视频 (用 {{HTMLElement("video")}} )，声音和音乐 (用 {{HTMLElement("audio")}} )，等等；
```suggestion
- 为将文档与它的相关资源关联，用各种标签如 {{HTMLElement("link")}} 或 {{HTMLElement("script")}}；
- 为显示多媒体如图片（用 {{HTMLElement("img")}} )、视频 (用 {{HTMLElement("video")}} )、声音和音乐 (用 {{HTMLElement("audio")}} ）等；
```

2024-06-24 02:19 UTC, tianyeeT commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +我们上面看到的是一个*绝对 URL*，但也有一个叫做*相对 URL* 的东西。[URL 标准](https://url.spec.whatwg.org/#absolute-url-string)定义了两者——尽管它使用术语[_绝对 URL 字符串_](https://url.spec.whatwg.org/#absolute-url-string)和[_相对 URL 字符串_](https://
```suggestion
我们上面看到的是一个*绝对 URL*，但也有一个叫做*相对 URL* 的东西。[URL 标准](https://url.spec.whatwg.org/#absolute-url-string)定义了两者——尽管它使用术语[_绝对 URL 字符串_](https://url.spec.whatwg.org/#absolute-url-string)和[_相对 URL 字符串_](https://url.spec.whatwg.org/#relative-url-string)，以将它们与 [URL 对象](https://url.spec.whatwg.org/#url)（URL 的内存表示）区分开来。
```

2024-06-24 02:19 UTC, tianyeeT commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
>  尽管 URL 具有非常的技术性，但 URL 表示一个可读性的网站入口点。它们可以被记住，并且任何人都可以将它们输入浏览器的地址栏。人是 Web 的核心，因此建立所谓的 _[semantic URLs](http://en.wikipedia.org/wiki/Semantic_URL)_ 被认为是最佳实践。语义 URL 使用具有固有含义的单词，任何人都可以理解，无论他们的技术水平如何。
```suggestion
尽管 URL 具有非常的技术性，但 URL 表示一个可读性的网站入口点。它们可以被记住，并且任何人都可以将它们输入浏览器的地址栏。人是 Web 的核心，因此建立所谓的 _[semantic URL](http://en.wikipedia.org/wiki/Semantic_URL)_ 被认为是最佳实践。语义 URL 使用具有固有含义的单词，任何人都可以理解，无论他们的技术水平如何。
```

2024-06-24 03:22 UTC, yin1999 requested changes
我不逐个列出了，请仔细校对并更新翻译

2024-06-24 03:22 UTC, yin1999 commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +本文讨论了统一资源定位符 (URL)，并解释了它们是什么，以及如何被构建的。
```suggestion
本文讨论了统一资源定位符（URL），并解释了它是什么，以及它的结构。
```

2024-06-24 03:22 UTC, yin1999 commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
>    <tbody>
前提部分的标点、符号和翻译（不翻译“Web”）

2024-06-24 03:22 UTC, yin1999 commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +和 {{Glossary("Hypertext")}} 以及 {{Glossary("HTTP")}} 一样，**URL** 是 Web 中的一个核心概念。它是{{Glossary("Browser","浏览器")}}用来检索 Web 上公布的任何资源的机制。
```suggestion
**URL**（统一资源定位符）是互联网上唯一资源的地址。它是一种{{Glossary("Browser","浏览器")}}用来检索已发布的资源（例如 HTML 页面、CSS 文档、图像等）的主要机制。
```

2024-06-24 03:22 UTC, yin1999 commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +理论上说，每个有效的 URL 都指向一个唯一的资源。这个资源可以是一个 HTML 页面，一个 CSS 文档，一幅图像，等等。而在实际中，也有一些例外，最常见的情况就是一个 URL 指向了不存在的或是被移动过的资源。由于通过 URL 呈现的资源和 URL 本身由 Web 服务器处理，因此 Web 服务器的拥有者需要认真地维护资源以及与它关联的 URL。
这段也需更新

2024-06-24 03:22 UTC, yin1999 commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
上面的两端翻译

- 第一段：翻译不一致
- 第二段：可以把“一个”去掉（不强调数量）

2024-06-24 03:22 UTC, yin1999 commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +> **备注：** 你可以将 URL 视为普通的邮寄地址：_scheme_ 表示你想要使用的邮政服务，那么 _domain name_ 就像是城市或城镇，_port_ 就像邮政编码；_path_ 表示你的邮件应该送到的建筑物；_parameter_ 表示额外的信息，例如建筑物中公寓的编号；最后，_anchor_ 表示你实际寄信给的人。
翻译

2024-06-24 03:22 UTC, yin1999 commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +> **备注：** 关于 URL 还有[一些额外的部分和一些额外的规则](https://zh.wikipedia.org/wiki/统一资源定位符)，但对于普通用户或 Web 开发人员来说并不相关。不用担心这些，你不需要了解它们来构建和使用完全功能的 URL。
```suggestion
> **备注：** 关于 URL 还有[一些额外的部分和一些额外的规则](https://zh.wikipedia.org/wiki/统一资源定位符)，但对于普通用户或 Web 开发人员来说并不相关。不用担心这些，你不需要了解它们来构建和使用功能齐全的 URL。
```

2024-06-24 03:22 UTC, yin1999 commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
>  ## 协议
方案

2024-06-24 03:22 UTC, yin1999 commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +URL 的第一部分是 _scheme_，它表示浏览器必须使用的协议来请求资源（协议是计算机网络中交换或传输数据的一组方法）。通常对于网站，协议是 HTTPS 或 HTTP（它的非安全版本）。访问网页需要这两者之一，但浏览器还知道如何处理其他方案，比如 `mailto:`（打开邮件客户端），所以如果你看到其他协议也不要感到惊讶。
翻译

2024-06-24 03:22 UTC, yin1999 commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +## 凭证
不是凭证。我们对 DNS 系统中的某个组成部分有个名称：权威域名服务器。这里是一样的，Authority 是指“权威”

2024-06-24 03:22 UTC, yin1999 commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
>  ![Authority](mdn-url-authority.png)
翻译

2024-06-24 03:22 UTC, yin1999 commented on files/zh-cn/learn/common_questions/web_mechanics/what_is_a_url/index.md
> +接下来是*凭证*，它与 scheme 之间用字符模式 `://` 分隔。如果存在，凭证包括 _domain_（例如 `www.example.com`）和 _port_（`80`），由冒号分隔：
翻译

2024-07-27 07:53 UTC, yin1999 approved these changes

2024-07-27 07:59 UTC, merged