[ko] box-shadow-generator 신규 번역
mdn/translated-content pull request #21041
Opened 2024-05-31 00:53 UTC by givvemee

### Description

기존에 한국어로 존재하지 않던 문서 [Box-shadow generator](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_backgrounds_and_borders/Box-shadow_generator) 를 번역합니다.

### Motivation

### Additional details

`color picker tool` 은 번역본에도 원문이 반영되어 따로 번역하지는 않았습니다. 

### Related issues and pull requests

2024-06-02 08:03 UTC, hochan222 requested changes
@givvemee 님 안녕하세요.

고생 많으셨습니다. 몇 가지 리뷰 사항 하기에 남겨두었습니다.

좋은 주말 보내세요 :)

2024-06-02 08:03 UTC, hochan222 commented on files/ko/web/css/css_backgrounds_and_borders/box-shadow_generator/index.md
> +- color picker tool을 이용하여 그림자의 {{cssxref("color")}} 를 지정합니다.
```suggestion
- color picker tool을 이용하여 그림자의 {{cssxref("color")}} 를 설정합니다.
```

2024-06-03 02:09 UTC, givvemee commented on files/ko/web/css/css_backgrounds_and_borders/box-shadow_generator/index.md
> +- color picker tool을 이용하여 그림자의 {{cssxref("color")}} 를 지정합니다.
@hochan222 리뷰 감사합니다. 수정 반영하였어요!

2024-06-03 02:58 UTC, hochan222 approved these changes
고생 정말 많으셨습니다~! 빠르게 반영해주셔서 감사합니다.

좋은 하루 보내세요 :)

2024-06-03 02:58 UTC, merged