zh-CN: update Glossary/Navigation_directive
mdn/translated-content pull request #21130
Opened 2024-06-01 14:58 UTC by PassionPenguin

2024-06-05 02:44 UTC, jasonren0403 requested changes
好好检查下提交内容，保证下质量

2024-06-05 02:44 UTC, jasonren0403 commented on files/zh-cn/glossary/navigation_directive/index.md
13行别漏了呀

https://github.com/mdn/content/blob/99bddc188f639f8c77961850ce774ad65317cc38/files/en-us/glossary/navigation_directive/index.md?plain=1#L13

2024-06-05 02:44 UTC, jasonren0403 commented on files/zh-cn/glossary/navigation_directive/index.md
>    - {{Glossary("Reporting directive")}}
这三个应该有翻译吧

2024-06-05 02:44 UTC, jasonren0403 commented on files/zh-cn/glossary/navigation_directive/index.md
> +title: 浏览指令
跟其他地方的翻译统一一下吧，“导航指令”，下同

2024-06-05 02:44 UTC, jasonren0403 commented on files/zh-cn/glossary/navigation_directive/index.md
>  - {{HTTPHeader("Content-Security-Policy")}}
```suggestion
```

2024-06-05 02:45 UTC, yin1999 commented on files/zh-cn/glossary/navigation_directive/index.md
>  - {{HTTPHeader("Content-Security-Policy")}}
还有个标题（参见）

2024-06-11 11:32 UTC, jasonren0403 commented on files/zh-cn/glossary/navigation_directive/index.md
> +详见[导航指令](/zh-CN/docs/Web/HTTP/Headers/Content-Security-Policy#navigation_directives)以获得完整列表。
```suggestion
详见[导航指令](/zh-CN/docs/Web/HTTP/Headers/Content-Security-Policy#导航指令)以获得完整列表。
```

2024-06-11 11:34 UTC, jasonren0403 approved these changes

2024-06-11 11:34 UTC, jasonren0403 approved these changes

2024-06-11 11:35 UTC, merged