French translation for  the "Edit and create pages" reference
mdn/translated-content pull request #2118
Opened 2021-08-17 21:18 UTC by audrasjb

This PR adds a French translation for  the "Edit and create pages" reference.

2021-08-29 06:50 UTC, SphinxKnight commented
I need to take time for this one but long story short: I believe this page should mention translated-content / the localization activities.
For instance a <French/other locale> contributor cannot create a page but in English.

I'll come back with suggestions.

All that being written, thanks for the PR :)

2021-09-01 06:14 UTC, SphinxKnight commented
@audrasjb Je sous-estimais la fonctionnalité de suggestions sur GitHub :) voici mes quelques propositions, n'hésite pas à reformuler / adapter si tu veux.

2021-09-01 06:15 UTC, SphinxKnight requested changes
see suggestions :)

2021-09-01 06:15 UTC, SphinxKnight commented on files/fr/mdn/contribute/howto/create_and_edit_pages/index.html
> +
```suggestion

<div class="notecard">
  <p><strong>Note :</strong> Le contenu de MDN s'organise au sein de deux dépôts Git : <a href="https://github.com/mdn/content"><code>mdn/content</code></a> avec le contenu en anglais et <a href="https://github.com/mdn/translated-content"><code>mdn/translated-content</code></a> avec le contenu traduit (y compris en français). C'est le dépôt <code>mdn/content</code> qui constitue la référence. Si vous souhaitez créer une page en français, celle-ci devra au préalable avoir été créée en anglais.</p>
</div>
```

2021-09-01 06:15 UTC, SphinxKnight commented on files/fr/mdn/contribute/howto/create_and_edit_pages/index.html
> +<p>Pour modifier une page, vous devez trouver la page source <a href="https://github.com/mdn/content">sur notre dépôt <i lang="en">content</i></a>. La façon la plus rapide de la trouver est d'aller s
```suggestion
<p>Pour modifier une page, vous devez trouver la page source :</p>
<ul>
  <li>Si elle est en anglais : <a href="https://github.com/mdn/content">sur notre dépôt <i lang="en">content</i></a></li>
  <li>Si elle est en français ou dans une autre langue : <a href="https://github.com/mdn/translated-content">sur notre dépôt <i lang="en">translated-content</i></a></li>
</ul>.
<p>La façon la plus rapide de la trouver est d'aller sur la page que vous souhaitez modifier, puis de vous rendre en bas de cette page et enfin de cliquer sur le lien <i lang="en">«&nbsp;Source on GitHub&nbsp;»</i>.</p>
```

2021-09-01 06:15 UTC, SphinxKnight commented on files/fr/mdn/contribute/howto/create_and_edit_pages/index.html
> +<p>Une fois que vous avez trouvé la source à modifier, rendez-vous sur notre fichier <i lang="en">README</i> et parcourez notre <a href="https://github.com/mdn/content#making-contributions">guide sur
```suggestion
<p>Une fois que vous avez trouvé la source à modifier, rendez-vous sur notre fichier <i lang="en">README</i> et parcourez notre <a href="https://github.com/mdn/translated-content/#making-contributions">guide sur la contribution (en anglais)</a>. Vous pouvez également consulter <a href="https://tech.mozfr.org/post/2021/03/16/MDN-sur-GitHub-comment-contribuer">ce billet en français</a> pour savoir comment contribuer.</p>
```

2021-09-01 06:15 UTC, SphinxKnight commented on files/fr/mdn/contribute/howto/create_and_edit_pages/index.html
> +
```suggestion
```

2021-09-01 06:15 UTC, SphinxKnight commented on files/fr/mdn/contribute/howto/create_and_edit_pages/index.html
> +
Les tags ne sont plus utilisés côté contenu traduit, ça ne me semble pas bénéfique que de les mentionner ici.

2021-09-01 06:15 UTC, SphinxKnight commented on files/fr/mdn/contribute/howto/create_and_edit_pages/index.html
> +
```suggestion

<div class="warning">
  <p><strong>Attention :</strong> Pour créer une page en français (ou dans une autre langue), celle-ci devra préalablement exister/avoir été créée en anglais.</p>
</div>
```

2021-09-01 06:15 UTC, SphinxKnight commented on files/fr/mdn/contribute/howto/create_and_edit_pages/index.html
> +  <li><a href="/fr/docs/MDN/Guidelines/Writing_style_guide">Guide stylistique de MDN</a></li>
```suggestion
  <li><a href="/fr/docs/MDN/Guidelines/Writing_style_guide">Guide stylistique de MDN</a></li>
  <li><a href="https://tech.mozfr.org/post/2021/03/16/MDN-sur-GitHub-comment-contribuer">MDN sur GitHub&nbsp;: comment contribuer&nbsp;?</a></li>
```

2021-09-18 19:57 UTC, audrasjb commented on files/fr/mdn/contribute/howto/create_and_edit_pages/index.html
> +
yes

2021-09-18 19:58 UTC, audrasjb commented
Thanks for the suggestions, that perfectly makes sense to me 👍

2021-09-18 19:59 UTC, merged