[zh-cn]: create the translation of `contextualIdentities.update()` me…
mdn/translated-content pull request #21307
Opened 2024-06-05 01:51 UTC by tianyeeT

…thod

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-06-05 02:38 UTC, yin1999 requested changes

2024-06-05 02:38 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/contextualidentities/update/index.md
> +更新给定 cookie store ID 的上下文身份的属性。
下同

```suggestion
更新给定 cookie 存储 ID 的上下文身份的属性。
```

2024-06-05 02:48 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/contextualidentities/update/index.md
> +更新给定 cookie 存储 ID 的上下文身份的属性。
可以找到 contextualIdentities 的官方翻译吗

2024-06-05 02:51 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/contextualidentities/update/index.md
> +更新给定 cookie store ID 的上下文身份的属性。
Related PR: https://github.com/mdn/translated-content/pull/21308
https://github.com/mdn/translated-content/pull/21298
https://github.com/mdn/translated-content/pull/21299
https://github.com/mdn/translated-content/pull/21296
https://github.com/mdn/translated-content/pull/21304
https://github.com/mdn/translated-content/pull/21306
已修改

2024-06-05 07:10 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/contextualidentities/update/index.md
> +更新给定 cookie 存储 ID 的上下文身份的属性。
没有找到，在中文网站介绍较少

2024-06-07 13:17 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/contextualidentities/update/index.md
> +更新给定 cookie 存储 ID 的上下文身份的属性。
请确认一下这个翻译是否合适，最好能给出相似或相关的翻译的文档链接

2024-06-23 13:36 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/contextualidentities/update/index.md
> +更新给定 cookie 存储 ID 的上下文身份的属性。
参见以下两个 SUMO 文档：

- https://support.mozilla.org/en-US/kb/how-do-you-use-leanplum-firefox
- https://support.mozilla.org/en-US/kb/how-do-you-use-google-firebase-firefox

其中均使用了“contextual”一词，而在对应的中文翻译中，使用了“场景”这一翻译。我觉得这相对较为贴合其实际意思（也便于用户理解）。

参见：

- [Mozilla Taiwan 关于“環境身分”的介绍](https://medium.com/@moz2000tw/firefox-53-%E7%82%BA%E6%82%A8%E7%8D%BB%E4%B8%8A-%E7%B2%BE%E7%B0%A1%E4%BD%88%E6%99%AF%E4%B8%BB%E9%A1%8C-css-%E9%81%AE%E7%BD%A9-%E9%82%84%E6%9C%89%E6%9B%B4%E5%A4%9A%E5%AF%A6%E7%94%A8%E5%8A%9F%E8%83%BD-3dc9dab6b72d)

2024-06-24 05:04 UTC, yin1999 reviewed
其他几个相关的 PR 也请更新一下（虽然我可能不会很快审查）

2024-06-24 05:04 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/contextualidentities/update/index.md
> +一个 [`Promise`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)，在更新身份完成时其会兑现一个描述已更新身份的 {{WebExtAPIRef('contextualIdentities.ContextualIdentity', 'ContextualIdentity')}} 对象。如果无法找到该身份或未启用上下
```suggestion
一个 [`Promise`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)，在更新身份完成时其会兑现一个描述已更新身份的 {{WebExtAPIRef('contextualIdentities.ContextualIdentity', 'ContextualIdentity')}} 对象。如果无法找到该身份或未启用场景身份特性，则 promise 被拒绝。
```

2024-06-24 12:38 UTC, yin1999 approved these changes

2024-06-24 12:38 UTC, merged