[zh-cn]: update the translation of BarProp documentation
mdn/translated-content pull request #21427
Opened 2024-06-10 09:13 UTC by fuchunhui

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-06-11 06:15 UTC, yin1999 requested changes

2024-06-11 06:15 UTC, yin1999 commented on files/zh-cn/web/api/barprop/index.md
> +{{domxref('Document Object Model', '文档对象模型')}} 的 **`BarProp`** 接口表示 Web 浏览器用户界面向 web 页面公开的脚本，以下每个接口元素都由一个 `BarProp` 对象表示。
```suggestion
{{domxref('Document Object Model', '文档对象模型', '', 1)}}的 **`BarProp`** 接口表示 Web 浏览器用户界面向 web 页面公开的脚本，以下每个接口元素都由一个 `BarProp` 对象表示。
```

2024-06-11 06:15 UTC, yin1999 commented on files/zh-cn/web/api/barprop/index.md
> +  - : 浏览器的 toolbar。
地址栏、菜单栏……等等为啥都不翻译

2024-06-11 06:15 UTC, yin1999 commented on files/zh-cn/web/api/barprop/index.md
> +  - : 一个 {{jsxref("Boolean")}}，如果所使用的界面元素表示的条是可见的，则返回 `true`。
```suggestion
  - : {{jsxref("Boolean", "布尔值", "", 1)}}，如果所使用的界面元素表示的条是可见的，则返回 `true`。
```

2024-06-11 06:15 UTC, yin1999 commented on files/zh-cn/web/api/barprop/index.md
> +下面的示例在控制台输出一个 `BarProp` 对象表示 location bar。
```suggestion
下面的示例在控制台输出一个表示地址栏的 `BarProp` 对象。
```

2024-06-11 06:15 UTC, yin1999 commented on files/zh-cn/web/api/barprop/visible/index.md
> +{{domxref("BarProp")}} 接口的 **`visible`** 只读属性返回 `true`，如果它所表示的用户界面元素的条是可见的。
```suggestion
{{domxref("BarProp")}} 接口的 **`visible`** 只读属性在它所表示的用户界面元素的条可见的情况下返回 `true`。
```

2024-06-11 06:15 UTC, yin1999 commented on files/zh-cn/web/api/barprop/visible/index.md
> +
```suggestion
```

2024-06-11 06:15 UTC, yin1999 commented on files/zh-cn/web/api/barprop/visible/index.md
> +一个 {{jsxref("Boolean")}}，如果顶层窗口是用 {{domxref("window.open", "弹出窗口", "窗口特征", 1)}} 被 {{domxref("window.open")}} 打开的，则为 `true`。
英文文档也要修改一下，因为 `popup_feature` 这个部分并不存在，新的指向应为 `https://developer.mozilla.org/en-US/docs/Web/API/Window/open#popup`。中文文档里面也不应该这么用，但先修复上游的错误吧

2024-06-12 03:07 UTC, fuchunhui commented on files/zh-cn/web/api/barprop/index.md
> +{{domxref('Document Object Model', '文档对象模型')}} 的 **`BarProp`** 接口表示 Web 浏览器用户界面向 web 页面公开的脚本，以下每个接口元素都由一个 `BarProp` 对象表示。
这个调整的作用是啥，有 API 文档不，我去学一下。

2024-06-12 03:13 UTC, fuchunhui commented on files/zh-cn/web/api/barprop/index.md
> +  - : 浏览器的 toolbar。
emmm 好，当时按照专有名词处理了。

2024-06-12 03:14 UTC, fuchunhui commented on files/zh-cn/web/api/barprop/visible/index.md
> +一个 {{jsxref("Boolean")}}，如果顶层窗口是用 {{domxref("window.open", "弹出窗口", "窗口特征", 1)}} 被 {{domxref("window.open")}} 打开的，则为 `true`。
OK，我先修改上游。

2024-06-12 04:02 UTC, fuchunhui commented on files/zh-cn/web/api/barprop/visible/index.md
> +一个 {{jsxref("Boolean")}}，如果顶层窗口是用 {{domxref("window.open", "弹出窗口", "窗口特征", 1)}} 被 {{domxref("window.open")}} 打开的，则为 `true`。
https://github.com/mdn/content/pull/34068

2024-06-13 05:06 UTC, yin1999 commented on files/zh-cn/web/api/barprop/visible/index.md
> +一个 {{jsxref("Boolean")}}，如果顶层窗口是用 {{domxref("window.open", "弹出窗口", "popup", 1)}} 被 {{domxref("window.open")}} 打开的，则为 `true`。
```suggestion
一个{{jsxref("Boolean", "布尔值", "", 1)}}，如果顶层窗口是用启用了 [`popup`](/zh-CN/docs/Web/API/Window/open#popup)  特性的 {{domxref("window.open")}} 打开的，则为 `true`。
```

2024-06-13 05:06 UTC, yin1999 commented on files/zh-cn/web/api/barprop/visible/index.md
> +  sourceCommit: 135b8311a5e3d12789e8421845be3ce026ef72b8
```suggestion
  sourceCommit: 864f91f32b49fd5038b29f0451ad18ff5682a5f7
```

2024-06-13 05:11 UTC, yin1999 approved these changes
Thank you @fuchunhui

2024-06-13 05:13 UTC, merged