[ko] String.prototype.codePointAt() 신규 번역
mdn/translated-content pull request #21452
Opened 2024-06-10 23:36 UTC by wisedog

- String.prototype.codePointAt() 신규 번역

2024-06-17 14:34 UTC, hochan222 requested changes
@wisedog 님 안녕하세요.

고생 정말 많으셨습니다. 몇가지 리뷰사항 하기에 남겨두었습니다.

좋은 하루 보내세요 :)

2024-06-17 14:34 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/string/codepointat/index.md
> +- `index`가 `0` – `str.length - 1`의 범위에서 벗어난다면, `codePointAt()`은 {{jsxref("undefined")}}을 반환합니다.
```suggestion
- `index`가 `0`부터 `str.length - 1`의 범위에서 벗어난다면, `codePointAt()`은 {{jsxref("undefined")}}을 반환합니다.
```
부터를 붙이는것이 조금 더 명확해보여서 제안드립니다. 

한국어에서 '–' 표현은 많이 사용하지 않는 듯해서 제안드렸는데, 아래와 같은 부분들을 보니 조금 고민이 되네요.

> UTF-16에서 각 문자열 인덱스는 `0` - `65535` 값을 갖는 코드 단위입니다.

2024-06-17 14:34 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/string/codepointat/index.md
> +문자열의 문자는 왼쪽에서 오른쪽으로 인덱싱됩니다. 첫 번째 문자의 인덱스는 `0`이고 `str`이라는 문자열의 마지막 문자의 인덱스는 `str.length - 1`입니다.
```suggestion
문자열의 문자는 왼쪽에서 오른쪽으로 인덱싱됩니다. 첫 번째 문자의 인덱스는 `0`이고, 문자열 `str`의 마지막 문자의 인덱스는 `str.length - 1`입니다.
```

조금 더 자연스럽게 변경했습니다.

2024-06-17 14:34 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/string/codepointat/index.md
> +유니코드 코드 포인트의 범위는 `0`에서 `1114111`(`0x10FFFF`)까지입니다. UTF-16에서 각 문자열 인덱스는 `0` - `65535` 값을 갖는 코드 단위입니다. 더 큰 코드 포인트 값은 16비트 서로게이트 의사 문자의 한 쌍으로 표현됩니다. 따라서 `codePointAt()`은 두 문자열 인덱스에 걸쳐 있을 수 있는 코드 포인트를 반환
```suggestion
유니코드 코드 포인트의 범위는 `0`에서 `1114111`(`0x10FFFF`)까지입니다. UTF-16에서 각 문자열 인덱스는 `0` - `65535` 값을 갖는 코드 단위입니다. 더 큰 코드 포인트 값은 16비트 서로게이트 의사 문자의 한 쌍으로 표현됩니다. 따라서 `codePointAt()`은 두 문자열 인덱스에 걸쳐 있을 수 있는 코드 포인트를 반환합니다. 유니코드에 대한 자세한 내용은 [UTF-16 문자, 유니코드 코드 포인트 및 문자소 클러스터](/ko/docs/Web/JavaScript/Reference/Global_Objects/String#utf-16_characters_unicode_code_points_and_grapheme_clusters)를 참조하세요.
```

-  https://github.com/mdn/translated-content/pull/21695#discussion_r1642856619

2024-06-18 23:19 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/string/codepointat/index.md
> +- `index`가 `0` – `str.length - 1`의 범위에서 벗어난다면, `codePointAt()`은 {{jsxref("undefined")}}을 반환합니다.
'-'  좌우에 숫자가 올 경우에는 그 의미가 명확한데, 제안주신 부분은 기호 양측이 숫자가 아니기에 제가 봐도 의미가 명확하지 않습니다. 제안 감사합니다.

2024-06-24 01:09 UTC, hochan222 approved these changes

2024-06-24 01:09 UTC, merged