[ko] Clients, Clients/get, Clients/matchAll 신규 번역
mdn/translated-content pull request #21459
Opened 2024-06-11 06:52 UTC by etoile-j

### Description

`Clients`, `Clients/get`, `Clients/matchAll` 문서 신규 번역하였습니다.

### Additional details
Clients의 나머지 두 메서드도 내일쯤 새 글로 올리겠습니다!🙂

2024-06-11 23:23 UTC, wisedog requested changes
한 군데 빼고는 아주 좋습니다. 간만에 기여 감사합니다!

2024-06-11 23:23 UTC, wisedog commented on files/ko/web/api/clients/get/index.md
> +## 명세
```suggestion
## 명세서
```

2024-06-12 15:19 UTC, etoile-j commented on files/ko/web/api/clients/get/index.md
> +## 명세
앗 감사합니다!

2024-06-17 02:30 UTC, wisedog approved these changes

2024-06-17 02:30 UTC, merged