zh-CN: create Glossary/Parser
mdn/translated-content pull request #21478
Opened 2024-06-11 10:57 UTC by PassionPenguin

2024-06-19 02:06 UTC, yin1999 requested changes

2024-06-19 02:06 UTC, yin1999 commented on files/zh-cn/glossary/parser/index.md
> +- 维基百科上的[语法分析器](https://en.wikipedia.org/wiki/语法分析)
```suggestion
- 维基百科上的[语法分析器](https://zh.wikipedia.org/wiki/语法分析)
```

2024-06-20 01:32 UTC, PassionPenguin commented on files/zh-cn/glossary/parser/index.md
> +title: 解析器
这里的parser也可以改成解析器叭？parser=lexer&tokenizer什么的

我查了一下，现在大家都还是混用，倒也没有统一共识

2024-06-20 01:32 UTC, PassionPenguin commented on files/zh-cn/glossary/parser/index.md
> +**解析器**是编译器或解释器中{{glossary("parse", "解析")}}源代码文件的模块。
```suggestion
**解析器**（语法分析器）是编译器或解释器中{{glossary("parse", "解析")}}源代码文件的模块。
```

2024-06-20 02:12 UTC, yin1999 commented on files/zh-cn/glossary/parser/index.md
> +title: 解析器
改吧

2024-06-20 03:09 UTC, yin1999 approved these changes

2024-06-20 03:09 UTC, merged