zh-CN: create Glossary/Privileged
mdn/translated-content pull request #21483
Opened 2024-06-11 11:31 UTC by PassionPenguin

2024-06-21 06:02 UTC, yin1999 requested changes
nits:

2024-06-21 06:02 UTC, yin1999 commented on files/zh-cn/glossary/privileged/index.md
> +title: 特权用户
```suggestion
title: 特权
```

2024-06-21 06:02 UTC, yin1999 commented on files/zh-cn/glossary/privileged/index.md
> +当用户被授予系统的额外权限或在与普通用户相比更高优先级的情况下获得对内容的终极访问权时，这些用户被称为**特权用户**。
```suggestion
当用户被授予系统的额外权限或在与普通用户相比更高优先级的情况下获得对内容的终极访问权时，这些用户被称为**特权**用户。
```

2024-06-21 06:02 UTC, yin1999 commented on files/zh-cn/glossary/privileged/index.md
> +- 维基百科上的[特权](<https://en.wikipedia.org/wiki/特权_(Windows)>)
```suggestion
- 维基百科上的[特权](<https://zh.wikipedia.org/wiki/特权_(Windows)>)
```

2024-06-23 02:48 UTC, PassionPenguin commented
> nits:

有一点，非常支持翻译作特权，但是通篇讲的确实特权用户lol，然后我们还有另外一个entry：privileged code

glossary里面好多这种ambigious title，第一眼什么都猜不出来（但是处理它们吧，确实又很浪费reviewer的时间，也没有什么技术性错误）😭

2024-06-23 06:45 UTC, yin1999 approved these changes

2024-06-23 06:45 UTC, merged