[zh-cn]: create the translation of `declarativeNetRequest.RuleAction` type
mdn/translated-content pull request #21615
Opened 2024-06-13 12:52 UTC by tianyeeT

… type

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-06-18 02:38 UTC, jasonren0403 requested changes
有一处需要注意的地方

2024-06-18 02:38 UTC, jasonren0403 commented on files/zh-cn/mozilla/add-ons/webextensions/api/declarativenetrequest/ruleaction/index.md
> +{{AddonSidebar}}
少了一行描述，请补上

https://github.com/mdn/content/blob/5f393e95a212ce0660d4322699dc1456f4cbf76c/files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/ruleaction/index.md?plain=1#L10

2024-06-20 05:30 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/declarativenetrequest/ruleaction/index.md
> +{{AddonSidebar}}
```suggestion
{{AddonSidebar}}

{{WebExtAPIRef("declarativeNetRequest.Rule")}} 的 `action` 属性表明了在匹配到规则时采取的相应动作的细节。
```

2024-06-28 04:28 UTC, jasonren0403 approved these changes
👍

2024-06-28 04:28 UTC, merged