[zh-cn]: sync with events
mdn/translated-content pull request #21610
Opened 2024-06-13 05:04 UTC by fuchunhui

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-06-13 06:05 UTC, fuchunhui commented
https://github.com/mdn/content/pull/34101

2024-06-13 06:53 UTC, PassionPenguin requested changes
calls for a removal for this note, as it's also written here for the **deleted events list** (mdn/content#31220)

2024-06-13 06:53 UTC, PassionPenguin commented on files/zh-cn/web/events/index.md
```suggestion
```

2024-06-13 07:18 UTC, fuchunhui commented on files/zh-cn/web/events/index.md
thanks

2024-06-24 01:26 UTC, PassionPenguin commented
@fuchunhui you may now reopen the PR and @yin1999 merge it given upstream's merged :)

2024-06-24 03:18 UTC, fuchunhui commented
> @fuchunhui you may now reopen the PR and @yin1999 merge it given upstream's merged :)

thanks for your reminder, I haven't done this before.

2024-06-24 03:29 UTC, yin1999 commented
I believe @PassionPenguin want you to mark this PR as "Ready for review". You can see this button below the CI tests list.

![image](https://github.com/mdn/translated-content/assets/15844309/ac0ce3cc-7320-4879-97d9-05c2b5803c59)

If you are thinking this PR is ready for review, please do so. And I'm willing to review this.

2024-06-24 07:55 UTC, PassionPenguin commented
> I believe @PassionPenguin want you to mark this PR as "Ready for review". You can see this button below the CI tests list.
> 
> ![image](https://private-user-images.githubusercontent.com/15844309/342192389-ac0ce3cc-7320-4879-97d9-05c2b5803c59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTU5NzEsIm5iZiI6MTcxOTIxNTY3MSwicGF0aCI6Ii8xNTg0NDMwOS8zNDIxOTIzODktYWMwY2UzY2MtNzMyMC00ODc5LTk3ZDktMDVjMmI1ODAzYzU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA3NTQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2M2NhODkxMDA4NjFkMTFlMWJlYTYwOTUwM2ZhODU1YmExYmQ5NjhkMDA0ZTI5YjQ1M2EyNWQwNGU3M2E0ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PY4fwsPiWFVwI_MTePI4M54JymzZ0YG5dQOWJ3jTvLc)
> 
> If you are thinking this PR is ready for review, please do so. And I'm willing to review this.

oops..sorry for the incorrect action name mentioned above. 😢

2024-06-24 12:29 UTC, fuchunhui commented
> I believe @PassionPenguin want you to mark this PR as "Ready for review". You can see this button below the CI tests list.
> 
> ![image](https://private-user-images.githubusercontent.com/15844309/342192389-ac0ce3cc-7320-4879-97d9-05c2b5803c59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzI0MDQsIm5iZiI6MTcxOTIzMjEwNCwicGF0aCI6Ii8xNTg0NDMwOS8zNDIxOTIzODktYWMwY2UzY2MtNzMyMC00ODc5LTk3ZDktMDVjMmI1ODAzYzU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDEyMjgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3OWQ3ZTZlYjdkMmRlYjA1MjMzMjU4Yzk1NTBlZDYyNzM2ODI1MzU4ZmUxMGQ3OWZmN2IyMjhjNzlhM2Q2ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C2DS1BAEDfJXegAHZeqFbGHRDmXm_iBwKYCs-R9dTwc)
> 
> If you are thinking this PR is ready for review, please do so. And I'm willing to review this.

thanks, it works.

2024-06-24 12:53 UTC, yin1999 commented on files/zh-cn/web/api/event/index.md
> +**`Event`** 接口表示在 [`EventTarget`](/zh-CN/docs/Web/API/EventTarget) 中出现的事件。
```suggestion
**`Event`** 接口表示在 [`EventTarget`](/zh-CN/docs/Web/API/EventTarget) 上出现的事件。
```

2024-06-24 12:53 UTC, yin1999 commented on files/zh-cn/web/events/index.md
> +  sourceCommit: 19e30e4787fff9074a50f16947dd2f6e9b7691c5
```suggestion
  sourceCommit: 4ca4fa3d9d1de5601b406b13dc75aff30709c66f
```

2024-06-24 12:53 UTC, yin1999 commented on files/zh-cn/web/events/index.md
> +            >Performance APIs</a
```suggestion
            >Performance API</a
```

2024-06-24 12:53 UTC, yin1999 commented on files/zh-cn/web/events/index.md
>            > 相关的事件。
```suggestion
          > 的相关事件。
```

2024-06-24 12:53 UTC, yin1999 commented on files/zh-cn/web/events/index.md
>          >、<a href="/zh-CN/docs/Web/API/TextTrackList#events"
410、411 行需要更新一下

2024-06-25 06:20 UTC, yin1999 approved these changes

2024-06-25 06:20 UTC, merged