[zh-cn]: create the translation of `devtools.panels` property
mdn/translated-content pull request #21622
Opened 2024-06-13 14:04 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-06-15 15:11 UTC, yin1999 requested changes

2024-06-15 15:11 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/devtools/panels/index.md
> +> **备注：** 尽管这些 API 基于 [Chrome devtools API](https://developer.chrome.com/docs/extensions/mv3/devtools/)，但 Firefox 中仍有许多功能尚未实现，因此这里未记录。要查看当前缺少哪些功能，请参阅 [devtools API 的限制](/zh-CN/docs/Mozilla/Add-ons/We
```suggestion
> **备注：** 尽管这些 API 基于 [Chrome devtools API](https://developer.chrome.com/docs/extensions/mv3/devtools/)，但 Firefox 中仍有许多特性尚未实现，因此这里未记录。要查看当前缺少哪些特性，请参阅 [devtools API 的局限性](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Extending_the_developer_tools#devtools_api_的局限性)。
```

2024-06-15 15:11 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/devtools/panels/index.md
> +使用 `devtools.panels` API，你可以在 devtools 窗口中创建新的面板。
devtools => 开发者工具

2024-06-15 15:11 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/devtools/panels/index.md
> +  - : 表示扩展添加到浏览器 devtools 中 HTML/CSS 检查器的窗格。
同

2024-06-15 15:11 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/devtools/panels/index.md
> +  - : 当前 devtools 主题的名称。
同

2024-06-15 15:11 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/devtools/panels/index.md
> +  - : 当 devtools 主题更改时触发。
同

2024-06-15 15:11 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/devtools/panels/index.md
> +- [devtools-panels](https://github.com/mdn/webextensions-examples/tree/main/devtools-panels)
和下面的 `{{WebExtExamples("h2")}}` 重复了，请删一下这部分（更新英文文档）

2024-06-16 11:51 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/devtools/panels/index.md
> +使用 `devtools.panels` API，你可以在 devtools 窗口中创建新的面板。
```suggestion
使用 `devtools.panels` API，你可以在开发者工具窗口中创建新的面板。
```

2024-06-16 11:51 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/devtools/panels/index.md
> +  - : 表示浏览器 devtools 中的 HTML/CSS 检查器。
```suggestion
  - : 表示浏览器开发者工具中的 HTML/CSS 检查器。
```

2024-06-16 11:51 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/devtools/panels/index.md
> +  - : 表示由扩展创建的 devtools 面板。
```suggestion
  - : 表示由扩展创建的开发者工具面板。
```

2024-06-16 11:51 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/devtools/panels/index.md
> +  - : 表示扩展添加到浏览器 devtools 中 HTML/CSS 检查器的窗格。
```suggestion
  - : 表示扩展添加到浏览器开发者工具中 HTML/CSS 检查器的窗格。
```

2024-06-16 11:51 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/devtools/panels/index.md
> +  - : 当前 devtools 主题的名称。
```suggestion
  - : 当前开发者工具主题的名称。
```

2024-06-16 11:51 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/devtools/panels/index.md
> +  - : 创建一个新的 devtools 面板。
```suggestion
  - : 创建一个新的开发者工具面板。
```

2024-06-16 11:51 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/devtools/panels/index.md
> +  - : 当 devtools 主题更改时触发。
```suggestion
  - : 当开发者工具主题更改时触发。
```

2024-06-16 11:51 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/devtools/panels/index.md
> +
```suggestion
```

2024-06-16 12:00 UTC, tianyeeT commented
@yin1999 :
Hi, here is the related PR: https://github.com/mdn/content/pull/34200

2024-06-28 01:30 UTC, yin1999 approved these changes

2024-06-28 01:30 UTC, merged