[ko] String.prototype.isWellFormed() 신규번역 외
mdn/translated-content pull request #21649
Opened 2024-06-15 04:13 UTC by wisedog

- String.prototype.isWellFormed() 신규 번역
- String.prototype.slice() 최신화

2024-06-17 15:28 UTC, hochan222 requested changes
@wisedog 님 안녕하세요.

고생 많으셨습니다. 리뷰 내용 하기에 남겨두었습니다.

좋은 하루 보내세요 :)

2024-06-17 15:28 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/string/iswellformed/index.md
> +JavaScript의 문자열은 UTF-16으로 인코딩됩니다. UTF-16 인코딩에는 서로게이트 쌍이라는 개념이 있으며, 이는 [UTF-16 문자, 유니코드 코드 포인트 및 그래프 문자 클러스터](/ko/docs/Web/JavaScript/Reference/Global_Objects/String#utf-16_characters_unicode_code_poi
```suggestion
JavaScript의 문자열은 UTF-16으로 인코딩됩니다. UTF-16 인코딩에는 서로게이트 쌍이라는 개념이 있으며, 이는 [UTF-16 문자, 유니코드 코드 포인트 및 문자소 클러스터](/ko/docs/Web/JavaScript/Reference/Global_Objects/String#utf-16_characters_unicode_code_points_and_graphheme_clusters) 섹션에 자세히 소개되어 있습니다.
```

- https://github.com/mdn/translated-content/pull/21695#discussion_r1642856619

2024-06-17 15:28 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/string/iswellformed/index.md
> +`isWellFormed()`를 사용하면 문자열이 잘 형성되었는지(즉, 론 서로게이트를 포함하지 않는지) 테스트할 수 있습니다. 사용자 정의 구현과 비교할 때 `isWellFormed()`는 엔진이 문자열의 내부 표현에 직접 액세스할 수 있으므로 더 효율적입니다. 문자열을 잘 형성된 문자열로 변환해야 하는 경우 {{jsxref("String/toWellF
```suggestion
`isWellFormed()`를 사용하면 문자열이 잘 형성되었는지(즉, 론 서로게이트를 포함하지 않는지) 테스트할 수 있습니다. 사용자 정의 구현과 비교할 때 `isWellFormed()`는 엔진이 문자열의 내부 표현에 직접 접근할 수 있으므로 더 효율적입니다. 문자열을 잘 형성된 문자열로 변환해야 하는 경우 {{jsxref("String/toWellFormed", "toWellFormed()")}} 메서드를 사용하세요. `isWellFormed()`를 사용하면 오류를 발생시키거나 유효하지 않은 것으로 표시하는 등 잘못된 형식의 문자열을 올바른 형식의 문자열과 다르게 처리할 수 있습니다.
```

2024-06-17 15:28 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/string/iswellformed/index.md
> +### encodeURI()에서 에러 피하기
```suggestion
### encodeURI()에서 오류 피하기
```

2024-06-17 15:28 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/string/slice/index.md
> +{{jsxref("String")}} 값의 **`slice()`** 메소드는 이 문자열의 일부를 추출하여 이를 새로운 문자열로 반환합니다. 원본 문자열은 수정하지 않습니다.
```suggestion
{{jsxref("String")}} 값의 **`slice()`** 메서드는 이 문자열의 일부를 추출하여 이를 새로운 문자열로 반환합니다. 원본 문자열은 수정하지 않습니다.
```

2024-06-30 23:21 UTC, wisedog commented
@hochan222  수정했습니다.

2024-07-08 16:31 UTC, hochan222 approved these changes
LGTM :)

2024-07-08 16:31 UTC, merged