[zh-tw] modify translation: Web/CSS/@font-face
mdn/translated-content pull request #21659
Opened 2024-06-15 12:48 UTC by BlueBoy247

### Description

I modified the translation in [this page](https://developer.mozilla.org/zh-TW/docs/Web/CSS/@font-face).

### Motivation

### Additional details

### Related issues and pull requests

2024-06-17 02:00 UTC, T34-active reviewed
看看这个繁体转换的内容行不行

2024-06-20 06:18 UTC, yin1999 requested changes
目前的内容和英文文档有很大的差异，请仔细更新

2024-06-20 18:18 UTC, BlueBoy247 commented
非常抱歉🙇‍♂️已重新確認並翻譯，煩請過目

2024-06-21 02:13 UTC, yin1999 reviewed
请先考虑以下问题

2024-06-21 02:13 UTC, yin1999 commented on files/zh-tw/web/css/@font-face/index.md
> +`@font-face` CSS @ 規則允許指定用於顯示文字之自定義字體，該字體可以從網路或用戶自己電腦上安裝的本地字體載入。透過自定義字體， `@font-face` 消除了對使用者電腦上安裝的有限數量字體的依賴。
缺少链接，最后一句话多了。麻烦考虑一下“font”的翻译，大陆地区大家已经习惯将其翻译为“字体”。我不确定台湾地区是否要明确区分“字体”和“字形”。目前 PR 的内容中两者都有出现，比较混乱

```suggestion
`@font-face` [CSS](/zh-TW/docs/Web/CSS) [@ 規則](/zh-TW/docs/Web/CSS/At-rule)允許指定用於顯示文字之自定義字體，該字體可以從網路或用戶自己電腦上安裝的本地字體載入。
```

2024-06-21 02:13 UTC, yin1999 commented on files/zh-tw/web/css/@font-face/index.md
```suggestion
```

2024-06-21 02:13 UTC, yin1999 commented on files/zh-tw/web/css/@font-face/index.md
> +  - {{cssxref("@font-face/font-variation-settings", "font-variation-settings")}}
```suggestion
- {{cssxref("@font-face/font-variation-settings", "font-variation-settings")}}
```

2024-06-21 02:13 UTC, yin1999 commented on files/zh-tw/web/css/@font-face/index.md
> +如果提供了 `local()` 函數，並指定了一個字體名稱來尋找用戶裝置上的字體，如果{{Glossary("user agent")}}找到了匹配的字體，就會使用這個本地字體。否則，將會下載並使用 `url()` 函數指定的字體資源。
```suggestion
如果提供了 `local()` 函數，並指定了一個字體名稱來尋找用戶裝置上的字體，如果{{Glossary("user agent", "使用者代理")}}找到了匹配的字體，就會使用這個本地字體。否則，將會下載並使用 `url()` 函數指定的字體資源。
```

2024-06-21 02:13 UTC, yin1999 commented on files/zh-tw/web/css/@font-face/index.md
> +  - : 指定對字體資源的引用，包括有關字體格式和技術的提示。 `@font-face` 規則必須有效。
```suggestion
  - : 指定對字體資源的引用，包括有關字體格式和技術的提示。`@font-face` 規則必須有效。
```

2024-06-21 02:13 UTC, yin1999 commented on files/zh-tw/web/css/@font-face/index.md
> +> **注意：** 在舊版瀏覽器上加載字體的回退策略描述在 [`src` 描述符頁面](/zh-TW/docs/Web/CSS/@font-face/src#指定舊版瀏覽器的後備方案)。
和前面的引用块相同，需要特殊的前缀才能实现高亮：

![image](https://github.com/mdn/translated-content/assets/15844309/63bad062-592e-4dee-a85b-12ece806c55d)

```suggestion
> **備註：** 在舊版瀏覽器上加載字體的回退策略描述在 [`src` 描述符頁面](/zh-TW/docs/Web/CSS/@font-face/src#指定舊版瀏覽器的後備方案)。
```

2024-06-21 04:37 UTC, BlueBoy247 commented on files/zh-tw/web/css/@font-face/index.md
> +`@font-face` CSS @ 規則允許指定用於顯示文字之自定義字體，該字體可以從網路或用戶自己電腦上安裝的本地字體載入。透過自定義字體， `@font-face` 消除了對使用者電腦上安裝的有限數量字體的依賴。
以[劍橋字典](https://dictionary.cambridge.org/zht/%E8%A9%9E%E5%85%B8/%E8%8B%B1%E8%AA%9E-%E6%BC%A2%E8%AA%9E-%E7%B9%81%E9%AB%94/font)和[維基百科](https://zh.wikipedia.org/zh-tw/%E5%AD%97%E5%9E%8B)的話，似乎是把"font"翻成「字型」而"typeface"翻作「字體」，而以我國[國家教育研究院](https://terms.naer.edu.tw/search/?query_term=font&query_field=title&query_op=&match_type=phrase)的資料來看，"font"既可翻作「字型」，亦有人翻為「字體」，"typeface"也是；此外依我國教育部國語辭典的[簡編本](https://dict.concised.moe.edu.tw/dictView.jsp?ID=36745#searchL)和[重編本](https://dict.revised.moe.edu.tw/dictView.jsp?ID=137574&q=1&word=%E5%AD%97%E9%AB%94)，似乎只收錄「字體」一詞，並無「字型」一詞；至於日常生活語彙使用上，兩詞基本上已被大眾混用。

不過依台灣一家中文字型設計公司justfont的[說明](https://blog.justfont.com/2013/02/some_nouns/)，「字體」是指**擁有共同設計理念的文字集合**，「字型」是指**字體實現出來可以使用的形式**，以本MDN文件提供的範例來說，當中的"Bitstream Vera Serif Bold"即為"Bitstream Vera Serif"字體中的其中一個字型。

目前個人想法是依[資訊與通訊術語大辭典](https://terms.naer.edu.tw/search/?query_term=font&query_field=title&query_op=&match_type=phrase&filter_bool=and&filter_term=%27%E8%B3%87%E8%A8%8A%E8%88%87%E9%80%9A%E8%A8%8A%E8%A1%93%E8%AA%9E%E5%A4%A7%E8%BE%AD%E5%85%B8%27&filter_field=subcategory_2.raw&filter_op=term&tabaction=browse)提供之中英對照，及上面提到的justfont的說明，將font翻作「字型」，由於font一詞在台灣普遍已被混用，想請問你的意見。

2024-06-22 02:42 UTC, yin1999 commented on files/zh-tw/web/css/@font-face/index.md
> +`@font-face` CSS @ 規則允許指定用於顯示文字之自定義字體，該字體可以從網路或用戶自己電腦上安裝的本地字體載入。透過自定義字體， `@font-face` 消除了對使用者電腦上安裝的有限數量字體的依賴。
/cc @irvin 你有什么建议嘛

2024-09-21 08:29 UTC, BlueBoy247 commented on files/zh-tw/web/css/@font-face/index.md
> +`@font-face` CSS @ 規則允許指定用於顯示文字之自定義字體，該字體可以從網路或用戶自己電腦上安裝的本地字體載入。透過自定義字體， `@font-face` 消除了對使用者電腦上安裝的有限數量字體的依賴。
還是我先翻成「字型」，後續若有人覺得有更合適的翻譯，再由他來更改？

2024-09-21 09:40 UTC, yin1999 commented on files/zh-tw/web/css/@font-face/index.md
> +`@font-face` CSS @ 規則允許指定用於顯示文字之自定義字體，該字體可以從網路或用戶自己電腦上安裝的本地字體載入。透過自定義字體， `@font-face` 消除了對使用者電腦上安裝的有限數量字體的依賴。
可以，先改一下吧

2024-09-21 13:13 UTC, yin1999 commented on files/zh-tw/web/css/@font-face/index.md
> +`@font-face` CSS @ 規則允許指定用於顯示文字之自定義字型，該字型可以從網路或用戶自己電腦上安裝的本地字型載入。透過自定義字型， `@font-face` 消除了對使用者電腦上安裝的有限數量字型的依賴。
```suggestion
`@font-face` CSS @ 規則允許指定用於顯示文字之自定義字型，該字型可以從網路或用戶自己電腦上安裝的本地字型載入。透過自定義字型，`@font-face` 消除了對使用者電腦上安裝的有限數量字型的依賴。
```

2024-09-21 13:13 UTC, yin1999 commented on files/zh-tw/web/css/@font-face/index.md
> +- Web 字型受到相同網域的限制（字型檔案必須與使用它們的頁面位於相同網域），除非使用[HTTP存取控制](/zh-TW/docs/Web/HTTP/CORS)來放寬此限制。
```suggestion
- Web 字型受到相同網域的限制（字型檔案必須與使用它們的頁面位於相同網域），除非使用 [HTTP 存取控制](/zh-TW/docs/Web/HTTP/CORS)來放寬此限制。
```

2024-09-21 13:13 UTC, yin1999 commented on files/zh-tw/web/css/@font-face/index.md
> +下面這個範例會套用使用者本地的 "Helvetica Neue Bold" 字型，只有當使用者未安裝該字型（兩種名稱都試過了），才會下載 "MgOpenModernaBold.ttf" 字型：
```suggestion
下面這個範例會套用使用者本地的「Helvetica Neue Bold」字型，只有當使用者未安裝該字型（兩種名稱都試過了），才會下載「MgOpenModernaBold.ttf」字型：
```

2024-09-21 13:21 UTC, yin1999 approved these changes
:+1:

2024-09-21 13:23 UTC, merged