[zh-cn]: create the translation of `api.HTMLMediaElement.setSinkId()` method
mdn/translated-content pull request #21687
Opened 2024-06-16 13:03 UTC by tianyeeT

https://github.com/mdn/translated-content/issues/20744#issuecomment-2163722099

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-06-16 13:40 UTC, yin1999 requested changes
其他的两个 PR 也有类似的问题，请修改

2024-06-16 13:40 UTC, yin1999 commented on files/zh-cn/web/api/htmlmediaelement/setsinkid/index.md
> +title: "HTMLMediaElement: setSinkId() method"
```suggestion
title: HTMLMediaElement：setSinkId() 方法
```

2024-06-16 13:40 UTC, yin1999 commented on files/zh-cn/web/api/htmlmediaelement/setsinkid/index.md
> +请注意，`enumerateDevices()` 的结果仅包括无需用户权限或已经授予权限的设备。
[不要断行](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md#%E6%8E%92%E7%89%88)

```suggestion
以下示例展示了如何从 {{domxref("MediaDevices.enumerateDevices()")}} 返回的设备数组中选择一个音频输出设备，并将其设置为音频的输出目标。请注意，`enumerateDevices()` 的结果仅包括无需用户权限或已经授予权限的设备。
```

2024-06-16 13:42 UTC, yin1999 commented
Blocked by #34088

2024-07-20 11:43 UTC, skyclouds2001 reviewed
https://github.com/mdn/content/pull/34088 has been merged

2024-07-29 04:56 UTC, yin1999 approved these changes

2024-07-29 04:58 UTC, merged