[ko] String.prototype.toWellFormed() 신규번역 외
mdn/translated-content pull request #21695
Opened 2024-06-16 23:16 UTC by wisedog

- String.prototype.toWellFormed() 신규 번역
- String.prototype.startsWith() 최신화

2024-06-17 14:01 UTC, hochan222 requested changes
@wisedog 님 안녕하세요.

고생 정말 많으셨습니다. 몇가지 리뷰사항 남겨두었습니다.

좋은 하루 보내세요!

2024-06-18 23:10 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/string/startswith/index.md
> +{{jsxref("String")}} 값의 **`startsWith()`** 메서드는 어떤 문자열의 문자로 시작하는지 확인하여 결과를 `true` 혹은 `false`로 반환합니다.
으흠~ 후자도 괜찮군요. 반영해보겠습니다.

2024-06-18 23:12 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/string/towellformed/index.md
> +JavaScript의 문자열은 UTF-16으로 인코딩됩니다. UTF-16 인코딩에는 서로게이트 쌍이라는 개념이 있으며, 이는 [UTF-16 문자, 유니코드 코드 포인트 및 그래프 문자 클러스터](/ko/docs/Web/JavaScript/Reference/Global_Objects/String#utf-16_characters_unicode_code_poi
그래프임이 더 뭔지 모를것 같아서 문자소로 하겠습니다. (근데 그것도 뭔지는 모르겠군요)

2024-06-24 01:13 UTC, hochan222 approved these changes

2024-06-24 01:13 UTC, merged