[Ko] svg  shape rendering 신규 번역
mdn/translated-content pull request #21696
Opened 2024-06-17 00:45 UTC by givvemee

### Description

기존에 한국어로 존재하지 않던 문서 [shape-rendering](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering) 를 신규 번역합니다.

### Motivation

### Additional details

### Related issues and pull requests

2024-06-17 15:23 UTC, hochan222 requested changes
@givvemee 님 안녕하세요.

고생 정말 많으셨습니다. 한 가지 리뷰 사항 하기에 남겨두었습니다.

좋은 하루 보내세요 :)

2024-06-17 15:23 UTC, hochan222 commented on files/ko/web/svg/attribute/shape-rendering/index.md
> +**`shape-rendering`** 특성은 경로, 원, 혹은 사각형 모양을 렌더링할 때 어떤 절충안을 감수할지에 대해 렌더러에게 힌트를 제공합니다.
```suggestion
**`shape-rendering`** 특성은 경로, 원, 혹은 직사각형 모양을 렌더링할 때,  렌더러에게 어떤 절충안을 감수할지 힌트를 제공합니다.
```

(1) rectangles을 직사각형으로 번역했습니다.
(2) 조금 더 자연스럽게 수정했습니다.

2024-06-18 00:09 UTC, givvemee commented
@hochan222 리뷰 감사합니다. 수정 완료되었어요.

2024-06-18 00:29 UTC, hochan222 approved these changes
고생 많으셨습니다. 좋은 하루 보내세요 :)

2024-06-18 00:29 UTC, merged