[zh-cn]: update the translation of `svg.elements.path.d` attribute
mdn/translated-content pull request #21701
Opened 2024-06-17 02:56 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-06-17 05:11 UTC, yin1999 requested changes

2024-06-17 05:11 UTC, yin1999 commented on files/zh-cn/web/svg/attribute/d/index.md
> +- [ClosePath](#closepath)：`Z`、`z`
仔细点

2024-06-17 10:22 UTC, tianyeeT commented on files/zh-cn/web/svg/attribute/d/index.md
> +- [ClosePath](#closepath)：`Z`、`z`
```suggestion
- [三次贝塞尔曲线](#三次贝塞尔曲线)：`C`、`c`、`S`、`s`
- [二次贝塞尔曲线](#二次贝塞尔曲线)：`Q`、`q`、`T`、`t`
- [椭圆曲线](#椭圆曲线)：`A`、`a`
- [ClosePath](#ClosePath)：`Z`、`z`
```

2024-06-17 14:19 UTC, tianyeeT commented on files/zh-cn/web/svg/attribute/d/index.md
> +- [ClosePath](#ClosePath)：`Z`、`z`
```suggestion
- [MoveTo](#moveto_路径命令)：`M`、`m`
- [LineTo](#lineto_路径命令)：`L`、`l`、`H`、`h`、`V`、`v`
- [三次贝塞尔曲线](#三次贝塞尔曲线)：`C`、`c`、`S`、`s`
- [二次贝塞尔曲线](#二次贝塞尔曲线)：`Q`、`q`、`T`、`t`
- [椭圆曲线](#椭圆曲线)：`A`、`a`
- [ClosePath](#closepath)：`Z`、`z`
```

2024-06-19 01:51 UTC, yin1999 commented on files/zh-cn/web/svg/attribute/d/index.md
>  {{SVGRef}}
第16行未更新

2024-06-19 01:51 UTC, yin1999 commented on files/zh-cn/web/svg/attribute/d/index.md
>    <tbody>
120行未更新，131行注释翻译

2024-06-19 01:51 UTC, yin1999 commented on files/zh-cn/web/svg/attribute/d/index.md
>  _Lineto_ 指令将绘制一条直线段。这个直线段从*当前位置*（_P<sub>o</sub>_; {_x<sub>o</sub>_, _y<sub>o</sub>_}）移到*指定位置*（_P<sub>n</sub>_; {_x<sub>n</sub>_, _y<sub>n</sub>_}）。然后，_指定位置_（_P<sub>n</sub>_）将变成下一个命令中的*当前位置*（_P<sub>o<
示例翻译

2024-06-19 01:51 UTC, yin1999 commented on files/zh-cn/web/svg/attribute/d/index.md
示例翻译（所有的示例）

2024-06-20 05:24 UTC, tianyeeT commented on files/zh-cn/web/svg/attribute/d/index.md
>  下面的示例展示了如何在悬停在元素上时应用新的路径。新的路径与旧的路径现统，但额外增加了一条穿过心形图案的线。
```suggestion
下面的示例展示了如何在悬停在元素上时应用新的路径。新的路径与旧的路径相同，但额外增加了一条穿过心形图案的线。
```

2024-06-24 06:13 UTC, yin1999 commented
示例里面的注释翻译一下 https://github.com/mdn/translated-content/pull/21701#discussion_r1645287507

2024-06-24 11:52 UTC, tianyeeT commented
> [#21701 (comment)](https://github.com/mdn/translated-content/pull/21701#discussion_r1645287507)

收到，之前没反应过来。

2024-06-25 14:55 UTC, yin1999 approved these changes

2024-06-25 14:56 UTC, merged