ko_translation_CSS_gradients
mdn/translated-content pull request #21724
Opened 2024-06-18 00:21 UTC by oh5chaeyoung

CSS gradients 일부를 번역하였습니다.

2024-06-20 18:02 UTC, 1ilsang requested changes
@oh5chaeyoung 님 안녕하세요. 기여해주셔서 감사합니다! 💯

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

질문이나 도움이 필요하시다면 언제든 멘션 부탁드리겠습니다.

2024-06-20 18:02 UTC, 1ilsang commented on docs/ko/fully_untranslated_files/Web_CSS_CSS_images_Using_CSS_gradients.md
> +그라디언트 안에 단색 영역을 만들려면 색상 정지점에 두 개의 위치를 지정하면 됩니다. 이렇게 하면 하나의 색상이 두 위치에 걸쳐 유지됩니다. 이는 동일한 색상이 서로 다른 위치에 두 개의 연속된 색상 정지점을 가지는 것과 동일합니다. 색상은 첫 번째 위치에서 색상이 완전히 나타나고, 두 번째 위치까지 그대로 유지됩니다. 그런 다음 인접한 색상 정지점에서
```suggestion
그레이디언트 안에 단색 영역을 만들려면 색상 정지점에 두 개의 위치를 지정하면 됩니다. 이렇게 하면 하나의 색상이 두 위치에 걸쳐 유지됩니다. 이는 동일한 색상이 서로 다른 위치에 두 개의 연속된 색상 정지점을 가지는 것과 동일합니다. 색상은 첫 번째 위치에서 색상이 완전히 나타나고, 두 번째 위치까지 그대로 유지됩니다. 그런 다음 인접한 색상 정지점에서 다음 색상으로 부드럽게 전환됩니다.
```

2024-06-20 18:02 UTC, 1ilsang commented on docs/ko/fully_untranslated_files/Web_CSS_CSS_images_Using_CSS_gradients.md
> +### 그라디언트 힌트
```suggestion
### 그레이디언트 힌트
```

2024-06-23 03:13 UTC, oh5chaeyoung commented
안녕하세요. 자세하게 리뷰해 주셔서 고맙습니다.
리뷰를 반영하는 과정이 처음이라 제대로 진행하였는지 궁금하여 연락드립니다.
잘못된 부분이 있다면 수정하겠습니다.
감사합니다 : )

2024-06-23 07:14 UTC, 1ilsang approved these changes
LGTM 고생하셨습니다. 👍

2024-06-23 07:17 UTC, merged