[ko] logical properties - basic concepts 신규 번역
mdn/translated-content pull request #21745
Opened 2024-06-19 01:29 UTC by givvemee

### Description

기존에 한국어로 존재하지 않던 문서 [Basic concepts of logical properties and values](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_logical_properties_and_values/Basic_concepts_of_logical_properties_and_values)를 번역합니다

### Motivation

### Additional details

[대열 레이아웃과 쓰기 모드](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flow_layout/Flow_layout_and_writing_modes) 에서는 flow layout 을 대열 레이아웃이라고 번역한 것을 뒤늦게 발견했는데요, 이 문서와 단어를 맞춰야 할지 고민입니다. 한자어가 오히려 어렵게 느껴질 것 같더라고요. 

### Related issues and pull requests

2024-06-30 12:20 UTC, sunhpark42 requested changes
안녕하세요 @givvemee 님, 번역 감사합니다. 내용 확인했습니다.
번역상 저로 flow layout이 대열 레이아웃으로 번역되는 경우보다는 다른 표현을 사용할 수 있다면 사용하는 것이 좋다고 생각이 들어서, 리뷰어 회의시에 논제로 꺼내보겠습니다. 의견 감사합니다:)

번역상 모호한 부분이 있어서 코멘트로 함께 남겨두었습니다. 확인 부탁드립니다.
감사합니다 :)

2024-06-30 12:20 UTC, sunhpark42 commented on files/ko/web/css/css_logical_properties_and_values/basic_concepts_of_logical_properties_and_values/index.md
> +CSS 2.1과 이전 버전에서는 화면의 물리적 크기를 따라 요소의 크기를 설정해왔습니다. 그렇기 떄문에 박스를 {{CSSxRef("width")}} 와 {{CSSxRef("height")}} 로 표현했고, 아이템은 `top` 과 `left` 에서부터 위치시키고, 테두리, 바깥 여백, 그리고 안쪽 여백을 `top`, `right`, `bottom`, `le
```suggestion
CSS 2.1과 이전 버전에서는 화면의 물리적 크기를 따라 요소의 크기를 설정해왔습니다. 그렇기 떄문에 박스를 {{CSSxRef("width")}} 와 {{CSSxRef("height")}} 로 표현했고, 아이템은 `top` 과 `left` 에서부터 위치시키고, 테두리, 바깥 여백, 그리고 안쪽 여백을 `top`, `right`, `bottom`, `left` 등에 할당했습니다. 논리적 속성과 값 모듈은 이러한 {{glossary("physical properties")}} 와 값을 논리적이거나 흐름 상대적인 값에 매핑합니다. 예로 `left`와 `right`, `top` 과 `bottom` 대신에 `start`와 `end`를 이용합니다.
```

원문상 위와 같은 흐름으로 번역되는것이 적절한 것 같아서 확인 부탁드립니다. 원문 같이 첨부드려요
```
The Logical properties and values module defines mappings for these {{glossary("physical properties")}} and values to their logical, or flow relative, counterparts — e.g. `start` and `end` as opposed to `left` and `right`/`top` and `bottom`.
```

2024-06-30 12:20 UTC, sunhpark42 commented on files/ko/web/css/css_logical_properties_and_values/basic_concepts_of_logical_properties_and_values/index.md
> +창의적인 이유로 가로 혹은 위에서 아래 방향이 아닌 다른 쓰기 모드를 사용할 때 콘텐츠의 흐름을 연관짓는 것은 매우 중요한 일입니다.
```suggestion
창의적인 이유로 가로 혹은 위에서 아래 방향이 아닌 다른 쓰기 모드를 사용할 때 콘텐츠의 흐름을 연관지을 수 있다는 것은 매우 중요한 일입니다.
```

being able to 의 의미가 빠진 것 같아서, 추가하는 것은 어떨까요?

추가로 헷갈리는 부분이 있어서, @givvemee 님은 어떻게 생각하실 지 궁금해서 함께 남겨보아요. 제가 이해하기로는 수평적이 아닌 쓰기 모드(즉, 위 아래로의 방식)에서 작업할 때 라고 이해했는데요, ,수평/수직방향이 아닌 쓰기 모드 이렇게 해석이 되어야 할까요..?
```
When working with a site in a writing mode other than a horizontal, top-to-bottom one
```

2024-07-01 00:21 UTC, givvemee commented on files/ko/web/css/css_logical_properties_and_values/basic_concepts_of_logical_properties_and_values/index.md
> +창의적인 이유로 가로 혹은 위에서 아래 방향이 아닌 다른 쓰기 모드를 사용할 때 콘텐츠의 흐름을 연관짓는 것은 매우 중요한 일입니다.
아 ... 제가 헷갈렸네요. other than a horizontal, top-to-bottom one 가 결국은 horizontal 이 아닌, 즉 top-to-bottom 를 특정하는 문장이었네요. ㅎㅎㅎ 수정하겠습니다.

2024-07-01 00:22 UTC, givvemee commented on files/ko/web/css/css_logical_properties_and_values/basic_concepts_of_logical_properties_and_values/index.md
> +창의적인 이유로 가로 혹은 위에서 아래 방향이 아닌 다른 쓰기 모드를 사용할 때 콘텐츠의 흐름을 연관짓는 것은 매우 중요한 일입니다.
@sunhpark42 리뷰 감사합니다.

2024-07-01 00:36 UTC, givvemee commented
@sunhpark42 `대열 레이아웃` 이라는 표현은 [이 문서](https://developer.mozilla.org/ko/docs/Web/CSS/CSS_flow_layout/Flow_layout_and_writing_modes) 에서 가져온 것이긴 한데요, 저는 logical properties and values 내의 문서들을 번역하면서 flow-relative, flow-layout 은 모두 흐름~ 으로 번역했어요. 그 편이 더 자연스러운 것 같아서요. 대열이라는 한자어를 한 번 더 파악해야 하는 수고로움이 있을 것 같기도 했고요. 참고 부탁드립니다.

2024-07-28 12:47 UTC, hochan222 requested changes, later dismissed
이미지 파일들은 자동으로 경로가 지정되어서 yari에서 제공되고 있습니다. 이미지 파일들 모두 제거 부탁드립니다~!

2024-07-30 00:45 UTC, givvemee commented
@hochan222 수정되었어요! 감사합니다.

2024-07-30 04:11 UTC, hochan222 commented
@sunhpark42 님, @givvemee 님 안녕하세요.

개인적으로는 음차가 좋아보이나.. 현재 PR은 기존에 존재하는 다른 문서에서 [대열 레이아웃](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flow_layout/Flow_layout_and_writing_modes)으로 번역이 진행되어, 대열 레이아웃으로 번역하는것이 좋아 보입니다.

나머지 고민은 ["음차 및 한국어 번역에 대한 기준 마련"](https://groups.google.com/g/yari-content-ko/c/f1RxhdUtuM4)에서 다루는것이 좋아 보입니다.

모두 좋은 하루 보내세요 :)

2024-07-30 07:28 UTC, sunhpark42 commented
확인 및 전달 감사합니다 호찬님,
@givvemee 님 7월중에 회사 일정이 바빠, 확인이 너무 늦어져서 죄송합니다. ㅠㅠ
다른 부분확인 되어서, 호찬님 코멘트 확인 후 반영해주시면 머지하도록 하겠습니다. 기다려주셔서 감사합니다. 🙇‍♀️

2024-08-05 01:07 UTC, givvemee commented
@hochan222 이거 논의 중이지만 `대열 레이아웃` 으로 수정하여 일단 머지는 해두어야 할까요?

2024-08-10 08:51 UTC, sunhpark42 commented
@givvemee 님 대열 레이아웃으로 작성 부탁드리며, 해당 논의 완료이후 수정으로 결정되면 해당 문구 일괄 수정하는 것이 좋을 것 같아, 수정부탁드립니다~!

2024-08-19 12:45 UTC, givvemee commented
> @givvemee 님 대열 레이아웃으로 작성 부탁드리며, 해당 논의 완료이후 수정으로 결정되면 해당 문구 일괄 수정하는 것이 좋을 것 같아, 수정부탁드립니다~!

제가 너무 늦어버렸네요 ... ㅎㅎ. 수정 완료하여 커밋했습니다. 감사해요!

2024-09-29 12:28 UTC, sunhpark42 approved these changes
안녕하세요 @givvemee 님 확인이 많이 늦었습니다. 죄송합니다 ㅠㅠ 수정사항 확인했습니다. 머지할게요! 항상 기여 감사합니다:)

2024-09-29 12:29 UTC, merged