update macros translate for zh-CN
mdn/translated-content pull request #2174
Opened 2021-08-21 14:06 UTC by mutoe

- update outdated `commonly-used_macros` translation
- add `other` macros translate
- fix 'macros' index link

2021-08-22 16:42 UTC, irvin requested changes
this duplicates #2173 , please rebase after it get merged.

2021-08-23 19:49 UTC, irvin commented
#2173 had been merged, please rebase your branch. (or you can close this one and open another new one instead.)

2021-08-28 02:07 UTC, pocketdr commented on files/zh-cn/mdn/structures/macros/commonly-used_macros/index.html
> -<h4 id="Deprecated">不赞成的</h4>
https://github.com/mdn/content/pull/1047#issuecomment-902335443

> This should broadly be interpreted to mean "use of this API is discouraged"

2021-08-29 07:10 UTC, pocketdr commented on files/zh-cn/mdn/structures/macros/commonly-used_macros/index.html
> -  <li>{{TemplateLink("EmbedGHLiveSample")}} 提供了一种新的动态示例编写和使用方式，你可以在<a href="/zh-CN/docs/MDN/Structures/Code_examples#github_live_samples">Github动态示例</a>中了解更多信息。</li>
已经提交 PR 在原文里添加这一段，https://github.com/mdn/content/pull/8440#issue-721899817

2021-08-29 12:50 UTC, mutoe commented on files/zh-cn/mdn/structures/macros/commonly-used_macros/index.html
> -  <li>{{TemplateLink("EmbedGHLiveSample")}} 提供了一种新的动态示例编写和使用方式，你可以在<a href="/zh-CN/docs/MDN/Structures/Code_examples#github_live_samples">Github动态示例</a>中了解更多信息。</li>
added, 等待合并

2021-08-29 12:51 UTC, mutoe commented
this PR is pending on https://github.com/mdn/content/pull/8440

2021-08-30 08:35 UTC, pocketdr commented on files/zh-cn/mdn/structures/macros/commonly-used_macros/index.html
> -<h4 id="Deprecated">不赞成的</h4>
这里还没有改~~

2021-10-12 14:03 UTC, irvin approved these changes

2021-10-12 14:11 UTC, merged