[ko] String() 생성자 신규 번역
mdn/translated-content pull request #21771
Opened 2024-06-20 23:03 UTC by wisedog

- String() 생성자 신규 번역

2024-07-08 14:32 UTC, wisedog commented
@1ilsang  혹시 이거 리뷰 부탁드려도 될까요? 셀프 리뷰하기엔 좀... 🥲

2024-07-09 11:06 UTC, 1ilsang requested changes
@wisedog 님 안녕하세요. 기여해주셔서 감사합니다! 💯

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

2024-07-09 11:06 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/string/string/index.md
> +  - : 문자로 바꿀 모든 것.
```suggestion
  - : 문자열로 바꿀 모든 것.
```

string 이기 때문에 "문자열"로 가이드 드립니다

2024-07-09 11:06 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/string/string/index.md
> +`String()`이 함수로 호출되면 ([`new`](/ko/docs/Web/JavaScript/Reference/Operators/new) 없이) [문자열 원시형](/ko/docs/Web/JavaScript/Reference/Global_Objects/String#string_coercion)으로 강제로 변환된 `값`을 반환합니다. 특히 [Symbol]
```suggestion
`String()`이 함수로 호출되면 ([`new`](/ko/docs/Web/JavaScript/Reference/Operators/new) 없이) [문자열 원시형](/ko/docs/Web/JavaScript/Reference/Global_Objects/String#string_coercion)으로 강제로 변환된 `값`을 반환합니다. 특히 [Symbol](/ko/docs/Web/JavaScript/Reference/Global_Objects/Symbol) 값은 `"Symbol(description)"`으로 변환되며, 여기서 `description`은 심볼의 [description](/ko/docs/Web/JavaScript/Reference/Global_Objects/Symbol/description)입니다.
```

~~값은 띄워주세요

2024-07-09 11:06 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/string/string/index.md
> +const a = new String("Hello world"); // a === "Hello world" 는 false입니다.
```suggestion
const a = new String("Hello world"); // a === "Hello world" 는 false입니다
```

2024-07-09 11:06 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/string/string/index.md
> +여기서 함수는 약속한 대로 문자열({{Glossary("primitive", "원시 값")}} 유형)을 생성합니다. 그러나 생성자는 문자열(객체 래퍼) 유형의 인스턴스를 생성하므로 문자열 생성자를 사용하는 경우는 거의 없습니다.
```suggestion
여기서 함수는 약속한 대로 문자열({{Glossary("primitive", "원시 값")}} 유형)을 생성합니다.
그러나 생성자는 문자열(객체 래퍼) 유형의 인스턴스를 생성하므로
문자열 생성자를 사용하는 경우는 거의 없습니다.
```

줄 수는 원본과 동일하게 해주세요. 관련 논의는 [여기](https://github.com/orgs/mdn/discussions/655#discussioncomment-9251708)에서 확인할 수 있습니다.

2024-07-09 13:09 UTC, wisedog commented
@1ilsang  리뷰 감사합니다. 모두 수정해서 다시 올렸습니다.

2024-07-10 05:00 UTC, 1ilsang approved these changes
LGTM 고생하셨습니다

2024-07-10 05:00 UTC, merged