[zh-cn]: create the translation of `tabs.connect()` method
mdn/translated-content pull request #21780
Opened 2024-06-21 05:44 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-06-27 01:39 UTC, yin1999 requested changes

2024-06-27 01:39 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/connect/index.md
> +调用此函数来建立扩展的后台脚本（或其他特权脚本，如弹出窗口脚本或选项页脚本）与属于该扩展并正在指定标签中运行的任何内容脚本之间的连接。此函数返回一个 `runtime.Port` 对象。
下面也是类似的，缺少一部分链接，还有 hash 未被本地化的情况

```suggestion
调用此函数来建立扩展的后台脚本（或其他特权脚本，如弹出窗口脚本或选项页脚本）与属于该扩展并正在指定标签中运行的任何内容脚本之间的连接。此函数返回一个 {{WebExtAPIRef("runtime.Port")}} 对象。
```

2024-06-27 01:39 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/connect/index.md
> +    examplePort.postMessage({ greeting: "Hi from background script" });
翻译一下

2024-06-27 06:54 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/connect/index.md
> +调用此函数后，将在任何属于此扩展并在指定标签中运行的内容脚本中触发 `runtime.onConnect` 事件。事件监听器将会收到另一个 `runtime.Port` 对象。两侧可以使用这些 `Port` 对象来交换消息。
```suggestion
调用此函数后，将在任何属于此扩展并在指定标签中运行的内容脚本中触发 {{WebExtAPIRef('runtime.onConnect')}} 事件。事件监听器将会收到另一个 {{WebExtAPIRef("runtime.Port")}} 对象。两侧可以使用这些 `Port` 对象来交换消息。
```

2024-06-27 06:54 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/connect/index.md
> +有关详细信息，请参阅[基于连接的消息传递](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#基于连接的消息传递)。你可以在不创建连接的情况下发送消息。关于如何选择这两种选项，请参阅[选择一次性消息和基于连接的消息传递之间的区别](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Content_
```suggestion
有关详细信息，请参阅[基于连接的消息传递](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#基于连接的消息传递)。你可以在不创建连接的情况下发送消息。关于如何选择这两种选项，请参阅[选择一次性消息和基于连接的消息传递之间的区别](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#选择一次性消息和基于连接的消息传递之间的区别)。
```

2024-06-27 06:54 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/connect/index.md
> +在此示例中，后台脚本监听[浏览器操作](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Anatomy_of_a_WebExtension#browser_actions_2)的点击事件，然后连接到当前活动的标签页，并通过从 `connect()` 返回的 `Port` 发送消息：
这里的hash路径上游文档有问题。没有转跳。

2024-06-27 06:54 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/connect/index.md
> +    examplePort.postMessage({ greeting: "Hi from background script" });
```suggestion
    examplePort.postMessage({打招呼："Hi from background script" });
```

2024-06-27 06:54 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/connect/index.md
> +  console.log(`错误：${error}`);
```suggestion
  console.log(`发生错误：${error}`);
```

2024-07-06 07:18 UTC, yin1999 requested changes

2024-07-06 07:18 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/connect/index.md
> +调用此函数后，将在任何属于此扩展并在指定标签中运行的内容脚本中触发 {{WebExtAPIRef('runtime.onConnect')}} 事件。事件监听器将会收到另一个 {{WebExtAPIRef("runtime.Port")}} 对象。两侧可以使用这些 `Port` 对象来交换消息。
```suggestion
调用此函数后，将在任何属于此扩展并在指定标签中运行的内容脚本中触发 {{WebExtAPIRef('runtime.onConnect')}} 事件。事件监听器将会收到另一个 {{WebExtAPIRef("runtime.Port")}} 对象。两侧可以使用 `Port` 对象来交换消息。
```

2024-07-06 07:18 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/connect/index.md
> +      - : `integer`。打开到由 `frameId` 指定的特定帧的端口，而不是标签页中的所有帧。
```suggestion
      - : `integer`。打开由 `frameId` 指定的特定框架的端口，而不是标签页中的所有框架。
```

2024-07-06 07:18 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/connect/index.md
> +    examplePort.postMessage({打招呼："Hi from background script" });
修改地不对，这是一个 json 对象，我们肯定不是翻译“键”而是翻译“值”啊。

```suggestion
    examplePort.postMessage({ greeting: "来自后台脚本的问候" });
```

2024-07-19 08:47 UTC, yin1999 approved these changes

2024-07-19 08:48 UTC, merged