[zh-cn]: create the translation of `tabs.duplicate()` method
mdn/translated-content pull request #21784
Opened 2024-06-21 07:55 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-06-21 07:56 UTC, tianyeeT commented
Related PR: https://github.com/mdn/content/pull/34312
I changed the original `Optional` into `{{optional_inline}}`.

2024-06-21 08:01 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/duplicate/index.md
> +slug: Mozilla/Add-ons/WebExtensions/API/tabs/discard
```suggestion
title: tabs.duplicate()
slug: Mozilla/Add-ons/WebExtensions/API/tabs/duplicate
```

2024-06-27 11:20 UTC, yin1999 requested changes

2024-06-27 11:20 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/duplicate/index.md
> +一个[`Promise`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)，其会在复制标签页后兑现一个 {{WebExtAPIRef('tabs.Tab')}} 对象，描述复制的标签页的详细信息。如果扩展具有 [`"tabs"` 权限](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/m
```suggestion
一个 [`Promise`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)，其会在复制标签页后兑现一个 {{WebExtAPIRef('tabs.Tab')}} 对象，描述复制的标签页的详细信息。如果扩展具有 [`"tabs"` 权限](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions)或匹配的[主机权限](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#主机权限)，`Tab` 对象只包含 `url`、`title` 和 `favIconUrl`。如果发生任何错误，则该 promise 将以错误消息拒绝。
```

2024-06-27 11:20 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/duplicate/index.md
> +  console.log(`发送错误：${error}`);
```suggestion
  console.log(`发生错误：${error}`);
```

2024-06-27 11:49 UTC, yin1999 approved these changes

2024-06-27 11:49 UTC, merged