[zh-cn]: create the translation of `tabs.create()` method
mdn/translated-content pull request #21781
Opened 2024-06-21 06:28 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-06-27 01:39 UTC, yin1999 requested changes
空格问题

2024-06-27 06:16 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/create/index.md
> +      - : `string`。使用此选项创建具有特定 cookie 存储 ID (`cookieStoreId`) 的标签页。此选项仅在扩展具有 `"cookies"` [权限](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions) 时可用。有关详细信息，请参阅[使用上下文标识](/zh-CN/docs/
```suggestion
      - : `string`。使用此选项创建具有特定 cookie 存储 ID (`cookieStoreId`) 的标签页。此选项仅在扩展具有 `"cookies"` [权限](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions)时可用。有关详细信息，请参阅[使用场景身份](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Work_with_contextual_identities)。
```

2024-06-27 06:16 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/create/index.md
> +      - : `boolean`。如果为 `true`，在 [阅读模式](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/API/tabs/toggleReaderMode) 中打开此标签页。默认为 `false`。
```suggestion
      - : `boolean`。如果为 `true`，在[阅读模式](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/API/tabs/toggleReaderMode)中打开此标签页。默认为 `false`。
```

2024-06-27 06:16 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/create/index.md
> +      - : `string`。要导航到的标签页的 URL。默认为新标签页页。
```suggestion
      - : `string`。要导航到的标签页的 URL。默认为新标签页。
```

2024-06-27 06:16 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/create/index.md
> +        完整的 URL 必须包含 Scheme（例如，'http\://www\.google.com' 而不是 'www\.google.com'）。
```suggestion
        完整的 URL 必须包含 scheme（例如，`http\://www\.google.com` 而不是 `www\.google.com`）。
```

2024-06-27 06:16 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/create/index.md
> +  console.log(`错误：${error}`);
```suggestion
  console.log(`发生错误：${error}`);
```

2024-06-27 06:57 UTC, yin1999 reviewed
对一下[预览页](https://pr21781.content.dev.mdn.mozit.cloud/zh-CN/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create)吧，还有标点、链接的问题。

2024-07-02 16:15 UTC, yin1999 requested changes

2024-07-02 16:15 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/create/index.md
> +      - : `integer`。标签页在窗口中的位置。提供的值将被夹紧在窗口中的标签数之间。
```suggestion
      - : `integer`。标签页在窗口中的位置。提供的值将被钳制在零和窗口中的标签数之间。
```

2024-07-02 16:15 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/create/index.md
> +        完整的 URL 必须包含 scheme（例如，`http\://www\.google.com` 而不是 `www\.google.com`）。
```suggestion
        完整的 URL 必须包含方案（scheme）（例如，`http://www.google.com` 而不是 `www.google.com`）。
```

2024-07-02 16:15 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/create/index.md
> +在新标签页中打开“https\://example.org”：
```suggestion
在新标签页中打开 `https://example.org`：
```

2024-07-06 07:19 UTC, yin1999 commented
@tianyeeT 麻烦处理一下

2024-07-06 07:37 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/create/index.md
> +      - : `boolean`。标签页是否应该成为窗口中的活动标签页。如果为 `false`，则不会影响窗口是否被聚焦（参见 {{WebExtAPIRef('windows.update')}}）。默认为 `true`。
```suggestion
      - : `boolean`。标签页是否应该成为窗口中的活动标签页。如果为 `false`，则不会产生任何效果。这不影响窗口是否获得焦点（参见 {{WebExtAPIRef('windows.update')}}）。默认为 `true`。
```

2024-07-06 07:57 UTC, yin1999 approved these changes

2024-07-06 07:57 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/create/index.md
> +一个 [`Promise`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)，其会兑现一个包含有关已创建标签页详细信息的 {{WebExtAPIRef('tabs.Tab')}} 对象。如果无法创建标签页（例如因为 `url` 使用了特权方案），则该 promise 将以错误消息返回。
```suggestion
一个 [`Promise`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)，其会兑现一个包含有关已创建标签页详细信息的 {{WebExtAPIRef('tabs.Tab')}} 对象。如果无法创建标签页（例如因为 `url` 使用了特权方案），则该 promise 将以错误消息拒绝。
```

2024-07-06 07:59 UTC, merged