[zh-cn]: create the translation of `tabs.sendMessage()` method
mdn/translated-content pull request #21815
Opened 2024-06-21 14:09 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-06-21 14:10 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/sendmessage/index.md
> +> **注意：** 你还可以使用[基于连接的消息传递](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#基于连接的消息传递)。
```suggestion
> **备注：** 你还可以使用[基于连接的消息传递](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#基于连接的消息传递)。
```

2024-06-23 07:46 UTC, yin1999 requested changes

2024-06-23 07:46 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/sendmessage/index.md
> +从扩展的后台脚本（或其他特权脚本，如弹出窗口脚本或选项页脚本）向任何运行在指定标签页中的[内容脚本](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Content_scripts)或在扩展的页面或 iframe 发送单个消息。
```suggestion
从扩展的后台脚本（或其他特权脚本，如弹出窗口脚本或选项页脚本）向任何运行在指定标签页中的[内容脚本](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Content_scripts)或在扩展的页面或 iframe 发送一条消息。
```

2024-06-23 07:46 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/sendmessage/index.md
> +      - : `integer`。将消息发送到指定的帧（frame），而不是标签页中的所有帧。内容脚本是否在所有帧中执行取决于 `manifest.json` 的 [`content_scripts`](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts) 部分中的 `all_frames` 设置。
与英文文档内容不一致，frame 不应该被翻译为帧，下面的翻译也不对

2024-06-23 14:07 UTC, yin1999 approved these changes

2024-06-23 14:07 UTC, merged