Update ARIA index and tech page
mdn/translated-content pull request #2185
Opened 2021-08-22 02:28 UTC by mutoe

2021-08-22 16:23 UTC, irvin requested changes

2021-08-22 16:23 UTC, irvin commented on files/zh-cn/web/accessibility/aria/index.html
這邊少了一個段落
https://github.com/mdn/content/blob/01741688cb7007c361fb7196f2f203b06f3a8103/files/en-us/web/accessibility/aria/index.html#L11

2021-08-22 16:23 UTC, irvin commented on files/zh-cn/web/accessibility/aria/aria_techniques/index.html
> +<p>ARIA 定义了可以应用于元素的语义，这些语义分为 <strong>roles</strong>（定义一种用户界面元素）、<strong>states</strong> 和 <strong>properties</strong> 支持的一个角色。作者必须在元素的生命周期中为其分配一个 ARIA 角色和适当的状态和属性，除非该元素已经具有适当的 ARIA 语义（通过使用适当的 HTML 元素
> states 和 properties 支持的一个角色

原文是

> states and properties that are supported by a role

這邊的意思應反過來，角色所支持的 states 和 properties

2021-08-22 18:23 UTC, mutoe commented on files/zh-cn/web/accessibility/aria/aria_techniques/index.html
> +<p>ARIA 定义了可以应用于元素的语义，这些语义分为 <strong>roles</strong>（定义一种用户界面元素）、<strong>states</strong> 和 <strong>properties</strong> 支持的一个角色。作者必须在元素的生命周期中为其分配一个 ARIA 角色和适当的状态和属性，除非该元素已经具有适当的 ARIA 语义（通过使用适当的 HTML 元素
感谢更正 :D

2021-08-23 19:41 UTC, irvin approved these changes

2021-08-23 19:42 UTC, merged