[zh-cn]: create the translation of `tabs.ZoomSettingsScope` type
mdn/translated-content pull request #21861
Opened 2024-06-23 02:00 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-06-23 07:42 UTC, yin1999 requested changes

2024-06-23 07:42 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/zoomsettingsscope/index.md
> +定义缩放更改是会在页面的源头中持久化，还是仅在此标签页中生效。当 {{WebExtAPIRef("tabs.zoomSettingsMode")}} 为“automatic”时，默认值为 `per-origin`，否则始终为 `per-tab`。
origin 的翻译不对，参见 https://github.com/mdn/translated-content/pull/21859#discussion_r1649986778

2024-06-23 07:42 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/zoomsettingsscope/index.md
> +- “per-tab”
字符串值就不使用中文的引号了。MDN 浏览器扩展相关的英文文档质量也不太好。其实英文文档应该好好重新组织一下的。在 JavaScript 的文档里面，我们一般会写成：

```md
- `"per-origin"`
  - : 描述
```

而不是像现在这样。

```suggestion
- "per-origin"
  - : 所有与此标签页具有相同来源的其他标签页将应用相同的缩放更改。此作用域仅在 {{WebExtAPIRef("tabs.zoomSettingsMode")}} 为“automatic”时可用。
- "per-tab"
```

2024-06-24 01:12 UTC, tianyeeT commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/zoomsettingsscope/index.md
> +定义缩放更改是会在页面的源头中持久化，还是仅在此标签页中生效。当 {{WebExtAPIRef("tabs.zoomSettingsMode")}} 为“automatic”时，默认值为 `per-origin`，否则始终为 `per-tab`。
```suggestion
定义缩放更改是会在页面的来源中持久化，还是仅在此标签页中生效。当 {{WebExtAPIRef("tabs.zoomSettingsMode")}} 为“automatic”时，默认值为 `per-origin`，否则始终为 `per-tab`。
```

2024-06-24 05:00 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/zoomsettingsscope/index.md
> +定义缩放更改是会在页面的来源中持久化，还是仅在此标签页中生效。当 {{WebExtAPIRef("tabs.zoomSettingsMode")}} 为“automatic”时，默认值为 `per-origin`，否则始终为 `per-tab`。
```suggestion
定义缩放更改是会对页面的来源持久化，还是仅在此标签页中生效。当 {{WebExtAPIRef("tabs.zoomSettingsMode")}} 为“automatic”时，默认值为 `per-origin`，否则始终为 `per-tab`。
```

2024-06-24 05:00 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/tabs/zoomsettingsscope/index.md
> +    - 在基于 Chrome 的浏览器中，缩放更改在导航时会重置；导航标签页时，页面总是以其源的缩放系数加载。
```suggestion
    - 在基于 Chrome 的浏览器中，缩放更改在导航时会重置；导航标签页时，页面总是以其来源的缩放系数加载。
```

2024-06-24 12:37 UTC, yin1999 approved these changes

2024-06-24 12:37 UTC, merged