[zh-cn]: update the translation of `CanvasGradient.addColorStop()` me…
mdn/translated-content pull request #21939
Opened 2024-06-26 06:47 UTC by tianyeeT

…thod

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-06-27 06:13 UTC, yin1999 requested changes
color stop 是色标的意思，还请认真修改一下这一文档的翻译：https://github.com/mdn/translated-content/pull/13725#discussion_r1230347134

2024-06-27 06:40 UTC, tianyeeT commented on files/zh-cn/web/api/canvasgradient/addcolorstop/index.md
> +**`CanvasGradient.addColorStop()`** 方法添加一个由**偏移值**和**颜色值**指定的断点到渐变。
```suggestion
**`CanvasGradient.addColorStop()`** 方法添加一个由**偏移值**和**颜色值**指定的色标到渐变。
```

2024-06-27 06:40 UTC, tianyeeT commented on files/zh-cn/web/api/canvasgradient/addcolorstop/index.md
> +  - : 一个在 `0` 到 `1` 之间（包含边界）的数字，表示颜色断点的位置。`0` 表示渐变的起始位置，`1` 表示渐变的结束位置。
```suggestion
  - : 一个在 `0` 到 `1` 之间（包含边界）的数字，表示色标的位置。`0` 表示渐变的起始位置，`1` 表示渐变的结束位置。
```

2024-06-27 06:40 UTC, tianyeeT commented on files/zh-cn/web/api/canvasgradient/addcolorstop/index.md
> +### 向渐变中添加断点
```suggestion
### 向渐变中添加色标
```

2024-06-27 06:40 UTC, tianyeeT commented on files/zh-cn/web/api/canvasgradient/addcolorstop/index.md
> +此示例使用 `addColorStop` 方法向线性 {{domxref("CanvasGradient")}} 对象中添加断点。然后使用该渐变填充矩形。
```suggestion
此示例使用 `addColorStop` 方法向线性 {{domxref("CanvasGradient")}} 对象中添加色标。然后使用该渐变填充矩形。
```

2024-06-27 06:40 UTC, tianyeeT commented on files/zh-cn/web/api/canvasgradient/addcolorstop/index.md
> +{{ EmbedLiveSample('向渐变中添加断点', 700, 180) }}
```suggestion
{{ EmbedLiveSample('向渐变中添加色标', 700, 180) }}
```

2024-07-03 07:55 UTC, skyclouds2001 commented on files/zh-cn/web/api/canvasgradient/addcolorstop/index.md
>  title: CanvasGradient.addColorStop()
```suggestion
title: CanvasGradient：addColorStop() 方法
```

2024-07-03 07:55 UTC, skyclouds2001 commented on files/zh-cn/web/api/canvasgradient/addcolorstop/index.md
> +  - : 如果 `color` 无法解析为 CSS 颜色值{{cssxref("&lt;color&gt;")}}，则抛出此异常。
```suggestion
  - : 如果 `color` 无法解析为 CSS 颜色值 {{cssxref("&lt;color&gt;")}}，则抛出此异常。
```

2024-07-08 02:38 UTC, yin1999 commented on files/zh-cn/web/api/canvasgradient/addcolorstop/index.md
> +**`CanvasGradient.addColorStop()`** 方法添加一个由**偏移值**和**颜色值**指定的色标到渐变。
```suggestion
**`CanvasGradient.addColorStop()`** 方法为给定的 canvas 渐变添加一个由偏移值（`offset`）和颜色值（`color`）指定的色标。
```

2024-07-08 02:38 UTC, yin1999 commented on files/zh-cn/web/api/canvasgradient/addcolorstop/index.md
> +  - : 一个 [CSS](/zh-CN/docs/Web/CSS) 颜色值 {{cssxref("&lt;color&gt;")}}，表示停靠的颜色。
可以不翻译，参见：#12570

```suggestion
  - : 一个 [CSS](/zh-CN/docs/Web/CSS) {{cssxref("&lt;color&gt;")}} 值，表示色标的颜色。
```

2024-07-08 02:38 UTC, yin1999 commented on files/zh-cn/web/api/canvasgradient/addcolorstop/index.md
> +  - : 如果 `color` 无法解析为 CSS 颜色值 {{cssxref("&lt;color&gt;")}}，则抛出此异常。
```suggestion
  - : 如果 `color` 无法解析为 CSS {{cssxref("&lt;color&gt;")}} 值，则抛出此异常。
```

2024-07-10 08:19 UTC, yin1999 approved these changes
Thank you @tianyeeT

2024-07-10 08:20 UTC, merged