[zh-cn]: update the translation of `Games/Introduction`
mdn/translated-content pull request #21937
Opened 2024-06-26 03:55 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-06-27 06:16 UTC, yin1999 requested changes
麻烦修一下损坏的链接：https://pr21937.content.dev.mdn.mozit.cloud/zh-CN/docs/Games/Introduction#_flaws

2024-06-27 06:29 UTC, tianyeeT commented on files/zh-cn/games/introduction/index.md
> +它能够制作的游戏种类可以和桌面端以及原生系统相当。采用现代网页技术和较新的浏览器，完全有可能做出令人印象深刻的顶级页面游戏。我们这里所说的，并不是很久之前就采用 Flash® 制作出的简单卡牌游戏或者多人社交游戏，而是 3D 动作射击游戏、RPG 游戏等等。得益于 [JavaScript](/zh-CN/docs/JavaScript) 实时编译技术性能的大幅提升，以及新开放的 API。在制作运
```suggestion
它能够制作的游戏种类可以和桌面端以及原生系统相当。采用现代网页技术和较新的浏览器，完全有可能做出令人印象深刻的顶级页面游戏。我们这里所说的，并不是很久之前就采用 Flash® 制作出的简单卡牌游戏或者多人社交游戏，而是 3D 动作射击游戏、RPG 游戏等等。得益于 [JavaScript](/zh-CN/docs/Web/JavaScript) 实时编译技术性能的大幅提升，以及新开放的 API。在制作运行在浏览器（或者是基于 [HTML5](/zh-CN/docs/Glossary/HTML5) 技术支持的设备）上的游戏时，我们不用妥协。
```

2024-06-27 06:29 UTC, tianyeeT commented on files/zh-cn/games/introduction/index.md
> +| **图形** | [WebGL](/zh-CN/docs/WebGL) ([OpenGL ES](https://www.khronos.org/opengles/) 2.0)
```suggestion
| **图形** | [WebGL](/zh-CN/docs/Web/API/WebGL_API) ([OpenGL ES](https://www.khronos.org/opengles/) 2.0)                                                                                                                                                                                           |
```

2024-06-27 06:29 UTC, tianyeeT commented on files/zh-cn/games/introduction/index.md
> +| **输入** | [Touch events](/zh-CN/docs/DOM/Touch_events)、[Gamepad API](/zh-CN/docs/Web/API/Gamepad_API/Using_the_Gamepad_API)、设备传感器、[WebRTC](/zh-CN/docs/WebRTC)、[Full Screen API](/zh-CN/docs/Web/API/F
```suggestion
| **输入** | [Touch events](/zh-CN/docs/Web/API/Touch_events)、[Gamepad API](/zh-CN/docs/Web/API/Gamepad_API/Using_the_Gamepad_API)、设备传感器、[WebRTC](/zh-CN/docs/Web/API/WebRTC_API)、[Full Screen API](/zh-CN/docs/Web/API/Fullscreen_API)、[Pointer Lock API](/zh-CN/docs/Web/API/Pointer_Lock_API) |
```

2024-06-27 06:29 UTC, tianyeeT commented on files/zh-cn/games/introduction/index.md
>  | **语言** | [JavaScript](/zh-CN/docs/JavaScript) (或是 C/C++ 使用 [Emscripten](https://github.com/kripken/emscripten/wiki) 来编译成 JavaScript)
```suggestion
| **语言** | [JavaScript](/zh-CN/docs/Web/JavaScript) (或是 C/C++ 使用 [Emscripten](https://github.com/kripken/emscripten/wiki) 来编译成 JavaScript)                                                                                                                                       |
```

2024-06-27 06:29 UTC, tianyeeT commented on files/zh-cn/games/introduction/index.md
> +| **网络** | [WebRTC](/zh-CN/docs/WebRTC) 或 [WebSockets](/zh-CN/docs/Web/API/WebSockets_API)
```suggestion
| **网络** | [WebRTC](/zh-CN/docs/Web/API/WebRTC_API) 或 [WebSockets](/zh-CN/docs/Web/API/WebSockets_API)                                                                                                                                                                                          |
```

2024-06-27 06:29 UTC, tianyeeT commented on files/zh-cn/games/introduction/index.md
> +| **存储** | [IndexedDB](/zh-CN/docs/IndexedDB) 或“云（存储）”
```suggestion
| **存储** | [IndexedDB](/zh-CN/docs/Web/API/IndexedDB_API) 或“云（存储）”                                                                                                                                                                                                                         |
```

2024-06-27 06:29 UTC, tianyeeT commented on files/zh-cn/games/introduction/index.md
> +| **Web**  | [HTML](/zh-CN/docs/HTML)、[CSS](/zh-CN/docs/CSS)、[SVG](/zh-CN/docs/SVG)、[Social API](/zh-CN/docs/Mozilla/Projects/Social_API) (还有其他很多东西！)
```suggestion
| **Web**  | [HTML](/zh-CN/docs/Web/HTML)、[CSS](/zh-CN/docs/Web/CSS)、[SVG](/zh-CN/docs/Web/SVG)（还有其他很多东西！）                                                                                                                   |
```

2024-06-27 06:29 UTC, tianyeeT commented on files/zh-cn/games/introduction/index.md
> +- [HTML](/zh-CN/docs/HTML) 和 [CSS](/zh-CN/docs/CSS)
```suggestion
- [HTML](/zh-CN/docs/Web/HTML) 和 [CSS](/zh-CN/docs/Web/CSS)
```

2024-06-27 06:29 UTC, tianyeeT commented on files/zh-cn/games/introduction/index.md
>  - [HTML audio](/zh-CN/docs/HTML/Element/audio)
```suggestion
- [HTML audio](/zh-CN/docs/Web/HTML/Element/audio)
```

2024-06-27 06:29 UTC, tianyeeT commented on files/zh-cn/games/introduction/index.md
>  - [IndexedDB](/zh-CN/docs/IndexedDB)
```suggestion
- [IndexedDB](/zh-CN/docs/Web/API/IndexedDB_API)
```

2024-06-27 06:29 UTC, tianyeeT commented on files/zh-cn/games/introduction/index.md
>  - [JavaScript](/zh-CN/docs/JavaScript)
```suggestion
- [JavaScript](/zh-CN/docs/Web/JavaScript)
```

2024-06-27 06:29 UTC, tianyeeT commented on files/zh-cn/games/introduction/index.md
>  - [Pointer Lock API](/zh-CN/docs/API/Pointer_Lock_API)
```suggestion
- [Pointer Lock API](/zh-CN/docs/Web/API/Pointer_Lock_API)
```

2024-06-27 06:29 UTC, tianyeeT commented on files/zh-cn/games/introduction/index.md
>  - [SVG](/zh-CN/docs/SVG) (可缩放矢量图形)
```suggestion
- [SVG](/zh-CN/docs/Web/SVG) (可缩放矢量图形)
```

2024-06-27 06:29 UTC, tianyeeT commented on files/zh-cn/games/introduction/index.md
>  - [WebGL](/zh-CN/docs/WebGL)
```suggestion
- [WebGL](/zh-CN/docs/Web/API/WebGL_API)
```

2024-06-27 06:29 UTC, tianyeeT commented on files/zh-cn/games/introduction/index.md
>  - [WebRTC](/zh-CN/docs/WebRTC)
```suggestion
- [WebRTC](/zh-CN/docs/Web/API/WebRTC_API)
```

2024-06-27 06:29 UTC, tianyeeT commented on files/zh-cn/games/introduction/index.md
>  - [WebSockets](/zh-CN/docs/Web/API/WebSockets_API)
```suggestion
- [WebSockets](/zh-CN/docs/Web/API/Web_Workers_API/Using_web_workers)
```

2024-07-04 01:11 UTC, yin1999 approved these changes

2024-07-04 01:11 UTC, merged