[zh-cn]: update the translation of `CanvasRenderingContext2D.createLinearGradient()` method
mdn/translated-content pull request #21992
Opened 2024-06-27 11:12 UTC by tianyeeT

…nearGradient()` method

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-06-28 07:14 UTC, yin1999 requested changes

2024-06-28 07:14 UTC, yin1999 commented on files/zh-cn/web/api/canvasrenderingcontext2d/createlineargradient/index.md
>  title: CanvasRenderingContext2D.createLinearGradient()
标题

2024-06-28 07:14 UTC, yin1999 commented on files/zh-cn/web/api/canvasrenderingcontext2d/createlineargradient/index.md
>    - : 一个根据指定线路初始化的线性 `CanvasGradient` 对象。
没更新

2024-06-28 07:14 UTC, yin1999 commented on files/zh-cn/web/api/canvasrenderingcontext2d/createlineargradient/index.md
> +这个例子使用 `createLinearGradient()` 方法初始化了一个线性渐变。在这个线性渐变中添加了三种色阶。最后，这个渐变被赋值给上下文对应的属性，实现了对矩形的填充。
色标

2024-06-28 07:14 UTC, yin1999 commented on files/zh-cn/web/api/canvasrenderingcontext2d/createlineargradient/index.md
> +// 添加三个颜色停止点
色标

2024-07-07 16:18 UTC, tianyeeT commented on files/zh-cn/web/api/canvasrenderingcontext2d/createlineargradient/index.md
>  title: CanvasRenderingContext2D.createLinearGradient()
```suggestion
title: CanvasRenderingContext2D：createLinearGradient() 方法
```

2024-07-30 01:26 UTC, yin1999 approved these changes

2024-07-30 01:28 UTC, merged