[zh-cn]: update the translation of `CanvasRenderingContext2D.setLineDash()` method
mdn/translated-content pull request #22027
Opened 2024-06-28 00:35 UTC by tianyeeT

…ash()` method

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-06-28 02:18 UTC, yin1999 requested changes

2024-06-28 02:18 UTC, yin1999 commented on files/zh-cn/web/api/canvasrenderingcontext2d/setlinedash/index.md
> +  - : 一个 {{jsxref("Array")}} 数组。一组描述交替绘制线段和间距（坐标空间单位）长度的数字。如果数组元素的数量是奇数，数组的元素会被复制并重复。例如， `[5, 15, 25]` 会变成 `[5, 15, 25, 5, 15, 25]`。如果数组为空，则虚线列表会被清空，线条描边将恢复为实线。
一个 array 数组（array 难道不就是数组吗）？

我之前提过，MDN 原来的翻译不一定正确，在 kuma 时代有太多文档都是在没有审核的情况下就被修改了。所以烦请认真翻译文档的内容，并仔细校对一下。这一处错误是我扫一眼就看出来的。还请再仔细检查一下其他的翻译是否正确。**请注重翻译质量而非数量**

2024-06-28 02:22 UTC, tianyeeT commented on files/zh-cn/web/api/canvasrenderingcontext2d/setlinedash/index.md
> +  - : 一个 {{jsxref("Array")}} 数组。一组描述交替绘制线段和间距（坐标空间单位）长度的数字。如果数组元素的数量是奇数，数组的元素会被复制并重复。例如， `[5, 15, 25]` 会变成 `[5, 15, 25, 5, 15, 25]`。如果数组为空，则虚线列表会被清空，线条描边将恢复为实线。
```suggestion
  - : 一个 {{jsxref("Array")}}。一组描述交替绘制线段和间距（坐标空间单位）长度的数字。如果数组元素的数量是奇数，数组的元素会被复制并重复。例如， `[5, 15, 25]` 会变成 `[5, 15, 25, 5, 15, 25]`。如果数组为空，则虚线列表会被清空，线条描边将恢复为实线。
```

2024-07-07 12:54 UTC, yin1999 commented on files/zh-cn/web/api/canvasrenderingcontext2d/setlinedash/index.md
> +  - : 一个 {{jsxref("Array")}}。一组描述交替绘制线段和间距（坐标空间单位）长度的数字。如果数组元素的数量是奇数，数组的元素会被复制并重复。例如， `[5, 15, 25]` 会变成 `[5, 15, 25, 5, 15, 25]`。如果数组为空，则虚线列表会被清空，线条描边将恢复为实线。
```suggestion
  - : 一个{{jsxref("Array", "数组", "", 1)}}，包含一组描述交替绘制线段和间隙（坐标空间单位）长度的数字。如果数组元素的数量是奇数，数组的元素会被复制和拼接。例如，`[5, 15, 25]` 会变成 `[5, 15, 25, 5, 15, 25]`。如果数组为空，则虚线列表会被清空，线条描边将恢复为实线。
```

2024-07-07 12:54 UTC, yin1999 commented on files/zh-cn/web/api/canvasrenderingcontext2d/setlinedash/index.md
> +Canvas 2D API 的 {{domxref("CanvasRenderingContext2D")}} 接口的 **`setLineDash()`** 方法用于在填充线时使用虚线模式。它使用一组值来指定描述模式的线和间隙的交替长度。
```suggestion
Canvas 2D API 的 {{domxref("CanvasRenderingContext2D")}} 接口的 **`setLineDash()`** 方法用于在描线时使用虚线模式。它使用一组值来指定描述模式的线和间隙的交替长度。
```

2024-07-07 12:54 UTC, yin1999 commented on files/zh-cn/web/api/canvasrenderingcontext2d/setlinedash/index.md
>  > **备注：** 如果要切换回至实线模式，将 dash list 设置为一个空数组即可。
```suggestion
> **备注：** 如果要切换回至实线模式，将虚线列表设置为空数组。
```

2024-07-07 12:59 UTC, yin1999 approved these changes

2024-07-07 12:59 UTC, merged