[zh-cn]: update the translation of `CanvasRenderingContext2D.stroke()` method
mdn/translated-content pull request #22030
Opened 2024-06-28 00:49 UTC by tianyeeT

…` method

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-06-28 02:15 UTC, yin1999 requested changes

2024-06-28 02:15 UTC, yin1999 commented on files/zh-cn/web/api/canvasrenderingcontext2d/stroke/index.md
> +Canvas 2D API 的 **`CanvasRenderingContext2D.stroke()`** 方法用于使用非零环绕规则，根据当前的画线样式，绘制当前或已经存在的路径的方法。
请再对一下翻译

2024-06-28 02:24 UTC, tianyeeT commented on files/zh-cn/web/api/canvasrenderingcontext2d/stroke/index.md
> +Canvas 2D API 的 **`CanvasRenderingContext2D.stroke()`** 方法用于使用非零环绕规则，根据当前的画线样式，绘制当前或已经存在的路径的方法。
```suggestion
Canvas 2D API 的 **`CanvasRenderingContext2D.stroke()`** 方法用于根据当前的画线样式，绘制当前或指定的路径。
```

2024-07-06 11:26 UTC, yin1999 commented on files/zh-cn/web/api/canvasrenderingcontext2d/stroke/index.md
> +Canvas 2D API 的 **`CanvasRenderingContext2D.stroke()`** 方法用于根据当前的画线样式，绘制当前或指定的路径。
```suggestion
Canvas 2D API 的 **`CanvasRenderingContext2D.stroke()`** 方法用于根据当前的描边样式，绘制当前或指定的路径。
```

2024-07-06 11:26 UTC, yin1999 commented on files/zh-cn/web/api/canvasrenderingcontext2d/stroke/index.md
> +描边沿着路径的中心对齐，也就是说，描边的一半位于路径的内侧，另一半位于外侧。
```suggestion
描边与路径的中心对齐，也就是说，描边的一半位于路径的内侧，另一半位于外侧。
```

2024-07-06 11:26 UTC, yin1999 commented on files/zh-cn/web/api/canvasrenderingcontext2d/stroke/index.md
> +  - : 绘制的路径 {{domxref("Path2D")}} 。
```suggestion
  - : 要描边的路径 {{domxref("Path2D")}} 。
```

2024-07-06 11:26 UTC, yin1999 commented on files/zh-cn/web/api/canvasrenderingcontext2d/stroke/index.md
> +这个例子使用 `rect()` 方法创建一个矩形，然后使用 `stroke()` 方法将其绘制到画布上。
```suggestion
此示例使用 `rect()` 方法创建一个矩形，然后使用 `stroke()` 方法将其绘制到画布上。
```

2024-07-06 11:26 UTC, yin1999 commented on files/zh-cn/web/api/canvasrenderingcontext2d/stroke/index.md
> +### 重新描边路径
```suggestion
### 重新对路径进行描边
```

2024-07-06 11:26 UTC, yin1999 commented on files/zh-cn/web/api/canvasrenderingcontext2d/stroke/index.md
> +{{ EmbedLiveSample('重新描边路径', 700, 180) }}
```suggestion
{{ EmbedLiveSample('重新对路径进行描边', 700, 180) }}
```

2024-07-06 11:26 UTC, yin1999 commented on files/zh-cn/web/api/canvasrenderingcontext2d/stroke/index.md
> +通常情况下，每当你想要描边新的内容时，应调用 {{domxref("CanvasRenderingContext2D.beginPath()", "beginPath()")}} 方法。如果不这样做，之前的子路径将保留在当前路径中，并且每次调用 `stroke()` 方法时都会被描边。然而，在某些情况下，这可能是期望的效果。
修改一下

2024-07-15 14:02 UTC, yin1999 commented on files/zh-cn/web/api/canvasrenderingcontext2d/stroke/index.md
> +通常情况下，每当你想要描边新的内容时，应调用 {{domxref("CanvasRenderingContext2D.beginPath()", "beginPath()")}} 方法。如果不这样做，之前的子路径将保留在当前路径中，并且每次调用 `stroke()` 方法时都会被描边。然而，在某些情况下，这可能是期望的效果。
是有什么问题吗

2024-07-15 14:03 UTC, yin1999 commented on files/zh-cn/web/api/canvasrenderingcontext2d/stroke/index.md
> +  - : 要描边的路径 {{domxref("Path2D")}} 。
```suggestion
  - : 要描边的 {{domxref("Path2D")}} 路径。
```

2024-07-31 05:58 UTC, yin1999 approved these changes

2024-07-31 05:58 UTC, merged