[zh-cn]: update the translation of `Document.exitFullscreen()` method
mdn/translated-content pull request #22048
Opened 2024-06-28 05:02 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-06-28 06:54 UTC, PassionPenguin requested changes

2024-06-28 06:54 UTC, PassionPenguin commented on files/zh-cn/web/api/document/exitfullscreen/index.md
> +一个 {{jsxref("Promise")}}，在 {{Glossary("user agent")}} 完成退出全屏模式后解决。如果在尝试退出全屏模式时发生错误，promise 的 `catch()` 处理程序将被调用。
```suggestion
一个 {{jsxref("Promise")}}，在{{Glossary("user agent", "用户代理")}}完成退出全屏模式后被兑现。如果在尝试退出全屏模式时发生错误，Promise 的 `catch()` 处理程序将被调用。
```

2024-06-28 07:06 UTC, yin1999 commented on files/zh-cn/web/api/document/exitfullscreen/index.md
> +一个 {{jsxref("Promise")}}，在 {{Glossary("user agent")}} 完成退出全屏模式后解决。如果在尝试退出全屏模式时发生错误，promise 的 `catch()` 处理程序将被调用。
handler => 处理器

2024-06-28 07:07 UTC, yin1999 commented on files/zh-cn/web/api/document/exitfullscreen/index.md
> +- {{ cssxref(":fullscreen") }} and {{cssxref("::backdrop")}}
and

2024-06-28 07:10 UTC, tianyeeT commented on files/zh-cn/web/api/document/exitfullscreen/index.md
> +- {{ cssxref(":fullscreen") }} and {{cssxref("::backdrop")}}
```suggestion
- {{ cssxref(":fullscreen") }} 和 {{cssxref("::backdrop")}}
```

2024-06-28 07:10 UTC, tianyeeT commented on files/zh-cn/web/api/document/exitfullscreen/index.md
> +一个 {{jsxref("Promise")}}，在 {{Glossary("user agent")}} 完成退出全屏模式后解决。如果在尝试退出全屏模式时发生错误，promise 的 `catch()` 处理程序将被调用。
```suggestion
一个 {{jsxref("Promise")}}，在{{Glossary("user agent", "用户代理")}}完成退出全屏模式后被兑现。如果在尝试退出全屏模式时发生错误，promise 的 `catch()` 处理器将被调用。
```

2024-07-13 12:35 UTC, yin1999 approved these changes

2024-07-13 12:35 UTC, yin1999 commented on files/zh-cn/web/api/document/exitfullscreen/index.md
> +- [全屏指南](/zh-CN/docs/Web/API/Fullscreen_API/Guide)
```suggestion
- [全屏 API](/zh-CN/docs/Web/API/Fullscreen_API)
- [全屏 API 指南](/zh-CN/docs/Web/API/Fullscreen_API/Guide)
```

2024-07-13 12:37 UTC, merged