[zh-cn]: update the translation of `Permissions-Policy.autoplay` directive
mdn/translated-content pull request #22052
Opened 2024-06-28 05:58 UTC by tianyeeT

…ctive

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-06-28 07:01 UTC, yin1999 requested changes
https://github.com/mdn/translated-content/pull/22053#pullrequestreview-2147208712

2024-07-02 02:35 UTC, skyclouds2001 commented on files/zh-cn/web/http/headers/permissions-policy/autoplay/index.md
>  title: "Permissions-Policy: autoplay"
参考 https://github.com/mdn/translated-content/pull/22049#discussion_r1661735586

2024-07-02 02:35 UTC, skyclouds2001 commented on files/zh-cn/web/http/headers/permissions-policy/autoplay/index.md
> +- [Permissions Policy](/zh-CN/docs/Web/HTTP/Permissions_Policy)
```suggestion
- [权限策略](/zh-CN/docs/Web/HTTP/Permissions_Policy)
```

2024-07-07 15:52 UTC, tianyeeT commented on files/zh-cn/web/http/headers/permissions-policy/autoplay/index.md
> +具体来说，如果定义的策略阻止使用此功能并且没有用户手势，{{domxref("HTMLMediaElement.play()")}} 返回的 {{jsxref("Promise")}} 将被 {{domxref("DOMException")}} 拒绝。{{HTMLElement("audio")}} 和 {{HTMLElement("video")}} 元素上的 [`autoplay`](/z
```suggestion
具体来说，如果定义的策略阻止使用此特性并且没有用户手势，{{domxref("HTMLMediaElement.play()")}} 返回的 {{jsxref("Promise")}} 将被 {{domxref("DOMException")}} 拒绝。{{HTMLElement("audio")}} 和 {{HTMLElement("video")}} 元素上的 [`autoplay`](/zh-CN/docs/Web/HTML/Element/audio#autoplay) 属性将被忽略。
```

2024-07-07 15:52 UTC, tianyeeT commented on files/zh-cn/web/http/headers/permissions-policy/autoplay/index.md
> +  - : 允许使用该功能的来源列表。请参阅 [`Permissions-Policy` > 语法](/zh-CN/docs/Web/HTTP/Headers/Permissions-Policy#语法)了解更多详细信息。
```suggestion
  - : 允许使用该特性的来源列表。请参阅 [`Permissions-Policy` > 语法](/zh-CN/docs/Web/HTTP/Headers/Permissions-Policy#语法)了解更多详细信息。
```

2024-07-08 03:13 UTC, yin1999 reviewed
nits

2024-07-08 05:03 UTC, yin1999 approved these changes

2024-07-08 05:03 UTC, merged