[zh-cn]: create the translation of `Permission-Policy.bluetooth` directive
mdn/translated-content pull request #22054
Opened 2024-06-28 06:10 UTC by tianyeeT

…ctive

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-06-28 06:21 UTC, yin1999 commented on files/zh-cn/web/http/headers/permissions-policy/bluetooth/index.md
> +具体来说，如果定义的策略不允许使用此功能，则由 {{domxref('Navigator.bluetooth')}} 返回的 {{domxref('Bluetooth')}} 对象的方法将会阻止访问：
feature => 特性。其他的几个 PR 也请麻烦改一下

2024-06-28 06:22 UTC, tianyeeT commented on files/zh-cn/web/http/headers/permissions-policy/bluetooth/index.md
> +具体来说，如果定义的策略不允许使用此功能，则由 {{domxref('Navigator.bluetooth')}} 返回的 {{domxref('Bluetooth')}} 对象的方法将会阻止访问：
收到

2024-06-28 06:47 UTC, PassionPenguin requested changes

2024-06-28 06:47 UTC, PassionPenguin commented on files/zh-cn/web/http/headers/permissions-policy/bluetooth/index.md
> +它可以通过发送以下 HTTP 响应头来定义权限策略：
```suggestion
SecureCorp Inc. 希望在所有浏览上下文中禁用 Web Bluetooth API，除了其自身的来源和 `https://example.com` 的来源。它可以通过发送以下 HTTP 响应头来定义权限策略：
```

2024-06-28 06:47 UTC, PassionPenguin commented on files/zh-cn/web/http/headers/permissions-policy/bluetooth/index.md
> +它可以通过发送以下 HTTP 响应头来定义权限策略：
```suggestion
FastCorp Inc. 希望为除了特定的 `<iframe>` 的所有跨来源的子框架禁用 `bluetooth`。它可以通过发送以下 HTTP 响应头来定义权限策略：
```

2024-06-28 07:01 UTC, yin1999 requested changes
https://github.com/mdn/translated-content/pull/22053#pullrequestreview-2147208712

2024-07-02 02:42 UTC, skyclouds2001 commented on files/zh-cn/web/http/headers/permissions-policy/bluetooth/index.md
> +- [Permissions Policy](/zh-CN/docs/Web/HTTP/Permissions_Policy)
```suggestion
- [权限策略](/zh-CN/docs/Web/HTTP/Permissions_Policy)
```

2024-07-02 02:42 UTC, skyclouds2001 commented on files/zh-cn/web/http/headers/permissions-policy/bluetooth/index.md
> +title: "Permissions-Policy: bluetooth"
参考 https://github.com/mdn/translated-content/pull/22049#discussion_r1661735586

2024-07-07 15:49 UTC, tianyeeT commented on files/zh-cn/web/http/headers/permissions-policy/bluetooth/index.md
> +具体来说，如果定义的策略不允许使用此功能，则由 {{domxref('Navigator.bluetooth')}} 返回的 {{domxref('Bluetooth')}} 对象的方法将会阻止访问：
```suggestion
具体来说，如果定义的策略不允许使用此特性，则由 {{domxref('Navigator.bluetooth')}} 返回的 {{domxref('Bluetooth')}} 对象的方法将会阻止访问：
```

2024-07-07 15:49 UTC, tianyeeT commented on files/zh-cn/web/http/headers/permissions-policy/bluetooth/index.md
> +  - : 允许使用该功能的来源列表。请参阅 [`Permissions-Policy` > 语法](/zh-CN/docs/Web/HTTP/Headers/Permissions-Policy#语法)了解更多详细信息。
```suggestion
  - : 允许使用该特性的来源列表。请参阅 [`Permissions-Policy` > 语法](/zh-CN/docs/Web/HTTP/Headers/Permissions-Policy#语法)了解更多详细信息。
```

2024-07-07 15:49 UTC, tianyeeT commented on files/zh-cn/web/http/headers/permissions-policy/bluetooth/index.md
> +`<iframe>` 属性可以有选择地在某些框架中启用功能，而在其他框架中禁用这些功能，即使这些框架包含来自同一来源的文档。
```suggestion
`<iframe>` 属性可以有选择地在某些框架中启用特性，而在其他框架中禁用这些特性，即使这些框架包含来自同一来源的文档。
```

2024-07-08 02:59 UTC, yin1999 reviewed
nits:

2024-07-08 02:59 UTC, yin1999 commented on files/zh-cn/web/http/headers/permissions-policy/bluetooth/index.md
> +SecureCorp Inc. 希望在所有浏览上下文中禁用 Web Bluetooth API，除了其自身的来源和 `https://example.com` 的来源。它可以通过发送以下 HTTP 响应头来定义权限策略：
```suggestion
SecureCorp Inc. 希望在所有浏览上下文中禁用 Web Bluetooth API，除了其自身的来源和来源 `https://example.com`。它可以通过发送以下 HTTP 响应标头来定义权限策略：
```

2024-07-08 02:59 UTC, yin1999 commented on files/zh-cn/web/http/headers/permissions-policy/bluetooth/index.md
> +FastCorp Inc. 希望为除了特定的 `<iframe>` 的所有跨来源的子框架禁用 `bluetooth`。它可以通过发送以下 HTTP 响应头来定义权限策略：
```suggestion
FastCorp Inc. 希望为除了特定的 `<iframe>` 的所有跨来源的子框架禁用 `bluetooth`。它可以通过发送以下 HTTP 响应标头来定义权限策略：
```

2024-07-08 02:59 UTC, yin1999 commented on files/zh-cn/web/http/headers/permissions-policy/bluetooth/index.md
> +然后在 `<iframe>` 元素上包含一个 {{HTMLElement('iframe','allow','#Attributes')}} 属性：
```suggestion
然后在 `<iframe>` 元素上包含一个 {{HTMLElement('iframe','allow','#属性')}} 属性：
```

2024-07-08 05:34 UTC, yin1999 approved these changes

2024-07-08 05:35 UTC, merged