[ko] with 문서 신규 번역
mdn/translated-content pull request #22055
Opened 2024-06-28 12:19 UTC by witch-factory

### Description

deprecated된 명령문이기는 하지만 기존에 한국어로 존재하지 않던 문서 [with](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with)을 신규 번역하였습니다.

### Motivation

### Additional details

### Related issues and pull requests

2024-06-29 06:00 UTC, wisedog commented
@1ilsang 이 PR 린트 돌다 만것 같은데 원인이 뭘까요?

2024-06-29 17:40 UTC, 1ilsang commented
@wisedog 님

현재는 [린트가 깨진 것으로 보이는데요](https://github.com/mdn/translated-content/actions/runs/9712658208/job/26807841502?pr=22055), 이 부분을 질문 주신 게 맞을까요?

제가 이전에 잠깐 봤을 때 린트 자체가 실행되지 않은 것 같았는데 이 부분을 질문 주신 걸까요?

2024-06-29 18:05 UTC, witch-factory commented
Preview URL에서 확인해 보았을 때 최상단의 `{{jsSidebar("Statements")}}`와 맨 밑의 같이 보기 항목의 `{{jsxref("Symbol.unscopables")}}`(번역 문서가 없는 문서로 연결)에서 문제가 생기는 것 같습니다.

원본에서는 `{{jsSidebar("Statements")}}`를 사용하고 있지만 다른 번역 문서에서는 jsSidebar 대신 `{{JSRef}}`를 사용하고 문서로의 링크를 직접 걸고 있는 듯 한데, 그렇게 수정하면 어떨까요?

2024-06-30 11:49 UTC, witch-factory commented
다시 확인해 보았더니 기존 문서와 같은 양식이네요. 린트를 다시 실행시킬 방법이 없을까요?

2024-06-30 13:24 UTC, wisedog commented
> 다시 확인해 보았더니 제가 생각한 게 아니었고 `{{jsSidebar("Statements")}}`를 쓴 다른 번역 문서도 많네요. 린트를 다시 실행시킬 방법이 없을까요?

해당 브랜치에 추가 커밋하면 아마 린트가 다시 실행될겁니다.

2024-06-30 13:40 UTC, witch-factory commented
감사합니다! 다시 커밋하였습니다.

2024-06-30 16:05 UTC, 1ilsang requested changes
@witch-factory 님 안녕하세요. 기여해주셔서 감사합니다! 💯

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

질문이나 도움이 필요하시다면 언제든 멘션 부탁드리겠습니다.

2024-06-30 16:05 UTC, 1ilsang commented on files/ko/web/javascript/reference/statements/with/index.md
> +ECMAScript 5 환경에서 `f([1, 2, 3], obj)`를 호출하면, `with` 문 내의 `values` 참조는 `obj`로 이행됩니다. 그러나 ECMAScript 2015는 Array.prototype에 [values](/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/values) 속성을 도
```suggestion
  ECMAScript 5 환경에서 `f([1, 2, 3], obj)`를 호출하면, `with` 문 내의 `values` 참조는 `obj`로 이행됩니다. 그러나 ECMAScript 2015는 `Array.prototype`에 [`values`](/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/values) 속성을 도입합니다(따라서 모든 배열에서 `values` 속성을 사용할 수 있게 됩니다). 따라서 환경을 업그레이드하면 `with` 문 내의 `values` 참조는 `[1, 2, 3].values`로 이행되며, 이는 버그를 일으킬 가능성이 큽니다.
  이 특정 예제에서는 `values`가 [`Array.prototype[@@unscopables]`](/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/@@unscopables)에 의해 스코프에 포함되지 않도록 정의되어 있어 해당 코드의 `values`는 여전히 `values` 매개변수로 올바르게 이행됩니다. 만약 스코프에 포함되지 않도록 정의되지 않았다면, 이는 디버깅하기 어려운 문제가 될 수 있습니다.
```

1. 줄 수는 원본과 동일하게 해주세요. 관련 논의는 [여기](https://github.com/orgs/mdn/discussions/655#discussioncomment-9251708)에서 확인할 수 있습니다.
2. 원문과 형태를 동일하게 유지해 주세요. `` ` `` 백틱이 빠져있습니다.

2024-07-01 00:33 UTC, witch-factory commented
@1ilsang  안녕하세요. 리뷰해 주신 부분들을 반영하였습니다. 확인 부탁드립니다. 그리고 unscopables를 "스코프 지정 불가능"으로 변경하였습니다. 

스코프 지정 불가능이라는 번역은 [Array.prototype[@@unscopables]](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/@@unscopables)에서 unscopable을 "범위 지정 불가능"으로 번역하고 있는 걸 참고하였습니다. [용어 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md)에서는 scope를 범위로 번역하고 있으나, 글의 다른 부분에서 "스코프 체인"이라는 단어가 반복적으로 쓰이는데 이를 범위 체인과 같이 변경하는 것은 어색하다고 보였습니다.

하지만 용어 가이드를 따라 scope를 범위로 일괄적으로 번역하거나 scope chain을 스코프 체인으로, unscopable은 범위 지정 불가능으로 하는 등 다른 방식이 낫다면 그대로 반영하겠습니다!

2024-07-01 14:44 UTC, 1ilsang approved these changes
@witch-factory 님 

단일 문서 내의 용어를 통일하는 것이 더 좋다고 느낍니다. 따라서 "스코프 체인 / 스코프 지정 불가능"으로 번역되어도 문제없어 보입니다.

LGTM 고생하셨습니다. 👍

2024-07-01 14:49 UTC, merged