[ko] using css counters 최신화
mdn/translated-content pull request #22085
Opened 2024-07-01 01:46 UTC by givvemee

### Description

기존 한국어 문서 [CSS 카운터 사용하기](https://developer.mozilla.org/ko/docs/Web/CSS/CSS_counter_styles/Using_CSS_counters)를 최신화합니다. 

### Motivation

### Additional details

`style containment` 를 `스타일 통제` 로 번역했는데, 이게 적절한지 아직 고민입니다....

### Related issues and pull requests

2024-07-30 08:07 UTC, sunhpark42 requested changes
안녕하세요 @givvemee 님 리뷰가 늦어져서 죄송합니다.
코멘트 확인 부탁드립니다. 감사합니다. (style containment 도 코멘트로 남겨두었습니다. )

2024-07-30 08:07 UTC, sunhpark42 commented on files/ko/web/css/css_counter_styles/using_css_counters/index.md
> +사용자가 지정한 카운터가 아니라면 `list-item` 은 카운터가 역순인지 아닌지 여부에 따라 자동적으로 각각의 요소에 대하여 1씩 증가하거나 감소하게 됩니다.
```suggestion
사용자가 지정한 카운터와는 다르게 `list-item` 은 카운터가 역순인지 아닌지 여부에 따라 자동적으로 각각의 요소에 대하여 1씩 증가하거나 감소하게 됩니다.
```
는 어떨까요?

2024-07-30 08:07 UTC, sunhpark42 commented on files/ko/web/css/css_counter_styles/using_css_counters/index.md
> +카운터의 속성은 {{cssxref("contain")}} 속성에 상세하게 설명된 스타일 통제를 사용하여 특정 요소 내에서 범위를 지정할 수 있습니다.
"스타일 포함"이나 "스타일 격리" 는 어떨까요?
특정 요소의 스타일이 해당 요소의 컨텍스트 안에만 영향을 미치도록 하여 다른 요소에 영향을 주지 않도록 하는 의미라서, 제안 드려봅니다.

2024-07-31 08:26 UTC, givvemee commented on files/ko/web/css/css_counter_styles/using_css_counters/index.md
> +사용자가 지정한 카운터가 아니라면 `list-item` 은 카운터가 역순인지 아닌지 여부에 따라 자동적으로 각각의 요소에 대하여 1씩 증가하거나 감소하게 됩니다.
둘의 차이가 뭘까요?

2024-07-31 08:26 UTC, givvemee commented on files/ko/web/css/css_counter_styles/using_css_counters/index.md
> +사용자가 지정한 카운터가 아니라면 `list-item` 은 카운터가 역순인지 아닌지 여부에 따라 자동적으로 각각의 요소에 대하여 1씩 증가하거나 감소하게 됩니다.
의미는 같고 문장만 다른데, 제안 주신 이유가 궁금해요! ㅎ_ㅎ

2024-08-10 08:55 UTC, sunhpark42 commented on files/ko/web/css/css_counter_styles/using_css_counters/index.md
> +사용자가 지정한 카운터가 아니라면 `list-item` 은 카운터가 역순인지 아닌지 여부에 따라 자동적으로 각각의 요소에 대하여 1씩 증가하거나 감소하게 됩니다.
```
Like other counters, this has a default initial value of 0 for upward counters and "number of items" for reversed counters.
Unlike author-created counters, `list-item` _automatically_ increments or decrements by one for each list element, depending on whether or not the counter is reversed.
```

원문위 위와 같고, Like/unlike의 의미가 위에서 ~처럼으로 번역이 되었기 때문에, 아니라면의 If (만약에) 의 의미보다는 ~~과는 다르게의 의미가 강하다고 생각했고 Like 번역과 맥락이 맞으면 좋지 않을까 했습니다~!

@givvemee 님이 보시기에 크게 차이가 없다고 생각되면, resolve하고 수정하지 않아도 되는 부분일 것 같아 말씀 부탁드립니다 :)

2024-09-29 12:36 UTC, sunhpark42 approved these changes
안녕하세요 @givvemee 님~ 요거 확인이 늦었습니다. 코멘트에 남겨주신 부분은 수정되지 않아도 괜찮은 부분이라 그 외 수정 내용은 확인하였습니다. 확인이 늦어 죄송합니다.
감사합니다!

2024-09-29 12:37 UTC, merged