[ko] using css gradient 번역
mdn/translated-content pull request #22105
Opened 2024-07-02 06:46 UTC by givvemee

### Description

기존에 한국어로 존재하지 않던 문서 [Using CSS gradients](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_images/Using_CSS_gradients#using_conic_gradients) 를 번역합니다 ......................... 

### Motivation

### Additional details

### Related issues and pull requests

2024-07-02 23:14 UTC, wisedog commented
왜 .... 이 많이 붙었는지는 확실히 알겠습니다. 좀 시간을 가지고 보도록 할께요. 

일단 그림은 같이 PR 포함하지 않으셔도 됩니다.

2024-07-07 08:41 UTC, wisedog requested changes
이 정도로 하겠습니다. 긴 글인데 정말 고생하셨습니다. 몇 가지만 수정 부탁드립니다. 

특히 이미지는 중앙에서 제어하니까 지우셔도, 아니 지우셔야 합니다. (다른 언어 레포를 가시면 확실히 아실 수 있습니다)

감사합니다!

2024-07-07 08:41 UTC, wisedog commented on files/ko/web/css/css_images/using_css_gradients/index.md
> +By default, the different color stops you specify are spaced equidistantly around the circle. You can position the starting angle of the conic gradient using the "from" keyword at the beginning follo
아앗 여기 해석이..

2024-07-07 08:41 UTC, wisedog commented on files/ko/web/css/css_images/using_css_gradients/index.md
> +색상 정지 지점을 기본값으로만 이용하지 않아도 됩니다. 위치를 미세하기 조정하기 위해 각각의 색상 정지 지점에 0개, 하나, 혹은 두 개의 백분율, 혹은 방사형과 선형의 경우에는 절대값을 부여할 수 있습니다. 위치를 백분율로 지정할 경우에는, `0%` 은 시작 지점이 되는 반면 `100%` 는 끝 지점을 표현합니다. 하지만, 의도한대로 효과를 내고 싶다면
이 부분이 원문 `You don't have to leave your color stops at their default positions.` 인데요. 
제가 CSS를 잘 몰라서 물어봅니다만, `default position`을 `기본 값`이라 해석하신 이유가 궁금합니다. 직역하자면 기본 위치인데요.

2024-07-07 08:41 UTC, wisedog commented on files/ko/web/css/css_images/using_css_gradients/index.md
> +색상 정지 지점을 기본값으로만 이용하지 않아도 됩니다. 위치를 미세하기 조정하기 위해 각각의 색상 정지 지점에 0개, 하나, 혹은 두 개의 백분율, 혹은 방사형과 선형의 경우에는 절대값을 부여할 수 있습니다. 위치를 백분율로 지정할 경우에는, `0%` 은 시작 지점이 되는 반면 `100%` 는 끝 지점을 표현합니다. 하지만, 의도한대로 효과를 내고 싶다면
또한 `위치를 미세하기 조정하기 위해 각각의 색상 정지 지점에 0개, 하나, 혹은 두 개의 백분율, 혹은 방사형과 선형의 경우에는 절대값을 부여할 수 있습니다. ` 인데, 원문은 
`To fine-tune their locations, you can give each one zero, one, or two percentage or, for radial and linear gradients, absolute length values.`

입니다. 여기서 해석을 각각 `0, 1 혹은 2퍼센트가` 맞지 않을까요? 또한 `절대값`보다는 `절대 길이`가 맞지 않나 싶습니다.

2024-07-07 08:41 UTC, wisedog commented on files/ko/web/css/css_images/using_css_gradients/index.md
> +기본적으로 그라디언트는 두 가지 인접한 색상 사이에서 균등하게 진행이 되며, 그 중간 지점은 두 색상 사이 색상 정지 지점의 중간 색상 값이 됩니다. 두 색상 정지 지점 사이의 {{Glossary("interpolation")}}이나 진행은 색상 힌트 위치를 포함시켜 제어할 수 있습니다. 이 예제에서는 라임과 푸른색 사이 그라디언트가 50% 지점이 아닌
`{{Glossary("interpolation")}}` 보다는 `{{Glossary("interpolation", "보간법")}}` 이라 하면 해당 링크의 텍스트를 변경할 수 있습니다.

2024-07-07 12:02 UTC, givvemee commented on files/ko/web/css/css_images/using_css_gradients/index.md
> +색상 정지 지점을 기본값으로만 이용하지 않아도 됩니다. 위치를 미세하기 조정하기 위해 각각의 색상 정지 지점에 0개, 하나, 혹은 두 개의 백분율, 혹은 방사형과 선형의 경우에는 절대값을 부여할 수 있습니다. 위치를 백분율로 지정할 경우에는, `0%` 은 시작 지점이 되는 반면 `100%` 는 끝 지점을 표현합니다. 하지만, 의도한대로 효과를 내고 싶다면
@wisedog 
위에 있던 
> 이 부분이 원문 You don't have to leave your color stops at their default positions. 인데요.
제가 CSS를 잘 몰라서 물어봅니다만, default position을 기본 값이라 해석하신 이유가 궁금합니다. 직역하자면 기본 위치인데요.

와 같이 답변 드리자면, 

정지 지점 < 이라는 단어 자체가 위치를 내포하고 있기 때문에 default position 은 기본 값으로 해석했는데, 기본 위치로 변경하는 것이 더 좋아 보입니다. 같은 맥락으로 절대값도 절대 길이로 변경합니다.
그런데 0, 1 혹은 2퍼센트는 ... 의견이 조금 다릅니다. 0% 와 100% 사이의 여러 중간 값들을 취할 수 있다는 맥락으로 생각하면 0개, 한 개, 혹은 두 개의 백분율이라고 해석되어야 하는 게 맞지 않나 싶어요.

2024-07-07 14:18 UTC, wisedog commented on files/ko/web/css/css_images/using_css_gradients/index.md
> +색상 정지 지점을 기본값으로만 이용하지 않아도 됩니다. 위치를 미세하기 조정하기 위해 각각의 색상 정지 지점에 0개, 하나, 혹은 두 개의 백분율, 혹은 방사형과 선형의 경우에는 절대값을 부여할 수 있습니다. 위치를 백분율로 지정할 경우에는, `0%` 은 시작 지점이 되는 반면 `100%` 는 끝 지점을 표현합니다. 하지만, 의도한대로 효과를 내고 싶다면
음.. 그렇군요 알겠습니다!

2024-07-07 14:18 UTC, wisedog approved these changes

2024-07-07 14:18 UTC, merged