[fr] Unify links to Mozilla Firefox source code
mdn/translated-content pull request #22115
Opened 2024-07-02 15:56 UTC by leon-win

### Description

This PR unifies links to Mozilla Firefox source code by using searchfox.org instead of hg.mozilla.org and obsolete dxr.mozilla.org, mxr.mozilla.org for `fr` locale.

### Related issues and pull requests

Relates to https://github.com/mdn/content/pull/33585

2024-07-06 15:08 UTC, cw118 requested changes
Thank you @leon-win ! Just one small comment :)

2024-07-06 15:08 UTC, cw118 commented on files/fr/mdn/writing_guidelines/writing_style_guide/code_style_guide/shell/index.md
> +# This may take a while...
```suggestion
# Cela peut prendre un certain temps…
```

2024-07-07 17:39 UTC, leon-win commented
> Thank you @leon-win ! Just one small comment :)

Done :ok_hand: ))

2024-07-08 22:47 UTC, cw118 approved these changes
This is great, thank you so much!

2024-07-08 22:47 UTC, merged