adhere toの誤訳の修正
mdn/translated-content pull request #22157
Opened 2024-07-04 08:40 UTC by mukaiizawa

### Description

「adhere to」を「吸着」と訳しているが、この文脈では「遵守」とするのが適切に思われます。

### Motivation

### Additional details

### Related issues and pull requests

2024-07-11 13:43 UTC, mfuji09 requested changes
1件を確認してください。

2024-07-11 13:43 UTC, mfuji09 commented on files/ja/web/html/element/input/date/index.md
> +> **メモ:** ユーザーによって入力されたデータがstep設定従わない場合、{{Glossary("user agent", "ユーザーエージェント")}}は最も近い有効な値に丸めるおそれがあり、どちらも同じ距離の場合は正の無限大へ丸められます。
提案された訳文に誤りがあったので、修正を提案します。
（原文に無限大と解釈できる表現は見当たらず、前の文のほうがより適切なように思います。）
また、日本語と英数字の間は1文字の空白を空けてください。

```suggestion
> **メモ:** ユーザーによって入力されたデータが step 設定に従っていない場合、{{Glossary("user agent", "ユーザーエージェント")}}は最も近い有効な値に丸める可能性があり、同じ距離の値が 2 つあった場合は、正の方向の値を優先します。
```

2024-07-11 14:10 UTC, mukaiizawa commented
ありがとうございます。
修正案を取り込みました。

2024-07-12 06:50 UTC, mfuji09 approved these changes
OKです。

2024-07-12 06:50 UTC, merged