[zh-CN] add web api url.parse() translation
mdn/translated-content pull request #22159
Opened 2024-07-04 09:58 UTC by little-huang

### Description

translate for url.parse() method

### Motivation

### Additional details

### Related issues and pull requests

2024-07-05 03:41 UTC, skyclouds2001 commented on files/zh-cn/web/api/url/parse_static/index.md
> +{{domxref("URL")}} 接口的 parse() 静态方法它返回一个根据参数定义的新创建的 {{domxref("URL")}} 对象。
```suggestion
{{domxref("URL")}} 接口的 `URL.parse()` 静态方法返回一个根据参数定义的新创建的 {{domxref("URL")}} 对象。
```

2024-07-05 03:41 UTC, skyclouds2001 commented on files/zh-cn/web/api/url/parse_static/index.md
> +[解析 URL 的相对引用](/zh-CN/docs/Web/API/URL_API/Resolving_relative_references) 和 [`URL()` 构造函数](/zh-CN/docs/Web/API/URL/URL#示例) 提供了更多示例，演示了不同的 `url` 和 `base` 值如何解析为最终的绝对 URL（尽管主要使用 `URL()`）。
```suggestion
[解析 URL 的相对引用](/zh-CN/docs/Web/API/URL_API/Resolving_relative_references)和 [`URL()` 构造函数](/zh-CN/docs/Web/API/URL/URL#示例)提供了更多示例，演示了不同的 `url` 和 `base` 值如何解析为最终的绝对 URL（尽管主要使用 `URL()`）。
```

2024-07-05 05:10 UTC, little-huang commented on files/zh-cn/web/api/url/parse_static/index.md
> +{{domxref("URL")}} 接口的 parse() 静态方法它返回一个根据参数定义的新创建的 {{domxref("URL")}} 对象。
ok , it’s been changed. thank you.

2024-07-05 05:10 UTC, little-huang commented on files/zh-cn/web/api/url/parse_static/index.md
> +[解析 URL 的相对引用](/zh-CN/docs/Web/API/URL_API/Resolving_relative_references) 和 [`URL()` 构造函数](/zh-CN/docs/Web/API/URL/URL#示例) 提供了更多示例，演示了不同的 `url` 和 `base` 值如何解析为最终的绝对 URL（尽管主要使用 `URL()`）。
ok , it’s been changed. thank you.

2024-07-10 01:31 UTC, jasonren0403 requested changes
一些需要修改的地方

2024-07-10 01:31 UTC, jasonren0403 commented on files/zh-cn/web/api/url/parse_static/index.md
> +short-title: parse()
https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md#元数据

本地化短标题与英语文档相同的情况下无需该元数据

```suggestion
```

2024-07-10 01:31 UTC, jasonren0403 commented on files/zh-cn/web/api/url/parse_static/index.md
> +slug: Web/API/URL/parse_static
同步文档后可以加上 `l10n.sourceCommit` 

```suggestion
slug: Web/API/URL/parse_static
l10n:
  sourceCommit: 6592d9b17990c03bffe810c4696f6161f9c49063
```

2024-07-10 01:31 UTC, jasonren0403 commented on files/zh-cn/web/api/url/parse_static/index.md
> +[解析 URL 的相对引用](/zh-CN/docs/Web/API/URL_API/Resolving_relative_references)和[`URL()` 构造函数](/zh-CN/docs/Web/API/URL/URL#示例)提供了更多示例，演示了不同的 `url` 和 `base` 值如何解析为最终的绝对 URL（尽管主要使用 `URL()`）。
```suggestion
[解析 URL 的相对引用](/zh-CN/docs/Web/API/URL_API/Resolving_relative_references)和 [`URL()` 构造函数](/zh-CN/docs/Web/API/URL/URL#示例)提供了更多示例，演示了不同的 `url` 和 `base` 值如何解析为最终的绝对 URL（尽管主要使用 `URL()`）。
```

2024-07-10 01:31 UTC, jasonren0403 commented on files/zh-cn/web/api/url/parse_static/index.md
> +  - : 一个字符串或任何其他具有 {{Glossary("stringifier")}} 的对象，表示绝对 URL 或 URL 的相对引用。如果 `url` 是相对引用，则需要 `base`，并用于解析最终的 URL。如果 `url` 是绝对 URL，则不会使用给定的 `base` 来创建结果 URL。
```suggestion
  - : 一个字符串或任何其他具有{{Glossary("stringifier", "字符串化器")}}的对象，表示绝对 URL 或 URL 的相对引用。如果 `url` 是相对引用，则 `base` 是必需的，并用于解析最终的 URL。如果 `url` 是绝对 URL，则不会使用给定的 `base` 来创建结果 URL。
```

2024-07-10 01:31 UTC, jasonren0403 commented on files/zh-cn/web/api/url/parse_static/index.md
> +下一步，我们检查 `URL.parse()` 方法是否受支持，使用条件 `"parse" in URL`。如果该方法受支持，我们会记录检查绝对 URL 的结果、相对引用和基础 URL 的结果、具有更[复杂基础 URL](/zh-CN/docs/Web/API/URL_API/Resolving_relative_references)的相对引用的结果、具有有效基础 URL 的有效绝对 URL（基
```suggestion
首先，我们使用条件 `"parse" in URL` 检查是否支持 `URL.parse()` 方法。如果该方法受支持，我们会记录检查绝对 URL 的结果、相对引用和基础 URL 的结果、具有更[复杂基础 URL](/zh-CN/docs/Web/API/URL_API/Resolving_relative_references)的相对引用的结果、具有有效基础 URL 的有效绝对 URL（基础 URL 未使用）的结果，以及导致方法返回 `null` 的无效基础 URL 的结果。
```

2024-07-10 01:31 UTC, jasonren0403 commented on files/zh-cn/web/api/url/parse_static/index.md
> +```html
```suggestion
```html hidden
```

2024-07-10 01:31 UTC, jasonren0403 commented on files/zh-cn/web/api/url/parse_static/index.md
> +```css
```suggestion
```css hidden
```

2024-07-10 01:31 UTC, jasonren0403 commented on files/zh-cn/web/api/url/parse_static/index.md
> +首先我们定义了一个 HTML `<pre>` 元素用于日志记录，并提供了一个记录方法 `log()`。
英语文档没有这句话

```suggestion
```

2024-07-10 01:31 UTC, jasonren0403 commented on files/zh-cn/web/api/url/parse_static/index.md
> +  // （仅使用方案和域名来解析 URL）
```suggestion
  //（仅使用协议和域名来解析 URL）
```

2024-07-11 00:56 UTC, little-huang commented
> 一些需要修改的地方

ok 感谢

2024-07-17 11:13 UTC, jasonren0403 commented on files/zh-cn/web/api/url/parse_static/index.md
> +{{EmbedLiveSample('URL.parse()', '100%')}}
```suggestion
{{EmbedLiveSample('使用 URL.parse()', '100%')}}
```

2024-07-17 11:13 UTC, jasonren0403 approved these changes
👍

2024-07-17 11:14 UTC, merged