[ja] Update Error page
mdn/translated-content pull request #22163
Opened 2024-07-04 19:42 UTC by syusui-s

### Description

`Error` のトップページの翻訳を英文の最新版の追従するように更新しました。

### Motivation

日本語版読者が最新の情報にたどり着けるようにします。

### Additional details

### Related issues and pull requests

Fixes https://github.com/mozilla-japan/translation/issues/781

2024-07-05 16:34 UTC, mfuji09 requested changes
いくつか修正をお願いします。

2024-07-05 16:34 UTC, mfuji09 commented on files/ja/web/javascript/reference/global_objects/error/index.md
> +以下の例は、似たエラーで失敗する2つのメソッドを示しています（`doFailSomeWay()` と `doFailAnotherWay()`）:
数字の前後は空白を空けるようお願いいたします。
```suggestion
以下の例は、似たエラーで失敗する 2 つのメソッドを示しています（`doFailSomeWay()` と `doFailAnotherWay()`）:
```

2024-07-05 16:34 UTC, mfuji09 commented on files/ja/web/javascript/reference/global_objects/error/index.md
> +> **警告**: 組み込みのサブクラス化は、ES6より古いコードに確実にトランスパイルできるわけではありません。なぜなら {{jsxref("Reflect.construct()")}} を使わずに特定の `new.target` を持つ基底クラスを構築する手段がないためです。[追加の設定](https://github.com/loganfsmyth/babel-plugin-transf
こちらも英数字の前後に空白を入れるようお願いします。
また、-erで終わる単語には長音記号を付けてください。

```suggestion
> **警告**: 組み込みのサブクラス化は、ES6 より古いコードに確実にトランスパイルできるわけではありません。なぜなら {{jsxref("Reflect.construct()")}} を使わずに特定の `new.target` を持つ基底クラスを構築する手段がないためです。[追加の設定](https://github.com/loganfsmyth/babel-plugin-transform-builtin-extend)を行うか、コンストラクターの最後で手動で {{jsxref("Object/setPrototypeOf", "Object.setPrototypeOf(this, CustomError.prototype)")}} を呼ぶ必要があります。そうしないと、構築されたインスタンスは `CustomError` のインスタンスになりません。詳しくは [the TypeScript FAQ](https://github.com/microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work) をご覧ください。
```

2024-07-05 16:34 UTC, mfuji09 commented on files/ja/web/javascript/reference/global_objects/error/index.md
> +> **メモ:** ES2015 クラスを使用した場合、一部のブラウザはスタックトレース上に `CustomError` コンストラクタを含めます。
```suggestion
> **メモ:** ES2015 クラスを使用した場合、一部のブラウザはスタックトレース上に `CustomError` コンストラクターを含めます。
```

2024-07-05 16:34 UTC, mfuji09 commented on files/ja/web/javascript/reference/global_objects/error/index.md
> +    // 親のコンストラクタに（ベンダー固有のものも含めて）残りの引数を渡す
```suggestion
    // 親のコンストラクターに（ベンダー固有のものも含めて）残りの引数を渡す
```

2024-07-06 02:15 UTC, syusui-s commented
ご確認ありがとうございます。
指摘点を修正してコミットしました。

2024-07-08 13:53 UTC, mfuji09 approved these changes
ありがとうございました。OKです。

2024-07-08 13:55 UTC, merged