Translated set-cookie page to Russian locale
mdn/translated-content pull request #22161
Opened 2024-07-04 12:47 UTC by mnik01

### Description

Translated set-cookie page to Russian locale by updating `.md` file.

### Motivation

There was not translated parts in page and some repeated text blocks.

### Additional details

-

### Related issues and pull requests

-

2024-07-04 12:49 UTC, mnik01 commented
Стоит ли переводить
```md
> **Warning:**
```

Как
```
> **Предупреждение:**
```

Или можно оставить слово warning как есть в английской версии?

2024-07-04 20:17 UTC, leon-win commented
> Стоит ли переводить
> 
> ```
> > **Warning:**
> ```
> 
> Как
> 
> ```
> > **Предупреждение:**
> ```
> 
> Или можно оставить слово warning как есть в английской версии?

Да, конечно, нужно переводить. А почему сомнения?)

2024-07-04 21:40 UTC, leon-win requested changes

2024-07-04 21:40 UTC, leon-win commented on files/ru/web/http/headers/set-cookie/index.md
> +HTTP заголовок **`Set-Cookie`** используется для отправки cookies с сервера на агент пользователя. После чего агент пользователя сможет отправлять их обратно на сервер с запросами.
```suggestion
Заголовок HTTP-ответа **`Set-Cookie`** используется для отправки куки-файлов с сервера агенту пользователя, чтобы он мог позже отправить его обратно на сервер.
```

2024-07-04 21:40 UTC, leon-win commented on files/ru/web/http/headers/set-cookie/index.md
> +Что бы проставить несколько cookies нужно отправить несколько **`Set-Cookie`** заголовков в одном ответе.
```suggestion
Для отправки нескольких куки-файлов в одном ответе должны быть отправлены несколько заголовков **`Set-Cookie`**.
```

2024-07-04 21:40 UTC, leon-win commented on files/ru/web/http/headers/set-cookie/index.md
> +> **Предупреждение:** Браузеры блокируют доступ клиентскому JavaScript коду к `Set-Cookie` заголовкам, так как это того требует спецификация Fetch, она определяет `Set-Cookie` как [запрещённый заголо
```suggestion
> **Предупреждение:** Браузеры блокируют доступ клиентскому JavaScript-коду к заголовкам `Set-Cookie`, как этого требует спецификация Fetch, определяющая `Set-Cookie` как [запрещённый заголовок ответа](https://fetch.spec.whatwg.org/#forbidden-response-header-name), который [должен быть исключён](https://fetch.spec.whatwg.org/#ref-for-forbidden-response-header-name%E2%91%A0) из любого ответа доступного для клиентских скриптов.
```

2024-07-04 21:40 UTC, leon-win commented on files/ru/web/http/headers/set-cookie/index.md
>  Для детальной информации, смотрите руководство по [HTTP cookies](/ru/docs/Web/HTTP/Cookies).
```suggestion
Больше информации в руководстве по [использованию HTTP-кук](/ru/docs/Web/HTTP/Cookies).

<table class="properties">
  <tbody>
    <tr>
      <th scope="row">Тип заголовка</th>
      <td>{{Glossary("Response header", "Заголовок ответа")}}</td>
    </tr>
    <tr>
      <th scope="row">{{Glossary("Forbidden header name")}}</th>
      <td>нет</td>
    </tr>
    <tr>
      <th scope="row">{{Glossary("Forbidden response header name")}}</th>
      <td>да</td>
    </tr>
  </tbody>
</table>
```

2024-07-04 21:47 UTC, leon-win commented
Привет, @mnik01 !

Благодарю за желание улучшить MDN!

Я успел посмотреть часть изменений, предложил свои улучшения. И заметил, что перевод страницы не полностью сделан (напирмер, таблица про типы заголовков и далее примеры синтаксиса не дополнены в соотвествии со свежей версий оригинала). А судя по описанию PR'а планировалось полностью синхронизировать перевод всей страницы?

2024-07-05 00:49 UTC, mnik01 commented
> Да, конечно, нужно переводить. А почему сомнения?)

На сайте эти заметки в маркдауне превращаются в плашки и Я думал подхватит ли скрипт её если слово будет не `warning`.

Пытался найти пример таких плашек в ру переводах, но не нашел, поэтому оставил как есть.

Спасибо, переведу.

2024-07-05 02:14 UTC, mnik01 commented
@leon-win Я обновил файлик — синхронизовал с актуальной версией [оригинала](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie)


Посмотрите, пожалуйста, всё ли ок. 
И, кстати, как лучше всего перевести `Compatibility notes`? Заметки по совместимости?

2024-07-05 02:18 UTC, mnik01 commented on files/ru/web/http/headers/set-cookie/index.md
> +  - : Указывает, что куки должны храниться с использованием разделенного хранилища. См. [Cookies с независимым разделённым хранением (CHIPS)](/en-US/docs/Web/Privacy/Privacy_sandbox/Partitioned_cooki
There is no such page translated yet

2024-07-05 02:19 UTC, mnik01 commented on files/ru/web/http/headers/set-cookie/index.md
> +        > **Предупреждение:** Куки с атрибутом `SameSite=None; Secure`, которые также не имеют атрибута [`Partitioned`](#partitioned), могут быть заблокированы в кросс-сайтовых контекстах в будущих в
There is no such pages translated yet

2024-07-05 02:19 UTC, mnik01 commented on files/ru/web/http/headers/set-cookie/index.md
> +  - : Указывает, что куки отправляются на сервер только при выполнении запроса по протоколу `https:` (за исключением localhost), и поэтому более устойчивы к [атакам типа "человек посередине"](/en-US/
It's not translated yet

2024-07-05 02:25 UTC, mnik01 commented on files/ru/web/http/headers/set-cookie/index.md
> +  - : Указывает, что куки должны храниться с использованием разделенного хранилища. См. [Cookies с независимым разделённым хранением (CHIPS)](/en-US/docs/Web/Privacy/Privacy_sandbox/Partitioned_cooki
There is no such translation yet

2024-07-05 02:26 UTC, mnik01 commented on files/ru/web/http/headers/set-cookie/index.md
> +        > **Предупреждение:** Куки с атрибутом `SameSite=None; Secure`, которые также не имеют атрибута [`Partitioned`](#partitioned), могут быть заблокированы в кросс-сайтовых контекстах в будущих в
There is no such translation yet

2024-07-05 02:26 UTC, mnik01 commented on files/ru/web/http/headers/set-cookie/index.md
> +  - : Указывает, что куки отправляются на сервер только при выполнении запроса по протоколу `https:` (за исключением localhost), и поэтому более устойчивы к [атакам типа "человек посередине"](/en-US/
There is no such translation yet

2024-07-05 02:26 UTC, mnik01 commented on files/ru/web/http/headers/set-cookie/index.md
> +  - : Указывает, что куки должны храниться с использованием разделенного хранилища. См. [Cookies с независимым разделённым хранением (CHIPS)](/en-US/docs/Web/Privacy/Privacy_sandbox/Partitioned_cooki
There is no such translation yet

2024-07-05 02:26 UTC, mnik01 commented on files/ru/web/http/headers/set-cookie/index.md
> +        > **Предупреждение:** Куки с атрибутом `SameSite=None; Secure`, которые также не имеют атрибута [`Partitioned`](#partitioned), могут быть заблокированы в кросс-сайтовых контекстах в будущих в
There is no such translation yet

2024-07-05 02:27 UTC, mnik01 commented on files/ru/web/http/headers/set-cookie/index.md
> +  - : Указывает, что куки отправляются на сервер только при выполнении запроса по протоколу `https:` (за исключением localhost), и поэтому более устойчивы к [атакам типа "человек посередине"](/en-US/
There is no such translation yet

2024-07-07 21:17 UTC, leon-win commented
> > Да, конечно, нужно переводить. А почему сомнения?)
> 
> На сайте эти заметки в маркдауне превращаются в плашки и Я не был уверен подхватит ли скрипт её если слово будет не `warning`. 

Да, [yari](https://github.com/mdn/yari) (движок, который обрабатывает документы MDN) производит множество манипуляций с разметкой, в том числе создаёт такие плашки. Он действительно "заточен" на конкретные слова (с сочетаниями символов), в данном случае дял русского языка `> **Предупреждение:**` будет преобразовано в специальную разметку.

Если я правильно понял (раз возникают такие опасения + много автоматических замечаний по оформлению от бота), то ты ведёшь работу "вслепую", то есть не запуская MDN локально? Если да, то это не очень хорошо( Использовать Github веб-интерфейс удобно только для мелких изменений.

А если переводить документ полностью, то лучше развернуть проект локально, для этого нужно слконировать оба репозитория ([content](https://github.com/mdn/content) и [translated-content](https://github.com/mdn/translated-content)). Как это сделать описано в https://github.com/mdn/content/blob/main/CONTRIBUTING.md#forking-and-cloning-the-repository (начиная с этого раздела и далее) и https://github.com/mdn/translated-content/blob/main/CONTRIBUTING.md. А также есть наш небольшой гайд по особенностям перевода именно на русский язык (https://github.com/mdn/translated-content/blob/main/docs/ru/translation-guide.md).

> Посмотрите, пожалуйста, всё ли ок.
Да, я постараюсь найти время и посмотреть :ok_hand: 

> И, кстати, как лучше всего перевести Compatibility notes? Заметки по совместимости?
Я думаю, что лучше "Замечания по совместимости".

2024-07-08 00:55 UTC, mnik01 commented
> Если я правильно понял , то ты ведёшь работу "вслепую"

Да, это так.

Гайд по особенностям перевода именно на русский я читал, а за наводку на то как локально развернуть проект — спасибо 👍 

Попробую поднять когда (если) будет время

2024-07-15 21:56 UTC, leon-win requested changes
Проверил ещё часть документа и внёс правки, дошёл до описания атрибута `Domain=<domain-value>`.

Но такими темпами очень долго будет(( Слишком много неточностей и проблем с форматированием, часть описания продублирована была (про кодирование), не обновлён синтаксис и т.д.

Нужно более внимательно подойти к переводу, и делать это в IDE с запуском локального сервера. А также обращать внимание на сообщения от бота `github-actions` об ошибка форматирвоания. С ними влить всё равно не получится))

2025-03-19 13:19 UTC, closed without merging