[zh-cn]: update the translation of CSS RGB()
mdn/translated-content pull request #22177
Opened 2024-07-05 23:16 UTC by linker-fen-js

### Description
新增CSS RGB()函数中关于相对值的中文翻译描述，同时增加了一些例子

### Motivation
相较于英文版，中文版缺失了关于相对值、from关键字的描述

### Additional details

### Related issues and pull requests

2024-07-06 06:54 UTC, yin1999 requested changes
现在的翻译并未完全对应英文的文档内容（包括文本内容以及样式）。请仔细校对一下。关于标点的使用说明，请参考[翻译指南](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md#%E4%B8%AD%E6%96%87%E7%BF%BB%E8%AF%91%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

2024-07-06 08:07 UTC, yin1999 requested changes
我列举了几个常见的问题，下文中也有出现，请一一修正。并在修改完成后再将 PR 标记为“ready”。

2024-07-06 08:07 UTC, yin1999 commented on files/zh-cn/web/css/color_value/rgb/index.md
> +/* 相对值（通过计算得到） */
```suggestion
/* 相对值 */
```

2024-07-06 08:07 UTC, yin1999 commented on files/zh-cn/web/css/color_value/rgb/index.md
> +> **备注：** `rgb（）` / `rgba（）` 都可接受旧版的语法，即所有的值都是用逗号分隔的，如 rgb(255，0，0)、rgba(255，0，0,0.5)。在逗号分隔的传统语法中，混合数字和百分比值类型是无效的（即 R、G 和 B 值必须是全部数字或全部百分比），也不允许使用 none 值。
多了 “`rgba(255，0，0,0.5)`”，且缺少代码样式。

```suggestion
> **备注：** `rgb()` / `rgba()` 也可以旧版语法编写，即所有的值都是用逗号分隔的，如 `rgb(255, 0, 0)`。在逗号分隔的旧版语法中，混合数字和百分比值类型是无效的（即 R、G 和 B 值必须是全部数字或全部百分比），也不允许使用 `none` 值。
```

2024-07-06 08:07 UTC, yin1999 commented on files/zh-cn/web/css/color_value/rgb/index.md
> +下面是对 `绝对值颜色` 和 [相对值颜色](/zh-CN/docs/Web/CSS/CSS_colors/Relative_colors) 的描述
中文之间不应有空格

```suggestion
下面是对绝对颜色和[相对颜色](/zh-CN/docs/Web/CSS/CSS_colors/Relative_colors)的描述
```

2024-07-06 08:07 UTC, yin1999 commented on files/zh-cn/web/css/color_value/rgb/index.md
> +#### 绝对值颜色语法
```suggestion
#### 绝对值语法
```

2024-07-06 08:07 UTC, yin1999 commented on files/zh-cn/web/css/color_value/rgb/index.md
> +  - : 每个都是从 `0` 到 `255` 之间的 {{CSSXref("&lt;number&gt;")}} 值，或从 `0%` 到 `100%` 之间的 {{CSSXref("&lt;percentage&gt;")}} 值，或为关键字 `none`(此处等同于 `0%` )，分别代表红色、绿色和蓝色的通道。
标点符号（正文的文本应使用“全角括号”），中文之间（或中文与全角的标点之间）不应有空格

```suggestion
  - : 每个都是从 `0` 到 `255` 之间的 {{CSSXref("&lt;number&gt;")}} 值，或从 `0%` 到 `100%` 之间的 {{CSSXref("&lt;percentage&gt;")}} 值，或为关键字 `none`（与 `0%` 等价），分别代表红色、绿色和蓝色的通道。
```

2024-07-06 09:44 UTC, linker-fen-js commented
> 现在的翻译并未完全对应英文的文档内容（包括文本内容以及样式）。请仔细校对一下。关于标点的使用说明，请参考[翻译指南](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md#%E4%B8%AD%E6%96%87%E7%BF%BB%E8%AF%91%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

我刚才重新修改了一些文本内容和样式，但git bot还是显示 “Please fix all the linting issues mentioned in above logs and in the review comments.”，我该如何查看具体哪一行文本导致了自动检查失败

2024-07-06 11:21 UTC, yin1999 reviewed
还请再仔细检查一下内容，有些空格和样式是不需要的（注意括号前后的空格）

2024-07-06 11:21 UTC, yin1999 commented on files/zh-cn/web/css/color_value/rgb/index.md
>  ### 值
少空行

![image](https://github.com/mdn/translated-content/assets/15844309/0ad264b1-b742-4115-abf6-21f6c1e3d013)

2024-07-07 06:15 UTC, yin1999 requested changes
我们并不赞同按自己的想法去翻译内容的做法，因为这会为我们的文档维护工作带来很多困难。请解决我提到的所有问题。然后再将此 PR 标记为“ready”

2024-07-07 06:15 UTC, yin1999 commented on files/zh-cn/web/css/color_value/rgb/index.md
> +第一个例子将输出与原始颜色相同的颜色。我们使用 `hsl(0 100% 50%)`（与 `rgb(255 0 0)` 等价）作为原始颜色，以下函数将把原始颜色的 `r`、`g` 和 `b` 通道值（`255` `0` 和 `0`）作为输出通道值。
这里缺少一段内容，而且翻译也并未对其

2024-07-07 06:15 UTC, yin1999 commented on files/zh-cn/web/css/color_value/rgb/index.md
> +> **备注：** 参见 [hsl()](/zh-CN/docs/Web/CSS/color_value/hsl) 函数以了解其定义。
英文文档并没有这段话

2024-07-07 06:15 UTC, yin1999 commented on files/zh-cn/web/css/color_value/rgb/index.md
> +```
这里是按自己的逻辑去写的，我们不赞同这种做法。请与英文文档的内容保持一致

2024-07-07 06:15 UTC, yin1999 commented on files/zh-cn/web/css/color_value/rgb/index.md
> +> **备注：** 因为原始颜色通道值会被解析为 `<number>` 值，所以在使用它们进行计算时，即使通道能够接受 `<percenter>`、`<angle>` 或其他值类型，我们也必须使用 `<number>` 进行运算。
这段也并不一致

2024-07-07 06:15 UTC, yin1999 commented on files/zh-cn/web/css/color_value/rgb/index.md
> +在本例中，三个 {{htmlelement("div")}} 元素的背景色都会使用 `rgb()` 函数进行设置，同时为了体现第三个元素的透明通道，我们在 {{htmlelement("body")}} 上使用了 {{cssxref("gradient/repeating-linear-gradient", "repeating-linear-gradient()")}} 函数设置斜条纹背景。
同上

2024-07-07 06:15 UTC, yin1999 commented on files/zh-cn/web/css/color_value/rgb/index.md
> +### 如何使用相对值
标题并不一致

2024-07-07 06:15 UTC, yin1999 commented on files/zh-cn/web/css/color_value/rgb/index.md
> +</div>
同上

2024-07-07 06:15 UTC, yin1999 commented on files/zh-cn/web/css/color_value/rgb/index.md
>  ### 旧版语法：逗号分隔值
请更新这一段的内容

2024-07-08 08:32 UTC, skyclouds2001 commented on files/zh-cn/web/css/color_value/rgb/index.md
> +- [CSS 颜色](/zh-CN/docs/Web/CSS/CSS_colors) 模块
```suggestion
- [CSS 颜色](/zh-CN/docs/Web/CSS/CSS_colors)模块
```

2024-07-08 08:32 UTC, skyclouds2001 commented on files/zh-cn/web/css/color_value/rgb/index.md
> +> **备注：** 因为原始颜色通道值会被解析为 `<number>` 值，所以在使用它们进行计算时，即使通道能够接受 `<percenter>`、`<angle>` 或其他值类型，我们也必须使用 `<number>`进行运算。例如在 `<number>` 中添加 `<percenter>` 是不起作用的。
```suggestion
> **备注：** 因为原始颜色通道值会被解析为 `<number>` 值，所以在使用它们进行计算时，即使通道能够接受 `<percenter>`、`<angle>` 或其他值类型，我们也必须使用 `<number>` 进行运算。例如在 `<number>` 中添加 `<percenter>` 是不起作用的。
```

2024-07-13 12:13 UTC, yin1999 approved these changes
Thanks

2024-07-13 12:15 UTC, merged