[ko] TypedArray.prototype.toString() 신규 번역 외
mdn/translated-content pull request #22187
Opened 2024-07-06 07:56 UTC by wisedog

- TypedArray.prototype.toString() 신규 번역
- Array.prototype.toString() 최신화

2024-08-01 03:27 UTC, wisedog commented
@1ilsang   죄송한데, 이 PR 리뷰 부탁드려도 될까요? 🥹

2024-08-01 07:19 UTC, 1ilsang requested changes
@wisedog 님 안녕하세요. 기여해주셔서 감사합니다! 💯

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

질문이나 도움이 필요하시다면 언제든 멘션 부탁드리겠습니다.

2024-08-01 07:19 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/array/tostring/index.md
> +// 1; a number
```suggestion
// 1; 숫자 타입
```

2024-08-01 07:19 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/array/tostring/index.md
> +{{jsxref("Array")}} 인스턴스의 **`toString()`** 메서드는 지정된 배열 및 그 요소를 나타내는 문자열을 반환합니다.
```suggestion
{{jsxref("Array")}} 인스턴스의 **`toString()`** 메서드는
지정된 배열 및 그 요소를 나타내는 문자열을 반환합니다.
```

줄 수는 원문과 동일하게 해주세요. 관련 논의는 [여기](https://github.com/orgs/mdn/discussions/655#discussioncomment-9251708)에서 확인할 수 있습니다.

2024-08-02 02:46 UTC, 1ilsang approved these changes

2024-08-02 02:46 UTC, merged