zh-CN: update Glossary/TCP_slow_start
mdn/translated-content pull request #22222
Opened 2024-07-07 03:35 UTC by PassionPenguin

2024-07-14 07:29 UTC, yin1999 requested changes

2024-07-14 07:29 UTC, yin1999 commented on files/zh-cn/glossary/tcp_slow_start/index.md
> +{{glossary('TCP')}} 慢开始帮助建立传输速度，使其达到网络的能力。它在不知道这些能力的情况下进行，而且不会造成拥塞。{{glossary('TCP')}} 慢开始是一种用于检测数据包传输可用带宽的算法，它平衡了网络连接的速度。它可以防止出现网络拥塞，而这些拥塞的能力最初是未知的，它会逐渐增加传输的信息量，直到找到网络的最大容量。
帮助建立传输速度？后面的翻译也再对一下，看看有没有需要修改的

2024-07-14 10:14 UTC, PassionPenguin commented on files/zh-cn/glossary/tcp_slow_start/index.md
> +{{glossary('TCP')}} 慢开始帮助建立传输速度，使其达到网络的能力。它在不知道这些能力的情况下进行，而且不会造成拥塞。{{glossary('TCP')}} 慢开始是一种用于检测数据包传输可用带宽的算法，它平衡了网络连接的速度。它可以防止出现网络拥塞，而这些拥塞的能力最初是未知的，它会逐渐增加传输的信息量，直到找到网络的最大容量。
```suggestion
{{glossary('TCP')}} 慢开始有助于根据网络能力提高传输速度。它在最初不知道网络能力的情况下实现这一目标，并且不会造成拥塞。{{glossary('TCP')}} 慢开始本身是一种用于检测数据包传输可用带宽并平衡网络连接速度的算法。它能防止出现最初能力未知的网络拥塞，并且逐渐增加传输的信息量，直到找到网络的最大容量。
```

2024-07-14 10:14 UTC, PassionPenguin commented on files/zh-cn/glossary/tcp_slow_start/index.md
> +要实现 TCP 慢开始，拥塞窗口（_cwnd_）设置了在接收到确认（ACK）之前源可以在网络上传输的数据量的上限。慢开始阈值（_ssthresh_）确定了慢开始的（停止）启动。当建立新连接时，cwnd 被初始化为一个 TCP 数据或确认数据包，并等待确认，或 ACK。当收到该 ACK 时，拥塞窗口会递增，直到 _cwnd_ 小于 _ssthresh_。慢开始还会在遇到拥塞时终止。
```suggestion
要实现 TCP 慢开始，拥塞窗口（_cwnd_）为数据源设置了在接收到确认（ACK）之前可以在网络上传输的数据量的上限，慢开始阈值（_ssthresh_）则确定了慢启动过（停止）的激活。当建立新连接时，cwnd 被初始化为一个 TCP 数据或确认数据包，并等待确认（ACK）。当收到 ACK 时，拥塞窗口会逐步增加，直到 _cwnd_ 小于 _ssthresh_。慢开始也会在遇到拥塞时终止。
```

2024-07-14 10:14 UTC, PassionPenguin commented on files/zh-cn/glossary/tcp_slow_start/index.md
> +拥塞本身是发生在网络层的一种状态，当消息流量太忙，它减慢了网络响应时间。服务器以 TCP 包发送数据，用户的客户端然后通过返回 acknowledgements 或 ack 来确认传输。根据硬件和网络条件，连接的容量是有限的。如果服务器发送太多的数据包太快，它们将被丢弃。意味着，不会有任何确认。服务器将其注册为丢失 ACKs。拥塞控制算法使用发送的数据包和 ack 流来确定发送速率。
```suggestion
拥塞本身是发生在网络层的一种状态，当消息流量太忙，拥塞将减慢网络的响应时间。服务器使用 TCP 包发送数据给用户的客户端，然后通过客户端返回确认（ACK）来确认传输。根据硬件和网络条件，连接的容量是有限的。如果服务器发送太多的数据包太快，它们将被丢弃（也就意味着，它们不会得到任何确认，而会被注册为丢失的确认）。拥塞控制算法使用发送的数据包和 ACK 流来确定发送速率。
```

2024-07-15 02:13 UTC, yin1999 reviewed
一些建议：TCP slow start 还是翻译成“慢启动”的更多。这也是教科书上采用的翻译

2024-07-15 02:13 UTC, yin1999 commented on files/zh-cn/glossary/tcp_slow_start/index.md
> +{{glossary('TCP')}} 慢开始有助于根据网络能力提高传输速度。它在最初不知道网络能力的情况下实现这一目标，并且不会造成拥塞。{{glossary('TCP')}} 慢开始本身是一种用于检测数据包传输可用带宽并平衡网络连接速度的算法。它能防止出现最初能力未知的网络拥塞，并且逐渐增加传输的信息量，直到找到网络的最大容量。
```suggestion
{{glossary('TCP')}} 慢启动有助于根据网络能力提高传输速度。它在最初不知道网络能力的情况下实现这一目标，并且不会造成拥塞。{{glossary('TCP')}} 慢启动本身是一种用于检测数据包传输可用带宽并平衡网络连接速度的算法。它能防止出现最初能力未知的网络拥塞，并且逐渐增加传输的信息量，直到找到网络的最大容量。
```

2024-07-15 02:13 UTC, yin1999 commented on files/zh-cn/glossary/tcp_slow_start/index.md
> +要实现 TCP 慢开始，拥塞窗口（_cwnd_）为数据源设置了在接收到确认（ACK）之前可以在网络上传输的数据量的上限，慢开始阈值（_ssthresh_）则确定了慢启动过（停止）的激活。当建立新连接时，cwnd 被初始化为一个 TCP 数据或确认数据包，并等待确认（ACK）。当收到 ACK 时，拥塞窗口会逐步增加，直到 _cwnd_ 小于 _ssthresh_。慢开始也会在遇到拥塞时终止。
```suggestion
要实现 TCP 慢启动，拥塞窗口（_cwnd_）为数据源设置了在接收到确认（ACK）之前可以在网络上传输的数据量的上限，慢开始阈值（_ssthresh_）则确定了慢启动的开始（和停止）。当建立新连接时，cwnd 被初始化为一个 TCP 数据或确认包，并等待确认（ACK）。当收到 ACK 时，拥塞窗口会逐步增加，直到 _cwnd_ 大于 _ssthresh_。慢开始也会在遇到拥塞时终止。
```

2024-07-15 02:13 UTC, yin1999 commented on files/zh-cn/glossary/tcp_slow_start/index.md
> +拥塞本身是发生在网络层的一种状态，当消息流量太忙，拥塞将减慢网络的响应时间。服务器使用 TCP 包发送数据给用户的客户端，然后通过客户端返回确认（ACK）来确认传输。根据硬件和网络条件，连接的容量是有限的。如果服务器发送太多的数据包太快，它们将被丢弃（也就意味着，它们不会得到任何确认，而会被注册为丢失的确认）。拥塞控制算法使用发送的数据包和 ACK 流来确定发送速率。
```suggestion
拥塞本身是发生在网络层的一种状态，当消息流量太忙，拥塞将减慢网络的响应时间。服务器使用 TCP 包发送数据给用户的客户端，然后通过客户端返回确认（ACK）来确认传输。根据硬件和网络条件，连接的容量是有限的。如果服务器太快地发送大量的数据包，它们将被丢弃（也就意味着，它们不会得到任何确认，而会被注册为丢失的 ACK）。拥塞控制算法使用发送的数据包和 ACK 流来确定发送速率。
```

2024-07-15 02:13 UTC, yin1999 commented on files/zh-cn/glossary/tcp_slow_start/index.md
> +- [填充页面：浏览器如何工作](/zh-CN/docs/Web/Performance/How_browsers_work)
```suggestion
- [渲染页面：浏览器的工作原理](/zh-CN/docs/Web/Performance/How_browsers_work)
```

2024-07-15 04:29 UTC, yin1999 approved these changes

2024-07-15 04:29 UTC, merged