zh-CN: create Glossary/WAI
mdn/translated-content pull request #22251
Opened 2024-07-07 07:59 UTC by PassionPenguin

2024-07-16 06:31 UTC, jasonren0403 requested changes

2024-07-16 06:31 UTC, jasonren0403 commented on files/zh-cn/glossary/wai/index.md
> +## See also
```suggestion
## 参见
```

2024-07-16 06:31 UTC, jasonren0403 commented on files/zh-cn/glossary/wai/index.md
> +WAI 或 Web 无障碍倡议是由万维网联盟（W3C）发起的一个倡议，旨在为需要使用非标准{{Glossary("browser", "浏览器")}}或设备的人们改善无障碍体验。
improve accessibility _for people with various challenges_

斜体部分译文没体现出来

2024-07-17 00:57 UTC, PassionPenguin commented on files/zh-cn/glossary/wai/index.md
> +WAI 或 Web 无障碍倡议是由万维网联盟（W3C）发起的一个倡议，旨在为需要使用非标准{{Glossary("browser", "浏览器")}}或设备的人们改善无障碍体验。
```suggestion
Web 无障碍倡议（WAI）是由万维网联盟（W3C）发起的一个倡议，旨在为需要使用非标准{{Glossary("browser", "浏览器")}}或设备的存在一定障碍的人们改善无障碍体验。
```

2024-07-17 11:21 UTC, jasonren0403 approved these changes

2024-07-17 11:21 UTC, merged