zh-CN: update Glossary/Undefined
mdn/translated-content pull request #22268
Opened 2024-07-07 08:02 UTC by PassionPenguin

同步一下argument之前的共识翻译（实际参数）

2024-07-18 08:21 UTC, yin1999 requested changes

2024-07-18 08:21 UTC, yin1999 commented on files/zh-cn/glossary/undefined/index.md
> +**`undefined`** 是一个{{Glossary("primitive", "原始值")}}，自动赋给刚刚声明的{{glossary("variable", "变量")}}，或者给那些没有提供实际的{{Glossary("Argument", "实际参数")}}的实际参数。
这样翻译有些公式化替换了，想一下什么是“formal argument”

```suggestion
**`undefined`** 是一个{{Glossary("primitive", "原始值")}}，自动赋给刚刚声明的{{glossary("variable", "变量")}}，或那些没有提供实际{{Glossary("Argument", "参数")}}的形参。
```

2024-07-18 10:55 UTC, PassionPenguin commented on files/zh-cn/glossary/undefined/index.md
> +**`undefined`** 是一个{{Glossary("primitive", "原始值")}}，自动赋给刚刚声明的{{glossary("variable", "变量")}}，或者给那些没有提供实际的{{Glossary("Argument", "实际参数")}}的实际参数。
emm，argument的翻译之前讨论修改过，变成了实际参数哇（当然，翻完就觉得奇怪）

<img width="579" alt="image" src="https://github.com/user-attachments/assets/72da222e-18df-4a39-971a-0982b5f3d037">

2024-07-18 11:00 UTC, yin1999 commented on files/zh-cn/glossary/undefined/index.md
> +**`undefined`** 是一个{{Glossary("primitive", "原始值")}}，自动赋给刚刚声明的{{glossary("variable", "变量")}}，或者给那些没有提供实际的{{Glossary("Argument", "实际参数")}}的实际参数。
上次的讨论我看到了的，我知道的。问题是，需要翻译成实际的实际参数吗？

本身，我们如果为了区分这两者，翻译成实际参数和形式参数当然没问题。但实际的实际参数是不是就很多余了，难道前面的 actual 就不是为了表示这个参数是实际的吗？

![image](https://github.com/user-attachments/assets/5a03ee05-afe6-42a5-bef9-925baaee3c15)

2024-07-29 04:22 UTC, yin1999 approved these changes

2024-07-29 04:22 UTC, merged