zh-CN: update Glossary/Truthy
mdn/translated-content pull request #22278
Opened 2024-07-07 08:04 UTC by PassionPenguin

2024-07-07 10:44 UTC, yin1999 requested changes

2024-07-07 10:44 UTC, yin1999 commented on files/zh-cn/glossary/truthy/index.md
> +// returns "狗狗"
returns 不翻译？

2024-07-07 13:24 UTC, PassionPenguin commented on files/zh-cn/glossary/truthy/index.md
> +// returns "狗狗"
啊，第一反应这是 `return`
```suggestion
// 返回"狗狗"
```

2024-07-07 13:37 UTC, yin1999 commented on files/zh-cn/glossary/truthy/index.md
> +// 返回"狗狗"
```suggestion
// 返回“狗狗”
```

2024-07-07 13:37 UTC, yin1999 commented on files/zh-cn/glossary/truthy/index.md
> +// returns "狗狗"
```suggestion
// 返回“狗狗”
```

2024-07-07 13:37 UTC, yin1999 commented on files/zh-cn/glossary/truthy/index.md
> +JavaScript 中的*真值*示例如下（这些值会被转换为 `true`，因此 `if` 后的代码段将被执行）：
```suggestion
JavaScript 中的*真值*示例如下（这些值会被强制转换为 `true`，因此 `if` 后的代码段将被执行）：
```

2024-07-08 02:08 UTC, yin1999 approved these changes

2024-07-08 02:08 UTC, merged