zh-CN: create Glossary/XMLHttpRequest
mdn/translated-content pull request #22286
Opened 2024-07-07 08:06 UTC by PassionPenguin

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-07-07 08:16 UTC, PassionPenguin commented on files/zh-cn/glossary/xmlhttprequest/index.md
> +title: XMLHttpRequest（XHR）
hah? @yin1999 为什么英文字符和全角标点间会要加空格啊？

2024-07-07 14:07 UTC, yin1999 commented on files/zh-cn/glossary/xmlhttprequest/index.md
> +title: XMLHttpRequest（XHR）
符号被 autocorrect 替换成英文了，这个是 autocorrect 的问题。

2024-07-14 02:14 UTC, yin1999 requested changes

2024-07-14 02:14 UTC, yin1999 commented on files/zh-cn/glossary/xmlhttprequest/index.md
> +title: XMLHttpRequest（XHR）
先撤销这里的修改吧

```suggestion
title: XMLHttpRequest (XHR)
```

2024-07-14 02:14 UTC, yin1999 commented on files/zh-cn/glossary/xmlhttprequest/index.md
> +{{domxref("XMLHttpRequest")}}（XHR）是一种创建 {{Glossary("AJAX")}} 请求的 {{Glossary("JavaScript")}} {{Glossary("API")}}。它的方法提供了在{{Glossary("browser", "浏览器")}}和{{Glossary("server", "服务器")}}之间发送请求的能力。
```suggestion
{{domxref("XMLHttpRequest")}}（XHR）是一种创建 {{Glossary("HTTP")}} 请求的 {{Glossary("JavaScript")}} {{Glossary("API")}}。它的方法提供了在{{Glossary("browser", "浏览器")}}和{{Glossary("server", "服务器")}}之间发送请求的能力。
```

2024-07-14 02:14 UTC, yin1999 commented on files/zh-cn/glossary/xmlhttprequest/index.md
>  - 维基百科上的 [XMLHttpRequest](https://zh.wikipedia.org/wiki/XMLHttpRequest)
```suggestion
- [XMLHttpRequest API](/zh-CN/docs/Web/API/XMLHttpRequest_API) 文档。
```

2024-07-14 02:14 UTC, yin1999 commented on files/zh-cn/glossary/xmlhttprequest/index.md
> +  sourceCommit: ada5fa5ef15eadd44b549ecf906423b4a2092f34
更新一下你参考的 mdn/content 仓库

```suggestion
  sourceCommit: 409978ee3d2edd2b045adfbe39769b2dae6f31ea
```

2024-07-14 02:53 UTC, yin1999 approved these changes

2024-07-14 02:53 UTC, merged