[ko] Intl.Segmenter 설명 신규 번역 외
mdn/translated-content pull request #22309
Opened 2024-07-07 23:10 UTC by wisedog

- Intl.Segmenter 설명 신규 번역
- Array.length 최신화

2024-07-09 11:53 UTC, 1ilsang requested changes
@wisedog 님 안녕하세요. 기여해주셔서 감사합니다! 💯

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

질문이나 도움이 필요하시다면 언제든 멘션 부탁드리겠습니다.

2024-07-09 11:53 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/array/length/index.md
> +`length`를 현재 크기보다 더 크게 설정하면 [회소 배열](/ko/docs/Web/JavaScript/Guide/Indexed_collections#희소_배열)을 생성합니다.
```suggestion
`length`를 현재 크기보다 더 크게 설정하면 [희소 배열](/ko/docs/Web/JavaScript/Guide/Indexed_collections#희소_배열)을 생성합니다.
```

오타로 보입니다. 😄

2024-07-09 11:53 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/intl/segmenter/index.md
> +  - [`@@toStringTag`](/ko/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag) 속성의 초기 값은 문자열 `"Intl.Segmenter"`입니다. 이 속성은 {{jsxref("Object.prototype.toString()")}}에서 사용됩니다.
```suggestion
  - : 인스턴스 객체를 생성한 생성자 함수입니다. `Intl.Segmenter` 인스턴스의 경우, 초기 값은 {{jsxref("Intl/Segmenter/Segmenter", "Intl.Segmenter")}} 생성자입니다.
- `Intl.Segmenter.prototype[@@toStringTag]`
  - : [`@@toStringTag`](/ko/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag) 속성의 초기 값은 문자열 `"Intl.Segmenter"`입니다. 이 속성은 {{jsxref("Object.prototype.toString()")}}에서 사용됩니다.
```

[원문](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/segmenter/index.md?plain=1#L28-L31)과 동일한 형태를 유지해 주세요.

2024-07-09 11:53 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/intl/segmenter/index.md
> +// The two sentences are not correctly segmented.
```suggestion
// 두 문장이 올바르게 분할되지 않았습니다.
```

2024-07-09 11:53 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/intl/segmenter/index.md
> +// etc.
```suggestion
// 기타 등등
```

2024-07-09 13:06 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/array/length/index.md
> +`length`를 현재 크기보다 더 크게 설정하면 [회소 배열](/ko/docs/Web/JavaScript/Guide/Indexed_collections#희소_배열)을 생성합니다.
아.... 🤦‍♂️

2024-07-09 13:12 UTC, wisedog commented
@1ilsang  리뷰 감사합니다. 수정했으니 다시 확인 부탁드립니다.

2024-07-10 05:02 UTC, 1ilsang approved these changes
LGTM 고생하셨습니다~!

2024-07-10 05:02 UTC, merged