[zh-CN] update translation of requestAnimationFrame
mdn/translated-content pull request #22324
Opened 2024-07-08 18:54 UTC by linker-fen-js

### Description
根据英语文档内容，更新了 [requestAnimationFrame](https://developer.mozilla.org/zh-CN/docs/Web/API/Window/requestAnimationFrame) 的中文内容。在文档里的示例章节，对第三个例子理解可能会有偏差
### Motivation
相关issue [#22087](https://github.com/mdn/translated-content/issues/22087)

### Additional details

### Related issues and pull requests

2024-07-14 05:46 UTC, jasonren0403 requested changes
一些建议

2024-07-14 05:46 UTC, jasonren0403 commented on files/zh-cn/web/api/window/requestanimationframe/index.md
> +对回调函数的调用频率通常是与显示器的刷新率相匹配。虽然 75hz、120hz 和 144hz 也被广泛使用，但是最常见的刷新率还是 60hz（每秒 60 个周期/帧）。为了提高性能和电池寿命，大多数浏览器都会暂停在后台选项卡或者隐藏的 {{ HTMLElement("iframe") }} 中运行的 `requestAnimationFrame()`
```suggestion
对回调函数的调用频率通常与显示器的刷新率相匹配。虽然 75hz、120hz 和 144hz 也被广泛使用，但是最常见的刷新率还是 60hz（每秒 60 个周期/帧）。为了提高性能和电池寿命，大多数浏览器都会暂停在后台选项卡或者隐藏的 {{ HTMLElement("iframe") }} 中运行的 `requestAnimationFrame()`。
```

2024-07-14 05:46 UTC, jasonren0403 commented on files/zh-cn/web/api/window/requestanimationframe/index.md
> +  - 时间戳是一个以毫秒为单位的十进制数字，最小精度为 1 毫秒。对于 `Window` 对象（非 `workers`）来说，它等同于 {{domxref("AnimationTimeline/currentTime", "document.timeline.currentTime")}}。此时间戳在同一代理上（所有同源的`窗口`，更重要的是同源的 `iframes`）运行的所有窗口之间共享—
```suggestion
  - 时间戳是一个以毫秒为单位的十进制数字，最小精度为 1 毫秒。对于 `Window` 对象（而非 `Workers`）来说，它等同于 {{domxref("AnimationTimeline/currentTime", "document.timeline.currentTime")}}。此时间戳在同一代理上（所有同源的 `window`，更重要的是同源的 `iframe`）运行的所有窗口之间共享——它允许在多个 `requestAnimationFrame` 回调函数中执行同步动画。此时间戳值也近似于在回调函数开始时调用 {{domxref('performance.now()')}}，但它们永远都不会是相同的值。
```

2024-07-14 05:46 UTC, jasonren0403 commented on files/zh-cn/web/api/window/requestanimationframe/index.md
> +  - 当多个回调函数队列在同一帧中被 `requestAnimationFrame()` 所激发时，它们都会收到相同的时间戳，即便时间会在计算先前的回调函数中流逝。
```suggestion
  - 当 `requestAnimationFrame()` 队列中的多个回调开始在同一帧帧中触发时，它们都会收到相同的时间戳，即便在计算前一个回调的工作量时时间已经过去。
```

2024-07-14 05:46 UTC, jasonren0403 commented on files/zh-cn/web/api/window/requestanimationframe/index.md
> +请求 ID 是一个 `long` 类型整数值，是在回调列表里的唯一标识符。这是一个非零值，但你不能对该值做任何其他猜想。你可以将此值传递给 {{domxref("window.cancelAnimationFrame()")}} 函数以取消该刷新回调请求。
```suggestion
请求 ID 是一个 `long` 类型整数值，是在回调列表里的唯一标识符。这是一个非零值，但你不能对该值做任何其他假设。你可以将此值传递给 {{domxref("window.cancelAnimationFrame()")}} 函数以取消该刷新回调请求。
```

2024-07-14 05:46 UTC, jasonren0403 commented on files/zh-cn/web/api/window/requestanimationframe/index.md
> +以下三个示例说明了设置时间零点的不同方法，时间零点是计算每帧中动画进度的起点。如果你想同步到外部时钟，例如 {{domxref("BaseAudioContext.currentTime")}}，可用的最高精度是单帧的持续时间，16.67ms @60hz。回调函数的时间戳参数表示上一帧的结束，因此最快将在下一帧中呈现新计算的值。
```suggestion
以下三个示例说明了设置时间零点的不同方法，时间零点是计算每帧中动画进度的起点。如果你想同步到外部时钟，例如 {{domxref("BaseAudioContext.currentTime")}}，可用的最高精度是单帧的持续时间（16.67ms @60hz）。回调函数的时间戳参数表示上一帧的结束，因此最快将在下一帧中呈现新计算的值。
```

2024-07-14 05:46 UTC, jasonren0403 commented on files/zh-cn/web/api/window/requestanimationframe/index.md
> +此示例会等待第一个回调函数执行时设置 `zero`。如果你的动画在开始时跳转到新值，则必须以这种方式构建。如果你无需与任意外部同步，例如音频，则建议使用此方法，因为某些浏览器对 `requestAnimationFrame()` 的初始调用和对回调函数的第一次调用，会存在多帧延迟。
```suggestion
此示例会等待第一个回调函数执行时设置 `zero`。如果你的动画在开始时跳转到新值，则必须采用这种结构。如果你无需与任意外部同步（例如音频），则建议使用此方法，因为某些浏览器在首次调用 `requestAnimationFrame()` 和首次调用回调函数之间会有多帧延迟。
```

2024-07-14 05:46 UTC, jasonren0403 commented on files/zh-cn/web/api/window/requestanimationframe/index.md
此部分链接列表需要更新

2024-07-14 05:46 UTC, jasonren0403 commented on files/zh-cn/web/api/window/requestanimationframe/index.md
同步全文修改可以添加一下 `l10n.sourceCommit` 值

2024-07-15 02:00 UTC, linker-fen-js commented on files/zh-cn/web/api/window/requestanimationframe/index.md
> +  - 当多个回调函数队列在同一帧中被 `requestAnimationFrame()` 所激发时，它们都会收到相同的时间戳，即便时间会在计算先前的回调函数中流逝。
修改建议中的“多个回调开始在同一帧帧中触发时”，这里的“帧”是误输了吗？我修改为了“多个回调开始在同一帧中触发时”。

2024-07-15 02:09 UTC, linker-fen-js commented on files/zh-cn/web/api/window/requestanimationframe/index.md
> +  - 当多个回调函数队列在同一帧中被 `requestAnimationFrame()` 所激发时，它们都会收到相同的时间戳，即便时间会在计算先前的回调函数中流逝。
“工作量时时间已经过去” 叠字感觉也会有点奇怪

2024-07-17 11:10 UTC, jasonren0403 approved these changes
👍 感谢贡献，还有一些小问题我来修复

2024-07-17 11:10 UTC, jasonren0403 commented on files/zh-cn/web/api/window/requestanimationframe/index.md
> +  sourceCommit: 71f57bc7f6065d835a5af7c3ced3ef26263c809f
这里是对应英语文档最新提交的 SHA 值

```suggestion
  sourceCommit: f9f48866f02963e752717310b76a70d5bdaf554c
```

2024-07-17 11:10 UTC, jasonren0403 commented on files/zh-cn/web/api/window/requestanimationframe/index.md
> +在这个例子中，一个元素的动画时间是 2 秒（2000 毫秒）。该元素以 0.1px/ms 的速度向右移动，所以它的相对位置（以 CSS 像素为单位）可以通过动画开始后所经过的时间（以毫秒）的函数来计算 `0.1 * elapsed`。该元素的最终位置是在其初始位置的右边 200px（`0.1 * 2000`）。
```suggestion
在这个例子中，一个元素的动画时间是 2 秒（2000 毫秒）。该元素以 0.1px/ms 的速度向右移动，所以它的相对位置（以 CSS 像素为单位）可以通过动画开始后所经过的时间（以毫秒为单位）的函数来计算，即 `0.1 * elapsed`。该元素的最终位置是在其初始位置的右边 200px（`0.1 * 2000`）。
```

2024-07-17 11:10 UTC, jasonren0403 commented on files/zh-cn/web/api/window/requestanimationframe/index.md
>  - [TestUFO：测试你的网络浏览器 requestAnimationFrame() 的时间偏差](https://www.testufo.com/#test=animation-time-graph)
```suggestion
- [TestUFO：测试你的 web 浏览器 requestAnimationFrame() 的时间偏差](https://www.testufo.com/#test=animation-time-graph)
```

2024-07-17 11:11 UTC, merged