ja: update glossary link description
mdn/translated-content pull request #22328
Opened 2024-07-09 05:14 UTC by PassionPenguin

mdn/content#34454

2024-07-14 15:32 UTC, mfuji09 requested changes
Please use half-width colon ":" instead of full-width colon "：". It is by a custom of ja community.

And please check another comment.

2024-07-14 15:32 UTC, mfuji09 commented on files/ja/glossary/breadcrumb/index.md
> +[MDN](/) > 関連用語 > パンくずリスト
This modifying seems incorrect.
Please compare this with en-US version.

2024-07-14 23:56 UTC, PassionPenguin commented
> Please use half-width colon ":" instead of full-width colon "：". It is by a custom of ja community.
> 
> And please check another comment.

sorry for my mistake! they should now looks good :)

2024-07-15 13:24 UTC, mfuji09 approved these changes
LGTM.

2024-07-15 13:24 UTC, merged