[ko] Intl.DateTimeFormat.supportedLocalesOf() 신규번역 외
mdn/translated-content pull request #22346
Opened 2024-07-10 09:20 UTC by wisedog

- Intl.DateTimeFormat.supportedLocalesOf() 신규 번역
- String.prototype.trimEnd() 최신 동기화

2024-07-14 15:39 UTC, hochan222 requested changes
@wisedog 님 안녕하세요.

리뷰사항 하기에 남겨두었습니다.

고생 많으셨습니다! 좋은 하루 보내세요 :)

2024-07-14 15:39 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/intl/datetimeformat/supportedlocalesof/index.md
> +인도네시아어와 독일어는 지원하지만 날짜 및 시간 서식에서 인도네시아어는 지원하지 않는 런타임을 가정하면 `supportedLocalesOf`는 인도네시아어와 독일어 언어 태그를 변경하지 않고 반환하지만 `pinyin` 콜레이션은 날짜 및 시간 서식과 관련이 없거나 인도네시아어에서 사용되며 인도네시아에 특화된 독일어는 지원되지 않을 가능성이 높습니다. 여기
```suggestion
인도네시아어와 독일어는 지원하지만 발리어는 날짜 및 시간 서식에서 지원하지 않는 런타임을 가정하면, `supportedLocalesOf`는 인도네시아어와 독일어 태그를 변경하지 않고 반환하지만 `pinyin` 정렬 방식은 날짜 및 시간 서식과 관련이 없고 인도네시아어와 사용되지 않으며 인도네시아에 특화된 독일어는 지원되지 않을 가능성이 높습니다. 여기서 `"lookup"` 알고리즘의 사양에 유의하세요. 대부분의 발리어 사용자가 인도네시아어도 이해하므로 `"best fit"` 일치기는 인도네시아어가 발리아어와 적절히 일치한다고 판단하여 발리아어 태그도 반환할 수도 있습니다.
```

code \`~\`는 번역하지 않아야해서 수정했습니다!

2024-07-14 23:25 UTC, wisedog commented
감사합니다. 수정 완료하였습니다.

2024-07-15 15:10 UTC, hochan222 approved these changes
LGTM :)

2024-07-15 15:10 UTC, merged