[ko] Intl.DateTimeFormat.prototype.format() 신규번역 외
mdn/translated-content pull request #22342
Opened 2024-07-09 23:21 UTC by wisedog

- Intl.DateTimeFormat.prototype.format() 신규 번역
- String.prototype.trimStart() 최신화

2024-07-14 08:29 UTC, 1ilsang requested changes
@wisedog 님 안녕하세요. 기여해주셔서 감사합니다! 💯

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

질문이나 도움이 필요하시다면 언제든 멘션 부탁드리겠습니다.

2024-07-14 08:29 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/intl/datetimeformat/format/index.md
> +단일 날짜의 서식을 지정하려면 `format` 접근자 함수를 사용합니다. 아래는 세르비아의 경우입니다.
```suggestion
단일 날짜의 서식을 지정하려면 `format` 접근자 함수를 사용합니다.
아래는 세르비아의 경우입니다.
```

줄 수는 원문과 동일하게 해주세요. 관련 논의는 [여기](https://github.com/orgs/mdn/discussions/655#discussioncomment-9251708)에서 확인할 수 있습니다.

2024-07-14 08:29 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/intl/datetimeformat/format/index.md
> +> 참고하시기 바랍니다.
```suggestion
```

[원문](https://github.com/mdn/content/blob/7ca252a5316512d024673614b5c361680c944daf/files/en-us/web/javascript/reference/global_objects/intl/datetimeformat/format/index.md?plain=1)에 존재하지 않는 내용으로 보입니다. 확인 부탁드리겠습니다.

2024-07-14 12:30 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/intl/datetimeformat/format/index.md
> +> 참고하시기 바랍니다.
같은 문서 ja, fr 을 보면 남아있어서 원래 있었는데 빠진듯 합니다. 근데 한참 전에 빠진것 같은데 왜 제 로컬에 남아있어서 이것까지 해석했는지 모르겠군요. ㅠㅠ  예전에 번역하려고 로컬에 저장해놓은것일 수 있어서 intl 쪽은 번역할때 다시 한 번 최신 문서 확인하도록 하겠습니다.

2024-07-15 02:21 UTC, 1ilsang approved these changes
LGTM 고생하셨습니다

2024-07-15 02:21 UTC, merged