ko css doublecolon spelling error 신규 번역
mdn/translated-content pull request #22343
Opened 2024-07-10 02:14 UTC by givvemee

### Description

기존에 한국어로 존재하지 않던 문서 [::spelling-error](https://developer.mozilla.org/en-US/docs/Web/CSS/::spelling-error)를 번역합니다. 

### Motivation

### Additional details

### Related issues and pull requests

2024-07-10 09:10 UTC, wisedog requested changes
PR 감사합니다. 이번에도 영어 원문을 남겨놓으신 부분이 있군요 😂

2024-07-10 09:10 UTC, wisedog commented on files/ko/web/css/_doublecolon_spelling-error/index.md
> +Only a small subset of CSS properties can be used in a rule with `::spelling-error` in its selector:
A ㅏ......

2024-07-10 09:10 UTC, wisedog commented on files/ko/web/css/_doublecolon_spelling-error/index.md
> +몇 개의 특정한 CSS 속성만이 `::spelling-error` 과 해당 선택자 내에서 함께 사용될 수 있습니다.
`Only a small subset of CSS properties` 인데, 이는 `CSS 속성의 일부 만이` 이정도로 번역이 어떨까요? 특정은 아닌듯 하여.. 🤔

2024-07-10 09:29 UTC, givvemee commented on files/ko/web/css/_doublecolon_spelling-error/index.md
> +Only a small subset of CSS properties can be used in a rule with `::spelling-error` in its selector:
으아아아악!

2024-07-12 00:23 UTC, givvemee commented on files/ko/web/css/_doublecolon_spelling-error/index.md
> +몇 개의 특정한 CSS 속성만이 `::spelling-error` 과 해당 선택자 내에서 함께 사용될 수 있습니다.
@wisedog 네엥. 이전에 번역했던 문서와 동일하게 가져가려다보니 그렇게 했는데, 제안 주신 것이 더 적절해 보여서 수정했어요. 감사합니다.

2024-07-15 05:20 UTC, wisedog approved these changes

2024-07-15 05:20 UTC, merged