[ko] pushManager 신규 번역
mdn/translated-content pull request #22350
Opened 2024-07-10 14:52 UTC by etoile-j

### Description

Push API의  pushManager 문서를 신규 번역하였습니다.

2024-07-15 11:07 UTC, 1ilsang requested changes
@etoile-j 님 안녕하세요. 기여해주셔서 감사합니다! 💯

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

질문이나 도움이 필요하시다면 언제든 멘션 부탁드리겠습니다.

2024-07-15 11:07 UTC, 1ilsang commented on files/ko/web/api/pushmanager/index.md
> +        // 예를 들어 fetch() API를 사용하여 서버로 전송할 수 있습니다.
```suggestion
        // 이제 애플리케이션 서버에 필요한 푸시 구독
        // 세부 정보를 사용할 수 있습니다.
        // 예를 들어 fetch() API를 사용하여 서버로 전송할 수 있습니다.
```

줄 수는 [원문](https://github.com/mdn/content/blob/3a91caa0ebbc5131ed75afe0e5168cd5bffc0976/files/en-us/web/api/pushmanager/index.md?plain=1#L54-L56)과 동일하게 해주세요. 관련 논의는 [여기](https://github.com/orgs/mdn/discussions/655#discussioncomment-9251708)에서 확인할 수 있습니다.

2024-07-16 11:52 UTC, etoile-j commented
@1ilsang 이 문서도 수정하였습니다!

2024-07-16 16:14 UTC, 1ilsang approved these changes
LGTM 고생하셨습니다

2024-07-16 16:14 UTC, merged