zh-CN: update Learn/JavaScript/Client-side_web_APIs/Manipulating_documents
mdn/translated-content pull request #22379
Opened 2024-07-12 14:24 UTC by PassionPenguin

2024-07-13 07:50 UTC, yin1999 requested changes
有些内容的修改需要撤销

2024-07-13 07:50 UTC, yin1999 commented on files/zh-cn/learn/javascript/client-side_web_apis/manipulating_documents/index.md
> +- 窗口（window）是载入网页的浏览器标签；在 JavaScript 中，它由 {{domxref("Window")}} 对象表示。使用这个对象上的方法，你可以做一些事情，比如返回窗口的大小（见 {{domxref("Window.innerWidth")}} 和 {{domxref("Window.innerHeight")}}），操作加载到窗口的文档，在客户端存储该文档的特定数据（例如
event handler 就翻译成事件处理器，之前的 PR 中我们已经提到过这一点，你可以看一下术语表

2024-07-13 07:50 UTC, yin1999 commented on files/zh-cn/learn/javascript/client-side_web_apis/manipulating_documents/index.md
> +    <title>简单 DOM 示例</title>
这些代码示例之所以不翻译，就是因为这样会导致代码与截图、在线示例对不上，因此从这里到下面的所有修改都是不合适的。

2024-07-13 07:50 UTC, yin1999 commented on files/zh-cn/learn/javascript/client-side_web_apis/manipulating_documents/index.md
> +> **备注：** 请注意，CSS 样式的 JavaScript 属性版本是用{{Glossary("camel_case", "驼峰命名法")}}书写的，而 CSS 版本是{{Glossary("kebab_case", "烤串命名法")}}的（例如，`backgroundColor` 对 `background-color`）。确保你不要把这些混为一谈，否则将无法工作。
可保留此处的修改

2024-07-13 07:50 UTC, yin1999 commented on files/zh-cn/learn/javascript/client-side_web_apis/manipulating_documents/index.md
> +在编写网页和应用程序时，你最想做的事情之一就有以某种方式操纵文档结构。这通常是通过使用文档对象模型（DOM）来实现的。这是一套用于控制 HTML 和样式信息的 API，大量使用了 {{domxref("Document")}} 对象。在这篇文章中，我们将详细了解如何使用 DOM，以及其他一些有趣的 API，它们可以以有趣的方式改变你的环境。
这里的修改我感觉没必要，我感觉比较常见的表述有两种：

- 你最想做的事情有 xxx（说明不唯一）
- 你最想做的事情之一是 xxx（也同样说明不唯一）

2024-07-13 13:18 UTC, PassionPenguin commented on files/zh-cn/learn/javascript/client-side_web_apis/manipulating_documents/index.md
> +- 窗口（window）是载入网页的浏览器标签；在 JavaScript 中，它由 {{domxref("Window")}} 对象表示。使用这个对象上的方法，你可以做一些事情，比如返回窗口的大小（见 {{domxref("Window.innerWidth")}} 和 {{domxref("Window.innerHeight")}}），操作加载到窗口的文档，在客户端存储该文档的特定数据（例如
（忘记改了，sorry，我翻到后面的时候才想起来，但是搜email history一下子没搜出来lol，想着去仓库找一下，然后就把这个事忘了）

2024-07-13 13:20 UTC, PassionPenguin commented on files/zh-cn/learn/javascript/client-side_web_apis/manipulating_documents/index.md
> +> **备注：** 请注意，CSS 样式的 JavaScript 属性版本是用{{Glossary("camel_case", "驼峰命名法")}}书写的，而 CSS 版本是{{Glossary("kebab_case", "烤串命名法")}}的（例如，`backgroundColor` 对 `background-color`）。确保你不要把这些混为一谈，否则将无法工作。
🤔？

https://github.com/mdn/content/blob/da6219d9480147488eda1f9120359384ee652b92/files/en-us/learn/javascript/client-side_web_apis/manipulating_documents/index.md?plain=1#L221

驼峰=>小驼峰？

```suggestion
> **备注：** 请注意，CSS 样式的 JavaScript 属性版本是用{{Glossary("camel_case", "小驼峰命名法")}}书写的，而 CSS 版本是{{Glossary("kebab_case", "烤串命名法")}}的（例如，`backgroundColor` 对 `background-color`）。确保你不要把这些混为一谈，否则将无法工作。
```

2024-07-13 13:31 UTC, yin1999 commented on files/zh-cn/learn/javascript/client-side_web_apis/manipulating_documents/index.md
> +- 窗口（window）是载入网页的浏览器标签；在 JavaScript 中，它由 {{domxref("Window")}} 对象表示。使用这个对象上的方法，你可以做一些事情，比如返回窗口的大小（见 {{domxref("Window.innerWidth")}} 和 {{domxref("Window.innerHeight")}}），操作加载到窗口的文档，在客户端存储该文档的特定数据（例如
如果有内容还没确定，或者还想自己检查一遍的，请在提交 PR 时就选择创建草稿，而不是直接创建可供审查的 PR。

2024-07-13 13:37 UTC, yin1999 commented on files/zh-cn/learn/javascript/client-side_web_apis/manipulating_documents/index.md
> +    <title>简单 DOM 示例</title>
> 此从这里到下面的所有修改都是不合适的

下面的还没撤销

2024-07-13 13:40 UTC, PassionPenguin commented on files/zh-cn/learn/javascript/client-side_web_apis/manipulating_documents/index.md
> +    <title>简单 DOM 示例</title>
全部的代码么？👌

2024-07-14 02:11 UTC, yin1999 commented on files/zh-cn/learn/javascript/client-side_web_apis/manipulating_documents/index.md
> +> **备注：** 请注意，CSS 样式的 JavaScript 属性版本是用{{Glossary("camel_case", "小驼峰命名法")}}书写的，而 CSS 版本是{{Glossary("kebab_case", "烤串命名法")}}的（例如，`backgroundColor` 对 `background-color`）。确保你不要把这些混为一谈，否则将无法工作。
```suggestion
> **备注：** 请注意，CSS 样式的 JavaScript 属性版本是用{{Glossary("camel_case", "小驼峰命名法")}}书写的，而 CSS 版本采用连字符（{{Glossary("kebab_case", "烤串命名法")}}）（例如，`backgroundColor` 对 `background-color`）。确保你不要把这些混为一谈，否则将无法工作。
```

2024-07-14 02:11 UTC, yin1999 approved these changes

2024-07-14 02:15 UTC, merged