Html object element
mdn/translated-content pull request #22371
Opened 2024-07-12 08:36 UTC by fuchunhui

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-07-13 07:51 UTC, yin1999 reviewed
有内容冲突

2024-07-15 09:14 UTC, fuchunhui commented
> 有内容冲突

已处理，移除冲突，我误操作把另一个分支的提交带上来了，已删除。

2024-07-15 13:58 UTC, yin1999 requested changes
if any => “如果有的话”，不是“如果有，是任意值”。

2024-07-15 13:58 UTC, yin1999 commented on files/zh-cn/web/api/htmlobjectelement/index.md
> +  - : 表示应用程序类文件名称的字符串，包含程序的子类，或访问类的路径，包含文件本身。
```suggestion
  - : 表示应用程序类文件名称的字符串，包含程序的子类，或访问类的路径，包含类文件本身。
```

2024-07-15 13:58 UTC, yin1999 commented on files/zh-cn/web/api/htmlobjectelement/index.md
> +  - : 返回 {{domxref("Document")}} 表示对象元素的嵌套浏览器上下文的活动文档，如果有，是任意值；否则返回 `null`。
```suggestion
  - : 返回表示对象元素的嵌套浏览器上下文的活动文档的 {{domxref("Document")}} （如果有的话），否则返回 `null`。
```

2024-07-15 13:58 UTC, yin1999 commented on files/zh-cn/web/api/htmlobjectelement/index.md
> +  - : 返回 {{glossary("WindowProxy")}} 表示对象元素的嵌套浏览器上下文的窗口代理。如果有，是任意值；否则返回 `null`。
```suggestion
  - : 返回表示对象元素的嵌套浏览器上下文的窗口代理的 {{glossary("WindowProxy")}}（如果有的话），否则返回 `null`。
```

2024-07-15 13:58 UTC, yin1999 commented on files/zh-cn/web/api/htmlobjectelement/index.md
> +  - : 反映 [`declare`](/zh-CN/docs/Web/HTML/Element/object#declare) HTML 属性的布尔值，表示这是一个声明，而不是实例化。
```suggestion
  - : 反映 [`declare`](/zh-CN/docs/Web/HTML/Element/object#declare) HTML 属性的布尔值，表示这是对象的声明，而不是对象的实例。
```

2024-07-15 13:58 UTC, yin1999 commented on files/zh-cn/web/api/htmlobjectelement/index.md
> +  - : 返回反映 [`name`](/zh-CN/docs/Web/HTML/Element/object#name) HTML 属性的字符串，指定浏览器上下文的名称。
```suggestion
  - : 返回反映 [`name`](/zh-CN/docs/Web/HTML/Element/object#name) HTML 属性的字符串，指定浏览上下文的名称。
```

2024-07-15 13:58 UTC, yin1999 commented on files/zh-cn/web/api/htmlobjectelement/index.md
> +  - : 返回表示描述控件不满足的验证约束（如果有的话）的本地化消息字符串。如果控件不是约束验证（`willValidate` 是 `false`）的候选者，或者它满足其约束，则此字符串为空。
```suggestion
  - : 返回表示描述控件不满足的验证约束的本地化消息字符串（如果有的话）。如果控件不是约束验证（`willValidate` 是 `false`）的候选者，或者它满足其约束，则此字符串为空。
```

2024-07-15 13:58 UTC, yin1999 commented on files/zh-cn/web/api/htmlobjectelement/index.md
> +  - : 返回带有此元素所在的有效性状态 {{domxref("ValidityState")}} 。
```suggestion
  - : 返回带有此元素所处于的验证状态 {{domxref("ValidityState")}} 。
```

2024-07-15 13:58 UTC, yin1999 commented on files/zh-cn/web/api/htmlobjectelement/index.md
> +  - : 设置元素的自定义有效性消息。如果消息是空字符串，则该元素存在自定义有效性错误，无法验证。
```suggestion
  - : 设置元素的自定义验证消息。如果消息不是空字符串，则该元素存在自定义验证错误，因此无法通过验证。
```

2024-07-16 05:39 UTC, yin1999 approved these changes

2024-07-16 05:39 UTC, merged