[ko] translate Learn JavaScript client-side_web_apis/fetching_data/index.md
mdn/translated-content pull request #22401
Opened 2024-07-14 06:14 UTC by sqaurelu

### Description

/ko/learn/javascript/client-side_web_apis/fetching_data/index.md 파일 번역했습니다.

### Related issues and pull requests

- [MDN 원문 링크](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data)

2024-07-27 08:14 UTC, hochan222 requested changes
@sqaurelu 님 안녕하세요.

긴글 번역해주셔서 정말 감사하고, 고생 많으셨습니다. 내용 넘 좋습니다.

몇 가지 리뷰 사항 하기에 남겨두었습니다. 확인 부탁드립니다.

좋은 하루 보내세요 :)

2024-07-27 08:14 UTC, hochan222 commented on files/ko/learn/javascript/client-side_web_apis/fetching_data/index.md
> +이 문서에는 겉핥기 식으로 많은 주제들이 논의되어 있습니다. 이 주제들에 대한 더 많은 세부 사항을 보려면 다음 문서를 시도하세요.
```suggestion
이 문서에는 겉핥기식으로 많은 주제들이 논의되어 있습니다. 이 주제들에 대한 더 많은 세부 사항을 보려면 다음 문서를 시도하세요.
```

2024-07-27 08:14 UTC, hochan222 commented on files/ko/learn/javascript/client-side_web_apis/fetching_data/index.md
> +이 모델은 많은 사이트에서 완벽하게 동작합니다. 하지만 매우 데이터 중심적인 웹 사이트를 생각해보세요. 예를 들어, [벤쿠버 공공 도서관](https://www.vpl.ca/)같은 웹 사이트를 생각해보세요. 무엇보다도 이와 같은 사이트를 데이터베이스에 대한 사용자 인터페이스로 생각할 수 있습니다. 특정 장르의 책을 검색하거나 이전에 빌린 책을 기반으로 마
```suggestion
이 모델은 많은 사이트에서 완벽하게 동작합니다. 하지만 매우 데이터 중심적인 웹 사이트를 생각해 보세요. 예를 들어, [벤쿠버 공공 도서관](https://www.vpl.ca/)같은 웹 사이트를 생각해 보세요. 무엇보다도 이와 같은 사이트를 데이터베이스에 대한 사용자 인터페이스로 생각할 수 있습니다. 특정 장르의 책을 검색하거나 이전에 빌린 책을 기반으로 마음에 드는 책에 대한 추천을 보여줄 수 있습니다. 이 작업을 수행할 때 표시할 새 도서 세트로 페이지를 업데이트해야 합니다. 하지만 페이지 헤더, 사이드바, 바닥글과 같은 항목을 포함한 대부분의 페이지 콘텐츠는 동일하게 유지됩니다.
```

2024-07-27 08:14 UTC, hochan222 commented on files/ko/learn/javascript/client-side_web_apis/fetching_data/index.md
> +여기서 주요 API는 [Fetch API](/ko/docs/Web/API/Fetch_API)입니다. 이를 통해 페이지에서 실행되는 JavaScript가 특정 리소스를 검색하기 위해 서버에 [HTTP](/ko/docs/Web/HTTP) 요청을 할 수 있습니다. 서버가 이를 제공하면 JavaScript는 일반적으로 [DOM 조작 API](/ko/docs/Le
```suggestion
여기서 주요 API는 [Fetch API](/ko/docs/Web/API/Fetch_API)입니다. 이를 통해 페이지에서 실행되는 JavaScript가 특정 리소스를 검색하기 위해 서버에 [HTTP](/ko/docs/Web/HTTP) 요청을 할 수 있습니다. 서버가 이를 제공하면 JavaScript는 일반적으로 [DOM 조작 API](/ko/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents)를 사용하여 페이지를 업데이트하기 위한 데이터를 사용할 수 있습니다. 요청되는 데이터는 구조화된 데이터를 전송하는 데 적합한 형식인 [JSON](/ko/docs/Learn/JavaScript/Objects/JSON)인 경우가 많지만, HTML이거나 텍스트일 수도 있습니다.
```

2024-07-27 08:14 UTC, hochan222 commented on files/ko/learn/javascript/client-side_web_apis/fetching_data/index.md
> +- 매 업데이트마다 더 적은 데이터가 다운로드되며, 이는 대역폭 낭비를 줄여줍니다. 이것은 광대역 연결의 데스크톱에서는 큰 문제가 아닐수도 있지만, 모바일 장치와 유비쿼터스 빠른 인터넷 서비스가 없는 국가에서는 주요 문제입니다.
```suggestion
- 매 업데이트마다 더 적은 데이터가 다운로드되며, 이는 대역폭 낭비를 줄여줍니다. 이것은 광대역 연결의 데스크톱에서는 큰 문제가 아닐 수도 있지만, 모바일 장치와 유비쿼터스 빠른 인터넷 서비스가 없는 국가에서는 주요 문제입니다.
```

2024-07-27 08:14 UTC, hochan222 commented on files/ko/learn/javascript/client-side_web_apis/fetching_data/index.md
> +나중에 필요하므로 로드할 텍스트 파일을 가리키는 상대적인 URL을 구성하는 것으로 시작합니다. {{htmlelement("select")}} 요소의 값은 선택한 {{htmlelement("option")}} 내부의 텍스트와 동일합니다(value 속성에 다른 값을 지정하지 않는 한). 예를 들어 "Verse 1"입니다. 해당 Verse 텍스트 파일은 "Ve
```suggestion
나중에 필요하므로 로드할 텍스트 파일을 가리키는 상대적인 URL을 구성하는 것으로 시작합니다. {{htmlelement("select")}} 요소의 값은 선택한 {{htmlelement("option")}} 내부의 텍스트와 동일합니다(value 속성에 다른 값을 지정하지 않는 한). 예를 들어 "Verse 1"입니다. 해당 Verse 텍스트 파일은 "Verse 1.txt"이며 HTML 파일과 동일한 디렉터리에 있으므로 파일 이름만 있으면 됩니다.
```

2024-07-27 08:14 UTC, hochan222 commented on files/ko/learn/javascript/client-side_web_apis/fetching_data/index.md
> +이를 해결하려면 로컬 웹 서버를 통해 예제를 실행하여 테스트해야 합니다. 이 방법을 알아보려면 [로컬 테스팅 서버 설정 가이드](/ko/docs/Learn/Common_questions/Tools_and_setup/set_up_a_local_testing_server)를 참고하세요.
```suggestion
이를 해결하려면 로컬 웹 서버를 통해 예제를 실행하여 테스트해야 합니다. 이 방법을 알아보려면 [로컬 검증 서버 설정 가이드](/ko/docs/Learn/Common_questions/Tools_and_setup/set_up_a_local_testing_server)를 참고하세요.
```

2024-07-27 08:14 UTC, hochan222 commented on files/ko/learn/javascript/client-side_web_apis/fetching_data/index.md
> +이 예제에서는 통조림만 판매하는 가상의 슈퍼마켓인 캔스토어(The Can Store)라는 샘플 사이트를 만들었습니다. 이 예제는 [GitHub에서 라이브](https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/)로 볼 수 있으며 [소스 코드](https://github.co
```suggestion
이 예제에서는 통조림만 판매하는 가상의 슈퍼마켓인 캔 가게(The Can Store)라는 샘플 사이트를 만들었습니다. 이 예제는 [GitHub에서 라이브](https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/)로 볼 수 있으며 [소스 코드](https://github.com/mdn/learning-area/tree/main/javascript/apis/fetching-data/can-store)를 볼 수 있습니다.
```

2024-07-27 08:14 UTC, hochan222 commented on files/ko/learn/javascript/client-side_web_apis/fetching_data/index.md
> +기본적으로 사이트에는 모든 제품이 표시되지만 왼쪽 열에 있는 양식 컨트롤을 사용하여 범주, 검색어 또는 두 가지 모두로 제품을 필터링할 수 있습니다.
```suggestion
기본적으로 사이트에는 모든 제품이 표시되지만, 왼쪽 열에 있는 양식 컨트롤을 사용하여 범주, 검색어 또는 두 가지 모두로 제품을 필터링할 수 있습니다.
```

2024-07-27 08:14 UTC, hochan222 commented on files/ko/learn/javascript/client-side_web_apis/fetching_data/index.md
> +그러나 완전한 웹사이트는 사용자 화면에 메시지를 표시하고 상황을 해결할 수 있는 옵션을 제공함으로써 이 오류를 보다 적절하게 처리할 수 있지만, 우리는 간단한 `console.error()` 외에는 아무것도 필요하지 않습니다.
```suggestion
그러나 완전한 웹사이트는 사용자 화면에 메시지를 표시하고 상황을 해결할 수 있는 옵션을 제공함으로써, 이 오류를 보다 적절하게 처리할 수 있지만, 우리는 간단한 `console.error()` 외에는 아무것도 필요하지 않습니다.
```

2024-08-03 12:54 UTC, sqaurelu commented
> @sqaurelu 님 안녕하세요.
> 
> 긴글 번역해주셔서 정말 감사하고, 고생 많으셨습니다. 내용 넘 좋습니다.
> 
> 몇 가지 리뷰 사항 하기에 남겨두었습니다. 확인 부탁드립니다.
> 
> 좋은 하루 보내세요 :)

리뷰 감사합니다! 모두 반영했습니다. 🙇‍♀️

2024-09-04 03:50 UTC, hochan222 approved these changes
@sqaurelu 님 확인이 늦어져서 죄송합니다!

고생 정말 많으셨습니다. 좋은 하루 보내세요!

2024-09-04 03:50 UTC, merged