Fix Kor CORS not matched scheme
mdn/translated-content pull request #22446
Opened 2024-07-16 16:07 UTC by Junhyunny

### Description

In this [CORS explanation](https://developer.mozilla.org/ko/docs/Web/HTTP/CORS#%ED%94%84%EB%A6%AC%ED%94%8C%EB%9D%BC%EC%9D%B4%ED%8A%B8_%EC%9A%94%EC%B2%AD), `Origin's scheme` in the HTTP Request header and `Access-Control-Allow-Origin's scheme` in the HTTP response header are different. Basically, CORS is sensitive to scheme. So I think this examples should be fixed like that both of them have same scheme. 

### Motivation

### Additional details

### Related issues and pull requests

2024-07-16 23:10 UTC, wisedog requested changes
안녕하세요, 첫 기여 감사합니다.

영문판에 비해 뒤쳐져서 해당 문서 다 번역해주시면 좋긴 하지만(사실 이게 기본 정책), 첫 기여니까 그 자체로 의미가 있다고 봅니다. 리뷰 사항만 봐주시면 감사하겠습니다.

2024-07-16 23:10 UTC, wisedog commented on files/ko/web/http/cors/index.md
> +const url = 'https://bar.other/resources/credentialed-content/';
이걸 https 로 변경한다면 4번째 위에 있는 설명과 안맞게 되는군요. 바꾸시려면 같이 바꾸시는게 좋겠습니다.

2024-07-16 23:10 UTC, wisedog commented on files/ko/web/http/cors/index.md
> +xhr.setRequestHeader('X-PINGOTHER', 'pingpong');
해당 예제는 영문에 없습니다. 즉, 영문 문서와 동기화를 시키면 아예 없어질 내용이니 굳이 수정할 필요는 없어보입니다.

2024-07-16 23:52 UTC, Junhyunny commented
안녕하세요, 안 그래도 문서를 비교해보니 예제 코드도 서로 매치가 안 되는 것 같더군요. 페이지 전체를 번역하는 것이 더 쉬울 것 같은데 그렇게 진행해도 될까요?

2024-07-17 08:59 UTC, wisedog commented
맞습니다. 그런데 CORS 문서는 양이 꽤 많아서 괜찮으실지 모르겠습니다

2024-07-17 23:34 UTC, Junhyunny commented
오늘부터 참고 사항들 읽어 보고 한 단락씩 시작해보겠습니다.

2024-07-28 23:10 UTC, wisedog commented
오! 멋집니다! 결국 이걸 해내셨네요 👍 제가 조만간 리뷰 드리도록 하겠습니다.

2024-07-29 00:29 UTC, Junhyunny commented
> 오! 멋집니다! 결국 이걸 해내셨네요 👍 제가 조만간 리뷰 드리도록 하겠습니다.

아직 모두 끝내진 못 했습니다. 남은 부분은 리뷰 주시면 피드백에 맞도록 주의 하면서 마저 작성하도록 하겠습니다.

2024-07-29 11:57 UTC, wisedog reviewed
호오... 이거 너무 잘하셨는데요. 흠 잡을데가 거의 없습니다. 

메타데이터와 프리플라이트만 의견 부탁드리겠습니다.

2024-07-29 11:57 UTC, wisedog commented on files/ko/web/http/cors/index.md
메타 데이터에 `en-US`의 최신 커밋 해시를 넣으셔야 합니다. [해당 가이드](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md) 참고해주세요~

2024-07-29 11:57 UTC, wisedog commented on files/ko/web/http/cors/index.md
> +**교차 출처 리소스 공유**(Cross-Origin Resource Sharing, {{Glossary("CORS")}})는 브라우저가 자신의 출처가 아닌 다른 어떤 {{glossary("origin", "출처")}}(도메인, 스킴 혹은 포트)로부터 자원을 로딩하는 것을 허용하도록 서버가 허가 해주는 {{Glossary("HTTP")}} 헤더 기반 메커
`preflight`는 현업에서는 음차해서 `프리플라이트`라고 사용하기도 하지만 용어사전에서는 [사전 요청](https://developer.mozilla.org/ko/docs/Glossary/Preflight_request)이라 정의되어 있습니다. 다만 프리플라이트 == 사전요청 이라는 생각을 못하시는 분들을 위해 맨 처음에만 `사전 요청(프리플라이트, Preflight)` 정도로 하면 어떨까요? 

이 이후에는 모두 `사전 요청`이라 해석하면 좋겠습니다.

2024-07-30 03:03 UTC, wisedog approved these changes
LGTM! 고생하셨습니다.

2024-07-30 03:04 UTC, merged

2024-07-30 07:16 UTC, Junhyunny commented
아직 `Credentialed requests and wildcards` 과 `Third-party cookies` 섹션이 마무리 덜 되었는데 마저 이어서 해도 될까요? 특히 Credentialed requests and wildcards 섹션 내용은 많이 다른 것 같습니다.

2024-07-30 07:18 UTC, wisedog commented
앗 이 부분을 확인 못했군요. ㅠㅠ 별도 PR로 주실 수 있으실까요?