Translate index.html
mdn/translated-content pull request #2244
Opened 2021-08-27 05:42 UTC by IcEWaRRiOr01

Translate border-image-source into russian

2021-08-30 05:26 UTC, sashasushko requested changes
@IcEWaRRiOr01 спасибо за помощь!

Оставил несколько саджестов и одно критичное замечание - про блок спеки и примеров. Их перед переводом нужно актуализировать. Но! Будет круто, если получится взять актуальную англ. версию целиком и перекинуть туда уже переведённые кусочки. Тогда у нас в ру-версии будет свежая версия материалов.

2021-08-30 05:26 UTC, sashasushko commented on files/ru/web/css/border-image-source/index.html
> +<p>Свойство CSS <strong><code>border-image-source</code></strong> определяет {{cssxref("&lt;image&gt;")}} который будет использоваться вместо стиля границы. Если для этого свойства установлено значен
```suggestion
<p>Свойство CSS <strong><code>border-image-source</code></strong> определяет изображение {{cssxref("&lt;image&gt;")}}, которое будет использоваться вместо стиля границы. Если для этого свойства установлено значение <code>none</code>, то вместо него будет использован стиль, определённый параметром {{cssxref("border-style")}}.</p>
```

2021-08-30 05:26 UTC, sashasushko commented on files/ru/web/css/border-image-source/index.html
> +<div class="note"><strong>Предупреждение:</strong> Хотя с этим свойством CSS можно использовать любой {{cssxref("&lt;image&gt;")}} , поддержка браузеров по-прежнему ограничена, и некоторые браузеры п
```suggestion
<div class="note"><strong>Предупреждение:</strong> Хотя с этим свойством CSS можно использовать любой вид {{cssxref("&lt;image&gt;")}} , поддержка браузеров по-прежнему ограничена, и некоторые браузеры поддерживают только изображения, определённые с использованием функциональной нотации <code>url()</code> .</div>
```

2021-08-30 05:26 UTC, sashasushko commented on files/ru/web/css/border-image-source/index.html
> +<pre class="brush:css">/* без изображения границы, используется указанный стиль границы */
```suggestion
<pre class="brush:css">/* без изображения для границ, используется указанный стиль границы */
```

2021-08-30 05:26 UTC, sashasushko commented on files/ru/web/css/border-image-source/index.html
> +/* image.jpg используется в качестве изображения */
```suggestion
/* В качестве изображения используется image.jpg */
```

2021-08-30 05:26 UTC, sashasushko commented on files/ru/web/css/border-image-source/index.html
> +/* Глобальные значения */
```suggestion
/* Общие значения */
```

2021-08-30 05:26 UTC, sashasushko commented on files/ru/web/css/border-image-source/index.html
> + <dd>Указывает, что для границы не используется изображение. Вместо этого используется стиль, определенный {{cssxref("border-style")}} .</dd>
```suggestion
 <dd>Указывает, что для границ не используется изображение. Вместо этого используется стиль, определенный {{cssxref("border-style")}}.</dd>
```

2021-08-30 05:26 UTC, sashasushko commented on files/ru/web/css/border-image-source/index.html
>  <h2 id="Specifications" name="Specifications">Примеры</h2>
Блок с примерами и спекой стоит [взять из англ. версии](https://github.com/mdn/content/blob/main/files/en-us/web/css/border-image-source/index.md), тут он устарел сильно

2023-05-03 06:26 UTC, SphinxKnight commented
@IcEWaRRiOr01 (cc @sashasushko) hello :) the repository now uses Markdown files. do you need any help for this PR or should it be converted as a draft or closed since it has been opened for more than a year?

2023-06-21 14:01 UTC, closed without merging