[ko] Element.getElementsByTagNameNS() 신규 번역
mdn/translated-content pull request #22458
Opened 2024-07-17 08:54 UTC by page1597

### Description
Element.getElementsByTagNameNS()의 신규 번역을 추가하였습니다.

2024-07-17 13:48 UTC, wisedog requested changes
또 기여해주셨네요! 감사합니다! 

전반적으로 잘 하셨는데, 몇 가지 짚고 넘어가야할 점이 있네요. 
리뷰 몇 가지 남겼는데요, 확인 부탁드려도 될까요?

2024-07-17 13:48 UTC, wisedog commented on files/ko/web/api/element/getelementsbytagnamens/index.md
> +var table = document.getElementById("forecast-table");
`en-US` 문서에는 안보이던데, 혹시 확인 부탁드려도 될까요?

2024-07-17 13:48 UTC, wisedog commented on files/ko/web/api/element/getelementsbytagnamens/index.md
> +**`Element.getElementsByTagNameNS()`** 는 지정된 네임스페이스에 속하는 주어진 태그 이름을 가진 요소들의 실시간 {{domxref("HTMLCollection")}} 을 반환합니다. {{Domxref("Document.getElementsByTagNameNS")}}와 유사하지만, 지정된 요소의 하위 요소들로 검색이 제한됩니다
줄 수는 원문과 동일하게 해주세요. 관련 논의는 [여기](https://github.com/orgs/mdn/discussions/655#discussioncomment-9251708)에서 확인할 수 있습니다.

내용 이어짐과는 큰 상관 없이 줄 수만 맞추시면 됩니다.

2024-07-17 13:48 UTC, wisedog commented on files/ko/web/api/element/getelementsbytagnamens/index.md
> +---
l10n 메타데이터가 필요합니다. 자세한 내용은 [여기](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md)를 확인해주세요.

2024-07-17 16:31 UTC, page1597 commented on files/ko/web/api/element/getelementsbytagnamens/index.md
> +var table = document.getElementById("forecast-table");
확인해 보니 예제 코드가 `en-US`문서와 살짝 다른 부분이 있어서 그 부분은 수정했는데, 안보인다는 말은 어떤 말인지 제가 이해를 잘 못한 것 같습니다.🥲 원문에서는 예제 코드 부분 전쳋가 안보인다는 말씀인 건가요?

2024-07-17 22:22 UTC, wisedog commented on files/ko/web/api/element/getelementsbytagnamens/index.md
> +var table = document.getElementById("forecast-table");
엇 제가 잘못 본걸까요?  🤔
`en-US`는 [여기](https://developer.mozilla.org/en-US/docs/Web/API/Element/getElementsByTagNameNS) 같은데 여기예제랑 PR에 올라온 예제랑 너무 상이합니다.

2024-07-18 00:52 UTC, page1597 commented on files/ko/web/api/element/getelementsbytagnamens/index.md
> +var table = document.getElementById("forecast-table");
원문이랑 동일하게 코드 수정하고 다른 수정사항도 반영했습니다. 확인 부탁드립니다!

2024-07-18 01:59 UTC, wisedog commented on files/ko/web/api/element/getelementsbytagnamens/index.md
> +var table = document.getElementById("forecast-table");
린트 에러만 잡으시면 될것같습니다. 첫 문단 끝에 공백이 있어서 린트 에러 납니다.

2024-07-18 02:27 UTC, page1597 commented on files/ko/web/api/element/getelementsbytagnamens/index.md
> +var table = document.getElementById("forecast-table");
앗 네 수정했습니다. 감사합니다!

2024-07-18 05:12 UTC, wisedog approved these changes

2024-07-18 05:13 UTC, merged

2024-07-18 05:13 UTC, wisedog commented
LGTM! 고생하셨습니다!