[zh-cn]: update the translation of SpeechGrammar `src` property
mdn/translated-content pull request #22487
Opened 2024-07-19 07:42 UTC by T34-active

### Description
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SpeechGrammar/src
### Related issues and pull requests
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/speechgrammar/src/index.md
* Last commit: https://github.com/mdn/content/commit/23e1a97d50050a3b3518a4b2f67ccf42e5fd75b7

2024-07-19 09:13 UTC, yin1999 requested changes

2024-07-19 09:13 UTC, yin1999 commented on files/zh-cn/web/api/speechgrammar/src/index.md
> +{{domxref("SpeechGrammar")}} 接口的 **`src`** 属性用于设置和返回包含 `SpeechGrammar` 对象中的语法字符串。
英文的原文就很奇怪，麻烦先更正一下英文文档的内容，然后再改一下翻译。

2024-07-20 13:16 UTC, PassionPenguin commented on files/zh-cn/web/api/speechgrammar/src/index.md
> +{{domxref("SpeechGrammar")}} 接口的 **`src`** 属性用于设置和返回包含 `SpeechGrammar` 对象中的语法字符串。
```suggestion
{{domxref(“SpeechGrammar”)}} 接口的 **`src`** 属性用于获取或设置 `SpeechGrammar` 对象中包含语法的字符串。
```

2024-07-21 01:03 UTC, PassionPenguin commented on files/zh-cn/web/api/speechgrammar/src/index.md
> +  sourceCommit: 23e1a97d50050a3b3518a4b2f67ccf42e5fd75b7
```suggestion
  sourceCommit: 5ccd2f0e0565ec9b3539cc067cdae369adc307b8
```

2024-07-21 01:47 UTC, yin1999 approved these changes

2024-07-21 01:51 UTC, merged