[ko] doublecolon view transition image pair 번역
mdn/translated-content pull request #22481
Opened 2024-07-19 01:16 UTC by givvemee

### Description

기존에 한국어로 존재하지 않던 문서 [::view-transition-image-pair](https://developer.mozilla.org/en-US/docs/Web/CSS/::view-transition-image-pair)를 번역합니다. 

### Motivation

### Additional details

### Related issues and pull requests

2024-07-27 06:19 UTC, hochan222 requested changes
@givvemee 님 안녕하세요.

리뷰사항 하기에 남겨두었습니다. 확인 부탁드립니다.

고생 많으셨습니다. 좋은 하루 보내세요 :)

--- 

(+ 마크다운 code 문법 뒤에 한칸씩 공백을 두셨는데요. 두신 이유가 궁금합니다!)

2024-07-27 06:19 UTC, hochan222 commented on files/ko/web/css/_doublecolon_view-transition-image-pair/index.md
> +`<pt-name-selector>`  는 다음 값들을 가질 수 있습니다.
```suggestion
`<pt-name-selector>` 는 다음 값들을 가질 수 있습니다.
```

2024-07-27 06:19 UTC, hochan222 commented on files/ko/web/css/_doublecolon_view-transition-image-pair/index.md
> +## See also
```suggestion
## 같이 보기
```

[단어 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md)에 따라 같이 보기로 수정 부탁드립니다!

2024-07-30 00:42 UTC, givvemee commented on files/ko/web/css/_doublecolon_view-transition-image-pair/index.md
> +## See also
@hochan222 수정 완료되었어요. 감사합니다!

2024-07-30 00:50 UTC, hochan222 approved these changes
감사합니다. 좋은 하루 보내세요 :)

2024-07-30 00:51 UTC, merged