Ko css view transition old
mdn/translated-content pull request #22522
Opened 2024-07-22 01:50 UTC by givvemee

### Description

기존에 한국어로 존재하지 않던 문서 [::view-transition-old](https://developer.mozilla.org/en-US/docs/Web/CSS/::view-transition-old) 를 번역합니다.

### Motivation

### Additional details

### Related issues and pull requests

2024-07-24 07:07 UTC, 1ilsang requested changes
@givvemee 님 안녕하세요. 기여해주셔서 감사합니다! 💯

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

질문이나 도움이 필요하시다면 언제든 멘션 부탁드리겠습니다.

2024-07-24 07:07 UTC, 1ilsang commented on files/ko/web/css/_doublecolon_view-transition-old/index.md
> +> **참고:** 추가적인 뷰 전환 스타일은 `::view-transition-old` 의 애니메이션을 설정할 수 있습니다. 뷰 전환 스타일은 뷰 전환이 이루어지는 동안 동적으로 생성됩니다. 더 많은 정보는 [setup transition pseudo-elements](https://drafts.csswg.org/css-view-transitions-1/
```suggestion
> **참고:** 추가적인 뷰 전환 스타일은 `::view-transition-old` 의 애니메이션을 설정할 수 있습니다. 뷰 전환 스타일은 뷰 전환이 이루어지는 동안 동적으로 생성됩니다. 더 많은 정보는 [전환 의사 요소 설정](https://drafts.csswg.org/css-view-transitions-1/#setup-transition-pseudo-elements)과 [의사 요소 스타일 업데이트](https://drafts.csswg.org/css-view-transitions-1/#update-pseudo-element-styles) 섹션 명세서를 참고하여 확인할 수 있습니다.
```

외부 목차여도 가급적 번역하는 것을 가이드 드립니다

2024-07-25 11:39 UTC, givvemee commented
@1ilsang 리뷰 감사합니당.

2024-07-26 02:54 UTC, 1ilsang approved these changes
LGTM 고생하셨습니다

2024-07-26 02:54 UTC, merged