[ko] Intl.Locale.prototype.getCalendars() 신규 번역
mdn/translated-content pull request #22531
Opened 2024-07-22 22:55 UTC by wisedog

- Intl.Locale.prototype.getCalendars() 신규 번역

2024-07-24 07:24 UTC, 1ilsang requested changes
@wisedog 님 안녕하세요. 기여해주셔서 감사합니다! 💯

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

질문이나 도움이 필요하시다면 언제든 멘션 부탁드리겠습니다.

2024-07-24 07:24 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/intl/locale/getcalendars/index.md
> +  - : 에디오피아력, Amete Alem (기원전 약 5493년경")
```suggestion
  - : 에디오피아, 아메테 알렘력 (기원전 약 5493년경)
```

2024-07-24 07:24 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/intl/locale/getcalendars/index.md
> +  - : 에디오피아력, Amete Mihret (기원전 약 8세기)
```suggestion
  - : 에디오피아, 아메테 미흐렛력 (기원후 약 8년경)
```

2024-07-25 12:22 UTC, wisedog commented
@1ilsang  수정완료했습니다.

2024-07-26 02:53 UTC, 1ilsang approved these changes
LGTM 고생하셨습니다

2024-07-26 02:54 UTC, merged