[ko] Math.cosh() 신규 번역 외
mdn/translated-content pull request #22556
Opened 2024-07-24 03:32 UTC by wisedog

- Math.cosh() 신규 번역
- Math.floor() 최신화

2024-07-24 07:30 UTC, 1ilsang requested changes
@wisedog 님 안녕하세요. 기여해주셔서 감사합니다! 💯

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

질문이나 도움이 필요하시다면 언제든 멘션 부탁드리겠습니다.

2024-07-24 07:30 UTC, 1ilsang commented on files/ko/web/javascript/reference/global_objects/math/floor/index.md
> +  // Shift back
```suggestion
  // 뒤로 이동
```

2024-07-25 12:25 UTC, wisedog commented
@1ilsang  수정 완료했습니다.

2024-07-26 02:53 UTC, 1ilsang approved these changes
LGTM 고생하셨습니다

2024-07-26 02:53 UTC, merged