zh-CN: update Glossary/Accessible_description
mdn/translated-content pull request #22568
Opened 2024-07-25 01:18 UTC by PassionPenguin

2024-07-26 06:27 UTC, yin1999 requested changes
还是更仔细地去更新每个文档吧，有些内容还是能在第一次更改的时候就注意到的。这样也能节省大家的时间。

2024-07-26 06:27 UTC, yin1999 commented on files/zh-cn/glossary/accessible_description/index.md
> +**无障碍描述**（Accessible Description）是可以提供额外的信息给辅助技术帮助用户理解该元素及其上下文的用户界面元素描述。它是与 HTML 元素相关联的文本描述，可以为辅助技术提供元素除{{glossary("accessible name", "无障碍名称")}}之外的描述内容。这对于依赖于像是{{glossary("Screen_reader", "屏幕阅读器")}}这
```suggestion
**无障碍描述**（Accessible Description）是可以提供额外的信息给辅助技术，以帮助用户理解该元素及其上下文的用户界面元素的描述。它是与 HTML 或 SVG 元素相关联的文本描述，可以为辅助技术提供元素除{{glossary("accessible name", "无障碍名称")}}之外的描述内容。这对于依赖于像是{{glossary("Screen_reader", "屏幕阅读器")}}这样的辅助技术的用户而言尤其重要。元素的无障碍描述是{{glossary("accessibility tree", "无障碍树")}}的一部分。
```

2024-07-26 06:27 UTC, yin1999 commented on files/zh-cn/glossary/accessible_description/index.md
> +例如，{{htmlelement("table")}} 的无障碍描述是其首个 {{htmlelement("caption")}} 的内容。在一个复杂的数据表中，一两句描述表格的内容就可以为表格提供一段描述信息。这也可以是表格前后（视觉上以及源代码中的顺序）的正文段落。如果在源代码中不是这个顺序，或者想要为此特定建立一个关联，就可以使用 [`aria-describedby`](/zh-CN/d
```suggestion
例如，{{htmlelement("table")}} 的无障碍描述是其首个 {{htmlelement("caption")}} 的内容。在一个复杂的数据表中，一两句描述表格的内容就可以为表格提供一段描述信息。这也可以是表格前后（视觉上以及源代码中的顺序）的正文段落。如果在源代码中不是这个顺序，或者想要为此特定建立一个关联，就可以使用 [`aria-describedby`](/zh-CN/docs/Web/Accessibility/ARIA/Attributes/aria-describedby) 属性来关联表格及其描述文本。
```

2024-07-26 06:27 UTC, yin1999 commented on files/zh-cn/glossary/accessible_description/index.md
> +类似地，当一个用户被要求创建一段密码时，`<label>` 元素就能为 `password` 类型的 {{htmlelement("input")}} 提供了其无障碍名称。一个好的无障碍描述应当以一种对所有用户都可见的方式包含密码的要求。它也可以通过 `aria-describedby` 属性明确地与输入关联，这样就将其添加到无障碍树中作为该节点的“描述”。
```suggestion
类似地，当一个用户被要求创建一段密码时，`<label>` 元素就能为 `password` 类型的 {{htmlelement("input")}} 提供无障碍名称。好的无障碍描述应当以一种对所有用户都可见的方式包含密码的要求。它也可以通过 `aria-describedby` 属性明确地与输入关联，这样就将其添加到无障碍树中作为该节点的“描述”。
```

2024-07-26 06:27 UTC, yin1999 commented on files/zh-cn/glossary/accessible_description/index.md
> +描述被简化为文本字符串。在我们的密码示例中，如果输入的 `aria-describedby` 属性值是一个 HTML {{htmlelement("ul")}} 的 `id`，那么描述就是所有列表项的文本和文本等效项的连接文本。
```suggestion
描述被简化为文本字符串。在我们的密码示例中，如果输入的 `aria-describedby` 属性值是一个 HTML {{htmlelement("ul")}} 的 `id`，那么描述就由所有列表项的文本和文本等效项连接而成。
```

2024-07-26 06:27 UTC, yin1999 commented on files/zh-cn/glossary/accessible_description/index.md
> +对于 HTML 元素，如果一个元素没有无障碍描述，那么描述需要通过编程的方式与相关元素关联。无障碍对象模型（AOM）通过按顺序检查以下特性来计算无障碍描述直到符合为止：
考虑一下，我个人是没看懂“直到符合为止”到底是什么意思的（这样翻译也不符合原文内容）。无障碍描述应该只会使用某个属性/特性的值，而不是将所有的属性/特性都拼接起来。

```suggestion
对于 HTML 元素，如果一个元素没有无障碍描述，那么描述需要通过编程的方式与相关元素关联。无障碍对象模型（AOM）通过按顺序检查以下特性来计算无障碍描述，直到某个特性被定义为止：
```

2024-07-26 06:27 UTC, yin1999 commented on files/zh-cn/glossary/accessible_description/index.md
> +3. 语言专有的特性可能也会参与到描述的计算中，如果这一特性尚未在计算{{glossary("accessible name", "无障碍名称")}}中用上。例如：
```suggestion
3. 语言专有的特性可能也会参与到描述的计算中，如果这一特性尚未用于定义{{glossary("accessible name", "无障碍名称")}}。例如：
```

2024-07-26 06:27 UTC, yin1999 commented on files/zh-cn/glossary/accessible_description/index.md
> +这些 HTML 中定义无障碍描述的步骤在 [HTML-AAM 无障碍描述](https://www.w3.org/TR/html-aam-1.0/#accdesc-computation) 中给出。SVG 元素的无障碍描述遵循相同的步骤，只是有一些小的差异，并在 [SVG-AAM 无障碍描述](https://www.w3.org/TR/svg-aam-1.0/#mapping_addition
```suggestion
这些 HTML 中定义无障碍描述的步骤在 [HTML-AAM 无障碍描述](https://www.w3.org/TR/html-aam-1.0/#accdesc-computation)中给出。SVG 元素的无障碍描述遵循相同的步骤，只是有一些小的差异（在 [SVG-AAM 无障碍描述](https://www.w3.org/TR/svg-aam-1.0/#mapping_additional_nd)中列出）。
```

2024-07-26 06:27 UTC, yin1999 commented on files/zh-cn/glossary/accessible_description/index.md
> +- [无障碍富互联网应用（ARIA）](/zh-CN/docs/Learn/Accessibility/ARIA)
```suggestion
- [ARIA](/zh-CN/docs/Web/Accessibility/ARIA)
```

2024-07-26 06:27 UTC, yin1999 commented on files/zh-cn/glossary/accessible_description/index.md
> +- [Web 无障碍倡议（WAI）](https://www.w3.org/WAI/)
```suggestion
- [W3C Web 无障碍倡议（WAI）](https://www.w3.org/WAI/)
```

2024-07-26 06:27 UTC, yin1999 commented on files/zh-cn/glossary/accessible_description/index.md
> +- [WAI-ARIA 推荐](https://w3c.github.io/aria/)
```suggestion
- [无障碍富互联网应用（WAI-ARIA）](https://w3c.github.io/aria/)
```

2024-07-26 06:48 UTC, PassionPenguin commented on files/zh-cn/glossary/accessible_description/index.md
> +对于 HTML 元素，如果一个元素没有无障碍描述，那么描述需要通过编程的方式与相关元素关联。无障碍对象模型（AOM）通过按顺序检查以下特性来计算无障碍描述直到符合为止：
按照顺序匹配，直到某一个规则符合的时候就应用这个规则并终止

2024-07-27 06:38 UTC, yin1999 approved these changes

2024-07-27 06:38 UTC, merged