zh-CN: update Glossary/Apple_Safari
mdn/translated-content pull request #22589
Opened 2024-07-25 14:42 UTC by PassionPenguin

2024-07-25 14:48 UTC, yin1999 requested changes
仔细一点

2024-07-25 14:48 UTC, yin1999 commented on files/zh-cn/glossary/apple_safari/index.md
> +    - {{glossary("WebKit")}}
```suggestion
  - apple.com.cn 上的 [Safari 浏览器](https://www.apple.com.cn/safari/)
- [WebKit 项目](https://www.webkit.org/)
- [WebKit 构建归档](https://webkit.org/build-archives/)
- [提交 Safari Bug](https://bugs.webkit.org/)
- 相关术语：
  - {{glossary("Browser", "Web 浏览器")}}
  - {{glossary("WebKit")}}
```

2024-07-25 14:51 UTC, PassionPenguin commented on files/zh-cn/glossary/apple_safari/index.md
> +    - {{glossary("WebKit")}}
oops, sorry

2024-07-27 06:53 UTC, yin1999 approved these changes

2024-07-27 06:53 UTC, merged