zh-CN: update Glossary/ARIA
mdn/translated-content pull request #22591
Opened 2024-07-25 14:50 UTC by PassionPenguin

2024-07-26 09:20 UTC, yin1999 requested changes

2024-07-26 09:20 UTC, yin1999 commented on files/zh-cn/glossary/aria/index.md
> +**ARIA** (_无障碍富{{glossary("Internet", "因特网")}}应用_) 是向{{Glossary("HTML")}} 中添加语义和其他元数据的{{Glossary("W3C")}} 规范，从而让 Web 内容与程序对残障人士更加友好。它又岂能帮助使用 HTML、JavaScript 和相关技术开发的动态内容和高级用户界面控件。
翻译成“富互联网应用”，保持上下文一致。此外，这段话还是和英文文档不一致的

```suggestion
**ARIA** (_无障碍富{{glossary("Internet", "互联网")}}应用_) 是向 {{Glossary("HTML")}} 中添加语义和其他元数据的{{Glossary("W3C")}} 规范，从而让 Web 内容与程序对残障人士更加友好。它又岂能帮助使用 HTML、JavaScript 和相关技术开发的动态内容和高级用户界面控件。
```

2024-07-26 11:50 UTC, PassionPenguin commented on files/zh-cn/glossary/aria/index.md
> +- [Web 无障碍倡议（WAI）](https://www.w3.org/WAI/)
```suggestion
- W3C 上的 [Web 无障碍倡议（WAI）](https://www.w3.org/WAI/)
```

2024-07-26 11:50 UTC, PassionPenguin commented on files/zh-cn/glossary/aria/index.md
> +- [ARIA 创作实践指南 (APG)](https://www.w3.org/WAI/ARIA/apg/)
```suggestion
- [ARIA 创作实践指南（APG）](https://www.w3.org/WAI/ARIA/apg/)
```

2024-07-26 11:50 UTC, PassionPenguin commented on files/zh-cn/glossary/aria/index.md
> +**ARIA** (_无障碍富{{glossary("Internet", "因特网")}}应用_) 是向{{Glossary("HTML")}} 中添加语义和其他元数据的{{Glossary("W3C")}} 规范，从而让 Web 内容与程序对残障人士更加友好。它又岂能帮助使用 HTML、JavaScript 和相关技术开发的动态内容和高级用户界面控件。
ARIA ([Accessible](https://developer.mozilla.org/en-US/docs/Glossary/Accessibility) Rich [Internet](https://developer.mozilla.org/en-US/docs/Glossary/Internet) Applications) is a [W3C](https://developer.mozilla.org/en-US/docs/Glossary/W3C) specification developed by [WAI](https://developer.mozilla.org/en-US/docs/Glossary/WAI) to make Web content and Web applications more accessible to people with disabilities. It especially helps with dynamic content and advanced user interface controls developed with HTML, JavaScript, and related technologies.

```suggestion
**ARIA** (_无障碍富{{glossary("Internet", "互联网")}}应用_) 是由 {{glossary("WAI")}} 开发的 {{Glossary("W3C")}} 规范，旨在向 {{Glossary("HTML")}} 中添加语义和其他元数据的，从而让 Web 内容与程序对残障人士更加友好。它尤其帮助使用 HTML、JavaScript 和相关技术开发的动态内容和高级用户界面控件。
```

2024-07-27 06:51 UTC, yin1999 reviewed
哥们，还是建议在改完内容以后和英文文档的内容对一下。“参见”部分改了以后还是有差异

2024-07-27 06:51 UTC, yin1999 commented on files/zh-cn/glossary/aria/index.md
> +**ARIA** (_无障碍富{{glossary("Internet", "互联网")}}应用_) 是由 {{glossary("WAI")}} 开发的 {{Glossary("W3C")}} 规范，旨在向 {{Glossary("HTML")}} 中添加语义和其他元数据的，从而让 Web 内容与程序对残障人士更加友好。它尤其帮助使用 HTML、JavaScript 和相关技术开发的动态内容和
```suggestion
**ARIA** (_{{Glossary("Accessibility", "无障碍")}}富{{glossary("Internet", "互联网")}}应用_) 是由 {{glossary("WAI")}} 开发的 {{Glossary("W3C")}} 规范，旨在让 Web 内容与程序对残障人士更加友好。它尤其有助于使用 HTML、JavaScript 和相关技术开发的动态内容和高级用户界面控件。
```

2024-07-27 06:51 UTC, yin1999 commented on files/zh-cn/glossary/aria/index.md
> +例如，你可以将 `role="alert"` 添加到 {{HTMLElement("p")}} {{glossary("tag", "标签")}}来告知视力有问题的用户，这段信息是重要的（要不然你应该是会通过文字颜色传达这个意思）。
```suggestion
例如，你可以将 `role="alert"` 添加到 {{HTMLElement("p")}} {{glossary("tag", "标签")}}来告知视力有问题的用户，这段信息是重要的（要不然你应该会通过文字颜色传达这个意思）。
```

2024-07-27 06:51 UTC, yin1999 commented on files/zh-cn/glossary/aria/index.md
> +- [WAI-ARIA 推荐](https://w3c.github.io/aria/)
```suggestion
- [无障碍富互联网应用（WAI-ARIA）](https://w3c.github.io/aria/)
```

2024-07-27 06:51 UTC, yin1999 commented on files/zh-cn/glossary/aria/index.md
> +- W3C 上的 [Web 无障碍倡议（WAI）](https://www.w3.org/WAI/)
```suggestion
- [W3C Web 无障碍倡议（WAI）](https://www.w3.org/WAI/)
```

2024-07-27 07:56 UTC, yin1999 approved these changes

2024-07-27 07:56 UTC, merged