zh-CN: update Glossary/ATAG
mdn/translated-content pull request #22603
Opened 2024-07-26 01:38 UTC by PassionPenguin

2024-07-26 02:38 UTC, jasonren0403 requested changes
请检查下所提交的文件（你似乎误删除了 attribute 的翻译）

2024-07-26 02:42 UTC, PassionPenguin commented
> 请检查下所提交的文件（你似乎误删除了 attribute 的翻译）

attribute是误添加到这儿的（

2024-07-26 09:07 UTC, PassionPenguin commented
> 不是这样撤销的，你这样会把文件删掉

诶，我记得我是rollback了诶，应该是给搞错了（

2024-07-26 09:10 UTC, yin1999 commented
要撤销文件的修改，就只要保证，你新建的所有提交在合并以后，是没有特定文件的任何修改的（而不是删除这个文件）。所以最简单的方法就找到当前 PR 所基于的基础 commit，去复制对应文件的全部内容，覆盖提交一下。

2024-07-27 03:13 UTC, jasonren0403 approved these changes
👍

2024-07-27 03:14 UTC, merged