zh-CN: update Glossary (A-B)
mdn/translated-content pull request #22613
Opened 2024-07-26 02:45 UTC by PassionPenguin

2024-07-30 02:05 UTC, yin1999 requested changes

2024-07-30 02:05 UTC, yin1999 commented on files/zh-cn/glossary/asynchronous/index.md
未更新 `l10n.sourceCommit`

2024-07-30 02:05 UTC, yin1999 commented on files/zh-cn/glossary/boolean/aria/index.md
未更新 `l10n.sourceCommit`

2024-07-30 02:05 UTC, yin1999 commented on files/zh-cn/glossary/browsing_context/index.md
> +  - {{glossary("Origin", "源")}}
未更新英文文档（应翻译为“来源”）

2024-07-30 02:05 UTC, yin1999 commented on files/zh-cn/glossary/buffer/index.md
> +**缓冲区**是物理内存中用于在数据进行转移时临时存放数据的一个存储区域。
```suggestion
**缓冲区**是物理内存中用于在数据进行转移时临时存放数据的存储区域。
```

2024-07-30 15:08 UTC, PassionPenguin commented on files/zh-cn/glossary/arpanet/index.md
>  - 维基百科上的[高级研究计划局网络](https://zh.wikipedia.org/wiki/ARPANET)
```suggestion
- 维基百科上的[高级研究计划局网络](https://zh.wikipedia.org/wiki/ARPANET)
- 相关术语：
  - {{Glossary("arpa", ".arpa")}}
  - {{Glossary("TCP")}}
```

2024-07-30 15:45 UTC, PassionPenguin commented on files/zh-cn/glossary/browsing_context/index.md
> +  - {{glossary("Origin", "源")}}
awaiting https://github.com/mdn/content/pull/35246

2024-07-31 00:53 UTC, yin1999 approved these changes
Thanks

2024-07-31 00:53 UTC, merged