[ko] delete operator 신규 번역
mdn/translated-content pull request #22719
Opened 2024-07-28 06:53 UTC by rami0617

- delete operator([영어문서](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete)) 번역

처음이라 미숙한 부분이 많습니다. 
리뷰 주시면 반영하겠습니다. 감사합니다!

2024-07-28 08:57 UTC, wisedog requested changes
안녕하세요! 첫 기여 매우 감사합니다. 

처음부터 도전적인 문서를 선택하셨는데요, 리뷰를 하면서 처음 번역 하시는 분께 너무 어려운걸 추천드렸나 좀 죄송하긴 했습니다. 눈높이에 맞지 않는 추천 죄송합니다.

다만, 생각보다 굉장히 잘 하셔서 놀랐습니다. 다만 크게 아래 부분만 고치시면 좋겠습니다.
- `en-US` 문서의 백틱(`)은 그대로 옮겨야 한다는 점
- 일부 단어 미번역

이 정도만 해결되면 바로 머지가 가능하리라 생각됩니다.

2024-07-28 08:57 UTC, wisedog commented on files/ko/web/javascript/reference/operators/delete/index.md
> +---
[가이드](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md)에 따르면 메타데이터에 [`en-US` 문서](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/delete/index.md?plain=1)의 최신 커밋 해시를 넣어야합니다. 

```suggestion
l10n:
  sourceCommit: 8cb0caef8175e1772f13ef7bc761f9616e2c5a4b
---
```

이 되겠네요.

2024-07-28 08:57 UTC, wisedog commented on files/ko/web/javascript/reference/operators/delete/index.md
> +**`delete` 연산자**는 객체의 속성을 제거합니다. 속성의 값이 객체이고 더 이상 그 객체에 대한 참조가 없다면, 해당 객체는 결국 자동으로 메모리에서 해제됩니다.
본문이 **`delete`** operator 라서 정확하게 **`delete`** 만 해주시면 되겠습니다.

2024-07-28 08:57 UTC, wisedog commented on files/ko/web/javascript/reference/operators/delete/index.md
> +## See also
`같이 보기`로 번역하며, 아래 링크도 해석할 수 있으면 해석을 추천드립니다.

2024-07-28 08:57 UTC, wisedog commented on files/ko/web/javascript/reference/operators/delete/index.md
> +## Browser compatibility
`브라우저 호환성` 입니다.

2024-07-28 08:57 UTC, wisedog commented on files/ko/web/javascript/reference/operators/delete/index.md
> +## Specifications
`명세서` 입니다

2024-07-28 08:57 UTC, wisedog commented on files/ko/web/javascript/reference/operators/delete/index.md
> +배열 요소를 삭제해도 `길이`는 영향을 받지 않습니다. 심지어 배열의 마지막 요소를 삭제하더라도 마찬가지입니다.
en-US 문서에서 `` 으로 설정한 단어는 그냥 원문 그대로 사용합니다. 여기선 `length` 겠네요.

2024-07-28 08:57 UTC, wisedog commented on files/ko/web/javascript/reference/operators/delete/index.md
> +속성이 [own](/ko/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn) [non-configurable](/ko/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#configurable_attribute) 속성인 경우를 제외하
1. `true`, `false` 해주시고
2. non-strict 모드는 엄격 모드가 아닌, 즉 비 엄격 모드라고 번역하면 좋겠습니다. 
3. own, non-configurable은 번역의 묘를 발휘하시면 좋겠는데요. 개인적으로는 [자체] , [구성 불가한] 정도로 번역하면 어떨까 합니다.

2024-07-28 08:57 UTC, wisedog commented on files/ko/web/javascript/reference/operators/delete/index.md
> +`delete` 연산자는 [`typeof`](/ko/docs/Web/JavaScript/Reference/Operators/typeof)와 같은 다른 단항 연산자와 동일한 [우선순위](/ko/docs/Web/JavaScript/Reference/Operators/Operator_precedence)를 갖습니다. 따라서 더 높은 우선순위의 연산자에 의해 형
strict mode 는 `엄격 모드` 로 번역 가능합니다.

2024-07-28 08:57 UTC, wisedog commented on files/ko/web/javascript/reference/operators/delete/index.md
> +`delete`연산자는 객체에서 주어진 속성을 삭제합니다. 성공적으로 삭제하면 `true`를 반환하고, 실패하면 `false`를 반환합니다. 일반적인 믿음(아마도 C++의 delete와 같은 다른 프로그래밍 언어들 때문에)과 달리 `delete`연산자는 메모리를 직접 해제하는 것과 전혀 관련이 없습니다. 메모리 관리는 참조를 끊는 방식으로 간접적으로 이루
본문의 `delete in C++` 링크가 빠졌습니다.

2024-07-28 08:57 UTC, wisedog commented on files/ko/web/javascript/reference/operators/delete/index.md
> +[classes](/ko/docs/Web/JavaScript/Reference/Classes)는 자동으로 strict mode로 작동하며, [private 속성](/ko/docs/Web/JavaScript/Reference/Classes/Private_properties)은 class body 내에서만 참조될 수 있기 때문에 private 속성은 절대 삭
classes는  `클래스`, class body 는 `클래스 본문` 정도로 번역하면 되겠습니다. 

또한 `delete identifier` 는 원문 그대로 사용하셔야해요.

2024-07-28 08:57 UTC, wisedog commented on files/ko/web/javascript/reference/operators/delete/index.md
> +- 함수 매개변수를 포함한 변수를 삭제하면 작동하지 않습니다. strict mode에서 `delete variable`는 {{jsxref("SyntaxError")}}를 발생시키며, non-strict mode에서는 아무런 일도 일어나지 않습니다.
스코프는 "범위"로 해석합니다. [참고](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md)

2024-07-28 08:57 UTC, wisedog commented on files/ko/web/javascript/reference/operators/delete/index.md
> +이렇게 하면 빈 슬롯이 있는 [sparse array](/ko/docs/Web/JavaScript/Guide/Indexed_collections#sparse_arrays)이 생성됩니다. 배열요소가 존재하지만 값이 undefined이기를 원한다면 `delete` 연산자 대신에 `undefined`를 사용해야 합니다. 다음 예제에서 `tree[3]`에 `un
현업에서 딱히 적해보진 않았을테지만  `sparse array`는 `희소 배열`이라고 합니다. `undefined` 백틱을 주의해주세요!

2024-07-29 03:04 UTC, rami0617 commented
> 안녕하세요! 첫 기여 매우 감사합니다.
> 
> 처음부터 도전적인 문서를 선택하셨는데요, 리뷰를 하면서 처음 번역 하시는 분께 너무 어려운걸 추천드렸나 좀 죄송하긴 했습니다. 눈높이에 맞지 않는 추천 죄송합니다.
> 
> 다만, 생각보다 굉장히 잘 하셔서 놀랐습니다. 다만 크게 아래 부분만 고치시면 좋겠습니다.
> 
> * `en-US` 문서의 백틱(`)은 그대로 옮겨야 한다는 점
> * 일부 단어 미번역
> 
> 이 정도만 해결되면 바로 머지가 가능하리라 생각됩니다.



> 안녕하세요! 첫 기여 매우 감사합니다.
> 
> 처음부터 도전적인 문서를 선택하셨는데요, 리뷰를 하면서 처음 번역 하시는 분께 너무 어려운걸 추천드렸나 좀 죄송하긴 했습니다. 눈높이에 맞지 않는 추천 죄송합니다.
> 
> 다만, 생각보다 굉장히 잘 하셔서 놀랐습니다. 다만 크게 아래 부분만 고치시면 좋겠습니다.
> 
> * `en-US` 문서의 백틱(`)은 그대로 옮겨야 한다는 점
> * 일부 단어 미번역
> 
> 이 정도만 해결되면 바로 머지가 가능하리라 생각됩니다.

리뷰 감사합니다! 말씀해 주신대로 수정하겠습니다.

2024-07-29 03:46 UTC, rami0617 commented
바쁘실텐데 리뷰해주셔서 감사합니다!
리뷰 주신대로 반영하였고 미흡한 점은 없는지 검토 부탁드립니다. 감사합니다!☺️

2024-07-29 04:53 UTC, wisedog approved these changes
LGTM! 매우 좋습니다. 훌륭하네요. 

다시 한 번 기여 감사드립니다.

2024-07-29 04:55 UTC, merged

2024-07-29 05:18 UTC, rami0617 commented
@wisedog 감사합니다!
그런데 아직 mdn에 반영이 되지 않은것 같습니다! 혹시 제가 무엇을 잘못했을까요..?

2024-07-29 06:18 UTC, wisedog commented
> @wisedog 감사합니다! 그런데 아직 mdn에 반영이 되지 않은것 같습니다! 혹시 제가 무엇을 잘못했을까요..?

MDN에서는 새로운 문서 혹은 수정된 내역을 즉각적으로 반영되지 않고 주기적으로 반영하기 때문에 1~2일 뒤에 확인해보시면 보실 수 있을겁니다😊

2024-07-29 06:22 UTC, rami0617 commented
아하! 그렇군요!
친절한 설명 감사합니다!
짧은 기간이었지만 친절히 설명해주시고 안내해주셔서 할 수 있었습니다. 다시 한 번 감사드립니다! 😁
큰 기여는 아니였지만 자그마한 기여를 한 후기를 제 블로그에 포스트 해도 될까요?

2024-07-29 06:37 UTC, wisedog commented
물론입니다. : ) 욕만 하지 말아주세요 😂

2024-07-29 06:40 UTC, rami0617 commented
핳 그럴리가 있나요~!
남은 하루 평온하게 지내시길 바랍니다. 감사합니다☺️