[ko] 교차 출처 리소스 공유(CORS) 재작성
mdn/translated-content pull request #22830
Opened 2024-07-30 16:39 UTC by Junhyunny

안녕하세요.

[Fix Kor CORS not matched scheme #22446](https://github.com/mdn/translated-content/pull/22446) PR에 이어 남은 번역 내용 올립니다. 

감사합니다.

2024-07-30 22:53 UTC, wisedog commented
@1ilsang  이 분의 지난 PR 을 제가 담당했었는데요, 미완성임을 인지 못하고 닫아버려서 그런데 제가 리뷰어로 마저 마무리해도 될까요?

2024-07-31 02:28 UTC, 1ilsang commented
@wisedog 님 넵 그렇게 해주시면 감사하겠습니다~!

2024-08-01 04:13 UTC, wisedog commented
@Junhyunny 리뷰 가능한 상태일까요? 다 안되셨다면 Draft 로 만드시고 리뷰 가능하실 때 Draft 떼주세요

2024-08-03 14:24 UTC, Junhyunny commented
> @Junhyunny 리뷰 가능한 상태일까요? 다 안되셨다면 Draft 로 만드시고 리뷰 가능하실 때 Draft 떼주세요

번역은 마무리 했습니다. 리뷰 잘 부탁드립니다.

2024-08-07 13:09 UTC, wisedog requested changes
고생하셨습니다! 전반적으로 백틱(`)이 조금 걸립니다.

2024-08-07 13:09 UTC, wisedog commented on files/ko/web/http/cors/index.md
> +요청에 자격 증명(가장 일반적으로는 `쿠키` 헤더)이 포함되고 응답에 `Access-Control-Allow-Origin: *` 헤더(즉, 와일드카드)가 포함되어 있으면, 브라우저는 응답에 대한 접근을 차단하고 개발자 도구 콘솔에 CORS 오류를 보고합니다.
백틱 안의 내용은 그대로 사용합니다. `쿠키`가 아니라 `Cookie` 입니다. 아래도 마찬가지 입니다.

2024-08-07 13:09 UTC, wisedog commented on files/ko/web/http/cors/index.md
>  ## 명세
`명세서`입니다.

2024-08-07 13:09 UTC, wisedog commented on files/ko/web/http/cors/index.md
하시는거 아래 같이보기도 해석할 수 있는 부분은 해석해주시면 어떨까요? 🥹

2024-08-08 12:55 UTC, Junhyunny commented
> 고생하셨습니다! 전반적으로 백틱(`)이 조금 걸립니다.

같이보기도 번역해봤는데 조금 어색한 것 같기도 하네요.

2024-08-11 22:34 UTC, wisedog approved these changes
LGTM!

2024-08-11 22:34 UTC, merged

2024-08-12 00:18 UTC, Junhyunny commented
수고하셨습니다.