[ko] double colon placeholder 번역
mdn/translated-content pull request #22925
Opened 2024-08-05 02:46 UTC by givvemee

### Description

기존에 한국어로 존재하지 않던 문서 [::placeholder](https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder) 를 번역합니다.

### Motivation

### Additional details

### Related issues and pull requests

2024-09-29 12:55 UTC, sunhpark42 requested changes, later dismissed
안녕하세요 @givvemee 님 리뷰가 많이 늦어 죄송합니다 ㅠㅠ
수정 필요한 부분이 있어 코멘트 남겨두었습니다. 확인 부탁드립니다.
다시 한 번 너무 늦게 리뷰 드려 죄송합니다.
감사합니다.

2024-09-29 12:55 UTC, sunhpark42 commented on files/ko/web/css/_doublecolon_placeholder/index.md
> +{{cssxref("::first-line")}} 의사 요소에 적용할 수 있는 한정적인 수의 CSS만이 `::placeholder` 와 그 선택자 규칙에 사용될 수 있습니다.
subset 이라서 한정적인 수 보다는 하위 집합은 어떨까요? 

> {{cssxref("::first-line")}} 의사 요소에 적용되는 CSS 속성의 하위 집합만 `::placeholder` 와 그 선택자 규칙에 사용될 수 있습니다.

2024-09-29 12:55 UTC, sunhpark42 commented on files/ko/web/css/_doublecolon_placeholder/index.md
> +> [!참고]
```suggestion
> [!NOTE]
```
변경 부탁드립니다~

2024-10-04 14:14 UTC, givvemee commented on files/ko/web/css/_doublecolon_placeholder/index.md
> +{{cssxref("::first-line")}} 의사 요소에 적용할 수 있는 한정적인 수의 CSS만이 `::placeholder` 와 그 선택자 규칙에 사용될 수 있습니다.
수정 완료되었어요. 감사합니다. XD

2024-10-27 18:02 UTC, hochan222 approved these changes
PR 지연이 많이되었고, 리뷰사항 잘 반영된듯해서 병합하도록 하겠습니다.

모두 고생 많으셨습니다. 좋은 하루 보내세요 :)

2024-10-27 18:02 UTC, merged