zh-CN: create `action.getBadgeText()`
mdn/translated-content pull request #22943
Opened 2024-08-06 12:45 UTC by PassionPenguin

2024-08-08 09:40 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/action/getbadgetext/index.md
> +> 该 API 基于 Chromium 的 [`chrome.action`](https://developer.chrome.com/docs/extensions/reference/action/#method-getBadgeText) API。该文档衍生于 Chromium 代码中的 [`browser_action.json`](https://chromium.googlesou
```suggestion
> 该 API 基于 Chromium 的 [`chrome.action`](https://developer.chrome.com/docs/extensions/reference/action/#method-getBadgeText) API。本文衍生自 Chromium 代码中的 [`browser_action.json`](https://chromium.googlesource.com/chromium/src/+/master/chrome/common/extensions/api/browser_action.json)。
```

2024-08-10 08:09 UTC, yin1999 requested changes

2024-08-10 08:09 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/action/getbadgetext/index.md
> +      - : `integer`，指定要获取徽标文本的窗口。
```suggestion
      - : `integer`，指定要获取徽章文本的标签页。
    - `windowId` {{optional_inline}}
      - : `integer`，指定要获取徽章文本的窗口。
```

2024-08-10 08:09 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/action/getbadgetext/index.md
> +- 若同时未指定 `windowId` 和 `tabId`，则返回全局徽标的文本。
```suggestion
- 若同时未指定 `windowId` 和 `tabId`，则返回全局的徽章文本。
```

2024-08-10 08:09 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/action/getbadgetext/index.md
> +以字符串形式兑现徽标文本的 [`Promise`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)。
```suggestion
一个 [`Promise`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)，会兑现包含徽章文本的字符串。
```

2024-08-10 08:09 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/action/getbadgetext/index.md
> +输出徽标文本：
```suggestion
输出徽章文本：
```

2024-08-12 06:27 UTC, yin1999 approved these changes

2024-08-12 06:27 UTC, merged