zh-CN: create `action`
mdn/translated-content pull request #22972
Opened 2024-08-07 05:01 UTC by PassionPenguin

2024-08-07 06:46 UTC, yin1999 requested changes
扫一眼看到的问题有这么几处，整体的翻译再看看

2024-08-07 06:46 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/action/index.md
> +读取并修改使用 [`action`](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/action) 清单键定义的浏览器工具栏按钮的属性，并监听点击事件。
再想想这句话的翻译，现在的翻译是不对的

2024-08-07 06:46 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/action/index.md
> +如果指定了弹窗，当用户点击图标时，它会显示 — 并加载内容。如果没有指定弹窗，当用户点击图标时，会向你的扩展发送一个事件。
```suggestion
如果指定了弹窗，当用户点击图标时，它会显示并加载内容。如果没有指定弹窗，当用户点击图标时，会向你的扩展发送一个事件。
```

2024-08-07 06:46 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/action/index.md
> +## Events
```suggestion
## 事件
```

2024-08-07 09:29 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/action/index.md
> +读取并修改使用 [`action`](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/action) 清单键定义的浏览器工具栏按钮的属性，并监听点击事件。
有问题嘛……Read and modify **attributes of** and listen to **clicks on** the ***browser toolbar button*** defined with the [action](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/action) manifest key.

```suggestion
读取并修改使用 [`action`](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/action) 清单键定义的浏览器工具栏按钮的属性，并监听按钮的点击事件。
```

2024-08-07 09:29 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/action/index.md
> +你可以将弹窗与按钮关联。与网页一样，弹窗使用 HTML、CSS 和 JavaScript 指定。在弹窗中运行的 JavaScript 可以访问与后台脚本相同的 WebExtension API，但其全局上下文是弹窗，而不是浏览器中显示的当前页面。要影响网页，你需要通过[消息](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Modify_a_web_page#
```suggestion
你可以将弹窗与按钮关联。与网页一样，弹窗使用 HTML、CSS 和 JavaScript 指定。在弹窗中运行的 JavaScript 可以访问与后台脚本相同的 WebExtension API，但其全局上下文是弹窗，而不是浏览器中显示的当前页面。要影响网页，你需要通过[消息](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Modify_a_web_page#消息)与网页进行通信。
```

2024-08-07 09:29 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/action/index.md
> +按钮还有一个上下文菜单，你可以使用 `action` {{WebExtAPIRef("menus.ContextType")}} API 使用 `action` API 添加项目到这个菜单。
```suggestion
按钮还有一个上下文菜单。你可以利用 {{WebExtAPIRef("menus")}} API 中 `action` 的  {{WebExtAPIRef("menus.ContextType")}} 添加上下文菜单项。
```

2024-08-07 09:29 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/action/index.md
> +- 获取和设置图标的属性（图标、标题、弹窗等）。你可以全局获取和设置这些属性，跨所有标签页，或者通过传递标签页 id 作为额外参数来为标签页设置。
```suggestion
- 获取和设置图标的属性（图标、标题、弹窗等）。你可以全局（对所有标签页）获取和设置这些属性，也可以通过传递标签页 id 作为额外参数来为某个标签页获取和设置这些属性。
```

2024-08-07 09:29 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/action/index.md
> +  - : 四个范围在 0-255 间的整型的数组，表示一个颜色。
```suggestion
  - : 四个范围在 0-255 间的整型组成的数组，表示一个颜色。
```

2024-08-08 01:06 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/action/index.md
> +- 获取和设置图标的属性（图标、标题、弹窗等）。你可以全局（对所有标签页）获取和设置这些属性，也可以通过传递标签页 id 作为额外参数来为某个标签页获取和设置这些属性。
再考虑一下第二句话的翻译，其原意表达的应该是“获取和设置的属性是全局的”

2024-08-08 01:06 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/action/index.md
> +  - : 四个范围在 0-255 间的整型组成的数组，表示一个颜色。
```suggestion
  - : 四个范围在 0-255 间的整型组成的数组，表示一个 RGBA 颜色。
```

2024-08-08 01:06 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/action/index.md
> +  - : 设置浏览器操作的标题。标题显示在鼠标悬停在浏览器操作图标上时的工具提示中。
不一致

2024-08-08 01:06 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/action/index.md
> +  - : 设置用户单击浏览器操作图标时打开的 HTML 文档。
```suggestion
  - : 设置用户单击浏览器操作图标时打开的弹窗所用的 HTML 文档。
```

2024-08-08 01:06 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/action/index.md
> +  - : 设置用户单击浏览器操作图标时打开的 HTML 文档。
```suggestion
  - : 设置用户单击浏览器操作图标时打开的弹窗所用的 HTML 文档。
```

2024-08-08 01:06 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/action/index.md
> +> 该 API 基于 Chromium 的 [`chrome.action`](https://developer.chrome.com/docs/extensions/reference/action/) API。该文档衍生于 Chromium 代码中的 [`action.json`](https://chromium.googlesource.com/chromium/src/+/maste
```suggestion
> 该 API 基于 Chromium 的 [`chrome.action`](https://developer.chrome.com/docs/extensions/reference/action/) API。该文档衍生自 Chromium 代码中的 [`action.json`](https://chromium.googlesource.com/chromium/src/+/master/chrome/common/extensions/api/action.json)。
```

2024-08-08 02:46 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/action/index.md
> +- 获取和设置图标的属性（图标、标题、弹窗等）。你可以全局（对所有标签页）获取和设置这些属性，也可以通过传递标签页 id 作为额外参数来为某个标签页获取和设置这些属性。
yeap，我的表达想法也是如此，，？

```suggestion
- 获取和设置图标的属性（图标、标题、弹窗等）。你可以全局地（对所有标签页而言）获取和设置这些属性，也可以通过传递标签页 id 作为额外参数来对某个标签页单独获取和设置这些属性。
```

2024-08-08 02:47 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/action/index.md
> +  - : 设置浏览器操作的标题。标题显示在鼠标悬停在浏览器操作图标上时的工具提示中。
```suggestion
  - : 设置浏览器操作的标题。这会在工具提示中显示出来。
```

2024-08-08 05:45 UTC, yin1999 approved these changes

2024-08-08 05:45 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/action/index.md
> +- 获取和设置图标的属性（图标、标题、弹窗等）。你可以全局地（对所有标签页而言）获取和设置这些属性，也可以通过传递标签页 id 作为额外参数来对某个标签页单独获取和设置这些属性。
```suggestion
- 获取和设置图标的属性（图标、标题、弹窗等）。你可以获取和设置这些属性的全局值（针对所有标签页），也可以通过传递标签页 id 作为额外参数来对某个标签页单独获取和设置这些属性。
```

2024-08-08 05:47 UTC, merged