zh-CN: create `events.UrlFilter`
mdn/translated-content pull request #22985
Opened 2024-08-07 14:12 UTC by PassionPenguin

2024-08-08 09:35 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/events/urlfilter/index.md
> +> 该 API 基于 Chromium 的 [`chrome.events](https://developer.chrome.com/docs/extensions/reference/events/#type-UrlFilter) API。本文衍生于 Chromium 代码中的 [`events.json`](https://chromium.googlesource.com/chromiu
```suggestion
> 该 API 基于 Chromium 的 [`chrome.events](https://developer.chrome.com/docs/extensions/reference/events/#type-UrlFilter) API。本文衍生自 Chromium 代码中的 [`events.json`](https://chromium.googlesource.com/chromium/src/+/master/extensions/common/api/events.json)。
```

2024-08-09 01:26 UTC, yin1999 requested changes
麻烦看一下预览，提交翻译内容时请务必检察一遍预览内容。我和你强调过好几次了

2024-08-09 03:12 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/events/urlfilter/index.md
> +> 该 API 基于 Chromium 的 [`chrome.events](https://developer.chrome.com/docs/extensions/reference/events/#type-UrlFilter) API。本文衍生自 Chromium 代码中的 [`events.json`](https://chromium.googlesource.com/chromiu
```suggestion
> 该 API 基于 Chromium 的 [`chrome.events`](https://developer.chrome.com/docs/extensions/reference/events/#type-UrlFilter) API。本文衍生自 Chromium 代码中的 [`events.json`](https://chromium.googlesource.com/chromium/src/+/master/extensions/common/api/events.json)。
```

2024-08-09 05:02 UTC, yin1999 commented
定义列表也不对

![image](https://github.com/user-attachments/assets/01c3bc41-3d07-478f-ba6e-7409925a0243)

2024-08-09 07:21 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/events/urlfilter/index.md
> +  - : `string`，匹配 URL 的主机名（不包括协议或端口 — 请参见`schemes`和`ports`）包含给定字符串的情况。
```suggestion
  - : `string`，匹配 URL 的[主机名](/zh-CN/docs/Web/API/HTMLAnchorElement/hostname)（不包括协议或端口 — 请参见`schemes`和`ports`）包含给定字符串的情况。
```

2024-08-09 08:05 UTC, yin1999 commented
你对一下英文文档和中文文档在定义列表部分的样式，中文的有空心圆圈，麻烦在编写定义列表的时候注意一下缩进以及使用的符号。

2024-08-12 04:21 UTC, PassionPenguin commented
> 你对一下英文文档和中文文档在定义列表部分的样式，中文的有空心圆圈，麻烦在编写定义列表的时候注意一下缩进以及使用的符号。

喔，我瞅瞅

2024-08-30 05:33 UTC, PassionPenguin commented
> 你对一下英文文档和中文文档在定义列表部分的样式，中文的有空心圆圈，麻烦在编写定义列表的时候注意一下缩进以及使用的符号。

😭 不是很懂（找不出区别，看 https://developer.mozilla.org/zh-CN/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN#定义列表 也没找到有什么不同的，不好意思，麻烦你帮忙改一下吧）

2024-08-30 05:46 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/events/urlfilter/index.md
> +      - 例如：`urlMatches: "^[^:]*:(?://)?(?:[^/]*\\.)?mozilla\\.org/.*$"` 匹配 `https://mozilla.org/`，`https://developer.mozilla.org/`，但不匹配 `https://developer.fakemozilla.org/`。
```suggestion
- `pathContains` {{optional_inline}}
  - ：`string`，匹配 URL 的路径段是否包含指定的字符串。
- `pathEquals` {{optional_inline}}
  - ：`string`，匹配 URL 的路径是否等于指定的字符串。
- `pathPrefix` {{optional_inline}}
  - ：`string`，匹配 URL 的路径段是否以指定的字符串开头。
- `pathSuffix` {{optional_inline}}
  - ：`string`，匹配 URL 的路径段是否以指定的字符串结束。
- `queryContains` {{optional_inline}}
  - ：`string`，匹配 URL 的查询段是否包含指定的字符串。
- `queryEquals` {{optional_inline}}
  - ：`string`，匹配 URL 的查询段是否等于指定的字符串。
- `queryPrefix` {{optional_inline}}
  - ：`string`，匹配 URL 的查询段是否以指定的字符串开头。
- `querySuffix` {{optional_inline}}
  - ：`string`，匹配 URL 的查询段是否以指定的字符串结束。
- `urlContains` {{optional_inline}}
  - ：`string`，匹配 URL（不含片段标识符）是否包含指定字符串。如果端口号与默认端口号一致，则会从 URL 中删除端口号。
- `urlEquals` {{optional_inline}}
  - ：`string`，匹配 URL（不含片段标识符）是否等于指定字符串。如果端口号与默认端口号一致，则会从 URL 中删除端口号。
- `urlMatches` {{optional_inline}}

  - : `string`，检查 URL（不含片段标识符）是否与指定的[正则表达式](/zh-CN/docs/Web/JavaScript/Guide/Regular_expressions)匹配。如果端口号与默认端口号一致，则会从 URL 中删除端口号。

    - 例如：`urlMatches: "^[^:]*:(?://)?(?:[^/]*\\.)?mozilla\\.org/.*$"` 匹配 `https://mozilla.org/`、`https://developer.mozilla.org/`，但不匹配 `https://developer.fakemozilla.org/`。
```

2024-08-30 06:30 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/events/urlfilter/index.md
> +      - 例如：`urlMatches: "^[^:]*:(?://)?(?:[^/]*\\.)?mozilla\\.org/.*$"` 匹配 `https://mozilla.org/`，`https://developer.mozilla.org/`，但不匹配 `https://developer.fakemozilla.org/`。
啊 不好意思 我在ide里面比较（复制粘贴英文的格式）竟然没发现 几次了 应该是ide的缩进设置有点问题

2024-08-31 02:07 UTC, yin1999 approved these changes

2024-08-31 02:07 UTC, merged