change " -> ' in javascript
mdn/translated-content pull request #2308
Opened 2021-09-03 07:23 UTC by somutoru

2021-09-03 15:06 UTC, mfuji09 requested changes

2021-09-03 15:06 UTC, mfuji09 commented on files/ja/web/api/document/visibilitychange_event/index.html
> -<pre class="brush:js notranslate">document.addEventListener("visibilitychange", function() {
英語版の原文は二重引用符になっています。
このページは英語版の翻訳版なので、この部分を修正する必要があると思われるのであれば、まず英語版に修正依頼を出し、反映されてから日本語版への修正を出すようお願いいたします。

2021-09-07 05:32 UTC, somutoru commented on files/ja/web/api/document/visibilitychange_event/index.html
> -<pre class="brush:js notranslate">document.addEventListener("visibilitychange", function() {
了解しました。お手数かけまして申し訳ないです。

2022-08-10 07:31 UTC, mfuji09 commented
いったんクローズとさせていただきます。

2022-08-10 07:31 UTC, closed without merging