[zh-cn]: update the translation of Date `setUTCHours()` method
mdn/translated-content pull request #23114
Opened 2024-08-17 02:59 UTC by T34-active

### Description
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setUTCHours
### Related issues and pull requests
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/setutchours/index.md
* Last commit: https://github.com/mdn/content/commit/fb85334ffa4a2c88d209b1074909bee0e0abd57a

2024-08-17 03:04 UTC, T34-active commented on files/zh-cn/web/javascript/reference/global_objects/date/setutchours/index.md
> +**`setUTCHours()`** 方法是 {{jsxref("Date")}} 实例的方法，它根据世界标准时间更改该日期的小时、分钟、秒或毫秒。
```suggestion
{{jsxref("Date")}} 实例的 **`setUTCHours()`** 方法根据世界协调时（UTC）更改该日期的小时、分钟、秒或毫秒。
```

2024-08-17 13:23 UTC, yin1999 requested changes

2024-08-17 13:23 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/date/setutchours/index.md
> +{{jsxref("Date")}} 实例的 **`setUTCHours()`** 方法根据世界协调时（UTC）更改该日期的小时、分钟、秒或毫秒。
未同步翻译

2024-08-19 02:13 UTC, T34-active commented on files/zh-cn/web/javascript/reference/global_objects/date/setutchours/index.md
> +{{jsxref("Date")}} 实例的 **`setUTCHours()`** 方法根据世界协调时（UTC）更改该日期的小时、分钟、秒或毫秒。
```suggestion
{{jsxref("Date")}} 方法是 **`setUTCHours()`** 实例的方法，用于根据世界协调时（UTC）更改日期对象的小时、分钟、秒或毫秒。
```

2024-08-19 02:38 UTC, yin1999 requested changes
劳烦对一下，特别是我明确指出后修改的第一句的翻译，还是有点错误

2024-08-19 02:38 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/date/setutchours/index.md
> +{{jsxref("Date")}} 方法是 **`setUTCHours()`** 实例的方法，用于根据世界协调时（UTC）更改日期对象的小时、分钟、秒或毫秒。
```suggestion
{{jsxref("Date")}} 实例的 **`setUTCHours()`** 方法用于根据世界协调时更改日期对象的小时、分钟、秒或毫秒。
```

2024-08-19 02:38 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/date/setutchours/index.md
> +  - 如果指定了 `msValue`，则必须同时指定 `minutesValue` 和 `secondsValue`。
```suggestion
  - : 0 到 999 之间的整数，表示毫秒数。如果指定了 `msValue`，则必须同时指定 `minutesValue` 和 `secondsValue`。
```

2024-08-19 02:38 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/date/setutchours/index.md
> +如果参数为 `NaN`（或其他会被[强制转换](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Number#number_强制转换)为 `NaN`，例如 `undefined`），则日期会被设置为[无效日期](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date#时代_时间戳和无
```suggestion
该方法会原地修改 {{jsxref("Date")}} 对象，并返回其新的[时间戳](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date#纪元、时间戳和无效日期)。如果参数为 `NaN`（或其他会被[强制转换](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Number#number_强制转换)为 `NaN` 的值，例如 `undefined`），则日期会被设置为[无效日期](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date#纪元、时间戳和无效日期)，并返回 `NaN`。
```

2024-08-20 11:38 UTC, yin1999 approved these changes

2024-08-20 11:38 UTC, merged