zh-CN: create Glossary/CLS
mdn/translated-content pull request #23352
Opened 2024-09-01 12:10 UTC by PassionPenguin

2024-09-01 13:36 UTC, yin1999 requested changes
中文之间不应添加空格

2024-09-03 01:57 UTC, yin1999 commented on files/zh-cn/glossary/cls/index.md
> +**累计布局偏移（CLS）**是一种由 Google 设计为[核心 Web 要素](https://web.dev/explore/learn-core-web-vitals)其中之一的网站的可用性指标。
![image](https://github.com/user-attachments/assets/6190c982-6f06-42c6-8f4c-4f68320a89df)

```suggestion
**累计布局偏移**（CLS）是一种由 Google 设计为[核心 Web 要素](https://web.dev/explore/learn-core-web-vitals)之一的网站的可用性指标。
```

2024-09-03 01:57 UTC, yin1999 commented on files/zh-cn/glossary/cls/index.md
> +{{domxref("LayoutShift")}} 接口是 [性能 API](/zh-CN/docs/Web/API/Performance_API) 的一部分，可用于测量单个布局偏移，然后用于计算网页的 CLS 分数。
```suggestion
{{domxref("LayoutShift")}} 接口（属于[性能 API](/zh-CN/docs/Web/API/Performance_API)）可用于测量单个布局偏移，然后用于计算网页的 CLS 分数。
```

2024-09-03 05:30 UTC, PassionPenguin commented on files/zh-cn/glossary/cls/index.md
> +**累计布局偏移（CLS）**是一种由 Google 设计为[核心 Web 要素](https://web.dev/explore/learn-core-web-vitals)其中之一的网站的可用性指标。
oops

2024-09-03 06:04 UTC, yin1999 approved these changes
:+1:

2024-09-03 06:04 UTC, merged