update contexts md how does the internet work in Korean
mdn/translated-content pull request #23367
Opened 2024-09-03 04:38 UTC by nextlife-dev

### Description

I found it has no text on "intranets and extranets" so I update it addition into korean

### Motivation

Intranets and Extranets are good contexts.

2024-09-04 10:25 UTC, 1ilsang requested changes
@nextlife-dev 님 안녕하세요. 기여해주셔서 감사합니다! 💯

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

질문이나 도움이 필요하시다면 언제든 멘션 부탁드리겠습니다.

2024-09-04 10:25 UTC, 1ilsang commented on files/ko/learn/common_questions/web_mechanics/how_does_the_internet_work/index.md
> +![Graphical Representation of how Extranet and Intranet work](internet-schema-8.png)
```suggestion
![엑스트라넷과 인트라넷의 작동 방식을 그래픽으로 표현합니다](internet-schema-8.png)
```

alt 내용도 번역 부탁드리겠습니다

2024-09-04 10:25 UTC, 1ilsang commented on files/ko/learn/common_questions/web_mechanics/how_does_the_internet_work/index.md
> +인트라넷은 특정 조직의 구성원들만 접근할 수 있는 사설 네트워크입니다. 이는 주로 구성원들이 공유 리소스에 안전하게 접근하고, 협업하며 소통할 수 있는 포털을 제공하는 데 사용됩니다. 예를 들어, 조직의 인트라넷은 부서나 팀 정보를 공유하는 웹 페이지, 주요 문서와 파일을 관리하는 공유 드라이브, 업무 관리 작업을 수행하는 포털, 위키, 토론 게시판, 메
```suggestion
인트라넷은 특정 조직의 구성원들만 접근할 수 있는 사설 네트워크입니다.
이는 주로 구성원들이 공유 리소스에 안전하게 접근하고, 협업하며 소통할 수 있는 포털을 제공하는 데 사용됩니다.
예를 들어, 조직의 인트라넷은 부서나 팀 정보를 공유하는 웹 페이지, 주요 문서와 파일을 관리하는 공유 드라이브,
업무 관리 작업을 수행하는 포털, 위키, 토론 게시판, 메시징 시스템과 같은 협업 도구를 호스팅할 수 있습니다.
```

줄 수는 원문과 동일하게 해주세요. 관련 논의는 [여기](https://github.com/orgs/mdn/discussions/655#discussioncomment-9251708)에서 확인할 수 있습니다.

2024-09-04 10:25 UTC, 1ilsang commented on files/ko/learn/common_questions/web_mechanics/how_does_the_internet_work/index.md
> +엑스트라넷은 인트라넷과 매우 유사하지만, 다른 조직과의 공유와 협업을 위해 사설 네트워크의 전체 또는 일부를 개방한다는 점이 다릅니다. 이는 일반적으로 기업과 긴밀히 협력하는 고객 및 이해관계자들과 안전하고 보안성 있게 정보를 공유하는 데 사용됩니다. 그 기능은 인트라넷이 제공하는 것과 유사합니다.
```suggestion
엑스트라넷은 인트라넷과 매우 유사하지만, 다른 조직과의 공유와 협업을 위해 사설 네트워크의 전체 또는 일부를 개방한다는 점이 다릅니다.
이는 일반적으로 기업과 긴밀히 협력하는 고객 및 이해관계자들과 안전하고 보안성 있게 정보를 공유하는 데 사용됩니다.
정보 및 파일 공유, 협업 도구, 토론 게시판 등 인트라넷이 제공하는 기능과 유사한 기능을 제공합니다.
```

1. 줄 수는 원문과 동일하게 해주세요. 관련 논의는 [여기](https://github.com/orgs/mdn/discussions/655#discussioncomment-9251708)에서 확인할 수 있습니다.
2. 원문의 내용이 빠진 것 같아요(`information and file sharing, collaboration tools, discussion boards, etc.`)

2024-09-04 10:25 UTC, 1ilsang commented on files/ko/learn/common_questions/web_mechanics/how_does_the_internet_work/index.md
> +인트라넷과 엑스트라넷 모두 인터넷과 동일한 종류의 인프라에서 실행되며 같은 프로토콜을 사용합니다. 따라서 권한을 부여받은 구성원들은 서로 다른 물리적 위치에서도 접근할 수 있습니다.
```suggestion
인트라넷과 엑스트라넷 모두 인터넷과 동일한 종류의 인프라에서 실행되며 같은 프로토콜을 사용합니다.
따라서 권한을 부여받은 구성원들은 서로 다른 물리적 위치에서도 접근할 수 있습니다.
```

줄 수는 원문과 동일하게 해주세요. 관련 논의는 [여기](https://github.com/orgs/mdn/discussions/655#discussioncomment-9251708)에서 확인할 수 있습니다.

2024-09-04 10:37 UTC, nextlife-dev commented on files/ko/learn/common_questions/web_mechanics/how_does_the_internet_work/index.md
> +엑스트라넷은 인트라넷과 매우 유사하지만, 다른 조직과의 공유와 협업을 위해 사설 네트워크의 전체 또는 일부를 개방한다는 점이 다릅니다. 이는 일반적으로 기업과 긴밀히 협력하는 고객 및 이해관계자들과 안전하고 보안성 있게 정보를 공유하는 데 사용됩니다. 그 기능은 인트라넷이 제공하는 것과 유사합니다.
그렇군요. 이 부분이 빠졌군요. 사실 번역하면서 '위의 글을 다시 볼 수 있는데, 중복해서 쓸 필요가 있을까?' 생각했는데, 원문과 다르게 쓰면 혼동이 있을 수 있겠습니다. 반성합니다.

2024-09-04 10:43 UTC, nextlife-dev reviewed
수정 필요한 사항이 없습니다. 확인해주셔서 감사합니다!

2024-09-08 08:21 UTC, 1ilsang approved these changes
LGTM 고생하셨습니다

2024-09-08 08:25 UTC, merged