[zh-cn]: create docs for HTMLTableSectionElement
mdn/translated-content pull request #23377
Opened 2024-09-04 11:31 UTC by fuchunhui

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-09-04 12:08 UTC, fuchunhui commented
https://github.com/mdn/translated-content/pull/23379

2024-09-06 03:35 UTC, yin1999 requested changes
请考虑以下列出的注释：

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/index.md
> +**`HTMLTableSectionElement`** 接口提供用于操作 HTML 表格部分（即 {{HTMLElement("thead")}}、{{HTMLElement("tfoot")}} 和 {{HTMLElement("tbody")}}）布局和呈现的特定属性和方法（除了常规 {{domxref("HTMLElement")}} 接口之外，它还可以通过继承来使用）。
这段的翻译还得再改改（现在和英文文档的内容是对不上的）

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/index.md
> +  - : 一个包含枚举值反映 [`align`](/zh-CN/docs/Web/HTML/Element/tr#align) 属性的字符串，其指示元素内容相对于周围上下文的对齐方式，可能的值有：`"left"`、`"right"` 和 `"center"`。
```suggestion
  - : 一个反映 [`align`](/zh-CN/docs/Web/HTML/Element/tr#align) 属性的字符串枚举值。其指示元素内容相对于周围上下文的对齐方式，可能的值有：`"left"`、`"right"` 和 `"center"`。
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/index.md
> +  - : 返回包含 section 中行的实时 {{domxref("HTMLCollection")}}，此 `HTMLCollection` 是实时的，且当行添加或删除时自动更新。
```suggestion
  - : 返回包含 section 中行的动态 {{domxref("HTMLCollection")}}。`HTMLCollection` 是动态的，当添加或删除行时会自动更新。
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/index.md
> +  - : 一个包含单字符的字符串。这个字符是用来对齐某一列所有单元格内容的基准。它反映 [`char`](/zh-CN/docs/Web/HTML/Element/tr#char) 并默认为与语言相关的小数点，例如，英语的默认值是`“.”`，法语的默认值为`“,”`。此属性是可选的，且支持度不是很好。
```suggestion
  - : 一个包含单字符的字符串。这个字符是用来对齐某一列所有单元格内容的基准。它反映 [`char`](/zh-CN/docs/Web/HTML/Element/tr#char) 并默认为与语言相关的小数点，例如，英语的默认值为 `'.'`，法语的默认值为 `','`。此属性是可选的，而且没有得到很好的支持。
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/index.md
> +  - : 一个包含整数的字符串，表示由 `HTMLTableRowElement.ch` 定义的字符的右侧（对于从左到右的脚本；或者对于从右到左的脚本在左侧）必须保留多少个字符。此属性是可选的，并没有得到很好的支持。
```suggestion
  - : 一个包含整数的字符串，表示由 `HTMLTableRowElement.ch` 定义的字符的右侧（对于从左到右的文本；或者对于从右到左的文本的左侧）必须保留多少个字符。此属性是可选的，并没有得到很好的支持。
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/index.md
> +  - : 一个表示枚举值的字符串，指示单元格内容必须如何对齐。它反映 [`valign`](/zh-CN/docs/Web/HTML/Element/tr#valign) 属性，且可以具有以下值之一：`“top”`、`“middle”`、`“bottom”` 或 `“baseline”`。
```suggestion
  - : 一个表示枚举值的字符串，指示单元格内容必须如何对齐。它反映 [`valign`](/zh-CN/docs/Web/HTML/Element/tr#valign) 属性，可以为以下值之一：`"top"`、`"middle"`、`"bottom"` 或 `"baseline"`。
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/index.md
> +  - : 返回一个表示 section 新行的 {{DOMxRef("HTMLTableRowElement")}}。它将其插入到位于给定的 `index` 位置的 {{HTMLElement("tr")}} 元素行集合中。如果 `index` 是 `-1`，则新行附加到集合中，如果 `index` 小于 `-1` 或大于集合的行数，则引发值为 `IndexSizeError` 的 {{DOM
```suggestion
  - : 返回一个表示 section 新行的 {{DOMxRef("HTMLTableRowElement")}}。它将其插入到行集合中给定索引（`index`）位置的 {{HTMLElement("tr")}} 元素之前。如果 `index` 是 `-1`，则新行添加到集合末尾，如果 `index` 小于 `-1` 或大于集合的行数，则引发值为 `IndexSizeError` 的 {{DOMxRef("DOMException")}}。
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/insertrow/index.md
> +{{domxref("HTMLTableSectionElement")}} 接口的 **`insertRow()`** 方法在给定的表格元素（{{HTMLElement("thead")}}、{{HTMLElement("tfoot")}} 或{{HTMLElement("tbody")}}）插入一个新行（{{HtmlElement("tr")}}），然后返回新行的引用。
```suggestion
{{domxref("HTMLTableSectionElement")}} 接口的 **`insertRow()`** 方法在给定的表格分段元素（{{HTMLElement("thead")}}、{{HTMLElement("tfoot")}} 或 {{HTMLElement("tbody")}}）插入一个新行（{{HtmlElement("tr")}}），然后返回新行的引用。
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/valign/index.md
> +可能的值有：`“top”`、`“middle”`、`“bottom”` 或 `“baseline”`。
```suggestion
可能的值有：`"top"`、`"middle"`、`"bottom"` 或 `"baseline"`。
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/rows/index.md
> +### Result
```suggestion
### 结果
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/insertrow/index.md
> +> [!NOTE] > `insertRow()` 将行直接插入到 section 中，该行不需要像使用 {{domxref("Document.createElement()")}} 创建新的 `<tr>` 元素那样单独追加。
特殊情况，参见：https://github.com/mdn/translated-content/pull/23300/files#diff-e1b7a58f6d81113667cb5e12ecc34be4858a39ccbde934d39b16dcee39093568R93

```suggestion
> **备注：** `insertRow()` 将行直接插入到分段（section）中，该行不需要像使用 {{domxref("Document.createElement()")}} 创建新的 `<tr>` 元素那样单独追加。
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/insertrow/index.md
> +  - : 新行的行索引，如果 `index` 是 `-1` 或者等于行数，新行附加到最后一行。如果省略 `index`，则默认值是 `-1`。
```suggestion
  - : 新行的行索引，如果 `index` 是 `-1` 或者等于行数，新行作为最后一行附加。如果省略 `index`，则默认值是 `-1`。
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/insertrow/index.md
> +  - : 如果 `index` 大于行数或小于 `-1`，则抛出异常。
```suggestion
  - : 如果 `index` 大于行数或小于 `-1`，则抛出此异常。
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/insertrow/index.md
> +在这个示例中，有两个按钮允许你从表格主体添加和移除行，它还使用表中当前行数更新 {{HTMLElement("output")}} 元素。
我们一般不会说“从 xx 添加”

```suggestion
在这个示例中，有两个按钮允许你对表格主体添加和移除行，它还使用表中当前行数更新 {{HTMLElement("output")}} 元素。
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/insertrow/index.md
> +const rows = bodySection.rows; // 集合是实时的，因此其总是最新的
```suggestion
const rows = bodySection.rows; // 集合是动态的，因此其总是最新的
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/insertrow/index.md
> +### Result
```suggestion
### 结果
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/rows/index.md
> +{{domxref("HTMLTableSectionElement")}} 接口的 **`rows`** 只读属性返回一个包含 section 中行属性的实时 {{domxref("HTMLCollection")}}。此 `HTMLCollection` 是实时的，且当行添加或移除时自动更新。
```suggestion
{{domxref("HTMLTableSectionElement")}} 接口的 **`rows`** 只读属性返回一个包含当前分段中行属性的动态 {{domxref("HTMLCollection")}}。此 `HTMLCollection` 是动态的，并在添加或移除行时自动更新。
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/rows/index.md
> +一个实时 {{domxref("HTMLTableRowElement")}} 的 {{domxref("HTMLCollection")}} 对象。
```suggestion
一个动态 {{domxref("HTMLTableRowElement")}} 的 {{domxref("HTMLCollection")}} 对象。
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/rows/index.md
> +在这个示例中，有两个按钮允许你从表格主体添加和移除行，它还使用表中当前行数更新 {{HTMLElement("output")}} 元素。
```suggestion
在这个示例中，有两个按钮允许你对表格主体添加和移除行，它还使用表中当前行数更新 {{HTMLElement("output")}} 元素。
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/rows/index.md
> +const rows = bodySection.rows; // 集合是实时的，因此其总是最新的
```suggestion
const rows = bodySection.rows; // 集合是动态的，因此其总是最新的
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/valign/index.md
> +{{domxref("HTMLTableSectionElement")}} 接口的 **`vAlign`** 属性是一个指示如何在 {{htmlelement("thead")}}、{{htmlelement("tbody")}} 或 {{htmlelement("tfoot")}} 表格部分垂直对齐文本字符串，单个行和单元格可以覆盖它。
```suggestion
{{domxref("HTMLTableSectionElement")}} 接口的 **`vAlign`** 属性是一个指示如何在 {{htmlelement("thead")}}、{{htmlelement("tbody")}} 或 {{htmlelement("tfoot")}} 表格部分垂直对齐文本的字符串，单个行和单元格可以覆盖它。
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/valign/index.md
> +> 此属性已废弃，使用 CSS 在单元格中水平对齐文本。使用 CSS {{cssxref("vertical-align")}} 属性垂直对齐单元格中文本。
```suggestion
> 此属性已弃用。请使用 CSS {{cssxref("vertical-align")}} 属性来垂直对齐分段单元格中的文本。
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/valign/index.md
> +  - : 将文本与单元格顶部对齐，使用 `vertical-align: top` 代替。
```suggestion
  - : 将文本与单元格顶部对齐。使用 `vertical-align: top` 代替。
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/valign/index.md
> +  - : 将文本与单元格底部对齐，使用 `vertical-align:  bottom` 代替。
```suggestion
  - : 将文本与单元格底部对齐。使用 `vertical-align:  bottom` 代替。
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/valign/index.md
> +  - : 与 `top` 相似，但将文本的基线对齐到最靠近顶部，这样字符的任何部分都不会超出单元格。
```suggestion
  - : 与 `top` 相似，但使文本的基线贴近顶部，这样字符的任何部分都不会超出单元格。
```

2024-09-06 03:35 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/valign/index.md
> +使用 CSS {{cssxref("vertical-align")}} 替代，它具有优先权，如[垂直对齐表格单元格](/zh-CN/docs/Web/CSS/vertical-align#vertical_alignment_in_a_table_cell)示例所示。
```suggestion
使用 CSS {{cssxref("vertical-align")}} 替代，它的优先级更高，如[垂直对齐表格单元格](/zh-CN/docs/Web/CSS/vertical-align#vertical_alignment_in_a_table_cell)示例所示。
```

2024-09-12 08:26 UTC, yin1999 approved these changes
Thank you @fuchunhui

2024-09-12 08:26 UTC, yin1999 commented on files/zh-cn/web/api/htmltablesectionelement/index.md
> +**`HTMLTableSectionElement`** 接口提供特定的属性和方法（除了常规 {{domxref("HTMLElement")}} 接口之外，它还可以通过继承来使用），用于操作当前分段的布局和呈现，即 HTML 表格中的表头、表尾和主体部分（{{HTMLElement("thead")}}、{{HTMLElement("tfoot")}} 和 {{HTMLElement("tb
```suggestion
**`HTMLTableSectionElement`** 接口提供特定的属性和方法（除了常规 {{domxref("HTMLElement")}} 接口之外，它还可以通过继承来使用），用于操作当前分段——即 HTML 表格中的表头、表尾和主体部分（{{HTMLElement("thead")}}、{{HTMLElement("tfoot")}} 和 {{HTMLElement("tbody")}}）——的布局和呈现。
```

2024-09-12 08:28 UTC, merged