[zh-CN]: update translation for Broadcast Channel API - part II
mdn/translated-content pull request #23375
Opened 2024-09-04 06:24 UTC by skyclouds2001

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-09-04 06:27 UTC, skyclouds2001 commented on files/zh-cn/web/api/broadcastchannel/postmessage/index.md
> +  - : 要发送到其他窗口的数据。数据使用[结构化克隆算法](/zh-CN/docs/Web/API/Web_Workers_API/Structured_clone_algorithm)进行序列化。这意味着您可以将各种数据对象安全地传递到目标窗口，而无需自己对其进行序列化。
```suggestion
  - : 要发送到其他窗口的数据。数据使用[结构化克隆算法](/zh-CN/docs/Web/API/Web_Workers_API/Structured_clone_algorithm)进行序列化。这意味着你可以将各种数据对象安全地传递到目标窗口，而无需自己对其进行序列化。
```

2024-09-04 10:23 UTC, skyclouds2001 commented on files/zh-cn/web/api/broadcastchannel/close/index.md
>  slug: Web/API/BroadcastChannel/close
```suggestion
title: BroadcastChannel：close() 方法
slug: Web/API/BroadcastChannel/close
l10n:
  sourceCommit: 50a45d52fd9f45f1ca30b546af5920d0ccda82dc
```

2024-09-04 10:24 UTC, skyclouds2001 commented on files/zh-cn/web/api/broadcastchannel/message_event/index.md
>  slug: Web/API/BroadcastChannel/message_event
```suggestion
slug: Web/API/BroadcastChannel/message_event
l10n:
  sourceCommit: 50a45d52fd9f45f1ca30b546af5920d0ccda82dc
```

2024-09-04 10:25 UTC, skyclouds2001 commented on files/zh-cn/web/api/broadcastchannel/messageerror_event/index.md
>  slug: Web/API/BroadcastChannel/messageerror_event
```suggestion
title: BroadcastChannel：messageerror 事件
slug: Web/API/BroadcastChannel/messageerror_event
l10n:
  sourceCommit: 50a45d52fd9f45f1ca30b546af5920d0ccda82dc
```

2024-09-04 10:25 UTC, skyclouds2001 commented on files/zh-cn/web/api/broadcastchannel/postmessage/index.md
>  slug: Web/API/BroadcastChannel/postMessage
```suggestion
title: BroadcastChannel：postMessage() 方法
slug: Web/API/BroadcastChannel/postMessage
l10n:
  sourceCommit: 50a45d52fd9f45f1ca30b546af5920d0ccda82dc
```

2024-09-10 08:26 UTC, jasonren0403 requested changes
需要留意下该接口下 channel 一词的翻译

2024-09-10 08:26 UTC, jasonren0403 commented on files/zh-cn/web/api/broadcastchannel/close/index.md
>  // 连接到指定频道
频道还是通道（L10），要统一下

2024-09-10 08:26 UTC, jasonren0403 commented on files/zh-cn/web/api/broadcastchannel/messageerror_event/index.md
> +相同，但使用 `onmessage` 和 `onmessageerror` 事件处理器属性：
```suggestion
下述代码也实现了相同需求，但使用 `onmessage` 和 `onmessageerror` 事件处理器属性：
```

2024-09-10 11:47 UTC, skyclouds2001 commented on files/zh-cn/web/api/broadcastchannel/close/index.md
> +{{domxref("BroadcastChannel")}} 接口的 **`close()`** 方法终止与底层通道的连接，从而允许对对象进行垃圾回收。这是必须执行的步骤，因为浏览器没有其他方法可以知道不再需要此通道。
```suggestion
{{domxref("BroadcastChannel")}} 接口的 **`close()`** 方法终止与底层频道的连接，从而允许对对象进行垃圾回收。这是必须执行的步骤，因为浏览器没有其他方法可以知道不再需要此频道。
```

2024-09-10 11:47 UTC, skyclouds2001 commented on files/zh-cn/web/api/broadcastchannel/messageerror_event/index.md
> +{{domxref("BroadcastChannel")}} 接口的 **`messageerror`** 事件在无法反序列化的消息到达通道时触发。
```suggestion
{{domxref("BroadcastChannel")}} 接口的 **`messageerror`** 事件在无法反序列化的消息到达频道时触发。
```

2024-09-18 07:35 UTC, jasonren0403 approved these changes

2024-09-18 07:36 UTC, merged