zh-cn: update the translation of the 'MathML'
mdn/translated-content pull request #23521
Opened 2024-09-12 11:20 UTC by familyboat

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-09-15 03:32 UTC, yin1999 requested changes

2024-09-15 03:32 UTC, yin1999 commented on files/zh-cn/learn/mathml/index.md
> +对数学符号和 [TeX](https://zh.wikipedia.org/wiki/TeX) 渲染规则的熟悉也可能会有所帮助，尽管所需的概念将在需要时进行解释。
中文就应使用原来的语序，请思考一下中文的语法和习惯。

2024-09-15 03:32 UTC, yin1999 commented on files/zh-cn/learn/mathml/index.md
> +  - : MathML 是用于在网页中编写数学公式的标记语言。这个模块为你提供了如何开始使用 MathML 的基础知识，包括它的工作原理、语法是什么样的，以及如何在 HTML 中开始使用它。
我不确定你的想法，是要尽量接近原文呢，还是意译。因为前面的翻译都有点更接近原文的表述，但这句又变成意译了。

注意：“with the basics of xxxx”，是跟后文的，你的翻译中，“开始使用 xxx 的基础知识”又和最后一句有点重复。我感觉这段话的翻译完全可以不改。

2024-09-15 03:32 UTC, yin1999 commented on files/zh-cn/learn/mathml/index.md
> +  - : 这是 MDN 上 MathML 文档的主要入口，你将在这里找到 MathML 语言所有特性的详细参考文档。想知道一个属性可以取的所有值吗？这是一个好去处。
最后的问句我觉得原文也是可以的，改了就算了，没关系

2024-09-15 04:55 UTC, familyboat commented on files/zh-cn/learn/mathml/index.md
> +  - : 这是 MDN 上 MathML 文档的主要入口，你将在这里找到 MathML 语言所有特性的详细参考文档。想知道一个属性可以取的所有值吗？这是一个好去处。
因为其他文章中，也有这样的表达，是为了保持一致，才这样修改的。

2024-09-15 05:15 UTC, familyboat commented
阅读了之前的翻译，和现在修改的翻译，大体上还是不做改动了。仅对一些链接的标题做一些修改（保持和其他文章中对应的标题是一致的）

2024-09-17 14:40 UTC, yin1999 approved these changes

2024-09-17 14:41 UTC, merged