zh-CN: create `extension `
mdn/translated-content pull request #23533
Opened 2024-09-13 13:24 UTC by PassionPenguin

2024-09-13 13:32 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/extension/index.md
> +  - : 对于在隐身模式标签中运行的内容脚本，以及在隐身模式进程中运行的扩展页面返回 `True`。（仅适用于具有“`split`” `incognito_behavior` 取值的扩展。）
```suggestion
  - : 对于在隐身模式标签中运行的内容脚本，以及在隐身模式进程中运行的扩展页面返回 `true`。（仅适用于具有 `incognito_behavior` 取值为“`split`”的扩展。）
```

2024-09-13 13:32 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/extension/index.md
> +  - : 对于在隐身模式标签中运行的内容脚本，以及在隐身模式进程中运行的扩展页面返回 `true`。（仅适用于具有 `incognito_behavior` 取值为“`split`”的扩展。）
这个原文的 `True`？（or `true` 更合适一点lol）

2024-09-24 02:30 UTC, jasonren0403 requested changes
一些问题

2024-09-24 02:30 UTC, jasonren0403 commented on files/zh-cn/mozilla/add-ons/webextensions/api/extension/index.md
> +> **备注：** **该模块中的消息 API 被弃用**，取而代之为在 [`runtime`](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/API/runtime) 模块中的等价 API。
```suggestion
> **备注：** **该模块中的消息 API 被弃用**，取而代之的是 [`runtime`](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/API/runtime) 模块中相应的 API。
```

2024-09-24 02:30 UTC, jasonren0403 commented on files/zh-cn/mozilla/add-ons/webextensions/api/extension/index.md
> +  - : 返回当前扩展内运行的背景页面的 [`Window`](/zh-CN/docs/Web/API/Window) 对象。如果背景脚本不在运行，则返回 [`null`](/zh-CN/docs/Web/JavaScript/Reference/Operators/null)。
background → 后台 更合适些？

2024-09-24 02:30 UTC, jasonren0403 commented on files/zh-cn/mozilla/add-ons/webextensions/api/extension/index.md
> +  - : 返回当前扩展内运行的背景页面的 [`Window`](/zh-CN/docs/Web/API/Window) 对象。如果背景脚本不在运行，则返回 [`null`](/zh-CN/docs/Web/JavaScript/Reference/Operators/null)。
```suggestion
  - : 返回当前扩展内运行的后台页面的 [`Window`](/zh-CN/docs/Web/API/Window) 对象。如果扩展不存在后台页面，则返回 [`null`](/zh-CN/docs/Web/JavaScript/Reference/Operators/null)。
```

2024-09-24 02:30 UTC, jasonren0403 commented on files/zh-cn/mozilla/add-ons/webextensions/api/extension/index.md
> +  - : 返回当前扩展内运行的每个标签的 JavaScript [`Window`](/zh-CN/docs/Web/API/Window) 对象的数组。如果指定了 `windowId`，则仅返回附加到指定窗口的标签的 Window 对象。
原文没有提及后半句话吧

2024-09-27 23:50 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/extension/index.md
> +  - : 返回当前扩展内运行的每个标签的 JavaScript [`Window`](/zh-CN/docs/Web/API/Window) 对象的数组。如果指定了 `windowId`，则仅返回附加到指定窗口的标签的 Window 对象。
不好意思😬

2024-09-30 01:16 UTC, jasonren0403 approved these changes
👍

2024-09-30 01:16 UTC, merged