zh-CN: create `extension.sendRequest() `
mdn/translated-content pull request #23535
Opened 2024-09-13 13:25 UTC by PassionPenguin

2024-09-18 07:41 UTC, yin1999 requested changes

2024-10-01 09:05 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/extension/sendrequest/index.md
> +该函数也可以通过[将会返回一个 Promise](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/API#callbacks_and_promises) 的 `browser.extension.sendRequest()` 方法来使用。
```suggestion
该 API 同样以将会返回一个 Promise 的方法 的 `browser.extension.sendRequest()` 的形式可用。
```

2024-10-01 09:05 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/extension/sendrequest/index.md
> +  - : `string`，你的插件希望连接到的插件的扩展 ID。如果省略，则默认为你自己的插件。
```suggestion
  - : `string`，你所希望连接到的拓展的 ID。如果省略，则默认为你自己的拓展。
```

2024-10-01 09:11 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/extension/sendrequest/index.md
> +该函数也可以通过[将会返回一个 Promise](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/API#callbacks_and_promises) 的 `browser.extension.sendRequest()` 方法来使用。
mdn/content#36144

2024-10-07 02:13 UTC, yin1999 approved these changes

2024-10-07 02:16 UTC, merged