zh-CN: create `extensionTypes`
mdn/translated-content pull request #23547
Opened 2024-09-13 13:44 UTC by PassionPenguin

2024-09-14 02:27 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/extensiontypes/index.md
> +  - : 最早将 JavaScript、CSS 插入到标签页中的时间点。
https://developer.chrome.com/docs/extensions/reference/api/extensionTypes?hl=zh-cn#type-RunAt

```suggestion
  - : 尽快将 JavaScript、CSS 插入到标签页中的时间点。
```

2024-09-14 02:27 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/extensiontypes/index.md
> +  sourceCommit: a16fecbf75f71fc11e03ef6cd0b0c34ad6f3d480
```suggestion
  sourceCommit: b8a0743ca8b1e1b1b1a95cc93a4413c020f11262
```

2024-09-14 02:29 UTC, yin1999 requested changes

2024-09-14 02:29 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/extensiontypes/index.md
> +> 此 API 基于 Chromium 的 [`chrome.extensionTypes`](https://developer.chrome.com/docs/extensions/reference/extensionTypes) API。该文档衍生自 Chromium 代码中的 [`extension_types.json`](https://chromium.googlesource.
注意一下其他的几个 PR，应该也有这个问题

```suggestion
> 此 API 基于 Chromium 的 [`chrome.extensionTypes`](https://developer.chrome.com/docs/extensions/reference/api/extensionTypes) API。该文档衍生自 Chromium 代码中的 [`extension_types.json`](https://chromium.googlesource.com/chromium/src/+/master/extensions/common/api/extension_types.json)。
```

2024-09-17 08:06 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/extensiontypes/index.md
> +> 此 API 基于 Chromium 的 [`chrome.extensionTypes`](https://developer.chrome.com/docs/extensions/reference/extensionTypes) API。该文档衍生自 Chromium 代码中的 [`extension_types.json`](https://chromium.googlesource.
不好意思，https://github.com/mdn/content/commit/b8a0743ca8b1e1b1b1a95cc93a4413c020f11262，没有fetch到这一条

2024-09-17 08:08 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/extensiontypes/index.md
> +> 此 API 基于 Chromium 的 [`chrome.extensionTypes`](https://developer.chrome.com/docs/extensions/reference/extensionTypes) API。该文档衍生自 Chromium 代码中的 [`extension_types.json`](https://chromium.googlesource.
其他几个我晚上去一个个改：）

2024-09-17 08:39 UTC, yin1999 approved these changes

2024-09-17 08:39 UTC, merged