zh-cn: optimise the translation of some articles
mdn/translated-content pull request #23559
Opened 2024-09-14 08:32 UTC by familyboat

### Description

将`专题`改为`主题`，
将`安装基础软件`改为`安装基本软件`,
将`本文`，`本模块`改为`这篇文章`，`这个模块`，
对某些语句调整顺序，期望调整后更通顺。

### Motivation

### Additional details

### Related issues and pull requests

2024-09-15 03:13 UTC, yin1999 requested changes
有些内容是之前就修改过的，如果合理便不必要继续修改。请撤销它们

2024-09-15 05:22 UTC, familyboat commented
我的本意是想修改后能更好的表达原文的意思，现在看来实际的效果不是这样，我会撤销不必要的修改的。

2024-09-18 08:58 UTC, yin1999 commented on files/zh-cn/learn/css/index.md
> +在开始本主题之前，你还应该熟悉如何使用电脑，如何被动地使用 Web（例如，只是浏览和消费内容）。你应该按照[安装基本软件](/zh-CN/docs/Learn/Getting_started_with_the_web/Installing_basic_software)中的详细内容搭建基础工作环境，以及按照[处理文件](/zh-CN/docs/Learn/Getting_started_with
[中文文档的标题](https://developer.mozilla.org/zh-CN/docs/Learn/Getting_started_with_the_web/Installing_basic_software)

```suggestion
在开始本主题之前，你还应该熟悉如何使用电脑，如何被动地使用 Web（例如，只是浏览和消费内容）。你应该按照[安装基础软件](/zh-CN/docs/Learn/Getting_started_with_the_web/Installing_basic_software)中的详细内容搭建基础工作环境，以及按照[处理文件](/zh-CN/docs/Learn/Getting_started_with_the_web/Dealing_with_files)中的内容理解如何创建和管理文件——这两个都是 [Web 入门](/zh-CN/docs/Learn/Getting_started_with_the_web)纯新手模块的一部分。
```

2024-09-18 08:58 UTC, yin1999 commented on files/zh-cn/learn/forms/index.md
> +  - : 在某些情况下，出于样式或功能的原因，原生表单控件无法提供你所需的东西。在这种情况下，你会需要使用原生 HTML 构建表单控件。这篇文章通过一个案例研究说明你将如何做到这一点，以及在实际操作时需要注意的事项。
widget 翻译为“微件”、control 翻译为“控件”，虽然它们的意思在这里是一样的

```suggestion
  - : 在某些情况下，出于样式或功能的原因，原生表单微件无法提供你所需的东西。在这种情况下，你会需要使用原生 HTML 构建表单微件。这篇文章通过一个案例研究说明你将如何做到这一点，以及在实际操作时需要注意的事项。
```

2024-09-18 08:58 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/index.md
> +- [安装基本软件](/zh-CN/docs/Learn/Getting_started_with_the_web/Installing_basic_software)
```suggestion
- [安装基础软件](/zh-CN/docs/Learn/Getting_started_with_the_web/Installing_basic_software)
```

2024-09-19 00:02 UTC, yin1999 approved these changes
👍

2024-09-19 00:02 UTC, merged