[ko] api/htmlelement/tabindex 신규 번역
mdn/translated-content pull request #23600
Opened 2024-09-16 07:25 UTC by rosaceaee

안녕하세요. [tabindex](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/tabIndex) 페이지 신규 번역하였습니다.

2024-09-22 09:14 UTC, hochan222 approved these changes
@rosaceaee 님 안녕하세요.

몇가지 리뷰사항 하기엔 남겨두었습니다. 확인 부탁드립니다.

기여해주셔서 감사합니다. 좋은 하루 보내세요 :)

2024-09-22 09:14 UTC, hochan222 commented on files/ko/web/api/htmlelement/tabIndex/index.md
> +1. `tabIndex`가 정수인 요소인 경우.
```suggestion
1. `tabIndex`가 양수인 요소인 경우.
```

> Elements with a positive `tabIndex`.

2024-09-22 09:14 UTC, hochan222 commented on files/ko/web/api/htmlelement/tabIndex/index.md
> +   이 순서는 `tabIndex` 요소의 가장 낮은 값에서 가장 높은 값으로 진행됩니다.
```suggestion
   동일한 `tabIndex` 값을 가진 요소들은 나타나는 순서대로 탐색되어야 합니다. 
   탐색은 가장 낮은 `tabIndex`에서 가장 높은 `tabIndex`로 진행됩니다.
```

should be 와 Navigation의 의미가 더 잘 전달되도록 제안드립니다.
    
> Elements that have identical `tabIndex` values should be navigated in the order they appear.
> Navigation proceeds from the lowest `tabIndex` to the highest `tabIndex`.

2024-09-22 09:14 UTC, hochan222 commented on files/ko/web/api/htmlelement/tabIndex/index.md
> +2. `tabIndex` 속성을 지원하지 않거나 지원하지만 `tabIndex` 값이 `0`인 경우에는 순서대로 표시됩니다.
```suggestion
2. `tabIndex` 속성을 지원하지 않거나 지원하면서 `tabIndex`를 `0`으로 지정한 요소들은 나타나는 순서대로 탐색됩니다.
```

[제안]

2024-09-22 09:14 UTC, hochan222 commented on files/ko/web/api/htmlelement/tabIndex/index.md
> +disabled 속성을 가진 요소는 탭 순서에 들어가지 않습니다.
```suggestion
비활성화된 요소들은 탭 순서에 참여하지 않습니다.
```

markdown code 문법이 아니여서 번역해도 좋을듯합니다. disabled보다는 비활성화의 의미가 더 가까운듯하여 리뷰드렸습니다.

2024-09-22 09:14 UTC, hochan222 commented on files/ko/web/api/htmlelement/tabIndex/index.md
> +값이 순서대로 부여되지 않아도 되며 특정 값으로 시작되어도 됩니다. 음수인 경우라면 각 브라우저에서 매우 큰 값으로 정돈하여 나타냅니다.
```suggestion
값은 순차적일 필요가 없으며, 특정 값으로 시작할 필요도 없습니다. 값은 음수일 수도 있지만, 각 브라우저는 매우 큰 값을 잘라냅니다.
```
nor must를 고려한 번역 제안 드립니다!

> Values don't need to be sequential, nor must they begin with any particular value. They
may even be negative, though each browser trims very large values.

2024-09-22 09:14 UTC, hochan222 commented on files/ko/web/api/htmlelement/tabIndex/index.md
> +## 명세
```suggestion
## 명세서
```

[단어 안내서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md#section-title)에 따라 명세서로 수정 부탁드립니다!

2024-09-22 09:14 UTC, hochan222 requested changes
.

2024-09-28 10:09 UTC, rosaceaee commented
@hochan222 님 상세한 리뷰 감사합니다! 
리뷰해주신 내용 반영하여 커밋하였습니다!

2024-09-29 11:12 UTC, hochan222 approved these changes
고생 많으셨습니다~! 좋은 하루 보내세요 :)

2024-09-29 11:16 UTC, hochan222 requested changes
@rosaceaee 님 안녕하세요.

현재 `PR Test / tests (pull_request_target) Failing after 42s` git action이 실패하고 있습니다.

![image](https://github.com/user-attachments/assets/ef2e6048-717c-42a9-b4c1-b495a780e7c3)

현재 경로는 `files/ko/web/api/htmlelement/tabIndex/index.md`인데, `files/ko/web/api/htmlelement/tabindex/index.md` 경로가 올바른 경로라서 수정이 필요해보입니다. (tabIndex => tabindex)

2024-09-29 11:55 UTC, hochan222 approved these changes
상기 오류 제가 수정 후 반영했습니다. 좋은 하루 보내세요 :)

2024-09-29 11:55 UTC, merged

2024-09-30 08:30 UTC, rosaceaee commented
@hochan222  수정해주셔서 감사합니다!  제가 대소문자 구분하는걸 누락했네요 죄송합니다 ㅠㅠ