[zh-cn]: create the translation of `documentpictureinpictureevent`
mdn/translated-content pull request #23699
Opened 2024-09-20 00:30 UTC by tianyeeT

### Description

### Motivation

### Additional details

### Related issues and pull requests
part of #23557

2024-09-20 02:45 UTC, skyclouds2001 commented
Note this may be blocked by https://github.com/mdn/content/pull/35918

2024-09-20 03:20 UTC, skyclouds2001 commented on files/zh-cn/web/api/documentpictureinpictureevent/index.md
> +- [使用文档画中画 API](/zh-CN/docs/Web/API/Document_Picture-in-Picture_API/Using)
考虑到整体 API 名称都不翻译，这里也不翻译更合适？

2024-09-20 07:28 UTC, tianyeeT commented on files/zh-cn/web/api/documentpictureinpictureevent/index.md
> +- [使用文档画中画 API](/zh-CN/docs/Web/API/Document_Picture-in-Picture_API/Using)
```suggestion
- [使用 DocumentPictureInPictureEvent API](/zh-CN/docs/Web/API/Document_Picture-in-Picture_API/Using)
```

2024-09-23 12:31 UTC, yin1999 requested changes

2024-09-23 12:31 UTC, yin1999 commented on files/zh-cn/web/api/documentpictureinpictureevent/index.md
> +**`DocumentPictureInPictureEvent`** 接口是 {{domxref("Document Picture-in-Picture API", "Document Picture-in-Picture API", "", "nocode")}} 的事件对象，表示当画中画（Picture-in-Picture）窗口打开时触发的 {{domxref("DocumentPic
```suggestion
**`DocumentPictureInPictureEvent`** 接口是 {{domxref("Document Picture-in-Picture API", "Document Picture-in-Picture API", "", "nocode")}} 的 {{domxref("DocumentPictureInPicture/enter_event", "enter")}} 事件（会在画中画窗口打开时触发）的对象。
```

2024-09-23 12:31 UTC, yin1999 commented on files/zh-cn/web/api/documentpictureinpictureevent/index.md
> +_继承自其父类 {{DOMxRef("Event")}} 的方法。_
“方法继承自父接口”/“继承其父接口的方法”，这里就不应该加“自”字

```suggestion
_继承其父接口 {{DOMxRef("Event")}} 的方法。_
```

2024-09-23 12:31 UTC, yin1999 commented on files/zh-cn/web/api/documentpictureinpictureevent/index.md
> +_继承自其父类 {{DOMxRef("Event")}} 的属性。_
```suggestion
_继承其父接口 {{DOMxRef("Event")}} 的属性。_
```

2024-09-23 12:31 UTC, yin1999 commented on files/zh-cn/web/api/documentpictureinpictureevent/index.md
> +  - : 返回一个 {{domxref("Window")}} 实例，表示事件触发时的画中画窗口的浏览上下文。
```suggestion
  - : 返回一个 {{domxref("Window")}} 实例，表示触发事件的 `DocumentPictureInPicture` 窗口的浏览上下文。
```

2024-09-23 12:31 UTC, yin1999 commented on files/zh-cn/web/api/documentpictureinpictureevent/index.md
> +- [使用 DocumentPictureInPictureEvent API](/zh-CN/docs/Web/API/Document_Picture-in-Picture_API/Using)
麻烦对一下

```suggestion
- [使用 Document Picture-in-Picture API](/zh-CN/docs/Web/API/Document_Picture-in-Picture_API/Using)
```

2024-09-24 01:48 UTC, yin1999 approved these changes

2024-09-24 01:49 UTC, yin1999 approved these changes

2024-09-24 01:49 UTC, merged