[pt-br] Fix translation of using webstorage api and deprecated code being used without warning in "Learn/files/pt-BR/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API"
mdn/translated-content pull request #23733
Opened 2024-09-22 13:31 UTC by AlexandrinoMaranhao

### Description
Fixed the untranslated parts of this page (almost more than half of it) and a deprecated property used without warning

### Motivation
College subject assignment plus I really feel like helping. It helps readers as the page is more up-to-date in upstream

### Additional details

### Related issues and pull requests
"Fixes #18654 "

2024-09-23 00:35 UTC, nathipg requested changes
Por favor, veja meus comentários nesse PR: https://github.com/mdn/translated-content/pull/23653

2024-11-21 08:06 UTC, josielrocha approved these changes

2024-11-21 08:07 UTC, josielrocha requested changes
Poderia verificar os comentários da Nath, pfv. 🙏🏼

2026-09-14 00:09 UTC, nathipg commented
It been 2 years since changes were requested and the original page was updated since them, so I'm closing it
If you need guidence to make a contribution in the future, you can reach me out

2026-09-14 00:09 UTC, closed without merging