zh-cn: update the translation of the first three articles of the `Getting started with the web`
mdn/translated-content pull request #23742
Opened 2024-09-23 06:09 UTC by familyboat

### Description

对`web 入门`的前三篇文章的内容做一个更新。

### Motivation

### Additional details

### Related issues and pull requests

2024-09-23 06:36 UTC, yin1999 requested changes
请在翻译完成后对内容进行校对（未本地化的图片无需单独拷贝到本地化仓库中，也请一并移除）

2024-09-23 07:02 UTC, familyboat commented
> 请在翻译完成后对内容进行校对（未本地化的图片无需单独拷贝到本地化仓库中，也请一并移除）

我刚刚对翻译的内容做了一次检查，我认为没有问题。如果你这边有发现问题的话，也希望你直接指出来。我会做出相应的调整的。
未本地化的图片已经删除，后面会注意这个的。

2024-09-23 13:23 UTC, yin1999 reviewed
> 我刚刚对翻译的内容做了一次检查，我认为没有问题。如果你这边有发现问题的话，也希望你直接指出来。我会做出相应的调整的。

最显而易见的三处，其他的还请再校对一下。我不太喜欢一次又一次地更改同一个文档。

还有一点需要注意：如果你加了 sourceCommit，请确保当前文档的内容已完全同步英文文档的内容（以前的翻译也可能会有问题，需要仔细检查）。

2024-09-23 13:23 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/dealing_with_files/index.md
> +也建议文件名中使用连字符，而不是下划线：`my-file.html` vs. `my_file.html`。[谷歌搜索引擎把连字符当作单词的分隔符，但不会识别下划线](https://developers.google.com/search/docs/crawling-indexing/url-structure)。通过配置你的服务器将下划线替换为连字符可以避免这种情况，但这是额外的工作以及文件
“vs.”，请看一下以前的翻译（用的中文），挺好的

2024-09-23 13:23 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/installing_basic_software/index.md
> +- **自动化构建工具**，如 [Webpack](https://webpack.js.org/) 、[Grunt](https://gruntjs.com/) 或 [Gulp](https://gulpjs.com/) ，以自动执行重复性任务，如简化代码和运行测试。
这里有很多多余的空格

2024-09-23 13:23 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/dealing_with_files/index.md
> +5. 将 `alt` 属性的内容变为你所引入的[图像的描述信息](/zh-CN/docs/Web/HTML/Element/img#authoring_meaningful_alternate_descriptions)。在这个例子中，就是 `alt="火狐 logo：盘绕世界的火狐"`。
```suggestion
5. 将 `alt` 属性的内容变为你所引入的[图像的描述信息](/zh-CN/docs/Web/HTML/Element/img#使用有实际意义的备用描述)。在这个例子中，就是 `alt="火狐 logo：盘绕世界的火狐"`。
```

2024-09-24 03:52 UTC, familyboat commented
根据你的反馈做了一些调整。
在调整的过程中，发现更新三篇文章要调整的内容过多，不利于审核。于是改为了更新前两篇文章的内容。
我现在对于翻译这个工作还处于经验不足的阶段，而且对于之前的译文也不是很了解（之前没有sourceCommit这个信息，也无法进行有效的diff，辅助更新工作）。我也是希望你能知无不言，我也会慢慢积累出经验并得到响应的成长的。

2024-09-25 03:20 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/what_will_your_website_look_like/index.md
> +做任何事情之前，都要先有一些想法。你的网站到底是做什么的？一个网站基本上可以做任何事情，但对于你的第一个网站来说，最好简单一些。我们将从创建一个简单的网页开始，它包含一个标题、一张图像和几个段落。
```suggestion
做任何事情之前，都要先有一些想法。你的网站到底是做什么的？一个网站基本上可以做任何事情，但对于你的第一个网站来说，最好简单一些。我们将从创建一个简单的网页开始，它包含一个标题、一张图片和几个段落。
```

2024-09-25 03:20 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/what_will_your_website_look_like/index.md
> +> 复杂的项目需要详细的、细化到所有细节的指引：颜色、字体、页面上元素的间距、合适的书写风格等等。这有时称作设计指南、设计系统或品牌手册，可以在 [Firefox Photon 设计系统](https://design.firefox.com/photon/)中找到一个示例。
这里有必要改不，我感觉原翻译挺好的

2024-09-25 03:20 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/what_will_your_website_look_like/index.md
> +接下来，拿起笔和纸，大致勾勒出你所希望的网站样子。对于第一个简单的网站，虽然要绘制的东西不多，但你现在应该养成这样做的习惯。画草图很有用——并且你不必有梵高的手法！
“不必”和“有”放一起读起来会有些奇怪（可能容易让人误解）


```suggestion
接下来，拿起笔和纸，大致勾勒出你所希望的网站样子。对于第一个简单的网站，虽然要绘制的东西不多，但你现在应该养成这样做的习惯。画草图很有用——并且你不需要有梵高的手法！
```

2024-09-25 03:20 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/what_will_your_website_look_like/index.md
> +> Web 团队通常包含一名平面设计师和一名{{Glossary("UX", "用户体验")}}（UX）设计师。平面设计师把网站的视觉效果放在一起。用户体验设计师则以一种稍微更抽象的方式解决用户体验及网站交互方面的问题。
```suggestion
> Web 团队通常包含一名平面设计师和一名{{Glossary("UX", "用户体验")}}（UX）设计师。平面设计师把网站的视觉效果放在一起。用户体验设计师则以一种稍加抽象的方式解决用户体验及网站交互方面的问题。
```

2024-09-25 03:20 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/what_will_your_website_look_like/index.md
> +使用[颜色选择器](/zh-CN/docs/Web/CSS/CSS_colors/Color_picker_tool)挑选心仪的颜色。当选中某种颜色时，会显示一个六位神秘代码，类似于 `#660066`。它是一个*十六进制数*，用于表示颜色。将其复制并暂存。
https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_colors/Color_picker_tool

```suggestion
使用[色彩选择工具](/zh-CN/docs/Web/CSS/CSS_colors/Color_picker_tool)挑选心仪的颜色。当选中某种颜色时，会显示一个六位神秘代码，类似于 `#660066`。它是一个*十六进制数*，用于表示颜色。将其复制并暂存。
```

2024-09-25 03:20 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/what_will_your_website_look_like/index.md
> +![MDN 文档网站上的颜色选择器工具，包含 RGB、HSL、HEX 格式](color-picker.png)
```suggestion
![MDN 文档网站上的色彩选择工具，包含 RGB、HSL、HEX 格式](color-picker.png)
```

2024-09-25 03:20 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/what_will_your_website_look_like/index.md
> +访问 [Google 图像](https://www.google.com/imghp)搜索合适的图像。
https://www.google.com/imghp

![image](https://github.com/user-attachments/assets/8ab6fe1e-1aa7-4c91-8b77-5cd8015ca222)

下同，先改一下吧，我再做审查（这些词汇其实也不用特地改，意思大差不差）

```suggestion
访问 [Google 图片](https://www.google.com/imghp)搜索合适的图片。
```

2024-09-25 03:42 UTC, familyboat commented on files/zh-cn/learn/getting_started_with_the_web/what_will_your_website_look_like/index.md
> +访问 [Google 图像](https://www.google.com/imghp)搜索合适的图像。
行。

2024-09-25 04:42 UTC, familyboat commented
图像这一小节的内容的内容根据反馈做了更新。将 图像 改为了 图片。但对于 将图像另存为 是否要改为 将图片另存为 我有点拿不准。
我看网络上有资料显示 Mac系统是 将图像另存为（我本身没有Mac）。
就像你前面提到的，图像和图片要表达的含义是大差不差的，这里混合使用我觉得也不会有什么歧义。

2024-09-27 01:06 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/what_will_your_website_look_like/index.md
>  另一个选择是使用 [安全 Web 字体](https://web.mit.edu/jmorzins/www/fonts.html)，如 Arial、Times New Roman、Courier New。
```suggestion
另一个选择是使用[安全 Web 字体](https://web.mit.edu/jmorzins/www/fonts.html)，如 Arial、Times New Roman、Courier New。
```

2024-09-27 01:06 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/what_will_your_website_look_like/index.md
> +> 使用从 Google 服务器加载的字体可能会违反欧盟的数据隐私规定 [GDPR](https://gdpr.eu/what-is-gdpr/)，因为加载字体时会暴露用户的 IP 地址。如果这对你而言是潜在的问题，那么可以选择第二种方式，也可以选择 GDPR 认可的字体供应商，如 [Bunny Fonts](https://fonts.bunny.net/about)。
```suggestion
> 使用 Google Fonts 上托管的字体可能会违反欧盟的数据隐私规定 [GDPR](https://gdpr.eu/what-is-gdpr/)，因为该字体服务会暴露用户的 IP 地址。如果这对你而言是潜在的问题，那么可以选择第二种方式，也可以选择符合 GDPR 的字体供应商，如 [Bunny Fonts](https://fonts.bunny.net/about)。
```

2024-09-27 01:06 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/what_will_your_website_look_like/index.md
> +和图片一样，很多字体都受版权保护，也就是说，你不可以在你的网站上随意使用它们。[Google Fonts](https://developers.google.com/fonts) 是 Google 旗下的提供许多字体许可的网络服务。
```suggestion
和图片一样，很多字体都受版权保护，也就是说，你不可以在你的网站上随意使用它们。[Google Fonts](https://developers.google.com/fonts) 是 Google 旗下的提供许多字体许可的 Web 服务。
```

2024-09-27 01:10 UTC, yin1999 approved these changes
感谢。关于“将图像另存为…”这个翻译。不同的浏览器的翻译各不相同，我们就不做强制规定了，翻译合理即可。

2024-09-27 01:10 UTC, merged