[zh-cn]: sync with content
mdn/translated-content pull request #23801
Opened 2024-09-27 06:44 UTC by fuchunhui

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-09-30 02:15 UTC, jasonren0403 requested changes
有几处问题

2024-09-30 02:15 UTC, jasonren0403 commented on files/zh-cn/web/css/white-space/index.md
> +> [!NOTE] > **空格**和**其他空白分隔符**之间存在区别。定义如下：
这里暂时不要更改

2024-09-30 02:15 UTC, jasonren0403 commented on files/zh-cn/web/css/white-space/index.md
65行需要使用cssxref宏（如`{{cssxref("min-content")}}`）

2024-10-05 07:44 UTC, yin1999 commented on files/zh-cn/web/css/white-space/index.md
> +### 在表格中控制换行
```suggestion
### 控制表格中的换行
```

2024-10-08 05:50 UTC, fuchunhui commented on files/zh-cn/web/css/white-space/index.md
主版本又更新了，稍晚我再同步一轮最新内容。

2024-10-08 05:52 UTC, fuchunhui commented on files/zh-cn/web/css/white-space/index.md
> +> [!NOTE] > **空格**和**其他空白分隔符**之间存在区别。定义如下：
是啥原因，不要统一吗

2024-10-08 05:58 UTC, fuchunhui commented on files/zh-cn/web/css/white-space/index.md
看起来还丢了一些其他的翻译，我稍晚再统一更新下。

2024-10-08 07:23 UTC, fuchunhui commented on files/zh-cn/web/css/white-space/index.md
Done

2024-10-08 07:24 UTC, jasonren0403 commented on files/zh-cn/web/css/white-space/index.md
> +> [!NOTE] > **空格**和**其他空白分隔符**之间存在区别。定义如下：
新标记在处理 markdown 标记开头的文字时有 bug（并且暂未修复）
相关PR：https://github.com/mdn/yari/pull/11548

2024-10-08 07:32 UTC, fuchunhui commented on files/zh-cn/web/css/white-space/index.md
> +> [!NOTE] > **空格**和**其他空白分隔符**之间存在区别。定义如下：
好吧，难怪提交的时候总是提示无修改，明白了。我处理下

2024-10-09 02:24 UTC, jasonren0403 commented on files/zh-cn/web/css/white-space/index.md
> +默认情况下，一个制表符等于 8 个空格，且可以使用 [`tab-size`](/zh-CN/docs/Web/CSS/tab-size) 属性。对于 `normal`、`nowrap` 和 `pre-line`值，每个制表符都会被转化为一个空格（U+0020）字符。
```suggestion
默认情况下，一个制表符等于 8 个空格，且可以使用 [`tab-size`](/zh-CN/docs/Web/CSS/tab-size) 属性。对于 `normal`、`nowrap` 和 `pre-line` 值，每个制表符都会被转化为一个空格（U+0020）字符。
```

2024-10-09 02:25 UTC, jasonren0403 commented on files/zh-cn/web/css/white-space/index.md
>  {{EmbedLiveSample("试试看", "100%", 350)}}
```suggestion
{{EmbedLiveSample("试试看", "100%", 450)}}
```

2024-10-09 02:26 UTC, jasonren0403 approved these changes
👍

2024-10-09 02:26 UTC, merged