zh-cn: sync the translation of the second two articles in `Get started with the web`
mdn/translated-content pull request #23807
Opened 2024-09-27 10:29 UTC by familyboat

### Description

更新`web 入门`的第三篇和第四篇文章。
更新的时候，对`代码`部分中的英文是否要翻译不是很确定，所以我保留了原样；对嵌入的图片的 alt 是否要翻译也不是很确定，也是保留了原样。
欢迎提出建议。

### Motivation

### Additional details

### Related issues and pull requests

2024-09-29 11:26 UTC, yin1999 commented
> 更新的时候，对`代码`部分中的英文是否要翻译不是很确定，所以我保留了原样；对嵌入的图片的 alt 是否要翻译也不是很确定

都需要翻译，代码部分仅在有配套的 GitHub 实时示例时，不需要进行全内容的翻译（仅翻译不影响对应关系的注释等内容）

加粗效果如果无法正常应用，请使用 Markdown 原生语法的链接代替，并将加粗的样式放到链接文字内：

```md
我想要加粗一个[**链接**](https://example.com)，那我应该这么写。
```

2024-10-01 02:33 UTC, familyboat commented
尝试了你说的加粗效果的方法，但还是没法正确显示，你帮忙看一下这个部分。
code 部分和 Alt 部分的翻译，根据你说的，我是这样理解的：Alt部分都翻译了，code部分有的涉及到对应的英文图片，这部分就没有翻译，其他的就都翻译了。

2024-10-02 13:49 UTC, yin1999 requested changes
请注意这些问题

2024-10-02 13:49 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/html_basics/index.md
> +1. **开始标签**（Opening tag）：包含元素的名称（本例为 p），及包围名称的**大于号**、**小于号**。这表示元素从这里开始或者开始起作用——在本例中即段落由此开始。
英文文档用的是给“尖括号”加粗，可以调整一下翻译+样式

2024-10-02 13:49 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/html_basics/index.md
> +3. 引号包围的属性值。
同上一处，调整一下翻译

2024-10-02 13:49 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/html_basics/index.md
> +不包含任何内容的元素称为{{glossary("void element", "空元素")}}。比如 {{htmlelement("img")}} 元素：
```suggestion
不包含任何内容的元素称为[**空元素**](/zh-CN/docs/Glossary/Void_element)。我们以 HTML 页面中已有的 {{htmlelement("img")}} 元素为例：
```

2024-10-02 13:49 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/html_basics/index.md
> +1. 用户有视觉障碍。有严重视觉障碍的用户可以使用屏幕阅读器来朗读 alt 属性的内容。
```suggestion
1. 用户有视觉障碍。有严重视觉障碍的用户可以使用屏幕阅读器来朗读代替（alt）文本。
```

2024-10-02 13:49 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/html_basics/index.md
> +alt 属性的关键字即“描述文本”。alt 文本应向用户完整地传递图像要表达的意思。用 "测试图片" 来描述 Firefox 标志并不合适，修改成 "Firefox 标志：一只盘旋在地球上的火狐" 就好多了。
```suggestion
alt 文本的关键字即“描述文本”。alt 文本应向用户完整地传递图像要表达的意思。用 "测试图片" 来描述 Firefox 标志并不合适，修改成“Firefox 标志：一只盘旋在地球上的火狐”就好多了。
```

2024-10-02 13:49 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/html_basics/index.md
> +> 更多信息请参阅 [无障碍学习模块](/zh-CN/docs/learn/Accessibility)。
```suggestion
> 更多信息请参阅[无障碍学习模块](/zh-CN/docs/learn/Accessibility)。
```

2024-10-02 13:49 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/html_basics/index.md
> +标题元素可用于指定内容的标题和子标题。就像一本书的书名、每章的大标题、小标题，等。HTML 文档也是一样。HTML 包括六个级别的标题，{{htmlelement("标题元素", "&lt;h1&gt;-&lt;h6&gt;")}}，一般最多用到 3-4 级标题。
```suggestion
标题元素可用于指定内容的标题和子标题。就像一本书的书名、每章的大标题、小标题，等。HTML 文档也是一样。HTML 包括六个级别的标题，{{htmlelement("Heading_Elements", "&lt;h1&gt; - &lt;h6&gt;")}}，一般最多用到 3-4 级标题。
```

2024-10-02 13:49 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/html_basics/index.md
> +> **备注：** `href` 这个名字可能一开始看起来有点令人费解，代表超文本引用（_**h**ypertext **ref**erence_）。
翻译尽量与原文对齐，请修改

2024-10-02 13:49 UTC, yin1999 commented on files/zh-cn/learn/getting_started_with_the_web/html_basics/index.md
> +HTML 是一种用于定义内容结构的*标记语言*。HTML 由一系列的{{Glossary("element", "元素")}}组成，这些元素可以用来包围不同部分的内容，使其以某种方式呈现或者工作。一对{{Glossary("tag", "标签")}}可以为一段文字或者一张图片添加超链接，将文字设置为斜体，改变字号，等等。例如，键入下面一行内容：
https://github.com/mdn/translated-content/pull/23807#issuecomment-2381319529 说的是这种情况

```suggestion
HTML 是一种用于定义内容结构的*标记语言*。HTML 由一系列的[**元素**](/zh-CN/docs/Glossary/Element)组成，这些元素可以用来包围不同部分的内容，使其以某种方式呈现或者工作。一对{{Glossary("tag", "标签")}}可以为一段文字或者一张图片添加超链接，将文字设置为斜体，改变字号，等等。例如，键入下面一行内容：
```

2024-10-02 14:28 UTC, familyboat commented on files/zh-cn/learn/getting_started_with_the_web/html_basics/index.md
> +HTML 是一种用于定义内容结构的*标记语言*。HTML 由一系列的{{Glossary("element", "元素")}}组成，这些元素可以用来包围不同部分的内容，使其以某种方式呈现或者工作。一对{{Glossary("tag", "标签")}}可以为一段文字或者一张图片添加超链接，将文字设置为斜体，改变字号，等等。例如，键入下面一行内容：
你是这个意思啊，我理解错了。我现在明白你的意思了。

2024-10-02 14:30 UTC, familyboat commented on files/zh-cn/learn/getting_started_with_the_web/dealing_with_files/index.md
> +1. 许多计算机，特别是网络服务器，是区分大小写的。因此，假如把你的网站上的一张图片放在 `test-site/MyImage.jpg`，然后在一个不同的文件中，你试图以 `test-site/myimage.jpg` 调用该图片，它可能无法工作。
没问题，我注意到之前的译文是有翻译web的，那现在就是web都不翻译了，是这个意思吗？

2024-10-04 07:38 UTC, familyboat commented
已经根据评论意见进行了修改。

2024-10-04 13:15 UTC, yin1999 approved these changes

2024-10-04 13:15 UTC, merged

2024-10-04 13:24 UTC, familyboat commented
不好意思，刚刚发现有一条建议被隐藏了，就没有应用。