[ko] accessibility/aria/roles/landmark_role 신규 번역
mdn/translated-content pull request #23894
Opened 2024-10-03 08:31 UTC by 0jenn0

### Description

안녕하세요 [landmark_role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/landmark_role) 페이지 신규 번역했습니다!

2024-10-03 08:49 UTC, 0jenn0 commented on files/ko/web/accessibility/aria/roles/landmark_role/index.md
> +- [접근성 향상을 위한 HTML 랜드마크 역할 사용하기](https://developer.mozilla.org/en-US/blog/aria-accessibility-html-landmark-roles/) (MDN 블로그, 2023)
`/ko/blog/aria-accessibility-html-landmark-roles/` 로 했더니
preview 사이트에서
<img width="568" alt="스크린샷 2024-10-03 오후 5 20 31" src="https://github.com/user-attachments/assets/13baffb0-3cb6-4170-bc18-be5d4ed3901a">

위와 같이 보이길래 지금처럼 수정했는데 괜찮을까요?

2024-10-09 07:09 UTC, wisedog commented on files/ko/web/accessibility/aria/roles/landmark_role/index.md
> +- [접근성 향상을 위한 HTML 랜드마크 역할 사용하기](https://developer.mozilla.org/en-US/blog/aria-accessibility-html-landmark-roles/) (MDN 블로그, 2023)
괜찮을 것 같습니다. 👍

2024-10-09 07:11 UTC, wisedog requested changes
리뷰가 좀 늦었습니다. 하나만 수정 부탁드릴께요

2024-10-09 07:11 UTC, wisedog commented on files/ko/web/accessibility/aria/roles/landmark_role/index.md
> +---
[관련 가이드](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md)를 참고해서 `i18n`을 넣어주세요!

2024-10-09 08:50 UTC, 0jenn0 commented on files/ko/web/accessibility/aria/roles/landmark_role/index.md
> +---
가이드 문서에 `l10n.*1만 사용합니다.` 라고 되어있어서 `l10n` 추가로 수정했는데 아니면 다시 수정하겠습니다!

2024-10-10 00:39 UTC, wisedog commented on files/ko/web/accessibility/aria/roles/landmark_role/index.md
> +---
아 l10n 이었군요;;; -ㅁ-

2024-10-10 00:39 UTC, wisedog approved these changes
LGTM!

2024-10-10 00:41 UTC, merged