fr-glossary/fps id:239
mdn/translated-content pull request #2393
Opened 2021-09-08 02:29 UTC by ManuSquall

suggest french translation for [id:239 /glossary/fps](https://tristantheb.github.io/history-content/#239)

2021-09-08 02:32 UTC, ManuSquall commented
Aï ! Même bémol que d'habitude on dirait :-(

2021-09-08 04:56 UTC, SphinxKnight requested changes

2021-09-08 04:56 UTC, SphinxKnight commented on files/fr/glossary/fps/index.html
> +<p>Movies generally have a frame rate of 24 fps. They are able to have fewer frames per second because the illusion of life is created with motion blurs. When moving on a computer screen there are no
Il reste cette phrase à traduire :)

2021-09-08 04:56 UTC, SphinxKnight commented on files/fr/glossary/fps/index.html
> +<p>Une <strong>fréquence d'images</strong> est la vitesse à laquelle le navigateur est capable de recalculer, de mettre en page et de peindre le contenu à l'écran. Les <strong>images par seconde</str
site Web -> site web
en français, il n'y a pas d'espace avant l'unité : 60 fps -> 60fps
pas de majuscule aux noms de langue : en Anglais -> en anglais

2021-09-08 04:56 UTC, SphinxKnight commented on files/fr/glossary/fps/index.html
> +<p>Les films ont généralement une fréquence d'images de 24 fps. Ils sont capables d'avoir moins d'images par seconde car l'illusion de la vie est créée avec des flous de mouvement. Lorsque vous vous
même remarque qu'au-dessus pour l'espace avant l'unité

2021-09-08 04:56 UTC, SphinxKnight commented on files/fr/glossary/fps/index.html
> +
ligne vide superflue :)

2021-09-08 11:40 UTC, ManuSquall commented on files/fr/glossary/fps/index.html
> +<p>Movies generally have a frame rate of 24 fps. They are able to have fewer frames per second because the illusion of life is created with motion blurs. When moving on a computer screen there are no
Oups, oublié de l'enlever après la traduction

2021-09-14 10:20 UTC, SphinxKnight approved these changes
Merci @ManuSquall  :) 
J'avais loupé l'histoire de l'identifiant en majuscule pour la barre latérale, je me suis permis de pousser un commit à ce sujet.

2021-09-14 10:21 UTC, merged

2021-09-14 10:41 UTC, ManuSquall commented
Hello Sphinx, l'histoire de l'identifiant à savoir? Donc au final on transforme bien les liens avec des majuscules en minuscules? Merci pour la review!

2021-09-14 10:51 UTC, ManuSquall reviewed
LGTM