Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_components 更新：
mdn/translated-content pull request #2402
Opened 2021-09-09 07:38 UTC by SimonAllen0901

1. 遷移英文版 index.html 至 zh-tw
2. 遷移英文版圖片至 zh-tw
3. 翻譯此頁內容

2021-09-10 14:49 UTC, t7yang requested changes
- 關於提升翻譯品質的問題，我舉出了前三個發現的問題並給翻譯的範例及說明可以如何改善。其他部分我就逐一列出，請重新檢視全文，盡可能提升翻譯品質，感謝。
- 其他則為明確的錯誤，請務必修正。

2021-09-10 14:49 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
> +<p><strong>你應該始終將唯一鍵（unique keys）傳遞給任何你用迭代渲染的東西裡。</strong>在你的瀏覽器中沒有什麼明顯變化，但如果你不使用唯一鍵（unique keys），React就會到你的console控制台發出警告訊息，並且你的應用程式可能會表現的很奇怪！</p>
> 你應該始終將唯一鍵（unique keys）

括號原文的作法在一篇文章或是一個章節中出現一次就好，不用一直重複提醒。

2021-09-10 14:49 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
> +<p>現在我們已整理好最重要的元件，我們可以將應用程式的剩餘部分也轉成元件。要記住元件要馬是明顯的UI部分，要馬是重複使用的UI部分，或者兩者都是，我們可以再製作兩個元件：</p>
> 要馬是明顯的UI部分，要馬

沒有「要馬」這種詞彙，就算有也應該是「要嘛」。

這是一個非常口語的用法，請不要在書面體使用。

2021-09-10 14:49 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
> + <li>在文件檔案的最開頭Import引入<code>React</code>，就像我們在<code>Todo.js</code>做的一樣。</li>
> 在文件檔案的最開頭Import引入<code>React</code>

這裡的 import 單純就是一個詞彙，不是程式碼的關鍵字，請使用「匯入」即可。（其餘的也請一併改用匯入）

2021-09-10 14:49 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
> + <li>建立一個基本結構與<code>Todo()</code>相同的新<code>Form()</code>元件，並將匯出。</li>
> 並將匯出

並將`其`匯出

2021-09-10 14:49 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
> + <li>在文件檔案的最末段Export匯出<code>Form</code></li>
> 在文件檔案的最末段Export匯出<code>Form</code>

- 「文件」是多餘的。
- 這裡 Export 也一樣只是單純的詞彙。

2021-09-10 14:49 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
> +<p>執行與在<code>FilterButton.js</code>中建立<code>Form.js</code>一樣的操作，從<code>App.js</code>中調用元件<code>FilterButton()</code>，並複製在<code>&lt;div&gt;</code>元素內第一個按鈕的HTML，從<code>class</code>到<code>filters</code>
> 中調用元件

「調用」是中國用語，請改用「呼叫」

2021-09-10 14:49 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
> +<p><strong>注意：</strong>你可能會注意到，我們在這裡犯了與第一次為<code>&lt;Todo /&gt;</code>元件犯的相同的錯誤，因為每個按鈕都是相同的。沒關係！我們稍後會在<a href="/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_interactivit
> 我們在這裡犯了與第一次為<code>&lt;Todo /&gt;</code>元件犯的相同的錯誤

犯了第一次在<code>&lt;Todo /&gt;</code>元件中相同的錯誤

2021-09-10 14:49 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
> +<p>到目前為止都還OK，但是我們的元件必須回傳一些東西！返回到<code>src/App.js</code>中，從無序清單中複製第一個<code><a href="/en-US/docs/Web/HTML/Element/li">&lt;li&gt;</a></code>，並將其貼到<code>Todo.js</code>中，使其讀起來像這樣：</p>
> `<a href="/en-US/docs/Web/HTML/Element/li">&lt;li&gt;</a>`

所有的內部連結都應轉換到 /zh-TW 語系。

2021-09-15 05:02 UTC, SimonAllen0901 commented
哇謝謝你的建議
很有幫助
我會再作修整調整

2021-12-23 02:15 UTC, closed without merging