Fix #21014
mdn/translated-content pull request #24060
Opened 2024-10-14 14:17 UTC by SphinxKnight

An update to easing-function intended to fix #21014

2024-10-14 16:39 UTC, tristantheb requested changes
En dehors de la première ligne, le reste a l'air ok 👍🏻

2024-10-14 16:39 UTC, tristantheb commented on files/fr/web/css/easing-function/index.md
> +Le [type de données](/fr/docs/Web/CSS/CSS_Types) [CSS](/fr/docs/Web/CSS) **`<easing-function>`** représente une fonction mathématique décrivant dont une valeur numérique change.
```suggestion
Le [type de données](/fr/docs/Web/CSS/CSS_Types) [CSS](/fr/docs/Web/CSS) **`<easing-function>`** représente une fonction mathématique décrivant la vitesse à laquelle la valeur change.
```

ça fait étrange à lire à l'oral sinon xD

2024-10-14 16:49 UTC, SphinxKnight commented on files/fr/web/css/easing-function/index.md
> +Le [type de données](/fr/docs/Web/CSS/CSS_Types) [CSS](/fr/docs/Web/CSS) **`<easing-function>`** représente une fonction mathématique décrivant dont une valeur numérique change.
merci :)

2024-10-15 10:43 UTC, tristantheb approved these changes

2024-10-15 10:43 UTC, merged