[zh-cn] Create translation of html `maxlength` attribute
mdn/translated-content pull request #24128
Opened 2024-10-18 08:19 UTC by MaxtuneLee

### Description
Create translation of html maxlength attribute

### Motivation
There is no translation for `maxlength` attribute currently

### Additional details

### Related issues and pull requests
Relates to https://github.com/mdn/translated-content/issues/17632

2024-10-18 08:33 UTC, MaxtuneLee commented on files/zh-cn/web/html/attributes/maxlength/index.md
> +- {{htmlelement('input')}}
Why? nothing changed in the suggestion.

2024-10-18 09:41 UTC, T34-active commented on files/zh-cn/web/html/attributes/maxlength/index.md
> +{{EmbedLiveSample('Examples', '100%', 200)}}
```suggestion
{{EmbedLiveSample('示例', '100%', 200)}}
```

2024-10-18 09:43 UTC, T34-active commented on files/zh-cn/web/html/attributes/maxlength/index.md
> +字符串长度是以 UTF-16 编码单元为单位进行测量的，通常（[对于大多数语言脚本](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/length#strings_with_length_not_equal_to_the_number_of_characters)）等同于字符数。如果未指定 `maxlength`，或指定了无效
```suggestion
字符串长度是以 UTF-16 编码单元为单位进行测量的，通常（[对于大多数语言脚本](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/length#长度不等于字符数的字符串)）等同于字符数。如果未指定 `maxlength`，或指定了无效值，则输入没有最大长度限制。
```

2024-10-18 11:45 UTC, PassionPenguin requested changes

2024-10-18 11:45 UTC, PassionPenguin commented on files/zh-cn/web/html/attributes/maxlength/index.md
> +- {{htmlelement('input')}}
```suggestion
- {{htmlelement('input')}}

```

2024-10-18 11:45 UTC, PassionPenguin commented on files/zh-cn/web/html/attributes/maxlength/index.md
> +`maxlength` 属性定义了用户可以在 {{htmlelement('input')}} 或 {{htmlelement('textarea')}} 中输入的最大[字符串长度](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/length)。该属性的值必须是 0 或更高的整数。
```suggestion
`maxlength` 属性定义了用户可以在 {{htmlelement('input')}} 或 {{htmlelement('textarea')}} 中输入的[字符串长度](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/length)的最大值。该属性的值必须是非负整数。
```

2024-10-18 11:45 UTC, PassionPenguin commented on files/zh-cn/web/html/attributes/maxlength/index.md
> +字符串长度是以 UTF-16 编码单元为单位进行测量的，通常（[对于大多数语言脚本](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/length#长度不等于字符数的字符串)）等同于字符数。如果未指定 `maxlength`，或指定了无效值，则输入没有最大长度限制。
```suggestion
字符串长度是以 UTF-16 编码单元为单位进行计算的，通常（[对于大多数语言脚本](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/length#长度不等于字符数的字符串)）等同于字符个数。如果未指定 `maxlength`，或指定了无效值，则输入将没有最大长度限制。
```

2024-10-18 11:45 UTC, PassionPenguin commented on files/zh-cn/web/html/attributes/maxlength/index.md
> +- {{htmlelement('input')}}
![image](https://github.com/user-attachments/assets/efb33d5d-95fa-49fb-92c7-2816f2de4efa)

mdn-linter 不灵敏

2024-10-20 04:12 UTC, MaxtuneLee commented on files/zh-cn/web/html/attributes/maxlength/index.md
> +- {{htmlelement('input')}}
> ![image](https://private-user-images.githubusercontent.com/41184947/377853996-efb33d5d-95fa-49fb-92c7-2816f2de4efa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzOTc3NjQsIm5iZiI6MTcyOTM5NzQ2NCwicGF0aCI6Ii80MTE4NDk0Ny8zNzc4NTM5OTYtZWZiMzNkNWQtOTVmYS00OWZiLTkyYzctMjgxNmYyZGU0ZWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDA0MTEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiOGVhZDllZmY5ZWM0YjY1MzhjMzY1N2ViYjQ5MWYzYmQzZGRmMDkyMmU4MzQwOWE3NmExNjYwZDAxZjNiYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GfIS7xYJs0zGDmFWTJlJZh-N8nBj6uL4-qOzUO2l7FA)
> 
> mdn-linter 不灵敏

原来如此，感谢 😃

2024-10-21 08:24 UTC, yin1999 reviewed
建议：

2024-10-21 08:24 UTC, yin1999 commented on files/zh-cn/web/html/attributes/maxlength/index.md
> +`maxlength` 属性定义了用户可以在 {{htmlelement('input')}} 或 {{htmlelement('textarea')}} 中输入的[字符串长度](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/length)的最大值。该属性的值必须是非负整数。
```suggestion
**`maxlength`** 属性定义了用户可以在 {{htmlelement('input')}} 或 {{htmlelement('textarea')}} 中输入的[字符串长度](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/length)的最大值。该属性的值必须是非负整数。
```

2024-10-21 08:24 UTC, yin1999 commented on files/zh-cn/web/html/attributes/maxlength/index.md
> +字符串长度是以 UTF-16 编码单元为单位进行计算的，通常（[对于大多数语言脚本](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/length#长度不等于字符数的字符串)）等同于字符个数。如果未指定 `maxlength`，或指定了无效值，则输入将没有最大长度限制。
https://developer.mozilla.org/zh-CN/docs/Glossary/Code_unit

```suggestion
字符串长度是以 UTF-16 码元为单位进行计算的，通常（[对于大多数语言脚本](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/length#长度不等于字符数的字符串)）等同于字符个数。如果未指定 `maxlength`，或指定了无效值，则输入将没有最大长度限制。
```

2024-10-21 08:24 UTC, yin1999 commented on files/zh-cn/web/html/attributes/maxlength/index.md
> +任何 `maxlength` 的值必须大于或等于 [`minlength`](/zh-CN/docs/Web/HTML/Attributes/minlength) 的值（如果存在且有效）。如果字段文本值的长度超过了 `maxlength` 的 UTF-16 编码单元长度，输入将无法通过约束验证。约束验证仅在用户更改值时应用。
```suggestion
任何 `maxlength` 的值必须大于或等于 [`minlength`](/zh-CN/docs/Web/HTML/Attributes/minlength) 的值（如果存在且有效）。如果字段文本值的长度超过了 `maxlength` 的 UTF-16 码元长度，输入将无法通过约束验证。约束验证仅在用户更改值时应用。
```

2024-10-21 08:24 UTC, yin1999 commented on files/zh-cn/web/html/attributes/maxlength/index.md
> +虽然浏览器通常会阻止用户输入超过 `maxlength` 属性允许的文本长度，但如果输入的长度确实超出了 `maxlength` 的限制，{{domxref("ValidityState.tooLong", "tooLong")}} 属性会在 {{domxref("ValidityState")}} 对象中返回 `true`。
```suggestion
虽然浏览器通常会阻止用户输入超过 maxlength 属性允许的文本长度，但如果输入的长度确实超出了 maxlength 的限制，{{domxref("ValidityState")}} 对象的 {{domxref("ValidityState.tooLong", "tooLong")}} 属性会返回 true。
```

2024-10-21 08:24 UTC, yin1999 commented on files/zh-cn/web/html/attributes/maxlength/index.md
> +- [表单数据校验](/zh-CN/docs/Learn/Forms/Form_validation)
```suggestion
- [表单验证](/zh-CN/docs/Learn/Forms/Form_validation)
```

2024-10-21 08:24 UTC, yin1999 commented on files/zh-cn/web/html/attributes/maxlength/index.md
> +  sourceCommit: 2b112aef57df0649462db5d9f47d782a7aa1f25c
当前文档的最新的 commit sha：

- https://github.com/mdn/content/commit/067a40e4ed27ea6e1f3b8bbfec15cd9dc3078f4c

```suggestion
  sourceCommit: 067a40e4ed27ea6e1f3b8bbfec15cd9dc3078f4c
```

2024-10-21 08:44 UTC, yin1999 approved these changes
Thanks @MaxtuneLee

2024-10-21 08:44 UTC, merged