Increase Chinese translation
mdn/translated-content pull request #24192
Opened 2024-10-22 09:25 UTC by cnbilinyj

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-10-23 00:15 UTC, jasonren0403 requested changes
请先应用mdn-linter对格式进行的自动修复

2024-10-24 07:29 UTC, jasonren0403 requested changes
一些建议

2024-10-24 07:29 UTC, jasonren0403 commented on files/zh-cn/web/api/lastelementchild/index.md
> +title: 文档：lastElementChild 属性
接口名不译

```suggestion
title: Document：lastElementChild 属性
```

2024-10-24 07:29 UTC, jasonren0403 commented on files/zh-cn/web/api/lastelementchild/index.md
> +short-title: lastElementChild
```suggestion
```

2024-10-24 07:29 UTC, jasonren0403 commented on files/zh-cn/web/api/lastelementchild/index.md
> +slug: Web/API/Document/lastElementChild
当前文档对应英语文档提交的 SHA 值，可以在这里拿到 https://github.com/mdn/content/commits/main/files/en-us/web/api/document/lastelementchild/index.md

```suggestion
slug: Web/API/Document/lastElementChild
l10n:
  sourceCommit: 41a8b9c9832359d445d136b6d7a8a28737badc6b
```

2024-10-24 07:29 UTC, jasonren0403 commented on files/zh-cn/web/api/lastelementchild/index.md
> +**`Document.lastElementChild`** 只读属性返回文档的最后一个子元素 {{domxref("Element")}}，如果没有子元素，则返回 `null`。
```suggestion
**`Document.lastElementChild`** 只读属性返回文档的最后一个子 {{domxref("Element", "元素", "", "nocode")}}，如果没有子元素，则返回 `null`。
```

2024-10-24 09:51 UTC, cnbilinyj commented
感谢发件人: ***@***.*** ***@***.***> 代表 Jason Ren ***@***.***>发送时间: 星期四, 十月 24, 2024 3:29:45 下午收件人: mdn/translated-content ***@***.***>抄送: 农药君 ***@***.***>; Author ***@***.***>主题: Re: [mdn/translated-content] Improve Chinese translation (PR #24192)
@jasonren0403 requested changes on this pull request.

一些建议

In files/zh-cn/web/api/lastelementchild/index.md:
> @@ -0,0 +1,36 @@
+---
+title: 文档：lastElementChild 属性

接口名不译
⬇️ Suggested change
-title: 文档：lastElementChild 属性
+title: Document：lastElementChild 属性





In files/zh-cn/web/api/lastelementchild/index.md:
> @@ -0,0 +1,36 @@
+---
+title: 文档：lastElementChild 属性
+short-title: lastElementChild

⬇️ Suggested change
-short-title: lastElementChild





In files/zh-cn/web/api/lastelementchild/index.md:
> @@ -0,0 +1,36 @@
+---
+title: 文档：lastElementChild 属性
+short-title: lastElementChild
+slug: Web/API/Document/lastElementChild

当前文档对应英语文档提交的 SHA 值，可以在这里拿到 https://github.com/mdn/content/commits/main/files/en-us/web/api/document/lastelementchild/index.md
⬇️ Suggested change
-slug: Web/API/Document/lastElementChild
+slug: Web/API/Document/lastElementChild
+l10n:
+  sourceCommit: 41a8b9c9832359d445d136b6d7a8a28737badc6b





In files/zh-cn/web/api/lastelementchild/index.md:
> @@ -0,0 +1,36 @@
+---
+title: 文档：lastElementChild 属性
+short-title: lastElementChild
+slug: Web/API/Document/lastElementChild
+---
+
+{{ APIRef("DOM") }}
+
+**`Document.lastElementChild`** 只读属性返回文档的最后一个子元素 {{domxref("Element")}}，如果没有子元素，则返回 `null`。

⬇️ Suggested change
-**`Document.lastElementChild`** 只读属性返回文档的最后一个子元素 {{domxref("Element")}}，如果没有子元素，则返回 `null`。
+**`Document.lastElementChild`** 只读属性返回文档的最后一个子 {{domxref("Element", "元素", "", "nocode")}}，如果没有子元素，则返回 `null`。



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-11-15 03:08 UTC, jasonren0403 commented
部分修复建议还尚未查看，如 https://github.com/mdn/translated-content/pull/24192/files/213413db1afa0c4cd1c086c623a6bfdba9d4fc4c#r1814411180

2024-11-25 08:02 UTC, closed without merging

2024-11-25 08:02 UTC, yin1999 commented
As the author has not made any changes on this PR. I've created another PR to replace it: #24748.