zh-cn: sync the translation of "Enumerability_and_ownership_of_properties"
mdn/translated-content pull request #24196
Opened 2024-10-22 10:35 UTC by familyboat

### Description

英文版有更新，对中文版进行同步。

### Motivation

### Additional details

### Related issues and pull requests

2024-11-01 07:59 UTC, jasonren0403 requested changes

2024-11-01 07:59 UTC, jasonren0403 commented on files/zh-cn/web/javascript/enumerability_and_ownership_of_properties/index.md
> +*可枚举属性*是那些内部的可枚举标志设置为 `true` 的属性，对于通过直接赋值或属性初始化器创建的属性，该标识值默认为 `true`。对于通过 [Object.defineProperty](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) 等定义的属性，该标识值默认为 `false`。大多数
```suggestion
*可枚举属性*是那些内部的可枚举标志设置为 `true` 的属性，对于通过直接赋值或属性初始化器创建的属性，该标识值默认为 `true`。对于通过 [`Object.defineProperty`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) 等定义的属性，默认并不是可枚举的。大多数迭代方法（如：[`for...in`](/zh-CN/docs/Web/JavaScript/Reference/Statements/for...in) 循环和 [`Object.keys`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/keys)）仅访问可枚举的键。
```

2024-11-01 07:59 UTC, jasonren0403 commented on files/zh-cn/web/javascript/enumerability_and_ownership_of_properties/index.md
> +属性的所有权由属性是否直接属于该对象决定的，而不是由属性是否属于它的原型链决定的。
```suggestion
属性的所有权取决于属性是否直接属于该对象，而不是对象的原型链。
```

2024-11-01 07:59 UTC, jasonren0403 commented on files/zh-cn/web/javascript/enumerability_and_ownership_of_properties/index.md
> +所有的属性，不论是可枚举或不可枚举、是字符串或 symbol、是自有的或继承的，都能用[点记号表示法或方括号表示法](/zh-CN/docs/Web/JavaScript/Reference/Operators/Property_accessors)进行访问。在本文，我们将专注于 JavaScript 提供的一个接着一个地访问对象属性的方法。
```suggestion
所有的属性，不论是可枚举或不可枚举、是字符串或 symbol、是自有的或继承的，都能用[点记号表示法或方括号表示法](/zh-CN/docs/Web/JavaScript/Reference/Operators/Property_accessors)进行访问。在本文，我们将专注于 JavaScript 提供的逐一访问一组对象属性的方法。
```

2024-11-01 07:59 UTC, jasonren0403 commented on files/zh-cn/web/javascript/enumerability_and_ownership_of_properties/index.md
> +| [`Object.getOwnPropertySymbols`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertySymbols)
```suggestion
| [`Object.getOwnPropertyNames`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames)                                                                                                                                                         | ✅<br />（字符串） | ❌               | ✅<br />（字符串）   | ❌                 |
| [`Object.getOwnPropertySymbols`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertySymbols)                                                                                                                                                     | ✅<br />（symbol） | ❌               | ✅<br />（symbol）   | ❌                 |
```

2024-11-01 07:59 UTC, jasonren0403 commented on files/zh-cn/web/javascript/enumerability_and_ownership_of_properties/index.md
> +| [`for...in`](/zh-CN/docs/Web/JavaScript/Reference/Statements/for...in)
```suggestion
| [`for...in`](/zh-CN/docs/Web/JavaScript/Reference/Statements/for...in)                                                                                                                                                                                                 | ✅<br />（字符串） | ✅<br />（字符串） | ❌                 | ❌                 |
```

2024-11-01 07:59 UTC, jasonren0403 commented on files/zh-cn/web/javascript/enumerability_and_ownership_of_properties/index.md
> +| [`Object.assign`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)<br />(第二个参数)
注意 Object.assign 不止两个参数

```suggestion
| [`Object.assign`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)<br />（第一个参数之后）                                                                                                                                                                 | ✅               | ❌               | ❌                 | ❌                 |
```

2024-11-01 07:59 UTC, jasonren0403 commented on files/zh-cn/web/javascript/enumerability_and_ownership_of_properties/index.md
> +| [Object spread](/zh-CN/docs/Web/JavaScript/Reference/Operators/Spread_syntax)
```suggestion
| [对象展开](/zh-CN/docs/Web/JavaScript/Reference/Operators/Spread_syntax)                                                                                                                                                                                          | ✅               | ❌               | ❌                 | ❌                 |
```

2024-11-01 07:59 UTC, jasonren0403 commented on files/zh-cn/web/javascript/enumerability_and_ownership_of_properties/index.md
> +- 使用 `SimplePropertyRetriever.theGetMethodYouWant(obj).includes(prop)` 时将发生判断操作。
```suggestion
- 使用 `SimplePropertyRetriever.theGetMethodYouWant(obj).includes(prop)` 时将发生检测操作。
```

2024-11-01 07:59 UTC, jasonren0403 commented on files/zh-cn/web/javascript/enumerability_and_ownership_of_properties/index.md
> +- 使用 `SimplePropertyRetriever.theGetMethodYouWant(obj).forEach((value, prop) => {}));` 时将发生迭代操作。 (或使用 `filter()`、`map()` 等方法)
```suggestion
- 使用 `SimplePropertyRetriever.theGetMethodYouWant(obj).forEach((value, prop) => {}));` 时将发生迭代操作。（或使用 `filter()`、`map()` 等方法）
```

2024-11-01 07:59 UTC, jasonren0403 commented on files/zh-cn/web/javascript/enumerability_and_ownership_of_properties/index.md
> +## See also
```suggestion
## 参见
```

2024-11-01 08:14 UTC, familyboat commented on files/zh-cn/web/javascript/enumerability_and_ownership_of_properties/index.md
> +- 使用 `SimplePropertyRetriever.theGetMethodYouWant(obj).forEach((value, prop) => {}));` 时将发生迭代操作。 (或使用 `filter()`、`map()` 等方法)
左括号是要使用半角左括号吗？ @jasonren0403

2024-11-01 09:32 UTC, familyboat commented on files/zh-cn/web/javascript/enumerability_and_ownership_of_properties/index.md
> +- 使用 `SimplePropertyRetriever.theGetMethodYouWant(obj).forEach((value, prop) => {}));` 时将发生迭代操作。 (或使用 `filter()`、`map()` 等方法)
不好意思，在本地查看代码后，发现是用的全角的左括号。以前没注意到两个全角的标点符号相连时，会是这样的显示效果。误以为是半角的左括号了。 @jasonren0403

2024-11-02 02:31 UTC, jasonren0403 approved these changes
👍 Thanks

2024-11-02 02:32 UTC, merged

2024-11-02 02:35 UTC, jasonren0403 commented on files/zh-cn/web/javascript/enumerability_and_ownership_of_properties/index.md
> +- 使用 `SimplePropertyRetriever.theGetMethodYouWant(obj).forEach((value, prop) => {}));` 时将发生迭代操作。 (或使用 `filter()`、`map()` 等方法)
> 不好意思，在本地查看代码后，发现是用的全角的左括号。以前没注意到两个全角的标点符号相连时，会是这样的显示效果。误以为是半角的左括号了。 @jasonren0403

对，我们尽量[在中文上下文中使用全角标点符号](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md#%E6%A0%87%E7%82%B9%E7%AC%A6%E5%8F%B7)