zh-cn: sync the translation of "JavaScript_technologies_overview"
mdn/translated-content pull request #24219
Opened 2024-10-25 06:51 UTC by familyboat

### Description

英文版有更新，对中文版进行同步。

### Motivation

### Additional details

### Related issues and pull requests

2024-10-29 05:25 UTC, jasonren0403 requested changes
一些修改建议

2024-10-29 05:25 UTC, jasonren0403 commented on files/zh-cn/web/javascript/javascript_technologies_overview/index.md
> +- [Carakan](<https://en.wikipedia.org/wiki/Presto_(browser_engine)#ECMAScript_engines>)，用于早期版本的 Opera。
```suggestion
- [Carakan](https://zh.wikipedia.org/wiki/Presto#JavaScript引擎)，用于早期版本的 Opera。
```

2024-10-29 05:25 UTC, jasonren0403 commented on files/zh-cn/web/javascript/javascript_technologies_overview/index.md
> +- Microsoft 的 [Chakra](<https://en.wikipedia.org/wiki/Chakra_(JScript_engine)>) 引擎，用于 Internet Explorer（尽管它实现的语言正式名称为“JScript”，为了避免商标问题）。早期版本的 Edge 使用的新 JavaScript 引擎，让人困惑地也叫 [Chakra](<https://en.wik
```suggestion
- Microsoft 的 [Chakra](<https://zh.wikipedia.org/wiki/Chakra_(JScript引擎)>) 引擎，用于 Internet Explorer（尽管它实现的语言正式名称为“JScript”，为了避免商标问题）。早期版本的 Edge 使用的新 JavaScript 引擎，令人困惑的是，它也叫作 [Chakra](<https://zh.wikipedia.org/wiki/Chakra_(JavaScript引擎)>)。
```

2024-10-29 05:25 UTC, jasonren0403 commented on files/zh-cn/web/javascript/javascript_technologies_overview/index.md
> +- Mozilla 的 [Rhino](<https://en.wikipedia.org/wiki/Rhino_(JavaScript_engine)>) 引擎，用 Java 语言实现的 JavaScript 引擎，主要由 Norris Boyd 创造（也在 Netscape）。
```suggestion
- Mozilla 的 [Rhino](<https://zh.wikipedia.org/wiki/Rhino_(JavaScript引擎)>) 引擎，用 Java 语言实现的 JavaScript 引擎，主要由 Norris Boyd（也曾在 Netscape）创建。
```

2024-10-29 05:25 UTC, jasonren0403 commented on files/zh-cn/web/javascript/javascript_technologies_overview/index.md
> +- Mozilla 的 [SpiderMonkey](https://spidermonkey.dev/)，用于 Firefox。它是*首*款 JavaScript 引擎，由 Brendan Eich 在 Netscape 创造。
```suggestion
- Mozilla 的 [SpiderMonkey](https://spidermonkey.dev/)，用于 Firefox。它是*首*款 JavaScript 引擎，由 Netscape 公司的 Brendan Eich 创建。
```

2024-10-29 05:25 UTC, jasonren0403 commented on files/zh-cn/web/javascript/javascript_technologies_overview/index.md
> +还有一些为非浏览器目的特别裁剪过的引擎：
```suggestion
还有一些引擎是专门为非浏览器用途定制的：
```

2024-10-29 05:25 UTC, jasonren0403 commented on files/zh-cn/web/javascript/javascript_technologies_overview/index.md
> +- [Node.js](https://nodejs.org/)——Node.js 是用于轻易构建快速、可扩展的网络应用的平台。
```suggestion
- [Node.js](https://nodejs.org/)——Node.js 是可轻松构建快速、可扩展网络应用程序的平台。
```

2024-10-29 05:25 UTC, jasonren0403 commented on files/zh-cn/web/javascript/javascript_technologies_overview/index.md
> +以下 JavaScript shell 是通过浏览器的 JavaScript 引擎运行代码：
```suggestion
以下 JavaScript shell 通过浏览器的 JavaScript 引擎运行代码：
```

2024-10-29 05:25 UTC, jasonren0403 commented on files/zh-cn/web/javascript/javascript_technologies_overview/index.md
>    - : 包括 [Web Console](https://firefox-source-docs.mozilla.org/devtools-user/web_console/index.html)、[JavaScript Profiler](https://firefox-source-docs.mozilla.org/devtools-user/performance/index.html
```suggestion
  - : 包括 [Web 控制台](https://firefox-source-docs.mozilla.org/devtools-user/web_console/index.html)、[JavaScript 性能分析](https://firefox-source-docs.mozilla.org/devtools-user/performance/index.html)、[调试器](https://firefox-source-docs.mozilla.org/devtools-user/debugger/index.html)等。
```

2024-10-29 05:25 UTC, jasonren0403 commented on files/zh-cn/web/javascript/javascript_technologies_overview/index.md
> +  - : StackBlitz 同样是一个支持调试的在线 playground，它支持托管和部署使用了 React、Angular 等技术的全栈应用
```suggestion
  - : StackBlitz 同样是一个支持调试的在线 playground，它支持托管和部署使用了 React、Angular 等技术的全栈应用。
```

2024-10-29 06:53 UTC, familyboat commented
已应用评论意见。

2024-10-30 01:39 UTC, jasonren0403 approved these changes
👍

2024-10-30 01:40 UTC, merged