zh-cn: sync the translation of 'inheritance and the prototype chain'
mdn/translated-content pull request #24216
Opened 2024-10-24 15:39 UTC by familyboat

### Description

英文版有更新，对中文版进行同步。

### Motivation

### Additional details

### Related issues and pull requests

2024-10-30 14:39 UTC, yin1999 commented on files/zh-cn/web/javascript/inheritance_and_the_prototype_chain/index.md
> +有几种可以指定对象的 `[[Prototype]]` 的方法，这些方法将在[后面的小节](#不同的创建对象和改变原型链的方法)中列出。现在，我们将使用 [`__proto__` 语法](/zh-CN/docs/Web/JavaScript/Reference/Operators/Object_initializer#原型_setter)进行说明。值得注意的是，`{ __proto__: ...
- 我们基本将“deprecated”统一翻译为“弃用”，而非“废弃”：https://developer.mozilla.org/zh-CN/docs/MDN/Writing_guidelines/Experimental_deprecated_obsolete
- 小节的标题我感觉是没有修改的必要性的（原标题本身并没问题，这样的修改也容易造成外站对 MDN 小节的引用链接失效）

2024-10-30 14:39 UTC, yin1999 commented on files/zh-cn/web/javascript/inheritance_and_the_prototype_chain/index.md
> +// 这叫做属性遮蔽（Property Shadowing）
不清楚修改的意义，可以看到前面也有 `xxx 属性` 这样的写法，还有专门改成这样的。

2024-10-30 14:39 UTC, yin1999 commented on files/zh-cn/web/javascript/inheritance_and_the_prototype_chain/index.md
> +// 其默认没有属性“d”，检查其原型。
同

2024-10-30 14:39 UTC, yin1999 commented on files/zh-cn/web/javascript/inheritance_and_the_prototype_chain/index.md
> +同理，你可以创建更长的原型链，并在所有的原型上查找属性。
这里的 them 是指“原型”吗，不应该是“原型链”吗。

之后的内容修改也请再考虑一下，可以删去可能不太有必要的修改。

2024-11-01 10:31 UTC, familyboat commented
关于标题，我对 mdn 中所有的文档进行替换。
关于“属性 x”还是“x 属性”没有做调整（你没有给出相应的意见）
将一些不必要的修改做了调整。

2024-11-02 14:43 UTC, familyboat commented
我觉得我应该为之前的回应表达一下歉意。我觉得我应该是带着解决方案和你沟通。不用纠结过去是什么样子的，而是想法子让未来更好。 @yin1999

2024-11-04 11:37 UTC, yin1999 requested changes

2024-11-04 11:37 UTC, yin1999 commented on files/zh-cn/web/javascript/inheritance_and_the_prototype_chain/index.md
> +在定义复杂的继承结构时，类提供了非常高的可读性和可维护性。[私有属性](/zh-CN/docs/Web/JavaScript/Reference/Classes/Private_properties)是原型继承中没有简单替代方案的特性。然而，类比传统的构造函数的性能要差，以及不支持旧环境。
```suggestion
在定义复杂的继承结构时，类提供了非常高的可读性和可维护性。[私有属性](/zh-CN/docs/Web/JavaScript/Reference/Classes/Private_properties)是原型继承中没有简单替代方案的特性。然而，类比传统的构造函数的性能要差，而且不支持旧环境。
```

2024-11-04 11:37 UTC, yin1999 commented on files/zh-cn/web/javascript/inheritance_and_the_prototype_chain/index.md
> +与 `Object.setPrototypeOf` 相比，将 `__proto__` 设置为非对象的值（译者注：`null` 不会被忽略）只会被忽略，而非抛出异常。它也只有稍微好一点的浏览器支持。然而，它是非标准的，并且已废弃。你应该几乎总是使用 `Object.setPrototypeOf` 作为代替。
请不要添加译者注，上面解释过了

2024-11-04 11:37 UTC, yin1999 commented on files/zh-cn/web/javascript/inheritance_and_the_prototype_chain/index.md
> +JavaScript 中的所有构造函数都有一个称作 `prototype` 的特殊属性，它与 `new` 运算符一起使用。原型对象的引用复制到新实例的内部属性 `[[Prototype]]` 中。例如，当你执行 `const a1 = new A()` 时，JavaScript（在内存中创建对象之后，用为对象定义的 `this` 运行 `A()` 之前）设置 `a1.[[Prototype]]
（这一段）感觉可不作修改

2024-11-04 12:19 UTC, yin1999 commented
> 关于“属性 x”还是“x 属性”没有做调整（我个人偏好一致性）

我的意思是，你给出的翻译是存在不一致的问题的（你的翻译有“属性 x”，也有“x 属性”）

> 我觉得我应该为之前的回应表达一下歉意。我觉得我应该是带着解决方案和你沟通。不用纠结过去是什么样子的，而是想法子让未来更好。

的确不用纠结过去是什么样的，只是我希望减少一些“可能是无太多必要的修改”，因为修改意味着额外的检查（因为修改不能确保一定正确）。要考虑一点，当贡献者翻译完一篇文档后，审查人员几乎需要付出同等的时间来对内容进行审查。但是活跃的贡献者数量目前是多于活跃的审查人员的。

我更希望的是，比如我们看到一句话的翻译可能会让人误解，或者使用的辞藻不够完善优美（引人注意），那么我们在有更好的想法时可以对其进行修改。

2024-11-05 16:16 UTC, familyboat commented
对你之前提到的所有评论意见做了相应的调整。我认可的地方是调整回原有的翻译（例如，“x 属性”还是“属性 x”，我遵循的就是英文表述的顺序）；我存在不同意见的地方，也给出了相应的回应。也请你考虑一下我的想法。

2024-11-09 12:52 UTC, yin1999 commented
还有上面提到过的问题没有得到解决：https://github.com/mdn/translated-content/pull/24216#discussion_r1822775843

2024-11-10 02:30 UTC, familyboat commented
> 还有上面提到过的问题没有得到解决（其他没问题了）：[#24216 (comment)](https://github.com/mdn/translated-content/pull/24216#discussion_r1822775843)

已处理。

2024-11-10 06:44 UTC, yin1999 approved these changes
Thanks @familyboat

2024-11-10 06:44 UTC, merged