ja: WEB/API/IndexedDB_API/Using_indexedDB を更新
mdn/translated-content pull request #24239
Opened 2024-10-26 14:07 UTC by mahito1594

### Description

Firefox のプライベートブラウジングで IndexedDB が動作するようになったため、英語版記事の記載に合わせて修正しました。
また 2024/08/20 時点の英語版記事 (62ce78b5c89fd809e00683b62f8e6a116990f82d) と差異がある記載を**一部**更新しました

### Motivation

### Additional details

mdn/content#31996 で削除されている「Locale-aware sorting」節 (日本語記事は「[ロケールを意識した並べ替え](https://developer.mozilla.org/ja/docs/Web/API/IndexedDB_API/Using_IndexedDB#%E3%83%AD%E3%82%B1%E3%83%BC%E3%83%AB%E3%82%92%E6%84%8F%E8%AD%98%E3%81%97%E3%81%9F%E4%B8%A6%E3%81%B9%E6%9B%BF%E3%81%88)」) の更新対応ができていません。
更新手順を理解できていないため更新しないままにしましたが、他の方の作業の妨げになりそうでしたら 67a22a9d7f64ee90a22b8e67240e8e4b950bdca2 を revert します。

更新手順を把握出来たら私の方で mdn/content#31996 を日本語記事に取り込む作業に挑戦してみたいと考えています。

### Related issues and pull requests
- Fixes mozilla-japan/translation#794

2024-10-30 14:39 UTC, mfuji09 requested changes
更新ありがとうございます。
1件だけ、修正をお願いします。

2024-10-30 14:39 UTC, mfuji09 commented on files/ja/web/api/indexeddb_api/using_indexeddb/index.md
> +IndexedDB API は必要なエラー処理を最小限にするよう設計されていますので、多くのエラーイベントを見ることはないでしょう (少なくとも、API に慣れていなければ)。しかしデータベースを開く場合は、エラーイベントが発生する一般的な状況があります。もっとも多いであろう問題は、データベースを作成する許可をユーザーがウェブアプリに与えなかったことです。IndexedDB の主要な設計目標のひ
「ブラウザ」は「ブラウザー」と長音表記を使用してください。

```suggestion
IndexedDB API は必要なエラー処理を最小限にするよう設計されていますので、多くのエラーイベントを見ることはないでしょう (少なくとも、API に慣れていなければ)。しかしデータベースを開く場合は、エラーイベントが発生する一般的な状況があります。もっとも多いであろう問題は、データベースを作成する許可をユーザーがウェブアプリに与えなかったことです。IndexedDB の主要な設計目標のひとつが、オフラインで使用するために大量のデータを保存できるようにすることです。(各ブラウザーでどれだけの量のストレージを持てるかについては、[ブラウザーのストレージ制限と削除基準ページ内のどれだけのデータが格納できるか](/ja/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria#どれだけのデータが格納できるか)をご覧ください)
```

2024-10-31 13:27 UTC, mahito1594 commented on files/ja/web/api/indexeddb_api/using_indexeddb/index.md
> +IndexedDB API は必要なエラー処理を最小限にするよう設計されていますので、多くのエラーイベントを見ることはないでしょう (少なくとも、API に慣れていなければ)。しかしデータベースを開く場合は、エラーイベントが発生する一般的な状況があります。もっとも多いであろう問題は、データベースを作成する許可をユーザーがウェブアプリに与えなかったことです。IndexedDB の主要な設計目標のひ
ご指摘ありがとうございます。
取り込みいたしました。

2024-10-31 16:40 UTC, mfuji09 approved these changes
OKです。ありがとうございました。

2024-10-31 16:42 UTC, merged