Update create author form
mdn/translated-content pull request #24261
Opened 2024-10-27 16:28 UTC by ikenk

### Description

### Motivation

To update the create_author_form doc

### Additional details

### Related issues and pull requests

2024-10-29 09:22 UTC, Yanko1013 reviewed
一些建议：

2024-10-29 09:22 UTC, Yanko1013 commented on files/zh-cn/learn/server-side/express_nodejs/forms/create_author_form/index.md
> +与![创建种类表单](/zh-CN/docs/Learn/Server-side/Express_Nodejs/forms/Create_genre_form) 一样，要使用 _express-validator_，我们必须 _require_ 我们想要使用的函数。
`As with the [genre form](/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_genre_form), `

`与![创建种类表单](/zh-CN/docs/Learn/Server-side/Express_Nodejs/forms/Create_genre_form) 一样，`

建议：这里应当引用文档，而非图片。

2024-10-29 09:22 UTC, Yanko1013 commented on files/zh-cn/learn/server-side/express_nodejs/forms/create_author_form/index.md
> +- 我们可以使用 `optional()` 函数来保证仅当有字段输入时才去运行后续的验证（这允许我们验证可选字段）。例如，下面我们检查可选的出生日期是否符合 ISO8601 标准（传递的`{ values: "falsy" }`对象意味着我们将接受空字符串或 `null` 作为空值）。
```suggestion
- 我们可以使用 `optional()` 函数来保证仅当有字段输入时才去运行后续的验证（这允许我们验证可选字段）。例如，下面我们检查可选的出生日期是否符合 ISO8601 标准（传递的 `{ values: "falsy" }` 对象意味着我们将接受空字符串或 `null` 作为空值）。
```

2024-10-29 09:22 UTC, Yanko1013 commented on files/zh-cn/learn/server-side/express_nodejs/forms/create_genre_form/index.md
> +要控制器中使用 _express-validator_，我們必須从 `'express-validator'` 模块中 _require_ 我们想使用的函数。
```suggestion
要控制器中使用 _express-validator_，我们必须从 `'express-validator'` 模块中 _require_ 我们想使用的函数。
```

`zh-cn` 应当使用简体中文。

2024-10-29 09:22 UTC, Yanko1013 commented on files/zh-cn/learn/server-side/express_nodejs/forms/create_genre_form/index.md
> +> 我们的验证使用 `trim()` 来确保不接受空格作为种类名称。我们还对表单中​​字段定义添加 `required` ![布尔属性](/zh-CN/docs/Glossary/Boolean/HTML)来验证客户端上的字段不为空：
应当移除`!`，否则为引用图片。

2024-10-29 10:33 UTC, yin1999 requested changes

2024-10-29 10:33 UTC, yin1999 commented on files/zh-cn/learn/server-side/express_nodejs/forms/create_genre_form/index.md
请移除这个文档的修改（相关的修改已在 #24220 中体现）

2024-10-31 16:29 UTC, ikenk commented on files/zh-cn/learn/server-side/express_nodejs/forms/create_genre_form/index.md
你说的这个应该不用我来处理吧？

2024-11-01 07:50 UTC, yin1999 commented on files/zh-cn/learn/server-side/express_nodejs/forms/create_genre_form/index.md
需要，请清理一下当前 PR 的提交。里面混入了很多 rebase 后产生的无效提交内容。

2024-11-01 07:59 UTC, ikenk commented on files/zh-cn/learn/server-side/express_nodejs/forms/create_genre_form/index.md
对不起，我也不知道这次是怎么回事，从本地提交到github的时候总在提示我冲突，我只好先在fork的仓库里把所有的分支都同步到和mdn仓库一致，然后再git pull --rebase进本地分支，最后再git push，但是git push之后就多出了很多别人的pr记录。
我其实很困惑为什么我在fork的仓库里sync的时候会把pr也包含进来。
如果可以的话我就重开一个pr，这样省事一点

2024-11-01 08:03 UTC, yin1999 commented on files/zh-cn/learn/server-side/express_nodejs/forms/create_genre_form/index.md
重新开吧，请避免修改 fork 仓库的主分支（主分支只用于和上游同步），有内容需要反馈到上游时请始终新建分支，然后只在分支中做修改）。常见的内容修改涉及的分支也请使用 `git merge` 命令来更新分支（用 `git rebase` 会导致审查人员的审查进度被重置）。

2024-11-01 08:03 UTC, closed without merging

2024-11-01 08:40 UTC, ikenk commented
我一直都是保持主分支和上游的同步而不会主动修改主分支来着，这次确实不知道怎么回事，给你添麻烦了，不好意思

> 2024年11月1日 16:03，A1lo ***@***.***> 写道：
> 
> 上游