docs: sync <base>
mdn/translated-content pull request #24271
Opened 2024-10-28 19:22 UTC by sedlukha

### Description

Update to the <base> documentation from the original article https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

2024-11-16 12:12 UTC, leon-win requested changes
Привет, @sedlukha !

Внёс предложения по улучшению перевода.

Как уже говорил в другом PR, необходимо уделить большее внимание качеству перевода, формулировок, грамматики.

На ревью таких PR'ов тратится очень много времени, сравнимое с созданием перевода, что очень непродуктивно.

2024-11-16 12:12 UTC, leon-win commented on files/ru/web/html/element/base/index.md
> +### Значение target не должно содержать символ ASCII переноса строки, табуляции или <
```suggestion
### Значение target не должно содержать символы переноса строк, табуляции или <
```

2024-11-16 12:12 UTC, leon-win commented on files/ru/web/html/element/base/index.md
> +Это сделано для предотвращения атак с инъекцией незавершенной разметки, атаки без использования скриптов, при которой в страницу внедряется незавершенный атрибут `target`, захватывающий любой следующ
```suggestion
Это необходимо для предотвращения атак с инъекцией незавершённой разметки. Это вид атаки без использования скриптов, при которой в страницу внедряется незавершённый атрибут `target`, в который попадает весь последующий текст до тех пор, пока браузер не встретит символ, закрывающий атрибут.
```

2024-11-16 12:12 UTC, leon-win commented on files/ru/web/html/element/base/index.md
> +Теги [Open Graph](https://ogp.me/) не учитывают `<base>` и всегда должны содержать полные абсолютные URL. Например:
```suggestion
Теги [Open Graph](https://ogp.me/) не учитывают `<base>` и всегда должны содержать полные абсолютные URL-адреса. Например:
```

2024-11-16 12:12 UTC, leon-win commented on files/ru/web/html/element/base/index.md
> +      <td>Должен иметь открывающий тег и без закрывающего тега.</td>
```suggestion
      <td>Должен иметь открывающий тег и не иметь закрывающего.</td>
```

2024-11-22 19:02 UTC, sedlukha commented
@leon-win спасибо за предложения по улучшению. все принял

2024-11-22 19:50 UTC, leon-win approved these changes

2024-11-22 19:50 UTC, merged