zh-cn: sync the translation of "memory management"
mdn/translated-content pull request #24277
Opened 2024-10-29 07:44 UTC by familyboat

### Description

英文版有更新，对中文本进行同步。

### Motivation

### Additional details

### Related issues and pull requests

2024-10-29 08:53 UTC, Yanko1013 commented on files/zh-cn/web/javascript/memory_management/index.md
> +更多有关 [`WeakRef`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/WeakRef) and [`FinalizationRegistry`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry) 的 API 的信息，参见对应的参考页
```suggestion
更多有关 [`WeakRef`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/WeakRef) 和 [`FinalizationRegistry`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry) 的 API 的信息，参见对应的参考页面。
```

2024-11-01 08:27 UTC, jasonren0403 requested changes
一些修改建议

2024-11-01 08:27 UTC, jasonren0403 commented on files/zh-cn/web/javascript/memory_management/index.md
> +  sourceCommit: e03b13c7e157ec7b7bb02a6c7c4854b862195905
```suggestion
  sourceCommit: 2c762771070a207d410a963166adf32213bc3a45
```

2024-11-01 08:27 UTC, jasonren0403 commented on files/zh-cn/web/javascript/memory_management/index.md
> +底层语言（如 C 语言）拥有手动的内存管理基本操作，例如：[`malloc()`](https://pubs.opengroup.org/onlinepubs/009695399/functions/malloc.html) 和 [`free()`](https://en.wikipedia.org/wiki/C_dynamic_memory_allocation#Overview_of_fun
尽量使用中文维基链接

```suggestion
底层语言（如 C 语言）拥有手动的内存管理原语，例如：[`malloc()`](https://pubs.opengroup.org/onlinepubs/009695399/functions/malloc.html) 和 [`free()`](https://zh.wikipedia.org/wiki/C动态内存分配#函数概述)。相反，JavaScript 是在创建对象时自动分配内存，并在不再使用时自动释放内存（_垃圾回收_）。这个自动性是混乱的潜在根源：它让开发者错误地以为他们不需要担心内存管理。
```

2024-11-01 08:27 UTC, jasonren0403 commented on files/zh-cn/web/javascript/memory_management/index.md
>  3. 不需要时将其释放\归还
```suggestion
3. 不需要时将其释放
```

2024-11-01 08:27 UTC, jasonren0403 commented on files/zh-cn/web/javascript/memory_management/index.md
> +const n = 123; // 为数字分配内存
```suggestion
const n = 123; // 为数值分配内存
```

2024-11-01 08:27 UTC, jasonren0403 commented on files/zh-cn/web/javascript/memory_management/index.md
> +const a2 = ["generation", "nan nan"];
```suggestion
const a = ["yeah yeah", "no no"];
const a2 = ["generation", "no no"];
```

2024-11-01 08:27 UTC, jasonren0403 commented on files/zh-cn/web/javascript/memory_management/index.md
> +// 有四个元素的新数组，由 a 和 a2 元素连接而成。
```suggestion
// 有四个元素的新数组，由 a 和 a2 其中的元素连接而成。
```

2024-11-01 08:27 UTC, jasonren0403 commented on files/zh-cn/web/javascript/memory_management/index.md
> +使用值基本上是指在分配的内存上进行读写。读写变量值或对象的属性值、甚至给函数传递参数都会使用值。
```suggestion
使用值基本上是指在分配的内存上进行读写。读写变量值或对象的属性值，甚至给函数传递参数都会使用值。
```

2024-11-01 08:27 UTC, jasonren0403 commented on files/zh-cn/web/javascript/memory_management/index.md
> +一些高级语言（如 JavaScript）使用的是自动内存管理（也就是[垃圾回收](<https://en.wikipedia.org/wiki/Garbage_collection_(computer_science)>)（GC））的形式。垃圾回收器的目的是监控内存分配和确定一块已分配的内存何时不再需要并释放这块内存。这个自动过程是个近似的说法，因为确定一块特定的内存是否仍然需要这个一般性问题是
```suggestion
一些高级语言（如 JavaScript）使用的是自动内存管理（也就是[垃圾回收](<https://zh.wikipedia.org/wiki/垃圾回收_(計算機科學)>)（GC））的形式。垃圾回收器的目的是监控内存分配和确定一块已分配的内存何时不再需要并释放这块内存。这个自动过程是个近似的说法，因为确定一块特定的内存是否仍然需要这个一般性问题是[无法判定的](http://en.wikipedia.org/wiki/Decidability_%28logic%29)。
```

2024-11-01 08:27 UTC, jasonren0403 commented on files/zh-cn/web/javascript/memory_management/index.md
> +> 现代的浏览器不再使用引用计数进行垃圾回收。
```suggestion
> 现代 JavaScript 引擎不再使用引用计数进行垃圾回收。
```

2024-11-01 08:27 UTC, jasonren0403 commented on files/zh-cn/web/javascript/memory_management/index.md
> +这个算法假定有一组叫做*根*的对象。在 JavaScript 中，根是全局对象。垃圾回收器将定期从这些根开始，找到从这些根能引用到的所有对象，然后找到从这些对象能引用到的所有对象，等等。从根开始，垃圾回收器将找到所有可以到达的对象并收集所有不能到达的对象。
```suggestion
这个算法假定有一组叫做*根*的对象。在 JavaScript 中，根是全局对象。垃圾回收器将定期从这些根开始，找到从这些根能引用到的所有对象，然后找到从这些对象能引用到的所有对象，等等。从根开始，垃圾回收器将找到所有*可到达*的对象并收集所有不能到达的对象。
```

2024-11-01 08:27 UTC, jasonren0403 commented on files/zh-cn/web/javascript/memory_management/index.md
> +
```suggestion
最大可用堆内存可以通过使用标志来增加：

```

2024-11-01 08:27 UTC, jasonren0403 commented on files/zh-cn/web/javascript/memory_management/index.md
> +`WeakMap` 和 `WeakSet` 的名字来源于*弱引用*值的概念。假设 `x` 被 `y`弱引用，这意味着尽管你能通过 `y` 访问 `x`的值，但如果 `x` 不再被*强引用*的话，标记清除算法不会认为 `x` 是可达的。大多数数据结构，除了在这讨论的这两个，都是强引用传入的对象，这样你才能在任意时间取回这些对象。只要程序中不再有键的引用，`WeakMap` 和 `WeakSet`
```suggestion
`WeakMap` 和 `WeakSet` 的名字来源于*弱引用*值的概念。假设 `x` 被 `y` 弱引用，这意味着尽管你能通过 `y` 访问 `x` 的值，但如果 `x` 不再被*强引用*的话，标记清除算法不会认为 `x` 是可达的。大多数数据结构，除了在这讨论的这两个，都是强引用传入的对象，这样你才能在任意时间取回这些对象。只要程序中不再有键的引用，`WeakMap` 和 `WeakSet` 的键能被垃圾回收（对 `WeakMap` 对象，值接着也适合被回收）。这一点由两个特性确保：
```

2024-11-01 08:27 UTC, jasonren0403 commented on files/zh-cn/web/javascript/memory_management/index.md
> +- `WeakMap` 和 `WeakSet` 仅能存储对象或 symbol。这是因为仅对象是可垃圾回收的——原始值总是被复制的（也就是，`1 === 1` 但 `{} !== {}`），这让原始值永远呆在集合中。[已注册的 symbol](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Symbol#shared_symbols_in_t
```suggestion
- `WeakMap` 和 `WeakSet` 仅能存储对象或 symbol。这是因为仅对象是可垃圾回收的——原始值总是被复制的（也就是，`1 === 1` 但 `{} !== {}`），这让原始值永远呆在集合中。[已注册的 symbol](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Symbol#shared_symbols_in_the_global_symbol_registry)（如 `Symbol.for("key")`）也是被复制，因此也不是可垃圾回收的，但是用 `Symbol("key")` 创建的 symbol 是可垃圾回收的。[内置通用 symbol](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Symbol#内置通用（well-known）symbol)（如 `Symbol.iterator`）来自于一组固定的集合，在程序的整个声明周期中是唯一的，类似于固有对象（如 `Array.prototype`），所以它们也能作为键。
```

2024-11-01 08:27 UTC, jasonren0403 commented on files/zh-cn/web/javascript/memory_management/index.md
> +假设 `key` 存储为真实的引用，它将创建一个循环引用，让键和值都不适合垃圾回收，即使在 `key` 没有被引用时——因为假设 `key` 被垃圾回收了，这意味着在某个特定的时刻，`value.key` 将指向一个不存在的地址，而这是非法的。为了修复这个，`WeakMap` 和 `WeakSet` 的条目不是真正的引用，而是 [临时对象](https://dl.acm.org/doi/pdf/
```suggestion
假设 `key` 存储为真实的引用，它将创建一个循环引用，让键和值都不适合垃圾回收，即使在 `key` 没有被引用时——因为假设 `key` 被垃圾回收了，这意味着在某个特定的时刻，`value.key` 将指向一个不存在的地址，而这是非法的。为了修复这个，`WeakMap` 和 `WeakSet` 的条目不是真正的引用，而是[临时对象](https://dl.acm.org/doi/pdf/10.1145/263700.263733)（对标记清除机制的增强）。[Barros 等人](https://www.jucs.org/jucs_14_21/eliminating_cycles_in_weak/jucs_14_21_3481_3497_barros.pdf)对算法提供了一个很好的总结（第 4 页）。引用一段：
```

2024-11-01 08:27 UTC, jasonren0403 commented on files/zh-cn/web/javascript/memory_management/index.md
> +> **Note:** `WeakRef` 和 `FinalizationRegistry` 能直接内省进垃圾回收机制。[尽量避免使用](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/WeakRef#尽量避免使用)因为运行时语义几乎完全不受保证。
```suggestion
> **备注：** `WeakRef` 和 `FinalizationRegistry` 能直接内省进垃圾回收机制。[尽量避免使用](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/WeakRef#尽量避免使用)，因为运行时语义几乎完全不受保证。
```

2024-11-01 08:27 UTC, jasonren0403 commented on files/zh-cn/web/javascript/memory_management/index.md
> +  // 一个 Map：从字符串 URL 到结果的 WeakRef
```suggestion
  // 一个 Map：从字符串 URL 到 WeakRef 结果
```

2024-11-01 08:27 UTC, jasonren0403 commented on files/zh-cn/web/javascript/memory_management/index.md
> +[`FinalizationRegistry`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry) 提供了一个更强的机制观察垃圾回收。它让你注册对象以及对象被垃圾回收时得到通知。例如，对于上面的缓存系统这个例子，即使在 blob 自身被垃圾回收时，引用 blob 的 `WeakRef` 对象不会被垃
```suggestion
[`FinalizationRegistry`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry) 提供了一个更强的机制观察垃圾回收。它让你注册对象以及对象被垃圾回收时得到通知。例如，对于上面的缓存系统这个例子，即使在 blob 自身被垃圾回收时，引用 blob 的 `WeakRef` 对象不会被垃圾回收——随着时间的积累，`Map` 可能积聚大量的无用条目。在这里的例子中，使用 `FinalizationRegistry` 能执行清除。
```

2024-11-01 08:27 UTC, jasonren0403 commented on files/zh-cn/web/javascript/memory_management/index.md
> +  // 一个 Map：从字符串 URL 到结果的 WeakRef
```suggestion
  // 一个 Map：从字符串 URL 到 WeakRef 结果
```

2024-11-01 08:35 UTC, familyboat commented on files/zh-cn/web/javascript/memory_management/index.md
> +底层语言（如 C 语言）拥有手动的内存管理基本操作，例如：[`malloc()`](https://pubs.opengroup.org/onlinepubs/009695399/functions/malloc.html) 和 [`free()`](https://en.wikipedia.org/wiki/C_dynamic_memory_allocation#Overview_of_fun
OK

2024-11-02 02:42 UTC, jasonren0403 approved these changes
👍

2024-11-02 02:42 UTC, merged