[zh-cn]: create doc for Fenced_frame_API
mdn/translated-content pull request #24374
Opened 2024-11-06 11:21 UTC by fuchunhui

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-11-07 06:25 UTC, T34-active reviewed
nits

2024-11-07 06:25 UTC, T34-active commented on files/zh-cn/web/api/fenced_frame_api/index.md
> +网络上[隐私](/zh-CN/docs/Web/Privacy)和[安全](/zh-CN/docs/Web/Security)问题的一个主要来源是嵌入在 {{htmlelement("iframe")}} 元素中的内容。历史上，`<iframe>`被用于设置第三方 cookie，这些 cookie 可用于跨站点共享信息和追踪用户。此外，嵌入在 `<iframe>` 中的内容可以与其嵌入文档进行通
```suggestion
网络上[隐私](/zh-CN/docs/Web/Privacy)和[安全](/zh-CN/docs/Web/Security)问题的一个主要来源是嵌入在 {{htmlelement("iframe")}} 元素中的内容。历史上，`<iframe>` 被用于设置第三方 cookie，这些 cookie 可用于跨站点共享信息和追踪用户。此外，嵌入在 `<iframe>` 中的内容可以与其嵌入文档进行通信（例如，使用 {{domxref("Window.postMessage()")}}）。
```

2024-11-07 06:25 UTC, T34-active commented on files/zh-cn/web/api/fenced_frame_api/index.md
> +  - : 表示 {{htmlelement("fencedframe")}} 的导航配置，即该框架中将显示什么内容。`FencedFrameConfig` 由诸如[受保护的受众 API](https://developers.google.com/privacy-sandbox/private-advertising/protected-audience)等来源返回，并设置为 {{domxre
```suggestion
  - : 表示 {{htmlelement("fencedframe")}} 的导航配置，即该框架中将显示什么内容。`FencedFrameConfig` 由诸如[受保护的受众 API](https://developers.google.com/privacy-sandbox/private-advertising/protected-audience) 等来源返回，并设置为 {{domxref("HTMLFencedFrameElement.config")}} 的值。
```

2024-11-07 06:25 UTC, T34-active commented on files/zh-cn/web/api/fenced_frame_api/index.md
> +- [用户代理客户端提示](/zh-CN/docs/Web/HTTP/Client_hints#user-agent_client_hints)在封闭框架中不可用，因为它们依赖于[权限策略](/zh-CN/docs/Web/HTTP/Permissions_Policy)委托，这可能会被用来泄露数据。
```suggestion
- [用户代理客户端提示](/zh-CN/docs/Web/HTTP/Client_hints#用户代理客户端提示)在封闭框架中不可用，因为它们依赖于[权限策略](/zh-CN/docs/Web/HTTP/Permissions_Policy)委托，这可能会被用来泄露数据。
```

2024-11-07 06:25 UTC, T34-active commented on files/zh-cn/web/api/fenced_frame_api/index.md
> +只有通过设置在 `<fencedframe>` 上的权限策略，才能启用专门设计为在其中使用的特定功能；在此上下文中，其他受策略控制的功能不可用。参见[围栏框架可用的权限策略](/zh-CN/docs/Web/HTML/Element/fencedframe#permissions_policies_available_to_fenced_frames)查看更多信息。
```suggestion
只有通过设置在 `<fencedframe>` 上的权限策略，才能启用专门设计为在其中使用的特定功能；在此上下文中，其他受策略控制的功能不可用。参见[围栏框架可用的权限策略](/zh-CN/docs/Web/HTML/Element/fencedframe#围栏框架可用的权限策略)查看更多信息。
```

2024-11-11 08:57 UTC, yin1999 requested changes
一些建议

2024-11-11 08:57 UTC, yin1999 commented on files/zh-cn/web/api/fenced_frame_api/index.md
> +**Fenced Frame API** 为控制嵌入在 {{htmlelement("fencedframe")}} 元素中的内容提供功能。
```suggestion
**围栏框架 API**（Fenced Frame API）提供了用于控制嵌入在 {{htmlelement("fencedframe")}} 元素中的内容的功能。
```

2024-11-11 08:57 UTC, yin1999 commented on files/zh-cn/web/api/fenced_frame_api/index.md
> +网络上[隐私](/zh-CN/docs/Web/Privacy)和[安全](/zh-CN/docs/Web/Security)问题的一个主要来源是嵌入在 {{htmlelement("iframe")}} 元素中的内容。历史上，`<iframe>` 被用于设置第三方 cookie，这些 cookie 可用于跨站点共享信息和追踪用户。此外，嵌入在 `<iframe>` 中的内容可以与其嵌入文档进行
```suggestion
Web 上[隐私](/zh-CN/docs/Web/Privacy)和[安全](/zh-CN/docs/Web/Security)问题的一个主要来源是嵌入在 {{htmlelement("iframe")}} 元素中的内容。历史上，`<iframe>` 被用于设置第三方 cookie，这些 cookie 可用于跨站点共享信息和追踪用户。此外，嵌入在 `<iframe>` 中的内容可以与其嵌入文档进行通信（例如，使用 {{domxref("Window.postMessage()")}}）。
```

2024-11-11 08:57 UTC, yin1999 commented on files/zh-cn/web/api/fenced_frame_api/index.md
> +大多数现代浏览器都在研究存储分区机制，以便 cookie 数据不再用于跟踪（例如，参见[具有独立分区状态的 Cookie（CHIPS）](/zh-CN/docs/Web/Privacy/Privacy_sandbox/Partitioned_cookies)或 [Firefox 状态分区机制](/zh-CN/docs/Web/Privacy/State_Partitioning)）。
```suggestion
大多数现代浏览器都在研究分区存储机制，以便 cookie 数据不再用于跟踪（有关示例请参见[具有独立分区状态的 Cookie（CHIPS）](/zh-CN/docs/Web/Privacy/Privacy_sandbox/Partitioned_cookies)或 [Firefox 状态分区](/zh-CN/docs/Web/Privacy/State_Partitioning)）。
```

2024-11-11 08:57 UTC, yin1999 commented on files/zh-cn/web/api/fenced_frame_api/index.md
> +在调用 `runAdAuction()` 时，必须传入 `resolveToConfig: true` 以获得 `FencedFrameConfig` 对象。如果 `resolveToConfig` 设置为 `false`，则所得的 {{jsxref("Promise")}} 将兑现为一个不透明的 [URN](/zh-CN/docs/Web/URI#urns)（例如：`urn:uuid:c369
```suggestion
在调用 `runAdAuction()` 时，必须传入 `resolveToConfig: true` 以获得 `FencedFrameConfig` 对象。如果 `resolveToConfig` 设置为 `false`，则所得的 {{jsxref("Promise")}} 将兑现为一个不透明 [URN](/zh-CN/docs/Web/URI#urns)（例如：`urn:uuid:c36973b5-e5d9-de59-e4c4-364f137b3c7a`），该 URN 只能在 `<iframe>` 中使用。
```

2024-11-11 08:57 UTC, yin1999 commented on files/zh-cn/web/api/fenced_frame_api/index.md
> +> 在 `<iframe>` 中支持不透明的 URN，以便将现有实现轻松迁移到[隐私沙盒](https://developers.google.com/privacy-sandbox)。这种支持是暂时的，随着采用率的提高，未来将会移除。
```suggestion
无论哪种方式，浏览器都会存储一个包含要嵌入内容的目标位置的 URL，该 URL 与不透明 URN 或 `FencedFrameConfig` 的内部 `url` 属性相对应。在嵌入上下文中运行的 JavaScript 无法读取 UR 值。

> [!NOTE]
> 在 `<iframe>` 中支持不透明 URN，以便将现有实现轻松迁移到[隐私沙盒](https://developers.google.com/privacy-sandbox)。这种支持是暂时的，随着采用率的提高，未来将会移除。
```

2024-11-11 08:57 UTC, yin1999 commented on files/zh-cn/web/api/fenced_frame_api/index.md
> +在嵌入到 `<fencedframe>` 中的文档内，JavaScript 可以访问一个 {{domref("Window.fence")}} 属性，此属性为该文档返回一个 {{domref("Fence")}} 实例。此对象包含几个与围栏框架 API 功能特别相关的函数。例如，{{domref("Fence.reportEvent()")}} 提供了一种通过 [beacon](/zh-CN/d
```suggestion
在嵌入到 `<fencedframe>` 中的文档内，JavaScript 可以访问 {{domxref("Window.fence")}} 属性，此属性为该文档返回一个 {{domxref("Fence")}} 实例。此对象包含几个与围栏框架 API 功能特别相关的函数。例如，{{domxref("Fence.reportEvent()")}} 提供了一种通过[信标](/zh-CN/docs/Web/API/Beacon_API)向一个或多个指定的 URL 触发报告数据提交的方式，以便报告广告展示和点击情况。
```

2024-11-11 08:57 UTC, yin1999 commented on files/zh-cn/web/api/fenced_frame_api/index.md
> +只有通过设置在 `<fencedframe>` 上的权限策略，才能启用专门设计为在其中使用的特定功能；在此上下文中，其他受策略控制的功能不可用。参见[围栏框架可用的权限策略](/zh-CN/docs/Web/HTML/Element/fencedframe#围栏框架可用的权限策略)查看更多信息。
```suggestion
只有通过设置在 `<fencedframe>` 上的权限策略，才能启用专门设计为在其中使用的特定功能；在此上下文中，其他受策略控制的特性不可用。参见[围栏框架可用的权限策略](/zh-CN/docs/Web/HTML/Element/fencedframe#围栏框架可用的权限策略)查看更多信息。
```

2024-11-11 08:57 UTC, yin1999 commented on files/zh-cn/web/api/fenced_frame_api/index.md
> +对于从 `<fencedframe>` 内部发出的任何请求，包括嵌入在 `<fencedframe>` 内的子 `<iframe>`，都会设置一个值为 `fencedframe` 的 {{httpheader("Sec-Fetch-Dest")}} 请求头。
```suggestion
对于从 `<fencedframe>` 内部发出的任何请求，包括嵌入在 `<fencedframe>` 内的子 `<iframe>`，都会设置一个值为 `fencedframe` 的 {{httpheader("Sec-Fetch-Dest")}} 标头。
```

2024-11-11 08:57 UTC, yin1999 commented on files/zh-cn/web/api/fenced_frame_api/index.md
> +服务器必须为任何打算加载到 `<fencedframe>` 中或嵌入在 `<fencedframe>` 内的 `<iframe>` 中的文档设置一个值为 `fenced-frame` 的 {{httpheader("Supports-Loading-Mode")}} 响应头。
```suggestion
服务器必须为任何打算加载到 `<fencedframe>` 中或嵌入在 `<fencedframe>` 内的 `<iframe>` 中的文档设置一个值为 `fenced-frame` 的 {{httpheader("Supports-Loading-Mode")}} 响应标头。
```

2024-11-11 08:57 UTC, yin1999 commented on files/zh-cn/web/api/fenced_frame_api/index.md
> +- [用户代理客户端提示](/zh-CN/docs/Web/HTTP/Client_hints#用户代理客户端提示)在封闭框架中不可用，因为它们依赖于[权限策略](/zh-CN/docs/Web/HTTP/Permissions_Policy)委托，这可能会被用来泄露数据。
```suggestion
- [用户代理客户端提示](/zh-CN/docs/Web/HTTP/Client_hints#用户代理客户端提示)在围栏框架中不可用，因为它们依赖于[权限策略](/zh-CN/docs/Web/HTTP/Permissions_Policy)委托，这可能会被用来泄露数据。
```

2024-11-11 08:57 UTC, yin1999 commented on files/zh-cn/web/api/fenced_frame_api/index.md
> +- 对从封闭框架内部打开的新浏览上下文强制执行严格的 [`Cross-Origin-Opener-Policy`](/zh-CN/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy) 设置，否则它们可能会被用来向其他源泄露信息。从封闭框架内部打开的任何新窗口都将设置 [`rel="noopener"`](/zh-CN/docs/Web/HTML/At
```suggestion
- 对从封闭框架内部打开的新浏览上下文强制执行严格的 [`Cross-Origin-Opener-Policy`](/zh-CN/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy) 设置，否则它们可能会被用来向其他源泄露信息。从围栏框架内部打开的任何新窗口都将设置 [`rel="noopener"`](/zh-CN/docs/Web/HTML/Attributes/rel/noopener) 和`Cross-Origin-Opener-Policy: same-origin`，以确保 {{domxref("Window.opener")}} 返回 `null` 并将其置于自己的浏览上下文组中。
```

2024-11-11 08:57 UTC, yin1999 commented on files/zh-cn/web/api/fenced_frame_api/index.md
> +- 为了缓解隐私问题，[`Content-Security-Policy: sandbox`](/zh-CN/docs/Web/HTTP/Headers/Content-Security-Policy/sandbox) 自定义设置不能被围栏框架继承。要使封闭框架加载，需要指定无 `sandbox` CSP（这意味着以下值），或者指定以下沙箱值：
```suggestion
- 为了缓解隐私问题，[`Content-Security-Policy: sandbox`](/zh-CN/docs/Web/HTTP/Headers/Content-Security-Policy/sandbox) 自定义设置不能被围栏框架继承。要加载围栏框架，需要指定无 `sandbox` CSP（这意味着以下值），或者指定以下沙箱值：
```

2024-11-11 08:57 UTC, yin1999 commented on files/zh-cn/web/api/fenced_frame_api/index.md
> +[`beforeunload`](/zh-CN/docs/Web/API/Window/beforeunload_event) 和 [`unload`](/zh-CN/docs/Web/API/Window/unload_event) 事件不能在围栏框架上触发，因为它们可以以页面删除时间戳的形式泄露信息。实施旨在消除尽可能多的潜在泄漏。
```suggestion
[`beforeunload`](/zh-CN/docs/Web/API/Window/beforeunload_event) 和 [`unload`](/zh-CN/docs/Web/API/Window/unload_event) 事件不能在围栏框架上触发，因为它们可以以页面删除时间戳的形式泄露信息。实现旨在消除尽可能多的潜在泄漏。
```

2024-11-11 08:57 UTC, yin1999 commented on files/zh-cn/web/api/fenced_frame_api/index.md
> +某些创建 {{domxref("FencedFrameConfig")}} 的 API 功能，如 {{domxref("Navigator.runAdAuction()")}}（[受保护的受众 API](https://developers.google.com/privacy-sandbox/private-advertising/protected-audience)）和 {{domxref
```suggestion
某些创建 {{domxref("FencedFrameConfig")}} 的 API 特性，如 {{domxref("Navigator.runAdAuction()")}}（[受保护的受众 API](https://developers.google.com/privacy-sandbox/private-advertising/protected-audience)）和 {{domxref("WindowSharedStorage.selectURL()")}}（[共享存储 API](/zh-CN/docs/Web/API/Shared_Storage_API)），以及其他特性如 {{domxref("Fence.reportEvent()")}}，要求你将你的网站注册到[隐私沙盒注册流程](/zh-CN/docs/Web/Privacy/Privacy_sandbox/Enrollment)中。如果你不注册，API 调用将失败，并在控制台中显示警告。
```

2024-11-11 08:57 UTC, yin1999 commented on files/zh-cn/web/api/fenced_frame_api/index.md
> +> 在 Chrome 中，你仍然可以在未注册情况下本地测试你的围栏框架代码。为了允许本地测试，请启用以下 Chrome 开发者标志：
```suggestion
> 在 Chrome 中，你仍然可以在未注册情况下本地测试你的围栏框架代码。要允许本地测试，请启用以下 Chrome 开发者标志：
```

2024-11-11 08:57 UTC, yin1999 commented on files/zh-cn/web/api/fenced_frame_api/index.md
> +- [隐私沙盒](https://developers.google.com/privacy-sandbox)
```suggestion
- developers.google.com 上的[围栏框架](https://developers.google.com/privacy-sandbox/private-advertising/fenced-frame)
- developers.google.com 上的[隐私沙盒](https://developers.google.com/privacy-sandbox)
```

2024-11-13 00:54 UTC, yin1999 approved these changes
Thank you @fuchunhui

2024-11-13 00:54 UTC, merged