[ru]: <style> - tag docs sync
mdn/translated-content pull request #24406
Opened 2024-11-08 20:19 UTC by sedlukha

### Description

[ru]: <style> - tag docs sync

[original](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style)

2024-11-08 22:11 UTC, leon-win commented
@sedlukha , пожалуйста, обрати внимание на исправления, предложенные ботом `mdn-linter`, они все актуальные.

И давай делать заголовки и описания PR`ов, как я написал в #24391.

Это кстати касается всех других PR`ов =)

2024-11-09 06:00 UTC, sedlukha commented
@leon-win Во всех PR я добавлял ссылки на `ru`, только если страница имеет перевод. В остальных случаях указывал `en-us`. Я ориентировался на подход, который использовался в текущих версиях переводов.

Я посмотрел твои пулреквесты и заметил, что ты везде ведешь на `ru`, даже если перевода нет.

У меня есть два вопроса:

1. Существует ли в документации инструкция о том, как задавать ссылки в переводах? Если ее нет, давай добавим.
2. Предлагаю пройтись по всем текущим файлам переводов и унифицировать ссылки, чтобы они вели на ru. Что думаешь? Готов это взять на себя

2024-11-15 21:36 UTC, leon-win commented
Привет, @sedlukha !

1. Я посмотрел и действительно не нашёл прямого указания всегда делать ссылки локализованными. Точнее нашёл только в китайской документации) Поэтому добавил в #24518. Логика простая: если перевод есть, то это будет ссылка на него, если перевода нет, то сработает редирект на английскую версию. А нужно это для того, чтобы не следить за ссылками и не исправлять каждый раз, когда появляется перевод (это было бы слишком трудоёмко).
2. На мой взгляд в этом острой необходимости нет. Можно исправлять при актуализации перевода конкретных документов. Я обычно так всегда и делаю.

2024-11-15 22:44 UTC, leon-win requested changes
Внёс предложения по улушчению перевода.

Общием моменты, на которые следует обратить внимание (здесь и в других PR'ах):
* правила русского языка отличаются от английского, поэтмоу и знаки препинания нужно тоже заменять (например. в английском часто используют точки с запятыми или тире не так, как можн оиспользовать в русском),
* единый стиль перевода. Например, если используешь "медиавыражение", то во всём документе, а в идеале и во всех документах))

2024-11-15 22:44 UTC, leon-win commented on files/ru/web/html/element/style/index.md
> +  - : Этот атрибут явно указывает, что определённые операции должны быть заблокированы до получения критических подресурсов. Стили, импортированные с помощью [`@import`](/ru/docs/Web/CSS/@import), об
```suggestion
  - : Этот атрибут явно указывает, что некоторые действия должны быть заблокированы до получения необходимых ресурсов. Стили, импортированные с помощью [`@import`](/ru/docs/Web/CSS/@import), обычно считаются критическими ресурсами, в то время как [`background-image`](/ru/docs/Web/CSS/background-image) и шрифты — нет. Блокируемые действия указываются в виде списка ключевых слов, разделённого пробелами. Допустимые значения:
```

2024-11-15 22:44 UTC, leon-win commented on files/ru/web/html/element/style/index.md
> +  - : Этот атрибут определяет, к какому виду медиа должен применяться этот стиль. Значением этого атрибута является [медиавыражение](/ru/docs/Web/CSS/CSS_media_queries/Using_media_queries), которое п
```suggestion
  - : Этот атрибут определяет, к какому виду медиа должен применяться стиль. Значением этого атрибута является [медиавыражение](/ru/docs/Web/CSS/CSS_media_queries/Using_media_queries), которое по умолчанию соответствует `all`.
```

2024-11-15 22:44 UTC, leon-win commented on files/ru/web/html/element/style/index.md
> +  - : Криптографический одноразовый номер, используемый для разрешения встроенных стилей в [политике Content-Security-Policy для style-src](/ru/docs/Web/HTTP/Headers/Content-Security-Policy/style-src
```suggestion
  - : Криптографический одноразовый номер, используемый для разрешения применения встроенных стилей с помощью [директивы style-src](/ru/docs/Web/HTTP/Headers/Content-Security-Policy/style-src) политики Content-Security-Policy. Сервер должен генерировать это значение каждый раз, когда отправляет заголовок. Важно предоставлять такое значение, которое невозможно угадать, так как в противном случае обойти политику ресурса будет достаточно просто.
```

2024-11-15 22:44 UTC, leon-win commented on files/ru/web/html/element/style/index.md
> +  - : Этот атрибут не должен быть указан: если он указан, допустимыми значениями являются только пустая строка или регистронезависимое значение `text/css`.
```suggestion
  - : Этот атрибут не следует устанавливать, но если он указан, то допустимыми значениями являются только пустая строка или регистронезависимое значение `text/css`.
```

2024-11-15 22:44 UTC, leon-win commented on files/ru/web/html/element/style/index.md
> +### Несколько элементов стиля
```suggestion
### Несколько элементов `style`
```

2024-11-15 22:44 UTC, leon-win commented on files/ru/web/html/element/style/index.md
> +В этом примере мы включили два элемента `<style>` — обратите внимание, как конфликтующие декларации в последнем элементе `<style>` перекрывают те, что были в предыдущем, если у них одинаковая [специф
```suggestion
В этом примере мы добавили два элемента `<style>`, обратите внимание, как конфликтующие объявления стилей в последнем элементе `<style>` перекрывают те, что были в предыдущем, если у них одинаковая [специфичность](/ru/docs/Web/CSS/Specificity).
```

2024-11-15 22:44 UTC, leon-win commented on files/ru/web/html/element/style/index.md
> +### Включение медиа-запроса
```suggestion
### Включение медиавыражения
```

2024-11-15 22:44 UTC, leon-win commented on files/ru/web/html/element/style/index.md
> +В этом примере мы добавляем к предыдущему медиа-запрос, включив атрибут `media` во второй элемент `<style>`, чтобы он применялся только при ширине области просмотра менее 500px.
```suggestion
В этом примере мы добавили медиавыражение с помощью атрибута `media` во втором элементе `<style>`, чтобы он применялся только при ширине области просмотра менее 500px.
```

2024-11-15 22:44 UTC, leon-win commented on files/ru/web/html/element/style/index.md
> +      <td>Ни один из тегов не может быть опущен.</td>
```suggestion
      <td>Ни один из тегов не может быть пропущен.</td>
```

2024-11-22 16:37 UTC, sedlukha commented on files/ru/web/html/element/style/index.md
> +  - : Этот атрибут явно указывает, что определённые операции должны быть заблокированы до получения критических подресурсов. Стили, импортированные с помощью [`@import`](/ru/docs/Web/CSS/@import), об
@leon-win 
> ... заблокированы до получения **необходимых** ресурсов. Стили, импортированные с помощью `@import`, обычно считаются **критическими** ресурсами ...


Кажется тут надо выбрать что-то одно. В одном предложении ресурсы _"необходимые"_, а уже в следующем они же стали _"критические"_

2024-11-22 17:03 UTC, sedlukha commented
> Внёс предложения по улушчению перевода.
> 
> Общие моменты, на которые следует обратить внимание (здесь и в других PR'ах):
> 
> * Правила русского языка отличаются от английского, поэтому и знаки препинания нужно тоже заменять (например, в английском часто используют точку с запятой или тире не так, как можно использовать в русском),
> * Единый стиль перевода. Например, если используешь "медиавыражение", то во всём документе, а в идеале и во всех документах, конечно))
> * Предлагаю сделать упор на качество, а не на количество. То есть вычитывать каждый абзац текста и весь документ в целом перед созданием PR'а. Ревью занимает очень много времени, поэтому лучше сделать меньше PR'ов, но более качественных.

 @leon-win  
Спасибо за замечания и советы!

Я стараюсь придерживаться оригинала максимально близко и избегать вольностей, чтобы в будущем было проще обновлять перевод, если оригинал изменится.

Признаю, что пока перевожу, скорее, на интуитиве, и без подробных рекомендаций тяжело понять, каким должен быть идеальный перевод. Именно поэтому я и решил начать с простых страниц по html, чтобы разобраться. 

Если на основе моих ошибок у тебя получится дополнить рекомендации по переводу — будет здорово! Это точно поможет всем, кто хочет заниматься переводом, и упростит ревью.

2024-11-22 19:40 UTC, leon-win commented on files/ru/web/html/element/style/index.md
> +  - : Этот атрибут явно указывает, что определённые операции должны быть заблокированы до получения критических подресурсов. Стили, импортированные с помощью [`@import`](/ru/docs/Web/CSS/@import), об
Здесь как раз хорошо получается, два разных слова, но с одним смыслом. Это помогает избежать стилистической ошибки немотивированного повторения (https://licey.net/free/4-russkii_yazyk/41-kurs_russkogo_yazyka_russkii_yazyk_i_kultura_obscheniya/stages/795-56_stilisticheskie_oshibki_i_ih_tipy.html).
И не столь важно, что в оригинале используется одно и то же слово. Правила в разных языках отличаются. При переводе на русский язык нужно соблюдать правила русского языка и не допускать ошибок, в том числе стилистических.

2024-11-22 20:00 UTC, sedlukha commented on files/ru/web/html/element/style/index.md
> +  - : Этот атрибут явно указывает, что определённые операции должны быть заблокированы до получения критических подресурсов. Стили, импортированные с помощью [`@import`](/ru/docs/Web/CSS/@import), об
как скажешь. придется мне прокачивать русский)

2024-11-22 20:01 UTC, sedlukha commented
принял все предложения по улучшению. спасибо, @leon-win

2024-11-22 20:07 UTC, leon-win commented
> Я стараюсь придерживаться оригинала максимально близко и избегать вольностей, чтобы в будущем было проще обновлять перевод, если оригинал изменится.

"Вольностей" действительно допускать не следует, но задача перевода -- донести смысл, а не набор переведённых слов. С последим оегко справляется робот) Собственно поэтому в MDN и используется ручной перевод, это долго и трудно, но качество выше.

Нужно подбирать формулировки, которые не содержат ошибок (грамматических и стилистических) и наиболее соответсвуют русской технической литературе. Стиль при этом может отличаться от оригинала.

> Признаю, что пока перевожу, скорее, на интуитиве, и без подробных рекомендаций тяжело понять, каким должен быть идеальный перевод. Именно поэтому я и решил начать с простых страниц по html, чтобы разобраться.

Подробные рекомендации сформулировать довольно сложно. Но главное, к чему я призываю (уже писал в другом PR, повторю): сделать упор на качество, а не на количество. Довести до идеала уже созданные PR, завершить и влить их, потом браться за другие. Эти уже созданные нужно перечиать ещё раз, с учётом того, что я написал выше (цель -- доности смысл, а не переод отдельных слов).

> Если на основе моих ошибок у тебя получится дополнить рекомендации по переводу — будет здорово! Это точно поможет всем, кто хочет заниматься переводом, и упростит ревью.

Пункт про перевод ссылок уже добавил)
Может и ещё что-то получится, посмотрим.

2024-11-22 20:12 UTC, leon-win approved these changes

2024-11-22 20:14 UTC, merged