zh-CN: update `AudioContext.createScriptProcessor()`
mdn/translated-content pull request #24436
Opened 2024-11-10 08:52 UTC by PassionPenguin

fixes #24431

2024-11-10 12:19 UTC, yin1999 requested changes
没更新标题，定义列表的格式也不对（无法正确渲染）

2024-11-10 19:53 UTC, skyclouds2001 commented on files/zh-cn/web/api/baseaudiocontext/createscriptprocessor/index.md
>  ### 返回
```suggestion
### 返回值
```

2024-11-11 06:51 UTC, PassionPenguin commented on files/zh-cn/web/api/baseaudiocontext/createscriptprocessor/index.md
>  ### 返回
蟹蟹！

2024-11-11 14:19 UTC, yin1999 reviewed
目前还有标点符号的使用问题，代码块中的注释也需要翻译一下

2024-11-12 02:26 UTC, PassionPenguin commented
> 目前还有标点符号的使用问题，代码块中的注释也需要翻译一下

2. codeblock里面的代码是对应仓库的，记得你说过这种不要翻译避免与仓库代码对不上？

2024-11-12 06:45 UTC, yin1999 commented
> > 目前还有标点符号的使用问题，代码块中的注释也需要翻译一下
> 
> 2. codeblock里面的代码是对应仓库的，记得你说过这种不要翻译避免与仓库代码对不上？

我们之前说的是注释都是可以翻译的，只是如果代码的内容在本地化以后会和在线示例对不上（输出的内容不一致），那么这些会导致不一致的内容不应该被本地化。

2024-11-13 02:45 UTC, PassionPenguin commented
> > > 目前还有标点符号的使用问题，代码块中的注释也需要翻译一下
> > 
> > 
> > 
> > 2. codeblock里面的代码是对应仓库的，记得你说过这种不要翻译避免与仓库代码对不上？
> 
> 我们之前说的是注释都是可以翻译的，只是如果代码的内容在本地化以后会和在线示例对不上（输出的内容不一致），那么这些会导致不一致的内容不应该被本地化。

欧

2024-11-15 05:50 UTC, yin1999 approved these changes
文档对照翻译请仔细一点。缺了一部分内容，我补上了。

2024-11-15 05:50 UTC, merged