[zh-cn]: update the translation of HTML <iframe> element
mdn/translated-content pull request #24506
Opened 2024-11-14 11:50 UTC by Yuhanawa

### Description
update the translation of HTML <iframe> element (Web/HTML/Element/iframe)

### Motivation

### Additional details

### Related issues and pull requests

2024-11-15 01:23 UTC, T34-active reviewed
fix format.

2024-11-15 01:23 UTC, T34-active commented on files/zh-cn/web/html/element/iframe/index.md
>  title: <iframe>
```suggestion
title: <iframe>：內嵌框架元素
```

2024-11-15 01:23 UTC, T34-active commented on files/zh-cn/web/html/element/iframe/index.md
> +  - : 用于为`<iframe>`指定其[特征策略](/zh-CN/docs/Web/HTTP/Permissions_Policy)。该策略根据请求的来源规定`<iframe>`可以使用哪些功能（例如，访问麦克风、摄像头、电池、web-share 等）
```suggestion
  - : 用于为 `<iframe>` 指定其[权限策略](/zh-CN/docs/Web/HTTP/Permissions_Policy)。该策略根据请求的来源规定 `<iframe>` 可以使用哪些功能（例如，访问麦克风、摄像头、电池、web-share 等）
```

2024-11-15 01:23 UTC, T34-active commented on files/zh-cn/web/html/element/iframe/index.md
> +    示例请参见 `Permissions-Policy` 中的[iframes](/zh-CN/docs/Web/HTTP/Headers/Permissions-Policy#iframes)
```suggestion
    示例请参见 `Permissions-Policy` 中的 [iframes](/zh-CN/docs/Web/HTTP/Headers/Permissions-Policy#iframes)
```

2024-11-15 01:23 UTC, T34-active commented on files/zh-cn/web/html/element/iframe/index.md
> +  - : 一个布尔属性，如果存在，则指定当前用户选定的主题应该与`<iframe>`源的请求一起发送。更多信息请参见 [Using the Topics API](/zh-CN/docs/Web/API/Topics_API/Using)
```suggestion
  - : 一个布尔属性，如果存在，则指定当前用户选定的主题应该与 `<iframe>` 源的请求一起发送。更多信息请参见[使用 Topics API](/zh-CN/docs/Web/API/Topics_API/Using)
```

2024-11-15 01:23 UTC, T34-active commented on files/zh-cn/web/html/element/iframe/index.md
>      > 这是一个历史遗留属性，已经被重新定义为 `allow="payment"`.
```suggestion
    > 这是一个历史遗留属性，已经被重新定义为 `allow="payment"`。
```

2024-11-15 01:23 UTC, T34-active commented on files/zh-cn/web/html/element/iframe/index.md
> +      - : 在页面加载时立即加载 iframe (默认值)
```suggestion
      - : 在页面加载时立即加载 iframe（默认值）
```

2024-11-15 01:23 UTC, T34-active commented on files/zh-cn/web/html/element/iframe/index.md
> +  - : 表示浏览器应当何时加载 iframe:
```suggestion
  - : 表示浏览器应当何时加载 iframe：
```

2024-11-15 01:23 UTC, T34-active commented on files/zh-cn/web/html/element/iframe/index.md
>    - : 以 CSS 像素格式，或像素格式，或百分比格式指定 frame 的高度。默认值为`150`。
```suggestion
  - : 以 CSS 像素格式，或像素格式，或百分比格式指定 frame 的高度。默认值为 `150`。
```

2024-11-15 01:23 UTC, T34-active commented on files/zh-cn/web/html/element/iframe/index.md
> +      - : 推迟 iframe 的加载，直到达到浏览器定义的 {{glossary("visual viewport")}} 的距离
```suggestion
      - : 推迟 iframe 的加载，直到达到浏览器定义的{{glossary("visual viewport", "可视视口")}}的距离
```

2024-11-15 01:23 UTC, T34-active commented on files/zh-cn/web/html/element/iframe/index.md
> +    - `origin`: referrer 首部中仅包含来源页面的源。换言之，仅包含来源页面的 [scheme](/zh-CN/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL), {{Glossary("host")}}, 以及 {{Glossary("port")}}。
```suggestion
    - `origin`: referrer 标头中仅包含来源页面的源。换言之，仅包含来源页面的 [scheme](/zh-CN/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL)，{{Glossary("host", "主机")}}以及 {{Glossary("port", "端口")}}。
```

2024-11-15 01:23 UTC, T34-active commented on files/zh-cn/web/html/element/iframe/index.md
> +    - `unsafe-url`: 始终在 referrer 首部中包含源以及路径（但不包括 [fragment](/zh-CN/docs/Web/API/HTMLAnchorElement/hash)，[密码](/zh-CN/docs/Web/API/HTMLAnchorElement/password)，或[用户名](/zh-CN/docs/Web/API/HTMLAnchorEleme
```suggestion
    - `unsafe-url`: 始终在 referrer 标头中包含源以及路径（但不包括 [fragment](/zh-CN/docs/Web/API/HTMLAnchorElement/hash)，[密码](/zh-CN/docs/Web/API/HTMLAnchorElement/password)，或[用户名](/zh-CN/docs/Web/API/HTMLAnchorElement/username)）。**这个值是不安全的**，因为这样做会暴露受 TLS 保护的资源的源和路径信息。
```

2024-11-15 01:23 UTC, T34-active commented on files/zh-cn/web/html/element/iframe/index.md
> +      <th scope="row">DOM interface</th>
```suggestion
      <th scope="row">DOM 接口</th>
```

2024-11-15 01:23 UTC, T34-active commented on files/zh-cn/web/html/element/iframe/index.md
> +      </td>
```suggestion
      <th scope="row">隐含的 ARIA 角色</th>
      <td>
        <a href="https://www.w3.org/TR/html-aria/#dfn-no-corresponding-role"
          >没有对应的角色</a
        >
      </td>
```

2024-11-15 01:23 UTC, T34-active commented on files/zh-cn/web/html/element/iframe/index.md
> +      </td>
```suggestion
      <td>
        <a href="/zh-CN/docs/Web/HTML/Content_categories#flow_content"
          >流式内容</a
        >,
        <a href="/zh-CN/docs/Web/HTML/Content_categories#phrasing_content"
          >短语内容</a
        >、嵌入内容、交互内容、可感知内容。
      </td>
```

2024-11-15 01:23 UTC, T34-active commented on files/zh-cn/web/html/element/iframe/index.md
> +      </td>
```suggestion
      <th scope="row">允许的 ARIA 角色</th>
      <td>
        <a href="/zh-CN/docs/Web/Accessibility/ARIA/Roles/application_role"><code>application</code></a>、<a href="/zh-CN/docs/Web/Accessibility/ARIA/Roles/document_role"><code>document</code></a>、<a href="/zh-CN/docs/Web/Accessibility/ARIA/Roles/img_role"><code>img</code></a>、<a href="/zh-CN/docs/Web/Accessibility/ARIA/Roles/none_role"><code>none</code></a>、<a href="/zh-CN/docs/Web/Accessibility/ARIA/Roles/presentation_role"><code>presentation</code></a>
      </td>
```

2024-11-15 01:23 UTC, T34-active commented on files/zh-cn/web/html/element/iframe/index.md
> +- [Privacy, permissions, and information security](/zh-CN/docs/Web/Privacy)
```suggestion
- [隐私、权限和信息安全](/zh-CN/docs/Web/Privacy)
```

2024-11-15 01:23 UTC, T34-active commented on files/zh-cn/web/html/element/iframe/index.md
> +请注意在使用 `srcdoc`时，在嵌入内容中的任何相对 URL 都将会相对于嵌入该内容的页面的 URL 进行解析，如果你想要使用锚链接指向嵌入内容，你需要明确使用 `about:srcdoc` 作为基准 URL。
```suggestion
请注意在使用 `srcdoc` 时，在嵌入内容中的任何相对 URL 都将会相对于嵌入该内容的页面的 URL 进行解析，如果你想要使用锚链接指向嵌入内容，你需要明确使用 `about:srcdoc` 作为基准 URL。
```

2024-11-15 06:18 UTC, Yuhanawa commented
我有个疑问: 在`zh-CN/docs/Web/HTTP/Headers`中`header`被翻译为了`标头`，在`zh-CN/docs/Web/API/HTMLAnchorElement/referrerPolicy`中`header`被翻译为了`请求头`，这此文件中`header`却被之前的人翻译为了`首部`？这是否应当更改

2024-11-15 06:21 UTC, T34-active commented
> 我有个疑问: 在`zh-CN/docs/Web/HTTP/Headers`中`header`被翻译为了`标头`，在`zh-CN/docs/Web/API/HTMLAnchorElement/referrerPolicy`中`header`被翻译为了`请求头`，这此文件中`header`却被之前的人翻译为了`首部`？这是否应当更改

这部分需要修改，在[术语表](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/glossary.md)中有写出。

2024-11-15 21:40 UTC, skyclouds2001 commented on files/zh-cn/web/html/element/iframe/index.md
> +  - : 用于为 `<iframe>` 指定其[权限策略](/zh-CN/docs/Web/HTTP/Permissions_Policy)。该策略根据请求的来源规定 `<iframe>` 可以使用哪些功能（例如，访问麦克风、摄像头、电池、web-share 等）
```suggestion
  - : 用于为 `<iframe>` 指定其[权限策略](/zh-CN/docs/Web/HTTP/Permissions_Policy)。该策略根据请求的来源规定 `<iframe>` 可以使用哪些功能（例如，访问麦克风、摄像头、电池、web 共享等）
```

2024-11-15 21:59 UTC, skyclouds2001 commented on files/zh-cn/web/html/element/iframe/index.md
> +  - : 用于为 `<iframe>` 指定其[权限策略](/zh-CN/docs/Web/HTTP/Permissions_Policy)。该策略根据请求的来源规定 `<iframe>` 可以使用哪些功能（例如，访问麦克风、摄像头、电池、web-share 等）
```suggestion
  - : 用于为 `<iframe>` 指定其[权限策略](/zh-CN/docs/Web/HTTP/Permissions_Policy)。该策略根据请求的来源规定 `<iframe>` 可以使用哪些功能（例如，访问麦克风、摄像头、电池、web 共享等）
```

2024-11-15 21:59 UTC, skyclouds2001 commented on files/zh-cn/web/html/element/iframe/index.md
>    - : 设置为`true`时，可以通过调用 `<iframe>` 的 {{domxref("Element.requestFullscreen", "requestFullscreen()")}} 方法激活全屏模式。
```suggestion
  - : 设置为 `true` 时，可以通过调用 `<iframe>` 的 {{domxref("Element.requestFullscreen", "requestFullscreen()")}} 方法激活全屏模式。
```


之前翻译的并非也请一并修改一下

2024-11-15 21:59 UTC, skyclouds2001 commented on files/zh-cn/web/html/element/iframe/index.md
> +  - : 设置为 `true` 可以将 `<iframe>` 设为无凭据模式，这意味着将内容加载到新的临时上下文中。它无法访问与其源相关的网络，cookie 和存储数据。它使用一个新的 top-level document 生命周期的本地上下文，作为补偿，可以解除 {{httpheader("Cross-Origin-Embedder-Policy")}} (COEP) 嵌入规则的限制，所以设
```suggestion
  - : 设置为 `true` 可以将 `<iframe>` 设为无凭据模式，这意味着将内容加载到新的临时上下文中。它无法访问与其源相关的网络，cookie 和存储数据。它使用一个新的顶层文档的生命周期的本地上下文，作为补偿，可以解除 {{httpheader("Cross-Origin-Embedder-Policy")}}（COEP）嵌入规则的限制，所以设置了 COEP 的文档可以嵌入未设置的第三方文档。更多信息请参见 [IFrame 无凭据模式](/zh-CN/docs/Web/Security/IFrame_credentialless)。
```

2024-11-15 21:59 UTC, skyclouds2001 commented on files/zh-cn/web/html/element/iframe/index.md
>    - : 设置为`true`时，跨域的 `<iframe>` 就可以调用 [Payment Request API](/zh-CN/docs/Web/API/Payment_Request_API)。
```suggestion
  - : 设置为 `true` 时，跨域的 `<iframe>` 就可以调用 [Payment Request API](/zh-CN/docs/Web/API/Payment_Request_API)。
```

2024-11-15 21:59 UTC, skyclouds2001 commented on files/zh-cn/web/html/element/iframe/index.md
> +    示例请参见 `Permissions-Policy` 中的 [iframes](/zh-CN/docs/Web/HTTP/Headers/Permissions-Policy#iframes)
```suggestion
    示例请参见 `Permissions-Policy` 中的 [iframe](/zh-CN/docs/Web/HTTP/Headers/Permissions-Policy#iframes)
```

2024-11-15 21:59 UTC, skyclouds2001 commented on files/zh-cn/web/html/element/iframe/index.md
> +      - : 在页面加载时立即加载 iframe（默认值）
```suggestion
      - : 在页面加载时立即加载 iframe（默认值）。
```

2024-11-15 21:59 UTC, skyclouds2001 commented on files/zh-cn/web/html/element/iframe/index.md
> +        这改进了在大多数使用场景中的性能表现，尤其是减少了页面的首次加载时间
```suggestion
      - : 推迟 iframe 的加载，直到达到浏览器定义的{{glossary("visual viewport", "可视视口")}}的距离，目的是在浏览器确定需要它前，避免占用获取 frame 所需的网络和存储带宽，这改进了在大多数使用场景中的性能表现，尤其是减少了页面的首次加载时间
```

原则上段内不换行，参见 https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md?plain=1#L147-L167

2024-11-15 21:59 UTC, skyclouds2001 commented on files/zh-cn/web/html/element/iframe/index.md
> +        > 这是一个反跟踪措施。
```suggestion
        > [!NOTE]
        > 只有当 JavaScript 启用时才会推迟加载。这是一个反跟踪措施。
```

2024-11-15 21:59 UTC, skyclouds2001 commented on files/zh-cn/web/html/element/iframe/index.md
> +  - : 表示在获取 iframe 资源时如何发送 [referrer](/zh-CN/docs/Web/API/Document/referrer) 标头：
```suggestion
  - : 表示在获取 iframe 资源时发送哪个 [referrer](/zh-CN/docs/Web/API/Document/referrer)：
```

原文：

> Indicates which referrer to send when fetching the frame's resource:

2024-11-15 21:59 UTC, skyclouds2001 commented on files/zh-cn/web/html/element/iframe/index.md
> +    - `no-referrer-when-downgrade` (default): 向不受 {{Glossary("TLS")}} ({{Glossary("HTTPS")}}) 保护的 {{Glossary("origin")}} 发送请求时，不发送 {{HTTPHeader("Referer")}} 标头。
```suggestion
    - `no-referrer-when-downgrade`: 向不受 {{Glossary("TLS")}} ({{Glossary("HTTPS")}}) 保护的 {{Glossary("origin")}} 发送请求时，不发送 {{HTTPHeader("Referer")}} 标头。
```

参考英文原文，默认值已经修改了

2024-11-15 21:59 UTC, skyclouds2001 commented on files/zh-cn/web/html/element/iframe/index.md
> +    - `unsafe-url`: 始终在 referrer 标头中包含源以及路径（但不包括 [fragment](/zh-CN/docs/Web/API/HTMLAnchorElement/hash)，[密码](/zh-CN/docs/Web/API/HTMLAnchorElement/password)，或[用户名](/zh-CN/docs/Web/API/HTMLAnchorEleme
这一整块请对照原文修正一下格式

2024-11-15 21:59 UTC, skyclouds2001 commented on files/zh-cn/web/html/element/iframe/index.md
> +    - `origin`: referrer 标头中仅包含来源页面的源。换言之，仅包含来源页面的 [scheme](/zh-CN/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL)，{{Glossary("host", "主机")}}以及 {{Glossary("port", "端口")}}。
```suggestion
    - `origin`: referrer 标头中仅包含来源页面的源。换言之，仅包含来源页面的[协议](/zh-CN/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL)，{{Glossary("host", "主机")}}以及 {{Glossary("port", "端口")}}。
```

2024-11-15 21:59 UTC, skyclouds2001 commented on files/zh-cn/web/html/element/iframe/index.md
> +- [CSP: frame-ancestors](/zh-CN/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors)
```suggestion
- [CSP：frame-ancestors](/zh-CN/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors)
```

2024-11-15 21:59 UTC, skyclouds2001 commented on files/zh-cn/web/html/element/iframe/index.md
> +      - : 允许导航到浏览器内置的或[registered by a website](/zh-CN/docs/Web/API/Navigator/registerProtocolHandler)的 非`http` 协议页面，此功能也可以同 `allow-popups` 或 `allow-top-navigation` 关键词激活。
与原文格式也不一致

2024-11-15 21:59 UTC, skyclouds2001 commented on files/zh-cn/web/html/element/iframe/index.md
>    - : 以 CSS 像素格式，或以像素格式，或以百分比格式指定的 frame 的宽度。默认值是`300`。
```suggestion
  - : 以 CSS 像素格式，或以像素格式，或以百分比格式指定的 frame 的宽度。默认值是 `300`。
```

2024-11-18 02:36 UTC, yin1999 requested changes
给出了一些常见错误的说明。请全文检查并更正

2024-11-18 02:36 UTC, yin1999 commented on files/zh-cn/web/html/element/iframe/index.md
> +  sourceCommit: f98675af9d0a80f33d7875c48cfdb41f71ed1de9
如果要添加 `l10n.sourceCommit`，请确保文档的所有内容都与英文文档同步了，且文档没有排版问题。请再检查以下全文的翻译（比如第 10 行的内容，目前与英文文档是存在差异的；第 14 行的括括号不对，`[DOM 树]` 前缺少空格）。

2024-11-18 02:36 UTC, yin1999 commented on files/zh-cn/web/html/element/iframe/index.md
> +    示例请参见 `Permissions-Policy` 中的 [iframe](/zh-CN/docs/Web/HTTP/Headers/Permissions-Policy#iframes)。
```suggestion
    示例请参见 `Permissions-Policy` 中的 [iframe](/zh-CN/docs/Web/HTTP/Headers/Permissions-Policy#iframe)。
```

2024-11-18 02:36 UTC, yin1999 commented on files/zh-cn/web/html/element/iframe/index.md
> +  - : 用于为 `<iframe>` 指定其[权限策略](/zh-CN/docs/Web/HTTP/Permissions_Policy)。该策略根据请求的来源规定 `<iframe>` 可以使用哪些功能（例如，访问麦克风、摄像头、电池、web 共享等）。
feature => 特性

```suggestion
  - : 用于为 `<iframe>` 指定其[权限策略](/zh-CN/docs/Web/HTTP/Permissions_Policy)。该策略根据请求的来源规定 `<iframe>` 可以使用哪些特性（例如，访问麦克风、摄像头、电池、web 共享等）。
```

2024-11-18 02:36 UTC, yin1999 commented on files/zh-cn/web/html/element/iframe/index.md
> +  - > [!NOTE]
请注意检查预览页面，这一行内容影响到渲染了。

![image](https://github.com/user-attachments/assets/188ce449-30d2-4217-ba2b-5dc20c4daecb)

```suggestion

    > [!NOTE]
```

2024-11-18 02:36 UTC, yin1999 commented on files/zh-cn/web/html/element/iframe/index.md
> +      - : 如果没有使用该关键字，嵌入的浏览上下文将被视为来自一个独立的源，这将使 {{Glossary("same-origin policy")}} 同源检查失败。（可以防御对 [数据存储/ cookie](/zh-CN/docs/Web/Security/Same-origin_policy#cross-origin_data_storage_access) 潜在访问，以及一些 J
中文间无空格（“防御对”和“数据存储”之间不应有空格）。请参见[站内链接翻译](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md#%E7%AB%99%E5%86%85%E9%93%BE%E6%8E%A5%E7%BF%BB%E8%AF%91)

2024-11-18 02:36 UTC, yin1999 commented on files/zh-cn/web/html/element/iframe/index.md
> +{{ EmbedLiveSample('A_simple_iframe', 640,400)}}
第一个参数之前是对的，不要改错了。参见[翻译指南中给出的有关“运行实例”宏的说明](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md#%E7%BF%BB%E8%AF%91%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81%E5%9D%97)

2024-11-18 02:36 UTC, yin1999 commented on files/zh-cn/web/html/element/iframe/index.md
> +{{ EmbedLiveSample('Embedding_source_code_in_an_iframe', 640, 300)}}
同上，请改正

2024-11-18 02:36 UTC, yin1999 commented on files/zh-cn/web/html/element/iframe/index.md
> +- 替换所有的双引号 (`"`) 为 `&quot;`以防止 `srcdoc` 属性被提前终止。(如果你使用 `'`, 那么你应该将 `'` 替换为 `&apos;`). 这个步骤在上一个步骤后执行，所以 `&quot;` 不会变成 `&amp;quot;`.
括号和句号的使用都有问题

2024-11-19 12:20 UTC, yin1999 approved these changes
常见的一些错误，下次请注意。这次我统一更新了（因为问题有一些多，很多地方还是没有同步翻译）

2024-11-19 12:30 UTC, merged