[zh-cn]Detailed notes on adding function backdrop-filter
mdn/translated-content pull request #24509
Opened 2024-11-15 02:29 UTC by KazeLiu

添加函数滤镜的详细注释

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-11-15 03:38 UTC, T34-active reviewed
nits

2024-11-15 03:38 UTC, T34-active commented on files/zh-cn/web/css/backdrop-filter/index.md
> +/* 旋转背景色调，值为角度*/
```suggestion
/* 旋转背景色调，值为角度 */
```

2024-11-15 05:48 UTC, yin1999 requested changes
相关的函数及其值的详细用法应该在“值”部分给出，而不是添加注释。因为注释本身并不能说明细节。如果你想完善该文档，请对照[英文文档](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter#values)，完善“值”部分。

2024-12-06 07:44 UTC, jasonren0403 submitted a review, later dismissed
同 @yin1999 的意见，建议改为更新本文档的“值”章节，其中的每个链接指向了这些函数的用法文档

2024-12-06 09:48 UTC, KazeLiu commented
> 相关的函数及其值的详细用法应该在“值”部分给出，而不是添加注释。因为注释本身并不能说明细节。如果你想完善该文档，请对照[英文文档](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter#values)，完善“值”部分。

要得 我下周改

2024-12-18 13:22 UTC, yin1999 commented
我先转草稿了，改好以后再将当前 PR 标记为可供审查。

2025-03-06 09:31 UTC, jasonren0403 commented on files/zh-cn/web/css/backdrop-filter/index.md
>  - `<filter-function-list>`
```suggestion
- `<filter-value-list>`
```

2025-03-06 13:31 UTC, yin1999 approved these changes
Thank you @KazeLiu and @jasonren0403

2025-03-06 13:33 UTC, merged