zh-cn: update "language overview"
mdn/translated-content pull request #24535
Opened 2024-11-16 14:23 UTC by familyboat

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-11-18 03:04 UTC, yin1999 commented on files/zh-cn/web/javascript/language_overview/index.md
> +运行时、或者宿主，将数据反馈给 JavaScript 引擎（解释器）、提供额外的全局属性、为引擎提供钩子与外部世界交互。模块解析、读取数据、打印消息、发送网络请求等都是运行时级别的操作。自诞生以来，JavaScript 已被各种环境所采用。，例如，浏览器（其提供诸如 [DOM](/zh-CN/docs/Web/API/Document_Object_Model) 这样的 API），Node.js
检查一下标点，这里的标点使用错误至少有两处。还有空格问题

2024-11-18 05:36 UTC, familyboat commented on files/zh-cn/web/javascript/language_overview/index.md
> +运行时、或者宿主，将数据反馈给 JavaScript 引擎（解释器）、提供额外的全局属性、为引擎提供钩子与外部世界交互。模块解析、读取数据、打印消息、发送网络请求等都是运行时级别的操作。自诞生以来，JavaScript 已被各种环境所采用。，例如，浏览器（其提供诸如 [DOM](/zh-CN/docs/Web/API/Document_Object_Model) 这样的 API），Node.js
已处理（最近在中国访问 github 比较困难，回复可能不会很及时。）

2024-11-19 08:46 UTC, jasonren0403 requested changes
一些修改建议

2024-11-19 08:46 UTC, jasonren0403 commented on files/zh-cn/web/javascript/language_overview/index.md
> +它支持标准的[算数运算符](/zh-CN/docs/Web/JavaScript/Reference/Operators#算数运算符)，例如，加、减、取余运算等等。BigInt 和 number 在算数运算中不能混用。
```suggestion
它支持标准的[算术运算符](/zh-CN/docs/Web/JavaScript/Reference/Operators#算术运算符)，例如，加、减、取余运算等等。BigInt 和 number 在算术运算中不能混用。
```

2024-11-19 08:46 UTC, jasonren0403 commented on files/zh-cn/web/javascript/language_overview/index.md
> +字符串重载了 `+` 运算符：当操作数之一是字符串时，执行的是字符串拼接而不是数字加法。特殊的[模板字面量](/zh-CN/docs/Web/JavaScript/Reference/Template_literals)语法能用嵌入式表达式更简洁地书写字符串。和 Python 的 f-string 或 c# 的插值字符串不同，模板字面量使用反引号（不是单引号，也不是双引号）。
```suggestion
字符串重载了 `+` 运算符：当操作数之一是字符串时，执行的是字符串拼接而不是数字加法。特殊的[模板字面量](/zh-CN/docs/Web/JavaScript/Reference/Template_literals)语法能用嵌入式表达式更简洁地书写字符串。和 Python 的 f-string 或 C# 的插值字符串不同，模板字面量使用反引号（不是单引号，也不是双引号）。
```

2024-11-19 08:46 UTC, jasonren0403 commented on files/zh-cn/web/javascript/language_overview/index.md
> +你可以使用 [`Boolean()`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Boolean/Boolean) 函数显示地执行这个转换：
```suggestion
你可以使用 [`Boolean()`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Boolean/Boolean) 函数显式执行这个转换：
```

2024-11-19 08:46 UTC, jasonren0403 commented on files/zh-cn/web/javascript/language_overview/index.md
> +然而，几乎没有必要这样做，因为 JavaScript 在期待布尔时会静默地执行这个转换，例如在 `if` 语句中（参见[控制结构](#控制结构)）。鉴于这个原因，我们有时候讲“[真值](/zh-CN/docs/Glossary/Truthy)”和“[假值](/zh-CN/docs/Glossary/Falsy)”，在布尔上下文中，表明分别能转换成 `true` 和 `false` 的值。
```suggestion
然而，几乎没有必要这样做，因为 JavaScript 在期望使用布尔值时会静默地执行这个转换，例如在 `if` 语句中（参见[控制结构](#控制结构)）。鉴于这个原因，我们有时候讲“[真值](/zh-CN/docs/Glossary/Truthy)”和“[假值](/zh-CN/docs/Glossary/Falsy)”，在布尔上下文中，表明分别能转换成 `true` 和 `false` 的值。
```

2024-11-21 03:24 UTC, jasonren0403 approved these changes
👍

2024-11-21 03:26 UTC, jasonren0403 commented
推荐以后在 Files changed 选项卡中，批量应用更改，然后一次性提交

2024-11-21 03:26 UTC, merged

2024-11-21 04:15 UTC, familyboat commented
> 推荐以后在 Files changed 选项卡中，批量应用更改，然后一次性提交

OK。下次我试着这样做。