[zh-cn]: create docs for Fence
mdn/translated-content pull request #24648
Opened 2024-11-21 07:30 UTC by fuchunhui

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-11-22 13:02 UTC, yin1999 requested changes

2024-11-22 13:02 UTC, yin1999 commented on files/zh-cn/web/api/fence/reportevent/index.md
> +          - `"buyer"`：广告拍卖中的出价方。
竞价

2024-11-22 13:02 UTC, yin1999 commented on files/zh-cn/web/api/fence/reportevent/index.md
> +          - `"component-seller"`：多级拍卖中的组件拍卖的卖方。
啥叫“组件拍卖方”，这翻译读着就有点奇怪。这一部分的翻译请再好好考虑一下。

2024-11-22 13:02 UTC, yin1999 commented on files/zh-cn/web/api/fence/setreporteventdataforautomaticbeacons/index.md
此文档的问题与上一个的类似，请先修改，我再审查。

2024-11-25 07:13 UTC, fuchunhui commented on files/zh-cn/web/api/fence/reportevent/index.md
> +          - `"component-seller"`：多级拍卖中的组件拍卖的卖方。
done，已统一处理为组件竞价。

2024-11-27 08:00 UTC, yin1999 commented on files/zh-cn/web/api/fence/reportevent/index.md
> +          - `"component-seller"`：多级拍卖中的组件拍卖的卖方。
我感觉核心问题是“组件”而非“拍卖方”，修改以后也很奇怪。我检索了一下 Google 对这些术语的定义：

- [英文版](https://developers.google.com/privacy-sandbox/private-advertising/sequential-auction-setup)（打开后可能需要手动切换语言）
- [中文版](https://developers.google.com/privacy-sandbox/private-advertising/sequential-auction-setup?hl=zh-cn)（机器翻译，术语中几乎都翻译成“组件”了）

“component seller”其实是参与多卖方竞价的“组成”卖方，我觉得翻译成“组成卖方”更好。因为我们平时也会说“组成成员”、“组成部门”等词语。

/cc @mdn/yari-content-zh

2024-12-01 02:00 UTC, yin1999 commented on files/zh-cn/web/api/fence/setreporteventdataforautomaticbeacons/index.md
> +  eventData: "an example string",
```suggestion
  eventData: "示例字符串",
```

2024-12-01 02:00 UTC, yin1999 approved these changes
Thanks @fuchunhui

2024-12-01 02:02 UTC, merged