[zh-cn]: create docs for HTMLLinkElement
mdn/translated-content pull request #24675
Opened 2024-11-22 03:57 UTC by fuchunhui

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-11-25 09:45 UTC, jasonren0403 requested changes
有一些问题

2024-11-25 09:45 UTC, jasonren0403 commented on files/zh-cn/web/api/htmllinkelement/as/index.md
> +当链接元素的 [`rel="preload"`](/zh-CN/docs/Web/HTML/Attributes/rel/preload) 时，`as` 属性必须有一个值，否则资源将不会被获取。它也可以应用于 [`rel="modulepreload"`](/zh-CN/docs/Web/HTML/Attributes/rel/preload) 的链接元素，但如果省略，将默认值为 `script
https://github.com/mdn/content/pull/36963

```suggestion
当链接元素的 [`rel="preload"`](/zh-CN/docs/Web/HTML/Attributes/rel/preload) 时，`as` 属性必须有一个值，否则资源将不会被获取。它也可以应用于 [`rel="modulepreload"`](/zh-CN/docs/Web/HTML/Attributes/rel/modulepreload) 的链接元素，但如果省略，将默认为 `script`。对于其他类型的链接元素，如 `rel="prefetch"`，则不应设置此属性。
```

2024-11-25 09:45 UTC, jasonren0403 commented on files/zh-cn/web/api/htmllinkelement/crossorigin/index.md
> +{{domxref("HTMLLinkElement")}} 接口的 **`crossOrigin`** 属性指定了在检索资源时要使用的跨源资源共享 {{Glossary("CORS")}} 设置。
```suggestion
{{domxref("HTMLLinkElement")}} 接口的 **`crossOrigin`** 属性指定了在检索资源时要使用的{{Glossary("CORS", "跨源资源共享")}}设置。
```

2024-11-25 09:45 UTC, jasonren0403 commented on files/zh-cn/web/api/htmllinkelement/crossorigin/index.md
> +- `anonymous` 或空字符串 (`""`)
```suggestion
- `anonymous` 或空字符串（`""`）
```

2024-11-25 09:45 UTC, jasonren0403 commented on files/zh-cn/web/api/htmllinkelement/disabled/index.md
> +// 设置 disabled 属性为 true 以启动样式表
感觉这里原文的注释有误

```suggestion
// 设置 disabled 属性为 false 以启用样式表
```

2024-11-25 09:45 UTC, jasonren0403 commented on files/zh-cn/web/api/htmllinkelement/disabled/index.md
> +- [Subresource Integrity](/zh-CN/docs/Web/Security/Subresource_Integrity)
```suggestion
- [子资源完整性](/zh-CN/docs/Web/Security/Subresource_Integrity)
```

2024-11-25 09:45 UTC, jasonren0403 commented on files/zh-cn/web/api/htmllinkelement/fetchpriority/index.md
> +这反过来又使浏览器能够提高或降低优先级，并可能使资源比原本更早或更晚地加载。应谨慎使用该属性，因为过度或错误的优先级设置可能会降低性能。
```suggestion
该属性允许开发人员向浏览器发出信号，表明在加载过程中早期获取特定资源对用户体验的影响，这种影响可能比浏览器在分配内部优先级时能够合理推断出的影响更大或更小，特别是在预加载资源时。这反过来又使浏览器能够提高或降低优先级，并可能使资源比原本更早或更晚地加载。应谨慎使用该属性，因为过度或错误的优先级设置可能会降低性能。
```

2024-11-25 09:45 UTC, jasonren0403 commented on files/zh-cn/web/api/htmllinkelement/fetchpriority/index.md
> +- [Optimize resource loading with the Fetch Priority API](https://web.dev/articles/fetch-priority?hl=en#browser_priority_and_fetchpriority) for information about how this API affects priorities on Ch
```suggestion
- HTTP {{httpheader("Link")}} 标头
- [使用 Fetch Priority API 优化资源加载](https://web.dev/articles/fetch-priority?hl=en#browser_priority_and_fetchpriority)一文讲述了该 API 如何影响 Chrome 中的优先级。
```

2024-11-25 09:45 UTC, jasonren0403 commented on files/zh-cn/web/api/htmllinkelement/hreflang/index.md
> +  title="French HTML" />
```suggestion
  title="法语 HTML 页面" />
```

2024-11-25 09:45 UTC, jasonren0403 commented on files/zh-cn/web/api/htmllinkelement/index.md
> +  - : 一个字符串，反映 [`referrerpolicy`](/zh-CN/docs/Web/HTML/Element/link#referrerpolicy) HTM L 属性，用于指示应使用哪个引用来源。
可以考虑将 HTTP 概念下的 Referrer 翻译为“来源地址” https://zh.wikipedia.org/wiki/HTTP%E5%8F%83%E7%85%A7%E4%BD%8D%E5%9D%80

```suggestion
  - : 一个字符串，反映 [`referrerpolicy`](/zh-CN/docs/Web/HTML/Element/link#referrerpolicy) HTML 属性，用于指示应使用哪个来源地址。
```

2024-11-25 09:45 UTC, jasonren0403 commented on files/zh-cn/web/api/htmllinkelement/index.md
> +  - : 表示目标资源字符编码的字符串。
```suggestion
  - : 一个字符串，表示目标资源的字符编码。
```

2024-11-25 09:45 UTC, jasonren0403 commented on files/zh-cn/web/api/htmllinkelement/referrerpolicy/index.md
> +{{domxref("HTMLLinkElement")}} 接口的 **`referrerPolicy`** 属性反映 {{HTMLElement("link")}} 元素的 HTML [`referrerpolicy`](/zh-CN/docs/Web/HTML/Element/link#referrerpolicy) 属性，该属性定义获取资源时发送哪个引用来源。
本文的 referrer 也同样可以考虑翻为“来源地址”

2024-11-25 09:45 UTC, jasonren0403 commented on files/zh-cn/web/api/htmllinkelement/referrerpolicy/index.md
> +- `strict-origin-when-cross-origin` (default)
```suggestion
- `strict-origin-when-cross-origin`（默认值）
```

2024-11-25 09:45 UTC, jasonren0403 commented on files/zh-cn/web/api/htmllinkelement/referrerpolicy/index.md
> +  - : 在所有情况下，仅将文档的来源作为引用来源发送。`https://example.com/page.html` 文档将发送引用来源 `https://example.com/`。
```suggestion
  - : 在所有情况下，仅将文档的源作为引用来源发送。`https://example.com/page.html` 文档将发送引用来源 `https://example.com/`。
```

2024-11-25 09:45 UTC, jasonren0403 commented on files/zh-cn/web/api/htmllinkelement/referrerpolicy/index.md
> +  - : 在执行同源请求时发送完整的 URL，但在其他情况下仅发送文档的来源。
```suggestion
  - : 在执行同源请求时发送完整的 URL，但在其他情况下仅发送文档的源。
```

2024-11-25 09:45 UTC, jasonren0403 commented on files/zh-cn/web/api/htmllinkelement/referrerpolicy/index.md
> +  - : 在执行同源或跨源请求时发送完整的 URL。此策略会将 TLS 保护的资源的来源和路径泄露给不安全的来源。请仔细考虑此设置的影响。
```suggestion
  - : 在执行同源或跨源请求时发送完整的 URL。此策略会将 TLS 保护的资源的源和路径泄露给不安全的源。请仔细考虑此设置的影响。
```

2024-11-25 09:45 UTC, jasonren0403 commented on files/zh-cn/web/api/htmllinkelement/sheet/index.md
> +`HTMLLinkElement` 对象的 `sheet` 属性将返回描述 `styles.css` 的 {{domxref("StyleSheet")}} 对象。
```suggestion
`HTMLLinkElement` 对象的 `sheet` 属性将返回描述为 `styles.css` 的 {{domxref("StyleSheet")}} 对象。
```

2024-11-26 03:27 UTC, fuchunhui commented on files/zh-cn/web/api/htmllinkelement/fetchpriority/index.md
> +- [Optimize resource loading with the Fetch Priority API](https://web.dev/articles/fetch-priority?hl=en#browser_priority_and_fetchpriority) for information about how this API affects priorities on Ch
感谢，这里遗漏掉了。

2024-11-26 03:28 UTC, fuchunhui commented on files/zh-cn/web/api/htmllinkelement/index.md
> +  - : 一个字符串，反映 [`referrerpolicy`](/zh-CN/docs/Web/HTML/Element/link#referrerpolicy) HTM L 属性，用于指示应使用哪个引用来源。
好的，我再全部检查一遍。

2024-11-26 03:43 UTC, fuchunhui commented on files/zh-cn/web/api/htmllinkelement/disabled/index.md
> +// 设置 disabled 属性为 true 以启动样式表
这里我再确认下。

2024-11-26 03:55 UTC, fuchunhui commented on files/zh-cn/web/api/htmllinkelement/disabled/index.md
> +// 设置 disabled 属性为 true 以启动样式表
https://github.com/mdn/content/pull/36976

2024-11-29 01:32 UTC, yin1999 commented on files/zh-cn/web/api/htmllinkelement/as/index.md
> +此属性反映 HTML [`<link>`](/zh-CN/docs/Web/HTML/Element/link) 元素的 [`as` 属性](/zh-CN/docs/Web/HTML/Element/link#as) 的值。
```suggestion
此属性反映 HTML [`<link>`](/zh-CN/docs/Web/HTML/Element/link) 元素的 [`as` 属性](/zh-CN/docs/Web/HTML/Element/link#as)的值。
```

2024-12-02 02:23 UTC, jasonren0403 approved these changes
Thanks 👍

2024-12-02 02:23 UTC, jasonren0403 commented on files/zh-cn/web/api/htmllinkelement/as/index.md
> +  sourceCommit: c30827dea447e33d0d875cb3e7e1632b56148e5f
```suggestion
  sourceCommit: 782dea39dbc29c19c82fef8fd8a1222db3c248ab
```

2024-12-02 02:25 UTC, merged

2024-12-02 03:51 UTC, fuchunhui commented on files/zh-cn/web/api/htmllinkelement/as/index.md
> +  sourceCommit: c30827dea447e33d0d875cb3e7e1632b56148e5f
https://github.com/mdn/content/pull/36963
👍