[ja-JP]blink element (<blink> tag)を新規翻訳
mdn/translated-content pull request #24679
Opened 2024-11-22 13:17 UTC by OHMORIYUSUKE

### Description

blink element (<blink> tag)を新規翻訳しました。

https://developer.mozilla.org/en-US/docs/Glossary/blink_element

### Motivation

現在では利用されないタグですが、使われない理由を日本語で残すことに意味があると思ったため。

### Additional details

### Related issues and pull requests

Fixes: https://github.com/mozilla-japan/translation/issues/797

2024-11-23 04:55 UTC, hmatrjp submitted a review, later dismissed

2024-11-23 04:55 UTC, hmatrjp commented on files/ja/glossary/blink_element/index.md
> +`<blink>` は、Netscapeのエンジニアである [Lou Montulli](https://en.wikipedia.org/wiki/Lou_Montulli) と同僚たちがマウンテンビューのバーでしていた会話がきっかけで生まれたようです。彼が翌朝オフィスに出社すると、同僚のひとりが徹夜でその機能を実装していたことに気づきました（[詳しい話はこちら](https://web.ar
ルー・モントゥリ氏についての Wikipedia ページは日本語版もあるので、リンクをそちらに向けてはいかがでしょうか。

2024-11-23 06:29 UTC, OHMORIYUSUKE commented on files/ja/glossary/blink_element/index.md
> +`<blink>` は、Netscapeのエンジニアである [Lou Montulli](https://en.wikipedia.org/wiki/Lou_Montulli) と同僚たちがマウンテンビューのバーでしていた会話がきっかけで生まれたようです。彼が翌朝オフィスに出社すると、同僚のひとりが徹夜でその機能を実装していたことに気づきました（[詳しい話はこちら](https://web.ar
ありがとうございます。日本語ページのURLに変更しました。
https://github.com/mdn/translated-content/pull/24679/commits/e06f4e736865b0ec10177c2f0feed53172e577b0

2024-11-27 13:24 UTC, mfuji09 requested changes
1件の確認と修正をお願いします。

2024-11-30 10:51 UTC, mfuji09 approved these changes
OKです。

2024-11-30 10:54 UTC, merged