[es, fr, ja, ko, pt-br, ru, zh-cn, zh-tw]Corrected image file paths and demos paths
mdn/translated-content pull request #24765
Opened 2024-11-25 18:16 UTC by OHMORIYUSUKE

### Description

Issue #24373 has been addressed.
Other image files had also been changed. For example, `starsolid.gif` was renamed to `star-solid.gif`. Therefore, the file paths have been corrected.

This problem occurs in the documentation for each language. All have been corrected in this PR.

### Motivation

If images and demos are not displayed correctly, they will confuse people referring to the document.

### Additional details

### Related issues and pull requests

Fixes #24373

2024-11-25 21:39 UTC, leon-win commented on files/ru/web/css/background-position/index.md
> +  background: url("star-transparent.gif") #ffee99 3em 50% no-repeat;
```suggestion
  background: url("star-transparent.gif") #ffee99 left 4em bottom 1em no-repeat;
```

2024-11-25 21:39 UTC, leon-win commented on files/ru/web/css/background-position/index.md
>      center;
```suggestion
    right 3em bottom 2em;
```

2024-11-25 21:40 UTC, leon-win commented
@OHMORIYUSUKE , thank you!

Looks good for `ru` (add some few suggestions) :+1:

2024-11-25 21:41 UTC, leon-win approved these changes

2024-11-26 06:30 UTC, jasonren0403 approved these changes
handy update, however looks good overall👍

2024-11-26 06:30 UTC, jasonren0403 commented on files/zh-cn/web/css/background-repeat/index.md
>    height: 84px;
```suggestion
  width: 160px;
  height: 70px;
```

2024-11-26 14:11 UTC, mfuji09 approved these changes
`ja` のファイルについては良いと思います。

2024-11-26 22:12 UTC, Graywolf9 approved these changes
The paths looks good for `es` 

Thank you so much!

2024-11-29 14:19 UTC, OHMORIYUSUKE commented
@1ilsang @cw118 @nathipg
Could you kindly review this when you have a moment?

2024-11-29 17:49 UTC, cw118 requested changes
Most of the changes look good, thank you!

I have not had the time to test on my local machine, but could you confirm that the `EmbedLiveSample` work after adding the titles (e.g. `"Exemple_simple"`)? There is a reason why empty strings were used in these macros in `translated-content`.

2024-12-01 12:26 UTC, 1ilsang commented
Looks good for `ko`. Thank you so much.

2024-12-01 12:26 UTC, 1ilsang approved these changes

2024-12-02 17:15 UTC, OHMORIYUSUKE commented
@cw118
> Most of the changes look good, thank you!
> 
> I have not had the time to test on my local machine, but could you confirm that the `EmbedLiveSample` work after adding the titles (e.g. `"Exemple_simple"`)? There is a reason why empty strings were used in these macros in `translated-content`.

Thank you for the review!

The EmbedLiveSample works correctly. I confirmed it on my local machine.

> There is a reason why empty strings were used in these macros in translated-content.

The display was not working as expected, so I fixed it in this pull request.
I referred to the following documentation when making the corrections:
https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Live_samples#grouping_code_blocks

I couldn't understand the reason why the macro was used with empty strings.My apologies.

2024-12-02 18:59 UTC, cw118 approved these changes
> The EmbedLiveSample works correctly. I confirmed it on my local machine.

Perfect, that should work then. We can confirm again once this is merged. Thanks very much for this @OHMORIYUSUKE !

In the past there were some strange issues with EmbedLiveSample in translated-content that required using empty strings, but it does seem that this is not a problem anymore (for the most part).

2024-12-03 14:12 UTC, OHMORIYUSUKE commented
@nathipg
Could you kindly review this when you have a moment?

2024-12-08 16:18 UTC, OHMORIYUSUKE commented
@josielrocha

You're not assigned as a reviewer, but if possible, could you kindly review it? Thank you in advance!

2025-01-09 17:42 UTC, cw118 commented
Gently poking @mdn/yari-content-pt-br for a review :)

2025-01-09 21:03 UTC, leon-win commented on files/pt-br/web/css/background-attachment/index.md
> +{{EmbedLiveSample("Exemplo_simpes")}}
```suggestion
{{EmbedLiveSample("Exemplo_simples")}}
```

2025-01-09 21:04 UTC, leon-win commented on files/pt-br/web/css/background-attachment/index.md
> +{{EmbedLiveSample("Exemplo_simpes")}}
I think it would be more correct this way)

2025-01-09 21:07 UTC, leon-win commented
I think there are so few `pt-BR`-related changes in this PR that it is not necessary to wait for confirmation from the pt-BR team =)

I fixed the typo (made a suggestion).

2025-01-10 16:03 UTC, cw118 commented
> I think there are so few `pt-BR`-related changes in this PR that it is not necessary to wait for confirmation from the pt-BR team =)

Thank you for reviewing `pt-br`! I agree, especially since this PR has been open for a long time, though I personally still prefer to try to ping them because locales may have conventions that only they know, among other reasons.

Let's merge this once the typo is fixed (N.B. [the same typo seems to be here as well](https://github.com/mdn/translated-content/pull/24765/files#diff-58dc4a8cc442ebb25882bad3c4fa7e04d03180a3f7abe5b45677e41b8cd3db81L39)) :)

2025-01-10 16:06 UTC, cw118 commented on files/pt-br/web/css/background-attachment/index.md
> +{{EmbedLiveSample("Exemplo_simpes")}}
N.B. it is written the same way [on line 39](https://github.com/mdn/translated-content/pull/24765/files#diff-58dc4a8cc442ebb25882bad3c4fa7e04d03180a3f7abe5b45677e41b8cd3db81L39), but I believe we can't add a suggestion there :/

2025-01-14 22:25 UTC, Graywolf9 commented
Hello to every one!

It seems that the `pt-br` samples are rendering succesfully, also I can't find but I remember somethign about removing the first argument in `EmbdeLiveSample` macro, so maybe we can continue with this PR

I don't know what do you think

2025-01-21 18:17 UTC, cw118 commented
> Hello to every one!
> 
> It seems that the `pt-br` samples are rendering succesfully, also I can't find but I remember somethign about removing the first argument in `EmbdeLiveSample` macro, so maybe we can continue with this PR
> 
> I don't know what do you think

Yes, previously EmbedLiveSample behaved strangely and on translated-content we used empty strings in the macro, but this does not seem to be required anymore? I still have to catch up on some MDN updates so I may have missed it somewhere 😅 

If the pt-br samples display well, then I think we can merge this now because it has been open for a long time. @leon-win maybe the typo that you found can be suggested/fixed in a separate PR to avoid blocking this one? Happy to discuss more though!

2025-01-21 20:08 UTC, leon-win commented
> > Hello to every one!
> > It seems that the `pt-br` samples are rendering succesfully, also I can't find but I remember somethign about removing the first argument in `EmbdeLiveSample` macro, so maybe we can continue with this PR
> > I don't know what do you think
> 
> Yes, previously EmbedLiveSample behaved strangely and on translated-content we used empty strings in the macro, but this does not seem to be required anymore? I still have to catch up on some MDN updates so I may have missed it somewhere 😅
> 
> If the pt-br samples display well, then I think we can merge this now because it has been open for a long time. @leon-win maybe the typo that you found can be suggested/fixed in a separate PR (or an issue can be created) to avoid blocking this one? Happy to discuss more though!

Sorry if I got in the way. I wanted to help))
Closed my suggestion :ok_hand:

2025-01-21 20:52 UTC, cw118 commented
> Sorry if I got in the way. I wanted to help)) Closed my suggestion 👌

No, not at all, thank you for seeing that typo! I was just thinking we could perhaps try another issue or PR so that the pt-br team can confirm it is correct without keeping this PR open. Would you like to create the issue/PR? If not I would be glad to do it 😃 

I will merge since this most locales are approved, and thank you @leon-win and @Graywolf9 for checking the pt-br files! Thank you for your patience @OHMORIYUSUKE 🎉

2025-01-21 20:52 UTC, merged

2025-01-21 21:33 UTC, leon-win commented
> No, not at all, thank you for seeing that typo! I was just thinking we could perhaps try another issue or PR so that the pt-br team can confirm it is correct without keeping this PR open. Would you like to create the issue/PR? If not I would be glad to do it 😃

I agree, it's better when each PR solves one specific problem. However, it doesn't always work out that way)

I think it's better for you to do it)) :handshake: