[ko] new transtion of date_and_time_formats
mdn/translated-content pull request #24784
Opened 2024-11-26 16:31 UTC by chanwoopark11

### Description

기존에 한국어로 존재하지 않던 문서 [html의 날짜와 시간형식](https://developer.mozilla.org/en-US/docs/Web/HTML/Date_and_time_formats)을 신규 번역했습니다.

### Motivation

### Additional details

몇가지 제가 어쩔수 없었던 사항이 있었는데
1. callout 관련하여 ko/curriculum/으로 경로를 지정했으나 링크가 깨져서 임시로 en-US로 대체하였습니다.
2. 번역기준을 한국으로 설정했습니다.(예를 들면 02는 영어에서는 February이지만 한국어론 2월인것처럼요)
3. 첫기여라 많이 부족하다는 점을 염두에 두고 봐주시면 감사하겠습니다.
### Related issues and pull requests
https://github.com/mdn/translated-content/issues/24514

2024-11-29 22:42 UTC, wisedog requested changes
안녕하세요! 제가 리뷰어까지 되었네요 ㅎㅎ  첫 기여 정말 감사드립니다. 처음이신데 너무 방대한 걸 골라서 지쳐서 나가 떨어지지 않을까 걱정 많이 했는데, 결국 해내셨군요! 몇 가지 리뷰 드립니다. 이 것만 해결되면 머지가 가능하지 싶습니다.

감사합니다.

2024-11-29 22:42 UTC, wisedog commented on files/ko/web/html/date_and_time_formats/index.md
> +> [!CALLOUT]
이 부분은 원문에 없는건데 왜 넣으셨는지 궁금합니다. MDN 번역은 `en-US` 원문과는 다른 자의적 편집을 지양하고 있습니다

2024-11-29 22:42 UTC, wisedog commented on files/ko/web/html/date_and_time_formats/index.md
> +HTML의 특정 요소는 날짜 와/또는 시간 값을 사용합니다. 이러한 값을 지정하는 문자열의 형식은 본 문서에서 설명합니다.
```suggestion
HTML에서 사용되는 날짜 및 시간 형식. HTML의 특정 요소는 날짜 와/또는 시간 값을 사용합니다. 이러한 값을 지정하는 문자열의 형식은 본 문서에서 설명합니다.
```
가능하면 본문과 줄 수를 맞춰서 주시면 좋습니다.

2024-11-29 22:42 UTC, wisedog commented on files/ko/web/html/date_and_time_formats/index.md
> +한 해는 일반적으로 365일로 구성되지만, **[윤년](#leap_years)**에는 예외적으로 하루가 추가됩니다.
```suggestion
한 해는 일반적으로 365일로 구성되지만, **[윤년](#윤년)** 에는 예외적으로 하루가 추가됩니다.
```

Markdown 자체가 영어에 맞춰진지라 ㅎㅎ 강조 구문 끝에 )가 있으면 한 칸을 띄워야지 제대로 렌더링이 됩니다. 그렇지 않으면 원문 `**` 그대로 출력됩니다. 현재 [Preview](https://pr24784.content.dev.mdn.mozit.cloud/ko/docs/Web/HTML/Date_and_time_formats)에서도 이렇게 출력됩니다. 북마크도 신경써주시면 좋겠습니다.

2024-11-29 22:42 UTC, wisedog commented on files/ko/web/html/date_and_time_formats/index.md
> +`02`월,2월,은 일반적으로 28일이지만, 윤년에는 29일이 됩니다.
```suggestion
`02`월 즉 2월은 일반적으로 28일이지만, 윤년에는 29일이 됩니다.
```

2024-11-30 01:10 UTC, chanwoopark11 commented on files/ko/web/html/date_and_time_formats/index.md
> +> [!CALLOUT]
제가 callout을 무조건 넣어야 되는걸로 착각한것 같습니다.
callout을 제거하면 될까요?

2024-11-30 01:54 UTC, chanwoopark11 commented
수정한 작업 커밋(re-correction of some wrong transtion)을 원격 브랜치로 푸쉬하던 도중, 다음과 같은 에러를 만났습니다.

 ! [rejected]              feature/time_and_formats -> feature/time_and_formats (fetch first)
error: failed to push some refs to 'https://github.com/chanwoopark11/translated-content'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

일단, git pull로 원격의 최신 변경 사항을 로컬 브랜치로 병합한후
제가 작업한 커밋과 병합 커밋이 같이 푸쉬되게 되었습니다.
이점 양해 바랍니다.

마지막으로 제가 진행한 수정작업에 대해 말씀드리자면
callout을 삭제해달라는 것으로 받아들여 callout은 삭제를 하였고

2번째 리뷰사항에서 제가 잘못 입력한 부분이 있어서 그 부분은 삭제를 하였습니다. 

나머지는 제안해주신 그대로 수정을 하였습니다. 감사합니다.

2024-11-30 04:34 UTC, wisedog commented on files/ko/web/html/date_and_time_formats/index.md
> +> [!CALLOUT]
네 맞습니다.

2024-11-30 04:37 UTC, wisedog approved these changes
LGTM! 고생하셨습니다

2024-11-30 04:37 UTC, merged

2024-11-30 06:13 UTC, chanwoopark11 commented
짧은 기간이였지만 많이 도와주셔서 감사합니다!