[ko] update(dl): general update
mdn/translated-content pull request #24841
Opened 2024-11-29 13:42 UTC by wondasom

### Description

- 문서 내용 순서 수정('기술 요약', '접근성')
- 가독성을 위해 소제목 수정
```diff
- ### 여러 개의 용어와 하나의 정의
+ ### 복수 용어와 단일 정의
```
- 새로운 내용 업데이트(VO 관련 등)
- 링크 업데이트

### Motivation

The doc was partially outdated.

### Additional details

🔗 Local test link: http://localhost:5042/ko/docs/Web/HTML/Element/dl

### Related issues and pull requests

N/A

2024-11-29 22:21 UTC, wisedog requested changes
첫 기여 감사합니다! 처음이신데 멋진걸 하셨네요. 조금만 더 보완하면 바로 머지될 수 있으리라 생각합니다.

2024-11-29 22:21 UTC, wisedog commented on files/ko/web/html/element/dl/index.md
> +title: <dl> 설명 목록
원문이 `<dl>: The Description List element` 니까 `<dl>: 설명 목록 요소` 가 어떨까 합니다.

2024-11-29 22:21 UTC, wisedog commented on files/ko/web/html/element/dl/index.md
>  ---
최신 원본 문서와 같기 때문에 `l10n`을 넣어주셔도 되겠습니다. [가이드](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/meta-data-guide.md)를 참고해주세요

2024-11-29 22:21 UTC, wisedog commented on files/ko/web/html/element/dl/index.md
> +<!-- The source for this interactive example is stored in a GitHub repository. If you'd like to contribute to the interactive examples project, please clone [https://github.com/mdn/interactive-exampl
이 부분은 원문에 없네요. 확인 부탁드립니다.

2024-11-29 22:21 UTC, wisedog commented on files/ko/web/html/element/dl/index.md
> +각각의 스크린 리더는 `<dl>`를 다르게 표현합니다. 즉, 총 아이템의 개수, 용어/정의 컨텍스트 및 탐색 방법등을 다르게 노출합니다. 이러한 차이가 반드시 버그는 아닙니다. iOS 14부터의 스크린 리더는 전체 읽기 멍령이 아닌 가상 커서 탐색 시, `<dl>` 콘텐츠가 목록임을 알립니다. ARIA 용어 및 정의 역할을 `<dl>`구조에 적용하면 ma
원문에는 iOS의 VoiceOver를 그대로 적어야 할 것으로 보입니다. VoiceOver도 고유명사이므로 `VoiceOver` 그대로 적으시면 됩니다. 

또한 원문에는 VoiceOver does not support list navigation commands with `<dl>`. Be careful applying ARIA `term` and `definition` roles to `<dl>` constructs as VoiceOver (macOS and iOS) will adjust how they are announced.

이라 되어 있는데 해석이 약간 빠진듯 합니다.

2024-11-29 22:21 UTC, wisedog commented on files/ko/web/html/element/dl/index.md
> +- [Brief Note on Description List Support](https://adrianroselli.com/2022/12/brief-note-on-description-list-support.html)
```suggestion
- [iOS14에서의 VoiceOver 설명 목록 지원](https://adrianroselli.com/2020/09/voiceover-on-ios-14-supports-description-lists.html)
- [설명 목록 지원에 대한 개략](https://adrianroselli.com/2022/12/brief-note-on-description-list-support.html)
```

해석을 안하셨는데, 이 정도면 어떨까요?

2024-11-29 22:21 UTC, wisedog commented on files/ko/web/html/element/dl/index.md
>  {{EmbedLiveSample("하나의_용어와_하나의_정의")}}
```suggestion
{{EmbedLiveSample("Single_term_and_description")}}
```

매크로는 원문과 동일해야 합니다.

2024-11-29 22:21 UTC, wisedog commented on files/ko/web/html/element/dl/index.md
>  {{EmbedLiveSample("여러_개의_용어와_하나의_정의")}}
```suggestion
{{EmbedLiveSample("Multiple_terms_single_description")}}
```

2024-11-29 22:21 UTC, wisedog commented on files/ko/web/html/element/dl/index.md
>  {{EmbedLiveSample("하나의_용어와_여러_개의_정의")}}
{{EmbedLiveSample("Single_term_multiple_descriptions")}}

2024-11-29 22:21 UTC, wisedog commented on files/ko/web/html/element/dl/index.md
> +{{EmbedLiveSample("메타데이터")}}
```suggestion
{{EmbedLiveSample('Metadata')}}
```

2024-11-29 22:21 UTC, wisedog commented on files/ko/web/html/element/dl/index.md
> +{{EmbedLiveSample("Wrapping name-value groups in div elements")}}
```suggestion
{{EmbedLiveSample('Wrapping name-value groups in `div` elements')}}
```

2024-11-29 22:21 UTC, wisedog commented on files/ko/web/html/element/dl/index.md
> +    </tr>
``` <tr>
      <th scope="row">Implicit ARIA role</th>
      <td>
        <a href="https://www.w3.org/TR/html-aria/#dfn-no-corresponding-role"
          >No corresponding role</a
        >
      </td>
    </tr>
```
이게 빠졌습니다.

2024-11-29 22:21 UTC, wisedog commented on files/ko/web/html/element/dl/index.md
> +        <a href='/ko/docs/Web/Accessibility/ARIA/Roles/group_role'><code>group</code></a>, <a href='/ko/docs/Web/Accessibility/ARIA/Roles/presentation_role'><code>presentation</code></a>
여기 한 번만 확인 부탁드립니다.

2024-12-17 10:12 UTC, wondasom commented on files/ko/web/html/element/dl/index.md
> +<!-- The source for this interactive example is stored in a GitHub repository. If you'd like to contribute to the interactive examples project, please clone [https://github.com/mdn/interactive-exampl
이 부분은 새로 넣은 건 아니구요 원래 있던 내용인데 지우는 걸 깜빡했네요~! 캐치해주셔서 감사해요

2024-12-17 10:27 UTC, wondasom commented
@wisedog 리뷰 감사합니다! 회사에서 요즘 접근성 부분을 많이 고치고 있어서 틈날 때 마다 기여 해 보려구요. 코멘트 해 주신 부분들 수정했습니다. 🙌🏼

2024-12-17 13:53 UTC, wisedog approved these changes
LGTM!

2024-12-17 13:53 UTC, merged