zh-CN: create `identity`
mdn/translated-content pull request #24871
Opened 2024-12-01 12:05 UTC by PassionPenguin

2024-12-01 18:48 UTC, skyclouds2001 commented on files/zh-cn/mozilla/add-ons/webextensions/api/identity/index.md
> +要使用此 API，你的拓展必须预先取得“identity” [API 权限](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#API_权限)。
```suggestion
要使用此 API，你的拓展必须预先取得“identity”[API 权限](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#API_权限)。
```

2024-12-02 02:08 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/identity/index.md
> +要使用此 API，你的拓展必须预先取得“identity” [API 权限](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#API_权限)。
豪德！（不是很确定这种情况该不该空格，谢谢你！）

2024-12-02 02:08 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/identity/index.md
> +要使用此 API，你的拓展必须预先取得“identity” [API 权限](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#API_权限)。
豪德！（不是很确定这种情况该不该空格，谢谢你！）

2024-12-04 03:20 UTC, yin1999 requested changes
有些需要修改的点

2024-12-04 03:20 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/identity/index.md
> +使用身份 API 以获取 [OAuth2](https://oauth.net/2/) 授权码或访问令牌，这样扩展就可以使用这一授权码或访问令牌从支持 OAuth2 访问的服务（例如 Google 或 Facebook）处访问用户数据。
还是注明一下

```suggestion
使用身份 API（identity API）以获取 [OAuth2](https://oauth.net/2/) 授权码或访问令牌，这样扩展就可以使用这一授权码或访问令牌从支持 OAuth2 访问的服务（例如 Google 或 Facebook）处访问用户数据。
```

2024-12-04 03:20 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/identity/index.md
> +要使用此 API，你的拓展必须预先取得“identity”[API 权限](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#API_权限)。
错别字（删了吧）

```suggestion
要使用此 API，你必须预先取得“identity”[API 权限](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#api_权限)。
```

2024-12-04 03:20 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/identity/index.md
> +[重定向 URL](https://www.oauth.com/oauth2-servers/redirect-uris/) 代表着 {{WebExtAPIRef("identity.launchWebAuthFlow()")}} 的终点，即将会传递给拓展包含访问令牌或授权码的那一个 URL。浏览器会从重定向 URL 中直接提取获得结果，而不会加载其响应。
- end point：端点 https://www.cloudflare.com/zh-cn/learning/security/glossary/what-is-endpoint/
- 错别字

```suggestion
[重定向 URL](https://www.oauth.com/oauth2-servers/redirect-uris/) 代表着 {{WebExtAPIRef("identity.launchWebAuthFlow()")}} 的端点，即会将包含访问令牌或授权码传递给扩展的 URL。浏览器会从重定向 URL 中直接提取获得结果，而不会加载其响应。
```

2024-12-04 03:20 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/identity/index.md
> +你可以调用 {{WebExtAPIRef("identity.getRedirectURL()")}} 来获取重定向 URL。此函数从扩展的 ID 派生出一个重定向 URL。为了简化测试，你应该使用 [`browser_specific_settings`](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_speci
```suggestion
你可以调用 {{WebExtAPIRef("identity.getRedirectURL()")}} 来获取重定向 URL。此函数从附加组件的 ID 派生出一个重定向 URL。为了简化测试，你应该使用 [`browser_specific_settings`](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings) 键显式地设置附加组件的 ID（否则你每次[临时安装扩展](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/)都会得到一个不同的重定向 URL）。
```

2024-12-04 03:20 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/identity/index.md
> +{{WebExtAPIRef("identity.getRedirectURL()")}} 会返回一个 URL（其域名固定，而其子域名将从扩展的 ID 派生而来）。一些 OAuth 服务器（例如 Google）只接受具有验证所有权的域名作为重定向 URL。由于虚拟域名无法由编写扩展的开发者控制，因此默认域名并不总是可用。
```suggestion
{{WebExtAPIRef("identity.getRedirectURL()")}} 会返回一个 URL（其域名固定，而其子域名将从附加组件的 ID 派生而来）。一些 OAuth 服务器（例如 Google）只接受具有验证所有权的域名作为重定向 URL。由于虚拟域名无法由编写扩展的开发者控制，因此默认域名并不总是可用。
```

2024-12-04 03:20 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/identity/index.md
> +- 将其作为 `url` 实参对应的的 URL 形参传递给 `identity.launchWebAuthFlow()` 时。
```suggestion
- 将其作为 `url` 实参对应的 URL 形参传递给 `identity.launchWebAuthFlow()` 时。
```

2024-12-04 03:20 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/identity/index.md
> +在使用 OAuth2 与服务提供商一起使用之前，你必须将扩展注册为服务提供商的 OAuth2 客户端。
```suggestion
在将 OAuth2 与服务提供商一起使用之前，你必须将扩展注册为服务提供商的 OAuth2 客户端。
```

2024-12-04 03:20 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/identity/index.md
> +这通常是特定于服务提供商的，但通常意味着在提供商的网站上为你的拓展创建一个条目。在此过程中，你需要提供你的重定向 URL 并获得一个客户端 ID（有时也可能是一个密钥）。你需要将这两者都传递给 {{WebExtAPIRef("identity.launchWebAuthFlow()")}}。
```suggestion
这通常是特定于服务提供商的，但通常意味着在提供商的网站上为你的扩展创建一个条目。在此过程中，你需要提供你的重定向 URL 并获得一个客户端 ID（有时也可能是一个密钥）。你需要将这两者都传递给 {{WebExtAPIRef("identity.launchWebAuthFlow()")}}。
```

2024-12-04 03:20 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/identity/index.md
> +  - : 启动 Web 认证流。
```suggestion
  - : 启动 Web 认证流程（WAF）。
```

2024-12-04 11:45 UTC, yin1999 approved these changes
注意，Firefox 将“add-on”翻译为“附加组件”，而不是“拓展”。

2024-12-04 11:45 UTC, merged

2024-12-04 11:49 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/identity/index.md
> +你可以调用 {{WebExtAPIRef("identity.getRedirectURL()")}} 来获取重定向 URL。此函数从附加组件f的 ID 派生出一个重定向 URL。为了简化测试，你应该使用 [`browser_specific_settings`](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_sp
Done in #24932

2024-12-04 11:50 UTC, PassionPenguin commented
> 注意，Firefox 将“add-on”翻译为“附加组件”，而不是“拓展”。

oops，全错了（

2024-12-04 14:29 UTC, yin1999 commented
> > 注意，Firefox 将“add-on”翻译为“附加组件”，而不是“拓展”。
> 
> oops，全错了（

其他 PR 里面如果有类似的情况请先自己改一下，我没必要[专门给个错误的词儿](https://github.com/mdn/translated-content/pull/24871#discussion_r1868659427)给你呀 😂

2024-12-04 14:42 UTC, PassionPenguin commented
> > > 注意，Firefox 将“add-on”翻译为“附加组件”，而不是“拓展”。
> > 
> > 
> > oops，全错了（
> 
> 其他 PR 里面如果有类似的情况请先自己改一下，我没必要[专门给个错误的词儿](https://github.com/mdn/translated-content/pull/24871#discussion_r1868659427)给你呀 😂

都改掉了呀