zh-CN: create `pkcs11.uninstallModule()`
mdn/translated-content pull request #24888
Opened 2024-12-02 02:31 UTC by PassionPenguin

2024-12-07 12:56 UTC, yin1999 reviewed
请先校对一遍

2024-12-09 11:23 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/pkcs11/uninstallmodule/index.md
> +若无法找到模块或发生其他错误，该 Promise 将被拒绝并返回一个错误消息。
```suggestion
若无法找到模块或发生其他错误，该 Promise 将以错误消息拒绝。
```

2024-12-09 11:23 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/pkcs11/uninstallmodule/index.md
> +卸载名为 "pkcs11_module" 的模块：
```suggestion
卸载名为“pkcs11_module”的模块：
```

2024-12-09 11:23 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/pkcs11/uninstallmodule/index.md
> +当模块被卸载后，会返回一个没有参数兑现的 [`Promise`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)。
```suggestion
当模块被卸载后，会返回一个不以任何参数兑现的 [`Promise`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)。
```

2024-12-11 02:37 UTC, yin1999 requested changes

2024-12-11 02:37 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/pkcs11/uninstallmodule/index.md
> +卸载 Firefox 中的指定 PKCS #11 模块。
```suggestion
卸载 Firefox 中的指定名称的 PKCS #11 模块。
```

2024-12-11 02:37 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/pkcs11/uninstallmodule/index.md
> +当模块被卸载后，会返回一个不以任何参数兑现的 [`Promise`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)。
翻译还是不对， Promise 本来就是异步返回，如果是卸载后再返回岂不成同步的了。

2024-12-11 04:21 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/pkcs11/uninstallmodule/index.md
> +当模块被卸载后，会返回一个不以任何参数兑现的 [`Promise`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)。
```suggestion
[`Promise`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)，当模块被卸载后将不以任何参数兑现。
```

2024-12-14 08:44 UTC, yin1999 approved these changes
用“不带任何参数兑现”会更好些，之前的翻译容易被误解为是“没有兑现”

2024-12-14 08:44 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/pkcs11/uninstallmodule/index.md
> +[`Promise`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)，当模块被卸载后将不以任何参数兑现。
```suggestion
[`Promise`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)，当模块被卸载后将不带任何参数兑现。
```

2024-12-14 08:46 UTC, merged