zh-CN: create `sidebarAction.setTitle()`
mdn/translated-content pull request #24903
Opened 2024-12-02 05:14 UTC by PassionPenguin

2024-12-02 06:09 UTC, yin1999 reviewed
下次遇到这类问题可以联系我们，有些做法我们并不推荐。但如果只看预览网页的话又会发现不了，容易把我们不希望看到的表示方法引入到中文文档中。

2024-12-02 06:09 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/sidebaraction/settitle/index.md
> +你的扩展应该在 [sidebar_action](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/sidebar_action) manifest 键中指定侧边栏的标题（这被称为<i>“manifest 标题”</i>）。如果你没有指定 manifest 标题，它将使用默认值即扩展名。
不要使用“`<i>`”元素来表示斜体。灵活变通一点，把斜体样式加到引号里面（你可以注意到 MDN yari 渲染斜体用的不是“`<i>`”元素，你这样会破坏原有的语义）：

```suggestion
你的扩展应该在 [sidebar_action](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/sidebar_action) manifest 键中指定侧边栏的标题（这被称为“_manifest 标题_”）。如果你没有指定 manifest 标题，它将使用默认值即扩展名。
```

2024-12-02 06:09 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/sidebaraction/settitle/index.md
> +如果你使用 `setTitle()` 设置新标题，并省略 `tabId` 和 `windowId` 选项，那么这将设置<i>“全局标题”</i>。全局标题将出现在所有没有设置标签特定标题的标签中，且其窗口没有设置窗口特定标题的标签中。
同理

2024-12-02 12:09 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/sidebaraction/settitle/index.md
> +你的扩展应该在 [sidebar_action](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/sidebar_action) manifest 键中指定侧边栏的标题（这被称为<i>“manifest 标题”</i>）。如果你没有指定 manifest 标题，它将使用默认值即扩展名。
well看来是不同localization team之间的策略不同，fr的team就是全部转为<i>并使用各种attribute

2024-12-04 14:51 UTC, yin1999 reviewed
还有一个上游的拼写错误：mdn/content#37095

2024-12-04 14:51 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/sidebaraction/settitle/index.md
> +你的附加组件应该在 [sidebar_action](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/sidebar_action) manifest 键中指定侧边栏的标题（这被称为“_manifest 标题_”）。如果你没有指定 manifest 标题，它将使用默认值即附加组件名。
manifest 可以翻译成“manifest”，我们在之前的文档里面一直是这么翻译的，其他 PR 也统一一下。

2024-12-04 14:53 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/sidebaraction/settitle/index.md
> +你的附加组件应该在 [sidebar_action](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/sidebar_action) manifest 键中指定侧边栏的标题（这被称为“_manifest 标题_”）。如果你没有指定 manifest 标题，它将使用默认值即附加组件名。
噢好

2024-12-04 14:54 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/sidebaraction/settitle/index.md
> +你的附加组件应该在 [sidebar_action](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/sidebar_action) manifest 键中指定侧边栏的标题（这被称为“_manifest 标题_”）。如果你没有指定 manifest 标题，它将使用默认值即附加组件名。
```suggestion
你的附加组件应该在 [sidebar_action](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/sidebar_action)“manifest”键中指定侧边栏的标题（这被称为“_manifest 标题_”）。如果你没有指定“manifest”标题，它将使用默认值即附加组件名。
```

2024-12-04 14:58 UTC, yin1999 commented
打错了，翻译成“清单” :/

2024-12-05 02:59 UTC, PassionPenguin commented
> 打错了，翻译成“清单” :/

ohno其他地方全改成“manifest”了

2024-12-07 12:40 UTC, yin1999 requested changes

2024-12-07 12:40 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/sidebaraction/settitle/index.md
> +你的附加组件应该在 [sidebar_action](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/sidebar_action) 清单键中指定侧边栏的标题（这被称为“_清单标题_”）。如果你没有指定清单标题，它将使用默认值即附加组件名。
```suggestion
你的扩展应该在 [sidebar_action](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/sidebar_action) 清单键中指定侧边栏的标题（这被称为“_清单标题_”）。如果你没有指定清单标题，它将使用默认值即扩展名。
```

2024-12-07 12:40 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/sidebaraction/settitle/index.md
> +如果你使用 `setTitle()` 设置新标题，并包含 `tabId` 选项，那么标题仅为给定的标签设置。这个标题称为“_标签特定标题_”。
```suggestion
如果你使用 `setTitle()` 设置新标题，并包含 `tabId` 选项，那么标题仅为给定的标签页设置。这个标题称为“_标签页特定标题_”。
```

2024-12-07 12:40 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/sidebaraction/settitle/index.md
> +如果你使用 `setTitle()` 设置新标题，并省略 `tabId` 和 `windowId` 选项，那么这将设置“_全局标题_”。全局标题将出现在所有没有设置标签特定标题的标签中，且其窗口没有设置窗口特定标题的标签中。
```suggestion
如果你使用 `setTitle()` 设置新标题，并省略 `tabId` 和 `windowId` 选项，那么这将设置“_全局标题_”。全局标题将出现在所有没有设置标签页特定标题的标签中，且其窗口没有设置窗口特定标题的标签页中。
```

2024-12-07 12:40 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/sidebaraction/settitle/index.md
> +  - : `object`。新标题和可选的目标标签页或窗口 ID。
```suggestion
  - : `object`。具有以下属性的对象：
```

2024-12-07 12:40 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/sidebaraction/settitle/index.md
> +      - : `string` 或 `null`。鼠标悬停时浏览器操作应显示的字符串。
串台了？上面和这边都错了

2024-12-07 12:40 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/sidebaraction/settitle/index.md
> +        如果 `title` 是空字符串，则使用附加组件名作为标题，但 {{WebExtAPIRef("sidebarAction.getTitle")}} 仍会提供空字符串。
```suggestion
        如果 `title` 是空字符串，则使用扩展名作为标题，但 {{WebExtAPIRef("sidebarAction.getTitle")}} 仍会提供空字符串。
```

2024-12-07 12:40 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/sidebaraction/settitle/index.md
> +        如果 `title` 为 `null`：
同

2024-12-11 02:23 UTC, yin1999 requested changes
又翻译成“拓展”了

2024-12-13 14:39 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/sidebaraction/settitle/index.md
> +如果你使用 `setTitle()` 设置新标题，并包含了 `windowId` 选项，那么标题仅为给定的窗口设置。这个标题称为“_窗口特定标题_”，并将出现在该窗口的所有标签中，这些标签没有设置标签特定标题。
```suggestion
如果你使用 `setTitle()` 设置新标题，并包含了 `windowId` 选项，那么标题仅为给定的窗口设置。这个标题称为“_窗口特定标题_”，并将出现在该窗口的所有没有设置标签页特定标题的标签页中。
```

2024-12-13 14:39 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/sidebaraction/settitle/index.md
> +如果你使用 `setTitle()` 设置新标题，并省略了 `tabId` 和 `windowId` 选项，那么这将设置“_全局标题_”。全局标题将出现在所有没有设置标签特定标题的标签中，且其窗口没有设置窗口特定标题的标签中。
```suggestion
如果你使用 `setTitle()` 设置新标题，并省略了 `tabId` 和 `windowId` 选项，那么这将设置“_全局标题_”。全局标题将出现在所有没有设置标签页特定标题的标签中，且其窗口没有设置窗口特定标题的标签页中。
```

2024-12-13 14:39 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/sidebaraction/settitle/index.md
> +        - 如果指定了 `tabId`，并且该标签页设置了特定的标签页标题，则该标签页将继承其所属窗口的标题。
```suggestion
        - 如果指定了 `tabId`，并且该标签页设置了标签页特定的标题，则该标签页将继承其所属窗口的标题。
```

2024-12-13 14:39 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/sidebaraction/settitle/index.md
> +  sourceCommit: b8a0743ca8b1e1b1b1a95cc93a4413c020f11262
```suggestion
  sourceCommit: 665b94c45d49c71009c3e6c9a9e0f601b6af0d82
```

2024-12-13 14:40 UTC, yin1999 approved these changes

2024-12-13 14:43 UTC, merged