[ja]: ranslate RDF documentation
mdn/translated-content pull request #24911
Opened 2024-12-02 18:10 UTC by OHMORIYUSUKE

### Description

RDF の英語ドキュメントを日本語に翻訳しました。
https://developer.mozilla.org/en-US/docs/Glossary/RDF

### Motivation

### Additional details

### Related issues and pull requests

2024-12-03 12:41 UTC, mfuji09 requested changes
1件を確認してください。

2024-12-03 12:41 UTC, mfuji09 commented on files/ja/glossary/rdf/index.md
> +**RDF**（Resource Description Framework）は、W3C によって開発された、ウェブページなどのワールドワイドウェブ上の情報を表現するための言語である。RDF は、リソース情報をエンコードする標準的な方法を提供し、アプリケーション間で完全に自動化された方法で交換できるようにします。
語尾が統一されていない部分があったので、統一をお願いします。

```suggestion
**RDF**（Resource Description Framework）は、W3C によって開発された、ウェブページなどのワールドワイドウェブ上の情報を表現するための言語です。RDF は、リソース情報をエンコードする標準的な方法を提供し、アプリケーション間で完全に自動化された方法で交換できるようにします。
```

2024-12-03 14:09 UTC, OHMORIYUSUKE commented on files/ja/glossary/rdf/index.md
> +**RDF**（Resource Description Framework）は、W3C によって開発された、ウェブページなどのワールドワイドウェブ上の情報を表現するための言語である。RDF は、リソース情報をエンコードする標準的な方法を提供し、アプリケーション間で完全に自動化された方法で交換できるようにします。
ありがとうございます。修正しました。

2024-12-04 14:19 UTC, mfuji09 approved these changes
ありがとうございました。OKです。

2024-12-04 14:19 UTC, merged