[zh-cn]: update for CSS basic shape
mdn/translated-content pull request #24914
Opened 2024-12-03 06:41 UTC by fuchunhui

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-12-04 03:01 UTC, yin1999 commented on files/zh-cn/web/css/basic-shape/index.md
> +在这个示例中，我们使用了[@keyframes](/zh-CN/docs/Web/CSS/@keyframes) {{cssxref("At-rule", "at 规则")}}为两个多边形之间的裁剪路径创建动画效果。请注意，这两个多边形必须具有相同数量的顶点，这是此类动画能够正常工作的必要条件。
英文文档貌似没加这个链接

```suggestion
在这个示例中，我们使用了[@keyframes](/zh-CN/docs/Web/CSS/@keyframes) at 规则为两个多边形之间的裁剪路径创建动画效果。请注意，这两个多边形必须具有相同数量的顶点，这是此类动画能够正常工作的必要条件。
```

2024-12-06 04:30 UTC, fuchunhui commented on files/zh-cn/web/css/basic-shape/index.md
🫡

2024-12-06 04:42 UTC, fuchunhui commented on files/zh-cn/web/css/basic-shape/index.md
> +  - : 为[通过容器内边距定义的矩形](#通过容器内边距定义矩形的语法)、[通过距离定义的矩形](#通过距离定义矩形的语法)以及[具有尺寸的矩形](#具有尺寸的矩形语法)定义圆角，使用与 CSS [`border-radius`](/zh-CN/docs/Web/CSS/border-radius) 缩写属性相同的语法。
是我理解错误了，综合看了下 inset 的使用，保留 inset 比较合适。

2024-12-06 04:52 UTC, fuchunhui commented on files/zh-cn/web/css/basic-shape/index.md
> +在两个 `<basic-shape>` 函数的列表中，每个值都基于其计算值进行插值，计算值可能是 {{cssxref("number")}}、{{cssxref("length")}}、{{cssxref("percentage")}}、{{cssxref("angle")}} 或可能为 {{cssxref("calc", "calc()")}}。如果值不是这些数据类型之一，但在两个进行插值的基
好的，你说的有道理。我调整下，再帮忙看看是否合适。

2024-12-06 05:01 UTC, fuchunhui commented on files/zh-cn/web/css/basic-shape/index.md
> +在这个示例中，我们使用了[@keyframes](/zh-CN/docs/Web/CSS/@keyframes) {{cssxref("At-rule", "at 规则")}}为两个多边形之间的裁剪路径创建动画效果。请注意，这两个多边形必须具有相同数量的顶点，这是此类动画能够正常工作的必要条件。
是的，英文文档没有加链接。增加想帮助读者更好理解这里是一个整体的概念。
考虑到可能大多数读者对这个规则也比较陌生，且增加链接不会影响文档的上下文，所以增加了链接操作。

2024-12-07 12:33 UTC, yin1999 requested changes

2024-12-07 12:33 UTC, yin1999 commented on files/zh-cn/web/css/basic-shape/index.md
> +`<basic-shape>` 数据类型用于创建基本形状，包括通过[容器 inset](#通过容器 inset 定义矩形的语法)、通过[坐标距离](#通过距离定义矩形的语法)，或通过[设定尺寸](#具有尺寸的矩形语法)、[圆形](#圆形语法)、[椭圆形](#椭圆形语法)、[多边形](#多边形语法)、[路径](#路径语法)以及[作者创建的形状](#形状语法)。这些基本形状是使用一个 `<basic
这里的第一个 hash 不对，请记一下，MDN yari 的规则大致是这样的：

- 将小标题中的开头和结尾的*无用字符*删去（这里的无用字符大概包含英文的空白字符、英文的绝大多数标点符号，注意，不包含减号）
- 将小标题中的连续无用字符替换为*一个下划线*

如果你不确定规则，最简单的方法是调出开发者工具的页面，查看对应小标题的 `id` 属性。

检查渲染页面：

![image](https://github.com/user-attachments/assets/a6ce91f2-7ebd-4f1c-987e-a65c27891344)

2024-12-07 12:33 UTC, yin1999 commented on files/zh-cn/web/css/basic-shape/index.md
> +  - : 为[通过容器 inset 定义的矩形](#通过容器 inset 定义矩形的语法)、[通过距离定义的矩形](#通过距离定义矩形的语法)以及[具有尺寸的矩形](#具有尺寸的矩形语法)定义圆角，使用与 CSS [`border-radius`](/zh-CN/docs/Web/CSS/border-radius) 缩写属性相同的语法。
同

2024-12-12 13:55 UTC, fuchunhui commented on files/zh-cn/web/css/basic-shape/index.md
> +在这个示例中，我们使用了[@keyframes](/zh-CN/docs/Web/CSS/@keyframes) {{cssxref("At-rule", "at 规则")}}为两个多边形之间的裁剪路径创建动画效果。请注意，这两个多边形必须具有相同数量的顶点，这是此类动画能够正常工作的必要条件。
好的

2024-12-12 14:01 UTC, fuchunhui commented on files/zh-cn/web/css/basic-shape/index.md
> +`<basic-shape>` 数据类型用于创建基本形状，包括通过[容器 inset](#通过容器 inset 定义矩形的语法)、通过[坐标距离](#通过距离定义矩形的语法)，或通过[设定尺寸](#具有尺寸的矩形语法)、[圆形](#圆形语法)、[椭圆形](#椭圆形语法)、[多边形](#多边形语法)、[路径](#路径语法)以及[作者创建的形状](#形状语法)。这些基本形状是使用一个 `<basic
我检查下

2024-12-13 06:40 UTC, fuchunhui commented on files/zh-cn/web/css/basic-shape/index.md
> +`<basic-shape>` 数据类型用于创建基本形状，包括通过[容器 inset](#通过容器 inset 定义矩形的语法)、通过[坐标距离](#通过距离定义矩形的语法)，或通过[设定尺寸](#具有尺寸的矩形语法)、[圆形](#圆形语法)、[椭圆形](#椭圆形语法)、[多边形](#多边形语法)、[路径](#路径语法)以及[作者创建的形状](#形状语法)。这些基本形状是使用一个 `<basic
感谢技巧的分享，很受用。

2024-12-13 12:26 UTC, yin1999 approved these changes
Thank you @fuchunhui

2024-12-13 12:26 UTC, merged