zh-CN: create `management.getSelf()`
mdn/translated-content pull request #24939
Opened 2024-12-04 11:55 UTC by PassionPenguin

2024-12-09 11:39 UTC, PassionPenguin reviewed
-

2024-12-18 13:20 UTC, yin1999 requested changes

2024-12-18 13:20 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/management/getself/index.md
> +获取有关调用该方法的插件的包含在 {{WebExtAPIRef("management.ExtensionInfo", "ExtensionInfo")}} 对象中的信息。
```suggestion
获取包含了有关调用该方法的附加组件的信息的 {{WebExtAPIRef("management.ExtensionInfo", "ExtensionInfo")}} 对象。
```

2024-12-18 13:20 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/management/getself/index.md
> +这是一个异步函数，返回一个 [`Promise`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)。
```suggestion
这是一个返回 [`Promise`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise) 的异步函数。
```

2024-12-18 13:20 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/management/getself/index.md
> +[`Promise`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)，将用包含有关附加组件的信息的 {{WebExtAPIRef("management.ExtensionInfo", "ExtensionInfo")}} 对象兑现。
```suggestion
[`Promise`](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)，会兑现为包含有关附加组件的信息的 {{WebExtAPIRef("management.ExtensionInfo", "ExtensionInfo")}} 对象。
```

2024-12-21 14:06 UTC, yin1999 approved these changes

2024-12-21 14:06 UTC, merged