[ko] window blur event 신규 번역
mdn/translated-content pull request #24949
Opened 2024-12-04 11:57 UTC by givvemee

### Description

기존에 한국어로 존재하지 않던 문서 [blur_event](https://developer.mozilla.org/en-US/docs/Web/API/Window/blur_event) 를 번역합니다.

### Motivation

### Additional details

### Related issues and pull requests

2025-01-14 15:25 UTC, hochan222 requested changes
@givvemee 님 안녕하세요.

한가지 리뷰 사항 남겨두었습니다. 기여해주셔서 감사합니다.

새해 복 많이 받으세요!

2025-01-14 15:25 UTC, hochan222 commented on files/ko/web/api/window/blur_event/index.md
> +메서드의 이벤트 이름을 {{domxref("EventTarget.addEventListener", "addEventListener()")}} 처럼 사용하거나 이벤트 핸들러 속성을 설정해야 합니다.
```suggestion
이벤트 이름을 {{domxref("EventTarget.addEventListener", "addEventListener()")}}와 같은 메서드에서 사용하거나 이벤트 핸들러 속성을 설정해야 합니다.
```
문장의 의미가 약간 다른듯하여 제안드립니다!

2025-01-19 01:52 UTC, givvemee commented
@hochan222 고맙습니다. 복 많이 받으세요!

2025-01-22 13:05 UTC, hochan222 approved these changes
LGTM

2025-01-22 13:05 UTC, merged