zh-CN: create `management.getPermissionWarningsByManifest()`
mdn/translated-content pull request #24941
Opened 2024-12-04 11:55 UTC by PassionPenguin

2024-12-08 07:20 UTC, JasonLamv-t requested changes
Well done! Need some improvements.

2024-12-08 07:20 UTC, JasonLamv-t commented on files/zh-cn/mozilla/add-ons/webextensions/api/management/getpermissionwarningsbymanifest/index.md
> +给定 [manifest.json](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json) 文件的文本，此函数以字符串数组形式返回生成的附加组件的权限警告。
```suggestion
给定 [manifest.json](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json) 文件的文本，此函数以字符串数组形式返回针对附加组件的权限警告。
```

2024-12-08 07:20 UTC, JasonLamv-t commented on files/zh-cn/mozilla/add-ons/webextensions/api/management/getpermissionwarningsbymanifest/index.md
> +  - : `string`，包含清单文件的字符串。这必须是有效的清单：比如说它必须包含所有强制性的清单键。
```suggestion
  - : `string`，包含清单文件的字符串。必须是有效的清单：比如说它必须包含所有必须的清单键。
```

2024-12-08 07:20 UTC, JasonLamv-t commented on files/zh-cn/mozilla/add-ons/webextensions/api/management/getpermissionwarningsbymanifest/index.md
> +记录给定清单文件的权限警告：
```suggestion
打印给定清单文件的权限警告：
```

2024-12-09 11:07 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/management/getpermissionwarningsbymanifest/index.md
> +  - : `string`，包含清单文件的字符串。这必须是有效的清单，例如说它必须包含所有强制性的清单键。
```suggestion
  - : `string`，包含清单文件的字符串。必须是有效的清单，例如它必须包含所有强制性的清单键。
```

2024-12-09 18:38 UTC, JasonLamv-t approved these changes
LGTM.

2024-12-09 18:38 UTC, merged