zh-CN: create `userScripts.register()`
mdn/translated-content pull request #24966
Opened 2024-12-06 13:53 UTC by PassionPenguin

2024-12-17 08:03 UTC, yin1999 requested changes
翻译后请打开内容预览页面和英文文档的内容对照一遍，我提过好多次了

2025-02-27 03:17 UTC, jasonren0403 requested changes, later dismissed
本页面的内容目前由 https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/userscripts_legacy/register/index.md?plain=1 承接，需要更新一下 slug 并加上 warning 标志

2025-02-28 13:03 UTC, PassionPenguin commented
> 本页面的内容目前由 https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/userscripts_legacy/register/index.md?plain=1 承接，需要更新一下 slug 并加上 warning 标志

oops，好的

2025-02-28 13:31 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/userscripts_legacy/register/index.md
> +> 当与用户脚本相关联的扩展页面（注册了用户脚本的页面）被卸载时，用户脚本将被自动注销。因此，你应当从一个生命周期足够长的扩展页面注册用户脚本 —— 这一页面的存续时间应至少需要覆盖你期望用户脚本保持注册状态的整个周期。
```suggestion
> 当与用户脚本相关联的扩展页面（注册了用户脚本的页面）被卸载时，用户脚本将被自动注销。因此，你应当在一个存活时间至少与你的用户脚本相当的扩展页面中注册该脚本。
```

2025-03-01 02:22 UTC, yin1999 approved these changes

2025-03-01 02:24 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/userscripts_legacy/register/index.md
> +- {{WebExtAPIRef("userScripts.RegisteredUserScript.unregister","RegisteredUserScript.unregister()")}}
```suggestion
- {{WebExtAPIRef("userScripts_legacy.RegisteredUserScript.unregister","RegisteredUserScript.unregister()")}}
```

2025-03-01 02:24 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/userscripts_legacy/register/index.md
> +{{JSxRef("Promise")}}，会兑现为一个用于注销用户脚本的 {{WebExtAPIRef("userScripts.RegisteredUserScript","RegisteredUserScript")}} 对象。
```suggestion
{{JSxRef("Promise")}}，会兑现为一个用于注销用户脚本的 {{WebExtAPIRef("userScripts_legacy.RegisteredUserScript","RegisteredUserScript")}} 对象。
```

2025-03-01 02:24 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/userscripts_legacy/register/index.md
> +该方法与 {{WebExtAPIRef("contentScripts.register","contentScripts.register()")}} API 方法非常相似（例如，它们都返回一个 Promise，且都会以一个具有 {{WebExtAPIRef("userScripts.RegisteredUserScript.unregister","unregister()")}} 方法（用
```suggestion
该方法与 {{WebExtAPIRef("contentScripts.register","contentScripts.register()")}} API 方法非常相似（例如，它们都返回一个 Promise，且都会以一个具有 {{WebExtAPIRef("userScripts_legacy.RegisteredUserScript.unregister","unregister()")}} 方法（用于注销脚本）的 API 对象兑现）。但是，支持的选项有所区别。
```

2025-03-01 02:24 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/userscripts_legacy/register/index.md
> +该方法允许从扩展的页面（例如后台页面）注册用户脚本。
```suggestion
该方法允许在扩展的页面（例如后台页面）注册用户脚本。
```

2025-03-01 02:27 UTC, merged