zh-CN: create `userScripts.RegisteredUserScript`
mdn/translated-content pull request #24965
Opened 2024-12-06 13:53 UTC by PassionPenguin

2024-12-18 07:56 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/userscripts/registereduserscript/index.md
> +> 如果此对象被销毁（例如因为超出作用域），则相关脚本将自动注销，因此你应该保留对此对象的引用，以便用户脚本保持注册的时间。
和 https://github.com/mdn/translated-content/pull/24964#discussion_r1888036412 的问题类似

2025-02-27 03:15 UTC, jasonren0403 requested changes, later dismissed
see https://github.com/mdn/translated-content/pull/24964#pullrequestreview-2646461262

本页面的内容目前由 https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/userscripts_legacy/registereduserscript/index.md?plain=1 承接了

2025-03-01 02:32 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/userscripts_legacy/registereduserscript/index.md
> +- {{WebExtAPIRef("userScripts.RegisteredUserScript.unregister","unregister()")}}
```suggestion
- {{WebExtAPIRef("userScripts_legacy.RegisteredUserScript.unregister","unregister()")}}
```

2025-03-01 02:32 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/userscripts_legacy/registereduserscript/index.md
> +该对象定义了用于注销用户脚本的 {{WebExtAPIRef("userScripts.RegisteredUserScript.unregister","unregister()")}} 方法。
```suggestion
`RegisteredUserScript` 对象是通过调用 {{WebExtAPIRef("userScripts_legacy.register","userScripts.register()")}} 返回的，表示在该调用中注册的用户脚本。

该对象定义了用于注销用户脚本的 {{WebExtAPIRef("userScripts_legacy.RegisteredUserScript.unregister","unregister()")}} 方法。
```

2025-03-01 02:32 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/userscripts_legacy/registereduserscript/index.md
> +> 如果与用户脚本相关联的这一对象被销毁（例如因为超出作用域），则用户脚本将自动注销。因此，只要你仍希望你的用户脚本保持注册状态，你就应该仍然保存好这一对象的引用。
```suggestion
> 如果与用户脚本相关联的这一对象被销毁（例如因为超出作用域），则用户脚本将自动注销。因此，只要你希望用户脚本保持注册状态，就应保留对此对象的引用。
```

2025-03-01 02:34 UTC, yin1999 approved these changes

2025-03-01 02:34 UTC, merged