[ko] window screenx 신규 번역
mdn/translated-content pull request #25002
Opened 2024-12-11 11:09 UTC by givvemee

### Description

기존에 한국어로 존재하지 않던 문서 [screenX](https://developer.mozilla.org/en-US/docs/Web/API/Window/screenX)를 신규 번역합니다.

### Motivation

### Additional details

### Related issues and pull requests

2024-12-18 15:27 UTC, 1ilsang requested changes
@givvemee 님 안녕하세요. 기여해주셔서 감사합니다! 💯

몇 가지 코멘트 남겨두었습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🙇

질문이나 도움이 필요하시다면 언제든 멘션 부탁드리겠습니다.

2024-12-18 15:27 UTC, 1ilsang commented on files/ko/web/api/window/screenx/index.md
> +또한 코드에서는 `screenLeft` 을 지원하는지, 만일 지원하지 않으면 `screenLeft`/`screenTop` 의 폴리필을 `screenX`/`screenY` 로 사용할 수 있도록 탐지하기 위해 스니펫이 추가되었습니다.
```suggestion
또한 코드에서는 `screenLeft` 을 지원하는지, 만일 지원하지 않으면
`screenLeft`/`screenTop` 의 폴리필을 `screenX`/`screenY` 로 사용할 수 있도록
탐지하기 위해 스니펫이 추가되었습니다.
```

줄 수는 원문과 같이 유지해 주세요. 관련 논의는 [여기](https://github.com/orgs/mdn/discussions/655#discussioncomment-9251708)에서 확인할 수 있습니다.

2024-12-18 15:27 UTC, 1ilsang commented on files/ko/web/api/window/screenx/index.md
> +**`Window.screenX`** 읽기 전용 속성은 사용자의 브라우저 뷰포트의 왼쪽 테두리에서 화면 왼편까지의 수평 거리를 CSS 픽셀 단위로 반환합니다.
```suggestion
**`Window.screenX`** 읽기 전용 속성은
사용자의 브라우저 뷰포트의 왼쪽 테두리에서 화면 왼편까지의 수평 거리를
CSS 픽셀 단위로 반환합니다.
```

줄 수는 원문과 같이 유지해 주세요. 관련 논의는 [여기](https://github.com/orgs/mdn/discussions/655#discussioncomment-9251708)에서 확인할 수 있습니다.

2024-12-18 15:27 UTC, 1ilsang commented on files/ko/web/api/window/screenx/index.md
> +> [!NOTE] > `screenX` 의 별칭은 최신 브라우저에
```suggestion
> [!NOTE]
> `screenX` 의 별칭은 최신 브라우저에
```

여기 개행이 안되어있네요.

2024-12-21 06:56 UTC, givvemee commented on files/ko/web/api/window/screenx/index.md
> +> [!NOTE] > `screenX` 의 별칭은 최신 브라우저에
@1ilsang 이걸 개행하면 lint error 가 발생하네요!? 흠 ...

2024-12-21 16:00 UTC, 1ilsang commented on files/ko/web/api/window/screenx/index.md
> +> [!NOTE] > `screenX` 의 별칭은 최신 브라우저에
`bracketSameLine` 룰이랑 충돌나는 부분이네요. 이 부분은 따로 수정이 되어야 할 것 같습니다.

PR은 머지하도록 하겠습니다. 고생하셨습니다.

2024-12-21 16:00 UTC, 1ilsang approved these changes

2024-12-21 16:00 UTC, merged