[zh-TW]: update @font-face
mdn/translated-content pull request #25000
Opened 2024-12-11 09:20 UTC by Dr-XYZ

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-12-11 11:50 UTC, Dr-XYZ commented
#13196

2024-12-19 06:11 UTC, yin1999 requested changes
有些错误需要更正

2024-12-19 06:11 UTC, yin1999 commented on files/zh-tw/web/css/@font-face/index.md
> +  - : 指定字型所使用的 Unicode 編碼範圍。
同，这里也改错了。请参考[维基百科](https://zh.wikipedia.org/zh-cn/%E7%A0%81%E4%BD%8D)

```suggestion
  - : 指定字型所使用的 Unicode 碼位範圍。
```

2024-12-19 06:11 UTC, yin1999 commented on files/zh-tw/web/css/@font-face/index.md
> +> 有關為舊版瀏覽器加載字型的回退策略，請參考 [`src` 參數值頁面](/zh-TW/docs/Web/CSS/@font-face/src#specifying_fallbacks_for_older_browsers)。
这句的翻译感觉不用调整，关于词汇的翻译还请准确使用。

```suggestion
> 有關為舊版瀏覽器加載字型的回退策略，請參考 [`src` 描述符頁面](/zh-TW/docs/Web/CSS/@font-face/src#指定舊版瀏覽器的後備方案)。
```

2024-12-19 06:11 UTC, yin1999 commented on files/zh-tw/web/css/@font-face/index.md
> +通過允許作者提供自己的字型，`@font-face` 使內容設計不再受限於所謂的「網頁安全字型」（即被認為是普遍可用的常見字型）。指定本地安裝字型的名稱，允許在不依賴網際網路連接的情況下，超越基礎字型進行客製化。
```suggestion
通過允許作者提供自己的字型，`@font-face` 使內容設計不再受限於所謂的「Web 安全」字型（即被認為是普遍可用的常見字型）。指定本地安裝字型的名稱，允許在不依賴網際網路連接的情況下，超越基礎字型進行客製化。
```

2024-12-19 06:11 UTC, yin1999 commented on files/zh-tw/web/css/@font-face/index.md
> +`@font-face` 規則不僅可用於 CSS 的頂層，也可以用於任何 [CSS 條件群組規則](/zh-TW/docs/Web/CSS/CSS_conditional_rules#at-rules)中。
```suggestion
`@font-face` 規則不僅可用於 CSS 的頂層，也可以用於任何 [CSS 條件群組 @ 規則](/zh-TW/docs/Web/CSS/CSS_conditional_rules#at_規則)中。
```

2024-12-19 06:11 UTC, yin1999 commented on files/zh-tw/web/css/@font-face/index.md
> +| Web Open Font Format 2 | `font/woff2` |
这里的是可以翻译的，https://zh.wikipedia.org/wiki/Web%E9%96%8B%E6%94%BE%E5%AD%97%E5%9E%8B%E6%A0%BC%E5%BC%8F

2024-12-19 06:11 UTC, yin1999 commented on files/zh-tw/web/css/@font-face/index.md
> +- 網頁字型受相同的域名限制（字型檔案必須與使用它們的頁面在同一域名），除非使用 [HTTP 存取控制](/zh-TW/docs/Web/HTTP/CORS)來放寬此限制。
不应把“的”放到前面，CORS 的限制是包括不“跨域名”——“相同域名”的。这句翻译都可以不修改（“網域”这一翻译也是正确的：<https://zh.wikipedia.org/wiki/域名>）

```suggestion
- Web 字型受相同域名的限制（字型檔案必須與使用它們的頁面在同一域名），除非使用 [HTTP 存取控制](/zh-TW/docs/Web/HTTP/CORS)來放寬此限制。
```

2024-12-19 06:11 UTC, yin1999 commented on files/zh-tw/web/css/@font-face/index.md
> +- `@font-face` 不能宣告於 CSS 選擇器內。例如，下列範例將無效：
我感觉原来的翻译更好

2024-12-19 06:11 UTC, yin1999 commented on files/zh-tw/web/css/@font-face/index.md
> +  This is Bitstream Vera Serif Bold.
可以翻译一下

2024-12-19 06:11 UTC, yin1999 commented on files/zh-tw/web/css/@font-face/index.md
> +- [使用 @font-face 創建漂亮字型](https://hacks.mozilla.org/2009/06/beautiful-fonts-with-font-face/)
`@font-face` 不是用来创建字体的，这里的翻译是错误的（不如原有的翻译）

2024-12-19 11:59 UTC, yin1999 approved these changes

2024-12-19 11:59 UTC, merged