zh-CN: create a translation of `Speculation Rules API`
mdn/translated-content pull request #25059
Opened 2024-12-15 04:04 UTC by melxy1997

### Description

增加了关于推测规则API（[Speculation_Rules_API](https://developer.mozilla.org/en-US/docs/Web/API/Speculation_Rules_API)）的中文版本

2024-12-15 07:08 UTC, yin1999 requested changes
再检查一下，简单看了一遍，具有的问题如下：

- 标点符号使用（中文内容需使用全角的标点，小的项目之间的并列需使用顿号，不应使用逗号）
- 中文之间不应有空格，需删除
- 有英文内容尚未翻译
- 中英文之间应保留一个空格
- 部分术语、小标题的翻译需改正，参见[术语表](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/glossary.md)

我先将 PR 转换为草稿了，请在准备完毕后再将其转换为“可供审查”。

2024-12-16 01:37 UTC, yin1999 commented on files/zh-cn/web/api/speculation_rules_api/index.md
> +            { "not"：{ "selector_matches"："[rel~=nofollow]" } }
json 的冒号不需要替换，注意一下（下文中也是）

2024-12-16 18:19 UTC, skyclouds2001 commented on files/zh-cn/web/api/speculation_rules_api/index.md
> +> 许多 API 在预渲染/激活时会被自动推迟。具体细节见 [在预渲染期间推迟或限制的平台功能](#在预渲染期间推迟或限制的平台功能)。
```suggestion
> 许多 API 在预渲染/激活时会被自动推迟。具体细节见[在预渲染期间推迟或限制的平台功能](#在预渲染期间推迟或限制的平台功能)。
```

2024-12-16 18:21 UTC, skyclouds2001 commented on files/zh-cn/web/api/speculation_rules_api/index.md
> +  - ：用于在当前文档中定义一组预加载和/或预渲染推测规则，这些规则被添加到文档的推测规则集中。
```suggestion
  - : 用于在当前文档中定义一组预加载和/或预渲染推测规则，这些规则被添加到文档的推测规则集中。
```

类似这样的结构是 MDN 文档的一种格式，这里的冒号也不应当替换；上同

2024-12-16 18:21 UTC, skyclouds2001 commented on files/zh-cn/web/api/speculation_rules_api/index.md
> +  - 用于选择允许在正在获取的文档上使用 `<script type="speculationrules">`来定义推测规则。
```suggestion
  - 用于选择允许在正在获取的文档上使用 `<script type="speculationrules">` 来定义推测规则。
```

2024-12-17 01:26 UTC, melxy1997 commented on files/zh-cn/web/api/speculation_rules_api/index.md
> +  - 用于选择允许在正在获取的文档上使用 `<script type="speculationrules">`来定义推测规则。
🫡fixed

2024-12-17 01:26 UTC, melxy1997 commented on files/zh-cn/web/api/speculation_rules_api/index.md
> +  - ：用于在当前文档中定义一组预加载和/或预渲染推测规则，这些规则被添加到文档的推测规则集中。
🫡fixed

2024-12-17 01:26 UTC, melxy1997 commented on files/zh-cn/web/api/speculation_rules_api/index.md
> +- [推测性加载](/zh-CN/docs/Web/Performance/Speculative_loading) 比较推测规则和其他类似的性能改进功能。
🫡fixed

2024-12-17 01:26 UTC, melxy1997 commented on files/zh-cn/web/api/speculation_rules_api/index.md
> +## 另见
🫡fixed

2024-12-17 01:26 UTC, melxy1997 commented on files/zh-cn/web/api/speculation_rules_api/index.md
> +> 许多 API 在预渲染/激活时会被自动推迟。具体细节见 [在预渲染期间推迟或限制的平台功能](#在预渲染期间推迟或限制的平台功能)。
🫡fixed

2024-12-17 01:26 UTC, melxy1997 commented on files/zh-cn/web/api/speculation_rules_api/index.md
> +            { "not"：{ "selector_matches"："[rel~=nofollow]" } }
🫡fixed

2024-12-17 06:19 UTC, yin1999 commented
> 再检查一下，简单看了一遍，具有的问题如下：
> 
> * 标点符号使用（中文内容需使用全角的标点，小的项目之间的并列需使用顿号，不应使用逗号）
> * 中文之间不应有空格，需删除
> * 有英文内容尚未翻译
> * 中英文之间应保留一个空格
> * 部分术语、小标题的翻译需改正，参见[术语表](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/glossary.md)
> 
> 我先将 PR 转换为草稿了，请在准备完毕后再将其转换为“可供审查”。

这里说的有些问题还是没处理好的，请再检查一下，比如 @skyclouds2001 提到的问题：https://github.com/mdn/translated-content/pull/25059#discussion_r1887295812

2024-12-17 13:15 UTC, melxy1997 commented
> > 再检查一下，简单看了一遍，具有的问题如下：
> > 
> > * 标点符号使用（中文内容需使用全角的标点，小的项目之间的并列需使用顿号，不应使用逗号）
> > * 中文之间不应有空格，需删除
> > * 有英文内容尚未翻译
> > * 中英文之间应保留一个空格
> > * 部分术语、小标题的翻译需改正，参见[术语表](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/glossary.md)
> > 
> > 我先将 PR 转换为草稿了，请在准备完毕后再将其转换为“可供审查”。
> 
> 这里说的有些问题还是没处理好的，请再检查一下，比如 @skyclouds2001 提到的问题：[#25059 (comment)](https://github.com/mdn/translated-content/pull/25059#discussion_r1887295812)
好的，已修改

2024-12-20 11:57 UTC, yin1999 approved these changes
感谢贡献，以后请注意我提到的这几个问题

2024-12-20 11:58 UTC, merged