[ko] Status-412 신규 번역
mdn/translated-content pull request #25101
Opened 2024-12-16 11:42 UTC by KKangHHee

### Description

- 기존에 한국어로 번역되지 않은 [Status-412](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/412) 번역
- 처음이라 부족한 부분 말씀 부탁드립니다!
### Motivation

### Additional details

### Related issues and pull requests

2024-12-18 13:59 UTC, wisedog requested changes
첫 기여 감사합니다! 나머지는 작은 수정사항인데 원문의 `Examples` 섹션이 모두 빠져있습니다. 확인 부탁드릴께요

2024-12-26 00:33 UTC, KKangHHee commented on files/ko/web/http/status/412/index.md
> +- [HTTP response status codes](/ko/docs/Web/HTTP/Status)
안녕하세요! 확인이 늦었네요ㅠㅠ 리뷰해주신 부분 수정해서 다시 올리겠습니다!! 감사합니다!

2024-12-26 03:02 UTC, wisedog commented
@KKangHHee  계속 수정중이시긴한데, 실질적으로 변경된 내용이 없습니다. 제가 도와드릴게 있을까요?

2024-12-26 03:14 UTC, KKangHHee commented
> @KKangHHee 계속 수정중이시긴한데, 실질적으로 변경된 내용이 없습니다. 제가 도와드릴게 있을까요?

안녕하세요. 번거롭게 해서 죄송합니다. 
브랜치 업데이트 후, 번역본 적용해서 올리는데 해당에서 막힘이 있는 것 같습니다. 혹시 제가 절차를 잘 지키지 못한걸까요?

2024-12-26 04:06 UTC, wisedog commented
@KKangHHee  오 이제 제대로 된 것 같네요.

2024-12-26 04:07 UTC, wisedog approved these changes
LGTM! 

첫 기여 감사하며, 자주 기여해주시길 부탁드리겠습니다! 고생하셨습니다

2024-12-26 04:33 UTC, KKangHHee commented
> LGTM!
> 
> 첫 기여 감사하며, 자주 기여해주시길 부탁드리겠습니다! 고생하셨습니다

친절한 리뷰 감사합니다!! 좋은 하루되세요 ㅎㅎ!

2024-12-27 00:02 UTC, merged