[ko] Working with the History API 번역 업데이트
mdn/translated-content pull request #25139
Opened 2024-12-18 00:15 UTC by effozen

### Description

Working with the History API 문서의 최신 업데이트 내용을 반영해서, 번역을 갱신하였습니다.

### Motivation

History API 학습 중 최신 정보가 반영되어 있지 않아, 불편함을 느껴 개선하게 되었습니다.

### Additional details

### Related issues and pull requests

2024-12-18 14:01 UTC, wisedog commented
일단 첫 기여 감사드립니다! 빠른 시일 내에 리뷰드리도록 하겠습니다.

2024-12-23 01:07 UTC, wisedog requested changes
기여 감사합니다! 첫 기여이신데, 상당히 매끄럽게 잘 PR을 해주셔서 놀랬습니다. 

앞으로도 잘 부탁드립니다. 몇 가지 소소한 수정사항을 남겼으니 수정 부탁드릴께요.

2024-12-24 08:55 UTC, effozen commented on files/ko/web/api/history_api/working_with_the_history_api/index.md
수정 완료하였습니다..!

2024-12-24 08:56 UTC, effozen commented on files/ko/web/api/history_api/working_with_the_history_api/index.md
> +예를 들어:
가이드에서 놓히고 있던 부분이 있었네요..! 이번일을 계기로 조금 더 세심하게 볼 수 있도록 하겠습니다. 친절하게 리뷰해주셔서 감사합니다. 😁 수정완료하였습니다!

2024-12-24 08:56 UTC, effozen commented on files/ko/web/api/history_api/working_with_the_history_api/index.md
> +
수정완료하였습니다!

2024-12-26 00:31 UTC, wisedog approved these changes
LGTM!

2024-12-26 00:36 UTC, merged