[zh-cn]: update the translation of HTMLSlotElement introduction
mdn/translated-content pull request #25217
Opened 2024-12-24 04:04 UTC by T34-active

### Description
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement
### Related issues and pull requests
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlslotelement/index.md
* Last commit: https://github.com/mdn/content/commit/9d5c9fbe387ba7c143fdd7c73a265b209b7f6ec4

2024-12-24 06:17 UTC, T34-active commented on files/zh-cn/web/api/htmlslotelement/index.md
> +**`HTMLSlotElement`** 接口是[影子 DOM API](/zh-CN/docs/Web/API/Web_components/Using_shadow_DOM) 的一部分，它允许访问 HTML {{HTMLElement("slot")}} 元素的名称和分配的节点。
```suggestion
通过[影子 DOM API](/zh-CN/docs/Web/API/Web_components/Using_shadow_DOM) 的 **`HTMLSlotElement`** 接口，可以访问 HTML `<slot>` 元素的名称和指定节点。
```

2024-12-25 01:55 UTC, yin1999 requested changes

2024-12-25 01:55 UTC, yin1999 commented on files/zh-cn/web/api/htmlslotelement/index.md
> +通过[影子 DOM API](/zh-CN/docs/Web/API/Web_components/Using_shadow_DOM) 的 **`HTMLSlotElement`** 接口，可以访问 HTML `<slot>` 元素的名称和指定节点。
请不要在文档最前面的术语之前再加内容了。API、事件相关的文档永远以此类特性的名称开头。

```suggestion
[影子 DOM API](/zh-CN/docs/Web/API/Web_components/Using_shadow_DOM) 的 **`HTMLSlotElement`** 接口用于访问 HTML `<slot>` 元素的名称和指定节点。
```

2024-12-25 01:55 UTC, yin1999 commented on files/zh-cn/web/api/htmlslotelement/index.md
> +_继承了其父接口 {{domxref("HTMLElement")}} 的属性。_
```suggestion
_还继承了其父接口 {{domxref("HTMLElement")}} 的属性。_
```

2024-12-25 01:55 UTC, yin1999 commented on files/zh-cn/web/api/htmlslotelement/index.md
> +_继承了其父接口 {{domxref("HTMLElement")}} 的方法。_
```suggestion
_还继承了其父接口 {{domxref("HTMLElement")}} 的方法。_
```

2024-12-25 01:55 UTC, yin1999 commented on files/zh-cn/web/api/htmlslotelement/index.md
> +  - : 返回分配给该插槽的节点序列。如果 `flatten` 选项设置为 `true`，它将返回包含分配给该插槽的节点的一个序列，以及分配给该插槽的任何后代插槽的节点。如果没有找到分配的节点，它将返回插槽的回退内容。
这段话翻译得对吗，“both”是和什么连用的

2024-12-25 01:55 UTC, yin1999 commented on files/zh-cn/web/api/htmlslotelement/index.md
> +  - : 返回分配给该插槽的元素序列（且不包括其他节点）。如果 `flatten` 选项设置为 `true`，则返回分配给该插槽的元素序列，以及分配给该插槽所有后代插槽的元素序列。如果未找到分配的元素，则返回插槽的回退内容。
这段不是和上一段很类似吗，咋会没意识到上一段翻译错了（哭死

2024-12-25 01:55 UTC, yin1999 commented on files/zh-cn/web/api/htmlslotelement/index.md
> +_继承了其父接口 {{domxref("HTMLElement")}} 的事件。_
```suggestion
_还继承了其父接口 {{domxref("HTMLElement")}} 的事件。_
```

2024-12-25 01:55 UTC, yin1999 commented on files/zh-cn/web/api/htmlslotelement/index.md
> +使用 {{DOMxRef("EventTarget.addEventListener", "addEventListener()")}} 监听这些事件，或通过将事件监听器分配给该接口的 `oneventname` 属性来监听。
```suggestion
使用 {{DOMxRef("EventTarget.addEventListener", "addEventListener()")}} 或通过将事件监听器赋值给该接口的 `oneventname` 属性来监听这些事件。
```

2024-12-25 01:55 UTC, yin1999 commented on files/zh-cn/web/api/htmlslotelement/index.md
> +    `插槽 "${slots[1].name}" 中的元素已更改为 "${nodes[0].outerHTML}"。`,
```suggestion
    `插槽“${slots[1].name}”中的元素已更改为“${nodes[0].outerHTML}”。`,
```

2025-01-07 07:01 UTC, T34-active commented on files/zh-cn/web/api/htmlslotelement/index.md
> +  - : 返回分配给该插槽的节点序列。如果 `flatten` 选项设置为 `true`，它将返回包含分配给该插槽的节点的一个序列，以及分配给该插槽的任何后代插槽的节点。如果没有找到分配的节点，它将返回插槽的回退内容。
```suggestion
  - : 返回分配给该插槽的节点序列。如果 `flatten` 选项设置为 `true`，则返回分配给该插槽的节点序列，以及分配给该插槽的任何后代插槽的节点序列。如果未找到已分配的节点，则返回插槽的回退内容。
```

2025-01-10 15:02 UTC, yin1999 approved these changes

2025-01-10 15:03 UTC, merged