zh-CN: create `pageAction.setIcon()`
mdn/translated-content pull request #25274
Opened 2024-12-30 13:43 UTC by PassionPenguin

2024-12-30 14:04 UTC, PassionPenguin commented
awaiting mdn/content#37348

2025-01-19 03:02 UTC, yin1999 requested changes
一些问题：

2025-01-19 03:02 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/pageaction/seticon/index.md
> +        浏览器将根据屏幕的像素密度选择要使用的图像。有关更多信息，请参阅[选择图标尺寸](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action#选择图标尺寸)。
```suggestion
        浏览器将根据屏幕的像素密度选择要使用的图像。有关更多信息，请参阅[选择图标大小](/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action#选择图标大小)。
```

2025-01-19 03:02 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/api/pageaction/seticon/index.md
> +      - : `integer`。要设置的标签页的 ID。
```suggestion
      - : `integer`。要设置图标的标签页的 ID。
```

2025-01-23 10:01 UTC, PassionPenguin reviewed
be consistent with others

2025-01-23 10:01 UTC, PassionPenguin commented on files/zh-cn/mozilla/add-ons/webextensions/api/pageaction/seticon/index.md
> +你可以通过提供一个图片文件的路径，或一个 {{WebExtAPIRef('sidebarAction.ImageDataType')}} 对象来指定单独一个图标。
```suggestion
你可以指定图片文件的路径或 {{WebExtAPIRef('sidebarAction.ImageDataType')}} 对象作为单个图标。
```

2025-01-23 12:29 UTC, yin1999 approved these changes

2025-01-23 12:29 UTC, merged