Svelte todo list beginning (zh-TW translation) (partial)
mdn/translated-content pull request #2587
Opened 2021-09-27 08:02 UTC by cdcd72

新增翻譯下列區段：
- Svelte accessibility support
- Styling our markup
- The code so far
- Summary

2021-09-27 15:47 UTC, t7yang requested changes

2021-09-27 15:47 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/svelte_todo_list_beginning/index.html
> +<p><strong>注意</strong>：假如你有足夠充分的理由，則可以先停用這些警示，例如當你在快速建構原型時。成為一個優秀的網路公民並讓你的頁面盡可能廣泛地被用戶訪問是很重要的。</p>
讓你的網頁盡可能被廣泛的使用者群體無障礙地取用／閱讀／存取。

不要用「訪問」或「拜訪」，這類詞彙更像是用於人對人之間的互動。中國的翻譯很喜歡用，但我個人不建議使用。

2021-09-27 15:47 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/svelte_todo_list_beginning/index.html
> +<p>Svelte則透過<a href="https://github.com/jsx-eslint/eslint-plugin-jsx-a11y#supported-rules">eslint-plugin-jsx-a11y</a>來檢查這些無障礙性規則，它是提供在JSX元素上許多無障礙性規則靜態檢查的一個eslint外掛。Svelte企圖將它們全部實現於編譯器中，而大部分都已經移植至Svel
> Svelte則透過<a href="https://github.com/jsx-eslint/eslint-plugin-jsx-a11y#supported-rules">eslint-plugin-jsx-a11y</a>來檢查這些無障礙性規則

「則」不需要，這裡沒有對應前文的轉折。「這些」也不需要，前文並沒有列舉規則，使得「這些」失去參照的對象顯得詭異。原文也沒有這個意思。

> 在GitHub中你還可以看到<a href="https://github.com/sveltejs/svelte/issues/820">仍缺少哪些無障礙檢核</a>。

你可以在Github中看到尚未實現的無障礙檢核。

> 你可以點擊連結來了解每一條規則代表什麼意思。

點選規則的連結可以查閱它們的涵義。

這裡有一些翻譯技巧

- 在英翻中時，如果代名詞是可以省略的，就省略。過多的代名詞會使得中文在閱讀上不通順也失去美感。
- 這裡的 each 有複數的意思，但中文其實沒有這個概念，所以在英翻中時，在不影響原文含意的情況下，選擇規避往往可以提升整體的閱讀性。

2021-09-27 15:47 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/svelte_todo_list_beginning/index.html
> +<h2 id="Styling_our_markup">樣式化我們的標記</h2>
建議：為標記語言加上樣式

你考慮看看這樣閱讀起來會不會比較好理解。

2021-09-27 15:47 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/svelte_todo_list_beginning/index.html
> +<p>為了看見如文末情況的程式碼狀態，你可以至已複製下來的儲存庫位置如下：</p>
> 至已

應該是打錯字

建議：
若像要看到本文結束後所有程式碼所呈現的最終效果，你可以參照下列的方式複製一份我們的程式庫：

2021-09-27 15:47 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/svelte_todo_list_beginning/index.html
> +<p>或直接下載資料夾內容如下：</p>
「如下」不需要

2021-09-27 15:47 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/svelte_todo_list_beginning/index.html
> +<p>為了在 REPL 看見當前程式碼狀態，點擊如下連結：</p>
這裡 kerning 規則不一致。

2021-09-27 15:47 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/svelte_todo_list_beginning/index.html
> +<p>隨著補上標記並樣式化，我們的待辦清單應用程式逐漸成形，終於可以開始專注在我們需要實現的功能。</p>
> 隨著補上標記並樣式化

可以參考我上面的思路，改良一下翻譯。

這一整句的結尾要補上一個「了」閱讀起來才不會奇怪。

2021-09-27 16:50 UTC, cdcd72 commented
調整完一版語意，可以再確認看看，還有無不妥的地方，謝謝。

2021-09-27 16:53 UTC, cdcd72 commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/svelte_todo_list_beginning/index.html
> +<p>為了看見如文末情況的程式碼狀態，你可以至已複製下來的儲存庫位置如下：</p>
這段翻譯比較糾結的地方是結尾那段，感覺不是要使用者再去複製一份下來，而應該是去原本已經複製下來的儲存庫位置。

2021-09-30 15:23 UTC, t7yang requested changes
其他大致沒什麼問題。

2021-09-30 15:23 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/svelte_todo_list_beginning/index.html
> +<p>無障礙性（縮寫為a11y）不總是容易正確，但Svelte將會協助並警示你，假如你寫出了不易閱讀的標記語言。</p>
> 無障礙性（縮寫為a11y）不總是容易正確

正確什麼？動詞要寫出來，不然就變成 a11y 本身不容易正確，意思就不一樣了。
或是換成用 A11y 不容易做對這樣的敘述方式。

2021-09-30 15:23 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/svelte_todo_list_beginning/index.html
> +<p>為了在REPL看見當前程式碼狀態，點擊如下連結：</p>
這裡是想要看到目前的狀態，用「為了」感覺怪怪的。

2021-10-01 01:37 UTC, cdcd72 commented
有在稍微修飾過，可以確認看看。

2021-10-02 19:08 UTC, t7yang approved these changes

2021-10-02 19:09 UTC, merged