补充缺失的「Sort stability」部分
mdn/translated-content pull request #2611
Opened 2021-09-30 03:49 UTC by liangjiancang

如题

2021-09-30 15:05 UTC, t7yang requested changes
請參考這個連結的內容（最後一版的 html）：

https://github.com/mdn/content/blob/01ff31c3d7c6818de4b0cdd3c130ab7ccc948856/files/en-us/web/javascript/reference/global_objects/array/sort/index.md

2021-09-30 15:19 UTC, liangjiancang commented
目前的翻译就是照着原版来的，我看不出有哪里对不上。

2021-09-30 15:30 UTC, t7yang commented
> 目前的翻译就是照着原版来的，我看不出有哪里对不上。

你點進去我給你的連結，並點選 raw 來看（如下連結），細節看你修改的部分，就知道差異在哪裡了。如果肉眼看不出來，就用 VSCode 去做 diff 。

https://raw.githubusercontent.com/mdn/content/01ff31c3d7c6818de4b0cdd3c130ab7ccc948856/files/en-us/web/javascript/reference/global_objects/array/sort/index.md

2021-09-30 15:55 UTC, liangjiancang commented
这次换行符位置都一模一样了（其实完全搞不懂标准是什么）。前面有一大段不一样的也改了。

2021-10-02 19:06 UTC, t7yang approved these changes

2021-10-02 19:12 UTC, merged