update glossary of character_encoding for zh-cn
mdn/translated-content pull request #2620
Opened 2021-10-02 00:52 UTC by buuug7

update glossary of character_encoding translate for zh-cn

2021-10-02 18:20 UTC, t7yang requested changes

2021-10-02 18:20 UTC, t7yang commented on files/zh-cn/glossary/character_encoding/index.html
> +<p>字符编码定义字节和文本之间的映射。字节序列允许解析成不同的文本。通过指定特定的编码（如UTF-8），我们可以知道如何解析字节序列。</p>
> we specify how the sequence of bytes is to be interpreted.

這是原文，其意思是指定相關的 bytes 如何被 interpreted ，不是你所表達的意思。

2021-10-02 18:20 UTC, t7yang commented on files/zh-cn/glossary/character_encoding/index.html
> +<p>这确保了您可以在HTML文档中使用任何人类语言字符，并且展示的结果值得信赖。</p>
- 這是文件，不需要使用敬語。
- 原翻譯更好，你的翻譯語句並不通順，請維持原翻譯。

2021-10-04 16:13 UTC, buuug7 commented on files/zh-cn/glossary/character_encoding/index.html
> +<p>这确保了您可以在HTML文档中使用任何人类语言字符，并且展示的结果值得信赖。</p>
@t7yang do whatever you want, or you can reject this PR, i can not nothing with the translation.

2021-10-04 16:13 UTC, buuug7 commented on files/zh-cn/glossary/character_encoding/index.html
> +<p>字符编码定义字节和文本之间的映射。字节序列允许解析成不同的文本。通过指定特定的编码（如UTF-8），我们可以知道如何解析字节序列。</p>
按照你的意思, 觉得不合理就关闭该PR吧

2021-10-05 11:26 UTC, closed without merging