Update index.html
mdn/translated-content pull request #2687
Opened 2021-10-09 05:03 UTC by Namorzyny

Remove confusing text on the buttons, examples which contain the content of personal preference should not be shown.

2021-10-09 05:19 UTC, yujincheng08 approved these changes

2021-10-09 05:43 UTC, JohnsonRan approved these changes

2021-10-09 12:37 UTC, JasonKhew96 approved these changes

2021-10-09 16:22 UTC, t7yang requested changes

2021-10-09 16:22 UTC, t7yang commented on files/zh-cn/web/api/document/createtextnode/index.html
> +  &lt;button value="createTextNode"&gt;createTextNode&lt;/button&gt;
```
  <button onclick="addTextNode('YES! ');">YES!</button>
  <button onclick="addTextNode('NO! ');">NO!</button>
  <button onclick="addTextNode('WE CAN! ');">WE CAN!</button>
```
Please update according the latest content.

Please describe what you done in the title, not just Update index.html.

2021-10-12 02:53 UTC, t7yang approved these changes

2021-10-12 02:57 UTC, merged