Complete fr translation for LA "Practical positioning examples"
mdn/translated-content pull request #2703
Opened 2021-10-11 13:34 UTC by jfalycee

traduction non faite !

2021-10-13 06:24 UTC, SphinxKnight requested changes
@jfalycee merci beaucoup pour la traduction de ces paragraphes. Je pense que pour que cette PR soit valide, il faudrait également traduire le reste de la page (malheureusement encore majoritairement en anglais). 

Pouvez-vous le faire s'il vous plaît ? N'hésitez pas à nous indiquer si vous avez besoin d'aide, cette PR peut être écrite à plusieurs mains si besoin.

2021-10-13 08:15 UTC, jfalycee commented
Bonjour, oui je veux bien finir la traduction de la page, et le code CSS fournit ne correspond pas non plus à l'exemple

2021-11-03 08:44 UTC, SphinxKnight commented
@jfalycee @tristantheb je me suis permis d'avancer sur cette page afin que la PR puisse être fusionnée avant la conversion de la Learning Area en Markdown. J'ai inclus les modifications de https://github.com/mdn/translated-content/pull/2738 et ai traduit le reste.
N'hésitez pas à me faire vos retours :)

2021-11-03 12:09 UTC, SphinxKnight approved these changes

2021-11-11 17:07 UTC, merged