Firefox 93 for developers を翻訳
mdn/translated-content pull request #2751
Opened 2021-10-17 06:42 UTC by yyss

Oct 15, 2021 の英語版に対応。

2021-10-18 08:41 UTC, mfuji09 requested changes
1点 (同じ問題で2か所) の問題がありますので、修正をお願いします。

2021-10-18 08:41 UTC, mfuji09 commented on files/ja/mozilla/firefox/releases/93/index.html
> +  <li><em>画像</em> について、既定の HTTP {{HTTPHeader("ACCEPT")}} ヘッダーを <code>image/avif,image/webp,*/*</code> に変更しました (<a href="/ja/docs/Web/Media/Formats/Image_types#AVIF_image">AVIF</a> 画像形式のサポートを追加した結果として
リンクのフラグメント (#AVIF_image) を実際のページのフラグメントに合わせてください。

2021-10-18 08:41 UTC, mfuji09 commented on files/ja/mozilla/firefox/releases/93/index.html
> +  <li><a href="/ja/docs/Web/Media/Formats/Image_types#AVIF_image">AVIF</a> 画像のサポートを、デフォルトで有効化しました ({{bug(1682995)}})。この形式は圧縮率が優れており、また特許の制限がありません (これは <a href="http://aomedia.org/">Alliance for Open
直前の指摘点と同じで、URL のフラグメントを見直してください。

2021-10-22 15:41 UTC, hochan222 requested changes
Hi, can someone please explain this PR?

I didn't understand why this PR trying to change the `ko-locale` file. One of them converted normal Korean files to English, and one deleted a properly recently updated .md file.

Thank you :) 

![image](https://user-images.githubusercontent.com/22424891/138483615-40ffe5f0-81f0-4c8b-8548-59d9513d874f.png)

![image](https://user-images.githubusercontent.com/22424891/138483578-9e2bd79e-b184-4ffd-b922-0e465557a401.png)

2021-10-25 14:09 UTC, closed without merging