[ko] Translation done to 'Web audio spatialization basics' document
mdn/translated-content pull request #2782
Opened 2021-10-19 16:17 UTC by logic-finder

https://developer.mozilla.org/ko/docs/Web/API/Web_Audio_API/Web_audio_spatialization_basics
위 문서를 번역하였습니다.

I translated [this document](https://developer.mozilla.org/ko/docs/Web/API/Web_Audio_API/Web_audio_spatialization_basics) into Korean.

※ 영문판은 .md인데 본 pr은 .html인 이유: https://github.com/mdn/translated-content/pull/1609#issuecomment-894433453 md로 업데이트되기 전에 제가 html을 ko폴더로 옮겼기 때문입니다. 단, 어차피 내용은 똑같으므로 문제는 없을 것으로 사료됩니다.

2021-11-03 12:46 UTC, logic-finder commented
@hochan222 안녕하세요, 2주가 경과하여 멘션드립니다. 감사합니다.

2021-11-13 11:23 UTC, yechoi42 requested changes
안녕하세요 :) 이번에도 소리 관련 글을 번역해주셨군요! 긴 글을 번역해주셔서 감사합니다. 이번 글에는 공통적인 제안사항이 있어, 제가 직접 모든 것을 수정하기보다는 번역자분께 한번 더 전반적인 수정을 부탁드리고 싶습니다. 

- 읽어보셨을 때 '이것'이라는 표현을 독자들이 쉽게 이해할 수 있는지 한번 확인해주세요. 어떤 문장은 단번에 이해되겠지만, 또 다른 어떤 문장들은 이해하기 쉽지 않을 거예요. 그런 경우에는 부연설명해주시거나 '이것'이 가리키는 것을 직접 언급해주세요. 
- '우리'라는 표현이 없어도 무방하다면 생략해주세요. 영어에서는 많이 사용하지만 우리말에서는 번역된 듯한 문장이라는 인상을 줍니다. 
- 직역하지 않으셔도 괜찮습니다 :) 직역했을 때 어색하다면 의역하시거나 조금 수정을 보셔도 좋을 듯합니다. 이 또한 번역자의 권한이고, 원문의 의미를 해치지 않는 선에서 읽는 사람이 편한 것이 최고의 번역이라고 생각합니다. 

조금 더 품이 드시겠지만, 번역자님께서 공들여 작성하신 글이 조금 더 잘 읽혔으면 하는 마음에 제안드립니다🙏 이 같은 기준으로 145번째 줄까지는 수정을 보았으니, 참고해주시면 감사할듯합니다! 

오늘도 덕분에 한국인 독자들이 쉽게 읽을 수 있는 문서가 늘고 있습니다. 언제나 번역에 기여해주셔서 감사합니다.

2021-11-13 11:23 UTC, yechoi42 commented on files/ko/web/api/web_audio_api/web_audio_spatialization_basics/index.html
> +<p>그럼 시작해 봅시다! {{domxref("BaseAudioContext")}} ({{domxref("AudioContext")}}가 확장된 인터페이스) 는 {{domxref("AudioListener")}} 객체를 반환하는 <code><a href="/ko/docs/Web/API/BaseAudioContext/listener">listener</a>
이것은 보통 여러분의 유저인, 장면의 리스너를 나타냅니다.
그것들은 고정적으로(static) 있습니다. 
-> 두 문장이 번역투가 있어서 바로 이해하기 어려운 듯합니다. 조금 더 읽기 쉽게 고쳐주시면 감사할 것 같습니다.

리스너의 위치에 관하여 이것의 사운드 위치를 계산할 수 있습니다.
-> '이것'의 대상도 문장의 흐름에서 바로 추론할 수 있게 조금 더 부연해주시면 좋겠습니다.

2021-11-13 11:23 UTC, yechoi42 commented on files/ko/web/api/web_audio_api/web_audio_spatialization_basics/index.html
> +<p>꽤 똑똑한 것들이군요. <code>HRTF</code> 모델을 사용합시다!</p>
```suggestion
<p>꽤 똑똑하네요. <code>HRTF</code> 모델을 사용합시다!</p>
```

2021-11-13 11:23 UTC, yechoi42 commented on files/ko/web/api/web_audio_api/web_audio_spatialization_basics/index.html
> +<p>다음 매개변수는 <a href="/ko/docs/Web/API/PannerNode/distanceModel"><code>distanceModel</code></a>입니다 — 이것은 오직 <code>linear</code>, <code>inverse</code>, 또는 <code>exponential</code>로만 설정될 수 있습니다. 이것들은 각기
```suggestion
<p>다음 매개변수는 <a href="/ko/docs/Web/API/PannerNode/distanceModel"><code>distanceModel</code></a>입니다 — 이것은 오직 <code>linear</code>, <code>inverse</code>, 또는 <code>exponential</code>로만 설정될 수 있습니다. 이것들은 각기 다른 알고리즘인데, 리스너로부터 멀어질 때 오디오 소스의 볼륨을 감소시키기 위해 사용됩니다. 우리는 단순한 <code>linear</code>를 사용할 것입니다.</p>
```

2021-11-13 11:23 UTC, yechoi42 commented on files/ko/web/api/web_audio_api/web_audio_spatialization_basics/index.html
> +<p>우리는 리스너와 음원 사이의 최대 거리를 (<a href="/ko/docs/Web/API/PannerNode/maxDistance"><code>maxDistance</code></a>) 설정할 수 있습니다 — 만약 음원이 이 지점으로부터 더 멀리 이동하면 볼륨은 더 이상 감소되지 않을 것입니다. 이것은 유용한데, 왜냐하면 여러분이 거리를 모방하기를
```suggestion
<p>우리는 리스너와 음원 사이의 최대 거리를 (<a href="/ko/docs/Web/API/PannerNode/maxDistance"><code>maxDistance</code></a>) 설정할 수 있습니다 — 만약 음원이 이 지점으로부터 더 멀리 이동하면 볼륨은 더 이상 감소되지 않을 것입니다. 최대 거리 설정 기능은 유용한데, 왜냐하면 여러분이 거리를 모방하기를 원하게 될지도 모르지만, 볼륨은 떨어지는 건 실제로 여러분이 원하는 것이 아닐 것입니다. 최대 거리는 기본값으로 10,000 (단위없는 상대 값)입니다. 아래와 같은 코드로 설정합니다. </p>
```
바로 이해하기 어려운 부분을 일부 수정했습니다. 추가적으로 수정 요청을 드리고 싶은 부분은 '왜냐하면 여러분이 거리를 모방하기를 원하게 될지도 모르지만' 이 문장입니다. '거리를 모방한다'는 표현을 알기 쉽게 풀어주시면 좋을 것 같습니다 !

2021-11-13 11:23 UTC, yechoi42 commented on files/ko/web/api/web_audio_api/web_audio_spatialization_basics/index.html
> +<p>또한 참조 거리 (<code><a href="/en-US/docs/Web/API/PannerNode/refDistance">refDistance</a></code>)가 있는데, 이는 거리 모델들에 의해 사용됩니다. 우리는 또한 기본값 1로 이것을 유지할 수 있습니다.</p>
```suggestion
<p>또한 거리 모델에 의해 사용되는 참조 거리 (<code><a href="/en-US/docs/Web/API/PannerNode/refDistance">refDistance</a></code>)가 있습니다. 이 또한 기본값 1로 설정할 수 있습니다.</p>
```

2021-11-13 11:23 UTC, yechoi42 commented on files/ko/web/api/web_audio_api/web_audio_spatialization_basics/index.html
> +<p>그리고 roll-off 인자 (<a href="/en-US/docs/Web/API/PannerNode/rolloffFactor"><code>rolloffFactor</code></a>) 가 있습니다 — 패너가 리스너로부터 멀어질 때 얼마나 빨리 볼륨이 감소하는지를 결정합니다. 기본값은 1입니다; 우리의 이동을 과장하기 위해 이 값을 조금 더 크게 만
```suggestion
<p>그리고 roll-off 인자 (<a href="/en-US/docs/Web/API/PannerNode/rolloffFactor"><code>rolloffFactor</code></a>) 가 있습니다 — 패너가 리스너로부터 멀어질 때 얼마나 빨리 볼륨이 감소하는지를 결정합니다. 기본값은 1입니다. 이동을 과장하기 위해 이 값을 조금 더 크게 만듭시다.</p>
```
우리말에서는 세미콜론(;)로 끝맺음을 잘 하지 않아서 온점(.)으로 끝맞춰 주시면 어떨까 싶습니다. '우리' 표현 또한 삭제해도 이해하는데 무리가 없다면, 생략하는 것이 더 자연스러울 것 같습니다.

2021-11-13 11:23 UTC, yechoi42 commented on files/ko/web/api/web_audio_api/web_audio_spatialization_basics/index.html
> +<p>이제 우리는 라디오의 위치와 방향 설정을 시작할 수 있습니다. 이것은 우리가 리스너에 대해 한 방법과 많이 비슷합니다. 이것들 또한 인터페이스의 조종 장치가 사용될 때 우리가 변경할 매개변수들입니다.</p>
```suggestion
<p>이제 라디오의 위치와 방향 설정을 시작할 수 있습니다. 이것은 리스너에 대해 한 방법과 많이 비슷합니다. 인터페이스의 조종 장치가 사용될 때 변경할 매개변수들도 있습니다.</p>
```

2021-11-13 11:23 UTC, yechoi42 commented on files/ko/web/api/web_audio_api/web_audio_spatialization_basics/index.html
> +<p>z 방향의 마이너스 값에 주목하세요 — 이것은 라디오가 우리를 바라보게 만듭니다. 양수 값은 음원이 우리를 등지게 만들 것입니다.</p>
```suggestion
<p>z 방향의 음수 값에 주목하세요 — 음수 값은 라디오가 우리를 바라보게 만듭니다. 양수 값은 음원이 우리를 등지게 만들 것입니다.</p>
```

2021-11-13 11:23 UTC, yechoi42 commented on files/ko/web/api/web_audio_api/web_audio_spatialization_basics/index.html
> +<p>이제 우리는 라디오를 '방' 주위에서 움직일 것입니다. 우리는 이것을 하기 위해 준비된 몇몇 조종 장치들을 가지고 있습니다. 우리는 이것을 좌우로, 위아래로, 앞뒤로 움직일 수 있습니다; 우리는 또한 회전시킬 수도 있습니다. 소리 방향은 앞에 있는 라디오 스피커에서부터 오므로, 우리가 이것을 회전시켰을 때, 우리는 소리의 방향을 변경할 수 있습니다
```suggestion
<p>이제 라디오를 '방' 주위에서 움직일 것입니다. 이를 위해 몇몇 조종 장치들을 준비했습니다. 라디오를 좌우로, 위아래로, 앞뒤로 움직일 수 있고, 회전시킬 수도 있습니다. 소리 방향은 앞에 있는 라디오 스피커에서부터 오므로, 라디오를 회전시키면 소리의 방향을 변경할 수 있습니다 — 예: 라디오가 180도 회전되어 우리를 등지고 있을 때 뒤로 소리가 향하도록 만들기.</p>
```

2021-11-13 19:10 UTC, logic-finder commented
안녕하세요, 상세한 리뷰 남겨주셔서 감사합니다. 말씀해 주신 대로 최대한 번역투를 빼고 읽기 쉽게 고쳐보려고 노력했습니다. 감사합니다.

2021-11-30 11:20 UTC, yechoi42 approved these changes
긴 글 다시 살펴봐주셔서 감사합니다. (_ _)
이전보다 훨씬 읽기 편해졌습니다!! 수고하셨습니다!

2021-11-30 11:21 UTC, merged