Update index.html
mdn/translated-content pull request #2819
Opened 2021-10-22 02:02 UTC by mygod48

The translation text before missed the explaination about `when the request's credentials mode (Request.credentials) is include`.

A small syntax error included.

2021-10-26 14:09 UTC, irvin requested changes
請修改 PR 標題，寫明本 PR 的功用

2022-05-29 07:09 UTC, yin1999 requested changes

2022-05-29 07:09 UTC, yin1999 commented on files/zh-cn/web/http/headers/access-control-allow-credentials/index.html
> +<p><strong><code>Access-Control-Allow-Credentials</code></strong> 响应头表示当请求中要求包含credentials({{domxref("Request.credentials")}}的值为<code>include</code)时，是否可以将对请求的响应暴露给页面。返回true则可以，其他值均不可以。</p>
目前的翻译是不正确的，请修改

2022-07-02 23:23 UTC, yin1999 approved these changes

2022-07-02 23:26 UTC, merged