[ko] Translation done of 'Advanced techniques: Creating and sequencing audio' document
mdn/translated-content pull request #2830
Opened 2021-10-22 16:06 UTC by logic-finder

https://developer.mozilla.org/ko/docs/Web/API/Web_Audio_API/Advanced_techniques
위 문서를 번역하였습니다.

I translated [this document](https://developer.mozilla.org/ko/docs/Web/API/Web_Audio_API/Advanced_techniques) into Korean.

※ 영문판은 .md인데 본 pr은 .html인 이유: https://github.com/mdn/translated-content/pull/1609#issuecomment-894433453 md로 업데이트되기 전에 제가 html을 ko폴더로 옮겼기 때문입니다. 단, 어차피 내용은 똑같으므로 문제는 없을 것으로 사료됩니다.

2021-11-04 12:59 UTC, yechoi42 requested changes
안녕하세요! 이번에도 멋진 글을 번역해 주셨네요 :) 긴 글 번역 수고하셨습니다. 감사합니다 ! 

누락된 문장을 하나 발견했고, 사소한 제안이 있습니다. 누락된 문장은 제가 러프하게 번역해놓긴 했지만, 음악에 대한 지식이 없다보니 내용이 이해가 잘 안되서 한번 확인해주시면 좋을 것 같습니다. 

제안 내용 확인해보시고 저를 다시 멘션해주시면 머지하도록 하겠습니다.

2021-11-04 12:59 UTC, yechoi42 commented on files/ko/web/api/web_audio_api/advanced_techniques/index.html
> +<p><strong>참고</strong>: 이 악기는 좋은 소리를 내기 위해 만들어지지 않았습니다. 이것은 데모 코드를 제공하기 위해 만들어졌고 이런 악기의 <em>아주</em> 단순화된 버전을 나타냅니다. 이 소리들은 다이얼 접속 모뎀에 기반합니다. 만약 여러분이 이것이 어떤 소리인지 모른다면 <a href="https://soundcloud.com/j
```suggestion
<p><strong>참고</strong>: 이 악기는 좋은 소리를 내기 위해 만들어지지 않았습니다. 이것은 데모 코드를 제공하기 위해 만들어졌고 이런 악기의 <em>아주</em> 단순화된 버전을 나타냅니다. 이 소리들은 다이얼 접속 모뎀에 기반합니다. 만약 여러분이 이것이 어떤 소리인지 모른다면 <a href="https://soundcloud.com/john-pemberton/modem-dialup">여기서 들어볼 수 있습니다.</a></p>
```
하이퍼링크의 위치를 조금 자연스럽게 해보았습니다:)

2021-11-04 12:59 UTC, yechoi42 commented on files/ko/web/api/web_audio_api/advanced_techniques/index.html
> +<p>우리의 attack과 release에 대해, 우리는 위에서 언급된 <code>linearRampToValueAtTime</code> 메서드를 사용할 것입니다. 이것은 두 개의 매개변수를 취합니다 — 변화시키고 있는 매개변수에 설정하기 원하는 값 (이 경우 gain) 그리고 언제 이것을 하고 싶은지. 우리의 경우 <em>언제</em>는 우리의 입력에
```suggestion
<p>우리의 attack과 release에 대해, 우리는 위에서 언급된 <code>linearRampToValueAtTime</code> 메서드를 사용할 것입니다. 이것은 두 개의 매개변수를 취합니다 — 변화시키고 있는 매개변수에 설정하기 원하는 값 (이 경우 gain) 그리고 언제 이것을 하고 싶은지. 우리의 경우 <em>언제</em>는 우리의 입력에 의해 제어됩니다. 그래서 아래의 예제에서 gain은 attack 범위 입력이 설정된 시간에 따라 선형 비율로 1까지 증가됩니다. 비슷하게 release의 경우 release 범위가 입력된 동안 선형적으로 gain은 0으로 설정됩니다. </p>
```
마지막 문장이 누락되어있어서 번역해보았는데요, 저도 의미가 확실치 않아서 의견주시면 감사하겠습니다. 아래는 원문입니다.
`Similarly, for our release, the gain is being set to 0, at a linear rate, over the time the release input has been set to.`

2021-11-04 12:59 UTC, yechoi42 commented on files/ko/web/api/web_audio_api/advanced_techniques/index.html
> +<p>우리가 맞춤형 파동을 설정하기 위해 웨이브 테이블을 사용하지 않을 것이라는 점을 제외하고, 우리는 스윕 사운드에 한 것과 같은 방식으로 첫번째 {{domxref("OscillatorNode")}}를 설정합니다 — 우리는 단지 기본 <code>sine</code> 파동을 사용할 것입니다:</p>
```suggestion
<p>우리가 맞춤형 파동을 설정하기 위해 웨이브 테이블을 사용하지 않을 것이라는 점을 제외하고, 우리는 스윕 사운드에 한 것과 같은 방식으로 첫번째 {{domxref("OscillatorNode")}}를 설정합니다 — 우리는 단지 기본 <code>사인</code> 파동을 사용할 것입니다:</p>
```
위에서 한글로 사인파라고 언급한 적이 있어서 sine 대신 사인이 더 통일성 있을 것 같아요 !

2021-11-04 12:59 UTC, yechoi42 commented on files/ko/web/api/web_audio_api/advanced_techniques/index.html
> +<p>여러분은 이것이 꽤 쉭쉭하는 소리가 나거나 금속성의 소리가 나는 것을 인지하였을 것입니다. 우리는 백색소음을 만들었고, 백색소음이라면 그래야만 합니다. 값은 -1과 1사이에서 실행되는데, 이는 우리가 모든 주파수의 피크를 가지고 있는데, 결국 이는 실제로 꽤 찢어지는 듯한 소리임을 의미합니다. 우리는 이 함수가 0.5에서 -0.5에서 실행되거나 피크
```suggestion
<p>여러분은 이것이 꽤 쉭쉭하는 소리가 나거나 금속성의 소리가 나는 것을 인지하였을 것입니다. 우리는 백색소음을 만들었고, 백색소음이라면 그래야만 합니다. 값은 -1과 1사이에서 실행되는데, 이는 우리가 모든 주파수의 피크를 가지고 있는데, 결국 이는 실제로 꽤 찢어지는 듯한 소리임을 의미합니다. 우리는 이 함수가 0.5에서 -0.5에서 실행되거나 피크를 내려 불편함을 줄이는 유사한 작업을 하도록 수정<em>할 수 있는데</em>, 그렇게 하면 재미가 없죠? 우리가 생성한 노이즈가 필터를 통과하도록 전송합시다.</p>
```
where's the fun in that을 조금 더 이해하기 쉽도록 의역해보았습니다 !

2021-11-04 12:59 UTC, yechoi42 commented on files/ko/web/api/web_audio_api/advanced_techniques/index.html
> +<p><strong>참고</strong>: 이 사운드 파일은 <a href="https://soundbible.com/1573-DTMF-Tones.html">soundbible.com에서 찾아졌습니다</a>.</p>
```suggestion
<p><strong>참고</strong>: 이 사운드 파일의 출처는 <a href="https://soundbible.com/1573-DTMF-Tones.html">soundbible.com</a>입니다.</p>
```
이것도 조금 더 이해하기 쉽도록 의역했습니다!

2021-11-05 02:58 UTC, logic-finder commented
안녕하세요 리뷰해주셔서 감사합니다. 말씀해주신 수정 사항을 전부 반영했으나 다시 수정하는 과정에서 되돌린 부분도 있었습니다. 주요 변경 사항은 아래와 같습니다.
- 좀 더 읽기 쉽게 수정 (ex: 제어기 → 슬라이더)
- `<em>` 태그 제거 (사유: 번역 지침서를 따랐습니다). 대신, `<strong>` 태그로 교체했습니다.

※ 원상복구한 커밋 (9aa6bcb)
<code>sine</code>으로 내버려 둔 이유가 오실레이터의 `type` 프로퍼티가 `'sine'` 이라, 이는 코드에 해당되는 내용이므로 변경하지 않았던 것 같습니다. 이 부분은 다시 `sine`으로 고쳤습니다. 더불어, 아래 문단의 <code>사각</code>도 `square`로 변경했습니다.

![image](https://user-images.githubusercontent.com/83723320/140450753-8ddd3d50-ec12-468e-a4ae-0f1c0605eb07.png)

감사합니다.

2021-11-13 10:42 UTC, yechoi42 approved these changes
감사합니다 ! 머지하겠습니다 :)

2021-11-13 10:42 UTC, merged