add basic example according to english version
mdn/translated-content pull request #2881
Opened 2021-10-27 13:14 UTC by fyzhu

2021-10-28 14:11 UTC, t7yang requested changes
this is not a md file, please change your format or make this change after html to md process.

2021-11-08 16:07 UTC, irvin commented
merged on #3015

2021-11-08 16:07 UTC, closed without merging

2021-11-08 16:08 UTC, irvin commented
@fyzhu 請參照英文版 md 文件，協助更新中文 md 文件內的所有段落

2021-11-10 08:08 UTC, fyzhu commented
OK