Date の誤訳を修正
mdn/translated-content pull request #2913
Opened 2021-10-30 01:22 UTC by oshiteku

原文では "This date and time are not the same as the UNIX epoch" となっている箇所が
"UNIX Epoch と同じです" と翻訳されてしまっていたため修正しました。

2021-10-31 15:12 UTC, mfuji09 requested changes
1点だけ、修正をお願いします。

2021-10-31 15:12 UTC, mfuji09 commented on files/ja/web/javascript/reference/global_objects/date/index.html
> +<p>JavaScript の日時は、基本的に協定世界時 (UTC) の1970年1月1日深夜0時からの経過ミリ秒数で指定されます。この日付と時刻は、コンピューターに記録される日付と時刻の値の主な基準値である <strong>UNIX Epoch</strong> (UTC の1970年1月1日深夜0時からの経過秒数) とは異なります。</p>
1点だけ。半角数字と日本語の間も、半角空白を1つ空けてください。

2021-10-31 15:29 UTC, oshiteku commented on files/ja/web/javascript/reference/global_objects/date/index.html
> +<p>JavaScript の日時は、基本的に協定世界時 (UTC) の1970年1月1日深夜0時からの経過ミリ秒数で指定されます。この日付と時刻は、コンピューターに記録される日付と時刻の値の主な基準値である <strong>UNIX Epoch</strong> (UTC の1970年1月1日深夜0時からの経過秒数) とは異なります。</p>
レビューありがとうございます。修正しました。

2021-11-02 05:01 UTC, mfuji09 approved these changes
OKです！

2021-11-02 05:09 UTC, merged