fix: [ja,ko,es,ru] update codes on Node.js server without a framework
mdn/translated-content pull request #2994
Opened 2021-11-07 10:00 UTC by yuto0214w

1. fixed 404 process code [all]
`response.writeHead(200, { 'Content-Type': contentType });` -> `response.writeHead(404, { 'Content-Type': 'text/html' });`
2. fixed `var contentType = 'text/html';` [es,ko,ru]
3. fixed code on korean page doen't show correctly [ko]
`<pre>` -> `<pre class="brush: js">`

2021-11-08 02:05 UTC, mfuji09 requested changes
There are still codes different from en-US version in the ja version.
(ex. line 45-59, line 73, etc.)
Please reflect the whole changes in en-US version.

2021-11-08 15:24 UTC, mfuji09 approved these changes
I approve about ja file.

2021-11-08 15:29 UTC, mpstv approved these changes

2021-11-09 12:38 UTC, yujo11 approved these changes

2021-11-09 14:30 UTC, merged