create `zh-CN` translation `Glossary/WebDAV`
mdn/translated-content pull request #3046
Opened 2021-11-11 00:57 UTC by yin1999

Add `zh-CN` translation for `Glossary/WebDAV`.

2021-11-12 01:43 UTC, t7yang requested changes

2021-11-12 01:43 UTC, t7yang commented on files/zh-cn/glossary/webdav/index.html
> +<h3 id="基础知识">基础知识</h3>
remove this block of content.

2021-11-12 01:43 UTC, t7yang commented on files/zh-cn/glossary/webdav/index.html
> +</ul>
update this block of content according this [section](https://github.com/mdn/content/blob/4a9f9d2e9c1811ce3519a7061e906db9200a5e97/files/en-us/glossary/webdav/index.md#see-also) in `HTML` form.

2021-11-12 06:25 UTC, yin1999 commented on files/zh-cn/glossary/webdav/index.html
> +</ul>
any example?

2021-11-16 03:25 UTC, irvin commented on files/zh-cn/glossary/webdav/index.html
> +</ul>
請參考目前的[翻譯測試](https://pr3046.content.dev.mdn.mozit.cloud/zh-CN/docs/Glossary/WebDAV)頁與[英文版網頁](https://developer.mozilla.org/en-US/docs/Glossary/WebDAV)，你直接調整讓其 `<ul><li>` 階層格式一致即可

2021-11-20 16:47 UTC, t7yang approved these changes

2021-11-20 16:48 UTC, merged