-moz 系の CSS プロパティを更新
mdn/translated-content pull request #3047
Opened 2021-11-11 01:08 UTC by mfuji09

- 2021/11/09 時点の英語版に同期

2021-11-20 08:42 UTC, potappo requested changes
ライブサンプルのマクロが失敗しているのを修正しましたので、確認お願いします。

2021-11-20 08:42 UTC, potappo commented on files/ja/web/css/-moz-outline-radius-bottomright/index.md
> +## 例
```suggestion
<h2 id="Examples">例</h2>
```

2021-11-20 12:43 UTC, mfuji09 commented on files/ja/web/css/-moz-outline-radius-bottomright/index.md
> +## 例
確認が漏れていました。ありがとうございました。

2021-11-21 13:37 UTC, potappo approved these changes

2021-11-21 13:37 UTC, merged