Convert file contents to Markdown and add Intranets and Extranets section
mdn/translated-content pull request #3074
Opened 2021-11-12 10:38 UTC by felipedeaquino

2021-11-12 23:57 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +        <a href="https://developer.mozilla.org/pt-BR/docs/Learn/Common_questions/Pensando_antes_de_codificar"
```suggestion
        <a href="/pt-BR/docs/Learn/Common_questions/Thinking_before_coding"
```

2021-11-12 23:59 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +          >Pensando antes de codificar</a>
```suggestion
          >Como eu começo a criar meu site?</a>
```

2021-11-13 00:07 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +[A história da internet é um pouco obscura](https://pt.wikipedia.org/wiki/Internet#Hist.C3.B3ria). Ela começou nos anos 60 como um projeto de pesquisa consolidado pelo exército norte americano, e tor
```suggestion
[A história da internet é um pouco obscura](https://pt.wikipedia.org/wiki/Internet#Hist.C3.B3ria). Ela começou nos anos 60 como um projeto de pesquisa consolidado pelo exército norte americano, e tornou-se uma infraestrutura pública nos anos 80 com o suporte dado por diversas universidades públicas e companhias privadas. As várias tecnologias que suportam a internet evoluíram através do tempo, mas a forma de funcionamento não mudou muito: Internet é uma forma de conectar computadores e garantir, em qualquer situação, que eles encontrem uma forma de se manter conectados.
```

2021-11-13 00:07 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +        <a href="https://developer.mozilla.org/pt-BR/docs/Learn/Common_questions/Pensando_antes_de_codificar"
Trocar para o link interno

2021-11-13 00:09 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +          >Pensando antes de codificar</a>
Aqui eu troquei pelo título que está na página traduzida

2021-11-13 00:11 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +[A história da internet é um pouco obscura](https://pt.wikipedia.org/wiki/Internet#Hist.C3.B3ria). Ela começou nos anos 60 como um projeto de pesquisa consolidado pelo exército norte americano, e tor
Nessa parte, uma pequena correção na palavra "companhias" que estava com um erro de digitação (sem o H).
Também pensei em trocar o "se acoplaram" por "evoluíram", tendo em vista que na versão em inglês está escrito "have evolved".

2021-11-13 00:20 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +![Dois computadores conectados](https://mdn.mozillademos.org/files/8441/internet-schema-1.png)
```suggestion
![Dois computadores conectados](internet-schema-1.png)
```

2021-11-13 00:22 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +![Dez computadores conectados entre si](https://mdn.mozillademos.org/files/8443/internet-schema-2.png)
```suggestion
![Dez computadores conectados entre si](internet-schema-2.png)
```

2021-11-13 00:28 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +Uma vez que nós adicionamos um roteador no sistema, nossa rede de 10 computadores apenas necessitará de 10 cabos: uma unica conexão para cada computador e um roteador com 10 conexões.
```suggestion
Uma vez que nós adicionamos um roteador no sistema, nossa rede de 10 computadores apenas necessitará de 10 cabos: uma única conexão para cada computador e um roteador com 10 conexões.
```

2021-11-13 00:28 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +Uma vez que nós adicionamos um roteador no sistema, nossa rede de 10 computadores apenas necessitará de 10 cabos: uma unica conexão para cada computador e um roteador com 10 conexões.
Adicionando o acento que ficou faltando na palavra "única"

2021-11-13 00:29 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +![10 computadores com um roteador](https://mdn.mozillademos.org/files/8445/internet-schema-3.png)
```suggestion
![10 computadores com um roteador](internet-schema-3.png)
```

2021-11-13 00:31 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +Por enquanto, tudo bem. Mas como conectar centenas, milhares, bilhões de computadores? Claro que um unico _roteador_ não pode se adaptar para tanto, mas, se você ler com cuidado, nós dissemos que um
```suggestion
Por enquanto, tudo bem. Mas como conectar centenas, milhares, bilhões de computadores? Claro que um único _roteador_ não pode se adaptar para tanto, mas, se você ler com cuidado, nós dissemos que um _roteador_ é um computador como qualquer outro, então o que nos impede de conectar dois _roteadores_ juntos? Nada, então façamos isto.
```

2021-11-13 00:31 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +![Dois roteadores conectados](https://mdn.mozillademos.org/files/8447/internet-schema-4.png)
```suggestion
![Dois roteadores conectados](internet-schema-4.png)
```

2021-11-13 00:32 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +![Roteadores conectados a roteadores](https://mdn.mozillademos.org/files/8449/internet-schema-5.png)
```suggestion
![Roteadores conectados a roteadores](internet-schema-5.png)
```

2021-11-13 00:36 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +Esta rede é muito parecida com o que chamamos de Internet, mas alguma coisa está faltando. Nós contruímos tais redes para nossos próprios fins. Existem outras redes além das nossas ligadas em outros
```suggestion
Esta rede é muito parecida com o que chamamos de Internet, mas alguma coisa está faltando. Nós construímos tais redes para nossos próprios fins. Existem outras redes além das nossas ligadas em outros lugares: nossos amigos, vizinhos, qualquer pessoa pode ter uma rede de computadores. Mas é inviável ligarmos cabos entre nossas casas e o resto do mundo, então como nos podemos lidar com isso? Muito bem, já existem cabos ligados a sua casa, como por exemplo, cabos de eletricidade e telefone. A estrutura do telefone já conecta nossa casa com o resto do mundo, então é exatamente o que nós precisamos. Para conectar nossa rede a rede telefônica, precisamos de um equipamento especial chamado _modem_. Este *modem* transforma a informação da nossa rede em uma informação gerenciável pela rede telefônica e vice-versa.
```

2021-11-13 00:40 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +Esta rede é muito parecida com o que chamamos de Internet, mas alguma coisa está faltando. Nós contruímos tais redes para nossos próprios fins. Existem outras redes além das nossas ligadas em outros
Corrigindo 2 erros de digitação "contruímos" estava faltando o S e "telefonica" estava sem acento.
Também troquei "que tenha" por "pode ter" considerando a versão em inglês "anyone can have their own network".
A adição da frase "então é exatamente o que nós precisamos" foi feita seguindo também a versão em inglês "so it is the perfect wire we need".

2021-11-13 00:41 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +Para resolver este problema, cada computador na rede está conectado à um pequeno computador especial chamado de _roteador_. Este _roteador_ tem um único trabalho: como um sinalizador em uma estação d
```suggestion
Para resolver este problema, cada computador na rede está conectado a um pequeno computador especial chamado de _roteador_. Este _roteador_ tem um único trabalho: como um sinalizador em uma estação de trem, ter certeza de que a mensagem enviada por um determinado computador chegue ao computador destinatário corretamente. Para enviar uma mensagem para o computador B, o computador A deve enviar a mensagem para o roteador, que por sua vez encaminha a mensagem para o computador B e tem a certeza de que a mensagem não foi entregue ao computador C.
```

2021-11-13 00:42 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +Para resolver este problema, cada computador na rede está conectado à um pequeno computador especial chamado de _roteador_. Este _roteador_ tem um único trabalho: como um sinalizador em uma estação d
Neste caso, o A não tem crase, porque a palavra em seguida é masculina.

2021-11-13 00:43 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +![Um roteador conectado a um modem](https://mdn.mozillademos.org/files/8451/internet-schema-6.png)
```suggestion
![Um roteador conectado a um modem](internet-schema-6.png)
```

2021-11-13 00:46 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +Então nós estamos conectados à infraestrutuca telefônica. O próximo passo é enviar mensagens da nossa rede para a rede que nós desejamos alcançar. Para fazer isto, vamos precisar conectar nossa rede
```suggestion
Então nós estamos conectados à infraestrutura telefônica. O próximo passo é enviar mensagens da nossa rede para a rede que nós desejamos alcançar. Para fazer isto, vamos precisar conectar nossa rede a um Provedor de Serviço de Internet (ISP, em inglês). Um ISP é uma companhia que gerencia alguns roteadores especiais que são conectados e podem também acessar roteadores de outros ISPs. Então a mensagem da nossa rede é transportada para a rede de redes do ISP e então para a rede de destino. A Internet é composta por toda esta infraestrutura de redes.
```

2021-11-13 00:47 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +Então nós estamos conectados à infraestrutuca telefônica. O próximo passo é enviar mensagens da nossa rede para a rede que nós desejamos alcançar. Para fazer isto, vamos precisar conectar nossa rede
Alterando 2 erros de digitação "infraestrutuca" e "compania".
Também alterando "pode" para "podem", tendo em vista que está se referindo aos roteadores.

2021-11-13 00:48 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +![Pilha completa da Internet](https://mdn.mozillademos.org/files/8453/internet-schema-7.png)
```suggestion
![Pilha completa da Internet](internet-schema-7.png)
```

2021-11-13 02:11 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +![Mostrando como um nome de domínio pode criar um apelido para um endereço IP](https://mdn.mozillademos.org/files/8405/dns-ip.png)
```suggestion
![Mostrando como um nome de domínio pode criar um apelido para um endereço IP](dns-ip.png)
```

2021-11-13 02:15 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +Como você deve ter notado, quando navegamos na Web com nossos navegadores, normalmente utilizamos os nomes de domínios para chegar a um website. Isto significa que a Internet e a Web são a mesma cois
```suggestion
Como você deve ter notado, quando navegamos na Web com nossos navegadores, normalmente utilizamos os nomes de domínios para chegar a um website. Isto significa que a Internet e a Web são a mesma coisa? Não é tão simples assim. Como vimos, a Internet é uma infraestrutura técnica que permite conectar bilhões de computadores. Entre estes computadores, alguns computadores (chamados de _servidores Web_) podem enviar mensagens inteligíveis para navegadores Web. A _Internet_ é a infraestrutura, enquanto a _Web_ é um serviço construído sob esta infraestrutura. Vale a pena notar que existem diversos outros serviços que funcionam na Internet, tais como email e {{Glossary("IRC")}}.
```

2021-11-13 02:17 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +Como você deve ter notado, quando navegamos na Web com nossos navegadores, normalmente utilizamos os nomes de domínios para chegar a um website. Isto significa que a Internet e a Web são a mesma cois
Corrigindo 2 erros de digitação, estava faltando o "é" de "It's not that simple", a palavra "intelegíveis" é com i, assim "inteligíveis".

2021-11-13 02:21 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +![Representação Gráfica de como uma Extranet e uma Intranet funcionam](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/How_does_the_Internet_work/internet-schema-8.png)
```suggestion
![Representação Gráfica de como uma Extranet e uma Intranet funcionam](internet-schema-8.png)
```

2021-11-13 02:22 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +- [Entendendo a diferença entre uma página web, um website, um servidor web e um mecânismo de pesquisa](https://developer.mozilla.org/pt-BR/docs/Learn/Common_questions/Pages_sites_servers_and_search_
```suggestion
- [Qual a diferença entre página web, site, servidor web e mecanismo de busca?](/pt-BR/docs/Learn/Common_questions/Pages_sites_servers_and_search_engines)
```

2021-11-13 02:23 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +- [Entendendo a diferença entre uma página web, um website, um servidor web e um mecânismo de pesquisa](https://developer.mozilla.org/pt-BR/docs/Learn/Common_questions/Pages_sites_servers_and_search_
```suggestion
- [Entendendo a diferença entre uma página web, um website, um servidor web e um mecânismo de pesquisa](/pt-BR/docs/Learn/Common_questions/Pages_sites_servers_and_search_engines)
```

2021-11-13 02:24 UTC, nathipg commented on files/pt-br/learn/common_questions/how_does_the_internet_work/index.md
> +- [Entendendo nomes de domínio](https://developer.mozilla.org/pt-BR/docs/Learn/Common_questions/What_is_a_domain_name)
```suggestion
- [Entendendo nomes de domínio](/pt-BR/docs/Learn/Common_questions/What_is_a_domain_name)
```

2021-11-13 02:25 UTC, nathipg requested changes
Obrigada pela sua contribuição!
Eu apontei algumas sugestões, poderia dar uma olhada, por favor?
Qualquer dúvida, estou à disposição.

2021-11-13 13:12 UTC, felipedeaquino commented
Ei! Muito obrigado por revisar. Infelizmente acabei me confundindo na hora de acatar as sugestões e gerei muitos commits desnecessários. Desculpe pela incoveniência. Minha ideia foi começar a ter experiência com pull requests e acabei fazendo bagunça.

2021-11-15 23:13 UTC, nathipg approved these changes

2021-11-15 23:15 UTC, nathipg commented
> Ei! Muito obrigado por revisar. Infelizmente acabei me confundindo na hora de acatar as sugestões e gerei muitos commits desnecessários. Desculpe pela incoveniência. Minha ideia foi começar a ter experiência com pull requests e acabei fazendo bagunça.

Sem problemas! Você ajudou muito atualizando essa página e ajudando a acertar a tradução, essas coisas acontecem 😄

2021-11-15 23:31 UTC, nathipg requested changes
Por falar nisso, acabei deixando uma coisa passar também, desculpa.
Poderia adicionar os arquivos de imagem que estão na pasta do repositório content para o translated-content, por favor?


São estes arquivos:

![image](https://user-images.githubusercontent.com/14853904/141868659-d92fbf23-0e41-41c8-a37e-8389d54a49e5.png)

e você adiciona seguindo a mesma estrutura no conteúdo traduzido.

Desculpa não ter pedido junto com as outras alterações.

2021-11-16 16:21 UTC, felipedeaquino commented
Prontinho! 🧙🏻‍♂️

2021-11-16 22:54 UTC, nathipg approved these changes

2021-11-16 22:54 UTC, merged