Firefox 94 for developers を翻訳
mdn/translated-content pull request #3081
Opened 2021-11-13 04:30 UTC by yyss

Nov 5, 2021 の英語版に対応。

2021-11-13 06:39 UTC, mfuji09 requested changes
1点だけ修正をお願いします。

2021-11-13 06:39 UTC, mfuji09 commented on files/ja/mozilla/firefox/releases/94/index.md
> +このページでは、開発者に影響する Firefox 94 の変更点をまとめています。Firefox 94 は、2021 年 11 月 2 日にリリースされました。</p>
行末の\</p>を外してください。
```suggestion
このページでは、開発者に影響する Firefox 94 の変更点をまとめています。Firefox 94 は、2021 年 11 月 2 日にリリースされました。
```

2021-11-14 13:26 UTC, yyss commented
修正しました。

2021-11-16 16:00 UTC, mfuji09 approved these changes
OKです。

2021-11-16 16:00 UTC, merged