fr-glossary/alpha id:85
mdn/translated-content pull request #3137
Opened 2021-11-18 12:23 UTC by ManuSquall

Suggest french translation for files/en-us/glossary/alpha/index.html id:85

I added some extra related doc link in french on line 16 and 17, if it's inadequate please ping me about that to remove it.

2021-11-18 19:23 UTC, SphinxKnight requested changes
L'image n'est pas nécessaire (elle est automatiquement reprise depuis la page anglaise)

2021-11-18 19:26 UTC, SphinxKnight commented on files/fr/glossary/alpha/index.md
> +Les couleurs sont représentées sous forme numérique comme une collection de nombres, chacun représentant la force ou le niveau d'intensité d'un composant donné de la couleur. Chacun de ces composants
```suggestion
Les couleurs sont représentées sous forme numérique comme un ensemble de nombres, chacun représentant la force ou le niveau d'intensité d'un composant donné de la couleur. Chacun de ces composants est appelé un **canal**. Dans un fichier d'image typique, les canaux de couleur décrivent la quantité de rouge, de vert et de bleu utilisée pour composer la couleur finale. Pour représenter une couleur à travers laquelle le fond peut être vu dans une certaine mesure, un quatrième canal est ajouté à la couleur: le **canal alpha**. Le canal alpha spécifie le degré d'opacité de la couleur.
```

2021-11-18 19:34 UTC, SphinxKnight requested changes
Quelques suggestions sur les liens.
Merci déjà @ManuSquall pour cette traduction !

2021-11-18 19:34 UTC, SphinxKnight commented on files/fr/glossary/alpha/index.md
> +- [Canal Alpha](https://fr.wikipedia.org/wiki/Canal_Alpha)
Attention le lien pointe vers un article de chaîne de télévision suisse
```suggestion
- [Article Wikipédia sur le canal alpha](https://fr.wikipedia.org/wiki/Canal_alpha)
```

2021-11-18 19:34 UTC, SphinxKnight commented on files/fr/glossary/alpha/index.md
> +- [Alpha compositing](https://en.wikipedia.org/wiki/Alpha_compositing) (en)
```suggestion
- [Alpha blending](https://fr.wikipedia.org/wiki/Alpha_blending)
```

2021-11-18 19:34 UTC, SphinxKnight commented on files/fr/glossary/alpha/index.md
> +- [Channel (digital image)](https://en.wikipedia.org/wiki/Channel_(digital_image)) (en)
Je pense qu'on peut retirer ce lien anglais avec le reste des autres ressources déjà présentes.
```suggestion
```

2021-11-18 19:34 UTC, SphinxKnight commented on files/fr/glossary/alpha/index.md
> +- [CSS color](/fr/docs/Web/CSS/CSS_Color)
Je pense que la page sur le type `<color>` est plus utile/visuelle pour quelqu'un qui découvre (via le glossaire) que la page concernant *le module de spécification CSS* qui est un concept un peu plus "élevé".
```suggestion
- [Les valeurs de couleurs en CSS](/fr/docs/Web/CSS/color_value)
```

2021-11-19 10:14 UTC, ManuSquall commented
> L'image n'est pas nécessaire (elle est automatiquement reprise depuis la page anglaise)

Je supprime la ligne correspondante alors @SphinxKnight

2021-11-19 10:21 UTC, ManuSquall commented on files/fr/glossary/alpha/index.md
> +- [Canal Alpha](https://fr.wikipedia.org/wiki/Canal_Alpha)
Oups merci!

2021-11-20 09:53 UTC, SphinxKnight commented
@ManuSquall quand je disais que l'image n'était pas nécessaire, je parlais du fichier ajouté via cette PR, pas du lien :)

2021-11-20 10:28 UTC, ManuSquall commented
> @ManuSquall quand je disais que l'image n'était pas nécessaire, je parlais du fichier ajouté via cette PR, pas du lien :)

Merci pour la précision @SphinxKnight , la PR devrait être convenable à présent ?

2021-11-20 18:32 UTC, SphinxKnight approved these changes
Merci @ManuSquall ! Fusionnons tout ça.

2021-11-20 18:32 UTC, merged