fix:issues#2392 and update WeakMap
mdn/translated-content pull request #3227
Opened 2021-11-30 07:27 UTC by meakle

1. fix https://github.com/mdn/translated-content/issues/2392
2. update WeakMap, keep same with English Docs

WeakMap Page：
* English：https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap
* zh-cn： https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/WeakMap

WeakMap 
* English: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap/WeakMap
* zh-cn: null，so I create this page

2021-12-07 13:53 UTC, irvin requested changes
也建議建立新文件時直接使用 markdown 格式

https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/weakmap/weakmap/index.md

2021-12-07 13:53 UTC, irvin commented on files/zh-cn/web/javascript/reference/global_objects/weakmap/weakmap/index.html
> +<h3 id="实现一_个带有_.clear_方法的类_WeakMap_类">实现一 个带有 .clear() 方法的类 <code>WeakMap</code> 类</h3>
請參照最新的原文內容，將 .clear 相關的段落移掉

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap/WeakMap

2021-12-07 13:55 UTC, irvin commented
另，下次可分開成兩個 PR：一個更新舊文件內容，一個建立新的文件。
如此我們即可分開處理與上線，不必因為其中一個文件的問題，而 block 另一個的上線進度。

2021-12-11 03:30 UTC, meakle commented on files/zh-cn/web/javascript/reference/global_objects/weakmap/weakmap/index.html
> +<h3 id="实现一_个带有_.clear_方法的类_WeakMap_类">实现一 个带有 .clear() 方法的类 <code>WeakMap</code> 类</h3>
ok，新文件也改成 markdown 格式了。

2021-12-13 13:23 UTC, t7yang requested changes

2021-12-13 13:23 UTC, t7yang commented on files/zh-cn/web/javascript/reference/global_objects/weakmap/weakmap/index.md
> +
remove this kind of unnecessary newline

2021-12-13 13:23 UTC, t7yang commented on files/zh-cn/web/javascript/reference/global_objects/weakmap/weakmap/index.md
> +-  {{jsxref("WeakSet")}}
a unnecessary space here

2021-12-13 14:19 UTC, meakle commented
I have updated the file format, but Github Action check is wrong.

I ran the command `yarn content validate-redirects --strict` locally. And I can't solve the problem, Could you tell me how to solve it？

thx.

![image](https://user-images.githubusercontent.com/43157411/145828393-c7d8224b-6b02-4c39-b654-5acf16738a74.png)

2021-12-21 13:26 UTC, irvin approved these changes

2021-12-21 13:30 UTC, irvin requested changes
請到[你的 branch 中](https://github.com/meakle/translated-content/tree/issues%232392
)按下 rebase，合併上游最新的進度，即可修復該 CI 錯誤

2022-01-04 16:28 UTC, irvin commented
因為這個 PR 的 history 太複雜，且我一時誤以為 weakmap/index.html 也需轉換為 md，因此再次造成 conflict。已於 #3553 替代並 Merge。

2022-01-04 16:28 UTC, closed without merging

2022-01-04 16:29 UTC, irvin commented
@meakle 請協助檢查是否有正確修正。