fr-glossary/style_origin id:530
mdn/translated-content pull request #3235
Opened 2021-12-01 16:03 UTC by ManuSquall

translate [id 530](https://tristantheb.github.io/history-content/#530) and delete unused tag from CSS file

2021-12-09 12:00 UTC, SphinxKnight requested changes
Il vaudrait mieux que la modification sur le fichier css/index.md soit dans une PR séparée. Ça permettrait de garder un historique plus précis.

Si ça pose problème ou que c'est trop compliqué, n'hésite pas.

2021-12-10 10:02 UTC, ManuSquall commented
Hello @SphinxKnight, merci pour la review! J'ai procédé à un revert du fichier en espérant que celà convienne?

2021-12-12 07:34 UTC, SphinxKnight requested changes

2021-12-12 07:34 UTC, SphinxKnight commented on files/fr/glossary/style_origin/index.md
> +Les origines de style sont utilisées pour déterminer où arrêter de revenir en arrière (ou de revenir en arrière) à travers la cascade de styles qui ont été appliqués à un élément lors de la suppressi
```suggestion
Les origines de style sont utilisées pour déterminer où arrêter de revenir en arrière (ou de revenir en arrière) à travers la cascade de styles qui ont été appliqués à un élément lors de la suppression de styles, par exemple lors de l'utilisation de mots-clés [`unset`](/fr/docs/Web/CSS/unset) ou [`revert`](/fr/docs/Web/CSS/revert).
```

2021-12-12 07:34 UTC, SphinxKnight commented on files/fr/glossary/style_origin/index.md
> +  - : L'origine de l'agent utilisateur est l'origine du style composé des styles par défaut utilisés par le navigateur Web de l'utilisateur. Si aucun autre style n'est appliqué au contenu, les styles
```suggestion
  - : L'origine de l'agent utilisateur est l'origine du style composé des styles par défaut utilisés par le navigateur web de la personne qui consulte le site. Si aucun autre style n'est appliqué au contenu, les styles d'origine de l'agent utilisateur sont utilisés lors du rendu des éléments.
```

2021-12-12 07:34 UTC, SphinxKnight commented on files/fr/glossary/style_origin/index.md
> +  - : L'origine de l'utilisateur est l'origine du style contenant tout CSS que l'utilisateur du navigateur Web a ajouté. Ceux-ci peuvent provenir de l'ajout de styles à l'aide d'un outil de développe
```suggestion
  - : L'origine de l'utilisateur est l'origine du style contenant tout CSS que l'utilisateur du navigateur web a ajouté. Ceux-ci peuvent provenir de l'ajout de styles à l'aide d'un outil de développement ou d'une extension de navigateur qui applique automatiquement des styles personnalisés au contenu, tels que [Stylus](https://add0n.com/stylus.html) ou [Stylish](https://userstyles.org/).
```

2021-12-12 16:29 UTC, SphinxKnight approved these changes
Merci @ManuSquall, ça part en production !

2021-12-12 16:29 UTC, merged