Fix localStorage link
mdn/translated-content pull request #3280
Opened 2021-12-07 00:53 UTC by cw118

Change to correct link for localStorage

Fixes #3247

2021-12-07 12:49 UTC, irvin requested changes

2021-12-07 12:49 UTC, irvin commented on files/zh-cn/web/security/same-origin_policy/index.html
> -<p>访问存储在浏览器中的数据，如 <a href="https://developer.mozilla.org/zh-CN/docs/Web/Guide/API/DOM/Storage">localStorage</a> 和 <a href="https://developer.mozilla.org/zh-CN/docs/IndexedDB">IndexedDB</a>，是以源进行分割。每个
參照英文版應對應到這一篇：
https://developer.mozilla.org/zh-CN/docs/Web/API/Window/localStorage

2021-12-07 12:49 UTC, irvin commented on files/zh-cn/web/security/same-origin_policy/index.html
> + <li>跨域<em><strong>写操作</strong>（Cross-origin writes）</em>一般是被允许的<em>。</em>例如链接（links），重定向以及表单提交。特定少数的HTTP请求需要添加 <a href="https://developer.mozilla.org/zh-CN/docs/Web/HTTP/CORS#Preflighted_requests" t
建議同時將 https://developer.mozilla.org/zh-CN/docs/Web/HTTP/CORS 文件上該段落的 ID 改回原文

2021-12-07 19:55 UTC, cw118 commented on files/zh-cn/web/security/same-origin_policy/index.html
> + <li>跨域<em><strong>写操作</strong>（Cross-origin writes）</em>一般是被允许的<em>。</em>例如链接（links），重定向以及表单提交。特定少数的HTTP请求需要添加 <a href="https://developer.mozilla.org/zh-CN/docs/Web/HTTP/CORS#Preflighted_requests" t
請問 "原文" 指的是中文嗎? 

我已儘量改了，若有錯誤請糾正，謝謝!

2021-12-21 13:13 UTC, irvin approved these changes

2021-12-21 13:14 UTC, merged