Graphic design for responsive sites を新規翻訳
mdn/translated-content pull request #3284
Opened 2021-12-07 16:58 UTC by mfuji09

2021/10/14 時点の英語版に同期

2021-12-18 05:16 UTC, potappo requested changes
誤字脱字の類を修正しましたので、確認お願いします。

2021-12-18 05:16 UTC, potappo commented on files/ja/web/progressive_web_apps/responsive/graphics_for_responsive_sites/index.md
> +[CSS メディアクエリー](/ja/docs/Web/CSS/Media_Queries/Using_media_queries)を使うと、ビューポートの大きさに応じて異なる CSS ルールを提供することができますが、可能な限り[モバイルファーストメディアクエリー](https://www.peachpit.com/articles/article.aspx?p=1960918)の使用を検討す
```suggestion
[CSS メディアクエリー](/ja/docs/Web/CSS/Media_Queries/Using_media_queries)を使うと、ビューポートの大きさに応じて異なる CSS ルールを提供することができますが、可能な限り[モバイルファーストメディアクエリー](https://www.peachpit.com/articles/article.aspx?p=1960918)の使用を検討すべきです。つまり、 CSS 内でメディアクエリーが検出される前の既定のレイアウトは、大きな画面/デスクトップ用のレイアウトではなく、小さな画面/モバイル用のレイアウトにします。そのため、モバイル端末でページが読み込まれた場合はモバイル用の資産のみをダウンロードし、デスクトップ用のリソース資産はダウンロードしなくなります。
```

2021-12-18 05:16 UTC, potappo commented on files/ja/web/progressive_web_apps/responsive/graphics_for_responsive_sites/index.md
> +この節では、様々な解像度の多難つで画像を動作させるための様々戦略について説明します。ここで問題となるのは、ラスター画像を高解像度のデバイスで表示すると、同じ数のピクセルがはるかに小さな画面スペースに表示されるため、小さく見えてしまうということです。ほとんどの高解像度端末では、ウェブページ全体に既定の拡大率が適用され、コンテンツが少しでも読みやすくなるようになっていますが、この場合は、拡大された画
```suggestion
この節では、様々な解像度のデバイスで画像を動作させるための様々な戦略について説明します。ここで問題となるのは、ラスター画像を高解像度のデバイスで表示すると、同じ数のピクセルがはるかに小さな画面スペースに表示されるため、小さく見えてしまうということです。ほとんどの高解像度端末では、ウェブページ全体に既定の拡大率が適用され、コンテンツが少しでも読みやすくなるようになっていますが、この場合は、拡大された画像がピクセル化されて醜く見えてしまうことが欠点です。
```

2021-12-18 18:02 UTC, mfuji09 commented
@potappo さん、レビューありがとうございます！

2021-12-19 15:52 UTC, potappo approved these changes

2021-12-19 15:52 UTC, merged