Web/API/ValidityState 以下を更新
mdn/translated-content pull request #3320
Opened 2021-12-12 01:52 UTC by mfuji09

- 2021/10/13 時点の英語版に同期
- いくつかのプロパティについては新規翻訳

2021-12-18 05:45 UTC, potappo requested changes
誤字脱字を修正しましたので、確認をお願いします。

2021-12-18 05:45 UTC, potappo commented on files/ja/web/api/validitystate/index.md
> +**`ValidityState`** インターフェイスは、制約の検証に関して、要素が取りうる*妥当性の状態*を表します。要素の値が不正な場合、なぜ検証に失敗したのかのかを知る手がかりにもなります。
```suggestion
**`ValidityState`** インターフェイスは、制約の検証に関して、要素が取りうる*妥当性の状態*を表します。要素の値が不正な場合、なぜ検証に失敗したのかを知る手がかりにもなります。
```

2021-12-18 05:45 UTC, potappo commented on files/ja/web/api/validitystate/stepmismatch/index.md
> +フィールドが数値の性質を持つ場合、例えば {{HTMLElement("input/date", "date")}}, {{HTMLElement("input/month", "month")}}, {{HTMLElement("input/week", "week")}}, {{HTMLElement("input/time", "time")}}, {{HTMLElement("input
```suggestion
フィールドが数値の性質を持つ場合、例えば {{HTMLElement("input/date", "date")}}, {{HTMLElement("input/month", "month")}}, {{HTMLElement("input/week", "week")}}, {{HTMLElement("input/time", "time")}}, {{HTMLElement("input/datetime-local", "datetime-local")}}, {{HTMLElement("input/number", "number")}}, {{HTMLElement("input/range", "range")}} の何れかの型であり、 step の値が `any` ではなく、値が [`step`](/ja/docs/Web/HTML/Attributes/step) と [`min`](/ja/docs/Web/HTML/Attributes/min) の値に設定された制約に適合しない場合に、 `stepMismatch` が true になります。フォームコントロールの値から [`min`](/ja/docs/Web/HTML/Attributes/min) の値を引き、 [`step`](/ja/docs/Web/HTML/Attributes/step) 値 (省略時は既定で 1) がゼロでない場合、一致しないと言えます。
```

2021-12-18 18:04 UTC, mfuji09 commented
@potappo 修正ありがとうございます！

2021-12-19 15:53 UTC, potappo approved these changes

2021-12-19 15:53 UTC, merged