fix 修复表述错误
mdn/translated-content pull request #3327
Opened 2021-12-12 14:38 UTC by yionr

貌似英文中表述也有问题，border为inherit不是能够继承吗，为什么说在非继承属性上使用无效？

2021-12-13 13:40 UTC, t7yang requested changes
原始翻譯只是有些微的錯誤（把 override 看成 overload）但整體意思是符合原文的，你的翻譯已經偏離的原文而且沒有必要去提 JS 的行為， inherited 完全是在講 CSS 的行為。如果無法確實理解的話，是否考慮修改 override 的錯誤就好。

2021-12-13 14:27 UTC, yionr commented
是的， 我本次改的内容确实和原文不一致，但是我认为原文的表述也是错误的。 我举了一个例子就是border。 他默认不是一个继承属性，但是当父元素有设置border的前提下，子元素的border设置为inherit是能够成功继承父border的样式的。原文中的表述和实际相违背了：

> https://developer.mozilla.org/en-US/docs/Web/CSS/inherit
> For non-inherited properties, this specifies a behavior that typically makes relatively little sense and you may consider using initial instead, or unset on the all property.

您的意思是，即使如此也应该保持译文和原文的一致性吗？

2021-12-13 15:07 UTC, irvin commented
> 您的意思是，即使如此也应该保持译文和原文的一致性吗？

如果原文有誤，建議先修正原文。

2021-12-16 02:37 UTC, t7yang approved these changes

2021-12-16 02:54 UTC, t7yang commented
@yionr 因為有 CI 的 redirect 錯誤（已經修復）， 你方便把你的分支 rebase 到最新的內容上來協助消除這個 CI 錯誤嗎？

2021-12-16 16:26 UTC, yionr commented
> @yionr 因為有 CI 的 redirect 錯誤（已經修復）， 你方便把你的分支 rebase 到最新的內容上來協助消除這個 CI 錯誤嗎？

sorry，我意识到git比较短板，CI/CD也不太了解。 我这样操作正确吗？如果把事情变得复杂了那我重新PR一下

2021-12-16 18:02 UTC, SphinxKnight requested changes
Please revert those changes to keep the PR to a single file or at least a single locale.

2021-12-17 00:42 UTC, closed without merging