AbortControllerの日本語訳
mdn/translated-content pull request #3385
Opened 2021-12-17 05:11 UTC by nissy-dev

以下のページを日本語に翻訳しました。
https://developer.mozilla.org/en-US/docs/Web/API/AbortController

2021-12-20 16:59 UTC, mfuji09 requested changes
原文は既にMarkdownになっていますので、HTMLではなくMarkdownで翻訳してくださるようお願いいたします。

2022-01-12 05:39 UTC, nissy-dev commented
@mfuji09 
レビューありがとうございます！遅くなってしまったのですが、Markdownで翻訳してみたので再度レビュー宜しくお願いします。

2022-01-12 14:38 UTC, mfuji09 requested changes
ガイドラインに基づく修正をお願いします。
（ガイドラインは https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline にあります。）

2022-01-12 14:38 UTC, mfuji09 commented on files/ja/web/api/abortcontroller/index.md
> +{{domxref("AbortController.AbortController()")}}コンストラクタを使うことで `AbortController` オブジェクトを新しく作ることができます。DOMリクエストとの送信は、AbortSignalオブジェクトを使って行われます。
英字と日本語の間は1文字空けてください。
また、 Constructor のように -er や -or で終わる単語は、「コンストラクター」のように長音をつけてください。

こちらのガイドラインを参照してください。
https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline

2022-01-14 14:09 UTC, mfuji09 approved these changes

2022-01-14 14:12 UTC, merged