同步英语版本修改
mdn/translated-content pull request #3455
Opened 2021-12-26 10:15 UTC by yionr

删掉的半句表述是错误的， 英文原文中已经删除

2021-12-27 14:42 UTC, t7yang requested changes

2021-12-27 14:42 UTC, t7yang commented on files/zh-cn/web/css/inherit/index.html
> +<p>对于继承属性，inherit 关键字只是增强了属性的默认行为，通常只在覆盖原有的值的时候使用。</p>
遺漏了 inherited properties 的連結

> For [inherited properties](/en-US/docs/Web/CSS/inheritance#Inherited_properties), this reinforces the default behavior, and is only needed to override another rule.

2021-12-27 15:43 UTC, yionr commented on files/zh-cn/web/css/inherit/index.html
> +<p>对于继承属性，inherit 关键字只是增强了属性的默认行为，通常只在覆盖原有的值的时候使用。</p>
抱歉，没太懂您的意思，您引用的这句话不就是中文原句的前半句，也就是我删除之后保留的那句吗

> 对于继承属性，inherit 关键字只是增强了属性的默认行为，通常只在覆盖原有的值的时候使用。

上面这句就是对下面这句的翻译

> For inherited properties, this reinforces the default behavior, and is only needed to override another rule.

2022-01-04 14:26 UTC, irvin requested changes

2022-01-04 14:26 UTC, irvin commented on files/zh-cn/web/css/inherit/index.html
> +<p>对于继承属性，inherit 关键字只是增强了属性的默认行为，通常只在覆盖原有的值的时候使用。</p>
<img width="682" alt="截圖 2022-01-04 下午10 24 43" src="https://user-images.githubusercontent.com/165936/148073429-051df709-1d7b-413e-8c88-c25edcdf1e69.png">

在 inherited properties 上的連結漏掉了： ```https://developer.mozilla.org/en-US/docs/Web/CSS/inheritance#inherited_properties```

對應的中文頁面為
```https://developer.mozilla.org/zh-TW/docs/Web/CSS/inheritance#inherited_properties```

2022-01-04 16:08 UTC, yionr reviewed
已添加

2022-01-10 15:45 UTC, t7yang approved these changes

2022-01-10 15:45 UTC, merged