fix: equalateral triangle
mdn/translated-content pull request #355
Opened 2021-03-29 13:32 UTC by harukitosa

#308 
https://github.com/mdn/translated-content/issues/308

二等辺三角形 -> 正三角形に修正しました。

2021-03-29 15:25 UTC, mfuji09 approved these changes
下記の修正をお願いします。

2021-03-29 15:25 UTC, mfuji09 commented on files/ja/web/javascript/reference/global_objects/math/index.html
>  <p>二等辺三角形の高さを計算したい場合、側辺の長さが 100 であるとわかっている場合は、<em>隣の角に正接を乗じた長さは、反対側と等しくなる</em>という数式を使用することができます。</p>
こちらの「二等辺三角形」も修正してください。

2021-03-29 15:26 UTC, mfuji09 requested changes
下記の修正をお願いします。

2021-03-29 20:18 UTC, femshima commented
確認しました。ありがとうございます。

2021-03-30 02:07 UTC, harukitosa commented
@mfuji09 
見逃していました、ありがとうございます修正しました。

2021-03-30 03:06 UTC, mfuji09 approved these changes
良いと思います。

2021-03-30 14:21 UTC, merged