[ko] Translation done of `Using custom elements` document
mdn/translated-content pull request #3580
Opened 2022-01-07 07:22 UTC by logic-finder

https://developer.mozilla.org/ko/docs/Web/Web_Components/Using_custom_elements
기존 문서에 다음의 수정을 진행하였습니다.

- 확장자 변경
- 영어 버전과 동일하게 변경
- 기존 번역 개선
- 미번역된 부분 번역

2022-01-15 05:22 UTC, logic-finder commented
포스푸시 이유) 3b3d21b 의 89번줄 주석 번역을 안한 걸 발견해서 고쳤습니다. 마크다운 가이드에 따라 커밋 수를 맞추기 위해 포스푸시를 하였습니다.

2022-02-01 16:33 UTC, hochan222 requested changes
안녕하세요. @logic-finder 님 번역해주신 글 잘 읽었습니다.

코드에서 개행 생략으로 읽기 불편한 부분이 있어서 개행 수정 요청드립니다.

수정해주시면 바로 병합하겠습니다.

좋은 하루 보내시고, 새해복 많이 받으세요. 기여해주셔서 감사합니다 :)

2022-02-01 16:33 UTC, hochan222 commented on files/ko/web/web_components/using_custom_elements/index.md
> +  }
```suggestion
class WordCount extends HTMLParagraphElement {
  constructor() {
    // 항상 super를 생성자에서 먼저 호출합니다
    super();
    
    // 요소 기능은 여기 작성됩니다
    
    ...
  }
```

2022-02-01 16:33 UTC, hochan222 commented on files/ko/web/web_components/using_custom_elements/index.md
> +this.shadowRoot.append(style,wrapper);
```suggestion
// shadow root을 생성합니다
this.attachShadow({mode: 'open'}); // 'this.shadowRoot'을 설정하고 반환합니다

// (중첩된) span 요소들을 생성합니다
const wrapper = document.createElement('span');
wrapper.setAttribute('class','wrapper');
const icon = wrapper.appendChild(document.createElement('span'));
icon.setAttribute('class','icon');
icon.setAttribute('tabindex', 0);
// 정의된 특성으로부터의 아이콘 혹은 기본 아이콘을 삽입합니다
const img = icon.appendChild(document.createElement('img'));
img.src = this.hasAttribute('src') ? this.getAttribute('src') : 'img/default.png';

const info = wrapper.appendChild(document.createElement('span'));
info.setAttribute('class','info');
// 특성의 내용을 취하고 그것을 info span 내부에 넣습니다
info.textContent = this.getAttribute('data-text');

// shadow dom에 적용할 몇 가지 CSS를 생성합니다
const style = document.createElement('style');
style.textContent = '.wrapper {' +
// 간결함을 위해 CSS 생략됨

// 생성된 요소들을 shadow DOM에 부착합니다
this.shadowRoot.append(style,wrapper);
```

2022-02-01 16:33 UTC, hochan222 commented on files/ko/web/web_components/using_custom_elements/index.md
> +shadow.appendChild(linkElem);
```suggestion
// 외부 스타일을 shadow dom에 적용하기
const linkElem = document.createElement('link');
linkElem.setAttribute('rel', 'stylesheet');
linkElem.setAttribute('href', 'style.css');

// 생성된 요소를 shadow dom에 부착하기
shadow.appendChild(linkElem);
```

2022-02-01 16:33 UTC, hochan222 commented on files/ko/web/web_components/using_custom_elements/index.md
> +}
```suggestion
class ExpandingList extends HTMLUListElement {
  constructor() {
    // 항상 super를 생성자에서 먼저 호출합니다
    super();
    
    // 요소 기능을 여기 작성합니다
    
    ...
  }
}
```

2022-02-01 16:33 UTC, hochan222 commented on files/ko/web/web_components/using_custom_elements/index.md
> +shadow.appendChild(div);
```suggestion
const shadow = this.attachShadow({mode: 'open'});

const div = document.createElement('div');
const style = document.createElement('style');
shadow.appendChild(style);
shadow.appendChild(div);
```

2022-02-01 16:33 UTC, hochan222 commented on files/ko/web/web_components/using_custom_elements/index.md
> +}
```suggestion
disconnectedCallback() {
  console.log('Custom square element removed from page.');
}

adoptedCallback() {
  console.log('Custom square element moved to new page.');
}
```

2022-02-01 16:43 UTC, logic-finder commented
리뷰해 주셔서 감사합니다. 새해 복 많이 받으세요.

2022-02-01 16:54 UTC, hochan222 approved these changes

2022-02-01 16:54 UTC, merged