Learn/JavaScript/Objects/JSON を更新
mdn/translated-content pull request #3683
Opened 2022-01-14 14:15 UTC by mfuji09

Fix #2720

2022-01-22 05:24 UTC, potappo requested changes
不自然な空白があったのを修正しました。確認をお願いします。

2022-01-22 05:24 UTC, potappo commented on files/ja/learn/javascript/objects/json/index.md
> +5.  最後に、サーバーからのレスポンスを待ち、それを処理するコードを用意するので、以下のコードをこれま でのコードの下に追加してください。
```suggestion
5.  最後に、サーバーからのレスポンスを待ち、それを処理するコードを用意するので、以下のコードをこれまでのコードの下に追加してください。
```

2022-01-22 11:19 UTC, mfuji09 commented on files/ja/learn/javascript/objects/json/index.md
> +5.  最後に、サーバーからのレスポンスを待ち、それを処理するコードを用意するので、以下のコードをこれま でのコードの下に追加してください。
ありがとうございます！

2022-01-23 13:03 UTC, potappo approved these changes

2022-01-23 13:04 UTC, merged