first-class function (not parameter, arguments)
mdn/translated-content pull request #3841
Opened 2022-01-26 15:13 UTC by rbals0445

- 영어 원문을 보면  a function can be passed as an `argument` 로 되어있습니다. 
-  argument와 parameter는 분명히 다른 개념이기도 하고, 실제로 example에서도 함수 argument(인자)로 넘기는 예시를 보여주고 있습니다.  매개변수 -> 인자로 수정하는것이 조금 더 정확할것 같다고 생각합니다!

2022-01-29 14:01 UTC, cos18 commented
기여해주셔서 감사합니다! 해당 내용은 번역 가이드의 용어집을 수정하는 등의 논의가 필요할 것 같아 추가 PR (#3888)을 만들고 논의를 한 후 처리를 할 예정입니다. 빠르게 해결한 이후 리뷰해드리겠습니다!

2022-02-05 05:19 UTC, cos18 requested changes
아직 #3888 이 완료되지 않았지만 빠른 처리를 위해 미리 리뷰 드립니다.

2022-02-05 05:19 UTC, cos18 commented on files/ko/glossary/first-class_function/index.html
> +<p>함수를 다른 변수와 동일하게 다루는 언어는 <strong>일급 함수</strong>를 가졌다고 표현합니다. 예를 들어, 일급 함수를 가진 언어에서는 함수를 다른 함수에 인자로 제공하거나, 함수가 함수를 반환할 수 있으며, 변수에도 할당할 수 있습니다.</p>
#3888 에 따르면 argument는 전달인자 혹은 인수로 번역하는 것이 올바릅니다. 해당 내용 수정 부탁드립니다!

2022-02-05 14:06 UTC, rbals0445 commented on files/ko/glossary/first-class_function/index.html
> +<p>함수를 다른 변수와 동일하게 다루는 언어는 <strong>일급 함수</strong>를 가졌다고 표현합니다. 예를 들어, 일급 함수를 가진 언어에서는 함수를 다른 함수에 인자로 제공하거나, 함수가 함수를 반환할 수 있으며, 변수에도 할당할 수 있습니다.</p>
인수로 수정 했습니다~

2022-02-06 06:29 UTC, cos18 approved these changes
LGTM! 기여 감사합니다 👍

2022-02-06 06:30 UTC, merged