[ko] updated css border page
mdn/translated-content pull request #3879
Opened 2022-01-29 08:38 UTC by kraccoon-dev

<a href="https://developer.mozilla.org/ko/docs/Web/CSS/border">border</a> 페이지의 아래 오류를 수정했습니다.
- 형식 구문 중복 코드블록 제거
- 명세 테이블 수정
- 같이 보기 해더 추가

2022-01-29 14:13 UTC, cos18 requested changes
기여해주셔서 감사합니다! 사소한 오타 제외하곤 이상 없는 것 같습니다. 수정 후 re-request 부탁드립니다!

2022-01-29 14:13 UTC, cos18 commented on files/ko/web/css/border/index.html
> +  <li><a href="/ko/docs/Learn/CSS/Building_blocks/Backgrounds_and_borders">css 배우기: 배경 및 테두리</a></li>
```suggestion
  <li><a href="/ko/docs/Learn/CSS/Building_blocks/Backgrounds_and_borders">CSS 배우기: 배경 및 테두리</a></li>
```
CSS는 고유명칭이기 때문에 대문자를 사용해주세요.

2022-01-29 14:55 UTC, kraccoon-dev commented on files/ko/web/css/border/index.html
> +  <li><a href="/ko/docs/Learn/CSS/Building_blocks/Backgrounds_and_borders">css 배우기: 배경 및 테두리</a></li>
확인해주셔서 감사합니다! 다음에는 더욱 꼼꼼히 작업해야겠어요🥲

2022-01-30 03:39 UTC, cos18 approved these changes
LGTM 👍

2022-01-30 03:40 UTC, merged