Remove {{page}} macro from API docs
mdn/translated-content pull request #3913
Opened 2022-01-30 12:59 UTC by alattalatta

#3897 

- `{{page}}` 제거
- Markdown (히스토리 없는 문서만)
  - 내용 수정 없습니다.

2022-02-20 10:06 UTC, cos18 requested changes
기여 감사드립니다. 리뷰드린 내용 확인 부탁드립니다!

2022-02-20 10:06 UTC, cos18 commented on files/ko/web/api/navigator/battery/index.html
> -<h2 id="브라우저_호환">브라우저 호환</h2>
브라우저 호환에 대한 내용이 원문에는 있는데 현재 없는 상황입니다.

```
## Browser compatibility

{{Compat}}
```

2022-02-20 10:06 UTC, cos18 commented on files/ko/web/api/screen/index.html
> -<p>{{page("/en-US/docs/Web/API/EventTarget","Methods")}}</p>
원본에서는 첫 문자가 대문자인 Page 매크로를 사용해서 내용을 보여주고 있는데 이 내용도 같이 지워야하는 매크로인가요?

https://github.com/mdn/content/blob/330026e2c4ce1ae92476d6a93f3bee425ddfcb0b/files/en-us/web/api/screen/index.md?plain=1#L60

2022-02-20 11:33 UTC, alattalatta commented on files/ko/web/api/screen/index.html
> -<p>{{page("/en-US/docs/Web/API/EventTarget","Methods")}}</p>
매크로는 대소문자 구분을 하지 않습니다. `{{Page}}`와 `{{page}}` 모두 제거 대상입니다.

2022-02-21 01:03 UTC, cos18 approved these changes
LGTM👍 수고하셨습니다!

2022-02-21 01:04 UTC, merged