Fixed weird code example on the french `split()` page
mdn/translated-content pull request #399
Opened 2021-04-03 19:24 UTC by ElMaxonDSCRD

I changed the `for` loop and the `print()` function (??? Python ???) to a simple `.join(' / ')`

2021-04-03 19:33 UTC, SphinxKnight approved these changes
Merci @ElMaxonDSCRD ! ça me paraît bien :) (print était il y a … très … longtemps utilisée dans la doc comme équivalent de `console.log` :/ ) 
Le seul truc sur lequel je pourrais pinailler et qui peut être amélioré au passage c'est le mélange qui subsiste entre les délimiteurs de chaînes de caractères (on a " et ' ). Je laisse le dernier mot à @tristantheb

2021-04-03 19:56 UTC, tristantheb commented
Bonsoir :)

Puisque l'exemple utilise beaucoup de variables dans ses chaines de caractères, et que ça mélange beaucoup les différents signes jusqu'à l'utilisation d'un backslash « \ » pour éviter de casser la chaine de caractères au milieu de la phrase. Je serai d'avis que le bloc de code soit mis à jour sous le format expliqué ici : https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Template_literals

Exemple d'utilisation :
```JS
const username = "Michel";
console.log(`Je m'appelle ${username}`);
// Retourne : Je m'appelle Michel
// Et ça ne nécessite pas de protection pour les divers apostrophes que l'on peut avoir en Français
```

Cette méthode d'écriture propre à EcmaScript 2015 est conseillée pour l'écriture des blocs d'exemple lorsqu'on doit mélanger signes et trou de variables. Ça rend les exemples plus propres, plus facile à lire, et ça aide aussi les gens à s'habituer à cette « nouvelle » écriture (qui a 6 ans...)

La page pour le moment en Anglais des lignes directrices pour JS : https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/JavaScript#use_template_literals

2021-04-05 11:54 UTC, SphinxKnight commented
Cross-ref: #387

2021-04-07 11:35 UTC, tristantheb requested changes
See https://github.com/mdn/translated-content/pull/399#issuecomment-812917788

2021-04-12 13:57 UTC, tristantheb approved these changes
Is ok for me now

2021-04-12 13:59 UTC, merged