[pt-BR] translations listformat and constructor
mdn/translated-content pull request #4052
Opened 2022-02-08 15:29 UTC by italogois

Translation of the pages [Intl.ListFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat) and [Intl.ListFormat() constructor
](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/ListFormat)

2022-02-22 00:25 UTC, nathipg requested changes
Muito obrigada pela contribuição!
Poderia dar uma olhada nos apontamentos que eu fiz, por favor?
Qualquer dúvida/questão pode me perguntar :D

2022-02-22 00:25 UTC, nathipg commented on files/pt-br/web/javascript/reference/global_objects/intl/listformat/listformat/index.md
> +  - : Uma string com a tag de idioma BCP 47, ou um array de string. Veja de forma geral a interpretação do argumento `locales`, see the
```suggestion
  - : Uma string com a tag de idioma BCP 47, ou um array de tais strings. Veja de forma geral a interpretação do argumento `locales` na página
```

2022-02-22 00:25 UTC, nathipg commented on files/pt-br/web/javascript/reference/global_objects/intl/listformat/listformat/index.md
> +      1)}} page.
```suggestion
      1)}}.
```

2022-02-22 00:25 UTC, nathipg commented on files/pt-br/web/javascript/reference/global_objects/intl/listformat/listformat/index.md
> +      - : O algoritimo locale matching para ser utilizado. Os possiveis valores são "`lookup`"
```suggestion
      - : O algoritmo de correspondência de localidade para ser utilizado. Os possíveis valores são "`lookup`"
```

2022-02-22 00:25 UTC, nathipg commented on files/pt-br/web/javascript/reference/global_objects/intl/listformat/listformat/index.md
> +        que representa listas com "e" (default, e.g., "`A, B, e C`"), ou
```suggestion
        que representa listas com "e" (padrão, e.g., "`A, B, e C`"), ou
```

2022-02-22 00:25 UTC, nathipg commented on files/pt-br/web/javascript/reference/global_objects/intl/listformat/listformat/index.md
> +        "`A, B, ou C`"). "`unit`" que representa listas com valores de unidade (e.g., "`5 pounds, 12 ounces`").
```suggestion
        "`A, B, ou C`"). "`unit`" que representa listas com valores de unidade (e.g., "`5 libras, 12 onças`").
```

2022-02-22 00:25 UTC, nathipg commented on files/pt-br/web/javascript/reference/global_objects/intl/listformat/listformat/index.md
> +        (default, e.g., "`A, B, e C`"); "`short`" (e.g.,
```suggestion
        (padrão, e.g., "`A, B, e C`"); "`short`" (e.g.,
```

2022-02-22 10:43 UTC, italogois commented
oi [nathipg](https://github.com/nathipg), as correções foram feitas.

2022-03-26 05:42 UTC, nathipg commented on files/pt-br/web/javascript/reference/global_objects/intl/listformat/index.md
> +  - : Retorna um array com as localidades fornecidas com suporte sem precisar retornar à localidade padrão do tempo de execução.
```suggestion
  - : Retorna um array com as localidades fornecidas com suporte sem precisar depender da localidade padrão do tempo de execução.
```

2022-03-26 05:43 UTC, nathipg commented on files/pt-br/web/javascript/reference/global_objects/intl/listformat/index.md
> +  - : Retorna um array de objetos representando os diferentes componentes que podem ser usados para formatar uma lista de valores com reconhecimento de localidade
```suggestion
  - : Retorna um array de objetos representando os diferentes componentes que podem ser usados para formatar uma lista de valores com reconhecimento de localidade.
```

2022-03-26 05:44 UTC, nathipg commented on files/pt-br/web/javascript/reference/global_objects/intl/listformat/index.md
> +O exemplo a seguir mostra como criar o List formarter utilizando o idioma Português.
```suggestion
O exemplo a seguir mostra como criar o List formatter utilizando o idioma Português.
```

2022-03-26 05:46 UTC, nathipg commented on files/pt-br/web/javascript/reference/global_objects/intl/listformat/index.md
> +O exemplo a seguir mostra como criar o List formarter retornando as partes formatadas.
```suggestion
O exemplo a seguir mostra como criar o List formatter retornando as partes formatadas.
```

2022-03-26 05:48 UTC, nathipg commented on files/pt-br/web/javascript/reference/global_objects/intl/listformat/index.md
> +- {{jsxref("Intl")}}
```suggestion
- {{jsxref("Intl")}}
- [Um polyfill para `Intl.ListFormat` no FormatJS](https://formatjs.io/docs/polyfills/intl-listformat)
```

2022-03-26 05:48 UTC, nathipg commented on files/pt-br/web/javascript/reference/global_objects/intl/listformat/index.md
> +## Polyfill
```suggestion
```

2022-03-26 05:49 UTC, nathipg commented on files/pt-br/web/javascript/reference/global_objects/intl/listformat/index.md
> +## Polyfill
```suggestion
```

2022-03-26 05:50 UTC, nathipg commented on files/pt-br/web/javascript/reference/global_objects/intl/listformat/index.md
> +
```suggestion
```

2022-03-26 05:52 UTC, nathipg commented on files/pt-br/web/javascript/reference/global_objects/intl/listformat/listformat/index.md
> +## Syntaxe
```suggestion
## Sintaxe
```

2022-03-26 05:59 UTC, nathipg requested changes
Obrigada pelas correções!

Agora foram só alguns erros de digitação, no geral está muito bom :D 

Na parte do fallback, sugeri a mudança para "depender" para a parte "having to fall back to" pela definição ser "have recourse to something when in difficulty." e fazer mais sentido na frase em português. Veja se você concorda com isso, por favor.

Também tirei a seção de Polyfill e adicionei nas referências para manter a estrutura da página em inglês. Me baseei na estrutura atual da página que está na branch main do content, mas caso seja referência a algum PR que ainda não entrou me avisa, por favor.

2022-04-09 00:47 UTC, nathipg approved these changes
Show de bola! Muito obrigada pela contribuição 😁

2022-04-09 00:55 UTC, merged