convert text-overflow zh-cn to md
mdn/translated-content pull request #4078
Opened 2022-02-10 07:05 UTC by fish-404

* convert text-overflow zh-cn index.html to index.md
* sync zh-cn content with en-us content

2022-02-15 16:26 UTC, irvin requested changes
在轉換 html > md 時，第一個 commit 需是變更檔名（將 .html 直接更名為 .md），其他修改再於後續 commit 進行。請參考其餘格時轉換的 MR 作法：
https://github.com/mdn/translated-content/pull/3805/commits

2022-02-18 16:04 UTC, fish-404 reviewed
Fix links

2022-03-01 13:20 UTC, irvin commented
> 明白了，謝謝，下次留意。另外我更新了幾個鏈接。

因為上面的這個步驟是硬性要求，建議你重新開一遍 PR，並把結果手動複製貼過去

2022-03-01 13:21 UTC, irvin requested changes
please redo the PR to ensure content of the first commit were mv .html to .md

2022-03-01 16:10 UTC, closed without merging