Convert Estilizando formularios HTML to Markdown
mdn/translated-content pull request #4095
Opened 2022-02-10 17:52 UTC by GNosii

Related to #3859

Missing screenshots:
- search-chrome-macos.png
- size-chrome-win7.png

2022-02-10 23:22 UTC, Vallejoanderson commented
Hola. @GNosii. Comparandolo con la version en ingles, algunos texto no coinciden o no son traduccion fiel del original. Podrias darle una segunda chequeada?

2022-02-11 23:34 UTC, Vallejoanderson commented on files/es/learn/forms/styling_web_forms/index.md
> +En este artículo aprenderemos como utilizar [CSS](/es/docs/Web/CSS) con formularios [HTML](/es/docs/Web/HTML) para hacerlos más atractivos. Aunque parezca extraño, esto es algo que puede llegar a ser
Nos ayudaria mucho que le dieras una chequeada a los siguientes parrafos para tener un resultado mas fiel al original :smiley:

2022-02-11 23:34 UTC, Vallejoanderson commented on files/es/learn/forms/styling_web_forms/index.md
> +#### El bueno
```suggestion
#### Lo bueno
```

2022-02-11 23:34 UTC, Vallejoanderson commented on files/es/learn/forms/styling_web_forms/index.md
> +#### El malo
```suggestion
#### Lo malo
```

2022-02-11 23:34 UTC, Vallejoanderson commented on files/es/learn/forms/styling_web_forms/index.md
> +#### El feo
```suggestion
#### Lo feo
```

2022-02-11 23:34 UTC, Vallejoanderson commented on files/es/learn/forms/styling_web_forms/index.md
> +* `<input type="file">`
Algunos de los inputs no redigiren a los vinculos de la [version en ingles](https://developer.mozilla.org/en-US/docs/Learn/Forms/Styling_web_forms) puedes comparar este codigo con el original [aqui](https://raw.githubusercontent.com/mdn/content/main/files/en-us/learn/forms/styling_web_forms/index.md) para que puedas guiarte.

2022-02-16 01:33 UTC, GNosii commented on files/es/learn/forms/styling_web_forms/index.md
> +* `<input type="file">`
Creo que lo resolví, podrías verificar y comentar nuevamente?

2022-02-16 03:14 UTC, Vallejoanderson commented
Hola, @GNosii. Recuerda que la version en espanol debe ser copia fiel del original. Has comparado todos los parrafos y segmentos de codigo [entre el original](https://raw.githubusercontent.com/mdn/content/main/files/en-us/learn/forms/styling_web_forms/index.md) y la version traduccida? Te hago observacion de tres cositas de la primera parte a revisar y comprar con la version [en ingles](https://raw.githubusercontent.com/mdn/content/main/files/en-us/learn/forms/styling_web_forms/index.md). 

1. Linea 7 no incluye todos los macros de la version `{{LearnSidebar}}{{PreviousMenuNext("Learn/Forms/Other_form_controls","Learn/Forms/Advanced_form_styling","Learn/Forms")}}.`
2. Linea 9, no es version fiel a la inglesa.
3. Luego del parrafo del punto anterior hay una tabla que si esta en la version en ingles.

Nos estas ayudando mucho :partying_face:  , nos gustaria tener una comunicacion mas directa contigo a traves de la [Matrix](https://chat.mozilla.org/#/room/!KawFgLWgqcAgSiGDXS:mozilla.org) o respondiendo a este mismo comentario acerca de tus dudas inquietudes o metodologia de trabajo, gracias @GNosii.

2022-02-21 17:09 UTC, Graywolf9 commented
Hola! @GNosii muchas gracias por tu valiosa ayuda. Veo que uno de los test esta fallando y es por una imagen, te comento que en los idiomas traducidos no hace falta tener las imágenes ya que estas se toman automáticamente de la versión en inglés, ¿crees que puedas retirar las imágenes?

De antemano muchas gracias y nuevamente agradecemos tu valiosa ayuda.

2022-03-03 16:22 UTC, Graywolf9 commented
Hola! @GNosii mis disculpas de antemano, ante la falta de respuesta me he tomado el tiempo de retirar los archivos en conflicto (las imágenes). Cualquier cosa seguimos al pendiente para ayudarte

Saludos.

2022-03-04 00:49 UTC, Graywolf9 requested changes
No he terminado la revisión, pero son las observaciones y sugerencias al momento :)

2022-03-06 18:04 UTC, GNosii commented
> Hola! @GNosii mis disculpas de antemano, ante la falta de respuesta me he tomado el tiempo de retirar los archivos en conflicto (las imágenes). Cualquier cosa seguimos al pendiente para ayudarte
> 
> Saludos.

Disculpa por la falta de respuesta, había estado lejos del computador algunos días. Busque las imágenes en la versión en inglés y tampoco las encontré, que pasa en ese caso?

2022-03-18 23:01 UTC, Graywolf9 commented on files/es/learn/forms/styling_web_forms/index.md
> +- [Tabla de compatibilidad de propiedades para controles de formulario](/es/docs/Learn/Forms/Property_compatibility_table_for_form_controls)
```suggestion
- [Tabla de compatibilidad de propiedades para controles de formulario](/es/docs/Learn/Forms/Property_compatibility_table_for_form_controls)

```

2022-03-18 23:03 UTC, Graywolf9 approved these changes

2022-03-18 23:04 UTC, Graywolf9 commented
Hola! @GNosii una apenada disculpa, me he tomado la libertad de traducir y actualizar el contenido faltante, muchísimas gracias por tu valiosa aportación a este artículo!

En estos momentos estamos trabajando en actualizar la documentación en Español con la versión en inglés

Si deseas seguir apoyando puedes:
* Actualizar el contenido de otras páginas con la versión en inglés
* Convertir html a md
* [Reportar issues](https://github.com/mdn/translated-content/issues/new/choose)
* [Revisar issues](https://github.com/mdn/translated-content/issues?q=is%3Aissue+is%3Aopen+label%3Al10n-es)
* [Unirte a nuestro equipo](https://chat.mozilla.org/#/room/!cIEBGoIHFpsXNeVUwp:mozilla.org)

Saludos.

2022-04-27 04:31 UTC, JuanVqz commented
Definitivamente listo para merge!! @GNosii @Graywolf9 muchas gracias!!!

2022-04-27 04:31 UTC, merged