Content sync and updated to md | Javascript/reference [ES]
mdn/translated-content pull request #4110
Opened 2022-02-11 16:20 UTC by Vallejoanderson

Fixes #4108

2022-02-14 15:13 UTC, JuanVqz reviewed
@Vallejoanderson muy buen trabajo... Gracias por tu aportación! 

Hice unos comentarios, esperando comentarios de los demás...

2022-02-14 15:13 UTC, JuanVqz commented on files/es/web/javascript/reference/index.md
> +### Abstracción de control
Creo que aquí seria, pero no estoy seguro.

```suggestion
### Control de abstracción
```

2022-02-14 15:13 UTC, JuanVqz commented on files/es/web/javascript/reference/index.md
> +### Flujo de control
Igual no estoy seguro pero lo dejo aquí por si alguien tiene más luz en el tema pueda aportar algo...

Mi justificación es por que estamos hablando de `if/else`, `switch`, etc, y lo que hacen es el `control de flujo`.

```suggestion
### Control de flujo
```

2022-02-14 15:13 UTC, JuanVqz commented on files/es/web/javascript/reference/index.md
> +### Operadores de desplazamiento bitwise
No conozco la palabra `bitwise` pero segun google dice que es `bit a bit`.
Entonces no se si sea bueno traducir o no, como en el caso de `webassembly` no fue necesario...

```suggestion
### Operadores de desplazamiento bit a bit
```

2022-02-14 15:27 UTC, davbrito commented on files/es/web/javascript/reference/index.md
> +original_slug: Web/JavaScript/Referencia
Yo estuve viendo y parece que eso se genera automaticamente con un script de Yari, en ésta linea https://github.com/mdn/yari/blob/9d0669d148d5fdc0feec74f605ff8ed9def6233c/build/sync-translated-content.js#L210

2022-02-14 15:46 UTC, davbrito commented on files/es/web/javascript/reference/index.md
> +### Abstracción de control
@JuanVqz el correcto es "Abstracción de control".

2022-02-14 16:15 UTC, davbrito requested changes
Muy bien. Te dejo algunos comentarios por aquí.

2022-02-14 16:15 UTC, davbrito commented on files/es/web/javascript/reference/index.md
> +### Manejo de memoria
```suggestion
### Gestión de memoria
```

2022-02-14 16:15 UTC, davbrito commented on files/es/web/javascript/reference/index.md
> +### Operadores igualitarios
```suggestion
### Operadores de igualdad
```

2022-02-14 16:15 UTC, davbrito commented on files/es/web/javascript/reference/index.md
> +### Operadores condicionales (ternarios)
Es en singular pues se refiere a un solo operador.

```suggestion
### Operador condicional (ternario)
```

2022-02-14 16:15 UTC, davbrito commented on files/es/web/javascript/reference/index.md
> +## Páginas adiciones de referencia
```suggestion
## Páginas adicionales de referencia
```

2022-02-14 16:17 UTC, davbrito commented
> @mdn/yari-content-es por cierto, este PR indica como ~70 páginas sin traducir, debemos crear un issue para todas estas. Quien se encarga de hacerlo? el que crea el PR, el que revisa o el que hace merge?

Creo que sería conveniente crear un Issue padre donde vayamos agregando todas las páginas que aún no existen en español. Y a partir de ahí se crean los issues individuales.

2022-02-14 16:40 UTC, JuanVqz commented
> > @mdn/yari-content-es por cierto, este PR indica como ~70 páginas sin traducir, debemos crear un issue para todas estas. Quien se encarga de hacerlo? el que crea el PR, el que revisa o el que hace merge?
> 
> Creo que sería conveniente crear un Issue padre donde vayamos agregando todas las páginas que aún no existen en español. Y a partir de ahí se crean los issues individuales.

Bueno si me parece bien, por eso decia hacer un issue con las ~70 páginas e ir tomando de ahí, pero si suena mejor uno para TODAS y luego vamos haciendo issues más pequeños, y para no saturar de issues en Español.

2022-02-14 17:26 UTC, Graywolf9 commented on files/es/web/javascript/reference/index.md
> +## Objetos globales
Verificar traducción `built-in`

2022-02-14 17:36 UTC, Graywolf9 commented on files/es/web/javascript/reference/index.md
> +### Propiedades de valor
Sugerencia: quizá `propiedades de tipo valor`

2022-02-14 17:52 UTC, Graywolf9 commented on files/es/web/javascript/reference/index.md
> +### Propiedades de funciones
Sugerencia: quizá `propiedades de tipo función`

2022-02-14 18:01 UTC, Graywolf9 commented on files/es/web/javascript/reference/index.md
> +### Colecciones en clave
Creo que en inglés hace referencia a colecciones con campos clave

2022-02-14 18:11 UTC, Graywolf9 commented on files/es/web/javascript/reference/index.md
> +### Operadores igualitarios
Sugerencia: `Operadores de igualdad`

2022-02-14 19:04 UTC, JuanVqz commented on files/es/web/javascript/reference/index.md
> +### Abstracción de control
@davbrito por que es el correcto?

2022-02-15 02:37 UTC, davbrito approved these changes

2022-02-16 03:28 UTC, Vallejoanderson commented on files/es/web/javascript/reference/index.md
> +### Propiedades de valor
Ok, lo tomo, gracias.

2022-02-16 03:28 UTC, Vallejoanderson commented on files/es/web/javascript/reference/index.md
> +### Propiedades de valor
```suggestion
### Propiedades de tipo valor
```

2022-02-16 03:39 UTC, Vallejoanderson commented on files/es/web/javascript/reference/index.md
> +### Colecciones en clave
```suggestion
### Colecciones con campos clave
```

2022-02-16 03:39 UTC, Vallejoanderson commented on files/es/web/javascript/reference/index.md
> +### Propiedades de funciones
```suggestion
### Propiedades de tipo función
```

2022-02-16 03:41 UTC, Vallejoanderson commented on files/es/web/javascript/reference/index.md
> +### Abstracción de control
Genial, en todos queda resuelto. :partying_face:

2022-02-16 03:42 UTC, Vallejoanderson commented on files/es/web/javascript/reference/index.md
> +### Operadores igualitarios
Muchas gracias!!!

2022-02-16 03:51 UTC, davbrito approved these changes

2022-02-16 14:30 UTC, JuanVqz approved these changes
Se ve bien! :+1:

2022-02-16 14:31 UTC, merged