Content sync and updated to md | Arraybuffer/index [ES]
mdn/translated-content pull request #4128
Opened 2022-02-13 04:35 UTC by Vallejoanderson

Lo subo a pesar del error que me da en local ya que lo revise varias veces y no consigo dar con que esta fallando para que no se muestre la pagina. De antemano, gracias.

2022-02-13 21:42 UTC, davbrito requested changes

2022-02-13 21:42 UTC, davbrito commented on files/es/web/javascript/reference/global_objects/arraybuffer/index.md
> +En este ejemplo, se crea un buffer de 8 bytes con una vista {{jsxref("Int21Array)}} consultando el buffer.
Hola @Vallejoanderson. Aquí está el error. Colocaste mal ésta macro.

```suggestion
En este ejemplo, se crea un buffer de 8 bytes con una vista {{jsxref("Int32Array")}} consultando el buffer.
```

2022-02-13 21:42 UTC, davbrito commented on files/es/web/javascript/reference/global_objects/arraybuffer/index.md
> +Es un arreglo de bytes, frecuentemente llamado de esta forma en otros lenguajes de programación. No se puede manipular directamente el contenido de un `ArrayBuffer`; en su lugar, se crea uno de los [
```suggestion
Es un arreglo de bytes, frecuentemente llamado de esta forma en otros lenguajes de programación. No se puede manipular directamente el contenido de un `ArrayBuffer`; en su lugar, se crea uno de los [objetos de arreglos tipados](/es/docs/Web/JavaScript/Reference/Global_Objects/TypedArray) o un objeto {{jsxref("DataView")}} que representa el buffer en un formato específico, y se usa para leer y escribir el contenido del buffer.
```

2022-02-13 21:42 UTC, davbrito commented on files/es/web/javascript/reference/global_objects/arraybuffer/index.md
> +El objeto **`ArrayBuffer`** se usa para representar un buffer genérico, de datos binarios crudos (raw) con una longitud específica.
Creo que en este caso no sería necesario poner esto. 🤷🏽

```suggestion
El objeto **`ArrayBuffer`** se usa para representar un buffer genérico, de datos binarios crudos con una longitud específica.
```

2022-02-13 21:42 UTC, davbrito commented on files/es/web/javascript/reference/global_objects/arraybuffer/index.md
> +  - : La longitud de solo lectura, en bytes, del `ArrayBuffer`. Está establecida cuando el array es construido y no puede ser cambiada.
```suggestion
  - : Propiedad de sólo lectura con la longitud en bytes del `ArrayBuffer`. Se establece cuando el array es construido y no puede ser cambiada.
```

2022-02-13 23:09 UTC, sergiogval commented on files/es/web/javascript/reference/global_objects/arraybuffer/index.md
> +El objeto **`ArrayBuffer`** se usa para representar un buffer genérico, de datos binarios crudos (raw) con una longitud específica.
Hola, chicos. He estado un poco desegado de la colaboración aquí pero estoy de vuelta. Mi sugerencia aquí es usar la palabra "en plano" más que crudo o raw. no sé qué les parezca, creo que es un lenguaje más técnico y neutral.

2022-02-13 23:31 UTC, sergiogval approved these changes

2022-02-13 23:31 UTC, sergiogval commented on files/es/web/javascript/reference/global_objects/arraybuffer/index.md
> +Es un arreglo de bytes, frecuentemente llamado de esta forma en otros lenguajes de programación. No se puede manipular directamente el contenido de un `ArrayBuffer`; en su lugar, se crea uno de los [
Dado que veo que la única diferencia acá es en la eliminación del espacio que hacía del hipervínculo un bug, estoy deacuerdo con David.

2022-02-13 23:31 UTC, sergiogval commented on files/es/web/javascript/reference/global_objects/arraybuffer/index.md
> +El constructor [`ArrayBuffer`](/es/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/ArrayBuffer) crea un nuevo `ArrayBuffer` de la longitud especificada en bytes. También se puede obtener un
Aquí sólo veo un pequeño detalle en la redacción. Es cuestión de puntiación de sobre una frase. Creo que queda más clara con la sigerencia que hago.
```suggestion
El constructor [`ArrayBuffer`](/es/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/ArrayBuffer) crea un nuevo `ArrayBuffer` de la longitud especificada en bytes. También se puede obtener un `ArrayBuffer` desde datos existentes.Por ejemplo, desde una cadena de caracteres en [Base64](/es/docs/Glossary/Base64) o desde un archivo local.
```

2022-02-13 23:31 UTC, sergiogval commented on files/es/web/javascript/reference/global_objects/arraybuffer/index.md
> +  - : La longitud de solo lectura, en bytes, del `ArrayBuffer`. Está establecida cuando el array es construido y no puede ser cambiada.
en JS la convención es escribir "Array" con la primera letra en mayúscula, lo mismo para los objetos y las clases.

```suggestion
  - : La longitud de solo lectura, en bytes, del `ArrayBuffer`. Está establecida cuando el Array es construido y no puede ser cambiada.
```

2022-02-13 23:31 UTC, sergiogval commented on files/es/web/javascript/reference/global_objects/arraybuffer/index.md
> +  - : Devuelve un nuevo `ArrayBuffer` que contiene una copia de los bytes de este `ArrayBuffer` desde el comienzo (inclusivo) `begin` hasta el fin (exclusivo) `end`. Si `begin` o `end` son negativos,
Sólo es el cambio de "array" a "Array"....

```suggestion
  - : Devuelve un nuevo `ArrayBuffer` que contiene una copia de los bytes de este `ArrayBuffer` desde el comienzo (inclusivo) `begin` hasta el fin (exclusivo) `end`. Si `begin` o `end` son negativos, esto se refiere a un indice desde el final del Array, en lugar del comienzo.
```

2022-02-13 23:33 UTC, davbrito commented
Buenas @sergiogval 
Veo que hiciste commits a algunos de los cambios. Como se ha mencionado en las reuniones se debe dejar que el mismo creador del PR incluya los cambios que se han sugerido.

2022-02-13 23:40 UTC, davbrito commented on files/es/web/javascript/reference/global_objects/arraybuffer/index.md
> +  - : Devuelve un nuevo `ArrayBuffer` que contiene una copia de los bytes de este `ArrayBuffer` desde el comienzo (inclusivo) `begin` hasta el fin (exclusivo) `end`. Si `begin` o `end` son negativos,
En desacuerdo. Allí la palabra array es un sustantivo y no hace referencia al objeto `Array` de JavaScript. Más bien en este caso la traducción debería ser "arreglo".
```suggestion
  - : Devuelve un nuevo `ArrayBuffer` que contiene una copia de los bytes de este `ArrayBuffer` desde el comienzo (inclusivo) `begin` hasta el fin (exclusivo) `end`. Si `begin` o `end` son negativos, esto se refiere a un índice desde el final del arreglo, en lugar del comienzo.
```

2022-02-13 23:47 UTC, sergiogval commented on files/es/web/javascript/reference/global_objects/arraybuffer/index.md
> +  - : La longitud de solo lectura, en bytes, del `ArrayBuffer`. Está establecida cuando el array es construido y no puede ser cambiada.
Array es una palabra reservda de JS. Creí que el acuerdo es no traducir palabras reservadas.

2022-02-13 23:48 UTC, sergiogval commented on files/es/web/javascript/reference/global_objects/arraybuffer/index.md
> +  - : Devuelve un nuevo `ArrayBuffer` que contiene una copia de los bytes de este `ArrayBuffer` desde el comienzo (inclusivo) `begin` hasta el fin (exclusivo) `end`. Si `begin` o `end` son negativos,
¿Es allí o ahí?, insisto, en JS la palabra "Array" es una palabra reservada y según mi entendimiento no se traducen.

2022-02-13 23:50 UTC, davbrito commented on files/es/web/javascript/reference/global_objects/arraybuffer/index.md
> +  - : La longitud de solo lectura, en bytes, del `ArrayBuffer`. Está establecida cuando el array es construido y no puede ser cambiada.
@sergiogval ¿Borraste mi comentario?

2022-02-13 23:55 UTC, davbrito commented on files/es/web/javascript/reference/global_objects/arraybuffer/index.md
> +  - : La longitud de solo lectura, en bytes, del `ArrayBuffer`. Está establecida cuando el array es construido y no puede ser cambiada.
En este caso se está hablando de un _array_ como un concepto conocido en muchos lenguajes de programación para referirse a una secuencia contigua de datos en memoria. No se está hablando de objeto `Array` de JavaScript. No es lo mismo.

2022-02-14 00:45 UTC, sergiogval commented
¿Qué comentario? No sé de qué hablas. Además la censura no es de mi agrado.
Lo que sí hice fue el agradecer tu recordatorio.
 Respecto al usar Array o arreglo es darle congruencia y continuidad con
los textos. Por último te pido que no me difames en un foro abierto. Eso es
no tener ética. Aclara tu error en el mismo lugar que me diamante. No basta
con borrarrlo, es de personas cobardes lo que hiciste. Si señalas
abiertamente de algo a alguien y te das cuenta que no estás en lo correcto,
así mismo debes aclararlo en público...

On Sun, Feb 13, 2022, 17:50 David Brito <
***@***.***> wrote:

> @davbrito commented on this pull request. In
> files/es/web/javascript/reference/global_objects/arraybuffer/index.md: > +
> - : Crea un nuevo objeto `ArrayBuffer`. + +## Propiedades estáticas + +-
> {{jsxre
> *DuckDuckGo* removed 1 tracker →
>
> <https://duckduckgo.com/email/privacy-report/eyJzZW5kZXIiOiJub3RpZmljYXRpb25zQGdpdGh1Yi5jb20iLCJhZGRyZXNzIjoic2VyZ2lvdmFsYWRleiIsImFkZHJlc3NfdG9rZW4iOm51bGwsInRyYWNrZXJzIjpbeyJuYW1lIjpudWxsLCJob3N0bmFtZSI6ImdpdGh1Yi5jb20iLCJlbWFpbF9sZWFrIjpmYWxzZX1dfQ>
>
> ***@***.**** commented on this pull request.
> ------------------------------
>
> In files/es/web/javascript/reference/global_objects/arraybuffer/index.md
> <https://github.com/mdn/translated-content/pull/4128#discussion_r805434938>
> :
>
> > +  - : Crea un nuevo objeto `ArrayBuffer`.
> +
> +## Propiedades estáticas
> +
> +- {{jsxref("ArrayBuffer.@@species", "get ArrayBuffer[@@species]")}}
> +  - : La función constructora que se usa para crear objetos derivados.
> +
> +## Métodos estáticos
> +
> +- {{jsxref("ArrayBuffer.isView", "ArrayBuffer.isView(<var>arg</var>)")}}
> +  - : Devuelve `true` si `arg` es una de las vistas de `ArrayBuffer`, como [objetos de arreglo tipados](/es/docs/Web/JavaScript/Reference/Global_Objects/TypedArray) o un {{jsxref("DataView")}}. Devuelve `false` en caso contrario.
> +
> +## Propiedades de instancias
> +
> +- {{jsxref("ArrayBuffer.prototype.byteLength")}}
> +  - : La longitud de solo lectura, en bytes, del `ArrayBuffer`. Está establecida cuando el array es construido y no puede ser cambiada.
>
> @sergiogval <https://github.com/sergiogval> ¿Borraste mi comentario?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mdn/translated-content/pull/4128#discussion_r805434938>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQCFR7545VSJOKNW5T7F6YDU3A7UBANCNFSM5OIF6BIA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-14 01:59 UTC, Vallejoanderson commented on files/es/web/javascript/reference/global_objects/arraybuffer/index.md
> +El constructor [`ArrayBuffer`](/es/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/ArrayBuffer) crea un nuevo `ArrayBuffer` de la longitud especificada en bytes. También se puede obtener un
Hola, @sergiogval. Gracias por la sugerencia, en este caso la version en ingles lo usan tambien con la coma en vez del punto. Creo que de esa forma seria mas fiel al original.

2022-02-14 01:59 UTC, Vallejoanderson commented on files/es/web/javascript/reference/global_objects/arraybuffer/index.md
> +  - : Devuelve un nuevo `ArrayBuffer` que contiene una copia de los bytes de este `ArrayBuffer` desde el comienzo (inclusivo) `begin` hasta el fin (exclusivo) `end`. Si `begin` o `end` son negativos,
Hola, @sergiogval y @davbrito. Gracias a ambos por interesarse en mi PR. He estado revisando y concuerdo con el punto @davbrito de que es usado como concepto y tambien con el punto de @sergiogval de que es una palabra reservada. Sin embargo, veo (segun mi entendimiento) en que la diferencia radica en si es capitalizada o no `array` o `Array` ya que la palabra reservada esta capitalizada. En el caso de `array` podria usarse sin incoveniente su traduccion que es `arreglo` y en el caso de `Array` que es el objeto no deberia traducirse. En ese sentido, en el texto citado ya que esta sin capitalizar `array` podriamos traducirlo ya que la version [en ingles](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) esta de la misma forma.

2022-02-14 01:59 UTC, Vallejoanderson commented on files/es/web/javascript/reference/global_objects/arraybuffer/index.md
> +El objeto **`ArrayBuffer`** se usa para representar un buffer genérico, de datos binarios crudos (raw) con una longitud específica.
Hola @sergiogval  y @davbrito. Creo que en este caso craw se refiere al estado de los datos `en bruto` mas que el formato del archivo en que se encuentran `en texto plano`.

2022-02-14 02:03 UTC, davbrito commented on files/es/web/javascript/reference/global_objects/arraybuffer/index.md
> +El objeto **`ArrayBuffer`** se usa para representar un buffer genérico, de datos binarios crudos (raw) con una longitud específica.
Correcto. Los datos no son texto plano. Son bytes en bruto. No necesariamente texto.

2022-02-14 05:39 UTC, davbrito commented
Una disculpa, fue error de mi parte pues pensé que el comentario se había borrado de alguna manera. Pero resulta que habías respondido en otro hilo de conversación similar. 

Es por eso que borré mi comentario al notar mi error. En ningún momento fue mi intención acusarte ni señalarte. Sólo hice una pregunta producto de una confusión y un error por mi parte.

2022-02-14 13:35 UTC, JuanVqz commented on files/es/web/javascript/reference/global_objects/arraybuffer/index.md
> +  - : Devuelve un nuevo `ArrayBuffer` que contiene una copia de los bytes de este `ArrayBuffer` desde el comienzo (inclusivo) `begin` hasta el fin (exclusivo) `end`. Si `begin` o `end` son negativos,
Viendo el original, y con la justificación de Vallejo para mi es valida la traducción también.
 
![image](https://user-images.githubusercontent.com/7331511/153873805-1180c00e-1456-4d1f-b722-b9620d7c836a.png)

2022-02-14 16:19 UTC, davbrito approved these changes

2022-02-14 16:25 UTC, merged