Web/API/DOMTokenList/forEach を新規翻訳
mdn/translated-content pull request #415
Opened 2021-04-05 16:21 UTC by mfuji09

2021/02/20 時点の英語版に基づき新規翻訳

2021-04-07 12:15 UTC, potappo requested changes
指摘箇所、英語版の修正が必要かと思いますが、そちらも出来れば PR お願いします。

2021-04-07 12:15 UTC, potappo commented on files/ja/web/api/domtokenlist/foreach/index.html
> +  <dd><code><var>callback</var></code> を実行する際に {{jsxref("this")}} として使用する値です。
英語版も間違っていますが、{{jsxref("this")}} は {{jsxref("Operators/this", "this")}} にしないとリンクされないです。

2021-04-07 14:53 UTC, mfuji09 commented on files/ja/web/api/domtokenlist/foreach/index.html
> +  <dd><code><var>callback</var></code> を実行する際に {{jsxref("this")}} として使用する値です。
あ、本当ですね。
英語版の方も修正しておきます。

2021-04-07 15:10 UTC, mfuji09 commented
修正しましたので、ご確認をお願いします。

2021-04-08 11:30 UTC, potappo approved these changes
修正確認しました。OK です。

2021-04-08 11:31 UTC, merged