4157 patch update media stream audio source node es
mdn/translated-content pull request #4159
Opened 2022-02-15 21:12 UTC by Graywolf9

- [x] Remove the macro `page`
- [x] Update content
- [x] Transform to `md`

2022-02-16 03:57 UTC, davbrito commented
Veo que el diagrama de herencia no se muestra correctamente:
![image](https://user-images.githubusercontent.com/39559632/154193386-409121c9-6432-4c44-8f58-d80dd1cfee5b.png)

¿Es porque la página de `AudioNode` no existe en español o hay otro motivo?

2022-02-16 04:04 UTC, davbrito requested changes
Dejo aquí unas sugerencias.

Estoy viendo también que se eliminó un archivo que no está relacionado (files/es/web/api/notifications_api/using_the_notifications_api/index.html). ¿Hay algún motivo para ello?

2022-02-16 04:04 UTC, davbrito commented on files/es/web/api/mediastreamaudiosourcenode/index.md
> +  - : {{domxref("MediaStream")}} es utilizado al construir este `MediaStreamAudioSourceNode`.
```suggestion
  - : El {{domxref("MediaStream")}} utilizado al construir este `MediaStreamAudioSourceNode`.
```

2022-02-16 04:43 UTC, Vallejoanderson commented
> Veo que el diagrama de herencia no se muestra correctamente: ![image](https://user-images.githubusercontent.com/39559632/154193386-409121c9-6432-4c44-8f58-d80dd1cfee5b.png)
> 
> ¿Es porque la página de `AudioNode` no existe en español o hay otro motivo?

Me parece que si, porque [la macro](https://github.com/mdn/yari/blob/main/kumascript/macros/InheritanceDiagram.ejs#L15) que construye ese diagrama(segun lo que veo porque no entiendo la mayoria) usa siempre la localizacion y no hay un fallback.

2022-02-16 04:50 UTC, Vallejoanderson requested changes

2022-02-16 04:50 UTC, Vallejoanderson commented on files/es/web/api/mediastreamaudiosourcenode/index.md
> +Este medio podría ser de un micrófono (a través de {{domxref("MediaDevices.getUserMedia", "getUserMedia()")}}) o de un compañero remoto en una llamada WebRTC (usando pistas de audio {{domxref("RTCPee
```suggestion
Este medio podría ser un micrófono (a través de {{domxref("MediaDevices.getUserMedia", "getUserMedia()")}}) o un compañero remoto en una llamada WebRTC (usando pistas de audio {{domxref("RTCPeerConnection")}}).
```

2022-02-16 20:55 UTC, Graywolf9 commented on files/es/web/api/mediastreamaudiosourcenode/index.md
> +  - : {{domxref("MediaStream")}} es utilizado al construir este `MediaStreamAudioSourceNode`.
Usualmente una oración en español tiene la capacidad de responder una pregunta, por ejemplo: ¿Cuándo es utilizado el `MediaStream`? entonces la oración queda: (El) `MediaStream` es utilizado...

2022-02-16 21:03 UTC, Graywolf9 commented
Muchas gracias @davbrito @Vallejoanderson 

Parece que lo del diagrama si es por que no existe la página, hago las pruebas.

El archivo eliminado era prueba y no estaba considerado en el commit, pero no sé por que se mezclo y no logré quitarlo de este PR

2022-02-16 21:05 UTC, Vallejoanderson commented
> Muchas gracias @davbrito @Vallejoanderson
> 
> Parece que lo del diagrama si es por que no existe la página, hago las pruebas.
> 
> El archivo eliminado era prueba y no estaba considerado en el commit, pero no sé por que se mezclo y no logré quitarlo de este PR

Sabes si borrando esto se lograria quitar?

![image](https://user-images.githubusercontent.com/48649209/154356878-28b74c93-4df5-4177-8a79-c8ada027bc42.png)

2022-02-16 21:13 UTC, Graywolf9 commented
@Vallejoanderson  me mandaba error, creo que por que el archivo ya no existe

2022-02-16 21:14 UTC, Graywolf9 commented on files/es/web/api/mediastreamaudiosourcenode/index.md
> +Este medio podría ser de un micrófono (a través de {{domxref("MediaDevices.getUserMedia", "getUserMedia()")}}) o de un compañero remoto en una llamada WebRTC (usando pistas de audio {{domxref("RTCPee
Reestructuré la frase para mayor concordancia, gracias por la observación

2022-02-16 22:39 UTC, Graywolf9 commented
> Veo que el diagrama de herencia no se muestra correctamente: ![image](https://user-images.githubusercontent.com/39559632/154193386-409121c9-6432-4c44-8f58-d80dd1cfee5b.png)
> 
> ¿Es porque la página de `AudioNode` no existe en español o hay otro motivo?

Cree la página en #4176

2022-02-20 06:21 UTC, davbrito commented on files/es/web/api/mediastreamaudiosourcenode/index.md
> +  - : {{domxref("MediaStream")}} es utilizado al construir este `MediaStreamAudioSourceNode`.
En este caso lo pongo así porque sería la traducción fiel a lo que dice el original
![image](https://user-images.githubusercontent.com/39559632/154831173-c53cf1e7-f63c-444e-98ba-f3d3c7741f8e.png)

Allí hablan de qué es la propiedad `mediaStream`. No de cuándo se utiliza la interfaz `MediaStream`.

2022-02-21 17:15 UTC, Graywolf9 commented on files/es/web/api/mediastreamaudiosourcenode/index.md
> +  - : {{domxref("MediaStream")}} es utilizado al construir este `MediaStreamAudioSourceNode`.
Tienes razón, lo agrego

2022-02-24 16:56 UTC, Vallejoanderson approved these changes

2022-02-24 16:56 UTC, merged