Content sync and updated to md | global_objects/asyncfunction [ES]
mdn/translated-content pull request #4169
Opened 2022-02-16 18:37 UTC by Vallejoanderson

Fixed #4163

2022-02-16 20:40 UTC, SphinxKnight commented
(failure for AutoCorrect is due to https://github.com/mdn/translated-content/issues/4170 and not due to this PR content, feel free to ignore it or to rebase this branch against a more recent state to avoid this workflow running)

2022-02-16 22:58 UTC, Graywolf9 commented
> (failure for AutoCorrect is due to #4170 and not due to this PR content, feel free to ignore it or to rebase this branch against a more recent state to avoid this workflow running)

Thanks for the comment !

2022-02-16 23:15 UTC, Graywolf9 requested changes

2022-02-16 23:15 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/asyncfunction/index.md
> +  - : Nombres a ser usados por la función como los nombres de los argumentos. Cada uno debe ser una cadena que corresponda a un identificador válido en JavaScript (cualquier [identificador](/es/docs/
```suggestion
  - : Nombres a ser usados por la función como los nombres de los argumentos. Cada uno debe ser una cadena que corresponda a un identificador válido en JavaScript (cualquier [identificador](/es/docs/Glossary/Identifier), [parámetro rest](/es/docs/Web/JavaScript/Reference/Functions/rest_parameters), o [parámetro desestructurado](/es/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment), opcionalmente con un valor por defecto), o una lista de tales cadenas separadas por comas.
```

2022-02-16 23:15 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/asyncfunction/index.md
> +    Así mismo, los parámetros se procesan de la misma manera que las declaraciones de funciones, aceptando espacios y comentarios. Por ejemplo: `"x", "theValue = 42", "[a, b] /* numbers */"` - o `"x,
```suggestion
    Así mismo, los parámetros se procesan de la misma manera que las declaraciones de funciones, aceptando espacios y comentarios. Por ejemplo: `"x", "theValue = 42", "[a, b] /* numbers */"` — o `"x, theValue = 42, [a, b] /* numbers */"`. (`"x, theValue = 42", "[a, b]"` es también correcto, pero muy confuso para leer).
```

2022-02-16 23:15 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/asyncfunction/index.md
> +  - : `functionBody`
```suggestion
- : `functionBody`
```

2022-02-16 23:15 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/asyncfunction/index.md
> +    - : Una cadena que contiene las sentencias de JavaScript que componen la definición de la función.
```suggestion
  - : Una cadena que contiene las sentencias de JavaScript que componen la definición de la función.
```

2022-02-16 23:15 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/asyncfunction/index.md
> +Los objetos {{jsxref("Statements/async_function", "async function")}} creados con el constructor `AsyncFunction` son procesados en el momento que la función es creada. Esto es menos eficiente que dec
```suggestion
Los objetos {{jsxref("Statements/async_function", "async function")}} creados con el constructor `AsyncFunction` son procesados en el momento que la función es creada. Esto es menos eficiente que declarar una función asincrona con un {{jsxref("Statements/async_function", "async function expression")}} y llamarla con eso en tu código , ya que las funciones son procesadas junto al resto del código.
```

2022-02-16 23:15 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/asyncfunction/index.md
> +> closures en sus contextos creados, siempre son creados en el contexto global.
```suggestion
> [_closures_](/es/docs/Web/JavaScript/Closures) en sus contextos creados, siempre son creados en el contexto global.
```

Para tener una referencia y qué es la palabra no traducida

2022-02-16 23:15 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/asyncfunction/index.md
> +  console.log(v); // imprimir 30 después de 4 segundos
```suggestion
  console.log(v); // imprime 30 después de 4 segundos
```

sugerencia

2022-02-17 01:14 UTC, Vallejoanderson commented on files/es/web/javascript/reference/global_objects/asyncfunction/index.md
> +> closures en sus contextos creados, siempre son creados en el contexto global.
Gracias, @Graywolf9

2022-02-21 17:22 UTC, Graywolf9 approved these changes

2022-02-21 17:22 UTC, merged