18. Update weakmap [ES]
mdn/translated-content pull request #4205
Opened 2022-02-19 06:11 UTC by JuanVqz

- [x] Change from HTML to MD
- [x] Sync content

Closes #4180

2022-02-19 15:50 UTC, Vallejoanderson commented
Muchas gracias @JuanVqz. Te cito unas pequenisimas observaciones.

2022-02-19 15:54 UTC, Vallejoanderson commented on files/es/web/javascript/reference/global_objects/weakmap/index.md
> +  - WeakMap
```suggestion
```

2022-02-19 15:54 UTC, Vallejoanderson commented on files/es/web/javascript/reference/global_objects/weakmap/index.md
> +
```suggestion
```

2022-02-19 15:54 UTC, Vallejoanderson commented on files/es/web/javascript/reference/global_objects/weakmap/index.md
> +- [Objetos WeakMap](/en-US/docs/Web/JavaScript/Guide/Keyed_collections#weakmap_object) en guía de [colecciónes con llaves](/en-US/docs/Web/JavaScript/Guide/Keyed_collections)
```suggestion
- [Objetos WeakMap](/es/docs/Web/JavaScript/Guide/Keyed_collections#weakmap_object) en guía de [colecciónes con llaves](/en-US/docs/Web/JavaScript/Guide/Keyed_collections)
```

2022-02-19 15:54 UTC, Vallejoanderson commented on files/es/web/javascript/reference/global_objects/weakmap/index.md
> +[tipo de JavaScript](/en-US/docs/Web/JavaScript/Data_structures#javascript_types) arbitrario,
Creo que esta iria asi:
```suggestion
[Tipos de datos en JavaScript](/es/docs/Web/JavaScript/Data_structures#javascript_types) arbitrario,
```

2022-02-19 17:03 UTC, JuanVqz commented
> Muchas gracias @JuanVqz. Te cito unas pequenisimas observaciones.

Gracias a ti, buenas observaciones :+1:

2022-02-20 05:31 UTC, Vallejoanderson commented on files/es/web/javascript/reference/global_objects/weakmap/index.md
> +- [Objetos WeakMap](/es/docs/Web/JavaScript/Guide/Keyed_collections#weakmap_object) en guía de [colecciónes con llaves](/en-US/docs/Web/JavaScript/Guide/Keyed_collections)
```suggestion
- [Objetos WeakMap](/es/docs/Web/JavaScript/Guide/Keyed_collections#weakmap_object) en guía de [colecciónes con llaves](/es/docs/Web/JavaScript/Guide/Keyed_collections)
```

2022-02-20 05:31 UTC, Vallejoanderson commented on files/es/web/javascript/reference/global_objects/weakmap/index.md
> +objecto sea recolectado como basura. Una vez que se ha recopilado un objeto
```suggestion
[Tipos de datos en JavaScript](/es/docs/Web/JavaScript/Data_structures#javascript_types) arbitrario,
y el cual no crea fuertes referencias a sus llaves.
Es decir, la presencia de un objeto como llave en un `WeakMap` no evita que el
objeto sea recolectado como basura. Una vez que se ha recopilado un objeto
```

2022-02-21 20:23 UTC, Graywolf9 requested changes

2022-02-21 20:23 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/weakmap/index.md
> +[Tipos de datos en JavaScript](/es/docs/Web/JavaScript/Data_structures#javascript_types) arbitrario,
```suggestion
[tipo de dato en JavaScript](/es/docs/Web/JavaScript/Data_structures#javascript_types),
```

2022-02-21 20:23 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/weakmap/index.md
> +### Por qué *Weak*Map?
```suggestion
### ¿Por qué *Weak*Map?
```

2022-02-21 20:23 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/weakmap/index.md
> +La API `map` _podría_ ser implementada en JavaScript con dos arrays (uno para las llaves, otro para los valores) compartidos por los cuatro métodos de la API.
```suggestion
Una API de mapeo _podría_ ser implementada en JavaScript con dos arreglos (uno para las llaves, otro para los valores) compartidos por los cuatro métodos de la API.
```

- No habla de "map" como código
- No habla de los "array" como código

2022-02-21 20:23 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/weakmap/index.md
> +Obtener valores del `map` implicaría iterar a través de todas las llaves hasta encontrar una coincidencia, luego usar el índice de esta coincidencia para recuperar el valor correspondiente del arregl
```suggestion
Establecer elementos en este mapa implicaría colocar una llave y valor al final de cada uno de los arreglos simultáneamente.
Como resultado, los índices de la llave y el valor corresponderían a ambas matrices.
Obtener valores del mapa implicaría iterar a través de todas las llaves hasta encontrar una coincidencia, luego usar el índice de esta coincidencia para recuperar el valor correspondiente del arreglo de valores.
```
No habla de "map" como código

2022-02-21 20:23 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/weakmap/index.md
> +1. El primero es una búsqueda *O(*n*)* (siendo _n_ el número de claves en el mapa). ya que ambas operaciones deben iterar a través de la lista de llaves para encontrar un valor coincidente.
```suggestion
1. El primero es una búsqueda *O(*n*)* (siendo _n_ el número de claves en el mapa) ya que ambas operaciones deben iterar a través de la lista de llaves para encontrar un valor coincidente.
```

2022-02-21 20:23 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/weakmap/index.md
> +  - : Devuelve un valor boleano que afirma si se ha asociado un valor a la `key` en el objeto `WeakMap` o no.
```suggestion
  - : Devuelve un valor booleano que afirma si se ha asociado un valor a la `key` en el objeto `WeakMap` o no.
```

2022-02-21 20:23 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/weakmap/index.md
> +  - : Establece el `value` para la `key` in el objeto `WeakMap`. Devuelve el objeto `WeakMap`.
```suggestion
  - : Establece el `value` para la `key` en el objeto `WeakMap`. Devuelve el objeto `WeakMap`.
```

2022-02-22 05:33 UTC, Vallejoanderson commented on files/es/web/javascript/reference/global_objects/weakmap/index.md
> +2. El segundo inconveniente es un problema de pérdida de memoria por que los arreglos se aseguran que las referencias a cada llave y cada valor se manengan indefinidamente. Estas referencias evitan q
```suggestion
2. El segundo inconveniente es un problema de pérdida de memoria por que los arreglos se aseguran que las referencias a cada llave y cada valor se mantengan indefinidamente. Estas referencias evitan que las llaves se recopilen como basura, incluso si no hay otras referencias al objeto. Esto también evitaría que los valores correspondientes se recopilen como basura.
```

2022-02-22 05:33 UTC, Vallejoanderson commented on files/es/web/javascript/reference/global_objects/weakmap/index.md
> +Por el contrario, en un `WeakMap`, un objecto llave se refiere fuertemente a su contenido siempre que la llave no se recolecte como basura, pero débilmente a partir de ese momento. Como tal, un `Weak
```suggestion
Por el contrario, en un `WeakMap`, un objeto llave se refiere fuertemente a su contenido siempre que la llave no se recolecte como basura, pero débilmente a partir de ese momento. Como tal, un `WeakMap`:
```

2022-02-22 05:33 UTC, Vallejoanderson commented on files/es/web/javascript/reference/global_objects/weakmap/index.md
> +- No evita la recolección de elementos no utilizados, lo que eventialmente elimina las referencias a la llave del objecto.
```suggestion
- No evita la recolección de elementos no utilizados, lo que eventualmente elimina las referencias a la llave del objeto.
```

2022-02-22 05:33 UTC, Vallejoanderson commented on files/es/web/javascript/reference/global_objects/weakmap/index.md
> +## Métodos de instancia
Quizas podria traducirse asi: 
```suggestion
## Métodos de instanciación
```

2022-02-22 05:37 UTC, Vallejoanderson approved these changes

2022-02-22 05:41 UTC, JuanVqz commented
Gracias a todos por sus observaciones, intentare hacerlo mejor la próxima vez

2022-02-22 18:03 UTC, Graywolf9 approved these changes

2022-02-22 18:04 UTC, merged