[WIP] cookie storeと関連ページを翻訳
mdn/translated-content pull request #4207
Opened 2022-02-19 07:58 UTC by mongolyy

cookie storeと関連ページを翻訳しました。
issue: mozilla-japan/translation#579

2022-02-19 07:59 UTC, mongolyy commented
推敲したいので、pull requestのタイトルに一旦WIPをつけています。
推敲が終わったら、WIPを外します。

2022-02-27 03:49 UTC, mfuji09 requested changes

2022-02-27 03:49 UTC, mfuji09 commented on files/ja/web/api/cookiestore/get/index.md
> +{{Domxref("CookieStore")}} インターフェイスの **`get()`** メソッドは、与えられた名前またはオプションオブジェクトを持つ1つの Cookie を返します（下記参照）。このメソッドは渡されたパラメータに最初にマッチする Cookie を返します。
```suggestion
{{Domxref("CookieStore")}} インターフェイスの **`get()`** メソッドは、与えられた名前またはオプションオブジェクトを持つ 1 つの Cookie を返します（下記参照）。このメソッドは渡されたパラメータに最初にマッチする Cookie を返します。
```
数字も前後に空白を入れるようお願いいたします。

2022-03-12 04:48 UTC, mongolyy commented on files/ja/web/api/cookiestore/get/index.md
> +{{Domxref("CookieStore")}} インターフェイスの **`get()`** メソッドは、与えられた名前またはオプションオブジェクトを持つ1つの Cookie を返します（下記参照）。このメソッドは渡されたパラメータに最初にマッチする Cookie を返します。
コメントありがとうございます！
他の行も含めて対応いたしました！  a1d3c6d

2022-03-12 12:17 UTC, mfuji09 approved these changes
OKです。

2022-03-12 12:36 UTC, merged