Undeprecate and update fr Battery Status API
mdn/translated-content pull request #4215
Opened 2022-02-19 20:54 UTC by cw118

Cette PR met à jour les pages documentant l'API Battery Status, qui n'est plus obsolète (voir mdn/content#13129)

2022-02-23 07:38 UTC, SphinxKnight requested changes
Quelques légers ajustements, mais ceci étant écrit : merci beaucoup @cw118 :)

2022-02-23 07:38 UTC, SphinxKnight commented on files/fr/web/api/battery_status_api/index.md
> +- [`BatteryManager`](/fr/docs/Web/API/WorkerNavigator)
```suggestion
- [`BatteryManager`](/fr/docs/Web/API/BatteryManager)
```
Petite coquille :)

2022-02-23 07:38 UTC, SphinxKnight commented on files/fr/web/api/batterymanager/level/index.md
>  ### Code JavaScript
```suggestion
### JavaScript
```
et idem pour "Code HTML" juste avant (GitHub ne me permets pas de suggérer à cet endroit 😞 ) à remplacer en "HTML". Cela fera plus cohérent avec les autres exemples au sein de la doc.

2022-02-23 07:38 UTC, SphinxKnight commented on files/fr/web/api/batterymanager/dischargingtime/index.md
>  ### Code HTML
```suggestion
### HTML
```

2022-02-23 07:38 UTC, SphinxKnight commented on files/fr/web/api/batterymanager/dischargingtime/index.md
>  ### Code JavaScript
```suggestion
### JavaScript
```

2022-02-23 07:38 UTC, SphinxKnight commented on files/fr/web/api/batterymanager/dischargingtime/index.md
> +{{EmbedLiveSample('Exemple', '100%', 30)}}
```suggestion
{{EmbedLiveSample('', '100%', 30)}}
```

2022-02-23 07:38 UTC, SphinxKnight commented on files/fr/web/api/batterymanager/level/index.md
> +{{EmbedLiveSample('Exemple', '100%', 30, '', 'Web/API/BatteryManager/level')}}
```suggestion
{{EmbedLiveSample('', '100%', 30, '', 'Web/API/BatteryManager/level')}}
```

2022-02-23 07:38 UTC, SphinxKnight commented on files/fr/web/api/batterymanager/chargingtime/index.md
>  ### Code JavaScript
```suggestion
### JavaScript
```

2022-02-23 07:38 UTC, SphinxKnight commented on files/fr/web/api/batterymanager/chargingtime/index.md
>  ### Code JavaScript
et idem pour "Code HTML" avant

2022-02-23 07:38 UTC, SphinxKnight commented on files/fr/web/api/batterymanager/chargingtime/index.md
> +{{EmbedLiveSample('Exemple', '100%', 30)}}
```suggestion
{{EmbedLiveSample('', '100%', 30)}}
```

2022-02-23 07:38 UTC, SphinxKnight commented on files/fr/web/api/batterymanager/charging/index.md
>  ### Code HTML
```suggestion
### HTML
```

2022-02-23 07:38 UTC, SphinxKnight commented on files/fr/web/api/batterymanager/charging/index.md
>  ### Code JavaScript
```suggestion
### JavaScript
```

2022-02-23 07:38 UTC, SphinxKnight commented on files/fr/web/api/batterymanager/charging/index.md
> +{{EmbedLiveSample('Exemple', '100%', 30)}}
```suggestion
{{EmbedLiveSample('', '100%', 30)}}
```

2022-02-23 21:33 UTC, cw118 commented on files/fr/web/api/batterymanager/dischargingtime/index.md
> +{{EmbedLiveSample('Exemple', '100%', 30)}}
Merci beaucoup pour la revue ! J'ai une petite question concernant les macros embedlivesample ici — si je passe une chaîne vide rien ne s'affiche :

<details>
<summary>Le code</summary>

````
## Exemple

### HTML

```html
<div id="dischargingTime">(temps de décharge inconnu)</div>
```

### JavaScript

```js
navigator.getBattery().then(battery => {
  const time = battery.dischargingTime;

  document.querySelector('#dischargingTime').textContent = battery.dischargingTime;
});
```

{{EmbedLiveSample('', '100%', 30)}}
````
</details>

![embedlivesample-vide](https://user-images.githubusercontent.com/87150472/155410934-29e64152-47a0-434d-8ad2-c53e6cfe55ee.png)

Par contre, ça marche si j'ajoute un titre (par ex. "Résultat") au-dessus de la macro, alors je ne sais pas trop quoi faire :

<details>
<summary>Le code</summary>

````
## Exemple

### HTML

```html
<div id="dischargingTime">(temps de décharge inconnu)</div>
```

### JavaScript

```js
navigator.getBattery().then(battery => {
  const time = battery.dischargingTime;

  document.querySelector('#dischargingTime').textContent = battery.dischargingTime;
});
```

### Résultat

{{EmbedLiveSample('', '100%', 30)}}
````
</details>

![embedlivesample-titre](https://user-images.githubusercontent.com/87150472/155411113-e3bc2f75-7447-4aca-a0a3-f13b31cf8e09.png)

2022-02-24 08:08 UTC, SphinxKnight commented on files/fr/web/api/batterymanager/dischargingtime/index.md
> +{{EmbedLiveSample('Exemple', '100%', 30)}}
Mea culpa, j'admets ne pas avoir vérifié ce point :/ 

Je suis partagé entre 
* la facilité de rajouter un titre "Résultat" qui va dans le sens d'une cohérence avec d'autres sections où les exemples suivent cette structure (+ d'un point de vue sémantique, ça me semble plus clair au sens où le résultat n'est pas du JavaScript) 
* et l'écueil du `EmbedLiveSample` qui ne fonctionne pas comme attendu et qu'il faudrait corriger sur le fond.

@cw118 je te laisse le choix et te fais confiance là-dessus, le seul réel critère important est d'avoir un exemple fonctionnel en fin de compte.

2022-02-24 22:07 UTC, cw118 commented on files/fr/web/api/batterymanager/dischargingtime/index.md
> +{{EmbedLiveSample('Exemple', '100%', 30)}}
Bon, j'ai opté pour des titres, j'ai tout revérifié et ça semble bien fonctionner

2022-02-25 06:29 UTC, SphinxKnight approved these changes
:100: Let's get this merged

2022-02-25 06:29 UTC, merged