modified index.html to index.markdown
mdn/translated-content pull request #4252
Opened 2022-02-22 17:29 UTC by Agalara

Some errors corrected.

2022-02-22 17:41 UTC, Vallejoanderson commented
Hola! @Agalara, Muchas gracias por tu aportación!

En este caso para que este completamente en formato markdown, puedes seguir las siguientes pautas.

- El formato del archivo en markdown es `.md`


Saludos.

2022-02-22 17:53 UTC, Vallejoanderson commented
Hola! @Agalara   Muchas gracias por tu aportación!

Para que puedas sustituir y actualizar la pagina tenemos en cuenta lo siguiente:

- El formato de la nueva pagina debe ser `.md`
- En este mismo PR puedes agregar tambien el archivo que esta siendo sustituido que es el `.html`, de esa forma no coexistiran los dos archivos(`el .html y el .md`) en el mismo directorio, lo puedes hacer a traves del Git a traves del comando `git rm <archivoaremover>`, por ejemplo:
  - `git rm files/es/learn/css/building_blocks/the_box_model/index.html`.

Mi recomendacion es que revises como esta estructurado todo dentro del archivo `.md` de la version [en ingles](https://raw.githubusercontent.com/mdn/content/main/files/en-us/learn/css/building_blocks/the_box_model/index.md) para que apartir de alli puedas tanto traducir el contenido para que sea fiel a la actual [version en ingles](https://raw.githubusercontent.com/mdn/content/main/files/en-us/learn/css/building_blocks/the_box_model/index.md) como tambien seguir el estilo markdown que ya esta presente en esta ultima.

Recuerda que puedes conversar con nosotros de forma mas directa a traves de la [Matrix](https://chat.mozilla.org/#/room/#mdn-l10n-es:mozilla.org). Estaremos muy felices de poder conversar contigo y que te puedas unir al grupo de colaboradores.

Saludos.

2022-02-22 18:26 UTC, sergiogval requested changes
Hola, gracias por aportar a la comunidad! te dejo mis comentarios sobre tu codigo.

2022-02-22 18:26 UTC, sergiogval commented on files/es/learn/css/building_blocks/the_box_model/index.markdown
> +  - relleno
En este caso es una buena traducción, sin embargo, tengo entendido que ya no se estara utilizando la tabla "Tags" . De momento no tengo la referencia a la mano pero creo que @Vallejoanderson nos puede ayudar con eso. Adicional propongo con el propósito de facilitar las cosas, hago una sugerencia en este comentario, para que no sea necesario que hagas tu cambio manualmente, puede solo presionar el botón `commit suggestion`

Me tom
```suggestion
-
```

2022-02-22 18:26 UTC, sergiogval commented on files/es/learn/css/building_blocks/the_box_model/index.markdown
> +</ol>
En realidad has hecho un gran esfuerzo con esta traducción, 400 lineas de código 💯

- [ ] Tengo una aclaacion que hacer. El archivo tiene el formato markdown o md. Este tipo de documentos son muy parecidos a los .html, con la diferencia de que es mucho mas sencillo dado que se omite el uso de tags, atributos y propiedades, entre otras cosas. En cambio se utiliza texto en plano y algunos caracteres especiales para señalar si el texto es tabla, header, link, etc. Te comparto una referencia en este [link.](https://www.markdownguide.org/basic-syntax/)  y un ejemplo de la version en ingles [aca](https://raw.githubusercontent.com/mdn/content/main/files/en-us/learn/css/building_blocks/the_box_model/index.md)**
Dejo a tu voluntad el hacer el cambio o no, pero creo que seria una buena forma de familiarizarse con el lenguaje. 

- [ ] En caso de no hacer el cambio a markdown, lo ideal es dejar el nombre del archivo como index.html esto con el prop`osito de evitar conflictos. 

Que se haga alguno de los cambios que se encuentran en los checkbox si es necesario para que de mi aprobacion.

2022-02-22 18:43 UTC, Agalara commented on files/es/learn/css/building_blocks/the_box_model/index.markdown
> +</ol>
Muchas gracias por tus respuestas Sergio. 
Como puedes ver estoy aprendiendo y con tus comentarios me ayudas a ello.  Desconocía que los archivos .md son  el formato markdown y literalmente le dí esa extensión al archivo html !
 Seguiré tu consejo de eliminar los tags si ya no se utilizan.  
Y bueno, la traducción estaba ya hecha, simplemente he estado revisando  y haciendo algunos cambios. Es posible que fuese realizada de forma automática?
Seguiré con ello en cuánto me sea posible.
Un saludo a todos.

2022-02-22 23:09 UTC, sergiogval commented on files/es/learn/css/building_blocks/the_box_model/index.markdown
> +</ol>
Por nada, el conocimiento es para compartirse :)

2022-02-23 22:19 UTC, Graywolf9 commented
Hola! @Agalara muchas gracias por tu valioso apoyo 👍 
El compañero Vallejoanderson ya te explicó parte del proceso que hacemos en las traducciones. A partir de eso puedes:
- Si no conoces `md` dejarlo en `html`
- Si no has usado `git` desde terminal o aplicación de escritorio hacer los cambios utilizando la interfaz de GitHub
- Si te has perdido en algún paso de estos, puedes borrar el PR e iniciar de 0
- Si deseas continuar sobre este PR con gusto estamos para ayudarte aquí o en [Matrix](https://chat.mozilla.org/#/room/#mdn-l10n-es:mozilla.org)
- Cualquier comentario no dudes en pedir ayudar, estamos para ayudarte

2022-03-01 10:31 UTC, closed without merging