Use of "tu" vs "usted"
mdn/translated-content pull request #4283
Opened 2022-02-25 19:53 UTC by stripTM

Using "tu" instead of "usted" and minor corrections

2022-02-25 20:38 UTC, sergiogval commented
Creo que necesitamos discutir esto de nuevo. En un canal abierto y sin scripts injectados  dentro de él.  No veo la razón por la cual ocultan la evidencia que comparto en un repositorio PUBLICO y sin avisarme a mi, ni dar justificación alguna.

2022-02-26 05:47 UTC, Vallejoanderson commented on files/es/mdn/contribute/index.md
> +- [Añada o actualice los datos de compatibilidad del navegador en una página de referencia](/es/docs/MDN/Structures/Compatibility_tables) (30 minutos a 1 hora)
De ser tuteo, creo que seria:

```suggestion
- [Añade o actualiza los datos de compatibilidad del navegador en una página de referencia](/es/docs/MDN/Structures/Compatibility_tables) (30 minutos a 1 hora)
```

2022-02-27 00:04 UTC, JuanVqz commented
Hola, @stripTM gracias por tu contribución!
Para poder usar el fallback, ¿Podrías corregir los "enlaces rotos" que el **bot** nos sugiere corregir, por favor?

2022-02-27 12:24 UTC, sergiogval commented
> Creo que necesitamos discutir esto de nuevo. En un canal abierto y sin scripts injectados  dentro de él.  No veo la razón por la cual ocultan la evidencia que comparto en un repositorio PUBLICO y sin avisarme a mi, ni dar justificación alguna.
> 
> ===================== 
> 
> This is the second time that you minimized my comment. Let me explain to you that in a collaborative environment is a bad practice such action. I really hope this won't happen again. 
> 
> Regarding the code, Fer, I am surprised that with more than 10 year if experience, you didn't noticed that there are tags in a md file. Guys this is serious. You are touching the main branch. This will go straight into production. We need to follow a gitflow and use a bran diferent from main. 
> 
> As last comment, by now we have two security  incidents  please control yourselves. Don't merge anything that has been fully review. 1 error of these may brake the complete page. Do you want that in your CV?

Stop minimizing my comments. There is no room for censorship in this space

2022-02-27 17:24 UTC, sergiogval commented
@stripTM @JuanVqz @SphinxKnight @Vallejoanderson @Graywolf9 .

2022-02-27 17:25 UTC, sergiogval commented
> @stripTM @JuanVqz @SphinxKnight @Vallejoanderson @Graywolf9 .
> 

These fools

2022-02-27 17:43 UTC, JuanVqz commented
> > Creo que necesitamos discutir esto de nuevo. En un canal abierto y sin scripts injectados  dentro de él.  No veo la razón por la cual ocultan la evidencia que comparto en un repositorio PUBLICO y sin avisarme a mi, ni dar justificación alguna.
> > =====================
> > This is the second time that you minimized my comment. Let me explain to you that in a collaborative environment is a bad practice such action. I really hope this won't happen again.
> > Regarding the code, Fer, I am surprised that with more than 10 year if experience, you didn't noticed that there are tags in a md file. Guys this is serious. You are touching the main branch. This will go straight into production. We need to follow a gitflow and use a bran diferent from main.
> > As last comment, by now we have two security  incidents  please control yourselves. Don't merge anything that has been fully review. 1 error of these may brake the complete page. Do you want that in your CV?
> 
> Stop minimizing my comments. There is no room for censorship in this space

Hola @sergiogval, ya intentamos tener la llamada contigo fue el viernes pasado por zoom, pero no llegaste, y como lo mencione antes https://github.com/mdn/translated-content/issues/4282#issuecomment-1053625448 no es el lugar para reportar. En el chat de la comunidad en español se te han proporcionado los enlaces necesarios para que lo hagas directamente con las dependencias encargadas. saludos.

2022-02-27 18:07 UTC, sergiogval commented
@stripTM @JuanVqz @SphinxKnight @Vallejoanderson @Graywolf9 .
    ![Screenshot_20220227-120409_GitHub.jpg](https://user-images.githubusercontent.com/67393791/155894205-7480060c-cfd4-46cd-a256-422e3283b1c9.jpg)
What for? Been even more hacked? Cut the bullshit.

2022-02-27 18:08 UTC, sergiogval commented
Pues mira yo reports donde se me de la gana. Al final tu y tus complies son los delincuentes. Pinche Marrano, casi me destrrozas la vida.

2022-02-27 18:14 UTC, sergiogval commented
Tengo tu nombre y el de tus amiguis en mi consola, grabado, tengo la foto delclink que me pasaste a la matrix y tengo un video donde se ven todos tus conocimientos técnico. Creme, no la vas a librar.

2022-02-28 03:07 UTC, sergiogval commented on files/es/mdn/contribute/index.md
> +> **Nota:** Si encontraste algo que es incorrecto en MDN pero no estás seguro de cómo solucionarlo, puede reportarlo llenando un [informe de error de documentación](https://github.com/mdn/content/iss
No creen que es redundante la parte de como estructurar el titulo del issue? Creo que viene la explicación en  el template del issue. Se los dejo al gusto.

2022-02-28 12:44 UTC, stripTM commented
> Hola, @stripTM gracias por tu contribución! Para poder usar el fallback, ¿Podrías corregir los "enlaces rotos" que el **bot** nos sugiere corregir, por favor?

@JuanVqz Pues creo que ya está todo corregido.

2022-02-28 14:13 UTC, sergiogval requested changes
LGTM, only please do me a favor and eliminate the comments that aren't adding value to this PR.

2022-02-28 14:33 UTC, davbrito approved these changes

2022-02-28 14:36 UTC, merged