Web/API/Request/credentialsの翻訳を更新
mdn/translated-content pull request #4301
Opened 2022-02-27 17:59 UTC by unarist

2022-02-28 01:22 UTC, mfuji09 requested changes
2点の修正をお願いします。

2022-02-28 02:27 UTC, sergiogval commented on files/ja/web/api/request/credentials/index.md
> +<h2 id="Syntax">構文</h2>
もちろん
スペイン語版がないようですので、この機会に貢献していきます。文章がうまく書かれていることを願っています。

2022-02-28 02:30 UTC, sergiogval commented on files/ja/web/api/request/credentials/index.md
> +<h2 id="Syntax">構文</h2>
```suggestion
## 構文
```

2022-02-28 02:52 UTC, sergiogval requested changes
I just get rid of a couple of tags. Thanks for the hint, very interesting topic.

2022-02-28 02:52 UTC, sergiogval commented on files/ja/web/api/request/credentials/index.md
> +<h3 id="Value">値</h3>
```suggestion
### 値
```

2022-02-28 02:52 UTC, sergiogval commented on files/ja/web/api/request/credentials/index.md
> +<h2 id="Syntax">構文</h2>
```suggestion
## 構文
```

2022-02-28 02:52 UTC, sergiogval commented on files/ja/web/api/request/credentials/index.md
> +<h2 id="Browser compatibility">ブラウザー実装状況</h2>
```suggestion

```

2022-02-28 02:52 UTC, sergiogval commented on files/ja/web/api/request/credentials/index.md
> +<h2 id="Specifications">仕様</h2>
```suggestion
## 仕様
```

2022-02-28 02:52 UTC, sergiogval commented on files/ja/web/api/request/credentials/index.md
> +{{Compat}}
```suggestion
## {ブラウザー実装状況{{Compat}}}
```

2022-02-28 02:52 UTC, sergiogval commented on files/ja/web/api/request/credentials/index.md
> +<h2 id="See also">関連情報</h2>
```suggestion
## 関連情報
```

2022-02-28 02:52 UTC, sergiogval commented on files/ja/web/api/request/credentials/index.md
> +  - request
タグセクションは廃止されると言われていましたが、何か知っていますか？

2022-03-02 10:07 UTC, unarist commented on files/ja/web/api/request/credentials/index.md
> +<h2 id="Syntax">構文</h2>
https://github.com/mdn/translated-content/pull/4301/commits/7fac363a403112f6a8cf7311d85e44565690a772 で修正しました

2022-03-02 10:07 UTC, unarist commented on files/ja/web/api/request/credentials/index.md
> +次のスニペットは、{{domxref("Request.Request()")}} コンストラクタを使って（スクリプトと同じディレクトリーにある画像ファイルのために）新しいリクエストを生成してから、リクエストの credentials を変数に保存しています：
https://github.com/mdn/translated-content/pull/4301/commits/7fac363a403112f6a8cf7311d85e44565690a772 で修正しました

2022-03-02 10:13 UTC, unarist commented on files/ja/web/api/request/credentials/index.md
> +  - request
わたしは特に知らないですね…。

2022-03-02 14:35 UTC, mfuji09 approved these changes
OKです。

2022-03-02 14:36 UTC, merged