Translate and rename index.html to index.md
mdn/translated-content pull request #4321
Opened 2022-03-01 03:23 UTC by Jalkhov

Closes #4319

2022-03-01 03:36 UTC, davbrito requested changes
¡Muchas gracias pro tu contribución @Jalkhov! Excelente la traducción. Sólo te dejo dos comentarios con respecto a las traducciones acordadas por el equipo de MDN en Español para ciertos títulos. (Como puedes observar en esta discusión https://github.com/mdn/translated-content/discussions/4029)

2022-03-01 03:36 UTC, davbrito commented on files/es/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
> +## Compatibilidad con los navegadores
```suggestion
## Compatibilidad con navegadores
```

2022-03-01 03:36 UTC, davbrito commented on files/es/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
> +## Ver también
```suggestion
## Véase también
```

2022-03-01 04:01 UTC, Jalkhov commented on files/es/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
> +## Ver también
Listo

2022-03-01 04:01 UTC, Jalkhov commented on files/es/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
> +## Compatibilidad con los navegadores
Listo

2022-03-01 04:07 UTC, davbrito approved these changes

2022-03-02 13:51 UTC, JuanVqz approved these changes
@Jalkhov muy buena, gracias por contribuir! :rocket:

2022-03-02 13:52 UTC, merged