convert text-overflow zh-cn to md
mdn/translated-content pull request #4344
Opened 2022-03-01 23:27 UTC by fish-404

- convert text-overflow zh-cn index.html to index.md
- sync zh-cn content with en-us content
- fix https://github.com/mdn/translated-content/issues/4011
- This pull request is redo #4078 to ensure content of the first commit were mv .html to .md

2022-03-15 13:14 UTC, irvin requested changes
- 請把最後兩個 commit 合併，或者先把前兩個 commit 的部分做成一個獨立的 PR，後兩個再 merge 之後再另外發。
- 請修 conflict

2022-04-04 05:05 UTC, yin1999 requested changes

2022-04-04 05:05 UTC, yin1999 commented on files/zh-cn/web/css/text-overflow/index.md
> +{{EmbedLiveSample('One-value_syntax', 600, 320)}}
EmbedLiveSample 引用的 ID 不正确：

```markdown
{{EmbedLiveSample('单值语法', 600, 320)}}
```

2022-04-04 05:05 UTC, yin1999 commented on files/zh-cn/web/css/text-overflow/index.md
> +{{EmbedLiveSample('Two-value_syntax', 600, 430)}}
EmbedLiveSample 引用的 ID 不正确：

```markdown
{{EmbedLiveSample('双值语法', 600, 320)}}
```

2022-04-04 05:05 UTC, yin1999 commented on files/zh-cn/web/css/text-overflow/index.md
> +**`text-overflow`** <a href="https://developer.mozilla.org/zh-CN/docs/Web/CSS">CSS</a> 属性确定如何向用户发出未显示的溢出内容信号。它可以被剪切，显示一个省略号（'...'）或显示一个自定义字符串。
考虑更新链接格式为 markdown 格式，并去除域名部分：

```markdown
[CSS](/zh-CN/docs/Web/CSS)
```

2022-04-04 05:05 UTC, yin1999 commented on files/zh-cn/web/css/text-overflow/index.md
> +```html
不同的块级元素之前请保留空行（以下仅是举例，文中其它部分请一并修改）：

```markdown
## Formal definition

{{CSSInfo}}

## Formal syntax

{{csssyntax}}

## 示例

### 单值语法

这个示例呈现了将不同的 `text-overflow` 值应用到一个段落上面，在从左到右的文本和从右到左的文本上的效果。

#### HTML

```html
```

2022-06-15 07:56 UTC, yin1999 commented
Closing for done this in #6184.

2022-06-15 07:56 UTC, closed without merging