Migrate CompatibilityTable to Compat macro (es)
mdn/translated-content pull request #4355
Opened 2022-03-02 12:01 UTC by YujiSoftware

# Related Issue

fix #354

# Work

I applied the issue-described site compatibility table migration script to the Compat macro for the documentation.
This script does the following:

* Delete {{CompatibilityTable}} to the line before the next h2 tag in each file
* Added the {{Compat()}} macro described in the English version (of the same path)

2022-03-02 14:43 UTC, cw118 commented
@YujiSoftware Thanks so much for making these PRs for the locales that need it :)

**Just a note to the l10n-es review team:** many of the Compat macros here could/should have no argument and instead have a `browser-compat` line in the YAML front-matter, but either way will work just fine. I'll leave it to you all to decide how to proceed with this PR and whether you'd like to move to front-matter all in one or in another pull request.

2022-03-02 17:16 UTC, davbrito requested changes

2022-03-02 17:16 UTC, davbrito commented on files/es/games/techniques/webrtc_data_channels/index.html
Here the script didn't add the replacement with the `{{Compat}}` macro. Is this intended?

2022-03-02 17:44 UTC, JuanVqz approved these changes
it's hard to review all the pages but until I can see it's working as expected and doing what it says that will do

2022-03-02 17:59 UTC, davbrito commented on files/es/games/techniques/webrtc_data_channels/index.html
Cool. Thanks @cw118!

2022-03-02 18:02 UTC, davbrito approved these changes

2022-03-03 13:36 UTC, JuanVqz commented
@YujiSoftware thank you for your contribution we appreciate it :100:

2022-03-03 13:36 UTC, merged