Adding Translated CSS Reference File: -webkit-scrollbar
mdn/translated-content pull request #4388
Opened 2022-03-03 23:15 UTC by BenjamimCS

Translated CSS Reference about `-webkit-scrollbar` pseudo-element

2022-04-09 00:54 UTC, nathipg requested changes
Desculpa a demora para revisar 🙇🏻‍♀️ 
Seria possível você passar essa página para o padrão com a extensão .md?
Olhando a versão em inglês, acredito que não demoraria muito para fazer isso, mas entendo caso você não possa.
Caso você queira manter a .html, vou deixar a página reservada para ser atualizada no futuro, sem problemas.

2022-04-09 01:51 UTC, BenjamimCS commented
> Desculpa a demora para revisar 🙇🏻‍♀️ Seria possível você passar essa página para o padrão com a extensão .md? Olhando a versão em inglês, acredito que não demoraria muito para fazer isso, mas entendo caso você não possa. Caso você queira manter a .html, vou deixar a página reservada para ser atualizada no futuro, sem problemas.

Ok, farei brevemente.

2022-05-14 22:42 UTC, BenjamimCS commented
Olá.
Não sei se foi notificado mas já fiz as mudanças necessárias para `.md`

2022-06-16 17:49 UTC, nathipg commented
> Olá. Não sei se foi notificado mas já fiz as mudanças necessárias para `.md`

Opa, desculpa, só recebi a notificação essa semana :/
Vou fazer a revisão no domingo sem falta, obrigada!

2022-06-19 13:32 UTC, nathipg commented on files/pt-br/web/css/_doublecolon_-webkit-scrollbar/index.md
> +> **Nota:** `::-webkit-scrollbar` está disponível somente em navegadores baseados em [Blink](https://www.chromium.org/blink) - e [WebKit](https://webkit.org) - (Chrome, Edge, Opera, Safari, todos os
```suggestion
> **Nota:** `::-webkit-scrollbar` está disponível somente em navegadores baseados em [Blink](https://www.chromium.org/blink) - e [WebKit](https://webkit.org) - (Chrome, Edge, Opera, Safari, todos os navegadores para iOS, e [outros](https://en.wikipedia.org/wiki/List_of_web_browsers#WebKit-based)). Um método padronizado para estilização de barras de rolagem está disponível com {{cssxref("scrollbar-color")}} e {{cssxref("scrollbar-width")}}.
```

2022-06-19 13:34 UTC, nathipg commented on files/pt-br/web/css/_doublecolon_-webkit-scrollbar/index.md
> +### CSS</h3>
```suggestion
### CSS
```

2022-06-19 13:48 UTC, nathipg requested changes
A alteração pra nova extenção ficou muito boa!
Segue alguns pequenos ajustes, muito obrigada pela sua ajuda 😁

2022-06-19 13:48 UTC, nathipg commented on files/pt-br/web/css/_doublecolon_-webkit-scrollbar/index.md
> +  * (won't be visible otherwise if width/height is specified) */
```suggestion
/* Demonstração de uma barra de rolagem personalizada
  * (não será visível ao menos que a largura/altura seja especificada) */
```

2022-06-19 13:48 UTC, nathipg commented on files/pt-br/web/css/_doublecolon_-webkit-scrollbar/index.md
> +  background-color: #aaa; /* or add it to the track */
```suggestion
  background-color: #aaa; /* ou que isso seja adicionado ao "caminho" da barra */
```

2022-06-19 13:48 UTC, nathipg commented on files/pt-br/web/css/_doublecolon_-webkit-scrollbar/index.md
> +/* Add a thumb */
```suggestion
/* Adiciona a barra arrastável */
```

2022-06-19 13:48 UTC, nathipg commented on files/pt-br/web/css/_doublecolon_-webkit-scrollbar/index.md
> +Thisisaveeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeerylongword
```suggestion
Estaéumapalavramuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuitolonga
Thisisaveeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeerylongword
```

2022-06-19 13:48 UTC, nathipg commented on files/pt-br/web/css/_doublecolon_-webkit-scrollbar/index.md
> +Who thought scrollbars could be made weeeeird?
```suggestion
Estaéumapalavramuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuitolonga<br>
E bem alta<br>
com uma barra de rolagem estranha.<br>
Quem diria que barras de rolagem poderiam ser estraaaanhas?
```

2022-06-19 13:48 UTC, nathipg commented on files/pt-br/web/css/_doublecolon_-webkit-scrollbar/index.md
> +- WebKit blog em [Styling Scrollbars](https://webkit.org/blog/363/styling-scrollbars/)
```suggestion
- WebKit blog em [Estilizando barras de rolagem](https://webkit.org/blog/363/styling-scrollbars/)
```

2022-06-19 13:48 UTC, nathipg commented on files/pt-br/web/css/_doublecolon_-webkit-scrollbar/index.md
> +- [WebKit test](https://trac.webkit.org/export/41842/trunk/LayoutTests/scrollbars/overflow-scrollbar-combinations.html) para os estilos da barra de rolagem mencionados acima
```suggestion
- [Testando WebKit](https://trac.webkit.org/export/41842/trunk/LayoutTests/scrollbars/overflow-scrollbar-combinations.html) para os estilos da barra de rolagem mencionados acima
```

2022-06-19 17:08 UTC, BenjamimCS commented
> A alteração pra nova extenção ficou muito boa!
> Segue alguns pequenos ajustes, muito obrigada pela sua ajuda 😁 

Eu que agradeço.  Obrigado. 😄

2022-06-21 23:44 UTC, nathipg requested changes
Obrigada pelo retorno rápido!
Alguns dos apontamentos não foram aceitos nem comentados, poderia dar uma olhada neles, por favor?

2022-07-18 01:44 UTC, nathipg approved these changes
Muito obrigada pela contribuição!
Ficou excelente, obrigada por todo o seu tempo 😁

2022-07-18 01:46 UTC, merged