user_input_methods のワークフローの日本語訳を追加
mdn/translated-content pull request #4416
Opened 2022-03-05 08:55 UTC by att55

### PR 内容

web/guide/user_input_methods のワークフローが日本語訳されていなかったので訳しました。

2022-03-08 14:43 UTC, mfuji09 requested changes
1点だけ、修正をお願いします。

2022-03-08 14:43 UTC, mfuji09 commented on files/ja/web/guide/user_input_methods/index.html
> +<p>最初に、マウス、キーボード、指でのタッチなどから、アプリケーションで対象としたい入力の仕組みをどれにするかを決める必要があります。入力の仕組みを決めたのであれば、ウェブプラットフォームや JavaScript ライブラリによって提供されているツールを使い、制御することができます。</p>
```suggestion
<p>最初に、マウス、キーボード、指でのタッチなどから、アプリケーションで対象としたい入力の仕組みをどれにするかを決める必要があります。入力の仕組みを決めたのであれば、ウェブプラットフォームや JavaScript ライブラリーによって提供されているツールを使い、制御することができます。</p>
```
ライブラリ→ライブラリーの修正をお願いします。

2022-03-09 08:44 UTC, att55 commented on files/ja/web/guide/user_input_methods/index.html
> +<p>最初に、マウス、キーボード、指でのタッチなどから、アプリケーションで対象としたい入力の仕組みをどれにするかを決める必要があります。入力の仕組みを決めたのであれば、ウェブプラットフォームや JavaScript ライブラリによって提供されているツールを使い、制御することができます。</p>
@mfuji09 レビューありがとうございます！こちら取り込みました！

2022-03-09 13:13 UTC, mfuji09 approved these changes
OKです。

2022-03-09 13:13 UTC, merged