新規翻訳：PlayCanvasでベーシックデモをビルドする
mdn/translated-content pull request #4474
Opened 2022-03-08 05:37 UTC by BallaBalloBella

「PlayCanvasでベーシックデモをビルドする」を翻訳しました。

2022-03-08 14:39 UTC, mfuji09 requested changes
いくつかの修正をお願いします。

2022-03-08 14:39 UTC, mfuji09 commented on files/ja/games/techniques/3d_on_the_web/building_up_a_basic_demo_with_playcanvas/index.md
> +> **備考:** さらに事例をご覧になる場合は[特集されているデモ](https://playcanvas.com/explore)も確認してください。
\**Note:** はキーワードになっているので、翻訳せずにそのままにしてください（動作が変わってしまいます）。

2022-03-08 14:39 UTC, mfuji09 commented on files/ja/games/techniques/3d_on_the_web/building_up_a_basic_demo_with_playcanvas/index.md
> +title: PlayCanvasでベーシックデモをビルドする
```suggestion
title: PlayCanvas でベーシックデモをビルドする
```
タイトルも、英字と日本語の間に空白を空けてください。

2022-03-08 14:39 UTC, mfuji09 commented on files/ja/games/techniques/3d_on_the_web/building_up_a_basic_demo_with_playcanvas/index.md
> +をビルドするを参照ください。
「をビルドする」の部分が重複しています。

2022-03-09 09:19 UTC, BallaBalloBella commented on files/ja/games/techniques/3d_on_the_web/building_up_a_basic_demo_with_playcanvas/index.md
> +> **備考:** さらに事例をご覧になる場合は[特集されているデモ](https://playcanvas.com/explore)も確認してください。
修正しました

2022-03-09 09:20 UTC, BallaBalloBella commented on files/ja/games/techniques/3d_on_the_web/building_up_a_basic_demo_with_playcanvas/index.md
> +title: PlayCanvasでベーシックデモをビルドする
修正しました

2022-03-09 09:20 UTC, BallaBalloBella commented on files/ja/games/techniques/3d_on_the_web/building_up_a_basic_demo_with_playcanvas/index.md
> +をビルドするを参照ください。
修正しました

2022-03-09 09:20 UTC, BallaBalloBella commented on files/ja/games/techniques/3d_on_the_web/building_up_a_basic_demo_with_playcanvas/index.md
> +> **備考:** さらに事例をご覧になる場合は[特集されているデモ](https://playcanvas.com/explore)も確認してください。
ありがとうございます

2022-03-09 09:21 UTC, BallaBalloBella commented on files/ja/games/techniques/3d_on_the_web/building_up_a_basic_demo_with_playcanvas/index.md
> +title: PlayCanvasでベーシックデモをビルドする
ありがとうございます

2022-03-09 09:21 UTC, BallaBalloBella commented on files/ja/games/techniques/3d_on_the_web/building_up_a_basic_demo_with_playcanvas/index.md
> +をビルドするを参照ください。
ありがとうございます

2022-03-09 13:12 UTC, mfuji09 approved these changes
OKです。

2022-03-10 14:19 UTC, merged