16. /es/docs/web/api/geolocation_api - [es]
mdn/translated-content pull request #4509
Opened 2022-03-10 05:43 UTC by JuanVqz

Closes #3980

- [x] Change format from HTML to MD
- [x] Sync content

2022-03-11 02:49 UTC, davbrito requested changes

2022-03-11 02:49 UTC, davbrito commented on files/es/web/api/geolocation_api/index.md
> +title: Uso de geolocalización
```suggestion
title: API de geolocalización
```

2022-03-11 02:49 UTC, davbrito commented on files/es/web/api/geolocation_api/index.md
> +Las `WebExtensions` que deseen utilizar el objeto `Geolocalización` deben agregar el permiso `"geolocation"` a su manifiesto.
```suggestion
Las `WebExtensions` que deseen utilizar el objeto `Geolocation` deben agregar el permiso `"geolocation"` a su manifiesto.
```

2022-03-11 02:49 UTC, davbrito commented on files/es/web/api/geolocation_api/index.md
> +- Una devolución de llamada exitosa obligatoria: si la recuperación de la ubicación es exitosa, la devolución de llamada se ejecuta con un objeto {{domxref("GeolocationPosition")}} como su único pará
```suggestion
- Una función obligatoria que será llamada en caso de éxito: si la recuperación de la ubicación es exitosa, la función se ejecuta con un objeto {{domxref("GeolocationPosition")}} como su único parámetro, proporcionando acceso a los datos de ubicación.
```

2022-03-11 02:49 UTC, davbrito commented on files/es/web/api/geolocation_api/index.md
> +- Una devolución de llamada de error opcional: si la recuperación de la ubicación no tiene éxito, la devolución de llamada se ejecuta con un objeto {{domxref("GeolocationPositionError")}} como su úni
```suggestion
- Una función opcional que será llamada en caso de error: si la recuperación de la ubicación no tiene éxito, la función se ejecuta con un objeto {{domxref("GeolocationPositionError")}} como su único parámetro, proporcionando información de acceso sobre lo que salió mal.
```

2022-03-11 02:49 UTC, davbrito commented on files/es/web/api/geolocation_api/index.md
> +Para obtener más información sobre el uso de la geolocalización, lea [uso de la API de geolocalización](/es/docs/Web/API/Geolocation_API/Using_the_Geolocation_API)
```suggestion
Para obtener más información sobre el uso de la geolocalización, lea [Uso de la API de geolocalización](/es/docs/Web/API/Geolocation_API/Using_the_Geolocation_API)
```

2022-03-11 02:49 UTC, davbrito commented on files/es/web/api/geolocation_api/index.md
> +  - : Representa la posición de un usuario. Una instancia de `GeolocationPosition` es devuelta por una llamada exitosa a uno de los métodos contenidos dentro de {{domxref("Geolocation")}}, dentro de
```suggestion
  - : Representa la posición de un usuario. Una instancia de `GeolocationPosition` es devuelta por una llamada exitosa a uno de los métodos contenidos dentro de {{domxref("Geolocation")}}, dentro de una devolución de llamada exitosa, y contiene una marca de tiempo más una instancia de objeto {{domxref("GeolocationCoordinates")}}.
```

2022-03-11 02:49 UTC, davbrito commented on files/es/web/api/geolocation_api/index.md
> +Dado que Google suele proporcionar la ubicación basada en Wi-Fi, es posible que la API Vanilla Geolocalización no esté disponible en China. Puede utilizar proveedores externos locales como [Baidu](ht
```suggestion
Dado que Google suele proporcionar la ubicación basada en Wi-Fi, es posible que la API _vanilla_ de Geolocalización no esté disponible en China. Puede utilizar proveedores externos locales como [Baidu](https://lbsyun.baidu.com/index.php?title=jspopular/guide/geolocation), [Autonavi](https://lbs.amap.com/api/javascript-api/guide/services/geolocation#geolocation), o [Tencent](https://lbs.qq.com/tool/component-geolocation.html). Estos servicios utilizan la dirección IP del usuario y/o una aplicación local para proporcionar un mejor posicionamiento.
```

2022-03-11 02:53 UTC, davbrito requested changes

2022-03-11 02:53 UTC, davbrito commented on files/es/web/api/geolocation_api/index.md
> +  - : El punto de entrada a la API. Devuelve una instancia de objeto {{domxref("Geolocalización")}}, desde la cual se puede acceder a todas las demás funciones.
```suggestion
  - : El punto de entrada a la API. Devuelve una instancia de objeto {{domxref("Geolocation")}}, desde la cual se puede acceder a todas las demás funciones.
```

2022-03-13 23:02 UTC, JuanVqz commented
Hola @davbrito, ya corregí las sugerencias, por favor puedes dar continuidad cuando tengas oportunidad, saludos!

2022-03-20 01:06 UTC, davbrito approved these changes

2022-03-20 01:07 UTC, merged