Update index.md
mdn/translated-content pull request #4519
Opened 2022-03-10 11:10 UTC by StephaneRegnie

Correction coquille dans Invoquer des fonctions

2022-03-10 21:27 UTC, cw118 requested changes
Merci déjà @StephaneRegnie !

Pour ce qui précède le deux-points, on préfère utiliser l'entité HTML `&nbsp;` (une espace insécable). J'ai apposé une suggestion avec quelques autres corrections pour que ce soit plus facile à intégrer :)

2022-03-11 08:56 UTC, StephaneRegnie commented on files/fr/learn/javascript/building_blocks/functions/index.md
> +Vous êtes probablement au clair avec cela maintenant, mais juste au cas où... pour utiliser une fonction après qu'elle ait été définie, vous devez la lancer - ou l'invoquer. Pour ce faire, vous devez
@cw118 OK parfait, merci ;)

2022-03-11 12:49 UTC, cw118 commented on files/fr/learn/javascript/building_blocks/functions/index.md
> +Vous êtes probablement au clair avec cela maintenant, mais juste au cas où... pour utiliser une fonction après qu'elle ait été définie, vous devez la lancer - ou l'invoquer. Pour ce faire, vous devez
👍 quand vous aurez le temps, il suffit de cliquer sur le bouton "Commit suggestion" pour accepter/pousser un commit sur ces changements (mais rien de pressé :) )

2022-03-14 15:51 UTC, cw118 approved these changes
👍

2022-03-14 15:51 UTC, merged