user_input_methods の指でのタッチの日本語訳を追加
mdn/translated-content pull request #4538
Opened 2022-03-11 09:31 UTC by att55

### PR 内容

user_input_methods の指でのタッチの日本語訳を追加しました。

2022-03-17 04:35 UTC, mfuji09 requested changes
以下の点の修正をお願いします。

2022-03-17 04:35 UTC, mfuji09 commented on files/ja/web/guide/user_input_methods/index.html
> +<p>タッチスクリーンデバイスにインストールされることを目的としている Web アプリを開発している時、ディスプレイ解像度とユーザー入力に関して異なる性能を考慮することは良いプラクティスです。<a href="/ja/docs/Web/API/Touch_events">タッチイベント</a>は、タッチスクリーンデバイス上のインタラクションな要素と一般的なインタラクションジェスチャーを実装するの
Webは「ウェブ」とカタカナ表記してください。

2022-03-17 04:35 UTC, mfuji09 commented on files/ja/web/guide/user_input_methods/index.html
> + <dd>この例は一度に複数のタッチ箇所を追跡しており、ユーザーは <code>{{htmlelement("canvas")}}</code> の中で一本以上の指で同時に描くことができます。タッチイベントをサポートしているブラウザでのみ動きます。</dd>
「ブラウザ」は「ブラウザー」と表記してください。

2022-03-17 04:35 UTC, mfuji09 commented on files/ja/web/guide/user_input_methods/index.html
> +<p>タッチイベントを使いたいのであれば、イベントリスナーの追加とイベントが発火された時に呼び出されるハンドラー関数を指定する必要があります。</p>
「イベントリスナーの追加」と「イベントが発火～ハンドラー関数を指定する」は同じことを言いなおしているだけなので、「と」で結ぶと意味が分かりにくくなります。下記のようにした方がいいと思います。
```suggestion
<p>タッチイベントを使いたいのであれば、イベントリスナーを追加して、イベントが発火された時に呼び出されるハンドラー関数を指定する必要があります。</p>
```

2022-03-18 09:21 UTC, att55 commented on files/ja/web/guide/user_input_methods/index.html
> +<p>タッチイベントを使いたいのであれば、イベントリスナーの追加とイベントが発火された時に呼び出されるハンドラー関数を指定する必要があります。</p>
ありがとうございます、こちら取り入れさせていただきます 🙏🏼

2022-03-18 09:23 UTC, att55 commented on files/ja/web/guide/user_input_methods/index.html
> +<p>タッチスクリーンデバイスにインストールされることを目的としている Web アプリを開発している時、ディスプレイ解像度とユーザー入力に関して異なる性能を考慮することは良いプラクティスです。<a href="/ja/docs/Web/API/Touch_events">タッチイベント</a>は、タッチスクリーンデバイス上のインタラクションな要素と一般的なインタラクションジェスチャーを実装するの
修正しました！

2022-03-18 09:23 UTC, att55 commented on files/ja/web/guide/user_input_methods/index.html
> + <dd>この例は一度に複数のタッチ箇所を追跡しており、ユーザーは <code>{{htmlelement("canvas")}}</code> の中で一本以上の指で同時に描くことができます。タッチイベントをサポートしているブラウザでのみ動きます。</dd>
修正しました！

2022-03-18 09:24 UTC, att55 commented
@mfuji09 さん
ご指摘いただいた点を修正いたしました！

2022-03-20 04:36 UTC, merged