docs: object date updated to md
mdn/translated-content pull request #4573
Opened 2022-03-12 16:21 UTC by Vallejoanderson

2022-03-13 23:00 UTC, JuanVqz reviewed
@Vallejoanderson Gracias por traducir tan importante documento, hice algunas sugerencias por favor revisarlas y si tienes algún comentario, por acá andamos :+1: saludos!

2022-03-18 23:50 UTC, Vallejoanderson commented on files/es/web/javascript/reference/global_objects/date/index.md
> +Una fecha en JavaScript es fundamentalmente especificada como el número de milisegundos que han pasado desde la medianoche del 1 de Enero de 1970, UTC. Esta fecha y hora no son los mismos que en la *
Resuelto @JuanVqz. Muchas gracias por las revisiones!

2022-03-20 01:05 UTC, davbrito requested changes

2022-03-21 01:55 UTC, Vallejoanderson commented
Muchas gracias por las revisiones. @davbrito @JuanVqz :)

2022-03-21 02:17 UTC, davbrito approved these changes

2022-03-21 02:18 UTC, merged