「ブラウザーの互換性」の表記揺れを統一
mdn/translated-content pull request #4584
Opened 2022-03-13 10:46 UTC by teruteru128

### PR 内容

「ブラウザ互換性」「ブラウザー互換性」「ブラウザの互換性」を「ブラウザーの互換性」に統一しました。

h2タグのid属性が日本語だった場合でも統一したので、あとで問題になり得るかもしれません。

2022-03-13 10:49 UTC, teruteru128 commented
たとえば[このページ](https://developer.mozilla.org/ja/docs/Web/API/Document/execCommand)のような非推奨ヘッダから互換性一覧へのリンクがある場合、デッドリンクになってしまう恐れが、というよりもうなってますね

2022-03-14 15:34 UTC, mfuji09 requested changes
置換すると不自然になると思われる箇所を指摘しました。
他にも不自然になっている箇所がないか、目視での確認をお願いいたします。

2022-03-14 15:34 UTC, mfuji09 commented on files/ja/mdn/structures/compatibility_tables/index.html
>  ---
このページについては、「ブラウザー互換性データ」と言った方が自然なように思えます。

2022-03-15 13:04 UTC, teruteru128 commented
拡張子書き換えと中身の書き換えを別にするつもりだったのに、失敗してしまった……

2022-03-15 13:05 UTC, teruteru128 commented
あとはこんなに大きなPRなんだからmdへの変換はやらないほうがいいと今更思ったので、変換は１ファイルだけにします

2022-03-15 13:06 UTC, teruteru128 commented on files/ja/mozilla/add-ons/webextensions/browser_compatibility_for_manifest.json/index.html
> +title: manifest.json のブラウザーの互換性
「の」を２回付ける必要はないと思います

2022-03-15 13:06 UTC, teruteru128 commented on files/ja/mdn/structures/compatibility_tables/index.html
>  ---
直しました。

2022-03-15 13:27 UTC, teruteru128 commented on files/ja/web/api/globaleventhandlers/onkeypress/index.html
> +<h3 id="Browser_compatibility_notes" name="Browser_compatibility_notes">ブラウザーの互換性ノート</h3>
この部分MDN上で表示されてないですね？どうしたんでしょうか？

2022-03-15 13:27 UTC, teruteru128 commented on files/ja/web/api/html_drag_and_drop_api/index.html
> +<p><a href="/ja/docs/Web/API/DataTransferItem#Browser_compatibility">DataTransferItem インターフェイスのブラウザーの互換性テーブル</a>に見られるように、ドラッグ&amp;ドロップの相互接続性はデスクトップブラウザーでは相対的に広いです(サポートの少ない{{domxref("DataTransferItem"
これも2個目の「の」はいらないと思います

2022-03-15 13:27 UTC, teruteru128 commented on files/ja/web/api/web_audio_api/using_web_audio_api/index.html
> +<p>最新のブラウザーは Web Audio API のほとんどの機能によく対応しています。 API の機能はたくさんありますので、もっと正確な情報は、各リファレンスページのブラウザーの互換性一覧表をチェックする必要があるでしょう。</p>
これも「の」は2ついらないでしょう

2022-03-15 13:27 UTC, teruteru128 commented on files/ja/web/api/web_workers_api/functions_and_classes_available_to_workers/index.html
> +   <td>WebGL（Web グラフィックライブラリ）は、プラグインを使用せずにブラウザーの互換性を保ちながらインタラクティブな 3D と 2D レンダリングができる JavaScript API である。</td>
いらない……？

2022-03-15 13:27 UTC, teruteru128 commented on files/ja/web/api/window/scrollx/index.html
> +<p>クロスブラウザーの互換性のため、<code>window.scrollX</code> ではなく <code>window.pageXOffset</code> を使用します。<em>さらに</em>、古いバージョンの Internet Explorer (IE9 以前) はいずれもサポートしていないため、チェックの上、なければ他の非標準の方法で回避する必要があります。以下に互換性を確保し
「クロスブラウザー互換性のため」はそのままでいいように思うが、自信がない。

2022-03-15 13:27 UTC, teruteru128 commented on files/ja/web/api/window/scrolly/index.html
> +<p>クロスブラウザーの互換性のため、<code>window.scrollY</code> ではなく <code>window.pageYOffset</code> を使用します。<em>さらに</em>、古いバージョンの Internet Explorer (IE9 以前) はいずれもサポートしていないため、チェックの上、なければ他の非標準の方法で回避する必要があります。以下に互換性を確保し
クロスブラウザー互換性

2022-03-15 13:27 UTC, teruteru128 commented on files/ja/web/css/css_scroll_snap/index.md
> +個々のプロパティページにて、それぞれのプロパティのブラウザーの互換性情報を詳しく説明しています。
これもいらない

2022-03-15 13:27 UTC, teruteru128 commented on files/ja/web/javascript/reference/lexical_grammar/index.md
> +2進数の構文は、先頭のゼロに続いて小文字または大文字のラテン文字 "B" を使用します (`0b` または `0B`)。この構文は ECMAScript 2015 の新しい構文なので、下記のブラウザーの互換性表をご覧ください。 `0b` の後の数字が 0 または 1 でない場合は、 {{jsxref("SyntaxError")}} が "Missing binary digits after
～表、となっている場合はそのままでいいのか？

2022-03-15 13:27 UTC, teruteru128 commented on files/ja/web/javascript/reference/lexical_grammar/index.md
> +8進数の構文は、先頭のゼロに続いて小文字または大文字のラテン文字 "O" を使用します (`0o` または `0O`)。この構文は ECMAScript 2015 の新しい構文なので、下記のブラウザーの互換性表をご覧ください。 `0o` の後の数字が範囲 (01234567) 外の場合、 {{jsxref("SyntaxError")}} が "Missing octal digits afte
ここも同じく互換性表

2022-03-15 13:27 UTC, teruteru128 commented on files/ja/web/mathml/authoring/index.html
> +<p>これら 2 つのスクリプトは <a href="/ja/docs/Web/MathML/Element/mspace">mspace</a> または <a href="/ja/docs/Web/MathML/Element/mpadded">mpadded</a> 要素の機能検出を行うことに注意してください (これらのページのブラウザーの互換性表を参照してください)。また、良好な Math
互換性表

2022-03-15 13:27 UTC, teruteru128 commented on files/ja/web/xslt/element/index.html
> +<div class="blockIndicator todo">\{{ListSubpages}} マクロを、<a href="/ja/docs/MDN/Contribute/Structures/Compatibility_tables">ブラウザーの互換性データ</a> が <code><a href="/ja/docs/Web/XSLT/Element/fallback">&lt;xsl
これも消したほうが違和感は少ないと思います

2022-03-15 13:31 UTC, teruteru128 commented
とりあえず確認が終わりました。

2022-03-15 16:14 UTC, mfuji09 commented
様々な書式の書き方については、プルリクエスト上で議論すると埋もれてしまうので、Slackかmozilla-japanのレポジトリで議論しませんか。

2022-03-15 17:52 UTC, teruteru128 commented
そうですね、そうしましょう

2022-08-14 05:00 UTC, mfuji09 commented
@teruteru128 さん
この後、 HTML の記事を一括で markdown 化する予定があります。
競合を解決するめどが立たないようであれば、いったんクローズし、 markdown 化後に再度実行してくださるようお願いします。

2022-08-16 04:25 UTC, closed without merging

2022-08-16 23:02 UTC, teruteru128 commented
了解しました