16. SyntaxError translation ang macro issue
mdn/translated-content pull request #4591
Opened 2022-03-13 15:11 UTC by hectormoba

2022-03-13 22:18 UTC, JuanVqz requested changes
@hectormoba muy buen aporte, muchas gracias por tu interés y ayuda! :100:  

Te solicité unos pequeños cambios, por favor.

2022-03-13 22:18 UTC, JuanVqz commented on files/es/web/javascript/reference/global_objects/syntaxerror/index.md
> +---
Hola Hector, te compartiré lo que yo entiendo de las alternativas e importancia  de la macro `compat`.

# Alternativas
Existen dos formas que la macro `{{Compat}}` funcione:

1. Escribir en los meta datos la referencia de compatibilidad `browser-compat: javascript.builtins.SyntaxError` y la macro usarla simplemente llamando `{{Compat}}`.

2. Escribir la referencia directo en la macro `{{Compat('javascript.builtins.SyntaxError')}}`

Preferencias sobre una o la otra? Creo que no existen, sin embargo en este caso te sugerí que fuera en los meta-datos por que es la forma que la documentación en [ingles](https://raw.githubusercontent.com/mdn/content/main/files/en-us/web/javascript/reference/global_objects/syntaxerror/index.md) la usó.

# Importancia
Es de suma importancia incluir correctamente la macro `{{Compat}}`, ya sea como la alternativa 1 o 2.


```suggestion
browser-compat: javascript.builtins.SyntaxError
---
```

2022-03-13 22:18 UTC, JuanVqz commented on files/es/web/javascript/reference/global_objects/syntaxerror/index.md
> +
```suggestion
```

2022-03-13 22:18 UTC, JuanVqz commented on files/es/web/javascript/reference/global_objects/syntaxerror/index.md
> +- {{jsxref("Error")}}
Por convención dejamos una linea en blanco al finalizar el documento. 

```suggestion
- {{jsxref("Error")}}

```

2022-03-14 22:43 UTC, JuanVqz requested changes
@hectormoba una disculpa por solicitar cambios nuevamente pero no había visto los tags.

2022-03-14 22:43 UTC, JuanVqz commented on files/es/web/javascript/reference/global_objects/syntaxerror/index.md
> +  - SyntaxError
@hectormoba una disculpa no había visto que agregaste los tags, MDN ya no usa tags (de hecho creo que nunca lo usó) para las traducciones. Entonces ya no los agregamos en las traducciones, podrías remover los por favor?
```suggestion
```

2022-03-15 12:55 UTC, hectormoba commented on files/es/web/javascript/reference/global_objects/syntaxerror/index.md
> +  - SyntaxError
Bien. Lo sabía pero me olvidé de sacarlos!. Me lo apunto para la próxima

2022-03-15 13:51 UTC, JuanVqz approved these changes
@hectormoba Gracias por contribuir! :100:

2022-03-15 16:55 UTC, Vallejoanderson requested changes

2022-03-15 16:55 UTC, Vallejoanderson commented on files/es/web/javascript/reference/global_objects/syntaxerror/index.md
> +### Creating a SyntaxError
```suggestion
### Creando un SyntaxError
```

2022-03-16 18:32 UTC, merged