Remove {{manch}} macro for French
mdn/translated-content pull request #4624
Opened 2022-03-15 06:56 UTC by SphinxKnight

Why be ambitious and help on #4617 when you can remove a simple macro in 1 file? 🤔

2022-03-15 20:58 UTC, cw118 requested changes
Je ne savais pas que cette macro existait 👀

Quelques suggestions plutôt subjectives, merci @SphinxKnight :)

2022-03-15 20:58 UTC, cw118 commented on files/fr/web/api/blobbuilder/index.md
> +
```suggestion
<table class="standard-table">
  <tbody>
    <tr>
      <td>
        <code>void <a href="/fr/docs/Web/API/BlobBuilder#append">append</a>(in ArrayBuffer data);</code>
      </td>
    </tr>
    <tr>
      <td>
        <code>void <a href="/fr/docs/Web/API/BlobBuilder#append">append</a>(in Blob data);</code>
      </td>
    </tr>
    <tr>
      <td>
        <code>void <a href="/fr/docs/Web/API/BlobBuilder#append">append</a>(in String data, [optional] in String endings);</code>
      </td>
    </tr>
    <tr>
      <td>
        <code>Blob <a href="/fr/docs/Web/API/BlobBuilder#getblob">getBlob</a>([optional] in DOMString contentType);</code>
      </td>
    </tr>
    <tr>
      <td>
        <code>File <a href="/fr/docs/Web/API/BlobBuilder#getfile">getFile</a>(in DOMString name, [optional] in DOMString contentType);</code>
      </td>
    </tr>
  </tbody>
</table>
```

2022-03-15 20:58 UTC, cw118 commented on files/fr/web/api/blobbuilder/index.md
> +  in DOMString contentType {{optional_inline}}
avec la macro `{{optional_inline}}` on voit "`in DOMString contentType Facultatif`" que je trouvais un peu bizarre

```suggestion
  in DOMString contentType // facultatif
```

2022-03-15 20:58 UTC, cw118 commented on files/fr/web/api/blobbuilder/index.md
> +- [La spécification de `BlobBuilder` au sein de l'API File](https://dev.w3.org/2009/dap/file-system/file-writer.html#idl-def-BlobBuilder)
```suggestion
- [La spécification de `BlobBuilder` au sein de l'API File (en anglais)](https://dev.w3.org/2009/dap/file-system/file-writer.html#idl-def-BlobBuilder)
```

2022-03-16 05:38 UTC, SphinxKnight commented on files/fr/web/api/blobbuilder/index.md
> +
je trouvais que le tableau n'apportait pas grand chose sémantiquement et je n'ai pas souvenir d'avoir vu ce type de structure sur d'autres pages analogues (indiquant qu'il faudrait garder ce tableau pour la cohérence).

2022-03-16 11:57 UTC, cw118 approved these changes
Merci beaucoup Sphinx 😄

2022-03-16 11:57 UTC, merged