Update index.md
mdn/translated-content pull request #4630
Opened 2022-03-15 10:17 UTC by StephaneRegnie

Corrections orthographe + grammaire dans Mettre à jour les données de la balle

2022-03-15 21:17 UTC, cw118 requested changes
Quelques suggestions, surtout pour de la typographie :)

2022-03-15 21:17 UTC, cw118 commented on files/fr/learn/javascript/objects/object_building_practice/index.md
> +Nous pouvons dessiner la balle dans n'importe quelle position, mais actuellement pour commencer à la bouger, nous aurons besoin d'une sorte de fonction de mise à jour. Insérez donc le code suivant à
```suggestion
Nous pouvons dessiner la balle dans n'importe quelle position, mais actuellement pour commencer à la bouger, nous aurons besoin d'une sorte de fonction de mise à jour. Insérez donc le code suivant à la fin de votre fichier JavaScript pour ajouter une méthode `update()` au `prototype` de `Ball()`&nbsp;:
```

2022-03-15 21:17 UTC, cw118 commented on files/fr/learn/javascript/objects/object_building_practice/index.md
> +Les quatre premières parties de la fonction vérifient si la balle a atteint le rebord du canvas. Si c'est le cas, nous inversons la polarité de la vitesse appropriée pour faire bouger la balle dans l
```suggestion
Les quatre premières parties de la fonction vérifient si la balle a atteint le rebord du `canvas`. Si c'est le cas, nous inversons la polarité de la vitesse appropriée pour faire bouger la balle dans le sens opposé. Donc, par exemple, si la balle se déplaçait vers le haut (`velY` positif) alors la vitesse verticale est changée afin qu'elle commence à bouger plutôt vers le bas (`velY` négatif).
```

2022-03-15 21:17 UTC, cw118 commented on files/fr/learn/javascript/objects/object_building_practice/index.md
> +Dans les quatre cas, nous vérifions:
```suggestion
Dans les quatre cas, nous vérifions&nbsp;:
```

2022-03-15 21:17 UTC, cw118 commented on files/fr/learn/javascript/objects/object_building_practice/index.md
> +- Si la coordonnée `y` est plus petite que 0 (la balle est en train de sortir par le  haut).
```suggestion
- Si la coordonnée `x` est plus grande que la largeur du `canvas` (la balle est en train de sortir du côté droit).
- Si la coordonnée `x` est plus petite que `0` (la balle est en train de sortir du côté gauche).
- Si la coordonnée `y` est plus grande que la hauteur du `canvas` (la balle est en train de sortir par le bas).
- Si la coordonnée `y` est plus petite que `0` (la balle est en train de sortir par le haut).
```

2022-03-15 21:17 UTC, cw118 commented on files/fr/learn/javascript/objects/object_building_practice/index.md
> +Dans chaque cas, nous incluons la taille `size` de la balle dans les calculs parce que les coordonnées  `x`/`y`  sont situées au centre de la balle mais nous voulons que le pourtour de la balle rebon
```suggestion
Dans chaque cas, nous incluons la taille (`size`) de la balle dans les calculs parce que les coordonnées `x`/`y` sont situées au centre de la balle, mais nous voulons que le pourtour de la balle rebondisse sur le rebord — nous ne voulons pas que la balle sorte à moitié hors de l'écran avant de commencer à rebondir vers l'arrière.
```

2022-03-16 06:20 UTC, StephaneRegnie commented
😉👍

2022-03-16 06:22 UTC, StephaneRegnie commented
😉👍

2022-03-16 10:57 UTC, StephaneRegnie commented on files/fr/learn/javascript/objects/object_building_practice/index.md
> +Dans les quatre cas, nous vérifions:
👍

2022-03-16 10:58 UTC, StephaneRegnie commented
@cw118 D'accord avec tes retours, j'ai quelque chose à faire ensuite ? Merci

2022-03-16 15:33 UTC, cw118 commented
> D'accord avec tes retours, j'ai quelque chose à faire ensuite ? Merci

Il ne reste qu'à accepter les suggestions :) vu qu'il y en a plusieurs, Github permet de les ajouter à un "lot" (en cliquant sur le bouton "[Add suggestion to batch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request )” pour chaque commentaire) et de générer un seul commit apportant toutes les modifications.

2022-03-16 16:57 UTC, cw118 commented
(Il y a aussi un conflit après #4270 que je vais régler)

2022-03-16 17:01 UTC, StephaneRegnie commented
👍

2022-03-16 17:04 UTC, StephaneRegnie commented
@cw118 C'est fait ;)

2022-03-16 18:53 UTC, cw118 commented on files/fr/learn/javascript/objects/object_building_practice/index.md
> +Dans les quatre cas, nous vérifions:
Il reste celle-ci :)

2022-03-16 20:07 UTC, cw118 approved these changes
Merci beaucoup pour ces corrections @StephaneRegnie !

2022-03-16 20:07 UTC, merged