/docs/Web/HTML/Quirks_Mode_and_Standards_Mode のリンク切れセクションを削除して、文書をブラッシュアップ
mdn/translated-content pull request #4673
Opened 2022-03-17 08:24 UTC by debiru

### 修正内容

- 原文では存在しない（削除されている）「モードの違い」というセクションが残っているが、リンク切れのリンクが2つだけ示されているだけで情報として意味を成していないので削除した
- ついでに、文書全体を軽くブラッシュアップした
    - html 形式だったので md 形式に変換した
    - 原文では参照されていた「Firefox のページ情報ウィンドウ」へのリンクを追加した
    - 日本語訳の用語「準標準」「完全標準準拠」「標準準拠」の使い方に揺れがあったので修正した

### 修正箇所

- https://developer.mozilla.org/ja/docs/Web/HTML/Quirks_Mode_and_Standards_Mode
    - この日本語訳の文書全体

### 修正に関する備考

- もともと書かれていた [ダウンロードするダイアログボックス](https://developer.mozilla.org/ja/docs/Glossary/XHTML#support) というリンクが意味を成していない（リンク先のハッシュフラグメントが存在しない）。
    - しかし原文も同様だったのでそのままにしている。

### 関連Issue

- https://github.com/mozilla-japan/translation/issues/592

2022-03-18 16:10 UTC, mfuji09 requested changes
私的項目の修正をお願いします。

2022-03-18 16:10 UTC, mfuji09 commented on files/ja/web/html/quirks_mode_and_standards_mode/index.md
> +ウェブブラウザーのレイアウトエンジンが利用するモードは、後方互換 (Quirks) モード、準標準 (Almost Standards) モード、完全標準準拠 (Full Standards) モードの3種類になりました。<strong>後方互換モード</strong>では、レイアウトは Navigator 4 や Internet Explorer 5 のような非標準の動作をエミュレートします
\<strong>要素ではなく、Markdownの\*\*を使用してください。

2022-03-18 16:33 UTC, debiru commented on files/ja/web/html/quirks_mode_and_standards_mode/index.md
> +かつてウェブでは、よく2つのバージョンのページを作成していました。ひとつは Netscape Navigator 向け、もうひとつは Microsoft Internet Explorer 向けです。 W3C がウェブ標準を作成したとき、ウェブ上のほとんどの既存サイトの表示が壊れるため、ブラウザーはウェブ標準を採用し始めることができませんでした。そのためブラウザーは、標準に準拠した新しいサイトと
be94969 で修正しました。複数箇所修正しています。

2022-03-18 16:34 UTC, debiru commented on files/ja/web/html/quirks_mode_and_standards_mode/index.md
> +`Content-Type` HTTP ヘッダで `application/xhtml+xml` を使用して、ページを [XHTML](/ja/docs/XHTML) として提供する場合は、文書で常に完全標準準拠モードを使用しますので、標準準拠モードを有効化するための DOCTYPE は不要です。ただし Internet Explorer 8 は<code>application/xhtml+x
b418e9a で修正しました。この1箇所以外は修正漏れは見当たりませんでした（見逃していなければ）。

2022-03-18 16:35 UTC, debiru commented on files/ja/web/html/quirks_mode_and_standards_mode/index.md
> +ウェブブラウザーのレイアウトエンジンが利用するモードは、後方互換 (Quirks) モード、準標準 (Almost Standards) モード、完全標準準拠 (Full Standards) モードの3種類になりました。<strong>後方互換モード</strong>では、レイアウトは Navigator 4 や Internet Explorer 5 のような非標準の動作をエミュレートします
cf586a6 で修正しました。`strong` の他に `code` の修正漏れもありました。

2022-03-18 16:38 UTC, debiru commented on files/ja/web/html/quirks_mode_and_standards_mode/index.md
> +かつてウェブでは、よく2つのバージョンのページを作成していました。ひとつは Netscape Navigator 向け、もうひとつは Microsoft Internet Explorer 向けです。 W3C がウェブ標準を作成したとき、ウェブ上のほとんどの既存サイトの表示が壊れるため、ブラウザーはウェブ標準を採用し始めることができませんでした。そのためブラウザーは、標準に準拠した新しいサイトと
afb9f68 を追加修正しました。句点直後の不要な空白を削除しています。

2022-03-20 03:21 UTC, mfuji09 approved these changes
OKです。

2022-03-20 03:21 UTC, merged

2022-03-20 03:21 UTC, mfuji09 commented
修正ありがとうございました。