Correção da explicação sobre os parâmetros
mdn/translated-content pull request #4718
Opened 2022-03-19 02:42 UTC by im-ramon

1. Faltou ser explicado como funciona o parâmetro "acumulador".
2. A explicação do parâmetro "valorAtual" estava sem o título (<dt>).

2022-03-26 06:35 UTC, nathipg commented on files/pt-br/web/javascript/reference/global_objects/array/reduce/index.html
> + <dd>É o valor inicial (ou o valor do callback anterior). Este valor inicia com o <font face="Consolas, Liberation Mono, Courier, monospace"><code>valorInicial</code></font> e será retornado na ultim
```suggestion
 <dd>É o valor inicial (ou o valor do callback anterior). Este valor inicia com o <font face="Consolas, Liberation Mono, Courier, monospace"><code>valorInicial</code></font> e será retornado na última iteração.</dd>
```

2022-03-26 06:36 UTC, nathipg requested changes
Obrigada pela contribuição!
Poderia corrigir esse pequeno erro de digitação, por favor?

2022-03-26 22:50 UTC, im-ramon commented
> Obrigada pela contribuição! Poderia corrigir esse pequeno erro de digitação, por favor?

Estou procurando onde corrijo. 😅 Sou novo por aqui.

2022-03-27 23:47 UTC, nathipg commented
> > Obrigada pela contribuição! Poderia corrigir esse pequeno erro de digitação, por favor?
> 
> Estou procurando onde corrijo. 😅 Sou novo por aqui.

Boa noite! 
Sem problemas, você pode aceitar a alteração que eu sugeri e isso vai gerar um commit corrigindo ou você pode alterar na sua máquina e criar um novo commit.
Se precisar de instruções mais detalhadas, me avisa, por favor, aí eu faço um passo a passo.

2022-03-28 00:04 UTC, im-ramon commented
> > > Obrigada pela contribuição! Poderia corrigir esse pequeno erro de digitação, por favor?
> > 
> > 
> > Estou procurando onde corrijo. 😅 Sou novo por aqui.
> 
> Boa noite! Sem problemas, você pode aceitar a alteração que eu sugeri e isso vai gerar um commit corrigindo ou você pode alterar na sua máquina e criar um novo commit. Se precisar de instruções mais detalhadas, me avisa, por favor, aí eu faço um passo a passo.

Se for possível, peço que me diga como posso aceitar a alteração, até já pesquisei na internet, mas ainda não entendi como/ onde fazer. Desde já agradeço!

2022-04-09 00:56 UTC, nathipg approved these changes

2022-04-09 01:09 UTC, merged