Rewrite Learn/What is JavaScript
mdn/translated-content pull request #4794
Opened 2022-03-23 14:14 UTC by alattalatta

#1042

- Markdown
  - 스쿼시 병합 하지 말아주세요.
- 재작성

2022-03-23 14:29 UTC, yechoi42 commented
안녕하세요 @alattalatta 님 :) 별도로 수정하신 포인트가 있을까요? 혹은 전반적으로 재번역하신 것일까요? 공유해주신다면 참고해서 리뷰하겠습니다!

2022-03-23 14:48 UTC, alattalatta commented
안녕하세요 @yechoi42 님, 문서 전체를 손질했습니다. [업데이트 커밋](https://github.com/mdn/translated-content/pull/4794/commits/096f2a1dc716112311088ab2491e5f4a7bad1faa)을 보시면 아시겠지만 기존 번역은 굳이 확인 안하셔도 될 것 같아요. 감사합니다.

2022-04-07 13:42 UTC, yechoi42 requested changes
와 번역 정말 깔끔하네요!! 몇가지 코멘트를 남겨두었습니다. 확인 후 저를 다시 불러주세요 :)

2022-04-07 13:42 UTC, yechoi42 commented on files/ko/learn/javascript/first_steps/what_is_javascript/index.md
> +웹 페이지의 내용이 — 가만히 정적인 정보만 보여주는 것이 아니라 — 주기적으로 갱신되거나, 사용자와 상호작용이 가능하거나, 애니메이션이 적용된 2D/3D 그래픽을 볼 수 있다면 JavaScript가 관여하고 있을 거라고 생각해도 좋습니다. JavaScript는 스크립팅 또는 프로그래밍 언어로, 표준 웹 기술이라는 케이크의 세 번째 층입니다. 다른 두 개
```suggestion
JavaScript는 웹 페이지에서 복잡한 기능을 구현할 수 있도록 하는 스크립팅 언어 또는 프로그래밍 언어입니다. 페이지의 내용이 — 가만히 정적인 정보만 보여주는 것이 아니라 — 주기적으로 갱신되거나, 사용자와 상호작용이 가능하거나, 애니메이션이 적용된 2D/3D 그래픽을 볼 수 있다면 JavaScript가 관여하고 있을 거라고 생각해도 좋습니다. JavaScript는 표준 웹 기술이라는 케이크의 세 번째 층입니다. 다른 두 개([HTML](/ko/docs/Learn/HTML)과 [CSS](/ko/docs/Learn/CSS))는 학습장의 다른 곳에서 자세히 알아봤습니다.
```
JavaScript 를 정의하는 문장은 순서와 의미를 원문과 동일하게 전달하는 것이 좋을 것 같아 수정하였습니다.

2022-04-07 13:42 UTC, yechoi42 commented on files/ko/learn/javascript/first_steps/what_is_javascript/index.md
> +![](html-and-css.png)
이 파일도 폴더 안에 추가해주세요

2022-04-07 13:42 UTC, yechoi42 commented on files/ko/learn/javascript/first_steps/what_is_javascript/index.md
> +![](just-html.png)
이 파일도 폴더에 추가해주셔야 로딩될 듯합니다

2022-04-07 13:42 UTC, yechoi42 commented on files/ko/learn/javascript/first_steps/what_is_javascript/index.md
> +바로 위의 텍스트 레이블클 클릭해서 어떤 일이 일어나는지 확인해보세요. (이 데모는 GitHub에서도 볼 수 있습니다. [소스코드](https://github.com/mdn/learning-area/blob/main/javascript/introduction-to-js-1/what-is-js/javascript-label.html)를 읽거나 [실행된 모습
```suggestion
바로 위의 텍스트 레이블을 클릭해서 어떤 일이 일어나는지 확인해보세요. (이 데모는 GitHub에서도 볼 수 있습니다. [소스코드](https://github.com/mdn/learning-area/blob/main/javascript/introduction-to-js-1/what-is-js/javascript-label.html)를 읽거나 [실행된 모습](https://mdn.github.io/learning-area/javascript/introduction-to-js-1/what-is-js/javascript-label.html)을 확인해보세요)
```

2022-04-07 13:42 UTC, yechoi42 commented on files/ko/learn/javascript/first_steps/what_is_javascript/index.md
> +- 텍스트 조각(프로그래밍에서 "문자열"(string)이라고 말하는)을 조작합니다. 위 예제에서는 문자열 "플레이어 1: "과 `name` 변수의 값을 합쳐 온전한 텍스트 레이블("Player 1: Chris")을 생성합니다.
```suggestion
- 프로그래밍에서 문자열(string)이라고 말하는 텍스트 조각을 조작합니다. 위 예제에서는 문자열 "플레이어 1: "과 `name` 변수의 값을 합쳐 온전한 텍스트 레이블("Player 1: Chris")을 생성합니다.
```
괄호가 겹으로 있으니 어색해서 이렇게 수정하는 것 어떨까요?

2022-04-07 13:42 UTC, yechoi42 commented on files/ko/learn/javascript/first_steps/what_is_javascript/index.md
> +![](browser.png)
이것도 옮겨주세요

2022-04-07 13:42 UTC, yechoi42 commented on files/ko/learn/javascript/first_steps/what_is_javascript/index.md
> +브라우저가 웹 페이지를 불러오면 어떤 일이 발생하는지 간단하게 복습해봅시다. ([CSS 동작 방식](/ko/docs/Learn/CSS/First_steps/How_CSS_works#CSS_는_실제로_어떻게_작동합니까)에서 먼저 알아봤습니다) 웹 페이지를 브라우저로 불러오면, 브라우저는 여러분의 코드(HTML, CSS, JavaScript)를 실행 환경(브
```suggestion
브라우저가 웹 페이지를 불러오면 어떤 일이 발생하는지 간단하게 복습해봅시다([CSS 동작 방식](/ko/docs/Learn/CSS/First_steps/How_CSS_works#CSS_는_실제로_어떻게_작동합니까)에서 먼저 알아봤습니다). 웹 페이지를 브라우저로 불러오면, 브라우저는 여러분의 코드(HTML, CSS, JavaScript)를 실행 환경(브라우저 탭)에서 실행합니다. 원자재(코드)를 가져와서 상품(웹 페이지)을 생산하는 공장처럼 생각할 수 있습니다.
```
마침표의 위치를 괄호 끝난 후로 옮겼습니다.

2022-04-07 13:42 UTC, yechoi42 commented on files/ko/learn/javascript/first_steps/what_is_javascript/index.md
> +스크립트를 적절한 시점에 불러오는 일에는 몇 가지 문제가 있습니다. 뭐든지 보이는 것 만큼 간단하지는 않은 법이죠. 흔히 마주치게 되는 문제는, 페이지의 모든 HTML은 순서 그대로 불러온다는 점입니다. JavaScript를 사용해서 페이지 내의 요소 — 더 정확하게는 [Document Object Model](/ko/docs/Learn/JavaScrip
```suggestion
스크립트를 적절한 시점에 불러오는 일에는 몇 가지 문제가 있습니다. 뭐든지 보이는 것만큼 간단하지는 않은 법이죠. 흔히 마주치게 되는 문제는, 페이지의 모든 HTML은 순서 그대로 불러온다는 점입니다. JavaScript를 사용해서 페이지 내의 요소 — 더 정확하게는 [Document Object Model](/ko/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents#the_document_object_model) — 를 조작하려고 할 때, 해당 요소를 포함한 HTML 코드보다 JavaScript를 먼저 불러와버리면 코드가 올바르게 동작하지 못할 것입니다.
```
띄어쓰기 수정했습니다

2022-04-07 13:42 UTC, yechoi42 commented on files/ko/learn/javascript/first_steps/what_is_javascript/index.md
> +![](async-defer.jpg)
여기도 이미지가 있습니다

2022-04-08 02:44 UTC, alattalatta commented on files/ko/learn/javascript/first_steps/what_is_javascript/index.md
> +![](html-and-css.png)
영어 문서와 동일한 이미지라 추가하지 않았습니다! https://github.com/mdn/translated-content/issues/4545 와 https://github.com/mdn/yari/pull/5215 를 참고해주세요.

PR 프리뷰 시에는 이미지를 불러올 수 없지만, 실제 배포 시(혹은 로컬 구동 시)에는 정상적으로 불러옵니다.

이하 동일한 리뷰는 제가 닫아놓을게요. 참고해주세요.

2022-04-10 01:47 UTC, alattalatta commented
@yechoi42 꼼꼼하게 봐주셔서 감사합니다~ 리뷰로 올려주신 건은 모두 반영했습니다.

2022-04-10 03:38 UTC, yechoi42 approved these changes
감사합니다! :) 머지하겠습니다.

2022-04-10 03:38 UTC, merged