Convert into md
mdn/translated-content pull request #4807
Opened 2022-03-24 10:04 UTC by UESTCzhouyuchuan

Convert into markdown and sync english version content.
Page:
Web/HTTP/status

2022-03-24 11:42 UTC, yin1999 commented
To keep the commit history, please follow the commit step below:

1. commit 1: renamve the `.html` file to `.md` file (using git command `git mv /path/to/index.html /path/to/index.md`)
2. commit 2: convert the content to markdown (and sync with english version, it's optional)

You can refer [the merged PR before](https://github.com/mdn/translated-content/pull/4744/commits)

If you have difficulty to deal with it in this pr, new pr is welcomed.

2022-03-24 11:47 UTC, yin1999 requested changes

2022-03-24 11:47 UTC, yin1999 commented on files/zh-cn/web/http/status/index.md
> +5. [服务端错误响应](#server_error_responses) (`500`–`599`)
those anchors are not correct.

```md
1. [信息响应](#信息响应) (`100`–`199`)
2. [成功响应](#成功响应) (`200`–`299`)
3. [重定向消息](#重定向消息) (`300`–`399`)
4. [客户端错误响应](#客户端错误响应) (`400`–`499`)
5. [服务端错误响应](#服务端错误响应) (`500`–`599`)
```

In markdown, the head is almost the same as the `id`.

2022-03-24 11:47 UTC, yin1999 commented on files/zh-cn/web/http/status/index.md
> +5. [服务端错误响应](#server_error_responses) (`500`–`599`)
so, please redo the commits and also update those anchors.

2022-03-24 11:54 UTC, yin1999 requested changes

2022-03-24 11:54 UTC, yin1999 commented on files/zh-cn/web/http/status/index.md
> +## 你也可以看看
suggestion:

```markdown
## 参见
```

2022-03-24 18:10 UTC, UESTCzhouyuchuan commented
> To keep the commit history, please follow the commit step below:
> 
> 1. commit 1: renamve the `.html` file to `.md` file (using git command `git mv /path/to/index.html /path/to/index.md`)
> 2. commit 2: convert the content to markdown (and sync with english version, it's optional)
> 
> You can refer [the merged PR before](https://github.com/mdn/translated-content/pull/4744/commits)
> 
> If you have difficulty to deal with it in this pr, new pr is welcomed.
Thanks. My friend. I have taken your advice.

2022-03-25 01:32 UTC, yin1999 requested changes

2022-03-25 01:32 UTC, yin1999 commented on files/zh-cn/web/http/status/index.md
> +> **Note:** 如果您收到的响应不在此列表中 [this list](#information-responses)，则它为非标准响应，可能是服务器软件的自定义响应。
For hightlight this notecard, using `> **备注：** ` (in `zh-CN`) as prefix. Reference: [markdown in mdn](https://developer.mozilla.org/zh-CN/docs/MDN/Contribute/Markdown_in_MDN#%E5%A4%87%E6%B3%A8%E3%80%81%E8%AD%A6%E5%91%8A%E5%92%8C%E6%A0%87%E6%B3%A8)

And this anchor is not right now.

suggestion:

```markdown
> **备注：** 如果您收到的响应不在[此列表](#信息响应)中，...
```

2022-03-25 01:32 UTC, yin1999 commented on files/zh-cn/web/http/status/index.md
> +- [List of HTTP status codes on Wikipedia](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)
`zh-CN` wiki is prefered (if exists):

```markdown
- [维基百科上的 HTTP 状态码](https://zh.wikipedia.org/wiki/HTTP状态码)
```

2022-03-25 01:32 UTC, yin1999 commented on files/zh-cn/web/http/status/index.md
> +HTTP 响应状态码用来表明特定 [HTTP](/en-US/docs/Web/HTTP) 请求是否成功完成。
just using the link to `zh-CN` (even if the document does not exist, mdn will fallback to `en-US` for not existing document).

```markdown
[HTTP](/zh-CN/docs/Web/HTTP)
```

2022-03-25 01:32 UTC, yin1999 commented on files/zh-cn/web/http/status/index.md
> +  - : 此状态代码主要用于与 {{HTTPHeader("Link")}} 链接头一起使用，以允许用户代理在服务器准备响应阶段时开始预加载[preloading](/en-US/docs/Web/HTML/Link_types/preload)资源。
also, use hyperlink to `zh-CN`:

```markdown
[预加载（preloading）](/zh-CN/docs/Web/HTML/Link_types/preload)
```

2022-03-25 01:32 UTC, yin1999 commented on files/zh-cn/web/http/status/index.md
> +  - : 当web服务器在执行服务器驱动的内容协商[server-driven content negotiation](/en-US/docs/Web/HTTP/Content_negotiation#server-driven_negotiation)后，没有发现任何符合用户代理给定标准的内容时，就会发送此响应。
suggestion:

```markdown
[服务端驱动的内容协商](/zh-CN/docs/Web/HTTP/Content_negotiation#服务端驱动型内容协商机制)
```

2022-03-25 03:35 UTC, UESTCzhouyuchuan commented on files/zh-cn/web/http/status/index.md
> +  - : 当web服务器在执行服务器驱动的内容协商[server-driven content negotiation](/en-US/docs/Web/HTTP/Content_negotiation#server-driven_negotiation)后，没有发现任何符合用户代理给定标准的内容时，就会发送此响应。
ok，get it

2022-03-25 11:04 UTC, yin1999 commented
If there is not conflict, [merging branch](https://github.com/mdn/translated-content/pull/4807/commits/aef70d12836795774f70136e542a70ffeb399d70) is not necessary. Just merge the last three commits into a single commit (without merging `main` branch).

2022-03-25 13:26 UTC, yin1999 requested changes

2022-03-25 13:26 UTC, yin1999 commented on files/zh-cn/web/http/status/index.md
> +- [List of HTTP status codes on Wikipedia](https://zh.wikipedia.org/wiki/List_of_HTTP_status_codes)
这个链接不正确哈，https://github.com/mdn/translated-content/pull/4807#discussion_r834874138

2022-03-25 14:40 UTC, UESTCzhouyuchuan commented on files/zh-cn/web/http/status/index.md
> +- [List of HTTP status codes on Wikipedia](https://zh.wikipedia.org/wiki/List_of_HTTP_status_codes)
en version content
```md
- [List of HTTP status codes on Wikipedia](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)
- [IANA official registry of HTTP status codes](https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml)
```

我这边用不了wikipedia，算了这搞的，等我研究复试结束后再想办法吧

2022-03-28 05:01 UTC, UESTCzhouyuchuan commented on files/zh-cn/web/http/status/index.md
> +- [List of HTTP status codes on Wikipedia](https://zh.wikipedia.org/wiki/List_of_HTTP_status_codes)
链接ok了，哥

2022-03-28 05:07 UTC, yin1999 commented on files/zh-cn/web/http/status/index.md
> +- [List of HTTP status codes on Wikipedia](https://zh.wikipedia.org/wiki/List_of_HTTP_status_codes)
链接内容请一并帮助修改：

```markdown
- [维基百科上的 HTTP 状态码](https://zh.wikipedia.org/wiki/HTTP状态码)
```

2022-03-29 18:43 UTC, merged