fix: 更正翻译
mdn/translated-content pull request #4819
Opened 2022-03-25 01:28 UTC by situ2001

翻译成影子DOM比翻译成阴影DOM更恰当

参考自 [javascript.info](https://zh.javascript.info/shadow-dom)

2022-03-29 18:26 UTC, irvin requested changes
搜索可見兩者的使用次數相差不多，請補充更多孰好孰壞的相關資訊、或相關的討論連結，以協助判斷。

https://www.google.com/search?q=%22阴影DOM%22
https://www.google.com/search?q=%22影子DOM%22

2022-03-29 18:59 UTC, irvin commented
@yin1999 how do you think?

2022-03-30 01:24 UTC, yin1999 commented
> @yin1999 how do you think?

我倾向于暂不翻译该词语，`Shadow DOM` 一词在 Google Chrome 以及 FireFox 浏览器的 `l10n` 本地化翻译中，均未作翻译（Edge 将其翻译为 `阴影DOM`）。而由 Google 搜索提供的结果来看，两种翻译均没有大量的应用，因此采用任意一种翻译均可能给读者带来一定的困扰。

## Google Chrome

![image](https://user-images.githubusercontent.com/15844309/160731242-a049a639-b5d6-420d-a742-5c7812b447ee.png)

## FireFox

source: https://hg.mozilla.org/l10n-central

仅有一处涉及 `Shadow DOM`

![image](https://user-images.githubusercontent.com/15844309/160731330-5da82624-48f6-4a97-9bf2-cfbe7c535d35.png)

## Edge

![image](https://user-images.githubusercontent.com/15844309/160731871-656e6fdf-bec8-4715-b3a8-031446b20692.png)

2022-03-30 11:36 UTC, irvin requested changes
@situ2001 那麼請你不更改翻譯，但補上（shadow dom）的附註，這樣如何？

2022-03-30 15:42 UTC, situ2001 commented
> @situ2001 那麼請你不更改翻譯，但補上（shadow dom）的附註，這樣如何？

好的

2022-03-30 15:49 UTC, situ2001 commented
@irvin 已按你的要求进行更改

2022-03-31 01:24 UTC, merged