:globe_with_meridians: improve localization for zh-CN
mdn/translated-content pull request #4836
Opened 2022-03-26 06:32 UTC by tolerious

2022-03-26 08:55 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/anatomy_of_a_webextension/index.html
> + <li><a href="https://developer.mozilla.org/zh-CN/docs/Mozilla/Add-ons/WebExtensions/user_interface/Options_pages">选项页面</a>是当用户访问扩展在扩展管理器内置的扩展选项页面时内嵌显示的页面。</li>
如果可以的话，请一并帮助移除这几个链接的 `https://developer.mozilla.org` 前缀（在原分至上提交新的commit即可）

2022-03-26 10:37 UTC, tolerious commented on files/zh-cn/mozilla/add-ons/webextensions/anatomy_of_a_webextension/index.html
> + <li><a href="https://developer.mozilla.org/zh-CN/docs/Mozilla/Add-ons/WebExtensions/user_interface/Options_pages">选项页面</a>是当用户访问扩展在扩展管理器内置的扩展选项页面时内嵌显示的页面。</li>
👌🏻

2022-03-26 11:24 UTC, tolerious commented on files/zh-cn/mozilla/add-ons/webextensions/anatomy_of_a_webextension/index.html
> + <li><a href="https://developer.mozilla.org/zh-CN/docs/Mozilla/Add-ons/WebExtensions/user_interface/Options_pages">选项页面</a>是当用户访问扩展在扩展管理器内置的扩展选项页面时内嵌显示的页面。</li>
> 如果可以的话，请一并帮助移除这几个链接的 `https://developer.mozilla.org` 前缀（在原分至上提交新的commit即可）

already done.

2022-03-26 12:24 UTC, tolerious commented on files/zh-cn/mozilla/add-ons/webextensions/anatomy_of_a_webextension/index.html
> + <li><a href="https://developer.mozilla.org/zh-CN/docs/Mozilla/Add-ons/WebExtensions/user_interface/Options_pages">选项页面</a>是当用户访问扩展在扩展管理器内置的扩展选项页面时内嵌显示的页面。</li>
> 如果可以的话，请一并帮助移除这几个链接的 `https://developer.mozilla.org` 前缀（在原分至上提交新的commit即可）

另外发现中文页面与英文原版的排版也有不少差异，这两天继续完善。

2022-03-26 15:24 UTC, tolerious commented on files/zh-cn/mozilla/add-ons/webextensions/anatomy_of_a_webextension/index.html
> + <li><a href="https://developer.mozilla.org/zh-CN/docs/Mozilla/Add-ons/WebExtensions/user_interface/Options_pages">选项页面</a>是当用户访问扩展在扩展管理器内置的扩展选项页面时内嵌显示的页面。</li>
> 如果可以的话，请一并帮助移除这几个链接的 `https://developer.mozilla.org` 前缀（在原分至上提交新的commit即可）

@yin1999  

1. 对照英文原版页面，把其中不符合内容的部分做了增删，对部分内容进行了翻译；
2. 翻译版中的图片已经与原版不符，从原版处拷贝过来了图片。

2022-03-27 01:36 UTC, yin1999 requested changes

2022-03-27 01:36 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/anatomy_of_a_webextension/index.html
> + <li><a href="/zh-CN/Add-ons/WebExtensions/Anatomy_of_a_WebExtension#Background_scripts">后台脚本</a>: 执行一个长时间运行的逻辑。</li>
该链接的 anchor 不正确，同时，其指向自身的特定 id，请参照修改：

href: `/zh-CN/Add-ons/WebExtensions/Anatomy_of_a_WebExtension#Background_scripts` -> `#后台脚本`

2022-03-27 01:36 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/anatomy_of_a_webextension/index.html
> + <li><a href="/zh-CN/Add-ons/WebExtensions/Anatomy_of_a_WebExtension#Content_scripts">内容脚本</a>: 扩展中包含的JavaScript，你可以注入它们到网页中。</li>
同上一条意见：

- `/zh-CN/Add-ons/WebExtensions/Anatomy_of_a_WebExtension#sidebars_popups_and_options_pages` -> `#侧边栏，弹出窗口，选项页面`
- `/zh-CN/Add-ons/WebExtensions/Anatomy_of_a_WebExtension#Content_scripts` -> `#内容脚本`

2022-03-27 01:36 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/anatomy_of_a_webextension/index.html
> +<h2 id="Background_scripts">后台脚本</h2>
这里无需修改，未来若要将此文档转换为 markdown 格式，其 id 将为中文（会影响其它页面对该内容的引用）。

2022-03-27 01:36 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/anatomy_of_a_webextension/index.html
> +<p>后台脚本将在扩展加载完毕后开始运行，直到扩展被禁用或卸载。只要获得了相应的<a href="/zh-CN/Add-ons/WebExtensions/manifest.json/permissions">权限</a>，你就可以在脚本中使用任何 <a href="/zh-CN/Add-ons/WebExtensions/API">WebExtension API</a>。</p>
请帮助更新链接：

- `/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions`
- `/zh-CN/docs/Mozilla/Add-ons/WebExtensions/API`

2022-03-27 01:36 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/anatomy_of_a_webextension/index.html
> +  <p><strong>警告:</strong> 在Firefox浏览器中，后台页面不支持使用<a href="/zh-CN/docs/Web/API/Window/alert"><code> alert() </code></a>,<a href="/zh-CN/docs/Web/API/Window/alert"><code> confirm() </code></a>和<a href="
请移除 `<code>` 内的空格，并在该链接前添加空格：

```html
  <p><strong>警告：</strong> 在Firefox浏览器中，后台页面不支持使用 <a href="/zh-CN/docs/Web/API/Window/alert"><code>alert()</code></a>、<a href="/zh-CN/docs/Web/API/Window/alert"><code>confirm()</code></a> 和 <a href="/zh-CN/docs/Web/API/Window/alert"><code>prompt()</code></a></p>
```

2022-03-27 01:36 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/anatomy_of_a_webextension/index.html
> +<p>详情请参考<a href="/zh-CN/Add-ons/WebExtensions/Content_Security_Policy">内容安全策略</a>。</p>
请一并帮助更新链接：`/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Content_Security_Policy`

2022-03-27 01:36 UTC, yin1999 commented on files/zh-cn/mozilla/add-ons/webextensions/anatomy_of_a_webextension/index.html
> + <li><a href="/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#communicating_with_background_scripts">通过与后台脚本交换信息</a>的方式，间接地使用所有 WebExtension API </li>
anchor 不正确，请更新：`/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#后台脚本通信`

2022-03-27 01:50 UTC, tolerious commented on files/zh-cn/mozilla/add-ons/webextensions/anatomy_of_a_webextension/index.html
> + <li><a href="/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#communicating_with_background_scripts">通过与后台脚本交换信息</a>的方式，间接地使用所有 WebExtension API </li>
> anchor 不正确，请更新：`/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#后台脚本通信`

👌🏻

2022-03-27 02:35 UTC, tolerious commented on files/zh-cn/mozilla/add-ons/webextensions/anatomy_of_a_webextension/index.html
> + <li><a href="/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#communicating_with_background_scripts">通过与后台脚本交换信息</a>的方式，间接地使用所有 WebExtension API </li>
> anchor 不正确，请更新：`/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#后台脚本通信`

@yin1999    上述问题均已更正。

2022-03-27 04:28 UTC, cw118 commented
@tolerious there's no need to worry about the "fallback to en-US" flaws, that **doesn't** mean the links should be changed to `/en-US/` — please do **keep them pointed to `/zh-CN/`** (I explained briefly on Matrix, would be happy to clarify more if needed :) )

2022-03-27 07:06 UTC, tolerious commented
> @tolerious there's no need to worry about the "fallback to en-US" flaws, that **doesn't** mean the links should be changed to `/en-US/` — please do **keep them pointed to `/zh-CN/`** (I explained briefly on Matrix, would be happy to clarify more if needed :) )

Thanks for your suggestion，I'll fix .  😄

2022-03-27 12:38 UTC, merged