「プロパティアクセサー」を更新
mdn/translated-content pull request #489
Opened 2021-04-12 16:20 UTC by mfuji09

2021/02/20 時点の英語版に基づき更新

2021-04-14 12:39 UTC, potappo requested changes
1箇所、翻訳漏れを指摘しましたので、お願いします。

2021-04-14 12:39 UTC, potappo commented on files/ja/web/javascript/reference/operators/property_accessors/index.html
> +<h2 id="Examples">Examples</h2>
「例」と訳して良いのではないでしょうか。

2021-04-15 00:12 UTC, mfuji09 commented on files/ja/web/javascript/reference/operators/property_accessors/index.html
> +<h2 id="Examples">Examples</h2>
おっと、翻訳から漏れていたようです。ご指摘ありがとうございます！

2021-04-15 00:16 UTC, mfuji09 commented
修正しました。ご確認をお願いします。

2021-04-15 12:19 UTC, potappo approved these changes
OK です。

2021-04-15 12:19 UTC, merged