web/html/element/input/date/index.html [es]
mdn/translated-content pull request #4903
Opened 2022-03-30 18:51 UTC by hectormoba

Fixed problems with macro {{page}} and translated all new content. Some considerations:

- Step section is confusing when we are translating in to Spanish. Feel free to propose changes that improve this section. 
- I've left a link to English content due to Spanish content is not created. 
- Wikipedia link content at the bottom of this page is in English as well.

2022-03-30 19:51 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +Una {{domxref("DOMString")}} representando la fecha introducida en la entrada. La fecha es formateada siguiendo el ISO8601, descrito en {{SectionOnPage("/es/docs/Web/HTML/Date_and_time_formats", Form
```suggestion
Una {{domxref("DOMString")}} representando la fecha introducida en la entrada. La fecha es formateada siguiendo el ISO8601, descrito en {{SectionOnPage("/es/docs/Web/HTML/Date_and_time_formats", "Formato válido de una fecha en formato de texto")}} (en inglés).
```

2022-03-30 20:14 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +> **Nota:** Cuando los datos introducidos por el usuario no siguen la configuración del stepping, puede que el {{Glossary("user agent")} lo redondeé al valor válido más cercanos, prefiriendo valores
```suggestion
> **Nota:** Cuando los datos introducidos por el usuario no siguen la configuración del stepping, puede que el {{Glossary("user agent")}} lo redondeé al valor válido más cercanos, prefiriendo valores mayores cuando hay dos opciones iguales cercanas.
```

2022-03-30 21:07 UTC, hectormoba commented on files/es/web/html/element/input/date/index.md
> +> **Nota:** Cuando los datos introducidos por el usuario no siguen la configuración del stepping, puede que el {{Glossary("user agent")} lo redondeé al valor válido más cercanos, prefiriendo valores
Gracias @Graywolf9!

2022-03-31 02:30 UTC, JuanVqz requested changes
@hectormoba muchas gracias por contribuir! es un tema super importante y bastante entretenido de leer, te hice unos comentarios y en especial marque una sugerencia como "obligatoria" por que puede que el build tenga errores si no aplicamos ese cambio, :1st_place_medal:

2022-03-31 02:30 UTC, JuanVqz commented on files/es/web/html/element/input/date/index.md
> +Una {{domxref("DOMString")}} representando la fecha introducida en la entrada. La fecha es formateada siguiendo el ISO8601, descrito en {{SectionOnPage("/es/docs/Web/HTML/Date_and_time_formats", "For
Por que agregaste `(en inglés)` sientes que queda más claro?
```suggestion
Una {{domxref("DOMString")}} representando la fecha introducida en la entrada. La fecha es formateada siguiendo el ISO8601, descrito en {{SectionOnPage("/es/docs/Web/HTML/Date_and_time_formats", "Formato válido de una fecha en formato de texto")}}.
```

2022-03-31 02:30 UTC, JuanVqz commented on files/es/web/html/element/input/date/index.md
> +La última fecha a aceptar. Si el {{htmlattrxref("value", "input")}} introducido en el elemento es posterior, el elemento no pasa la [validación de restricción](/en-US/docs/Web/Guide/HTML/Constraint_v
```suggestion
La última fecha a aceptar. Si el {{htmlattrxref("value", "input")}} introducido en el elemento es posterior, el elemento no pasa la [validación de restricción](/es/docs/Web/Guide/HTML/Constraint_validation) (en inglés). Si el valor del atributo `max` es un valor que no es una posible fecha en el formato de cadena de texto `aaaa-mm-dd`, el elemento no tendrá un valor máximo.
```

2022-03-31 02:30 UTC, JuanVqz commented on files/es/web/html/element/input/date/index.md
> +La fecha más temprana a aceptar. Si el {{htmlattrxref("value", "input")}} introducido en el elemento es anterior, el elemento no pasa la [validación de restricció](/en-US/docs/Web/Guide/HTML/Constrai
```suggestion
La fecha más temprana a aceptar. Si el {{htmlattrxref("value", "input")}} introducido en el elemento es anterior, el elemento no pasa la [validación de restricció](/es/docs/Web/Guide/HTML/Constraint_validation) (en inglés). Si el valor del atributo `max` es un valor que no es una posible fecha en el formato de cadena de texto `aaaa-mm-dd`, el elemento no tendrá un valor mínimo.
```

2022-03-31 02:30 UTC, JuanVqz commented on files/es/web/html/element/input/date/index.md
> +`<input type="date">`no soporta los atribuos de tamaño como por {{htmlattrxref("size", "input")}}. Mejor usa [CSS](/es/docs/Web/CSS) para adaptar su tamaño.
```suggestion
`<input type="date">`no soporta los atributos de tamaño como lo es {{htmlattrxref("size", "input")}}. Mejor usa [CSS](/es/docs/Web/CSS) para adaptar su tamaño.
```

2022-03-31 02:30 UTC, JuanVqz commented on files/es/web/html/element/input/date/index.md
> +Por defecto, `<input type="date">` no valida su valor más allá de su formato. Generalmente, las interfaces no te dejean introducir nada que no sea una fecha (lo que es de ayuda), pero tu puedes dejar
```suggestion
Por defecto, `<input type="date">` no valida su valor más allá de su formato. Generalmente, las interfaces no te dejean introducir nada que no sea una fecha (lo que es de ayuda), pero tu puedes dejar el campo vacío o entrar una fecha inválida (como 32 de abril) en los navegadores que no soportan el tipo `date`, cuando el tipo `date` retrocede a `text`.
```

2022-03-31 02:30 UTC, JuanVqz commented on files/es/web/html/element/input/date/index.md
> +Este es el CSS usado en el ejemplo de arriba. Hacemos uso de los [pseudo-elementos](/es/docs/Web/CSS/Pseudo-elements) {{cssxref(":valid")}} y {{cssxref(":invalid")}} para añadir un icono al lado de l
Este cambio es requerido

```suggestion
Este es el CSS usado en el ejemplo de arriba. Hacemos uso de los [pseudo-elementos](/es/docs/Web/CSS/Pseudo-elements) {{cssxref(":valid")}} y {{cssxref(":invalid")}} para añadir un icono al lado de la entrada, basándonos en si el valor es válido o no. Tuvimos que poner el icono en un {{htmlelement("span")}} y no dentro de la propia entrada, porque, al menos en Chrome, el contenido generado por las entradas está dentro del control del form y no puede ser puede ser mostrardo o dársele estilos correctamente.
```

2022-03-31 02:30 UTC, JuanVqz commented on files/es/web/html/element/input/date/index.md
> +Si lo intentas mandar, verás que el navegador muestra un error y destaca la entrada como inválida si tu entrada no sigue el patrón ` ####-##-##` (donde `#`son digitos del 0 al 9). Por supuesto, esto
```suggestion
Si lo intentas mandar, verás que el navegador muestra un error y destaca la entrada como inválida si tu entrada no sigue el patrón `####-##-##` (donde `#`son digitos del 0 al 9). Por supuesto, esto no impide a los usuarios de introducir fechas inválidas o formatos incorrectos. Así que seguimos teniendo un problema.
```

2022-03-31 02:30 UTC, JuanVqz commented on files/es/web/html/element/input/date/index.md
> +Para este ejemplo, creamos un nuevo elemento {{htmlelement("input")}} e intentamos establecer su `type`a `date`, entonces inmediatamente comprobamos cuál es si tipo (los navegadores sin soporte retor
```suggestion
Para este ejemplo, creamos un nuevo elemento {{htmlelement("input")}} e intentamos establecer su `type` a `date`, entonces inmediatamente comprobamos cuál es su tipo (los navegadores sin soporte retornarán `text`, ya que el tipo `fecha` regresa el tipo `text`). Si `<input type="date">` no es soportada, ocultamos el menu de selección nativo y mostramos el elemento ({{htmlelement("select")}}).
```

2022-04-01 14:41 UTC, hectormoba commented on files/es/web/html/element/input/date/index.md
> +Una {{domxref("DOMString")}} representando la fecha introducida en la entrada. La fecha es formateada siguiendo el ISO8601, descrito en {{SectionOnPage("/es/docs/Web/HTML/Date_and_time_formats", "For
Siento que le ahorras la usuario el tener que comprobar que está o no inglés. Y creo que antes MDN lo aclaraban. Pero veo que en la documentación nueva no se estila. Podemos convenir no ponerlo. Pero estaría bien que tuvieramos una sola linea de actuación.

2022-04-01 15:05 UTC, JuanVqz commented on files/es/web/html/element/input/date/index.md
> +Una {{domxref("DOMString")}} representando la fecha introducida en la entrada. La fecha es formateada siguiendo el ISO8601, descrito en {{SectionOnPage("/es/docs/Web/HTML/Date_and_time_formats", "For
Creo que eso lo agrega una macro en yira cuando el link apunta a `en-US`, veamos si alguien tiene una segunda opinion @mdn/yari-content-es

2022-04-01 15:08 UTC, JuanVqz approved these changes
gracias por aplicar los cambios! :+1:

2022-04-07 15:24 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +> **Nota:** El formato mostrado puede ser diferente del `valor` real, ya que la fecha mostrada es formateada _según el idioma del navegador del usuario_, pero el valor analizado es siempre formateado
Cuando esta entre comilla invertida se habla de código y por tanto se deja como tal

```suggestion
> **Nota:** El formato mostrado puede ser diferente del `value` real, ya que la fecha mostrada es formateada _según el idioma del navegador del usuario_, pero el valor analizado es siempre formateado a `aaaa-mm-dd`.
```

2022-04-07 15:27 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +Este código encuentra el primer elmento {{HTMLElement("input")}} el `type` del cuál es `date` y establece su valor a `2017-06-01` (1 de junio de 2017). Entonces, lee el valor de vuelta en formato cad
Sugerencia de redacción

```suggestion
Este código encuentra el primer elmento {{HTMLElement("input")}} donde `type` es `date` y establece su valor a `2017-06-01` (1 de junio de 2017). Entonces, lee el valor de vuelta en formato cadena de texto y número.
```

2022-04-07 15:31 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +La fecha más temprana a aceptar. Si el {{htmlattrxref("value", "input")}} introducido en el elemento es anterior, el elemento no pasa la [validación de restricció](/es/docs/Web/Guide/HTML/Constraint_
```suggestion
La fecha más temprana a aceptar. Si el {{htmlattrxref("value", "input")}} introducido en el elemento es anterior, el elemento no pasa la [validación de restricció](/es/docs/Web/Guide/HTML/Constraint_validation). Si el valor del atributo `max` es un valor que no es una fecha posible en el formato de cadena de texto `aaaa-mm-dd`, el elemento no tendrá un valor mínimo.
```

2022-04-07 15:33 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +El atributo `step` es un número que especifica la granularidad que un valor debe seguir o el valor especial `any`, el cuál está descrito más abajo. Solo los valores que son iguales a la base para hac
Faltó traducción

```suggestion
El atributo `step` es un número que especifica la granularidad que un valor debe seguir o el valor especial `any`, el cuál está descrito más abajo. Solo los valores que son iguales a la base para ir avanzando ([`min`](#min) si está especificado, sino {{htmlattrxref("value", "input")}}, o un valor por defecto apropiado si ninguno de estos dos es especificado) son válidos.
```

2022-04-07 15:34 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +> **Nota:** Cuando los datos introducidos por el usuario no siguen la configuración del stepping, puede que el {{Glossary("user agent")}} lo redondeé al valor válido más cercanos, prefiriendo valores
Faltó traducción

```suggestion
> **Nota:** Cuando los datos introducidos por el usuario no siguen la configuración de avance, puede que el {{Glossary("user agent")}} lo redondeé al valor válido más cercanos, prefiriendo valores mayores cuando hay dos opciones iguales cercanas.
```

2022-04-07 15:39 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +    Enter your birthday:
Opcional: los textos de los ejemplos que no afecten funcionalidad pueden ser traducidos

```suggestion
    Ingresa tu fecha de nacimiento:
```

2022-04-07 15:39 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +  <p><button>Submit</button></p>
```suggestion
  <p><button>Enviar</button></p>
```

2022-04-07 15:42 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +Tu puedes usar los atributos {{htmlattrxref("min", "input")}} y {htmlattrxref("max", "input")}} para restringir qué fechas puede introducir el usuario. En el siguiente ejemplo, establecemos la fecha
Faltó llave de apertura

```suggestion
Tu puedes usar los atributos {{htmlattrxref("min", "input")}} y {{htmlattrxref("max", "input")}} para restringir qué fechas puede introducir el usuario. En el siguiente ejemplo, establecemos la fecha mínima a `2017-04-01` y la fecha máxima a `2017-04-30`:
```

2022-04-07 15:42 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +    >Choose your preferred party date:
```suggestion
    >Elige tu fecha preferida de fiesta:
```

2022-04-07 15:45 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +Por defecto, `<input type="date">` no valida su valor más allá de su formato. Generalmente, las interfaces no te dejean introducir nada que no sea una fecha (lo que es de ayuda), pero tu puedes dejar
Mejora de traducción

```suggestion
Por defecto, `<input type="date">` no valida su valor más allá de su formato. Generalmente, las interfaces no te dejean introducir nada que no sea una fecha (lo que es de ayuda), pero tu puedes dejar el campo vacío o entrar una fecha inválida (como 32 de abril) en los navegadores que no soportan el tipo `date`, cuando el tipo `date` regresa un tipo `text`.
```

2022-04-07 15:47 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +Si tu usas {{htmlattrxref("min", "input")}} y {htmlattrxref("max", "input")}} para limitar la disponibilidad de las fechas (véase [Estipulando valores de fecha máximos y mínimos](#estipulando_valores
Faltó llave de apertura

```suggestion
Si tu usas {{htmlattrxref("min", "input")}} y {{htmlattrxref("max", "input")}} para limitar la disponibilidad de las fechas (véase [Estipulando valores de fecha máximos y mínimos](#estipulando_valores_de_fecha_máximos_y_mínimos)), los navegadores que lo soporten mostrarán un error si tu tratas de enviar una fecha que está por fuera de los límietes. A pesar de esto, tú necesitarás comprobar de nuevo el resultado enviado para asegurarte que el valor está entre esas fechas, si el menú de selección de fechas no está completamente soportado en el dispositivo del usuario.
```

2022-04-07 15:50 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +    Choose your preferred party date (required, April 1st to 20th):
```suggestion
    Elige tu fecha preferida de fiesta (obligatorio, del 1 al 20 de Abril):
```

2022-04-07 15:51 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +Si tu intentas enviar el formulario con una fecha incomplenta (o una fecha por fuera de los límites), el navegador mostrará un error. Intenta probar con el ejemplo:
Typos

```suggestion
Si intentas enviar el formulario con una fecha incompleta (o una fecha por fuera de los límites), el navegador mostrará un error. Intenta probar con el ejemplo:
```

2022-04-07 15:53 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +Este es el CSS usado en el ejemplo de arriba. Hacemos uso de los [pseudo-elementos](/es/docs/Web/CSS/Pseudo-elements) {{cssxref(":valid")}} y {{cssxref(":invalid")}} para añadir un icono al lado de l
Redacción
Typos
form no esta entre comillas por lo que hablamos del formulario

```suggestion
Este es el CSS usado en el ejemplo de arriba. Hacemos uso de los [pseudo-elementos](/es/docs/Web/CSS/Pseudo-elements) {{cssxref(":valid")}} e {{cssxref(":invalid")}} para añadir un icono al lado de la entrada, basándonos en si el valor es válido o no. Tuvimos que poner el icono en un {{htmlelement("span")}} y no dentro de la propia entrada, porque, al menos en Chrome, el contenido generado por las entradas está dentro del control del formulario y no puede ser puede ser mostrado o darle estilos correctamente.
```

2022-04-07 15:55 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +Los navegadores que no la soportan, degradan el tipo a texto, creando un problema de constencia en la interfaz de usuario (los controles mostrados son diferentes) y en el manejo de los datos.
typos

```suggestion
Los navegadores que no la soportan, degradan al tipo a texto, creando un problema de consistencia en la interfaz de usuario (los controles mostrados son diferentes) y en el manejo de los datos.
```

2022-04-07 15:57 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +El segundo problema es uno más serio: con la entrada de tipo fecha, el valor es normalizado al formato `yyyy-mm-dd`. Pero con la entrada de tipo texto, el navegador no sabe reconocer en qué formato d
Ya habías traducido `yyyy-mm-dd` a `aaaa-mm-dd` para mantener consistencia manejar todos de la misma forma

```suggestion
El segundo problema es uno más serio: con la entrada de tipo fecha, el valor es normalizado al formato `aaaa-mm-dd`. Pero con la entrada de tipo texto, el navegador no sabe reconocer en qué formato debe estar la fecha, y existen diferentes formantos en que las personas escriben fechas, como:
```

2022-04-07 16:20 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +- `Mes dd, yyyy`
```suggestion
- `ddmmaaaa`
- `dd/mm/aaaa`
- `mm/dd/aaaa`
- `dd-mm-aaaa`
- `mm-dd-aaaa`
- `Mes dd, aaaa`
```

2022-04-07 16:28 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +    >Enter your birthday:
```suggestion
    >Ingresa tu fecha de nacimiento:
```

2022-04-07 16:30 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +    <button>Submit</button>
```suggestion
    <button>Enviar</button>
```

2022-04-07 16:31 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +Si lo intentas mandar, verás que el navegador muestra un error y destaca la entrada como inválida si tu entrada no sigue el patrón `####-##-##` (donde `#`son digitos del 0 al 9). Por supuesto, esto n
typo

```suggestion
Si lo intentas mandar, verás que el navegador muestra un error y destaca la entrada como inválida si tu entrada no sigue el patrón `####-##-##` (donde `#` son digitos del 0 al 9). Por supuesto, esto no impide a los usuarios de introducir fechas inválidas o formatos incorrectos. Así que seguimos teniendo un problema.
```

2022-04-07 16:33 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +</form>
```suggestion
<form>
  <div class="nativeDatePicker">
    <label for="bday">Ingresa tu fecha de nacimiento:</label>
    <input type="date" id="bday" name="bday" />
    <span class="validity"></span>
  </div>
  <p class="fallbackLabel">Ingresa tu fecha de nacimiento:</p>
  <div class="fallbackDatePicker">
    <span>
      <label for="day">Día:</label>
      <select id="day" name="day"></select>
    </span>
    <span>
      <label for="month">Mes:</label>
      <select id="month" name="month">
        <option selected>Enero</option>
        <option>Febrero</option>
        <option>Marzo</option>
        <option>Abril</option>
        <option>Mayo</option>
        <option>Junio</option>
        <option>Julio</option>
        <option>Agosto</option>
        <option>Septiembre</option>
        <option>Octubre</option>
        <option>Noviembre</option>
        <option>Diciembre</option>
      </select>
    </span>
    <span>
      <label for="year">Año:</label>
      <select id="year" name="year"></select>
    </span>
  </div>
</form>
```

2022-04-07 16:43 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +## Compatibilidad en los navegadores
De acuerdo a lo acordado esa es la cadena por defecto: https://github.com/mdn/translated-content/discussions/4029

```suggestion
## Compatibilidad con navegadores
```

2022-04-07 16:45 UTC, Graywolf9 commented on files/es/web/html/element/input/date/index.md
> +- [Compatibilidad con las propiedades CSS](/en-US/docs/Learn/Forms/Property_compatibility_table_for_form_controls)(en inglés)
Poner los enlaces en `es` así el render automáticamente manda a español cuando alguien más cree esas páginas
No es necesario poner "(en inglés)" ya que el render en automático poner (en-US)

```suggestion
- [Tutorial seleccionador de fechas](/es/docs/Learn/Forms/Basic_native_form_controls)
- [Formatos de fecha y tiempo usados en HTML](/es/docs/Web/HTML/Date_and_time_formats)
- [Compatibilidad con las propiedades CSS](/es/docs/Learn/Forms/Property_compatibility_table_for_form_controls)
```

2022-04-07 21:03 UTC, hectormoba commented on files/es/web/html/element/input/date/index.md
> +La última fecha a aceptar. Si el {{htmlattrxref("value", "input")}} introducido en el elemento es posterior, el elemento no pasa la [validación de restricción](/es/docs/Web/Guide/HTML/Constraint_vali
Listo. No lo incluiré en las próximas ediciones!

2022-04-07 21:04 UTC, hectormoba commented on files/es/web/html/element/input/date/index.md
> +El atributo `step` es un número que especifica la granularidad que un valor debe seguir o el valor especial `any`, el cuál está descrito más abajo. Solo los valores que son iguales a la base para hac
Sí. Justo en ese apartado tuve algunos problemas con la tradución. Me gusta el concepto de "avanzar" como traducción al castellano.

2022-04-07 21:07 UTC, hectormoba commented on files/es/web/html/element/input/date/index.md
> +    Enter your birthday:
Pensé que solo debíamos traducir la parte del código que es esencial para hacer entendendible el ejemplo. Prefiero dejarlo en inglés, porque a veces hay partes del código muy largas que no añaden nada al ser traducidas. Pero deberíamos establecer una convención para la traducción y seguirla.

2022-04-07 21:09 UTC, hectormoba commented on files/es/web/html/element/input/date/index.md
> +Tú también puedes usar el atributo {{htmlattrxref("required", "input")}} para que completar la fecha sea obligatorio (un error se mostrará si queremos mandar una fecha vacía). Esto debería funcionar
jaja un poco sí

2022-04-19 22:36 UTC, hectormoba commented
@Vallejoanderson este PR lleva 20 días abierto ¿Cómo podemos avanzar?

2022-04-19 23:55 UTC, JuanVqz commented
> @Vallejoanderson este PR lleva 20 días abierto ¿Cómo podemos avanzar?

@hectormoba gracias por comentar, definitivamente esta listo para fusionarse! muchas gracias @hectormoba :+1:

2022-04-19 23:55 UTC, merged