Web/HTTP/Headers/Date を更新
mdn/translated-content pull request #497
Opened 2021-04-13 16:07 UTC by mfuji09

2021/02/20 時点の英語版に同期

2021-04-17 10:48 UTC, potappo requested changes
指摘の修正をお願いします。

2021-04-17 10:48 UTC, potappo commented on files/ja/web/http/headers/date/index.html
> - <dd>2桁の日番号。例えば "04" または "23"。</dd>
数字の後に半角空白を入れてください。「2桁の」→「2 桁の」
以下でも同様の部分がありますが、それらについてもお願いします。

2021-04-17 13:27 UTC, mfuji09 commented on files/ja/web/http/headers/date/index.html
> - <dd>2桁の日番号。例えば "04" または "23"。</dd>
見落としていました。
修正しましたので、ご確認ください。

2021-04-19 08:59 UTC, potappo approved these changes
OK です。

2021-04-19 08:59 UTC, merged