Intl.PluralRules オブジェクト以下の記事を更新
mdn/translated-content pull request #4996
Opened 2022-04-05 15:18 UTC by mfuji09

2022-04-08 13:42 UTC, potappo approved these changes
誤字を修正しましたので、確認をお願いします。

2022-04-08 13:42 UTC, potappo commented on files/ja/web/javascript/reference/global_objects/intl/pluralrules/supportedlocalesof/index.md
> +**`Intl.PluralRules.supportedLocalesOf()`** メソッドは、ランタイムの既定のロケールのうち、代替する必要なく複数形の書式で対応されているものをが入った配列を返します。
```suggestion
**`Intl.PluralRules.supportedLocalesOf()`** メソッドは、ランタイムの既定のロケールのうち、代替する必要なく複数形の書式で対応されているものが入った配列を返します。
```

2022-04-08 13:43 UTC, potappo requested changes
ラジオボタンの選択ミスしたので再度コメント。

2022-04-08 13:57 UTC, mfuji09 commented on files/ja/web/javascript/reference/global_objects/intl/pluralrules/supportedlocalesof/index.md
> +**`Intl.PluralRules.supportedLocalesOf()`** メソッドは、ランタイムの既定のロケールのうち、代替する必要なく複数形の書式で対応されているものをが入った配列を返します。
ありがとうございます！

2022-04-09 07:06 UTC, potappo approved these changes

2022-04-09 07:06 UTC, merged