add structuredclone
mdn/translated-content pull request #5082
Opened 2022-04-12 14:11 UTC by molang3739

structuredclone

2022-04-12 14:28 UTC, irvin requested changes

2022-04-13 03:14 UTC, molang3739 commented on files/zh-cn/web/api/structuredclone/index.md
> +> **注意:** 一个可能有用的场景是在保存buffer之前先异步的校验里面的数据.
Thanks for the feedback

2022-04-13 05:27 UTC, yin1999 requested changes

2022-04-13 05:27 UTC, yin1999 commented on files/zh-cn/web/api/structuredclone/index.md
> +- [Structured clone algorithm](/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm)
更新链接：`/zh-CN/docs/Web/API/Web_Workers_API/Structured_clone_algorithm`

2022-04-13 08:14 UTC, molang3739 commented on files/zh-cn/web/api/structuredclone/index.md
> +- [Structured clone algorithm](/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm)
done

2022-04-13 08:15 UTC, yin1999 commented on files/zh-cn/web/api/structuredclone/index.md
> +{{参见}}
这处改错了，请还原为 `Compat`，下方的 `## See also` 翻译为 `## 参见`

2022-04-13 08:29 UTC, molang3739 commented on files/zh-cn/web/api/structuredclone/index.md
> +{{参见}}
ok

2022-04-13 08:30 UTC, yin1999 requested changes

2022-04-13 08:30 UTC, yin1999 commented on files/zh-cn/web/api/structuredclone/index.md
> +  - :是一个 {{Glossary("transferable objects")}} (可转移对象：译者注)的数组，里面的 `值` 并没有被克隆，而是被转移到被拷贝对象上.
此处需要修改（直接复制下方代码粘贴即可），另外，请一并将其它的英文标点修改为中文标点：

```markdown
- `value`
  - : 被克隆的对象。可以是任何 [结构化算法类型](/zh-CN/docs/Web/API/Web_Workers_API/Structured_clone_algorithm)。
- `transfer` {{optional_inline}}
  - : 是一个 {{Glossary("transferable objects")}} (可转移对象：译者注)的数组，里面的 `值` 并没有被克隆，而是被转移到被拷贝对象上。
```

2022-04-13 08:30 UTC, yin1999 commented on files/zh-cn/web/api/structuredclone/index.md
> +-   [`core-js`](https://github.com/zloirock/core-js) 已经支持 [`structuredClone`的polyfill](https://github.com/zloirock/core-js#structuredclone)
`-` 后使用一个空格即可

2022-04-13 11:01 UTC, yin1999 requested changes

2022-04-13 11:01 UTC, yin1999 commented on files/zh-cn/web/api/structuredclone/index.md
> +structuredClone(value { transfer })
请保留这里的逗号：

```js
structuredClone(value, { transfer })
```

2022-04-13 11:01 UTC, yin1999 commented on files/zh-cn/web/api/structuredclone/index.md
> +const transferred = structuredClone(uInt8Array { transfer: [uInt8Array.buffer] });
请保留这里的逗号：

```js
const transferred = structuredClone(uInt8Array, { transfer: [uInt8Array.buffer] });
```

2022-04-13 12:16 UTC, molang3739 commented on files/zh-cn/web/api/structuredclone/index.md
> +const transferred = structuredClone(uInt8Array { transfer: [uInt8Array.buffer] });
ok

2022-04-14 06:13 UTC, yin1999 requested changes

2022-04-14 06:13 UTC, yin1999 commented on files/zh-cn/web/api/structuredclone/index.md
> +  - : 被克隆的对象。可以是任何 [结构化算法类型](/zh-CN/docs/Web/API/Web_Workers_API/Structured_clone_algorithm)。
其它地方看着都没问题了，这一处对 `structured-clonable type` 一词的翻译还需修改一下：`结构化克隆支持的类型`，同时可以更新链接到指定的 section（mdn/content#14982）：

```markdown
- : 被克隆的对象。可以是任何[结构化克隆支持的类型](/zh-CN/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#支持的类型)。
```

2022-04-14 07:18 UTC, molang3739 commented on files/zh-cn/web/api/structuredclone/index.md
> +  - : 被克隆的对象。可以是任何 [结构化算法类型](/zh-CN/docs/Web/API/Web_Workers_API/Structured_clone_algorithm)。
ok ,这样改更容易理解一点

2022-04-26 13:12 UTC, merged