/Web/HTML/Element/Heading_Elements 日本語訳が不適切で誤解を生む箇所がある
mdn/translated-content pull request #5093
Opened 2022-04-13 13:32 UTC by debiru

### 対象

- https://developer.mozilla.org/ja/docs/Web/HTML/Element/Heading_Elements
    - この文書全体の文書を修正する。

### 概要

> 複数の &lt;h1> を使用してもエラーにはなりませんが、これは最善の方法とは見なされていません。これは読み上げソフトや SEO で有利です。

前半については原文に "error" なんて表現はないので意味が変わり得る。後半はどのような状態が「有利」なのか全く分からない。

また、どうやら原文ページが更新されていて文章構造が変わっているようなので、それに追従する。

### 備考

- html ファイルだったので md にしました
- table タグの部分は原文でも table タグで書かれていたのでそのままにしました
- 上記概要に関連する部分が、原文では新しい節となっていたので追従しました
- 細かい表現や単語前後のスペースを調整しました

### 関連URL

- https://github.com/mozilla-japan/translation/issues/594

2022-04-15 16:11 UTC, mfuji09 requested changes
翻訳スタイルガイドに従っていない箇所、および英語版との相違点の修正をお願いします。

2022-04-15 16:11 UTC, mfuji09 commented on files/ja/web/html/element/heading_elements/index.md
> +      <th scope="row"><a href="/ja/docs/Web/Guide/HTML/Content_categories">コンテンツカテゴリ</a></th>
「コンテンツカテゴリー」のように長音を使用してください。

2022-04-15 16:11 UTC, mfuji09 commented on files/ja/web/html/element/heading_elements/index.md
> +- [Computer says NO to HTML5 document outline | HTML5 Doctor](https://html5doctor.com/computer-says-no-to-html5-document-outline/)
この部分のリンク見出しが英語版と異なるようですので、合わせてください。

2022-04-15 16:11 UTC, mfuji09 commented on files/ja/web/html/element/heading_elements/index.md
> +```html
英語版とスタイルが異なっていますので、合わせてください。

2022-04-15 16:11 UTC, mfuji09 commented on files/ja/web/html/element/heading_elements/index.md
> +- [MDN "WCAG を理解する ― ガイドライン 1.3 の解説"](/ja/docs/Web/Accessibility/Understanding_WCAG/Perceivable#Guideline_1.3_—_Create_content_that_can_be_presented_in_different_ways)
リンクのフラグメント（#以降）が flaw として報告されているので、すべて小文字にしてください。

2022-04-15 16:11 UTC, mfuji09 commented on files/ja/web/html/element/heading_elements/index.md
> +{{Compat("html.elements.h1")}}
{{Compat}}マクロが英語版と異なります。
冒頭の browser-compat: を反映させるとこのマクロは引数無しで使えるようになりますので、そのようにしてください。

2022-04-16 06:17 UTC, debiru commented on files/ja/web/html/element/heading_elements/index.md
> +- [Computer says NO to HTML5 document outline | HTML5 Doctor](https://html5doctor.com/computer-says-no-to-html5-document-outline/)
- 英語版：Computer says no to the HTML5 outline
- サイト：Computer says NO to HTML5 document outline

英語版のタイトルは誤っているようだったので title 要素内容を取り出し、ついでに ` | HTML Doctor` のようなサイト名もあったほうが分かりやすいと思ったのですが、英語版を正として完全に一致させたほうがよいのでしょうか。

2022-04-16 06:51 UTC, debiru commented on files/ja/web/html/element/heading_elements/index.md
> +      <th scope="row"><a href="/ja/docs/Web/Guide/HTML/Content_categories">コンテンツカテゴリ</a></th>
dd696e7 修正しました。他の箇所も確認しましたが、ガイドラインに反している表記は他には見つけられませんでした。

2022-04-16 06:53 UTC, debiru commented on files/ja/web/html/element/heading_elements/index.md
> +- [Computer says NO to HTML5 document outline | HTML5 Doctor](https://html5doctor.com/computer-says-no-to-html5-document-outline/)
b5b66f4 修正しました。1個目のリンクについて、英語版の表記はサイトと若干差異があるようです。

- 英語版：Computer says no to the HTML5 outline
- サイト：Computer says NO to HTML5 document outline

2022-04-16 06:55 UTC, debiru commented on files/ja/web/html/element/heading_elements/index.md
> +```html
0c885f7 で対応しました。

2022-04-16 06:55 UTC, debiru commented on files/ja/web/html/element/heading_elements/index.md
> +- [MDN "WCAG を理解する ― ガイドライン 1.3 の解説"](/ja/docs/Web/Accessibility/Understanding_WCAG/Perceivable#Guideline_1.3_—_Create_content_that_can_be_presented_in_different_ways)
f00b855 で修正しました。文書内の全てのフラグメントを確認して修正しました。

2022-04-16 06:58 UTC, debiru commented on files/ja/web/html/element/heading_elements/index.md
> +{{Compat("html.elements.h1")}}
914ca8c で対応しました。

このような直接のHTML要素ではない文書で、あるHTML要素の互換性テーブルを表示する場合も `browser-compat:` を使用した方がよいのでしょうか。`compat` に引数を取って扱ったほうが利便性が高いと考えて1回目の修正ではそのままにしておきました。

2022-04-16 12:59 UTC, mfuji09 commented on files/ja/web/html/element/heading_elements/index.md
> +      <th scope="row"><a href="/ja/docs/Web/Guide/HTML/Content_categories">コンテンツカテゴリ</a></th>
対応ありがとうございます。

2022-04-16 13:03 UTC, mfuji09 commented on files/ja/web/html/element/heading_elements/index.md
> +- [Computer says NO to HTML5 document outline | HTML5 Doctor](https://html5doctor.com/computer-says-no-to-html5-document-outline/)
対応ありがとうございます。
英語版のタイトルを翻訳した場合を除き、英語版に合わせるべきだと思います。そうしないと、のちに英語版と見比べたときに、誤っていると見なされてしまうと思います（ちょうど今回の主となる修正部分のように）。
英語版が間違っているのであれば、英語版の方も修正してプルリクエストを出していただければ幸いです。

2022-04-16 13:03 UTC, mfuji09 commented on files/ja/web/html/element/heading_elements/index.md
> +```html
ありがとうございます。

2022-04-16 13:03 UTC, mfuji09 commented on files/ja/web/html/element/heading_elements/index.md
> +- [MDN "WCAG を理解する ― ガイドライン 1.3 の解説"](/ja/docs/Web/Accessibility/Understanding_WCAG/Perceivable#Guideline_1.3_—_Create_content_that_can_be_presented_in_different_ways)
ありがとうございます。

2022-04-16 13:05 UTC, mfuji09 commented on files/ja/web/html/element/heading_elements/index.md
> +{{Compat("html.elements.h1")}}
この文書のように、文書中の互換性テーブルが1つであれば、基本的に browser-compat: を使用した方が良いと思います。
複数の互換性テーブルがある場合は、おっしゃるように compat マクロの引数にしておいた方がいいでしょう。

2022-04-16 13:14 UTC, mfuji09 commented
OKです。

2022-04-16 13:14 UTC, mfuji09 approved these changes
OKです。

2022-04-16 13:14 UTC, merged