Complete translate ko/web/javascript/reference/global_objects/set/values/index.md
mdn/translated-content pull request #5138
Opened 2022-04-18 07:40 UTC by jinbekim

기존의 ko/web/javascript/reference/global_objects/set/values/index.md의 번역을 완료했습니다.

2022-05-05 04:56 UTC, yechoi42 requested changes
안녕하세요. 기여 감사드립니다. 몇 가지 제안을 남겨두었는데, 확인 후 저를 멘션하시거나 제게 다시 리뷰를 요청해주세요.

2022-05-05 04:56 UTC, yechoi42 commented on files/ko/web/javascript/reference/global_objects/set/values/index.md
> +> 따라서, `key()` 페이지는 이곳으로 리다이렉트 됩니다. ({{jsxref("Map")}} 객체와 유사성을 위해)
```suggestion
> **참고:** **`keys()`** 메소드는 이 메소드의 별칭입니다({{jsxref("Map")}} 객체와 유사성을 위해).
> 따라서, `key()` 페이지는 이곳으로 리다이렉트 됩니다. 
```
원문을 보니 괄호안의 내용이 앞문장에 들어가는 것이 적확한듯하여 제안드립니다.
`The keys() method is an alias for this method (for similarity with [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) objects), hence the keys() page redirecting here.`

2022-05-05 04:56 UTC, yechoi42 commented on files/ko/web/javascript/reference/global_objects/set/values/index.md
> +**`values()`** method는 `Set` 객체에 요소가 삽입된 순서대로 각 요소의 값을 순환할 수 있는 [Iterator](/ko/docs/Web/JavaScript/Guide/Iterators_and_Generators) 객체를 반환합니다.
```suggestion
**`values()`** method는 `Set` 객체에 요소가 삽입된 순서대로 각 요소의 값을 순환할 수 있는 새로운 [Iterator](/ko/docs/Web/JavaScript/Guide/Iterators_and_Generators) 객체를 반환합니다.
```
가장 첫번째 있는, 정의하는 문장이어서 원문의 표현을 그대로 담으면 좋을 것 같습니다.

2022-05-05 04:56 UTC, yechoi42 commented on files/ko/web/javascript/reference/global_objects/set/values/index.md
> +주어진 `Set`의 각 요소의 값을 삽입순서대로 가진 배열의 새로운 iterator 객체를 반환합니다.
```suggestion
주어진 `Set`의 각 요소의 값을 삽입 순서대로 포함하는 새로운 iterator 객체
```
원문의 의미와 차이가 있는 듯 하여서 제안드립니다. 더 좋은 표현이 있다면 제안해주세요 :) 
`A new iterator object containing the values for each element in the given Set, in insertion order.`

2022-05-05 07:51 UTC, jinbekim commented
@yechoi42 제안해주신 내용 잘 살펴보았습니다. 제가 첫 작업이다 보니 미숙한 곳이 많았던 것 같습니다.
제안해주신 내용 모두 적합하다 생각되어 수정했습니다. 감사합니다. 👍

2022-05-06 14:31 UTC, yechoi42 reviewed
@jinbekim 님, 이건 제가 지난번에 말씀드리면 더 좋았을 것인데요 조금 번거롭지만 작업을 한 가지 더해주셔야 할 것 같습니다. :(

html에서 md파일로 변환해 기여하는 경우에는 다음과 같은 커밋 방식을 따라야 합니다. `확장자만 html에서 md로 바꾸고 commit 해주세요.` 다음 문서에 자세히 나와있는데요. 기존의 기여 이력을 지키기 위함이라서, 번거로우시겠지만 정리 부탁드립니다. 

https://github.com/mdn/translated-content/blob/main/docs/ko/markdown-guide.md

어렵다고 생각되시면 다시 PR을 열으셔도 괜찮을 것 같습니다. 만약 리뷰어가 자동으로 다른 분께 지정되었다면 저를 리뷰어를 지정하시거나 멘션하시면 빠른 머지 도와드리겠습니다!

2022-05-06 16:07 UTC, jinbekim commented
@yechoi42  제가 다른분의 기여내역을 없앨뻔 했군요. 하나 더 배웁니다. 꼼꼼하게 봐주셔서 너무 감사드립니다. :)

2022-05-07 14:55 UTC, yechoi42 approved these changes
넵 깔끔하게 변경해주셔서 감사합니다~!

2022-05-07 14:56 UTC, merged