[pt-BR] Update figure element
mdn/translated-content pull request #5156
Opened 2022-04-19 03:09 UTC by psergiojr

Bringing pt-BR translation up-to-date.

Since the en-US version has already been converted to Markdown, I took the oportunity and did the same.

Fixes #4694

2022-06-19 14:04 UTC, nathipg requested changes
Obrigada pela contribuição 😁 
Apontei algumas pequenas mudanças, poderia dar uma olhada, por favor?

2022-09-19 00:07 UTC, nathipg approved these changes

2022-09-19 00:08 UTC, nathipg commented
@psergiojr Tudo certo no PR! Poderia resolver o conflito que está tendo com a main, por favor?

2022-11-06 17:10 UTC, josielrocha approved these changes

2022-11-06 17:10 UTC, merged