Перевод filter-function/invert
mdn/translated-content pull request #5209
Opened 2022-04-22 08:32 UTC by lex111

2022-04-22 08:33 UTC, lex111 commented on files/ru/web/css/filter-function/invert/index.md
> +  - : Степень преобразования, заданная в виде целого числа ({{cssxref("&lt;number&gt;")}}) или процента ({{cssxref("&lt;percentage&gt;")}}). Значение `100%` полностью инвертирует цвета, соответственн
Снова в конце непонятные слова...

2022-04-23 14:20 UTC, myshov commented on files/ru/web/css/filter-function/invert/index.md
> +  - : Степень преобразования, заданная в виде целого числа ({{cssxref("&lt;number&gt;")}}) или процента ({{cssxref("&lt;percentage&gt;")}}). Значение `100%` полностью инвертирует цвета, соответственн
Эту фразу нужно перевести как "Лакунарное значение", близкий аналог дефолтных значений https://berjon.com/xmlbp-no-lacunae-values/. Надо будет также добавить в английскую версию страницу в глоссарий

2022-04-23 15:46 UTC, myshov commented on files/ru/web/css/filter-function/invert/index.md
> +  - : Степень преобразования, заданная в виде целого числа ({{cssxref("&lt;number&gt;")}}) или процента ({{cssxref("&lt;percentage&gt;")}}). Значение `100%` полностью инвертирует цвета, соответственн
Открыл issue https://github.com/mdn/content/issues/15283

2022-04-24 16:40 UTC, myshov commented on files/ru/web/css/filter-function/invert/index.md
> +  - : Степень преобразования, заданная в виде целого числа ({{cssxref("&lt;number&gt;")}}) или процента ({{cssxref("&lt;percentage&gt;")}}). Значение `100%` полностью инвертирует цвета, соответственн
[Обнаружил](https://github.com/mdn/content/issues/15283#issuecomment-1107875250), что в CSS спецификации отказались от этого термина. Надо будет везде "lacuna value" заменить на "initial value" (начальное значение)

2022-04-24 16:44 UTC, myshov requested changes

2022-04-24 16:44 UTC, myshov commented on files/ru/web/css/filter-function/invert/index.md
> +[Функция](/ru/docs/Web/CSS/CSS_Functions) [CSS](/ru/docs/Web/CSS) **`invert()`** инвертирует цвета на изображении. Его результатом является {{cssxref("&lt;filter-function&gt;")}}.
```suggestion
[Функция](/ru/docs/Web/CSS/CSS_Functions) [CSS](/ru/docs/Web/CSS) **`invert()`** инвертирует цвета изображения. Его результатом является {{cssxref("&lt;filter-function&gt;")}}.
```

2022-04-24 16:44 UTC, myshov commented on files/ru/web/css/filter-function/invert/index.md
> +  - : Степень преобразования, заданная в виде целого числа ({{cssxref("&lt;number&gt;")}}) или процента ({{cssxref("&lt;percentage&gt;")}}). Значение `100%` полностью инвертирует цвета, соответственн
```suggestion
  - : Степень преобразования, заданная в виде целого числа ({{cssxref("&lt;number&gt;")}}) или процента ({{cssxref("&lt;percentage&gt;")}}). Значение `100%` полностью инвертирует цвета, соответственно `0%` ничего не делает. Значения между `0%` и `100%` является линейными множителями эффектами. Начальное занчение для интерполяции — `0`.
```

2022-04-24 16:44 UTC, myshov commented on files/ru/web/css/filter-function/invert/index.md
> +## See also
```suggestion
## Смотрите также
```

2022-04-24 16:45 UTC, myshov approved these changes

2022-04-24 19:50 UTC, lex111 commented on files/ru/web/css/filter-function/invert/index.md
> +  - : Степень преобразования, заданная в виде целого числа ({{cssxref("&lt;number&gt;")}}) или процента ({{cssxref("&lt;percentage&gt;")}}). Значение `100%` полностью инвертирует цвета, соответственн
Спасибо, хотя я принципе не очень понимаю, зачем эти последние два предложения.

2022-04-24 19:51 UTC, merged

2022-04-25 07:51 UTC, myshov commented on files/ru/web/css/filter-function/invert/index.md
> +  - : Степень преобразования, заданная в виде целого числа ({{cssxref("&lt;number&gt;")}}) или процента ({{cssxref("&lt;percentage&gt;")}}). Значение `100%` полностью инвертирует цвета, соответственн
Для разных фильтров используются разные значения, кажется полезная информация