Fixes links on doc about window.scroll()
mdn/translated-content pull request #5210
Opened 2022-04-22 08:43 UTC by LeMisterV

2022-04-23 09:13 UTC, SphinxKnight commented
Merci beaucoup pour ces corrections @LeMisterV ! Je vois qu'il y a d'autres (petits) problèmes sur cette page, puis-je profiter de cette PR pour pousser un commit afin de la mettre à jour complètement ?

2022-04-24 09:18 UTC, LeMisterV commented
[SphinxKnight](https://github.com/SphinxKnight) Effectivement je me suis contenté de corriger les liens, mais si d'autres corrections peuvent être apportés autant le faire en même temps bien sûr.
Dis moi si je peux faire quelque-chose, je ne connais pas trop les process de contrib mdn....

2022-04-24 12:07 UTC, SphinxKnight commented
> [SphinxKnight](https://github.com/SphinxKnight) Effectivement je me suis contenté de corriger les liens, mais si d'autres corrections peuvent être apportés autant le faire en même temps bien sûr. Dis moi si je peux faire quelque-chose, je ne connais pas trop les process de contrib mdn....

Bonjour, pour le processus de contribution, il y a certains éléments de réponse dans [ce billet](https://tech.mozfr.org/post/2021/03/16/MDN-sur-GitHub-comment-contribuer). Ceci étant noté, au-delà du setup technique, toutes les contributions sont les bienvenues :), une branche par PR et hop on revoit / fusionne :)
C'est la version anglaise qui a le rôle de référence et c'est pour ça qu'ici, je me suis dit que l'occasion était bienvenue pour mettre à jour la page (vue qu'elle est plutôt courte).

N'hésite pas si tu as d'autres questions (sur cette PR, dans une issue, une discussion GitHub ou sur Matrix/Element : https://matrix.to/#/#l10n-fr:mozilla.org)

@cw118 je suis preneur d'une revue avec un œil tiers si tu as le temps prochainement :)

2022-04-24 19:55 UTC, cw118 requested changes
Un commentaire mineur, à part ça tout est bon pour moi :)

2022-04-24 19:55 UTC, cw118 commented on files/fr/web/api/window/scroll/index.md
> +ou
Rien de bloquant mais à mes yeux le "ou" ici risque de passer inaperçu/prêter à confusion, essayons peut-être :

```suggestion
Ou avec `options`&nbsp;:
```

2022-04-24 21:01 UTC, SphinxKnight commented
> Un commentaire mineur, à part ça tout est bon pour moi :)

Bien vu, merci beaucoup 🙇

2022-04-24 21:01 UTC, merged