fix image of linear-gradient in zh-CN docs
mdn/translated-content pull request #5211
Opened 2022-04-22 10:03 UTC by Yayoiqz

Fix this problem：
![infoflow 2022-04-22 18-02-27](https://user-images.githubusercontent.com/23414662/164684857-f511312c-4731-49f2-8285-f8d6307f92ca.png)

2022-04-22 11:22 UTC, yin1999 requested changes

2022-04-22 11:22 UTC, yin1999 commented on files/zh-cn/web/css/gradient/linear-gradient/index.html
> +<p><img alt="linear-gradient.png" src="/zh-cn/web/css/gradient/linear-gradient/linear-gradient.png" style="height: 383px; width: 309px;">渐变线由包含渐变图形的容器的中心点和一个角度来定义的。渐变线上的颜色值是由不同的点来定义，包括起始点，终点，以及两者之间的可
Just use `linear-gradient.png` and **remove the `linear-gradient.png` file** in this commit ([mdn/yari](https://github.com/mdn/yari) will fallback to `en-US` to fetch this image). Additionally, please help to remove the `style` attribute:

```html
<img alt="linear-gradient.png" src="linear-gradient.png">
```

2022-04-29 04:46 UTC, Yayoiqz reviewed
done

2022-05-06 03:21 UTC, fuchunhui approved these changes

2022-05-08 09:27 UTC, merged