update(es): Page for max-block-size CSS
mdn/translated-content pull request #5216
Opened 2022-04-22 14:32 UTC by Eschiclers

Updated from HTML to Markdown
Replaced {{ page }} - #3937

Updated and translated using the original file https://github.com/mdn/content/blob/main/files/en-us/web/css/max-block-size/index.md

2022-04-26 18:23 UTC, Graywolf9 requested changes

2022-04-26 18:23 UTC, Graywolf9 commented on files/es/web/css/max-block-size/index.md
> +Cada vez que usaría normalmente `max-height` o `max-width`, debería usar `max-block-size` para establecer el máximo "alto" del contenido (incluso si esto no es un valor vertical) y `max-inline-size`
Sugerencia de redacción

```suggestion
En los momentos que normalmente utilizaría `max-height` o `max-width`, debería usar `max-block-size` para establecer el "alto" máximo del contenido (incluso si esto no es un valor vertical) y `max-inline-size` para establecer el "ancho" máximo del contenido (aunque esto puede ser vertical en lugar de horizontal). Vea el {{SectionOnPage("/es/docs/Web/CSS/writing-mode", "Ejemplo")}}, que muestra los diferentes modos de escritura en acción.
```

2022-04-26 18:23 UTC, Graywolf9 commented on files/es/web/css/max-block-size/index.md
> +max-block-size: unset;
Los comentarios pueden ser traducidos para ayudar a entender el código

```suggestion
/* Valores de longitud <length> */
max-block-size: 300px;
max-block-size: 25em;

/* Valores de porcentaje <percent> */
max-block-size: 75%;

/* Valores de palabras clave */
max-block-size: none;
max-block-size: max-content;
max-block-size: min-content;
max-block-size: fit-content(20em);

/* Valores globales */
max-block-size: inherit;
max-block-size: initial;
max-block-size: revert;
max-block-size: revert-layer;
max-block-size: unset;
```

2022-04-26 18:23 UTC, Graywolf9 commented on files/es/web/css/max-block-size/index.md
> +  - : Define el `max-block-size` como un valor absoluto.
Para una mejor lectura

```suggestion
  - : Define `max-block-size` como un valor absoluto.
```

2022-04-26 18:23 UTC, Graywolf9 commented on files/es/web/css/max-block-size/index.md
> +  - : Define el `max-block-size` como un porcentaje del tamaño del contenedor en el eje de bloque.
```suggestion
  - : Define `max-block-size` como un porcentaje del tamaño del contenedor en el eje de bloque.
```

2022-04-26 18:23 UTC, Graywolf9 commented on files/es/web/css/max-block-size/index.md
> +  - : El mínimo intrínseco para el `max-block-size`.
```suggestion
  - : El preferido intrínseco para `max-block-size`.
- `min-content`
  - : El mínimo intrínseco para `max-block-size`.
```

2022-04-26 18:23 UTC, Graywolf9 commented on files/es/web/css/max-block-size/index.md
> +Los valores de `writing-mode` afectan al mapeo de `max-block-size` a `max-width` o `max-height` como sigue:
```suggestion
Los valores de `writing-mode` afectan al mapeo de `max-block-size` a `max-width` o `max-height` como a continuación:
```

2022-04-26 18:23 UTC, Graywolf9 commented on files/es/web/css/max-block-size/index.md
> +> **Nota:** Los valores de `writing-mode` `sideways-lr` y `sideways-rl` fueron eliminados de la especificación de escritura de nivel 3 de CSS en el proceso de diseño de sucesión. Pueden ser restaurad
Para mejor redacción

```suggestion
> **Nota:** Los valores de `writing-mode`: `sideways-lr` y `sideways-rl`, fueron eliminados de la especificación de escritura de nivel 3 de CSS en el proceso de diseño de sucesión. Pueden ser restaurados en el nivel 4.
```

2022-04-26 18:23 UTC, Graywolf9 commented on files/es/web/css/max-block-size/index.md
> +<p>Modo de escritura <code>vertical-rl</code> (el valor predeterminado):</p>
```suggestion
<p>Modo de escritura <code>vertical-rl</code>:</p>
```

2022-04-26 22:46 UTC, Eschiclers commented
Estoy de acuerdo con todos los cambios para mejorar la redacción y ya los he añadido @Graywolf9 
Gracias por las sugerencias

2022-04-27 15:02 UTC, Graywolf9 approved these changes

2022-04-27 15:04 UTC, Graywolf9 commented
Muchas gracias por tu tiempo y colaboración !

2022-04-27 15:04 UTC, merged