/web/css/color_value/hexadecimal_rgb の翻訳
mdn/translated-content pull request #5229
Opened 2022-04-23 08:01 UTC by debiru

### 概要

/web/css/color_value/hexadecimal_rgb の新規翻訳

### 備考

- 値のセクションで、「赤」などが英語版ではアンダースコア（em）でマークアップされていたけれど、日本語だと em は見づらいのでアスタリスク（strong）でマークアップした。
- 別のCSS文書へのリンクを `cssxref` で書こうかとも思ったけれど、`<color>` の括弧がそのまま書けなかった（`&lt;` などと書くのは面倒だった）のと、英語版が `cssxref` を使っていなかったので、markdown のリンク構文でそのまま書いた。

### 関連URL

- https://github.com/mozilla-japan/translation/issues/600

2022-04-24 13:47 UTC, mfuji09 requested changes
1か所だけ、修正をお願いします。

2022-04-24 13:47 UTC, mfuji09 commented on files/ja/web/css/color_value/hexadecimal_rgb/index.md
> +**16進カラー構文**は [sRGB](/ja/docs/Glossary/RGB) カラーを 16 進数で記述するための記法で、その原色成分（赤、緑、青）と透明度を記述します。[`<color>`](/ja/docs/Web/CSS/color_value) 型が許容される箇所であればどこでも使うことができます。
数字と日本語の間に空白が入っていない箇所がありました。
```suggestion
**16 進カラー構文**は [sRGB](/ja/docs/Glossary/RGB) カラーを 16 進数で記述するための記法で、その原色成分（赤、緑、青）と透明度を記述します。[`<color>`](/ja/docs/Web/CSS/color_value) 型が許容される箇所であればどこでも使うことができます。
```

2022-04-24 14:13 UTC, debiru commented on files/ja/web/css/color_value/hexadecimal_rgb/index.md
> +**16進カラー構文**は [sRGB](/ja/docs/Glossary/RGB) カラーを 16 進数で記述するための記法で、その原色成分（赤、緑、青）と透明度を記述します。[`<color>`](/ja/docs/Web/CSS/color_value) 型が許容される箇所であればどこでも使うことができます。
Commit suggestion ありがとうございます。その箇所だけのようだったので GitHub 上からコミットを取り込みました。

2022-04-26 00:46 UTC, mfuji09 commented
修正ありがとうございます。
修正が完了したら、右上の Reviewers のところで再レビュー依頼マーク（右回りの矢印）をクリックしておいていただけると、早く確認ができます。

2022-04-26 00:46 UTC, merged

2022-04-26 05:34 UTC, debiru commented
> 修正が完了したら、右上の Reviewers のところで再レビュー依頼マーク（右回りの矢印）をクリックしておいていただけると、早く確認ができます。

なるほど、把握しておらず失礼いたしました。承知いたしました。ご対応ありがとうございます。