translate(ja): add new translate of `Glossary/Deep_copy`
mdn/translated-content pull request #5280
Opened 2022-04-26 12:41 UTC by yoshinorin

refs: https://github.com/mozilla-japan/translation/issues/601

https://developer.mozilla.org/en-US/docs/Glossary/Deep_copy の新規翻訳です。

2022-04-26 15:07 UTC, mfuji09 requested changes
リンク先について、修正をお願いします。

2022-04-26 15:07 UTC, mfuji09 commented on files/ja/glossary/deep_copy/index.md
> +この振る舞いは [shallow copy](/en-US/docs/Glossary/Shallow_copy) とは対照的で、コピー元かコピー先のどちらかを変更すると他のオブジェクトも変更される可能性があります。（なぜならば、それら2つのオブジェクトは参照を共有しているためです）
リンクは /en-US/ ではなく /ja/ に対して行うようお願いします。
まだ該当ページが日本語版にない場合でも、 /ja/ にリンクするようにしてください。エラーになりますが、英語版にフォールバックされ、リンク先が未翻訳であることが明確になります。

2022-04-27 11:45 UTC, yoshinorin commented on files/ja/glossary/deep_copy/index.md
> +この振る舞いは [shallow copy](/en-US/docs/Glossary/Shallow_copy) とは対照的で、コピー元かコピー先のどちらかを変更すると他のオブジェクトも変更される可能性があります。（なぜならば、それら2つのオブジェクトは参照を共有しているためです）
@mfuji09 
ありがとうございます。 `ja`に変更しました。

2022-04-29 14:38 UTC, mfuji09 approved these changes
OKです。

2022-04-29 14:39 UTC, merged