translate(zh-cn):add about HTMLVideoElement translated
mdn/translated-content pull request #5302
Opened 2022-04-27 07:50 UTC by Jack-Zhang-1314

2022-04-27 13:01 UTC, yin1999 requested changes

2022-04-27 14:06 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/htmlvideoelement/enterpictureinpicture_event/index.md
> +此接口还继承他的父事件 {{domxref("Event")}} 的属性。
这样写会不会有点突兀

2022-04-27 15:00 UTC, yin1999 commented on files/zh-cn/web/api/htmlvideoelement/videoheight/index.md
> +- 媒体所在的容器 (以目标的长宽比为中心匹配的子矩形)。
我明天再看看这句话

2022-04-28 06:58 UTC, yin1999 commented on files/zh-cn/web/api/htmlvideoelement/videoheight/index.md
> +- 媒体所在的容器 (以目标的长宽比为中心匹配的子矩形)。
我搜到了这篇文章：<https://www.theinsidetips.com/tip-1211-what-is-clean-aperture/>

同时咨询了学摄影的同学，`clean aperture` 指的应该是“镜头校正”，用于去除拍摄时视频四个角上较暗的部分，这一是 Apple 专用的一个词汇。因此，这句话可以这样翻译：

```
媒体的镜头校正（以媒体中心点为中心的一个匹配目标长宽比的子矩形；译者注：用于校正媒体四个角上的广角畸变）。
```

2022-04-28 07:57 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/htmlvideoelement/videoheight/index.md
> +- 媒体所在的容器 (以目标的长宽比为中心匹配的子矩形)。
厉害了,这个太专业了o(￣▽￣)ｄ

2022-04-28 08:02 UTC, yin1999 commented
有一个文件的路径有问题：`文件/中华/蹼/应用程序接口/htmlvideoelement/enterpictureinpicture_event/index.md` 了，请使用 `git mv` 重命名文件。

2022-04-28 08:28 UTC, Jack-Zhang-1314 commented
@yin1999 谢谢你,没有你的帮助我完不成这么棒的翻译

2022-04-28 08:35 UTC, yin1999 commented
如果没有**合并冲突**的话，无需合并最新的main分支到这个pr（for next time）

2022-04-28 08:47 UTC, Jack-Zhang-1314 commented
@yin1999 请问我应该怎么在此pr的基础上修改提交呢.原谅我的经验不足

2022-04-28 08:50 UTC, yin1999 commented
> @yin1999 请问我应该怎么在此pr的基础上修改提交呢.原谅我的经验不足

若要撤销最后一次提交（不撤销也不影响），可使用以下的步骤：

1. 在本地同步远程仓库后，使用命令 `git reset HEAD~1 --hard`，硬撤销 `merge commit`
2. 使用命令 `git push origin --force-with-lease` 将本地的分支强制推送到远程仓库（即可撤销最后一次 merge commit）

2022-04-28 09:03 UTC, Jack-Zhang-1314 commented
> 2\. git push origin --force-with-lease

好的,谢谢啦

2022-04-28 09:21 UTC, yin1999 commented
多撤销了一个 commit，使用 `git mv` 重命名文件即可。

2022-04-28 09:22 UTC, Jack-Zhang-1314 commented
> 多撤销了一个 commit，使用 `git mv` 重命名文件即可。

呜呜呜.心态炸裂

2022-04-28 09:37 UTC, Jack-Zhang-1314 commented
@yin1999 如果提交产生的Campare,我需要去做什么吗

2022-04-28 09:39 UTC, yin1999 commented
> @yin1999 如果提交产生的Campare,我需要去做什么吗

不需要，`compare` 是用于帮助 reviewer 完成代码审查的，无需每次重新审查整个文档

2022-04-28 09:42 UTC, yin1999 commented
文件重命名还存在一点问题，你好像是新建了一个 copy，文件名错误的文档没有被移除。

**把文件名错误的文档删除掉即可**

2022-05-03 02:30 UTC, yin1999 commented
因为你使用main分支创建了此pr， `fetch upstream` 会将原仓库的commit推送到这个pr，导致其需要其他本地化团队的 review。请撤销这些commit：

1. `git reset --hard ff5e408` # 撤回本地的提交到 [ff5e408](https://github.com/mdn/translated-content/pull/5302/commits/ff5e408c062580044e10e3b1d0e4bc31a14b33bc) 这个提交记录
2. `git push origin --force-with-lease` 强制推送本地分支到远程，以撤销远程分支中的 commit

2022-05-03 03:46 UTC, Jack-Zhang-1314 commented
@yin1999 这样可以嘛

2022-05-03 04:01 UTC, cw118 commented
@Jack-Zhang-1314 After a quick look. everything seems OK from a git/scope point of view :) 

For future contributions, please be sure to create separate branches and avoid modifying files/opening PRs on `main`, otherwise edits outside of the scope of your pull request will be included whenever you fetch upstream.

2022-05-03 04:07 UTC, Jack-Zhang-1314 commented
@cw118 I'm so sorry. In the future I will create separate branches to avoid causing too much trouble.

2022-05-03 04:08 UTC, cw118 commented
@Jack-Zhang-1314 No worries! Thank you and congratulations in advance for your first contribution here :)

2022-05-03 16:23 UTC, merged