Update index.html
mdn/translated-content pull request #5356
Opened 2022-04-30 15:59 UTC by Jonatandb

2022-05-02 15:38 UTC, Graywolf9 requested changes

2022-05-02 15:38 UTC, Graywolf9 commented on files/es/web/css/syntax/index.html
> +<p>Hay más de <a href="/en-US/docs/Web/CSS/Reference" title="/en-US/docs/Web/CSS/Reference">100 propiedades diferentes</a> en CSS y cerca de un número infinito de diferentes valores. No todos los par
Las url se manejan apuntando al idioma en que estamos `es` ya sea exista o no el contenido, el bot lo redirige automáticamente en caso de no existir y cuando se cree, se corregirá automáticamente

```suggestion
<p>Hay más de <a href="/es/docs/Web/CSS/Reference" title="/es/docs/Web/CSS/Reference">100 propiedades diferentes</a> en CSS y cerca de un número infinito de diferentes valores. No todos los pares de propiedades y valores son permitidos cada propiedad define que valores son válidos. Cuando un valor no es válido para una propiedad específica, la declaración es considerada <em>inválida</em> y es completamente ignorada por el motor del CSS.</p>
```

2022-05-02 15:38 UTC, Graywolf9 commented on files/es/web/css/syntax/index.html
> +<p>Debido a que un elemento de la página puede ser seleccionado por varios selectores, y, por lo tanto, por varias reglas que pueden contener la misma propiedad más de una vez, con diferentes valores
```suggestion
<p>Debido a que un elemento de la página puede ser seleccionado por varios selectores, y, por lo tanto, por varias reglas que pueden contener la misma propiedad más de una vez, con diferentes valores, el estandar CSS define cuál regla tiene precedencia por sobre las otras y debe ser aplicada: esto se conoce como el algoritmo <a href="/es/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance" title="Cascading and inheritance">cascada</a>.</p>
```

2022-05-02 15:38 UTC, Graywolf9 commented on files/es/web/css/syntax/index.html
> + <li><strong>Reglas At</strong> que inician con un símbolo '<code>@</code>' (<code>U+0040 COMMERCIAL AT</code>), seguido de un identificado y luego el resto de la declaración que finaliza con un punt
```suggestion
 <li><strong>Reglas At</strong> que inician con un símbolo '<code>@</code>' (<code>U+0040 COMMERCIAL AT</code>), seguido de un identificador y luego el resto de la declaración que finaliza con un punto y coma (;) por fuera de un bloque o al inicio del próximo bloque. Cada tipo de <a href="/es/docs/Web/CSS/At-rule" title="At-rule">reglas at</a>, definidas por un identificador, tienen su propia sintaxis interna, y semántica por supuesto. Se utilizan para establecer información de meta datos (como {{ cssxref("@charset") }} o {{ cssxref("@import") }}), información condicional (como {{ cssxref("@media") }} o {{ cssxref("@document") }}), o información descrciptiva (como {{ cssxref("@font-face") }}).</li>
```

2022-05-02 15:38 UTC, Graywolf9 commented on files/es/web/css/syntax/index.html
> +<p><a name="nested_statements">Existe otro grupo de declaraciones: las <strong>declaraciones anidadas</strong>. Estas son declaraciones que pueden ser usadas en un subset específico de reglas at (las
Actualización de la url

```suggestion
<p><a name="nested_statements">Existe otro grupo de declaraciones: las <strong>declaraciones anidadas</strong>. Estas son declaraciones que pueden ser usadas en un subset específico de reglas at (las <em>reglas de grupo condicionales</em>). Estas declaraciones sólo aplican si una condición específica se cumple: el contenido de la regla at <code>@media</code> se aplica sólo si el dispositivo en el que el navegador se encuentra corriendo cumple dadas condiciones; el contenido de la regla at <code>@document</code> se aplica sólo si la página actual cumple dadas condiciones, y así. En CSS1 y CSS2.1, sólo los sets de reglas pueden ser usados dentro de reglas de grupo condicionales. Esto era muy restrictivo y se dejó de aplicar en </a><a href="/es/docs/Web/CSS/CSS_Conditional_Rules" title="/es/docs/Web/CSS/CSS_Conditional_Rules"><em>CSS Conditionals Level 3</em></a>. Actualmente, aunque sigue siendo experimental y no es soportado por todos los navegadores, las reglas de grupo condicional pueden contener varios sets de reglas, e incluso, aunque no todas, reglas at.</p>
```

2022-05-02 16:31 UTC, Graywolf9 commented
Hola @Jonatandb muchas gracias por tiempo y contribución, te he dejado algunas observaciones

2022-05-02 16:51 UTC, Jonatandb commented
> Hola @Jonatandb muchas gracias por tiempo y contribución, te he dejado algunas observaciones

Gracias, todo commiteado!

2022-05-03 15:35 UTC, Graywolf9 approved these changes

2022-05-03 15:35 UTC, merged

2022-05-03 15:36 UTC, Graywolf9 commented
Excelente @Jonatandb muchas gracias por tu tiempo y esfuerzo!

2022-05-03 15:49 UTC, Jonatandb commented
> Excelente @Jonatandb muchas gracias por tu tiempo y esfuerzo!

No fue nada, gracias a ustedes por ayudar a traducir y mantener tan excelente contenido! 👏🏻👏🏻👏🏻