mv to .md and sync with english version for Reference/Global_Objects/Object/constru
mdn/translated-content pull request #5361
Opened 2022-05-01 03:40 UTC by fuchunhui

2022-05-04 02:24 UTC, yin1999 requested changes

2022-05-04 02:24 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/object/constructor/index.md
> +如果对象被密封或冻结，那么更改构造不起作用，也不会抛出异常：
```suggestion
如果对象被密封或冻结，那么更改 constructor 将不会起作用，也不会抛出异常：
```

2022-05-04 02:24 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/object/constructor/index.md
> +大多数情况下，此属性用于定义一个**函数构造（function-constructor）**，并使用 **new** 和原型链继承进一步使用它。
好像没有搜到有关“函数构造”这一名词
```suggestion
大多数情况下，此属性用于定义一个**函数的构造函数（function-constructor）**，并使用 **new** 和原型链继承进一步使用它。
```

2022-05-04 02:24 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/object/constructor/index.md
> +## 浏览器兼容
```suggestion
## 浏览器兼容性
```

2022-05-05 04:25 UTC, fuchunhui commented on files/zh-cn/web/javascript/reference/global_objects/object/constructor/index.md
> +**`constructor`** 属性返回创建实例对象 {{jsxref("Object")}} 构造函数的引用。注意，此属性的值是对函数本身的引用，而不是一个包含函数名称的字符串。
同意

2022-05-05 04:26 UTC, fuchunhui commented on files/zh-cn/web/javascript/reference/global_objects/object/constructor/index.md
> +对原始类型来说，如 `1`，`true` 和 `"test"`，该值是只读的。
OK

2022-05-05 04:27 UTC, fuchunhui commented on files/zh-cn/web/javascript/reference/global_objects/object/constructor/index.md
> +打印对象的构造函数
done

2022-05-05 04:29 UTC, fuchunhui commented on files/zh-cn/web/javascript/reference/global_objects/object/constructor/index.md
> +下面这个示例会创建原型 `Tree` 以及该类型的对象 `theTree`，然后打印 `theTree` 对象的 `constructor` 属性。
可以接受，调整为括号注释。

2022-05-05 04:31 UTC, fuchunhui commented on files/zh-cn/web/javascript/reference/global_objects/object/constructor/index.md
> +可以为除了 `null` 和 `undefined` 之外的任何类型分配 `constructor` 属性，因为它们没有相应的构造函数（像 `String`、`Number`、`Boolean` 等），但基本类型不会保留这些更改（也不会抛出异常）。也是同样的原因，基本类型允许设置任何属性（除了 `null` 和 `undefined`），不会产生副作用。就是说，每当把这样的基本类型当成对象使用时
OK。确实是放在括号里表达，更清晰一些。

2022-05-05 06:50 UTC, fuchunhui commented on files/zh-cn/web/javascript/reference/global_objects/object/constructor/index.md
> +大多数情况下，此属性用于定义一个**函数构造（function-constructor）**，并使用 **new** 和原型链继承进一步使用它。
可

2022-05-05 06:51 UTC, fuchunhui commented on files/zh-cn/web/javascript/reference/global_objects/object/constructor/index.md
> +## 浏览器兼容
这里我犹豫了，检查发现，大多数写的是“浏览器兼容”

2022-05-10 05:40 UTC, fuchunhui commented
LGTM

2022-05-10 13:41 UTC, merged