translate(ja): update `Web/HTTP/Headers/X-Forwarded-xxxxx`
mdn/translated-content pull request #5369
Opened 2022-05-01 14:04 UTC by yoshinorin

refs: https://github.com/mozilla-japan/translation/issues/605\

### やったこと

- https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/X-Forwarded-For
    - `html` から `md` に変換  
    - ブラウザ互換性の項を削除 （英語版で削除済みのため）
    - 英語版の内容にあわせて加筆・変更
- https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/X-Forwarded-Host
    - `html` から `md` に変換 
    - ブラウザ互換性の項を削除 （英語版で削除済みのため）
- https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/X-Forwarded-Proto
    - `html` から `md` に変換
    - ブラウザ互換性の項を削除 （英語版で削除済みのため）

2022-05-01 14:08 UTC, yoshinorin commented on files/ja/web/http/headers/x-forwarded-for/index.md
> +クライアントがサーバーに直接接続を行った場合、クライアントのIPアドレスはサーバーに送信されます。（そして、しばしばサーバーのアクセスログに記録されます）しかし、クライアントの接続が[フォワードプロキシ または リバースプロキシ](https://en.wikipedia.org/wiki/Proxy_server)を通過する場合はサーバーは最後のプロキシの IP アドレスしかわからず、ほとんど
> これは最後のプロキシがサーバーの一部としてのロードバランサーである場合に特にあてはまります。

ここの翻訳なのですが、原文は `That’s especially true if the final proxy is a load balancer which is part of the same installation as the server. ` となっており、正確な意味が把握できませんでした。したがって正しい訳となっているのか自信がありません。

> https://github.com/mdn/content/blame/c147168cf4b6b35688ebdc4a627e4944083acfac/files/en-us/web/http/headers/x-forwarded-for/index.md#L21-L23

2022-05-09 15:55 UTC, mfuji09 requested changes
いくつかコメントを入れましたので、修正をお願いします。
なお、コメントは1つ目の記事のみに入れていますが、同様の箇所が2、3番目の記事にもある場合は、そちらの修正もお願いします。

2022-05-09 15:55 UTC, mfuji09 commented on files/ja/web/http/headers/x-forwarded-for/index.md
> +
この空行は英語版になく、不要だと思います

2022-05-09 15:55 UTC, mfuji09 commented on files/ja/web/http/headers/x-forwarded-for/index.md
> +現時点で、仕様書の一部ではありません。このヘッダーの標準化版は {{HTTPHeader("Forwarded")}} ヘッダーです。
原文は Not part of any current specification. ですので、「現行のどの仕様書にも含まれていません」のように訳したほうが良いと思います。

2022-05-09 15:55 UTC, mfuji09 commented on files/ja/web/http/headers/x-forwarded-for/index.md
> +      <td>{{Glossary("Request header", "要求ヘッダー")}}</td>
「要求ヘッダー」→「リクエストヘッダー」の方が良いと思います。
他の2つの記事ではそうなっていますので。

2022-05-10 22:18 UTC, yoshinorin commented
@mfuji09 
ご指摘いただいた点、変更しました。

2022-05-13 14:40 UTC, mfuji09 commented
@yoshinorin さん
ありがとうございました。
なお、修正が終わったら、ページ右上の Reviewers の中で Re-request review のボタン（回転する矢印のボタン）を押しておいていただけると助かります。

2022-05-13 14:40 UTC, mfuji09 approved these changes
OKです。

2022-05-13 14:40 UTC, merged

2022-05-14 04:06 UTC, yoshinorin commented
> なお、修正が終わったら、ページ右上の Reviewers の中で Re-request review のボタン（回転する矢印のボタン）を押しておいていただけると助かります。

ありがとうございます。次回以降押すようにします。