Fix typo: "登录", not "登陆"
mdn/translated-content pull request #5386
Opened 2022-05-03 02:24 UTC by gymgym1212

2022-05-10 13:58 UTC, yin1999 commented on files/zh-cn/glossary/cross-site_scripting/index.html
> +<p>跨站脚本攻击（Cross-site scripting，XSS）是一种安全漏洞，攻击者可以利用这种漏洞在网站上注入恶意的客户端代码。当被攻击者登录网站时就会自动运行这些恶意代码，从而，攻击者可以突破网站的访问权限，冒充受害者。根据开放式 Web 应用安全项目（OWASP），XSS 在 2017 年被认为 <a href="https://owasp.org/www-project-top-
```suggestion
<p>跨站脚本攻击（Cross-site scripting，XSS）是一种安全漏洞，攻击者可以利用这种漏洞在网站上注入恶意的客户端代码。若受害者运行这些恶意代码，攻击者就可以突破网站的访问限制并冒充受害者。根据开放式 Web 应用安全项目（OWASP），XSS 在 2017 年被认为 <a href="https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A7-Cross-Site_Scripting_(XSS)">7 种最常见的 Web 应用程序漏洞之一</a>。</p>
```

2022-05-10 14:44 UTC, t7yang commented
> I don't feel exactly sure about this, there is no **login** nor **landing** at the English doc.
> 
> @yin1999 @t7yang how do you think?

Agree, the change request is mistranslated.

2022-05-10 14:47 UTC, t7yang commented on files/zh-cn/glossary/cross-site_scripting/index.html
> +<p>跨站脚本攻击（Cross-site scripting，XSS）是一种安全漏洞，攻击者可以利用这种漏洞在网站上注入恶意的客户端代码。当被攻击者登录网站时就会自动运行这些恶意代码，从而，攻击者可以突破网站的访问权限，冒充受害者。根据开放式 Web 应用安全项目（OWASP），XSS 在 2017 年被认为 <a href="https://owasp.org/www-project-top-
This one is better 👍

2022-05-10 14:57 UTC, irvin requested changes
@gymgym1212 please change according to the suggestions

2022-05-11 00:52 UTC, gymgym1212 commented
I have applied the suggestion from code review. Now it's clearer.

2022-05-11 06:06 UTC, merged