Rename Learn to md
mdn/translated-content pull request #5459
Opened 2022-05-07 05:15 UTC by alattalatta

- Markdown
  - 스쿼시 병합 하지 말아주세요.
- 43923830923d6be47735e1c5ddb70cc99601be48
  - 내용 변경 없고 외부 링크 업데이트/제거만 했습니다.
    - code.org
      - 한국어 아님
    - programmers.co.kr
      - 대부분의 강의가 유료임

https://github.com/mdn/mdn-community/discussions/65

2022-05-08 00:47 UTC, yujo11 requested changes
안녕하세요 alattalatta님!

함께 얘기 나눠보고 싶은 부분이 있어 코멘트 남겼습니다!

확인 해주시면 감사하겠습니다!

2022-05-08 00:47 UTC, yujo11 commented on files/ko/learn/index.md
> +
code.org 같은 경우는 영어 베이스이긴 하지만 페이지 진입 시에 언어 선택이 가능하고 아동용 컨텐츠에는 한국어 번역 및 자막 작업까지 완료된게 많더라구요.

그래서 조금의 부연 설명과 함께 해당 링크를 남겨놓는게 어떨지 얘기를 나눠보고 싶네용

- ex
```
(기존) 기초 코딩 이론과 연습. 주로 아이들이나 완전 초보자를 대상으로 함 
=> 기초 코딩 이론과 연습. 주로 아이들이나 완전 초보자를 대상으로 함. 현재 전체 프로그램 중 일부만 한국어로 컨텐츠가 제공되는 상태
```

<img width="1664" alt="스크린샷 2022-05-08 오전 9 38 53" src="https://user-images.githubusercontent.com/61097373/167276858-c6e67543-a02a-439e-a3e6-3b8c46b802f2.png">

2022-05-08 05:28 UTC, alattalatta commented on files/ko/learn/index.md
> +
음, 글쎄요, 말씀하신 대로 아동용 콘텐츠는 한국어가 되긴 하는데, MDN 자료를 보고 있을 정도면 블록 코딩을 하고 있을 단계는 아닐 것 같아서요.

2022-05-10 23:04 UTC, yujo11 commented on files/ko/learn/index.md
> +
그것도 그렇네요

이대로 병합하도록 하겠습니다!

2022-05-10 23:04 UTC, yujo11 approved these changes

2022-05-10 23:04 UTC, merged