Translate from original Math.max() (updated content)
mdn/translated-content pull request #5475
Opened 2022-05-07 19:24 UTC by marcelozarate

This PR fixes #3865

2022-05-09 16:00 UTC, Graywolf9 requested changes

2022-05-09 16:00 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/math/max/index.md
> +Ver [apply y funciones built-in](/es/docs/Web/JavaScript/Reference/Global_Objects/Function/apply#apply_and_built-in_functions)
```suggestion
Ver [apply y funciones incorporadas](/es/docs/Web/JavaScript/Reference/Global_Objects/Function/apply#apply_and_built-in_functions)
```

2022-05-09 16:29 UTC, marcelozarate commented on files/es/web/javascript/reference/global_objects/math/max/index.md
> +arreglos construídos programáticamente. Esto debería ser usado solamente para arreglos con
Está bien, mi intuición como hablante de español (AR) era decir "proceduralmente", pero no estaba seguro de la aceptación entre todos los hispanohablantes, ya que no está en el diccionario de la RAE, y luego de consultar [esta respuesta de la RAE](https://twitter.com/raeinforma/status/781799753306796033) me incliné por la misma, pero tampoco estaba convencido. Creo que es una palabra (programatically/procedurally) que debe ir a la parte de las convenciones porque se puede dar mucha confusión con las posibles traducciones (nunca en mi vida había leído u oído procedimental, y quizás en España es la acepción más usada).

2022-05-10 15:34 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/math/max/index.md
> +arreglos construídos programáticamente. Esto debería ser usado solamente para arreglos con
Sí, me pasó lo mismo mientras leía la traducción, en estos casos de duda, recomiendo reestructurar para usar palabras más genéricas y quede clara la idea, retomando que las mejores traducciones son las que se hacen de manera interpretada más que de traducción literal. Respecto a las convenciones no es una palabra tan común en la documentación (cada contribuidor en inglés usa palabras diferentes) por lo que lo dejamos en la reestructura para una mejor comprensión.

Muchas gracias

2022-05-10 15:41 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/math/max/index.md
> +Ver [apply y funciones built-in](/es/docs/Web/JavaScript/Reference/Global_Objects/Function/apply#apply_and_built-in_functions)
Es una excelente idea lo del glosario, muchas gracias!

Y para este caso la nota es (que creo también debería agregar al discoussion XD): 
- Cuando se trata de `código`: no se traduce
- Cuando esta dentro del contexto de la oración y no hace referencia como elemento: se traduce
- Cuando dentro del tema del que habla el documento es más usado en inglés: se puede mantener en inglés en _itálicas_ y en su primer aparición poner entre paréntesis la traducción. p.ej. placeholder
- Cuando se utiliza la palabra en inglés pero el significado puede ser confuso para los lectores: se puede mantener en español colocando entre paréntesis la palabra o frase en inglés.

Estas convenciones pueden ser mejoradas convocando a reunión del equipo revisor.

2022-05-10 15:49 UTC, Graywolf9 approved these changes

2022-05-10 16:03 UTC, merged

2022-05-10 16:04 UTC, Graywolf9 commented
Muchas gracias por tu valioso tiempo y contribución 🥳