/docs/Web/HTML/Element/img の例の画像のリンク切れを修正
mdn/translated-content pull request #5560
Opened 2022-05-11 03:08 UTC by hyakt

mozilla-japan/translation/issues/606

/docs/Web/HTML/Element/img の例の画像を en-US と同様のパスに修正しました。
ご確認よろしくお願いします。

2022-05-16 01:51 UTC, mfuji09 requested changes
画像は追加しなくても英語版が参照されるようになっていますので、画像に変更がなければ削除してくださるようお願いします。

2022-05-16 05:31 UTC, hyakt commented
@mfuji09 
ご確認ありがとうございます。
上記のプレビューに表示されなかったので、必要かなと思い追加したのでしたが不要だったのですね。
[479e17b](https://github.com/mdn/translated-content/pull/5560/commits/479e17bd817f72a8bf9827a5253fe7848ca999f1) のコミットで修正いたしました。

2022-05-17 01:33 UTC, mfuji09 approved these changes
OKです。ありがとうございました。

2022-05-17 01:53 UTC, merged

2022-05-18 13:18 UTC, hyakt commented
@mfuji09 
すみません、こちら反映後確認したのですが、まだ画像リンク切れの状態になっているようです。
https://developer.mozilla.org/ja/docs/Web/HTML/Element/img#examples

画像を追加する、もしくは en-US の画像を参照するなどの対応が必要と思うのですがいかがでしょうか。
https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/HTML/Element/img/favicon144.png