fix javascript mime type
mdn/translated-content pull request #5632
Opened 2022-05-13 14:44 UTC by hoonoh

fixes invalid javascript mime type

2022-05-25 13:30 UTC, pje1740 requested changes

2022-05-25 13:30 UTC, pje1740 commented on files/ko/web/http/basics_of_http/mime_types/common_types/index.html
> +   <td><code>application/javascript</code></td>
기여해주셔서 감사합니다!
영문 기준 확인해보았을 때 `text/javascript`로 현재 표기되어 있는 것 같습니다. 파일 전체는 아니더라도 수정 주신 부분만 영문과 싱크를 맞춰주실 수 있을까요? 혹 제가 잘못 이해한 부분이 있다면 정정 부탁드리겠습니다! 리뷰가 늦어진 점 양해 부탁 드려요 🙇‍♀️

2022-05-26 07:40 UTC, hoonoh commented on files/ko/web/http/basics_of_http/mime_types/common_types/index.html
> +   <td><code>application/javascript</code></td>
안녕하세요, js의 MIME type에 대한 히스토리를 확인해보니 `text/javascript`를 `application/javascript`로 [대체 권고](https://datatracker.ietf.org/doc/html/rfc4329)했다 [원복](https://www.rfc-editor.org/rfc/rfc9239.html)했던 일이 있었네요. 간단하게 확인하고 PR했었는데 오래된 레퍼런스를 봤었나봅니다;
추가된 커밋에는 영문 페이지에 포함된 레퍼런스 링크 내용도 포함했습니다.

2022-06-01 14:03 UTC, pje1740 commented on files/ko/web/http/basics_of_http/mime_types/common_types/index.html
> +   <td><code>application/javascript</code></td>
상세하게 히스토리 확인하시고 공유 주셔서 감사합니다!! 고생 많으셨습니다 👍

2022-06-01 14:04 UTC, pje1740 approved these changes
고생 많으셨습니다!! 🔥

2022-06-01 14:04 UTC, merged