Update index.html
mdn/translated-content pull request #5639
Opened 2022-05-13 20:04 UTC by 54Freedom

2022-05-14 07:25 UTC, yin1999 commented
请在英文单词和中文之间保留一个空格

2022-05-23 08:17 UTC, irvin requested changes
please fix above issue

2022-05-31 01:05 UTC, yin1999 requested changes

2022-05-31 01:05 UTC, yin1999 commented on files/zh-cn/learn/server-side/first_steps/introduction/index.html
> +<p>客户端代码使用 <a href="/zh-CN/docs/Learn/HTML">HTML</a>，<a href="/zh-CN/docs/Learn/CSS">CSS</a>，和<a href="/zh-CN/docs/Learn/JavaScript">JavaScript</a> 来编写——这些代码直接在Web浏览器中运行，并且几乎没有访问底层操作系统的路径（包括对文件系统访问的限
```suggestion
<p>客户端代码使用 <a href="/zh-CN/docs/Learn/HTML">HTML</a>、<a href="/zh-CN/docs/Learn/CSS">CSS</a> 和 <a href="/zh-CN/docs/Learn/JavaScript">JavaScript</a> 来编写——这些代码直接在 Web 浏览器中运行，并且几乎没有访问底层操作系统的路径（包括对文件系统访问的限制）。</p>
```

2022-05-31 01:05 UTC, yin1999 commented on files/zh-cn/learn/server-side/first_steps/introduction/index.html
> +<p>银行使用服务器端编程来存储帐号信息，并且仅允许授权的用户查看和进行交易。Facebook、Twitter、Instagram、和Wikipedia，使用服务器端编程来突出、分享和控制对有趣内容的访问。</p>
```suggestion
<p>银行使用服务器端编程来存储帐号信息，并且仅允许授权的用户查看和进行交易。Facebook、Twitter、Instagram 和 Wikipedia，使用服务器端编程来突出、分享和控制对有趣内容的访问。</p>
```

2022-05-31 01:05 UTC, yin1999 commented on files/zh-cn/learn/server-side/first_steps/introduction/index.html
> +<p>服务器端编程则允许我们在数据库中存储信息，并且允许我们动态地创建和返回HTML和其他类型的文件（比如，PDF文件和图片等）。我们也可以简单地传输数据 （{{glossary("JSON")}}, {{glossary("XML")}}等），来让合适的客户端框架呈现（这样就减少了服务器的处理压力和需要被传输的数据总量）。</p>
```suggestion
<p>服务器端编程则允许我们在数据库中存储信息，并且允许我们动态地创建和返回HTML和其他类型的文件（比如，PDF文件和图片等）。我们也可以简单地传输数据 （{{glossary("JSON")}}、{{glossary("XML")}} 等），来让合适的客户端框架呈现（这样就减少了服务器的处理压力和需要被传输的数据总量）。</p>
```

2022-05-31 01:07 UTC, yin1999 approved these changes

2022-05-31 01:12 UTC, merged