Rewrite Asynchronous JavaScript with Markdown for zh-CN
mdn/translated-content pull request #5671
Opened 2022-05-15 06:04 UTC by jiwangyihao

使用Markdown重写异步JavaScript引导页，同时与英文版保持同步。

2022-05-15 07:04 UTC, yin1999 requested changes

2022-05-15 07:04 UTC, yin1999 commented on files/zh-cn/learn/javascript/asynchronous/index.md
> +- 由 Marijn Haverbeke 编写的 [Eloquent JavaScript](https://eloquentjavascript.net/) 网络书中的 [异步编程](https://eloquentjavascript.net/11_async.html)。
```suggestion
- 由 Marijn Haverbeke 编写的电子书籍 [Eloquent JavaScript](https://eloquentjavascript.net/) 中的[异步编程](https://eloquentjavascript.net/11_async.html)。
```

2022-05-15 07:28 UTC, jiwangyihao commented on files/zh-cn/learn/javascript/asynchronous/index.md
> +- 由 Marijn Haverbeke 编写的 [Eloquent JavaScript](https://eloquentjavascript.net/) 网络书中的 [异步编程](https://eloquentjavascript.net/11_async.html)。
感谢指正，已在最后一次commit中修改

2022-05-15 07:32 UTC, yin1999 commented
请使用 `git rebase -i HEAD~2` [合并最后两个 commit](https://docs.github.com/cn/get-started/using-git/about-git-rebase)，第二个 commit id 前的 `pick` 修改为 `s`。

2022-05-24 13:11 UTC, irvin requested changes
please rebase to fix conflict

2022-06-05 12:20 UTC, closed without merging