translation mistakes
mdn/translated-content pull request #5713
Opened 2022-05-17 14:37 UTC by AlwaysReVaule

changed some translation mistakes.

2022-05-19 08:40 UTC, irvin requested changes
有 conflict，請協助 rebase （或者重開一個可能較快）

2022-05-19 15:37 UTC, AlwaysReVaule commented
> 
not sure about is this okay, I just picked up  the "Resolve conflicts" button to resolve this conflict that may caused by other contributors tasks--I saw some contributors are removing all the <font></font>tags from the old version document. :)

2022-05-23 04:06 UTC, AlwaysReVaule commented
@yin1999 你方便看一下我是否解决了这个冲突吗？因为我有看到你在做font tag remove的工作，我认为是我们同时工作引起的冲突。谢谢~

2022-05-23 04:10 UTC, yin1999 commented
> @yin1999 你方便看一下我是否解决了这个冲突吗？因为我有看到你在做font tag remove的工作，我认为是我们同时工作引起的冲突。谢谢~

已解决

2022-05-23 10:17 UTC, merged

2022-05-23 10:17 UTC, irvin commented
thanks!