Intl.Collator オブジェクトの記事を更新
mdn/translated-content pull request #5729
Opened 2022-05-18 14:47 UTC by mfuji09

2022-05-21 06:59 UTC, potappo requested changes
脱字を修正しましたので、確認をお願いします。

2022-05-21 06:59 UTC, potappo commented on files/ja/web/javascript/reference/global_objects/intl/collator/supportedlocalesof/index.md
> +インドネシア語とドイツ語に対応しているもの、バリ語に対応していないランタイムを想定すると、ピンインの照合がインドネシア語では使用されておらず、インドネシアに特化したドイツ語に対応している可能性が低いとしても、 `supportedLocalesOf` はインドネシア語とドイツ語の言語タグを変更せずに返します。これは "`lookup`" アルゴリズムの仕様であること注意してください。 "`bes
```suggestion
インドネシア語とドイツ語に対応しているもの、バリ語に対応していないランタイムを想定すると、ピンインの照合がインドネシア語では使用されておらず、インドネシアに特化したドイツ語に対応している可能性が低いとしても、 `supportedLocalesOf` はインドネシア語とドイツ語の言語タグを変更せずに返します。これは "`lookup`" アルゴリズムの仕様であることに注意してください。 "`best fit`" マッチャーは、ほとんどのバリ語話者がインドネシア語も理解しているので、インドネシア語がバリ語に適切であると判断し、バリ語の言語タグも返すかもしれません。
```

2022-05-22 08:19 UTC, mfuji09 commented on files/ja/web/javascript/reference/global_objects/intl/collator/supportedlocalesof/index.md
> +インドネシア語とドイツ語に対応しているもの、バリ語に対応していないランタイムを想定すると、ピンインの照合がインドネシア語では使用されておらず、インドネシアに特化したドイツ語に対応している可能性が低いとしても、 `supportedLocalesOf` はインドネシア語とドイツ語の言語タグを変更せずに返します。これは "`lookup`" アルゴリズムの仕様であること注意してください。 "`bes
ありがとうございました！

2022-05-23 13:33 UTC, potappo approved these changes

2022-05-23 13:33 UTC, merged