[ko] correcting MDN_getting_started typing mistake
mdn/translated-content pull request #5738
Opened 2022-05-19 21:12 UTC by cofla159

'ko/docs/MDN/Contribute/Getting_started' 문서에서 오타를 발견하여 수정했습니다.
git 사용이 처음이라 branch명을 한글로 설정했다 바꾸었더니 commit이 두 번 된 것으로 보이는데 괜찮을까요?

2022-05-20 05:14 UTC, yujo11 requested changes
안녕하세요 cfla159님!

>git 사용이 처음이라 branch명을 한글로 설정했다 바꾸었더니 commit이 두 번 된 것으로 보이는데 괜찮을까요?

- 커밋 내역이 여러개 쌓이는건 상관없으나 최초 커밋에서는 "해대"라는 오타를 "대해"라고 변경하신거 같은데 두번째 커밋에서는 해당 라인을 아예 제거한걸로 보이네요. 이 부분 확인 해주시면 좋을거 같습니다!

2022-05-20 05:14 UTC, yujo11 commented on files/ko/mdn/contribute/getting_started/index.html
> - <li><a href="/ko/docs/MDN/Contribute/Contribute_to_docs_that_are_currently_needed">주요한 주제에 해대 새로운 글 작성 </a>(1시간 이상)</li>
이 부분이 아예 지워진거 같네요. 의도하신 부분이 맞을까요?

2022-05-20 09:02 UTC, cofla159 commented on files/ko/mdn/contribute/getting_started/index.html
> - <li><a href="/ko/docs/MDN/Contribute/Contribute_to_docs_that_are_currently_needed">주요한 주제에 해대 새로운 글 작성 </a>(1시간 이상)</li>
첫 번째 커밋의 오타 수정이 의도한 결과고 두 번째는 커밋을 다시 하면서 잘못 수정된 것 같습니다. 수정해서 다시 커밋해야 할까요?

2022-05-21 04:06 UTC, yujo11 commented on files/ko/mdn/contribute/getting_started/index.html
> - <li><a href="/ko/docs/MDN/Contribute/Contribute_to_docs_that_are_currently_needed">주요한 주제에 해대 새로운 글 작성 </a>(1시간 이상)</li>
넵 맞습니다!

2022-05-21 05:17 UTC, cofla159 commented on files/ko/mdn/contribute/getting_started/index.html
> - <li><a href="/ko/docs/MDN/Contribute/Contribute_to_docs_that_are_currently_needed">주요한 주제에 해대 새로운 글 작성 </a>(1시간 이상)</li>
네 그럼 이 이슈는 닫고 다시 pull request 하겠습니다 감사합니다~!

2022-05-21 05:17 UTC, closed without merging

2022-05-22 01:13 UTC, yujo11 commented on files/ko/mdn/contribute/getting_started/index.html
> - <li><a href="/ko/docs/MDN/Contribute/Contribute_to_docs_that_are_currently_needed">주요한 주제에 해대 새로운 글 작성 </a>(1시간 이상)</li>
작업하신 브랜치에서 커밋을 추가로 남기면 이 PR에 해당 커밋 내역이 자동으로 쌓여서 PR을 다시 올리지 않으셔도 괜찮아요!

다음에 PR하실 때 참고해주세용