relecture linguistique
mdn/translated-content pull request #5752
Opened 2022-05-20 18:29 UTC by Mozinet-fr

Relecture linguistique

2022-05-20 21:24 UTC, cw118 requested changes
Merci déjà pour ces corrections @Mozinet-fr ! Quelques légers ajustments :)

2022-05-20 21:24 UTC, cw118 commented on files/fr/learn/javascript/objects/classes_in_javascript/index.md
> +Cela ressemble beaucoup au constructeur `Personne`, mais il y a quelque chose que nous n'avons pas encore vu : la fonction [`call()`](/fr/docs/Web/JavaScript/Reference/Global_Objects/Function/call).
```suggestion
Cela ressemble beaucoup au constructeur `Personne`, mais il y a quelque chose que nous n'avons pas encore vu&nbsp;: la fonction [`call()`](/fr/docs/Web/JavaScript/Reference/Global_Objects/Function/call). Cette fonction permet d'appeler une fonction définie ailleurs dans le contexte actuel. Le premier paramètre spécifie la valeur de `this` que l'on souhaite utiliser lorsque l'on utilisera la fonction, les paramètres suivants seront les paramètres qui pourront être passés en arguments lorsqu'elle sera appelée.
```

2022-05-20 21:24 UTC, cw118 commented on files/fr/learn/javascript/objects/classes_in_javascript/index.md
>  Nous voulons que le constructeur `Professeur()` aie les mêmes attributs que `Personne()`, nous les spécifions donc dans l'appel fait via la fonction `call()`.
```suggestion
Nous voulons que le constructeur `Professeur()` ait les mêmes attributs que `Personne()`, nous les spécifions donc dans l'appel fait via la fonction `call()`.
```

2022-05-20 21:24 UTC, cw118 commented on files/fr/learn/javascript/objects/classes_in_javascript/index.md
> +Vous pouvez hériter des propriétés `width` et `height` en procédant comme ceci (mais également en suivant bien sûr les différentes étapes décrites ci-dessous) :
```suggestion
Vous pouvez hériter des propriétés `width` et `height` en procédant comme ceci (mais également en suivant bien sûr les différentes étapes décrites ci-dessous)&nbsp;:
```

2022-05-20 21:24 UTC, cw118 commented on files/fr/learn/javascript/objects/classes_in_javascript/index.md
> +Notre classe `Professeur()` doit hériter des méthodes définies dans le prototype de `Personne()`. Aussi, comment procéder pour obtenir ce résultat ?
```suggestion
Notre classe `Professeur()` doit hériter des méthodes définies dans le prototype de `Personne()`. Aussi, comment procéder pour obtenir ce résultat&nbsp;?
```

2022-05-20 21:24 UTC, cw118 commented on files/fr/learn/javascript/objects/classes_in_javascript/index.md
>  Ajoutez la ligne suivante à la suite du bloc de code que nous venons d'ajouter :
```suggestion
Ajoutez la ligne suivante à la suite du bloc de code que nous venons d'ajouter&nbsp;:
```

2022-05-20 21:24 UTC, cw118 commented on files/fr/learn/javascript/objects/classes_in_javascript/index.md
>  3.  Cela peut devenir problématique, autant le corriger dès maintenant. C'est possible via l'ajout de la ligne de code suivante à la fin :
```suggestion
2.  Nous avons également besoin de faire encore une chose avant de continuer. Après avoir ajouté la ligne précédente, le constructeur du prototype de `Professeur()` est désormais équivalent à celui de `Personne()`, parce que nous avons défini `Professeur.prototype` pour référencer un objet qui hérite ses propriétés de `Personne.prototype`&nbsp;! Essayez, après avoir sauvegardé votre code et rechargé la page, d'entrer `Professeur.prototype.constructor` dans la console pour vérifier.
3.  Cela peut devenir problématique, autant le corriger dès maintenant. C'est possible via l'ajout de la ligne de code suivante à la fin&nbsp;:
```

2022-05-20 21:24 UTC, cw118 commented on files/fr/learn/javascript/objects/classes_in_javascript/index.md
> +**Note :** si vous rencontrez un problème pour faire fonctionner ce code, comparez-le à notre [version finalisée](http://mdn.github.io/learning-area/javascript/oojs/advanced/oojs-class-inheritance-fi
```suggestion
**Note :** Si vous rencontrez un problème pour faire fonctionner ce code, comparez-le à notre [version finalisée](http://mdn.github.io/learning-area/javascript/oojs/advanced/oojs-class-inheritance-finished.html) (ou regardez tourner [notre démo en ligne](https://mdn.github.io/learning-area/javascript/oojs/advanced/oojs-class-inheritance-finished.html)).
```

2022-05-20 21:24 UTC, cw118 commented on files/fr/learn/javascript/objects/classes_in_javascript/index.md
> +Vous pourriez également être intéressé par certaines des nouvelles fonctionnalités d’{{glossary("ECMAScript")}} qui nous permettent de mettre en place l'héritage d'une façon beaucoup plus élégante en
```suggestion
Vous pourriez également être intéressé par certaines des nouvelles fonctionnalités d'{{glossary("ECMAScript")}} qui nous permettent de mettre en place l'héritage d'une façon beaucoup plus élégante en JavaScript (voir [Classes](/fr/docs/Web/JavaScript/Reference/Classes)). Nous ne les avons pas développées ici, parce qu'elles ne sont actuellement pas prises en charge par tous les navigateurs. Toutes les autres constructions dont nous avons discuté dans cette série d'articles sont prises en charge par IE9 et les versions moins récentes, et il existe des méthodes qui prennent plus en charge les navigateurs moins récents.
```

On préfère des apostrophes droites :)

2022-05-20 21:24 UTC, cw118 commented on files/fr/learn/javascript/objects/classes_in_javascript/index.md
> +Dans notre [section sur la programmation orientée objet](/fr/docs/Learn/JavaScript/Objects/Object-oriented_JS#Object-oriented_programming_from_10000_meters), nous avons également inclus une classe `E
```suggestion
Dans notre [section sur la programmation orientée objet](/fr/docs/Learn/JavaScript/Objects/Object-oriented_JS#Object-oriented_programming_from_10000_meters), nous avons également inclus une classe `Etudiant` comme un concept qui hérite de toutes les fonctionnalités de la classe `Personne` et qui a également une méthode `saluer()` différente de celle de `Personne`, beaucoup moins formelle que la méthode `saluer()` de `Professeur()`. Jetez un œil à ce à quoi ressemble la méthode `saluer()` de la classe `Etudiant` dans cette section et essayez d'implémenter votre propre constructeur `Etudiant()` qui hérite de toutes les fonctionnalités de `Personne()` et la fonction `saluer()` différente.
```

2022-05-20 21:24 UTC, cw118 commented on files/fr/learn/javascript/objects/classes_in_javascript/index.md
> +**Note :** à cause de la manière dont JavaScript fonctionne, avec la chaîne de prototype, etc., le partage de fonctionnalités entre objet est souvent appelée **délégation** — les objets spécialisés d
```suggestion
**Note :** À cause de la manière dont JavaScript fonctionne, avec la chaîne de prototype, etc., le partage de fonctionnalités entre objet est souvent appelée **délégation** — les objets spécialisés délèguent cette fonctionnalité à l'objet de type générique. C'est certainement beaucoup plus précis que de l'appeler héritage, puisque la fonctionnalité «&nbsp;héritée&nbsp;» n'est pas copiée dans les objets qui «&nbsp;héritent&nbsp;». Au contraire, elle demeure dans l'objet générique.
```

2022-05-21 13:32 UTC, Mozinet-fr commented
Pourquoi changer mes espaces insécables en &nbsp; ?

2022-05-21 15:34 UTC, cw118 commented
@Mozinet-fr L'utilisation de l'entité HTML est une "convention" MDN pour la locale française qui permet de rendre les espaces insécables (en anglais "non-breaking space" qui donne "nbsp") visibles avec les outils d'édition :)

2022-05-21 18:10 UTC, Mozinet-fr commented
> @Mozinet-fr L'utilisation de l'entité HTML est une "convention" MDN pour la locale française qui permet de rendre les espaces insécables (en anglais "non-breaking space" qui donne "nbsp") visibles avec les outils d'édition :)
Donc, c'est parce que mes espaces insécables Unicode ne sont pas différentiables dans l'interface d’édition.

2022-05-21 18:22 UTC, cw118 commented
Effectivement :)

2022-05-28 04:28 UTC, cw118 commented
@Mozinet-fr Est-ce qu'on peut aider pour cette PR ?

2022-05-28 13:37 UTC, Mozinet-fr commented
> @Mozinet-fr Est-ce qu'on peut aider pour cette PR ?

Assurément

2022-05-28 20:23 UTC, cw118 approved these changes
Je me suis permis d'appliquer les suggestions, merci beaucoup @Mozinet-fr !

2022-05-28 20:23 UTC, merged