Issue/607/20220521
mdn/translated-content pull request #5758
Opened 2022-05-21 06:19 UTC by gurezo

下記 issue の PR です
https://github.com/mozilla-japan/translation/issues/607

2022-05-21 07:41 UTC, potappo requested changes
細かいミスの修正といくつか指摘をしましたので、確認お願いします。

2022-05-21 07:41 UTC, potappo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/angular_todo_list_beginning/index.md
> +      <th scope="row">Objective:</th>
```suggestion
      <th scope="row">目的:</th>
```

2022-05-21 07:41 UTC, potappo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/angular_todo_list_beginning/index.md
> +  これが、'./app.component.html'
```suggestion
  これが、'./app.component.html' です。
```

2022-05-21 07:41 UTC, potappo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/angular_todo_list_beginning/index.md
> +このガイドでは、後の手順でフィルタリングを追加する方法を示しますが、フィルターを使用してすべての items 　のデフォルトリストを表示することもできます。
```suggestion
このガイドでは、後の手順でフィルタリングを追加する方法を示しますが、フィルターを使用してすべての items のデフォルトリストを表示することもできます。
```

2022-05-21 07:41 UTC, potappo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/angular_todo_list_beginning/index.md
> +The `<li>` contains an `*ngFor`, a built-in Angular directive that iterates over the items in the `items` array.
下2行含めて翻訳漏れかと思うので翻訳をお願いします。

2022-05-21 07:41 UTC, potappo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/angular_todo_list_beginning/index.md
> +        基本的なアプリ構造を作成するには、やることのリストを表示するようにします アイテム、およびコンポーネントなどの基本的な Angular の概念を理解し、構造、コンポーネント間でのデータの共有、コンテンツのループ 作成する。
翻訳として雑然としているので、見直しをお願いします。おそらく、以下のような翻訳になるかと思います。

To create our basic app structure, get it displaying a list of to-do items, and understand fundamental Angular concepts such as component structure, sharing data between components, and looping content creation. 

基本的なアプリ構造の作成例として、やることリストを表示し、コンポーネント構造、コンポーネント間でのデータの共有、コンテンツ作成のループのような、基本的な Angular の概念を理解すること。

2022-05-21 07:54 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/angular_todo_list_beginning/index.md
> +        基本的なアプリ構造を作成するには、やることのリストを表示するようにします アイテム、およびコンポーネントなどの基本的な Angular の概念を理解し、構造、コンポーネント間でのデータの共有、コンテンツのループ 作成する。
確認のうえ、修正します。

2022-05-21 07:55 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/angular_todo_list_beginning/index.md
> +The `<li>` contains an `*ngFor`, a built-in Angular directive that iterates over the items in the `items` array.
確認の上、修正します。

2022-05-21 08:28 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/angular_todo_list_beginning/index.md
> +The `<li>` contains an `*ngFor`, a built-in Angular directive that iterates over the items in the `items` array.
こちら原文が残ったままでした。削除します。

2022-05-21 08:31 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/angular_todo_list_beginning/index.md
> +The `<li>` contains an `*ngFor`, a built-in Angular directive that iterates over the items in the `items` array.
[73f103a](https://github.com/mdn/translated-content/pull/5758/commits/73f103a23e2e86513596390c92fcc37010c562c9)

2022-05-21 08:31 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/angular_todo_list_beginning/index.md
> +        基本的なアプリ構造を作成するには、やることのリストを表示するようにします アイテム、およびコンポーネントなどの基本的な Angular の概念を理解し、構造、コンポーネント間でのデータの共有、コンテンツのループ 作成する。
[73f103a](https://github.com/mdn/translated-content/pull/5758/commits/73f103a23e2e86513596390c92fcc37010c562c9)

2022-05-21 08:33 UTC, gurezo commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/angular_todo_list_beginning/index.md
> +        基本的なアプリ構造を作成するには、やることのリストを表示するようにします アイテム、およびコンポーネントなどの基本的な Angular の概念を理解し、構造、コンポーネント間でのデータの共有、コンテンツのループ 作成する。
[436129f](https://github.com/mdn/translated-content/pull/5758/commits/436129fa71c3f22b8339d5b4eb71e5f8a3bd6adb)

2022-05-21 08:34 UTC, gurezo commented
@potappo 
レビュー指摘箇所を確認・見直し・修正をコミットしました。
再度レビューの方、よろしくお願い申し上げます。

2022-05-23 13:37 UTC, potappo approved these changes
OK です。

2022-05-23 13:38 UTC, merged