「async を使用した非同期フロー制御」の未翻訳部分の翻訳
mdn/translated-content pull request #5767
Opened 2022-05-21 18:50 UTC by SuzukiKatsuma

「async を使用した非同期フロー制御」の未翻訳部分の翻訳を行いました。
また HTML から Markdown に移行しました。

issue: mozilla-japan/translation#598

2022-05-23 16:41 UTC, mfuji09 requested changes
一部の修正をお願いします。

2022-05-23 16:41 UTC, mfuji09 commented on files/ja/learn/server-side/express_nodejs/displaying_data/flow_control_using_async/index.md
> +では**複数**の非同期クエリを実行する必要があり、すべての操作が完了するまでページをレンダリングできない場合はどうすればよいでしょうか？甘い考えで実装するとリクエストを「デイジーチェーン」して、前のリクエストのコールバックで後続のリクエストを開始し、最後のコールバックでレスポンスを受け取ってレンダリングすることができます。この方法の問題点は並列で実行した方が効率的である場合でも、リクエストを直
「クエリ」は「クエリー」と長音を付けてください。

2022-05-23 16:41 UTC, mfuji09 commented on files/ja/learn/server-side/express_nodejs/displaying_data/flow_control_using_async/index.md
> +async には多くの便利なメソッドがあります（詳しくは [the documentation](https://caolan.github.io/async/v3/docs.html) を参照してください）。ここでは重要ないくつかの関数を紹介します。
the documentation の部分は原文のままにする意味はないので、「ドキュメント」などと訳してください。

2022-05-23 16:41 UTC, mfuji09 commented on files/ja/learn/server-side/express_nodejs/displaying_data/flow_control_using_async/index.md
> +async には多くの便利なメソッドがあります（詳しくは [the documentation](https://caolan.github.io/async/v3/docs.html) を参照してください）。ここでは重要ないくつかの関数を紹介します。
the documentation の部分は原文のままにする意味はないので、「ドキュメント」などと訳してください。

2022-05-23 17:52 UTC, SuzukiKatsuma commented
@mfuji09 さん、レビューありがとうございます！
早速ですが、「クエリ」を「クエリー」に修正いたしました。


ただ一点だけ翻訳について相談とご確認をお願いいたします。

> the documentation の部分は原文のままにする意味はないので、「ドキュメント」などと訳してください

上記のレビューを頂きました。
私としましては、リンク先のドキュメントが日本語でないことを伝えたく原文のまま "the documentation" としていました。
MDN の日本語のページ内でリンクがあるとき、英語のページ (未翻訳の記事など) は英語のままでリンクが貼られているからです。

それを踏まえて、翻訳の候補として三つの案が思い浮かんだのですが、助言を頂きたいです。

* このまま the documentation とする。
* @mfuji09 さんからのレビューの中で頂いた翻訳案「ドキュメント」とする。
* the documentation は翻訳して、かつ英語であることを明記するため「ドキュメント (en-US)」とする。

お手数をおかけしますが、よろしくお願いいたします。

2022-05-25 17:41 UTC, mfuji09 commented
@SuzukiKatsuma さん
リンクテキストがリンク先のページのタイトルである場合は、リンクテキストを翻訳をしなくて良いでしょう。しかし、今回の the documentation はリンク先のページのタイトルではありませんので、翻訳した方が良いと思います。
ご提案のように、「ドキュメント (en-US)」のように翻訳していただけると、より分かりやすいと思います。

2022-05-27 08:37 UTC, SuzukiKatsuma commented
確認と説明、ありがとうございます。

リンクテキストの翻訳は「リンク先のページのタイトルかどうか」というのは分かりやすい指標ですね！
今後の翻訳にも活かしていきたいと思います。

それでは支持して頂いた「ドキュメント (en-US)」のように翻訳いたします。

2022-05-27 08:55 UTC, SuzukiKatsuma commented
@mfuji09 さん、"the documentation" についても修正いたしました。

改めてレビューをお願いいたします。

2022-05-30 01:14 UTC, mfuji09 approved these changes
OKです。ありがとうございました。

2022-05-30 01:24 UTC, merged

2022-05-30 07:45 UTC, SuzukiKatsuma commented
レビューありがとうございました！