continue updating translation
mdn/translated-content pull request #5777
Opened 2022-05-22 14:51 UTC by AlwaysReVaule

after PR: https://github.com/mdn/translated-content/pull/5769#issue-1244138657

2022-05-23 00:07 UTC, yin1999 requested changes

2022-05-23 00:07 UTC, yin1999 commented on files/zh-cn/learn/javascript/objects/classes_in_javascript/index.html
> +<p>我们现在可以使用<a href="/en-US/docs/Web/JavaScript/Reference/Operators/new"><code>new</code>运算符</a>去实例化对象实例，就像我们之前做过的一样的方式:</p>
```suggestion
<p>我们现在可以使用 <a href="/zh-CN/docs/Web/JavaScript/Reference/Operators/new"><code>new</code> 运算符</a>来实例化对象实例，就像我们之前使用过的方式一样：</p>
```

2022-05-23 00:07 UTC, yin1999 commented on files/zh-cn/learn/javascript/objects/classes_in_javascript/index.html
> +<p><strong>注意</strong>：在引擎盖下，您的类正在转换为原型继承模型 - 这只是语法糖。但我相信你会同意它更容易写。</p>
这句话是否过于“直译”了：

```suggestion
<p><strong>注意</strong>：在 JS 引擎下，类会被转换为原型继承模型——这只是语法糖。但我相信你会觉得这是一种更容易的写法。</p>
```

2022-05-23 03:51 UTC, AlwaysReVaule commented on files/zh-cn/learn/javascript/objects/classes_in_javascript/index.html
> +<p><strong>注意</strong>：在引擎盖下，您的类正在转换为原型继承模型 - 这只是语法糖。但我相信你会同意它更容易写。</p>
@yin1999 是的，当时我很困惑这个hood要怎么译

2022-05-23 03:55 UTC, AlwaysReVaule commented on files/zh-cn/learn/javascript/objects/classes_in_javascript/index.html
> +<p>我们现在可以使用<a href="/en-US/docs/Web/JavaScript/Reference/Operators/new"><code>new</code>运算符</a>去实例化对象实例，就像我们之前做过的一样的方式:</p>
下次我会注意引用连接自中文简体 😊 @yin1999

2022-05-23 03:59 UTC, AlwaysReVaule commented on files/zh-cn/learn/javascript/objects/classes_in_javascript/index.html
> + <li>那些在对象实例上可用的对象，它可以是像我们上面看到的构造函数实例化时创建的对象（例如<code>let teacher1 = new Teacher( 'Chris' );</code>  然后和 <code>teacher1.name</code>)，也可以是一个对象文字（<code>let teacher1 = { name : 'Chris' }</code>然后和<code>t
😊好的 @yin1999

2022-05-24 14:44 UTC, irvin commented
please resolve conflict

2022-05-25 00:23 UTC, AlwaysReVaule commented
> please resolve conflict

@irvin The conflict already resolved. 😊

2022-05-25 00:26 UTC, AlwaysReVaule commented
> please resolve conflict

@irvin The conflict already resolved. 😊

2022-05-25 00:47 UTC, yin1999 commented on files/zh-cn/learn/javascript/objects/classes_in_javascript/index.html
> + <li>那些在对象实例上可用的对象，它可以是像我们上面看到的构造函数实例化时创建的对象（例如 <code>let teacher1 = new Teacher( 'Chris' );</code>  以及其属性 <code>teacher1.name</code>)，也可以是一个对象字面量（<code>let teacher1 = { name : 'Chris' }</code> 以及其属性
多了个空格：

```suggestion
 <li>那些在对象实例上可用的对象，它可以是像我们上面看到的构造函数实例化时创建的对象（例如 <code>let teacher1 = new Teacher( 'Chris' );</code> 以及其属性 <code>teacher1.name</code>)，也可以是一个对象字面量（<code>let teacher1 = { name : 'Chris' }</code> 以及其属性 <code>teacher1.name</code>）。</li>
```

2022-05-25 00:47 UTC, yin1999 commented on files/zh-cn/learn/javascript/objects/classes_in_javascript/index.html
> +<p>ECMAScript 2015 引入了<a href="/en-US/docs/Web/JavaScript/Reference/Classes">class syntax</a>到 JavaScript，作为使用更简单、更简洁的语法编写可重用类的一种方式，这更类似于 C++ 或 Java 中的类。在本节中，我们将个人和教师示例从原型继承转换为类，以向你展示它是如何完成的。</p>
一并更新链接：

```suggestion
<p>ECMAScript 2015 引入了<a href="/zh-CN/docs/Web/JavaScript/Reference/Classes">class syntax</a> 到 JavaScript，作为使用更简单、更简洁的语法编写可重用类的一种方式，这更类似于 C++ 或 Java 中的类。在本节中，我们将个人和教师示例从原型继承转换为类，以向你展示它是如何完成的。</p>
```

2022-05-25 00:58 UTC, yin1999 commented on files/zh-cn/learn/javascript/objects/classes_in_javascript/index.html
> + <li>那些在对象实例上可用的对象，它可以是像我们上面看到的构造函数实例化时创建的对象（例如 <code>let teacher1 = new Teacher( 'Chris' );</code> 以及其属性 <code>teacher1.name</code>)，也可以是一个对象字面量（<code>let teacher1 = { name : 'Chris' }</code> 以及其属性
```suggestion
 <li>那些在对象实例上可用的对象，它可以是像我们上面看到的构造函数实例化时创建的对象（例如 <code>let teacher1 = new Teacher( 'Chris' );</code> 以及其属性 <code>teacher1.name</code>），也可以是一个对象字面量（<code>let teacher1 = { name : 'Chris' }</code> 以及其属性 <code>teacher1.name</code>）。</li>
```

2022-05-25 01:01 UTC, merged