fix description about import rules
mdn/translated-content pull request #5785
Opened 2022-05-23 10:43 UTC by hogashi

https://developer.mozilla.org/en-US/docs/Web/CSS/@import

`Imported rules must come before all other types of rules, except @charset rules.` seems to be `You must write @import first` , not `@import is prioritized` .

ref: https://www.w3.org/TR/CSS22/syndata.html#at-rules

```
CSS 2.2 user agents must ignore any '@import' rule that occurs inside a block or after any non-ignored statement other than an @charset or an @import rule.
```

And I also fixed some phrases. Would you please review this?

2022-05-30 15:43 UTC, mfuji09 requested changes
提案がありますので、ご確認ください。
なお、日本語版へのプルリクエストは日本人しか読みませんので、日本語でどうぞ。

2022-05-30 15:50 UTC, hogashi commented on files/ja/web/css/@import/index.md
> +インポートされたルールは、 {{CSSxRef("@charset")}} を除く他のすべての種類のルールよりも先でなければなりません。 `@import` ルールは[入れ子になるステートメント](/ja/docs/Web/CSS/Syntax#nested_statements)ではないので、 [条件付きアットルールグループ](/ja/docs/Web/CSS/At-rule#条件付きグループ
なるほど、いかにもよさそうです、そのまま commit してしまいます!

2022-05-30 15:51 UTC, hogashi commented
ありがとうございます! 提案よさそうと思いましたので、そのまま取り入れてみました。再度見ていただけると幸いです!

2022-06-02 14:32 UTC, mfuji09 approved these changes
OKです。ありがとうございます。

2022-06-02 15:42 UTC, merged