Docs/Glossary/FTP を更新
mdn/translated-content pull request #582
Opened 2021-04-19 14:15 UTC by x270

英語版 Last modified: Jan 13, 2021 と同期。

2021-05-04 04:32 UTC, mfuji09 requested changes
1件の指摘を入れました。
また、英語版と同期させるときには、13行目と15行目のidも英語版に合わせるようお願いします。

2021-05-04 04:32 UTC, mfuji09 commented on files/ja/glossary/ftp/index.html
> +<p><strong>FTP</strong> (File Transfer Protocol、ファイル転送プロトコル) は、ある{{glossary("host","ホスト")}}から別のホストに、インターネットを介してファイルを転送するための長年の標準的な{{glossary("protocol","プロトコル")}}でした。しかし、チームやホスティングアカウントは FTP を許可せず、代わ
Git の後の空白が全角スペースになっているので、半角にするようお願いします。

2021-05-04 11:39 UTC, x270 commented on files/ja/glossary/ftp/index.html
> +<p><strong>FTP</strong> (File Transfer Protocol、ファイル転送プロトコル) は、ある{{glossary("host","ホスト")}}から別のホストに、インターネットを介してファイルを転送するための長年の標準的な{{glossary("protocol","プロトコル")}}でした。しかし、チームやホスティングアカウントは FTP を許可せず、代わ
確認ミスです。失礼いたしました。

2021-05-04 11:40 UTC, x270 commented
@mfuji09  
レビューありがとうございます。  
コメント箇所を修正しましたので、お手数ですがご確認お願いします。  
また、13行目、15行目のid属性も、英語版と同期しました。

2021-05-05 17:33 UTC, mfuji09 approved these changes
対応ありがとうございました。
これでよいと思います。

2021-05-05 17:33 UTC, merged