whole page Chinese translation
mdn/translated-content pull request #5820
Opened 2022-05-25 16:44 UTC by AlwaysReVaule

2022-05-26 01:03 UTC, yin1999 requested changes
我提出了部分内容的修改意见，一部分需要修改的内容未提到，请按以下流程更新：

1. 将文内的链接更新为指向中文文档的（即使文档不存在），替换 `/en-US/` 为 `/zh-CN/`
2. 删除句号后存在的空格
3. 将有序列表中的两段话并为一段

2022-05-26 01:03 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +<p><img alt="我们的待办事项列表应用程序使用文本输入呈现以输入新待办事项" src="https://mdn.mozillademos.org/files/17246/rendered-form-with-new-items.png " style="border-style:solid;border-width:1px;display:block;height:301px;marg
```suggestion
<p><img alt="我们的待办事项列表应用程序使用文本输入呈现以输入新待办事项" src="rendered-form-with-new-items.png"></p>
```

2022-05-27 17:55 UTC, AlwaysReVaule commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +<h2 id="Creating_a_method_binding_it_to_an_event_with_v-on">创建一个方法 &amp;用v-on绑定这个方法到一个事件上</h2>
为什么原句中的&amp不保留？ @yin1999

2022-05-27 17:55 UTC, AlwaysReVaule commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
>  <table class="learn-box standard-table">
@yin1999 我想这里应该是要保留table的样式的

2022-05-27 17:55 UTC, AlwaysReVaule commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +  <p>添加它如下:</p>
@yin1999 这里我认为最好保持原来的两段样式，但是你的翻译方式，更为合适。
```suggestion
  <p>在这个组件中，我们需要在 <code>ToDoForm</code> 组件对象内的 <code>methods</code> 属性中添加一个 <code>onSubmit()</code> 方法。 我们将使用它来处理提交操作。</p>
   
  <p>添加它如下:</p>
```
```suggestion
  <p>在这个组件中，我们需要在 <code>ToDoForm</code> 组件对象内的 <code>methods</code> 属性中添加一个 <code>onSubmit()</code> 方法。 我们将使用它来处理提交操作。</p>
   
  <p>就像这样:</p>
```

2022-05-27 17:55 UTC, AlwaysReVaule commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +  <p>为了保持一致性，我们将在此处使用简写语法。 将 <code>submit</code> 处理程序添加到您的 <code>&lt;form&gt;</code> 元素，如下所示：</p>
@yin1999 same，我的意见，依然应该保持原格式。
```suggestion
  <p>接下来我们需要将该方法绑定到我们的 <code>&lt;form&gt;</code> 元素的 <code>submit</code> 事件处理程序。 就像 Vue 如何使用 <code><a href="https://vuejs.org/v2/api/#v-bind">v-bind</a></code> 语法来绑定属性，Vue 有 用于事件处理的特殊指令：<code><a href="https://vuejs.org/v2/api/#v-on">v-on</a></code>。 <code>v-on</code> 指令通过 <code>v-on:event="method"</code> 语法工作。 和 <code>v-bind</code> 很像，还有一个简写语法：<code>@event="method"</code>。</p>
  <p>为了保持一致性，我们将在此处使用简写语法。 将 <code>submit</code> 处理程序添加到您的 <code>&lt;form&gt;</code> 元素，如下所示：</p>
```

2022-05-27 17:55 UTC, AlwaysReVaule commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +  <p>修饰符被附加到事件的末尾，带有一个点，如下所示：<code>@event.modifier</code>。 以下是事件修饰符列表：</p>
@yin1999 同上

2022-05-27 17:55 UTC, AlwaysReVaule commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +<h2 id="In_this_module">在这个模块</h2>
```suggestion
<h2 id="In_this_module">本章目录</h2>
```

2022-05-27 17:55 UTC, AlwaysReVaule commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +<p><img alt="我们的待办事项列表应用程序使用文本输入呈现以输入新待办事项" src="https://mdn.mozillademos.org/files/17246/rendered-form-with-new-items.png " style="border-style:solid;border-width:1px;display:block;height:301px;marg
@yin1999 样式改掉了吗？

2022-05-27 17:55 UTC, AlwaysReVaule commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +  <p>回到你的 <code>ToDoForm</code> 组件，像这样更新 <code>onSubmit()</code> 方法。 如果标签值为空，我们就不发出 <code>todo-added</code> 事件。</p>
@yin1999 保持意见

2022-05-27 17:55 UTC, AlwaysReVaule commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +   <li><code>.passive</code>：等效于使用 <code><a href="/en- 在 vanilla JavaScript 中创建事件监听器时使用 <code>{passive: true }</code> 参数 US/docs/Web/API/EventTarget/addEventListener">addEventListener()</a></code>.</
@yin1999 翻译语序还是很奇怪
```suggestion
   <li><code>.passive</code>：等效于使用<code>{passive: true }</code>参数，当在vanilla JavaScript 中创建事件监听器时使用<code><a href="/en-US/docs/Web/API/EventTarget/addEventListener">addEventListener()</a></code>。</li>
```

2022-05-27 17:55 UTC, AlwaysReVaule commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +   <li><code>.passive</code>：等效于使用 <code><a href="/en- 在 vanilla JavaScript 中创建事件监听器时使用 <code>{passive: true }</code> 参数 US/docs/Web/API/EventTarget/addEventListener">addEventListener()</a></code>.</
```suggestion
 <li><code>.passive</code>：等效于使用<code>{passive: true }</code>参数，当在vanilla JavaScript 中创建事件监听器时使用<code><a href="/zh-CN/docs/Web/API/EventTarget/addEventListener">addEventListener()</a></code>。</li>
```

2022-05-28 00:05 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +<p><img alt="我们的待办事项列表应用程序使用文本输入呈现以输入新待办事项" src="https://mdn.mozillademos.org/files/17246/rendered-form-with-new-items.png " style="border-style:solid;border-width:1px;display:block;height:301px;marg
这里引用的图片由旧的文档平台产生，其在未来会被移除。目前此图片已被存入 mdn/content repo，而其样式部分会由 mdn/yari 自动根据图片实际大小添加，无需保留此样式，请更新。

2022-05-29 05:13 UTC, yin1999 requested changes

2022-05-29 05:13 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +   <li><code>.passive</code>：等效于使用 <code><a href="/en- 在 vanilla JavaScript 中创建事件监听器时使用 <code>{passive: true }</code> 参数 US/docs/Web/API/EventTarget/addEventListener">addEventListener()</a></code>.</
```suggestion
   <li><code>.passive</code>：等效于在 vanilla JavaScript 中使用 <code><a href="/zh-CN/docs/Web/API/EventTarget/addEventListener">addEventListener()</a></code> 创建事件监听器时传入 <code>{ passive: true }</code> 参数。</li>
```

2022-05-29 05:13 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
>    <pre class="brush: js notranslate">&lt;form @submit.prevent="onSubmit"&gt;</pre>
```suggestion
  <pre class="brush: js">&lt;form @submit.prevent="onSubmit"&gt;</pre>
```

2022-05-29 05:13 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +<p>如果您现在尝试提交表单，您会注意到页面没有重新加载。 如果打开控制台，可以看到<code><a href="/en-US/docs/Web/API/Console/log">console.log()</a></code>的结果 我们在 <code>onSubmit()</code> 方法中添加了。</p>
```suggestion
<p>如果您现在尝试提交表单，您会注意到页面没有重新加载。如果打开控制台，可以看到我们在 <code>onSubmit()</code> 方法中添加的 <code><a href="/zh-CN/docs/Web/API/Console/log">console.log()</a></code> 所输出结果。</p>
```

2022-05-29 05:13 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +<h2 id="Binding_data_to_inputs_with_v-model">用v-model来绑定数据到输入</h2>
```suggestion
<h2 id="Binding_data_to_inputs_with_v-model">用 v-model 来绑定数据到输入</h2>
```

2022-05-29 05:13 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +  <p>我们现在需要一些方法将 <code>new-todo-input</code> <code>&lt;input&gt;</code> 字段的值附加到 <code>label</code> 字段。 Vue 对此有一个特殊的指令：<code><a href="https://vuejs.org/v2/api/#v-model">v-model</a></code>。 <code>v-mod
```suggestion
  <p>我们现在需要一些方法将 <code>new-todo-input</code> <code>&lt;input&gt;</code> 字段的值附加到 <code>label</code> 字段。Vue 对此有一个特殊的指令：<code><a href="https://vuejs.org/v2/api/#v-model">v-model</a></code>。<code>v-model</code> 绑定到您在其上设置的数据属性，并使其与 <code>&lt;input&gt;</code> 保持同步。<code>v-model</code> 适用于所有不同的输入类型，包括复选框、单选框和选择输入。要使用 <code>v-model</code>，你需要向 <code>&lt;input&gt;</code> 添加一个结构为 <code>v-model="variable"</code> 的属性。<p>
```

2022-05-29 05:13 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +  <p>所以在我们的例子中，我们会将它添加到我们的 <code>new-todo-input</code> 字段中，如下所示。 现在就这样做：</p>
```suggestion
  <p>所以在我们的例子中，我们会将它添加到我们的 <code>new-todo-input</code> 字段中，如下所示。现在就这样做：</p>
```

2022-05-29 05:13 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
>    <pre class="brush: js notranslate">&lt;input
```suggestion
  <pre class="brush: js">&lt;input
```

2022-05-29 05:13 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +  <p><strong>注意</strong>：您还可以通过事件和 <code>v-bind</code> 属性的组合将数据与 <code>&lt;input&gt;</code> 值同步。 事实上，这就是 <code>v-model</code> 在幕后所做的。 但是，确切的事件和属性组合因输入类型而异，并且比仅使用 <code>v-model</code> 快捷方式需要更多代码。</p>
```suggestion
  <p><strong>注意：</strong>你还可以通过事件和 <code>v-bind</code> 属性的组合将数据与 <code>&lt;input&gt;</code> 值同步。事实上，这就是 <code>v-model</code> 在幕后所做的。但是，确切的事件和属性组合因输入类型而异，并且比仅使用 <code>v-model</code> 快捷方式需要更多代码。</p>
```

2022-05-29 05:13 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +<h2 id="Changing_v-model_behavior_with_modifiers">使用修饰符改变<code>v-model</code>行为</h2>
```suggestion
<h2 id="Changing_v-model_behavior_with_modifiers">使用修饰符改变 <code>v-model</code> 的行为</h2>
```

2022-05-29 05:13 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +<p>与事件修饰符类似，我们也可以添加修饰符来改变 <code>v-model</code> 的行为。 在我们的案例中，有两个值得考虑。 第一个，<code>.trim</code>，将删除输入之前或之后的空格。 我们可以将修饰符添加到我们的 <code>v-model</code> 语句中，如下所示：<code>v-model.trim="label"</code>。</p>
```suggestion
<p>与事件修饰符类似，我们也可以添加修饰符来改变 <code>v-model</code> 的行为。在我们的案例中，有两个值得考虑。第一个，<code>.trim</code>，将删除输入之前或之后的空格。我们可以将修饰符添加到我们的 <code>v-model</code> 语句中，如下所示：<code>v-model.trim="label"</code>。</p>
```

2022-05-29 05:13 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +<p>我们应该考虑的第二个修饰符称为 <code>.lazy</code>。 当 <code>v-model</code> 同步文本输入的值时，此修饰符会发生变化。 如前所述，<code>v-model</code> 同步通过使用事件更新变量来工作。 对于文本输入，此同步使用 <a href="/en-US/docs/Web/API/HTMLElement/input_event"><code>
```suggestion
<p>我们应该考虑的第二个修饰符称为 <code>.lazy</code>。当 <code>v-model</code> 同步文本输入的值时，此修饰符会发生变化。如前所述，<code>v-model</code> 同步通过使用事件更新变量来工作。对于文本输入，此同步使用 <a href="/en-US/docs/Web/API/HTMLElement/input_event"><code>input</code> 事件</a>进行。 通常，这意味着 Vue 在每次击键后都会同步数据。<code>.lazy</code> 修饰符导致 <code>v-model</code> 使用 <a href="/zh-CN/docs/Web/API/HTMLElement/change_event"><code>change</code> 事件</a> 代替。这意味着 Vue 只会在输入失去焦点或提交表单时同步数据。 就我们的目的而言，这更合理，因为我们只需要最终数据。</p>
```

2022-05-29 05:13 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +<p>要同时使用 <code>.lazy</code> 修饰符和 <code>.trim</code> 修饰符，我们可以将它们链接起来，例如 <code>v-model.lazy.trim="label"</code>.</p>
```suggestion
<p>要同时使用 <code>.lazy</code> 修饰符和 <code>.trim</code> 修饰符，我们可以将它们链接起来，例如 <code>v-model.lazy.trim="label"</code>。</p>
```

2022-05-29 05:13 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +<p>在我们的 <code>ToDoForm</code> 组件中还有一件事需要修复——提交后，<code>&lt;input&gt;</code> 仍然包含旧值。 但这很容易解决——因为我们使用 <code>v-model</code> 将数据绑定到 <code>ToDoForm</code> 中的 <code>&lt;input&gt;</code>，如果 我们将 name 参数设置为空字符
```suggestion
<p>在我们的 <code>ToDoForm</code> 组件中还有一件事需要修复——提交后，<code>&lt;input&gt;</code> 仍然包含旧值。但这很容易解决——因为我们使用 <code>v-model</code> 将数据绑定到 <code>ToDoForm</code> 中的 <code>&lt;input&gt;</code>，如果 我们将 name 参数设置为空字符串，输入也会更新。</p>
```

2022-05-29 05:13 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +<p>将您的 <code>ToDoForm</code> 组件的 <code>onSubmit()</code> 方法更新为：</p>
```suggestion
<p>将你的 <code>ToDoForm</code> 组件的 <code>onSubmit()</code> 方法更新为：</p>
```

2022-05-29 05:13 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +<p>现在，当您单击“添加”按钮时，“new-todo-input”将自行清除。</p>
```suggestion
<p>现在，当你单击“添加”按钮时，“new-todo-input”将自行清除。</p>
```

2022-05-29 05:23 UTC, yin1999 requested changes

2022-05-29 05:23 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +<p>现在，当您查看正在运行的站点时，您应该会看到显示的新表单。</p>
```suggestion
<p>现在，当你查看正在运行的站点时，你应该会看到显示的新表单。</p>
```

2022-05-29 05:23 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +<p>如果您填写并单击“添加”按钮，页面会将表单发送回服务器，但这并不是我们真正想要的。我们真正想要做的是在 <a href="/zh-CN/docs/Web/API/HTMLFormElement/submit_event"><code>submit</code> 事件</a>上运行一个方法，该方法将添加 <code>App</code> 中定义的 <code>ToDoItem</code>
```suggestion
<p>如果你填写并单击“添加”按钮，页面会将表单发送回服务器，但这并不是我们真正想要的。我们真正想要做的是在 <a href="/zh-CN/docs/Web/API/HTMLFormElement/submit_event"><code>submit</code> 事件</a>上运行一个方法，该方法将添加 <code>App</code> 中定义的 <code>ToDoItem</code> 数据列表的新待办事项。为此，我们需要向组件实例添加一个方法。</p>
```

2022-05-29 05:23 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +<p>我们需要将方法添加到 <code>ToDoForm</code> 组件对象中，以使方法可用。这是在组件的 <code>methods</code> 属性中完成的，它与 <code>data()</code>、<code>props</code> 等位于同一位置。<code>methods</code> 属性包含我们可能需要在组件中调用的任何方法。引用时，方法已完全运行，因此使用它们在模板内
```suggestion
<p>我们需要将方法添加到 <code>ToDoForm</code> 组件对象中，以使方法可用。这是在组件的 <code>methods</code> 属性中完成的，它与 <code>data()</code>、<code>props</code> 等位于同一位置。<code>methods</code> 属性包含我们可能需要在组件中调用的任何方法。引用时，方法已完全运行，因此使用它们在模板内显示信息不是一个好主意。为了显示通过计算获得的数据，你应该使用 <code>computed</code> 属性，我们稍后会介绍。</p>
```

2022-05-29 05:23 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +  <p>接下来我们需要将该方法绑定到我们的 <code>&lt;form&gt;</code> 元素的 <code>submit</code> 事件处理程序。 就像 Vue 如何使用 <code><a href="https://vuejs.org/v2/api/#v-bind">v-bind</a></code> 语法来绑定属性，Vue 有 用于事件处理的特殊指令：<code><a href
```suggestion
  <p>接下来我们需要将该方法绑定到我们的 <code>&lt;form&gt;</code> 元素的 <code>submit</code> 事件处理程序。 就像 Vue 如何使用 <code><a href="https://vuejs.org/v2/api/#v-bind">v-bind</a></code> 语法来绑定属性，Vue 有 用于事件处理的特殊指令：<code><a href="https://vuejs.org/v2/api/#v-on">v-on</a></code>。 <code>v-on</code> 指令通过 <code>v-on:event="method"</code> 语法工作。 和 <code>v-bind</code> 很像，还有一个简写语法：<code>@event="method"</code>。为了保持一致性，我们将在此处使用简写语法。 将 <code>submit</code> 处理程序添加到你的 <code>&lt;form&gt;</code> 元素，如下所示：</p>
```

2022-05-29 05:23 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +  <p>当您运行此程序时，应用程序仍会将数据发布到服务器，从而导致刷新。由于我们在客户端上进行所有处理，因此没有服务器来处理回发。我们还会在页面刷新时丢失所有本地状态。为了防止浏览器发布到服务器，我们需要阻止事件的默认操作通过页面冒泡（<code><a href="/zh-CN/docs/Web/API/Event/preventDefault">Event .preventDefault()
```suggestion
  <p>当你运行此程序时，应用程序仍会将数据发布到服务器，从而导致刷新。由于我们在客户端上进行所有处理，因此没有服务器来处理回发。我们还会在页面刷新时丢失所有本地状态。为了防止浏览器发布到服务器，我们需要阻止事件的默认操作通过页面冒泡（<code><a href="/zh-CN/docs/Web/API/Event/preventDefault">Event .preventDefault()</a></code>，在原生 JavaScript 中）。Vue 有一个特殊的语法叫做 <strong>event modifiers</strong> 可以在我们的模板中为我们处理这个问题。修饰符被附加到事件的末尾，带有一个点，如下所示：<code>@event.modifier</code>。以下是事件修饰符列表：</p>
```

2022-05-29 05:23 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +<p>如果您现在尝试提交表单，您会注意到页面没有重新加载。如果打开控制台，可以看到我们在 <code>onSubmit()</code> 方法中添加的 <code><a href="/zh-CN/docs/Web/API/Console/log">console.log()</a></code> 所输出结果。</p>
```suggestion
<p>如果你现在尝试提交表单，你会注意到页面没有重新加载。如果打开控制台，可以看到我们在 <code>onSubmit()</code> 方法中添加的 <code><a href="/zh-CN/docs/Web/API/Console/log">console.log()</a></code> 所输出结果。</p>
```

2022-05-29 05:23 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +  <p>您的组件对象现在应该如下所示：</p>
```suggestion
  <p>你的组件对象现在应该如下所示：</p>
```

2022-05-29 05:23 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +  <p>更新您的 <code>onSubmit()</code> 方法，使其如下所示：</p>
```suggestion
  <p>更新你的 <code>onSubmit()</code> 方法，使其如下所示：</p>
```

2022-05-29 05:23 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +  <p>现在回到您正在运行的应用程序，在 <code>&lt;input&gt;</code> 字段中添加一些文本，然后单击“添加”按钮。 您应该会看到您输入的值已记录到控制台，例如：</p>
```suggestion
  <p>现在回到你正在运行的应用程序，在 <code>&lt;input&gt;</code> 字段中添加一些文本，然后单击“添加”按钮。 你应该会看到你输入的值已记录到控制台，例如：</p>
```

2022-05-29 05:23 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +<p>如上所示更新您的 <code>v-model</code> 属性以链接 <code>lazy</code> 和 <code>trim</code>，然后再次测试您的应用。 例如，尝试提交一个两端都有空格的值。</p>
```suggestion
<p>如上所示更新你的 <code>v-model</code> 属性以链接 <code>lazy</code> 和 <code>trim</code>，然后再次测试你的应用。 例如，尝试提交一个两端都有空格的值。</p>
```

2022-05-29 05:23 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +  <p>当您提交 <code>ToDoForm</code> 时，您应该会看到来自 <code>addToDo()</code> 方法的控制台日志。 这很好，但我们仍然没有将任何数据传递回 <code>App.vue</code> 组件。 我们可以通过将额外的参数传递给 <code>ToDoForm</code> 组件中的 <code>this.$emit()</code> 函数来做到这一点。
```suggestion
  <p>当你提交 <code>ToDoForm</code> 时，你应该会看到来自 <code>addToDo()</code> 方法的控制台日志。 这很好，但我们仍然没有将任何数据传递回 <code>App.vue</code> 组件。 我们可以通过将额外的参数传递给 <code>ToDoForm</code> 组件中的 <code>this.$emit()</code> 函数来做到这一点。</p>
```

2022-05-29 05:23 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +  <p>在这种情况下，当我们触发事件时，我们希望将 <code>label</code> 数据连同它一起传递。 这是通过在 <code>$emit()</code> 方法中包含您要作为另一个参数传递的数据来完成的：<code>this.$emit("todo-added", this.label)</code >。 这类似于原生 JavaScript 事件如何包含数据，除了自定义 Vue 事件
```suggestion
  <p>在这种情况下，当我们触发事件时，我们希望将 <code>label</code> 数据连同它一起传递。 这是通过在 <code>$emit()</code> 方法中包含你要作为另一个参数传递的数据来完成的：<code>this.$emit("todo-added", this.label)</code>。 这类似于原生 JavaScript 事件如何包含数据，除了自定义 Vue 事件默认不包含事件对象。 这意味着发出的事件将直接匹配你提交的任何对象。 所以在我们的例子中，我们的事件对象只是一个字符串。</p>
```

2022-05-29 05:23 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +<p>如果您再次测试您的表单，您将在提交时看到您在控制台中输入的任何文本。 Vue 自动将 <code>this.$emit()</code> 中事件名称后面的参数传递给您的事件处理程序。</p>
```suggestion
<p>如果你再次测试你的表单，你将在提交时看到你在控制台中输入的任何文本。Vue 自动将 <code>this.$emit()</code> 中事件名称后面的参数传递给您的事件处理程序。</p>
```

2022-05-29 05:23 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +  <p>再次尝试测试您的表单，您应该会看到新的待办事项被附加到列表的末尾。</p>
```suggestion
  <p>再次尝试测试你的表单，你应该会看到新的待办事项被附加到列表的末尾。</p>
```

2022-05-29 05:23 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +  <p>在我们继续之前，让我们做进一步的改进。如果您在输入为空时提交表单，则没有文本的待办事项仍会添加到列表中。为了解决这个问题，我们可以防止在 name 为空时触发 todo-added 事件。由于 <code>.trim</code> 指令已经对 name 进行了修剪，因此我们只需要测试空字符串。回到你的 <code>ToDoForm</code> 组件，像这样更新 <code>onSub
```suggestion
  <p>在我们继续之前，让我们做进一步的改进。如果你在输入为空时提交表单，则没有文本的待办事项仍会添加到列表中。为了解决这个问题，我们可以防止在 name 为空时触发 todo-added 事件。由于 <code>.trim</code> 指令已经对 name 进行了修剪，因此我们只需要测试空字符串。回到你的 <code>ToDoForm</code> 组件，像这样更新 <code>onSubmit()</code> 方法。如果标签值为空，我们就不发出 <code>todo-added</code> 事件。</p>
```

2022-05-29 05:23 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> + <p>再次尝试您的表单。 现在您将无法将空项目添加到待办事项列表中。</p> </li>
```suggestion
 <p>再次尝试你的表单。 现在你将无法将空项目添加到待办事项列表中。</p> </li>
```

2022-05-29 05:25 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +    <p>Vue 组件被编写为管理应用程序数据的 JavaScript 对象和映射到底层 DOM 结构的基于 HTML 的模板语法的组合。 对于安装，以及使用 Vue 的一些更高级的功能（如单文件组件或渲染功能），您需要一个安装了 node + npm 的终端。</p>
```suggestion
    <p>Vue 组件被编写为管理应用程序数据的 JavaScript 对象和映射到底层 DOM 结构的基于 HTML 的模板语法的组合。 对于安装，以及使用 Vue 的一些更高级的功能（如单文件组件或渲染功能），你需要一个安装了 node + npm 的终端。</p>
```

2022-05-29 05:25 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +  <p>我们现在需要一些方法将 <code>new-todo-input</code> <code>&lt;input&gt;</code> 字段的值附加到 <code>label</code> 字段。Vue 对此有一个特殊的指令：<code><a href="https://vuejs.org/v2/api/#v-model">v-model</a></code>。<code>v-model
```suggestion
  <p>我们现在需要一些方法将 <code>new-todo-input</code> <code>&lt;input&gt;</code> 字段的值附加到 <code>label</code> 字段。Vue 对此有一个特殊的指令：<code><a href="https://vuejs.org/v2/api/#v-model">v-model</a></code>。<code>v-model</code> 绑定到你在其上设置的数据属性，并使其与 <code>&lt;input&gt;</code> 保持同步。<code>v-model</code> 适用于所有不同的输入类型，包括复选框、单选框和选择输入。要使用 <code>v-model</code>，你需要向 <code>&lt;input&gt;</code> 添加一个结构为 <code>v-model="variable"</code> 的属性。<p>
```

2022-05-29 05:25 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +<p>如果你再次测试你的表单，你将在提交时看到你在控制台中输入的任何文本。Vue 自动将 <code>this.$emit()</code> 中事件名称后面的参数传递给您的事件处理程序。</p>
```suggestion
<p>如果你再次测试你的表单，你将在提交时看到你在控制台中输入的任何文本。Vue 自动将 <code>this.$emit()</code> 中事件名称后面的参数传递给你的事件处理程序。</p>
```

2022-05-29 05:31 UTC, yin1999 commented on files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.html
> +    <p>熟悉核心 <a href="/zh-CN/docs/Learn/HTML">HTML</a>、<a href="/zh-CN/docs/Learn/CSS">CSS</ a> 和 <a href="/zh-CN/docs/Learn/JavaScript">JavaScript</a> 语言，了解 <a href="/zh-CN/docs/Learn/Tools_and_testi
```suggestion
    <p>熟悉核心 <a href="/zh-CN/docs/Learn/HTML">HTML</a>、<a href="/zh-CN/docs/Learn/CSS">CSS</a> 和 <a href="/zh-CN/docs/Learn/JavaScript">JavaScript</a> 语言，了解 <a href="/zh-CN/docs/Learn/Tools_and_testing/Understanding_client-side_tools /Command_line">终端/命令行</a>。</p>
```

2022-05-29 05:35 UTC, merged