docs: html to markdown
mdn/translated-content pull request #5853
Opened 2022-05-27 12:22 UTC by YangFong

2022-05-27 12:29 UTC, yin1999 commented
please read [markdown in mdn](https://developer.mozilla.org/zh-CN/docs/MDN/Contribute/Markdown_in_MDN) first, it will help you to understand how to convert a html to markdown.

Then, the covnertion should have two commits (Ref: #5812):

1. rename the html file to markdown file, using `git mv /path/to/html /path/to/md`
2. convert the content from html to markdown.

2022-05-27 12:37 UTC, yin1999 requested changes

2022-05-27 12:37 UTC, yin1999 commented on files/zh-cn/web/html/element/hr/index.md
> +**HTML <code>&lt;hr&gt;</code>  元素**表示段落级元素之间的主题转换（例如，一个故事中的场景的改变，或一个章节的主题的改变）。
the `<code>&lt;hr&gt;</code>` should be ``` `<hr>` ``` in markdown:

```suggestion
**HTML `<hr>` 元素**表示段落级元素之间的主题转换（例如，一个故事中的场景的改变，或一个章节的主题的改变）。
```

2022-05-27 12:37 UTC, yin1999 commented on files/zh-cn/web/html/element/hr/index.md
> +{{EmbedInteractiveExample("pages/tabbed/hr.html", "tabbed-shorter")}}</div>
```suggestion
{{EmbedInteractiveExample("pages/tabbed/hr.html", "tabbed-shorter")}}
```

2022-05-27 12:37 UTC, yin1999 commented on files/zh-cn/web/html/element/hr/index.md
> +</div>
See markdown in mdn:

```suggestion
> **备注：** 要更改 `<hr>` 与段落之间的间隙或样式，请使用 [CSS](/zh-CN/docs/CSS)。
```

2022-05-27 12:37 UTC, yin1999 commented on files/zh-cn/web/html/element/hr/index.md
> +</ul>
convert to markdown style

2022-05-27 12:37 UTC, yin1999 commented on files/zh-cn/web/html/element/hr/index.md
> +</dl>
```suggestion
- {{htmlattrdef("align")}} {{deprecated_inline}}
  - : 设置对齐方式。如果没有值，默认值为 `left`。
- {{htmlattrdef("color")}} {{Non-standard_inline}}
  - : 使用颜色名或十六进制设置颜色。
- {{htmlattrdef("noshade")}} {{deprecated_inline}}
  - : 去除阴影。
- {{htmlattrdef("size")}} {{deprecated_inline}}
  - : 使用像素设置高度。
- {{htmlattrdef("width")}} {{deprecated_inline}}
  - : 使用像素或者百分比设置宽度。
```

2022-05-27 12:37 UTC, yin1999 commented on files/zh-cn/web/html/element/hr/index.md
> +&lt;/p&gt;</code></pre>
covnert to code block, see markdown in mdn.

2022-05-27 12:37 UTC, yin1999 commented on files/zh-cn/web/html/element/hr/index.md
> +{{EmbedLiveSample("Example")}}
match with the translated id `Example` ---> `示例`

```suggestion
{{EmbedLiveSample("示例")}}
```

2022-05-27 12:37 UTC, yin1999 commented on files/zh-cn/web/html/element/hr/index.md
> +| {{SpecName('HTML4.01', 'present/graphics.html#h-15.3', '&lt;hr&gt;')}}            | {{Spec2('HTML4.01')}}    |                                                 |
using macro instead, refer [mdn/content](https://github.com/mdn/content/blob/e5f88575a8a15393caa8c8bb8dc92b1336aa86d8/files/en-us/web/html/element/hr/index.md?plain=1#L111):

```suggestion
{{Specifications}}
```

2022-05-27 12:37 UTC, yin1999 commented on files/zh-cn/web/html/element/hr/index.md
> +## 相关内容
translate to `参见`：

```suggestion
## 参见
```

2022-05-28 02:10 UTC, yin1999 requested changes

2022-05-28 02:10 UTC, yin1999 commented on files/zh-cn/web/html/element/hr/index.md
> +- *DOM 接口* {{domxref("HTMLHRElement")}}
请将其更新为属性表：

```suggestion
<table class="properties">
  <tbody>
    <tr>
      <th scope="row">
        <a href="/zh-CN/docs/Web/Guide/HTML/Content_categories"
          >内容分类</a
        >
      </th>
      <td>
        <a href="/zh-CN/docs/Web/Guide/HTML/Content_categories#流式元素（flow_content）"
          >流式元素</a
        >。
      </td>
    </tr>
    <tr>
      <th scope="row">允许的内容</th>
      <td>无，是一个{{Glossary("empty element", "空元素")}}。</td>
    </tr>
    <tr>
      <th scope="row">标签省略</th>
      <td>必须有开始标签，不能有结束标签。</td>
    </tr>
    <tr>
      <th scope="row">允许的父元素</th>
      <td>
        所有接受<a href="/zh-CN/docs/Web/Guide/HTML/Content_categories#流式元素（flow_content）"
          >流式元素</a
        >的元素。
      </td>
    </tr>
    <tr>
      <th scope="row">隐式 ARIA 角色</th>
      <td>{{ARIARole("separator")}}</td>
    </tr>
    <tr>
      <th scope="row">允许的 ARIA 角色</th>
      <td>
        {{ARIARole("presentation")}} 或 {{ARIARole("none")}}
      </td>
    </tr>
    <tr>
      <th scope="row">DOM 接口</th>
      <td>{{domxref("HTMLHRElement")}}</td>
    </tr>
  </tbody>
</table>
```

2022-05-28 02:10 UTC, yin1999 commented on files/zh-cn/web/html/element/hr/index.md
> +该元素包含 <a href="zh-CN/docs/Web/HTML/Global_attributes">全局属性</a>
转换为 markdown:

```suggestion
该元素包含[全局属性](/zh-CN/docs/Web/HTML/Global_attributes)。
```

2022-05-28 02:10 UTC, yin1999 commented on files/zh-cn/web/html/element/hr/index.md
> +{Compat("html.elements.hr")}}
```suggestion
{{Compat}}
```

2022-05-28 11:37 UTC, YangFong commented
不太简单，需要考虑的事情不少

2022-05-28 11:40 UTC, yin1999 commented
因为这是一个 html to markdown 转换的pr，为保持文档的修改记录，需要将 commit 拆分为 2 个：

1. 第一个commit，将html文件重命名为markdown文件（运行命令 `git mv /path/to/html /path/to/markdown`）
2. 第二个commit，将文件的内容转换为 markdown。

若对此感到困难，可以另开 PR，或由我协助完成本次 convertion。

2022-05-28 11:44 UTC, YangFong commented
@yin1999 是要将过程浓缩为两次 commit 吗，那么这一个 PR 该怎么算。

2022-05-28 11:46 UTC, yin1999 commented
> @yin1999 是要将过程浓缩为两次 commit 吗，那么这一个 PR 该怎么算。

是的，而且第一个commit需要是文件重命名（使用 git mv 命令）

2022-05-28 11:50 UTC, YangFong commented
@yin1999 那么，是重新开一个 PR，还是在此基础上进行修改。

2022-05-28 11:54 UTC, yin1999 commented
> @yin1999 那么，是重新开一个 PR，还是在此基础上进行修改。

都可以，如果是在本pr的基础上修改，可通过以下的方式进行：

1. 首先复制 markdown 文件中的所有内容到其它文件
2. 运行命令 `git reset HEAD~5 --hard` 撤销最近的 5 次 commit
3. 运行命令 `git mv files/zh-cn/web/html/element/hr/index.html files/zh-cn/web/html/element/hr/index.md` 将文件重命名为 markdown 文件，并提交 commit
4. 打开重命名后的 markdown 文件，将复制的 markdown 文件内容粘贴到文件中，保存并提交 commit
5. 使用命令 `git push origin --force` 强制推送到远程仓库

如果对此还不太熟悉，我可以协助完成

2022-05-28 12:03 UTC, merged