zh-CN:translate readableStream/pipeto
mdn/translated-content pull request #5870
Opened 2022-05-28 07:04 UTC by Jack-Zhang-1314

2022-05-30 12:53 UTC, yin1999 requested changes

2022-05-30 12:53 UTC, yin1999 commented on files/zh-cn/web/api/readablestream/pipeto/index.md
> +translation_of: api/ReadableStream/pipeTo
```suggestion
translation_of: Web/API/ReadableStream/pipeTo
```

2022-05-30 12:53 UTC, yin1999 commented on files/zh-cn/web/api/readablestream/pipeto/index.md
> +管道流通常在管道持续时间[锁定](/zh-CN/docs/Web/API/ReadableStream/locked)它，阻止其他 reader 锁定它。
```suggestion
管道流通常在管道持续时间[锁定](/zh-CN/docs/Web/API/ReadableStream/locked)这个流，并阻止其他 reader 锁定它。
```
```suggestion
管道流通常在管道持续时间[锁定](/zh-CN/docs/Web/API/ReadableStream/locked)它，阻止其他 reader 锁定它。
```

2022-05-30 12:53 UTC, yin1999 commented on files/zh-cn/web/api/readablestream/pipeto/index.md
> +{{domxref("ReadableStream")}} 接口的 **`pipeTo()`** 方法通过管道将当前的 `ReadableStream` 输出到给定的 {{domxref("WritableStream")}} 并且当管道过程成功完成时返回一个兑现的 {{jsxref("Promise")}}，如果遇到任何错误则返回一个拒绝的 Promise。
这段话的翻译错误，请更正。然后，“prping process”我觉得翻译成“传输过程”会更好些

2022-05-30 12:53 UTC, yin1999 commented on files/zh-cn/web/api/readablestream/pipeto/index.md
> +{{domxref("ReadableStream")}} 接口的 **`pipeTo()`** 方法通过管道将当前的 `ReadableStream` 输出到给定的 {{domxref("WritableStream")}} 并且当管道过程成功完成时返回一个兑现的 {{jsxref("Promise")}}，如果遇到任何错误则返回一个拒绝的 Promise。
这段话的翻译错误，请更正。然后，“prping process”我觉得翻译成“传输过程”会更好些

2022-05-30 12:53 UTC, yin1999 commented on files/zh-cn/web/api/readablestream/pipeto/index.md
> +管道流通常在管道持续时间[锁定](/zh-CN/docs/Web/API/ReadableStream/locked)它，阻止其他 reader 锁定它。
better?

```suggestion
传输一个流时通常会在传输的持续时间内[锁定](/zh-CN/docs/Web/API/ReadableStream/locked)这个流，以阻止其他 reader 锁定它。
```

2022-05-30 12:53 UTC, yin1999 commented on files/zh-cn/web/api/readablestream/pipeto/index.md
> +管道流通常在管道持续时间[锁定](/zh-CN/docs/Web/API/ReadableStream/locked)它，阻止其他 reader 锁定它。
“管道”在中文中很难被认为是动词，所以请修改中文翻译，以使读者更易读懂。对于该处以及下面代码中的翻译，请一并改进

```suggestion
传输一个流时通常会在传输的持续时间内[锁定](/zh-CN/docs/Web/API/ReadableStream/locked)这个流，以阻止其他 reader 锁定它。
```

2022-05-31 02:18 UTC, yin1999 requested changes

2022-05-31 02:18 UTC, yin1999 commented on files/zh-cn/web/api/readablestream/pipeto/index.md
> +  - : 管道至 `writable` 应该被使用的选项。可用选项是:
同先前提到的

2022-05-31 02:18 UTC, yin1999 commented on files/zh-cn/web/api/readablestream/pipeto/index.md
> +      - : 如果设置一个 [`AbortSignal`](/zh-CN/docs/Web/API/AbortSignal) 对象，然后可以通过相应的[`AbortController`](/zh-CN/docs/Web/API/AbortController)中止正在进行的管道操作。
同先前提到的

2022-05-31 02:18 UTC, yin1999 commented on files/zh-cn/web/api/readablestream/pipeto/index.md
> +当管道完成时返回一个兑现的 {{jsxref("Promise")}}。
同先前提到的，这里也不是返回一个的兑现的 promise，而是“返回一个 promise，其在传输完成时兑现。”

2022-05-31 02:26 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/readablestream/pipeto/index.md
> +  - : 管道至 `writable` 应该被使用的选项。可用选项是:
还在改进中,感谢建议

2022-05-31 07:14 UTC, yin1999 requested changes

2022-05-31 07:20 UTC, merged