AutoCorrect files/zh-cn/svg
mdn/translated-content pull request #5875
Opened 2022-05-28 07:38 UTC by huacnlee

https://github.com/mdn/translated-content/pull/4191
https://github.com/mdn/translated-content/pull/5726

2022-05-28 07:40 UTC, yin1999 commented
Could you create an issue for tracking the process? Just like #5436.

2022-05-28 07:46 UTC, yin1999 requested changes

2022-05-28 07:46 UTC, yin1999 commented on files/zh-cn/web/svg/applying_svg_effects_to_html_content/index.html
> +<h2 id="使用内嵌SVG">使用内嵌 SVG</h2>
The process won't update the id

`使用内嵌 SVG` ---> `使用内嵌_svg`

process:

1. replace space with `_`
2. remove all symble like `()`
3. covnert to lower case

2022-05-28 07:57 UTC, huacnlee commented on files/zh-cn/web/svg/applying_svg_effects_to_html_content/index.html
> +<h2 id="使用内嵌SVG">使用内嵌 SVG</h2>
I see

2022-05-28 09:44 UTC, huacnlee commented on files/zh-cn/web/svg/applying_svg_effects_to_html_content/index.html
> +<h2 id="使用内嵌SVG">使用内嵌 SVG</h2>
我想了想，这个 Heading 的 id 还是不能改，影响外部链接

2022-05-28 10:20 UTC, yin1999 commented on files/zh-cn/web/svg/applying_svg_effects_to_html_content/index.html
> +<h2 id="使用内嵌SVG">使用内嵌 SVG</h2>
以后该文档转换为 markdown 后，id会自动根据上述规则生成，仍会影响外部链接

2022-05-28 12:27 UTC, huacnlee reviewed
以上 Heading 的 id 我已经修改过了，其他 77 个文件也都检查过

2022-05-28 21:56 UTC, merged

2022-05-30 05:06 UTC, irvin commented on files/zh-cn/web/svg/applying_svg_effects_to_html_content/index.html
> +<h2 id="使用内嵌SVG">使用内嵌 SVG</h2>
終究還是會 h2m 或漸次人工轉換成 markdown，我認為格式檢查可以不處理這個問題