AutoCorrect files/zh-cn/web/api/f*/
mdn/translated-content pull request #5928
Opened 2022-05-28 08:55 UTC by huacnlee

2022-06-02 12:07 UTC, yin1999 commented
@huacnlee, conflict, please rebase

2022-06-04 11:57 UTC, huacnlee commented
@yin1999 Just updated

2022-06-04 12:12 UTC, yin1999 requested changes

2022-06-04 12:12 UTC, yin1999 commented on files/zh-cn/web/api/fetch_api/using_fetch/index.md
> +- {{domxref("Response.statusText")}} — 字符串（默认值为 ""），该值与 HTTP 状态码消息对应。注意：HTTP/2 [不支持](https://fetch.spec.whatwg.org/#concept-response-status-message) 状态消息
```suggestion
- {{domxref("Response.statusText")}} — 字符串（默认值为 ""），该值与 HTTP 状态码消息对应。注意：HTTP/2 [不支持](https://fetch.spec.whatwg.org/#concept-response-status-message)状态消息
```

2022-06-04 12:12 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/respondwith/index.html
> +<p>有关跨域内容污染的渲染端安全检测与 {{domxref("Response")}} 体的透明度（或者不透明度）相关联，而不是 URL。如果 request 是一个顶级的导航，而返回值是一个类型属性不透明的 {{domxref("Response")}}（即不透明响应体），一个 <a class="external external-icon" href="http://fetch.spec
```suggestion
<p>有关跨域内容污染的渲染端安全检测与 {{domxref("Response")}} 体的透明度（或者不透明度）相关联，而不是 URL。如果 request 是一个顶级的导航，而返回值是一个类型属性不透明的 {{domxref("Response")}}（即不透明响应体），一个 <a href="https://fetch.spec.whatwg.org/#concept-network-error">network error</a> 将被返回给 <a href="https://fetch.spec.whatwg.org/#concept-fetch"><code>Fetch</code></a>。所有成功（非网络错误）响应的最终 URL 是请求的 URL。</p>
```

2022-06-04 12:12 UTC, yin1999 commented on files/zh-cn/web/api/file_api/using_files_from_web_applications/index.html
> +<h2 id="示例：使用对象URL来显示图片">示例：使用对象 URL 来显示图片</h2>
```suggestion
<h2 id="示例：使用对象_url_来显示图片">示例：使用对象 URL 来显示图片</h2>
```

2022-06-04 12:14 UTC, yin1999 commented on files/zh-cn/web/api/fetch_api/using_fetch/index.md
> +- `fetch` **不会发送跨域 cookie**，除非你使用了 _credentials_ 的[初始化选项](/zh-CN/docs/Web/API/fetch#参数)。（自 [2018 年 8 月](https://github.com/whatwg/fetch/pull/585) 以后，默认的 credentials 政策变更为 `same-origin`。Firefox 也在 61.
```suggestion
- `fetch` **不会发送跨域 cookie**，除非你使用了 _credentials_ 的[初始化选项](/zh-CN/docs/Web/API/fetch#参数)。（自 [2018 年 8 月](https://github.com/whatwg/fetch/pull/585)以后，默认的 credentials 政策变更为 `same-origin`。Firefox 也在 61.0b13 版本中进行了修改）
```

2022-06-04 12:14 UTC, yin1999 commented on files/zh-cn/web/api/fetch_api/using_fetch/index.md
>  > **备注：** [Body](#Body) 还有其他相似的方法，用于获取其他类型的内容。
```suggestion
> **备注：** [Body](#body) 还有其他相似的方法，用于获取其他类型的内容。
```

2022-06-04 12:18 UTC, merged