AutoCorrect files/zh-cn/web/javascript/reference/operators/
mdn/translated-content pull request #5965
Opened 2022-05-28 12:40 UTC by huacnlee

2022-05-28 12:42 UTC, yin1999 commented
请等待当前的工作都完成后继续新的工作

2022-05-29 01:38 UTC, yin1999 requested changes

2022-05-29 01:38 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/addition/index.html
> +<pre class="syntaxbox"><strong>表达式：</strong> <var>x</var> + <var>y</var>
```suggestion
<pre class="brush: js">>x + y
```

2022-05-29 01:38 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/async_function/index.html
> +original_slug: Web/JavaScript/Reference/Operators/async 允许声明一个函数为一个包含异步操作的函数
should not be modified, please consider how to deal with it

```suggestion
original_slug: Web/JavaScript/Reference/Operators/async允许声明一个函数为一个包含异步操作的函数
```

2022-05-29 01:38 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/bitwise_not/index.html
> +<p>按位非运算时，任何数字<code>x 的运算结果都是</code><code>-(x + 1)</code>。例如，<code>〜-5</code>运算结果为<code>4</code>。</p>
```suggestion
<p>按位非运算时，任何数字 <code>x</code> 的运算结果都是<code>-(x + 1)</code>。例如， <code>〜-5</code> 运算结果为 <code>4</code>。</p>
```

2022-05-29 01:38 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/decrement/index.html
> +<pre class="syntaxbox"><strong>操作符：</strong> <var>x</var>-- or --<var>x</var>
```suggestion
<pre class="brush: js">x--
--x
```

2022-05-29 01:38 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/delete/index.html
> +<p>让我们来看看相同的代码在严格模式下会有怎样的表现。会抛出一个语法错误（ <code>SyntaxError）而不是返回 false。</code></p>
```suggestion
<p>让我们来看看相同的代码在严格模式下会有怎样的表现。会抛出一个语法错误（<code>SyntaxError</code>）而不是返回 false。</p>
```

2022-05-29 01:38 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/division/index.html
> +<h3 id="除以0">除以 0</h3>
```suggestion
<h3 id="除以_0">除以 0</h3>
```

2022-05-29 01:38 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/equality/index.html
> +<h3 id="比较字符串和String对象">比较字符串和 String 对象</h3>
```suggestion
<h3 id="比较字符串和_string_对象">比较字符串和 String 对象</h3>
```

2022-05-29 01:38 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/greater_than/index.html
> +<h3 id="Boolean_null_undefined_NaN的比较">Boolean, null, undefined, NaN 的比较</h3>
```suggestion
<h3 id="Boolean_null_undefined_NaN_的比较">Boolean, null, undefined, NaN 的比较</h3>
```

2022-05-29 01:38 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/index.html
> +<h3 id="条件三元运算符">条件 (三元) 运算符</h3>
```suggestion
<h3 id="条件（三元）运算符">条件（三元）运算符</h3>
```

2022-05-29 01:38 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/object_initializer/index.html
> +<h2 id="对象字面量表示法与JSON">对象字面量表示法与 JSON</h2>
```suggestion
<h2 id="对象字面量表示法与_json">对象字面量表示法与 JSON</h2>
```

2022-05-29 01:38 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/remainder/index.html
> +<h3 id="被除数为NaN">被除数为 NaN</h3>
```suggestion
<h3 id="被除数为_nan">被除数为 NaN</h3>
```

2022-05-29 01:38 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/spread_syntax/index.html
> +<h4 id="等价于apply的方式">等价于 apply 的方式</h4>
```suggestion
<h4 id="等价于_apply_的方式">等价于 apply 的方式</h4>
```

2022-05-29 01:38 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/spread_syntax/index.html
> +<p>没有展开语法的时候，只能组合使用 <code>push</code>, <code>splice</code>, <code>concat</code> 等方法，来将已有数组元素变成新数组的一部分。有了展开语法，  通过字面量方式，构造新数组会变得更简单、更优雅：</p>
```suggestion
<p>没有展开语法的时候，只能组合使用 <code>push</code>, <code>splice</code>, <code>concat</code> 等方法，来将已有数组元素变成新数组的一部分。有了展开语法，通过字面量方式，构造新数组会变得更简单、更优雅：</p>
```

2022-05-29 01:38 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/spread_syntax/index.html
> +<h4 id="数组拷贝copy">数组拷贝 (copy)</h4>
```suggestion
<h4 id="数组拷贝_copy">数组拷贝 (copy)</h4>
```

2022-05-29 01:38 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/strict_inequality/index.html
> +<h3 id="比较Object对象">比较 Object 对象</h3>
```suggestion
<h3 id="比较_object_对象">比较 Object 对象</h3>
```

2022-05-29 01:38 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/this/index.html
> +<h3 id="类中的this">类中的 this</h3>
```suggestion
<h3 id="类中的_this">类中的 this</h3>
```

2022-05-29 02:26 UTC, huacnlee commented on files/zh-cn/web/javascript/reference/operators/async_function/index.html
> +original_slug: Web/JavaScript/Reference/Operators/async 允许声明一个函数为一个包含异步操作的函数
我记录一下这个 case，后续得想办法避开

2022-05-29 02:27 UTC, merged

2022-05-29 02:29 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/async_function/index.html
> +original_slug: Web/JavaScript/Reference/Operators/async 允许声明一个函数为一个包含异步操作的函数
这个问题不只有这一处，请检查现有的PR