add translation about ARIA Attributes
mdn/translated-content pull request #6068
Opened 2022-06-02 06:43 UTC by yin1999

To mv the following document to the new home, initial the translation about ARIA Attributes:

- Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-hidden_attribute
- Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute
- Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute

2022-06-02 12:08 UTC, yin1999 commented
rebase to fix pr review problem

2022-06-03 12:33 UTC, irvin requested changes

2022-06-03 12:33 UTC, irvin commented on files/zh-cn/web/accessibility/aria/attributes/index.md
> +1. ### 小部件（weiget）特性
```suggestion
1. ### 小部件（widget）特性
```

2022-06-03 12:38 UTC, yin1999 commented on files/zh-cn/web/accessibility/aria/attributes/index.md
> +{{SubpagesWithSummaries}}
waiting for mving document from `Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria*`

2022-06-04 13:21 UTC, irvin approved these changes

2022-06-04 13:21 UTC, merged