Fix duplicated sentence
mdn/translated-content pull request #6118
Opened 2022-06-04 18:27 UTC by tramio

**Issue:** fixes #5712 

**Context:** a sentence was doubled on line 124

**Changes:** removed the duplicate

2022-06-04 18:44 UTC, cw118 requested changes
Merci @tramio ! J'ai noté un commentaire, n'hésitez pas si besoin d'aide :)

2022-06-04 18:44 UTC, cw118 commented on files/fr/learn/css/css_layout/responsive_design/index.md
> +Cette approche se retrouve aujourd'hui à de nombreux endroits sur le Web, et elle est documentée dans notre article sur les [Méthodes de mises en page traditionnelles](/fr/docs/Apprendre/CSS/CSS_layo
```suggestion
Cette approche se retrouve aujourd'hui à de nombreux endroits sur le Web, et elle est documentée dans notre article sur les [méthodes de mises en page traditionnelles](/fr/docs/Learn/CSS/CSS_layout/Legacy_Layout_Methods). Il est probable que vous rencontrerez des sites web utilisant cette approche dans votre travail, donc il est utile de la comprendre, même si vous ne construiriez pas un site moderne en utilisant une grille flexible basée sur le flottement.
```

On peut utiliser le lien/slug "anglais" ici (c'est une convention sur MDN pour la locale française et cela évite la redirection) :)

2022-06-04 19:01 UTC, cw118 approved these changes
Merci pour cette correction @tramio, fusionnons tout ça 🤗

2022-06-04 19:01 UTC, merged

2022-06-04 19:04 UTC, tramio commented on files/fr/learn/css/css_layout/responsive_design/index.md
> +Cette approche se retrouve aujourd'hui à de nombreux endroits sur le Web, et elle est documentée dans notre article sur les [Méthodes de mises en page traditionnelles](/fr/docs/Apprendre/CSS/CSS_layo
Merci pour la correction, je viens de l'ajouter !

Est-ce que vous sauriez où je pourrais lire les conventions pour la locale française ? J'ai pu trouver [celles d'autres langues](https://github.com/mdn/translated-content/tree/main/docs) mais pas celles du français. 👀 🔍

2022-06-04 20:16 UTC, cw118 commented on files/fr/learn/css/css_layout/responsive_design/index.md
> +Cette approche se retrouve aujourd'hui à de nombreux endroits sur le Web, et elle est documentée dans notre article sur les [Méthodes de mises en page traditionnelles](/fr/docs/Apprendre/CSS/CSS_layo
Il n'y a pas vraiment de documents qui précisent toutes les conventions sur MDN, mais on suit [ce guide stylistique](https://github.com/mozfr/besogne/wiki/Guide-stylistique-pour-la-traduction) en utilisant par exemple l'entité HTML `&nbsp;` pour l'espace insécable qui précède certains signes de ponctuation.

En espérant que cela réponde un peu à votre question, on est dispo dans les issues/PR et aussi dans ce [salon de Matrix](https://chat.mozilla.org/#/room/#l10n-fr:mozilla.org) pour aider :)

2022-06-10 21:52 UTC, tramio commented on files/fr/learn/css/css_layout/responsive_design/index.md
> +Cette approche se retrouve aujourd'hui à de nombreux endroits sur le Web, et elle est documentée dans notre article sur les [Méthodes de mises en page traditionnelles](/fr/docs/Apprendre/CSS/CSS_layo
Mes excuses, je ne réponds que maintenant 🙀 J'ai sauvegardé le guide, merci pour la réponse et à bientôt !