clean up all `<p>`, `<dt>` and `<dd>` tag for zh-CN (Part 2)
mdn/translated-content pull request #6127
Opened 2022-06-05 05:16 UTC by yin1999

continue #6088.

2022-06-06 06:35 UTC, yin1999 commented on files/zh-cn/web/css/background-attachment/index.html
> +<p>该交互式示例网页的源码存储在 GitHub 中，如果你想为该网页项目做点贡献的话，请进此链接 <a href="https://github.com/mdn/interactive-examples">https://github.com/mdn/interactive-examples</a> 并给我们一个请求加入的回复。</p>
just removing this
```suggestion
```

2022-06-06 06:35 UTC, yin1999 commented on files/zh-cn/web/css/background-clip/index.html
> +<p>此交互样例的源代码被储存在 GitHub 库中。如果你想要对此交互样例工程有代码贡献，请点击 <a href="https://github.com/mdn/interactive-examples">https://github.com/mdn/interactive-examples</a>并向我们发送拉取请求</p>
```suggestion
```

2022-06-06 06:35 UTC, yin1999 commented on files/zh-cn/web/css/background-image/index.html
> +<p>此交互实例的代码被存储于 Github 仓库。如果你想对这些交互实例贡献代码，请 clone <a href="https://github.com/mdn/interactive-examples">https://github.com/mdn/interactive-examples</a> 并向我们发起拉取请求。</p>
```suggestion
```

2022-06-06 06:35 UTC, yin1999 commented on files/zh-cn/web/css/block-size/index.html
> +<p>这个交互例子的源码存在 Githubd 的仓库中。如果你想为这个交互例子的项目做一份贡献，请从 <a href="https://github.com/mdn/interactive-examples">https://github.com/mdn/interactive-examples</a>克隆此项目并给我们发送一个 pull 请求。</p>
```suggestion
```

2022-06-06 06:35 UTC, yin1999 commented on files/zh-cn/web/css/border-block-end/index.html
> +<p>该交互式示例的源码存储在 GitHub 存储库中。如果你想参与该项目的开发，请克隆 <a href="https://github.com/mdn/interactive-examples">https://github.com/mdn/interactive-examples</a> 并向我们发送拉取代码请求</p>
```suggestion
```

2022-06-06 06:35 UTC, yin1999 commented on files/zh-cn/web/css/box-sizing/index.html
> +<p>* { box-sizing: border-box; }</p>
```suggestion
<pre class="brush: css">* { box-sizing: border-box; }</pre>
```

2022-06-06 06:35 UTC, yin1999 commented on files/zh-cn/web/css/filter-function/drop-shadow/index.html
> +<p>这个交互式示例的源代码存储在 GitHub 存储库中。如果您想对交互式示例项目作出贡献，请克隆 <a href="https://github.com/mdn/interactive-examples">https://github.com/mdn/interactive-examples</a> 并向我们发送拉取请求。</p>
```suggestion
```

2022-06-06 06:35 UTC, yin1999 commented on files/zh-cn/web/css/flex-basis/index.html
> +<p>这个交互式的例子的源代码存储在一个 GitHub 库。如果你想为这个项目贡献代码，请克隆这个仓库 <a href="https://github.com/mdn/interactive-examples">https://github.com/mdn/interactive-examples</a> 然后给我们提交一个 pull request</p>
```suggestion
```

2022-06-06 06:35 UTC, yin1999 commented on files/zh-cn/web/css/flex/index.html
> +<p>这个交互案例的源码存储在 github 仓库。如果你想对此案例做贡献，请克隆项目<a href="https://github.com/mdn/interactive-examples">https://github.com/mdn/interactive-examples</a> 并且给我们推送一个请求 (PR)。</p>
```suggestion
```

2022-06-06 06:35 UTC, yin1999 commented on files/zh-cn/web/css/font-variant-caps/index.html
> +<p>该交互式例子的源码位于我们的 Github 仓库中。如果您有兴趣对交互式例子项目进行贡献，请克隆仓库<a href="https://github.com/mdn/interactive-examples">https://github.com/mdn/interactive-examples</a>，并向我们提出合并请求 (pull request)。</p>
```suggestion
```

2022-06-06 06:35 UTC, yin1999 commented on files/zh-cn/web/css/grid-auto-rows/index.html
> +<p>此交互式示例的源代码托管于 GitHub 中。如果您想为交互示例贡献代码，请 clone <a href="https://github.com/mdn/interactive-examples">https://github.com/mdn/interactive-examples</a> 并且给我们发送 pull request.</p>
```suggestion
```

2022-06-07 13:29 UTC, irvin requested changes
please rebase

2022-06-07 13:51 UTC, merged