translate zh-CN: writeableStream
mdn/translated-content pull request #6144
Opened 2022-06-06 09:03 UTC by fwqaaq

Hi, `sink` 和 `writer` 都没有翻译, 可能不翻译会好一点

2022-06-06 09:06 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/writablestream/index.md
> +下面的例子说明了这个接口的几个特征。它展示了使用自定义 sink 和 API 提供的排队策略创建的 `WritableStream`。然后它调用一个 `sendMessage()` 的函数，传递新创建的流和一个字符串。在这个函数内部，它调用流的 `getWriter()` 方法，该方法返回一个 {{domxref("WritableStreamDefaultWriter")}} 实例。`forE
` Finally, write() and close() return promises that are processed to deal with success or failure of chunks and streams.`

* 这句话并没有翻译的很好

2022-06-06 09:18 UTC, yin1999 commented on files/zh-cn/web/api/writablestream/index.md
> +下面的例子说明了这个接口的几个特征。它展示了使用自定义 sink 和 API 提供的排队策略创建的 `WritableStream`。然后它调用一个 `sendMessage()` 的函数，传递新创建的流和一个字符串。在这个函数内部，它调用流的 `getWriter()` 方法，该方法返回一个 {{domxref("WritableStreamDefaultWriter")}} 实例。`forE
请先尝试自己理解着翻译，另外，简单看了一下。在中文文档内请把“See Also” 统一翻译为“参见”

2022-06-06 09:42 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/writablestream/index.md
> +下面的例子说明了这个接口的几个特征。它展示了使用自定义 sink 和 API 提供的排队策略创建的 `WritableStream`。然后它调用一个 `sendMessage()` 的函数，传递新创建的流和一个字符串。在这个函数内部，它调用流的 `getWriter()` 方法，该方法返回一个 {{domxref("WritableStreamDefaultWriter")}} 实例。`forE
好的

2022-06-06 09:54 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/writablestream/index.md
> +下面的例子说明了这个接口的几个特征。它展示了使用自定义 sink 和 API 提供的排队策略创建的 `WritableStream`。然后它调用一个 `sendMessage()` 的函数，传递新创建的流和一个字符串。在这个函数内部，它调用流的 `getWriter()` 方法，该方法返回一个 {{domxref("WritableStreamDefaultWriter")}} 实例。`forE
已经词穷了 `/(ㄒoㄒ)/~~`

2022-06-06 11:03 UTC, yin1999 requested changes

2022-06-06 11:03 UTC, yin1999 commented on files/zh-cn/web/api/writablestream/index.md
> +  - : 返回 {{domxref("WritableStreamDefaultWriter")}} 新实例并且将流锁定到该实例。当流被锁定时，直到这个流被释放之前，不能获取其他 writer。
```suggestion
  - : 返回一个新的 {{domxref("WritableStreamDefaultWriter")}} 实例并且将流锁定到该实例。当流被锁定时，直到这个流被释放之前，不能获取其他 writer。
```

2022-06-07 01:09 UTC, yin1999 requested changes

2022-06-07 01:09 UTC, yin1999 commented on files/zh-cn/web/api/writablestream/index.md
> +- 在创建计数策略（第 35 行）时设置的 `highWaterMark` 属性，用于设置 `WritableStream` 实例操作单个 `write()` 时处理的最大数据量。在该示例中，它是可以发送到 `defaultWriter.write()` 的最大数据量（第 11 行）。
```suggestion
- 为创建计数策略（第 35 行）而设置的 `highWaterMark` 属性，其用于设置 `WritableStream` 实例处理单个 `write()` 操作时可接受的最大数据量。在该示例中，它是可以传递给 `defaultWriter.write()` 的最大数据量（第 11 行）。
```

2022-06-07 01:16 UTC, merged