translate zh-CN: writableStream constructor
mdn/translated-content pull request #6158
Opened 2022-06-07 07:45 UTC by Jack-Zhang-1314

2022-06-08 00:52 UTC, yin1999 commented on files/zh-cn/web/api/writablestream/writablestream/index.md
> + **`WritableStream()`** 构造函数创造一个新的 {{domxref("WritableStream")}} 对象实例。
```suggestion
**`WritableStream()`** 构造函数创造一个新的 {{domxref("WritableStream")}} 对象实例。
```

2022-06-08 00:52 UTC, yin1999 commented on files/zh-cn/web/api/writablestream/writablestream/index.md
> +    > **备注:**你可以定义一个自己的 `queuingStrategy`，或者为这个对象值使用 {{domxref("ByteLengthQueuingStrategy")}} 或 {{domxref("CountQueuingStrategy")}} 的实例。如果没有提供 `queuingStrategy`，则使用的默认值与 `CountQueuingStrategy` 相同，其 h
```suggestion
    > **备注:** 你可以定义一个自己的 `queuingStrategy`，或者为这个对象值使用 {{domxref("ByteLengthQueuingStrategy")}} 或 {{domxref("CountQueuingStrategy")}} 的实例。如果没有提供 `queuingStrategy`，则使用的默认值与 `CountQueuingStrategy` 相同，其 highWaterMark 为 1。
```

2022-06-08 00:52 UTC, yin1999 commented on files/zh-cn/web/api/writablestream/writablestream/index.md
> +    > **备注:**你可以定义一个自己的 `queuingStrategy`，或者为这个对象值使用 {{domxref("ByteLengthQueuingStrategy")}} 或 {{domxref("CountQueuingStrategy")}} 的实例。如果没有提供 `queuingStrategy`，则使用的默认值与 `CountQueuingStrategy` 相同，其 h
```suggestion
    > **备注:** 你可以定义一个自己的 `queuingStrategy`，或者为这个对象值使用 {{domxref("ByteLengthQueuingStrategy")}} 或 {{domxref("CountQueuingStrategy")}} 的实例。如果没有提供 `queuingStrategy`，则使用的默认值与 `CountQueuingStrategy` 相同，其 highWaterMark 为 1。
```
```suggestion
    > **备注:**你可以定义一个自己的 `queuingStrategy`，或者为这个对象值使用 {{domxref("ByteLengthQueuingStrategy")}} 或 {{domxref("CountQueuingStrategy")}} 的实例。如果没有提供 `queuingStrategy`，则使用的默认值与 `CountQueuingStrategy` 相同，其 highWaterMark 为 1。
```

2022-06-08 00:55 UTC, yin1999 requested changes

2022-06-08 00:55 UTC, yin1999 commented on files/zh-cn/web/api/writablestream/writablestream/index.md
> +**`WritableStream()`** 构造函数创造一个新的 {{domxref("WritableStream")}} 对象实例。
```suggestion
**`WritableStream()`** 构造函数创建一个新的 {{domxref("WritableStream")}} 对象实例。
```

2022-06-08 00:55 UTC, yin1999 commented on files/zh-cn/web/api/writablestream/writablestream/index.md
> +  - : 一个包含定义了构造流行为方法和属性的对象。underlyingSource 包括：
这句话明显翻译错误，请对照英文原文对整篇文章进行检查，然后再 rerequest review

2022-06-08 03:09 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/writablestream/writablestream/index.md
> +  - : 一个包含定义了构造流行为方法和属性的对象。underlyingSource 包括：
我参照了当时你对`ReadableStream`的翻译.你当时是这样修改的

2022-06-08 03:32 UTC, Jack-Zhang-1314 commented
造成了一点麻烦不好意思/(ㄒoㄒ)/~~

2022-06-08 03:36 UTC, yin1999 commented on files/zh-cn/web/api/writablestream/writablestream/index.md
> +  - : 一个包含定义了构造流行为方法和属性的对象。underlyingSource 包括：
那个 PR 是用于更正标点和空格，我并未对正文内容进行检查。那边的翻译也不是很准确，请修改

2022-06-08 04:02 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/writablestream/writablestream/index.md
> +  - : 一个包含定义了构造流行为方法和属性的对象。underlyingSource 包括：
已修改

2022-06-08 07:00 UTC, yin1999 requested changes

2022-06-08 07:00 UTC, yin1999 commented on files/zh-cn/web/api/writablestream/writablestream/index.md
> +  - : 一个包含方法和属性的对象，这些方法和属性定义了如何构造流实例的行为。underlyingSource 包括：
请对照英文原文理解其意思：

```suggestion
  - : 一个包含方法和属性的对象，这些方法和属性定义了构造的流的实例的具体行为。`underlyingSource` 包括：
```

2022-06-08 07:00 UTC, yin1999 commented on files/zh-cn/web/api/writablestream/writablestream/index.md
> +    > **备注:** 你可以定义一个自己的 `queuingStrategy`，或者为这个对象值使用 {{domxref("ByteLengthQueuingStrategy")}} 或 {{domxref("CountQueuingStrategy")}} 的实例。如果没有提供 `queuingStrategy`，则使用的默认值与 `CountQueuingStrategy` 相同，其
请严格按照格式填写：<https://developer.mozilla.org/zh-CN/docs/MDN/Contribute/Markdown_in_MDN#备注、警告和标注>

```suggestion
    > **备注：** 你可以定义一个自己的 `queuingStrategy`，或者为这个对象值使用 {{domxref("ByteLengthQueuingStrategy")}} 或 {{domxref("CountQueuingStrategy")}} 的实例。如果没有提供 `queuingStrategy`，则使用的默认值与 `CountQueuingStrategy` 相同，其 highWaterMark 为 1。
```

2022-06-08 07:00 UTC, yin1999 commented on files/zh-cn/web/api/writablestream/writablestream/index.md
> +      - : 如果应用程序发出希望立即关闭流并且将其移至错误状态的信号，将调用此方法，该方法也是由开发人员定义。它可以清理任何被占用的资源，就像 `close()` 一样，但是即使写入的数据正在排入，`abort()` 也将被调用——那些块将被丢弃。如果这个过程是异步完成的，它可以返回一个 promise，表明成功或失败。`reason` 参数包含一个字符串，用于指定流被中止的原因。
这一部分再好好翻译一下，然后请注意中英文之间的空格：https://github.com/mdn/translated-content/issues/6166#issuecomment-1149387985

2022-06-09 04:25 UTC, yin1999 commented on files/zh-cn/web/api/writablestream/writablestream/index.md
> +      - : 如果应用程序发出希望立即关闭流并且将其移至错误状态的信号，将调用此方法，该方法也是由开发人员定义。它可以清理任何被占用的资源，就像 `close()` 一样，但是即使写入的数据正在排入，`abort()` 也将被调用——那些块将被丢弃。如果这个过程是异步完成的，它可以返回一个 promise，表明成功或失败。`reason` 参数包含一个字符串，用于指定流被中止的原因。
```suggestion
      - : 如果应用程序发出希望立即关闭流并且将其移至错误状态的信号，将调用此方法，该方法也是由开发人员定义。它可以清理任何被占用的资源，就像 `close()` 一样，但是即使存在等待的 `write` 操作，`abort()` 也将被调用——那些分块将被丢弃。如果这个过程是异步完成的，它可以返回一个 promise，以表明操作成功或失败。`reason` 参数包含一个字符串，用于指定流被中止的原因。
```

2022-06-09 04:25 UTC, yin1999 commented on files/zh-cn/web/api/writablestream/writablestream/index.md
> +  - : 一个可选择定义流的排队策略的对象。这需要两个参数：
```suggestion
  - : 一个可选的定义流的队列策略的对象。这需要两个参数：
```

2022-06-09 04:25 UTC, yin1999 commented on files/zh-cn/web/api/writablestream/writablestream/index.md
> +      - : 非负整数 - 这定义了在应用背压之前可以包含在内部队列中的块的总数。
```suggestion
      - : 非负整数——这定义了在应用背压之前可以包含在内部队列中的分块的总数。
```

2022-06-09 04:25 UTC, yin1999 commented on files/zh-cn/web/api/writablestream/writablestream/index.md
> +      - : 包含参数 chunk 的方法 - 这表示每个块使用的大小（以字节为单位）。
```suggestion
      - : 包含参数 chunk 的方法——这表示每个分块所需要使用的字节数。
```

2022-06-09 04:31 UTC, yin1999 commented on files/zh-cn/web/api/writablestream/writablestream/index.md
> +      - : 非负整数——这定义了在应用背压之前可以包含在内部队列中的分块的总数。
```suggestion
      - : 非负整数——这定义了在应用背压之前可以包含在内部队列中的分块的最大数量。
```

2022-06-09 04:33 UTC, yin1999 commented on files/zh-cn/web/api/writablestream/writablestream/index.md
> +  - : 一个包含方法和属性的对象，这些方法和属性定义了构造的流的实例的具体行为。`underlyingSource` 包括：
```suggestion
  - : 一个包含方法和属性的对象，这些方法和属性定义了构造的流的实例的具体行为。`underlyingSource` 可以包括：
```

2022-06-09 04:36 UTC, merged