Web/http/headers/connection を更新。
mdn/translated-content pull request #617
Opened 2021-04-21 15:10 UTC by x270

英語版 Last modified: Mar 16, 2021 と同期。

2021-05-05 17:44 UTC, mfuji09 requested changes
1点の修正をお願いします。

2021-05-05 17:44 UTC, mfuji09 commented on files/ja/web/http/headers/connection/index.html
> +<div class="note">{{HTTPHeader("Connection")}} や {{HTTPHeader("Keep-Alive")}} などの接続固有のヘッダーフィールドは、<a href="https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2.2">HTTP/2 では使用しないでください</a>。Chrome
この部分のマークアップ（class名とその中のp要素）が英語版と異なっていますので、英語版に合わせて修正をお願いします。
改行位置までは合わせなくてもよいと思います。

2021-05-06 15:17 UTC, x270 commented
@mfuji09  
レビューありがとうございます。  
divタグのclass名の変更と、その内側へのpタグ追加を行いました。  
お手数おかけしますが、再確認をお願いいたします。

2021-05-07 16:16 UTC, mfuji09 approved these changes
OKです。

2021-05-07 16:16 UTC, merged