Update index.html
mdn/translated-content pull request #621
Opened 2021-04-21 21:18 UTC by NemoNobobyPersonne

Typo and translation completion

2021-04-21 22:45 UTC, tristantheb requested changes
Hello / Bonsoir,

There are still errors in the document (thanks Grammarlecte), unfortunately I don't have a list of points at the moment, it happens soon!

2021-04-21 22:58 UTC, tristantheb commented
https://github.com/NemoNobobyPersonne/translated-content/blob/5d2303c9e1ccccb6b73e1dfe88a8adc6b910445a/files/fr/web/html/element/input/index.html#L29

2021-04-29 13:42 UTC, tristantheb commented
Duplicate of #500

2021-04-29 15:51 UTC, Hallay16 requested changes
files/fr/web/html/element/input/index.html

2021-04-29 21:03 UTC, tristantheb commented
[Duplicata]
The content will be corrected when the Input element and its sub-pages are corrected. For this reason, and to avoid creating branch conflicts, I am closing this Pull Request.
I invite you to follow the Pull Request 500 linked above to see how we are progressing with the update of the HTML elements.

---
Le contenu sera corrigé au moment de la correction de l'élément Input et de ces sous pages. Pour cette raison, et pour éviter de créer des conflits de branches, je ferme donc cette Pull Request.
Je vous invite à suivre la Pull Request 500 liée plus haut afin de savoir comment nous avançons sur la mise à jour des éléments HTML.

2021-04-29 21:03 UTC, closed without merging

2021-04-29 21:21 UTC, NemoNobobyPersonne commented
>>>Le contenu sera corrigé au moment de la correction de l'élément Input et de ces sous pages. Pour cette raison, et pour éviter de créer des conflits de branches, je ferme donc cette Pull Request<<<

 

Hum, la seule conclusion que je puisse en tirer est que, pour d’obscures raisons apparemment peu spécifiques, mes corrections – certes minimes – ont été passées par pertes et profits sans autre forme de procès : si ces raisons étaient une « impérieuse obligation », n’aurait-il pas été possible de désactiver l’édition de cette page - et des autres pages dans la même situation - aussi longtemps que celle-ci durerait ?

 

Cela aurait été de nature à éviter de décourager les bonnes volontés, car en ce qui me concerne, il est exclu que je fasse à nouveau la moindre contribution aussi longtemps que je n’aurais pas la certitude qu’elle ne subira pas le même sort.

 

BB

 

De : tristantheb ***@***.***> 
Envoyé : jeudi 29 avril 2021 23:04
À : mdn/translated-content ***@***.***>
Cc : NemoNobobyPersonne ***@***.***>; Author ***@***.***>
Objet : Re: [mdn/translated-content] Fix typo and complete translation (#621)

 

[Duplicata]
The content will be corrected when the Input element and its sub-pages are corrected. For this reason, and to avoid creating branch conflicts, I am closing this Pull Request.
I invite you to follow the Pull Request 500 linked above to see how we are progressing with the update of the HTML elements.

  _____  

Le contenu sera corrigé au moment de la correction de l'élément Input et de ces sous pages. Pour cette raison, et pour éviter de créer des conflits de branches, je ferme donc cette Pull Request.
Je vous invite à suivre la Pull Request 500 liée plus haut afin de savoir comment nous avançons sur la mise à jour des éléments HTML.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub <https://github.com/mdn/translated-content/pull/621#issuecomment-829594709> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AG6CUNJCGJM3XQTW7MVEFF3TLHCUHANCNFSM43LE32YA> .  <https://github.com/notifications/beacon/AG6CUNK27IBJ5ITL2FRXNKLTLHCUHA5CNFSM43LE32YKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGFZJYVI.gif>

2021-04-29 23:08 UTC, tristantheb commented
Bonsoir,

Comme cela a été précisé sur le message de fermeture du ticket, la correction que vous avez apportée et les corrections qui ont ensuite été demandées, seront intégrées à la mise à jour de la section HTML/Elements/<x>/<y> 🙂 
Nous avons ouvert une Requête de projet global #500 avant l’ouverture de votre Requête #621.

Afin de ne pas créer un conflit entre votre modification et une modification ouverte sur un projet de Retraduction et Mise à jour des anciennes traductions de tous les éléments HTML, et cette requête a été fermée. Il n’y a pas de raisons obscures ou quoi que ce soit d’illuminati en dehors d’une raison simple : L’édition est déjà dans une « TO-DO list » de travail, ce travail consiste à mettre à jour un grand nombre de pages en une seule fois afin de donner aux lecteurs un contenu corrigé, à jour et correct en une seule fois.

En quoi cela consiste :
–  Mettre à jour les pages depuis la version anglaise
–  Supprimer les contenus qui ne sont plus d’actualités
–  Corriger les fautes d’orthographe, de grammaire, etc.
–  Mettre à jour la structure du contenu selon de nouvelles règles

Pour davantage d’informations sur le travail qui est effectué, et un exemple des travaux généraux que nous faisons sur les éléments HTML (`<a>`, `<abbr>`, ..., `<input>`, ...) je vous invite à regarder le contenu suivant : [https://github.com/mdn/translated-content/pull/500/files](https://github.com/mdn/translated-content/pull/500/files), [https://github.com/mdn/translated-content/pull/500](https://github.com/mdn/translated-content/pull/500)

Cette fermeture n’est ni punitive, ni péjorative, ni négative. Elle a seulement pour but d’éviter des conflits de branches. La correction apportée, et les corrections demandées qui n’ont pas été intégrées sur cette requête seront créditées sur la requête de travail global.

Merci de votre compréhension.

2021-04-30 05:33 UTC, NemoNobobyPersonne commented
Bonjour,

 

>>>la correction que vous avez apportée et les corrections qui ont ensuite été demandées, seront intégrées à la mise à jour<<<

 

Désolé, mais ce n’était pas évident pour moi au vu des messages reçus…

 

>>>Cette fermeture n’est ni punitive, ni péjorative, ni négative<<<

 

Loin de moi une telle idée, mais l’impression que j’en avais eu était que les corrections suggérées ne seraient finalement pas utilisées comme entrant en conflit ou faisant double emploi avec une révision plus générale en cours : d’où ma réaction un peu « épidermique »…

 

Avec mes excuses pour le dérangement occasionné.

 

De : tristantheb ***@***.***> 
Envoyé : vendredi 30 avril 2021 01:08
À : mdn/translated-content ***@***.***>
Cc : NemoNobobyPersonne ***@***.***>; Author ***@***.***>
Objet : Re: [mdn/translated-content] Fix typo and complete translation (#621)

 

Bonsoir,

Comme cela a été précisé sur le message de fermeture du ticket, la correction que vous avez apportée et les corrections qui ont ensuite été demandées, seront intégrées à la mise à jour de la section HTML/Elements// 🙂
Nous avons ouvert une Requête de projet global #500 <https://github.com/mdn/translated-content/pull/500>  avant l’ouverture de votre Requête #621 <https://github.com/mdn/translated-content/pull/621> .

Afin de ne pas créer un conflit entre votre modification et une modification ouverte sur un projet de Retraduction et Mise à jour des anciennes traductions de tous les éléments HTML, et cette requête a été fermée. Il n’y a pas de raisons obscures ou quoi que ce soit d’illuminati en dehors d’une raison simple : L’édition est déjà dans une « TO-DO list » de travail, ce travail consiste à mettre à jour un grand nombre de pages en une seule fois afin de donner aux lecteurs un contenu corrigé, à jour et correct en une seule fois.

En quoi cela consiste :
–  Mettre à jour les pages depuis la version anglaise
–  Supprimer les contenus qui ne sont plus d’actualités
–  Corriger les fautes d’orthographe, de grammaire, etc.
–  Mettre à jour la structure du contenu selon de nouvelles règles

Pour davantage d’informations sur le travail qui est effectué, et un exemple des travaux généraux que nous faisons sur les éléments HTML (<a>, <abbr>, ..., <input>, ...) je vous invite à regarder le contenu suivant : https://github.com/mdn/translated-content/pull/500/files, #500 <https://github.com/mdn/translated-content/pull/500> 

Cette fermeture n’est ni punitive, ni péjorative, ni négative. Elle a seulement pour but d’éviter des conflits de branches. La correction apportée, et les corrections demandées qui n’ont pas été intégrées sur cette requête seront créditées sur la requête de travail global.

Merci de votre compréhension.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub <https://github.com/mdn/translated-content/pull/621#issuecomment-829653332> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AG6CUNJ2PVCN45LK7CHNXUTTLHRGDANCNFSM43LE32YA> .  <https://github.com/notifications/beacon/AG6CUNLTY4T4MJMMMGU5OCLTLHRGDA5CNFSM43LE32YKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGFZYCVA.gif>