web/css/border-*-color (zh-TW translation)
mdn/translated-content pull request #6229
Opened 2022-06-12 08:40 UTC by lilychen1388

Add and translate 4 pages:
"border-top-color", 
"border-right-color", 
"border-bottom-color", 
"border-left-color"

2022-06-22 17:09 UTC, irvin requested changes

2022-06-22 17:09 UTC, irvin commented on files/zh-tw/web/css/border-bottom-color/index.md
> +**`border-bottom-color`** 是一種CSS屬性，用來設定元件下側[邊框](/zh-TW/docs/Web/CSS/border)的顏色。也可由含括此屬性功能的簡寫屬性{{cssxref("border-color")}}或{{cssxref("border-color")}}設定該屬性值。
```suggestion
**`border-bottom-color`** 是一種CSS屬性，用來設定元件下側[邊框](/zh-TW/docs/Web/CSS/border)的顏色。也可由含括此屬性功能的簡寫屬性{{cssxref("border-color")}}或{{cssxref("border-bottom")}}設定該屬性值。
```

2022-06-22 17:09 UTC, irvin commented on files/zh-tw/web/css/border-bottom-color/index.md
> +**`border-bottom-color`** 是一種CSS屬性，用來設定元件下側[邊框](/zh-TW/docs/Web/CSS/border)的顏色。也可由含括此屬性功能的簡寫屬性{{cssxref("border-color")}}或{{cssxref("border-color")}}設定該屬性值。
另三篇亦同

2022-06-25 20:39 UTC, lilychen1388 commented on files/zh-tw/web/css/border-bottom-color/index.md
> +**`border-bottom-color`** 是一種CSS屬性，用來設定元件下側[邊框](/zh-TW/docs/Web/CSS/border)的顏色。也可由含括此屬性功能的簡寫屬性{{cssxref("border-color")}}或{{cssxref("border-color")}}設定該屬性值。
已修正。

2022-06-25 23:58 UTC, yin1999 requested changes
若与 main 分支没有冲突，请不要合并 main 分支到 PR 所在的分支，请通过 `git reset` 命令撤销最后一次 commit 后，force push 到 `origin`

2022-06-26 16:21 UTC, lilychen1388 commented
試圖處理了git commit，也確認過內容裡 irvin  指出的錯誤已被修正。謝謝兩位的指點，再麻煩你們了。

2022-07-09 06:50 UTC, yin1999 approved these changes

2022-07-09 06:51 UTC, merged