Traducción: Elemento HTML - Title
mdn/translated-content pull request #6253
Opened 2022-06-14 02:12 UTC by Ferrmolina

Traducción aplicada en base a la [página original en inglés](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title)

2022-06-14 19:39 UTC, JuanVqz commented on files/es/web/html/element/title/index.html
>  original_slug: Web/HTML/Elemento/title
necesita la llave para que compat funcioné

```suggestion
original_slug: Web/HTML/Elemento/title
browser-compat: html.elements.title
```

2022-06-14 19:47 UTC, JuanVqz reviewed
Hola @Ferrmolina, muchas gracias por aportar a la comunidad MDN en español.

Sabes, tu contribución es importante, veo que llevas exactamente la idea de lo que se requiere espero no desanimarte con esto pero si dejamos el archivo que editaste como `index.html` en algún momento tu contribución se borrara por que debemos cambiar los archivos `html` a `markdown`, de esa manera tu contribución perdurará por la eternidad (ja, esto exagerando un poco) pero es cierto, durará mucho mas tiempo. por que? por que `md` se apega a los estandares de MDN. 

Así que me gustaria proponer/preguntar si es posible que modifiques el archivo de formato, es decir, de `index.html` a `index.md` y de esa forma podrás apegarte 100% al contenido y formato de la versión en [ingles](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/title/index.md?plain=1).

Espero tu respuesta, de cualquier modo si no tienes tiempo de cambiar el formato, aceptaré tu PR aún que puede llegar a desaparecer en algún momento.


Si deseas seguir apoyando puedes:
* [Actualizar el contenido con la versión en inglés](https://github.com/mdn/translated-content/discussions/4029)
* [Revisar issues](https://github.com/mdn/translated-content/issues?q=is%3Aopen+is%3Aissue+label%3Al10n-es)

Si tienes dudas, contactamos, con gusto te ayudamos en el chat en español:
* [Unirte a nuestro equipo](https://chat.mozilla.org/#/room/#mdn-l10n-es:mozilla.org)

Saludos.

2022-06-14 22:21 UTC, Graywolf9 requested changes
Hola! @Ferrmolina excelente trabajo de traducción y ya vi que has hecho el cambió de formato en tiempo record, felicidades.

Te dejó algunos comentarios adicionales a los de mis compañeros.

Muchas gracias por tu valioso tiempo y aportación.

2022-06-14 22:21 UTC, Graywolf9 commented on files/es/web/html/element/title/index.md
> +- No utilice "Blobs de palabras clave." Si su título es solo una lista de palabras, los algoritmos a menudo reducen la posición de su página en los resultados de búsqueda.
Para indicar que no es una palabra nativa, también podría quedar "listas de palabras clave", ya que la interpretación de a lo que se refiere es algo similar

```suggestion
- No utilice "_blobs_ de palabras clave." Si su título es solo una lista de palabras, los algoritmos a menudo reducen la posición de su página en los resultados de búsqueda.
```

2022-06-14 22:21 UTC, Graywolf9 commented on files/es/web/html/element/title/index.md
> +<title>Awesome interesting stuff</title>
Los textos literales también pueden ser traducidos para ayudar al lector

```suggestion
<title>Cosas increíbles e interesantes</title>
```

2022-06-14 22:21 UTC, Graywolf9 commented on files/es/web/html/element/title/index.md
> +Este ejemplo establece una página cuyo título (tal como se muestra en la parte superior de la ventana o en la pestaña de la ventana) es "Awesome interesting stuff".
Para concordar con el ejemplo

```suggestion
Este ejemplo establece una página cuyo título (tal como se muestra en la parte superior de la ventana o en la pestaña de la ventana) es "Cosas increíbles e interesantes".
```

2022-06-14 22:21 UTC, Graywolf9 commented on files/es/web/html/element/title/index.md
> +<title>Menu - Blue House Chinese Food - FoodYum: Online takeout today!</title>
Los textos literales también pueden ser traducidos para ayudar al lector

```suggestion
<title>Menú - Comida china Blue House - FoodYum: ¡Comida a domicilio en línea hoy!</title>
```

2022-06-14 22:21 UTC, Graywolf9 commented on files/es/web/html/element/title/index.md
> +<title>2 errores - Tu orden - Blue House Chinese Food - FoodYum: Online takeout today!</title>
```suggestion
<title>2 errores - Tu orden - Comida china Blue House - FoodYum: ¡Comida a domicilio en línea hoy!</title>
```

2022-06-14 22:21 UTC, Graywolf9 commented on files/es/web/html/element/title/index.md
> +> **Nota:** Actualmente, los lectores de pantalla no anunciarán automáticamente la actualización dinámica del título de una página. Si va a actualizar el título de la página para reflejar cambios sig
- Agregar los vinculos en `/es/` el bot automáticamente dirigirá a español si esta disponible o inglés en caso contrario
- Se traduce lo de ARIA para ayudar al lector

```suggestion
> **Nota:** Actualmente, los lectores de pantalla no anunciarán automáticamente la actualización dinámica del título de una página. Si va a actualizar el título de la página para reflejar cambios significativos en el estado de una página, entonces también puede ser necesario el uso de [regiones en vivo de ARIA](/es/docs/Web/Accessibility/ARIA/ARIA_Live_Regions).
```

2022-06-14 22:21 UTC, Graywolf9 commented on files/es/web/html/element/title/index.md
> +- [MDN Understanding WCAG, Guideline 2.4 explanations](/en-US/docs/Web/Accessibility/Understanding_WCAG/Operable#guideline_2.4_—_navigable_provide_ways_to_help_users_navigate_find_content_and_determi
```suggestion
- [MDN Entendiendo las WCAG, Directriz 2.4 explicaciones](/es/docs/Web/Accessibility/Understanding_WCAG/Operable#guideline_2.4_—_navigable_provide_ways_to_help_users_navigate_find_content_and_determine_where_they_are)
```

2022-06-14 22:21 UTC, Graywolf9 commented on files/es/web/html/element/title/index.md
> +- [Understanding Success Criterion 2.4.2 | W3C Understanding WCAG 2.1](https://www.w3.org/WAI/WCAG21/Understanding/page-titled.html)
```suggestion
- [Entendiendo el Criterio de Conformidad 2.4.2 | W3C Entendiendo las WCAG 2.1](https://www.w3.org/WAI/WCAG21/Understanding/page-titled.html)
```

2022-06-14 22:21 UTC, Graywolf9 commented on files/es/web/html/element/title/index.md
> +## Compatibilidad del navegador
Para homologar este apartado en las traducciones

```suggestion
## Compatibilidad con navegadores
```

2022-06-14 22:33 UTC, Ferrmolina commented
Gracias por tu feedback @Graywolf9. Correcciones aplicadas.

2022-06-15 15:30 UTC, Graywolf9 approved these changes

2022-06-15 15:31 UTC, Graywolf9 commented
Muchas gracias  a ti @Ferrmolina excelente trabajo !

2022-06-15 15:31 UTC, merged