[zh-TW] update the translate of CustomEvent
mdn/translated-content pull request #6271
Opened 2022-06-14 09:08 UTC by shiyou0130011

I changed `Web/API/CustomEvent` and `Web/API/CustomEvent/CustomEvent` to **Markdown format** and updated them to follow the newest English doc.

2022-06-14 09:11 UTC, yin1999 requested changes
Please leave 2 commits for a markdown convertion (reference: <https://github.com/mdn/translated-content/pull/6153/commits>). You can do the `update` task in the second commit (convert and sync)

2022-06-15 03:18 UTC, shiyou0130011 commented
> Please leave 2 commits for a markdown convertion (reference: https://github.com/mdn/translated-content/pull/6153/commits). You can do the `update` task in the second commit (convert and sync)

Hello [yin1999](https://github.com/yin1999)
I've update the branch to leave only 2 commits. Please check.

2022-06-15 03:43 UTC, yin1999 requested changes
I am not familiar with traditional Chinese, so just for some typo

2022-06-15 03:43 UTC, yin1999 commented on files/zh-tw/web/api/customevent/customevent/index.md
> +## 延伸閱讀
```suggestion
## 參見
```

2022-06-15 03:43 UTC, yin1999 commented on files/zh-tw/web/api/customevent/customevent/index.md
> +-  {{domxref("CustomEvent")}}
```suggestion
- {{domxref("CustomEvent")}}
```

2022-06-15 03:43 UTC, yin1999 commented on files/zh-tw/web/api/customevent/index.md
> +
```suggestion

```

2022-06-15 03:43 UTC, yin1999 commented on files/zh-tw/web/api/customevent/index.md
> +
```suggestion

```

2022-06-15 03:43 UTC, yin1999 commented on files/zh-tw/web/api/customevent/index.md
> +## 延伸閱讀
```suggestion

## 參見
```

2022-07-11 13:17 UTC, irvin approved these changes

2022-07-11 13:51 UTC, yin1999 commented
> @shiyou0130011 conflict 了，需要 rebase

resolved

2022-07-11 14:11 UTC, merged