Page translation: Notification.close() [es]
mdn/translated-content pull request #6280
Opened 2022-06-15 03:58 UTC by Ferrmolina

Tradución para página reportada en issue #6273

2022-06-15 11:53 UTC, marcelozarate requested changes
Excelente traducción, revisada línea por línea, y sin dudas excelente calidad, tanto en contexto, como ortográfica y gramaticalmente. Dejo unos mínimos detalles a corregir, pero es una gran colaboración. ¡Gracias por tu tiempo!

2022-06-15 11:53 UTC, marcelozarate commented on files/es/web/api/notification/close/index.md
> +- [Uso de la API de Notificaciones](/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API)
```suggestion
- [Uso de la API de Notificaciones](/es/docs/Web/API/Notifications_API/Using_the_Notifications_API)
```

Siempre referenciamos la URL en español, Yari se encargará de hacer un fallback si no está disponible

2022-06-15 11:53 UTC, marcelozarate commented on files/es/web/api/notification/close/index.md
> +## Vea también
```suggestion
## Véase también
```

2022-06-15 15:42 UTC, Graywolf9 commented
Muchas gracias por el excelente trabajo @Ferrmolina y muchas gracias por la revisión @marcelozarate 

Dejo el tip: Para cuando es un PR relacionado a un issue puedes poner Fix #6273 para que se vinculen y al ser aprovado se cierre el issue automáticamente

Saludos!

2022-06-18 22:01 UTC, marcelozarate approved these changes

2022-06-18 22:01 UTC, merged