Update french index.md - attributeChangedCallback
mdn/translated-content pull request #6326
Opened 2022-06-17 07:57 UTC by srimko

The french translation proposed to call the method `observedAttributes()` inside the constructor whereas the english documentation propose to specify a static get method inside the custom element class.
I modified the translation to avoid misunderstanding about this specification.

2022-06-17 17:39 UTC, cw118 requested changes
Merci beaucoup @srimko ! Quelques suggestions :)

2022-06-17 17:39 UTC, cw118 commented on files/fr/web/web_components/using_custom_elements/index.md
> +Notez que, pour déclencher le rappel `attributeChangedCallback()` lorsqu'un attribut change, vous devez observer les attributs. Cela est réalisé en spécifiant le getter `static get observedAttributes
```suggestion
Notez que, pour déclencher le rappel `attributeChangedCallback()` lorsqu'un attribut change, vous devez observer les attributs. Cela est réalisé en spécifiant la méthode `static get observedAttributes()` dans la classe de l'élément personnalisé, en incluant à l'intérieur une instruction `return` qui renvoie un tableau contenant les noms des attributs que vous voulez observer&nbsp;:
```

(N.B. l'entité `&nbsp;` est une espace insécable)

2022-06-20 19:27 UTC, srimko commented on files/fr/web/web_components/using_custom_elements/index.md
> +Notez que, pour déclencher le rappel `attributeChangedCallback()` lorsqu'un attribut change, vous devez observer les attributs. Cela est réalisé en spécifiant le getter `static get observedAttributes
Très bien merci.

2022-06-21 14:08 UTC, cw118 commented on files/fr/web/web_components/using_custom_elements/index.md
> +Notez que, pour déclencher le rappel `attributeChangedCallback()` lorsqu'un attribut change, vous devez observer les attributs. Cela est réalisé en spécifiant le getter `static get observedAttributes
Le bouton "Commit suggestion" permet de pousser un commit apportant ces modifications. N'hésitez pas si besoin d'aide :)

2022-06-21 21:00 UTC, cw118 approved these changes
Merci @srimko, félicitations pour cette première contribution :)

2022-06-21 21:00 UTC, merged