Angular_styling の翻訳 #610 の PR
mdn/translated-content pull request #6358
Opened 2022-06-18 05:32 UTC by gurezo

@hmatrjp @potappo 
Angular_styling の翻訳 のPRです。
https://github.com/mozilla-japan/translation/issues/610

Angular の各ページのリンクの修正・翻訳に加え、
翻訳済みの React  の各ページのリンクの修正・翻訳も実施しました

2022-06-19 07:41 UTC, potappo requested changes
MDN 内の他記事へのリンクは存在するかどうかに関わらず、すべて ja にしてもらいたいです。

リンク先がいつの間にか翻訳されている場合もあるので（この記事だと他フレームワークの記事が該当する可能性が高）、MDN 日本語版では、慣習的にすべてのリンクを ja に直しています。
※日本語版が存在しないリンクは自動的に英語版へのリンクとなります。

この記事は他記事へのリンクが多くて手間かと思います（エディタの置換機能などを使ってください）が、よろしくお願いします。

2022-06-19 07:53 UTC, gurezo commented
@potappo 
レビューありがとうございます。

> #リンク先がいつの間にか翻訳されている場合もあるので（この記事だと他フレームワークの記事が該当する可能性が高）、MDN 日本語版では、慣習的にすべてのリンクを ja に直しています。
> ※日本語版が存在しないリンクは自動的に英語版へのリンクとなります。

ルールを知らなかったので、失礼しました。
確認・修正の上、プッシュします・

2022-06-19 08:05 UTC, gurezo commented
@potappo 
修正しました。お時間ある時に再レビューお願い申し上げます。

2022-07-11 12:21 UTC, potappo approved these changes
OK です。

2022-07-11 12:21 UTC, merged