Patch error on #5774 issue
mdn/translated-content pull request #6363
Opened 2022-06-18 11:47 UTC by EnriqueSource

Errores reparados y artículo completado.

2022-06-20 17:40 UTC, Graywolf9 requested changes
Muchas gracias por tu valioso tiempo y colaboración, te he dejado algunas observaciones

2022-06-20 17:40 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/math/random/index.md
> +### Obtener un número **entero** entre dos valores determinados
No hace falta remarcar la palabra

```suggestion
### Obtener un número entero entre dos valores determinados
```

2022-06-20 17:40 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/math/random/index.md
> +Tenga en cuenta que los números de coma flotante en JavaScript cumplen con la norma IEEE 754. Debido a esto, dichos números tienen un comportamiento de redondeo al evento más cercano. Es por eso que
Para mantener el formato estandarizado

```suggestion
Tenga en cuenta que los números de coma flotante en JavaScript cumplen con la norma IEEE 754. Debido a esto, dichos números tienen un comportamiento de redondeo al evento más cercano. Es por eso que en las funciones descritas en los siguientes ejemplos (excluyendo a la propia `Math.random()` ) los rangos declarados no son exactos. Si se eligen límites extremadamente grandes (2^53 o superiores), es posible, en casos extremadamente raros, calcular el "habitualmente excluido" límite superior.
```

2022-06-20 17:40 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/math/random/index.md
> +
Faltó de incluir y traducir

```suggestion

This example returns a random integer between the specified values. The value is no lower than min (or the next integer greater than min if min isn't an integer), and is less than (but not equal to) max. 

```

2022-06-20 17:40 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/math/random/index.md
> +Notesé que en este caso también `min` será incluido y `max` excluido.
Mantenerlo como comentario

```suggestion

```

2022-06-20 17:40 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/math/random/index.md
> +  return Math.floor(Math.random() * (max - min) + min);
```suggestion
  return Math.floor(Math.random() * (max - min) + min); // Notesé que en este caso también `min` será incluido y `max` excluido.
```

2022-06-20 17:40 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/math/random/index.md
> +> **Nota:** Puede ser tentador utilizar `Math.round()` para conseguir lo mismo, pero al hacerlo, los números aleatorios devueltos por la función **no** seguirán una distribución uniforma, tal y como
Para mejor coherencia con la versión original

```suggestion
> **Nota:** Puede ser tentador utilizar `Math.round()` para conseguir lo mismo, pero al hacerlo, los números aleatorios devueltos no seguirán una distribución uniforme. Esto podría no ser aceptable para sus necesidades.
```

2022-06-20 17:40 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/math/random/index.md
> +### Obtener un número entero aleatorio entre dos determinados valores (incluyendo ambos)
```suggestion
### Obtener un número entero aleatorio entre dos valores (incluyendo ambos)
```

2022-06-20 17:40 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/math/random/index.md
> +Ahora, tanto el valor mínimo como el máximo están incluidos en el resultado.
```suggestion

```

2022-06-20 17:40 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/math/random/index.md
> +  return Math.floor(Math.random() * (max - min + 1) + min);
```suggestion
  return Math.floor(Math.random() * (max - min + 1) + min); // Ahora, tanto el valor mínimo como el máximo están incluidos en el resultado.
```

2022-06-22 04:58 UTC, EnriqueSource commented
Agregados todos los cambios. Nota: Las notas añadidas como comentarios dentro de los bloques de código se han añadido en una línea nueva, en lugar de hacerlo directamente tras una linea de código. Esto lo he hecho así porque es como recomienda la guía de estilo de mdn. También creo que es la opción más legible. Cualquier cosa que falte no dudes en indicarlo.

2022-06-24 10:26 UTC, marcelozarate reviewed
Faltan algunos cambios mínimos y estaríamos ¿verdad? @EnriqueSource @Graywolf9

2022-06-24 15:01 UTC, Graywolf9 reviewed
Pequeño typo, lo corrigo y hago merge, muchas gracias por tu valioso tiempo y contribución

2022-06-24 15:01 UTC, Graywolf9 approved these changes

2022-06-24 15:06 UTC, merged