Feature/sensor apis
mdn/translated-content pull request #6414
Opened 2022-06-20 14:10 UTC by DmitrySkripunov

Hello! 
Suggesting a translation to Russion Sensor APIs page

2022-08-16 15:20 UTC, caugner requested changes, later dismissed

2022-08-16 15:20 UTC, caugner commented on .gitignore
> +node_modules
`translated-content` doesn't have a `package.json`, so these two lines should not be added.

```suggestion
```

2022-09-28 09:39 UTC, sashasushko commented
@DmitrySkripunov thank you for your help. I remember about your PR. And I'll review it ASAP. Sorry for waiting. Peace 🕊

2022-10-20 11:16 UTC, caugner commented on .gitignore
> +node_modules
@DmitrySkripunov In the mean-time, translated-content did get a `package.json`. Would you mind opening a separate PR for adding these lines to `.gitignore`?

2022-10-20 11:20 UTC, caugner commented on .gitignore
> +node_modules
Never mind, there already is one: https://github.com/mdn/translated-content/pull/9269

2023-08-04 00:35 UTC, queengooborg commented
Hey @sashasushko @myshov, just checking in to see if you plan to review this PR soon!

2023-09-07 08:36 UTC, queengooborg commented
Since this PR has been sitting around for over a month, I have updated the PR and am going to merge it.  I apologize if there are inaccuracies in the translation (I don't speak Russian), but it does not feel right to simply close the PR and waste the contributor's efforts.

2023-09-07 08:36 UTC, merged

2023-10-09 06:30 UTC, sashasushko commented
There are small issues with punctuation, but in total the translation is ok. Thanks, @queengooborg