Replace link to tool that doesn't support IPv6
mdn/translated-content pull request #6415
Opened 2022-06-20 15:04 UTC by ruurtjan

#### Summary
This PR replaces a link to a tool that doesn't support IPv6 with a tool that does.

#### Motivation
Many sites now listen to both IPv4 and IPv6 addresses. The MDN docs should promote IPv6 adoption.

I originally made a PR to the `mdn/content` repo, which got merged. But then I noticed that the translated content also contains links to a tool that doesn't support IPv6, and @teoli2003 asked me to create a PR here too. See https://github.com/mdn/content/pull/17468

#### Supporting details
Old link: 
![image](https://user-images.githubusercontent.com/1055478/174625640-ca969e63-67ee-4a1d-a100-9d2ab6afa8a6.png)

New link:
![image](https://user-images.githubusercontent.com/1055478/174620317-8220649f-4bcf-41b1-8c59-109141d3b6bb.png)

#### Related issues

https://github.com/mdn/content/pull/17468

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-06-20 16:08 UTC, irvin approved these changes

2022-06-21 07:53 UTC, ruurtjan commented
I pushed a commit that also replaces the link in the JA translation.

2022-06-21 10:27 UTC, marcelozarate approved these changes

2022-06-21 16:39 UTC, Graywolf9 requested changes
Thank you so much! I let you a comment

2022-06-21 23:47 UTC, nathipg requested changes
Thanks for the contribution!
I agree with @Graywolf9 about the link text, could you also change it in pt-br, please?

2022-06-21 23:47 UTC, nathipg commented on files/pt-br/learn/getting_started_with_the_web/how_the_web_works/index.html
> +<p>Sites podem ser acessados diretamente pelo seu endereço IP. Você pode encontrar o endereço IP de um site, digitando seu domínio em uma ferramenta como o <a href="https://www.nslookup.io/website-to
```suggestion
<p>Sites podem ser acessados diretamente pelo seu endereço IP. Você pode encontrar o endereço IP de um site, digitando seu domínio em uma ferramenta como o <a href="https://www.nslookup.io/website-to-ip-lookup/">DNS lookup</a>.</p>
```

2022-06-22 13:12 UTC, ruurtjan commented
Thanks! I've accepted the suggested changes.

2022-06-22 15:43 UTC, Graywolf9 approved these changes

2022-06-25 03:15 UTC, mfuji09 requested changes
Can you replace the link text with the correct site name?

2022-06-25 03:15 UTC, mfuji09 commented on files/ja/learn/getting_started_with_the_web/how_the_web_works/index.html
> +<p>ウェブサイトには、IP アドレスを使用して直接アクセスできます。<a href="https://www.nslookup.io/website-to-ip-lookup/">IP Checker</a> のようなツールにドメインを打ち込むことで、ウェブサイトの IP アドレスを見つけることができます。</p>
Can you replace the link text?

```suggestion
<p>ウェブサイトには、IP アドレスを使用して直接アクセスできます。<a href="https://www.nslookup.io/website-to-ip-lookup/">DNS lookup</a> のようなツールにドメインを打ち込むことで、ウェブサイトの IP アドレスを見つけることができます。</p>
```
```suggestion
<p>ウェブサイトには、IP アドレスを使用して直接アクセスできます。<a href="https://www.nslookup.io/website-to-ip-lookup/">IP Checker</a> のようなツールにドメインを打ち込むことで、ウェブサイトの IP アドレスを見つけることができます。</p>
```

2022-06-25 20:56 UTC, ruurtjan commented
@mfuji09: done :)

2022-06-27 14:42 UTC, mfuji09 approved these changes

2022-07-02 18:00 UTC, cw118 commented
Gently poking @mdn/yari-content-pt-br @mdn/yari-content-ru @mdn/yari-content-ko for reviews :)

2022-07-03 12:06 UTC, GwangYeol-Im approved these changes
Thank you for your contribution :)

2022-07-18 01:45 UTC, nathipg approved these changes
Great job!

2022-07-22 04:37 UTC, merged