suggest french translation for #4204
mdn/translated-content pull request #6482
Opened 2022-06-24 20:48 UTC by ManuSquall

Suggest a french translation for [id 4204](https://tristantheb.github.io/history-content/#4204). I'm not sure about a macro translation, waiting for the review, thanks in advance !

2022-06-26 13:40 UTC, cw118 requested changes
Quelques legers ajustements, merci déjà @ManuSquall :)

2022-06-26 13:40 UTC, cw118 commented on files/fr/web/api/htmlheadingelement/index.md
> +L'élément HTML implémentant cette interface : [`<h1>`](/fr/docs/Web/HTML/Element/Heading_Elements), [`<h2>`](/fr/docs/Web/HTML/Element/Heading_Elements), [`<h3>`](/fr/docs/Web/HTML/Element/Heading_El
```suggestion
L'élément HTML implémentant cette interface&nbsp;:

- [`<h1>`](/fr/docs/Web/HTML/Element/Heading_Elements)
- [`<h2>`](/fr/docs/Web/HTML/Element/Heading_Elements)
- [`<h3>`](/fr/docs/Web/HTML/Element/Heading_Elements)
- [`<h4>`](/fr/docs/Web/HTML/Element/Heading_Elements)
- [`<h5>`](/fr/docs/Web/HTML/Element/Heading_Elements)
- [`<h6>`](/fr/docs/Web/HTML/Element/Heading_Elements).
```

On préfère ce formatage pour la locale française :)

2022-06-26 13:40 UTC, cw118 commented on files/fr/web/api/htmlheadingelement/index.md
> + - : Chaîne représentant un attribut énuméré indiquant l'alignement de l'en-tête par rapport au contexte environnant. Les valeurs possibles sont `"left"`, `"right"`, `"justify"`, et `"center"`.
```suggestion
- [`HTMLHeadingElement.align`](/fr/docs/Web/API/HTMLHeadingElement/align) {deprecated_inline}}
  - : Chaîne représentant un attribut énuméré indiquant l'alignement de l'en-tête par rapport au contexte environnant. Les valeurs possibles sont `"left"`, `"right"`, `"justify"`, et `"center"`.
```

2022-06-27 22:08 UTC, ManuSquall commented
Merci pour la revue! Changements appliqués!!

2022-06-28 04:07 UTC, cw118 approved these changes
Merci à nouveau @ManuSquall :) 🚀

2022-06-28 04:08 UTC, merged