fix the broken link and update html format
mdn/translated-content pull request #6496
Opened 2022-06-26 00:17 UTC by yin1999

Fixes #6488:

- mentioned by @awxiaoxian2020, the link to locale team does not exist, so update this link to [review team](https://github.com/mdn/translated-content/blob/main/PEERS_GUIDELINES.md#review-teams).
- The html format (`<code><strong>HTMLCanvasElement</strong></code><strong><code>.transferControlToOffscreen()</code></strong>`) is not used anymore, update it to `<strong><code>HTMLCanvasElement.transferControlToOffscreen()</code></strong>` which is `` **`HTMLCanvasElement.transferControlToOffscreen()`** `` in raw markdown

2022-06-26 00:24 UTC, yin1999 commented
pin @mdn/localization-team-leads for a review on this :)

2022-06-26 00:34 UTC, awxiaoxian2020 requested changes
Please also check it in [Simplified Chinese Guide / 简体中文翻译指南](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md) and [Traditional Chinese Guide / 正體中文翻譯指南](https://github.com/mdn/translated-content/blob/main/docs/zh-tw/translation-guide.md) :)

2022-06-26 01:34 UTC, yin1999 commented
> Please also check it in [Simplified Chinese Guide / 简体中文翻译指南](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md) and [Traditional Chinese Guide / 正體中文翻譯指南](https://github.com/mdn/translated-content/blob/main/docs/zh-tw/translation-guide.md) :)

Thanks, done in 64e8fa5eacc4299e8b0607133da56abbfde65a2f

2022-06-26 01:40 UTC, awxiaoxian2020 approved these changes

2022-06-26 13:32 UTC, hochan222 commented
> pin https://github.com/orgs/mdn/teams/localization-team-leads for a review on this :)

https://github.com/mdn/translated-content/pull/6516 for ko locale. Thank you :)

2022-06-29 01:07 UTC, yin1999 commented
Hi @SphinxKnight, could you have a review on this?

2022-06-29 06:06 UTC, SphinxKnight approved these changes
Looks good to me :)

2022-06-29 06:32 UTC, merged