Re-translate the writing style guide for zh-CN (Part 2)
mdn/translated-content pull request #6511
Opened 2022-06-26 09:03 UTC by awxiaoxian2020

continue #6238 .

Todo:

- [ ] covert to md
- [ ] add translations

2022-06-26 09:08 UTC, awxiaoxian2020 commented
@yin1999 Could you please help me to handle the unsupported `dl` elements?
``` markdown
 # Report from 2022/6/26 16:54:17
## All unhandled elements
- dl (12)
## Details per Document
### [/zh-CN/docs/MDN/Guidelines/Writing_style_guide](https://developer.mozilla.org/zh-CN/docs/MDN/Guidelines/Writing_style_guide)
### Missing conversion rules
- dl (326:1)
- dl (376:1)
- dl (389:1)
- dl (446:1)
- dl (457:1)
- dl (470:1)
- dl (483:1)
- dl (496:1)
- dl (511:1)
- dl (528:1)
- dl (543:1)
- dl (560:1)
```

2022-06-26 10:22 UTC, yin1999 commented
fixed, please using command `git rebase` to squash those two commits

2022-06-26 11:03 UTC, yin1999 commented
LGTM

2022-06-26 11:06 UTC, awxiaoxian2020 commented
> LGTM. Is it ready for merging?

I will add more translations when I'm available.

2022-06-26 11:08 UTC, yin1999 commented
> I will add more translations when I'm available.

Ok, please do this in the last commit

2022-06-26 23:41 UTC, yin1999 requested changes

2022-06-26 23:41 UTC, yin1999 commented on files/zh-cn/mdn/guidelines/writing_style_guide/index.md
> +对于函数名、变量名、方法名等，应使用“Inline Code”按钮（编辑器中显示为“<>”的按钮）将其设置为内联代码格式（内联代码使用的是 {{HTMLElement("code")}} 元素）。比如：`frenchText()` 函数。
请更新

2022-06-27 00:19 UTC, yin1999 approved these changes
Thanks a lot

2022-06-27 00:20 UTC, merged