Cache-Control (zh-TW translation)
mdn/translated-content pull request #658
Opened 2021-04-26 17:34 UTC by artyomliou

增加一篇翻譯

2021-04-26 23:51 UTC, t7yang commented on files/zh-tw/web/http/headers/cache-control/index.html
> + <dd>此回應可以被 <em>任何快取軟體</em> 儲存起來，即使它本身通常是不可快取的。 不過，在使用儲存起來的 HTTP 回應之前， <em>必須</em> 必須向後端伺服器做驗證，因此你不能拿 <code>no-cache</code> 跟 <code>immutable</code> 一起使用。 <strong>如果你的確不要任何快取軟體儲存你的回應，可以使用 <code>no-st
消除中文與中文之間的多餘的半形空格：

```
， <em>必須</em> 必
  ^
```

2021-04-26 23:53 UTC, t7yang commented on files/zh-tw/web/http/headers/cache-control/index.html
> + <dd>此回應 <strong>不能</strong> 被 <em>任何快取軟體</em> 儲存起來。 當然它無法防止 <em>先前儲存起來</em> 的回應被回傳。 客戶端可以用 <code>max-age=0</code> 來清除快取，並強制向後端伺服器做驗證。 (其他指令跟 <code>no-store</code> 一起使用都無效)。</dd>
替換文中多處中文與中文之間的半形括號為全形括號「（）」，例：
```
。 (其他指令跟
  ^
```

2021-04-26 23:57 UTC, t7yang requested changes
請根據指示修正譯文中的問題，感謝。

2021-04-27 01:03 UTC, artyomliou commented
調整過了，還麻煩幫忙 review，
如果有不合規定的地方還麻煩幫忙指出
謝謝

2021-04-27 01:10 UTC, t7yang approved these changes

2021-04-27 01:14 UTC, merged