Translate Using server-sent events into korean
mdn/translated-content pull request #66
Opened 2021-02-19 11:41 UTC by uyeong

2021-03-12 06:34 UTC, SphinxKnight commented
Sorry, but this locale is currently frozen and changes/fixes are not currently accepted. Please see https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ and [README](https://github.com/mdn/translated-content/blob/main/README.md) of this repo.

2021-04-15 15:28 UTC, SphinxKnight commented
@uyeong Please check #519 if you would like to participate in a possible Korean localization effort to get this locale "unfrozen" :)

2021-05-18 07:45 UTC, hochan222 requested changes
동결이 해제됨에 따라 리뷰를 진행했습니다. 몇가지 단어들에 대해 한국어로 대체되면 더 좋을듯해서 리뷰했습니다. 기여해주셔서 감사합니다 좋은 하루 보내세요 :)

2021-05-18 07:45 UTC, hochan222 commented on files/ko/web/api/server-sent_events/using_server-sent_events/index.html
> +<h2 id="Receiving_events_from_the_server" name="Receiving_events_from_the_server">サーバからイベントを受信する</h2>
```suggestion
<h2 id="Receiving_events_from_the_server" name="Receiving_events_from_the_server">서버에서 이벤트 받기</h2>
```

2021-05-18 07:45 UTC, hochan222 commented on files/ko/web/api/server-sent_events/using_server-sent_events/index.html
> +<h2 id="Browser_compatibility">Browser compatibility</h2>
```suggestion
<h2 id="Browser_compatibility">브라우저 호환성</h2>
```

2021-06-02 01:17 UTC, hochan222 approved these changes
LGTM :)

2021-06-02 01:20 UTC, merged