補上GitHub首頁翻譯zh-TW
mdn/translated-content pull request #661
Opened 2021-04-27 09:12 UTC by javawillch

補上GitHub首頁翻譯zh-TW

2021-04-27 12:57 UTC, t7yang requested changes
請重新檢視你的翻譯，並針對下列及文中給予的提醒進行調整：

1. 標點符號的正確性及一致性。
2. 本地詞彙的使用。
3. Git 專業詞彙的翻譯可以參考台灣相關專家，如高健龍、保哥等的著作。
4. 翻譯後請務必重新閱讀一邊，若發現某些過於機械式英翻中語句請以更口語的方式進行表達。

2021-04-27 12:57 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/github/index.html
> + <li>不同的團隊成員也會需要創建他們自己的獨特的版本（在Git中叫做<strong>branches</strong> (分支)），他們在這裡添加一些新的功能特性，然後通過一些可控的方法（在GitHub 中我們使用<strong>pull request</strong> (拉取請求)）將其合併到原來的主幹項目中。 </li>
`（在Git中叫做<strong>branches</strong> (分支)）`
中文間的標點符號請用全形，若碰到雙重夾注號可以考慮混合甲式及乙式避免過於突兀。

2021-04-27 12:57 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/github/index.html
> + <li>一個工具來使用Git，取決於你喜歡用哪類型工具，你可以使用一個 <a href="https://git-scm.com/downloads/guis/">Git GUI client</a> (我們建議使用GitHub Desktop, SourceTree or Git Kraken) 或是堅持使用terminal window。即便你傾向使用GUI，實際上使用terminal w
`或是堅持使用`
這裡翻譯為「堅持」使用有點詭異，可以考慮就用白話一點「或就用」

2021-04-27 12:57 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/github/index.html
> +<p>最好還具有一些基本的終端機知識，例如在目錄之間移動，創立文件以及修改系統<code> 路徑 </ code>。</ p>
`<code> 路徑 </ code>`
特別用 `<code>` 修飾的文字通常是不需要翻譯的，這裡的 `PATH` 指的是系統的 `PATH` 環境變數，請不要翻譯。

2021-04-27 12:57 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/github/index.html
> +  <dd>這本Git手冊更深入地介紹了版本控制系统是什麼，存儲庫是什麼，基本GitHub模如何運行，Git命令和範例等等。</ dd>
`存儲庫`
台灣沒有「存儲」這種說法，這是對岸的用語，請避免使用。
關於台灣本地慣用翻譯的部分請參考
1. 微軟 Language Portal 
2. 國家教育研究院的「雙語詞彙、學術名詞暨辭書資訊網」

2021-04-27 12:57 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/github/index.html
> +  <dd>當您想為別人的代碼做貢獻時，Forking Projects分叉專案是必不可少的。本指南說明了方法。</ dd>
`代碼`
請用「程式碼」

2021-04-27 12:57 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/github/index.html
> +  <dd>問題就像是GitHub項目的論壇，人們可以在其中提出問題和報告問題，還可以管理更新（例如，分配人員來解決問題，澄清問題，讓人們知道問題已解決）。本文為您提供了您需要了解的有關問題的信息。</ dd>
`信息`
請避免使用中國用語，可用「資訊」／「訊息」。
參考翻譯：「本文將提供你有關問題的必備知識」

2021-04-27 12:57 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/github/index.html
> +<p><strong>溫馨提示：</strong> 在 Git 和 GitHub 上面你還可以做一大堆事情，但我們認為，如果你想要有效地使用 Git ，上面的這些知識是至少應該具備的。當你更深入地了解 Git 時，你將會意識到，當你開始使用更加複雜的指令時會更容易出錯。但不要擔心，即使是專業的網絡工程師有時都會感到困惑，並通過網絡檢索或<a href="https://github.com/k8
`在 Git 和 GitHub 上面你還可以做一大堆事情`
參考翻譯：「你還可以用 git 跟 github 來完成更多的事情」

`網絡`
中國用語，請用「網路」

```
這樣的網站來尋找答案。 </p>
                    ^
```
請留意多餘的空格

2021-04-27 12:57 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/github/index.html
> +  </li>
這裡直接翻譯就好，不用留原文，反正已經有連結，讀者可以自行點閱。

2021-04-28 16:22 UTC, javawillch commented on files/zh-tw/learn/tools_and_testing/github/index.html
> +  </li>
好的謝謝

2021-04-28 16:22 UTC, javawillch commented on files/zh-tw/learn/tools_and_testing/github/index.html
> +<p><strong>溫馨提示：</strong> 在 Git 和 GitHub 上面你還可以做一大堆事情，但我們認為，如果你想要有效地使用 Git ，上面的這些知識是至少應該具備的。當你更深入地了解 Git 時，你將會意識到，當你開始使用更加複雜的指令時會更容易出錯。但不要擔心，即使是專業的網絡工程師有時都會感到困惑，並通過網絡檢索或<a href="https://github.com/k8
好的謝謝

2021-04-28 16:23 UTC, javawillch commented on files/zh-tw/learn/tools_and_testing/github/index.html
> +  <dd>問題就像是GitHub項目的論壇，人們可以在其中提出問題和報告問題，還可以管理更新（例如，分配人員來解決問題，澄清問題，讓人們知道問題已解決）。本文為您提供了您需要了解的有關問題的信息。</ dd>
好的謝謝

2021-04-28 16:23 UTC, javawillch commented on files/zh-tw/learn/tools_and_testing/github/index.html
> +  <dd>當您想為別人的代碼做貢獻時，Forking Projects分叉專案是必不可少的。本指南說明了方法。</ dd>
好的謝謝

2021-04-28 16:24 UTC, javawillch commented on files/zh-tw/learn/tools_and_testing/github/index.html
> +  <dd>這本Git手冊更深入地介紹了版本控制系统是什麼，存儲庫是什麼，基本GitHub模如何運行，Git命令和範例等等。</ dd>
https://www.microsoft.com/zh-tw/language
https://terms.naer.edu.tw/
確認一下是這兩個網址嗎？ 感謝

2021-04-28 16:24 UTC, javawillch commented on files/zh-tw/learn/tools_and_testing/github/index.html
> +<p>最好還具有一些基本的終端機知識，例如在目錄之間移動，創立文件以及修改系統<code> 路徑 </ code>。</ p>
好的 了解

2021-04-28 16:25 UTC, javawillch commented on files/zh-tw/learn/tools_and_testing/github/index.html
> + <li>一個工具來使用Git，取決於你喜歡用哪類型工具，你可以使用一個 <a href="https://git-scm.com/downloads/guis/">Git GUI client</a> (我們建議使用GitHub Desktop, SourceTree or Git Kraken) 或是堅持使用terminal window。即便你傾向使用GUI，實際上使用terminal w
好的

2021-04-28 16:25 UTC, javawillch commented on files/zh-tw/learn/tools_and_testing/github/index.html
> + <li>不同的團隊成員也會需要創建他們自己的獨特的版本（在Git中叫做<strong>branches</strong> (分支)），他們在這裡添加一些新的功能特性，然後通過一些可控的方法（在GitHub 中我們使用<strong>pull request</strong> (拉取請求)）將其合併到原來的主幹項目中。 </li>
若碰到雙重夾注號可以考慮混合甲式及乙式避免過於突兀 二這句話沒有很名白 
總之我都是改全形的標點符號可以嗎？

2021-04-28 16:28 UTC, javawillch reviewed
請問我是把修改完的版本，點選下面Resolve Conflicts然後copy paste上去嗎？
還是我要再重新commit一次然後再pull request?

2021-04-28 18:32 UTC, irvin commented
> 請問我是把修改完的版本，點選下面Resolve Conflicts然後copy paste上去嗎？
> 還是我要再重新commit一次然後再pull request?

用一個新的 commit，pull request 會自動更新

2021-05-01 11:20 UTC, t7yang requested changes
因為過多的錯誤，我不一一指名。

請重新檢視全文並注意下列事項

下列為通用原則，你的翻譯可能沒有包含下列所有羅列的問題，但仍建議你仔細閱讀。

標點符號

- 正確性（正確使用、使用中文全形標點）、一致性
- 參考：
  - [教育部《重訂標點符號手冊》修訂版](https://language.moe.gov.tw/001/upload/files/site_content/m0001/hau/haushou.htm)
  - [維基百科標點符號](https://zh.wikipedia.org/zh-tw/%E6%A0%87%E7%82%B9%E7%AC%A6%E5%8F%B7)

中外文交界的修飾

- 基於閱讀及選取操作上的便利性，中外文（拉丁語系）交界處請使用一個半形空格進行修飾。範例，
  - `使用 Git 作為版本控制`
  - 中文標點符號既中文字：`版本控制系統—— Git 。` （ `Git` 前後的空格）

在地化詞彙

- 應使用本地化詞彙，如「Network 網路 ~~網絡~~」、「Code 程式碼 ~~代碼~~」、「Programming 程式設計／程設 ~~編程~~」、「Array 陣列 ~~數組~~」、「Configuration 組態 ~~配置~~」、「Extension 套件 ~~插件~~」等。
- 請盡可能避免參考線上翻譯，如 Google 翻譯，應參考：
  - [國家教育研究院 雙語詞彙、學術名詞暨辭書資訊網](https://terms.naer.edu.tw/)
  - [微軟語言入口網站](https://www.microsoft.com/zh-tw/language/)
- 在翻譯專業領域文章時，術語翻譯應參考台灣該領域之專家著作，譬如 Git 主題請參考高見龍等專家著作。

2021-05-03 14:12 UTC, t7yang requested changes
翻譯內容仍有多處瑕疵，再麻煩根據翻譯指導原則重新檢視翻譯，感謝。

https://github.com/mdn/translated-content/blob/main/docs/zh-tw/translation-guide.md

2021-08-12 04:42 UTC, merged