zh-CN:translate progress
mdn/translated-content pull request #6626
Opened 2022-07-01 05:25 UTC by Jack-Zhang-1314

2022-07-01 23:36 UTC, yin1999 requested changes
翻译完成请对照英文原文阅读一遍

2022-07-01 23:36 UTC, yin1999 commented on files/zh-cn/web/api/progressevent/progressevent/index.md
> +**`ProgressEvent()`** 构造函数返回一个新的 {{domxref("ProgressEvent")}} 对象，表示当前一个漫长过程的进度。
```suggestion
**`ProgressEvent()`** 构造函数返回一个新的 {{domxref("ProgressEvent")}} 对象，表示当前一个漫长处理过程的完成进度。
```

2022-07-01 23:36 UTC, yin1999 commented on files/zh-cn/web/api/progressevent/progressevent/index.md
> +  - : 带有事件名称的字符串。它是区分大小写的，并且浏览器将其设置为 `loadstart`、`progress`、`abort`、`error`、`load`、`timeout` 或者 `loadend`。
```suggestion
  - : 带有事件名称的字符串。它是区分大小写的，浏览器将其设置为 `loadstart`、`progress`、`abort`、`error`、`load`、`timeout` 或 `loadend`。
```

2022-07-01 23:36 UTC, yin1999 commented on files/zh-cn/web/api/progressevent/progressevent/index.md
> +  - : 一个对象，除了 {{domxref("Event/Event", "Event()")}} 中定义的属性，他还具有以下属性:
```suggestion
  - : 一个对象，除了 {{domxref("Event/Event", "Event()")}} 中定义的属性，它还具有以下属性:
```

2022-07-01 23:36 UTC, yin1999 commented on files/zh-cn/web/api/progressevent/progressevent/index.md
> +      - : 一个布尔值，表示底层的进程将要完成的总工作量和已经完成的工作流是否是可计算的。换句话说，它说明进度是否可衡量。它的默认值是 `false`。
```suggestion
      - : 一个布尔值，表示底层的进程将要完成的总工作量和已经完成的工作量是否是可计算的。换句话说，它说明进度是否可衡量。它的默认值是 `false`。
```

2022-07-01 23:36 UTC, yin1999 commented on files/zh-cn/web/api/progressevent/progressevent/index.md
> +      - : 一个数值，表示底层的进程已经执行的工作量。可以使用该属性和 `ProgressEvent.total` 计算完成工作的比率。当使用一个 HTTP 下载资源，这个仅表示内容本身的一部分，不包含头和其他开销。它默认为 `0`。
```suggestion
      - : 一个数值，表示底层的进程已经完成的工作量。可以使用该属性和 `ProgressEvent.total` 计算完成工作的比例。当使用 HTTP 下载一个资源时，其仅表示内容本身（body）的部分，不包含头和其它开销。它默认值为 `0`。
```

2022-07-01 23:36 UTC, yin1999 commented on files/zh-cn/web/api/progressevent/progressevent/index.md
> +      - : 一个数值，表示底层的进程正在执行的工作量的总量。当使用一个 HTTP 下载资源，这个仅表示内容本身的一部分，不包含头和其他开销。它默认为 `0`。
```suggestion
      - : 一个数值，表示底层的进程正在进行的工作的总工作量。当使用 HTTP 下载一个资源时，其仅表示内容本身（body）的部分，不包含头和其它开销。它默认值为 `0`。
```

2022-07-01 23:36 UTC, yin1999 commented
注意名称代词，正常情况下，应使用不隐含性别的“它”，而非“他”。

2022-07-01 23:41 UTC, merged

2022-07-02 00:47 UTC, Jack-Zhang-1314 commented
👌的,下次注意