Update translation for object
mdn/translated-content pull request #6643
Opened 2022-07-02 01:52 UTC by marcelozarate

This should fix #4558

2022-07-04 15:59 UTC, Graywolf9 requested changes
Muchas gracias por la actualización del documento! Te he dejado algunos comentarios @marcelozarate

2022-07-04 15:59 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/object/index.md
> +## Description
Línea extra y reorganiza texto

```suggestion
Casi todos los objetos en JavaScript son instancias de {{jsxref("Object")}}; un objeto típico hereda propiedades (incluyendo los métodos) de `Object.prototype`, a pesar de que esas propiedas puedan ser sobreescritas. Aun así, un `Object` puede ser deliberadamente creado para que esto no se cumpla (por ejemplo con {{jsxref("Object.create", "Object.create(null)")}}), o puede alterarse para que esto no sea más verdad (por ejemplo con {{jsxref("Object.setPrototypeOf")}}).
```

2022-07-04 15:59 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/object/index.md
> +Los cambios realizados en el `Object` prototipo son vistos por todos los objetos de la cadena de prototipos, a no ser que las propiedas y métodos sujetos a esos cambios hayan sido sobreescritos más a
Reorganiza texto

```suggestion
Los cambios realizados en el `Object` prototipo son vistos por todos los objetos de la cadena de prototipos, a no ser que las propiedas y métodos sujetos a esos cambios hayan sido sobreescritos más abajo en la cadena. Sobreescribir o extender el comportamiento de un objeto es un mecanismo muy poderoso, aunque potencialmente peligroso.
```

2022-07-04 22:02 UTC, marcelozarate reviewed
Fix typos

2022-07-06 15:02 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/object/index.md
> +var rg = new Employee("Red Green", "Manitas");
```suggestion
var rg = new Employee("Red Green", "Reparador");
```

2022-07-06 15:02 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/object/index.md
> +// Hola, yo soy Red Green, el Manitas
```suggestion
// Hola, yo soy Red Green, el Reparador
```

2022-07-11 15:55 UTC, Graywolf9 approved these changes
Excelente, muchas gracias por tu valioso tiempo y aportación.

2022-07-11 15:55 UTC, merged