Building Angular applications and further resources 繁體中文整頁
mdn/translated-content pull request #668
Opened 2021-04-27 15:05 UTC by ShawnTseng

Page: Building Angular applications and further resources
Language: zh-TW
1. The link was changed.
2. The translation of this page completed.
3. The footer navigation in this page was changed.

2021-04-27 15:45 UTC, t7yang requested changes
幾乎都是標點符號及風格不一致，請重新檢視全文並修正。

若對標點符號的應用有疑問，請參閱：
  - [教育部《重訂標點符號手冊》修訂版](https://language.moe.gov.tw/001/upload/files/site_content/m0001/hau/haushou.htm)
  - [維基百科標點符號](https://zh.wikipedia.org/zh-tw/%E6%A0%87%E7%82%B9%E7%AC%A6%E5%8F%B7)

2021-04-27 15:45 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_building/index.html
> +<p>這篇文章內容涵蓋，如何建立一個產品版本(production)的應用程式，以及提供後續的學習資源。</p>
`產品版本(production)的應用程式`
中文間請使用正確中文全形夾注號：`產品版本（production）的應用程式`

2021-04-27 15:45 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_building/index.html
> +   <td>學會如何編譯你的Angular應用程式</td>
> 你的Angular應
中英文穿插請維持一致的風格，若想要前後保持一半形空格則全文都應維持此風格。

2021-04-27 15:45 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_building/index.html
> +<p>你可以使用任何後端，像是 <a href="https://firebase.google.com/docs/hosting">Firebase</a>, <a href="https://cloud.google.com/solutions/web-hosting">Google Cloud</a> 或 <a href="https://cloud.google.com/appengin
> <a href="https://firebase.google.com/docs/hosting">Firebase</a>, <a href="https://cloud.google.com/solutions/web-hosting">Google Cloud</a> 或 <a href="https://cloud.google.com/appengine/docs/standard/python/getting-started/hosting-a-static-website">App Engine</a>.
應使用中文全形頓號及句號。

2021-04-28 14:48 UTC, ShawnTseng commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_building/index.html
> +<p>這篇文章內容涵蓋，如何建立一個產品版本(production)的應用程式，以及提供後續的學習資源。</p>
已調整，麻煩再協助確認，謝謝。

2021-04-28 14:48 UTC, ShawnTseng commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_building/index.html
> +   <td>學會如何編譯你的Angular應用程式</td>
已調整，麻煩再協助確認，謝謝。

2021-04-28 14:48 UTC, ShawnTseng commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_building/index.html
> +<p>你可以使用任何後端，像是 <a href="https://firebase.google.com/docs/hosting">Firebase</a>, <a href="https://cloud.google.com/solutions/web-hosting">Google Cloud</a> 或 <a href="https://cloud.google.com/appengin
已調整，麻煩再協助確認，謝謝。

2021-04-28 14:49 UTC, ShawnTseng commented
@t7yang 
已調整，麻煩再協助確認，若有遺漏再麻煩告知，謝謝。

2021-04-28 15:29 UTC, t7yang approved these changes
其實翻譯得不錯，但還是有一些問題，再麻煩重新檢視全文並修正。

2021-04-28 15:29 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_building/index.html
> +   <td>熟悉<a href="/zh-TW/docs/Learn/HTML">HTML</a>、<a href="/zh-TW/docs/Learn/CSS">CSS</a>和<a href="/zh-TW/docs/Learn/JavaScript">JavaScript</a>的主要概念，以及<a href="/zh-TW/docs/Learn/Tools_and_testing/Un
> 熟悉<a href="/zh-TW/docs/Learn/HTML">HTML</a>

連結交界的部分其實也應該一樣維持相同風格，請重新檢視全文並修正。

2021-04-28 15:29 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_building/index.html
> +<h2 id="whats_next">接著要做什麼</h2>
標籤之間請跟原文一樣維持一個換行符號（p tag 跟 h2 tag 之間）。

2021-04-28 23:58 UTC, ShawnTseng commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_building/index.html
> +   <td>熟悉<a href="/zh-TW/docs/Learn/HTML">HTML</a>、<a href="/zh-TW/docs/Learn/CSS">CSS</a>和<a href="/zh-TW/docs/Learn/JavaScript">JavaScript</a>的主要概念，以及<a href="/zh-TW/docs/Learn/Tools_and_testing/Un
已調整

2021-04-28 23:58 UTC, ShawnTseng commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_building/index.html
> +<p>命令列介面－CLI（Command Line Interface），會將應用程式編譯並且輸出到新的目錄 <code>dist</code> 底下。
已調整

2021-04-28 23:58 UTC, ShawnTseng commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_building/index.html
> +<h2 id="whats_next">接著要做什麼</h2>
已調整

2021-04-29 00:04 UTC, t7yang requested changes

2021-04-29 00:04 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_building/index.html
> +<p>以上。希望您喜歡Angular！</p>
> 希望您喜歡Angular

中英文間的間隔。

2021-04-29 00:04 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_building/index.html
> +<p>命令列介面 —— CLI（Command Line Interface），會將應用程式編譯並且輸出到新的目錄 <code>dist</code> 底下。
> 命令列介面 ——

中文標點符號就是屬於中文，所以中間自然就不需要多留半個半形空格作為間隔。

2021-04-29 15:00 UTC, ShawnTseng commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_building/index.html
> +<p>命令列介面 —— CLI（Command Line Interface），會將應用程式編譯並且輸出到新的目錄 <code>dist</code> 底下。
已調整

2021-04-29 15:00 UTC, ShawnTseng commented
@t7yang 不好意思，再麻煩看一次。

2021-04-29 15:40 UTC, t7yang approved these changes

2021-04-29 15:47 UTC, merged

2021-04-30 13:31 UTC, doggy8088 commented
@ShawnTseng **Production** 建議可以翻譯成「生產版本」

2021-04-30 16:36 UTC, ShawnTseng commented
> @ShawnTseng **Production** 建議可以翻譯成「生產版本」
@doggy8088 
#712 
Thanks