Work in #4618 | Add: match section
mdn/translated-content pull request #6703
Opened 2022-07-06 02:24 UTC by Jalkhov

Closes #6702

2022-07-06 15:18 UTC, Graywolf9 requested changes
Muchas gracias por tu trabajo, te he dejado algunos comentarios :)

2022-07-06 15:18 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/symbol/match/index.md
> +### Desactivación de la comprobación `isRegExp`.
Prioridad a infinitivos

```suggestion
### Deshabilitar la verificación `isRegExp`.
```

2022-07-06 15:18 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/symbol/match/index.md
> +- [Polyfill of `Symbol.match` in `core-js`](https://github.com/zloirock/core-js#ecmascript-symbol)
```suggestion
- [Polyfill de `Symbol.match` en `core-js`](https://github.com/zloirock/core-js#ecmascript-symbol)
```

2022-07-06 17:16 UTC, Jalkhov commented on files/es/web/javascript/reference/global_objects/symbol/match/index.md
> +### Desactivación de la comprobación `isRegExp`.
A esto me refería cuando comenté lo de Using, que suena mejor colocar Usar, que Usando, este caso es el mismo.

2022-07-07 16:49 UTC, Graywolf9 approved these changes
Muchas gracias por tu tiempo y aporte <3

2022-07-07 16:49 UTC, merged