理解JavaScript 前端框架-更新 Angular 教學目錄
mdn/translated-content pull request #685
Opened 2021-04-28 16:57 UTC by tai0825

更新 Angular 教學目錄

2021-04-28 23:48 UTC, t7yang requested changes

2021-04-28 23:48 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/index.html
> +<p>如果您需要根據我們的版本檢查程式碼，可以在 <a href="https://github.com/kapunahelewong/angular-to-do-example/tree/main/src">angular-to-do-example</a>上找到範例程式碼的最終版本。</p>
> <a href="https://github.com/kapunahelewong/angular-to-do-example/tree/main/src">angular-to-do-example</a>上找到範

請維持一致的風格（中英文間保持一個半型空格）。

2021-04-28 23:48 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/index.html
> + <dt><a href="/zh-TW/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Angular_item_component">4. 建立一個項目組件</a></dt>
> 4. 建立一個項目組件

針對「component」請維持一致的翻譯，建議翻譯為「元件」。

2021-04-29 03:34 UTC, dannypc1628 commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/index.html
> + <dd>元件為您提供了一種組織應用程式的方式。本篇文章將引導您建立一個元件，來處理列表中的各個項目，並增加檢查、編輯以及刪除的功能。</dd>
> the Angular event model is covered here

這段沒有翻譯到，可以翻成如：
`此外， Anguler 的事件模型也會在本篇文章中介紹。`

>本篇文章將引導您建立一個元件，來處理列表中的各個項目，並增加檢查、編輯以及刪除的功能。

第一眼看到`檢查`沒有馬上理解。閱讀前後文後，了解這邊的`列表`指的是`待辦列表`，所以後面的`檢查`指的是待辦項目上面的CheckBox。也許有更順的翻法，但我暫時沒想到><

2021-04-29 05:11 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/index.html
> + <dd>元件為您提供了一種組織應用程式的方式。本篇文章將引導您建立一個元件，來處理列表中的各個項目，並增加檢查、編輯以及刪除的功能。</dd>
Todo List 一般翻譯為待辦清單。如果怕「項目」不容易理解可以直接寫「待辦項目」。

這裡的 check 可以翻譯為「標示完成」。


最後一句也漏翻了。

2021-04-29 07:51 UTC, tai0825 commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/index.html
> + <dd>元件為您提供了一種組織應用程式的方式。本篇文章將引導您建立一個元件，來處理列表中的各個項目，並增加檢查、編輯以及刪除的功能。</dd>
已補上修正版本

2021-04-29 07:53 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/index.html
> + <dd>此刻，我們已準備好使用 Angular 來創建我們的代辦事項應用程式。完成後的應用程式將具有顯示代辦項目列表，並包含編輯、刪除與新增項目等功能。在本篇中，您將學到應用程式的結構，以及建立一個可顯示代辦項目的基礎列表。</dd>
> 代辦事項

待辦不是代辦，記得送出前全部檢視過一遍。

2021-04-29 08:04 UTC, tai0825 commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/index.html
> + <dd>此刻，我們已準備好使用 Angular 來創建我們的代辦事項應用程式。完成後的應用程式將具有顯示代辦項目列表，並包含編輯、刪除與新增項目等功能。在本篇中，您將學到應用程式的結構，以及建立一個可顯示代辦項目的基礎列表。</dd>
已修正完畢

2021-04-29 08:06 UTC, t7yang approved these changes

2021-04-29 08:26 UTC, merged