no terminado primera revision
mdn/translated-content pull request #6851
Opened 2022-07-14 05:04 UTC by EnriqueSource

2022-07-14 10:46 UTC, Jalkhov requested changes
Hola @EnriqueSource, muchas gacias por tu valioso aporte, te he dejado algunos comentarios. Tambien quiero agregar que están faltando algunas zonas del documento, especificamente las zonas despues de la sección: `### Ejemplo 2: Alternando dos colores` y `#### HTML`.

Te dejo nuestra [guía oficial](https://github.com/mdn/translated-content/tree/main/docs/es?rgh-link-date=2022-07-12T21%3A46%3A35Z) para que conozcas todos los pasos para hacer una contribución, y tambien nuestros canales para comunicarte directamente con nosotros en caso de alguna duda:

Telegram: [t.me/+Dr6qKQCAepw4MjFj](https://t.me/+Dr6qKQCAepw4MjFj)
Matrix: [chat.mozilla.org/#/room/#mdn-l10n-es:mozilla.org](https://chat.mozilla.org/#/room/#mdn-l10n-es:mozilla.org)

2022-07-14 10:46 UTC, Jalkhov commented on files/es/web/api/setinterval/index.md
> +El método **`setInterval()`** , ofrecido en las interfaces {{domxref("Window")}} y {{domxref("Worker")}} , llama a una función o ejecuta un fragmento de código de forma reiterada, con un retardo de t
```suggestion
El método **`setInterval()`**, ofrecido en las interfaces {{domxref("Window")}} y {{domxref("Worker")}} , llama a una función o ejecuta un fragmento de código de forma reiterada, con un retardo de tiempo fijo entre cada llamada.
```

2022-07-14 10:46 UTC, Jalkhov commented on files/es/web/api/setinterval/index.md
> +Este método devuelve un ID de intervalo que lo identifica de forma única. de ese modo, el intervalo puede ser eliminado más tarde llamando a {{domxref("clearInterval", "clearInterval()")}} .
```suggestion
Este método devuelve un ID de intervalo que lo identifica de forma única, de ese modo, el intervalo puede ser eliminado más tarde llamando a {{domxref("clearInterval", "clearInterval()")}} .
```

2022-07-14 10:46 UTC, Jalkhov commented on files/es/web/api/setinterval/index.md
> +    - : una función {{jsxref("function")}} que se ejecuta cada cierto tiempo. El tiempo lo determina `delay`, estando éste en milisegundos. La primera ejecución ocurre tras el tiempo determinado por
```suggestion
    - : Una función {{jsxref("function")}} que se ejecuta cada cierto tiempo. El tiempo lo determina `delay`, estando éste en milisegundos. La primera ejecución ocurre tras el tiempo determinado por `delay`.
```

2022-07-14 10:46 UTC, Jalkhov commented on files/es/web/api/setinterval/index.md
> +    - : una sintaxis especial que permite incluir una cadena en lugar de una función, la cual es compilada y ejecutada cada `delay` segundos. Se recomienda no usar esta sintaxis, por la misma razón q
En el archivo de la versión en español dice "milisegundos", en vez de "segundos".
```suggestion
    - : una sintaxis especial que permite incluir una cadena en lugar de una función, la cual es compilada y ejecutada cada `delay` milisegundos. Se recomienda no usar esta sintaxis, por la misma razón que hace que el uso de {{jsxref("Global_Objects/eval", "eval()")}} sea un riesgo de seguridad.
```

2022-07-14 10:46 UTC, Jalkhov commented on files/es/web/api/setinterval/index.md
> +    - : el tiempo en milisegundos (milésimas de segundo) que el temporizador debe retrasar cada ejecución de la función o código especificado. Si no se especifica ninguno, por defecto es 0. Ver el ap
```suggestion
    - : El tiempo en milisegundos (milésimas de segundo) que el temporizador debe retrasar cada ejecución de la función o código especificado. Si no se especifica ninguno, por defecto es 0. Ver el apartado [Delay restrictions](#delay_restrictions) descrito más abajo para más detalles sobre el rango de valores de retardo (delay) permitido.
```

2022-07-14 10:46 UTC, Jalkhov commented on files/es/web/api/setinterval/index.md
> +Puede ser útil tener en cuenta que `setInterval()` y {{domxref("setTimeout()")}} comparten el mismo grupo de IDs. También es importante saber que `clearInterval()` y {{domxref("clearTimeout", "clearT
Pequeño error ortográfico
```suggestion
Puede ser útil tener en cuenta que `setInterval()` y {{domxref("setTimeout()")}} comparten el mismo grupo de IDs. También es importante saber que `clearInterval()` y {{domxref("clearTimeout", "clearTimeout()")}} técnicamente pueden ser utilizados indistintamente. Sin embargo, para mayor claridad siempre debe tratar de hacerlos coincidir, evitando así confusiones al mantener su código.
```

2022-07-15 10:37 UTC, Jalkhov commented
@EnriqueSource Gracias por seguir contribuyendo, a mi parecer hasta ahora todo va bien, estoy a la espera de los siguientes commits n.n

2022-07-15 10:56 UTC, EnriqueSource commented
Muchas gracias @Jalkhov . Espero tenerlo terminado este domingo. Un saludo

2022-07-21 05:02 UTC, EnriqueSource commented
Hola @Jalkhov . La traducción está completada. Hay algunos errores en el entorno de yari. Los errores estan en "Especificaciones" y "Compatibilidad con navegadores". Imagino que estará relacionado con el flag que da en el aviso. Por favor revísalo cuando puedas y haré los cambios necesarios. Un saludo.

2022-07-21 10:45 UTC, EnriqueSource commented
También me gustaría preguntarte sobre los links a otros post de mdn. Sólo he encontrado uno en español. Por eso he decidido dejarlos todos apuntando al post en inglés y preguntarte qué hacer.

2022-07-21 11:12 UTC, Jalkhov requested changes
Hola @EnriqueSource Gracias por seguir contribuyendo, te dejé algunos comentarios, respecto al flaw del bot, no se interpretarlo la verdad, vamos a ver si con las nuevas correcciones sucede algo.

2022-07-21 11:12 UTC, Jalkhov commented on files/es/web/api/setinterval/index.md
> +slug: Web/API/setInterval
@Graywolf9 mencionó que vamos a conservar los slugs.
```suggestion
slug: Web/API/setInterval
translation_of: Web/API/WindowOrWorkerGlobalScope/setInterval
original_slug: Web/API/WindowOrWorkerGlobalScope/setInterval
```

2022-07-21 11:12 UTC, Jalkhov commented on files/es/web/api/setinterval/index.md
> +Cuando le pasas un método a `setInterval()` o cualquier otra función, ésta será invocada con el valor de [`this`](/en-US/docs/Web/JavaScript/Reference/Operators/this) incorrecto. Este problema es exp
```suggestion
Cuando le pasas un método a `setInterval()` o cualquier otra función, ésta será invocada con el valor de [`this`](/es/docs/Web/JavaScript/Reference/Operators/this) incorrecto. Este problema es explicado en detalle en la [JavaScript reference](/en-US/docs/Web/JavaScript/Reference/Operators/this#as_an_object_method).
```

2022-07-21 11:12 UTC, Jalkhov commented on files/es/web/api/setinterval/index.md
> +El código ejecutado por `setInterval` se ejecuta en un contexto de ejecución distinto al de la función desde la que fue llamado. Como consecuencia, la palabra clave [`this`](/en-US/docs/Web/JavaScrip
```suggestion
El código ejecutado por `setInterval` se ejecuta en un contexto de ejecución distinto al de la función desde la que fue llamado. Como consecuencia, la palabra clave [`this`](/es/docs/Web/JavaScript/Reference/Operators/this) para la función llamada se establece en el objeto `window` (u objeto `global`), que no es el mismo contexto de ejecución del valor `this` de la función que llamó a `setInterval()` . Véase el siguiente ejemplo en el que se utiliza `setTimeout()` en lugar de `setInterval()` . El problema con `this` es el mismo en ambos temporizadores:
```

2022-07-21 11:12 UTC, Jalkhov commented on files/es/web/api/setinterval/index.md
> +Todos los entornos de ejecución modernos de JavaScript (en navegadores y otros lugares) soportan [arrow functions](/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions), con `this` léxico,
```suggestion
Todos los entornos de ejecución modernos de JavaScript (en navegadores y otros lugares) soportan [arrow functions](/es/docs/Web/JavaScript/Reference/Functions/Arrow_functions), con `this` léxico, lo que nos permite escribir `setInterval( () => this.myMethod)` si estamos dentro del método `myArray` .
```

2022-07-21 11:12 UTC, Jalkhov commented on files/es/web/api/setinterval/index.md
> +- [Polyfill of `setInterval` wich allows passing arguments to the callback in `core-js`](https://github.com/zloirock/core-js#settimeout-and-setinterval)
```suggestion
- [Polyfill de `setInterval` wich allows passing arguments to the callback en `core-js`](https://github.com/zloirock/core-js#settimeout-and-setinterval)
```

2022-07-21 11:12 UTC, Jalkhov commented on files/es/web/api/setinterval/index.md
> +- {{domxref("window.requestAnimationFrame")}}
Nuestra línea en blanco al final
```suggestion
- {{domxref("window.requestAnimationFrame")}}

```

2022-07-21 11:15 UTC, Jalkhov commented
> También me gustaría preguntarte sobre los links a otros post de mdn. Sólo he encontrado uno en español. Por eso he decidido dejarlos todos apuntando al post en inglés y preguntarte qué hacer.

Hola, todos los links que encuentres deben ser convertidos a su versión en español, solo debes reemplazar `/en-US/` o `/es-US/` por simplemente `/es/`.

2022-07-21 11:18 UTC, Jalkhov commented on files/es/web/api/setinterval/index.md
> +browser-compat: api-setInterval
El error del bot se debe a esto, así es como está en la versión oficial.
```suggestion
browser-compat: api.setInterval
```

2022-07-21 17:55 UTC, JuanVqz commented on files/es/web/api/setinterval/index.md
> +browser-compat: api-setInterval
Que buen ojo!

2022-07-21 17:57 UTC, JuanVqz approved these changes
@EnriqueSource  Gracias por contribuir. @Jalkhov hizo una excelente revisión tambien.

2022-07-21 17:57 UTC, JuanVqz commented on files/es/web/api/setinterval/index.md
> +slug: Web/API/setInterval
Si, totalmente de acuerdo.

2022-07-21 17:57 UTC, JuanVqz commented on files/es/web/api/setinterval/index.md
> +```
Para mi seria poner estos en 2 espacios pero es a personal preference

2022-07-21 19:09 UTC, EnriqueSource commented
Gracias @JuanVqz por tus comentarios y seguimiento

2022-07-21 19:11 UTC, EnriqueSource commented
Ok. @Jalkhov . Gracias por tu revisión y por la aclaración.

2022-07-23 10:30 UTC, EnriqueSource commented on files/es/web/api/setinterval/index.md
> +```
Hola @JuanVqz . Así es como está en el archivo original en _en-us_

2022-07-23 10:53 UTC, Jalkhov commented on files/es/web/api/setinterval/index.md
> +```
> Hola @JuanVqz . Así es como está en el archivo original en _en-us_

Hola @EnriqueSource Precisamente por eso @JuanVqz dijo que es una preferencia personal n.n Si te parece, aceptalo, sino, no hay problema, puedes clickar en "Resolve conversation" para cerra este tema.

2022-07-23 10:53 UTC, EnriqueSource commented
Hola @Jalkhov . Además de resolver tus comentarios he añadido se campo _l10n_ con el valor sha en _sourceCommit_ , tal y como hizo @JuanVqz en su último commit. Tampoco añadir ningún tag, ya que creo que no hay que añadirlos. Espero que todo está ya correcto. Cualquier cosa que haya que cambiar no dudes en comentarla. Un saludo

2022-07-23 11:11 UTC, Jalkhov commented on files/es/web/api/setinterval/index.md
> +  sourceCommit: a7a18a2913f5abc5b4342fa01d1dae00cdd7c629
Tengo una duda, revisando el archivo original noto que usaste un SHA que está anterior a algunos más nuevos, 2 específicamente, esto puede ser totalmente válido si cuando hiciste los cambios te basaste en los cambios realizados hasta ese commit, pero, comparando los archivos veo que los cambios que están en el commit mas nuevo del archivo original, están en tu PR, por lo que prefiero preguntarte porque usaste ese commit específicamente?
![imagen](https://user-images.githubusercontent.com/36505934/180602627-79993ad9-d90b-4073-bedf-524e0507a316.png)

2022-07-23 11:12 UTC, Jalkhov reviewed
Hola de nuevo @EnriqueSource Muy buena por agregar los slugs y nuestro nuevo metadato, te dejé un solo comentario, pero es importante n.n

2022-07-23 13:42 UTC, EnriqueSource commented
Gracias @Jalkhov . Efectivamente he visto tu comentario. Problema de actualización de mi folk con el repo original. He visto unos cámbios menores en algún titulo. Arreglaré los cambios al final del día y envío el commit definitivo.

2022-07-24 14:04 UTC, EnriqueSource commented
Hola @Jalkhov . Crea que ya está todo prefecto. Cualquier cosa dímelo. Un saludo

2022-07-24 16:54 UTC, Jalkhov requested changes
Hola @EnriqueSource ahora sí está todo acorde, mchas gracias por tomarte el tiempo, solo te dejé un comentario y estamos listos.

2022-07-24 16:54 UTC, Jalkhov commented on files/es/web/api/setinterval/index.md
> +- [Polyfill de `setInterval` wich allows passing arguments to the callback en `core-js`](https://github.com/zloirock/core-js#settimeout-and-setinterval)
Ups, se me pasó esto la vez pasada. Tu eliges si aceptas mi traducción o si tienes alguna mejor pues adelante n.n
```suggestion
- [Polyfill de `setInterval` que permite pasar argumentos al callback en `core-js`](https://github.com/zloirock/core-js#settimeout-and-setinterval)
```

2022-07-24 19:42 UTC, EnriqueSource commented on files/es/web/api/setinterval/index.md
> +- [Polyfill de `setInterval` wich allows passing arguments to the callback en `core-js`](https://github.com/zloirock/core-js#settimeout-and-setinterval)
Esa traducción es perfecta. Resuelta

2022-07-24 19:53 UTC, Jalkhov commented
Muchas gracias @EnriqueSource por tu valioso aporte, espero seguir viendote por aquí n.n

2022-07-24 19:55 UTC, Jalkhov approved these changes
Muchas gracias @EnriqueSource por tu valioso aporte, espero seguir viendote por aquí n.n

2022-07-24 20:02 UTC, merged

2022-07-25 10:46 UTC, EnriqueSource commented
De nada @Jalkhov . Gracias por tus palabras. Sí, seguirás viéndome por aquí.