Learn/Forms/HTML_forms_in_legacy_browsers を更新
mdn/translated-content pull request #689
Opened 2021-04-29 13:45 UTC by mfuji09

- 2021/04/28 時点の英語版に更新
- 原語併記マクロを削除 (https://github.com/mozilla-japan/translation/issues/547)

2021-05-01 08:53 UTC, potappo requested changes
typo の修正を提案しています。確認お願いします。

2021-05-01 08:53 UTC, potappo commented on files/ja/learn/forms/html_forms_in_legacy_browsers/index.html
> +<p>{{HTMLElement("button")}} 要は 2 つの問題に悩まされていましたが、すでに解決しました。</p>
```suggestion
<p>{{HTMLElement("button")}} 要素は 2 つの問題に悩まされていましたが、すでに解決しました。</p>
```

2021-05-01 08:53 UTC, potappo commented on files/ja/learn/forms/html_forms_in_legacy_browsers/index.html
> +<p>一般に、フォームコントロールの既定の外観は変更しない方が良いと考えられています。というのも、 1 つの CSS プロパティの値を変更すると、一部の入力型は変更されますが、他の入力型は変更されないからです。例えば、 <code>input { font-size: 2rem; }</code> と宣言した場合、 <code>number</code>、<code>date</code>、<c
```suggestion
<p>一般に、フォームコントロールの既定の外観は変更しない方が良いと考えられています。というのも、 1 つの CSS プロパティの値を変更すると、一部の入力型は変更されますが、他の入力型は変更されないからです。例えば、 <code>input { font-size: 2rem; }</code> と宣言した場合、 <code>number</code>、<code>date</code>、<code>text</code> には影響がありますが、 <code>color</code> や <code>range</code> には影響しません。プロパティを変更すると、予期せぬ形でウィジェットの外観に影響を与えることがあります。例えば、 <code>[value] { background-color: #ccc; }</code> は、 <code>value</code> 属性を持つすべての {{HTMLElement("input")}} を対象としていますが、 {{HTMLElement("meter")}} の背景色や境界線の角の丸めを変更すると、ブラウザーによって異なる予期せぬ結果になる可能性があります。 {{cssxref('appearance', 'appearance: none;')}} と宣言してブラウザーのスタイルを削除することもできますが、一般的には目的を達成できません。すべてのスタイルが失われ、訪問者が慣れ親しんだ既定のルック＆フィールが削除されるからです。</p>
```

2021-05-01 15:16 UTC, mfuji09 commented
ありがとうございます！取り込みました。

2021-05-02 14:14 UTC, potappo approved these changes

2021-05-02 14:14 UTC, merged