[todo list beginning] complete the first part translation
mdn/translated-content pull request #690
Opened 2021-04-29 13:46 UTC by Kun-Neng

1. 修改誤植錯字"代辦"。
2. 完成 [開始開發我們的 Angular 待辦事項應用程式] 第一部分翻譯，其餘部分尚未完成，之後會再發新的 PR 補上。

2021-04-29 15:38 UTC, t7yang requested changes

2021-04-29 15:38 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_todo_list_beginning/index.html
> +這個待辦事項應用程式有兩個元件 — 一個元件作為您的應用程式基底，另一個元件用來處理待辦事項。</p>
> 元件 — 一個

請使用正確的中文破折號

2021-04-30 06:33 UTC, Kun-Neng commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_todo_list_beginning/index.html
> +這個待辦事項應用程式有兩個元件 — 一個元件作為您的應用程式基底，另一個元件用來處理待辦事項。</p>
請問是改成"元件 - 一個"嗎？

2021-04-30 06:49 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_todo_list_beginning/index.html
> +這個待辦事項應用程式有兩個元件 — 一個元件作為您的應用程式基底，另一個元件用來處理待辦事項。</p>
[教育部《重訂標點符號手冊》修訂版](https://language.moe.gov.tw/001/upload/files/site_content/m0001/hau/haushou.htm)

2021-04-30 11:48 UTC, t7yang requested changes

2021-04-30 11:48 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_todo_list_beginning/index.html
> +這個待辦事項應用程式有兩個元件 ── 一個元件作為您的應用程式基底，另一個元件用來處理待辦事項。</p>
> 元件 ── 一個
中文標點符號就是中文字，自然就不用用半形空格去修飾。

2021-04-30 12:08 UTC, Kun-Neng reviewed
移除中文破折號前後空格

2021-04-30 12:08 UTC, Kun-Neng commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_todo_list_beginning/index.html
> +這個待辦事項應用程式有兩個元件 ── 一個元件作為您的應用程式基底，另一個元件用來處理待辦事項。</p>
好的，再去修正。

2021-04-30 13:17 UTC, t7yang approved these changes

2021-04-30 13:18 UTC, merged