zh-CN:translate  Picture-in-Picture
mdn/translated-content pull request #6913
Opened 2022-07-16 22:41 UTC by Jack-Zhang-1314

2022-07-16 22:56 UTC, yin1999 requested changes
请进一步润色部分语句的翻译

2022-07-16 22:56 UTC, yin1999 commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +[`:picture-in-picture`](/zh-CN/docs/Web/CSS/:picture-in-picture) [CSS](/zh-CN/docs/Web/CSS) [伪类](/zh-CN/docs/Web/CSS/Pseudo-classes) 匹配当前进入画中画模式的视频元素，允许你配置样式表，以便视频来回在画中画或者传统演示模式切换时去自动适应大小，样式或布局内容。
中文与中文之间请不要添加空格，请阅读完整阅读 [MDN 简体中文文档翻译指南](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md)。

2022-07-16 22:56 UTC, yin1999 commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +  - : 表示浮动的视频窗口;包含 {{domxref("PictureInPictureWindow/width", "width")}} 和 {{domxref("PictureInPictureWindow/height", "height")}} 属性，以及一个 {{domxref("PictureInPictureWindow/onresize", "onresize")}} 事件处
中文标点

2022-07-16 23:04 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +[`:picture-in-picture`](/zh-CN/docs/Web/CSS/:picture-in-picture) [CSS](/zh-CN/docs/Web/CSS) [伪类](/zh-CN/docs/Web/CSS/Pseudo-classes) 匹配当前进入画中画模式的视频元素，允许你配置样式表，以便视频来回在画中画或者传统演示模式切换时去自动适应大小，样式或布局内容。
ok

2022-07-17 01:28 UTC, linlinzzo commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +画中画 API 添加了 {{DOMxRef("HTMLVideoElement")}} 和 {{DOMxRef("Document")}} 接口的方法，以允许切换浮动视频窗口。
```suggestion
画中画 API 添加了 {{DOMxRef("HTMLVideoElement")}} 和 {{DOMxRef("Document")}} 接口的方法，以便允许切换浮动视频窗口。
```

2022-07-17 01:28 UTC, linlinzzo commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +*画中画 API 添加了* {{DOMxRef("HTMLVideoElement")}}、{{DOMxRef("Document")}} 和 {{DOMxRef("ShadowRoot")}} 接口的属性，这些属性用于决定是否浮动的视频窗口是受支持和可用的，是否当前画中画模式是处于激活状态并且哪个视频是浮动的。
```suggestion
*画中画 API 添加了* {{DOMxRef("HTMLVideoElement")}}、{{DOMxRef("Document")}} 和 {{DOMxRef("ShadowRoot")}} 接口的属性，这些属性用于决定是否浮动的视频窗口是受支持和可用的、是否当前画中画模式是处于激活状态并且哪个视频是浮动的。
```

2022-07-17 01:28 UTC, linlinzzo commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +  - : 当用户切换 tab 和/或 应用程序时，`autoPictureInPicture` 属性将自动进入和离开视频元素的画中画模式。
```suggestion
  - : 当用户切换标签页和（或）应用程序时，`autoPictureInPicture` 属性将自动进入或离开视频元素的画中画模式。
```

2022-07-17 01:28 UTC, linlinzzo commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +参见 [使用 Feature Policy](/zh-CN/docs/Web/HTTP/Feature_Policy/Using_Feature_Policy) 去了解关于使用 Feature Policy 控制对 API 访问的更多信息。
```suggestion
参见[使用 Feature Policy](/zh-CN/docs/Web/HTTP/Feature_Policy/Using_Feature_Policy) 去了解关于使用 Feature Policy 控制对 API 访问的更多信息。
```

2022-07-17 01:28 UTC, linlinzzo commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +当使用者点击“Toggle Picture-in-Picture”按钮时，这段代码由一个点击处理程序调用：
```suggestion
当使用者点击 `Toggle Picture-in-Picture` 按钮时，这段代码将会由一个点击处理程序调用：
```

2022-07-17 01:28 UTC, linlinzzo commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +该块首先查看 {{DOMxRef("Document", "document")}} `pictureInPictureElement` 属性的值。
```suggestion
该块首先会查看 {{DOMxRef("Document", "document")}} `pictureInPictureElement` 属性的值。
```

2022-07-17 02:40 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +当使用者点击“Toggle Picture-in-Picture”按钮时，这段代码由一个点击处理程序调用：
符号并不需要更改

2022-07-17 03:00 UTC, linlinzzo approved these changes
LGTM

2022-07-18 04:36 UTC, yin1999 requested changes

2022-07-18 04:36 UTC, yin1999 commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +*画中画 API 添加了* {{DOMxRef("HTMLVideoElement")}}、{{DOMxRef("Document")}} 和 {{DOMxRef("ShadowRoot")}} 接口的属性，这些属性用于决定是否浮动的视频窗口是受支持和可用的、是否当前画中画模式是处于激活状态并且哪个视频是浮动的。
请修改

2022-07-18 04:36 UTC, yin1999 commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +  - : `disablePictureInPicture` 属性将提供一个用户代理不向用户建议使用画中画或者自动请求它的提示。
请修改

2022-07-18 04:36 UTC, yin1999 commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +_画中画 API 定义了三个事件，它们可以被用来检测何时画中画模式被切换或者何时浮动窗口大小被调整。_
请修改，中文的常用语序是不会把疑问词放在前面的。

```
你中午吃什么了？
```

```
什么你中午吃了？
```

2022-07-18 04:36 UTC, yin1999 commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +  - : 当它大小改变时发送到 {{DOMxRef("PictureInPictureWindow")}}。
请修改

2022-07-18 04:36 UTC, yin1999 commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +[CSS](/zh-CN/docs/Web/CSS) 的[伪类](/zh-CN/docs/Web/CSS/Pseudo-classes) [`:picture-in-picture`](/zh-CN/docs/Web/CSS/:picture-in-picture) 匹配当前进入画中画模式的视频元素，并允许你配置样式表，以便视频在画中画或者传统播放模式来回切换时去自动适应大小，样式或布局内容。
请根据已合并的PR修改

2022-07-18 04:36 UTC, yin1999 commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +## 控制权限
```suggestion
## 控制访问权限
```

2022-07-18 04:36 UTC, yin1999 commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +可以使用 [Feature Policy](/zh-CN/docs/Web/HTTP/Feature_Policy) 控制画中画的可用性。全屏模式的功能由字符 `"picture-in-picture"` 标识，默认允许的列表值是 `"self"`，意味着在顶级文档上下文以及从最顶层文档相同的来源加载的嵌套浏览上下文中允许画中画模式。
```suggestion
可以使用 [Feature Policy](/zh-CN/docs/Web/HTTP/Feature_Policy) 控制画中画的可用性。全屏模式的功能由字符串 `"picture-in-picture"` 标识，默认的允许列表的值是 `"self"`，意味着在顶级文档上下文以及从最顶层文档相同的来源加载的嵌套浏览上下文中允许画中画模式。
```

2022-07-18 04:36 UTC, yin1999 commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +参见 [使用 Feature Policy](/zh-CN/docs/Web/HTTP/Feature_Policy/Using_Feature_Policy) 去了解关于使用 Feature Policy 控制对 API 访问的更多信息。
```suggestion
参见[使用 Feature Policy](/zh-CN/docs/Web/HTTP/Feature_Policy/Using_Feature_Policy)，了解关于使用 Feature Policy 控制对 API 访问的更多信息。
```

2022-07-18 04:36 UTC, yin1999 commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +该块首先会查看 {{DOMxRef("Document", "document")}} `pictureInPictureElement` 属性的值。
```suggestion
该块首先会查询 {{DOMxRef("Document", "document")}} `pictureInPictureElement` 属性的值。
```

2022-07-18 04:36 UTC, yin1999 commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +如果值不是 `null`，则它是当前处于画中画模式并在浮动窗口的元素。我们调用 {{DOMxRef("Document.exitPictureInPicture", "document.exitPictureInPicture()")}} 将视频带进它初始的大小。
```suggestion
如果值不是 `null`，则它是当前处于画中画模式并在浮动窗口的元素。我们调用 {{DOMxRef("Document.exitPictureInPicture", "document.exitPictureInPicture()")}} 将视频带进它初始的盒子。
```

2022-07-18 07:11 UTC, linlinzzo commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +  - : `disablePictureInPicture` 属性将指示用户代理是否应该向用户建议画中画的功能，或者自动请求该功能。
原文： https://github.com/mdn/content/blob/main/files/en-us/web/api/picture-in-picture_api/index.md?plain=1#L51

上面写着 to not suggest，此处翻译为“是否”，不太妥当吧？

```suggestion
  - : `disablePictureInPicture` 属性将指示用户代理不向用户建议画中画的功能，或者自动请求该功能。
```

2022-07-18 07:33 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +  - : `disablePictureInPicture` 属性将指示用户代理是否应该向用户建议画中画的功能，或者自动请求该功能。
true阻止该功能

2022-07-18 13:14 UTC, yin1999 commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +*画中画 API 添加了* {{DOMxRef("HTMLVideoElement")}}、{{DOMxRef("Document")}} 和 {{DOMxRef("ShadowRoot")}} 接口的属性，这些属性用于决定是否浮动的视频窗口是受支持和可用、是否当前画中画模式处于激活状态并且哪个视频是浮动的。
```suggestion
*画中画 API 添加了* {{DOMxRef("HTMLVideoElement")}}、{{DOMxRef("Document")}} 和 {{DOMxRef("ShadowRoot")}} 接口的属性，这些属性用于决定浮动的视频窗口是否是受支持和可用的、当前画中画模式是否处于激活状态并且哪个视频是浮动的。
```

2022-07-18 13:14 UTC, yin1999 commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +  - : `disablePictureInPicture` 属性将指示用户代理是否应该向用户建议画中画的功能，或者自动请求该功能。
这样翻译就行了：

```suggestion
  - : `disablePictureInPicture` 属性将指示用户代理是否应该向用户建议画中画的功能。
```

2022-07-18 13:14 UTC, yin1999 commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +  - : 当 {{DOMxRef("HTMLVideoElement")}} 进入画中画模式发送给它。
```suggestion
  - : 当 {{DOMxRef("HTMLVideoElement")}} 进入画中画模式时触发该事件。
```

2022-07-18 13:14 UTC, yin1999 commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +  - : 当 {{DOMxRef("HTMLVideoElement")}} 离开画中画模式发送给它。
```suggestion
  - : 当 {{DOMxRef("HTMLVideoElement")}} 离开画中画模式时触发该事件。
```

2022-07-18 13:14 UTC, yin1999 commented on files/zh-cn/web/api/picture-in-picture_api/index.md
> +  - : 当 {{DOMxRef("PictureInPictureWindow")}} 大小改变时发送给它。
```suggestion
  - : 当 {{DOMxRef("PictureInPictureWindow")}} 大小改变时触发该事件。
```

2022-07-18 13:19 UTC, merged