Fix #6912 /mozilla/firefox/releases/3/templates/index.html
mdn/translated-content pull request #6921
Opened 2022-07-17 05:13 UTC by Vallejoanderson

Fix #6912

2022-07-17 22:04 UTC, Jalkhov requested changes
Hola @Vallejoanderson Gracias por la pequeña pero valiosa contribución, dejé algunos comentarios/dudas que espero @JuanVqz despeje.

2022-07-17 22:04 UTC, Jalkhov commented on files/es/mozilla/firefox/releases/3/templates/index.md
> +Las plantillas se han mejorado enormemente en Firefox 3. La mejora más importante permite el uso de [procesador de consultas personalizado](/es/Cómo_implementar_un_componente_procesador_de_consultas_
@JuanVqz Corrígeme si me equivoco, pero creo que las url quedan practicamente igual, solo se cambia el código locale ¿No?
```suggestion
Las plantillas se han mejorado enormemente en Firefox 3. La mejora más importante permite el uso de [procesador de consultas personalizado](/es/How_to_implement_a_custom_XUL_query_processor_component) para manejar otro tipo de fuentes de datos además de RDF. Esto es posible gracias a la nueva sintaxis de consultas. También se incluyen soporte para SQL ([mozStorage](/es/docs/Storage)) y fuentes de datos XML. Ya {{ interwiki('wikimo', 'XUL:Template_Features_in_1.9', 'está disponible') }} una descripción completa de las nuevas características para plantillas. ({{ Bug(285631) }})
```

2022-07-17 22:04 UTC, Jalkhov commented on files/es/mozilla/firefox/releases/3/templates/index.md
> +- Se ha mejorado el servicio tipo XUL [sorts](/es/XUL/Guía_de_plantillas/Ordenar_resultados) clasificando mejor tanto el árbol de contenido como el de sin contenido. También permite clasificar conten
Mismo caso que la review anterior.
```suggestion
- Se ha mejorado el servicio tipo XUL [sorts](/es/XUL/Template_Guide/Sorting_Results) clasificando mejor tanto el árbol de contenido como el de sin contenido. También permite clasificar contenidos de plantillas no editables. ({{ Bug(335122) }})
```

2022-07-17 22:45 UTC, JuanVqz commented
> Hola @Vallejoanderson Gracias por la pequeña pero valiosa contribución, dejé algunos comentarios/dudas que espero @JuanVqz despeje.

Completamente de acuerdo ☝️ buen ojo!

2022-07-17 23:01 UTC, Jalkhov requested changes

2022-07-17 23:01 UTC, Jalkhov commented on files/es/mozilla/firefox/releases/3/templates/index.md
> +- [Firefox 3 para desarrolladores](/es/docs/Mozilla/Firefox/Releases/3)
Nuestra respectiva línea en blanco al final que por alguna razón Github se la ahorra jeje
```suggestion
- [Firefox 3 para desarrolladores](/es/docs/Mozilla/Firefox/Releases/3)

```

2022-07-25 23:44 UTC, Jalkhov commented
Hola @Vallejoanderson ¿Cómo va todo por aquí? ¿Alguna novedad en cuanto a este PR?

2022-07-27 04:01 UTC, Vallejoanderson reviewed
Muchas gracias @Jalkhov por las correcciones :)

2022-07-28 10:44 UTC, marcelozarate approved these changes
¡Muchas gracias @Vallejoanderson!

2022-07-28 11:11 UTC, Jalkhov commented
@Vallejoanderson Solo estaría faltando nuestro nuevo metadato, no se si estás al corriente de como se lleva eso.

2022-07-29 21:35 UTC, JuanVqz commented on files/es/mozilla/firefox/releases/3/templates/index.md
> +---
no fui capaz de encontrar el archivo en ingles que corresponde a este documento (en la web).

```suggestion
l10n:
  souceCommit: sha-del-archivo-en-ingles
---
```

2022-07-31 00:23 UTC, marcelozarate requested changes
Ahí te sugerí los cambios, @Vallejoanderson

2022-07-31 00:23 UTC, marcelozarate commented on files/es/mozilla/firefox/releases/3/templates/index.md
> +original_slug: Plantillas_en_Firefox_3
```suggestion
original_slug: Plantillas_en_Firefox_3
l10n:
  sourceCommit: 2aaa075dd310f0de930bab617bb6fe1033970da3
```

Ese sería el sha que tiene que agregar

2022-08-01 01:07 UTC, Vallejoanderson commented on files/es/mozilla/firefox/releases/3/templates/index.md
> +original_slug: Plantillas_en_Firefox_3
Muchas gracias @marcelozarate, tremenda tu ayuda! :D

2022-08-01 04:09 UTC, Jalkhov approved these changes
A mi parecer todos está ok, los `broken_links` que arroja el bot tampoco existen en la versión en inglés, así que creo que por ahora se puede dejar así.

2022-08-01 04:13 UTC, Jalkhov requested changes

2022-08-01 04:13 UTC, Jalkhov commented on files/es/mozilla/firefox/releases/3/templates/index.md
> +  souceCommit: sha-del-archivo-en-ingles
Eso se coló por ahí jeje
```suggestion
l10n:
  sourceCommit: 2aaa075dd310f0de930bab617bb6fe1033970da3
```

2022-08-02 10:54 UTC, Jalkhov approved these changes

2022-08-02 10:56 UTC, Jalkhov commented
Muchas gracias por tu contribución @Vallejoanderson n.n

2022-08-02 10:56 UTC, merged