新增翻译 Sec-CH-UA 标头并修排版
mdn/translated-content pull request #6925
Opened 2022-07-17 10:17 UTC by linlinzzo

2022-07-17 12:56 UTC, linlinzzo commented
Sec-CH-UA 倒是没有您你，已根据之前给的分段建议进行修改。

2022-07-17 22:40 UTC, yin1999 requested changes
请首先阅读<https://developer.mozilla.org/zh-CN/docs/MDN/Contribute/Markdown_in_MDN>，熟悉 MDN 使用的 markdown 规范

2022-07-18 00:43 UTC, linlinzzo commented on files/zh-cn/web/http/headers/sec-ch-ua/index.md
> +- [HTTP 缓存 > 不同的相应](/zh-CN/docs/Web/HTTP/Caching#varying_responses) 和 {{HTTPHeader("Vary")}}
哪个？

2022-07-18 03:38 UTC, linlinzzo commented on files/zh-cn/web/http/headers/sec-ch-ua-arch/index.md
> +- [HTTP 缓存 > 不同的相应](/zh-CN/docs/Web/HTTP/Caching#varying_responses) 和 {{HTTPHeader("Vary")}}
这个中文部分可以这么翻译吗？这个章节后面没翻的页面也都有这个。规范一下？

2022-07-18 03:46 UTC, yin1999 commented on files/zh-cn/web/http/headers/sec-ch-ua-arch/index.md
> +- [HTTP 缓存 > 不同的相应](/zh-CN/docs/Web/HTTP/Caching#varying_responses) 和 {{HTTPHeader("Vary")}}
指什么

2022-07-18 03:47 UTC, linlinzzo commented on files/zh-cn/web/http/headers/sec-ch-ua-arch/index.md
> +- [HTTP 缓存 > 不同的相应](/zh-CN/docs/Web/HTTP/Caching#varying_responses) 和 {{HTTPHeader("Vary")}}
> 指什么

HTTP 缓存 > 不同的相应

2022-07-18 03:47 UTC, yin1999 commented on files/zh-cn/web/http/headers/sec-ch-ua-arch/index.md
> +- [HTTP 缓存 > 不同的相应](/zh-CN/docs/Web/HTTP/Caching#varying_responses) 和 {{HTTPHeader("Vary")}}
这儿有错别字，你还没改对

2022-07-18 03:49 UTC, linlinzzo commented on files/zh-cn/web/http/headers/sec-ch-ua-arch/index.md
> +- [HTTP 缓存 > 不同的相应](/zh-CN/docs/Web/HTTP/Caching#varying_responses) 和 {{HTTPHeader("Vary")}}
> 这儿有错别字，你还没改对

？到底是哪个错别字？

2022-07-18 03:49 UTC, yin1999 commented on files/zh-cn/web/http/headers/sec-ch-ua-arch/index.md
> +- [HTTP 缓存 > 不同的相应](/zh-CN/docs/Web/HTTP/Caching#varying_responses) 和 {{HTTPHeader("Vary")}}
```suggestion
- [HTTP 缓存 > Vary 响应](/zh-CN/docs/Web/HTTP/Caching#vary_响应) 和 {{HTTPHeader("Vary")}}
```

2022-07-18 03:57 UTC, linlinzzo commented on files/zh-cn/web/http/headers/sec-ch-ua-arch/index.md
> +- [HTTP 缓存 > 不同的相应](/zh-CN/docs/Web/HTTP/Caching#varying_responses) 和 {{HTTPHeader("Vary")}}
两个文档的这个地方都改了，之后翻译的时候也会参考。

2022-07-18 14:03 UTC, yin1999 requested changes
注意上下文翻译的一致性，可以在 code review 中批量接受修改建议

2022-07-18 14:03 UTC, yin1999 commented on files/zh-cn/web/http/headers/sec-ch-ua/index.md
> +> **备注：** {{HTTPHeader("Sec-CH-UA-Full-Version-List")}} 与 **`Sec-CH-UA`** 相同，但包括完整版本号，而不是每个品牌的有效版本号。
```suggestion
> **备注：** {{HTTPHeader("Sec-CH-UA-Full-Version-List")}} 与 **`Sec-CH-UA`** 相同，但包括完整版本号，而不是每个品牌的重要版本号。
```

2022-07-18 14:03 UTC, yin1999 commented on files/zh-cn/web/http/headers/sec-ch-ua/index.md
> +  - : 与可区分的 Web 公开功能关联的“营销”版本号。
```suggestion
  - : 与可区分的 Web 公开功能关联的“市场”版本号。
```

2022-07-18 14:03 UTC, yin1999 commented on files/zh-cn/web/http/headers/sec-ch-ua/index.md
> +`Sec-CH-UA` 是一个[低熵提示](/zh-CN/docs/Web/HTTP/Client_hints#low_entropy_hints)。除非被用户代理策略明确阻止，否则它将在所有请求中发送（无需服务器通过发送 {{HTTPHeader("Accept-CH")}} 来选择加入）。来自 Chromium、Chrome、Edge 和 Opera 桌面浏览器的字符串如下所示。请注意，它们
```suggestion
`Sec-CH-UA` 是一个[低熵提示](/zh-CN/docs/Web/HTTP/Client_hints#low_entropy_hints)。除非被用户代理策略明确阻止，否则它将在所有请求中发送（无需通过服务器发送 {{HTTPHeader("Accept-CH")}} 来选择是否发送）。

来自 Chromium、Chrome、Edge 和 Opera 桌面浏览器的字符串如下所示。请注意，它们都共享“Chromium”品牌，但有一个额外的品牌表明其来源。它们还具有故意不正确的品牌字符串，该字符串可能出现在任何位置并具有不同的文本。
```

2022-07-18 14:03 UTC, yin1999 commented on files/zh-cn/web/http/headers/sec-ch-ua/index.md
> +- [用户代理端提示 API](/zh-CN/docs/Web/API/User-Agent_Client_Hints_API)
```suggestion
- [用户代理客户端提示 API](/zh-CN/docs/Web/API/User-Agent_Client_Hints_API)
```

2022-07-18 14:03 UTC, yin1999 commented on files/zh-cn/web/http/headers/sec-ch-ua/index.md
> +- [通过用户代理端提示改善用户隐私和开发人员体验](https://web.dev/user-agent-client-hints/)（web.dev）
```suggestion
- [通过用户代理客户端提示改善用户隐私和开发人员体验](https://web.dev/user-agent-client-hints/)（web.dev）
```

2022-07-18 14:07 UTC, linlinzzo commented
> 下次尽量拆分为不同的PR，建议创建新的分支来提交贡献，而不是在主分支

我好像创建不了这个仓库的分支，fork 到自己的仓库的话会和这个有什么差别吗？

2022-07-18 14:08 UTC, linlinzzo commented
感觉你好像基本 24 小时在弄。。

2022-07-18 14:10 UTC, yin1999 commented
> 我好像创建不了这个仓库的分支，fork 到自己的仓库的话会和这个有什么差别吗？

在fork的仓库中新建分支，也不建议直接修改主分支

2022-07-18 14:10 UTC, merged