Update index.html
mdn/translated-content pull request #6930
Opened 2022-07-17 20:28 UTC by 55TTKKSS

El original, "En este artículo describe" es incorrecto; o bien "En este artículo se describen" (conforme propongo), o "En este artículo describimos" (la versión en inglés), o "Este artículo describe".

2022-07-17 22:57 UTC, JuanVqz commented
En el reporte del bot, muestra qué hay algunas urls rotas/inexistentes.

broken_links:
Can't resolve /en-US/Learn/How_the_Internet_works
Can't resolve https://developer.mozilla.org/en-US/docs/MDN/Getting_started
Can't resolve https://developer.mozilla.org/en-US/docs/Web/HTML
Can't resolve /en-US/docs/Learn/What_is_a_web_server
Can't resolve /en-US/docs/Learn/Understanding_links_on_the_web

Aprovechando tu contribución podrías por favor encontrarlas y arreglarlas?

Como dije si tienes dudas con gusto te podemos ayudar, saludos

2022-07-17 23:15 UTC, 55TTKKSS commented
> 

JuanVqz, muy buenas; de mil amores haría lo que me indicás, esto de encontrar y reparar las url rotas o inexistentes... El problema es que no tengo idea de cómo hacer! Soy burro de "burritud" absoluta en este tema... Estoy tratando de aprender html, css y javascript, y por mi trabajo, vengo medio lento. Si me das un poco de tiempo, aprenderé cómo viene la mano con eso, y prometo meterme en esas correcciones también! ;-)

2022-07-17 23:42 UTC, 55TTKKSS commented
> En el reporte del bot, muestra qué hay algunas urls rotas/inexistentes.
> 
> broken_links: Can't resolve /en-US/Learn/How_the_Internet_works Can't resolve https://developer.mozilla.org/en-US/docs/MDN/Getting_started Can't resolve https://developer.mozilla.org/en-US/docs/Web/HTML Can't resolve /en-US/docs/Learn/What_is_a_web_server Can't resolve /en-US/docs/Learn/Understanding_links_on_the_web
> 
> Aprovechando tu contribución podrías por favor encontrarlas y arreglarlas?
> 
> Como dije si tienes dudas con gusto te podemos ayudar, saludos

JuanVqz, ahí intenté hacer el pull-request de la corrección de "How_the_Internet_works", si puedes, por favor, fíjate si es correcta mi propuesta. Desde ya, mil gracias!

2022-07-18 11:05 UTC, marcelozarate requested changes
Gracias @55TTKKSS ahí van algunos cambios, lo que te sugirió @JuanVqz no era para armar un PR aparte pero bueno, espero que entiendas que la próxima es mejor arreglar todo los problemas del documento en un mismo PR.

2022-07-18 11:05 UTC, marcelozarate commented on files/es/learn/common_questions/pages_sites_servers_and_search_engines/index.html
> +<p><span class="seoSummary">En este artículo se describen varios conceptos referidos a la web: Páginas web, sitios web, servidores web, y motores de búsqueda. Estos términos con frecuencia son confun
```suggestion
<p><span class="seoSummary">En este artículo se describen varios conceptos referidos a la web: Páginas web, sitios web, servidores web, y motores de búsqueda. Estos términos con frecuencia son confundidos por recién llegados a la web, o son incorrectamente usados. ¡Vamos a aprender qué significa cada uno!</span></p>
```

2022-07-18 12:32 UTC, 55TTKKSS commented on files/es/learn/common_questions/pages_sites_servers_and_search_engines/index.html
> +<p><span class="seoSummary">En este artículo se describen varios conceptos referidos a la web: Páginas web, sitios web, servidores web, y motores de búsqueda. Estos términos con frecuencia son confun
> Gracias @55TTKKSS ahí van algunos cambios, lo que te sugirió @JuanVqz no era para armar un PR aparte pero bueno, espero que entiendas que la próxima es mejor arreglar todo los problemas del documento en un mismo PR.

@marcelozarate, ante todo, perdón por la @ si la usé incorrectamente, pero creo entender que es la forma de referirse a otros usuarios. En cuanto a no armar un PR -¿pull request?- separado para cada cambio, fue mi error, entendí tarde y pésimo; pedí ya, y pido nuevamente, mil disculpas -soy bastante nabo para algunas cosas-. 
En cuanto a los cambios que me sugerís, si entiendo bien, proponés "Vamos a aprender que significa de cada uno!". Yo entiendo mejor la redacción que (si no me estoy equivocando) yo propuse, esto es, con el signo de exclamación inicial y sin el "de". Como fuere, si la redacción sin la exclamación inicial les parece mejor, bueno, déjenla..., como uds. dispongan. En todo caso, no sé qué se supone que haga yo ahora.

2022-07-18 14:34 UTC, JuanVqz commented on files/es/learn/common_questions/pages_sites_servers_and_search_engines/index.html
> +<p><span class="seoSummary">En este artículo se describen varios conceptos referidos a la web: Páginas web, sitios web, servidores web, y motores de búsqueda. Estos términos con frecuencia son confun
Cuando alguien te hace una sugerencia como esta y estas de acuerdo, solo sigue los pasos en las imágenes y aceptaras los cambios.

![image](https://user-images.githubusercontent.com/7331511/179535059-e13bbdc3-d317-4206-808a-d762bda1bb66.png)
![image](https://user-images.githubusercontent.com/7331511/179535207-c54880f5-a400-40b8-95e6-ffb52cc1d15c.png)

2022-07-18 15:53 UTC, Graywolf9 commented on files/es/learn/common_questions/pages_sites_servers_and_search_engines/index.html
> +<p>Como cualquier área de conocimiento, la web viene con un montón de jerga. No te preocupes, no te abrumaremos con todo esto (tenemos un glosario por si tienes curiosidad). Sin embargo, hay un unos
Cambios del PR #6932 con las sugerencias de @marcelozarate

2022-07-18 16:00 UTC, Graywolf9 commented on files/es/learn/common_questions/pages_sites_servers_and_search_engines/index.html
> + <dd>Un servicio web que sirve para encontrar páginas web; es el caso de Google, Bing, Yahoo o DuckDuckGo. Normalmente se accede a los motores de búsqueda a través de un navegador web (por ejemplo, s
Cambios del PR #6935 con las sugerencias de @marcelozarate en https://github.com/mdn/translated-content/pull/6935#pullrequestreview-1041661935

> Te dejo unas sugerencias para ser más fiel al contenido original.

2022-07-18 16:22 UTC, Graywolf9 commented
Hola! @55TTKKSS espero estés mu bien

He unido todos los PRs relacionados al mismo archivo para un mejor control de los cambios y observaciones.

Juan ha dejado arriba algunas capturas de como puedes aceptar las sugerencias e incorporarlas a los cambios a aplicar una vez estés de acuerdo con los mismos, en caso de no puedes preguntar y alguno te dará el motivo de la observación.

Te invitamos a que en futuros aportes hacer el PR hasta tener todos tus cambios o hacerlos gradualmente pero sobre el mismo PR (Pull Request) agregando commits al mismo.

Cualquier duda o comentario, no dudes en preguntar.

Muchas gracias de nuevo por tus aportes

2022-07-18 20:42 UTC, 55TTKKSS commented on files/es/learn/common_questions/pages_sites_servers_and_search_engines/index.html
> +<p><span class="seoSummary">En este artículo se describen varios conceptos referidos a la web: Páginas web, sitios web, servidores web, y motores de búsqueda. Estos términos con frecuencia son confun
@JuanVqz, mil gracias por enseñarme! Ok, dejo sentado, falseando la expresión de los gobernantes españoles en América, que "acato y obedezco, pero bajo protesta", jajaj, porque no estoy de acuerdo con la redacción propuesta, y sin embargo, no soy quien para discutirles lo que uds. propongan hacer con el texto. ;-)

2022-07-22 17:34 UTC, marcelozarate commented on files/es/learn/common_questions/pages_sites_servers_and_search_engines/index.html
> +<p><span class="seoSummary">En este artículo se describen varios conceptos referidos a la web: Páginas web, sitios web, servidores web, y motores de búsqueda. Estos términos con frecuencia son confun
> @JuanVqz, mil gracias por enseñarme! Ok, dejo sentado, falseando la expresión de los gobernantes españoles en América, que "acato y obedezco, pero bajo protesta", jajaj, porque no estoy de acuerdo con la redacción propuesta, y sin embargo, no soy quien para discutirles lo que uds. propongan hacer con el texto. ;-)

Quizás no supiste interpretar, pero te estoy sugiriendo la forma que te suena mejor, lo que está en verde es la sugerencia (como quedaría) y lo que está en rojo es como está actualmente (o los cambios propuestos iniciales)

2022-07-22 18:11 UTC, JuanVqz commented on files/es/learn/common_questions/pages_sites_servers_and_search_engines/index.html
> +<p><span class="seoSummary">En este artículo se describen varios conceptos referidos a la web: Páginas web, sitios web, servidores web, y motores de búsqueda. Estos términos con frecuencia son confun
Hola @55TTKKSS! @marcelozarate no esta imponiendo solo fue una sugerencia, en MDN creemos en la buena voluntad de los contribuyentes, estoy de acuerdo con las sugerencias de Marcelo. haré commit y trataré de finalizar este PR.
Gracias a ambos por contribuir.

2022-07-26 11:02 UTC, merged