ScriptProcessorNode の記事を更新
mdn/translated-content pull request #6966
Opened 2022-07-18 15:51 UTC by mfuji09

#3895

2022-07-25 13:48 UTC, potappo requested changes
マークダウンのミスを修正していますので、確認をお願いします。

2022-07-25 13:48 UTC, potappo commented on files/ja/web/api/scriptprocessornode/index.md
> +  - : ScriptProcessorNode` の入力バッファーが処理可能な状態になったときに発行されます。
```suggestion
  - : `ScriptProcessorNode` の入力バッファーが処理可能な状態になったときに発行されます。
```

2022-07-25 15:06 UTC, mfuji09 commented on files/ja/web/api/scriptprocessornode/index.md
> +  - : ScriptProcessorNode` の入力バッファーが処理可能な状態になったときに発行されます。
ありがとうございます！

2022-07-26 13:24 UTC, potappo approved these changes

2022-07-26 13:24 UTC, merged