Work in #4618 | Add: tostring section
mdn/translated-content pull request #6997
Opened 2022-07-19 19:29 UTC by Jalkhov

Closes #6996

2022-07-19 20:11 UTC, Jalkhov commented on files/es/web/javascript/reference/global_objects/symbol/tostring/index.md
> +- {{jsxref("Object.prototype.toString()")}}
Benditas líneas en blanco
```suggestion
- {{jsxref("Object.prototype.toString()")}}

```

2022-07-20 16:43 UTC, marcelozarate requested changes
¡Excelente @Jalkhov! Una única sugerencia a debatir

2022-07-20 16:43 UTC, marcelozarate commented on files/es/web/javascript/reference/global_objects/symbol/tostring/index.md
> +El objeto {{jsxref("Symbol")}} anula el método `toString` del objeto {{jsxref("Object")}}; no hereda {{jsxref("Object.prototype.toString()")}}. Para los objetos `Symbol`, el método `toString` devuelv
```suggestion
El objeto {{jsxref("Symbol")}} sobreescribe el método `toString` del objeto {{jsxref("Object")}}; no hereda {{jsxref("Object.prototype.toString()")}}. Para los objetos `Symbol`, el método `toString` devuelve una representación de cadena del objeto.
```

anular no me parece lo mismo que overrides, me da una impresión diferente.

2022-07-20 16:48 UTC, Jalkhov commented on files/es/web/javascript/reference/global_objects/symbol/tostring/index.md
> +El objeto {{jsxref("Symbol")}} anula el método `toString` del objeto {{jsxref("Object")}}; no hereda {{jsxref("Object.prototype.toString()")}}. Para los objetos `Symbol`, el método `toString` devuelv
Anular y sobreescribir son sinónimos
![imagen](https://user-images.githubusercontent.com/36505934/180037797-b4ecb92b-7a3a-4668-9ba0-b03084ddbc92.png)
Por lo que terminológicamente vendrían siendo lo mismo, sin embargo, `sobreescribe` ciertamente es un termino mas amigable y explica mejor, pero, no se si te parece, cambiarlo a `reemplaza`, es lo mismo, pero es como que mas elegante jaja

2022-07-20 16:52 UTC, marcelozarate commented on files/es/web/javascript/reference/global_objects/symbol/tostring/index.md
> +El objeto {{jsxref("Symbol")}} anula el método `toString` del objeto {{jsxref("Object")}}; no hereda {{jsxref("Object.prototype.toString()")}}. Para los objetos `Symbol`, el método `toString` devuelv
¡Me gusta reemplazar! no sé de dónde sacas esos sinónimos pero le bajo el pulgar sin dudas, sobrescribir = triturar XD

2022-07-20 16:55 UTC, Jalkhov commented on files/es/web/javascript/reference/global_objects/symbol/tostring/index.md
> +El objeto {{jsxref("Symbol")}} anula el método `toString` del objeto {{jsxref("Object")}}; no hereda {{jsxref("Object.prototype.toString()")}}. Para los objetos `Symbol`, el método `toString` devuelv
Jajaja vale ya hago el commit. Y, si te das cuenta, solo algunas de las primeras palabras están en negrita, imagino que son como las más acordes...aunque destrozar...eeehhh xd

2022-07-20 17:49 UTC, marcelozarate approved these changes
¡EXCELENTE @Jalkhov! Muchas gracias

2022-07-20 17:49 UTC, merged