Update index.html
mdn/translated-content pull request #7077
Opened 2022-07-22 22:59 UTC by 55TTKKSS

2022-07-23 02:34 UTC, Jalkhov commented
Hola @55TTKKSS Gracias por seguir contribuyendo, en el transcurso del día de mañana hago la revisión como debe ser n.n

2022-07-23 18:58 UTC, 55TTKKSS commented
> 

@Jalkhov , estimado, aclaraciones: muchos de los cambios y aclaraciones que propongo, provienen de la página en inglés..., que tenía partes que incluso no estaban en la versión en español; incluso había algún problema con las instrucciones para correr el servidor y el tema de las versiones de Python... (Python2 o Python3), traté de incluir/corregir eso, pero no sé si los cambios propuestos lo logran suficientemente. Pido desde ya disculpas; supongo que para un usuario que no sepa NADA de python, mi propuesta puede llegar a ser un poco -no mucho, pero algo- más clara que el original.

2022-07-23 19:11 UTC, Jalkhov commented
> @Jalkhov , estimado, aclaro algo: muchos de los cambios que propongo, provienen de la página en inglés..., que tenía partes que no estaban en la versión en español; había también algún problema con las instrucciones para correr el servidor y el tema de las versiones de Python... (Python2 o Python3), traté de corregir/agregar eso, pero no sé si los cambios propuestos lo logran suficientemente. Pido desde ya disculpas; supongo que para un usuario que no sepa NADA de python, mi propuesta puede llegar a ser un poco -no mucho, pero algo- más clara que el original.

Hola @55TTKKSS pues sí, hay archivos que están totalmente desactualizados, tanto estructura como contenido, actualmente el objetivo que se busca es hacer básicamente una copia de los archivos en ingles pero traducidos claro, los pasos para eso están en [nuestra guía](https://github.com/mdn/translated-content/tree/main/docs/es), en resumen, se trata de cambiar hasta la extensión del documento de HTML a MARKDOWN, y luego actualizar todo el contenido tomando el mismo de la versión en ingles. Si te interesa actualizar completamente los documentos te invito a que pruebes con el documento de esta PR y aquí vamos aclarando dudas.

2022-08-01 16:39 UTC, Jalkhov commented
Hola @55TTKKSS ¿Cómo va todo por aquí? ¿Pensaste en lo que te dije o te quedas con lo contribuido en este PR?

2022-08-02 05:02 UTC, 55TTKKSS commented
> Hola @55TTKKSS ¿Cómo va todo por aquí? ¿Pensaste en lo que te dije o te quedas con lo contribuido en este PR?

@Jalkhov, estimado, perdón, mil disculpas por la demora... Me enfermé, estoy recuperándome.
Paso a responderte en relación a tu propuesta: 
- Yo no tendría problemas con traducir páginas completas, al menos en lo que se refiere al esfuerzo; el tema es que estoy hasta el cuello de trabajo, y bueno, no tengo tanto tiempo...
- Por eso, precisamente, me es más fácil dar una mano comparendo las páginas que pueda -en castellano y en inglés-, mientras voy estudiando HTML -seguiré con CSJ y Javascript- y ver si encuentro errores o problemas de concordancia; puedo hacer eso con relativa facilidad (de hecho, uso la versión en inglés para repasar, mientras voy leyendo en castellano)...
- Respecto de lo de pasar las páginas a MARKDOWN, bueno: a.- no tengo pensado por el momento estudiar markdown (de hecho, soy tan ignorante que no tenía idea de que tal cosa existiera hasta que me hablaste del tema); y honestamente, no tengo tiempo en este momento para ponerme a estudiarlo... b.- sin embargo, se me ocurre que tal vez, más que "traducir" las páginas en github..., "a mano", y ya que hay una página ya escrita en castellano, ¿no sería más práctico armar un programita -estaba por decir un parser, pero entiendo que técnicamente no se llamaría así, aunque desconozco qué nombre pudiera corresponderle- que tome todo el texto de una página -como está en este momento, digo, el texto que yo vengo tratando de ayudar a editar en github- y lo "convierta" a markdown? Se me ocurre que -por lo que pude ver de MARKDOWN- no sería demasiado difícil hacerlo, y sería mucho más rápido y eficiente. Tal vez, para cuando haya terminado con javascript, me de maña para armarlo, podría ser un lindo proyectito para mí. Veremos. Te comento que se me ocurren formas de programarlo, pero no tengo el conocimiento para trabajar con páginas web, y definitivamente lo que me viene a la cabeza no estaría en javascript, sino muy probablemente en turbo pascal 3.01a (un procesador secuencial de texto), o alguna pavada por el estilo, jajajaja.
En fin, nada, Perdón por no poder ayudar con lo que me sugerís en este momento, pero bueno, el laburo no me permite mucho más de lo que estoy haciendo. Es complejo.

2022-08-02 05:03 UTC, 55TTKKSS commented
Por lo mismo que decía antes, me quedo con lo contribuido en este PR, no puedo hacer mucho más... Mis horarios y yo estamos en guerra, jajaja.

2022-08-02 11:01 UTC, Jalkhov commented
@55TTKKSS Vale, no hay problema, entonces procedo a hacer la revisión.

2022-08-02 11:15 UTC, Jalkhov requested changes

2022-08-02 11:15 UTC, Jalkhov commented on files/es/learn/common_questions/set_up_a_local_testing_server/index.html
> + <li><strong>Cuentan con peticiones asincrónicas</strong>. Algunos navegadores (incluido chrome) no ejecutarán solicitudes asíncronas (consulte <a href="/en-US/docs/Learn/JavaScript/Client-side_web_A
URLs a su versión en español
```suggestion
 <li><strong>Cuentan con peticiones asincrónicas</strong>. Algunos navegadores (incluido chrome) no ejecutarán solicitudes asíncronas (consulte <a href="/es/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data">Obtención de datos desde el servidor</a>) si se ejecuta el ejemplo desde un archivo local. Esto se debe a restricciones de seguridad (para obtener más información sobre la seguridad web, lee <a href="/es/docs/Learn/Server-side/First_steps/Website_security">La seguridad del sitio web</a>).</li>
```

2022-08-02 11:15 UTC, Jalkhov commented on files/es/learn/common_questions/set_up_a_local_testing_server/index.html
> + <li><strong>Incluyen otros archivos</strong>. Los navegadores comunmente tratan a los pedidos para cargar recursos formulados utilizando el esquema <code>file://</code>, como solicitudes de recursos
URL a su versión en español
```suggestion
 <li><strong>Incluyen otros archivos</strong>. Los navegadores comunmente tratan a los pedidos para cargar recursos formulados utilizando el esquema <code>file://</code>, como solicitudes de recursos de origenes cruzados (<em>cross-origin requests</em>). Por ello, si se carga un archivo local que incluye otros archivos locales, puede dispararse un error <a href="/es/docs/Glossary/CORS">CORS</a>.</li>
```

2022-08-02 11:15 UTC, Jalkhov commented on files/es/learn/common_questions/set_up_a_local_testing_server/index.html
> +  </div>
Creo que este espacio puede estar demás.
```suggestion
</div>
```

2022-08-09 21:39 UTC, Graywolf9 commented
> estimado, aclaro algo: muchos de los cambios que propongo, provienen de la página en inglés..., que tenía partes que no estaban en la versión en español; había también algún problema con las instrucciones para correr el servidor y el tema de las versiones de Python... (Python2 o Python3), traté de corregir/agregar eso, pero no sé si los cambios propuestos lo logran suficientemente. Pido desde ya disculpas; supongo que para un usuario que no sepa NADA de python, mi propuesta puede llegar a ser un poco -no mucho, pero algo- más clara que el original.

Hola! @55TTKKSS saludos y muchas gracias por tu tiempo y contribución, nosotros no creamos contenido, solo hacemos la localización de inglés a español por lo que no necesitas conocimientos en programación, solo tomar el código de la versión en inglés y pegarlo en la parte de español para así tener el ejemplo actualizado.

Desde ya muchas gracias de nuevo

2022-08-16 20:11 UTC, Graywolf9 commented
Hola! @55TTKKSS los cambios han entrado en conflicto con otra tarea de en la que se esta convirtiendo el formato `html` en `md`, una disculpa por los inconvenientes y te invitamos a seguir mejorando la web.

Muchas gracias por todo.

Nota: De ahora en adelante hacer cambios a archivos `.md` ya que los `html` pronto dejaran de existir

2022-08-16 20:11 UTC, closed without merging