Add Slugs and sourceCommit metadata
mdn/translated-content pull request #7096
Opened 2022-07-23 20:45 UTC by Jalkhov

Closes #6249

2022-07-23 20:50 UTC, Jalkhov commented
@JuanVqz Noto que hay algunos flaws no críticos, pero hay algunos links rotos, por lo visto el trabajo no ha terminado jaja

2022-07-23 22:51 UTC, Jalkhov commented
Listo, ya las alertas que quedan son en cuanto a paginas que aún no existen.

2022-07-28 21:40 UTC, marcelozarate requested changes
¡Excelente trabajo @Jalkhov! Perdón por la demora en la revisión, algunos pequeños cambios fueron introducidos mientras, no son muchos, pero sería genial si ya los metemos y así ya te sugerí el sha correspondiente. Muchísimas gracias por tu labor.

2022-07-28 21:40 UTC, marcelozarate commented on files/es/web/javascript/reference/global_objects/symbol/tostring/index.md
> +	sourceCommit: cf607d68522cd35ee7670782d3ee3a361eaef2e4
```suggestion
  sourceCommit: cf607d68522cd35ee7670782d3ee3a361eaef2e4
```

2022-07-28 21:40 UTC, marcelozarate commented on files/es/web/javascript/reference/global_objects/symbol/toprimitive/index.md
> +  sourceCommit: 61a8cddbde9257e05c55063985f28ac8d364082a
```suggestion
  sourceCommit: 02024642bdb12940509cb4c7e2e60cbc3d62bf21
```
Por la demora en revisar sucedió que el archivo original cambió ¿puedes añadir los cambios que figuran [aquí](https://github.com/mdn/content/commit/02024642bdb12940509cb4c7e2e60cbc3d62bf21#diff-07fceb7f9ec897377913e40ae39e93c672cff3055f7c75d09c1a3ea7e0a30aae)?

2022-07-28 21:40 UTC, marcelozarate commented on files/es/web/javascript/reference/global_objects/symbol/species/index.md
> +  sourceCommit: e34fbf7f735b68fdcb630432ef68d9ac7672ef88
```suggestion
  sourceCommit: 8bf018f0a39d012a0d98afe3f15e0ed0fb7c8ce5
```

¿puedes añadir estos cambios por favor?
https://github.com/mdn/content/commit/8bf018f0a39d012a0d98afe3f15e0ed0fb7c8ce5#diff-d3de0b8d2599e5758e76347dd5e25242b831eb4fd08753ee6ebf905e9a3d6172

2022-07-28 21:49 UTC, Jalkhov commented
> ¡Excelente trabajo @Jalkhov! Perdón por la demora en la revisión, algunos pequeños cambios fueron introducidos mientras, no son muchos, pero sería genial si ya los metemos y así ya te sugerí el sha correspondiente. Muchísimas gracias por tu labor.

Hola @marcelozarate Gracias por revisar, esto lo hablé con @Graywolf9 y me dijo que no había problema con eso, que se podía hacer más adelante ya que no eran cambios fuertes, en su momento me resultó demasiado trabajo jeje En estos momentos no me da el tiempo, pero si tu quieres hacerlo bienvenido, pero como dijo Alex, se puede dejar tranquilamente para después.

2022-07-29 17:53 UTC, merged