Suggest a french translation for id 195
mdn/translated-content pull request #7109
Opened 2022-07-24 12:19 UTC by ManuSquall

Suggest a french translation for [id 195](https://tristantheb.github.io/history-content/#195).

2022-07-26 08:17 UTC, SphinxKnight commented
Merci pour cette nouvelle contribution @ManuSquall en tout cas 💪

2022-07-26 18:49 UTC, SphinxKnight commented
bon j'ai demandé les avis sur element pour éviter que ça soit juste "mon avis" ^  ^

2022-07-26 20:03 UTC, ManuSquall commented
Super 😊 waiting for it so ! "L'avis" en question n'est pas n'importe lequel aussi 🥳

2022-07-29 18:06 UTC, tristantheb commented
Je ne suis pas contre l'idée du « partitionnement », cependant ce qui ressort le plus sur les sites visitables prenant en charge de l'hébergement de site, ou de la gestion de nom de domaine, c'est « partage » qui ressort le plus souvent 😅

2022-07-29 18:42 UTC, SphinxKnight commented
Ça me va :), allons y avec partage !

2022-07-29 18:44 UTC, SphinxKnight requested changes
mini commentaires revus et corrigés :)

2022-07-30 04:22 UTC, SphinxKnight approved these changes
:partying_face:

2022-07-30 04:27 UTC, merged