broadcastchannel api fr translation
mdn/translated-content pull request #7119
Opened 2022-07-25 06:22 UTC by boliangt

Hello,
This is a simple translation in french of the broadcastchannel api

2022-07-25 17:11 UTC, boliangt commented
Hello @cw118,

I'm sorry, there was missing double-quotes that obviously broked the auto-test.
Still, I'm not sure whether the EmbedLive features would run since i also modified the h1 text content in 
https://github.com/mdn/translated-content/pull/7119/files#diff-7e6665acc1545e76fd3e06bc9373ecad709293df98dd77f5d4893e7147383e8dR152

Thank you for the review

2022-07-25 17:53 UTC, cw118 commented
No worries :) I have started a review and I will complete it as soon as possible. That being said, thank you so much for this substantial contribution :)

2022-07-25 18:27 UTC, boliangt commented on files/fr/web/api/broadcastchannel/message_event/index.md
> +const canal = new BroadcastChannel('example-channel');
this id breaks the second embedded live example, i'll correct it with the translated id for consistency

2022-07-26 05:18 UTC, cw118 requested changes
@boliangt voici une première passe :) J'ai fait une revue un peu "sur le fond" (je ferai peut-être une seconde relecture), vous pouvez utiliser l'onglet "Files changed" pour appliquer les suggestions. N'hésitez pas si besoin d'aide ou de discussion.

Cela dit, merci beaucoup pour tout ce travail :)

2022-07-26 05:18 UTC, cw118 commented on files/fr/web/api/broadcastchannel/postmessage/index.md
> +  - Reference
```suggestion
translation_of: Web/API/BroadcastChannel/postMessage
```

2022-07-26 05:18 UTC, cw118 commented on files/fr/web/api/broadcastchannel/postmessage/index.md
> +Le message est transmis en tant qu'événement ['message'](/fr/docs/Web/API/BroadcastChannel/message_event) ciblant chaque {{domxref("BroadcastChannel")}} lié au canal.
```suggestion
La méthode **`BroadcastChannel.postMessage()`** envoie un message qui peut être de n'importe quel type d'[`Object`](/fr/docs/Web/JavaScript/Reference/Global_Objects/Object) à chaque écouteur de n'importe quel [contexte de navigation](/fr/docs/Glossary/Browsing_context) d'une même [origine](/fr/docs/Glossary/Origin). Le message est transmis en tant qu'évènement ['message'](/fr/docs/Web/API/BroadcastChannel/message_event) ciblant chaque [`BroadcastChannel`](/fr/docs/Web/API/BroadcastChannel) lié au canal.
```

2022-07-26 05:18 UTC, cw118 commented on files/fr/web/api/broadcastchannel/postmessage/index.md
> +## Compatibilité navigateur
```suggestion
## Compatibilité des navigateurs
```

2022-07-26 05:18 UTC, cw118 commented on files/fr/web/api/broadcastchannel/postmessage/index.md
> +- {{domxref("BroadcastChannel")}}, l'interface à laquelle elle se rapporte.
```suggestion
- [`BroadcastChannel`](/fr/docs/Web/API/BroadcastChannel), l'interface à laquelle elle se rapporte.
```

2022-07-26 05:18 UTC, cw118 commented on files/fr/web/api/broadcastchannel/name/index.md
> +## Syntaxe
```suggestion
## Valeurs
```

cf. [cette PR/modification sur la page en-US](https://github.com/mdn/content/pull/18798/commits/c4dc53ae28371c1f833bd698c49c7faf399d145c)

2022-07-26 05:18 UTC, cw118 commented on files/fr/web/api/broadcastchannel/name/index.md
> +```
```suggestion
Une chaîne.
```

cf. [cette PR/modification sur la page en-US](https://github.com/mdn/content/pull/18798/commits/c4dc53ae28371c1f833bd698c49c7faf399d145c)

2022-07-26 05:57 UTC, boliangt commented on files/fr/web/api/broadcast_channel_api/index.md
> +L'**API Broadcast Channel** permet la communication entre {{glossary("browsing context", "contextes de navigation")}} (c'est à dire, _windows_, _tabs_, _frames_, ou _iframes_) et workers d'une même {
Est-ce que le système de _flaws_ détectera les liens morts en cas de changement dans le glossaire ? D'accord, je commit la suggestion

2022-07-26 06:22 UTC, boliangt commented on files/fr/web/api/broadcast_channel_api/index.md
> +Lorsqu'un message est posté, un événement [`message`](/fr/docs/Web/API/BroadcastChannel/message_event) est distribué sur chaque objet {{domxref("BroadcastChannel")}} connecté à ce canal. Une fonction
C'est une éternelle discussion, réforme 90 ou non ? Ok, je mets l'ancienne orthographe, mais il faudrait faire une recherche sur l'ensemble de la documentation pour voir quelle est l'orthographe la plus employée parmi les deux.

2022-07-26 06:23 UTC, boliangt commented on files/fr/web/api/broadcast_channel_api/index.md
> +L'**API Broadcast Channel** permet la communication entre {{glossary("browsing context", "contextes de navigation")}} (c'est à dire, _windows_, _tabs_, _frames_, ou _iframes_) et workers d'une même {
d'ailleurs, je vois beaucoup de balise `<i>`, ne serait-il pas mieux de mettre `<em>` ?

2022-07-26 06:41 UTC, SphinxKnight commented on files/fr/web/api/broadcast_channel_api/index.md
> +L'**API Broadcast Channel** permet la communication entre {{glossary("browsing context", "contextes de navigation")}} (c'est à dire, _windows_, _tabs_, _frames_, ou _iframes_) et workers d'une même {
> Est-ce que le système de _flaws_ détectera les liens morts en cas de changement dans le glossaire ? D'accord, je commit la suggestion

A posteriori oui pour les redirections/changements d'URL, c'est-à-dire que si on édite la page, on devrait avoir un avertissement pour utiliser la nouvelle URL.
Pour les liens complètement morts de MDN, ça apparaît ainsi : 
![image](https://user-images.githubusercontent.com/2413436/180940216-882f3af2-e88e-46b4-95e6-55b832f8d1a7.png)

> d'ailleurs, je vois beaucoup de balises `<i>`, ne serait-il pas mieux de mettre `<em>` ?

Cet élément est sémantiquement plus adapté pour l'utilisation de termes en anglais&nbsp;:
 - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/i#usage_notes
 - https://developer.mozilla.org/fr/docs/Web/HTML/Element/i

2022-07-26 06:42 UTC, SphinxKnight commented
Merci beaucoup @boliangt, c'est une PR conséquente :) Bienvenue !

2022-07-26 10:02 UTC, boliangt commented
Voilà, je pense qu'on est dans les derniers mètres pour cette partie :)

2022-07-26 12:42 UTC, cw118 commented on files/fr/web/api/broadcast_channel_api/index.md
> +Lorsqu'un message est posté, un événement [`message`](/fr/docs/Web/API/BroadcastChannel/message_event) est distribué sur chaque objet {{domxref("BroadcastChannel")}} connecté à ce canal. Une fonction
J'ai oublié de mettre le lien, c'est l'orthographe "préférée" de mozfr (du moins c'est celle qui est indiquée dans le guide stylistique) : https://github.com/mozfr/besogne/wiki/Guide-stylistique-pour-la-traduction#Divers

2022-07-26 13:09 UTC, boliangt commented on files/fr/web/api/broadcast_channel_api/index.md
> +Lorsqu'un message est posté, un événement [`message`](/fr/docs/Web/API/BroadcastChannel/message_event) est distribué sur chaque objet {{domxref("BroadcastChannel")}} connecté à ce canal. Une fonction
Je viens de voir qu'il en restait un dernier

2022-07-26 13:32 UTC, cw118 requested changes
Quelques petites coquilles, on n'est pas loin du merge :)

2022-07-26 13:32 UTC, cw118 commented on files/fr/web/api/broadcastchannel/index.md
> +  - : Ferme l'objet canal, indiquant qu'il n'aura plus aucun nouveau message et lui permettant finalement d'être libéré par le ramasse-miètes.
```suggestion
  - : Ferme l'objet canal, indiquant qu'il n'aura plus aucun nouveau message et lui permettant finalement d'être libéré par le ramasse-miettes.
```

2022-07-26 13:32 UTC, cw118 commented on files/fr/web/api/broadcastchannel/index.md
> +    Également accessible via la propriété `onmessageerror`.
```suggestion
  - : Déclenché lorsqu'un message arrive mais ne peut pas être désérialisé. Également accessible via la propriété `onmessageerror`.
```

2022-07-26 13:32 UTC, cw118 commented on files/fr/web/api/broadcastchannel/messageerror_event/index.md
> +L'évènement `messageerror` est déclenché sur un objet [`BroadcastChannel`](/fr/docs/Web/API/BroadcastChannel) lorsqu'un message qui n'a pas pu être déserialisé arrive dans le canal.
```suggestion
L'évènement `messageerror` est déclenché sur un objet [`BroadcastChannel`](/fr/docs/Web/API/BroadcastChannel) lorsqu'un message qui n'a pas pu être désérialisé arrive dans le canal.
```

2022-07-26 13:32 UTC, cw118 commented on files/fr/web/api/broadcastchannel/postmessage/index.md
> +La méthode **`BroadcastChannel.postMessage()`** envoie un message qui peut être de n'importe quel type d'[`Object`](/fr/docs/Web/JavaScript/Reference/Global_Objects/Object) à chaque écouteur de n'imp
```suggestion
La méthode **`BroadcastChannel.postMessage()`** envoie un message qui peut être de n'importe quel type d'[`Object`](/fr/docs/Web/JavaScript/Reference/Global_Objects/Object) à chaque écouteur de n'importe quel [contexte de navigation](/fr/docs/Glossary/Browsing_context) d'une même [origine](/fr/docs/Glossary/Origin). Le message est transmis en tant qu'évènement [`message`](/fr/docs/Web/API/BroadcastChannel/message_event) ciblant chaque [`BroadcastChannel`](/fr/docs/Web/API/BroadcastChannel) lié au canal.
```

2022-07-26 13:32 UTC, cw118 commented on files/fr/web/api/broadcastchannel/postmessage/index.md
> +    Cela signifie que vous pouvez passer un large spectre de type de données de manière sûre à la fenêtre de destination sans avoir à réaliser le traitement de sérialisation par vous-même.
```suggestion
  - : Données à envoyer à la fenêtre. Les données sont sérialisées en utilisant l'[algorithme de clonage de structure](/fr/docs/Web/API/Web_Workers_API/Structured_clone_algorithm). Cela signifie que vous pouvez passer un large spectre de type de données de manière sûre à la fenêtre de destination sans avoir à réaliser le traitement de sérialisation par vous-même.
```

2022-07-26 14:00 UTC, cw118 approved these changes
Merci beaucoup @boliangt pour cet excellent travail !

2022-07-26 14:00 UTC, merged

2022-07-26 14:48 UTC, SphinxKnight commented
@cw118 veux-tu qu'on fasse une autre PR pour rajouter la clé `l10n/sourceCommit` ? (rien d'urgent/grave)

@boliangt si besoin, pour info/partage là-dessus histoire que ce soit un peu compréhensible https://github.com/mdn/mdn-community/discussions/129

2022-07-26 14:57 UTC, cw118 commented
@SphinxKnight zut je l'ai oubliée :/ une PR serait super oui 👍