#618 Glossary/Block のHTML ファイルを MD ファイルに変換
mdn/translated-content pull request #7129
Opened 2022-07-25 17:26 UTC by chie04121

下記対象ページのhtmlファイルをmd形式のファイル内容に変換しました。

対象ページ
https://developer.mozilla.org/ja/docs/Glossary/Block
https://developer.mozilla.org/ja/docs/Glossary/Block/CSS
https://developer.mozilla.org/ja/docs/Glossary/Block/Scripting

markdown形式のルビの記載方法が分からなかったので、そのままの記載にしています。
表示上は問題なかったです。
![image](https://user-images.githubusercontent.com/51228859/180837726-5be41f03-43b8-413a-87a2-57e2958b0c89.png)

2022-07-26 17:20 UTC, mfuji09 requested changes
指摘箇所の修正をお願いします。
また、英語版（原文）と照らし合わせて、最新の状態を反映してくださるようお願いします。
（単に md に変換しただけだと、英語版の変更が追跡しにくくなるためです。）

2022-07-26 17:20 UTC, mfuji09 commented on files/ja/glossary/block/css/index.md
> +ウェブページにおいて<ruby> **ブロック** <rp> (</rp><rt>block</rt><rp>) </rp></ruby>は、新しい行、つまり、横書きでは前の要素の下に、次の要素の上に現れる {{glossary("HTML")}} {{glossary("element", "要素")}}です (よく*ブロックレベル要素*として知られています)。例えば、 {{htmleleme
ruby 関係の要素については、単に削除してください。
```suggestion
ウェブページにおいて **ブロック** (block) は、新しい行、つまり、横書きでは前の要素の下に、次の要素の上に現れる {{glossary("HTML")}} {{glossary("element", "要素")}}です (よく*ブロックレベル要素*として知られています)。例えば、 {{htmlelement("p")}} は既定ではブロックレベル要素であり、それに対して {{htmlelement("a")}} は*インライン要素*です。 — HTML ソース内で複数のリンクを互いに隣に置くことができ、出力時には互いに同じ行に表示されます。
```

2022-07-26 17:20 UTC, mfuji09 commented on files/ja/glossary/block/scripting/index.md
> +I{{glossary("JavaScript")}} では、ブロックは、中括弧（ "`{}`"）で囲まれた関連する{{glossary("statement","文")}}のコレクションです。 たとえば、{{jsxref("Statements/if...else","if (条件)")}} ブロックの後に文のブロックを置くことができます。これは、条件が真であればインタープリタがブロック内のコ
余計な文字があります。また、末尾が -er の英単語の最後は長音を使用してください。
```suggestion
{{glossary("JavaScript")}} では、ブロックは、中括弧（ "`{}`"）で囲まれた関連する{{glossary("statement","文")}}のコレクションです。 たとえば、{{jsxref("Statements/if...else","if (条件)")}} ブロックの後に文のブロックを置くことができます。これは、条件が真であればインタープリターがブロック内のコードを実行する必要があることを示し、条件が偽の場合はブロック全体をスキップします。
```

2022-08-10 11:18 UTC, mfuji09 commented
@chie04121 さん
本件、レビューから2週間ほど経っていますが、まだ修正されていません。
このまま継続されますか？

2022-08-16 11:43 UTC, mfuji09 commented
競合がどうしても解決できなかったため、 #7717 で PR を作り直しました。

2022-08-16 11:43 UTC, closed without merging

2022-08-27 01:33 UTC, chie04121 commented
連絡が滞り、申し訳ありませんでした。
PRクローズありがとうございます。