增加章節「Set up your application」的繁體中文翻譯。
mdn/translated-content pull request #713
Opened 2021-04-30 23:10 UTC by indianazhao

如題，增加章節「Set up your application」的繁體中文翻譯。

2021-04-30 23:47 UTC, leochen0818 requested changes

2021-04-30 23:47 UTC, leochen0818 commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +<p>這個 <code>ng new</code> 命令在你的桌面建立了一個最簡單的初始 Angular 應用。指令後面接著的 <code>--routing</code> 和 <code>--style</code> 幾個參數，定義了如何處理應用的導覽 (路由) 與樣式。這個較學描述了更多有關這個功能的細節。</p>
這個「教」學

2021-04-30 23:59 UTC, indianazhao commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +<p>這個 <code>ng new</code> 命令在你的桌面建立了一個最簡單的初始 Angular 應用。指令後面接著的 <code>--routing</code> 和 <code>--style</code> 幾個參數，定義了如何處理應用的導覽 (路由) 與樣式。這個較學描述了更多有關這個功能的細節。</p>
謝謝！

2021-05-02 15:47 UTC, tonny0531 commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +<p>使用 <code>cd</code> 命令進入你最新的專案：</p>
這邊的 **命令** 改為 **指令** 可能會比較好
跟前後文比較相符

2021-05-02 15:57 UTC, t7yang requested changes

2021-05-02 15:57 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +<p>這個 <code>ng new</code> 命令在你的桌面建立了一個最簡單的初始 Angular 應用。指令後面接著的 <code>--routing</code> 和 <code>--style</code> 幾個參數，定義了如何處理應用的導覽 (路由) 與樣式。這個教學描述了更多有關這個功能的細節。</p>
> 導覽 (路由) 與

請用中文夾注號

2021-05-02 15:57 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +<p>使用 <code>cd</code> 命令進入你最新的專案：</p>
文中有些指令有一些用命令，更多的用命令，所以請統一用語。

2021-05-03 03:31 UTC, t7yang requested changes

2021-05-03 03:31 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +<p>你可以在終端機裡透過使用 Angular 命令列介面 (CLI) 來產生、建置、測試和佈署 Angular 應用。請在終端機裡執行以下指令來安裝 Angular 命令列介面：</p>
> 介面 (CLI) 來產生

請使用正確的中文夾注號、中英文交界請使用半形空格修飾（含標點符號）。

2021-05-03 03:31 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +<p>Angular 命令列介面的指令全都是以 <code>ng</code> 開頭，後面接著你想要 CLI 執行的指令。進入桌面資料夾裡，使用 <code>ng new</code> 指令來建立一個名為 <code>todo</code> 的新應用：</p>
> 想要 CLI 執行的指令

翻譯錯誤，應：想要執行的 CLI 指令

2021-05-03 03:31 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +<p>這個 <code>ng new</code> 指令在你的桌面建立了一個最簡單的初始 Angular 應用。指令後面接著的 <code>--routing</code> 和 <code>--style</code> 幾個參數，定義了如何處理應用的導覽（路由）與樣式。這個教學描述了更多有關這個功能的細節。</p>
> 指令後面接著的 <code>--routing</code> 和 <code>--style</code> 幾個參數，定義了如何處理應用的導覽（路由）與樣式。

指令後面接著的 <code>--routing</code> 和 <code>--style</code> 參數，用於定義應用程式如何處理導覽及樣式。

不要照搬英文的倒裝結構，這會讓中文句子變得不通順。

2021-05-03 03:31 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +<p>如果提示出現強制執行更嚴格的類型檢查，你可以選擇「是」。</p>
如果出現是否啟用強制型別檢查的提示。

一樣，不要跟著照搬英文的被動語態。

2021-05-03 03:31 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +<p>使用 <code>cd</code> 指令進入你最新的專案：</p>
進入你新建的專案：

2021-05-03 03:31 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +<p>當命令列介面提示你相關分析時，請回答 <code>no</code>。</p>
當命令列提示是否共享你的專案資料時

2021-05-03 03:31 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +<p>打開瀏覽器，輸入網址 <a href="http://localhost:4200/">http://localhost:4200/</a> 查看你新的入門應用。如果你對原始檔案作任何修改，應用都會自動重新整理。</p>
在瀏覽器開啟 <a href="http://localhost:4200/">http://localhost:4200/</a> 來檢視你的新建的應用程式。應用程式會即時重新整理以便反應你對原始碼的異動。

2021-05-03 03:31 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +<p>當 <code>ng serve</code> 正在執行，你可能需要開啟第二個終端機分頁或視窗來執行指令。任何時間點想要停止應用程式，請在終端機輸入 <code>Ctrl+c</code>。</p>
當 <code>ng serve</code> 正在執行時
或
當 <code>ng serve</code> 正在執行中

2021-05-04 00:17 UTC, t7yang approved these changes

2021-05-04 00:21 UTC, merged