convert to markdown for absolute position for zh-CN
mdn/translated-content pull request #7137
Opened 2022-07-26 09:24 UTC by awxiaoxian2020

fixes #4940.
not check other contents.

2022-07-26 11:50 UTC, yin1999 requested changes

2022-07-26 11:50 UTC, yin1999 commented on files/zh-cn/learn/css/css_layout/positioning/index.md
> +首先，围绕元素内容添加任何内边距、边界和外边距来布置单个元素盒子——这就是 [盒模型](/zh-CN/docs/Learn/CSS/Building_blocks/The_box_model) ，我们前面看过。默认情况下，块级元素的内容宽度是其父元素的宽度的 100％，并且与其内容一样高。内联元素高宽与他们的内容高宽一样。您不能对内联元素设置宽度或高度——它们只是位于块级元素的内容中。 如果要以
```suggestion
首先，围绕元素内容添加任何内边距、边界和外边距来布置单个元素盒子——这就是[盒模型](/zh-CN/docs/Learn/CSS/Building_blocks/The_box_model) ，我们前面看过。默认情况下，块级元素的内容宽度是其父元素的宽度的 100％，并且与其内容一样高。内联元素高宽与他们的内容高宽一样。您不能对内联元素设置宽度或高度——它们只是位于块级元素的内容中。 如果要以这种方式控制内联元素的大小，则需要将其设置为类似块级元素 `display: block;`。
```

2022-07-26 11:50 UTC, yin1999 commented on files/zh-cn/learn/css/css_layout/positioning/index.md
> +这只是解释了单个元素，但是元素相互之间如何交互呢？ **正常的布局流**（在布局介绍文章中提到）是将元素放置在浏览器视口内的系统。默认情况下，块级元素在视口中垂直布局——每个都将显示在上一个元素下面的新行上，并且它们的外边距将分隔开它们。
```suggestion
这只是解释了单个元素，但是元素相互之间如何交互呢？**正常的布局流**（在布局介绍文章中提到）是将元素放置在浏览器视口内的系统。默认情况下，块级元素在视口中垂直布局——每个都将显示在上一个元素下面的新行上，并且它们的外边距将分隔开它们。
```

2022-07-26 11:50 UTC, yin1999 commented on files/zh-cn/learn/css/css_layout/positioning/index.md
> +如果可能，我们希望您在本地计算机上跟随练习 — 从 GitHub 仓库下载一个[`0_basic-flow.html`](https://mdn.github.io/learning-area/css/css-layout/positioning/0_basic-flow.html) ([源代码](https://github.com/mdn/learning-area/blob/master/
```suggestion
如果可能，我们希望您在本地计算机上跟随练习——从 GitHub 仓库下载一个 [`0_basic-flow.html`](https://mdn.github.io/learning-area/css/css-layout/positioning/0_basic-flow.html) ([源代码](https://github.com/mdn/learning-area/blob/master/css/css-layout/positioning/1_static-positioning.html)) 然后用它作为我们的起步点。
```

2022-07-26 11:50 UTC, yin1999 commented on files/zh-cn/learn/css/css_layout/positioning/index.md
> +    left: 30px;
````suggestion
```css
top: 30px;
left: 30px;
```
````

2022-07-26 11:50 UTC, yin1999 commented on files/zh-cn/learn/css/css_layout/positioning/index.md
> +> **备注：**你可以在 [`1_static-positioning.html`](https://mdn.github.io/learning-area/css/css-layout/positioning/1_static-positioning.html) 查看这个例子 ([see source code](https://github.com/mdn/learning-area/bl
```suggestion
> **备注：** 你可以在 [`1_static-positioning.html`](https://mdn.github.io/learning-area/css/css-layout/positioning/1_static-positioning.html) 查看这个例子 ([see source code](https://github.com/mdn/learning-area/blob/master/css/css-layout/positioning/1_static-positioning.html))。
```

2022-07-26 11:50 UTC, yin1999 commented on files/zh-cn/learn/css/css_layout/positioning/index.md
> +### 介绍 top, bottom, left, right
```suggestion
### 介绍 top、bottom、left 和 right
```

2022-07-26 11:50 UTC, yin1999 commented on files/zh-cn/learn/css/css_layout/positioning/index.md
> +{{ EmbedLiveSample('Introducing_top_bottom_left_and_right', '100%', 500) }}
```suggestion
{{ EmbedLiveSample('介绍 top、bottom、left 和 right', '100%', 500) }}
```

2022-07-26 11:50 UTC, yin1999 commented on files/zh-cn/learn/css/css_layout/positioning/index.md
> +    position: absolute;
````suggestion
```css
position: absolute;
```
````

2022-07-26 11:50 UTC, yin1999 commented on files/zh-cn/learn/css/css_layout/positioning/index.md
> +{{ EmbedLiveSample('Absolute_positioning', '100%', 450) }}
```suggestion
{{ EmbedLiveSample('绝对定位', '100%', 450) }}
```

2022-07-26 11:50 UTC, yin1999 commented on files/zh-cn/learn/css/css_layout/positioning/index.md
> +> **备注：**如果需要，您可以使用{{cssxref("top")}}，{{cssxref("bottom")}}，{{cssxref("left")}}和{{cssxref("right")}} 调整元素大小。尝试设置 `top: 0; bottom: 0; left: 0; right: 0;` 和 `margin: 0;` 对你定位的元素，看看会发生什么！之后再回来
```suggestion
> **备注：** 如果需要，您可以使用 {{cssxref("top")}}，{{cssxref("bottom")}}、{{cssxref("left")}} 和 {{cssxref("right")}} 调整元素大小。尝试设置 `top: 0; bottom: 0; left: 0; right: 0;` 和 `margin: 0;` 对你定位的元素，看看会发生什么！之后再回来
```

2022-07-26 11:50 UTC, yin1999 commented on files/zh-cn/learn/css/css_layout/positioning/index.md
> +    position: relative;
````suggestion
```css
position: relative;
```
````

2022-07-26 11:50 UTC, yin1999 commented on files/zh-cn/learn/css/css_layout/positioning/index.md
> +{{ EmbedLiveSample('Positioning_contexts', '100%', 420) }}
```suggestion
{{ EmbedLiveSample('定位上下文', '100%', 420) }}
```

2022-07-26 11:50 UTC, yin1999 commented on files/zh-cn/learn/css/css_layout/positioning/index.md
> +```html
请注意与HTML文件的对应关系，需要加上 hidden

````suggestion
```html hidden
````

2022-07-26 11:50 UTC, yin1999 commented on files/zh-cn/learn/css/css_layout/positioning/index.md
> +```css
同样的，使用 `<div class="hidden">` 包裹的区域内的代码块都需要加上 `hidden`，请全文检查

2022-07-27 02:25 UTC, yin1999 requested changes
考虑按英文版本增加标题和修改示例代码块

2022-07-27 02:25 UTC, yin1999 commented on files/zh-cn/learn/css/css_layout/positioning/index.md
> +> **备注：**你可以在 [`7_sticky-positioning.html`](https://mdn.github.io/learning-area/css/css-layout/positioning/7_sticky-positioning.html) 查看这个例子 ([see source code](https://github.com/mdn/learning-area/bl
```suggestion
> **备注：** 你可以在 [`7_sticky-positioning.html`](https://mdn.github.io/learning-area/css/css-layout/positioning/7_sticky-positioning.html) 查看这个例子 ([see source code](https://github.com/mdn/learning-area/blob/master/css/css-layout/positioning/7_sticky-positioning.html))。
```

2022-07-27 02:27 UTC, yin1999 commented
如果暂时没有时间修改的话，我就先合并了

2022-07-27 02:29 UTC, awxiaoxian2020 commented
> 如果暂时没有时间修改的话，我就先合并了

先合并吧，这篇文章还有很多需要同步的地方。等合适的时候，我们再一同修改吧。

2022-07-27 02:30 UTC, yin1999 commented
> > 如果暂时没有时间修改的话，我就先合并了
> 
> 先合并吧，这篇文章还有很多需要同步的地方。等合适的时候，我们再一同修改吧。

合并一下 commit

2022-07-27 02:35 UTC, merged