fr-suggest french translation for id: 229
mdn/translated-content pull request #7149
Opened 2022-07-26 20:36 UTC by ManuSquall

Suggest a french translation for [id 229](https://tristantheb.github.io/history-content/#229).

2022-07-27 06:26 UTC, SphinxKnight requested changes
Merci à nouveau @ManuSquall :) quelques légers retours. Je suis plutôt favorable à "rendu" que "affichage" (au sens où l'écran affiche quelque chose et où le navigateur "rend" qqc).
Ceci étant écrit, j'ai gardé affichage pour les liens de "Voir aussi" 🤔 ...

2022-07-27 06:26 UTC, SphinxKnight commented on files/fr/glossary/first_paint/index.md
> +le **premier affichage** (ou <i lang="en">**First Paint**</i> en anglais), qui fait partie de l'[API Paint Timing](/fr/docs/Web/PerformancePaintTiming), est le temps entre la navigation et le moment
```suggestion
Le **premier rendu** (ou <i lang="en">**first paint**</i> en anglais), qui fait partie de l'[API <i lang="en">Paint Timing</i>](/fr/docs/Web/PerformancePaintTiming), correspond au temps entre la navigation et le moment où le navigateur affiche les premiers pixels à l'écran, rendant à l'écran tout ce qui est visuellement différent de ce qui y était présent avant la navigation. Cet indicateur répond à la question  «&nbsp;Est-ce que quelque chose est bien en train de se passer&nbsp;?&nbsp;».
```

2022-07-27 06:26 UTC, SphinxKnight commented on files/fr/glossary/first_paint/index.md
> +- [L'APIPaint Timing](/fr/docs/Web/PerformancePaintTiming) {{deprecated_inline}}
```suggestion
- [Premier affichage significatif (ou <i lang="en">first meaningful paint</i> en anglais)](/fr/docs/Glossary/first_meaningful_paint)
- [Premier affichage de contenu (ou <i lang="en">first contentful paint</i> en anglais)](/fr/docs/Glossary/First_contentful_paint)
- [L'API  <i lang="en">Paint Timing</i>](/fr/docs/Web/PerformancePaintTiming) {{deprecated_inline}}
```

2022-07-27 06:26 UTC, SphinxKnight commented on files/fr/glossary/first_paint/index.md
> +title: Premier affichage
```suggestion
title: Premier rendu
```

2022-07-27 21:29 UTC, ManuSquall commented
Have done some changes! Hope it fits now :-)

2022-07-28 05:13 UTC, SphinxKnight approved these changes

2022-07-28 05:13 UTC, merged