翻譯Angular Getting Started 頁面
mdn/translated-content pull request #719
Opened 2021-05-01 15:02 UTC by vezona

2021-05-02 17:35 UTC, tomyjwu reviewed
翻譯是很主觀的，提出的意見請參考一下

2021-05-02 17:35 UTC, tomyjwu commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +<p>如果你想使用嚴格檢查模式，可以回覆「同意」。</p>
如果被詢問是否使用嚴格型別檢查模式，可以回覆「同意」。

2021-05-02 17:35 UTC, tomyjwu commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +    當你想定義某些特定模組樣式，卻不希望影響到整體程式時，便可使用此檔案進行設定。
當你想定義某些樣式給特定模組用，

2021-05-02 17:35 UTC, tomyjwu commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +    >裡面的html。這個檔案的內容也被視為模板，此模板定義你在瀏覽器中看到的畫面
內含
`<code>AppComponent</code>`
所使用的網頁html , 這個檔案的內容也被視為元件模板(Template)，

2021-05-02 17:35 UTC, tomyjwu commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +    <code>app.component.ts</code>: 又被稱為Class，內含此專案主要頁面的相關邏輯
又被稱為元件類別 (Class)

2021-05-02 17:35 UTC, tomyjwu commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +  >。此結構會將邏輯、畫面、樣式分開，如此一來便能讓程式更易於維護與擴張
```
 <code>AppComponent</code
  >。
```
把原來的文檔結構tag 放在同一行，之後修改時比較不會改壞。
```
 <code>AppComponent</code>。
```

2021-05-02 17:35 UTC, tomyjwu commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +<p>如此一來，你就能在一開始便使用最佳的程式。</p>
如此一來，你就能在一開始便依循最佳的實作慣例

2021-05-02 17:35 UTC, tomyjwu commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +  也能產生<code>app.component.spec.ts</code>的元件測試檔案，但本次教學導覽不會深入探討測試的部分，所以你可以忽略這個資料夾
資料夾 => 檔案

2021-05-02 17:35 UTC, tomyjwu commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +<p>一旦你建立一個元件，CLI就會按照你的命名在目錄中建立此四個資料夾。</p>
資料夾 => 檔案

2021-05-02 17:35 UTC, tomyjwu commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +  </li>
可能有用到prettier之類工具而改到這段。如果沒有翻譯，建議保持原樣。

2021-05-03 03:46 UTC, irvin commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +<p>你會發現 Angular CLI 是一個很實用的建造網站工具</p>
在建造應用程式時，你會發現 Angular CLI 是很實用的工具

中文英文的句法常常是顛倒過來的

2021-05-03 04:17 UTC, t7yang requested changes
請還原排版工具進行的排版調整， MDN 文件原始碼並未使用這樣的排版方式，這會使得 Git 偵測到巨量的異動，讓審核工作變得困難，也會造成其他譯者的無所適從。

2021-05-11 02:03 UTC, vezona commented
> @vezona any updates?

啊抱歉，今晚會更新並調整~感謝!

2021-05-12 14:41 UTC, vezona commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +    <td>建構應用程式並啟動開發伺服器，當檔案變化時重新建構</td>
這段我當時也思考良久，我自己是覺得「建構，啟動應用程式於本機開發伺服器」較為拗口，但不確定我翻的「建構應用程式並啟動開發伺服器」是否有正確表達原文的意思

2021-05-12 14:52 UTC, vezona commented
> @vezona any updates?

感謝協助審稿，已更新審稿後的建議，若有其他建議也請再告知～

2021-05-14 03:34 UTC, t7yang requested changes
翻譯內容仍有許多問題，不逐一點出，還請重新檢視並修正問題。

除了提及的問題外，也請參考新上線的[正體中文翻譯指南](https://github.com/mdn/translated-content/blob/main/docs/zh-tw/translation-guide.md)並重新檢視你的翻譯內容確保符合中文翻譯的指導原則，感謝。

2021-05-14 03:34 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> + </table>
不必要的排版異動

2021-05-14 03:34 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +<p class="summary">現在該看一下 Google 的 Angular框架了，這是另一個你經常會遇到的前端框架。在本文中，我們將會探索 Angular所提供的功能、安裝必備工具、建立範例應用程式，並進一步瞭解 Angular的基本架構。</p>
中英文空格修飾請維持一致的風格。

2021-05-14 03:34 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +<p>想在本地端安裝 Angular，你必須安裝：</p>
很多不必要的排版異動

2021-05-14 03:34 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.html
> +<p>想執行你的 <code>待辦事項</code> 專案, 請使用 <code>ng serve</code>:</p>
> 專案, 請使用

注意使用正確的標點符號

2021-06-07 02:16 UTC, closed without merging