fr-suggest french translation for id: 243
mdn/translated-content pull request #7204
Opened 2022-07-29 22:58 UTC by ManuSquall

Suggest a french translation for [id 243](https://tristantheb.github.io/history-content/#243).

2022-07-30 04:37 UTC, SphinxKnight requested changes
Quelques menues suggestions :)

2022-07-30 04:37 UTC, SphinxKnight commented on files/fr/glossary/gamut/index.md
> +translation_of: Glossary/Gamut
```suggestion
translation_of: Glossary/Gamut
l10n:
  sourceCommit: 841204421a73fe3062521c274632649e8d460bdf
```

2022-07-30 04:37 UTC, SphinxKnight commented on files/fr/glossary/gamut/index.md
> +Un **gamut** ou encore appellé une **gamme de couleurs** est un sous-ensemble de couleurs, représentant généralement les couleurs qu'un écran ou qu'un périphérique d'impression peut afficher.
```suggestion
Un **gamut** ou encore appelé une **gamme de couleurs** est un sous-ensemble de couleurs, représentant généralement les couleurs qu'un écran ou qu'un périphérique d'impression peut afficher.
```

2022-07-30 04:37 UTC, SphinxKnight commented on files/fr/glossary/gamut/index.md
> +Aucun écran ou imprimante ne peut représenter toute la gamme de couleurs qu'un œil humain peut percevoir. Le _gamut_ d'un périphériques représente l'ensemble qu'il prend en charge.
```suggestion
Aucun écran ou imprimante ne peut représenter toute la gamme de couleurs qu'un œil humain peut percevoir. Le _gamut_ d'un périphérique représente l'ensemble qu'il prend en charge.
```

2022-07-30 04:37 UTC, SphinxKnight commented on files/fr/glossary/gamut/index.md
> +Traditionnellement, dans le développement Web, la seule gamme utilisée était _[sRGB](https://fr.wikipedia.org/wiki/SRGB)_ (<i lang="en">Standard Red-Green-Blue</i> en anglais), où chaque couleur est
```suggestion
Traditionnellement, dans le développement web, la seule gamme utilisée était [sRGB](https://fr.wikipedia.org/wiki/SRGB) (pour <i lang="en">Standard Red-Green-Blue</i> en anglais), où chaque couleur est décrite à l'aide de trois octets, un pour chaque couleur primaire. Cependant, les moniteurs à large gamme de couleurs et les imprimantes professionnelles prennent en charge une gamme de couleurs plus large, qui ne peut pas être représentée à l'aide de ce gamut.
```

2022-07-30 04:37 UTC, SphinxKnight commented on files/fr/glossary/gamut/index.md
> +Depuis 2021, les navigateurs ont commencé à fournir des fonctionnalités pour d'autres gamut, comme_[P3](https://fr.wikipedia.org/wiki/DCI-P3)_, largement utilisé dans l'industrie du cinéma, et _[rec2
```suggestion
Depuis 2021, les navigateurs ont commencé à fournir des fonctionnalités pour d'autres gamuts, comme[P3](https://fr.wikipedia.org/wiki/DCI-P3), largement utilisé dans l'industrie du cinéma, et [rec2020](https://fr.wikipedia.org/wiki/Rec._2020).
```

2022-07-30 04:37 UTC, SphinxKnight commented on files/fr/glossary/gamut/index.md
> +- [_Le Gamut_](https://fr.wikipedia.org/wiki/Gamut) sur _Wikipedia_.
```suggestion
- [L'article Wikipédia sur le gamut](https://fr.wikipedia.org/wiki/Gamut)
```

2022-07-30 04:37 UTC, SphinxKnight commented on files/fr/glossary/gamut/index.md
> +Les développeurs peuvent définir différents ensembles de couleurs pour les appareils prenant en charge des gammes plus étendues à l'aide de la [fonctionnalité média](fr/docs/Web/CSS/Media_Queries/Usi
```suggestion
Il est désormais possible de définir différents ensembles de couleurs pour les appareils prenant en charge des gammes plus étendues à l'aide de la [fonctionnalité média](fr/docs/Web/CSS/Media_Queries/Using_media_queries) [`color-gamut`](/fr/docs/Web/CSS/@media/color-gamut). Des couleurs en dehors de la gamme RGB peuvent être définies à l'aide de fonctions CSS spécifiques telles que [`lch()`](/fr/docs/Web/CSS/color_value/lch) pour le système de coordonnées cylindriques LCH ou [`lab()`](/fr/docs/Web/CSS/color_value/lab) pour le système de coordonnées Lab.
```

2022-07-30 04:37 UTC, SphinxKnight commented on files/fr/glossary/gamut/index.md
> +Les développeurs peuvent définir différents ensembles de couleurs pour les appareils prenant en charge des gammes plus étendues à l'aide de la [fonctionnalité média](fr/docs/Web/CSS/Media_Queries/Usi
Pour une formulation épicène.

2022-07-30 04:37 UTC, SphinxKnight commented on files/fr/glossary/gamut/index.md
> +- [_Le Gamut_](https://fr.wikipedia.org/wiki/Gamut) sur _Wikipedia_.
Je ne sais pas pourquoi il y avait `_` pour cette liste…

2022-07-30 04:37 UTC, SphinxKnight commented on files/fr/glossary/gamut/index.md
> +translation_of: Glossary/Gamut
Nouvelle règle ^ ^
Voir https://github.com/orgs/mdn/discussions/129

L'idée est de permettre de savoir à quel état de `mdn/content` la version traduite est associée (pour ensuite tracer les besoins de mise à jour)

2022-08-09 03:52 UTC, cw118 approved these changes
Merci beaucoup pour cette PR @ManuSquall :)

2022-08-09 03:52 UTC, merged