chore: Converted web\api\animationevent\elapsedtime to MD
mdn/translated-content pull request #7230
Opened 2022-07-30 12:52 UTC by nathipg

2022-07-31 02:31 UTC, josielrocha requested changes
Hey Natty!

Obrigado pela contribuição.

Fiz algumas sugestões abaixo, poderia, por favor, dar uma olhada?

😉

2022-07-31 02:31 UTC, josielrocha commented on files/pt-br/web/api/animationevent/elapsedtime/index.md
> +translation_of: Web/API/AnimationEvent/elapsedTime
Adicionando atributos existentes na versão original

```suggestion
---
title: AnimationEvent.elapsedTime
slug: Web/API/AnimationEvent/elapsedTime
page-type: web-api-instance-property
tags:
  - AnimationEvent
  - Animações Web
  - Api
  - CSSOM
  - Propriedade
  - Referência
browser-compat: api.AnimationEvent.elapsedTime
translation_of: Web/API/AnimationEvent/elapsedTime
```

2022-07-31 02:31 UTC, josielrocha commented on files/pt-br/web/api/animationevent/elapsedtime/index.md
> +
```suggestion

{{APIRef("Web Animations API")}}

```

2022-07-31 02:31 UTC, josielrocha commented on files/pt-br/web/api/animationevent/elapsedtime/index.md
> +
Utilizando a macro para gerar as especificações

```suggestion
## Especificações

{{Specifications}}
```

2022-07-31 02:31 UTC, josielrocha commented on files/pt-br/web/api/animationevent/elapsedtime/index.md
> +## Síntaxe
```suggestion
## Sintaxe
```

2022-07-31 02:31 UTC, josielrocha commented on files/pt-br/web/api/animationevent/elapsedtime/index.md
> +- The {{domxref("AnimationEvent")}} interface it belongs to.
Traduzindo algumas partes do trecho abaixo.

*OBS:* A última linha não foi bem traduzida e mais "adaptada".

```suggestion
- [Usando animações CSS](/pt-BR/docs/CSS/Using_CSS_animations)
- Propriedades e regras de CSS relacionadas à animação: {{cssxref("animation")}}, {{cssxref("animation-delay")}}, {{cssxref("animation-direction")}}, {{cssxref("animation-duration")}}, {{cssxref("animation-fill-mode")}}, {{cssxref("animation-iteration-count")}}, {{cssxref("animation-name")}}, {{cssxref("animation-play-state")}}, {{cssxref("animation-timing-function")}}, {{cssxref("@keyframes")}}
- Esse atributo pertence à interface {{domxref("AnimationEvent")}}.
```

2022-10-07 11:34 UTC, SphinxKnight commented
subsumed by work on https://github.com/mdn/translated-content/issues/7950

2022-10-07 11:34 UTC, closed without merging