Update index.html
mdn/translated-content pull request #7231
Opened 2022-07-30 12:57 UTC by dz85

原来的翻译不够准确会引起歧义。

2022-07-30 13:03 UTC, yin1999 requested changes
请参考 [translation-guide](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md)

2022-07-30 13:23 UTC, dz85 commented
> 请参考 [translation-guide](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md)

啥意思，是有哪里不符合规则了吗？请指教。

2022-07-30 13:25 UTC, yin1999 commented
标点符号，英文中的介词也可以去除

2022-07-30 13:42 UTC, dz85 commented
> 标点符号，英文中的介词也可以去除

标点符号做了调整；关于你说的介词这一点不太理解什么意思：我是意译，而不是直译。

2022-07-31 00:17 UTC, yin1999 requested changes

2022-07-31 00:17 UTC, yin1999 commented on files/zh-cn/web/javascript/closures/index.html
> +<p>我们将一个函数周边环境的状态称为<strong>词法环境</strong>（the <strong>lexical environment</strong>），那么当某个函数与其词法环境的引用捆绑在一起的时候，我们称这个组合为<strong>闭包</strong>（<strong>closure</strong>）。换而言之，闭包让开发者可以从内部函数访问外部函数的作用域。在 JavaSc
因为这一文档是主要描述闭包的，且第一段会作为搜索引擎检索的摘要，应保持尽量的简介明了：他人通过搜索引擎的摘要就能大致明白**什么是闭包**。现有的描述没法突出什么是“闭包”。以下是我的修改建议：

```suggestion
<p><strong>闭包</strong>（closure）是一个函数以及其捆绑的周边环境状态（<strong>lexical environment</strong>，<strong>词法环境</strong>）的引用的组合。换而言之，闭包让开发者可以从内部函数访问外部函数的作用域。在 JavaScript 中，闭包会随着函数的创建而被同时创建。</p>
```

2022-08-03 04:32 UTC, merged