chore: Converted pt-BR/docs/web/api/batterymanager/dischargingtimecha…
mdn/translated-content pull request #7243
Opened 2022-07-30 13:24 UTC by nathipg

…nge_event to MD

2022-08-03 12:00 UTC, josielrocha requested changes
Obrigado pela contribuição @nathipg!!

Fiz algumas sugestões com o objetivo de ajustar alguns _typos_ e também atualizar o conteúdo em relação a versão em inglês

👍🏽

2022-08-03 12:00 UTC, josielrocha commented on files/pt-br/web/api/batterymanager/dischargingtimechange_event/index.md
> +original_slug: Web/API/BatteryManager/ondischargingtimechange
```suggestion
title: 'BatteryManager: dischargingtimechange event'
slug: Web/API/BatteryManager/dischargingtimechange_event
page-type: web-api-event
tags:
  - API
  - Event
  - Reference
browser-compat: api.BatteryManager.dischargingtimechange_event
translation_of: Web/API/BatteryManager/ondischargingtimechange
```

2022-08-03 12:00 UTC, josielrocha commented on files/pt-br/web/api/batterymanager/dischargingtimechange_event/index.md
> +Especifica um _event listener_ para receber eventos {{event("dischargingtimechange")}}. Esses eventos ocorrem quando a propriedade {{domxref("BatteryManager.dischargingTime","dischargingTime")}} (tem
```suggestion
O evento **`dischargingtimechange`** da [API de status da bateria](/pt-BR/docs/Web/API/Battery_Status_API) é acionado quando a bateria {{domxref("BatteryManager.dischargingTime","dischargingTime")} } é atualizada.
```

2022-08-03 12:00 UTC, josielrocha commented on files/pt-br/web/api/batterymanager/dischargingtimechange_event/index.md
> +Onde `funcRef` é uma função para ser chamada quando o evento {{event("dischargingtimechange")}} ocorre.
```suggestion
## Sintaxe

Use o nome do evento em métodos como {{domxref("EventTarget.addEventListener", "addEventListener()")}} ou defina uma propriedade do manipulador de eventos.

```js
addEventListener('dischargingtimechange', (event) => { });

ondischargingtimechange = (evento) => { };
```

## Tipo de evento

_Um {{domxref("Evento")}} genérico._

## Exemplo

### Conteúdo HTML

```html
<div id="level">(nível de bateria desconhecido)</div>
<div id="chargingTime">(tempo de carregamento desconhecido)</div>
```

### Conteúdo JavaScript

```js
navigator.getBattery().then((battery) => {
    battery.ondischargingtimechange = () => {
        document.querySelector('#level').textContent = battery.level;
        document.querySelector('#chargingTime').textContent = battery.chargingTime;
    }

});
```

{{ EmbedLiveSample('Exemplo', '100%', 40) }}
```

2022-08-04 00:59 UTC, josielrocha commented on files/pt-br/web/api/batterymanager/dischargingtimechange_event/index.md
> +- {{domxref("Navigator.battery")}}
```suggestion
## Veja também

- {{domxref("BatteryManager")}}
- {{domxref("Navigator.getBattery")}}
```

2022-10-07 11:34 UTC, SphinxKnight commented
subsumed by work on https://github.com/mdn/translated-content/issues/7950

2022-10-07 11:34 UTC, closed without merging