Convert HTML to markdown
mdn/translated-content pull request #7250
Opened 2022-07-30 13:50 UTC by bpires

Convert HTML to markdown | Fix #7221

**File:** `./files/pt-br/web/javascript/guide/indexed_collections/index.html`

---
**md-conversion-problems-report** [fixed manually]

```
# Report from 30/07/2022, 08:12:22
## All unhandled elements
- div.note (3)
- img[alt="Typed arrays in an ArrayBuffer"][src="https://mdn.mozillademos.org/files/8629/typed_arrays.png"][style="height: 278px; width: 666px;"] (1)
## Details per Document
### [/pt-BR/docs/Web/JavaScript/Guide/Indexed_collections](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Indexed_collections)
### Missing conversion rules
- div.note (44:1)
- div.note (87:1)
- div.note (112:1)
- img[alt="Typed arrays in an ArrayBuffer"][src="https://mdn.mozillademos.org/files/8629/typed_arrays.png"][style="height: 278px; width: 666px;"] (439:4)
```

2022-07-31 21:58 UTC, nathipg commented on files/pt-br/web/javascript/guide/indexed_collections/index.md
> +> **Nota :** No código acima, `comprimentoDoArray` deve ser um `Número`. De outra maneira, um array com um único elemento (o valor passado) será criado. Chamar `arr.length` retornará `comprimentoDoAr
```suggestion
> **Note:** No código acima, `comprimentoDoArray` deve ser um `Número`. De outra maneira, um array com um único elemento (o valor passado) será criado. Chamar `arr.length` retornará `comprimentoDoArray`, mas o array na verdade, contem elementos vazios (undefined). Executar um loop {{jsxref("Statements/for...in","for...in")}} no array, não retornará nenhum dos elementos do array.
```

2022-07-31 21:59 UTC, nathipg commented on files/pt-br/web/javascript/guide/indexed_collections/index.md
> +> **Nota :** No código acima, `comprimentoDoArray` deve ser um `Número`. De outra maneira, um array com um único elemento (o valor passado) será criado. Chamar `arr.length` retornará `comprimentoDoAr
Esse ponto de traduzir o Note, é algo que eu também fazia, porque nos .html como pegava o estilo da classe ficava tudo certo, mas nos .md quando isso é traduzido perde aquele estilo de azul e o ícone de info :/
O melhor é deixar em inglês mesmo nesse caso, percebi que o warning também tem esse comportamento.

2022-07-31 22:00 UTC, nathipg commented on files/pt-br/web/javascript/guide/indexed_collections/index.md
> +> **Nota :** se você fornece um valor não inteiro ao operador do array, como no código acima, a propriedade será criada no objeto representando o array, ao invés do elemento do array.
```suggestion
> **Note:** se você fornece um valor não inteiro ao operador do array, como no código acima, a propriedade será criada no objeto representando o array, ao invés do elemento do array.
```

2022-07-31 22:01 UTC, nathipg commented on files/pt-br/web/javascript/guide/indexed_collections/index.md
> +> **Nota :** o operador do array (colchetes) também é usado para acessar as propriedades do array (arrays também são objetos em JavaScript). Por exemplo,
```suggestion
> **Note:** o operador do array (colchetes) também é usado para acessar as propriedades do array (arrays também são objetos em JavaScript). Por exemplo,
```

2022-07-31 22:06 UTC, nathipg commented on files/pt-br/web/javascript/guide/indexed_collections/index.md
> +arr.length = 42;
Esse trecho está dessa forma:

![image](https://user-images.githubusercontent.com/14853904/182047120-af0f579a-720d-44a7-a6eb-a85ba1660bcc.png)

Fazendo com que seja renderizado assim:

![image](https://user-images.githubusercontent.com/14853904/182047132-0f2ff586-825d-4e95-8904-f84da1c1abec.png)

Poderia adicionar os espaços extra dessa forma, por favor?

![image](https://user-images.githubusercontent.com/14853904/182047143-c432e6d0-7c58-4383-9a27-4a621f10a69e.png)

Para ser renderizado assim:

![image](https://user-images.githubusercontent.com/14853904/182047150-41dc3b4f-05b2-41a9-b904-cc6a9a5f8cb4.png)

O conversor automático acabou deletando eles.

2022-07-31 22:13 UTC, nathipg requested changes
Obrigada pela sua contribuição!
Poderia dar uma olhada em alguns pontos que comentei, por favor?

2022-08-03 03:37 UTC, bpires commented on files/pt-br/web/javascript/guide/indexed_collections/index.md
> +> **Nota :** No código acima, `comprimentoDoArray` deve ser um `Número`. De outra maneira, um array com um único elemento (o valor passado) será criado. Chamar `arr.length` retornará `comprimentoDoAr
Mantendo "Nota" considerando a configuração do Yari para translated cards em pt-br

2022-08-03 04:16 UTC, bpires reviewed
Nath, os espaços extras não consegui resolver, porque para mim eles estão lá, e renderizam normalmente, não havendo nada a alterar. 
Por favor confere o que ocorreu e me dá uma luz.

2022-08-03 04:16 UTC, bpires commented on files/pt-br/web/javascript/guide/indexed_collections/index.md
> +arr.length = 42;
Fiquei em dúvida aqui. No meu código aqui no GH mesmo está como se houvessem sido mantidos os espaços extras, vê:

![image](https://user-images.githubusercontent.com/86871991/182522580-40edb7a6-fafa-4a3e-af41-eeba0a168b72.png)

Quando renderizo também está normal, com os comentários alinhados.

Não sei o que aconteceu, você pode verificar novamente?

2022-08-03 04:16 UTC, bpires commented on files/pt-br/web/javascript/guide/indexed_collections/index.md
> +> **Nota :** se você fornece um valor não inteiro ao operador do array, como no código acima, a propriedade será criada no objeto representando o array, ao invés do elemento do array.
Mantendo o formato nota, porém removendo o espaço desnecessário.

```suggestion
> **Nota:** se você fornece um valor não inteiro ao operador do array, como no código acima, a propriedade será criada no objeto representando o array, ao invés do elemento do array.
```

2022-08-08 04:11 UTC, SphinxKnight requested changes
please do not merge this PR while it touches irrelevant documents from other locale's.
if you need help fixing this with Git, please let us know in the commentary, we should be able to assist putting this PR back on track :)

2022-08-08 13:38 UTC, bpires commented
Hi @SphinxKnight, sorry for the inconvenience! I immediately realized something was not right and already asked the localization team for their assistance. We'll solve it shortly and, hopefully, I'll learn something out of it and make sure it won't happen again. Thanks for understanding 😅

2022-08-08 15:09 UTC, closed without merging