Suggest a french translation for id 238
mdn/translated-content pull request #7281
Opened 2022-07-31 21:10 UTC by ManuSquall

Suggest a french translation for [id 238](https://tristantheb.github.io/history-content/#238).

2022-08-01 06:50 UTC, SphinxKnight requested changes
Quelques modifications mineures, le point le plus important étant le terme "boîte" qui est spécifique à CSS pour la traduction de "box".

2022-08-01 06:50 UTC, SphinxKnight commented on files/fr/glossary/fragmentainer/index.md
> +translation_of: Glossary/Fragmentainer
```suggestion
translation_of: Glossary/Fragmentainer
l10n:
  sourceCommit: 541357c50283942128c2f5c0335418bc2b90e751
```

2022-08-01 06:50 UTC, SphinxKnight commented on files/fr/glossary/fragmentainer/index.md
> +Un fragmenteur (ou <i lang="en">fragmentainer</i> en anglais) est défini dans la [spécification de fragmentation CSS](https://www.w3.org/TR/css-break-3/) (en anglais) comme suit :
```suggestion
Un fragmenteur (ou <i lang="en">fragmentainer</i> en anglais) est défini dans la [spécification de fragmentation CSS](https://www.w3.org/TR/css-break-3/) (en anglais) comme suit&nbsp;:
```

2022-08-01 06:50 UTC, SphinxKnight commented on files/fr/glossary/fragmentainer/index.md
> +> Une zone, de la manière d'une zone de page, une zone de colonne ou une région, qui contient une partie (ou la totalité) d'un flux fragmenté. Les fragmenteurs peuvent être prédéfinis ou générés selo
```suggestion
> Une boîte, telle qu'une boîte de page, de colonne ou une région, qui contient une partie (ou la totalité) d'un flux fragmenté. Les fragmenteurs peuvent être prédéfinis ou générés selon les besoins. Lorsqu'un contenu fragmentable déborde d'un fragmenteur dans la dimension de bloc, il se brise dans le conteneur suivant de son contexte de fragmentation à la place.
```

2022-08-01 06:50 UTC, SphinxKnight commented on files/fr/glossary/fragmentainer/index.md
> +Les contextes fragmentés se trouvent dans les médias CSS paginés (ou <i lang="en">CSS Paged Media</i> en anglais), où le fragmenteur serait la boîte qui définit une page. Dans une disposition à plusi
```suggestion
Les contextes fragmentés se trouvent dans les médias CSS paginés (ou <i lang="en">CSS Paged Media</i> en anglais), où le fragmenteur correspond à la boîte qui définit une page. Dans une disposition à plusieurs colonnes, le fragmenteur est la boîte de colonne créée lorsque les colonnes sont définies sur un conteneur à plusieurs colonnes. Dans les régions CSS, chaque région est un fragmenteur.
```

2022-08-01 06:50 UTC, SphinxKnight commented
Merci à nouveau @ManuSquall :D

2022-08-10 14:23 UTC, ManuSquall commented
Apply review suggestions

2022-08-12 15:32 UTC, cw118 approved these changes
Merci à nouveau pour cette traduction @ManuSquall :)

2022-08-12 15:32 UTC, merged