Finished translating the half missing part.
mdn/translated-content pull request #7333
Opened 2022-08-03 09:57 UTC by Blyxyas

2022-08-03 11:03 UTC, marcelozarate requested changes
¡Muchas gracias! @Blyxyas te sugerí unos cambios para poder aprobar el PR y fusionarlo.

En estos momentos estamos trabajando en actualizar la [documentación en Español](https://developer.mozilla.org/es/) con la [versión en inglés](https://developer.mozilla.org/en-US/).

Si deseas seguir apoyando puedes:

Actualizar el contenido con la versión en inglés
Convertir HTML a Markdown (traduciendo)
[Reportar issues](https://github.com/mdn/translated-content/issues/new/choose)
[Revisar issues](https://github.com/mdn/translated-content/issues?q=is%3Aissue+is%3Aopen+label%3Al10n-es)
[Unirte a nuestro equipo](https://chat.mozilla.org/#/room/!cIEBGoIHFpsXNeVUwp:mozilla.org)

Saludos.

2022-08-03 11:03 UTC, marcelozarate commented on files/es/web/http/headers/www-authenticate/index.html
> +<h2 id="See_also">Vea también</h2>
```suggestion
<h2 id="See_also">Véase también</h2>
```
De acuerdo a nuestra guía https://github.com/mdn/translated-content/tree/main/docs/es

en las traducciones recomendadas ponemos así.

2022-08-03 14:10 UTC, JuanVqz commented
@Blyxyas veo que es tu primer contribución en el repositorio, bienvenid@!

2022-08-04 15:07 UTC, marcelozarate approved these changes
¡Gracias por tu aporte @Blyxyas! Puedes unirte a nuestro [chat](https://chat.mozilla.org/#/room/#mdn-l10n-es:mozilla.org) si deseas seguir colaborando.

2022-08-04 15:08 UTC, merged