Sourcebuffer
mdn/translated-content pull request #7347
Opened 2022-08-03 22:35 UTC by Jack-Zhang-1314

In localized document, If it is a document that has not been translated directly, it is recommended to use the latest English document directly and do not convert it.

2022-08-03 23:44 UTC, yin1999 requested changes

2022-08-03 23:44 UTC, yin1999 commented on files/zh-cn/web/api/sourcebuffer/appendbuffer/index.md
> +browser-compat: api.SourceBuffer.appendBuffer
please remove `BCD` metadata

2022-08-04 00:06 UTC, yin1999 reviewed
please fix and squash commit (except the first rename commit)

2022-08-04 00:06 UTC, yin1999 commented on files/zh-cn/web/api/sourcebuffer/mode/index.md
> +如果 mode 初始值为 sequence 想要改为 segments 则会引发错误，必须以`sequence`模式维护现有段顺序。但是，可以将值从`segments 模式`改为`sequence 模式`。它意味着播放顺序将被固定，并会生成新的时间戳。
```suggestion
如果 mode 初始值为 sequence 想要改为 segments 则会引发错误，必须以 `sequence` 模式维护现有段顺序。但是，可以将值从 `segments` 模式改为`sequence` 模式。它意味着播放顺序将被固定，并会生成新的时间戳。
```

2022-08-04 00:32 UTC, Jack-Zhang-1314 commented
I used `squash`, but it becomes 6 commit now

2022-08-04 07:21 UTC, yin1999 commented
next time, please pull before making locale changes (for changes have been made in GitHub)

2022-08-04 07:21 UTC, yin1999 approved these changes

2022-08-04 07:22 UTC, merged

2022-08-04 19:59 UTC, Jack-Zhang-1314 commented
> next time, please pull before making locale changes (for changes have been made in GitHub)

* I tried it yesterday, I don't know if it's right

1. 需要回退的范围

```
git rebase -i 
# 将除了最新的提交的 pick 都改成 squash(s)
pick 4646e9c fw3
pick a0868c5 fw4
pick 911da7f fw5
pick 5c2e562 fw6

# Rebase 4073aa6..5c2e562 onto 4073aa6 (4 commands)
#
# Commands:

>>>>>>>>>>>>>>>>
pick 4646e9c fw3
s a0868c5 fw4
s 911da7f fw5
s 5c2e562 fw6
```

2. 显示所有的提交信息,有需要的可以更改

```bash
# This is the 1st commit message:

fw3

# This is the commit message #2:

fw4

# This is the commit message #3:

fw5

# This is the commit message #4:

fw6
```

3. 压缩这些提交信息

```bash
((d466032...)),这时候会进入到一个检出的提交中,这时候需要合并到主分支
git checkout -b dev
git checkout main
git rebase dev
git branch -D dev
```

> Or using `git rebase -i HEAD~n` directly, and the commit will not be checked out.

2022-08-05 00:54 UTC, yin1999 commented
https://backlog.com/git-tutorial/cn/stepup/stepup7_5.html

并不需要这里的第三步：

1. `git rebase -i HEAD~n`
2. 编辑rebase信息
3. 完成 rebase 后，直接 force push

2022-08-05 00:57 UTC, Jack-Zhang-1314 commented
> https://backlog.com/git-tutorial/cn/stepup/stepup7_5.html
> 
> 并不需要这里的第三步：
> 
> 1. `git rebase -i HEAD~n`
> 2. 编辑rebase信息
> 3. 完成 rebase 后，直接 force push

使用 `git rebase -i HEAD~n` 之后, 指针不会出现上面的游离态, 那我差不多明白了