Getting started with Vue (zh-TW translation)
mdn/translated-content pull request #739
Opened 2021-05-03 08:02 UTC by qiiwiiq

翻譯 Getting started with Vue 最後 1/3 頁面

2021-05-03 15:16 UTC, t7yang requested changes
除了提及的問題外，也建議參考新上線的[針對 MDN 翻譯內容的一般指導原則](https://github.com/mdn/translated-content/blob/main/docs/zh-tw/translation-guide.md)

2021-05-03 15:16 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/vue_getting_started/index.html
> +<p><strong>注意</strong>：如果你在使用 CLI 創建專案時有選擇 CSS 前處理器，你可以在 <code>&lt;style&gt;</code> 標籤上添加 <code>lang</code> 屬性，這些內容在建置的時候將會被 Webpack 處理。舉例來說，<code>&lt;style lang="scss"&gt;</code> 允許你在樣式資訊中使用 SCSS 語法
這裡用「預處理器」，前處理器怪怪的。

2021-05-04 02:11 UTC, qiiwiiq commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/vue_getting_started/index.html
> +<p>雖然有些框架鼓勵你把模板、邏輯和樣式的程式碼放在不同的檔案，但是 Vue 卻採取相反的策略。使用<a href="https://vuejs.org/v2/guide/single-file-components.html">單一檔案元件</a>時，Vue 讓你把模板、相關指令碼和 CSS 整合在一起放在以 <code>.vue</code> 結尾的檔案裡。這些檔案會被 JS 的打包工具（
謝謝～已修正(中英文間添加半形空白)

2021-05-04 02:14 UTC, qiiwiiq commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/vue_getting_started/index.html
> +<p>使用 Vue CLI 創建的專案會會產生現成的 <code>.vue</code> 檔案以及 Webpack。看一下我們使用 CLI 創建的專案，在 <code>src</code> 資料夾你會看到你的第一個 <code>.vue</code> 檔案：<code>App.vue</code>。</p>
謝謝～已修正贅字

2021-05-04 02:14 UTC, qiiwiiq commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/vue_getting_started/index.html
> +<p>打開你的 <code>App.vue</code> 檔案 － 你將會看到它由三個部分組成：<code>&lt;template&gt;</code>、<code>&lt;script&gt;</code> 以及 <code>&lt;style&gt;</code>，分別包含了元件的模板、指令碼和樣式資訊。所有的單一檔案元件都是使用這種基本架構。</p>
謝謝～已修正中文破折號

2021-05-04 02:14 UTC, qiiwiiq commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/vue_getting_started/index.html
> +<p><strong>注意</strong>：如果你在使用 CLI 創建專案時有選擇 CSS 前處理器，你可以在 <code>&lt;style&gt;</code> 標籤上添加 <code>lang</code> 屬性，這些內容在建置的時候將會被 Webpack 處理。舉例來說，<code>&lt;style lang="scss"&gt;</code> 允許你在樣式資訊中使用 SCSS 語法
謝謝已改用「預處理器」

2021-05-04 05:51 UTC, t7yang requested changes

2021-05-04 05:51 UTC, t7yang commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/vue_getting_started/index.html
> +    <p>熟悉 <a href="/en-US/docs/Learn/HTML">HTML</a> 、 <a href="/en-US/docs/Learn/CSS">CSS</a> 、以及 <a href="/en-US/docs/Learn/JavaScript">JavaScript</a> 的核心知識，知道如何使用 <a href="/en-US/docs/Learn/Tools_a
> <a href="/en-US/docs/

最後一個需要幫忙，把內部連結改成 /zh-TW 吧，這樣讀者在閱讀時才能導向中文頁面（先不用關心中文頁面不存在的問題）。

2021-05-04 06:13 UTC, t7yang approved these changes

2021-05-04 06:14 UTC, merged

2021-05-04 06:14 UTC, qiiwiiq commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/vue_getting_started/index.html
> +    <p>熟悉 <a href="/en-US/docs/Learn/HTML">HTML</a> 、 <a href="/en-US/docs/Learn/CSS">CSS</a> 、以及 <a href="/en-US/docs/Learn/JavaScript">JavaScript</a> 的核心知識，知道如何使用 <a href="/en-US/docs/Learn/Tools_a
已修正～