[zh-TW]Translate String.prototype.localeCompare()
mdn/translated-content pull request #7466
Opened 2022-08-09 15:19 UTC by shiyou0130011

as the title said, to translate `String.prototype.localeCompare()`

2022-08-09 23:39 UTC, yin1999 requested changes, later dismissed

2022-08-09 23:39 UTC, yin1999 commented on files/zh-tw/web/javascript/reference/global_objects/string/localecompare/index.md
> +translation_of: Web/JavaScript/Reference/Global_Objects/String/localeCompare
see #7412

```suggestion
```

2022-08-09 23:39 UTC, yin1999 commented on files/zh-tw/web/javascript/reference/global_objects/string/localecompare/index.md
> +如果環境中有支援[`Intl.Collator` API](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator)，這個方法實際上是調用 `Intl.Collator` API。
follow https://github.com/mdn/translated-content/blob/main/docs/zh-tw/translation-guide.md#%E7%AB%99%E5%85%A7%E9%80%A3%E7%B5%90%E7%BF%BB%E8%AD%AF

```suggestion
如果環境中有支援[`Intl.Collator` API](/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator)，這個方法實際上是調用 `Intl.Collator` API。
```

2022-08-10 01:14 UTC, yin1999 commented on files/zh-tw/web/javascript/reference/global_objects/string/localecompare/index.md
> +如果環境中有支援[`Intl.Collator` API](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator)，這個方法實際上是調用 `Intl.Collator` API。
There are a lot of links needed to be updated, please follow this one.

2022-08-15 12:27 UTC, irvin requested changes
我覺得這邊的意思應該是說「平台可以自行決定如何比較，但必須在任何 cast 下都維持一致」？ @yin1999 你覺得呢？

2022-08-15 12:27 UTC, irvin commented on files/zh-tw/web/javascript/reference/global_objects/string/localecompare/index.md
> +若環境沒有實現 `Intl.Collator` ，則這兩個參數就會被忽略，其回傳結果完全看該環境是如何實現此方法的。唯一能確定回傳結果的情況是比較的結果相等時。
> making the comparison result returned entirely implementation-dependent — it's only required to be consistent.

其回傳結果完全看該環境如何實現此方法，而唯一的要求是必須維持一致。

2022-08-15 13:16 UTC, yin1999 commented on files/zh-tw/web/javascript/reference/global_objects/string/localecompare/index.md
> +若環境沒有實現 `Intl.Collator` ，則這兩個參數就會被忽略，其回傳結果完全看該環境是如何實現此方法的。唯一能確定回傳結果的情況是比較的結果相等時。
参考规范：

> The actual return values are [implementation-defined](https://tc39.es/ecma262/multipage/overview.html#implementation-defined) to permit encoding additional information in them, but this method, when considered as a method of two arguments, is required to be a [consistent comparator](https://tc39.es/ecma262/multipage/indexed-collections.html#consistent-comparator) defining a total ordering on the set of all Strings. This method is also required to recognize and honour canonical equivalence according to the Unicode Standard, including returning +0𝔽 when comparing distinguishable Strings that are canonically equivalent.

我认为最后一句话的意思应该是指，对于同样的两个字符串，其比较的结果应该始终一致（the same value `V`）

![image](https://user-images.githubusercontent.com/15844309/184641762-75f96abf-c8cb-4373-a2d3-ff141db936cb.png)

2022-08-15 15:59 UTC, irvin commented on files/zh-tw/web/javascript/reference/global_objects/string/localecompare/index.md
> +若環境沒有實現 `Intl.Collator` ，則這兩個參數就會被忽略，其回傳結果完全看該環境是如何實現此方法的。唯一能確定回傳結果的情況是比較的結果相等時。
其回傳結果完全看該環境如何實作，唯一的要求是（對於同樣的字串）比較結果必須始終一致。

2022-08-17 16:24 UTC, irvin requested changes

2022-08-17 16:24 UTC, irvin commented on files/zh-tw/web/javascript/reference/global_objects/string/localecompare/index.md
> +若環境沒有實現 `Intl.Collator` ，則這兩個參數就會被忽略，其回傳結果完全看該環境是如何實現此方法的。唯一能確定回傳結果的情況是比較的結果相等時。
```suggestion
若環境沒有實現 `Intl.Collator` ，則這兩個參數就會被忽略，其回傳結果完全看該環境如何實作，唯一的要求是（對於同樣的字串）比較結果必須始終一致。
```

2022-08-29 17:05 UTC, merged