Path error on #6800 issue
mdn/translated-content pull request #7493
Opened 2022-08-10 05:23 UTC by EnriqueSource

2022-08-10 05:25 UTC, EnriqueSource commented
Hola. Por favor, comprobar los dos flaws que tiene el archivo con dos macros.

2022-08-10 12:20 UTC, Jalkhov requested changes
Hola @EnriqueSource Muchas gracias por tu aporte. Te dejé comentarios. Las flaws que mencionas no implican problema alguno, solo indican que el documento al que apunta la url no existe, pero, mdn redirige automaticamente a su versión en inglés.

2022-08-10 12:20 UTC, Jalkhov commented on files/es/web/css/height/index.md
> +  sourceCommit: abcebf471d56ef12239e2565f26d952e8a8cab2eabcebf471d56ef12239e2565f26d952e8a8cab2e
Se puede usar tranquilamente la versión más corta n.n
```suggestion
  sourceCommit: abcebf471d56ef12239e2565f26d952e8a8cab2e
```

2022-08-10 12:20 UTC, Jalkhov commented on files/es/web/css/height/index.md
> +  {{cssxref("inline-size")}}
Nuestra línea en blanco al final
```suggestion
  {{cssxref("inline-size")}}
  
```

2022-08-10 12:20 UTC, Jalkhov commented on files/es/web/css/height/index.md
> +browser-compat: css.properties.height
Convervamos nuestras slugs
```suggestion
translation_of: Web/CSS/height
original_slug: Web/CSS/height
browser-compat: css.properties.height
```

2022-08-11 19:11 UTC, EnriqueSource commented
Muchas gracias Jalkhov por tu revisión y por tus comentarios. Me los apunto para la siguiente;D .
Todo resuelto.

2022-08-12 10:57 UTC, Jalkhov approved these changes

2022-08-12 10:58 UTC, merged

2022-12-06 16:53 UTC, Graywolf9 commented on files/es/web/css/height/index.md
> +  sourceCommit: abcebf471d56ef12239e2565f26d952e8a8cab2eabcebf471d56ef12239e2565f26d952e8a8cab2e
Muchas gracias por la review @Jalkhov !

En la última reunión acordamos que hasta llegar a un acuerdo para estandarizar esta bien cualquiera de las versiones largas, además de que esta es la arrojada por el script de Juan

2022-12-06 16:54 UTC, Graywolf9 commented on files/es/web/css/height/index.md
> +  {{cssxref("inline-size")}}
Anteriormente se habló de que esto no era más un requerimiento puesto que el linting de mdn las quita automaticamente puesto que esta establecido que no haya lineas al final

2022-12-07 08:59 UTC, EnriqueSource commented on files/es/web/css/height/index.md
> +  {{cssxref("inline-size")}}
Si bien es cierto que es una buena práctica dejar la línea en blanco, es bueno saber que no es obligatorio. Gracias