Update index.md
mdn/translated-content pull request #7650
Opened 2022-08-14 03:12 UTC by GrontyLion

1. 此处red-inner与red-outer背景颜色一样，导致不易看出red-inner与red-outer之间存在的上下边距，故将red-inner修改为orange-inner。
2. 此处由小标题可知，应该是为了演示BFC可以避免外边距折叠的现象，但是这里用的例子却是演示了BFC隔绝内部元素向BFC外部传递margin，与标题描述不符，故根据标题意思，为其在red-outer中添加一个margin-top用来演示BFC可以避免外边距折叠的现象。

2022-08-14 03:44 UTC, yin1999 requested changes
请参考文档：https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing

这一示例展示的避免外边距重叠的情况是，两个相邻的元素之间的外边距重叠（也就是两个div的margin）。为避免重叠，在后一个div外套了一层outer div（其没有margin）

2022-08-14 03:47 UTC, yin1999 commented
对于这一示例，我认为较好的做法是为内层div添加一个颜色：

```css
.red-inner {
  background: yellow;
}
```

2022-08-14 03:48 UTC, yin1999 commented
同时，由于本地化文档仅是对英文文档的同步翻译，所以，若要做出这一修改，请先修改 <https://developer.mozilla.org/en-US/docs/web/guide/css/block_formatting_context#margin_collapsing>

2022-08-14 03:50 UTC, GrontyLion commented
对的，

> 请参考文档：https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing
> 
> 这一示例展示的避免外边距重叠的情况是，两个相邻的元素之间的外边距重叠（也就是两个div的margin）。为避免重叠，在后一个div外套了一层outer div（其没有margin）

谢谢提醒，是我犯错误了。

2022-09-23 05:19 UTC, yin1999 commented
Closing in favour of mdn/content#21003

2022-09-23 05:19 UTC, closed without merging