[ko/update] web/javascript/reference/operators/await
mdn/translated-content pull request #7654
Opened 2022-08-14 07:39 UTC by hochan222

@ojj1123 님 안녕하세요.

충돌로인해 불편함을 덜어드리고자 PR을 생성했습니다. await에 대한 내용은 해당 PR로 반영해도 괜찮을까요? 

불편을 드려서 죄송합니다. (CC: @yujo11 ) 

이전 PR: https://github.com/mdn/translated-content/pull/7497

---
아래 `await` 페이지에 업데이트 PR입니다.
원문: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await

아래 부분 해석이 약간 어색하다고 느껴져서 검토 부탁드려요. `Description`부분 아래쪽에 있는 내용입니다.
- en-US 원문
```
...
An `await` splits execution flow, allowing the caller of the async function
to resume execution. After the `await` defers the continuation of the async
function, execution of subsequent statements ensues. If this `await` is the
last expression executed by its function, execution continues by returning to the
function's caller a pending `Promise` for completion of the
`await`'s function and resuming execution of that caller.
```

- ko 번역
```
...
`await`은 실행 흐름을 분할하고 `await` 함수의 호출자가 `await` 함수의 지연된 지속 전에 실행을 재개할 수 있게 합니다. `await`가 
`await` 함수를 연기한 후, 이것이 함수에 의해 실행된 첫 번째 `await`이라면 즉시 실행은 함수 호출자에게 `await` 함수의 완료에 대한 대기
(pending) 중인 `Promise`를 반환하고 그 호출자의 실행을 재개함으로써 계속 이어갑니다.
```

2022-08-14 14:45 UTC, ojj1123 commented
@hochan222 제가 늦게 확인했네요..!!
새로 pr 네네 해당 PR로 반영해도 상관없습니다:)

기존 PR은 닫아도 괜찮을까요?

2022-08-14 14:50 UTC, hochan222 commented
넵넵 감사합니다. PR closed 하겠습니다. 

좋은 하루 보내세요 :)

2022-08-29 14:56 UTC, yujo11 commented
@ojj1123 님 안녕하세요 리뷰가 늦어져서 죄송합니다

빠른 시일 내에 리뷰 진행하도록 하겠습니다 🙇‍♂️🙇‍♂️🙇‍♂️

2022-08-30 04:44 UTC, ojj1123 commented
@yujo11 리뷰 감사합니다~

2022-09-13 12:32 UTC, hochan222 commented
@yujo11 님 확인 멘션 드립니다.

2022-09-16 06:44 UTC, ojj1123 commented
이건 리뷰가 언제 이루어지나요??

2022-09-18 16:46 UTC, yujo11 requested changes
안녕하세요 @ojj1123님 먼저 리뷰가 늦어져서 죄송하다는 말씀 드리고 싶습니다ㅠㅠ

PR본문으로 남겨주신 내용이 말씀해주신대로 어색하다고 느껴져서 고쳐볼려고 했는데 원문이 어려워서 고민하느라 시간이 너무 많이 흘러버렸네요.

그 사이에 `await`의 영어 문서가 업데이트 되어 해당 내용을 적용해서 해석을 조금 바꿔봤는데요.

내용 확인해주시면 감사하겠습니다! 🙇‍♂️🙇‍♂️🙇‍♂️

2022-09-18 16:46 UTC, yujo11 commented on files/ko/web/javascript/reference/operators/await/index.md
최근 `await`문서가 업데이트 돼서 해당 내용들까지 같이 반영하면 좋을거 같네요.

[An await splits execution flow, allowing the caller of the async function to resume execution. After the await defers the continuation of the async function, execution of subsequent statements ensues. If this await is the last expression executed by its function, execution continues by returning to the function's caller a pending Promise for completion of the await's function and resuming execution of that caller.
](https://github.com/mdn/content/commit/f11a38ee802f4fab2e6e7b01b24c9707c52e0243)


- 기존

`await` 문은 `Promise`가 처리(즉, 이행되거나 거부됨)될 때까지 `async` 함수의 실행을 일시 정지하고, `Promise`가 이행되면 `async` 함수를 일시 정지한 부분부터 실행합니다. 이때 `await` 문의 반환값은 `Promise` 에서 이행된 값이 됩니다.

만약 `Promise`가 거부되면, `await` 문은 거부된 값을 `throw`합니다.

`await` 연산자 다음에 나오는 표현식의 값이 `Promise`가 아니면 해당 값을 [resolved Promise](/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve)로 변환시킵니다.


`await`은 실행 흐름을 분할하고 `await` 함수의 호출자가 `await` 함수의 지연된 지속 전에 실행을 재개할 수 있게 합니다. `await`가 `await` 함수를 연기한 후, 이것이 함수에 의해 실행된 첫 번째 `await`이라면 즉시 실행은 함수 호출자에게 `await` 함수의 완료에 대한 대기(pending) 중인 `Promise`를 반환하고 그 호출자의 실행을 재개함으로써 계속 이어갑니다.


- 변경

`Promise`가 reject 되면 `await` 표현식은 rejected value를 반환합니다.  `await` 표현식을 포함하는 함수는 오류의 스택 트레이스에 나타납니다.  그렇지 않고 reject된 `Promise`를 기다리지 않거나 즉시 반환되는 경우 호출자 함수는 스택 트레이스에 나타나지 않습니다.

`await`는 실행 흐름을 분할하여 비동기 함수의 호출자가 실행을 재개할 수 있게 합니다. `await`가 비동기 함수의 실행을 연기한 후, 후속 명령문이 실행됩니다. 이 `await`가 함수에 의해 실행된 마지막 표현식인 경우 `await`의 함수 완료에 대한 보류 중인 `Promise`를 함수 호출자에게 반환하고 해당 호출자의 실행을 재개하여 실행이 계속됩니다.

`await`는 비동기 함수와 모듈 내에서만 유효하기 때문에, 자체로 비동기이고, `Promise`를 반환합니다. `await` 표현식은 메인 스레드를 차단하지 않으며 결과에 실제로 의존하는 코드의 실행만 연기합니다.

2022-09-18 17:47 UTC, ojj1123 commented on files/ko/web/javascript/reference/operators/await/index.md
지금 보니 원문 description이랑 example이 많이 추가 됐네요.

근데 리뷰 달아주신 부분을 제가 어떻게 받아들여야 할지 헷갈려서 그런데,
제가 번역한 '기존'부분에 '변경'부분을 반영하고, 바뀐 원문도 반영해달라고 이해하면 될까요?

2022-09-18 18:02 UTC, ojj1123 commented on files/ko/web/javascript/reference/operators/await/index.md
근데 이게 제가 만든 PR이 아닌데 수정할 수가 있나요?

2022-09-20 02:13 UTC, ojj1123 commented
@hochan222 await관련 원문 문서가 많이 변경되어서 수정해야하는데, 이 pr을 닫고 제가 다시 올려도 괜찮을까요?

2022-09-20 02:38 UTC, hochan222 commented
넵넵 새로 PR 생성 후 멘션주시면 yujo 님으로 리뷰어님 변경드리겠습니다!

2022-10-02 18:03 UTC, closed without merging