Remove the {{link}} macro from ru
mdn/translated-content pull request #7671
Opened 2022-08-14 16:01 UTC by MrBrain295

Part of: #7566

2022-08-14 23:44 UTC, yin1999 requested changes
Those are html file, so we should use `<a>` tag

2022-08-14 23:44 UTC, yin1999 commented on files/ru/glossary/javascript/index.html
> + <li>[Руководство JavaScript](/ru/docs/Web/JavaScript/Guide) на MDN</li>
```suggestion
 <li><a href="/ru/docs/Web/JavaScript/Guide">Руководство JavaScript</a> на MDN</li>
```

2022-08-14 23:44 UTC, yin1999 commented on files/ru/glossary/javascript/index.html
> + <li> [Справочник по JavaScript](/ru/docs/Web/JavaScript/reference) на MDN</li>
```suggestion
 <li><a href="/ru/docs/Web/JavaScript/reference">Справочник по JavaScript</a> на MDN</li>
```

2022-08-14 23:44 UTC, yin1999 commented on files/ru/glossary/json/index.html
> + <li>[JSON](/ru/docs/Web/JavaScript/Reference/Global_Objects/JSON) на MDN</li>
```suggestion
 <li><a href="/ru/docs/Web/JavaScript/Reference/Global_Objects/JSON">JSON</a> на MDN</li>
```

2022-08-17 16:31 UTC, MrBrain295 commented
@sashasushko

2022-09-15 13:57 UTC, yin1999 approved these changes
LGTM

2022-09-15 13:58 UTC, yin1999 commented
@caugner shall we merge this?

2022-09-15 14:13 UTC, merged