[ko/fix] Update typo error
mdn/translated-content pull request #7681
Opened 2022-08-15 04:27 UTC by mirusu400

😉

2022-08-26 04:49 UTC, pje1740 approved these changes
확인했습니다! 고생하셨습니다!

2022-08-26 04:50 UTC, pje1740 commented
main 브랜치에서 html 파일들이 수정되면서 컨플릭이 발생하고 있는 거 같습니다. main 브랜치와 rebase 하여 컨플릭 해결 후 작업하신 브랜치로 force push 부탁 드리겠습니다. 혹시 헷갈리시는 부분이 있다면 말씀 주세요!

2022-08-26 04:51 UTC, pje1740 requested changes
컨플릭 해결이 필요하여 Request changes로 수정합니다.

2022-08-26 08:15 UTC, mirusu400 reviewed
수정 완료했습니다

2022-08-28 01:58 UTC, yin1999 commented
Hi @mirusu400, could you disable the workflow in your fork and then revert the last commit?

2022-08-28 06:50 UTC, mirusu400 commented
@yin1999 I'll just close my PR and make new PR later.

2022-08-28 06:52 UTC, closed without merging

2022-08-28 06:55 UTC, mirusu400 commented
@yin1999 #8071