/MDN 以下のファイルを md へ一括変換
mdn/translated-content pull request #7765
Opened 2022-08-18 02:09 UTC by mfuji09

2022-08-18 02:12 UTC, mfuji09 commented
一括変換時のログメッセージです。
今回は、エラー部分は手作業で対応しました。

# Report from 2022/8/17 22:55:36
## All unhandled elements
- div.notecard.warning (3)
- td (3)
- div.quote (1)
## Details per Document
### [/ja/docs/MDN/At_ten](https://developer.mozilla.org/ja/docs/MDN/At_ten)
### Missing conversion rules
- div.quote (26:1)
### [/ja/docs/MDN/Community/Learn_forum](https://developer.mozilla.org/ja/docs/MDN/Community/Learn_forum)
### Missing conversion rules
- div.notecard.warning (87:1)
### [/ja/docs/MDN/Contribute](https://developer.mozilla.org/ja/docs/MDN/Contribute)
#### Invalid AST transformations
##### td (42:4) => tableCell
```
type: "list"
ordered: false
start: 

spread: false
children: 
  type: "listItem"
  spread: false
  children: 
    type: "paragraph"
    children: 
      type: "text"
      value: "協力する分野のウェブ技術の知識 (JavaScript や CSS など)。"
  type: "listItem"
  spread: false
  children: 
    type: "paragraph"
    children: 
      type: "text"
      value: "英語に関する合理的な理解 (完璧でなくても構いません。私たちが支援します)。"
```
##### td (52:4) => tableCell
```
type: "list"
ordered: false
start: 

spread: false
children: 
  type: "listItem"
  spread: false
  children: 
    type: "paragraph"
    children: 
      type: "text"
      value: "協力する分野のウェブ技術の知識 (JavaScript や CSS など)。"
  type: "listItem"
  spread: false
  children: 
    type: "paragraph"
    children: 
      type: "text"
      value: "英語に関する合理的な理解 (完璧でなくても構いません。私たちが支援します)。"
```
##### td (62:4) => tableCell
```
type: "list"
ordered: false
start: 

spread: false
children: 
  type: "listItem"
  spread: false
  children: 
    type: "paragraph"
    children: 
      type: "text"
      value: "協力する分野のウェブ技術の知識 (JavaScript や CSS など)。"
  type: "listItem"
  spread: false
  children: 
    type: "paragraph"
    children: 
      type: "text"
      value: "技術的なトピックを説明したり、初心者がコードを学べるようにすることに対する熱意。"
  type: "listItem"
  spread: false
  children: 
    type: "paragraph"
    children: 
      type: "text"
      value: "適度な英語力。完璧である必要はありません。"
```
### [/ja/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN](https://developer.mozilla.org/ja/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN)
### Missing conversion rules
- div.notecard.warning (11:1)
- div.notecard.warning (153:1)

2022-08-18 05:40 UTC, mfuji09 commented
#7782

2022-08-18 10:10 UTC, potappo requested changes
以下の変換ミスがあるようです。
- 「学習フォーラム」のページの深いネストのリストの変換が上手く行っていない。
- Note ブロックの変換が上手く行っていない（全般的に）。

2022-08-18 14:47 UTC, mfuji09 commented
両方とも対処してみました。

「学習フォーラム」の件ですが、どうやら変換スクリプトの処理の都合で、 `<ol>` がネストされたリストを変換すると、正しくインデントが解釈できなくなるようです。
`<ol>` を変換するときに、見出し番号の次に空白が2つ付いてしまうために、正しくインデントが解釈できなくなることが原因のようです（どうやら変換スクリプトのバグっぽいですね）。
事前処理で対策するのは無理そうなので、変換後に直すしかなさそうです。

Note: についてもわかる範囲で修正してみました。こちらも HTML の時には何通りもの書き方があったので（中には Yari になってから現れたものもある）、変換プロセスの中ですべてに対応するのは無理そうです。こちらは数が大変多いので、致命的なものと、単純な置換で対処できるものを除いて、変換完了後（マージ後）に気が付いた人が直すようにした方が現実的かもしれません。

2022-08-19 01:38 UTC, potappo approved these changes
OK です。

2022-08-19 01:38 UTC, merged