retranslate classlist
mdn/translated-content pull request #7834
Opened 2022-08-20 02:10 UTC by Jack-Zhang-1314

2022-08-20 02:16 UTC, yin1999 requested changes
请一并注意空格

2022-08-20 02:16 UTC, yin1999 commented on files/zh-cn/web/api/element/classlist/index.md
> +// add or remove multiple classes
不应去除原先的翻译的注释（与英文对应）

2022-08-20 03:34 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/element/classlist/index.md
> +// our starting state: <div class="foo"></div>
```suggestion
// 初始状态：<div class="foo"></div>
```

2022-08-20 03:34 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/element/classlist/index.md
> +// use the classList API to remove and add classes
```suggestion
// 使用 classList API 移除、添加类值
```

2022-08-20 03:34 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/element/classlist/index.md
> +// if visible is set remove it, otherwise add it
```suggestion
// 如果 visible 类值已存在，则移除它，否则添加它
```

2022-08-20 04:41 UTC, yin1999 requested changes

2022-08-20 04:41 UTC, yin1999 commented on files/zh-cn/web/api/element/classlist/index.md
> +**`Element.classList`** 是一个只读属性，返回一个动态的元素 `class` 属性的 {{domxref("DOMTokenList")}} 集合。这可以用于操作 class 集合。
翻译得不对，原翻译更加合适

2022-08-21 04:33 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/element/classlist/index.md
> +**`Element.classList`** 是一个只读属性，返回一个动态的元素 `class` 属性的 {{domxref("DOMTokenList")}} 集合。这可以用于操作 class 集合。
思考一下，确实这样

2022-08-21 04:34 UTC, yin1999 commented on files/zh-cn/web/api/element/classlist/index.md
> +**`Element.classList`** 是一个只读属性，返回一个动态的元素 `class` 属性的 {{domxref("DOMTokenList")}} 集合。这可以用于操作 class 集合。
动态集合而非动态元素，对该集合的修改会直接反映到元素上，目前的翻译容易造成误解

2022-08-21 05:27 UTC, yin1999 approved these changes

2022-08-21 05:27 UTC, merged