add: UUID ja
mdn/translated-content pull request #7842
Opened 2022-08-20 07:42 UTC by ShirasuGyoza

ページ（用語集）：
https://developer.mozilla.org/en-US/docs/glossary/uuid

日本語ページを新規追加（.md）して翻訳しました。

fix https://github.com/mozilla-japan/translation/issues/574

2022-08-23 12:10 UTC, mfuji09 requested changes
3件の修正をお願いします。

2022-08-23 23:58 UTC, ShirasuGyoza commented on files/ja/glossary/uuid/index.md
> +- [`Crypto.randomUUID()`](/en-US/docs/Web/API/Crypto/randomUUID)
https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID
はまだ日本語のページが無いため、リンクは en-US にしています

2022-08-24 00:00 UTC, ShirasuGyoza commented on files/ja/glossary/uuid/index.md
> +もしシステムが、本当に完全な一意の ID を必要としたなら、それは中央機関によって割り当てられるかもしれません。
ありがとうございます！修正しました
[d6a740d](https://github.com/mdn/translated-content/pull/7842/commits/d6a740d8c6e713f9f01bffe9b19ad2a37c8e0bfa)

2022-08-24 00:01 UTC, ShirasuGyoza commented on files/ja/glossary/uuid/index.md
> +## さらに学ぶには
他の似たページに合わせて分けて書いてしまっていました。1つだけ「関連項目」として修正しました。
[d6a740d](https://github.com/mdn/translated-content/pull/7842/commits/d6a740d8c6e713f9f01bffe9b19ad2a37c8e0bfa)

2022-08-24 00:02 UTC, ShirasuGyoza commented
レビューありがとうございます！指摘いただいた箇所を修正しましたのでお手すきで再度レビューをお願いします。

2022-08-25 04:05 UTC, mfuji09 requested changes
リンクの件は、下記のコメントの通りにお願いします。

2022-08-25 04:05 UTC, mfuji09 commented on files/ja/glossary/uuid/index.md
> +- [`Crypto.randomUUID()`](/en-US/docs/Web/API/Crypto/randomUUID)
日本語のページがなくても、リンクは /ja/ を使用してください。日本語の記事がなければ自動的に英語版が案内されますし、日本語訳を作成すれば、そちらに切り替わります。

/en-US/ でリンクを作成すると、日本語訳を作成したときに、その記事へのリンクをすべて手動で更新しなければならなくなります。

2022-09-11 14:08 UTC, ShirasuGyoza commented on files/ja/glossary/uuid/index.md
> +- [`Crypto.randomUUID()`](/en-US/docs/Web/API/Crypto/randomUUID)
こちら修正が遅くなり申し訳ありません、
リンクについて、理解しました。 `/ja/` に修正しました。
[d57c168](https://github.com/mdn/translated-content/pull/7842/commits/d57c16856986f1ca341d9d52349e03b0e987d466)

2022-09-11 14:11 UTC, mfuji09 approved these changes
OKです。

2022-09-11 14:11 UTC, merged