web/api/performance* 以下を md に一括変換
mdn/translated-content pull request #7846
Opened 2022-08-20 09:23 UTC by mfuji09

#7782 
変換スクリプトが報告するエラーはすべて解決済みです。

2022-08-20 16:12 UTC, potappo requested changes
明らかに変換ミスになっていた箇所を修正しましたので、確認をお願いします。

2022-08-20 16:12 UTC, potappo commented on files/ja/web/api/performancenavigation/type/index.md
> +従来の **`PerformanceNavigation`\*\***`.type`\*\* 読み取り専用プロパティは、このページへの移動方法を説明する定数を含む `unsigned short` を返します。可能な値は次のとおりです:
```suggestion
従来の **`PerformanceNavigation.type`** 読み取り専用プロパティは、このページへの移動方法を説明する定数を含む `unsigned short` を返します。可能な値は次のとおりです:
```

2022-08-20 16:12 UTC, potappo commented on files/ja/web/api/performanceobserver/observe/index.md
> +監視するパフォーマンスエントリタイプのセットを指定するには、**{{domxref("PerformanceObserver")}}** インターフェイスの**`observe()`** メソッドを使用します。パフォーマンスエントリタイプは {{domxref("DOMString")}} オブジェクトの配列として指定され、それぞれが 1 つのエントリタイプを命名します。型名は{{Section
```suggestion
監視するパフォーマンスエントリタイプのセットを指定するには、**{{domxref("PerformanceObserver")}}** インターフェイスの **`observe()`** メソッドを使用します。パフォーマンスエントリタイプは {{domxref("DOMString")}} オブジェクトの配列として指定され、それぞれが 1 つのエントリタイプを命名します。型名は{{SectionOnPage("/ja/docs/Web/API/PerformanceEntry/entryType", "パフォーマンスエントリタイプ名")}}に記載されています。
```

2022-08-21 06:16 UTC, mfuji09 commented
後は特に問題なさそうなので、とりあえずマージします。

2022-08-21 06:16 UTC, merged