docs: update map section
mdn/translated-content pull request #7885
Opened 2022-08-21 12:25 UTC by YangFong

2022-08-21 12:43 UTC, yin1999 requested changes

2022-08-21 12:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/map/clear/index.md
> +### 调用 `clear()` 方法
We try to avoid using `<code>` in head

```suggestion
### 使用 clear()
```

2022-08-21 12:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/map/delete/index.md
> +### 使用 `delete()` 方法
```suggestion
### 使用 delete()
```

2022-08-21 12:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/map/clear/index.md
> +console.log(myMap.has('bar')); // true
please follow english document, if you want to improve it, please modify the english document first:

```suggestion
myMap.size;       // 2
myMap.has('bar'); // true
```

2022-08-21 12:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/map/clear/index.md
> +console.log(myMap.has('bar')); // false
```suggestion
myMap.size;       // 0
myMap.has('bar')  // false
```

2022-08-21 12:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/map/delete/index.md
> +console.log(myMap.has("bar"));    // 返回 false。"bar" 元素将不再存在于 Map 实例中
```suggestion
myMap.delete('bar'); // 返回 true。成功地移除元素
myMap.has('bar');    // 返回 false。"bar" 元素将不再存在于 Map 实例中
```

2022-08-21 12:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/map/entries/index.md
>  ```plain
```suggestion
```js
```

2022-08-21 12:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/map/get/index.md
> +  - : 必要参数，也是唯一参数，要从目标 `Map` 对象中获取的元素的键。
```suggestion
  - : 要从目标 `Map` 对象中获取的元素的键。
```

2022-08-21 12:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/map/get/index.md
> +### 使用 `get()` 方法
```suggestion
### 使用 get()
```

2022-08-21 12:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/map/get/index.md
> +console.log(myMap.get('baz'));   // 返回 undefined
```suggestion
myMap.get('bar');  // 返回 "foo"
myMap.get('baz');   // 返回 undefined
```

2022-08-21 12:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/map/has/index.md
> +### 使用 `has()` 方法
```suggestion
### 使用 has()
```

2022-08-21 12:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/map/has/index.md
> +console.log(myMap.has("baz"));  // 返回 false
```suggestion
myMap.has('bar');  // 返回 true
myMap.has('baz');  // 返回 false
```

2022-08-21 12:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/map/set/index.md
> +### 使用 `set()` 方法
```suggestion
### 使用 set()
```

2022-08-21 12:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/map/set/index.md
> +### 链式使用 `set()` 方法
```suggestion
### 链式使用 set()
```

2022-08-21 12:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/map/size/index.md
> +console.log(myMap.size); // 3
```suggestion
myMap.size // 3
```

2022-08-21 12:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/map/values/index.md
> +### 使用 `values()`
```suggestion
### 使用 values()
```

2022-08-21 12:56 UTC, YangFong commented
For using 'console.log()', the upstream has recently been updated.Therefore, this change is made.

2022-08-21 12:58 UTC, yin1999 commented
> For using `console.log()`, the upstream has recently been updated.Therefore, this change is made.

Not all of those files

2022-08-21 13:01 UTC, YangFong commented
> Not all of those files

Maybe I should have done the whole thing first.

2022-08-22 00:44 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/map/delete/index.md
> +console.log(myMap.has("bar"));    // 返回 false。"bar" 元素将不再存在于 Map 实例中
Please check those unresolved suggestions, you can try to update the english documents, then please poke me for a review.

Or just apply those suggestions

2022-08-22 23:19 UTC, yin1999 approved these changes

2022-08-22 23:19 UTC, merged