web/svg 以下を md へ一括変換
mdn/translated-content pull request #7923
Opened 2022-08-22 12:36 UTC by mfuji09

#7782 
変換スクリプトから報告された問題は対策済みです。

2022-08-25 15:33 UTC, potappo requested changes
文章中の Markdown の変換ミスだけ修正しています。確認をお願いします。

2022-08-25 15:33 UTC, potappo commented on files/ja/web/svg/attribute/accent-height/index.md
> +**`accent-height`**属性は原点からアクセント文字の上端までの距離を定義します。これはフォント座標系で測られる距離です。
```suggestion
**`accent-height`** 属性は原点からアクセント文字の上端までの距離を定義します。これはフォント座標系で測られる距離です。
```

2022-08-25 15:33 UTC, potappo commented on files/ja/web/svg/attribute/cx/index.md
> +**`cx`**属性は中心の x-座標を定義します。
```suggestion
**`cx`** 属性は中心の x-座標を定義します。
```

2022-08-25 15:33 UTC, potappo commented on files/ja/web/svg/attribute/cy/index.md
> +**`cy`**属性は中心の y-座標を定義します。
```suggestion
**`cy`** 属性は中心の y-座標を定義します。
```

2022-08-25 15:33 UTC, potappo commented on files/ja/web/svg/attribute/d/index.md
> +**`d`**属性は描かれるパスを定義します。
```suggestion
**`d`** 属性は描かれるパスを定義します。
```

2022-08-25 15:33 UTC, potappo commented on files/ja/web/svg/attribute/d/index.md
> +*3 次[ベジエ曲線](https://ja.wikipedia.org/wiki/%E3%83%99%E3%82%B8%E3%82%A7%E6%9B%B2%E7%B7%9A)*は 4 点で定義される滑らかな曲線です:
```suggestion
*3 次[ベジエ曲線](https://ja.wikipedia.org/wiki/%E3%83%99%E3%82%B8%E3%82%A7%E6%9B%B2%E7%B7%9A)* は 4 点で定義される滑らかな曲線です:
```

2022-08-25 15:33 UTC, potappo commented on files/ja/web/svg/attribute/d/index.md
> +*2 次[ベジエ曲線](https://ja.wikipedia.org/wiki/%E3%83%99%E3%82%B8%E3%82%A7%E6%9B%B2%E7%B7%9A)*は 3 点で定義される滑らかな曲線です:
```suggestion
*2 次[ベジエ曲線](https://ja.wikipedia.org/wiki/%E3%83%99%E3%82%B8%E3%82%A7%E6%9B%B2%E7%B7%9A)* は 3 点で定義される滑らかな曲線です:
```

2022-08-25 15:33 UTC, potappo commented on files/ja/web/svg/attribute/fill-opacity/index.md
> +**`fill-opacity`**属性は、図形に適用されるペイントサーバー(_色_, _勾配_, _パターン_, 等)の不透明度を定義するプレゼンテーション属性です。
```suggestion
**`fill-opacity`** 属性は、図形に適用されるペイントサーバー(_色_, _勾配_, _パターン_, 等)の不透明度を定義するプレゼンテーション属性です。
```

2022-08-25 15:33 UTC, potappo commented on files/ja/web/svg/attribute/scale/index.md
> +**`scale`**属性は、{{SVGElement("feDisplacementMap")}}フィルタプリミティブにおいて用いられる距離の尺度因子を定義します。その量は、{{SVGElement("filter")}}要素の{{SVGAttr("primitiveUnits")}}属性で規定される座標系で表されます。
```suggestion
**`scale`** 属性は、{{SVGElement("feDisplacementMap")}}フィルタプリミティブにおいて用いられる距離の尺度因子を定義します。その量は、{{SVGElement("filter")}}要素の{{SVGAttr("primitiveUnits")}}属性で規定される座標系で表されます。
```

2022-08-25 15:33 UTC, potappo commented on files/ja/web/svg/attribute/stroke-dasharray/index.md
> +**`stroke-dasharray`**属性は、 輪郭を描くために使用される、破線や間隔のある線のパターンを定義するプレゼンテーション属性です。
```suggestion
**`stroke-dasharray`** 属性は、 輪郭を描くために使用される、破線や間隔のある線のパターンを定義するプレゼンテーション属性です。
```

2022-08-25 15:33 UTC, potappo commented on files/ja/web/svg/attribute/stroke-dashoffset/index.md
> +**`stroke-dashoffset`**属性は、関連する破線をレンダリングするうえで、オフセットを定義するプレゼンテーション属性です。
```suggestion
**`stroke-dashoffset`** 属性は、関連する破線をレンダリングするうえで、オフセットを定義するプレゼンテーション属性です。
```

2022-08-26 13:57 UTC, mfuji09 commented
@potappo レビューありがとうございました。

2022-08-26 14:03 UTC, merged