zh-cn:retranslate stream  concept
mdn/translated-content pull request #7933
Opened 2022-08-22 21:02 UTC by Jack-Zhang-1314

2022-08-22 23:25 UTC, yin1999 requested changes

2022-08-22 23:25 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/concepts/index.md
> -{{apiref("Streams")}}
line 6?

2022-08-22 23:25 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/concepts/index.md
> +一个 **Writable stream（可写流）** 是一个可以写入数据的数据终点，在 JavaScript 中以一个 {{domxref("WritableStream")}} 对象表示。这是 JavaScript 层面对 **underlying sink（底层接收器）** 的抽象——一个更低层次的 I/O 接收器，将原始数据写入其中。
We should follow the translation guide, please modify this.

2022-08-22 23:25 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/concepts/index.md
> +Streams API 使用 **链式管道（pipe chain）**的结构将流传输到另一个流已经成为可能。有两种方法可以作用于它：
After created the PR, please check the pr preview. It's a easy way to check the render problem:

<https://pr7933.content.dev.mdn.mozit.cloud/zh-CN/docs/Web/API/Streams_API/Concepts>

2022-08-23 01:25 UTC, yin1999 requested changes
请修改

2022-08-23 01:25 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/concepts/index.md
> +- **Pull sources** 需要在你连接到它们后，显式地请求数据。例如通过 [Fetch](/zh-CN/docs/Web/API/Fetch_API) 或 [XHR](/zh-CN/docs/Web/API/XMLHttpRequest/XMLHttpRequest) 请求访问一个文件。
复数、空格

2022-08-23 01:25 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/concepts/index.md
> +数据被按序读入到许多分块，这些分块被称作 **chunk**。**chunk** 可以是单个字节，也可以是某种更大的数据类型，例如特定大小的 [typed array](/zh-CN/docs/Web/JavaScript/Typed_arrays)。单个流的 **chunk** 可以有不同的大小和类型。
许多小的片段，被称作**分块**（chunk）

2022-08-23 01:25 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/concepts/index.md
> +一个流一次只能被一个 reader 读取；当一个 reader 被创建并开始读一个流（**active reader**，译者注：该流已经处于活动状态）时，我们说，它被 **locked**（锁定）在该流上。如果你想让另一个 reader 读这个流，则通常需要先取消第一个 reader ，再执行其他操作（你也可以 **tee**，译者注：拷贝流，参阅下面的 Teeing 部分）。
移除“译者注”，请参考英文原文。同时，请对应文内标题

2022-08-23 01:25 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/concepts/index.md
> +一个 **Writable stream**（可写流）是一个可以写入数据的数据终点，在 JavaScript 中以一个 {{domxref("WritableStream")}} 对象表示。这是 JavaScript 层面对 **underlying sink**（底层接收器）的抽象——一个更低层次的 I/O 接收器，将原始数据写入其中。
**可写流**（writable stream）

2022-08-23 01:25 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/concepts/index.md
> +当 writer 被创建并开始写入一个流（**active writer**，译者注：该 writer 已处于活动状态）时，我们说，它被 **locked**（锁定）在该流上。同一时刻，一个 writer 只能写入一个可写流。如果你想要其他 writer 开始写入你的流，在你将 writer 附着到该流之前，你必须先中止上一个 writer。
“译者注”

2022-08-23 01:25 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/concepts/index.md
> +## 内置队列和排队策略
“排队策略” or “队列策略”，请搜索一下

2022-08-23 01:25 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/concepts/index.md
> +## 链式管道传输（Pipe chain）
移除英文，这里并不影响理解

2022-08-23 01:25 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/concepts/index.md
> +流的一个重要概念是 **backpressure**（背压）——这是单个流或一个 pipe chain 调节读/写速度的过程。当链中后面的一个流仍然忙碌，尚未准备好接受更多的分块时，它会通过链向上游的流发送一个信号，告诉上游的转换流（或原始源）适当地减慢传输速度，这样你就不会在任何地方遇到瓶颈。
```suggestion
流的一个重要概念是**背压**——这是单个流或一个链式管道调节读/写速度的过程。当链中后面的一个流仍然忙碌，尚未准备好接受更多的分块时，它会通过链向上游的流发送一个信号，告诉上游的转换流（或原始源）适当地减慢传输速度，这样你就不会在任何地方遇到瓶颈。
```

2022-08-23 01:25 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/concepts/index.md
>  要在可读流中使用 backpressure 技术，我们可以通过查询 controller 的 {{domxref("ReadableStreamDefaultController.desiredSize")}} 属性。如果该值太低或为负数，我们的 ReadableStream 可以告诉它的底层源停止往流中装载数据，然后我们沿着 stream chain 进行背压。
上面已经给出了 `背压`，请翻译

2022-08-23 02:50 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/streams_api/concepts/index.md
> +一个流一次只能被一个 reader 读取；当一个 reader 被创建并开始读一个流（**active reader**，译者注：该流已经处于活动状态）时，我们说，它被 **locked**（锁定）在该流上。如果你想让另一个 reader 读这个流，则通常需要先取消第一个 reader ，再执行其他操作（你也可以 **tee**，译者注：拷贝流，参阅下面的 Teeing 部分）。
```
（**active reader**，译者注：该流已经处于活动状态）
```

* 这个直接翻译成 不太理解翻译成什么---> **流已经处于活动状态**, 或许你有更好的建议？

2022-08-23 03:02 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/streams_api/concepts/index.md
> +## 内置队列和排队策略
可能 `入队策略` 会更好一点 `排队策略` 可能更强调如何排队等待的规则，你怎么看？

2022-08-23 03:50 UTC, yin1999 requested changes

2022-08-23 03:50 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/concepts/index.md
> +数据被按序读入到许多小的片段，这些片段被称作**分块**（chunk）。**chunk** 可以是单个字节，也可以是某种更大的数据类型，例如特定大小的 [typed array](/zh-CN/docs/Web/JavaScript/Typed_arrays)。单个流的 **chunk** 可以有不同的大小和类型。
```suggestion
数据被按序读入到许多小的片段，这些片段被称作**分块**（chunk）。**分块**可以是单个字节，也可以是某种更大的数据类型，例如特定大小的 [typed array](/zh-CN/docs/Web/JavaScript/Typed_arrays)。单个流的**分块**可以有不同的大小和类型。
```

2022-08-23 03:50 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/concepts/index.md
> +一个流一次只能被一个 reader 读取；当一个 reader 被创建并开始读一个流（**active reader**）时，我们说，它被 **locked**（锁定）在该流上。如果你想让另一个 reader 读这个流，则通常需要先取消第一个 reader ，再执行其他操作（你也可以 **tee**，请参阅下面的 Teeing 部分）。
```suggestion
一个流一次只能被一个 reader 读取；当一个 reader 被创建并开始读一个流（**active reader**）时，我们说，它被 **locked**（锁定）在该流上。如果你想让另一个 reader 读这个流，则通常需要先取消第一个 reader ，再执行其他操作（你也可以 **tee**，请参阅下面的拷贝部分）。
```

2022-08-23 03:50 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/concepts/index.md
> +一个 **可写流**（Writable stream）是一个可以写入数据的数据终点，在 JavaScript 中以一个 {{domxref("WritableStream")}} 对象表示。这是 JavaScript 层面对 **underlying sink**（底层接收器）的抽象——一个更低层次的 I/O 接收器，将原始数据写入其中。
```suggestion
一个**可写流**（Writable stream）是一个可以写入数据的数据终点，在 JavaScript 中以一个 {{domxref("WritableStream")}} 对象表示。这是 JavaScript 层面对 **underlying sink**（底层接收器）的抽象——一个更低层次的 I/O 接收器，将原始数据写入其中。
```

2022-08-23 03:55 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/concepts/index.md
> +当 writer 被创建并开始写入一个流（**active writer**，译者注：该 writer 已处于活动状态）时，我们说，它被 **locked**（锁定）在该流上。同一时刻，一个 writer 只能写入一个可写流。如果你想要其他 writer 开始写入你的流，在你将 writer 附着到该流之前，你必须先中止上一个 writer。
```suggestion
当 writer 被创建并开始向一个流写入数据（一个活跃的 writer）时，我们说，它被 **锁定**（locked）在该流上。同一时刻，一个 writer 只能向一个可写流写入数据。如果你想要用其它 writer向流中写入数据，在你将 writer 附着到该流之前，你必须先中止上一个 writer。
```

2022-08-23 03:58 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/streams_api/concepts/index.md
> +当 writer 被创建并开始写入一个流（**active writer**，译者注：该 writer 已处于活动状态）时，我们说，它被 **locked**（锁定）在该流上。同一时刻，一个 writer 只能写入一个可写流。如果你想要其他 writer 开始写入你的流，在你将 writer 附着到该流之前，你必须先中止上一个 writer。
```suggestion
当 writer 被创建并开始向一个流写入数据（一个活跃的 writer）时，我们说，它被 **锁定**（locked）在该流上。同一时刻，一个 writer 只能向一个可写流写入数据。如果你想要用其它 writer 向流中写入数据，在你将 writer 附着到该流之前，你必须先中止上一个 writer。
```

2022-08-23 04:18 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/concepts/index.md
> +## 内置队列和排队策略
“队列策略”较为合适，“入队策略”强调写入，但队列策略对于“可读流”读取和“可写流”写入均会生效。

2022-08-23 04:52 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/streams_api/concepts/index.md
> +## 内置队列和排队策略
有道理，那 `排队策略` 似乎也没有问题，不过之前的翻译这里没有统一，要不就 `队列策略`

2022-08-23 04:57 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/concepts/index.md
> +## 内置队列和排队策略
yes, please

2022-08-23 05:00 UTC, yin1999 approved these changes

2022-08-23 05:01 UTC, merged