Use readable
mdn/translated-content pull request #7963
Opened 2022-08-23 22:45 UTC by Jack-Zhang-1314

2022-08-24 00:21 UTC, yin1999 requested changes
Could you please check the pr review generated by GitHub workflow? Some render issue could be found there.

And some words is not well translated.

2022-08-24 01:53 UTC, yin1999 requested changes

2022-08-24 01:53 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/using_readable_streams/index.md
> +我们有一个简单的示例，叫做[解压 PNG 分块](https://github.com/mdn/dom-examples/tree/master/streams/png-transform-stream)（[也可以参见现场演示](https://mdn.github.io/dom-examples/streams/png-transform-stream/)）。此示例将图像作为流来获取，然后将它
现场演示

2022-08-24 01:53 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/using_readable_streams/index.md
> +关于如何使用可读_字节_流的信息，参见[使用可读字节流](/zh-CN/docs/Web/API/Streams_API/Using_readable_byte_streams)：具有底层字节源的流，可以向消费者执行高效的零复制传输，绕过流的内部队列。
斜体

2022-08-24 01:53 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/using_readable_streams/index.md
> +> **备注：** 本文要求你已理解可读流相关知识，并了解相关的高级概念，如果还不了解，建议你先查看[流的概念和简介](/zh-CN/docs/Web/API/Streams_API#concepts_and_usage)以及掌握 [Streams API 概念](/zh-CN/docs/Web/API/Streams_API/Concepts)然后再阅读此文。
注意链接的 hash，大部分的hash都需要更新，[translation-guide](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md#%E7%AB%99%E5%86%85%E9%93%BE%E6%8E%A5%E7%BF%BB%E8%AF%91) 中也有提到：

> 还需特别注意路径后带有片段标识（fragment）的站内链接，请同步更新片段标识为本地化文档中指定标题的 ID（若不清楚标题和 ID 之间的转换规则，可以在浏览器的开发者工具中查找对应标题的 ID）。

2022-08-24 01:57 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/streams_api/using_readable_streams/index.md
> +> **备注：** 本文要求你已理解可读流相关知识，并了解相关的高级概念，如果还不了解，建议你先查看[流的概念和简介](/zh-CN/docs/Web/API/Streams_API#concepts_and_usage)以及掌握 [Streams API 概念](/zh-CN/docs/Web/API/Streams_API/Concepts)然后再阅读此文。
这部分没有摘录英文文档，可能太旧了🤔

2022-08-24 02:07 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/streams_api/using_readable_streams/index.md
> +我们有一个简单的示例，叫做[解压 PNG 分块](https://github.com/mdn/dom-examples/tree/master/streams/png-transform-stream)（[也可以参见现场演示](https://mdn.github.io/dom-examples/streams/png-transform-stream/)）。此示例将图像作为流来获取，然后将它
？这样会不会太突兀

2022-08-24 02:08 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/using_readable_streams/index.md
> +我们有一个简单的示例，叫做[解压 PNG 分块](https://github.com/mdn/dom-examples/tree/master/streams/png-transform-stream)（[也可以参见现场演示](https://mdn.github.io/dom-examples/streams/png-transform-stream/)）。此示例将图像作为流来获取，然后将它
不应该翻译成“现场演示”，你可以参考以前的翻译

2022-08-24 02:46 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/streams_api/using_readable_streams/index.md
> +我们有一个简单的示例，叫做[解压 PNG 分块](https://github.com/mdn/dom-examples/tree/master/streams/png-transform-stream)（[也可以参见现场演示](https://mdn.github.io/dom-examples/streams/png-transform-stream/)）。此示例将图像作为流来获取，然后将它
记不得了，不是这个吗，我记得是这个，忘了在哪

2022-08-24 03:21 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/streams_api/using_readable_streams/index.md
> +我们有一个简单的示例，叫做[解压 PNG 分块](https://github.com/mdn/dom-examples/tree/master/streams/png-transform-stream)（[也可以参见现场演示](https://mdn.github.io/dom-examples/streams/png-transform-stream/)）。此示例将图像作为流来获取，然后将它
**在线演示** 😢

2022-08-24 03:30 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/using_readable_streams/index.md
> +> **备注：** 本文要求你已理解可读流相关知识，并了解相关的高级概念，如果还不了解，建议你先查看[流的概念和简介](/zh-CN/docs/Web/API/Streams_API#concepts_and_usage)以及掌握 [Streams API 概念](/zh-CN/docs/Web/API/Streams_API/Concepts)然后再阅读此文。
@Jack-Zhang-1314 不止这一处，请更新其它的链接，同时请继续改善翻译

2022-08-28 08:43 UTC, yin1999 requested changes

2022-08-28 08:43 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/using_readable_streams/index.md
> +但是一个自定义流仍然是 `ReadableStream` 实例，意味着你可以给它附着一个 reader。例如，看看我们的[简单随机流示例](https://github.com/mdn/dom-examples/blob/master/streams/simple-random-stream/index.html)（[也可以参见在线演示](https://mdn.github.io/dom-ex
```suggestion
但是一个自定义流仍然是 `ReadableStream` 实例，意味着你可以给它附着一个 reader。例如，看看我们的[简单随机流示例](https://github.com/mdn/dom-examples/blob/master/streams/simple-random-stream/index.html)（[也可以参见在线演示](https://mdn.github.io/dom-examples/streams/simple-random-stream/)），其创建了一个自定义的流，排入了一些随机的字符串，然后在按下 _Stop string generation_ 的按钮后，再次从流中读取数据。
```

2022-08-28 08:43 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/using_readable_streams/index.md
> +> **备注：** 为了使用 {{domxref("FetchEvent.respondWith()")}} 消费流，排入的流内容的类型必须是 {{jsxref("Uint8Array")}}；例如使用 {{domxref("TextEncoder")}} 编码。
```suggestion
> **备注：** 为了使用 {{domxref("FetchEvent.respondWith()")}} 消费流，排入的流内容的类型必须是 {{jsxref("Uint8Array")}}；例如使用 {{domxref("TextEncoder")}} 进行编码。
```

2022-08-28 08:43 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/using_readable_streams/index.md
> +### 关闭并且取消流
```suggestion
### 关闭并取消流
```

2022-08-28 08:43 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/using_readable_streams/index.md
> +流的另一特征是通过管道的方式从一个流输出到另一个（称为 [pipe chain](/zh-CN/docs/Web/API/Streams_API/Concepts#链式管道传输)）。这会调用两个方法——{{domxref("ReadableStream.pipeThrough()")}}，它将可读流管道输出至拥有一对 writable/readable 的流中，并将一种数据转换成另一种；{{do
```suggestion
流的另一特征是通过管道的方式从一个流输出到另一个（称为[链式管道传输](/zh-CN/docs/Web/API/Streams_API/Concepts#链式管道传输)）。这会调用两个方法——{{domxref("ReadableStream.pipeThrough()")}}，它将可读流管道输出至拥有一对 writer/reader 的流中，并将一种数据转换成另一种；{{domxref("ReadableStream.pipeTo()")}} 将可读流管道传输至作为链式管道传输终点的 writer。
```

2022-08-28 16:08 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/streams_api/using_readable_streams/index.md
> +4. 你继续链接 `pipe` 函数，直到没有更多流要读取，在这种情况下，请遵循步骤 2。
reader 锁定流，它只是在不停的递归分块，而不是流

2022-08-29 00:00 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/using_readable_streams/index.md
> +4. 你继续链接 `pipe` 函数，直到没有更多流要读取，在这种情况下，请遵循步骤 2。
`reading the stream` means `可读流`?

2022-08-29 00:10 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/streams_api/using_readable_streams/index.md
> +4. 你继续链接 `pipe` 函数，直到没有更多流要读取，在这种情况下，请遵循步骤 2。
开始读取流， you are right, I can't code now, so please you.

2022-08-29 00:55 UTC, yin1999 commented on files/zh-cn/web/api/streams_api/using_readable_streams/index.md
> +4. 你继续链接 `pipe` 函数，直到没有更多流要读取，在这种情况下，请遵循步骤 2。
```suggestion
1. 编写一个从流的读取开始的函数。
2. 如果流中没有更多的分块要读取，你需要退出这个函数。
3. 如果流中有更多的分块要读取，你可以处理当前的分块后，再次运行该函数。
4. 你继续链接 `pipe` 函数，直到没有更多流要读取，在这种情况下，请遵循步骤 2。
```

2022-08-29 00:59 UTC, merged