zh-cn retranslate fetch event
mdn/translated-content pull request #7988
Opened 2022-08-24 23:29 UTC by Jack-Zhang-1314

2022-08-24 23:55 UTC, yin1999 requested changes

2022-08-24 23:55 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/index.md
> +这是会在 {{domxref("ServiceWorkerGlobalScope", "service worker global scope", "", 1)}} 中触发 `fetch` 事件的事件类型。它包含关于 fetch 的信息，包括 request 和接收方如何处理响应。它提供 {{domxref("FetchEvent.respondWith", "event.respondWith
```suggestion
这是会在 {{domxref("ServiceWorkerGlobalScope", "service worker 全局作用域", "", 1)}}中触发 `fetch` 事件的事件类型。它包含关于 fetch 的信息，包括 request 和接收方如何处理响应。它提供 {{domxref("FetchEvent.respondWith", "event.respondWith()")}} 方法，允许我们为此 fetch 提供一个响应。
```

2022-08-24 23:55 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/index.md
> +  - : 发起 fetch 的同源 {{domxref("Client", "客户端")}} 的 {{domxref("Client.id", "id")}}。
```suggestion
  - : 发起 fetch 的同源{{domxref("Client", "客户端")}}的 {{domxref("Client.id", "id")}}。
```

2022-08-24 23:55 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/index.md
> +  - : 一个 {{jsxref("Promise")}}，可能兑现为 {{domxref("Response")}} 或 `undefined`，如果该 fetch 没有导航或者 [navigation preload](/zh-CN/docs/Web/API/NavigationPreloadManager) 没有触发，则是 undefined。
翻译得有问题

2022-08-24 23:55 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/index.md
> +  - : 页面导航期间正在替换的 {{domxref("Client", "客户端")}} 的 {{domxref("Client.id", "id")}}。
```suggestion
  - : 页面导航期间正被替换的{{domxref("Client", "客户端")}}的 {{domxref("Client.id", "id")}}。
```

2022-08-24 23:55 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/index.md
> +  - : 页面导航期间，替换上一个 {{domxref("Client", "客户端")}} 的 {{domxref("Client.id", "id")}}。
与上一句句式相同，有逗号就都有逗号：

```suggestion
  - : 页面导航期间用于替换的{{domxref("Client", "客户端")}}的 {{domxref("Client.id", "id")}}。
```

2022-08-24 23:55 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/index.md
> +  - : 阻止浏览器的默认 fetch 操作，并且由你自己提供一个响应（可以由 promise 包裹）。
```suggestion
  - : 阻止浏览器的默认 fetch 操作，并且由你自己提供一个响应（可以是一个 promise）。
```

2022-08-24 23:55 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/index.md
> +  - : 延长事件的生命周期。用于通知浏览器超出响应返回范围的任务，例如流和缓存。
https://developer.mozilla.org/zh-CN/docs/Web/API/ExtendableEvent/waitUntil

2022-08-24 23:55 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/index.md
> +fetch 事件对非 GET 请求使用浏览器默认值。对于 GET 请求它试图在缓存中匹配，然后发送到网络。如果在缓存中匹配成功，它将异步更新缓存，以供下次使用。
默认值？请理清示例代码的逻辑

然后发送到网络？

2022-08-25 00:44 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/fetchevent/index.md
> +fetch 事件对非 GET 请求使用浏览器默认值。对于 GET 请求它试图在缓存中匹配，然后发送到网络。如果在缓存中匹配成功，它将异步更新缓存，以供下次使用。
respoondWith 是响应客户端，你可以看 deno 的示例，也许 发送到网络 不太好，或许使用 响应客户端，但是不够准确

2022-08-25 00:48 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/fetchevent/index.md
> +  - : 一个 {{jsxref("Promise")}}，可能兑现为 {{domxref("Response")}} 或 `undefined`，如果该 fetch 没有导航或者 [navigation preload](/zh-CN/docs/Web/API/NavigationPreloadManager) 没有触发，则是 undefined。
<https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/preloadResponse>

* navigation preload 触发之后，才会兑现成响应，否则都是 undefined

2022-08-25 00:50 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/fetchevent/index.md
> +fetch 事件对非 GET 请求使用浏览器默认值。对于 GET 请求它试图在缓存中匹配，然后发送到网络。如果在缓存中匹配成功，它将异步更新缓存，以供下次使用。
<https://doc.deno.land/deno/stable/~/Deno.serveHttp>

2022-08-25 00:56 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/index.md
> +  - : 一个 {{jsxref("Promise")}}，可能兑现为 {{domxref("Response")}} 或 `undefined`，如果该 fetch 没有导航或者 [navigation preload](/zh-CN/docs/Web/API/NavigationPreloadManager) 没有触发，则是 undefined。
- `is not a navigation`
- `navigation preload is not enabled`

2022-08-25 00:57 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/index.md
> +fetch 事件对非 GET 请求使用浏览器默认值。对于 GET 请求它试图在缓存中匹配，然后发送到网络。如果在缓存中匹配成功，它将异步更新缓存，以供下次使用。
`fall back` 并不是“然后发送”的意思，我在你的另一个pr中有说明

2022-08-25 01:06 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/fetchevent/index.md
> +fetch 事件对非 GET 请求使用浏览器默认值。对于 GET 请求它试图在缓存中匹配，然后发送到网络。如果在缓存中匹配成功，它将异步更新缓存，以供下次使用。
可是 `回落`？这怎么翻译？

2022-08-25 01:07 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/fetchevent/index.md
> +  - : 一个 {{jsxref("Promise")}}，可能兑现为 {{domxref("Response")}} 或 `undefined`，如果该 fetch 没有导航或者 [navigation preload](/zh-CN/docs/Web/API/NavigationPreloadManager) 没有触发，则是 undefined。
ok, 这个是不会返回 promise

2022-08-25 01:07 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/index.md
> +fetch 事件对非 GET 请求使用浏览器默认值。对于 GET 请求它试图在缓存中匹配，然后发送到网络。如果在缓存中匹配成功，它将异步更新缓存，以供下次使用。
回落意味着：缓存未命中

2022-08-25 01:09 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/index.md
> +fetch 事件对非 GET 请求使用浏览器默认值。对于 GET 请求它试图在缓存中匹配，然后发送到网络。如果在缓存中匹配成功，它将异步更新缓存，以供下次使用。
对于不清楚的翻译，请多查找资料，并对应英文文档的上下文来理解语义，我没目前没有足够的时间来为你纠正所有的错误

2022-08-25 01:14 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/index.md
> +  - : 延长事件的生命周期。用于通知浏览器任务超出响应回复时间，仍然在解决，例如流和缓存。
再修改一下吧

2022-08-25 01:27 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/index.md
> +_从它的祖先 {{domxref("Event")}} 继承熟悉_。
```suggestion
_从它的祖先 {{domxref("Event")}} 继承属性_。
```

2022-08-25 01:27 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/index.md
> +fetch 事件对非 GET 请求使用浏览器默认值。对于 GET 请求它试图在缓存中匹配，如果缓存中没有匹配，则使用网络中的。如果在缓存中匹配成功，它将异步更新缓存，以供下次使用。
```suggestion
fetch 事件对非 GET 请求使用浏览器默认值。对于 GET 请求它试图在缓存中匹配，如果缓存中没有匹配，则回退到网络请求。如果在缓存中匹配成功，它将异步更新缓存，以供下次使用。
```

2022-08-25 01:31 UTC, merged