zh-cn translate fetchevent request
mdn/translated-content pull request #7992
Opened 2022-08-25 04:58 UTC by Jack-Zhang-1314

2022-08-25 05:18 UTC, yin1999 requested changes

2022-08-25 05:18 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/request/index.md
> +来自 [service worker fetch 示例](https://github.com/GoogleChrome/samples/blob/gh-pages/service-worker/prefetch/service-worker.js)的代码片段（[fetch 示例的在线演示](https://googlechrome.github.io/samples/service-worke
> 该 promise 会用 {{domxref("Cache")}} 中第一个匹配的 URL 请求进行解析。如果没有匹配，代码将从网络获取一个响应。

resolve在promise中不是解析的意思，麻烦对照英文原文进行翻译

2022-08-25 05:18 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/request/index.md
> +该代码还会处理 {{domxref("fetch()")}} 操作抛出的异常。注意，HTTP 错误响应（例如 404）不会抛出异常。他将返回一个拥有适当错误代码集的正常的响应对象。
```suggestion
该代码还会处理 {{domxref("fetch()")}} 操作抛出的异常。注意，HTTP 错误响应（例如 404）不会抛出异常。它将返回一个拥有适当错误代码集的正常的响应对象。
```

2022-08-25 05:18 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/request/index.md
> +- [使用 Service Workers](/zh-CN/docs/Web/API/Service_Worker_API/Using_Service_Workers)
```suggestion
- [使用 Service Worker](/zh-CN/docs/Web/API/Service_Worker_API/Using_Service_Workers)
```

2022-08-25 05:59 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/fetchevent/request/index.md
> +来自 [service worker fetch 示例](https://github.com/GoogleChrome/samples/blob/gh-pages/service-worker/prefetch/service-worker.js)的代码片段（[fetch 示例的在线演示](https://googlechrome.github.io/samples/service-worke
待敲定？

2022-08-25 06:07 UTC, yin1999 requested changes

2022-08-25 06:07 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/request/index.md
> +来自 [service worker fetch 示例](https://github.com/GoogleChrome/samples/blob/gh-pages/service-worker/prefetch/service-worker.js)的代码片段（[fetch 示例的在线演示](https://googlechrome.github.io/samples/service-worke
MDN 关于 promise 的文档对这些专业术语都有说明，如果不熟悉，建议先从更简单的文档入手，并学习与这些技术有关的专业术语，然后再尝试翻译带有这些专业术语的文档

<https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise#描述>

2022-08-25 06:42 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/fetchevent/request/index.md
> +来自 [service worker fetch 示例](https://github.com/GoogleChrome/samples/blob/gh-pages/service-worker/prefetch/service-worker.js)的代码片段（[fetch 示例的在线演示](https://googlechrome.github.io/samples/service-worke
resolved，称为 已决议，但是这句话 resolve 应该是个动词，并没有敲定状态，会不会敲定好一些

2022-08-25 06:45 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/fetchevent/request/index.md
> +来自 [service worker fetch 示例](https://github.com/GoogleChrome/samples/blob/gh-pages/service-worker/prefetch/service-worker.js)的代码片段（[fetch 示例的在线演示](https://googlechrome.github.io/samples/service-worke
或者说它的状态由...url决议。

2022-08-25 07:41 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/request/index.md
> +来自 [service worker fetch 示例](https://github.com/GoogleChrome/samples/blob/gh-pages/service-worker/prefetch/service-worker.js)的代码片段（[fetch 示例的在线演示](https://googlechrome.github.io/samples/service-worke
请使用“兑现”

2022-08-25 07:45 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/fetchevent/request/index.md
> +来自 [service worker fetch 示例](https://github.com/GoogleChrome/samples/blob/gh-pages/service-worker/prefetch/service-worker.js)的代码片段（[fetch 示例的在线演示](https://googlechrome.github.io/samples/service-worke
😅

2022-08-26 04:59 UTC, yin1999 requested changes

2022-08-26 04:59 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/request/index.md
> +这个属性是非空的（自从 Firefox 46 版本开始）。如果一个请求不是由其它方式提供的，构造函数的`初始的`对象必须包含一个请求（参见 {{domxref("FetchEvent.FetchEvent", "FetchEvent()")}}）。
```suggestion
这个属性是非空的（自从 Firefox 46 版本开始）。如果一个请求不是由其它方式提供的，构造函数的 `init` 对象必须包含一个请求（参见 {{domxref("FetchEvent.FetchEvent", "FetchEvent()")}}）。
```

2022-08-26 04:59 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/request/index.md
> +来自 [service worker fetch 示例](https://github.com/GoogleChrome/samples/blob/gh-pages/service-worker/prefetch/service-worker.js)的代码片段（[fetch 示例的在线演示](https://googlechrome.github.io/samples/service-worke
```suggestion
来自 [service worker fetch 示例](https://github.com/GoogleChrome/samples/blob/gh-pages/service-worker/prefetch/service-worker.js)的代码片段（[fetch 示例的在线演示](https://googlechrome.github.io/samples/service-worker/prefetch/)）。{{domxref("ServiceWorkerGlobalScope.fetch_event", "onfetch")}} 事件处理程序监听 `fetch` 事件。当被触发时，将最终会传递给受控页面的 promise 传递给 {{domxref("FetchEvent.respondWith", "FetchEvent.respondWith()")}}。该 promise 会用 {{domxref("Cache")}} 中第一个匹配的 URL 请求来兑现。如果没有匹配，代码将从网络获取响应。
```

2022-08-26 05:41 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/fetchevent/request/index.md
> +这个属性是非空的（自从 Firefox 46 版本开始）。如果一个请求不是由其它方式提供的，构造函数的`初始的`对象必须包含一个请求（参见 {{domxref("FetchEvent.FetchEvent", "FetchEvent()")}}）。
FetchEvent 并没有在使用 init 指代参数中的对象，似乎更强调初始化的对象需要包含这个请求

2022-08-26 05:55 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/request/index.md
> +这个属性是非空的（自从 Firefox 46 版本开始）。如果一个请求不是由其它方式提供的，构造函数的`初始的`对象必须包含一个请求（参见 {{domxref("FetchEvent.FetchEvent", "FetchEvent()")}}）。
FetchEvent 的 `request` 对象来自 `fetch()`，它是一个由 `fetch()` 触发的事件（`fetch()` 是有 `init` 对象的）：

![image](https://user-images.githubusercontent.com/15844309/186831998-26c2f319-9a34-45c1-a952-fb7993c9d830.png)

2022-08-26 06:25 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/fetchevent/request/index.md
> +这个属性是非空的（自从 Firefox 46 版本开始）。如果一个请求不是由其它方式提供的，构造函数的`初始的`对象必须包含一个请求（参见 {{domxref("FetchEvent.FetchEvent", "FetchEvent()")}}）。
但是 fetch 的第二个参数并不会包含 request

2022-08-26 06:52 UTC, yin1999 commented on files/zh-cn/web/api/fetchevent/request/index.md
> +这个属性是非空的（自从 Firefox 46 版本开始）。如果一个请求不是由其它方式提供的，构造函数的`初始的`对象必须包含一个请求（参见 {{domxref("FetchEvent.FetchEvent", "FetchEvent()")}}）。
mdn/content 已合并了 PR mdn/content#19986，我已更新建议

2022-08-26 07:01 UTC, merged