new translation: forms/html5_input_types
mdn/translated-content pull request #8028
Opened 2022-08-26 11:58 UTC by jasonren0403

2022-08-26 12:55 UTC, jasonren0403 commented on files/zh-cn/learn/forms/html5_input_types/index.md
> +### 高级技巧
统一一下类似地方的翻译
```suggestion
### 进阶内容
```

2022-08-26 22:55 UTC, yin1999 commented on files/zh-cn/learn/forms/html5_input_types/index.md
> +### 高级技巧
Please go ahead

2022-08-26 23:30 UTC, yin1999 requested changes
Some suggestions, you can apply changes in code review

2022-08-26 23:30 UTC, yin1999 commented on files/zh-cn/learn/forms/html5_input_types/index.md
> +当使用了这种 {{htmlattrxref("type","input")}} 类型时，用户需要输入一个合法的电子邮件地址，任何其他输入都会使得在表单提交时浏览器显示错误信息。你可以在下述截图上看到这个行为：
```suggestion
当使用了这种 {{htmlattrxref("type","input")}} 类型时，用户需要输入一个合法的电子邮件地址，任何其他输入都会使得浏览器在表单提交时显示错误信息。你可以在下面的截图中看到这个行为：
```

2022-08-26 23:30 UTC, yin1999 commented on files/zh-cn/learn/forms/html5_input_types/index.md
> +这是使用这些较新的 input 类型的另一个很好的理由——可以为这些设备的用户改善了用户体验。
```suggestion
这是使用这些较新的 input 类型的另一个很好的理由——可以为这些设备的用户改善用户体验。
```

2022-08-26 23:30 UTC, yin1999 commented on files/zh-cn/learn/forms/html5_input_types/index.md
> +正如你在上面看到的，`email` 与其他较新的 `input` 类型一样，提供了内置的*客户端*错误验证，在数据被发送到服务器之前由浏览器执行。它*是*引导用户准确填写表格的一个有用的辅助工具，可以节省时间：立即知道你的数据不正确是很有用的，而不是要等待服务器的往返。
```suggestion
正如你在上面看到的，`email` 与其他较新的 `input` 类型一样，提供了内置的*客户端*错误验证，在数据被发送到服务器之前由浏览器执行。它*是*引导用户准确填写表格的一个有用的辅助工具，可以节省时间：可以立即知道你的数据是否正确，而不需要等待服务器返回结果。
```

2022-08-26 23:30 UTC, yin1999 commented on files/zh-cn/learn/forms/html5_input_types/index.md
> +但它*不应该*被认为是一种详尽的安全措施！你的应用程序始终应该在*服务器端*和客户端对任何表单提交的数据进行安全检查，因为客户端验证太容易被关闭了，所以恶意用户仍然可以很容易地将坏数据发送到你的服务器。请参阅[网站安全](/zh-CN/docs/Learn/Server-side/First_steps/Website_security)来了解*可能*会发生什么。实现服务端认证超出了本模块的范围
`抱熟于心`好像不是一个成语/俗语：

```suggestion
但它*不应该*被认为是一种详尽的安全措施！你的应用程序始终应该在*服务器端*和客户端对任何表单提交的数据进行安全检查，因为客户端验证太容易被关闭了，所以恶意用户仍然可以很容易地将坏数据发送到你的服务器。请参阅[网站安全](/zh-CN/docs/Learn/Server-side/First_steps/Website_security)来了解*可能*会发生什么。实现服务端认证超出了本章的范围，但你应该熟稔于心。
```

2022-08-26 23:30 UTC, yin1999 commented on files/zh-cn/learn/forms/html5_input_types/index.md
> +注意，在默认限制条件下，`a@b` 也是一个合法的电子邮件地址，因为 `email` input 类型默认也允许内部网的电子邮件地址（intranet email addresses）。为了实现不同的认证行为，你可以使用 [`pattern`](/zh-CN/docs/Web/HTML/Attributes/pattern) 属性，而且可以自定义错误信息；我们将在[客户端表单认证](/zh-CN
```suggestion
注意，在默认限制条件下，`a@b` 也是一个合法的电子邮件地址，因为 `email` input 类型默认也允许内部网络的电子邮件地址。为了实现不同的验证行为，你可以使用 [`pattern`](/zh-CN/docs/Web/HTML/Attributes/pattern) 属性，而且可以自定义错误信息；我们将在[客户端表单认证](/zh-CN/docs/Learn/Forms/Form_validation)文章中进一步说明如何使用这些功能。
```

2022-08-26 23:30 UTC, yin1999 commented on files/zh-cn/learn/forms/html5_input_types/index.md
> +`text` 域和 `search` 域的主要区别是浏览器赋予它们的外观显示。通常情况下，`search` 域拥有圆角边框，有时会显示“Ⓧ”标志，当点击它时会清除输入框。另外，在动态键盘设备上，键盘的回车键会显示“**search**”，或显示为放大镜图标。
```suggestion
`text` 字段和 `search` 字段的主要区别是浏览器赋予它们的外观显示。通常情况下，`search` 字段拥有圆角边框，有时会显示“Ⓧ”标志，当点击它时会清除输入框。另外，在动态键盘设备上，键盘的回车键会显示“**search**”，或显示为放大镜图标。
```

2022-08-26 23:30 UTC, yin1999 commented on files/zh-cn/learn/forms/html5_input_types/index.md
> +下面的截图显示了 macOS 上的 Firefox 71、Safari 13 和 Chrome 79 和 Windows 10 上的 Edge 18 和 Chrome 79 的非空查询域，请注意，清除图标仅当在输入框中存在值得时候才会显示，且与 Safari 不同的是，仅当聚焦状态时才会显示此图标。
```suggestion
下面的截图显示了 macOS 上的 Firefox 71、Safari 13 和 Chrome 79，以及 Windows 10 上的 Edge 18 和 Chrome 79 的非空查询字段，请注意，清除图标仅当在输入框中存在值得时候才会显示，且与 Safari 不同的是，仅当聚焦状态时才会显示此图标。
```

2022-08-26 23:30 UTC, yin1999 commented on files/zh-cn/learn/forms/html5_input_types/index.md
> +另外一个值得提示的特性是，`search` 域的值可以自动地保存下来，在同一网站的自动完成框中复用输入，这样的特性倾向于在大多数现代浏览器中自动进行。
```suggestion
另外一个值得提示的特性是，`search` 字段的值可以自动地保存下来，在同一网站的自动完成框中复用输入，这样的特性倾向于在大多数现代浏览器中自动进行。
```

2022-08-26 23:30 UTC, yin1999 commented on files/zh-cn/learn/forms/html5_input_types/index.md
> +在 {{htmlattrxref("type","input")}} 属性值中使用 `url`，即可创建一个用于输入网址的文本域：
```suggestion
在 {{htmlattrxref("type","input")}} 属性值中使用 `url`，即可创建一个用于输入网址的文本字段：
```

2022-08-26 23:30 UTC, yin1999 commented on files/zh-cn/learn/forms/html5_input_types/index.md
> +HTML 日期控件可用于处理这种特定的数据，提供日历部件并使数据统一。
部件、组件、控件，请同一使用“控件”，MDN 英文文档正在将所有的“widget”改为“control”：

```suggestion
HTML 日期控件可用于处理这种特定的数据，提供日历控件并使数据统一。
```

2022-08-26 23:30 UTC, yin1999 commented on files/zh-cn/learn/forms/html5_input_types/index.md
> +[`<input type="datetime-local">`](/zh-CN/docs/Web/HTML/Element/Input/datetime-local) 创建了显示和选择一个没有特定时区信息的日期和时间的组件。
```suggestion
[`<input type="datetime-local">`](/zh-CN/docs/Web/HTML/Element/Input/datetime-local) 创建了显示和选择一个没有特定时区信息的日期和时间的控件。
```

2022-08-26 23:30 UTC, yin1999 commented on files/zh-cn/learn/forms/html5_input_types/index.md
> +[`<input type="month">`](/zh-CN/docs/Web/HTML/Element/Input/month) 创建了显示和选择带有年份信息的某个月的组件。
```suggestion
[`<input type="month">`](/zh-CN/docs/Web/HTML/Element/Input/month) 创建了显示和选择带有年份信息的某个月的控件。
```

2022-08-26 23:30 UTC, yin1999 commented on files/zh-cn/learn/forms/html5_input_types/index.md
> +[`<input type="time">`](/zh-CN/docs/Web/HTML/Element/Input/time) 创建了显示和选择时间的组件。时间可能会以 *12 小时制*显示，但一定会以 *24 小时制*形式返回。
```suggestion
[`<input type="time">`](/zh-CN/docs/Web/HTML/Element/Input/time) 创建了显示和选择时间的控件。时间可能会以 *12 小时制*显示，但一定会以 *24 小时制*形式返回。
```

2022-08-26 23:30 UTC, yin1999 commented on files/zh-cn/learn/forms/html5_input_types/index.md
> +[`<input type="week">`](/zh-CN/docs/Web/HTML/Element/Input/week) 创建了显示和选择一年中特定编号周的组件。
```suggestion
[`<input type="week">`](/zh-CN/docs/Web/HTML/Element/Input/week) 创建了显示和选择一年中特定编号周的控件。
```

2022-08-26 23:30 UTC, yin1999 commented on files/zh-cn/learn/forms/html5_input_types/index.md
> +所有的日期和时间组件总可以由 [`min`](/zh-CN/docs/Web/HTML/Attributes/min) 和 [`max`](/zh-CN/docs/Web/HTML/Attributes/max) 属性控制，可由 [`step`](/zh-CN/docs/Web/HTML/Attributes/step) 属性进一步做控制，具体值随着 input 类型的不同而产生变化。
```suggestion
所有的日期和时间控件总可以由 [`min`](/zh-CN/docs/Web/HTML/Attributes/min) 和 [`max`](/zh-CN/docs/Web/HTML/Attributes/max) 属性控制，可由 [`step`](/zh-CN/docs/Web/HTML/Attributes/step) 属性进一步做控制，具体值随着 input 类型的不同而产生变化。
```

2022-08-26 23:30 UTC, yin1999 commented on files/zh-cn/learn/forms/html5_input_types/index.md
> +在支持的情况下，点击一个颜色控件将倾向于显示操作系统的默认颜色选择功能，以便你真正做出选择。以下是在 macOS 的 Firefox 浏览器上拍摄的屏幕截图，提供了一个例子：
```suggestion
在支持的情况下，点击一个颜色控件将倾向于显示操作系统的默认颜色选择功能，以便你真正做出选择。以下是在 macOS 上 Firefox 浏览器的屏幕截图，提供了一个例子：
```

2022-08-26 23:30 UTC, yin1999 commented on files/zh-cn/learn/forms/html5_input_types/index.md
> +这里有一个现场例子供你尝试：
```suggestion
这里有一个在线示例供你尝试：
```

2022-08-26 23:30 UTC, yin1999 commented on files/zh-cn/learn/forms/html5_input_types/index.md
> +- [表单部件兼容性列表](/zh-CN/docs/Learn/Forms/Property_compatibility_table_for_form_controls)
```suggestion
- [表单控件兼容性列表](/zh-CN/docs/Learn/Forms/Property_compatibility_table_for_form_controls)
```

2022-08-27 00:06 UTC, yin1999 approved these changes
Thanks a lot

2022-08-27 00:06 UTC, merged