new translation: forms/other_form_controls
mdn/translated-content pull request #8029
Opened 2022-08-26 12:03 UTC by jasonren0403

2022-08-26 12:53 UTC, jasonren0403 commented on files/zh-cn/learn/forms/other_form_controls/index.md
> +### 高级技巧
跟其他地方的翻译统一一下：
```suggestion
### 进阶内容
```

2022-08-27 00:13 UTC, yin1999 requested changes

2022-08-27 00:13 UTC, yin1999 commented on files/zh-cn/learn/forms/other_form_controls/index.md
> +现在我们来具体看看非 `<input>` 表单部件的功能，从下拉列表菜单（drop-down list）、多行文本域（multi-line text field）到其他有用的表单功能，如我们在前一篇文章看到的 {{htmlelement('output')}} 元素和进度条（progress bar）元素。
We'd better use `表单控件` instead of `表单部件`

2022-08-27 02:34 UTC, yin1999 commented on files/zh-cn/learn/forms/other_form_controls/index.md
> +  - : 指定文本部件的可见行数。这实际上是起始高度，因为它可以通过调整 `<textarea>` 的大小来改变，也可以用CSS重写。如果没有指定，默认值是2。
```suggestion
  - : 指定文本控件的可见宽度（列），单位为字符的宽度。这实际上是起始宽度，因为它可以通过调整 `<textarea>` 的大小来改变，也可以用 CSS 重写。如果没有指定，默认值是 20。
- {{htmlattrxref("rows","textarea")}}
  - : 指定文本控件的可见行数。这实际上是起始高度，因为它可以通过调整 `<textarea>` 的大小来改变，也可以用 CSS 重写。如果没有指定，默认值是 2。
```

2022-08-27 02:34 UTC, yin1999 commented on files/zh-cn/learn/forms/other_form_controls/index.md
> +## 下拉部件
```suggestion
## 下拉控件
```

2022-08-27 02:34 UTC, yin1999 commented on files/zh-cn/learn/forms/other_form_controls/index.md
> +下拉菜单是一种简单地让用户从许多不同选项中进行选择的部件，不占用用户界面太多空间。HTML 有两种下拉内容：一种是**选择框**、另外一种是**自动补全框**。这两种情况下的交互是相同的——一旦被激活，浏览器就会显示可供用户选择的值的列表。
```suggestion
下拉菜单是一种简单地让用户从许多不同选项中进行选择的控件，不占用用户界面太多空间。HTML 有两种下拉内容：一种是**选择框**、另外一种是**自动补全框**。这两种情况下的交互是相同的——一旦被激活，浏览器就会显示可供用户选择的值的列表。
```

2022-08-27 02:34 UTC, yin1999 commented on files/zh-cn/learn/forms/other_form_controls/index.md
> +> **备注：** 在多选选择框的情况下，你会注意到选择框不再以下拉内容的形式显示数值——相反，所有的值都会一次性显示在一个列表中，可选的 [`size`](/zh-CN/docs/Web/HTML/Attributes/size) 属性决定了部件的高度。
```suggestion
> **备注：** 在多选选择框的情况下，你会注意到选择框不再以下拉内容的形式显示数值——相反，所有的值都会一次性显示在一个列表中，可选的 [`size`](/zh-CN/docs/Web/HTML/Attributes/size) 属性决定了控件的高度。
```

2022-08-27 02:34 UTC, yin1999 commented on files/zh-cn/learn/forms/other_form_controls/index.md
> +### 自动补充框
```suggestion
### 自动补全框
```

2022-08-27 02:34 UTC, yin1999 commented on files/zh-cn/learn/forms/other_form_controls/index.md
> +你可以通过 {{HTMLElement("datalist")}} 元素中的一些显示的 {{HTMLElement("option")}} 子元素为表单项提供推荐的自动完成值。`<datalist>` 元素需要指定一个 `id`。
```suggestion
你可以通过 {{HTMLElement("datalist")}} 元素中的一些显示的 {{HTMLElement("option")}} 子元素为表单项提供推荐的自动补全值。`<datalist>` 元素需要指定一个 `id`。
```

2022-08-27 02:34 UTC, yin1999 commented on files/zh-cn/learn/forms/other_form_controls/index.md
> +一旦数据列表与表单控件相关联，它的选项就会被用来自动完成用户输入的文本；通常，它以下拉框的形式呈现给用户，列出他们输入内容的可能匹配。
```suggestion
一旦数据列表与表单控件相关联，它的选项就会被用来自动补全用户输入的文本；通常，它以下拉框的形式呈现给用户，列出他们输入内容的可能匹配。
```

2022-08-27 03:17 UTC, jasonren0403 commented on files/zh-cn/learn/forms/other_form_controls/index.md
> +一个进度条表示一个随时间变化的竖直，最高可以达到 {{htmlattrxref("max","progress")}} 属性所指定的最大值。这样的条是使用 {{ HTMLElement("progress")}} 元素创建出来的。
fix typo
```suggestion
进度条表示一个随时间变化的数值，最高可以达到 {{htmlattrxref("max","progress")}} 属性所指定的最大值。这样的条是使用 {{ HTMLElement("progress")}} 元素创建出来的。
```

2022-08-27 03:19 UTC, jasonren0403 commented on files/zh-cn/learn/forms/other_form_controls/index.md
> +- 如果当前值位于最差范围，则计量器为红色。
优化表达
```suggestion
- 如果当前值位于首选范围，则计量器显示为绿色。
- 如果当前值位于平均范围，则计量器显示为黄色。
- 如果当前值位于最差范围，则计量器显示为红色。
```

2022-08-27 05:51 UTC, yin1999 approved these changes

2022-08-27 05:51 UTC, yin1999 commented on files/zh-cn/learn/forms/other_form_controls/index.md
> +`<textarea>` 也需要关闭标签，其中要包含的默认文字需要放在开闭标签之间。作为对比，{{HTMLElement("input")}} 是不包含关闭标签的空元素，它的默认值应该在 [`value`](/zh-CN/docs/Web/HTML/Attributes/value) 属性中指定。
```suggestion
`<textarea>` 也需要关闭标签，其中要包含的默认文字需要放在开闭标签之间。作为对比，{{HTMLElement("input")}} 是不包含关闭标签的空元素，它的默认值应该在 [`value`](/zh-CN/docs/Web/HTML/Element/input#value) 属性中指定。
```

mdn/content#20017

2022-08-27 06:06 UTC, merged