Update Learn/Form/html_forms_in_legacy_browsers
mdn/translated-content pull request #8030
Opened 2022-08-26 12:44 UTC by jasonren0403

2022-08-26 23:59 UTC, yin1999 requested changes

2022-08-26 23:59 UTC, yin1999 commented on files/zh-cn/learn/forms/html_forms_in_legacy_browsers/index.md
> +实际上，最重要的事情是阅读那些浏览器的文档，并尝试理解通用的（解决）模式。如果你在 [MDN](/) 上阅读了本篇文档，这将是个良好的开始，只需要检查你想用的元素或 DOM 接口的支持情况即可。MDN 有一个关于包含 HTML 中可用的元素、属性或 API 的兼容表单可查。
```suggestion
实际上，最重要的事情是阅读那些浏览器的文档，并尝试理解通用的（解决）模式。如果你在 [MDN](/) 上阅读了本篇文档，这将是个良好的开始，只需要检查你想用的元素或 DOM 接口的支持情况即可。对于大部分 HTML 中可用的元素、属性或 API，MDN 提供了兼容性表格以供查询。
```

2022-08-26 23:59 UTC, yin1999 commented on files/zh-cn/learn/forms/html_forms_in_legacy_browsers/index.md
> +由于 [HTML 表单](/zh-CN/docs/Learn/Forms) 包含了复杂的交互，有一个非常重要的规则：保持简单化，也常称做“[KISS(keep it as simple as possible) 准则](https://en.wikipedia.org/wiki/KISS_principle)”。有很多情况下，我们希望表单 "更漂亮 "或 "具有高级功能"，但构建高效的 HTML
```suggestion
由于 [HTML 表单](/zh-CN/docs/Learn/Forms)包含了复杂的交互，有一个非常重要的规则：保持简单化，也常称做“[KISS 原则](ttps://zh.wikipedia.org/wiki/KISS原则)”。有很多情况下，我们希望表单“更漂亮”或“具有高级功能”，但构建高效的 HTML 表单并不是一个设计或技术问题，而是一个简单直观且便利的用户互动问题。记得花时间读一下这篇文章 [forms usability on UX For The Masses](http://www.uxforthemasses.com/forms-usability/)。
```

2022-08-26 23:59 UTC, yin1999 commented on files/zh-cn/learn/forms/html_forms_in_legacy_browsers/index.md
>  ### 优雅地降级 (Graceful degradation) 是 web 开发者最好的朋友
```suggestion
### 优雅降级 (Graceful degradation) 是 web 开发者最好的朋友
```

2022-08-26 23:59 UTC, yin1999 commented on files/zh-cn/learn/forms/html_forms_in_legacy_browsers/index.md
> +[Graceful degradation and progressive enhancement](https://www.sitepoint.com/progressive-enhancement-graceful-degradation-choice/) 是一个开发模式，它允许你通过同时支持多种浏览器来构建优秀内容。当你为现代浏览器构建内容时，你想确保它能在旧式浏览器中以某种方式工作，这就
```suggestion
[优雅降级和渐进增强](https://www.sitepoint.com/progressive-enhancement-graceful-degradation-choice/)是一种开发模式，它允许你通过同时支持多种浏览器来构建优秀内容。当你为现代浏览器构建内容时，你想确保它能在旧式浏览器中以某种方式工作，这就是优雅降级（graceful degradation）。
```

2022-08-26 23:59 UTC, yin1999 commented on files/zh-cn/learn/forms/html_forms_in_legacy_browsers/index.md
> +### 让我们过一遍 CSS
```suggestion
### 摆脱 CSS
```

2022-08-26 23:59 UTC, yin1999 commented on files/zh-cn/learn/forms/html_forms_in_legacy_browsers/index.md
> +总而言之，当涉及到表单控件小部件的样式时，用 CSS 为它们设计样式的副作用可能是不可预测的。所以不要这样做。正如从这篇[表单控件兼容性列表](/zh-CN/docs/Property_compatibility_table_for_form_widgets) 中所看到的复杂性那样，它非常的困难。即使仍然可以对文本元素（如大小、字体颜色等）进行一些调整，但那样做会有副作用。最好的办法还是不要美化
```suggestion
总而言之，当涉及到表单控件小部件的样式时，用 CSS 为它们设计样式的副作用可能是不可预测的。所以不要这样做。正如从这篇[表单控件的 CSS 属性兼容性表格](/zh-CN/docs/Property_compatibility_table_for_form_widgets)中所看到的复杂性那样，它非常的困难。即使仍然可以对文本元素（如大小、字体颜色等）进行一些调整，但那样做会有副作用。最好的办法还是不要美化 HTML 表单小组件。但你仍然可以将样式应用到表单周围的项目上。如果你是一个专业人士，并且你的客户需要那么做，在这种情况下，你可以研究一些硬技能，如[使用 JavaScript 重建组件](/zh-CN/docs/Learn/Forms/How_to_build_custom_form_controls)。但在那种情况下，最好还是毫不犹豫的[让客户收回这些愚蠢的决定](http://www.smashingmagazine.com/2011/11/03/but-the-client-wants-ie-6-support/)。
```

2022-08-26 23:59 UTC, yin1999 commented on files/zh-cn/learn/forms/html_forms_in_legacy_browsers/index.md
> +## 功能检测和模拟 (polyfills)
```suggestion
## 特性检测和 polyfill
```

2022-08-26 23:59 UTC, yin1999 commented on files/zh-cn/learn/forms/html_forms_in_legacy_browsers/index.md
> +CSS 和 JavaScript 是了不起的技术，但重要的是确保不会破坏传统的浏览器。在使用你的目标浏览器不完全支持的功能之前，你应该进行功能检测。
```suggestion
CSS 和 JavaScript 是了不起的技术，但重要的是确保不会破坏传统的浏览器。在使用你的目标浏览器不完全支持的特性之前，你应该进行特性检测。
```

2022-08-26 23:59 UTC, yin1999 commented on files/zh-cn/learn/forms/html_forms_in_legacy_browsers/index.md
> +### CSS 特征检测
```suggestion
### CSS 特性检测
```

2022-08-26 23:59 UTC, yin1999 commented on files/zh-cn/learn/forms/html_forms_in_legacy_browsers/index.md
> +在设计一个表单控件的样式之前，你可以使用 {{cssxref('@supports')}} 检查一下浏览器是否支持你打算使用的功能：
```suggestion
在设计一个表单控件的样式之前，你可以使用 {{cssxref('@supports')}} 检查一下浏览器是否支持你打算使用的特性：
```

2022-08-26 23:59 UTC, yin1999 commented on files/zh-cn/learn/forms/html_forms_in_legacy_browsers/index.md
> +有很多情形，好的 “polyfill” 能通过提供缺少的 API 以提供帮助。一个 [polyfill](http://remysharp.com/2010/10/08/what-is-a-polyfill/) 是一些用于填补旧式浏览器中缺失功能的 JavaScript 脚本。虽然它们可以用来改善对任何功能的支持，但对 JavaScript 使用它们比对 CSS 或 HTML 使用风险要小；有很
"Unobtrusive" 的翻译不一致，中文双引号两边无需空格：

```suggestion
有很多情形，好的“polyfill”能通过提供缺少的 API 以提供帮助。一个 [polyfill](http://remysharp.com/2010/10/08/what-is-a-polyfill/) 是一些用于填补旧式浏览器中缺失功能的 JavaScript 脚本。虽然它们可以用来改善对任何功能的支持，但对 JavaScript 使用它们比对 CSS 或 HTML 使用风险要小；有很多情况下 JavaScript 会崩溃（网络问题、脚本冲突等）。但是对于 JavaScript 来说，如果你在工作中考虑到不引人注意的 JavaScript，如果 polyfill 缺失，那也没什么大不了的。
```

2022-08-26 23:59 UTC, yin1999 commented on files/zh-cn/learn/forms/html_forms_in_legacy_browsers/index.md
> +> **备注：** Modernizr 还有其他很棒的功能可以帮助您处理 unobtrusive JavaScript 和优雅的降级技术。请阅读 [Modernizr 文档](https://modernizr.com/docs/)。
同样地，“unobtrusive”

2022-08-26 23:59 UTC, yin1999 commented on files/zh-cn/learn/forms/html_forms_in_legacy_browsers/index.md
>  original_slug: Learn/HTML/Forms/HTML_forms_in_legacy_browsers
```suggestion
```

2022-08-26 23:59 UTC, yin1999 commented on files/zh-cn/learn/forms/html_forms_in_legacy_browsers/index.md
> +- [如何构造 web 表单](/zh-CN/docs/Learn/Forms/How_to_structure_a_web_form)
```suggestion
- [如何构建 web 表单](/zh-CN/docs/Learn/Forms/How_to_structure_a_web_form)
```

2022-08-26 23:59 UTC, yin1999 commented on files/zh-cn/learn/forms/styling_web_forms/index.md
> +- [如何构造 web 表单](/zh-CN/docs/Learn/Forms/How_to_structure_a_web_form)
```suggestion
- [如何构建 web 表单](/zh-CN/docs/Learn/Forms/How_to_structure_a_web_form)
```

2022-08-27 01:57 UTC, jasonren0403 commented on files/zh-cn/learn/forms/html_forms_in_legacy_browsers/index.md
> +由于 [HTML 表单](/zh-CN/docs/Learn/Forms)包含了复杂的交互，有一个非常重要的规则：保持简单化，也常称做“[KISS 原则](ttps://zh.wikipedia.org/wiki/KISS原则)”。有很多情况下，我们希望表单“更漂亮”或“具有高级功能”，但构建高效的 HTML 表单并不是一个设计或技术问题，而是一个简单直观且便利的用户互动问题。记得花时间读一下这
```suggestion
由于 [HTML 表单](/zh-CN/docs/Learn/Forms)包含了复杂的交互，有一个非常重要的规则：保持简单化，也常称做“[KISS 原则](https://zh.wikipedia.org/wiki/KISS原则)”。有很多情况下，我们希望表单“更漂亮”或“具有高级功能”，但构建高效的 HTML 表单并不是一个设计或技术问题，而是一个简单直观且便利的用户互动问题。记得花时间读一下这篇文章 [forms usability on UX For The Masses](http://www.uxforthemasses.com/forms-usability/)。
```

2022-08-29 12:04 UTC, jasonren0403 commented
有点不太确定 `unobtrusive JavaScript` 该翻成啥。。

2022-08-31 02:08 UTC, yin1999 approved these changes
LGTM, thanks!

2022-08-31 02:10 UTC, merged