fix:  inapropriate translation with "前端框架簡介"
mdn/translated-content pull request #8033
Opened 2022-08-26 15:31 UTC by DevRickLin

#7994

2022-08-29 17:27 UTC, irvin requested changes
請參考

2022-08-29 17:27 UTC, irvin commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.md
> +在 JavaScript 誕生的 1996 年，它只有為當時由靜態文檔組成的網頁提供交互性和興奮感的作用。但之後網路漸漸從*拿來看*，變成*拿來用*了。JavaScript 慢慢地紅了起來，JavaScript 開發者也開始針對自己碰上的問題，寫出了能解決問題的工具、接著包成能複用的工具包。他們就能把這個被稱為**函式庫**（library）的東西，拿去與他人共享。共享的函式庫生態，也有助於塑造
參考[原文](https://github.com/mdn/content/blob/6033ca2f22833bbfee06981bb5a82e271525664e/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.md?plain=1#L38)整段一併調整

`When JavaScript debuted in 1996, it added occasional interactivity and excitement to a web that was, up until then, composed of static documents. The web became not just a place to _read things_, but to _do things_. JavaScript's popularity steadily increased. Developers who worked with JavaScript wrote tools to solve the problems they faced, and packaged them into reusable packages called **libraries**, so they could share their solutions with others. This shared ecosystem of libraries helped shape the growth of the web.`

```suggestion
在 JavaScript 誕生的 1996 年，它的作用僅是為主要由靜態文件組成的網頁，添加些許的互動和興奮感。但網路漸漸從_閱讀_的場所，轉變為_做事_的地方。JavaScript 慢慢地紅了起來，開發者也開始撰寫工具，以解決他們遭遇的問題，並打包成易於重複使用的**函式庫**（library），以便與他人分享。這個共享函式庫的生態，也同時推進了網路的增長。
```

2022-08-30 03:43 UTC, DevRickLin commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.md
> +在 JavaScript 誕生的 1996 年，它只有為當時由靜態文檔組成的網頁提供交互性和興奮感的作用。但之後網路漸漸從*拿來看*，變成*拿來用*了。JavaScript 慢慢地紅了起來，JavaScript 開發者也開始針對自己碰上的問題，寫出了能解決問題的工具、接著包成能複用的工具包。他們就能把這個被稱為**函式庫**（library）的東西，拿去與他人共享。共享的函式庫生態，也有助於塑造
我應該使用 --amend 覆蓋之前的 commit，還是在修改後提交新的 commit ?

2022-08-30 05:13 UTC, yin1999 commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.md
> +在 JavaScript 誕生的 1996 年，它只有為當時由靜態文檔組成的網頁提供交互性和興奮感的作用。但之後網路漸漸從*拿來看*，變成*拿來用*了。JavaScript 慢慢地紅了起來，JavaScript 開發者也開始針對自己碰上的問題，寫出了能解決問題的工具、接著包成能複用的工具包。他們就能把這個被稱為**函式庫**（library）的東西，拿去與他人共享。共享的函式庫生態，也有助於塑造
提交新的 commit 即可

2022-08-30 06:12 UTC, DevRickLin commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.md
> +在 JavaScript 誕生的 1996 年，它只有為當時由靜態文檔組成的網頁提供交互性和興奮感的作用。但之後網路漸漸從*拿來看*，變成*拿來用*了。JavaScript 慢慢地紅了起來，JavaScript 開發者也開始針對自己碰上的問題，寫出了能解決問題的工具、接著包成能複用的工具包。他們就能把這個被稱為**函式庫**（library）的東西，拿去與他人共享。共享的函式庫生態，也有助於塑造
 已經提交了該段落的翻譯，並進行了部分的潤色。

2022-08-30 08:58 UTC, irvin commented on files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.md
> +在 JavaScript 誕生的 1996 年，它的作用僅僅是為當時由靜態文檔組成的網頁，提供些許的交互性和興奮感。而當網路漸漸從*閱讀＊的場所，成為*做事*的場所，JavaScript 也慢慢地紅了起來。JavaScript 開發者們撰寫了許多工具來解決自己遭遇的問題、並打包成能複用的工具包，稱為**函式庫**（library），以便和他人共享自己的解決方案。共享的函式庫生態也推進了網路的增長
繁體中文中的 interactive 翻譯為「互動」而非「交互性」。
「複用」之處也較「重複使用」更少見。此兩處我直接修改。
```suggestion
在 JavaScript 誕生的 1996 年，它的作用僅僅是為當時由靜態文檔組成的網頁，提供些許的互動和興奮感。而當網路漸漸從_閱讀_的媒介，成為_做事_的場所，JavaScript 也慢慢地紅了起來。JavaScript 開發者們撰寫了許多工具，來解決自己遭遇的問題，並打包成能重複使用的工具包，稱為**函式庫**（library），以便和他人共享自己的解決方案。函式庫共享的生態，也推進了網路的增長。
```

2022-08-30 17:56 UTC, merged