Fix translation and tags
mdn/translated-content pull request #8144
Opened 2022-08-31 09:25 UTC by Reggr0y

Align the tags and bottom elements with the EN version, Change "Voir aussi" for "Pour approfondir" as seen on other FR glossary pages.

2022-08-31 12:58 UTC, cw118 requested changes
Merci pour ces corrections @Reggr0y ! Quelques commentaires, n'hésitez pas si besoin d'aide :)

2022-08-31 12:58 UTC, cw118 commented on files/fr/glossary/ajax/index.md
>    - l10n:priority
```suggestion
```

Pas besoin des *tags* sur translated-content (idem avec `translation_of` et `original_slug` aux lignes 10 et 11, je ne peux pas commenter sur ces endroits :/) :)

2022-08-31 12:58 UTC, cw118 commented on files/fr/glossary/ajax/index.md
> +## Pour approfondir
```suggestion
## Voir aussi
```

"Voir aussi" est la convention utilisée pour la locale française (je soumettrai une PR pour aligner ces titres sous peu) :)

2022-09-04 13:06 UTC, gregWDumont commented on files/fr/glossary/ajax/index.md
>    - l10n:priority
Merci pour l'information. Je me suis inspiré de ce que j'ai trouvé sur les autres articles mais prendrai cela en compte à l'avenir.

2022-09-04 13:32 UTC, gregWDumont commented
J'ai fait les modifs sur ma version locale avec un nouveau commit à la clef, est-ce que vous pouvez me dire si cela vous convient ?

2022-09-04 14:57 UTC, cw118 approved these changes
C'est parfait, merci 🔥

2022-09-04 14:57 UTC, merged