Create folder and translate content for Color_Wheel
mdn/translated-content pull request #8191
Opened 2022-09-01 13:35 UTC by gregWDumont

I do not get why "Contenu embarqué" is part of his pull request as it has already been accepted in a previous one and I have not changed anything since then.

2022-09-01 13:48 UTC, cw118 commented
@gregWDumont Vous devez probablement effectuer un *fetch* du dépôt distant (mdn/translated-content) sur votre fork, puis créer une nouvelle branche avant de faire des modifications. 

N'hésitez pas si besoin d'aide (N.B. on ne traduit pas les noms/chemins de fichier, donc il faut utiliser **`files/fr/glossary/color_wheel/index.md`** et non `files/fr/glossary/cercle_chromatique/index.md`) :)

2022-09-01 13:53 UTC, cw118 requested changes
(cf. le commentaire ci-dessus)

2022-09-02 08:23 UTC, gregWDumont commented
Hello,
merci, pour le retour.
Est-ce que je dois faire une nouvelle PR ?

2022-09-02 18:42 UTC, cw118 commented
@gregWDumont je pense que ce serait plus facile de clore cette PR et d'en créer une autre (il y a un *workflow* qui s'exécute sur la branche `main`, cela pourrait compliquer un peu le processus de revue), mais ce n'est pas "obligatoire" :) 

À noter également que les noms de fichier doivent être en minuscules (par ex. `files/fr/glossary/color_wheel/index.md`, pas `files/fr/glossary/Color_wheel/index.md`)

2022-09-03 18:28 UTC, closed without merging