Web/API/HTML_Sanitizer_API の翻訳
mdn/translated-content pull request #8195
Opened 2022-09-01 14:50 UTC by debiru

### 概要

以下のページの新規翻訳

- https://developer.mozilla.org/en-US/docs/Web/API/HTML_Sanitizer_API

### 備考

メタデータ項目を最新の形（不要なものを削除する）にしてみました。

### 関連

close mozilla-japan/translation#633

2022-09-07 09:57 UTC, mfuji09 requested changes
コメントした部分を確認してください。

2022-09-07 09:57 UTC, mfuji09 commented on files/ja/web/api/html_sanitizer_api/index.md
> +API にアクセスするには、{{domxref('Sanitizer.Sanitizer()','Sanitizer()')}} コンストラクタを使用して {{domxref('Sanitizer')}} インスタンスを作成し、設定することになります。設定オプションのパラメータで、許可する要素や許可しない要素、属性を指定し、カスタム要素やコメントを有効にすることができます。
細かいところですが、コンストラクタ⇒コンストラクター、パラメータ⇒パラメーターでお願いします。
```suggestion
API にアクセスするには、{{domxref('Sanitizer.Sanitizer()','Sanitizer()')}} コンストラクターを使用して {{domxref('Sanitizer')}} インスタンスを作成し、設定することになります。設定オプションのパラメーターで、許可する要素や許可しない要素、属性を指定し、カスタム要素やコメントを有効にすることができます。
```

2022-09-07 09:57 UTC, mfuji09 commented on files/ja/web/api/html_sanitizer_api/index.md
> +id が `userFrame` である {{HTMLElement("iframe")}} からのデータをサニタイズする。
ここだけ文体が違うので、確認してください。
```suggestion
id が `userFrame` である {{HTMLElement("iframe")}} からのデータをサニタイズします。
```

2022-09-07 09:57 UTC, mfuji09 commented on files/ja/web/api/html_sanitizer_api/index.md
> +例えば、クライアントサイドのテンプレート化ソリューションの一部として、またはユーザー生成コンテンツをレンダリングするために、あるいは他のサイトからのフレームにデータを含めるときに、ウェブアプリケーションはしばしばクライアントサイドで信頼できない HTML を扱う必要があるのです。Sanitizer API を使用すると、このような潜在的に信頼できない HTML を安全な方法でレンダリングすること
この文脈で「あるのです」は少し不自然に感じます。単に「あります」のほうがよいと思います。
```suggestion
例えば、クライアントサイドのテンプレート化ソリューションの一部として、またはユーザー生成コンテンツをレンダリングするために、あるいは他のサイトからのフレームにデータを含めるときに、ウェブアプリケーションはしばしばクライアントサイドで信頼できない HTML を扱う必要があります。Sanitizer API を使用すると、このような潜在的に信頼できない HTML を安全な方法でレンダリングすることができます。
```

2022-09-08 09:26 UTC, debiru commented on files/ja/web/api/html_sanitizer_api/index.md
> +API にアクセスするには、{{domxref('Sanitizer.Sanitizer()','Sanitizer()')}} コンストラクタを使用して {{domxref('Sanitizer')}} インスタンスを作成し、設定することになります。設定オプションのパラメータで、許可する要素や許可しない要素、属性を指定し、カスタム要素やコメントを有効にすることができます。
43a6911 で修正しました。「パラメータ」は2箇所修正しました。

2022-09-09 06:39 UTC, mfuji09 approved these changes
OKです。

2022-09-09 06:39 UTC, merged