translation and update to match with EN version
mdn/translated-content pull request #8196
Opened 2022-09-01 14:51 UTC by gregWDumont

typo in the commit title

2022-09-03 16:24 UTC, cw118 requested changes
Merci pour cette PR @gregWDumont, quelques remarques :)

2022-09-03 16:24 UTC, cw118 commented on files/fr/glossary/abstraction/index.md
> +- Aider l'utilisateur en évitant qu'il ait à écrire du code de bas niveau.
```suggestion
- Aider l'utilisatrice ou l'utilisateur à éviter d'écrire du code de bas niveau.
```

Formulation inclusive (cf. [le guide stylistque](https://github.com/mozfr/besogne/wiki/Guide-stylistique-pour-la-traduction#sadresser-%C3%A0-lutilisateur-ou-lutilisatrice))

2022-09-03 16:24 UTC, cw118 commented on files/fr/glossary/abstraction/index.md
> +- Pouvoir modifier l'implémentation interne de la classe indépendamment sans que l'utilisateur soit affecté.
```suggestion
- Pouvoir modifier l'implémentation interne de la classe indépendamment sans affecter l'utilisatrice ou l'utilisateur.
```

2022-09-03 16:24 UTC, cw118 commented on files/fr/glossary/abstraction/index.md
> +- Aider à augmenter la sécurité d'une application ou d'un programme car seuls les détails importants sont fournis à l'utilisateur.
```suggestion
- Aider à augmenter la sécurité d'une application ou d'un programme car seuls les détails importants sont fournis à l'utilisatrice ou l'utilisateur.
```

2022-09-03 16:24 UTC, cw118 commented on files/fr/glossary/abstraction/index.md
> +  // method to set values of internal members
```suggestion
  // méthode pour affecter des valeurs aux membres internes
```

2022-09-03 16:24 UTC, cw118 commented on files/fr/glossary/abstraction/index.md
> +## **Pour approfondir**
```suggestion
## Voir aussi
```

2022-09-04 12:56 UTC, gregWDumont commented
I have made the changes, let me know if anything else is needed. Thanks for your time and suggestions.

2022-09-04 15:00 UTC, cw118 approved these changes
Merci à nouveau pour cet excellent travail :)

2022-09-04 15:00 UTC, merged