Create index.md
mdn/translated-content pull request #8232
Opened 2022-09-02 09:33 UTC by gregWDumont

Update links except for `Object.create()`, "HTML DOM API", and `structuredClone()` which has not been translated yet.

I have not modified it but there is an issue with this as it doesn't appear on the EN-US repo: [`window`](/en-US/docs/Web /API/Fenêtre).

2022-09-02 18:39 UTC, gregWDumont commented
These links are supposed to replace the ones from the EN-US/docs/ source. I can't figure out if I should leave the initial links or use the ones from the translated repo?!

2022-09-02 18:46 UTC, cw118 commented
Links to other MDN Web Docs pages should start with `/fr/docs/`. For example, to create a link to the (French) browser glossary page (`https://developer.mozilla.org/fr/docs/Glossary/Browser`), one writes: `[Navigateur](/fr/docs/Glossary/Browser)`. Internal links like these should point to `fr` even if the page does not yet exist in French :)

2022-09-02 19:28 UTC, cw118 requested changes
Quelques suggestions :) cela dit, merci beaucoup @gregWDumont !

2022-09-02 19:28 UTC, cw118 commented on files/fr/glossary/deep_copy/index.md
> +// Array(3) [ "eggs", "flour", "water" ]
```suggestion
let liste_ingredients = ["nouilles", {"liste": ["œufs", "farine", "eau"]}];
let liste_ingredients_copieprofonde = JSON.parse(JSON.stringify(liste_ingredients));

// Modifier la valeur de la propriété 'liste' dans liste_ingredients_copieprofonde
liste_ingredients_copieprofonde[1].liste = ["farine de riz", "water"];
// La propriété 'liste' ne change pas dans liste_ingredients
console.log(liste_ingredients[1].liste);
// Array(3) [ "œufs", "farine", "eau" ]
```

2022-09-02 19:28 UTC, cw118 commented on files/fr/glossary/deep_copy/index.md
> +Cependant, alors que l'objet dans le code ci-dessus est assez simple pour être [sérialisable](/files/fr/Glossary/Serialization), de nombreux objets JavaScript ne sont pas du tout sérialisables - par
```suggestion
Cependant, alors que l'objet dans le code ci-dessus est assez simple pour être [sérialisable](/fr/docs/Glossary/Serialization), de nombreux objets JavaScript ne sont pas du tout sérialisables — par exemple, les [fonctions](/fr/docs/Web/JavaScript/Guide/Functions) (avec des fermetures), les [symboles](/fr/docs/Web/JavaScript/Reference/Global_Objects/Symbol), les objets qui représentent des éléments HTML dans [l'API HTML DOM](/fr/docs/Web/API/HTML_DOM_API), les données récursives, et bien d'autres cas. L'appel de `JSON.stringify()` pour sérialiser ces objets échouera. Il n'y a donc aucun moyen de faire des copies complètes de tels objets.
```

2022-09-02 19:28 UTC, cw118 commented on files/fr/glossary/deep_copy/index.md
> +Pour les objets qui _sont_ sérialisables, vous pouvez également utiliser le [`structuredClone()`](/en-US/docs/Web/API/structuredClone) méthode pour créer des copies profondes. `structuredClone()` a l
```suggestion
Pour les objets qui _sont_ sérialisables, vous pouvez également utiliser la méthode [`structuredClone()`](/fr/docs/Web/API/structuredClone) pour créer des copies profondes. `structuredClone()` est avantageuse car elle permet de _transférer_ des [objets transférables](/fr/docs/Glossary/Transferable_objects) dans la source vers la nouvelle copie, plutôt que de simplement les cloner. Mais notez que `structuredClone()` n'est pas une fonctionnalité du langage JavaScript lui-même — il s'agit plutôt d'une fonctionnalité des navigateurs et de tout autre environnement d'exécution de JavaScript qui implémente un objet global comme [`window`](/fr/docs/Web/API/Window), et appeler `structuredClone()` pour cloner un objet non sérialisable échouera de la même manière que l'appel de `JSON.stringify()` pour le sérialiser échouera.
```

2022-09-02 19:28 UTC, cw118 commented on files/fr/glossary/deep_copy/index.md
> +## Pour approfondir
```suggestion
## Voir aussi
```

2022-09-02 19:29 UTC, cw118 requested changes

2022-09-02 19:29 UTC, cw118 commented on files/fr/glossary/deep_copy/index.md
> +- [`window.structuredClone()`](/en-US/docs/Web/API/structuredClone)
```suggestion
- [Copie superficielle](/fr/docs/Glossary/Shallow_copy)
- [`window.structuredClone()`](/fr/docs/Web/API/structuredClone)
```

j'avais loupé cette partie :/

2022-09-03 17:57 UTC, cw118 approved these changes
Merci beaucoup pour cette traduction @gregWDumont ! 

Je me suis permis de pousser un commit rajoutant la clé `l10n sourceCommit` (voir https://github.com/orgs/mdn/discussions/129) :)

2022-09-03 17:57 UTC, merged