[Ko/update] Identifying resources on the Web
mdn/translated-content pull request #8253
Opened 2022-09-03 14:06 UTC by SnowMarble

2022-09-12 16:24 UTC, hochan222 requested changes
@SnowMarble 님 안녕하세요.

리뷰 사항 문서에 남겨두었습니다!

기여해주셔서 감사합니다. 좋은 하루 보내세요 :)

2022-09-12 16:24 UTC, hochan222 commented on files/ko/web/http/basics_of_http/identifying_resources_on_the_web/index.md
> +이러한 URL을 브라우저의 주소 표시줄에 입력하여 URL과 연결되는 페이지(리소스)를 로드할 수 있습니다.
```suggestion
이러한 URL 중 하나를 브라우저의 주소 표시줄에 입력하여 URL과 연결되는 페이지(리소스)를 로드할 수 있도록 지시할 수 있습니다.
```

> Any of those URLs can be typed into your browser's address bar to tell it to load the associated page (resource).

 `Any of those` 와 `to tell it`의 의미를 조금 더 살렸습니다!

2022-09-12 16:24 UTC, hochan222 commented on files/ko/web/http/basics_of_http/identifying_resources_on_the_web/index.md
> +| file        | 사용자 지정 파일 이름                                                    |
```suggestion
| file        | 호스트별 파일 이름                                                    |
```

> Host-specific file names

사용자가 호스트와 동치는 아니라고 생각해서 리뷰 드렸습니다. 혹시 `사용자 지정`이라고 번역하신 특별한 이유가 있으신지 궁금합니다!

2022-09-12 16:24 UTC, hochan222 commented on files/ko/web/http/basics_of_http/identifying_resources_on_the_web/index.md
> +## 사용 참고 사항
```suggestion
## 사용 일람
```

- [translation-guide](https://github.com/mdn/translated-content/blob/main/docs/ko/translation-guide.md#section-title)

2022-09-12 22:25 UTC, SnowMarble commented on files/ko/web/http/basics_of_http/identifying_resources_on_the_web/index.md
> +| file        | 사용자 지정 파일 이름                                                    |
여기서 호스트는 컴퓨터 자체를 뜻하기 보단 컴퓨터를 사용하는 사람, 주체 정도로 받아들였습니다. 그리고 실제 file 프로토콜은 컴퓨터를 사용하는 사람이 파일을 선택/지정하여 브라우저 등에서 여는것이니, 이 주체를 '사용자'라 했고, 행위를 '저정'이라고 하였습니다.

2022-09-13 12:30 UTC, hochan222 commented on files/ko/web/http/basics_of_http/identifying_resources_on_the_web/index.md
> +| file        | 사용자 지정 파일 이름                                                    |
@SnowMarble 님, 빠른 답변 감사드립니다.

[rfc8089 - The "file" URI Scheme](https://datatracker.ietf.org/doc/html/rfc8089)에 따르면

일반적으로 file URI 구조는 `file://host/path` 형식을 갖습니다. 이때, host는 IP/Path 도 가능하며, 생략이 된다면 "localhost"로 자동 지정됩니다.

따라서 아래 세가지 모두 유효한 문법입니다.

- "file:///path/to/file"
- "file:/path/to/file"
- "file://host.example.com/path/to/file"

비록 보안상 이유로 IP/Path 형식은 브라우저에서 제한을 하지만 존재하는 형식입니다. 따라서 해당 단어의 host는 [host](https://developer.mozilla.org/ko/docs/Web/HTTP/Headers/Host)의 의미로 해석되어야합니다.

`Host-specific file names`의 의미를 `사용자 지정 파일 이름`으로 번역하면 [host](https://developer.mozilla.org/ko/docs/Web/HTTP/Headers/Host)의 의미로 해석될 여지보다는 local 환경으로만 해석될 여지가 있다고 생각되어서 리뷰를 드렸었습니다.

충분히 `사용자 지정 파일 이름`의 의도도 공감하며 고민이 되네요.

2022-09-13 12:36 UTC, SnowMarble commented on files/ko/web/http/basics_of_http/identifying_resources_on_the_web/index.md
> +| file        | 사용자 지정 파일 이름                                                    |
여기에 호스트의 정의가 있군요.

> The "host" is the fully qualified domain name of the system on which
   the file is accessible.  This allows a client on another system to
   know that it cannot access the file system, or perhaps that it needs
   to use some other local mechanism to access the file.

말씀해주신데로 '호스트'로 직접 번역하는 것이 적합해보입니다. 섬세한 리뷰 감사합니다👍👍

2022-09-13 12:40 UTC, hochan222 approved these changes

2022-09-13 12:40 UTC, merged