[ko] handler.ownKeys()
mdn/translated-content pull request #8271
Opened 2022-09-04 12:37 UTC by SnowMarble

2022-09-09 11:51 UTC, yujo11 requested changes

2022-09-09 11:51 UTC, yujo11 commented on files/ko/web/javascript/reference/global_objects/proxy/proxy/ownkeys/index.md
> +다음 매개변수는 `ownKeys()` 메서드에 전달됩니다. `this`는 처리기에 바인딩됩니다.
```suggestion
다음 매개변수는 `ownKeys()` 메서드에 전달됩니다. `this`는 핸들러에 바인딩됩니다.
```

"처리기"라는 단어 대신 "핸들러" 혹은 원문 그대로 "handler"라는 단어를 사용하는건 어떨까요?

2022-09-09 12:36 UTC, SnowMarble commented on files/ko/web/javascript/reference/global_objects/proxy/proxy/ownkeys/index.md
> +다음 매개변수는 `ownKeys()` 메서드에 전달됩니다. `this`는 처리기에 바인딩됩니다.
용어집에 'handler'는 '처리기'로 번역하도록 되어있어 이렇게 번역했습니다.

![image](https://user-images.githubusercontent.com/69508345/189351101-1f1318ae-e017-4228-b47d-af484e6574e0.png)

Examples와 마찬가지로 용어 번역에대한 검토가 필요한것 같습니다.

2022-09-10 12:35 UTC, yujo11 commented on files/ko/web/javascript/reference/global_objects/proxy/proxy/ownkeys/index.md
> +다음 매개변수는 `ownKeys()` 메서드에 전달됩니다. `this`는 처리기에 바인딩됩니다.
아하 그렇네요 제가 용어집을 숙지하지 못 했군요. 일단 머지 후에 이 부분은 따로 논의해봐야곘네요! 감사합니다!

2022-09-10 12:35 UTC, yujo11 approved these changes

2022-09-10 12:36 UTC, merged