[ko] handler.setPrototypeOf()
mdn/translated-content pull request #8278
Opened 2022-09-04 13:48 UTC by SnowMarble

2022-09-12 17:56 UTC, hochan222 requested changes
@SnowMarble 님, 안녕하세요.

리뷰사항 중 `null` 부분만 수정해주시면 바로 머지하겠습니다!

기여해주셔서 감사합니다. 좋은 하루 보내세요 :)

2022-09-12 17:56 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/proxy/proxy/setprototypeof/index.md
> +다음 매개변수는 `setPrototypeOf()` 메서드에 전달됩니다. `this`는 처리기에 바인딩됩니다.
> `this`는 처리기에 바인딩됩니다.

최근에 handler 번역에 대해서 어색하다는 의견이 있었습니다. @SnowMarble 님은 핸들러 vs 처리기중 어느 번역이 더 좋다고 생각하시나요?

단어 번역 가이드의 히스토리를 파악해보았는데, 이벤트 처리기(이벤트 핸들러), 이벤트 수신기(이벤트 리스너)로부터 처리기가 정의 되었습니다. 

https://ko.javascript.info/ 에서는 수신기와 처리기 대신 모든 번역에서 핸들러, 리스너를 선택했습니다.

반면에 microsoft, ibm은 이벤트 처리기, 이벤트 수신기를 선택했습니다.

> this is bound to the handler.

이것은 핸들러에 바인딩됩니다.
이것은 처리기에 바인딩됩니다.

처리기라는 단어도 실제 사용중인 단어라서 고민이 되긴하네요. 단어를 자주 접하지 못해서 어색한건가..? 라는 생각도 들구요. 저한텐 핸들러가 더 자연스럽긴합니다..!

2022-09-12 17:56 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/proxy/proxy/setprototypeof/index.md
> +  - : 대상 객체의 새 프로토타입 또는 null
```suggestion
  - : 대상 객체의 새 프로토타입 또는 `null`
```

2022-09-12 23:29 UTC, SnowMarble commented on files/ko/web/javascript/reference/global_objects/proxy/proxy/setprototypeof/index.md
> +다음 매개변수는 `setPrototypeOf()` 메서드에 전달됩니다. `this`는 처리기에 바인딩됩니다.
현재 사전에 따른다면 '처리기'를 사용하는것이 맞지만, 저도 그랬듯이 많은 사람들에게도 '핸들러'가 익숙할것 같습니다. 

그래서 우리말 샘에서도 찾아보니 '오류 핸들러', '입축력 핸들러' 라는 용어가 있던데, 이들이 확정된 규범 표기는 아니더라구요.

> ... 예외 상황이 발생할 경우를 대비하여 이를 처리하도록 작성된 프로그램 모듈. ⇒규범 표기는 미확정이다.

하지만 여기서 규범 표기 미확정이라는 것은 '팬데믹'처럼 사회에선 많이 쓰이지만 아직 표기만 확정하지 않은것이라 핸들러 라는 용어를 사용하는것에 큰 문제는 없을것 같습니다.

mdn에서 사용되는 용어도 하나의 표준으로 여겨질 수 있기에 조금 더 고려해봐야 할것 같습니다.

2022-09-13 12:35 UTC, hochan222 commented on files/ko/web/javascript/reference/global_objects/proxy/proxy/setprototypeof/index.md
> +다음 매개변수는 `setPrototypeOf()` 메서드에 전달됩니다. `this`는 처리기에 바인딩됩니다.
@SnowMarble 님, 답변 감사드립니다.

우선 현재 PR에서는 그대로 표기하는것으로 보류하고 병합하겠습니다. 추후 변경사항이 있으면 일괄적용 하면 좋겠네요..!

2022-09-13 12:35 UTC, hochan222 approved these changes

2022-09-13 12:35 UTC, merged