[ko/update] ArrayBuffer
mdn/translated-content pull request #8286
Opened 2022-09-04 14:11 UTC by SnowMarble

2022-09-05 12:49 UTC, pje1740 approved these changes
확인했습니다! 고생하셨습니다 🔥

2022-09-05 12:49 UTC, pje1740 commented on files/ko/web/javascript/reference/global_objects/arraybuffer/index.md
> +ArrayBuffer() 생성자는 주어진 길이(바이트)의 새 ArrayBuffer를 만듭니다. Base64 문자열이나 로컬 파일과 같은 기존 데이터에서 배열 버퍼를 가져올 수도 있습니다.
이 문장은 제거하면 좋을 거 같습니다! 원문에 없기도 하고 밑에 내용과 중복되네요.

2022-09-05 12:50 UTC, pje1740 requested changes
제가 approve로 남겼네요! 수정할 부분만 확인 부탁드릴게요!

2022-09-05 13:00 UTC, SnowMarble commented
@pje1740 수정했습니다:)

2022-09-25 16:06 UTC, hochan222 commented
@pje1740  님, 안녕하세요. 혹시, PR이 지연되고 있는 이유가 있을까요?

2022-09-26 11:49 UTC, pje1740 approved these changes
수정된 내용 확인했습니다! 감사합니다! 🔥

2022-09-26 11:50 UTC, merged