Create index.md
mdn/translated-content pull request #8372
Opened 2022-09-07 15:26 UTC by gregWDumont

2022-09-08 06:33 UTC, SphinxKnight requested changes
Merci à nouveau @gregWDumont 🙇 
Quelques suggestions pour compléter cette traduction initiale :)

2022-09-08 06:33 UTC, SphinxKnight commented on files/fr/glossary/effective_connection_type/index.md
> +slug: Glossary/Effective_connection_type
```suggestion
title: Type de connexion réel
slug: Glossary/Effective_connection_type
l10n:
  sourceCommit: 6fcbba930a3d72f4373a376012db37aa75d1518f
```

2022-09-08 06:33 UTC, SphinxKnight commented on files/fr/glossary/effective_connection_type/index.md
> +Le **type de connexion réel**, ou "effective connection type" en anglais (ECT), fait référence aux performances mesurées du réseau, renvoyant un type de connexion cellulaire, comme la 3G, même si la
```suggestion
Le **type de connexion réel**, ou «&nbsp;<i lang="en">effective connection type</i>&nbsp;» en anglais (abrégé en ECT), fait référence aux performances mesurées du réseau, renvoyant un type de connexion cellulaire, comme la 3G, même si la connexion réelle est effectuée en haut débit ou Wi-Fi, en fonction du temps entre le navigateur demandant une page et le type de connexion réel.
```

2022-09-08 06:33 UTC, SphinxKnight commented on files/fr/glossary/effective_connection_type/index.md
> +Les valeurs de '`slow-2g`', '`2g`', '`3g`' et '`4g`' sont déterminées en utilisant le temps d'aller-retour de la requête et des valeurs de liaison descendante.
```suggestion
Les valeurs de `"slow-2g"`, `"2g"`, `"3g"` et `"4g"` sont déterminées en utilisant le temps d'aller-retour de la requête et des valeurs de liaison descendante.
```

2022-09-08 06:33 UTC, SphinxKnight commented on files/fr/glossary/effective_connection_type/index.md
> +| `4g`      | 0ms                                                         | ∞                | Le réseau est adapté à la vidéo HD, à la vidéo en temps réel, etc.                                    |
```suggestion
| ECT         | Durée minimale d'[aller-retour](</fr/docs/Glossary/Round_Trip_Time_(RTT)>) | Liaison descendante maximale | Explication                                                                                             |
| ----------- | ----------------------------------------------------------- | ---------------- | -------------------------------------------------------------------------------------------------------- |
| `slow-2g` | 2000ms                                                      | 50 Kbps          | Le réseau convient uniquement aux petits transferts tels que les pages composées uniquement de texte.                                  |
| `2g`      | 1400ms                                                      | 70 Kbps          | Le réseau est adapté aux transferts de petites images.                                    |
| `3g`      | 270ms                                                       | 700 Kbps         | Le réseau est adapté aux transferts de ressources volumineuses telles que des images en haute résolution, de l'audio et de la vidéo SD. |
| `4g`      | 0ms                                                         | ∞                | Le réseau est adapté à la vidéo HD, à la vidéo en temps réel, etc.                                    |
```

2022-09-08 06:33 UTC, SphinxKnight commented on files/fr/glossary/effective_connection_type/index.md
> +[effectiveType](/en-US/docs/Web/API/NetworkInformation/effectiveType) est une propriété de l'[API d'informations réseau](/fr/docs/Web/API/Network_Information_API), visible sur JavaScript via l'objet
```suggestion
[`effectiveType`](/fr/docs/Web/API/NetworkInformation/effectiveType) est une propriété de l'[API d'informations réseau](/fr/docs/Web/API/Network_Information_API), visible sur JavaScript via l'objet [`navigator.connection`](/fr/docs/Web/API/Navigator/connection). Pour voir votre type de connexion réel, ouvrez la console des outils de développement d'un navigateur compatible et saisissez ce qui suit&nbsp;:
```

2022-09-08 06:33 UTC, SphinxKnight commented on files/fr/glossary/effective_connection_type/index.md
> +- {{HTTPHeader("ECT")}}
```suggestion
- [`NetworkInformation`](/fr/docs/Web/API/NetworkInformation)
- [`NetworkInformation.effectiveType`](/fr/docs/Web/API/NetworkInformation/effectiveType)
- [`ECT`](/fr/docs/Web/HTTP/Headers/ECT)
```

2022-09-08 07:15 UTC, gregWDumont commented
Salut,
J'espère que l'on sera bon avec cette nouvelle version.

2022-09-10 14:34 UTC, SphinxKnight approved these changes
:100: Merci @gregWDumont, je me suis permis de pousser un commit sur un point que j'avais oublié dans la première revue à propos des unités (pour épargner un A/R)

2022-09-10 14:36 UTC, merged

2022-09-10 18:43 UTC, gregWDumont commented
Je t'en prie, l'essentiel c'est d'avoir un bon résultat !