Getting started with Svelte の翻訳
mdn/translated-content pull request #8373
Opened 2022-09-07 20:38 UTC by SuzukiKatsuma

### 概要
原文をコピーしたドキュメントを新たに作成した後、"Getting started with Svelte" を翻訳しました。

### 関連
issue: https://github.com/mozilla-japan/translation/issues/612

2022-09-11 15:21 UTC, mfuji09 requested changes
主に表記方法について、コメントを入れましたので確認してください。

2022-09-11 15:21 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/svelte_getting_started/index.md
> +  - `main.js`: アプリケーションのエントリポイントです。これは `App` コンポーネントをインスタンス化して、HTML ページの body にバインドするだけです。
「エントリ」→「エントリー」としてください。

2022-09-11 15:21 UTC, mfuji09 commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/svelte_getting_started/index.md
> +縮小版の `bundle.js` のサイズは 3KB 程度で、これには「Svelte ランタイム」(わずか 300 行の JavaScript コード) と `App.svelte` のコンパイル済みコンポーネントが含まれています。お分かりのように `bundle.js` は `index.html` から参照される唯一の JavaScript ファイルです。ウェブページに読み込まれる他のライブ
ライブラリ→ライブラリーでお願いします。
```suggestion
縮小版の `bundle.js` のサイズは 3KB 程度で、これには「Svelte ランタイム」(わずか 300 行の JavaScript コード) と `App.svelte` のコンパイル済みコンポーネントが含まれています。お分かりのように `bundle.js` は `index.html` から参照される唯一の JavaScript ファイルです。ウェブページに読み込まれる他のライブラリーはありません。
```

2022-09-11 19:22 UTC, SuzukiKatsuma commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/svelte_getting_started/index.md
> +tags:
tags: 以下を削除して、sourceCommit の ID を記載しました。

2022-09-11 19:34 UTC, SuzukiKatsuma commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/svelte_getting_started/index.md
> +縮小版の `bundle.js` のサイズは 3KB 程度で、これには「Svelte ランタイム」(わずか 300 行の JavaScript コード) と `App.svelte` のコンパイル済みコンポーネントが含まれています。お分かりのように `bundle.js` は `index.html` から参照される唯一の JavaScript ファイルです。ウェブページに読み込まれる他のライブ
[78e229a](https://github.com/mdn/translated-content/pull/8373/commits/78e229a8e3c0e79290f422b31d1efcfe7f23182d) - 修正しました。

2022-09-11 19:35 UTC, SuzukiKatsuma commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/svelte_getting_started/index.md
> +  - `main.js`: アプリケーションのエントリポイントです。これは `App` コンポーネントをインスタンス化して、HTML ページの body にバインドするだけです。
[78e229a](https://github.com/mdn/translated-content/pull/8373/commits/78e229a8e3c0e79290f422b31d1efcfe7f23182d) - 修正しました。

2022-09-11 19:35 UTC, SuzukiKatsuma commented on files/ja/learn/tools_and_testing/client-side_javascript_frameworks/svelte_getting_started/index.md
> +## Svelte: 優れたユーザーインターフェースを構築する新しいアプローチ
[78e229a](https://github.com/mdn/translated-content/pull/8373/commits/78e229a8e3c0e79290f422b31d1efcfe7f23182d) - 修正しました。

2022-09-11 19:39 UTC, SuzukiKatsuma commented
コメントいただいた箇所を修正しました！
再度レビューをよろしくお願いします。

2022-09-12 03:29 UTC, mfuji09 approved these changes
OKです。

2022-09-12 03:30 UTC, merged