Learn/HTML/Howto/Author_fast-loading_HTML_pages を更新
mdn/translated-content pull request #840
Opened 2021-05-12 16:16 UTC by mfuji09

- conflicting ディレクトリ内の翻訳文の方が新しいので、こちらのファイルを本来の場所に移動した
- 2021/04/24 時点の英語版に同期
- 原語併記マクロを削除 (https://github.com/mozilla-japan/translation/issues/547)

2021-05-22 04:54 UTC, potappo requested changes
同じ原文の翻訳が二つ続いていたため、片方を削除しました。確認をお願いします。

2021-05-22 04:54 UTC, potappo commented on files/ja/learn/html/howto/author_fast-loading_html_pages/index.html
> +<p>そのため、特に動的に生成されるページについては、この件について調べてみると有益です。よって特に、動的に生成されるページのためにこの問題について調べることは有益です。少し厄介ですが、通常キャッシュできないページのリクエストを大幅に節約できるでしょう。</p>
```suggestion
<p>そのため、特に動的に生成されるページについては、この件について調べてみると有益です。少し厄介ですが、通常キャッシュできないページのリクエストを大幅に節約できるでしょう。</p>
```

2021-05-22 13:07 UTC, mfuji09 commented on files/ja/learn/html/howto/author_fast-loading_html_pages/index.html
> +<p>そのため、特に動的に生成されるページについては、この件について調べてみると有益です。よって特に、動的に生成されるページのためにこの問題について調べることは有益です。少し厄介ですが、通常キャッシュできないページのリクエストを大幅に節約できるでしょう。</p>
見落としていました。ありがとうございました。

2021-05-23 14:00 UTC, potappo approved these changes
OK です。

2021-05-23 14:01 UTC, merged