fix: markdown render errors about BOLD
mdn/translated-content pull request #8406
Opened 2022-09-10 01:18 UTC by pea-sys

2022-09-11 04:36 UTC, mfuji09 requested changes
1か所の指摘をしましたので、修正をお願いします。
なお、日本語版記事へのPRは日本人しか読みませんので、日本語でどうぞ。

2022-09-11 04:36 UTC, mfuji09 commented on files/ja/web/api/indexeddb_api/basic_terminology/index.md
> +- **IndexedDB は、キーと値の組を格納します。** 値は複雑な構造のオブジェクトで、キーはそのオブジェクトのプロパティです。オブジェクトの任意のプロパティを使用するインデックスを作成して、迅速な検索や並べ替えされた列挙を行うことができます。キーにはバイナリーオブジェクトを使用することができます。
原文でも IndexedDB databases となっていますし、ここではデータベース（意味は下記の「主な用語」を参照）のことを言っていますので、「データベース」の語を削除すべきではないと思います。もし違和感があるのであれば、「IndexedDBのデータベース」などと書いた方がいいでしょう。
他の変更点についても同様にしてください。

2022-09-11 06:06 UTC, pea-sys commented on files/ja/web/api/indexeddb_api/basic_terminology/index.md
> +- **IndexedDB は、キーと値の組を格納します。** 値は複雑な構造のオブジェクトで、キーはそのオブジェクトのプロパティです。オブジェクトの任意のプロパティを使用するインデックスを作成して、迅速な検索や並べ替えされた列挙を行うことができます。キーにはバイナリーオブジェクトを使用することができます。
レビューありがとうございます。
ご指摘を元に一部不要な修正を差し戻しました。

2022-09-12 15:32 UTC, mfuji09 approved these changes
OKです。

2022-09-16 16:16 UTC, merged