Improve zh-cn translation
mdn/translated-content pull request #8419
Opened 2022-09-11 05:14 UTC by ezirmusitua

2022-09-11 05:52 UTC, yin1999 requested changes
Hi @ezirmusitua, please read the [translation-guide](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md):

- remove the `tag` metadata
- update links to `zh-CN` locale

2022-09-11 07:58 UTC, awxiaoxian2020 requested changes

2022-09-11 07:58 UTC, awxiaoxian2020 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +本文介绍了你在网络中最常遇见的视频编码，总结了这些编码方式的能力、兼容性以及使用时需要考虑的事项，并且提供了一些为你的项目的视频选择编码的建议 。
```suggestion
本文介绍了你在网络中最常遇见的视频编码，总结了这些编码方式的能力、兼容性以及使用时需要考虑的事项，并且提供了一些为你的项目的视频选择编码的建议。
```

2022-09-11 07:58 UTC, awxiaoxian2020 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +- 一个相当典型的 30 分钟视频会议需要大约 447.9 GB 的存储空间，而一部 2 小时的电影需要_几乎 1.79 **TB**（即 1790 GB）_。
```suggestion
- 一个相当典型的 30 分钟视频会议需要大约 447.9 GB 的存储空间，而一部 2 小时的电影需要_几乎 1.79 **TB**（即 1790 GB）_的空间。
```

2022-09-11 07:58 UTC, awxiaoxian2020 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +不仅所需的存储空间巨大，而且传输这样的未压缩视频所需的网络带宽也将是巨大的，达到 249 MB/秒——不包括音频和开销。这就是视频编解码器的用武之地。就像音频编解码器对声音数据所做的那样，视频编解码器压缩视频数据并将其编码为以后可以解码和播放或编辑的格式。
```suggestion
不仅所需的存储空间巨大，而且传输这样的未压缩视频所需的网络带宽也将是巨大的，达到 249 MB/秒——不包括音频和开销。视频编解码器的在此时就派上用场了。就像音频编解码器对声音数据所做的那样，视频编解码器压缩视频数据并将其编码为以后可以解码和播放或编辑的格式。
```

2022-09-11 07:58 UTC, awxiaoxian2020 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +与任何编码器一样，影响编码视频大小和质量的基本因素有两组：关于源视频格式和内容的细节，以及编码视频时使用的编解码器的特性和配置。
```suggestion
与任何编码器一样，影响编码视频大小和质量的基本因素有两组：源视频格式和内容的细节，以及编码视频时使用的编解码器的特性和配置。
```

2022-09-11 09:03 UTC, awxiaoxian2020 requested changes

2022-09-11 09:03 UTC, awxiaoxian2020 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +2. 一个 **[MP4](/zh-CN/docs/Web/Media/Formats/Containers#mpeg-4_mp4)** 容器和 **[AVC](#avc_h.264)** (**H .264**) 视频编解码器，最好使用 **[AAC](/zh-CN/docs/Web/Media/Formats/Audio_codecs#aac)** 作为您的音频编解码器。这是因为带有 AVC
请将所有的“您”替换成“你”

2022-09-11 09:03 UTC, awxiaoxian2020 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +- [Web audio codec guide](/zh-CN/docs/Web/Media/Formats/Audio_codecs)
链接翻译一下会更好

2022-09-11 09:11 UTC, awxiaoxian2020 requested changes

2022-09-11 09:11 UTC, awxiaoxian2020 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +不仅所需的存储空间巨大，而且传输这样的未压缩视频所需的网络带宽也将是巨大的，达到 249 MB/秒——不包括音频和开销。视频编解码器的在此时就派上用场了。就像音频编解码器对声音数据所做的那样，视频编解码器压缩视频数据并将其编码为以后可以解码和播放或编辑的格式。
```suggestion
不仅所需的存储空间巨大，而且传输这样的未压缩视频所需的网络带宽也将是巨大的，达到 249 MB/秒——不包括音频和开销。视频编解码器在此时就派上用场了。就像音频编解码器对声音数据所做的那样，视频编解码器压缩视频数据并将其编码为以后可以解码和播放或编辑的格式。
```

2022-09-11 09:11 UTC, awxiaoxian2020 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +最简单的准则是：任何使编码视频看起来更像原始的、未压缩的视频的东西通常也会使结果数据更大。因此，它始终是大小与质量的权衡。在某些情况下，为了降低数据大小而牺牲更大的质量是值得的。其他时候，质量损失是不可接受的，因此有必要接受导致相应较大文件的编解码器配置。
```suggestion
最简单的准则是：任何使要编码的视频看起来更像原始的、未压缩的东西通常会使数据更大。因此，它始终需要在大小与质量作出权衡。在某些情况下，为了降低数据大小而牺牲更高的质量是值得的。而有时质量损失是不可接受的，因此有必要接受导致使文件数据更大的编解码器配置。
```

2022-09-11 09:11 UTC, awxiaoxian2020 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +此外，所有编解码器都有其优点和缺点。有些编码器在处理特定的形状和图案会出现问题，有的不擅长复制锐利的边缘，有的在黑暗区域往往会丢失细节，不同的编码器都有可能出现各种各样的问题，这一切是由编码器底层的算法和数学理论导致的。
```suggestion
此外，所有编解码器都有其优点和缺点。有些编码器在处理特定的形状和图案会出现问题，有的不擅长处理锐利的边缘，有的在黑暗区域往往会丢失细节，不同的编码器都有可能出现各种各样的问题，这一切是由编码器底层的算法和数学理论决定的。
```

2022-09-11 09:11 UTC, awxiaoxian2020 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +此外，每个编码器实用程序在处理源视频的方式上可能有所不同，从而导致输出质量和/或大小的差异。
```suggestion
此外，每个编码器实用程序在处理源视频的方式上可能有所不同，从而导致输出质量和大小的差异。
```

2022-09-12 04:11 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +考虑到你可以获得多接近无损的限制，你可以考虑使用 [AVC](#avc_h.264) 或 [AV1](#av1)。例如，如果你使用 [MediaStream Recording API](/zh-CN/docs/Web/API/MediaStream_Recording_API) 录制视频，则在创建 {{domxref("MediaRecorder") 时可能会使用如下代码}} 目的：
```suggestion
考虑到你可以获得多接近无损的限制，你可以考虑使用 [AVC](#avc_h.264) 或 [AV1](#av1)。例如，如果你使用 [MediaStream Recording API](/zh-CN/docs/Web/API/MediaStream_Recording_API) 录制视频，则在创建 {{domxref("MediaRecorder")}} 时可能会使用如下代码}} 目的：
```

2022-09-12 04:33 UTC, yin1999 requested changes

2022-09-12 04:33 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +- 一个相当典型的 30 分钟视频会议需要大约 447.9 GB 的存储空间，而一部 2 小时的电影需要_几乎 1.79 **TB**（即 1790 GB）_的空间。
下划线用作斜体样式的话，前后必须是标点或空格，因此，请使用以下样式：

```suggestion
- 一个相当典型的 30 分钟视频会议需要大约 447.9 GB 的存储空间，而一部 2 小时的电影需要几乎 _1.79 **TB**_（即 1790 GB）的空间。
```

2022-09-12 04:33 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +      <td>Video Processor 9（视频处理器 9）</td>
VP8 VP9 并没有官方的中文翻译，若要添加注释内容，请使用`（VP8）`/`（VP9）`

2022-09-12 04:33 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +**[运动补偿](https://en.wikipedia.org/wiki/Motion_compensation)** 是一种寻找运动（相机或视野中的物体）并确定移动的物体在各个方向上有多少个像素的偏移的技术。确定后存储这些不能只用相似变化描述的像素偏移。本质上，编码器会找到移动的对象，然后构建一个类似于原始对象但所有对象都被转换到新位置的帧内。理论上，这近似于新帧的外观。然后，为了完成运动
请使用中文维基：

```suggestion
**[运动补偿](https://zh.wikipedia.org/wiki/运动补偿)** 是一种寻找运动（相机或视野中的物体）并确定移动的物体在各个方向上有多少个像素的偏移的技术。确定后存储这些不能只用相似变化描述的像素偏移。本质上，编码器会找到移动的对象，然后构建一个类似于原始对象但所有对象都被转换到新位置的帧内。理论上，这近似于新帧的外观。然后，为了完成运动补偿，需要找到剩余的差异，然后将对象移动的集合和像素差异的集合存储在表示新帧的数据中。这个描述偏移和像素差异的对象称为**残差帧**。
```

2022-09-12 04:33 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +      <th scope="row">规格</th>
统一翻译为规范：

```suggestion
      <th scope="row">规范</th>
```

2022-09-12 04:33 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +**[MPEG-2 Part 2](https://en.wikipedia.org/wiki/H.262/MPEG-2_Part_2)**是MPEG-2规范定义的视频格式，也偶尔会被提及通过其 {{Glossary("ITU")}} 名称，H.262。它与 MPEG-1 视频非常相似——事实上，任何 MPEG-2 播放器都可以自动处理 MPEG-1，而无需任何特殊工作——除了它已扩展为支持更高
中文维基：
```suggestion
**[MPEG-2 Part 2](https://zh.wikipedia.org/wiki/H.262)** 是 MPEG-2 规范定义的视频格式，也偶尔会被提及通过其 {{Glossary("ITU")}} 名称，H.262。它与 MPEG-1 视频非常相似——事实上，任何 MPEG-2 播放器都可以自动处理 MPEG-1，而无需任何特殊工作——除了它已扩展为支持更高的比特率和增强的编码技术。
```

2022-09-12 04:33 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +MPEG-2 有几个具有不同功能的配置文件。然后每个配置文件有四个级别可用，每个级别都会增加视频的属性，例如帧速率、分辨率、比特率等。大多数配置文件使用具有 4:2:0 色度二次采样的 Y'CbCr，但更高级的配置文件也支持 4:2:2。此外，还有四个级别，每个级别都支持更大的帧尺寸和比特率。例如，北美使用的电视 [ATSC](https://en.wikipedia.org/wiki/ATSC
使用中文维基

2022-09-12 04:33 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +      <th scope="row">规格</th>
规范

2022-09-12 04:33 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +2. 一个 **[MP4](/zh-CN/docs/Web/Media/Formats/Containers#mpeg-4_mp4)** 容器和 **[AVC](#avc_h.264)** (**H .264**) 视频编解码器，最好使用 **[AAC](/zh-CN/docs/Web/Media/Formats/Audio_codecs#aac)** 作为你的音频编解码器。这是因为带有 AVC
```suggestion
2. 一个 **[MP4](/zh-CN/docs/Web/Media/Formats/Containers#mpeg-4_mp4)** 容器和 **[AVC](#avc_h.264)** (**H.264**) 视频编解码器，最好使用 **[AAC](/zh-CN/docs/Web/Media/Formats/Audio_codecs#aac)** 作为你的音频编解码器。这是因为带有 AVC 和 AAC 编解码器的 MP4 容器是一种广泛支持的组合——事实上，每个主流浏览器都支持它——而且质量通常对大多数用例都很好。但是，请确保验证你是否符合许可证要求。
```

2022-09-12 04:33 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +> **注意：无论{{HTMLElement("video")}} 元素中是否有任何 {{HTMLElement("source")}} 元素，** {{HTMLElement("video")}} 元素都是需要闭合的 `</video> ` 标签。
参见：<https://developer.mozilla.org/zh-CN/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN#备注、警告和标注>

```suggestion
> **备注：** 无论 {{HTMLElement("video")}} 元素中是否有任何 {{HTMLElement("source")}} 元素，{{HTMLElement("video")}} 元素都是需要闭合的 `</video> ` 标签。
```

2022-09-12 04:33 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +考虑到你可以获得多接近无损的限制，你可以考虑使用 [AVC](#avc_h.264) 或 [AV1](#av1)。例如，如果你使用 [MediaStream Recording API](/zh-CN/docs/Web/API/MediaStream_Recording_API) 录制视频，则在创建 {{domxref("MediaRecorder")}} 时可能会使用如下代码}} 目的：
```suggestion
考虑到你可以获得多接近无损的限制，你可以考虑使用 [AVC](#avc_h.264) 或 [AV1](#av1)。例如，如果你使用 [MediaStream Recording API](/zh-CN/docs/Web/API/MediaStream_Recording_API) 录制视频，则在创建 {{domxref("MediaRecorder")}} 时可能会使用如下代码目的：
```

2022-09-12 04:33 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +此示例创建一个 `MediaRecorder`，配置为使用 BT.2100 HDR 以 4:4:4 色度二次采样和 [FLAC](/zh-CN/docs/Web/) 以 12 位颜色录制 [AV1](#av1) 视频Media/Formats/Audio_codecs#flac) 用于无损音频。生成的文件将使用视频和音频轨道之间共享的不超过 800 Mbps 的比特率。你可能需要根据硬件性能、你
注意这里的连接

2022-09-12 04:33 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +## 相关资料
```suggestion
## 参见
```

2022-09-15 06:48 UTC, yin1999 requested changes

2022-09-15 06:48 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +> **注意：** 无论{{HTMLElement("video")}} 元素中是否有任何 {{HTMLElement("source")}} 元素， {{HTMLElement("video")}} 元素都是需要闭合的 `</video> ` 标签。
```suggestion
> **备注：** 无论 {{HTMLElement("video")}} 元素中是否有任何 {{HTMLElement("source")}} 元素，{{HTMLElement("video")}} 元素都是需要闭合的 `</video> ` 标签。
```

2022-09-15 06:48 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +**Video Processor 9** (**VP9**) 是 Google 开发的旧 VP8 标准的继承者。与 VP8 一样，VP9 是完全开放且免版税的。其编解码性能与AVC相当或略快，但质量更好。 VP9 的编码视频质量在相似比特率下可与 HEVC 相媲美。
```suggestion
**Video Processor 9**（**VP9**）是 Google 开发的旧 VP8 标准的继承者。与 VP8 一样，VP9 是完全开放且免版税的。其编解码性能与 AVC 相当或略快，但质量更好。 VP9 的编码视频质量在相似比特率下可与 HEVC 相媲美。
```

2022-09-15 06:48 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +ITU 的**H.263** 编解码器主要设计用于低带宽情况。特别是，它的重点是 PSTN（公共交换电话网络）、{{Glossary("RTSP")}} 和 SIP（基于 IP 的视频会议）系统上的视频会议。尽管针对低带宽网络进行了优化，但它相当占用 CPU，并且可能无法在低端计算机上充分执行。数据格式类似于 MPEG-4 Part 2。
```suggestion
ITU 的 **H.263** 编解码器主要设计用于低带宽情况。特别是，它的重点是 PSTN（公共交换电话网络）、{{Glossary("RTSP")}} 和 SIP（基于 IP 的视频会议）系统上的视频会议。尽管针对低带宽网络进行了优化，但它相当占用 CPU，并且可能无法在低端计算机上充分执行。数据格式类似于 MPEG-4 Part 2。
```

2022-09-15 06:48 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +- 单帧全彩色高清 (1920x1080) 视频（每像素 4 字节）为 8,294,400 字节。
```suggestion
- 单帧全彩色高清（1920x1080）视频（每像素 4 字节）为 8,294,400 字节。 
```

2022-09-15 06:48 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +- 在典型的每秒 30 帧的情况下，每秒高清视频将占用 248,832,000 字节 (\~249 MB)。
```suggestion
- 在典型的每秒 30 帧的情况下，每秒高清视频将占用 248,832,000 字节（\~249 MB）。
```

2022-09-15 06:48 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +    视频质量和大小
```suggestion
    源视频格式和内容对编码视频质量和大小的潜在影响
```

2022-09-15 06:48 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +为了解决这个问题，并改善视频数据的搜索时间，将周期性的**关键帧**（也称为**帧内**或**i帧**）放置到视频文件中。关键帧是完整帧，用于修复当前可见的任何损坏或伪影残留。
```suggestion
为了解决这个问题，并改善视频数据的搜索时间，将周期性的**关键帧**（也称为**帧内**或 **i 帧**）放置到视频文件中。关键帧是完整帧，用于修复当前可见的任何损坏或伪影残留。
```

2022-09-15 06:48 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +          <a href="https://zh.wikipedia.org/wiki/%E8%8E%AB%E5%88%97%E6%B3%A2%E7%B4%8B"
```suggestion
          <a href="https://zh.wikipedia.org/wiki/莫列波紋"
```

2022-09-15 06:48 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
>            A
```suggestion
```

2022-09-15 06:48 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
>            >
```suggestion
          >是当源图像中的一个图案和编码器的操作方式在空间上略微失准时产生的大尺度空间干涉图案。然后，编码器生成的鬼影会在解码时在源图像的图案中引入奇怪的漩涡效果。
```

2022-09-15 06:48 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +          是当源图像中的一个图案和编码器的操作方式在空间上略微失准时产生的大尺度空间干涉图案。然后，编码器生成的鬼影会在解码时在源图像的图案中引入奇怪的漩涡效果。
```suggestion
```

2022-09-15 06:48 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +有损压缩算法会引入 **[振铃效应](https://zh.wikipedia.org/wiki/%E6%8C%AF%E9%88%B4%E6%95%88%E6%87%89)**，即对象外部区域被压缩算法生成的彩色像素污染的效果。当算法使用跨越对象与其背景之间的清晰边界的块时，就会发生这种情况。这在较高的压缩级别下尤其常见。
```suggestion
有损压缩算法会引入**[振铃效应](https://zh.wikipedia.org/wiki/振鈴效應)**，即对象外部区域被压缩算法生成的彩色像素污染的效果。当算法使用跨越对象与其背景之间的清晰边界的块时，就会发生这种情况。这在较高的压缩级别下尤其常见。
```

2022-09-15 06:48 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +请注意上方星星边缘周围的蓝色和粉红色条纹（以及步进和其他重要的压缩伪影）。那些边缘是振铃效应。振铃效应在某些方面类似于 [飞蚊噪声](#mosquito_noise)，除了振铃效果或多或少稳定不变，而蚊子噪音闪烁和移动。
```suggestion
请注意上方星星边缘周围的蓝色和粉红色条纹（以及步进和其他重要的压缩伪影）。那些边缘是振铃效应。振铃效应在某些方面类似于[飞蚊噪声](#mosquito_noise)，除了振铃效果或多或少稳定不变，而蚊子噪音闪烁和移动。
```

2022-09-15 06:48 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +**分色** 发生在压缩导致渐变中颜色细节丢失时。图像不是通过区域中的各种颜色进行平滑过渡，而是呈现为块状的，带有接近图像原始外观的颜色斑点。
```suggestion
**分色**发生在压缩导致渐变中颜色细节丢失时。图像不是通过区域中的各种颜色进行平滑过渡，而是呈现为块状的，带有接近图像原始外观的颜色斑点。
```

2022-09-15 06:48 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +飞蚊噪声鬼影最常见于 MPEG 视频中，但只要使用离散余弦变换 (DCT) 算法就会出现；例如 JPEG 静止图像。
```suggestion
飞蚊噪声鬼影最常见于 MPEG 视频中，但只要使用离散余弦变换（DCT）算法就会出现；例如 JPEG 静止图像。
```

2022-09-15 06:48 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +**飞蚊噪声**是一种时间鬼影，表现为噪声或**边缘繁忙**，表现为闪烁的朦胧或闪烁，大致跟随在具有硬边缘或前景对象和背景之间的尖锐过渡的对象的边缘之外。效果在外观上可能类似于 [振铃效应](#ringing) 。
```suggestion
**飞蚊噪声**是一种时间鬼影，表现为噪声或**边缘繁忙**，表现为闪烁的朦胧或闪烁，大致跟随在具有硬边缘或前景对象和背景之间的尖锐过渡的对象的边缘之外。效果在外观上可能类似于[振铃效应](#ringing) 。
```

2022-09-15 06:48 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +**[运动补偿](https://zh.wikipedia.org/wiki/%E8%BF%90%E5%8A%A8%E8%A1%A5%E5%81%BF)** 是一种寻找运动（相机或视野中的物体）并确定移动的物体在各个方向上有多少个像素的偏移的技术。确定后存储这些不能只用相似变化描述的像素偏移。本质上，编码器会找到移动的对象，然后构建一个类似于原始对象但所有对象都被转换到新位置的帧内。理论上，这近
```suggestion
**[运动补偿](https://zh.wikipedia.org/wiki/运动补偿)**是一种寻找运动（相机或视野中的物体）并确定移动的物体在各个方向上有多少个像素的偏移的技术。确定后存储这些不能只用相似变化描述的像素偏移。本质上，编码器会找到移动的对象，然后构建一个类似于原始对象但所有对象都被转换到新位置的帧内。理论上，这近似于新帧的外观。然后，为了完成运动补偿，需要找到剩余的差异，然后将对象移动的集合和像素差异的集合存储在表示新帧的数据中。这个描述偏移和像素差异的对象称为**残差帧**。
```

2022-09-15 06:48 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +          href="https://zh.wikipedia.org/wiki/%E8%BF%90%E5%8A%A8%E8%A1%A5%E5%81%BF#Illustrated_example"
```suggestion
          href="https://en.wikipedia.org/wiki/Motion_compensation#Illustrated_example"
```

2022-09-15 06:48 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +在 Web 浏览器的 HTML 内容中，AVC 具有广泛的兼容性，并且许多平台支持 AVC 媒体的硬件编码和解码。但是，在你的项目中选择使用 AVC 之前，请注意其 [许可要求](https://www.mpegla.com/programs/avc-h-264/)！
```suggestion
在 Web 浏览器的 HTML 内容中，AVC 具有广泛的兼容性，并且许多平台支持 AVC 媒体的硬件编码和解码。但是，在你的项目中选择使用 AVC 之前，请注意其[许可要求](https://www.mpegla.com/programs/avc-h-264/)！
```

2022-09-15 06:48 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +      <td> Lossy <a href="https://zh.wikipedia.org/wiki/%E7%A6%BB%E6%95%A3%E4%BD%99%E5%BC%A6%E5%8F%98%E6%8D%A2">基于 DCT 的算法</a>, 虽然可以在图像中创建无损宏块</td>
```suggestion
      <td> Lossy <a href="https://zh.wikipedia.org/wiki/离散余弦变换">基于 DCT 的算法</a>, 虽然可以在图像中创建无损宏块</td>
```

2022-09-15 06:48 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +HTML 内容中的 VP8 有很好的浏览器支持，尤其是在 [WebM](/zh-CN/docs/Web/Media/Formats/Containers#webm) 文件中。这使得 VP8 成为你的内容的理想候选者，尽管如果你可以使用 VP9，它是一个更好的选择。 Web 浏览器是_需要_支持 WebRTC 的 VP8，但并非所有这样做的浏览器都支持 HTML 音频和视频元素。
```suggestion
HTML 内容中的 VP8 有很好的浏览器支持，尤其是在 [WebM](/zh-CN/docs/Web/Media/Formats/Containers#webm) 文件中。这使得 VP8 成为你的内容的理想候选者，尽管如果你可以使用 VP9，它是一个更好的选择。Web 浏览器是*需要*支持 WebRTC 的 VP8，但并非所有这样做的浏览器都支持 HTML 音频和视频元素。
```

2022-09-15 06:48 UTC, yin1999 commented on files/zh-cn/web/media/formats/video_codecs/index.md
> +        基于有损<a href="https://zh.wikipedia.org/wiki/%E7%A6%BB%E6%95%A3%E4%BD%99%E5%BC%A6%E5%8F%98%E6%8D%A2">DCT 的算法</a>
```suggestion
        基于有损 <a href="https://zh.wikipedia.org/wiki/离散余弦变换">DCT 的算法</a>
```

2022-09-15 07:19 UTC, yin1999 approved these changes

2022-09-15 07:23 UTC, merged