**Note:** **メモ**を**Note:** に置換
mdn/translated-content pull request #8484
Opened 2022-09-13 21:51 UTC by pea-sys

ほとんどのページが**Note:**と表現していたので
多数派の表現に寄せます

2022-09-16 16:13 UTC, mfuji09 requested changes

2022-09-16 16:13 UTC, mfuji09 commented on files/ja/conflicting/learn/javascript/objects/classes_in_javascript/index.md
> -> **Note:** **メモ**: 通常、コンストラクター関数の名前は大文字で始まります。コードの中で、コンストラクター関数がより容易に認識されるようにするための慣習です。
**メモ** の後の : も削除してください。

2022-09-16 22:16 UTC, pea-sys commented on files/ja/conflicting/learn/javascript/objects/classes_in_javascript/index.md
> -> **Note:** **メモ**: 通常、コンストラクター関数の名前は大文字で始まります。コードの中で、コンストラクター関数がより容易に認識されるようにするための慣習です。
レビューありがとうございます。
指摘を元に修正しました。
75dd00f3776a8e3507a434979e88bdeb32a01549

2022-09-18 04:13 UTC, mfuji09 approved these changes
OKです。

2022-09-18 04:13 UTC, merged

2022-09-18 22:20 UTC, pea-sys commented
#7848