Finish translation in learn/javascript/howto
mdn/translated-content pull request #8497
Opened 2022-09-14 09:18 UTC by jasonren0403

Note: some of the permulinks left untouched, because the corresponding document is not updated

2022-09-14 09:19 UTC, jasonren0403 commented on files/zh-cn/learn/javascript/howto/index.md
> +- [我该使用什么样的机制将时间代码添加到我的网页上？](/zh-CN/docs/Learn/JavaScript/Building_blocks/Events#What_mechanism_should_I_use)
```suggestion
- [我该使用什么样的机制将事件代码添加到我的网页上？](/zh-CN/docs/Learn/JavaScript/Building_blocks/Events#What_mechanism_should_I_use)
```

2022-09-15 00:23 UTC, yin1999 requested changes

2022-09-15 00:23 UTC, yin1999 commented on files/zh-cn/learn/javascript/howto/index.md
> +### Web API 接口
尽量保持和英文文档一致吧，英文文档没有写 `interface`，而 API 的 `I` 即为接口，无需额外再补充接口一词：

```suggestion
### Web API
```

2022-09-15 00:24 UTC, yin1999 approved these changes

2022-09-15 00:26 UTC, merged