Markdown conversion for `pt-BR` - Replace - Games section :warning:  Do not squash :warning:
mdn/translated-content pull request #8511
Opened 2022-09-15 04:20 UTC by SphinxKnight

Follow-up of https://github.com/mdn/translated-content/pull/8458

2022-09-15 04:20 UTC, SphinxKnight commented
Please :warning: Do not squash merge :warning:

2022-09-17 01:18 UTC, josielrocha requested changes
Hi @SphinxKnight!

I have made some suggestions, could yout please check them out?

2022-09-17 01:18 UTC, josielrocha commented on files/pt-br/games/tools/asm.js/index.md
> +
```suggestion
## O que é asm.js, exatamente?

```

2022-09-17 01:18 UTC, josielrocha commented on files/pt-br/games/introduction_to_html5_game_development/index.md
> +  - : Acessar dados binários brutos de dentro do JavaScript; Manipule texturas GL, dados de jogos ou qualquer outra coisa.
```suggestion
- [SVG](/pt-BR/docs/SVG) (Gráficos Vetorias Escaláveis)
  - : Crie gráficos vetoriais que sejam dimensionados sem problemas, independemente do tamanho ou da resolução da exibição do usuário.

- [Typed Arrays](/pt-BR/docs/JavaScript/Typed_arrays)
  - : Acessar dados binários brutos de dentro do JavaScript; Manipule texturas GL, dados de jogos ou qualquer outra coisa.
```

2022-09-17 01:18 UTC, josielrocha commented on files/pt-br/games/index.md
> +  - : Lista dos frameworks HTML5 mais populares para jogos, juntamente com a sua classificação, benefícios e exemplos.
```suggestion
  - : Fóruns para desenvolvedores, criadores de framework e publicadores. Faça perguntas, obtenha retorno, ajude outras pessoas.

- [HTML5 Game Engine](http://html5gameengine.com/)
  - : Lista dos frameworks HTML5 mais populares para jogos, juntamente com a sua classificação, benefícios e exemplos.
```

2022-09-19 10:58 UTC, SphinxKnight commented
@josielrocha since the feedback was on "empty" content left after the conversion tool and only touched 3 documents, I've updated accordingly. Thanks a lot for the review :bow:

2022-09-19 12:44 UTC, josielrocha approved these changes

2022-09-19 13:28 UTC, merged