Markdown conversion for `pt-BR` - Replace - API section :warning:  Do not squash :warning:
mdn/translated-content pull request #8517
Opened 2022-09-15 05:10 UTC by SphinxKnight

Follow-up of https://github.com/mdn/translated-content/pull/7961
Conversion report: https://gist.github.com/SphinxKnight/e66a41050cc8314ab9fcfd527ef8201f#file-md-conversion-problems-report-2022-09-15t05_08_30-471z-md

2022-09-15 05:10 UTC, SphinxKnight commented
Please :warning: Do not squash merge :warning:

2022-09-17 01:14 UTC, josielrocha requested changes
Hi @SphinxKnight,
Thank you for your precious contribution.

I have mad some suggestions and I would appreciate if you could check them.
Thank you a lot!

2022-09-17 01:14 UTC, josielrocha commented on files/pt-br/web/api/document/close/index.md
> +O metodo `document.close()` termina a gravação em um documento, aberto com [document.open()](/en/DOM/document.open "en/DOM/document.open").
```suggestion
O método **`document.close()`** termina a gravação em um documento, aberto com [document.open()](/en/DOM/document.open "en/DOM/document.open").
```

2022-09-17 05:09 UTC, SphinxKnight commented
> Hi @SphinxKnight, Thank you for your precious contribution.
> 
> I have made some suggestions and I would appreciate if you could check them. Thank you a lot!

I would apply the ones related to "markdown-conversion" related issues. Otherwise, I think it would be best to address the rest later (ex. https://github.com/mdn/translated-content/pull/8517#discussion_r973519163 which was already an issue before the conversion). Moreover, since this PR's commits will not be squashed, that means introducing "more" commits to the main history.

I can file issues for each comment if you prefer. That way, we can fix them afterwards.

Please let me know, I don't want to block things and if you definitely prefer introducing those changes now, I'll comply :)

2022-09-17 11:45 UTC, josielrocha commented
> > Hi @SphinxKnight, Thank you for your precious contribution.
> > I have made some suggestions and I would appreciate if you could check them. Thank you a lot!
> 
> I would apply the ones related to "markdown-conversion" related issues. Otherwise, I think it would be best to address the rest later (ex. [#8517 (comment)](https://github.com/mdn/translated-content/pull/8517#discussion_r973519163) which was already an issue before the conversion). Moreover, since this PR's commits will not be squashed, that means introducing "more" commits to the main history.
> 
> I can file issues for each comment if you prefer. That way, we can fix them afterwards.
> 
> Please let me know, I don't want to block things and if you definitely prefer introducing those changes now, I'll comply :)

It sounds good! Let's fix that after Markdown migration.

2022-09-17 11:45 UTC, josielrocha approved these changes

2022-09-19 11:04 UTC, SphinxKnight commented on files/pt-br/web/api/angle_instanced_arrays/index.md
> +> **Nota:** **Disponibilidade:** Esta extenção só está disponível para contextos {{domxref("WebGLRenderingContext", "WebGL1", "", 1)}}. Em {{domxref("WebGL2RenderingContext", "WebGL2", "", 1)}}, a fu
created as https://github.com/mdn/translated-content/issues/8627

2022-09-19 11:07 UTC, SphinxKnight commented
@josielrocha sorry for the rush previously, I've re-read the comments and only one was an actual "content" update, I've filed an issue for it and applied the rest of the suggestions :) 

Thanks!

2022-09-19 11:10 UTC, SphinxKnight commented
And I'll file an issue to check for patterns with `**` being escaped, I know we had to deal with some of them in `fr`

2022-09-19 11:12 UTC, merged