Issue 614
mdn/translated-content pull request #8580
Opened 2022-09-17 06:49 UTC by Retsu-MURAKAMI

Translated into Japanese. review, please.

2022-09-18 04:16 UTC, mfuji09 requested changes
スタイル上の修正をお願いします。
なお、日本語訳へのプルリクエストは日本人しか読みませんので、日本語でどうぞ。

2022-09-18 04:16 UTC, mfuji09 commented on files/ja/glossary/code_point/index.md
> +**コードポイント**は、（Unicodeなどの）テキストを表現するシステムにおいて、抽象文字を表現するために割り当てられた番号のことです。Unicodeでは、コードポイントは、"U+1234"という形式で表現されます。ここで「1234」が割り当てられた番号です。例えば、"A"という文字には、U+0041というコードポイントが割り当てられています。
英数字と日本語の間には、1文字の半角スペースを入れてください。以降の部分も同様に修正してください。
```suggestion
**コードポイント**は、（Unicode などの）テキストを表現するシステムにおいて、抽象文字を表現するために割り当てられた番号のことです。 Unicode では、コードポイントは、 "U+1234" という形式で表現されます。ここで「1234」が割り当てられた番号です。例えば、 "A" という文字には、 U+0041 というコードポイントが割り当てられています。
```

2022-09-18 14:17 UTC, Retsu-MURAKAMI commented on files/ja/glossary/code_point/index.md
> +**コードポイント**は、（Unicodeなどの）テキストを表現するシステムにおいて、抽象文字を表現するために割り当てられた番号のことです。Unicodeでは、コードポイントは、"U+1234"という形式で表現されます。ここで「1234」が割り当てられた番号です。例えば、"A"という文字には、U+0041というコードポイントが割り当てられています。
修正しました。確認をお願いします。また丸括弧は半角にしましたが、全角のままのほうがよければ元に戻します。

2022-09-18 14:20 UTC, Retsu-MURAKAMI commented on files/ja/glossary/code_point/index.md
> +**コードポイント**は、（Unicodeなどの）テキストを表現するシステムにおいて、抽象文字を表現するために割り当てられた番号のことです。Unicodeでは、コードポイントは、"U+1234"という形式で表現されます。ここで「1234」が割り当てられた番号です。例えば、"A"という文字には、U+0041というコードポイントが割り当てられています。
ごめんなさい、修正漏れがあったのでしばらくお待ち下さい。

2022-09-18 14:26 UTC, Retsu-MURAKAMI commented on files/ja/glossary/code_point/index.md
> +**コードポイント**は、（Unicodeなどの）テキストを表現するシステムにおいて、抽象文字を表現するために割り当てられた番号のことです。Unicodeでは、コードポイントは、"U+1234"という形式で表現されます。ここで「1234」が割り当てられた番号です。例えば、"A"という文字には、U+0041というコードポイントが割り当てられています。
修正完了しました。確認をお願いします。

2022-09-19 13:44 UTC, mfuji09 approved these changes
OKです。

2022-09-19 13:44 UTC, merged