用語集 - Advance measure の翻訳
mdn/translated-content pull request #8582
Opened 2022-09-17 08:02 UTC by hskwakr

### 概要
日本語ページを新規追加して翻訳しました。
- https://developer.mozilla.org/en-US/docs/glossary/advance_measure

### 関連
- https://github.com/mozilla-japan/translation/issues/639

2022-09-18 04:21 UTC, mfuji09 requested changes
英数字と日本語文字の間のスペースが空いていないところがありましたので、修正を提案します。

2022-09-18 04:21 UTC, mfuji09 commented on files/ja/glossary/advance_measure/index.md
> +この用語は幾つかのCSSの {{cssxref("&lt;length&gt;")}} の単位の定義で使われます。
```suggestion
この用語は幾つかの CSS の {{cssxref("&lt;length&gt;")}} の単位の定義で使われます。
```

2022-09-18 04:21 UTC, mfuji09 commented on files/ja/glossary/advance_measure/index.md
> +_advance measure_ における単位 `ch` は文字"0"の書体の幅または高さを表し、記述方向（横書き・縦書き）によります。同様に単位 `ic` は文字"水"の書体の幅または高さを表します。
```suggestion
_advance measure_ における単位 `ch` は文字 "0" の書体の幅または高さを表し、記述方向（横書き・縦書き）によります。同様に単位 `ic` は文字 "水" の書体の幅または高さを表します。
```

2022-09-18 05:14 UTC, hskwakr commented
@mfuji09 レビューありがとうございます。提案していただいた箇所を修正しました。ご確認よろしくお願いします。

2022-09-20 16:36 UTC, mfuji09 approved these changes
OKです。

2022-09-20 16:37 UTC, merged