zh-cn(translate): object.hasown
mdn/translated-content pull request #8620
Opened 2022-09-19 06:41 UTC by Jack-Zhang-1314

2022-09-19 11:58 UTC, yin1999 requested changes

2022-09-19 14:26 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/global_objects/object/hasown/index.md
> +建议在 {{jsxref("Object.hasOwnProperty()")}} 上使用它，因为它适用于使用 `Object.create(null)` 创建的对象以及覆盖继承了 `hasOwnProperty()` 方法的对象。尽管可以通过在外部对象上调用 `Object.prototype.hasOwnProperty()` 解决这些问题，但是 `Object.hasOwn()` 更加直观
```suggestion
建议通过 {{jsxref("Object.hasOwnProperty()")}} 方法使用它，因为它适用于使用 `Object.create(null)` 创建的对象以及覆盖继承了 `hasOwnProperty()` 方法的对象。尽管可以通过在外部对象上调用 `Object.prototype.hasOwnProperty()` 解决这些问题，但是 `Object.hasOwn()` 更加直观。
```

2022-09-20 07:09 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/object/hasown/index.md
> +建议在 {{jsxref("Object.hasOwnProperty()")}} 上使用它，因为它适用于使用 `Object.create(null)` 创建的对象以及覆盖继承了 `hasOwnProperty()` 方法的对象。尽管可以通过在外部对象上调用 `Object.prototype.hasOwnProperty()` 解决这些问题，但是 `Object.hasOwn()` 更加直观
```suggestion
建议使用此方法替代 {{jsxref("Object.hasOwnProperty()")}}，因为它适用于使用 `Object.create(null)` 创建的对象以及覆盖了继承的 `hasOwnProperty()` 方法的对象。尽管可以通过在外部对象上调用 `Object.prototype.hasOwnProperty()` 解决这些问题，但是 `Object.hasOwn()` 更加直观。
```

2022-09-20 07:11 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/object/hasown/index.md
> +建议在 {{jsxref("Object.hasOwnProperty()")}} 上使用它，因为它适用于使用 `Object.create(null)` 创建的对象以及覆盖继承了 `hasOwnProperty()` 方法的对象。尽管可以通过在外部对象上调用 `Object.prototype.hasOwnProperty()` 解决这些问题，但是 `Object.hasOwn()` 更加直观
不建议仅使用机器翻译而不去核对原文，有些语句是明显有逻辑问题的。请仔细检查翻译，然后再提交 PR。看错误的翻译原不如直接看英文文档。

2022-09-20 07:12 UTC, merged

2022-09-20 12:31 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/javascript/reference/global_objects/object/hasown/index.md
> +建议在 {{jsxref("Object.hasOwnProperty()")}} 上使用它，因为它适用于使用 `Object.create(null)` 创建的对象以及覆盖继承了 `hasOwnProperty()` 方法的对象。尽管可以通过在外部对象上调用 `Object.prototype.hasOwnProperty()` 解决这些问题，但是 `Object.hasOwn()` 更加直观
你是对的，机器翻译的往往比我好，如果有些问题，往往是我自己翻译的 😮‍💨