Update Input/date
mdn/translated-content pull request #8624
Opened 2022-09-19 07:56 UTC by jasonren0403

sync content and remove dead asset links

2022-09-19 08:27 UTC, yin1999 requested changes

2022-09-19 08:27 UTC, yin1999 commented on files/zh-cn/web/html/element/input/date/index.md
> +该代码中可能有趣的另一部分是特性检测代码。要检测浏览器是否支持 `<input type="date">`，我们创建一个新的 {{htmlelement("input")}} 元素，尝试将其 `type` 设置为 `date`，然后立即检查其 `type` 值。不支持的浏览器将返回 `text`，因为 `date` 类型将回退为 `text` 类型。如果不支持 `<input type="dat
```suggestion
该代码中可能有趣的另一部分是特性检测代码。要检测浏览器是否支持 `<input type="date">`。

我们创建一个新的 {{htmlelement("input")}} 元素，尝试将其 `type` 设置为 `date`，然后立即检查其 `type` 值。不支持的浏览器将返回 `text`，因为 `date` 类型将回退为 `text` 类型。如果不支持 `<input type="date">`，我们将隐藏原生选择器并显示后备选择器 UI（{{htmlelement("select")}} 元素）。
```

2022-09-19 08:27 UTC, yin1999 commented on files/zh-cn/web/html/element/input/date/index.md
> +> **备注：** 请记住有些年份有 53 周（见 [**每年的周数**](https://zh.wikipedia.org/wiki/ISO週日曆#每年的星期)）！当你在开发产品应用时应当考虑这个问题。
```suggestion
> **备注：** 请记住有些年份有 53 周（见[**每年的周数**](https://zh.wikipedia.org/wiki/ISO週日曆#每年的星期)）！当你在开发产品应用时应当考虑这个问题。
```

2022-09-19 08:27 UTC, yin1999 commented on files/zh-cn/web/html/element/input/date/index.md
> +    previousDay = daySelect.value;
请使用两个空格

2022-09-19 14:24 UTC, jasonren0403 commented
其他的修了，用空格的那个不知道为啥突然IDE格式化不太好用

2022-09-20 03:19 UTC, jasonren0403 commented on files/zh-cn/web/html/element/input/date/index.md
> +在本章，我们将研究 `<input type="date">` 基础的和更复杂的的用法。
```suggestion
在本章，我们将研究 `<input type="date">` 基础的和更复杂的用法。
```

2022-09-20 07:02 UTC, yin1999 commented
> 其他的修了，用空格的那个不知道为啥突然IDE格式化不太好用

也请依照英文文档更新

2022-09-20 07:24 UTC, yin1999 approved these changes

2022-09-20 07:24 UTC, merged