Update Input/reset
mdn/translated-content pull request #8659
Opened 2022-09-20 10:44 UTC by jasonren0403

2022-09-20 10:50 UTC, jasonren0403 commented on files/zh-cn/web/html/element/input/reset/index.md
> +- [表单和按钮](/zh-CN/docs/Learn/HTML/Forms_and_buttons)
```suggestion
- [表单和按钮](/zh-CN/docs/Learn/Forms/Basic_native_form_controls#按钮)
```

2022-09-20 10:54 UTC, jasonren0403 commented on files/zh-cn/web/html/element/input/reset/index.md
> +- [HTML 表单](/zh-CN/docs/Learn/HTML/Forms)
```suggestion
- [HTML 表单](/zh-CN/docs/Learn/Forms)
```

2022-09-21 00:20 UTC, yin1999 requested changes

2022-09-21 00:20 UTC, yin1999 commented on files/zh-cn/web/html/element/input/reset/index.md
> +如果您未指定 `value`，则会获得一个带有默认标签的按钮（通常为“Reset”，但这将根据{{Glossary("user agent", "用户代理")}}而有所不同）：
中文环境应该会显示为：“重置”：

```suggestion
如果你未指定 `value`，则会获得一个带有默认标签的按钮（通常为“重置”，但这将根据{{Glossary("user agent", "用户代理")}}而有所不同）：
```

2022-09-21 00:20 UTC, yin1999 commented on files/zh-cn/web/html/element/input/reset/index.md
> +要禁用重置按钮，只需在其上指定 {{htmlattrxref("disabled")}} 的全局属性，如下所示：
```suggestion
要禁用重置按钮，只需在其上指定 {{htmlattrxref("disabled")}} 全局属性，如下所示：
```

2022-09-21 00:20 UTC, yin1999 commented on files/zh-cn/web/html/element/input/reset/index.md
> +您可以在运行时通过简单地将 `disable` 设置为 `true` 或 `false` 来启用和禁用按钮。在 JavaScript 中，使用 `btn.disabled = true` 或 `btn.disabled = false`。
```suggestion
你可以在运行时通过简单地将 `disable` 设置为 `true` 或 `false` 来启用和禁用按钮。在 JavaScript 中，使用 `btn.disabled = true` 或 `btn.disabled = false`。
```

2022-09-21 00:20 UTC, yin1999 commented on files/zh-cn/web/html/element/input/reset/index.md
> +> **备注：** 有关启用和禁用按钮的更多观念，请参见 [`<input type="button">`](/zh-CN/docs/Web/HTML/Element/input/button#启用与禁用按钮) 页面。
用“观念”是不是不太合适

2022-09-21 00:20 UTC, yin1999 commented on files/zh-cn/web/html/element/input/reset/index.md
>  ## 例子
```suggestion
## 示例
```

2022-09-21 06:36 UTC, jasonren0403 commented on files/zh-cn/web/html/element/input/reset/index.md
> +> **备注：** 有关启用和禁用按钮的更多观念，请参见 [`<input type="button">`](/zh-CN/docs/Web/HTML/Element/input/button#启用与禁用按钮) 页面。
```suggestion
> **备注：** 有关启用和禁用按钮的更多概念，请参见 [`<input type="button">`](/zh-CN/docs/Web/HTML/Element/input/button#启用与禁用按钮) 页面。
```

2022-09-21 06:39 UTC, yin1999 approved these changes

2022-09-21 06:43 UTC, merged