Initial translation for `animation-composition`
mdn/translated-content pull request #8662
Opened 2022-09-20 11:54 UTC by SphinxKnight

2022-09-20 17:01 UTC, tristantheb requested changes
Some sentences sounds wrong orally, I think, I've left you some suggestions ^^

2022-09-20 19:23 UTC, SphinxKnight commented on files/fr/web/css/animation-composition/index.md
> +  - : La valeur d'effet surcharge la valeur sous-jacente de la propriété. Il s'agit de la valeur par défaut.
hmm justement j'ai hésité entre "la valeur de l'effet" et "la valeur d'effet" mais j'ai penché pour la deuxième option, car ce sont les valeurs dont on parle ici (underlying value vs effect value)

(OK pour le remplace)

2022-09-20 19:25 UTC, SphinxKnight commented on files/fr/web/css/animation-composition/index.md
> +  - : La valeur d'effet est construite à partir de la valeur sous-jacente de la propriété. L'opération produit un effet additif. Pour les types d'animation pour lesquels l'opération d'addition n'est
je ne suis pas d'accord ici non plus ^ ^
"This operation produces an additive effect." : "additive" ne se traduit pas en "additionnel", de même, "the addition operation is not commutative" ne parle pas d'une opération supplémentaire mais bien de l'addition.

2022-09-21 20:07 UTC, tristantheb commented on files/fr/web/css/animation-composition/index.md
> +  - : La valeur d'effet surcharge la valeur sous-jacente de la propriété. Il s'agit de la valeur par défaut.
Yep ok, je vois l'idée après coup ^^ J'ai changé pour garder le "remplace" ;)

2022-09-21 20:08 UTC, tristantheb approved these changes
👌🏻

2022-09-21 20:10 UTC, merged