Use french link
mdn/translated-content pull request #8698
Opened 2022-09-21 14:47 UTC by Benjioe

2022-09-21 15:47 UTC, cw118 requested changes
Merci pour cette PR @Benjioe !

J'ai apposé une suggestion car il faut utiliser le lien/*slug* anglais ("canonique") même pour la locale française (et j'en ai profité pour proposer d'autres corrections mineures :)).

2022-09-21 20:19 UTC, tristantheb commented on files/fr/games/tutorials/2d_breakout_game_pure_javascript/bounce_off_the_walls/index.md
> +Nous sommes maintenant arrivés au stade où notre balle se déplace et reste sur le plateau de jeu. Dans le quatrième chapitre, nous examinerons la mise en place d'une raquette contrôlable - voir [Raqu
@Benjioe Cf ce bloque de suggestion concernant la PR https://github.com/mdn/translated-content/pull/8697

2022-09-23 19:58 UTC, cw118 approved these changes
Merci beaucoup pour ces corrections @Benjioe !

2022-09-23 19:58 UTC, merged

2022-09-26 11:42 UTC, Benjioe commented
@cw118 je me suis rendu compte sur le lien de preview que :
- L'url du lien Suivant de l'entête n'est pas le même que celui du pied de page
- D'après ce que je vois de la prod, c'est plutôt le lien en entête qui est bon (a cause d'un 'docs_fr' qui apparaît dans l'URL du bas)

Je peux faire un patch où il faut une nouvelle PR ?

2022-09-26 12:06 UTC, SphinxKnight commented
@Benjioe je me permets de répondre ici :) Vu que cette PR a été fusionnée, autant en ouvrir une autre pour compléter :)

2022-09-26 17:15 UTC, cw118 commented
Mea culpa, vous avez raison 😅

Oui vous pouvez créer une nouvelle PR pour corriger les liens :)