docs: update set content
mdn/translated-content pull request #8723
Opened 2022-09-22 06:24 UTC by YangFong

2022-09-22 23:43 UTC, yin1999 requested changes

2022-09-22 23:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/set/foreach/index.md
> +    - `value`, `key`
```suggestion
    - `value`、`key`
```

2022-09-22 23:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/set/foreach/index.md
> +      - : `Set` 中正在处理的当前元素。因为 `Set` 中没有键，所以两个参数的值都被传递。
```suggestion
      - : `Set` 中正在处理的当前元素。因为 `Set` 中没有键，所以 `value` 会被共同传递给这两个参数。
```

2022-09-22 23:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/set/foreach/index.md
> +但是由于集合对象中没有索引（keys），所以前两个参数都是 {{domxref("Set")}} 中元素的值（**values**），之所以这样设计回调函数是为了和 {{jsxref("Map.foreach", "Map")}} 以及 {{jsxref("Array.forEach","Array")}} 的 `forEach()` 函数用法保持一致。
注意翻译、复数形式：

```suggestion
但是由于集合对象中没有键（key），所以前两个参数都是 {{jsxref("Set")}} 中元素的值（**value**），之所以这样设计回调函数是为了和 {{jsxref("Map.foreach", "Map")}} 以及 {{jsxref("Array.forEach","Array")}} 的 `forEach()` 函数用法保持一致。
```

2022-09-22 23:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/set/has/index.md
> +**`has()`** 方法返回一个布尔值来指示对应的值是否存在 `Set` 对象中。
```suggestion
**`has()`** 方法返回一个布尔值来指示对应的值是否存在于 `Set` 对象中。
```

2022-09-22 23:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/set/size/index.md
> +**`size`** 属性将会返回 {{jsxref("Set")}} 对象中元素的个数。
```suggestion
**`size`** 属性将会返回 {{jsxref("Set")}} 对象中（不重复）元素的个数。
```

2022-09-22 23:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/set/size/index.md
> +`size` 的值是一个整数，表示 `Set` 对象有多少条目。`size` 的集合访问函数是 `undefined`; 你不能改变这个属性。
```suggestion
`size` 的值是一个整数，表示 `Set` 对象有多少条目。`size` 的 set 访问函数是 `undefined`；你不能改变这个属性。
```

2022-09-22 23:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/set/delete/index.md
> +
```suggestion
```

2022-09-22 23:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/set/clear/index.md
> +**`clear()`** 方法将移除 `Set` 对象中所有元素。
不是 promise，不建议加上“将”字：

```suggestion
**`clear()`** 方法移除 `Set` 对象中所有元素。
```

2022-09-22 23:43 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/set/add/index.md
> +mySet.add(5).add('some text'); // chainable
```suggestion
mySet.add(5).add('some text'); // 可以链式调用
```

2022-09-22 23:57 UTC, YangFong commented on files/zh-cn/web/javascript/reference/global_objects/set/size/index.md
> +**`size`** 属性将会返回 {{jsxref("Set")}} 对象中元素的个数。
此处改为‘唯一的’或许更合适

2022-09-23 00:02 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/set/size/index.md
> +**`size`** 属性将会返回 {{jsxref("Set")}} 对象中元素的个数。
可以

2022-09-23 00:09 UTC, yin1999 approved these changes

2022-09-23 00:10 UTC, merged