Firefox 105 for developersを翻訳
mdn/translated-content pull request #8748
Opened 2022-09-23 02:23 UTC by yyss

Sep 21, 2022の英語版に対応。

2022-10-01 14:08 UTC, mfuji09 requested changes
1件の修正をお願いします。
また、その後で原文が更新されているようですので、原文の更新を反映していただけると幸いです。

2022-10-01 14:08 UTC, mfuji09 commented on files/ja/mozilla/firefox/releases/105/index.md
> +tags:
tags: は翻訳版には含めないようお願いします。
代わりに、 l10n: sourceCommit: を加えてください。加え方は、以下の記事を参照ください。
https://mozilla-japan.github.io/mdn-translation-guide/new-translation-procedure-2.html

2022-10-02 12:21 UTC, yyss commented
l10n: sourceCommit: に変更しました。
また、最新の英語版に合わせて更新しました。

2022-10-03 15:27 UTC, mfuji09 approved these changes
ありがとうございます。

2022-10-03 15:27 UTC, merged