docs: update content for strict_equality
mdn/translated-content pull request #8776
Opened 2022-09-24 12:22 UTC by YangFong

2022-09-24 12:24 UTC, YangFong commented
这个翻译我感觉存在争议，到底叫“全等“（JS  高级程序设计），还是叫”严格“（你不知道的 JS（中卷））。

2022-09-24 23:04 UTC, yin1999 requested changes

2022-09-24 23:04 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/strict_equality/index.md
> +全等运算符（`===`）会检查它的两个操作数是否相等，并且返回一个布尔值结果。与[相等运算符](/en-US/docs/Web/JavaScript/Reference/Operators/Equality)不同，全等运算符总是认为不同类型的操作数是不同的。
注意链接指向的locale


```suggestion
全等运算符（`===`）会检查它的两个操作数是否相等，并且返回一个布尔值结果。与[相等运算符](/zh-CN/docs/Web/JavaScript/Reference/Operators/Equality)不同，全等运算符总是认为不同类型的操作数是不同的。
```

2022-09-24 23:42 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/strict_equality/index.md
> +- [严格不等于运算符](/zh-CN/docs/Web/JavaScript/Reference/Operators/Strict_inequality)
可以考虑统一一下翻译：

```suggestion
- [不相等运算符](/zh-CN/docs/Web/JavaScript/Reference/Operators/Inequality)
- [严格不相等运算符](/zh-CN/docs/Web/JavaScript/Reference/Operators/Strict_inequality)
```

`Strict equality` 可翻译为“严格相等”，这样不会对读者造成困扰。

2022-09-24 23:46 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/strict_equality/index.md
> +全等运算符（`===` 和 `!==`）使用[全等比较算法](http://www.ecma-international.org/ecma-262/5.1/#sec-11.9.6)来比较两个操作数。
```suggestion
全等运算符（`===` 和 `!==`）提供了[严格相等判定](/zh-CN/docs/Web/JavaScript/Equality_comparisons_and_sameness#严格相等)语义。
```

2022-09-24 23:47 UTC, YangFong commented on files/zh-cn/web/javascript/reference/operators/strict_equality/index.md
> +- [严格不等于运算符](/zh-CN/docs/Web/JavaScript/Reference/Operators/Strict_inequality)
那对应的篇章和其他位置的外链也要进行统一转换

2022-09-24 23:48 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/operators/strict_equality/index.md
> +- [严格不等于运算符](/zh-CN/docs/Web/JavaScript/Reference/Operators/Strict_inequality)
请另开PR

2022-09-25 00:13 UTC, yin1999 approved these changes

2022-09-25 00:16 UTC, merged