[FEAT] add ko translated guildline
mdn/translated-content pull request #878
Opened 2021-05-16 15:14 UTC by hochan222

add ko translated guildline

draft

2021-05-16 15:50 UTC, hochan222 commented
@alattalatta 말씀해주신 내용 가이드에 정리해보았습니다. 한번 확인해주실 수 있으신가요?

2021-05-16 16:32 UTC, alattalatta requested changes
고생하셨습니다...!

저도 부족한 부분이 너무 많았어서 확인해주셨으면 하는 부분이 몇 개 있어요, 특히 Iterate가, 저는 여전히 반복보다는 순회가 더 의미에 부합하는 것 같지만 이게 대중적으로도 괜찮은지 잘 모르겠네요.

2021-05-16 16:32 UTC, alattalatta commented on docs/ko/translation-guide.md
> +| Iterate | 순회 | | |
순회로 해도 괜찮을까요? 반복("반복 가능한 객체")과 순회("순회 가능한 객체")의 검색 결과 차이가 정말 상당해서요.

2021-05-16 16:32 UTC, alattalatta commented on docs/ko/translation-guide.md
> +| Padding | 안쪽 여백 | 레이아웃 성질일 때에 한정 | [CSS 기본 박스 모델 입문](https://developer.mozilla.org/ko/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model) |
"레이아웃 성질일 때에 한정"은 제가 괜히 사족을 붙인 것 같아요 😅 어차피 CSS `padding`을 `안쪽여백`으로 할 것도 아니고...

2021-05-16 16:32 UTC, alattalatta commented on docs/ko/translation-guide.md
> +| Tutorial | 자습서 | |
```suggestion
| Tutorial | 자습서 | |
| Usage notes | 사용 일람 | Heading |
```

자주 보이는 헤딩에 요것도 있었어요.

2021-05-16 16:32 UTC, alattalatta commented on docs/ko/translation-guide.md
> +- "무슨무슨 값" (numeric value, integer value, ...) 같은 경우, 항상 띄어서 표기합니다.
"기본 값"도 띄어쓰는게 맞을까요? 그러면 이것도 예시에 포함해주시면 더 확실해질 듯 하여요. 아니면 예외를 둘 것인지

2021-05-16 16:32 UTC, alattalatta commented on docs/ko/translation-guide.md
> +| Flow | 플로 | | |
```suggestion
| Flow | 플로 | 레이아웃 방식일 경우에 한정 | |
```

플로 하나로 통일하는게 어떨까요? 굳이 "레이아웃 방식 한정"을 덧붙인 이유는

> Flow layout is ... according to the document's flow.

와 같은 문장이 있으면 "**플로** 레이아웃은 ... 문서 **흐름**에 따라 ..."와 같은 느낌으로 번역했었거든요.

2021-05-17 11:59 UTC, hochan222 commented on docs/ko/translation-guide.md
> +| Iterate | 순회 | | |
> Iterate: 순회
> Loop/Repeat과 구별하기 위해서 "순회"로 번역했었습니다. ("배열을 반복합니다." 대신 "배열을 순회합니다.")
> Iterator는 반복기/반복자가 아닌 순회기/순회자가 됩니다.
> 그런데 일반적으로 "반복" 용례가 훨씬 많아서 잘 모르겠네요.

Iterator 자체는 반복기/반복자가 좋다고 생각합니다. 역사적으로 볼때 Iterator를 반복기/반복자로 인식하는 사람이 더 많다고 생각합니다. 
문제가 Iterate의 경우인데, Iterator를 반복기/반복자라고하고 Iterate는 순회라는 표현을 쓰면 아무래도 혼동이 많을까요?

2021-05-17 12:03 UTC, hochan222 commented on docs/ko/translation-guide.md
> +| Padding | 안쪽 여백 | 레이아웃 성질일 때에 한정 | [CSS 기본 박스 모델 입문](https://developer.mozilla.org/ko/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model) |
> "레이아웃 성질일 때에 한정"은 제가 괜히 사족을 붙인 것 같아요

저는 좋아보입니다! :) 이 부분은 삭제할까요?

```suggestion
| Padding | 안쪽 여백(패딩) | 레이아웃 성질일 때에 한정 | [CSS 기본 박스 모델 입문](https://developer.mozilla.org/ko/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model) |
```

이전에 작성해주신 이 케이스가 너무 좋아 보여서 suggestion에 남겼습니다.

2021-05-17 12:03 UTC, hochan222 commented on docs/ko/translation-guide.md
> +| Tutorial | 자습서 | |
오..! 맞아요! 감사합니다 :)

2021-05-17 12:06 UTC, hochan222 reviewed
> "기본 값"도 띄어쓰는게 맞을까요? 그러면 이것도 예시에 포함해주시면 더 확실해질 듯 하여요. 아니면 예외를 둘 것인지

예시에 추가했습니다!

2021-05-17 12:06 UTC, hochan222 commented on docs/ko/translation-guide.md
> +    - 틀린 예: 정숫값, 소숫값
```suggestion
    - 예: 정수 값, 소수 값, 반환 값, 기본 값
    - 틀린 예: 정숫값, 소숫값, 반환값, 기본값
```

예시에 추가했습니다!

2021-05-17 12:10 UTC, hochan222 commented on docs/ko/translation-guide.md
> +| Flow | 플로 | | |
> 플로 하나로 통일하는게 어떨까요?
좋아 보입니다!

> 플로(Flow)
는 어떤가요? suggestion에 반영했습니다!

2021-05-17 13:06 UTC, alattalatta commented on docs/ko/translation-guide.md
> +| Iterate | 순회 | | |
의견을 좀 더 모아보면 좋겠네여.

2021-05-17 13:11 UTC, alattalatta commented on docs/ko/translation-guide.md
> +| Padding | 안쪽 여백 | 레이아웃 성질일 때에 한정 | [CSS 기본 박스 모델 입문](https://developer.mozilla.org/ko/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model) |
네 지워주세요! 😊 

가까운 문단 내에 padding이 계속 나오면 처음에는 안쪽 여백(패딩), 그 후에는 안쪽 여백 단독으로 사용하는 식으로 번역할 수 있겠네요. 그러면 바깥 여백(마진)도 동일하게 하는 것으로..

2021-05-17 13:18 UTC, alattalatta commented on docs/ko/translation-guide.md
> +| Flow | 플로 | | |
플로"우"가 너무 압도적이기 때문인가요? (Flow)를 붙인다면 레이아웃 방식인 그리드와 플렉스박스도 그리드(Grid) 레이아웃과 플렉스박스(Flexbox) 레이아웃이 되어야 하는 것인지- 하는 질문을 저는 아예 회피하려고 되도록 _단어(Word)_ 형태를 쓰지 않았거든요 😓

2021-05-17 14:55 UTC, hochan222 commented on docs/ko/translation-guide.md
> +| Iterate | 순회 | | |
@cos18 @GwangYeol-Im @nKiNk @pje1740 @yechoi42 @yujo11  어떻게 생각하시나요?

2021-05-17 14:56 UTC, hochan222 commented on docs/ko/translation-guide.md
> +| Padding | 안쪽 여백 | 레이아웃 성질일 때에 한정 | [CSS 기본 박스 모델 입문](https://developer.mozilla.org/ko/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model) |
좋아요 :)

2021-05-17 14:59 UTC, yechoi42 commented on docs/ko/translation-guide.md
> +| Iterate | 순회 | | |
Iterator는 말씀해주신대로 반복자가 가장 익숙하네요. Iterate는 '순회'로 표기해도 이해하는데 문제없을 것 같습니다. 오히려 반복이 어색한 느낌...

2021-05-17 15:02 UTC, hochan222 commented on docs/ko/translation-guide.md
> +| Flow | 플로 | | |
> 저는 아예 회피하려고 되도록 단어(Word) 형태를 쓰지 않았거든요 😓

저도 단어(Word) 형태는 특별한 경우 아니면 쓰지 않는것이 좋겠다는 의견에 동의합니다! 단지, 제가 의견을 제시한 이유는 그리드하면 Grid가 바로 연상되고 플렉스박스하면 Flexbox가 바로 연상되는데 플로하면 Flow가 바로 연상이 안될수도 있을것 같아서 이야기드렸습니다. 

@cos18 @GwangYeol-Im @nKiNk @pje1740 @yechoi42 @yujo11 어떻게 생각하시나요?

2021-05-18 04:32 UTC, nKiNk approved these changes

2021-05-18 06:22 UTC, pje1740 reviewed
고생하셨습니다! 👍

2021-05-18 06:22 UTC, pje1740 commented on docs/ko/translation-guide.md
> +기사 제목에는 거의 항상 ID가 주어지는데, 기사 내에서 네이게이션을 자동으로 생성하고 실시간 샘플을 생성하기위한 코드 블록을 식별하는 등의 이유가 있습니다. 제목을 번역 할 때 ID도 같이 번역 할 필요가 없습니다. 나머지 슬러그는 번역되지 않으므로 모든 것이 일관되게 유지됩니다.
네비게이션 오타난 거 같아요!

2021-05-18 07:27 UTC, hochan222 commented on docs/ko/translation-guide.md
> +기사 제목에는 거의 항상 ID가 주어지는데, 기사 내에서 네이게이션을 자동으로 생성하고 실시간 샘플을 생성하기위한 코드 블록을 식별하는 등의 이유가 있습니다. 제목을 번역 할 때 ID도 같이 번역 할 필요가 없습니다. 나머지 슬러그는 번역되지 않으므로 모든 것이 일관되게 유지됩니다.
```suggestion
기사 제목에는 거의 항상 ID가 주어지는데, 기사 내에서 네비게이션을 자동으로 생성하고 실시간 샘플을 생성하기위한 코드 블록을 식별하는 등의 이유가 있습니다. 제목을 번역 할 때 ID도 같이 번역 할 필요가 없습니다. 나머지 슬러그는 번역되지 않으므로 모든 것이 일관되게 유지됩니다.
```

2021-05-18 07:28 UTC, hochan222 commented on docs/ko/translation-guide.md
> +기사 제목에는 거의 항상 ID가 주어지는데, 기사 내에서 네이게이션을 자동으로 생성하고 실시간 샘플을 생성하기위한 코드 블록을 식별하는 등의 이유가 있습니다. 제목을 번역 할 때 ID도 같이 번역 할 필요가 없습니다. 나머지 슬러그는 번역되지 않으므로 모든 것이 일관되게 유지됩니다.
알려주셔서 감사합니다!

2021-05-18 09:03 UTC, yujo11 commented on docs/ko/translation-guide.md
> +| Flow | 플로 | | |
저도 하나로 통일하는 의견에 대찬성입니다!

'플로'로 통일하면 좋을거 같습니다!

2021-05-18 09:03 UTC, yujo11 commented
고생하셨습니다!!👍👍👍

2021-05-18 09:04 UTC, yujo11 approved these changes

2021-05-18 13:50 UTC, hochan222 commented on docs/ko/translation-guide.md
> +| See also | 같이 보기 | Heading |
```suggestion
| See also | 참고 자료 | Heading |
```

2021-05-18 13:50 UTC, hochan222 commented on docs/ko/translation-guide.md
> +| See also | 같이 보기 | Heading |
많은 부분에서 `참고 자료`로 돼있어서 리뷰했습니다.

2021-05-18 14:34 UTC, alattalatta commented on docs/ko/translation-guide.md
> +| See also | 같이 보기 | Heading |
전체 페이지에 대해 검색했을 땐 "같이 보기"가 더 많이 나와요.
- `>같이 보기<`: 702개 파일 내 702번 등장
-  `>See also<`: 377개 파일 내 382번 등장
   - 번역이 덜 끝난 것들
- `>더 알아보기<`: 93개 파일 내 94번 등장
   - 보통 일반 문서에서는 잘 안쓰이고 Glossary의 "Learn more"에 보입니다.
- `>함께 보기<`: 67개 파일 내 67번 등장
- `>참고\s?자료<`: 6개 파일 내 6번 등장

비중은 이렇구요, [`<strong>`: 높은 중요도 요소#같이_보기](https://developer.mozilla.org/ko/docs/Web/HTML/Element/strong#%EA%B0%99%EC%9D%B4_%EB%B3%B4%EA%B8%B0) 같은 경우 `<b>`, `<em>`, `font-weight`만 있고 외부 링크같은 것이 없어서 "참고 자료"는 덜 어울리지 않을까? 하여요.

2021-05-18 15:24 UTC, hochan222 commented on docs/ko/translation-guide.md
> +| See also | 같이 보기 | Heading |
앗 제가 띄어쓰기를 안해서 `같이보기`로 검색해서 적게 나왔습니다. 다음에는 의견을 제시할때 저도 정량적 지표와 함께 제시하도록할게요! 이해했습니다. 알려주셔서 감사합니다! 

> 비중은 이렇구요, <strong>: 높은 중요도 요소#같이_보기 같은 경우 <b>, <em>, font-weight만 있고 외부 링크같은 것이 없어서 "참고 자료"는 덜 어울리지 않을까? 하여요.

저도 동의합니다! 그대로 유지하는게 좋아보입니다. 별도로 향후에 `같이 보기(See also)` 와 같이 Heading에 영어가 같이 명시돼있는경우에 대해서는 한글만 허용하는게 좋을까요?

2021-05-18 15:39 UTC, alattalatta commented on docs/ko/translation-guide.md
> +| See also | 같이 보기 | Heading |
네! 헤딩이 뭐시기(Blah) 형식인 것은 1. 모두 오래된 레거시 페이지들이고, 2. 가독성을 너무 해쳐서, 영어 제거하는 쪽에 대찬성합니다

2021-05-18 17:05 UTC, hochan222 commented on docs/ko/translation-guide.md
> +| See also | 같이 보기 | Heading |
네! 좋아요! 답변해주셔서 감사합니다. 좋은 밤 보내세요 :)

2021-05-19 08:24 UTC, hochan222 commented on docs/ko/translation-guide.md
> +| Iterate | 순회 | | |
저도 순회로 하는게 좋은것같습니다. 우선은 순회로 올리겠습니다!

2021-05-19 08:25 UTC, hochan222 commented on docs/ko/translation-guide.md
> +| Flow | 플로 | | |
우선 플로로 올리겠습니다!

2021-05-19 08:27 UTC, hochan222 commented
This is a Korean guideline. We are ready to merge.

2021-05-19 08:34 UTC, alattalatta approved these changes

2021-05-20 01:50 UTC, yechoi42 approved these changes
수고하셨습니다 :)

2021-05-26 15:33 UTC, alattalatta commented
@hochan222 이거 병합하셔도 될 것 같은뎁, 어차피 로케일 문서니까 콘텐츠 팀 리뷰 따로 안받아도 되지 않을까요?

2021-05-26 23:25 UTC, hochan222 commented
동의합니다! 제가 리뷰어 지정을 다시한 이유는 저희는 files 폴더에 대하여만 권한이있어서 처음에 기본 리뷰어로 지정돼서 추가했었는데 다른 locale 팀보니까 저희도 머지해도될것같네요! 

리마인드 해주셔서 감사합니다 :)

아래 링크는 codeowners 링크입니다!

https://www.github.com/mdn/translated-content/tree/main/.github%2FCODEOWNERS

2021-05-26 23:25 UTC, merged