AutoCorrect fix files/zh-cn/web/javascript
mdn/translated-content pull request #8781
Opened 2022-09-24 13:48 UTC by huacnlee

2022-09-28 12:56 UTC, yin1999 requested changes

2022-09-28 12:56 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/errors/missing_parenthesis_after_argument_list/index.md
> +因为没有使用”+“操作符来连接字符串，JavaScript 认为 `log` 函数的参数的值只是“`PI: ”，在这种情况下，它应该用一个右括号作为结束。`
```suggestion
因为没有使用“+”操作符来连接字符串，JavaScript 认为 `log` 函数的参数的值只是“`PI: `”，在这种情况下，它应该用一个右括号作为结束。
```

2022-09-28 12:56 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/arraybuffer/bytelength/index.md
> +`byteLength 访问器属性`表示一个{{jsxref("ArrayBuffer")}} 对象的字节长度。
```suggestion
`byteLength` 访问器属性表示一个 {{jsxref("ArrayBuffer")}} 对象的字节长度。
```

2022-09-28 12:56 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/bigint/tolocalestring/index.md
> +// → 一二三，四五六，七八九，一二三，四五六，七八九
还是之前的问题，不建议对示例代码部分作更正

2022-09-28 13:36 UTC, huacnlee commented
这个文件后面禁用掉好了

2022-09-29 03:08 UTC, huacnlee commented
已更新

2022-09-29 03:12 UTC, huacnlee commented on files/zh-cn/web/javascript/reference/global_objects/bigint/tolocalestring/index.md
> +// → 一二三，四五六，七八九，一二三，四五六，七八九
https://github.com/mdn/translated-content/pull/4191/commits/aed5d1357a535bf556fe039eb97899984d74224d

2022-10-01 03:11 UTC, yin1999 requested changes

2022-10-01 03:11 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/lexical_grammar/index.md
> +`更多信息可以参考 null`
```suggestion
更多信息可以参考 `null`
```

2022-10-01 03:11 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/typedarray/foreach/index.md
> +**`forEach()`**方法对类型化数组的每个元素调用提供的函数。这个方法的算法和 {{jsxref("Array.prototype.forEach()")}}_相同。_ _TypedArray_ 是这里的 [类型化数组类型](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#TypedArray_objects
```suggestion
**`forEach()`**方法对类型化数组的每个元素调用提供的函数。这个方法的算法和 {{jsxref("Array.prototype.forEach()")}} _相同_。_TypedArray_ 是这里的[类型化数组类型](/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#TypedArray_objects)之一。
```

2022-10-01 03:11 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/typedarray/reduce/index.md
> +      - : 在上一次迭代中，调用 callback 的返回值，或者是提供的 `initialValue。`.
```suggestion
      - : 在上一次迭代中，调用 callback 的返回值，或者是提供的 `initialValue`。
```

2022-10-01 03:11 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/regexp/compile/index.md
> +`已废弃的 compile`**`()`** 方法被用于在脚本执行过程中（重新）编译正则表达式。与`RegExp`构造函数基本一样。
```suggestion
已废弃的 **`compile()`** 方法被用于在脚本执行过程中（重新）编译正则表达式。与 `RegExp` 构造函数基本一样。
```

2022-10-01 03:11 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/object/values/index.md
> +`如果要 Object.values`兼容不支持它的旧环境，可在 [tc39/proposal-object-values-entries](https://github.com/tc39/proposal-object-values-entries) 或 [es-shims/Object.values](https://github.com/es-shims/Object.values) 中找
```suggestion
如果要 `Object.values`兼容不支持它的旧环境，可在 [tc39/proposal-object-values-entries](https://github.com/tc39/proposal-object-values-entries) 或 [es-shims/Object.values](https://github.com/es-shims/Object.values) 中找到 Polyfill。
```

2022-10-01 03:11 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +// → 一二三，四五六。七八九
```suggestion
// → 一二三,四五六.七八九
```

2022-10-01 03:11 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/intl/numberformat/index.md
> +// → 9.9 亿
```suggestion
// → 9.9亿
```

2022-10-01 03:11 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/number/tolocalestring/index.md
> +// → 一二三，四五六。七八九
```suggestion
// → 一二三,四五六.七八九
```

2022-10-01 03:20 UTC, yin1999 approved these changes

2022-10-01 03:20 UTC, merged