用語集 XIncludeを日本語に翻訳。
mdn/translated-content pull request #8866
Opened 2022-09-27 11:32 UTC by Retsu-MURAKAMI

用語集 XInclude を日本語に翻訳しました。確認をお願いします。

2022-09-28 13:52 UTC, mfuji09 requested changes
3か所の修正をお願いします。

2022-09-28 13:52 UTC, mfuji09 commented on files/ja/glossary/xinclude/index.md
> +tags:
tags: 以下は翻訳版では削除し、代わりに l10n: sourceCommit: を入れてください。
入れ方については、 <https://mozilla-japan.github.io/mdn-translation-guide/new-translation-procedure-2.html> を参照してください。

2022-09-28 13:52 UTC, mfuji09 commented on files/ja/glossary/xinclude/index.md
> +主要なブラウザは、XInclude の仕組みを標準ではサポートしていません。
「ブラウザ」は「ブラウザー」と表記してください。
参考: https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline

2022-09-28 13:52 UTC, mfuji09 commented on files/ja/glossary/xinclude/index.md
> +- [`XPath`](/en-US/docs/Web/XPath)
リンク先は日本語版記事の URL に修正してください。
```suggestion
- [`XPath`](/ja/docs/Web/XPath)
```

2022-09-28 14:54 UTC, Retsu-MURAKAMI commented on files/ja/glossary/xinclude/index.md
> +tags:
削除して、l10nを追加しました。確認をお願いします。

2022-09-28 14:54 UTC, Retsu-MURAKAMI commented on files/ja/glossary/xinclude/index.md
> +主要なブラウザは、XInclude の仕組みを標準ではサポートしていません。
こちらも修正しました。確認をお願いします。

2022-09-28 14:55 UTC, Retsu-MURAKAMI commented on files/ja/glossary/xinclude/index.md
> +- [`XPath`](/en-US/docs/Web/XPath)
修正しました。確認お願いします。

2022-09-30 15:23 UTC, mfuji09 commented on files/ja/glossary/xinclude/index.md
> +tags:
確認しました。ありがとうございます。

2022-09-30 15:23 UTC, mfuji09 commented on files/ja/glossary/xinclude/index.md
> +主要なブラウザは、XInclude の仕組みを標準ではサポートしていません。
確認しました。

2022-09-30 15:23 UTC, mfuji09 approved these changes
OKです。

2022-09-30 15:24 UTC, merged