chore: update links to indexeddb-examples
mdn/translated-content pull request #8868
Opened 2022-09-27 15:12 UTC by schalkneethling

As part of the repository triage we have been doing, we have been updating links to the repositories and live examples in /content. This can be easy for you all to miss, so I will open some pull requests to update these links as appropriate. This is the first of those.

fix #8857

2022-09-27 15:40 UTC, Graywolf9 approved these changes
LGTM for `es` thank you!

2022-09-27 23:43 UTC, yin1999 approved these changes
LGTM, but the links to github.io could be `https`, for: zh-cn, ja, fr, ru, etc.

2022-09-27 23:43 UTC, yin1999 commented on files/zh-cn/web/api/idbcursor/direction/index.md
> +使用游标遍历数据时，可以不需要我们指定在特定字段选择数据；我们可以直接获取所有数据，同时在每次循环迭代过程当中，我们可以通过 cursor.value.foo 获取数据，如下是一个完整的游标遍历数据的例子； [IDBCursor example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbcursor)
```suggestion
使用游标遍历数据时，可以不需要我们指定在特定字段选择数据；我们可以直接获取所有数据，同时在每次循环迭代过程当中，我们可以通过 cursor.value.foo 获取数据，如下是一个完整的游标遍历数据的例子； [IDBCursor example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbcursor) ([view example live](https://mdn.github.io/dom-examples/indexeddb-examples/idbcursor/)).
```

2022-09-27 23:43 UTC, yin1999 commented on files/zh-cn/web/api/idbcursor/index.md
> +在这个简单的代码片段中，我们创建了一个事务和检索一个对象存储，之后使用一个游标遍历存储对象中所有的记录。游标不是必须使用主键来选则数据库，我们可以把它全部拿出来。同时需要注意在每次循环遍历中，你可以在当前记录下的游标对象中使用 `cursor.value.foo` 抓取数据。对于完整的工作示例，请查看我们的 [IDBCursor example](https://github.com/mdn/d
```suggestion
在这个简单的代码片段中，我们创建了一个事务和检索一个对象存储，之后使用一个游标遍历存储对象中所有的记录。游标不是必须使用主键来选则数据库，我们可以把它全部拿出来。同时需要注意在每次循环遍历中，你可以在当前记录下的游标对象中使用 `cursor.value.foo` 抓取数据。对于完整的工作示例，请查看我们的 [IDBCursor example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbcursor) ([在线查看示例](https://mdn.github.io/dom-examples/indexeddb-examples/idbcursor/))。
```

2022-09-27 23:43 UTC, yin1999 commented on files/zh-cn/web/api/idbcursor/key/index.md
> +我们可以不根据游标的 key 来选取数据；我们可以抓取所有。还要注意，在循环的每个迭代中，您可以使用 cursor.value.foo 从当前记录下获取数据。完整示例，请看[IDBCursor example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbcursor) ([view example li
```suggestion
我们可以不根据游标的 key 来选取数据；我们可以抓取所有。还要注意，在循环的每个迭代中，您可以使用 cursor.value.foo 从当前记录下获取数据。完整示例，请看[IDBCursor example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbcursor) ([view example live](https://mdn.github.io/dom-examples/indexeddb-examples/idbcursor/).)
```

2022-09-27 23:43 UTC, yin1999 commented on files/zh-cn/web/api/idbkeyrange/index.md
> +> **备注：** For a more complete example allowing you to experiment with key range, have a look at our [IDBKeyRange-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbkeyrange)
```suggestion
> **备注：** For a more complete example allowing you to experiment with key range, have a look at our [IDBKeyRange-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbkeyrange) repo ([view the example live too](https://mdn.github.io/dom-examples/indexeddb-examples/idbkeyrange/)).
```

2022-09-27 23:43 UTC, yin1999 commented on files/zh-cn/web/api/idbkeyrange/lowerbound/index.md
> +> **备注：** 要获得一个更完整的示例，使您能够使用键范围进行实验，请查看我们的 [IDBKeyRange-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbkeyrange)（[实时查看该示例](http://mdn.github.io/dom-examples/indexeddb-ex
```suggestion
> **备注：** 要获得一个更完整的示例，使您能够使用键范围进行实验，请查看我们的 [IDBKeyRange-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbkeyrange)（[实时查看该示例](https://mdn.github.io/dom-examples/indexeddb-examples/idbkeyrange/)）。
```

2022-09-28 02:10 UTC, Graywolf9 commented on files/es/web/api/idbcursor/continue/index.html
> +<p>En este simple fragmento nosotros creamos una transacción, recuperar un objeto del almacen, despues usamos un cursor para interactuar a traves de todos los registros en almacen de objetos. El curs
```suggestion
<p>En este simple fragmento nosotros creamos una transacción, recuperar un objeto del almacen, despues usamos un cursor para interactuar a traves de todos los registros en almacen de objetos. El cursor no requiere que nosotros seleccionemos los datos basados en una tecla; podemos tomarlo todo. También es importante resaltar que en cada interacción de la cadena, puedes tomar datos desde el registro actual debajo del objeto del cursor usando<code> </code><code style="font-style: normal; line-height: 1.5;">cursor.value.foo</code><span style="line-height: 1.5;">. Para dar un ejemplo completo, puedes mirar nuestra <a href="http://mdn.github.io/dom-examples/indexeddb-examples/idbcursor/">IDBCursor example</a></span><span style="line-height: 1.5;"> (</span><a href="https://mdn.github.io/dom-examples/indexeddb-examples/idbcursor/" style="line-height: 1.5;">view example live</a><span style="line-height: 1.5;">.)</span></p>
```

2022-09-28 02:11 UTC, Graywolf9 commented on files/es/web/api/idbcursor/index.html
> +<p>En este simple fragmento creamos una transacción, recuperamos un almacén de objetos y usamos un cursor para iterar todos los registros del almacén de objetos. El cursor no nos obliga a seleccionar
```suggestion
<p>En este simple fragmento creamos una transacción, recuperamos un almacén de objetos y usamos un cursor para iterar todos los registros del almacén de objetos. El cursor no nos obliga a seleccionar los datos en base a una <code>key</code>; podemos simplemente cogerlos todos. También tenga en cuenta que en cada iteración del bucle, puede tomar datos del registro actual bajo el objeto del cursor utilizando <code style="font-style: normal; line-height: 1.5;">cursor.value.foo</code>. Para un ejemplo completo de funcionamiento, vea nuestro <span style="line-height: 1.5;"><a href="https://mdn.github.io/dom-examples/indexeddb-examples/idbcursor/">IDBCursor example</a></span><span style="line-height: 1.5;"> (</span><a href="https://mdn.github.io/dom-examples/indexeddb-examples/idbcursor/" style="line-height: 1.5;">view example live</a><span style="line-height: 1.5;">.)</span></p>
```

2022-09-28 03:45 UTC, cw118 reviewed
Some "suggestions" for `https` links (and a few minor fixes), thank you :)

2022-09-28 03:45 UTC, cw118 commented on files/fr/web/api/idbcursor/advance/index.md
> +On notera également que, dans chaque itération de la boucle, on peut récupérer les données de l'enregistrement en cours grâce à l'objet curseur via `curseur.value.foo`. Pour un exemple fonctionnel co
```suggestion
On notera également que, dans chaque itération de la boucle, on peut récupérer les données de l'enregistrement en cours grâce à l'objet curseur via `curseur.value.foo`. Pour un exemple fonctionnel complet, voir [notre exemple IDBCursor](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbcursor) ([l'exemple en _live_](https://mdn.github.io/dom-examples/indexeddb-examples/idbcursor/)).
```

2022-09-28 03:45 UTC, cw118 commented on files/fr/web/api/idbcursor/continue/index.md
> +Dans ce petit morceau de code, on fait une transaction, on récupère un magasin d'objet, puis on utilise un curseur afin d'itérer sur les enregistrements contenus dans le magasin. Il n'est pas nécessa
```suggestion
Dans ce petit morceau de code, on fait une transaction, on récupère un magasin d'objet, puis on utilise un curseur afin d'itérer sur les enregistrements contenus dans le magasin. Il n'est pas nécessaire de sélectionner les données selon une clé, on peut simplement toutes les récupérer. On notera qu'à chaque itération de la boucle, on récupère les données correspondantes à l'enregistrement grâce au curseur sous la forme `curseur.value.toto`. Pour étudier un exemple de travail complet, voir [notre exemple IDBCursor](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbcursor) ([voir l'exemple live](https://mdn.github.io/dom-examples/indexeddb-examples/idbcursor/)).
```

2022-09-28 03:45 UTC, cw118 commented on files/fr/web/api/idbcursor/index.md
> +Dans ce fragment simple, nous créons une transaction, récupérons un magasin d'objets, puis utilisons un curseur pour parcourir tous les enregistrements du magasin d'objets. Le curseur ne nous oblige
```suggestion
Dans ce fragment simple, nous créons une transaction, récupérons un magasin d'objets, puis utilisons un curseur pour parcourir tous les enregistrements du magasin d'objets. Le curseur ne nous oblige pas à sélectionner les données basées sur une clé, nous pouvons simplement travailler sur tout les enregistrements. Notez également que dans chaque itération de la boucle, vous pouvez récupérer les données de l'enregistrement en cours sous l'objet curseur à l'aide `curseur.value.toto`. Pour un exemple de travail complet, voir notre [exemple IDBCursor](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbcursor) ([l'exemple en _live_](https://mdn.github.io/dom-examples/indexeddb-examples/idbcursor/)).
```

2022-09-28 03:45 UTC, cw118 commented on files/fr/web/api/idbindex/count/index.md
> +Efin, on parcourt chaque enregistrement pour l'insérer dans un tableau HTML. Pour consulter un exemple fonctionnel complet, vous pouvez vous référer à notre dépôt [IDBIndex-example](https://github.co
```suggestion
Enfin, on parcourt chaque enregistrement pour l'insérer dans un tableau HTML. Pour consulter un exemple fonctionnel complet, vous pouvez vous référer à notre dépôt [IDBIndex-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbindex) ([cf. la démonstration _live_](https://mdn.github.io/dom-examples/indexeddb-examples/idbindex/)).
```

2022-09-28 03:45 UTC, cw118 commented on files/fr/web/api/idbindex/getkey/index.md
> +Enfin, on parcourt les enregistrements pour remplir un tableau HTML. Le dépôt [`indexeddb-examples`](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples) contient un exemple complet ([vo
```suggestion
Enfin, on parcourt les enregistrements pour remplir un tableau HTML. Le dépôt [`indexeddb-examples`](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples) contient un exemple complet ([voir l'exemple en direct](https://mdn.github.io/dom-examples/indexeddb-examples/idbindex/)).
```

2022-09-28 03:45 UTC, cw118 commented on files/fr/web/api/idbindex/multientry/index.md
> +Enfin, on parcourt chacun des enregistrements pour insérer les données dans un tableau HTML. Pour consulter un exemple complet, vous pouvez vous référer à [notre dépôt IDBIndex-example](https://githu
```suggestion
Enfin, on parcourt chacun des enregistrements pour insérer les données dans un tableau HTML. Pour consulter un exemple complet, vous pouvez vous référer à [notre dépôt IDBIndex-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbindex) ([voir également la démo _live_](https://mdn.github.io/dom-examples/indexeddb-examples/idbindex/)).
```

2022-09-28 03:45 UTC, cw118 commented on files/fr/web/api/idbindex/unique/index.md
> +Enfin, on parcourt chaque enregistrement et on insère les données dans le tableau HTML (pour voir un exemple complet, consulter [notre dépôt IDBIndex-example](https://github.com/mdn/dom-examples/tree
```suggestion
Enfin, on parcourt chaque enregistrement et on insère les données dans le tableau HTML (pour voir un exemple complet, consulter [notre dépôt IDBIndex-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbindex) ([voir la démonstration _live_](https://mdn.github.io/dom-examples/indexeddb-examples/idbindex/)).
```

2022-09-28 03:45 UTC, cw118 commented on files/fr/web/api/idbkeyrange/bound/index.md
> +> **Note :** Pour un exemple complet qui utilise les intervalles de clé, vous pouvez consulter [le dépôt GitHub IDBKeyRange-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/i
```suggestion
> **Note :** Pour un exemple complet qui utilise les intervalles de clé, vous pouvez consulter [le dépôt GitHub IDBKeyRange-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbkeyrange) ([ainsi que la démonstration associée](https://mdn.github.io/dom-examples/indexeddb-examples/idbkeyrange/)).
```

2022-09-28 03:45 UTC, cw118 commented on files/fr/web/api/idbkeyrange/index.md
> +> **Note :** Pour un exemple complet qui utilise les intervalles de clé, vous pouvez consulter [le dépôt GitHub IDBKeyRange-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/i
```suggestion
> **Note :** Pour un exemple complet qui utilise les intervalles de clé, vous pouvez consulter [le dépôt GitHub IDBKeyRange-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbkeyrange) ([ainsi que la démonstration associée](https://mdn.github.io/dom-examples/indexeddb-examples/idbkeyrange/)).
```

2022-09-28 03:45 UTC, cw118 commented on files/fr/web/api/idbkeyrange/lower/index.md
> +> **Note :** Pour un exemple complet qui utilise les intervalles de clé, vous pouvez consulter [le dépôt GitHub IDBKeyRange-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/i
```suggestion
> **Note :** Pour un exemple complet qui utilise les intervalles de clé, vous pouvez consulter [le dépôt GitHub IDBKeyRange-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbkeyrange) ([ainsi que la démonstration associée](https://mdn.github.io/dom-examples/indexeddb-examples/idbkeyrange/)).
```

2022-09-28 03:45 UTC, cw118 commented on files/fr/web/api/idbkeyrange/lowerbound/index.md
> +> **Note :** Pour un exemple complet qui utilise les intervalles de clé, vous pouvez consulter [le dépôt GitHub IDBKeyRange-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/i
```suggestion
> **Note :** Pour un exemple complet qui utilise les intervalles de clé, vous pouvez consulter [le dépôt GitHub IDBKeyRange-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbkeyrange) ([ainsi que la démonstration associée](https://mdn.github.io/dom-examples/indexeddb-examples/idbkeyrange/)).
```

2022-09-28 03:45 UTC, cw118 commented on files/fr/web/api/idbkeyrange/loweropen/index.md
> +> **Note :** Pour un exemple complet qui utilise les intervalles de clé, vous pouvez consulter [le dépôt GitHub IDBKeyRange-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/i
```suggestion
> **Note :** Pour un exemple complet qui utilise les intervalles de clé, vous pouvez consulter [le dépôt GitHub IDBKeyRange-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbkeyrange) ([ainsi que la démonstration associée](https://mdn.github.io/dom-examples/indexeddb-examples/idbkeyrange/)).
```

2022-09-28 03:45 UTC, cw118 commented on files/fr/web/api/idbkeyrange/only/index.md
> +> **Note :** Pour un exemple complet qui utilise les intervalles de clé, vous pouvez consulter [le dépôt GitHub IDBKeyRange-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/i
```suggestion
> **Note :** Pour un exemple complet qui utilise les intervalles de clé, vous pouvez consulter [le dépôt GitHub IDBKeyRange-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbkeyrange) ([ainsi que la démonstration associée](https://mdn.github.io/dom-examples/indexeddb-examples/idbkeyrange/)).
```

2022-09-28 03:45 UTC, cw118 commented on files/fr/web/api/idbkeyrange/upper/index.md
> +> **Note :** Pour un exemple complet qui utilise les intervalles de clé, vous pouvez consulter [le dépôt GitHub IDBKeyRange-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/i
```suggestion
> **Note :** Pour un exemple complet qui utilise les intervalles de clé, vous pouvez consulter [le dépôt GitHub IDBKeyRange-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbkeyrange) ([ainsi que la démonstration associée](https://mdn.github.io/dom-examples/indexeddb-examples/idbkeyrange/)).
```

2022-09-28 03:45 UTC, cw118 commented on files/fr/web/api/idbkeyrange/upperbound/index.md
> +> **Note :** Pour un exemple complet qui utilise les intervalles de clé, vous pouvez consulter [le dépôt GitHub IDBKeyRange-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/i
```suggestion
> **Note :** Pour un exemple complet qui utilise les intervalles de clé, vous pouvez consulter [le dépôt GitHub IDBKeyRange-example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbkeyrange) ([ainsi que la démonstration associée](https://mdn.github.io/dom-examples/indexeddb-examples/idbkeyrange/)).
```

2022-09-28 03:45 UTC, cw118 commented on files/fr/web/api/idbobjectstore/index/index.md
> +> **Note :** pour un exemple fonctionnel complet, voir notre [exemple sur GitHub](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbindex) ([la démonstration associée](http://mdn.gi
```suggestion
> **Note :** pour un exemple fonctionnel complet, voir notre [exemple sur GitHub](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbindex) ([la démonstration associée](https://mdn.github.io/dom-examples/indexeddb-examples/idbindex/)).
```

2022-09-29 20:13 UTC, cw118 approved these changes
LGTM for french, thank you @schalkneethling !

2022-10-01 17:19 UTC, josielrocha approved these changes
LGTM for **pt-br**. Thank you @schalkneethling!

2022-10-01 18:36 UTC, schalkneethling commented
Hey @lex111 and @kenji-yamasaki, when you have a moment, your review will be appreciated. Thanks!

2022-10-02 07:41 UTC, sashasushko approved these changes
Approve from @mdn/yari-content-ru

2022-10-02 22:53 UTC, yin1999 commented
Waiting for review from @mdn/yari-content-ja

2022-10-03 14:29 UTC, JuanVqz approved these changes

2022-10-04 14:06 UTC, mfuji09 requested changes
`http:` should be `https:` in `ja` files.

2022-10-04 14:06 UTC, mfuji09 commented on files/ja/web/api/idbcursor/index.md
> +In this simple fragment we create a transaction, retrieve an object store, then use a cursor to iterate through all the records in the object store. The cursor does not require us to select the data
```suggestion
In this simple fragment we create a transaction, retrieve an object store, then use a cursor to iterate through all the records in the object store. The cursor does not require us to select the data based on a key; we can just grab all of it. Also note that in each iteration of the loop, you can grab data from the current record under the cursor object using `cursor.value.foo`. For a complete working example, see our [IDBCursor example](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbcursor) ([view example live](https://mdn.github.io/dom-examples/indexeddb-examples/idbcursor/)).
```

2022-10-04 14:06 UTC, mfuji09 commented on files/ja/web/api/idbcursor/continue/index.md
> +この単純で部分的な実例ではトランザクションを作り、オブジェクトストアを取得した後、オブジェクトストア内の全ての反復処理するためカーソルを使用しています。カーソルはキーに基づいてデータを選択するには必要ありません。その全てを捕らえることができます。また、それぞれのループ内での繰り返しでカーソルオブジェクトを用い、 `cursor.value.foo` とすることで、現在のレコードからカーソルの下の
```suggestion
この単純で部分的な実例ではトランザクションを作り、オブジェクトストアを取得した後、オブジェクトストア内の全ての反復処理するためカーソルを使用しています。カーソルはキーに基づいてデータを選択するには必要ありません。その全てを捕らえることができます。また、それぞれのループ内での繰り返しでカーソルオブジェクトを用い、 `cursor.value.foo` とすることで、現在のレコードからカーソルの下のデータを取得できることには注目です。完全な例については [IDBCursor の例](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbcursor) ([ライブデモを見る](https://mdn.github.io/dom-examples/indexeddb-examples/idbcursor/)) を参照してください。
```

2022-10-04 14:06 UTC, mfuji09 commented on files/ja/web/api/idbcursor/advance/index.md
> +注意点としてループの繰り返しで、カーソルオブジェクトの現在のレコードのテータを `cursor.value.foo`を使って取得できます。完全な動作例は、[IDBCursor の例](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbcursor)([ライブ例を見る](http://mdn.github.io/
```suggestion
注意点としてループの繰り返しで、カーソルオブジェクトの現在のレコードのテータを `cursor.value.foo`を使って取得できます。完全な動作例は、[IDBCursor の例](https://github.com/mdn/dom-examples/tree/main/indexeddb-examples/idbcursor)([ライブ例を見る](https://mdn.github.io/dom-examples/indexeddb-examples/idbcursor/))を見てください。
```

2022-10-04 22:45 UTC, merged