ブラウザー拡張機能のruntimeページの翻訳
mdn/translated-content pull request #8895
Opened 2022-09-29 08:55 UTC by eetann

### Description

ブラウザー拡張機能のruntimeページの未翻訳であった部分を翻訳しました。

### Additional details

ページ下部の注意書き（`> **Note:** この API は Chromium の〜`の部分）は、 [storageのページ](https://github.com/mdn/translated-content/blob/71f7685af7191dc64284b642beac31fc5d52a3e6/files/ja/mozilla/add-ons/webextensions/api/storage/index.md) と合わせた表記にしました。

2022-10-04 03:33 UTC, mfuji09 requested changes
レビューを行いましたので、修正をお願いします。

2022-10-04 03:33 UTC, mfuji09 commented on files/ja/mozilla/add-ons/webextensions/api/runtime/index.md
> +> **Note:** この API は Chromium の [`chrome.runtime`](https://developer.chrome.com/extensions/runtime) API に基づいています。また、このドキュメントは [`runtime.json`](https://chromium.googlesource.com/chromium/src/+/master/
後出しで申し訳ありませんが、 `**Note:**` が `**メモ:**` に変更になりましたので、変更をお願いします。

```suggestion
> **メモ:** この API は Chromium の [`chrome.runtime`](https://developer.chrome.com/extensions/runtime) API に基づいています。また、このドキュメントは [`runtime.json`](https://chromium.googlesource.com/chromium/src/+/master/extensions/common/api/runtime.json) における Chromium のコードに基づいています。Microsoft Edge での実装状況は Microsoft Corporation から提供されたものであり、ここでは Creative Commons Attribution 3.0 United States License に従っています。
```

2022-10-04 03:33 UTC, mfuji09 commented on files/ja/mozilla/add-ons/webextensions/api/runtime/index.md
> +  - : 2つのコンテキスト間の接続の一方を表します。メッセージを交換するために使います。
日本語と英数字の間は、半角空白を空けるようにしてください。

2022-10-04 03:33 UTC, mfuji09 commented on files/ja/mozilla/add-ons/webextensions/api/runtime/index.md
> +  - : ブラウザのOSの識別です。
「ブラウザ」は「ブラウザー」と表記してください。

2022-10-04 03:33 UTC, mfuji09 commented on files/ja/mozilla/add-ons/webextensions/api/runtime/index.md
> +  - : ユーザーのコンピュータに入っているネイティブアプリケーションと拡張機能を接続します。
「コンピュータ」は「コンピューター」と表記してください。

2022-10-04 03:33 UTC, mfuji09 commented on files/ja/mozilla/add-ons/webextensions/api/runtime/index.md
> +  - : コンテンツスクリプト から同じ拡張機能の別の処理、または別の拡張機能への接続します。
「コンテンツスクリプト」の後に不自然な空白があるので、削除をお願いします（他の場所も同様）。

2022-10-04 09:06 UTC, eetann commented
@mfuji09 
ありがとうございます！
レビューいただいた箇所について、修正いたしました。
再レビューをお願いいたします。

2022-10-05 15:13 UTC, mfuji09 approved these changes
良いと思います。

2022-10-05 15:14 UTC, merged