Fix for Issue #8401
mdn/translated-content pull request #8912
Opened 2022-09-30 05:35 UTC by aegisnull

### Description
This pull request includes the fix for the problem of broken image urls as reported on Issue #8401

### Motivation
This should improve the overall experience of the page by not having broken links on the main content

### Additional details

### Related issues and pull requests
Fixes #8401
https://github.com/mdn/translated-content/issues/8401

2022-09-30 16:30 UTC, Graywolf9 commented
Hi! @aegisnull thank you so much for your time and contribution. Since the localizated content take the images from en-US content is not necessary to put the images again, it should work only with the changes on the `index.md` file. Could you try it and modify?

2022-09-30 16:59 UTC, aegisnull commented
@Graywolf9 you have a valid point, as requested I have instead removed the duplicate files I added and replaced the dead links with a link to the images in the original en-US content.

2022-09-30 18:20 UTC, Graywolf9 requested changes

2022-09-30 18:20 UTC, Graywolf9 commented on files/es/web/http/overview/index.md
> +![A Web document is the composition of different resources](https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview/fetching_a_page.png)
The render automatically found the image if it exists in content repo

```suggestion
![A Web document is the composition of different resources](fetching_a_page.png)
```

2022-09-30 18:22 UTC, Graywolf9 commented
Thank you so much for your attention @aegisnull 

I let you an example, what I mean in my initial comment is that the page automatically take the image from the en-US folder

2022-10-03 15:17 UTC, Graywolf9 commented on files/es/web/http/overview/index.md
> +![HTTP as an application layer protocol, on top of TCP (transport layer) and IP (network layer) and below the presentation layer.](https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview/http-laye
```suggestion
![HTTP as an application layer protocol, on top of TCP (transport layer) and IP (network layer) and below the presentation layer.](http-layers.png)Diseñado a principios de la década de 1990, {{glossary("HTTP")}} es un protocolo ampliable, que ha ido evolucionando con el tiempo. Es lo que se conoce como un protocolo de la capa de aplicación, y se transmite sobre el protocolo {{glossary("TCP")}}, o el protocolo encriptado {{glossary("TLS")}}, aunque teóricamente podría usarse cualquier otro protocolo fiable. Gracias a que es un protocolo capaz de ampliarse, se usa no solo para transmitir documentos de hipertexto ({{glossary("HTML")}}), si no que además, se usa para transmitir imágenes o vídeos, o enviar datos o contenido a los servidores, como en el caso de los formularios de datos. {{glossary("HTTP")}} puede incluso ser utilizado para transmitir partes de documentos, y actualizar páginas Web en el acto.
```

2022-10-03 15:17 UTC, Graywolf9 commented on files/es/web/http/overview/index.md
> +![Client server chain](https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview/client-server-chain.png)
```suggestion
![Client server chain](client-server-chain.png)
```

2022-10-03 15:20 UTC, Graywolf9 commented on files/es/web/http/overview/index.md
> +![A basic HTTP request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview/http_request.png)
```suggestion
![A basic HTTP request](http_request.png)
```

2022-10-03 15:20 UTC, Graywolf9 commented on files/es/web/http/overview/index.md
> +![](https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview/http_response.png)
```suggestion
![](http_response.png)
```

2022-10-03 15:29 UTC, Graywolf9 approved these changes

2022-10-03 15:30 UTC, Graywolf9 commented
Thank you so much for your time and contribution @aegisnull 

I apply the changes to the urls to keep the short way to use, this to improve de load time and follow the guidelines.

2022-10-03 15:31 UTC, merged