用語集TURNの翻訳（issue #644）
mdn/translated-content pull request #8976
Opened 2022-10-03 13:38 UTC by Retsu-MURAKAMI

### Description

用語集のTURNを日本語に翻訳しました。
確認お願いします。

### Related issues and pull requests

https://github.com/mozilla-japan/translation/issues/644

2022-10-04 09:37 UTC, yoshinorin reviewed
@Retsu-MURAKAMI 
PRのタイトルに `（issue #644）` を含めていると、マージした後に、このリポジトリの `#644` のIssueと紐づけられてしまうので、タイトルから削除しておいたほうが良いと思います。

2022-10-05 15:00 UTC, mfuji09 requested changes
1件の修正を検討してください。

2022-10-05 15:00 UTC, mfuji09 commented on files/ja/glossary/turn/index.md
> +**TURN** (Traversal Using Relays around NAT) は、{{glossary("NAT", "Network Address Translator")}} (NAT) やファイアウォールの内側からコンピューターがデータを受信および送信できるようにする {{Glossary('protocol')}} です。TURN は WebRTC で使用され、インターネッ
用語集へのリンクも翻訳した方が良いと思います。
```suggestion
**TURN** (Traversal Using Relays around NAT) は、{{glossary("NAT", "Network Address Translator")}} (NAT) やファイアウォールの内側からコンピューターがデータを受信および送信できるようにする {{Glossary('protocol', 'プロトコル')}} です。TURN は WebRTC で使用され、インターネット上の任意の 2 つのデバイスがピアツーピア接続できるようにします。
```

2022-10-06 01:04 UTC, Retsu-MURAKAMI commented on files/ja/glossary/turn/index.md
> +**TURN** (Traversal Using Relays around NAT) は、{{glossary("NAT", "Network Address Translator")}} (NAT) やファイアウォールの内側からコンピューターがデータを受信および送信できるようにする {{Glossary('protocol')}} です。TURN は WebRTC で使用され、インターネッ
反映させました。

プロトコルは訳そうと思っていたのですが、マクロの書き方がわからなかったので、どこかにマクロの書き方一覧とかないでしょうか？

2022-10-06 13:03 UTC, mfuji09 approved these changes
OKです。

2022-10-06 13:03 UTC, merged

2022-10-06 13:14 UTC, Retsu-MURAKAMI commented on files/ja/glossary/turn/index.md
> +**TURN** (Traversal Using Relays around NAT) は、{{glossary("NAT", "Network Address Translator")}} (NAT) やファイアウォールの内側からコンピューターがデータを受信および送信できるようにする {{Glossary('protocol')}} です。TURN は WebRTC で使用され、インターネッ
ありがとうございます！！