translate crypto.subtle.generateKey method for zh-cn
mdn/translated-content pull request #9049
Opened 2022-10-05 23:28 UTC by Venjy

### Description
Translate api SubtleCrypto.generateKey for zh-cn

### Motivation
Add zh-cn translate for this page

### Additional details

[https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/generateKey](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/generateKey)
### Related issues and pull requests

2022-10-06 00:30 UTC, yin1999 requested changes
指出了一些问题，请参照 [translation-guide](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md) 进行更新

2022-10-06 00:30 UTC, yin1999 commented on files/zh-cn/web/api/subtlecrypto/generatekey/index.md
> + **`SubtleCrypto.generateKey()`** 方法可用于生成新的密钥或密钥对
请与英文文档保持一致

2022-10-06 00:30 UTC, yin1999 commented on files/zh-cn/web/api/subtlecrypto/generatekey/index.md
> +    - 对于 [RSASSA-PKCS1-v1_5](/en-US/docs/Web/API/SubtleCrypto/sign#rsassa-pkcs1-v1_5)、[RSA-PSS](/en-US/docs/Web/API/SubtleCrypto/sign#rsa-pss)、[RSA-OAEP](/en-US/docs/Web/API/SubtleCrypto/encrypt#rsa-
请将链接更新为指向 `zh-CN` 的（即使实际并不存在）：

```suggestion
    - 对于 [RSASSA-PKCS1-v1_5](/zh-CN/docs/Web/API/SubtleCrypto/sign#rsassa-pkcs1-v1_5)、[RSA-PSS](/zh-CN/docs/Web/API/SubtleCrypto/sign#rsa-pss)、[RSA-OAEP](/zh-CN/docs/Web/API/SubtleCrypto/encrypt#rsa-oaep) 算法：
```

2022-10-06 00:30 UTC, yin1999 commented on files/zh-cn/web/api/subtlecrypto/generatekey/index.md
> +      [AES-GCM](/en-US/docs/Web/API/SubtleCrypto/encrypt#aes-gcm)、 [AES-KW](/en-US/docs/Web/API/SubtleCrypto/wrapKey#aes-kw) 算法: 这是一个 {{domxref("AesKeyGenParams")}} 对象。
这里注意标点和空格

2022-10-06 00:30 UTC, yin1999 commented on files/zh-cn/web/api/subtlecrypto/generatekey/index.md
> +    - `unwrapKey`: 密钥将被用于{{domxref("SubtleCrypto.unwrapKey()", "解包另一个密钥")}}
标点：

```suggestion
    - `encrypt`：密钥将被用于{{domxref("SubtleCrypto.encrypt()","加密")}}
    - `decrypt`：密钥将被用于{{domxref("SubtleCrypto.encrypt()","解密")}}
    - `sign`：密钥将被用于{{domxref("SubtleCrypto.sign()", "签名")}}
    - `verify`：密钥将被用于{{domxref("SubtleCrypto.verify()", "验签")}}
    - `deriveKey`：密钥将被用于{{domxref("SubtleCrypto.deriveKey()", "派生密钥")}}
    - `deriveBits`：密钥将被用于{{domxref("SubtleCrypto.deriveBits()", "派生比特位")}}
    - `wrapKey`：密钥将被用于{{domxref("SubtleCrypto.wrapKey()", "包装另一个密钥")}}
    - `unwrapKey`：密钥将被用于{{domxref("SubtleCrypto.unwrapKey()", "解包另一个密钥")}}
```

2022-10-06 00:30 UTC, yin1999 commented on files/zh-cn/web/api/subtlecrypto/generatekey/index.md
> +- 对于非对称算法，promise将返回一个{{domxref("CryptoKeyPair")}}
请参照英文文档更新

2022-10-06 00:30 UTC, yin1999 commented on files/zh-cn/web/api/subtlecrypto/generatekey/index.md
> +### 生成RSA密钥对
```suggestion
### 生成 RSA 密钥对
```

2022-10-06 00:30 UTC, yin1999 commented on files/zh-cn/web/api/subtlecrypto/generatekey/index.md
> +## 另请参见
```suggestion
## 参见
```

2022-10-06 11:09 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/subtlecrypto/generatekey/index.md
> +## 规格
```suggestion
## 规范
```

2022-10-06 11:21 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/subtlecrypto/generatekey/index.md
> +使用 {{domxref("SubtleCrypto")}} 接口的 **`generateKey()`** 方法可用于生成用于对称算法的密钥或用于非对称算法的密钥对
```suggestion
使用 {{domxref("SubtleCrypto")}} 接口的 **`generateKey()`** 方法用于生成新的密钥（用于对称算法）或密钥对（用于非对称算法）。
```

2022-10-06 11:24 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/subtlecrypto/generatekey/index.md
> +当遇到以下异常时，返回的promise会进入rejected状态
```suggestion
当遇到以下异常时，promise 会被拒绝：
```

2022-10-06 11:33 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/subtlecrypto/generatekey/index.md
> +以下为生成 RSA 密钥对的代码。完整的示例[在这里](https://github.com/mdn/dom-examples/blob/main/web-crypto/encrypt-decrypt/rsa-oaep.js)
```suggestion
以下代码生成 RSA-OAEP 加密密钥对。[在 GitHub 上查看完整代码示例](https://github.com/mdn/dom-examples/blob/main/web-crypto/encrypt-decrypt/rsa-oaep.js)。
```

2022-10-06 11:38 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/subtlecrypto/generatekey/index.md
> +以下为生成 ECDSA 密钥对的代码，完整的示例[在这里](https://github.com/mdn/dom-examples/blob/main/web-crypto/sign-verify/ecdsa.js)
```suggestion
以下代码生成 ECDSA 签名密钥对。[在 GitHub 上查看完整代码示例](https://github.com/mdn/dom-examples/blob/main/web-crypto/sign-verify/ecdsa.js)。
```

2022-10-06 11:39 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/subtlecrypto/generatekey/index.md
> +- [Cryptographic key length recommendations](https://www.keylength.com/).
```suggestion
- [加密密钥长度的建议](https://www.keylength.com/).
```

2022-10-06 11:40 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/subtlecrypto/generatekey/index.md
> +以下为生成 HMAC 密钥的代码，完整的示例[在这里](https://github.com/mdn/dom-examples/blob/main/web-crypto/sign-verify/hmac.js)
```suggestion
以下代码生成 HMAC 签名密钥对。[在 GitHub 上查看完整代码示例](https://github.com/mdn/dom-examples/blob/main/web-crypto/sign-verify/hmac.js)。
```

2022-10-06 11:42 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/subtlecrypto/generatekey/index.md
> +以下为生成 AES 密钥的代码，完整的示例[在这里](https://github.com/mdn/dom-examples/blob/main/web-crypto/encrypt-decrypt/aes-gcm.js)
```suggestion
以下代码生成 AES-GCM 加密密钥。[在 GitHub 上查看完整代码示例](https://github.com/mdn/dom-examples/blob/main/web-crypto/encrypt-decrypt/aes-gcm.js)。
```

2022-10-06 11:52 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/subtlecrypto/generatekey/index.md
> +  - : 当结果是{{domxref("CryptoKey")}}，但keyUsages为空时触发
```suggestion
  - : 当结果是类型为 `secret` 或 `private` 但 `keyUsages` 为空的{{domxref("CryptoKey", "加密密钥")}}时触发。
```

2022-10-06 11:54 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/subtlecrypto/generatekey/index.md
> +  - : 当结果是{{domxref("CryptoKeyPair")}}，但私钥的keyUsages为空时触发
```suggestion
  - : 当结果是{{domxref("CryptoKeyPair", "加密密钥对")}}，但它的 `privateKey.usages` 属性为空时触发。
```

2022-10-06 20:06 UTC, Venjy commented
update

2022-10-07 00:18 UTC, yin1999 commented on files/zh-cn/web/api/subtlecrypto/generatekey/index.md
> +    - `deriveKey`：密钥将被用于{{domxref("SubtleCrypto.deriveKey()", "派生密钥")}}
```suggestion
    - `deriveKey`：密钥将被用于{{domxref("SubtleCrypto.deriveKey()", "派生新的密钥")}}
```

2022-10-07 00:18 UTC, yin1999 commented on files/zh-cn/web/api/subtlecrypto/generatekey/index.md
> +一个 {{jsxref("Promise")}}，兑现为 {{domxref("CryptoKey")}}（用于对称加密算法）或  {{domxref("CryptoKeyPair")}}（用于非对称加密算法）
```suggestion
一个 {{jsxref("Promise")}}，兑现为 {{domxref("CryptoKey")}}（用于对称加密算法）或  {{domxref("CryptoKeyPair")}}（用于非对称加密算法）。
```

2022-10-07 00:18 UTC, yin1999 commented on files/zh-cn/web/api/subtlecrypto/generatekey/index.md
> +  - : 当结果是类型为 `secret` 或 `private` 但 `keyUsages` 为空的{{domxref("CryptoKey", "加密密钥")}}时触发。
```suggestion
  - : 当结果是类型为 `secret` 或 `private` 的{{domxref("CryptoKey", "加密密钥")}}，但 `keyUsages` 参数为空时触发。
```

2022-10-07 00:18 UTC, yin1999 commented on files/zh-cn/web/api/subtlecrypto/generatekey/index.md
> +### 生成 ECDSA 密钥对
```suggestion
### 生成椭圆曲线密钥对
```

2022-10-07 00:18 UTC, yin1999 commented on files/zh-cn/web/api/subtlecrypto/generatekey/index.md
> +- [加密密钥长度的建议](https://www.keylength.com/).
```suggestion
- [加密密钥长度的建议](https://www.keylength.com/)。
```

2022-10-07 00:26 UTC, yin1999 approved these changes
Thank you @Venjy! Welcome aboard.

Also thanks for @Jack-Zhang-1314's suggestions :)

2022-10-07 00:26 UTC, merged