Update mdn/contribute/index.html.
mdn/translated-content pull request #906
Opened 2021-05-18 03:32 UTC by pocketdr

Update mdn/contribute/index.html with English version.
Please not close it if approved.
The rest of content will be updated soon.

2021-05-18 07:01 UTC, t7yang requested changes

2021-05-18 07:15 UTC, pocketdr commented on files/zh-cn/mdn/contribute/index.html
> +<p><strong>MDN Web Docs 需要你的帮助！</strong>如果你不是这里的常客，简单介绍一下，这里绝对称得上是 Web 技术的宝库！里面的所有内容，都是由热情的参与者们贡献的，他们来自世界各地，有着不同的身份。不过人无完人，在这个宝库中也有着大量——因为参与者真的超级多——等待改善的问题，比如文章的排版行文，又或者是文章内的示例和网站本身的错误等等。如果你有兴趣成为我们的一
这一段

2021-05-18 07:27 UTC, pocketdr commented on files/zh-cn/mdn/contribute/index.html
> +<p><strong>MDN Web Docs 需要你的帮助！</strong>如果你不是这里的常客，简单介绍一下，这里绝对称得上是 Web 技术的宝库！里面的所有内容，都是由热情的参与者们贡献的，他们来自世界各地，有着不同的身份。不过人无完人，在这个宝库中也有着大量——因为参与者真的超级多——等待改善的问题，比如文章的排版行文，又或者是文章内的示例和网站本身的错误等等。如果你有兴趣成为我们的一
自由发挥的内容确实多了点，我大概删减了一下
```suggestion
<p>欢迎！当你来到了这里，说明你已经迈出了成为 MDN 贡献者的第一步！</p>MDN Web Docs 里面的所有内容，都是由热情的参与者们贡献的，他们来自世界各地，有着不同的身份。不过人无完人，里面也有着大量——因为参与者真的很多——等待改善的问题，比如文章的排版行文，又或者是文章内的示例和网站本身的错误等等。如果你有兴趣成为我们的一员的话，下面列出了你可以通过哪些方式帮到我们。</p>
```

2021-05-18 07:27 UTC, pocketdr commented on files/zh-cn/mdn/contribute/index.html
> +<h2 id="Other_useful_pages">相关链接</h2>
是这样，目前 Contributing to MDN 的简中页面错误非常严重，所以想先将这个表格翻译好，后续内容正在翻译。

2021-05-18 07:27 UTC, pocketdr commented on files/zh-cn/mdn/contribute/index.html
> +   <td>我们的 <a href="/zh-CN/docs/Learn">Web 开发教程</a>非常热门，<a href="https://discourse.mozilla.org/c/mdn/learn/250">论坛上</a>也有许多初来乍到的爱好者，</td>
遗留了一点内容
```suggestion
   <td>我们的 <a href="/zh-CN/docs/Learn">Web 开发教程</a>非常热门，<a href="https://discourse.mozilla.org/c/mdn/learn/250">论坛上</a>也有许多初来乍到的爱好者，他们有很多疑问等待有经验的人帮助他们解决。</td>
```

2021-05-18 07:38 UTC, t7yang commented
請用一個新的 commit 完整修正你要異動的部分，然後標題請回復原本的翻譯或請充分說明為何現在翻譯比原本的更好。

2021-05-18 09:10 UTC, t7yang approved these changes

2021-05-18 16:13 UTC, irvin commented on files/zh-cn/mdn/contribute/index.html
> +<p>欢迎！当你来到了这里，说明你已经迈出了成为 MDN 贡献者的第一步！</p>MDN Web Docs 里面的所有内容，都是由热情的参与者们贡献的，他们来自世界各地，有着不同的身份。不过人无完人，里面也有着大量——因为参与者真的很多——等待改善的问题，比如文章的排版行文，又或者是文章内的示例和网站本身的错误等等。如果你有兴趣成为我们的一员的话，下面列出了你可以通过哪些方式帮到我们。</p>
這邊少了一個p開頭

2021-05-18 16:14 UTC, irvin requested changes
請補一下上面那個漏掉的 <p>

2021-05-20 01:24 UTC, t7yang approved these changes

2021-05-20 03:50 UTC, merged