ko/glossary/bootsrap/index.html docs create and description translation
mdn/translated-content pull request #909
Opened 2021-05-18 05:06 UTC by hwang1588

『new description translation』

- ko/glossary/bootstrap/index.html
--------------------------------------------------
『update description translation』

- null

2021-05-18 05:06 UTC, hwang1588 reviewed
첫 pr입니다. 파일은 체크했습니다. 감사합니다.

2021-05-20 04:14 UTC, hwang1588 commented
『new description translation』

- ko/glossary/bootstrap/index.html
- ko/glossary/breadcrumb/index.html
- -------------------------------------------------
『update description translation』

null

2021-05-20 16:38 UTC, cos18 requested changes
늦게 리뷰드려서 죄송합니다. 리뷰 확인 부탁드립니다!

2021-05-20 16:38 UTC, cos18 commented on files/ko/glossary/bootstrap/index.html
> +<p>Bootstrap은 반응형 웹사이트를 빠르게 만들기 위한 무료 오픈소스 {{Glossary("HTML")}}, CSS 및 {{ Glossary ( " JavaScript " ) }} 의 프레임워크 입니다.</p>
```suggestion
<p>Bootstrap은 반응형 웹사이트를 빠르게 만들기 위한 무료 오픈소스 {{Glossary("HTML")}}, CSS 및 {{Glossary( "JavaScript")}} 의 프레임워크 입니다.</p>
```
매크로가 작동하지 않는 오류가 있습니다.

2021-05-20 16:38 UTC, cos18 commented on files/ko/glossary/bootstrap/index.html
> +<p>Bootstrap은 당초 Twitter Blueprint라고 불렸으며, <a href="https://twitter.com/"> Twitter</a> 개발자에 의해 개발되었습니다. 반응형 디자인을 지원하며 그대로 사용하거나 필요에 따라 자신의 코드에 맞추어 사용할 수 있는 사전 정의된 디자인 템플릿이 있습니다. 부트스트랩은 모든 최신 브라우저와 {{
```suggestion
<p>Bootstrap은 당초 Twitter Blueprint라고 불렸으며, <a href="https://twitter.com/"> Twitter</a> 개발자에 의해 개발되었습니다. 반응형 디자인을 지원하며 그대로 사용하거나 필요에 따라 자신의 코드에 맞추어 사용할 수 있는 사전 정의된 디자인 템플릿이 있습니다. 부트스트랩은 모든 모던 브라우저와 {{glossary("Microsoft Internet Explorer", "Internet Explorer")}} 의 최근 버전과 호환되기 때문에 타 브라우저와의 호환성에 대해 걱정하지 않으셔도 됩니다.</p>
```

Modern Browsers를 최신 브라우저라고 해석하기엔 오역이 될 가능성이 보입니다. 이를 표음대로 적는게 좋지 않을까 싶습니다.

2021-05-20 16:42 UTC, cos18 commented
> 『new description translation』
> 
> * ko/glossary/bootstrap/index.html
> * ko/glossary/breadcrumb/index.html
> 
> 『update description translation』
> 
> null

추가로, 위에 언급하신 breadcrumb는 PR에 반영이 되지 않은건가요?

2021-05-20 23:24 UTC, hwang1588 commented
@cos18 안녕하세요! 리뷰 주신 부분 확인했습니다. 혹시 아직 merge가 안되었다면 다음 업데이트때 기존 문서도 수정해서 한번에 pr드려도 될까요?

2021-05-21 00:35 UTC, hwang1588 commented
> > 『new description translation』
> > 
> > * ko/glossary/bootstrap/index.html
> > * ko/glossary/breadcrumb/index.html
> > 
> > 『update description translation』
> > null
> 
> 추가로, 위에 언급하신 breadcrumb는 PR에 반영이 되지 않은건가요?

안녕하세요. 첫 pr이 머지 되지 않은 상태에서 두번째 pr에 breadcrumb을 추가했습니다~!

2021-05-24 06:18 UTC, closed without merging