fix: broken link
mdn/translated-content pull request #9127
Opened 2022-10-09 02:44 UTC by elo1lson

* fix issue  related in issue #9113

### Description
Broken link
### Related issues and pull requests

Fix #9113

2022-10-09 08:18 UTC, SphinxKnight requested changes
The file is moved here (arquivos/fr/rede) for unknown reasons. Its path should stay the same.

2022-10-09 08:20 UTC, SphinxKnight commented
Thanks for stepping in @elo1lson, however the link could be improved and most importantly, the file shouldn't be moved.

2022-10-09 10:07 UTC, elo1lson commented
@SphinxKnight sorry, but I believe the `/fr/Reference_CSS` route doesn't exist in any language, I believe the correct one would be `/fr/Css/Reference`

2022-10-09 10:23 UTC, SphinxKnight commented
> @SphinxKnight sorry, but I believe the `/fr/Reference_CSS` route doesn't exist in any language, I believe the correct one would be `/fr/Css/Reference`, oh, and sorry, my translator translated the names of the folders by mistake, I noticed that now, I'll fix it

please have a look at my suggestion for the right route

2022-10-09 13:30 UTC, SphinxKnight requested changes
see previous suggestion in the review for the right link to use

2022-10-09 13:30 UTC, SphinxKnight commented on arquivos/fr/rede/css/herança/index.md
> +Pour [chaque propriété CSS](fr/Css/Reference), la spécification indique si, par défaut, cette propriété est héritée ou non. Cela permet de définir le comportement qu'on observera lorsqu'aucune valeur
this has not been taken into account

2022-10-10 06:21 UTC, SphinxKnight requested changes
the file moved again to another location.
@elo1lson I'm going to switch this one to a draft.

2022-10-11 02:17 UTC, closed without merging