zh-cn(update): sync with english for overflow
mdn/translated-content pull request #9140
Opened 2022-10-09 13:05 UTC by Jack-Zhang-1314

### Description

`Mozilla extensions` 内容已经过时, 是否需要翻译？

### Motivation

### Additional details

### Related issues and pull requests

2022-10-09 13:15 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/css/overflow/index.md
> +  - : 内容不能被裁减并且可能渲染到元素框的外部。
```suggestion
  - : 内容不能被裁减并且可能渲染到边距盒（padding）的外部。
```

2022-10-09 22:59 UTC, yin1999 requested changes

2022-10-09 22:59 UTC, yin1999 commented on files/zh-cn/web/css/overflow/index.md
> +**`overflow`** 是 [CSS](/zh-CN/docs/Web/CSS) 的[简写属性](/zh-CN/docs/Web/CSS/Shorthand_properties)，其设置了元素溢出时所需的行为——即当元素的内容太大而无法适应它的[块级格式上下文](/zh-CN/docs/Web/Guide/CSS/Block_formatting_context)时。
```suggestion
**`overflow`** 是 [CSS](/zh-CN/docs/Web/CSS) 的[简写属性](/zh-CN/docs/Web/CSS/Shorthand_properties)，其设置了元素溢出时所需的行为——即当元素的内容太大而无法适应它的[块级格式化上下文](/zh-CN/docs/Web/Guide/CSS/Block_formatting_context)时。
```

2022-10-09 22:59 UTC, yin1999 commented on files/zh-cn/web/css/overflow/index.md
> +  - : 如果需要，内容将被裁减以适应边距（padding）盒。无论是否实际裁剪了任何内容，浏览器总是显示滚动条，以防止滚动条在内容改变时出现或者消失。打印机仍然可以打印溢出的内容。
```suggestion
  - : 如果需要，内容将被裁减以适应边距（padding）盒。无论是否实际裁剪了任何内容，浏览器总是显示滚动条，以防止滚动条在内容改变时出现或者消失。打印机可能会打印溢出的内容。
```

2022-10-09 22:59 UTC, yin1999 commented on files/zh-cn/web/css/overflow/index.md
> +  - : Use `overflow: clip` instead.
```suggestion
  - : 请使用 `overflow: hidden` 代替。
- `-moz-scrollbars-horizontal` {{deprecated_inline}}
  - : 请使用 `{{Cssxref("overflow-x")}}: scroll` 和 `{{Cssxref("overflow-y")}}: hidden`，或使用 `overflow: scroll hidden` 代替。
- `-moz-scrollbars-vertical` {{deprecated_inline}}
  - : 请使用 `{{Cssxref("overflow-x")}}: hidden` 和 `{{Cssxref("overflow-y")}}: scroll`，或使用 `overflow: hidden scroll` 代替。
- `-moz-hidden-unscrollable` {{deprecated_inline}}
  - : 请使用 `overflow: clip` 代替。
```

2022-10-09 22:59 UTC, yin1999 commented on files/zh-cn/web/css/overflow/index.md
> +As of Firefox 63, `-moz-scrollbars-none`, `-moz-scrollbars-horizontal`, and `-moz-scrollbars-vertical` are behind a feature preference setting. In about:config, set `layout.css.overflow.moz-scrollbar
```suggestion
在 Firefox 63 中：`-moz-scrollbars-none`、`-moz-scrollbars-horizontal` 和 `-moz-scrollbars-vertical` 位于特性首选项中。即需要在 about:config 中，将 `layout.css.overflow.moz-scrollbars.enabled` 设置为 `true`。
```

2022-10-09 22:59 UTC, yin1999 commented on files/zh-cn/web/css/overflow/index.md
> +overflow 选项包括裁减、显示滚动条、或者显示从容器流向周围区域的内容。
```suggestion
overflow 选项包括裁减、显示滚动条，或者显示从容器流向周围区域的内容。
```

2022-10-09 22:59 UTC, yin1999 commented on files/zh-cn/web/css/overflow/index.md
> +为了 `overflow` 具有效果，块级水平的容器必须有一个设定的高度（`height` 或 `max-height`）或 `white-space` 设置为 `nowrap`。
```suggestion
为使 `overflow` 具有效果，块级水平的容器必须有一个设定的高度（`height` 或 `max-height`）或 `white-space` 设置为 `nowrap`。
```

2022-10-09 22:59 UTC, yin1999 commented on files/zh-cn/web/css/overflow/index.md
> +## 形式化定义
```suggestion
## 形式定义
```

2022-10-09 22:59 UTC, yin1999 commented on files/zh-cn/web/css/overflow/index.md
> +## 形式化语法
```suggestion
## 形式语法
```

2022-10-09 22:59 UTC, yin1999 commented on files/zh-cn/web/css/overflow/index.md
> +{{EmbedLiveSample("Setting_different_overflow_values_for_text", "600", "250")}}
注意，其是对小标题（自动转换为 id）的引用，请在翻译至中文时注意这些标题引用：

```suggestion
{{EmbedLiveSample("为文本设置不同的 overflow 值", "600", "250")}}
```

2022-10-09 22:59 UTC, yin1999 commented
> `Mozilla extensions` 内容已经过时, 是否需要翻译？

请翻译

2022-10-10 03:17 UTC, Jack-Zhang-1314 commented
> > `Mozilla extensions` 内容已经过时, 是否需要翻译？
> 
> 请翻译

下次我会注意

2022-10-10 04:16 UTC, yin1999 approved these changes

2022-10-10 04:17 UTC, merged