Update index.md
mdn/translated-content pull request #9143
Opened 2022-10-09 16:49 UTC by LIXiangChen

### Description

Based on the latest version of _en_ document translation, some content is not fully translated.

### Motivation

The _en_ document has classified pseudo-classes, which is very nice, and the _zh-cn_ version did not have it before.

### Additional details

### Related issues and pull requests

2022-10-09 17:11 UTC, jasonren0403 reviewed
please use zh-CN in links as much as possible

请尽可能链接至相应的简体中文文档，根据之前的经验来看平台会自动fallback的

2022-10-10 01:35 UTC, jasonren0403 commented on files/zh-cn/web/css/pseudo-classes/index.md
> +These pseudo-classes apply when viewing something which has timing, such as a [WebVTT](/zh-CN/docs/Web/API/WebVTT_API) caption track.
```suggestion
这些伪类适用于查看有计时功能的东西，如 [WebVTT](/zh-CN/docs/Web/API/WebVTT_API) 字幕轨。
```

2022-10-10 01:38 UTC, jasonren0403 commented on files/zh-cn/web/css/pseudo-classes/index.md
> +  - https://drafts.csswg.org/css-ui/
```suggestion
```

本地化文档只留下`title`和`slug`就行
https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md#%E5%85%83%E6%95%B0%E6%8D%AE

2022-10-10 03:55 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/css/pseudo-classes/index.md
> +> **注意：**相较于伪类，[伪元素](/zh-CN/docs/Web/CSS/Pseudo-elements) 可用于设置元素 _特定部分_ 的样式。
```suggestion
> **备注：** 相较于伪类，[伪元素](/zh-CN/docs/Web/CSS/Pseudo-elements)可用于设置元素*特定部分*的样式。
```

2022-10-10 04:06 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/css/pseudo-classes/index.md
> +伪类让你可以将样式应用于元素——不仅仅是与文档树内容有关的，也可以是与外部因素有关的——像是与导航历史有关的（{{CSSxRef(":visited")}}，举例而言）、与其内容的状态有关的（像是某些表单元素上的 {{CSSxRef(":checked")}}）、或者与鼠标位置有关的（像是 {{CSSxRef(":hover")}}，它可以让你知道鼠标是否在一个元素上）。
```suggestion
伪类让你可以将样式应用于元素，不仅与文档树内容有关，也与外部因素有关——像是与导航历史有关的（例如，{{CSSxRef(":visited")}}）、与其内容的状态有关的（像是某些表单元素上的 {{CSSxRef(":checked")}}）或者与鼠标位置有关的（像是 {{CSSxRef(":hover")}}，它可以让你知道鼠标是否在一个元素上）。
```

2022-10-10 04:08 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/css/pseudo-classes/index.md
> +  - : Matches an element that is currently in fullscreen mode.
```suggestion
  - : 匹配当前处于全屏模式的元素。
```

2022-10-10 04:10 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/css/pseudo-classes/index.md
> +## 时间维度式伪类
```suggestion
## 时间方面的伪类
```

2022-10-10 04:12 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/css/pseudo-classes/index.md
> +## 用户动作伪类
```suggestion
## 用户行为伪类
```

2022-10-10 04:21 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/css/pseudo-classes/index.md
> +这些伪类接受 [宽容的选择器列表](/zh-CN/docs/Web/CSS/Selector_list) 作为参数。
```suggestion
这些伪类接受[任意数量的选择器列表](/zh-CN/docs/Web/CSS/Selector_list)作为参数。
```

* forgiving 翻译成 **任意数量** 不确定是否准确

2022-10-10 04:23 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/css/pseudo-classes/index.md
> +## 相关链接
```suggestion
## 参见
```

https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md#常用标题

2022-10-10 05:03 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/css/text-underline-offset/index.md
> +## 正式定义
```suggestion
## 形式定义
```

2022-10-10 05:03 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/css/text-underline-offset/index.md
> +## 正式语法
```suggestion
## 形式语法
```

2022-10-10 05:04 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/css/text-underline-offset/index.md
> +## 相关链接
```suggestion
## 参见
```

2022-10-10 05:08 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/css/text-underline-offset/index.md
> +**`text-underline-offset`** [CSS](/zh-CN/docs/Web/CSS) 属性设置下划线文本装饰线（使用 {{cssxref("text-decoration")}} 应用）与其原始位置的偏移距离。
```suggestion
[CSS](/zh-CN/docs/Web/CSS) 的 **`text-underline-offset`** 属性设置下划线文本装饰线（使用 {{cssxref("text-decoration")}} 应用）与其原始位置的偏移距离。
```

2022-10-10 08:08 UTC, LIXiangChen commented on files/zh-cn/web/css/pseudo-classes/index.md
> +这些伪类接受 [宽容的选择器列表](/zh-CN/docs/Web/CSS/Selector_list) 作为参数。
"forgiving selector list" 是一个专有概念, 我觉得译成 "任意数量的" 不太好, 但目前似乎也没有公认的翻译, 要不保留英文吧?

https://www.w3.org/TR/selectors-4/#typedef-forgiving-selector-list

2022-10-10 09:49 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/css/pseudo-classes/index.md
> +这些伪类接受 [宽容的选择器列表](/zh-CN/docs/Web/CSS/Selector_list) 作为参数。
可容错 怎么样，规范的意思是即使部分选择器有错，其他选择器也会正常解析

2022-10-10 12:51 UTC, LIXiangChen commented on files/zh-cn/web/css/pseudo-classes/index.md
> +这些伪类接受 [宽容的选择器列表](/zh-CN/docs/Web/CSS/Selector_list) 作为参数。
行, 你修改一下? (我不知道当前状态下我这边应该怎么操作...)

另外采用你的翻译, 我把此处涉及的 /zh-CN/docs/Web/CSS/Selector_list 这个页面也更新了一下, 因为里面涉及到对这几个概念的解释, 你可以再review一下

2022-10-10 23:11 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/css/pseudo-classes/index.md
> +这些伪类接受 [宽容的选择器列表](/zh-CN/docs/Web/CSS/Selector_list) 作为参数。
以修改

2022-10-11 10:52 UTC, yin1999 requested changes

2022-10-11 10:54 UTC, yin1999 commented
此外，请阅读 [translation-guide](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md)，规范文档撰写格式

2022-10-11 11:57 UTC, LIXiangChen commented on files/zh-cn/web/css/text-underline-offset/index.md
> +browser-compat: css.properties.text-underline-offset
好的, 拆开了. 所有 _ 都要改成 * 吗? 我看guide里好像没写

2022-10-11 12:08 UTC, yin1999 commented
注意翻译的文档中的空格，此外，请尽量不要在一个PR中放入对多个文档的修改，有时存在较多的问题，要一一列举较为麻烦（也会需要一个比较长的周期才能一次性应用所有的修改）。以后对文档的撰写规范相对熟悉了，可以选择放入多个。

2022-10-11 12:09 UTC, yin1999 commented on files/zh-cn/web/css/text-underline-offset/index.md
> +browser-compat: css.properties.text-underline-offset
_和*的区别在于，使用星号来表示斜体是可以不在*号的两侧保留空格的，但下划线则必须保留空格（否则不会被渲染为斜体）。

2022-10-11 12:11 UTC, LIXiangChen commented on files/zh-cn/web/css/text-underline-offset/index.md
> +browser-compat: css.properties.text-underline-offset
原来如此

2022-10-11 12:29 UTC, LIXiangChen commented
好的, 这个PR中目前没有什么还想修改的了, 我就不动了, 请看看还没有问题

2022-10-11 12:40 UTC, yin1999 commented
中文于中文之间请不要放置空格，对于添加的内容，请尽量地去翻译。我暂时没时间来审查修改了那么多文件的PR，请仔细检查所有内容，我需要过一段时间才能进行审查。

2022-10-11 16:39 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/css/_colon_has/index.md
> +当锚定到一个元素时，如果作为参数传递的任何[相对选择器](/zh-CN/docs/Web/CSS/CSS_Selectors#relative_selector)匹配到至少一个元素，则函数式 CSS [伪类](/zh-CN/docs/Web/CSS/Pseudo-classes) **`:has()`** 表示该元素。这个伪类提供了一种把[可容错相对选择器列表](/zh-CN/docs/Web/
```suggestion
CSS 函数式[伪类](/zh-CN/docs/Web/CSS/Pseudo-classes) **`:has()`** 表示一个元素，如果作为参数传递的任何[相对选择器](/zh-CN/docs/Web/CSS/CSS_Selectors#relative_selector)在锚定到该元素时，至少匹配一个元素。这个伪类通过把[可容错相对选择器列表](/zh-CN/docs/Web/CSS/Selector_list#可容错相对选择器列表)作为参数，提供了一种针对引用元素选择父元素或者先前的兄弟元素的方法。
```

2022-10-11 16:43 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/css/_colon_has/index.md
> +相对选择器列表参数是[可容错](/zh-CN/docs/Web/CSS/Selector_list#可容错选择器列表)的。通常在 CSS 中，当选择器列表中的一个选择器是无效的时，那么整个列表则被视为无效。当 `:has()` 选择器列表中的一个选择器无法解析时，不正确或不受支持的选择器将被忽略，而其它的则将被正常使用。
```suggestion
相对选择器列表参数是[可容错](/zh-CN/docs/Web/CSS/Selector_list#可容错选择器列表)的。通常在 CSS 中，选择器列表中的某个选择器无效时，那么整个列表则被视为无效。当 `:has()` 选择器列表中的一个选择器无法解析时，不正确或不受支持的选择器将被忽略，而其它的则将被正常使用。
```

2022-10-11 16:45 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/css/_colon_has/index.md
> +注意，如果一个浏览器中不支持 `:has()` 伪类本身，则整个选择器块将失效（除非 `:has()` 本身位于一个可容错选择器列表中，比如在 [`:is()`](/zh-CN/docs/Web/CSS/:is) 或 [`:where()`](/zh-CN/docs/Web/CSS/:where) 中）。
```suggestion
注意，如果一个浏览器自身不支持 `:has()` 伪类，则整个选择器块将失效（除非 `:has()` 本身位于一个可容错选择器列表中，比如在 [`:is()`](/zh-CN/docs/Web/CSS/:is) 或 [`:where()`](/zh-CN/docs/Web/CSS/:where) 中）。
```

2022-10-12 02:59 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/css/_colon_has/index.md
> +`:has()` 伪类不能被嵌套在另一个 `:has()` 内。另外，伪元素不是 `:has()` 内的有效选择器。这是因为许多伪元素基于其祖先的样式有条件地存在，如果允许通过 `:has()` 查询这些伪元素可能导致循环查询。虽然 `:has()` 和伪元素不是有效的 `:has()` 选择器，但由于选择器列表是可容错的，它们将只是被忽略。选择器将不会失效。
```suggestion
`:has()` 伪类不能被嵌套在另一个 `:has()` 内。另外，伪元素不是 `:has()` 内的有效选择器。这是因为许多伪元素基于其祖先的样式有条件地存在，如果允许通过 `:has()` 查询这些伪元素可能导致循环查询。虽然 `:has()` 和伪元素在 `:has()` 中是无效的选择器，但由于选择器列表是可容错的，它们将只是被忽略。选择器将不会失效。
```

2022-10-12 06:50 UTC, LIXiangChen commented on files/zh-cn/web/css/_colon_has/index.md
> +注意，如果一个浏览器中不支持 `:has()` 伪类本身，则整个选择器块将失效（除非 `:has()` 本身位于一个可容错选择器列表中，比如在 [`:is()`](/zh-CN/docs/Web/CSS/:is) 或 [`:where()`](/zh-CN/docs/Web/CSS/:where) 中）。
这个可能不太妥哦, 英文原文里 "itself" 指的就是伪类本身, 不是指浏览器. 虽然整体意思差不多, 但想强调的重点不同吧

2022-10-12 06:53 UTC, Jack-Zhang-1314 commented
英文是被动，你翻译之后就拗口了

On Wed, Oct 12, 2022 at 2:51 PM LI XiangChen ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In files/zh-cn/web/css/_colon_has/index.md
> <https://github.com/mdn/translated-content/pull/9143#discussion_r993060270>
> :
>
> >  ```
>
> -## 描述
> +相对选择器列表参数是[可容错](/zh-CN/docs/Web/CSS/Selector_list#可容错选择器列表)的。通常在 CSS 中，当选择器列表中的一个选择器是无效的时，那么整个列表则被视为无效。当 `:has()` 选择器列表中的一个选择器无法解析时，不正确或不受支持的选择器将被忽略，而其它的则将被正常使用。
> +
> +注意，如果一个浏览器中不支持 `:has()` 伪类本身，则整个选择器块将失效（除非 `:has()` 本身位于一个可容错选择器列表中，比如在 [`:is()`](/zh-CN/docs/Web/CSS/:is) 或 [`:where()`](/zh-CN/docs/Web/CSS/:where) 中）。
>
> 这个可能不太妥哦, 英文原文里 "itself" 指的就是伪类本身, 不是指浏览器. 虽然整体意思差不多, 但想强调的重点不同吧
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mdn/translated-content/pull/9143#discussion_r993060270>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATV2GSVJKUJVNMLDLRQ7KQDWCZNVLANCNFSM6AAAAAARAYKWRU>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-10-13 05:21 UTC, yin1999 requested changes

2022-10-13 05:21 UTC, yin1999 commented on files/zh-cn/web/css/_colon_not/index.md
> +- 如果传递给 `:not()` 伪类的选择器无效或者浏览器不支持，则整个规则都将是无效的。克服这种行为的有效方式是使用：[`:is`](/zh-CN/docs/Web/CSS/:is) 伪类，它接受一个可容错选择器列表。例如 `:not(.foo, :invalid-pseudo-class)` 将使整个规则无效，但是 `:is(:not(.foo), :not(:invalid-pseudo
“克服行为”这个翻译是不是不太合适：

```suggestion
- 如果传递给 `:not()` 伪类的选择器无效或者浏览器不支持，则整个规则都将是无效的。避免这种行为的有效方式是使用：[`:is`](/zh-CN/docs/Web/CSS/:is) 伪类，它接受一个可容错选择器列表。例如 `:not(.foo, :invalid-pseudo-class)` 将使整个规则无效，但是 `:is(:not(.foo), :not(:invalid-pseudo-class))` 将匹配任何不是 `.foo` 的元素。
```

2022-10-13 05:21 UTC, yin1999 commented on files/zh-cn/web/css/_colon_has/index.md
> +### 与兄弟组合符一起
常见的翻译并不是“兄弟组合符”，你可以去搜索一下

2022-10-13 05:21 UTC, yin1999 commented on files/zh-cn/web/css/_colon_has/index.md
> +{{EmbedLiveSample('With_the_sibling_combinator', 600, 150)}}
这个宏的第一个参数需要跟随翻译的标题的变化而变化，请不要只是拷贝英文文档中的

2022-10-13 05:21 UTC, yin1999 commented on files/zh-cn/web/css/_colon_has/index.md
> +This example shows two similar texts side-by-side for comparison – the left one with an `H1` heading followed by a paragraph and the right one with an `H1` heading followed by an `H2` heading and the
尽量翻译所有的内容，对于拿不准的内容，可以先选择在议题或讨论中提问。或者去搜索相关的资料。所以我**不推荐**在一个PR中包含太多的修改。这不仅不利于我们的审查，也不利于快速将修改合并到主分支中。

再者，如果这一部分内容是英文的，读者可以选择直接阅读英文文档，阅读中文文档并不能为读者带来良好的阅读体验。

2022-10-13 06:03 UTC, LIXiangChen commented on files/zh-cn/web/css/_colon_has/index.md
> +### 与兄弟组合符一起
我知道以前的文档里是翻译成了 "器", 但是这明显是不太合适的, 因为它就是一个操作符嘛, 在其它网站的文章里, 一般也是称为 "符" 的. 所以如果可以的话, 我其实想把所有的都改成 "符" (除非 W3C 有指定的官方译法)

2022-11-04 08:46 UTC, yin1999 approved these changes

2022-11-04 08:47 UTC, merged