zh-cn(update): sync with english for textDecoder
mdn/translated-content pull request #9156
Opened 2022-10-10 06:47 UTC by Jack-Zhang-1314

### Description

### Motivation

### Additional details

### Related issues and pull requests

2022-10-11 09:40 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/textdecoder/index.md
> +在此示例中，我们对俄语文本“Привет，мир！”，它的意思是（"Hello, world."）进行解码。在我们的 {{domxref("TextDecoder/TextDecoder", "TextDecoder()")}} 构造函数中，我们指定 Windows-1251 字符编码，适用于西里尔字母。
```suggestion
在此示例中，我们对俄语文本“Привет，мир！”进行编码，它的意思是（"Hello, world."）。在我们的 {{domxref("TextDecoder/TextDecoder", "TextDecoder()")}} 构造函数中，我们指定适用于西里尔字母脚本的 Windows-1251 字符编码，。
```

2022-10-11 10:49 UTC, yin1999 requested changes

2022-10-11 10:49 UTC, yin1999 commented on files/zh-cn/web/api/textdecoder/index.md
> +**`TextDecoder`** 接口表示一个文本解码器，一个解码器只支持一种特定文本编码，例如 `UTF-8`、 `ISO-8859-2`、`KOI8-R`、`GBK`, 等等。解码器将字节流作为输入，并提供代码点流作为输出。
```suggestion
**`TextDecoder`** 接口表示一个文本解码器，一个解码器只支持一种特定文本编码，例如 `UTF-8`、`ISO-8859-2`、`KOI8-R`、`GBK`，等等。解码器将字节流作为输入，并提供码位流作为输出。

{{AvailableInWorkers}}
```

2022-10-11 10:49 UTC, yin1999 commented on files/zh-cn/web/api/textdecoder/index.md
> +  - : 返回一个新构造的 `TextDecoder`，它使用参数中指定的解码方法生成代码点流。
```suggestion
  - : 返回一个新构造的 `TextDecoder`，它使用参数中指定的解码方法生成码位流。
```

2022-10-11 10:49 UTC, yin1999 commented on files/zh-cn/web/api/textdecoder/index.md
> +  - : {{DOMxRef("DOMString")}} 所包含的解码器的名称，表示 `TextDecoder` 所使用的解码方法的字符串。
对比翻译一下

2022-10-11 10:49 UTC, yin1999 commented on files/zh-cn/web/api/textdecoder/index.md
> +  - : 布尔值，{{jsxref('Boolean')}}，是否显示致命错误。
翻译得也不太对，好好修改吧：

```suggestion
  - : 布尔值（{{jsxref('Boolean')}}），是否显示致命错误。
```

2022-10-11 10:49 UTC, yin1999 commented on files/zh-cn/web/api/textdecoder/index.md
> +  - : 返回一个{{DOMxRef("DOMString")}}，其中包含使用特定 `TextDecoder` 对象的方法解码的文本。
请对比英文文档

2022-10-11 10:49 UTC, yin1999 commented on files/zh-cn/web/api/textdecoder/index.md
>  - [Node.js 支持从 v11.0.0 全局导出](https://nodejs.org/api/util.html#util_class_util_textdecoder)
这个翻译是不对的

2022-10-11 15:46 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/textdecoder/index.md
> +  - : {{DOMxRef("DOMString")}} 所包含的解码器的名称，表示 `TextDecoder` 所使用的解码方法的字符串。
```suggestion
  - : 一个包含的解码器名称的字符串，即描述 `TextDecoder` 将使用的方法的字符串。
```

2022-10-11 15:50 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/textdecoder/index.md
>  - [Node.js 支持从 v11.0.0 全局导出](https://nodejs.org/api/util.html#util_class_util_textdecoder)
```suggestion
- [从 Node.js v11.0.0 开始支持从全局导出](https://nodejs.org/api/util.html#util_class_util_textdecoder)
```

2022-10-11 22:45 UTC, yin1999 requested changes

2022-10-11 22:45 UTC, yin1999 commented on files/zh-cn/web/api/textdecoder/index.md
> +  - : 布尔值（{{jsxref('Boolean')}}），是否显示致命错误。
这里的翻译还未修改

2022-10-12 02:47 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/textdecoder/index.md
> +  - : 布尔值（{{jsxref('Boolean')}}），是否显示致命错误。
```suggestion
  - : 布尔值（{{jsxref('Boolean')}}），表示错误模式是否致命。
```

2022-10-12 03:09 UTC, yin1999 approved these changes

2022-10-12 03:15 UTC, merged