セレクターリストを 2022/10/05 時点の英語版に同期
mdn/translated-content pull request #9218
Opened 2022-10-12 14:59 UTC by rch850

### Description

[セレクターリスト](https://developer.mozilla.org/ja/docs/Web/CSS/Selector_list)のページを更新しました。

### Motivation

[:has()](https://developer.mozilla.org/en-US/docs/Web/CSS/:has) を和訳するにあたって forgiving をどう訳すか迷ったので、それについて詳述しているページを先に和訳しようと思いました。

もともとの和訳に「寛容な」という形容詞があったので、そのまま「寛容なセレクターリスト」や「寛容な相対セレクターリスト」といった形で和訳しました。

### Additional details

### Related issues and pull requests

2022-10-18 17:03 UTC, mfuji09 requested changes
表記方法の問題だけですが、修正をお願いします。
同じ問題は繰り返して指摘していませんので、ファイルの他の箇所も同様に修正をお願いします。

2022-10-18 17:03 UTC, mfuji09 commented on files/ja/web/css/selector_list/index.md
> +複数のセレクターが同じ宣言を共有しているときは、カンマ区切りのリストにまとめることができます。セレクターリストはいくつかの関数型 CSS 擬似クラスのパラメータとして与えることもできます。空白文字がカンマの前後に入る場合もあります。
「パラメータ」は -er で終わる語ですので、最後に長音を付けてください。

2022-10-18 17:03 UTC, mfuji09 commented on files/ja/web/css/selector_list/index.md
> +次の3つの宣言は等価です:
数字の周囲にも空白を入れてください。

2022-10-18 17:03 UTC, mfuji09 commented on files/ja/web/css/selector_list/index.md
> +- 疑似クラス [`:is()`](/ja/docs/Web/CSS/:is)、[`:where()`](/ja/docs/Web/CSS/:where)、[`:not()`](/ja/docs/Web/CSS/:not)、[`:has()`](/ja/docs/Web/CSS/:has) は、寛容なセレクターリストを受け付けます。
上で「擬似要素」を使用しているので、こちらも「擬似クラス」とした方が良いと思います。

2022-10-22 07:58 UTC, rch850 commented on files/ja/web/css/selector_list/index.md
> +複数のセレクターが同じ宣言を共有しているときは、カンマ区切りのリストにまとめることができます。セレクターリストはいくつかの関数型 CSS 擬似クラスのパラメータとして与えることもできます。空白文字がカンマの前後に入る場合もあります。
うっかりしてました。修正しました。

2022-10-22 07:59 UTC, rch850 commented on files/ja/web/css/selector_list/index.md
> +次の3つの宣言は等価です:
こちらも修正しました。

2022-10-22 08:03 UTC, rch850 commented on files/ja/web/css/selector_list/index.md
> +- 疑似クラス [`:is()`](/ja/docs/Web/CSS/:is)、[`:where()`](/ja/docs/Web/CSS/:where)、[`:not()`](/ja/docs/Web/CSS/:not)、[`:has()`](/ja/docs/Web/CSS/:has) は、寛容なセレクターリストを受け付けます。
上での「疑似要素」は `> ul::after` を指しているのですが、こちらでは `:is()` などを指しているので、別物だと思いました。原文でも前者は pseudo-elements、後者は pseudo-classes となっており、区別していると思います。

2022-10-22 10:56 UTC, mfuji09 commented on files/ja/web/css/selector_list/index.md
> +- 疑似クラス [`:is()`](/ja/docs/Web/CSS/:is)、[`:where()`](/ja/docs/Web/CSS/:where)、[`:not()`](/ja/docs/Web/CSS/:not)、[`:has()`](/ja/docs/Web/CSS/:has) は、寛容なセレクターリストを受け付けます。
「擬似要素」と「疑似クラス」で「擬」の字が違うという指摘です。

2022-10-24 19:59 UTC, rch850 commented on files/ja/web/css/selector_list/index.md
> +- 疑似クラス [`:is()`](/ja/docs/Web/CSS/:is)、[`:where()`](/ja/docs/Web/CSS/:where)、[`:not()`](/ja/docs/Web/CSS/:not)、[`:has()`](/ja/docs/Web/CSS/:has) は、寛容なセレクターリストを受け付けます。
そういうことでしたか！完全に見過ごしていました。擬似に揃えました。

2022-10-25 13:34 UTC, mfuji09 approved these changes
OKです。

2022-10-25 13:35 UTC, merged