feat: add dragstart event translation
mdn/translated-content pull request #9340
Opened 2022-10-18 04:24 UTC by abrahamcalsin

## Description
Added new Spanish translation of HTMLElement: dragstart event

## Motivation

## Additional details

## Related issues and pull requests

2022-10-18 16:51 UTC, Graywolf9 requested changes
Hola! @abrahamcalsin muchas gracias por contribuir a MDN en español

Hemos migrado de `html` a markdown `md` por lo que la estructura del documento sería el diferente, puedes utilizar de referencia la versión en inglés

Página: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dragstart_event
Fuente: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/dragstart_event/index.md?plain=1

Nuevamente, muchas gracias por tu tiempo y ayuda

2022-10-18 17:28 UTC, JuanVqz commented
@abrahamcalsin tambien puedes [unirte al chat](https://chat.mozilla.org/#/room/#mdn-l10n-es:mozilla.org) para resolver cualquier duda que puedas tener.

Saludos.

2022-10-19 19:10 UTC, Graywolf9 commented on files/es/web/api/htmlelement/dragstart_event/index.md
> +En adición a las propiedades listadas, a continuación las propiedades de la interfaz principal, {{domxref("Event")}}, están disponibles.
Para estar igual que en la versión original en inglés

```suggestion
_En adición a las propiedades listadas, a continuación las propiedades de la interfaz principal, {{domxref("Event")}}, están disponibles._
```

2022-10-19 19:11 UTC, Graywolf9 commented on files/es/web/api/htmlelement/dragstart_event/index.md
> +  - Los datos que se transfieren durante una interacción de arrastrar y soltar.
Los `:` lo convierten en una lista de definición en lugar de una lista desordenada

```suggestion
- {{domxref("DragEvent/dataTransfer", "DragEvent.dataTransfer")}} {{ReadOnlyInline}}
  - : Los datos que se transfieren durante una interacción de arrastrar y soltar.
```

2022-10-19 19:12 UTC, Graywolf9 commented on files/es/web/api/htmlelement/dragstart_event/index.md
> +
Texto faltante

```suggestion
Escuchamos el evento `dragstart` para hacer que el elemento sea medio transparente mientras se arrastra.

For a more complete example of [drag](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/drag_event) and drop, see the page for the drag event.
```

2022-10-19 19:13 UTC, Graywolf9 commented on files/es/web/api/htmlelement/dragstart_event/index.md
> +  <div id="draggable" draggable="true">This div is draggable</div>
Las cadenas literales pueden ser traducidas

```suggestion
  <div id="draggable" draggable="true">Este div es arrastrable</div>
```

2022-10-19 19:14 UTC, Graywolf9 commented on files/es/web/api/htmlelement/dragstart_event/index.md
> +  event.target.classList.remove("dragging");
```suggestion
  // hazlo medio transparente
  event.target.classList.add("dragging");
});
source.addEventListener("dragend", (event) => {
  // restablecer la transparencia
  event.target.classList.remove("dragging");
```

2022-10-19 19:15 UTC, Graywolf9 commented
Excelente traducción @abrahamcalsin te he dejado algunos pequeños comentarios

2022-10-19 22:02 UTC, Graywolf9 approved these changes
Muchas gracias por todo tu tiempo y atenciones @abrahamcalsin

2022-10-19 22:02 UTC, merged