zh-cn(translate): translate about showPicker
mdn/translated-content pull request #9341
Opened 2022-10-18 06:13 UTC by Jack-Zhang-1314

### Description

### Motivation

### Additional details

### Related issues and pull requests

2022-10-18 06:14 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/htmlinputelement/showpicker/index.md
> +[瞬态用户激活](/zh-CN/docs/Web/Security/User_activation)是需要的。用户必须与页面或者  UI 元素交互，才能使这个功能按顺序工作。
```suggestion
[瞬态用户激活](/zh-CN/docs/Web/Security/User_activation)是需要的。用户必须与页面或者 UI 元素交互，才能使这个功能按顺序工作。
```

2022-10-18 06:16 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/htmlinputelement/showpicker/index.md
> +以下代码展示了当按钮被点击时，input 展示的交互层。.
```suggestion
以下代码展示了当按钮被点击时，input 展示的交互层。
```

2022-10-18 11:23 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/htmlinputelement/showpicker/index.md
> +  - : 如果元素不可变，则抛出，这意味着用不不能修改它和/或无法自动预填充它。
```suggestion
  - : 如果元素不可变，则抛出，这意味着用户不能修改它和/或无法自动预填充它。
```

2022-10-18 13:01 UTC, yin1999 requested changes
“交互层”这个翻译并不合适，请斟酌

2022-10-29 01:22 UTC, yin1999 commented
> 我只想到了 **交互面板** 和 **交互层**（这个字少），但是不翻译似乎不太好

Picker 虽然确实就是一个与用户交互的东西，但整个UI不就是和用户交互的吗？若不知道怎么翻译，完全可以参考一下其它的前端或者产品。

这个词本来就是选取的意思，我觉得翻译成“选择器”是更加合适的。

然后，请检查全文翻译，有些句子翻译得不对，下面的一个明显的错误。

![image](https://user-images.githubusercontent.com/15844309/198755458-47fcfe9e-efd4-4042-acc5-97347dbb89ad.png)

2022-10-29 04:28 UTC, Jack-Zhang-1314 commented
﻿对，但是翻译成选择器会误认为 css 的 selector，而且交互突出这是用户手动等触发吧。我不认为选择器是很好的翻译

2022-10-29 04:31 UTC, yin1999 commented
> 对，但是翻译成选择器会误认为 css 的 selector，而且交互突出这是用户手动等触发吧。我不认为选择器是很好的翻译

这是 html，和 css 的选择器完全是两个不同的概念。要是 html 里面有一个 selector 又有一个 picker，这样确实容易搞混。交互层但从字面上就看不出来，到底是什么，这个概念太宽泛了。就像我上面提到的，整个用户界面就是一个完整的交互层。

2022-10-29 04:44 UTC, Jack-Zhang-1314 commented
对，但是你都翻译成了 选择器。这很容易让学过 css 的人产生疑惑，这是什么，然后之下的描述又和他们自己的选择器没什么大关系，我不认为这是好的。交互层，我想表达的是用户触发之后所得倒的效果。

2022-10-29 04:54 UTC, yin1999 commented
> 对，但是你都翻译成了 选择器。这很容易让学过 css 的人产生疑惑，这是什么，然后之下的描述又和他们印象的选择器的模型的意思没什么大关系，我不认为这是好的。交互层，我想表达的是用户触发之后所得倒的效果。

我并不支持“交互层”这样的翻译，请找出广泛使用这一翻译的证明。我见到的基本都是翻译为“选择器”或类似意思的。单纯搜索“交互层”这一词，也没见到这样的用法。

2022-10-29 05:05 UTC, Jack-Zhang-1314 commented
你说的有道理。但是 选择器 不是好的翻译，我认为 选择框 好一点

https://www.zhangxinxu.com/study/202210/js-showpicker-demo.php

2022-10-29 06:16 UTC, yin1999 commented
> 你说的有道理。但是 选择器 不是好的翻译，我认为 选择框 好一点
> 
> https://www.zhangxinxu.com/study/202210/js-showpicker-demo.php

选择器这一翻译在很多前端框架中都是这么翻译的，我并不认为这有什么不妥。但你想要改成“选择框”也行，我不反对这一翻译：https://element-plus.gitee.io/zh-CN/component/date-picker.html

2022-10-29 07:28 UTC, Jack-Zhang-1314 commented
> > 你说的有道理。但是 选择器 不是好的翻译，我认为 选择框 好一点
> > https://www.zhangxinxu.com/study/202210/js-showpicker-demo.php
> 
> 选择器这一翻译在很多前端框架中都是这么使用的，我并不认为这有什么不妥。但你想要改成“选择框”也行，我不反对这一翻译：https://element-plus.gitee.io/zh-CN/component/date-picker.html

那就选择器吧，我将保留同时出现的 picker 和 selected 英文，以便辨别

2022-10-29 12:35 UTC, yin1999 approved these changes

2022-10-29 12:35 UTC, merged