refactor: convert dragover_event(html) file to markdown (es)
mdn/translated-content pull request #9412
Opened 2022-10-20 22:52 UTC by abrahamcalsin

## Description
Convert the dragover_event(html) file to markdown (es).

## Motivation

## Additional details
The conversion was not done as is, I added and removed some things to adapt to the new markdown rules.

## Related issues and pull requests

2022-10-21 15:21 UTC, Graywolf9 commented on files/es/web/api/htmlelement/dragover_event/index.md
> +- En el manejador de eventos drop para la zona de caída, manejamos el movimiento del elemento arrastrable desde el contenedor original a la zona de caída.
```suggestion
- En el manejador de eventos `dragstart`, obtenemos una referencia al elemento que el usuario arrastró
- En el manejador del evento `dragover` para el contenedor de destino, llamamos a `event.preventDefault()`, que lo habilita para recibir eventos de `drop`.
- En el manejador de eventos `drop` para la zona de caída, manejamos el movimiento del elemento arrastrable desde el contenedor original a la zona de caída.
```

2022-10-21 15:24 UTC, Graywolf9 requested changes
Hola! @abrahamcalsin muchas gracias de nuevo por tu tiempo y contribución

Te dejo algunas observaciones, además de comentarte que notó que actualizaste algunas partes con la versión en inglés pero otras las dejaste como la antigua versión.

La versión en inglés es la versión base y para decir que un documento está actualizado en español debe de tener exactamente el mismo contenido pero en español

Nuevamente muchas gracias por todo

2022-10-21 15:24 UTC, Graywolf9 commented on files/es/web/api/htmlelement/dragover_event/index.md
> +- En el manejador de eventos drop para la zona de caída, manejamos el movimiento del elemento arrastrable desde el contenedor original a la zona de caída.
Se mantienen los formatos tal cual en inglés

```suggestion
- En el manejador de eventos `dragstart`, obtenemos una referencia al elemento que el usuario arrastró
- En el manejador del evento `dragover` para el contenedor de destino, llamamos a `event.preventDefault()`, que lo habilita para recibir eventos de `drop`.
- En el manejador de eventos `drop` para la zona de caída, manejamos el movimiento del elemento arrastrable desde el contenedor original a la zona de caída.
```

2022-10-21 15:24 UTC, Graywolf9 commented on files/es/web/api/htmlelement/dragover_event/index.md
> +For a more complete example of [drag](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/drag_event) and drop, see the page for the drag event.
Faltó traducir

```suggestion
For a more complete example of [drag](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/drag_event) and drop, see the page for the drag event.
```

2022-10-25 18:18 UTC, Graywolf9 commented
Hola! @abrahamcalsin espero te encuentres muy bien, tienes alguna duda o comentarios?

2022-10-26 03:57 UTC, abrahamcalsin commented
> Hola! @abrahamcalsin espero te encuentres muy bien, tienes alguna duda o comentarios?

Hola @Graywolf9 !

Sí, tengo una. Entonces, si ahora vuelvo a actualizarlo, ¿puedo modificar todo el contenido de la versión anterior y añadir el contenido completo de la versión en inglés pero en español? obviamente siguiendo las reglas de contribución.

2022-10-26 15:08 UTC, Graywolf9 commented
Así es @abrahamcalsin si lo deseas puedes dejarlo al día sin ningún problema en este mismo PR y se revisa como actualización del contenido también

2022-10-26 16:24 UTC, Graywolf9 commented on files/es/web/api/htmlelement/dragover_event/index.md
> +
sección repetida

```suggestion
```

2022-10-26 16:25 UTC, Graywolf9 commented on files/es/web/api/htmlelement/dragover_event/index.md
> +El evento se activa en la caída al objetivo.
```suggestion
El evento se activa en el objetivo de caída.
```

2022-10-26 16:27 UTC, Graywolf9 commented on files/es/web/api/htmlelement/dragover_event/index.md
> +Usar el nombre del evento en métodos como {{domxref("EventTarget.addEventListener", "addEventListener()")}} , o establecer una propiedad de controlador de eventos.
```suggestion
Usar el nombre del evento en métodos como {{domxref("EventTarget.addEventListener", "addEventListener()")}} , o establecer una propiedad de manejador de eventos.
```

2022-10-26 16:29 UTC, Graywolf9 commented on files/es/web/api/htmlelement/dragover_event/index.md
> +    <div class="dropzone"></div>
Para tener también el ejemplo actualizado

```suggestion
<div class="dropzone">
  <div id="draggable" draggable="true">Este div es arrastrable</div>
</div>
<div class="dropzone" id="droptarget"></div>
```

2022-10-26 16:31 UTC, Graywolf9 commented on files/es/web/api/htmlelement/dragover_event/index.md
> +}
```suggestion
body {
  /* Impedir que el usuario seleccione texto en el ejemplo */
  user-select: none;
}
#draggable {
  text-align: center;
  background: white;
}
.dropzone {
  width: 200px;
  height: 20px;
  background: blueviolet;
  margin: 10px;
  padding: 10px;
}
```

2022-10-26 16:33 UTC, Graywolf9 commented on files/es/web/api/htmlelement/dragover_event/index.md
> +);
```suggestion
let dragged = null;
const source = document.getElementById("draggable");
source.addEventListener("dragstart", (event) => {
  // almacenar una ref. en el elemento arrastrado
  dragged = event.target;
});
const target = document.getElementById("droptarget");
target.addEventListener("dragover", (event) => {
  // impedir el valor predeterminado para permitir soltar
  event.preventDefault();
});
target.addEventListener("drop", (event) => {
  // prevent default action (open as link for some elements)
  event.preventDefault();
  // move dragged element to the selected drop target
  if (event.target.className === "dropzone") {
    dragged.parentNode.removeChild(dragged);
    event.target.appendChild(dragged);
  }
});
```

2022-10-26 16:35 UTC, Graywolf9 reviewed
Muchas gracias por tu tiempo y los nuevos cambios, te he dejado unas cuantas observaciones.

2022-10-26 18:57 UTC, Graywolf9 commented on files/es/web/api/htmlelement/dragover_event/index.md
> +### JavaScript
Para arreglar el ejemplo en vivo

```suggestion
#### HTML

```html
<div class="dropzone">
  <div id="draggable" draggable="true">Este div es arrastrable</div>
</div>
<div class="dropzone" id="droptarget"></div>
```

#### CSS

```css
body {
  /* Impedir que el usuario seleccione texto en el ejemplo */
  user-select: none;
}
#draggable {
  text-align: center;
  background: white;
}
.dropzone {
  width: 200px;
  height: 20px;
  background: blueviolet;
  margin: 10px;
  padding: 10px;
}
```

#### JavaScript
```

2022-10-26 19:11 UTC, Graywolf9 commented on files/es/web/api/htmlelement/dragover_event/index.md
> +<div class="dropzone" id="droptarget"></div>
````suggestion
#### HTML

```html
<div class="dropzone">
  <div id="draggable" draggable="true">Este div es arrastrable</div>
</div>
<div class="dropzone" id="droptarget"></div>
```

#### CSS

```css
body {
  /* Impedir que el usuario seleccione texto en el ejemplo */
  user-select: none;
}
#draggable {
  text-align: center;
  background: white;
}
.dropzone {
  width: 200px;
  height: 20px;
  background: blueviolet;
  margin: 10px;
  padding: 10px;
}
```

#### JavaScript
````

2022-10-26 19:24 UTC, Graywolf9 approved these changes
Excelente, muchas gracias a ti por tu tiempo, disposición y valiosa ayuda

2022-10-26 19:25 UTC, merged