feat(translate):  Client-side tooling overview の翻訳
mdn/translated-content pull request #9442
Opened 2022-10-22 09:02 UTC by gurezo

@hmatrjp @potappo 
- [ Client-side tooling overview の翻訳 #651 ](https://github.com/mozilla-japan/translation/issues/651)  のPRです。
- [原文追加](https://github.com/mdn/translated-content/commit/2bd469c908c45c0053b8e09389acfecdba66c365) 2bd469c
- [url リンク 日本語サイトに変更](https://github.com/mdn/translated-content/commit/fb0aa6ff7fc6a8dbf2eff43532d6277f34de06cd) fb0aa6f
- [ページタイトル、参照リンク名翻訳](https://github.com/mdn/translated-content/commit/34c6a4a0bdc7f9ad7c30274db8f0f84246803fe2) 34c6a4a
- [冒頭セクション翻訳](https://github.com/mdn/translated-content/commit/d14ec39ea815e069b1213d6e200755a6680991e6) d14ec39
- [Overview of modern tooling / 最新のツールの概要翻訳](https://github.com/mdn/translated-content/commit/901bcdbd465d2fc81c9439a74e03de67e0a23cc4) 901bcdb
- [The modern tooling ecosystem / 最新ツールのエコシステム翻訳](https://github.com/mdn/translated-content/commit/0a082410fc43341510ed144e37c1c0796411d916) 0a08241

2022-10-22 09:17 UTC, gurezo commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/overview/index.md
今回翻訳したページ以外は、日本語ページが存在しないのでリンクタイトルの翻訳はスコープ外としました。

2022-11-19 06:38 UTC, potappo requested changes
翻訳ありがとうございます。
以下、修正が必要な指摘です。
長音漏れは各行で指摘を入れていますので、合わせて確認お願いします。

tags は削除してください。
https://mozilla-japan.github.io/mdn-translation-guide/new-translation-procedure-2.html

「Web」は「ウェブ」としてください（ツール名などの固定名詞は除く）。
https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline

「ソース コード管理」など、カタカナの後に不自然な空白がある箇所が見受けられます。
なんらかの理由があって追加しているところは良いですが、意図しない空白がないか全体的に見直しをお願いします。

Parcel の説明の部分、「それらを使用しようとするたびに自動的に。」が不自然に浮いてしまっているので、翻訳の見直しをお願いします。

2022-11-19 06:38 UTC, potappo commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/overview/index.md
> +Web アプリのライフサイクルのこの段階では、通常、"将来のコード" (ブラウザーでネイティブ サポートされていない可能性のある最新の CSS や JavaScript 機能など) でコーディングするか、 [TypeScript](https://www.typescriptlang.org/) などの別の言語を完全に使用してコーディングすることができます。 変換ツールは、ブラウザと互換性のある
```suggestion
Web アプリのライフサイクルのこの段階では、通常、"将来のコード" (ブラウザーでネイティブ サポートされていない可能性のある最新の CSS や JavaScript 機能など) でコーディングするか、 [TypeScript](https://www.typescriptlang.org/) などの別の言語を完全に使用してコーディングすることができます。 変換ツールは、ブラウザーと互換性のあるコードを生成して、本番環境で使用できるようにします。 
```

2022-11-19 06:38 UTC, potappo commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/overview/index.md
> +コード フォーマッタは、コードのエラーを指摘するのではなく、通常、スタイル ルールに従ってコードが正しくフォーマットされていることを確認し、理想的には見つけたエラーを自動的に修正する傾向があることを除いて、リンターに多少関連しています。
```suggestion
コード フォーマッターは、コードのエラーを指摘するのではなく、通常、スタイル ルールに従ってコードが正しくフォーマットされていることを確認し、理想的には見つけたエラーを自動的に修正する傾向があることを除いて、リンターに多少関連しています。
```

2022-11-19 06:38 UTC, potappo commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/overview/index.md
> +[Prettier](https://prettier.io/) はコード フォーマッタの非常に一般的な例であり、モジュールの後半で使用します。
```suggestion
[Prettier](https://prettier.io/) はコード フォーマッターの非常に一般的な例であり、モジュールの後半で使用します。 
```

2022-11-19 06:38 UTC, potappo commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/overview/index.md
> +   - [TypeScript](https://www.typescriptlang.org/): TypeScript は、多数の追加機能を提供する JavaScript のスーパーセットです。 TypeScript コンパイラは、本番用にビルドするときに TypeScript コードを JavaScript に変換します。
```suggestion
   - [TypeScript](https://www.typescriptlang.org/): TypeScript は、多数の追加機能を提供する JavaScript のスーパーセットです。 TypeScript コンパイラーは、本番用にビルドするときに TypeScript コードを JavaScript に変換します。 
```

2022-11-19 06:38 UTC, potappo commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/overview/index.md
> +  - たとえば、npm パッケージ マネージャーを使用して依存関係を管理している場合は、 [npm ホームページ](https://www.npmjs.com/) にアクセスして、探しているツールの種類を検索することをお勧めします。日付フォーマット ユーティリティ、または一般的なコード フォーマッタを検索している場合は「フォーマッタ」。 人気度、品質、メンテナンス スコア、およびパッケージが最
```suggestion
  - たとえば、npm パッケージ マネージャーを使用して依存関係を管理している場合は、 [npm ホームページ](https://www.npmjs.com/) にアクセスして、探しているツールの種類を検索することをお勧めします。日付フォーマット ユーティリティ、または一般的なコード フォーマッターを検索している場合は「formatter (フォーマッター)」。 人気度、品質、メンテナンス スコア、およびパッケージが最後に更新されたのはいつ頃かを確認してください。 また、クリックしてツール ページにアクセスし、パッケージの月間ダウンロード数や、必要な機能を備えているかどうかを判断するために使用できる適切なドキュメントがあるかどうかを確認してください。 これらの基準に基づくと、 [date-fns ライブラリ](https://www.npmjs.com/package/date-fns) は、使用するのに適した日付フォーマット ツールのように見えます。 このモジュールの第 3 章では、このツールの動作を確認し、パッケージ マネージャー全般について詳しく学習します。
```

2022-11-19 06:38 UTC, potappo commented on files/ja/learn/tools_and_testing/understanding_client-side_tools/overview/index.md
> +  - たとえば、npm パッケージ マネージャーを使用して依存関係を管理している場合は、 [npm ホームページ](https://www.npmjs.com/) にアクセスして、探しているツールの種類を検索することをお勧めします。日付フォーマット ユーティリティ、または一般的なコード フォーマッタを検索している場合は「フォーマッタ」。 人気度、品質、メンテナンス スコア、およびパッケージが最
検索語としては英語を入れるべきかと思うので、原語を追記しました。

2022-11-19 08:53 UTC, gurezo commented
@potappo 

[0735878](https://github.com/mdn/translated-content/pull/9442/commits/0735878739db7a0689fa06a8edf09d5b4263c51d) 修正しました。
お時間がある時にレビューをお願いします。

2022-12-17 05:46 UTC, potappo approved these changes
OK です。

2022-12-17 06:12 UTC, merged