PointerEvent.height の更新
mdn/translated-content pull request #9444
Opened 2022-10-22 09:44 UTC by SuzukiKatsuma

### Description

[PointerEvent.height](https://developer.mozilla.org/ja/docs/Web/API/PointerEvent/height) の翻訳を更新しました。

* 原文リンク：https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/height

### Related issues and pull requests

resolve: mozilla-japan/translation#655

2022-10-25 13:33 UTC, mfuji09 requested changes
3点の修正をお願いします。

2022-10-25 13:33 UTC, mfuji09 commented on files/ja/web/api/pointerevent/height/index.md
> +l10n:
page-type: と browser-compat: は翻訳記事では不要ですので、削除してください。

2022-10-25 13:33 UTC, mfuji09 commented on files/ja/web/api/pointerevent/height/index.md
> +{{domxref("PointerEvent")}} インターフェイスの読み取り専用プロパティである **`height`** は、ポインタの接触ジオメトリーの高さを y 軸に従って表します (CSS ピクセル単位)。またポインタデバイスのソース (指など) によっては、与えられたポインタに対して、各イベントが異なる値を生成することがあります。
「ポインタ」も「ポインター」と長音表記してください。

2022-10-25 13:33 UTC, mfuji09 commented on files/ja/web/api/pointerevent/height/index.md
> +このプロパティの例は [PointerEvent.width の例](/ja/docs/Web/API/PointerEvent/width#example)に含まれています。
リンク先の記事ではフラグメントが #例 となりますので、そのように修正をお願いします。

2022-10-25 13:52 UTC, SuzukiKatsuma commented
@mfuji09 さん、コメントいただいた箇所を修正しました！
再度レビューをよろしくお願いします。

2022-10-26 16:53 UTC, mfuji09 approved these changes
OKです。

2022-10-26 16:53 UTC, merged