Update SyntaxError
mdn/translated-content pull request #945
Opened 2021-05-21 00:31 UTC by wisedog

en-US 문서에 맞춰 Syntax Error 문서를 다시 작성하였습니다.

2021-05-22 10:21 UTC, cos18 requested changes

2021-05-22 10:21 UTC, cos18 commented on files/ko/web/javascript/reference/global_objects/syntaxerror/index.html
> +    이 오류가 발생한 줄의 칸 수. {{jsxref("Error")}}로부터 상속되었습니다.
```suggestion
    이 오류가 발생한 줄(행)에서의 열 위치. {{jsxref("Error")}}로부터 상속되었습니다.
```

`줄의 칸 수`라고 번역할 경우 그 줄의 **총 칸 수**로 해석할 가능성도 있고, `SyntaxError.prototype.lineNumber`와 동일한 의미로 해석할 가능성도 있어보입니다. 위와 같이 바꾸는 게 어떨까요?

2021-05-22 13:04 UTC, wisedog commented on files/ko/web/javascript/reference/global_objects/syntaxerror/index.html
> +    이 오류가 발생한 줄의 칸 수. {{jsxref("Error")}}로부터 상속되었습니다.
좋은 의견입니다. 제안하시는 번역이 더 매끄럽네요.

2021-05-27 15:56 UTC, cos18 commented
@wisedog 수정 완료하셨나요? 리뷰를 재요청하지 않으셔서 확인차 문의드립니다!

2021-05-27 23:30 UTC, wisedog commented
제가 깜빡했네요 : (

2021-05-28 09:49 UTC, cos18 approved these changes
LGTM 👍

2021-05-28 09:50 UTC, merged