[ko] Add 'test your skills! - variables' section
mdn/translated-content pull request #948
Opened 2021-05-21 06:39 UTC by logic-finder

https://developer.mozilla.org/ko/docs/Learn/JavaScript/First_steps/Variables
문서 하단에 'test your skills! - variables' 섹션 추가하고 해당 페이지(풀리퀘스트 #946)로의 링크 추가하였습니다.

2021-05-29 03:07 UTC, GwangYeol-Im requested changes
상세 코멘트 확인 부탁드립니다!

2021-05-29 03:07 UTC, GwangYeol-Im commented on files/ko/learn/javascript/first_steps/variables/index.html
> +<p>당신은 이 문서의 끝에 도달했지만, 가장 중요한 정보들을 기억할 수 있으신가요? 당신은 나아가기 전에 이 정보들을 보유하고 있다는 것을 확인하는 추가적인 테스트들을 찾을 수 있습니다 — 다음을 보세요: <a href="/ko/docs/Learn/JavaScript/First_steps/Test_your_skills:_variables">당신의 기량을
해당 섹션 확인했습니다 :) 테스트 섹션이 있는 것은 좋은 방향이지만, 현재 안내 문구가 다소 번역투로 변환 되어 있어 글의 위의 흐름과 비교해 보았을 때 어색한 감이 없지 않아 있는 듯해요! 괜찮다면 좀 더 자연스러운 문장을 구사해보면 어떨까 싶네요!!

2021-05-29 08:11 UTC, logic-finder commented on files/ko/learn/javascript/first_steps/variables/index.html
> +<p>당신은 이 문서의 끝에 도달했지만, 가장 중요한 정보들을 기억할 수 있으신가요? 당신은 나아가기 전에 이 정보들을 보유하고 있다는 것을 확인하는 추가적인 테스트들을 찾을 수 있습니다 — 다음을 보세요: <a href="/ko/docs/Learn/JavaScript/First_steps/Test_your_skills:_variables">당신의 기량을
안녕하세요 코멘트 남겨주셔서 감사합니다. 다름이 아니오라 지금 #987 에서 리뷰어님께서 제기하신 문제가 있는데 이게 해결되면 말씀하신 부분 수정하도록 하겠습니다. 제가 초보인지라 깃을 다룰 때 실수를 한 것 같은데 지금 이 pr에서도 보시다시피 저는 분명 브랜치를 나눠서 작업했는데 예전에 올린 다른 pr의 커밋들까지(#925, #946) 본 pr(#948)의 커밋에 속해 있어서 본 pr이 merged된다면 conflict가 일어날 것으로 예상됩니다. 혹시 귀한 시간이 남으신다면 잠깐만 사용하셔서 #987 에서 제가 작성한 코멘트에 해당하는 문제를 어떻게 해결하면 좋을지 전문가의 고견을 나눠주실 수 있으신가요 ㅠ

2021-05-30 16:55 UTC, logic-finder commented
브랜치 정리했습니다. 원래 #925, #946 pr의 커밋들까지 (그리고 #946 머지되면서 conflict난 것 수정한 것까지) 포함하고 있었는데 (제가 깃이 처음이라 브랜치에서 브랜치를 생성해버리는 바람에 그렇게 된 것 같습니다), 체리픽하고 force push해서 원래 이 pr이 가져야 했던 커밋만 남겼습니다.

2021-05-30 16:56 UTC, logic-finder commented on files/ko/learn/javascript/first_steps/variables/index.html
> +<p>당신은 이 문서의 끝에 도달했지만, 가장 중요한 정보들을 기억할 수 있으신가요? 당신은 나아가기 전에 이 정보들을 보유하고 있다는 것을 확인하는 추가적인 테스트들을 찾을 수 있습니다 — 다음을 보세요: <a href="/ko/docs/Learn/JavaScript/First_steps/Test_your_skills:_variables">당신의 기량을
위 문제 해결했습니다.

2021-05-30 19:46 UTC, logic-finder commented on files/ko/learn/javascript/first_steps/variables/index.html
> +<p>당신은 이 문서의 끝에 도달했지만, 가장 중요한 정보들을 기억할 수 있으신가요? 당신은 나아가기 전에 이 정보들을 보유하고 있다는 것을 확인하는 추가적인 테스트들을 찾을 수 있습니다 — 다음을 보세요: <a href="/ko/docs/Learn/JavaScript/First_steps/Test_your_skills:_variables">당신의 기량을
말씀해주신 부분 수정하였습니다 (a804076).

2021-06-10 00:55 UTC, GwangYeol-Im commented on files/ko/learn/javascript/first_steps/variables/index.html
> +<p>당신은 이 문서의 끝에 도달했지만, 가장 중요한 정보들을 기억할 수 있으신가요? 당신은 나아가기 전에 이 정보들을 보유하고 있다는 것을 확인하는 추가적인 테스트들을 찾을 수 있습니다 — 다음을 보세요: <a href="/ko/docs/Learn/JavaScript/First_steps/Test_your_skills:_variables">당신의 기량을
리뷰 반영해 주셔서 감사합니다 :) 답변이 늦은 부분은 죄송해요ㅠ 잘 해결하셨다니 다행입니다!

2021-06-10 00:55 UTC, merged