zh-cn(update): sync transform about the English
mdn/translated-content pull request #9531
Opened 2022-10-26 14:33 UTC by Jack-Zhang-1314

### Description

### Motivation

### Additional details

### Related issues and pull requests

2022-10-26 14:34 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/transformstream/index.md
> +它可以传递给 {{domxref("ReadableStream.pipeThrough()")}} 方法，以便将流数据从一种格式转换成另一种。例如，他可以使用解码（或者编码）视频帧，解压缩数据或者将流从 XML 转换到 JSON。
```suggestion
它可以传递给 {{domxref("ReadableStream.pipeThrough()")}} 方法，以便将流数据从一种格式转换成另一种。例如，它可以用于解码（或者编码）视频帧，解压缩数据或者将流从 XML 转换到 JSON。
```

2022-10-26 15:27 UTC, yin1999 requested changes

2022-10-26 15:27 UTC, yin1999 commented on files/zh-cn/web/api/transformstream/index.md
> +[Streams API](/zh-CN/docs/Web/API/Streams_API) 的 **`TransformStream`** 接口表示[链式管道（pipe chain）](/zh-CN/docs/Web/API/Streams_API/Concepts#链式管道传输)*转换流（transform stream）*概念的具体实现.
请检查PR preview，然后，“链式管道”并不合适，听着像一个名词了，我觉得在中文下还是加上“传输”两字更好，这个咱们之前已经提及过了

2022-10-26 16:39 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/transformstream/index.md
> +[Streams API](/zh-CN/docs/Web/API/Streams_API) 的 **`TransformStream`** 接口表示[链式管道（pipe chain）](/zh-CN/docs/Web/API/Streams_API/Concepts#链式管道传输)*转换流（transform stream）*概念的具体实现.
```suggestion
[Streams API](/zh-CN/docs/Web/API/Streams_API) 的 **`TransformStream`** 接口表示[链式管道（pipe chain）传输](/zh-CN/docs/Web/API/Streams_API/Concepts#链式管道传输)*转换流（transform stream）*概念的具体实现.
```

2022-10-26 16:41 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/transformstream/index.md
> +[Streams API](/zh-CN/docs/Web/API/Streams_API) 的 **`TransformStream`** 接口表示[链式管道（pipe chain）](/zh-CN/docs/Web/API/Streams_API/Concepts#链式管道传输)*转换流（transform stream）*概念的具体实现.
嗯，但是读起来有点深奥🤔

2022-10-26 23:52 UTC, yin1999 commented on files/zh-cn/web/api/transformstream/index.md
> +[Streams API](/zh-CN/docs/Web/API/Streams_API) 的 **`TransformStream`** 接口表示[链式管道（pipe chain）](/zh-CN/docs/Web/API/Streams_API/Concepts#链式管道传输)*转换流（transform stream）*概念的具体实现.
pipe 是一个动词，表示 “管道传输”，你得把这个词提到前面去，然后还有个问题你没改：斜体没有被渲染，对中文的词加斜体就行了

![image](https://user-images.githubusercontent.com/15844309/198159916-75ebf985-6a43-421b-830c-52aed4e9c722.png)

2022-10-27 02:42 UTC, Jack-Zhang-1314 commented on files/zh-cn/web/api/transformstream/index.md
> +[Streams API](/zh-CN/docs/Web/API/Streams_API) 的 **`TransformStream`** 接口表示[链式管道（pipe chain）](/zh-CN/docs/Web/API/Streams_API/Concepts#链式管道传输)*转换流（transform stream）*概念的具体实现.
改过之后你看一下，**链式管道传输** 读起来稍微舒服一点🤔

2022-10-27 05:42 UTC, yin1999 approved these changes

2022-10-27 05:46 UTC, merged