docs: update input/number
mdn/translated-content pull request #9579
Opened 2022-10-29 07:25 UTC by jasonren0403

### Description

get rid of LiveSampleError and outdated content

2022-10-29 07:37 UTC, jasonren0403 commented on files/zh-cn/web/html/element/input/number/index.md
> +允许值范围内的最大值。如果输入到元素中的 {{htmlattrxref("value", "input")}} 超过此值，则元素将无法通过[约束验证](/zh-CN/docs/Web/Guide/HTML/HTML5/Constraint_validation)。如果 `max` 属性的值不是数字，则元素没有最大值。
```suggestion
允许值范围内的最大值。如果输入到元素中的 {{htmlattrxref("value", "input")}} 超过此值，则元素将无法通过[约束验证](/zh-CN/docs/Web/Guide/HTML/Constraint_validation)。如果 `max` 属性的值不是数字，则元素没有最大值。
```

2022-10-29 07:37 UTC, jasonren0403 commented on files/zh-cn/web/html/element/input/number/index.md
> +允许值范围内的最小值。如果元素的 {{htmlattrxref("value", "input")}} 小于此值，则该元素将无法通过 [约束验证](/zh-CN/docs/Web/Guide/HTML/HTML5/Constraint_validation)。如果为 `min` 指定的值不是有效数字，则输入没有最小值。
```suggestion
允许值范围内的最小值。如果元素的 {{htmlattrxref("value", "input")}} 小于此值，则该元素将无法通过 [约束验证](/zh-CN/docs/Web/Guide/HTML/Constraint_validation)。如果为 `min` 指定的值不是有效数字，则输入没有最小值。
```

2022-10-29 07:39 UTC, jasonren0403 commented on files/zh-cn/web/html/element/input/number/index.md
> +`<input type="number">` 元素的隐含 [role](/zh-CN/docs/Web/Accessibility/ARIA/Roles) 是 [`spinbutton`](/zh-CN/docs/Web/Accessibility/ARIA/Roles/spinbutton_role) 。如果 spinbutton 对你的表单控件来说不是一个重要的功能，那就*不要*使用 `t
```suggestion
`<input type="number">` 元素的隐含 [role](/zh-CN/docs/Web/Accessibility/ARIA/Roles) 是 [`spinbutton`](/zh-CN/docs/Web/Accessibility/ARIA/Roles/spinbutton_role) 。如果 spinbutton 对你的表单控件来说不是一个重要的功能，那就*不要*使用 `type="number"`；此时，请使用带有 [`pattern`](/zh-CN/docs/Web/HTML/Attributes/pattern) 属性的 [`inputmode="numeric"`](/zh-CN/docs/Web/HTML/Global_attributes/inputmode)，将字符限制在数字和相关字符。如果坚持使用 `<input type="number">`，用户在试图做其他事情时，有可能意外地增加一个数字。此外，如果用户试图输入不是数字的东西，也没有明确的反馈说明他们做错了什么。
```

2022-10-29 07:40 UTC, jasonren0403 commented on files/zh-cn/web/html/element/input/number/index.md
> +- [HTML 表单指南](/zh-CN/docs/Learn/HTML/Forms)
```suggestion
- [HTML 表单指南](/zh-CN/docs/Learn/Forms)
```

2022-10-29 12:24 UTC, yin1999 requested changes

2022-10-29 12:24 UTC, yin1999 commented on files/zh-cn/web/html/element/input/number/index.md
> +**`"number"`** 类型的 {{HTMLElement("input")}} 元素用于让用户输入一个数字，其包括内置验证以拒绝非数字输入。
```suggestion
**`number`** 类型的 {{HTMLElement("input")}} 元素用于让用户输入一个数字，其包括内置验证以拒绝非数字输入。
```

2022-10-29 12:24 UTC, yin1999 commented on files/zh-cn/web/html/element/input/number/index.md
> +不支持 `number` 类型的浏览器会回退为标准的 `text` 输入框。
调整顺序

2022-10-29 12:24 UTC, yin1999 commented on files/zh-cn/web/html/element/input/number/index.md
> +   <td>表示一个数字的 {{jsxref("Number")}} ，或为空</td>
```suggestion
   <td>表示一个数字的 {{jsxref("Number")}}，或为空</td>
```

2022-10-29 12:24 UTC, yin1999 commented on files/zh-cn/web/html/element/input/number/index.md
> +允许值范围内的最小值。如果元素的 {{htmlattrxref("value", "input")}} 小于此值，则该元素将无法通过 [约束验证](/zh-CN/docs/Web/Guide/HTML/Constraint_validation)。如果为 `min` 指定的值不是有效数字，则输入没有最小值。
```suggestion
允许值范围内的最小值。如果元素的 {{htmlattrxref("value", "input")}} 小于此值，则该元素将无法通过[约束验证](/zh-CN/docs/Web/Guide/HTML/Constraint_validation)。如果为 `min` 指定的值不是有效数字，则输入没有最小值。
```

2022-10-29 12:24 UTC, yin1999 commented on files/zh-cn/web/html/element/input/number/index.md
> +> **Note:** 请尽可能避免使用 `placeholder` 属性，它在语义上没有其他解释表单的方式有用，并且可能会导致额外的问题。参见 {{SectiononPage("/zh-CN/docs/Web/HTML/Element/input", "标签与占位符")}}以获取更多信息。
```suggestion
> **备注：** 请尽可能避免使用 `placeholder` 属性，它在语义上没有其他解释表单的方式有用，并且可能会导致额外的问题。参见 {{SectiononPage("/zh-CN/docs/Web/HTML/Element/input", "标签与占位符")}}以获取更多信息。
```

2022-10-29 12:24 UTC, yin1999 commented on files/zh-cn/web/html/element/input/number/index.md
> +如果控件的内容具有方向（({{Glossary("LTR")}} 或 {{Glossary("RTL")}}），但需要以相反的方向显示占位符，则可以使用 Unicode 双向算法来格式化字符，从而覆盖原有占位符的方向；请参见[如何针对 bidi 文字使用 Unicode 控制符](https://www.w3.org/International/questions/qa-bidi-unicode
```suggestion
如果控件的内容具有方向（{{Glossary("LTR")}} 或 {{Glossary("RTL")}}），但需要以相反的方向显示占位符，则可以使用 Unicode 双向算法来格式化字符，从而覆盖原有占位符的方向；请参见[如何针对双向文本使用 Unicode 控制符](https://www.w3.org/International/questions/qa-bidi-unicode-controls)获取更多信息。
```

2022-10-29 12:24 UTC, yin1999 commented on files/zh-cn/web/html/element/input/number/index.md
> +> **Note:** 当用户输入的数据不符合步进配置时，{{Glossary("user agent","用户代理")}}可能会四舍五入到最近的有效值，当有两个同样接近的选项时，更倾向于正方向的数字。
```suggestion
> **备注：** 当用户输入的数据不符合步进配置时，{{Glossary("user agent","用户代理")}}可能会四舍五入到最近的有效值，当有两个同样接近的选项时，更倾向于正方向的数字。
```

2022-10-30 03:51 UTC, yin1999 approved these changes

2022-10-30 03:53 UTC, merged