docs: update examples for array
mdn/translated-content pull request #9584
Opened 2022-10-30 06:00 UTC by YangFong

### Description

Update examples.

2022-10-30 10:47 UTC, yin1999 requested changes
https://github.com/mdn/translated-content/actions/runs/3354320230/jobs/5557784000#step:8:39

2022-10-30 13:15 UTC, YangFong commented
不明白，我没有观察到 463 行 59 列存在什么问题。

2022-10-30 13:17 UTC, yin1999 commented on files/zh-cn/web/javascript/reference/global_objects/array/index.md
> +注意，返回的对象引用*相同*元素作为原数组（而不是 {{glossary("deep copy"，"深拷贝")}}）。改变这些元素的内部结构将反映在原始数组和返回对象中。
yari 的行号标记有错误，那条提示只能告诉你，有宏写错了：

```suggestion
注意，返回的对象引用*相同*元素作为原数组（而不是 {{glossary("deep copy", "深拷贝")}}）。改变这些元素的内部结构将反映在原始数组和返回对象中。
```

2022-11-01 01:15 UTC, yin1999 approved these changes

2022-11-01 01:18 UTC, merged

2022-11-01 01:24 UTC, YangFong commented
这次的错误也不算少：

- 宏指令符号错误。
- 两处链接指向错误。
- `Note` 错转为*注释*。
- 英转中后未调整间隙。