Breakout juego en 2D usando Phaser
mdn/translated-content pull request #9640
Opened 2022-11-02 00:18 UTC by marcelozarate

### Description

Translation of /en-US/docs/Games/Tutorials/2D_breakout_game_Phaser to Spanish.

### Motivation

### Additional details

### Related issues and pull requests

Relates to #9638

2022-11-03 17:54 UTC, Graywolf9 requested changes
Hola! Muchas gracias por tu tiempo y colaboración, excelente traducción, te he dejado pequeños comentarios

2022-11-03 17:54 UTC, Graywolf9 commented on files/es/games/tutorials/2d_breakout_game_phaser/index.md
> +title: Breakout juego en 2D usando Phaser
No estoy seguro del nombre del juego en español, pero creo que mientras esta podría ser una buena opción

```suggestion
title: Juego breakout en 2D usando Phaser
```

2022-11-03 17:54 UTC, Graywolf9 commented on files/es/games/tutorials/2d_breakout_game_phaser/index.md
> +14. [Animaciones y tweens](/es/docs/Games/Tutorials/2D_breakout_game_Phaser/Animations_and_tweens)
Buscando un poco vi que "tweens" es abreviación de "between" haciendo alución a los frameworks intermedios

```suggestion
14. [Animaciones y keyframes intermedios](/es/docs/Games/Tutorials/2D_breakout_game_Phaser/Animations_and_tweens)
```

2022-11-03 17:54 UTC, Graywolf9 commented on files/es/games/tutorials/2d_breakout_game_phaser/index.md
>  ---
Veo que el articulo está ya actualizado por lo que sería adecuado agregar el sourceCommit

```suggestion
l10n:
  sourceCommit: e4783c03e39807e0060a2f4df3bf3962d25d8388
---
```

2022-11-10 19:05 UTC, Graywolf9 commented
Hola! @marcelozarate espero te encuentres muy bien, hay algún comentario sobre las observaciones o esta listo para proceder?

2022-11-14 12:26 UTC, marcelozarate commented
@Graywolf9 ¡perfecto! ¡Buen inicio de semana! continuaré con https://developer.mozilla.org/es/docs/games/tutorials/2d_breakout_game_phaser/initialize_the_framework

2022-11-14 16:23 UTC, Graywolf9 approved these changes
Excelente, muchas gracias!

2022-11-14 16:23 UTC, merged