CSS_grid_layout/basic_concept: upgrade and fix fr
mdn/translated-content pull request #9660
Opened 2022-11-03 01:18 UTC by pols12

### Description

Upgrades French localization to include English fixes and improvements from September 2020.

### Motivation

Code samples were bugged because of their accumulation in the same section. I noted other improvements have been done in English source, so I imported them.

### Additional details

Note I have kept `code` syntax inside headings, not applying mdn/content#19336, since I think it’s better for screen-readers, especially in translations (since these terms come from English).

Also, I have been afraid by this gap between original and French l10n.
* Does a tool exist to follow updates to a page and to see outdated translations?
* Is each date update noted, in order to easier check what have changed since last update?
* Do we have a tool to provide a diff for a given file between two dates?

### Related issues and pull requests

2022-11-07 05:40 UTC, cw118 requested changes
Thank you for the PR @pols12 ! Here are some minor comments/suggestions :)

> Does a tool exist to follow updates to a page and to see outdated translations?
Is each date update noted, in order to easier check what have changed since last update?

We are discussing and trying to plan a better way to show how up-to-date localized content is: https://github.com/orgs/mdn/discussions/129

> Do we have a tool to provide a diff for a given file between two dates?

I believe git and/or GitHub are already some great tools for seeing diffs.

2022-11-07 05:40 UTC, cw118 commented on files/fr/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +On peut créer une grille avec des pistes à taille fixes en utilisant une unité comme le pixel. Pour les pistes à taille variable on peut utiliser le pourcentage ou l’unité `fr` créée à cet effet.
```suggestion
On peut créer une grille avec des pistes à taille fixes en utilisant une unité comme le pixel. Pour les pistes à taille variable on peut utiliser le pourcentage ou l'unité `fr` créée à cet effet.
```

Pas d'apostrophe courbe :)

2022-11-07 05:40 UTC, cw118 commented on files/fr/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +### L’unité `fr`
```suggestion
### L'unité `fr`
```

(apostrophe droite ici :))

2022-11-07 05:40 UTC, cw118 commented on files/fr/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +{{ EmbedLiveSample("L’unité_fr", '220', '140') }}
```suggestion
{{ EmbedLiveSample("L'unité_fr", '220', '140') }}
```

2022-11-07 05:40 UTC, cw118 commented on files/fr/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +```html hidden
```suggestion
```html
```

cf. [le fichier en-US](https://github.com/mdn/content/blob/main/files/en-us/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md?plain=1#L196)

2022-11-07 05:40 UTC, cw118 commented on files/fr/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +```html hidden
```suggestion
```html
```

2022-11-07 05:40 UTC, cw118 commented on files/fr/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +Les valeurs écrites en entier utilisées plus haut peuvent être abrégées en une ligne pour les colonnes avec {{cssxref("grid-column")}} et une ligne pour les rangées avec {{cssxref("grid-row")}}. L’ex
```suggestion
Les valeurs écrites en entier utilisées plus haut peuvent être abrégées en une ligne pour les colonnes avec {{cssxref("grid-column")}} et une ligne pour les rangées avec {{cssxref("grid-row")}}. L'exemple suivant donne le même positionnement que le code précédent, mais avec beaucoup moins de CSS. La valeur avant la barre oblique (`/`) représente la ligne de début, celle d'après représente la ligne de fin.
```

2022-11-07 05:40 UTC, cw118 commented on files/fr/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +Vous pouvez omettre la valeur de la ligne de fin si la zone ne recouvre qu’une piste.
```suggestion
Vous pouvez omettre la valeur de la ligne de fin si la zone ne recouvre qu'une piste.
```

2022-11-07 05:40 UTC, cw118 commented on files/fr/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +> Les navigateurs prennent dorénavant tous en charge les valeurs sans ce préfixe, mais les versions préfixées continuent d’être prises en charge sous forme d’alias.
```suggestion
> Les navigateurs prennent dorénavant tous en charge les valeurs sans ce préfixe, mais les versions préfixées continuent d'être prises en charge sous forme d'alias.
```

2022-11-07 05:40 UTC, cw118 commented on files/fr/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +![Nested grid in flow](grid3.jpg)
```suggestion
[Grille imbriquée dans le flux](1_nested_grids_in_flow.png)
```

Ici on veut afficher la même image que celle sur la page anglaise, donc il faut utiliser le même nom de fichier :)

2022-11-07 05:40 UTC, cw118 commented on files/fr/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +En définissant la propriété `display:grid` sur l'élément `box1`, il devient lui-même une grille et ses enfants se positionnent sur cette grille.
```suggestion
En définissant la propriété `display: grid` sur l'élément `box1`, il devient lui-même une grille et ses enfants se positionnent sur cette grille.
```

2022-11-07 05:40 UTC, cw118 commented on files/fr/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +> **Note :** Cette fonctionnalité apparait dans Firefox 71, le seul navigateur pour le moment à la prendre en charge.
```suggestion
> **Note :** Cette fonctionnalité apparaît dans Firefox 71, le seul navigateur pour le moment à la prendre en charge.
```

2022-11-07 05:40 UTC, cw118 commented on files/fr/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +Selon la version actuelle de la spécifiction, il faudrait modifier l'exemple de grille imbriquée précédent et remplacer `grid-template-columns: repeat(3, 1fr)` en `grid-template-columns: subgrid`. La
```suggestion
Selon la version actuelle de la spécification, il faudrait modifier l'exemple de grille imbriquée précédent et remplacer `grid-template-columns: repeat(3, 1fr)` en `grid-template-columns: subgrid`. La grille imbriquée utilisera alors la grille parente pour inscrire ses éléments dans le document.
```

J'en profite pour corriger une petite coquille :)

2022-11-07 05:40 UTC, cw118 commented on files/fr/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +Plusieurs éléments peuvent être placés dans la même cellule. Dans ce cas, il faut utiliser la propriété {{cssxref("z-index")}} pour contrôler l’ordre dans lequel les éléments se chevauchent.
```suggestion
Plusieurs éléments peuvent être placés dans la même cellule. Dans ce cas, il faut utiliser la propriété {{cssxref("z-index")}} pour contrôler l'ordre dans lequel les éléments se chevauchent.
```

2022-11-07 05:40 UTC, cw118 commented on files/fr/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +L’élément `box2` chevauche maintenant `box1` ; il s’affiche par-dessus parce qu’il arrive après dans le code source.
```suggestion
L'élément `box2` chevauche maintenant `box1`&nbsp;; il s'affiche par-dessus parce qu'il arrive après dans le code source.
```

2022-11-07 20:05 UTC, pols12 commented on files/fr/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +On peut créer une grille avec des pistes à taille fixes en utilisant une unité comme le pixel. Pour les pistes à taille variable on peut utiliser le pourcentage ou l’unité `fr` créée à cet effet.
OK. Existe-t-il un précis des conventions typographiques pour la MDN en français ?

2022-11-07 20:08 UTC, pols12 commented on files/fr/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +```html hidden
Oui, j’aurais plutôt dû suggérer cela pour l’original en anglais.

2022-11-07 20:11 UTC, pols12 commented on files/fr/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +> **Note :** Cette fonctionnalité apparait dans Firefox 71, le seul navigateur pour le moment à la prendre en charge.
J’ai l’habitude d’utiliser les rectifications orthographiques de 1990, désolé.

2022-11-07 20:20 UTC, pols12 commented on files/fr/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +![Nested grid in flow](grid3.jpg)
En effet, je me suis mélangé les pinceaux en regardant les commits un par un. Désolé.

2022-11-08 15:11 UTC, cw118 approved these changes
Merci beaucoup et félicitations pour cette première contribution @pols12 ! Fusionnons tout ça :)

Voici le [guide stylistique de mozfr](https://github.com/mozfr/besogne/wiki/Guide-stylistique-pour-la-traduction), vous y trouverez la majorité des conventions utilisées sur MDN pour la locale française.

2022-11-08 15:11 UTC, merged