用語集 - IIFE (即時実行関数式) の更新
mdn/translated-content pull request #9695
Opened 2022-11-04 09:19 UTC by eetann

### Description

用語集 IIFE (即時実行関数式) の英語版が更新されていたため、日本語版も更新しました。

2022-11-08 14:03 UTC, mfuji09 requested changes
英字と日本語の間に空白が入っていない箇所がいくつかありますので、修正をお願いします。
（変更提案をした部分以外にもあるかもしれません。）

2022-11-08 14:03 UTC, mfuji09 commented on files/ja/glossary/iife/index.md
> +IIFE という名前は[Ben Almanのブログ](https://web.archive.org/web/20171201033208/http://benalman.com/news/2010/11/immediately-invoked-function-expression/#iife)で付けられました。
英字の周囲には半角空白を空けてください。
```suggestion
IIFE という名前は [Ben Alman のブログ](https://web.archive.org/web/20171201033208/http://benalman.com/news/2010/11/immediately-invoked-function-expression/#iife)で付けられました。
```

2022-11-08 23:54 UTC, eetann commented
@mfuji09 修正しました。再度確認お願いいたします！

2022-11-09 17:11 UTC, mfuji09 approved these changes
OKです。

2022-11-09 17:11 UTC, merged