sourcemap 번역 신규 추가
mdn/translated-content pull request #9717
Opened 2022-11-05 13:35 UTC by wisedog

HTTP header sourcemap을 신규로 번역하였습니다. 
번역 도중 빠져있는 Glossary/Forbidden_header_name 도 추가했습니다.

2022-11-05 14:47 UTC, hochan222 requested changes
@wisedog 님 안녕하세요.

하기 리뷰사항 반영 후 멘션주시면 바로 머지 진행하겠습니다.

감사합니다. 좋은 하루 보내세요 :)

2022-11-05 14:47 UTC, hochan222 commented on files/ko/web/http/headers/sourcemap/index.md
> +browser-compat: http.headers.SourceMap
```suggestion
```

https://github.com/mdn/translated-content/issues/7412 이슈로 `title`, `slug`, `original_slug`, `l10n.*` 를 제외한 메타 태그는 삭제 부탁드립니다 :)

- [메타 데이터 번역 가이드](https://github.com/mdn/translated-content/blob/main/docs/ko/translation-guide.md#%EB%A9%94%ED%83%80%EB%8D%B0%EC%9D%B4%ED%84%B0)

2022-11-05 14:47 UTC, hochan222 commented on files/ko/glossary/forbidden_header_name/index.md
> +  - forbidden
```suggestion
```

2022-11-06 01:13 UTC, wisedog commented on files/ko/web/http/headers/sourcemap/index.md
> +browser-compat: http.headers.SourceMap
오호.. 태그가 이제 삭제되는군요. 알겠습니다!

2022-11-06 01:16 UTC, wisedog commented on files/ko/glossary/forbidden_header_name/index.md
> +  - forbidden
@hochan222  반영했습니다.

2022-11-06 01:35 UTC, hochan222 approved these changes
LGTM. 좋은 하루 보내세요 :)

2022-11-06 01:35 UTC, merged