Translated html <article> to Spanish #7299
mdn/translated-content pull request #9725
Opened 2022-11-05 17:06 UTC by Alvaro-L-C

Copied the french page and translated it into Spanish from the English one. 
It has the same content as the french one,  some changes to what was previously on the page to make it easier to understand (imo).
Let me know if there is anything I should change.

2022-11-07 17:39 UTC, Graywolf9 requested changes
Thank you so much for your time and help! 

I let you some comments, let me know any doubts or you can commit them if ok

2022-11-07 17:39 UTC, Graywolf9 commented on files/es/web/html/element/article/index.md
> +title: '<article>'
To have same structure as `en-US`

```suggestion
title: '<article>' El elemento con contendio del artículo
```

2022-11-07 17:39 UTC, Graywolf9 commented on files/es/web/html/element/article/index.md
> +  - Web
Tags are not needed since are taken from `en-US`

```suggestion
```

2022-11-07 17:39 UTC, Graywolf9 commented on files/es/web/html/element/article/index.md
> +        >. Un elemento <code>&#x3C;article></code> no puede ser descendente de
For a better l10n

```suggestion
        >. Un elemento <code>&#x3C;article></code> no puede ser hijo de
```

2022-11-07 17:39 UTC, Graywolf9 commented on files/es/web/html/element/article/index.md
> +Este elemento solo incluye los [atributos globales](/es/docs/Web/HTML/Global_attributes), comunes para todos los elementos.
To have the same structure as `en-US`

```suggestion
Este elemento solo incluye los [atributos globales](/es/docs/Web/HTML/Global_attributes).
```

2022-11-07 17:39 UTC, Graywolf9 commented on files/es/web/html/element/article/index.md
> +- Cada `<article>` independiente debe ser identificado, normalment con un elemento header (de `<h1>` a `<h6>`).
For a better l10n

```suggestion
- Cada `<article>` debe ser identificado, normalmente con un elemento de encabezado (elementos [`<h1>` - `<h6>`](/en-US/docs/Web/HTML/Element/Heading_Elements)) como hijo.
```

2022-11-07 17:39 UTC, Graywolf9 commented on files/es/web/html/element/article/index.md
> +- Cuando un `<article>` está incorporado dentro de otro, representa un artículo cuyo contenido está relacionado con el artículo que lo anida. Por ejemplo, un comentario en una entrada de blog puede s
typo

```suggestion
- Cuando un `<article>` está incorporado dentro de otro, representa un artículo cuyo contenido está relacionado con el artículo que lo anida. Por ejemplo, un comentario en una entrada de blog puede ser un `<article>` dentro de otro` <article>` que representa la propia entrada del blog.
```

2022-11-07 17:39 UTC, Graywolf9 commented on files/es/web/html/element/article/index.md
> +- La fecha y momento de publicación de un elemento `<article>` pueden ser declarados mediante el atributo [`datetime`](/es/docs/Web/HTML/Element/time#attr-datetime) de un elemento [`<time>`](/es/docs
To follow the `en-US` info

```suggestion
- La fecha y momento de publicación de un elemento `<article>` pueden ser declarados mediante el atributo [`datetime`](/es/docs/Web/HTML/Element/time#attr-datetime) de un elemento [`<time>`](/es/docs/Web/HTML/Element/time).
```

2022-11-07 17:39 UTC, Graywolf9 commented on files/es/web/html/element/article/index.md
> +</article>
Missing or extra code, take the code from `en-US`

```suggestion
<article class="film_review">
  <h2>Jurassic Park</h2>
  <section class="main_review">
    <h3>Reseña</h3>
    <p>¡Los dinosaurios estuvieron genial!</p>
  </section>
  <section class="user_reviews">
    <h3>Reseñas de usuarios</h3>
    <article class="user_review">
      <h4>¡Demasiado aterrador!</h4>
      <p>Demasiado aterradores para mí</p>
      <footer>
        <p>
          Publicado el
          <time datetime="2015-05-16 19:00">16 de mayo</time>
          por Lisa.
        </p>
      </footer>
    </article>
    <article class="user_review">
      <h4>¡Amo a los dinos!</h4>
      <p>Estoy de acuerdo, los dinosaurios son mis favoritos.</p>
      <footer>
        <p>
          Publicado el
          <time datetime="2015-05-17 19:00">17 de mayo</time>
          por Tom.
        </p>
      </footer>
    </article>
  </section>
  <footer>
    <p>
      Publicado el
      <time datetime="2015-05-15 19:00">15 de mayo</time>
      por Staff.
    </p>
  </footer>
</article>
```

2022-11-07 17:39 UTC, Graywolf9 commented on files/es/web/html/element/article/index.md
> +## Ver también
For the `es` conventions

```suggestion
## Compatibilidad con navegadores

{{Compat}}

## Véase también
```

2022-11-07 17:39 UTC, Graywolf9 commented on files/es/web/html/element/article/index.md
> +- [Secciones y estructura de un documento HTML5](/es/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines)
For a better l10n

```suggestion
- [Uso de secciones y esquemas HTML](/es/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines)
```

2022-11-08 13:12 UTC, JuanVqz commented on files/es/web/html/element/article/index.md
> +- Cuando un `<article>` está incorporado dentro de otro, representa un artículo cuyo contenido está relacionado con el artículo que lo anida. Por ejemplo, un comentario en una entrada de blog puede s
creo que era el espacio luego el `

2022-11-08 13:14 UTC, JuanVqz commented
The bot said this pr has merge conflicts but GitHub said "This branch has no conflicts with the base branch", :thinking:

2022-11-08 16:16 UTC, Graywolf9 commented on files/es/web/html/element/article/index.md
> +- Cuando un `<article>` está incorporado dentro de otro, representa un artículo cuyo contenido está relacionado con el artículo que lo anida. Por ejemplo, un comentario en una entrada de blog puede s
La dislexia xD gracias!

2022-11-08 16:45 UTC, Graywolf9 commented on files/es/web/html/element/article/index.md
> +title: '<article>' El elemento con contendio del artículo
Fix error

```suggestion
title: '<article>: El elemento con contendio del artículo'
```

2022-11-08 16:49 UTC, Graywolf9 approved these changes
Thank you so much for your time and atention!

2022-11-08 16:50 UTC, Graywolf9 commented
And yes, @JuanVqz the bot post a comment when needs to be rebased and add a tag, and only remove the tag when is solved

2022-11-08 16:50 UTC, merged