update description translation
mdn/translated-content pull request #977
Opened 2021-05-24 06:34 UTC by hwang1588

『new description translation』

- ko/glossary/bootstrap/index.html
- ko/glossary/breadcrumb/index.html
--------------------------------------------------
『update description translation』

- null

2021-05-24 06:35 UTC, hwang1588 commented
기존 요청드린 pr은 폐기 후 제 로컬에서 수정하여 다시 pr 드립니다. 감사합니다.

2021-05-24 07:08 UTC, hochan222 commented
혹시 이전 PR 링크 알려주실 수 있나요?

2021-05-24 07:15 UTC, hwang1588 commented
> 혹시 이전 PR 링크 알려주실 수 있나요?

#909 입니다.

2021-05-24 07:23 UTC, hochan222 commented
@cos18 동일 pr인것같아서 리뷰어 지정했습니다.

2021-05-27 15:10 UTC, cos18 requested changes
늦게 확인해 죄송합니다.
간단한 맞춤법 오류가 있어 코멘트에 달아놨습니다. 이외 문제는 없어보여, 수정한 커밋 올리시면 바로 Approve하겠습니다. 기여 감사드립니다!

2021-05-27 15:10 UTC, cos18 commented on files/ko/glossary/breadcrumb/index.html
> +<p><span class="seoSummary"><strong>브레드크럼</strong>, 또는 브레드크럼 트레일은 일반적으로 사이트의 header와 기본 컨텐츠 사이에 배치되는 탐색 보조 도구로, 사이트 구조와 관련된 현재 페이지의 계층 구조, 최상위에서부터 현재 페이지 까지를 사용자의 링크 목록 등으로 표시합니다. 현재 페이지 까지 방문한 순서대로
```suggestion
<p><span class="seoSummary"><strong>브레드크럼</strong>, 또는 브레드크럼 트레일은 일반적으로 사이트의 header와 기본 컨텐츠 사이에 배치되는 탐색 보조 도구로, 사이트 구조와 관련된 현재 페이지의 계층 구조, 최상위에서부터 현재 페이지까지를 사용자의 링크 목록 등으로 표시합니다. 현재 페이지까지 방문한 순서대로 보입니다. </span></p>
```

2021-05-27 15:10 UTC, cos18 commented on files/ko/glossary/breadcrumb/index.html
> +<p>브레드크럼 트레일을 통해 사용자는 웹 사이트 내에서 현재 자신의 위치를 알 수 있습니다. 이러한 유형의 탐색이 올바르게 수행되면 사용자는 사이트 내 위치와 이동 경로를 알 수 있습니다. 또한 사용자가 이전 위치로 돌아가는 데 도움이되며 상위 페이지로 이동하는 데 필요한 클릭 수를 줄일 수 있습니다.</p>
```suggestion
<p>브레드크럼 트레일을 통해 사용자는 웹 사이트 내에서 현재 자신의 위치를 알 수 있습니다. 이러한 유형의 탐색이 올바르게 수행되면 사용자는 사이트 내 위치와 이동 경로를 알 수 있습니다. 또한 사용자가 이전 위치로 돌아가는 데 도움이 되며 상위 페이지로 이동하는 데 필요한 클릭 수를 줄일 수 있습니다.</p>
```

2021-05-29 04:39 UTC, cos18 approved these changes
LGTM 👍

2021-05-29 04:53 UTC, merged