BackgroundFetchUpdateUIEventの翻訳
mdn/translated-content pull request #9781
Opened 2022-11-07 17:53 UTC by neko-kawaii-nyan

### Description
下記ページツリーの翻訳
https://developer.mozilla.org/en-US/docs/Web/API/BackgroundFetchUpdateUIEvent

### Related issues and pull requests
https://github.com/mozilla-japan/translation/issues/658

2022-11-08 14:09 UTC, mfuji09 requested changes
「コンストラクター」「ブラウザー」などの表記がガイドラインに沿っていない場所がありました。同じ問題は繰り返して指摘しませんので、全体の修正をお願いします。

2022-11-08 14:09 UTC, mfuji09 commented on files/ja/web/api/backgroundfetchupdateuievent/backgroundfetchupdateuievent/index.md
> +コンストラクター **`BackgroundFetchUpdateUIEvent()`** は新しく {{domxref("BackgroundFetchUpdateUIEvent")}} オブジェクトを生成します。 このコンストラクタは通常、使用されることはありません。なぜなら、これらのオブジェクトはブラウザによって自動で生成され、バックグラウンドのフェッチイベントのコールバックに渡されるから
```suggestion
コンストラクター **`BackgroundFetchUpdateUIEvent()`** は新しく {{domxref("BackgroundFetchUpdateUIEvent")}} オブジェクトを生成します。 このコンストラクターは通常、使用されることはありません。なぜなら、これらのオブジェクトはブラウザーによって自動で生成され、バックグラウンドのフェッチイベントのコールバックに渡されるからです。
```

2022-11-08 15:18 UTC, neko-kawaii-nyan commented
こちら修正しました

2022-11-09 16:59 UTC, mfuji09 approved these changes
OKです。

2022-11-09 16:59 UTC, merged