refactor: update the content of the article closures
mdn/translated-content pull request #9817
Opened 2022-11-09 17:13 UTC by abrahamcalsin

### Description

Update the content of the article _**closures**_, according to the original english version.

### Motivation

### Additional details

### Related issues and pull requests

2022-11-09 19:36 UTC, Graywolf9 requested changes
Muchas gracias por tu tiempo y contribución!

Te he dejado algunas observaciones y además veo que solo has tocado algunas partes del documento y no el documento entero, aunque hay algunas cosas que valdría la pena corregir/homologar:

- Hemos hablado en el [chat](https://chat.mozilla.org/#/room/#mdn-l10n-es:mozilla.org) sobre la mejor traducción de "closure" y hemos concordado en que sería mejor que se utilice `_closure_` ya que no hay aún una traducción adecuada para este termino de programación en español, y en italicas para denotar que no es una palabra nativa
- En los fragmentos de código solo traducimos los literales (cadenas de texto) y comentarios, para alterar lo menos posible la funcionalidad del código.

De nuevo muchas gracias por tu apoyo y son bien recibidos tus comentarios.

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
Este párrafo no existe en inglés

```suggestion
```

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
> +    decrement() {
```suggestion

    decrement() {
```

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
> +- Ámbito encerrado (puede ser un bloque, funcion o módulo)
```suggestion
- Ámbito encapsulado (puede ser un bloque, funcion o módulo)
```

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
> +En el ejemplo anterior, hay una serie de funciones anidadas, las cuales tienen acceso al ámbito de las funciones externas. En este contexto, podemos decir que los closures tienen acceso a _todos_ los
Para hacer notar que no es una palabra nativa

```suggestion
En el ejemplo anterior, hay una serie de funciones anidadas, las cuales tienen acceso al ámbito de las funciones externas. En este contexto, podemos decir que los _closures_ tienen acceso a _todos_ los ámbitos de las funciones externas.
```

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
> +Los closures pueden capturar variables en ámbitos de bloque y de módulo también. Por ejemplo, lo siguiente crea un cierre sobre la variable de ámbito de bloque `y`:
```suggestion
Los _closures_ pueden capturar variables en ámbitos de bloque y de módulo también. Por ejemplo, lo siguiente crea un cierre sobre la variable de ámbito de bloque `y`:
```

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
> +outer()(); // Logs 5 6
```suggestion
outer()(); // Muestra 5 6
```

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
> +Los closures sobre módulos pueden ser aún más interesantes.
```suggestion
Los _closures_ sobre módulos pueden ser aún más interesantes.
```

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
> +// miModulo.js
Ya que es el nombre de un archivo

```suggestion
// myModule.js
```

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
> +En este ejemplo, el módulo exporta un par de funciones getter-setter, que se cierran sobre la variable `x` del módulo. Incluso cuando `x` no es directamente accesible desde otros módulos, se puede le
```suggestion
En este ejemplo, el módulo exporta un par de funciones _getter-setter_, que se cierran sobre la variable `x` del módulo. Incluso cuando `x` no es directamente accesible desde otros módulos, se puede leer y escribir con las funciones.
```

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
> +import { getX, setX } from "./miModulo.js";
Para hacer referencia al archivo como el ejemplo original

```suggestion
import { getX, setX } from "./myModule.js";
```

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
> +Los closures también pueden cerrarse sobre valores importados, que se consideran _enlaces vivos_, porque cuando el valor original cambia, el importado cambia en consecuencia.
```suggestion
Los _closures_ también pueden cerrarse sobre valores importados, que se consideran _enlaces vivos_, porque cuando el valor original cambia, el importado cambia en consecuencia.
```

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
> +// miModulo.js
```suggestion
// myModule.js
```

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
> +// creadorDeClosure.js
```suggestion
// closureCreator.js
```

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
> +import { setX } from "./miModulo.js";
```suggestion
import { getX } from "./closureCreator.js";
import { setX } from "./myModule.js";
```

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
>  ## Creando closures en loops: Un error común
```suggestion
## Creando closures en bucle: Un error común
```

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
> +    { id: 'edad', help: 'Tu edad (debe ser mayor de 16)' },
En este caso `id` hace referencia al atributo `id` de los `input`

```suggestion
    { id: 'email', help: 'Tu dirección de correo electronico' },
    { id: 'email', help: 'Tu nombre completo' },
    { id: 'email', help: 'Tu edad (debe ser mayor de 16)' },
```

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
> +    { id: 'edad', help: 'Tu edad (debe ser mayor de 16)' },
```suggestion
    { id: 'email', help: 'Tu dirección de correo electronico' },
    { id: 'name', help: 'Tu nombre completo' },
    { id: 'age', help: 'Tu edad (debe ser mayor de 16)' },
```

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
> +Otra forma de escribir lo anterior es utilizando closures anónimos:
```suggestion
Otra forma de escribir lo anterior es utilizando _closures_ anónimos:
```

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
> +    { id: 'edad', help: 'Tu edad (debe ser mayor de 16)' },
```suggestion
    { id: 'email', help: 'Tu dirección de correo electronico' },
    { id: 'name', help: 'Tu nombre completo' },
    { id: 'age', help: 'Tu edad (debe ser mayor de 16)' },
```

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
> +    })(); // Inmediatamente el escuchador de eventos adjunta el valor actual del item (conservado hasta la iteración)
De acuerdo a la convención de traducciónes: https://github.com/mdn/translated-content/tree/main/docs/es

```suggestion
    })(); // Inmediatamente el detector de eventos adjunta el valor actual del item (conservado hasta la iteración)
```

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
> +Si no quires usar más closures, puedes optar por usar la palabra clave [`let`](/es/docs/Web/JavaScript/Reference/Statements/let) o [`const`](/es/docs/Web/JavaScript/Reference/Statements/const):
```suggestion
Si no quires usar más _closures_, puedes optar por usar la palabra clave [`let`](/es/docs/Web/JavaScript/Reference/Statements/let) o [`const`](/es/docs/Web/JavaScript/Reference/Statements/const):
```

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
> +    { id: 'edad', help: 'Tu edad (debe ser mayor de 16)' },
```suggestion
    { id: 'email', help: 'Tu dirección de correo electronico' },
    { id: 'name', help: 'Tu nombre completo' },
    { id: 'age', help: 'Tu edad (debe ser mayor de 16)' },
```

2022-11-09 19:36 UTC, Graywolf9 commented on files/es/web/javascript/closures/index.md
> +    { id: 'edad', help: 'Tu edad (debe ser mayor de 16)' },
```suggestion
    { id: 'email', help: 'Tu dirección de correo electronico' },
    { id: 'name', help: 'Tu nombre completo' },
    { id: 'age', help: 'Tu edad (debe ser mayor de 16)' },
```

2022-11-10 04:45 UTC, abrahamcalsin commented
> Muchas gracias por tu tiempo y contribución!
> 
> Te he dejado algunas observaciones y además veo que solo has tocado algunas partes del documento y no el documento entero, aunque hay algunas cosas que valdría la pena corregir/homologar:
> 
> * Hemos hablado en el [chat](https://chat.mozilla.org/#/room/#mdn-l10n-es:mozilla.org) sobre la mejor traducción de "closure" y hemos concordado en que sería mejor que se utilice `_closure_` ya que no hay aún una traducción adecuada para este termino de programación en español, y en italicas para denotar que no es una palabra nativa (excepto en títulos, ahí se omiten las italicas)
> * En los fragmentos de código solo traducimos los literales (cadenas de texto) y comentarios, para alterar lo menos posible la funcionalidad del código.
> 
> De nuevo muchas gracias por tu apoyo y son bien recibidos tus comentarios.

Gracias por las reviews @Graywolf9, tengo un duda acerca del chat, intente registrarme y me da error, aqui adjunto una captura:

![image](https://user-images.githubusercontent.com/77748010/201000960-b7538c4d-6ba7-480e-a013-84580f974304.png)

2022-11-10 17:22 UTC, Graywolf9 approved these changes
Muchas gracias por tu tiempo y atenciones.

Sobre el chat, parece que el problema no es con el chat si no con tu usuario que ha sido desactivado, también puedes intentar en nuestro grupo de telegram https://t.me/+Dr6qKQCAepw4MjFj, ambos están vinculados, por lo que sería lo mismo

2022-11-10 17:22 UTC, merged

2022-11-11 04:01 UTC, abrahamcalsin commented
> Muchas gracias por tu tiempo y atenciones.
> 
> Sobre el chat, parece que el problema no es con el chat si no con tu usuario que ha sido desactivado, también puedes intentar en nuestro grupo de telegram [t.me/+Dr6qKQCAepw4MjFj](https://t.me/+Dr6qKQCAepw4MjFj), ambos están vinculados, por lo que sería lo mismo

Gracias!
Saludos!