[es] Update String.prototype.match()
mdn/translated-content pull request #9826
Opened 2022-11-10 09:46 UTC by mariofdezzz

### Description

Update String.prototype.match() as required in issue.

### Related issues and pull requests

- Relates to  #4135

2022-11-10 19:00 UTC, Graywolf9 requested changes
Muchas gracias por tu tiempo y contribución

Te he dejado algunas observaciones, además de comentar que en el caso de los ejemplos solo traducimos las cadenas de texto y los comentarios para tratar de alterar lo menos posible el código original, si pudieras hacer este ajuste en los bloques de código estaría excelente.

Nuevamente muchas gracias por todo

2022-11-11 10:22 UTC, mariofdezzz commented on files/es/web/javascript/reference/global_objects/string/match/index.md
> +## Compatibilidad en navegadores
Muchas gracias! No había visto esta página

2022-11-11 10:26 UTC, mariofdezzz reviewed
Muchas gracias por el feedback!
Disculpa las molestias, sé que es una pr larga y no conozco todos las normas todavía

2022-11-11 16:32 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/string/match/index.md
> +const cadena3 = 'The contract was declared null and void.';
Hola de nuevo! Muchas gracias por tu tiempo y atenciones, y ntp con gusto estamos para apoyarlos 

Para este bloque de código en específico esta bien, puesto que estamos en el apartado donde no se utilizan RegExp por eso al final es la comparación `match` entre una cadena y `null`.

Sin aún así consideras que el ejemplo se puede mejorar el procedimiento sería hacer esta sugerencia en el repo de `content` (`en-US`) y una vez aprobado actualizarlo aquí, ya que nuestra base es el contenido el inglés y nosotros solo lo localizamos (traducimos)

Artículo en ingles: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match
Fuente en inglés: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/match/index.md?plain=1

De nuevo muchas gracias

2022-11-12 18:20 UTC, mariofdezzz commented on files/es/web/javascript/reference/global_objects/string/match/index.md
> +const cadena3 = 'The contract was declared null and void.';
```js
// 1) Cambio realizado
const cadena3 = 'The contract was declared null and void.';
cadena3.match(null); // devuelve ['null']

// 2) Tu propuesta
const cadena3 = 'El contrato fue declarado nulo y sin efecto.';
cadena3.match(null); // devuelve null 
// No encuentra ninguna ocurrencia
```

Disculpa las molestias pero si me gustaría entenderte al 100%, siento que no está completamente claro.

La propuesta que me comentas sería adaptar el el texto al español, independientemente de que el ejemplo pierda su sentido, ya que el resultado cambia al adaptar el texto al español. Es esto correcto?

Por otra parte, voy a adaptar los bloques de código ya, como me propusiste en tu primer comentario 😁

2022-11-14 17:20 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/string/match/index.md
> +const cadena3 = 'The contract was declared null and void.';
Hola! Ninguna molestia, estamos para ayudar con mucho gusto.

De los ejemplos no traducimos nada de código o nombres de variables, esto precisamente para que el ejemplo no pierda sentido y siga funcionando exactamente igual que en inglés, lo único que traducimos son las cadenas de texto o "literales" y comentarios ya que estas no afectan el funcionamiento.

En el caso de la siguiente línea no esta buscando la palabra "null" ya que no esta entre comillas, esta buscando el valor `null` por lo que el efecto no cambia en lo absoluto.

```
cadena3.match(null); // devuelve null 
```

2022-11-14 18:31 UTC, mariofdezzz commented on files/es/web/javascript/reference/global_objects/string/match/index.md
> +const cadena3 = 'The contract was declared null and void.';
En el ejemplo, el valor `null` dentro de `match()` ***pasa a ser una cadena*** debido a la conversión automática de `new RegExp(null)`. Por esta misma razón considero, personalmente, este ejemplo realmente importante, ya que va en contra de lo que se podría preconcebir. Si se tradujera la cadena, este _edge case_ no sería visible.

Te dejo un ejemplo stackblitz para que lo compruebes por ti mismo:
https://stackblitz.com/edit/js-jdqcmm?file=index.js

2022-11-14 18:54 UTC, Graywolf9 commented on files/es/web/javascript/reference/global_objects/string/match/index.md
> +const cadena3 = 'The contract was declared null and void.';
Ya veo, una disculpa, era yo quien no estaba entendiendo. Para esa cadena en particular se podría poner de la siguiente manera. Así continuamos con la congruencia y reglas de localización y a su vez garantizamos el funcionamiento del ejemplo, muchas gracias por tu explicación

```
const str3 = 'El contrato fue declarado null (nulo) y sin efecto.';
```

2022-11-14 19:08 UTC, mariofdezzz commented on files/es/web/javascript/reference/global_objects/string/match/index.md
> +const cadena3 = 'The contract was declared null and void.';
Genial! Cambio realizado 👍🏼

2022-11-14 19:18 UTC, Graywolf9 approved these changes
Muchas gracias por tu tiempo y atenciones ha sido excelente el proceso y las observaciones de regreso

2022-11-14 19:20 UTC, merged