[ko] Fix problems in '2d breakout game tutorials with pure js series #7~#10'.
mdn/translated-content pull request #987
Opened 2021-05-26 09:18 UTC by logic-finder

### **7편 충돌 감지 (1f969ff)**
● 오타, 공백, 문장, 하이퍼링크 수정
'별돌' -> '벽돌', '어덟' -> '여덟' 등등

● {{PreviousNext}} 주소 수정
전) Games/Tutorials/순수한_자바스크립트를_이용한_2D_벽돌깨기_게임/Build_the_brick_field
후) Games/Tutorials/2D_Breakout_game_pure_JavaScript/Build_the_brick_field

전) Games/Workflows/2D_Breakout_game_pure_JavaScript/Track_the_score_and_win
후) Games/Tutorials/2D_Breakout_game_pure_JavaScript/Track_the_score_and_win

### **8편 점수 추가와 승패 판정 방법 (b677601)**
● 문체, 문장, 하이퍼링크 수정
전) ~이다.
후) ~입니다.

● {{PreviousNext}} 주소 수정

### **9편 마우스로 패들 조종하기 (8100af9)**
● 하이퍼링크, 문장 수정
● {{PreviousNext}} 주소 수정

### **10편 개발 마무리 (784856c)**
● 하이퍼링크, 문장 수정
● {{PreviousNext}} 주소 수정

2021-05-27 15:31 UTC, cos18 requested changes
#948 #974 두 PR의 커밋 내용이 섞여서 PR이 된것 같습니다. 브랜치 정리를 해주셔야 이후 다른 PR과 충돌이 나지 않을 것 같습니다.

2021-05-27 16:21 UTC, logic-finder commented
안녕하세요 커멘트 남겨주셔서 감사합니다. 제가 깃이 처음이라 뭔가 실수를 한 것 같습니다. 어디서부터 잘못된 것인지조차 파악이 안 됩니다... 제가 지금까지 올린 pr이 총 5개인데 (#925, #946, #948, #974, #987) 이중에서 #946만 merged되었습니다. #946이 merge되기 전에 reviewer님께서 제안하신 수정사항을 commit했습니다. 그런데 #946이 merge되고 나니까 나머지 pr들에서 conflict가 발생했는데 그 conflict가 뭐냐하면 방금 말한 #946이 merge되기 전에 commit한 수정사항이었습니다. 그래서 일일히 다 conflict resolve를 했습니다. 이번 pr 올릴때도 해당 conflict가 발생했던 것으로 기억나는데 (67e4ecc) 어떻게 해결해야 될 지 모르겠습니다. 그리고 또 아까 2a65600 를 push하려고 하니까 오류가 발생하길래 어떻게 어떻게 하니까(pull) 그제서야 되었습니다. 대단히 실례임은 잘 알고 있습니다만 혹시 무엇이 문제일지 고견을 좀 여쭤봐도 되겠습니까?

2021-05-30 17:25 UTC, logic-finder commented
위 문제 해결했습니다. 브랜치 정리했습니다. 원래 #925, #946, #948, #974 pr의 커밋 그리고 #946 머지되면서 conflict 났던 것 수정한 것까지 포함하고 있었는데 (제가 깃이 처음이라 브랜치에서 브랜치를 생성해서 그렇게 된 것 같습니다) 체리픽하고 force push해서 원래 이 pr이 가져야 했던 커밋만 남겼습니다. 조언해주셔서 대단히 감사합니다.

2021-06-06 12:51 UTC, cos18 requested changes
늦은 리뷰 죄송합니다.
추가로, PR을 올리시기 전에 yari를 실행해보시고 번역한 페이지에 들어가보시길 권장드립니다. 간단한 링크 오류들을 잡아주고, fix flaw를 누르면 바로 수정해줍니다.

<img width="1543" alt="Screen Shot 2021-06-06 at 9 50 15 PM" src="https://user-images.githubusercontent.com/33975709/120924962-4c18d780-c711-11eb-9aa5-1c5fa853f05c.png">

2021-06-06 12:51 UTC, cos18 commented on files/ko/games/tutorials/2d_breakout_game_pure_javascript/collision_detection/index.html
> +<p>이 학습은 <a href="ko/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript">Gamedev Canvas tutorial</a>의 일곱 번째 단계입니다. <a href="https://github.com/end3r/Gamedev-Canvas-workshop/blob/gh-pages/lesson07.
```suggestion
<p>이 학습은 <a href="/ko/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript">Gamedev Canvas tutorial</a>의 일곱 번째 단계입니다. <a href="https://github.com/end3r/Gamedev-Canvas-workshop/blob/gh-pages/lesson07.html">Gamedev-Canvas-workshop/lesson7.html</a>에서 이번 학습에서 완성된 코드를 확인할 수 있습니다.</p>
```

링크가 잘못되어있습니다.

2021-06-06 12:51 UTC, cos18 commented on files/ko/games/tutorials/2d_breakout_game_pure_javascript/collision_detection/index.html
> +<p>우리는 충분히 여기까지 왔습니다! 이제 여덟 번째 장에서는 <a href="https://developer.mozilla.org/ko/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Track_the_score_and_win">점수 추가와 승패 판정 방법</a>을 알아 볼 것입니다.</p>
```suggestion
<p>우리는 충분히 여기까지 왔습니다! 이제 여덟 번째 장에서는 <a href="/ko/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Track_the_score_and_win">점수 추가와 승패 판정 방법</a>을 알아 볼 것입니다.</p>
```

2021-06-06 12:51 UTC, cos18 commented on files/ko/games/tutorials/2d_breakout_game_pure_javascript/track_the_score_and_win/index.html
> +<p>이번 단계는  <a href="https://developer.mozilla.org/ko/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript">Gamedev Canvas tutorial</a>의 8번째 단계입니다. <a href="https://github.com/end3r/Gamedev-Canvas-wo
```suggestion
<p>이번 단계는  <a href="/ko/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript">Gamedev Canvas tutorial</a>의 8번째 단계입니다. <a href="https://github.com/end3r/Gamedev-Canvas-workshop/blob/gh-pages/lesson08.html">Gamedev-Canvas-workshop/lesson8.html</a>에서 이번 단계의 소스 코드를 확인할 수 있습니다.</p>
```

2021-06-06 12:51 UTC, cos18 commented on files/ko/games/tutorials/2d_breakout_game_pure_javascript/track_the_score_and_win/index.html
> +<p>게임은 현재 꽤 멋지게 보입니다. 다음 단계에서는, <a href="https://developer.mozilla.org/ko/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Mouse_controls">Mouse controls (마우스로 패들 조종하는 방법)</a>을 통해서 게임을 즐길 수 있습니다
```suggestion
<p>게임은 현재 꽤 멋지게 보입니다. 다음 단계에서는, <a href="/ko/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Mouse_controls">Mouse controls (마우스로 패들 조종하는 방법)</a>을 통해서 게임을 즐길 수 있습니다.</p>
```

2021-06-06 12:51 UTC, cos18 commented on files/ko/games/tutorials/2d_breakout_game_pure_javascript/track_the_score_and_win/index.html
> +title: "점수 추가와 승패\_판정\_방법"
```suggestion
title: 점수 추가와 승패 판정 방법
```
불필요한 역슬래시가 있습니다.

2021-06-06 12:51 UTC, cos18 commented on files/ko/games/tutorials/2d_breakout_game_pure_javascript/mouse_controls/index.html
> +<p>이 레슨은 <a href="https://developer.mozilla.org/ko/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript">Gamedev Canvas tutorial</a>의 10개 중 <strong>9번째</strong> 단계입니다. 당신은 <a href="https://github.co
```suggestion
<p>이 레슨은 <a href="/ko/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript">Gamedev Canvas tutorial</a>의 10개 중 <strong>9번째</strong> 단계입니다. 당신은 <a href="https://github.com/end3r/Gamedev-Canvas-workshop/blob/gh-pages/lesson09.html">Gamedev-Canvas-workshop/lesson9.html</a>에서 완성된 소스코드를 찾을 수 있습니다.</p>
```

2021-06-06 12:51 UTC, cos18 commented on files/ko/games/tutorials/2d_breakout_game_pure_javascript/mouse_controls/index.html
> +<p>이 함수에서 우리는 첫번째로 <code>relativeX</code> 값을 계산하는데, 이는 뷰포트 (<code>e.clientX</code>) 안에 있는 가로 마우스 위치 빼기 캔버스의 좌측 끝과 뷰포트 (<code>canvas.offsetLeft</code>) 의 좌측 끝 사이의 거리와 같습니다. 효과적으로 이것은 캔버스의 좌측 끝과 마우스 포인
```suggestion
<p>이 함수에서 우리는 첫번째로 <code>relativeX</code> 값을 계산하는데, 이는 뷰포트 (<code>e.clientX</code>) 안에 있는 가로 마우스 위치에 캔버스의 좌측 끝과 뷰포트 (<code>canvas.offsetLeft</code>) 의 좌측 끝 사이의 거리를 뺀 값과 같습니다. 이는 캔버스의 좌측 끝과 마우스 포인터 사이의 거리와 같습니다. 상대적인 X 포인터 위치가 0보다 크고 캔버스 폭보다 적으면 포인터가 경계 내에 있게 되고, <code>paddleX</code>의 위치(패들 왼쪽 가장자리에 배치되어 있습니다)는 패들 폭의 반을 뺀 <code>relativeX</code>의 값으로 설정되므로 이동은 패들의 중앙과 관련될 것입니다.</p>
```

몇몇 문장들이 이해하기 어렵게 해석되었습니다. 직역보단 좀 더 이해하기 쉽게 수정해보았습니다.

2021-06-06 12:51 UTC, cos18 commented on files/ko/games/tutorials/2d_breakout_game_pure_javascript/mouse_controls/index.html
> +<p>이제 우리는 완전한 게임을 할 수 있게 되었습니다. 우리는 몇 가지 작은 코드만으로 이 레슨을 마치게 될 것 입니다! — <a href="https://developer.mozilla.org/ko/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Finishing_up">마지막</a>.</p>
```suggestion
<p>이제 우리는 완전한 게임을 할 수 있게 되었습니다. 우리는 몇 가지 작은 코드만으로 이 레슨을 마치게 될 것 입니다! — <a href="/ko/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Finishing_up">마지막</a>.</p>
```

2021-06-06 12:51 UTC, cos18 commented on files/ko/games/tutorials/2d_breakout_game_pure_javascript/finishing_up/index.html
> +<p><a href="https://developer.mozilla.org/ko/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript">Gamedev Canvas tutorial</a>의 <strong>10개의 레슨 중 마지막 단계</strong>입니다. 이 수업을 마친 후 비교하여 살펴볼 소스코드는 <a hre
```suggestion
<p><a href="/ko/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript">Gamedev Canvas tutorial</a>의 <strong>10개의 레슨 중 마지막 단계</strong>입니다. 이 수업을 마친 후 비교하여 살펴볼 소스코드는 <a href="https://github.com/end3r/Gamedev-Canvas-workshop/blob/gh-pages/lesson10.html">Gamedev-Canvas-workshop/lesson10.html</a>에서 찾아볼 수 있습니다.</p>
```

2021-06-06 12:51 UTC, cos18 commented on files/ko/games/tutorials/2d_breakout_game_pure_javascript/finishing_up/index.html
> +<p>남은 생명 수를 표시하는 방법은 점수 카운터가 그려지는 것과 같은 형태입니다. <code>drawScore()</code>함수 아래에 다음 기능을 추가하십시오.</p>
```suggestion
<p>남은 생명 수를 표시하는 방법은 점수 카운터가 그려지는 것과 같은 형태입니다. <code>drawScore()</code>함수 아래에 다음 기능을 추가하세요.</p>
```

~해요체를 권장합니다.

2021-06-06 12:51 UTC, cos18 commented on files/ko/games/tutorials/2d_breakout_game_pure_javascript/finishing_up/index.html
> +<p>이것으로 대체하십시오.</p>
```suggestion
<p>이렇게 대체하세요.</p>
```

2021-06-06 12:51 UTC, cos18 commented on files/ko/games/tutorials/2d_breakout_game_pure_javascript/finishing_up/index.html
> +<p>축하합니다! 당신은 모든 수업을 완수하였습니다! 이쯤 되면 이제 캔버스의 조작 기초와 간단한 2D 게임 구현 방법을 알게 되었을 것입니다. 이제 몇몇 프레임워크를 배우고 게임 개발을 계속하기에 좋은 시간입니다. 이 시리즈의 <a href="https://developer.mozilla.org/ko/docs/Games/Tutorials/2D_break
```suggestion
<p>축하합니다! 당신은 모든 수업을 완수하였습니다! 이쯤 되면 이제 캔버스의 조작 기초와 간단한 2D 게임 구현 방법을 알게 되었을 것입니다. 이제 몇몇 프레임워크를 배우고 게임 개발을 계속하기에 좋은 시간입니다. 이 시리즈의 <a href="/ko/docs/Games/Tutorials/2D_breakout_game_Phaser">2D breakout game using Phaser</a> 또는 <a href="/ko/docs/Games/Tutorials/HTML5_Gamedev_Phaser_Device_Orientation">Cyber Orb built in Phaser</a> 튜토리얼을 확인해 볼 수 있습니다. <a href="/ko/docs/Games">Games section on MDN</a>의 섹션에서 더 많은 지식과 영감을 얻어보세요.</p>
```

2021-06-06 12:51 UTC, cos18 commented on files/ko/games/tutorials/2d_breakout_game_pure_javascript/mouse_controls/index.html
> +<p>마우스 움직임을 감지하는 것은 키 누름을 감지하는 것보다 더욱 쉽습니다. 우리에게 필요한 모든 것은 {{event("mousemove")}} 이벤트에 대한 리스너입니다. 이 <code>keyup event</code> 바로 아래에 이 행을 추가하십시오.</p>
```suggestion
<p>마우스 움직임을 감지하는 것은 키 누름을 감지하는 것보다 더욱 쉽습니다. 우리에게 필요한 모든 것은 {{event("mousemove")}} 이벤트에 대한 리스너입니다. 이 <code>keyup event</code> 바로 아래에 이 행을 추가해보세요.</p>
```

2021-06-06 12:51 UTC, cos18 commented on files/ko/games/tutorials/2d_breakout_game_pure_javascript/mouse_controls/index.html
> +<p>포인터 좌표에 따라 패들 위치를 업데이트할 수 있습니다. 다음의 핸들러 함수가 정확히 이것을 할 것입니다. 추가한 이전 줄 아래에 다음 함수를 추가하십시오.</p>
```suggestion
<p>포인터 좌표에 따라 패들 위치를 업데이트할 수 있습니다. 다음의 핸들러 함수가 정확히 이것을 할 것입니다. 추가한 이전 줄 아래에 다음 함수를 추가해보세요.</p>
```

2021-06-06 13:53 UTC, logic-finder commented on files/ko/games/tutorials/2d_breakout_game_pure_javascript/track_the_score_and_win/index.html
> +title: "점수 추가와 승패\_판정\_방법"
이거 고쳤었는데 체리픽할때 실수로 이 커밋을 빼먹은 모양이네요 ㅠ 수정해주셔서 감사합니다.

2021-06-06 13:58 UTC, logic-finder commented
부족한 pr 죄송합니다 ㅠㅠ 정성들여 수정해주셔서 대단히 감사드립니다. 수정사항 모두 반영했습니다.

2021-06-07 12:36 UTC, cos18 approved these changes
LGTM

2021-06-07 12:37 UTC, cos18 commented
@logic-finder 추가로 리뷰 수정이 완료되었으면 review를 re-request해주셔야 reviewer가 다 변경되었는지 확인할 수 있습니다. 다음번에는 꼭 해주세요!

2021-06-07 12:38 UTC, merged

2021-06-07 13:31 UTC, logic-finder commented
오 그렇군요ㅠ 소중한 조언 감사합니다 좋은 하루 보내세요