Update index.md pt-br translation version
mdn/translated-content pull request #9931
Opened 2022-11-16 00:29 UTC by danvitoriano

### Description

Update index.md pt-br translation version

### Motivation

Add missing translations to portuguese (pt-br) language.

### Additional details

### Related issues and pull requests

2022-11-17 11:37 UTC, josielrocha requested changes
Muito obrigado pela sua ajuda @danvitoriano!

Deixei abaixo algumas sugestões referentes a forma como escrevemos os links.

Poderia verificar por favor?

2022-11-17 11:37 UTC, josielrocha commented on files/pt-br/web/javascript/javascript_technologies_overview/index.md
> +- As funções [setTimeout](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout) e [setInterval](https://developer.mozilla.org/pt-BR/docs/Web/API/setInterval) foram inicialmente especificadas n
Os links internos devem, preferencialmente, serem escritos:

- Usando caminhos relativos, isso ajuda em eventuais mudanças de domínio
- Podemos escrever todos os links prefixados com `/pt-BR`, caso a página de destino não exista o build se encarrega de renderizar o fallback em `/en-US`

```suggestion
- As funções [setTimeout](/pt-BR/docs/Web/API/setTimeout) e [setInterval](/pt-BR/docs/Web/API/setInterval) foram inicialmente especificadas na interface [Window](http://www.whatwg.org/html/#window) no Padrão HTML.
```

2022-11-17 11:37 UTC, josielrocha commented on files/pt-br/web/javascript/javascript_technologies_overview/index.md
> +Ambientes sem navegador (como Node.js) geralmente não têm APIs DOM — porque não interagem com um documento — mas ainda assim implementam muitas APIs da Web, como [fetch()](https://developer.mozilla.o
Removendo o domínio dos links e ajustando o idioma

```suggestion
- A [interface WebAssembly](https://webassembly.github.io/spec/js-api) fornece utilitários para comunicação entre código JavaScript e módulos [WebAssembly](/pt-BR/docs/WebAssembly).

Ambientes sem navegador (como Node.js) geralmente não têm APIs DOM — porque não interagem com um documento — mas ainda assim implementam muitas APIs da Web, como [fetch()](/pt-BR/docs/Web/API/fetch) e [setTimeout()](/pt-BR/docs/Web/API/setTimeout).
```

2022-11-19 16:07 UTC, merged

2022-11-23 18:16 UTC, danvitoriano commented on files/pt-br/web/javascript/javascript_technologies_overview/index.md
> +- As funções [setTimeout](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout) e [setInterval](https://developer.mozilla.org/pt-BR/docs/Web/API/setInterval) foram inicialmente especificadas n
obrigado pelas dicas @josielrocha! nas próximas farei desta forma!