Improve ja translation of Web Storage API documents
mdn/translated-content pull request #9978
Opened 2022-11-18 14:16 UTC by mikecat

### Description

* 仕様書のリンク切れを修正
* リンクのテキストをリンク先のタイトルに合わせる
* 訳を自然に思えるように調整
* 英語版のコンテンツの取り込み
* マークアップの調整

### Motivation

違和感を減らす。

### Additional details

### Related issues and pull requests

2022-11-21 15:54 UTC, mfuji09 requested changes
指摘箇所の修正をお願いします。
なお、同じ指摘は繰り返しませんので、他の部分についても修正をお願いします。

2022-11-21 15:54 UTC, mfuji09 commented on files/ja/web/api/storageevent/index.md
> +  - : 値を変化させたドキュメントのURL。
日本語と英文字の間に空白を入れてください。

2022-11-21 19:19 UTC, mikecat commented
@mfuji09 修正しました。

2022-11-22 02:56 UTC, mfuji09 requested changes
追加で申し訳ありませんが、指摘分の修正をお願いします。
（プルリクエストの単位が大きすぎるので、一度にすべてを見ることが難しいことをご了解ください。）

2022-11-22 12:30 UTC, mikecat commented
@mfuji09 修正しました。

2022-11-22 14:23 UTC, mfuji09 approved these changes
OKです。

2022-11-22 14:23 UTC, merged