Improve ja translation of Window.console
mdn/translated-content pull request #9982
Opened 2022-11-18 16:41 UTC by mikecat

### Description

英語になっていた部分を日本語化。

### Motivation

違和感を減らす。

### Additional details

> より詳細な例については[Usage](https://developer.mozilla.org/ja/docs/Web/API/console#usage)（[console](https://developer.mozilla.org/ja/docs/Web/API/console) 内）をご参照下さい。

の部分について、consoleのページ中にUsageという節は無さそうでした。これは英語版でも無さそうでした。

### Related issues and pull requests

Relates to mdn/content#22398

2022-11-19 00:38 UTC, mfuji09 requested changes
2件を確認してください。
なお、表記方法のガイドラインは以下のページをお読みください。

https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline

2022-11-19 00:38 UTC, mfuji09 commented on files/ja/web/api/window/console/index.md
> +> **メモ:** 現在はブラウザ間で多くの実装の違いがありますが、それらを統合して互いの一貫性を高める作業が進められています。
「ブラウザ」は「ブラウザー」と長音表記してください。

2022-11-19 00:38 UTC, mfuji09 commented on files/ja/web/api/window/console/index.md
> +| 仕様書                                | 状態                             | 備考                 |
「仕様書」の表は、英語版と同じマクロを使用してください。

2022-11-19 01:02 UTC, mikecat commented
@mfuji09 ありがとうございます。修正しました。

2022-11-20 02:42 UTC, mfuji09 approved these changes
OKです。

2022-11-20 02:42 UTC, merged