fix: event at target order(修复事件在 AT_TARGET 阶段的顺序问题)
mdn/translated-content pull request #999
Opened 2021-05-27 10:28 UTC by hua1995116

详情可以看

https://github.com/mdn/content/pull/5221/commits/f6b7351532fbc3bea3ef22e309a3e25f4b1e6044

已经在英文文档中进行了修改，中文文档同步修改。

2021-05-31 07:48 UTC, irvin commented
你的修改在原文的最終版本* 中沒有對應的修改， https://github.com/mdn/content/commit/f6b7351532fbc3bea3ef22e309a3e25f4b1e6044 沒有進入原文版的主線喔。

* https://github.com/mdn/content/blob/main/files/en-us/web/api/eventtarget/addeventlistener/index.html

2021-05-31 07:49 UTC, irvin requested changes
請提供原文下的連結，謝謝
https://github.com/mdn/content/blob/main/files/en-us/web/api/eventtarget/addeventlistener/index.html

2021-05-31 07:51 UTC, hua1995116 commented
https://github.com/mdn/content/blob/main/files/en-us/web/api/eventtarget/addeventlistener/index.html#L98-L100 @irvin

2021-05-31 07:51 UTC, hua1995116 commented
diff https://github.com/mdn/content/commit/9563e5a1e90069db112682e2051a3fbb8b0ae07f#diff-79dd41e9249e6f18dfdd8943fd37356a50c639a045f4f9e0a89c0ce5ea6c22b3

2021-05-31 16:05 UTC, irvin requested changes

2021-05-31 16:05 UTC, irvin commented on files/zh-cn/web/api/eventtarget/addeventlistener/index.html
> +<div class="note"><strong>注意:</strong> 对于事件目标上的事件监听器来说，事件会处于“目标阶段”，而不是冒泡阶段或者捕获阶段。在目标阶段，"捕获"事件监听器触发将优先于非"捕获"事件（在 Chrome 89.0.4363.0 以及之后版本）。在 Chrome 旧版本(89.0.4363.0之前，不包含当前版本)中，在目标阶段的事件会按照事件注册顺序依次触发，而
相對於原文所多出來的版號等敘述請移除，我們原則上希望維持中英文版本內容的一致性。

2021-05-31 16:09 UTC, hua1995116 commented on files/zh-cn/web/api/eventtarget/addeventlistener/index.html
> +<div class="note"><strong>注意:</strong> 对于事件目标上的事件监听器来说，事件会处于“目标阶段”，而不是冒泡阶段或者捕获阶段。在目标阶段，"捕获"事件监听器触发将优先于非"捕获"事件（在 Chrome 89.0.4363.0 以及之后版本）。在 Chrome 旧版本(89.0.4363.0之前，不包含当前版本)中，在目标阶段的事件会按照事件注册顺序依次触发，而
好的

2022-07-06 02:40 UTC, yin1999 approved these changes

2022-07-06 02:43 UTC, merged